### ISSUE TITLE
Possibility to add Cancel button in the form

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#10001]
Sometimes a "Cancel" button would be good to have in a form, but there is no easy way to currently add it.
As context/reference and to know what is meant with this issue, see the following image and the requirement to have the 'Cancel' button (additionally to also a possibility to call the button "Save" differently, in this case 'Confirm' -- which is already possible) :
![image](https://github.com/pkp/pkp-lib/assets/378421/3e4bff23-e769-4c4d-a2bc-7c34fadd3639)

**Comment by blesildaramirez** [comment]
Pull requests:
pkp-lib:main: https://github.com/pkp/pkp-lib/pull/10125
ui-library:main https://github.com/pkp/ui-library/pull/367
