### ISSUE TITLE
The setSpec of the OAI-PMH endpoint shouldn't contain reserved URI characters

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#10006]
**Describe the bug**
[According to the specification](https://www.openarchives.org/OAI/openarchivesprotocol.html#Set), the setSpec attribute shouldn't contain [reserved URI characters](https://www.ietf.org/rfc/rfc2396.txt#:~:text=2.2.%20Reserved%20Characters). We're using the `urlencode()` which replaces spaces by `+`, which is on the reserved list.

**What application are you using?**
OJS 3.3

**Comment by nils-stefan-weiher** [comment]
Related to https://github.com/pkp/pkp-lib/issues/4235. The issue was fixed for 3.4 but not 3.3.

**Comment by asmecher** [comment]
Thanks for the reminder, @nils-stefan-weiher!

@jonasraoni, there's [a note](https://github.com/pkp/pkp-lib/issues/4235#issuecomment-1164498750) on why I didn't back-port the fix for #4235 over to `stable-3_3_0`. I'll close this as a duplicate.
