### ISSUE TITLE
Usage event plugin should not use public ids

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#1001]
Currently it is passing to any plugin registered against its hook the usage event with the url containing the public id, if the accessed object has one. To make sure that the log files can be processed any time, we should only use OJS internal ids, so if the public ids are changed, the old log files will still be enough to retrieve the object.

**Comment by beghelli** [comment]
Will implement a quick fix, but if the chances to have a public id that might direct to an internal id is high, we can implement this more complex solution:
1 - use the unique site id to identify the usage logs created by the system;
2 - make sure that the usage stats loader knows when it's processing an OJS usage event log file;
3 - avoid retrieving objects using public ids on that case;
4 - create a tool to replace all public ids by OJS internal ones on the previous usage log files;

We avoid using the getByBestId method when we can make sure that ids are all internal ones. That way we make sure we don't accidentally get a wrong object with a public id that matches another object internal id. We also leave the option to use apache log files, although this case will still have the problem of not being able to reprocess old log files if the public ids are changed.

**Comment by beghelli** [comment]
@asmecher Do you think that we need to worry about the chances to have a public id that might direct to an internal id?

**Comment by asmecher** [comment]
@beghelli, do you mean a numeric public identifier?

**Comment by beghelli** [comment]
@asmecher Yes, someone could use a numeric one that clashes with internal ones right? I mean, it's something we should worry?

**Comment by asmecher** [comment]
I think we should actually prevent users from entering purely numeric custom IDs. It would be an easy enough test and IMO there's no good reason to break our necks trying to come up with rules for handling that kind of ambiguity.

**Comment by beghelli** [comment]
nice, I can implement that then :) thanks.

**Comment by asmecher** [comment]
@beghelli, did this one get completed? It looks like it did...

**Comment by beghelli** [comment]
@asmecher yes, it's completed by @mfelczak work. Thanks Michael :). Closing.
