### ISSUE TITLE
Fatal error changing site primary locale

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#10017]
**Describe the bug**
When changing a site's primary locale, OJS attempts to back-fill missing required data using the previous primary locale. For example, a site with an English primary language site will require users to enter their given names in English, with other languages being optional. If that primary locale later gets changed to e.g. French, then OJS will copy English-language primary names into the French field where it is not filled in.

In `lib/pkp/classes/user/DAO.php`, this is implemented in [`changeSitePrimaryLocale`](https://github.com/pkp/pkp-lib/blob/011ebb8c2ea29a01729e1420723cb39fd70180b2/classes/user/DAO.php#L292).

However, it's possible that there is already a row for the given name field for the new language, but its value is blank. The [check for a value not being empty](https://github.com/pkp/pkp-lib/blob/011ebb8c2ea29a01729e1420723cb39fd70180b2/classes/user/DAO.php#L324) does not distinguish between a nonexistent row and an empty setting value. This causes a fatal error:

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '98676-en-givenName' for key 'user_settings_unique' in .../lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:545
Stack trace:
#0 .../lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): PDOStatement->execute()
#1 .../lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('INSERT INTO use...', Array)
#2 .../lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('INSERT INTO use...', Array, Object(Closure))
#3 .../lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(546): Illuminate\\Database\\Connection->run('INSERT INTO use...', Array, Object(Closure))
#4 .../lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(498): Illuminate\\Database\\Connection->statement('INSERT INTO use...', Array)
#5 .../lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(469): Illuminate\\Database\\Connection->insert('INSERT INTO use...', Array)
#6 .../htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Database\\DatabaseManager->__call('insert', Array)
#7 .../lib/pkp/classes/user/DAO.php(324): Illuminate\\Support\\Facades\\Facade::__callStatic('insert', Array)
#8 .../lib/pkp/controllers/grid/admin/languages/AdminLanguageGridHandler.php(356): PKP\\user\\DAO->changeSitePrimaryLocale('pt_BR', 'en')
#9 [internal function]: PKP\\controllers\\grid\\admin\\languages\\AdminLanguageGridHandler->setPrimaryLocale(Array, Object(APP\\core\\Request))
#10 .../lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\\core\\Request))
11 .../lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\\core\\Request), Array)
#12 .../lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPComponentRouter->route(Object(APP\\core\\Request))
#13 .../lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))
#14 .../index.php(21): PKP\\core\\PKPApplication->execute()
#15 {main}

**To Reproduce**
Steps to reproduce the behavior:
1. Set up an OJS installation with two languages enabled.
2. Go to your profile form. Make sure the secondary language has a blank "given name" and save the profile.
3. Go to Administration, find the Languages page, and attempt to change the primary language to something else.
4. See error in PHP log.

**What application are you using?**
 OJS, OMP or OPS version 3.4.0-x

(Reported by SciELO)

**Comment by Hafsa-Naeem** [comment]
@asmecher, I've updated the [PR#10052](https://github.com/pkp/pkp-lib/pull/10052) for another review.

**Comment by asmecher** [comment]
I got the reproduce steps wrong for this. These should work, @Hafsa-Naeem:

1. Load the [datasets repo database](https://github.com/pkp/datasets) for `stable-3_4_0`.
2. Log in as `admin` / `admin`.
3. Go to the user's profile and enter `0` for the French-language given name.
4. Go to Administration > Site Settings > Languages
5. Try to change the primary language from English to French

**Comment by Hafsa-Naeem** [comment]
Ready for review @asmecher 
PR
OJS_3_4_0 [pkp/pkp-lib#10017 Handle duplicate entries in user settings when changing site primary locale ](https://github.com/pkp/pkp-lib/pull/10088)

**Comment by asmecher** [comment]
Thanks, @Hafsa-Naeem -- commented: https://github.com/pkp/pkp-lib/pull/10088#issuecomment-2181317504

**Comment by Hafsa-Naeem** [comment]
@asmecher  I've updated the [PR#10088](https://github.com/pkp/pkp-lib/pull/10088) and ready for another review.

**Comment by asmecher** [comment]
Nice work on this one, @Hafsa-Naeem! Please forward-port to `main`, then we can get it closed off.

**Comment by Hafsa-Naeem** [comment]
Thank you @asmecher! I've forward-ported the changes to the `main` in [PR #10137.](https://github.com/pkp/pkp-lib/pull/10137)

**Comment by asmecher** [comment]
All merged, thanks -- closing!
