### ISSUE TITLE
[OJS 3.4.0] Error ordering issues by date published using API

### ISSUE THREAD

**Issue by thiagolepidus** [pkp/pkp-lib#10012]
**Describe the bug**
Ordering issues by date published returns the error: "One of ORDERBY_* constants must be provided"

**To Reproduce**
Access the API via the 'api/v1/issues?orderBy=datePublished' endpoint on an OJS server

**What application are you using?**
 OJS version 3.4.0

**Additional information**
The error occurs because although the API [supports the parameter](https://github.com/pkp/ojs/blob/stable-3_4_0/api/v1/issues/IssueHandler.php#L128), ordering by date published is not implemented in the [Collector](https://github.com/pkp/ojs/blob/stable-3_4_0/classes/issue/Collector.php#L140) class.

**Comment by asmecher** [comment]
Merged and cherry-picked forward to `main` -- thanks!
