### ISSUE TITLE
Error on the Plugin Gallery Page when the PKP Site is Down

### ISSUE THREAD

**Issue by YvesLepidus** [pkp/pkp-lib#10036]
**Describe the bug**

The  [PluginGalleryGridHandler](https://github.com/pkp/pkp-lib/blob/62bf1b18a865a6019d6d33f061fb053f063ea722/controllers/grid/plugins/PluginGalleryGridHandler.inc.php) class contains snippets that are susceptible to *Guzzle* exceptions.
We have noticed that the [loadData](https://github.com/pkp/pkp-lib/blob/62bf1b18a865a6019d6d33f061fb053f063ea722/controllers/grid/plugins/PluginGalleryGridHandler.inc.php#L124), [viewPlugin](https://github.com/pkp/pkp-lib/blob/62bf1b18a865a6019d6d33f061fb053f063ea722/controllers/grid/plugins/PluginGalleryGridHandler.inc.php#L176) and [installPlugin](https://github.com/pkp/pkp-lib/blob/62bf1b18a865a6019d6d33f061fb053f063ea722/controllers/grid/plugins/PluginGalleryGridHandler.inc.php#L251) methods need exception handling for potential connection errors, whether *5xx* or *4xx*.

Issue related: #10018

**What application are you using?**
 OJS version 3.3.0.17

**Affected versions**
`3.3.0.x` and `3.4.0.x`

**Solution**
We are proposing exception handling in these snippets. [PR](https://github.com/pkp/pkp-lib/pull/10035)

**Comment by asmecher** [comment]
Thanks, @YvesLepidus, I've merged the PR to `stable-3_3_0`. Are you able to forward-port this to `stable-3_4_0`?

**Comment by asmecher** [comment]
Never mind, I went ahead and forward-ported to `stable-3_4_0` and `main`. Thanks, @YvesLepidus!
