### ISSUE TITLE
Upgrade script for existing default masthead roles and user assignments

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#10041]
Existing default masthead roles (editor, section editor and reviewer) should be considered to be displayed on the masthead.
All existing user-role assignments -- not only assignments to the masthead roles, but to all roles -- should be also considered to be displayed on the masthead.

PRs:
- https://github.com/pkp/pkp-lib/pull/10042
- https://github.com/pkp/ojs/pull/4309
- https://github.com/pkp/omp/pull/1591
- https://github.com/pkp/ops/pull/703

**Comment by bozana** [comment]
@asmecher, could you please review the PRs above?
Thanks a lot!

**Comment by asmecher** [comment]
Please go ahead, @bozana. My only thought is that we haven't considered OMP, where there are also internal reviewers that should possibly be listed. It might be worth checking with John about that.

**Comment by bozana** [comment]
Good catch, @asmecher! -- I currently do not differentiate between internal and external reviewers for display -- I just consider all reviewers from `review_assignments` table that have completed a review -- but I have not marked the role "Internal Reviewer" to be considered on the masthead :-\
I asked John and will repair accordingly...
Thanks a lot!
