### ISSUE TITLE
[OJS] remove unused locale files/non-existent plugins

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1004]
OJS contains locale code for three plugins that haven't been published. Translators have translated the en_US files. Having locale files for non-existent plugins is not good, and this situation could be resolved by:

* removing the three plugin folders from the ojs-dev-2_4 branch or by
* releasing the three plugins

The missing plugins are 
* `plugins/blocks/recentArticles`
* `plugins/generic/relatedVideos`
* `plugins/paymethods/moneris`

**Comment by asmecher** [comment]
I suppose these are maintained outside of the official git repository? If that's the case, and they're 3rd-party plugins, we should direct the translators to send those back to the respective repositories. If it's our own repos, we could facilitate. But in any case, those locale files should be removed from the OJS repo.

**Comment by jmacgreg** [comment]
Hey guys, 

Apologies, this was my bad, committing code by mistake; they should be deleted outright. 

J

**Comment by mtub** [comment]
ok. I will take care of it.
