### ISSUE TITLE
[OMP] Review ONIX export for calls to get localized data

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#10046]
**Describe the bug**
The ONIX plugin has calls to `getLocalized`... functions, which will get localized data based on the exporting user's current locale.

Metadata exports shouldn't depend on the current locale. In cases where the exporting standard doesn't support multilingual data, it's better to rely on the publication's primary locale (`$publication->getData('locale')`) in deciding which language to include.

**Comment by kaitlinnewson** [comment]
PRs for review:

- OMP 3.3: https://github.com/pkp/omp/pull/1701
- pkp-lib 3.3: https://github.com/pkp/pkp-lib/pull/10424

@bozana could you review whenever you're able? There's one issue I'm seeing that maybe we can take a look at together and I've made a note in the PR. 

Will forward-port once ready.

**Comment by bozana** [comment]
Hi @kaitlinnewson, I took a look and left a few comments... We can see them today together, if you want... :-)

**Comment by bozana** [comment]
@kaitlinnewson, great, thanks a lot!
I left just one minor comment :-)
We can then merge...

**Comment by kaitlinnewson** [comment]
@bozana I've updated the PR - ready to merge!

**Comment by kaitlinnewson** [comment]
@bozana Forward-ported and the PRs are linked above.

**Comment by bozana** [comment]
All merge, thanks a lot @kaitlinnewson!
