### ISSUE TITLE
Introduce Author::add::before hook

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#10053]
Introduce the new Author::add::before before inserting the author https://github.com/pkp/pkp-lib/blob/4c027a986761e8751df91e85dabeb7e1e498573d/classes/author/Repository.php#L162

PR:
- ~~https://github.com/pkp/pkp-lib/pull/10054~~ https://github.com/pkp/pkp-lib/pull/9726
- ~~https://github.com/pkp/ojs/pull/4315 (only submodule update)~~

**Comment by bozana** [comment]
Hi @jonasraoni, could you please take a look at this PR? Thanks a lot!

**Comment by forgive38** [comment]
Hello,
il this PR is validated, you can close  #
 #9726

**Comment by bozana** [comment]
Ah, I was not aware (and have not searched) of that PR... :-\
Thanks @forgive38!

**Comment by bozana** [comment]
Thanks a lot!
I merged the PR from @forgive38, and closed my PRs...
Will close the issue...
