### ISSUE TITLE
[OJS 3.4] you can add an empty keyword

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#10056]
**Describe the bug**
Keywords are free text, but you can enter just a space character.
I think OJS must check the content of a keyword

**To Reproduce**
Go to a submission, keywords field: type a "space" and select it. You get an empty - more precisely only a space - keyword

**What application are you using?**
 OJS 3.4 testdrive / Firefox

Thank you

**Comment by Hafsa-Naeem** [comment]
Ready for review @asmecher 
PR
OJS_main: [pkp/pkp-lib##10056 Prevent dropdown from taking whitespace input in autosuggest
](https://github.com/pkp/ui-library/pull/372)

**Comment by asmecher** [comment]
Thanks, @Hafsa-Naeem -- passing to @jardakotesovec to review.

**Comment by Hafsa-Naeem** [comment]
@jardakotesovec Updated the [PR#372](https://github.com/pkp/ui-library/pull/372) and it's ready for review again

**Comment by jardakotesovec** [comment]
Merged to main - @asmecher do you want to fix it for 3.4 as well? Just to note - 3.4 is using different components (from vue2 ecosystem)

**Comment by asmecher** [comment]
I think I'd be OK with leaving the fix for just `main`, if it's not a trivial backport.
