### ISSUE TITLE
Incorrect handling of HTML entity code &amp; in OJS email subject

### ISSUE THREAD

**Issue by Hafsa-Naeem** [pkp/pkp-lib#10051]
**Describe the bug**
When sending emails from OJS, the HTML entity `&amp;` is displayed as `&amp;` in the email subject instead of `&`.

**To Reproduce**
1. Configure OJS to send an email with a subject containing `&`.
2. Observe that the subject in the received email contains `&amp;` instead of `&`.

**What application are you using?**
  OJS 3.3.0.13

**Additional information**
Reference forum post: [HTML entity code &amp; in OJS email subject](https://forum.pkp.sfu.ca/t/html-entity-code-amp-in-ojs-email-subject/88673)

**Comment by Hafsa-Naeem** [comment]
Ready for review @asmecher 

### PRs

- [PR #10052 Fixed HTML entity code &amp; in OJS email subject](https://github.com/pkp/pkp-lib/pull/10052)
- [PR #4314  Update submodule reference](https://github.com/pkp/ojs/pull/4314)

**Comment by asmecher** [comment]
Thanks, @Hafsa-Naeem! I've suggested a change [here](https://github.com/pkp/pkp-lib/pull/10052#discussion_r1639960052).

**Comment by asmecher** [comment]
https://github.com/pkp/pkp-lib/pull/10052 looks great, thanks! Just [one minor comment](https://github.com/pkp/pkp-lib/pull/10052/files#r1640292392), then it's ready for forward-porting to `stable-3_4_0` and `main`.

https://github.com/pkp/ojs/pull/4314 looks good, but it's now a collection of several commits; it's a good habit to squash these together so that submodule updates don't get spread in with other changes.

**Comment by Hafsa-Naeem** [comment]
@asmecher I've updated the [PR#10052](https://github.com/pkp/pkp-lib/pull/10052) and am ready for another review.

**Comment by asmecher** [comment]
I merged https://github.com/pkp/pkp-lib/pull/10052, thanks! I'll update the submodule has manually. Please go ahead and forward-port this to `stable-3_4_0` and `main`.

**Comment by Hafsa-Naeem** [comment]
Thank you! I'll forward-port changes to `stable-3_4_0` and `main`.

**Comment by Hafsa-Naeem** [comment]
Ready for review @asmecher
### PRs

- OJS 3_4_0 [pkp/pkp-lib#10051 Fixed HTML entity code &amp; in OJS email subject #10058](https://github.com/pkp/pkp-lib/pull/10058)
- OJS main [pkp/pkp-lib#10051 Fixed HTML entity code &amp; in OJS email subject #10059](https://github.com/pkp/pkp-lib/pull/10059)

**Comment by Hafsa-Naeem** [comment]
Ready for review again with fix for "[empty subject not triggering  a warning](https://github.com/pkp/pkp-lib/pull/10058#discussion_r1640914629)" @asmecher

### PR
OJS 3_4_0: [pkp/pkp-lib#10051 Fixed HTML entity code &amp; in OJS email subject](https://github.com/pkp/pkp-lib/pull/10058)

**Comment by asmecher** [comment]
Thanks, I've added [a comment](https://github.com/pkp/pkp-lib/pull/10058#discussion_r1643307819); I think this will also need syncing forward from `stable-3_4_0` to `main` once you've looked it over.

**Comment by Hafsa-Naeem** [comment]
@asmecher  Ready for review again.

PR: 
OJS 3_4_0: [pkp/pkp-lib#10051 Fixed HTML entity code &amp; in OJS email subject #10058](https://github.com/pkp/pkp-lib/pull/10058)

**Comment by asmecher** [comment]
Thanks, @Hafsa-Naeem, but I see there's now a merge conflict; I've asked @jonasraoni for feedback [here](https://github.com/pkp/pkp-lib/pull/10058#discussion_r1643494179).

**Comment by Hafsa-Naeem** [comment]
@asmecher I've suggested a solution [here](https://github.com/pkp/pkp-lib/pull/10058#discussion_r1644730101) regarding the feedback from you and @jonasraoni . Please review and let me know your thoughts.

**Comment by asmecher** [comment]
Aaaaalmost there, thanks, @Hafsa-Naeem! Can you update the [PR for `main`](https://github.com/pkp/pkp-lib/pull/10059) so it's synced with the [changes you made in `stable-3_4_0`](https://github.com/pkp/pkp-lib/pull/10058)?

**Comment by Hafsa-Naeem** [comment]
@asmecher updated the PR for OJS main: [ pkp/pkp-lib#10051 Fixed HTML entity code &amp; in OJS email subject #10059](https://github.com/pkp/pkp-lib/pull/10059)

**Comment by asmecher** [comment]
Thanks, @Hafsa-Naeem, all merged!
