### ISSUE TITLE
Publishing an issue uses the incorrect email template

### ISSUE THREAD

**Issue by salmanm2003** [pkp/pkp-lib#10069]
Hi @asmecher,
When an issue is published, OJS uses the incorrect email template NOTIFICATION to notify users instead of the correct template, PUBLISH_NOTIFY.

**To Reproduce**
1. Go to 'Issues'
2. Click on 'publish issue'
3. Tick ' Send an email about this to all registered users'
4. The recieved email template is 'NOTIFICATION' instead of 'PUBLISH_NOTIFY' 

 I am using OJS 3-3-0_17

Here is the PR:
[https://github.com/pkp/ojs/pull/4322](https://github.com/pkp/ojs/pull/4322)

**Comment by asmecher** [comment]
@salmanm2003, this is a duplicate of https://github.com/pkp/pkp-lib/issues/3646 -- there are details on its status (and a link to a resolution for 3.5.0) there.
