### ISSUE TITLE
Custom report generator leaves Issue Galleys untranslated

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1007]
Steps to reproduce:
* OJS 2.4.7, with published and accessed Issue Galleys
 * User Home -> Journal Manager -> Stats and Reports
 * Generate Custom Report
 * Change Report Template to "Issue File Galleys"
 * "Generate custom report"

Expected Result:
* "Type" column values are translated.

Actual Result:
* "Type" column values are "##editor.issues.galley##"

**Comment by beghelli** [comment]
Already merged, checking if needs porting to master. Closing.
