### ISSUE TITLE
Consider only external reviewers for display on Editorial Masthead page

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#10080]
Only external reviewers should be considered for display on the Editorial Masthead page.
Especially in OMP, also internal reviewers exist and they should not be considered for display on the Editorial Masthead page.

PRs:
- https://github.com/pkp/pkp-lib/pull/10081
- https://github.com/pkp/ojs/pull/4326
- https://github.com/pkp/omp/pull/1596
- https://github.com/pkp/ops/pull/707

**Comment by bozana** [comment]
@asmecher, could you please take a look at the PRs above?
Thanks a lot!

**Comment by bozana** [comment]
Hi @asmecher, could you please review the PRs above?
Thanks a lot!

**Comment by asmecher** [comment]
Please go ahead, thanks, @bozana!
