### ISSUE TITLE
Add tests for ORCID integration

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#10127]
The current ORCID functionality has minimal testing. Both integration and unit tests should be added.

- [ ] Job integration tests
- [ ] e2e cypress testing for as much functionality as possible

Open questions:

- How to mock ORCID API endpoints/OAuth process?

See #9899 for job test references

PRs (🚧 in progress):

- `pkp-lib`: #10148

**Comment by taslangraham** [comment]
@ewhanson I opened draft PRs with some e2e tests. Please take a look when you can:
pr - https://github.com/pkp/pkp-lib/pull/10524/files
ojs [tests] - https://github.com/pkp/ojs/pull/4472

**Comment by taslangraham** [comment]
@ewhanson I've updated e2e tests to work for OJS, OPS, and OMP. PRs, ready for review:

[pkp-lib](https://github.com/pkp/pkp-lib/pull/10524)
https://github.com/pkp/ops/pull/819
https://github.com/pkp/omp/pull/1777
https://github.com/pkp/ojs/pull/4472

**Comment by ewhanson** [comment]
Thanks @taslangraham, all merged!
