### ISSUE TITLE
Minor cleanup/refactor for ORCID integration

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#10131]
The ORCID refactor from #9771 left a few areas where code duplication/reuse could be improved.

- [ ] Refactor `OrcidController` to abstract more "common sense" checks
- [ ] Abstract out `OrcidManager::getApiTypes() in some form (see [note from original PR](https://github.com/pkp/pkp-lib/pull/9818#discussion_r1618847585)).

**Comment by taslangraham** [comment]
I've added a PR for this @ewhanson.
###PRs 
- pkp-lib: https://github.com/pkp/pkp-lib/pull/10370
**Submodule updates**
- OPS: https://github.com/pkp/ops/pull/765
- OJS: https://github.com/pkp/ojs/pull/4428
- OMP: https://github.com/pkp/omp/pull/1692

**Comment by ewhanson** [comment]
Thanks @taslangraham, all merged!
