### ISSUE TITLE
Add API documentation for ORCID endpoints

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#10130]
New API endpoints were added when ORCID functionality was integrated into the core application (see: #9771. OpenAPI documentation still needs to be added for these endpoints.

**Comment by taslangraham** [comment]
Added a PR for this @ewhanson 
PR - https://github.com/pkp/ojs/pull/4453

**Comment by ewhanson** [comment]
Merged! Thanks @taslangraham.
