### ISSUE TITLE
[OMP] Add option to disable validation in Onix export plugin

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10132]
Currently validation is always enforced in the Onix export plugin, but we want to add the option to disable it in order to ensure that the export can still be done when there may be metadata gaps. 

This currently exists in some other plugins, such as the DOAJ Export plugin.

**What application are you using?**
OMP 3.3/3.4/main

**Additional information**

Example from the DOAJ plugin:

![Screenshot 2024-06-26 at 1 20 10 PM](https://github.com/pkp/pkp-lib/assets/6903515/b625700c-3cb1-4986-a206-b4c210e24033)

**Comment by kaitlinnewson** [comment]
PRs for review, and will be forward-ported once approved:
- OMP 3_3_0: https://github.com/pkp/omp/pull/1624

If you want to force validation to break in the exports, you can replace the xsd schema files in `plugins/importexport/onix30` with [the latest versions (3.0.8)](https://www.editeur.org/files/ONIX%203/ONIX_BookProduct_3.0_XSDs+codes_Issue_65.zip).

@bozana would you be able to review?

One thing I had a question about is in the locale files. I copied over a locale key that is currently in OJS only - does it make sense to move this key into `pkp-lib`, or are duplicate keys in OJS and OMP acceptable? If duplicates are okay, then I can copy over the translations as well.

**Comment by bozana** [comment]
Hi @kaitlinnewson, I was traveling but am now back and will take a look at this soon... Thanks!

**Comment by kaitlinnewson** [comment]
Thanks @bozana - I'm looking at moving the locale key to pkp-lib so not ready to merge yet, but if you have time to review that would be great

**Comment by kaitlinnewson** [comment]
@bozana I've made the locale key changes and added them to the list of PRs above, ready for review on OMP 3_3_0

**Comment by bozana** [comment]
@kaitlinnewson, @asmecher has updated all locales. Could you please rebase? Then we will merge.
Thanks a lot!

**Comment by kaitlinnewson** [comment]
@bozana rebase is done for 3_4_0 and main (no changes in 3_3_0) - let me know if you see any issues as I haven't used rebasing very much before.

Working on forward-porting now and will update when that's done.

**Comment by bozana** [comment]
Hi @kaitlinnewson, I have just merged everything from here. Would you now like to port OMP changes to stable-3_4_0 and main?

**Comment by kaitlinnewson** [comment]
@bozana I've ported to 3_4_0 and main and added them to the list above. The PRs are slightly different from the changes in 3_3_0 as some things were moved to being handled in pkp-lib between the versions.

**Comment by bozana** [comment]
All merged, thus closing...
