### ISSUE TITLE
Consider TSV as API response

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#10145]
Within the issue https://github.com/pkp/pkp-lib/issues/9666 -- that is the migration of the issue https://github.com/pkp/pkp-lib/issues/8248 to the main -- the TSV as API response needs to be implemented.

S. also: https://github.com/pkp/pkp-lib/commit/2f9966308e3e69b9f5b125a9f20f5c1846dbf53f

PRs:
- https://github.com/pkp/pkp-lib/pull/10146
- https://github.com/pkp/ojs/pull/4345
- https://github.com/pkp/omp/pull/1621 (only submodule update)
- https://github.com/pkp/ops/pull/722 (only submodule update)

**Comment by bozana** [comment]
@touhidurabir, could you please review the PR above? I can gladly solve it differently -- e.g. put it at another place -- if needed.
Thanks a lot!

**Comment by bozana** [comment]
@touhidurabir, I have now changed it accordingly. Could you please take another look?
Thanks a lot!

**Comment by touhidurabir** [comment]
@bozana looks great . should be good to merge .
