### ISSUE TITLE
Firefox does not correctly save named files

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#10154]
**Describe the bug**
From [the forum](https://forum.pkp.sfu.ca/t/issue-with-file-naming-in-ojs-3-3-0-8-underscores-added-to-downloaded-files/89136/3):
> When I try to download a file from the editing interface, while the files are still in Review/Copyediting, etc., the file is saved with an underscore at the beginning and the end:
> `myfile.docx`
> becomes
> `_myfile.docx_`
> and for some users, this is a significant issue because they are unable to open the files.

This appears to affect only Firefox.

**What application are you using?**
 OJS, OMP or OPS version 3.3.0 and later

**Additional information**
- https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http
- https://stackoverflow.com/questions/22477273/firefox-and-chrome-appending-underscore-before-and-after-file-name-while-interne
- https://www.rfc-editor.org/rfc/rfc2616#section-3.6

**Comment by ronste** [comment]
Hi @asmecher ,

I just updated one of our installation to 3.3.0-20 in the hope to fix this issue in the context of the citation style language plugin but it didn't work:

See, e.g., here: [https://www.berliner-blaetter.de/index.php/blaetter/article/view/1167](https://www.berliner-blaetter.de/index.php/blaetter/article/view/1167)

The code as of the patch mentioned above is there. I deleted all caches I am aware of (i.e. browser, server cache folder and those on the OJS admin page).

Any further ideas?

**Comment by ronste** [comment]
Update: I had a look at the citationStyleLanguage plugin. In that case the header is written at:

https://github.com/pkp/citationStyleLanguage/blob/b1f6c23d0bb1c2e69ef349fd729cf097a6517d83/CitationStyleLanguagePlugin.php#L654

The plugin (even in version 3.5rc2) still contains the ' \\" ' in the header.

**Comment by bozana** [comment]
https://github.com/pkp/citationStyleLanguage/pull/149
https://github.com/pkp/citationStyleLanguage/pull/150
