### ISSUE TITLE
Error Message Persisting During Final Step of Submission Process Despite Deletion and Restoration of Default Components in Components Set-up

### ISSUE THREAD

**Issue by aqaissi1** [pkp/pkp-lib#10162]
**Describe the bug**
In the final step of the submission process, "Review Submission," an error message appears. The message states: "You must upload at least one of each of the following file types: Research Note, Policy Brief, Book Review, Article, Research Article." These file types are actually Sections I created by mistake in the Components Set-up. Despite deleting these sections and restoring the default components, the error persists.

**What application are you using?**
 OJS 3.4.0.3

**Additional information**
Screenshots of the error
<img width="885" alt="error 2" src="https://github.com/pkp/pkp-lib/assets/174733619/b9290023-1125-4ed9-9baf-cebc9ad034bb">
<img width="928" alt="Error 1" src="https://github.com/pkp/pkp-lib/assets/174733619/b3e35be7-d73f-4c29-b2c4-dc16184db18d">

**Comment by asmecher** [comment]
@aqaissi1, you should be able to fix this by applying [this change](https://github.com/pkp/pkp-lib/commit/358730f20465417b8df082731543d4d6e55beee8) in `lib/pkp`.

**Comment by aqaissi1** [comment]
Thanks a lot! That was helpful.
