### ISSUE TITLE
Right sidebar needs to be removed

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1016]
Right now the sidebar will still appear if blocks are added to it, and it isn't laid out properly on the page. We still need to discuss where we want to go with the sidebars, but at least for OMP 1.2 we'll need to remove it from the frontend and should remove the ability to add blocks to it in the settings panel.

**Comment by asmecher** [comment]
Removed.

**Comment by NateWr** [comment]
Just re-opening so I remember to remove the code from the templates (unless you've already done that -- didn't see it).

**Comment by NateWr** [comment]
Ok, [PR[(https://github.com/pkp/pkp-lib/pull/1021) for the remaining right sidebar stuff.

Also, the custom block manager and web feed plugins look like they still have some references:

```
4 results found in 4 files for BLOCK_CONTEXT_RIGHT_SIDEBAR
plugins/generic/customBlockManager/CustomBlockManagerPlugin.inc.php(1)
    93 $blockPlugin->setBlockContext(BLOCK_CONTEXT_RIGHT_SIDEBAR);
plugins/generic/customBlockManager/CustomBlockPlugin.inc.php(1)
    119 if (!Config::getVar('general', 'installed')) return BLOCK_CONTEXT_RIGHT_SIDEBAR;
plugins/generic/webFeed/WebFeedBlockPlugin.inc.php(1)
    63 return array(BLOCK_CONTEXT_LEFT_SIDEBAR, BLOCK_CONTEXT_RIGHT_SIDEBAR);
plugins/generic/customBlockManager/controllers/grid/form/CustomBlockForm.inc.php(1)
    84 $plugin->setBlockContext(BLOCK_CONTEXT_RIGHT_SIDEBAR);
```

**Comment by asmecher** [comment]
Ah -- forgot to commit the submodule repo. I fixed the custom block manager plugin but don't see anything in the web feed plugin; I think that's already corrected.

**Comment by asmecher** [comment]
@NateWr, I've merged your PR; is this ready to close from your perspective?

**Comment by NateWr** [comment]
Yep! Closing.

**Comment by crism** [comment]
This is still present in one OMP-specific file.

**Comment by NateWr** [comment]
Thanks @crism. Can you open a pull request?

**Comment by NateWr** [comment]
It looks like this change has already made it into OMP master. Closing.
