### ISSUE TITLE
[OMP] Onix export record references are not unique for each pub format

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10173]
**Describe the bug**
In the Onix export plugin in OMP, each "product" (publication format) has a `<RecordReference>`. For a publication that has more than one publication format, there will be multiple `<RecordReference>` tags in the output XML.

Currently these are the same for every publication format, but they should be unique for each in order to align with the ONIX standard, and ensure that records can be identified by a unique identifier and differentiated from each other. We should also change how we are setting them to better align with best practices (see link below for more info on recommendations).

If we upgrade to newer versions of Onix, the current implementation will cause validation to fail as it will be enforced in future versions (e.g. 3.0.8).

This is a potentially breaking change, as it changes the identifiers for all of these records once we fix it. It has the potential to create duplicate records if the XML is being imported and is using these tags to check if the record exists already.

**What application are you using?**
OMP 3.3/3.4/main

**Additional information**
- [Location where the RecordReference is set in the Onix export plugin](https://github.com/pkp/omp/blob/927a9358326845a85e153a9af06e6a94f3f51fbc/plugins/importexport/onix30/filter/MonographONIX30XmlFilter.php#L159)
- ["Twelve ONIX problems"](https://www.editeur.org/files/ONIX%203/APPNOTE%20Twelve%20ONIX%20problems.pdf) (see p. 10)

**Comment by bozana** [comment]
Is there a possible solution for the duplicate records? Or is this what will happen however and we cannot do anything?

**Comment by kaitlinnewson** [comment]
Resolved as part of the work done in https://github.com/pkp/pkp-lib/issues/10561. Each ONIX RecordReference is now unique, and is a string combination of server host URL + context path + publication format ID ([see the code on the ONIX plugin for specifics](https://github.com/pkp/omp/blob/main/plugins/importexport/onix30/filter/MonographONIX30XmlFilter.php#L180-L186)).

**Comment by asmecher** [comment]
@kaitlinnewson and @bozana, if this gets resolved in the next couple hours it can go out with 3.4.0-8; otherwise I'll defer to 3.4.0-9. Up to you two if you think it's ready!

**Comment by bozana** [comment]
Hi @kaitlinnewson, PR for 3.4 is merged. Can this issue be closed?
Thanks a lot!
