### ISSUE TITLE
Add ORCID ID to the PubMed export plugin

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#10174]
**Describe the bug**
The authors might have ORCID IDs assigned to them, but we're not exporting them at the PubMed plugin.
We might follow the integration receipt available here: https://info.orcid.org/orcid-ids-and-the-nlm-dtd-how-does-it-work/

**What application are you using?**
OJS 3.3

**Comment by jonasraoni** [comment]
@eirikhanssen could you please review the linked micro-PRs (pre-warning to decrease the stress haha)?

**Comment by ewhanson** [comment]
Hey @jonasraoni, happy to have a look. I'm seeing some conflicting information about whether or not the URL would be acceptable based on [various](https://dtd.nlm.nih.gov/ncbi/pubmed/doc/out/180101/el-Identifier.html) [DTDs](https://dtd.nlm.nih.gov/ncbi/pubmed/doc/out/230101/el-Identifier.html). I'll reach out to ORCID to confirm.

**Comment by jonasraoni** [comment]
Great, if you have easy access to them that will simplify my life haha. 
AFAICS, they expect the ID just with the numbers (so I'll have to do an extra update anyway)

**Comment by asmecher** [comment]
@jonasraoni and @ewhanson, I'd like to wrap up 3.3.0-x builds in the next week or so; this is non-criticial so I'll include it if it's ready, but otherwise will defer.

**Comment by jonasraoni** [comment]
Okay! FYI this is a sponsored task.
I'm just waiting for a feedback from @ewhanson. On the [description link](https://info.orcid.org/orcid-ids-and-the-nlm-dtd-how-does-it-work/) and on Google I found some samples using just the ID, without the URL part, but an official confirmation is always welcome.
