### ISSUE TITLE
Port tool to move locale keys to 3.3 branch

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10186]
**Describe the bug**
The tool to move locale keys is not available in the 3.3 branch, making it more challenging to move locale keys in all of the 3.3 branches.

**What application are you using?**
 OJS, OMP, OPS version 3.3.0

**Comment by kaitlinnewson** [comment]
PR for review:

- pkp-lib 3_3_0: https://github.com/pkp/pkp-lib/pull/10187

I just made some minor changes so it would work in 3.3 - ready for review @asmecher.

No forward porting needed as it's already in 3.4/main.

**Comment by asmecher** [comment]
Merged that, thanks!
