### ISSUE TITLE
Convert Queries to an Eloquent model

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#10189]
The Query class (https://github.com/pkp/pkp-lib/blob/stable-3_4_0/classes/query/Query.php) and QueryDAO (https://github.com/pkp/pkp-lib/blob/stable-3_4_0/classes/query/QueryDAO.php) are implemented using the old-style DAO pattern. Migrate to an Eloquent model.

**Comment by kaitlinnewson** [comment]
Hi @asmecher, could you give this PR a review? I'm hitting a wall with some errors I'm seeing in testing and could use a second look!

- Draft PR: https://github.com/pkp/pkp-lib/pull/10384

**Comment by asmecher** [comment]
@kaitlinnewson, what errors are you getting? (Do you have a branch on OJS that's getting github actions kicked off?)

**Comment by kaitlinnewson** [comment]
@asmecher Errors are in manual testing, but I'll also kick off the cypress tests - one I'm running into is when creating a new discussion in some cases, but it's not cropping up consistently:

```
[Thu Sep 12 16:12:14 2024] PHP Fatal error:  Uncaught TypeError: get_class(): Argument #1 ($object) must be of type object, null given in /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/mail/Mailer.php:79
Stack trace:
#0 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/mail/Mailer.php(79): get_class(NULL)
#1 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(257): PKP\mail\Mailer->renderView(NULL, Array)
#2 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(282): Illuminate\Mail\Mailer->render('', Array)
#3 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Mail\Mailable->Illuminate\Mail\{closure}()
#4 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(279): Illuminate\Mail\Mailable->withLocale(NULL, Object(Closure))
#5 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/log/Repository.php(132): Illuminate\Mail\Mailable->render()
#6 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/controllers/grid/queries/QueriesGridHandler.php(689): PKP\log\Repository->logMailable(Object(PKP\log\SubmissionEmailLogEventType), Object(PKP\mail\mailables\DiscussionReview), Object(APP\submission\Submission))
#7 [internal function]: PKP\controllers\grid\queries\QueriesGridHandler->updateQuery(Array, Object(APP\core\Request))
#8 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPRouter.php(329): call_user_func(Array, Array, Object(APP\core\Request))
#9 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPComponentRouter.php(265): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#10 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/Dispatcher.php(158): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#11 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/core/PKPApplication.php(392): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#12 /Users/kaitlinnewson/Code/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#13 {main}
  thrown in /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/mail/Mailer.php on line 79
```

**Comment by asmecher** [comment]
Vitaliy knows that part of the code much better than me -- @Vitaliy-1, any suggestions? At a glance, it looks like it might be a missing mailable/email template.

**Comment by Vitaliy-1** [comment]
At the first glance, here: `#5 /Users/kaitlinnewson/Code/ojs-main/lib/pkp/classes/log/Repository.php(132): Illuminate\Mail\Mailable->render()` the code tries to render (meaning to substitute email variables with real values) email with an empty body. That code changed the last time I worked with it, I think in such cases it was passing an empty string before. But now it's just null, which leads to the fatal error.

**Comment by kaitlinnewson** [comment]
@asmecher I've resolved the errors and this is ready for a first review.

**Comment by jardakotesovec** [comment]
Great! After this is settled, @asmecher would be possible to follow up with the GET api for the queries, so we still have chance to also migrate notifications grid to vue.js? Just for listing. Any POST updates still could go through grid actions for 3.5.

**Comment by asmecher** [comment]
Merged and tests passing! Closing this issue :tada:
