### ISSUE TITLE
Convert Notes to an Eloquent model

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#10188]
The Note class (https://github.com/pkp/pkp-lib/blob/stable-3_4_0/classes/note/Note.php) and NoteDAO (https://github.com/pkp/pkp-lib/blob/stable-3_4_0/classes/note/NoteDAO.php) are implemented using the old-style DAO pattern. Migrate to an Eloquent model.

**Comment by kaitlinnewson** [comment]
@asmecher This is ready for a review: 

- pkp-lib main: https://github.com/pkp/pkp-lib/pull/10268

I did a PR to OJS main for tests and they are failing, but I'm not sure that it's related to my changes - still reviewing the logs:

- OJS main (tests only): https://github.com/pkp/ojs/pull/4385

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson! A few of us have added some suggestions/comments -- this is getting very close to ready.

Looking at the log failures, I picked out the error log artifact from the end of one of the runs. It contains a bunch of repetitions of this:
```
PHP Fatal error:  Class APP\core\Services contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PKP\core\PKPServices::init) in /home/runner/ojs/classes/core/Services.php on line 20
[Thu Aug  1 17:27:51 2024] 127.0.0.1:60172 [500]: GET / - Class APP\core\Services contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PKP\core\PKPServices::init) in /home/runner/ojs/classes/core/Services.php on line 20
```
The abstract `init` function was removed from `PKPServices` [just today](https://github.com/pkp/pkp-lib/commit/4c31a124038bb79d0dfb4fdd0755f17c891c3d28#diff-06f399b2adf99d15ebf0423883a17c9cb1996d0139e5837f0e9a479c8b47aff1L43) -- I think you can resolve this error by...
 - Rebasing the `10188-main` branch of your `pkp-lib` repository on the latest `main`,
 - Force-pushing your newly-rebased `10188-main` branch of `pkp-lib` up to your remote,
 - Rebasing the `10188-main` branch of your `ojs` repository on the latest `main`, making sure to update the `lib/pkp` submodule to the new latest, and finally
 - Force-pushing the newly-rebased `101188-main` branch of OJS up to your remote.

**Comment by kaitlinnewson** [comment]
Thanks for your reviews @taslangraham @jonasraoni and @asmecher - I've implemented/reviewed the feedback and the tests have passed for OJS. This is ready for another review, and should be ready to merge if there is no further feedback.

**Comment by kaitlinnewson** [comment]
@asmecher I've reviewed & implemented your latest feedback, ready for another look/merge!

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson! Just one remaining thing: https://github.com/pkp/pkp-lib/pull/10268#discussion_r1709947478

**Comment by kaitlinnewson** [comment]
@asmecher Done!

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson (and @taslangraham and @jonasraoni) -- I've merged this!
