### ISSUE TITLE
[ojs-3.4.0-5, php 8.3.8.r2] Fatal ERROR 500, blank page on article page preview as well as published pages

### ISSUE THREAD

**Issue by asidibe1** [pkp/pkp-lib#10204]
On the publication tab, the preview lead to a fatal error

![production capture](https://github.com/user-attachments/assets/8dc9604c-ed0b-4778-995b-6c6e32c4f80a)

I use the bootstrap 3 theme

![image](https://github.com/user-attachments/assets/671ec8c7-b1d8-4578-ae21-61e0b726778a)

All the article information was filled manually and the galley files imported

However, the issue can be previewed although the article link still leads to a fatal error 500 or blank page in browsers.

Can you please help me with that?
Best

**Comment by asmecher** [comment]
@asidibe1, please check your PHP error log for details.

**Comment by asidibe1** [comment]
Thank you for your reply. It was finally resolved, it seems that there were conflict with some plugins and the config.
