### ISSUE TITLE
Article PDF viewer does not use rich-formatted titles

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#10208]
Split from https://github.com/pkp/pkp-lib/issues/10138:

The PDF article viewer (https://github.com/pkp/pdfJsViewer) currently uses the plaintext article title when presenting an article galley. Since OJS 3.4.0-x now supports rich text in article titles, this viewer should use the HTML-formatted version of the title instead.

Beware, this feature is also used for issue galleys, which do not yet support HTML in titles! There are two options:

1. Adjust the PDF viewer plugin so that it can handle both plaintext titles from issues, and rich titles from articles.

Or...

2. Adjust the issue galley tools so that they support rich titles as well. (Actually, I don't suggest this just yet.)

**Comment by Hafsa-Naeem** [comment]
@asmecher ready for review
OJS_3_4_0 [pkp/pkp-lib#10208 Article PDF viewer to use rich-formatted titles #72
](https://github.com/pkp/pdfJsViewer/pull/72)

**Comment by asmecher** [comment]
@Hafsa-Naeem, I added [a comment](https://github.com/pkp/pdfJsViewer/pull/72#pullrequestreview-2205322889), thanks!

**Comment by Hafsa-Naeem** [comment]
@asmecher Ready for review again.
**PR:**
OJS_3_4_0: [pkp/pkp-lib#10208 Article PDF viewer to use rich-formatted titles](https://github.com/pkp/pdfJsViewer/pull/72)

**Comment by asmecher** [comment]
Thanks, it looks like @jonasraoni has added a review already -- thanks, Jonas.

**Comment by jonasraoni** [comment]
I haven't reviewed this one, anyway, I think it's good when many people take a look at the PRs (to see how the code is evolving and offer more insights).

**Comment by Hafsa-Naeem** [comment]
Ready for review again @asmecher and @jonasraoni 
OJS_3_4_0 [https://github.com/pkp/pdfJsViewer/pull/72](pkp/pkp-lib#10208 Article PDF viewer to use rich-formatted titles #72)

**Comment by Hafsa-Naeem** [comment]
Ready for review again @asmecher and @jonasraoni 
**OJS_3_4_0**: [pkp/pkp-lib#10208 Article PDF viewer to use rich-formatted titles #72](pkp/pkp-lib#10208 Article PDF viewer to use rich-formatted titles #72)

**Comment by Hafsa-Naeem** [comment]
@asmecher ready for review again
OJS_3_4_0: [pkp/pkp-lib#10208 Article PDF viewer to use rich-formatted titles #72
](https://github.com/pkp/pdfJsViewer/pull/72)

**Comment by asmecher** [comment]
@Hafsa-Naeem, with apologies for not scheduling this clearly against 3.5.0 -- could you close the PR and open another against `main`? It looks good, but the changes shouldn't be applied to 3.4.0.

**Comment by Hafsa-Naeem** [comment]
@asmecher I;ve closed the PR in 3.4.0 and applied the changes to main.  It's ready for review
OJS_main: [pkp/pkp-lib#10208 Article PDF viewer to use rich-formatted titles #73
](https://github.com/pkp/pdfJsViewer/pull/73)

**Comment by asmecher** [comment]
@Hafsa-Naeem, I think you'll have to adjust the [Hypothes.is plugin](https://github.com/asmecher/hypothesis) as well to match -- have you had a look at that one?

**Comment by Hafsa-Naeem** [comment]
@asmecher I've updated the code for [Hypothesis](https://github.com/asmecher/hypothesis)
[pkp/pkp-lib#10208 update hypothesis to use displaytpl](https://github.com/asmecher/hypothesis/pull/25)

**Comment by asmecher** [comment]
@Hafsa-Naeem, sorry for letting this one sit so long! It all reviews and tests fine, so I've merged it. Closing, thanks!
