### ISSUE TITLE
Update StageAssignment model to use eloquence HasCamelCasing trait

### ISSUE THREAD

**Issue by taslangraham** [pkp/pkp-lib#10220]
**Describe the bug**
The [eloquence ](https://github.com/kirkbushell/eloquence)package was introduced in pkp-lib via [issue #10129](https://github.com/pkp/pkp-lib/issues/10129). This package provides a [trait](https://github.com/kirkbushell/eloquence/blob/master/src/Behaviours/HasCamelCasing.php) that enables seamless camelCase interaction with Eloquent model attributes, eliminating the need for explicitly defined accessors and mutators.

Update the `StageAssignment` model to leverage the eloquence trait instead of using custom accessors and mutators.

**What application will be affected?**
PKP Lib(main). Potentially OJS, OMP or OPS.

PRs:
pkp-lib main - https://github.com/pkp/pkp-lib/pull/10221/files
ojs main - https://github.com/pkp/ojs/pull/4370/files
omp main - https://github.com/pkp/omp/pull/1646/files
ops main - https://github.com/pkp/ops/pull/733/files

**Comment by taslangraham** [comment]
@asmecher ready for review

**Comment by asmecher** [comment]
All merged, thanks!
