### ISSUE TITLE
Update eloquent models use to HasCamelCasing trait

### ISSUE THREAD

**Issue by taslangraham** [pkp/pkp-lib#10234]
Describe the bug
The [eloquence ](https://github.com/kirkbushell/eloquence)package was introduced in pkp-lib via https://github.com/pkp/pkp-lib/issues/10129. This package provides a [trait](https://github.com/kirkbushell/eloquence/blob/master/src/Behaviours/HasCamelCasing.php) that enables seamless camelCase interaction with Eloquent model attributes, eliminating the need for explicitly defined accessors and mutators.

More models can be updated to use this trait, namely:

- [ ] InvitationModel
- [ ] UserGroupStage
- [ ] UserUserGroup

What application will be affected?
PKP Lib(main). Potentially OJS, OMP or OPS main.

PRs
pkp lib - https://github.com/pkp/pkp-lib/pull/10250
ojs - https://github.com/pkp/ojs/pull/4384
omp - https://github.com/pkp/omp/pull/1661
ops -https://github.com/pkp/ops/pull/742

**Comment by defstat** [comment]
@taslangraham everything merged - I am closing the issue.
