### ISSUE TITLE
[ops-3.4.0-5, php 8.3.8.r2] the latest preprint of the same day not coming on top

### ISSUE THREAD

**Issue by asidibe1** [pkp/pkp-lib#10231]
This is not a reel bug, but I can't find any way to specify the ordering in preprint appearance on the site. In addition, the latest preprint of the day in coming the latest in the order of submission.

Can someone help?
Thanks

**Comment by asmecher** [comment]
@asidibe1, could you post this question on our support forum? https://forum.pkp.sfu.ca
