### ISSUE TITLE
Possible to reach broken dashboard without context

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1024]
It's possible to get to a dashboard without a context at this URL:

`http://192.168.0.8/omp/index.php/index/dashboard`

You can land on it by going to `/index/login` while logged out. Then log in from anther tab. Then go back and reload `index/login` and it will kick you to the index dashboard.

The grids fail to load.

**Comment by asmecher** [comment]
Replicated with an admin account.
