### ISSUE TITLE
Fix usage/implementation of $urlLocaleForPage at the PKPRouter::url()

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#10242]
**Describe the bug**
On the PR https://github.com/pkp/pkp-lib/pull/9628 a parameter called `$urlLocaleForPage` was introduced, but in a couple of places its usage seems to be incorrect or missing something, it's needed to review and apply fixes.

For example, the PKPRouter doesn't have the argument `$urlLocaleForPage`, but it's being used here:
https://github.com/pkp/pkp-lib/blob/c111708049c9ae8246a22a35aa440b6a35d8c7f9/classes/template/PKPTemplateManager.php#L280

**What application are you using?**
OJS 3.5

**Comment by asmecher** [comment]
@ajnyga, heads-up: this is related to https://github.com/pkp/pkp-lib/issues/699

**Comment by ajnyga** [comment]
Thanks, tagging @jyhein here since I can not assign him directly,

**Comment by bozana** [comment]
@jyhein checked it, and now I also roughly went through, and it all seems to be OK -- The PKPPageRouter, also used and for the code mentioned above in the issue, and checked here s. https://github.com/pkp/pkp-lib/blob/c111708049c9ae8246a22a35aa440b6a35d8c7f9/classes/template/PKPTemplateManager.php#L215, does have that parameter.
Thus, I will close the issue...
