### ISSUE TITLE
Update HasRoles middleware to apply site admin role when applicable

### ISSUE THREAD

**Issue by taslangraham** [pkp/pkp-lib#10266]
## Issue Description
See the following comments for context:
https://github.com/pkp/pkp-lib/pull/10258#discussion_r1695897652
https://github.com/pkp/pkp-lib/pull/10258#discussion_r1697679498

PR - https://github.com/pkp/pkp-lib/pull/10267

**Comment by taslangraham** [comment]
@asmecher @touhidurabir I've created a PR for this. Please take a look.
PR - https://github.com/pkp/pkp-lib/pull/10267

**Comment by asmecher** [comment]
Thanks, @taslangraham! @touhidurabir, could you take a first review?
