### ISSUE TITLE
[OMP] undefined constant in WebFeedBlockPlugin

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1027]
```
PHP Notice:  Use of undefined constant BLOCK_CONTEXT_RIGHT_SIDEBAR - assumed 'BLOCK_CONTEXT_RIGHT_SIDEBAR' in plugins/generic/webFeed/WebFeedBlockPlugin.inc.php on line 63
```

**Comment by crism** [comment]
Could be defined in that file, or in `lib/pkp/classes/plugins/BlockPlugin.inc.php`—will think about which seems more appropriate.

**Comment by beghelli** [comment]
This is a leftover, we are getting rid of the right sidebar for OMP 1.2. See: https://github.com/pkp/pkp-lib/issues/1016

**Comment by crism** [comment]
Yes, just noticed that commit, @beghelli. Thanks; never mind this.
