### ISSUE TITLE
For installed plugins, display the version that is currently installed

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10272]
**Describe the bug**
In the plugin gallery, users can tell when they have a plugin installed, but can't easily tell what version is installed unless they go to the database. We should add this information so the user can quickly tell - this may be helpful in cases where a user is trying to troubleshoot plugin issues, or if they want to know how many versions behind they are.

**To Reproduce**
1. Go to the plugin gallery
2. Click on an installed plugin
3. Note that the installed version is not displayed (can only be inferred if the plugin is up-to-date).

**What application are you using?**
 OJS, OMP or OPS (all versions)

**Additional information**
An example of what this may look like:
![Screenshot 2024-08-02 at 2 25 43 PM](https://github.com/user-attachments/assets/eb4e75c7-750e-452e-b3dc-340c74345b33)

**Comment by kaitlinnewson** [comment]
PR for review @asmecher:

- pkp-lib main: https://github.com/pkp/pkp-lib/pull/10273

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by kaitlinnewson** [comment]
Backported to 3.4 and added above @asmecher.

**Comment by asmecher** [comment]
Moving to the 3.4.0-8 milestone, as https://github.com/pkp/pkp-lib/pull/10313 introduces locale key changes and should be merged shortly after the 3.4.0-7 release is out. @kaitlinnewson, the PR looks good, but I'll hold off on merging it until later!

**Comment by kaitlinnewson** [comment]
@asmecher this one should be ready to merge & close now!

**Comment by asmecher** [comment]
We might need to make a quick follow-up release from the `stable-3_4_0` branch based on https://github.com/pkp/pkp-lib/issues/10341. Let's hold off for just a little longer.

**Comment by kaitlinnewson** [comment]
Hi @asmecher, I wanted to flag this PR to 3.4 which adds a locale key, in case it may be affected by the weblate changes for 3.5 discussed in Mattermost.

**Comment by asmecher** [comment]
@kaitlinnewson, thanks for the reminder -- I've gone ahead and merged this.
