### ISSUE TITLE
Pre-select reader roles on registration

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1028]
Per today's UI/UX discussion with NW and KS:

User role selection during registration was a point of confusion for users during UI/UX testing. We discussed ways to simplify the process. One specific proposal was to hide and pre-select the "Reader" role on the registration form.

IMO that approach creates a new source of confusion: on multi-journal/press sites, there is a spin-out "Show Other Journals" that lists available roles from other contexts. Preselecting reader roles for all of these defeats the purpose of the role, which is to associate a user who has not chosen to be a reviewer or reader with the journal. Without a role, it would be ambiguous which they were interested in.

Likewise, just selecting and hiding the reader role for the current context but no others is confusing, because it appears as though options are available for other contexts that are not available to the current one.

Solution implemented here: leave the Reader checkboxes as they were before, but pre-check the Reader role for the current context.

**Comment by asmecher** [comment]
(Will review with UI/UX on Monday, but closing for now.)

**Comment by NateWr** [comment]
Ok, I don't really have any good ideas for resolving this. I agree with your approach. Let's leave it closed.
