### ISSUE TITLE
Additional data for submissions/{ID}/participants API

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10280]
## Describe the issue
I would like to use the /submissions/{id}/participants API to replace the "Participants" grid with vue.js component. This issues describe the data requirements to be able to do it.

## Behaviour of legacy participant grid
This is the grid we know from workflow page.
<img width="296" alt="Screenshot 2024-08-06 at 13 32 51" src="https://github.com/user-attachments/assets/d5550557-5fc9-44ec-ba14-798f3bc866ad">

**My understanding how the list of participants for legacy grid gets created**
1) It fetches all userGroups that are assigned to given stage and submission via `stage_assignments` table. That gives it list of User groups to present in the UI (StageParticipantGridHandler.php -> loadData)
2) Than for every present user group it gets all the users assigned again via `stage_assignments` table (StageParticipantGridHandler.php -> loadCategoryData)
3) Additionally it checks whether whether user is still in such user group to indicate whether that "Role ended"

## Missing context in the /participants API
What I am missing to mimic this behaviour is getting the stage assignment user group - ideally not just id, but either whole object or at least the name to be able to present it in the UI.

In current endpoint I get list of participating users, along with the user groups that user is currently in. Which I can use to check the "Role ended" scenario. But I don't know via which user group the user was assigned to in `stage_assignments` table.

Also `stageAssignmentId` is needed for some operations.

Additionally it might be good to include the context about the `stageId`, which also comes from `stage_assignments` table. I might not use it at this point, as I can filter by `stageId` using query param. But its also important participant context that might be useful at some point.

Without breaking changes it could be added like this for example:

```
[
  {
    fullName: "Daniel Barnes",
    ...
    ...
     stageAssignmentId: 65,
     stageAssignmentUserGroup: { id: ..., name: {...}}
     stageAssignmentStageId: 15
  }
]
```

**What application are you using?**
 OJS, OMP or OPS version 3.5

**Comment by jardakotesovec** [comment]
@Vitaliy-1 Hi Vitaliy, can I ask you just sanity check that what I described in the issue is accurate?

@ewhanson Hi Erik, any guidance how to add this additional context to the existing endpoint? In terms of the naming/structure. 

After these feedbacks, this I think could be labeled as "Try me" as it should be relatively friendly issue to work on.

**Comment by taslangraham** [comment]
I can pick this up once @Vitaliy-1 and @ewhanson provide their feedback

**Comment by jardakotesovec** [comment]
Just did small update to also include stageAssignmentId

**Comment by ewhanson** [comment]
@jardakotesovec, would this be a good candidate for the `include` type of thing we've been talking about over in #10290? Or is this additional info that will always be needed from the `participants` endpoint?

**Comment by jardakotesovec** [comment]
@ewhanson In this case I would suggest that it should include both user (participant) and stage assignment data by default as these are somewhat essential to get full picture what kind of participant it is (stageAssignmentGroupId) and also stageAssignmentId is also essential for example to remove that participant.

**Comment by ewhanson** [comment]
Thanks @jardakotesovec. That make sense. I think the best approach without breaking changes would be to include this information in the summary data that's generated as a result of `summarizeReviewer()` here: https://github.com/pkp/pkp-lib/blob/d95ecb187b8e31b7e6dff6c5263b5bf65fe6eedc/classes/user/maps/Schema.php#L49-L57 The actual new new data would need to be fetched in `mapProperties()` here: https://github.com/pkp/pkp-lib/blob/d95ecb187b8e31b7e6dff6c5263b5bf65fe6eedc/classes/user/maps/Schema.php#L98-L103

That should be enough to include it when calling the participants endpoint. This approach would additionally include the new information in a few different places (anywhere reviewer data is fetched).

So the `array_merge` above would also include `[..., 'stageAssignmentId', 'stageAssignmentUserGroup', 'stageAssignmentStageId']` as would the `mapByProperties` method to include the data in the shape you described above.

Does that fit with the needs you have?

**Comment by jardakotesovec** [comment]
@ewhanson I will look more detail tomorrow. But surprised that this would be handled via summarizeReviewer. I am interested in participants (editors, author,...), not reviewers for this endpoint.

**Comment by taslangraham** [comment]
Ready for review @ewhanson 
### PRs
- pkp-lib: https://github.com/pkp/pkp-lib/pull/10383/files
    - Updates `mapByProperties` in   [pkp-lib/classes/user/maps/Schema.php](https://github.com/pkp/pkp-lib/blob/d95ecb187b8e31b7e6dff6c5263b5bf65fe6eedc/classes/user/maps/Schema.php#L103) to include user's stage assignment information once a submission and stage Id is provided
- OJS(submodule update): https://github.com/pkp/ojs/pull/4434
- OMP(submodule update): https://github.com/pkp/omp/pull/1696
- OPS(submodule update): https://github.com/pkp/ops/pull/768

**Comment by ewhanson** [comment]
Thanks @taslangraham! Looks good, just a few small comments in the PR.

**Comment by taslangraham** [comment]
@ewhanson thanks for the review. I've responded to your comments and made a few minor cleanup

**Comment by jardakotesovec** [comment]
@taslangraham Hi Taslan,
I came across some other use cases on participants client side, where also `recommendOnly` and `canChangeMetadata` would be useful.
Could you please add these? These are on the stage_assignments table, so hopefully its quick addition.

Thank you!

**Comment by taslangraham** [comment]
@jardakotesovec Sure thing, I'll update shortly

**Comment by taslangraham** [comment]
@jardakotesovec I've updated the pkp-lib [pr](https://github.com/pkp/pkp-lib/pull/10383/files) to include the additional fields. Changes can be viewed [here](https://github.com/pkp/pkp-lib/compare/0a5bcb403ad76627086138c775683d073bf806bd..e0670ce72f6318df1eb9dc75800f48387b504da7)

**Comment by ewhanson** [comment]
Thanks @taslangraham and @jardakotesovec. I'll have a final look at it now.

**Comment by ewhanson** [comment]
@taslangraham, looks good to me! The app submodule commits need to be updated again, but feel free to merge once that's done.

**Comment by taslangraham** [comment]
All merged @ewhanson @jardakotesovec
