### ISSUE TITLE
Avoid saving files with UTF-8 characters

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#10282]
**Describe the bug**
A user uploaded a library file called `FORMATO DE EVALUACIÓN DE ARTÍCULOS-OTH.docx` in OJS 3.1.1.2, I'm not sure since when it has been broken, but the installation has been upgraded to 3.3, and the file isn't accessible, due to its UTF-8 encoding at the disk.

I copied the file using the expected encoding to the same folder, on a well configured terminal I can see the right text on both:

![image](https://github.com/user-attachments/assets/f276707e-56ff-4872-bdd0-c5d5dbc1cc27)

On a not properly configured terminal it's clear that there's a different encoding:
![image](https://github.com/user-attachments/assets/46f15649-2769-4b04-8bdc-5147d6e433f1)

Filename which is different from the database
```bin
0000000: 464f 524d 4154 4f20 4445 2045 5641 4c55  FORMATO DE EVALU
0000010: 4143 494f cc81 4e20 4445 2041 5254 49cc  ACIO..N DE ARTI.
0000020: 8143 554c 4f53 2d4f 5448 2e64 6f63 78    .CULOS-OTH.docx
```

Same filename as the database
```
0000000: 464f 524d 4154 4f20 4445 2045 5641 4c55  FORMATO DE EVALU
0000010: 4143 49c3 934e 2044 4520 4152 54c3 8d43  ACI..N DE ART..C
0000020: 554c 4f53 2d4f 5448 2e64 6f63 78         ULOS-OTH.docx
```

---

Not sure where the encoding was changed (when saving to the disk or at the database), and the software versions used at the time. If there's room for this to happen, it's probably better to store files using only ASCII characters, instead of for example, attempting to normalize the encoding.

To keep a cute name, we can proxy the download (not very interesting from a performance perspective, but...) or replace the characters (might not be that great considering Chinese, Arabian, etc).

**What application are you using?**
OJS 3.3

**Comment by asmecher** [comment]
@jonasraoni, are you able to reproduce the issue, ideally just within a current release of OJS?

**Comment by jonasraoni** [comment]
I'll try to simulate it later, perhaps it's an old bug 🤔

Anyway, it's possible to reconnect the files with something like `file_exists($path) || file_exists(Normalizer::normalize($path, Normalizer::FORM_D)) || file_exists(Normalizer::normalize($path, Normalizer::FORM_C))`.

**Comment by jonasraoni** [comment]
There were several cases, but I couldn't reproduce the issue on the same installation that I found them.
I've created a file using both encodings, both were inserted in the database and in the file system without changes on the encoding, therefore both are accessible.

As the source is unknown, I've removed the label and I'll close this. The fix might be helpful in case it happens with others :)
