### ISSUE TITLE
PHP fatal error when editing Publisher Library file

### ISSUE THREAD

**Issue by jyhein** [pkp/pkp-lib#10287]
**Describe the bug**
PHP fatal error when editing Publisher Library file.

**To Reproduce**
In Settings > Workflow > Publisher Library: 
1. add file: Type any, upload file, and  check 'Public Access' -> OK
2. Try to 'Edit' the file -> Error (pic)
![error](https://github.com/user-attachments/assets/6e52380a-be54-49eb-94b5-e2a9083ffa05)

PHP Error Log:
PHP Fatal error:  Type of PKP\controllers\grid\settings\library\form\EditLibraryFileForm::$contextId must be int (as in class PKP\controllers\grid\files\form\LibraryFileForm) in ojs/lib/pkp/controllers/grid/settings/library/form/EditLibraryFileForm.php on line 27

**What application are you using?**
 OJS version 3.5

**Comment by taslangraham** [comment]
I opened a PR for this @asmecher. It also includes a few other minor fixes in the file. 
PR - https://github.com/pkp/pkp-lib/pull/10291
Test(ojs) - https://github.com/pkp/ojs/pull/4392

**Comment by asmecher** [comment]
Added [a comment](https://github.com/pkp/pkp-lib/pull/10291/files#r1715825760), thanks, @taslangraham!

**Comment by taslangraham** [comment]
thanks for the review @asmecher, I've made the suggested change
