### ISSUE TITLE
Hide reviewing interests on registration form from non-reviewers

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1029]
Hide reviewing interests on registration form from non-reviewers. Only make it visible when the reviewer checkbox is checked.

**Comment by asmecher** [comment]
As with https://github.com/pkp/pkp-lib/issues/1028, this becomes ambiguous when multiple contexts are available. For now, I'll adjust behavior only for single-context sites. For multi-context sites, the field will always be visible.

**Comment by asmecher** [comment]
Screencap shows...
- Reader role on current context checked by default (issue #1028)
- Reviewer interests field only shown when *any* reviewer role checked
- Roles available for other contexts via extras-on-demand (these need styling!)

![Screencap here](https://cloud.githubusercontent.com/assets/200411/12213276/47c4480c-b62a-11e5-9b1d-b764d32b3f55.gif)

**Comment by NateWr** [comment]
Making progress. I'll work on the styles. A couple thoughts:

1. What happens if someone unclicks Reader for all contexts?

2. A short description text for the Roles field might be useful. Is there anything we can tell a user about the Reader role? Does it give them access to anything? Are they likely to receive email notifications or anything like that? 

3. Maybe change "Show Other Journals" to "Register with other journals"?

4. Roles can be changed, but is there any way we can sort the Reader-type role at the top?

5. Testing with latest master here (OMP) the reviewer interests is still always shown. Any commit missing on OMP side?

**Comment by bozana** [comment]
What about the possibility for each journal/press to define the roles an user can register for? -- This was the case in OJS 2.4.x and demand of some presses (e.g. LangSci). -- Then those options for "Register with other journals" wouldn't work well. Or can we assume that those are the minimal/default set each journal/press will provide?

**Comment by NateWr** [comment]
![show-other-presses](https://cloud.githubusercontent.com/assets/2306629/12238289/2c9ee912-b87b-11e5-81c8-3baafbc18622.gif)

**Comment by asmecher** [comment]
@bozana, in the user group editing form, the manager can decide which roles are available for self-registration. Does that suit e.g. LangSci?

@NateWr:
> 1. What happens if someone unclicks Reader for all contexts?

It's possible to be enrolled in the system but not associated with any journal. That's typically a boundary case that causes some confusion, but I'm not sure how better to handle it.

> 2. A short description text for the Roles field might be useful. Is there anything we can tell a user about the Reader role? Does it give them access to anything? Are they likely to receive email notifications or anything like that? 

We can't hard-code much about the roles because they can be created/deleted/configured per the Manager's needs. We could consider adding a description field and adding some defaults, but I'm not sure an additional field is going to improve it overall.

> 3. Maybe change "Show Other Journals" to "Register with other journals"?

Sure, changed: https://github.com/pkp/ojs/commit/971be6c18efb8bd8651986ce3d8ef9bce683f2c3 https://github.com/pkp/omp/commit/803193808ed4e784941d9c87faffd4e40d651cf3

4. Roles can be changed, but is there any way we can sort the Reader-type role at the top?

Sure, changed: https://github.com/pkp/pkp-lib/commit/9ed0c7fc1e7fe25ed9828f58e89a677acaa1da7a

5. Testing with latest master here (OMP) the reviewer interests is still always shown. Any commit missing on OMP side?

This wasn't merged for OJS or OMP yet. Pulls:
https://github.com/pkp/ojs/pull/704
https://github.com/pkp/pkp-lib/pull/1041
Will merge and port over to OMP master.

**Comment by asmecher** [comment]
@NateWr, pull OMP master again -- I've merged the changes. But the styling needs porting to OJS master.

**Comment by NateWr** [comment]
There should be a PRs with styles waiting for pkp-lib, omp and ojs..

**Comment by asmecher** [comment]
OK, thanks -- could you drop the URLs here? Unfortunately Github doesn't seem to link automatically.

**Comment by NateWr** [comment]
I forgot to update the PR titles to include proper linking.

[pkp-lib](https://github.com/pkp/pkp-lib/pull/1034)
[omp](https://github.com/pkp/omp/pull/190)
[ojs](https://github.com/pkp/ojs/pull/702)

Looks like there's a linting error I can fix tomorrow or just go ahead and do it if you want to tick this issue off.

> It's possible to be enrolled in the system but not associated with any journal. That's typically a boundary case that causes some confusion, but I'm not sure how better to handle it.

Can we avoid it by giving the reader role input for the current context a `disabled` attribute? That should prevent people from un-checking it and also just resolve the tiny bit of ambiguity for users.

> We can't hard-code much about the roles because they can be created/deleted/configured per the Manager's needs. We could consider adding a description field and adding some defaults, but I'm not sure an additional field is going to improve it overall.

I was actually thinking about a description text for the overall Roles section. I was thinking that maybe it could say something like, "Register as a Reader if you want to receive publication notifications from that journal." But I don't know if any such activity takes place. It's just uncommon for people to have to register a "base" role so some context might be helpful.

**Comment by asmecher** [comment]
@beghelli, I assigned those PRs to you as you'd begun revewing. OK to leave on your plate?

**Comment by beghelli** [comment]
@asmecher Sure.

**Comment by beghelli** [comment]
@NateWr do you need to update the last pull requests? I just managed to get your changes working when I fetched directly your branches. But maybe I did something wrong getting the commits in those pull requests...

**Comment by beghelli** [comment]
Also, the extras on demand controller is used elsewhere in the system. Pages like management/tools/reportGenerator need a little bit more of styling, I think... Or maybe the template is wrong. We can open a new issue if we just need to adapt the controller usage...

**Comment by NateWr** [comment]
@beghelli There was a [linting error](https://travis-ci.org/pkp/ojs/jobs/101615092) that I was going to fix, but otherwise the PRs should be good.

Thanks for pointing out the `reportGenerator`. I've just had a look myself. As far as I can tell, the existing styling should work. Each `extrasOnDemand` should be supplied with an active title and inactive title. It probably just needs an inactive title.

Want me to put that into new commits that fix the linting as well?

**Comment by beghelli** [comment]
If you can, it would help :) Thanks.

**Comment by asmecher** [comment]
(One more place to check extras on demand styling: when creating a reviewer, there's a spinout to select files for review.)

**Comment by NateWr** [comment]
That one appears to not be an `extrasOnDemand` component. It's got a custom accordian action on it in `ReviewerFormFooterHandler.js`. Shall I convert it to an `extrasOnDemand` component?

**Comment by asmecher** [comment]
Ah -- yes, please, if just for the sake of standardization.

**Comment by NateWr** [comment]
It required a bit of extra text for the toggle + grid titles. Quick ok on the language?

![control-shared-files](https://cloud.githubusercontent.com/assets/2306629/12301907/669f4760-ba1a-11e5-8973-eff449af7dc0.png)

**Comment by asmecher** [comment]
IMO that's a little redundant -- rather than both "Control Shared Files" and "Files To Be Reviewed", why not just use one heading that's clickable?

**Comment by NateWr** [comment]
Because it's a grid and grids have titles. Even when they don't have titles they have a big gaping hole where a title would be which throws off the visual hierarchy and pulls your eye over to the search icon on the right rather than keeping it running down the left vertically.

![control-shared-files](https://cloud.githubusercontent.com/assets/2306629/12302076/48acffbc-ba1b-11e5-8ab0-35bc59992e63.png)

**Comment by asmecher** [comment]
I sense frustration :) Fair enough, though maybe we can resolve the problem more broadly. Thinking out loud (@beghelli): what about a grid feature that makes the title into a clickable way of collapsing the whole grid?

**Comment by beghelli** [comment]
@NateWr I still prefer the last one, it makes me feel less confused trying to understand why two titles so similar are so close...

@asmecher It seems like a good idea and an easy one to implement. I can try that...

**Comment by asmecher** [comment]
@beghelli, watch out for one detail: that grid is also presented in the "Edit Review" modal, where it should not be collapsed by default. IIRC I recently added conditional code to selectively present the grid title; that ought to be usable in selectively adding the grid feature.

**Comment by NateWr** [comment]
Please no more grid features that effect the UI. It's already incredibly difficult to come up with a design that accounts for all the existing variations in display, interaction and content.

The fact that grids are visually off-balance without a title is a good example of this problem. The more use cases you pack into one system the more impossible it becomes to really design the UI.

I'd much rather have a minor duplication in labelling than an entirely new exception to manage.

**Comment by NateWr** [comment]
I'd even rather let you guys have the grid without a title than have to support click-to-expand grids as a rule. :)

**Comment by asmecher** [comment]
@NateWr, the bad news is that we already have title-less grids, and click-to-expand grids, just not consistently written. Moving it to a feature doesn't change that, it just makes it cleaner and more consistent, and resolves the immediate layout problem.

Is an ideal solution part of the bigger conversation about grids?

**Comment by NateWr** [comment]
@asmecher Which grids are click-to-expand? I'm less concerned about title-less grids. They're a visual annoyance but no big deal (at least what I've seen). I don't know what to think about click-to-expand grids unless I see them. It kind of depends on context, but in an ideal world a grid shouldn't care about the context in which it is displayed or not displayed.

**Comment by asmecher** [comment]
@NateWr, I mean the one we're already looking at. Grids don't currently support click-to-expand, so in this case the title is pulled out of the grid, then wrapped in an accordion. That's de facto a click-to-expand grid, just hacked together out of the available local masonry.

Beyond that, we've also spoken about making the dashboard submission lists click-to-expand, though I don't think we've come to a decision about it.

We do have collapsible categories elsewhere (IIRC the plugin grid), so this sort of echoes that too.

**Comment by NateWr** [comment]
In this case I think the `extrasOnDemand` is the better option. How I would present a click-to-expand link is very different to how I would present a grid title. Trying to come up with a way to bridge the two would be difficult and I don't think the result would be significantly better.

I think the downsides of embedding a grid in a click-to-expand link are small and the upsides large: easier maintainability, more flexibility (if we wanted to drop another component in there later, no problem), and more closely scoped components.

Also, the extras on demand is a tiny component that does one thing. It'd be easy to customize it in a particular case where we wanted to do so. The grids come with lots of considerations so adjusting it here and there is more difficult and risky.

What do you think about adding a more appropriate active text? It should probably be done this way anyway for better accessibility.

Closed:
![to-be-reviewed](https://cloud.githubusercontent.com/assets/2306629/12303134/a294dc7a-ba20-11e5-8043-e9e727945f1a.png)

Opened:
![to-be-reviewed-hide](https://cloud.githubusercontent.com/assets/2306629/12303133/a2939fcc-ba20-11e5-9f71-3348bd366853.png)

**Comment by asmecher** [comment]
@NateWr, I also take your point about not binding the behavior of a grid to the behavior of an extras-on-demand control. The permutations do get bad.

I'm OK to go ahead with what you've mocked up.

**Comment by NateWr** [comment]
Or maybe this language is more clear and with less potential for confusion:

![close-file-selection](https://cloud.githubusercontent.com/assets/2306629/12303232/181f8f6c-ba21-11e5-88d3-d408555e3cc9.png)

**Comment by asmecher** [comment]
Yes, better still.

**Comment by NateWr** [comment]
New PRs for [ojs](https://github.com/pkp/ojs/pull/707) and [omp](https://github.com/pkp/omp/pull/192).

**Comment by beghelli** [comment]
@NateWr Can this be closed?
