### ISSUE TITLE
Correct possible dropping of notnull from locale columns on upgrade

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#10293]
The implementation of #9425 included migration code that [extended the length of any identified `locale` columns](https://github.com/pkp/pkp-lib/pull/9309/files#diff-fad8d9bebeb168fbbd3d8e8788d32eab822ca77ef32a66501484c5c02f6a3915R86). However, some of these columns (e.g. [publication_galleys.locale](https://github.com/pkp/ojs/blob/b08b8bbc7b5bf1f618f7ce8aa2ff01e8fdb91715/classes/migration/install/OJSMigration.php#L265)) are nullable, and this code will either make them `NOT NULL` or, if there is null data present, fail with an error.

I would suggest altering the migration to make it preserve the `NOT NULL` status of the column when extending the length.

@jyhein and @ajnyga, just a heads-up -- @touhidurabir would like to fix it.

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10305
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4398 [TEST ONLY]

**Comment by ajnyga** [comment]
thanks, go ahead

**Comment by touhidurabir** [comment]
@asmecher tests are passing , can you take a look at the PR at https://github.com/pkp/pkp-lib/issues/10293#issue-2456546217

**Comment by asmecher** [comment]
@ajnyga, could you or @jyhein review this one? Thanks!

**Comment by asmecher** [comment]
@ajnyga or @jyhein, this is breaking just about everything on upgraded installations; could you have a look at the PRs above?

**Comment by bozana** [comment]
@touhidurabir, what does "->first(default:[])" mean?

**Comment by touhidurabir** [comment]
> @touhidurabir, what does "->first(default:[])" mean?

@bozana please see at https://github.com/pkp/pkp-lib/pull/10305/files#r1771286012 for reasoning .

**Comment by bozana** [comment]
So I took a look at the code changes and they look good to me: we now look if the column to be changed is nullable and act accordingly i.e. we use `$table->string($l, 28)->nullable()->change()` (instead of `$table->string($l, 28)->change()`) in that case.
I have not tested it, but I think we can merge it :-)

**Comment by ajnyga** [comment]
sorry for missing this in august, we talked about this in the morning and looks to be fine. I also tried running upgrade test from 3.4 stable.
