### ISSUE TITLE
Error Database Duplicate Entry

### ISSUE THREAD

**Issue by irvanhau** [pkp/pkp-lib#10297]
Hello, i found this error when i upgrade the ojs 2.4.7.1
A database error has occurred: Duplicate entry '1100-3-1' for key 'review_rounds_submission_id_stage_id_round_pkey', any other same with me?

**Comment by asmecher** [comment]
@irvanhau, can you post this question on our support forum (https://forum.pkp.sfu.ca) rather than filing an issue? That's the best place to get help.

**Comment by irvanhau** [comment]
@asmecher aokay alex, thankyou for the information!!
