### ISSUE TITLE
Fix listbuilder delete action

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1030]
The "Delete" action for listbuilder rows is formatted to the right of the first column, instead of to the left.
In the pictured example, this is the "Edit User" action in the Journal Manager's users grid.

![actions](https://cloud.githubusercontent.com/assets/200411/12210498/4e441934-b60f-11e5-8f31-fa5f0695948f.png)

**Comment by NateWr** [comment]
Hmm, if I recall, other listbuilder components work better with the actions on the right. Might need a grid-specific CSS override here.

**Comment by NateWr** [comment]
Should be good to go here.

**Comment by asmecher** [comment]
PR was: https://github.com/pkp/pkp-lib/pull/1033

**Comment by asmecher** [comment]
@NateWr, can you take a quick look at aaebcfe? Listbuilders that only had one column were missing their delete actions after this PR was merged, so this makes sure that case is handled.

Try out the Chapter edit modal, available from the Monograph tab of the Catalog Entry tool; it has two single-column listbuilders. OTOH a little tweaking is needed for the case where the row is an active dropdown, before it's been bounced back to the server as a static row.

**Comment by NateWr** [comment]
Good catch. Did some touch-ups in https://github.com/pkp/pkp-lib/pull/1104

Related but not really: https://github.com/pkp/omp/pull/206
