### ISSUE TITLE
Add queue job unit tests for 3.5

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#10306]
This is a continuation of issue https://github.com/pkp/pkp-lib/issues/9899 for 3.5 

**Job classes to have unit tests**

##### OJS
- [x] APP\jobs\doi\DepositIssue
- [x] APP\jobs\notifications\IssuePublishedNotifyUsers
- [x] APP\jobs\notifications\OpenAccessMailUsers
- [ ] APP\jobs\orcid\DepositOrcidReview
- [x] APP\jobs\statistics\CompileCounterSubmissionDailyMetrics
- [x] APP\jobs\statistics\CompileCounterSubmissionInstitutionDailyMetrics
- [x] APP\jobs\statistics\CompileIssueMetrics
- [x] APP\jobs\statistics\CompileSubmissionGeoDailyMetrics
- [x] APP\jobs\statistics\CompileUniqueInvestigations
- [x] APP\jobs\statistics\CompileUniqueRequests
- [ ] APP\jobs\statistics\CompileUsageStatsFromTemporaryRecords [deprecated 3.4.0.5]
- [x] APP\jobs\statistics\DeleteUsageStatsTemporaryRecords
- [x] APP\jobs\statistics\ProcessUsageStatsLogFile
##### OMP
- [x] APP\jobs\statistics\CompileCounterSubmissionDailyMetrics
- [x] APP\jobs\statistics\CompileCounterSubmissionInstitutionDailyMetrics
- [x] APP\jobs\statistics\CompileSeriesMetrics
- [x] APP\jobs\statistics\CompileSubmissionGeoDailyMetrics
- [x] APP\jobs\statistics\CompileUniqueInvestigations
- [x] APP\jobs\statistics\CompileUniqueRequests
- [ ] APP\jobs\statistics\CompileUsageStatsFromTemporaryRecords [deprecated 3.4.0.5]
- [x] APP\jobs\statistics\DeleteUsageStatsTemporaryRecords
- [x] APP\jobs\statistics\ProcessUsageStatsLogFile
##### OPS
- [x] APP\jobs\statistics\CompileCounterSubmissionDailyMetrics
- [x] APP\jobs\statistics\CompileCounterSubmissionInstitutionDailyMetrics
- [x] APP\jobs\statistics\CompileSubmissionGeoDailyMetrics
- [x] APP\jobs\statistics\CompileUniqueInvestigations
- [x] APP\jobs\statistics\CompileUniqueRequests
- [ ] APP\jobs\statistics\CompileUsageStatsFromTemporaryRecords [deprecated 3.4.0.5]
- [x] APP\jobs\statistics\DeleteUsageStatsTemporaryRecords
- [x] APP\jobs\statistics\ProcessUsageStatsLogFile
##### PKP-LIB
- [x] PKP\jobs\bulk\BulkEmailSender
- [x] PKP\jobs\doi\DepositContext
- [x] PKP\jobs\doi\DepositSubmission
- [x] PKP\jobs\email\EditorialReminder
- [x] PKP\jobs\invitations\RemoveExpiredInvitationsJob
- [x] PKP\jobs\metadata\BatchMetadataChangedJob
- [x] PKP\jobs\metadata\MetadataChangedJob
- [x] PKP\jobs\notifications\NewAnnouncementNotifyUsers
- [x] PKP\jobs\notifications\StatisticsReportMail
- [x] PKP\jobs\notifications\StatisticsReportNotify
- [ ] PKP\jobs\orcid\DepositOrcidSubmission
- [ ] PKP\jobs\orcid\SendAuthorMail
- [ ] PKP\jobs\orcid\RevokeOrcidToken
- [x] PKP\jobs\statistics\ArchiveUsageStatsLogFile
- [x] PKP\jobs\statistics\CompileContextMetrics
- [x] PKP\jobs\statistics\CompileMonthlyMetrics
- [x] PKP\jobs\statistics\CompileSubmissionMetrics
- [x] PKP\jobs\statistics\RemoveDoubleClicks
- [x] PKP\jobs\submissions\RemoveSubmissionFileFromSearchIndexJob
- [x] PKP\jobs\submissions\RemoveSubmissionFromSearchIndexJob
- [x] PKP\jobs\submissions\UpdateSubmissionSearchJob

Orcid functionality related tests will be handled by https://github.com/pkp/pkp-lib/issues/10127

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10340
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4411
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1685
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/758

**Comment by touhidurabir** [comment]
@asmecher Tests are all added and tested for all apps(`OJS`, `OMP` and `OPS`) including `PKP-lib` for every apps . Please take a look at https://github.com/pkp/pkp-lib/issues/10306#issue-2463151689 .

**Comment by asmecher** [comment]
Thanks, @touhidurabir, I made a few comments on the PRs.

**Comment by touhidurabir** [comment]
@asmecher all tests are passing now . If all good, goo to merge , Please take a look at the PRs at https://github.com/pkp/pkp-lib/issues/10306#issue-2463151689

**Comment by asmecher** [comment]
All merged -- thanks, @touhidurabir!
