### ISSUE TITLE
OJS 3.4.0-5 PHP 8.3 site structure, scripts and css lost behind a reverse proxy

### ISSUE THREAD

**Issue by asidibe1** [pkp/pkp-lib#10300]
**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

The site is working well for all journals in http but when we use a reverse proxy (through nginx proxy manager) to connect a domain through https, all the structure of the site as well as connection information are lost.
With the system certificate and https, the site is accessible after acceptance
![image](https://github.com/user-attachments/assets/1fb37bb9-5ca2-4eca-b610-b1f2ad0b3e52)

It is also accessible as long as it is through http
![image](https://github.com/user-attachments/assets/d0c1022b-ed3e-4068-8864-f30929a84894)

If we reverse proxy the https version, then we end on a bad gateway 502 error.
Do anybody use a similar reverse proxy system? I am no problem with any CMS or other web site but only ojs and ops.
How can I solve this? I was thinking of a local certification authority to certificate the internal ip address. Can you advise please?

**What application are you using?**
 OJS-3.4.0-5 and OPS-3.4.0-5

Thank you for your reply
Best

**Comment by asmecher** [comment]
@asidibe1, I see this is also posted in our [support forum](https://forum.pkp.sfu.ca/t/ojs-3-4-0-5-php-8-3-site-structure-scripts-and-css-lost-behind-a-reverse-proxy/89933); I'll continue the conversation there.
