### ISSUE TITLE
Move ORCID connect button to user Identity tab

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#10315]
The ORCID connect button within the user profile is currently located in the Public tab (see photo). Through consultation with the PKP-ORCID working group, we've decided this should be relocated as part of the primary, "Identity" tab.

<img width="1022" alt="Screenshot of ORCID connect button in public tab" src="https://github.com/user-attachments/assets/e1af05b5-6550-4cdf-a38d-b0a438d4089e">

### Notes

This will need to be completed on the `main` branch only.
This work will likely only touch the `pkp-lib` repository, but submodule commits should be made for OJS, OMP, and OPS.

**Comment by taslangraham** [comment]
Read for review @ewhanson 
### **PRs**:
- pkp-lib: https://github.com/pkp/pkp-lib/pull/10325/files

**submodule updates**:
- ojs - https://github.com/pkp/ojs/pull/4404
- omp - https://github.com/pkp/omp/pull/1677
- ops - https://github.com/pkp/ops/pull/752

**Comment by ewhanson** [comment]
Thanks, @taslangraham. All looks good so I've merged it!

**Comment by taslangraham** [comment]
Thanks for the review @ewhanson
