### ISSUE TITLE
Deleting authenticated ORCIDs should revoke tokens

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#10318]
**Describe the issue**
When a user authenticates their ORCID and links it to OJS, an access and refresh token are created and stored in the database. Currently, when an ORCID is deleted, the ORCID along with the tokens are deleted from the database, but they are not revoked from ORCID. Whenever an authenticated ORCID is removed from OJS, the corresponding tokens should be removed as well as described in the [ORCID documentaiton](https://info.orcid.org/ufaqs/how-can-i-revoke-tokens/#).

For the `FieldOrcid` Vue component, this revocation can be done as part of the OJS API call here: https://github.com/pkp/pkp-lib/blob/0fb17c21f20212ac944b5c15b19707a5e8fae83a/api/v1/orcid/OrcidController.php#L129

This will need to be handled separately for the user profile ORCID connection workflow.

**What application are you using?**
 OJS, OMP, and OPS version 3.5, `main` branch

**Additional information**
This will apply only to the `main` branch.

**Comment by taslangraham** [comment]
Ready for review @ewhanson 

### Description
- Revoke ORCID tokens from ORCID when they are removed from a user’s profile or author details.
- Implemented a job to make HTTP call to the ORCID API, revoking a user's access tokens for the application.
- Revoking an ORCID linked to a user’s profile does not revoke tokens linked to their author details for individual submissions, and vice versa.

### PRs:
pkp lib - https://github.com/pkp/pkp-lib/pull/10333/files

**submodule updates**
- ojs: https://github.com/pkp/ojs/pull/4409/files
- ops: https://github.com/pkp/ops/pull/754/files
- omp: https://github.com/pkp/omp/pull/1678/files

**Comment by ewhanson** [comment]
Thanks @taslangraham. Looks good! Just a few comments in the PR.

I also had a question about the placement of the delete button:

<img width="974" alt="Screenshot of user profile with ORCID" src="https://github.com/user-attachments/assets/953eb024-ba71-49d4-93cd-2e7aa1120931">

I'm not sure how easy it would be, but if possible, I think it would be better if it were in-line with the ORCID URL, same as the Vue component.

**Comment by taslangraham** [comment]
@ewhanson thanks for the review. 

In response to your suggestion, 
> I'm not sure how easy it would be, but if possible, I think it would be better if it were in-line with the ORCID URL, same as the Vue component.

I'm working on a few UI changes on https://github.com/pkp/pkp-lib/issues/10319, I could apply the suggested UI change as a part of that issue

**Comment by ewhanson** [comment]
That sounds good @taslangraham, feel free to make that UI change there.

**Comment by taslangraham** [comment]
@ewhanson I've made the suggested updates. Please take a look

**Comment by ewhanson** [comment]
All merged, thanks @taslangraham!
