### ISSUE TITLE
Implement ORCID brand guidelines in ORCID functionality

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#10319]
**Describe the issue**
ORCID elements such as the "connect ORCID" button should conform to the ORCID branding guidelines as described in the [ORCID documentation](https://info.orcid.org/documentation/integration-guide/user-experience-display-guidelines/). There are [mockups in Figma](https://www.figma.com/design/Wf7sDlUg2372jaKKTJ0Mgz/OJS-3.4-3.5?node-id=3274-5890&t=elK6Yv3zmWt3WftX-0) for the buttons under "ORCID verification". These currently appear in a few different places:

- [ ] User profile (as noted in Figma)
- [ ] In invitation emails (as noted in Figma). Email invitations should also include a plain-text link in addition to the email "button."

<img width="716" alt="Screenshot of user profile mockup" src="https://github.com/user-attachments/assets/ab53c3ab-d81e-40ad-ae45-f7b46dcedf06">

<img width="716" alt="Screenshot of email invitation mockup" src="https://github.com/user-attachments/assets/c6f5f6af-4a2f-43ea-8b73-c693935c8203">

**What application are you using?**
 OJS, OMP, and OPS version 3.5, (`main` branch)

**Comment by taslangraham** [comment]
Ready for review @ewhanson 

### PRs
[pkp-lib](https://github.com/pkp/pkp-lib/pull/10346)

1. Update email button to match ORCID guidelines; added plain text link; fix missing value for template variable, `$principalContactSignature`
![Screenshot 2024-09-04 121748](https://github.com/user-attachments/assets/45965b1e-f86d-4222-8e10-051178894da5)

2. Update ORCID buttons, and ID display on User profile page

    **User's ORCID ID**
    ![Screenshot 2024-09-04 124209](https://github.com/user-attachments/assets/3a365420-2bf9-4970-898b-75d365f02619)

    **User has ORCID but is currently not authenticated**

    ![Screenshot 2024-09-04 124133](https://github.com/user-attachments/assets/9e6a712f-d747-4abd-a554-d91b89ec2c11)

    **User does not have ORCID**

    ![Screenshot 2024-09-04 124047](https://github.com/user-attachments/assets/cdc4c770-abf4-44ba-9f32-697250050453)

3. Added an automatic redirect with a message displayed on the page to inform the user after user successfully connects their ORCID record as advised by ORCID guidelines

[UI Library](https://github.com/pkp/ui-library/pull/406/files)
Display option to resend verification request as shown in Figma design
![Screenshot 2024-09-04 125022](https://github.com/user-attachments/assets/bc09ca21-1e95-4dc3-85a8-05c6592c943d)

### Submodule updates

- osj: https://github.com/pkp/ojs/pull/4425
- ops: https://github.com/pkp/ops/pull/762
- omp: https://github.com/pkp/omp/pull/1689

**Comment by ewhanson** [comment]
Thanks @taslangraham! It's looking really good. Just a few questions in the PRs.

**Comment by taslangraham** [comment]
@ewhanson, I've made the relevant changes based on your feedback and Devika's.

**Comment by ewhanson** [comment]
Thanks, @taslangraham. Merged!
