### ISSUE TITLE
check for egrep in convertApacheAccessLogFile fails although file is present at location

### ISSUE THREAD

**Issue by bdcaf** [pkp/pkp-lib#10314]
I have the impression https://github.com/pkp/pkp-lib/blob/d95ecb187b8e31b7e6dff6c5263b5bf65fe6eedc/tools/convertApacheAccessLogFile.php#L123 needs to be negated. (At least I was able to reprocess once I negated it.)

**Comment by asmecher** [comment]
@bdcaf, I think that's already being proposed/discussed [here](https://github.com/pkp/pkp-lib/pull/10294#discussion_r1715087039) -- @bozana, is that right?

**Comment by bdcaf** [comment]
Yes looks like it. Sorry for the noise, it didn't show up on my searches for this problem. Thanks for doing the good work.

**Comment by bozana** [comment]
Wow @asmecher, how did you notice that discussion and remembered and... :-O Amazing... :-)

**Comment by jonasraoni** [comment]
I suspect he's doing the same as me, trying to cope with all GitHub notifications, but it's tough, especially now that we have more members 😁
