### ISSUE TITLE
[OMP] Apply timezone setting to DB connection

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#1031]
The new timezone setting should be applied to both PHP and the DB to ensure that saved dates work correctly with DB date functions, e.g. date_posted < CURRENT_DATE.

**Comment by bozana** [comment]
Do I understand it correctly: 
Now we have the setting for the time zone in the config file. This setting is then applied to PHP in PKPLocale::initialize. It is not applied to the DB, but it should. Right?
Should this be applied to the DB in the PKPApplication constructor? Something like this: "$dbconn->Execute('SET time_zone = ...')"?

**Comment by mfelczak** [comment]
Hi @bozana, that's my understanding, although note that setting the DB timezone will need to work for both MySQL and PostgreSQL.

**Comment by bozana** [comment]
Thanks @mfelczak! I will then try to solve it after OMP 1.2 is released, because this issue is apparently not so crucial for that release...

**Comment by bozana** [comment]
Hi @mfelczak and @asmecher, would you mind to take a look at this change (for this issue): https://github.com/bozana/pkp-lib/commit/93f99149b61ac1ccbd12980b6a8ef2f289137490

I will have to check, if the installation process is covered within this -- the time zone settings during/for the installation -- I don't think so.
And I will have to test it with PostgreSQL -- I have to install it first...
Thus, if you think this is OK and at the correct place (possibly at the very start), then I will proceed... :-)
THANKS A LOT!!!

**Comment by asmecher** [comment]
Looks reasonable to me, @bozana, just one comment!

**Comment by bozana** [comment]
Maybe one more comment: I think we will have to use offset, because: "Named time zones can be used only if the time zone information tables in the mysql database have been created and populated." (s. http://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html)
And PHP time zone has to be set before calculating the offset.

**Comment by bozana** [comment]
@asmecher, thanks a lot! I will make the recommended change and test those two other cases (installation and PostgreSQL)...

**Comment by bozana** [comment]
For setting timezone in PostgreSQL s. TIMEZONE part here: http://www.postgresql.org/docs/8.3/static/sql-set.html

**Comment by bozana** [comment]
I am not sure if this solution solves the daylight saving time (DST) issues, but I believe it does: the PHP considers DST, we calculate the offset to UTC using the PHP time and use that to set the time zone for DB.
For MySQL we don't have another possibility than to use the offset, but for PostgreSQL we could use the names from the time zone setting, and the PostgreSQL would deal with DST. If this is then synchron with how PHP deals with DST, I am not sure. Thus, maybe best to use offset for PostgreSQL as well.
?

**Comment by bozana** [comment]
pkp-lib omp-dev-1_2 PR: https://github.com/pkp/pkp-lib/pull/1421

**Comment by mfelczak** [comment]
Hi @bozana, this looks good.

Both MySQL and PostgreSQL actually support timezone names provided that the timezone data has been initialized. But I think using the offset is better, since it will account for DST and ensure that PHP and the DB are always at the same offset.

Since PHP and the DB require regular updates to timezone information (i.e. dates each year when DST begins and ends), it is possible to have one up-to-date and the other out-of-date, e.g. if PHP has been upgraded, but MySQL is using out-of-date timezone data.

**Comment by mfelczak** [comment]
@asmecher, unless @bozana has anything else to add, this should be ready to go.

**Comment by bozana** [comment]
@mfelczak and @asmecher, nothing to add, ready to go :-) Thanks!!!

**Comment by asmecher** [comment]
Good enough for me, thanks!
