### ISSUE TITLE
Refactor announcements as an Eloquent Model

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#10328]
Announcement is an entity that utilises settings table. This makes its refactoring to the Eloquent model a non-trivial task.
As a part of this issue
- [x] Adapt Eloquent model to work with data from a settings table as usual properties/attributes
- [x] Adapt Eloquent to work with localized properties
- [x] Refactor Announcement entity

This will serve as an example for refactoring of other entities, such as: [genres](https://github.com/pkp/pkp-lib/issues/10133) and [controlled vocabulary](https://github.com/pkp/pkp-lib/issues/10292).

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/10382
OJS: https://github.com/pkp/ojs/pull/4433

**Comment by Vitaliy-1** [comment]
@touhidurabir, can you review this? 
@Hafsa-Naeem, I see that you are also working on refactoring of entity which deals with settings table. Feel free to make comments if you'd like.

**Comment by touhidurabir** [comment]
@Vitaliy-1 I have added reviews at https://github.com/pkp/pkp-lib/pull/10382#pullrequestreview-2311493712
