### ISSUE TITLE
fulfillQueuedPayment fails when no user session is set such as in payment gateway callbacks

### ISSUE THREAD

**Issue by otuoma** [pkp/pkp-lib#10327]
**Describe the bug**

The following error occurs when a payment gateway (tested using stripe) calls the callback URL upon successful payment

```
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/html/classes/payment/ojs/OJSPaymentManager.php:359
```

**To Reproduce**

The error occurs when the method fulfillQueuedPayment is called as in this example https://github.com/OtCloudCompany/ojs/blob/4df3e060fa05e1108905a0458e5d641af257f8cf/plugins/paymethod/malipo/MalipoPlugin.php#L365

**Is Fixed by**
Getting the userId from QueuedPayment instead of the request session fixes the issue, but I am not sure what other issues this could introduce.

https://github.com/OtCloudCompany/ojs/blob/4df3e060fa05e1108905a0458e5d641af257f8cf/classes/payment/ojs/OJSPaymentManager.php#L360

**What application are you using?**
 OJS 3.4.0-6 

**Additional information**
Entire stack trace 
`PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/html/classes/payment/ojs/OJSPaymentManager.php:359\nStack trace:\n#0 /var/www/html/plugins/paymethod/malipo/MalipoPlugin.php(293): APP\\payment\\ojs\\OJSPaymentManager->fulfillQueuedPayment()\n#1 /var/www/html/pages/payment/PaymentHandler.php(48): APP\\plugins\\paymethod\\malipo\\MalipoPlugin->handle()\n#2 [internal function]: APP\\pages\\payment\\PaymentHandler->plugin()\n#3 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()\n#4 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#5 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPPageRouter->route()\n#6 /var/www/html/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch()\n#7 /var/www/html/index.php(21): PKP\\core\\PKPApplication->execute()\n#8 {main}\n  thrown in /var/www/html/classes/payment/ojs/OJSPaymentManager.php on line 359`

**Comment by asmecher** [comment]
@otuoma, thanks -- the existing Paypal plugin didn't encounter this same problem because it fulfills payment on a request from the user's browser, rather than a request initiated by the payment service. The fix you proposed looks good to me and I've committed it for release in the next 3.4.0-x build (due likely today).

**Comment by otuoma** [comment]
Great! Now I can proceed with my plugin development knowing it will work with the main stream OJS releases. The plugin source code has now been moved to this repository [https://github.com/OtCloudCompany/Malipo](https://github.com/OtCloudCompany/Malipo)
