### ISSUE TITLE
Include metadataLocales in /submissions/{submissionId} API

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10329]
**Describe the issue**

While working on migrating Publications to the side modal. I need to be able to configure the publication metadata forms correctly client side. For that I need supported metadata locales for specific submission. 

Could we add following to the `api/submissions/{submissionId}` response?

```
{
  ...
  metadataLocales: [
	{key: 'en', label: 'English'},
	{key: 'fr_CA', label: 'French (Canada)'},
  ]
}
```

This would come [from](https://github.com/pkp/pkp-lib/blob/main/pages/workflow/PKPWorkflowHandler.php#L225).

```
        $locales = collect($submissionContext->getSupportedSubmissionMetadataLocaleNames() + $submission->getPublicationLanguageNames())
            ->map(fn (string $name, string $locale) => ['key' => $locale, 'label' => $name])
            ->sortBy('key')
            ->values()
            ->toArray();

```

**What application are you using?**
 OJS, OMP or OPS version 3.5

PRs:
- https://github.com/pkp/pkp-lib/pull/10330
- https://github.com/pkp/ojs/pull/4406 (only submodule update)
- https://github.com/pkp/omp/pull/1695 (only submodule update)
- https://github.com/pkp/ops/pull/767 (only submodule update)

**Comment by jardakotesovec** [comment]
@bozana Thank you! Looking good. I am not sure if this might generate individual sql queries per each submission on endpoints like /submissions? 

As I run into couple more issues with the publication forms - I did create discussion to explore alternative solution than client side manipulation. Lets see how that goes and than will come back to this one. 

https://github.com/pkp/pkp-lib/discussions/10331

**Comment by Vitaliy-1** [comment]
> I am not sure if this might generate individual sql queries per each submission on endpoints like /submissions?

Yes, this will produce 2 additional sql queries per submission in the list.

**Comment by bozana** [comment]
Doesn't /submissions use summary props, where this metadataLocales is not included?

**Comment by Vitaliy-1** [comment]
I was referring to the backend submission controller, parts where we mapping submissions to the submissions list.

**Comment by jardakotesovec** [comment]
I will close this one for now in favour of https://github.com/pkp/pkp-lib/issues/10336. 

We might need to do this once we would shift form building towards JS, but let's not get ahead of ourselves too much.

**Comment by jardakotesovec** [comment]
So it turned out this still could be useful for some forms.

@Vitaliy-1 Could you please advise how to make this either performant or other option that would work fine for me to expose it only on /submissions/{submissionId}, so it does not cause problems on the listings we have.

**Comment by bozana** [comment]
As far as I can see this property is not included into submission listing, s. https://github.com/pkp/pkp-lib/blob/main/classes/submission/maps/Schema.php#L62.

**Comment by Vitaliy-1** [comment]
Thanks, not included then! My bad.

**Comment by jardakotesovec** [comment]
@Vitaliy-1 @bozana Oki, in that case are we comfortable to merge it?

**Comment by jardakotesovec** [comment]
@bozana I see that your implementation would return only array of the locale names.

Would be possible to include the labels as mentioned in original issue?

I could get the labels some other way if we could assume that whatever locales are selected for given journal stay same - but  since it can gets changes - I can't think of reliable way of getting the labels for all locales that might occur for given submission.

**Comment by bozana** [comment]
@jardakotesovec, let me see -- it should be possible for me to change it...

**Comment by bozana** [comment]
Hi @jardakotesovec, what do you mean with 

> Would be possible to include the labels as mentioned in original issue?

That JSON part looks for me locally like this:
`"metadataLocales":[{"key":"en","label":"English"},{"key":"fr_CA","label":"French (Canada)"}]`
Isn't is correct?

**Comment by jardakotesovec** [comment]
@bozana I see, ok. From the schema it seems that it would be only array of strings? Thats what confused me.

```
"metadataLocales": {
			"type": "array",
			"items": {
				"type": "string",
				"validation": [
					"regex:/^([A-Za-z]{2,4})(?<sc>[_-]([A-Za-z]{4,5}|[0-9]{4}))?([_-]([A-Za-z]{2}|[0-9]{3}))?(@[a-z]{2,30}(?&sc)?)?$/"
				]
			}
		},
```

**Comment by bozana** [comment]
How about having this:
`"metadataLocales":{"en":"English","fr_CA":"French (Canada)"}`
Or would you rather have it with key and value?

**Comment by jardakotesovec** [comment]
@bozana Thank you, yes this shape is perfectly fine. Can we merge it? :-)

**Comment by bozana** [comment]
OK, I have slightly changed it,
@Vitaliy-1, could you maybe take a look at/review the PR -- if you would have any other suggestion?
