### ISSUE TITLE
Allow except or/and depending middleware requirement for routing middleware

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#10342]
**Describe the problem**
Some middleware may require the presence of one or more other middleware to run/function properly . One such example is the `DecodeApiTokenWithValidation` and `ValidateCsrfToken` middleware that require `HasUser` middleware . 

Another case is some middleware may new pass some routes to pass without verifying it's own passing logic (what requirements defined in the middleware `handle` function) .

**What problem it will solve**
One example is the invitation API where when accepting an invitation , there will/can be no API KEY or user associated with the request . This scenario make it impossible to access api routes because of global middleware such as `DecodeApiTokenWithValidation` and `ValidateCsrfToken` look for API KEY or logged in user session . 

**What application are you using?**
 OJS, OMP or OPS version `main` (upcoming `3.5.0`)

**Additional information**
see https://github.com/pkp/pkp-lib/issues/10311 and possible proposed solution at https://github.com/pkp/pkp-lib/issues/10311#issuecomment-2309574338

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10343
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4412 [TEST ONLY]
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1686 [TEST ONLY]
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/759 [TEST ONLY]

**Comment by touhidurabir** [comment]
Merged the `pkp-lib` PR at https://github.com/pkp/pkp-lib/pull/10343, will let the submodule get updated later manually .

**Comment by defstat** [comment]
@touhidurabir those changes should effect already existing endpoints that retrieve the user from the bearer authorization token? Should, for example, endpoints that have `$controller->addPolicy(new UserRolesRequiredPolicy($request), true);` defined in the `authorize` function be affected by this change?

**Comment by touhidurabir** [comment]
> should those changes affect the existing endpoints that retrieve the user from the bearer authorization token?

It should . What is does is that if a route does not have `HasUser` middleware attached, it will bypass the global middleware `DecodeApiTokenWithValidation` and `ValidateCsrfToken`. 

> will endpoints with `$controller->addPolicy(new UserRolesRequiredPolicy($request), true);` defined in the `authorize` function be affected by this change?

It will but not only by this change . As the API Routes now handle by laravel routing system, we need to determine the user and then attach it to `PKPRequest` where we get the user from `Illimuniate` request which is done in the another global middleware named `PolicyAuthorizer` . I did it this way to preserve the behaviour of our policy authorizers . Now when `HasUser` middleware not attached, the `DecodeApiTokenWithValidation`  and `ValidateCsrfToken` will be bypassed which in turn will not set the user in `Illimuniate` request which in turn will not able to set the user in `Registry` for `PKPRequest` to resolve user . For such routes, if `UserRolesRequiredPolicy` attached, it will throw `Authorization Deny` . And this is excepted as we are saying that a route will not have user so that means there should not be any roles to determine if there is not user . This is where we will need to think what authorization we will attach to which route and what behaviour we expect . 

@defstat is that clarify your question ? Or may be I am misunderstanding the question .

**Comment by defstat** [comment]
@touhidurabir, yes that answers my question, thanks a lot.
