### ISSUE TITLE
[OJS] Merging users messes up signoffs table

### ISSUE THREAD

**Issue by gpieri** [pkp/pkp-lib#1036]
When merging users the user_id in the signoffs table are updated incorrectly.

Suppose there are two users A and B. And A is merged into B (A will be removed).

Instead of updating the user_id of A into the user_id of B, the user_id of B is changed into the user_id of A.

This leads to inconsistencies in the database, and in certain cases breaks the Editing tab of the article.

**Comment by asmecher** [comment]
Cherry-picked also to ojs-dev-2_4 and omp-stable-1_1_1, thanks!
