### ISSUE TITLE
[OMP] Update the Onix schema version

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10365]
**Describe the bug**
In #10086 the version of the Onix schema used was updated for Onix exports. We should update the schema in other locations in OMP so they are consistent with each other, and we are using more up-to-date codelists.

Onix maintains backwards compatibilty in the code values, so there shouldn't be a need to handle values that are no longer part of the Onix schema. From [the documentation](https://www.editeur.org/14/Code-Lists/):

> To maintain backwards compatibility in respect of code values as well as message formats, code values, once published, are never deleted or substantively redefined. They may, however, be marked as ‘deprecated’, and replaced by new values; and their definitions may sometimes be revised to clarify the intended meaning or usage.

**What application are you using?**
OMP (all versions)

**Comment by bozana** [comment]
We can then try to update to ONIX 3.1 (Issue 66). 

We can use these translations:
- https://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/Translations/ONIX_Codelists_Translation_IT_66.xml ‘Official’ Italian (via **Informazione Editoriali**)
- https://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/Translations/ONIX_Codelists_Translation_ES_66.xml ‘Official’ Spanish (via **FGEE**)
- https://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/Translations/ONIX_Codelists_Translation_NB_66.xml Norwegian (via **Bokbasen**)
- https://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/ONIX_BookProduct_Codelists_Issue_66.xml EDItEUR's English original
- watch out for FR and FI (to come soon)

The new files are in different format, so we will probably need to adapt ONIXParserDOMHandler. If we need the XML file validation we can use https://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/ONIX_BookProduct_Codelist_Structure.xsd.

We would look how to best provide some attribution to EDItEUR and the organizations (in bold above) who did the translation work, together with a link to the EDItEUR license DOI:[10.4400/nwgj](https://doi.org/10.4400/nwgj).

**Comment by kaitlinnewson** [comment]
PRs ready for a first review @bozana:

- OMP main: https://github.com/pkp/omp/pull/1735
- pkp-lib main: https://github.com/pkp/pkp-lib/pull/10543 

A few notes/summary of the changes: 

- We are now using the XML format instead of XSD for the CodeList files, and I've included [all translations available in XML](https://www.editeur.org/14/Code-Lists/#Translations) format (Issue 66)
- Users will now see values that have been "Discontinued" (Deprecated) in the lists in ONIX. These have been kept in case a previously created publication was using one of these values, but appear at the bottom of the list and are labelled to discourage users from selecting them.
- The two lists that have been removed and replaced are List 7 (product forms, now using List 150), and List 95 (weight units, now using List 50).
- The CodeList files in the Native Import/Export plugin and the ONIX Export plugin have not been updated, and will be done in separate PRs.

**Comment by bozana** [comment]
Hi @kaitlinnewson, I took a look into the PRs and the changes look good :-)
I would also test it tomorrow... will then let you know...
Great work! Thanks a lot!

**Comment by kaitlinnewson** [comment]
For the second suggestion, there's a chance we could run into test failures if the hosted XSD is changed for a new version of ONIX that we aren't yet using - but I can't find a version online that is "locked" to our Issue (66).

**Comment by bozana** [comment]
I asked Alec if we need to validate these files every time tests are run -- it seems to me that this is not really necessary because they will probably never change and are actually the originals... but lets see what he says...
For now I think we can exclude them from validation, so we see if other tests pass...

**Comment by bozana** [comment]
Hi @kaitlinnewson, I have tested it roughly and find just one problem, s. the comment in the OMP PR.
Thanks!

**Comment by kaitlinnewson** [comment]
Hi @bozana, I've fixed that issue and added the files to the xml lint exclusions for the tests. Should be ready to go!

**Comment by bozana** [comment]
All merged, thus closing...
Thanks a lot @kaitlinnewson!
