### ISSUE TITLE
Editorial Reminder: miscalculation for inactiveDays (I think) 

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#10376]
**Describe the bug**
I think that the list of inactive submissions to the copyediting and production stages in the Editorial Reminder email is not the one that should appear.

Here's what I think is wrong:

```
diff --git a/jobs/email/EditorialReminder.php b/jobs/email/EditorialReminder.php
index fca40c30c7..c66f278579 100644
--- a/jobs/email/EditorialReminder.php
+++ b/jobs/email/EditorialReminder.php
@@ -115,7 +115,7 @@ class EditorialReminder extends BaseJob
 
             if (in_array($submission->getData('stageId'), [WORKFLOW_STAGE_ID_EDITING, WORKFLOW_STAGE_ID_PRODUCTION])) {
                 $lastActivityTimestamp = strtotime($submission->getData('dateLastActivity'));
-                if ($lastActivityTimestamp < strtotime('+30 days')) {
+                if ($lastActivityTimestamp < strtotime('-30 days')) {
                     /** @var WorkflowStageDAO $workflowStageDao */
                     $workflowStageDao = DAORegistry::getDAO('WorkflowStageDAO');
                     $outstanding[$submissionId] = __(

```

**Comment by asmecher** [comment]
@bozana, could you have a look at this one?

**Comment by bozana** [comment]
Hi @forgive38, sorry for my delay -- I haven't managed to take a look :-( I will be away for some days -- so even more delay to come :-( -- but I will come to this as soon as possible.
Thanks for understanding!

**Comment by bozana** [comment]
Hi @forgive38, I finally took a look, sorry for the delay :-(
Yes, I think you are right :-)
Would you like to make a PR?

**Comment by forgive38** [comment]
Hi,

PR: #10378
