### ISSUE TITLE
[OJS] MySQL 5.7.5 and Group By/Having

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#1038]
MySQL 5.7.5 introduced a new SQL mode which is on by default, [ONLY_FULL_GROUP_BY](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by). This change trips up one SQL query in the PLN plugin. In the SQL to [check for updated issues](https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/generic/pln/classes/DepositObjectDAO.inc.php#L115) the last column (`a.last_modified as article_modified`) is not aggregated, so MySQL logs an error.

> ERROR 1055 (42000): Expression #2 of SELECT list is not in GROUP
> BY clause and contains nonaggregated column 'mydb.t.address' which
> is not functionally dependent on columns in GROUP BY clause; this
> is incompatible with sql_mode=only_full_group_by

**Comment by asmecher** [comment]
Merged, thanks.
