### ISSUE TITLE
[OJS] Announcements are not visible at the published date

### ISSUE THREAD

**Issue by lepidus** [pkp/pkp-lib#1039]
Announcements are not visible at the published date. They only become visible the day after.

Announcement should be visible at the published date.

**Comment by asmecher** [comment]
Master branch port:
https://github.com/pkp/pkp-lib/commit/3d6029a40d060141375530aab2c68cf09bd7c2a8
(Typo: Commit message includes wrong bug number)

Thanks, @lepidus!

**Comment by gpieri** [comment]
You're welcome, @asmecher.

(Regarding the typo... I spotted it after submitting the PR, I thought had fixed it, sorry. We're using the issue number on the commit message, in this case 1039. Should we start using the PR number as in the master branch port?)

**Comment by asmecher** [comment]
No, that was my typo, not yours! Sorry, I wasn't clear.

**Comment by gpieri** [comment]
I see. I misinterpreted it. :-)

**Comment by gpieri** [comment]
Hi, @mfelczak. I updated the PR with the suggested changes. Let us know if there is any additional improvement.

**Comment by asmecher** [comment]
Merged the revised commit; will port around.
