### ISSUE TITLE
Assess cookie requirements for non-registered users

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#10401]
Currently we create sessions for all website visitors. Historically, this is done because we were using session variables to record things like the current locale.

Now that the current locale is in the URL for 3.5.0, we no longer need session variables for this. If there are no other pressing requirements for cookies/sessions for folks who are not logged in, we could look at making session creation happen when a user logs in.

Needs a survey to check for other implications -- e.g. for debouncing for stats, etc.

**Comment by asmecher** [comment]
(Tagging @touhidurabir for a think)

**Comment by touhidurabir** [comment]
I think the first requirement is to identify the routes for which user is not required and stop creating sessions for those routes . Creating/Starting of session done in the [PKP\core\Dispatcher](https://github.com/pkp/pkp-lib/blob/main/classes/core/Dispatcher.php#L115) after the work done as part of https://github.com/pkp/pkp-lib/issues/9566 . I believe from this is where we need to start making the adjustment . 

Challenges lies to identify before the route execute is that routes required users or not . For API (which has moved to Laravel routing tool set as part of https://github.com/pkp/pkp-lib/pull/9176) this may be doable easily as work done at https://github.com/pkp/pkp-lib/issues/10342 or may not even require much work at all . But for page routing, it depends `authorize` method of `Handler` class and if that has `UserRequiredPolicy` .  Determining that part and based on that starting session, I think that is the key but no easy to figure that out .

**Comment by asmecher** [comment]
Closing this as a duplicate of https://github.com/pkp/pkp-lib/issues/3624.
