### ISSUE TITLE
Discussion board notifications cannot handle disabled users

### ISSUE THREAD

**Issue by busspatrick** [pkp/pkp-lib#10402]
**Describe the bug**
When a discussion board contains a disabled/merged user as a participant or owner, email notifications will fail for all other members of the discussion board. See PHP error below:

<img width="992" alt="Screenshot 2024-09-12 at 1 27 38 PM" src="https://github.com/user-attachments/assets/489b989e-0d2c-4f91-9e2c-ea50a706873b">

Debugging the above, I've traced the problem to Line 351 in lib/pkp/controllers/grid/queries/QueryNotesGridHandler.php. Changing this line to the below resolved the error:

`if (!$recipient = Repo::user()->get($userId)) { continue; }`

**To Reproduce**
1. Create a test user that will later be merged/disabled.
2. While signed in as this user, create a discussion board within a submission.
3. Add other participants to the discussion board.
4. Confirm that messages to the discussion board are dispatching emails to the participants (you may need to verify the workflow's notification settings).
5. Delete/merge the test user that created the discussion board.
6. While signed in as a different user, attempt to reply to any message on the board. You should see the above error in the PHP error log.

**What application are you using?**
 OJS and OMP version 3.4.0-5

**Additional information**

<img width="838" alt="Screenshot 2024-09-10 at 5 59 17 PM" src="https://github.com/user-attachments/assets/b07554ef-262b-4c73-9cca-b475b6fcaaec">

**Comment by asmecher** [comment]
@busspatrick, thanks, I've adapted your change slightly to move the test earlier. Thanks for the very detailed report!

**Comment by busspatrick** [comment]
@asmecher You're very welcome. Thanks for addressing this so quickly.
