### ISSUE TITLE
Submission Checklist: Error adding new item when list is empty

### ISSUE THREAD

**Issue by felixhelix** [pkp/pkp-lib#10413]
**Describe the bug**
Once the submission checklist is empty, it is not possible to add an item.
The following error occurs:
`
PHP Fatal error:  Uncaught ValueError: max(): Argument #1 ($value) must contain at least one element in /var/www/html/ops/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php:98\nStack trace:\n#0 /var/www/html/ops/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php(98): max()\n#1 /var/www/html/ops/lib/pkp/controllers/grid/settings/submissionChecklist/SubmissionChecklistGridHandler.inc.php(147): SubmissionChecklistForm->execute()\n#2 /var/www/html/ops/lib/pkp/classes/core/PKPRouter.inc.php(397): SubmissionChecklistGridHandler->updateItem()\n#3 /var/www/html/ops/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()\n#4 /var/www/html/ops/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route()\n#5 /var/www/html/ops/lib/pkp/classes/core/PKPApplication.inc.php(360): Dispatcher->dispatch()\n#6 /var/www/html/ops/index.php(68): PKPApplication->execute()\n#7 {main}\n  thrown in /var/www/html/ops/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php on line 98, referer: https://...`

**To Reproduce**
1. Remove all items in the Submission Checklist.
2. Add new item

**What application are you using?**
OPS version 3.3.0.17

**Comment by touhidurabir** [comment]
@felixhelix I think this has been resolved in https://github.com/pkp/pkp-lib/issues/9849 and fix has been release in `3.3.0-18` . I see you are using `3.3.0.17` so an update should fix it .
