### ISSUE TITLE
[OJS] PLN Plugin updates deposits too frequently

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#1042]
The PLN plugin updates a deposit regardless of the deposit's status. Deposits that are being processed by the staging software, LOCKSSOMatic, or LOCKSS should not be changed before LOCKSS has reached agreement. Changing the deposits while they are being processed can cause the deposit package to be overwritten before it has been processed, which may cause a checksum mismatch.

**Comment by asmecher** [comment]
Merged, thanks!
