### ISSUE TITLE
[OJS 3.3 3.4] error 500 when creating a reviewer with keywords very similar (collation issue)

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#10423]
**Describe the bug**
When you create a reviewer with keywords like " the thé The" you'll get a 500.
Certainly due to collation with mysql (case insensitive accent insensitive)
(like in https://github.com/pkp/pkp-lib/blob/18b6660ea0ded9cfa4dd0bfe4cf400d6198c4313/classes/search/SubmissionSearchDAO.php#L99)

I try to set 
collation = utf8mb3_bin
in config.inc.php but not much better

I got the error on your testdrive 3.3 and 3.4

**Comment by asmecher** [comment]
Thanks, @forgive38, I've merged this for 3.4.0 and main!
