### ISSUE TITLE
Upgrade from 3.2 to last 3.3.0-19 crashes due wrong type in substr(): Argument #3

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#10445]
**Describe the bug**
When I upgrade from stable-3.2 to stable-3.3 (3.3.0-19) I got the following error:

```
2024-09-18 13:42:09 [migration: OJSv3_3_0UpgradeMigration]
PHP Fatal error:  Uncaught TypeError: substr(): Argument #3 ($length) must be of type ?int, string given in /var/www/html/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php:181
Stack trace:
#0 /var/www/html/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php(181): substr()
#1 /var/www/html/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php(120): OJSv3_3_0UpgradeMigration->_toJSON()
#2 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): OJSv3_3_0UpgradeMigration->{closure}()
#3 /var/www/html/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php(121): Illuminate\Support\Collection->each()
#4 /var/www/html/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php(37): OJSv3_3_0UpgradeMigration->_settingsAsJSON()
#5 /var/www/html/lib/pkp/classes/install/Installer.inc.php(406): OJSv3_3_0UpgradeMigration->up()
#6 /var/www/html/lib/pkp/classes/install/Installer.inc.php(252): Installer->executeAction()
#7 /var/www/html/lib/pkp/classes/install/Installer.inc.php(175): Installer->executeInstaller()
#8 /var/www/html/lib/pkp/classes/cliTool/UpgradeTool.inc.php(89): Installer->execute()
#9 /var/www/html/lib/pkp/classes/cliTool/UpgradeTool.inc.php(65): UpgradeTool->upgrade()
#10 /var/www/html/tools/upgrade.php(22): UpgradeTool->execute()
#11 {main}
  thrown in /var/www/html/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php on line 181
```

After this, the upgrade exits and the system is unusable.

**What application are you using?**
Dockerized OJS 3.2.1-4 > 3.3.0-19.

**Additional information**

I tested it with multiple journals (from same origin and destination versions) and upgrade crashes with all of them.
If I upgrade to 3.3.0-18, upgrade finishes but a different error is shown (posted in #9953)... so looks like this is an issue introduced in -19.
If I upgrade to 3.3.0-17, all works as expected so then you can upgrade to 3.3.0-19 without any trouble (but it's not a workaround because in -17 the data of the reviewer's form is mixed as documented in #9953).

If you can't reproduce the issue with the standard "datasets", I can provide a DB dump.

**Comment by asmecher** [comment]
This was introduced with https://github.com/pkp/ojs/pull/4379 -- the call to `substr` looks to be incorrect, and newer versions of PHP are cashing due to a type mismatch. @jonasraoni, can you have a look?

**Comment by asmecher** [comment]
The following patches should correct it:
- OJS 3.3.0-x: https://github.com/pkp/ojs/commit/a5c7b3e3f378698874931be50e5adb54a7310272
- OJS/OMP/OPS 3.4.0-x: https://github.com/pkp/pkp-lib/commit/3ba2e29b1c9ea3364d39b6c63d280ea96276b4e2 (in `lib/pkp`)

@marcbria, I've added these directly to `stable-3_3_0` and `stable-3_4_0`. If you can confirm that they resolve the error message, that will help!

**Comment by marcbria** [comment]
Wow... that was fast. :-)
I will test it tomorrow morning!
Thanks Alec and Jonas.

**Comment by marcbria** [comment]
I confirm the patch works as expected.
