### ISSUE TITLE
OJS 3.4 (multiple versions): plugins showing "Can be upgraded" in gallery when no newer version exists

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/pkp-lib#10440]
After upgrading from OJS 3.4.0.5 to 3.4.0.7, multiple plugins show "Can be upgraded" in the plugin gallery; however, no newer plugin is available.

For example, the QuickSubmit plugin shows "Can be upgraded" even though we are running v1.0.7.2 released on 2024-04-12, which is the most recent version available in GitHub. If I click "Upgrade" for the plugin in the gallery, I get an error message saying "Plugin already installed, and is newer than the version available in the gallery." The plugin then continues to show "Can be upgraded" in the gallery.

This is currently happening on our only two journals running 3.4. We upgraded both from 3.4.0.5 to 7 at the same time. We encountered a similar issue with both journals when we upgraded from 3.4.0.4 to 3.4.0.5.

This issue appears which each installed plugin on both journals *except* ORCiD Profile.

**Comment by kaitlinnewson** [comment]
Hi @tmrozewski-york, this might be caused by a discrepancy between what is in the database and the version of the plugin code. Can you check your `versions` table in the database and check the version for one of the plugins showing the error, e.g. QuickSubmit?

**Comment by kaitlinnewson** [comment]
Thanks @tmrozewski-york, things look alright in your database. Can you also confirm that the plugin files are present on the server? You can either try using the plugin and see if it's working and appearing for you in the UI, or ask your IT support to check in the file system with something like `ls plugins/importexport/quickSubmit/`.

**Comment by tmrozewski-york** [comment]
@kaitlinnewson my IT says there are not plugin files for quickSubmit

**Comment by kaitlinnewson** [comment]
@tmrozewski-york Can you try installing the plugin with the "Upload a New Plugin" functionality and see if that does the trick to replace those files on the server? You can download the [release package for QuickSubmit on GitHub for your version here](https://github.com/pkp/quickSubmit/releases/tag/v1_0_7-2) (the `.tar.gz` file). Alternatively, you could unpackage the release directly onto the server in `plugins/importexport/quickSubmit/.`

**Comment by tmrozewski-york** [comment]
@kaitlinnewson manually installing it with the tar.gz worked (it had worked when we were running 3.4.0.5 as well). Anyway what's causing this to happen?

**Comment by kaitlinnewson** [comment]
@tmrozewski-york Currently the "can be upgraded" message is shown when either the version in the database is older than what's in [the plugin gallery `plugins.xml`](https://github.com/pkp/plugin-gallery), or when the files on the server are missing. This messaging could be improved in the second case (which is what was happening in your QuickSubmit plugin), perhaps to show a message about "missing plugin files" instead.

Previously there was a workaround where clicking the "upgrade" button would download the files again, but it looks like this [was changed here](https://github.com/pkp/pkp-lib/blame/97635b0ca0c6630e8792ac6aa4b7971b433924b9/classes/plugins/PluginHelper.php#L200). @jonasraoni what do you think about reverting the change in this line?

As for why the plugin files are missing, that would take some more investigating. Are you doing anything with plugins during the upgrade process?

**Comment by tmrozewski-york** [comment]
> As for why the plugin files are missing, that would take some more investigating. Are you doing anything with plugins during the upgrade process?

I'm not sure about the upgrade script we're using in-house. I'll speak with the team here about it. Any suggestions about where we should be looking or what we should look for?

**Comment by kaitlinnewson** [comment]
@tmrozewski-york I'd take a look at anything related to plugins in your script to start - for instance, is there a point where plugin files are being deleted, moved, or not carried over into the upgraded install in some way?

**Comment by asmecher** [comment]
> As for why the plugin files are missing, that would take some more investigating.

I suspect the plugin files are not being brought across during upgrade, which is the correct outcome of the upgrade process. When upgrading from 3.3.x to 3.4.x, for example, the 3.3.x plugin files *should not* be copied across into the 3.4.x directory tree.

**Comment by tmrozewski-york** [comment]
@asmecher you nailed it - turns out we'd adapted the 3.4.x.x. script from the 3.3 > 3.4 script and not from the 3.3.x.x upgrade script. Thanks for the lead, and sorry to mobilize you both for this one!
