### ISSUE TITLE
Extend Invitation Toolset support

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#10459]
**Describe the change**
Enhancement of the Invitation API and General Invitation Toolset

**Invitation API Changes**:
- [x] **Role Assignment**: Extend the Invitation API to support Role Assignment for both existing and new users.
- [x] **Validation Handling**: Implement [Laravel's Validation API](https://laravel.com/docs/11.x/validation) to improve the handling of validation errors in the Invitation API.
- [x] **API Resources**: Use [Laravel API Resources](https://laravel.com/docs/11.x/eloquent-resources) to return the Invitation object in a consistent format.

**General Invitation Toolset Changes**:
- [x] **Invitation Structure**: Change the invitation structure so that each invitation is placed in its own folder.
- [x] **Code Reduction**: Refactor the invitation toolset to minimize code. Specifically, move the accept/decline logic to dedicated handlers (e.g., API Handlers) to reduce complexity in the invitation logic.
--- 
**PRs**

PKP-LIB: https://github.com/pkp/pkp-lib/pull/10472

OJS: https://github.com/pkp/ojs/pull/4448
OMP: pkp/omp#1708
OPS: pkp/ops#778

**Comment by defstat** [comment]
@asmecher everything merged

**Comment by asmecher** [comment]
Excellent, thanks! :tada:
