### ISSUE TITLE
UI improvements PKP PLN plugin's status page

### ISSUE THREAD

**Issue by mjordan** [pkp/pkp-lib#1045]
Currently the PLN plugin's status page presents a somewhat cryptic matrix of 'Y' and 'N's, and determining a given deposit's status is somewhat difficult. We should make this page easier to understand, and provide some information about what each of the status indicators means. @ubermichael has some mockups that do a much better job of conveying status information.

**Comment by ubermichael** [comment]
This is where I'm at right now. It's working and I'm mostly happy with it. I'm not ready to send a PR yet, but you can [preview the changes](https://github.com/pkp/ojs/compare/ojs-dev-2_4...ubermichael:pln-status-page?expand=1).

![status-page](https://cloud.githubusercontent.com/assets/1328893/12402323/f674d3e0-bde0-11e5-89c8-205dfdced617.png)

**Comment by mjordan** [comment]
Very nice.

**Comment by asmecher** [comment]
Merged, thanks, @ubermichael -- though I didn't test it, I only read the code.

**Comment by mjordan** [comment]
I don't think the links out to explanations of the various statuses were in this PR. @ubermichael we can do finish these on Monday.
