### ISSUE TITLE
Add ability to save submission step 3 without submitting document

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1046]
From SI:

> There’s no “save and finish later” option on Tab 3—requires immediate submission to save data entered on Tab 3

**Comment by asmecher** [comment]
I decided to add a 4th step as a "landing pad" rather than add 2 buttons to the bottom of the step 3 form ("save" and "complete submission") because I thought that would be less confusing.

Pulls:
https://github.com/pkp/pkp-lib/pull/1053
https://github.com/pkp/omp/pull/194

@beghelli, could you review this? Thanks!

**Comment by beghelli** [comment]
Done, just two comments.

**Comment by asmecher** [comment]
Thanks!

**Comment by asmecher** [comment]
OJS pull: https://github.com/pkp/ojs/pull/708

**Comment by asmecher** [comment]
Another PR required for this issue to correct a URL generation problem:
https://github.com/pkp/pkp-lib/pull/1077

**Comment by asmecher** [comment]
Re-opening for https://github.com/pkp/pkp-lib/pull/1077 (@beghelli to review)

**Comment by NateWr** [comment]
Um, what happened here? It says I closed this issue today but I don't recall doing so...

**Comment by asmecher** [comment]
I'm not sure either; I know github does parse comments for verbs like "closes"...? but I didn't see anything go past either.

**Comment by beghelli** [comment]
Merged #1077

**Comment by asmecher** [comment]
Thanks, @beghelli!
