### ISSUE TITLE
[OJS] DataCite export plugin seems to set the article acceptance date as the first date of the editorDecisions collection and not the last one as it is supposed to be

### ISSUE THREAD

**Issue by sbirAECA** [pkp/pkp-lib#10470]
In the file ojs/plugins/generic/datacite/filter
/DataciteXmlFilter.php on line 472 when performing a reverse it seems to place the oldest date as the first and not the last.

**Comment by asmecher** [comment]
@sbirAECA, you're referring to https://github.com/pkp/ojs/blob/c05ad0fc1e093ab6edef80afd867ba6674a841c7/plugins/generic/datacite/filter/DataciteXmlFilter.php#L472. I think the decision to use the first "accept" decision was intentional, but @bozana may be able to add more details.

**Comment by bozana** [comment]
Hi @sbirAECA, yes I think it is correct to use the first date when the decision was accepted.
