### ISSUE TITLE
Suggest adding rel="nofollow" to links used by citation plugin

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#10474]
**Describe the bug**
The citation style language plugin depends upon a list of citation formats with full links containing information to generate the citation format, e.g. 

`....../citationstylelanguage/get/associacao-brasileira-de-normas-tecnicas?submissionId=21727&publicationId=29453`

And these links can be crawled by search engines and can end up being found in results, looking like:

![SPEE_URL](https://github.com/user-attachments/assets/eafc7d39-0573-4ce5-8b73-3051275b6026)

Suggest adding a `rel="nofollow"` attribute to the anchor tag used in the `article_details.tpl` template to prevent these from being indexed.  

https://github.com/pkp/ojs/blob/stable-3_3_0/templates/frontend/objects/article_details.tpl#L350

Google seems to really like to crawl these:

![Screenshot from 2024-09-26 10-21-34](https://github.com/user-attachments/assets/88d088e3-a302-4582-aa78-8a8376408a5e)

**What application are you using?**
OJS 3.3 and 3.4

**Comment by kaitlinnewson** [comment]
PR for review to 3.3 @asmecher : https://github.com/pkp/ojs/pull/4449

Some other discussion of this issue can be found in https://github.com/pkp/ojs/pull/2465. I went with the "nofollow" solution as an alternative to changes to robots.txt, and am assuming we won't be making major changes to the citations in 3.3.

If approved, I'll forward-port to the citationStyleLanguage plugin for 3.4/main, as [this part of the template has been moved](https://github.com/pkp/citationStyleLanguage/blob/main/templates/citationblock.tpl).

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson, that makes sense. Please go ahead and port and merge forward! I've merged the `stable-3_3_0` PR.

**Comment by kaitlinnewson** [comment]
Forward-ported and merged!

@asmecher Are submodule updates also needed for 3.4/main, or will that be done closer to the next releases?

**Comment by jnugent** [comment]
Hi @kaitlinnewson the PKP PS team appreciates having the submodule updates in stable-3_4 as they are needed because we track the stable branches for our hosted installations, rather than working off of release packages.  We routinely update installs by just pulling down recent commits and updating sub modules as necessary.

**Comment by kaitlinnewson** [comment]
Submodule update PRs -

3.4: 
- OJS: https://github.com/pkp/ojs/pull/4454
- OMP: https://github.com/pkp/omp/pull/1712
- OPS: https://github.com/pkp/ops/pull/781

main:
- OJS: https://github.com/pkp/ojs/pull/4455
- OMP: https://github.com/pkp/omp/pull/1713
- OPS: https://github.com/pkp/ops/pull/782

@bozana Are you able to merge the 3.4 submodule PRs? This is already done for 3.3 as the change was in the core theme then and not in the CSL plugin.

**Comment by bozana** [comment]
All merged... :-)

**Comment by kaitlinnewson** [comment]
Thanks @bozana! Closing this as completed.
