### ISSUE TITLE
Assistant permission role should be able to list access GET /participants endpoint

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10481]
**Describe the bug**
As Assistant - in current workflow interface - I am able to see list of Participants (with reduce action list).

But on new side modal workflow I am getting

http://localhost:7003/index.php/publicknowledge/api/v1/submissions/15/participants
```
{
    "error": "user.authorization.roleBasedAccessDenied",
    "errorMessage": "The current role does not have access to this operation."
}
```

**What application are you using?**
 OJS, OMP or OPS version 3.5

**Comment by taslangraham** [comment]
Created a PR with the fix @jardakotesovec.

PR (pkp-lib)- https://github.com/pkp/pkp-lib/pull/10482/files

 Submodule updates:
- [ojs](https://github.com/pkp/ojs/pull/4451/files)
- [ops](https://github.com/pkp/ops/pull/779/files)
- [omp](https://github.com/pkp/omp/pull/1709/files)

**Comment by ewhanson** [comment]
Thanks, @taslangraham! Looks good. 

I was going to merge them (and did merge pkp-lib) but saw afterwards that the submodules need updating for OJS. pkp-lib is already merged, but could you rebase the submodule updates and merge those? Thanks!

**Comment by taslangraham** [comment]
All updated and merged @ewhanson
