### ISSUE TITLE
Add support for module script tags to support Vite

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#10492]
**Describe the bug**
I want to use [Vite](https://vitejs.dev/), a modern asset bundler, when developing a custom OJS theme. However, it is not possible to load the JavaScript assets using the `TemplateManager::addJavaScript()` function, because it does not support module script tags. 

```
<script type="module" src="..."></script>
```

I can work around this in my own theme. However, I am preparing a Composer package to make the setup easier for the community. It would be best for this use case if I could integrate directly with the `{load_scripts}` template tag.

**To Reproduce**
I am aware that this is _not_ a bug and I of all people campaigned to keep requests out of the issues. :laughing: But I have a PR incoming.

**What application are you using?**
I'd like this to go back to OJS 3.3 if possible, for a client.

**Comment by NateWr** [comment]
The following PRs add this feature by extending the `$args` param of `TemplateManager::addJavaScript()`. To load a module script, you can use the following code:

```php
$templateMgr->addJavaScript('path/to/script.js', ['type' => 'module']);
```

If you approve this change, I can prepare PRs for OMP/OPS as well as `stable-3_4_0` and `main`.

PRs:
https://github.com/pkp/pkp-lib/pull/10493 (stable-3_3_0)

Tests:
https://github.com/pkp/ojs/pull/4456 (stable-3_3_0)

**Comment by NateWr** [comment]
@jardakotesovec thanks, I hadn't considered that. I did a little bit of googling and found the [output.format](https://rollupjs.org/configuration-options/#output-format) option for rollup. However, this didn't solve the problem when running in dev mode, using HMR. I think the rollup option is only for the final build.

Do you know a way to get this working with the HMR server?

**Comment by NateWr** [comment]
Thanks @jardakotesovec. I can prepare PRs for all the branches needed for the backport. It looks like a [few tests failed](https://github.com/pkp/ojs/actions/runs/11141193245), but looks to me like timeout errors. I'm not familiar with the normal pass/fail rate these days. Is it possible to run these again or would you be comfortable merging like this?

**Comment by NateWr** [comment]
@jardakotesovec I've added pull requests for `stable-3_3_0`, `stable-3_4_0` and `main` now. I didn't create tests for each one out of laziness. If you'd like to see test PRs for all apps for each branch let me know.

**Comment by NateWr** [comment]
@jardakotesovec just following up on this. It looks like the PR to `main` was merged but not the ones to the stable branches.

**Comment by jardakotesovec** [comment]
@NateWr done, sorry for delay.
