### ISSUE TITLE
Clicking a notification title in the task list does not redirect to the url

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10495]
**Describe the bug**
In a user's notifications tasks list, clicking the title of the notification is not redirecting to the correct url related to that notification

**To Reproduce**
1. Login as a user that has task notifications (e.g "dbarnes")
2. Open the tasks list in the upper right corner
3. Click the title of a notification
4. See that it is marked as read, but does not redirect to the appropriate url

**What application are you using?**
 OJS, OMP or OPS main

PRs:
- pkp-lib: https://github.com/pkp/pkp-lib/pull/10603

**Comment by jardakotesovec** [comment]
@kaitlinnewson yeah I noticed this issue as well, thanks for filling it...  hopefully will get to it sometime soon.

**Comment by jardakotesovec** [comment]
@Tribunal33 Should be addressed on main. Can you give it a try? Thank you!

**Comment by Tribunal33** [comment]
Both bell icon displays list of alert notifications and the links within the alerts page are functioning when selecting them.  I would say that they are redirecting to old submission workflows, but I think it is out of scope for this particular ticket.  @jardakotesovec what do you think can we close this?  I checked OMP and OJS alert bell.

**Comment by jardakotesovec** [comment]
@Tribunal33 Oki, I added note to https://github.com/pkp/pkp-lib/issues/10670 make sure I don't forget it when I get to the redirects and having correct links within apps.
