### ISSUE TITLE
[OCS] Add review form responses to reviews report

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#1050]
Currently only free-form comments are included. Port to OJS as well.

**Comment by asmecher** [comment]
Merged for OCS 2.3.7; needs porting to OJS 2.4.x (and beyond?)

**Comment by mfelczak** [comment]
Thanks @asmecher.

Would you like me to cherry-pick this over to OCS master in addition to porting it over to ojs-dev-2_4?

**Comment by asmecher** [comment]
No, OCS master is abandoned. Any further work on a futuristic OCS will mean a rewrite rather than resumption of development there.

**Comment by mfelczak** [comment]
Ok, thanks -- I'll port this to ojs-dev-2_4.

**Comment by asmecher** [comment]
Thanks, @mfelczak!
