### ISSUE TITLE
/submissions/{submissionId} does not return all reviewRound on OMP

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10515]
**Describe the bug**
When having review round both in internal and external reviewRound in OMP - I get in the API only the external review round.

GET /submissions/{submissionId} 
reviewRounds field

Cause is likely here, when its keyBy round, and if there is one review round in internal and external - both of these have round 1 and therefore only one wins.

```
    protected function getReviewRoundsFromSubmission(Submission $submission): Collection
    {
        $reviewRoundDao = DAORegistry::getDAO('ReviewRoundDAO'); /** @var ReviewRoundDAO $reviewRoundDao */

        return collect($reviewRoundDao->getBySubmissionId($submission->getId())->toIterator())
            ->keyBy(fn (ReviewRound $reviewRound) => $reviewRound->getData('round'));
    }

```

**What application are you using?**
OMP 3.5

**Comment by taslangraham** [comment]
Ready for review @ewhanson 
PR - https://github.com/pkp/omp/pull/1732

**Comment by taslangraham** [comment]
@ewhanson actually, no. It's not ready for review. I think I may have overlooked something.

**Comment by taslangraham** [comment]
Ready for review now @ewhanson.
PR - https://github.com/pkp/omp/pull/1732

**Comment by ewhanson** [comment]
Thanks, @taslangraham. Looks good to me! Once the tests finish running, feel free to merge.

**Comment by taslangraham** [comment]
Merged!
