### ISSUE TITLE
[OMP] redirection gives PHP error when visiting dashboard

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1051]
This is against `HEAD` of OMP. Initial visit to the site’s sole press does not create errors, but when a logged-in user goes to the dashboard, this shows up in the error log:
```
PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/omp_dev/cache/t_compile/16cc5eda4ddacef5f7baf596cadfb96e2f432910^%%56^561^5616391A%%minifiedScripts.tpl.php:35) in /var/www/omp_dev/lib/pkp/classes/core/PKPRequest.inc.php on line 102, referer: http://.../omp_dev/index.php/pww_test
```

**Comment by asmecher** [comment]
Fixed -- I thought I already did but it must've gone into an unmerged branch.

**Comment by crism** [comment]
Seems to have done it—thanks, @asmecher!
