### ISSUE TITLE
Allow plugins to extend the categories of the Publisher Library

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#10521]
**Describe the feature**
The Publisher Library allows journal managers to upload files to one of four categories. These categories are fixed and cannot be modified. 

I propose that we add hooks which allow plugins to extend the categories. This will allow a plugin to make use of files uploaded to the Publisher Library.

**Use Case**
I have two clients who want a consistent way for journal managers to upload and manager logos for their partner institutions. This is a common challenge which journals often solve by injecting logos into the `pageFooter`, `additionalHomepageContent`, or a custom sidebar block. 

These approaches do not provide sensible design constraints, so logos are often wildly different sizes and not aligned well. You can see some common examples of this UI pattern [here](https://dribbble.com/shots/24793990-Client-logos-in-card) and [here](https://elfsight.com/logo-showcase-widget/templates/logo-grid/).

**What application are you using?**
3.3.x

**Additional information**
If the PRs are accepted, my client plans to support me in publishing a "Partner Logos" plugin so the community can benefit from this.

**Comment by NateWr** [comment]
PR:
- https://github.com/pkp/pkp-lib/pull/10522 (`stable-3_3_0`)

Tests:
- https://github.com/pkp/ojs/pull/4470 (`stable-3_3_0`)

**Comment by NateWr** [comment]
It looks like the postgres tests are failing in a way that doesn't look likely to be related to this PR:

> psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"

**Comment by NateWr** [comment]
@asmecher Jonas re-ran the tests for me and they're still failing on a postgres connection error. It looks like all the pgsql tests failed in the last commit to `stable-3_3_0` too, but not on this connection error: https://github.com/pkp/ojs/commits/stable-3_3_0/

**Comment by NateWr** [comment]
@asmecher All tests are passing. Can you review? Or should I ping someone else?

**Comment by asmecher** [comment]
All merged, thanks -- I'll take care of the submodules between now and the next release.
