### ISSUE TITLE
[OJS] OJS3b1 assertion error

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1052]
```
PHP Warning:  assert(): Assertion failed in /var/www/ojs3/lib/pkp/classes/db/DAO.inc.php on line 515, referer: http://.../ojs3/index.php/pww_test/user/register
```
In `updateDataObjectSettings()`, some field’s data is not an array… not sure which field(s) is/are triggering this, though.

**Comment by asmecher** [comment]
I think that's a duplicate of https://github.com/pkp/pkp-lib/issues/694.

**Comment by crism** [comment]
I think you’re right, @asmecher.
