### ISSUE TITLE
Add to single submission endpoint which editorial decisions are available 

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10537]
**Describe the issue**
While migrating workflow page to side modal, I would like to get information from API which editorial decisions are currently available for active stage.

For some decisions there is not trivial logic when to display them and is good to expose it via API rather than duplicate on client side, because server side needs to know that anyway to decide whether it allows to trigger given decision.

As discussed with @Vitaliy-1 , we could add following:

GET /submissions/{submissionId}
```
{
  ...
  stages: [{
    id: 1
    availableEditorialDecisions: [{id, label}]
  }]
  ...
}
```

Since editorial decisions can be applied for active stage - these can be calculated only for active stage.

Here is current logic, which would be moved over to the API: https://github.com/pkp/ojs/blob/1ff4fa17320fff1e219be7dec49dd027d82fd26f/pages/workflow/WorkflowHandler.php#L230

OMP&OPS has its own logic - these should be included as part of this logic as well.

**What application are you using?**
 OJS, OMP or OPS version main

**Comment by taslangraham** [comment]
Ready for review @ewhanson 


**PRs**
- pkp-lib: https://github.com/pkp/pkp-lib/pull/10549/files
- ojs: https://github.com/pkp/ojs/pull/4484/files
- ops: https://github.com/pkp/ops/pull/796/files
- omp: https://github.com/pkp/omp/pull/1738/files

**Comment by ewhanson** [comment]
Thanks @taslangraham. One minor style request in OPS, otherwise looks good! Feel free to merge after that.

**Comment by taslangraham** [comment]
Thanks for the review @ewhanson. I've made the stylistic change and merged the PRs!
