### ISSUE TITLE
OJS 3.3.x (loading) in stage (submission, review, etc...)

### ISSUE THREAD

**Issue by arifadli** [pkp/pkp-lib#10531]
![image](https://github.com/user-attachments/assets/ce6ba5dc-2888-4a59-ac56-0fb9a946e897)
OJS 3.3.x (loading) in stage (submission, review, etc...)

Please help me

**Comment by asmecher** [comment]
@arifadli, please start by posting on our support forum (https://forum.pkp.sfu.ca); include the exact version of OJS you're using, and any relevant details from your PHP error log. If it turns out to be a bug, we'll migrate it back here.
