### ISSUE TITLE
Reviewer history shows "Confirmed" for both accepted and declined reviews

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#10546]
**Describe the bug**
"History" option under individual reviewer's name in the workflows shows a brief timestamped snapshot of actions related to that reviewer. Whether a reviewer has accepted to review or declined, the status is always "Confirmed" which is confusing to editors as it can be understood as "accepted". The correct status is visible both next to the reviewer's name and in the Activity Log.

**To Reproduce**
1. Log in as a Reviewer and decline a review
2. Return to the editorial workflow and verify that reviewer's name is marked with "Request Declined" and the same action is recorded in the Activity Log
3. Open "History" under the reviewer's name. It shows "Confirmed" corresponding to the timestamp of when the review was Declined.
4. Repeat the same steps, but this time accept to review. 
5. Open "History" under the reviewer's name. It shows "Confirmed" corresponding to the timestamp of when the review was Accepted.

**What application are you using?**
 OJS 3.3 and 3.4

Screenshot from Reviewer History

![image](https://github.com/user-attachments/assets/bf86454b-7147-4b3d-a114-22f3a655c3fd)

Screenshot from the Activity Log

![image](https://github.com/user-attachments/assets/a2d38add-92fc-4e7d-a3c0-f74b521eb4fd)

**Comment by taslangraham** [comment]
Ready for review. @kaitlinnewson do you mind taking a look? 

### PRs

- [pkp-lib main](https://github.com/pkp/pkp-lib/pull/10615/files)
- [pkp-lib stable 3.3](https://github.com/pkp/pkp-lib/pull/10613/files)
- [pkp-lib stable 3.4](https://github.com/pkp/pkp-lib/pull/10614/files)

**Submodule updates**

- [ojs main](https://github.com/pkp/ojs/pull/4521/files)
- [ojs stable 3.3](https://github.com/pkp/ojs/pull/4523/files)
- [ojs stable 3.4](https://github.com/pkp/ojs/pull/4522/files)

- [omp stable-3.4](https://github.com/pkp/omp/pull/1767/files)
- [omp stable 3.3](https://github.com/pkp/omp/pull/1766/files)
 
- [ops stable 3.3](https://github.com/pkp/ops/pull/812/files)
- [ops stable 3.4](https://github.com/pkp/ops/pull/811/files)

**Comment by kaitlinnewson** [comment]
@taslangraham looks good to me and confirmed that it fixes the bug - just one minor comment on the 3.3 PR that would apply to all 3 branches.
