### ISSUE TITLE
Unexpected ISSN behaviour in DOI metadata registration

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#10541]
**Description**
OJS can record both a print and electronic ISSN. Currently, we push _one_ of these ISSNs to Crossref's schema as part of our metadata deposit. If both exist, the one that gets prioritized is the _print_ ISSN. That probably shouldn't be the case. I'm flagging this as low priority, _but_ it's worth noting that ISSN is a mechanism by which Crossref connects members and prefixes to specific journals and unusual behaviour here could result in some pretty big headaches. 

**To Reproduce**
1. With two ISSNs configured in journal settings, assign a DOI
2. Check the registration agency plugin (in this case, Crossref)
3. Export the XML file
4. Search for ISSN to see which was recorded.
5. If both ISSNs were populated, you'll only see the print ISSN in the deposited XML. 

**What application are you using?**
Can confirm this is occurring in 3.3.0.17 and, were I to hazard a guess, is probably happening in 3.4. I'm a little amazed I've never noticed this before, actually. 

**Additional information**
Crossref, at least, allows for both a print and electronic ISSN simultaneously via XML attribute. (See https://data.crossref.org/reports/help/schema_doc/5.3.1/common5_3_1_xsd.html#issn and also https://data.crossref.org/reports/help/schema_doc/5.3.1/index.html) 

It might also be worth checking to see if this behaviour is mirrored with the DataCite plugin as well. In either event, were we only choosing _one_ canonical ISSN for DOI registration, it really should be the electronic one. I'd recommend patching 3.3 for this if possible, given the volume of users on that release version.

**Comment by AhemNason** [comment]
I can't get this to repeat anymore, and it seems like both ISSNs are doing what they're supposed to. But, I need a sanity check on this. Was there a wrinkle in time? Two of us ran into this issue at the same time and now it longer appears to be happening. But if someone could confirm the logic that would be just dandy.

**Comment by kaitlinnewson** [comment]
Hey @AhemNason, it looks like the ISSNs are handled here in 3.3:

https://github.com/pkp/ojs/blob/aae7f7f877dc7d9e26bbffce46a48ab32ca0aa5b/plugins/importexport/crossref/filter/IssueCrossrefXmlFilter.inc.php#L158-L167

```php
/* Both ISSNs are permitted for CrossRef, so sending whichever one (or both) */
if ($ISSN = $context->getData('onlineIssn') ) {
	$journalMetadataNode->appendChild($node = $doc->createElementNS($deployment->getNamespace(), 'issn', $ISSN));
	$node->setAttribute('media_type', 'electronic');
}
/* Both ISSNs are permitted for CrossRef so sending whichever one (or both) */
if ($ISSN = $context->getData('printIssn') ) {
	$journalMetadataNode->appendChild($node = $doc->createElementNS($deployment->getNamespace(), 'issn', $ISSN));
	$node->setAttribute('media_type', 'print');
}
```

This should assign both the online and print ISSNs when they are set, starting with online. In 3.3 at least, it doesn't look like this code has been touched recently. I did a quick check on my local dev setup for 3.3 and confirmed it populated both ISSNs.

**Comment by AhemNason** [comment]
I'm going to chalk this up to a solar flare or something. A library colleague said this was happening in real time. I looked on a local install and confirmed it was happening, and then _all evidence since_ suggests that, not only is it not happening, but it maybe never did. What a week. I'll close this out. Thanks for looking @kaitlinnewson!
