### ISSUE TITLE
[OMP] Update Onix schema in export plugins

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10561]
Along with update the Onix files used in the core of OMP (https://github.com/pkp/pkp-lib/issues/10365), we need to update the versions in the Native Export & Onix Export plugins to get everything up to a recent release of the schema. Work will also need to be done to address #10173 alongside this issue in order to use the new version. 

**What application are you using?**
OMP main branch

**Comment by kaitlinnewson** [comment]
PR ready for a first review @bozana:

- OMP main: https://github.com/pkp/omp/pull/1753

This also resolve the record reference issue in #10173.

**Comment by bozana** [comment]
Hi @kaitlinnewson, that all looked good to me. I have merged it and will thus close the issue.
Thanks a lot!
