### ISSUE TITLE
Update of settings by Eloquent doesn't insert new values or delete rows with new values

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#10562]
**Describe the bug**
The current implementation of the update statement in the extended Eloquent isn't suitable for the settings data model. Considering the example:
```sql
UPDATE announcement_settings SET setting_value = 
CASE WHEN setting_name='title' AND locale='en' THEN 'English Title' WHEN setting_name='title' AND locale='fr_CA' THEN 'French TItle' ELSE setting_value END
WHERE announcement_id = 16;
``` 
It doesn't allow to remove null values of already existing settings. Considering the example, if we already have a database record:
| announcement_setting_id | announcement_id | locale  | setting_name | setting_value |
| -------------------------- | ------------------ | ------- | ------------- | -------------- |
| 1 | 1 | en | title | Title in English |
| 2 | 1  | fr_FR | title | Title in French |

Then, trying to update with 
```php
$announcement->title = [
  'fr_FR' => Title in French modified
];
$announcement->save();
```
won't remove the title in English:
| announcement_setting_id | announcement_id | locale  | setting_name | setting_value |
| -------------------------- | ------------------ | ------- | ------------- | -------------- |
| 1 | 1 | en | title | Title in English |
| 2 | 1  | fr_FR | title | Title in French modified|

**update** - The EntityDAO behaviour is to remove values explicitly set to `null`, e.g.
```php
$announcement->update(
  'title' => [
    'en' => null,
    'fr_FR' => 'Title in French modified'
  ],
)
```
Also, we need to insert new settings during update. 
We have two places in the code, where the logic is implemented:

- Old DAO: https://github.com/pkp/pkp-lib/blob/b4bb4998b136322019e59a2ccc5de439c774e7bc/classes/db/DAO.php#L432
- EntityDAO: https://github.com/pkp/pkp-lib/blob/b4bb4998b136322019e59a2ccc5de439c774e7bc/classes/core/EntityDAO.php#L190

@touhidurabir's proposal: https://github.com/pkp/pkp-lib/pull/10324/files#diff-4dcc09fe73d537128c17c4bbb260ad4ba24ccc0ecb8cdc7d0b47ebc7986e2cedR79-R129

**What application are you using?**
 OJS, OMP or OPS main branch

**Comment by Vitaliy-1** [comment]
PR pkp-lib: https://github.com/pkp/pkp-lib/pull/10542
tests: https://github.com/pkp/ojs/pull/4496

**Comment by Vitaliy-1** [comment]
When Entity DAO is updated, all object attributes are passed for the update statement. E.g., if issue description is updated:
```
[id] => 1
[journalId] => 1
[volume] => 1
[number] => 2
...
[description] => Array
    (
        [en] => <p>Updated description</p>
        [fr_CA] => 
    )

[title] => Array
    (
        [en] => 
        [fr_CA] => 
    )
```
Moreover, all other settings associated with the Entity are removed: https://github.com/pkp/pkp-lib/blob/72087f4dabb1e80629b33639e3568501fd309fe2/classes/core/EntityDAO.php#L203 This behaviour is preserved in the PR

For the Model it would be only:
```
[description] => Array
    (
        [en] => <p>Updated description</p>
        [fr_CA] => 
    )
``` 

If the model doesn't have schema, the default data is composed from Model properties: https://github.com/Vitaliy-1/pkp-lib/blob/i10292_update_settings/classes/core/SettingsBuilder.php#L76

**Comment by Vitaliy-1** [comment]
@touhidurabir, can you take a look?

**Comment by touhidurabir** [comment]
@Vitaliy-1 see the comment at https://github.com/pkp/pkp-lib/pull/10542#issuecomment-2475346476
