### ISSUE TITLE
[OMP] Update Onix version in Native Export plugin to match Onix Export plugin

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10560]
**Describe the bug**
In OMP 3.3/3.4, the Onix export plugin was updated to Issue 24. We want to update the Native export plugin as well, which also contains Onix code lists and xsd files and is using the Onix export plugin filter class.

**What application are you using?**
OMP 3.3/.4

**Comment by kaitlinnewson** [comment]
PRs ready for review @bozana:

- OMP 3.3: https://github.com/pkp/omp/pull/1741
- OMP 3.4: https://github.com/pkp/omp/pull/1742

I'll port some of these changes to `main` when I work on #10561 next.

**Comment by bozana** [comment]
Hi @kaitlinnewson, I have not tested it, but I trust you did. I see you have also fix some things from this issue: https://github.com/pkp/pkp-lib/issues/9602. Nice!
I have merged, so closing...
Thanks a lot!
