### ISSUE TITLE
Unable to upload images to custom nav item at site level

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#10578]
**Describe the bug**
I want to upload an image to a custom page navigation menu item. This is possible when using a custom page at the journal level, but not at the site level.

**To Reproduce**
1. Make sure you have more than one journal.
2. Go to Administration > Site Settings > Site Setup > Navigation.
3. Click **Add Item**.
4. Select **Custom Page** for Navigation Menu Type.
5. In the **Content** field, click the button to add an image.
6. See that no Upload option is available.

Follow the same steps at the journal level to see that the image upload option is available.

**What application are you using?** 
OJS `stable-3_3_0` branch.

**Additional information**
This happens because the TinyMCE plugin doesn't add the `uploadUrl` to the plugin settings when no context is available. However, files are stored by user, not context, so the upload will work if enabled. PR incoming.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/tinymce/pull/91 (`stable-3_3_0`)

Tests only:
https://github.com/pkp/ojs/pull/4500 (`stable-3_3_0`)

I can't remember whether the tests capture updates to plugin submodules or not. Will the tests above work ok or do I need to do something special?

**Comment by NateWr** [comment]
There were a few test failures but they look inconsistent to me.

**Comment by asmecher** [comment]
I would support those changes but you might need to do a small bit of digging when it comes to the `main` branch -- the `CONTEXT_SITE` constant changed with https://github.com/pkp/pkp-lib/issues/8333. The `stable-3_3_0` PRs look good and are ready for forward-porting.

**Comment by NateWr** [comment]
@asmecher I've added PRs for each of the branches. I've manually tested `stable-3_3_0` and `stable-3_4_0`. However, I wasn't sure what the correct `contextPath` for the site-level API was, so I used `Application::SITE_CONTEXT_PATH`. I was unable to test this because editing a navigation menu item at the site is broken for me. This may be due to an out-of-sync database, but I suspect it's a side-effect of #8333.

**Steps to reproduce:**
1. Make sure you have more than one journal in a site.
2. Go to Administration > Site Settings > Site Setup > Navigation.
3. Click **Add Item**
4. See error.

Here is the error in my logs:

```
[14-Nov-2024 15:38:40 UTC] PHP Fatal error:  Uncaught TypeError: PKP\controllers\grid\navigationMenus\form\PKPNavigationMenuItemsForm::__construct(): Argument #1 ($contextId) must be of type int, null given, called in /lib/pkp/controllers/grid/navigationMenus/NavigationMenuItemsGridHandler.php on line 240 and defined in /lib/pkp/controllers/grid/navigationMenus/form/PKPNavigationMenuItemsForm.php:40
Stack trace:
#0 /lib/pkp/controllers/grid/navigationMenus/NavigationMenuItemsGridHandler.php(240): PKP\controllers\grid\navigationMenus\form\PKPNavigationMenuItemsForm->__construct(NULL, 0)
#1 [internal function]: PKP\controllers\grid\navigationMenus\NavigationMenuItemsGridHandler->addNavigationMenuItem(Array, Object(APP\core\Request))
#2 /lib/pkp/classes/core/PKPRouter.php(329): call_user_func(Array, Array, Object(APP\core\Request))
#3 /lib/pkp/classes/core/PKPComponentRouter.php(265): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#4 /lib/pkp/classes/core/Dispatcher.php(158): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#5 /lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 /index.php(30): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /lib/pkp/controllers/grid/navigationMenus/form/PKPNavigationMenuItemsForm.php on line 40
```

I _think_ `PKPNavigationMenuItemsForm` needs to accept a `null` context id.

**Comment by asmecher** [comment]
@jonasraoni, could you have a look at the above comment?

**Comment by jonasraoni** [comment]
I can confirm it's a side-effect, probably from a merge conflict, I'll push a fix on the other issue.

**Comment by asmecher** [comment]
@NateWr, I think the error you encountered should now be fixed by https://github.com/pkp/pkp-lib/pull/10619; could you try re-running?

**Comment by asmecher** [comment]
Thanks, @NateWr; @jonasraoni, I'll let you take first crack at this!

**Comment by jonasraoni** [comment]
Okay, regarding the #<wbr>1, I think it makes sense to drop the `has.context`, if this route is supposed to work on a site level, then the constraint doesn't fit.

**Comment by NateWr** [comment]
@asmecher @jonasraoni just checking in on this. Is this good to merge as-is or did you want me to make additional changes?

**Comment by jonasraoni** [comment]
Okay, I've created side-issues to handle the regressions.

**Comment by NateWr** [comment]
Thanks @jonasraoni!
