### ISSUE TITLE
Add journal's copyright/licencing terms to each deposit

### ISSUE THREAD

**Issue by mjordan** [pkp/pkp-lib#1057]
We intended to do this in the original version of the plugin but it appears that it was never implemented. The data we need to include is setup section 4.1 Access and Security Settings.  Not a large development task.

Tagging @ubermichael.

**Comment by ubermichael** [comment]
Right now, the BagIt metadata file for each zipped bag looks like this:

> External-Identifier: F64EF1F7-E237-472E-9140-4C5039E72CF5
> PKP-PLN-Deposit-UUID: 4D438664-5165-4469-9AC6-D0CC2F22C9C5
> PKP-PLN-File-UUID: F64EF1F7-E237-472E-9140-4C5039E72CF5
> PKP-PLN-Deposit-Received: 2016-01-07T16:37:58-08:00
> PKP-PLN-Deposit-Volume: 44
> PKP-PLN-Deposit-Issue: 3
> PKP-PLN-Deposit-PubDate: 2015-07-14T00:00:00-07:00
> PKP-PLN-Journal-UUID: 7D3C4239-2A73-29F4-B34D-ABFD53EA147D
> PKP-PLN-Journal-Title: Intl J Test
> PKP-PLN-Journal-ISSN: 9876-5432
> PKP-PLN-Journal-URL: http://ojs.dv/index.php/ijt
> PKP-PLN-Publisher-Name: Publisher institution
> PKP-PLN-Publisher-URL: http://publsiher.example.com

The OJS export XML includes an `<open_access/>` tag in the `<issue>` tag, as well as something like this in each section.

>      <permissions>
>        <license_url>http://creativecommons.org/licenses/by-nc-sa/4.0</license_url>
>        <copyright_holder locale="en_US">Edward Cheeseman Caruthers</copyright_holder>
>        <copyright_year>1969</copyright_year>
>      </permissions>

Each article in the export contains a similar stanza.

Do you want to include the information from setup section 4.1 in addition to the licensing in the export XML? It seems easy enough to include it with the BagIt metadata above, although there may be a use for having it in a separate file.

**Comment by mjordan** [comment]
The journal-specific information we need to get is in secion 4.1 of the jurnal setup:

![ojs_setup_4_1](https://cloud.githubusercontent.com/assets/403918/12360598/c54b6358-bb6d-11e5-90d6-27d969233793.png)

I'll deffer to @jmacgreg to confirm that this is the only location where journal-level licensing/copyright information is managed. I think it would be sufficient  to bundle with each deposit 1) whether or not the journal is OA, and if so, the contents of the "Open Access Policy" field, or 2) whether the journal required a subscription. If that latter, some standardized text would suffice.

I like the idea of putting this information in a field in bag-info.txt, despite that according to the BagIt spec,

>It is RECOMMENDED that lines not exceed 79 characters in length. Long values may be continued onto the next line by inserting a newline (LF), a carriage return (CR), or carriage return plus newline (CRLF) and indenting the next line with linear white space (spaces or tabs).

If we were to encode this data in a bag-info.txt element, we could do something like this:

>PKP-PLN-Journal-Is-OA: [Yes or No, depending on which radio button is selected in the configuration.]
>PKP-PLN-OA-Policy: [the value of the "Open Access Policy" settings field, n/a if not OA]

I think that's all we'd need. Since the 79-caracter limit on fields is not mandatary, maybe just removing all line returns would be sufficient, leaving HTML markup intact.

Thoughts?

**Comment by jmacgreg** [comment]
Confirmed!

**Comment by ubermichael** [comment]
Great, thanks to both of you.

@jmacgreg can you also confirm that these are the only journal settings involved? `openAccessPolicy`, `licenseURL`, and `publishingMode`?

**Comment by mjordan** [comment]
@jmacgreg and @ubermichael you will have seen the email I just sent regarding how to handle "OJS will not be used to publish the journal's contents online." @asmecher you want to see a copy?

**Comment by asmecher** [comment]
@mjordan I won't know whether I wanted it until I've read it :)

**Comment by mjordan** [comment]
Ha. Expect to see it shortly.

**Comment by mjordan** [comment]
Where is `licenseURL` set (I don't see a config option for it)? If we can grab that, we may want to add that URL to the Bag's `fetch.txt`.

**Comment by jmacgreg** [comment]
@ubermichael, that is correct I think, so long as you don't need any of the copyright stuff. If you need copyright stuff, you'll also want: 

`copyrightNotice` (that's the text blurb, and that's all that OJS instances previous to OJS 2.4.x had, so it may be populated while other fields may not); 

`copyrightYearBasis` (whether to use the article or issue publication date to set copyright year)

`copyrightHolderType` (who holds the copyright: author, journal, or other)

**Comment by ubermichael** [comment]
Thanks James. I think we'll definitely need those bits as well.

**Comment by mjordan** [comment]
:+1:  So maybe it's better to bundle it up in an XML file be add to the Bag? That's a lot of extra bag-info.txt fields.

**Comment by ubermichael** [comment]
There's no limit to the number of bag-info.txt fields, and the bagit library should handle the 79 character limit, so I think we're OK there.

Seems like the easiest thing to do is add the copyright and licensing info to the Atom XML that OJS sends for the deposit, store it in the staging server's database, and then add it to the bag as it's being reserialized in the staging server.

**Comment by mjordan** [comment]
Sounds good. I just want to make sure that the packages that are stored in LOCKSS contain everything. If it's easier to put everything in those Bags' bag-info.txt, let's do that.

**Comment by ubermichael** [comment]
Ok. I'm ready to add this info to the deposit XML. Is there anything else to add?

```xml
  <pkp:license>
    <pkp:openAccessPolicy>This journal provides immediate open access
    to its content on the principle that making research freely
    available to the public supports a greater global exchange of
    knowledge.</pkp:openAccessPolicy>
    <pkp:licenseURL>http://creativecommons.org/licenses/by-nc-sa/4.0</pkp:licenseURL>
    <pkp:publishingMode mode="0">Open</pkp:publishingMode>
    <pkp:copyrightNotice>This is a copyright notice.</pkp:copyrightNotice>
    <pkp:copyrightBasis>article</pkp:copyrightBasis>
    <pkp:copyrightHolder>author</pkp:copyrightHolder>
  </pkp:license>
```

**Comment by mjordan** [comment]
Looks good. What's `mode="0"`? Also, if the journal is not OA, we should probably not include the `<pkp:openAccessPolicy>` element.

**Comment by ubermichael** [comment]
The mode attribute is the number stored in the database. It should be 0, 1, or 2. The content of the element is the human readable equivalent.

**Comment by mjordan** [comment]
Ah, thanks. @asmecher what do those numbers mean?

**Comment by ubermichael** [comment]
Those numbers are defined here: https://github.com/pkp/ojs/blob/master/classes/journal/Journal.inc.php#L24

```php
define('PUBLISHING_MODE_OPEN', 0);
define('PUBLISHING_MODE_SUBSCRIPTION', 1);
define('PUBLISHING_MODE_NONE', 2);
```

**Comment by mjordan** [comment]
Thanks @ubermichael.

**Comment by ubermichael** [comment]
Just ran some tests, and this is the resulting bag-info.txt file from a deposit from OJS and full processing from the staging server.

```
External-Identifier: 2BB1413F-437A-48A7-A79D-D953C2511E01
PKP-PLN-Deposit-UUID: 4318B431-901E-4069-8A5B-09FBA0A4FAC4
PKP-PLN-File-UUID: 2BB1413F-437A-48A7-A79D-D953C2511E01
PKP-PLN-Deposit-Received: 2016-01-15T16:30:35-08:00
PKP-PLN-Deposit-Volume: 44
PKP-PLN-Deposit-Issue: 3
PKP-PLN-Deposit-PubDate: 2015-07-14T00:00:00-07:00
PKP-PLN-Journal-UUID: 7D3C4239-2A73-29F4-B34D-ABFD53EA147D
PKP-PLN-Journal-Title: Intl J Test
PKP-PLN-Journal-ISSN: 9876-5432
PKP-PLN-Journal-URL: http://ojs.dv/index.php/ijt
PKP-PLN-Publisher-Name: Publisher institution
PKP-PLN-Publisher-URL: http://publsiher.example.com
PKP-PLN-openAccessPolicy: This journal provides immediate open access to its content on the principle that making research freely available to the public supports a greater global exchange of knowledge.
PKP-PLN-licenseURL: http://creativecommons.org/licenses/by-nc-sa/4.0
PKP-PLN-publishingMode: Open
PKP-PLN-copyrightNotice: This is a copyright notice.
PKP-PLN-copyrightBasis: article
PKP-PLN-copyrightHolder: author
```

**Comment by mjordan** [comment]
Looks good. So to summarize, the data we want is added to the bag-info.txt file generated by OJS, then on the staging server is converted into the XML illustrated above, which is added to the deposit's Bag that ends up preserved by LOCKSS. Is that correct?

**Comment by ubermichael** [comment]
Almost. When the plugin creates the atom XML deposit, it adds the licensing to the XML. My changes don't affect the bag's bag-info.txt file at all. The staging server receives the deposit XML with the licensing information in it, and adds it to the row in the database on the staging server. The final processing step is to reserialize the bag file after everything has been validated. The licensing info is added to the bag-info.txt file during the reserialize step.

I did it this way so that the licensing information is available even before the deposit bag is downloaded, and so that the information is available in the staging server's UI.

**Comment by mjordan** [comment]
OK, thanks!

**Comment by asmecher** [comment]
@ubermichael and @mjordan, does that last PR resolve this issue completely?

**Comment by ubermichael** [comment]
Yes, this issue can be closed. We have one more issue to file for 2.4.8, discovered this morning.

**Comment by asmecher** [comment]
Thanks! Awaiting the new one before doing anything rash.
