### ISSUE TITLE
Issue archives show non-existent paginated results

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#10596]
**Describe the bug**
The issue archive handler will show the issue archive for pages of results that don't exist. For example, if a journal only has 5 pages of results, `/issue/archive/23` will show a message that says "This journal has not published any issues."

**To Reproduce**
1. See example in public demo at https://ojs33.demo.publicknowledgeproject.org/index.php/demojournal/issue/archive/10

**What application are you using?**
 OJS `stable-3_3_0`

**Additional information**
I believe it should show a 404 error on such pages. PR incoming.

**Comment by NateWr** [comment]
The following PRs return a `404` response when a page is accessed that doesn't exist.

PRs:
https://github.com/pkp/ojs/pull/4514 (`stable-3_3_0`)
https://github.com/pkp/ojs/pull/4515 (`stable-3_4_0`)
https://github.com/pkp/ojs/pull/4516 (`main`)

**Comment by asmecher** [comment]
All merged, thanks!
