### ISSUE TITLE
OJS - 3.5 - Settings Access: When user modifies their own role and remove settings access there are contradicting messages

### ISSUE THREAD

**Issue by Tribunal33** [pkp/pkp-lib#10612]
**Describe the bug**
If a user has access to settings and they remove the role granting them access and click **OK** when editing the user roles they will see both a Access denied message and a success message.  The user does not automatically get removed from the settings area until there is a page refresh.

**To Reproduce**
1. Load up the VM of your choice 
2. Login with a user that has access to settings
3. Navigate to Settings -> Users & Roles via side nav menu
4. From the **Users** tab
5. Find current user
   1. Select the triangle to open more options for this user
   2. Select **Edit User**
6. Find the role that grants access to settings
7. Uncheck that role
8. Select **OK** to Save
9. Observe messages from browser pop up and UI success message (seen in images below)

**What application are you using?**
 OJS, OMP or OPS version 3.5

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
![Image](https://github.com/user-attachments/assets/39cadfcd-327c-4171-86b5-d9a2f4a88867)

**Comment by asmecher** [comment]
Hi @mreiko! I need to verify part of this to see if I can reproduce, then I'll likely close the rest. OK to take it from here.

**Comment by asmecher** [comment]
Checked in on details and I'm satisfied that there isn't a security issue here, just an imperfect UI. Closing as a WONTFIX for now -- until and unless we get the sense it's impacting users.
