### ISSUE TITLE
Redesigned Workflow - Notifications

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10618]
Goal is to display existing notifications same as for 3.4 on the workflow stages. And also document the scenarios for the documentations for Devika to review.

**What application are you using?**
 OJS, OMP or OPS version 3.5

**Comment by jardakotesovec** [comment]
### NOTIFICATION_TYPE_ASSIGN_PRODUCTIONUSER 
- when no galleys, nor production discussion
 ![Image](https://github.com/user-attachments/assets/deed138a-87c2-446e-92e5-f11d014d5208)
 

### NOTIFICATION_TYPE_AWAITING_REPRESENTATIONS
- when no galleys, but some production discussion
![Image](https://github.com/user-attachments/assets/b6fdd7c5-8c9b-4502-a27a-75826897753b)

**Comment by Tribunal33** [comment]
So far this looks good @jardakotesovec please take a look at the bugs that were found.  After they are fixed we can close this down.

**Comment by Tribunal33** [comment]
Bugs have been fixed and this is working as intended.  Closing this issue.  Moved #10701 off of this parent as it can be an enhancement to the existing notifications system.
