### ISSUE TITLE
localized article cover images

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1062]
If there is an article cover image in the primary language and no article cover image in other languages, the cover image in the primary language should be displayed. This is not the case now and I think that this is a bug:
If the cover image should be displayed will be determined in this way: https://github.com/pkp/ojs/blob/ojs-stable-2_4_7/templates/issue/issue.tpl#L18-L19 i.e. it will checked if there is a localized file name ($article->getLocalizedFileName()). But, for the display later only the file for the current locale is considered: https://github.com/pkp/ojs/blob/ojs-stable-2_4_7/templates/issue/issue.tpl#L42 i.e. $article->getLocalizedFileName().
The pull request is coming...

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by martinpub** [comment]
Hi @asmecher and @bozana, could a similar fix be made regarding <em>issue</em> covers? We would greatly appreciate it, as our journals using covers and different locales never have localised covers. Or is it solved by the patch presented in https://github.com/pkp/pkp-lib/issues/1419?

**Comment by bozana** [comment]
@martinpub, that PR solves it only for journal primary language i.e. if the cover images are in that language. S. https://github.com/pkp/pkp-lib/issues/2432 for a complete localized issue cover images display. I am not sure if this is wished in general i.e. if the PR will be merged -- @asmecher will review it -- thus please keep the track of that issue.

**Comment by martinpub** [comment]
Thanks @bozana, I will follow https://github.com/pkp/pkp-lib/issues/2432.
