### ISSUE TITLE
Native import plugin isn't working

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#1063]
Both in omp stable and omp master, can't import a monograph. See: http://forum.pkp.sfu.ca/t/remove-press-manager-from-omp-publication/7042/7

**Comment by asmecher** [comment]
@beghelli, the quoted sample XML at the forum link doesn't validate. Have you checked whether that's the problem?

**Comment by asmecher** [comment]
(FWIW I fixed a couple of small glitches in the master branch, and OMP master now imports its own XML sample.)

**Comment by asmecher** [comment]
I'm pretty sure the issue was XML validation. I've fixed a validation problem with the sample XML in OMP master, omp-stable-1_1_1, omp-dev-1_1, and OJS master.
