### ISSUE TITLE
Notification NOTIFICATION_TYPE_FORMAT_NEEDS_APPROVED_SUBMISSION is not updated&displayed

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10636]
**Describe the bug**
While working on reviewing what notifications we display in current workflow, I run into one OMP notification, which works in 3.3, but not in 3.4/3.5.

![Image](https://github.com/user-attachments/assets/de84954b-15e0-45ce-9085-91e4cbfae838)

**To Reproduce**
1. Go to Submission which is in Production stage but not yet published
2. See notification in 3.3 but not in 3.4/3.5

**Investigation**
I think that this notification is created in PKPApproveSubmissionNotificationManager.inc.php, when this notification update is triggered - https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/submission/form/PKPSubmissionSubmitStep4Form.inc.php#L161

I suspect this was not carried over to 3.4.0.

**What application are you using?**
OMP 3.4/3.5

**Comment by taslangraham** [comment]
Ready for review @ewhanson 

**PRs**
pkp-lib 3.4 - https://github.com/pkp/pkp-lib/pull/10647/files
pkp-lib 3.5(main) - https://github.com/pkp/pkp-lib/pull/10648/files

**submodule updates**
omp 3.4 - https://github.com/pkp/omp/pull/1780
ojs 3.4 - https://github.com/pkp/ojs/pull/4536
ops 3.4 - https://github.com/pkp/ops/pull/822

omp 3.5 - https://github.com/pkp/omp/pull/1782
ojs 3.4 - https://github.com/pkp/ojs/pull/4537
ops 3.4 - https://github.com/pkp/ops/pull/824

**Comment by ewhanson** [comment]
Looks good to me. Thanks, @taslangraham. The submodules will need to be updated, but feel free to merge `main` once that's done. I can merge `stable-3_4_0` for you once that's done.

**Comment by taslangraham** [comment]
@ewhanson Thanks for the review. I've updated the submodules, so feel free to go ahead and merge the `stable-3_4_0` PRs.

There are tests, which seems unrelated to the changes I've made, that are failing on OPS main. Once I've resolved those I'll merge the PRs for main.

**Comment by taslangraham** [comment]
I've merged the PRs for the main branches

**Comment by ewhanson** [comment]
Thanks @taslangraham, I've merged the ones for 3.4. If that's it, feel free to close the issue.
