### ISSUE TITLE
VirtualArrayIterator __construct references `$this->theArray` before it's initialised

### ISSUE THREAD

**Issue by SydneyUni-Jim** [pkp/pkp-lib#10632]
https://github.com/pkp/pkp-lib/blob/6013d783f564c6f3d7bb1b5455b4913ce2d70eaf/classes/core/VirtualArrayIterator.php#L47-L61

Line 54 references `$this->theArray`, but that is only initialised later on line 56.

Line 58 reassigns `$this->itemsPerPage` to the parameter `$itemsPerPage` anyway. And if `$itemsPerPage` is zero, this subsequently causes a DivisionByZeroError in `getPageCount()`.

**Comment by asmecher** [comment]
@SydneyUni-Jim, I've fixed this, thanks -- but I think the underlying problem is that your journal setup is incomplete. Make sure that `config.inc.php` has settings for `items_per_page` and `page_links` in the `[interface]` section, and that Settings > Website > Setup > Lists has valid numbers.

**Comment by SydneyUni-Jim** [comment]
Hi @asmecher. After more debugging I learnt that it was indeed the later. Somehow two of my journals had zero for both items per page and page links.
