### ISSUE TITLE
Redesigned Workflow - submission statuses

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10643]
## Indication on stage which has not started yet
The {stage} stage has not yet been initiated.
Note that in comparison to 3.4 we don't show the files/discussions until the stage is initiated.

![Image](https://github.com/user-attachments/assets/cd358169-0ef3-48cf-9888-806fd0c6da9b)

## Indication on selected stage when moved to the next stage(s)
To show in submission stage when submission is in review stage
"The submission is currently in the review stage."
![Image](https://github.com/user-attachments/assets/012a5b92-c5a9-474a-aa67-40ecbc9e01f9)

To show in the review stage round 1 when submission is moved to review stage round 2
"The submission has been advanced to the next round of review"
![Image](https://github.com/user-attachments/assets/b21276c1-5151-4287-ac1d-39cad960420a)

To show in the review stage round 1 when submission is moved to Copyediting after review round 2
"The submission advanced to the next review round, was accepted, and is currently in the copyediting stage."

![Image](https://github.com/user-attachments/assets/95c6b2b3-a377-4085-b936-82c10a7c172b)

To show in review round 2 when submission is in the copyediting stage
"The submission is currently in the copyediting stage."

![Image](https://github.com/user-attachments/assets/a5824272-e9e6-4c93-ab3d-e285b199dfa6)

word "copyediting" will change to "production" in review and submission rounds if the submission is in the production 

## Indication of review round statuses
TODO: cover individual review round statuses in separate ticket with cross comparison of indications we have in editorial activity
![Image](https://github.com/user-attachments/assets/1730ae0c-7c8a-4087-a4c8-461bcf173aff)

## Indication in production stage that submission is published
![Image](https://github.com/user-attachments/assets/c28cdeab-d474-42dc-b778-e33e85f50090)

**Comment by Devika008** [comment]
These are perfect :)

**Comment by Tribunal33** [comment]
@jardakotesovec don't know the reasoning behind this difference of Review stage not showing anything besides the status message without a participants table but copyediting and production do show a participants table.  I think it would be more consistent to remove the participants table when the stage has not yet been initiated.    

![Image](https://github.com/user-attachments/assets/48623772-f650-463e-a08e-92c67fe25259)

**Comment by Tribunal33** [comment]
I think all status have been checked and covered with some test cases.  I believe this ticket can be closed.  The participants table is part of 3.4 so this is existing functionality.  I would like to have this removed but shouldn't stop this ticket from closing.  

I have gone through the review rounds and found these status which will be covered in a new ticket?

The Status messages that can be seen are:
1. “Awaiting responses from reviewers.” <-- if no responses from reviewers exist
2. "New reviews have been submitted” <--  if some or all reviewers have submitted
3. “Revisions have been requested.” <-- if reviewers request revisions
4. “All recommendations are in and a decision is needed.” <-- All clear
