### ISSUE TITLE
Update 3.2.1.3 to 3.4.0.5 update issues

### ISSUE THREAD

**Issue by mitarulv** [pkp/pkp-lib#10645]
I converted the old tables from MyISAM to InnoDB and ran the upgrade process. After a while, the script freezes. Upon inspecting the database tasks:

bash: mysql
mysql: SHOW FULL PROCESSLIST;
update notification_settings set setting_value = '{"captcha":"The characters you entered did not match the characters in the image. Please check the characters and try again."}' WHERE setting_name = 'contents' AND setting_name = 'contents';

I recreated the database and imported the dump. I also truncated the notification_settings table and tried again, but the same issue occurred.
Same process running for more than 30 min without changes with empty table and "interesting" AND query.

Then I just killed process by PID. Oh and php-fpm + update.php log had absolutely 0 errors.

OJS version: 3.2.1.3 to 3.4.0.5
MariaDB: 8+ (don't remember exactly, but it doesn't even matter rn.)
Composer packages were updated
PHP version: 8.2

P.S. The update script is problematic—it fails every time, making partial adjustments and creating new tables, which causes errors with already existing tables. It generally fails because it doesn't make sense. Can you make it either continue from the point where it was interrupted or redo the steps already done? Oh wait, you can't because columns are altered! Maybe just skip them if they are already in the expected state?

To upgrade another system from 3.3 to 3.4 I had to manually compare and adjust dumps and that was the only time when there were no issues during  upgrade - because after few fails just stopped using it!

Unfortunately I have to Sys. Admin this .... Sorry, I'm frustrated after restoring the dump over 20 times today and troubleshooting most update/upgrade unfriendly system there is. And why there isn't user friendly import/export tool? .......

**Comment by kaitlinnewson** [comment]
Hi @mitarulv, thanks for the report - it sounds like you're having upgrade issues, so this would be best to post in [our Support Forum](https://forum.pkp.sfu.ca/) - this is where PKP team members and other community members can help with support and troubleshooting. If something turns out to be a bug in the software, then we'll create an issue for it here.
