### ISSUE TITLE
Update UI to use user's custom initials when available

### ISSUE THREAD

**Issue by taslangraham** [pkp/pkp-lib#10651]
Description

https://github.com/pkp/pkp-lib/issues/10489 introduced support for users to set a 2-character custom initial to represent themselves in the application. We need to update the UI components that display initials to use these custom initials when available. If no custom initial is set, the current behavior of deriving initials from the user’s name should be used as a fallback.

UI Library components that need to be updated:
- [UserAvatar ](https://github.com/pkp/ui-library/tree/main/src/components/UserAvatar)
- [InitialsAvatar ](https://github.com/pkp/ui-library/tree/main/src/components/InitialsAvatar)

**What application are you using?**
 OJS, OMP and OPS version 3.5(main)

**PR**
ui-library - https://github.com/pkp/ui-library/pull/455/files
pkp -lib - https://github.com/pkp/pkp-lib/pull/10661/files
**Submodule updates**
ojs - https://github.com/pkp/ojs/pull/4540/files
omp - https://github.com/pkp/omp/pull/1781/files
ops - https://github.com/pkp/ops/pull/823/files

**Comment by taslangraham** [comment]
@blesildaramirez Do you mind reviewing the PR in the issue description, for me, please?

**Comment by jardakotesovec** [comment]
@taslangraham Looking good - just suggestion whether we could do the initial calculation on server side?  So the logic whether we use the 'prefered' or calculated would happen on php. And user/participant objects would have just the 'initial' field which would be calculated. What you think?

**Comment by taslangraham** [comment]
@jardakotesovec I don't have any objections to doing it that way. I'll go ahead and move the logic over to server-side

**Comment by taslangraham** [comment]
@jardakotesovec I've moved the logic to calculate initials to server-side, and updated the components only to accept and render the initials. Please take a look.

This required changes to pkp-lib as well. @ewhanson Could you take a look at that PR, please? I've included it in the issue description.

**Comment by ewhanson** [comment]
Thanks, @taslangraham. Just a few questions there, but the code looks good. 👍

**Comment by taslangraham** [comment]
@ewhanson I've responded to your questions and made adjustments based on your review. Please take a look.

**Comment by ewhanson** [comment]
Thanks, @taslangraham! They look good to me. Assuming you're not waiting on anything for the ui-library, feel free to rebase and merge.

**Comment by taslangraham** [comment]
All merged! Thanks for the review @ewhanson.
