### ISSUE TITLE
.xhtml file missing `text/html` mimetype, not loaded by HtmlArticleGalley plugin

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#10664]
**Describe the bug**
When a file with a `.xhtml` is uploaded, it is assigned the mimetype `text/xml`. As a result, it is not loaded by the `HtmlArticleGalleyPlugin` viewer.

**To Reproduce**
1. Upload a `.xhtml` galley to a submission (example below)
2. Publish the submission
3. Click on the alley on the article landing page
4. See that it downloads the file instead of showing it

**What application are you using?**
 `stable-3_3_0`

**Additional information**
This is addressed in #5063, but it only applies to files named with a `.html` extension. When I added an exception to `PKPString::getAmbiguousExtensionsMap()` for `xhtml`, the mimetype `text/html` was assigned and the galley was displayed correctly.

**Example XHTML File**
GitHub won't let me upload it, so copy and save this as `.xhtml`.

```html
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Lorem ipsum dolor sit amet</title>
  </head>
  <body>
    <main>
      ...
    </main>
  </body>
</html>
```

**Comment by NateWr** [comment]
The following PR adds an exception for XHTML files to apply the `text/html` mimetype.

PR:
https://github.com/pkp/pkp-lib/pull/10665 (`stable-3_3_0`)

Tests:
https://github.com/pkp/ojs/pull/4545 (`stable-3_3_0`)

**Comment by asmecher** [comment]
Looks good, thanks, @NateWr -- can you forward-port to `stable-3_4_0` and `main`?

**Comment by NateWr** [comment]
Thanks @asmecher, I've added PRs for all branches now.
