### ISSUE TITLE
Revisit OAI PMH in PKP suite to explore exposing additional metadata and full text 

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#1066]
I think the OAI-PMH actually allows for more metadata to be exposed than we currently provide, including the full text. I wonder if we could investigate the possibilities. I don't think we've looked at the OAI implementation in a long time. 

This could have implications for the PKP Index.

**Comment by jalperin** [comment]
tagging @jmacgreg. and is Kevin not on github?

**Comment by asmecher** [comment]
@jalperin, OAI-PMH is a container format. It mandates that OAI-DC must be among the supported formats but otherwise you can do whatever you want. What do you have in mind?

**Comment by jalperin** [comment]
It is a general request, but thinking of a few things (and maybe others can think of more)
a) year of publication, volume, and issue numbers (currently only exposed as a string that needs parsing in "dc:source") in their own fields (this would make the stats gathering more accurate)
b) full text, if it can be extracted (i.e., from whatever does the search). Even if only the text, and no formatting. This would help Harvesters provide better search results (i.e., the PKP Index)
c) licensing information (now that we have it)
d) DOIs, ORCIDs, and other identifiers (for the sake of completeness)

**Comment by asmecher** [comment]
Some of that is already in the NLM OAI format, written for OJS to support Synergies, and doubtlessly NLM will have elements for the data we haven't included yet. But without a specific use case it's hard to prioritize this.

**Comment by jalperin** [comment]
does the NLM format include full text? and, if so, are we using it for the PKP index?

**Comment by asmecher** [comment]
It includes such full text as can be extracted from PDFs and HTML using the text indexing tools. As far as I know we aren't using it for the index.

**Comment by jalperin** [comment]
OK. good to know. Will close.
