### ISSUE TITLE
[UI] Style accordians in information center

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1067]
![selection_051](https://cloud.githubusercontent.com/assets/2306629/12418195/aa59916a-bea5-11e5-916b-4573d3ad6da7.png)

Also, what's the difference between Current and Earlier notes? Are notes stage-specific?

**Comment by beghelli** [comment]
I think this is coming from the file notes, where earlier notes were related to older file revisions, and current to the current revision. But it doesn't make sense to reproduce that in the submission level.

**Comment by asmecher** [comment]
^ That is the case: this shows only for file notes, not submission notes.

**Comment by NateWr** [comment]
Thanks guys. Any objection to calling them "Current Revision Notes" and "Earlier Revision Notes"?

**Comment by asmecher** [comment]
Sure, that seems clearer.

**Comment by NateWr** [comment]
Ok, I just did a quick pass on the styling and updated the language but it should be good enough for now.

PR: https://github.com/pkp/pkp-lib/pull/1111
