### ISSUE TITLE
Add listbuilder items can show empty rows

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1068]
Here's a gif showing the problem:

![add-recipients](https://cloud.githubusercontent.com/assets/2306629/12418821/a25411b2-bea9-11e5-8494-1d697c6d299d.gif)

Is the potential recipient list ever going to get very long? Is there any reason we shouldn't just use a list of possible recipients with checkboxes for selecting them?

If that's not an option, I'll look into figuring out the styling issues that are causing this problem. But ideally the user wouldn't be able to add a grid row with a recipient if no other potential recipients exist.

**Comment by beghelli** [comment]
I think we use the listbuilder to keep consistent. We tried to use it anywhere we need to build a list, and I can imagine that this list could get bigger, with copyeditor, multiple authors, editor.

Even if we don't use this listbuilder here anymore, we have to fix this behavior, which I think it's more a JS thing than just styling. I can take a look. I will rename this to a more generic title.
