### ISSUE TITLE
Redesigned Workflow - FileManager

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10688]
FileManager is replacing the legacy file grid used in 3.4. But new UI is only for listing the files. All modals are exactly same as before.

### Differences to 3.4
- Search functionality is omitted in new file manager - we (me&Devika) think it might not be necessary, and can be added later if there is demand
- Reviewer's Attachments file grid, which was displayed for author in Review stage is ommited in 3.5. More details in separate section about that.

### QA Notes:
- Given that this is 95% regression testing compared to 3.4. Easiest is to have 2 latest (main) versions of ojs/omp/ops and one with having new submission listing On and other Off. And use the same database - that makes it very easy to compare whether correct files show up in correct places. Alternatively can be compared against 3.4 - but these needs to have separate databases.
```
[features]
enable_new_submission_listing = Off
```

### What to look for in terms of regressions:
- there are differences in what File managers are used for author/editor
- there are differences in what actions can be taken by author/editor. Might wort to also check some assistant just to be sure.
- check whether all modals that are opened are same (3.5 legacy workflow vs 3.5 new workflow), including title
- check that all actions work
- check that correct files appears 
- there is date in the listing - that is still to be refined across multiple new places - https://github.com/pkp/pkp-lib/issues/9733
- for title&descriptions and designs - source of the truth is in figma - https://www.figma.com/design/Wf7sDlUg2372jaKKTJ0Mgz/OJS-3.4-3.5?node-id=7755-15968&t=J0uJILaGVUZHunl9-4 , for everything else source of the truth is 3.4.

###  Reviewer's Attachments
Reviewer's attachments is file grid displayed to author in review stage
<img width="1316" alt="Image" src="https://github.com/user-attachments/assets/504e00e0-5573-4d23-bc52-5ccc647d2108" />

It has been bit mystery to me how that works, so will try to cover it here.

In 3.3 when Editor would request revisions from Author - its possible to select files that has been submitted/revised but also upload new files. My understanding is that the problem was only the existing ones would be shared via Reviewer's attachment grid and other would be included only as email attachment, which was confusing - its covered more in detail here https://github.com/pkp/pkp-lib/issues/6805 . From technical point of view 3.3 was setting such files as 'viewable', which was used to determine which files to show in Reviewer's Attachment grid. Viewable also got deprecated in 3.3.

And with 3.4 and later this approach seems to be abandoned as its using new editorial decision to request revisions with new UI. All files gets attached to the email, but did not manage to display anything in `Reviewer's Attachment grid.`. Which might be better to show nothing than just some of them as described above.

From the issue [(https://github.com/pkp/pkp-lib/issues/7144)](https://github.com/pkp/pkp-lib/issues/7144) we can conclude its desirable to be able to see these files on author dashboard, but it would require notable effort to get that working, therefore keeping it as future improvement request.

In context of my current effort it seems that there is no way to display files in Reviewer's Attachment grid in 3.4/3.5.. so I will not include it in new workflow page. 

Tagging @asmecher @Devika008 @Vitaliy-1 For awareness on this. If you think I made some incorrect conclusion let me now.

**Comment by Tribunal33** [comment]
@jardakotesovec this **passes QA** and can be closed.  I tried to limit the scope.  You have addressed all the major issues for UI (See screenshot 1) and the functionality works as expected.  Hard to say for certain as there are several scenarios that I have no clue what the existing behavior was.  

Search functionality was skipped
Data format was skipped
Discussion section was skipped.

General tests have been created for the following areas.  Let me know if there is something I missed.
1.	General layout of file grid looks good
2.	Upload file for each stage in each file transfer area
a.	Submission -> Submission Files
b.	Review -> Revisions Uploaded, Files for Review
c.	Copyediting -> Draft Files, Copyedited Files
d.	Production -> Production Ready Files
3.	Check out Files are correct for each user role.
a.	Login as each user and observe each section can be seen/or not
b.	When Logged in check user actions are correct


screenshot 1
![Image](https://github.com/user-attachments/assets/52f757d5-99cd-4df7-910a-12d1a59dc771)

One potential issue is upload of files not being seen on revision list for stages that have already been passed.  Solution and enhancement would be to remove the ability to add files after a stage has been completed?  Currently this is similar functionality as expected on older OJS versions.
screenshot 2:
![Image](https://github.com/user-attachments/assets/6c1e49ef-3453-4566-9e39-251198a5e6e3)
