### ISSUE TITLE
Fatal error encounted with Publisher Library file's public download URL

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#10694]
**Describe the bug**
When I try to download a file in the Publisher Library from its publicly accessible URL, I encounter a fatal error.

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PKP\pages\libraryFiles\LibraryFileHandler::__construct(), 0 passed in /lib/pkp/pages/libraryFiles/index.php on line 19 and exactly 1 expected in /lib/pkp/pages/libraryFiles/LibraryFileHandler.php:37
Stack trace:
#0 /lib/pkp/pages/libraryFiles/index.php(19): PKP\pages\libraryFiles\LibraryFileHandler->__construct()
#1 /lib/pkp/classes/core/PKPPageRouter.php(203): require('/home/nate/Proj...')
#2 /lib/pkp/classes/core/Dispatcher.php(158): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#3 /lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 /index.php(30): PKP\core\PKPApplication->execute()
#5 {main}
  thrown in /lib/pkp/pages/libraryFiles/LibraryFileHandler.php on line 37
```

**To Reproduce**
1. Go to Settings > Workflow > Publisher Library.
2. Add a file and check the Public Access checkbox.
3. Go to the publicly accessible URL that it shows (something like `http://localhost:8000/index.php/publicknowledge/en/libraryFiles/downloadPublic/1`)

**What application are you using?**
 `main` branch (3.5 pre-release)

**Additional information**
cc @basti95 This will need to be fixed before `partnerLogos` can be released for 3.5.

**Comment by asmecher** [comment]
Should be fixed by https://github.com/pkp/pkp-lib/commit/a36dde6e7198f567e892098cc58c63bc0ff20110, thanks!
