### ISSUE TITLE
3.5 - OJS Alert (Bell icon) links are not working

### ISSUE THREAD

**Issue by Tribunal33** [pkp/pkp-lib#10702]
**Describe the bug**
Noticed that the links that are part of the alert notification system are not responding when clicked on.

Pre-condidtions : 
Have an account with alerts or using default dataset

**To Reproduce**
1. Go to Journal of choice and login as user jjanssen or dbarnes
2. Select the alert bell at the top of the journal
3. Select one of the alert links

Actual : Link does not redirect and a flashed warning animated icon
Expected : Link should redirect to proper location as it does in 3.4.0 without warning animated icon

**What application are you using?**
 OJS, version 3.5.0

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
![Image](https://github.com/user-attachments/assets/b52d9bb2-5082-4df2-a6fc-8742e24ee174)

**Comment by jardakotesovec** [comment]
@Tribunal33 I think its same as this one right - https://github.com/pkp/pkp-lib/issues/10495

**Comment by Tribunal33** [comment]
Closed as a Duplicate issue.
