### ISSUE TITLE
Improve confirmation notices when skipping the email is an option

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1070]
From user testing conclusions:

> Editing: Provide a confirmation note after adding reviewers and sending email (e.g., Reviewer Successfully Added and Email Sent”). Consider adding this to the History.

A confirmation note already existed, but was covered up by the modal screen. This was fixed in a separate commit.

The review history does seem to log two events when a reviewer is added, including a **Notified** event:

![selection_052](https://cloud.githubusercontent.com/assets/2306629/12422690/15a42826-bec0-11e5-990b-68176757f30a.png)

However, the **Notified** event appears even if you select the option to not send an email when the reviewer is added. Does this event signify something other than the email?

I'd recommend two steps to address the issue raised in user testing:
- [ ] Modify the confirmation notice after adding a reviewer to indicate if an email was sent or not.
- [ ] Figure out the appropriate history logs and make sure the email is logged as necessary.

**Comment by NateWr** [comment]
The commit above adjusts the confirmation notice when adding a reviewer. However, this "skip email" pattern is used for unassigning reviewers as well as several other places in the system.

Notifications should be updated across the board as part of this issue.

**Comment by asmecher** [comment]
Mind including the PR links?

**Comment by NateWr** [comment]
No PR yet. This last comment was mostly a note to myself since I won't work on it again until next week, but also a notice to others to comment if it sounded like a bad idea.

**Comment by asmecher** [comment]
Ah, sure.

**Comment by NateWr** [comment]
I've now adjusted the notification messages when assigning and unassigning a reviewer (still no PR). However, I've run into problems with the other `skipEmail` options.

One is connected to thanking a reviewer. I couldn't actually figure out how to thank a reviewer. How do I do this?

The others are all attached to editorial decisions. I believe there may be a bug with multiple emails being sent out and I wasn't confident I understood the system well enough to make changes. Here is an example of the problem, as I understand it, when selecting Request Revisions from the External Review stage.

- [SendReviewsForm::execute()](https://github.com/pkp/pkp-lib/blob/master/controllers/modals/editorDecision/form/SendReviewsForm.inc.php#L105) calls `EditorDecisionWithEmail::_sendReviewMailToAuthor()`, which [does or does not send an email based on the checkbox](https://github.com/pkp/pkp-lib/blob/master/controllers/modals/editorDecision/form/EditorDecisionWithEmailForm.inc.php#L258-L267).
- In the same request, [SendReviewsForm fires off the PKPEditorDecisionHandler::saveSendReviews action](https://github.com/pkp/pkp-lib/blob/master/controllers/modals/editorDecision/form/SendReviewsForm.inc.php#L35). This [calls PKPEditorDecisionHandler::_saveEditorDecision](https://github.com/pkp/pkp-lib/blob/master/classes/controllers/modals/editorDecision/PKPEditorDecisionHandler.inc.php#L133) which [generates another email](https://github.com/pkp/pkp-lib/blob/master/classes/controllers/modals/editorDecision/PKPEditorDecisionHandler.inc.php#L401-L407).

I haven't traced through the other editorial actions in the review stage with the `skipEmail` option, but I believe they follow a similar trajectory.

This raised a few questions I'm hoping someone can answer:

Why are we sending two emails? Is this an error or appropriate behaviour? If the notification in `_saveEditorDecision` should remain, what's the best way to retrieve the value of the `skipEmail` option within that function?

cc'ing @asmecher and @beghelli since I figure you guys are best placed to answer this question.

**Comment by asmecher** [comment]
That's an error; I think the cleanest approach would be for the handler (or form) class to pass a flag into the deeper business logic to send or not send the email, rather than having the business logic get the $request object and work with request parameters directly.

**Comment by NateWr** [comment]
@asmecher Sorry I'm not entirely clear on your recommendation. Should `SendReviewsForm::_sendReviewMailToAuthor` be removed? Am I meant to be modifying the `saveSendReviews` args [here](https://github.com/pkp/pkp-lib/blob/master/classes/controllers/modals/editorDecision/PKPEditorDecisionHandler.inc.php#L133)? I can't actually find where that function is called. It seems to be set to `EditorDecisionWithEmailForm::$_saveFormOperation` but that variable never seems to be called...

**Comment by asmecher** [comment]
BTW, thanking a reviewer used to be accessed directly from the reviewer grid by clicking the envelope icon. (These icons are long gone but you should have a text action in their place, under the Acknowledged column, once the review has been received and read.)

**Comment by asmecher** [comment]
Nate, looking into [your comment](https://github.com/pkp/pkp-lib/issues/1070#issuecomment-175034126):

There are two processes happening here:
- Email sending with an email template (in `EditorDecisionWithEmailForm::_sendReviewMailToAuthor`, invoked from `SendReviewsForm::execute`)
- Notification creation (which sometimes triggers emails) via the saveFormOperation mechanism. The saveFormOperation is passed along to the form template as the form action.

The `_sendReviewMailToAuthor` email is necessary, as this is the detailed email template for that specific purpose. The other one, triggered by the notification, seems to me to be the problem. @beghelli, can you take a quick look?

**Comment by crism** [comment]
This is related to #1148.

**Comment by asmecher** [comment]
(moving over to @beghelli for a look at https://github.com/pkp/pkp-lib/issues/1070#issuecomment-182043507)

**Comment by asmecher** [comment]
Deferring from OMP 1.2.

**Comment by asmecher** [comment]
@NateWr, assigning to you -- it looks like you started working on this, but I'm not sure how far it got.

**Comment by NateWr** [comment]
It looks like #1148 has solved the email issue. So the only thing that remains in this ticket is to check the floating notifications when a reviewer is assigned and make sure they confirm whether an email was sent or not.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2591

Tests:
https://github.com/pkp/ojs/pull/1426
https://github.com/pkp/omp/pull/417

**Comment by NateWr** [comment]
Tests passed. @asmecher can you code review?

**Comment by asmecher** [comment]
Looks good, @NateWr, please go ahead!

**Comment by NateWr** [comment]
Merged.
