### ISSUE TITLE
3.5 - Redesigned workflow - Font size of notification message is 16px but should be 14px

### ISSUE THREAD

**Issue by Tribunal33** [pkp/pkp-lib#10703]
**Describe the bug**
The font size is bigger than expected for the title of the notification

**To Reproduce**
1. Go to any stage from the active submission list (review, copyediting, production, etc..)
2. Observe the notifcation font size
3. See sampe images below.

**What application are you using?**
 OJS, OMP 3.5.0

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
![Image](https://github.com/user-attachments/assets/b3c01047-0ddd-423b-91b9-cb627d9dbcfb)

**Comment by jardakotesovec** [comment]
@Tribunal33 Thank you. Addressed on main branch

**Comment by Tribunal33** [comment]
Checked OJS and OMP latest main.  Looks good.  14 px for all of the notifications I could find.
