### ISSUE TITLE
3.5 - OJS - Redesigned workflow - Production notifications are being shown on the copyediting stage

### ISSUE THREAD

**Issue by Tribunal33** [pkp/pkp-lib#10700]
**Describe the bug**
After completing the copyediting stage and moving to production stage the notification is seen on the copyediting stage.

**Predcondition** : 
_Able to login and see the notification section message of a production stage submission_

**To Reproduce**
1. Any VM install with latest dataset
2. Login as Journal Manager or Subeditor 
3. From the dashboard find a submission in the production stage
4. Observe the notification section
5. Select copyediting stage from the side navigation
6. Observe the notfication section

**Actual**: Notification section is visible.
**Expected**: Notification section should be removed

**What application are you using?**
 OJS version 3.5 (latest build)

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

![Image](https://github.com/user-attachments/assets/f9f7bb94-83ab-40ab-a376-fa08b97f05bc)

**Comment by jardakotesovec** [comment]
@Tribunal33  Thanks! Good catch, should be now fixed on main branch.

**Comment by Tribunal33** [comment]
This has been fixed with latest changes.  No longer seeing notifications on other stages.  Closing bug.
