### ISSUE TITLE
Exception when creating a custom page menu at the site context

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#10720]
**Describe the bug**
It's not possible to use the custom page menus at the site context.

**To Reproduce**
- 1. Create a custom page menu at the site context
- 2.
  - 1. Try to click on the preview.
  - 2. Or add it to the site and try to open the index page.

**What application are you using?**
` main`  branch

**Additional information**
> Accept null values at the method that you had problems (or do checks/coercions at the calling site)... The line where the exception was raised, including other variables can be dropped, but looks like something is missing. A simple test using a context level menu showed me a couple of other issues, so it's good to review the previous commits on that file.

 _Originally posted by @jonasraoni in [#10578](https://github.com/pkp/pkp-lib/issues/10578#issuecomment-2545173263)_

**Comment by bozana** [comment]
Hi @jonasraoni, I have just reviewed the PR and it looks good, but I do not know how I can test it 😅 Where/how can I create a custom page menu at the site context?
