### ISSUE TITLE
[OMP] press logo alt text is ignored

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1072]
When uploading a press logo, the user is exhorted to provide alt text for accessibility. However, all that is served out is `alt="Page Header Logo"`, regardless of user-provided text.

**Comment by asmecher** [comment]
(Version number?)

**Comment by crism** [comment]
This is against `HEAD`, sorry.

**Comment by crism** [comment]
The text currently comes from `lib/pkp/locale/en_US/common.xml`, key `common.pageHeaderLogo.altText`.

In `lib/pkp/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php`, that token is used in `getImagesSettingsName()`… where else is that used? I think this only affects configuration settings, and is less important (though should still be fixed).

In three templates:

* `lib/pkp/templates/common/header.tpl`
* `lib/pkp/templates/frontend/components/footer.tpl`
* `lib/pkp/templates/frontend/components/header.tpl`

the generic alt text is only used if `$displayPageHeaderLogoAltText` is not set. However, I can’t find anything that would set that… that would seem to be the root of the problem.

**Comment by crism** [comment]
The page logo file is set in `classes/template/TemplateManager.inc.php` by `$context->getPageHeaderLogo()` (which calls a method in `classes/press/Press.inc.php`)… the equivalent incantation is needed for the alt text.

The question, then, is this: Should `getPageHeaderLogo()` be changed to return an array with the image URL and the alt text, or should a second method `getPageHeaderLogoAltText()` be created? The current method is only called in the one place, and it seems cleaner to me to change the existing method, but I don’t want to do anything disruptive.

**Comment by crism** [comment]
I think I have a fix… just need to figure out how to properly manage submodule contributions.

**Comment by crism** [comment]
The bit in `PKPAppearanceForm.inc.php` is only used as alt text when displaying the image just uploaded, and I think it’s fine there. This issue should be closed after the pull request is acted on.

**Comment by asmecher** [comment]
Did you send a PR? Mind posting the link here?

**Comment by crism** [comment]
I believe it’s https://github.com/pkp/pkp-lib/pull/1073.

**Comment by asmecher** [comment]
Thanks, @crism. @NateWr, mind taking a look? This fits in with some front-end changes of yours.

**Comment by asmecher** [comment]
Thanks!
