### ISSUE TITLE
[OJS] Disallow numeric public issue and article ids

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#1074]
Currently editors can enter numeric public ids that may overlap with internal ids, leading to lookup clashes for issue and article data.

For example, an internal issue id used for a lookup via IssueDAO::getIssueByBestIssueId will incorrectly match a public issue id for another issue.

**Comment by bozana** [comment]
@mfelczak, @mtub and me came up against this problem in the journal querelles-net, s. http://www.querelles-net.de/index.php/qn/issue/archive. They are using something like this for the public ids: "16-4" (i.e. volumeNo-No.) When the public ids option in setup 4 is enabled (like now) everything is fine. But, when the journal manager disables the public ids option in setup 4, then the issues cannot be find well, e.g. issue/view/2 is showing issue 3 (which is the first issue having "02-x" as public id). Maybe you can then consider this case too? Thanks!

**Comment by beghelli** [comment]
@mfelczak This is also a problem for stats processing. I discussed this a little bit with Alec here https://github.com/pkp/pkp-lib/issues/1001 (last comments). The idea to solve this is the same that you describe here: avoid purely numeric public ids.

**Comment by mfelczak** [comment]
Thanks @bozana and @beghelli for the additional use cases, that's helpful.

**Comment by mfelczak** [comment]
We need to disallow numeric public ids on the following:
- issue id
- issue galley id
- article id
- article galley id
- supplementary file id

**Comment by mfelczak** [comment]
@bozana, @mtub: is the bug with public ids of the form "volumeNo-No" recent or was this fixed [here](https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8853)? I can't reproduce it on my local install.

**Comment by bozana** [comment]
Hi @mfelczak, the bug is still there in ojs-stable-2_4_8 and ojs-dev-2_4. You can reproduce it like this: 
You will need at least two issues, lets say issue with ID=1 and issue with ID=2.
Go to setup 4.3 and select the option "Custom identifiers will be used to identify issues.".
Then give the issue with ID=1 the custom public identifier "02-1", and the issue with ID=2 the custom identifier "01-2".
Then deselect the option in setup 4.3 again.
Go now to archives and click on the issue with ID=1. You should now actually see the TOC of the issue with the ID=2. And vice versa.

**Comment by mfelczak** [comment]
Thanks for the confirmation, @bozana -- I was able to reproduce it.

This is similar to a previous [bug report](https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8853) dealing with retrieving published articles via public IDs. I'll extend that fix to the following:
- issues
- issue galleys
- article galleys
- supplementary files

Can you please confirm that the following commit fixes the issue for you? Some additional testing for the other publication items would also be welcome.

**Comment by bozana** [comment]
Thanks @mfelczak, this fixes the issue :-) I've also tested it for the other objects. There is just one minor thing to eventually consider: Now, if the public identifier is a number, the error message says "The public identifier X already exists for another object...", which could be true, but I am not sure if it is clear to the users, so maybe to display the error message, that the identifier cannot be a number? -- As I said, just a minor thing and I wouldn't mind if it stays as it is :-)

**Comment by mfelczak** [comment]
Thanks @bozana, much appreciated.

Agreed that the error message isn't ideal. I didn't want to introduce a new locale key since it'd require a round of translations.

@asmecher, https://github.com/pkp/ojs/pull/855 should be ready to go.

**Comment by asmecher** [comment]
(Oops, https://github.com/pkp/ojs/pull/855#issuecomment-222674333 should have been posted here)

**Comment by bozana** [comment]
Oh, good point @asmecher! -- it didn't cross my mind :-O

**Comment by mfelczak** [comment]
closing
