### ISSUE TITLE
Enter not working inside References textarea field

### ISSUE THREAD

**Issue by ajntc** [pkp/pkp-lib#10747]
**Describe the bug**
We can paste a full reference with new lines but cannot use "Enter" inside "References" textarea field. tried on several desktop browsers.
It works in OJS `3.3.0-17`

**To Reproduce**
1. Go to one of submissions
2. Open tab 'Publication > References'
3. Try to use "Enter" key - even on empty field
4. Nothing happens - no new line

**What application are you using?**
Stopped working in `3.3.0-18`. I'm using `3.3.0-19` right now.

**Additional information**
![Image](https://github.com/user-attachments/assets/3214c2b4-e070-483d-a1cf-78122eb461e3)

**Comment by kaitlinnewson** [comment]
Hi @ajntc, thanks for the report. This issue has been fixed (see https://github.com/pkp/pkp-lib/issues/9884 for more details) and was released in `3.3.0-20`, so should be resolved once you upgrade.
