### ISSUE TITLE
[OMP] copying files from one stage to another fails

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1075]
Using OMP `HEAD`. I have a submission in external review, with submission and internal review files, but no external review files.

I visit a URL like `.../omp/index.php/test/workflow/access/2` and select “Upload/Select Files,” which brings up a modal dialog. I check “Include all files from all accessible workflow stages,” select files from the internal review stage, and select OK. The busy icon spins but nothing else happens in the browser. On the server, error messages are seen:
```
PHP Notice:  Undefined variable: newFileId in .../lib/pkp/controllers/grid/files/review/form/ManageReviewFilesForm.inc.php on line 101, referer: .../omp/index.php/test/workflow/index/2/3
PHP Notice:  Undefined variable: newRevision in .../lib/pkp/controllers/grid/files/review/form/ManageReviewFilesForm.inc.php on line 101, referer: .../omp/index.php/test/workflow/index/2/3
omp: Invalid file!, referer: .../omp/index.php/test/workflow/index/2/3
```

**Comment by crism** [comment]
Looks like bad copy-and-paste code from `ManageSubmissionFilesForm::importFile()`. Not sure how to properly populate those variables, though…

**Comment by crism** [comment]
That diagnosis might be correct, but it’s been thus ever since the function was first created in de5c0f418b5e6987322ede5047eed8830c9e284b. Hrm.

**Comment by crism** [comment]
@asmecher, any insights on this one?

**Comment by asmecher** [comment]
@crism, thanks for reporting -- try the commit above?

**Comment by crism** [comment]
@asmecher Works for me!

**Comment by asmecher** [comment]
Thanks for confirming!
