### ISSUE TITLE
[OJS] Implement responsive tweaks for 2.x reader front-end

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1076]
Make changes as necessary so that OJS' reader front end (viewing About pages, main page, article pages, etc.) is responsive. No need to worry about editorial/management interface. The author submission, and reviewer review pages could conceivably be included. 

We should also consider testing using https://www.google.ca/webmasters/tools/mobile-friendly/.

**Comment by asmecher** [comment]
(I do think it's important to start by assessing the 3rd-party work contributed in this area, both as good FOSS citizens and to build on that effort.)

**Comment by jmacgreg** [comment]
Long obsolete.
