### ISSUE TITLE
[OMP] dashboard action buttons have spurious list bullets

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1078]
As seen below, dashboard actions have these weird circles next to them in the latest OMP `HEAD`.

This is due to the button being a doubly-nested `ul/li`… the apparent fix is to change the style in `styles/structure/body.less`, but I want to make sure that won’t interfere with other intended use or styling. Are there strong opinions about that?

![screen shot 2016-01-20 at 2 14 38 pm](https://cloud.githubusercontent.com/assets/1933900/12497814/be3a8ce2-c063-11e5-9310-01808df85db1.png)

**Comment by asmecher** [comment]
@crism, I think your compiled CSS is probably out of date. Try deleting `cache/*.css` and reloading.

**Comment by crism** [comment]
You were right, @asmecher. I guess this is what I get for playing on the bleeding edge.
