### ISSUE TITLE
[OJS] Show status of site-wide plugins for journal managers

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1080]
Journal managers manage plugins in OJS installations. Some plugins are site-wide and can only be activated/deactivated by site admins. The text presented to journal managers is 

```
"This is a site-wide plugin. Only the Site Administrator may manage this plugin." 
```

with no indication of the status. It might help journal managers to know if a particular plugin is enabled or not.

**Comment by NateWr** [comment]
This text does not appear to be used anymore in OJS. Closing as outdated.
