### ISSUE TITLE
Crossref plugin doesn't support newer content-types

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1087]
OJS 2.4.7 uses Crossref schema 4.3.3, but later versions have been updated to support additional content-types, such as text/rtf.

**Comment by asmecher** [comment]
@bozana, would you mind looking at this? It's a short one.

**Comment by ctgraham** [comment]
Short, but note the changelog(s) from Crossref:

crossref4.3.6.xsd:
>   4.3.6  (CSK)  12/2/14  reworked standard designator
   4.3.5  10/31/14 added rel:program to support deposit of relationships
   4.3.5 (PDF) updated standard_designator and child elements, moved mml:math to xrefFaces to fix problem with depositing mathML and other markup, restricted CrossMark update types to an enumerated list, removed cm_update_label
   4.3.5 (PDF) added <relationships> and child elements to support deposit of relationships between DOIs.
   4.3.5 (PDF) 9/8/14 changed standard_designator to designators, etc.
   4.3.4 (PDF) 3/24/2014 moved standard_designator, standards_body, and child elements to common file, added standard_designator to citation
   4.3.3, 4.3.4 (PDF) made doi_data required for standard_metadata
   4.3.4 12/10/2013 

common4.3.6.xsd:
>  4.3.6 (PDF) add WebCite as value for archive, lengthen surname and given_name fields to 55
  4.3.0-6 (PDF) disallow empty value for citation "key" attribute
  4.3.5, 4.3.6 (PDF) 5/14/2015 added text/rtf as mime type
  4.3.6 (PDF) 5/13/2015 relax surname validation to accommodate some author names with '?' and digits.
  4.3.5,6 (PDF) 3/31/2015 added ai:program to components
  4.3.1,2,4,5,6 (PDF) 3/2/2015 removed redundant ORCID validation
  4.3.6  (CSK)  12/2/14  reworked standard designator
  4.3.5	(PDF) 10/9/2014 updated standard_designator and child elements, moved mml:math to xrefFaces to fix problem with depositing mathML and other markup, restricted CrossMark update types to an enumerated list, removed cm_update_label
  4.3.1,2,4 (PDF) 6/24/2014 minor change to ORCID regex to only allow X
  4.3.4 (PDF) 5/27/2014 added unspecified and syndication as values for property attribute, removed tdm as value for content_version
  4.3.2,4 (PDF) 4/14/2014 changed superseded_by to supersedes
  4.3.4 (PDF) 3/26/2014 moved standard_designator, standards_body, and child elements to common file, added standard_designator and standards_body to citation; added type attribute to standard_designator
  4.3.1,,2,4 (PDF) 3/13/2014 added application/epub+zip to mime_type.atts
  4.3.4 (PDF) 12/19/2013 changed 'KLB' to 'KB'
  4.3.4 (PDF) 12/10/2013 added archive_location and archive; changed name to depositor_name to support JATS-like name changes, added alt-name, name elements 
  4.3.4 (PDF) 12/10/2013 added archive_location and archive; changed name to depositor_name to support JATS-like name changes, added alt-name, name elements 
  4.3.4 (PDF) 12/10/2013 added archive_location and archive; changed name to depositor_name to support JATS-like name changes, added alt-name, name elements 

The change passed my own searching and testing, but my efforts shouldn't be considered comprehensive.

**Comment by bozana** [comment]
Thanks @ctgraham! I was just and still am researching the changes... :-)

**Comment by bozana** [comment]
@asmecher , @ctgraham I went though all of the changes and as far as I could see, it is OK. I also tested an issue export.

**Comment by asmecher** [comment]
Thanks, @ctgraham and @bozana -- merged.

@bozana, I don't think this needs to be forward-ported because the CrossRef plugin hasn't been re-adapted to the master branch, correct?

**Comment by bozana** [comment]
@asmecher yes, the master branch contains just a very old version... thus, no re-adapting necessary... thanks!!!

**Comment by asmecher** [comment]
Thanks, closing!
