### ISSUE TITLE
Not all issues displayed for the DOI export/registration

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1088]
The pager is not working on the page Crossref/DataCite/mEDRA > Export issues.

**Comment by bozana** [comment]
@asmecher,  @ctgraham, I think I would need your help here :-\ For export/registration only issues are displyed that can be exported, i.e.
-- for DataCite and mEDRA: only issues that could have a DOI -- this is not that critical
-- for Crossref: only issues that contain an article that could have a DOI -- this mean a looooooot of computation: to go through each issue and through each article...
Thus, till now the rangeInfo was considered to get the all issues from the DB, that are then filtered. Thus the issues from the DB and filetered issues do not necessarily match i.e. paging didn't work. See for example https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/importexport/crossref/CrossRefExportPlugin.inc.php#L121-L148. If I would omit the rangeInfo in the L121, the computation will surely lead to the time execution error :-(
Do you maybe have a good idea how to solve this?

**Comment by ctgraham** [comment]
I think this is tied to https://github.com/pkp/pkp-lib/issues/824.  My (under-researched) opinion is that all issues should be listed.  If the DOI plugin specifies a DOI format for issues and for articles/galleys, registration here will do both.  If the DOI plugin specifies only a DOI format for articles/galleys, registration here will register articles by issue.  If the DOI plugin specifies only a DOI format for issues and not for articles/galleys (unlikely), registration will really just register the issue.

**Comment by bozana** [comment]
What should be displayed if the DOI plugin specifies only a DOI format for articles/galleys, but excludes all articles of an issue, ile. if an issue doesn't have anything to export/register? Hmmm... Maybe, as you said, to display all issues but in this case to disable register and export function? This will still be less computation, than as it is now.

**Comment by ctgraham** [comment]
I vote to display the issue with "0" articles listed, and the Register and Export function disabled, if the DOI plugin is not configured to register Issues and no Articles pass the criteria.

**Comment by bozana** [comment]
@ctgraham, I agree. @asmecher, @jmacgreg: Do you have any concerns regarding this? If not I would solve it this way... :-)

**Comment by jmacgreg** [comment]
Sounds good to me!

**Comment by asmecher** [comment]
Likewise, @bozana -- you and @ctgraham know this better than I do and your approach sounds logical.

**Comment by bozana** [comment]
Hi all ( @ctgraham, @asmecher, @jmacgreg )

I changed the issues display just for the Crossref plug-in for now. Could you please take a look (the commit above and the explanation and images below)? 
If OK so, I would change it for DataCite and mEDRA as well. 

Now all issues are displayed, but if an issue contains only articles that don't have DOIs, then the actions/functions are not displayed for that issue,s.:
![issuesdisplay](https://cloud.githubusercontent.com/assets/378421/12644533/b46093d2-c5c3-11e5-9efb-cc97988de24a.png)

If all listed issues on a page don't contain any article to be registered, then also the buttons (and comments) below the listing table are not displayed:
![nothingtoregister](https://cloud.githubusercontent.com/assets/378421/12644563/ea639240-c5c3-11e5-9415-1e40c8d3fa06.png)

I am not sure if I should also make the following changes for this coming release 2.4.8 or rather for 2.4.9:
-- consider the same display concept for other objects (articles, galleys, supp files) for all DOI export/registration plug-ins -- to display all objects, but without actions/functions if they cannot be registered -- maybe this is not necessary at all?
-- issue https://github.com/pkp/pkp-lib/issues/824 i.e. the possibility to only assign and register issue DOIs in the Crossref plug-in

What do you think?

Thanks a lot!!!

**Comment by asmecher** [comment]
If this addresses the original problem with the pager not working, then I'm happy -- I'd rather we didn't invest too much time in 2.4.x changes unless they're clearly bugs.

**Comment by asmecher** [comment]
Thanks, @bozana & @ctgraham!
