### ISSUE TITLE
Reviews don't appear in My Assigned

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1090]
Even though I have assigned a user as a reviewer, the review doesn't appear in their "my assigned" queue. Is it possible that this is because the submission is already at the production stage? Can anyone else reproduce this problem?

![reviewer-assigned](https://cloud.githubusercontent.com/assets/2306629/12585315/6d290642-c443-11e5-9cc5-271d793268e9.png)

![reviewer-no-my-assigned](https://cloud.githubusercontent.com/assets/2306629/12585319/74050bd2-c443-11e5-87a4-9bdb6bc2875d.png)

**Comment by asmecher** [comment]
@NateWr, can you email me a DB dump so I can look at the exact situation?

**Comment by asmecher** [comment]
@NateWr, when the monograph is published any outstanding reviews will disappear from the reviewer's active queue. Turning off the checkbox...

- [ ] Create a catalog entry for this book based on the metadata below.

...will cause the submission to reapear in the active list.

**Comment by asmecher** [comment]
(I'm OK with the current behavior, at least for 1.2, so closing.)

**Comment by NateWr** [comment]
Yeah of course that makes sense.
