### ISSUE TITLE
Create new reviewer: user created but doesn't appear in user grid

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1091]
When I use the option to create a new reviewer when assigning a reviewer, the user gets created and can be found in the reviewer selection grid. But the user can not be located in the standard users grid.

![create-reviewer](https://cloud.githubusercontent.com/assets/2306629/12585364/acb9436c-c443-11e5-9caa-6cade1b83d3c.png)

![create-reviewer-not-found](https://cloud.githubusercontent.com/assets/2306629/12585363/acb7962a-c443-11e5-891b-a464c7c667f7.png)

**Comment by asmecher** [comment]
@NateWr, [this stanza](https://github.com/pkp/pkp-lib/blob/master/templates/controllers/grid/users/reviewer/form/createReviewerForm.tpl#L36-L44) should either present a drop-down of potential user groups, or if there's just one, auto-select it via a hidden field. Can you check if that field is appearing, or if the hidden field is instead, on the "create reviewer" form?

**Comment by NateWr** [comment]
Yep it's just the hidden field.

![hidden-user-group](https://cloud.githubusercontent.com/assets/2306629/12724002/c6d0cd32-c903-11e5-884e-cb5d5318b8ca.png)

It does look like `nwright` is getting assigned to the External Reviewer group (user group id: 18) in the database. But that's as far as I've looked.

**Comment by asmecher** [comment]
Hmm, so the new user does have the user group, but they aren't showing up in the Users grid... Sounds to me like the problem is the users grid, then, not the reviewer creation process. Mind sending me another DB dump?

**Comment by asmecher** [comment]
The problem was the behavior of SQL `COALESCE(...)` -- when any parameter is `NULL` (as commonly in the case of a result of a `LEFT JOIN`), the returned result is `NULL`. Used `COALESCE(...)` to coerce `NULL` results into empty strings.
