### ISSUE TITLE
OAI-PMH interface strips HTML, but leaves HTML entities

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1092]
To display record content, OAI-PMH strips the HTML tags via `stripAssocArray()`:
https://github.com/pkp/pkp-lib/blob/a39b1328db9ec06d2902e67b337dc5a63c60a496/includes/functions.inc.php#L331

This, however, just calls strip_tags, and so HTML entities are left intact.  These HTML entities are then (appropriately) escaped for XML output and passed to the client.

If plaintext output is intended for something like the dc.description, then it really should be plaintext.

**Comment by asmecher** [comment]
Thanks, @ctgraham!
