### ISSUE TITLE
JBImages plugin artificially constrains directory upload parameter

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1096]
See the "max_upload_dir_size" parameter in the jbimages plugin config.php file (eg. https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_7/lib/tinymce/jscripts/tiny_mce/plugins/jbimages/config.php#L140). This artificially constrains the amount of space a particular user has to upload images. Should this restriction be in place at all? Or, if it is, maybe remove it for editorial/management staff who may need more space? FYI, this is the max space allowed for the users' public folder image dir, that is, "public/site/images/<username>/.

**Comment by asmecher** [comment]
Some kind of constraint is required because otherwise anyone will be able to register (e.g. as Reader) and then use the JBImages tool to upload arbitrary image content.

**Comment by jmacgreg** [comment]
Gotcha - but can the constraint be lifted for editors/JMs?

**Comment by asmecher** [comment]
You should be able to edit lib/pkp/lib/tinymce/jscripts/tiny_mce/plugins/jbimages/config.php and change...

    $config['max_upload_dir_size'] = 25000;

...to...

    $config['max_upload_dir_size'] = (Validation::isEditor() || Validation::isJournalManager())?0:25000;

That will mean Editors and Journal Managers will be unlimited; everyone else will get 25MB. (That's totally untested but smells OK to me.)

**Comment by NateWr** [comment]
Closing as obsolete. Use the [controlPublicFiles](https://github.com/pkp/controlPublicFiles) plugin from v3.2 on.
