### ISSUE TITLE
Escaped HTML is slipping into Crossref exports

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1097]
In OJS 2.x, the journal article abstract is being provided as-is in the Crossref export via the jats:abstract/jats:p field.  The result is that escaped HTML is inappropriately being included.  The actual intent of the jats p tag is described here: http://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-7xd0.html

Proposal: strip the HTML and decode the HTML entities until such time as a robust translation between HTML and JATS is incorporated.

**Comment by ctgraham** [comment]
Also affects in part the PubMed XML export, so my PR will include that as well.  (PubMed export strips the HTML, but leaves HTML entities double-encoded.)

**Comment by asmecher** [comment]
Merged; thanks, @ctgraham.
