### ISSUE TITLE
Crossref / PubMed exports: transform abstract HTML to JATS

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1098]
Feature request as exports are being re-written for OJS 3.x: we should be able to transform relevant HTML tags in the abstract to JATS tags for XML exports like Crossref and PubMed Central.

See also: https://github.com/pkp/pkp-lib/issues/1097

**Comment by bozana** [comment]
@ctgraham, I believe it is solved for Crossref in OJS 3.0: https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php#L119-L124, right?
If so then just PubMed is left in this issue...

**Comment by ctgraham** [comment]
The code you reference is consistent with https://github.com/pkp/pkp-lib/issues/1097, but the scope of this issue goes beyond that.

Specifically, this issue asks whether there can (should?) be a crosswalk from HTML (or upstream XML?) to [JATS tags](http://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-7xd0.html), e.g.: `<b>` to `<bold>`, `<em>` to `<italic>`, etc.

Consider for example:
https://github.com/PeerJ/jats-conversion/blob/master/src/data/xsl/html-to-jats.xsl

**Comment by bozana** [comment]
Aaaaaaaaaaaaa, ok, sorry :-)

**Comment by NateWr** [comment]
It's all a bit up in the air right now, with Libero Editor being abandoned, but I think the question of how will OJS handle JATS internally is different from the question of how it will deliver JATS to downstream consumers like Crossref/Pubmed. My sense is that the approach recommended here -- crosswalking some HTML entities to JATS -- is not going to be the route we go down (wouldn't support images or citations in JATS). I think any distribution we do will be from a JATS file itself. Have you seen the [jatsTemplate](https://github.com/pkp/jatsTemplate/) plugin? I suppose that would be the place to consider any changes to the abstract that are needed, and it may already do that.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
