### ISSUE TITLE
[OJS] PLN Plugin should check prerequisites on the settings page

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#1105]
The PLN plugin doesn't report missing prerequisites (like Archive_Tar) to the journal manager anywhere. They're sent to a log file, but it's difficult for some to find.

As of 2.4.8 (or maybe 2.4.7.1), journals won't to enable the plugin if a prerequisite isn't met. But journals before then could have the plugin enabled without the prerequisites. If they upgrade to 2.4.8, the plugin will remain enabled and there will be no errors displayed.

In the worst case (like Archive_Tar missing), the journal manager could get a WSOD for plugin pages.

**Comment by ubermichael** [comment]
I have a patch in the works. The end result looks like this, for missing prereqs.

![missing-at](https://cloud.githubusercontent.com/assets/1328893/12730196/b0f49cd8-c8df-11e5-83ad-3cb2a57646ba.png)

**Comment by asmecher** [comment]
Merged, thanks!
