### ISSUE TITLE
[OMP] Can’t edit contributors to a book

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1106]
Against `HEAD`: in the Catalog Entry modal pop-up, on the Monograph tab, contributors can be added and reordered, but there seems to be no way to edit their names, e-mail addresses, roles, or status as primary contact or browse-list presence.

**Comment by crism** [comment]
This may be due to badly-constructed HTML; the check-boxes, for instance, have:
```html
<div id="isChecked">
  <div href="#" class="pkp_helpers_container_center checked"></div>
</div>
```
The multiple `div` elements with the same `id` are not valid, nor is the use of `href` on a `div`. This may lead to JavaScript events misfiring… I’m investigating.

**Comment by asmecher** [comment]
(Note that this may also be affecting the Chapters grid -- I recently noticed that the category row actions aren't showing.)

**Comment by crism** [comment]
The chapters grid has its own handler, but curiously, has an `id` of `authorsGridContainer-...`.

What they may have in common is that the grids are getting set to read-only, which disables a bunch of controls… but I’m still tracing the code, so that’s just a gut guess right now.

**Comment by asmecher** [comment]
Just let me know if you want a hand, @crism.

**Comment by crism** [comment]
Why does `PKPAuthorGridHandler` have `editAuthor()` _and_ `updateAuthor()`? That looks suspicious.

Overall, @asmecher, this section of code looks like it wasn’t finished. There are what looks like cut-and-paste errors in both the PHP and the Smarty templates. It might benefit from a review from you.

**Comment by asmecher** [comment]
@crism, I just ran a quick test and I'm able to edit authors as I'd expect. Maybe something specific to your setup -- would you be able to send me a DB dump along with a few notes on duplicating the problem (e.g. what account you're logged in with, and what submission ID you're looking at)?

**Comment by crism** [comment]
Hm. I thought it might have something to do with the published status of the submission in question, but a different, unpublished submission has the same problem, in both Chrome for Windows and Firefox for Linux. Will try to prepare a database snapshot for you.

**Comment by asmecher** [comment]
Thanks, @crism. What's happening is that the grid is deciding you don't have permission to edit authors because you're not assigned to the submission, but in doing a little bit of related clean-up I'm down a rabbit-hole. I'll post a fix once I dig out.

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/omp/pull/208
https://github.com/pkp/pkp-lib/pull/1110

This shares a bunch of code that was previously duplicated in OJS and OMP. There were slight differences -- OJS and OMP differed in when they permitted various roles to edit and add authors -- but I don't think those differences were the result of design so much as nearly-parallel evolution.

Bruno, could you have a look? If it seems OK, I'll port to OJS master and merge.

**Comment by beghelli** [comment]
Nice clean up! Good to go, I think.

**Comment by asmecher** [comment]
OK, thanks.
