### ISSUE TITLE
Review SEO-implications of meta tags

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1109]
We're currently setting meta tags for `keywords` and `description` in the header of every page on the frontend.

https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/headerHead.tpl#L16-L17

The `keywords` tag should be removed. It is not used by Google and may be treated as malicious by other search engines, due it's frequent abuse. Here is Matt Cutts from Google explaining:

https://www.youtube.com/watch?v=jK7IPbnmvVU

The `description` tag should be removed if it is not unique on every URL. And I don't think it's likely or valuable for us to try to be generating appropriate tags for every page on the frontend. Duplicate meta descriptions can be harmful for a page's uniqueness, which impacts its SEO value. Here is Matt Cuts explaining again:

https://www.youtube.com/watch?v=W4gr88oHb-k

**Comment by NateWr** [comment]
If there are no objections here I can remove them. @asmecher anyone we should pull in here?

**Comment by asmecher** [comment]
No, @NateWr, I'm content with that.

**Comment by NateWr** [comment]
https://github.com/pkp/pkp-lib/pull/1180
https://github.com/pkp/ojs/pull/759
https://github.com/pkp/omp/pull/225
https://github.com/pkp/pdfJsViewer/pull/8

**Comment by asmecher** [comment]
All merged/cherry-picked -- thanks, @NateWr!
