### ISSUE TITLE
Changing the maximum upload size - 3.0b

### ISSUE THREAD

**Issue by MorganGarvin** [pkp/pkp-lib#1114]
Hello, 

I'm having an issue changing the maximum allowed upload size in the OJS 3.0b. I have the php.ini file set up with post_max_size = 0 (unlimited), upload_max_filesize = 1024M , and memory_limit = 1128M.I have also removed the htaccess file from the tinymce folder. 

Files up to about 100MB work however anything over that produces the HTTP error "Upload URL might be wrong or doesn't exist" 

Am I missing anything obvious here? Or approaching this in the right way?

Thanks,

Morgan

**Comment by asmecher** [comment]
@MorganGarvin, check your Apache post limit and watch for messages in your error log. Next time, could you post questions like this in our [support forum](http://forum.pkp.sfu.ca/)?

**Comment by MorganGarvin** [comment]
@asmecher Terribly sorry, I'll move this conversation there!
