### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by nschloe** [pkp/pkp-lib#1119]
I would like to be able to retrieve meta data of articles (and possibly their PDF URL) via a REST API in OJS. Does such a thing exist?

**Comment by asmecher** [comment]
Hi @nschloe. Could you post this sort of question on our forum at http://forum.pkp.sfu.ca/?

**Comment by asmecher** [comment]
(See https://github.com/pkp/pkp-lib/issues/1503 for some early spec work on this)
