### ISSUE TITLE
Email parameters missing when selecting and unassigning a reviewer

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1121]
Some variables in e-mails REVIEW_REQUEST and REVIEW_CANCEL, i.e. when selecting and unassigning a reviewer, are not resolved because the parameters are missing.

**Comment by bozana** [comment]
Ah, now I see that there is a similar issue already: https://github.com/pkp/pkp-lib/issues/1099

**Comment by bozana** [comment]
S. https://github.com/pkp/pkp-lib/pull/1134 for REVIEW_REQUEST

**Comment by asmecher** [comment]
@bozana and @selwyntcy, could you have a quick look at this PR? https://github.com/pkp/pkp-lib/pull/1166

I added a function (`MailTemplate::replaceParams`) to pre-assign variables to a message body before it's sent. This allows us to avoid ever presenting variable tags when it's not necessary, which is almost always the case. I added calls to this in the reviewer unassign and acknowledge (thank) emails.

It would've been nice if I could have built this behavior into the existing `getBody` or `assignParams` calls, but I didn't feel like the calling semantics would be clear enough so I left it for now.

Do you think this is a good approach to use elsewhere?

**Comment by bozana** [comment]
@asmecher, I think this is good and it can me merged ;-)

**Comment by asmecher** [comment]
Great! Closing.

**Comment by selwyntcy** [comment]
Thanks, @asmecher!
