### ISSUE TITLE
[OMP] reviewer status is too sticky

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1122]
[Using `HEAD` of OMP.] When a user looks at their assignments in the dashboard, if they have ever been a reviewer on a submission, then the action URL is to the reviewer action (_e.g._ `.../reviewer/submission/2`). There is no way (aside from knowing the correct URL) to get to the submission’s actual current state.

**Comment by crism** [comment]
This problem appears to trace to `SubmissionsListGridCellProvider::getCellActions()`, specifically:
```php
$reviewAssignmentDao = DAORegistry::getDAO('ReviewAssignmentDAO');
$reviewAssignment = $reviewAssignmentDao->getLastReviewRoundReviewAssignmentByReviewer($submission->getId(), $user->getId());
if (is_a($reviewAssignment, 'ReviewAssignment')) return array(new LinkAction(...));
```
Either `$reviewAssignment` should be `null` if the review is finished (which seems inappropriate), or there needs to be additional logic to see if the user has some subsequent role to play with respect to this submission.

**Comment by crism** [comment]
Indeed, it looks like someone started down this road… `$userGroupDao` is created at [`controllers/grid/submissions/SubmissionsListGridCellProvider.inc.php:97`](https://github.com/pkp/pkp-lib/blob/master/controllers/grid/submissions/SubmissionsListGridCellProvider.inc.php#L97), but then never used.

**Comment by crism** [comment]
Though I think the thing is to look at the round associated with the review; if the round is over, then use `getUrlByUserRoles()`… I’ll try that and see what it does.

**Comment by crism** [comment]
That resolves the problem for the multi-role reviewer, but now the reviewer-only gets, “You don’t currently have access to that stage of the workflow.” What’s the correct logic to determine the last stage to which a user had access?

**Comment by asmecher** [comment]
I'm not sure if this adequately answers your question, but you should be able to use `$reviewAssignment->getStageId()` to determine what stage the review assignment applies to.

**Comment by crism** [comment]
Ah… yes, I’m going to claim that this is fixed; the resulting problem is related to a problem found in #1127, which I’ll file separately.

**Comment by asmecher** [comment]
Thanks, @crism, that sounds great -- is there a PR attached? I don't see a link here.
