### ISSUE TITLE
[OJS] Typo in Google Analytics Plugin

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#1130]
Typo on Google Analytics plugin. 

"Leave the site hompage settings as-is"

<img width="832" alt="screenshot 2016-02-10 12 48 43" src="https://cloud.githubusercontent.com/assets/504276/12954425/e7892c20-cff4-11e5-9420-e92fd6f89df3.png">

**Comment by asmecher** [comment]
Fixed! Ahem yourself.
