### ISSUE TITLE
[OJS] GET used for changing state of the system

### ISSUE THREAD

**Issue by judgej** [pkp/pkp-lib#1131]
HTTP GET should *never* change state of the system, because GET URLs can be cached, and fed to administrators who may happen to be logged in using all sorts of hidden techniques.

GET is used throughout this application to change state - to update, delete, add, move items etc. No CSRF tokens are used to prevent these actions from taking place if presented to the browser of an administrator who happens to be logged in.

So when changing state - don't use GET - ever. Use RESTful methods instead - they are all well known. Anything using AJAX has no excuse as POST/PUT/DELETE/PATCH/FOOBAR can be used without restriction. Browser forms can only do GET and POST, but should all be POST anyway. Simple links to delete items in lists, need to handled using AJAX (not using GET) or at an absolute minimum have a CSRF token unique to every page load.

**Comment by asmecher** [comment]
We're aware of this need for strengthening but haven't gotten to it yet. There is a small first step in place to mitigate problems with forms in that we check to ensure that they're submitted via POST, but that doesn't resolve URL-based actions like (most commonly in OJS) re-ordering or deleting items.

We're better positioned to address this systematically in the OMP / OJS 3.0 generation of code, where we're using JQueryUI etc. But for OJS 2.x switching away from GETs will be a pain, and I suspect CSRF tokens will be a good middle ground to reduce the potential for abuse while still not fully meeting the intentions of GET URLs.

**Comment by asmecher** [comment]
Here is the first of several additions to the toolkit to address this issue: Add CSRF token tools to form classes. https://github.com/asmecher/pkp-lib/commit/a1aa4dea476ee2f8db6e2240f6694fbc777df29f

- Form classes can add CSRF checks: https://github.com/asmecher/pkp-lib/commit/a1aa4dea476ee2f8db6e2240f6694fbc777df29f#diff-448e48a9756df9accaafc39141ffb394R43
- Form mark-up can include CSRF tokens: https://github.com/asmecher/pkp-lib/commit/a1aa4dea476ee2f8db6e2240f6694fbc777df29f#diff-d6f0f421cae68b3800d74f94e94771b7R22

Tokens are maintained by the Session object and expire every 24 hours or along with the session, whichever comes first. @judgej and perhaps @ctgraham, I'd love to have your feedback on this so far.

If this looks good I'll add it to all the appropriate forms, then move on to looking at `GET` requests.

**Comment by judgej** [comment]
Just some notes based on my encounters of CSRF in other systems:

CSRF tokens are normally replaced on every single page load - not kept for any extended periods. Not sure if I read your "24 hour period" correctly. A page that has AJAX POSTs and PUTs will actually get its CSRF token refreshed on every POST. Libraries such as jQuery can automatically keep track of that and update the CSRF token in a header meta field each time it changes (on receipt of every POST!)

Frameworks such as laravel handle CSRF in middleware. Before the controller even sees the request, the middleware will see if a POST or PUT is being submitted, that it has a CSRF token, and that it is correct, and will halt the page with an exception immediately if it needs to. That way it is not up to each individual form handler to have to implement a CSRF check. That way there are never any forms that accidentally forget to implement the checks. It may be necessary to disable that CSRF middleware check on a few select pages, such as callbacks from payment gateways, but in general if it is always on for every page, then it helps secure the application substantially.

I've not looked in depth at your code (will try to tomorrow), but it is a great move forward.

**Comment by asmecher** [comment]
Thanks, @judgej. FYI, I opted for CSRF tokens that expire with the sooner of 24 hours or the session because of the multiple-tab scenario (I frequently navigate this way). It's a security trade-off but a fair one (in my fallible opinion).

**Comment by asmecher** [comment]
(The more I think about it, though, the more 24 hours seems excessive.)

**Comment by asmecher** [comment]
Pulls/commits:

- OJS master: https://github.com/pkp/ojs/pull/951
- OMP master: https://github.com/pkp/omp/pull/313
- pkp-lib master: https://github.com/pkp/pkp-lib/pull/1651
- customBlockManager master: https://github.com/pkp/customBlockManager/commit/3d3f663900198f4ef8a3462e57e113c816287121
- googleAnalytics master: https://github.com/pkp/googleAnalytics/commit/1523c36f62e9b57873dd830854232a4227bbf5db
- orcidProfile master: https://github.com/pkp/orcidProfile/commit/b0121aa742168991b5e159e1cc42b7456a631f35
- staticPages master: https://github.com/pkp/staticPages/commit/d1e0ac01f88474d3101c33b5af1bc5a4cdb3633a
- translator master: https://github.com/pkp/translator/commit/2e71e5b36651337158e21f76bc72bc6bfab91ecb

I'm going to merge/commit all of this, rather than leave so many submodule updates floating around, but @bozana, I'd love for you to take a spin through these changes. There's a lot of repetitive work here, so a close look at the overall approach and a high-level skim through the bulk of it would probably be best.

**Comment by asmecher** [comment]
By the way, I dropped the maximum validity of the CSRF token to 1 hour.

**Comment by asmecher** [comment]
(@NateWr, I think github inadvertently closed this with your commit. I'm never sure why/when it does this. Reopening.)

**Comment by asmecher** [comment]
@bozana, have you had a chance to look over my overall approach here?

**Comment by bozana** [comment]
Sorry @asmecher, not in Detail, but I will today or tomorrow, OK?

**Comment by asmecher** [comment]
Sure, thanks! I'm just never sure when these notifications get through.

**Comment by asmecher** [comment]
@bozana, sorry to bug you on this one :)

**Comment by bozana** [comment]
@asmecher, wow, tons of work! Great job! :-))) 
I did the review and testing, and there are just a few comments... 
Sorry, you will not believe me, but first today I saw your first message for me above, from 19 days ago :-\ and thus first today I realized what do you want me to do... :-P You are right, I apparently do miss those comments sometimes :-\

**Comment by asmecher** [comment]
Thanks for the review! Closing for now, though there are certainly areas we could broaden CSRF checking, and I'd still welcome feedback on the general approach (if you're still following the issue, @judgej).

**Comment by judgej** [comment]
Following, but not heavily involved in development in PKP at the moment. Got a couple of sites up, so helping to improve security is certainly still of interest :-)

**Comment by asmecher** [comment]
Sure, thanks!
