### ISSUE TITLE
Author Exposed in Reviewer Dashboard Grid for Double-blind Review

### ISSUE THREAD

**Issue by selwyntcy** [pkp/pkp-lib#1136]
The last name of a submission's author is exposed in the reviewer dashboard grid for a double-blind review in OJS.

From the screen cap below, the author's last name "ojs3" is shown in front of the submission title.

![author_exposed](https://cloud.githubusercontent.com/assets/13673787/13043150/5719ff46-d401-11e5-8312-891fe16ddbac.png)

**Comment by selwyntcy** [comment]
The assigned submission is of the class `Article` instead of `ReviewerSubmission`, and thus it escapes the test for review method in https://github.com/pkp/pkp-lib/blob/cb6fa16ad663618fe2133dc6dec556bb0e8535fa/controllers/grid/submissions/SubmissionsListGridCellProvider.inc.php#L152

**Comment by asmecher** [comment]
Definitely a good catch -- thanks, @selwyntcy! Will take a look, unless you're tinkering with it. We added the author name to the title post-1.1.1 and obviously overlooked this case. A general review is probably a good idea to make sure other areas aren't affected e.g. notifications.

**Comment by selwyntcy** [comment]
@asmecher Please proceed. I'm still new to the code, learning along :)

**Comment by asmecher** [comment]
Fixed -- this may need better optimization later, but it should work. Also prevents reviewers from searching by author name. Thanks for reporting, @selwyntcy!

**Comment by selwyntcy** [comment]
Thanks, @asmecher!
