### ISSUE TITLE
Remove expedited submission process

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1138]
Nate's pulls:

https://github.com/pkp/ojs/pull/749
https://github.com/pkp/pkp-lib/pull/1115
https://github.com/pkp/omp/pull/212

My rebases:

https://github.com/pkp/ojs/pull/751
https://github.com/pkp/pkp-lib/pull/1137
https://github.com/pkp/omp/pull/219

**Comment by asmecher** [comment]
@NateWr, I created this issue for tracking purposes and prefixed all the PR titles with `pkp/pkp-lib#1138`. Otherwise the chaos of pull requests -- 6 in this case -- gets really hard to track. This way there's one definitive place to look for the bug's status.

**Comment by NateWr** [comment]
:+1:
