### ISSUE TITLE
[OMP] Users offered inaccessible URLs

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1139]
From both #1122 and #1127, both against `HEAD`.

#1122: `SubmissionsListGridCellProvider::getUrlByUserRoles()` produces a URL which the user does not have access to, if the submission has moved on. The user should instead get the most recent stage to which they have permission.

#1127: When a review is begun, the author is notified that their submission has changed status. However, the notification includes a link to the workflow (`.../index.php/workflow/access/4`), which the author does not have permission to see (“The current role does not have access to this operation”)

**Comment by asmecher** [comment]
@crism, the attached patch should at least correct the problem of authors getting `workflow` URLs.

Do you have a set of reproduce steps for the other issue, where users can't access stages after the workflow has moved on?

**Comment by crism** [comment]
Interesting… I’ll test f17c3ee here, thanks.

As for reproduction… I’ll double-check, but I think a reviewer with no other role is locked out once the work is in production.

**Comment by asmecher** [comment]
Ah, I see that problem with reviewers. Looking now.

**Comment by asmecher** [comment]
OK, I think these have it covered. Closing for now -- but please test if you get the chance, @crism!

**Comment by crism** [comment]
This looks pretty good to me. Nice work!
