### ISSUE TITLE
[OMP] Enroll Existing User is confusing

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1147]
From #1127, against `HEAD`:

In the Enroll Existing User modal, it’s not obvious what the effect of the user group selection is, nor that the box populated with “Reviewer” is the place to type a name to search for.

**Comment by bozana** [comment]
@crism, I think this is now solved in #1149 right?

**Comment by crism** [comment]
If we change the label in “Reviewer,” yes. Did that actually change?

**Comment by bozana** [comment]
Do you mean the label for the autocomplete field? If so, yes, I've just made a PR: https://github.com/bozana/pkp-lib/commit/ced7371b251cf4966eb41a0afb3ef98883a07f9d

**Comment by crism** [comment]
Yes, that seems to address it. (IMO, it would be appropriate for that commit to reference this issue, just for future reference.)

**Comment by bozana** [comment]
Yes, I've just seen this issue... :-\

**Comment by asmecher** [comment]
@bozana, I merged https://github.com/pkp/pkp-lib/pull/1203 -- does that completely address this issue?

**Comment by bozana** [comment]
Yes, closing... :-)
