### ISSUE TITLE
[OMP][OJS] only send one e-mail per user for event notification

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1148]
From #1127, against `HEAD`:

When a review is begun, the author is notified that their submission has changed status. However, the notification includes a link to the workflow (`.../index.php/workflow/access/4`), which the author does not have permission to see (“The current role does not have access to this operation”). (This separate issue is filed as #1139.)

A more useful notification typically follows on its heels. In fact, many notifications seem to be paired: “Hey, something happened,” and “Here’s useful information about what happened.” The less-informative notification could be suppressed.

**Comment by crism** [comment]
All the action happens in `PKPEditorDecisionHandler::_saveEditorDecision()`, which calls `NotificationManager::updateNotification()` up to 3 times.

**Comment by asmecher** [comment]
@beghelli, is this something you touched on with your recent commits?

**Comment by crism** [comment]
This behavior is evident in OJS `HEAD` as well. When an editor requests revisions, the author receives a nice e-mail with the request. He also receives a notification that there is a message within OJS; that message is the same one that was e-mailed.

**Comment by crism** [comment]
Actually, after deeper tracing, I think the problem is within `PromoteForm::execute()`, which calls `EditorDecisionForm::_initiateReviewRound()`, which eventually leads to `PKPNotificationOperationMaager::sendNotificationEmail()`, and then calls `EditorDecisionWithEmailForm::_sendReviewMailToAuthor()`. That will result in two e-mails being sent.

**Comment by crism** [comment]
Ah… except that many of these notifications have no user associated with them, so `PKPNotificationOperationManager::sendNotificationEmail()` exits without actually sending e-mail. That makes sense, since there are 5 calls to `createNotification()`… now I just need to track down which ones actually result in e-mail being sent.

**Comment by crism** [comment]
OK, it’s down to this:
```
EditorDecisionHandler::savePromoteInReview();
 → PKPEditorDecisionHandler::savePromoteInReview();
  → EditorDecisionHandler::_saveGeneralPromote();
   → PKPEditorDecisionHandler::_saveEditorDecision();
    ⇒ PromoteForm::execute();
     → EditorDecisionWithEmailForm::_sendReviewMailToAuthor();
      ⇒ SubmissionMailTemplate::send(); // sends mail to author
    ⇒ PKPNotificationManager::updateNotification();
     ⇒ EditorDecisionNotificationManager::updateNotification();
      → NotificationManagerDelegate::createNotification();
       → PKPNotificationOperationManager::createNotification();
        → PKPNotificationOperationManager::sendNotificationEmail();
         ⇒ MailTemplate::send(); // sends more mail to author
```
Now, the question is what is the better thing to do…

**Comment by asmecher** [comment]
@beghelli, do you have a preference?

**Comment by crism** [comment]
The second notification is the less useful one. If we could pass a flag saying that the e-mail is redundant, that would do it… the problem I immediately see is that we’d have to pass that flag all the way from `updateNotification()` on down. It might be possible to decide whether or not to send e-mail lower down that chain, based on the state of the world, but the don’t-send-email checkbox complicates that.

So what do you all think of that no-email flag?

**Comment by crism** [comment]
Ah-hah! We already _have_ '$suppressEmail'—we’re just not using it!

**Comment by asmecher** [comment]
;) The trials and tribulations of working with a large codebase.

**Comment by crism** [comment]
Gah. The problem is that my listing above is oversimplified; `PKPNotificationManager::updateNotification()` actually iterates through multiple notification types, and calls `updateNotification()` on the appropriate handler for each one. We need to be able to figure out how to suppress e-mail on `EditorDecisionNotificationManager` _if_ e-mail has been sent directly (_i.e._, the user did not check the box on the form), but not suppress e-mail for the other notifications (_e.g._ to reviewers). It seems like that logic belongs in the handler, but then I have to figure out how to get access to the right information to make the decision… bleah.

**Comment by asmecher** [comment]
The "do not send email" checkbox is intended for situations where the editor (etc) has communicated directly with the reviewer (etc). I'd suggest suppressing the notification email regardless of whether the box was checked.

**Comment by crism** [comment]
Hmm… I don’t know. I think there’s merit to the author knowing that something has changed within the OMP system, even if the editor advised them separately that the manuscript was being sent for review. _E.g._, the editor may actually _do_ it immediately, or take a week to get around to it… So if the personal message e-mail isn’t sent, then I do think it’s worth sending a notification update to the author.

**Comment by asmecher** [comment]
Do you have other use cases for the "do not send email" checkbox? I'd expect editors to check it only if they've already spoken with the recipient. If they want the recipient to receive an email, they won't check the box.

**Comment by crism** [comment]
That’s a good point… and it does make the coding easier. I think we can just always suppress e-mail from `EditorDecisionNotificationManager` in that case; I’ll have to trace it through to be sure.

**Comment by crism** [comment]
- [x] PR #1309 addresses only author notification of editor decisions.
- [ ] I’ll look at revision requests next; after that, I’ll file specific issues for other instances of redundant e-mail. (When I filed this, I hoped there was a general solution…)

**Comment by asmecher** [comment]
Merged -- thanks, @crism.
