### ISSUE TITLE
[OMP] error when re-enrolling a user as a reviewer

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1149]
From #1127, against `HEAD` (but with more detail):

User 2 is a member of group 18 (external reviewers). User 2 participated in the first round of external reviews. In the second round, under “Locate a Reviewer,” User 2 is not listed. When “Enroll Existing User” is selected, User 2 can be found, but on attempting to add him as a reviewer, the notification dialog spins indefinitely, and an error message is logged:
```
DB Error: Duplicate entry '18-2' for key 'user_user_groups_pkey', referer: .../index.php/test/workflow/index/2/5
```
Either the user should be permitted to participate in multiple review rounds (my preference), or should be explicitly disallowed, even through enrollment. In either case, adding a user to a group of which they are already a member should never cause an error; the pre-existence should probably just be taken as a success. (Maybe use `UPDATE IGNORE`?)

**Comment by crism** [comment]
The initial selection of candidates is in `PKPUserDAO::getFilteredReviewers()`. Scrutinizing the SQL query…

**Comment by crism** [comment]
[Aside: what is the point of `COALESCE(COUNT(...),0)`? `COUNT()` should always return an integer, never `NULL`.]

**Comment by asmecher** [comment]
Hmm, I can't spot any good reason to have `COUNT` wrapped in a `COALESCE`, and the git history points the finger at me. Suggest removing it.

**Comment by crism** [comment]
The problem seems to be:
```sql
WHERE	ras.review_id IS NULL
	AND ran.review_id IS NULL
```
… which is fine if there is only one round of reviews, but with multiple rounds, a reviewer may well participate again. I need to untangle this logic to put it back together…

**Comment by crism** [comment]
@asmecher: noted, thanks.

**Comment by crism** [comment]
I believe this fixes the initial selection. I’ll test it, then see if a fix for the second part is even needed.

**Comment by crism** [comment]
This does seem to work for selection. Assigning the round 1 reviewer to round 2 via the grid works. However, Enroll Existing User still causes the duplicate key error; adding a user to an already-relevant group should be fine to do.

**Comment by crism** [comment]
It does seem that `INSERT IGNORE` will do the trick. Testing, though I’m curious if there are security implications I’m not thinking of.

**Comment by asmecher** [comment]
`INSERT IGNORE` would bump our MySQL requirements considerably; I haven't checked PostgreSQL. Have you looked at the ADODB `replace` function? That's what we've used elsewhere in OJS/OMP.

**Comment by crism** [comment]
With `replace()`, the error log says, “Invalid reviewer id.” Hm.

**Comment by crism** [comment]
Seems to be `ReviewerForm::execute()`. Not sure why…

**Comment by crism** [comment]
`ReviewerForm::_isValidReviewer()` uses `PKPUserDAO::getReviewersNotAssignedToSubmission()`, which also ignores round-wise assignment. So why did this work with `INSERT IGNORE` but doesn’t now? Hm.

**Comment by crism** [comment]
And why doesn’t the grid constructor use `getReviewersNotAssignedToSubmission()`?

**Comment by asmecher** [comment]
@bozana, can I throw you into this one? It'll take some investigation and I'm currently snowed under.

**Comment by bozana** [comment]
@crism, don't you think that the external reviewer shouldn't be displayed/considered here (using the function Enroll Existing User) at all? Isn't the mistake already there? Why would I like to enroll an user that is already enrolled?

**Comment by bozana** [comment]
I think this SQL solves the problem:
`$result = $this->retrieve(
			'SELECT DISTINCT u.*
			FROM users u, user_groups ug, user_user_groups uug
			WHERE u.user_id NOT IN
				(SELECT DISTINCT u.user_id
				FROM users u, user_user_groups uug, user_groups ug
				WHERE u.user_id = uug.user_id AND ug.user_group_id = uug.user_group_id AND ug.role_id = ?)' .
				($contextId?' AND ug.context_id = ?':'') .
				(isset($search) ? ' AND (u.first_name LIKE ? OR u.middle_name LIKE ? OR u.last_name LIKE ? OR u.email LIKE ? OR u.username LIKE ?)':''),
			$params
		);`
@crism, could you maybe take a look, test and integrate it into your PR?
I would then say that we forget the other issue for now -- enrolling the user that already has that role -- I believe this shouldn't happen -- if no objections...

**Comment by crism** [comment]
It can be further simplified:
```php
		$result = $this->retrieve(
			'SELECT	*
			FROM	users
			WHERE	user_id NOT IN (
				SELECT	DISTINCT u.user_id
				FROM	users u, user_user_groups uug, user_groups ug
				WHERE	u.user_id = uug.user_id
					AND ug.user_group_id = uug.user_group_id
					AND ug.role_id = ?
				)' .
				($contextId ? ' AND ug.context_id = ?' : '') .
				(isset($search) ? ' AND (u.first_name LIKE ? OR u.middle_name LIKE ? OR u.last_name LIKE ? OR u.email LIKE ? OR u.username LIKE ?)' : ''),
			$params
		);
```

**Comment by crism** [comment]
Oops, no it can’t. `d-:`

**Comment by crism** [comment]
There, I think that’ll do it. Seems to work here.

**Comment by bozana** [comment]
Great @crism! Thanks a lot! Do we then need those changes for the double group assignment? I would rather not consider them now i.e. just if they are needed...

**Comment by crism** [comment]
I’d prefer to keep it; it’s more robust. If the user does, somehow, happen to already be in the group—perhaps due to a race condition from having more than one administrative user—this will silently succeed, whereas without the change, it throws an error.

**Comment by bozana** [comment]
OK, I will then take a look at/test this too... :-)

**Comment by bozana** [comment]
Phew this is getting more complicated :-P 

I think that the function 'getReviewersNotAssignedToSubmission' can be removed from the PKPReviewerGridHandler -- as far as I can see it is not used anywhere. @asmecher, could you maybe think of a strange call of this function that I could not be able to find with grep? ;-)

And I think the function 'getReviewersNotAssignedToSubmission' in PKPUserDAO is not working correctly -- probably the SQL statement is wrong again, but I cannot think about this now -- it's too late here -- maybe tomorrow... :-)

**Comment by asmecher** [comment]
@bozana, I think grepping that function should catch any use of it; I suspect that function is a leftover from OJS 2.x.

**Comment by bozana** [comment]
@crism, could you please please please remove the getReviewersNotAssignedToSubmission from PKPReviewerGridHandler too?

I took a look at PKPUserDAO ::getReviewersNotAssignedToSubmission -- it works well, the only thing we could eventually consider: This function considers if there is an unfinished review of a reviewer. If so, the reviewer will not be considered/returned in the result i.e. he/she will not be able to be assigned in the next round. This is not the case in the PKPUserDAO ::getFilteredReviewers function. So what is the right approach? -- We will have to make them both work in the same way.
@asmecher, what do you think is the right approach -- can a reviewer that haven't finished a review be considered for the next review round?

**Comment by bozana** [comment]
@asmecher, there are a few small things that could be changed -- the info texts do not seem to be totally right:
a) When choosing a user to enroll as a reviewer, "Reviewer" is displayed in the input field, but actually any other user that is currently not a review (but will be then enrolled as a reviewer) is meant to be here, s:
![infotext](https://cloud.githubusercontent.com/assets/378421/13352474/c9cb51a4-dc8d-11e5-9bfc-04d070d2b5eb.png)

b) When creating a new round, the following text is displayed -- I am not sure about the files but the reviewer from the last round are definitely not preselected, thus maybe to remove that sentence?
S:
![newreviewroundtext](https://cloud.githubusercontent.com/assets/378421/13352514/0a2d3af0-dc8e-11e5-9514-45020a4eb056.png)

**Comment by crism** [comment]
> @crism, could you please please please remove the getReviewersNotAssignedToSubmission from PKPReviewerGridHandler too?

Done, though it maybe should be orthogonal to this issue.

**Comment by asmecher** [comment]
@bozana, to answer [your question](https://github.com/pkp/pkp-lib/issues/1149#issuecomment-189257204):
> what do you think is the right approach -- can a reviewer that haven't finished a review be considered for the next review round?
I don't know off the top of my head, so I'd err on the side of permissiveness. If the Editor wants to choose a reviewer who didn't finish a review in the last round, that's up to them IMO.

For [these questions](https://github.com/pkp/pkp-lib/issues/1149#issuecomment-189259001):
> When choosing a user to enroll as a reviewer, "Reviewer" is displayed in the input field, but actually any other user that is currently not a review (but will be then enrolled as a reviewer) is meant to be here
I'm not sure I follow perfectly, but I think you're asking whether the "Reviewer" label is good enough a prompt for the user to type a name? Agreed, it's not very good. We use a "Search By Name" label outside the "Assign Reviewer" modal; maybe follow that example.
Hmm, it looks like you're right. It would be good to follow OJS 2.x's example here, as it seems to have kept people reasonably satisfied. Could you file an issue for that?

**Comment by bozana** [comment]
@asmecher, I will then change the function PKPUserDAO ::getFilteredReviewers so that it returns also reviewers that haven't finished a review. I will also change the label to "Search By Name" and file an issue for the review round text.
@crism, thanks a lot! The function "getReviewersNotAssignedToSubmission" is also listed in the _getReviewRoundOps but I can remove that, together with the change above.

**Comment by asmecher** [comment]
Thanks

**Comment by bozana** [comment]
Thanks @asmecher! I've made the last PR belonging to this issue... :-)

**Comment by asmecher** [comment]
Merged https://github.com/pkp/pkp-lib/pull/1203 -- thanks!
