### ISSUE TITLE
[OMP] author can’t indicate revisions are complete

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1150]
From #1127, against `HEAD`:

There does not seem to be a way for the author to indicate that revisions are complete. They can upload files… but how does the editor know they’re done?

**Comment by crism** [comment]
This also applies to copy edits; how does the copyeditor signal completion?

**Comment by asmecher** [comment]
The new "discussions" area is where communication about copyediting takes place. They would use that to compose a message to the editor.

**Comment by crism** [comment]
Thanks, @asmecher. That was definitely not clear to our role-playing group; at a minimum, this needs to be addressed via the on-screen documentation. It does seem like a hand-off process to us, though.

**Comment by asmecher** [comment]
Duplicate of https://github.com/pkp/pkp-lib/issues/2665.

**Comment by bozana** [comment]
This will be solved together with https://github.com/pkp/pkp-lib/issues/3278
