### ISSUE TITLE
[OMP] half-entered production discussions look weird to other users

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1155]
From #1127, against `HEAD`:

When one user starts a Production Discussion, other users will see an odd, half-baked entry, until the first user finishes submitting it. It seems like the item should be invisible to other users until submission is complete. (The discussion is visible, with a name of just a dash and no other metadata. Presumably, a stub is made in the database; it should either be deferred, or marked as incomplete and skipped by other users.)

**Comment by crism** [comment]
Ooh, fun. Try this, from two computers, with two logins:
 1. From computer A, logged in as user A, click Add discussion.
 1. From computer B, logged in as user B, refresh the relevant page (say, external review).
 1. From computer B, find the stub discussion. Select the expand arrow.
 1. From computer B, delete the discussion.
 1. From computer A, fill in the subject and message for the new (and now deleted) discussion.
 1. From computer A, save the discussion.

Sadly, no fireworks, but computer A gets `##user.authorization.invalidQuery##` message.

In any case, this demonstrates a potentially serious race condition, especially if any users are hostile, cranky, or just curious, making this more than just a UI curiosity.

**Comment by crism** [comment]
This is not something inherent to grids; file and reviewer grids do not write to the database upon starting to add items. This appears to be unique to discussions (via `QueriesGridHandler`).

**Comment by crism** [comment]
The problem appears to stem from the `Que,ryForm` constructor, which calls `QueryDAO::insertObject()` at line 57 and `NoteDAO::insertObject()` at line 70.

Either this needs not to happen (and I can see a bunch of reasons why that might not work), or others’ views need to filter out transient stubs.

**Comment by asmecher** [comment]
Filtering out the stubs seems like a logical solution.

**Comment by crism** [comment]
That pull request can be acted on, but doesn’t quite close the issue—there remains the problem that, in a discussion with a non-null message, any other null messages are then displayed within the discussion widget.

**Comment by asmecher** [comment]
@crism, I'm not sure if I'm getting the issue right, but the goal here is to hide stub queries, and the PR looks like it'll do that. We don't use stubs for comments except the initial one, so I don't think we'll see issues beyond that. Unless I'm missing a case?

**Comment by crism** [comment]
Yeah, @asmecher—if user A starts to add a message to an existing conversation, and user B looks at the conversation before user A saves changes, user B will see a null message from user A in the thread. That should likewise be suppressed.

**Comment by asmecher** [comment]
Ah, yes, IIRC we're using stub notes too so that we can upload files to them. I'll merge this and leave the other to a separate PR, thanks!

**Comment by asmecher** [comment]
Merged!
