### ISSUE TITLE
[OMP] PHP errors triggered by catalog editing

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1158]
From #1127, against `HEAD`:

At some point while editing a catalog entry, an error message was logged:
```
PHP Warning:  Illegal offset type in .../lib/pkp/classes/submission/SubmissionKeywordDAO.inc.php on line 57, referer: .../index.php/test/catalog/book/3
```
followed by a series of errors like:
```
PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in .../lib/pkp/classes/submission/SubmissionKeywordDAO.inc.php on line 64, referer: .../index.php/test/catalog/book/3
```
Unsure yet what caused it.

**Comment by crism** [comment]
The line in question is in `SubmissionKeywordDAO::getKeywords()`:
```php
function getKeywords($submissionId, $locales) {

	$returner = array();
	foreach ($locales as $locale) {
		$returner[$locale] = array();  // line 57!
```
Presumably `$locales` is not being set correctly… tracing it down now.

**Comment by asmecher** [comment]
If this was on an old checkout, I may have already fixed it. Let me see if I can find the commit.

**Comment by asmecher** [comment]
Hmm, couldn't spot it, though I do recall fixing it.

**Comment by crism** [comment]
@asmecher, I haven’t seen the error in a little while, but I wasn’t sure what was causing it in the first place. Unfortunately, `getKeywords()` is a pretty popular method name, so it’s taking a while to figure out who called it.

**Comment by crism** [comment]
Possible calls:
 * `PKPSubmissionMetadataFormImplementation::initData()`
 * `ViewableFilePlugin::displaySubmissionFile()`

… and it looks like that’s it.

You did change the `ViewableFilePlugin` call in omp@b11ed902,  on 1 February, but `PKPSubmissionMetadataFormImplementation` hasn’t changed since 93ca8b57 in 2013.

**Comment by asmecher** [comment]
I couldn't spot anything that would cause the message in the current codebase, beyond something like an incompletely configured set of language settings. I'll keep an eye out for this, but I'd lean towards closing it unless you're able to reproduce the message with a fresh checkout.

**Comment by crism** [comment]
I’m unable to reproduce this now, so I’ll close it.
