### ISSUE TITLE
[OMP] Cover thumbnail size generates PHP Warning

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1159]
It looks like [the call to CatalogEntryCatalogMetadataForm::_buildSurrogateImage()](https://github.com/pkp/omp/blob/master/controllers/tab/catalogEntry/form/CatalogEntryCatalogMetadataForm.inc.php#L269) is missing [a couple of arguments](https://github.com/pkp/omp/blob/master/controllers/tab/catalogEntry/form/CatalogEntryCatalogMetadataForm.inc.php#L379).

I took a quick look and probably the arguments can be made optional. But best if someone familiar with the code takes a look.

Here are the PHP Warnings:

```
[Wed Feb 17 14:54:06.402254 2016] [:error] [pid 23589] [client 192.168.0.8:56649] PHP Warning:  Missing argument 4 for CatalogEntryCatalogMetadataForm::_buildSurrogateImage(), called in /var/www/html/omp/controllers/tab/catalogEntry/form/CatalogEntryCatalogMetadataForm.inc.php on line 269 and defined in /var/www/html/omp/controllers/tab/catalogEntry/form/CatalogEntryCatalogMetadataForm.inc.php on line 379, referer: http://192.168.0.8/omp/index.php/publicknowledge/workflow/index/5/5
[Wed Feb 17 14:54:06.402303 2016] [:error] [pid 23589] [client 192.168.0.8:56649] PHP Warning:  Missing argument 5 for CatalogEntryCatalogMetadataForm::_buildSurrogateImage(), called in /var/www/html/omp/controllers/tab/catalogEntry/form/CatalogEntryCatalogMetadataForm.inc.php on line 269 and defined in /var/www/html/omp/controllers/tab/catalogEntry/form/CatalogEntryCatalogMetadataForm.inc.php on line 379, referer: http://192.168.0.8/omp/index.php/publicknowledge/workflow/index/5/5

```

**Comment by bozana** [comment]
Thanks @NateWr! I think I introduced it :-P I'll take a look... :-)

**Comment by bozana** [comment]
@NateWr, could you maybe tell me what is the catalog image and what the thumbnail image i.e. I know the thumbnail image -- I changed that -- but I think I don't know what are those catalog images for :-\

**Comment by bozana** [comment]
If you don't know out of your head (or how do you say it :-D) no problem, I'll take a look...

**Comment by NateWr** [comment]
Yeah I don't know, sorry! But looking at the code it looks like there is a defined max size allowed that's used for the "catalog image".  But the thumbnail size is set by options under Settings > Website > Appearance.

My guess is that it's a larger image saved so that if the thumbnail size changes a new thumbnail can be generated from a higher-res copy.

**Comment by bozana** [comment]
Ah I think I know -- this was the image that was a little bit bigger than thumbnails, used on the book page -- they had always the same size. But I think we don't need that image any more, right? I think also on the book page we are displaying/using the thumbnail, right? There is then also the original cover image saved, so that new thumbnails can be calculated, if necessary...

**Comment by NateWr** [comment]
I don't know, probably best to check with @asmecher, but sounds logical to me.

**Comment by bozana** [comment]
OK, I'll wait for @asmecher :-)
But, concerning design: you are using the same image (size) for the catalog listing and the book page, right? I mean this is meant to be so?

**Comment by NateWr** [comment]
Yeah I am. Although I do think some people might want to change that in a theme.

**Comment by bozana** [comment]
OK, I think I could then either
-- implement the resizing option for those 'catalog' (the name feels a little bit wrong) images too, at the moment in the appearance settings, similar to the thumbnails, and we would then use them on the book page
or 
-- remove them for now and eventually consider the change above later
:-)

**Comment by NateWr** [comment]
I don't think I'd ever want to add two sets of options for thumbnail sizes in core. Ideally, this kind of thing would eventually be handled by themes. See #787 

I don't really have any use for the secondary size at the moment so I'd say whatever Alec thinks will work for now.

**Comment by bozana** [comment]
Yes, OK, then it would probably be best to remove it for now... lets see what Alec think... Thanks!

**Comment by asmecher** [comment]
I'm fine to remove it for now.

**Comment by bozana** [comment]
OK

**Comment by bozana** [comment]
@asmecher, I removed the code (s. above), but what would be best way to consider it for the upgrade? -- those old/earlier used "catalog.png" images should be deleted, I think. Should I then implement a function in the Upgrade.inc.php that does that?

**Comment by asmecher** [comment]
@bozana, I think users upgrading from 2.x to 3.x can expect to work on their presentation, perhaps more than any other element, so I don't mind if presentation-related settings don't migrate. I'd suggest leaving the old settings in the database if they aren't used in the new code. If the settings are used in the new code but have changed in meaning, then I'd suggest removing the old setting in the upgrade process (leaving the file in place).

**Comment by bozana** [comment]
@asmecher, this is for OMP 1.2 :-) And there are no settings, just files, the images, that were used on the book pages and are not going to be used any more.

**Comment by asmecher** [comment]
Ah, OK. Hmm... I would suggest not deleting the files. Better to potentially leave unused images around than to remove them without giving the site administrator a warning first.

**Comment by bozana** [comment]
Maybe then one more question :-) If one uploads a new cover page, the thumbnail will be replaced, but the old catalog.png stays. Should I then check in the code if there is catalog.png when uploading a cover, then remove it? Or just leave it, although it will in this case be different than the new thumbnail image?

**Comment by asmecher** [comment]
The `catalog.png` file will no longer be used, even if it's present, correct? If that's right, then I'd suggest just leaving it. I'm not fond of maintaining active code for the sake of legacy data; the chances of that code getting obsolete or buggy without detection are higher than the utility it provides.

**Comment by bozana** [comment]
OK, thanks a lot, everything clear now :-)

**Comment by asmecher** [comment]
Merged, thanks!
