### ISSUE TITLE
 Sorting of announcements by date_posted

### ISSUE THREAD

**Issue by hermannschwaerzlerUIBK** [pkp/pkp-lib#1161]
Hi everybody,
this is about OJS 2.4.x. There is this rather oldish bug about allowing for sorting of announcements:
https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=4259
It is marked as fixed but the respective commit https://github.com/pkp/pkp-lib/commit/7d6ac60109271220f6808abf79f0e2ced49ba30e does only allow the **entering and changing** of the "Published" date (saved as "date_posted" to the DB).

The original request that this date should be used as the sorting criterion is still not fulfilled. 
Announcements are still sorted by "announcement_id" in the relevant functions 
`PKPAnnouncementDAO::getAnnouncementsNotExpiredByAssocId`
and
`PKPAnnouncementDAO::getNumAnnouncementsNotExpiredByAssocId`

I think the `ORDER BY` clauses in those functions should be changed to
`ORDER BY date_posted`, right?

Greetings
Hermann

**Comment by asmecher** [comment]
It looks like you're right, @hermannschwaerzlerUIBK -- please try applying https://github.com/pkp/pkp-lib/commit/77a8e8e56226e100dc191b1f77f1a4f02a14ee96 in your lib/pkp subdirectory and let me know if that solves the issue.

**Comment by hermannschwaerzlerUIBK** [comment]
Hello Alec,
yes your patch does indeed solve the issue. Thanks a lot!
Greetings
Hermann

**Comment by asmecher** [comment]
Thanks for confirming!
