### ISSUE TITLE
[OJS] Article Component needs illustration

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1165]
When submitting to OJS, the article components are very heavily science-oriented; there is no option for an illustration or even a figure.

**Comment by asmecher** [comment]
The OJS default list is in https://github.com/pkp/ojs/blob/master/registry/genres.xml -- you might want to check out the defaults we have for OMP if you want to propose an addition that matches? https://github.com/pkp/omp/blob/master/registry/genres.xml

**Comment by crism** [comment]
Ah… multimedia, image, and style have been added since the 3.0α release, which we’re testing. I think the first two of those would suffice. `<emily_litella>`Never mind.`</emily_litella>`
