### ISSUE TITLE
[OMP] reviewer elapsed time has wrong units

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1167]
Against `HEAD`: When looking at the list of reviewers, the average review time seemed far too large. Indeed, running the query directly shows:

`date_completed`|`date_notified`|`date_completed - date_notified`
----------------|---------------|--------------
`2016-02-03 15:15:27`|`2016-02-03 15:13:38`|`189`
`2016-02-08 12:01:35`|`2016-02-08 11:58:45`|`4290`
`2016-01-21 10:59:38`|`2016-01-20 14:54:51`|`960487`
`2016-02-08 11:38:46`|`2016-02-08 11:35:47`|`299`
`2016-02-19 12:24:00`|`2016-02-19 12:22:34`|`166`
`2016-01-20 14:41:11`|`2016-01-20 14:32:31`|`880`

They’re not seconds, but I’m not sure what they actually are. I think `DATEDIFF()` is what is wanted here; is that widely enough supported?

**Comment by asmecher** [comment]
@crism, this seems to work with both MySQL and PostgreSQL -- sadly no SQL standard solution seems available. Feedback welcome as always. Thanks for reporting!
