### ISSUE TITLE
Unauthorized access to submission library file after upload

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1169]
When I upload a file to the submission library (not the overall document library but the submission-specific one), I am not able to access that file. I get the following error:

```
[Mon Feb 22 12:22:17.514602 2016] [:error] [pid 3759] [client 192.168.0.8:43351] ojs2: Unauthorized access to library file., referer: http://192.168.0.8/ojs/index.php/publicknowledge/workflow/index/10/1
```

File uploaded as admin and attempted to access it as admin as well. Tested on latest OJS master but problem effects OMP too.

**Comment by asmecher** [comment]
The attached patch should fix it, @NateWr. The way we're doing access control in the file API handler is a little ugly but I'm content not to crack it open yet.
