### ISSUE TITLE
Section title is hidden

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1172]
The section title is in the mark-up but is hidden from presentation. See e.g.:
http://journals.sfu.ca/uiux/index.php/publicknowledge/issue/view/1

The `<h2>` element contains the section title, but it's never shown. All articles appear to be in an "Articles" section, rather than "Articles", "Reviews", etc.

**Comment by NateWr** [comment]
Note for later: change `.obj_issue_toc .sections` --> `.obj_issue_toc .section`.

**Comment by NateWr** [comment]
PR: https://github.com/pkp/ojs/pull/797

**Comment by asmecher** [comment]
Thanks, @NateWr!
