### ISSUE TITLE
[OJS] Add a block to the PLN plugin

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#1173]
The PLN plugin needs a block to advertise that a journal is preserved in the PLN.

See pkp/ojs#742

/cc: @asmecher who requested the issue.

**Comment by asmecher** [comment]
I don't think that was me...

**Comment by ubermichael** [comment]
I think it was Alec: https://github.com/pkp/ojs/pull/742#issuecomment-183129068

**Comment by asmecher** [comment]
Ah, I thought you meant requesting the feature, not requesting the issue.
