### ISSUE TITLE
[OJS] journal sections messed up in publication

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1174]
Against `HEAD`:

I renamed the Articles section of my toy journal, then added a second “Reviews” section. I submitted an article to each section, and published an issue with them. The dashboard shows the TOC for the issue as having one article in each section; however, the reader’s view of the journal puts both articles into “Reviews.”

**Comment by asmecher** [comment]
Beat you to it!
https://github.com/pkp/pkp-lib/issues/1172
