### ISSUE TITLE
Dynamic loading of locale files breaks Translator plugin

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1175]
The new Counter plugin dynamically loads locale files to support drop-in addition of new COUNTER reports.
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/reports/counter/CounterReportPlugin.inc.php#L40-L51

The Translator plugin assumes that a call to a plugin's `getLocaleFilename()` will return an identically ordered array of locale files, regardless of which locale is selected.

As a result, if a plugin returns a variant set of locale files (ala Counter) the Translator plugin returns an unhelpful error "The locale file '' is missing or unreadable."

Perhaps all plugins' `getLocaleFilename()` should return an identically ordered array of locale files, based on the reference locale, regardless of whether the locale files exist in the selected locale.  More likely, the Translator plugin should allow for variant locale files lists.

**Comment by asmecher** [comment]
Thanks, @ctgraham. Do you mind forward-porting this to the master branch? If that's more than you care to bite off, that's fine with me too.

**Comment by ctgraham** [comment]
@asmecher, that would be a good excuse to slide into the master branch code... I'm unconvinced, however, of the soundness of my current strategy (`str_replace`) in general.  Right now, I'm mulling the getLocaleFilename() returning a hash instead of a simple array.  Or maybe there should be a different method to return all prospective locale filenames, regardless of whether they exist in the current locale?  To support this kind of functionality, the plugin should be able to describe both the available and unavailable locale files in some way.

**Comment by asmecher** [comment]
The translator plugin is special-purpose enough, and so rarely enabled, that I don't mind if we make an assumption here. If that makes you shudder, feel free to tinker around a little.

The `registry/locales.xml` descriptor (accessible via AppLocale/PKPLocale) describes all the necessary `xx_YY` codes; `Applicatoin::makeComponentMap` should give you all the filenames you need.

**Comment by asmecher** [comment]
Making this a WONTFIX; Weblate has made the translation plugin obsolete.
