### ISSUE TITLE
Issues with reviewer grid and associated modals

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1178]
While working on #758 I came across a few issues, some of which probably need to get solved for OMP 1.2.

- [x] A review can not be confirmed unless a file is uploaded.
- [x] ~~In the code there are references to a `declined` state, but this never actually gets used.~~ 
- [ ] Editors can not set or adjust the recommendation. It seems like this would be important in cases where an editor uploads a file instead of the reviewer filling out the review form.
- [x] The "Go Back" button in the review wizard doesn't work.

**Comment by NateWr** [comment]
The declined state was implemented in #1177

**Comment by bozana** [comment]
@NateWr, maybe just a comment on the first point above: either comments or file have to be there for the confirmation...

**Comment by NateWr** [comment]
@bozana In my tests having comments did not prevent the missing file notification from appearing and blocking confirmation.

**Comment by NateWr** [comment]
Example

![selection_161](https://cloud.githubusercontent.com/assets/2306629/13252668/fa1ffc34-da2f-11e5-90bf-675598389c1e.png)

**Comment by bozana** [comment]
@NateWr, oh, I'll have a look... :-)

**Comment by NateWr** [comment]
Thanks!

**Comment by bozana** [comment]
@NateWr, regarding the remained issue here i.e. recommendation set up by an editor: do you think that an editor should be able to choose a recommendation instead of a reviewer (e.g. only if there is no reviewer recommendation) or should an editor also be able to change the existing reviewer recommendation?

**Comment by bozana** [comment]
@asmecher, I've just realized, that when I click on the "Go Back" button a new tab is opened, is there a possibility/a parameter, that I could use to tell the action to stay in the same window? THANKS!!!

**Comment by NateWr** [comment]
@bozana I'm in favor of allowing the editor to do whatever (for instance, maybe they had a chat with the reviewer directly and the reviewer said "yeah ok switch my recommendation). But obviously it would be good if this change is logged somewhere. Do we have a reviewer history log anywhere that these decisions are recorded?

**Comment by asmecher** [comment]
@bozana:
> is there a possibility/a parameter, that I could use to tell the action to stay in the same window? THANKS!!!

I think you'd probably need to do this yourself in a JS handler -- something like...
    $element.tabs({active: 1});

**Comment by bozana** [comment]
@NateWr, I'll take a look... THANKS!!!
@asmecher, I think it should be solved in another way ;-) -- I made PRs for that... THANKS!!!

**Comment by bozana** [comment]
@NateWr, maybe we can then change the milestone to OJS 3.0 because the remain issue about review recommendations is only relevant for OJS, right? -- There are no recommendations in OMP, right?

**Comment by NateWr** [comment]
@bozana, I think you're right. I haven't seen recommendations in my OMP testing.

**Comment by bozana** [comment]
Hi @NateWr and @asmecher, I am just working on the last item of this issue -- to allow editors to select and overwrite the reviewer recommendation. Currently there is no place in the DB to follow the history of the reviewer recommendations. Thus, do we want/need to follow the recommendation history and create a new DB table review_recommendations containing all the necessary information or do you think that it is not so important and an entry in the the event log could/would be sufficient?

**Comment by bozana** [comment]
The solution looks now like this:
a) when there are no reviewer comments/recommendations yet:
![reviewerrecommendationbyeditor1](https://cloud.githubusercontent.com/assets/378421/14498871/66a55f3c-019c-11e6-9034-424d3822eca8.png)

b) when the reviewer comments/recommendations are there:
![reviewerrecommendationbyeditor2](https://cloud.githubusercontent.com/assets/378421/14498880/6e63eaa4-019c-11e6-9f32-b4b723ef83e3.png)


I.e. I left the status information about the current recommendation at the top (s. the second image).
The recommendation adjustment part is at the bottom, because a reviewer file is needed for the final/form confirmation (s. the first image).
OK so?

**Comment by asmecher** [comment]
Yes, @bozana, that looks fine. I'd suggest we just use the event log to record changes.

**Comment by bozana** [comment]
The PR to enable editors to set or adjust the reviewer recommendation:
pkp-lib: https://github.com/pkp/pkp-lib/pull/1384
ojs: https://github.com/pkp/ojs/pull/822

At the moment the event is logged and so the change recorded. There are e.g. following information: date, editor ID, reviewer ID, submission ID, but there is no information at the moment what is/was the recommendation. Eventually we could use the event log DB table for that too -- to provide the recommendation parameter that will then be logged in the event_log_settings table? Those event logs are not displayed, so the users will not know it, but maybe for a sake of proof...

**Comment by asmecher** [comment]
The event logs can be viewed in Editorial History > History. (These need review -- I can see a few untranslated keys on mine already -- but that's outside the scope of this entry.) Can you double-check to see that the log entry corresponding to this change is viewable there?

**Comment by bozana** [comment]
Yes, I see them :-) THANKS!!!

(What do you mean with logging issue left on this one? :-))

**Comment by asmecher** [comment]
Just checking whether the editor filling in/changing a recommendation gets logged properly.

**Comment by NateWr** [comment]
Looking good @bozana. Once Alec signs off on this, can you assign this issue back to me? I want to tinker with the UX on this a bit, but I'm not sure what I want to do with it yet.

**Comment by bozana** [comment]
Hi @NateWr, I believe @asmecher finished with this, so I will assign it to you :-)

**Comment by NateWr** [comment]
Nevermind, it looks and works great. I'll leave it as is. :+1:
