### ISSUE TITLE
[OJS] Exclude bots from session management

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#1179]
Unnecessary db updates and filling-up of the sessions table.

**Comment by asmecher** [comment]
@mfelczak, possibly (and I just cross-linked with #3624, which might have overlapping concerns), but have you considered slowing the rate of indexing using `robots.txt` (for well-behaved bots)?

**Comment by mfelczak** [comment]
Thanks @asmecher, we've added a crawl delay for the time being.

**Comment by mfelczak** [comment]
This looks to be implemented as part of https://github.com/pkp/ojs/pull/2010
