### ISSUE TITLE
make the proxy use for web serviece requests optional

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1183]
S. http://forum.pkp.sfu.ca/t/lucene-plugin-not-working/8338

a) make generally the proxy use for web service requests optional
b) add the option whether to use the proxy settings for Solr web service requests.

**Comment by asmecher** [comment]
Thanks, @bozana 

Merged pulls:
- https://github.com/pkp/pkp-lib/pull/1184
- https://github.com/pkp/ojs/pull/761

Could you cherry-pick this to ojs-dev-2_4, and forward port to master?

**Comment by bozana** [comment]
Thanks @asmecher. Done... :-)
