### ISSUE TITLE
consider proxy settings for external feed plugin

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1187]
S. forum.pkp.sfu.ca/t/lucene-plugin-not-working/8338

**Comment by asmecher** [comment]
@bozana, I've kind of lost track of all the PRs for this. Go ahead and merge what's needed for the other branches/apps; no need to review this again. Thanks!

**Comment by bozana** [comment]
I'll wait a little bit with merging this PR, if the user in the forum could test the patch... then I will port it to other branches too...
