### ISSUE TITLE
Fatal error: Call to undefined method SectionEditorSubmission::setCopyrightHolder() in /home/user/journal/classes/submission/form/MetadataForm.inc.php on line 451

### ISSUE THREAD

**Issue by molavy** [pkp/pkp-lib#1188]
when i want edit article metadata from archive 
on submit article edit form return this error
Fatal error: Call to undefined method SectionEditorSubmission::setCopyrightHolder() in /home/user/journal/classes/submission/form/MetadataForm.inc.php on line 451
ojs version  OJS 2.4.4.1

**Comment by asmecher** [comment]
@molavy, can you pursue this on the forum rather than filing an issue? http://forum.pkp.sfu.ca/
