### ISSUE TITLE
Document Composer requirement for OJS 3.x

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1192]
The need to initialize third-party modules via Composer should be documented in the 3.x README.md.  Should it also be documented in the 3.x docs/README?  When OJS 3.0 is packaged, will it include third party modules in the download, or require that a `composer.phar update` be run?

**Comment by asmecher** [comment]
I've added the same snippet from the OMP README.md to the OJS README.md.

For the distribution, I'd imagine we'll continue to build and ship everything in the tarball.

For casual git checkouts, I've increasingly been recommending the Vagrant configuration:

https://github.com/pkp/vagrant

This allows a one-liner to spin up a reliable installation from git master without having to worry about system requirements etc.
