### ISSUE TITLE
[OJS] article galley remains published and accessible after un-approval

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1195]
Against `HEAD`:

I have an issue already published, with two articles. I added a new galley to one of the articles, uploaded a file, and approved the file and galley. The file was then accessible through the published issue.

I changed my mind, and marked the galley as unapproved. The file was still visible and accessible through the front end. I unapproved the file itself, too; still accessible. I’ve purged the data caches and template cache, to no effect.

**Comment by crism** [comment]
It looks like the query in `ArticleGalleyDAO::getGalleysBySetting()` is relevant here; my test installation has a completely empty `submission_galley_settings`, which seems odd.

**Comment by crism** [comment]
Nope, I was wrong about the source of the problem. It’s much simpler. The template `article_details.tpl` asks for `$article->getGalleys()`, which simply returns all the galleys of an article.

I’m not sure the right design approach here (@asmecher?)—would a separate accessor `getApprovedGalleys()` be appropriate, or an optional parameter to `getGalleys()`?

**Comment by crism** [comment]
Or…we could ask each galley if it’s been approved, in the handler. I think that’s probably the best approach.

**Comment by crism** [comment]
We need a combination. The templates make Boolean decisions based on `$article->getGalleys()`; it would be very useful to have a single method that returns an empty list if no galleys are approved, so I suggest `$article->getApprovedGalleys()`. That would (on `PublishedArticle`) call `getGalleys()`, then filter based on `getIsApproved()`.

The next question is, what if a galley is approved, but has no approved files? I think the filter had better handle that case, as well.

**Comment by asmecher** [comment]
@NateWr, FYI, in case it's also relevant to your OMP 1.2 front-end review.

**Comment by NateWr** [comment]
Now that we've simplified the galley management process, there's no approvals process. Closing.
