### ISSUE TITLE
File upload for reviewer

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1198]
I believe since recent changes on the file uploader, the file upload for reviewer is not working any more. This is what I see:
![fileuploadforreviewer](https://cloud.githubusercontent.com/assets/378421/13351794/800b2548-dc89-11e5-9a52-d8dc2c8f21c8.png)

Any idea?

**Comment by asmecher** [comment]
@bozana, Nate replaced the file uploader with a better implementation. Make sure you're on a recent checkout of the app and pkp-lib, then...

    cd lib/pkp
    composer.phar update
    cd ../..
    rm cache/*.css cache/t_compile/*.php

Let me know if that doesn't do it.

**Comment by bozana** [comment]
@asmecher, thanks!!! This unfortunately haven't solved the problem :-( I can upload a file for Revisions for example, but for Review Files or Reviewers I cannot :-( Is this possible for you?

**Comment by asmecher** [comment]
@NateWr, could you take a look?

**Comment by NateWr** [comment]
Hi @bozana, can you give any more details about the context when you get this problem?

I just tried to reproduce this but didn't have any problems. I'm probably not in the right place. Here's what I did:

1. Login as an internal reviewer and go to the Submissions page.
2. Click on Internal Review for a submission assigned to me.
3. Go to Step 3 (Download & Review), find the Reviewer Files grid at the bottom and click Upload File.
4. Follow the steps in the modal to upload the file.

I didn't see any use role select box like your screenshot shows. Am I in the right place? Do I need a particular user role maybe? Some other setting that's causing that to appear?

**Comment by bozana** [comment]
Hi @NateWr. Ah, I do the same as you, but in the 4. step I don't see this place to upload a file :-O I see the upload file modal and the first tab "Upload Submission" there, but there is no file upload area or button :-(

**Comment by bozana** [comment]
Aaaa... For some reason has this div display: none; in my CSS...

**Comment by NateWr** [comment]
@bozana Can you check the form controller options for the form and add them here?

![selection_166](https://cloud.githubusercontent.com/assets/2306629/13459664/33173334-e06d-11e5-80e7-9ab0ea6cfa63.png)

The `$.pkp.controllers.wizard.fileUpload.form.FileUploadFormHandle` hides the uploader by default, and then displays it when the genre or file ID selectors are set up properly (if none are present, it should display it when initialized):

https://github.com/pkp/pkp-lib/blob/master/js/controllers/wizard/fileUpload/form/FileUploadFormHandler.js#L317-L333

I suspect that your current user has multiple roles and this is causing some change to the configuration I have not seen. I don't get any dropdown about "Upload this file in my role as..." so maybe that's throwing things off -- though looking at the code the display logic should be entirely ignorant of this field.

**Comment by bozana** [comment]
Ah, I build the JS (lib/pkp/tools/buildjs.sh) anew and now it is working :-) Thus this mean that the right/currant pkp.min.js was not committed or that I should do this alone however or ...?

**Comment by NateWr** [comment]
I don't know! I've never compiled the `pkp.min.js` file so never committed it. Maybe I should? @asmecher

**Comment by bozana** [comment]
I think it is both possible, to use minified and non-minified JS -- it is a config option -- and apparently I use the minified JS... :-)

**Comment by asmecher** [comment]
Leave the minification turned off, and just prior to release I'll build a proper copy. I don't tend to maintain it during development phases.

**Comment by bozana** [comment]
OK :-)
