### ISSUE TITLE
Add profile image upload to user management form

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1199]
See http://forum.pkp.sfu.ca/t/profile-image-upload/8817

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by bozana** [comment]
@asmecher, would this be something to consider for OJS 3.x?

**Comment by asmecher** [comment]
Yes, certainly for the master branch but I'm not sure what release to target yet. Could you file a new issue to review/correct the public profile more broadly?
