### ISSUE TITLE
improve the text for the new review round

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1201]

**Comment by bozana** [comment]
When creating a new review round (in OMP) the following text appears: "You are about to create a new review round for this submission. Files that have not been used in other review rounds are listed below. By default, the reviewers from the previous review round have been selected to participate in this new review round.". 
The reviewers from the previous review round are not selected, thus at least the last sentence is wrong. 
"It would be good to follow OJS 2.x's example here, as it seems to have kept people reasonably satisfied." (s. https://github.com/pkp/pkp-lib/issues/1149#issuecomment-189514437)

**Comment by bozana** [comment]
@asmecher, I've checked it in OJS 2.4.x and there the reviewers from the previous review round are automatically selected. The review request e-mail still has to be sent by the editor. I am not sure if we could/would like do this here in master too -- automatically selecting the reviewers from the previous round -- because the reviewer selection and the review request e-mail are both in one step in master -- differently to the OJS 2.4.x. What do you think? THANKS!!!

**Comment by asmecher** [comment]
I don't think we want to assign & notify reviewers from previous rounds automatically. What about adding a filter option to the reviewer search that lists reviewers assigned to previous rounds? That would make re-selection of existing reviewers easy.

**Comment by bozana** [comment]
In the PR above I added the possibility to filter the reviewers from the submission's previous review rounds, and I removed the last sentence from the new review round text.
Here how the new filter option looks like:

![previousroundsfilter](https://cloud.githubusercontent.com/assets/378421/13892658/29076d02-ed59-11e5-9c84-a71129abc0c8.png)

**Comment by asmecher** [comment]
This looks great -- that's a good solution to a slightly tricky problem. Just one small fix on the PR.

**Comment by bozana** [comment]
@asmecher, I've fixed the typo and SQL so this can be merged too, I believe.

**Comment by asmecher** [comment]
Great -- merged, thanks!
