### ISSUE TITLE
[OJS] Limit author fees to submission stage and hide for declined/archived submissions

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#1202]
Author fee options and links (e.g. fast-track review, publication fee) should not be visible/available to authors once a submission has been declined or archived.

**Comment by mfelczak** [comment]
Also fixes bug where the submission and fast track fees should only be displayed during initial submission/review and the publication fee should only be displayed post-review once the article has been accepted.

**Comment by mfelczak** [comment]
Updated issue description and commit message.

**Comment by asmecher** [comment]
I guess this cuts off a potential revenue source -- but agreed :)
