### ISSUE TITLE
[OJS] Empty mime magic on remote url galleys with CrossRef export plugin

### ISSUE THREAD

**Issue by alonsoj** [pkp/pkp-lib#1204]
When exporting an issue or article with remote galleys to XML with the CrossRef Export plugin the mime type of these galleys is empty
`<resource mime_type=""> `

**Comment by bozana** [comment]
@alonsoj, thanks a lot!
@ctgraham and @jmacgreg, shall we then ignore the attribute mime_type for the remote galley?

**Comment by ctgraham** [comment]
It turns out I don't have a journal with published remote galleys, but removing the attribute in this case makes sense to me.  Sorry I can't test it with some real data.

**Comment by jmacgreg** [comment]
Yep, agreed here.

**Comment by asmecher** [comment]
Thanks, @bozana!
