### ISSUE TITLE
[UI] Revisions file grid needs improvements for clarity

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1208]
Icons and data are unclear in the revisions grid on the reviews page.

Related: #1154 #1144

**Comment by NateWr** [comment]
From alec:

> Signoffs used to be used pretty broadly, e.g. in the Copyediting and Layout Editing areas, but those were supplanted by the discussions tool. I think the review area is the last place they're used, and I'd be happy to see them go.

So this can be reverted to a regular file grid.

**Comment by NateWr** [comment]
I've converted the revisions grid over to a basic `FileListGridHandler`.

PR: https://github.com/pkp/pkp-lib/pull/1227

However, I'm a bit confused about the permissions. I only added the author role to the `fetchGrid` and `fetchRow` operations:

https://github.com/NateWr/pkp-lib/commit/09abd92cbaca3bbc7ce9806086cd5742cb7d8bd5#diff-5406fc0068e2f121d56a19f1765f9545R32

But they can still add/edit/delete revision files. That seems like the way we want it, I just don't understand why that's the case with this code. Am I missing something? 

I don't want to introduce a bug here so can you double-check and test before merging?

**Comment by NateWr** [comment]
I added a couple commits to this PR which tidy up the style of the notification messages in the author dashboard.

- Style a list of notifications similar to the grid.
- Don't show a full message on the author dashboard (only available via click).

![pkp-review-author-notifications](https://cloud.githubusercontent.com/assets/2306629/13572722/afb32100-e473-11e5-911f-97f9f0461b7e.png)

- Clean up the style of the messages a little bit.

![pkp-review-author-notifications-modal](https://cloud.githubusercontent.com/assets/2306629/13572723/afb39950-e473-11e5-8839-d7826f6d2e52.png)

**Comment by asmecher** [comment]
Authors need to be able to upload files, but shouldn't be able to edit/delete files that aren't theirs. We'll talk about this in a sec, and I'll check before merging.

**Comment by asmecher** [comment]
Pulls:

https://github.com/pkp/pkp-lib/pull/1266
https://github.com/pkp/omp/pull/240/files
https://github.com/pkp/ojs/pull/791

**Comment by asmecher** [comment]
Merged. Thanks, @NateWr -- several KLOCs removed.
