### ISSUE TITLE
increase the size of the URL database fields

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1209]
Currently the URL database fields are 255 long. They should be changed to 2047.

**Comment by asmecher** [comment]
@bozana, I merged 5 PRs for this -- I think that's all of them. (They're easier to track if you drop links in to the issue, BTW.)

**Comment by bozana** [comment]
Thanks @asmecher! 5 is correct. OK, I will then always insert the links to PRs on issue pages! Sorry :-\

**Comment by bozana** [comment]
The travis test for ojs-dev-2_4 failed because of this DB error: "Specified key was too long; max key length is 767 bytes". The URL column in the table referrals is used for the index, thus apparently it cannot be 2047 long, thus I will undo the change. The new PR is coming...
