### ISSUE TITLE
Check for outdated language

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1212]
A reminder to do a quick click-through scan for help text and other language which might need to be updated or removed.

Example:

![selection_147](https://cloud.githubusercontent.com/assets/2306629/13464217/f7e42c16-e087-11e5-8428-07cc1b169df2.png)

**Comment by beghelli** [comment]
Just adding here to keep track: dashboard is not used anymore, so we should check for that also.

**Comment by NateWr** [comment]
I'm making some more sweeping changes to tidy up forms where I think we can nab some easy wins for clarity. Posting here for second-opinion if anything looks off.

![pkp-catalog-entry-monograph](https://cloud.githubusercontent.com/assets/2306629/13577148/f1fadb74-e488-11e5-8df2-c54ce0560f4d.png)

**Comment by NateWr** [comment]
I'm going to break it up into different PRs as I go to prevent lots of merge conflicts:

https://github.com/pkp/pkp-lib/pull/1230
https://github.com/pkp/omp/pull/230
https://github.com/pkp/ojs/pull/780

These PRs remove help text on the workflow stages and tidies up the catalog entry modal.

**Comment by asmecher** [comment]
Merged/cherry-picked the above 3, and will watch for Travis complaints.

**Comment by NateWr** [comment]
Does anyone know what **Restricted** means here in the Series form:

![pkp-series-restricted](https://cloud.githubusercontent.com/assets/2306629/13602090/53bbb47a-e52c-11e5-8bd7-0b8c02159af7.png)

**Comment by asmecher** [comment]
@NateWr, when that's checked, the series will not be available during the submission process for new submissions. That's a less than perfectly clear label, I'd say.

**Comment by NateWr** [comment]
Thanks @asmecher. Got that fixed along with a bunch of string changes for the Press > Settings page.

The following PRs tidy up the Press > Settings forms. With clever wording, I was able to merge a bunch of strings kept in `ojs` and `omp` into `pkp-lib` as well.

https://github.com/pkp/pkp-lib/pull/1241
https://github.com/pkp/ojs/pull/783
https://github.com/pkp/omp/pull/231

I haven't done a careful look at OJS but these PRs should bring it in line with the changes done to OMP so at least we won't have to duplicate a bunch of work later.

**Comment by asmecher** [comment]
Thanks, @NateWr, merged. I'll watch for Travis to see what happens -- it's having some weird (probably load-related) behavior today.

**Comment by asmecher** [comment]
(I'll leave this issue open in case you're still working on something for 1.2.)

**Comment by NateWr** [comment]
Yeah still got more to look over...

**Comment by NateWr** [comment]
What does it mean if the "Accept a Competing Interest Statement" checkbox is checked? Does checking this add a field to the submission form or something?

![accept-ci-statement](https://cloud.githubusercontent.com/assets/2306629/13645868/e1a38e54-e624-11e5-9f45-e8d616cc3f0d.png)

**Comment by asmecher** [comment]
When checked, Reviewers will be asked for a competing interest statement during the peer review.

**Comment by NateWr** [comment]
:+1:

**Comment by NateWr** [comment]
Took a quick look at the email template descriptions and they look good (didn't look at templates themselves). Questions about:

I was unable to find this **Notify Users** link. Any idea where I can find it to update the language?

![email-template-notify-users](https://cloud.githubusercontent.com/assets/2306629/13665765/ec82a540-e6a5-11e5-8bd7-623b94f6b7eb.png)

---

These two reference options in Settings > Workflow > Review which I couldn't see:

![email-template-review-request-attached](https://cloud.githubusercontent.com/assets/2306629/13665763/ec7fb9ac-e6a5-11e5-90a0-106e126ccb9a.png)
![email-template-review-request-one-click](https://cloud.githubusercontent.com/assets/2306629/13665764/ec809d2c-e6a5-11e5-8120-7b924c1f636a.png)

**Comment by NateWr** [comment]
New round of PRs which cover the appearance and review settings pages:

https://github.com/pkp/pkp-lib/pull/1252
https://github.com/pkp/ojs/pull/788
https://github.com/pkp/omp/pull/236

(still more to do)

**Comment by asmecher** [comment]
Merged the above three, thanks.

The "Notify Users" link is an OJS 2.x feature permitting managers to send out mass emails. It's not implemented in OJS 3.0 yet, and may not make the 3.0 release, but best to leave that in place for the moment, I think. We can use the translation later, and upgrading users will continue to have existing email templates in place until we do revamp that feature.

The references to the attachment-based review: we used to have two modes for peer review, either having the review document attached to the email, or asking them to download it via the website. I think I'd like to try dropping the attachment-based review feature, as it leads to a lot of forking of e.g .email templates. So remove those references for now, and maybe file a clean-up issue for OJS 3.1 to revisit that feature and either implement it for 3.x or remove it fully.

**Comment by NateWr** [comment]
Thanks @asmecher. So is the "Notify Users" feature ever planned for OMP or could it be removed from there?

**Comment by NateWr** [comment]
So I'll remove the email references for review actions in attachment mode. Can I also remove references to "one-click" mode?

**Comment by NateWr** [comment]
What's the difference between these two options in Settings > Distribution > Permissions?

![selection_005](https://cloud.githubusercontent.com/assets/2306629/13742844/2e71087e-e9d6-11e5-9f97-c9ffaa12cf5f.png)

**Comment by NateWr** [comment]
Should this be a tinymce field or should I remove the <br> tags from the default message?

![selection_009](https://cloud.githubusercontent.com/assets/2306629/13752102/114031d8-ea05-11e5-9955-42f8da8d80fd.png)

**Comment by NateWr** [comment]
New round of PRs which cover final settings/tools/admin pages as well as the submission, review and author workflow.

https://github.com/pkp/pkp-lib/pull/1272
https://github.com/pkp/omp/pull/241
https://github.com/pkp/ojs/pull/790

The only thing left after this is the catalog page which I'll hit after Bruno's revamp.

**Comment by asmecher** [comment]
From [this comment](https://github.com/pkp/pkp-lib/issues/1212#issuecomment-196407919): 
> Should this be a tinymce field or should I remove the tags from the default message?

All emails should now be TinyMCE-enabled. Not sure what's happening there but it could use a look.

From [this comment](https://github.com/pkp/pkp-lib/issues/1212#issuecomment-196263730):
> What's the difference between these two options in Settings > Distribution > Permissions?

Not sure if this answers the question, but the Copyright is e.g. `Copyright (c) 2016 by Alec Smecher` and the license is e.g. `CC-By 4.0`.

**Comment by asmecher** [comment]
From [this comment](https://github.com/pkp/pkp-lib/issues/1212#issuecomment-196204815):
> So is the "Notify Users" feature ever planned for OMP or could it be removed from there?

I suspect we'll eventually need a way to send email notifications to users, so leave it out of the interface for now, but don't worry about cleaning out locale keys for the moment.

From [this comment](https://github.com/pkp/pkp-lib/issues/1212#issuecomment-196242657):
> So I'll remove the email references for review actions in attachment mode. Can I also remove references to "one-click" mode?

No, please leave references to "one-click" mode in place. It's reasonably widely used in 2.4.x and we'll probably have to forward-port it to OJS 3.0.x and OMP 1.2.x.

**Comment by NateWr** [comment]
I've had a once-over of the Catalog page now and no language changes were needed. Closing this one out.
