### ISSUE TITLE
[OJS] article incorrectly shows subscription required notice

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1220]
Against `HEAD`:

A journal issue’s access status is set to Open access in the dashboard. Nonetheless, when viewing specific articles (with URLs like `.../index.php/test/article/view/1`), a lock icon is shown with the text “Requires Subscription.” (Article galleys are accessible anyway.)

**Comment by asmecher** [comment]
@crism, FYI, our current plan is to release OJS 3.0 without subscription support, then add that e.g. for OJS 3.1. But yes, this needs fixing for the 3.0 release.

**Comment by crism** [comment]
The `accessLegend.tpl` file assumes access is restricted; it only considers whether per-article access can be purchased (`$purchaseArticleEnabled`). I think the right thing to do here is consider, in `article.tpl`, whether or not to include `accessLegend.tpl`. Now I just need to find the right variable to query to make that decision…

**Comment by crism** [comment]
No, the access legend is supposed to include an OA legend if appropriate. So… where’s that stored?

**Comment by crism** [comment]
Well, that didn’t work… why not?

**Comment by crism** [comment]
Oh… duh. Parentheses matter, but it also helps to check out the correct branch on the server. `d-:`

**Comment by crism** [comment]
Now it’s a question of styling. The current stylesheets have handling for restricted access, but no Open Access. Font Awesome doesn’t have an Open Access icon to go with the lock. We could use one of the icons from [Wikimedia Commons](https://commons.wikimedia.org/wiki/Open_Access), or from somewhere else? @asmecher, anyone else, thoughts?

**Comment by asmecher** [comment]
Thanks, @crism -- I've merged that fix. Styling-wise, I suspect @NateWr is the best person to ask -- he'll probably want to change things -- but he may need to defer considering this until after OMP 1.2 is out.

**Comment by crism** [comment]
Thanks, @asmecher. Looking forward to the styled changes when there’s time.

**Comment by NateWr** [comment]
I'll revisit this once we're back on OJS 3.0. But I think my intention was to display _no_ access legend unless access was restricted. If the default is open, then we don't really need to add anything, unless there's a particular need within the community to wear the OA status as a badge of honor. 

I'm tempted to leave it out in the default theme, but open to alternative ideas.

**Comment by crism** [comment]
@NateWr, no message would work fine, too.

**Comment by NateWr** [comment]
As part of work on #1390, I've removed the `access_legend.tpl` for now. When we turn to re-adding support for subscriptions, we can re-add it with a better sense of how it ought to work.

**Comment by crism** [comment]
Cool, thanks, @NateWr. Should we close this?

**Comment by NateWr** [comment]
I'm fine closing it, but not sure if @asmecher wants to keep it around for when we get to subscriptions.

**Comment by asmecher** [comment]
I'm content to handle that outside this entry. Thanks, @NateWr and @crism!
