### ISSUE TITLE
Assign sub editors by section/series

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1222]
Submissions should automatically be assigned to the Series/Section Editors configured in the section/series edit form.

This will also require editing the test data to remove manual assignments; previously they were not made automatically.

**Comment by asmecher** [comment]
PRs:

- https://github.com/pkp/pkp-lib/pull/1223
- https://github.com/pkp/ojs/pull/778

The logic here is not all that trivial. Basically, it goes, when a submission is completed:
1. It's assigned to every user group associated with the submission stage, that only has one person in it.
2. It's also assigned to the submitting user, with the first Author role it can connect them to.
3. It's also assigned to anyone noted as a sub editor in that section/series, once for each series/section editor role that user is active in.

Notifications are sent to any editors/sub editors assigned above. If neither was notified, then all of the journal/press's managers get a "you must assign this submission to someone" notification.

**Comment by asmecher** [comment]
@stranack, does the above logic make sense to you? I wish there was a way of simplifying this -- any time we start building a long ruleset it tells me we're overcomplicating things in a way users will also be confused about.

**Comment by stranack** [comment]
I'm probably missing something, but can we not just follow the simple 
OJS 2 logic?

New submissions are considered "unassigned" unless the author chose a 
section that has one or more section editors assigned. In that case, 
each section editor assigned to that section gets the new submission 
added to his/her queue.

Can we start this way, and if we get feedback that this is insufficient, 
revise for 3.1/1.3 ?

Kevin



On 2016-03-04 5:02 PM, Alec Smecher wrote:
> @stranack <https://github.com/stranack>, does the above logic make sense
> to you? I wish there was a way of simplifying this -- any time we start
> building a long ruleset it tells me we're overcomplicating things in a
> way users will also be confused about.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pkp/pkp-lib/issues/1222#issuecomment-192541090>.
>

-- 
--
Kevin Stranack, MLIS, MAEd
Learning and Development Consultant
Email: kevin@stranack.ca
Twitter: @stranack
Skype: kstranack
Web: http://stranack.ca

**Comment by asmecher** [comment]
We discussed this today and decided that we're basically using the OJS 2.x approach, but with what seems to be some necessary complication due to the flexible role system and some design decisions made for OMP 1.0 based on discussions of problems with the OJS 2.x approach (hence the single-role-implies-assignment idea).

**Comment by asmecher** [comment]
Also ported to OMP.
