### ISSUE TITLE
Published date shown as soon as catalog entry created

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1229]
I toggled the Create Catalog Entry checkbox on for a submission that was still in the review stage, with no publication formats or anything. It appeared in the catalog as expected, but it shows a publication date, when it should probably show either nothing or a forthcoming date.

![published-date](https://cloud.githubusercontent.com/assets/2306629/13576641/98aacedc-e486-11e5-88f6-ac32b50c76ab.png)

Is there anywhere to put a forthcoming date?

**Comment by beghelli** [comment]
I think you can still use the publication date field and set it to a future date. I would try to use that, it makes more sense than having another field. But I agree that the default should be to present "no publication date available" or something instead of the current day that the catalog entry was created and made available...

**Comment by NateWr** [comment]
Do you know how to find this publication date field in OMP? Not seeing anything under Catalog Entry.

**Comment by bozana** [comment]
I think you cannot set that dayte -- the date that is displayed on the catalog page -- just the dates for the each publication format. S. https://pkp.sfu.ca/support/forum/viewtopic.php?f=25&t=13905 and https://pkp.sfu.ca/support/forum/viewtopic.php?f=40&t=13443 from earlier...

**Comment by beghelli** [comment]
Ok, so I was dreaming with that then, sorry.

2016-03-08 13:10 GMT-03:00 bozana <notifications@github.com>:

**Comment by asmecher** [comment]
The ONIX data set includes a wide variety of options for publication dates, but they're all associated with the publication format, not the monograph, and it's not clear which dates of those we'd list.

**Comment by NateWr** [comment]
Hmm, we're going to need some publication date for display, won't we? I looked at OpenSI and Langsci and both seem to have an "Added" date (?) and a "Publication date".

![selection_042](https://cloud.githubusercontent.com/assets/2306629/13914417/2e7ca204-ef46-11e5-87bd-b70988d59eb5.png)

![selection_041](https://cloud.githubusercontent.com/assets/2306629/13914418/2e7d13ce-ef46-11e5-8a71-8fd0e38bb34a.png)

I wonder where this data is coming from...

**Comment by asmecher** [comment]
That's on the publication format, correct, Nate? There's good-quality publication date data on the publication format, but not the monograph as a whole.

**Comment by NateWr** [comment]
I don't know where the data comes from, but the UI in the screenshots presents it as data pertaining to the monograph. It's not displayed as though it's attached to specific formats.

I do think we'll want to display a publication date that pertains to the book as a whole. As a reader that's what I generally expect. But that doesn't mean we need to have a new field for that piece of data. If we don't have a publication date attached to a book then our best course of action is probably to display the earliest publication date from all available formats.

**Comment by NateWr** [comment]
(btw, we can punt this to after OMP 1.2, but if so we'll want to *remove* the display of the publication date from the frontend)

**Comment by bozana** [comment]
Hi @NateWr, for LangSci the "Added" date is the one when the book is added to the catalog and the "Publication date" is the (ONIX) date defined for a publication format on the Catalog Entry modal. One can apparently influence the "Added" date a little bit: you can remove and add the book to the catalog again, and the date will change.

**Comment by asmecher** [comment]
Two proposals:

1. Call it "date added", not "date published". Have publication dates only under the publication formats per ONIX data.
2. Find the earliest "date published" from all publication formats, and if one can be found, use that.

I'm leaning towards option 1; it's simple and clear to the reader, and presents data only where it's most appropriate.

**Comment by asmecher** [comment]
(Implemented option 1, because it's quick, but leaving open for feedback for a little while in case there are agitators)

**Comment by asmecher** [comment]
Arright, hearing nothing...
