### ISSUE TITLE
Email template tags look like buttons

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1236]
The email template tags are confusing users because they look too much like buttons. Re-style them to not look clickable.

![email-template-tags](https://cloud.githubusercontent.com/assets/2306629/13599429/be9f97fa-e51a-11e5-90ae-66617eb31ae6.png)

**Comment by NateWr** [comment]
@asmecher Fixed the styles in https://github.com/pkp/tinymce/pull/7. Do you want PRs for OJS/OMP to update the submodule? Or just let you pick it up when you make the rest of the changes we discussed?

**Comment by asmecher** [comment]
Thanks, @NateWr -- don't worry about the submodule commits.
