### ISSUE TITLE
[OJS] Article publication date incorrectly set to "today"

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1238]
Article publication dates (that is: published_articles.date_published) appear to be set incorrectly to "today" when scheduling an article for publication to an issue that has already been published. The article's publication date should be set to the issue's publication date (issue.date_publicatished) by default. The only time articles should receive a different publication date is if the article publication date is explicitly set. 

Steps to replicate: 

1) publish an issue. 
2) wait a day (or set the issue's publication date to an earlier date). 
3) schedule an article to that issue by choosing the issue under Scheduling and pressing the first "Record" button. 

The article's publication date will be set to today. It should instead be set to the issue's publication date. 

I believe this is a problem with the code here: 

https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/pages/sectionEditor/SubmissionEditHandler.inc.php#L2569

... possibly introduced here: 

https://github.com/pkp/ojs/commit/ac6e287f83318c66b28f64e6316df283d8e378f3

... thought the code has changed somewhat since then. 

Current workaround: individually set each published article's publication date.

**Comment by asmecher** [comment]
@jmacgreg, one of the common use cases for publishing an article to an already-published issue is if the journal is using a megajournal-style model (where the "current" issue gets new articles). I'd argue that the article publication date should be set to the day the article is scheduled, not the date the issue was published.

**Comment by mtub** [comment]
I agree with what @asmecher said - in fact the change you suggest, @jmacgreg, would really contradict the meaning of "publishing" an article. You should not set the publication date to an earlier date.

**Comment by jmacgreg** [comment]
Right, on further consideration totally agreed (as I probably was when the original article/issue date_published code was introduced). This was a problem reported by a client, IIRC; I'll see if I can track down what the issue was and if there was a larger issue behind the scenes, but otherwise I'm ok with closing this.

**Comment by bozana** [comment]
@jmacgreg and @asmecher, what shall we do with those empty dates, that probably come in with the quick submit plugin? I.e. how to deal with them in the Crossref export? At the moment, the article can not be exported if the date is missing.

**Comment by jmacgreg** [comment]
Hi Bozana, 

Can you refresh my memory if there is any date at all to fall back on? That is, is there an issue publication date?

**Comment by bozana** [comment]
Hi James, yes there is the issue publication date, but if the article publication date is not set, the article is not considered for the Crossref export. This could also lead to this issue: http://forum.pkp.sfu.ca/t/ojs-2-4-7-1-crossref-zero-items/10808. 
It could eventually stay as it is -- it requires the user to enter those publication dates, but... 
At the other places in the system we display the issue publication date (e.g. RT, OAI) in such a case. 
So I just wanted to check if we do think this all should stay as it is :-)
THANKS!!!

**Comment by asmecher** [comment]
I would rather leave this as is, and in the future (OJS 3.0) really try to make these fields more logical. The fallback-on-issue behavior was an expedient fix to a problem (Google Scholar was getting poisoned metadata), but it's made the code unnecessarily convoluted, and there are cases like this.

**Comment by jmacgreg** [comment]
My suggestion for OJS 2.4.x would be to fall back to the issue publication date if there isn't an article publication date set. As alec suggests, that becomes convoluted. I curse that Quick Submit plugin almost daily.

**Comment by bozana** [comment]
Hihihihi :-)
Shall I then change the Crossref plugin behavior -- to export the issue publication date if the article publication date is missing and thus consider also those articles for the export?

**Comment by jmacgreg** [comment]
Yes please! I think that's the best solution for now. We can maybe have a meeting to discuss a better implementation for OJS 3 later? I'll be on the dev call today so we can chat quickly then too. :-)
