### ISSUE TITLE
[OJS] Missing mime_content_type function prevents downloading deposits

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#1242]
There's at least one OJS instance out there running without the mime_content_type function available. It's strange, that function should be available in the default PHP install that they're running (5.4.45). 

The PLN plugin doesn't check for the function before calling it, causing a fatal error if it isn't available.

**Comment by asmecher** [comment]
That function is deprecated in favour of the finfo suite of functions; see String::mime_content_type for an OJS implementation that checks for 3 different options and uses what's available.

**Comment by ubermichael** [comment]
Interesting. There's no mention of it being deprecated on http://php.net/manual/en/function.mime-content-type.php.

Thanks Alec.

**Comment by ubermichael** [comment]
The PR now uses the String::mime_content_type function.

**Comment by asmecher** [comment]
Looks good, thanks -- merged.
