### ISSUE TITLE
[OJS] Custom stylesheet not loaded on frontend

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1247]
A custom stylesheet added via **Settings > Website > Appearance > Journal style sheet** is not actually linked on the frontend.

**Comment by asmecher** [comment]
This ended up being a one-liner.

**Comment by seunboi** [comment]
Hello, 
Sorry if I am posting in the wrong place. Now the CSS file won't upload. 
![1](https://cloud.githubusercontent.com/assets/20903263/17595871/d26ec624-5fe6-11e6-8ef2-b5085bfec290.JPG)
![2](https://cloud.githubusercontent.com/assets/20903263/17595878/d76b6fa6-5fe6-11e6-9e85-427a0a5e76a3.JPG)

**Comment by asmecher** [comment]
@seunboi, try posting this on the support forum at http://forum.pkp.sfu.ca/, and don't forget to include the application and version you're using.

**Comment by seunboi** [comment]
Thanks. Will do so.

**Comment by JcNeo** [comment]
Hi @seunboi, good day

Can you please share with me how you solved the problem with the CSS, since I have the same error does not load any CSS file, previously it worked but now it does not allow me

regards!!!

JoseCandido
