### ISSUE TITLE
Consider user rights/role for the "New Submission" button display

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1248]
Display the "New Submission" button only if the user is allowed to make a submission. S. https://github.com/pkp/pkp-lib/issues/975#issuecomment-194306456.

**Comment by bozana** [comment]
@beghelli, is it so that only author role can use this button?

**Comment by asmecher** [comment]
@bozana, the submitting user currently needs to be in a user group that's got an author role:
https://github.com/pkp/pkp-lib/blob/master/classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php#L34

**Comment by bozana** [comment]
@asmecher, thanks for pointing to the place in the code -- that helps! So actually, it is all groups with author role (ROLE_ID_AUTHOR) and assigned to WORKFLOW_STAGE_ID_SUBMISSION + all groups with manager role (ROLE_ID_MANAGER), s. https://github.com/pkp/pkp-lib/blob/master/classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php#L81-L104

**Comment by bozana** [comment]
Hmmm... If I only have translator role that is not assigned to WORKFLOW_STAGE_ID_SUBMISSION, I am able to enter the submit step 1 and then I get this warning: "Your account does not currently have a role permitting new submissions, such as Author. Please double-check your account; you may be able to add a suitable role yourself by editing your profile. ". Then I am able to give myself the author role and make a submission. Thus, actually, the new submission button should be displayed to all with the role ROLE_ID_AUTHOR and all with the role ROLE_ID_MANAGER.

**Comment by asmecher** [comment]
Yes, you're right -- managers and authors should be able to start submissions. We may get feedback that requires changes to this later, but I think that'll be a good start.

**Comment by asmecher** [comment]
Merged, thanks!
