### ISSUE TITLE
[OJS] File uploader UI appears broken

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1255]
In OJS 3 `HEAD`, the file upload interface has a notification: “The system file uploader is loading, …” followed by the unstyled drop zone and a button that says “Upload File Change File.”

The underlying HTML appears identical to the file upload space in OMP `HEAD`; some JavaScript isn’t firing correctly.

This is surprising, since the underlying `pkp-lib` should be identical (I update daily).

**Comment by asmecher** [comment]
Try...

    rm cache/*.css
    rm cache/*.php
    rm cache/t_compile/*.php
    cd lib/pkp
    php composer.phar update

**Comment by crism** [comment]
Sorry, @asmecher—you’re absolutely right. I’ve gotten in that habit with OMP, but not yet with OJS for some reason. `d-:`
