### ISSUE TITLE
[OJS] close button unresponsive in reviewer’s Submission Details modal

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1256]
Against `HEAD`:

As a reviewer, I receive an assignment. On the first page (`.../test/reviewer/submission/4`), there is a link, “View All Submission Details.” It brings up a modal dialog with a button at the bottom labeled “Close.” That button is unresponsive, as far as I can tell. The X at the top of the modal dialog works just fine.

**Comment by NateWr** [comment]
@crism, would you mind testing again against latest master? I remember that close button but can't remember if I actually fixed it or not.

**Comment by NateWr** [comment]
No need to re-test @crism. Just came across this is my own testing and it will be removed in some forthcoming commits connected to #1212.

**Comment by NateWr** [comment]
The PRs in [this issue comment](https://github.com/pkp/pkp-lib/issues/1212#issuecomment-196459844) should fix things. Once they're merged this can be closed.

**Comment by asmecher** [comment]
Done!

**Comment by crism** [comment]
Good to know, @NateWr—thanks.
