### ISSUE TITLE
[OJS] include reviewers in review-round discussions

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1257]
Against `HEAD`:

While testing OJS with a journal editor, we drew his attention to the Review Discussions part of the Review stage tab. He immediately assumed that it could be used for discussions with the reviewers, as well as with the author. While individual reviewers can be contacted by e-mail, there’s no in-system way to have a group discussion between the editor and multiple reviewers.

It wouldn’t make sense to allow reviewers to start such a conversation, but it could be something to allow, at the editor’s discretion.

**Comment by asmecher** [comment]
@stranack raised something similar recently. Kevin, what do you think about the approach @crism is proposing? I worry it might muddy where the reviews live.

**Comment by stranack** [comment]
This is an interesting point and worth further consideration. At this point though, I'd be tempted to leave it as is until we get further feedback. Let's get a sense of how the discussions are working overall, and then dig into details like this a little later.

**Comment by ajnyga** [comment]
I think this can be closed @asmecher

**Comment by asmecher** [comment]
Yes, thanks!
