### ISSUE TITLE
[OJS] “Resubmit for Review” button is unclear

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1258]
In `HEAD`, in the review stage of a submission, there are four buttons. Three of them are predicates of which the editor is the subject: “Request Revisions,” “Send to Copyediting,” “Decline Submission.” One has the author as the subject: “Resubmit for Review.” The intent is to ask the author to submit revisions which will be further reviewed, but this was unclear to a journal editor (and to us) while testing the system.

Given the space restriction on the button, I’m not sure what better to suggest, though I do wonder if it couldn’t be rolled into “Request Revisions.”

**Comment by asmecher** [comment]
@stranack, as a data point for your review-stage feedback.

**Comment by NateWr** [comment]
I'm not sure of the technical implications, but I think it could be good to roll the "Request Revisions" nad "Resubmit for review" into the same modal.

Perhaps there could be a radio button grouping with two options:

- Revisions will not require a new round of reviews
- Initiate a new review round for these revisions

**Comment by NateWr** [comment]
This issue is being addressed alongside #1144. You can see the proposed changes here: https://github.com/pkp/pkp-lib/issues/1144#issuecomment-324392595

**Comment by bozana** [comment]
Everything merged, thus closing...
