### ISSUE TITLE
[OJS] send to copyediting should select revisions by default

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1260]
In `HEAD`: After the author has submitted revisions, when the editor sends the submission to copyediting, the revision files are not selected by default. I can’t think of a good reason why not.

**Comment by crism** [comment]
There are two different grids used for promotion: `grid.files.review.SelectableReviewRevisionsGridHandler` (which does not seem to select files by default) and `grid.files.copyedit.SelectableCopyeditFilesGridHandler` (which does).

**Comment by crism** [comment]
Ugh… somewhere in there, maybe in the hooks, the `selected` flag gets set by default in one case, and not in the other. I haven’t managed to figure out where… anyone else have any pointers?

**Comment by crism** [comment]
OK! This finally comes down to the value of `submission_files.viewable`. The question, then, is why are revisions not set as viewable? It’s not the display grids’ problem at all.

**Comment by crism** [comment]
Looks like this was [previously addressed](https://github.com/pkp/pkp-lib/blob/master/classes/file/SubmissionFileManager.inc.php#L329), but just for submissions:
```php
$submissionFile->setViewable($fileStage == SUBMISSION_FILE_SUBMISSION?true:false); // Bug #8308: Submission files should be selected for promotion by default
```
@asmecher, what’s the rationale for when files should be viewable or not? What implication does it have beyond not being selected by default in a selectable grid?

**Comment by crism** [comment]
Hrm, but… the _only_ place the `selected` flag is set (as far as I can find) is in `SelectableItemsFeature::getInitializedRowInstance()`. It calls `isDataElementSelected()`, which varies by `GridHandler` subclass… what if some of the grid handlers just always returned `true`? I’m thinking just:
 * `SelectableCopyeditFilesGridHandler`
 * `SelectableReviewRevisionsGridHandler`

Is there any downside to this plan?

**Comment by asmecher** [comment]
I think we were nervous about making permissive assumptions about how files are treated by default, but I can foresee that your expectations will be pretty normal amongst our user community. I'm OK to go ahead with the proposed change.

**Comment by crism** [comment]
Uh… and I seem to have screwed up the project name in the commit messages. Sorry about that.

**Comment by asmecher** [comment]
Merged -- thanks for your patience and work on this one, @crism!
