### ISSUE TITLE
[OJS] author gets inappropriate message in production stage

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1261]
Against `HEAD`: When an author’s submission is in production, and the link is followed from the submissions dashboard, the author gets the message, “Stage not initiated.” There is no reason to give the author access to the production dashboard, but the rejection message is false and confusing.

A trivial fix is to change the message to something more accurate. A better fix would be to give the author some kind of meaningful (but safe) view of the state of their submission.

**Comment by crism** [comment]
I think that, just as in the Copyediting stage, the author ought to be able to see the relevant discussions, and nothing else. It seems entirely possible that the author might be involved in a conversation even at the production stage, or at least I see no reason to rule it out.

**Comment by crism** [comment]
In fact, the author can be selected to receive a discussion message at the Production stage, but cannot get in to read it! Will try to look at how the Copyediting tab is built and build something parallel in Production.

**Comment by crism** [comment]
Ah… the template includes this logic:
```
{if $submission->getStageId() >= $smarty.const.WORKFLOW_STAGE_ID_PRODUCTION && !empty($representations)}
```
The submission in question has no galleys as yet… Is there any good reason not to just chop that last clause? If the submission is in production, why claim it’s not? @NateWr, @asmecher?

**Comment by NateWr** [comment]
Not that I know of...

**Comment by crism** [comment]
OK, the author can now see the production tab… but there’s nothing there. Need to add access to the discussion, à la Copyediting.

**Comment by asmecher** [comment]
Thanks for tracking this down, @crism!
