### ISSUE TITLE
Discussions grid message styles need work

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1267]
![selection_008](https://cloud.githubusercontent.com/assets/2306629/13751834/e7802804-ea03-11e5-8ae9-a3233147544f.png)

**Comment by NateWr** [comment]
PR: https://github.com/pkp/pkp-lib/pull/1313

Screenshot:

![discussion-grid](https://cloud.githubusercontent.com/assets/2306629/14078920/8fcf8818-f4f1-11e5-8aa0-a348b3f1103b.png)

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by NateWr** [comment]
Tiny PRs addressing your comment at https://github.com/pkp/pkp-lib/pull/1313#discussion_r57758898

https://github.com/pkp/pkp-lib/pull/1319
https://github.com/pkp/omp/pull/253

**Comment by asmecher** [comment]
Merged those, thanks!
