### ISSUE TITLE
Reviews ready notification displays in author review round

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1268]
When reviews are submitted, a notification appears in the author dashboard. This is good but could lead an author to think that they should be able to view the reviews.

![selection_010](https://cloud.githubusercontent.com/assets/2306629/13754646/ab4a3152-ea0f-11e5-8bd9-f2aad4160dc7.png)

The same notification message is used for editors and authors, but it would be nice if authors had a unique message that was more clear, like: "New reviews have been submitted and are being considered by the editor."

**Comment by asmecher** [comment]
@NateWr, is this an old checkout? That locale key ("New reviews ready") no longer appears in the codebase by my grepping.

**Comment by NateWr** [comment]
Sorry I changed that string to something else since taking that screenshot. Looks like the related message key is [editor.submission.roundStatus.reviewsReady](https://github.com/pkp/pkp-lib/pull/1272/files#diff-f69e5caa980791d6835909656e9eace7L523).

**Comment by asmecher** [comment]
Not the cleanest solution but works for now.
