### ISSUE TITLE
OMP doesn't have a place for internal review stage guidelines

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1269]
There's a place to enter External Review Guidelines (Settings > Workflow > Review) but not Internal Review Guidelines. And the external guidelines are not re-used for the internal review.

As a result, there's a broken modal pop-up on step 3 for reviewers which tries to open guidelines.

**Comment by asmecher** [comment]
Good catch. I've fixed the missing OMP extension of the review form, which was supposed to add the "internal review guidelines" field, and adjusted the presentation in the reviewer's interface to properly distinguish between the two.
