### ISSUE TITLE
Empty editor decisions list for copywriter

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1270]
In some cases in the workflow an empty editor decisions list may be printed, for instance in the Copyediting tab when logged in as a copyeditor. This should be a quick fix, but check all tabs.

**Comment by NateWr** [comment]
The following PRs don't fix this issue, but they do remove some unneeded code discovered while looking into this issue:

https://github.com/pkp/pkp-lib/pull/1312
https://github.com/pkp/ojs/pull/805
https://github.com/pkp/omp/pull/251

Actually fixing this issue requires modifying the editorial actions so that they don't use the `load_url_in_div` pattern, which results in an empty element.

https://github.com/pkp/pkp-lib/blob/master/templates/controllers/tab/workflow/submission.tpl#L12

Alternatively, the CSS could be restructured, but that's likely to have more unintended knock-on effects.

Assigning this to OJS 3.0 but it's pretty low-priority.

**Comment by asmecher** [comment]
The above PRs broke the tests, but this selector change should fix them:
https://github.com/pkp/pkp-lib/commit/13b01e9d5423459934231d9be21d40923a4a2018
I'll verify and merge if it looks OK.

**Comment by asmecher** [comment]
Merged the above. This entry still needs work per https://github.com/pkp/pkp-lib/issues/1270#issuecomment-202338650

**Comment by NateWr** [comment]
Pushing to 3.0.1.

**Comment by NateWr** [comment]
Bumping onto our 3.1 milestone.

**Comment by NateWr** [comment]
I addressed this in most cases by adding a notice that an editor needs to be assigned. Users with assistant roles assigned to later stages will still not see this notice and get the empty gap, but that's rare in comparison to the usual use-case: the submission stage before an editor is assigned.

![selection_016](https://user-images.githubusercontent.com/2306629/27219327-3a1bf802-5279-11e7-806f-c7fb6f9c62ec.png)

PR:
https://github.com/pkp/pkp-lib/pull/2590

Tests:
https://github.com/pkp/ojs/pull/1425
https://github.com/pkp/omp/pull/416

**Comment by NateWr** [comment]
Tests passed. @asmecher would you do code review?

**Comment by NateWr** [comment]
Merged.
