### ISSUE TITLE
Copyeditor can not initiate discussion with author

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1271]
When logged in as a copyeditor assigned to the copyedit stage, I'm having trouble initiating a discussion with the author.

I can select the author, and the discussion appears in my discussions table, but there's a PHP Warning in the error log and the discussion never appears in the author's discussions table.

```
[Mon Mar 14 18:19:43.910461 2016] [:error] [pid 15940] [client 192.168.0.8:41630] PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'QueryForm' does not have a method 'updateEntry' in /var/www/html/omp/lib/pkp/classes/controllers/listbuilder/ListbuilderHandler.inc.php on line 303, referer: http://192.168.0.8/omp/index.php/publicknowledge/workflow/index/28/4
```

**Comment by asmecher** [comment]
I couldn't duplicate the behavior here, but the attached commit should fix it.

**Comment by NateWr** [comment]
Fix confirmed. :+1:
