### ISSUE TITLE
Check for installation test

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1273]
The last check for the installation test is: $this->waitForElementPresent('link=login');
In OJS 2.4.x there is always the "Login" link in the navigation bar, so that the test passes also if the installation was not successful -- for example if an error was displayed in the installation form. This is not the case for the current master branch -- the "Login" link comes first after the installation, but in order to unitize it, the last check will be changed in the stable as well as in the master branch, to $this->waitForTextPresent('has completed successfully.');

**Comment by asmecher** [comment]
Merged, thanks! Needs cherry-picking.
