### ISSUE TITLE
[OJS] version 2.4.8: No export of sponsor in NativeExportDom.inc.php

### ISSUE THREAD

**Issue by nddf** [pkp/pkp-lib#1277]
Hello, 

The plugin does not export sponsor information in plugins/importexport/native/NativeExportDom.inc.php.
The following added code helped me out: 

 
![sponsorfix](https://cloud.githubusercontent.com/assets/12379318/13775028/9a4fbf5a-eaa2-11e5-8da3-9cf85d42e630.png)

**Comment by ctgraham** [comment]
@nddf , did you close this issue on purpose?  Our current practice is to leave the issue open until the pull request has been merged in.  I see you've created a PR here: https://github.com/pkp/ojs/pull/795
