### ISSUE TITLE
Simplify Sponsors Page

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1283]
Both OMP 1.2 and OJS 3 have complicated settings for the sponsors page (under Settings > Journal or Press) - inherited from OJS 2. Consider stripping this down to a text field, similar to how we simplified Masthead.

**Comment by asmecher** [comment]
I think I'm going to move this to 3.0. The current structure works, but it's overprescriptive for no apparent reason.

**Comment by asmecher** [comment]
Deferring to 3.0.1, unless someone thinks it's really necessary for 3.0.

**Comment by asmecher** [comment]
This got resolved in https://github.com/pkp/pkp-lib/issues/1397.
