### ISSUE TITLE
Copyeditor initiated discussion not recorded

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1286]
When a copyeditor uses the Add Discussion link and fills in the modal, the message is not being recorded in the Copyediting Discussions grid.

http://journals.sfu.ca/uiux/index.php/publicknowledge/workflow/index/3/4

**Comment by NateWr** [comment]
Assigned to OMP 1.2 so that it's tested and replicated or ignored before the release.

**Comment by asmecher** [comment]
I think this was fixed by https://github.com/pkp/pkp-lib/commit/94bcc5c2089e770c9a85a4f7894d7fa2decc85ce a while ago. Anyway, it checks out for me now.
