### ISSUE TITLE
Tools link leads to error

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1289]
In OJS 3, selecting the Tools link results in the following error:

Warning: Smarty error: unable to read resource: "management/tools/index.tpl" in /mnt/u1/var/www/journals/uiux/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php on line 1094

The URL is:
http://journals.sfu.ca/uiux/index.php/publicknowledge/management/tools/index

**Comment by asmecher** [comment]
Used a solution we've used elsewhere: converted this part of management to a tab set, and made the container link go to the first tab.
