### ISSUE TITLE
[OMP] Publication formats appear on frontend even if removed from catalog entry

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1294]
The following publication format appears on the frontend.

![selection_046](https://cloud.githubusercontent.com/assets/2306629/13950306/0abd6d30-f022-11e5-984c-0d0fd37cda71.png)

As far as I can tell, the Catalog Entry option is just a cosmetic "sign off", and doesn't actually do anything. Is this a bug or intentional? If intentional we need to re-think the wording on this.

**Comment by asmecher** [comment]
The "Complete" flag is to indicate that whoever is in charge of the academic aspect of approvals is finished their work. It's just cosmetic. The "No Catalog Entry" language definitely needs changing.

**Comment by asmecher** [comment]
I've adjusted the wording to "Complete" / "Not Complete". But I'm leaving this issue open -- any feedback, @stranack?

**Comment by NateWr** [comment]
Thanks for the clarification @asmecher. This is disheartening, since we spent so much time going over the approvals process. But I think it makes sense. I have a couple of language tweaks I want to do (help docs, approve confirm modal, awaiting approval) so I'll assign this to me.

**Comment by NateWr** [comment]
Ok I've updated the language in the checkboxes to say "Awaiting Approval" and "Approved", just like the format checkboxes. I've also adjusted the language in the confirmation modals to indicate more clearly the task that is meant to be "approved".

https://github.com/pkp/pkp-lib/issues/1294

![selection_033](https://cloud.githubusercontent.com/assets/2306629/14076119/cd318eba-f4d6-11e5-9e7b-f4c35b47bd1e.png)
![selection_034](https://cloud.githubusercontent.com/assets/2306629/14076120/cd31f1de-f4d6-11e5-8f57-a256ebf6b7bc.png)

I also updated the help docs in my big PR to reflect this change.

**Comment by NateWr** [comment]
It looks like OJS just has the single sign-off, rather than the separate metadata/publication sign-offs. So I think we're ok to close this one.
