### ISSUE TITLE
Native XML import should be improved for OMP and OJS

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1295]
I am testing the native import in OMP and found the following things that could/should be improved:
- [x] c) what about assoc_type ad assoc_id -- I have to see what is this and how is this handled -- at the moment they are = null. This seems to be the way how representations and files are connected, so at least this should be considered for the import. It is also the way how reviewer assignments are connected with the files -- this is a little bit bigger problem, because we don't deal with reviewer assignments in the import. ( PR OMP: https://github.com/pkp/omp/pull/261 and https://github.com/pkp/pkp-lib/pull/1337) (PR OJS: https://github.com/pkp/ojs/pull/817)
- [x] d) submission status is wrong -- I imported a published submission (it is imported as such and also displayed on the catalog page) but status is = 1 (i.e. STATUS_QUEUED). (PR OMP, OJS: https://github.com/pkp/pkp-lib/pull/1302)
- [x] e) consider "viewable" attribute for revision element i.e. files (PR OMP, OJS: https://github.com/pkp/pkp-lib/pull/1302)
- [x] f) consider "type" element for submission (PR OMP, OJS: https://github.com/pkp/pkp-lib/pull/1302)
- [x] g) consider "available" attribute for publication format element (i.e. only for OMP) (also for export)
- [x] consider remote pub formats: There is remote element defined for files. At the moment it seems that there is no difference between this and the href element? Shouldn't the remote element rather be used for remote representations i.e. defined for the representation element and the src attribute saved as representation remoteURL? (PR OMP, OJS:  #1299)
- [x] adapt file genres according to the solution from https://github.com/pkp/pkp-lib/issues/1263 (PR OMP, OJS: https://github.com/pkp/pkp-lib/pull/1299)

The needed native import improvements for OJS 3.0:
- [x] a) The supplementary files are not considered in the export. (PR OJS: https://github.com/pkp/ojs/pull/965) (PR OMP: https://github.com/pkp/omp/pull/318)

**Comment by asmecher** [comment]
Hmm, that `submission_file_ref` thing is a pretty big oversight -- probably on my part -- so thanks for catching it! I tend to test without paying much attention to files, which is probably how it was overlooked.

I do like the overall approach we're using -- submission files in a pool, referred to from specific uses -- but of course we'll have to consider how to map IDs, which shouldn't be preserved upon import.

(BTW, the `id` element -- not used here, these are attributes -- has a germinal `advice` attribute, where the importer can recommend whether to `update` an existing entity or `ignore` the ID.)

Have a look at the import/export context object. That's not the same as "context" in terms of press or journal, it's a way to store information about the import/export and pass it between different levels of the filter.

**Comment by bozana** [comment]
Hi @asmecher, maybe you mean the PKPImportExportDeployment class? There, some information is saved and passed between different levels of the filter. We could also save the information about the relation between the XML file and DB IDs there, e.g. to have something like fileIds[fileId][revisionId] = DBFileId or fileIds[fileId-revisionId] = DBFileId. This would probably work for the relation between the representations and files, because the files come first and then representations, i.e. the necessary file information is there when importing representations. But what to do with the revision's source? Could we assume that first the files are listed i.e. processed, that are source for other files? In connection to this question: should we import all files at the moment, e.g. also the review files? As far as I could see, there is no possibility to connect them with the appropriate review assignment (that could also not exist before the import), or have I overlooked something? Maybe it doesn't matter -- to just have them in the database and in files folder but not to be able to access them in the system? -- As far as I could see, only those files in workflow stages (different than submission and proof) can have source files i.e. the source question is related only to those workflow stages files. THANKS!!!

**Comment by asmecher** [comment]
@bozana, yes, sorry -- I meant the Deployment, not the Context. We've pretty much ransacked the English language for all the similar words -- Context, Deployment, Type, Collection, Delegate, ...

You're asking about the `source_file_id` and `source_revision`, correct? I think we don't need to include those for now; they're more informational and deeper in the workflow than we currently have gone in import/export concerns. We'll probably need to include support once we have the workflow included in the process, but we aren't there yet.

**Comment by bozana** [comment]
@asmecher, I've considered the submission_file_ref, that is only used for representations at the moment. I'll wait with the PR till the other native export PR is merged.

And yes, I was asking about source_file_id and source_revision i.e. the source attribute of the revision XML element. So, for example, the following revision (a part of the current native export) will be inserted by the current native import, but without the source (i.e. = NULL):
```
<revision number="1" source="1-1" genre="Book Manuscript" filename="1-99Z_Book Manuscript-2-1-10-20151211.pdf" viewable="true" date_uploaded="2016-01-18" date_modified="2016-01-18" filesize="86369" filetype="application/pdf" user_group_ref="Press manager" uploader="admin">
	<name locale="en_US">book 1 author submission file revision 2</name>
	<embed encoding="base64">...</embed>
</revision>
```
Is this OK so, i.e. can we leave it so at the moment?

**Comment by asmecher** [comment]
Yes, I think that's OK for now (no source_file_id/source_revision_id).

**Comment by asmecher** [comment]
That last PR to OMP needs porting to OMP, right?

**Comment by bozana** [comment]
@asmecher, yes, I will have to check all those import/export issues for OJS :-)

**Comment by bozana** [comment]
The needed native import improvements for OJS 3.0:
- [ ] a) The supplementary files are not considered in the export.
- [ ] b) Only issue(s) can be imported. Allow article(s) import too?

**Comment by asmecher** [comment]
@bozana, I merged that latest PR, thanks -- I'll let you update any checkboxes here that need checking.

**Comment by bozana** [comment]
Thanks @asmecher! Those are new checkboxes, for later :-) Maybe I should add them above, with all the others?

**Comment by asmecher** [comment]
If you like; that might help avoid things getting lost if this list gets longer.

**Comment by bozana** [comment]
I will close this issue and open a new one -- to consider some time in the future: https://github.com/pkp/pkp-lib/issues/1709
