### ISSUE TITLE
[OJS] “does not have access” error loading additional submissions

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1297]
Against OJS `HEAD`, I’m logged in as the administrator, looking at the submissions dashboard. There are many unassigned submissions, enough that the “Load More” affordance is active. When I scroll down the list or click “Load More,” I get a pop-up message: “The current role does not have access to this operation.” This happens even if I move the mouse too close to the list of submissions.

The Administrator user has the roles JM, JE, and ProdE.

**Comment by crism** [comment]
This happens if I’m logged in as the user who submitted all the submissions, too; looks like just a general bug with the list expansion.

**Comment by asmecher** [comment]
@beghelli, any idea what might be happening here?

**Comment by beghelli** [comment]
I think that it has to do with the operation to fetch rows, 'fetchRows', not being strictly assigned to any user roles in the grid handler authorization method... strange, but I will check.

**Comment by crism** [comment]
Interestingly, the “My Assigned” grid doesn’t have this problem, just “Unassigned.”

**Comment by crism** [comment]
I may have been barking up the wrong tree. @beghelli, clicking “Load more” sends _two_ XHR requests. They’re indistinguishable, except for the `_` parameter, but seem to have contradictory parameters. They look like: `$$$call$$$/grid/submissions/unassigned-submissions/unassigned-submissions-list-grid/fetch-rows?grid-submissions-unassignedsubmissions-unassignedsubmissionslistgridPage=1&grid-submissions-unassignedsubmissions-unassignedsubmissionslistgridItemsPerPage=5&grid-submissions-unassignedsubmissions-unassignedsubmissionslistgridPage=2&grid-submissions-unassignedsubmissions-unassignedsubmissionslistgridItemsPerPage=5&search=&column=author&stageId=0&_=1461015743092`… Surely that’s not right‽

**Comment by crism** [comment]
A stack trace at the point the permission denied dialog pops up:

function | file
--- | ---
`jQuery.event.trigger` | `jquery.js:4537`
`.trigger/<` | `jquery.js:5235`
`.each` | `jquery.js:384`
`jQuery.prototype.each` | `jquery.js:137`
`.trigger` | `jquery.js:5234`
`$.pkp.classes.features.InfiniteScrollingFeature.prototype.loadMoreItems_` | `InfiniteScrollingFeature.js:334`
`$.pkp.classes.Handler.prototype.callbackWrapper/<` | `Handler.js:268`

**Comment by crism** [comment]
Which, interestingly, still gets called twice; I have to dismiss the error dialog twice. I have a suspicion some code somewhere is called twice, leading to the double call (there are two identical event handlers on the loader) _and_ the doubled parameter set in each call, which may be resulting in the error.

**Comment by crism** [comment]
Nope, that’s interesting but not in the way I’d thought. When the submissions page is first loaded, there are only three (distinct) click handlers. After each click, a new, redundant handler is added, which may be diagnostic, but means that redundancy is not the source of the first failure.

**Comment by crism** [comment]
Whoa!

**Comment by crism** [comment]
OK, still more information. At `GridHandler.js:603`, there’s a call to `$.get()`. At this point, `this.fetchRowsUrl` _already_ has `long-thingPage=1&long-thingItemsPerPage=5`, but `params` is being added to that, which _adds_ `long-thingPage=2&long-thingItemsPerPage=5`. So where are the pre-built parameters coming from? Maybe when the grid is first built?

**Comment by crism** [comment]
So this happens right off the bat; the first thing in `GridHandler::fetchGrid()` is `setUrls()`, which AFAICT sets the URLs to include the first-page parameters. Let’s see what happens if we strip those off…

**Comment by crism** [comment]
Well, that doesn’t make things worse, so I’m going to keep that code, but it doesn’t fix the problem…

**Comment by crism** [comment]
@beghelli—after a few days barking up wrong trees, I have a handle on it.

When the dashboard is freshly-loaded, the `RoleBasedHandlerOperationPolicy` constructor is called with operations `fetchGrid`, `fetchRows`, and `fetchRow`. When it’s called for the load more operation, it’s only given the operations `fetchGrid`, `fetchRow`, and `deleteSubmission`. But `fetchRows` is the operation needed here, and so permission is denied.

The question, then, is where are those set, and how can I fix them? Thanks.

**Comment by beghelli** [comment]
@crism , really sorry, I thought I had solved this. It seems to be exactly what I said on my first comment, but I forgot to implement. 

I think it is fixed by the commit above, can you double check with your database to see if that really solves the problem? It is not on the official repo yet, only on mine, so if you want to test you can fetch my repository, master branch (it will be quick, it is up to date with the official one) and cherry pick the commit. 

Thanks,
Bruno

**Comment by crism** [comment]
@beghelli, perfect! That did it… it was staring me in the face. And no worries—this quest was extremely educational, especially in light of the upcoming sprint.

**Comment by asmecher** [comment]
Merged your PR -- thanks, @crism. @beghelli, does that resolve the issue fully?

**Comment by sintret** [comment]
still problem with ojs 3.1.2 with fresh install

you can try to my website
http://jurnal.sintret.com/index.php/index/login
username admin
password 123456
