### ISSUE TITLE
[OJS][OMP] Interrupted submission ends up in Incomplete state with no way to advance

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1298]
On both platforms, against `HEAD`, something has gone wrong with a submission. (We didn’t note the details at the time, as the problem wasn’t immediately apparent.) Returning to the system, the user’s dashboard shows, under “My Authored,” a submission with the status “Incomplete.” Following the link brings the user to the Submission tab. However, there’s no evident way to take any action on the item, including submitting it or otherwise moving it along; it appears stuck in limbo forever.

**Comment by crism** [comment]
The interrupted submission has `status` of 1 (as do other new submissions), but a `submission_progress` of 4 (whereas others are 0).

**Comment by asmecher** [comment]
@crism, the `submission_progress` <> 0 indicates that OMP doesn't think the submission has been completed fully. The "Incomplete" link should bring you back to the submission process at the stage where the user stopped. I've tested it locally and it looks OK; can you double-check that you've got a fresh checkout of both app and pkp-lib? Also try `rm cache/t_compile/*.php`.

**Comment by crism** [comment]
@asmecher, the link does bring us back to that stage… but then there’s nothing apparent to do. What should we be expecting to see?

**Comment by crism** [comment]
Maybe it’s because the submitter is also a journal editor? I get the Submission tab; Submission files (with one file listed); Pre-Review Discussions (with no items). I can upload additional files; I can add participants; I can add a discussion. I can edit the metadata and schedule the article (in OJS) for publication, but I can’t complete the submission.

**Comment by asmecher** [comment]
What stage do you get returned to? Is there now "submit" / "continue" button at the bottom?

**Comment by crism** [comment]
When the submitter/editor clicks on the “Incomplete” link, he is taken to the editor’s workflow, in the Submission stage. There are files, but no apparent way to advance.
![incomplete_submission](https://cloud.githubusercontent.com/assets/1933900/13994344/52ce4a92-f0f2-11e5-91f5-8fe3289d6693.png)

**Comment by asmecher** [comment]
Ah, they should be taken back to the author's submission area instead. That's something that should always happen when `submission_progress <> 0`.

**Comment by crism** [comment]
@asmecher, exactly. I haven’t delved into the code yet, though.

**Comment by asmecher** [comment]
OK, I'll take a look.

**Comment by asmecher** [comment]
@crism, could you verify that the above commit (now in pkp-lib) resolves this for your example?

**Comment by crism** [comment]
@asmecher, that seemed to work. Fast work, thanks!

**Comment by asmecher** [comment]
Great, thanks!
