### ISSUE TITLE
[OMP] Check exposure of Reviewer's Attachments in Author Dashboard

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1300]
There's a Reviewer's Attachments grid in the author dashboard. I noticed that no files appeared here until the editor selected Send to External Review, and selected the files from the Reviewer's Attachments grid in the editorial workflow.

My understanding is that the selection of files in Send to External Review is for the editor to forward files onto the next stage. Should these files get exposed to the author?

I'm thinking there's a high probability that reviewer identities will get leaked this way.

**Comment by bozana** [comment]
There was the requirement from SI to allow editors to upload an anonymized review file and to be able to send that file to the authors, s. https://github.com/pkp/pkp-lib/issues/788. I.e. the editor should always take care about the blindness of those files send to the author. I am not sure if External Review should be treated in the same way as the other editor's decisions, but I believe it could.

**Comment by asmecher** [comment]
It's currently implemented that way on purpose, and editors will have the chance to revisit their decisions before editors are assigned and notified and thus get access to files. And editors can also limit review assignment files to a specific subset. I'd suggest leaving this as is for OMP 1.2, but watching out for feedback in case it is a problem. (FYI, @stranack.)
