### ISSUE TITLE
Reload Default Email Templates misses deleted templates and deletes plugin data

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1303]
The function `reloadDefaultEmailTemplates()` is intended to pull the email templates back in from XML to the database.
https://github.com/pkp/ojs/blob/ojs-dev-2_4/pages/admin/AdminLanguagesHandler.inc.php#L189-L213

It incorrectly clears template default data from `email_templates_default_data` for plugin-installed emails which is is not prepared to restore.

It also does not reload the names of default templates which have been deleted or missed in `email_templates_default`.

**Comment by ctgraham** [comment]
I think this issue can be closed based on the above merges.

**Comment by asmecher** [comment]
Thanks!

**Comment by ctgraham** [comment]
Because of the buggy behavior of the previous code, we might want to cherry-pick this to stable_2_4_8 for 2.4.8-1.

**Comment by ctgraham** [comment]
Oooh, oooh, @asmecher, pick me, pick me!  (to stable-2_4_8).

**Comment by asmecher** [comment]
Agreed. Cherry-picked!
