### ISSUE TITLE
Notification emails are generally Journal specific, but sent from the Site level.

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1307]
See http://forum.pkp.sfu.ca/t/notification-emails-reply-to-principal-contact-of-site-administrator-but-not-principal-contact-of-the-journal/9455

In OJS 2.4, It is confusing for readers (and for journal managers) to have the reply-to field set to the Site Admin, when the messaging is typically journal related and initiated by the journal manager.

Using the `$notifcation`'s `$context` to get the Journal Manager should be trivial.

**Comment by asmecher** [comment]
@jnugent, this one too.

**Comment by jnugent** [comment]
This looks great!  @asmecher please merge. Unless I should :)

**Comment by asmecher** [comment]
All yours, @jnugent!

**Comment by jnugent** [comment]
merged with great justice.

**Comment by asmecher** [comment]
http://old.he-man.org/cartoon/cmotu-pop/powerpose1.jpg
