### ISSUE TITLE
Email log reflects misleading "From" address

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1311]
In OJS 2.4.x, after SPF enhancements, the emails are still logged in `email_log.from_address` with the actual "From" address.

This causes the log to lose a level of specificity, as all emails will be sent from the same sender now.

Either we should add the reply_to to the `email_log` and log the reply-to address, or the `from_address` field should reflect the reply-to instead of the actual SMTP From after SPF enhancements.

Thoughts?

**Comment by asmecher** [comment]
Good spotting. Yes, I think the log should record reply-to/on-behalf-of (depending on what shakes out for best SPF practices in the next release). @jnugent, let me know if you weren't expecting to own the subject!

**Comment by jnugent** [comment]
I think the reply to address would be fine. Regardless of what we do for SPF, we have been including a reply-to for the contact that spawned the mail.   We don't munge reply-to, ever, AFAIK.  If we use it, we're safe from configuration setting switches that may alter other fields.  We'd at least be consistent.

**Comment by ctgraham** [comment]
Superseded by https://github.com/pkp/pkp-lib/issues/1433
