### ISSUE TITLE
[OMP] Update pt_BR locale of OMP

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1317]
* provide updated translation
* complete translation (`master` branch)

see https://pkp.sfu.ca/wiki/index.php?title=OMP:_Portuguese_(pt_BR)

**Comment by asmecher** [comment]
@mtub, does merging the above PR make this ready to close?

**Comment by mtub** [comment]
No, there's more coming soon (pkp-lib + maybe missing keys).

**Comment by asmecher** [comment]
Closing for OMP 1.2 -- all merged.
