### ISSUE TITLE
Counter plugin throws error for old PHP version

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1326]
http://forum.pkp.sfu.ca/t/blank-page-on-manager-plugins-ojs-2-4-8/10448/2

User reports a "blank page" when running under PHP 5.2.9.  I replicated at least the warning messages, though not a PHP fatal.

**Comment by asmecher** [comment]
It's going to be so thrilling to launch OJS 3.0, which requires at least 5.3.x and means we've been able to tear out a tremendous amount of compatibility cruft.
