### ISSUE TITLE
Update ReCAPTCHA support for API v2

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1327]
See https://github.com/google/recaptcha and http://forum.pkp.sfu.ca/t/recaptcha-v2-for-ojs

**Comment by NateWr** [comment]
@asmecher Did this not get resolved on release day? https://github.com/pkp/pkp-lib/commit/76ec7e5d7c075c39b46fa6d2bf4743aa167bc5b0

**Comment by asmecher** [comment]
Yes, as part of https://github.com/pkp/pkp-lib/issues/1775, thanks!
