### ISSUE TITLE
Autocomplete doesn't work well with categories

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#1330]
It's not possible to have something like an opt group for the autocomplete suggestions. See spotlight form, typing for something that matches a series and a monograph name, for example. You will be able to select what should be the category name.

Actually there is a way to extend the jQuery autocomplete plugin and implement something like that, see here: https://jqueryui.com/autocomplete/#categories

I tested and it seems it's not working with items defining values, so I am leaving this for later.

**OMP 3.1**

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
