### ISSUE TITLE
Application-specific language in pkp-lib

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1332]
There are still locale keys in the shared library, pkp-lib, containing language specific to PKP applications. In most cases, it's OJS language that has slipped into the library. Opening this issue to track these keys. Will update the list, feel free to add.

Some of these might need an application-agnostic update, other keys might better be placed in an application's repository.

**Comment by mtub** [comment]
- admin.scheduledTask.downloadLog

**Comment by asmecher** [comment]
@mtub, would you like me to tackle these and summarize the resolution for each?

**Comment by mtub** [comment]
Yes, this is exactly what I was hoping for ;) - let's just update the list until everything has been resolved. Thanks, @asmecher.

**Comment by asmecher** [comment]
OK, scheduling for 3.0 -- it won't be an issue for OMP 1.2.

**Comment by asmecher** [comment]
@mtub, I've dealt with all the ones listed so far. Do you expect to turn more of these up in the near future? If so, let's leave this issue open; otherwise, let's close it.

**Comment by mtub** [comment]
Thanks, @asmecher. Will close the issue. There will be more in the future, but not of the same kind: I guess we still have to deal with strings that, in en_US, match both journal and book operations, but lack proper translations that can be used both in OJS and OMP. Let's defer that to the future.
