### ISSUE TITLE
[OJS] issue cover settings save inappropriate null-locale values, causing PHP scalar errors

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1336]
With `HEAD` of OJS, I get frequent error log messages of the sort:
```
Cannot use a scalar value as an array in .../lib/pkp/classes/core/DataObject.inc.php on line 133
```
With additional debugging messages added, this appears to happen from a variety of subclasses of `DataObject`, including `Issue`, `Journal`, and `User`.

Looking at the code, it seems possible that `$this->_data[$key]` is not initialized before attempting to set `$this->_data[$key][$locale]`. The whole method looks a bit off; the case that `$locale` is `null` seems to be considered in two different places (though only one will actually run). Given that this is core functionality, I’m a little hesitant to hack it up, but it seems to merit review.

**Comment by asmecher** [comment]
That code is as old as the hills, which means both 1) I'm unsure why it would suddenly start complaining (perhaps PHP's error/warning reporting got stricter, which does happen sometimes) and 2) it probably is due for a review. I'll take a peek sometime soon.

**Comment by crism** [comment]
@asmecher, I suspect that something in OJS initializes itself differently than OMP stuff does, since OMP has no problems in this respect. The code tries to set `$this->_data[$key][$locale]` naïvely; that suggests that it expects someone else to have set `$this->_data[$key]` at some point. I’m trying to figure out where the difference lies between classes that work and ones that don’t.

**Comment by asmecher** [comment]
Hmm, there was another comment you made on this or a very similar issue within the last few days, that used error_log to figure out the index being used -- but I can't spot it now. Do you have it handy?

**Comment by crism** [comment]
Yes, sorry, I should have referenced http://forum.pkp.sfu.ca/t/cannot-use-a-scalar-as-an-array/10488/5 in the initial report.

**Comment by asmecher** [comment]
@crism, can you dump out the DB entries for one of the badly-behaved settings?

**Comment by crism** [comment]
The `issues` table:
```tsv
issue_id	journal_id	volume	number	year	published	current	date_published	date_notified	last_modified	access_status	open_access_date	show_volume	show_number	show_year	show_title	style_file_name	original_style_file_name
1	1	1	1	2016	1	1	2016-02-22 15:09:35	NULL	2016-03-09 15:48:18	1	NULL	1	1	1	1	NULL	NULL
```
The `issue_settings` table:
```tsv
issue_id	locale	setting_name	setting_value	setting_type
1		hideCoverPageArchives	1	int
1		hideCoverPageCover	1	int
1		showCoverPage	1	int
1	en_US	coverPageAltText		string
1	en_US	coverPageDescription		string
1	en_US	description	<p>Testing an electronic issue of Media-N.</p>	string
1	en_US	hideCoverPageArchives	0	int
1	en_US	hideCoverPageCover	0	int
1	en_US	showCoverPage	0	int
1	en_US	title	Erasure	string
```

**Comment by asmecher** [comment]
That `null` value for `hideCoverPageArchives` is a problem -- it should be a localized setting. I suspect that's going to be a typical cause of these types of messages.

**Comment by crism** [comment]
OK—are there not supposed to be non-localized default values for localizable settings?

**Comment by asmecher** [comment]
No, if there's a default it'll be specified in localized form (see `registry/journalSettings.xml` for examples), or the setting will be empty (no DB entry) until the settings form is saved.

**Comment by crism** [comment]
And in any case, `hideCoverPageArchives` has been localized since pkp/ojs@5c8da1bf3c1f85337ca4e165d85267cc42a6f766… So how did the null values get in there?

**Comment by crism** [comment]
Looks like a problem with installation/configuration, then, not with operation. I’ll poke in that direction…

**Comment by crism** [comment]
Interestingly “Do not display…” is _checked_ in the form, meaning the database value should be true. It’s `1` for the null locale, but `0` for `en_US`, meaning the null value is the one being honored…

**Comment by crism** [comment]
Yeah, something is busted, but I can’t find it in a careful trace. I deleted the no-locale version of `hideCoverPageArchives`, then visited the issue cover tab; hide is set to true, saved it as-was, and now the no-locale `hideCoverPageArchives` is back.

**Comment by crism** [comment]
More fun with error log messages:
```
CoverForm::execute():121: hideCoverPageArchives from getData() is: Array\n(\n    [0] => 1\n)\n, referer: .../index.php/mediap/manageIssues
CoverForm::execute():127: hideCoverPageArchives before setHideCoverPageArchives() is: Array\n(\n    [0] => 1\n    [en_US] => 0\n)\n, .../index.php/mediap/manageIssues
```
This is when saving the cover tab, _after_ deleting the no-locale setting of `hideCoverPageArchives` from the database, and clearing the data cache. I think maybe the form template doesn’t properly handle this value (despite the `multilingual=true`).

**Comment by crism** [comment]
The form data includes `coverPageAltText[en_US]` and `coverPageDescription[en_US]` as parameters, but just `hideCoverPageArchives` and `hideCoverPageCover`. It seems like those latter parameters are not properly internationalized. Where’s the breakdown?

**Comment by crism** [comment]
My best guess now is that this actually has to do with how Smarty templates get processed when checkboxes are allegedly multilingual. A survey of my database shows no apparently inappropriately no-locale settings values, except three for `issue_settings`, all Boolean, with checkbox controls.

**Comment by crism** [comment]
Indeed, when I delete the offending no-locale settings from `issue_settings`, all of my PHP warnings go away—unless I save the cover settings for an issue again, in which case they start snowing my error log again. Changing the bug title to reflect this.

**Comment by asmecher** [comment]
Ah, yes, you've hit the nail on the head: the form builder vocabulary code that we use to standardize (somewhat) form elements doesn't support multilingual checkboxes. We discussed how to support these and decided that they were simply a bad idea, so we need to review where the code expects them to behave and change the controls used. These elements are likely hold-overs from OJS 2.x.

**Comment by bozana** [comment]
@asmecher, @NateWr, @crism, could this issue be closed with the recent changes from Nate -- now that cover images are not localized any more... ?

**Comment by crism** [comment]
This specific problem does seem to have gone away, due to wiping out these settings. I’ll keep an eye out for other manifestations…

**Comment by bozana** [comment]
May I then close this issue and if something else pops up, a new issue can be opened?

**Comment by asmecher** [comment]
For anyone else who hits this, there are further debugging instructions at https://forum.pkp.sfu.ca/t/cannot-use-a-scalar-as-an-array/10488/19.
