### ISSUE TITLE
Can't get OJS to install

### ISSUE THREAD

**Issue by luandro** [pkp/pkp-lib#1339]
A few months ago I got the OJS system to successfully install on my stack (PHP 5.6, MariaDB, Nginx, Ubuntu 14.04). But it suddenly stopped working, and now I can't re-install it, not even a fresh install.

I get to the install page: `example.com/index.php?journal=index&page=install`. But when clicking the "Install Open Journal Systems" button, and get redirected to `example.com/index.php?journal=index&page=install&op=install` I get a 500 error.

I've done the installation steps (giving 777 permission to uploads, cache, public and config.inc.php) many times, and even changed my virtual machine. No luck, any help?

**Comment by asmecher** [comment]
@luandro, could you post on our support forum at http://forum.pkp.sfu.ca? That's the best way to get support, and if it turns out to be a bug, we'll take care of channeling it back into the issue system.
