### ISSUE TITLE
[OJS] issue TOC grid fails with fatal error

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1342]
Against `HEAD`:
```
PHP Fatal error:  Call to undefined method PublishedArticle::getSequence() in .../controllers/grid/toc/TocGridHandler.inc.php
```
The correct method is `getSeq()`.

**Comment by crism** [comment]
Ugh… usage is all over the place in terms of `getSeq()` _vs._ `getSequence()`. Any suggestions on which direction to fix this?

**Comment by asmecher** [comment]
Both are at play in the OMP master codebase (which we're working hardest on ATM), and overall living happily in coexistence -- though I'd suggest we standardize after OMP 1.2 comes out and before OJS 3.0 does. FYI, OMP 1.2 is going to occupy almost all my attention for the next week or two, but thereafter I'll be getting back to the OJS master branch stuff you're filing. If you're finding it too unstable, one option would be to give the team a chance to finish 1.2 and follow up on some of this afterwards. But if you're raring to continue and don't mind us being temporarily distracted, please do -- it's much appreciated.

**Comment by crism** [comment]
The ubiquity of various classes’ `getSeq*()` makes it very difficult to track all the usage. I’ll change this one call to match the method name, rather than risk changing the method.

**Comment by crism** [comment]
Oh, dear… the call is actually being made on whatever is passed to `TocGridHandler::getDataElementSequence()`… which might not always be a `PublishedArticle` instance. Hrmph.

**Comment by crism** [comment]
`Plugin` and its subclasses were consistent about `*Seq()`; I’ve left them alone. However, `DataObject` subclasses were variously using `*Seq()` and `*Sequence()`, which is a problem for generic things like grid handling. I’ve standardized all of them on `*Sequence()`. I’ll test locally before sending pull requests, but if anyone else wants to look this over, please do—I recognize it’s potentially disruptive (though surprisingly little changed in [OMP](https://github.com/pkp/omp)).

**Comment by asmecher** [comment]
Thanks, @crism; I'll leave these open until OMP 1.2 is out, then give it a proper look.

**Comment by asmecher** [comment]
Thanks, @crism, it's merged. FYI, you can cause the Travis CI tests to run with a lib-pkp checkout from your own branch in cases where both the application and the library need modifications; see: https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors#PKP_library_submodule_changes

**Comment by crism** [comment]
Thanks for the merge, and the Travis tip, @asmecher!
