### ISSUE TITLE
OMP Help Panel integration for OMP 1.2

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1344]
This issue is just for tracking the following PRs against the OMP 1.2 milestone:

https://github.com/pkp/pkp-lib/pull/1343
https://github.com/pkp/omp/pull/266

The original issue which isn't pegged to OMP 1.2 is #1032.

**Comment by asmecher** [comment]
Those are both merged in via my own forks of those branches. See [this comment on issue 1032](https://github.com/pkp/pkp-lib/issues/1032#issuecomment-206482412).

**Comment by asmecher** [comment]
@NateWr, this looks fabulous. I can see lots of room for more content links (e.g. the Catalog Entry tabset is pretty high on the list) but as a content and content delivery baseline for 1.2 we're on very good footing. I'll close this entry for now, but will update the UI/UX checkout install and let @stranack know when that's done in case he wants to review it.

**Comment by NateWr** [comment]
Just a note to say I did a quick look over everything in master and it looks like it's all in place and working well. :+1:

**Comment by asmecher** [comment]
This is great -- we've struggled with this for many years and it finally feels like it's done right.
