### ISSUE TITLE
Plugin authorization

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1346]
Admin user cannot use plugin settings function on the administration > settings > plugins page, if the plugin is context specific. S.: https://github.com/pkp/omp/blob/master/classes/security/authorization/internal/PluginLevelRequiredPolicy.inc.php#L47-L49. Is this intended to be so? If so:
The (not translated) message "##user.authorization.pluginLevel##" appears, because it is in the manager.xml locale file, s. https://github.com/pkp/omp/commit/d5a7da5d44a41679802fb73d078d4cebe1b8a72d. So maybe it should be moved to the locale.xml or LOCALE_COMPONENT_PKP_MANAGER should be considered somewhere?
On the manager settings > website > plugins page, the site-wide plugins are not listed at all, thus I don't know when the manager could access those plugins at all?
What is/would be the right/indented solution for the plugin management and authorization?

**Comment by asmecher** [comment]
Can you check the URL to see if that area is served up with a context, or whether the context path is `index`?

**Comment by bozana** [comment]
It is on this URL: http://.../index.php/press1/admin/settings i.e. with context path. It is the Administration area > Settings > Plugins.

**Comment by asmecher** [comment]
I couldn't reproduce this, @bozana, but I'm guessing you've removed the Manager user group assignment the administrator usually gets? If so, I'll defer this to post-1.2.

**Comment by bozana** [comment]
This is not the case for OJS 3 -- there is no administration > settings page i.e. all plugin settings are under settings > website > plugins, thus removing OJS label and milestone from this issue...

**Comment by bozana** [comment]
Hmmm, the same for current OMP master... so closing the issue...

**Comment by asmecher** [comment]
Are the site-wide plugins accessible somewhere or did those get lost?

**Comment by bozana** [comment]
Yes, they are accessible for admins on the normal settings > website > plugins page
