### ISSUE TITLE
User Import/Export Issues

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1347]
- [x] a) the path element for user_group element should be removed (s. https://github.com/pkp/pkp-lib/commit/89fa15d55b47580457207f1edd4e91836414f74e) -- XML validation expects it at the moment. (PR OMP: https://github.com/pkp/omp/pull/267) (PR OJS: https://github.com/pkp/ojs/pull/818) (PR OMP, OJS: https://github.com/pkp/pkp-lib/pull/1348)
- [x] b) plugins.importexport.users.uploadFile key is missing (PR OMP: https://github.com/pkp/omp/pull/267) (PR OJS: https://github.com/pkp/ojs/pull/818)
- [x] c) uploaded import file cannot be found, the message above is the result of the import (PR OMP: https://github.com/pkp/omp/pull/267) (PR OJS: https://github.com/pkp/ojs/pull/818)
- [x] d) "Export All Users" leads to 404 error (PR OMP, OJS: https://github.com/pkp/pkp-lib/pull/1348)
- [x] e) if the import file is not valid, result message is the same as if the import was successful (PKP-LIB PR: https://github.com/pkp/pkp-lib/pull/1711) (OJS PR: https://github.com/pkp/ojs/pull/966) (OMP PR: https://github.com/pkp/omp/pull/319)

**Comment by bozana** [comment]
A better validation error reporting is required (s. e) above), but this can be deferred for OJS 3.0.

**Comment by asmecher** [comment]
Thanks! Does any of that OMP PR need to be ported to OJS?

**Comment by bozana** [comment]
@asmecher, here the last PRs in this issue: 
OJS PR: https://github.com/pkp/ojs/pull/966
OMP PR: https://github.com/pkp/omp/pull/319
THANKS!!!

**Comment by asmecher** [comment]
Both merged, thanks, @bozana! Is this ready to be closed?
