### ISSUE TITLE
CSV Import/Export Plugin

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1352]
The CSV Import/Export Plugin in OMP doesn't work. How is it supposed to work?

**Comment by asmecher** [comment]
Are you trying via the web interface? That's not implemented (yet); it's currently command-line only.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
