### ISSUE TITLE
[OJS] Navbar user home should stay in journal context for single journal installs

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#1353]
Check site settings for journal redirect, similar to conditional display of "My Journals" in user block.

**Comment by asmecher** [comment]
Thanks for the reminder, @mfelczak -- looks good. Can you cherry-pick this to ojs-dev-2_4 too?

**Comment by mfelczak** [comment]
Thanks @asmecher, cherry-picked to ojs-dev-2_4: https://github.com/pkp/ojs/pull/821
