### ISSUE TITLE
[OMP] category grid error when reordering empty categories

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1357]
Against `HEAD`, editing the catalog entry for a book, I try to reorder chapters, some of which have no contributors. I get an error message in the log:
```
Call to a member function getSequence() on boolean in .../controllers/grid/users/chapter/ChapterGridHandler.inc.php on line 247, referer: ...
```
That method is:
```php
	function getDataElementInCategorySequence($categoryId, $author) {
		return $author->getSequence();
	}
```

**Comment by crism** [comment]
Ah, no—those headers are for the chapter contributors (though it looks odd if there are none). The proximal bug here is that if a chapter has no contributors, reordering fails when it tries to handle the authors.

**Comment by crism** [comment]
And to correct my original report—this is something that was already `getSequence()`, nothing to do with #1342.

**Comment by beghelli** [comment]
This is not related to OMP, tested and works well. I think I fixed this for OMP but not for OJS, taking a look. Anyway, removing from OMP timeline.

**Comment by crism** [comment]
@beghelli, how is this not related to OMP? I only have a Chapters grid in OMP, not in OJS. This is observable in the `HEAD` of OMP as of this morning.

**Comment by beghelli** [comment]
@crism oups, sure, made a confusion about OJS, sorry. But I can order my chapters and authors correctly. Are you sure your code is up to date?

**Comment by crism** [comment]
It seems to be up to date. What happens if one or more chapters have no authors or other contributors?

**Comment by beghelli** [comment]
:) sorry, you're right, since your first message. Fixing that now, and thanks for watching this so closely.

**Comment by beghelli** [comment]
Done @crism , this should fix it. And sorry again for overlooking your well documented issue. Cheers.

**Comment by crism** [comment]
@beghelli LOL, thanks. I’ll give this a test shortly.

**Comment by crism** [comment]
Confirm this is working.
