### ISSUE TITLE
[OJS] PHP error when saving article metadata

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1359]
Against `HEAD`, testing another issue, I open the metadata for an article, reorder the authors, and save the metadata. I get an error in the log:
```
PHP Warning:  Missing argument 1 for Submission::getCoverage(), .../classes/search/ArticleSearchIndex.inc.php on line 71 and defined in .../lib/pkp/classes/submission/Submission.inc.php on line 624, referer: ...
```
Should probably be `getLocalizedCoverage()`.

**Comment by asmecher** [comment]
Actually, just needed a `null` parameter specified. Fixed.

**Comment by crism** [comment]
Thanks for the quick fix!
