### ISSUE TITLE
Consider articles with no publication date for the Crossref export/registration

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1367]
Currently the articles with a missing publication date are not considered for the Crossref export/registration. 
They should be considered and the issue publication date should be taken instead.

**Comment by bozana** [comment]
@jmacgreg, could you please take a look at/test the commit above?
@ctgraham, would you mind to take a look at it too?
If OK, I'll make a PR...
THANKS A LOT!!!

**Comment by jmacgreg** [comment]
@bozana, I just tested and it works great!! I made sure to try and export articles without publication dates , and can confirm that the issue's publication date was pulled in instead.

**Comment by bozana** [comment]
Thanks a lot @jmacgreg!!! I will then make a PR...

**Comment by ctgraham** [comment]
Why are we requiring the publication date for export to Crossref?  If I'm reading the schema correctly, the `journal_article`'s `publication_date` is not required.
http://doi.crossref.org/schemas/crossref4.3.6.xsd

**Comment by bozana** [comment]
@ctgraham, when I tried to validate without publication_date, my editor complains. Thus I suppose there should be minOccurs="0" if it wouldn't be needed.

**Comment by jmacgreg** [comment]
Pulling in @AhemNason in case he has any thoughts on the matter. IMO, if the issue has a publication date but the article (for some reason) doesn't, we should still include the issue pub date.

**Comment by jmacgreg** [comment]
... and if neither the issue AND the article have a publication date, something has probably gone horribly wrong :P

**Comment by ctgraham** [comment]
Ah, yes.  The absence of the minOccurs implies minOccurs = 1.  My bad.

My last question then is: Are we confident that adding in the issue publication date is better than raising an error to the user regarding the missing data?  This could get messy in a publish-as-you go case, could it not?

**Comment by AhemNason** [comment]
Yeah. This is definitely a relevant issue. It's actually pretty common for the stuff to be put in by the Quick Submit plugin to actually be missing the Issue Pub Date, for example (maybe that's an old problem?). I think it should build out for one or the other in absence. 

It's relevant for dating the backfile too. They need the publication of the article _online_ as well as the publication of the article in general. I've done a manual export before (a few versions ago) where the numbers didn't line up and it would have cost the journal some dollars.

I think you folks have covered all this well here.

**Comment by mtub** [comment]
Frankly, I don't get the importance of the issue publication date. I think it's okay to proceed as suggested for the moment (fall back to issue date), but when thinking about how to redesign this, I'd suggest priority for the article publication date, making this mandatory and don't allow for this to be empty. If journals have a publication date for their issues, that's fine, but the article publication dates are much more important in this online world we live and publish in.

**Comment by asmecher** [comment]
Sorry, once again I've lost track of this issue. @bozana, is the attached PR ready for review/merge? It looks like @jmacgreg has used it; does any of the subsequent conversation require changes? (It doesn't look like it, at a glance.)

**Comment by bozana** [comment]
@asmecher, the PR is ready and no changes are needed, just a general question exists, if we are sure we want to do it this way and not rather raising the error and let the user correct/enter the date. I think we could proceed with the PR and use the issue date, because we are doing the same on other places in the system i.e. it is consistent i.e. the issue date is already in the metadata elsewhere. But we could maybe think about solving this problem in general...

**Comment by ctgraham** [comment]
I still lean toward the opinion that if an Article is missing the Publication Date, this is an error condition that should be flagged in the plugin, rather than substituting in the Issue's Publication Date instead.

I'll solicit feedback from our scholarly publishing folks.

**Comment by asmecher** [comment]
@ctgraham, I fully support that suggestion -- for OJS 3.0. Note that I've already had to re-address the issue of publication dates for OMP 1.2 to get into Google Scholar, and for the moment if a user hasn't explicitly entered a publication date (via ONIX hell) then the content simply won't get indexed. We'll probably need to raise a notification for the user there but my general approach is that we don't want to make assumptions about this going forward.

For OJS 2.x I'm more in favour of consistency with existing usage. But let's set a higher threshold for 3.0 and forward.

**Comment by ajnyga** [comment]
Hi @bozana 
Is this missing from OJS3? I am digging into a case where a journal of ours registered DOIs for old articles they added with the quicksubmit plugin. The issue pubdate is set correctly in the Crossref database, but the article pubdate is showing 1970-01-01 and the article pubdate in OJS is empty meaning that the Crossref export has not used the issue pubdate as suggested above.

**Comment by bozana** [comment]
Hi @ajnyga 
Hmm... Was that article registered using OJS 3? -- I believe this feature is there from the Crossref beginnings in the OJS 3 i.e. since https://github.com/pkp/pkp-lib/issues/383. 
According to the line https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php#L126-L130 it should work correctly, right?
What date exactly is in your DB table published_submissions for that article? -- to try to reproduce it...
