### ISSUE TITLE
[OJS] breadcrumbs have double-escaped HTML

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1373]
Against `HEAD`, the navigational breadcrumbs are doubly-escaped in HTML. For example, a journal has a section called “Editors' Notes”; the source HTML for the breadcrumbs is `Editors&amp;#039; Notes`, which displays as “Editors&#039; Notes.”

**Comment by asmecher** [comment]
This is the master branch, I presume?

**Comment by crism** [comment]
Yes, @asmecher—sorry for not being clear.

**Comment by asmecher** [comment]
Got it, thanks. This looks like a one-off issue; I didn't see other cases of the same problem.
