### ISSUE TITLE
XML Issue/Articles Export Plugin Failure

### ISSUE THREAD

**Issue by eggragator** [pkp/pkp-lib#1374]
I have a strange problem with our OJS system. I am working on migrating our OJS data to a new server, including two journals. The .xml export plugin worked fine for one journal, but not the other. At first I thought it was a size issue, but it persisted after we had increased our limit to 100MB (to exceed the existing journal size). This is the error:
![image](https://cloud.githubusercontent.com/assets/16583545/14510284/56390b4a-0196-11e6-94cf-4f3219561fb6.png)

The only reason I can think of that the export would work for one journal and not the other is if there was some setting or background metadata that was giving it trouble. Whatever the cause, the .xml files the plugin outputs are very slow to open even in a text editor, and fail to upload. Here is a sample of the file when it did finally load in Notepad:
![ojs xml export plugin issue](https://cloud.githubusercontent.com/assets/16583545/14510330/94e3d03c-0196-11e6-9e1c-e801afba56fd.png)

Has anyone seen similar issues before? Our current site is at http://journals.wsulibraries.org
We are trying to migrate from 2.4.6.0 to 2.4.8.0, but that doesn't seem to be the issue since it worked for one of our journals. Any guidance would be appreciated!

Many thanks,
Samuel

**Comment by asmecher** [comment]
Hi @eggragator -- could you post this on our support forum at http://forum.pkp.sfu.ca/? If it does turn out to be a bug, we'll shepherd it back here.
