### ISSUE TITLE
reviewer comments for editor only

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1376]
If there are only reviewer comments for editor, they will not be displayed in review detail. 
PR is coming...

**Comment by bozana** [comment]
PR pkp-lib omp-stable-1_2_0: https://github.com/pkp/pkp-lib/pull/1377
PR pkp-lib omp-dev-1_2: https://github.com/pkp/pkp-lib/pull/1378
PR pkp-lib master: https://github.com/pkp/pkp-lib/pull/1379

**Comment by asmecher** [comment]
That's a respectable first bug for OMP. Thanks!
