### ISSUE TITLE
Support qualifications for DC identifiers in OAI interface

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1386]
The OAI DC interface lists identifiers from the publication format's metadata, but without qualifiers to indicate what type of identifier is present. Add some way to distinguish.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
