### ISSUE TITLE
[OJS] Adding editor from select review page not logging email

### ISSUE THREAD

**Issue by alonsoj** [pkp/pkp-lib#1388]
When adding an editor from select review page (/journal/editor/createReviewer/article_id) and selecting "**Send the user a welcome email containing their username and password.**" option, OJS sends an email to the  new editor but not logs the email sent at the **Email Log** section.

**Comment by asmecher** [comment]
@alonsoj, that message is not considered "article-related" so isn't tracked in the article's email log; also, we would prefer to avoid logging messages that include passwords somewhere that is visible to others.

**Comment by alonsoj** [comment]
@asmecher, and how can i know if the message has been sent properly?

**Comment by asmecher** [comment]
@alonsoj, I'd suggest checking your server's mail sending log. The location will depend on your server's specific setup.

**Comment by alonsoj** [comment]
@asmecher, yes, but our editors want to check it for themselves

**Comment by asmecher** [comment]
Can you describe the requirement a little further? Are Editors suspicious that OJS isn't sending emails when they press the Send button?

**Comment by alonsoj** [comment]
I have tested myself and if in some cases the mail doesn't arrive to the reviewer (maybe mail server down). If the editor is not sure that the mail arrives to the reviewer I think this option lacks some of its usefulness (quick reviewer assignment).

**Comment by asmecher** [comment]
@alonsoj Yes, I thought that might be the case. We've been working on better conforming to mail server's expectations around SPF (Sender Protection Framework), which in the past has caused some mail servers not to deliver some messages. FYI, even if these messages were logged in the article's email log, it's not a guarantee that the message was received by the reader; mail servers will accept the message from OJS and then silently discard them if they don't conform to the server's SPF rules.

We're talking about SPF rules internally and will likely have a change to our mail policies in time for the next release, OJS 2.4.9, which will be scheduled shortly.
