### ISSUE TITLE
Allow protocol-relative URLs in compiled CSS

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1391]
Otherwise the protocol (e.g. http://) gets compiled into the CSS, and requests via a different protocol (e.g. https://) can cause warnings.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/1392

@jmacgreg, this causes cached CSS to use protocol-relative URLs.

I checked the Google CDN URLs and the OMP 1.2 release already supports protocol-relative URLs. If you plan to upgrade to OMP 1.2, it'll be fixed there; if it'll take a while, you can just disable CDNs in `config.inc.php` to cause OMP to use local copies (which will be fetched according to the user's protocol).

I've assigned the CSS PR to @beghelli, so once he's reviewed it I can commit it around and, if you plan to take awhile upgrading to 1.2, back-port to OMP 1.1.1.

**Comment by jmacgreg** [comment]
Hi Alec, thanks - I've currently modified some cache files (not a permanent solution, obvs), but will look at the CDN flag as well. They'll be upgrading to 1.2 shortly though, so rather than forget that we enabled that, I may just let this be. Thanks!

**Comment by beghelli** [comment]
@asmecher  oups, didn't meant to close, just merged the pull request.

**Comment by asmecher** [comment]
Actually, that's fine with me! Thanks, @beghelli.
