### ISSUE TITLE
[OJS] Can't upload new Issue Galley file

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1395]
When the Upload button is clicked, the modal form attempts to submit.

Issues > (any issue) > Edit > Issue Galleys > Create Issue Galley

**Comment by asmecher** [comment]
@NateWr, I tested this and it worked for me. I don't have an "Upload" button anymore (since the plupload rewrite you did); I only have "Upload File", which selects and then uploads. What browser are you using? Any chance you've got something old hanging around your composer.json or template cache?

**Comment by NateWr** [comment]
Maybe it was old cruft or maybe it was #1411 that I was running into. Anyway, with a mouse it works fine for me.
