### ISSUE TITLE
[OJS] Consolidate information entry into fewer fields

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1397]
@asmecher Do you think we could make some progress for OJS 3.0 on consolidating all of these different textareas we have for different journal info into a couple basic pages? Here's a list of the data entry we have that feeds into the frontend pages:

- Settings > Journal > Masthead > Journal Description
- Settings > Journal > Masthead > Masthead
- Settings > Journal > Masthead > Journal History
- Settings > Journal > Masthead > Mailing Address
- Settings > Journal > Contact
- Settings > Journal > Policies > Privacy Statement
- Settings > Journal > Policies > Focus and Scope
- Settings > Journal > Policies > Open Access Policy
- Settings > Journal > Policies > Publication Scheduling
- Settings > Journal > Guidelines > Author Guidelines
- Settings > Journal > Sponsor > (Lots of stuff)
- Settings > Workflow > Production (can this be removed?)
- Settings > Website > Archiving > LOCKSS License Description
- Settings > Website > Archiving > CLOCKSS License Description

I think we could have three textareas for About the Journal, Editorial Team (Masthead) and Submissions.

**About the Journal** could have checkboxes for whether or not to automatically add the contact information and mailing address, and then would replace the following textareas:
- Settings > Journal > Masthead > Journal Description
- Settings > Journal > Masthead > Journal History
- Settings > Journal > Masthead > Mailing Address
- Settings > Journal > Policies > Privacy Statement
- Settings > Journal > Policies > Focus and Scope
- Settings > Journal > Policies > Open Access Policy
- Settings > Journal > Policies > Publication Scheduling
- Settings > Journal > Sponsor > (Lots of stuff)
- Settings > Website > Archiving > LOCKSS License Description
- Settings > Website > Archiving > CLOCKSS License Description

**Editorial Team** can do what it already does, just loading the Masthead entry:
- Settings > Journal > Masthead > Masthead

**Submissions** can be left largely alone, however I think we could move Author Guidelines into the Settings > Workflow > Submission area and get rid of the Settings > Journal > Guides tab.

**Comment by asmecher** [comment]
@stranack, what do you think?

@NateWr, not a good argument not to do anything, but just FYI: we did about 4 setup re-orgs on OMP 1.0 (which largely resulted in the current not-thrilling structure) and it's going to be hard to get enthusiastic about a fifth. Unless it's alcoholic.

**Comment by stranack** [comment]
I like this idea of simplifying these settings.

**Comment by asmecher** [comment]
I can handle it. Let's talk during the next call or, if there's an opportunity, during the sprint.

**Comment by NateWr** [comment]
Definitely a good candidate for a drunken pull request event.

**Comment by NateWr** [comment]
How are the Journal Initials and Journal Abbreviation used? I noticed "Initials" (which is saved as `acronym`) is used in email templates, but wasn't sure about abbreviation.

![selection_040](https://cloud.githubusercontent.com/assets/2306629/15214737/bb70b3c0-1846-11e6-8743-dd779058e76e.png)

**Comment by NateWr** [comment]
Do we plan to support categories in OJS 3? Any idea how I can enable them?

```
		{if $categoriesEnabled}
			{url|assign:categoriesUrl router=$smarty.const.ROUTE_COMPONENT component="listbuilder.settings.categories.CategoriesListbuilderHandler" op="fetch" escape=false}
			{load_url_in_div id="categoriesContainer" url=$categoriesUrl}
		{/if}
```

**Comment by NateWr** [comment]
Settings > Journal > Policies includes two checkboxes: `requireAuthorCompetingInterests` and `requireReviewerCompetingInterests`. Neither of these appear to be used anywhere that I could find.

The latter is very similar to `reviewerCompetingInterestsRequired` which appears on the Settings > Workflow > Review form.

I'm going to just drop them completely unless someone tells me they're needed, in which case I can move them over to the Settings > Workflow > Review form.

**Comment by NateWr** [comment]
PRs with some big cutbacks:
pkp/pkp-lib#1397
https://github.com/pkp/omp/pull/286
https://github.com/pkp/ojs/pull/837

## Changes

Removed:
- Settings > Journal > Masthead > Journal History
- Settings > Journal > Policies > Privacy Statement
- Settings > Journal > Policies > Focus and Scope
- Settings > Journal > Policies > Open Access Policy
- Settings > Journal > Policies > Publication Scheduling
- Settings > Journal > Sponsor
- Settings > Workflow > Production
- Settings > Website > Archiving > LOCKSS License Description
- Settings > Website > Archiving > CLOCKSS License Description

Moved:
- Settings > Journal > Masthead > Mailing Address has been moved to Settings > Journal > Contact
- Settings > Journal > Guidelines > Author Guidelines has been moved to Settings > Workflow > Submission

Kept:
- Settings > Journal > Masthead > Journal Description is now used as a Journal Summary (potential front-page/sidebar usage)
- Settings > Journal > Masthead > Masthead

New:
- Settings > Journal > Masthead > About the Journal is now a large rich HTML editor where they can put anything they want into the about page on the frontend.
- A new About > Contact page exists. Since About the Journal is going free-form, I thought it might be good to have a separate page.

## Cleanup
I think we could probably remove some more code that's running the grids on the Sponsors tab.

**Comment by asmecher** [comment]
Regarding https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218744117:

The Acronym is used in CrossRef, Refworks, BibTeX, URN and DOI exports, and as a prefix for subjects in email templates.
The Abbreviation is used in OMP in ONIX, but not currently in OJS.

I could maybe argue for a role for both (e.g. "LangSciJ" vs. "LSJ", but wouldn't do it with any enthusiasm. It might be a good idea of we're considering removing one or the other to quickly vet what each external format requires to make sure we're feeding it good data.

**Comment by asmecher** [comment]
Regarding https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218746636:

No, I don't think categories (a la OMP, where submissions get categorized according to a controlled vocab) will be all that useful in OJS. A roughly equivalent feature would be to use keywords as the OJS 2.x tag cloud plugin does, which is probably more useful as it gets automatically organized by existing metadata.

We did have a different feature (also helpfully called "categories") in OJS 2.x, which was a way of categorizing large sets of journals into topics. But I'm not convinced that is worth rewriting, at least for 3.0.

**Comment by asmecher** [comment]
Regarding https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218784807:

> Settings > Journal > Policies includes two checkboxes: requireAuthorCompetingInterests and requireReviewerCompetingInterests. Neither of these appear to be used anywhere that I could find.
>
> The latter is very similar to reviewerCompetingInterestsRequired which appears on the Settings > Workflow > Review form.
>
> I'm going to just drop them completely unless someone tells me they're needed, in which case I can move them over to the Settings > Workflow > Review form.

Agreed, probably best to drop them for now. I believe the reviewer settings are accidental duplicates. The author setting will probably need to be hooked up at some point, but I don't think it's a common requirement so it can be post-3.0.

**Comment by stranack** [comment]
I did have a least one person specifically ask for categories (as exist in OJS 2) to be transferred to OJS 3. They have multiple journals on one installation and find it helpful (especially for categorizing student journals from professional journals).

**Comment by stranack** [comment]
For continuous publishing, categories (as in OMP) could serve a useful purpose in OJS 3. Journals could use a feature much like the Catalogue to organize and display articles on the home page, and in categorized lists. I think it is at least worth considering, even for 3.1.

**Comment by asmecher** [comment]
For continuous publication, let's leave that discussion to https://github.com/pkp/pkp-lib/issues/1407.

**Comment by asmecher** [comment]
@NateWr, it looks like e.g. the copyright notice is no longer displayed but I don't see that in your notes.

**Comment by asmecher** [comment]
@willinsky, could you take a glance at Nate's proposal in https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218823349 for simplifying the setup fields? Some of those are long-standing OJS fields that I think were devised in an attempt to communicate best practices to editors as much as expose journal workings to outside participants.

**Comment by willinsky** [comment]
This looks a great consolidation. I don't see the Copyright Policy, which is one I added rewording to and which we have had reasonable requests about encouraging an explicit posting of it.

**Comment by NateWr** [comment]
Regarding https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218823533 on Acronym/Abbrevation:

I'm fine just leaving it alone.

Regarding https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218828717 and https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218845850:

> We did have a different feature (also helpfully called "categories") in OJS 2.x, which was a way of categorizing large sets of journals into topics. But I'm not convinced that is worth rewriting, at least for 3.0. (Alec)

> I did have a least one person specifically ask for categories (as exist in OJS 2) to be transferred to OJS 3. They have multiple journals on one installation and find it helpful (especially for categorizing student journals from professional journals). (Kevin)

Can I strip out the template code for now and start a list of features that may/may not make it for OJS 3.0 (eg - categories/subscriptions)? It can get a bit confusing having these things littering the template files.

Regarding https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218894834 and https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218935915:

> the copyright notice is no longer displayed

The Copyright Notice appears under Settings > Distribution > Permissions, and this is displayed with each article if the checkbox is selected. This is how it is in current `master` so these PRs don't change that.

![selection_045](https://cloud.githubusercontent.com/assets/2306629/15243972/b6ce02ea-18f6-11e6-9401-359a2249db73.png)

Should there be a general Copyright Policy that we encourage to appear in the About the Journal page? If so, I can add it to the list of recommended content in the field description here:

![selection_046](https://cloud.githubusercontent.com/assets/2306629/15244030/0c8ecc46-18f7-11e6-99ad-cd04af220f93.png)

@willinsky if there's anything in that description that you think should be added/removed/edited, let me know.

**Comment by asmecher** [comment]
On https://github.com/pkp/pkp-lib/issues/1397#issuecomment-218998466:
>> We did have a different feature (also helpfully called "categories") in OJS 2.x, which was a way of categorizing large sets of journals into topics. But I'm not convinced that is worth rewriting, at least for 3.0. (Alec)
>> I did have a least one person specifically ask for categories (as exist in OJS 2) to be transferred to OJS 3. They have multiple journals on one installation and find it helpful (especially for categorizing student journals from professional journals). (Kevin)

> Can I strip out the template code for now and start a list of features that may/may not make it for OJS 3.0 (eg - categories/subscriptions)? It can get a bit confusing having these things littering the template files.

Yes, that's probably the best approach.
> The Copyright Notice appears under Settings > Distribution > Permissions, and this is displayed with each article if the checkbox is selected. This is how it is in current master so these PRs don't change that.
> [...]
> Should there be a general Copyright Policy that we encourage to appear in the About the Journal page? If so, I can add it to the list of recommended content in the field description here:
> [...]

The Copyright Statement and Copyright Notice are different things. The Copyright Notice is a journal-wide statement of policy that authors might want to read before they submit. It should go in About, and may not strictly apply to all articles (e.g. if it's changed over the years). The Copyright Statement is e.g. "Copyright (c) 2016 by Cholmondeley", which gets stamped on the article as the definitive statement for a piece of content, and that one gets displayed with the article.

**Comment by asmecher** [comment]
@willinsky, I thought this was going to be more controversial! Are you OK to accept Nate's proposed changes, or would you like to see them in action first?

**Comment by NateWr** [comment]
@asmecher I've added copyright notice to the list of recommended content for About the Journal.

I've also stripped out all the categories code. I may have gone farther than you wanted here and stripped out too much. Take a look particularly at https://github.com/pkp/ojs/pull/837/commits/19ca02308019cc8e1a2f16c2fae25627168a5ba4.

**Comment by willinsky** [comment]
Of course, I'd love to see them in action, but am feeling that this is an improvement and that less guidance is needed now that in the past.

**Comment by jalperin** [comment]
Regarding abbreviations, they are not being used correctly in the screenshot. Journals do have [formal abbreviations](http://images.webofknowledge.com/WOK46/help/WOS/A_abrvjt.html) that get used at citation time. It's an outdated practice, but was a space saving measure back in the day, and still used by some citation styles.

**Comment by bozana** [comment]
The journal abbreviation is also used in public identifiers (e.g. DOI), as part of the suffix pattern.
Maybe to also consider the information DOAJ is requesting for journals and how to make it easier i.e. guide journal managers to enter those information, s.: https://doaj.org/application/new
I.e., for example: 
14) and 18) URL containing information about APCs and submission charges,
26) URL containing the digital archiving policy,
36) URL for the editorial board page,
38) URL about review policies/process,
39) URL for the journal's Aims & Scope,
40) URL for the journal's instructions for authors
44) URL for the journal's Open Access statement,
49) URL on your site where your license terms are stated,
53) and 55) URL with the information weather author(s) are allowed to hold the copyright and publishing rights without restrictions

**Comment by bozana** [comment]
Ah, sorry, I mean journal initials are used in pub ids, not abbreviation... :-\

**Comment by asmecher** [comment]
New PRs with a fresh rebase and tests fixed:
- https://github.com/pkp/pkp-lib/pull/1463
- https://github.com/pkp/ojs/pull/841
- https://github.com/pkp/omp/pull/289

@NateWr, if you do any further work on this, could you do a hard reset to my branch?

@willinsky, any opinion on https://github.com/pkp/pkp-lib/issues/1397#issuecomment-219676561? I suspect they've based a lot of these requirements directly on OJS.

**Comment by asmecher** [comment]
@NateWr, I've merged this into master for pkp-lib, OJS, and OMP after a little further tinkering with tests. I removed the enabled/disabled flag from the Masthead form -- it was only partially implemented there and that was causing problems. (Generally I favour not putting controls like this in multiple places, so I'm happy to leave it on the Admin's "edit" form.) IIRC this merge was holding you up on other stuff -- thanks for bearing with me through some travel delays!

Closing the issue, unless there was something still outstanding?

**Comment by NateWr** [comment]
:+1: I'll take a look thanks.

**Comment by asmecher** [comment]
@NateWr, @bozana pointed out that many of the plugins still refer to the `publisherInstitution` setting, which these PRs removed.

**Comment by bozana** [comment]
Aaaa... good to know where it is i.e. is not... :-) Thanks!

**Comment by NateWr** [comment]
Where was the field, was it a TinyMCE field, what is it for, what content was meant to go in it, how are plugins using it?

**Comment by asmecher** [comment]
It was on the production stage settings form `templates/controllers/tab/settings/productionStage/form/productionStageForm.tpl`, which got removed entirely; it's going into various kinds of extracts:

- plugins/importexport/doaj/DOAJExportDom.inc.php
- plugins/importexport/doaj/DOAJPlugin.inc.php
- plugins/importexport/crossref/CrossRefExportDom.inc.php
- plugins/importexport/datacite/classes/DOIExportDom.inc.php
- plugins/importexport/pubmed/PubMedExportDom.inc.php
- plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.inc.php
- plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
- plugins/oaiMetadataFormats/rfc1807/OAIMetadataFormat_RFC1807.inc.php
- plugins/oaiMetadataFormats/nlm/OAIMetadataFormat_NLM.inc.php
- plugins/oaiMetadataFormats/marc/record.tpl
- plugins/oaiMetadataFormats/marcxml/record.tpl
- plugins/generic/counter/CounterHandler.inc.php
- plugins/generic/counter/reportxml.tpl
- plugins/generic/webFeed/templates/rss.tpl
- templates/gateway/lockss.tpl
- templates/gateway/clockss.tpl

**Comment by NateWr** [comment]
What is it? The name of the publisher? A description of the publisher?

**Comment by bozana** [comment]
Yes, that was the name of the publisher, I think.

**Comment by NateWr** [comment]
The following PR restores the `publisherInstitution` field and adds it to the Masthead settings.

https://github.com/pkp/ojs/pull/943

I believe this issue can be closed once merged.

**Comment by asmecher** [comment]
Thanks, @NateWr, that's a big one!
