### ISSUE TITLE
PKP PLN check for scheduled_tasks is missing parameter

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1401]
In OJS 2.x dev

See:
https://github.com/pkp/ojs/blob/c28b02f665346256fc733e9448540dc7a6ded6a9/plugins/generic/pln/PLNPlugin.inc.php#L637

Should be:
```
return isset($products['acron']) || Config::getVar('general', 'scheduled_tasks', false);
```

**Comment by ctgraham** [comment]
I think this is ready for merge to dev-2_4 and cherry-pick to stable-2_4_8.

**Comment by asmecher** [comment]
Merged and cherry-picked. Thanks, @ctgraham!
