### ISSUE TITLE
Test RESTful URLs setting

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1402]
It may not currently be working; see http://forum.pkp.sfu.ca/t/clear-restful-urls-in-ojs3

**Comment by crism** [comment]
In fact, the recommended rewrite rules won’t work, since some resources are at `.../lib.pkp/js/lib/jquery/...` _e.g._, and rewriting those to start with `index.php` would fail. So it looks like my rewrite rules are being ignored, but it would just break differently if they weren’t. Hm.

**Comment by crism** [comment]
Except the rewrite rule is being honored when I try to visit a journal directly (as the error message quoted above)… The problem is that Apache is trying to find `index.php/test` instead of dispatching that URL to `index.php`. Yuck.

**Comment by asmecher** [comment]
@crism, what SAPI are you using? mod_php? CGI? FastCGI?

**Comment by crism** [comment]
@asmecher, `phpinfo()` reports “Apache 2.0 Handler” as the server API (this is with Apache 2.4.6).

**Comment by crism** [comment]
I’m finding evidence that this is a known problem with FastCGI. Might it affect `mod_php` too? Using a `PT` flag instead of `L` in the rewrite rules didn’t help…

**Comment by asmecher** [comment]
@crism, the basic litmus test for a rewrite setup is to use a `phpinfo()` script (call it `test.php`). If you can't supply something after the script's name (e.g. `http://.../test.php/something/else/here`), then your PHP/Apache/rewrite config is broken.

**Comment by crism** [comment]
Hmm… no, it comes through in `PATH_INFO`. Something else is going on here, but I’ve back-burnered this for now. This is a cosmetic thing, and if it turns out to be a pain here, I can live without it.

**Comment by asmecher** [comment]
I tested this with mod_php and mod_rewrite on an Ubuntu VM and OJS 3.0 behaves just like OJS 2.x with the settings recommended in docs/FAQ. Closing for now.

**Comment by crism** [comment]
As noted in the PKP forum, the problem is that if OJS is not running in the server root, a `RewriteBase` directive is needed for this to work properly.

**Comment by paulocoghi** [comment]
I have installed OJS 3.1.0-1 with PHP-FPM 7.0 and Nginx. It works perfectly with `restful_urls = Off`.

But, if I configure it with `restful_urls = On` and add the rewrite rules, parts of the page (because the lack of css) don't load.

**Comment by paulocoghi** [comment]
Have someone installed OJS 3 with Nginx and `restful_urls = On` successfully?

**Comment by kaschioudi** [comment]
@asmecher : I dug into this and it doesn't seem related to https://github.com/pkp/pkp-lib/issues/3110.  

My understanding is that PKPRouter relies on `$_SERVER` super global variable to get the path info but that variable is not available on NGINX (cf https://github.com/kaschioudi/pkp-lib/blob/master/classes/core/PKPRouter.inc.php#L149-L179).  

Even though this seems to be a well documented issue with NGINX (https://trac.nginx.org/nginx/ticket/321) I was unable to successfully test it. I added the instructions below to my site config with no luck.
```
set $path_info $fastcgi_path_info;
fastcgi_param PATH_INFO $path_info;
```

**Comment by paulocoghi** [comment]
When possible, I will dig deep into this issue as well.
