### ISSUE TITLE
Redirect to the current page after Login As

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1403]
When the editor uses the Login As link in the Participants grid (e.g., for the author), the confirmation popup comes up, but after hitting OK, you are taken to the editor's Submissions list and you are NOT logged in as the intended user.

**Comment by asmecher** [comment]
@stranack, oops, I solved a user ID bug that was preventing you from performing the "log in as".

There's a second issue here, though: sounds like you're expecting the user to be redirected to the equivalent page in the new user's account (e.g. workflow for that same submission), then back again when they "log out as". That's not an unreasonable expectation but it's not currently written that way. I think it wouldn't take too much time.

**Comment by stranack** [comment]
I think it is fine not to get to the equivalent page. If we can add something like that in the future, great -- but for now, it is OK with that bug fixed.

**Comment by asmecher** [comment]
OK, thanks! Rescheduling for consideration of that latter part.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/4845#pullrequestreview-254777434
- https://github.com/pkp/ojs/pull/2423 (tests only)

**Comment by forgive38** [comment]
PR : 
#4990 for v3.2 with indent corrections.

**Comment by asmecher** [comment]
Thanks, @forgive38!

@defstat, could you please review the PRs here?

**Comment by defstat** [comment]
@forgive38 Just some small changes at the review. 

Could you also add the appropriate commit to the OJS branch in order for the tests to run?

**Comment by asmecher** [comment]
Thanks, @forgive38 and @defstat! Merged and cherry-picked forward to `master`.
