### ISSUE TITLE
OJS 3: Step 4 of New Submission Hangs

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1404]
On step 4 of OJS 3, when the author hits Finish Submission and OK to the popup confirmation, the system hangs. The submission is successfully made and can be accessed by returning to the submission list.

**Comment by asmecher** [comment]
Is this on the UI/UX install of OJS3?

**Comment by stranack** [comment]
Yes.

On 2016-04-22 8:01 AM, Alec Smecher wrote:
> Is this on the UI/UX install of OJS3?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pkp/pkp-lib/issues/1404#issuecomment-213464718>
>

-- 
--
Kevin Stranack, MLIS, MAEd
Learning and Development Consultant
Email: kevin@stranack.ca
Twitter: @stranack
Skype: kstranack
Web: http://stranack.ca

**Comment by asmecher** [comment]
Just chucking a fix in before I disappear and pop up in Montreal -- but this should be fixed now.
