### ISSUE TITLE
Change "Submissions" Link in Reader Interface

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1406]
From the reader interface, the menu under the user profile name includes "Submissions", "View Profile", and "Logout". The Submissions link is chosen to get to the submission list, but also to Issues, Settings, and Tools. Can we broaden that link to something like "Dashboard" -- which is more inclusive of everything found by following that link?

Right now, when directing a user to the "Tools" for example, you must tell them to choose "Submissions", which doesn't really make sense.

**Comment by asmecher** [comment]
I forget whether it was @NateWr or @beghelli? One of the two of you, IIRC, was interested in clarifying the use of "dashboard" and had some concrete ideas.

**Comment by NateWr** [comment]
I think dashboard makes the most sense or all users, but I think our past usage has introduced some confusion around that term. At least, it's my sense that some people only want to call the workflow the dashboard, or don't want to use the word at all.

Ideally it would be short enough to fit on one line in that admin menu, but nothing is coming to mind at the moment.

**Comment by stranack** [comment]
I'd vote for "dashboard". While not perfect, at least it represents a broader concept of what users will get when selecting it. We could then keep an eye on our ongoing usability testing to see if it causes any unforeseen problems.  It is also the term used by Wordpress, which seems to be working for them.

**Comment by stranack** [comment]
On step 5 of the author submission, we are currently providing a link back to the "dashboard". If we decide to NOT go with "dashboard" we need to fix this.

**Comment by asmecher** [comment]
Changing "Submissions" back to "Dashboard" would be a revert of part of https://github.com/pkp/pkp-lib/issues/985. I think "Dashboard" was better, though we did get some feedback (e.g. from FUB) questioning that choice. @beghelli, unless you have any major objections, could you revert that part of issue #985?

**Comment by NateWr** [comment]
Sorry I jumped the gun on this one, but I went ahead and named it Dashboard as part of changes in #1461.
