### ISSUE TITLE
Help button on Production page misplaced

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1408]
The Help link appears correctly on Submission, Review, and Copyediting, but is still displaying below the Participants grid on the Production stage.

http://journals.sfu.ca/uiux/index.php/publicknowledge/workflow/index/32/5

**Comment by asmecher** [comment]
The "help" issue is still open against OJS; what's currently there is a mix of the most recent stuff in lib-pkp and some intermediate stage stuff in ojs. https://github.com/pkp/pkp-lib/issues/1032
