### ISSUE TITLE
Add Discussion Fails for Layout Editor

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1409]
In the Production Stage, the LE has access to the Add Discussion link, is able to fill in the discussion form, and everything appears to work. However, the discussion does not display in the Discussion grid.

http://journals.sfu.ca/uiux/index.php/publicknowledge/workflow/index/32/5

Logged in as  Stephen Hellier

**Comment by asmecher** [comment]
I can't replicate this; maybe it's an older issue? (I updated the install today.) Can you check again?

**Comment by asmecher** [comment]
Seems to already have been resolved; can't duplicate.
