### ISSUE TITLE
Revision process has to be clarified 

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1413]
Revision panel isn't self-explaining. There should be some hints for the authors what to do on the panel...

**Comment by asmecher** [comment]
@henkela, which of our applications are you using, and what version? A screenshot of the panel you're referring to would also help.

**Comment by henkela** [comment]
I'm using OJS (git clone). I tested it with a colleague and it was a bit confusing to know what to do... I reinstalled it on a prduction server and will post a screenshot if it didn't change already.

**Comment by asmecher** [comment]
Would that be the master branch, or something else?

**Comment by asmecher** [comment]
(Closing for lack of feedback)
