### ISSUE TITLE
Implement usage stats visualization at submission public page

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#1417]
https://docs.google.com/document/d/1OomMk0p3nzYj_FWJ7XRsgBepIEVms9deK_4SdL4Excg/edit

**Comment by beghelli** [comment]
Pull requests:
https://github.com/pkp/omp/pull/282
https://github.com/pkp/pkp-lib/pull/1418

**Comment by bozana** [comment]
OJS PR: https://github.com/pkp/ojs/pull/831

**Comment by asmecher** [comment]
Merged! Great to have you all working on this.

**Comment by asmecher** [comment]
(Go ahead and close this if it's ready, @beghelli.)

**Comment by beghelli** [comment]
I would like to implement caching, will try to finish today.
