### ISSUE TITLE
[OJS] Cover images are shown as broken images in other interface languages (2.4.8.0)

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#1419]
Issues that have cover image set in one language show fine only in that language, on the other interface languages it is shown as a broken image link.

Here you can see it: http://seer.fclar.unesp.br/alfa/issue/view/550
Below are the database settings for this issue.
![DB settings for issue](https://cloud.githubusercontent.com/assets/18707781/14867176/b38d7da0-0c9d-11e6-9d2f-aeb033b4cafb.png)

This happens on ALL issues, regardless if it was created before the new OJS version or after.

**Comment by asmecher** [comment]
@luizbgomide, thanks for reporting; please try the patch at https://github.com/pkp/ojs/commit/097dafb14fd460fd7b330fd044f894dc16de6bfa.diff and let me know if it works for you.

**Comment by luizbgomide** [comment]
Fixed!
Thanks for help.
