### ISSUE TITLE
Copyediting: People use Notify in Participants grid to communicate, rather than Discussion grid

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1432]
...but it fails to enter the message in the discussion grid correctly (bug)

**Comment by asmecher** [comment]
FYI, @stranack, this is filed from the usability testing outcomes spreadsheet.

The "Notify" link isn't supposed to create a Discussion, it just sends an email. I have a dim recollection of a conversation about this but can't recall the details. Do you think it would make sense to make Notify instead create a discussion?

**Comment by stranack** [comment]
We should review how people are using the two communication systems and decide from there. Is it confusing to have two methods? Should we get rid of Notify now that we have discussions?

There were a few cases where people were using Notify, but it was breaking the workflow because a file wasn't being made available (Copyeditors to Authors, I believe).

However, if we can ensure that using either communication method would work, then we can avoid making Notify generate a discussion. For example, giving authors access to the Copyedited grid.

**Comment by NateWr** [comment]
I think that we agreed to make Notify use the Discussions system. I don't think it's a good idea to have two separate messaging techniques (from a UI or code perspective).

The issue we ran into is that Notify seems to be more intuitive to people. So we thought it would be good to keep Notify but have it create a Discussion. This would have a knock-on benefit of bringing awareness to the Discussions grid as users would see their messages appear there.

(That's from my recollection of our discussion and maybe that was just my thoughts.)

**Comment by NateWr** [comment]
Alec, I think that there's some scope for a more general solution to how our JS components might talk with each other, perhaps using `SiteHandler` as an event router of sorts. Could be a useful shortcut for this Notify use-case, but also could be handy for our workflow Notifications as well.

Perhaps we could chat about this at some point? There may already be some infrastructure in place. I'm just not so sure about how it works or how it solves the issue that our JS components are being delivered and refreshed on the page at different times.

**Comment by asmecher** [comment]
We do use the SiteHandler as a bespoke message broker in a few places. I've tried to avoid this approach because it loads that handler down with considerations for other widgets, but perhaps it's a good opportunity for a generalized feature if we need a lot of that kind of communication.

The developer who wrote the Javascript framework documented it laboriously; see e.g. here: https://pkp.sfu.ca/wiki/index.php?title=JavaScript_coding_conventions#Strict_Encapsulation_of_Widgets

**Comment by stranack** [comment]
Yes to Notify creating a new Discussion entry.

**Comment by asmecher** [comment]
Partially implemented:
- https://github.com/pkp/ojs/compare/master...asmecher:i1432-fix?expand=1
- https://github.com/pkp/pkp-lib/compare/master...asmecher:i1432-fix?expand=1

This partially solves the problem by creating a new query when the notify tool is used. But it creates a few new problems:

- Some actions in "notify" have workflow implications, e.g. notifying the copyeditor should create a copyediting task. However, manually using queries (discussions) to do the same thing won't create the task. Blurring the line between the two tools might be confusing.
- @NateWr and I were discussing message passing between widgets and a better solution for that is needed here too. Currently I'm reaching out from the notification form, snagging the query grid, and forcing a reload: https://github.com/pkp/pkp-lib/compare/master...asmecher:i1432-fix?expand=1#diff-818bfa23c9a888b80ad3ab78f350c06fR129 If we do a lot of this it risks becoming spaghetti.

**Comment by NateWr** [comment]
@asmecher: Shouldn't a new discussion create a new task for all participants?

In addition to the spaghetti problem, we'll also run into bugs related to race conditions. Everything's coming in async so we can't know that a `#queriesGrid .pkp_controllers_grid` exists when the Notify action is triggered.

My thinking with the `SiteHandler` was that a queries grid could tell `SiteHandler` "I'm responsible for `pkp.add_discussion` events". And then the Participants grid could send an event to `SiteHandler` which said "Here's a `pkp.add_discussion` event with this user attached".

I think we gain two things with this model: 1) if no queries grid exists, we can error gracefully by saying "no handler wants this event". And the user can try again a few sceonds later and, if the grid has loaded, it works fine. We don't end up trying to reference DOM elements which don't exist. 2) We disassociate the strict relationship between events. In theory, one event could trigger actions in multiple handlers. We could rename the discussions grid handler or replace it entirely with a different grid that we wanted to listen to that event.

We also end up with a central registry of events which makes it a little easier to uncover the relationships between handlers.

I haven't yet tested your code out myself, but to touch on the Notify problem more specifically: it looks like maybe you're keeping the Notify form in place, and just triggering an event on the discussions grid after a notify form has been completed and sent. It seems to me like it would be better to short-circuit the Notify workflow completely. Clicking "Notify" in the participants grid could simply emit an event handled by the Discussions grid which says "i want to open a new discussion and add this user to the participants list". That way we delegate all the functionality to Discussions and we don't need to maintain a separate Notify handler. It's just an event emitter.

**Comment by asmecher** [comment]
I'm content with it for 3.0, though there are some unresolved points (e.g. message handling) that need better resolution.

@NateWr, I can't just delegate everything to the discussion grid/handler because there are some concerns in Notify that aren't well handled there yet -- email template selection, notification creation/destruction, etc. Those will need further work and if it turns out they're mobile enough to pull out of the participants grid then so much the better -- but IMO that's post-3.0.

**Comment by asmecher** [comment]
Manually committed in the substantive parts of the changes proposed in https://github.com/pkp/pkp-lib/issues/1432#issuecomment-219175029 for both OJS and OMP master branches. Leaving the rest for consideration.

**Comment by asmecher** [comment]
Deferring, unless someone has a strong opinion.

**Comment by asmecher** [comment]
Yes, excellent, and I haven't been able to think of as good a solution myself (regardless of scope). This isn't something that users are demanding -- though we've had several requests for better integration of custom email templates occasionally -- so I'd rather see us defer this and implement it properly (as you propose) rather than come up with a cranky stop-gap. Deferring.

**Comment by jmacgreg** [comment]
+1 for this being requested multiple times, and +1 for deferring and tackling properly. @NateWr did you want me close #3193 in favour of this? I like your proposed modal above.

**Comment by NateWr** [comment]
@jmacgreg I actually think the other one is probably a better issue for what you want. This one is related to a more isolated technical problem (getting Notify workflow features into the Discussions).

**Comment by asmecher** [comment]
@stranack, this is the issue I was thinking about addressing before we review copyediting and similar processes.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
