### ISSUE TITLE
Copyediting Request Email Template - Replace code with data

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1435]
When the editor uses the Add Participant link to add a copyeditor, and chooses the Copyediting Request template, the resulting template is displaying code rather than the data:

http://journals.sfu.ca/uiux/index.php/publicknowledge/workflow/index/45/4

For example:
{$copyeditorName}:
{$submissionCopyeditingUrl}
 {$copyeditorUsername}

**Comment by asmecher** [comment]
That was caused by out-of-date email templates on the UI/UX install; I've fixed that.
