### ISSUE TITLE
Copyediting Request does not trigger a Task

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1436]
When a copyeditor is assigned, he/she should receive a new Task, right? That doesn't seem to be happening:

http://journals.sfu.ca/uiux/index.php/publicknowledge/workflow/index/45/4

When logged in as mfritz, there is no new task related to this assignment.

**Comment by asmecher** [comment]
Notes from an email that I'm also leaving here, even though it's not quite the right place:

> I found some cruft in PKPStageParticipantNotifyForm.inc.php:
> - _removeUploadTaskNotification and _addUploadTaskNotification can probably be removed
> - If that's the case, then probably NOTIFICATION_TYPE_LAYOUT_ASSIGNMENT and NOTIFICATION_TYPE_INDEX_ASSIGNMENT can go (both code and database)
