### ISSUE TITLE
Element vs Component

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1439]
In the Settings, we refer to these as "Article Components" -- see Settings > Workflow > Components.

In the file grids, we still refer to these as "Elements".

I believe we agreed that Components was the preferred term.

**Comment by asmecher** [comment]
Hmm, could you include a screenshot of where you see Elements? I'm looking in the wrong place.

**Comment by stranack** [comment]
It is used on all of the grids - Submission Files, Review Files, Draft Files, etc. See:
http://journals.sfu.ca/uiux/index.php/publicknowledge/workflow/index/1/3

Screenshot:
https://dl.dropboxusercontent.com/u/9529729/element-label-in-grids.png

**Comment by asmecher** [comment]
I think @NateWr recently removed headers from certain grids, including all the files grids. On my (more current) checkout there are no column titles. Can you confirm, Nate?

**Comment by NateWr** [comment]
Confirmed! File grid headers didn't really say anything meaningful, I felt. Ok change?

**Comment by stranack** [comment]
We did have one suggestion to make the grid columns sortable by clicking on the grid header, but if that isn't something we plan to do, then the change is find with me.

**Comment by NateWr** [comment]
I'd rather encourage use of the filters. Sorting/ordering presents other problem because we may not have all entries visible at one time in some grids, but not others.
