### ISSUE TITLE
Fix tabbing from username to password on login

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1443]

**Comment by asmecher** [comment]
@NateWr, I think this was already filed or mentioned somewhere but I couldn't spot it.

**Comment by NateWr** [comment]
It's mentioned in one my massive list issues (https://github.com/pkp/pkp-lib/issues/639). I flagged this issue in that one but anything urgent probably needs its own issue like this, pegged against a milestone.

**Comment by asmecher** [comment]
Quick fix: I just set the tab index and left the position as it was.

**Comment by NateWr** [comment]
Sorry we can't do that. Tabindex is a no-go for accessibility concerns.
Just assign this to me and I'll figure sonething out

**Comment by asmecher** [comment]
Ah, OK. All yours.

**Comment by NateWr** [comment]
Ok, I've been doing a bunch of work around login/registration (mostly registration) on the back of this issue, in part related to work I want to do for #975.

I've stripped out some more dependencies on the backend JS framework (we're very close to dropping it as a dependency on the frontend!).

I'm also working on improving the registration process in general, and went ahead and took a stab at the complications around roles. We do the following:

- Auto-sign up users to Reader and Author roles for the _current_ context (I think there are some issues with our submission flow if we don't auto-register as author).
- Prompt users with a more understandable opt-in for enrolling as a reviewer.

![ojs-registration](https://cloud.githubusercontent.com/assets/2306629/15333282/f28bf518-1c60-11e6-9138-e05cd2c2143a.png)

And we do a little spin-out for the interests:

![review-spinout](https://cloud.githubusercontent.com/assets/2306629/15333305/0781215a-1c61-11e6-8759-2cef7f86fa31.gif)

That example above shows what it looks like in a multi-journal installation with 10 journals. I'd **really, really** like to not include this on the frontend. I know we've been around the block on this. I believe the previous complaint was from managers who run several journals and want to point a user to a registration form and have them easily opt-in for all the journals.  I have a couple compromises to propose.

- The multi-context role selection will still be available from the user profile page on the backend, and we'll make it easier than it was before to hop over to that after registration (post-registration landing page with quick links).
- We can keep the multi-context registration options on the frontend for the non-context site registration page (`registerSite.tpl`). If a site wants to include those options on the regular registration page, they (or PKP Services) will be able to simply copy the template logic from the `registerSite.tpl` template.

**Comment by asmecher** [comment]
Much improved, but we need to be careful how we refer to reviewer roles. "Internal Reviewer" and "External Reviewer" are just defaults, and they can be renamed, opened and closed for self-registration, etc.

**Comment by NateWr** [comment]
This is actually pulling the role names directly. Thoughts on moving the multi-context role selection into `registerSite.tpl` and the backend only?

**Comment by NateWr** [comment]
Ok, I've dug a bit deeper and I'm now priming the default Reader/Author role assignment in context [from the backend](https://github.com/NateWr/pkp-lib/commit/05214b6609c8bdb7969e639c503ae349dbc4f2eb#diff-4e84768943459d3da90a50abcd8a248bR122). I'd like to discuss how we use the Author role nad whether it might make more sense to change permissions around submissions than to add the Author role (maybe a quick Skype chat or at the dev meeting).

In addition, I've removed the separate templates for `userRegisterSite.tpl` (overall site) and `userRegister.tpl` (journal). They all pump through `userRegister.tpl` and there's just a bit of logic controlling what's visible depending on the context.

When registering for a journal, we get the registration form and the reviewer opt-in with the drop-down interests. No role selection exists for other contexts (users can still do that in their user profile in the backend).

When registering for the site, we get the registration form, the context role selection, and a more appropriate reviewer interests prompt.

Before issuing PRs I need to port over some of these changes to OMP and update the Bootstrap 3 theme as well. But on the whole I think we'll have cleaner, more readable code throughout.

**Comment by NateWr** [comment]
I've got the commits prepared for ojs/omp/pkp-lib. But I suspect we'll have some merge conflicts with #1397 so I'll hold off on issuing PRs until those changes are in and I can re-stage the changes.

**Comment by NateWr** [comment]
Note to self: the tag-it configuration fix in https://github.com/pkp/pkp-lib/issues/1467 needs to be ported over to the frontend.

**Comment by asmecher** [comment]
I think https://github.com/pkp/pkp-lib/issues/1443#issuecomment-220300974 got attached to the wrong bug entry.

**Comment by NateWr** [comment]
No this is the right issue. I kind of took over the issue and turned it into a wider revamp of login/registration, and the `tag-it` component is now initialized in the theme for the frontend.

**Comment by asmecher** [comment]
Ah, OK.

**Comment by asmecher** [comment]
(I've merged in the PRs for issue #1397.)

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/1481
https://github.com/pkp/omp/pull/292
https://github.com/pkp/ojs/pull/846

Done:
- Auto-registers users to Reader/Author role types when registering within context.
- Improves reviewer opt-in and interests selection.
- When registering out of context, provides a list of journals with roles. Pretty heavy-handed but a lower-priority registration area.
- Removes login/registration dependencies on backend JS framework
- Adds `$disableUserReg` to every template so it can be used anywhere we want to put a registration link.
- Defines some new locale strings for registration/login
- Oh yeah, it fixes the tabbing order problem too. :)

Remaining:
- Let's talk about the Reader/Author roles and the submission process. It's a little odd to opt-in users to Author roles and maybe we can find a better solution to the problem.
- I have to port over the fix in #1467 for the tag-it component. It will be easier to do after merge now that I've prepared the PRs.
- I'd still like to do some stuff with the overall submission -> registration -> new submission flow but we'll do that in a different issue. I've abused this one enough. :)

**Comment by NateWr** [comment]
Ok I've fixed the tests that were failing. They were looking for an Author role checkbox to click which no longer exists (it's a hidden field).

However, in OMP some where looking for Volume Editor. Is this an author-type role? Maybe just double-check I haven't caused problems by fixing the tests. https://github.com/pkp/omp/pull/292/commits/e78813168f1443724a6d3578c226058e4951ae0b

**Comment by asmecher** [comment]
There are several author user groups in OMP by default: authors, volume editors, chapter authors, and translators. In the test data, a couple of these are represented.

I suspect that element of testing isn't working, because that role isn't currently allowed for user self-registration.

If there are ambiguous author user groups available for self-registration, a user who starts a submission but doesn't have an author role should be given a list of available. I suggest altering the role configuration in the tests to permit self-registration by Volume Editors, then editing the tests to cause them to select that role.

**Comment by NateWr** [comment]
Hmm, this is at the point of registration, not submission. So I don't think there's any use in offering role selection for Volume Editor at this stage.

Would you rather me re-work this PR to implement what we discussed about role assignment during submission, so that there's no role opt-in during registration (except Reviewers)? I was planning on doing it after this was merged but I can take another crack at this next week if that's easier, then work out the tests from there.

**Comment by asmecher** [comment]
What I'm suggesting is keeping the role selection in the tests, but moving it from the point of registration to the point of submission.

**Comment by NateWr** [comment]
Although having said that, I was plannign on doing that as part of a larger revamp of the submission process, so could drag things out quite a bit...

I suppose the immediate problem is: the tests expect to a user to register as a Volume Editor, but in actuality every user is being auto-registered as Author and Volume Editor (I believe). Will that cause problems for the tests or is it good enough for now?

**Comment by NateWr** [comment]
Ok I see now there's a role selection under Contributors during submission. I can work on adjusting the tests for that next week.

**Comment by NateWr** [comment]
@asmecher Ok, I've tried to update the tests to select the submitter's role during the submission process. However, since I don't have the tests running locally, and I'm not very familiar with the testing platform, I'm not really sure if my selectors are correct:

https://github.com/pkp/omp/pull/292/commits/d4982620fdeffd4967133bf94a90c45488f24476#diff-d4cb414fc50b015543ba2f6ed21ab808R90

I'll keep an eye on the tests to see if they fail and if I'm able to get them working. But I may need some help ironing out the selectors.

**Comment by asmecher** [comment]
OJS seems happy but there's a typo in OMP: https://travis-ci.org/pkp/omp/jobs/133875725

    Parse error: syntax error, unexpected ';' in /home/travis/build/pkp/omp/tests/ContentBaseTestCase.inc.php on line 94

**Comment by NateWr** [comment]
Thanks @bozana!
