### ISSUE TITLE
[UI] Clarify the need to check box when copyeditor uploads revised file

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1446]
Copyediting: When copyeditor uploads revised file, we need to clarify the need to check the box next to the appropriate file. People miss this and it is critical that they do this.

_(Filed from usability testing outcomes.)_

**Comment by asmecher** [comment]
I think this recently got resolved here: https://github.com/pkp/pkp-lib/issues/1260

**Comment by NateWr** [comment]
I'm not actually clear on what the issue was, just wanted to get it filed. @stranack do you know if this is resolved now?

**Comment by asmecher** [comment]
@stranack, pinging you for feedback :)

**Comment by stranack** [comment]
This is resolved.

**Comment by asmecher** [comment]
Great, thanks!
