### ISSUE TITLE
[UI] Improve recipient selection process for new discussions

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1447]
Usability testing outcome:

> Workflow: Recipients in Add Discussion modal is a problem: people fail to add who the message is directed at; confused to see themselves as the default; better to have no one as the default

I suspect we'll get more mileage by styling it a bit like the From/To areas familiar from email clients.

```
From: {user's details entered and uneditable}
To: {recipient list builder, maybe jQuery UI autocomplete like reviewer interests?}
```

**Comment by asmecher** [comment]
IMO the user creating the conversation will frequently, but not always, want to be part of it. Thinking e.g. of a high-level editor who wants to connect e.g. a translator with a copyeditor, but doesn't want to be part of the conversation.

**Comment by NateWr** [comment]
Punting to 3.0.1

**Comment by ajnyga** [comment]
Some of our journals like to have several editors working with submissions. The new discussion feature in OJS3 is of course a great way to communicate between the editors/section editors but starting a new discussion means that you have to add every participant one by one.

What would you think if besides the "Add user" button there would be a "Add group" button, which would add for example all assigned section editors as participants to the discussion? This would save a lot of clicks.

**Comment by asmecher** [comment]
That would be an interesting addition -- would this remain as a single row on the list, or expand out to show all users? I'd suggest expanding to list the users -- that way individuals can be removed, and it's clear exactly who is included. (@stranack and @NateWr.)

**Comment by ajnyga** [comment]
I was also thinking that maybe a "add all" option would work as well. That does include some risks though, I mean if after adding all participants the user fails to remove the unwanted participants.

The way I was thinking that both of these would work (add group, add all) is that instead of adding a row saying something like "Section editors", it would simply add several rows, for example all participants with the section editor role.

**Comment by NateWr** [comment]
Good idea. How many participants do we reasonably expect to be assigned to a single submission? If it's under 10-15, I wonder if it would be quickest just to list all the possible participants so that users can just click to add the ones they want to include.

**Comment by ajnyga** [comment]
I find it hard to believe that in any scenario there would be more than 10. 

I still vote for the group selection option I described above (it could use the current UI), but any solution that helps adding multiple users is of course welcome!

**Comment by asmecher** [comment]
I think the longest participant lists will be in edited volumes in OMP, and I think the list won't be so long that a well-presented set of checkboxes would be unmanageable.

**Comment by asmecher** [comment]
See also https://github.com/pkp/pkp-lib/issues/2430, where there's discussion of "invisible" users. Presumably that option would also impact the user list that's presented when creating a discussion.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2581

Tests only:
https://github.com/pkp/ojs/pull/1420
https://github.com/pkp/omp/pull/415

![selection_009](https://user-images.githubusercontent.com/2306629/27043050-c51d5702-4f90-11e7-9417-90854d74fad7.png)

**Comment by ajnyga** [comment]
@NateWr I like the simplicity of the solution!
How about adding "select all" checkbox as well?

**Comment by NateWr** [comment]
I've been going back and forth on this. I think it would need some design work to implement a select all checkbox, as these controls are usually embedded within a table header/footer where their function is a bit more intuitive.

Alternate idea: should all participants be selected by default? @stranack do you think this would make good sense?

**Comment by ajnyga** [comment]
With the all participants selected as default the only (potential) problem I see is the higher possibility of sending messages to participants by mistake. I mean for example sending a sensitive message to the author by mistake. But this is a theoretical problem.

**Comment by stranack** [comment]
I'd be inclined to NOT select all by default, test for a while, and revisit. The ability to select individuals is SO MUCH easier under this new design that I'm fine with having people do some extra checking if needed.

I think a lot of the discussions will be one on one (copyeditor asking author about some detail, layout editor asking copyeditor to confirm some wording, etc.) and not necessary for group inclusion -- and potentially leading to information overload. Perhaps this could be a configuration option in Settings (e.g., include all participants by default -- while still allowing for selective unchecking)?

**Comment by ajnyga** [comment]
We have two journals where decisions are made by a group of editors. This is the original scenario I was thinking when I suggested the "add group" option to the original UI. But as Kevin said, this is already so much quicker that I think this should satisfy them anyway.

**Comment by NateWr** [comment]
Tests passed. @bozana can you do code review on this?

**Comment by bozana** [comment]
@NateWr, nice work! It can be merged :-)

**Comment by ajnyga** [comment]
Great work, thank you!

**Comment by NateWr** [comment]
Merged!
