### ISSUE TITLE
CrossRef minor improvements

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1449]

**Comment by asmecher** [comment]
- Extend issue publication year to support a broader range: https://github.com/pkp/ojs/commit/99a011d19c95e74d94fe7bb859d433ab0f8e5dff
- Suppress `pages` element when page numbering could not be parsed: https://github.com/pkp/ojs/commit/1b3a9f192ab8a91ab116729013db23ab30b033b2

**Comment by asmecher** [comment]
- We discussed falling back on the issue publication date when the article publication date isn't available. That's already the case. (`plugins/importexport/crossref/CrossRefExportDom.inc.php`)

**Comment by bozana** [comment]
@asmecher, here the PR needed for the publication date: https://github.com/pkp/ojs/pull/820 -- there you see the issue number belonging to the PR :-)

**Comment by asmecher** [comment]
I must be going blind! I think I was looking at the master branch, which already does this (a little differently). I've merged that PR and cherry-picked it over to `ojs-stable-2_4_8`.

**Comment by asmecher** [comment]
Closing for 2.4.8-1!
