### ISSUE TITLE
[OMP][OJS] Update ORCID plugin for OMP 1.2/OJS 3

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1450]
The plugin developed from the sprint (#1416) works with OJS 2._x_, but needs adaptation to be compatible with the latest and greatest.
 - [x] Get registration and settings working with OJS 3
 - [x] Get the new registration and submission forms wired up to the plugin in OJS 3
 - [x] Genericize it (change journal references to context) so that it will work in OMP 1.2 as well

**Comment by crism** [comment]
Something is wonky with registration. @asmecher, any suggestions? I think `Registry` and `HookRegistry` are transient, right? So all the plugins should register all their hooks every time a page is hit… but `OrcidProfilePlugin` only registers its hooks on the plugin administration page. When I add error logging to `HookRegistry::register()` and `HookRegistry::call()`, I see other plugins working correctly on every page hit. What the heck is different here‽

**Comment by asmecher** [comment]
@crism, that probably means the plugin isn't registered with the system. To get it registered, you need to either install it through the web interface, or if it's already in place (e.g. by unpacking the tarball), run the upgrade script. (Back up your DB before you do that.)

**Comment by crism** [comment]
The plugin management interface shows it, and I can enable and disable it, and change its settings. However, it might not be fully registered—the upgrade script dies, because it tries to upgrade the database from the old version of OJS, too, which involves deleting a table which doesn’t exist.

**Comment by asmecher** [comment]
OTOH you could also register the plugin like this:

    INSERT INTO `versions` (`major`, `minor`, `revision`, `build`, `date_installed`, `current`, `product_type`, `product`, `product_class_name`, `lazy_load`, `sitewide`) VALUES (1,0,0,0,'2016-04-25 11:05:46',1,'plugins.generic','orcidProfile','OrcidProfilePlugin',1,0);

**Comment by crism** [comment]
Ah, `versions` is where it lives… but `orcidProfile` is already there.

**Comment by asmecher** [comment]
Can you send me a copy of the plugin code you're currently working with?

**Comment by crism** [comment]
https://github.com/PublishingWithoutWalls/orcidSso/tree/feature/ojs3

**Comment by crism** [comment]
Hm… when I try to delete the plugin, I’m told it doesn’t exist. That could be part of the problem… I’ll install it through the Web interface.

**Comment by crism** [comment]
The filename/plugin name mismatch (`orcidSso` vs `orcidProfile`) may also have been a problem. Trying to do too much at once… `d-:`

**Comment by asmecher** [comment]
Yes, the name mismatch would explain it.

**Comment by crism** [comment]
Buh. That seems to have done it. Sorry for the noise.

**Comment by asmecher** [comment]
No problem, there's a little too much magic in there for my tastes and you're not the first to run into it.

**Comment by crism** [comment]
I’m stymied again. The output filter `profileFilter()` fires 20 times! The pattern matches 4 of those times, meaning I get 4 ORCID buttons.

It looks like (based on printing `$output` in the error log) the filter fires for every non-trivial `{...}` in the template, rather than just firing when the template is done. Is this a change from OJS 2._x_? Or is `unregister_outputfilter()` not working correctly? I’m still investigating, but if anyone has any bright ideas, I’d love to hear them…

**Comment by asmecher** [comment]
@crism, did you get un-stumped? If I wanted to see this behavior in action, I'd check out your master branch with an OJS 3.0 master branch install, correct?

**Comment by crism** [comment]
I was working on other stuff for the past few days… the ORCID authentication now works, but I need to fix the return URL. If you want to take a look, see the `feature/ojs3` branch.

**Comment by crism** [comment]
OK, finally getting back to this. The fact that ORCID and names are on different tabs is troublesome. If I can get it filling in the ORCID correctly, that will be a start, though. Hidden fields, or read-only fields for name parts on the public tab, maybe?

**Comment by crism** [comment]
It’s working for profile updating. However, it looks weird; the CSS isn’t getting loaded, and I can’t figure out why not. The call to `PKPTemplateManager::addStyleSheet()` is firing, but it doesn’t seem to result in any change to the CSS delivered to the browser. What am I missing?

**Comment by crism** [comment]
Ah… it _is_ being set correctly; the OJS home page picks up on it. However, the templates for the dashboard don’t properly acknowledge the stylesheet variables!

**Comment by crism** [comment]
Nope, I take it back. The plugin stylesheets are being added in the wrong context! Sorted, I think.

**Comment by crism** [comment]
Huh… some recent change in OJS caused `Request::getJournal()` _and_ `Request::getContext()` to return `null`.

**Comment by crism** [comment]
Oh, nevermind… was trying to register site-wide (context 0)—that don’t work yet.

**Comment by crism** [comment]
OK! Need to make it work for author info and for site-wide registration/profile… but progress.

**Comment by asmecher** [comment]
Sorry I haven't been watching this more closely! I've been traveling -- but I'm finished now.

**Comment by crism** [comment]
This needs to be better behaved when there is no context. Currently, there are no settings available when looking at site-wide plugins, and so when registering a site-wide account, it fails (since the ORCID API settings are missing).

However, I can’t think of a good reason why _all_ the settings shouldn’t be site-wide. Is there any reason why one journal (or press) on a site would use one ORCID developer account, and another would use a different one? @asmecher, thoughts?

**Comment by crism** [comment]
I’m dropping the ORCID support for authors. Against OJS 2._x_, every author was on the same page, and the plugin only applied to the first author, presumably the user, who could authorize the ORCID app. In OJS 3, each author has their own edit pane, indistinguishable; the “connect my ORCID” button doesn’t make sense in that context.

What should happen, and doesn’t (and I’ll file separately) is that a user with an ORCID should have that information copied, along with the nation and affiliation, into the author profile.

**Comment by asmecher** [comment]
+1, huge thanks, @crism!

**Comment by crism** [comment]
I can confirm that, with @asmecher’s changes to support API changes, this works with both OJS 3 and OMP 1.2.

**Comment by asmecher** [comment]
Thanks again, @crism!
