### ISSUE TITLE
[OJS] Multi-context site settings needs work

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1453]
When multiple journals exist, there's a site settings panel under Administration > Site Settings. This needs to be improved and the frontend settings needs to be tested.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/1639
https://github.com/pkp/omp/pull/311
https://github.com/pkp/ojs/pull/946

Although OMP doesn't really have an overall site index like OJS, I implemented a few of the updates just to keep parity between the two apps.

These PRs remove the `intro` field from sites but leave the `about` field. I didn't really see much use of having two nearly identical fields so I just consolidated them into the `about` field.

**Comment by asmecher** [comment]
Merged all three, thanks! Is this issue ready to be closed?

**Comment by NateWr** [comment]
I think so, yeah

**Comment by asmecher** [comment]
Done.
