### ISSUE TITLE
[UI] Clarify difference between file metadata and article metadata

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1454]
From usability testing outcomes:

> Submission: Clarify difference between file metadata and article metadata (e.g., “File Information”?). Nate: Give file metadata a heading in the format of “[File Type] metadata” (eg - “Book Manuscript metadata”.

**Comment by NateWr** [comment]
https://github.com/pkp/pkp-lib/pull/1455

![selection_047](https://cloud.githubusercontent.com/assets/2306629/15290302/80fa54f4-1b6f-11e6-8041-d4ff39028a24.png)

**Comment by asmecher** [comment]
Merged, thanks!
