### ISSUE TITLE
[UX] Easy wins from usability testing

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1456]
Filing a few easy wins from previous rounds of usability testing so we have an Issue to tag commits against without spinning out lots of new issues/notifications.

- [x] Registration: Add indication of password requirements to registration form
- [x] Submission: On submitter’s Dashboard, rename column label from “Element” to “Component” to match language.
- [x] Submission: Rename "Submission Checklist" to "Submission Requirements" (many users treated them like yes/no questions rather than a series of requirements)
- [x] Workflow: Remove unnecessary information from the filename metadata screen. Irrelevant to author/reviewer, adds to cognitive load

**Comment by NateWr** [comment]
https://github.com/pkp/pkp-lib/pull/1458
https://github.com/pkp/omp/pull/287
https://github.com/pkp/ojs/pull/838

**Comment by NateWr** [comment]
Restore some file information: https://github.com/pkp/pkp-lib/pull/1458/files/a11174d89c5627356d39cf79d8ba54e4a3bb9d46#r63414475

**Comment by NateWr** [comment]
I've restored the file metadata info as requested in https://github.com/pkp/pkp-lib/pull/1458/files#r63414475.

![selection_065](https://cloud.githubusercontent.com/assets/2306629/15474318/44a129c8-20fc-11e6-8ece-29c668d0e5f3.png)

![selection_069](https://cloud.githubusercontent.com/assets/2306629/15474539/2a03da6a-20fd-11e6-859f-b1e5c3b48abf.png)

![selection_070](https://cloud.githubusercontent.com/assets/2306629/15474540/2a1b5dac-20fd-11e6-9d3d-d8c6b8360140.png)

A couple of ideas:

1. Maybe this should only be shown for `SubmissionArtworkFile.inc.php`? Those are the only files with screen/print dimensions.

2. It might make more sense to turn this filename display into an editable naming tool. We'd tick off one of the things @stranack has raised in the past about auto-naming files, and then just provide an edit link which would reveal an input field if the user wanted to change the name.

![selection_068](https://cloud.githubusercontent.com/assets/2306629/15474481/ee58cda4-20fc-11e6-9e3a-656a46f42edf.png)

**Comment by asmecher** [comment]
I particularly like that last one, @NateWr. Agreed about editable naming with a sensible default.

**Comment by NateWr** [comment]
New PRs:

https://github.com/pkp/pkp-lib/pull/1480
https://github.com/pkp/omp/pull/291
https://github.com/pkp/ojs/pull/845

This restores the read-only metadata, assigns a [generated name](https://github.com/pkp/pkp-lib/pull/1480/commits/c836efbdd2087536dfa04452d8504b2f452ad8fa#diff-52cfff01111662d4dbe1e94ee1a4fc25R525) when [a file is created](https://github.com/pkp/pkp-lib/pull/1480/commits/c836efbdd2087536dfa04452d8504b2f452ad8fa#diff-2a9513cc937d8d3ff346971805921d9bR92), and creates a little editing toggle to allow the automatic name to be edited.

I feel like the data in the generated file name is really something that should be handled properly in the UI, but we'll tackle that when we can look at grids a bit more comprehensively.

**Comment by asmecher** [comment]
There are a few JS tweaks required before this one will pass testing.

**Comment by NateWr** [comment]
Ok fixed those errors and tests are running on the PRs now.

**Comment by NateWr** [comment]
It looks like the tests error'd out and now there are merge conflicts. Do you want me to re-stage these PRs, @asmecher?

**Comment by asmecher** [comment]
@NateWr, the OMP tests worked fine -- I've cherry-picked all that -- and either the OJS commit was an occasional timeout or it might be related to the scrolling problem @beghelli was looking at independently. Let's see how far the tests get; it's all in master now.
