### ISSUE TITLE
Public identifiers for OJS 3.0

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1457]
- [x] a) add "identifiers" tab to the metadata/edit modal of each publication object (issue, article, galley)
- [x] b) move "publisher-id" (custom URL identifier) to the new "identifiers" tab
- [x] c) remove old custom URL identifiers journal settings options -- they should always be there
- [x] d) implement DOI plugin 
- [x] e) implement URN plugin
- [x] f) implement a different pub ids assignment concept -- the pub ids shouldn't be assigned automatically as till now, but by the editor within the publishing process: 
- on the "identifiers" tab,
- when scheduling an article to an issue
- when publishing an issue 
- [x] g) moved to a new issue, after 3.0, s. https://github.com/pkp/pkp-lib/issues/1668 
- [x] h) UI/UX improvemnt (s. below)
- [x] i) Migration 2.4.x -> 3.0  (PR: https://github.com/pkp/ojs/pull/967)
- change pub id plugins settings name enableRepresentationDoi/URN, enableSubmissionDoi/URN
- remove journal settings names: enablePageNumber, enablePublicArticleId, enablePublicGalleyId, enablePublicIssueId, enablePublicSuppFileId?
- supp files? -> no supp files any more, s. also issue 1074 (s. https://github.com/pkp/pkp-lib/issues/1683#issuecomment-238826983)
- [x] j) Test OAI
- [x] k) Consider remote galleys (s. https://github.com/pkp/ojs/pull/969)

**Notes**: 
- At the moment the 'Clear Pub Id' function exists for each object i.e. each pub id, for all issue objects and for the whole journal.
- There is no duplicate check for the pub ids with suffix = pattern and default (as till now).
- The checkbox "Assign pub id to this object" is always checked per default.
- Galleys view: the pub ids should be displayed somewhere

UI/UX:
- Display what is missing in the pub id suffix, why it cannot be assigned.
- Use something like pkp_button_link_offset (like Cancel buttons in modals) for "Clear DOI"/"Clear URN"
- Make "Clear Issue Objects DOIs"/"Clear Issue Objects URNs" as buttons, something like pkp_button_offset
- Add headings "URN" and "DOI" for the pub id assignment parts on the issue publishing confirmation modal, when publishing an issue.

**Comment by asmecher** [comment]
Does this need an OMP PR before it can be merged?

**Comment by bozana** [comment]
I would like to first keep it simple and make just the minimal necessary changes in OMP, s. https://github.com/bozana/omp/commit/4b072a4af9d89a4c6cad1d05fef9051b5db24602 (I will wait with this OMP PR till the other PR are merged, OK?)
Then, when everything OK, I can migrate the new pub id concept to OMP too.
OK so?

**Comment by asmecher** [comment]
Sure, that's fine, as long as the pkp-lib PR doesn't break OMP.

**Comment by bozana** [comment]
Hmmm... Even better then to merge everything together i.e. I will make the OMP PR above as soon as I've integrated all the review comments :-) THANKS!!!

**Comment by bozana** [comment]
Hi @asmecher, I integrated the recommended changes from the code review, please see the PRs:
pkp-lib: https://github.com/pkp/pkp-lib/pull/1459
ojs: https://github.com/pkp/ojs/pull/839
omp: coming... 
THANKS A LOT!!!

**Comment by asmecher** [comment]
Thanks, @bozana! I merged the pkp-lib PR and cherry-picked the OJS one in (submodule hash conflict).

**Comment by bozana** [comment]
@asmecher, I still have to consider some things for the migration from 2.4.x (s. i) above), thus I will open this issue again, ok? And I will move g) to a new issue, maybe for 3.1, ok?

**Comment by asmecher** [comment]
Hmm, it looks like github decided to close this when I merged one of the PRs -- it's never clear to me when/why it does this. But yes, agreed.

**Comment by NateWr** [comment]
Sorry to pop in on this issue, but wanted to let @asmecher know of this tiny little PR for the clear DOI button styles:

https://github.com/pkp/pkp-lib/pull/1632

**Comment by asmecher** [comment]
Does that make this one ready to close, @bozana?

**Comment by bozana** [comment]
Ah, sorry, for not writhing it here, one still at Nate's plate ;-)
OJS PR: https://github.com/pkp/ojs/pull/969
Assigning Nate...
Then yes, ready to close :-)

**Comment by NateWr** [comment]
Looks good! Just a couple of minor comments to look over.

**Comment by bozana** [comment]
Hi @NateWr, the commit above considers your comments... Thanks a lot!

**Comment by NateWr** [comment]
:+1: Merged! Ready to be closed?

**Comment by bozana** [comment]
Thanks @NateWr! Yes, finally I can close this 'monster' issue! ;-) And will be happy to open a new one, for future work or bugs or... -- to have some variety with issue numbers :-DDD
Closing...
