### ISSUE TITLE
[UI] Remove tasks grid in frontend

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1461]
Instead of the full tasks grid, we'll just display the notification count in the user dropdown.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/1462
https://github.com/pkp/omp/pull/288
https://github.com/pkp/ojs/pull/840

Screenshot
![selection_052](https://cloud.githubusercontent.com/assets/2306629/15296107/b23e66f6-1b8b-11e6-88b1-40ec0d0b3292.png)
:

**Comment by asmecher** [comment]
Merged, thanks! The tests were failing because the submodule commit wasn't last in the list; I'll watch to see if this resolves itself now that it's merged.
