### ISSUE TITLE
[OJS] OJS 2 license information: make it harder to reset permissions

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1466]
In OJS 2's setup, there's a section on permissions, that has this option:

> Copyright statement and license information will be permanently attached to published content, ensuring that this data will not change in the case of a journal changing policies for new submissions. To reset stored permissions information already attached to published content, use the button below.
> **[Reset Article Permissions]**

This makes it much too easy to accidentally or intentionally reset permissions on already published articles, which should be avoided (e.g. because in most open access journals, the publisher doesn't hold the copyright). As with #408, this seems to stem from a view centered on test journals. But we are dealing with live journals and should refrain from offering too many options to fiddle with important features of already published works.

Copyright and permissions of already published works should  be addressed via the article id and article page, not via "for every published article".

**Comment by mfelczak** [comment]
One use-case where a global reset/set may be helpful is import of back issues for a journal moving to OJS. If a journal wants to tweak or standardize copyright/licensing for a large batch of imported articles it can do so without needing to edit the DB directly. For older journals with large back catalogues doing this on a per-article basis will be impractical.

That being said, I'm in general agreement with @mtub here. The above use-case will be rare and falls outside of common use.

**Comment by NateWr** [comment]
@mfelczak would it be appropriate for this functionality to be moved to Tools and require an admin?

**Comment by mfelczak** [comment]
@NateWr, that makes sense to me, although it's probably sufficient to require Journal Manager access (as opposed to Site Admin access).

**Comment by mtub** [comment]
If the feature exists, for editors or for admins, there should be a prominent warning that journals should check if they are allowed to change the license retroactively.

**Comment by asmecher** [comment]
I would advocate strongly for keeping this in the JM's purview.

**Comment by NateWr** [comment]
As part of #3594, I've moved this into the Tools area and made it accessible to Journal Managers. I've also beefed up the scare factor in the warning, removed the string from other locales so they re-translate it, and added "this can not be undone" to the confirmation prompt in `en_US`.

![selection_080](https://user-images.githubusercontent.com/2306629/46354271-1fee5400-c656-11e8-9dd0-2558e4517f7c.png)
![selection_081](https://user-images.githubusercontent.com/2306629/46354272-2086ea80-c656-11e8-9d95-c5087c5543e0.png)

I'm going to close this, but please speak up if you think anything needs further work. It won't be merged until the new form stuff goes in for 3.2.
