### ISSUE TITLE
[UI] Work out theme registration, enabling and parent-child relationships

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1468]
I'm repurposing this issue for general work that needs to be done on themes. Some issues identified to be reworked:

- [x] Themes appear in selection list (Website > Appearance) even if they're not enabled (enabled doesn't mean active?).
- [x] Themes should overwrite the `getEnabled` method to check if they're currently active.
- [x] Hooks registered in constructor fire whether the theme is enabled or not (see original comment below).
- [x] Themes should have an easier API for managing style/script/font assets.
- [x] Get a basic parent/child relationship going for themes.
- [x] Allow plugins to add LESS files to process to the main stylesheet
- [x] Consider using LESS var for `{$baseUrl}` https://github.com/pkp/pkp-lib/issues/1468#issuecomment-222560347

_The original comment:_

If a theme [hooks in to do things like print JavaScript](https://github.com/pkp/ojs/blob/master/plugins/themes/default/DefaultThemePlugin.inc.php#L25), they execute the hooks whether they're currently enabled or not.

The obvious solution is to just check if the theme is active before registering a hook. If there's a risk of lots of badly coded themes not doing this, we might set up a specific architecture for hook registration which is gated "under the hood" so themers don't need to be aware of this.

**Comment by asmecher** [comment]
The `ThemePlugin` subclass should take care of mapping hooks etc. into a sensible API that hides the details from the theme implementer, but ideally without limiting the themer should they want more control over how the system behaves. So I'm ambivalent about changing the loading behavior, but if we do have examples of theme plugins that need to register hooks, I wonder whether that indicates that the `ThemePlugin` should enrich its API to move that out of the theme.

**Comment by NateWr** [comment]
It may be possible to use LESS variables for `{$baseUrl}` by passing it in at compile time like this:

```
$parser = new Less_Parser();
$parser->parseFile( '/var/www/mysite/bootstrap.less', '/mysite/' );
$parser->parse( '@baseUrl: http://whatever.com' );
$css = $parser->getCss();
```

**Comment by NateWr** [comment]
Ok I wasn't able to get this finished up before I go. Notes for later:

- Parent-child relationships work for styles and templates but not yet for scripts.
- Need to test the global site index. Not sure if styles/scripts will load properly there.
- @asmecher Am I right in thinking these two methods in the default theme are only for the default theme. They shouldn't be replicated in other themes, and the `settngs.xml` isn't needed?

**Comment by asmecher** [comment]
Sounds good, @NateWr. Yes, you're correct -- `getContextSpecificPluginSettingsFile()`, `getInstallSitePluginSettingsFile()`, and `settings.xml` are only required to enable the plugin by default. You might find as you add a second theme plugin that there is some change in behavior required to make only the default plugin active during the installation process; if that's the case feel free to prod me.

**Comment by NateWr** [comment]
Initial PRs:

https://github.com/pkp/pkp-lib/pull/1519
https://github.com/pkp/ojs/pull/860

Themes now fire off an [init()](https://github.com/pkp/pkp-lib/pull/1519/files#diff-a8bc8a63802d1659d8ddc41a44c55b9fR64) method where they can run code only when the theme is active. Themes can [add stylesheets and scripts](https://github.com/pkp/ojs/pull/860/files#diff-6df5306de8589db221dce98a0815f09aR25) or [set a parent theme and modify existing styles/scripts](https://github.com/NateWr/default-child/blob/master/DefaultChildThemePlugin.inc.php#L25).

I'd like to document themeing. Do we have a place for more permanent docs? I can use my [sample child theme](https://github.com/NateWr/default-child) readme as a place to document stuff if that works too.

Some things to consider:

1. I deprecated the `PageHandler::displayCss` hook but [kept it](https://github.com/pkp/pkp-lib/pull/1519/files#diff-02cc91091ed65614e4709090fe93c948R106) for backwards compatibility. How do we feel about removing it? 

2. I've removed the `ThemePlugin::compileCss` and `PageHandler::displayCoreCss` hooks. Intervention should now be done with the `PageHandler::compileLess` hook [here](https://github.com/pkp/pkp-lib/pull/1519/files#diff-a52d1f134c8e119d3cdb2e280b60ac82R272), which provides the necessary details to know which file is being compiled.

3. A new hook, `PageHandler::getCompiledLess` is introduced as a fallback. If a CSS router request can't find a registered style to display, it will fire off the hook so that a plugin can handle the request. This should be discouraged and plugins should be encouraged to register their styles where necessary. But there isn't a simple API for doing so outside of themes.

4. All styles and scripts on the frontend should be registered and then loaded with the `{load_style ...}` and `{load_script ...}` smarty functions. Can we deprecate the `Templates::Common::Footer::PageFooter` hook and the `{$additionalHeadData}` variable? Are we using them for anything else we need?

**Comment by NateWr** [comment]
The readme for my [sample child theme](https://github.com/NateWr/default-child) repo now includes some better documentation which should probably get moved over to a more permanent place and incorporated in a blog post at some point.

**Comment by asmecher** [comment]
> 1. I deprecated the `PageHandler::displayCss` hook but kept it for backwards compatibility. How do we feel about removing it?

Have at 'er. I don't think this will have an adverse impact with the existing theme structure being so young.

> All styles and scripts on the frontend should be registered and then loaded with the {load_style ...} and {load_script ...} smarty functions. Can we deprecate the `Templates::Common::Footer::PageFooter` hook and the `{$additionalHeadData}` variable? Are we using them for anything else we need?

The `Templates::Common::Footer::PageFooter` hook is used in a couple of plugins:

- plugins/generic/googleAnalytics/GoogleAnalyticsPlugin.inc.php
- plugins/generic/phpMyVisites/PhpMyVisitesPlugin.inc.php

The `{$additionalHeadData}` variable is used in...

- plugins/generic/exampleGenericPlugin/ExampleGenericPlugin.inc.php
- plugins/generic/tinymce/TinyMCEPlugin.inc.php
- plugins/generic/webFeed/WebFeedPlugin.inc.php
- plugins/generic/announcementFeed/AnnouncementFeedPlugin.inc.php
- lib/pkp/plugins/generic/usageStats/PKPUsageStatsPlugin.inc.php

If you can suggest an improved alternative to each that we could use in the existing plugins (since those also serve as examples), I'd be open to removing one or both.

**Comment by NateWr** [comment]
Ok I've had a look at the plugins and I do think the hook, `Templates::Common::Footer::PageFooter`, should remain for cases where dynamic script output needs to take place, rather than linking to `<script>` files.

`$additionalHeadData` is interesting, since it's from before the frontend/backend split. Here's what I found:

- plugins/generic/exampleGenericPlugin/ExampleGenericPlugin.inc.php - Couldn't find it. Maybe it's just something you whipped up yourself?
- plugins/generic/tinymce/TinyMCEPlugin.inc.php - Backend only. This does need to be a variable, rather than a script tag, since it's pulling in dynamic variables.
- plugins/generic/webFeed/WebFeedPlugin.inc.php - Frontend only. Prints `<link>` elements.
- plugins/generic/announcementFeed/AnnouncementFeedPlugin.inc.php - Frontend only. Prints `<link>` elements.
- lib/pkp/plugins/generic/usageStats/PKPUsageStatsPlugin.inc.php - Frontend only. Just a script tag.

What I'd like to do is:

1. Create a `{load_headers}` template tag that mimics the `{load_styles}` and `{load_scripts}` tags. It would also add a `PKPTemplateManager::addHeader` function like the `addStyleSheet` and `addJavaScript` helpers. This would allow the `<link>` tags to attach to a specific context. And we could also consolidate the `{$metaCustomHeaders}` option into this. Then plugins will have an easier API-based method to add whatever they need to the head, defining a unique context rather than having to know the appropriate pages. Because the `{load_headers}` template tag would just be outputting strings, this would also allow dynamic script output, like the TinyMCE setup.

2. Extend the script registration process to allow script data to be output. This would support the Google Analytics and PhpMyVisites cases where we need to output dynamic JS values.

3. Convert each of the plugins you mentioned to use the new techniques.

What do you think of this? It's a bit more work but not terribly difficult and would provide a more consistent API for plugins to work with these kinds of assets.

**Comment by NateWr** [comment]
Ok I've updated the PRs with the comments from your code review. I just need a bit of direction on this comment (https://github.com/pkp/pkp-lib/issues/1468#issuecomment-226730236) and then I think we'll be good to go.

**Comment by asmecher** [comment]
Nate, I like the consistency of your proposal in https://github.com/pkp/pkp-lib/issues/1468#issuecomment-226730236 -- please go for it. The ExampleGenericPlugin is in a separate repo: https://github.com/asmecher/exampleGenericPlugin

**Comment by NateWr** [comment]
I've issued a number of PRs so we can get going on code review, but they're not quite ready for merge. I'm waiting for some feedback on the UsageStats plugin to do some refactoring there, the OJS PR doesn't include a submodule update (since this would need to be changed anyway), and I won't port OMP until we've finalized this spec.

https://github.com/pkp/pkp-lib/pull/1578
https://github.com/pkp/ojs/pull/899
https://github.com/pkp/tinymce/pull/10
https://github.com/pkp/googleAnalytics/pull/1
https://github.com/asmecher/exampleGenericPlugin/pull/2

**This does quite a lot of stuff:**

- Refactors and expands the API in `PKPTemplateManager.inc.php` to manage scripts, styles and head elements.
- _All_ scripts, styles and headers on the backend and frontend are now piped through this API, including external assets and inline'd scripts and styles. The Theme API is a layer of sugar that sits on top of the API in `PKPTemplateManager.inc.php`.
- Consolidates a few other scripts into the `minifiedScripts.tpl` list to be compiled with the JS framework.
- The API uses a `contexts` system to indicate where an asset should be loaded. There are two contexts in use, `backend` and `frontend`. This can be extended by themers if desired, eg `frontend-head`. Also, all contexts take advantage of a dynamic naming scheme. So if you load scripts for the `frontend` context, it will also check contexts related to the current `page` and `op`. So on the article view page, any scripts loaded in the `frontend`, `frontend-article` or `frontend-article-view` contexts will be loaded.
- Removes the JS framework from the frontend and only loads it in the backend (:tada:). Currently this causes an error on the article view page when usage stats are loaded. That will be fixed as soon as I get some feedback on my desired direction (posted in slack for James and Bozana to consider).
- Refactors `MenuHandler.js` and all of our nav menus to use aria attributes.
- Initializes TinyMCE in the `SiteHandler.js` and provides a hook to customize TinyMCE options.
- Implements a namespace pattern for plugins to make dynamic data available for use in JS handlers (see the TinyMCE options).
- Implements a system fonts fallback for Noto Sans if CDN usage is disabled.

**A couple of things to consider:**

- Favicon tags should specify a `type` attribute with the MimeType attribute. The existing code suggets that this can be access at `$favicon['MimeType']` but no such data existed for me. This may be a bug that needs to be handled separately. I've left it out for now.
- I believe `SearchFormHandler.js` is not used anywhere in the backend and therefore can maybe be removed. We'll probably need to think about how we want the frontend to behave, whether instant search is a critical feature, and how it might be architected to be reliable in different themes.
- We're still using `minifiedScripts.tpl` because I didn't fancy rewriting your regex in [buildjs.sh](https://github.com/pkp/pkp-lib/blob/master/tools/buildjs.sh#L111). My regex skills are mostly confined to copy/pasting stuff from StackOverflow. For that matter, you should check [my regex](https://github.com/pkp/pkp-lib/pull/1578/files#diff-a52d1f134c8e119d3cdb2e280b60ac82R517). If you're up for adjusting the `buildjs.sh` script, we could probably restructure the list of files into a PHP array somewhere.

**Docs**
It'd be great to document some best practices, so that over devs can make use of this API as we refactor all of our plugins and such for OJS 3.0. Is there a good place where I can draft up some stuff on this for the team and third-party devs? Potential docs:
- Registering a script, style or head item
- Outputting to a specific context or even a specific page
- Using our LESS compiler to add styles to existing sheets
- Registering JS data to a plugin's namespace

**Comment by asmecher** [comment]
Thanks, @NateWr, this looks very promising. I'd suggest we merge these whenever you're ready and the tests will pass -- I suppose that'll mean at least a partial port to OMP. I can help with the merging if you're hesitant e.g. to include submodule hashes because of the volume of code here. Let me know when you're ready, and maybe give the team a quick tour of template implications on Monday.

**Comment by NateWr** [comment]
Ok I've pushed updates to the PRs for OJS and pkp-lib and Travis is running the tests. I'll wait to see about those tests before wrangling an update for OMP.

**Comment by NateWr** [comment]
Hmm, Travis seemed to fail on some submodule issues. Is it because I have multiple submodule updates in the final commit? Should I add the non-pkp-lib submodules in a separate commit?

https://travis-ci.org/pkp/ojs/jobs/142216239#L222
https://travis-ci.org/pkp/ojs/jobs/142216279#L222
https://travis-ci.org/pkp/ojs/jobs/142216321#L222

**Comment by asmecher** [comment]
I haven't looked into the test failure in detail, but I think the submodule plugin updates are confusing it. For the moment, I'm happy to work around this for you -- e.g. when you're ready I can run the tests locally.

A couple of problems before it's ready, though:
- OJS tries to get context-specific data from DB before the system is installed/before a context has been created. To fix, cherry-pick (or adapt): https://github.com/asmecher/pkp-lib/commit/5c523abe5bc3a3e3e51ab27f606c25ebf12f61b6
- Attempted calls to PKPComponentRouter::getRequestedPage (this is a PageRouter method only). E.g.:

        [05-Jul-2016 01:06:11 UTC] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'PKPComponentRouter' does not have a method 'getRequestedPage' in /home/asmecher/git/ojs/lib/pkp/classes/core/PKPRequest.inc.php on line 849
        [05-Jul-2016 01:06:11 UTC] PHP Stack trace:
        [05-Jul-2016 01:06:11 UTC] PHP   1. {main}() /home/asmecher/git/ojs/index.php:0
        [05-Jul-2016 01:06:11 UTC] PHP   2. PKPApplication->execute() /home/asmecher/git/ojs/index.php:68
        [05-Jul-2016 01:06:11 UTC] PHP   3. Dispatcher->dispatch() /home/asmecher/git/ojs/lib/pkp/classes/core/PKPApplication.inc.php:227
        [05-Jul-2016 01:06:11 UTC] PHP   4. PKPComponentRouter->route() /home/asmecher/git/ojs/lib/pkp/classes/core/Dispatcher.inc.php:134
        [05-Jul-2016 01:06:11 UTC] PHP   5. PKPRouter->_authorizeInitializeAndCallRequest() /home/asmecher/git/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php:262
        [05-Jul-2016 01:06:11 UTC] PHP   6. call_user_func:{/home/asmecher/git/ojs/lib/pkp/classes/core/PKPRouter.inc.php:372}() /home/asmecher/git/ojs/lib/pkp/classes/core/PKPRouter.inc.php:372
        [05-Jul-2016 01:06:11 UTC] PHP   7. GridHandler->fetchRow() /home/asmecher/git/ojs/lib/pkp/classes/core/PKPRouter.inc.php:372
        [05-Jul-2016 01:06:11 UTC] PHP   8. GridHandler->renderRow() /home/asmecher/git/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php:701
        [05-Jul-2016 01:06:11 UTC] PHP   9. GridHandler->renderRowInternally() /home/asmecher/git/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php:538
        [05-Jul-2016 01:06:11 UTC] PHP  10. GridHandler->_renderCellInternally() /home/asmecher/git/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php:1009
        [05-Jul-2016 01:06:11 UTC] PHP  11. GridCellProvider->render() /home/asmecher/git/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php:1100
        [05-Jul-2016 01:06:11 UTC] PHP  12. PKPTemplateManager::getManager() /home/asmecher/git/ojs/lib/pkp/classes/controllers/grid/GridCellProvider.inc.php:48
        [05-Jul-2016 01:06:11 UTC] PHP  13. PKPTemplateManager->initialize() /home/asmecher/git/ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php:739
        [05-Jul-2016 01:06:11 UTC] PHP  14. PKPRequest->getRequestedPage() /home/asmecher/git/ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php:198
        [05-Jul-2016 01:06:11 UTC] PHP  15. PKPRequest->_delegateToRouter() /home/asmecher/git/ojs/lib/pkp/classes/core/PKPRequest.inc.php:743
        [05-Jul-2016 01:06:11 UTC] PHP  16. call_user_func_array:{/home/asmecher/git/ojs/lib/pkp/classes/core/PKPRequest.inc.php:849}() /home/asmecher/git/ojs/lib/pkp/classes/core/PKPRequest.inc.php:849

**Comment by asmecher** [comment]
(BTW, I merged the plugin PRs because there's a low volume of development there and we can update the submodule hashes for OJS/OMP when we choose.)

**Comment by NateWr** [comment]
Oh thanks for the heads up on the router stuff. I saw that in my logs but couldn't figure out the source, then forgot about it.

So I can wrap the one offending call in a check for the router type:

https://github.com/NateWr/pkp-lib/commit/1af0118093f6a44e4a6eb5a0368776493d0c6490

But I wonder if _all_ of the assets being loaded should only be loaded in the context of a page router. Do we ever need these assets in a component request? I'm thinking all of the assets loaded in `PKPTemplateManager->initialize()` should be only be executed if `is_a($router, 'PKPPageRouter')`. So from [here](https://github.com/pkp/pkp-lib/pull/1578/files#diff-a52d1f134c8e119d3cdb2e280b60ac82R128) to [here](https://github.com/pkp/pkp-lib/pull/1578/files#diff-a52d1f134c8e119d3cdb2e280b60ac82R216).

Does that sound right?

(thanks for the uninstalled/no-context commit. Cherry-picked that in)

**Comment by asmecher** [comment]
Yes, since the page router will always be responsible for handling HTML setup/teardown and the components will only (so far but as far as I can predict) add content to the body.

**Comment by NateWr** [comment]
Ok here's a PR for OMP as well:

https://github.com/pkp/omp/pull/301

If there's anything else you want me to do to aid in the merge process, let me know. Tomorrow is my last working day before I'm off.

**Comment by asmecher** [comment]
Thanks, I've rebased the PKP-lib (https://github.com/asmecher/pkp-lib/tree/i1468_theme_api_2) and OJS (https://github.com/asmecher/ojs/tree/i1468_theme_api_2) PRs and I'm working on them locally. If you commit further on yours, let me know so I can CP them into mine rather than rebasing again -- it's a big of a pain.

In running the data build scripts, though, there's a problem with the front end not pulling in assets -- no CSS, no JS. Know where I should start looking? Do I have to install a default setting or something?

**Comment by NateWr** [comment]
All I can think is to make sure you've cleared cache on the frontend?

You can `{$scripts|@print_r}` in the templates to see all of the scripts that are registered. Ditto for `$styles` and `$headers`. You should see everything registered, not just the ones loaded in a given context.

**Comment by asmecher** [comment]
I think it's related to the `enabled` / `active` setting in the default theme. Looking into it now.

**Comment by asmecher** [comment]
I've fixed the enable problem (see primarily https://github.com/asmecher/pkp-lib/commit/4a9c60ad5a49499e99f2d18d948a2ef2ffc931e7) and I've cleaned up a bunch of JSLint problems etc. I merged the PRs for plugins, `lib/pkp`, and OJS. Currently OJS master is broken -- I'll work on a few things but one for you to look at, @NateWr --

The `minifiedScripts.tpl` file could use some restructuring. It's no longer used as a template anywhere; it's either grepped in `lib/pkp/tools/buildjs.sh` for minification, or grepped in `PKPTemplateManager.inc.php`. This presents two problems:
- It shouldn't be maintained as a template if it's not being used as one. Perhaps a simple flat file?
- Some code that's not under our control has been moved into it, and is failing the JSlint/compile process. This code should be excluded from the lint/build process as it used to be.

**Comment by asmecher** [comment]
OK, so I went ahead and merged the OMP request too. OJS is now just failing the validation stage (per https://github.com/pkp/pkp-lib/issues/1468#issuecomment-230908038) and I'll see if I can get OMP to the same state today. See if you can get that one put away before you go, @NateWr!

**Comment by NateWr** [comment]
The following PRs pull some of the minified scripts out and register them separately. I think these are all the ones that were added.

https://github.com/pkp/pkp-lib/pull/1587
https://github.com/pkp/ojs/pull/910
https://github.com/pkp/omp/pull/303

I agree that the template file should go. But I am not familiar enough with your build scripts to properly rewrite the way that the `buildjs.sh` handles that file. If it's just a list we maybe don't need any regex.

Ideally, it'd be nice to be able to selectively lint during our build process. Maybe if the list just had a simple format that could be parsed before linting:

```
<file>
<file>
lint <file>
lint <file>
```

**Comment by asmecher** [comment]
Merged, thanks, @NateWr -- just a few last JS check issues to tidy up. See e.g.: https://travis-ci.org/pkp/ojs/jobs/143064867

**Comment by asmecher** [comment]
Fixed the JS linting problems, and OJS and OMP master are both testing OK again. Linting commits:

- https://github.com/pkp/pkp-lib/commit/586ea87f83b1c69730c5135905626f357be88d2c
- https://github.com/pkp/pkp-lib/commit/4ebfa824e853b9bfffc9429c870c5cfbb45400b9

I'll file the minifiedScripts.tpl refactor elsewhere. Thanks, @NateWr, hoping you're having a good break.
