### ISSUE TITLE
[OJS] "Forgot password" doesn't deliver reset password

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1469]
Hi, 
I'm using OJS 3 (updated shortly after Code Sprint this year). I tried to use "forgot password" on the admin account. Then I got an e-mail containing a link, which basically just led to the login-page of my ojs-installation. This triggered the second mail "password successfully reset. 
But I never had to type a password. Did I misunderstand something or is there a bug? 
Keep up the good work!
Best, 
Andreas
PS: 
First Mail Subject: [] Password Reset Confirmation
First Mail Contetn: [...]We have received a request to reset your password for the web site.

If you did not make this request, please ignore this email and your password will not be changed. If you wish to reset your password, click on the below URL.

Reset my password: http://<my-sites-url>/login/resetPassword/admin?confirm=b0d5daa265c2a20504bb1ef0a0b7eb97b969038a4fdbfc0f7527a58460629fa7%3A1463588294

Second Mail Subject: [] Password Reset
Second  Mail Contetn: [...] Your password has been successfully reset for use with the web site. Please retain this username and password, as it is necessary for all work with the journal.

Your username: admin

**Comment by asmecher** [comment]
Added. To resolve this for your existing installation (as opposed to a new installation), edit the PASSWORD_RESET email template via the web interface and add the text to your email template for all applicable languages:

    Your new password: {$password}

**Comment by HighwayStar** [comment]
I have same issue with current master  branch.

E-mail recieved after password reset:
```
Your password has been successfully reset for use with the  web site. Please retain this username and password, as it is necessary for all work with the journal.<br />
<br />
Your username: test1<br />
<br />
<br/><br/>
```

**Comment by asmecher** [comment]
@HighwayStar, did you try the approach recommended above?
https://github.com/pkp/pkp-lib/issues/1469#issuecomment-228913830

Note that the email templates are installed to the database when the press is created, so updating the code after this fix was applied will not affect presses/installations that have already been created.

**Comment by HighwayStar** [comment]
As far as I can see there is no password field in current master branch email template https://github.com/pkp/ojs/blob/master/locale/en_US/emailTemplates.xml#L66

```
		<description>This email is sent to a registered user when they indicate that they have forgotten their password or are unable to login. It provides a URL they can follow to reset their password.</description>
	</email_text>
	<email_text key="PASSWORD_RESET">
		<subject>Password Reset</subject>
		<body><![CDATA[Your password has been successfully reset for use with the {$siteTitle} web site. Please retain this username and password, as it is necessary for all work with the journal.<br />
<br />
Your username: {$username}<br />
<br />
{$principalContactSignature}]]></body>
```

**Comment by asmecher** [comment]
@HighwayStar Thanks, I'm not sure how I missed that -- but it's fixed. You can apply the last two commits to your 3.0.0 installation, then use the "Reload defaults" link for each language you're using to reload the email templates from XML.

**Comment by HighwayStar** [comment]
Sorry for late answer, but I tried it now and changes now are in xml files, but Reload default soesnt work for me. For both global email template reset and Reset for each template does nothing for me. Template text remains the same.
