### ISSUE TITLE
Test/fix cover image view

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1470]
See http://forum.pkp.sfu.ca/t/omp-1-2-coverhandler-function-cover-does-not-work/12754

**Comment by bozana** [comment]
I believe this is OK in the new OMP 1.2, right?

**Comment by asmecher** [comment]
I think so, but it needs verification.

**Comment by bozana** [comment]
You were right @asmecher, here the PR: https://github.com/pkp/omp/pull/322

**Comment by asmecher** [comment]
Thanks, @bozana!
