### ISSUE TITLE
Fix representations/galleys/galley files cardinality problem

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1472]
- [x] Get rid of viewableFiles category (use generic instead) -- this will help in the future to facilitate code sharing e.g. as these types of plugins interact with the workflow (think document-centric tools)
- [x] Get rid of galley type selection, as this is actually more file format specific
- [x] ...more?...

**Comment by asmecher** [comment]
- [ ] Fix CounterPlugin call to isPdfGalley, isHTMLGalley (which may be removed)

**Comment by asmecher** [comment]
Pulls (work in progress):
- https://github.com/pkp/ojs/pull/858
- https://github.com/pkp/pkp-lib/pull/1511

**Comment by asmecher** [comment]
Remaining work:
- [ ] Fix missing Validation::isAuthor: https://github.com/pkp/ojs/commit/07f2eb1ad6d7d67597d0459b3d13a502397bd5b0#commitcomment-17663480
- [ ] Fix HTML galley plugin (including CSS and image uploads)

**Comment by asmecher** [comment]
Fixed!

**Comment by bozana** [comment]
@asmecher, I found one more thing I believe: You can add several files to a galley now, using the row action "upload file" and then it looks strange in the grid?
And we should figure out how to deal with other kind of files e.g. supp files. Would they be added as galleys?

**Comment by asmecher** [comment]
Thanks -- I fixed the multiple file listing problem in the grid. Supplementary files should be created as galleys for now but I think we'll probably have to figure out a way to promote content from previous stages. Let's talk about this on Monday.

**Comment by bozana** [comment]
Hmmm... I think we should find another solution for the galley files: Now I can apparently 'replace' them and the last uploaded file will be always shown, but the others are still there. So they can be accessed (e.g. ...article/download/1/7/18-1) and they are considered for export. Maybe it will also be difficult to deal with the situation on some other places, if necessary? I cannot change/delete them then any more. I also cannot edit the file metadata any more (neither from those old ones in the DB nor from the current/last one). Thus, maybe to really replace the old ones (if it is not a revision of the old one), like in OJS 2.4.x, and to somehow allow to edit the file metadata too?

**Comment by bozana** [comment]
Maybe just a not here, for Monday, that the current way to find supplementary files is not clear/explicit: I could, for example, upload a Multimedia component as a supplementary file as well as a part of a submission (dependent file), so how to know if it is a supplementary file that should be published and exported (e.g. for Crossref)?

**Comment by NateWr** [comment]
https://github.com/pkp/pkp-lib/pull/1535

This PR addresses a few clarity issues around the file upload for galleys in OJS.

- Change "Upload File" to "Change File" to reflect the one-file-per-grid relationship.
- Remove the "Add Another File" button from the file upload wizard's confirmation tab for files in the `SUBMISSION_FILE_PRODUCTION_READY` stage.

I'm not sure what implications this has for OMP. Does OMP use the same `SUBMISSION_FILE_PRODUCTION_READY` for publication format files? If so, this might degrade the experience there. I'm not sure how to handle that.

This doesn't address @bozana's concerns about multiple files. When you "change file", you create a new file associated with the galley, but all the old ones are still there.

**Comment by asmecher** [comment]
Thanks, @NateWr, just one change needed on the PR. I don't mind if old files are kept but no longer presented -- we'll need to keep them for the sake of auditability, but I don't think there's any need to permit access to other versions via this grid. If anything, the event log should allow downloads of older files.

**Comment by bozana** [comment]
If the old files will remain in the system: Lets say I upload a new galley, that is not a revision of the existing file i.e. as a new file -- maybe immediately the first question: why would this be possible? Then I would like to upload a revision of that new file: the old file is still listed in the list of possible files to be revised ("If you are uploading a revision of an existing file, please indicate which file.") -- not only the last one -- which seems a little bit strange to me ;-) :-D

**Comment by asmecher** [comment]
Ah, I see -- I can fix the revisions thing pretty quickly, let me take a look.

**Comment by asmecher** [comment]
Fixed -- thanks!
