### ISSUE TITLE
Update setup help areas according to pkp/pkp-lib#1397

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1479]
@stranack, here's our first merge requiring help updates to OMP and OJS (master branches).

**Comment by asmecher** [comment]
(from pkp/pkp-lib#1397)

**Comment by asmecher** [comment]
@stranack, relevant to today's discussion of help.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/1778
https://github.com/pkp/ojs-user-guide/pull/1
https://github.com/pkp/ojs/pull/1007

**Comment by asmecher** [comment]
Ah, sorry, I'm asking questions before finishing my email trawl. I've assigned @stranack to review the help stuff, and with his go-ahead we can merge the rest to suit.

**Comment by asmecher** [comment]
Merged/cherry-picked, thanks!
