### ISSUE TITLE
Error loading index.php when trying to install first time

### ISSUE THREAD

**Issue by misilot** [pkp/pkp-lib#1482]
Hello,

I get the following errors when trying to install the 2.4.7-1 for the first time.

```
[Tue May 24 16:05:13.636299 2016] [:error] [pid 10819] [client 255.255.255.0:62347] PHP Deprecated:  Non-static method PKPApplication::defineExposedConstant() should not be called statically in /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php on line 545
[Tue May 24 16:05:13.636480 2016] [:error] [pid 10819] [client 255.255.255.0:62347] PHP Deprecated:  Non-static method PKPApplication::getExposedConstants() should not be called statically in /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php on line 513
[Tue May 24 16:05:13.641695 2016] [:error] [pid 10819] [client 255.255.255.0:62347] PHP Fatal error:  Cannot use 'String' as class name as it is reserved in /var/www/html/lib/pkp/classes/core/String.inc.php on line 57
```

I am using:
PHP 7.0.6 (cli) (built: Apr 29 2016 11:46:41) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
On centos 7.

Thank you,

Tom

**Comment by asmecher** [comment]
@misilot, PHP 7 introduces a `String` class, and OJS already has its own, so the two conflict. For the moment, I would suggest using PHP 5.x. See https://github.com/pkp/pkp-lib/issues/1118 for details.

**Comment by misilot** [comment]
@asmecher Thanks, I will try PHP5.6, do you know when OJS3.0 might be released? Since, #1118 talks about that version. The only reason I ask, is active support ends 31 Dec 2016 for PHP5.6, which is the end of the year, and would like to not be playing the replace PHP version game if it all possible.

Thank you!

**Comment by asmecher** [comment]
@misilot, we'll be releasing OJS 3.0 this summer, and will release a version of OJS 2.4.x that supports PHP7 this year as well. I wasn't aware that PHP7 usage was at an appreciable level in the wild yet.

**Comment by misilot** [comment]
@asmecher Thanks! It isn't so much that PHP7 isn't at an appreciable level in the wild, but there have been considerable improvements to the code for PHP7 and the end of support for PHP5.6 (the last version 5 release) is coming soon.

**Comment by asmecher** [comment]
Thanks, @misilot. We'll definitely have PHP7-capable releases before then; I'm keeping an eye on PHP7 uptake.

**Comment by mfelczak** [comment]
@asmecher and @misilot, I was curious about this myself and dug up some concrete dates. Active development for PHP 5.6 will end Dec 31, 2016 but security updates will continue to be released until Dec 31, 2018.

**Comment by gen-ass** [comment]
@asmecher hi, you mentioned the PHP 7.0 update

> PHP 7 introduces a String class, and OJS already has its own

was it introduced in the OJS 2.4.8.1 version?

**Comment by asmecher** [comment]
@gen-ass, OJS 2.4.8-1 still uses a class called `String` and thus won't currently work with PHP7. Have you looked at OJS 3.x?

**Comment by gen-ass** [comment]
Thanks, I am busy testing OJS 3.X...

**Comment by asmecher** [comment]
Sounds good, @gen-ass. We'll probably release an OJS 2.4.x that doesn't clash with PHP7, but not until PHP7 has a larger install base -- it's currently at <3%.
