### ISSUE TITLE
[UI] Backend style update

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1483]
While implementing the context-sensitive help, there was an intention to do some [broad style adjustments](https://github.com/pkp/pkp-lib/issues/1032#issuecomment-196988788) for the backend.

In addition, since the initial revamp, I've become better acquainted with the platform and want to make a few more adjustments around button styles, font sizes, etc, to improve readability and give it a slightly more professional, forward-leaning aesthetic.

**Comment by NateWr** [comment]
PRs (mostly everything is in pkp-lib):
https://github.com/pkp/pkp-lib/pull/1489
https://github.com/pkp/omp/pull/293
https://github.com/pkp/ojs/pull/848

This was almost entirely style changes, but there were a few minor markup changes, so we'll see how the tests do.

This represents a pretty big change all-around. I took quite a few liberties here so if there's anything that anyone considers a regression we can chat about it at the dev meeting. I'd say it's around 70% genuinely useful changes and 30% "I like it better" changes.

New header style to better represent our use of tabs. Color changes for the primary nav menu.
![selection_106](https://cloud.githubusercontent.com/assets/2306629/15573043/4ca256dc-233c-11e6-932a-5e69748df2cd.png)

Fancy tabs!
![fancy-tabs](https://cloud.githubusercontent.com/assets/2306629/15573233/59543606-233d-11e6-81a2-622eb0d1e41e.gif)

Sleeker buttons for the cool kids
![selection_102](https://cloud.githubusercontent.com/assets/2306629/15573280/ca7f8042-233d-11e6-8ed5-4bfcab883278.png)

Submission-wide actions moved to their own bar
![selection_103](https://cloud.githubusercontent.com/assets/2306629/15573288/e28cd9f0-233d-11e6-8fdd-e8e48163b263.png)

Lighter grid styles with slight font size reduction
![selection_101](https://cloud.githubusercontent.com/assets/2306629/15573247/7303d0de-233d-11e6-87df-94f447bf4743.png)

Special grid ordering styles
![selection_100](https://cloud.githubusercontent.com/assets/2306629/15573330/321ae548-233e-11e6-8960-34464f6ed65f.png)

Nested tabs
![selection_105](https://cloud.githubusercontent.com/assets/2306629/15573300/f298c5ac-233d-11e6-82c1-935025cdf869.png)

Tabs in modals
![selection_098](https://cloud.githubusercontent.com/assets/2306629/15573317/193e68e2-233e-11e6-9f3b-2605408ee270.png)

Tabs in grids
![selection_107](https://cloud.githubusercontent.com/assets/2306629/15573307/ff0e2ef8-233d-11e6-9437-21b765c7c6f1.png)

Standardizing form buttons on the left and button rows in modals in forms
![selection_104](https://cloud.githubusercontent.com/assets/2306629/15573352/54165330-233e-11e6-8477-c1711ef45455.png)

If you see the following in a modal, where the required notice appears below the buttons, _file an issue and assign to me_ (non-modal forms are ok)
![selection_108](https://cloud.githubusercontent.com/assets/2306629/15573412/d005c75a-233e-11e6-85c4-2039ebf5162f.png)

**Comment by asmecher** [comment]
Thanks, Nate -- merging as the tests pass, and looking forward to exploring some of the changes once I pull down locally. (Insert joke about the blindness of server-side developers.)

**Comment by NateWr** [comment]
Sorry one more little PR: https://github.com/pkp/pkp-lib/pull/1490

**Comment by asmecher** [comment]
(Merged the little PR above; working on the OMP test failure)
