### ISSUE TITLE
[UI] Assign submissions to issues from issue table of contents

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1485]
Users should be able to assign a submission to an issue from the issue management table of contents.

![selection_090](https://cloud.githubusercontent.com/assets/2306629/15547127/6411f5e0-229a-11e6-9462-09a7e25d3a64.png)

**Comment by asmecher** [comment]
Agreed -- though oddly enough nobody has ever asked for this in OJS 2.x, which also has article-centric scheduling into issues. IMO this is a secondary priority for OJS 3.0, though I'll leave it scheduled there for now.

**Comment by asmecher** [comment]
Deferring slightly.

**Comment by NateWr** [comment]
Closing as this hasn't attracted much interest over the last 5 years.
