### ISSUE TITLE
[OJS] Journals page design layout with ul

### ISSUE THREAD

**Issue by alonsoj** [pkp/pkp-lib#1486]
Hello:

I think it would be desiderable to design layout of journals page with ul list, or at least adding a div with a class to every div to facilitate css design. And a mosaic view of the journals it would be great. For OJS 2.x and 3.

Maybe related to issue #1390 

Greetings

**Comment by asmecher** [comment]
Hi @alonsoj -- could you post this on our forum at http://forum.pkp.sfu.ca/ rather than this issue tracker? Here we tend to work on specific development tasks, and the forum is better for broad discussion.
