### ISSUE TITLE
[UI] Author and Reviewer dashboards/workflows need review

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1488]
There may or may not be issues with them, but the ones in OJS haven't had a look to see if there are any styling/language errata that need to be worked out. 
## Overall dashboard
- [x] Editorial History > Notes: text under the buttons in modal.
- [x] Read and unread tasks are both shown as bold.
- [x] Article metadata > Contributors > Add contributor: required fields notice appears below buttons
## Submission (stage)
- [x] Submission files: rename "Edit metadata" to "Edit" since most formats have no metadata now.
- [x] File names in discussion modals appear with label outlines.
- [x] Messages in discussion modals appear with label outlines.
## Review
- [x] Discussions grid sits right up against bottom of participants grid.
- [x] Request Revisions modal includes a link to add reviews. It shouldn't appear when no reviews exist. Results in `alert()` error if you click it when no reviews exist.
- [x] Request Revisions modal link to add reviews needs some layout/style love.
- [x] Request Revisions modal: Reviewer's Attachments grid filter has off-style button row.
- [ ] Once a review is created, it's visibility (Blind, Double-blind, Open) doesn't appear to be displayed anywhere and can't be edited.
- [ ] Author gets _no_ notification when reviewers are assigned or reviews are in. Should they get something?
- [x] Email Reviewer: the "required fields" indicator is below the submit button.
- [x] Review history could use some style touch-ups.
- [ ] New review round: can't forward original Review Files from first round, only the Revisions. Is that intended?
- [x] Author and Editor workflow review rounds: can't go from round 2 to round 1 and back to round 2 without causing JS error. 
## Reviewer
- [ ] Once a review is completed, the task remains in the tasks list. Clicking on it goes to an invalid submission error. It goes away once the page is reloaded.
## Production

(Couldn't test due to local db error.)
- [x] Extra space in OJS galley grid. https://github.com/pkp/pkp-lib/issues/1488#issuecomment-237848195

**Comment by NateWr** [comment]
Extra space in OJS galley grid:
![extra-space-omp](https://cloud.githubusercontent.com/assets/2306629/17437798/b33b7000-5b17-11e6-9067-cb892984a8a9.png)

**Comment by NateWr** [comment]
@asmecher or anyone: should the metadata be shown to a reviewer when they are previewing the article (before accepting the review request)?

![selection_017](https://cloud.githubusercontent.com/assets/2306629/17438555/51a8e30a-5b1b-11e6-8839-aef6985ae952.png)

**Comment by asmecher** [comment]
@NateWr, regarding https://github.com/pkp/pkp-lib/issues/1488#issuecomment-237854334 -- yes, that's fine, as long as the author information is not included for reviews that aren't open.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/1685
https://github.com/pkp/omp/pull/316
https://github.com/pkp/ojs/pull/961

Once these PRs are in, this issue can be reassigned to 3.0.1.

**Comment by asmecher** [comment]
The OJS and OMP PRs report test failures on JS linting. Sorry, @NateWr, this is your Monday albatross :)

**Comment by NateWr** [comment]
@asmecher Do you understand what it's complaining about?

https://travis-ci.org/pkp/ojs/jobs/150255230#L880

As far as I can tell, `if (options.peerReviewUrl !== null)` does not use the the options object any differently than any of the other handlers which aren't throwing linting errors:

https://github.com/pkp/pkp-lib/blob/master/js/classes/features/GeneralPagingFeature.js#L26
https://github.com/pkp/pkp-lib/blob/master/js/classes/Handler.js#L47
etc...

**Comment by asmecher** [comment]
Who knows what evil lurks in the heart of Google Closure Compiler?

In some cases it complains about insufficiently defined objects -- rightly so, IMO, since otherwise `Object` would just be a catch-all for doing whatever you want. You can describe types a little further in-line like this: https://github.com/pkp/pkp-lib/blob/master/js/classes/features/OrderItemsFeature.js#L227

**Comment by NateWr** [comment]
Ok, now it's just failing on that same syntax thing that's been fixed as part of the #1536 PRs. Should we wait and rebase once that's in to make sure the linting goes through alright?

> rightly so, IMO, since otherwise Object would just be a catch-all for doing whatever you want

I kind of thought that was the beauty of JavaScript. :)

**Comment by asmecher** [comment]
I've assigned that PR over to @bozana; yes, probably a good idea to rebase when that's in so we don't start to compound testing problems.

> I kind of thought that was the beauty of JavaScript. :)

https://pbs.twimg.com/media/CkM9dL_WYAAqnsO.jpg:large

**Comment by NateWr** [comment]
Ok, I've rebased and now I'm getting that error with the settings wizard:

https://travis-ci.org/pkp/ojs/jobs/151812207#L829

I'm not sure what's going on with this one. I noticed that the test involves a dual-language journal, so I turned on the multi-language setting to test, but I still get the Settings Wizard pop up when it should.

Is it possible that it's just timing out? Creating a new journal takes a long time on my machine (15-20 seconds). If the tests are running on a server without much memory, maybe it's taking too long?

**Comment by bozana** [comment]
@NateWr, have you rebased my last issue 1707? There is the fix for that...

**Comment by NateWr** [comment]
Hmm I thought I rebased on latest master. I'll try again...

**Comment by NateWr** [comment]
Ok, the OJS test has finally passed. I expect OMP to follow shortly. @bozana can you code review?
https://github.com/pkp/pkp-lib/pull/1727
https://github.com/pkp/ojs/pull/961
https://github.com/pkp/omp/pull/316

**Comment by bozana** [comment]
@NateWr, just a couple of minor comments. Great work! :-)))

**Comment by NateWr** [comment]
Ok, Alec's commented on the [last remaining question](https://github.com/pkp/pkp-lib/pull/1727/files/04bfa236cdbe44f450dbb77b86ef30bf0a6738f6..0ce7954d351902792c9d78a3a0bc9b3ad33935ef#r75151703) so I think it's ready for a final review, @bozana.

**Comment by bozana** [comment]
@NateWr, everything OK, if you could just rebase the branches because of the merge conflicts? I will then merge...

**Comment by NateWr** [comment]
I think this is ready to go. The OJS tests are passing but the OMP tests keep failing due to what looks like a Selenium server issue. I've restarted them but they failed again.

https://travis-ci.org/pkp/omp/jobs/153351663#L1707

Is there some kind of problem with the Selenium server at the moment or is there a real issue with OMP? There just isn't a lot that changed in the OMP PR.

**Comment by bozana** [comment]
Merged, thanks @NateWr! Ready for closing?

**Comment by NateWr** [comment]
Reassigning this to 3.1. There are a few things in here worth addressing but not urgent.

**Comment by NateWr** [comment]
Closing as obsolete.
