### ISSUE TITLE
[PKP PLN] Add issue-level information to deposit package

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1494]
It is important to preserve a historical record of issue-level information that changes over time. We should capture the following kinds of elements in each deposit package: 
- Editorial masthead info (under OJS 2.x this would be editorial groups, and the names/emails/affiliations assigned to each group)
- Publisher info (setup step 1.5)
- Sponsoring organizations (1.6)
- Sources of support (1.7)
- Journal history (1.9)

Also consider collecting policies: 
- Focus and Scope (2.1)
- Review policy (2.2)
- Privacy statement (2.3)
- OA Policy (4.1)
- Journal section policies (Journal Management -> Journal Sections)

This is a relatively low-priority feature request, but something that should be considered in due time.

**Comment by jmacgreg** [comment]
Adding a few participants: @mjordan, @ubermichael.

**Comment by ubermichael** [comment]
None of that seems particularly challenging. It's  matter of exporting the data from OJS and including it in each deposit Bag. For me, the biggest challenge is figuring out how to get at the data in OJS, but that's just because I'm not too familiar with the internals.

**Comment by NateWr** [comment]
@jmacgreg is this still relevant? It refers to several pieces of data that only exist in 2.x.

**Comment by jmacgreg** [comment]
I think this can safely be closed.
