### ISSUE TITLE
[OJS] OJS 3.0 Undefined method getFileSize()

### ISSUE THREAD

**Issue by sondh** [pkp/pkp-lib#1495]
We have a fairly vanilla version of OJS 3.0 we are playing with, see image for setup. 

![screen shot 2016-05-27 at 11 26 05 am](https://cloud.githubusercontent.com/assets/2636627/15621842/8899fa00-23ff-11e6-83ae-02ee2bab6e7c.png)

Trying to load a simple HTML file into a gallery and view the page resulted in the following error

`Fatal error: Call to undefined method ArticleGalley::getFileSize() in /var/www/html/plugins/generic/usageEvent/UsageEventPlugin.inc.php on line 216`

Here is the HTML file if interested:
```
<!doctype html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <title>Test HTML Article File</title>

</head>

<body>
  <h1>Here is the test title</h1>
  <p>Here is some test body text</p>
</body>
</html>
```

OJS accurately recognizes the file as HTML under type.

Thoughts?

**Comment by asmecher** [comment]
@sondh, I'm working on some fairly big changes to this aspect of the code over at https://github.com/pkp/pkp-lib/issues/1472 -- I hope to get it merged into the master branch in the next week or so. I'd suggest watching for notifications on that issue, and when it's merged, let me know if it's working better for your requirements.
