### ISSUE TITLE
[PKP PLN] "Primary contact" used in preamble to terms of use

### ISSUE THREAD

**Issue by mjordan** [pkp/pkp-lib#1496]
The preamble to the terms of use says "As Primary Contact, I, in good faith" but if I am not mistaken, accepting the terms of use is only available to the Journal Manager role, and that the journal manger may not be the same person as the primary contact. I think it's more accurate to say "As journal manager, I, in good faith....". 

Tagging @jmacgreg for clarification on this distinction, crediting @bronwens for noticing it.

**Comment by ubermichael** [comment]
Interesting. I didn't notice this one come in at all. I'll make the change.

**Comment by asmecher** [comment]
Scheduling for 2.4.8-1 so it's not forgotten, though of course it can be deferred if we decide.

**Comment by mjordan** [comment]
@jmacgreg would you mind clarifying the distinction first, i.e., it is the journal manager who agrees, not the primary contact?

**Comment by jmacgreg** [comment]
Correct - a journal manager (of which there can be more than one) can use the plugin, but there's no way to confirm that that person is also the "primary contact", which is just a name and email address added to journal setup. What about simply removing the distinction: "I, in good faith ..."

**Comment by mjordan** [comment]
Thanks. We'd have to run removing the "in good faith" part by our legalistic overloard(s).....

**Comment by ubermichael** [comment]
@jmacgreg Are you suggesting only removing "As Primary Contact, " so it would read "I, in good faith, accept and confirm the following terms and conditions..."

**Comment by jmacgreg** [comment]
@ubermichael correct!

**Comment by mjordan** [comment]
Ah, sorry, I misunderstood but fully support that solution. Should still inform those that helped draft the existing text. I can do that.

**Comment by ubermichael** [comment]
Ok. Are we good to go with this change then?

**Comment by mjordan** [comment]
Not yet, am mailing to get sign off.

**Comment by mjordan** [comment]
Looks like "As Journal Manager, I, in good faith" is the preferred version.

**Comment by ubermichael** [comment]
Pull request in, after some confused futzing on my part. Commit 39011b0 can be ignored. If anyone can tell me how to delete it, I'd be grateful.

**Comment by mjordan** [comment]
@ubermichael, looks good. AFAICT both commits are identical so git may not care there are two of them in one PR... @asmecher feel free to merge or authorize me to do so.

**Comment by asmecher** [comment]
Merged and cherry-picked forward to `ojs-dev-2_4`. Thanks, @mjordan and @ubermichael.
