### ISSUE TITLE
Improve Crossref statuses

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1498]
There are some things to be improved in the Crossref plugin for OJS.2.4.x:
- [x] 1) Let the scheduled task always update statuses of unregistered DOIs -- to have all the current statuses. -- At the moment this is done only if 'automatic deposit' is configured. I would like to separate status update from automatic deposit i.e. always update statuses (if there are Crossref username + password), and deposit automatically only if the option is selected.
- [x] 2) Additionally, provide the button 'Check status'. There will be only button i.e. no action link (because of the space in the table column). This function will use Crossref API to get the current deposit status.
- [x] 3) Consider/save only the last deposit status. -- Currently, the plugin is going through all Crossref deposit statuses and if it finds "completed" it takes it, marks the DOI registered, and stops. But, what if the status was first completed, but then later there was an attempt to update the DOI that failed? -- It would be more correct to consider only the last deposit status.
- [x] 4 a) Automatically deposit only unregistered DOIs with no status. -- At the moment also DOIs with status = failed and status = submitted are considered and thus redeposited (which could, in case of an failure, lead to failures over and over again).
- [ ] 4 b) After a failure, because the status = failed is not considered for automatic deposit (s. 4a), eventually give the user a possibility to mark an article as corrected and ready to be automatically deposited again, after he/she solved the problem. Else, the user can still use the "Register" button.
- [x] 5) Rename the current statuses, consider the following statuses:
- Not deposited: no deposit attempt has been made for this DOI.
- Submitted: this DOI has been submitted for the deposit.
- Deposited: the DOI has been deposited to Crossref, but may not be active yet.
- Active: the DOI has been deposited, and is resolving correctly.
- Failed: the DOI deposit has failed.  
- Marked registered: the DOI is manually marked as registered.
Note: Internally, for the DB, the old naming that is the same as Crossref naming + 'markedRegistered' will remain. The constants will be defined and a status mapping (from the internally DB naming to the text that should be displayed to the users) will be implemented and used. 
- [x] 6) Always provide the button "Mark registered", that will mark the object as registered (set the setting 'crossref::registeredDoi') and set it's status to 'markedRegistered'.
- [x] 7) If the scheduled task founded a new DOI with status = failed, create a notification for all journal managers.
- [x] 8) Implement some new UI/UX improvements: 
- Simplified number of pages: Now there is one main menu item "Manage DOIs" (instead of "Export unregistered articles", "Export Issues" and "Export articles")
- On the "Manage DOIs" page, there is the menu item "Manage Issues" (equivalent to the old "Export Issues").
- The articles are listed by their statuses (i.e. the filters all, not deposited, failed, submitted, deposited, active exist).
- The not deposited articles are pre-selected.
- "Export XML" button is renamed into "Download XML".
- A new column "DOI" is added. If the user is an editor, the DOIs are linked to the article metadata form.
- [x] 9) The issue https://github.com/pkp/pkp-lib/issues/1543 corrected.

**Comment by jmacgreg** [comment]
(I had no idea you could have checklists in Github!! That's amazing!!)

**Comment by AhemNason** [comment]
It's just markdown :) 

Just throw in ```[ ]``` before an item and it'll create a checkbox. I hope to go over this stuff sooner than later, by the way. Unfortunately, it might have to happen either while I'm away or the following week.

**Comment by rlammey** [comment]
These updates look great. Patricia from our support team had a quick question: 

For #5 I am curious about the status ‘Deposited: the DOI has been deposited to Crossref, but may not be active yet.’ if a DOI is deposited it’s automatically ‘active’ (at least in the linking sense), maybe I’m missing something?

I was thinking its when you've deposited the XML but it hasn't been processed (sitting in our queue) so the DOI isn't 'live' yet. And then stage Submitted: this DOI has been submitted for the deposit - corresponds to the 'success' message you get when Crossref accepts the deposit in the first place but hasn't started to process it yet. Is that right? Thanks!

**Comment by bozana** [comment]
@rlammey, yes, you are right:
For #5: 'Deposited' means when deposited XML is successfully processed (and we get the status = "completed" from Crossref deposits API) but the DOI is still not 'live' -- we were told that "there is a delay between a deposit completing successfully and a DOI being 'ready'.".
And 'Submitted' is when the XML is uploaded/submitted but hasn't started to be processed yet.

**Comment by asmecher** [comment]
@jmacgreg and @AhemNason, are you two testing this one? It's filed against 2.4.9 but could be cherry-picked into 2.4.8-1 if it's stable and everyone thinks that's appropriate.

**Comment by AhemNason** [comment]
James and I are hoping to test all these changes again on Monday. There were some significant changes we asked for we need to retest. James is dealing with travelling stuff today, so we're hoping early next week will be time for us to sign off.

**Comment by asmecher** [comment]
OK, thanks!

**Comment by asmecher** [comment]
@bozana, I merged the OJS 2.4.8-1 PR -- is this ready to close?

**Comment by bozana** [comment]
I closed the issue and will cherry-pick it to dev soon... :-) Thanks!
