### ISSUE TITLE
[OJS] bug in admin roles?

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1499]
I'm not sure about this. 
My system currently only contains the admin and one other user. I submitted an article as the user. Then - as admin - I wanted to use assign the submission but although admin has been assigned to be Journal editor I can't add admin as journal editor in add paricipant dialog. For testing, I added jouenal manager as role for admin. This can be used in the add participants dialog. 
Is this just my misunderstanding of the roles or is this a bug? 

I'm running ojs 3.0 (updated this morning) on debian jessie.

**Comment by asmecher** [comment]
@henkela, if I understand your situation correctly, it's currently by design -- the admin doesn't get implicit manager/editor access -- but that's likely going to lead to problems like yours, where admins are expected to get that access. See https://github.com/pkp/pkp-lib/issues/440 for some discussion and a proposed solution. Did I understand the issue correctly?

**Comment by henkela** [comment]
Thanks for the quick reply!
Well, sort of yes. ;-)
In the roles tab I see that admin has the role jornal editor and expected that this is the role for assigning submissions to review, hence give admin the rights to do so. But only if I assign journal manager as a role to the admin the account is able to do so. 

By the way, if I assign external user and author to the same user that user can be assigned to review his very own maniscript. Should there be a check to prevent this situation? 

(I will send a pull request these days for some German translations that I did...)

**Comment by asmecher** [comment]
Hmm, I'm having trouble replicating this, though I'm not sure I'm following the same pattern. Would it be possible for you to send me a database dump (neutering it as necessary) and steps to reproduce?

**Comment by henkela** [comment]
These are the steps that I did to observe both the admin not being able to put a submission to review and an author being his own reviewer.  
I installed a fresh OJS with admin and english and german language. 
Then I added a dummy journal. 
After that I added an user assigned with external reviewer and author. 
I logged in as this user. 
I submitted an article as this user. 
I logged of as this user. 
Now - being admin again - I went to the submission view and wanted to assign the submission to review but the button doesn't show up. 
I went to roles and added Journal manager for the admin. 
Then I had the button for getting the manuscript to review. 
In the review pane I added a reviewer.
Since only one user is there, which has the role external reviewer (and author) I used that one. 
Now, the author is the reviewer of his own paper. 
I logged in as the user again and did the review. 
I logged off as the user and approved the review as journal manager, which was minor revisions, so I additionally asked for revisions.  
I logged in as the user and clicked on the first task, which was a broken link. Then I accessed the submission view via the menu and everything looked fine. 

I hope these are not too much steps and you get what I didn't. I admit it's a sort of evil test but having a system with reviewer and authors that might be the same person at some time I was wondering if OJS detects if a self-review happens in case a journal manager is really really tired ;-)

I attached a database dump of my development clone that I did today (and where I actually tried what I described with a very fresh install and database to rule out that I did some mess with my production install)
[db_dump.zip](https://github.com/pkp/pkp-lib/files/291774/db_dump.zip)

**Comment by bozana** [comment]
@henkela, @asmecher, I just tested the current OJS master branch and the admin user does get implicitly "Journal manager" role. 
The new submitted article can then not be "Send to review" till a Journal editor is assigned in the Participants grid. This is the current workflow.
Thus, I think this issue can be closed?

**Comment by asmecher** [comment]
Yes, that sounds reasonable. Thanks!
