### ISSUE TITLE
[OMP] hide physical dimensions when empty

### ISSUE THREAD

**Issue by lilients** [pkp/pkp-lib#1500]
Hi,

a physical publicationformat is displayed with "Physical Dimensions" at the book page although there is no information added.
![bug_physical-dimensions](https://cloud.githubusercontent.com/assets/7815226/15675578/ea5da674-2742-11e6-9e3e-d86d70cbb551.PNG)

I changed the line 390 in /templates/frontend/objects/monograph_full.tpl from 
`{if $publicationFormat->getPhysicalFormat()}`
to:
`{if $publicationFormat->getPhysicalFormat() && $publicationFormat->getDimensions() != ''}`
to solve this problem.

Is that a correct solution or do you have a better idea? I think a fix for omp-stable-1_2_0 would be useful.

Best,
Svantje

**Comment by asmecher** [comment]
Thanks for reporting, @lilients -- throwing over to you, @NateWr, for a quick bit of fun.

**Comment by NateWr** [comment]
Looks like a good solution @lilients. Are you able to submit a PR?

**Comment by lilients** [comment]
here it is: https://github.com/pkp/omp/pull/295

**Comment by NateWr** [comment]
Thanks @lilients! I've merged that PR now (sorry for the delay, I was off on holiday).
