### ISSUE TITLE
article report considers only UI and primary locale

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1502]
... but an article metadata can be in another locale, not necessarily in the  primary locale, but in the article locale, as far as I know it... so in that case, if not found in UI and primary locale, the article will not be listed (OJS 3.0)...

**Comment by NateWr** [comment]
@bozana is this going to be obsolete with work on #7318?

**Comment by bozana** [comment]
Hi @NateWr,
No, article report is different -- it lists all articles and all their metadata -- no stats... So this report I don't have to touch for stats work...

**Comment by bozana** [comment]
It seems this particular issue was solved, now the submission list is gotten differently, s. https://github.com/pkp/ojs/blob/stable-3_3_0/plugins/reports/articles/ArticleReportPlugin.inc.php#L88. thus, all articles should be listed/considered...
However there is still an issue with languages and metadata displayed in the report. For that I will open a new issue.
Closing this one...
