### ISSUE TITLE
[OJS] Language translation not working in 'Workflow Settings' and 'Submission'

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1505]
Hi, 
me again :$
When I added the german translations I came cross fields that are not replaced when I change the language from english to german. Most of them were just missing but at least ##grid.genres.article## is not getting replaced although I added it to locale/de_DE/default.xml
If you could point me to the appropriate php-file I could have a look myself if something's missing there, too. 
Best, 
Andreas

**Comment by asmecher** [comment]
@mtub might be the best to answer these kinds of questions -- but if the English-language translation is working but the German is not, then perhaps the translation has been added to the wrong .xml file? Translation files are loaded selectively.

**Comment by henkela** [comment]
Hmm, I found the grid.genres.article in locale/en_US/default.xml that's why I added it to the according default.xml. I do find both values in the cache/fc-locale files, too. Just it isn't replaced when I load the page.

**Comment by asmecher** [comment]
Ah, defaults are handled a little differently. When you create a journal (or press in OMP) some settings are installed into the database -- see `registry/journalSettings.xml`. Then the user goes through setup and customizes those in the database. If the translation isn't present at the time the defaults are installed, the settings in the database will be untranslated. Does that make sense?

**Comment by henkela** [comment]
I understand that. 
Are there any means to push changes on the defaults to the database? Like, for example, let's say there is an update of OJS that introduces a new defaults-field, how would the database get updated?

**Comment by asmecher** [comment]
@henkela, generally we avoid situations where we make assumptions about changes like that -- for example, introducing a default policy during an upgrade, when the journal might not at all agree with that policy. But there are some examples, e.g. introducing a new email template or making a correction to a typo in the database. These are implemented in the upgrade script, which is coordinated in `dbscripts/xml/upgrade.xml`. It refers to a lot of other XML scripts for specific versions, and these are in `dbscripts/xml/upgrade/*.xml`.

**Comment by henkela** [comment]
Dear @asmecher, 
sorry to bother again. I've another issue with the translations. I made a new branch in my fork of ojs and pkp/lib for production and introduced my german translations there. But when I want to submit a new article and come cross the upload file modal all translations are not shown. The translations are mainly in lib/pkp/locale/de_DE/submission.xml. I then remembered this thread and adapted the upgrade/*.xml files to push my locales to the db (querying and dropping of table signoffs  gave an error since that table didn't exist anymore so I removed those statements). 
But even after succesfullly running upgrade.php upgrade the translations are not made. Would you have another hint for me?

**Comment by asmecher** [comment]
Have you tried running an XML validator like `xmllint` on your translations? Also, ensure your file permissions in `cache/` are correct (and try deleting all `.php` files from there to flush old cached data).

**Comment by henkela** [comment]
Thank you
Interestingly, at some point it started working. I guess some of my actions triggered a cache refresh then...

**Comment by henkela** [comment]
now, I found it... switching between languages refreshes the cache... 
But here's another one: 
Has something been changed with ##common.file.namingPattern##? It is not replaced anymore. Neither in English nor in German. Instead it's only written ##common.file.namingPattern## in the submission files panel. When I click on it the browser tries to download the file and there the naming seem ok - 1-99Z_Article Text- and so on...

**Comment by asmecher** [comment]
@henkela, you can manually flush the translation file cache by removing `cache/*.php` -- but did you get a validator going? Some of what you're reporting does sound like an XML file validation problem to me.
