### ISSUE TITLE
[OJS] Workflow Settings -> Submission Preparation Checklist multilingual broken

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1513]
Hi @asmecher, 
I came cross another strange behavior. In Workflow settings I switched to german, which worked - so far so good :-). Then I wanted to edit an item of Submission Preparation Checklist. First obesrvation: the edit-context that opens is empty, hence it doesn't contain the existing text. Then I copied the existing text from the the checklist opened the edit-context again and pasted and edited it and saved the changes, which led to the second observation: The changes are not applied to the Checklist. Then I switched to english and found the entry I added in the german version. Seems like the multilingual context switch is not working yet. 
Best, 
Andreas

**Comment by henkela** [comment]
PS: same thing happens when I use "Add Item" in the german context. The item appears in the english context only.

**Comment by asmecher** [comment]
@henkela, what version of OJS were you working with?

**Comment by asmecher** [comment]
Closing (needs feedback).
