### ISSUE TITLE
[OJS] Allow users to remove their own accounts

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1515]
If an user wants to remove their account, they should be able to.

**Comment by asmecher** [comment]
@WaDelma, we'd need to consider what should happen to e.g. published content they submitted, peer reviews they participated in, etc.; those are considered part of the editorial record and may need to be audited later.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
