### ISSUE TITLE
[OJS] PLN Gateway always reports Archive_Tar missing

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#1517]
The PLN Gateway doesn't include the Archive/Tar.php library before checking if the Archive_Tar class is available.

**Comment by ubermichael** [comment]
Looks like I already made a PR for this at https://github.com/pkp/ojs/pull/809 but didn't file the issue.

**Comment by asmecher** [comment]
Merged and cherry-picked back to `ojs-stable-2_4_8`.
