### ISSUE TITLE
TinyMCE missing on manager/editUser

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1522]
In OJS 2.4.x, the TinyMCE editor is not initialized for the Address and Bio field when a manager is editing a user.

See: http://forum.pkp.sfu.ca/t/creating-hyperlink-in-edit-boxes/13541

**Comment by asmecher** [comment]
Is there a PR for this?

**Comment by ctgraham** [comment]
There is now!

**Comment by asmecher** [comment]
Committed and cherry-picked to `ojs-stable-2_4_8`. Thanks, @ctgraham!
