### ISSUE TITLE
Google Analytics plugin

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1525]
I presume the plugin will get a re-work in time for OJS 3. If so, it should probably use the new tracking code, which only requires a single property ID:

https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet

Also, one hook, `Templates::Common::Footer::PageFooter`, should output the code on all frontend pages.

**Comment by asmecher** [comment]
Rewritten into separate repo: http://github.com/pkp/googleAnalytics
Also modernized the tracking JS per @NateWr's comment.
