### ISSUE TITLE
Fix autocomplete for reviewers on frontend

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1526]
Autocomplete returns irrelevant results. This was fixed in #1467 but the registration form changes were already in the process of being merged. See #1467 for simple fix.

**Comment by NateWr** [comment]
Ok I botched the submodule commits on those PRs. Here are new ones:

https://github.com/pkp/pkp-lib/pull/1642
https://github.com/pkp/ojs/pull/948
https://github.com/pkp/omp/pull/312

For some reason the tests don't seem to be getting run on OJS/OMP.

**Comment by asmecher** [comment]
It looks like Travis suffered some kind of queuing outage that's since been fixed; could you re-push the PRs that need testing to run?

**Comment by NateWr** [comment]
I re-pushed the PRs. It looks like OMP passed but OJS is failing on the `pgsql` test:

https://travis-ci.org/pkp/ojs/jobs/148961049#L909

That seems to be failing on test code that's shared between OMP and OJS:

https://github.com/pkp/pkp-lib/blob/master/tests/PKPContentBaseTestCase.inc.php#L118

Should I just try to re-push the OJS PR again to see if it was a fluke?

**Comment by asmecher** [comment]
Looks like a fluke; I restarted the job to see if it passes this time.

**Comment by asmecher** [comment]
Hmm, it looks like the submodule is gone. Did you update it again or something?

**Comment by NateWr** [comment]
I'm not sure what you mean. I see the submodule commit in the OJS and OMP PRs...

**Comment by asmecher** [comment]
I mean after restarting the job I got...

    Unable to checkout '29f6ed64e66b92e18c8f93a47d45c5e3fe18f24a' in submodule path 'lib/pkp'

...suggesting that the lib/pkp submodule got updated again and the old hash doesn't exist anymore.

**Comment by NateWr** [comment]
Oh, yeah that sounds like it could have happened. :) I've refreshed both PRs and tests are running.

**Comment by NateWr** [comment]
Ok, the OJS test failed at the same place. But this time it failed on the `mysql` test, not the `pgsql`.

https://travis-ci.org/pkp/ojs/jobs/149767252#L899

**Comment by asmecher** [comment]
Restarted again -- sounds like a glitch (race condition?), though I'm a little anxious about two hits in a row.

**Comment by asmecher** [comment]
Passed this time. I don't think the failures were your fault, @NateWr -- we'll have to see whether it's a common issue going forward. Merged!
