### ISSUE TITLE
Public identifiers for OMP

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1527]
Migrate pub ids changes from OJS master to OMP master, s. https://github.com/pkp/pkp-lib/issues/1457

- [x] a) add "identifiers" tab to the metadata/edit modal of each publication object (monograph, publication format, file)
- [x] b) introduce "publisher-id" (custom URL identifier) field, add it to the new "identifiers" tab
- [x] c) consider "publisher-id" (custom URL identifier) in the reader interface, s. also issue 1074
- [x] d) implement DOI plugin 
- [x] e) implement URN plugin
- [x] f) implement a different pub ids assignment concept -- the pub ids shouldn't be assigned automatically as till now, but by the editor within the publishing process: 
- on the "identifiers" tab,
- publication formats tab in the catalog-entry modal
- when approving a publication format and file 
- [x] g) UI/UX improvements, s. below

UI/UX:
- Display what is missing in the pub id suffix, why it cannot be assigned.
- Use something like pkp_button_link_offset (like Cancel buttons in modals) for "Clear DOI"/"Clear URN"
- Make "Clear Issue Objects DOIs"/"Clear Issue Objects DOIs" as buttons, something like pkp_button_offset
- Add headings "URN" and "DOI" for the pub id assignment parts on the issue publishing confirmation modal, when publishing an issue.

**Comment by bozana** [comment]
PRs:
pkp-lib: https://github.com/pkp/pkp-lib/pull/1570
omp: https://github.com/pkp/omp/pull/300
ojs: https://github.com/pkp/ojs/pull/897

**Comment by asmecher** [comment]
Thanks, the 3 PRs in https://github.com/pkp/pkp-lib/issues/1527#issuecomment-229285757 look good -- just a couple trivial typos. Do these need to be merged in coordination with the CrossRef stuff?

**Comment by bozana** [comment]
Thanks @asmecher, yes it would be better to merge them at the same time or first, but... also not a very big deal/problem if not :-)
