### ISSUE TITLE
[OJS] Improvements to discussions grid

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1529]
The following are a few improvements to the discussions grid identified during a review of the workflow. The easy ones should be done for OJS 3.0 and the others considered depending on our time and release schedule.
- [x] Discussions: smaller font size for participant names in existing discussion view.
- [x] ~~Discussions: Add Discussion button is causing scroll to jump to top.~~ could not reproduce
- [ ] Discussions: editing discussions allows the full editing process. But maybe it makes sense to only allow participants and the subject of a discussion to be edited.
- [ ] Discussions: filter out closed discussions by default, but allow to show them with visible toggle.
- [ ] Discussions: Those discussions which are currently unread tasks should have their titles bolded to match tasks presentation and ease discovery.

**Comment by NateWr** [comment]
PR with a few small CSS tweaks:
https://github.com/pkp/pkp-lib/pull/1645

I'm going to punt the rest of this to post-3.0 unless there's any major complain.

**Comment by asmecher** [comment]
Merged the PR; yes, that's fine, thanks.

**Comment by NateWr** [comment]
None of this stuff is high priority. I'd rather focus on a) UI/UX testing outcomes and b) UI refactoring where we can take a broader look at improvements to components like the discussions grid.

So closing this, but speak up if there's something here you think is really important.
