### ISSUE TITLE
[OJS] One-click feature to add reviews to email doesn't hide reviewer name

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1531]
All editorial actions on the Review stage include a link to automatically insert reviews into the email sent to the author. When clicked, these reviews include the reviewer's name, even if the review is marked as a blind review.

I believe the reviewer's name should not be included.

This effects the modals for Request Revisions, Resubmit for Review, Send to Copyediting, and Decline Submission.

**Comment by asmecher** [comment]
@NateWr, the reviewer identification in the email template should be e.g. "Reviewer A" and "Reviewer B". Are you seeing the name somewhere?

**Comment by NateWr** [comment]
Yeah it was giving me full names. I'll reconfirm with latest master next
week if youre not seeing it.

**Comment by asmecher** [comment]
Never mind, I see it now.

**Comment by ijrereditor** [comment]
I use Open Journal Systems 2.4.8.3 version. While I am trying to add reviewers' comments to email that will send to authors, I click on the Import Peer Review button. But it includes only Reviewer A, Reviewer B, Reviewer C without reviewers' comments.

**Comment by ijrereditor** [comment]
I hope, somebody can help me with this issue.
iColak

**Comment by asmecher** [comment]
@ijrereditor, please see my follow-up here: https://forum.pkp.sfu.ca/t/review-form-sending-feedback/57961/4
Please continue the conversation over there.
