### ISSUE TITLE
[OJS] Can't submit review modal without uploading a file

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1532]
When viewing a review from the Reviewers grid, the form in the review modal expects a file to be uploaded. But it's also possible that an Editor may set the review recommendation without any file to upload.

The form in this modal should submit even if no files are uploaded.

**Comment by bozana** [comment]
Just a note, if I remember it well: when saving this form, the review is considered as completed. Till now there had to be either reviewer comments or files for a review to be completed, thus I don't know what effect it could have elsewhere in the system if there are not there...

**Comment by NateWr** [comment]
Maybe when I tested I didn't have a review comment either. I'll test again to check but yeah, one or the other should be required probably.

**Comment by NateWr** [comment]
On second though, it seems like the Recommendation should be the one condition for marking a review completed.

![selection_021](https://cloud.githubusercontent.com/assets/2306629/16221697/18b27f1e-378c-11e6-89be-dc588eb5e90d.png)

That's the only bit of the process that is really necessary for editorial interaction, and it means an editor still has to signal some kind of intent before we mark the review as complete.

Whether or not review files or comments exist seems like an extra constraint which may not always apply.

**Comment by bozana** [comment]
We should check that then the further activities in the system do not assume that there is a comment or file...

**Comment by NateWr** [comment]
Good point. For instance all of the editorial actions (request revisions, etc) have a link to add the review comments to the email. Make sure that responds gracefully if no review comment/file exists...

**Comment by asmecher** [comment]
OMP should require a file; OJS should not. Moved OMP-specific notification into the OMP repo and reverted the OJS form handler to plain old AjaxFormHandler.
