### ISSUE TITLE
[OJS] PLN Plugin SQL and Non-Aggregated Columns

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#1533]
Postgres is more picky about non-aggregated columns mixed with DISTINCT and GROUP BY. There's one query in DepositObjectDAO that doesn't aggregate all the columns, and it's causing deposits from Postgres-backed journals to fail.

This issue is similar to pkp/pkp-lib#1038 but specific to Postgres.

**Comment by asmecher** [comment]
@ubermichael, is this ready for closing?

**Comment by ubermichael** [comment]
It should be, yes. I don't know what your process is for cherry picking, so I haven't closed it.

**Comment by asmecher** [comment]
It's already cherry-picked. Closing!
