### ISSUE TITLE
[OJS] PLN Plugin Missing Deposit Type Prevents Deposits

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#1534]
In at least one journal, the plugin_settings table is missing a setting for the PLN plugin: object_type which defaults to 'Issue.' Without that setting, _processNewDepositObjects($journal) falls through the switch cases doing nothing. No packages are created and no packages are sent to the PLN.

**Comment by ubermichael** [comment]
@asmecher What's the PKP policy for switch statements without a default? Seems like this should have logged something or created a notification or something. 

See this example:  https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/generic/pln/classes/tasks/Depositor.inc.php#L221 

The switch does nothing when $objectType is null.

**Comment by asmecher** [comment]
@ubermichael, I generally prefer to have sensible defaults if possible:

    case 'notDefaultCase':
        doSomething();
        break;
    case 'namedDefaultCase':
    default:
        doSomethingElse();
        break;

If there's no sensible default, then generally we've been using asserts:

    default: assert(false);

Not sure if the assertion would've helped in your case.

**Comment by ubermichael** [comment]
Thanks Alec. I don't think the assert would have helped here either.

**Comment by asmecher** [comment]
@ubermichael, I've merged the PR, but note that OJS 2.4.8-1 will be released from the `ojs-stable-2_4_8` branch, not the `ojs-dev-2_4` branch the PR was merged into. I can cherry-pick this over to `ojs-stable-2_4_8`, but are there any others I should pick in as well?

**Comment by ubermichael** [comment]
@asmecher Yes, please cherry-pick this one and https://github.com/pkp/ojs/pull/867 

I didn't even thing to do the PRs against the stable branch. Sorry about that.

**Comment by ubermichael** [comment]
@asmecher Can this one be closed now? I'm not sure on your workflow.

**Comment by asmecher** [comment]
Yes, thanks!
