### ISSUE TITLE
[OJS] Fix cover images for issues and articles

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1536]
The Issue Galley and Issue Cover Image file upload controls are broken. When clicking "Upload File" it tries to submit the whole form in the modal.

**Comment by NateWr** [comment]
For some reason the Issue Cover Image file upload works for me now. I'm modifying a bunch of issue settings so maybe something changed there. Will have to investigate.

**Comment by NateWr** [comment]
This turned into quite a large project. The broken upload controls were caused by duplicate element ids in the forms, which prevented the `plupload` control from aligning the upload control buttons properly.

To fix this, I had to make some changes to upload handler. In the process, I did a lot of refactoring. I'm not happy with the UX flow for cover images, but to improve this I'd need to do rewrite bigger chunks of the upload control. I didn't want to do this so close to OJS 3.0.

Instead, I've refactored the handling of cover images to use the same language and data structure for Monographs, Articles and Issues.

PRs:
https://github.com/pkp/pkp-lib/pull/1666
https://github.com/pkp/ojs/pull/959
https://github.com/pkp/omp/pull/315

Here's a run-down of some of the changes:
- Cover images and cover image alt text is now not localizable. I'm in favor of not localizing the cover image. But to do this will require a new form control to be written.
- OJS included some legacy stuff about cover "pages", as well as a bunch of options for display logic. I've discarded these and refactored setting names to use the common `coverImage` term. The frontend just displays a cover image if one exists.
- The "Cover" tab in the article metadata modal has been removed, and the cover image upload control was added to the metadata form.
- Old, apparently unused, settings related to the cover image were removed: `originalFileName`, `width`, `height`.
- Issue-specific stylesheet uploads are no longer available.
- In the course of updating settings, I touched on the XML import/export plugins. Someone with experience here should look at [this](https://github.com/pkp/ojs/pull/959/files#diff-ed336d112a886f4b426f63371ede4c84R278) and [this](https://github.com/pkp/ojs/pull/959/files#diff-ed336d112a886f4b426f63371ede4c84R278).
- I created a couple of handlers for making ajax requests to delete cover images. Do these need CSRF protection?
- OJS still doesn't resize cover images, like OMP does. I'd like to handle this alongside #787, before or after OJS 3.0.

I've asked @bozana to do a code review if she has time, since I had to touch a lot of new pieces in this.

**Comment by asmecher** [comment]
Sounds good, @NateWr, and agreed with e.g. removing the localization of these images. We may have requests to re-add it later, but overall it's been a confusing feature. @bozana, all yours!

**Comment by bozana** [comment]
@NateWr, I am just testing it locally. See how the cover image area looks for me, after I uploaded an issue image:
![issuecoverimage](https://cloud.githubusercontent.com/assets/378421/17446153/36f23bb0-5b48-11e6-8f29-cf56c5578bf9.png)
Is this correct so? Or is something wrong with my image? :-)

**Comment by bozana** [comment]
@NateWr, I don't know where to put these comments:
- the link for the cover image at the journal start page is wrong, the 'issue' page is missing in the URL

**Comment by bozana** [comment]
this is how my strange article with lots of galleys and a cover image looks like in the TOC, ok so?
![articlecoverimage](https://cloud.githubusercontent.com/assets/378421/17446618/5cff4300-5b4a-11e6-8010-4b6ad850f95b.png)

**Comment by bozana** [comment]
Some do like to put the cover image description (e.g. the license information) below to it, s. for example: 
https://www.querelles-net.de/index.php/qn/issue/view/17-2 
http://www.fkw-journal.de/index.php/fkw/issue/view/72
Shall we support that in 3.0? On the other side, on the archive page they were also not displayed....

**Comment by NateWr** [comment]
Thanks for the awesome code review! Very helpful. I think I've addressed everything you raised. Just one thing I couldn't reproduce that remains to be fixed.

Re: https://github.com/pkp/pkp-lib/issues/1536#issuecomment-237921642
I'm unable to reproduce that issue with the cover image breaking out of the modal. What browser and version are you using? Did you flush the CSS cache?

Re: https://github.com/pkp/pkp-lib/issues/1536#issuecomment-237931304
The cover description is related to the old cover page display option, which I've also removed. I'd rather leave it out. The alt text could be repurposed for this and displayed in a template if so desired.

**Comment by bozana** [comment]
Hmmm... Yes, I deleted the CSS cache... I use Iceweasel 38.8.0 :-) So maybe not quite the representative... :-)

**Comment by NateWr** [comment]
@asmecher I'm getting an JS linting error:

```
WARNING - Property refresh never defined on $.pkp.controllers.UploaderHandler.pluploader
	  this.pluploader.refresh();
```

`this.pluploader` stores the `plupload` instance:

```
this.pluploader = new plupload.Uploader(uploaderOptions);
```

Obviously we're not going to define every function of the uploader. How am I meant to handle this warning?

https://travis-ci.org/pkp/ojs/jobs/151169768#L844

**Comment by NateWr** [comment]
@bozana I've updated the PRs to address your latest [comments](https://github.com/pkp/ojs/pull/959#issuecomment-238203062). The image layout issue in IceWeasel has me a bit stumped. As far as I'm aware, IceWeasel should be a pretty light fork of Firefox to handle licensing issues. I imagine the rendering engines won't have been changed, but I can't reproduce it in my FireFox. I'm hoping this is just a small rendering bug that FireFox has fixed and IceWeasel will catch up soon...

Regarding the tests failing. I've made some JS linting fixes with one more to go. The PHP tests have me a bit more confused. It's failing on this line in `20-CreateJournalTest.php`:

```
$this->waitForElementPresent('css=div.header:contains(\'Settings Wizard\')');
```

I tested the wizard myself and the element exists with the text content as I'd expect. I thought it might be because the CSS selector wasn't specific enough (there are other `div.header` elements). So I changed it to this:

```
$this->waitForElementPresent('css=div.pkp_modal_panel div.header:contains(\'Settings Wizard\')');
```

But the test [still failed](https://travis-ci.org/pkp/ojs/jobs/151169770#L816). Any ideas here?

**Comment by asmecher** [comment]
@NateWr, there doesn't seem to be a single consistent JS ecosystem for sharing externs, so we've got a cobbled-together set of basic definitions in `lib/pkp/tools/closure-externs.js`; you'll need to add this there.

**Comment by NateWr** [comment]
Ok, the JS linting tests are passing now. It's just this weird test failure with the "Settings Wizard"...

**Comment by asmecher** [comment]
@bozana, assigning this to you officially :) It looks like Nate's got the JS linting problems fixed, so merging this in will get the master branch Travis testing back on track.

**Comment by NateWr** [comment]
@asmecher Aren't the tests still failing on this "Settings Wizard" thing?

**Comment by bozana** [comment]
@NateWr, all 3 PRs merged, thanks!!! Can this issue be closed now?

**Comment by bozana** [comment]
@NateWr, I've just wanted to create a new issue and I see there the place to upload stylesheets. Didn't we wanted to remove that? If so, would you take a look?

**Comment by NateWr** [comment]
:) no worries!
