### ISSUE TITLE
[OMP] upgrade 1.1.1.1 to 1.2.0 fails using postgres database

### ISSUE THREAD

**Issue by nielsb** [pkp/pkp-lib#1538]
In the server log I find this:

ERROR:  type "serial" does not exist
STATEMENT:  ALTER TABLE auth_sources ALTER COLUMN auth_id TYPE SERIAL

**Comment by asmecher** [comment]
Hi @nielsb -- are you using the command-line upgrade tool? If so, could you post the complete output? If you're using the web-based upgrade tool, try the command-line one; it provides more complete debugging information.

**Comment by nielsb** [comment]
I use the cli, but it does not give any hints at all :-(

[omp@portia omp-1.2.0]$ php tools/upgrade.php upgrade
[pre-install]
[load: upgrade.xml]
[version: 1.2.0.0]
[data: dbscripts/xml/upgrade/1.2.0.0_preupdate.xml (skipped)]
[schema: lib/pkp/xml/schema/common.xml]
ERROR: Upgrade failed: DB: ERROR:  type "serial" does not exist

The problem is that postgres does not have the type serial as a native type.

This is CentOS 6, php 5.3.3, postgres 9.2.16

**Comment by asmecher** [comment]
@nielsb, can you send me a database dump to try myself? It's true that `serial` is not a native type in PostgreSQL, but that shouldn't cause a problem unless something like OTOH one of the `serial` columns isn't the type PostgreSQL expects it to be.

**Comment by nielsb** [comment]
No problem, this is a test installation anyway, so it has no interesting data in it. I have mailed it to you private mail.

**Comment by asmecher** [comment]
@nielsb, with apologies for the delay in responding -- I tracked this down to a known issue in the ADODB library we use for database schema management. There's a patch you can apply [in our old forum](https://pkp.sfu.ca/support/forum/viewtopic.php?f=40&t=11896&p=45922#p45922) to work around the problem before running the upgrade script.
