### ISSUE TITLE
Consider deprecated article URLs in OJS 3.0

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1541]
The URLs article/viewFile and article/downloadSuppFile seem not to be used in OJS 3.0, but they should be considered (for old URLs to resolve properly), redirecting either to the article/view (or article/download?). 
Are there any other URLs to be considered in the same way?

**Comment by asmecher** [comment]
Added a 301 redirect for viewFile URLs. Still need to deal with `downloadSuppFile` (after the supp file migration code has been written for upgrade).

**Comment by asmecher** [comment]
Moved suppFile issue to https://github.com/pkp/pkp-lib/issues/1683.
