### ISSUE TITLE
[OMP] i18n assertion failure on DB driver switch statement

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1542]
With today’s latest `HEAD` code:
```
[Tue Jun 21 16:29:25.774095 2016] [:error] [pid 3691] [client 130.126.152.109:43414] PHP Warning:  assert(): Assertion failed in .../lib/pkp/classes/i18n/PKPLocale.inc.php on line 166
```
This is part of a switch statement on the kind of database connection; it falls through to the `default` clause.

I do _not_ have this problem with the latest and greatest OJS, interestingly.

**Comment by asmecher** [comment]
@bozana, could you take a look? This is related to https://github.com/bozana/pkp-lib/commit/93f99149b61ac1ccbd12980b6a8ef2f289137490.

**Comment by bozana** [comment]
@crism, what DB are you using and would it be possible for you to print out "$conn->getDriver()" there?
And, I am not sure I understand where do you have the problem and where not :-\

**Comment by crism** [comment]
@bozana, the returned value is `MySql`, with capitals. The switch statement is looking for `mysql`, all lower-case. This happens multiple times per page render, anywhere on the OMP site.

**Comment by asmecher** [comment]
`crism`, what is the value of `driver` in the `[database]` section of your `config.inc.php`?

**Comment by crism** [comment]
@asmecher—oh, interesting! It’s `MySql` in OMP, and `mysql` in OJS. In both cases, I installed via the Web setup interface… I wonder why OMP chose to write `MySql`. I’ll fix that, but the switch should probably be case-insensitive as there may be other legacy installations that do that.

**Comment by asmecher** [comment]
@crism, are you sure `MySql` wasn't something you changed? I've never seen an install that doesn't use lower-case `mysql`, and I reinstall and rebuild frequently using the automated test framework.

**Comment by crism** [comment]
Hrm. I can’t find anything in the source code history that would have done this. I did test against Postgres and then switch back to MySQL, though I thought I had used the wizard to switch both times. Perhaps I did do it manually, and screwed it up. I’ll close this.

**Comment by asmecher** [comment]
Not a problem -- glad it's working again.
