### ISSUE TITLE
DOI automatic registration

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1543]
DOI export plugins seem to have a few bugs:
- It is looked if the plugin is enabled for a journal, which is not the case for importexport plugins, thus it would be better to look if the username and password are set.
- $this->notify used if there is no DOI prefix set does not exist. Rather this->addExecutionLogEntry should be used.
- The array of unregistered objects instead of the array of object IDs is constructed for the registration.
- There is no check if the DOI can be assigned (e.g. if the object is excluded). In the case an excluded object is in the list, the function _getObjectsFromIds in DOIExportPlugin will return false (for the whole object list/array).

Thus, I am wondering it worked at all ;-)

See:
- https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/importexport/crossref/CrossrefInfoSender.inc.php 
- https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/importexport/datacite/DataciteInfoSender.inc.php 

The CrossRef bug will be solved here: https://github.com/pkp/pkp-lib/issues/1498
The mEDRA fix:
ojs-dev-2_4: https://github.com/pkp/ojs/pull/890
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/891
The DataCite fix:
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/871
ojs-dev-2_4: https://github.com/pkp/ojs/pull/872

**Comment by bozana** [comment]
See PRs for DataCite:
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/871
ojs-dev-2_4: https://github.com/pkp/ojs/pull/872

**Comment by asmecher** [comment]
Thanks for continuing to shepherd this! I merged the two PRs in https://github.com/pkp/pkp-lib/issues/1543#issuecomment-227809046 -- what else is needed for 2.4.8-1?

**Comment by bozana** [comment]
I would like to merge at lease the medra and crossref fix of this issue, but maybe also the whole crossref improvement, after James and Mike tested it, OK?

**Comment by marchitelli** [comment]
Ho @bozana , I applied the fix at https://github.com/pkp/ojs/pull/871 but it seems not working yet.

**Comment by bozana** [comment]
Could you maybe remove the plugins.importexport.datacite.DataciteInfoSender from the database table scheduled_tasks and tehn click on the "Reload Scheduled Tasks" link at the Generic Plugins > Acron Plugin or run "php tools/runScheduledTasks.php plugins/importexport/datacite/scheduledTasks.xml" from you OJS folder?

**Comment by marchitelli** [comment]
Hi @boz, I tried to do this. When I reload scheduled task I see a new raw in the database for datacite with the time when I reloaded acron tasks but I get no effects on the articles waiting for doi registration

**Comment by boz** [comment]
@bozana ^

**Comment by bozana** [comment]
Hmmm... I've just tested it with an old test account and it worked for me. First I had an error that the domain is not correct, because my domain was not the same as the domain registered for that account at DataCite, then I manipulated the DOI URL so that it matches with the domain registered at DataCite and the automatic registration worked. Could you maybe print out the result at the end of the function registerDoi to see what is happening? -- But I remember you said that the manual registration via the "Register" button, using the same function worked, right? Hmmm... 
I could however try to implement it so that the result is printed in the scheduled task log file, if the registration failed -- so that the users could see the failures there.

**Comment by marchitelli** [comment]
Yes, using the DOI manual registration via the web interface it works

this is my log just after deleting the datacite row in scheduled_tasks table and reloading scheduled tasks from acron plugin

```
ojs@ojs01:/ojs$ php tools/runScheduledTasks.php plugins/importexport/datacite/scheduledTasks.xml
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit
ojs2 has produced an error
  Message: WARNING: assert(): Assertion failed
  In file: /ojs/lib/pkp/classes/i18n/PKPLocale.inc.php
  At line: 519
  Stacktrace:
  Server info:
   OS: Linux
   PHP Version: 5.4.45-0+deb7u3
   Apache Version: N/A
   DB Driver: postgres
   DB server version: PostgreSQL 9.1.18 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit


```

**Comment by marchitelli** [comment]
@bozana I think that the warnign reported is not related to the plugin error. May you suggest me how modify the plugin logging? Thanks

**Comment by bozana** [comment]
@marchitelli, I added a small change, to log the registration result in the scheduled task, if the registration failed, s. https://github.com/pkp/ojs/pull/878.
The scheduled task logs are in the OJS file folder under scheduledTaskLogs. For the DataCite scheduled task you will then have to see the last log file with the name something like "DataCiteinfosender-....log"
I hope that you can that way seem if the registration fails and why. But if this is not the case, I don't know what else could be the reason i.e. what else you could take a look at. Then some kind of debugging on different places in the code would be maybe necessary...

**Comment by marchitelli** [comment]
@bozana with the improvement on logging that you made, I caught the error. 
It is an errore on metadata of one article (details below). I am wondering if there is a way to skip articles in error and proceed registering  the others automatically

The error was  '400 - [xml] xml error: cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'nonemptycontentStringType

**Comment by bozana** [comment]
@marchitelli, s. this new issue: https://github.com/pkp/pkp-lib/issues/1558
I.e. I change it so, that the other files can be further processed, if one file fails. But if just one object from the file is wrong, all other objects from that file will not be registered too. I cannot change this. I am not sure if it would make sense to construct one XML file for one object -- this will mean more processing :-(

**Comment by asmecher** [comment]
Is this one finished, @bozana? It looks like it...

**Comment by bozana** [comment]
@asmecher, the Crossref fix will come with https://github.com/pkp/pkp-lib/issues/1498, that is still not merged, @jmacgreg and @AhemNason are testing. Else, yes :-)

**Comment by asmecher** [comment]
OK, closing!
