### ISSUE TITLE
da_DK email template OFR_REVIEW_REMINDER_LATE contains empty subject

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1544]
https://github.com/pkp/ojs/blame/ojs-stable-2_4_8/plugins/generic/objectsForReview/locale/da_DK/emailTemplates.xml#L29

The `subject` column is defined `notnull` in the database, so this causes problems.

**Comment by asmecher** [comment]
@mtub, mind pinging a da_DK translator for this one subject? Or perhaps, for the moment, throwing in a Google Translate placeholder.

**Comment by mtub** [comment]
will take care of this…

**Comment by mtub** [comment]
turns out, all the email subjects are not translated in the da_DK locale of that plugin. have put the English text in the email subject for the moment and will alert the da_DK translators of this
