### ISSUE TITLE
[OJS] PHPUnit cannot be installed with pear

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1547]
The masters readme of the ojs repo says that PHPUnit should be installed with pear from pear.phpunit.de.

This way of installing it has been [deprecated](https://github.com/sebastianbergmann/phpunit/wiki/End-of-Life-for-PEAR-Installation-Method) and thus the readme should be updated to reflect current way of installation.

**Comment by WaDelma** [comment]
Also it's unclear if tests can be run for only pkp-lib or does one need to have application to test pkp-lib.

**Comment by asmecher** [comment]
Updated, thanks!

**Comment by asmecher** [comment]
For more information on testing, see https://pkp.sfu.ca/wiki/index.php?title=Unit_Tests -- and we're relying fairly heavily on Travis for integration into Github rather than developing with phpunit locally; see the `.travis.yml` for details.
