### ISSUE TITLE
[OJS] Add contributor form validation error missing locale string

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1553]
Submission > Metadata > Add Contributor: Try to save form without selecting contributor role and the error message displays missing a locale key.

![selection_023](https://cloud.githubusercontent.com/assets/2306629/16337432/5dbdabc8-3a0d-11e6-9d4e-0595abb83add.png)

**Comment by asmecher** [comment]
These were missing locale keys -- added. They're app-specific and were in OMP but not OJS.
