### ISSUE TITLE
[OJS] first Scheduled Task Log filename is untranslated

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1555]
In OJS 2.4.x, the [`AppLocale::requireComponents()` of `LOCALE_COMPONENT_PKP_ADMIN`](https://github.com/pkp/pkp-lib/blob/ad17dd567068aa7b50f6931edda5617ae6558f8f/classes/scheduledTask/ScheduledTask.inc.php#L59) is too late to catch the first use of [`$this->getName()`](https://github.com/pkp/pkp-lib/blob/ad17dd567068aa7b50f6931edda5617ae6558f8f/classes/scheduledTask/ScheduledTask.inc.php#L48) when instanciating a `ScheduledTask`.

E.g:
```
-rw-r--r-- 1 apache apache     133 Jun 24 09:09 ##admin.scheduledTask.reviewReminder##-576d31124bd19-20160624.log
-rw-r--r-- 1 apache apache     133 Jun 24 09:09 Subscriptionexpiryreminder-576d31129f173-20160624.log
-rw-r--r-- 1 apache apache     133 Jun 24 09:09 Openaccessnotification-576d3112a6164-20160624.log
-rw-r--r-- 1 apache apache     287 Jun 24 09:09 Usagestatisticsfileloadertask-576d3112d02f0-20160624.log
-rw-r--r-- 1 apache apache     610 Jun 24 09:09 PKPPLNDepositorTask-576d3113d0ff5-20160624.log
-rw-r--r-- 1 apache apache     133 Jun 24 09:09 CrossRefautomaticregistrationtask-576d311cf0aab-20160624.log
```

This also exists in master:
https://github.com/pkp/pkp-lib/blob/6246b313b461146de2c472a8bcd1d337643cdbf4/classes/scheduledTask/ScheduledTask.inc.php#L39-L60

I'll PR a fix for the missed translation.

**Question: do we really want the filenames to be localized?**

**Comment by asmecher** [comment]
Merged, cherry-picked back to `ojs-stable-2_4_8`, and forward to `master`. Thanks, @ctgraham!
