### ISSUE TITLE
multiple DOI XML file registrations

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1558]
For batch DOI registration e.g. registration of all unregistered objects:
At the moment as soon as one DOI XML file registration is not successfully submitted/registered the processing stops and returns the failure. It could however happen that one fails but the next one is OK and could be submitted/registered successfully, s. https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/importexport/datacite/classes/DOIExportPlugin.inc.php#L697-L701.

This is related to DataCite and mEDRA registration: For DataCite, one XML file per object will be submitted/registered. For mEDRA, one XML file per object type (e.g. one XML file for all issues, one XML file for all articles and one XML file for all galleys) will be submitted/registered.
This is not so important for Crossref, because there will be only one XML file for all articles.

**Comment by bozana** [comment]
PRs:
ojs-dev-2_4: https://github.com/pkp/ojs/pull/881
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/882

**Comment by asmecher** [comment]
Both merged, thanks!

**Comment by marchitelli** [comment]
@bozana is the plugin activation per journal or per site?
It seems that the activation on a single journal enable the automatic registration site wide

So, is it necessary to enable the plugin on single journals?

**Comment by bozana** [comment]
@marchitelli, the activation is per single journal. I haven't tested it with multiple journals, but in the InfoSender i.e. in the plugin scheduled task there is the function _getJournals, that should only return the journals that has the option enabled. I will take a look...

**Comment by bozana** [comment]
@marchitelli, I tested it on my local installation with multiple journals and it worked correctly i.e. only the journals that had the option selected were considered by the scheduled task.
