### ISSUE TITLE
do not consider file size in mEDRA DOI registration for remote galleys

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1559]
Currently in mEDRA DOI registration for galleys, the file size is considered and exported as Extent element:
```
<Extent>
<ExtentType>22</ExtentType>
<ExtentValue>{$fileSize}</ExtentValue>
<ExtentUnit>17</ExtentUnit>
</Extent>
```
For remote galleys there is no file size in the system, thus do not create this element for remote galleys.

**Comment by asmecher** [comment]
Merged and cherry-picked to `ojs-stable-2_4_8`, thanks!

**Comment by bozana** [comment]
How did you manage to cherry pick it so quickly? :-OOO
