### ISSUE TITLE
[OJS] update all locales before OJS 2.4.8-1 release

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1560]
Make sure that the latest translation updates from `ojs-dev-2_4` are included in `ojs-stable-2_4_8` for the release of OJS 2.4.8-1.

**Comment by mtub** [comment]
There's another update coming in...

**Comment by asmecher** [comment]
@mtub, is this ready to close from your perspective?

**Comment by mtub** [comment]
sorry… closing now.
