### ISSUE TITLE
[OJS] Removing user doesn't remove from database

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1571]
I created an account and then deleted it. When trying to create new account with same email as the deleted one OJS complained that user with that email exists. The deleted user is not listed anywhere in OJS.

If I select the users table in database I can see that the deleted user is still there.

**Comment by asmecher** [comment]
That's expected behavior. "Remove" removes all roles; if you want to delete the user, use the "merge users" tool.

**Comment by WaDelma** [comment]
Well currently the user isn't shown anywhere in OJS and cannot be edited at all... So the email that the user has is completely unusable.

**Comment by asmecher** [comment]
Use the Search tool and click the checkbox labeled "Include users with no roles in this journal."

**Comment by WaDelma** [comment]
Well that seems convoluted and hard to find...

**Comment by asmecher** [comment]
That may seem odd if you're considering a single-journal installation, but it makes more sense if you consider multi-journal installations.

**Comment by WaDelma** [comment]
I still think remove is bad name for action: I all other places where term remove is used it means it actually removes what you are removing.
For example I just searched the user without rules and to remove it I just clicked remove again. This opened the confirmation window (which in all other removal cases asks confirmation and doesn't say that removal is actually not removal) and when I clicked ok it said:
> This user does not have any roles.
Which I was going file here as bug until I realized what remove actually does.

Maybe name it 'Unenroll'? Which is what it actually does.

Also I would rename 'Current Users' to 'Current Users with Roles' which is more accurate. Or just put the users without roles to the end into their own section.

And btw currently you can do traditional removal, but it's clunky: Create a dummy account and merge all users that you want to remove to that dummy account.

**Comment by asmecher** [comment]
Agreed that this is a point of some confusion. OJS 3.0 already has some improvements over 2.x in this regard and there's likely room for more. I'm guessing you're working with 2.x? If so, we're unlikely to make changes ourselves but I'd be happy to review/include a pull request.

**Comment by WaDelma** [comment]
I am actually working with 3.0, because our publication is planning on upgrading to it this fall.

**Comment by Potomac** [comment]
We are now in 2019 and it is still a bug in OJS 3.1.2,

I am working with a team who discovers and learns how to use OJS, and  as the other users in this bugreport I think the delete button should really delete the user in the database, 

the current situation brings confusion when we want to recreate the same user or a new user with the email adress of the "deleted" user.

**Comment by asmecher** [comment]
@Potomac, there is no "delete" button, there is "remove" and "merge". Are you using the software in English, or another language?

**Comment by Potomac** [comment]
I use OJS 3.1.2 in french language, the french name for the menu is "Supprimer" (which means in english : "Delete"),

When I click on a such menu "Delete/Supprimer" I expect that the user will be really deleted for the database, so the confusion is still here,

my OJS installation manages one journal (no multi-journal)

**Comment by asmecher** [comment]
Maybe this is a bigger issue in the French translation than e.g. in the English version. In English, at least to me, "remove" isn't as strong a term as "delete" -- it can suggest that the association between the user and the journal is removed, but that the user account continues in some form. Our translations are all volunteer-maintained, so if you think an adjustment to the translation would cause less confusion for your users, a quick pull request to change it would be welcome.

**Comment by Hikky99** [comment]
I am using OJS in English and I have the same issue since August last year. Is there a fix now?

**Comment by asmecher** [comment]
@Hikky99, have you reviewed the earlier clarification on this issue (e.g. https://github.com/pkp/pkp-lib/issues/1571#issuecomment-229467297)?

**Comment by Hikky99** [comment]
> @Hikky99, have you reviewed the earlier clarification on this issue (e.g. [#1571 (comment)](https://github.com/pkp/pkp-lib/issues/1571#issuecomment-229467297))?

Yes I have. That didn't quite  help I am afraid.

**Comment by asmecher** [comment]
@Hikky99, I guess what I'm asking is...
- Does the clarification between `Merge Users` and `Remove` provide the solution you need?
- If not, would you suggest a particular wording change or similar?

**Comment by Hikky99** [comment]
No, the **Merge Users** and **Remove** did not help me.

I added a  user, say Tom Little to a particular role. When I viewed my user list, Tom Little was not found. I tried adding Tom Little again but I was told Tom Little existed but he certainly was not in the user list.
I cleared cache but still I couldnt add Tom Little. I cannot also remove or merge a User that doesnt exist.

@asmecher This is my situation.

**Comment by asmecher** [comment]
@Hikky99, the user account does exist but has no role to associate it with your journal. The user list by default only shows users that have an association with your journal. See https://github.com/pkp/pkp-lib/issues/1571#issuecomment-229738662 for a way to list other users.

**Comment by Hikky99** [comment]
@asmecher 
My problem is resolved. Than you for been so responsive. I appreciate. Thanks to the community.

**Comment by crest-sarl** [comment]
Please @asmecher how did you solve it?
