### ISSUE TITLE
[OJS] Allow customizing initials

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1572]
Current way of automatically generating initials breaks in some languages.

We had today one author want OJS to not just take first letter, but Sz digraph in their initials and we have had problems with Chinese authors initials before.

One solution would be just generate the initials into a textbox and then allow editing them afterwards if necessary.

**Comment by NateWr** [comment]
Support for initial has been removed in more recent versions of OJS. Authors can use the preferred name field now.
