### ISSUE TITLE
[OJS] Deleting role is confusing

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1574]
With an admin account one cannot delete default roles, but the button to delete them is still there.

When clicking remove button on role you get message: 

> You are about to remove this role from this context. This operation will also delete related settings and all the users assignments to this role. Do you want to continue?

But if there is any user assigned with that role, the role cannot be actually deleted. Either change the message or make it remove the role anyways.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
