### ISSUE TITLE
[OJS] Stage Assignment doesn't allow removing assignments

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1575]
When changing what powers different roles have the main grid works correctly. But if you click the edit button and try to remove power from role and then click ok it doesn't actually change anything.    Adding powers from edit menu works correctly.

Also if you add/remove powers from roles in main view too quickly the notifications overlap 'Production' column preventing you from editing it.

**Comment by asmecher** [comment]
Fixed in https://github.com/pkp/pkp-lib/commit/090cf49803f5ecdb7277213351c7c648a39d6392. Thanks for reporting!
