### ISSUE TITLE
[OJS] When session times out changing tab in a page doesn't move you to login page

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1576]
If session times out and try to switch a tab in a page (eg. being on Distribution Settings on tab Access and moving to tab Payments) message:

> The current role does not have access to this operation.

is shown instead of moving user to login page.

**Comment by jamshidhashimi** [comment]
For this, I propose adding:

```
// Ensure a logged in user is available
import('[lib.pkp.classes.security.authorization.UserRequiredPolicy](url)');
$this->addPolicy(new UserRequiredPolicy($request, 'user.authorization.loginRequired'));
```
(You can see the [UserRequiredPolicy](https://github.com/pkp/pkp-lib/blob/master/classes/security/authorization/UserRequiredPolicy.inc.php) class here)
before
```
// Ensure we're in a context
import('lib.pkp.classes.security.authorization.ContextRequiredPolicy');
$this->addPolicy(new ContextRequiredPolicy($request, 'user.authorization.noContext'));
```
in [ContextPolicy.inc.php](https://github.com/pkp/pkp-lib/blob/master/classes/security/authorization/internal/ContextPolicy.inc.php).

This way, at least user understands that the session is either destroyed or expired. Through `Handler.js`, a redirect to login page is also possible, but I don't know if that's something we want to do for now.

I tested the functionality and it works fine in my setup.

@asmecher please advice.

**Comment by jamshidhashimi** [comment]
Hi @asmecher. Thank you for the suggestions. It was nice for me to explore the `setAdvice` method and functionality in the codebase. I wanted to add it in `UserRequiredPolicy` but noticed that we don't have to, as the [constructor](https://github.com/pkp/pkp-lib/blob/master/classes/security/authorization/AuthorizationPolicy.inc.php#L46) in `AuthorizationPolicy` is handling that part. So only adding the `UserRequiredPolicy` in the `ContextPolicy` seems working fine, as I suggested above.

On handling errors, I agree and suggest we explore that further, maybe in a different issue? as for example in the context of this issue, on what to do after the user gets the `Login Required' message is to choose what is the best next action: to directly redirect, to show a timer and redirect, or to just show options on what to do and let the user to choose, for example either stay or redirect.

**Comment by asmecher** [comment]
I think that'll work with all the currently coded uses of `ContextPolicy`, but I could imagine cases where `ContextPolicy` would be used to ensure that there's a context but where a user login shouldn't be required. Maybe `ContextAccessPolicy` would be a better fit? That requires at least one role in the current context, so it would presume that a user is present.

**Comment by jamshidhashimi** [comment]
Hi @asmecher. Currently `ContextAccessPolicy` is not called when dealing with `Submissions`. Having the `UserRequiredPolicy` check in `ContextAccessPolicy` is only triggered in the `Settings` section for example. This may need some work to do, to keep things aligned there. For now, as `ContextAccessPolicy` is extending `ContextPolicy`, putting `UserRequiredPolicy` check in the `ContextPolicy` gets triggered in most of the places.

Considering above, here is the current implementation in my own Fork: [i1576-fix](https://github.com/jamshidhashimi/pkp-lib/commit/0ddf8ea873add8c2106eed46188dbc660ef2c07c)

Can you please review?

**Comment by jamshidhashimi** [comment]
@asmecher please review the following draft PRs:

https://github.com/pkp/pkp-lib/pull/4531
https://github.com/pkp/ojs/pull/2309

**Comment by asmecher** [comment]
Those drafts both look fine, @jamshidhashimi! I suppose the relevant change from before is the addition of the policy to PaymentsHandler?

**Comment by jamshidhashimi** [comment]
Thanks @asmecher. This is the same PR as before, but there were some unwanted submodule additions that I removed and submitted a clean PR.

**Comment by asmecher** [comment]
Gotcha, thanks. The PRs look clean, but I think the TabHandler work still remains to be looked at, right?

**Comment by jamshidhashimi** [comment]
Yes @asmecher. That's correct.

**Comment by NateWr** [comment]
Closing this since the distribution settings tabs no longer use the `TabHandler`.
