### ISSUE TITLE
[OJS] Add marker for user accounts that are disabled

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1579]
Currently in user listing it's hard to see which users are disabled: You have to look each user individually.

A row should be added in which there is marker that indicates if the user is disabled.

Maybe even make it checkbox which allows toggling the disabled state.

**Comment by WaDelma** [comment]
Or just make it a status row which tells the state of the user: is it disabled, is it activated, is it pending password change.

Other choice for indication would be to have different background color for each of these. Only thing to make sure then is that colorblindness doesn't make it unreadable.

**Comment by NateWr** [comment]
Closing this in favor of https://github.com/pkp/pkp-lib/issues/2860, which includes screenshots of work that includes this change.
