### ISSUE TITLE
[OJS] OJS3 locale update

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1582]
* start with OJS2 locale files (`ojs-dev-2_4` branch)
* replicate changes to keys and key names
* complete translations for release of OJS3

**Comment by asmecher** [comment]
Last things needing doing:

 - [ ] really incomplete locales excluded from build
 - [ ] completeness flags set in locales.xml

**Comment by asmecher** [comment]
FYI, I'm pulling a few last details in from the `translation3` install now. As of this moment (unless someone tells me otherwise), anything going on that install will probably not make the 3.0 release.

**Comment by asmecher** [comment]
OK, everything there that's not already included is inessential and could use a bit of review for details before committing. Closing for 3.0!
