### ISSUE TITLE
[OJS] Send bulk email in batches

### ISSUE THREAD

**Issue by vnen** [pkp/pkp-lib#1583]
When I try to send the new issue notification email, the SMTP server don't handle them all, so only a few are actually sent. This makes sense since servers throttle it to avoid spam.

Most applications that need to send lots of email do it in small batches. Since there's already a system for scheduled tasks, it would be interesting to use it to dilute the email queue in small batches and send them over a longer time.

**Comment by asmecher** [comment]
@vnen, is this the Editor's "Notify Users" link? That's already batched -- see `pages/editor/IssueManagementHandler.inc.php` and `lib/pkp/classes/mail/MassMail.inc.php`.
