### ISSUE TITLE
Crossref plugin tries to register objects without DOIs

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1585]
In OJS 2.4.x, the CrossrefInfoSender tries to update and register published articles without checking if they are eligible for registration.

See logic at:
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/importexport/crossref/CrossrefInfoSender.inc.php#L58-L82

To reproduce, publish an issue but prevent DOI assignment for the articles.  Run the scheduled task `./plugins/importexport/crossref/scheduledTasks.xml`.  Expected result: no action.  Actual result: each article passes through `$plugin->updateDepositStatus()` with no DOI and throws an assertion error at https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/importexport/datacite/classes/DOIExportPlugin.inc.php#L859 .

**Comment by asmecher** [comment]
@bozana, mind looking at the attached PR and taking care of cherry-picking? Thanks!

**Comment by bozana** [comment]
Merged, thanks a lot! 
There will be a bunch of Crossref plugin improvements coming with this issue: https://github.com/pkp/pkp-lib/issues/1498. The implementation is currently in my OJS repository, branch 1498fix. There, I've already considered this issue, but I will now cherry-picked this PR to the stable branch as well, till those bigger changes are not merged. It is already considered in the master, so no need for cherry-picking it there.
