### ISSUE TITLE
Table of Contents alignment

### ISSUE THREAD

**Issue by mjb24v** [pkp/pkp-lib#1591]
Hi there,
Since upgrading to the latest version of OJS (2.4.8.0), the alignment of the page numbers of PDF links seems off (in our theme but also when I switch back to one of the default themes). They are no longer vertically aligned  - see attached screenshot. 
![toc](https://cloud.githubusercontent.com/assets/20366189/16706281/14c75cd8-459e-11e6-88af-fc25cbaa22c3.png)

**Comment by bozana** [comment]
Hmmm... Maybe you could try to clear your cache, OJS and browser cache?

**Comment by mjb24v** [comment]
Thanks for the reply! Clearing the various caches doesn't seem to have done anything (see http://press-start.gla.ac.uk/index.php/press-start/issue/view/3 for example) so I might just see if I can fix it myself in the theme template with some CSS.

**Comment by bozana** [comment]
Hmmm... Your common.css seems not to be the current one:
Your: http://press-start.gla.ac.uk/lib/pkp/styles/common.css
Current 2.4.8 one: https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/styles/common.css
Could it be that you have somehow missed CSS at the update?

**Comment by mjb24v** [comment]
Interesting. The upgrade process was a bit of a disaster (installing the full package broke the site) so we ended up using the command line patch option, which I've not tried before. Perhaps that missed the CSS stuff. I'll try swapping in the version of common.css from Github...

**Comment by mjb24v** [comment]
And that fixed it (replacing my common.css with that on Github)! Thanks!
