### ISSUE TITLE
remove app/journal-specific language in pkp-lib

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1595]
These should be changed to a broader meaning or moved to the matching application directory. Tracking issue, will add to the list whenever I stumble upon more keys.

This is for the `master` branch.
- [x] `editor.publicIdentificationExistsForTheSameType` ("journal")
- `plugins.metadata.nlm30.nlm30XmlOutput.displayName` ("journal") [This is the name of the tag set, so leaving as is. -AS]
- [x] `plugins.reports.usageStats.metricType`("OMP")
- [x] `plugins.reports.usageStats.report.displayName`("OMP")
- [x] `plugins.reports.usageStats.report.description`("OMP")
- [x] `plugins.reports.usageStats.metricType.full`("OMP")

**Comment by asmecher** [comment]
Last 4 already addressed in other issues.
