### ISSUE TITLE
Implement medra DOI export plugin

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1603]
Note: the solution here considers all galleys with a doi for export. Eventually we would like to differentiate between galleys and consider for example only MonographFiles. But, what to do then with the others, if they get a doi assigned? - the doi should not be assign to them and this would an editor has to take care of - it cannot be done automatically. If the dois are not assigned to them, then the current solution is ok however.

**Comment by asmecher** [comment]
I think that means this is ready to close -- let me know if not, @bozana!
