### ISSUE TITLE
Error in submission review status highlightning

### ISSUE THREAD

**Issue by marchitelli** [pkp/pkp-lib#1606]
Starting from [a thread in the forum](http://forum.pkp.sfu.ca/t/colouring-overdue-reviews/1059/), I found (and hoping corrected) an error in the highlightning logic.

Unfortunately, I committed my fix against a wrong and already open PR. I am working on the editorial issues following your suggestions, but I need more time.

Here the code: https://github.com/pkp/ojs/commit/d8d2eb95bfa7bcf72b207579d5bc1560478e2253
@asmecher, may you check, please, and, if this is ok, cherry pick only this last commit?

Thanks,
andrea

**Comment by asmecher** [comment]
With apologies for leaving this so horribly long -- is it still relevant, @marchitelli?
