### ISSUE TITLE
PLN Deposits fail if metadata contains HTML entities

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1607]
For OJS 2.4.x.

When constructing the XML for the PLN deposit in [DepositPackage.pm](https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/pln/classes/DepositPackage.inc.php), user-entered data could have characters disallowed by XML.  See especially fields like openAccessPolicy or copyrightNotice.

Steps to reproduce:
Copy and paste text into Journal Setup which would cause an HTML entity, such as &laquot;.
Run the PLN deposit task.
PLN deposit results in a 500 error.

**Comment by ctgraham** [comment]
@ubermichael suggests:

> I think the best option is to convert them to proper unicode/utf-8. Iconv should make that pretty easy. 

> I'm not at work this week, and probably won't be able to fix it until next week. Can you let Alec and Mark Jordan know about this? It's a significant enough problem that they may want to hold up the release of 2.4.8.1.

Personally, assuming that HTML is valid content, I would recommend escaping over trying to map the content to Unicode.

**Comment by ubermichael** [comment]
I don't think escaping would be the right thing: it complicates processing further down the road and makes importing/rebuilding the journal more difficult (double decoding!). 

You also suggested that we declare the entities, but that adds a bunch of complexity as well (either add all the HTML 4 entities, link to a DTD with them, or parse the metadata to determine which entities are needed and declare a custom subset). And turning them into numeric entities would work, but the XML is already UTF-8 and a copyright character is easier to read than a numeric entity.

**Comment by asmecher** [comment]
FWIW I also favour escaping -- it's the only thing guaranteed to prevent data loss in the case of a wildly nasty data set (e.g. database dump/reload with different character sets -- this does happen). Since recovery is relatively rare, imposing a bit more work on the restoration process is a lesser evil IMO than not knowing how much of your data you're discarding.

**Comment by ctgraham** [comment]
I think double decoding is appropriate:  One level of escaping for HTML, and one level of escaping for storing HTML in XML.  Alternately, we could encapsulate the HTML inside CDATA references, if you want to avoid the second escape in favor of human readability.

**Comment by ubermichael** [comment]
New patch to use mb_* functions, correct whitespace, and use CDATA sections. Please review.

**Comment by asmecher** [comment]
Merged!

**Comment by asmecher** [comment]
Cherry-picked to `ojs-stable-2_4_8`.
