### ISSUE TITLE
[OJS] Trouble installing

### ISSUE THREAD

**Issue by FlaminSeraphim** [pkp/pkp-lib#1612]
When installing on Ubuntu 16.04 it has php 7. Whenever we try to install ojs it will not work the server gives a error 500. The apache server says that it doesn't like the command String. The apache server says
[Wed Jul 13 15:57:04.629455 2016] [:error] [pid 1115] [client 127.0.0.1:33164] PHP Deprecated:  Non-static method PKPApplication::defineExposedConstant() should not be called statically in /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.inc.php on line 545
[Wed Jul 13 15:57:04.629513 2016] [:error] [pid 1115] [client 127.0.0.1:33164] PHP Deprecated:  Non-static method PKPApplication::getExposedConstants() should not be called statically in /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.inc.php on line 513
[Wed Jul 13 15:57:04.631732 2016] [:error] [pid 1115] [client 127.0.0.1:33164] PHP Fatal error:  Cannot use 'String' as class name as it is reserved in /var/www/html/ojs/lib/pkp/classes/core/String.inc.php on line 57

**Comment by asmecher** [comment]
Also posted [on the forum](http://forum.pkp.sfu.ca/t/support-ubuntu-and-php-versions/16220). (@FlaminSeraphim, please stick to just one venue -- we're a small team, and you'll reach the same people either way.)
