### ISSUE TITLE
Error with implicit authentication (Shibboleth SSO)

### ISSUE THREAD

**Issue by kasioumis** [pkp/pkp-lib#1614]
Running [OJS master](https://github.com/pkp/ojs/commits/master) (up to https://github.com/pkp/ojs/commit/932185bb128c5ab60c9a9b147600801f8fe17218), with `implicit_auth = On` in `config.inc.php`, I'm getting `PHP Fatal error:  Call to undefined method Role::setJournalId() in /opt/ojs3/plugins/implicitAuth/shibboleth/ShibAuthPlugin.inc.php on line 245` after being authenticated by Shibboleth and returning back to OJS. The user I'm logging in with is listed in `implicit_auth_admin_list`.

**Comment by asmecher** [comment]
@kasioumis, I'll take a look at the immediate problem before the release of OJS 3.0, but beware that the current `implicit_auth` setting and related code are not expected to work at the moment and will likely need an overhaul. That code is basically unchanged from its roots in OJS 2.x and needs to be rewritten for 3.0. We will be working on some related topics after the release of OJS 3.0, such as a proper OAuth implementation.

**Comment by asmecher** [comment]
For the moment (for the OJS3.0 release) I've removed the implicitAuth plugin category.

**Comment by kasioumis** [comment]
@asmecher are there any news/timeline on porting implicit authentication (Shibboleth SSO) to OJS3? A github issue to track? Thanks!

**Comment by ctgraham** [comment]
@kasioumis, I've filed this here: https://github.com/pkp/pkp-lib/issues/1963
