### ISSUE TITLE
Reword Add Details to Review Details

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1617]
During the submission process, when uploading a file, step 2 is currently "2. Add Details":

http://journals.sfu.ca/uiux/index.php/publicknowledge/submission/wizard/2?submissionId=35#step-2

This should be changed to "2. Review Details" as there is no longer the requirement to add anything here.

This applies to OJS 3 and OMP 1.2.

**Comment by asmecher** [comment]
Done (master branch): https://github.com/pkp/pkp-lib/commit/473944e0d0ecbd8bde05207ba885192647356e56
I'll leave this open in case you need to do anything in the help files as a result, but feel free to close otherwise.
