### ISSUE TITLE
Block adding discussion to oneself only

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1619]
When using the Add Discussion tool, it is possible for a user to only include themselves in the list of Participants. Testing showed people did this somewhat frequently.

Can we block saving unless the user has included someone other than themselves in the discussion?

**Comment by jamshidhashimi** [comment]
PR:

pkp/pkp-lib#4303 

@asmecher please review. Thanks.

**Comment by asmecher** [comment]
Merged. Thanks, @jamshidhashimi!
