### ISSUE TITLE
Allow editor to change contributor information

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1620]
In Catalog Entry > Monograph, in the List of Contributors section, editors should be able to uncheck whether listed contributors are the "Primary Contact" or "In Browse List". 

http://omp.sfu.ca/uiux/index.php/publicknowledge/workflow/index/16/5

**Comment by bozana** [comment]
@stranack, do you mean that those should be the real checkboxes and not just icons, so that editors do not have to go to "Edit" grid row action to do that?

**Comment by asmecher** [comment]
@stranack, awaiting your feedback!
