### ISSUE TITLE
[OJS] Missing $request param in comment form emails

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#1621]

**Comment by asmecher** [comment]
Is there a particular problem this solves, or is it just a clean-up? OTOH the `$request` object should be nullable all the way down the chain, though at a glance it may affect e.g. logging.

**Comment by mfelczak** [comment]
Hi @asmecher, just tidying up. I followed the chain down, however, and you're right the `$request` object is used for logging as well as cleaning-up attachments (ArticleMailTemplate::send).

I've updated the PRs to also include ProofreadCommentForm.inc.php which I missed.

**Comment by asmecher** [comment]
@mfelczak, is it tested? I like the cleanup but some of that code is such a labyrinth I'm worried about inadvertently introducing e.g. a warning message or something.

**Comment by mfelczak** [comment]
No problem, I'll test it out.

**Comment by mfelczak** [comment]
Unlike the copyediting, layout, and proofreading comment pop-ups, the editor decision comments pop-up doesn't include a 'Save and Email' button (only 'Save' and 'Close') -- @asmecher is this by design or a bug?

**Comment by asmecher** [comment]
I can't think of a reason for it to be that way, though it's never come up, so I'd call it a low priority to change. But go for it if you like.

**Comment by mfelczak** [comment]
Thanks @asmecher. Digging around a bit, this may be on account of the notify author email alongside which the editor comments reside. The notify author email is also tied to a journal setting indicating whether the primary author or all authors should be notified by email. Leaving as-is for now.

**Comment by asmecher** [comment]
@mfelczak, do you mean the open PRs (https://github.com/pkp/ojs/pull/935 and https://github.com/pkp/ojs/pull/934/files) are good to go, or they should not be merged?

**Comment by mfelczak** [comment]
@asmecher, I've had a chance to review this and update the PR. There were already calls that included the $request param e.g. $commentForm->email($request) but it was missing from the method declarations.

**Comment by asmecher** [comment]
OK, thanks!

**Comment by mfelczak** [comment]
Hey @asmecher, just wanted to confirm that you got the above PR (https://github.com/pkp/ojs/pull/979)?

**Comment by asmecher** [comment]
Ah, I see it now. (PRs don't always link consistently to their issues -- best to explicitly note it.) I've merged that and ported it over to `ojs-dev-2_4`.

**Comment by mfelczak** [comment]
Thanks @asmecher, and will do!
