### ISSUE TITLE
Rewrite Custom Locale Plugin for 3.0

### ISSUE THREAD

**Issue by kasioumis** [pkp/pkp-lib#1626]
Running [OJS master](https://github.com/pkp/ojs/commits/master) (up to https://github.com/pkp/ojs/commit/2b52f95537b70085009bfa02ca73fad124e6f0f0), when the "Custom Locale" Plugin is enabled, I'm getting `PHP Fatal error:  Call to a member function getId() on a non-object in /opt/ojs3/plugins/generic/customLocale/CustomLocalePlugin.inc.php on line 27`

**Comment by asmecher** [comment]
That plugin has yet to be rewritten for OJS 3.0 and will not be included in the 3.0 tarball -- nonetheless I'm not getting the message you are. What URL are you looking at within the system?

**Comment by asmecher** [comment]
(When this plugin gets rewritten, the exclusion from the tarball needs removing -- or else this can be distributed via the plugin gallery. Commit: https://github.com/pkp/ojs/commit/d8188f0253a0d44b8527b838ad4953e36786f229)

**Comment by asmecher** [comment]
(@kasioumis, I'm commandeering this issue as a rewrite of that plugin for OJS 3.0.1.)

**Comment by kasioumis** [comment]
@asmecher we get the `PHP Fatal Error` right at the index page. The admin interface works just fine.

**Comment by mtub** [comment]
@asmecher, can you keep me in the loop for when someone is going to work on that plugin? Might be interested in reviewing/commenting.

**Comment by asmecher** [comment]
@mtub, sure, you should be subscribed on the sidebar now that you've commented here.

**Comment by asmecher** [comment]
The plugin is available thanks to LangSci Press over at https://github.com/langsci/customLocale, and I've proposed some changes over on my fork (https://github.com/asmecher/customLocale) that permit it to work with OJS 3.0.1 too. It could use some improvements and I've already sent in a PR to LangSci Press. Feel free to file issues and send PRs to that repository instead. It's best maintained as an external plugin.
