### ISSUE TITLE
[OMP] Length of the rights statement

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#1628]
in omp 1.2 we have a 255 limitation on the form side for the Rights.   May be it is helpful not to control the length of the field, cause in sql  db, it is a text-field. 
Known benefits:
We can add a   HTML snippet there,  as we get from creative commens and display directly in the front-end.

![screenshot from 2016-07-21 09 06 01](https://cloud.githubusercontent.com/assets/1921992/17014033/78fa0bd2-4f22-11e6-8f84-250d014983db.png)

**Comment by withanage** [comment]
@asmecher  thanks for adding it to  1.2.1 . I have  found a similar restriction as above in the description field for the file metada   which we use for submission reviews.

![screenshot from 2016-09-28 13 29 15](https://cloud.githubusercontent.com/assets/1921992/18911905/cb4873a4-857f-11e6-9667-899c9f798673.png)

**Comment by asmecher** [comment]
@withanage, I've removed that limit -- see the above commit.

**Comment by withanage** [comment]
@asmecher  
thanks a lot for the changes. Have tested and works fine.
