### ISSUE TITLE
Add book and chapter DOIs and other public identifiers to the OAI interface in OMP

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1629]
Consider public identifiers (DOI, URN) via the OAI interface in OMP.

**Comment by bozana** [comment]
@asmecher, could you also take a look at this PR: https://github.com/pkp/omp/pull/331 ?

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by bozana** [comment]
PR omp-stable-1_2_0: https://github.com/pkp/omp/pull/332
PR omp-dev-1_2: https://github.com/pkp/omp/pull/333

**Comment by bozana** [comment]
Aaaa... you are so quick! :-)

**Comment by bozana** [comment]
Closing...

**Comment by amandastevens** [comment]
In answering a support question I realized that only DOIs for publication formats were added to the OAI-PMH interface in OMP, not DOIs for chapters or books. Including DOIs for chapters and books has been requested by a PKP-PS client and on the forum (https://forum.pkp.sfu.ca/t/doi-for-chapters-in-omp/33481/5). So I'm reopening this issue.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
