### ISSUE TITLE
Add support for HTML presentation

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1631]
Port the OJS HTML galleys plugin across to OMP for HTML publication.

**Comment by asmecher** [comment]
@stranack, FYI.

**Comment by asmecher** [comment]
@stranack, I've added basic support here (and checked it out on the sfulib install). Does the author have other assets to go with the HTML file, like images & CSS?

**Comment by stranack** [comment]
Yes, both images and css.

**Comment by asmecher** [comment]
Could you email me a set of these for one of the submissions?

**Comment by asmecher** [comment]
@stranack, I have an image and HTML working -- but I don't see the CSS attachment to go with it. Can you send it again?

**Comment by stranack** [comment]
I haven't made a detailed CSS file yet - was waiting until the HTML was ready. Here's a simple one to work with, though:

https://dl.dropboxusercontent.com/u/9529729/psm.css
