### ISSUE TITLE
Loading spinner always appears during journal settings wizard

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1636]
It only appears to effect the first stage of the settings wizard.

![selection_001](https://cloud.githubusercontent.com/assets/2306629/17099931/45d47910-5263-11e6-993c-df89d460ca92.png)

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1638

**Comment by NateWr** [comment]
OJS PR for running tests:
https://github.com/pkp/ojs/pull/954

**Comment by asmecher** [comment]
Merged, thanks!
