### ISSUE TITLE
Can't add discussion with no stage participants

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1640]
If not participants exist in a stage, the new discussion modal will not show any potential recipients. A message should be shown instructing them that discussions can only be initiated with participants.

(Edit - this issue description was modified in line with changes to recipient selection in https://github.com/pkp/pkp-lib/issues/1447)

**Comment by NateWr** [comment]
PRs (tests running):
https://github.com/pkp/pkp-lib/pull/2625
https://github.com/pkp/ojs/pull/1442

**Comment by NateWr** [comment]
@bozana Here's a small one. Mind code reviewing?

**Comment by bozana** [comment]
👍 Merged pkp-lib, thanks!!! Can the issue be closed?
