### ISSUE TITLE
Editor cannot add Section Editors

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1641]
Context: An author has submitted to a section that has no Section Editors assigned (see "Research" in the UI/UX installation).

Problem: When the editor tries to add an SE via the participants grid, no Section Editors are showing in the selection dropdown. Is the section dropdown looking to the section's list of assigned SEs rather than the journal's full list of SEs?

Recommendation: Some journals will overlook adding SEs to sections. We should allow editors to add *any* SE to the participants grid for any submission.

**Comment by stranack** [comment]
Possibly related: When a submission is assigned to a section that has Section Editors, the editor is unable to remove any of those SEs from the participants grid. Having the flexibility to make this kind of change on a submission by submission basis would be useful.

**Comment by asmecher** [comment]
I think your second comment is related to https://github.com/pkp/pkp-lib/commit/090cf49803f5ecdb7277213351c7c648a39d6392 which was a general bug in removing stage participant assignments. That's fixed in the master branch and I've update the OJS uiux installation.
