### ISSUE TITLE
Notes unstyled in submission > more information

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1647]
Submissions > Active > Open Submission > More Information > Add a note to the submission.

![selection_005](https://cloud.githubusercontent.com/assets/2306629/17135580/6615786c-5328-11e6-87e6-92d28e064ffd.png)

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1648

New look:
![selection_006](https://cloud.githubusercontent.com/assets/2306629/17136538/eb36a02a-532d-11e6-8958-fbc54ddee0b5.png)

**Comment by NateWr** [comment]
PR with a few more style adjustments:
https://github.com/pkp/pkp-lib/pull/1681

**Comment by asmecher** [comment]
Merged, thanks -- I think that makes this ready to close again.
