### ISSUE TITLE
Remove the announcement expiry date stamp from UI

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1649]
On both the Announcements page (just under "Read More"):
http://monographs.lib.sfu.ca/index.php/sfulibrary/announcement

and the page for the announcement:
http://monographs.lib.sfu.ca/index.php/sfulibrary/announcement/view/2

the timestamp for the announcement expiry is displayed. This should be removed in both cases.

**Comment by asmecher** [comment]
That was already removed per https://github.com/pkp/pkp-lib/issues/1390 -- the install likely needs to be updated (and the template cache flushed).
