### ISSUE TITLE
typo in PKPAppearanceForm.inc.php

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1652]
Hi, 

in pkp-lib/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php on line 327 there is a semikolon instead of a comma, which breaks the "Appearance-Modal" in Website settings: 

return new LinkAction(
325                         'deleteFile-' . $settingName,
326                         new RemoteActionConfirmationModal(
327                                 **$request->getSession();**
328                                 __('common.confirmDelete'), null,
329                                 $router->url(
330                                         $request, null, null, 'deleteFile', null, array(
331                                                 'fileSettingName' => $settingName,
332                                                 'tab' => 'appearance'
333                                         )
334                                 ),
335                                 'modal_delete'
336                         ),
337                         __('common.delete'),
338                         null
339                 );

**Comment by asmecher** [comment]
Oops -- fixed, thanks for spotting it!
