### ISSUE TITLE
pnotify missing?

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1656]
Hi, 
when opening .../submission or ../manageIssues (maybe others, too) I see "File does not exist: ../lib/pkp/js/lib/pnotify/pnotify.buttons.js" (as well for pnotify.core.js) on the webserver-logs. And indeed, the folder pnotify is empty. Current install is a clone of recent ojs master branch and composer.phar update was called, too. Is pnotify used at all? Is there a entriy for submodule missing in .git/config?
Best, 
Andreas

**Comment by asmecher** [comment]
@henkela, pnotify is installed via submodule of `lib/pkp` (itself a submodule). When you do a submodule init/update, make sure you use `--recursive`. OTOH I use:

    git submodule update --init --recursive

**Comment by henkela** [comment]
@asmecher, weird thing is that that's not working for my fork... probably I messed it up somehow...
