### ISSUE TITLE
Add Copyeditor problems

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1658]
In the copyediting stage, when I hit the Add button in the participants grid, the modal pops up as expected, all form elements work, but the OK button doesn't appear to respond. Its visible appearance changes (from unselected to selected) but the modal stays up.

When I cancel out of the modal, the selected copyeditor does not appear in the grid.

When I try add again, the originally selected copyeditor is no longer available as a choice.

**Comment by stranack** [comment]
After moving to Production, the "new user added to stage" notifications all show up and the users are now in the Participants grid.

**Comment by asmecher** [comment]
I fixed a small typo that was causing PHP errors (which can cause the kind of behavior your were seeing). Fixed and cherry-picked into uiux; it should work OK now.
