### ISSUE TITLE
Schedule for Publication modal behaviour

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1659]
When I fill in the fields for the Schedule for Publication modal and hit Save, another modal pops up, with just the title (Publication) and an OK button - no text. Hitting this OK button processes my action. Can we remove this second step?

**Comment by asmecher** [comment]
@bozana, could this be caused by some of the recent permanent identifier work?

**Comment by bozana** [comment]
Ah, yes, for sure, because then the modal for pub id assignment should be displayed, but maybe I haven't considered the case if there are no pub ids or something like that.... I will take a look. Sorry! :-\

**Comment by asmecher** [comment]
Merged -- thanks, @bozana!
