### ISSUE TITLE
Remove Author Names/Reviewer Names from Filenames

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1663]
Currently, uploaded filenames automatically include the name of the user. This is generally useful, except for authors and reviewers during the review process, as it undermines the double blind process.

Can we ensure that author names and reviewer names are not included in filenames?

**Comment by bozana** [comment]
@asmecher, here is the PR: https://github.com/pkp/pkp-lib/pull/1764
All files uploaded in the review stage will have the anonymous default file name. Also the files copied from the submission to the review stage (by "Send to Review" action), if they have the default file names -- if they have the default file names, the names will be change to the anonymous default file names. Hope this is OK...

**Comment by asmecher** [comment]
Closing!

**Comment by marcbria** [comment]
@asmecher any plan to port this to the LTS version?
We all agreed that LTS won't get new features but what about relevant fixes like this one?

**Comment by asmecher** [comment]
@marcbria, this was coded up way back in 2016, so should be included in the LTS. Maybe it's a different issue or a regression?
