### ISSUE TITLE
getId and getFileId for SubmissionFiles

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1669]
check if getId (as for all other objects) can be used instead of getFileId

**Comment by bozana** [comment]
This is still not the case, thus can I close the issue @asmecher?

**Comment by asmecher** [comment]
I'd suggest leaving it open. I'd like eventually to get rid of `getFileId` in favour of `getId` -- the current behavior is out of our normal practice and could be confusing.

**Comment by NateWr** [comment]
I believe this was addressed in the submission file refactor undertaken for 3.3. The method `SubmissionFile::getFileId()` still exists, but now points to the underlying id of the file in the `files` table. The method `SubmissionFile::getId()` is used for the submission file's id.
