### ISSUE TITLE
Problems with tasks created when requesting revisions

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1682]
Requesting revisions creates two nearly identical tasks for the author.

![selection_018](https://cloud.githubusercontent.com/assets/2306629/17442192/86216dda-5b2c-11e6-91e8-c7eb0daf2277.png)

Also, when an author uploads revisions, there is no task created to notify the editor. An author may upload multiple revision files. I'd recommend when a revision file is uploaded, we should check if a task already exists for the editor. If it doesn't, create one. If it does, make sure it's marked unread (so it will toggle back to unread if the editor has marked it read from a previous file).

**Comment by disjunctor** [comment]
Should there be a button 'Submit the revision'  on the author's review page? I cannot see something like this in the current version of the OJS.

**Comment by asmecher** [comment]
@disjunctor, what version of OJS are you using?

**Comment by disjunctor** [comment]
@asmecher, OJS 3.0 from git master

**Comment by bozana** [comment]
Because I am working on notifications right how, s. https://github.com/pkp/pkp-lib/issues/1710, I will address this issue too.
Now there is only one task for author, the second one: "Revision required". When author uploads a revision file the task  "A revised file has been uploaded for your editorial consideration in Review" will be created. If there were such tasks, they will be deleted and a new ones created, i.e. they will always be new/unread for the editors.

**Comment by disjunctor** [comment]
@asmecher @bozana 
at the review stage as an author I cannot delete uploaded files: there is no 'delete button'.
This is an important thing for the workflow, if someone uploads wrong file.

**Comment by bozana** [comment]
Yes, I noticed that too, but I am not sure how is it meant to be, maybe @asmecher can say. Editors do have the delete option. What you could do is replace the file.
And for you question above: there is no button 'Submit the revision', author can just upload a file and the editors will get a task assigned, that a new file revision came in.

**Comment by disjunctor** [comment]
But what is the way to understand if the revision was completed?
Sometimes author has to upload multiple files, and he/she can do it step by step (it can take several days). This probably can lead to the misunderstanding between the author and editor: the editor can send incomplete revision to the reviewer. Anyway, on wrong action author is supposed to open a discussion, right? This involves many more actions compared to the just one button click (e.g. delete file, submit revision).

**Comment by NateWr** [comment]
Hi @disjunctor,

I'm not sure what the intention was in not allowing authors to delete revision files. That may have just been an oversight or there may have been a specific requirement there. @asmecher will know best and be able to comment on what to do.

I'll address in more detail your suggestion of a "Submit Revisions" button, because it touches on some broader issues related to a broader development strategy we're trying to follow with OJS 3.

The new workflow in OJS 3 involves a conceptual change from a prescriptive, linear workflow to a more adaptable, non-linear workflow. Various stages or actions of the editorial process can happen _at the same time_.

This makes the workflow a little more adaptable to the hundreds and thousands of different editorial procedures that our users follow. But it also means that we can't count on things happening in a strict sequence, and in some cases like this we can't know with at any given moment exactly what's supposed to happen next.

At first glance, it may seem simple to just add a sign-off button ("Submit Revisons"). But it doesn't take long for further complications to arise. What happens when an editor makes separate requests for revisions on different documents? Now we need to tie the sign-off button to specific files. What if an editor wants to add a new set of revision requests after seeing the first? Now we need a revisions round system like the review round system.

We'll end up with a much more complicated revisions system -- complicated for the users and complicated for our small team of developers to maintain -- which will only be used by a minority of our users.

In fact we used to have a sign-off system in various places in the workflow. It turned out to be very difficult to understand. And every time we thought we'd nailed it down, someone would come up with a use-case where it didn't work.

So we have a more flexible approach in which authors can upload files at their own pace and editors receive notifications related to these uploads. The discussions tool is an "out", a way for editors, authors and editorial assistants to coordinate in the minority of cases where further details or conversation is needed.

This simplifies the process for the majority of use-cases and cuts down considerably on the complexity of the code that we have to maintain. That means we can spend more of our time refining core aspects of the software instead of trying to shoe-horn dozens of different specialized workflow requirements into the system.

**Comment by disjunctor** [comment]
@NateWr,
thank you for the explanation. I will try to verify our use-cases, taking into account the conception of non-linear workflow.

**Comment by bozana** [comment]
This issue was solved together with the issue https://github.com/pkp/pkp-lib/issues/1710, so closing...
