### ISSUE TITLE
Implement OJS 2.4.x to 3.0 upgrade

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1683]

**Comment by asmecher** [comment]
- [ ] Map old article/downloadSuppFile URLs to new ones (from https://github.com/pkp/pkp-lib/issues/1541)

**Comment by jalperin** [comment]
adding @fabiobatalha from SciELO so he gets notifications (but not sure if this works for people outside the pkp team)

**Comment by bozana** [comment]
@asmecher, may I put a note regarding the supp files and pub ids here? -- I believe this should be considered for the migration: till now the supp files could have a pub id (public URL, DOI, URN) and now there is no model for that?

**Comment by asmecher** [comment]
PRs:

- https://github.com/pkp/pkp-lib/pull/1742
- https://github.com/pkp/ojs/pull/980

@bozana, could you glance over these? I'm going to merge them and keep doing some testing/fixing, and if (when) anything that comes from that I'll link to it. I'm not sure how useful a normal-style code review will be, but I'll be talking with Kevin/James early next week about testing and we'll discuss reviewing some test upgrades along with that.

**Comment by asmecher** [comment]
Closing for 3.0!
