### ISSUE TITLE
Deleting section editor from participants grid can cause a section editor to be deleted

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1684]
Here's a weird one. To reproduce from demo data:

1. Open a submission in review stage (eg - Montgomerie, et al).
2. David Buskins should be assigned as section editor. Stephanie Berardo may be assigned as well. If not, assign her as an additional section editor.
3. Assign Minoti Inoue as an additional section editor. You should have three section editors with Minoti last.
4. Click the "Remove" link to unassign Minoti.

Result: both Minoti and Stephanie are removed from the participants grid.

**Comment by asmecher** [comment]
Hmm, I also saw this happen. Will take a look.

**Comment by asmecher** [comment]
Fixed, thanks!
