### ISSUE TITLE
Improvements to information center

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1686]
A couple of small improvements to come out of the user testing.

- [x] Fix ##submission.event.participantAdded## in Editorial History
- [x] Could History be the default tab rather than Notes? It is a better match for what is expected from the link label

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1687

**Comment by asmecher** [comment]
Merged -- closing!

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1697

This should fix the JS linting error.

**Comment by asmecher** [comment]
You'll need to remove the `var` further down, and there's still..

    Compile (Check)...
	/tmp/tmp.XqcIRIiHcM/lib/pkp/js/controllers/UploaderHandler.js:84: WARNING - Property id never defined on $.pkp.controllers.UploaderHandler.pluploader
	  var pluploaderId = this.pluploader.id;

**Comment by NateWr** [comment]
This is now crossing over into the same linting errors I'm having here:

https://github.com/pkp/pkp-lib/issues/1536#issuecomment-238842437

I'm going to close this and figure out the linting issues in the other issue.
