### ISSUE TITLE
DOAJ language export

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1690]
The article language field is used for the langauge element in DOAJ XML. There could be more then one languages entered and separated with the ";" which is not considered in the XML export, s. https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/importexport/doaj/classes/DOAJExportDom.inc.php#L97. 
Either this should be considered there or the article locale should be the one to base on, like everywhere else in the system. @asmecher, what do you think? 
s. http://forum.pkp.sfu.ca/t/doaj-plugin-and-multi-language-articles/17210/3

**Comment by asmecher** [comment]
I replied to the forum thread -- yes, I think using the article locale is a better idea. The language field is not machine-readable and in my opinion it should eventually be removed, once we figure out e.g. how to permit article languages that aren't supported UI languages in OJS.

**Comment by kmruck** [comment]
thanks dear @bozana and @asmecher! i pointed bozana to this problems as for FQS we received the DOAJ seal (https://doaj.org/toc/1438-5627?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22index.issn.exact%22%3A%221438-5627%22%7D%7D%2C%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A100%7D), but while uploading the abstracts (again) only german abstracts are visible. Abstracts are available in English, German, and Spanish, and i for sure would love to get the English abstracts shown in DOAJ ... so for me it is important how to continue/get this problem fixed, as 1,791 article abstracts are longing to get uploaded and the number is growing day by day ;-)) ... i think this problem concerns not just FQS but all multilingual journals using OJS, so any support is welcome! thanks!!! katja

**Comment by bozana** [comment]
Oooo @kmruck is active in GitHub :-) We will solve this, but I believe the 3.0 has such a huge priority and so much work, that we will not be able to solve this before the 3.0 release... But else, yes, stay tuned... :-)

**Comment by bozana** [comment]
@asmecher, could you take a look at this PR: https://github.com/pkp/ojs/pull/1011 ?

**Comment by asmecher** [comment]
Merged the above PR, thanks, @bozana!
