### ISSUE TITLE
move chapterId to SubmissionFile

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1694]
Move the function chapterId to the parent class SubmissionFile -- also SupplementaryFile can be assigned to a chapter, thus all file classes should contain this function, thus it is good to put it in the parent class.
Although this is OMP specific i.e. the OMP specific code will be in the pkp-lib (but it was already there), this is a preferred change because it will reduce the code.
The following classes are then not needed any more:
- classes/monograph/ArtworkFileDAODelegate.inc.php
- classes/monograph/MonographArtworkFile.inc.php
- classes/monograph/MonographFile.inc.php
- classes/monograph/MonographFileDAODelegate.inc.php

**Comment by asmecher** [comment]
PRs:

- https://github.com/pkp/pkp-lib/pull/1695
- https://github.com/pkp/omp/pull/317

There's no PR required for OJS, right, @bozana?

**Comment by bozana** [comment]
Yes, no PR required for OJS :-)

**Comment by asmecher** [comment]
Both merged! Yup, the huge amount of removed code demonstrates that this was the right approach, I think, despite the fact that an OMP concern is somewhat moved into pkp-lib. Thanks, @bozana!
