### ISSUE TITLE
[OJS] Setting an empty section causes a submission to disappear

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1696]
In as submission's metadata you can set the Section to empty and then save the metadata form. Doing this causes the submission to disappear from the Active/Archive list. And attempting to reach it by ID leads to an invalid submission error.

**Comment by asmecher** [comment]
OMP should be able to permit empty series (=section), but OJS should not.

**Comment by bozana** [comment]
PR: https://github.com/pkp/ojs/pull/996
@NateWr, the tests will surely fail, but I will already assign you for the review however...

**Comment by NateWr** [comment]
:+1: All good. Not sure what's going on with the tests. Should I merge this anyway?

**Comment by bozana** [comment]
@NateWr, thanks a lot! I think we could wait for @asmecher to save us from those testing failures :-) and then merge it, OK?

**Comment by bozana** [comment]
Merged, thus closing...
