### ISSUE TITLE
Review/Revise Email Templates

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1698]
Some email template messages may require updating before the release. A systematic review of all is needed to determine which ones need attention.

**Comment by mtub** [comment]
depending on how severe the updates are, this might affect translations... (as do any other last minute locale updates…)

**Comment by asmecher** [comment]
@stranack, what's the likelihood that you can take a spin through these within the next week? (0% is an acceptable answer)

**Comment by asmecher** [comment]
Done for 3.0!
