### ISSUE TITLE
Add a banner notification ("Assign a copyeditor using the Add link in the Participants list")

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1702]
In the Copyediting stage, immediately after an editor has moved the submission to copyediting, there should be a banner notification - “Assign a copyeditor using the Add link in the Participants list”. Should the Add text be a link? This banner should stay active until at least one copyeditor has been assigned.

**Comment by asmecher** [comment]
Moved to https://github.com/pkp/pkp-lib/issues/1710
