### ISSUE TITLE
Add a banner notification ("Assign a user to create galleys using the Add link in the Participants list")

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1704]
In the Production stage, immediately after an editor has sent a submission to Production, there should be a banner notification - "Assign a user to create galleys using the Add link in the Participants list". Should the Add text be linked? This banner should stay active until the assigned user has responded.

**Comment by asmecher** [comment]
Moved to https://github.com/pkp/pkp-lib/issues/1710
