### ISSUE TITLE
add supplementary file support for the native import and export 

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1707]
Consider SupplementaryFile in the native import and export for OJS and OMP
OJS PR: https://github.com/pkp/ojs/pull/965
OMP PR: https://github.com/pkp/omp/pull/318

**Comment by asmecher** [comment]
Don't forget to assign this to a reviewer per the rota document :)

**Comment by bozana** [comment]
hihihihi I've forgotten :-\
@NateWr, could you please review this PRs?

**Comment by NateWr** [comment]
@bozana I must admit I'm not really familiar with the XML import/export tools. I've had a look at the code and left a few minor comments.

I checked out the `ojs` PR and tried to export a submission that I knew had a supplementary file. I got a fatal error. Here's my apache error log for that request:

```
[Wed Aug 10 14:05:04.262131 2016] [:error] [pid 15124] [client 192.168.0.8:35767] PHP Warning:  DOMDocument::schemaValidate(): Internal error: xmlSchemaVDocWalk, there is at least one entity reference in the node-tree currently being validated. Processing of entities with this XML Schema processor is not supported (yet). Please substitute entities before validation.. in /var/www/html/ojs/lib/pkp/classes/xslt/XMLTypeDescription.inc.php on line 126, referer: http://192.168.0.8/ojs/index.php/publicknowledge/management/importexport/plugin/NativeImportExportPlugin
[Wed Aug 10 14:05:04.262227 2016] [:error] [pid 15124] [client 192.168.0.8:35767] PHP Notice:  Trying to get property of non-object in /var/www/html/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php on line 191, referer: http://192.168.0.8/ojs/index.php/publicknowledge/management/importexport/plugin/NativeImportExportPlugin
[Wed Aug 10 14:05:04.267486 2016] [:error] [pid 15124] [client 192.168.0.8:35767] PHP Warning:  assert(): Assertion failed in /var/www/html/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 110, referer: http://192.168.0.8/ojs/index.php/publicknowledge/management/importexport/plugin/NativeImportExportPlugin
[Wed Aug 10 14:05:04.267506 2016] [:error] [pid 15124] [client 192.168.0.8:35767] PHP Fatal error:  Call to a member function getUsername() on a non-object in /var/www/html/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 111, referer: http://192.168.0.8/ojs/index.php/publicknowledge/management/importexport/plugin/NativeImportExportPlugin
```

It seems that `$submissionFile->getUploaderUserId()` is not returning an ID. Any idea what's going on here? Do I need to upload fresh files on this branch maybe? This is old test data...

**Comment by bozana** [comment]
@NateWr, hmmm... I have to admit that I don't know what those log file messages mean, what could it be... Else, for import/export to work properly, the appropriate filters and filter groups have to be in the database. Because they were changed during the time and because there is no upgrade script for them, I had to correct them manually in my database. (I will soon try to write the upgrade scripts for them too). If you want you could send me your database and I could take a look...

**Comment by NateWr** [comment]
@bozana I tried to do it with a new submission and still got the following errors.

```
[Thu Aug 11 10:23:46.200730 2016] [:error] [pid 31064] [client 192.168.0.8:57437] PHP Warning:  assert(): Assertion failed in /var/www/html/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php on line 243, referer: http://192.168.0.8/ojs/index.php/publicknowledge/management/importexport/plugin/NativeImportExportPlugin
[Thu Aug 11 10:23:46.200756 2016] [:error] [pid 31064] [client 192.168.0.8:57437] PHP Fatal error:  Call to a member function setDeployment() on a non-object in /var/www/html/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php on line 245, referer: http://192.168.0.8/ojs/index.php/publicknowledge/management/importexport/plugin/NativeImportExportPlugin
```

Is a new submission enough to get the appropriate filters and filter groups? Or do I need a fresh journal? Or a fresh installation of OJS?

**Comment by bozana** [comment]
@NateWr, you will need to do the tools/upgrade.php upgrade (this will add the new filter for supp files and correct some others), but then I believe you will also have to manually check the filters and filter_groups in the DB, because the old wrong ones are probably still there :-( I will try to make a screenshot of the filters you would need...

**Comment by bozana** [comment]
here the screenshots:
filter_groups:
![nativefiltergroups](https://cloud.githubusercontent.com/assets/378421/17586965/5c8019d4-5fc5-11e6-8752-fecfa834acfb.png)

filters:
![nativefilters](https://cloud.githubusercontent.com/assets/378421/17586977/67f39214-5fc5-11e6-9ff7-88df19f5771b.png)

the filters has to contain the right filter_group_id...

**Comment by bozana** [comment]
do you have those in your db?

**Comment by bozana** [comment]
@NateWr, this log file message "Assertion failed in /var/www/html/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php on line 243" points that the filters in your DB are not correct (either there are more than one or non of that kind). If you try to manually correct them as in my screenshots it should work, I believe.

**Comment by NateWr** [comment]
@bozana Ok, I went ahead and did a fresh install of OJS. Completely new database, on your OJS branch and pkp-lib `master`. I created a submission and added two files (one supplementary). When I try to export the submission, I get the following errors:

```
[Thu Aug 11 14:45:55.709205 2016] [:error] [pid 2878] [client 192.168.0.8:60495] PHP Warning:  DOMDocument::schemaValidate(): Element '{http://pkp.sfu.ca}authors': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}id, {http://pkp.sfu.ca}title ). in /var/www/html/ojs/lib/pkp/classes/xslt/XMLTypeDescription.inc.php on line 126, referer: http://192.168.0.8/ojs/index.php/asdf/management/importexport/plugin/NativeImportExportPlugin
[Thu Aug 11 14:45:55.709359 2016] [:error] [pid 2878] [client 192.168.0.8:60495] ojs2: Could not convert submissions., referer: http://192.168.0.8/ojs/index.php/asdf/management/importexport/plugin/NativeImportExportPlugin
```

**Comment by bozana** [comment]
@NateWr, hmmm... I'll do the same to reproduce it... Could you maybe also send me your DB dump vial e-mail? Thanks a lot!

**Comment by bozana** [comment]
I think I found the error -- I've forgotten to check if the supp file metadata exist before creating an XML element...

**Comment by bozana** [comment]
Hmmm... Although, my error is a little bit different... Do you myabe miss the title for the submission?

**Comment by NateWr** [comment]
I've merged both PRs. Nice work! Ready to close this issue?

**Comment by bozana** [comment]
Yes, thanks a lot! Closing...
