### ISSUE TITLE
[OJS] Site administration edit site settings labels not fully displayed if site got a title image

### ISSUE THREAD

**Issue by cjuergen** [pkp/pkp-lib#1708]
This is a trivial mostly cosmetic bug. 
Adding a logo to the site (not journal site) has side effects on the form displayed when changing site settings.
The texts might not be fully displayed as the logo determines the size of the table they are in.

![website-sitesetting-headerlogo-lines](https://cloud.githubusercontent.com/assets/1050448/17515281/b7feb1ec-5e37-11e6-814b-7f7074b9dbcd.png)

Tested in OJS 2.4.8-1 vanilla instance with various browsers.

**Comment by NateWr** [comment]
Closing this as we are no longer providing bug fixes for OJS 2.x.
