### ISSUE TITLE
Native Import Issues for OJS and OMP

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1709]
- [x] a) If there was an import error the submission is still partly imported. If an error occurs, remove already processed/imported submissions and issues. Sections will not be removed.
- [x] b1) Consider source files -- At the moment they seem to be ignored i.e. the inserted source_file_id and source_revision is always = null. 
- [x] b2) Different revisions of a file are inserted with different file_id. Instead they should be inserted with the same file_id.
- [x] b3) Consider query files
- [x] c) OJS: Only issue(s) can be imported. Allow article(s) import too
- [x] d) OJS: consider issue reference in articles import XML 
- [x] e) "locale" attribute for localized nodes is optional, which leads to inserting data into DB without locale, if the locale attribute is missing.
- [x] f) OJS: check if a section being imported exists: check titles and abbreviations (as in OJS 2.4.x)
- [x] g) consider some errors catching and displaying them to the user, instead of fatalError.
- [ ] h) file import using href element
- [x] i) provide export XML for download, instead of displaying it in the browser
- [x] j) OJS: add pages element for the article element
- [x] k) Consider controlled vocabularies (keywords, agencies, disciplines, subjects) -- no matter how the journal/press workflow submission settings are i.e. what vocabulary is selected
- [x] l) Fail the import if the revision `uploader` or `user_group_ref` do not exist in the system (moved from https://github.com/pkp/pkp-lib/issues/1728)

**Comment by bozana** [comment]
@asmecher, do you think some of those issues should be addressed for OJS 3.0?

**Comment by asmecher** [comment]
I think we can leave these for 3.0.1, but if we get spare time before the release (ha!) it might be a worthy addition to consider.

**Comment by bozana** [comment]
@asmecher, when a published article is being imported, there have to be an issue associated with it. At the moment we do not have this information. Is there maybe a good way to have a reference to an issue in the import XML file? For example an additional attribute "issue_id" for the "article" element, that would be considered if there is no issue in deployment (i.e. if not the whole issue is being imported, so that we in that case know which issue)? I could add a drop-down list of issues in the import form, for user to select an issue in that case, but maybe it would be easier and also more flexible to have the information in the XML file -- e.g. this way articles from different issues could be imported at once.

**Comment by bozana** [comment]
@asmecher, one more question: I've just realized, that attribute "locale" is optional for localized nodes (s. https://github.com/pkp/pkp-lib/blob/master/xml/importexport.xsd#L22-L24). Thus an article title doesn't have to have locale and in that case it will be inserted without the locale in the DB, which is wrong, I think. Should then the locale attribute be set to required? I think this would be more correct than to assume it (to use either the submission or primary locale) if the locale is missing -- there could be for example several title nodes without the locale attribute... 
Also the article node attribute "locale" is optional, which could also be changed to required?

**Comment by asmecher** [comment]
Most users are going to be importing single-language content, and many don't have a lot of XML skill, so I'm leaning towards inheriting from upstream if something isn't specified. It'll keep the XML shorter and more readable and for most users it'll be enough.

That would mean...

- Articles inheriting the default from the journal
- Content within articles (e.g. titles and abstracts) would inherit the default from the article

If you think that's a mistake, your recommendation is OK too -- I don't have a very strong preference.

**Comment by asmecher** [comment]
@bozana, about https://github.com/pkp/pkp-lib/issues/1709#issuecomment-247593584 -- I suppose this is for when the import document contains `article` elements that aren't within their own `issue` element, right?

I think having the content in the XML file makes sense, but the issue ID is a pretty brittle way of doing it; maybe it's worth supporting to referring to issues both by ID and by some combination of volume/number/year?

**Comment by WaDelma** [comment]
I have quite bit of legacy data to import so I will chime in here.

I will be importing lots of stuff (2128 articles) that have mixed languages and most of it doesn't have locale information. Also no issue information either for any of the articles.

We also have customised publishing front end and published stuff aren't actually in issues in OJS, but bundled into issues in the front end (don't ask why... I wasn't there when it was made).

**Comment by bozana** [comment]
@WaDelma, what exactly do you mean by "have mixed languages and most of it doesn't have locale information" and  "falling back to unlocaled stuff"?
I will then leave the locales in XML optional, and if they are not there I will, as @asmecher said, take journal primary locale or submission locale (depending on what object is being inserted). 
If the article XML element has date_published it is treated/seen as published article and it will have to be assigned to an issue -- this is requirement for published articles (DB table published_submissions) in OJS. Thus in your case, you will maybe have to leave that date out of the XML import file -- it is/will be possible to import not published articles -- and then do something with those articles?

**Comment by bozana** [comment]
Here the documentation, how the default locales will be for different objects:

- submission file i.e. revision name default locale = context primary locale
- issue galley locale: test if it is required
- issue metadata default locale = context primary locale
- section metadata default locale = context primary locale
- submission default locale = context primary locale
- submission metadata default locale = submission locale
- authors metadata default locale = submission locale
- article galley default locale = submission locale
- representation name default locale = submission locale
- supplementary files metadata default locale = submission locale

**Comment by WaDelma** [comment]
Never mind I just realised that I can get most of the locale information. I was just concerned that it would add incorrect locale info for articles as there are at least 4 languages used in different articles. 

Metadata plugin doesn't interact with importexport right? I have DC metadata for these articles. Also it seems that DC metadata plugin doesn't support DCMI Metadata Terms, which are also used in metadata.

**Comment by bozana** [comment]
PRs for c) and e) above:
pkp-lib: https://github.com/pkp/pkp-lib/pull/1836
ojs: https://github.com/pkp/ojs/pull/1020
omp: https://github.com/pkp/omp/pull/335
@asmecher, mind taking a look at these PRs?

**Comment by bozana** [comment]
> I think having the content in the XML file makes sense, but the issue ID is a pretty brittle way of doing it; maybe it's worth supporting to referring to issues both by ID and by some combination of volume/number/year?

The volume/number/year only make sense if this is the issue identification. In that case: could we have the attribute "issue_vol_no_year" for the article element, that would contain e.g. "1-1-2016"? If we separate it into 3 attributes it could happen that not all are entered, but... maybe it is OK too, i.e. in that case there would be an error. What would you prefer/what would be better?
And for issue ID: can we then have an attribute "issue_id" for article element?

**Comment by bozana** [comment]
@WaDelma, right, metadata plugin doesn't interact with importexport...

**Comment by asmecher** [comment]
> The volume/number/year only make sense if this is the issue identification. In that case: could we have the attribute "issue_vol_no_year" for the article element, that would contain e.g. "1-1-2016"?

I think this might be a good opportunity to create some general-purpose elements for representing issue identification; the `<issue>` element is already pretty heavy with attributes for these.

**Comment by bozana** [comment]
Hmmm... What do you mean?

**Comment by asmecher** [comment]
I mean that these three lines:
https://github.com/pkp/ojs/blob/ojs-3_0_0-0/plugins/importexport/native/native.xsd#L122..L124
...and these...
https://github.com/pkp/ojs/blob/ojs-3_0_0-0/plugins/importexport/native/native.xsd#L128..L131
...are also intended to identify an issue (hopefully uniquely). If it's possible, then we should try to harmonize the issue identification here in the `<issue>` element, with what you're proposing in an `issue_ref` (or something similar) to associate imported articles with issues.

**Comment by bozana** [comment]
Do you mean to then have an element <issue_ref> that will have the same 3 attributes (volume, number and year)?

**Comment by asmecher** [comment]
Yes, maybe `issue_identification` is the best approach. If we were to use attributes alone, it's possible to restrict attribute values using e.g. regular expressions, but I don't love the idea of jamming a bunch of regular-expression based data together when we're already encoding within XML...

**Comment by bozana** [comment]
OK, thanks!!! I'll do...

**Comment by asmecher** [comment]
For the 3 PRs above (https://github.com/pkp/pkp-lib/issues/1709#issuecomment-248307538), just a couple of minor comments. When that's addressed, please go ahead and merge/cherry-pick, thanks!

**Comment by bozana** [comment]
PR for d) (issue_identification) above: https://github.com/pkp/ojs/pull/1021
@asmecher, could you please take a look?

**Comment by Ph-We** [comment]
Hi!

We've come upon the following issues while trying to import one of our journals:

1. There seems to be no way to import a full issue galley. The XML part for it looks like this:
<img src="/uploads/default/original/2X/4/4bcdbd03ecde254fb44a1dbfea13f05136e18b7b.png" width="502" height="272"> 
But after the import procedure is over, this galley is missing. As far as I know, this issue has not yet been addressed anywhere. The error is this:
> `> HP Fatal error:  Call to a member function setDeployment() on null in …plugins/importexport/native/filter/NativeXmlIssueFilter.inc.php` 

2. During the import all the recurrent section titles are repeated in _Settings -> Journal -> Sections_ the number of times they occur in different issues. I believe this issue should have been addressed here: https://github.com/pkp/pkp-lib/issues/1709
But please, let me know, if it is not my case.

3. If some article has no author, the issue gets cut off on this article during the import.

4. If the issue number is a string ("1-2" in our case), the issue is not imported.
 The articles imported

See also: [http://forum.pkp.sfu.ca/t/ojs3-native-xml-import/20935](url)

Best,
Ivan

**Comment by bozana** [comment]
@Ph-We, number 1. (s. https://github.com/pkp/ojs/commit/54377aa3d596c2d80bff7d49f6e072cc54775177) and 2. (s. https://github.com/pkp/ojs/commit/4d5e8dd5fe781985a7de3669e8a63396134ab229) are solved and merged in the master branch. I will then cherry-pick them to ojs-stable-3_0_0 too.
3. The authors are mandatory i.e. so defined in the XML schema. If missing in the XML import file, you should see the validation error. Is this the case for you? 
In that case of a failure, the import is aborted and the imported data (till then) is still in the database. This will be addressed in the point g) and a) from this issue.
4. I am currently working on a new way of issue identification (s. https://github.com/pkp/ojs/pull/1021) and will double check that the string for the issue number works properly.
Thanks a lot Ivan! Please follow this issue and its merged PR for the news i.e. solutions of your issues.

**Comment by Ph-We** [comment]
@bozana, thank you very much for your support!
As to the mandatory authors, do you mean the normal behavior would suppose _importing_ articles without authors with only validation errors displayed? As far as I remember, the authors were not mandatory for XML in OJS2. That was reasonable, since some texts might not really have had authors.

**Comment by bozana** [comment]
@Ph-We, yes, the validation error will be displayed and the article will not be imported.
I was always like this, i.e. authors (with firstname, lastname and email) were always mandatory, s. https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/importexport/native/native.dtd#L135 and https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/importexport/native/native.dtd#L141. I am not sure if this is attended to be changed sometime, this @asmecher can better tell.

**Comment by asmecher** [comment]
In OJS 2.x authors were required, but journals commonly used work-arounds in cases where they weren't available. Eventually we'll need to enrich our support for e.g institutional authors and authorless submissions, but we haven't done that yet for either OJS 2.x or 3.x.

**Comment by bozana** [comment]
PR of the first changes for ojs-stable-3_0_0:
pkp-lib: https://github.com/pkp/pkp-lib/pull/1857
ojs: https://github.com/pkp/ojs/pull/1032

**Comment by bozana** [comment]
PRs for d) (issue_identification) above:
ojs master: https://github.com/pkp/ojs/pull/1021 (merged)
ojs-stable-3_0_0: https://github.com/pkp/ojs/pull/1041
lensGalley: https://github.com/asmecher/lensGalley/pull/8 (merged)

**Comment by asmecher** [comment]
All the above are merged. Tests for `ojs-stable-3_0_0`: https://travis-ci.org/pkp/ojs/builds/165342989

**Comment by Ph-We** [comment]
Hi @bozana,
This might be urgent. There seem to be no element for article **pages** in schema. So we neither can export page ranges, nor import them.

**Comment by bozana** [comment]
PR for j) above: 
master: https://github.com/pkp/ojs/pull/1054
@asmecher, could you take a look at this small addition?

**Comment by bozana** [comment]
PR for i) above:
pkp-lib: https://github.com/pkp/pkp-lib/pull/1876
ojs master: https://github.com/pkp/ojs/pull/1055
@asmecher, also these PRs?

**Comment by asmecher** [comment]
Thanks, @bozana -- merged https://github.com/pkp/ojs/pull/1054. I suppose this needs back-porting to `ojs-stable-3_0_0`?

For https://github.com/pkp/pkp-lib/pull/1876 and https://github.com/pkp/ojs/pull/1055, one comment to consider: https://github.com/pkp/ojs/pull/1055#pullrequestreview-3964223

Thanks!

**Comment by bozana** [comment]
Thanks a lot @asmecher! I integrated your comment. Could you take a look?

**Comment by bozana** [comment]
@asmecher, the OMP fixes (for e) and i) above) are only merged into OMP master branch. Should they be cherry-picked also to the omp-stable-1_2 or any other branch as well?

**Comment by Ph-We** [comment]
Hi @bozana,

This is quite important too. There seem to be no element for keywords. Could you confirm?

**Comment by asmecher** [comment]
@bozana, does this have compatibility-breaking potential? If so, don't back-port to `omp-stable-1_2_0`, just to `omp-dev-1_2`. If it's just bugfixes and new capabilities, then it's good to back-port to `omp-stable-1_2_0` too. Thanks!

**Comment by bozana** [comment]
I have not back-port it to omp-stable-1-2_0 and omp-dev-1_2 because apparently I will have to back-port even more commits, these are based on/build upon. Those two branches misses a lot of commits from master, so lets see first which branch will be used for the next omp release...

**Comment by bozana** [comment]
@asmecher, I would then add a new element for keywords. Shall they be separated from subjects (submission metadata subject field) or shall there be a common subject element for both of them? Shall the items be separated by ";" and use just one element or shall every keyword have its own element? THANKS!!!

**Comment by bozana** [comment]
PRs for k) above: 
master: https://github.com/pkp/pkp-lib/pull/1975

@asmecher, could you take a look at this PR?

**Comment by asmecher** [comment]
I think it would be better to allow each keyword to be entered in its own XML element, rather than using a separator inside the element -- likewise for every field that's backed by a `ControlledVocab` structure.

**Comment by bozana** [comment]
OK, I will change it... Thanks!!!

**Comment by bozana** [comment]
@asmecher, I changed it. Now it looks like this:
```
	<keywords locale="en_US">
		<keyword>kw1-1</keyword>
		<keyword>kw1-2</keyword>
	</keywords>
	<keywords locale="de_DE">
		<keyword>kw1-1</keyword>
		<keyword>kw1-2</keyword>
	</keywords>
	<agencies locale="en_US">
		<agency>supporting agency 1</agency>
	</agencies>
	<agencies locale="de_DE">
		<agency>supporting agency 1</agency>
	</agencies>
	<disciplines locale="en_US">
		<disciplin>discipline1</disciplin>
		<disciplin>discipline2</disciplin>
	</disciplines>
	<disciplines locale="de_DE">
		<disciplin>discipline1</disciplin>
		<disciplin>discipline2</disciplin>
	</disciplines>
	<subjects locale="en_US">
		<subject>subject1</subject>
		<subject>subject2</subject>
	</subjects>
	<subjects locale="de_DE">
		<subject>subject1</subject>
		<subject>subject2</subject>
	</subjects>
```

OK so?

**Comment by bozana** [comment]
PRs for a), g) and l) above:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/1987
ojs master: https://github.com/pkp/ojs/pull/1096
omp master: https://github.com/pkp/omp/pull/354

**Comment by asmecher** [comment]
Just a couple of comments, but it also looks like the tests aren't working.

**Comment by asmecher** [comment]
Also...

> @asmecher, I changed it. Now it looks like this...

Yes, thanks! More verbose but more usable, I think.

**Comment by bozana** [comment]
@asmecher, could you take a look at these PRs for a), g) and l) above:
lensGalley master: asmecher/lensGalley#10
pkp-lib master: #1987
ojs master: pkp/ojs#1096
omp master: pkp/omp#354

I also don't know why ojs tests are failing, they run through for me locally :-(

**Comment by asmecher** [comment]
Regarding https://github.com/pkp/pkp-lib/issues/1709#issuecomment-260763039: all reviewed, looks good! One small tweak needs doing (the constructor syntax). Could you try rebasing and making sure the lib-pkp submodule commit is up to date? I suspect that'll fix the tests. I'm not sure what's breaking there, but it's breaking consistently, which suggests it's not just a passing hiccough. This is a nice, clean addition.

**Comment by Ph-We** [comment]
Hi @bozana, @asmecher,

The schema names seem to be different in the database and in the code, so the procedure fails.

**Comment by bozana** [comment]
@Ph-We, how do you see that i.e. what errors do you see? THANKS!!!

**Comment by bozana** [comment]
PRs for b1), b2) and b3) above:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2293

**Comment by bozana** [comment]
@asmecher, could you code review the PR above?

**Comment by Ph-We** [comment]
Hi @bozana, I really need your help. We still get numerous errors of this sort:
`Rename section "Article and Book Reviews" to  "Article and Book Reviews 140027367_en"  [ 2014 => 4 ]`

Could you please tell, what might be wrong with such section names? And how we could handle this.
This renaming results in dubbing the sections:

![image](https://cloud.githubusercontent.com/assets/22288161/23121975/83a9ee18-f773-11e6-8297-90b4ba384fa1.png)

**Comment by bozana** [comment]
@Ph-We, where do you see those error messages -- I cannot find them in the code... :-O
This happens when you import articles, right? How does your XML looks like i.e. the section information there? Are they totally the same as the sections already in the system -- for all languages?

**Comment by Ph-We** [comment]
Hi @bozana, I'm really sorry for bothering you. The problem appeared to be on our side, and that was a part of our own log :o( 
I'm deleting the previous message, sorry once more!

**Comment by bozana** [comment]
@Ph-We, no problem!

**Comment by asmecher** [comment]
@bozana, is there anything more on this one you'd like to include in OMP 3.1?

**Comment by bozana** [comment]
Yes, everything solved, I'll merge the last PR in a moment... Thanks!!!

**Comment by bozana** [comment]
everything merged, thus closing...
