### ISSUE TITLE
[OMP] Can't register because no role selection is available

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1715]
With current OMP `master`, it doesn't appear to be possible to register a user account because no role selection is available and the form fails with a no role selected error.

I believe this is related to changes in the login process in `pkp-lib` for OJS which must have not been fully accounted for in OMP.

**Comment by asmecher** [comment]
@NateWr, do any of the roles (External Reviewer, Reader, Author) permit self-registration? Watch for the checkbox when editing roles. There are several that are configured by default to permit self-registration, but if you created your DB before that feature was added (quite a while ago), those defaults might not be present in your DB.

**Comment by NateWr** [comment]
Yeah both Author and External Reviewer allow self-registration in my install...

**Comment by asmecher** [comment]
Hmm. What recent changes do you think might be responsible? (I haven't looked into this yet, just hoping to get detail captured.)

**Comment by NateWr** [comment]
I couldn't find it in a quick look but I did do a lot of work on the registration form a while back, to streamline the signup process. I thought I got all of it going in OMP.

**Comment by asmecher** [comment]
OK, gotcha -- feel free to leave this filed for now (which I think is probably your plan :)

**Comment by asmecher** [comment]
I'm just running through the tests on OMP master on my local machine, and self-registration still seems to be fine. I'm running the tests on the Travis server too but I expect it'll confirm the same. Have you tried a fresh install?

**Comment by NateWr** [comment]
A fresh install helped. I only ran into this issue when trying to register a new account in OMP before any press existed. I'll close this unless you think there's anything else to be looked at.
