### ISSUE TITLE
Create a block plugin to display a submissions button 

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1717]

**Comment by NateWr** [comment]
@asmecher I've created a tiny little block plugin in a repo here:

https://github.com/NateWr/makeSubmission

I thought a repo might be best since it's shared between OJS and OMP. Would you like to add it as a gitmodule? Or would you rather I just chuck the files into OJS/OMP separately?

**Comment by asmecher** [comment]
Yup, good call on the separate repo, please go ahead and add submodule commits.

**Comment by NateWr** [comment]
Should the repo be added to the `pkp` organization instead of my personal account?

**Comment by asmecher** [comment]
Let's transfer it over to PKP. I believe you can start the transfer without being an admin on the PKP side, then I can accept it, but I'm not totally sure about that.

**Comment by NateWr** [comment]
I tried to transfer under my repo > settings > transfer, but it told me I didn't have the rights on pkp. I also tried going via new repo, and changing the owner to pkp, but it said I had insufficient rights.

**Comment by asmecher** [comment]
@NateWr, I made you an Owner. With great power comes great resistive heating.

**Comment by bozana** [comment]
Proverbalist :-)

**Comment by asmecher** [comment]
Merged both PRs, thanks!
