### ISSUE TITLE
Consider "Objects for Review" plugin for forward porting

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1718]
Consider forward-porting it to support OJS 3.x.

**Comment by asmecher** [comment]
Also a couple of quick suggestions from the forum: http://forum.pkp.sfu.ca/t/two-suggested-changes-to-objects-for-review/17765

**Comment by bozana** [comment]
Closing this one, because of this new GitHub Issue: https://github.com/pkp/pkp-lib/issues/2325
