### ISSUE TITLE
Homogenise max_length for session_id columns in OJS and OCS

### ISSUE THREAD

**Issue by cjuergen** [pkp/pkp-lib#1720]
Hi,

while installing OCS 2.3.6 I ran into this error: [Can't Login to the Admin Page](https://pkp.sfu.ca/support/forum/viewtopic.php?t=11040)
Enhancing the max length of all session_id columns to 128 worked fine. I checked the databases for OJS, OCS and OMP and found these default setting:

`OJS
table_name;column_name;data_type;character_maximum_length
"sessions";"session_id";"character varying";128
"captchas";"session_id";"character varying";40

OCS
table_name;column_name;data_type;character_maximum_length
"sessions";"session_id";"character varying";40
"captchas";"session_id";"character varying";40

OMP
table_name;column_name;data_type;character_maximum_length
"sessions";"session_id";"character varying";128`

Shouldn't these be homogenised

Claudia Jürgen

**Comment by asmecher** [comment]
Thanks -- these are homogenized. Note that the homebrew CAPTCHA test is deprecated in favour of ReCAPTCHA (and has been removed from the master branch / OJS 3.0).
