### ISSUE TITLE
[OJS] Installation screen needs to be wrapped in content container

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1721]
![selection_027](https://cloud.githubusercontent.com/assets/2306629/17589769/7393df94-5fce-11e6-8ba5-e11221058dce.png)

**Comment by NateWr** [comment]
Also, the first two links after installation don't work. Registration seems to be obsolete and there's no discussion list.

![selection_028](https://cloud.githubusercontent.com/assets/2306629/17590132/5f336694-5fd0-11e6-883e-a08f3793ee7c.png)

**Comment by NateWr** [comment]
PRs (tests pending):
https://github.com/pkp/pkp-lib/pull/1722
https://github.com/pkp/ojs/pull/971
https://github.com/pkp/omp/pull/321

**Comment by NateWr** [comment]
@asmecher Can you do a code review on this? The tests passed except for the JS linting, which is failing on the same problem that's being resolved in #1536. Since this commit involves no JS changes it's probably ready for review.

**Comment by asmecher** [comment]
All merged, thanks!
