### ISSUE TITLE
file deletion rights

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1725]
I uploaded a file as an editor. Then I wanted to delete it as journal manager and I got the message that I am not allowed i.e. have no rights for this action, but the file is deleted however. What is the right way? Maybe the message shouldn't be there?

**Comment by NateWr** [comment]
Was it a submission file? If so, which stage and grid?

**Comment by bozana** [comment]
I uploaded a supp file at the 1. stage ('Submission') as editor, under the 'Submission Files' where the submitted article from the author is, and wanted to delete it later as a journal manager.

**Comment by bozana** [comment]
Hmmm... Now I couldn't reproduce it, thus I will close the issue... Hmmm... :-O
