### ISSUE TITLE
fail the import if the revision uploader is not in the system

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1728]
From https://github.com/pkp/pkp-lib/issues/1713#issuecomment-239504349 (comment):

> From #1713 (comment):
> 
> ```
> @asmecher, what if the user (or maybe also the user group) from the submission_file revision element from the import XML file doesn't exist in the DB?
> ```
> 
> Hmm, null should definitely not be allowed -- we need to know who is responsible for the file. Do we have enough information to create a user? I suspect probably not. I would suggest, for the moment, failing if the user does not exist; longer term, we may need to merge some capabilities from the user import/export plugin in, permitting references in the XML from files to user entries that more fully describe the user.

**Comment by bozana** [comment]
PRs:
master: https://github.com/pkp/pkp-lib/pull/1986

@asmecher, could you take a look at this PR?

**Comment by bozana** [comment]
@asmecher, I am currently working on the import error display and removing the already processed/imported submissions (in case of an error) i.e. a) and g) from this issue: https://github.com/pkp/pkp-lib/issues/1709. I will then merge this changes there too and soon make a new PR, with all of them, so that you do not have to look at this -- I will remove this PR and issue and combine them with the other... Sorry!

**Comment by bozana** [comment]
This issue moves to l) here: https://github.com/pkp/pkp-lib/issues/1709. Thus, closing...

**Comment by asmecher** [comment]
No problem, thanks!
