### ISSUE TITLE
Dependent file not associating with main file

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1732]
This HTML file has been uploaded and approved, and has a dependent CSS file uploaded to OMP.

http://monographs.lib.sfu.ca/index.php/sfulibrary/catalog/download/1/2/23-5

The CSS file is not associating with the HTML file and as a result not displaying as expected.

**Comment by NateWr** [comment]
The HTML file includes a `<link>` attribute pointing to:

http://monographs.lib.sfu.ca/index.php/sfulibrary/catalog/download/1/2/39-1

This will immediately download the CSS file. My guess is that the lib is forcing download, and this is interfering with how a browser might normally load and interpret a CSS file. When inspecting the asset in Chrome, it appears to be loaded but but the Sources panel doesn't show any output from it.

**Comment by asmecher** [comment]
Ah, yes, I think there are force-download headers on there. Will tinker tomorrow.

**Comment by stranack** [comment]
I'm not sure if it is related, but I believe OMP doesn't yet have an HTML viewer, similar to what OJS 2.x had. Instead the HTML is displayed outside of the OMP context. Or should I file this as a separate issue?

**Comment by NateWr** [comment]
I'd be interested to know your workflow for producing the HTML, @stranack. It seems a shame to me, if you've got an HTML representation of the file, that we can't display the HTML of the full article right there on the article page. HTML is what the web is all about. It would make way more sense for the output, rather than trying to turn it into some kind of "galley". But I realize it might entail a rough transition for people used to creating these standalone "HTML" files.

Maybe we could hop on a call some time this week or next?

**Comment by asmecher** [comment]
In OJS 2.x we used to jam whatever HTML was supplied (typically with its own `head`/`body` etc.) into an OJS-style wrapper, and as a result no OJS journal ever had HTML galleys that were remotely close to valid. I'm at a bit of a loss for a best-practices way to resolve this for OJS3 -- for example we could filter out head/body elements and just take the body text, but then we'd lose any custom headers and styling information. I think Nate's instinct to look at the generation process is a good one, and I have high hopes for other approaches e.g. the XML publishing process leading to a Lens reader interface, but we'll still have to deal with both legacy HTML and users who want to generate HTML from Microsoft Word and Just Have It Work(tm).

**Comment by asmecher** [comment]
I fixed the download header problem -- but what this also took was resetting the MIME type on the uploaded CSS to "text/css" instead of some variant of C code.

**Comment by WaDelma** [comment]
I know that iframes aren't the best thing ever, but wouldn't those allow embedding full html files.

**Comment by NateWr** [comment]
Closing as the initial issue was fixed.
