### ISSUE TITLE
[OMP] new user registration mentions journals

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1734]
With OMP `HEAD`, When registering a new user at the side-wide level (`.../omp_dev/index/user/register?source=`), presses are described as “journals”: “Which journals on this site would you like to register with?” and “If you requested to be a reviewer on any journal, please enter your subject interests.”

**Comment by asmecher** [comment]
Good spotting, @crism -- I suspect we can quickly resolve this by moving some locale keys that ought to be app-specific out of the `lib/pkp` locale files and into the application locale files.

**Comment by crism** [comment]
Nope—this is actually in the OMP code base, probably due to some cut-and-paste error.

**Comment by asmecher** [comment]
Thanks, @crism!
