### ISSUE TITLE
Clearing template cache clears .gitignore files

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1737]
Administration > Clear Template Cache clears the template cache files. It also takes a couple of versioned .gitignore files with it:

```
deleted:    cache/t_cache/.gitignore
deleted:    cache/t_compile/.gitignore
```

Not urgent. Filing for OJS 3.0.1

**Comment by ctgraham** [comment]
Not urgent, but damn annoying.

**Comment by NateWr** [comment]
@ctgraham This is a useful command that I use to clear templates and css when I work on the frontend. Executed from the `/cache` directory: `rm -r *.php *.css HTML t_compile/*.php`. 

Only way I can keep from going crazy. :)

**Comment by ctgraham** [comment]
My strategy has been:
* *Le sigh*
* `git checkout -- .gitignore`

**Comment by NateWr** [comment]
I took a quick stab at this today by just consolidating the `.gitignore` directives into the global `.gitignore` file. But of course git them removes the cache directories and the caching system doesn't create them if they don't exist.

Seems like it shouldn't be too difficult to create the necessary directories on initial setup, but it's more then I want to bite off right now. 

Punting to 3.0.2 unless anyone wants to fix this.

**Comment by asmecher** [comment]
Alternately, why not just make the cache clear functions more selective in what they remove?

**Comment by asmecher** [comment]
The more I think about this, the more I think this is a problem in Smarty, not a problem in OJS/pkp-lib. It's the [Smarty functions](https://github.com/pkp/pkp-lib/blob/ojs-stable-3_0_2/classes/template/PKPTemplateManager.inc.php#L786) that are deleting overzealously.

**Comment by jamshidhashimi** [comment]
It looks we were using an older version of Smarty. This issue looks resolved after the smarty version was updated in pkp-lib's `composer.json`.

Also, see [this](https://github.com/smarty-php/smarty/commit/a9e7e8881e36ef59b8cf9a948a54a1a15e2b794c#diff-83fc60aa9662328e03f12255e54116e1) and [this](https://www.smarty.net/forums/viewtopic.php?p=70440&sid=ab919de8ffc65ad7f9c3360626ba4b2f).

Tested locally as well.

@NateWr @asmecher please confirm.

**Comment by NateWr** [comment]
:+1: great!
