### ISSUE TITLE
Implement theme options

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1739]
An issue to track work on a theme options API.

- [x] Implement API to add options, with fields generated automatically and an API for accessing options.
- [x] Default theme: add font selections
- [x] Default theme: add color picker
- [x] Bootstrap theme: add theme selector
- [ ] Bootstrap theme: add color pickers which match bootstrap variables
- [ ] Document API
- [ ] Extend with more field types

Related but not planned to be part of the theme options API: #787

**Comment by asmecher** [comment]
@NateWr, mind summarizing the PRs here? I'll take a look at the linting issue etc.

**Comment by NateWr** [comment]
The new theme options API is a set of methods on the `ThemePlugin` class. It's still very nascent and could use a lot of building out of its feature-set.

- Added a hook to `PluginRegistry::loadCategory()` which fires after a category has been loaded. This allows themes to be intialized _after_ the load, so that parent/child themes are aware of each other regardless of when they appear in the load order.
- Add `addOption()` and `getOption()` methods on the ThemePlugin class intended to be used by themes.
- Add methods to the ThemePlugin class which allow it to tie into `Form` hooks for `readUserVars()` and `execute()`.
- Added hooks for the appearance form and site settings form. This required loading the themes when the form is instantiated (so that hooks are registered before being fired), so it's not generalizable in the way I'd like.
- Clear template and CSS cache when a theme option is updated.
- Adjusted the `themes.tpl` template used for selecting a theme. Now the appearance and site settings forms will load theme options related to the currently active theme. If a theme is switched, a new `ThemeOptionsHandler.js` will remove the theme options but it doesn't yet fetch the ones for the new theme (this is really rough but will work to get some basic options in for 3.0).
- Theme options only support text, radio and color field types at the moment.
- A new gitmodule was added for spectre, a simple color picker (the one in your browser's devtools) which falls back to the HTML5 `color` input if supported.
- The default theme was given typography and color options. The bootstrap3 theme now includes a selector to choose one of the bundled sub-themes.

Once we can get the OJS tests passing, I'll submit PRs for pkp-lib and OMP too.

**Comment by NateWr** [comment]
I've fixed a number of tests, but still having a JS linting issue, and the last `mysql` test timed out. But in the interests of time, I've gone ahead and opened PRs for the various repos.

PRS:
https://github.com/pkp/pkp-lib/pull/1763
https://github.com/pkp/ojs/pull/985
https://github.com/pkp/omp/pull/330

If it's not too late for you @bozana, can you code review? Otherwise @asmecher can take over. He'll probably need to step in to work out the JS linting issue anyway...

**Comment by bozana** [comment]
@asmecher, could you please overtake the code review for this? -- I am not so familiar with themes. I think I found the solution for the JS linting error... :-)

**Comment by asmecher** [comment]
Thanks, @NateWr & @bozana. A few changes before it's ready to merge, @NateWr, but I don't think it'll need another review -- once you're ready, go ahead and merge. This looks really good.

**Comment by bozana** [comment]
I knew Alec would be more helpful! :-)

**Comment by NateWr** [comment]
Tests are running.

I want to do just a bit of manual testing on this tomorrow, since I had to rush through the changes, so hold off on merging if you see the tests pass.

**Comment by asmecher** [comment]
> if you see the tests pass

ha ha ha

**Comment by NateWr** [comment]
@asmecher 

OJS tests are passing!

OMP tests are failing on `AclarkSubmissionTest`. The OMP PR for #1528 is failing on this test as well, which makes me a bit suspicious.

**Comment by asmecher** [comment]
As elsewhere, go ahead for OJS. I can run through tests locally for OMP on Friday and see what's gotten it bottled up.

**Comment by NateWr** [comment]
Merged!
