### ISSUE TITLE
Translations of some titles in Portuguese

### ISSUE THREAD

**Issue by amandasramalho** [pkp/pkp-lib#1741]
I noticed that some texts/titles are not translated into Portuguese. (OMP)
See below my contributions:

**Comment by asmecher** [comment]
Tagging @mtub, who manages translations. He's on vacation for a little while so might take some time to respond.

**Comment by gpassero** [comment]
Also:
##journal.viewAllIssues## ( on journal start page :( )

**Comment by mtub** [comment]
Sorry for neglecting this - I thought these translations had long been provided. If anyone is willing to send a pull request, I will gladly (and quickly) review and merge it.
