### ISSUE TITLE
Action "copy review form" inactive

### ISSUE THREAD

**Issue by amandasramalho** [pkp/pkp-lib#1747]
When I click in "copy form" it opens a screen confirmation of the action, but when I click "ok" nothing happens.

![copyreviewform](https://cloud.githubusercontent.com/assets/5446933/17863260/575d4528-686f-11e6-8aa2-8cf254be367d.png)

**Comment by asmecher** [comment]
@amandasramalho, can you check your PHP error log to see if something appears there?

**Comment by amandasramalho** [comment]
@asmecher See attached!

[2016-09-01+omp_scielo_org-error.zip](https://github.com/pkp/pkp-lib/files/451900/2016-09-01.omp_scielo_org-error.zip)

**Comment by asmecher** [comment]
@amandasramalho, I think this has already been fixed by https://github.com/pkp/pkp-lib/commit/0480ac5eafdb22a05b17a01cb821f3cc215561ca -- could you try refreshing your installation with the latest code (or cherry-picking in that commit)?

**Comment by amandasramalho** [comment]
@asmecher Unfortunately the error continues.

[erro_omp.zip](https://github.com/pkp/pkp-lib/files/462280/erro_omp.zip)

**Comment by asmecher** [comment]
@amandasramalho, can you try turning on the `show_stacktrace` setting in your `config.inc.php` then triggering the error again? That might give some more detail in the error log.

**Comment by amandasramalho** [comment]
@asmecher The log is attached.
[omp-error.zip](https://github.com/pkp/pkp-lib/files/467864/omp-error.zip)

**Comment by asmecher** [comment]
Hmm, I'm still not seeing the expected stack trace, and my copy isn't showing the same behavior. Can you confirm that you're using the current `master` branch, both for the application, and the `lib/pkp` submodule?

Another way to get some information from your installation, if you have a developer toolbar like Firebug for Firefox -- just before hitting the "OK" confirmation to copy the form, edit your `config.inc.php` and turn the `Debug` option to `On`. Then hit the confirmation button. The resulting server response will dump out all database queries to the browser. Use the developer toolbar to capture the resulting queries. Grab the last few in the list -- I suspect they'll provide more information about the problem you hit.

**Comment by amandasramalho** [comment]
@asmecher See the image to the record of Firebug:
![captura de tela 2016-09-15 as 11 57 45](https://cloud.githubusercontent.com/assets/5446933/18593949/170fdc02-7c14-11e6-9375-4342363b297a.png)

Our version of PHP is:
PHP 5.6.25 (cli) (built: Aug 31 2016 00:36:42) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by asmecher** [comment]
@amandasramalho, look for the subrequest with a URL containing `copyReviewForm`; expand that row in the list to see if you can inspect the response the server returned. You'll likely find that it contains error messages; please post those here and I'll see what I can do.

**Comment by amandasramalho** [comment]
@asmecher 
![image](https://cloud.githubusercontent.com/assets/5446933/18598075/82199a20-7c27-11e6-9244-d10d48ef093d.png)
![image](https://cloud.githubusercontent.com/assets/5446933/18598099/9ae56c6e-7c27-11e6-92ab-0a212655b071.png)

**Comment by asmecher** [comment]
Thanks, @amandasramalho, that's what I was looking for! I've committed 040d0ba to the master branch -- could you see if that fixes the issue?

**Comment by amandasramalho** [comment]
Hi @asmecher 
We apply the fix and now everything is okay!
Thank you!

P.s. There are any current manual system use?

**Comment by asmecher** [comment]
Hi @amandasramalho -- thanks, glad to hear it!
There are currently two manuals that might help:

- https://pkp.gitbooks.io/ojs3/content/en/
- https://pkp.gitbooks.io/ojs-user-guide/content/en/

**Comment by amandasramalho** [comment]
@asmecher 
These manuals are of OJS, right? And what about manuals for OMP?

**Comment by asmecher** [comment]
Sorry, my assumption :) For OMP:

- https://pkp.gitbooks.io/omp-1-2-user-guide/content/en/
