### ISSUE TITLE
remove PHP 5.3 code from OJS 2.4.8-1

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1749]
s. http://forum.pkp.sfu.ca/t/cannot-update-the-database-using-php-5-2/17821

the PR is comming...

**Comment by bozana** [comment]
ojs-stable-2_4_8 PR: https://github.com/pkp/ojs/pull/994
ojs-dev-2_4 PR: https://github.com/pkp/ojs/pull/995
@asmecher, why are those tests failing? :-(
Else, it would be ready to merge...

**Comment by asmecher** [comment]
@bozana, looks like the Closure compiler/linter was unavailable for a short time. I've restarted those tests and expect they'll pass (the download link is working again for the part that failed).

**Comment by bozana** [comment]
Merged, thus closing...
