### ISSUE TITLE
[OJS] Make changelogs to be part of the version control

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1750]
I tried to find what changed between two versions OJS (2.4.4.1 and 2.4.8.1 to be exact) and first thing I looked for was a changelog.    
It seems that only the changelog for newest release is available.    
I suggest moving it to a file under version control so that tracking changes would be easier.

**Comment by asmecher** [comment]
@WaDelma, we ship release notes that are much more usable than the change logs; see `docs/release-notes`. We used to include historical changelogs with each release, but removed them starting with OJS 2.4.7. Detailed change information is available from github.com, which IMO is much more usable than a changelog. My sense was that the changelogs were just taking up space.

**Comment by WaDelma** [comment]
Ah, okay. Also is there better place to ask code related questions? I don't want to spam this place with stuff that could be answered easily. (Like I am currently trying to figure out how DOI plugin works and would like to ask specific question regarding it).    
The question thread in forums seems to be for different level of questions...

**Comment by WaDelma** [comment]
The question was: Where/How DOIs get stored?

**Comment by bozana** [comment]
The DOIs will be stored in the object settings table e.g. article_settings

**Comment by asmecher** [comment]
@WaDelma, the forum is generally the best place, but I'm happy to answer questions here too. Generally, specific code-related stuff can either go in the forum or here, and user-related questions and higher-level functionality questions are best in the forum. Closing this issue for now.
