### ISSUE TITLE
Extra closing </div> on homepage if no announcements exist

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1751]
> in OMP (master and 1.2.0, if there are no announcements, the page will be broken by a closed div of a "non existent" div.

https://github.com/pkp/omp/blob/master/templates/frontend/pages/index.tpl#L76

The same pattern is used in OJS so should be checked for problems.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/986
https://github.com/pkp/omp/pull/326

@bozana I don't anticipate any issues with this. Mind code reviewing and merging?

**Comment by bozana** [comment]
@NateWr, merged both, can the issue be closed?
