### ISSUE TITLE
OpenAIRE plugin migration to 3.0

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1754]

**Comment by bozana** [comment]
PR: https://github.com/pkp/ojs/pull/991
@asmecher, if this can be integrated for 3.0, I would ask @NateWr to code review... :-)

**Comment by asmecher** [comment]
Yes, that sounds fine -- @NateWr, consider yourself assigned!

**Comment by NateWr** [comment]
The code looks good @bozana. I have a couple of UI/UX questions.

1. Will authors who are making a submission always know what OpenAIRE is and what their ProjectID is?  Can we be more helpful in explaining to the submitting author what they are being asked to provide, as well as whether it's really expected or an optional extra?

![selection_048](https://cloud.githubusercontent.com/assets/2306629/17999367/dc6c107e-6b70-11e6-81e8-89080d5a3448.png)

2. Is the project ID supposed to be displayed on the frontend?

**Comment by bozana** [comment]
@NateWr, yes we could better explain it, maybe something like this: The research publications, that resulted from EU projects and initiatives "The European Commission’s Seventh Framework Programme" (FP7) "Open Access Pilot", "The European Research Council (ERC) Scientific Council Guidelines for Open Access" are harvested and visible on the OpenAIRE platform. This publications should contain the project ID, that equals the Grant Agreement identifier.

The authors should then know their Project ID/Grant Agreement number, because the publication is a result of that EU project. 
I don't think the project ID should be displayed at the frontend -- at least not in this version -- it will be displayed/delivered via OAI -- for OpenAIRE to harvest it...

**Comment by bozana** [comment]
Or maybe @stranack could help us with the better explanation?

**Comment by NateWr** [comment]
Ok, my recommendation would be:

**OpenAIRE ProjectID**
If this research resulted from an EU initiative that complies with the OpenAIRE metadata platform, please include the ProjectID, a six-digit number which corresponds with the Grant Agreement identifier.

If there's a link that we can point to with more details, that'd be great to include.

Thoughts @stranack?

**Comment by asmecher** [comment]
Closing!
