### ISSUE TITLE
[OJS] duplicate keys in usageStats plugin (also: duplicate plugin)

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1757]
in master branches, both OJS and pkp-lib have a generic/usageStats plugin with partly the same locale key names in both directories… please check which version is recent and needed…

(also, the lib-pkp version has "OMP usage statistics report" in it…)

**Comment by asmecher** [comment]
The "OMP" reference in `lib/pkp` has already been resolved.

The OJS locale files were pure duplicates; I've removed them.
Them OMP ones add a few locale keys; I've kept those files where the additional keys were translated and removed the files otherwise.
