### ISSUE TITLE
Call to removed function getLatestGalleyFiles in article_details.tpl

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1760]
That function has been removed (some time ago); OTOH you should be able to use `$galley->getFile()` (checking if it exists or not -- it may be a remote URL galley instead).

**Comment by NateWr** [comment]
Are you maybe talking about [galley_details.tpl](https://github.com/pkp/ojs/blob/master/templates/frontend/objects/galley_details.tpl#L19)?

It looks like this file came with some work @bozana did on pub ids. It appears to be a galley interstitial view. Any advice on how I can view it and style it as needed?

I noticed the same method is used in the `lensGalley` and `pdfJsViewer` plugins.

**Comment by bozana** [comment]
Hmmm... I think I introduce it, like a galley view page, where the pub ids are displayed, but I believe it is not needed i.e. there shouldn't be that galley front end page, right?

**Comment by NateWr** [comment]
Ideally, PDFs, HTML and eLens galleys would just load themselves for viewing, and other formats would just download themselves. But maybe @asmecher knows of another reason these pages need to exist. I know there is some Google Scholar stuff related to interstitials.

**Comment by bozana** [comment]
I think this template gelley_details.tpl is not used at all and can be deleted

**Comment by NateWr** [comment]
Thanks, I can do that tonight or tomorrow night unless Alec suggests otherwise.

**Comment by asmecher** [comment]
@NateWr, `galley_details.tpl` appears to be referenced from `templates/frontend/pages/article.tpl`.

**Comment by NateWr** [comment]
Yes it is. I just don't know if it's actually used or required.

**Comment by bozana** [comment]
I think it is not -- in the pages/article/ArticleHandler, in the function view, where the templates/frontend/pages/article.tpl is called: if there is a galley the function download is called. 
That was earlier code, I believe, and when I was testing galley pub ids... Sorry :-\

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/1005

(tests still running)

**Comment by NateWr** [comment]
@asmecher: two errors due to timeouts in the `CrossrefNlm30CitationSchemaFilterTest` tests. Probably safe to merge?

**Comment by asmecher** [comment]
Merged, thanks -- test problems are unrelated. Closing!
