### ISSUE TITLE
Sidebar Management Wording

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1765]
Under Settings > Website > Appearance, in the Sidebar Management section, the text reads:

**Sidebar Management**
Left Sidebar               Unselected

However, the sidebar on the default reader interface is on the right. We should either reword "Left Sidebar" to "Right Sidebar" or just "Sidebar".

**Comment by asmecher** [comment]
@NateWr, passing this your way.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1774

@asmecher I searched the `tests` directories in pkp-lib, ojs and omp for any mention of sidebars, and didn't find anything that this change should effect. But if you want me to push some OJS/OMP commits to do the tests let me know.

**Comment by NateWr** [comment]
@mtub Sorry, this is kind of an annoying last-minute change to the locale.

**Comment by asmecher** [comment]
I'm going to reschedule this for 3.0.1 for two reasons:

- [ ] Remaining locales
- [ ] The locale key is still `.leftSidebar` -- and there's correspondingly `.rightSidebar` etc. These need cleaning up.

**Comment by NateWr** [comment]
I've updated all references to "left" sidebar with just "sidebar". I figure we can treat this as "primary" sidebar, and any future sidebars we may implement (article pages, footers), can be named specifically like `SIDEBAR_FOOTER`. I also removed all of the outdated strings from the locale files.

PRs:
https://github.com/pkp/pkp-lib/pull/1935
https://github.com/pkp/ojs/pull/1078
https://github.com/pkp/omp/pull/343
https://github.com/pkp/customBlockManager/pull/13

An update to the `makeSubmission` block was roled in as a submodule update to OJS/OMP. I've given the Bootstrap3 theme a new branch (`ojs-3.0.1`) that we can merge in once 3.0.1 is released. And maybe then I can implement proper versioned updates for the theme.

**Comment by NateWr** [comment]
There's some new code that got merged today with the old sidebar references. #1859

**Comment by asmecher** [comment]
@NateWr, is this one ready for code review etc.?

**Comment by NateWr** [comment]
Tests passed! Ready for code review.

**Comment by asmecher** [comment]
All merged, thanks, @NateWr -- note that I'm _not_ going to back-port this to the stable branches, as it'd break compatibility with third-party plugins, despite the fact that this represents a divergence between the stable and master branch locale files that we've been able to avoid so far.
