### ISSUE TITLE
[OJS] theme plugin upgrading fails with wrong category message

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1766]
When trying to upgrade a theme by uploading a new `.tar.gz` file, I get a message, “The uploaded plugin does not fit the category of the upgraded plugin.” Initial debugging shows that `PluginHelper::upgradePlugin()` is being called with a blank `$category` value.

**Comment by asmecher** [comment]
@crism, what version of OJS are you using? Does your plugin have a `version.xml` descriptor? Could you post the tarball somewhere?

**Comment by crism** [comment]
Sorry, this is latest-and-greatest as of this morning. The plugin is nearly identical to something previously uploaded; the category is correctly read from `version.xml`, but `UploadPluginForm::execute()` doesn’t get a `$request` object with `category` or `plugin` set. The value’s not getting passed through from `PluginGridHandler::_showUploadPluginForm()`, a victim of the switch to AJAX-land.

**Comment by asmecher** [comment]
@NateWr has been working on this recently and may be able to help. If you provide him with a plugin tarball, it'll be that much easier :)

**Comment by crism** [comment]
See [the IOPN theme](https://github.com/PublishingWithoutWalls/pkp-iopn/tree/master/themes/ojs/iopn)—so far, just a renamed clone of the default theme.

**Comment by crism** [comment]
The `uploadFormPlugin.tpl` form template needs a couple of hidden parameters passed through. Need to brush up on Smarty, again…

**Comment by WaDelma** [comment]
#1650 should fix this problem.

**Comment by NateWr** [comment]
@crism There are a bunch of changes coming in with the theme options API, which should be merged today or tomorrow.

https://github.com/pkp/pkp-lib/issues/1739

I've never "upgraded" a plugin and I'm not too familiar with the process. But happy to look into it once we get 3.0 out the door.

**Comment by crism** [comment]
@NateWr, upgrading is the same as installing, except it supersedes the selected plugin. There are a bunch of checks that the superseding is correct, and those checks don’t have enough information to correctly evaluate it, so the upgrade is rejected. This is particularly important for themes, because the development process involves making changes and uploading them…

**Comment by crism** [comment]
I think I’m running into the same problem that @WaDelma did. In `AdminPluginGridHandler::authorize()`, access is restricted iff `$category` and `$plugin` are specified. This seems to mean that anyone with access to the plugin panel can upload a plugin, but hardly anyone can upgrade one.

**Comment by crism** [comment]
Ah-hah! This is actually a problem with context `0`. I’m trying to upgrade the plugin site-wide, but that requires the user to have a role. There’s no affordance for users to have roles outside the context of a specific journal, so even as the überadmin, I’m rejected.

**Comment by crism** [comment]
Or… maybe not. I got rejected upgrading with respect to a specific journal, too. There’s no reason this user shouldn’t have permission to do pretty much anything.

**Comment by asmecher** [comment]
@bozana, I think you were tinkering with some related code recently. Mind taking a look?

**Comment by bozana** [comment]
@crism, could you see/test if the commits from the issue https://github.com/pkp/pkp-lib/issues/1872 solved the problem? -- they are merged both in master and ojs-stable-3_0_0

**Comment by crism** [comment]
I was able to upgrade my theme plugin using `HEAD` of OJS as of this morning. Thanks!

**Comment by asmecher** [comment]
Thanks, @crism and @bozana -- closing!
