### ISSUE TITLE
About link on reader nav bar

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1767]
From the reader interface, Under About, we no longer have an About link, just Editorial Team, Submissions, Contact.

I know that clicking About takes you to the about page, but many users missed it in testing when it was setup like this, so we changed it so the menu options were: About, Editorial Team, Submissions, Contact.

Can we do this for OJS 3 as well as OMP 1.2?

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/1006

The sub-menu link will appear once content has been added to About the Journal under Settings > Journal. I just removed the conditional so that it always appears -- I think it's fair for us to strongly encourage the use of the about page by default.

**Comment by NateWr** [comment]
The tests timed out but I think it's safe to merge, @asmecher. yolo

**Comment by asmecher** [comment]
Merged, thanks -- but moving over to OMP rather than closing, as I think it still needs porting there.

**Comment by NateWr** [comment]
No OMP is fine. They have separate primary menus (eg - Catalog vs Current Issue).

**Comment by asmecher** [comment]
Ah, OK, thanks!
