### ISSUE TITLE
[OJS] Native importexport plugin seems to be broken

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1768]
As I noticed in [forum post](http://forum.pkp.sfu.ca/t/migrating-from-legacy-database-to-ojs/18771) the native importexport seems to be broken.  
I tried to export test article and the import it back and it failed.

**Comment by WaDelma** [comment]
Apparently exporting issue and importing it works fine. So the problem is just with importing articles.

**Comment by bozana** [comment]
@WaDelma, if this is an issue for OJS 3.0: yes, only article import is not possible at the moment. See/track the c) here: https://github.com/pkp/pkp-lib/issues/1709.

**Comment by bozana** [comment]
@WaDelma, the only article import is implemented, thus could this issue be closed now?
