### ISSUE TITLE
Consider adding aria-required to required fields

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1772]
We already use the HTML5 `required` attribute, but it's not clear how many screen reader tools support this instead of `aria-required`. Do some research and then implement if necessary.

**Comment by NateWr** [comment]
I asked an ally expert I know who recommended we use `aria-required`. https://twitter.com/coolfields/status/772427731564957696

**Comment by NateWr** [comment]
I looked at this today. Since we've been attaching the visual required indicator to labels rather than fields, for the most part we don't have the required flag set up properly when defining fields in most of our forms.

A quick estimate looks like 70-100 instances of this would need `required=true` flags added to the form field calls in template files.

Depending on how you want to handle this, I can run through each of these, so that the `required` attribute is assigned to the label _and_ the field for each of these instances. Or we can dump this on the pile of things to be addressed with a broader refactor of the FBV.

**Comment by NateWr** [comment]
PRs (tests running):
https://github.com/pkp/pkp-lib/pull/1942
https://github.com/pkp/ojs/pull/1080
https://github.com/pkp/omp/pull/345

I went through and updated manually everywhere I could find that seemed appropriate. There are still some areas (file uploads, tinymce fields) where I'm not sure how a required attribute would work.

Because this was a manual job, I think there's a high likelihood of introducing a bug here. I did click through a bunch to try and test, but I'm bound to have missed stuff. Probably best that we don't cherry-pick this back to stable versions.

**Comment by asmecher** [comment]
The tests are failing, both for OJS and OMP in different places, so I think there must be a legit breakage.

**Comment by asmecher** [comment]
(The tests fail consistently at the same spot regardless of whether it's MySQL or PostgreSQL, which is a hint that it's probably not a false positive)

**Comment by NateWr** [comment]
Re-kicked the tests on these. @bozana can you code review?

**Comment by bozana** [comment]
@NateWr, everything fine. A rebase seems to be needed, but then, it can be merged... Thanks!

**Comment by NateWr** [comment]
Ok, tests are running on rebase number six. :laughing:

**Comment by NateWr** [comment]
Restarted the OJS tests which timed out...

**Comment by bozana** [comment]
@NateWr, no idea why OJS tests are failing :-( Mind you rebase and push it again? :-(

**Comment by NateWr** [comment]
Hmm, I noticed that they all failed on the same `createIssue` test. I created an issue manually just to check and didn't have problems. I've restarted the OJS tests, but if they fail at the same place again, maybe there's something going on.

**Comment by asmecher** [comment]
Moving to 3.0.2.

**Comment by NateWr** [comment]
@asmecher The tests seem to be failing on the `createIssue` task. However, they don't include any information. They seem to be timing out here.

https://travis-ci.org/pkp/ojs/builds/177992614

I've created an issue manually to see if I could spot any problem but didn't see anything. Do you have any ideas?

**Comment by asmecher** [comment]
@NateWr, your `lib/pkp` submodule is old and needs a rebase -- it's missing some of Bozana's more recent changes that are already in your OJS branch. Once it's rebased it'll run (I've tested locally).

**Comment by NateWr** [comment]
Rebased and tests running.

**Comment by NateWr** [comment]
All tests failed at `testCreateIssues` again. @asmecher are you sure this is working or should I dig into the test failure some more?

**Comment by asmecher** [comment]
The problem is `templates/controllers/grid/issues/form/issueForm.tpl` -- with these changes in place, the Volume, Number, Year, and Title fields are all required, but that shouldn't be the case. They should only be required when the respective checkboxes are ticked.

**Comment by NateWr** [comment]
Thanks @asmecher! This presents some new problems but I'll file those in a separate request. Tests running again.

**Comment by asmecher** [comment]
@NateWr, the OMP tests appear to be OK (I just restarted one straggler), but the OJS tests still seem to be stuck on the create issue test. Would you like me to try locally again?

**Comment by bozana** [comment]
New PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2123
ojs master: https://github.com/pkp/ojs/pull/1155

**Comment by bozana** [comment]
everything merged to master, can the issue be closed?

**Comment by NateWr** [comment]
Thanks @bozana!

**Comment by asmecher** [comment]
Phew! Thanks, @bozana and @NateWr.
