### ISSUE TITLE
[OMP] Current master points to unknown commit of pkp-lib submodule

### ISSUE THREAD

**Issue by isgrim** [pkp/pkp-lib#1773]
Hi everyone,

the current (https://github.com/pkp/omp/commit/677932c45ab3523a11289bfcd26ede7686b8373c) master branch of the omp repository does point to an unknown commit of pkp-lib.
Maybe someone forgot to push the commit to the remote?

`Unable to checkout '5c9b56312727ef8d08ee17d25102d7f42a08c8f1' in submodule path 'lib/pkp'`

**Comment by asmecher** [comment]
Hi @isgrim -- that's entirely possible, we're working hard and fast on the release of OJS 3.0. I've pushed up a new submodule update; please let me know if the problem persists.
