### ISSUE TITLE
[OJS] Announcement description is saved, but not displayed

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1780]
Any announcement description added to Settings -> Website Settings -> Announcements is saved, but not displayed on the Announcements page.

**Comment by NateWr** [comment]
@jmacgreg can you describe a bit more what you're expecting to see but not seeing? I've just tested quickly and I see the announcements displayed properly. The **Short Description** is meant to be a summary for presentation in announcements lists. The **Description** should be the full text of the announcement which only appears on the single announcement's page.

Are you seeing something different? Did you expect something different?

**Comment by jmacgreg** [comment]
Sorry guys, I can't actually figure out what I was on about before. Closing for lack of internal clarity.
