### ISSUE TITLE
[OJS] BibTeX citation display format doesn't work

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1781]
Viewing an article and clicking the "BibTeX" option should (IIRC) display citation information in TeX markup; instead, nothing happens.

**Comment by asmecher** [comment]
I fixed the syntax error that was causing the problem, so now it works, but it's ugly. @NateWr, just letting you know -- this is currently flagged against 3.0.1, not 3.0 -- but the BibTeX output could probably stand some kind of "copy to clipboard" button instead of just dumping it out.

**Comment by asmecher** [comment]
Fixed by https://github.com/pkp/ojs/pull/1008!
