### ISSUE TITLE
Ensure ReCaptcha language is correct

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1786]
...either by checking its autodetection feature, or by specifying directly.

(From: https://github.com/pkp/pkp-lib/issues/1775)

**Comment by Vitaliy-1** [comment]
ReCaptcha uses browser language but not the language of page html. Ideally when user changes language the ReCaptcha must change language to. In theory this can be supported by adding the first 2 letters from html lang attribute to the end of the reference to google ReCaptcha. But supported languages must be explicitly pointed.

**Comment by asmecher** [comment]
See the attached patch. This isn't a perfect match -- Google's ReCaptcha [language codes](https://developers.google.com/recaptcha/docs/language) don't use a consistent standard, and I don't like the idea of manually maintaining a mapping between standard language codes from Google's set. So for the moment we're taking the first 2 letters of the locale, e.g. `pt` for Portuguese rather than `pt-PT` or `pt-BR`, which would be more specific but would require manual maintenance of the mapping.
