### ISSUE TITLE
Tab-specific primary nav menu items don't work when already on page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1787]
24352f197923298e5c4903dc6af31291116cc2ba introduced new links for nav menu items to open secondary tabs on pages directly.

This works if the user is on an entirely different page. But if the user is on the page where the tabset is, it doesn't open the new tab (though it does seem to focus on it).

Example: Go to the Issues page. Then click on the Issues > Back Issues link in the primary nav menu on the left. The tab will be highlighted but back issues won't be loaded.

**Comment by NateWr** [comment]
PR: https://github.com/pkp/pkp-lib/pull/1915

Tests running at: https://github.com/pkp/ojs/pull/1074

**Comment by asmecher** [comment]
Merged and cherry-picked over to `ojs-stable-3_0_0`, thanks!
