### ISSUE TITLE
[OJS] stable-3_0_0 translations 

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1790]
Hi all, 
great to see ojs 3 is going stable :-) 
I just cloned the stable branch of ojs 3 and made a basic setup. Unfortunately, I came cross some missing translations. 
Here is the list: 
##about.onlineSubmissions.submissionActions##
##plugins.themes.default.option.typography.label##	
##plugins.themes.default.option.typography.notoSans##
##plugins.themes.default.option.typography.notoSerif##
##plugins.themes.default.option.typography.notoSerif_notoSans##
##plugins.themes.default.option.typography.notoSans_notoSerif##
##plugins.themes.default.option.typography.lato##
##plugins.themes.default.option.typography.lora##
##plugins.themes.default.option.typography.lora_openSans##
##plugins.themes.default.option.colour.label##	
##plugins.themes.default.option.colour.description##

**Comment by asmecher** [comment]
Thanks, @henkela -- @mtub is probably already aware of these. There were a few last-minute locale key changes that didn't get updates.

**Comment by mtub** [comment]
Thanks, @henkela, for reporting these. As Alec said, there had been a few last-minute updates to the OJS 3 code that couldn't be translated. Will look into doing these over the next weeks, together with further updates. These translations will go to GitHub and will be included in the next updated release (https://github.com/pkp/pkp-lib/milestone/10). As always: feel free to make suggestions for translations that are missing or not perfect.

Just to spare you some work: We can scan for missing translations quite effectively, so while I like your thorough reports, it's not always necessary to list all of the missing keys. With regards to plugins: They are not the highest in our translation priority, but it's always good to know how the community feels about plugins, so if you're particularly interested in a particular plugin, please let me know or suggest a translation.

Thanks!

**Comment by t4x0n** [comment]
Hi, where can I make some suggestions for Spanish translations? I have my install more accurate that default version (default version have a lot of missing translations). So, maybe I could put my changes here in GitHub, but I don't know where can I put these suggestions... can you please give me a link or some info about that? thanks!
