### ISSUE TITLE
Port QuickSubmit plugin to OJS 3.0

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1792]

**Comment by defstat** [comment]
I am on that....

**Comment by asmecher** [comment]
Assigned!

**Comment by bozana** [comment]
I think, the milestone here can be changed -- it is ready for OJS 3.0.2, right? Maybe the next milestone would be OMP?

**Comment by asmecher** [comment]
I need to either add the plugin as a submodule or (better) add it to the plugin gallery; just leaving it open until then so I don't forget. I don't think we need this plugin for OMP, or at least not yet.

**Comment by asmecher** [comment]
Added to plugin gallery!

**Comment by bozana** [comment]
Coooooool! :-)

**Comment by marcbria** [comment]
I can't find this plugin in the plugin gallery of the last OMP (3.1.1.4).
It this plugin supersede by any OMP core feature?

Sorry in advance if this is not he right place/post to ask.

**Comment by asmecher** [comment]
@marcbria, there isn't an OMP QuickSubmit plugin (yet); just an OJS one.

**Comment by Riznor** [comment]
The plugin is in my gallery but I can't install it.

**Comment by asmecher** [comment]
@Riznor, the best place to get technical support is on our support forum at https://forum.pkp.sfu.ca. Include information on what version of OJS you're using, how you tried to install the plugin, and what the result was.

**Comment by Riznor** [comment]
Thank you, @asmecher.
