### ISSUE TITLE
[OJS] #submissionFilesGridDiv div never loads

### ISSUE THREAD

**Issue by kardeiz** [pkp/pkp-lib#1794]
The `#submissionFilesGridDiv` div never loads on step 2 of the "Submit an Article" process. The dev console shows that `http://my-url/index.php/my-journal/$$$call$$$/grid/files/submission/submission-wizard-files-grid/fetch-grid?submissionId=12&_=1472833858245` returns a 404.

This is with the new 3.0.0 release. The same thing happens whether I am a journal manager/editor or a newly registered user with the author role.

**Comment by asmecher** [comment]
@kardeiz, can you confirm that `lib/pkp/controllers/grid/files/submission/SubmissionWizardFilesGridHandler.inc.php` exists in your installation?

**Comment by kardeiz** [comment]
Whoops, good call; it is absent. Looks like a bad deployment process on my part. I apologize for wasting your time! Thank you for your fast response!

**Comment by asmecher** [comment]
No worries, glad to hear it was an easy fix.
