### ISSUE TITLE
Spectrum colour picker not loaded in journal settings wizard

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1795]
When accessing the Appearance form via the journal settings wizard, then "spectrum" colour picker is not loaded, leading to...

    TypeError: $colourInput.spectrum is not a function

...and since JS stops executing, other page elements have trouble after this.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1799

Tests running at:
https://github.com/pkp/ojs/pull/1010

**Comment by asmecher** [comment]
Committed. To patch an OJS 3.0.0 installation, apply https://github.com/pkp/pkp-lib/pull/1799/commits/b3db8542d3bca57851c2e48ca545d237a9ed924e within `lib/pkp`.
