### ISSUE TITLE
[OMP] OAI Dc11 Metadata plugin not working in omp-stable-1_2_0. Missing method from pkp-lib

### ISSUE THREAD

**Issue by isgrim** [pkp/pkp-lib#1798]
Hi everyone,

i get the following error when accessing the OAI endpoint with ListRecords:
`PHP Fatal error:  Uncaught Error: Call to undefined method PublishedMonograph::getFullTitle() in /home/nw/dev/projects/omp1.2/plugins/metadata/dc11/filter/Dc11SchemaPublicationFormatAdapter.inc.php:83\nStack trace:\n#0 /home/nw/dev/projects/omp1.2/lib/pkp/classes/metadata/MetadataDataObjectAdapter.inc.php(266): Dc11SchemaPublicationFormatAdapter->extractMetadataFromDataObject(Object(PublicationFormat))\n#1 /home/nw/dev/projects/omp1.2/lib/pkp/classes/filter/Filter.inc.php(447): MetadataDataObjectAdapter->process(Object(PublicationFormat))\n#2 /home/nw/dev/projects/omp1.2/lib/pkp/classes/core/DataObject.inc.php(445): Filter->execute(Object(PublicationFormat))\n#3 /home/nw/dev/projects/omp1.2/lib/pkp/plugins/oaiMetadataFormats/dc/PKPOAIMetadataFormat_DC.inc.php(22): DataObject->extractMetadata(Object(Dc11Schema))\n#4 /home/nw/dev/projects/omp1.2/plugins/oaiMetadataFormats/dc/OAIMetadataFormat_DC.inc.php(29): PKPOAIMetadataFormat_DC->toXml(Object(PublicationFormat), NULL)\n#5 /home/nw/dev/projects/omp1.2/lib/pkp/classes/oai/OAI.inc.php( in /home/nw/dev/projects/omp1.2/plugins/metadata/dc11/filter/Dc11SchemaPublicationFormatAdapter.inc.php on line 83, referer: http://localhost/omp/index.php/heibooks/oai
`

After tracking the missing method it seems the pkp-lib submodule of the omp-stable-1_2_0 branch is missing some commits from a previous pull request.

This is the tree, which omp-stable-1_2_0 currently uses:
https://github.com/pkp/pkp-lib/commits/ad075bc5aa42a69d84174d8015437ace00f2c05e

And the pkp-lib omp-stable-1_2_0 branch is pointing to a different state:
https://github.com/pkp/pkp-lib/commits/omp-stable-1_2_0

**Comment by asmecher** [comment]
@isgrim, try applying this patch in the `lib/pkp` submodule:
https://github.com/pkp/pkp-lib/commit/bd07189b7da8e0a00df096597a0a61840ad85a0e

**Comment by isgrim** [comment]
@asmecher Thank you very much! It is now working for me.

**Comment by asmecher** [comment]
Great, thanks for confirming!
