### ISSUE TITLE
UserGroupDAO insertObject returns wrong value

### ISSUE THREAD

**Issue by crazy-weasel** [pkp/pkp-lib#1800]
Hi!

Running the upgrader for OJS3 always failed for me because of a unique key violation. (Duplicate entry '2-0-4' for key 'user_group_stage_pkey')

I tracked the error down and found that in [UserGroupDAO.inc.php:88](https://github.com/pkp/pkp-lib/blob/master/classes/security/UserGroupDAO.inc.php#L88) a second call to getInsertID is made instead of just returning $userGroup->getId() like in most of the other DAOs. (Some return nothing, and others return the object -- a bit inconsistent)

The wrong return value is then used in [UserGroupDAO.inc.php:716](https://github.com/pkp/pkp-lib/blob/master/classes/security/UserGroupDAO.inc.php#L716) to assign the group to a stage. (..and that fails.)

Greetings,
Alex

Edit:
If it is important: DB Server 10.1.9-MariaDB. Tested with MyISAM and InnoDB. But the code is faulty no matter what Serversoftware is used. (because of the other SQL Statements in updateLocaleFields between setId and return)

**Comment by asmecher** [comment]
@crazy-weasel, this appears to be the same as http://forum.pkp.sfu.ca/t/ojs-2-4-7-to-3-0-0-upgrade-problems/19114 --

I wonder whether repeated calls to `getInsertId` are causing the problem. (I haven't seen trouble here, but your DBMS is a different version than mine.)

Try changing `lib/pkp/classes/security/UserGroupDAO.inc.php` line 88 from...

    return $this->getInsertId();

...to...

    return $userGroup->getId();

...to see if that changes things?

**Comment by crazy-weasel** [comment]
@asmecher Yes, I tried changing to `return $userGroup->getId();` bevore I wrote the issue and it fixes the problem.

I debugged the calls, and the first call to getInsertId works normally. The second one returns 0. My guess is that the update-queries inside `$this->updateLocaleFields($userGroup);` modify the last InsertId-value.

Sorry that I haven't made it clear enough in my first post.

**Comment by asmecher** [comment]
@crazy-weasel, that's certainly possible, even though we're supplying the table name to the `_getInsertId` call -- if I remember correctly, different DBMSs behave differently in this regard and I have a vague recollection of either MySQL or PostgreSQL treating the "last insert ID" as a database-wide single value. I'll make the change suggested above; thanks for your help!

**Comment by asmecher** [comment]
All the above patches are equivalent, just committed to different branches. To patch your OJS 3.x installation, apply https://github.com/pkp/pkp-lib/commit/d5391b4b6dfb3adb127ad20c7a06888e2a239325 in the lib/pkp subdirectory.
