### ISSUE TITLE
Display article references metadata on article details page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1808]
See: http://forum.pkp.sfu.ca/t/ojs3-article-citations-problem-on-update-from-2-4-8-version/19729

Alec, I think we'll need to talk about what the status is of the citations management plugin, and how references ought to be displayed on the article details page. At the moment, as far as I see, there's just a textarea in the article metadata, which would lead to low predictability in displaying the output. 

But however we decide to move forward, the current template just doesn't display anything.

**Comment by asmecher** [comment]
OJS 2.x supported a plaintext field for copy/paste -- good -- which used to feed a whole subsystem called the Citation Assistant, which has proven unwieldy and hard to maintain and hasn't been supported for some time. Overall I think the XML conversion toolset will provide a better long term approach to handling citations. I suggest we do our best to support the plaintext field as an ongoing data source -- potentially with a couple of plugins to feed entries there through the Google and CrossRef citation parse/lookup services -- and as a higher-end but lesser-used option, support pulling them in a much richer way from JATS XML uploaded as galley files. (The Lens Reader probably already has support for presenting these, I haven't checked.) Make sense?

**Comment by NateWr** [comment]
> Make sense?

Yes, though I don't have any experience with the Google/CrossRef services. Is there an example of how existing citations are stored in the database that I might use for exploring how to display this on the frontend? Or is it really just a non-HTML text dump?

**Comment by asmecher** [comment]
It's really just a non-HTML text dump. I could imagine having a couple of generic plugins (e.g. one for Google and one for CrossRef citation lookups each) that watch for this and drop in links to those external services to look up the references. Then for any articles that have richer content -- thinking JATS XML -- we would lean instead on tools like Lens Reader to present references.

**Comment by ajnyga** [comment]
This is connected to the issue: http://forum.pkp.sfu.ca/t/improve-google-scholar-exposure-with-reference-metatags/21693

**Comment by vedranvucic** [comment]
I think that references should be visible on details page.  I think that link of references to other services i.e Google  should be optional since we cannot depend on those services and their company policies.  Thus, simple placement of references written in text field as you described should be sufficient. All the rest can depend on other plugin(s).

**Comment by NateWr** [comment]
Simple commit to add references to the frontend display of articles and monographs.

PRs:
https://github.com/pkp/ojs/pull/1215
https://github.com/pkp/omp/pull/386

No `pkp-lib` PR. Tests running.

**Comment by NateWr** [comment]
OMP test passed. OJS tests timed out (https://travis-ci.org/pkp/ojs/builds/194897930).

I've rebased but I think this is good to go. @bozana can you code review and merge?

**Comment by bozana** [comment]
Everything fine and merged...
