### ISSUE TITLE
[OJS][OMP] undefined constant in site settings

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1810]
`PHP Notice:  Use of undefined constant bool - assumed 'bool' in .../lib/pkp/classes/admin/form/PKPSiteSettingsForm.inc.php on line 134` (also 135, 136)

This is against `HEAD`, but it looks to have been there since 4aaf1f29245e7a5a29810409045f91d2f7f527ef.

**Comment by asmecher** [comment]
Thanks, @crism!
