### ISSUE TITLE
Allow any participants to privately accept/refuse/withdraw from participation

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1814]
Participants should be able to privately withdraw from participation on any submission. They may have a conflict of interest, or may be busy, or there may be some other sort of issue. Their decision should not be made available to other participants (except the submission's assigned editor). This action should be private, with notification only going to the assigned editor, and any action history only provided to the assigned editor.

**Comment by asmecher** [comment]
Again, curious about @willinsky's take.

**Comment by willinsky** [comment]
Trying to imagine use cases. Maybe you have one but here's my thinking: If an author withdraws from a multi-author paper in process, that participation should not be rendered invisible but marked by something like "withdrawn" available to the other authors. If a reviewer withdraws that would only be available to assigned editor. If a copyeditor withdraws after having worked on a paper, that participation is part of the record and can end or switch to someone else without explanation but their decision to withdraw will be there and would be better handled as a "withdrawn" than simply disappearing.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
