### ISSUE TITLE
Move metadata (DC/GS) meta tags into HTML head

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1815]

**Comment by asmecher** [comment]
See http://forum.pkp.sfu.ca/t/ojs3-dc-highwire-metadata-not-included-in-the-html-header/19982. @NateWr, an easy solution would be to add something like a Smarty `$additionalHeaders` variable into `lib/pkp/templates/frontend/components/header.tpl`, then allow calling templates to populate it before including the header. Objections to that? Alternately, we could do something similar to what you've done with JS and CSS and allow PHP-side injection.

**Comment by asmecher** [comment]
@bozana, could you have a look at https://github.com/pkp/ojs/pull/1024?

**Comment by Vitaliy-1** [comment]
Many thanks for the update! All seems to work fine. All Metadata is displaying in the head now.

**Comment by asmecher** [comment]
https://github.com/pkp/ojs/pull/1024 need sporting over to OMP master.

**Comment by bozana** [comment]
Isn't this issue finished for OJS? -- because of the milestone...

**Comment by asmecher** [comment]
Yes, it's finished for OJS (the milestone is currently OMP 3.1).

**Comment by bozana** [comment]
Ah, sorry, I saw wrong... :-\

**Comment by asmecher** [comment]
Pull requests:

- https://github.com/pkp/pkp-lib/pull/2318
- https://github.com/pkp/omp/pull/395

@bozana, could you have a look at this? The pkp-lib change adds the ability of hook registrants to specify priority in calling hooks -- this was necessary because we need to ensure that e.g. the DC and GS metadata tag plugins have a chance to inject the metadata before the PDF viewer plugin displays the file.

**Comment by asmecher** [comment]
(This is a pretty big change to merge right before the release, so one option would be to release before merging and then merge it after. Still considering.)

**Comment by bozana** [comment]
@asmecher, I went through everything roughly. If we would have some more time I could also test it...

**Comment by asmecher** [comment]
Thanks, @bozana. On balance I think this is too risky to merge in so close to the release, and since we haven't been able to get confirmation from GS about whether OMP content is getting indexed anyway, there's little upside at the moment. I'll go through the rest of the review comments and fix, but leave unmerged until after OMP 3.1 is released.

**Comment by asmecher** [comment]
Fixed and merged into OMP `master` -- thanks, @bozana. @NateWr, [this comment](https://github.com/pkp/omp/pull/395#discussion_r103530196) could still use a review -- not sure if it got lost in the noise.
