### ISSUE TITLE
Implement subscription support

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1816]

**Comment by asmecher** [comment]
Works in progress:

- https://github.com/pkp/ojs/compare/master...asmecher:i1816-fix2?expand=1
- https://github.com/pkp/pkp-lib/compare/master...asmecher:i1816-fix2?expand=1

**Comment by asmecher** [comment]
FIXMEs:
- [ ] `nonExpiring` removed from subscription type form; collapse into null value for `duration` and remove?

**Comment by asmecher** [comment]
Merged administration grids into master. Ignore anything above.

FIXMEs remaining:
- [ ] Reload the sidebar to include/exclude subscription tools on change of `publishingMode` setting (after JS merge to use its messaging bus?)
- [ ] Audit subscription policy form settings
- [ ] Filter form on individual (& presumably institutional) subscriptions grid

**Comment by NateWr** [comment]
@asmecher It looks like a recent change might have caused issues for the tests in OMP. You made `ArticleSearch::formatResults()` no longer a static function here: https://github.com/pkp/ojs/commit/62ba59bf2e25095d98c0437bfb4c34ee8d76f93b#diff-401946acaf57017870300415e4440bdbR235

In [OMP tests for a PR of mine](https://travis-ci.org/pkp/omp/jobs/264340114), I'm getting the following error:

```
Fatal error: Cannot make non static method SubmissionSearch::formatResults() static in class MonographSearch in /home/travis/build/pkp/omp/classes/search/MonographSearch.inc.php on line 21
```

Should I update `MonographSearch::formatResults` to not be static, or do you want to take a look at it?

**Comment by asmecher** [comment]
Hmm, I thought I ported that over -- maybe it's in my local repo. I'll take a look.

**Comment by asmecher** [comment]
This should be fixed now, thanks!

**Comment by NateWr** [comment]
:+1:

**Comment by asmecher** [comment]
See also https://forum.pkp.sfu.ca/t/ojs-2-4-8-1-paypal-payments-ipn-problems/32446/13 regarding which IPN variable to use to verify the amount matches the expected amount.

**Comment by asmecher** [comment]
FIXMEs remaining -- all outstanding items above are summarized here:
- [ ] Audit subscription policy form settings
- [ ] Filter form on individual (& presumably institutional) subscriptions grid
- [ ] Test/fix payments in OMP master
- [ ] Make sure plugin-based composer dependencies (such as for PayPal plugin) are built into packages.
- [ ] Check IPN amounts when taxes added per https://forum.pkp.sfu.ca/t/ojs-2-4-8-1-paypal-payments-ipn-problems/32446

**Comment by ajnyga** [comment]
A general question: are you still going to support payment plugins like in OJS2?

**Comment by asmecher** [comment]
@ajnyga, yup! I've done some preliminary work with [Omnipay](https://github.com/thephpleague/omnipay), which will be used as part of the OJS plugin to support Paypal payment handling. That'll keep the Paypal plugin leaner than it used to be, and make it a more general template for other tools that might ideally use other Omnipay gateways. (The Omnipay toolkit isn't standardized/generalized enough to let us simply support all of its integrations at a go, unfortunately.)

**Comment by ajnyga** [comment]
Are you still going to have the "manual payment" option as well?

I am asking because I made a payment plugin for OJS2 that was designed for societies. Basically it enabled society members to pay their subscibtion with a code they received from the society after paying their membership fee. I used the manual payment plugin as a basis when I built that plugin and was hoping to do that for OJS3. But I will wait and see how the payment plugins work and figure it out after that.

**Comment by asmecher** [comment]
Yes, I think those two options will still exist as plugins, much the same way as in OJS 2.x. The biggest change is that the PayPal plugin will use Omnipay and thus will inclue less of its own code, relying instead on the 3rd-party library.

**Comment by asmecher** [comment]
@NateWr, could you tinker with these templates?

- templates/user/subscriptions.tpl
- templates/frontend/pages/subscriptions.tpl
- templates/user/userIndividualSubscriptionForm.tpl

**Comment by NateWr** [comment]
Worked on this a bunch today. Still some more to do, but if the tests are ok then go ahead and merge and I'll start from `master` on Monday.

PR:
https://github.com/pkp/ojs/pull/1582

Todo:
- Style restricted galley download links appropriately.
- Test restricted galley download links in different circumstances.
- Update the Bootstrap3 theme with the new templates.

Bugs/Questions/Comments:
- In institutional subscriptions, an error is thrown if `domain` is empty, though the code looks like it wants to allow it to be empty.
- "Open Access Options for Subscription Journals" - tried changing this from Disabled to something else. But after saving and reloading it's back to Disabled.
	- The checkbox below it is disabled with no info on how to enable it. Will it be enabled when Disabled is set to something else?
- There's a checkbox for "Author Self-Archiving Policy" that is disabled. How can I enable it?
- When creating a new subscription type, the description does not get saved.
- I saved IP addresses in an institutional subscription. When I reloaded the form, the IP addresses were printed as `Array`.
- When creating an institutional subscription, I checked "Subscriptions require membership information". On saving the form, I get an error: "Please use the checkbox provided". Unchecking that checkbox allowed me to submit the form.
- The descriptions for Delayed Open Access Policy and Author Self-Archiving Policy mention appearing in About the Journal. I don't think this is correct, but not sure where it appears.
- Why do we select a user when creating institutional subscriptions? I was under the impression it would work for logged-out users based on IP.
- After doing a manual payment, clicking on the "send notification of payment" link led to a fatal error: `PHP Fatal error:  Uncaught Error: Call to undefined method OJSPaymentManager::getById() in /var/www/html/ojs/plugins/paymethod/manual/ManualPaymentPlugin.inc.php:105`
- Renew payment button led to fatal error: `PHP Fatal error:  Uncaught Error: Class 'Form' not found in /var/www/html/ojs/plugins/paymethod/manual/ManualPaymentPlugin.inc.php:78`
- Couldn't complete institutional subscription with manual payment: `PHP Fatal error:  Uncaught Error: Call to undefined method InstitutionalSubscriptionDAO::insertSubscription() in /var/www/html/ojs/classes/subscription/form/UserInstitutionalSubscriptionForm.inc.php:196`

I'll pick it up again on Monday with the remaining TODOs and anything else that pops up. :+1:

**Comment by asmecher** [comment]
Yow, thanks, @NateWr. I'll work through some of these. I have yet to finish IP handling and some of the institutional subscription forms, which I'll do today, along with single-issue and article purchases. More to come.

**Comment by asmecher** [comment]
@NateWr, how do you feel about adding $amount beside the article and issue galleys when they're for sale? I find it jarring to get hauled off to PayPal before I even know what a thing costs.

**Comment by NateWr** [comment]
> @NateWr, how do you feel about adding $amount beside the article and issue galleys when they're for sale? I find it jarring to get hauled off to PayPal before I even know what a thing costs.

:+1:

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/1591

Found a couple more issues:

- Admin/Journal Manager can download issue and article galleys, but `$hasAccess` is false in IssueHandler. Seems to be that `IssueAction::subscribedUser` is returning a different result there then it's returning when called in `ArticleHandler`.
- Made a manual payment. It is described as "awaiting payment", but when clicking edit on the payment, the "Active" option is selected.
