### ISSUE TITLE
Licensing link

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1818]
Could we add the licensing link to the article-level page?

It is currently displayed in OMP under the copyright information:
http://monographs.lib.sfu.ca/index.php/sfulibrary/catalog/book/1

Something similar would work for OJS 3.

**Comment by stranack** [comment]
Could we also consider replacing the text ("Licensing") with the appropriate Creative Commons text and/or image?

https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en

**Comment by NateWr** [comment]
We have a small number of CC licenses which we list explicitely:

https://github.com/pkp/pkp-lib/blob/master/locale/en_US/submission.xml#L616-L627

**Comment by NateWr** [comment]
(Sorry, submitted early.)

I believe if the license matches one of our known license URLs, we display the CC logo, otherwise we use the generic "License" term.

This list could obviously be expanded, or perhaps we can just display the CC logo with any license URL that includes `creativecommons.org`. That said, this may be one place where we can educate users with what we think is good practice. Do you have a list of CC licenses we want to encourage or that we think should be included?

**Comment by bozana** [comment]
maybe just a note to think about if/when changing this: it is recommended to use the machine readable licenses...

**Comment by NateWr** [comment]
I'm going to defer this until we have a list of additional licenses we'd like to support.

**Comment by mtub** [comment]
The recent PR (#3709) might be an easy solution for the legacy upgrade problems (#3707), but I fear that the list of licenses might get a little long if we were to also apply this to a license selector menu in settings. In terms of educating users I'd prefer a shorter list of recommended and up-to-date licenses (maybe just CC BY 4.0, CC BY-SA 4.0), but at least for legacy content we also need to display a proper license link (machine-readable, linking to the CC page, displaying the CC logo...). I suggest to only include CC licenses.

This still leaves us with the problem that for many journals this will still not work - all journals using a CC license from another jurisdiction. They will need a means to enter the name and URL of their license and also enter this information in all UI languages. Please not that we cannot assume the license jurisdiction from the locale being used, those are completely independent.

**Comment by NateWr** [comment]
If I understand correctly, the PR just adds to the list of licenses to select to automatically complete the URL. But editors can still enter their own license details. Does that address your concern @mtub?

**Comment by NateWr** [comment]
I have pulled the PR (#3709) into work I'm doing on #3594. It includes a few more badges. I'm going to go ahead and close this, but if anyone has additional badges/licenses to contribute, I'm happy to merge those in any time.
