### ISSUE TITLE
Title parameter in multiple locale.xml files is $param instead of $title

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1820]
In OJS 2.4 dev:

See: https://github.com/pkp/ojs/blob/695a4d47fabfaf31f6fc7cea253e2f9a0724b06b/locale/ja_JP/locale.xml#L807-L868
vs: https://github.com/pkp/ojs/blob/e7e1941b5f1eb4feb332f417478278f1917285b1/locale/en_US/locale.xml#L1165-L1182

Reported: http://forum.pkp.sfu.ca/t/how-can-i-use-last-name-of-author-in-the-mail-template/19034/14?u=ctgraham

**Comment by ctgraham** [comment]
Looks like this was introduced with:
https://github.com/pkp/ojs/commit/faa31d7fa99c27277483220e037b4f2fafc92f30
and affects multiple locales.

**Comment by ctgraham** [comment]
A fix is probably a candidate for forward porting to master:
https://github.com/pkp/ojs/blob/0168e1726510d0fe6038899f7fad2551be18c612/locale/ja_JP/locale.xml#L771-L827

**Comment by asmecher** [comment]
Ported forward to `master` and `ojs-stable-3_0_0` just for consistency (likewise: grep/sed, with visual sanity check)
