### ISSUE TITLE
Error during registration of a new publisher in OMP

### ISSUE THREAD

**Issue by amandasramalho** [pkp/pkp-lib#1824]
Some new publisher registration area sessions appears only as "Loading". And when I click "next", accuses page error.
![image](https://cloud.githubusercontent.com/assets/5446933/18594250/5d78d1b6-7c15-11e6-8d19-166d0c21944a.png)
![image](https://cloud.githubusercontent.com/assets/5446933/18594274/7bf056dc-7c15-11e6-8200-b5bab35dedb6.png)

**Comment by amandasramalho** [comment]
[omp-error.zip](https://github.com/pkp/pkp-lib/files/477328/omp-error.zip)

**Comment by asmecher** [comment]
Thanks for the details, @amandasramalho. If you're using a developer toolbar like Firebug for Firefox, take a look at the sub-requests corresponding to the endlessly-loading spinners. I think you'll find that there is an error message of some kind included in the JSON response, which is causing the Javascript front-end to stop working, which leads to the later quirks you describe. The contents of those error messages would help in debugging.

**Comment by amandasramalho** [comment]
@asmecher would it be this?
![error_publisher](https://cloud.githubusercontent.com/assets/5446933/18597765/ce6ce6d6-7c25-11e6-81d3-717ec8d9d875.png)

**Comment by asmecher** [comment]
Ah -- I think you're running into https://github.com/pkp/pkp-lib/issues/1795.
