### ISSUE TITLE
OJS3 upgrade issue: unique key violation  for key 'article_search_keyword_text')

### ISSUE THREAD

**Issue by kafonso** [pkp/pkp-lib#1829]
Hi,
Running the upgrader for OJS3 always failed for me because of a unique key violation. (Duplicate entry 'ascertained' for key 'article_search_keyword_text')
best regards
Carlos M Afonso

**Comment by asmecher** [comment]
@kafonso, if you're using the command-line upgrade tool, can you post its full output?
If you're using the web-based installer, can you try the command-line tool?
Note that you'll need to restore from backup before trying the upgrade again.

**Comment by espertoweb** [comment]
hi did you solve the issue? I'm having the same one.

**Comment by NateWr** [comment]
@espertoweb our [support forum](https://forum.pkp.sfu.ca/c/questions/5) is the best place to ask for help.
