### ISSUE TITLE
PHP Warning: end() expects parameter 1 to be array in search.tpl

### ISSUE THREAD

**Issue by ania-appb** [pkp/pkp-lib#1834]
We spotted this error looking through our php errors log when testing our new installation of OJS 3.0 (this was not an upgrade):
Error:
PHP Warning: end() expects parameter 1 to be array, null given in /home/acta/ojs/ojs-3.0.0/cache/t_compile/c18f74cb7ec86d000ca85f6baec01c420e4e3321^%%61^61E^61E71072%%search.tpl.php on line 53
-----------------------------------------------------
Comment:

Actually 'yaerEnd' is used in:
ojs-3.0.0/templates/frontend/pages/search.tpl

while 'yearEnd' appears in
ojs-3.0.0/pages/search/SearchHandler.inc.php

Do you have any idea how  this can be fixed?

Anna

**Comment by bozana** [comment]
Hmm... This point to a cache file. Could you maybe try to clear all the .php files in cache/ and cache/t_compile/ ?

**Comment by asmecher** [comment]
@ania-appb, I've corrected the typo `yaerEnd` by replacing it with `yearEnd` in two places -- see the attached commits. Can you pull these changes into your installation and see if it resolves the issue?

**Comment by asmecher** [comment]
To clarify, you'll have to apply both:

- https://github.com/pkp/ojs/commit/cd7dc4de41be7cc909f863ef16ec3f42e3656e9a
- https://github.com/pkp/ojs/commit/3fe0cd65f8bffc140cb8c66557c09b3bafc039c2

**Comment by ania-appb** [comment]
Thank you, I pulled all these changes into our installation. I'll let you know if I see any problems.
