### ISSUE TITLE
OJS3 installation silently fails when php5-mysql is not installed

### ISSUE THREAD

**Issue by fmux** [pkp/pkp-lib#1835]
I am currently attempting to install OJS 3.0.0 on a Debian jessie machine with Apache 2.2.22, PHP 5.4.45 and PostgreSQL 9.1.22. Following the steps in the installation guide, after extracting the software, setting up the directories and adapting the permissions, I tried to open OJS in a browser, which yielded only an empty page with a HTTP status code 500. There was no information at all in the server logs, even after enabling debug output in all the relevant places (Apache config, php.ini, OJS's config.inc.php).

The problem was finally solved by edititing config.inc.php and changing 
> driver = mysql

to
> driver = postgresql

Alternatively, installing the php5-mysql package also fixed the problem.

It seems that the installation cannot proceed if the driver mentioned in config.inc.php is not installed (even when one doesn't want to use it at all and instead is planning to change it during installation). Moreover, having no debug output about this at all makes this problem very hard to diagnose.

I think that OJS3 should either
1. mention the MySQL module for PHP as a requirement in the installation guide,
2. amend the installation guide to say that one should change this setting in config.inc.php manually prior to starting the installation via browser, or
3. (and best) make the PHP script not fail in case the respective driver is not installed.

**Comment by asmecher** [comment]
I suspect this is a side-effect of https://github.com/pkp/pkp-lib/issues/1803 (which has already been fixed in github). Can you verify whether that patch changes the behavior of the installation tool? (It could also be useful to turn on `show_stacktrace` and `display_errors` in `config.inc.php`.)

**Comment by fmux** [comment]
Indeed, the current version from GitHub does not exhibit this behaviour any more. As I wrote above, turning on debug output (including `show_stacktrace` and `display_errors`) did not yield anything, so something might still be off with the logging. I'm nevertheless closing this issue as fixed.

Thank you for your help!

**Comment by asmecher** [comment]
Great, thanks for verifying, @fmux!
