### ISSUE TITLE
Proxy settings not used when verifying CAPTCHA

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#1837]
With OJS 3.0 the verification of a user's response to reCAPTCHA fails if behind a proxy, even if it has been declared in the configuration file (`http_host|port`).

The proxy have to be added explicitly to the HTTP context options around line 58 of [FormValidatorReCaptcha.inc.php](https://github.com/pkp/pkp-lib/blob/ojs-stable-3_0_0/classes/form/validation/FormValidatorReCaptcha.inc.php#L60) :

``` php
                $requestOptions = array(
                        'http' => array(
                                ...
                                'proxy' => 'tcp://HOST:PORT',
                                'request_fulluri' => true,
```

**Comment by asmecher** [comment]
@ptrckb, at a glance, I'm not sure the recaptcha library we're using supports the `proxy` option you've described. Is this documented somewhere?

**Comment by asmecher** [comment]
@ptrckb, this has been re-filed over at https://github.com/pkp/pkp-lib/issues/2367 with a pull request. It sounds like you're in a proxy environment. Are you in a position to test that pull request? (Closing this issue in favour of that one.)
