### ISSUE TITLE
Metrics migration from 2.4.x to 3.0

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1840]
The migration for the DB table metrics is not considered:
-- Supp files ids (in the column "assoc_id") should be adjusted - in 3.0 there is the setting_name "old-supp-id" (in submission_file_settings table). What to do with the supp file ids in the metrics table, that do not exist as "old-supp-id"? -- This is a case in the PKP OJS 3.0 demo installation.
-- The ASSOC_TYPE_ constants has to be adjusted for this table - only for galleys i.e. representations has been already considered/adjusted, s. dbscripts/xml/upgrade/3.0.0_change_assoc_type_metrics.xml.
-- The 4 new columns (assoc_object_type, assoc_object_id, pkp_section_id and representation_id) should be filled according to the function https://github.com/pkp/ojs/blob/master/classes/statistics/MetricsDAO.inc.php#L45
-- Article Galleys are not tracked any more in 3.0 (instead the files are), s. e.g. UsageStatsLoader::getExpectedPageAndOp. But they will remain in the table as they are i.e. with the ASSOC_TYPE_REPRESENTATION

**Comment by bozana** [comment]
Here the ASSOC_TYPE_ constants in 2.4.x and 3.0:  
decimal 2.4.x = hexadecimal 2.4.x  type 2.4.x  --> type 3.x  decimal 3.x = hexadecimal 3.x  
256 = 100  journal  -->  the same
257 = 101  article  -->  submission  1048585 = 0x0100009
(additionally in 3.x:  published submission  528 = 210)
259 = 103  issue and section  -->  issue the same, section  530 = 212
260 = 104  galley  -->  representation  521 = 209
261 = 105  issue galley  -->  the same
262 = 106  supp file  -->  submission file  515 = 203

**Comment by bozana** [comment]
To adjust ASSOC_TYPE_... (s. https://github.com/pkp/pkp-lib/issues/1840#issuecomment-248867390):
for articles:
UPDATE metrics SET assoc_type = 1048585 WHERE assoc_type = 257
for supp files:
UPDATE metrics SET assoc_type = 515 WHERE assoc_type = 262

**Comment by bozana** [comment]
To adjust supp file ids:
`UPDATE metrics m, submission_file_settings sfs SET m.assoc_id = sfs.file_id WHERE m.assoc_type = 515 AND sfs.setting_name = 'old-supp-id' AND sfs.setting_value = m.assoc_id`

**Comment by bozana** [comment]
To fill the new columns:
insert issue id and section id for articles, article galleys and supp files -- they all have submission_id in the table:
`UPDATE metrics m, submissions s SET m.pkp_section_id = s.section_id WHERE m.submission_id IS NOT NULL AND s.submission_id = m.submission_id`
`UPDATE metrics m, published_submissions p SET m.assoc_object_type = 259, m.assoc_object_id = p.issue_id WHERE m.submission_id IS NOT NULL AND p.submission_id = m.submission_id`

insert issue id for issue galleys:
`UPDATE metrics m, issue_galleys ig SET m.assoc_object_type = 259, m.assoc_object_id = ig.issue_id WHERE m.assoc_type = 261 AND ig.issue_id = m.assoc_id`

insert representation id for article galleys and supp files:
`UPDATE metrics SET representation_id = assoc_id WHERE assoc_type = 521`
`UPDATE metrics m, submission_files sf, submission_file_settings sfs SET m.representation_id = sf.assoc_id WHERE m.assoc_type = 515 AND sfs.setting_name = 'old-supp-id' AND sfs.setting_value = m.assoc_id sf.assoc_type = 521`

**Comment by bozana** [comment]
@asmecher and @ctgraham, could you please read the metrics upgrade 'concept' above if it sounds OK for you, or if I missed something, or...
@ctgraham, would it be possible for you to test an upgrade with this patch: https://github.com/bozana/ojs/commit/55e84408b94abe3b4b976f08c4261c42b67b0e92 ? -- I tested it with already upgraded PKP OJS 3.0 demo and it worked well. I will also try to find a 2.4.x installation to test it.
@asmecher, does the order of those 2.4.0 - 2.4.2 scripts looks reasonable to you? -- because this I haven't tested. Also, what do you think we should do with the supp file ids in the metrics table, that do not exist as "old-supp-id"? -- This is a case I found in the PKP OJS 3.0 demo installation :-O
After you have taken a look and confirmed, I would ask the user from the forum with 2.4.2 version to test it, if possible, and make a PR.
THANKS!!!

**Comment by asmecher** [comment]
The `old-supp-id` is tracked only in order to keep serving documents at old OJS2-style URLs within OJS3 -- see ArticleHandler::downloadSuppFile. Do you mean that an upgraded supp file didn't have an `old-supp-id` entry?

**Comment by bozana** [comment]
There is an entry in the metrics table with assoc_type = 262 and assoc_id = 1. This means supp file with id 1. The table metrics was not considered at the upgrade i.e. it still contains old supp file ids. When I however look in the migrated submission_file_settings table I do not find an entry with old-supp-id = 1.

**Comment by ctgraham** [comment]
I'm still catching up on the scope of changes to the 3.x metrics (and realizing some of the missing pieces from 2.x dev, such as the refactoring of the COUNTER reports).

I have read through your description, and it seems sound.

I tested an upgrade from one of our journals from 2.4.8-1 to 3.0 with the patch from fix1840, and the update statements performed as expected.

I see a lot of re-learning and re-working in my future in order to get COUNTER and SUSHI-Lite into 3.x.

**Comment by bozana** [comment]
Thanks a lot @ctgraham! I will then make a PR...

**Comment by bozana** [comment]
PR:
master: https://github.com/pkp/ojs/pull/1033
@asmecher, could you take a look?

**Comment by bozana** [comment]
PR ojs-stable-3_0_0: https://github.com/pkp/ojs/pull/1052

**Comment by bozana** [comment]
Everything merged, thus closing...
