### ISSUE TITLE
Index issue metadata and galleys

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1842]
Add issue metadata (description, volume, number, etc.) and issue galleys to the OJS index.

**Comment by gemusehandler** [comment]
Provide an option to include 'issue editors' in these, and a ISBN. Some serials are somewhere in between journals and books (bookazines) and do use isbn's to sell issues in hard copy on-line.

**Comment by NateWr** [comment]
Closing for lack of interest.
