### ISSUE TITLE
Extend Piwik support to include embeddable graphs/data

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1845]
From GDoc discussion:

>  ...but thinking it could display relevant piwik usage information on various journal pages.

http://developer.piwik.org/api-reference/reporting-api-metadata#static-image-graphs

**Comment by ctgraham** [comment]
@asmecher it looks like this issue is resolved, is that accurate?

**Comment by asmecher** [comment]
@ctgraham, no, I think there was a compatibility update for 3.3 shoehorned into this issue but the original feature request hasn't been implemented yet.

**Comment by ctgraham** [comment]
@Tyl13 , this could be an interesting issue to look at, with interest to the ULS and to the broader PKP community.  Note that piwik is now know as Matomo.

**Comment by Tyl13** [comment]
What specific usage information would want to be shown and on which pages? Any additional information would be helpful. Thanks in advance.

**Comment by ctgraham** [comment]
Through Custom Blocks and through Custom Pages, we already support embedding Matomo widgets and images in the global sidebar or in a dedicated page.  I think the value-add here would come from the ability to bind Matomo widgets/images against a dynamic URL: e.g.: showing visitors for a specific page, on that specific page.  Based on a quick read-through, I'm not confident the Matomo API supports this.

Alternately, the resolution here might actually be just documentation on how to use the widget and images in Custom Blocks and Custom Pages.

**Comment by Tyl13** [comment]
As @ctgraham said, the API does not support binding static image graphs to specific pages. While they do have an API to get useful information about specific page URLs, they do not come built with graphing capabilities. The metadata seems like it can only return information about the site as a whole. Widgets that can be embedded on Custom Pages and Custom Blocks do allow showing information for specific pages. 

It may be possible to use a Custom Block to dynamically get visits for the current URL. That may require this or another plugin to be able to access the generic URL on the Custom Block, and replace it with the current URL.

**Comment by NateWr** [comment]
Sounds like some nice ideas here, but no concrete proposals. I'm going to close this for now. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
