### ISSUE TITLE
Ensure closed registrations works properly

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1847]
Reports that users can register even if the option to only allow Journal Managers to register users has been checked.

http://forum.pkp.sfu.ca/t/registering-users-with-ojs-3-0/19589

Key points:
- List of journals shows Register link
- Unregistered users can complete registration form when user registration is disabled

**Comment by NateWr** [comment]
I was unable to reproduce this.

http://forum.pkp.sfu.ca/t/registering-users-with-ojs-3-0/19589/4

**Comment by NateWr** [comment]
It looks like this is an issue with the `registerFormContexts.tpl` file, which only appears on the site-wide registration form. It doesn't check if registration has been disabled for each context.

https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/registrationFormContexts.tpl

**Comment by asmecher** [comment]
@NateWr, related: https://github.com/pkp/pkp-lib/issues/1892#issuecomment-257554502

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/2019
https://github.com/pkp/ojs/pull/1110
https://github.com/pkp/omp/pull/362

These PRs:
- Pass a `$contexts` variable to every template which only includes enabled contexts open for registration.
- Set the `$disableUserReg` flag in site-wide context when all contexts disable registration, so that registration links are hidden.
- Show an error message if the user attempts to access site-wide registration page when no contexts allow registration.
- Only show role selection in site-wide registration for contexts that haven't disabled registration.
- Only show role selection in user profile for contexts that haven't disabled registration.

Although OMP doesn't have a site-wide context, I thought I'd add the bit of connecting code required anyway in case we add such a context later.

**Comment by asmecher** [comment]
@NateWr, is this one ready to be assigned to someone for review?

**Comment by NateWr** [comment]
Ooh, tests passed first try! @asmecher yep, ready for review.

@bozana, you seem to be getting lots done these days so I'll assign to you, but no worries if you're too busy.

**Comment by bozana** [comment]
No problem, I'll do... :-)

**Comment by bozana** [comment]
@NateWr, everything fine, except, that I do not understand this last point: "Only show role selection in user profile for contexts that haven't disabled registration". How is this supposed to behave? -- because I see no difference when on a users profile > roles page... 
Also there is "+ Register with other journals"/"+ Hide other journals" on the users profile > roles page, but I cannot see there anything -- no journals -- it is empty -- maybe it is my browser issue?

**Comment by bozana** [comment]
I merged this PR, but you could still see/explain me what is with the last point.... Should this be cherry-picked or closed? :-)

**Comment by asmecher** [comment]
> @bozana, you seem to be getting lots done these days so I'll assign to you, but no worries if you're too busy.

Way to punish good behavior!

**Comment by bozana** [comment]
I don't see/feel it that way, so no worries... :-)

**Comment by NateWr** [comment]
> @NateWr, everything fine, except, that I do not understand this last point: "Only show role selection in user profile for contexts that haven't disabled registration". How is this supposed to behave? -- because I see no difference when on a users profile > roles page...
> Also there is "+ Register with other journals"/"+ Hide other journals" on the users profile > roles page, but I cannot see there anything -- no journals -- it is empty -- maybe it is my browser issue?

The role selection seems to show properly when in the site-wide context (ie - it only shows role selection for journals which allow user registrations). But when on a specific journal, other journals are supposed to be hidden in the "other journals" UI control, but none seem to be getting shown.

I'm not sure if this was caused by this change, but I've filed a new issue for it. #2039

I'm thinking this shouldn't be cherry-picked since has the potential to cause some breakage. Closing.
