### ISSUE TITLE
StaticPages Plugin doesn't call "PkpHandler::setupTemplate"

### ISSUE THREAD

**Issue by crazy-weasel** [pkp/pkp-lib#1860]
Hi!

The StaticPages-Plugin doesn't call setupTemplate when displaying a page. That's a problem, because the base implementation of this method assigns the template-variable "userRoles".

In the provided bootstrap3-theme (and any other theme using userRoles without a cast to array) this is a problem resulting in a failed call to array_intersect. Additionaly, static pages will look differently when some parts are only shown to some user-roles. (because there are no roles on static pages)

Proposed quick fix: add a call to self::setupTemplate($request); in StaticPagesHandler::view

Greetings,
Alex

**Comment by asmecher** [comment]
Thanks, @crazy-weasel, that makes sense. Mind sending in a PR and linking it to this issue? Then I'll take care of cherry-picking it around to the various branches.

**Comment by crazy-weasel** [comment]
Done @asmecher :)

Well.. I guess the first PR was made to the wrong repository.. please ignore it! (My first PR)

**Comment by asmecher** [comment]
Thanks, @crazy-weasel -- better to use `$this->` rather than `self::` because this is an instance call; since it's a one-liner I just committed that change and closed the PR. Thanks for reporting & fixing!
