### ISSUE TITLE
Add tool to clean reviewer interests

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1861]
Write a tool to remove user interests that are not referenced by any user accounts. This can be useful for cleaning out the controlled vocabulary after removing spam user registrations.

**Comment by asmecher** [comment]
Related tables: `users`; `user_interests`; `controlled_vocab_entries`; `controlled_vocab_entry_settings`.

**Comment by asmecher** [comment]
@kaschioudi, I have an OMP user who would like to run this -- how much do you have left to do?

**Comment by kaschioudi** [comment]
@asmecher: I just pushed the remaining changes
https://github.com/kaschioudi/pkp-lib/commit/c2ff57ad7ba59f5d0466caa697994bdf2abc2f93
https://github.com/kaschioudi/ojs/commit/fd0076aa3362d58aba005d7880460024d2082bc5

Here's the PR for pkplib: https://github.com/pkp/pkp-lib/pull/2186

Oddly enough I am unable to create a PR for ojs (https://github.com/pkp/ojs/compare/master...kaschioudi:1861-fix?expand=1). Not sure why..

**Comment by asmecher** [comment]
It won't let you create another pull request while one is already open -- but the open one has your latest commits pushed to it, so that's OK.

**Comment by asmecher** [comment]
Merged and ported over to OMP `master` and `omp-stable-1_2_0`, thanks!
