### ISSUE TITLE
Ensure unique template files are compiled for each journal

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1862]
Compiled and cached template files are saved per-template. But if two journals are using different themes with different template output, their compiled template files will overwrite each other.

Using a unique hash for each journal's templates will fix this.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1863

**Comment by asmecher** [comment]
Changing a theme plugin (in setup) flushes the template cache, correct?

**Comment by NateWr** [comment]
Yes

**Comment by asmecher** [comment]
Thanks, Nate -- sorry it took so long to get merged!

**Comment by asmecher** [comment]
(Also cherry-picked over to `ojs-stable-3_0_0`)
