### ISSUE TITLE
Check box on the logging page of OJS 3.0

### ISSUE THREAD

**Issue by ania-appb** [pkp/pkp-lib#1867]
On the logging page of OJS 3.0 there is a checkbox: Remember my username and password.
And this check box isn’t really useful as remembering doesn’t work at all.
Perhaps it could be removed or the proper code corrected.

**Comment by asmecher** [comment]
@NateWr, assigning to you on the chance that it's probably a markup issue in the front end. If not, feel free to reassign (or have a crack anyway).

**Comment by NateWr** [comment]
@asmecher Is this maybe just a mis-phrased label? Is the functionality intended to keep the person logged in, or actually store their login details in a cookie and fill it out for them?

**Comment by asmecher** [comment]
@NateWr, I haven't tested the feature myself, but my understanding is that it should give the session cookie longer-lived characteristics.

**Comment by NateWr** [comment]
I tested and the cookie does last longer, over 30 days, if you check the box. If you don't, the cookie expires when the browser closes.

I'd recommend just re-wording it to "Keep me logged in". Sound good? Should I rename locale string key and invalidate existing translations too?

**Comment by asmecher** [comment]
@NateWr, yes, that sounds good.

@ania-appb, can you confirm that this still isn't working as expected? Can you check the resulting cookie to see what its expiry is when you use the checkbox?

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/2088
https://github.com/pkp/ojs/pull/1139

No OMP PR necessary.

**Comment by NateWr** [comment]
Tests passed. @asmecher code review?

@mtub Heads up. I removed the `user.login.rememberUsernameAndPassword` translation key in a bunch of locales.

**Comment by mtub** [comment]
Yeah, I noticed :)

**Comment by asmecher** [comment]
"Eagle Eyes" Tullney.

**Comment by asmecher** [comment]
Merged, thanks! I'll remove the test locale on the master branch in a sec.

**Comment by asmecher** [comment]
I haven't back-ported this to `ojs-stable-3_0_1` because of the translation requirements. Ready to close, @NateWr?
