### ISSUE TITLE
Make datepicker respect date formats

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1868]
In e.g. `FormHandler.js`, the datepicker is initialized with a hard-coded date format:

```
$('.datepicker').datepicker({dateFormat: 'yy-mm-dd'});
```

Some users may want to configure this differently per `config.inc.php`, e.g.:

http://forum.pkp.sfu.ca/t/ojs-3-do-not-respect-the-defined-values-from-config-inc-php/21817/3

**Comment by NateWr** [comment]
The [dateFormat](http://api.jqueryui.com/datepicker/#option-dateFormat) option effects the visual display *and* the format that's submitted. To preserve the submitted format, we'll need to [altField](http://api.jqueryui.com/datepicker/#option-altField) and [altFormat](http://api.jqueryui.com/datepicker/#option-altFormat).

**Comment by defstat** [comment]
I am on it.

**Comment by asmecher** [comment]
Assigned!

**Comment by defstat** [comment]
@asmecher The past 2 days I was trying to find out if there was a case, or an already existing central mechanism that could port php variables in the FormHandler Javascript object, using its "options" parameter (like OJS does with grids and 'features' variable of the 'options' parameter). I couldn't find any. 

So I decided to go with a general approach that includes some code changes in form/textInput.tpl and FormHandler.js. 

Tried to add the altField and altFormat as well, as @NateWr suggested. 

I have found some .datepicker initialization in other places to (other from FormHandler.js), not sure if I have to see those too. I will look at them. I added a function in PKPString that changes PHP date formats to JQuery Datepicker date formats, and registered it in PKPTemplateManager. Not sure if that is the right approach, or the right class to put that kind of a function. 

The approach described above can be found at https://github.com/defstat/pkp-lib/tree/1868-make-datepicker-respect-date-formats

**Comment by asmecher** [comment]
OK, sounds good! Could you open a pull request? That way the code review tools are available.

**Comment by NateWr** [comment]
Thanks for the PR @defstat! To help Alec keep track of all this stuff, we drop a link to the PR into the issue like this:

PR: https://github.com/pkp/pkp-lib/pull/1898

That will help him notice it and make sure it gets assigned for code review. :+1:

**Comment by defstat** [comment]
Thanks @NateWr! I will do that.

**Comment by asmecher** [comment]
Careful what you ask for, @NateWr -- this is yours to review! :)

**Comment by NateWr** [comment]
@asmecher This was buried in a PR discussion but I wanted to make sure that you saw it:

I ran into some problems when I changed the date_format_short in config:

```
date_format_short = "%d %M, %Y"
```

I noticed that this breaks the Posted column in the Announcements grid. That column calls DateGridCellProvider which uses strftime() rather than date(), and so doesn't support as many format options.

https://github.com/pkp/pkp-lib/blob/master/classes/controllers/grid/DateGridCellProvider.inc.php#L48

Should it maybe use date( $format, strtotime( $value ) ); or the DateTime object?

**Comment by NateWr** [comment]
@defstat The code in the pull requests is looking good. I'm running into display errors when I use a text representation of the month in the short date format:

```
date_format_short = "%d %M, %Y"
```

When I view a Back Issue, for example, the month comes out as `00`. Same for Announcement expiry dates. Even if I update the date and save it, the value is still coming out like that. The date does appear to be getting saved correctly in the database, so my guess is that it's getting corrupted as it gets read out and prepared for display. Can you try out this config format and see if you can track down the issue?

**Comment by defstat** [comment]
@NateWr could it be because of a general problem related to the comment you made to @asmecher ? It seems that date_format function in the template is not enough to "translate" the "%d %M, %Y" format. 
I changed a template to see if that's the case, as follows: 

```
{assign var=dateNorm value=$publishedArticle->getDatePublished()|strtotime}
assign var=dateFormatNorm value=$dateFormatShort|replace:'%':''}

{fbvElement type="text" required=true id="datePublished" value=$dateFormatNorm|date:$dateNorm translate=false label="editor.issues.published" inline=true size=$fbvStyles.size.MEDIUM class="datepicker"}
```

and it worked.

**Comment by NateWr** [comment]
Ahh @defstat, I was confusing the smarty `date_format` [approach](http://www.smarty.net/docsv2/en/language.modifier.date.format.tpl) with PHP's `date()` [formatting](http://php.net/manual/en/function.date.php). `M` in `date()` is a short month name (Oct), but `%M` in Smarty's `:date_format` is "minute as a decimal number". 

This is maddening. :)

It looks like your `dateformatPHP2JQueryDatepicker` method translates from the PHP date format. But our config settings for dates follow the Smarty syntax.

I believe the config setting `date_format_short` is used primarily in the templates. But we'll need to check whether that's the case, or whether it's used directly in PHP date format calls, in which case we might need to disambiguate these formats.

@asmecher Do you have any thoughts on this?

**Comment by asmecher** [comment]
The Smarty implementation uses `strftime`, rather than `date`. See e.g. http://andy-carter.com/blog/php-date-formats. If we stick with `strftime`, it shouldn't be necessary to convert between them, I think.

**Comment by NateWr** [comment]
I had a look at `strftime` vs `date` and I see `strftime` is more commonly used because it can provide translated month names.

@defstat, so I guess just update `dateformatPHP2JQueryDatepicker` to convert from the `strftime` format to jQuery Datepicker.

**Comment by defstat** [comment]
@NateWr the converted dateformatPHP2JQueryDatepicker is checked in. 

Reference: http://api.jqueryui.com/datepicker/#option-dateFormat and http://andy-carter.com/blog/php-date-formats

**Comment by defstat** [comment]
@NateWr I added the code for the 

https://github.com/pkp/pkp-lib/blob/master/templates/frontend/objects/announcement_full.tpl#L19
https://github.com/pkp/pkp-lib/blob/master/templates/frontend/objects/announcement_summary.tpl#L24

[https://github.com/pkp/pkp-lib/pull/1898/commits/817194a6ad2baf551edd8f45bed6c7710393d309]

About the submodule, I will try today to do that (never done that before). If I don't make it, I will ask you tomorrow if you are available.

**Comment by NateWr** [comment]
@defstat Not sure if you were able to connect with Alec about the submodule commit. Here's how it works. When the tests run for OJS or OMP, they automatically load the `pkp-lib` submodule. So when you have changes to `pkp-lib` and `ojs`, you add a special commit to `ojs` which the tests use to know which commit of `pkp-lib` to test against.

The way it works is to add a commit with a message formatted like this: `Submodule update ##<your_github_username>/<the_pkp-lib_branch_name>##`. This commit should be the most recent commit in the OJS repo.

So in your case, you'd do something like this when commiting in the OJS repo:

```
$ git add lib/pkp
$ git commit -m "Submodule update ##defstat/1868-make-datepicker-respect-date-formats##"
$ git push
```

Then when the tests run on OJS, they'll know to look at your `pkp-lib` repository in the `1868-make-datepicker-respect-date-formats` branch.

Hopefully that makes sense. Let me know if you need any further help with this.

**Comment by defstat** [comment]
@NateWr I am doing the following 
1. I have already forked the ojs repository, on which I made the changes regarding the files there. I made a branch (branch A, let's say. its name is the same as the branch in lib/pkp (1868-make-datepicker-respect-date-formats)) for that, and I had pushed the changes an made a pull request for the changes (#1082)
2. I've just committed the lib/pkp to the same defstat/ojs branch (branch A) and pushed it. 

Now the ojs #1082 pull request contains the initial commit and the Submodule update commit. 

Is that the correct approach?

**Comment by NateWr** [comment]
That looks correct @defstat. It looks like you have a conflict with the master branch though, where the PR says "This branch has conflicts that must be resolved".

In this case, you probably need to rebase your `pkp-lib` changes against the latest changes in master. To do this, undo the submodule commit in `ojs`:

`$ git reset HEAD~1`

Then you need to rebase your branch of `pkp-lib` against the latest commit on `master`:

```
$ cd lib/pkp
$ git rebase -i upstream/master
```

You may need to sort through conflicts. Then once it's rebased successfully you can force push it up to your branch, then go back and re-do the submodule commit on `ojs`:

```
$ git push --force
$ cd ../..
$ git add lib/pkp
$ git commit -m "Submodule update ##defstat/1868-make-datepicker-respect-date-formats##"
```

That's all based on my own specific workflow, so you might need to adjust some steps here and there. But that's usually how I resolve conflicts like this.

**Comment by defstat** [comment]
@NateWr thank you very much! 

hmmm, I merged the master branch into the 1868-make-datepicker-respect-date-formats :( :(... Surely not the correct thing to do! I will try to fix it!

**Comment by defstat** [comment]
@NateWr 
I did the following:
1. cd lib/pkp folder
2. checkout 1868-make-datepicker-respect-date-formats branch
3. hard reset (to erase the merge)
4. push force (to update the defstat/pkp-lib) -> now the branch has the code that had before the merge
5. checkout master 
6. updated the master branch from pkp/pkp-lib
7. checkout 1868-make-datepicker-respect-date-formats branch
8. rebase onto master
9. Resolved conflicts by using "theirs" (they were files I hadn't changed)
10. force push branch 1868-make-datepicker-respect-date-formats branch
11. cd ojs folder
12. checkout 1868-make-datepicker-respect-date-formats branch
13. add lib/pkp with comment "Submodule update ##defstat/1868-make-datepicker-respect-date-formats##"
14. commit + push
15. pull request.

https://github.com/pkp/ojs/pull/1082

unfortunately this has not fixed the can't resolve issue. Furthermore it seems that it no longer has only the 1868-make-datepicker-respect-date-formats branch's files committed  (905 files) Am I doing something wrong there? (of course I am)

**Comment by defstat** [comment]
@NateWr 

Well I have done some progress. It turns out that I hadn't updated the master branch from pkp/ojs, and rebased the initial branch of (1868-make-datepicker-respect-date-formats branch of defstat/ojs). Now, I made some changes on the master branch (.ignore files, and the main push for the merge with the original code), and now I can see those changes on the 1868-make-datepicker-respect-date-formats branch as well., and the pull request (https://github.com/pkp/ojs/pull/1082). Is that correct?

**Comment by NateWr** [comment]
Latest PRs:
https://github.com/pkp/ojs/pull/1106
https://github.com/pkp/pkp-lib/pull/1898

It looks like your `pkp-lib` PR is pulling in some commits from Bozana. Is that intentional?

Sometimes, I find it is easiest just to restart from scratch. Checkout the `master` branch, make sure it's up-to-date, then create a new branch off of that. You can then cherry-pick in just the commits you want from your other branch and be confident you've got a clean branch.

Do this for `pkp-lib` and `ojs` and hopefully that will resolve your issues. When you make new PRs, be sure to close the old ones and drop new links into this issue.

**Comment by defstat** [comment]
@NateWr No its not. It happened after the rebase of the pkp-lib branch on the master branch and resolving the conflicts... 
OK I will make the changes on a new branch. Thanks.

**Comment by defstat** [comment]
@NateWr  I think its ok now 
https://github.com/pkp/ojs/pull/1106

**Comment by NateWr** [comment]
HI @defstat, it looks like those commits from Bozana are still in the `pkp-lib` branch:

https://github.com/pkp/pkp-lib/pull/1898/commits

Are those supposed to be there?

**Comment by defstat** [comment]
@NateWr 

The pkp/pkp-lib PR is https://github.com/pkp/pkp-lib/pull/2011
The pkp/ojs PR is https://github.com/pkp/ojs/pull/1106 

I closed the https://github.com/pkp/pkp-lib/pull/1898 PR

**Comment by NateWr** [comment]
Ok, thanks! Yeah always drop a copy of the latest PRs or I lose track. :)

The `pkp-lib` PR looks good. I just made one review comment on the OJS PR, but once that's sorted you're ready to go.

Before merge, there will be a couple more things left to do:

1. Your https://github.com/pkp/ojs/pull/1106 has merge conflicts. It looks like it's just `lib/pkp` that is conflicting. Usually, that means you need to rebase the `pkp-lib` PR, then redo the submodule commit so it points to the rebased `pkp-lib` commit.

2. We'll want to make sure we have OMP covered by this as well. Are you set up with a development copy of OMP to look for any OMP-specific instances where the datepicker needs to be adjusted? There may not be any, but it would be good to check so that we don't inadvertently add any new bugs to OMP.

**Comment by bozana** [comment]
@defstat and @NateWr, just to make sure, that I understand the latest status of the issue: There are some missing changes in OJS and OMP should be considered as well, right?

**Comment by defstat** [comment]
@bozana There are three thinks (@NateWr could correct me if I am wrong):
1. missing changes in OJS
2. I must check if changes should be made to OMP (I haven't worked with OMP yet)
3. resolve ojs/PR conflicts

the current PRs are 
The pkp/pkp-lib PR is #2011
The pkp/ojs PR is pkp/ojs#1106

**Comment by bozana** [comment]
Thanks @defstat!

**Comment by defstat** [comment]
@bozana 

New PRs
OJS: https://github.com/pkp/ojs/pull/1114
pkp-lib: https://github.com/pkp/pkp-lib/pull/2026

**Comment by bozana** [comment]
Everything fine here, just if there is something to consider for OMP...

**Comment by bozana** [comment]
I've just taken a look at OMP and if I see it correctly there is currently no place that this change should be considered. The only two places that eventually could be considered are the date text input fields here: controllers/grid/catalogEntry/form/marketForm.tpl and controllers/grid/catalogEntry/form/pubDateForm.tpl. But they maybe function in a different way? -- the date format is to be defined there, in the next form select field... Thus, I would say we will leave it as it is for now and some time later we can see... if necessary...

**Comment by defstat** [comment]
@Bozana 

new PR for pkp/pkp-lib: https://github.com/pkp/pkp-lib/pull/2030
same PR for pkp/ojs: https://github.com/pkp/ojs/pull/1114

**Comment by bozana** [comment]
Everything merged, thanks @defstat, we can then close the issue...
