### ISSUE TITLE
UI plugin upgrade

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1872]
The plugin upgrade via UI is not working, s. https://github.com/pkp/pkp-lib/pull/1523#issuecomment-230398934
The PR is coming...

**Comment by bozana** [comment]
PR master: https://github.com/pkp/pkp-lib/pull/1874
@asmecher, mind taking a very quick look, i.e. can I merge it? Should this also go to ojs-stable-3_0_0?

**Comment by asmecher** [comment]
Just made a couple of comments on that PR, thanks, @bozana!

**Comment by bozana** [comment]
PR ojs-stable-3_0_0: https://github.com/pkp/pkp-lib/pull/1884
everything merged and cherry-picked, thus closing...
