### ISSUE TITLE
Display comments for editor

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1873]
The comments for editor are nowhere displayed, s. http://forum.pkp.sfu.ca/t/ojs-3-comment-for-the-editor-information-missing/21921/

**Comment by bozana** [comment]
@NateWr, @stranack, @asmecher: any idea where to display them in OJS and OMP? Else maybe for 3.0.2?

**Comment by asmecher** [comment]
This is something I've forgotten to raise during the UI/UX call for several weeks running. Deferring to 3.0.2. Definitely could use some input from Kevin and Nate on this one.

**Comment by NateWr** [comment]
A few ideas off the top of my head, not sure if they're worth much:

1. If this is something very common or that a lot of journal editors are looking at upon immediate submission, we could consider adding a link the submissions list which appears for editors (Delete | More Information | Comments for the Editor).

2. If I were an editor, I feel like my first instinct would be to look under the Metadata modal. As a dev, I don't really like mixing the public data with a private message. But it seems an intuitive place to look for "other info".

3. We could use this as an opportunity to expose our editorial notes feature. My thinking is that when a submission includes a comment for the editor, we add that as a Note, with a prefix like "Comments provided for the editor upon submission: <the message>". No one will find it in there, though, so we'd need to have some kind of notification on the Submission page which could say something like "View the comments for the editor" and which opened the Editorial History modal and then the Notes tab. So, downside is it takes quite a bit of work to do right. Upside is that we can hopefully encourage more editors to use the notes system (assuming we don't want to phase that out in favor of discussions in the long run).

**Comment by asmecher** [comment]
From an editor's perspective, I think I'd expect to see it upon entering the Submission stage as a (maybe dismissable) notification. I don't think mixing it with the scholarly metadata makes logical sense, although I agree that it was the first place I looked when considering where to put it.

**Comment by ajnyga** [comment]
Before reading this I was convinced that the comments would be available in "Pre-Review Discussions". Basically a message from the author. Is there a reason why you are not considering this option?

**Comment by asmecher** [comment]
@ajnyga, that is a good suggestion.

**Comment by ajnyga** [comment]
@asmecher and @bozana, here is a pull request I did regarding the issue: https://github.com/pkp/pkp-lib/pull/2200

Would be great to get a working solution to 3.0.2.

**Comment by NateWr** [comment]
I haven't tested this but chucking them into a discussion sounds like a great idea. :+1:

**Comment by asmecher** [comment]
@bozana, would you mind reviewing the PR?

**Comment by bozana** [comment]
@asmecher, once the comments to editor are moved to discussions, we cannot export them any more in the native import/export plugin -- because we do not know what discussion is "Comments To Editor", right? Can we then remove that element from schema?

**Comment by bozana** [comment]
New PRs:
https://github.com/pkp/pkp-lib/pull/2252
https://github.com/pkp/ojs/pull/1237

**Comment by bozana** [comment]
@asmecher -- the PRs above migrate the comments for the editor in OJS. Could you take a look? I will adopt it now for OMP as well...

**Comment by asmecher** [comment]
Merged, thanks! Just one comment, not worth holding things up.

**Comment by bozana** [comment]
This PR considers submission comments with no author assignments -- possible in OJS 3.x:
ojs master: https://github.com/pkp/ojs/pull/1242

**Comment by asmecher** [comment]
Closing -- correct, @bozana? Thanks, @ajnyga, @bozana, and everyone else who worked on this one!

**Comment by bozana** [comment]
I will port those last changes to OMP tomorrow, but the issue can stay closed...

**Comment by asmecher** [comment]
Or I can just shift it over to that milestone :) thanks!

**Comment by bozana** [comment]
everything merged, thus closing...

**Comment by ajnyga** [comment]
@bozana, this did not make the cut for 3.0.2., right?

**Comment by bozana** [comment]
It is in 3.0.2...

**Comment by reaganch** [comment]
I'm running OJS v3.1.2 but still can't see the comments to the editor in the submission page. Could you please let me know where exactly I should be seeing it?

**Comment by NateWr** [comment]
When an author adds comments to the editor during submission, these are converted into a "Discussion" and added to the Pre-Review Discussions. These can be found by opening the Submission stage in the submission's workflow and looking near the bottom. This page in the docs shows a screenshot of the section (but there are no comments to the editor in this example):

https://docs.pkp.sfu.ca/learning-ojs/en/editorial-workflow#submission-record

**Comment by reaganch** [comment]
I can confirm that when logged in as the Editor, I cannot see the comments for the editor displayed as a pre-review discussion. The pre-review discussions box is empty.

**Comment by NateWr** [comment]
I was unable to reproduce the problem as you describe it in the latest `master` version, so it is possible that it has been fixed since 3.1.2.

**Comment by reaganch** [comment]
Thanks @NateWr. Will upgrade to v3.2 and check.
