### ISSUE TITLE
Adding the link to a submission file for a reviewer in OJS 3.0

### ISSUE THREAD

**Issue by ania-appb** [pkp/pkp-lib#1875]
See on the forum: 
http://forum.pkp.sfu.ca/t/review-request-in-ojs-3-0-reviewer-doesn-t-see-the-submission-file-although/22000

The link should be added in the 1. Request panel: the reviewer has to have a possibilty to open the file before making a decision whether to make a review or not.
How could I add this link?

**Comment by ajnyga** [comment]
Hi @asmecher 

This is a suggestion to solve the above problem
https://github.com/pkp/pkp-lib/compare/master...ajnyga:fix1875?expand=1

**Comment by asmecher** [comment]
Sharp as always -- many thanks, @ajnyga!
