### ISSUE TITLE
DataCite export's "publisher" should be clarified

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1877]
Martin from DataCite suggests that the `publisher` element in the DataCite metadata should be built around the usage of citations, and should thus be the Journal Title for output from OJS.
http://forum.pkp.sfu.ca/t/ojs-2-4-8-1-need-help-with-datacite-export-plugin/22129/6?u=ctgraham

Currently, we inherit `DOIExportDom::getPublisher()` in DataciteExportDom.  This prefers the Publishing Institution for the journal over the Journal Title.
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/importexport/datacite/classes/DOIExportDom.inc.php#L549-L559

**Comment by bozana** [comment]
Thanks a lot @ctgraham! I merged it and will change this accordingly for OJS 3 and maybe cherry-pick it to ojs-stable-2_4_8 as well.

**Comment by ctgraham** [comment]
Note that Martin Fenner reports that DataCite is discussing this limitation of not have a clear way to represent the journal title in their metadata internally.  A better solution may arise from that conversation.

**Comment by bozana** [comment]
PRs:
ojs-dev-2_4: https://github.com/pkp/ojs/pull/1056
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1060
master: https://github.com/pkp/ojs/pull/1061
ojs-stable-3_0_0: https://github.com/pkp/ojs/pull/1062

**Comment by bozana** [comment]
All PRs are merged, thus this issue can be closed, right @ctgraham?

**Comment by ctgraham** [comment]
I sense there will be more conversation here eventually, but this does resolve the issue for the change Martin Fenner suggested.  Locally, I've been instructed to still prefer the publisher institution, so until DataCite enhances their schema, we may continue to have conflicting directions.

**Comment by mfenner** [comment]
@ctgraham just one clarification: whether and when DataCite changes its schema to better support both "Journal Title" and "Publisher" is up to the DataCite Metadata Working Group, and the next schema revision is probably at least another 12 months away.

**Comment by mfenner** [comment]
Another related issue is that DataCite metadata currently don't support `volume`, `issue` and `pages`. I am currently a bit torn on this one: one hand this info is needed to properly format a citation, on the other hand these fields are pretty useless in an online-only world, and the DOI should be enough to locate the article.
