### ISSUE TITLE
OJS at cPanel

### ISSUE THREAD

**Issue by hrace009** [pkp/pkp-lib#1879]
I have install OJS using softacoulous at cPanel
When trying to create new issue i got messag with whitescreen
<pre><code>Not Acceptable

An appropriate representation of the requested resource /index.php/pb/editor/saveIssue could not be found on this server.

Additionally, a 406 Not Acceptable error was encountered while trying to use an ErrorDocument to handle the request.</code></pre>

and the issue not create

**Comment by asmecher** [comment]
@hrace009, OJS never returns a 406 error -- this must be coming from something else in your server stack. I would suggest checking your web server's error log to see if details appear there.
