### ISSUE TITLE
OJS Cannot cmplete installation

### ISSUE THREAD

**Issue by HighwayStar** [pkp/pkp-lib#1883]
I trying to fresh install OJS from master branch and cannot complete installation. After filling all forms and clicking 'Install Open journal Systems' button browser just return to the same page without any message about installation error or anything else.

I've bisected this issue down to first bad commit

```
Author: Alec Smecher <alec@xxxxxx>
Date:   Wed Sep 21 16:19:26 2016 -0700

    Template header filename fix

:040000 040000 824e4445f96484a58251154465fb1d010b321698 0156f06b8b76b162cc88b05879b976cd2941554b M      templates
```

On previous 619ee7757e6f9d8c9a493db17fd5be2af33306f2  installation works fine.

**Comment by HighwayStar** [comment]
Sorry wrong bad commit, bisecting again and will update.

**Comment by ctgraham** [comment]
Closing this issue as obsolete.
