### ISSUE TITLE
[OJS] installation with one hidden journal behaves inappropriately

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1892]
I may be conflating a couple of issues, but I haven’t fully characterized the problem yet.

With a clean, new OJS 3.0.0-0 installation, create one journal. Do _not_ mark it as publicly listed.

When visiting the OJS installation, one is forwarded to the only journal on the site, even though it should not be public.

Moreover, when attempting to register a user for the journal, the registration fails, as the new user has no roles specified. This appears to be due to `$currentContext` not being set in the `userRegister.tpl` template. Making the journal public allows user registration to succeed.

**Comment by asmecher** [comment]
@crism, is this the same as https://github.com/pkp/pkp-lib/issues/592?

**Comment by crism** [comment]
The first part of the problem is the same as the last point in #592. The inability to register does not seem to be described in #592.

**Comment by NateWr** [comment]
Correct me if I'm wrong, but once public access is cut off, the ability to register will be moot. No one will be able to access the registration form to sign up.

**Comment by crism** [comment]
@NateWr, I assumed that a lack of a public listing would mean that the journal could still be visited directly by those that knew the correct URL. That would allow the editors to begin configuring the journal before letting the public see it.

**Comment by NateWr** [comment]
@crism I'm a little uncomfortable leaving a site available when the checkbox suggests it's not publicly available. To me that means more than just not-linked-directly-to.

Logged-in users (Editors, Managers, etc) should still be able to visit the journal for configuration. And new users can be registered from the Users panel in the admin area.

**Comment by bozana** [comment]
@NateWr solved the issue https://github.com/pkp/pkp-lib/issues/592, but this still have to be solved: when trying to register on an installation with no public journals, the user get the error: "At least one role must be selected.". Should the registration option be disabled in the case when there is no public journal there?

**Comment by asmecher** [comment]
Moving that last aspect of the issue to OJS 3.0.2.

**Comment by NateWr** [comment]
Just for future reference, some changes were made in https://github.com/pkp/pkp-lib/issues/592#issuecomment-255766456 but I think they only address site-wide registration when all contexts have `disableUserReg`. If no publicly-accessible journals exist, I think registration will still be reachable but incomplete-able.

**Comment by NateWr** [comment]
I did some testing on this and as far as I can tell the registration form is not available whenever a journal is not publicly accessible. Furthermore, if no journals are publicly accessible, the registration form is still not available.

Closing as I think this is resolved.
