### ISSUE TITLE
Fix MIME type detection problems for CSS

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1893]
CSS files are often misdetected as `text/plain` or `text/x-c` by the MIME magic toolset (`finfo` / `mime_content_type`). At a glance, it looks like our best solution will be to hard-code a workaround for CSS files that watches for filename suffixes. Browsers don't like e.g. `text/plain` and will refuse to style documents that include CSS files with `text/plain` stylesheets (per the HTTP header).

**Comment by ctgraham** [comment]
Why is this not already handled by:
https://github.com/pkp/pkp-lib/blob/da97460d0fa86b09b07f232e5f188caeb704579b/classes/core/PKPString.inc.php#L439-L454
?

**Comment by ctgraham** [comment]
It's not already handled because the `finfo_open` check exits early.
https://github.com/pkp/pkp-lib/blob/da97460d0fa86b09b07f232e5f188caeb704579b/classes/core/PKPString.inc.php#L422

**Comment by asmecher** [comment]
Good spotting, @ctgraham, I'd forgotten about that code. There were two bugs in it:

- The `finfo` suite being present would result in a return from the function before the work-arounds were applied
- The `mime_content_type` function was being called using a server-side temporary filename, which doesn't include an extension

I've fixed both issues and reverted the `FileManager`-based work-around that this issue previously applied. Tested and ported around.

**Comment by ctgraham** [comment]
Are you also adding the call to [PHP's `mime_content_type` back in](https://github.com/pkp/pkp-lib/issues/1925)?  If not, I'll make a separate pull for this.

**Comment by asmecher** [comment]
@ctgraham, please go ahead!

**Comment by asmecher** [comment]
(Sorry for stepping on your toes!)

**Comment by ctgraham** [comment]
We're just fixing the problems together separately.
