### ISSUE TITLE
Dataverse plugin overrides NOTIFICATION_TYPE_ERROR message

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1894]
In OJS 2.4.x, the `NotificationManager` generously allows plugins to override the `getNotificationContents()` return value via hook:
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/notification/NotificationManager.inc.php#L173-L175

The Dataverse plugin uses this to abscond with the core `NOTIFICATION_TYPE_ERROR` message.  Not cool, Dataverse plugin, not cool.
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L1673-L1676

**Comment by asmecher** [comment]
@bozana, may I pass this one to you?

**Comment by bozana** [comment]
@ctgraham, shouldn't all the calls of `NOTIFICATION_TYPE_ERROR` here (when notifications are created) be replaced by the new NOTIFICATION_TYPE_DATAVERSE_ERROR? I see you inserted a TODO comment. Would you be able to check/evaluate it?

**Comment by bozana** [comment]
Thanks a lot @ctgraham! I merged it and will cherry-pick it to ojs-stable-2_4_8...

**Comment by bozana** [comment]
PRs:
ojs-dev-2_4: https://github.com/pkp/ojs/pull/1066/
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1071

**Comment by bozana** [comment]
Everything merge, can this issue then be closed?
