### ISSUE TITLE
ORCID support in native XML import/export format for issues

### ISSUE THREAD

**Issue by mjlassila** [pkp/pkp-lib#1896]
It seems that there is no dedicated XML element for importing author information including ORCID iDs. As using ORCID is getting more and more common, it would be useful if it could be included in the native import/export format.

**Comment by asmecher** [comment]
(Mentioned in the forum over here: http://forum.pkp.sfu.ca/t/how-to-show-biography-of-an-author/9313/5)

**Comment by bozana** [comment]
(Mentioned also here: http://forum.pkp.sfu.ca/t/ojs-3-x-import-export-of-users/28357/4)

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2713
ojs master: https://github.com/pkp/ojs/pull/1496 (submodule update ONLY)

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR?

**Comment by asmecher** [comment]
Looks good, thanks!
