### ISSUE TITLE
Add/Improve reader notification tools

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1897]
There are currently no tools to send out notifications to readers (either automatic or manual) upon publication of new content.

**Comment by asmecher** [comment]
Feedback from SI:

> In a perfect world, Readers would be able to “subscribe” to a particular series and then OMP would automatically send them a notification when a new publication in that series is released. We envision this tool being particularly useful for readers/libraries/organizations that want to add every volume of a particular series to their collections, which is why a series-based notification is most useful for us. Until that kind of functionality is developed, a good compromise would be to have a tool that allows me to manually create an email to be sent to all users with the “Reader” role so that I can announce new publications that way. (The only wrinkle with this compromise is that Readers might get sick of receiving notifications for every publication we put out, so they would need to be able to manage their own notifications.)

**Comment by ajnyga** [comment]
Hi @asmecher 
I found this old issue through a forum post I was reading. 

It occurred to me that after the changes https://github.com/pkp/pkp-lib/issues/2561#issuecomment-331271010 to the Announcements functionality, you could pretty much use them now as a general purpose notification tool. Although @NateWr did not regard this as a good idea in general https://github.com/pkp/pkp-lib/issues/2561#issuecomment-308110455

The only thing missing really is to have the actual announcement text in the notification email. I did not cover this yesterday, but adding that would probably meet the requirements above. Also SI's comment about unsubscribing fits the plan here: https://github.com/pkp/pkp-lib/issues/2561#issuecomment-331238325

In any case this should be dealt together with https://github.com/pkp/pkp-lib/issues/2805

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.

**Comment by Muhammad-Naseer** [comment]
; Use SMTP for sending mail instead of mail()
 smtp = On

; SMTP server settings
 smtp_server = smtp.gmail.com
 smtp_port = 587

; Enable SMTP authentication
; Supported mechanisms: ssl, tls
 smtp_auth = tls
 smtp_username = "abce@domain.com"    // for example 
 smtp_password = "ABC#124"


I am using above smtp settings in ojs 3.3.0.11. This was work few days ago but now its not working. Getting error "There was problem sending an email message. Please try again later. or contact your system administrator"

**Comment by asmecher** [comment]
@Muhammad-Naseer, can you post questions like this on our support forum (https://forum.pkp.sfu.ca)? That's the best place to get help.
