### ISSUE TITLE
[ojs/plugins/importexport/crossref/] HTTP ERROR 500

### ISSUE THREAD

**Issue by wolass** [pkp/pkp-lib#1900]
/management/importexport/plugin/CrossRefExportPlugin/exportSubmissions

in the new OJS  3.0.0, when I click the `submit` button in the crossref plugin I get the HTTP 500 error. 

I see the XML using the `Download XML` also `Check status` button ends up with the same error.

What is wrong here?

**Comment by bozana** [comment]
@wolass, hmmm... this is strange... I have no idea what could that be... :-\ If you don't experience any problem with "Download XML", but with "Submit" and "Check status", that means the error is occurring only when the Crossref API is used/called. Where do you see that error, in the small notification box in the upper right corner? Then it is maybe something temporarily at the Crossref side. Maybe you could try again later? Also maybe double check your credentials, e.g. can you log in at Crossref manually with them? I don't think this is the reason, but: You don't use a proxy, do you? You have php5-curl?

**Comment by wolass** [comment]
1. I am able to log in with my credentials @ crossref and these are the same what i use in OJS plugin. 
2. I am seeing a HTTP ERROR 500 page (not in the right corner but with a "sad page" in chrome).
3. I have my serve on an AWS ec2 instance 
5. BLAH!!! I read your last line and I checked for php5-curl

IT WAS MISSING! 
> sudo apt-get install php5-curl 
> sudo service apache2 restart 

did the thing !

Thank you for the help!

**Comment by asmecher** [comment]
Thanks for following up -- glad to hear it's working!

**Comment by dwisuseno** [comment]
@wolass I have same problem with u. but i have installed curl, but still error 500. 
any suggestion?

**Comment by asmecher** [comment]
@dwisuseno, this is an old bug with a posted resolution. If the suggested resolution didn't work for you, it's probably not the same bug. I'd suggest posting your question in our forum (https://forum.pkp.sfu.ca) and posting as much information as possible, including your OJS version.

**Comment by chavananand** [comment]
required PHP is >= 7.2.0; i'm currently using PHP 7.3.23-2+ubuntu20.04.1+deb.sury.org+1
i dont know whats the problem
![Screenshot from 2020-10-11 11-03-35](https://user-images.githubusercontent.com/72011711/95671202-9f9e4a00-0bb1-11eb-8a9d-4beb37bd9c59.png)

**Comment by asmecher** [comment]
@chavananand, this is an old bug with a posted resolution. If the suggested resolution didn't work for you, it's probably not the same bug. I'd suggest posting your question in our forum (https://forum.pkp.sfu.ca) and posting as much information as possible, including your OJS version.
