### ISSUE TITLE
Update Crossref DOI display according to their new guidelines

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1901]
See http://forum.pkp.sfu.ca/t/crossref-new-guidelines/21861. This should be done for OJS 2.4.9 and 3.0.1.

**Comment by asmecher** [comment]
Objections to moving this over to 3.0.2, @jmacgreg?

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1150
ojs ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1151

**Comment by bozana** [comment]
@jmacgreg, could you take a look at these changes i.e. PRs, if they are OK so?

**Comment by bozana** [comment]
@asmecher, I am not sure if something should be changed in the lensGalley plugin, could you take a look at that?

**Comment by jmacgreg** [comment]
@bozana these look great to me! They mirror my previous brief tests of what were needed. I also thought this was assigned to me - so thank you for completing it!

**Comment by asmecher** [comment]
The Lens viewer will need to update the Lens library for the new URLs. I'm holding off doing that for the moment as apparently they broke the mobile view -- see https://github.com/asmecher/lensGalley/issues/9 for details. We can revisit this once it becomes a problem.

**Comment by bozana** [comment]
everything merged, thus closing...

**Comment by primoz-svetek** [comment]
Sorry, I am not sure: Will this change get into OJS 2.4.9?

**Comment by bozana** [comment]
@primoz-svetek, yes, it will be in the next OJS release
