### ISSUE TITLE
[OJS 3.0] getBasePath() returns an empty path in PKPTemplateManager

### ISSUE THREAD

**Issue by judgej** [pkp/pkp-lib#1902]
Getting lots of warnings in the page similar to this:

> Warning: file_exists(): open_basedir restriction in effect. File(/lib/pkp/js/lib/jquery/plugins/validate/localization/messages_en.js) is not within the allowed path(s): (/var/www/vhosts/example.com/:/tmp/) in /var/www/vhosts/example.com/httpdocs/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 567

Line 567 checks for a file at:

> $basePath . $localePath . $localeCheck .'.js'

`$basePath` is set further up:

``` php
    function registerJSLibrary() {
        $basePath = $this->_request->getBasePath();
                ..
```

It is that `getBasePath()` which returns a `null`.

**Comment by judgej** [comment]
It looks like the base path is possibly correct, in that it is the HTTP base path. However, that raised the question why it is being used as an OS directory base name in the check for the language files.

**Comment by judgej** [comment]
Putting the path to the application root directory (which happens to be where the index.php file is) fixes it for me:

    if (file_exists(dirname(INDEX_FILE_LOCATION) . $basePath . $localePath . $localeCheck .'.js')) {

It seems like a bit of a kludge as a permanent fix though, but gets me past this point at least.

**Comment by ctgraham** [comment]
See also: http://forum.pkp.sfu.ca/t/ojs-3-error-logs/20706/5?u=ctgraham

**Comment by asmecher** [comment]
@mfelczak, did you get the chance to track this further?

**Comment by asmecher** [comment]
@mfelczak, I still haven't been able to replicate this locally -- but I understand it's happening on our GT servers? Would you mind setting me up with an environment I can see this in? I'm not familiar with our administration practices on those servers.

**Comment by economystic** [comment]
I had the same problem with OJS 3.0.2. The site is on a paid hosting with php5.5. The solution suggested by @judgej worked fine for me. I can give access to you to our hosting service if you want to replicate and track further the problem.

**Comment by asmecher** [comment]
Taking a quick look, this might already be fixed in #2364 -- try applying https://github.com/pkp/pkp-lib/commit/7820368dda6cd6779f2ed2348e04ad8189888fdf to see if it resolves the issue for you.

**Comment by economystic** [comment]
Yes. This solves the issue.

**Comment by asmecher** [comment]
Great, thanks for confirming!
