### ISSUE TITLE
[OJS 3.0] "Information Block" Not Displaying

### ISSUE THREAD

**Issue by judgej** [pkp/pkp-lib#1903]
The block with the "for librarians" and "for readers" links in does not display in the sidebar at all. The block plugin is installed and enabled, and there is information available for this block.

I'm not sure if the block is supposed to appear in the "settings->website->appearance-sidebar management" administration panel or not, but it doesn't.

**Comment by judgej** [comment]
I am only seeing three blocks in the appearance admin page:

* Make Submission
* Related Items
* Web Feeds

Two blocks that are not showing here, but are installed and active, and appear to be in the filesystem are:

* Information
* Language Toggle

**Comment by judgej** [comment]
Spent most of a day trying to understand blocks, and just can't fathom out why the information block is not displaying. Tried stripping it down to a minimum, like the "submissions" block. Tried messing with the context and other settings for the block in the database, so it looks like other blocks that do work. But it's no-go. The information block class gets loaded in the `appearance` admin page (in the context of a journal) but it does not appear in the sidebar management admin area at all. What happens to it after is loads is something I can't work out - something does something with it (or doesn't) somewhere deep in the guts of this application.

So I'm just going to use a custom block with links and custom static pages to present the information.

**Comment by asmecher** [comment]
This is also reported here: http://forum.pkp.sfu.ca/t/information-block-is-not-showing-up-ojs-3-0-0/22858

I'll take a look.

**Comment by asmecher** [comment]
@judgej, could you try executing the following in MySQL?

    SELECT * FROM versions WHERE product='information';

You should get a result like...

    +-------+-------+----------+-------+---------------------+---------+----------------+-------------+------------------------+-----------+----------+
    | major | minor | revision | build | date_installed      | current | product_type   | product     | product_class_name     | lazy_load | sitewide |
    +-------+-------+----------+-------+---------------------+---------+----------------+-------------+------------------------+-----------+----------+
    |     1 |     0 |        0 |     0 | 2016-09-30 22:42:07 |       1 | plugins.blocks | information | InformationBlockPlugin |         1 |        0 |
    +-------+-------+----------+-------+---------------------+---------+----------------+-------------+------------------------+-----------+----------+
    1 row in set (0.00 sec)

**Comment by judgej** [comment]
Yes, all values exactly the same, apart from the install date, which was January this year when I first installed OJS v2.8.

| "major" | "minor" | "revision" | "build" | "date_installed"      | "current" | "product_type"   | "product"     | "product_class_name"     | "lazy_load" | "sitewide" | 
|---------|---------|------------|---------|-----------------------|-----------|------------------|---------------|--------------------------|-------------|------------| 
| "1"     | "0"     | "0"        | "0"     | "2016-01-25 17:27:31" | "1"       | "plugins.blocks" | "information" | "InformationBlockPlugin" | "1"         | "0"        |

**Comment by judgej** [comment]
Ha! Yes, mine is also in backwards world like [the other poster](http://forum.pkp.sfu.ca/t/information-block-is-not-showing-up-ojs-3-0-0/22858) - disabling it makes it appear to be enabled and vice-versa.

**Comment by judgej** [comment]
This is in my `plugin_settings` with the block apparently disabled but actually working:

| plugin_name            | context_id | setting_name | setting_value | setting_type | 
|------------------------|------------|--------------|---------------|--------------| 
| informationblockplugin | 1          | context      | 1             | int          | 
| informationblockplugin | 1          | enabled      | 1             | bool         | 
| informationblockplugin | 1          | seq          | 4             | int          | 

Note that the `enabled` column remains as `1` whether the block is checked as enabled or not in the plugins admin page. The `seq` correctly changes to the block position when I move it up and down the side bar.

**Comment by judgej** [comment]
Actually, that's wrong - the `enabled` flag does reset to `0` when the block is disabled. Now it is appearing in the appearance tab (which is certainly wasn't before I started messing with the enabled checkbox this morning) it seems to be working like this:

* Setting it to enabled in the plugins tab will make it appear to the left (i.e. displayed) in the appearance panel.
* Moving it left and right in the appearance panel will enable and disable it in the plugins page,

So what we have is two actions in two different places that set and reset the same `enabled` flag, which is fine. However, there is a difference: the appearance tab dragging-and-dropping will set the `seq` also, while the plugins tab does not. I noticed the `seq` yesterday remained at 10 while it was not working, but is 4 now that it is.

*My hunch* was that this is a problem related to some code assuming the `seq` values will be contiguous. But setting the `seq` back to 10 dos not break it. So this is a little strange. I have no idea what has changed between yesterday and today to get this block working.

**Comment by asmecher** [comment]
@judgej, make sure you flush your data cache (e.g. `rm cache/*.php`) after making changes to the settings -- otherwise you'll probably only see the DB settings reflected in the settings area, otherwise it'll be fetched from cache files.

**Comment by judgej** [comment]
Ooh. Is this a known issue that needs fixing?

**Comment by asmecher** [comment]
That's expected behavior for direct changes to the database -- I'm not sure how else we'd do it and still support file-based caching. When changing settings via the UI, the settings cache is automatically flushed, so you should only see this happening if you make direct changes to the database and don't flush.

**Comment by judgej** [comment]
I misunderstood. I thought you meant the cache had to be manually flushed no matter how the settings were changed. You meant that me updating the database directly was not having any effect because the front end and the admin pages were looking at the cached data and bypassing the database.

**Comment by asmecher** [comment]
Yep -- sorry, I could initially have been clearer.

**Comment by asmecher** [comment]
Closing -- I think this was resolved. (Please correct me if not!)
