### ISSUE TITLE
Acron really, really wants to run...

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1905]
...so much so that it races itself.  See resolution attempt: https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8737
and
https://github.com/pkp/ojs/blob/dbe779f2bd97e9a0f2842c4357fb56496b7179e4/plugins/generic/acron/AcronPlugin.inc.php#L241-L260

I don't think the `switch ($updateResult) {` check is very effective.  The only reason the [getRowsAffected()](https://github.com/pkp/pkp-lib/blob/a39b1328db9ec06d2902e67b337dc5a63c60a496/classes/scheduledTask/ScheduledTaskDAO.inc.php#L99) call might [return "0"](https://github.com/pkp/ojs/blob/dbe779f2bd97e9a0f2842c4357fb56496b7179e4/plugins/generic/acron/AcronPlugin.inc.php#L257) is if [both calls ran the `time()` command](https://github.com/pkp/ojs/blob/dbe779f2bd97e9a0f2842c4357fb56496b7179e4/plugins/generic/acron/AcronPlugin.inc.php#L247) at the same second.

The time between the queueing of the tasks to [`$this->_tasksToRun` by the loadCallbackHandler()](https://github.com/pkp/ojs/blob/dbe779f2bd97e9a0f2842c4357fb56496b7179e4/plugins/generic/acron/AcronPlugin.inc.php#L140) and the [`foreach ($this->_tasksToRun)`](https://github.com/pkp/ojs/blob/dbe779f2bd97e9a0f2842c4357fb56496b7179e4/plugins/generic/acron/AcronPlugin.inc.php#L224-L247) could be minutes, depending on the request.

We might reduce (but still not eliminate) the race condition just a bit by re-checking the tasks-to-run closer to the shutdown function.

**Comment by asmecher** [comment]
Would `microtime` rather than `time` be useful in reducing the likelihood of collisions?

**Comment by ctgraham** [comment]
My reading is that we would actually want to go the other way, if we changed this.  The `time()` / `UPDATE` check operates like this:
* update the last runtime to now
** if no update occurred (another process update now as well, no DB rows changed), flag concurrency
** if an update occurred, proceed with the scheduled task.

The lower the resolution on the time, the better chance of catching concurrency.  If we truncated `time()` to a minute, of the _n_ processes started that minute, only one would win.  I considered truncating to a 5 minute period, but you still run into the boundary cases, no matter what interval is chosen.

If we want tweak the semaphore around the time, we should clone `PKPScheduledTaskDAO::updateLastRunTime()` to a new function which takes a third parameter of the `frequency` and validate the frequency in the SQL UPDATE statement.

**Comment by ctgraham** [comment]
There is also a flaw in that the `ScheduledTaskTool` (from CLI) updates the last runtime only after task completion (without consideration for the success or failure of the task).  See: https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_8/classes/cliTool/ScheduledTaskTool.inc.php#L112-L113

As it stands, if Acron was enabled and CLI work was being done by cron or interactively, Acron could run overtop of a concurrent CLI job.

The CLI's call to `updateLastRunTime()`, should be aligned with the `AcronPlugin`'s call of `updateLastRunTime()` prior to the `execute()` call.

**Comment by ctgraham** [comment]
There is also a flaw in the logic of:
```
			switch ($updateResult) {
				case false: // DB doesn't support the get affected rows used inside update method.
				case 1: // Introduced a new last run time.
```
The [`switch` statement uses loose comparisons](http://php.net/manual/en/control-structures.switch.php), so `case false` will eat `case 0`.

**Comment by asmecher** [comment]
Ah -- interesting. Your last comment alone may well explain really bad behavior on the part of this plugin, @ctgraham.

**Comment by ctgraham** [comment]
These PRs are ready for review/merge:
https://github.com/pkp/ojs/issues/1069
https://github.com/pkp/pkp-lib/issues/1917

**Comment by asmecher** [comment]
Thanks, @ctgraham! @bozana, can I give this to you?

**Comment by bozana** [comment]
Sure! Acron, the 'lovely' issue I am 'looking forward' to dive in and wonder :-)

**Comment by bozana** [comment]
As far as I can see and understand it, these PRs are OK and they help solve the issue.
@ctgraham, I will merge the PRs, then add the submodule update commit to ojs-dev-2_4 and also change master, ojs-stable-3_0_0, omp-stable-1_2 and omp-dev-1_2 accordingly. Thanks!!!

**Comment by bozana** [comment]
PRs:
master: https://github.com/pkp/pkp-lib/pull/1997
ojs-stable-3_0_0: https://github.com/pkp/pkp-lib/pull/1998
omp-dev-1_2: https://github.com/pkp/pkp-lib/pull/2001
omp-stable-1_2_0: https://github.com/pkp/pkp-lib/pull/2000

**Comment by bozana** [comment]
Hmmm... I wasn't sure if I should cherry-pick it to ojs-stable-2_4_8 as well. @asmecher, what do you think?

**Comment by bozana** [comment]
I decided today to cherry-pick it to ojs-stable-2_4_8 too... :-)

**Comment by bozana** [comment]
everything merged, closing...

**Comment by asmecher** [comment]
Belatedly: yes, thanks!
