### ISSUE TITLE
Show volume info only when checkbox selected

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1907]
See http://forum.pkp.sfu.ca/t/eliminating-0-volume-variable-when-not-using-volumes/22965

**Comment by asmecher** [comment]
Closing!

**Comment by mpbraendle** [comment]
We see the same problem for the year of publication - was this fixed, too? I do not see an indication in the code.

**Comment by asmecher** [comment]
@mpbraendle, I've just surveyed the year and it's overall covered. I added a tweak to improve this (see just above). But depending on how e.g. citation formats work, they may expect the year to be entered regardless. If you do see it somewhere you don't wish it to appear, please post details here.

**Comment by ajnyga** [comment]
Here is a related bug:
http://forum.pkp.sfu.ca/t/unable-to-deselect-volume-number-and-years-in-issue-data-section/30989

**Comment by bozana** [comment]
PR for the last comment:
ojs-stable-3_0_2: https://github.com/pkp/ojs/pull/1389

**Comment by bozana** [comment]
@ajnyga, may I ask you to take a look at the PR, if so OK?

**Comment by ajnyga** [comment]
This does solve it, but the bug still remains in the getIssueSeries / getIssueIdentification functions.
If getIssueSeries gets called and the journal has disabled all other identification than the title, the function will still return the three zeros. I am thinking of a situation where the same function gets used somewhere else later?

**Comment by bozana** [comment]
Yes, I will leave this decisions to @asmecher. -- I am not sure how this function is meant to be used, but I think that it could be only used in the case one of the option (showVolume, showNumber or showYear) is available, like in that issue_summary.tpl -- else it does not make any sense...

**Comment by bozana** [comment]
Thanks a lot @ajnyga! I will then merge and cherry-pick it to master...

**Comment by bozana** [comment]
maybe to also take this issue into account -- that would change all these approaches: https://github.com/pkp/pkp-lib/issues/2190

**Comment by ajnyga** [comment]
I was thinking that it could be solved here: https://github.com/pkp/ojs/blob/master/classes/issue/Issue.inc.php#L506
```
	function getIssueSeries() {
		if ($this->getShowVolume() || $this->getShowNumber() || $this->getShowYear())
		{
			return $this->getIssueIdentification(array('showTitle' => false));
		} else {
			return null;
		}
	}
```
With the current template solution, you also have to worry about other themes, like https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/objects/issue_summary.tpl

But if this is due to change with #2190 anyway, then I guess it does not matter that much.

**Comment by bozana** [comment]
Yes @ajnyga, that makes much more sense for now -- me crazy, how haven't I thought on that :-\ I'll change it like this for now, till #2190 comes... THANKS!!!

**Comment by bozana** [comment]
PR for pdfJsViewer: https://github.com/pkp/pdfJsViewer/pull/16

**Comment by ajnyga** [comment]
Ok, great!

**Comment by bozana** [comment]
@ajnyga, I made the changes as you suggested, but only in the master branch...

**Comment by ajnyga** [comment]
Ok, thanks! This is not an issue with our journals, I think. All of them use volume or number to my knowledge.
