### ISSUE TITLE
[OJS] Crossref plugin doesn’t use test API for status query

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1910]
Against the latest `HEAD`: When the Crossref plugin makes a deposit, it checks the test configuration status:
```php
		$endpoint = ($this->isTestMode($context) ? CROSSREF_API_URL_DEV : CROSSREF_API_URL);
```
… but when querying to see if the deposit was successful, it does not:
```php
		curl_setopt(
			$curlCh,
			CURLOPT_URL,
			CROSSREF_API_URL . (strpos(CROSSREF_API_URL,'?')===false?'?':'&') . $params
		);
```

**Comment by asmecher** [comment]
@bozana, mind taking a look?

**Comment by crism** [comment]
I’m on it; I think the fix is fairly simple.

**Comment by asmecher** [comment]
Excellent! Thanks, @crism, I'll leave @bozana to the code review.

**Comment by bozana** [comment]
Thanks a lot @crism! I will then also cherry-pick it to ojs-stable-3_0_0...

**Comment by bozana** [comment]
PRs:
master: https://github.com/pkp/ojs/pull/1070
ojs-stable-3_0_0: https://github.com/pkp/ojs/pull/1072

**Comment by bozana** [comment]
Everything merged, can this issue then be closed?

**Comment by crism** [comment]
@bozana, I think so.

**Comment by asmecher** [comment]
Doing so, thanks all!
