### ISSUE TITLE
[OJS] 2.4.8 Fatal Error while sending Editor’s comment to an Author

### ISSUE THREAD

**Issue by Marg0lin** [pkp/pkp-lib#1918]
While trying to send Editor's Decision about declining review (a feature located in Home > User > Editor > Submissions > #review_number > Review > Editor's Decision > Notify Author) there is an error `PHP Fatal error: Call to a member function getEmail() on a non-object in /home/path/to/ojs_instance/classes/submission/sectionEditor/SectionEditorAction.inc.php` on line 2056" [code on line 2056 is `$authorEmail = $authorUser->getEmail();`] it was preceded by another error, so I suspect the first could lead to the second: `PHP Fatal error: Call to a member function getFullName() on a non-object in /home/path/to/ojs_instance/cache/t_compile/%%5A^5AA^5AA9AD09%%management.tpl.php on line 101` [code on line 101 is `<?php $this->assign('emailString', ((is_array($_tmp=$this->_tpl_vars['submitter']->getFullName())) ? $this->_run_mod_handler('concat', true, $_tmp, " <", $this->_tpl_vars['submitter']->getEmail(), ">") : $this->_plugins['modifier']['concat'][0][0]->smartyConcat($_tmp, " <", $this->_tpl_vars['submitter']->getEmail(), ">"))); ?>`]. The OJS has been upgraded recently. The problem seems to be browser independent. In Review History Event Log there in an event "Editor decision submitted" - just like the comment has been sent successfully. What is it? Cache issue?

**Comment by asmecher** [comment]
I think this was already resolved [on our forum](http://forum.pkp.sfu.ca/t/fatal-error-while-sending-editors-comment-to-author/23236). You can use either way to reach us -- the forum is slightly better -- but either way, please stick with one venue.
