### ISSUE TITLE
[OJS] justboil.me image uploader doesn't work when `public/site` does not exist

### ISSUE THREAD

**Issue by kardeiz** [pkp/pkp-lib#1919]
The justboil.me image uploader hangs at `Upload in progress` when `public/site` does not exist.

This issue occurs even when apache/HTTPD has write permissions on `public`. 

Creating `public/site` and granting write permissions to apache resolves the issue.

**Comment by kardeiz** [comment]
Now I'm so confused...

This worked (once) yesterday. I literally see a file I uploaded via TinyMCE/justboil.me under `public/site/images/<me>/`.

However, when I tried the exact same thing today, it hangs again. When I change the environment to `development` in `justboil.me/ci/index.php` (in order to get better errors), I see:

    PHP Fatal error:  Call to a member function getUserVar() on a non-object in
    <...>/classes/i18n/AppLocale.inc.php

**Comment by kardeiz** [comment]
Apparently this is still somehow connected to this: [https://pkp.sfu.ca/support/forum/viewtopic.php?t=8924](https://pkp.sfu.ca/support/forum/viewtopic.php?t=8924).

When I start a new session in incognito browsing, I can upload files correctly. I presume the same thing could be done by logging out, clearing cookies, and logging back in.

What is going on here?

**Comment by asmecher** [comment]
@kardeiz, can you reliably reproduce the problem, i.e. is it always failing upon a second image upload?

**Comment by kardeiz** [comment]
Yes, I can reproduce the problem, although as I note above it appears to be cookie-related.

Steps to reproduce:

1. Delete the `public/site` folder if it exists (this folder does not exist in the OJS source download, and the justboil.me integration doesn't seem capable of creating it).
2. As a logged in user, try to upload a file (e.g., from the abstract field of a submission). `/plugins/generic/tinymce/plugins/justboil.me/ci/index.php` will error (500).
3. Create the `public/site` folder.
4. As a logged in user, try to upload a file. The justboil.me plugin will continue to throw an error until you log out, delete your cookies, and log back in. Just logging out and back in will not resolve the issue.

I think there are two issues here:

1. The plugin should be able to create the `public/site` folder if it doesn't exist. I don't know if PHP has the equivalent of `mkdir_p`, but that's probably necessary for the actions that create `public/site/images/<user>`.
2. There appears to be some sketchy cookie/session activity going on around these actions.

**Comment by asmecher** [comment]
Thanks, @kardeiz. @bozana, would you mind taking a look at this? I suspect it's related to the way we've tried to wrap the OJS session up with JBImages.

For the record, I'm not hugely fond of the way we've been integrating image uploads, so broader thinking is totally welcome here.

**Comment by bozana** [comment]
I will take a look, it could just take some time -- probably in the next week, because traveling... :-(

**Comment by RafaelMansilha** [comment]
Hi @bozana , have you looked at this?? I'm having the same problem here.

http://forum.pkp.sfu.ca/t/omp-1-2-cant-upload-images-with-tinymce/13683/6?u=rafaelmansilha

**Comment by bozana** [comment]
I haven't looked at this yes -- so many other issues/priorities -- sorry! :-\ But soon, maybe tomorrow, I promise! :-)

**Comment by RafaelMansilha** [comment]
No problem, I totality understand, I'll be waiting, =D

**Comment by murilodbva** [comment]
I believe I found the same error when I try to upload a image in my application:
```
/plugins/generic/tinymce/plugins/justboil.me/ci/index.php?blank - Call to a member function getUserVar() on null in ojs-3.0.1/classes/i18n/AppLocale.inc.php on line 70
/plugins/generic/tinymce/plugins/justboil.me/ci/index.php?upload/english - Call to a member function getUserVar() on null in ojs-3.0.1/classes/i18n/AppLocale.inc.php on line 70
```
So I discovered that this issue is from oficial version.

I made these steps to reproduce this error:
1. Download the last oficial version (3.0.1):
[http://pkp.sfu.ca/ojs/download/ojs-3.0.1.tar.gz](http://pkp.sfu.ca/ojs/download/ojs-3.0.1.tar.gz)
2. Run the application by php for install the application OJS, with this command at terminal:
`php -S 0.0.0.0:8800`
3. Open the browser and install OJS by this URL:
[http://0.0.0.0:8800](http://0.0.0.0:8800)
4. Stop the running at terminal with the shortcut:
**Ctrl + C**
5. Again, run OJS again by php and open it in browser:
`php -S 0.0.0.0:8800`
[http://0.0.0.0:8800](http://0.0.0.0:8800)
6. Click for create a new magazine.
7. At description, try to upload a image.
8. The error was showed in terminal.

**Comment by TeXnicker** [comment]
Hi guys!

I'm joining to majority position on errors from JustBoil.Me plugin. Version OJS 3.0.2 still reproduces this error. I used to try out @murilodbva pathway and still get cycled error progress 😡.

May be OJS devs should drop this plugin? AFAIK it's development stopped in 2013. OJS has now been re-written. And this plugin works awfully. I have to make sidebar buttons in HTML instead of SVG icons with hyperlinks.

**Comment by asmecher** [comment]
Agreed, @TeXnicker, this plugin has not served us well and I'd rather we removed it in favour of something better aligned with the rest of the codebase (e.g. not requiring CodeIgniter and an awkward shim to integrate it with PKP's software stack).

**Comment by wundo** [comment]
@asmecher I'm willing to help out on this, is there anyone working on removing the justboil.me dependency? Any PR?

**Comment by asmecher** [comment]
Hi @wundo -- I'm not aware of anyone working on this at the moment; contributions welcome!

**Comment by OhnO395** [comment]
mkdir -p public/site/images
change mode for web server

good luck
ohno395

**Comment by rlisperguier** [comment]
Hi everyone,

Any update on this issue? i'm getting this error on a fresh installation of OJS3.0.2 under PHP7.0 (also tried in PHP 5.6).

Digging some code inside de Justboil plugin i got this behaviour:

- Using apache for serve the site, i made a **var_dump** of the current user session and got NULL in the user.
- Using **php -S** for serving the app, the same **var_dump** gives me the current user. 

The file used for this test was **integratePKP.php**. I's seems that the problems reside on the user session context.

Anyone knows any other method to attach the image upload feature to tinymce?

**Comment by mctosimaitb** [comment]
hii,, pls solve this issue. i still stuck

**Comment by bozana** [comment]
Hi all,
I've just tried to reproduce the problem using the current OJS master branch and I was not able to do that :-( -- I was trying to reproduce it like explained here: https://github.com/pkp/pkp-lib/issues/1919#issuecomment-256428142

If the `public/site/` folder is missing one will not be able to upload the image, but if the folder is there and the permissions are correct I cannot reproduce the problem :-(
The `public/site/` folder should be created at the very beginning, at the installation, s:
https://github.com/pkp/ojs/blob/master/dbscripts/xml/install.xml#L14
and
https://github.com/pkp/pkp-lib/blob/master/classes/install/PKPInstall.inc.php#L109
Thus the folder should be there (the plugin does not have to create it). -- The requirement is the existence of the public/site/ folder and the correct permissions.

The second problem was apparently with the user session, but I have not been able to reproduce it :-( I will try further...

**Comment by bozana** [comment]
Ah, OK, now I see it too...

**Comment by bozana** [comment]
Here we get the session and the user from the session: https://github.com/pkp/tinymce/blob/master/plugins/justboil.me/integratePKP.php#L76-L78.
In the `SessionManager` then, a cookie with the `cookie_path=/plugins/generic/tinymce/plugins/justboil.me/ci/` (differently to the normal OJS `cookie_path=/`) is set here: https://github.com/pkp/pkp-lib/blob/master/classes/session/SessionManager.inc.php#L41, if the OJS config variable `session_cookie_path` is not set (which is the case per default) -- The function `$request->getBasePath()` returns `/plugins/generic/tinymce/plugins/justboil.me/ci/`.
This leads to the situation that the plugin always uses that cookie value and thus never gets the correct user; just when used for the first time and/or when that cookie is deleted.

@asmecher, I see two possible solutions:
1) not to get the user from the session, but from the request object -- I believe the image upload is now only possible if the user is logged in, so maybe there is no need any more to get the session (from here https://github.com/pkp/tinymce/blob/master/plugins/justboil.me/integratePKP.php#L76-L78)?
2) to provide cookie_path parameter to the SessionManager function.

What do you think would be better? Or any other idea?

**Comment by asmecher** [comment]
> 2. to provide cookie_path parameter to the SessionManager function.

Sorry, to which function?

**Comment by bozana** [comment]
To getManager and constructor...

**Comment by asmecher** [comment]
Hmm, what about an approach that would allow the JBImages bootstrap process (which is what puts things in the wrong place in the first place) to set a cookie path appropriately, rather than modifying the core OJS for the sake of JBImages (it's a plugin I already don't like much)? I'm not sure if it's possible e.g. to set an in-memory config variable to override the default if it's not specified manually, but something like that.

**Comment by bozana** [comment]
the function $request->getBasePath() returns that 'wrong' path /plugins/generic/tinymce/plugins/justboil.me/ci/ -- I am not sure we can change that? -- It seems correct to me, or?

**Comment by bozana** [comment]
Maybe then to get the user from the request and not from the session (the solution no. 1 above) in that plugin?

**Comment by asmecher** [comment]
You might be able to force a value into the configuration using `Config::getData` (which returns a reference). If there's no cookie path already there, force one that better suits the JBImages bootstrap. That wouldn't require any core changes.

**Comment by bozana** [comment]
@asmecher, yes, you are right 👍 -- I haven't thought about that at all...

**Comment by bozana** [comment]
PR:
tinymce master: https://github.com/pkp/tinymce/pull/22

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR?

**Comment by bozana** [comment]
Ahhhhhhhhh, OK, I see... :-) 👍

**Comment by jmvezic** [comment]
Hi all,

I'm just found this thread and I can report that this issue apparently isn't fixed in OMP 3.1. Can we have a fix for OMP as well?

**Comment by bozana** [comment]
Hi @jmvezic, the fix came after the OMP 3.1 release, so could you maybe apply these changes https://github.com/pkp/tinymce/pull/22/files, clear the cookies, double check you have public/site/ folder, and see if it works?

**Comment by jmvezic** [comment]
I'll certainly report back (I'll try to do it today, but maybe tomorrow). Thank you for the quick response.

**Comment by jmvezic** [comment]
@bozana Works like a charm, thank you!

**Comment by wundo** [comment]
YAY! thanks @bozana  and everyone involved!
