### ISSUE TITLE
problem rendering glyphicons in ojs 3.0.0

### ISSUE THREAD

**Issue by wolass** [pkp/pkp-lib#1920]
I have a strange problem and do not know if this is a bug or settings problem:

the glyphicons are sometimes rendering correctly and sometimes not. It depends on:
1. the computer I use (I always use the latest chrome browser but on either windows or linux)
2. The address eithe npwtj.com or www.npwtj.com bot there are no rules - If it does not work on one then it works on the other. 
3. Even if they work on the main site they can still fail rendering in the "dashboard"

any clues here?
I am using the standard out-of-the-box theme without anything fancy. 

I tried installing bootstrap theme set but its the same thing there.

**Comment by ctgraham** [comment]
This is very likely a configuration issue (c.f. the browser warning "`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://npwtj.com/lib/pkp/fonts/fontawesome/fontawesome-webfont.woff2?v=4.3.0. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`").  Can you repost this in the [support forum](http://forum.pkp.sfu.ca/) instead?
