### ISSUE TITLE
Add support for catalog paging

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1922]
See http://forum.pkp.sfu.ca/t/omp-1-2-0-0-catalog-paging/23223.

(Not sure if this is still an issue, though I suspect it is -- @NateWr?)

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/omp/pull/477

@asmecher can you code review?

**Comment by asmecher** [comment]
Reviewed, thanks, @NateWr -- pagination code is such a pain.

**Comment by NateWr** [comment]
Ok, as we discussed (somewhere, I can't find it), I refactored a few different places where we're paginating results on the frontend to use a new overrideable template in pkp-lib. We're now using this template (and the service class functions) to paginate:

- Issue archives
- Catalog
- Catalog series
- Catalog categories
- Section archives (in browseBySection) archive

I introduced new IssueService methods and migrated to them for the REST API. That will be useful for refactoring the issue grids to a new vue.js component when we want.

I did not refactor the searching pagination in OJS or OMP. It looked like there was a different way of handling those requests, and I'm not familiar with any of our search architecture, so I didn't want to touch them. But those are, I believe, the only uses left of the old Smarty functions for paginating a `DAOResultFactory`. If you want me to look at refactoring that, I may need some introduction to searching, how the search plugins work, etc. 

PRs:
https://github.com/pkp/pkp-lib/pull/3174
https://github.com/pkp/ojs/pull/1754
https://github.com/pkp/omp/pull/485
https://github.com/pkp/browseBySection/pull/4

**Comment by NateWr** [comment]
All tests have passed. @asmecher can you give this one last look?

**Comment by asmecher** [comment]
Looks good, @NateWr, just a few minor comments -- please go ahead and merge once you're satisfied that they're addressed.

**Comment by asmecher** [comment]
@NateWr, it looks like this one got merged. Can it be closed, or is there still work outstanding?

**Comment by NateWr** [comment]
Still working on the last of the tests. Relevant PRs are in [this comment](https://github.com/pkp/pkp-lib/issues/1922#issuecomment-350794209).

**Comment by NateWr** [comment]
Merged! Finally!
