### ISSUE TITLE
PKPString::mime_content_type() should fall back on mime_content_type when fileinfo is unavailable

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1925]
In OJS 2.4.x, we used to default to `mime_content_type()`, then to `file_info`, then to a system `file` call.
https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_8/classes/core/String.inc.php#L376-L402

In master, we now go directly for `Fileinfo` with fallback only to `file`.  There was a brief time in the PHP documentation when `mime_content_type()` was [mistakenly marked as deprecated](https://bugs.php.net/bug.php?id=71367), but it is in fact a valid and valuable fallback.  Some clients report [hosts restricting access to the `Fileinfo` package](http://forum.pkp.sfu.ca/t/wrong-format-of-jpg-message-when-adding-jpg-file/23402/12?u=ctgraham).

**Comment by asmecher** [comment]
I did indeed remove `mime_content_type` based on its deprecated status. Argh. I would still suggest keeping `Fileinfo` tools as the first option.

**Comment by ctgraham** [comment]
Agreed.  Fall through as `Fileinfo` -> `mime_content_type` -> `file`.

**Comment by ctgraham** [comment]
Why didn't this issue get an automatic "@ctgraham referenced this issue in a commit" for https://github.com/ulsdevteam/pkp-lib/commit/702de1e865c0d9c946b6fade20d0390764598290 ?

**Comment by asmecher** [comment]
> Why didn't this issue get an ...

It did -- maybe after you checked?

Anyway, thanks! Merged and cherry-picked around.
