### ISSUE TITLE
locale key parameter missing

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1929]
the `$articleId` and `$submissionId` parameters are missing for these locale keys: `log.author.submitted` (classes/author/form/submit/AuthorSubmitStep5Form.inc.php) and `log.editor.archived` (in classes/submission/sectionEditor/SectionEditorAction.inc.php)
(These keys are not used any more in OJS 3).

**Comment by alireza08** [comment]
Hi,
I corrected these two variables.

**AuthorSubmitStep5Form.inc.php** 
```
function execute() {
...
ArticleLog::logEvent($this->request, $article, ARTICLE_LOG_ARTICLE_SUBMIT, 'log.author.submitted', 
			array('authorName' => $user->getFullName(),
				  'submissionId' => $article->getId()));
return $this->articleId;
}
```

**SectionEditorAction.inc.php** 
```
function archiveSubmission($sectionEditorSubmission, $request) {
		.....
		// Add log
		import('classes.article.log.ArticleLog');
		ArticleLog::logEvent($request, $sectionEditorSubmission, ARTICLE_LOG_EDITOR_ARCHIVE, 'log.editor.archived',array('articleId' => $sectionEditorSubmission->getId()));
	}
```

**Comment by bozana** [comment]
PRs:
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1076
ojs-dev-2_4: https://github.com/pkp/ojs/pull/1077
