### ISSUE TITLE
Include article prefix on article details page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1930]
See: http://forum.pkp.sfu.ca/t/prefix-of-title-does-not-appear-in-issue/23206/6

Currently the templates output `$article->getLocalizedTitle()`, but this doesn't include the prefix. There is `$article->getLocalizedFullTitle()`, which includes the prefix. But it also includes the subtitle, which we don't want in most cases.

Either create a new method, `getLocalizedPrefixedTitle()`, or update the templates to concatenate the prefix with the title directly.

@asmecher @mtub Is there any particular way we're concatenating prefixes with titles already? I'm thinking about different needs for different languages. Or are we just chucking the two together?

**Comment by asmecher** [comment]
We're pretty much chucking them together -- though there are a few hard-coded rules (see PKPString::concatTitleFields). I don't know enough about rules for this in other languages to have much of a suggestion for how to improve it.

**Comment by NateWr** [comment]
@asmecher I looked at this quickly today. There are a _lot_ of places using `$article->getLocalizedTitle()` where they would probably expect the prefix. That seems like the most common and intuitive use of the method.

What do you think about modifying this method to include the prefix by default, and then adding a param to exclude the prefix. We can then just update those few instances (like, I presume, export plugins and metadata output) where the title without the prefix is preferred.

That would look like this:

```
	function getLocalizedTitle($preferredLocale = null, $includePrefix = true) {
		$title = $this->getLocalizedData('title', $preferredLocale);
		if ($includePrefix) {
			$title = $this->getLocalizedPrefix() . $title;
		}
		return $title;
	}
```

**Comment by asmecher** [comment]
@NateWr, I'm a little antsy about mixing business logic (how full titles are assembled) into a function that's generally concerned with data access, but on second thought, getting a localized title is already sort of business-logicky. Yes, I think that approach makes sense -- but are you intentionally removing the other logic that used to apply when glomming the strings together?

**Comment by NateWr** [comment]
@asmecher I'm not aware of any previous logic for glomming the strings together. `Submission` objects have no `getPrefixedTitle` method and the `getFullTitle` method just concatenates them with a space:

https://github.com/pkp/pkp-lib/blob/master/classes/submission/Submission.inc.php#L477-L496

As far as I'm aware, throughout the system just kind of ignores prefixes (oversight?) except in `getFullTitle`.

**Comment by asmecher** [comment]
I mean the glomming in `PKPString::concatTitleFields` (called e.g. from `Submission::getFullTitle`).

**Comment by NateWr** [comment]
Ah, no, the `contactTitleFields` is only for joining a title with a subtitle. With the prefix, we're just concatenating them with a space.

**Comment by NateWr** [comment]
Ok, I went through the references and didn't find many places where the title without a prefix is desired.

I searched specifically in the `importexport` plugin directory but didn't see any references to the prefix. The only place I found the prefix used was in the form where it's entered and in ordering search results.

I did find references to `getLocalizedTitle()` in the following files and I wasn't sure if they should be with or without prefix:

```
ArticleTombstoneManager.inc.php
PubMedExportDom.inc.php
OAIMetadataFormat_RFC1807.inc.php
```

Any ideas? So far this is only OJS. I haven't looked at OMP. Maybe it's in heavier use there for sorting book titles in the catalog.

**Comment by bozana** [comment]
I think `getLocalizedTitle` in `ArticleTombstoneManager.inc.php` is for sections, thus this is not relevant.
For `OAIMetadataFormat_RFC1807.inc.php`: I believe the title display via OAI should be consistent for all OAI formats, if possible. For example, also here to be considered then: `https://github.com/pkp/ojs/blob/master/plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.inc.php#L84`. Thus maybe also `getTitle()` calls should be considered for the change?

**Comment by NateWr** [comment]
Thanks @bozana. I think I've got all the necessary bits updated, including Submissions and OMP Series. I ran through searches for `getTitle`, `getLocalizedTitle`, `getPrefix`, `getLocalizedPrefix`, `getFullTitle` and `getLocalizedFullTitle`. Anywhere the prefix was explicitly set (form data, metdata output and import/export plugins), I added the optional flag to prevent `getTitle` and `getLocalizedTitle` from including the prefix. Every other call includes the prefix. It turned into a bit more of a rabbit-hole than I anticipated.

PRs (tests running):
https://github.com/pkp/pkp-lib/pull/1960
https://github.com/pkp/ojs/pull/1090
https://github.com/pkp/omp/pull/347

**Comment by NateWr** [comment]
Tests have passed. @bozana, mind doing a code review?

**Comment by bozana** [comment]
@NateWr, the code looks good, so it can be merged and cherry-picked (if necessary) :-)

**Comment by NateWr** [comment]
Thanks @bozana! I've cherry-picked them over. Closing.
