### ISSUE TITLE
signoffs migration

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1931]
These few issues exist when migrating SIGNOFF_PROOFING from OMP 1.1 to OMP 1.2:
- The SIGNOFF_PROOFING entries are moved to the DB table queries with the wrong assoc_type: assoc type = 521 = ASSOC_TYPE_REPRESENTATION is wrong, it should be 1048585 = ASSOC_TYPE_SUBMISSION, in order to be visible in the production discussions list. Thereby the assoc_id and seq have to be considered too.
- The publication format files that had an auditor (SIGNOFF_PROOFING) have the wrong assoc_type (and thus assoc_id) after the migration: assoc_type = 520 = ASSOC_TYPE_NOTE is wrong, it should be 521 = ASSOC_TYPE_REPRESENTATION, in order for those files to be visible as publication formats files (for editors in the publication formats grid and for readers on the book page). (In OMP 1.1 the files with the assoc_type = 520 were displayed to the readers, but in OMP 1.2 are not). Changing the assoc_type to 521 means that the files will not be connected with the production discussion, but this is correct so i.e. not so important.

s. http://forum.pkp.sfu.ca/t/problem-with-upgrade-to-omp-1-2/22242/5

Note: After the migration, all participants are included as discussion participants. There was a thought that only the assigned auditors should be included as discussion participants. Maybe a reason against it: also editors or press managers could be active in the SIGNOFFs and we would not know it exactly, thus maybe the simplest solution to consider them all (all participants).

**Comment by bozana** [comment]
@asmecher, should I then also try to correct the second point above for the OMP 1.2 installations i.e. those that already upgraded from 1.1 to 1.2? If so, how to best proceed with it -- how to return the files with assoc_type = 520 = ASSOC_TYPE_NOTE to have assoc_type = 521 = ASSOC_TYPE_REPRESENTATION i.e. how could I exactly know what files are publication format files and what are notes files? Could I only check if one of these DB columns are not null: direct_sales_price, sales_type and viewable? Would that be sufficient and/or correct way to do it?

**Comment by bozana** [comment]
@asmecher, I've just realized that the logic from my last comment here (to look at those 3 DB columns to repair the files in the OMP 1.2 installations that already upgraded from 1.1) is not sufficient -- files could be uploaded as publication format files, but still not be approved and without terms set i.e. without data in those 3 columns. Thus, we cannot reconstruct the data totally. Furthermore, editors maybe already uploaded new files or repaired them somehow, in order to display them on the book pages online again, so that a try to repair them now could maybe make the things even worse i.e. having double files displayed to the readers. Thus I think we should not try to repair those publication format files for those OMP 1.2 installations and leave them for the editors i.e. that the editors repair all publication format files manually. What do you think?

**Comment by bozana** [comment]
PRs:
master: https://github.com/pkp/omp/pull/341

@asmecher, could you take a look at this PR?

**Comment by bozana** [comment]
@asmecher, just to let you know, that I tested it also with a 'real' data and I think it works correctly now.

**Comment by asmecher** [comment]
At a glance, this looks good -- does it also adequately handle data that went through the original migration?

**Comment by bozana** [comment]
Yes, it can just not repair missing publication files, s. https://github.com/pkp/pkp-lib/issues/1931#issuecomment-257385293

**Comment by asmecher** [comment]
OK, yes, I think your logic is good. I'll merge this -- and thanks for taking on a tough one that was at least partially my mess!

**Comment by asmecher** [comment]
Oh -- one small fix to make: the `$i` variable isn't initialized before it's used.

**Comment by bozana** [comment]
Thanks a lot @asmecher! I fix the variable initialization here: https://github.com/pkp/omp/pull/348. Then I will cherry-pick it all to omp-stable-1_2_0 and omp-dev-1_2.

**Comment by bozana** [comment]
Everything merged, thus closing...
