### ISSUE TITLE
Investigate upgrade of submission note files

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1932]
See http://forum.pkp.sfu.ca/t/submission-notes-and-upgrading-to-ojs3-note-files-lost/23374 for details.

**Comment by asmecher** [comment]
@bozana, assigning you because you were active on the referenced PR. Feel free to defer to OJS 3.1 if you're busy with other things.

**Comment by bozana** [comment]
The submission notes are correctly migrated, but the notes in 3.x generally do not consider files/attachments. No information is lost.
Maybe to display the notes in the same way as messages in a discussion?

**Comment by bozana** [comment]
Ah, I was wrong -- the connection between the submission file and a note is missing (the assoc_type and assoc_id for the file are missing) and this will be difficult to repair for those already migrated :-\
Maybe we could only try to guess: In OJS 2.4.x there could be only 1 file per note. Thus maybe to go all files with stage_id = 3 (note) where assoc_type and assoc_id is NULL, then to get all the notes for that submission (the file belongs to) and assign the notes to the files in the order they are in the DB?
@asmecher, what do you think?

The file display is partly considered, s. https://github.com/pkp/pkp-lib/blob/master/templates/controllers/informationCenter/notesList.tpl#L14, just that the variable `noteFilesDownloadLink` does not exists yet and is thus not assigned to the template. Once the migration issue is solved, the variable can be set and assigned to the template as well.

**Comment by asmecher** [comment]
@bozana, please continue investigating, but it's a viable approach for us to simply stop supporting files on notes. The notes feature as a whole is not widely used in OJS 2.x, and the notes feature on top of that probably has very, very few users, so I'm not sure it's worth a large investment of time.

**Comment by bozana** [comment]
Here is the SQL that should be executed by those already migrated from OJS 2.4.x to OJS 3.x and that are missing the notes files:
UPDATE ojs3DB.submission_files, ojs2DB.notes SET ojs3DB.submission_files.assoc_type = 520, ojs3DB.submission_files.assoc_id = ojs2DB.notes.note_id WHERE ojs2DB.notes.file_id = ojs3DB.submission_files.file_id AND ojs3DB.submission_files.file_stage = 3

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1334

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR above?

**Comment by asmecher** [comment]
Looks good, @bozana, please go ahead. By the way, I like this `_tmp` pattern you're using recently for migrating old data -- in past years we might've left old columns available in the database for legacy purposes, and it becomes difficult to avoid leaving them around. This way we can strip the old upgrade scripts when we decide to shorten the upgrade legacy and nothing gets left around.

**Comment by bozana** [comment]
PR for the display of submission not file:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2396

**Comment by bozana** [comment]
@asmecher, could you take a look at this PR, to display the submission note file for download: https://github.com/pkp/pkp-lib/pull/2396 ?

**Comment by asmecher** [comment]
Do I understand correctly that with this PR OJS will correctly present note files that were created in 2.x, but it's still impossible to create note files in OJS 3.x? If so, it might be worth noting in the related code that it's needed for legacy data -- otherwise I'm likely to come through and remove it accidentally sometime in the unknown future.

**Comment by bozana** [comment]
@asmecher, I added your suggestions and merged. I will then close this issue. In the future we can then see what to do with submission notes, if they should stay as they are, if we should provide the file upload there too, etc.

**Comment by asmecher** [comment]
Thanks, @bozana!
