### ISSUE TITLE
Article galleys metrics migration from 2.4.x to 3.0

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1933]
From the issue https://github.com/pkp/pkp-lib/issues/1840

> Article Galleys are not tracked any more in 3.0 (instead the files are), s. e.g. UsageStatsLoader::getExpectedPageAndOp. But they will remain in the table as they are i.e. with the ASSOC_TYPE_REPRESENTATION.

From this issue comment https://github.com/pkp/pkp-lib/issues/1314#issuecomment-253970656:

> And now that I am thinking about it all, the ASSOC_TYPE_REPRESENTATIONs, that are already in the DB, from OJS 2.4.x, are not considered any more for reports/statistics, which will make the numbers pretty different :-( Thus, those should be migrated to be ASSOC_TYPE_SUBMISSION_FILE, to fit into the new logic -- I didn't realized it, s. last point/item here #1840.

Thus, the ASSOC_TYPE_REPRESENTATION should be accordingly replaced by ASSOC_TYPE_SUBMISSION_FILE, if they are not remote galleys. Remote galleys are not tracked and counted any more, but they can remain in the DB as ASSOC_TYPE_REPRESENTATIONs.

**Comment by bozana** [comment]
PRs:
master: https://github.com/pkp/ojs/pull/1118

**Comment by bozana** [comment]
@asmecher could you take a look at the PR above?
@ctgraham, do you also think this concept/solution is OK so i.e. if there is something you think is not right in the concept? -- just to have one more person (that knows about the metrics) taking a look/thinking about it...
THANKS!!!

**Comment by asmecher** [comment]
Merged, thanks, @bozana!
