### ISSUE TITLE
Resequence the category items

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1937]
The first article in the TOC cannot be changed, s. http://forum.pkp.sfu.ca/t/ojs-3-cannot-order-articles/23629/

`$categoryData->rowsId` in the function `_saveRowsInCategoriesSequence` in `lib/pkp/classes/controllers/grid/feature/OrderCategoryGridItemsFeature.inc.php` contains also the parent category ID (e.g. section ID), that can be the same as the category item ID (e.g. article ID), e.g.:
```
[rowsId] => Array (
 [0] => 1
 [1] => 4
 [2] => 1
 [3] => 12
 [4] => 14
 [5] => 24
)
```
So that `$rowPosition` here https://github.com/pkp/pkp-lib/blob/master/classes/controllers/grid/feature/OrderCategoryGridItemsFeature.inc.php#L147 is always the first index.
Thus, the first element containing the parent category ID should be removed here.

Furthermore, `$newSequence` always increases, which every ordering, because `$firstSeqValue` is added to the `$rowPosition` here https://github.com/pkp/pkp-lib/blob/master/classes/controllers/grid/feature/OrderCategoryGridItemsFeature.inc.php#L148. Thus, just the new `$rowPosition` should be taken for/as `$newSequence`.

**Comment by bozana** [comment]
PR:
master: https://github.com/pkp/pkp-lib/pull/1938

**Comment by bozana** [comment]
@NateWr, I don't know how your time is to code review this PR? Else, I'll ask @asmecher...

**Comment by NateWr** [comment]
Sure!

**Comment by NateWr** [comment]
Merged!

I wasn't able to reproduce the original problem, but if I understand it correctly, it only occurs when there's a conflict between the section id and article id. I tested with the changes as well and didn't see any problems so :+1:

**Comment by bozana** [comment]
Thanks a lot @NateWr! I will then cherry-pick to other branches...

**Comment by bozana** [comment]
All PRs merged, thus closing...
