### ISSUE TITLE
[OJS] Enable minified JS by default in OJS 2.4.x

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#1939]
PKPTemplateManager.inc.php:113 includes a flag for using minified JS based on a config setting ("enable_minified"). However, that setting is not included in config.TEMPLATE.inc.php -- it should be added and enabled by default.

**Comment by asmecher** [comment]
Note that I can't speak to the quality/completeness of the minified JS in OJS 2.x -- it's been a long time since that received any JS attention. It'll need some testing, and unless there's a good reason to spend time on it, I'd rather leave a dead horse un-kicked.

**Comment by mfelczak** [comment]
Thanks @asmecher -- I may be able to have a look. I'm not familiar with the process, but is there anything that I would need to do beyond minifying the core PKP JS included by default in the header?

**Comment by asmecher** [comment]
Minifying the JS, pushing the updated JS to github, and turning on the config option would be enough. Kick it around a little for testing. (I think there's almost zero code in the 2.x releases that uses this framework -- probably just the citation assistant.)

**Comment by mfelczak** [comment]
Thanks @asmecher, that's helpful. At the moment all that unminified JS is being included in the header across all pages (even though it sounds like it's not really being used).

**Comment by asmecher** [comment]
(OJS 2.x is no longer supported)
