### ISSUE TITLE
{$abstractTermIfEnabled} is not rendering in the emails for review request to a reviewer

### ISSUE THREAD

**Issue by wolass** [pkp/pkp-lib#1946]
I get this at the top of the abstract when I am asking a reviewer for a review:

`{$abstractTermIfEnabled}`

**Comment by asmecher** [comment]
@wolass, which of our applications are you using, and what version?

**Comment by wolass** [comment]
Oh sorry all my comments are about ojs 3.0.0

**Comment by asmecher** [comment]
Was this upgraded from a previous version of OJS, or is it a fresh install?

**Comment by wolass** [comment]
Upgrade from 2.4.7

**Comment by asmecher** [comment]
Try applying either of the attached patches in the `lib/pkp` subdirectory (both are equivalent, just for different branches). That email variable isn't used in OJS 3.0 anymore, but the patch will add it just in case you have OJS 2.x templates still in place, as you do after your upgrade.
