### ISSUE TITLE
Rewiew link in the submissions window takes me to the review and not to the workflow if I am both reviewr and editor of the submission

### ISSUE THREAD

**Issue by wolass** [pkp/pkp-lib#1947]
When acting both a reviewer and an editor on the same paper, after clicking `Review` link I am always sent to the review window. And I can never reach the  "workflow" part.

so I need to use the adress in the browser `/workflow/#/1` to get to the submission workflow page.

Is this intended?

**Comment by asmecher** [comment]
@wolass, I presume this is OJS 3.0 you're using?

**Comment by asmecher** [comment]
(Confirmed!)

**Comment by asmecher** [comment]
Do you expect to have a production environment where editors are also reviewers, or is this just test data?
