### ISSUE TITLE
Update COinS plugin for OJS 3.0

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1953]
Update the plugin from OJS 2.x code to OJS 3.x code; test with Zotero to ensure that the COinS data is being detected on the article and issue pages and that the data can be correctly ingested.

The front-end hooks that used to be used to embed content have almost certainly changed.

This plugin is currently suppressed from the build package via `tools/buildpkg.sh`; once it's rewritten, allow the plugin to be shipped.

**Comment by defstat** [comment]
I am on it!

**Comment by asmecher** [comment]
Repo: https://github.com/defstat/coins

**Comment by asmecher** [comment]
Moving to 3.1, but only to close 3.0.2 off -- I can add this to the plugin gallery ASAP. (The QuickSubmit plugin is now there too.)

**Comment by asmecher** [comment]
It's released and placed in the plugin gallery for OJS 3.0.2! @defstat, can you remove your repo? I've forked it over to the pkp account (and made a few quick tweaks).

**Comment by defstat** [comment]
@asmecher  Removed
