### ISSUE TITLE
[OJS] 3.0.0 lens.js

### ISSUE THREAD

**Issue by RichardPilbery** [pkp/pkp-lib#1954]
The NlmToLensConverter.Prototype has two functions called test. As a result, when using this converter instead of Elife, the error "Uncaught Error: No suitable converter found for this document(…)" appears in the javascript console and the 'Loading article' gif remains on screen.

If you remove the second function this.test (line 5506–5508) from the file plugins > generic > lensGallery > lib > lens > lens.js, the XML renders correctly.

**Comment by asmecher** [comment]
@RichardPilbery, that's third-party code -- we don't maintain it. See https://github.com/elifesciences/lens/ for the github repo. I'd suggest following up with them to see why the XML isn't getting rendered -- first, I'd suggest ensuring that the XML validates properly, just OTOH.

**Comment by RichardPilbery** [comment]
Their code is not the problem. I've run my XML through an instance of their Master branch code and it renders fine. The elifesciences [NlmToLensConverter](https://github.com/elifesciences/lens/blob/develop/converter/lens_converter.js) prototype does not contain two instances of the test function like the OJS version does.

**Comment by asmecher** [comment]
@RichardPilbery, that code (`lens.js`) is part of Lens Reader. OJS 3.0 includes the [beta 4 release](https://github.com/elifesciences/lens/releases/download/2.0.0-beta4/lens-2.0.0-beta4.zip) of Lens Reader, which includes the code you're referencing.

**Comment by RichardPilbery** [comment]
@asmecher You're right, it does! I didn't look at the beta as they've released [v2.0.0,](https://github.com/elifesciences/lens/releases/tag/2.0.0) which does not have this error. Any chance the plugin could be updated in OJS?

**Comment by asmecher** [comment]
@RichardPilbery, yes, I've filed that here:
https://github.com/asmecher/lensGalley/issues/9
If you do swap out the beta for the full release, please report on whether any issues crop up!
