### ISSUE TITLE
[OJS] 3.0.0 schemaValidate, proxy settings and allow_url_fopen

### ISSUE THREAD

**Issue by knjigor** [pkp/pkp-lib#1955]
Refer to http://forum.pkp.sfu.ca/t/ojs-3-crossref-error/23770/14?u=knjigor

**Comment by bozana** [comment]
For XML validation, the PHP method `schemaValidate` is used. It gets the Crossref schema URL as parameter. I don't know how this method then uses the URL and how to solve the proxy problem :-( @asmecher, do you think `stream_context_set_default` (like for example described here) would work? 
Or, does anybody know how we could download localy all the "millions" ;-) schemas, that the Crossref schema includes?

**Comment by asmecher** [comment]
It looks like `stream_context_create` is one way to do it -- looking at http://php.net/manual/en/context.http.php -- but it would need some testing. Another option would be to add an option to disable validation completely -- this would work around this problem but also would be useful for other purposes, such as production deployment if/where validation was too time-consuming. But I would rather we didn't mirror all the CrossRef stuff locally.

**Comment by bozana** [comment]
The option to disable validation would be also good if the `allow_url_fopen = Off` -- we use schemas URLs, so the `schemaValidate` uses `fopen` to get the schema. If `allow_url_fopen` is disabled, this will not work. S. http://forum.pkp.sfu.ca/t/ojs3-0-2-and-crossref-plugin-validation-error/28369/10.

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_0_2: https://github.com/pkp/pkp-lib/pull/2264
ojs ojs-stable-3_0_2: https://github.com/pkp/ojs/pull/1248

**Comment by bozana** [comment]
@asmecher, could you please take a look at the PRs above?

**Comment by bozana** [comment]
Everything merged, thus closing...
