### ISSUE TITLE
PubmedNlm30CitationSchemaFilterTest and CURL SSL Version

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1959]
This test is failing with the error: `DOMDocument::loadXML(): Space required after the Public Identifier in Entity, line: 1`. This is because all the URLs are redirected to `https` and the result XML is: 
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;mode=xml&amp;tool=pkp-wal&amp;id=12140307">here</a>.</p>
</body></html>
```

Changing the webservice URLs in `plugins/citationLookup/pubmed/filter/PubmedNlm30CitationSchemaFilter.inc.php` to `https` leads to this error: `error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure`.
Thus, now I am not sure, how to change this line correctly: https://github.com/pkp/pkp-lib/blob/master/classes/webservice/WebService.inc.php#L326. What SSL version should be there, so that this functions well for all webservices and on all server environments (OpenSSL version)? CURL_SSLVERSION_TLSv1? -- It solves this test issue, but it eventually does not work for all server environments because it needs OpenSSL > 1, I believe.

**Comment by asmecher** [comment]
I've been wrestling with this (among other things) since Friday -- it looks like OpenSSL/CURL is hard to update on the current Travis testing environment, so I've just disabled the test for now (especially since it's related to code that's only IIRC used in the defunct Citation Assistant).

The commit: https://github.com/asmecher/pkp-lib/commit/281624a0221c1be6261f793273627b1dc0b46ac7

I'll merge it fairly soon -- just working on some other related stuff.

**Comment by asmecher** [comment]
I've cherry-picked that test disable around, FYI.

**Comment by bozana** [comment]
Great, thanks @asmecher! This could eventually stay open till a solution for OpenSSL/CURL (not only for Travis, but also other users?) is find?

**Comment by asmecher** [comment]
Yes, I think that's a good idea.

**Comment by asmecher** [comment]
I think we added some of these calls around the same time as both the push to move to HTTPS everywhere, and a few high-profile SSL vulnerabilities. I suspect they were necessary to adapt to PHP environments that weren't kept up to date with those developments. My hope is that we're past that now and can return to letting the defaults prevail, but unfortunately there's no way to know what'll happen in our broader community.

The safest thing to do, I think, would be to remove the `CURLOPT_SSLVERSION` by default, but allow a `config.inc.php` variable to override it when specified. It would need to be a different `config.inc.php` variable for each service, as the specific services will have different tolerances/configurations.

**Comment by asmecher** [comment]
@bozana, you could use `get_class` or something, I suppose, and use an array parameter in `config.inc.php` -- something like

`curl_sslversion[ClassNameHere] = 4`

**Comment by bozana** [comment]
Hmmm... maybe I understand it wrong: I think this all is used like this, for example:
```
$webServiceRequest = new WebServiceRequest($url, $params, $method);
$webService = new WebService();
$result =& $webService->call($webServiceRequest);
```
Thus, WebService will not know the class that is using it, or?
:-\

**Comment by asmecher** [comment]
Sorry, I misremembered this as a class extension. I suppose it would be necessary to add a new member variable to `WebServiceRequest` (e.g. `setSslVersion`) and a setter that an upstream caller could use.

**Comment by NateWr** [comment]
@bozana is this test failure still relevant or should I close this issue?

**Comment by bozana** [comment]
Closing :-) Thanks @NateWr !!!
