### ISSUE TITLE
[OJS] OJS 3.0: Section editor gets assigned to all submissions

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#1962]
I tested the section editor functionality in OJS 3.0 and encountered a problem:
- I create one section editor account
- I create two sections in the journal A and B and assign the section editor to section B
- I submit a new article to section A
- The section editor is automatically assigned to the submission althought she is not assigned to section A

I encoutered this problem with two separate installations. The first one is an upgrade from 2.4 and the second one is a clean installation of OJS 3.0.

**Comment by asmecher** [comment]
This is intended behavior -- in cases where only one user fulfills a role, that user is automatically assigned to submissions when they come in.

**Comment by ajnyga** [comment]
But the journal has a normal editor as well. What if I specifically do not want to give section A articles to the section editor - only the section B articles?

**Comment by WaDelma** [comment]
I think the work around for this is just to another dummy section editor. What I understood from @asmecher comment is that if you only have one section editor they will be assigned automatically, but if you have more than one it doesn't happen. Correct if I am wrong.

**Comment by ajnyga** [comment]
Yep, I tried a similar solution where I assigned the section editor role to the editor as well. The result is the same as probably would be if I would add a dummy account.

I still think that the default functionality with one editor and one section editor is misleading and does not seem logical. But I can of course work with this now that I know what to tell the journals.

**Comment by asmecher** [comment]
@ajnyga, I was just working on #2313 and @bozana noted that this issue relates to the same problem. Have a look at the PRs over there, if you like. I'll close this in favour of that entry.

**Comment by ajnyga** [comment]
Great thanks!
