### ISSUE TITLE
Port implicit authentication to master

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1963]
See https://github.com/pkp/pkp-lib/issues/1614

Implicit authentication (such as Shibboleth) is currently only coded to OJS 2.x, and needs to be ported to master.

Ideally, this would happen in the plugin framework, instead of being "magic" in the config.inc.php.  This make a dependency on https://github.com/pkp/pkp-lib/issues/1923

**Comment by crism** [comment]
@ctgraham, any work in progress to share on this? I’m very interested in getting this working, and willing to help out.

**Comment by ctgraham** [comment]
Hi, @crism.  I'm in a bit of dependency hell on this one.  Specifically, I've convinced myself that to do this right, each authentication source needs to be a plugin, and each authentication needs to be configurable by at the [site level, the journal level, or both](https://github.com/pkp/pkp-lib/issues/1923).  I sketched something out in a local repository, but it depended on [knowing the requesting context within a component](https://github.com/pkp/pkp-lib/issues/1923#issuecomment-278104651).  So then we're off to [normalize the constructors for component controllers](https://github.com/pkp/pkp-lib/issues/2444)

It looks like in the meantime I've lost most of the changes of interest from my local repo that enabled site inheritance in the plugin architecture.  I'm going to try to reconstitute these, and this time post them to the ulsdevteam repo so the WIP doesn't get lost.

Would you be interested in testing the commits of pkp/pkp-lib#2444, or starting to extract the legacy implicit authentication into a plugin form while I do that?

**Comment by crism** [comment]
@ctgraham, I was just looking at #1923… Yes, I can test #2444. Thanks for the update.

**Comment by crism** [comment]
I believe this depends on #2443; noting that here so I don’t forget if I get pulled away for a week or two… again.

**Comment by crism** [comment]
Yuck. It looks like the concept of implicit authentication permeates OJS 2._x_. The Shibboleth plugin registers a callback, but the calls to that callback are all over the place; over 50 references, by a quick count.

Is it even possible to do this as a clean plugin? I’m going to try, but welcome thoughts…

**Comment by asmecher** [comment]
@crism, the Shibboleth support was a 3rd-party contribution, possibly more spaghetti than necessary if integration had been approached at a deeper level, and not well maintained. I would be equally happy to see a fresh start.

**Comment by crism** [comment]
If this is going to ship with OJS and OMP, it need to be possible to enable and disable, which means it inherits (conceptually) from both `AuthPlugin` and `LazyLoadPlugin`. For now, I’m leaving it as inheriting from `AuthPlugin` and I copied a few methods related to enabling from `LazyLoadPlugin`. Anyone have a problem with that?

**Comment by crism** [comment]
When the plugin is enabled:
 - [ ] configuration should allow Shibboleth settings to be entered and stored
 - [ ] configuration should allow assertion of implicit admins
 - [ ] any direct login attempts should be redirected to the Shibboleth provider
 - [ ] all login links should redirect to Shibboleth provider
 - [ ] logins through Shibboleth should successfully create new accounts, if no e-mail address matches
 - [ ] logins through Shibboleth should succeed if previously used with Shibboleth
 - [ ] logins through Shibboleth should succeed in accessing existing accounts if e-mail addresses match

When the plugin is not enabled:
 - [ ] new account creation/login etc. should work as usual
 - [ ] Shibboleth-created accounts should be able to reset/recover through the usual UI

I’m least confident that Shibboleth should grant access to accounts by e-mail… a clever attacker could configure a fake Shibboleth service, but they’d have to be an O*S admin to configure this, which means they could just hijack any account they wanted anyway, so I think this is OK. @ctgraham, @asmecher?

**Comment by ctgraham** [comment]
Ultimately, we'll want the option of making Shibboleth authentication optional.  That doesn't need to be a requirement here, but it will be one of my goals.

I'm also pretty wary of the hijack-an-acccount-based-on-email-match issue.  This becomes a bigger problem with my ultimate goal of pluggable, hierarchical authentication.  If email matching is to be used for authentication, all email updates must be verified.  For example:
* Dr. Evil signs up a new account "Professor Plum" via some pluggable authentication source (OpenID, OAuth, etc).
* Dr. Evil changes the account's email address to Professor Plum's real email address, unverified.
* Dr. Evil tricks Professor Plum to login with another pluggable authentication source (Shibboleth).
* Dr. Evil now has access to an account which Professor Plum thinks is his or her own.

If the change of email is verified, this risk is mitigated.  Alternately, adding a new authentication source to an existing account could require authentication with the original source for linking.

**Comment by crism** [comment]
@ctgraham, that’s the kind of thing I worry about—however, the Shibboleth plugin, as I envision it working and as it worked in 2._x_, will take over completely; when enabled, it will be the _only_ way to log in. So Prof. Plum may be using an account to which Dr. Evil _used_ to have access, but he won’t any more.

That said, it should always the be the case that a change of e-mail address should require notification.

The scenario I have in mind is: Dr. Evil sets up an identity provider, which he controls, and which includes an identity for Prof. Plum, who already has an account on OJS. Dr. Evil then switches OJS to use that identity provider, and now can log in to the account on which Prof. Plum has worked so hard. However, that scenario requires Dr. Evil to have admin privileges on OJS, in which case, he’s already won, so…

**Comment by ctgraham** [comment]
The case of the malicious journal manager would be problematic primarily in a multijournal context.  If Prof. Plum has an account with access to many journals, and the malicious journal manager only has access to one journal (in which Prof. Plum is registered), this could result in privilege escalation.

**Comment by crism** [comment]
Weird… I think the `LoadHandler` hook doesn’t fired if the plugin is enabled site-wide. Any ideas, @ctgraham?

**Comment by ctgraham** [comment]
I haven't played with the `LoadHandler` hook in the context of a `plugins.auth` plugin before.  I'm just back from vacation today and catching up on things, but I'll have a dev sprint tomorrow where I could look at this and confirm your interpretation.

You're just working with the [issue-1963 branch](https://github.com/UIUCLibrary/pkp-lib/tree/issue-1963) within pkp-lib?

**Comment by crism** [comment]
Yes, all the work is contained within that branch. Right now, the `LoadHandler` handler is a stub, but debugging code on the server shows it as not even registered.

**Comment by asmecher** [comment]
@crism, is it possible that your plugin isn't registered? Make sure there's an entry in the `versions` table.

**Comment by asmecher** [comment]
Also, I forget the details of the auth plugin lifecycle, but it could be that this plugin category is loaded *after* the `LoadHandler` hook is called.

**Comment by ctgraham** [comment]
A plugin which only exists in the shared library cannot be registered by the `Installer::addPluginVersions()` function.

`Installer::addPluginVersions()` calls `PluginRegistry::loadCategory()`, and `PluginRegistry::loadCategory()` enumerates only plugins from the application:
https://github.com/pkp/pkp-lib/blob/f3f43817f4da2e42785f137f81692729d9b42345/classes/plugins/PluginRegistry.inc.php#L113-L125

To this point, each shared plugin consists of a base class in the shared library, and an implementing class in the application.

Creating a stub plugin in the application which inherits this shared library plugin allows it to be registered; the stub plugin name must match the expectations of `PluginRegistry::_instanciatePlugin()`; 
 specifically, the directory must be named exactly like the "application" name in the version.xml,with either an index.php wrapper or an "inc.php" file with the CamelCased version of the application name from version.xml, plus the plugin category, plus the keyword "plugin".

https://github.com/pkp/pkp-lib/blob/f3f43817f4da2e42785f137f81692729d9b42345/classes/plugins/PluginRegistry.inc.php#L221-L238

This gets us closer, but is still not enough to catch the `LoadHandler` hook.

Generic plugins get special treatment in the Dispatcher which allows them to be registered early enough use the `LoadHandler`:
https://github.com/pkp/pkp-lib/blob/f3f43817f4da2e42785f137f81692729d9b42345/classes/core/Dispatcher.inc.php#L132

Perhaps auth plugins like this in the application should really inherit from generic plugins in the shared library?  Or perhaps we could just add another special call out to `PluginRegistry::loadCategory('auth', true);` in the Dispatcher?

**Comment by crism** [comment]
Debugging shows that `ShibbolethAuthPlugin::register()` is definitely called; if I uncheck the active box and recheck it, it is called each time (once with `getEnabled() == false`, once `true`). Also, FWIW, I am testing this plugin by uploading it through the dashboard, rather than from git pulls; don’t know if that makes a difference for handlers firing. I’ll keep tracing this down, but it looks like @ctgraham is probably on the right track.

**Comment by ctgraham** [comment]
If you upload the plugin via the UI, won't it end up in the application area rather than the shared library area?  Or do you get to choose?

**Comment by crism** [comment]
@ctgraham, yes, it does go into the shared area. There don’t seem to be any non-relative path dependencies, though, so it _shouldn’t_ matter where the plugin lives. (In particular, the callback registration uses `array($this, 'handleRequest')`.)

**Comment by ctgraham** [comment]
`PluginHelper::installPlugin()` and `PluginHelper::upgradePlugin()`, contra `Installer::addPluginVersions()`, will successfully register a new plugin, regardless of whether it is in the shared library, application, or both.
https://github.com/pkp/pkp-lib/blob/f3f43817f4da2e42785f137f81692729d9b42345/classes/plugins/PluginHelper.inc.php#L135
and
https://github.com/pkp/pkp-lib/blob/f3f43817f4da2e42785f137f81692729d9b42345/classes/plugins/PluginHelper.inc.php#L254

This points to `Installer::addPluginVersions()` needing to be aware of shared-library only plugins.  But will this play nicely with all existing plugins?  Hmmmm.... 

Regardless, you particular problem of the `LoadHander` callback being missed is strictly related to `Dispatcher::dispatch()`'s preference for only generic plugins.

**Comment by crism** [comment]
To clarify [my previous post](#issuecomment-314132240), `ShibbolethAuthPlugin::register()` is called when actually registering the plugin, but is not called for random page visits, unlike for generic plugins, as @ctgraham notes. Is it unnecessary overhead to ping every single registered plugin for every page load? Should I be barking up a different tree in trying to capture the return visit after Shibboleth authentication? (In 2._x_, this was handled by the built-in [`PKPLoginHandler::ImplicitAuthReturn()`](https://github.com/pkp/pkp-lib/blob/ojs-2_4_8-2/pages/login/PKPLoginHandler.inc.php#L84-L95), not by a plugin.)

**Comment by ctgraham** [comment]
Are you suggesting a hook dedicated to authentication plugins somewhere different than in `Dispatcher::dispatch()`?  Certainly every page load needs to ping every authentication plugin, as it needs to ping every generic plugin, so I was assuming the calls would be parallel.  I'm up for taking a look at your thoughts if you want to propose a new dedicated authentication hook.

**Comment by crism** [comment]
@ctgraham, should `Dispatcher::dispatch()` only call generic and authentication plugins? Or should it also look at block plugins, citation plugins, etc.? When expanding from 1 to 2, I always wonder if we should not instead expand from 1 to many.

**Comment by ctgraham** [comment]
@asmecher can correct me, but I think the original idea was that plugins would only be instantiated as needed, but then "generic" plugins could be special (and would be instantiated super early so that they could modify other functionality).

I feel ambivalent about this.  Having this special functionality of the generic plugins has caused them to be overused as a category, and extending early instantiation to any plugin that configures it could be beneficial.  It also might be overkill.

I was considering the suggestion of making auth plugins inherit from a generic plugin as a compromise position, but I could also be talked into backing the idea of giving all plugins this function, or making both generic and auth plugins "special".

**Comment by asmecher** [comment]
@ctgraham's summary is correct. The `generic` plugin category is enough gun to shoot yourself in the foot with; the other categories should have more specific interactions and lifecycles.

The `auth` category is needing (and getting) an overhaul, so if you need more capabilities than it current provides, go ahead and add them (e.g. earlier loading). If your requirement is likely to be a one-off and not typical for all plugins, then consider coding it as a `generic` plugin that registers its own `auth` plugin as part of the bargain (there are examples of other plugins doing this sort of thing, e.g. the web feed plugin).

I would not want us e.g. to have all plugins loaded early in the request cycle, because there are so many and the overhead would be so high. One way to reduce this is to continue shifting plugins out of the main codebase and into their own repos (and not distributing them with the app), but I'd still hesitate to promote plugin loading so early in general.

**Comment by crism** [comment]
I was starting to lean toward having an additional generic plugin anyway. It looks like a lot of user-specific calls check for an `AuthSource` for the user and load something appropriate, but for the initial login and registration, that obviously doesn’t work. Implicit authentication, broadly, could maybe be a generic plugin, that auth plugins other than Shibboleth could make use of?

**Comment by asmecher** [comment]
@crism, I think you could certainly make a case for removing the auth plugin category entirely and implementing specific ones as generic plugins. It's unlikely we'd ever have more than say 2 or 3 of them, for one thing.

**Comment by crism** [comment]
Next challenge… It’s now a generic plugin. The settings are only available per-journal, though; no Settings link is offered on the site-wide plugins. When I try to use per-journal settings, I get `##user.authorization.pluginLevel##`. I’ll investigate, but if either of you know what’s going on, off the top of your collective head…

**Comment by crism** [comment]
And the next challenge… in 2._x_, [`Validation::login()`](https://github.com/pkp/ojs/blob/ojs-2_4_8-2/classes/security/Validation.inc.php#L23-L120) called the `ImplicitAuthPlugin::implicitAuth` hook with an unset user; the Shibboleth plugin would set the user (or not) and return. I don’t want to reimplement all of the new `Validation::login()`—seems inappropriate, not to mention annoying.

@asmecher, @ctgraham, what do you think is the best way to modify `Validation` to have a way to say, “trust me, this user’s legit”?

**Comment by ctgraham** [comment]
You make a user legit by directly interacting with the [`SessionManager`](https://github.com/pkp/pkp-lib/blob/3bbe4f146f3e264b070101cb1cd3c3bbbc5c1135/classes/session/SessionManager.inc.php) and [`Session`](https://github.com/pkp/pkp-lib/blob/3bbe4f146f3e264b070101cb1cd3c3bbbc5c1135/classes/session/Session.inc.php) to [`Session::setUserId()`](https://github.com/pkp/pkp-lib/blob/3bbe4f146f3e264b070101cb1cd3c3bbbc5c1135/classes/session/Session.inc.php#L70-L87)

**Comment by crism** [comment]
OK! This now executes a successful login by UIN or e-mail address. Still needs to register a new user and hijack all the login affordances, plus I want to play with the implications of site-wide settings a bit.

**Comment by crism** [comment]
New user registration tested and confirmed.

**Comment by crism** [comment]
Problem: `signOut()` redirects to the login page, which the Shibboleth plugin hijacks, logging the user right back in again. @asmecher, @ctgraham, what do you think? It seems to me that overriding `LoginHandler::signOut()` with a redirect to the context home page is the way to go.

**Comment by ctgraham** [comment]
"Log Off" isn't really relevant to Shibboleth, unless your IdP supports centralized logout and all SPs support logout callbacks.  I've not yet met an implementation which does; does yours?  My instinct would be to give an option to suppress the "Log Off" option by default.  If not suppressed, the plugin should require a URI for log off, overriding the normal signOut function as you suggest.

**Comment by crism** [comment]
I’m not entirely sure why I’d want to sign out of OJS with or without Shibboleth, honestly, but clearly someone wants to, maybe in a shared computer situation? Anyway, the plugin hijacks `signOut`, logs the user out of OJS (but not Shibboleth) and takes them to the current context home page. I didn’t consider logging out of Shibboleth, but that’s a possibility.

**Comment by asmecher** [comment]
I'm not totally sure about this, but as I recall there's a URL available to Shibboleth endpoints that you can redirect to where logout can be provided at the provider level.

**Comment by crism** [comment]
@asmecher, yes, we could hit the Shibboleth logout and come back to the current page. What I have here is Good Enough for our uses, but that would be a good enhancement. There’s some other workflow stuff—login goes to the context home, which surprised one of my testers (was on the submissions page, expected (reasonably) to come back to it)—might make good fodder for the sprint.
