### ISSUE TITLE
[OJS] Access denied

### ISSUE THREAD

**Issue by lclaudius** [pkp/pkp-lib#1965]
I'm creating a new journal on OJS 3.0.0 (Ubuntu 16.04, php5.6, postgresql 9.5). When I log in with the main admin account to make some configuration change, the management pages pop out messages about the present role lacking authorization for the page, and then "access denied". My name still appears on the top bar. If I click on "profile", I'm taken to the login page again, and then I'll be able to use the management pages.

**Comment by WaDelma** [comment]
Did you keep the page open for long? There is limited time how long session lasts without doing anything.

**Comment by lclaudius** [comment]
No, WaDelma. Logged in, went straight to the management pages, and got the error message. Only after logging in again I'm able to use the management pages.

**Comment by asmecher** [comment]
Do you have the `session_check_ip` option enabled in `config.inc.php`? If so, try disabling it -- it may be that your IP address is changing (e.g. if it's behind a proxy bank of some kind), which would cause OJS to reject the session when that option is enabled.

**Comment by lclaudius** [comment]
Good call, asmecher! It was indeed on. I'm using a fixed IP, but the OJS server is behind Cloudflare. I disabled the session_check_ip option and now it's working. Thanks!
