### ISSUE TITLE
[OJS] Correct and Clean Up EndNote Citation Export

### ISSUE THREAD

**Issue by mchladek** [pkp/pkp-lib#1966]
This is following up on this discussion from the PKP Forum: <http://forum.pkp.sfu.ca/t/ojs-how-to-cite-endnote-export-issue-year-instead-of-journal-name/12113>

There seems to be a number of inaccuracies with the tags used when exporting a citation to the EndNote `.enw` file format. These include the following:

1. The `%B` tag is meant to be a secondary title but is currently filled with the publication year. This causes EndNote to incorrectly import the journal name. It erroneously imports the publication year as the journal name.
2. The `%9` tag is meant to be for the type of work but provides keywords instead, which means it duplicates the already present `%K` tag.
3. The `%!` tag is meant to be for a short title but right now it fills in the article's full title, duplicating what's already present in the `%T` tag.
4. The `%7` tag is meant to be the edition number but currently it is filled with the issue publication date. The `%8` tag, which is the full publication date of the article is probably sufficient.
5. The `%P` tag for pages is incorrectly filled. Currently, OJS fills two tags: The `%&` for the starting page and then it tries to calculate the total number of pages, filling the `%P` tag with that number. However, the `%&` tag is meant for the section number, not page number. And EndNote expects the `%P` tag to be a page range.

What the tags are meant to represent is based on the EndNote X1.0.1 User's Guide from Thomson.

**Comment by asmecher** [comment]
Many thanks, @mchladek!

**Comment by asmecher** [comment]
Also cherry-picked to `ojs-stable-3_0_0`.
