### ISSUE TITLE
Smarty typos in tab/settings/appearance/form/ templates

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1976]
There are some minor typos which prevent HTML ids from being populated correctly.

Missing smarty delimiters:
https://github.com/pkp/pkp-lib/blob/b2f2c999c5f41070507627488e68cafc7c953d37/templates/controllers/tab/settings/appearance/form/favicon.tpl#L16
https://github.com/pkp/pkp-lib/blob/b2f2c999c5f41070507627488e68cafc7c953d37/templates/controllers/tab/settings/appearance/form/homepageImage.tpl#L16

Missing quotes:
https://github.com/pkp/pkp-lib/blob/b2f2c999c5f41070507627488e68cafc7c953d37/templates/controllers/tab/settings/appearance/form/stylesheet.tpl#L16

**Comment by asmecher** [comment]
Merged and cherry-picked around, thanks!
