### ISSUE TITLE
[OJS] Slow SQL query due to unnecessary join

### ISSUE THREAD

**Issue by mdmstw** [pkp/pkp-lib#1979]
Version: OJS 2.4.8.0 (also in 2.4.8.1)
File: classes/submission/sectionEditor/SectionEditorSubmissionDAO.inc.php
Line: 836

Line 836 contains an unnecessary and redundant JOIN which causes the query to run quite slowly (30 seconds as opposed to 0.2 seconds with a system of several thousand users and tens of thousands of review_assignments).

Lines 836 and 837 are both joining the same review_assignments table, but the alias "ra" in the join on line 836 is not actually used anywhere further in the query, making that particular join unnecessary and quite large.

Line 839 also joins the articles table and appears to be unnecessary as it is also not used further in the query.

**Comment by ctgraham** [comment]
+1.  Seems sound.  Do you have interest in making a pull request?

**Comment by mdmstw** [comment]
I don't currently have an interest in making a pull request, but wanted to simply notify any active (or official) maintainers for possible correction in a future patch. I very rarely work with the OJS code and am not terribly familiar with the system in its entirety. Thank you, though.

**Comment by ctgraham** [comment]
This is the place for the notification.  We'll take care of it.  Thanks.

**Comment by bozana** [comment]
PR https://github.com/pkp/ojs/pull/1351 is merged, can the issue be closed?
