### ISSUE TITLE
Review form button placement

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1980]
In many places, forms include a Cancel button on the left and a Submit button on the right. On (not unusually) large displays this may mean the Submit button gets pushed to the bottom right of the screen, where it can be easily overlooked.

See e.g. the Reviewer's interface.

Should the buttons be kept closer together?

**Comment by asmecher** [comment]
(@NateWr, I suspect the answer is "yes", but assumptions etc. etc.)

**Comment by NateWr** [comment]
This is something I've noticed as well. And a general problem is that save buttons get lost on our big, page-wide forms (eg - Settings > Appearance). I think this is an area to think about when we get around to refactoring the FBV.

A similar problem exists with action links in grids on large screens.

**Comment by NateWr** [comment]
I think that this is addressed in the UI refactor at #5865.
