### ISSUE TITLE
Some notification emails sent out with empty recipient list

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1989]
See e.g. ` NOTIFICATION_TYPE_EDITOR_ASSIGNMENT_SUBMISSION`, which is sent out from `PKPSubmissionSubmitStep4Form.inc.php` when a submission is assigned to an editor upon receipt:

                // Update assignment notifications
                import('classes.workflow.EditorDecisionActionsManager');
                $notificationManager->updateNotification(
                        $request,
                        EditorDecisionActionsManager::getStageNotifications(),
                        null,
                        ASSOC_TYPE_SUBMISSION,
                        $this->submission->getId()
                );

Note that no specific user is assigned to this notification.

This is handled by `EditorAssignmentNotificationManager.inc.php` (see the `updateNotification` function). Again, no specific users are expected by the function (the `$userIds` parameter goes unused).

This appears to be fine for the sake of the notification, but when it comes time to send the notification email, the recipient is not set so the email is sent with an empty recipient list.

This appears to affect all notifications that use a `null` value for `$userId` in calls to `createNotification`.

**Comment by bozana** [comment]
@asmecher, do you know/could you tell me when the emails are sent out, for which notifications, and where to look for it? I will search by myself and report if I figure it out...

**Comment by bozana** [comment]
In https://github.com/pkp/pkp-lib/blob/master/classes/notification/form/PKPNotificationSettingsForm.inc.php the notification types are defined that every user can subscribe to i.e. unsubscribe from. When a notification is created here https://github.com/pkp/pkp-lib/blob/master/classes/notification/PKPNotificationOperationManager.inc.php#L155, it will be checked if the user unsubscribed from that notification and if not, the notification e-mail will be sent, s. https://github.com/pkp/pkp-lib/blob/master/classes/notification/PKPNotificationOperationManager.inc.php#L172-L176.
That means for all other notification types that are not in PKPNotificationSettingsForm, the email will be sent by default (when parameter `$suppressEmail = false`). Thus also for the notification type above `NOTIFICATION_TYPE_EDITOR_ASSIGNMENT_SUBMISSION`.
Some notification types are defined to be visible for all, e.g. those managed by `EditorAssignmentNotificationManager`, s. https://github.com/pkp/pkp-lib/blob/master/classes/notification/managerDelegate/EditorAssignmentNotificationManager.inc.php#L54-L56. So I am not sure what does this "visible for all users" mean and why are they visible for all users? In that case, the `userId` in the `notifications` table is considered to be `null`. Thus I am not sure if this "visible for all users" can be separated from the e-mails -- for example: can we have "visible for all users" but also concrete `userIds` (`!= null`) in the DB table?
I will then try to insert appropriate userIds, regardless of this "visible for all users", when creating notifications here https://github.com/pkp/pkp-lib/blob/master/classes/notification/managerDelegate/EditorAssignmentNotificationManager.inc.php#L93-L95, like this: NOTIFICATION_TYPE_EDITOR_ASSIGNMENT_SUBMISSION, NOTIFICATION_TYPE_EDITOR_ASSIGNMENT_INTERNAL_REVIEW and NOTIFICATION_TYPE_EDITOR_ASSIGNMENT_EXTERNAL_REVIEW shall consider all journal editors, and NOTIFICATION_TYPE_EDITOR_ASSIGNMENT_EDITING and NOTIFICATION_TYPE_EDITOR_ASSIGNMENT_PRODUCTION shall only consider the assigned editors. Is this OK so? -- I am orienting myself on those notification messages here https://github.com/pkp/pkp-lib/blob/master/classes/notification/managerDelegate/EditorAssignmentNotificationManager.inc.php#L31-L42, which I am not sure are correct?

**Comment by bozana** [comment]
Hmmm... one more question: for the first 3 notification types i.e. when a submission is not assigned yet, which roles should be considered: only ROLE_ID_MANAGER or maybe also ROLE_ID_SECTION_EDITOR? And ROLE_ID_GUEST_EDITOR?

**Comment by bozana** [comment]
The notification types mentioned here can have a user -- it makes sense. I will also check for the others that currently have userId = null, but shall we maybe also consider something like `if userId == null then do not send email`, in such a case?

**Comment by bozana** [comment]
And now, that I had a look at the function sendNotificationEmail, if there is no user, the e-mail should not be set, s. https://github.com/pkp/pkp-lib/blob/master/classes/notification/PKPNotificationOperationManager.inc.php#L438. How is this then possible?

**Comment by bozana** [comment]
Well, after testing all this now, I think there is no such problem :-) If there is no user the email will not be send. Thus, @asmecher, are you sure you have seen this issue occur? Maybe it is something else?

**Comment by asmecher** [comment]
Thanks, @bozana, it looks like you're right -- I missed that check. I've asked for more information.

**Comment by bozana** [comment]
I've just spoken with Carola, and I think this is not the issue, so it can be closed. 
We realized that the notification NOTIFICATION_TYPE_SUBMISSION_SUBMITTED does not necessarily goes to all managers, which was expected and wished. The notification will be created only if there is no section/series editor and not only one/single user with the role ROLE_ID_MANAGER. Which is OK i.e. not buggy behavior. If it is wished, for some users to always be informed about new submissions, the following journal/press setting should be used: `Settings > Workflow > Submission > Notification of Author Submission > input field "Send a copy to this email address"`.

The other thing is the question how are the profile notification settings supposed to work -- they guilt only for the users connected with a notification, if the notification is generated and they are actually there for an opt-out possibility, right? For example, if NOTIFICATION_TYPE_SUBMISSION_SUBMITTED is created, it is associated with all managers and all of them will get the notification and email, except if they configured it differently on their profile notification settings page. This again is OK i.e. not buggy behavior, maybe it could be just explained on the top of the profile notification settings page, because the people expect to be always notified.

And a different issue, that I will take a look now: it seems that authors are not informed when a submission is sent to copyediting and production, but it is wished so.

**Comment by bozana** [comment]
OK, we figured out what is going on for the e-mails that should be send by editors when clicking on "Send To Copyediting" and "Send To Production" -- they are not send if the author user is the same user as manager or editor, which might be right decision: here, only users with ROLE_ID_AUTHOR are searched for: https://github.com/pkp/pkp-lib/blob/master/controllers/modals/editorDecision/form/EditorDecisionWithEmailForm.inc.php#L211. Therefore if the manager/editor did a submission (in their manager/editor role and not explicit author role) they will not be found there in the search above and the e-mail will have no recipients and will not be send. This is maybe OK so, @asmecher ?

Another problem: the e-mail SUBMISSION_ACK_NOT_USER is not send upon a submission (in the submission step 4), if there is only one author and the submitter is that author, s. https://github.com/pkp/omp/blob/master/classes/submission/form/SubmissionSubmitStep4Form.inc.php#L55 and https://github.com/pkp/omp/blob/master/classes/submission/form/SubmissionSubmitStep4Form.inc.php#L74. Here again, in this case, there will be no recipient and the e-mail will not be sent. Thus the primary contact and e-mail address as specified in the journal/press submission settings will not be informed about the new submission, which is not good. This e-mail template is meant to be sent to other authors: "This email, when enabled, is automatically sent to the other authors who are not users within OMP specified during the submission process.". But if there are no other authors, it should be still send to the primary contact and e-mail address `copySubmissionAckAddress` as defined in submission settings. Would you agree @asmecher? If so, I will open a new issue for that and close this one :-)

**Comment by asmecher** [comment]
Thanks @bozana!

> This is maybe OK so, but maybe it would be better to just get all submission authors, as it is done for the template/form display -- this way all authors that the editor sees in that template will be also for real notified. What do you think @asmecher?

Yes, I agree that this is a better approach -- it would also resolve the problem of emails getting generated with empty recipient lists, which is a bug (and not just a policy).

> Another problem: the e-mail SUBMISSION_ACK_NOT_USER...

Wouldn't the `SUBMISSION_ACK` email template meet that requirement already?

**Comment by bozana** [comment]
> Wouldn't the SUBMISSION_ACK email template meet that requirement already?

Yes, it has the current user i.e. the submitter as recipient i.e. it always has a recipient. Shall this email template then be sent to the primary contact and specified e-mail address in the submission settings, although the e-mail text is then slightly different?

**Comment by asmecher** [comment]
Hmm, I don't have a strong preference here. Note that I just added the `SUBMISSION_ACK_NOT_USER` email template to git -- it was missing (never ported from OMP). On balance, I'd suggest using the `SUBMISSION_ACK` email.

**Comment by bozana** [comment]
PRs:
a) https://github.com/pkp/pkp-lib/pull/2012
b) 
ojs: https://github.com/pkp/ojs/pull/1107
omp: https://github.com/pkp/omp/pull/359

@asmecher, could you take a look at the PRs?

**Comment by asmecher** [comment]
Thanks, @bozana, this looks good. Additional authors might find the emails confusing if e.g. they haven't been assigned for workflow access, but we'll see if feedback bears that out. Go ahead!

**Comment by bozana** [comment]
Thanks @asmecher! Merged. I will then cherry-pick it to ojs-stable-3_0_0, omp-dev-1_2 and omp-stable-1_2_0 and then close the issue...

**Comment by bozana** [comment]
PR i.e. cherry-picks:
a)
ojs-stable-3_0_0: https://github.com/pkp/pkp-lib/pull/2017
omp-stable-1_2_0: https://github.com/pkp/pkp-lib/pull/2016
omp-dev-1_2: https://github.com/pkp/pkp-lib/pull/2015

b)
ojs-stable-3_0_0: https://github.com/pkp/ojs/pull/1109
omp-stable-1_2_0: https://github.com/pkp/omp/pull/360
omp-dev-1_2: https://github.com/pkp/omp/pull/361

**Comment by bozana** [comment]
everything merged, thus closing...
