### ISSUE TITLE
[OJS3] Flaws in registration

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#1996]
#### 1. {$email} not replaced
In the error message for disabled account due to missing activation, the email variable is not resolved.
![screenshot](https://cloud.githubusercontent.com/assets/11337857/20345663/816ff6f4-abf8-11e6-8b79-5e7a92f7eacc.jpg)

#### 2. missing template
On the activation page which is linked in the activation email only a name of the object to show is displayed.
![screenshot](https://cloud.githubusercontent.com/assets/11337857/20345823/2d533e68-abf9-11e6-9b0c-76208cdf7915.jpg)

**Comment by asmecher** [comment]
The attached patches should resolve both issues -- apply them in the `lib/pkp` submodule. All 3 are equivalent, just applied to different branches. Please confirm if this doesn't work for you! Thanks for reporting.
