### ISSUE TITLE
License missed

### ISSUE THREAD

**Issue by naok62** [pkp/pkp-lib#2002]
Hello,
I looked at your project and I noticed the absence of a license file, could I know which you want to use in the project, I would be happy to send my first PR to the project
Thanks  :)

**Comment by asmecher** [comment]
@naok62, which of our applications/repositories are you looking at?

**Comment by naok62** [comment]
Je fais référence au projet  : pkplib

**Comment by asmecher** [comment]
That library (and all the applications that use it) are licensed under the GPL version 2. The license file is distributed in the application, and the pkp-lib library is bundled with it for distribution, hence `docs/COPYING` (the GPL license) is in the application repository but not the pkp-lib repository. Code headers in `pkp-lib` note that it's GPLv2, for what it's worth.
