### ISSUE TITLE
[OJS3] Native XML broken

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#2006]
### 1.
```
Warning: assert(): Assertion failed in /var/www/html/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 110

Fatal error: Call to a member function getUsername() on a non-object in /var/www/html/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 111
```
I get this error message on export of an article out of ojs3. The article was exported from a migrated installation, then imported to a clean installation. Checking `submission_files` table brought me to the conclusion, that **the importer missed to do sanity checks on the specified upload user**, who does not exist in the clean installation. `submission_files.uploader_user_id` is `NULL` for all files of the imported submissions. This explains the above error. There was no error message on import.

### 2.
**Sanity checks are also missing for the `<issue_identification>` part of the xml**. If the issue does not exist in the journal, the importer produces a garbage submission with neither error nor success message on the result tab.
![scr](https://cloud.githubusercontent.com/assets/11337857/20392006/4cf3d010-acd6-11e6-9306-4b8d5ec857f1.jpg)

### 3.
Deleting the above empty submission results in the following. 
![scr](https://cloud.githubusercontent.com/assets/11337857/20392086/9d612b74-acd6-11e6-9a0c-be024b9ce543.jpg)
It does only dissapear after refreshing the page. It is possible that this last point is completely unrelated to the native xml plugin. Possibly this happens on all last unassigned submissions that are deleted.

**Comment by bozana** [comment]
@pkel, the first two issues are considered here https://github.com/pkp/pkp-lib/issues/1709 and will be resolved with the latest PRs, that still have to be code reviewed and merged (s. https://github.com/pkp/pkp-lib/issues/1709#issuecomment-260763039)
Your 3. issue doesn't have to do anything with XML import/export and I added it to other reload issues, s. https://github.com/pkp/pkp-lib/issues/1853#issuecomment-261261225
Thus, if OK, could you please close this issue and track the other two issues for the fixes? 
THANKS!!!
