### ISSUE TITLE
[ojs3][migrate] Can't load pdf.

### ISSUE THREAD

**Issue by OhnO395** [pkp/pkp-lib#2007]
i'm migrate data from 2.4.4-1 to 3.0.1 until finish, but i can't download .pdf file from new web.

old web (can download)
![image](https://cloud.githubusercontent.com/assets/3378704/20418522/cb8b9f7a-ad80-11e6-8a71-5fc9bbd4708c.png)

new web (It a blank)
![image](https://cloud.githubusercontent.com/assets/3378704/20418534/dc70f2ae-ad80-11e6-95a0-695a341e1d3b.png)

how to fix it?

thank you.

**Comment by asmecher** [comment]
@OhnO395, could you post this in the forum (searching first to see if you can find your answer in the posts that are already there)? If it turns out to be a bug, we can move it into this venue. http://forum.pkp.sfu.ca/
