### ISSUE TITLE
[OMP] Bootstrap theme plugin for OMP 1.2

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#2009]
The OJS Bootstrap plugin is fantastic. We’d like to be able to harmonize the design between our OMP and OJS installations… so let’s see if we can port the OJS plugin to OMP!

**Comment by crism** [comment]
@NateWr, @asmecher, @stranack—tagging at Alec’s suggestion.

**Comment by asmecher** [comment]
Thanks, @crism! Are you working with OMP master, `omp-stable-1_2_0`, or `omp-dev-1_2`? Various bits and pieces of the `master` branch have been back-ported to one or both of the other branches, and some remains only in `master`. We'll likely release our next OMP directly from `master`, in line with our plans to bring OMP and OJS together for simultaneous releases and decrease the amount each app suffers when we work on the other.

**Comment by crism** [comment]
We’re currently running `omp-stable-1_2_0`, but can do development against whatever makes sense, as long as there’s a not-too-future stable release we can deploy it with.

**Comment by asmecher** [comment]
What's your timeline for this? It's entirely possible that we'll release from `master` in time.

**Comment by crism** [comment]
Our timeline is ASAP, in a strict literal sense. We can start releasing content with a less-attractive façade, and announce the upgrade to great fanfare. `(-:`

**Comment by NateWr** [comment]
Hi @crism, sounds good! I'd love for someone else to take responsibility for the OMP version. :)

I suppose the question is the best way to manage shared code between the OMP and OJS version. Although there's quite a lot of overlap, to be honest I think where the themes overlap is also where you'll see very little code being changed over time. A lot of it is set-and-forget, like all the bootstrap theme options, headers/footers, user registration, etc.

The real work comes in with the app-specific content. Issues and articles for OJS. Monographs and catalog pages for OMP.

So my initial recommendation would be to create a fork of the OJS theme and completely rename it, then blow away the app-specific stuff with your own. And then we can (hopefully) manually manage changes required within any of the shared code by communicating with Issues in our respective repos.

That may or may not work out great. But I think for now it's a good low-impact way for us to coordinate. And if it becomes more of a problem in the future we can look at better coordinating our release schedules and PR procedures, to ensure the themes stay relatively in-tune with each other.

Does that sound good? Would you like to create a `bootstrap3-omp` repo?

**Comment by crism** [comment]
@NateWr, that’s the direction I was thinking… refactoring will be “fun” afterward.

**Comment by asmecher** [comment]
@crism, I'd suggest working with the master branch. We're unlikely to introduce any "problematic" changes between now and the release of whatever OMP comes next, and the current master branch should be fairly stable (with stability issues expected to be trivial to fix). It'll give us concrete feedback to move us towards an OMP release, and in return, I can help backstop any problems you do encounter with a bit of dev attention.

**Comment by crism** [comment]
Finally bringing my attention back to this… Looking at the default theme plugins for OJS and OMP, there seems to be quite a lot of overlap. So I think making the OMP Bootstrap theme being a fork of the OJS one makes sense—and, in fact, we could refactor the common parts out. I’ll start that approach shortly…

**Comment by asmecher** [comment]
@crism, looking forward to seeing this! Perhaps it's worth eventually calling this a "PKP bootstrap theme" and maintaining separate branches for OJS and OMP applications? I suppose it depends on how much code overlap there ends up being between the two...

**Comment by asmecher** [comment]
@crism, I see that there are some releases over at https://github.com/UIUCLibrary/omp-bootstrap3 -- excellent! Can I close this issue?

**Comment by crism** [comment]
@asmecher, no—no releases yet. It’s barely more than a fork of the OJS bootstrap. This issue is very much still open, sorry.

**Comment by asmecher** [comment]
No apology necessary!

**Comment by NateWr** [comment]
Closing until there is renewed interest.
