### ISSUE TITLE
Consider site-wide search (multi-journal)

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2010]
See http://forum.pkp.sfu.ca/t/ojs-global-search/651 -- apparently the search feature is currently only journal-specific in OJS 3.0. (We used to support global, multi-journal search in OJS 2.x.)

Consider fixing global search, unless there's a good reason not to provide it.

**Comment by ajnyga** [comment]
These are the changed I did to enable site level search in OJS3.

https://github.com/pkp/ojs/blob/master/pages/search/SearchHandler.inc.php#L32
`if ($request->getContext()) $this->addPolicy(new OjsJournalMustPublishPolicy($request));`

https://github.com/pkp/ojs/blob/master/templates/frontend/objects/article_summary.tpl#L15
```
{assign var=articlePath value=$article->getBestArticleId()}
{assign var=journalPath value=$journal->getPath()}
```

https://github.com/pkp/ojs/blob/master/templates/frontend/pages/search.tpl#L71
`{include file="frontend/objects/article_summary.tpl" article=$result.publishedArticle journal=$result.journal showDatePublished=false}`

The templates are in our site level theme plugin. I do not know whether you want to send the `$journal` even when the search is inside one context.

But anyway, the global search can be achieved in OJS3 fairly easily. However, I do not know whether this is a problem in OJS3 as well: https://github.com/pkp/pkp-lib/issues/2272?

**Comment by asmecher** [comment]
Thanks as always, @ajnyga -- mind sending in a PR for some testing/review?

**Comment by ajnyga** [comment]
I made the article summary template conditional because I think it is called from other places as well and $journal will not be available then. I think.

https://github.com/pkp/ojs/pull/1345

Have not checked if https://github.com/pkp/pkp-lib/issues/2272 is something to worry about.

**Comment by asmecher** [comment]
Looks great, thanks! #2272 restricts results from disabled journals from appearing using SQL, so this won't cause problems with that.
