### ISSUE TITLE
Section and published article ordering

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2018]
Published article ordering should be per section and this is not always considered, e.g. when a published article changes section.
The function loadData in TocGridHandler does not consider the custom section ordering plus the section reordering does not function well.
The function setDefaultCustomSectionOrders in SectionDAO consideres all sections and not only those that exist in that issue.
The function moveCustomSectionOrder is not needed any more -- the parameter $up is never used in OJS 3.0 -- the reordering functions in a different way.

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1112

**Comment by bozana** [comment]
@asmecher, could you take a look at this PR?

**Comment by asmecher** [comment]
I haven't tested it, but it looks good, @bozana -- if you've tested it, please go ahead!

**Comment by bozana** [comment]
Thanks a lot @asmecher! I merged it and will cherry-pick it to ojs-stable-3_0_0...

**Comment by bozana** [comment]
Everything merged, thus closing...
