### ISSUE TITLE
OJS 3.0 only works fine with PHP 5.3 (not with 7)

### ISSUE THREAD

**Issue by distriker** [pkp/pkp-lib#2021]
Hi everyone:
I am trying to use OJS 3.0 with PHP 7 but, after many attemps, I have discovered that it just works with PHP 5.3. Do you know how could I solve it or if exist a possibility to make a fork with OJS build-in PHP 7?

Thanks in advance.

Regards

**Comment by WaDelma** [comment]
OJS 3.0 should work with PHP 7. What error you get? Did you remember to switch your database driver to mysqli (Assuming you use mysql)?

**Comment by distriker** [comment]
Hi @WaDelma! Thank you for your answer. The error is:

> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Application has a deprecated constructor in X

[Here you have the full error](https://gist.github.com/distriker/ba8dbc3c971d9cc4e83f6d4bddc17b25).

I have checked in my control panel if I have activated mysqli and yes, it is activated.
Regards

**Comment by WaDelma** [comment]
Note: I haven't tried PHP 7 myself, but based on #1118 it should work.

You should be able to suppress those errors.

**Comment by distriker** [comment]
I have set the driver to mysqli like vodou say, but the errors persists.

**Comment by asmecher** [comment]
@distriker, some tweaks were committed after the release of OJS 3.0. Those should be in the `ojs-stable-3_0_0` branch in git (both the `ojs` repo and the `pkp-lib` submodule). Those fixes will be released shortly in OJS 3.0.1.
