### ISSUE TITLE
Add section to the submission filter form in the editorial back-end

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2022]
See http://forum.pkp.sfu.ca/t/ojs3-browsing-articles-by-section/25002 for details.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/2041
- https://github.com/pkp/ojs/pull/1120
- https://github.com/pkp/omp/pull/363

@kaschioudi, could you review this one?

**Comment by kaschioudi** [comment]
@asmecher : I went through your changes and everything seems fine to me.

**Comment by asmecher** [comment]
Manually merged, thanks!

**Comment by NateWr** [comment]
@asmecher This is getting blown away with the new submissions list panel component I'm introducing. During the rebase, I've kept the `sectionId` parameter in the `SubmissionDAO::getAssignedToUser()` method. So if we want to talk about advanced filters we can do that down the line.

**Comment by NateWr** [comment]
This is address in the PRs attached to #2612. Closing.
