### ISSUE TITLE
[OJS] Unwanted emails are triggered

### ISSUE THREAD

**Issue by mithunjj** [pkp/pkp-lib#2025]
After upgrading to OJS 3.0 from OJS 2.x, lots of mails are triggered to the root user.

<img width="1016" alt="ojs" src="https://cloud.githubusercontent.com/assets/5390465/20552299/90da3e3e-b16f-11e6-9f45-fb68dd5d4789.png">

I had followed this https://github.com/pkp/pkp-lib/issues/1838#issuecomment-251711066

But in vain.

Please help me with a fix.

**Comment by asmecher** [comment]
@mithunjj, could you post this in our [support forum](http://pkp.sfu.ca/support/forum/) rather than here? If it turns out to be a new bug, we'll migrate it to an entry here instead.
