### ISSUE TITLE
Plugin - "Hosted By PKP|PS" Block

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2035]
This shouldn't be shipped with the release. This should only be available to PKP|PS staff.

**Comment by asmecher** [comment]
I don't think it is shipped within OJS. Where are you seeing it?

**Comment by stranack** [comment]
http://journals.sfu.ca/capetown2016/index.php/cjsa/management/settings/website

OK, it might be part of the PKP|PS installation script.

**Comment by asmecher** [comment]
Yep, I think so!
