### ISSUE TITLE
Website Settings > Appearance > Lists

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2037]
Could we consider getting rid of the lists configuration? 

It is used much less now (e.g., Emails), users can configure the Items per Page on the list itself now, and the configuration option has always been confusing for users during initial setup.

Also, the Page Links doesn't seem to work. I set it to "3", saved, but the email list still had 7 page links.

**Comment by jmacgreg** [comment]
We're running into the same issue with a hosted client. I'd be in favour of getting rid of this GUI option as well as the config.inc.php parameters as well. Right now they appear to apply inconsistently to lists like the Archive (where I think only the config.inc.php parameter is applied for some reason). I think there's a general disconnect about whether this option should affect the backend or the frontend. I think the backend is taking care of itself, and the frontend could be left to theme implementers.

**Comment by NateWr** [comment]
Agreed.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
