### ISSUE TITLE
OJS update to 3.0.1-0 fails due INSERT

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#2038]
For my installation the upgrade from 3.0.0 to 3.0.1-0 failed. Problematic was a unique key violation during the inserts in `dbscripts/xml/upgrade/3.0.1_update.xml`. Both plugins already had an entry.
Replacing `INSERT` with `INSERT IGNORE` fixes the problem.

```
INSERT INTO plugin_settings (plugin_name, setting_name, setting_value, setting_type, context_id) SELECT 'googlescholarplugin', 'enabled', '1', 'bool', journal_id FROM journals
INSERT INTO plugin_settings (plugin_name, setting_name, setting_value, setting_type, context_id) SELECT 'dublincoremetaplugin', 'enabled', '1', 'bool', journal_id FROM journals
```

**Comment by asmecher** [comment]
@pkel, this is probably because you had a pre-release version of OJS 3.0.1 installed (or manually installed those plugins). Your work-around is fine, but because `INSERT IGNORE` is a MySQL-specific SQL extension (and not supported e.g. under PostgreSQL) we're unlikely to merge it in.
