### ISSUE TITLE
Role selection in other journals on user profile page broken

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2039]
When a user access their user profile page from within a journal context, role selection for other journals is hidden in a RevealMore UI control. However, no other journals are ever listed, even when they should be.

This could be a bug introduced with #1847.

**Comment by asmecher** [comment]
@NateWr, mind if I leave this one with you?

**Comment by NateWr** [comment]
This was a bug introduced with #1847.

PR:
https://github.com/pkp/pkp-lib/pull/2225

TESTS ONLY:
https://github.com/pkp/ojs/pull/1207

**Comment by NateWr** [comment]
Tests passed. @asmecher I'll assign this one to you for code review.

**Comment by asmecher** [comment]
Looks good -- thanks, @NateWr.

**Comment by asmecher** [comment]
Also cherry-picked to `ojs-stable-3_0_1`.
