### ISSUE TITLE
Add theme api methods for manipulating parent scripts, styles and options

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2042]
Child Themes should be able to de-register scripts, styles and options from a Parent Theme.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2043

Tests Only:
https://github.com/pkp/ojs/pull/1121

**Comment by asmecher** [comment]
Don't forget to assign someone to review these when they're ready!

**Comment by NateWr** [comment]
Yes sir! You win! :)

Rebased and ready for code review.

**Comment by asmecher** [comment]
Merged, thanks!
