### ISSUE TITLE
Article cover images don't appear in search results

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2044]
Article cover images aren't displayed in search results because the template variable, `$coverImagePath`, used in `/templates/frontend/objects/article_summary.tpl`, is only available in the issue templates.

We can add this variable to the search templates, but it won't work if we ever decide to add site-wide, cross-journal searching.

I'd like to add a new method to `Article` and `Issue` objects, `getLocalizedCoverImageUrl()`:

```php
	/**
	 * Get a full URL to the localized cover image
	 *
	 * @return string
	 */
	function getLocalizedCoverImageUrl() {
		$coverImage = $this->getLocalizedCoverImage();
		if (!$coverImage) {
			return '';
		}

		$request = Application::getRequest();

		import('classes.file.PublicFileManager');
		$publicFileManager = new PublicFileManager();

		return $request->getBaseUrl() . '/' . $publicFileManager->getJournalFilesPath($this->getContextId()) . '/' . $coverImage;
	}
```

This will ensure that we can get a valid URL to the cover image regardless of what context the current request eminated from.

Any objections?

**Comment by NateWr** [comment]
PRs (tests running):
https://github.com/pkp/ojs/pull/1122
https://github.com/NateWr/bootstrap3/pull/46

**Comment by NateWr** [comment]
Tests passed! @bozana, can you code review?

**Comment by bozana** [comment]
All well @NateWr :-) You can then merge it after a rebase. 
Just that I don't know why do you have that submodule commit...

**Comment by NateWr** [comment]
Thanks @bozana! All merged. Closing.
