### ISSUE TITLE
[OJS]  Submission notes visible for authors in OJS 3.0

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2047]
If I have understood correctly, submission notes should only be visible for editorial staff?

However, If I log in with an author role and look for my submission on the "My authored" list, I can access the submission notes by clicking the blue triangle => "More information".

This gives me an error "The current role does not have access to this operation.", but after clicking OK and again OK for another dialog box I can see the History tab (it does not load anything) and the Notes tab. Clicking the Notes tab does not give any errors and it shows the notes the editor has added.

So, my question: should this be happening, probably not?

I am using OJS 3.0.0

**Comment by NateWr** [comment]
I've just been digging into notes a bit. Whoever deals with this, the role assignment is here:

https://github.com/pkp/pkp-lib/blob/master/controllers/informationCenter/InformationCenterHandler.inc.php#L33-L41

There are child classes of `InformationCenter` you'll want to double-check for permissions too.

**Comment by asmecher** [comment]
PRs:

- https://github.com/pkp/pkp-lib/pull/2213
- https://github.com/pkp/omp/pull/382
- https://github.com/pkp/ojs/pull/1200

**Comment by asmecher** [comment]
@bozana, mind taking a look at these PRs?

**Comment by bozana** [comment]
@asmecher, it looks good -- it can be merged and cherry-picked (if necessary)...

**Comment by asmecher** [comment]
Merged, thanks!
