### ISSUE TITLE
Add setting for site-wide Google Analytics tracking

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2048]
See http://forum.pkp.sfu.ca/t/where-can-i-put-the-id-of-google-analytics/25818 for details.

**Comment by ctgraham** [comment]
I'm working on this within the context of https://github.com/pkp/pkp-lib/issues/1923 .

This should most certainly *not* be a config.inc.php setting.

**Comment by asmecher** [comment]
@ctgraham, gotcha -- that's just been a convenient fallback based on the OJS 2.x site/journal config division. Improvements welcome of course.

**Comment by asmecher** [comment]
@ctgraham, should we defer this one to the next release (OJS/OMP 3.1.1)?

**Comment by ctgraham** [comment]
Yes, I'm not going to catch up with this until after we exit reporting hell here locally.

**Comment by NateWr** [comment]
@ctgraham would you like to remain assigned to this?

**Comment by ctgraham** [comment]
Unassigned.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.

**Comment by fgnievinski** [comment]
just double checking if the site-wide Site setting shouldn't be removed in favor of the journal Website setting?
https://forum.pkp.sfu.ca/t/google-analytics-code-problem-for-ojs-server/7502/7
