### ISSUE TITLE
Don't expose front-end URLs via OAI when publishing disabled

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2050]
See http://forum.pkp.sfu.ca/t/oai-pmh-and-access-to-journal-content-in-ojs-3-0/25809/3 for details.

**Comment by bozana** [comment]
Maybe this journal option should also be considered for issue and articles display in any case? -- I.e. if there are some "published" issues and articles in such a journal (with this setting option) and if someone knows the URLs, the content is displayed...

**Comment by asmecher** [comment]
Duplicate of https://github.com/pkp/pkp-lib/issues/4149.
