### ISSUE TITLE
[OJS]Add new step in submission

### ISSUE THREAD

**Issue by firas4431** [pkp/pkp-lib#2054]
hi

i need to add new step to the 5 steps in the submission the file and the result come and see in the editor and section Reviewers in ojs "in result become 6 steps" because the policies of the journal need that,
i can create the form in new step and store the data in table in db but i can't insert this step in five step and also can't put the link to this information in editing page and section Reviewers

how can do this please
now i use system V. 2.4.8.1

thank you from first

**Comment by bozana** [comment]
Are you just changing and adding the code or developing this in a plugin? Also, could you maybe try to better explain what exactly you would like to do, where to put/insert what? I think this question would better fit in the support forum, that in the GitHub Issues...

**Comment by ctgraham** [comment]
See: http://forum.pkp.sfu.ca/t/add-new-step-in-submission/25895

**Comment by bozana** [comment]
Ah, thanks @ctgraham, thus the issue can be closed...
