### ISSUE TITLE
[OJS] Uploaded files are sometimes missing from filesystem

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#2055]
With version 3.0.0-0… a user is uploading images associated with articles. For some reason, the user tries to upload a redundant copy of an image, which OJS guesses is a revision of the first image, and creates a new revision in the database. However, no file is created in the filesystem, which leads to later errors, as there is no file with the calculated filename.

I’m working with the user to characterize exactly what steps lead to the problem.

**Comment by crism** [comment]
It looks like this was triggered by very similarly-named illustrations. _E.g._, user uploads `illustration with long name 1.jpg`, and all is well. User then uploads `illustration with long name 2.jpg`; OJS presumes by the similar filename that this is a revision of the first file. The user, not facile with OJS yet, doesn’t notice and proceeds.

Obviously, that wouldn’t produce the desired results, and the UI could be clearer about it. However, the fact that it results in missing files and broken behavior downstream (#2056) is puzzling.

**Comment by NateWr** [comment]
The "possible duplication or revision detected" behaviour has been removed in 3.3.
