### ISSUE TITLE
[OJS] missing files cause crashes and other bad behavior

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#2056]
With version 3.0.0-0… as reported in #2055, sometimes a file is not present on the filesystem, though there is an entry for it in the database. Attempting to download or view the files causes a 500 Internal Server Error. Promoting a submission to review causes the missing files to be skipped. Errors are logged on the server, but the user is left with little information to act on (in this case, attempting multiple times to promote to the submission to review). The file promotion appears to stop with the first bad one it finds, skipping other files which are present on the filesystem.

**Comment by NateWr** [comment]
The file download code was refactored in 3.3 and missing files now result in a 404. The file promotion code will be refactored in 3.4 as part of #7265. Closing as outdated.
