### ISSUE TITLE
[OMP] Featured and New release checkboxes failing

### ISSUE THREAD

**Issue by cziaarm** [pkp/pkp-lib#2057]
Hello,

Just tried this on a newly installed OMP with a single monograph submitted. Trying to use the "featured" or "new relase" check box on http://..../index.php/test/manageCatalog results in the error below.

Thanks,

Rory

PHP Fatal error:  Call to a member function getId() on a non-object in /home/cziaarm/PKP/OMP-VENDOR/controllers/grid/manageCatalog/CatalogMonographsGridHandler.inc.php on line 194, referer: http://192.168.171.150/index.php/test/manageCatalog
 PHP Stack trace:, referer: http://192.168.171.150/index.php/test/manageCatalog
 PHP   1. {main}() /home/cziaarm/PKP/OMP-VENDOR/index.php:0, referer: http://192.168.171.150/index.php/test/manageCatalog
 PHP   2. PKPApplication->execute() /home/cziaarm/PKP/OMP-VENDOR/index.php:64, referer: http://192.168.171.150/index.php/test/manageCatalog
 PHP   3. Dispatcher->dispatch() /home/cziaarm/PKP/OMP-VENDOR/lib/pkp/classes/core/PKPApplication.inc.php:227, referer: http://192.168.171.150/index.php/test/manageCatalog
 PHP   4. PKPComponentRouter->route() /home/cziaarm/PKP/OMP-VENDOR/lib/pkp/classes/core/Dispatcher.inc.php:134, referer: http://192.168.171.150/index.php/test/manageCatalog
 PHP   5. PKPRouter->_authorizeInitializeAndCallRequest() /home/cziaarm/PKP/OMP-VENDOR/lib/pkp/classes/core/PKPComponentRouter.inc.php:262, referer: http://192.168.171.150/index.php/test/manageCatalog
 PHP   6. call_user_func() /home/cziaarm/PKP/OMP-VENDOR/lib/pkp/classes/core/PKPRouter.inc.php:372, referer: http://192.168.171.150/index.php/test/manageCatalog
 PHP   7. CatalogMonographsGridHandler->toggle() /home/cziaarm/PKP/OMP-VENDOR/lib/pkp/classes/core/PKPRouter.inc.php:372, referer: http://192.168.171.150/index.php/test/manageCatalog

**Comment by asmecher** [comment]
@cziaarm, what version of OMP are you using?

**Comment by cziaarm** [comment]
Hello,

This was from development  ff81202fa1f44cfc2a8aebb508639b9e1ee47332 to be precise.

Cheers,

Rory

**Comment by asmecher** [comment]
Thanks, @cziaarm -- I've just committed a fix to this; please let me know if that resolves the issue for you.

**Comment by cziaarm** [comment]
@asmecher issue resolved.

Thanks a million!

**Comment by cziaarm** [comment]
Scratch that...

apologies for the poor UAT (only had one submission on my dev env).

For the featured checkboxes there looks to be an index related problem.

checkboxes for featured will check the  next unchecked box and uncheck the last checked box, rather than the one that is actually clicked on.

New releases are behaving as expected.

**Comment by asmecher** [comment]
@cziaarm, checking the boxes may cause the order of items to jump around somewhat -- is that perhaps causing it to look like the wrong box gets checked/unchecked?

**Comment by cziaarm** [comment]
You are right. I just hadn't noticed the reordering (test submissions had very similar titles).


Working as expected. :)


Thanks!


Rory McNicholl
Lead developer
Digital Archives & Research Technologies
University of London Computer Centre
Senate House
Malet Street
London
WC1E 7HU

t: +44 (0)20 7863 1344
e: rory.mcnicholl@london.ac.uk
w: http://www.ulcc.ac.uk/

The University of London is an exempt charity in England and Wales.
________________________________

**Comment by NateWr** [comment]
The catalog management panel was replaced in 3.2, I believe, and this no longer applies.
