### ISSUE TITLE
[OJS] Upgrade Tool upgrade.php shows wrong version as latest

### ISSUE THREAD

**Issue by dtwardy** [pkp/pkp-lib#2060]
When using the command line tool (../tools/upgrade.php) the tool lists OJS 2.4.8.1 as latest version. Since I'm upgrading from OJS 3.0.0 to OJS 3.0.1 this behaviour doesn't make any sense. I suppose a variable hasn't been updated? 

I've checked this with a fresh OJS 3.0.0 installation so no legacy problems.

**Comment by asmecher** [comment]
@dtwardy, that's an XML document on the PKP website. I was hesitant to throw this over to 3.0.0 as of the initial release of that version, but now that we've released 3.0.1 and that's proven reasonably stable I'll likely update it within the next week or so. There's no implication for your local install.

**Comment by dtwardy** [comment]
Ok, great.

**Comment by crism** [comment]
As of today, OJS 3.0.0 still reports 2.4.8-1 as the latest available version.

**Comment by asmecher** [comment]
Hi @crism -- I may leave 2.4.x as current until we complete 3.1. OJS 3.x is stable, but doesn't yet support subscriptions, which might catch some users by surprise.
