### ISSUE TITLE
Do an audit of internal (editorial) stats using "real" data

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#2061]
There may be cases where the stats being produced by the stats plugins are producing inaccurate results because the users didn't "do the right thing" (i.e., something was published without registering an editorial decision). 

Specific activities:
- [ ] Could contact Alex from SciELO for some specific examples of problems
- [ ] Consult some clients on what statistics they want
- [ ] Review existing stats to find issues where there are data problems
- [ ] Assess how problems move from OJS 2 --> 3
- [ ] Assess if "clean" OJS 3 install would exhibit problems

**Comment by asmecher** [comment]
@jalperin, these are all good things to do but are pretty vague. They'll be likelier to move up the priority list if there are specific problems you can identify.

**Comment by jalperin** [comment]
I don't have the specifics, but this has been raised as an issue, and we
should spend some time to explore it. The first two tasks are to contact
users for specifics.

**Comment by asmecher** [comment]
Is there an email thread or something with Scielo that provides context?

**Comment by jalperin** [comment]
Stems from my meeting with them. Will ask their Alex to comment here (task
one!)

**Comment by NateWr** [comment]
@jalperin is this obsolete now that you've produced the stats fields table from the 2017 sprint?

**Comment by jalperin** [comment]
The sprint report is probably as specific as we're likely to get, so yes, can close in favour of implementing the reports suggested at the Sprint.
