### ISSUE TITLE
[OJS] Problems with native xml import

### ISSUE THREAD

**Issue by alappe** [pkp/pkp-lib#2063]
Aloha,

I'm running OJS 3.0.1 on PHP 7.0.13. When trying to use the native import function, I do get the error

> Element 'issue': No matching global declaration available for the validation root.

when I try it with the provided `testissue.xml` from the `tests/functional` directory. Using `xmllint --valid $FILE`, it complains about the missing DTD. When adding `<!DOCTYPE issue PUBLIC "-//PKP//OJS Articles and Issues XML//EN" "http://pkp.sfu.ca/ojs/dtds/native.dtd">`, it results in 
`validity error : Element galley content does not follow the DTD, expecting (id* , label , file), got (id id file )`. It seems this DTD does not contain anything for `issue`, only for `issues`.

With the local file I actually need to import, I also get some validity errors… but I thought at least the testissue should work…

If you need more info, I am happy to provide it…

**Comment by asmecher** [comment]
Hi, @alappe -- we changed "native" XML formats between OJS 2.x and 3.x; the DTD describes the schema for OJS 2.x import/exports, and for OJS 3.x we're using an XSD (XML schema) based descriptor. You can find this in `plugins/importexport/native/native.xsd` and `lib/pkp/plugins/importexport/native/pkp-native.xsd`, and there's sample XML in `plugins/importexport/native/tests/functional/testissue.xml`. Try validating your XML against the XSD.

**Comment by alappe** [comment]
Hey @asmecher,

thanks for the quick reply. But that means I should be able to import the `plugins/importexport/native/tests/functional/testissue.xml` into the 3.0.1, right? Because that also fails with:

> ## Validation errors:
> * Element 'issue': No matching global declaration available for the validation root.

**Comment by bozana** [comment]
@alappe, that test XML is not updated, thus you will not be able to import it. You could use `tests/data/60-content/issue.xml` instead, but you will have to have the user group "Author" in your installation, because it is used in this example XML file.

**Comment by alappe** [comment]
Ah, perfect… this should help me to get my actual xml runnig… thanks @bozana!

**Comment by bozana** [comment]
@alappe, one more thing: the `uploader` (from the `revision` element) will also have to exist in your installation...

**Comment by bozana** [comment]
@alappe, can this issue then be closed?

**Comment by alappe** [comment]
Yes, thanks…
