### ISSUE TITLE
Standardize emailed URL handling

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2064]
Some emailed URLs rely upon the email variable including the `<a href="...">...</a>` markup being included in the variable. (See `EditorDecisionWithEmailForm::initData`.) Others assume the email template will provide the markup.

For the sake of allowing the submission URL to appear in TinyMCE fields as a "pretty" variable, the markup should be included in the variable.

This is currently not done consistently -- and in some cases the same variable is coded both ways, hence http://forum.pkp.sfu.ca/t/additional-tag-in-email-in-omp-1-2-0/26082.

Watch also the upgrade scripts, which edit existing email templates in converting from plaintext to HTML.

**Comment by asmecher** [comment]
@defstat, mind taking a look at this?

**Comment by defstat** [comment]
@asmecher The "Insert Tag" button of the editor adds the choices for the user, using the https://github.com/pkp/pkp-lib/blob/master/templates/form/textarea.tpl#L30 (among other lines of the same file) along with some javascript code that reads the "data-variable" attribute into a javascript object and displays it as a html list upon the "Insert Tag" button click.

I have 2 questions (lets say for the submissionUrl): 
1. how do we want the variables to be displayed in the popup (when we click the "Insert Tag" button)
2. How do we want the variable to be displayed in the editor when that variable is selected from the tags. (now the submissionURL url for example is being displayed as "URL" in the editor)

Regarding the emailTemplates, there is a number of user parameters and a number of used emailTemplates that use the <a href="$parameter">$parameter</a> pattern. Do we need the parameter to pass as <a href="$parameter">$parameter</a> through all the code and change the emailTemplates to add only the $parameter?
If that's the case, we want to do the same for the second question above? (so that if we click on a variable to add the URL as is to the editor?

**Comment by asmecher** [comment]
Sorry for the delay on this, @defstat --

> how do we want the variables to be displayed in the popup (when we click the "Insert Tag" button)

Generally the `common.url` locale key should be sufficient. (This reads "URL" in English.) If we have a case where that's ambiguous, e.g. if there are a couple of URLs, then we could create something more specific -- but I think "URL" is enough for the moment.

> How do we want the variable to be displayed in the editor when that variable is selected from the tags. (now the submissionURL url for example is being displayed as "URL" in the editor)

I think it makes sense for both to be the same, e.g. "URL" in both cases. Unless I misunderstand the question, which is always possible :)

If I understand the last question correctly, you're concerned about the number of variables that show up in the email templates but aren't reflected in the TinyMCE selector widget, is that right? I'd like to eventually add them all, but I don't mind of that's a long term goal.

**Comment by asmecher** [comment]
Also, where possible, I think it makes sense to replace the variables with their appropriate values *before* the email text is even displayed. That way the user can work with the text naturally and not see the variable replacements at all. However, that's not always possible or desirable, e.g. because the user needs to work with the email text on the same dialog where the user is chosen, so the name can't be replaced beforehand.

**Comment by defstat** [comment]
@asmecher for the URL standardization we could change the 

https://github.com/pkp/pkp-lib/blob/master/classes/mail/MailTemplate.inc.php#L254

adding a check if the value if a url like:

`if (filter_var($value, FILTER_VALIDATE_URL) != false) {
     $value = "<a href='$value' class='$key-style-class'>$value</a>";
}

$subject = str_replace('{$' . $key . '}', $value, $subject);
$body = str_replace('{$' . $key . '}', $value, $body);` 

That way any url value will be transformed to the `<a href='$value' class='$key-style-class'>$value</a>` pattern. 

Of course we should change all emailTemplates as well, and remove the `<a href='{$value}'>{$value}</a> ` pattern from them leaving only the `{$value}`

For example at https://github.com/pkp/ojs/blob/master/locale/en_US/emailTemplates.xml#L114 

`<a href="{$contextUrl}">{$contextUrl}</a>`

Could that solution be acceptable?

**Comment by defstat** [comment]
@asmecher As for the other comment [https://github.com/pkp/pkp-lib/issues/2064#issuecomment-282851157]

Maybe we could tag the parameters, by using an other variable for the fbvElement except from `variables`

For example
https://github.com/pkp/pkp-lib/blob/master/templates/controllers/modals/editorDecision/form/promoteForm.tpl#L39 

We could name that `variableType ` and contain tags for the parameters. A tag could be 'displayed'.

At https://github.com/pkp/pkp-lib/blob/master/js/classes/TinyMCEHelper.js#L62 we could check if the tag is 'displayed' for the `variableSymbolic`. If it is we could add the plain `variableName` in the editor, given that the `variableName ` will be the exact value of the variable, and not in the styled <div> form.

**Comment by defstat** [comment]
@asmecher 
#2344 
[OJS]#1305

**Comment by defstat** [comment]
@asmecher #2344 for [https://github.com/pkp/pkp-lib/issues/2064#issuecomment-282851157]

**Comment by defstat** [comment]
@asmecher PR #2363 and pkp/ojs#1316

**Comment by asmecher** [comment]
Thanks, @defstat! Two changes and I think it'll be ready:

- There needs to be an upgrade script to remove the anchor markup from already-installed email templates. (See e.g. https://github.com/pkp/omp/blob/master/dbscripts/xml/upgrade/1.2.0.0_update.xml#L49 for an example use of SQL REPLACE for this.)
- This also needs porting to OMP.

**Comment by defstat** [comment]
@asmecher I added the script to change the tables in the latest upgrade script of OJS and OMP, but I am not sure that this is what you asked. (for OMP the work is in progress, as it seems not to run the [data] portion of the script for some reason)

**Comment by asmecher** [comment]
Thanks, @defstat, that is indeed the upgrade process I'd imagined. See my comment about JS linting -- and I think you have some work on the OMP side still? Otherwise this looks good.

**Comment by defstat** [comment]
**New PRs**
#2381
pkp/ojs#1333
pkp/omp#399

**Comment by asmecher** [comment]
@defstat, I replaced the above pulls with my own rebases:

- https://github.com/pkp/pkp-lib/pull/2398
- https://github.com/pkp/ojs/pull/1336
- https://github.com/pkp/omp/pull/401

I had to add the following commit to get the JS tests working: https://github.com/pkp/pkp-lib/pull/2398/commits/507fe4359e02ed41d8f2f99edf566f55c09b5c7c
(Yes, the linter/compiler is that picky.)

I'm still not sure why your PRs weren't showing the JS linting errors, but anyway -- if it happens more, let's look into it, and if not, no harm/no foul.

**Comment by asmecher** [comment]
Meanwhile, merged, thanks!

**Comment by defstat** [comment]
Reopened because of a bug that interfered with the textArea insert PKP tags function 

PR: pkp/pkp-lib#2776

**Comment by asmecher** [comment]
Thanks, @defstat -- merged. Is this ready to be closed again?

**Comment by defstat** [comment]
@asmecher Yes for now.

**Comment by defstat** [comment]
@asmecher The previous merge broke the JS lint checks.
PR: pkp/pkp-lib#2808
