### ISSUE TITLE
DOI Export Plugin assertion "register" is noisy

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2068]
This line asserts a user variable rather than a boolean:
https://github.com/pkp/ojs/blob/1581c87595ebbb84df8b59d4fec26084cb4ef009/plugins/importexport/datacite/classes/DOIExportPlugin.inc.php#L242

The intent is to assert that there is content in the user variable, not that the user variable is a boolean true.

**Comment by asmecher** [comment]
Merged, thanks!
