### ISSUE TITLE
Localize RECAPTCHA display

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2073]
C.f.: http://forum.pkp.sfu.ca/t/fake-user-spam-regestration/25285/8

The RECAPTCHA javascript API construction has the (unused) [option of setting a language](https://developers.google.com/recaptcha/docs/display#js_param).  This could (should?‡) be tied into the user's selected locale.  A mapping of locale to [language code](https://developers.google.com/recaptcha/docs/language) would be needed.

‡ Google will autodetect the language code (probably based on the UA?), but if a user has explicitly selected a different locale, shouldn't the interface honor that instead?

**Comment by asmecher** [comment]
That's a duplicate -- although this one is better filed!
https://github.com/pkp/pkp-lib/issues/1786
