### ISSUE TITLE
DOMDocument::createElementNS() is being used without consideration for escaping

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2074]
C.f. http://forum.pkp.sfu.ca/t/crossref-xml-export-plugin-not-working-in-ojs-3/26255/4?u=ctgraham

Examples include at least:
https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/filter/IssueCrossrefXmlFilter.inc.php
and
https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php

Can be resolved by `htmlspecialchars()` or by `DOMDocument::createTextNode()`.

**Comment by bozana** [comment]
I will then fix this with htmlspecialchars...

**Comment by ctgraham** [comment]
I'm already most of the way through a search-and-replace.

**Comment by bozana** [comment]
Thanks a lot!

**Comment by ctgraham** [comment]
https://github.com/pkp/pkp-lib/issues/2077
https://github.com/pkp/ojs/pull/1131

Requires testing and porting to OMP.

**Comment by bozana** [comment]
I can test an port this...

**Comment by bozana** [comment]
This is the right issue...  -- I first added the following comment to the wrong issue...

I reviewed and tested the changes -- they work well! Thanks a lot @ctgraham!
There are a few minor things, that I can add after the merge:
-- issue year is escaped in NativeFilterHelper, but not in O4DOIXmlFilter
-- e-mail is escaped in O4DOIXmlFilter and IssueCrossrefXmlFilter, but not in DOAJXmlFilter and PKPAuthorNativeXmlFilter
-- the escape for DOI in DataciteXmlFilter is missing
-- the escape for representation->getId() in the element `id` in RepresentationNativeXmlFilter is not needed

**Comment by bozana** [comment]
Additionally the escape parameter for url creation is added.

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2084
ojs master: https://github.com/pkp/ojs/pull/1135

**Comment by bozana** [comment]
Everything merged here, thus closing...

**Comment by bozana** [comment]
I forgot to remove htmlspecialchars for URLs after using the "escape" parameter for the request URL function, so that URLs are escaped double and thus incorrect :-(
Here the fix PRs:
master: https://github.com/pkp/ojs/pull/1144
ojs-stable-3_0_1: https://github.com/pkp/ojs/pull/1145

**Comment by bozana** [comment]
Remove double escape mEDRA URLs
