### ISSUE TITLE
Review first_page / last_page parsing

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2075]
Review the semantics of startPage and endPage for DOAJ (c.f. https://doaj.org/features).

The current code assumes a single page range or the magic of a single e-prefixed page number:
https://github.com/pkp/ojs/blob/c3c29f172c9a5b2d579d969f4044101617fd7921/plugins/importexport/doaj/filter/DOAJXmlFilter.inc.php#L99-L113

This might be improved with the new features coming out of https://github.com/pkp/pkp-lib/issues/333

**Comment by ctgraham** [comment]
Also review citationFormat plugins [bibtext](https://github.com/pkp/ojs/blob/56e9bed67eb6dd1fe8db889fe25628da27541176/plugins/citationFormats/bibtex/citation.tpl#L26) and [endnote](https://github.com/pkp/ojs/blob/4af018f3a9c5908df9ca9d8b1c8de80471acff79/plugins/citationFormats/endNote/citation.tpl#L34).  Do these require numeric-only output?

**Comment by ctgraham** [comment]
Also review [webFeed](https://github.com/pkp/ojs/blob/master/plugins/generic/webFeed/templates/rss.tpl#L103-L114) and [Google Scholar](https://github.com/pkp/ojs/blob/master/plugins/generic/googleScholar/GoogleScholarPlugin.inc.php#L86-L89).

**Comment by ctgraham** [comment]
* webFeed uses Prism, and [Prism explicitly notes](http://www.prismstandard.org/resources/mod_prism.html) that `prism:startingPage` and `prism:endingPage` must not be used for page counting, and should represent the beginning and end of the article's pagination, regardless of non-contiguous sections.
* Google Scholar uses Highwire Press tags.  I haven't seen clear documentation on this, but given that the purpose of the `citation_firstpage` / `DC.citation.spage` and `citatation_endpage` / `DC.citation.epage` tags are for primarily for citation purposes, it seems this should use the same assumption: non-numeric allowed, not used for counting due to potential non-contiguous ranges.
* EndNote has already been corrected to use ranges per https://github.com/pkp/pkp-lib/issues/2076
* [BibTeX also supports ranges](https://nwalsh.com/tex/texhelp/bibtx-42.html).

**Comment by asmecher** [comment]
Thanks, @ctgraham -- is this ready for review?

**Comment by ctgraham** [comment]
@asmecher, yes, ready for review.

**Comment by ctgraham** [comment]
DOAJ is definitely a string datatype, but doesn't explicitly say what to do with non-contiguous ranges.  The last page of the last range is consistent with the prior interpretation.

PubMed is also a string datatype, and explicitly notes to use the same first page and last page for a single page, and to use the first and last page of the article, regardless of non-contiguous ranges.
https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.FirstPage_OR

**Comment by ctgraham** [comment]
@asmecher, ready for review now.

**Comment by asmecher** [comment]
Both PRs merged, thanks! @bozana -- this is the change I mentioned on your DOAJ PR regarding page numbering.
