### ISSUE TITLE
[OJS] Author View Metadata modal javascript error

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2083]
Hi,

If after submitting a manuscript I login as an author and want to view the submission metadata, I get this javascript error:

`Error: There is no handler bound to this element!  Handler.js:142:10`

The javascript that is causing the error is here:
https://github.com/pkp/ojs/blob/ojs-stable-3_0_1/templates/controllers/modals/submissionMetadata/form/issueEntrySubmissionReviewForm.tpl

On row 64 the template checks if the user can edit metadata. If not, the file uploader section is not loaded.

However, on line 20 the javascript is calling for #coverImageUploader although this is not visible in the form when the user can not edit metadata. 

OJS 3.0.1.

**Comment by asmecher** [comment]
@bozana, would you mind taking a look at this one? Thanks!

**Comment by ajnyga** [comment]
I was thinking whether the cover image preview needs any javascript if the user is just viewing an image. The quickest solution could be a simpler preview function for just viewing an image.

**Comment by ajnyga** [comment]
Ok, so it seems that tinymce needs to have a handler attached to the form. I made a small hack where I attached the AjaxFormHandler to the form and after that the tinymce error was gone. Below is a template that is working. You probably have a more eloquent solution to the handler problem, I do not know the code well enough. Note that I also removed the cover image delete link and changed the alt text field to check if it should be readonly.

`{**
 * controllers/modals/submissionMetadata/form/issueEntrySubmissionReviewForm.tpl
 *
 * Copyright (c) 2014-2016 Simon Fraser University Library
 * Copyright (c) 2003-2016 John Willinsky
 * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
 *
 * Display a submission's issue entry form.
 *
 *}
{* generate a unique ID for the form *}
{assign var="submissionMetadataViewFormId" value="submissionMetadataViewForm-"|uniqid|escape}

<script type="text/javascript">
	$(function() {ldelim}
		// Attach the form handler.
		$('#{$submissionMetadataViewFormId}').pkpHandler(
			{if !$formParams.readOnly}
			'$.pkp.controllers.form.FileUploadFormHandler',
			{ldelim}
				$uploader: $('#coverImageUploader'),
				$preview: $('#coverImagePreview'),
				uploaderOptions: {ldelim}
					uploadUrl: {url|json_encode router=$smarty.const.ROUTE_COMPONENT op="uploadCoverImage" escape=false},
					baseUrl: {$baseUrl|json_encode},
					filters: {ldelim}
						mime_types : [
							{ldelim} title : "Image files", extensions : "jpg,jpeg,png" {rdelim}
						]
					{rdelim},
					multipart_params: {ldelim}
						submissionId: {$submissionId|escape},
						{if $stageId}stageId: {$stageId|escape},{/if}
					{rdelim}
				{rdelim}
			{rdelim}
			{else}
			'$.pkp.controllers.form.AjaxFormHandler'
			{/if}
		);
	{rdelim});
</script>

<form class="pkp_form" id="{$submissionMetadataViewFormId}" method="post" action="{url router=$smarty.const.ROUTE_COMPONENT op="saveForm"}">
	{csrf}
	{assign var="notificationId" value="submissionMetadataViewFormNotification-"|uniqid|escape}
	{include file="controllers/notification/inPlaceNotification.tpl" notificationId=$notificationId}

	<input type="hidden" name="submissionId" value="{$submissionId|escape}" />
	<input type="hidden" name="stageId" value="{$stageId|escape}" />
	<input type="hidden" name="displayedInContainer" value="{$formParams.displayedInContainer|escape}" />
	<input type="hidden" name="tab" value="submission" />

	{include file="submission/form/section.tpl" readOnly=$formParams.readOnly}

	{include file="core:submission/submissionMetadataFormTitleFields.tpl" readOnly=$formParams.readOnly}

	{* Contributors *}
	{if !$formParams.hideSubmit || !$formParams.anonymous}
		{* generate a unique ID for the form *}
		{assign var="authorsGridContainer" value="authorsGridContainer-"|uniqid|escape}
		{url|assign:authorGridUrl router=$smarty.const.ROUTE_COMPONENT  component="grid.users.author.AuthorGridHandler" op="fetchGrid" submissionId=$submissionId stageId=$stageId escape=false}
		{load_url_in_div id=$authorsGridContainer url="$authorGridUrl"}
	{/if}

	{* Cover Image *}
	{fbvFormArea id="coverImage" title="editor.article.coverImage"}
		{if !$formParams.readOnly}
			{fbvFormSection}
				{include file="controllers/fileUploadContainer.tpl" id="coverImageUploader"}
				<input type="hidden" name="temporaryFileId" id="temporaryFileId" value="" />
			{/fbvFormSection}
		{/if}
		{fbvFormSection id="coverImagePreview"}
			{if $coverImage != ''}
				<div class="pkp_form_file_view pkp_form_image_view">
					<div class="img">
						<img src="{$publicFilesDir}/{$coverImage|escape:"url"}{'?'|uniqid}" {if $coverImageAlt !== ''} alt="{$coverImageAlt|escape}"{/if}>
					</div>

					<div class="data">
						<span class="title">
							{translate key="common.altText"}
						</span>
						<span class="value">
							{fbvElement type="text" id="coverImageAltText" label="common.altTextInstructions" value=$coverImageAltText readOnly=$formParams.readOnly}
						</span>
						{if !$formParams.readOnly}
						<div id="{$deleteCoverImageLinkAction->getId()}" class="actions">
							{include file="linkAction/linkAction.tpl" action=$deleteCoverImageLinkAction contextId="issueForm"}
						</div>
						{/if}
					</div>
				</div>
			{/if}
		{/fbvFormSection}
	{/fbvFormArea}

	{include file="submission/submissionMetadataFormFields.tpl" readOnly=$formParams.readOnly}

	{if !$formParams.hideSubmit}
		{fbvFormButtons id="submissionMetadataFormSubmit" submitText="common.save"}
	{/if}
</form>`

**Comment by ajnyga** [comment]
This same issue causes the review form to crash if the reviewer checks the submission metadata in step 1: http://forum.pkp.sfu.ca/t/ojs3-moving-between-steps-in-submission-and-review-forms-sometimes-cause-errors/26283/9

**Comment by bozana** [comment]
@asmecher, sorry for asking, I am not sure: how would it be better to solve this: to check if the form is read-only and depending on that to use the appropriate handler, either FileUploadFormHandler,js or AjaxFormHandler, e.g. https://gist.github.com/ajnyga/0f379d70000284ae19362e624e3080c0#L18
Or to provide a new parameter $readOnly to the FileUploadFormHandler,js, that already extends AjaxFormHandler.js, and in that case not to execute these lines: https://github.com/pkp/pkp-lib/blob/master/js/controllers/form/FileUploadFormHandler.js#L34-L49 ? :-\

**Comment by asmecher** [comment]
I think it's better to extend FileUploadFormHandler to support read-only operation.

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_0_1: https://github.com/pkp/pkp-lib/pull/2241
ojs ojs-stable-3_0_1: https://github.com/pkp/ojs/pull/1229

**Comment by bozana** [comment]
@NateWr, could yo please review the PRs above? I am not sure if there is a better way -- in case of readOnly forms (currently only one template) the AjaxFormHandler should be used i.e. the FileUploadFormHandler should just act as its parent...

**Comment by NateWr** [comment]
Hi @bozana,

Looks good! I just had one comment on variable naming, but otherwise it looks good. Go ahead and merge once that change is in place.

I'm not sure there is a better way to handle this. We could check for the existence of the `$uploader` element, but that just ties functionality to specific HTML in ways that are already confusing enough. And I like that the `readOnly` param is explicit about its intention and scoped to one specific meaning, rather than trying to interpret the appropriate behaviour from other things.

**Comment by bozana** [comment]
everything merged and cherry-picked, thus closing...
