### ISSUE TITLE
[OJS] Reviewer doesn't have adequate permission to download review file

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2092]
The problem has been discussed here: http://forum.pkp.sfu.ca/t/ojs-3-the-current-role-does-not-have-access-to-this-operation/24614/16 and in addition we have just run into the same problem on a journal we host. 

Problem behaviour: a reviewer accepts a review, and goes to Step 3, where they should be able to download the review file. When they click on the review file, they receive the following JSON erorr: 

{"status":false,"content":"The current role does not have access to this operation.","elementId":"0"}

Some things I've confirmed: 

- access is via one-click, but I also tried by logging in as the reviewer, and no luck; 
- reviewer has been enrolled as a reviewer; 
- reviewer has accepted the review.

**Comment by bozana** [comment]
It seems that this OJS 2.4.x files have all `viewable = 0` in the database, which is not correct and makes this condition not pass: https://github.com/pkp/pkp-lib/blob/master/classes/security/authorization/internal/SubmissionFileAssignedReviewerAccessPolicy.inc.php#L55.
Apparently the property "viewable" was not considered in the upgrade script. I do not know if there is any rule to apply to correct it?

**Comment by bozana** [comment]
@asmecher, I think this condition: `$submissionFile->getViewable()` is maybe not necessary for review assignments: In normal case, the files that an editor selects for the review i.e. in the "Review Files" grid are viewable. However, the editor can deselect the checkbox when editing such a file and the file will then have viewable = 0. But, if that file is assigned to a reviewer, in the "Reviewers" grid and inserted in the table review_files, it should be viewable for the reviewers no matter. Thus "viewable" for the files assigned to a reviewer (that editor defines selecting the checkbox in the "Review Files" grid) should not be considered for the reviewer to access the files. Don't you think so?

**Comment by bozana** [comment]
Currently I only see one purpose of "viewable" in OJS 3.x -- to control whether a reviewer file should be viewable by the author. When uploaded, the reviewer files have `viewable = 0`. Those reviewer files that are selected when informing the author e.g. by "Send To Copyedit" get then `viewable = 1`. And just those are viewable for the author.
To control whether a reviewer can view a file should maybe only consider if the file is in review_files table i.e. assigned to the reviewer, as explained in the comment above, I think.

"viewable" is currently also used to maintain the checkboxes of the selectable lists when promoting from copyediting to production. Here all stage changes: 
If promoting 
a) from submission to review: all files in submission stage (Submission Files grid) are viewable. They are all provided for selection. When selected they will be copied into new files that are also first viewable in review (Review Files grid), but this can be changed by the editor.
b) from review to copyediting: the revision and reviewer files are provided for selection. Both are not viewable and all are provided for selection. Those selected will be copied into new files that are first viewable in copyediting (Draft Files grid), but this can be changed by the editor.
c) from copyediting to production: only the viewable copyedited files are provided for selection.
When selected they will be copied into new files that are not viewable in production (Production Ready Files grid).

@asmecher, is this all correct i.e. as it should be?

**Comment by asmecher** [comment]
@bozana, that all makes sense to me. The use of `viewable` in Copyediting/Production probably partially stems from our previous workflow tools, and was likely made a little incoherent by our switch over to the discussion tools. Your proposal is OK with me.

**Comment by bozana** [comment]
PRs:
1) remove check if the file is viewable for reviewer access:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2147
pkp-lib ojs-stable-3_0_1: https://github.com/pkp/pkp-lib/pull/2148

**Comment by bozana** [comment]
@jmacgreg, the first PR from above should solve the issue....

**Comment by bozana** [comment]
Concerning the migration of "viewable":
Now that also those not viewable files are visible in Draft Files and Copyedited grid, we could leave them as they are.
Now that the viewable is not considered for reviewer access, we can also leave the Review Files as they are.
Because the author access to the reviewer files i.e. viewable for the files in the stage = 5 (review attachment) is handled in OJS 2.4.x, we also do not have to do anything here. 
The files in the stage = 15 (revisions) always have viewable = 0, thus this can stay as it is.
Thus, nothing urgent to be considered fr the migration. The only thing to consider for the migration of `viewable` is to set it to 1 for file_stagle = 2 (submission) and 6 (final). And eventually also for file_stage = 18, if the file has source_file that is viewable.
@asmecher, what do you think? OK so?

**Comment by asmecher** [comment]
Yes, @bozana -- happy to have you on this one!

**Comment by bozana** [comment]
I moved the migration of "viewable" to a new issue: https://github.com/pkp/pkp-lib/issues/2151

Thus, @jmacgreg, when you apply the first PR above and that solves your issue, this issue can be closed...

**Comment by jmacgreg** [comment]
Thanks Bozana! I'll test, and re-open if I run into problems.

**Comment by ajnyga** [comment]
Hi,

I do not think that any of the above fix this issue?
http://forum.pkp.sfu.ca/t/section-editors-cannot-download-file-submission-and-got-error-ojs3/25050
