### ISSUE TITLE
[OJS3] Submission of Forms is Broken on Review Stage

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#2095]
In our test installation we get some weird behaviour on the review stage page when we try to submit a form. After hitting the *ok* button, the page only shows the loading symbol and nothing else happens. 

Reloading the page manually helps - the expected result is shown, including the notification popups in the upper right part. This happens on adding a paricipant and adding a discussion. On adding a participant to the review it seems that the task is handled correctly and only display is broken. 

But onn adding a new discussion to the review round, there is **no email notifaction send to the discussions participants**.

**Comment by pkel** [comment]
Testers are reporting that the **notify participant function** triggered from the review stage does not send emails either. Currently, there is no possibility to contact a sleeping reviewer from within ojs.

**Comment by asmecher** [comment]
Do you mean "but notification is *not* sent"? What version of OJS are you using? Have you checked your server's mail logs to see whether the messages are getting rejected there?

**Comment by asmecher** [comment]
Also, when you see an endless spinner, it usually corresponds to a message in your PHP error log. Check there for details. Also please include your OJS version in issue reports.

**Comment by pkel** [comment]
Sorry for not specifying the version in my latest bug reports. I will try to make this better in the future.

The installation is using 3.0.1.

Error printing to stdout is active in OJS settings but no error showed up. Does this catch all relevant errors? 

I use smtp configuration in config.inc.php for mail transfer. Where are the corresponding logs stored?

**Comment by asmecher** [comment]
When errors are sent to stdout, then in cases where OJS expects a response in JSON format, it'll get both the JSON and a PHP error message -- hence it won't be able to parse them, and you'll get an endless spinner.

If you're using SMTP, the logs will be stored on your SMTP server, and you probably won't have access to them. In that case, you might try adding some error logging -- e.g. in `lib/pkp/classes/mail/Mail.inc.php` in the `send` function, you could add...

    error_log(print_r($this,true));

This would cause every message sent via the SMTP mailer to be logged to the PHP error log.

**Comment by pkel** [comment]
I will setup proper logging and report back.

The weird thing is that most emails go through. Why would the server reject especially those about a new discussion?

**Comment by asmecher** [comment]
It's common for servers to reject emails if they don't like the addressing -- e.g. if the sender's domain isn't something the server thinks it has jurisdiction over. Without access to the email server's logs, if these are dropping into oblivion they can be hard to debug, unfortunately.

**Comment by pkel** [comment]
With the php error to stdout disabled and after a restart of the webeserver, I can't reproduce this any more. Mails are sent correctly and I have no infinite spinner any more on the Review Stage.

**Comment by asmecher** [comment]
Thanks, @pkel!
