### ISSUE TITLE
[OJS3] Reviewer role hides access to SE view of review stage

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#2099]
If a SE assigns himself as reviewer he is not able to access the review management page any more but only sees what a normal reviewer does. Finishing the review does not help. Fiddling with the URL and changing it to `/workflow/index` does help, but is a bit inconvenient.

You may ask, why this is necessary. Our SEs use this in OJS2 to contact reviewers anonymously. It is mainly used when SE want to give negative feedback without revealing their name. If OJS3 has other possibilities to achieve this goal, please tell me.

**Comment by asmecher** [comment]
@pkel, see e.g. http://forum.pkp.sfu.ca/t/ojs3-section-editor-acting-also-as-reviewer/25553. We're likely to further restrict SE access to submissions they're also assigned as reviewers on. You might consider using the Discussions tool to have SEs communicate feedback to Editors, then have the Editor communicate those back to Reviewers/Authors.

**Comment by pkel** [comment]
I understand your argument but it would be wise then, to prevent SE from assigning themselves as reviewer. Currently they lock themselves out if they do so -- at least it seems like they do. A small manipulation in the url reveals the SE view on the review.

A perfect solution for us would be a *hide my name in this discussion* function. The SE > E > R path adds some overhead.

**Comment by asmecher** [comment]
It's a common requirement for journals to occasionally use their Section Editors to review certain submissions, and in that case, they definitely shouldn't be able to access the editorial workflow of those submissions, even if they're in sections that the editor edits. Your use case is different, and definitely less common. Currently OJS doesn't handle either very well, as you've noted, but given the more common use case we're more likely to make your life even more difficult with your current plan rather than less.

See http://forum.pkp.sfu.ca/t/ojs-3-the-current-role-does-not-have-access-to-this-operation/24614/16 for some related discussion in the forum. (Tagging @bozana, who's active over there too.)

Your suggestion for hiding names in discussions is interesting -- @stranack, what do you think?

**Comment by pkel** [comment]
I do not want to change your plans, but you will have to think about somthing to prevent self lockout by reviewer role self assignment. I think a small warning *hereby you will loose your SE capabilities* can do a lot here. Otherwise all our SE will be trapped at least once.

**Comment by asmecher** [comment]
Agreed, I think a warning upon assignment makes sense.

**Comment by ajnyga** [comment]
Many of our editors have contacted us regarding this issue. I think that a warning is the least we could do here.

However it would make more sense, if the links leading to the submission workflow would point to the editor view AFTER the editor/reviewer has done the review? This way the editor could use the common review functions.

**Comment by asmecher** [comment]
Why are your Section Editors self-assigning as Reviewers, @ajnyga and @pkel? I think I'm still not understanding the use case, or what they expect to happen.

**Comment by ajnyga** [comment]
I think there are three different cases where this has happened:
1. Some journals have a workflow, where the editors do their own review round before the actual peer-review. 
2. I think that some journals actually use editors for the peer-review together with outside reviewers
3. In some cases the editors have tested the functionality

You can of course use the discussion functionality for case 1, but it would make sense if you could just use the actual review functionality? 

Whatever the solution here is, the current situation where you can "lock down" the editor workflow has to be prevented somehow. Now the site manager has to remove the review request from the database.

**Comment by mcdowellb** [comment]
OK, so this may sound silly, but it is quite frustrating.  I was having some problems that others were having in that my reviewers were unable to download the review document.  I have now fixed this, but in trying to learn more about the problem, I assigned myself, the editor, to the review.  Now, when I click on the submission, I can only access the review.  I can no longer access the submission and the other reviews.  This is just extremely frustrating as I have no way to get back to the editorial role for this submission.  

Any ideas?

Bill

**Comment by asmecher** [comment]
@mcdowellb, if you just want to un-assign yourself as reviewer, the easiest way to do that will be to go to the editor's view of that article by URL. Open up another submission as editor, then change the article ID in the URL to the one you're trying to work with; then unassign yourself as reviewer. This should cause the URL in the submission lists to revert to the Editor one.

**Comment by mcdowellb** [comment]
@asmecher, this is great info.  I was able to get in, but I also don't know how to remove a reviewer whom has already accepted the invitation to review.  I did accept it in my quest to see if I could see the file, but unfortunately I have no idea how to remove someone that has accepted the review request.  Any more help?

**Comment by asmecher** [comment]
@mcdowellb, you could either intervene in the database and remove the `review_assignments` entry, or you can continue to use the custom-built URL to access it as editor. This is something we'll do better with in a future release.

**Comment by NateWr** [comment]
I believe this issue was addressed in #3130, so I'll close this. But please re-open if there's something more to do here.
