### ISSUE TITLE
[OJS3] Default Theme. Review interests on registration not visible

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#2100]
![reviewing-interests](https://cloud.githubusercontent.com/assets/11337857/21178864/bb7bac8a-c1f1-11e6-8dcd-f2746d166d1d.jpg)

The textbox for adding review interest during registration is not framed and thus not visible.

**Comment by asmecher** [comment]
@pkel, what version of OJS are you using?

**Comment by pkel** [comment]
3.0.1. See [here](https://jstatsoft.tr1k.de/index.php/jss/user/register).

**Comment by asmecher** [comment]
Thanks, I can reproduce this locally too. @NateWr, mind taking a look?

**Comment by NateWr** [comment]
Yeah I keep noticing this and forgetting to file. Thanks @pkel. The field is there, just styled invisibly until you focus it. :)

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/1211
https://github.com/pkp/omp/pull/385

I went ahead and merged these myself. Just one-liner CSS fixes.
