### ISSUE TITLE
Update PubMed plugin for OJS 3.x

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2101]
It's not yet rewritten for OJS 3.x -- see http://forum.pkp.sfu.ca/t/export-to-pubmed-xml-in-ojs-3-x-not-working/26700.

**Comment by asmecher** [comment]
See also the PMDM system, recently released: https://www.ncbi.nlm.nih.gov/pubmed/management

**Comment by bozana** [comment]
@asmecher, here clean up for OJS according to your clean up here: https://github.com/pkp/ojs/pull/1326
