### ISSUE TITLE
[OJS] tinymce error (downloadable font: OS/2: bad linegap: -32 ) with Firefox

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2108]
While testing OJS3 I noticed that my co-workers Firefox 50 keeps on getting this error in console:
`downloadable font: OS/2: bad linegap: -32 (font-family: "tinymce" style:normal weight:normal stretch:normal src index:1) source: http://mydomain.fi/lib/pkp/lib/vendor/tinymce/tinymce/skins/lightgray/fonts/tinymce.woff  skin.min.css:1:30806`

I use Firefox 50 as well, but for some reason I do not get that. 

There are a lot of similar errors reported when I googled around. This seems to have at least some sort of solution: https://github.com/TryGhost/Casper/issues/154

**Comment by asmecher** [comment]
@NateWr, any idea?

**Comment by ajnyga** [comment]
I am getting this in Firefox 50 / OSX. As I mentioned earlier, in FF50/Win7 I could not see this.

Someone here https://github.com/roundcube/roundcubemail/issues/4788 says that:
> The font issue is probably unrelated and fixed in git with update to TinyMCE 4.1.8.

And it seems that OJS3 is using 4.1.7.

**Comment by NateWr** [comment]
Thanks for the detective work @ajnyga! @asmecher any concerns updating the bundle of TinyMCE? Should we hold that for a major update (3.1)?

**Comment by asmecher** [comment]
Go for it on the master branch; we can back-port to `ojs-stable-3_0_1` if needed and once we're relatively sure it's stable.

**Comment by NateWr** [comment]
I updated to the latest version (v4.6.4), which is a big jump. I did some clicking around and didn't notice any issues. I also took the liberty of changing the main body text to white to match other input fields.

PRs (tests running):
https://github.com/pkp/pkp-lib/pull/2589
https://github.com/pkp/tinymce/pull/17
https://github.com/pkp/ojs/pull/1422

**Comment by NateWr** [comment]
Tests passed. Not much code to review, but @bozana could you take a look at this to ensure it's working smoothly?

**Comment by bozana** [comment]
@NateWr, great, works well! All merged, I think.
