### ISSUE TITLE
Guest Editor role is inoperative

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2111]
It's rarely mentioned in the code and doesn't appear to be working.

**Comment by crism** [comment]
I can confirm this—our users were puzzled when their guest editors couldn’t access submissions. Temporary workaround is to just make them Journal Editors.

**Comment by asmecher** [comment]
See also this change to section editor access: https://github.com/pkp/pkp-lib/issues/2109

With that in place, there's really no need to distinguish between Section Editor and Guest Editor in the code. You can create a new role, using Section Editor as the role type, called "Guest Editor", to distinguish between the two types. So your work-around will be good going forward.

**Comment by asmecher** [comment]
Committed to master.
