### ISSUE TITLE
[OMP] rethink use of "fair copy"

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2113]
I was wondering: Is "fair copy" really the right term to talk about the final corrected version of a manuscript? The term is only used once, but I noticed some difficulties in translating it into other languages, which might have something to do with the use of fair copy in talking about hand-written documents.

Also, `editor.monograph.editorial.fairCopy` is no longer used and could be removed from all locales, right?

This leaves us with `submission.upload.fairCopy` (pkp-lib) and maybe `submission.fairCopy` (in OMP - is this used at all?) being the only occurences of "Fair Copy".

Could someone have a look at the wording? Is there maybe a better term?

**Comment by asmecher** [comment]
Tagging @willinsky and @stranack on this one.

**Comment by NateWr** [comment]
This is no longer used in `stable_3_3_0`.
