### ISSUE TITLE
Display native export validation errors

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2117]
Currently the errors are only in the log file and the XML is not displayed, thus it is difficult to debug i.e. see what is wrong. Thus, display the validation errors and invalid XML to the user, as it is in DOI export plugins.

**Comment by bozana** [comment]
PRs
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2122
ojs master: https://github.com/pkp/ojs/pull/1156
omp master: https://github.com/pkp/omp/pull/372

**Comment by bozana** [comment]
@NateWr, tests are running, but... could you take a look at those PRs?

**Comment by NateWr** [comment]
@bozana Looks good! A couple of minor recommendations. I haven't run this through any tests myself. Do you have a dataset I can use to produce a validation error to test this?

**Comment by bozana** [comment]
Thanks a lot @NateWr! I fixed everything, I think. If you comment this line, you can see the error message when exporting a submission: https://github.com/pkp/pkp-lib/blob/master/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php#L166

**Comment by NateWr** [comment]
Thanks! Tested, looks good. All merged!
