### ISSUE TITLE
[OJS] Enable journal to appear publicly on the site when path written with capital letters leads to an error

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2118]
In OJS 3.0.1. a situtation where site admin tries to enable a jouranl to appear publicly AND the journal path is written with capital letters:
![screenshot_18](https://cloud.githubusercontent.com/assets/16347527/21351733/cc697ef8-c6c6-11e6-959f-cd4a3059a82f.png)

I get this error:
![screenshot_19](https://cloud.githubusercontent.com/assets/16347527/21351743/d392272a-c6c6-11e6-9dcd-89fd5de2e781.png)

If I try to change the path to lowercase, I get this error:
![screenshot_21](https://cloud.githubusercontent.com/assets/16347527/21351751/e436c310-c6c6-11e6-9a85-7cd13b61aa78.png)

Of course I can change this from the database, but for some users that is probably not an option.

This is a journal that is migrated from OJS2.

**Comment by bozana** [comment]
Yes capital letters seem not to be allowed for journal path in OJS 3.0.x. Is this meant to be so @asmecher ?
@ajnyga, in the meantime, would it be possible for you to first change it to something different e.g. "sehl1" and then back to "sehl" again?

**Comment by ajnyga** [comment]
Hi,

Yes that is probably a working solution, I already changed this in the database.

**Comment by asmecher** [comment]
I would suggest we relax the lowercase requirement. For users with existing OJS 2.x journals, a change to capitalization will break inbound links.

**Comment by asmecher** [comment]
The change here permits uppercase letters to appear in paths.
