### ISSUE TITLE
BibTeX plugin missing comma between pages and doi element

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2119]
OJS 2.4.8-1: BibTeX citation output is malformed.

Reported: http://forum.pkp.sfu.ca/t/probleme-mit-bibtex-modul/27053

Cause is a missing comma on:
https://github.com/pkp/ojs/blob/dbe779f2bd97e9a0f2842c4357fb56496b7179e4/plugins/citationFormats/bibtex/citation.tpl#L26

**Comment by asmecher** [comment]
Merged and cherry-picked to `ojs-stable-2_4_8`. Thanks, @ctgraham!
