### ISSUE TITLE
Provide access to previous revisions of files in files grids

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2130]
See e.g. the discussion at https://github.com/pkp/pkp-lib/issues/2097.

**Comment by ajnyga** [comment]
I still think that this is a fairly easy solution:

controllers/grid/files/SubmissionFilesGridDataProvider.inc.php => prepareSubmissionFileData function line 164:
```
      	$submissionFileData[] = array(
      		'submissionFile' => $revision
      	);
```

controllers/grid/files/review/ReviewGridDataProvider.inc.php => loadData line 62:
`      $submissionFiles = $submissionFileDao->getRevisionsByReviewRound($reviewRound, $this->getFileStage());
`

**Comment by ajnyga** [comment]
I realized that for all the revisions added in OJS3 the old versions are available under More information => History. 

![screenshot_51](https://cloud.githubusercontent.com/assets/16347527/21748942/fa661c34-d59a-11e6-955e-a07e4ee687b0.png)

So it is basically just a matter of getting the right entries to event_log and event_log_settings during the upgrade from OJS2 to OJS3.

**Comment by asmecher** [comment]
Agreed, the log access mechanism is already there if we can fix up the log entries/conditions -- something that already needs doing. Is accessing revisions via the log convenient for you, or is it too deeply buried?

**Comment by ajnyga** [comment]
It is a bit deeply buried. but this is a problem only during the transition from OJS2 to OJS3. With the new submissions the files grid is already working very well. 

As I described in the other issue, many authors have submitted different kinds of files using the author revision function in OJS2. It is these files that our editors need to get access to after the upgrade.

I already wrote a small script that creates the log entries using the data in submission_files table, but this is probably something that should be taken into account in the upgrade script. Our prodcution server upgrade to OJS3 is running as we speak so I will use my own script to fix this afterwards.

**Comment by asmecher** [comment]
OK, thanks for the background! I'll file this against OJS 3.1, and we can at least improve the log entries if nothing more.

**Comment by asmecher** [comment]
(Clearing the milestone in favour of higher-prioritized issues, unless someone is feeling ambitious/motivated...)

**Comment by NateWr** [comment]
Closing due to lack of interest.
