### ISSUE TITLE
OJS3: Errors on installation page are unobtrusive

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2131]
In the OJS 3.0.1 installation, errors made in the "Administrator Account" section are classed to "error", but this class is not formatted any differently than the ordinary text.

![hidden-install-error](https://cloud.githubusercontent.com/assets/7001322/21432907/9f2812a8-c83b-11e6-9fa2-54d15c83c55b.PNG)

**Comment by ctgraham** [comment]
CSS rule `.pkp_form label.error` would kick in if these messages were in a `label` instead of a `span`.

**Comment by ctgraham** [comment]
The `span` is sourced here:
https://github.com/pkp/pkp-lib/blob/ojs-stable-3_0_1/templates/form/formSection.tpl#L23
but perhaps adding the selector `.pkp_form span.error` to the existing CSS declaration is preferable?
https://github.com/pkp/pkp-lib/blob/ojs-stable-3_0_1/styles/form/form.less#L46-L54

**Comment by asmecher** [comment]
@NateWr, mind taking a look?

**Comment by asmecher** [comment]
Snarfed this one for myself.
