### ISSUE TITLE
[OCS] Empty page after upload the files without possibility to install

### ISSUE THREAD

**Issue by distriker** [pkp/pkp-lib#2132]
Hi everyone!
I am interested in Open Conference System because I want to build the website of a conference. It is very strange because the last update of OCS was in 2014, but I tried to install it. However, I uploaded all the files to my server but when I enter in the site it shows an empty page, without anything.

Have you got any idea about that? As an alternative I have thought to use Open Journal System, but there is several things that I have to change if I want to adapt it "correctly". Is stopped the development of OCS?

Thanks in advance!

Regards

**Comment by asmecher** [comment]
Closing in favour of https://github.com/pkp/pkp-lib/issues/2133. FYI, this issue tracker is a good place to go if you're fairly sure you're hitting a specific bug, but for general inquiries you might be better served by posting in the forum at http://forum.pkp.sfu.ca/.
