### ISSUE TITLE
[OCS] Virus Win.Trojan.Toa-5370166-0 detected

### ISSUE THREAD

**Issue by distriker** [pkp/pkp-lib#2133]
Hi everyone!

I am having problems with Open Conference System. I uploaded it with Filezilla and it doesn't show me the install process. I was trying again, but this time I use the hosting file manager. I received a bad surprise when I get an error in the uploading process: «El archivo que cargó, ocs-ocs-dev-2_3(2).zip, contiene un virus, por lo que se canceló la carga: Win.Trojan.Toa-5370166-0 FOUND» (in English, _The file that you load, ocs-ocs-dev-2_3(2).zip, has a virus, so the load was canceled: Win.Trojan.Toa-5370166-0 FOUND_»).

To verify that I analyzed the compressed file with VirusTotal and I got positive with two antivirus (ClamAV and Jiangmin). You can [check the result](https://www.virustotal.com/es/file/9113c7bb60766a8783cafc65b681bf5e0a6598a4bbb5398a6a4094e43567808c/analysis/1482787930/).

Could it have any relation with this issue #2132? I published some minutes before I detected that problem.

Thanks in advance.

Regards

**Edit:** I have found the virus in ocs-stable-2_3_6 and ocs-dev-2_3, but not in the 2.3.5 version [dowloaded from PKP website](https://pkp.sfu.ca/ocs/ocs_download/).

**Comment by asmecher** [comment]
@distriker, where are you getting these files from if not the PKP website?

**Comment by asmecher** [comment]
Closing for lack of input.
