### ISSUE TITLE
Improve password reset to use one-use, time-limited hash

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2135]
**Describe the problem you would like to solve**
Password reset is a two-step process that emails a temporary password and asks the user to change it on the next login. This can be confusing for users who are accustomed to receiving a one-time link to set a new password when they forget a password.

**Describe the solution you'd like**
When the user has forgotten a password, send an email with a one-use, time-limited link with a hash. When clicking on the link, they can change their password and regain access to their account.

**Who is asking for this feature?**
System administrators and some users.

**Additional information**
This post was updated by @NateWr on 2021-11-15 to reflect the discussion below. The following was the original post.

> Passwords should not be emailed. We had a discussion (@ctgraham, @asmecher) about this, see #745. IIRC, it was decided to keep the support for the `password` variable in legacy versions of the applications, but remove it completely from the master/dev branches, see #750. That was 2015.
> 
> In 2016, we got this: #1469 (OJS) and this #1524 (OMP).
> 
> And now, OJS 3 still sends unencrypted emails with passwords. I cannot see why, but maybe I missed something. I'd really like to see this changed, what do you think?

**Comment by TobiasWantzen** [comment]
What's the alternative? Spontaniously I'd send a temporary password by mail, valid for 2 hours, »User must change password on next log in.« activated.

**Comment by WaDelma** [comment]
Usually password resets are handled by sending link to change the password that can be only used one time and is only valid for certain time.

**Comment by asmecher** [comment]
As I understand it, we're emailing only temporary passwords when a change is required upon use, which is equivalent (in my opinion) to sending out a hash. There's at least one thing we could probably improve upon, which is a limited window for credentials (whether hash or password) sent in this way.

**Comment by ctgraham** [comment]
I prefer eliminating any use of a temporary password in favor of consistent use of a password reset hash.  The hash is a dedicated-use tool and is inherently time-sensitive.

**Comment by forgive38** [comment]
Hello,

Currently, with ojs 3.1.1, the process to reset a password is still in 2 steps:
1- receive a email with a one time link, then when you follow the link, you 
2 - receive a email with a temporary password, that you have to change the first time you use it.

I think the first step is enough.
One ambiguous thing for the second step, is the mail (email_text key="PASSWORD_RESET")
It is written "We have included your username and password in this email, which are needed for all work with this journal through its website." so I think the mail should be something like "the password included in this mail is temporary, you have to change it the next you log on the website"

thank you

**Comment by mtub** [comment]
@asmecher, @ctgraham - is there any chance of moving forward with this?

**Comment by asmecher** [comment]
(The two-step nature of the password reset email also came up in the latest email/notifications UI/UX review. Adding the UI/UX label.)

**Comment by jalperin** [comment]
+1 for eliminating 2-step password reset. The workflow I typically see is, click "forgot password"; get an email with a hash; click link and be logged in and prompted to set up a new password.

**Comment by touhidurabir** [comment]
@asmecher PRs to review 
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8450
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3632 [TEST ONLY]

will forward it to `main` once we finalise it for the `stable-3.3.0`

**Comment by asmecher** [comment]
Thanks and sorry for the wait! I've added comments here: https://github.com/pkp/pkp-lib/pull/8450#pullrequestreview-1209305982

**Comment by jalperin** [comment]
Do we still have the second email that sends you the password? I believe @mtub's request from 2016 (and my +1) are both asking for that second email to be removed. I have heard that this creates confusion multiple times, and it is also different from how _every_ password reset I have ever used works. 

In my view (and that of the vast majority of websites), it should work as follows: 
1. request reset
2. receive email with limited time hash
3. clicking link takes you to password reset form (already logged in, and with no need to enter temporary password)

Has there been discussion about switching to this simplified workflow?

**Comment by asmecher** [comment]
Thanks, @touhidurabir, I've tested this and it's a *lot* smoother. I've added a few review comments [here](https://github.com/pkp/pkp-lib/pull/8450#pullrequestreview-1217705617).

**Comment by touhidurabir** [comment]
@asmecher Updated PRs to review

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8450
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3632

If all ok, I will forward port it for the `OMP` and `OPS` of the `stable-3.3.0` and then will start working on `main` branch .

**Comment by asmecher** [comment]
Thanks, @touhidurabir -- two comments, but once those are addressed, please do go ahead and port to `main`, OMP, and OPS.

**Comment by touhidurabir** [comment]
@asmecher PRs

### Stable-3.3.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8450
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3632
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1288
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/423

**Comment by touhidurabir** [comment]
@asmecher PRs

### Stable-3.3.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8450
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3632
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1288
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/423

### main
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/244
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8512
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3686
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1291
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/426

**Comment by touhidurabir** [comment]
@asmecher All PRs have been rebased and passed the tests . 

@asmecher PRs

### Stable-3.3.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8450
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3632
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1288
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/423

### main
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/244
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8512
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3686
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1291
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/426

**Comment by asmecher** [comment]
@touhidurabir, I caught what I think are a few rebase issues in the PRs -- could you check those comments over and let me know?

**Comment by touhidurabir** [comment]
@asmecher I have fixed those accidental merge that happened during manual conflict resolving when rebasing, sorry about it . Please take a look now .

**Comment by touhidurabir** [comment]
@asmecher Updated PRs

### Stable-3.3.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8450
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3632
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1288
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/423

### main
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/244
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8512
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3686
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1291
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/426

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I've noted a couple of issues to fix with respect to `pageTitle` on https://github.com/pkp/pkp-lib/pull/8450 -- this tweak will also need forward-porting to `main`. Once both are ready, this is good for merging.

**Comment by touhidurabir** [comment]
@asmecher I have updated and forward port the requested changes to main . if the tests for `OJS` (both `main` and `stable`) passes, I will forward the submodule update for `OMP/OPS` .

**Comment by asmecher** [comment]
@touhidurabir Are these ready for another look?

**Comment by touhidurabir** [comment]
@asmecher build passed for the `OJS` in both `main` and `stable` so I have forward ported the submodule update for other  apps . here is the full PR list . 

### Stable-3.3.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8450
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3632
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1288
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/423

### main
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/244
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8512
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3686
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1291
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/426

**Comment by asmecher** [comment]
Thanks, @touhidurabir -- all merged!
