### ISSUE TITLE
[OMP]

### ISSUE THREAD

**Issue by almeidafilho** [pkp/pkp-lib#2137]
How can I resolve that?
ic method Application::getName() should not be called statically, assuming $this from incompatible context in /home/storage/7/e0/51/observaprocessos/public_html/revistaobservaprocessos/lib/pkp/classes/install/form/InstallForm.inc.php on line 144

Deprecated: Non-static method Application::getName() should not be called statically, assuming $this from incompatible context in /home/storage/7/e0/51/observaprocessos/public_html/revistaobservaprocessos/lib/pkp/classes/install/form/InstallForm.inc.php on line 146

Deprecated: Non-static method Application::getName() should not be called statically, assuming $this from incompatible context in /home/storage/7/e0/51/observaprocessos/public_html/revistaobservaprocessos/lib/pkp/classes/install/form/InstallForm.inc.php on line 148

Deprecated: Non-static method VersionCheck::getCurrentCodeVersion() should not be called statically, assuming $this from incompatible context in /home/storage/7/e0/51/observaprocessos/public_html/revistaobservaprocessos/lib/pkp/classes/install/form/MaintenanceForm.inc.php on line 37

Strict Standards: Non-static method Version::fromString() should not be called statically in /home/storage/7/e0/51/observaprocessos/public_html/revistaobservaprocessos/lib/pkp/classes/site/VersionCheck.inc.php on line 115

Deprecated: Non-static method PKPRequest::getUserVar() should not be called statically, assuming $this from incompatible context in /home/storage/7/e0/51/observaprocessos/public_html/revistaobservaprocessos/lib/pkp/classes/form/Form.inc.php on line 351

Deprecated: Non-static method PKPRequest::_checkThis() should not be called statically, assuming $this from incompatible context in /home/storage/7/e0/51/observaprocessos/public_html/revistaobservaprocessos/lib/pkp/classes/core/PKPRequest.inc.php on line 582

**Comment by asmecher** [comment]
@almeidafilho, before filing an issue, I'd suggest checking for existing posts in the support forum: http://forum.pkp.sfu.ca/
If you're unable to locate a similar post, try posting there. If it turns out to be a bug, we'll take care of migrating it over here.
