### ISSUE TITLE
Suggestions for Native XML Import

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#2142]
I am writing a script to automatically import articles/galleys via Native XML after copyediting has been done externally. The following suggestions for improvement came up:

  * Make `filesize` attribute on `<revision>` optional and derive the information from content of `<embed>`.
  * Make `user_group_ref` and `uploader` attributes optional and default to the importing user.
  * In OJS2, I had the possibility to set copyright holder and year via xml. I am missing this feature in OJS3.

My version is OJS 3.0.1

**Comment by asmecher** [comment]
Thanks for the feedback, @pkel. Good suggestions.

**Comment by ctgraham** [comment]
If the `user_group_ref` is optional, what should be the criteria for selecting one of potentially many user groups from a user?

**Comment by ctgraham** [comment]
Specifically for @asmecher or @bozana, if a User and Group is specified in the import, but the user specified does not currently have that group, is that an error, or is that acceptable?

**Comment by asmecher** [comment]
@ctgraham, I don't have a strong opinion on this either way -- potentially file under "enough rope to hang yourself".

**Comment by ctgraham** [comment]
If the user group is optional, I'm preferring any of the user's current groups which has access to the specified stage.
