### ISSUE TITLE
Offer option to suggest other reviewers when declining to review

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#2146]
When declining a review, the potential reviewer should be asked to suggest others. Right now, this could be done in an email, but it might be nice if the system offered a few rows asking for (name, email, notes), and if the editor could then easily those into a new user.  #featureRequest

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
