### ISSUE TITLE
[OJS 3.0.1] Release for OJS 3.0.1 is broken

### ISSUE THREAD

**Issue by kardeiz** [pkp/pkp-lib#2152]
The release for [OJS 3.0.1](https://github.com/pkp/ojs/releases/tag/ojs-3_0_1-0) is broken: it is missing the contents of `lib/pkp`.

**Comment by asmecher** [comment]
@kardeiz, where did you download the release from?

**Comment by kardeiz** [comment]
@asmecher from the link provided above: https://github.com/pkp/ojs/releases/tag/ojs-3_0_1-0.

**Comment by kardeiz** [comment]
Also, wow, that is a ton of changes for a single patch-level update!

**Comment by kardeiz** [comment]
Okay, I found a full release on the PKP website.

However, it looks like not all of the `__construct` commands were replaced. I'm getting tons of errors like:

    Call to undefined method PKPUsageStatsPlugin::PKPUsageStatsPlugin()

I started working my way through these, but stopped after a while

    Call to undefined method GenericPlugin::GenericPlugin()
    Call to undefined method PKPOpenurl10MetadataPlugin::PKPOpenurl10MetadataPlugin()
    Call to undefined method PKPMods34MetadataPlugin::PKPMods34MetadataPlugin()

**Comment by asmecher** [comment]
OJS 3.0.0 contains a lot of new code and thus there were a lot of changes/improvements with 3.0.1. And the constructor change hit a lot of files, even though it doesn't represent a functionality change. Anyway, as you've noticed, there's an OJS download page where properly-built releases go; the github download page just gives the repo contents.

**Comment by kardeiz** [comment]
Is there any point in having the GitHub releases, then? It seems unnecessarily confusing. I would suggest making the GH releases identical with the website releases, removing the GH releases page, or adding a note to each GH release that it cannot be used to run OJS. If I see a release page on a GitHub repo, I expect it to contain files that I can `make`/execute/use directly.
