### ISSUE TITLE
[OJS 3.0.0] meta and link tags in wrong place 

### ISSUE THREAD

**Issue by kardeiz** [pkp/pkp-lib#2153]
`templates/frontend/pages/article.tpl` dumps a lot of `meta` and `link` tags inside the HTML `body` with `article_googleScholar.tpl` and `article_dublinCore.tpl`. I'm not sure whether Google can read these tags in this location&mdash;my guess is not.

`meta` tags can only be outside the `head` element under certain conditions that are not met here. For more discussion, see this SO question: http://stackoverflow.com/questions/1447842/what-happens-if-the-meta-tags-are-present-in-the-document-body.

These tags should be redirected to the `head` element. I'm not sure whether there is an easy way to do this in the current template setup.

**Comment by asmecher** [comment]
See https://github.com/pkp/pkp-lib/issues/1815.

**Comment by kardeiz** [comment]
Whoops, sorry, didn't see that!
