### ISSUE TITLE
OJS install/upgrade documentation is slightly inaccurate

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2156]
Specifically:

- In OJS3, the language of the Full Package upgrade starts with a non-sequitur
- In OJS2 and OJS3, there is reference to copying the download's "config.inc.php", which does not exist.
- In OJS2 and OJS3, there is no mention of the GeoCityLite datafile in the install documentation

C.f.:
http://forum.pkp.sfu.ca/t/i-do-not-understand-the-procedure-of-upgrading-to-ojs-3-0-0/27314/2
http://forum.pkp.sfu.ca/t/runscheduledtasks-php-fails-in-ojs-3-0-1-call-to-undefined-method-scheduledtasktool-scheduledtasktool/25698/8

**Comment by ctgraham** [comment]
Pulls pkp/ojs#1174, pkp/ojs#1175, pkp/ojs#1176, pkp/ojs#1177 ready for review.

**Comment by asmecher** [comment]
All merged, thanks!
