### ISSUE TITLE
Bad link in Crossref settings form after pkp/pkp-lib#1498

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2164]
See: http://forum.pkp.sfu.ca/t/2-4-8-1-crossref-unregistered-page-still-calls-for-all-tpl/27535

CrossRef settings form still references "all" as the unregistered articles link, but this has been removed.
Change: https://github.com/pkp/ojs/blob/f246c7ba70b0f808f31532ca33107cb1203da168/plugins/importexport/crossref/classes/form/CrossRefSettingsForm.inc.php#L46

**Comment by ctgraham** [comment]
Master does not exhibit this issue because it somewhat awkwardly truncates the message as: "OJS will deposit assigned DOIs automatically to CrossRef. Please note that this may take a short amount of time after publication to process. You can check for all unregistered DOIs."

**Comment by bozana** [comment]
Aaaa... this was my mistake... Sorry... 
Yes, I left the sentence in the master branch without a link, in order not to change the locales so much... and it is just the next tab "Articles" on the same page... 
Thanks a lot @ctgraham! Can the issue then be closed?
