### ISSUE TITLE
Display author biographical information in OJS

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2174]
The author bios aren't displayed on the frontend if they exist.

This is just a placeholder issue for tracking. PR inbound soon.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/2175
https://github.com/pkp/ojs/pull/1186
https://github.com/pkp/omp/pull/379

**Comment by NateWr** [comment]
Tests passed! @bozana can you code review?

**Comment by Ph-We** [comment]
Just to remind, there is still no possibility to contact an author.

**Comment by NateWr** [comment]
I doubt we'll be exposing email addresses publicly, or implementing a publicly accessible form-to-email system. Those are big targets for spam bots.

**Comment by Ph-We** [comment]
Of course, we cannot allow exposing authors' emails. But the "Email the author (Login required)" functionality was always normal for OJS2, as well as for any other publishing system.

**Comment by NateWr** [comment]
Tests passed but a merge conflict arose. I've rebased again so should be ready for merge once it's passed code review.

**Comment by bozana** [comment]
@NateWr, looking all good :-) When OMP test is finish you can merge it... Thanks!!!

**Comment by NateWr** [comment]
Thanks @bozana, all merged!

Closing because I think this is an added feature and so doesn't need to be cherry-picked.
