### ISSUE TITLE
No Reviewers after upgrading from 2.4.8 to 3.0.1

### ISSUE THREAD

**Issue by RDerler** [pkp/pkp-lib#2176]
i don't know, if this is related to [https://github.com/pkp/pkp-lib/issues/2159](url), so i'm creating a new issue. 

after upgrading (did the upgrade multiple times to make sure) not a single article had reviewers and their reviews attached. the problem is, that the review_round_id in the review_assignments table is missing. 

editing 1000+ lines by hand to fix this would be super annoying, so is there a way to query that? so far i was not able to find a good solution. 

update:
the following line from the update script is never executed (3.0.0_update.xml): 
<query driver="mysql">UPDATE review_assignments ra, review_rounds rr SET ra.review_round_id = rr.review_round_id WHERE ra.submission_id = rr.submission_id AND ra.round = rr.round</query>

after executing it manually the missing ids are there.

thing is, driver="mysql" seems to be the problem. i'm using mysqli driver, so no line with driver="mysqli" is executed, or at least it seems that way

for testing i copied all lines with the mysql driver and changed the driver to mysqli. i'm testing now, but it seems to work.

**Comment by asmecher** [comment]
@RDerler, you're right -- the upgrade queries for which we needed different SQL syntax to support both MySQL and PostgreSQL specified the `mysql` driver, not the `mysqli` driver. The attached patches (both are equivalent) should add `mysqli` queries that are equivalent to the `mysql` ones. I'd suggest re-running the upgrade with this patch in place. Can you confirm whether that solves the issue?

**Comment by RDerler** [comment]
it does solve the issue, yes. but there are other files, not changed, having no mysqli queriey:
- indexes.xml
- counter_monthly_log_1_1.xml
- data-sql.xml

don't know if they matter. 

another issue i have is that the main admin is no admin after upgrade. the admin_group_id is set to 0, every time. solved it by setting it back to 1.

UPDATE `user_user_groups` SET `user_group_id` = '1' WHERE `user_user_groups`.`user_group_id` = 0 AND `user_user_groups`.`user_id` = 1;

**Comment by asmecher** [comment]
Ah, I grepped too narrowly. Changes were required to `dbscripts/xml/indexes.xml` and `plugins/generic/counter/counter_monthly_log_1_1.xml` as well, thanks.

**Comment by asmecher** [comment]
The issue with `user_group_id` in `user_user_groups` is interesting. The code responsible for populating that is `classes/install/Upgrade.inc.php` in `migrateUserRoles`:

    $userGroupDao->update('INSERT INTO user_groups (context_id, role_id, is_default) VALUES (?, ?, ?)', array(CONTEXT_SITE, ROLE_ID_SITE_ADMIN, 1));

...then a few lines lower...

    $userGroupDao->update('INSERT INTO user_user_groups (user_group_id, user_id) VALUES (?, ?)', array($userGroupDao->getInsertId(), (int) $row['user_id']));

The user group ID from the above insert should be fetched by the `getInsertId`, which maps to `getInsertId` in `lib/pkp/classes/security/UserGroupDAO.inc.php`:

    return $this->_getInsertId('user_groups', 'user_group_id');

...which uses the ADODB `po_insert_id` function, which should at last map (for `mysqli`) to `lib/pkp/lib/adodb/drivers/adodb-mysqli.inc.php` in `function _insertid()`:

    $result = @mysqli_insert_id($this->_connectionID);
    if ($result == -1){
        if ($this->debug) ADOConnection::outp("mysqli_insert_id() failed : "  . $this->ErrorMsg());
    }
    return $result;

Perhaps we're hitting http://stackoverflow.com/questions/15332250/why-is-mysqli-insert-id-always-returning-0.

I wonder if the `mysqli` driver is pickier about this function only working *immediately* after the last `INSERT` statement involving an autoincrement.

Could you try this, re-run the upgrade, and confirm if it improves things?

    diff --git a/classes/install/Upgrade.inc.php b/classes/install/Upgrade.inc.php
    index c10d0b4..5f894ed 100644
    --- a/classes/install/Upgrade.inc.php
    +++ b/classes/install/Upgrade.inc.php
    @@ -192,10 +192,12 @@ class Upgrade extends Installer {
     		// First, do Admins.
     		// create the admin user group.
     		$userGroupDao->update('INSERT INTO user_groups (context_id, role_id, is_default) VALUES (?, ?, ?)', array(CONTEXT_SITE, ROLE_ID_SITE_ADMIN, 1));
    +		$userGroupId = $userGroupDao->getInsertId();
    +
     		$userResult = $userGroupDao->retrieve('SELECT user_id FROM roles WHERE journal_id = ? AND role_id = ?', array(CONTEXT_SITE, ROLE_ID_SITE_ADMIN));
     		while (!$userResult->EOF) {
     			$row = $userResult->GetRowAssoc(false);
    -			$userGroupDao->update('INSERT INTO user_user_groups (user_group_id, user_id) VALUES (?, ?)', array($userGroupDao->getInsertId(), (int) $row['user_id']));
    +			$userGroupDao->update('INSERT INTO user_user_groups (user_group_id, user_id) VALUES (?, ?)', array($userGroupId, (int) $row['user_id']));
     			$userResult->MoveNext();
     		}

**Comment by RDerler** [comment]
yes, this does work. as far as i know it is generally recommended for mysql to grep die ID right after insert. i had this problem with the normal mysql driver too.

**Comment by RDerler** [comment]
next thing is, i need2fix the production DB, so im working on a script. basically i'm executing the missing queries now. so, if i am correcot, the only table i need to recreate from the old DB is articles_migration. script below:

CREATE INDEX issue_settings_name_value ON issue_settings (setting_name(50), setting_value(150));
CREATE INDEX submission_settings_name_value ON submission_settings (setting_name(50), setting_value(150));
CREATE INDEX submission_galley_settings_name_value ON submission_galley_settings (setting_name(50), setting_value(150));

UPDATE published_submissions SET date_published = NULL WHERE CONCAT(date_published) = '0000-00-00 00:00:00';
UPDATE review_assignments ra, review_rounds rr SET ra.review_round_id = rr.review_round_id WHERE ra.submission_id = rr.submission_id AND ra.round = rr.round;

CREATE TABLE articles_migration AS (SELECT journal_id, article_id, user_id, submission_file_id, revised_file_id, review_file_id, editor_file_id FROM articles)
UPDATE submission_files sf, articles_migration am SET sf.file_stage=2 WHERE am.submission_file_id=sf.file_id;
UPDATE submission_files sf, articles_migration am SET sf.file_stage=4 WHERE am.review_file_id=sf.file_id;
UPDATE submission_files sf, articles_migration am SET sf.file_stage=15 WHERE am.revised_file_id=sf.file_id;
UPDATE submission_files sf, articles_migration am SET sf.file_stage=7 WHERE am.editor_file_id=sf.file_id;
DROP TABLE IF EXISTS articles_migration;

UPDATE submission_files sf, submission_galleys sg SET sf.assoc_type = 521, sf.assoc_id = sg.galley_id WHERE sf.file_id = sg.file_id AND sf.submission_id = sg.submission_id;
UPDATE metrics m, submission_file_settings sfs SET m.assoc_id = sfs.file_id WHERE m.assoc_type = 515 AND sfs.setting_name = 'old-supp-id' AND sfs.setting_value = m.assoc_id;
UPDATE metrics m, submissions s SET m.pkp_section_id = s.section_id WHERE m.submission_id IS NOT NULL AND s.submission_id = m.submission_id;
UPDATE metrics m, published_submissions p SET m.assoc_object_type = 259, m.assoc_object_id = p.issue_id WHERE m.submission_id IS NOT NULL AND p.submission_id = m.submission_id;
UPDATE metrics m, issue_galleys ig SET m.assoc_object_type = 259, m.assoc_object_id = ig.issue_id WHERE m.assoc_type = 261 AND ig.issue_id = m.assoc_id;
UPDATE metrics m, submission_files sf SET m.representation_id = sf.assoc_id WHERE m.assoc_type = 515 AND sf.file_id = m.assoc_id AND sf.assoc_type = 521;
UPDATE metrics m, submission_galleys sg SET m.assoc_type = 515, m.assoc_id = sg.file_id WHERE m.assoc_type = 521 AND sg.galley_id = m.assoc_id AND ((sg.remote_url IS NULL) OR (sg.remote_url = ''));

CREATE TABLE counter_monthly_log ( year int(11) NOT NULL, month int(11) NOT NULL, journal_id int(11) NOT NULL, count_html int(20) NOT NULL DEFAULT 0, count_pdf int(20) NOT NULL DEFAULT 0, count_other int(20) NOT NULL DEFAULT 0, UNIQUE KEY counter_monthly_log_ukey (year,month,journal_id) );
DROP TABLE IF EXISTS counter_monthly_log_old;

**Comment by asmecher** [comment]
@RDerler, the `articles_migration` table is created during the upgrade process and doesn't exist outside the 3.x upgrade code. I'm not sure if that answers your question?

**Comment by asmecher** [comment]
> yes, this does work. as far as i know it is generally recommended for mysql to grep die ID right after insert. i had this problem with the normal mysql driver too.

Great, thanks for confirming. I've committed this to `master` and `ojs-stable-3_0_1` branches. Agreed that this is a good policy, but oddly, I've never had a problem with this code using the `mysql` driver and MySQL (5.5.53, FWIW).
