### ISSUE TITLE
Improve the how-to-cite content block on the article details page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2177]
The citation formats content block takes up a lot of real-estate. Most journal managers want to de-emphasise this block.

In the future, there may be dozens or hundreds of formats provided by CSL (https://github.com/pkp/pkp-lib/issues/723), so plan for having an unlimited number of potential formats.

From UI/UX Testing Outcomes: https://docs.google.com/spreadsheets/d/1RkZ0avL3UIUU-hUScbM77lLCsGtk-T2_dL-FEx_vKcM/

**Comment by asmecher** [comment]
At a glance, this appears to be a PHP-based CSL mapper, which would be graftable onto OJS using the filter framework without too much suffering: https://bitbucket.org/rjerome/citeproc-php

**Comment by NateWr** [comment]
Some work on a CSL implementation has been started in https://github.com/pkp/pkp-lib/issues/723

**Comment by asmecher** [comment]
(I think this one was already on your plate, @NateWr, but it wasn't assigned per Github.)

**Comment by NateWr** [comment]
This can be closed now that #723 is in.
