### ISSUE TITLE
Add nav menu management and static pages features

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2178]
Implement a control in the website settings to configure the navigation menus.

- [ ] Nav menu items should be able to be re-ordered and nested up to one level.
- [ ] Default menu items should be available for the homepage, announcements, current issue, issue archive, submissions, login and registration.
- [ ] Custom menu items should be able to be created. The user should be able to define content for each custom menu item in a large TinyMCE field. (This should effectively implement the old Static Pages plugin.)
- [ ] A new journal install should automatically configure a navigation menu with the default menu items as well as a custom menu item for About the Journal.
- [ ] Themes should be able to register the nav menu slots which are available, and a control should be available for each slot. (For instance, the default theme would offer a slot for the primary menu and a slot for the user menu.)

From the UI/UX outcomes spreadsheet: https://docs.google.com/spreadsheets/d/1RkZ0avL3UIUU-hUScbM77lLCsGtk-T2_dL-FEx_vKcM/

**Comment by asmecher** [comment]
@defstat, would you mind taking a look at this?

**Comment by defstat** [comment]
@asmecher @NateWr 
I think I am going to work on this like that:

I will make a new plugin (navigationMenusPlugin) which, upon installation will make a new tab at the WebsiteSettings page. Also the installation is going to add 2 tables in the database - navigation_menus and navigation_menu_settings.

The new tab's page is going to have a grid with all the menu items available for the menu.
There will be 2 kinds of menu items: the "default" which can't be erased or edited, and the "custom" that can be edited. 

All the menu items can be rearranged by rearranging the rows in the grid (like Sections for example)
I don't find any existing control that nests its components, so I think I will have to extend the "order" functionality with the ability for rows to be dropped  on other rows. In the DB that can be shown with 2 columns in the navigation_menus table: seq and assoc_id. The first shows the order of the menu items and the second the navigation_menu_id of the "parent" of a menu item, if nested.

The "edit" function of the editable menu items could provide 2 possibilities to the user
- add an existing path to the new menuItem
- add content and a new path to the newitem (maybe incorporating the code of the StaticPages Plugin)

That way, I think that we have the data to rewrite the frontend/components/primaryNavMenu.tpl and display the changes to the menu. 

I am not sure I understand the last point of the list above (Themes should be able to register the nav menu slots......). If we don't have something as an example, could you explain a little bit what we need?

**Comment by asmecher** [comment]
One thought -- perhaps this isn't a good candidate for a plugin, but rather to be built directly into the core. I don't think we'd be able to encapsulate it fully as a plugin, so there's no real benefit to implementing it that way, and some downsides (users could delete it, some aspects of plugin development are more convoluted than coding into the core, and some aspects of plugins e.g. upgrading schemas aren't well worked out yet).

**Comment by defstat** [comment]
@asmecher OK. 

Not sure if the approach described leaves anything uncovered, but I suppose we will see the result.

**Comment by ajnyga** [comment]
This is a plugin I made a couple of months back mainly to learn how to use the grid model in a plugin. Maybe the readme there is usefull in someway: https://github.com/ajnyga/navigation

**Comment by NateWr** [comment]
@defstat sorry for the late feedback. Your outline looks like you've got it pretty well covered. Here's some thoughts:

> I am not sure I understand the last point of the list above (Themes should be able to register the nav menu slots......). If we don't have something as an example, could you explain a little bit what we need?

Right now, our default theme has two different navigation menus:

![ojs-nav-menus](https://cloud.githubusercontent.com/assets/2306629/25221933/c592dcae-25ae-11e7-904c-f6e6bb6d9e35.png)

Another theme might choose to offer just one navigation menu area. Or maybe it will have three navigation menu areas. The idea is to have a theme define which nav areas it can support, so that the nav menu feature supports more than one possible navigation menu.

This is probably something you can ignore for the first iteration of the feature, but maybe something to consider if you want. Ideally, each theme would define a nav area with a unique name:

```php
/** In the theme initialization code */
$this->addNavMenu('primary');
$this->addNavMenu('user');
```

By using some common names (`primary`, `user`, `footer`), we can automatically re-assign existing nav menus when a theme is changed. But there may be cases where a theme switch leaves an existing menu unassigned, so this would need to be accounted for too (so that custom pages don't disappear).

> The new tab's page is going to have a grid with all the menu items available for the menu.

If you want to consider not using a grid for this, I think this might be one instance where it would make sense. All possible nav menu items will be displayed, so we don't need pagination or searching. And if you display items in nested lists, you can use the jQueryUI's draggable feature to automatically get simple ordering of nested items:

```
<ul>
  <li>
    About
    <ul>
      <li>Nested in About</li>
   </ul>
  </li>
</ul>
```

If that sounds like it's just getting more confusing, don't worry about it. A grid will work as well.

**Comment by defstat** [comment]
@ajnyga 
At the Website Settings of a Journal I added a tab with 2 Grids. 
The first one is for NavigationMenus and the second for NavigationMenuItems. 

Regarding the NavigationMenusGrid - The user can add a new NavigationMenu giving a title to it. There will be a database flag for each NavigationMenu that determines if its "defaultMenu" or not. "defaultMenus" are those that are specified by OJS installation and can't be edited - The user can add menuItems though and rearrange their order in the NavigationMenu.

Regarding the NavigationMenuItemsGrid - the user has an overview of all the NavigationMenuItems. The user can add a new NavigationMenuItem and declare its parent NavigationMenu from a dropdown list. he can also declare a localized title for the menu as well as a path.

I tried to check the  jQueryUI's draggable feature as another action of each NavigationMenu (along with edit, remove, etc) - There the user could be introduced with a page displaying all the NavigationMenuItems for the specified NavigationMenu. After that the user could rearrange the NavigationMenuItems, and nest them up to one level. Well, I didn't make it work, so I will add a dropdown to the NavigationMenuItem edit form, and populate it on NavigationMenu dropDown selection, giving the user the ability to select one parent NavigationMenuItem. I still have problems figuring out the ordering process of a NavigationMenu's Items. I could use an "order items" action to the NavigationMenu grid actions for each NavigationMenu. If you agree I will proceed like that, and try the JQuery solution again after adding the functionality.

There is the menuDefault flag at the database for the NavigationMenuItems as well, for the same purpose described earlier for the NavigationMenus. 

I also intend to add an enable/disable feature for both NavigationMenus and NavigationMenuItems. 

Database-wise I have added 4 tables for the feature:
navigation_menus
navigation_menu_settings
navigation_menu_items
navigation_menu_item_settings





Any thoughts?

**Comment by NateWr** [comment]
@defat, it sounds like you've got it basically in place. I have some thoughts about an alternative UI using the Sidebar grid as an example. You'll get drag-and-drop out-of-the-box, though nesting will still be an issue.

I'm guessing right now you've got something that looks like this:
![selection_033](https://cloud.githubusercontent.com/assets/2306629/26825443/eead070e-4aac-11e7-9db9-1f158f3151e7.png)

I'd suggest only showing the Navigation Menus grid. When a user clicks on the name of a Navigation Menu, it will launch a modal:
![selection_034](https://cloud.githubusercontent.com/assets/2306629/26825472/0b41fa8c-4aad-11e7-849d-ee350f5e5f4d.png)

This modal will contain a sortable grid (like the Sidebar) which will show menu items assigned to this menu (on the left) and all available menu items (on the right). Users can drag-and-drop the unassigned items onto the menu, and can create new items from the button at the top.
![selection_032](https://cloud.githubusercontent.com/assets/2306629/26825499/282519ea-4aad-11e7-813d-a00684ea58d9.png)

Nesting will still be an issue, but I don't think you can solve that with jQueryUI because the grids use tables. For the time being, adding a dropdown option to specify a parent should work.

The ther piece of this I didn't hear about is the navigation menu slots. These are named areas defined by the theme, and each menu should be able to be assigned to a menu slot.

Looking good! :+1:

**Comment by defstat** [comment]
@NateWr Yes I forgot about the "areas". I have them into the database table navigation_menus but I am not sure the best way to add them - I thought that we could add yet another grid there for "areas" and have a dropDown at navigation_menus edit page. 

On the other hand, would a plain string identifier "tagging" the navigationMenu be enough?

**Comment by NateWr** [comment]
I'd recommend that you just add it as a setting for each menu. So when creating or editing a menu, one of the fields is a dropdown list where they can select one of the areas to place it.

Also, when switching themes, it should maybe automatically assign menus to the areas when the area ids don't match.

**Comment by defstat** [comment]
@NateWr @asmecher 

PRs
OJS: pkp/ojs#1448
PKP-LIB: pkp/pkp-lib#2639

There are three main notions regarding the NavigationMenus feature:
1. NavigationMenus: It is a set of NavigationMenuItems, assigned to a theme navigationArea. There are three default 
                    NavigationMenus 'user', 'primary', 'footer'
2. NavigationMenuItems: It has a localized title which is displayed to the user if the parent NavigationMenu
                        is being displayed. It has 'page', 'op' and 'path' attributes that makes the redirection to the 
                        right internal URL, and in the case of custom (user defined) NavigationMenuItems, the user can define
                        the 'content' attribute, which will be displayed as a new OJS page (replacing functionallity of the StaticPages plugin).  
3. NavigationMenuItemAssignments:   It adds support for hierarchical rules regarding NavigationMenus and NavigationMenuItems. Each NavigationMenu
                                    supports any number of nested NavigationMenuItems, and each NavigationMenuItem can be child to any 
                                    other NavigationMenuItem, providing a two-level menu hierarchy.

The feature supports the following:
1.  Add NavigationMenus tables (4) upon OJS Installation
2.  Add default NavigationMenus, NavigationMenuItems and their relations (NavigationMenuItemAssignments) upon Journal creation
3.  Each Journal (context) has a management tab for NavigationMenus. There the user can manage (add/edit/remove) NavigationMenus
    and NavigationMenuItems
4.  A new control has been implemented (by Nate), for declaring the NavigationMenuItemAssignments in each NavigationMenu edit form.
5.  The user can add custom NavigationMenuItems and assign 'path' and 'content' attributes to it. That can replace the StaticPages plugin.
6.  There is support of 'default' NavigationMenus and NavigationMenuItems - Installed upon Journal creation. 
    - Default NavigationMenus can't be removed and the user can't change their title. 
    - Default NavigationMenuItems can't be edited/removed in any way.
7.  All context NavigationMenu feature related database rows will be deleted upon Context removal.
8.  Support of NavigationMenuItems installation/uninstallation by using XML files upon registering/unregistering Plugins and executing 
    form code (see Announcements feature)
9.  Support for declaring custom NavigationMenuAreas in themes, and assigning NavigationMenus to them. 
10. Mechanism for loading the areas (and the NavigationMenus assigned to them) to any template.
11. The 'user' NavigationMenu is being differently managed - it has items that can't be removed or changed and they depend on rules. 
    The user can add more NavigationMenuItems to the user NavigationMenu. These are going to be dispayed after the above mentioned items. 

The database:
1.  navigation_menus: Table for NavigationMenus
2.  navigation_menu_items: Table for NavigationMenuItems.
    -   default_id column adds a context-specific "id" for each NavigationMenuItem. It is defined in the installation XML files and 
        can be used for uninstalling the NavigationMenuItem by using the same installation XML files
3.  navigation_menu_item_settings: Table for localized NavigationMenuItems data.
    -   content
    -   title
4.  navigation_menu_item_assignments:   Table for assigning NavigationMenuItems to NavigationMenus and NavigationMenuItems to NavigationMenuItems
                                        hierarchy. Each row declares a hierarchical rule. The sequense of each NavigationMenuItem is declared
                                        here as well.

TODO? (discuss):
1. Site-wide support?
2. Support of default theme areas assignment to the NavigationMenus
3. Each context must have no less than one 'user' NavigationMenu assigned to the active theme.
4. Support of NavigationMenuItems where the user can define an internal (already existing) URL as its landing page, without 'content'.

**Comment by asmecher** [comment]
On default menus, I suggest allowing the user to do whatever they like with them, but warning them before they do something stupid (like deleting a default menu).

**Comment by asmecher** [comment]
It might also be necessary/worthwhile to allow menu items to go to arbitrary URLs, rather than describing targets using page/op. Page/op is sufficient for most things (and is good because it's resilient in the face of URL changes), but it's likely that users will want to be able to link outside that scheme.

**Comment by asmecher** [comment]
This will need some work to get the tests going -- see e.g. https://travis-ci.org/pkp/ojs/builds/251767159.

**Comment by NateWr** [comment]
@defstat The outline looks good. I haven't had a chance to give it a test drive yet but it sounds like you've covered just about everything. A couple initial thoughts:

1. Move the NavigationMenuItem title to the assignments database. That way a menu item can have a different title for each menu it's assigned to. (For instance, I might want it to be "Past Issues" in one menu and "Archive" in another. Or "Search this journal" in one and just "Search" in another.

2. For the check on whether a context is missing a user menu, I'd suggest moving the check to the special navigation menu items. And rather than enforcing a hard limit, show a warning message when no user links are assigned. Some people might hard-code these into a theme.

**Comment by NateWr** [comment]
@defstat Ok I've taken a look and done a pass on the code review. It's all shaping up really nice and has turned into quite a lot of work I can see. I'm going to throw you another curveball regarding the default types.

I had imagined each menu item type being a selectable option for a menu item, with the custom page content just one type among several built into the app. Here's a quick mockup:

![menu-item-types](https://user-images.githubusercontent.com/2306629/28317037-3a4ecbc6-6bbd-11e7-82ae-c544f33e6e6b.png)

This would prevent having duplicate entries in the default types (like About and About the Journal). And it would allow people to add multiple of the same type to a single menu. About and About the Journal is one example, based on our default menu setup. But someone else might want the following:

- Issues (`/issues/archive`)
-- Current Issue (`/issues/current`)
-- Past Issues (`/issues/archive`)

So instead of defining them as default items that are not editable, I'd see them as different types (or "Targets") that are defined in PHP and hooked so that plugins can add their own:

```
$types = array(
  'currentIssue' => $router->getUrl(...),
  'submissions' => $router->getUrl(...),
);
HookRegistry::call('NavigationMenus::Types', array(&$types));
```

The other thing we'll need is some kind of display callback which determines whether a menu item is displayed in current conditions. This will be necessary for Announcements and will help us get rid of the special user nav menu by allowing us to define display conditions for the user nav items.

I'd see the callback working like this: when retrieving items, run through a switch that can be hooked into for third-party plugins.

```
$menuItemType = $menuItem->getType();
switch ($menuItemType) {
  case 'announcements':
    // check if annoucements are enabled
    return $isAnnouncementsEnabled;
  case 'userProfile':
    // check if user is logged in
    return $isUserLoggedIn;
  case default:
    // Fire hook for determining display status of third-party types. Default: true
    $display = true;
    HookRegistry::call('NavigationMenus::DisplayType', array(&$display, $menuItemType));
    return $display;
}
```

This will allow the types to be extended by third-party plugins, and should allow us to conditionally display the user nav menu items like login/register.

**Comment by defstat** [comment]
@NateWr Regarding the "Move the NavigationMenuItem title to the assignments database.", we will have to, somehow, edit the Assignment. Do you think that we should extend the "Assignment Control" for that?

**Comment by NateWr** [comment]
@defstat Yeah. if you can set this up in the database, and assign the menu item title by default, I can pop in and update the control with an editing interface.

**Comment by defstat** [comment]
@NateWr I added the default title of an Assignment to be the title of its corresponding NavigationMenuItem - so I didn't really removed it from the Item object. (in the current configuration, if the user re-orders the Assignment, it resets the default title, because it removes and re-inserts the assignment)

I did try to add an "Edit" button to the assignment edit control, with no luck :)

I also added what Alec suggested - the support of custom URL on the NavigationMenuItem object and Form.

**Comment by NateWr** [comment]
@defstat great! I'd say work on the item types thing as the biggest priority. If we run out of time for OJS 3.1, we can ship navigation menus without the unique titles, and add that later. But I think getting the types down is going to be important if we can get that done in time to go out with 3.1.

**Comment by defstat** [comment]
@NateWr @asmecher 

- I added the NavigationMenuItem Type support using Service pattern
- I transferred some functionality in the above Service
- I also added the NavigationMenuItem Custom Url support
- I added a displayNavigationMenu callback and hook
- Solved some bugs regarding default (installed to every Journals at the start) navigationMenus and NavigationMenuItems, and edit NavigationMenuItems
- Did a little code cleaning and database column clean-up

The code is not ready for review, but the functionality described is.

The userNavBar of the master branch has become a little bit complex - Maybe we need some more code addition - a hook mabe - to add more "custom" navigationMenu parts - like additional navigation menu template - if that makes sense.

**Comment by asmecher** [comment]
@defstat, @NateWr is away for a week, but let me know if I can fill in e.g. on code review etc. in the meantime.

**Comment by NateWr** [comment]
@defstat I tried to take a look at this today but I'm running into a DB error:

```
DB Error: Unknown column 'nmh.navigation_menu_item_assignment_id' in 'field list'
```

I tried to run `php tools/upgrade.php upgrade` but that fails with the following error:

```
ERROR: Upgrade failed: DB: Incorrect table definition; there can be only one auto column and it must be defined as a key
```

**Comment by defstat** [comment]
@NateWr 
PR:
OJS: pkp/ojs#1448
PKP-LIB: pkp/pkp-lib#2813 (replaces pkp/pkp-lib#2639)

**Comment by NateWr** [comment]
@defstat I've added several comments in the code review. Here are a few more general comments:

- I'd like to indicate which navigation menu items have a conditional display of some kind when they're assigned to a menu. This could be an icon that, when clicked, opens a modal saying something like "This menu item and any sub-menu items will only be displayed when a user is not logged in."
- I'd like to see the menu item types have a description, which is displayed when that type is selected in the menu item add/edit form. Something like: "This type links to a page displaying the About the Journal content from Settings > Journal."
- I'd also like to indicate when a navigation menu item is a parent, that it's URL won't be accessible, and so the user should add a duplicate link below. This could be done with an icon and modal text as well.

I can work on this UI stuff if you'd like. I'd expand the `getMenuItemTypes` array to include more details about the item:

```php
$types = array(
  NMI_TYPE_ABOUT => array(
    'title' => __('navigation.about'),
    'description' => __('example.description'),
    'conditionalDisplayMessage' => __('example.message'),
  ),
  ...
);
```

Does that sound good?

**Comment by defstat** [comment]
@nateWr it sounds great, I will check the code review comments and try to fix them by tomorrow night, so we have a day to do more if necessary.

**Comment by NateWr** [comment]
Phew! So much code to review. Nice work @defstat!

@asmecher I've left a bunch of final comments on the last PRs. However, the functionality is in place and most of the comments are just small code formatting things. Only a few of them relate to strings. @defstat should be able to tidy just the string-related things up and you can merge the PR for the string freeze today or Monday. Then he can continue on the rest without effecting the string freeze.

I'd like another set of eyes (@asmecher or @bozana) just on the installation and upgrade scripts. I'm not very familiar that part of the system. If you could just take a look at that part and make sure it looks ok, then I think this is just about ready for merge.

PRs:
https://github.com/pkp/pkp-lib/pull/2813
https://github.com/pkp/ojs/pull/1448

**Comment by defstat** [comment]
Review changes made - all checks passed [https://travis-ci.org/pkp/ojs/builds/281654037?utm_source=github_status&utm_medium=notification]

PRs:
#2813
pkp/ojs#1448

**Comment by asmecher** [comment]
Oops, this didn't get ported to OMP master branch! @defstat, can you make that a priority? The master branch is broken until then.

**Comment by NateWr** [comment]
@asmecher that's my bad. I thought that we were ok going ahead to get this in for the string freeze. @defstat is already working on the OMP side and I think we should get it in today or tomorrow.

**Comment by ajnyga** [comment]
(offtopic: @NateWr, can you let me know when the string freeze starts so that I can prepare an update for the FI locale for 3.1)

**Comment by NateWr** [comment]
@ajnyga I think we're basically there, but talk to @mtub about that as he's the master of locales.

**Comment by defstat** [comment]
@asmecher sorry about that. 
@NateWr PRs:
OJS: pkp/ojs#1554
OMP: pkp/omp#446
PKP-LIB: #2831

**Comment by bozana** [comment]
@defstat and @NateWr, great work! 🥇 
If one of the existing "Navigation Menu Items" is edited "Custom Page" is always pre-selected as _menuItemType_, which is not correct (e.g. for "Editorial Team"), right? For those the appropriate _menuItemType_ (e.g. "Editorial Team") should be pre-selected, correct?

**Comment by NateWr** [comment]
Thanks @bozana! That's my fault. Looks like @defstat has already fixed it: https://github.com/defstat/pkp-lib/commit/51cf2a51f2f3ba7f9f4bdd04dcc8a0ed3bc9b01e

**Comment by NateWr** [comment]
OMP support merged now too! I've got one more change I'd like to do, which is to store a theme's nav menu areas in an array separate from the theme options. Ideally, theme options will only be used for user-configurable things that they can change under Settings > Website > Appearance. I can do that at any point before 3.1's release. Shouldn't be too tough.

**Comment by NateWr** [comment]
@defstat I missed the following PHP Notice that is getting thrown in OMP:

```
PHP Notice:  Use of undefined constant NMI_TYPE_CATALOG - assumed 'NMI_TYPE_CATALOG' in /var/www/html/omp/classes/services/NavigationMenuService.inc.php on line 73
```

**Comment by defstat** [comment]
@NateWr 
pkp-lib: #2839

**Comment by NateWr** [comment]
@defstat Actually, that should go into `omp` and the `ojs-specific` ones should go there.

**Comment by NateWr** [comment]
I implemented some small additions to the theme API to keep nav menus separate from theme options and make it a little easier for themers to interact with menus in the parent/child relationship.

PRs:
https://github.com/pkp/pkp-lib/pull/2841
https://github.com/pkp/ojs/pull/1563
https://github.com/pkp/omp/pull/447

**Comment by NateWr** [comment]
@bozana can you code review the PRs above?

Also, @defstat, it'd be good if you took a look as well. Just a minor change specifically for themers.

**Comment by bozana** [comment]
@NateWr, all great! :-)
What if I create a new navigation menu -- am I able to see it somewhere? How is this meant to be?
Thanks!!!

**Comment by NateWr** [comment]
Navigation menus are only assigned to a nav menu area. Areas are defined in your theme. So if your theme has:

```
$this->addMenuArea(array('primary','user'));
```

You'll only be able to assign a nav menu to one of those areas. Then in the theme template files you load the nav menu assigned to an area like this:

```
{load_menu area="primary"}
```

So if you wanted to place a new nav menu in your theme, you'd need to add the area to your theme. Then you can assign a nav menu from the backend to display there.

Make sense?

**Comment by bozana** [comment]
Thanks @NateWr! One more question :-\ What is then the drop-down "Active Theme Navigation Areas" ?

**Comment by NateWr** [comment]
These are the areas the active theme has registered, using `$this->addMenuArea()`. So your theme "registers" an area, and you can then assign a nav menu to it.

**Comment by bozana** [comment]
For example: I create a new navigation menu and select "primary" there, but this does not do anything i.e. does not display anything differently i.e. my new navigation menu is not displayed anywhere. Is this correct?

**Comment by NateWr** [comment]
You can only have one navigation menu assigned to each area, but I don't think there's any check or warning message in place if you assign two menus to one area. Do you already have another menu assigned to `primary`?

**Comment by NateWr** [comment]
You shouldn't see a navigation menu area appear as an option to be selected unless your active theme has registered it. And it's up to the theme to actually display any menu areas it has registered. But the default theme should only register `primary` and `user` and display both.

**Comment by bozana** [comment]
Ah, I can assign different nav menues to one area -- I just did it. And this is not supported i.e. considered here: https://github.com/NateWr/pkp-lib/blob/030d2237eb1d1780f3edd4b3cc7408593ac0e979/classes/template/PKPTemplateManager.inc.php#L1574-L1588
And in that case it is maybe also random which nav menu is find with that SQL statement.
Thus maybe not to list the areas already assigned (i.e. having a nav menu) in that drop-box?

**Comment by NateWr** [comment]
It would be good to throw a form validation error if someone tries to save a menu to a menu area that already has a menu assigned. But that would require a new string, so I think it's for 3.1.1.

**Comment by bozana** [comment]
Yes, OK. Actually the nav menu is then actually the same as nav area, and the nav menu title is not needed, right?

**Comment by bozana** [comment]
The PRs can be merged... :-) 👍

**Comment by bozana** [comment]
Maybe just a brainstorming: the other possibilities could maybe be:
-- not to display the "Add Menu" link if all nav menus i.e. areas are already there
or
-- to display the empty drop-down list for "Active Theme Navigation Areas"

**Comment by NateWr** [comment]
Thanks! I'll rebase them for merge.

> Actually the nav menu is then actually the same as nav area, and the extra nav menu title is not needed, right?

If someone swaps themes, a nav menu area may no longer exist, but we don't want to get rid of the nav menu. And a title just helps them identify it in the backend. But more clarity around this would be good.

> not to display the "Add Menu" link if all nav menus i.e. areas are already there

I want people to be able to create a menu without necessarily assigning it to a nav menu area. This can be useful if you're staging changes to your website, for instance.

> to display the empty drop-down list for "Active Theme Navigation Areas"

Yeah, I think letting them submit the form and then feeding back an error message if there's another nav menu assigned is a good way to inform them of the problem.

**Comment by NateWr** [comment]
Merged.

@defstat I think the only thing left is to split the app-specific menu item type constants into the apps. Would you like me to take care of that?

**Comment by asmecher** [comment]
@defstat, I think `registry/navigationMenuItems.xml` ius missing from both OJS and OMP, but is referenced from `lib/pkp/controllers/grid/admin/context/form/ContextSiteSettingsForm.inc.php`.

**Comment by defstat** [comment]
@NateWr @asmecher 
PRs:
PKP-LIB: #2839
OJS: pkp/ojs#1581
OMP: pkp/omp#448

**Comment by NateWr** [comment]
@defstat The PRs looks great. I've tested them and they all work fine. Just the OJS PR has a merge conflict that needs fixing. Let me know once that's done and I'll merge. :+1:

**Comment by defstat** [comment]
@NateWr Rebased and pushed.

**Comment by NateWr** [comment]
Sorry, one last request: can you move this comment up above the other two item definitions?

https://github.com/pkp/ojs/pull/1581/files#diff-e93fc0829668490f4cb23536dd68f8afR20

**Comment by defstat** [comment]
@NateWr sorry, lost it on conflict resolve. Just changed it

**Comment by NateWr** [comment]
All merged! I think... that... means we can close this issue! :tada:
