### ISSUE TITLE
CSRF check prevents notes from being deleted

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2182]
A note in the information center can't be deleted. The request fails to pass the CSRF check in `InformationCenterHandler::deleteNote()`, probably because it's missing a CSRF variable.

(Currently looking at it as part of #2163 so I'll report back when I find a solution. Just flagging this to ensure it doesn't get missed.)

**Comment by NateWr** [comment]
Yeah this was an easy one.

PR:
https://github.com/pkp/pkp-lib/pull/2183

@asmecher you mind code reviewing? I'm guessing this one is small enough it doesn't need tests but you know the CSRF stuff.

**Comment by asmecher** [comment]
Got it, thanks!
