### ISSUE TITLE
User group settings only installed for primary locale upon context creation

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2184]
See http://forum.pkp.sfu.ca/t/new-translation-getting-default-values-for-email-templates-article-components-and-role-names-after-upgrade-to-ojs3/27438/3 and https://github.com/ajnyga/pkp-lib/commit/235b4c0aafdf13dfe53c32c60c853fc6044d57ec.

**Comment by asmecher** [comment]
The issue seems to have been fixed for new journal creation via the UI, but not yet for the upgrade process. See http://forum.pkp.sfu.ca/t/problems-with-some-labels-when-changing-languages/31749 for details.

**Comment by bozana** [comment]
I've just tested it and had no problems -- the user_group_settings were inserted for all installed languages -- the change/commit above actually does solve also the upgrade problem: https://github.com/pkp/pkp-lib/commit/dc9e6c11f1a3c735414775a5e053321dce0e7d9f#diff-6993579cf500b691f53345aa057a4b02
Can this issue then be closed?

**Comment by asmecher** [comment]
Let's say yes!
