### ISSUE TITLE
[OJS] Tinymce in full screen mode problematic in multilingual journals

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2189]
In author guidelines selecting the full screen mode show the two other languages on top of the form:
![screenshot_62](https://cloud.githubusercontent.com/assets/16347527/21889968/24a807c8-d8d4-11e6-8440-56edd236023c.png)

This does not seem to happen for example with the competing interests field in the next tab.

**Comment by ajnyga** [comment]
That's with Firefox 50 in Win7, in case it is a browser issue.

**Comment by NateWr** [comment]
I'll take a look, but my guess is that full-screen editing mode is just not going play nicely with our multi-language input pattern. Getting them to work together might be a pretty big task that requires rethinking how we handle multilingual tinymce fields.

**Comment by ajnyga** [comment]
Hi, I do not think that this is that important. I just wondered why the same problem does not appear to happen with the competing interests field?

**Comment by NateWr** [comment]
Thanks for the heads up! I'll check out that field when I take a look. Maybe there's some simple `z-index` stuff we can do to improve things.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2588

Simple CSS fix. Self-merged.
