### ISSUE TITLE
[OJS] Issue Data -> Identification checkboxes are redundant

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2190]
On the Issue Data tab, editors can add volume/number/year/title information, and also toggle which elements are required via checkboxes. I think the checkboxes are a holdover from OJS 2, where JMs could indicate which elements are required by default. Given that there is no area where defaults can be indicated in the OJS 3 UI (as far as I can find), I think the checkboxes are redundant. Can we do away with these? 

<img width="814" alt="issuedataidentification" src="https://cloud.githubusercontent.com/assets/201446/21897051/d5087bea-d8be-11e6-84a1-e20dbba27514.png">

**Comment by asmecher** [comment]
@NateWr, I think you have a related/duplicate issue filed somewhere already?

**Comment by NateWr** [comment]
I've brought this up in the past. I'd like to get rid of the checkboxes. 

But if I recall, I was told that the checkboxes are there for display purposes. It's so that someone can add something (Vol/Num/Year/Title) but not have it be displayed on the frontend.

Personally I think it's not an option worth having. So I'm all for removing it if possible. :)

(I don't remember filing an issue specifically about this, though it's possible. I've filed so many! I did a quick search but didn't turn anything up.)

**Comment by jmacgreg** [comment]
Yeah, I did a search but couldn’t find anything either. I think it’s worth ditching. The OJS 2 paradigm wasn’t perfect either, and I think led to some minor but still irritating confusion over time. It should simply be an option of including/displaying this content if it’s included in the metadata itself. 

Cheers, 
James

**Comment by asmecher** [comment]
Before ditching this I think we should look at some example data from the wild.

**Comment by jmacgreg** [comment]
What kind of data are you looking for?

**Comment by asmecher** [comment]
I think a few sample archive listings where journals have a few issue naming types at play would help -- e.g. something that uses VNY but occasionally throws in a special volume or oddly-numberd issue.

**Comment by bozana** [comment]
Hmmm... Whatever someone is using, if we only display those fields that exist we could get rid of the checkboxes. Except in the case, when somebody wants to keep the info (e.g. volume, number or title) but do not want to show it -- which I do not know why would happen... Right?

**Comment by NateWr** [comment]
Related to https://github.com/pkp/pkp-lib/issues/2093.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
