### ISSUE TITLE
consider and migrate remote supp files as remote galley files

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2192]
currently the migration from OJS 2.4.x to OJS 3.0 does not consider the remote supp files.

**Comment by asmecher** [comment]
Deferred -- correct, @bozana?

**Comment by bozana** [comment]
yes, that's OK -- I hope not so many uses supp file and even less remote supp file, so that it is not such a big issue...

**Comment by bozana** [comment]
PRs:
ojs-stable-3_0_2: https://github.com/pkp/ojs/pull/1257

**Comment by bozana** [comment]
@asmecher, could you code review the PR above?

**Comment by asmecher** [comment]
Looks good, please go ahead!
