### ISSUE TITLE
[OJS] Upgrading to OJS3: reviewers can see the names of the authors

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2195]
After upgrading to OJS3 the `review_method` variable in `review_assignments` is handled differently, but the old values in that field are not updated during the migration. When adding a new assignment in OJS2 the `review_method` is set to '0'. OJS3 only uses values '1', '2' and '3'.

To make things worse, if you edit an review assigment in OJS3 it shows as if the review would be double blind although it is only showing that value, because it is the first item on the list.

The result seems to be that at least in some cases after upgrading to OJS3 the reviewers can see the names of the authors. We already had such situation.

If no better migration is possible, then the upgrade script should set that value to 2 for all reviews just in case.

I fixed this by updating the review_assignments assignments table with `UPDATE review_assignments SET review_method = '2'`

This is related to an older issue, but so important that I decided to make an independent issue instead
https://github.com/pkp/pkp-lib/issues/2173

**Comment by bozana** [comment]
I'll take a look...

**Comment by ajnyga** [comment]
Thanks!
Probably the value for double-blind reviews in OJS2 was '0'? In OJS3 that value does not exist anymore.

**Comment by bozana** [comment]
Yes, I think it would be best to set the value of the review_method to 2 (double-blind) when migrating, because, there was no such option in OJS 2.4.x, where a journal manager/editor could define the review method i.e. review method wasn't used. @asmecher, do you think this would be OK?

**Comment by bozana** [comment]
Alec said yes, so I will soon make a PR with a fix...

**Comment by bozana** [comment]
PRs:
ojs-stable-3_0_1: https://github.com/pkp/ojs/pull/1194

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR above?

**Comment by asmecher** [comment]
Just one minor comment, otherwise looks good, @bozana!

**Comment by bozana** [comment]
Thanks a lot @asmecher. I added the constant name and as soon as the tests are finished I will merge and cherry-pick...

**Comment by bozana** [comment]
Everything merged, thus the issue can be closed, I think.
