### ISSUE TITLE
[OJS 3.0.1] A reviewer has commented on "title" notifications should not go to other reviewers 

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2201]
A journal contacted me that OJS is sending a notification to other reviewers, when one of them has returned their review. In a double-blind review only the editor should know the names of the reviewers and the authors. Now, the other reviewers can see the name of the reviewers from the notification, from the sender address. Furthermore, while the other reviewer can not access the link included in the message, I do not get the point of sending such message.

Is there some logic behind this I do not understand?

If not, these lines here: 
https://github.com/pkp/pkp-lib/blob/master/classes/submission/reviewer/form/ReviewerReviewStep3Form.inc.php#L203-L204

Should be replaced with
>  // Never send reviewer comment notification to authors or to other reviewers
>  if ($userGroup->getRoleId() == ROLE_ID_AUTHOR || $userGroup->getRoleId() == ROLE_ID_REVIEWER || in_array($userId, $receivedList)) continue;

**Comment by bozana** [comment]
@ajnyga, I am not sure that this is the place in the code where that happens: as far as I could test it, the variable `$stageAssignemnts` here https://github.com/pkp/pkp-lib/blob/master/classes/submission/reviewer/form/ReviewerReviewStep3Form.inc.php#L193 gets only the appropriate users from the "Participants" list, that are also in the DB table `stage_assignments`, and the reviewers are actually not there -- mostly only authors and editors.
Also, the e-mail text that is send at that place in the code is "A reviewer has commented on "{$title}".". Thus, no link is there.
Thus, could you maybe send me the e-mail text, that those reviewers gets?

**Comment by ajnyga** [comment]
> 
> Sender: [Name of reviewer A] <[email of reviewer A]>
> Date: 9. tammikuuta 2017 17:49
> Recipinet: [Name of reviewer B]
> Subject: [NJ] New notification from [Name of journal] 
>  
> You have a new notification from [Name of journal] :
> 
> A reviewer has commented on " [Name of article] ".
> 
> Link: http://domain.fi/ojs/index.php/journalabbr/workflow/externalReview/1503
> 
> [Name of editor] 
> ----
> [Name of journal]

**Comment by bozana** [comment]
Oh, yes, that seems to be that e-mail...

**Comment by ajnyga** [comment]
As you can see, the sender is Reviewer A and the recipient is Reviewer B.

I asked the journal to check that B does not have other roles in the journal and according to them she does not have.

I was able to reproduce this and after applying the change above the issue was fixed. But I will double check this again with a fresh install of OJS3.

**Comment by bozana** [comment]
It must be then that place in the code. I just wonder, why it is not like that for me, in my local installation... I'll take another look...

**Comment by bozana** [comment]
Could it be that after the migration also reviewer are in the DB table `stage_assignemnts`?

**Comment by bozana** [comment]
Oh, I see, yes I think this is the case, the migration puts also the reviewer in the `stage_assignemnts` table. OK, then I think it would be best, to only get the editors at that place: `$editorStageAssignments = $stageAssignmentDao->getEditorsAssignedToStage($submission->getId(), $submission->getStageId());`
Because that e-mail should only go to the editors, right? This way we would be on the safe side... I believe...

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_0_1: https://github.com/pkp/pkp-lib/pull/2206

**Comment by bozana** [comment]
@asmecher, could you please also take a look at the PR above?

**Comment by ajnyga** [comment]
Thank you @bozana . I had a feeling this could be migration related. Your fix is definitely better than mine.

@asmecher, I wonder if having the reviewers in `stage_assignments` table affects something else?

**Comment by asmecher** [comment]
@bozana, I can't remember how/why we decided whether to include reviewers in `stage_assignments`. Could you do a bit of a survey to see whether this is required, and how consistent it is?

**Comment by bozana** [comment]
@asmecher, it is done here: https://github.com/pkp/ojs/blob/master/classes/install/Upgrade.inc.php#L361-L368, but in OJS 3 workflow they are not included in the `stage_assignments`, as far as I can see.

**Comment by asmecher** [comment]
It's intentional that reviewers don't get stage assignments in the workflow -- if that's not the case in the upgrade script, then yes, please remove it from there.

**Comment by ajnyga** [comment]
Hi, can you confirm whether there are any risks in having the reviewers in the stage_assignments?

**Comment by asmecher** [comment]
@ajnyga, I think this issue illustrates the risk -- that notifications can unintentionally be sent to reviewers.

**Comment by bozana** [comment]
@asmecher, shall we delete them, for those who already upgraded to 3.0.1, something like this:
`DELETE FROM sa USING stage_assignments sa INNER JOIN review_assignments ra ON (sa.submission_id = ra.submission_id AND sa.user_id = ra.reviewer_id) ` ?

**Comment by bozana** [comment]
@asmecher, I removed the insertion code from the Upgrade.inc.php + added SQL to remove those already inserted. Could you please take a look at both PRs above?

**Comment by asmecher** [comment]
@bozana, we're likely to run into cases where users are assigned as reviewers and other roles. OTOH you should be able to look at `stage_assignments.user_group_id` and then `user_groups.role_id` to determine more specifically which assignments are done for reviewer roles.

**Comment by bozana** [comment]
Ah, yes, you are right -- I'll do that check too....
I think I am going crazy from all those tables, columns, connections, if this than that, here like this but here like that... :-DDD

**Comment by asmecher** [comment]
<sub>We're all crazy here.</sub>

**Comment by bozana** [comment]
@asmecher, I also considered the check in the user_groups table. Could you please take a new look? THANKS!!!

**Comment by asmecher** [comment]
Excellent, thanks, @bozana! Please merge, and don't forget to forward-port to master.

**Comment by bozana** [comment]
Everything merged, thus closing...
