### ISSUE TITLE
[OJS 3.0.1] Automatic filename contains author name under double blind review

### ISSUE THREAD

**Issue by mittinatten** [pkp/pkp-lib#2202]
When a user submits an article to OJS 3.0.1 the files are assigned automatic file names, of the format `<author last name>, <original filename>`. Under double blind review, if the author doesn't manually edit the filename afterwards the author's last name is then visible to the reviewer, since the same filename is used for the review.

**Comment by ajnyga** [comment]
At least with our journals the original format of the files is:
[Username], [Role], [Filename]

And when the editor takes the submission to the review stage, it is automatically saved as:
[Role], [Filename]

These two formats are defined here:
https://github.com/pkp/pkp-lib/blob/master/locale/en_US/common.xml#L148-L149

Is your `common.file.anonymousNamingPattern` correct?

If these problems are with submissions that you have received using OJS2.x and have migrated to OJS3 later, then the issue could this: 
https://github.com/pkp/pkp-lib/issues/2195

**Comment by mittinatten** [comment]
Now I see I did a silly mistake, sorry for bothering. I called my test author "Test Author" and thought that Author was the last name and not the role. This issue was started because an editor said they could see the last name, but now I can't reproduce it, so I'll close this issue for now.
