### ISSUE TITLE
Notifications list in front end layout requires back-end JS tools

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2203]
See http://forum.pkp.sfu.ca/t/ojs-loading-eternally-when-trying-to-see-notifications/27601: the `notification` page attempts to to present a grid of notifications in a page using the front-end layout, which doesn't include JQuery. Thus a JS error occurs:

    Uncaught ReferenceError: $ is not defined(anonymous function)

**Comment by asmecher** [comment]
@NateWr, I suppose the simplest approach to fixing this would be to make that page use the back-end layout.

**Comment by NateWr** [comment]
No. I thought I'd turned that into a backend tab on the user profile page, but maybe I'm just remembering something I _meant_ to do.

**Comment by asmecher** [comment]
Mailing list stuff still needs a rewrite, but I've fixed the page layout to use the backend templates.
