### ISSUE TITLE
PostgreSQL Update Statements

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2208]
PostgreSQL Update Statements must not contain the updated table in the FROM part of the statement and thus, that table name cannot have an alias used in WHERE part of the statement. An example of a correct UPDATE statement is here: https://github.com/pkp/ojs/blob/master/classes/install/Upgrade.inc.php#L1632-L1635
S. also http://forum.pkp.sfu.ca/t/upgrading-ojs-2-4-8-to-3-0-1-files-not-visible-under-submission-workflow-view/27689

**Comment by bozana** [comment]
PRs:
ojs-stable-3_0_1: https://github.com/pkp/ojs/pull/1197

**Comment by bozana** [comment]
@mittinatten, could you please test the commit from the PR above and confirm if it works now? THANKS!!!

**Comment by mittinatten** [comment]
Works like a charm! Thank you so much, this really saved my day!

**Comment by bozana** [comment]
@mittinatten, there are a few issues related to the upgrade/migration that are still not solved/merged fully -- maybe you would like to take a look at those -- maybe you would like to wait till they are solved:
https://github.com/pkp/pkp-lib/issues/2201
https://github.com/pkp/pkp-lib/issues/2187
https://github.com/pkp/pkp-lib/issues/2159
https://github.com/pkp/pkp-lib/issues/2192
https://github.com/pkp/pkp-lib/issues/2173

**Comment by bozana** [comment]
Everything merged for this issue, thus closing...

**Comment by mittinatten** [comment]
We are a bit overdue with the upgrade already, so I would like to get it running as soon as possible. But as far as I could tell the issues mainly affected ongoing review processes? We only have a handful of those so I think we could be able to handle them manually, either by changing the database manually or by scripting some of the changes postupgrade, later.

**Comment by bozana** [comment]
OK...
