### ISSUE TITLE
Editorial actions do not appear when an editor assigns themselves

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2212]
If an editor assigns themselves to a submission, editorial actions (Send to Review, Accept, etc) don't appear until the page is refreshed. (To replicate, editors should not be assigned automatically.)

This issue was split off from #1853.

**Comment by NateWr** [comment]
PRs (tests running):
https://github.com/pkp/pkp-lib/pull/2229
https://github.com/pkp/ojs/pull/1210
https://github.com/pkp/omp/pull/384

This just reaches out manually from the participant grid in a bit of a hacky fashion. This is another time the global event router would be useful. But it should do for OJS 3.0.2 and I'll note it down for a refactor later.

This also solves the issue whereby the participant grid will not refresh when removing the last participant of a particular role. The whole grid refreshes.

**Comment by NateWr** [comment]
@asmecher Just a heads up that this should be ready to go if you're looking to clear the last Critical Issue from OJS 3.0.2. I've rebased and restarted tests due to some conflicts with DTD validation, so haven't been able to see results on JS tests. But hoping it's basically good to go.

**Comment by asmecher** [comment]
Merged, thanks -- it looks like there are some unrelated issues with JS linting, and I'll take care of those.
