### ISSUE TITLE
OJS3: Display <head> element from html galley file

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#2216]
add line:
`'htmlGalleyContents' => $this->_getHTMLContents(request, $galley),`
Into articleViewCallback function in HtmlArticleGalleyPlugin.inc.php for adding element into `<head>` from html galley file. Please revise this opportunity.

**Comment by asmecher** [comment]
@Vitaliy-1, could you open a pull request suggesting the change?

**Comment by Vitaliy-1** [comment]
I have only done commits to own repository for now. Is this process different than downloading branch, changing the file, and pull changes back from console?

**Comment by asmecher** [comment]
Try following this: https://help.github.com/articles/creating-a-pull-request/

**Comment by Vitaliy-1** [comment]
We are using this modification to insert highwire press tags into html galley page. Also for linking custom css and js - we prefer not to add them from smarty. Maybe someone would find it useful.  My pull request is on ojs master branch.
