### ISSUE TITLE
[OJS] Childtheme enabled and Static page plugin turned off breaks the search page

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2217]
I know, the title does not make sense, but that is exactly what is happening.

I have created a new theme for our site and have prepared modified child themes for our journals based on that theme. 

I noticed that entering the search page breaks the whole layout: CSS is not loading and neither are the modified templates in the theme folder. This is only happening in the search page, all other pages are working fine. I also noticed that in two journals the search page is working fine. No errors are visible in the error log. 

So, after looking into the differences these two journals had I noticed that they have the Static Page plugin enabled. And sure enough, after enabling the static page plugin the problems in the search page disappear.

This does not happen with a the main theme, only with the child themes.

OJS 3.0.1

**Comment by asmecher** [comment]
Mind taking a look, @NateWr?

**Comment by ajnyga** [comment]
I can rule out first whether it is only a problem with my own child themes. I will test this by Wednesday.

**Comment by NateWr** [comment]
Hi @ajnyga, can you provide me with one of the child themes that you're having trouble with? Or better yet a stripped down child theme where you can reproduce the problem?

**Comment by ajnyga** [comment]
Sure, I will send you one tomorrow.

**Comment by ajnyga** [comment]
Hi @NateWr 

I am totally out of answers here. I tried removing all the alterations I had to our theme, but still the problem persisted.

Then I chose an alternative route. I made a new copy of the default theme and renamed it to default2

I only applied these changes:
```
$ diff -r default default2
Only in default2: Default2ThemePlugin.inc.php
Only in default: DefaultThemePlugin.inc.php
diff -r default/index.php default2/index.php
19c19
< require_once('DefaultThemePlugin.inc.php');
---
> require_once('Default2ThemePlugin.inc.php');
21c21
< return new DefaultThemePlugin();
---
> return new Default2ThemePlugin();
diff -r default/locale/en_US/locale.xml default2/locale/en_US/locale.xml
15,16c15,16
<       <message key="plugins.themes.default.name">Default Theme</message>
<       <message key="plugins.themes.default.description">This theme implements the default theme.</message>
---
>       <message key="plugins.themes.default2.name">Default2 Theme</message>
>       <message key="plugins.themes.default2.description">This theme implements the default theme.</message>
diff -r default/version.xml default2/version.xml
14c14
<       <application>default</application>
---
>       <application>default2</application>
19c19
<       <class>DefaultThemePlugin</class>
---
>       <class>Default2ThemePlugin</class>

```
```
$ diff default/DefaultThemePlugin.inc.php default2/Default2ThemePlugin.inc.php
18c18
< class DefaultThemePlugin extends ThemePlugin {
---
> class Default2ThemePlugin extends ThemePlugin {
153c153
<               $this->addScript('default', 'js/main.js');
---
>               $this->addScript('default2', 'js/main.js');
179c179
<               return __('plugins.themes.default.name');
---
>               return __('plugins.themes.default2.name');
187c187
<               return __('plugins.themes.default.description');
---
>               return __('plugins.themes.default2.description');


```
https://drive.google.com/open?id=0B2-Fk_aieQXmYlBKYTFYU1NNREU

The problem is the same as above with this theme as well. The search page is broken, but enabling the static page plugin fixes it.

**Comment by NateWr** [comment]
Well this is a confusing one. Using your theme file, I tracked it down to a problem with `PluginRegistry.inc.php`. For some reason, only on the Search page, the `default2` plugin is just not getting registered here:

https://github.com/pkp/pkp-lib/blob/master/classes/plugins/PluginRegistry.inc.php#L141

If you inspect the `$plugins` variable after that call, the `default2` theme is not loaded on the Search page when StaticPages is enabled.

I wondered if this might be caused by `default2` getting converted to `default` through some kind of name sanitization process which stripped the `2`. So I renamed your sample theme to `defaulttwo` throughout, and lo-and-behold it worked.

I have no idea why this should be the case, and especially why it only happens when StaticPages is enabled and the Search page is being displayed. I had a quick look through the StaticPages plugin but nothing jumped out at me.

@bozana or @asmecher: are any bells ringing for either of you?

**Comment by ajnyga** [comment]
Thank you. Very weird. The theme I noticed this the first time is named "tsvJournal". I wonder if capital letters are a problem as well?

**Comment by asmecher** [comment]
Very weird, and not making much sense to me either. Just checking -- is it possible that at some point there was a mismatch between the entry for this plugin in `versions` (which gets installed based on the plugin's `version.xml`) and the name of the plugin (the directory it's installed in)? There is some plugin lifecycle voodoo that ties these together.

**Comment by ajnyga** [comment]
Hi, I will try different things. Even if the reason is what you say, I can not figure out why why it would only apply in the search page and be resolved by turning on the static page plugin.

**Comment by NateWr** [comment]
>  Just checking -- is it possible that at some point there was a mismatch between the entry for this plugin in versions (which gets installed based on the plugin's version.xml) and the name of the plugin (the directory it's installed in)?

Yeah maybe. I mean, I've just been changing the name as I go so could be some mismatch stuff. I can try it out on a fresh install and see if that helps.

**Comment by ajnyga** [comment]
Hi @NateWr 

I did an interesting experiment with this:

I activated a child theme AND activated Static pages plugins. The Search page works as described above. 

I then removed this whole section from the static pages plugin: https://github.com/pkp/staticPages/blob/master/StaticPagesPlugin.inc.php#L104-L143 => the Search page was still working.

BUT, when I removed also this line https://github.com/pkp/staticPages/blob/master/StaticPagesPlugin.inc.php#L102 => **the Search page was broken**, no CSS file is called.

I then opened `PKPPageRouter.inc.php` and added `$templateMgr = TemplateManager::getManager($request);` here https://github.com/pkp/pkp-lib/blob/master/classes/core/PKPPageRouter.inc.php#L200 => **the Search page started to work**. Also after totally disabling the Static page plugin.

So, I do not know what to think of this :)
