### ISSUE TITLE
OJS3: 'Phone' field 24-character limit

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#2218]
Hi! The character limit for the 'Phone' field is 24. This may not be enough in some cases.
E.g. in our case it might be something like 1 (111) 111-11-11, *111111 or even longer.

**Comment by asmecher** [comment]
@Ph-We, I've extended it to 32 in the master branch.

**Comment by Ph-We** [comment]
@asmecher, thanks!
