### ISSUE TITLE
Too many clicks required to approve publication formats in OMP

### ISSUE THREAD

**Issue by Glottotopia** [pkp/pkp-lib#2219]
#- remove popup when approving a publication format saying 
"Approve the metadata for this format. Metadata can be checked from the Catalog Entry panel."

- remove popup when approving a file saying "Approve this proof to indicate proofreading is complete and the file is ready to be published."

I have an edited volume with 28 chapters. I am happy with all chapters. I have to click 56 times on approve, and then I have to click 56 times on [OK]. Additionally, I cannot use Enter for some reason, and the popup has lag. 

Suggested behaviour: 
- no popup
- if the information is deemed necessary, use either a tooltip or a notification.

**Comment by asmecher** [comment]
@stranack, worth considering.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
