### ISSUE TITLE
[OJS 2.x] jbimages plugin appears on registration page

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2220]
The jbimages plugin appears in the TinyMCE tools on the registration page, but we expect that image uploading is restricted to logged in users only.  Reported:
http://forum.pkp.sfu.ca/t/tinymce-problem-with-user-registration-in-ojs/27738

**Comment by ctgraham** [comment]
Bump; review requested.

**Comment by asmecher** [comment]
Sorry for losing sight of this one, @ctgraham -- it looks good, thanks. Merged.
