### ISSUE TITLE
Allow users to browse announcements by announcement type

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2222]
It would be nice to have kind of announcements categories one could browse by, for example. S.  http://forum.pkp.sfu.ca/t/menus-announcements-oj-3-0-1-0/27758.
The minimal solution would be to allow a page "announcementType" that would get the announcement type ID as parameter and build the page similar to the current "announcement" page i.e. list all announcements from that category.
In another step, we could think about the layout and where to put them?

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
