### ISSUE TITLE
[OJS 2.x] Smarty doesn't understand Validation::isLoggedIn() in if statements

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2232]
The usage of `Validations::isLoggedIn()` in the smarty `if` statement at:
https://github.com/pkp/ojs/blob/e964621ad19ed8a8f435da02e3fe44734bb87ed2/templates/user/register.tpl#L16
results in the error message:
`Message: USER ERROR: Smarty error: [in user/register.tpl line 16]: syntax error: unidentified token '::isLoggedIn()'`

And similar for additional usages in this file.

**Comment by asmecher** [comment]
Good spotting -- thanks, @ctgraham!
