### ISSUE TITLE
Add hex value entry for colour picker

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#2242]
Right now the colour picker (e.g. on the Appearance tab of the Website Setting in OJS3) only supports choosing the colour by clicking. Therefore choosing exact colour values is quite hard.

The used colour picker comes with a option to enter rgb hex values when called with `showInput: true` as parameter.

Before: 
![without](https://cloud.githubusercontent.com/assets/23074158/22374822/0d565dc4-e4a8-11e6-84c0-8345390403be.PNG)

After:
![with](https://cloud.githubusercontent.com/assets/23074158/22374842/18fced6e-e4a8-11e6-895c-afad72203722.PNG)

Could provide a pull request if the change is approved.

**Comment by asmecher** [comment]
Please do, @MarHerUMR!

**Comment by asmecher** [comment]
Merged -- thanks, @MarHerUMR!
