### ISSUE TITLE
[OJS] OJS 3.0.1 Add reviewer modal not loading

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2249]
Hi,

One of our journals has an submission that has been made using OJS 3.0.1. They have started the review stage, but can not assign reviewers because the add reviewer modal is not responding. Firefox asks if you want to continue loading the script, but that does not help.

There are no errors in php error_log on no errors in javascript log. It seems that the script is stuck here:
![screenshot_94](https://cloud.githubusercontent.com/assets/16347527/22415439/1552fd8c-e6d0-11e6-83f4-83561cc53e2f.png)

Any idea how to debug this?

**Comment by ajnyga** [comment]
It seems to be something in the submission abstract that is breaking the script, because removing the abstract solves the problem. I will test what string is the reason and let you know.

**Comment by ajnyga** [comment]
Tagging @NateWr and @asmecher 

Short story short: If you have a string like `<15` in the abstract the above problem with adding reviewers will emerge. This does not happen if you have `< 15`.

No idea why.

**Comment by ajnyga** [comment]
This is maybe the same issue: 
https://github.com/tinymce/tinymce/issues/2567

**Comment by asmecher** [comment]
@ajnyga, is this an abstract that was entered into the system via the TinyMCE GUI (and thus should be properly escaped) or came in some other way (thus might not be properly escaped)?

Check in the database to see whether that abstract has the `<` encoded as `<`, or as `&lt;`.

**Comment by ajnyga** [comment]
Hi,

This is an abstact that was sent among the first ones after we moved to OJS3.
If I look at the source with tinymce, I see "&lt;"

Spocke in the above tinymce thread writes that "Properly encode your content. &amp;lt; not &lt; I guess we need to add some docs somewhere about how to entity encode HTML this issue seems to be reported from time to time."

**Comment by ajnyga** [comment]
edit: I checked the generated source at the metadata page and it has "`&amp;lt;15`"

But as I said, although I have entered that using tinymce and it seems to be escaped correctly, it is still causing the script mentioned above to time out.

**Comment by ajnyga** [comment]
Another detail. If there is not much content after `<15` you do not get this problem. But if there is for example a full paragraph of text following that, the script times out.

I was able to replicate this will a clean install of 3.0.1.

**Comment by ajnyga** [comment]
@asmecher,
The html variable that the loop has contains the review request letter, which in turn contains the abstract. This is what is sent to that script: 

`<span class="pkpTag mceNonEditable" data-symbolic="reviewerName">Name</span>:<br /><br />I believe that you would serve as an excellent reviewer of the manuscript, &quot; Kahden kierroksen artikkeli,&quot; which has been submitted to Scientific Journal. The submission's abstract is inserted below, and I hope that you will consider undertaking this important task for us.<br /><br />Please log into the journal web site by <span class="pkpTag mceNonEditable" data-symbolic="responseDueDate">Response Due Date</span> to indicate whether you will undertake the review or not, as well as to access the submission and to record your review and recommendation.<br /><br />The review itself is due <span class="pkpTag mceNonEditable" data-symbolic="reviewDueDate">Review Due Date</span>.<br /><br />Submission URL: <a href="{$submissionReviewUrl}"><span class="pkpTag mceNonEditable" data-symbolic="submissionReviewUrl">URL</span></a><br /><br />Thank you for considering this request.<br /><br />admin admin<br/>xxx@tsv.fi<br /><br />&quot; Kahden kierroksen artikkeli&quot;<br /><br />Sed ut perspiciatis unde <15 omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?`

As you can see, `<15` is not escaped.

**Comment by ajnyga** [comment]
I guess it comes down to this:
https://github.com/pkp/pkp-lib/blob/master/classes/mail/SubmissionMailTemplate.inc.php#L57
https://github.com/pkp/pkp-lib/blob/master/classes/core/PKPString.inc.php#L497

**Comment by asmecher** [comment]
Ah, I see -- now that we're supporting HTML in messages, I think the call to PKPString::html2text can be removed. Can you try that and see if it resolves the issue?

**Comment by ajnyga** [comment]
Hi,

Yes, removing html2text from https://github.com/pkp/pkp-lib/blob/master/classes/mail/SubmissionMailTemplate.inc.php#L57 solves this issue. I would do a pull request, but I have to get some sleep.
