### ISSUE TITLE
[OJS] Journals with publishing mode set to "none" should not send notifications when publishing an issue

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2250]
OJS 3.0.1.

We have a few journals that only use OJS for editing submissions and do not publish issues in their OJS journal.

Many of them usually ask what is the right time to "take out" the articles from OJS. I have usually responded that for better internal archiving they should basically assign the articles to issues and when an issue is ready, they should publish it.

This, however, creates a notification for authors and this is not something that these journals want. They have their own form of publishing autonomous from OJS (like paper). 

So, I suggest that when publishing an issue, OJS should check if the journal is actually using OJS for publishing and only in that case send the notifications.

**Comment by asmecher** [comment]
Thanks, @ajnyga!
