### ISSUE TITLE
[OJS 3.0]: Google Analytics Plugin double text

### ISSUE THREAD

**Issue by itssazzad** [pkp/pkp-lib#2253]
In OJS 3, the Settings text is doubled when clicking "OK" without putting "Account number" (mandatory field), and the user is returned to the Settings page.

![googleanalyticsplugin-settingsformissue](https://cloud.githubusercontent.com/assets/17194473/22476434/c983134e-e7b8-11e6-94ae-087a7932c76d.jpg)

**Comment by asmecher** [comment]
Fixed, thanks!

**Comment by itssazzad** [comment]
Thanks @asmecher!
