### ISSUE TITLE
Crossref 4.3.6 schema URL changed

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2258]
It seems that ULR for Crossref 4.3.6 schema changed. It is not http://www.crossref.org/schema/deposit/crossref4.3.6.xsd any more but http://www.crossref.org/schemas/crossref4.3.6.xsd. This should be fixed in OJS 2.4.8-1 and 3.0.2.

**Comment by bozana** [comment]
PRs:
ojs-stable-3_0_2: https://github.com/pkp/ojs/pull/1244

**Comment by bozana** [comment]
@asmecher, could you take a look? THANKS!!!

**Comment by asmecher** [comment]
Yup, looks good -- but I do still recommend asking CrossRef for a redirect.  Please commit & forward-port!

**Comment by bozana** [comment]
A OK I will then wait, to see what they will answer...

**Comment by bozana** [comment]
@asmecher, now that they redirect the schema, we do not have to consider this change any more? If using some other validator (and not the PHP), the XML files could still be invalid, right?

**Comment by asmecher** [comment]
Do you know if the new URLs are their preferred ones? I suspect they are. If that's the case, better to use them, I think.

**Comment by bozana** [comment]
@asmecher, how can the filters and filter groups in the DB be upgraded (e.g. the XML schema there)? Would upgrade do it automatically, or shall I write the appropriate SQL in an upgrade script? THANKS!

**Comment by asmecher** [comment]
Hmm, I think this will probably take manual SQL; I don't believe the filter stuff is prepared to update its own schema URLs in the case of a change.

**Comment by bozana** [comment]
@asmecher, could you please take a look at this PR: https://github.com/pkp/ojs/pull/1244 ?
Crossref told me that the new schema is http://www.crossref.org/schemas/crossref4.3.6.xsd which redirects to the https i.e. https://www.crossref.org/schemas/crossref4.3.6.xsd and confirmed me that they would be using the https URLs going forward. Thus, as you suggested, I changed the URL to the new https URL. 
Note: I haven't changed the xmlns, is that OK so?
If everything OK, I will then do the same for ojs-stable-2_4_8, ojs-dev-2_4 and master.

**Comment by asmecher** [comment]
That looks fine -- please port around. Note that we don't generally add database updates in stable branches. If we released OJS 3.0.2-1, for example, the upgrade from 3.0.2-0 to 3.0.2-1 wouldn't run this addition as currently written. However, it's going to be forward-ported into the 3.1.0 upgrade, and it's idempotent, so there's no risk in doing it in this case.

**Comment by bozana** [comment]
everything merged, thus closing...
