### ISSUE TITLE
Style the new plugin gallery

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2261]
Now that the plugin gallery is in operation, the plugin information could be presented a bit better.

This is a placeholder issue to stage PRs against.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2262

TESTS ONLY:
https://github.com/pkp/ojs/pull/1247

The new plugin detail view:

![selection_119](https://cloud.githubusercontent.com/assets/2306629/22658891/9670e686-ec93-11e6-89cc-a2157d724e23.png)

![selection_120](https://cloud.githubusercontent.com/assets/2306629/22658890/966f0a00-ec93-11e6-8b6d-220fdda548b2.png)

**Comment by NateWr** [comment]
Tests passed. @asmecher can you code review?

**Comment by NateWr** [comment]
Thanks @asmecher, I escaped the variable per your code review comment. I also tidied up the template a bit. Tests running again, but should be good to go.

**Comment by asmecher** [comment]
As usual, this is something it would've taken me way longer to make half as good. Thanks, @NateWr! Back-ported to `ojs-stable-3_0_2` as well.
