### ISSUE TITLE
Review master branch for dead/crufty code

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2265]
- Unnecessary subclassing in application repos
- Context depth cruft
- ...etc

**Comment by asmecher** [comment]
Pulls:
- https://github.com/pkp/omp/pull/390/files
- https://github.com/pkp/ojs/pull/1250
- https://github.com/pkp/pkp-lib/pull/2279

Some reverted stuff for later consideration:
- https://github.com/asmecher/pkp-lib/commit/8d489dbdb5d73bf61b1f2df6c0e7d94ed645f113
- https://github.com/asmecher/omp/commit/d0229e137ca901e33ef12266bab83a0c7c1099c4

**Comment by asmecher** [comment]
Existing OMP databases will require these queries to keep the Series Editor role working (already handled upon upgrade):

    UPDATE email_templates_default SET from_role_id=17 WHERE from_role_id=513
    UPDATE email_templates_default SET to_role_id=17 WHERE to_role_id=513
    UPDATE user_groups SET role_id=17 WHERE role_id=513
    UPDATE submission_comments SET role_id=17 WHERE role_id=513

**Comment by paflov** [comment]
Hi,
this commit breakes 
`php tools/upgrade.php upgrade`
for me, since the script is missing the class roleDAO:

> PHP Fatal error:  require_once(): Failed opening required '/srv/ojs3/classes/security/RoleDAO.inc.php' 
Best

**Comment by asmecher** [comment]
@paflov, which application are you using? Have you also pulled the master branch for the application repository?
