### ISSUE TITLE
Custom uploaded CSS files get loaded too early

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2266]
Their styles get overwritten by the main stylesheet. This is probably due to changes introduced to fix this issue:

https://github.com/pkp/pkp-lib/issues/2136#issuecomment-271819363

**Comment by NateWr** [comment]
Looks like we were never respecting the asset priority values, we just never noticed before because we were assigning the priority keys in the right order by accident.

PRs
https://github.com/pkp/pkp-lib/pull/2268

TESTS ONLY
https://github.com/pkp/ojs/pull/1249

**Comment by asmecher** [comment]
Thanks, @NateWr! Merged and cherry-picked over to `ojs-stable-3_0_2` as well.
