### ISSUE TITLE
[OJS 3.0] Disappearing Page Footer in the article page when "Recommend Similar Articles" plugin is enabled

### ISSUE THREAD

**Issue by itssazzad** [pkp/pkp-lib#2271]
In OJS 3.0, the page footer (powered by OJS | ...) is disappeared in the article page when "Recommend Similar Articles" plugin is enabled. 

![ojs3-page-footer-disappear](https://cloud.githubusercontent.com/assets/17194473/22707399/11eed43e-ed49-11e6-924f-126c2042ff96.jpg)

**Comment by bozana** [comment]
Hi @itssazzad, I am using current ojs-stable-3_0_2 branch and the footer does not disappear for me. Is it possible for you to test it with the current version? -- It seems that the problem has already been solved...

**Comment by asmecher** [comment]
@itssazzad, were you able to replicate this in the current version, or find anything relevant in your PHP error log?

**Comment by itssazzad** [comment]
@bozana : Thanks for looking into it! And sorry for not to answer you back earlier! Actually, I missed your reply!! Yes, now it works in OJS-3.0.2. I think the problem was in OJS-3.0.1. 

@asmecher : No, not able to replicate in the current latest OJS-3.0.2 version, :) I mean it seems the problem has been resolved in the latest version. 

BUT, the same problem is found for **"Lucene Search Plugin"**. When this plugin is enabled, the footer (powered by OJS | ...) is disappeared in the article page.

**Comment by asmecher** [comment]
@itssazzad, thanks -- the Lucene plugin has not been rewritten yet for OJS 3.x and will not work. It's excluded from the build package but present in the git repo.
