### ISSUE TITLE
Use DOI as the article link in citations

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2281]
When a persistent identifier, especially a DOI, is assigned to an article (or a particular galley), OJS should not give citation examples that include links to the journal website. This concerns citation plugins, especially "how to cite" and the BibTeX output.

(Random example from https://doi.org/10.5204/ssj.v7i2.336)

## BibTeX:

_What we have right now:_

> @article{SSJ,
	author = {Sally Kift},
	title = {The decline and demise of the Commonwealth’s strategic investment in quality learning and teaching},
	journal = {Student Success},
	volume = {7},
	number = {2},
	year = {2016},
	doi = {10.5204/ssj.v7i2.336},
	url = {https://studentsuccessjournal.org/article/view/336}
}

_What we should have:_

> @article{SSJ,
	author = {Sally Kift},
	title = {The decline and demise of the Commonwealth’s strategic investment in quality learning and teaching},
	journal = {Student Success},
	volume = {7},
	number = {2},
	year = {2016},
	doi = {10.5204/ssj.v7i2.336},
	**url = {https://doi.org/10.5204/ssj.v7i2.336}**
}

(With regards to DOI registries asking to always include the resolver link, this probably could also go a little further and have the doi link in the exact same form in the doi and the url field.)

## how to cite

Take this example:

> KIFT, Sally. The decline and demise of the Commonwealth’s strategic investment in quality learning and teaching. Student Success, [S.l.], v. 7, n. 2, p. 1-9, july 2016. ISSN 2205-0795. Available at: <https://studentsuccessjournal.org/article/view/336>. Date accessed: 10 feb. 2017. doi: http://dx.doi.org/10.5204/ssj.v7i2.336. 

Not only is this ugly, it encourages to use the journal url to cite this article and it doesn't reflect DOI styling guidelines. IMHO, this should read as

> KIFT, Sally. The decline and demise of the Commonwealth’s strategic investment in quality learning and teaching. Student Success, [S.l.], v. 7, n. 2, p. 1-9, july 2016. ISSN 2205-0795. Available at: **<https://doi.org/10.5204/ssj.v7i2.336>**. Date accessed: 10 feb. 2017.

**Comment by asmecher** [comment]
As with other citation-related tasks, it would be nice if we were able to tackle https://github.com/pkp/pkp-lib/issues/723 before refining these further.

**Comment by fgnievinski** [comment]
now that #723 is done maybe this could be closed

**Comment by asmecher** [comment]
Agreed, thanks!
