### ISSUE TITLE
[OJS3] Single Journal install homepage is awkward

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2282]
In the event of a single journal site installation, we suppress the Site Settings option:
https://github.com/pkp/ojs/blob/011f4dd67839ebf896645994ff0a12f5451e2b68/templates/admin/index.tpl#L27-L29

But the Site Settings holds the option for the Site index to redirect to the Journal index.  This leaves the site index just listing a single Journal, when we probably want the Site index to redirect to that single Journal.
![ojs-single-journal-site-index](https://cloud.githubusercontent.com/assets/7001322/22805248/ab0f5e16-eeea-11e6-9c1c-6626b41f37ca.PNG)

See also: http://forum.pkp.sfu.ca/t/single-journal-url-htaccess-configuration/27931

**Comment by asmecher** [comment]
The index page on a single-journal install should already redirect to the single journal, making the site settings page irrelevant. Do you have e.g. a second disabled journal or something?

**Comment by ctgraham** [comment]
No, this is a clean install of 3.0.2.  The only action taken post-install is to add the single journal.

**Comment by ctgraham** [comment]
I can replicate this on a box which doesn't have xdebug, and when I copy the install to a box with xdebug, it works as expected.  Grrrr.

**Comment by ctgraham** [comment]
Replicated this xdebug enabled.  The exact use case for me is `restful_urls` On, with mod_rewrite of:
```
<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteCond %{REQUEST_FILENAME} !-d
   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
   RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
   RewriteCond %{REQUEST_URI} !^.*/index.php/.*$
   RewriteRule ^/ojs/(.*)$ /ojs/index.php/$1 [QSA,L]
</IfModule>
```

With access to /ojs/ on the server, I get the following oddity:

- `$_SERVER['PATH_INFO']` = "/index.html"
- `$_SERVER['PATH_TRANSLATED']` = "/.../htdocs/index.html"
- `$_SERVER['PHP_SELF']` = "/ojs/index.html"

The result is that `PKPRequest::getRequestPath()` returns '/ojs/index.html', which totally screws with the expectations of `$router->getRequestedContextPath($request)` in `Handler::getTargetContext()`, and the logic falls through to return `null`.

This seems to be almost certainly a webserver configuration issue or bug.

**Comment by asmecher** [comment]
@ctgraham, you're assigned on this one -- is it something that you'll be able to put time into in the next couple of weeks? If not, we can probably reassign or reschedule.

**Comment by ctgraham** [comment]
I think this is a "not our problem" issue.  OJS is getting lousy PATH_INFO from PHP.  I don't think we want to maintain a workaround for it.   I think noting here the workaround of removing "index.html" from the [DirectoryIndex](https://forum.pkp.sfu.ca/t/single-journal-url-htaccess-configuration/27931/14) is sufficient.
