### ISSUE TITLE
[OJS 2.4.8.1] .gitignore bug

### ISSUE THREAD

**Issue by Looted** [pkp/pkp-lib#2285]
In .gitignore we have this line:

`config.inc.php`

which not only ignores config.inc.php in root path, but also lib/pkp/classes/config/Config.inc.php (which broke my deployment, I couldn't run the upgrade tool). Changing it to: 

`/config.inc.php`

fixes the issue. Should I make a PR for this?

**Comment by asmecher** [comment]
Please do!

**Comment by asmecher** [comment]
Thanks, @Looted!
