### ISSUE TITLE
ORCID button needs to be styled on registration page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2286]
![selection_131](https://cloud.githubusercontent.com/assets/2306629/22880524/6aa3b69a-f1da-11e6-9a82-60436da7fb48.png)

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/orcidProfile/pull/16

@bozana Mind doing a code review on this one?

**Comment by bozana** [comment]
@NateWr, sorry for no respond -- I was traveling for a few days -- will do it soon... :-)

**Comment by NateWr** [comment]
no problem, no hurry

**Comment by bozana** [comment]
@NateWr, this looks good. I do not have write permission on this repository, so maybe @asmecher can merge it?

**Comment by asmecher** [comment]
Merged, and also added @bozana to the contributors list!
