### ISSUE TITLE
[OJS 3.0.2] Can't switch to APA or CBE Citation Formats

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#2288]
If we try to switch to either APA or CBE the displayed format stays the same.
http://forum.pkp.sfu.ca/t/problem-with-first-name-displaying-in-citation/28641

**Comment by asmecher** [comment]
@Ph-We, I'm afraid I can't replicate this behavior -- both citation formats appear to work OK for me. Can you investigate further?

**Comment by Ph-We** [comment]
@asmecher, Yes, after some further investigation I've found that the issue is stably replicated only with Cyrillic entries. This might probably something akin to this:
http://forum.pkp.sfu.ca/t/problem-with-first-name-displaying-in-citation/28641/7

**Comment by Ph-We** [comment]
Here is an example: https://cmd-journal.hse.ru/article/view/2900

**Comment by asmecher** [comment]
@Ph-We, can you check your browser's console for a Javascript error?

**Comment by asmecher** [comment]
Using Firebug, I see that the response is blank; did anything show up in the PHP error log?

**Comment by Ph-We** [comment]
Hi @asmecher, I've traced the issue might be related to this error in PHP log:
`[19-May-2017 13:09:03 Europe/Berlin] Malformed UTF-8 characters, possibly incorrectly encoded`

**Comment by asmecher** [comment]
@Ph-We, I think this means that a call to PHP's `json_encode` encountered invalid character encodings. Is it possible that there is non-UTF8 data in your database, or that your database connection parameters in `config.inc.php` aren't appropriate for UTF8?

**Comment by Ph-We** [comment]
@asmecher, I could reproduce this with three different installations: productive, test, localhost. On the latter  there was only one article with most simple words in its title. And I did not touch `config.inc.php`. So I doubt there could be any non-UTF8 or malformed UTF8 data.

**Comment by asmecher** [comment]
@Ph-We, I suspect the message is coming from [JSONMessage.inc.php](https://github.com/pkp/pkp-lib/blob/ojs-3_0_2-0/classes/core/JSONMessage.inc.php#L165). In order to confirm that this is the case, and check what content is causing trouble, can you modify the file and change...

    error_log(json_last_error_msg());

...to...

    error_log(json_last_error_msg());
    error_log("Subject: " . print_r($jsonObject, true));

**Comment by Ph-We** [comment]
@asmecher, thanks, now I've got something more informative:
```
[26-May-2017 10:50:04 Europe/Berlin] Malformed UTF-8 characters, possibly incorrectly encoded

[26-May-2017 10:50:04 Europe/Berlin] Subject: Array
(
    [status] => 1
    [content] => 	

		РРІР°РЅРѕРІ, Р., &amp; 		РЎРёРґРѕСЂРѕРІ, Р.
(2017).
 РЎС‚Р°С‚СЊСЏ Рѕ РіР»Р°РІРЅРѕРј.
<em>Р–СѓСЂРЅР°Р» Рѕ Р¶РёР·РЅРё, 1</em>(1), 1-33.
doi:10.1234/.v1i1.3
    [elementId] => 0
)
```

So it seems to count any Cyrillic characters as malformed UTF8, since they really get malformed on some stage.

**Comment by asmecher** [comment]
Ah, @Ph-We, I found it. The Smarty `truncate` modifier was being used to get the author's first initial for both of those formats, and it's not UTF-8 aware. Try the patch attached to this issue.
