### ISSUE TITLE
[OJS] Missing Site Title

### ISSUE THREAD

**Issue by vedranvucic** [pkp/pkp-lib#2291]
Maybe we should separate somehow function of that in two parts. One part should serve for naming tab in browser and the other one for the purpose we have at the moment.
So <message key="common.openJournalSystems">Open Journal Systems</message>
can be named differently for the purpose of naming tab in browser and be kept with this name for the purpose we have now.

**Comment by asmecher** [comment]
See this forum discussion: http://forum.pkp.sfu.ca/t/how-to-change-title-in-browser-tabe-of-front-opage-of-multijournal-site-ojs-3-0-1-0/28649/5

**Comment by asmecher** [comment]
Thanks, @ctgraham! @vedranvucic, if you have a chance to validate the fix, it would be much appreciated.

**Comment by ctgraham** [comment]
Fix reported as broken here: https://forum.pkp.sfu.ca/t/how-to-change-title-in-browser-tabe-of-front-opage-of-multijournal-site-ojs-3-0-1-0/28649/15
