### ISSUE TITLE
[OJS] Returning to search from a search result leads to an expired document 

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2294]
Hi,

In OJS3 when you do a search, the form uses POST. This leads to a situation where a user clicks an article title and then tries to return back (using the browser back button like they usually do) to the search results, but ends up in `Document Expired` page. 

This could be easily fixed if the search would use GET instead of POST. Any reasons why it should not @asmecher?

**Comment by asmecher** [comment]
GET is fine with me -- IIRC we did this with OJS 2.x. Do you mind submitting a PR? Or I'd be happy to do it too :)

**Comment by asmecher** [comment]
Beware of https://github.com/pkp/pkp-lib/issues/2300 in fixing this!

**Comment by ajnyga** [comment]
Ok, so #2300 prevents from switching to GET? Or?

**Comment by asmecher** [comment]
You can switch to GET, but you'll need to address the way the form action URL is generated. When `disable_path_info` is on, it'll attempt to use URL parameters, which get clobbered by the form parameters.

**Comment by asmecher** [comment]
@ajnyga, I've just fixed https://github.com/pkp/pkp-lib/issues/2300 -- that change will need to be ported to the master branch in order to prevent that problem for recurring here when we move to GETs. Not the tidiest solution but plenty effective for the two cases we need it for.
