### ISSUE TITLE
[OJS] DevelopedByBlockPlugin error in a clean OJS 3.0.2 installation.

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#2296]
Installing a new OJS 3.0.2 from the tarball published here: https://pkp.sfu.ca/ojs/ojs_downloa

On first step, I get this error:
![image](https://cloud.githubusercontent.com/assets/2779168/23063895/445657c8-f50d-11e6-990b-629bd901df4c.png)

```
DevelopedByBlockPlugin::getSeq() should be compatible with BlockPlugin::getSeq($contextId = NULL) in /var/www/https/ojs-3.0.2/plugins/blocks/developedBy/DevelopedByBlockPlugin.inc.php on line 0

Warning: Declaration of DevelopedByBlockPlugin::getBlockContext() should be compatible with BlockPlugin::getBlockContext($contextId = NULL) in /var/www/https/ojs-3.0.2/plugins/blocks/developedBy/DevelopedByBlockPlugin.inc.php on line 0

Warning: Declaration of DevelopedByBlockPlugin::getEnabled() should be compatible with BlockPlugin::getEnabled($contextId = NULL) in /var/www/https/ojs-3.0.2/plugins/blocks/developedBy/DevelopedByBlockPlugin.inc.php on line 0
```

**Comment by asmecher** [comment]
@marcbria, you'll probably see several warnings like this -- they're cosmetic, and we'll gradually resolve them over the next few releases. I've fixed this one. I'd recommend directing error messages to a log file rather than the browser, as warnings in AJAX subrequests will cause the Javascript to fail in parsing responses.

**Comment by marcbria** [comment]
This first warining was the "tip of the iceberg". After this first page, you get a 500 error.

My testing server stack is: 
- Ubuntu 16.04.1 (LTS) up to date.
- Apache 2.4.18 (mod_rewrite)
- PHP 7.0.13
- MySQL 14.14 
- mod_ssl/2.4.18 (with let's encrypt)

1) Tarball downloaded from the OJS Download page (http://pkp.sfu.ca/ojs/download/ojs-3.0.2.tar.gz)
2) $ chmod www-data:www-data * -Rf
3) $ chown 774 * -Rf (not much happy with this, but it's a testing verion and I wanted to be sure we don't have a permissions' issue).
4) Staring web installation (same issue with commandline) and first page looks good (except for the waring errors reported before)
5) On submit... we get a 500 error.

Log shows this (sensitive data was anonymized):

`[Thu Feb 23 15:47:45.801168 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of ValidatorUrl::getRegexp() should be compatible with ValidatorUri::getRegexp($allowedSchemes = NULL) in /var/https/ojs-3.0.2/lib/pkp/classes/validation/ValidatorUrl.inc.php on line 19, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.801420 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of InstallForm::execute() should be compatible with Form::execute($object = NULL) in /var/https/ojs-3.0.2/lib/pkp/classes/install/form/InstallForm.inc.php on line 20, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.801527 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of UpgradeForm::execute() should be compatible with Form::execute($object = NULL) in /var/https/ojs-3.0.2/lib/pkp/classes/install/form/UpgradeForm.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.801701 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of InstallHandler::validate($request) should be compatible with PKPHandler::validate($requiredContexts = NULL, $request = NULL) in /var/https/ojs-3.0.2/lib/pkp/pages/install/InstallHandler.inc.php on line 20, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.805209 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of DevelopedByBlockPlugin::getSeq() should be compatible with BlockPlugin::getSeq($contextId = NULL) in /var/https/ojs-3.0.2/plugins/blocks/developedBy/DevelopedByBlockPlugin.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.805277 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of DevelopedByBlockPlugin::getBlockContext() should be compatible with BlockPlugin::getBlockContext($contextId = NULL) in /var/https/ojs-3.0.2/plugins/blocks/developedBy/DevelopedByBlockPlugin.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.805311 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of DevelopedByBlockPlugin::getEnabled() should be compatible with BlockPlugin::getEnabled($contextId = NULL) in /var/https/ojs-3.0.2/plugins/blocks/developedBy/DevelopedByBlockPlugin.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.811643 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of AbntCitationPlugin::fetchCitation(&$article, &$issue, &$journal) should be compatible with CitationPlugin::fetchCitation($article, $issue, $journal) in /var/https/ojs-3.0.2/plugins/citationFormats/abnt/AbntCitationPlugin.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.811723 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of AbntCitationPlugin::manage($verb, $args, &$message, &$messageParams, &$pluginModalContent = NULL) should be compatible with Plugin::manage($args, $request) in /var/https/ojs-3.0.2/plugins/citationFormats/abnt/AbntCitationPlugin.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.816178 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of PubIdImportExportPlugin::display(&$args, $request) should be compatible with ImportExportPlugin::display($args, $request) in /var/https/ojs-3.0.2/plugins/importexport/pubIds/PubIdImportExportPlugin.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.817253 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of OAIMetadataFormat_RFC1807::toXml(&$record, $format = NULL) should be compatible with OAIMetadataFormat::toXml($record, $format = NULL) in /var/https/ojs-3.0.2/plugins/oaiMetadataFormats/rfc1807/OAIMetadataFormat_RFC1807.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.817516 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of PKPOAIMetadataFormat_DC::toXml(&$dataObject, $format = NULL) should be compatible with OAIMetadataFormat::toXml($record, $format = NULL) in /var/https/ojs-3.0.2/lib/pkp/plugins/oaiMetadataFormats/dc/PKPOAIMetadataFormat_DC.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.817754 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of OAIMetadataFormat_NLM::toXml(&$record, $format = NULL) should be compatible with OAIMetadataFormat::toXml($record, $format = NULL) in /var/https/ojs-3.0.2/plugins/oaiMetadataFormats/nlm/OAIMetadataFormat_NLM.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.817977 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of OAIMetadataFormat_MARC::toXml(&$record, $format = NULL) should be compatible with OAIMetadataFormat::toXml($record, $format = NULL) in /var/https/ojs-3.0.2/plugins/oaiMetadataFormats/marc/OAIMetadataFormat_MARC.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.818169 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of OAIMetadataFormat_MARC21::toXml(&$record, $format = NULL) should be compatible with OAIMetadataFormat::toXml($record, $format = NULL) in /var/https/ojs-3.0.2/plugins/oaiMetadataFormats/marcxml/OAIMetadataFormat_MARC21.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.818997 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Warning:  Declaration of PayPalPlugin::displayPaymentSettingsForm(&$params, &$smarty) should be compatible with PKPPaymethodPlugin::displayPaymentSettingsForm(&$params, $smarty) in /var/https/ojs-3.0.2/plugins/paymethod/paypal/PayPalPlugin.inc.php on line 0, referer: https://myserver.mydomain.es/ojs/index.php/index/install
[Thu Feb 23 15:47:45.820863 2017] [:error] [pid 28311] [client 1.109.238.xxx:38182] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/https/ojs-3.0.2/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php:456\nStack trace:\n#0 /var/https/ojs-3.0.2/lib/pkp/lib/adodb/adodb.inc.php(558): ADODB_mysql->_connect('localhost', 'ojsuser', 'xxx', 'ojs_test_302')\n#1 /var/https/ojs-3.0.2/lib/pkp/classes/db/DBConnection.inc.php(144): ADOConnection->Connect('localhost', 'ojsuser', 'xxx', 'ojs_test_302', false)\n#2 /var/https/ojs-3.0.2/lib/pkp/classes/db/DBConnection.inc.php(119): DBConnection->connect()\n#3 /var/https/ojs-3.0.2/lib/pkp/classes/db/DBConnection.inc.php(106): DBConnection->initConn()\n#4 /var/https/ojs-3.0.2/lib/pkp/classes/db/DBConnection.inc.php(55): DBConnection->initCustomDBConnection('mysql', 'localhost', 'ojsuser', 'xxx', 'ojs_test_302', false, 'utf8')\n#5 /var/https/ojs-3.0.2/lib/pkp/classes/install/PKPInstall.inc.php(76): DBConnection->__construct('mysql', 'localhost', 'ojsuser', 'xxx', 'ojs_test_302', false, 'utf8')\n#6 /var/www/https in /var/https/ojs-3.0.2/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php on line 456, referer: https://myserver.mydomain.es/ojs/index.php/index/install
`

Tomorrow I will try with the git version (master branch) to see if the issue is with my stack or a general one with the tarball distribution.

Feel free to split this issue and close the first one.

**Comment by marcbria** [comment]
Worked like a charm :-)

Now you pointed, this line become pretty obvious:
> PHP Fatal error: Uncaught Error: Call to undefined function mysql_connect()

BTW, is it possible to catch this error and suggest mysqli instead of the default driver?

As far as I remember I'm installing this on an standard ubuntu, so I suspect some people will fall in the same hole.

Thanks!!

**Comment by asmecher** [comment]
@marcbria, glad to hear it's working. What I'd like to do is resolve all those strict-mode warnings so they're no longer an issue -- that way you'd get a single message that's to-the-point.
