### ISSUE TITLE
OJS3: special characters in "keywords" metadata field in the dashboard 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#2299]
![keywords](https://cloud.githubusercontent.com/assets/20665587/23068171/38f2beda-f52b-11e6-8acd-6a3938663caf.png)

The problem appears when trying to add cyrillic `б` symbol, which is situated at the` ,` on keyboard. So this is impossible to write all cyrillic words that have this letter. Only solution for now is copy-paste from text editor.

Another problem is not quite good behavior of this form when trying to place cursor inside it. 
1. There is a need to place it only right behind the last word. With the second locale its really uncomfortable. 
2. With second locale it is impossible to delete a keyword by pressing "red cross". It is only work with first locale field. Deleting anything there is possible only by backspace (one keyword by one).

**Comment by Ph-We** [comment]
See here: https://github.com/pkp/pkp-lib/issues/1828

**Comment by asmecher** [comment]
@Vitaliy-1, could you file this with the tag-it project over at https://github.com/aehlke/tag-it/issues? I don't think we have any control over that widget's key bindings.

**Comment by Ph-We** [comment]
Hi @asmecher, 
Unfortunately, this issue was reported several times there 4 years ago, and still is not fixed :(
https://github.com/aehlke/tag-it/issues/262
https://github.com/aehlke/tag-it/issues/251

**Comment by asmecher** [comment]
Yes, switching to another widget might be the best approach. I'd suggest working on that over on #1828 -- and tagging @NateWr, as he might have a suggestion or two on what to use.
