### ISSUE TITLE
Form method="GET" (default) does not work with `path_info_disabled` URLs.

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2300]
With `path_info_disabled = On`, generated URLs will include parameters e.g.:

    http://.../index.php?journal=a&page=b&op=c

When inserting these URLs into form actions...

    <form action="http://.../index.php?journal=a&page=b&op=c" method="GET">

...then form (with `method="GET"` or no method specified) will munge the supplied URL parameters, effectively stripping them off.

As a result, when using `path_info_disabled`, the search forms will not work. (Other forms IIRC all use `method="POST"`.)

**Comment by asmecher** [comment]
Suggested work-around: use `method="POST"` for search forms. This change will be needed in...

- plugins/blocks/navigation/block.tpl
- templates/search/search.tpl

**Comment by diegoabadan** [comment]
Hello, we noticed that after this modification the search via the navigation block failed in many cases.

The result looks like this:
Https://revista.enap.gov.br/index.php/RSP/index/search?simpleQuery=test&searchField=query
(not found)

For example, search from this page:
Http://revistas.facultyfacit.edu.br/index.php/JNT/issue/archive

There are two examples of journals I found on google using the latest stable release (2.4.8.2)

**Comment by bricas** [comment]
I can confirm what @diegoabadan is saying. Our search is now broken with this change. I reverted the commit on our install and search is functional again.

**Comment by diegoabadan** [comment]
@asmecher , Should I open a new issue?

**Comment by asmecher** [comment]
Filed at https://github.com/pkp/pkp-lib/issues/2442. Watch for a patch to appear shortly.
