### ISSUE TITLE
Permit searching by submission ID

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2306]
See http://forum.pkp.sfu.ca/t/ojs3-search-submissions-by-id/28860

**Comment by defstat** [comment]
@asmecher PR #2351

**Comment by asmecher** [comment]
Just a couple of comments over there -- looks good overall.

**Comment by defstat** [comment]
@asmecher

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by NateWr** [comment]
This is going to need some additional work if/when the new submissions list is merged in, since that offers a single search input that searches across a range of fields automatically.

I can see two possible routes: 1) detect if the `searchPhrase` is just an `int`. If it is, treat it like an ID search. 2) support the use of search prefixes like `id:1` for power users.

**Comment by asmecher** [comment]
I like Github's take on this -- see the drop-down to the left of the search box at https://github.com/pkp/pkp-lib/issues. I prefer having explicit control over what's searched where rather than hoping the system assumes correctly, and we'll probably want to add support for more ambiguous things like ISBNs, DOIs, etc. in the future.

**Comment by defstat** [comment]
So to understand the change better:

We need a drop down in the place of the "ID" label, with a number of choices (which?), and depending on the choice we are going to treat the input differently. 
Let's say there will be 2 choices, one for ID and one for ID Range, where the first will take as input an int and the other a pattern like [idFrom]-[idTo].

Am I missing something?

**Comment by asmecher** [comment]
It'll be something like that, @defstat -- but don't do anything yet; @NateWr is working on an alternative to the submission lists using some new tools (including Vue.js), and has just re-opened this issue so he knows something needs to be done on that toolset as well.

**Comment by NateWr** [comment]
The following PRs allow searching by submission ID. Basically, if an integer is entered into the submission list search panel, it also retrieves submissions that have that ID.

PRs:
https://github.com/pkp/pkp-lib/pull/2700
https://github.com/pkp/ojs/pull/1487

@asmecher I know you're wanting a more explicit search targeting feature. What do you think about having this simplified version for 3.1, then making a new issue for a future feature that supports explicit searching by ID, DOI, ISBN, etc?

**Comment by asmecher** [comment]
That makes sense to me, @NateWr. We've never had anyone ask for searching by other IDs, so I'm content to leave it until someone does.

**Comment by NateWr** [comment]
Woops, I got this confused with the other one you code reviewed and merged it. Just a few lines, mind glancing at it before I close this, @asmecher?

https://github.com/pkp/pkp-lib/pull/2700/commits/12b125e3be5cb224c098be499cc7ce9ccf489eea

**Comment by NateWr** [comment]
@asmecher Here's the PR removing the `count()`:

https://github.com/pkp/pkp-lib/pull/2709
https://github.com/pkp/ojs/pull/1492

**Comment by asmecher** [comment]
Looks good, please go ahead!

**Comment by NateWr** [comment]
Merged!
