### ISSUE TITLE
Autocomplete for reviewer interests is case sensitive

### ISSUE THREAD

**Issue by mittinatten** [pkp/pkp-lib#2309]
When I start typing a reviewer interest in OJS 3.0.2 I only get suggestions that match the case I'm using. If I type in the whole interest with the wrong case I still get the relevant hits, but no autocomplete suggestions.

**Comment by asmecher** [comment]
Either patch should work -- they're identical, just posted to different branches of `lib/pkp`. Thanks!

**Comment by mittinatten** [comment]
Thanks!
