### ISSUE TITLE
Prevent section editor auto-assignments outside section assignments

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2313]
See http://forum.pkp.sfu.ca/t/section-editor-is-assigned-automatically-in-ojs-3-0-2/28976/4 for details.

**Comment by asmecher** [comment]
PRs:

- https://github.com/pkp/ojs/pull/1283
- https://github.com/pkp/pkp-lib/pull/2314

**Comment by asmecher** [comment]
@bozana, could you take a look at these once the tests are finished? (No OMP PR -- just OJS and pkp-lib.)

**Comment by bozana** [comment]
@asmecher. looks good, please go ahead... :-)

**Comment by bozana** [comment]
Is this issue the same one: https://github.com/pkp/pkp-lib/issues/1962 ?

**Comment by asmecher** [comment]
I think so -- thanks, @bozana!
