### ISSUE TITLE
[OJS] uBlock Origin browser plugin causing problems in OJS 3.0.2

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2316]
Hi,

One of our journal editors noticed that when he had the uBlock Origin browser plugin enabled some of the features in OJS 3.0.2. stopped working.

For example when trying to view the editorial history page for a submission the content of the modal window kept on loading. I was first convinced that some error was causing this, but it turned out that simply disabling the browser plugin the editoria history page loaded without problems.

Probably uBlock Origin filters are catching something in the code that they consider to be an ad? I am using Adblock Plus and have not encountered anything similar.

**Comment by ajnyga** [comment]
The string that uBlock Origin is picking up is `/event-log/`

Basically the call to `http://domain.fi/journal/$$$call$$$/grid/event-log/submission-event-log-grid/fetch-grid?submissionId=60532&_=1488312791239` is blocked because of that string.

I can of course make an exception for a domain in the adblocker, but probably most of the users will not realize what the problem is.

**Comment by asmecher** [comment]
@ajnyga, thanks for tracking this down. I'm not sure whether there's anything we ought to do here, beyond noting it in case someone else hits the same problem. We also occasionally have similar run-ins with `mod_security` in other situations, and my feeling is that we shouldn't rename elements of the software to suit overreaching rules like this.

**Comment by ajnyga** [comment]
Yes agreed, there is not much sense in filtering `/event-log/` to start with in my opinion. Maybe it would be actually better to send a bug report to the plugin developer.

**Comment by asmecher** [comment]
Agreed, thanks!
