### ISSUE TITLE
PHP catchable error on issue import (OJS 3)

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2319]
I just tried to import some content that was exported out of one OJS instance into another OJS instance, but when I run

`php tools/importExport.php NativeImportExportPlugin import issues-1_2.xml journal username`

I get the following errors almost immediately: 

`[28-Feb-2017 21:05:50 Europe/Berlin] PHP Strict Standards:  Declaration of PublishedArticleDAO::getBySetting() should be compatible with ArticleDAO::getBySetting($settingName, $settingValue, $journalId = NULL, $rangeInfo = NULL) in /Users/jmacgreg/git/ojs3/classes/article/PublishedArticleDAO.inc.php on line 20
[28-Feb-2017 21:05:50 Europe/Berlin] PHP Catchable fatal error:  Object of class Journal could not be converted to string in /Users/jmacgreg/git/ojs3/lib/pkp/lib/adodb/adodb.inc.php on line 1017`

There are a bunch of "PHP Strict" warnings beforehand, but I think they can be ignored (except for maybe the one I included above). Any thoughts?

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1285

**Comment by bozana** [comment]
@jmacgreg, would it be possible for you to test the last changes: 
-- https://github.com/pkp/ojs/commit/a741ca02ed56f49a146babdd31bdc8cb77821388
-- https://github.com/pkp/pkp-lib/commit/043c4c8f388d246c2277b5d7c1fb430bec7618a3
There was also a bug in the export of submission language, so it would be good if you would also export the issue again (after applying these changes) before importing it... :-\
Thanks a lot!

**Comment by jmacgreg** [comment]
Thanks Bozana! I’ll give this a try, and ask the client in question to retry as well. 

Cheers, 
James

**Comment by jmacgreg** [comment]
Hi Bozana, all looks good to me - thanks for the quick fix!

**Comment by PyDeq** [comment]
Hello, please, when do you plan to release a new version of OJS? This (and one another) issue is blocking our effort to migrate to OJS.

**Comment by bozana** [comment]
@PyDeq, maybe you can apply the patches? Which is the other issue you are waiting for?

**Comment by PyDeq** [comment]
@bozana, yes, I guess I can apply the patches but if a new release is coming soon I'd rather wait for it.
The other issue is a problem with importing embedded PDF files. It throws an error because of a missing `TemporaryFileManager` import. It looks like it has been already fixed but I am not able to test it since 3.0.1 and 3.0.2 suffer from this issue.
