### ISSUE TITLE
ROLE_ID_SUBSCRIPTION_MANAGER

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2320]
This role id is used e.g. in the Upgrade.inc.php but it is nowhere defined...

**Comment by asmecher** [comment]
@stranack, the subscription manager is an OJS2 role that'll need some UI/UX consideration for OJS3. In our current role model, we've got a small number of roles, then flexible assignments of those roles to the various stages of the workflow. The subscription manager kind of falls outside of this; we could either add it as a role, with the stage assignment grid not used in this case, or we could e.g. add a stage for "distribution" that would grant e.g. assistant roles access to manage subscribers, payments, etc. I don't love either solution. Any other ideas?

**Comment by asmecher** [comment]
Re-added; the UI/UX issue WRT role administration remains, but dealing with that separately.
