### ISSUE TITLE
BFR and OFR plugin work

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2325]
BFR, s. http://forum.pkp.sfu.ca/t/how-to-archive-published-book-reviews-ojs-2-x/28685/8
-- consider actualizing status to published, when the review article was published
-- improve using the keyboard (tab key) to move down between the fields when entering data
-- provide migration to OFR
OFR, s. http://forum.pkp.sfu.ca/t/two-questions-about-objects-for-review-plug-in/17718/2
-- do not display empty metadata on the full object view page

**Comment by asmecher** [comment]
We also need to decide on how/whether to rewrite these plugins for OJS3, and how/whether to migrate data from the old 2.x OFR/BFR plugins.

**Comment by j-dornbusch** [comment]
Following [the debate on the forum](https://forum.pkp.sfu.ca/t/2-books-for-review-questions/29234/18), here is a link to our modified version of OJS with the "offer-to-potential-reviewer" feature.
https://github.com/dsi-ehess/ojs/tree/offer-to-potential-reviewer
It's a branch created from OJS 2_4_8 stable.
The workflow has become a bit more complex because it includes two new statutes, "proposed" and "accepted". This is why I could add a checkbox in the configuration to enable or not the feature.
Please note that on my working copy,  in order to load and reload the plugin with default email templates, I was forced to hack OJS core on [this line](https://github.com/pkp/pkp-lib/blob/73f7c9cb0dea8dc664c9bef61fc946da64729720/classes/install/Installer.inc.php#L153).
I replaced
`if (!isset($this->installedLocales)) {`
by
`if (empty($this->installedLocales)) {`
Because at runtime, installedLocales is an empty array and templates are not loaded to database. I do not know if this change is relevant.

**Comment by ajnyga** [comment]
Our journals did not use the plugin in OJS2 so I do not have a thorough knowledge on how it works. However, I have talked with our National Library about the possibility to attach book related metadata to book (or other) reviews that are published as common articles in OJS.

I have been thinking of tackling it with a plugin that would do roughly the following:
- Add selection to section settings where you can define, that this is a section for reviews
- For the articles in that sections the metadata form (beginning from the submission) will show a grid where you can enter the data of the object of review (you could use a lot of the code in funding plugin). The source of these objects could be a) A public list of objects which will return, in the case of books, at least the ISBN (unfortunately I have not found that sort of list with an API) b) a list of objects maintained by the journal or c) a possibility for the author to create a new object.
The important thing here is that for books you always use the ISBN as the identifier. In our case this will help the National Library to connect reviews and books with precision.
- In the plugin settings you have the means to maintain a list of review objects and the created objects are saved to the database.
- You will have a public handler to show that list on a public page
- When the article is published, the plugin will show the book metadata on the article page and the metadata can also be added to OAI-PMH (I have not checked if CrossRef exports for example support adding review object data).

**Comment by asmecher** [comment]
@ajnyga -- yes, your ideas parallel exactly what I was thinking!

**Comment by bozana** [comment]
s also this old issue: https://github.com/pkp/pkp-lib/issues/1718#issuecomment-239039096

**Comment by mtub** [comment]
Any update on this? I like @ajnyga's ideas to have a better link with metadata sources such as national libraries, but I also think it is important to port the existing plugin to OJS3 and to have some way of migrating data (i.e. the existing book/object metadata).

**Comment by asmecher** [comment]
This is something @sfbetz has been thinking about redesigning, but I suspect summer chaos reigns!

**Comment by mtub** [comment]
While I was hoping for an OJS 3 port to be available sooner, this might also be something for the next sprint…

**Comment by asmecher** [comment]
NOTE: The `Upgrade` script currently includes the `objects_for_review_settings` table in its locale name migration from `sr_SR` to `sr_RS@latin`, but there is currently no table definition to extend the table length to accommodate the new contents. I'm leaving this as a manual intervention for the users who use both objects for review and `sr_SR`, which will be few, but it would be nice to correct this once the OFR plugin is rewritten. (See https://forum.pkp.sfu.ca/t/database-upgrade-error-when-upgrading-to-3-1-1-2/46553/5 and following post.)

**Comment by jmacgreg** [comment]
@ajnyga has been working on a rewrite of the OFR plugin, which can be found here: https://github.com/ajnyga/objectsForReview/. This work was started in the Heidelberg spring (outcomes and status document here: https://docs.google.com/document/d/1QOv1gxJZ1U5Pyjcf77Ml5kHKmfs9O4_7ctPJryUtWjI/edit#). This Github entry should probably stay open for now, as there will have to be some additional DB cleanup considered if folks start to use the new plugin, but I'd suggest that anyone who's looking for an updated plugin keep follow @ajnyga's progress in his repository.

**Comment by asmecher** [comment]
At this point I think it's best to recommend https://github.com/ajnyga/objectsForReview/ for this work in the future. It is unlikely that we're going to be able to prioritize further work on the old OFR and BFR plugins given that they have large codebases and a limited set of users.
