### ISSUE TITLE
ArticleSearchIndex::_updateTextIndex() clears prior indexed content

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2327]
Calls to `ArticleSearchDAO::insertObject()` in [OJS 2.4.8](https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/search/ArticleSearchDAO.inc.php#L159-L189) and [OJS 3.0.2](https://github.com/pkp/pkp-lib/blob/ojs-stable-3_0_2/classes/search/SubmissionSearchDAO.inc.php#L89-L117) clear existing object keywords if they exist.

The function `ArticleSearchIndex::_updateTextIndex()` calls `ArticleSearchDAO::insertObject()` in [2.4.8](https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/search/ArticleSearchIndex.inc.php#L379-L391) and [3.0.2](https://github.com/pkp/ojs/blob/ojs-stable-3_0_2/classes/search/ArticleSearchIndex.inc.php#L305-L318).

The function `ArticleSearchIndex::_updateTextIndex()` is called sequentially with the same arguments in subroutine [`ArticleSearchIndex::articleFilesChanged()`](https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/search/ArticleSearchIndex.inc.php#L148-L152) because both [`ArticleSearchIndex::articleFileChanged()`](https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/search/ArticleSearchIndex.inc.php#L114) and [`ArticleSearchIndex::suppFileMetadataChanged()`](https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/search/ArticleSearchIndex.inc.php#L213-L225) (via `_updateTextIndex()`) call `insertObject()` on the same file id.

The result is that the fulltext object keyword relationships for supplemental files are lost.

**Comment by ctgraham** [comment]
Similarly here: https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/submission/form/SuppFileForm.inc.php#L255-L276

My first thought was to add a new constant ARTICLE_SEARCH_SUPPLEMENTARY_FILE_METADATA to ArticleSearch.inc.php, but this would potentially confuse the mapping of `ArticleSearch::getIndexFileMap()` and dependencies of the use and display of two different search bitvalues mapped to a single search "field"?

An alternate approach is to provide a parameterized flag to ensure calls can avoid clearing existing keyword relationships when adding additional keywords to an object.

**Comment by ctgraham** [comment]
`ArticleSearch::_indexObjectKeywords()` assumes a empty index, so parameterizing a flag to to avoid clearing existing keywords starts to get messy quickly.

**Comment by asmecher** [comment]
Thanks, @ctgraham -- merged and ported to `ojs-stable-2_4_8`.

**Comment by ctgraham** [comment]
@asmecher, it looks like forward porting this to 3.x is unnecessary because 3.x doesn't index the metadata for files, only metadata for articles?  Am I reading that right in ArticleSearchIndex.inc.php and SubmissionSearchIndex.inc.php?

**Comment by asmecher** [comment]
OJS 3.x doesn't include a separate "supplementary files" set, so those are no longer indexed per the code that was problematic here.
