### ISSUE TITLE
Postgres-problems with PKPUserDAO

### ISSUE THREAD

**Issue by mittinatten** [pkp/pkp-lib#2329]
Postgres only supports single quotes for values, as in `WHERE field = '...'`. The function `getUsersByField(...)` in `PKPUserDAO`, has double-quotes around `CONTROLLED_VOCAB_INTEREST`.

Here's a patch https://github.com/pkp/pkp-lib/commit/569e33ef0385e934ce7879f8a7a98297977bb74f.

As far as I can tell this shouldn't have any negative consequences for MySQL but haven't been able to test it.

**Comment by bozana** [comment]
Hi @mittinatten, would you like to make a PR?

**Comment by bozana** [comment]
PR merged and cherry-picked to master, thanks a lot @mittinatten! Closing...
