### ISSUE TITLE
[OJS] Enable editors to edit page numbers from the issue TOC view

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2330]
In OJS2 the editors were able to edit the page numbers from the TOC view. This is a feature many of our editors have requested to OJS3 as well. I realize that the TOC view should be kept as clean as possible, but managing the pagenumbers only via the "Schedule for publication" modal is cumbersome.

**Comment by pmangahis** [comment]
+1 from hosted client

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
