### ISSUE TITLE
Clean up TemplateManager::display / TemplateManager::fetch

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2336]
PHP7 doesn't like these functions' liberal overrides of parent function parameter lists. `fetch` and `display` are also intertwingled -- each should call its parent, rather than the current practice of `PKPTemplateManager::display` delegating to `PKPTemplateManager::fetch` and avoiding its own parent implementation entirely.

**Comment by asmecher** [comment]
Pulls:

- https://github.com/pkp/omp/pull/397
- https://github.com/pkp/pkp-lib/pull/2347/files
- https://github.com/pkp/ojs/pull/1307

**Comment by asmecher** [comment]
All merged. This is likely to break a few things.

**Comment by ajnyga** [comment]
I guess the TemplateManager::display is not available after this?

**Comment by asmecher** [comment]
Sorry, @ajnyga, just getting back to this and it looks like you've already resolved it yourself!
