### ISSUE TITLE
[OJS] Update Serbian locale

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2337]
A decision has been made regarding the locale names, see #1858 and #1911.

Opening this issue to track the renaming and updating of two Serbian locales.

**Comment by mtub** [comment]
At the end of this process, the sr_SR folders (which are using the wrong country code and do not include the script variant) will have been removed/replaced.

**Comment by mtub** [comment]
@asmecher , these pull requests are all of the translation work done so far. do you mind to have a look?

**Comment by asmecher** [comment]
Many thanks! I've merged the fix for #1911 so these are finally getting a look. There's some work still required on the OJS PR before the XML will validate.

**Comment by asmecher** [comment]
@mtub, all of these appear to be merged -- is this issue ready to be closed?

**Comment by mtub** [comment]
Yes, closing…
