### ISSUE TITLE
[OJS] OJS3 Usage Statistics plugin displayStatistics setting not context specific

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2338]
Hi, tagging @bozana here because I think that you have dealt the issues with this plugin before :)

It seems that you can not disable or enable the "Display submission statistics chart for reader" setting just for one context at the moment. If I turn it on for one journal, it turns on for all. 

This probably means that when an editor of a journal does that, she will disable/enable the setting for the whole site as well?

Is there a reason why displayStatistics setting is not context specific?

**Comment by bozana** [comment]
Hi @ajnyga, the whole plugin is site-wide meaning that everything is for the whole site. I will take a look if it would be possible to somehow consider the display context specific... 
Thanks!

**Comment by ajnyga** [comment]
Ok, thank you again.

The thing is that I do not whether all journals want to show those ALM's on their site. Of course this is something I can also change in their own theme plugin if necessary.

**Comment by ajnyga** [comment]
Hi @bozana a friendly bump to ask whether the work on site level plugins has solved / is solving this for 3.1?

I think you would only have to get $context  and consider these parts of the code:
https://github.com/pkp/pkp-lib/blob/master/plugins/generic/usageStats/UsageStatsSettingsForm.inc.php#L51
https://github.com/pkp/pkp-lib/blob/master/plugins/generic/usageStats/UsageStatsSettingsForm.inc.php#L105
https://github.com/pkp/pkp-lib/blob/master/plugins/generic/usageStats/PKPUsageStatsPlugin.inc.php#L90

This could be extended so that the type of the graph and other related settings would be context specific as well. 

What do you think, I could do a quick pr if that sounds right?

**Comment by bozana** [comment]
@ajnyga, ah sorry, I forgot this one.
I've just spoken with @NateWr, and what you suggest could be the solution for now, till we do not implement something else. 
There is only one thing we should consider: We should add an explanation, something like:
On the index page: "The following display options will be used as default i.e. for each journal/context that does not overwrite them."
On the journal/context page: "The following display options affect only the current journal/context."
Does this sound OK to you?
I believe you are going to have vacation, so I can also do it this way... Else, you are of course very welcome to make a PR :-)

**Comment by ajnyga** [comment]
Yes, leaving tomorrow. Of course you can handle this, it will be a lot faster. But if you have your hands full, I can work with this after my vacation (and http://www.jukola.com/2017/)

**Comment by bozana** [comment]
Ha! I am curious... :-)

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2596
ojs master: https://github.com/pkp/ojs/pull/1430

**Comment by bozana** [comment]
@NateWr, could you review this?

@ajnyga, if you would have a possibility to test the changes, it would be great!

**Comment by ajnyga** [comment]
Thanks once again @bozana! I will try these by tomorrow and let you know.

**Comment by NateWr** [comment]
Looks good! Just some minor text changes.

**Comment by ajnyga** [comment]
This seemed to work fine with a test server, I will test it on our production server later.

**Comment by bozana** [comment]
Thanks @ajnyga ! Will then close it for now...
