### ISSUE TITLE
pub id plugins: display reassign and asignDOIs notifications in the right time

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2346]
The notification messages are first displayed later, when the modal is closed, which does not make sense, s. https://github.com/pkp/ojs/pull/1304#discussion_r105128469

**Comment by NateWr** [comment]
@bozana do you know if this is still a bug?

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
