### ISSUE TITLE
[OJS 2.4.x] Public Profile link from comments is broken

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2348]
In templates/comment/comments.tpl, each call to `{translate key="comments.authenticated" ... }` is missing the `publicProfileUrl` parameter.  As a result, the links to authenticated user names from .../comments/view/... all hyperlink as `<a href="{$publicProfileUrl}">`.  See: http://forum.pkp.sfu.ca/t/how-to-get-the-public-user-profil-url/29106/10?u=ctgraham

Exists at:
https://github.com/pkp/ojs/blob/f0f718d51ce912ac99acc4bd94496147d2ae2cdf/templates/comment/comments.tpl#L33
https://github.com/pkp/ojs/blob/f0f718d51ce912ac99acc4bd94496147d2ae2cdf/templates/comment/comments.tpl#L90
https://github.com/pkp/ojs/blob/f0f718d51ce912ac99acc4bd94496147d2ae2cdf/templates/comment/comments.tpl#L132

**Comment by asmecher** [comment]
Thanks, @ctgraham, I've merged your PR and cherry-picked across to `ojs-stable-2_4_8`. As you've noted, this is a pretty rarely executed backwater.
