### ISSUE TITLE
[OJS 2.4.x] Plugin usageStats incompatible with PECL geoip

### ISSUE THREAD

**Issue by atarix83** [pkp/pkp-lib#2349]
Hi,
With PECL geoip extension installed I have this error while is running scheduledTasksAutoStage.xml :

`Cannot redeclare geoip_country_code_by_name()`

Function is defined both in plugins/generic/usageStats/lib/geoIp/geoip.inc and PECL extension.

This error interrupts the execution of the scheduledTask.

**Comment by asmecher** [comment]
@atarix83, you can prevent the geoIp library that ships with OJS 2.x from loading by editing `plugins/generic/usageStats/GeoLocationTool.inc.php`; look for `geoIp`. There should be two calls to `require` that you may be able to remove. You'd need to ensure that the PECL version of geoip is compatible with the one OJS expects.
