### ISSUE TITLE
[pkp-lib] Remove duplicate key in several locales

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2355]
`submission.event.fileUploaded` is a duplicate key with two different strings in /lib/pkp/submission.xml

Please decide which one to use and remove the other key from en_US and other locales using it (ca_ES, fi_FI, de_DE, es_ES, ar_IQ, ru_RU)

**Comment by mtub** [comment]
* `submission.event.participantAdded`

**Comment by NateWr** [comment]
This is no longer an issue in the `main` branch.
