### ISSUE TITLE
Improve "Required" field labels on review forms

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2359]
See http://forum.pkp.sfu.ca/t/required-field-feedback-at-the-end-of-the-form/29142 for details. The review form field labels don't include the usual `*` flag, and this can't be easily added because the element labels are presented in `formSection` titles based on user-created titles that are composed using TinyMCE. Thus the labels are wrapped in `<p>` elements, and a `*` will be dumped onto the next line.

**Comment by bozana** [comment]
Is this a duplicate of https://github.com/pkp/pkp-lib/issues/1783 ?

**Comment by asmecher** [comment]
Not a duplicate, but related.

**Comment by ViRuSTriNiTy** [comment]
I can provide a PR for this issue. It can be partly solved by simple adjustments in `reviewFormResponse.tpl` and `forms.less`. The basic idea is to append an asterisk to the last `<p>`  in the field label (see my last suggestion here: https://forum.pkp.sfu.ca/t/missing-asterisk-for-required-fields-in-review-forms/49775).

 I've done so in my OJS setup and it works pretty nicely.

What do you say?

**Comment by asmecher** [comment]
@ViRuSTriNiTy, a PR would be welcome, thanks!

**Comment by asmecher** [comment]
Looks good to me -- merged! Thanks for contributing, @ViRuSTriNiTy.

**Comment by ViRuSTriNiTy** [comment]
@asmecher merges quicker as me writing a short reply.
