### ISSUE TITLE
Drop file check on minification use

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2364]
See https://github.com/pkp/pkp-lib/issues/469#issuecomment-287107164 for details.

**Comment by NateWr** [comment]
There are two more places this `file_exists` check is done improperly:

https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L571

https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L588

For these, I think we do need to check if the file exists, but not sure how to get a proper file path in this instance.

**Comment by asmecher** [comment]
Mind reviewing https://github.com/pkp/pkp-lib/commit/769974faac04c4bed7e449f5e8371ce344cd51ae, @NateWr? I think this resolves the use of baseUrl, and since it's not used in the templates anywhere, removes it to prevent improper use there.

If it looks good to you, I'll cherry-pick it over to `ojs-stable-3_0_2` and `omp-stable-3_1_0`.

**Comment by NateWr** [comment]
Looks good! :+1:

**Comment by asmecher** [comment]
Thanks, @NateWr!
