### ISSUE TITLE
[OJS] Native XML Plugin lacks paging in Export issues listing

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2365]
Referring to this discussion and the first problem mentioned there: http://forum.pkp.sfu.ca/t/ojs-3-0-most-of-the-issues-missing-from-native-xml-export-plugin/29368

OJS3.0.2.

The native xml plugin does not have paging available in the export issues listing so basically with larger archives most of the issues are hidden.

You can of course change the amount of visible items from the website settings, but with larger archives this is not a good option.

**Comment by bozana** [comment]
PRs:
ojs ojs-stable-3_0_2: https://github.com/pkp/ojs/pull/1318

**Comment by bozana** [comment]
@ajnyga, could you please see/test if now everything is fine?

**Comment by ajnyga** [comment]
@bozana it does, thanks!

AJ

**Comment by bozana** [comment]
OK, thanks a lot, I will then wait for tests to finish and then merge and cherry-pick...

**Comment by bozana** [comment]
Everything merged, thus closing...
