### ISSUE TITLE
[pkp-lib] parse errors on grids for systeminfo

### ISSUE THREAD

**Issue by verdonv** [pkp/pkp-lib#2371]
My server was reporting php parse errors on two pages for system info grids. The fix was easy enough.

On files:
/lib/pkp/controllers/grid/admin/systemInfo/ServerInfoGridHandler.inc.php
/lib/pkp/controllers/grid/admin/systemInfo/VersionInfoGridHandler.inc.php

On line 63, the comma needed to be removed from after the last item in the array,  LOCALE_COMPONENT_APP_MANAGER

**Before**
```
		AppLocale::requireComponents(
			LOCALE_COMPONENT_PKP_USER,
			LOCALE_COMPONENT_PKP_ADMIN,
			LOCALE_COMPONENT_APP_ADMIN,
			LOCALE_COMPONENT_APP_MANAGER,
		);

```
**After**
```
		AppLocale::requireComponents(
			LOCALE_COMPONENT_PKP_USER,
			LOCALE_COMPONENT_PKP_ADMIN,
			LOCALE_COMPONENT_APP_ADMIN,
			LOCALE_COMPONENT_APP_MANAGER
		);

```

**Comment by asmecher** [comment]
Thanks, @verdonv -- good spotting.
