### ISSUE TITLE
Incorrect return link in HTML Galley view

### ISSUE THREAD

**Issue by verdonv** [pkp/pkp-lib#2372]
When using the HTML Galley view, the link to the top-left to return the viewer to the main article view, in fact just reloads the html galley view, leaving the reader in a loop. The PDF Viewer Galley view return link is fine.

**Comment by asmecher** [comment]
@verdonv, which application are you using, and what version?

**Comment by verdonv** [comment]
@asmecher, sorry. OJS 3.0.2 pulled from github Monday.

**Comment by asmecher** [comment]
I've checked my local install and the back links seem to be working OK. I'd suggest clearing up the branches per http://forum.pkp.sfu.ca/t/ojs-3-how-to-add-blocks-to-sidebar/29548/9 and seeing if that resolves this issue.

**Comment by verdonv** [comment]
Hi @asmecher,

That didn't seem to fix it. I've also tried adding a new galley, in case something went wrong in the upgrade, and it's in the db. I think at this point, just to be 100% sure, I'm going to nuke everything and start fresh.

**Comment by verdonv** [comment]
OK @asmecher 

I nuked everything, started 100% fresh, and can verify that there is a little weirdness in the return link from the HTML Galley view. What it actually is, is that the little arrow returns correctly, but the text link does not. Now I suppose this could be on purpose, but it is different than the behaviour of the PDF Galley View.

If you'd like a link, let me know.

![screen shot 2017-03-23 at 12 50 12 pm](https://cloud.githubusercontent.com/assets/5149763/24259634/da76f3c8-0fc7-11e7-9b3c-ad9965bc63dc.png)

**Comment by asmecher** [comment]
Hi @verdonv,

That probably was intentional, but better to make the two presentations behave consistently, and on balance I think it makes sense to go back to the table of contents. Committed -- thanks for reporting!
