### ISSUE TITLE
«ERROR:  relation "submissions_tmp" already exists» w/ Postgres 9.6.0

### ISSUE THREAD

**Issue by Geremia** [pkp/pkp-lib#2373]
With OJS 3.0.0.0 and 3.0.2.0, I get the following error:
```
/var/log/postgresql-9.6:ERROR:  relation "submissions_tmp" already exists
/var/log/postgresql-9.6:        CREATE TABLE submissions_tmp AS (SELECT submission_id, context_id, comments_to_ed, date_submitted FROM submissions)
```
My database is Postgres 9.6.0.

**Comment by asmecher** [comment]
Hi @Geremia -- it sounds like you're trying to perform an upgrade on a database that's already failed an upgrade. Make sure you restore from backup before attempting another upgrade; otherwise your database will be left in a state between the two versions, which is very difficult to work with.

**Comment by Geremia** [comment]
@asmecher Yes, I'm not sure why Postgres is so difficult to upgrade. What exactly do you suggest I do? My other version 9.4 databases have upgraded to version 9.6 successfully.

**Comment by asmecher** [comment]
@Geremia, I'm not sure how the `pg_upgrade` tool plays into this, I'm referring to the OJS upgrade tool/process. The error message you quoted (`relation "submissions_tmp" already exists`) suggests that `submissions_tmp` exists in the database you're trying to upgrade; that can only be created by the upgrade tool and should be cleaned up afterwards, which suggests to me that you're running the upgrade tool on a database that already had an upgrade fail on it. Restore your database from the backup you made before running the upgrade tool. Check to make sure that the `submissions_tmp` table doesn't exist in it -- it shouldn't.

**Comment by Geremia** [comment]
@asmecher Oh, I see.

I still get this on the submissions page:
```
Loading
Loading
Loading 
```
The submissions never load, when they certainly did a month ago when I still had Postgres 9.4.

**Comment by Geremia** [comment]
Also, I get a 404 on `plugins/generic/lucene/js/LuceneAutocompleteHandler.js`, which really doesn't even exist on the server.

**Comment by asmecher** [comment]
@Geremia, would you mind moving this over to the support forum at http://forum.pkp.sfu.ca/? If it turns out to be a bug, we can move back over here. I suspect you'll find more details in the PHP error log; include that in your post. If you're using your 3.0.0 backup with the 3.0.2 code, you can expect some things not to work; you need to run the upgrade tool to migrate your database from 3.0.0 to 3.0.2.

**Comment by Geremia** [comment]
Okay, with a clean database from backup, I get this when upgrading to  3.0.2:
```
A database error has occurred: ERROR: type "serial" does not exist
```

**Comment by Geremia** [comment]
I think what happened is that my CSP policy broke something.
