### ISSUE TITLE
Rename Current "Indexing" Tab in Distribution Settings

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2378]
The current "Indexing" tab in the Distribution settings is misleading and should be renamed "Search Engine Optimization" or "SEO" or "Search Engine Details" or something similar.

Indexing is widely expected to refer to being indexed in an indexing service like the DOAJ or Web of Science.

Could a new "Indexing" tab be automatically created in the Distribution Settings when the DOAJ plugin (or any other index-related plugin) is activated (similar to Static Pages), and contain the relevant setting information for that activated plugin?

**Comment by NateWr** [comment]
This has been improved in recent versions.
