### ISSUE TITLE
[OJS] Upgrade Script and old plugin versions

### ISSUE THREAD

**Issue by verdonv** [pkp/pkp-lib#2386]
After trolling through the forums, and finding a related post from an early OJS 3 release, I discovered that the reason I could not install the QuickSubmit plugin, although I was getting misleading messages about it already being installed, and an update being available, was that there was a row in the 'versions' table relating to the QuickSubmit plugin from OJS 2.x. Deleting that row allowed the QuickSubmit plugin to be installed from the 3.x plugin gallery.

I would suggest that during the database upgrade step, when upgrading from 2.x to 3.x, that any entries in 'versions' referring to older non-supported plugins either be deleted, or moved to another table, or something. Perhaps the issue should be dealt with by the QuickSubmit plugin installer, if it finds older versions entries.

**Comment by verdonv** [comment]
I realize now too that it may be possible that the QuickSubmit plugin did attempt to deal with this, and that I had a permission error in the plugins/ folder. Somewhere along the way, I corrected permission there so the webserver could write to the plugins folder. If there was a permissions error going on though, I never got any kind of dialogue stating such... just a dialogue saying the plugin was already installed, could be updated, then offering me the install option again.

**Comment by davidalar** [comment]
Hola @verdonv !   yo tuve el mismo problema... pero conseguí instalarlo de la siguiente forma:

1.- Descargue la ultima versión de plugins (para OJS 3.0.2) y la puse en el directorio: ojs-3.0.2/plugins/importexport
2.- Luego modifiqué el archivo config.inc.php  "installed = Off" para forzar una actualización.
seguí estos pasos:
    - Edit config.inc.php and change "installed = On" to "installed = Off"
    - Open a web browser to your OJS site; you should be redirected to the
      installation and upgrade page
    - Select the "Upgrade" link and follow the on-screen instructions
    - Re-edit config.inc.php and change "installed = Off" back to
       "installed = On"
3.- Finalmente revisé el listado de plugins en ojs 3.0.2 y QuickSubmit  estaba correctamente instalado!

Sorry for typing in spanish ... my english is very poor...

**Comment by asmecher** [comment]
I think this is related to issue #2387.

**Comment by bozana** [comment]
In OJS 3.x there is no QuickSubmit plugin -- it is in a separate repository i.e. in the plugin gallery. When upgrading from OJS 2.4.x to OJS 3.x the entry in the `versions` table will stay, the plugin will not be listed in the list of installed plugins, and the status "Can be upgraded" will be displayed for the plugin in the plugin gallery. The plugin can then be updated to the new version from within the plugin gallery or uploading the .tar.gz. Thus everything seems to be OK here. Can we then now close this issue?

**Comment by verdonv** [comment]
@bozana, I'm not really following. To be sure I understand, are you saying that it is/would be behaving correctly, except for the "plugin category in the XML definition" issue you mention in #2387 ?

**Comment by bozana** [comment]
@verdonv, yes, I think so. For the plugin deletion, one have to watch on the permissions on the plugins folder. Else one will get the deletion error. When a plugin is deleted, it will stay in the DB table version, with current = 0. This seems to be the intended and OK so, s. https://github.com/pkp/pkp-lib/blob/master/classes/controllers/grid/plugins/PluginGridHandler.inc.php#L368.
The same thing happens with the upgrade from 2.4.x to 3.x i.e. the plugin is disabled. Because of the bug in the plugins.xml the plugin gallery couldn't correctly realize the status of the plugin, that an update is possible/necessary.
