### ISSUE TITLE
[quickSubmit 1.0.1] Version info not displayed in Plugin Gallery

### ISSUE THREAD

**Issue by verdonv** [pkp/pkp-lib#2387]
After installing the quickSubmit plugin into OJS 3.0.2 stable, nothing displays in the 'Status' column of the Plugin Gallery, and when clicking on the name of the plugin in the 'Name' column, I am still offered to install it (in the pop-up dialogue), even though it was just installed.

![screen shot 2017-03-24 at 2 16 20 pm](https://cloud.githubusercontent.com/assets/5149763/24307984/94f0ed4c-109c-11e7-857c-94206978d4bb.png)

**Comment by asmecher** [comment]
@verdonv, did you install this plugin through the Plugin Gallery, or through another mechanism (e.g. copying the files manually)?

**Comment by verdonv** [comment]
Hi,

Installed directly through plugin gallery.

**Comment by Ph-We** [comment]
I think, this might be related:
http://forum.pkp.sfu.ca/t/ojs-3-0-2-solved-readers-get-redirected-to-the-advanced-search/28775/28?u=ph_we

**Comment by asmecher** [comment]
@bozana, mind taking a look at this?

**Comment by bozana** [comment]
This is due to the wrong plugin category in the XML definition for the plugin gallery: http://pkp.sfu.ca/ojs/xml/plugins.xml -- quick submit is not a generic but importexport plugin.
I will change that in the XML file...

**Comment by bozana** [comment]
done, so I will close this issue...

**Comment by asmecher** [comment]
Ah -- thanks, and good spotting, @bozana!
