### ISSUE TITLE
Concatenate "about" content during OJS2 to OJS3 migration

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2392]
See e.g. http://forum.pkp.sfu.ca/t/suggest-an-update-for-journal-settings-when-upgrading-from-ojs2-to-ojs3/29626

Just to quickly see what and how changed: https://github.com/pkp/pkp-lib/issues/1397

**Comment by asmecher** [comment]
@jmacgreg, IIRC (and I may be inventing this) you had some SQL you were putting together for this for hosting?

**Comment by jmacgreg** [comment]
Nope, not I! I was mostly just informing journals that they'd have to do some manual work here.

**Comment by asmecher** [comment]
Hmm, I remember this coming up recently but the rest is foggy -- @felczak? @bozana?

**Comment by bozana** [comment]
Yes, I mentioned it :-) I will take a look...

**Comment by bozana** [comment]
The concatenation could be done like this:
a) the following pages from OJS 2.4.x could be concatenated into the current "About the Journal" filed:

- Focus and Scope
- Peer Review Policy
- Publication Frequency
- Open Access Policy
- Journal Sponsorship
- Journal History

b) Shall Privacy Statement content be added at the end of the Author Guidelines? 
c) editorialTeam and displayMembership could be tried to be concatenated into the Masthead field.

@asmecher, what do you think?

**Comment by asmecher** [comment]
Yes, thanks -- this looks good. (@jalperin, I think you came across a use case for this too?)

**Comment by jalperin** [comment]
Yes. But also making an HTML masthead for those that has set up the awful masthead thing in ojs2

**Comment by jalperin** [comment]
Sorry @bozana, I see you mentioned the editorial team also. All that looks good. Privacy statement could go with author guidelines.

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1357

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR?

**Comment by bozana** [comment]
Hmmm... the privacy statement text i.e. a link to it is used on several other places in the system, e.g. submission step 1, usage statistics, in the default info text for readers, notification mail list form/page (might be old/not used)... and also in OMP... so maybe it would make sense to reactivate it again i.e. to provide an input field for that again? @asmecher, what do you think?

**Comment by asmecher** [comment]
Hmm, yes, I do think that makes sense. There are probably a few orphaned settings still kicking around like this.

**Comment by bozana** [comment]
@asmecher, could you then take a look at the PRs above? Thanks!

**Comment by asmecher** [comment]
Looks good, @bozana. Which is to say, it's necessarily messy, but will be useful -- and one day we'll axe the OJS 2.x upgrade process and lose a lot of lines of code. Thanks!

**Comment by bozana** [comment]
everything merged, thus closing...

**Comment by asmecher** [comment]
FYI, I'm getting some warnings on a (potentially dirty) database:
````
[code: Installer Installer::concatenateIntoAbout]
PHP Warning:  Cannot use a scalar value as an array in /home/asmecher/git/ojs/lib/pkp/classes/core/DataObject.inc.php on line 133
PHP Stack trace:
PHP   1. {main}() /home/asmecher/git/ojs/tools/upgrade.php:0
PHP   2. UpgradeTool->execute() /home/asmecher/git/ojs/tools/upgrade.php:34
PHP   3. UpgradeTool->upgrade() /home/asmecher/git/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php:64
PHP   4. Installer->execute() /home/asmecher/git/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php:88
PHP   5. Installer->executeInstaller() /home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:186
PHP   6. Installer->executeAction() /home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:265
PHP   7. call_user_func:{/home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:415}() /home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:415
PHP   8. Upgrade->concatenateIntoAbout() /home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:415
PHP   9. DAOResultFactory->next() /home/asmecher/git/ojs/classes/install/Upgrade.inc.php:1945
PHP  10. JournalDAO->_fromRow() /home/asmecher/git/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php:104
PHP  11. ContextDAO->_fromRow() /home/asmecher/git/ojs/classes/journal/JournalDAO.inc.php:46
PHP  12. DAO->getDataObjectSettings() /home/asmecher/git/ojs/lib/pkp/classes/context/ContextDAO.inc.php:76
PHP  13. DataObject->setData() /home/asmecher/git/ojs/lib/pkp/classes/db/DAO.inc.php:587
PHP Warning:  Cannot use a scalar value as an array in /home/asmecher/git/ojs/lib/pkp/classes/db/SettingsDAO.inc.php on line 41
PHP Stack trace:
PHP   1. {main}() /home/asmecher/git/ojs/tools/upgrade.php:0
PHP   2. UpgradeTool->execute() /home/asmecher/git/ojs/tools/upgrade.php:34
PHP   3. UpgradeTool->upgrade() /home/asmecher/git/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php:64
PHP   4. Installer->execute() /home/asmecher/git/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php:88
PHP   5. Installer->executeInstaller() /home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:186
PHP   6. Installer->executeAction() /home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:265
PHP   7. call_user_func:{/home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:415}() /home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:415
PHP   8. Upgrade->concatenateIntoAbout() /home/asmecher/git/ojs/lib/pkp/classes/install/Installer.inc.php:415
PHP   9. Context->getSupportedFormLocales() /home/asmecher/git/ojs/classes/install/Upgrade.inc.php:1946
PHP  10. Context->getSetting() /home/asmecher/git/ojs/lib/pkp/classes/context/Context.inc.php:191
PHP  11. SettingsDAO->getSetting() /home/asmecher/git/ojs/lib/pkp/classes/context/Context.inc.php:320
PHP  12. GenericCache->get() /home/asmecher/git/ojs/lib/pkp/classes/db/SettingsDAO.inc.php:72
PHP  13. call_user_func_array:{/home/asmecher/git/ojs/lib/pkp/classes/cache/GenericCache.inc.php:63}() /home/asmecher/git/ojs/lib/pkp/classes/cache/GenericCache.inc.php:63
PHP  14. SettingsDAO->_cacheMiss() /home/asmecher/git/ojs/lib/pkp/classes/cache/GenericCache.inc.php:63
PHP  15. SettingsDAO->loadSettings() /home/asmecher/git/ojs/lib/pkp/classes/db/SettingsDAO.inc.php:96
````
(repeats)

**Comment by bozana** [comment]
@asmecher, it seems like a journal setting is not localized although it should be and like the supportedLocales is not an array, could that be?
That script is first executed, that's why the errors are here, but they would probably appear somewhere else as well.
Thus I am not sure what could I do in such a case, when the data in the DB is not correct?

**Comment by asmecher** [comment]
@bozana, I think I identified this as an old data error with the `metaCitations` setting. It can be cleaned out with...

    delete from journal_settings where setting_name = 'metaCitations' and (locale is not null and locale <> '');

Don't worry, it's not your bug :) I'll let you know if anything else needs doing.

**Comment by bozana** [comment]
Hmmm... I think the functions are at the wrong place in the upgrade.xml...
