### ISSUE TITLE
[OJS] Editorial decisions buttons should be disabled on stages that are already finished

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2393]
In OJS3.0.2. the editorial decision buttons are active also in the stages that the submissions has already passed. For example, if a submission has reached the review stage, you can still do editorial decisions from the submissions stage. This is problematic especially with the send to review button, which basically creates a new review round every time. With submissions with several editors there could be lack of communication resulting to such situations and removing extra review rounds is not possible through the UI.

So, I would suggest that after finishing a stage, the editorial decision buttons should all be disabled in the previous stages or even removed.

**Comment by asmecher** [comment]
@ajnyga, has this happened in practice? I'm wary of removing/disabling the buttons entirely as we do want to permit out-of-order editorial work; it might suit a journal/press's workflow better, and if a decision is recorded in error, it does permit them to work around it.

**Comment by ajnyga** [comment]
Hi,

I have had three cases where there has been several (2-4) review rounds open in submission. Based on the discussion I have had with the editors, it seems likely that at least in some cases these have been started with the scenario above.

But this is a low priority issue. Maybe you could discuss this the next time you do testing with the UI.

I guess a "cancel this review round" button would also solve this.

**Comment by asmecher** [comment]
Alternately, what about not automatically creating a new round if one is already active? OTOH we'd have to consider how to treat the selected files -- e.g. would they be added to the existing round? -- but it might be more intuitive that way.

**Comment by ajnyga** [comment]
I guess that is an option as well. But why not then just disable the "Send to review" button if a review round is already active? This way there would be no need to worry about the selected files. I mean, what else does the button do besides enabling the review stage and creating the first review round?

I totally agree that it is a good thing to provide flexibility in the workflow, but active buttons in work stages that are already finished is maybe a bit confusing way of doing this. The best way to provide flexibility would actually be the option of sending a submission back to a preceding stage (with an entry to the history) and canceling already started review rounds. But that would of course mean a lot of changes and would probably create some other difficulties which I can not think of right now.

**Comment by ajnyga** [comment]
@bozana I think that the extra review rounds are partly connected to the upgrade from OJS2 to OJS3. I do not know if I can track it down anymore and maybe this is fixed already somewhere, but it seems that there have been situations where the upgrade script has created a round 1 for a submission that was still on submission stage when the upgrade took place.

**Comment by bozana** [comment]
I will take a look at a upgrade for the 1000000... times again ;-) to see if i.e. when those review rounds are created... That is very much possible...

**Comment by ajnyga** [comment]
@bozana I do not think that extra review rounds are created _during_ the upgrade. 

But it seems that some of the submission have been in the submissions stage but at the same time, during the upgrade, they get a review round as well. So now, after the upgrade editors go to the submission stage and click the active send to review button and voila, they create round 2.

**Comment by bozana** [comment]
@ajnyga, yes it comes from upgrade -- when submission has an editor assigned and is in the review queue in 2.4.x, but no review round is started... -- I've just tested it... I have to see where those review rounds are created for such a case...

**Comment by ajnyga** [comment]
Sounds like just the scenario we have had with the few submissions. Most of these are of course now in a later stage already. But the original issue here is still in my opinion something worth discussing (meaning the active buttons)

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1343

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR and decide about the original request about the decision buttons (at least for now)? :-)

**Comment by asmecher** [comment]
@bozana, that PR looks good to me -- but would you mind removing the trailing `;` at the end of the query (and the one above it)? Just for consistency; ADODB doesn't seem to mind.

**Comment by bozana** [comment]
The PR is merged, thus this issue can be either closed (if the buttons should remain) or deferred (if the buttons should be changed)...

**Comment by asmecher** [comment]
This is going out with OJS 3.1, so closing!
