### ISSUE TITLE
QuickSubmit - PHP Fatal Error when submitting form

### ISSUE THREAD

**Issue by VMFnet** [pkp/pkp-lib#2403]
Using OJS 3.0.2 and the latest quickSubmit 1.0.2 from gitHub.

When filling in the form and submitting, the user gets a blank page.
The following error is in the log : 

PHP Fatal error:  Call to undefined method PublishedArticleDAO::getByArticleId() in /www/journal/plugins/importexport/quickSubmit/QuickSubmitForm.inc.php on line 67.

Said line of QuickSubmitForm.inc.php looks like this : 

$publishedSubmissionDao = DAORegistry::getDAO('PublishedArticleDAO');
$this->publishedSubmission = $publishedSubmissionDao->getByArticleId($this->submissionId, $this->context->getId(), false);

**Comment by defstat** [comment]
@VMFnet I think you should use the https://github.com/pkp/quickSubmit/releases/tag/ojs-3_0_2-0 for OJS 3.0.2, not the latest master branch, as it has changes regarding the future releases of OJS.

Maybe, you can try install it from the plugin gallery.

@asmecher ?

**Comment by asmecher** [comment]
Agreed, I think you're mixing code from the `master` branch with code from a stable branch. Make sure you're using the same branch name for all modules.

**Comment by VMFnet** [comment]
I was indeed mixing two different codebases. Thank you @defstat and @asmecher for pointing that out !
I reinstalled the plugin manually with the correct code release (couldn't use the install from the gallery as the page displayed 'already installed' when choosing Quicksubmit), 
now everything seems to be working fine.

**Comment by asmecher** [comment]
Glad to hear it's working, @VMFnet!
