### ISSUE TITLE
consider file import using href element

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2405]

**Comment by bozana** [comment]
This is probably solved here: https://github.com/pkp/pkp-lib/issues/2500

**Comment by bozana** [comment]
@ctgraham, you have solved this, right?

**Comment by ctgraham** [comment]
Yes, though I am working on a weird result where a call to `filesize($filename)` returns 0 for a `$filename` of nonzero length in some contexts, so you'll probably see another issue/pr soon.
