### ISSUE TITLE
[OJS] Publish Notify email template not used in OJS 3.0.2

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2406]
Hi,

One of our editors noticed that OJS 3.0.2. has a Publish Notify email template, but the system does not seem to use it. Instead the basic Notification template is used.
https://github.com/pkp/ojs/blob/master/locale/en_US/emailTemplates.xml#L110

They would like to use it, because the current notification for new issues is quite unfriendly and uninformative compared to the Publish Notify template:

> **New notification from {JOURNALNAME}**
> You have a new notification from {JOURNALNAME}:
> An issue has been published.
> 
> Link: {URL}
> 
> {PRINCIPAL CONTACT NAME}

Because of the simple language, some of the recipients of an earlier issue notification have thought that the notification is a security risk.

**Comment by asmecher** [comment]
This is a hold-over from OJS 2.x (along with e.g. anything payment-related) that hasn't had a feature implemented in OJS 3.x to back it. We do intend to address the lack of mass communication tools in OJS 3.x (the old OJS 2.x "notify users" tool was clunky). I don't see anything filed for this yet, so this entry should serve.

**Comment by asmecher** [comment]
Dupe of https://github.com/pkp/pkp-lib/issues/1897.
