### ISSUE TITLE
Remove mutex use

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2407]
Now that we're requiring more modern database servers, use SQL `UNION` rather than the (clever but unnecessary) [mutex hack](https://www.xaprb.com/blog/2005/09/22/mutex-tables-in-sql/).

**Comment by asmecher** [comment]
PRs:

- https://github.com/pkp/pkp-lib/pull/2408
- https://github.com/pkp/ojs/pull/1344
- https://github.com/pkp/omp/pull/402

**Comment by asmecher** [comment]
@bozana, assuming (ha!) the tests pass, could you take a review of this?

**Comment by bozana** [comment]
@asmecher, just a few comments and questions... :-)

**Comment by asmecher** [comment]
Merged, and good riddance to some convoluted queries -- thanks, @bozana!
