### ISSUE TITLE
[OJS] Auto review remind oneclick link is not working

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2412]
In OJS 3.0.2. if oneclick access is selected, the automatic review remind email contains a broken link.

PR: https://github.com/pkp/pkp-lib/pull/2413

Also @asmecher, I am seeing to forms of link expiry logic in the code, the last one is correct probably:
`$context->getSetting('numWeeksPerReview') + 4 * 7` AND
`($context->getSetting('numWeeksPerReview') + 4) * 7`

**Comment by asmecher** [comment]
Correct on both counts, @ajnyga -- many thanks! I've added the parentheses where they were missing. Cherry-picked around to `ojs-stable-3_0_2` and `omp-stable-3_1_0`.
