### ISSUE TITLE
[OJS] OJS 3.0.2. Removing a section makes all submissions connected to that section disappear

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2415]
It seems that when removing a journal section in OJS3.0.2. there is no fallback. In the submission table, the submission section is set to NULL for all the submissions that were in the removed section and the submission is not visible anymore through the UI. Even when manually entering the workflow address you get `Invalid submission`. 

Basically OJS should
1. Ask for replacing section for the one that is being removed OR
2. Only allow merging sections, like with user accounts OR
3. Another angle: change some sql so that the submission is visible even though a section is set to NULL

https://github.com/pkp/ojs/blob/master/classes/article/ArticleDAO.inc.php#L309

**Comment by ajnyga** [comment]
ping @NateWr or @asmecher 
I know you have a lot going on with 3.1, but I really think that this is an issue that should be addressed as well.

**Comment by NateWr** [comment]
My take would be to force them to select which section the submissions should be reassigned to. And it's impossible to delete a section when it's the only remaining section.

So, thinking off the top of my head, the UI flow would be:

- Click delete
- Modal form appears with explanatory note saying that all submissions in X category must be reassigned. Form includes a field "Reassign all submissions to the following section", with a list of `radio` inputs allowing them to select another section.
- Click delete on the form
- Confirmation modal pops up: Are you sure...? All submission will be reassigned to ...
- Click OK.

**Comment by ajnyga** [comment]
@NateWr I agree. Are you doing this? I could try to do a pr based on that.

**Comment by asmecher** [comment]
Deleting a section should be an extremely rare interaction, so I don't mind if we skip the hand-holding and simply tell an editor that they can't delete a section until all articles are moved to other sections. Just FWIW.

**Comment by NateWr** [comment]
@ajnyga If you can put together a PR that'd be great. We're coming down to the wire on 3.1. :)

**Comment by ajnyga** [comment]
Hi @NateWr and @asmecher 
I did a quick "minimum" fix according to Alec's comment. We can change this later, but will probably have to deal with OMP at the same time.

While doing this, I actually noticed that there is an existing translation available for this: https://github.com/pkp/ojs/blob/ojs-stable-3_0_2/locale/en_US/manager.xml#L91

pr: https://github.com/pkp/ojs/pull/1524

**Comment by NateWr** [comment]
I actually don't think we need to worry about OMP, because series (what we call sections in OMP) aren't required, so a submission without a series shouldn't disappear from the UI.

I agree this is sufficient to prevent people from screwing up their data and will suffice for UX until we have a real need for something better -- which may be never.

I left a few comments on the PR. Let me know when it's ready for another look. :+1:

**Comment by ajnyga** [comment]
Thanks! I will check the changes during the weekend.

**Comment by NateWr** [comment]
:ship: Thanks for the quick turnaround! I'll close this, but we can file a new bug for a prettier UI if and when it's really a priority for us.

**Comment by ajnyga** [comment]
Sure. I have some code ready for moving the articles to another section, so maybe with 3.2.

**Comment by asmecher** [comment]
Thanks, @ajnyga (and @NateWr)!

**Comment by ijolte** [comment]
I was delete my sections, and there is no mention to move to another section. because it, all of my articles gone. I'm newbie on OJS 3 and can't handle it. please, make easy step to fix its. thanks a lot

**Comment by asmecher** [comment]
Hi @ijolte -- I see you've also posted this over at https://forum.pkp.sfu.ca/t/by-mistake-i-deleted-the-sections-and-now-all-the-article-have-been-deleted/30333/8. Please just post in one place in order to help us keep our resources organized.
