### ISSUE TITLE
[OJS] OJS3.0.2 Review form breaks for users that are visiting OJS for the first time

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2417]
Hi @asmecher and @bozana 

This is an issue which seems to be very complicated but at the same time important to solve as soon as possible while it affects one the key features in OJS and a important user group.

In some cases the review form gets broken when moving between the steps. You get stuck in the same step and translation keys are ##not translated##. You can proceed by clicking the button in the form again and in the next step you see the "Error submitting form" modal. The problem is mentioned here http://forum.pkp.sfu.ca/t/ojs3-moving-between-steps-in-submission-and-review-forms-sometimes-cause-errors/26283 and here http://forum.pkp.sfu.ca/t/error-when-accepting-a-reviewer-invitation/29819

I have been able to reproduce this several times (not always) with these two scenarios:

Scenario 1:
- Add a reviewer and log out
- Clear your whole browser cache and log in again as the reviewer
- Find the correct submission and click the review link
- Click the accept review button => **error occurs**

Scenario 2 (this is more problematic):
- do as above but go as far as step 3 in the review form, as a reviewer would normally do
- log out, clear browser cache
- log in again, find submission and click review link, you should go to step 3
- fill in the review form and submit the form, press ok for the modal => **error occurs** AND you have just lost everything you wrote to the review form. _This has now happened a few times for our reviewers and it is of course very annoying as they are doing voluntary work._
- Note that if you would had failed to fill in for example the recommendation before clicking submit, the second click on the submit button does not create the error anymore.

So I think that _something_ is not loading correctly during the first time the review form is loaded, but this is solved when something is already in the browser cache. 

I see nothing in the javascript console and nothing in the php error log.

Also: **this could be an issue with the submission form as well?**

**Comment by ajnyga** [comment]
I think it is connected somehow to the task list in the dashboard sidebar:

- Select oneclick review and add a reviewer
- log out, clear browser cache, then click the link with the login key
- Outcome: no Task list or the Submissions link visible in the lefthand sidebar at all.
- If you click Accept review => the above error occurs
- If you leave before clicking and visit the link again without emptying the cache, the "The form was not submitted correctly" error modals appear (a couple of them) and also the task list and submissions link appear. If you now click Accept review, the from works.

There is a long block of code missing there when you visit the link for the first time right below 
`<div class="pkp_navigation" id="headerNavigationContainer">`

The missing code starts with this, so there is no tabhandler attached to the page, which would probably explain some of the errors:
```
<script type="text/javascript">
// Attach the JS file tab handler.
$(function() {
$('#navigationPrimary').pkpHandler(
'$.pkp.controllers.MenuHandler');
});
</script>
```

**Comment by ajnyga** [comment]
Yes, $isUserLoggedIn is not set at all. 

I tried to debug this by adding this
```
				if ($user->getId() == 18261){
					error_log(print_r(Validation::isLoggedIn(), true));
				}
```
To here: https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L334

To outcome was that when I visited the review form through the oneclick link, there was no output. The `$user` variable there is not set at all, the code never reaches that point. So there is something very wrong there.

Also, the problem occurring here when coming through the oneclick link is somehow different from the original scenario I wrote above, because when you log in the usual way, the task list is loaded. Still, the same error may occur as described in the first post.

This definitely needs @asmecher to figure out what is happening here. I have no idea how to proceed with this.

**Comment by asmecher** [comment]
@ajnyga, does this seem to be related to custom review forms, or have you seen it using the stock review form?

**Comment by asmecher** [comment]
Also, I'm not sure if this is related, but @ajnyga, if you're using your patch for issue #1875, you may also need to apply https://github.com/pkp/pkp-lib/commit/8a0f43920e22d1c0a3d8792e11acb545f8d09751 to resolve potentially non-unique IDs in the DOM.

**Comment by asmecher** [comment]
(Our continuous integration script tests reviews multiple times and that part of the script works reliably, so I'm trying to figure out what's different in your scenario.)

**Comment by ajnyga** [comment]
Hi,

This is not related to a certain type of review form. It is the movement between the steps that is the problem. I was not able to reproduce this in a fresh install of OJS3. Then again, this problem in different forms has been around since November when we started to test our upgrade. So maybe it is something that requires old data to happen.

Our installation does not have #1875 yet.

**Comment by ajnyga** [comment]
I especially do not understand why when accessing through a oneclick link this is not set at all
https://github.com/pkp/pkp-lib/blob/master/templates/common/header.tpl#L54

**Comment by asmecher** [comment]
@ajnyga, the one-click access doesn't grant a "complete" login -- it bypasses some of the normal session management tools for the sake of allowing the reviewer to work through the review process. We didn't want grant a first-class login through that link because that would be too "generous" for a one-time login token.

**Comment by ajnyga** [comment]
Ok, but the tasks list should still load?

**Comment by ajnyga** [comment]
The missing tasks panel is probably a red herring. Although a clean 302 install seems to show it and our current installation, basically a clean 302, does not.

The connecting issue is the empty browser cache. Both when logging in the usual way or clicking the oneclick link, if the user has not visited the form before, the moving between steps creates the error once.

**Comment by ajnyga** [comment]
I have identified the problem, or at least part of it.

If a reviewer has deleted all old cookies and logs in to the system, the `data` field in the `sessions` table looks like this:
`userId|s:5:"123456";username|s:10:"USERNAME";`

The CSRF value is missing. If the reviewer would no proceed to open to reviewing form and clicking a button to move between the steps, an error would occur. However, the reviewer now logs out and comes back right away, the same `data` field in the sessions table looks like this:

`csrf|a:2 {s:9:"timestamp";i:1491466317;s:5:"token";s:32:"e3ac6f97c72dd4af9efdb1168482016a";}username|s:10:"arvioija14";userId|s:5:"21111";`

And not to make this too simple. This does not happen, if I create a new reviewer. But if that same new reviewer gets a new assignment (meaning two assignments) and clears cookies before logging in, the CSRF part is again missing and errors occur.

Any idea why CSRD would be left out?

**Comment by ajnyga** [comment]
This is the risk scenario that seems to happen with oneclick reviews:
- First visit through the oneclick link, reviewer accepts the review. Session is created, includes the CSRF part.
- Second visit. The user has a new browser/computer or has deleted cache. Clicks the oneclick link, a **new** session is created, but it does **not** include the CSRF part. The first following push of a submission button will break the form. After this, the session has the CSRF part.

**Comment by ajnyga** [comment]
@asmecher I can confirm with a clean install of OJS3.0.2 that scenario 3 above is a problem.

I changed the CSRF token validity time 60 seconds (https://github.com/pkp/pkp-lib/blob/master/classes/session/Session.inc.php#L221) and opened a review form. Then waited for a bit and tried to submit the form.

The result was that the error occurred (translation strings visible etc.) and the form data was lost.

**It is very likely that it takes more than an hour to fill that form, so some solution is needed here!**

**Comment by ajnyga** [comment]
@asmecher, regarding scenario 1 above https://github.com/pkp/pkp-lib/issues/2417#issuecomment-292138470

Right after clicking a oneclick access link, the data field in the session table looks like this:
`userId|s:5:"123456";username|s:9:"USERNAME";`	
Then, after just a second or so, the CRSF part is added to the end.
`userId|s:5:"123456";username|s:9:"USERNAME";csrf|a:2:{s:9:"timestamp";i:1491591384;s:5:"token";s:32:"7539b1c235e46f2f9fcd74ab6b5cf13b";}`

However, in some cases, not sure yet why, the CSRF part is not inserted. Is there a javascript that changes or tries to change that value when the page is loading?

**Comment by asmecher** [comment]
I wonder whether this is a concurrency thing (race condition) caused by near-simultaneous loads of different components of the page. Still trying to figure out how to replicate it locally. I'd suggest outright disabling one-click reviewer URLs, though, as they complicate the issue with respect to session management -- if this can be duplicated without them, it'll reduce the number of variables to tackle.

OJS 2.x doesn't exhibit this behavior and shares a lot of session management code with OJS 3.x. On the flip side, OJS 2.x doesn't have the same kind of concurrency demands as OJS 3.x does, since OJS 2.x tends to build responses in a single contiguous page load.

Another possible cause is the JS front-end, e.g. the AjaxFormHandler, but I wouldn't expect that to totally invalidate a session, which seems to be happening here.

**Comment by ajnyga** [comment]
Thanks! I will continue testing this on Monday.

I just want to stress that I have not been able to reproduce scenario 1 on a fresh install which is situated on the same server. So the problem has to be with a) OJS settings or b) old data in db. 

Also, I have not been able to reproduce the problem in our production server consistently. What the exact combination is, I am not sure.

I have started to think two things: 
Firstly, could the `session_check_ip` setting affect this somehow? That is disabled in our production server because it created problems with some users coming from university networks.
Secondly, if I am testing this with several reviewer accounts at the same and using the same browser/ip, could that mess something up? I will do some testing with this scenario on Monday.

**Comment by asmecher** [comment]
The `session_check_ip` setting could indeed be related -- it's best to disable that in general, as certain users may be behind a proxy pool and their sessions will periodically be invalidated if their proxy server changes.

**Comment by ajnyga** [comment]
I have tried to debug the problem with the oneclick links the whole day. As mentioned above, for some reason the crsf token is sometimes missing from the session data after logging in with with a oneclick link (`csrf|a:2:{s:9:"timestamp";i:1491591384;s:5:"token";s:32:"7539b1c235e46f2f9fcd74ab6b5cf13b";}`) and this results to a form error.

Here are some things I have noticed:

- I can reproduce the oneclick problem with a clean install of OJS302 in a subdirectory of our production server. I can not reproduce it in my local XAMPP server or one of our test servers. This has led me to believe that some server (or OJS) setting could affect this.

- session_check_ip does not seem to affect this. I changed the setting in our production server with no results.

- I have tested these scenarious multiple times with different reviewer accounts:

1. Clean browser cache, clear OJS sessions table => click oneclick link.
This is the scenario that in many cases creates the problem, **but not always**. 

I noticed that there is a small delay before the csrf part appears to the session: why is that? It almost seems like the session data is written twice when the review form is loaded and maybe in some cases the second load is getting stuck? I could not track down in the code the exact places where the session data is written the the table.

2.  Login with oneclick link, log out => clear OJS session table => click oneclic link
This too in some cases creates an error, not always.

3. Login with oneclick link, log out => **do not** clear OJS session table => click oneclic link
This does not create the error.

As you can see, the problem seems to be somewhat random. I have not been able to reproduce this at all with IE, only with Firefox, but it could be that I have just tested far more with FF.

Any suggestion what to debug?

**Comment by ajnyga** [comment]
I did some debugging by adding this line `error_log(print_r($data, true));` here https://github.com/pkp/pkp-lib/blob/master/classes/session/SessionManager.inc.php#L186

This is the output in a situation when a user click a oneclick link with no existing cookie or session:
```
[Tue Apr 25 15:44:26 2017] [error] [client 192.xxx.xx.xx] userId|s:5:"123456789";username|s:9:"USERNAME";

[Tue Apr 25 15:44:26 2017] [error] [client 192.xxx.xx.xx] userId|s:5:"123456789";username|s:9:"USERNAME";, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259

[Tue Apr 25 15:44:29 2017] [error] [client 192.xxx.xx.xx] userId|s:5:"123456789";username|s:9:"USERNAME";csrf|a:2:{s:9:"timestamp";i:1493124269;s:5:"token";s:32:"b0c49d625416b896c91339cdba6ef8f5";}, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259

[Tue Apr 25 15:44:29 2017] [error] [client 192.xxx.xx.xx] userId|s:5:"123456789";username|s:9:"USERNAME";, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259
```

So it seems that write is called four times during one page load. Note that on the third time CSRF token exists, but during the last call it has been removed.

**Comment by asmecher** [comment]
@ajnyga, hmm -- I would suggest trying to correlate these writes with round trips to/from the server. Could you log the request URI alongside the calls to write the session?

**Comment by ajnyga** [comment]
Hi,

I think you are right @asmecher 

I added:
error_log(print_r($_SERVER['REQUEST_URI'], true));
error_log(print_r($data, true));

This is the output when the **error happens**
```
[Tue Apr 25 20:21:54 2017] [error] [client 10.x.x.x] /journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9

[Tue Apr 25 20:21:54 2017] [error] [client 10.x.x.x] userId|s:5:"18261";username|s:9:"USERNAME1";

--

[Tue Apr 25 20:21:54 2017] [error] [client 10.x.x.x] /journalname/$$$call$$$/page/page/css, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9

[Tue Apr 25 20:21:54 2017] [error] [client 10.x.x.x] userId|s:5:"18261";username|s:9:"USERNAME1";, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9 

--

[Tue Apr 25 20:21:56 2017] [error] [client 10.x.x.x] /journalname/reviewer/step/52783?step=1&_=1493140915359, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9
[Tue Apr 25 20:21:56 2017] [error] [client 10.x.x.x] userId|s:5:"18261";username|s:9:"USERNAME1";csrf|a:2:{s:9:"timestamp";i:1493140916;s:5:"token";s:32:"98d03951a80b33cf0ad823e17f5e0ec5";}, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9

--

[Tue Apr 25 20:21:56 2017] [error] [client 10.x.x.x] /journalname/$$$call$$$/page/page/user-nav-backend?_=1493140915358, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9
[Tue Apr 25 20:21:56 2017] [error] [client 10.x.x.x] userId|s:5:"18261";username|s:9:"USERNAME1";, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9
```

This is the output when the **error does not happen**
```
[Tue Apr 25 20:15:12 2017] [error] [client 10.x.x.x] /journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259

[Tue Apr 25 20:15:12 2017] [error] [client 10.x.x.x] userId|s:5:"18262";username|s:9:"USERNAME2";

--

[Tue Apr 25 20:15:12 2017] [error] [client 10.x.x.x] /journalname/$$$call$$$/page/page/css, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259

[Tue Apr 25 20:15:12 2017] [error] [client 10.x.x.x] userId|s:5:"18262";username|s:9:"USERNAME2";, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259

-- 

[Tue Apr 25 20:15:15 2017] [error] [client 10.x.x.x] /journalname/$$$call$$$/page/page/user-nav-backend?_=1493140513511, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259

[Tue Apr 25 20:15:15 2017] [error] [client 10.x.x.x] userId|s:5:"18262";username|s:9:"USERNAME2";, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259

--

[Tue Apr 25 20:15:15 2017] [error] [client 10.x.x.x] /journalname/reviewer/step/52783?step=1&_=1493140513512, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259

[Tue Apr 25 20:15:15 2017] [error] [client 10.x.x.x] userId|s:5:"18262";username|s:9:"USERNAME2";csrf|a:2:{s:9:"timestamp";i:1493140515;s:5:"token";s:32:"619b2e2c1ef836ae93f90dace9150b42";}, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4648&key=43Jqh259
```

`/journalname/reviewer/step/52783?step=1&_=1493140513512` and `/journalname/$$$call$$$/page/page/user-nav-backend?_=1493140513511` are in different order when the CSRF part is missing!

**Comment by asmecher** [comment]
My current hypothesis:

- CSRF tokens are only generated when they're needed, and stored as part of the session thereafter.
- The "main" request for the review page doesn't require a CSRF token so one isn't generated when that page is hit.
- I suspect at least two subrequests do require CSRF tokens
- A race condition between these means whichever subrequest is handled *last* will leave a valid CSRF token behind; the first request's CSRF will be clobbered.

The fix I'd propose for this in https://github.com/asmecher/pkp-lib/commit/1bf353e86b45456177005f8f9a4d7d36f0c9cc64 is to get the main request to generate and store the CSRF token as a courtesy, even though it doesn't need to use it. That'll resolve the race among subrequests, because the markup resulting from the main request is what kicks off the subrequests (thus the CSRF token will be guaranteed generated already).

@ajnyga, can you do a little bit of testing with this to see if it improves behavior? I'm flying blind here as I can't seem to cause the behavior you describe.

**Comment by ajnyga** [comment]
Thank you @asmecher,

I will see what that does to the problem. This could take some time because I can not reproduce it consistently. However, looking at the solution and the output I got earlier when debugging, I do think that this solves it.

I think that this issue is related to the amount of traffic the server is getting. Because, as I said, I can only reproduce this in our production server and also there only sometimes.

**Comment by ajnyga** [comment]
Hi @asmecher,

That one line definitely makes all the difference. This is the output after the patch:

```
[Thu Apr 27 22:25:36 2017] [error] [client 10.x.x.x] /journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9
[Thu Apr 27 22:25:36 2017] [error] [client 10.x.x.x] userId|s:5:"18261";username|s:9:"USERNAME1";csrf|a:2:{s:9:"timestamp";i:1493321136;s:5:"token";s:32:"d54343e61c2c13803bdbf1e72cb548ae";}
--
[Thu Apr 27 22:25:36 2017] [error] [client 10.x.x.x] /journalname/$$$call$$$/page/page/css, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9
[Thu Apr 27 22:25:36 2017] [error] [client 10.x.x.x] userId|s:5:"18261";username|s:9:"USERNAME1";csrf|a:2:{s:9:"timestamp";i:1493321136;s:5:"token";s:32:"d54343e61c2c13803bdbf1e72cb548ae";}, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9
--
[Thu Apr 27 22:25:40 2017] [error] [client 10.x.x.x] /journalname/reviewer/step/52783?step=1&_=1493321137846, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9
[Thu Apr 27 22:25:40 2017] [error] [client 10.x.x.x] userId|s:5:"18261";username|s:9:"USERNAME1";csrf|a:2:{s:9:"timestamp";i:1493321136;s:5:"token";s:32:"d54343e61c2c13803bdbf1e72cb548ae";}, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9
--
[Thu Apr 27 22:25:40 2017] [error] [client 10.x.x.x] /journalname/$$$call$$$/page/page/user-nav-backend?_=1493321137845, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9
[Thu Apr 27 22:25:40 2017] [error] [client 10.x.x.x] userId|s:5:"18261";username|s:9:"USERNAME1";csrf|a:2:{s:9:"timestamp";i:1493321136;s:5:"token";s:32:"d54343e61c2c13803bdbf1e72cb548ae";}, referer: http://domain.net/journalname/reviewer/submission?submissionId=52783&reviewId=4642&key=68ALLnA9

```
The CSRF token is now consistently in all the four calls, so it will not matter if the user-nav-backend calls comes in last!

Thanks!

Basically scenarios 1 and 3 are solved now, scenario 2 is theoretical (and probably solved with this fix as well) and the scenario 4 is probably solved as well. (https://github.com/pkp/pkp-lib/issues/2417#issuecomment-292138470)

There have been occasions in OJS3 workshops where the submission or review forms break in a bit different way. It could be that these are related to CSRF as well, but have felt more like javascript issues. But these are for another ticket if I find a consistent pattern there. I have not had many workshops lately.

**Comment by asmecher** [comment]
Excellent, thanks for all your work helping to track this one down, @ajnyga! Merged to `master`, `ojs-stable-3_0_2`, and `omp-stable-3_1_0`.
