### ISSUE TITLE
[OJS] Formbuildervocabulary does not consider required param for textareas

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2418]
Hi,

I noticed that when you create a custom review form, you can not make a `textarea `voluntary. The selection is saved correctly in `review_form_elements`, but it does not apply when the form is opened. The same thing does not happen with for example `select ` elements.

The reason seems to be in the `formbuildervocabulary ` that does not consider the `required` param for textarea's.

PR: https://github.com/pkp/pkp-lib/pull/2419

Note: I do not know whether this would affect for example the settings forms?

**Comment by asmecher** [comment]
Merged, thanks! Also cherry-picked to `ojs-stable-3_0_2` and `omp-stable-3_1_0`.
