### ISSUE TITLE
[OJS 3.x] No check on PHPMailer::send() status

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2420]
We catch exceptions from PHPMailer, but an error in sending doesn't necessarily generate an exception.
https://github.com/pkp/pkp-lib/blob/91da80b797e2f7dd98014134251c2884de6f30c5/classes/mail/Mail.inc.php#L516-L522

So, if `PHPMailer::send()` simply returns false, the email fails and there is no feedback in the UI or in the error log.

I replicated this by configuring a bad SMTP connection in config.inc.php and attempting to send a email to a user in OJS 3.0.2.

**Comment by asmecher** [comment]
Thanks, @ctgraham!
