### ISSUE TITLE
Style lost at logging out ?!

### ISSUE THREAD

**Issue by bashar81** [pkp/pkp-lib#2425]
We are losing style at every logout of a journal page.

Any suggestions ?

![image](https://cloud.githubusercontent.com/assets/13675795/24754480/47366e18-1adf-11e7-9207-81c64fb67781.png)

**Comment by asmecher** [comment]
@bashar81, what version of OJS are you using?
Is your journal public, and if so, what's the URL?

**Comment by bashar81** [comment]
I am using the 3.0.1, clean install, at http://journals.ju.edu.jo
In my case, upgrading to the 3.0.2 failed due to a DB error. I managed to get the DB back to its original condition until next weekend so i could try once more !

**Comment by asmecher** [comment]
@bashar81, I ran through a test registration and wasn't able to see the behavior you describe.

**Comment by bashar81** [comment]
That's strange ! This is frequently occurring with me when logging out from a journal page.

**Comment by asmecher** [comment]
Can you try the process with another browser to see if it might somehow be browser or cache related?

**Comment by asmecher** [comment]
Closing (lack of feedback).
