### ISSUE TITLE
Add ISBN as a metadata field and include in public display

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2427]
OMP does not currently have a field to add an ISBN for individual monographs. This should be added to the metadata (not collected from authors, but able to be added later by editors) and be displayed on the public interface.

**Comment by bozana** [comment]
@stranack, there is a possibility to add ONIX ISBN, in the publication formats tab, under Product Identification. This would then also be displayed in the right sidebar. Would that work/be enough?

**Comment by kshuttle** [comment]
An ISBN metadata field for OMP would still be useful. Ideally it would be great to see this in the Publication tab under Identifiers, with the DOI field.

**Comment by NateWr** [comment]
ISBN's are available to assign to the publication format. And as far as I understand, a unique ISBN should be assigned to each "edition" of a book (ie - publication format). I'll close this for now, but if there is further discussion to have about ISBNs, let's file a new issue with some specific use cases. cc @ajnyga
