### ISSUE TITLE
[OJS] Provide option to add "hidden" participants to submissions

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2430]
There are instances where participants on a submission should be hidden from the authors or other non-privileged contributors (eg. those at the editor level): 

- administrative or low-level staff who don't need to be seen/interacted with authors to do their jobs (eg. typesetters); 
- in some journal workflows, section or guest editors shouldn't be seen by authors, and definitely not contacted by (eg. berated by) authors

Providing an option for the assigned editor to "hide" users when they are added as a participant would be great. I'd suggest that this should be a per-assignment option in the assignment modal, and these users should be identified somehow as such to the editor in the participant list. They simply shouldn't be displayed in the author's Participants view, and discussions should also be hidden.

**Comment by asmecher** [comment]
On the administrative side, see https://github.com/pkp/pkp-lib/issues/440 -- this gives site admins access to the "log in as" feature.

**Comment by jmacgreg** [comment]
Hi @asmecher, I don't think that relates to this general use case, for example where an editor wants someone like a section editor to work on a submission, but without being seen (and contacted, questioned, pestered, etc.) by the author. At the same time, these participants should still act as full participants on the submission, and should also have their actions and whatnot recorded.

**Comment by asmecher** [comment]
Gotcha, I saw the word "administrative" and read "administrator" ;)

**Comment by NateWr** [comment]
My worry would be that the privacy protection would be prone to human error if an editor has to manage it manually. What would be the reason not to include author-visibility as an option attached to a user role, as you suggested for #2433? That way it would apply to everyone with that role rather than at the editor's discretion?

**Comment by asmecher** [comment]
(Clearing the milestone, as I'm not at all sure about this feature add -- I like @NateWr's suggestion above, if it's workable.)

**Comment by asmecher** [comment]
This also applies to choosing discussion participants (per SI's request).

**Comment by jmacgreg** [comment]
Closing as we've only had one request for this, I don't think it's a pressing issue.

**Comment by MarkWieczorek** [comment]
It would be nice to re-open this issue, as it is a necessary feature for our journal! Here is a discussion that I just started on the forum:

https://forum.pkp.sfu.ca/t/provide-option-to-hide-participants-from-authors/98143
