### ISSUE TITLE
Saving changes in other locals

### ISSUE THREAD

**Issue by bashar81** [pkp/pkp-lib#2431]
Dear Sir,

There seems to be an issue saving changes in other locales. The pointer keeps rolling for hours. Same things happens when you try to upload a file with a name in a different locale than English.

Any suggestions ?
Regards,

**Comment by asmecher** [comment]
Which of our applications are you using, and what version? (Please include this information with your posts.)
Check your PHP error log to see if relevant details appear there.

**Comment by bashar81** [comment]
OJS 3.0.1, clean install, nothing on PHP log !

**Comment by bashar81** [comment]
OK, so it seems the database/tables encoding was incorrect. Basically, it was automatically created as latin_swidish_ci. After transforming the database and the tables into utf8mb64_general_ci it was solved. I think this should be specifically inserted into the DB creation script. And this seems the reason my earlier DB couldn't update successfully to the new OJS version. I will give it a shot and let you know later.

Regards,

**Comment by asmecher** [comment]
Thanks, and glad to hear it's resolved!
