### ISSUE TITLE
localized issue cover images

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2432]
equivalent to this article cover images, s. also https://github.com/pkp/pkp-lib/issues/1062

**Comment by bozana** [comment]
PR:
ojs-dev-2_4: https://github.com/pkp/ojs/pull/1348

**Comment by bozana** [comment]
@asmecher, s. https://github.com/pkp/pkp-lib/issues/1062#issuecomment-292893034. Could you then take a look at this PR, if it is OK and should be merged? THANKS!

**Comment by bozana** [comment]
@NateWr, could you maybe take a look at this?

**Comment by NateWr** [comment]
Oh, I see this is for OJS 2.x. I actually have never worked with OJS 2.x. I don't even have it installed! 

I did a quick read of the code and it looks ok. Maybe one of the publishing services people can run a quick test on it? If not, I can try to get it installed and figure it out.

**Comment by asmecher** [comment]
It looks OK at a glance, @bozana -- if you've tested it, please go ahead and merge!

**Comment by bozana** [comment]
Merged, thus closing... THANKS!!!

**Comment by martinpub** [comment]
Much appreciated @bozana, thanks!
