### ISSUE TITLE
[OJS] Add preliminary/summary "Decline" email template

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2434]
Again, requested by a number of journals recently. The submission workflow could benefit from a separate "summary reject" email template that would be used if a submission is immediately determined to be unsuitable, eg. before peer review. When the "Decline Submission" button is clicked from the initial Submission workflow stage, this summary reject template would be used instead of the current decline template.

**Comment by alexxxmendonca** [comment]
This would also be extremely helpful for us.

👍

**Comment by defstat** [comment]
@asmecher 

PRs:
OJS: pkp/ojs#1462
LIB: #2668

**Comment by asmecher** [comment]
@defstat, I think this could be done more simply. Since the "Initial decline" is the same as the normal "decline" except for the email template, it should be possible to only change [EditorDecisionWithEmailForm.inc.php::initData](https://github.com/pkp/pkp-lib/pull/2668/files#diff-19b7c52b579ffb95557ba526ed72a0b0) so that the appropriate email template is invoked if the submission stage is the submission stage.

For the email text, I'd suggest using the same as `REVIEW_DECLINE`, and letting managers customize it if they wish.

We'd also need to install the new email template upon upgrade.

**Comment by alexxxmendonca** [comment]
Statistically speaking, it would be important to differentiate this initial rejection from the peer-reviewed rejection. 

Our journals often need to know their "desk reject" ratio, and this would mean the papers that received that initial rejection.

That being said, it should be still considered as a "final reject" decision on a general statistic number -- which would be a combination of initial rejection + peer reviewed rejection.

**Comment by jmacgreg** [comment]
+1 for differentiating and tracking between different reject types. 

@defstat, it doesn't matter to me whether the text of the new email is the same as the REVIEW_DECLINE email as long as it's editable, but if you would like to provide some different default text I would be happy to provide some feedback there.

**Comment by asmecher** [comment]
Point taken! @defstat, you were right.

**Comment by defstat** [comment]
@asmecher I have changed the name of the email template as well as the name of the decision type. I suppose I have added the email template to the upgrade.xml script like so

`<code function="installEmailTemplate" key="EDITOR_DECISION_INITIAL_DECLINE" locales="en_US" />`

but the upgrade tool does not seem to install the template (the installation process successfully installs the template though). Should I change some other upgrade file as well?

**Comment by asmecher** [comment]
@defstat, where in `upgrade.xml` did you put the `installEmailTemplate` call? When running the command-line version, do you see the upgrader running through upgrade processes in the same area of `upgrade.xml`?

**Comment by asmecher** [comment]
@defstat, ah, I see it's in the OJS 2.x to 3.x portion of the upgrade, i.e. inside:

    <upgrade minversion="2.4.0.0" maxversion="2.4.9.9">

Are you testing a 2.x to 3.x upgrade? If so, you should also see the template added. If you're testing a 3.x to 3.x upgrade, it won't currently work -- that `installEmailTemplate` line also needs to be added to the 3.0.x to 3.1 area of the `upgrade.xml` file.

**Comment by defstat** [comment]
@asmecher yes now I got it (I think) - I added the install script at the 
`<upgrade minversion="2.4.0.0" maxversion="3.0.9.9">`
part - I think that covers all range of versions?

**Comment by defstat** [comment]
@asmecher 
PR
OMP: pkp/omp#427

**Comment by asmecher** [comment]
All merged -- thanks, @defstat!
