### ISSUE TITLE
Make wording of editorial team consistent in backend and frontend

### ISSUE THREAD

**Issue by lilients** [pkp/pkp-lib#2441]
I think the different wording for the editorial team page (.../about/editorialTeam) at the backend [is](http://forum.pkp.sfu.ca/t/editorial-team-edit/21326) [confusing](http://forum.pkp.sfu.ca/t/editorial-board/26849).

Backend: 
![editorialTeam_backend](https://raw.githubusercontent.com/lilients/img/master/editorialTeam_backend.PNG)

Frontend:
![editorialTeam_frontend](https://raw.githubusercontent.com/lilients/img/master/editorialTeam_frontend.PNG)

I would propose using the term "Editorial Team" instead of "Masthead" at the backend. This way backend and frontend would be consistent. I would propose to change this in OJS and OMP.

Following keys are relevant: `manager.setup.masthead` in manager.xml and `about.editorialTeam` in locale.xml.

I would add the locale `manager.setup.editorialTeam` and simply copy the string from `about.editorialTeam` to the new locale (and change all calls of the locale in the code ...). I can do this for all languages (that have the  `about.editorialTeam` locale), this way no new translation work would be needed.

I would also change the storage of the string in the database from `masthead` to `editorialTeam`.

I can create pull requests next week. 🌞

**Comment by asmecher** [comment]
@stranack, any preferences?

**Comment by lilients** [comment]
I changed the wording of the input for the editorial team at the backend from masthead to editorial team in all languages that have the key `manager.setup.masthead` (These languages do not have it: `ca_ES`, `cs_CZ`, `eu_ES`, `hr_HR`, `nl_NL`, `pt_PT`, `sr_SR`, `sv_SE`, `tr_TR`, `uk_UA`, `zh_CN`) and in the table `journal.settings`.

Backend: 
![editorialTeam_backend](https://raw.githubusercontent.com/lilients/img/master/editorialTeam_backend_new.PNG)

Frontend:
![editorialTeam_frontend](https://raw.githubusercontent.com/lilients/img/master/editorialTeam_frontend_new.png)

**Comment by bozana** [comment]
Thanks @lilients, I'll wait for @stranack to say... then I can take a look at the PR... :-)

**Comment by stranack** [comment]
This sounds like a sensible change -- go for it!

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1356
omp master: https://github.com/pkp/omp/pull/404

**Comment by bozana** [comment]
@lilients, those are the PRs, correct? -- Did I miss something?

**Comment by bozana** [comment]
Still missing translations: eu_ES, hr_HR, nl_NL, tr_TR, zh_CN

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1650

**Comment by lilients** [comment]
thanks @bozana!
