### ISSUE TITLE
Sidebar search does not work outside of search page

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2442]
See https://github.com/pkp/pkp-lib/issues/2300#issuecomment-293081290 for details.

**Comment by asmecher** [comment]
@bricas or @diegoabadan, could one of you confirm that the patch here (listed twice, but either is equivalent) resolves the issue for you?

**Comment by bricas** [comment]
👍  Worked for me!

**Comment by diegoabadan** [comment]
Worked for me! Thanks

**Comment by asmecher** [comment]
Thanks for following up!
