### ISSUE TITLE
Reviewer affiliation info is not recorded when creating reviewers

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#2446]
I am an editor using OJS 3.0.2. When creating a reviewer at assign reviewer from review stage of submissions, the reviewer affiliation is not recorded. When you check affiliation information from user info it is not seen. The affiliation info is very important for my journal as we give certificates to the reviewers including their affiliation info.

**Comment by bozana** [comment]
PR:
lib-pkp master: https://github.com/pkp/pkp-lib/pull/2448

**Comment by bozana** [comment]
@Baytan, if you apply the patch above it should solve the problem. This will be included in the next OJS release...

**Comment by Baytan** [comment]
Thank you very much. Thanks all the contributors of the OJS. It is a great job:).
