### ISSUE TITLE
PHP code documentation cleanup

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2449]
Working with GridHandler and GridRow recently, I found a number of typos in the method documentation: things like incorrect parameter order or wrong parameter typing.

**Comment by bozana** [comment]
can the issue be closed?

**Comment by ctgraham** [comment]
Actually, maybe this should be left open as a catch-all for other inline documentation cleanup?  What do y'all think?

**Comment by bozana** [comment]
Yes, we could do that, and if we realize that new issues are being created and this one is not used, we can then close it...

**Comment by NateWr** [comment]
Going to close this for now, but happy for docblock clean-up to proceed. Feel free to file new issues if new problems are discovered.
