### ISSUE TITLE
Large log messages in the FileLoader can exceed PHP's memory_limit

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#245]
When processing large files with many execution log entries (large external log files in OJS 2.4 UsageStatsLoader is a good example), the accumulated execution log can exceed PHP's memory_limit, killing the process unceremoniously and losing the execution log email notification.

**Comment by asmecher** [comment]
Back to you, Bruno.

**Comment by beghelli** [comment]
Porting completed.

**Comment by beghelli** [comment]
Porting completed.
