### ISSUE TITLE
[OJS3] Discussion item will be created even if canceled

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#2460]
When logged in as an author you can add a discussion to the Review Discussions. On clicking "Add discussion" the panel for the discussion opens.

When you now cancel the panel I would expect that no new discussion is created. But instead an empty discussion is created, with no title. It appears on reloading the Review page. Also you can't delete the empty discussions as an author.

This behavior occurs with OJS 3.0.2

**Comment by asmecher** [comment]
@MarHerUMR, when you cancel creating a query, there should be an AJAX request to delete the empty placeholder. Could you look at a developer tool like Firebug for Firefox to watch for that deletion to happen? If it does happen, could you inspect the response to see if anything relevant appears there (e.g. an error message)?

**Comment by MarHerUMR** [comment]
@asmecher Thanks for the hint.

On closing a POST request is sent to `index.php/test/$$$call$$$/grid/queries/queries-grid/delete-query?queryId=7&submissionId=1&stageId=3`

The response is `{"status":false,"content":"","elementId":"0"}`

I'm going to have a look a the code and try to understand where the problem is coming from.

**Comment by asmecher** [comment]
At a glance, this sounds like https://github.com/pkp/pkp-lib/commit/9a3de6b89006140d606c557ea2986dba4c6c6d70 -- but that should already be included in OJS 3.0.2. Can you double-check your OJS version?

**Comment by MarHerUMR** [comment]
Shure. It's an installation of http://pkp.sfu.ca/ojs/download/ojs-3.0.2.tar.gz.

What I've seen so far:

When closing the panel the POST is sent to `index.php/test/$$$call$$$/grid/queries/queries-grid/delete-query?queryId=8&submissionId=1&stageId=3`

Response: `{"status":false,"content":"","elementId":"0"}`

After reloading the page and clicking delete a POST is sent to `index.php/test/$$$call$$$/grid/queries/queries-grid/delete-query?submissionId=1&stageId=3&queryId=8`

Response: `Response: {"status":true,"content":"","elementId":"0","event":{"name":"dataChanged","data":["8"]}}`

The only difference I can see at first glance is the order of the parameters. But this shouldn't make a difference right?

**Comment by asmecher** [comment]
Found it, thanks, @MarHerUMR -- try any of the attached patches in the `lib/pkp` submodule. All are equivalent, just applied to different branches.
