### ISSUE TITLE
[OJS3] Native Import can't clean up after failure for article section

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2461]
The article's [section reference is not required by the schema](https://github.com/pkp/ojs/blob/943db5885a8f91f905383067993a9f7cd38e82ce/plugins/importexport/native/native.xsd#L29).

However, if the article does not have a valid section reference, [it will still be imported with a section_id of 0](https://github.com/pkp/ojs/blob/e48d991cb67a3cf3c73ec6846fce89c95b701c7b/plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php#L80-L94).

The [`ArticleDAO::getFetchJoins()`](https://github.com/pkp/ojs/blob/92e46b44d853787ab4fb5bd2e6ca3cd90dd3828d/classes/article/ArticleDAO.inc.php#L364-L370) is used by [`SubmissionDAO::getById()`](https://github.com/pkp/pkp-lib/blob/90e6d2ceb6013b99724e0a713cbd02e2fcfca58c/classes/submission/SubmissionDAO.inc.php#L347) and mandates that the article have an associated section in the first join.

As a result, the ultimate call to [`SubmissionDAO::deleteById()`](https://github.com/pkp/pkp-lib/blob/90e6d2ceb6013b99724e0a713cbd02e2fcfca58c/classes/submission/SubmissionDAO.inc.php#L132-L144) will cause a fatal error if the passed in `$submissionId` is not returned as a [submission object](https://github.com/pkp/pkp-lib/blob/90e6d2ceb6013b99724e0a713cbd02e2fcfca58c/classes/submission/SubmissionDAO.inc.php#L134) when that object is used to [instantiate a `SubmissionFileManager`](https://github.com/pkp/pkp-lib/blob/90e6d2ceb6013b99724e0a713cbd02e2fcfca58c/classes/submission/SubmissionDAO.inc.php#L143).

**Comment by asmecher** [comment]
Sections are currently mandatory for articles on purpose. Some OJS 2.x users tinkered with `0` for `section_id` -- the joins in OJS 2.x where `LEFT JOIN`s -- but we've never supported that approach.

**Comment by ctgraham** [comment]
So I presume we will need to mark the `section_ref` required in the schema, and will need to ensure that the submission is not inserted to the database if not attached to a valid section (because it can't be cleaned up later!).

**Comment by bozana** [comment]
just a note, also for later: i think that article insertion is reversed if there is no such section, s. https://github.com/pkp/ojs/blob/master/plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php#L86, but the section_ref should then be required...

**Comment by ctgraham** [comment]
The error is flagged if the section is missing, but the insert is unable to be undone.  The query from `SubmissionDAO::getById()` can only find articles with valid sections, so `deleteById()` can't delete them.

The `SubmissionDAO` should probably implement an `insert()` method which checks for a valid section before committing to the database.

**Comment by ctgraham** [comment]
This gets back to the earlier question of what to do in the event of error.  Did we settle on exceptions as the standard for 3.x?  I see only a few instances in the codebase.

**Comment by bozana** [comment]
Ah, I see @ctgraham -- you can insert an article without a sectionId but cannot retrieve it then. Hmmm... Maybe @asmecher can tell how to best proceed in this and all other similar cases...
However, the native import has to be change -- the submission should not be inserted before the section is not checked...

**Comment by ctgraham** [comment]
In the immediate case, however, there is an awkward situation in the error reporting.  `PKPImportExportDeployment::addError()` expects an `$assocType` and `$assocId`.  If we catch this error by not inserting the object, then `$assocId` will be null, and any invalid section error will be grouped under one non-existent submission.

**Comment by bozana** [comment]
Yes, maybe we can introduce another assocType for that kind of error message... in that case, nothing has to be done/deleted, because no article will be inserted... ?

**Comment by ctgraham** [comment]
Similar to the required `article@section_ref`, it appears the [code in master requires `submission/revision@uploader`](https://github.com/pkp/pkp-lib/blob/d3c44030b2b8a1a538d66fd20bd81aa5f32741cf/plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php#L184-L189), but [the schema does not](https://github.com/pkp/pkp-lib/blob/d3c44030b2b8a1a538d66fd20bd81aa5f32741cf/plugins/importexport/native/pkp-native.xsd#L103).  I'll plan to mark this required as well.

**Comment by bozana** [comment]
@ctgraham, maybe you would like to also see this issue regarding the uploader... : https://github.com/pkp/pkp-lib/issues/2142

**Comment by ctgraham** [comment]
@bozana, thanks for the pointer to #2142.  If you would review the pulls there, I'll get back to working on this one.

**Comment by bozana** [comment]
Everything merged from #2142, thanks a lot @ctgraham!!!
