### ISSUE TITLE
[UI/UX] Give the author access to the copyedited and galley files grids

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2465]
> Copyediting: We should give the author access to the Copyedited grid, useful if CE uses Discussion to ask for feedback but fails to attach file.
>
> Kevin: This came up in testing. The copyeditor uploaded the file to the grid and informed the author to inspect the file -- but did not attach a copy of the file to the discussion thread. As a result, the author was unable to find the file. If the grid was visible to the author, she would have been able to find it. Wow, I hope that explanation made sense!

> Production: We should give the author access to the galley grid, useful if LE uses Discussion to ask for feedback but fails to attach file

From the [UI/UX outcomes list](https://docs.google.com/spreadsheets/d/1RkZ0avL3UIUU-hUScbM77lLCsGtk-T2_dL-FEx_vKcM/edit#gid=0).

**Comment by asmecher** [comment]
PRs:

- https://github.com/pkp/ojs/pull/1375
- https://github.com/pkp/pkp-lib/pull/2507
- https://github.com/pkp/omp/pull/409

**Comment by asmecher** [comment]
@bozana, would you mind reviewing this one?

**Comment by bozana** [comment]
@asmecher, everything fine, just minor, minor comments, so please go ahead... :-)

**Comment by asmecher** [comment]
Thanks, @bozana!
