### ISSUE TITLE
Some upgrade queries are improperly scoped

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2467]
The upgrade code contains, within the "for each journal" loop:

    $userGroupDao->update('UPDATE review_assignments SET stage_id = ?', array(WORKFLOW_STAGE_ID_EXTERNAL_REVIEW));

This needs to execute once per install, not once per journal.

Later, it contains:

    $userGroupDao->update('UPDATE authors SET user_group_id = ?', array((int) $group->getId()));

This _should_ be per-journal, but executes on the whole site dataset for every journal, resulting in authors referring to groups in other journals.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/ojs/pull/1364
@bozana, would you mind having a look?

**Comment by bozana** [comment]
@asmecher, yes, that looks good :-) Thus, when tests pass it can be merged... :-)

**Comment by asmecher** [comment]
Thanks! Merged into `ojs-stable-3_0_2` and cherry-picked to `master`.
