### ISSUE TITLE
Giving PKPSubmissionFileDAO::insertObject() a nonaccessible file reference causes a fatal error

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2469]
Given an invalid `$sourceFile` parameter passed to [`PKPSubmissionFileDAO::insertObject()`](https://github.com/pkp/pkp-lib/blob/7b7914fe6d6be505361272b3b22149f1882c910a/classes/submission/PKPSubmissionFileDAO.inc.php#L295-L324), the function will trigger a fatal error via [`$this->_castToDatabase()`](https://github.com/pkp/pkp-lib/blob/7b7914fe6d6be505361272b3b22149f1882c910a/classes/submission/PKPSubmissionFileDAO.inc.php#L321) because [`_castToDatabase()` requires/assumes a passed in `SubmissionFile`](https://github.com/pkp/pkp-lib/blob/7b7914fe6d6be505361272b3b22149f1882c910a/classes/submission/PKPSubmissionFileDAO.inc.php#L1031-L1042).

Possible culprit: `SubmissionFileDAODelegate::insertObject()` states that it will [return a `SubmissionFile`](https://github.com/pkp/pkp-lib/blob/7b7914fe6d6be505361272b3b22149f1882c910a/classes/submission/SubmissionFileDAODelegate.inc.php#L41), but it explicitly allows for a [null return in the event of error](https://github.com/pkp/pkp-lib/blob/7b7914fe6d6be505361272b3b22149f1882c910a/classes/submission/SubmissionFileDAODelegate.inc.php#L121-L127).

**Comment by NateWr** [comment]
This is obsolete as of the submission file refactor in 3.3.
