### ISSUE TITLE
 Reviewer has access to manuscript after declining review request 

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2481]
See http://forum.pkp.sfu.ca/t/reviewer-has-access-to-manuscript-after-declining-review-request/30660 for details.

**Comment by asmecher** [comment]
@ajnyga's PR, which fixes the front-end behavior: https://github.com/pkp/pkp-lib/pull/2478/commits

**Comment by asmecher** [comment]
Pulls:

- https://github.com/pkp/pkp-lib/pull/2482
- https://github.com/pkp/ojs/pull/1368
- https://github.com/pkp/omp/pull/407

**Comment by ajnyga** [comment]
wow, there was a lot more to it than I thought :)

**Comment by asmecher** [comment]
@bozana, would you mind taking a look at the PRs above?

**Comment by bozana** [comment]
Looks good @asmecher. I merged till everything is still mergeable and green ;-)

**Comment by ajnyga** [comment]
Was this not ported to 3.0.2?

**Comment by bozana** [comment]
I think it is not. I will take a look what would be needed...

**Comment by bozana** [comment]
The PRs for ojs-stable-3_0_2:
pkp-lib: https://github.com/pkp/pkp-lib/pull/2539
ojs: https://github.com/pkp/ojs/pull/1391

**Comment by bozana** [comment]
@ajnyga, would it be possible for you to test these PRs as well? THANKS A LOT!!!

**Comment by bozana** [comment]
@asmecher, could you double check the fix for ojs-stable-3_0_2 above? -- If the next minor release would use that branch, I would do more/consistent cherry-picking/back-porting to that branch for my PRs from now on... :-)

**Comment by asmecher** [comment]
Yes, please go ahead!

**Comment by amandastevens** [comment]
In OJS 3.1.1 reviewers can still see submissions they've declined to review in their "My Queue" list. They can open a declined submission and see the submission details, although I don't think they can access the files.

**Comment by asmecher** [comment]
@bozana, would you mind taking a look at the comment above?

**Comment by bozana** [comment]
In OJS 2 those declined/canceled reviews are visible for the reviewers, but were in the archive queue. @asmecher, I suppose this should also be the case in OJS 3? In that case, @amandastevens, it is correct that the reviewer can see the submission and metadata (and files if the journal setting allows it so), but those submissions should be in the reviewer's archive queue. 
Or, shall we change the concept here and not allow the review to see those submissions at all?

**Comment by amandastevens** [comment]
That's correct, @bozana , the reviewer can still see the submission and metadata. I'm inclined to think they shouldn't be able to access the submission at all after declining it but maybe there is an advantage to moving it to the reviewer's archive that I haven't thought of.

**Comment by NateWr** [comment]
Yeah, I think @amandastevens is probably right here. Although reviewers may want to see submissions they've reviewed in the past in their Archive, I don't think there's any reason to show declined assignments. These probably shouldn't appear in any list for the reviewer.

**Comment by asmecher** [comment]
Personally, I think the editor owes it to reviewers to manage reviewer communication with diligence -- they're asking for free labour, often from strangers. IMO the best practice is to communicate with potentially active reviewers that the submission is being declined as part of the decline process. IMO review activities should not be blocked by the status of an article -- a review posted on a declined article may still be valuable -- but the reviewer should definitely have some indication of the submission's status while they're working on it.

So I'd suggest perhaps...
- Clearly indicate submission status on review pages
- Warn editors of active reviews when they go to record a decision (I could see this being valuable for all kinds of decisions)

**Comment by bozana** [comment]
@asmecher, it is not the submission that is declined, but the review by the reviewer -- reviewer declines/cancels the review, but it still see the submission in his list...

**Comment by asmecher** [comment]
Sorry, I parachuted in too quickly :) yes, I agree with @NateWr and @amandastevens on this, until we hear a good reason to do otherwise.

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/4289
https://github.com/pkp/ojs/pull/2211

**Comment by bozana** [comment]
Hi all (@amandastevens, @NateWr, @asmecher ), OK, I made the changes, so that the reviewer will not seen the submissions that he/she declined the review for.
I did the minimal change -- for example I haven't removed the parameter/option for some AccessPolicies (e.g. https://github.com/pkp/pkp-lib/blob/master/classes/security/authorization/SubmissionAccessPolicy.inc.php#L30), so that we can provide it again, if we want.
@asmecher, could you take a look at the PRs above? If you think I can also consider more changes, e.g. to remove the declined check here: https://github.com/pkp/pkp-lib/blob/master/templates/reviewer/review/step1.tpl#L93.

**Comment by asmecher** [comment]
Thanks, @bozana, this looks good and simplifies the code to boot. Please continue!

**Comment by alireza08** [comment]
Hi @bozana ,
is the declined article totally removed from reviewer's list or moved to archive?
Tnx

**Comment by tothbog** [comment]
Sorry, we have just upgraded to 3.1.1.4, and while testing, I have found the above problem still existing:

Reviewers declining a review see the submission in their list, and it is nowhere indicated that they have declined it. 

What should we do?

**Comment by NateWr** [comment]
Hi @tothbog, this fix is not included in 3.1.1-4. You may need to wait until 3.1.2 or 3.2 is released. I'm not sure to which forthcoming versions it has been ported.
