### ISSUE TITLE
Default email signature is wrapped in nested anchor tags

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2483]
As a result of https://github.com/pkp/pkp-lib/issues/2064, URLs passed through mail template parameter assignment are wrapped in `a` tags on-the-fly:
https://github.com/pkp/pkp-lib/blob/594043e323656965698bd0862355472358c69697/classes/mail/MailTemplate.inc.php#L253-L255

The default email signature is, however, already wrapped in an `a` tag:
https://github.com/pkp/ojs/blob/8c8c13780e5760221ad272d66a9d2c388a34df48/locale/en_US/default.xml#L186-L188

This results in a malformed URL within the email, e.g.:
```
<a href="&lt;a href='https://dev.ojs.tld/ojs/index.php/journal' class='contextUrl-style-class'&gt;https://dev.ojs.tld/ojs/index.php/journal&lt;/a&gt;">Journal Name</a>
```

To reproduce, install OJS master, create a Journal, and initiate a password reset.  The password reset email will have the malformed URL in the signature.

**Comment by asmecher** [comment]
@defstat, could you take a look at this? Thanks!

**Comment by defstat** [comment]
@asmecher @ctgraham At #2494 I approached that a little bit differently than just "fixing" the  https://github.com/pkp/ojs/blob/8c8c13780e5760221ad272d66a9d2c388a34df48/locale/en_US/default.xml#L186-L188, which I am not sure it would be a generic solution.

The https://github.com/pkp/pkp-lib/blob/594043e323656965698bd0862355472358c69697/classes/mail/MailTemplate.inc.php#L253-L255 fix supposes that every time the function finds a template variable that its value is a URL, that URL *must* be displayed as <a href="{$value}"> {$value} </a>. The case of https://github.com/pkp/ojs/blob/8c8c13780e5760221ad272d66a9d2c388a34df48/locale/en_US/default.xml#L186-L188 is different. the display is <a href="{$value}"> something else </a>. 

So I thought that it could serve as a generic solution to do the following:
1. search the $body of the email for the href="{$key}"
2. if we find any occurrence for that pattern, replace the {$key} with $value
3. if we are done replacing those, replace all other occurrences of {$key} with  <a href="{$value}"> {$value} </a>

What do you think of that approach?

**Comment by ctgraham** [comment]
I agree that Managers or Editors would reasonably want to add their own `<a href="">somethings</a>` into the mail bodies, and just changing the default from the locale keys would be a poor solution.

I like the idea of checking for `href="{$key}"` explicitly.  Can we assume, though, that only `href` attributes would be reasonably used?  (No `<img src="">` for example?)

Note also that if an URL occurs in the subject, it should not be converted to HTML here: https://github.com/pkp/pkp-lib/blob/594043e323656965698bd0862355472358c69697/classes/mail/MailTemplate.inc.php#L257

**Comment by asmecher** [comment]
I'm an advocate for the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle), having overseen the gradual accumulation of enormous numbers of special cases like this e.g. in the OJS 2.x codebase. Is there a downside to just fixing the locale key, @defstat?

**Comment by defstat** [comment]
@asmecher two things pops into my mind: The case where someone wants a different name for its URL and if someone edits the email template so that he uses a template variable inside any html tag described by a url (http://stackoverflow.com/questions/2725156/complete-list-of-html-tag-attributes-which-have-a-url-value). 

I will check any other occurrences of <a href={$..}> in all templates.

**Comment by asmecher** [comment]
OK, sounds good, @defstat, I'm convinced!

**Comment by defstat** [comment]
@asmecher @ctgraham You think that we need something else for that fix?

**Comment by asmecher** [comment]
Does this pull cover everything? https://github.com/pkp/pkp-lib/pull/2494

**Comment by defstat** [comment]
@asmecher PR: #2494

**Comment by asmecher** [comment]
Thanks, @defstat -- closing!
