### ISSUE TITLE
[OJS] Any timeline for updated plugins?

### ISSUE THREAD

**Issue by trenkert** [pkp/pkp-lib#2487]
Is it possible to give a prospective timeline for the updates on plugins for OJS3?

Especially the

- browse plugin
- customlocale plugin

It would really help if developers and admins knew at which point which plugins will (may) be available again.

**Comment by asmecher** [comment]
@trenkert, could you post this on our forum at http://forum.pkp.sfu.ca/? this isn't really a bug report, so the forum is a better venue for it.
