### ISSUE TITLE
Missing newline between EndNote %P and %V

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2496]
See http://forum.pkp.sfu.ca/t/how-to-cite-endnote-issue-merged-fields/30801

I don't understand why yet, but the `if` for "%P" here is omitting the newline:
https://github.com/pkp/ojs/blob/dfd84aa0242ce30ea75207b27a2fe945b113a4ef/plugins/citationFormats/endNote/citation.tpl#L34-L35

**Comment by ctgraham** [comment]
This seems to be a recurring Smarty argument/bug:
https://groups.google.com/forum/#!topic/smarty-developers/0bJE32HkB7c

**Comment by ctgraham** [comment]
Dumb workaround solutions: add a space to the end of the "%P" line; add an extra newline to between the end of the "%P" line and the closing `{/if}`; hardcode a `{"\n"}`.

**Comment by asmecher** [comment]
Thanks -- merged and cherry-picked. Another option might be to recode this inside PHP rather than using a Smarty template at all; Smarty's not the best when it comes to control over whitespace.
