### ISSUE TITLE
OJS 3.x TinyMCE not activated show error

### ISSUE THREAD

**Issue by michaelmeneses** [pkp/pkp-lib#2497]
**EN**
When updating OJS from 2.x to 3.x, the following error occurred while entering site settings.
As the TinyMCE plugin was not activated it presented this error and did not allow to open the Plugins tab.

I'll submit a correction.

**PT_BR**
Na atualização do OJS de 2.x para 3.x houve o seguinte erro ao entrar nas configurações do site.
Como o plugin TinyMCE não estava atividado apresentava esse erro e não permitia abrir a aba de Plugins.

Vou submeter uma correção.

![captura de tela de 2017-05-08 10-56-14](https://cloud.githubusercontent.com/assets/6410303/25807537/86edbde2-33dd-11e7-9b02-e68ffe979978.png)

**Comment by michaelmeneses** [comment]
Pull request **OPEN** in https://github.com/pkp/pkp-lib/pull/2498

**Comment by asmecher** [comment]
Thanks, @michaelmeneses -- and just for our information, is there a reason you're using OJS without the TinyMCE plugin enabled? A lot of functionality expects it to be working/enabled.

**Comment by michaelmeneses** [comment]
@asmecher 

I upgraded OJS from 2.4.8.1 to 3.0.2 and one of the site's journals was not TinyMCE enabled. Actually presented this error that prevented the display of the list of plugins.

If errors can happen because TinyMCE is disabled, this is one of them.

**Comment by asmecher** [comment]
Was that journal not TinyMCE-enabled on purpose, or was it accidental? (Just collecting requirements.)

**Comment by michaelmeneses** [comment]
For now I'm testing the update in the development environment.
I joined the production environment and the TinyMCE plugin is really disabled.
It was not purposeful.

**Comment by ajnyga** [comment]
Hi, I bumped into this a few times after the upgrade from OJS2. The problem was that when tinymce was disabled in OJS2 and you upgraded to OJS3, you could not enter the plugin settings tab to enable it, I had to do it from the database. It was causing a lot of errors in different settings tabs.

**Comment by asmecher** [comment]
Thanks, all -- perhaps in the longer term it would make sense to build TinyMCE into OJS fully, rather than shipping it as a plugin. But for now this seems to resolve the issue.
