### ISSUE TITLE
subject and subjectClass migration

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2501]
From https://github.com/pkp/pkp-lib/issues/1828#issuecomment-299922155:

> ...the OJS2 to OJS3 upgrade should migrite "subjects" (per the code) to OJS3's "keywords", and "subjectClass" (per the code) to "subjects"...

**Comment by ajnyga** [comment]
Hi just to be sure I want to mention that the modification should take into account the journals that have already upgraded to 3.0.2 and thus have some of the OJS2 keywords in the OJS3 subject field AND have  the post-upgrade keywords in the keyword field.

**Comment by bozana** [comment]
@ajnyga, I am not sure we can safely move those already migrated -- because we are not sure, what were the old one and what are the new ones -- or do you think we could just consider all i.e. move all subjects to keywords? Else, we could maybe provide an extra SQL that should be manually run by those who are sure they want to do that?

**Comment by ajnyga** [comment]
Hi,

I think that all the old OJS2 values are still available in submission_settings? 
`SELECT * FROM submission_settings WHERE setting_name = subject`

So maybe:
- load all subject values from the submission_settings table to the new keywords vocabulary, compare to existing values per submission, preserve the already added values which have been done after OJS3 upgrade
- empty the OJS3 subject vocabulary
- load all subjectClass values from the submission_settings table to the OJS3 subject vocabulary

**Comment by bozana** [comment]
Ah ok then :-) THANKS!!!

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1405

**Comment by bozana** [comment]
@asmecher, could you please take a look at the PR above?
@ajnyga, it would be great if you could test it with your data...

**Comment by asmecher** [comment]
Reading the code, this looks good, thanks, @bozana -- confirmation on a data test would be nice too!

**Comment by ajnyga** [comment]
I am going to test upgrading our server with git during next week, so I could try this then. But I can only test the repairKeywordsAndSubjects part, because we are already in OJS3. I do have a copy of our OJS2 database as well, but do not know if I have the time to test that. Next week is my last week at work.

**Comment by bozana** [comment]
I tested it both witch my small amount of data, so anything you can do is very welcome and no worries for the rest! Thanks a lot!!! :-)

**Comment by bozana** [comment]
I will merge this... And in case @ajnyga encounters something, I will fix it...

**Comment by ajnyga** [comment]
With a smaller data (when testing git upgrades) I did not encounter any problems. I did not however have the time to test the full data, but will of course do that when upgrading to 3.1.
