### ISSUE TITLE
Add plugin version installation tool

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2503]
Per e.g. http://forum.pkp.sfu.ca/t/installing-a-plugin-via-git/30827, there should be an easy way to register a single plugin with the system (e.g. during development) without needing to run the entire upgrade script.

**Comment by bozana** [comment]
@asmecher, this does not consider some other things a plugin could need, for example the filters installation...

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2595

**Comment by bozana** [comment]
@asmecher, could you take a look at that PR?

**Comment by asmecher** [comment]
Just a couple of quick comments -- otherwise, please go ahead!

**Comment by bozana** [comment]
PR:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2607
