### ISSUE TITLE
Web Feed plugin causes fatal error if enabled at the site level

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2504]
At the site level, `$currentJournal` will be null, and will be used as an object:
https://github.com/pkp/ojs/blob/dfd84aa0242ce30ea75207b27a2fe945b113a4ef/plugins/generic/webFeed/WebFeedPlugin.inc.php#L96-L98

Reported and fixed here: https://github.com/pkp/ojs/pull/1373

**Comment by asmecher** [comment]
Merged and cherry-picked -- thanks, @michaelmeneses! Longer term, it would be nice to permit this plugin to operate gracefully site-wide (presumably showing content from all journals).
