### ISSUE TITLE
Update browse-plugin for OJS 3.1

### ISSUE THREAD

**Issue by trenkert** [pkp/pkp-lib#2512]
Is the browse plugin (https://github.com/pkp/ojs/blob/master/tools/buildpkg.sh#L43) being updated for OJS 3.1?

**Comment by asmecher** [comment]
The latest on this is over at http://forum.pkp.sfu.ca/t/ojs-3-0-3-0-1-browse-plugin-doesnt-show/26145 -- if you have general inquiries, the forum is a better resource than this issue tracker (which we use for bugs).
