### ISSUE TITLE
Allow SVG in image uploads?

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2513]
Currently we only support `jpg`, `jpeg` and `png`. SVG support is pretty good from IE9 up and Android 2.2.3 up (I think). Should we allow .svg uploads?

Obvious use-case is the logo field.

**Comment by asmecher** [comment]
Sure, that sounds worthwhile.

**Comment by defstat** [comment]
PRs:
OJS: pkp/ojs#1461
pkp-lib: #2666
QuickSubmitPlugin: pkp/quickSubmit#11
OMP: pkp/omp#426
