### ISSUE TITLE
ActiveSubmissionsListGridHandler code cleanup

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2514]
Some oddities in ActiveSumissionsListGridHander I noticed:

Do we really intend to filter `$column[]` keys here?
https://github.com/pkp/pkp-lib/blob/ce84dc5479a5fbe492de2dbcd6e28c6a5a36848e/controllers/grid/submissions/activeSubmissions/ActiveSubmissionsListGridHandler.inc.php#L69
Why not just `$columns['editor'] = $editorColumn;`?

If we intend to ignore the `$filterData` parameter here, it should probably be noted in the inline documentation for the API.
https://github.com/pkp/pkp-lib/blob/ce84dc5479a5fbe492de2dbcd6e28c6a5a36848e/controllers/grid/submissions/activeSubmissions/ActiveSubmissionsListGridHandler.inc.php#L87

This variable appears to be unused:
https://github.com/pkp/pkp-lib/blob/ce84dc5479a5fbe492de2dbcd6e28c6a5a36848e/controllers/grid/submissions/activeSubmissions/ActiveSubmissionsListGridHandler.inc.php#L129

**Comment by asmecher** [comment]
I think @NateWr's submission list work -- due for merging in the next few weeks -- will probably moot this.
