### ISSUE TITLE
[OJS 3.0.2.0] Bug in issueArchive.tpl

### ISSUE THREAD

**Issue by TobiasWantzen** [pkp/pkp-lib#2525]
If there is no current or archived issue in OJS, the template `ojs/templates/frontend/pages/issueArchive.tpl` should show `{translate key="current.noCurrentIssueDesc"}`. Instead, it shows an empty page with »0 of 0 items«.

Because $issues is an existing array, `lines 25 to 26` of `ojs/templates/frontend/pages/issueArchive.tpl` should be changed to:
```
	{if empty(!$issues)}
	<div>
		{translate key="current.noCurrentIssueDesc"}
	</div>
```
Maybe a special class for the `<div>` should be considered if necessary.

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1386

**Comment by bozana** [comment]
Thanks @TobiasWantzen!!!
