### ISSUE TITLE
Native Import should discriminate between errors and warnings

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2526]
The `PKPNativeImportExportDeployment` exposes errors which were added to processed objects via an associative array of those processed objects:
https://github.com/pkp/pkp-lib/blob/06bb9cf6bb4b06dbaf17f5cd435321ccbb6d4de2/classes/plugins/importexport/PKPImportExportDeployment.inc.php#L150-L160

This leads to obfuscated code such as:
https://github.com/pkp/omp/blob/138786415a8314d294aab512364be517b662ffbf/plugins/importexport/native/NativeImportExportPlugin.inc.php#L141-L147
"Let's fetch the processed object ids and then perform a magic inline function on them!"

The `PKPNativeImportExportDeployment` should have dedicated methods `getProcessedObjectErrors()` and `getProcessedObjectWarnings()` to clarify the coding structure, and to allow for non-fatal import errors regardless of the association type.  For example, currently OJS considers errors fatal at submission level, and non-fatal at the issue level:
https://github.com/pkp/ojs/blob/7c40c0fc9ea80115eb9f05453ae8c3deccef1049/plugins/importexport/native/NativeImportExportPlugin.inc.php#L349-L391

**Comment by bozana** [comment]
Thanks a lot @ctgraham! All PRs are merged... (and GitHub closed the issue)

**Comment by ctgraham** [comment]
Thanks, @bozana; I'm about to import content into our first OJS3 journal!

**Comment by bozana** [comment]
:thumbsup:
:four_leaf_clover: 
:pray:

**Comment by ctgraham** [comment]
pkp/ojs#1385 introduces some unset variables.
