### ISSUE TITLE
[OJS] ReportPlugin::report() parameter implementation is inconsistent

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#253]
ReportPlugin's definition of report() includes only $args as a parameter:
https://github.com/pkp/ojs/blob/ojs-dev-2_4/classes/plugins/ReportPlugin.inc.php#L199

Several subclasses of ReportPlugin follow suit:
https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/reports/views/ViewReportPlugin.inc.php#L51
https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/reports/subscriptions/SubscriptionReportPlugin.inc.php#L60
https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/reports/reviews/ReviewReportPlugin.inc.php#L54
The TimedViewReportPlugin is an example of one that does not:
https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/reports/timedView/TimedViewReportPlugin.inc.php#L89
and it depends on the $request parameter:
https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/reports/timedView/TimedViewReportPlugin.inc.php#L103
which is set by the caller at:
https://github.com/pkp/ojs/blob/ojs-dev-2_4/pages/manager/StatisticsHandler.inc.php#L160

Shouldn't each of these definitions be:
```
	function report($args, $request) {
```
?

**Comment by beghelli** [comment]
Thanks again.
