### ISSUE TITLE
Use SVG format of ORCID icon

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2534]
Support for SVG is IE9+.

https://figshare.com/articles/ORCID_iD_icon_graphics/5008697

**Comment by NateWr** [comment]
PRs (tests running):
https://github.com/pkp/orcidProfile/pull/18
https://github.com/pkp/ojs/pull/1441

**Comment by NateWr** [comment]
All tests passed. @bozana would you code review?

**Comment by bozana** [comment]
@NateWr, sorry for the delay! :-((( All fine, it can be merged :-) I have no write access to the orcidProfile repository, but will ask @asmecher :-)

**Comment by bozana** [comment]
@NateWr, only bootstrap3 repository to be merged, the other two are merged...

**Comment by Vitaliy-1** [comment]
@NateWr 
I don't think that it works now. The ORCID icon isn't displayed alongside with ID. 
Or am I missing something?
![screencapture-ojs-latest-stable-test-index-php-psp-article-view-107-2018-12-25-14_57_34](https://user-images.githubusercontent.com/20665587/50422733-8e0d7600-0855-11e9-92e9-f0328f32411e.png)

**Comment by NateWr** [comment]
Can you check your theme's `templates/frontend/objects/article_details.tpl` file and make sure it looks like this? https://github.com/pkp/ojs/pull/1441/files#diff-91eaa95f8172b06bd15727d9073c9b03
