### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by Akshar23** [pkp/pkp-lib#2536]
I recently upgraded from OJS 2.4.8.1 to 3.0.2.0 and i am unable to open my settings under administrator.
Can Someone help me please?

**Comment by bozana** [comment]
@Akshar23, could you please post the question in the forum: http://forum.pkp.sfu.ca and also try to give us as much information as possible? E.g. was the upgrade successful, did you get any errors/warnings, what do you see in your apache error log files when trying to open the administrator settings, etc.

**Comment by Akshar23** [comment]
Hey,
Thank you for the immediate reply and apologies for the late response.
I have been constantly trying to upgrade OJS on my website,Finally the
upgrade is successful.
I just cleared the cache folder and it worked,I'll help people on the forum
if I see them having same issues.

Thank You
@Akshar23
