### ISSUE TITLE
OJS3 upgrade article_galley_settings not migrated to submission_galley_settings 

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2537]
Hi,

When upgrading from OJS2 to OJS3 the custom galley identifiers are not migrated. In OJS2 they are stored in article_galley_settings, but in OJS3 they are stored to submission_galley_settings. This means that after the upgrade all links directed to the the custom galley identifier do not work anymore. This is easily fixed by copying the values from one table to another, but should be taken into account in the upgrade as well.

I tried to look for an earlier topic, but maybe this has not been discovered yet?

**Comment by bozana** [comment]
Thanks a lot mighty migration guru/wizard @ajnyga! :-) I will take a look... :-)

**Comment by ajnyga** [comment]
😂

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1401

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR?

**Comment by asmecher** [comment]
Thanks, @bozana -- just one question/comment!
