### ISSUE TITLE
OJS2 Layout Editor has link to Issue Galleys, but no handler for Issue Galleys

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2538]
In OJS 2.4.8-2, a Layout Editor can navigate to:
User Home -> Layout Editor -> Back Issues -> (Select Issue) -> Issue Galleys

This results in a 404.

The link appears here:
https://github.com/pkp/ojs/blob/ed3813e9d6b632cda67f7fcabd95ad9e5159a3f1/templates/editor/issues/issueToc.tpl#L51

Courtesy of:
https://github.com/pkp/ojs/blob/ed3813e9d6b632cda67f7fcabd95ad9e5159a3f1/pages/editor/IssueManagementHandler.inc.php#L635
Via:
https://github.com/pkp/ojs/blob/ed3813e9d6b632cda67f7fcabd95ad9e5159a3f1/pages/layoutEditor/index.php#L24

There is no handler for `case 'issueGalley':` in the aforementioned `index.php`.

Our current vote is that layout editors should not have access to issue galleys.

**Comment by ctgraham** [comment]
Seeking input on how this should be permissioned here: http://forum.pkp.sfu.ca/t/scope-of-layout-editor-role/31029/1

**Comment by ctgraham** [comment]
In our specific use-case, the Layout Editor is really just responsible for the Article Layout, and should not have been creating an Issue Galley anyway.

In other scenarios, I could definitely see the Layout Editor being responsible for the layout of the Issue, including the Issue Galley and the Issue Cover.

I don't imagine the Layout Editor should ever have access to the Issue Identification or the Issue DOI settings, as the Layout Editor currently does.

**Comment by asmecher** [comment]
Merged, thanks! We could argue about whether this access is overall the best policy, but it's better than a 404.
