### ISSUE TITLE
Layout Editors should be able to access Issue Galleys

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2540]
There should be a way to permit Layout Editors to work with Issue Galleys.

This dovetails with a few other issues that require some consideration on roles/permissions outside the workflow; see e.g. https://github.com/pkp/pkp-lib/issues/2320 and http://forum.pkp.sfu.ca/t/new-role-permission-level-to-to-solve-a-central-problem-in-ojs/29030.

**Comment by ctgraham** [comment]
See also: https://github.com/pkp/pkp-lib/issues/2538#issuecomment-304010638

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
