### ISSUE TITLE
update Password Reset default e-mail template

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2542]
s. http://forum.pkp.sfu.ca/t/users-not-receiving-password-in-password-reset-mail/31031
and https://github.com/pkp/ojs/commit/c794568fe773669d41eff5838f7ab2397676fe11

but also because of other changes after that...

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1398

**Comment by bozana** [comment]
@asmecher, could you take a look at this PR?

**Comment by asmecher** [comment]
Looks good, please go ahead!
