### ISSUE TITLE
OJS 2.4.x: Article Review by Access Key does not log the acting user

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2548]
To reproduce:
* Set the reviewer one-click option
* Use the provided access link to review an article
* Login as Editor and view the Article History

Expected: Article History reflects the review action, associated with the user assigned to the access key.

Actual: Article History omits any user information for the review action.

Cause:
Review actions are [logged with `ArticleLog::logEvent()`](https://github.com/pkp/ojs/blob/8c8aee18298e664dff7d7a3d8ee19e36d2a6e571/classes/submission/reviewer/ReviewerAction.inc.php#L219-L221), which [depends on `PKPRequest::getUser()`](https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/article/log/ArticleLog.inc.php#L33-L38).

**Comment by ctgraham** [comment]
I'm going to assume it would not be appropriate to autologin a reviewer based on the use of the ACCESS_KEY.  This would certainly be a quick solution.

**Comment by ctgraham** [comment]
Is it possible to call `ReviewerAction::recordRecommendation()` or `ReviewerAction::uploadReviewerVersion()` as a user other than the reviewer?

`SubmissionReviewHandler` as a `ReviewHandler` is the only core caller and current suggests "no":
https://github.com/pkp/ojs/blob/8c8aee18298e664dff7d7a3d8ee19e36d2a6e571/pages/reviewer/ReviewerHandler.inc.php#L116-L119
https://github.com/pkp/ojs/blob/8c8aee18298e664dff7d7a3d8ee19e36d2a6e571/pages/reviewer/ReviewerHandler.inc.php#L185-L192

Another quick, cheating solution would be to log directly with the reviewer object instead of delegating to `PKPRequest::getUser`

**Comment by asmecher** [comment]
> Is it possible to call `ReviewerAction::recordRecommendation()` or `ReviewerAction::uploadReviewerVersion()` as a user other than the reviewer?

At a grep, no, I don't see any cases like that.

> I'm going to assume it would not be appropriate to autologin a reviewer based on the use of the ACCESS_KEY. This would certainly be a quick solution.

We're trying to keep the access keys of limited use -- so they can only be used to perform a review, for example, and not e.g. to pilfer a reviewer account if they're compromised.

Have you considered having `ReviewerAction::recordRecommendation()` and `ReviewerAction::uploadReviewerVersion()` log with `ArticleLog::logEventHeadless` rather than `ArticleLog::logEvent`? That way you can explicitly specify a user ID.

**Comment by asmecher** [comment]
(OJS 2.x is no longer supported)
