### ISSUE TITLE
[OJS] Article without Section causes fatal error

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#255]
In OJS 2.4x: Unchecked use of $section variable at https://github.com/pkp/ojs/blob/ojs-dev-2_4/classes/article/Article.inc.php#L679 means that if an Article does not have a Section assigned, the execution will terminate with: "PHP Fatal error:  Call to a member function getDisableComments() on a non-object"

This may be at core a data issue, but even if so, a check should be added.  Should it be:
```
if ($section && $section->getDisableComments()) {
```
or
```
if (!$section || $section->getDisableComments()) {
```
?

**Comment by asmecher** [comment]
Confession time: I just ran into this recently and was irritated by it myself. I'm still in favour of some kind of data checker, but I doubt we're going to get to it before the 3.0 line. I've gone with one of your proposals in the original post.
