### ISSUE TITLE
unify the use of schedulesTasks for Cron and Acron

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2550]
s. http://forum.pkp.sfu.ca/t/any-howto-crontab-somewhere/20929/7

Basically:
-- UI in OJS for admins to see all possible scheduled tasks and to select the needed ones.
-- Add/save all scheduledTask information (e.g. frequency, enabled) into the DB table scheduled_tasks. 
-- Cron as well as Acron should then only use this table to get the list of scheduledTasks to be executed.
-- At plugin installation i.e. enabling its scheduledTask will be inserted into the DB table.
-- The time of last execution will be handled as till now.

**Comment by NateWr** [comment]
Closing this in favor of #4622, which is getting implemented as part of the 3.4 milestone.

**Comment by bozana** [comment]
Is that new issue implementing scheduled tasks -- I thought only queues... ? For some tasks it would be important to be able to say when 'exactly' they should be executed... I think there is an issue that addresses that too... So maybe that issue would replace this one... I could try to find it...

**Comment by bozana** [comment]
Oh, I must be wrong... I think it is the issue I meant... :thinking: 
Sorry

**Comment by NateWr** [comment]
#4622 will refactor how scheduled tasks are run and executed. So I think it will replace both cron and acron.
