### ISSUE TITLE
[OMP] Spotlights broken in default theme due to missing javascript

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2551]
The spotlights had a bit of JavaScript to toggle between them that was added in this commit: https://github.com/pkp/omp/commit/93a83a2ce481840c1577a4cfb16947b3b9fbadc9#diff-b80f46f36ee855b1f0c1d1ef54ead7f8

It was then accidentally removed when syncing changes from OJS default theme in this commit: 

https://github.com/pkp/omp/commit/97e22a38f1fd3282f4e5812859b9ca6059e16da6#diff-b80f46f36ee855b1f0c1d1ef54ead7f8L91

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/omp/pull/464

@bozana can you code review?

**Comment by bozana** [comment]
👍  Merged. Can the issue be closed?
