### ISSUE TITLE
fix warning in RecommendByAuthorPlugin

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2552]
s. http://forum.pkp.sfu.ca/t/http-error-during-upload-of-submission-file-ojs-3-0-2-0/31160/11

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2553
ojs master: https://github.com/pkp/ojs/pull/1409

**Comment by bozana** [comment]
@asmecher, OK so?

**Comment by asmecher** [comment]
Sure, please go ahead.
