### ISSUE TITLE
Integration with collaborative authoring platform Authorea

### ISSUE THREAD

**Issue by jmnicholson** [pkp/pkp-lib#2554]
Hello! Josh, from [Authorea](https://www.authorea.com/), here.

We have received numerous requests from OJS hosted journals/publishers wishing to directly integrate with Authorea for direct submission.  Authorea is a collaborative authoring platform that allows researchers to write in a variety of markup languages (rich text, latex, markdown) and edit and format their papers for virtually any journal submission system there is. We have integrated directly with eJP and publishers hosted on their platform (American Geophysical Union, eLife, Rockefeller University press, Society for Neuroscience) so that authors on Authorea can directly submit to these publishers.

We would like to be able to integrate in the same way with OJS journals.  Attached is a ZIP that shows what we send over during submission.  In most cases, we send content over (PDF, Word, or .tex and author metadata in XML) to the editorial systems FTP server.

Please let me know if there is anything else you need!
 
[submission (1).zip](https://github.com/pkp/pkp-lib/files/1039400/submission.1.zip)

**Comment by alexxxmendonca** [comment]
(Hi Josh!)

I would just like to add that SciELO is currently studing a partnership with Authorea. So having this integrated with OJS would benefit us if we go any further with this.

**Comment by asmecher** [comment]
Hi @jmnicholson -- we're working on an API for OJS at the moment (see https://github.com/pkp/pkp-lib/issues/1503 for some basics, although the current state of work has gone much further and isn't currently reflected there) and also have other users who have worked on submissions into OJS from other authoring/submission systems (see e.g. https://github.com/OSCOSS/OJS-Authoring-Integration-plugin).

At a glance, I don't see anything challenging in that .zip file -- but do you have some kind of a specification for both the package, and for the submission interaction? I'm thinking e.g. about things like authorization/authentication; typically in OJS a user would create an Author account, then submit via the web interface, so I'm curious what your "ideal" workflow would look like.

**Comment by jmnicholson** [comment]
Thanks for the quick response! You can find more information about how the submission process from Authorea currently works here (https://intercom.help/authorea/publish/how-do-i-directly-submit-to-a-journal). 

In short, any user writing their article on Authorea can select from a dropdown menu within their article to submit their files directly to a journal. In most cases, submissions are sent over as a partial submission where users can then complete the process as normal (they receive an invite to continue their submission from the editorial system and their author fields are prepopulated).  We can add fields on our end quite easily so if partial submissions are not ideal we can add specific requests on journal-by-journal basis and send over a full submission.

**Comment by asmecher** [comment]
@jmnicholson, as we're a distributed FOSS project, it would be difficult for us to provide you with any sort of comprehensive list of OJS journals that would be able to accept submissions through this mechanism. Would you expect the journal managers/admins to email you individually in order to have their OJS installations listed?

**Comment by jmnicholson** [comment]
Yes, we would expect to integrate technically first with one journal and the add journals on a case by case basis after coordinating with individual publishers/editors.

I presume one technical integration is sufficient for covering all journals more or less. Is that right?

**Comment by asmecher** [comment]
Yes, use cases like this would typically result in a plugin that would be available to all OJS users, either installed by default or (more likely) available for installation via a discovery/installation interface (called the "Plugin Gallery").

To flip this around, if we had a REST API allowing user account registration and submission creation, would Authorea be in a position to use it? We're working on a REST API now and use cases like this would help define concrete interactions.

**Comment by jmnicholson** [comment]
Yes, we can tie into any API. I believe that might represent the best solution going forward. Is there a feeling or timeline on when such an API is expected to be complete?

**Comment by asmecher** [comment]
That does sound ideal! We're releasing our first crack at a REST API with OJS 3.1 (our next major release, currently planned for this summer). It'll include a number of GET endpoints, but we're not sure yet what PUT/POST operations will be in place. Creating submissions is already on our list. Tagging @kaschioudi, who is currently working on the REST API implementation.

**Comment by jmnicholson** [comment]
Just wanted to check in on this. Has there been any progress on the API? Is there anything we can do to help? We're keen to integrate with OJS and have been receiving more requests for it of late.

**Comment by asmecher** [comment]
@jmnicholson, the API will be released in OJS 3.1, currently due for October. The Swagger description is available here: https://github.com/pkp/ojs/blob/master/docs/dev/swagger.yaml
