### ISSUE TITLE
[OJS] Difficulties in selecting another tagit field with multiple form locales enabled

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2556]
To @NateWr, a minor issue. 

I noticed that with the tagit field, in order to select the secondary locale you have to click an area about 200 pixels wide from the beginning of the text field (at least latest Firefox). So for example here, clicking the second field right below the entered words, the second field is activated. But if I click on the right corner of the second field, it is not getting selected.
![screenshot_19](https://cloud.githubusercontent.com/assets/16347527/26626238/4bf47184-45ff-11e7-8307-4fd51aa760d8.png)

This is only happening with the tagit fields, not for example with the subtitle field. 

Edit: also note that the locales are not showing, but I think that this was reported elsewhere?

**Comment by bozana** [comment]
Concerning the locales not showing: @ajnyga have you maybe applied these PRs: https://github.com/pkp/pkp-lib/pull/2499 and https://github.com/pkp/pkp-lib/pull/2510, s. b) in this issue: https://github.com/pkp/pkp-lib/issues/1807?

**Comment by ajnyga** [comment]
Thanks @bozana definitely have not, but did recall seeing this mentioned somewhere!

**Comment by NateWr** [comment]
Yeah the jQuery tag-it field has some issues like this. Basically, the way it works is that it creates a fake input field via styles, and then hides a little input field which appears after the existing words

The demo seems to automatically redirect focus when clicking the outer element:

http://aehlke.github.io/tag-it/

But I'm not sure why it's not doing it in our case. I've tried to wrestle with this in the past but never had much luck. I hope to resolve it as part of a wider refactor of the form input system where we'd probably move away from the lib. But I'm not aware of a properly accessible component like this anywhere.

**Comment by ajnyga** [comment]
Thanks. This is a minor problem, but seems to happen to me especially when I enter content to the first field. In these situations at least I tend to click the next field further from the right corner. With empty fields I seem to usually click the left corner of the field and the problem of course does not happen. So this is an annoying problem at most.

Hopefully PKP will give a heads up when you decide to remove the tagit library. Some of my plugins (like https://github.com/ajnyga/finto) use the in-built tagit library and I think that some others use it as well. These are of course replaceable when you change it to whatever library you decide to use then.

**Comment by NateWr** [comment]
Thanks for the heads-up. I don't foresee it happening too soon.

**Comment by bozana** [comment]
Can this issue be closed?
