### ISSUE TITLE
Consider introducing autoload behavior

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2559]
Using an autoloader, we would be able to remove the `import` function entirely. I suspect there would be a considerable performance improvement and we wouldn't need to deal with pesky maintenance of all those LOCs.

**Comment by asmecher** [comment]
@kaschioudi pointed out the Composer autoloader toolset, which is documented here: https://getcomposer.org/doc/01-basic-usage.md#autoloading

At a glance, it looks like this might require us to rename all classes to `.php` instead of `.inc.php` (!!!) -- not impossible, but certainly not ideal.

**Comment by asmecher** [comment]
I like what you've proposed in the PR, @kaschioudi. All I suggest is moving the OJS stuff out of `pkp-lib`, and it should be ready to merge.

**Comment by asmecher** [comment]
(Also see if you can resolve the code duplication between the two autoload functions.)

**Comment by kaschioudi** [comment]
PR: https://github.com/pkp/pkp-lib/pull/2627

**Comment by kaschioudi** [comment]
@asmecher :  this is ready for another look.

**Comment by asmecher** [comment]
Thanks, @kaschioudi. Did you add a namespace for the application too, or decide against that?

**Comment by asmecher** [comment]
Looks good, @kaschioudi. Can you also port the OJS change over to OMP? Feel free to self-merge those whenever you're ready.

**Comment by kaschioudi** [comment]
https://github.com/pkp/omp/pull/425

**Comment by kaschioudi** [comment]
@asmecher : just to be sure. By self merge, you mean accept the PR (into master) or merge this branch into api and submission list branch (into i2163_js_with_api) ?

**Comment by asmecher** [comment]
Into master; not sure if you have privileges to do that, though, so let me know if not.

**Comment by kaschioudi** [comment]
@asmecher OJS is ready to go. thanks.

**Comment by asmecher** [comment]
Thanks, @kaschioudi. There was a merge conflict on the `lib/pkp` submodule, so I cherry-picked in the relevant commits:

- https://github.com/pkp/ojs/pull/1443/commits/9bce9d49427d49b9b72fda178cc03fb4e0814a70
- https://github.com/pkp/ojs/pull/1443/commits/ef663c1865b58776923424033c156e015cf69f1f

...and have already committed a submodule update.

The rest were merge commits and old submodule updates. Next time, see if you can get rid of these so that only the relevant commits are left -- an interactive rebase ought to do it. I can walk you through it if you like.
