### ISSUE TITLE
Allow simple HTML in Section Titles

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2563]
I need to add italics to a journal section in OJS 3, but the tags are displayed and not rendered:

ECOLOGY AND EMPIRE: <EM>JANE EYRE</EM> AND <EM>GOBLIN MARKET</EM>

Can we add this ability? It looks like article titles can now handle italics, so adding it to section titles would be a helpful addition.

**Comment by asmecher** [comment]
See e.g.: http://forum.pkp.sfu.ca/t/how-to-make-italics-in-article-title-in-ojs-3/25598

We'd also need to figure out how to deal with both rich and non-rich variants of the same data. Titles etc. are frequently provided to 3rd-party tools e.g. via OAI, etc., and jamming HTML into those would cause trouble. It's easy enough to strip HTML tags out, but considering other use cases like mathematical formulas, taxonomies, etc. (for article titles in particular).

**Comment by asmecher** [comment]
(also see, from deep in the crypt, https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=6759)

**Comment by NateWr** [comment]
Related to #2564, where some research on the impact to downstream indexing services.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
