### ISSUE TITLE
[OJS 2.x] Instructions for References are wrong

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2570]
In OJS 2.x, the instructions for references state:
["Please separate individual references with a blank line."](https://github.com/pkp/pkp-lib/blob/8a03743be11ceeae51e53752a6396c2c52764136/locale/en_US/submission.xml#L16).
This strongly implies that you could paste formatted references with internal linebreaks, separated by blank lines.

The actual tokenizer for references, however, very explicitly assumes that [each line is one reference](https://github.com/pkp/pkp-lib/blob/8a03743be11ceeae51e53752a6396c2c52764136/classes/citation/CitationListTokenizerFilter.inc.php#L38-L48).

It would be trivial to correct the instruction to "Please enter each reference on its own line", but the option to paste formatted references separated by blank lines seems superior.

Note that the test case provides an unhelpful and convoluted test case:
https://github.com/pkp/pkp-lib/blob/8a03743be11ceeae51e53752a6396c2c52764136/tests/classes/citation/CitationListTokenizerFilterTest.php
This does not actually represent any form of a citation and mixes several styles of line separation in one test.

**Comment by ctgraham** [comment]
I'm tempted to prefer a solution such as:
```
        /**
         * @see Filter::process()
         * @param $input string
         * @return mixed array
         */
        function &process(&$input) {
                // The default implementation assumes that raw citations are
                // separated with a blank line.

                // Normalize line endings.
                if (strpos($input, "\r") !== FALSE) {
                        // Windows formatting to *nix
                        $input = str_replace("\r\n", "\n", $input);
                        // Are returns begin used as line endings?
                        $input = str_replace("\r", "\n", $input);
                }

                // Remove trailing/leading whitespace per line
                $lines = explode("\n", $input);
                $input = '';
                foreach ($lines as $line) {
                        $input .= trim($line)."\n";
                }

                // Remove trailing/leading line breaks overall.
                $input = trim($input, "\n");

                // Normalize line seperation
                $input = String::regexp_replace('/\n{2,}/s', "\n\n", $input);
                if (strpos($input, "\n\n") === FALSE) {
                        $input = str_replace("\n", "\n\n", $input);
                }

                // Break up at line endings.
                if (empty($input)) {
                        $citations = array();
                } else {
                        $citations = explode("\n\n", $input);
                }

                // Remove numbers from the beginning of each citation.
                foreach($citations as $index => $citation) {
                        $citations[$index] = String::regexp_replace('/^\s*[\[#]?[0-9]+[.)\]]?\s*/', '', $citation);
                }

                return $citations;
        }

```

**Comment by ctgraham** [comment]
Also, raw citations are passed through the `strip_unsafe_html` filter, implying that you could find legitimate HTML in a raw citation?
https://github.com/pkp/ojs/blob/2ca8fce0aec9c5d476c2af5b3b5e315347eb2707/templates/article/article.tpl#L106

No.

This should be the `escape` filter instead.  Consider ABNT as a style:
```
COSTA, Sely M. S. Filosofia aberta, modelos de negócios e agências de fomento: elementos essenciais sobre a discussão sobre o acesso aberto à informação científica. Ciência da Informação, Brasília, v. 35, n. 2, p. 39-50, mai./ago. 2006. Disponível em: <http://www.scielo.br/pdf/ci/v35n2/a05v35n2.pdf>. Acesso em: 08 out. 2012.
```

**Comment by asmecher** [comment]
(Closing 2.x issue)
