### ISSUE TITLE
Additional hooks

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2572]
s. http://forum.pkp.sfu.ca/t/hooking-to-publishissue/30863

Add a possibility to hook to a GridHandler operation/function, as well as in the publishIssue and unpublishIssue function.

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2573
ojs master: https://github.com/pkp/ojs/pull/1415

**Comment by bozana** [comment]
@asmecher, OK so?

**Comment by asmecher** [comment]
Never mind the other comment I just made (and deleted) -- I misread the `assert` condition. This looks fine, please go ahead!
