### ISSUE TITLE
[OJS] Upgrade Lucene Plugin

### ISSUE THREAD

**Issue by lilients** [pkp/pkp-lib#2575]
We would like to adapt the Lucene/Solr plugin ([code + readme](https://github.com/pkp/ojs/tree/master/plugins/generic/lucene), [description](https://pkp.sfu.ca/wiki/index.php?title=OJSdeSearchConcept)) for OJS 3. My plan looks like this:

- [ ]  implement basic search function with Solr in OJS 3
- [ ]  using recent versions of [Solr](https://lucene.apache.org/solr/) and Java
- [ ]  without destroing the OJS built-in search 😉 
- [ ]  consider OMP
- [ ]  go for fancier stuff (settings, [make issues searchable](https://github.com/pkp/pkp-lib/issues/321), [search by section](https://github.com/pkp/pkp-lib/issues/636), [mega-journals](https://github.com/pkp/pkp-lib/issues/382), ...)

As you can see, I am at the beginning of the process. Just wanted to let you know, I am working on this. I will discuss more concrete steps here later on. Always happy though to get your ideas and feedback. 🌞

**Comment by lilients** [comment]
I came across a problem upgrading the lucene plugin for OJS 3. 

The hook [`SubmissionSearch::retrieveResults`](https://github.com/pkp/pkp-lib/blob/master/classes/search/SubmissionSearch.inc.php#L246) checks if a plugin returns the search results and afterwads [handles](https://github.com/pkp/pkp-lib/blob/master/classes/search/SubmissionSearch.inc.php#L291) [the result](https://github.com/pkp/pkp-lib/blob/master/classes/search/SubmissionSearch.inc.php#L295). 

But this does not seem to work anymore, because at some point the return value of the hook seems to be converted to boolean: The plugin function [`callbackRetrieveResults`](https://github.com/lilients/lucene/blob/master/LucenePlugin.inc.php#L400 ) [returns](https://github.com/lilients/lucene/blob/master/LucenePlugin.inc.php#L518) an array with submissionIds but the [hook call in `SubmissionSearch`](https://github.com/pkp/pkp-lib/blob/master/classes/search/SubmissionSearch.inc.php#L246) gets only a boolean. 

Also returning a variable via the hook seems to be unusual in the OJS code. This is indeed the only case, where there is a return value that is beeing used afterwards someway different than as a boolean.

Is the conversion of hook return values to boolean intentional or could it be removed? In the first case I would need to change the returning of the search results differently in `SubmissionSearch` (via reference?).

**Comment by asmecher** [comment]
Hooks should always return booleans; the return value defines how other registrants on the same hook will be handled. In brief...
- `false` means carry on, call other hook registrants and go about your normal business
- `true` means "I've handled this, don't do anything more"; later hook registrants won't get called, and often the hook calling code will stop doing its normal behavior (e.g. sending an email, displaying a form, etc).

If this code tries to return something non-boolean from a hook callback, that's definitely nonstandard behavior. I'd suggest moving the return into the hook parameter list (by reference if needed).

**Comment by asmecher** [comment]
^ Merged that, much better!

**Comment by NateWr** [comment]
Closing this as more recent work has been done in #4611 and a working plugin has been released at https://github.com/ojsde/lucene.
