### ISSUE TITLE
Color of tasks panel is confusing

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2576]
Many testers are confused by the use of pink on the tasks link in the navigation menu. They think it indicates the current page.

My initial thoughts are to reposition the tasks to the top navbar, and have them drop down.

**Comment by NateWr** [comment]
@stranack et al, what do you think about moving the tasks list up to the top bar:

![selection_007](https://user-images.githubusercontent.com/2306629/27029566-c6b20e9e-4f60-11e7-9b5c-d99fc63348d6.png)

Does this downgrade the tasks list too much?

**Comment by NateWr** [comment]
PRs (tests running):
https://github.com/pkp/pkp-lib/pull/2623
https://github.com/pkp/ojs/pull/1439

**Comment by NateWr** [comment]
Tests passed. @bozana can you code review?

**Comment by bozana** [comment]
@NateWr, pkp-lib PR is merged and OJS PR closed (because test only). Can this issue be closed?

**Comment by NateWr** [comment]
On a fresh install, the tasks panel is loaded before the admin is logged in, leading to access denied errors.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2737

Tests only:
https://github.com/pkp/ojs/pull/1507
