### ISSUE TITLE
[OJS] when the user is logged ##about.onlineSubmissions.submissionActions## is displayed in Spanish translation (see images)  

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#2578]
In About > Submissions (http://domain.cl/index.php/journal/about/submissions) the text 

If you are not login you can see the normal text, but when you are logged is displaying ##about.onlineSubmissions.submissionActions## in the Spanish translation. The translate exist! because is showing when you are not logged, but disappear when you are logged! 

Examples: 

Logged: 
![image](https://user-images.githubusercontent.com/5422984/26989287-7bcb913a-4d20-11e7-8f71-72a4fd58616d.png)

Not Logged:
![image](https://user-images.githubusercontent.com/5422984/26989311-8fd02272-4d20-11e7-824e-21a5e2660895.png)

**Comment by mtub** [comment]
Hi @t4x0n , that key is indeed missing from the Spanish translation. The translation you see while not logged in should be another string. I think that the missing translation of `about.onlineSubmissions.submissionActions` will be added soon during the next round of updating the Spanish locale. (tagging @marcbria)

**Comment by thaysecantanhede** [comment]
Same occurs in portuguese. Could that be fixed via translator plugin? 
![image](https://user-images.githubusercontent.com/31325173/29688722-0bda7ffe-88f7-11e7-9486-7d8bc1117714.png)

**Comment by t4x0n** [comment]
Hi @mtub, you should close this issue because in OJS 3.1 is solved. 

Thank you!
