### ISSUE TITLE
Show all assigned roles in the user profile

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2579]
Under the Roles tab on the user Profile page, only Author, Reviewer, and Reader show -- even when I have more powerful roles, such as Editor, Journal Manager, etc. Can we add these roles to the Profile tab?

**Comment by ajnyga** [comment]
Thumbs up for this. Some editors have actually asked me why their profile is not showing all the roles.

Maybe for the high level roles there could be just selected but disabled checkboxes next to the role name and these could be in gray?

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
