### ISSUE TITLE
Fix HTML galley image migration in OJS2 to OJS3

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2582]
The old OJS2.x mapping of dependent files is not migrated to OJS3's expectations.

- Set the file_stage for dependent files to 17 (check what that constant is)
- Set assoc_type and assoc_id to 515 (submission file) and file ID of HTML galley
- Remove the defunct `submission_html_galley_images` table and references to it.
- Rename and move images, e.g.:

      mv files/journals/3/articles/244/public/244-1-4668-1-1-20170207.jpg files/journals/3/articles/244/submission/proof/244-1-4668-1-17-20170207.jpg

**Comment by hcoussy** [comment]
Hi asmecher, 
I (hcl), left a comment on [OJS forum](http://forum.pkp.sfu.ca/t/url-image-html-galley-in-ojs3/31514) today about this problem.
On your 2nd point, do you mean set assoc_type to 515 and assoc_id with file ID of HTML galley ?
I had also problems with the genre_id field that was not instanciate (eg: 46 for image/png). Did you include it ? And in this case I saw image named for example 244-46-4668-1-17-20170207.png
Thanks in advance for your answer.
Helene

**Comment by asmecher** [comment]
@hcoussy, the `assoc_type` should indeed be 515 (`ASSOC_TYPE_SUBMISSION_FILE`), and the ID should be the galley's "main" file ID (e.g. the HTML file ID), not the `galley_id`. I think nonexistent genres might be a different issue. I'll post a migration path in just a sec that might be helpful.

**Comment by asmecher** [comment]
So https://github.com/asmecher/ojs/commit/e6ec4aa7a29b03cd1dacf2ab02cd057e5af7d35e should resolve this for OJS master branch, and https://github.com/asmecher/ojs/commit/361ec474b586f3712ce53b2e9c2d00d88f5d6d9b is a near-identical port for the `ojs-stable-3_0_2` branch (i.e. an OJS 3.0.2 release). Apply whichever patch is relevant to your OJS version. Then, in order to kick off the repair without requiring a full re-upgrade, try creating the following tool in `tools/fixGalleyImages.php`:

```
<?php

/**
 * @file tools/fixGalleyImages.php
 *
 * Copyright (c) 2014-2017 Simon Fraser University
 * Copyright (c) 2003-2017 John Willinsky
 * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
 *
 * @class upgradeTool
 * @ingroup tools
 *
 * @brief CLI tool for upgrading OJS.
 *
 * Note: Some functions require fopen wrappers to be enabled.
 */

define('RUNNING_UPGRADE', 1);
require(dirname(__FILE__) . '/bootstrap.inc.php');

import('classes.install.Upgrade');

class FixGalleyImagesTool extends CommandLineTool {
	/**
	 * Constructor.
	 * @param $argv array command-line arguments
	 */
	function __construct($argv = array()) {
		parent::__construct($argv);
	}

	/**
	 * Execute the specified command.
	 */
	function execute() {
		$installer = new Upgrade(array());
		$installer->repairImageAssociations();
	}
}

$tool = new FixGalleyImagesTool(isset($argv) ? $argv : array());
$tool->execute();

?>
```

To run it, *take a backup of your database and files directory*, then run `php tools/fixGalleyImages.php`. It should return to the command line silently when finished. Check a galley before and after to verify whether it fixed the HTML images there.

This is still testing-level code, so please do take a backup first and review the published content afterwards to see whether it repaired the issue.

**Comment by jmacgreg** [comment]
Hi @asmecher, I can report success with the code patch and the PHP script process! Thanks!

**Comment by asmecher** [comment]
Thanks, @jmacgreg! Committed to `master` and `ojs-stable-3_0_2` branches. I'll leave the command-line tool here; I don't think it's worth adding to the repo.

**Comment by bozana** [comment]
Hmmm... the genre ids are not considered here...

**Comment by bozana** [comment]
Also the file (in the files_dir) is not moved...

**Comment by asmecher** [comment]
@bozana, I believe you're working on these last two issues at the moment?

**Comment by bozana** [comment]
PR: https://github.com/pkp/ojs/pull/1619
