### ISSUE TITLE
[OJS3] Changing the section does not immediately change metadata requirements

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2584]
Testing against OJS 3.0.2.  If one section requires entry of a field, and another section does not require entry of a field, an Editor cannot change the section, complying with the new section's requirements but violating the old section's requirements.

Steps to reproduce:
1) Setup two sections:
 a) Articles: require abstract
 b) Editorials: do not require abstract
2) Submit to the Articles section, with placeholder abstract
3) Reassign Submission to Editorials section:
 a) Open Submission metadata
 b) Change section
 c) Delete abstract

Expected results: Successful save of metadata
Actual results: Error saving metadata, old metadata is reloaded

**Comment by NateWr** [comment]
This is no longer an issue since OJS 3.2. The new publication tab separates the section assignment and abstract into different forms, so once the section is changed, submitting the title and and abstract form without a required abstract will return an error.
