### ISSUE TITLE
[OJS] tell admin which journal they are about to remove

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2587]
`<message key="admin.contexts.confirmDelete">Are you sure you want to permanently delete this journal and all of its contents?</message>`

In multi-journal installations, it might be safer to include the name of the journal they are about to remove - string is displayed in a pop-up after clicking on 'Remove' in the list of journals.

**Comment by NateWr** [comment]
PRs:

**Comment by NateWr** [comment]
![selection_017](https://user-images.githubusercontent.com/2306629/27233371-1911f02a-52b1-11e7-8425-29e6b25ccca4.png)

**Comment by NateWr** [comment]
Tests passed. Self-merged.
