### ISSUE TITLE
Clearing template cache should clear .css files too

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2592]
Clearing the template cache from the admin area doesn't clear the compiled CSS files. These should be cleared as well during this operation.

**Comment by RahulChakravarthy** [comment]
Hi @NateWr 
Just wanted to confirm something are you referring to this compiled css file as seen in the screenshot or a different one.

![selection_039](https://user-images.githubusercontent.com/25262322/28337996-6887f93c-6bd5-11e7-870b-007f7dc2a979.png)

Thanks,
Rahul

**Comment by TobiasWantzen** [comment]
This will be quite simple:
wwwTATuP-live/lib/pkp/pages/admin/AdminFunctionsHandler.inc.php
add after line 84:
`		$templateMgr->clearCssCache();

Thanks,
Tobias

**Comment by asmecher** [comment]
@NateWr, can you confirm @TobiasWantzen's suggestion?

**Comment by NateWr** [comment]
Thanks @TobiasWantzen!

PR:
https://github.com/pkp/pkp-lib/pull/2812

Tests only:
https://github.com/pkp/ojs/pull/1546

**Comment by NateWr** [comment]
Self-merged.
