### ISSUE TITLE
[OJS] Update pl_PL locale for OJS 3.1 release

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2603]
Issue tracking the updates to the pl_PL locale.

**Comment by puchatek108** [comment]
Is somebody working on it? Ive been manually adjusting pl language from version 2.4.8 to 3.0.2. so I can share this with anybody interested.

**Comment by marcin-golebiowski** [comment]
@puchatek108 Could you share it with me?

**Comment by puchatek108** [comment]
Sure, its in progress Ill upload soon.

**Comment by mtub** [comment]
There are already translators working on a Polish translation, but I don't know how far they got. I've asked them to join this discussion so that you can talk about how to collaborate best.

Thank you all for your efforts!

**Comment by szmigieldesign** [comment]
Hello,
I'm one of co-translators of 2.x versions. We've done together with Ewa Rozkosz - second translator - an update to 3.0 while working on two journals commercially earlier this year. Unfortunately I can't ZIP those translations as server doesn't allow it (btw - a better way to ZIP translations via translator plugin would be nice) so I have to download them manually via FTP. I'll link to an archive here for you to merge. It's complete up to the point of running an Open Access journal. Subscriptions are missing and some plugin related strings.

**Comment by mtub** [comment]
Hi Łukasz,

thanks for the update. I suggest to proceed as with other languages where we had conflicting translations: I'll merge the translation that was pre-announced from the OJS 2 translators first. (Feel free to link to an archive or send me the files via email.)

After that, if other translators could upload their translations to GitHub, we could compare and see where the other translations fill some gaps or offer some improvements - I'd be glad if you all could review the versions then.

**Comment by szmigieldesign** [comment]
There you go - this is the latest version we've made. It can be merged and extended in the future. This isn't just the translation of missing strings but also adaptation to new OJS3 workflow.

[ojs3-pl-PL-2017-08-08.zip](https://github.com/pkp/pkp-lib/files/1209145/ojs3-pl-PL-2017-08-08.zip)

**Comment by puchatek108** [comment]
Oh thats great. Thanks!

**Comment by szmigieldesign** [comment]
Shouldn't we wait for @mtub to merge the translations first?

**Comment by mtub** [comment]
Hi @szmigieldesign , I've uploaded your first batch of files (OJS locale without plugins), see
https://github.com/pkp/ojs/compare/master...mtub:i2603?expand=1

I've removed quite a lot of English text. We'll see if we can fill the gaps with the work of @puchatek108 etc., but I'd also advise you to compare the English and Polish versions after we've merged everything once more. Will continue with the other files…

**Comment by mtub** [comment]
Hi @szmigieldesign , @puchatek108 - I've merged the OJS updates from @szmigieldesign - feel free to review, send updates etc. - I will upload the pkp-lib changes soon.

For the future, I'd appreciate pull requests - it's just too much work to hand-pick the files from a larger collection containing leftover code from other plugins etc.

**Comment by szmigieldesign** [comment]
Many thanks @mtub. I'm sorry for sending such disorganized files. We simply worked on top of 2.x version the hardcore way. I believe that merging it and continuing the work on GIT will provide that no such thing happens in the future.

**Comment by mtub** [comment]
Hi @puchatek108, all contributions from @szmigieldesign have been reviewed, updated, and merged. Please compare with your files and send pull requests if necessary, so that we can all look at your suggestions.

**Comment by puchatek108** [comment]
Ok, thank You. Ill do it when I came back from summer holidays. All best!

**Comment by mtub** [comment]
Postponing the discussion until after the release. Needs collaboration between several translators and a better workflow, but we cannot figure out more updates at the moment.

**Comment by szmigieldesign** [comment]
Hello,

@mtub, I think we could use an advice on how to push the topic with translating OJS further using the proper, GIT-based way. However, I'm not sure how to approach this - should I download XML files, translate them and do pull requests or is there a better way to do it? Perhaps with translator plugin (and then GIT upload)?
