### ISSUE TITLE
Add ReCAPTCHA v2 to OJS 2.x

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2608]
Requested:
http://forum.pkp.sfu.ca/t/recaptcha-v2-for-ojs/10422
http://forum.pkp.sfu.ca/t/ojs-2-4-8-1-captcha-does-not-work/28785/9

c.f. https://github.com/pkp/pkp-lib/issues/1327 completed for 3.x

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by asmecher** [comment]
Back-ported to `ojs-stable-2_4_8`: https://github.com/pkp/pkp-lib/commit/57f784671db0640441a93ac3de9fb850157238c5 and https://github.com/pkp/ojs/commit/9ac8b86809ed6efa2841c0c66f1ba34a8384ef52

**Comment by msiraj83** [comment]
When I used recapcha v3, than i got the following error. 
"Error for owner – invalid key type"

Is v3 support is avalible in ojs-3.1.2-1 ??
Thanks

**Comment by ctgraham** [comment]
OJS 3.1.2-1 only supports ReCAPTCHA v2 at this time.  There was a user in the forum interested in working on a pull request for ReCAPTCHA v3:
https://forum.pkp.sfu.ca/t/antispam-form-ojs-3-1-0/49532/28?u=ctgraham
