### ISSUE TITLE
[OJS]: Option for Journal Homepage Setup Creates Loop

### ISSUE THREAD

**Issue by willinsky** [pkp/pkp-lib#261]
Setup Step 5.2 Journal Homepage
Under "Current Issue," when you click "Add the Table of Contents for the Current Issue," it adds the cover image for the current issue instead of the ToC. Although you can then click through to the ToC, the article PDF links lead back to the cover image, and you cannot see the articles.

**Comment by asmecher** [comment]
John, I think there are some custom modifications that are preventing that installation from operating as it should. For example, I'm guessing someone has put a delay in place? See the glacial pace of this page in particular: http://ojs.stanford.edu/ojs/index.php/intersect/issue/view/35/showToc

If someone is tinkering with that installation, I'd suggest starting by reviewing all modifications to make sure nothing there is the culprit. (For example, they could try configuring a fresh copy of the code using the database from the production installation and see if the same problems are present there.)

I suspect the redirect that's jumping from an article request back ot the ToC is probably this one:
https://github.com/pkp/ojs/blob/ojs-2_4_3-0/pages/article/ArticleHandler.inc.php#L528

**Comment by willinsky** [comment]
Juan actually did the install on this, and the glacial pace is attributed to Stanford burying us deep within their so-called cloud (aka pit). However, just heard: it turns out the editors had a problem in scheduling the articles to an issue. It is resolved now and all is working. Will keep at eye on on it to see if there's further issues.

**Comment by asmecher** [comment]
OK, sounds good.

**Comment by biosystematic** [comment]
Dear willinsky,
I have visit your website http://ojs.stanford.edu/ojs/index.php/intersect and realized that the photo that you are added to the home page is really big in size.
This photo 
http://ojs.stanford.edu/ojs/index.php/intersect/issue/view/67
is 2.43 MB that is too much for a website. to load your website very quick you should decrease the size of this photo.

**Comment by asmecher** [comment]
@biosystematic, this issue isn't related to your post, and that image size is a feature of the specific journal you're accessing, not the overarching software it uses. I would suggest contacting someone involved with the journal (see http://ojs.stanford.edu/ojs/index.php/intersect/about/contact).
