### ISSUE TITLE
Add contextual information to icons in new submission list

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2613]
Many testers struggled to interpret the icons which track reviews, files and discussions in the new submission list. We expect regular users (editors and journal managers) to learn these icons over time, but several requested some kind of contextual dropdown with more information.

This dropdown could serve more general purposes too, allowing common actions to be taken directly from the submission list. A quick mockup:
![selection_020](https://user-images.githubusercontent.com/2306629/27426321-318c83a0-5733-11e7-948e-ab3fe9b22724.png)

Another idea mockup:
![selection_051](https://user-images.githubusercontent.com/2306629/29454384-ddf997f6-8404-11e7-8fc3-fc742281b337.png)

**Comment by ajnyga** [comment]
A very large thumbs up for this!

**Comment by NateWr** [comment]
Some work in progress on this at https://github.com/pkp/ui-library/tree/i2613_submission_details

![selection_096](https://user-images.githubusercontent.com/2306629/30383800-6b005e10-989a-11e7-9526-edd5b9861b39.png)

**Comment by NateWr** [comment]
This has been merged for 3.1.
