### ISSUE TITLE
Deleting from submission list is too prominent and rarely used

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2615]
Users commented on the visual prominence of the delete button in the new submission lists. Several suggested such an activity is very rare and should be "hidden".

Confusion was also expressed regarding what "delete" means. Is it like Decline? Does it just remove from the current list? We probably need to be clear that it will permanently delete the submission and all associated objects.

**Comment by NateWr** [comment]
One idea: turn the delete button into an "Archive" button. And show the "delete" button only for archived submissions.

**Comment by mmcmahonCTU** [comment]
Yes, I thought I was just deleting myself from the reviewer role and deleted the entire thing, so agree Delete is too prominent. I'd support only having available after Archive.

**Comment by ajnyga** [comment]
+ @NateWr  for your suggestion in the second comment. Most editors just want to "clear things" so moving them to archive is quite enough.

I have a related issue that came up with the Delete button that I did not want to add as a separate issue (I can if you find it useful!).

When an user has both the editor role and the author role in a submission, the Delete button is not visible. In my logic, the higher permission level of an editor should override the limitations that the author has. So whenever an user is assigned as an editor to the submission, the button is visible.

**Comment by NateWr** [comment]
@ajnyga yes, file an issue please and tag me. I'll label it as a `bug`.

**Comment by openacademia** [comment]
Just wanted to add my agreement here! It is way too easy for editors to delete a submission without realizing it is lost forever. Some editors want to distinguish rejections from other types of removals (withdrawn papers for example), so it would be good if they could clear a submission from the active list without removing them from the face of the earth ;)

**Comment by luizbgomide** [comment]
I agree that Archive is a better option for it, allowing deletion only of Archived Submissions. That was the previous behaviour and much more natural and less error prone.

**Comment by NateWr** [comment]
The following PR does not show the delete button unless a submission has been declined. This should solve the immediate problem of accidental deletions. 

I decided not to convert the existing delete button into a decline button. There are some complex rules regarding who is allowed to decline a submission, so I thought it best to get the most important part of this in for 3.3. The ability to decline a submission from the submission list, or perform any editorial action, will be addressed in #2887.

PR:
https://github.com/pkp/ui-library/pull/120

Tests:
https://github.com/pkp/ojs/pull/2896

**Comment by NateWr** [comment]
Merged to 3.3.

@amandastevens and @kaitlinnewson I don't _think_ that this will effect documentation unless you have documentation about deleting submissions. Now the delete button will only appear for submissions that have been declined (status = `STATUS_DECLINED`).
