### ISSUE TITLE
Change "Add" to "Assign" in participants grid

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2616]
Users expressed a preference for using the "assign" terminology, especially as it corresponds with the notices in the new submissions list.

**Comment by NateWr** [comment]
PRs (tests running):
https://github.com/pkp/pkp-lib/pull/2624
https://github.com/pkp/ojs/pull/1440

**Comment by NateWr** [comment]
Tests passed. Self-merged.

@mtub I changed a string [here](https://github.com/pkp/pkp-lib/commit/8ef5820fca9a92a33190fac97022918560372bf2#diff-f69e5caa980791d6835909656e9eace7R529), but it's such a minor change I thought it best not to remove any of the translations. Do you agree?

**Comment by mtub** [comment]
agreed...

**Comment by NateWr** [comment]
@mtub I found a few more strings to change. What do you think about the changes from "link above" to "Participants list". The list is no longer "above" the message. Should the strings get removed from the other translations or left as-is?

https://github.com/pkp/pkp-lib/pull/2735/files#diff-f69e5caa980791d6835909656e9eace7L590

PRs:
https://github.com/pkp/pkp-lib/pull/2735
https://github.com/pkp/ojs/pull/1505
