### ISSUE TITLE
Add counts of submissions to submission tabs and list filters

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2617]
The submission tabs (My Queue, Unassigned, All Active, Archived) could benefit from displaying a count of submissions in each tab. This seems especially useful for Unassigned, which only needs to be viewed if one exists.

Also, when filtering (#2612) is added, there was a request to show counts by filters.

This request wasn't widespread so it remains a low priority for now.

**Comment by forgive38** [comment]
Hi, 

Just an idea (I don't think it's reasonable, but...): if submissions are indexed in an Apache Solr type, and updated with each modification, it's very easy to have a sorting or filtering with facets and counters.
And access to the submission list would be very fast.

Just an idea :)

**Comment by NateWr** [comment]
Thanks @forgive38! We do have total counts. These come back from the API requests that fill those lists. 

From v3.2, it should be _very_ easy to fulfil this issue because all the lists have a single app route in Vue.js, so the data can easily be captured and added to tabs.

Consider this a big, easy win from v3.2 onwards.

**Comment by NateWr** [comment]
From the sounds of https://github.com/pkp/pkp-lib/issues/4960#issuecomment-522562315 you might be willing to work on this. Great!

The dashboard is going through a bit of revision as part of the versioning work in #2072. In the next couple weeks that will be merged to the `master` branch and you can work off of it. 

In the meantime, you can see what the tabs look like in this template:

https://github.com/NateWr/pkp-lib/blob/i2072_versioning/templates/dashboard/index.tpl

And they are using the new `Tabs` vue component here:

https://github.com/NateWr/ui-library/blob/i2072_versioning/src/components/Tabs/Tabs.vue

You will need to extend the `Tabs` component to accept a `badge` prop and then add that to the template here:

```
<template v-else>
  {{ tab.label }}
</template>
```

So it looks something like this:

```
<template v-else>
  {{ tab.label }}
  <badge v-if="badge">{{ badge }}</badge>
</template>
```

And then you can pass in that value in `dashboard/index.tpl` like this:

```
<tab
  id="myQueue" 
  label="{translate key="dashboard.myQueue"}" 
  badge="components.{$smarty.const.SUBMISSIONS_LIST_MY_QUEUE}.itemsMax ? components.{$smarty.const.SUBMISSIONS_LIST_MY_QUEUE}.itemsMax : ''"
>
```

**Comment by NateWr** [comment]
@thinkbulecount2 do you want to take a stab at part of this? Our goal is to extend our tabs component so that we can add a badge to display beside the label, like the (12) in the image below.

![tab-badge](https://user-images.githubusercontent.com/2306629/65978850-5084eb80-e46c-11e9-9391-0b56663a6ed7.png)

Currently our tabs use markup like this:

```
<tabs>
	<tab label="First tab" id="first">
		First tab content
	</tab>
</tabs>
```

The `Tab` component would need to be extended to accept an additional `badge` prop:

```
<tabs>
	<tab label="First tab" id="first" badge="12">
		First tab content
	</tab>
</tabs>
```

So what we'd need is:

- [ ] Add a `badge` prop to the `Tab` component.
- [ ] When the `badge` prop has been passed, show a `Badge` component with that value.
- [ ] Document this property with a new previewed component in the UI Library.

**Comment by thinkbulecount2** [comment]
PRs:
[pkp-lib](https://github.com/pkp/pkp-lib/pull/5222)
[ui-library](https://github.com/pkp/ui-library/pull/47)

cc: @NateWr

**Comment by NateWr** [comment]
:tada: merged!
