### ISSUE TITLE
Extend "revisions uploaded" notification to include new files

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2618]
Currently the "revisions uploaded" notification to the editor is only invoked when an author revises an existing file. It should also notify the editor when a new (non-revision) file is uploaded. See http://forum.pkp.sfu.ca/t/notification-of-revision-upload/31676/3 for details.

**Comment by asmecher** [comment]
See also https://github.com/pkp/pkp-lib/issues/2665

**Comment by bozana** [comment]
The review round status already changes for any revision upload, just e-mail notification is missing and that will come with https://github.com/pkp/pkp-lib/issues/3278

**Comment by bozana** [comment]
The following PRs solve this as well as the issues #3326 and #2618, using the PR #3169 as a basis (but changing it as discussed there):
pkp-lib master: #3399
ui-library master: pkp/ui-library#10
ojs master: pkp/ojs#1840
