### ISSUE TITLE
Inconsistency in the translation of terms in portuguese [OMP]

### ISSUE THREAD

**Issue by amandasramalho** [pkp/pkp-lib#2620]
The terms of the tab "Catalog" are different from the warning message and the name of the tab.
In addition, the translation of the entire message does not match the English version. I suggest the translation below:

A monografia não aparecerá no catálogo enquanto a "Entrada no catálogo" não for criada. Para adicionar este livro ao catálogo, clique em "Entrada no catálogo" acima e encontre a guia "catálogo".

Portuguese:
![image](https://user-images.githubusercontent.com/5446933/27493359-f94e3d7e-581f-11e7-98bc-71045fab7bbd.png)

English:
![image](https://user-images.githubusercontent.com/5446933/27493444-433ebcd8-5820-11e7-91ed-6450f6139c67.png)

**Comment by mtub** [comment]
Thanks for reporting this. Fixed by pkp/omp#423
