### ISSUE TITLE
Add reviewer recommendation to imported comments for composing message to Author

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2628]
See http://forum.pkp.sfu.ca/t/reviewers-decision-is-not-sent-to-the-authors-fully/31744/5

**Comment by kaschioudi** [comment]
PR: https://github.com/pkp/pkp-lib/pull/3096

**Comment by asmecher** [comment]
@kaschioudi, is this ready to be closed?

**Comment by kaschioudi** [comment]
>  is this ready to be closed?

Yes

**Comment by amandastevens** [comment]
A PKP PS client asked to have reviewer recommendation not sent to the author by default with the other review comments to the author. I'm curious as to why this wasn't introduced as an option that the editor could select, as I imagine different editors have different preferences for sending the reviewer recommendation or not?

**Comment by asmecher** [comment]
@amandastevens, the editor always has the option to modify the imported comments before sending to the author, so I suspect we erred on the side of providing more information (so it can be trimmed down) rather than less (which would leave the editor chasing details to add to the email manually). This is one of those situations where we could add an option, but adding fine-grained options like these leads to an out-of-control setup interface.

**Comment by amandastevens** [comment]
I can see that.  So, the editor could change the review recommendation before sending reviews to the author, but not choose whether to include the recommendation or not.

**Comment by asmecher** [comment]
Almost. When the editor wants to send the reviews to the author, they will hit the "import reviews" button to bring the review contents into the email compose box. Then they can review and adjust/remove any information they choose before sending it to the author as an email.
