### ISSUE TITLE
[OJS] Add "Download all files" option to all submission grids

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2630]
The "Download all files" option is currently only available to users via the original Submissions grid - it isn't available in eg. Review, Copyediting, Draft files, etc. submissions grids. It would be useful to have available in all grids where submissions are managed.

**Comment by asmecher** [comment]
Added to "Production Ready" list per https://github.com/pkp/pkp-lib/issues/6115.

**Comment by NateWr** [comment]
Closing due to lack of interest.
