### ISSUE TITLE
[OCS] user home link points user home in the web site and not in the current conference

### ISSUE THREAD

**Issue by luberti** [pkp/pkp-lib#2632]
The user home link in the navigation bar points to the user home in the web site and not in the current conference

**Comment by asmecher** [comment]
@luberti, the two-level navigation/organization scheme that we used in OCS 2.x has not proven worth the trouble, and high ambiguity in where some links should go (e.g. "home" bugt also "user home") result. We plan to rewrite OCS on our current platform along the same lines as we've done for OJS and OMP; see https://pkp.sfu.ca/2017/03/06/the-future-of-ocs/. Until then, we don't plan to make further releases on the OCS 2.x line unless occasioned e.g. by a security problem.
