### ISSUE TITLE
Prevent direct access to justboil.me upload plugin

### ISSUE THREAD

**Issue by micheldiniz** [pkp/pkp-lib#2635]
The plugin can be accessed directly through the browser (as in the example site http://journals.sfu.ca/testdrive3/plugins/generic/tinymce/plugins/justboil.me/dialog-v4.htm ), if a user is registered he can upload some files, after login, through this plugin, a hacker can explore this, Is it a bug or an misunderstood configuration?

**Comment by asmecher** [comment]
@micheldiniz, see https://pkp.sfu.ca/2017/04/12/regarding-recent-ojs-defacement-attacks/ -- please feel free to follow up here if you have additional information to add.
