### ISSUE TITLE
[OJS] Replace low res icon in webfeed for high res screens

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#2637]
In the webFeed and the announcementFeed plugins are .gif icons that look blurry on high resolution screens.

I would suggest to replace those gifs with svgs by the srcset attribute. Browsers with 1x screens will still load the gifs with smaller filesize. Every other browser will load the svgs that will look sharp.

I could provide a pull request with the icons as svg, but there's one problem. The width of the images has to be set to 80px, otherwise the images will be displayed at half the size. But I'm not familiar with less so it would be great when somebody could provide some assistance.

What do you think?

**Comment by RahulChakravarthy** [comment]
Hello @MarHerUMR 

Whenever you get the time, is it possible for you to attach the icon svgs in this thread. I believe I have located where the width tag must be adjusted to 80px and I just need to test it with your svgs.

Thanks
Rahul

**Comment by MarHerUMR** [comment]
Sure. Here they are: [svg.zip](https://github.com/pkp/pkp-lib/files/1158776/svg.zip)

**Comment by NateWr** [comment]
The PR (https://github.com/pkp/ojs/pull/1457) looks good. Yes, I think these should probably go into `pkp-lib` and the change should happen in OMP as well (not sure if you've tinkered with that at all). 

When you make that change, can you issue PRs against the `master` branch as well, so we have this change going forward? Usual practice is to do the initial work against `master`, and then cherry-pick into other branches to backport it.

**Comment by NateWr** [comment]
Merged the PRs:
https://github.com/pkp/pkp-lib/pull/2664
https://github.com/pkp/ojs/pull/1460

Nice work @RahulChakravarthy! :+1: If you're satisfied that this issue is done, you can close it.

**Comment by MarHerUMR** [comment]
I just had a look at it. Looks good. Thanks a lot 👍
