### ISSUE TITLE
PDF fail to display after upgrading OJS from version 2.4.4.1 to 2.4.5.0

### ISSUE THREAD

**Issue by tningal** [pkp/pkp-lib#264]
Hi All,

Have you experienced PDF's not displaying in the browser? I have upgraded to OJS 2.4.5.0 from 2.4.4.1 and have experienced this problem and could not find a way to solve it.

I have already posted this in the forum but so far have not found any solutions yet so am posting here. I have checked and read all the posts on embedded PDFs not displaying. If anyone could share some thoughts here or provide options to explore towards solving it, I would be grateful. Any responses from gurus with in-depth knowledge on this issue would be appreciated.

Kind regards

Tine Ningal
university College Dublin (UCD)
Ireland

**Comment by asmecher** [comment]
Tine, I've responded to your PM via the forum. The related thread is: http://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=13410
It's best to keep the conversation to a single venue so it doesn't get too scattered.
