### ISSUE TITLE
copyright holder and year

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2640]
The copyright holder and year seem to be wrong: https://github.com/pkp/ojs/blob/master/pages/article/ArticleHandler.inc.php#L113
Instead the article metadata should be assigned.

s. also http://forum.pkp.sfu.ca/t/article-copyright-settings-reset-article-permissions/32075

**Comment by bozana** [comment]
PR ojs master: https://github.com/pkp/ojs/pull/1450

**Comment by bozana** [comment]
@asmecher, could you take a look at this PR?

**Comment by asmecher** [comment]
Good catch! Please go ahead. (Does this need porting to OMP?)

**Comment by bozana** [comment]
OMP seems to be fine :-)
