### ISSUE TITLE
[OJS] Remove the automatically added line breaks in article abstracts

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#2641]
Right now the article template automatically converts new line characters into line breaks:
`{$article->getLocalizedAbstract()|strip_unsafe_html|nl2br}`

When adding html with paragraphs as the abstract you will end up with additional (and imho unnecessary) line breaks between the paragraphs. The source code input in the Submission and Publication Metadata form will automatically add new line character between paragraph tags. So even this:

`<p>foo</p><p>bar</p>`

will be converted into

`<p>foo</p>\n<p>bar</p>`

and finally turned into:

`<p>foo</p><br><p>bar</p>`

The behavior of the template is at least confusing because the preview in the wysiwyg editor doesn't show what you will actually get. So I'd suggest to remove the `nl2br`.

**Comment by asmecher** [comment]
@MarHerUMR, what version of OJS are you using?

**Comment by MarHerUMR** [comment]
I saw this behavior in OJS 3.2. I'm not sure if it's the same in OJS 2

**Comment by asmecher** [comment]
@MarHerUMR, can you check that version number? OJS 3.2 hasn't been released yet.

**Comment by MarHerUMR** [comment]
You are totally right, I meant 3.0.2,sorry.

**Comment by MarHerUMR** [comment]
I've just tried it with Version build from the development source and get the same result.

**Comment by asmecher** [comment]
Thanks -- agreed, @MarHerUMR. I removed the `nl2br` filter.

**Comment by bozana** [comment]
Hmmm... it is possible that someone does not use TinyMCE, correct? -- @asmecher, do we consider/support this in OJS 3? Then this solution will lead for the text to have no line breaks...
In OJS 2 it was the same...

**Comment by bozana** [comment]
Or, if we assume that TinyMCE is always used, as mentioned here https://github.com/pkp/pkp-lib/issues/3540#issuecomment-380018934, than we can leave the TinyMCE settings as they are and remove those `nl2br` everywhere for display, but maybe consider them for upgrade from OJS 2?

**Comment by bozana** [comment]
OK, because we assume the TinyMCE to always be used, we do not have to do anything further here i.e. the removal of nl2br is correct...
Thanks @asmecher!
