### ISSUE TITLE
Facing issues while installing

### ISSUE THREAD

**Issue by atishagrawal** [pkp/pkp-lib#2643]
**Warning: require(./lib/pkp/includes/bootstrap.inc.php): failed to open stream: No such file or directory in C:\wamp64\www\ojs\index.php on line 65**

I am seeing this error when I try to install the project

**Comment by asmecher** [comment]
@atishagrawal, what version of OJS are you working with? Are you installing from a `.tar.gz` file, or from Github?

**Comment by asmecher** [comment]
Closing for lack of feedback. @atishagrawal, the forum is probably a better place to start -- see https://forum.pkp.sfu.ca/.

**Comment by ramanmittal-kiwi** [comment]
> Closing for lack of feedback. @atishagrawal, the forum is probably a better place to start -- see https://forum.pkp.sfu.ca/.

I don't have a PHP background. I am facing the same issue on installation at my window 10 with XAMPP. Please help.

**Comment by asmecher** [comment]
@atishagrawal, download OJS from https://pkp.sfu.ca/ojs_download, not GitHub. The GitHub downloads won't contain important pieces like submodules.

**Comment by ramanmittal-kiwi** [comment]
> @atishagrawal, download OJS from https://pkp.sfu.ca/ojs_download, not GitHub. The GitHub downloads won't contain important pieces like submodules.

Thanks for your quick help. After putting the files in htdocs\ojs1 directory. When I browse with web browser I get file structure of ojs1 directory like this
![Index of _ojs1](https://user-images.githubusercontent.com/29918577/73082306-3e352e80-3eef-11ea-81e5-11af6256dc7f.png)

**Comment by asmecher** [comment]
@atishagrawal, you're missing some files there. But rather than following up here, could you post on our support forum (linked above)?

**Comment by ramanmittal-kiwi** [comment]
> @atishagrawal, you're missing some files there. But rather than following up here, could you post on our support forum (linked above)?

Sure

**Comment by ramanmittal-kiwi** [comment]
Thanks again for the quick reply. I have posted at the issue at your forum. Please Reply at https://forum.pkp.sfu.ca/t/get-dbconnection-error-in-ojs-3-0-with-xampp-7-2-26/58198.
