### ISSUE TITLE
QuickSubmit plugin abstract requirement status check should depend on section

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2644]
See http://forum.pkp.sfu.ca/t/ojs-3-0-2-quicksubmit-plugin-problems-with-abstract-and-keywords/32195 for details.

**Comment by racemochridhe** [comment]
Apologies if this has been addressed already in the most recent update, but I can confirm this remains an issue in 3.2.0.3. I spent a considerable portion of the morning erasing placeholder abstract text that had to be added to ram submissions through QuickSubmit for a section that does not require abstracts.

**Comment by asmecher** [comment]
@racemochridhe, I just double-checked in 3.3.0 and it doesn't appear to be an issue. If you're able to confirm with that release, it'll help identify the source of the problem, and whether it still exists.

**Comment by racemochridhe** [comment]
Thank you for the update. I'll add that to our reasons to upgrade!

**Comment by maxfieldk29** [comment]
I am running into this issue (with the abstract anyway, not the keywords) in 3.3.0.5.

**Comment by hilongo** [comment]
We are running into this issue too... 3.3.0.5 Multi-journal multi-language installation, if that info is useful

**Comment by librariam** [comment]
+1 from PKP|PS. Confirming the abstract being mandatory in quick submit when set as not required for that section is still an issue in 3.3.0.7 and 3.3.0.8

**Comment by ewhanson** [comment]
Abstract requirement possibly addressed in pkp/quickSubmit#55.

**Comment by librariam** [comment]
+1 more from PKP|PS

**Comment by mpbraendle** [comment]
+1 from UZH and Swiss Chemical Society. Many unnecessary editing steps can be saved if this is fixed (e.g. one needs to enter some dummy text such as "No abstract" in quickSubmit and then remove it later in the submission). Would be a big time saver given the thousands of installations worldwide.

**Comment by jonasraoni** [comment]
These PRs should address the issue for `stable-3_3_0` onwards:
- https://github.com/pkp/quickSubmit/pull/55
- https://github.com/pkp/quickSubmit/pull/83
- https://github.com/pkp/quickSubmit/pull/84
