### ISSUE TITLE
Errors in QuickSubmit form entry require re-entry of keywords

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2645]
See http://forum.pkp.sfu.ca/t/ojs-3-0-2-quicksubmit-plugin-problems-with-abstract-and-keywords/32195 for details.

**Comment by taslangraham** [comment]
In the latest release, `1.0.7-2`, keywords remain in the form after server-side validation errors.

**Comment by jonasraoni** [comment]
I can confirm that it's working even on the test drive installation, which has an older version (`1.0.6-2`).
