### ISSUE TITLE
the revision node grouping for supplementary files in native export

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2648]
the grouping of revision nodes in native export does not work correctly for supplementary files:
supplementary files contain the submission_files, but also other elements, s. https://github.com/pkp/ojs/blob/master/plugins/importexport/native/native.xsd#L78-L95.
the revisions are appended to the submission and supplementary file element, s. https://github.com/pkp/pkp-lib/blob/ojs-stable-3_0_2/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php#L299
which leads to an invalid XML -- the revision elements not grouped together:

```
<supplementary_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" stage="submission" id="8791" xsi:schemaLocation="http://pkp.sfu.ca native.xsd">
      <revision number="2" genre="Data Analysis" ...>
        <name locale="en_US">...</name>
        <embed encoding="base64">...</embed>
      </revision>
      <creator locale="en_US">...</creator>
      <description locale="en_US">...</description>
      <date_created>...</date_created>
      <language>...</language>
      <revision number="1" genre="Data Analysis" ...>
        <name locale="en_US">...</name>
        <embed encoding="base64">...</embed>
      </revision>
    </supplementary_file>
```

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2649
ojs master: https://github.com/pkp/ojs/pull/1453 (ONLY submodule update)

**Comment by bozana** [comment]
@asmecher, could you take the pkp-lib PR above? ojs PR is only the submodule update.

**Comment by asmecher** [comment]
I haven't tested this, but it looks good. Please go ahead!
