### ISSUE TITLE
Native import dies if presented with a duplicate submission file revision

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2650]
If the native XML import is given a duplicate `submission_file@id` with a duplicate `submission_file/revision@number`, the code will fail hard with a database error when attempting to insert the duplicate record into the database.

This code does not prevent the duplicate insert:
https://github.com/pkp/pkp-lib/blob/73c20a0ca8eed64c3daeb45a01f0debb74b01c00/plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php#L256-L266

Hard fail is here with no error trapping:
https://github.com/pkp/pkp-lib/blob/73c20a0ca8eed64c3daeb45a01f0debb74b01c00/classes/submission/SubmissionFileDAODelegate.inc.php#L72-L79
calls
https://github.com/pkp/pkp-lib/blob/73c20a0ca8eed64c3daeb45a01f0debb74b01c00/classes/db/DAO.inc.php#L224-L226

**Comment by asmecher** [comment]
Merged, thanks!
