### ISSUE TITLE
[OJS] Alternate mail template for subsequent review request not selected

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#2655]
OJS 2.4 used to switch to different template for review requests depending on review round. It does not work anymore with OJS 3. Instead the same template is selected with no mention of the new version.

**Comment by ptrckb** [comment]
Similar to http://forum.pkp.sfu.ca/t/review-request-subsequent-mails-not-doing/32102

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/2656

**Comment by NateWr** [comment]
Looks like this was merged last year. Does this issue need to remain open, @asmecher?

**Comment by asmecher** [comment]
Nope -- closing.
