### ISSUE TITLE
Citation formats can't be fetched with path_info_disabled

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2657]
See https://forum.pkp.sfu.ca/t/the-requested-citation-format-could-not-be-retrieved/31384.

The problem is https://github.com/pkp/ojs/blob/ojs-3_0_2-0/templates/frontend/objects/article_details.tpl#L257, where the extra piece of the path is manually appended to the URL. URLs should only be built with the `{url ...}` Smarty function.

**Comment by NateWr** [comment]
This should be addressed by the switch to CSL in #723. Once the API is in I'll create an endpoint to deliver the citation. But in the meantime I'm using the `{url... }` smarty function and appending `&return=json` to the end of that URL, which if I understand the problem should work with `path_info_disabled`.

**Comment by asmecher** [comment]
Thanks, @NateWr -- would you mind dropping that change into the `ojs-stable-3_0_2` branch?

**Comment by NateWr** [comment]
Hmm, maybe this should be handled separately in `ojs-stable-3_0_2`, unless we want to backport the API, which doesn't seem appropriate for a stable branch.

**Comment by asmecher** [comment]
Yes, agreed -- moving the extra piece into the `{url ...}` call should be a one-liner.

**Comment by NateWr** [comment]
#723 is merged, which fixes this issue.
