### ISSUE TITLE
Filter hook

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2658]
Add a hook for Filters, so that plugins can influence/change the exported data. For example, the funders plugin should be able to add xml elements to the Crossref xml export.

**Comment by bozana** [comment]
PR:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2659

**Comment by bozana** [comment]
@asmecher, may I add this hook?

**Comment by asmecher** [comment]
Please!
