### ISSUE TITLE
{pluck_files} function called without required 'files' param

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#2662]
When trying to go to the monograph's view page, an error occurs:

{pluck_files} function called without required `files` param. Called in \omp\lib\pkp\classes\template\PKPTemplateManager.inc.php:1493 error

The view page shows 'Array' in the place where the files supposed to be. 

![untitled](https://user-images.githubusercontent.com/560456/28410114-52ee0a96-6d45-11e7-91cf-2729c98717e2.png)

**Comment by NateWr** [comment]
@defstat can you outline what files are added to your test monograph (and what galley types)? That will help us reproduce the issue when we get around to addressing it.

**Comment by defstat** [comment]
@NateWr something like that?

![untitled2](https://user-images.githubusercontent.com/560456/28410717-320cd832-6d47-11e7-8300-de10f2b2e4f1.png)

**Comment by NateWr** [comment]
That's helpful. When you upload the file, you shuold be selecting a "component type" or something like that. Can you indicate which types you've sleected for those two files?

**Comment by defstat** [comment]
If you are referring to 'submission component', the first was "Glossary" and the second is "Index"

**Comment by asmecher** [comment]
(Just FYI, I'm seeing this with our normal test data set as well.)

**Comment by NateWr** [comment]
Work was done on this in #2759
