### ISSUE TITLE
Deleting an issue where no custom issue ordering exists creates a random custom issue ordering

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2663]
See https://forum.pkp.sfu.ca/t/ojs-3-0-2-deleting-any-issue-shuffles-the-order-of-issues-in-the-archive/32263

To replicate:
* Create a number of issues without invoking custom ordering.  By default, issue publication date provides the sort.
* Delete any issue.

Expected result: issue ordering by publication date remains
Actual result: a custom issue order is created by default database seek ordering

**Comment by asmecher** [comment]
Merged -- thanks, @ctgraham!
