### ISSUE TITLE
[OMP] Lack of default plugins/gateways directory fail gateways check

### ISSUE THREAD

**Issue by ducquang92** [pkp/pkp-lib#2667]
Hi there,
I just experienced a bug in webfeed plugin which is triggered by lack of plugins/gateways directory and figured out the cause and workaround.

**Bug description**
- webfeed plugin generates RSS feed at http://journa.url/index.php/journal/gateway/plugin/WebFeedGatewayPlugin/atom
- Directly access this link on OMP will result in 302 redirection to homepage.

**Cause**
- The above link uses loadCategory('gateways') function (/pages/gateway/GatewayHandler.inc.php) to check for the existence of the plugin.
- Function loadCategory (in ./lib/pkp/classes/plugins/PluginRegistry.inc.php) will then create the variable  $categoryDir (has the value of _/plugins/gateways_ in this case). As the _gateways_ directory is not available in default OMP installation, the following check (_if (!is_dir($categoryDir)) return $plugins;_) will cause the function to end regardless of the existence of webFeed directory inside plugins/generic directory. It will fail the check and cause the error.

**Affect**
- I think all plugins placed inside directories other than _gateways_ directory that make use of gateway function like webFeed will experience this issue.

**Workaround**
- Create empty directory _plugins/gateways_ to make sure this error won't occur to generic plugins that make use of gateway function such as webFeed

**Comment by asmecher** [comment]
Thanks, @ducquang92. I've added a README document as a placeholder while there are no gateway plugins included with OMP distributions.
