### ISSUE TITLE
[OJS] CrossRef export may refer to wrong journal path

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#267]
See http://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=13440

**Comment by asmecher** [comment]
Jason, do you mind reviewing this?

**Comment by jnugent** [comment]
Alec, sure -- did you want me to wait until we have confirmation from the user testing the patch?

**Comment by asmecher** [comment]
No, we're getting towards the release of OJS 2.4.6 and I'd like to include this.
