### ISSUE TITLE
migrate crossref deposit status setting name

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2671]
the setting name for deposit status has changed in ojs 3. in ojs 2.4 it was crossref::depositStatus in ojs 3 it is crossref::status. also: crossref::depositStatusUrl changed to crossref::statusUrl.

**Comment by bozana** [comment]
PR ojs master: https://github.com/pkp/ojs/pull/1468

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR?

**Comment by asmecher** [comment]
Closing -- thanks, @bozana!
