### ISSUE TITLE
Several minor adjustments to submission lists

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2675]
This issue is a placeholder for some minor changes to the new submission lists:

- [x] Reverse author/title prominence in lists.
- [x] Search text gets overwritten while typing sometimes
- [x] Add submission ID
- [x] `SubmissionListItem` uses `this.submission` but should standardise on `this.item` for all lists.
- [x] Modals with no title have a collapsed header. To reproduce, open the activity log for a submission with no title.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2698
https://github.com/pkp/ojs/pull/1486

Tests running...

**Comment by NateWr** [comment]
@asmecher Mind code reviewing?

**Comment by asmecher** [comment]
This looks like solid evolution to me, though until I get the Vue stuff under my fingernails I'm not able to do much more than scroll and blink. I do think the magic numbers need resolving, though, per my code comment. Otherwise please go ahead!

**Comment by NateWr** [comment]
@asmecher Ok, I've spun off the constants thing to a [new issue](https://github.com/pkp/pkp-lib/issues/2708) that I'll plan to address very soon. Are you happy with [the PR](https://github.com/pkp/pkp-lib/pull/2698) getting merged?

**Comment by asmecher** [comment]
Yes, please go ahead!

**Comment by NateWr** [comment]
Merged!

(@jmacgreg the submission ID is now displayed in the lists in `master`.)

**Comment by NateWr** [comment]
Forgot to implement these changes for the catalog entry list panel in OMP.

PR:
https://github.com/pkp/omp/pull/431

**Comment by NateWr** [comment]
@asmecher one more PR to code review as part of this issue. It's pretty straightforward, just a few minor changes to the catalog list in OMP to bring it in line with the submissions list changes. Mind code-reviewing?

**Comment by asmecher** [comment]
No objections, thanks -- please go ahead!
