### ISSUE TITLE
Fix (probably) wrong wording in new API locale keys

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2678]
`locale/en_US/api.xml` has (in row 22)

`<message key="api.submissions.400.stageNotValid">Your request could not be fulfilled because the submission stage ID is compatible.</message>`

I presume this should be "not compatible" or "not valid".

(see https://github.com/pkp/pkp-lib/commit/2fa294a37614d270fbe1a08129500b8b3f954c04#diff-73ef12d7b895e7eba99b7753f8d3e837R22)

tagging @natewr, @kaschioudi

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2696
