### ISSUE TITLE
Add setting to require a journal manager to approve all new user accounts

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2681]
PKP Sprint.  Create the ability for Journal Managers / Editors to require approval of new accounts.

**Comment by NateWr** [comment]
@ctgraham I'm going to leave this open but wanted to check if you still wanted to be assigned to it.

**Comment by NateWr** [comment]
Closing this as outdated. @ctgraham feel free to reopen if you plan on finishing the work here. Otherwise, consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
