### ISSUE TITLE
User registration at the site level when email validation is enabled fails.

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2682]
When a new user registers at the site level, but config.inc.php's email section specifies require_validation, the system tries to send an email for validation.  This depends on the $context variable, which is unset at the site level.

**Comment by asmecher** [comment]
@ctgraham, this is the bug that came up at the sprint, correct? Did you tinker with it, or file and move on to the task at hand?

**Comment by ctgraham** [comment]
Yes, we just filed it here and went back to working on the sprint.  Would have been nice if I had tagged the line of code that was failing.

**Comment by asmecher** [comment]
Not a problem, thanks!

**Comment by bozana** [comment]
PR:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2811

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR?

**Comment by asmecher** [comment]
Thanks, @bozana!
