### ISSUE TITLE
[OJS2] Failed new user registration password bleeds into the login block

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2683]
Steps to reproduce:
* Configure the User Block to display
* Access the registration form with the User Block displaying the username/password fields
* Partially fill out the registration form (or add in a form error)
* Submit the registration form

Expected result:
* User Block is unaffected

Actual result:
* Password is returned in the User Block's password field

![image](https://user-images.githubusercontent.com/7001322/28925335-985552f4-7832-11e7-98bf-20891f507d34.png)

**Comment by bozana** [comment]
PRs:
ojs-dev-2_4: https://github.com/pkp/ojs/pull/1836
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1838
