### ISSUE TITLE
"Will not be peer reviewed" section flag is not used/presented

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2688]
"Will not be peer reviewed" section flag is not used/presented in the code.
(See https://forum.pkp.sfu.ca/t/will-not-be-peer-reviewed-option/32650)

**Comment by asmecher** [comment]
@NateWr and @stranack, this is one of those things that used to provide information in the About area (but was otherwise inoperative). We could consider e.g...

- Removing the option
- Restoring the presentation of the section information in the About area or when starting a submission
- Making the option disable/hide the peer review area of the workflow

**Comment by NateWr** [comment]
FYI, I think the Section Policy is also not displayed anywhere. It might be good to pull this data into the submission area.

It would be very cool for submissions in that section to simply have Submission and Published stages, and just the accept/decline buttons on the Submission stage.

**Comment by ajnyga** [comment]
`It would be very cool for submissions in that section to simply have Submission and Published stages, and just the accept/decline buttons on the Submission stage.`

I strongly second this! In many journals much of the incoming articles are one that do get peer-reviewed. However, I would think that journals do copyediting even with these ones? Even with things like book reviews the editor still wants to have a conversation with the author and possibly even asks for some revisions or even turns down a book review altogether.

**Comment by asmecher** [comment]
@ajnyga and @NateWr, I'm wary of settings that "force" workflow changes on users -- in my experience there are always exceptions, like the occasional editorial that does need a peer review. Perhaps we could use that setting to hide (by default) stages, in a way that they could be expanded and used if desired?

**Comment by asmecher** [comment]
@eddoff, I don't have a strong opinion about this, but it feels to me like the kind of concern that should be left up to a theme (or child theme).

**Comment by NateWr** [comment]
We do not show this on the frontend because it is not strictly enforced in the system. Peer review practices differ widely, even sometimes within the same journal section, even if they shouldn't, and so it is not very easy to programmatically determine whether a sufficient peer review has taken place. For this reason I am hesitant to add that information to the reader-facing site in an automated or semi-automated fashion.

**Comment by ajnyga** [comment]
In Finland we have a "Label for peer-reviewed scholarly publications"
https://www.tsv.fi/en/services/label-for-peer-reviewed-scholarly-publications

Basically a publication can apply a permission to use that label, if they are doing peer reviews according to a specific standard.

The label is stamped to each article individually. For that, I have a plugin for OJS: https://github.com/ajnyga/tsvVertu

You could see how that works and just change the part where it actually adds the label to the table of contents and the landing page. The quickest solution would just be that you replace these images with your own versions: https://github.com/ajnyga/tsvVertu/tree/master/images

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
