### ISSUE TITLE
Changing date formats in config.inc.php can lead to misparsed dates

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2689]
See https://forum.pkp.sfu.ca/t/unrealistic-reviewer-invitation-dates/32346.

Suspected cause: dates are formatted according to config.inc.php into text boxes. When they're parsed again, the changed format isn't taken into account.

**Comment by asmecher** [comment]
Alternately, this may (also) be caused by the Turkish locale. See a comment to that effect on the linked thread.

**Comment by defstat** [comment]
There is a bug in the usage of datepickers. I added the PR pkp/pkp-lib#2775.

It could make a difference to this Issue too, but I could not replicate the problem.

**Comment by asmecher** [comment]
See also https://forum.pkp.sfu.ca/t/questions-about-ojs-3-0-2/34166/22

**Comment by asmecher** [comment]
See also https://forum.pkp.sfu.ca/t/wrong-automatic-dates-for-the-review-timeline/38672 for some problem formats.

**Comment by defstat** [comment]
@asmecher right now the client-side code for the datepickers assumes that the user will use only the `date_format_short` for displaying dates (I am referring to display dates on datepickers only). 
There are some code segments that format dates on server-side before displaying them (for example https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/reviewer/form/ReviewerForm.inc.php#L173), and others that format dates on template level (for example https://github.com/pkp/ojs/blob/master/templates/controllers/grid/issues/form/issueAccessForm.tpl#L28)

I suggest a general approach on the date manipulation regarding the input: 
- If we need other date formats other than short-date to be displayed to date inputs, then I suggest adding a new FBV tag to indicate that, per datepicker field, leaving short-date format as default. 
- Maybe avoid other date formatting prior to displaying the datepicker. (let the interface get the database date, and format that as needed, automatically, taking into account the formats of the config file)

#3420 Has a fix for an "initial value datepicker issue", as it is described at https://github.com/pkp/pkp-lib/issues/3420#issuecomment-368256283.

**Comment by asmecher** [comment]
Thanks, @defstat, your proposal makes sense (as does the attached pull request). Please go ahead. So far I think our datepickers in practice only apply to `date_format_short`, and I'm not sure we'd add a second format to those, so perhaps that part can wait until it's needed.

**Comment by asmecher** [comment]
See also: https://forum.pkp.sfu.ca/t/the-important-dates-suggested-by-the-system-to-the-user-do-not-match-the-deadlines-defined-in-the-configuration/59892

**Comment by defstat** [comment]
@asmecher 

The `datetime` class is found to other `inputs` but they don't seem to take a formatted date from the server side code. 

**PR** 
[PKP-LIB]: #5760

**Comment by asmecher** [comment]
Thanks, @defstat -- merged https://github.com/pkp/pkp-lib/pull/5760 and cherry-picked to `stable-3_2_0`!
