### ISSUE TITLE
[OJS] PLN plugin adds two copies of some files to Bag

### ISSUE THREAD

**Issue by mjordan** [pkp/pkp-lib#269]
Two copies of the issue and terms XML files are being added to the Bags generated by the PLN plugin. It looks like the $termsXml element is getting saved in the bag directory, then copied into the payload/data directory, and then the original Xml file is deleted. Except that file deletion isn't happening. Then, when the directory is bagged up, both copies of the file are included. The same thing happens for the $export file. Only one copy of each file should be in the Bag, and it should be in the /data directory.

Location in code is surrounding https://github.com/pkp/ojs/blob/ojs-stable-2_4_5/plugins/generic/pln/classes/DepositPackage.inc.php#L246

**Comment by asmecher** [comment]
Merged, thanks!
