### ISSUE TITLE
[OJS] Broken HTML of index/admin/index

### ISSUE THREAD

**Issue by marcin-golebiowski** [pkp/pkp-lib#2690]
There is a broken HTML on index/admin/index page. The confirm text needs to be escaped because there are double quotes returned from json_encode.

![sceen](https://user-images.githubusercontent.com/115426/29006502-aad92fb0-7af1-11e7-8f5a-6d946fb1a903.png)

https://github.com/pkp/ojs/pull/1477

OJS version:  3.0.2.0

**Comment by asmecher** [comment]
Thanks, @marcin-golebiowski! Merged.
