### ISSUE TITLE
OAI appears to be willing to provide records before the earliest record date

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2693]
See https://forum.pkp.sfu.ca/t/oai-pmh-data-provider-validation-and-registration-error/31852 for details. Not sure if it's relevant, but the record appears to be a deleted record. (A glance at the code shows it should already account for this in calculating the earliest record date.)

**Comment by bozana** [comment]
PR:
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1481

**Comment by bozana** [comment]
@asmecher, do you think this is OK so?

**Comment by asmecher** [comment]
@bozana, this appears to have already been fixed, I just noticed -- see https://forum.pkp.sfu.ca/t/ojs2-oaipmh-and-getearliestdatestamp-ojs-2-4-8/31326/5. It didn't get an issue number before, so I'll use this one. The PR is https://github.com/pkp/pkp-lib/pull/2567 plus there's a necessary additional fix (6b83092).

**Comment by bozana** [comment]
I think this can be closed, right? -- It was cherry-picked to ojs-dev-2_4 and OJS 3 is OK...

**Comment by asmecher** [comment]
Yes, thanks!
