### ISSUE TITLE
Use journal/press thumbnail instead of logo for back-end image

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2695]
The "logo" image in the upper-left of the journals' (or press's) back-end dashboard should be the journal thumbnail, if one exists, instead of the journal logo. The logo is usually a pretty wide banner image, but the thumbnail is more usually a smaller, hopefully more square representation of the logo image, and would fit better in that space.

**Comment by NateWr** [comment]
In the default theme in OJS 3.0, the logo should be more of a square image. We've been pretty intent on discouraging banner images wherever possible.

Also, in the default theme, the journal thumbnail appears on a white background, whereas it appears on a dark background in the backend. I don't think it will slot in very well in most cases.
