### ISSUE TITLE
LazyLoadPlugin get/setEnabled do not consider site plugins

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2699]
s. https://forum.pkp.sfu.ca/t/usage-statistics-plugin-and-creating-new-journals/30841

If it is s site plugin, getEnabled and setEnabled should consider the context = 0.

This is not in conflict with the further work here https://github.com/pkp/pkp-lib/issues/1923

**Comment by bozana** [comment]
@asmecher, could you take a look at the PRs?

**Comment by asmecher** [comment]
Good catch, @bozana, I've run into this before but didn't track it down. Please go ahead.
