### ISSUE TITLE
New review round modal re-opens automatically when closed in IE11

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2703]
When the modal is closed, it immediately re-opens. My first guess is that it's a problem with the focus toggling. When a modal is closed, we return focus to the element which opened it. Maybe this focus event is activating the tab. I think that might be a "feature" of the jQuery UI tabs...

**Comment by NateWr** [comment]
I thought this would be easy just by taking the "New Review Round" button out of the tabs. Unfortunately, jQueryUI's tabs destroy any HTML not part of the tab/tab-content pairs. 

I think the least destructive hack is to detect IE11 and prevent the focus from being restored specifically for that LinkAction. So far, though, IE11 detection seems less than bullet-proof.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2711

Tests only:
https://github.com/pkp/ojs/pull/1494

I was able to reproduce this in IE9-11. Rather than try to sniff out every browser that might have an issue, I've disabled the focus restoring when it's being put back onto the New Review Round button.

This is a hacky workaround that will have negative effects for screen-readers. Restoring focus after a modal is closed is important to keep those using screen-readers oriented on the page. This workaround only effects this one interaction, and should only be needed for a ModalRequest LinkAction inside of a jQueryUI tabs component. But if/when we move away from jQueryUI tabs, we should be able to remove the workaround.

**Comment by asmecher** [comment]
Just out of interest, what would you see replacing jQueryUI tabs? They've been a very useful organizational construct in the 3.x releases and I lean on them pretty frequently.

**Comment by NateWr** [comment]
Still tabs, but I think eventually we'll probably have our own tabs as Vue.js components. It's a pretty low priority though.

**Comment by NateWr** [comment]
Tests passed. Just had to rebase to resolve a conflict. @bozana can you do the code review?

**Comment by bozana** [comment]
@NateWr, looks good :-) I've merged the pkp-lib. What about ojs -- it says tests only -- this I should not merge, right? Can this issue then be closed?

**Comment by NateWr** [comment]
Thanks! Yep! Closing! :)
