### ISSUE TITLE
New default footer images

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2705]
John and Sophy created these new images for the OJS and OMP footer, to replace the old "powered by..." ones:

https://dl.dropboxusercontent.com/u/9529729/footer-logos.zip

These are PNG files, but let me know if you need SVG.

**Comment by sssoz** [comment]
@NateWr 

Positioned in the footer, within the container, at the bottom right of the page, like this:
<img width="1133" alt="screen shot 2017-08-28 at 16 07 35" src="https://user-images.githubusercontent.com/6668406/29791474-1185b876-8c0b-11e7-8be9-70a2ce6519aa.png">

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/2754
https://github.com/pkp/ojs/pull/1514
https://github.com/pkp/omp/pull/435

@asmecher with this change, I'm not sure we're linking to `aboutThisPublishingSystem` anywhere anymore. Can you think of any other lingering links? Do we need to preserve it?

**Comment by asmecher** [comment]
@NateWr, I do think we should preserve that link ("About This Publishing System"). It contains content I can consistently google for to find installs, even if they've had the most common alterations that remove mention to PKP (e.g. the footer). It also displays the current working version, which isn't indexed thoroughly elsewhere (the PKP index isn't as comprehensive). And for journal users, it provides an informative link back to PKP that hopefully distinguishes between the journal and PKP's software.

**Comment by NateWr** [comment]
So are you saying leave the page even though there's no link to it? Or do we need to link to it? And any thoughts on how/where we do that?

**Comment by asmecher** [comment]
We should link to it. Top of mind is something in About, alternately maybe the logos/text in the footer area, but I suspect that would be too prominent and perhaps would get the axe. Two goals we want to meet (in rough order) are

1) information about OJS available to users somewhere logical (About makes sense here)
2) that page should get indexed by search engines if possible (thus linked, but not so important where)

**Comment by NateWr** [comment]
I can add an additional link, but I think it undermines the goals John and Sophy had in creating the new logo.

![about-ojs](https://user-images.githubusercontent.com/2306629/30225831-d02a7c30-94cb-11e7-8f7e-019148d50872.png)

Can I throw this back to @willinsky and @sssoz? We need to add a separate linkable component to the footer logo. Do you have ideas about how you want the new logo integrated with a second linkable component (could be an image, text, whatever)?

**Comment by willinsky** [comment]
Nate is right about our goal, and I would think that our logos should always be hyperlinked, leading to About > About this Publishing System. While my first thought was to have the logo link back to the PKP site, I realize that the About this Publishing System is still about the best landing page we have for introducing OJS and with links back to the PKP site.

**Comment by NateWr** [comment]
Ok that makes things easier. I can do that next week.

**Comment by NateWr** [comment]
PRs (tests running):
https://github.com/pkp/pkp-lib/pull/2754
https://github.com/pkp/ojs/pull/1514
https://github.com/pkp/omp/pull/435

**Comment by asmecher** [comment]
All merged -- closing, thanks!
