### ISSUE TITLE
[OJS] How to achieve Browse by Section functionality in OJS 3.0.2?

### ISSUE THREAD

**Issue by farhanabbas1983** [pkp/pkp-lib#2707]
Hello there,

Previously in ojs 2.4.x, there was a plug (Browse by sections) which worked perfectly, and it facilitated our readers a lot to get access to relevant material / section of their interest. After upgrading to ojs 3.0.2, I found out that this plug in is not any more available / functional in ojs 3.x. That is a shocker because our readers and end users are suffering alot and finding it difficult to reach to the relevant information in the shortest time possible.

On our main website, we created menus for each section to facilitate end users to access the relevant section but these urls are not working in ojs 3.x.

Therefore, I want to know whether there is a way to achieve this functionality. Can I create URLs so that when the reader clicks on a link, the specific articles in that sections open up.

Curiously waiting for the response.

Kind Regards,
Farhan Abbas
Software Engineer 
King Edward Medical University

**Comment by NateWr** [comment]
@farhanabbas1983,  I've provided some hints on how you can go about this on [your forum post](https://forum.pkp.sfu.ca/t/ojs-3-0-3-0-1-browse-plugin-doesnt-show/26145/9) (where we prefer to do questions-and-answers) and filed a dev-oriented [issue](https://github.com/pkp/pkp-lib/issues/2714) for developing a browsing by section feature.
