### ISSUE TITLE
[OJS] "force_login_ssl = On" in config does not force https on user registration pages

### ISSUE THREAD

**Issue by ingokeck** [pkp/pkp-lib#2716]
Hi all,

One of our users noticed that even though we have set the system-wide config.inc.php to enforce HTTPS for logins (which works fine for logins):

```
; Force SSL connections site-wide
force_ssl = Off

; Force SSL connections for login only
force_login_ssl = On
```

...this does not force HTTPS for the new user registration pages. This is true to the word of the description I guess; but from a security point of view it makes no sense to transport the password in the clear at registration and then enforce the encryption for later logins only. 

I would propose to have the setting force_login_ssl to also apply for all user registration pages, or anywhere else where passwords are sent to the server.

For a quick workaround I did a rewrite on apache2-level for the register pages:
```
<Directory "path_to_ojs">
    Require all granted
    # redirect user register pages to https
    RewriteEngine On
    RewriteCond %{HTTPS} =off [NC]
    RewriteCond %{REQUEST_URI} "^(.*)/register$" [NC]
    RewriteRule ^(.*)$ https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
</Directory>
```

PS: Btw, thank you for the great work you are all doing with OJS, and for publishing it under a free license! We would not have been able to setup our small publisher so quickly without it.

**Comment by ingokeck** [comment]
Just notice another strange thing, probably related: It seems that in the force_login_ssl = On setting, the login-page is https, but subsequent pages are transferred as http again, even if I as user started out intentionally with https. Is that intentional?

**Comment by t4x0n** [comment]
Hi @asmecher, I think this is OK now!  You fix this in this issue initiated by myself: https://github.com/pkp/pkp-lib/issues/3004

**Comment by asmecher** [comment]
Thanks, @t4x0n!
