### ISSUE TITLE
[OJS] Add editor/reviewer discussions

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#2717]
In OJS3 we don't have a place where an editor can have discussions with reviewers. The existing review discussion area is limited to the submission's participants, which doesn't include reviewers. This was available in OJS2 via a comments-with-reviewer thread available to editors. OJS3 editors are currently using email outside of OJS3 to maintain discussions and these are being excluded from the official submission record.

@NateWr: I think it makes sense to try to tie this feature into discussions in the same way that the Notify feature in the participants grid creates a discussion. We'll also need to add reviewers as allowed participants in discussions, but need to make sure that authors can't initiate discussions with peer reviewers. We may also want to forbid opening a discussion that includes an author and peer reviewer if the reviewer assignment is set to a blind review.

**Comment by NateWr** [comment]
Related: https://github.com/pkp/pkp-lib/issues/1257

**Comment by ajnyga** [comment]
Also related to this and #1257 is the work I will start with open reviews.

The idea is to enable reviewers and authors communicate if open review is selected. This will include adding code related to reviewer discussions, so tackling these would make sense.

I will do a more detailed issue about the plans by tomorrow and add a link here.

**Comment by asmecher** [comment]
@ajnyga, did this one get left open by accident?

**Comment by asmecher** [comment]
Thanks!
