### ISSUE TITLE
[OMP] .git directories shipped in package

### ISSUE THREAD

**Issue by bricas** [pkp/pkp-lib#272]
After downloading the latest OMP package, I noticed .git directories included under the following directories:

plugins/generic/customBlockManager/
plugins/generic/emailLogger/
plugins/generic/staticPages/

These folders are unnecessary and cause problems for people who want to track OMP independently.

Thanks.

**Comment by asmecher** [comment]
Fixed the package build script to exclude these. Thanks for reporting!
