### ISSUE TITLE
role IDs for default email templates

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2724]
The role IDs in emailTemplates.xml and DB table email_templates_default should be adapted/migrated... It seems like they are not used?

**Comment by asmecher** [comment]
@bozana, just FYI, those were purely informational -- they were used to show who the sender and recipients were in the Prepared Emails list.

**Comment by mpbraendle** [comment]
Hmm. As you see in the screenshot on https://github.com/pkp/pkp-lib/issues/2906, for most of the default templates, Sender and Receiver are set as "Subscription Manager", which is plain wrong. Neither sender nor receiver can be changed, or when a new template is added, configured.
For an editorial to set this up this might be disturbing. Either remove those columns (if not used anymore), or add an option to edit them.

**Comment by pnault** [comment]
Hi,
I'm totally with @mpbraendle on this: absence of information is better then wrong information. In 3.0.1 not all column were filled but those who were had wright information, see: https://forum.pkp.sfu.ca/t/prepared-emails-sender-recipient-has-subscription-manager/35967?u=pnault

**Comment by tothbog** [comment]
We use the latest version, 3.1.1.2, but we have the same problem. We cannot change sender, nor who is "signing" the letter. For instance, if an editor invite a new referee, the REVIEWER_REGISTER template is sent by the editor, but at the end of the letter the principal contact name appears. I tried to change it to ${editorialContactName} without success. Also, I cannot put a Dear "NAME" to the beginning, but I don't see why. 

Is there any solution to these?

**Comment by asmecher** [comment]
@tothbog, I don't think that's related to this issue, which specifically deals with the numeric `role_id`s for display in the email listing. I'd suggest posting your question on our support forum (http://forum.pkp.sfu.ca/).

**Comment by tothbog** [comment]
Ok, sorry, I did not realize that. Thanks, I will post there.

**Comment by NateWr** [comment]
This has been fixed as part of #2906.
