### ISSUE TITLE
Counter report includes hard-coded English

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#274]
See e.g. https://github.com/pkp/ojs/blob/ojs-stable-2_4_5/plugins/reports/counter/index.tpl#L26

**Comment by ctgraham** [comment]
This is resolved in dev-2_4 per https://github.com/pkp/ojs/pull/422, though it will require a round of translation.

**Comment by asmecher** [comment]
Thanks, @ctgraham. Closing this entry.
