### ISSUE TITLE
[OJS] unsecured "Share it" button 

### ISSUE THREAD

**Issue by Jirrka** [pkp/pkp-lib#2740]
If I run OJS in https mode there is small bug - pages, on which there is "Share it" button are unsecure.
It is easy to change in file classes/rt/ojs/SharingRT.inc.php

line 98

to 
**$btnUrl = (strpos(trim($btnRecord['img']), 'https://') !== 0 ? "https://s7.addthis.com/static/btn/" : "") . $btnRecord['img'];**

and everything looks to work ok.

**Comment by asmecher** [comment]
In the git repo, we've already changed this to use protocol-relative URLs. See https://github.com/pkp/ojs/commit/42690195e9b881fbcde7fec672ec5de76e833bfe for the patch. This hasn't been released in a .tar.gz package yet.
