### ISSUE TITLE
Submission list filtering doesn't work in iOS

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2746]
In Safari on iPad, clicking the Filter button in the new list panels doesn't open the filtering options. :(

**Comment by NateWr** [comment]
Turns out class names starting with two hyphens (eg - `--isVisible`) are not valid and only Safari seems to care. :)

PRs:
https://github.com/pkp/pkp-lib/pull/2748
https://github.com/pkp/ojs/pull/1511 (tests only)
https://github.com/pkp/omp/pull/434

**Comment by NateWr** [comment]
Tests passed. @asmecher would you code review? I'll rebase to fix the merge conflicts.

**Comment by asmecher** [comment]
Yup, please go ahead!
