### ISSUE TITLE
Load article-specific data when using the query builder

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2747]
This issue is split off from #2163. It's about PHP notices related to missing article columns. A PR and discussion can be found here:

https://github.com/pkp/ojs/pull/1483

But I wanted to tag it to an issue so it doesn't get forgotten. (h/t Bozana for reminding me about it. :)).

**Comment by asmecher** [comment]
Thanks, @NateWr -- I just added some new comments over on pkp/ojs#1483.

**Comment by NateWr** [comment]
Wohoo! Finally merged! Thanks for the assist(s).
