### ISSUE TITLE
Running OJS 3 upgrade script disrupts active theme

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2752]
If you run the OJS 3 database upgrade script (`php tools/upgrade.php upgrade`), the active theme gets disrupted. The frontend loads as though it can not find an active theme (no stylesheets/scripts registered or loaded).

Under Settings > Plugins, all themes appear to be disabled. Enabling the active theme there seems to fix things. As far as I can tell, in the `plugin_settings` table, running the upgrade script removes the `enabled` setting for all plugin contexts except `0`.

Update - this seems to effect other plugins as well. I had to go in and reactivate the TinyMCE plugin.

(h/t @lilients for reporting)

**Comment by bozana** [comment]
Hmmm... Maybe this is my fault, s. this change https://github.com/pkp/ojs/pull/1488/files ?
Are those site wide plugins? Hmmm... they seem not to be :-O
Hihihihi... I see -- I've forgotten to check the plugin_name, so the SQL changes all plugins... I can fix this... THANKS!!!

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1513

**Comment by bozana** [comment]
@NateWr, could you take a look at the PR?

**Comment by NateWr** [comment]
@bozana :+1: go ahead and merge when the tests pass.

**Comment by bozana** [comment]
Thanks @NateWr! Merged and closing...
