### ISSUE TITLE
DOAJ export is exporting declined articles

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2753]
Hi @bozana , just heard about this from an editor. I will post more details soon.

Scenario: an article is added to a forthcoming number and after that it is declined. Will 
https://github.com/pkp/ojs/blob/master/classes/article/PublishedArticleDAO.inc.php#L739 take that into account?

Edit: the journal had other declined articles as well, but those are not getting exported or are not even on the list. 

Edit2: the exported & declined article was assigned to an issue before it was declined. The article was used to test the system, so the scenario above is probably correct and the export function there does not seem to discard declined articles.

OJS 3.0.2.

**Comment by ajnyga** [comment]
The pr's there are for some other issue?

So maybe just add here https://github.com/pkp/ojs/blob/master/classes/article/PublishedArticleDAO.inc.php#L775

`i.published = 1 AND s.context_id = ? AND s.status != STATUS_DECLINED`?

**Comment by bozana** [comment]
@ajnyga, how were those articles declined? Were they first published and then declined? -- Because that SQL looks for articles assigned to a published issue...

**Comment by bozana** [comment]
Ah, OK, I see that also in other function in PublishedArticleDAO it is always looked after `AND s.status <> ' . STATUS_DECLINED . '` so I will do the same...

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1526

**Comment by bozana** [comment]
Merged, thus closing...

**Comment by ajnyga** [comment]
Great! I guess this was a very unlikely case where the editor has tested some functionalities with a test submission. Normally even while testing you do not attach the submission to an issue, but it seemed to be the case here.

Thanks again!

**Comment by bozana** [comment]
Thank you @ajnyga !!!
