### ISSUE TITLE
HTML galley CSS file migration

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2758]
The article CSS files are not migrated.

There is no possibility for already migrated journals to repair this automatically because the relationship between the HTML galley and the CSS file does not exist any more, thus a SQL statement will be provided for such journals to execute manually on their databases. The file migration (to the correct folder in the OJS files_dir) for such journals will probably be possible.

s. https://forum.pkp.sfu.ca/t/ojs-html-articles/32902/16

**Comment by bozana** [comment]
For journals already migrated from OJS 2.4.x to OJS 3.0.x:
1) First the DB table submission_files has to be fixed, using both databases OJS 2.4.x and OJS 3.0.x DB. Here the SQL statements, `ojs3` is the name of the used OJS 3.0.x DB and `ojs2` is the name of the used OJS 2.4.x DB:

```
UPDATE ojs3.submission_files sf, ojs3.genres g, ojs3.submissions s, ojs2.article_galleys ag SET sf.genre_id = g.genre_id WHERE g.entry_key = 'STYLE' AND g.context_id = s.context_id AND s.submission_id = sf.submission_id AND sf.file_id = ag.style_file_id

UPDATE ojs3.submission_files SET file_stage=17 WHERE file_id IN (SELECT style_file_id FROM ojs2.article_galleys)

UPDATE ojs3.submission_files sf, ojs2.article_galleys ag SET sf.assoc_type = 515, sf.assoc_id = ag.file_id WHERE sf.file_id = ag.style_file_id
```

2) Then the OJS upgrade (php tools/upgrade.php upgrade) should be run, that will execute the `Upgrade::moveCSSFiles()` function.

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1517

**Comment by bozana** [comment]
@asmecher, could you review this? -- Especially the solution for the journals already migrated to OJS 3.0.x...

**Comment by asmecher** [comment]
@bozana, I haven't tested it, but the code looks good. Go ahead, thanks -- this looks like it was a little tricky.

**Comment by bozana** [comment]
Hmmm... the genre ids are not considered here...
