### ISSUE TITLE
Galleys displayed as Array in OMP 

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2759]
![selection_075](https://user-images.githubusercontent.com/2306629/29965529-d7d81242-8f05-11e7-8a2c-3c343ab8ddbf.png)

**Comment by asmecher** [comment]
@NateWr, FYI, I think this is related and there's a proposed solution: https://forum.pkp.sfu.ca/t/omp-1-2-pdf-button-missing-array-instead/32749/12

**Comment by paflov** [comment]
And: https://github.com/pkp/pkp-lib/pull/3027

**Comment by NateWr** [comment]
Here are some PRs incorporating @paflov's fixes:

https://github.com/pkp/pkp-lib/pull/3083
https://github.com/pkp/omp/pull/474

@bozana could you code review? (Thanks again @paflov!)

**Comment by NateWr** [comment]
Merged!
