### ISSUE TITLE
Add new template hooks for plugin settings pages

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2760]
Referring to a discussion here: https://github.com/kaschioudi/ojs3-markup/issues/32#issuecomment-326542224

At the moment the only template hooks for settings pages is here:
https://github.com/pkp/ojs/blob/master/templates/management/settings/website.tpl#L30

I think there are three alternatives here:
1. Decide that plugin settings should not be added to the general settings pages at all
2. Add similar template hooks as shown above to other settings sections as well
3. Use some alternative method than template hooks (just a thought, no details)

**Comment by ajnyga** [comment]
@NateWr I don't think I have the needed permissions here to assign anyone.

**Comment by NateWr** [comment]
I'd like all the tabs to be filterable eventually. For now, for the OTS plugin, it should suffice to add a hook to the Settings > Workflow page.

**Comment by ajnyga** [comment]
Maybe do all four templates while you are at it? https://github.com/pkp/ojs/tree/master/templates/management/settings

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/2768

**Comment by NateWr** [comment]
Tests passed. @asmecher any objection to adding these?

**Comment by asmecher** [comment]
No objections, please go ahead!
