### ISSUE TITLE
world icon wonky on Keyword field

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#2762]
I have a 3.0.2 install with Spanish and English. 

The globe icon looks good on most fields, but on this one, it is a little wonky. Have a look at these two screenshots: 

![screenshot 2017-09-01 10 27 27](https://user-images.githubusercontent.com/129638/29980894-83a4977c-8f00-11e7-8f8d-b527b444589a.png)

![screenshot 2017-09-01 10 27 31](https://user-images.githubusercontent.com/129638/29980898-8589221a-8f00-11e7-8f4c-ca10fa0230e8.png)

**Comment by asmecher** [comment]
@NateWr, assigning to you in absentia and without your consent! Squawk as necessary.

**Comment by bozana** [comment]
This is fixed for the coming 3.1 release, s. https://github.com/pkp/pkp-lib/pull/2499... Thus closing...
