### ISSUE TITLE
When using multilingual inputs, it is not clear which language goes in which field

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#2763]
When using a multi-lingual input, there is no clear indication of which language goes in which form. I found this confusing on first pass. 

The assumption is that the language of the UI is on top, which is logical, but probably needs to be made explicit somehow. 

![screenshot 2017-09-01 10 27 31](https://user-images.githubusercontent.com/129638/29980943-b2abb988-8f00-11e7-8b3c-1ac7e310387d.png)

**Comment by asmecher** [comment]
Dupe of https://github.com/pkp/pkp-lib/issues/2556
