### ISSUE TITLE
Request Metadata Review button?

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2765]
Currently, the system is focused on files, but the metadata is somewhat overlooked. 

One way to make this more obvious would be to add an action button on the Copyediting stage, such as "Request Metadata Review". This button would trigger messages to the author and/or copyeditor, asking them to suggest changes to the metadata before moving to Production. The Discussion grid would be used for discussing this.

Open to other ideas!

**Comment by asmecher** [comment]
IMO this would need consideration after the versioning stuff gets merged (https://github.com/pkp/pkp-lib/issues/2072).

**Comment by NateWr** [comment]
The ability to open metadata for editing by the author has been added. If a further invitation or task is desired, I think this can be filed as a new issue.
