### ISSUE TITLE
[OJS] Installation doesn't show any error when you select the wrong database driver

### ISSUE THREAD

**Issue by jorgesumle** [pkp/pkp-lib#2766]
I was selecting MySQL instead of MySQLi and got a blank screen without any error after clicking on the install button. It would save people some time, if we warned them about the wrong driver or missing driver if possible after they hit the install button and it fails.

**Comment by asmecher** [comment]
@jorgesumle, what version of OJS were you trying to install? Was an error displayed in your PHP error log?

**Comment by jorgesumle** [comment]
I'm using the latest version from the Git repository. Here is the error log:

<pre><samp>
[Tue Sep 05 08:21:29.516653 2017] [:error] [pid 6056] [client 127.0.0.1:47858] PHP Warning:  Declaration of APIRouter::url($request, $endpoint, $params) should be compatible with PKPRouter::url($request, $newContext = NULL, $handler = NULL, $op = NULL, $path = NULL, $params = NULL, $anchor = NULL, $escape = false) in /var/www/html/pruebas/ojs/lib/pkp/classes/core/APIRouter.inc.php on line 24, referer: http://localhost/pruebas/ojs/index.php/index/install
[Tue Sep 05 08:21:29.519865 2017] [:error] [pid 6056] [client 127.0.0.1:47858] PHP Warning:  Declaration of InstallHandler::validate($request) should be compatible with PKPHandler::validate($requiredContexts = NULL, $request = NULL) in /var/www/html/pruebas/ojs/lib/pkp/pages/install/InstallHandler.inc.php on line 0, referer: http://localhost/pruebas/ojs/index.php/index/install
[Tue Sep 05 08:21:29.542241 2017] [:error] [pid 6056] [client 127.0.0.1:47858] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/pruebas/ojs/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php:456\nStack trace:\n#0 /var/www/html/pruebas/ojs/lib/pkp/lib/adodb/adodb.inc.php(558): ADODB_mysql->_connect('localhost', 'root', 'mypassword', '')\n#1 /var/www/html/pruebas/ojs/lib/pkp/classes/db/DBConnection.inc.php(144): ADOConnection->Connect('localhost', 'root', 'mypassword', NULL, false)\n#2 /var/www/html/pruebas/ojs/lib/pkp/classes/db/DBConnection.inc.php(119): DBConnection->connect()\n#3 /var/www/html/pruebas/ojs/lib/pkp/classes/db/DBConnection.inc.php(106): DBConnection->initConn()\n#4 /var/www/html/pruebas/ojs/lib/pkp/classes/db/DBConnection.inc.php(55): DBConnection->initCustomDBConnection('mysql', 'localhost', 'root', 'mypassword', NULL, false, 'utf8')\n#5 /var/www/html/pruebas/ojs/lib/pkp/classes/install/PKPInstall.inc.php(76): DBConnection->__construct('mysql', 'localhost', 'root', 'mypassword', NULL, false, 'utf8')\n#6 /var/www/html/pruebas/ojs/lib/pkp/classes/install/Installer.inc.php(178): PKP in /var/www/html/pruebas/ojs/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php on line 456, referer: http://localhost/pruebas/ojs/index.php/index/install</sampt></pre>

I was wondering if it was possible to show an error saying something like:

Fatal error: could not use functions of mysql, check if you have the driver installed. Maybe you should try MySQLi driver instead.

**Comment by NateWr** [comment]
@asmecher is it time to remove all but `mysqli` and `postgres9` from this list? https://github.com/pkp/pkp-lib/blob/main/classes/install/form/InstallForm.inc.php#L82-L95

**Comment by asmecher** [comment]
If it's OK with you I'd like to leave this until we're able to remove ADODB; at that point we can get rid of the `mysql` vs. `mysqli` distinction, strip out a bunch of compatibility code, and generally clean up this aspect, since we'll only be dealing with Laravel-based connections from that point.

**Comment by NateWr** [comment]
In that case I'll close this and let the problem sort itself out with the ADODB removal.
