### ISSUE TITLE
[OJS] CustomBlockManager-PlugIn localised

### ISSUE THREAD

**Issue by felixgruender** [pkp/pkp-lib#277]
Until now, the content of a CustomBlock can only be displayed and edited in one language. It would be good to consider a multilingual solution.

Best regards,
Felix Gründer

**Comment by asmecher** [comment]
Felix, are you interested in seeing this fixed for OJS 2.x, or OJS 3.x? I've recently removed the custom block manager plugin from the OJS repository itself, and created a separate repository for it:

https://github.com/pkp/customBlockManager

Starting with OJS 3.0 (and OMP 1.1), this is the code that'll be used. (It's a git submodule in the OJS and OMP repositories, so when the package is built for either release, the plugin is included.)

I'd say it's a low priority for us to change the custom block manager to support multilingual content for the old OJS 2.x plugin, but it would be a great addition to the new plugin.

**Comment by bozana** [comment]
The support for the multilingual content is solved in the new CustomBlockManager submodule/plug-in :-)

**Comment by asmecher** [comment]
Pull request for resolving this in OJS 2.x: https://github.com/pkp/ojs/pull/391

**Comment by asmecher** [comment]
Merged -- thanks, Felix!
