### ISSUE TITLE
[OJS] Preview shows DOIs even when they are not assigned

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2770]
Hi,

OJS3.0.2 shows DOIs for all articles even if the article has no DOI assigned. This is confusing for the editors who like to use the preview function.

**Comment by bozana** [comment]
Hmmm... Yes, I think that makes sense, now that the DOIs have to be explicit assigned... The patch is coming...

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1522
