### ISSUE TITLE
Integrate UI component library into OJS/OMP

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2771]
This is a placeholder issue for integrating the UI component library as a submodule for OJS and OMP. Once integrated, all UI components for an app should be loaded from the component library.

I'm tagging this for OJS 3.1 but it's still unclear whether it will make the cutoff.

**Comment by NateWr** [comment]
This went pretty smoothly. The UI library is now a submodule and each app's JS and CSS build is compiled based on dependencies. It also provides linting during compilation for the components.

@asmecher Do you have any idea how we might best handle testing in the future when both submodules need to be updated? Can we extend the `Submodule update ##<user>/<branch>##` to somehow indicate a branch of `ui-library` needs to be checked out?

I have some initial PRs to start working through any hiccups with the tests:
https://github.com/pkp/pkp-lib/pull/2777
https://github.com/pkp/ojs/pull/1525
https://github.com/pkp/omp/pull/439

**Comment by asmecher** [comment]
@NateWr:
> Do you have any idea how we might best handle testing in the future when both submodules need to be updated? Can we extend the Submodule update ##<user>/<branch>## to somehow indicate a branch of ui-library needs to be checked out?

Hmm, yes, and we could probably stand to extend that to submodules more generally. Everyone may well be too busy to get to this before 3.1, but please file it for sure. It may be that since that script was concocted (it's `tools/startSubmodulesTRAVIS.sh` BTW) there's something more official that's come along.

**Comment by NateWr** [comment]
I've refreshed the PRs in this issue to also include features from #2613 and #2615. That should make it easier for someone to manage the merge of all of this for 3.1 if we do a string freeze before I'm back from holiday.

These include some improvements based on user feedback on the new submission lists, including color-coded stage labels, labels for the status icons, and de-emphasising the delete button. It'd be great to get this into 3.1 but if not we can get it going early in the next cycle.

PRs:
https://github.com/pkp/pkp-lib/pull/2777
https://github.com/pkp/ojs/pull/1525
https://github.com/pkp/omp/pull/439

**Comment by asmecher** [comment]
All merged/cherry-picked, but waiting for the tests to pass on both apps before closing:

- https://travis-ci.org/pkp/ojs/builds/277096148
- https://travis-ci.org/pkp/omp/builds/277099544

**Comment by asmecher** [comment]
OJS tests are working; OMP tests are failing on another problem (Travis timeouts). Closing, thanks!

**Comment by NateWr** [comment]
wohoo! Thanks!
