### ISSUE TITLE
[OJS3.0.2] Changing journal visibility setting will restore the default language settings 

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2778]
Every time you change the journal visibility setting from Administration => Hosted journals OJS3 will restore the site language default settings.

**Comment by ajnyga** [comment]
I think that this should be conditional and should only happen when creating a new journal: https://github.com/pkp/ojs/blob/master/controllers/grid/admin/journal/form/JournalSiteSettingsForm.inc.php#L124

Or is there a reason why that would be done on every save?

**Comment by ajnyga** [comment]
Example:
The site has three languages enabled: English, German and Finnish.

I create a new journal and leave it hidden. In the language settings I only choose English.

Later, when I change the visibility settings, OJS will enable German and Finnish as well in the UI.

So nothing serious, but annoying.

**Comment by asmecher** [comment]
@ajnyga, agreed. I'll change this in a sec.
