### ISSUE TITLE
[OJS] Forward-port permissions changes for OJS 3.0

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#278]
http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8578
http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8859
http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=9022

**Comment by asmecher** [comment]
Jason, mind reviewing the two attached PRs?

**Comment by jnugent** [comment]
Will do.  Was there also a pull request for OMP?

**Comment by jnugent** [comment]
Alec, they look great.  I made a few  minor comments.  The submodule commit in the OJS pull doesn't pass Travis though.

**Comment by asmecher** [comment]
No PR for OMP yet -- I'll finish for OJS first, then adapt before merging.

**Comment by asmecher** [comment]
@jnugent, I've finally gotten around to fixing the linting problems and the last UI/UX tweaks. Mind quickly re-reviewing these?
https://github.com/pkp/pkp-lib/pull/306
https://github.com/pkp/ojs/pull/401
https://github.com/pkp/omp/pull/100

**Comment by asmecher** [comment]
Merged.
