### ISSUE TITLE
[OJS] Uploading article cover image for published articles

### ISSUE THREAD

**Issue by jorgeandr3s** [pkp/pkp-lib#2784]
Is there a way to upload an article cover image to an already published article from the back-end or in any other form?

[It doesn't look nice](http://revistas.ute.edu.ec/index.php/tsafiqui/issue/view/Tsafiqui_001) to have the cover image just in some of the articles

**Comment by asmecher** [comment]
@jorgeandr3s, could you post your question to our [support forum](http://forum.pkp.sfu.ca/) rather than this bug tracker? That's a better place for general questions.
