### ISSUE TITLE
Replace the affiliation text area with an affiliation grid

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2787]
Related to @jmacgreg suggestion here https://github.com/pkp/pkp-lib/issues/2785, I think that handling affiliation related data in OJS and OMP would benefit from a different kind of storing solution.

At the moment affiliation data is collected with a text field and people tend to write their institution names in different ways.

I suggest using a grid solution similar to the one in the Funding plugin (https://github.com/ajnyga/funding) where each affiliation would be stored as a separate data. This would enable us to search the data more easily and would also enable us to use some kind of API to suggest institutition names while users are writing down their affiliations and also store identifiers for those affiliations.

Orcid has one solution:
"Get an identifier from the ORCID Registry. Institutions added to the ORCID Registry via the provided list in the user interface have their Ringgold identifier included when accessed via the API."
https://support.orcid.org/knowledgebase/articles/276884

**Comment by jmacgreg** [comment]
Using ORCID to manage affiliations would be great! Especially if that gets us Ringgold (or, more precisely, disambiguated institutions). I believe that Crossref + ORCID + others are working on a "PIDs for Institutions" solution that will probably replace this over time. But I'm sure that that will be available via ORCID as well.

**Comment by ajnyga** [comment]
Yes, we have to plan this so that the API can change.
http://www.isni.org/content/isni-organizations-registry-identifying-organizations-scholarly-supply-chain

**Comment by ajnyga** [comment]
Also related: 
https://www.crossref.org/blog/organization-identifier-working-group-update/
https://darkarchive.wordpress.com/2017/09/26/crossref-live-london/

**Comment by ajnyga** [comment]
https://www.crossref.org/blog/org-id-a-recap-and-a-hint-of-things-to-come/

**Comment by asmecher** [comment]
Do we have confidence that any of the proposed services have enough coverage that we wouldn't be creating a problem e.g. for developing-world institutions? I worry that fixing things on a third-party controlled vocabulary would be exclusive.

**Comment by ajnyga** [comment]
I think that any solution that includes permanent identifiers like DOIs, ORCIDs and Organization ID's have to be built on the assumption that not all articles / researchers / organizations have an ID. This will never change.

But that should not stop us from building solutions based on those identifiers.
OJS should just work so that it does not assume a certain type of identifier.

When you add an Organization name + identifier pair to the database, it just has to identify the type of identifier used. If a new and better organizational identifier type comes along, you can use that as well.

The same thing should work with things like keywords. Also there it would be important that you would be able to save Keyword + identifier pairs to the database. This would enable users to add support for local thesauruses.

**Comment by asmecher** [comment]
That sounds sensible, @ajnyga. I think we'd have to make a few tricky decisions around "enforcement" of a standard to suit different use cases -- some use cases (like institution lists) need to be able to permit user-specified elements from outside the set, where other use cases will need fixed classifications. And if a fixed classification changes, orphaned may either need to be resolved or left (again, based on the use case). I can't help but wonder if there's already a good standard/toolset for this general need...

**Comment by asmecher** [comment]
What about GRID instead of Ringgold for institutions? https://gridac.freshdesk.com/support/solutions
Not sure what the respective lists' overlap is like.

**Comment by alexxxmendonca** [comment]
I never heard about those, but they deserve some attention.

We should keep in mind their coverage.

Ringgold has over 500,000 organizations while GRID has nearly 100,000. I couldn't find coverage info for ROR.

https://www.ringgold.com/identify/
https://www.grid.ac/stats

**Comment by ajnyga** [comment]
ROR has around 100 000: https://ror.org/search
They have used GRID as seed data: https://www.crossref.org/blog/ror-announces-the-first-org-id-prototype/

The good thing with ROR is probably that Crossref is actively participating in the development which could mean that some of the technical solutions are the same as you would have in DOIs, thinking of the API here.

Also ROR does seem to be more open. I easily found their API endpoint, but can not find it for Ringgold. Wondering if that is a paid service?

**Comment by ajnyga** [comment]
One option is to use a combination of core code and plugins.
In the core code we change the system so that it can save Organization name + identifier pairs to the database. Also we add a hook to the system the allows you the create for example a ROR plugin which handles the connection to the API and communicates with the core code. So if some organization id standard is better in some area, people can create their own plugins to communicate with it. We can of course add a default API to the core.

The same system would be needed in Keywords and other similar metadata fields.

**Comment by alexxxmendonca** [comment]
The openness of ROR is definitely attractive.

Yes, Ringgold is a paid service.

**Comment by NateWr** [comment]
An RoR plugin exists for those that want to use it. And I think we will judge if/when to bring support into core based on the plugin's adoption. Ongoing work can be found at https://github.com/pkp/pkp-lib/issues/6686.
