### ISSUE TITLE
Possible unnecessary variable read in the first submission form

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#2789]
In the _readInputData_ method of the _PKPSubmissionSubmitStep1Form.inc.php_ the following variables get read from the Request:

`$vars = array('authorUserGroupId', 'locale', 'copyrightNoticeAgree', 'commentsToEditor', 'copyrightNoticeAgree');`

The _copyrightNoticeAgree_ is twice in the array. Isn't it sufficient when it get's read from the request once?

**Comment by asmecher** [comment]
That's a typo, though harmless. I've removed it, thanks!
