### ISSUE TITLE
Articles remain in published state after issue is unpublished

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#2790]
When a published issue is unpublished, the articles assigned to the issue are displayed as being in the 'Published' stage in the Submissions listing rather than in the 'Production' stage.

**Comment by bozana** [comment]
@mfelczak, where/how do you see it? I am not sure it is the same for me with the current master branch...

**Comment by mfelczak** [comment]
Hey @bozana, I'm seeing it the My Assigned queue after I publish and then unpublish an issue (screenshot attached). In this example, Test Submission #2 was in the unpublished issue.

![submission_list](https://user-images.githubusercontent.com/200793/30499700-89cf1a30-9a29-11e7-8b03-69cc0ddd2194.png)

**Comment by bozana** [comment]
Strange, I couldn't see it... I'll test again...

**Comment by bozana** [comment]
Sorry @mfelczak, one more question: do you also use the master branch or something else?

**Comment by bozana** [comment]
Hmmm... I have the problem the other way around: the articles that are published appear as in "Production"... :-)

**Comment by mfelczak** [comment]
Hi @bozana, I'm using the latest on the ojs-stable-3_0_2 branch

**Comment by bozana** [comment]
PRs: 
ojs-stable-3_0_2: https://github.com/pkp/ojs/pull/1532

**Comment by bozana** [comment]
@mfelczak, would/could you maybe review/test this PR?

**Comment by bozana** [comment]
I do not know what to do with such articles (that are unpublished) for search indexing :-\ Maybe @asmecher knows?

**Comment by asmecher** [comment]
> I do not know what to do with such articles (that are unpublished) for search indexing :-\ Maybe @asmecher knows?

The article's `status` column should be a gateway for results to be presented/not presented, so the index can be a little messy, as long as a publishing action results in the index getting (re)created for the article. Beyond that, I'd rather not invest too much time in tidying up the existing search index -- I think it might be better to look at a third-party index we could integrate using our existing stack instead.
