### ISSUE TITLE
Fix formatting of reviewer comments when imported from review form textbox into author email

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2791]
See https://forum.pkp.sfu.ca/t/ojs-3-0-2-review-form-extended-text-box-problem/33230/7 for details.

I suggest 2 recommendations:
- [x] Expedient bug-fix without DB implications: Have the text box contents HTMLified when importing into the email compose window. This would resolve the immediate issue for the stable branch.
- [ ] Better long-term fix, but requiring database intervention: Support a rich text box for that field type, and convert existing responses into HTML in the database.

**Comment by asmecher** [comment]
To fix the immediate layout problem in OJS 3.0.2, apply https://github.com/pkp/pkp-lib/commit/84d40958546b5f28993bb7a527f7d07820b8d74a in `lib/pkp`.

**Comment by NateWr** [comment]
Closing this in favor of a long-term fix that adopts fields from the UI Library for the review form: https://github.com/pkp/pkp-lib/issues/3971
