### ISSUE TITLE
Upload Revision canceled but still in revision list

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#2794]
We use OJS master for development. I think the bug is the same in 3.0.2
When an author wants to upload a file for revisions, after he choose the file in first Tab "1. Upload File" if he cancel, the uploaded file is in the revisions grid (after refresh), whether he chooses an existing version or new file.

**Comment by asmecher** [comment]
@forgive38, have you checked your PHP error log for details? Can you confirm whether this is also an issue in 3.0.2?

**Comment by forgive38** [comment]
I confirm this issue for 3.0.2 and no error in my log file

**Comment by forgive38** [comment]
somebody else got same issue ?

**Comment by asmecher** [comment]
No, I haven't encountered it -- assigning to OJS 3.1.1 for investigation, but we'll probably need some more information before we can replicate/diagnose this locally.

**Comment by forgive38** [comment]
There is another bug : with this file upload wizard, when in "1. Upload File" you choose a file or drag&drop one, you have the possibility to change the file.
But as the file is already upload and saved, even if you change the file, the first is in the database as the second one you uploaded.
This is true when you don't upload a revision of an existent file.

**Comment by forgive38** [comment]
this issue seems to be due to a lack of csrftoken when deletefile is called.

**Comment by asmecher** [comment]
PRs to add CSRF tokens:

- https://github.com/pkp/pkp-lib/pull/2939
- https://github.com/pkp/ojs/pull/1631

@NateWr, could you review these?

**Comment by forgive38** [comment]
Thank you for this patch.
I think there is same issue when, in first tab "1. Upload File" you want to change a file already uploaded.

https://github.com/asmecher/pkp-lib/blob/630b9f113515f78f2c937f7b1cb580dea164eaed/js/controllers/wizard/fileUpload/FileUploadWizardHandler.js#L324

**Comment by forgive38** [comment]
And what do you think about delete the uploaded file when you close the fileuploadWizard modal before the last step ?

**Comment by NateWr** [comment]
:+1:

**Comment by asmecher** [comment]
Forward-ported https://github.com/pkp/pkp-lib/pull/2939 to `master`. (The OJS pull is just a submodule update and JS minification update.)

**Comment by NateWr** [comment]
Can this be closed?

**Comment by asmecher** [comment]
No, I still have a couple other cases to review.

**Comment by asmecher** [comment]
^ The above commits (https://github.com/pkp/pkp-lib/commit/a157ffd9614cc6bedee42bc993d8a578d964164d for `lib/pkp` and https://github.com/pkp/ojs/commit/21321fd27f6ccfacb1fb992bf025793246cc99e8 to update the minified JS in the base directory) correct the file replacement case mentioned in https://github.com/pkp/pkp-lib/issues/2794#issuecomment-339245617 for `ojs-stable-3_1_0`. Also forward-ported to `master`.

**Comment by asmecher** [comment]
The final case pointed out in this issue (https://github.com/pkp/pkp-lib/issues/2794#issuecomment-339248509) is not as quick to fix.

Filed separately: https://github.com/pkp/pkp-lib/issues/2974

Otherwise, all committed to `master` and `ojs-stable-3_1_0`.
