### ISSUE TITLE
Skip verbs in restful URI for articles

### ISSUE THREAD

**Issue by peterk** [pkp/pkp-lib#2798]
Currently the URI scheme seems to include the verb "view" in the identifier for an article like

`http://journals.sfu.ca/testdrive3/index.php/journal/article/view/1`

URI design typically omits verbs from the identifier (as the requested action is communicated in the HTTP protocol request). It would be great to get rid of the "view"-part for the articles as it would shorten links and would make it easier to be consistent in API design and data exports.

**Comment by asmecher** [comment]
@peterk, you're correct, but the current design is a long legacy of OJS dating back over a decade. We could change it and add redirects for existing URLs, but I'm not sure it's worth the investment of time. We do have a REST API for release in OJS 3.1, and the URLs there are designed with better alignment to current standards.

**Comment by NateWr** [comment]
This is a perfectly sensible recommendation. But as Alec said we are tied with our current routing system. We will change this some day, but it will likely be a 4.0 kind of application rebuild. I'm going to close this issue as out-of-scope for now.
