### ISSUE TITLE
[OJS] Problem when deleting a CustomBlock

### ISSUE THREAD

**Issue by felixgruender** [pkp/pkp-lib#280]
Deleting a CustomBlock (in: System Plugins > Custom Block Manager) doesn't seem to work properly: the related entries still remain in the database.
Apparently there's a little bug in plugins/generic/customBlockManager/SettingsForm.inc.php (function execute())

Best regards,
Felix

**Comment by asmecher** [comment]
Merged -- thanks, Felix!
