### ISSUE TITLE
It seems that old bug returned

### ISSUE THREAD

**Issue by slavash2305** [pkp/pkp-lib#2800]
It seems that [this bug  (Bug 8977)](https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8977#c1) returned.

We have received already the second letter as below (must be in Russian, but we have Ukrainian):
OJS ver. 2.4.3.0

>> Система Open Journal Systems помітила незвичайну активність у функціонуванні модуля платежів PayPal журналу Russian Journal of Herpetology.
> Може знадобитись подальше вивчення цього питання або ручне втручання.
>                        
> Цей лист створений модулем PayPal системи Open Journal Systems.
> 
> Повна інформація про запит:
> Array
> (
>     [transaction_subject] => 
>     [payment_date] => 14:25:22 Sep 14, 2017 PDT
>     [txn_type] => web_accept
>     [last_name] => ***
>     [residence_country] => ***
>     [item_name] => ***
>     [payment_gross] => ***
>     [mc_currency] => ***
>     [business] => ***
>     [payment_type] => instant
>     [protection_eligibility] => Eligible
>     [verify_sign] =>
> AfGhdiwjldC.sOZ9YP.akedLASMGAk.Vo95EGWOuMES.lBWkqOWz9.9C
>     [payer_status] => verified
>     [payer_email] => ***
>     [txn_id] => 6KN77172KT014464Y
>     [quantity] => 1
>     [receiver_email] => ***
>     [first_name] => ***
>     [payer_id] => ***
>     [receiver_id] => ***
>     [item_number] => 43
>     [payment_status] => Completed
>     [payment_fee] => ***
>     [mc_fee] => ***
>     [mc_gross] => ***
>     [custom] => ***
>     [charset] => UTF-8
>     [notify_version] => 3.8
>     [ipn_track_id] => ***
> )
> 
> 
> Додаткова інформація (якщо наявна):
> Confirmation return: 
> CURL error: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
> 
> Дані сервера:
> Array
> (
>     [CONTENT_LENGTH] => 757
>     [CONTENT_TYPE] => application/x-www-form-urlencoded
>     [DOCUMENT_ROOT] => ***/folium/folium.ru/www/rjh/
>     [GECOS] => folium.ru
>     [HOME] => ***/folium
>     [HTTP_ACCEPT] => */*
>     [HTTP_CONNECTION] => close
>     [HTTP_CORRELATION_ID] => cf50332f3778f
>     [HTTP_HOST] => rjh.folium.ru
>     [HTTP_USER_AGENT] => PayPal IPN ( https://www.paypal.com/ipn )
>     [HTTP_X_ACCEL_HOST] => ***
>     [HTTP_X_ACCEL_IP] => 173.0.81.1
>     [HTTP_X_ACLR_INTERNAL] => /ZACLR
>     [HTTP_X_FORWARDED_FOR_ORIG] => ***
>     [LD_PRELOAD] => /usr/lib/libthr.so:/usr/local/lib/libpwd_dbenv.so
>     [PATH] => /usr/bin:/bin
>     [PERLLIB] => ***/folium/perllib
>     [PROF_SRV] => 1
>     [REMOTE_ADDR] => 173.0.81.1
>     [REMOTE_PORT] => 0
>     [SCRIPT_FILENAME] => ***/folium/folium.ru/www/rjh/index.php
>     [SERVER_ADDR] => 62.113.86.15
>     [SERVER_ADMIN] => ***
>     [SERVER_NAME] => ***
>     [SERVER_PORT] => 2067
>     [SERVER_SIGNATURE] => 
>     [SERVER_SOFTWARE] => Apache/1.3.37 (Unix) PHP/5.3.29 mod_perl/1.31
>     [SHELL] => /usr/local/sbin/rtsh
>     [UNIQUE_ID] => ***
>     [USER] => ***
>     [GATEWAY_INTERFACE] => CGI/1.1
>     [SERVER_PROTOCOL] => HTTP/1.0
>     [REQUEST_METHOD] => POST
>     [QUERY_STRING] => 
>     [REQUEST_URI] => /index.php/rjh/payment/plugin/Paypal/ipn
>     [SCRIPT_NAME] => /index.php
>     [PATH_INFO] => /rjh/payment/plugin/Paypal/ipn
>     [PATH_TRANSLATED] =>***/rjh/rjh/payment/plugin/Paypal/ipn
>     [PHP_SELF] => /index.php/rjh/payment/plugin/Paypal/ipn
>     [REQUEST_TIME] => 1505424330
>     [argv] => Array
>         (
>         )
> 
>     [argc] => 0
> )

The payment has not been completed. It's status remained "Awaiting Online Payment".

We will greatly appreciate any ideas. Any questions are welcome! We try to answer all.

**Comment by asmecher** [comment]
I see that you've also posted this on [the support forum](https://forum.pkp.sfu.ca/t/it-seems-that-the-resolved-earlier-bug-returned/33809). Please just post in one venue -- otherwise it could duplicate effort. I'll follow up over there.
