### ISSUE TITLE
Add opt-out settings for issue publish and announcements notifications

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2805]
A remnant from https://github.com/pkp/pkp-lib/issues/2561:

> add profile settings to disable/enable the two notification types (AND add unsubscribe link to the notification emails which enables the user to disable the type of notification with one click, this could be added later on, but it would fit the overall design there very well)

**Comment by ajnyga** [comment]
There is already an unsubscribe mentioned here: https://github.com/pkp/pkp-lib/blob/master/classes/notification/PKPNotificationOperationManager.inc.php#L298
But it is maybe not visible in the message template and not sure what it does exactly.

What the unsubscribe links should do, in my opinion, is toggle the settings in the profile=>notifications page. I have a feeling that the link above is/was meant to disable notifications alltogether?

**Comment by ajnyga** [comment]
Just to carry some of the discussion from the original thread here, I still think it would make sense limiting "public notifications", namely "new issue" and "announcements" (maybe others) to one tool.

This could be built using the current Announcements tool, and it would have:
- title field
- pull down menu for prefilling the notification content (see related https://github.com/pkp/pkp-lib/issues/3646)
- free text field
- checkbox to choose whether the notification/annoucement is shown on webpage or only sent by email
- checkboxes for choosing which roles receive the notification

This would give journals more control and a tool that has been asked many times on the forum.

You could also have the ability to opt-out of these notifications based on context.

**Comment by NateWr** [comment]
After some discussion in #3575, I'm going to work on the opt-in/out options in the user profile settings for 3.1.1-1. The unsubscribe link will remain for 3.2.

**Comment by NateWr** [comment]
This was completed as part of work in #3575.
