### ISSUE TITLE
wrong notification URL in ReviewRoundNotificationManager

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2806]
s. https://forum.pkp.sfu.ca/t/notification-to-series-editor-contains-link-for-reviewer-in-omp/32261

A fix for the current OMP stable version (omp-stable-3_1_0) should be provided...

**Comment by bozana** [comment]
PR:
pkp-lib omp-stable-3_1_0: https://github.com/pkp/pkp-lib/pull/2807

**Comment by bozana** [comment]
@NateWr, could you take a look at this PR?

**Comment by NateWr** [comment]
:+1: Looks good! Merge whenever you'd like.
