### ISSUE TITLE
Spinner/grid in modal presentation

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2815]
I'm seeing a recent UI sizing glitch when grids are presented inside modals:

![image](https://user-images.githubusercontent.com/200411/30834606-bcda0b2e-a208-11e7-920a-6b50a468287b.png)

![image](https://user-images.githubusercontent.com/200411/30834599-b1e53108-a208-11e7-8047-0d79d1d434c2.png)

These are in the "Assign Reviewer"  modal, but I think it probably presents more generally.

**Comment by asmecher** [comment]
@NateWr, are you able to prioritize this one? @stranack would like to take some screenshots for documentation updates.

**Comment by NateWr** [comment]
Yeah will do. But I think it should only occur on tables with long text that doesn't wrap like the screenshot above.

**Comment by ajnyga** [comment]
@NateWr will those changes work with 3.0.2 or should I have a working installation using the current master branch?

**Comment by NateWr** [comment]
@ajnyga You might be able to just apply the change to `3.0.2`.

**Comment by ajnyga** [comment]
With OS X + Chrome and OS X + Safari, no scrollbar is visible. 
It appears if you use two fingers to scroll the div vertically. But you have to know you can do that.

The problem with this solution is that relevant information is hidden (what component).

Why not use overflow-wrap? https://css-tricks.com/almanac/properties/o/overflow-wrap/ http://caniuse.com/#feat=wordwrap

**Comment by NateWr** [comment]
I wrote out a big long thing about how `word-wrap` doesn't work with the table cells in our grids for some reason and it's caused me no end of grief and I couldn't wait to move away from tables in the grids and then I found out about `table-layout: fixed`, which seems to make this possible! I will have to do some testing but I'm hopeful. :)

**Comment by ajnyga** [comment]
Maybe render the rows so that the file component name is under the filename - not after it?

This way no data will be hidden in the overflow and at least I do not see no harm that a longer name is not so apparently visible with OS X.

**Comment by NateWr** [comment]
> Maybe render the rows so that the file component name is under the filename - not after it?

I'd love to do this, but I would have to refactor how grid rows/cells work, and that would have a huge impact on every grid in our app. It would be a nightmare to test.

I went down a pretty deep rabbit hole yesterday. `table-layout: fixed` does allow us to use `word-wrap`. However, it has some knock-on effects with table columns.

![grid-fixed-tears](https://user-images.githubusercontent.com/2306629/31270412-310b4762-aa7c-11e7-8bcc-13c5c8976f48.png)

I was able to get around this by refactoring away the indent columns we used to use, and setting a fixed (`em`) width on the selection columns.

This leaves us with a bunch of grids here and there with columns that are too small for the column labels:

![grid-fix-tears-6](https://user-images.githubusercontent.com/2306629/31270509-96eecf22-aa7c-11e7-97e3-148862c0c59c.png)

This isn't critical, but it will be very hard to discover all of the grids we need to change. Grids are hidden all over the system. It's also a problem that will crop up with translations all the time (when the "Replies" and "Closed" strings are longer than in English).

It kind of feels like we'd be swapping one edge-case visual glitch for a bunch of more common visual glitches. I'm not opposed to the change -- we should probably be using `table-layout: fixed` and we clean up some unused code in the grids. But I wonder if it would be better to make a change like this at the beginning of a version cycle so we can get more eyes hunting out and fixing the grids with columns that are too narrow before a release.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2836

**Comment by ajnyga** [comment]
This came to mind, although you probably already tried it: https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

**Comment by NateWr** [comment]
`text-overflow: ellipsis` has the same width limitations as `word-wrap`.

**Comment by NateWr** [comment]
Deferring this pending further discussion about the pros and cons.

**Comment by NateWr** [comment]
I'm tempted to never fix this and instead just keep migrating grids over to ListPanels. Objections?

**Comment by NateWr** [comment]
Closing as obsolete.
