### ISSUE TITLE
Publication date cannot be set via UI

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2816]
See https://forum.pkp.sfu.ca/t/editing-publication-date-on-omp/33904.

Some templates, e.g. `templates/frontend/objects/monograph_summary.tpl`, use `$publishedSubmission->getDatePublished`, which gets a date that is stamped upon publication but can't be otherwise set via the UI.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/omp/pull/487

@bozana can you code review?

**Comment by bozana** [comment]
@NateWr, very nice! Just two minor comments/questions...

**Comment by NateWr** [comment]
Merged!
