### ISSUE TITLE
Safari 11.0 does not display submission list in the current branch of OJS 3.1

### ISSUE THREAD

**Issue by crosfield** [pkp/pkp-lib#2825]
<img width="1699" alt="screen shot 2017-09-29 at 00 42 29" src="https://user-images.githubusercontent.com/8432203/30991853-926b5c04-a4af-11e7-867e-4f700e1b0a7d.png">

**Comment by asmecher** [comment]
@crosfield, does anything appear in the browser console?

@NateWr, mind taking a look?

**Comment by NateWr** [comment]
I'm updating my iPad to see if I can test on Safari 11. @crosfield can you try running `npm install` and `npm build` again? There were some very recent browser compatibility fixes that went in that changed the package dependencies.

**Comment by crosfield** [comment]
It's strange. Today after 'git submodule update --recursive' submission list is fine displayed! I don't know what it was. And I didn't do npm install & npm build
