### ISSUE TITLE
Article covers named server-side without article ID

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2827]
See https://forum.pkp.sfu.ca/t/ojs-2-4-8-cant-import-article-covers/33977 for details.

The cause is that [this LoC](https://github.com/pkp/ojs/blob/ojs-2_4_8-0/plugins/importexport/native/NativeImportDom.inc.php#L400) uses `$article->getId()`, but in the [import process](https://github.com/pkp/ojs/blob/ojs-2_4_8-0/plugins/importexport/native/NativeImportDom.inc.php#L794), that hasn't been set yet by the [insertObject call](https://github.com/pkp/ojs/blob/ojs-2_4_8-0/plugins/importexport/native/NativeImportDom.inc.php#L803).

Solution: Move the `handleArticleCoverNode` calls below the `insertArticle` call; a `$articleDao->updateArticle` call will probably be necessary in turn below that to completely persist all the necessary data.

**Comment by mittinatten** [comment]
I can confirm that these changes solved our problem. If it helps I can make a PR.

Thanks!

**Comment by asmecher** [comment]
Thanks -- please do!

**Comment by mittinatten** [comment]
Submitted #1557

**Comment by asmecher** [comment]
Thanks, @mittinatten -- merged and cherry-picked over to `ojs-dev-2_4` as well.
