### ISSUE TITLE
remove citationFormats plugins

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2832]
a) from the plugins folder (pkp/ojs#1556)
b)  in code (pkp/ojs#1555, https://github.com/pkp/ojs/pull/1568)
c) from DB table versions i.e. consider it in the update script (https://github.com/pkp/ojs/pull/1568)

**Comment by bozana** [comment]
This code part is making a problem, PHP error or warning:
https://github.com/pkp/ojs/blob/master/pages/article/ArticleHandler.inc.php#L164
https://github.com/pkp/ojs/blob/master/api/v1/submissions/SubmissionHandler.inc.php#L299
Thus it should be removed.

@NateWr, is this index used: https://github.com/pkp/ojs/blob/master/api/v1/submissions/SubmissionHandler.inc.php#L346? -- It uses the old citationFormats plugins. Should there the new CSL be considered?

**Comment by bozana** [comment]
PRs:
ojs master:
https://github.com/pkp/ojs/pull/1555

**Comment by NateWr** [comment]
Oh, good catch @bozana! Merged.

Leaving open for the db stuff in the upgrade scripts, yeah?

**Comment by NateWr** [comment]
My brain was melting for a second there. I knew I removed all of the plugins, so why are they still there?!?! Now I see the citationFormat plugins have a single locale file in them, created with this commit:

https://github.com/pkp/ojs/commit/ef82134bccba95c2e8786d36849a13f5384ff825

Here's a PR that removes them:
https://github.com/pkp/ojs/pull/1556

**Comment by bozana** [comment]
@NateWr, yes I will add a delete SQL statement in the upgrade script. 
Do you know what to do with citations in SubmissionHandler (s. second entry above)?

**Comment by NateWr** [comment]
It can be removed for now. Kassim is trying a new approach for populating API data so in theory the plugin should be responsible for adding the data.

**Comment by bozana** [comment]
@NateWr, could you take a look at this PR: https://github.com/pkp/ojs/pull/1568 ? Thanks!!!

**Comment by bozana** [comment]
Everything merged thus closing...
