### ISSUE TITLE
Revert change in locale/pt_BR/editor.xml

### ISSUE THREAD

**Issue by leofontenelle** [pkp/pkp-lib#2840]
Making a diff between the current version of `locale/pt_BR/editor.xml` and the one on my OJS 3.0.2 installation, I see this new version lacks a translation for the message `editor.publicIdentificationExistsForTheSameType`. However, this message is not obsolete, being found at `controllers/tab/pubIds/form/PKPPublicIdentifiersForm.inc.php`. Please revert this change in the translation, putting back this translation: `<message key="editor.publicIdentificationExistsForTheSameType">O identificador público '{$publicIdentifier}' já existe para outro objeto do mesmo tipo. Por favor, escolha identificadores únicos para os objetos do mesmo tipo dentro de sua revista.</message>`

Thanks!

**Comment by mtub** [comment]
Hi @leofontenelle ,

the key has been removed to the application repos. It is still present, you can find it in the OJS editor.xml file: https://github.com/pkp/ojs/blob/master/locale/pt_BR/editor.xml#L230
