### ISSUE TITLE
Remove excluded plugins from git stable branch

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#2843]
The Related Items block is installed with OJS 3.x but it relies on the old Reading Tools framework which hasn't been ported to OJS 3.x 

We should remove the block plugin from the OJS 3.x release as it causes some confusion for users when it doesn't work/isn't displayed.

**Comment by asmecher** [comment]
That plugin is currently excluded from the build process, but will be present for anyone installing from github. There are lots of other plugins in the same situation.

Vague idea: maybe these should be outright removed from the stable branches when they're created?

**Comment by asmecher** [comment]
This should be done for all plugins listed in the build tool's exclude list.

**Comment by asmecher** [comment]
Done for Related Items and Lucene plugins. I've left the rest present, at least for now.
