### ISSUE TITLE
Encode public-facing email addresses to prevent spam harvesting

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2844]
https://www.smarty.net/docsv2/en/language.function.mailto.tpl

**Comment by ajnyga** [comment]
Hi @asmecher https://github.com/pkp/pkp-lib/pull/2845

I started to think if there are accessibility issues with this solution, @NateWr?

It now uses javascript eval, the other option would be to use hex. I do not know whether one or the other is better (I think I've heard that javascript is more effective, but do not know how accessible it is?)

**Comment by NateWr** [comment]
Author email addresses may be displayed too. If they're not now, I think we've had a request for them to be.

**Comment by ajnyga** [comment]
Hi @NateWr. Do you think that it would be a good solution in general to use javascript for protecting emails this way, I mean the accessibility issue with special browsers for visual impairment etc.? I do not have much knowledge on how they work in these cases.

Regarding the author emails, there is one problem here. At the moment author email is obligatory. However, in many cases you have very old articles in the system for authors who do not have an email and for these authors many journals have filled "fake" emails. Changing the system to show emails there, would make all these fake emails visible in old articles. However, how about showing emails for users with ORCID?

**Comment by NateWr** [comment]
I'm sceptical of how good obfuscation works in general, but I don't really know about accessibility issues related to this or anything. I think JavaScript is supported by many screen readers these days though I know they're expensive so some people are still on really old ones.

My previous reaction of "that's insane why are we publishing email addresses on a publicly-accessible website" were met with pretty strong support for email addresses in academic culture. So :man_shrugging:. I guess we can try to obfuscate and see if anyone complains.

**Comment by ajnyga** [comment]
Me too, especially things like mail(at)dot.com, which is what you usually see. I mean, if the browser can show the actual email then why not a harvesting bot. But, I have seen people say that those bots are usually overly simple. 

Maybe we can just think of this as digital placebo XD

Regarding email addresses in article pages, I do not recall anybody from our editors asking about those. At the moment they are not shown. So I am fine with leaving those out in the first place.

**Comment by asmecher** [comment]
"digital placebo" -- yes, I think this is not unlikely.

**Comment by NateWr** [comment]
Closing this due to lack of interest.
