### ISSUE TITLE
Four duplicate keys in locale/manager.xml

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2848]
Hi @mtub ,

While updating the Finnish translation, I noticed this: https://github.com/pkp/ojs/blob/master/locale/en_US/manager.xml#L383-L386

**Comment by mtub** [comment]
@asmecher, you've put the new strings in there, but right now they don't display data on when to notify users subscribing to the content. Is this intentional?

**Comment by asmecher** [comment]
Those are holdovers from OJS 2.x, IIRC, and are implemented in `classes/tasks/SubscriptionExpiryReminder.inc.php`. I'm not sure I'll have time to dust this off and test it in time for the 3.1 release, but will try.

**Comment by asmecher** [comment]
@ajnyga, I'm pretty sure the line numbers have shifted since this was filed; can you describe what you saw in a little more detail? This may already be obsoleted by recent releases.

**Comment by ajnyga** [comment]
hmm, a poorly written ticket description.

But probably I saw this: https://github.com/pkp/ojs/blob/master/locale/en_US/manager.xml#L379-L382

Those four keys have an identical label.

**Comment by asmecher** [comment]
That's this set of fields in the subscription policy form:
![ss](https://user-images.githubusercontent.com/200411/58830636-9dac9a00-85ff-11e9-8ff4-284e73b6ec77.png)
As you can see, the labels are redundant, but the dropdowns provide context. So perhaps not the most intuitive distinction, but not a bug strictly speaking. We could add "x months" or "x weeks" to the English-language text, I suppose?
