### ISSUE TITLE
Galley Public Identifiers

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#285]
Change the check of the uniqueness of the galley public identifiers, s. http://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=4484#p51104 and http://pkp.sfu.ca/support/forum/viewtopic.php?f=2&t=10171.
Because of that, remove also the "custom identifier" suffix option in the DOI and URN plug-in and use the custom pattern %x instead.

**Comment by asmecher** [comment]
Thanks, Bozana!
