### ISSUE TITLE
[OJS] Changed code of plugins/blocks/navigation/block.tpl disabled Lucene Autocomplete

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#2856]
OJS 2.4.8.2:  Lucene autocomplete does not work anymore since the code in https://github.com/pkp/ojs/blob/b4219970b5a958cdf1ddb9898d094223b143608d/plugins/blocks/navigation/block.tpl#L15-L20

has been added.

The problem might be in https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/lucene/templates/filterInput.tpl

**Comment by bozana** [comment]
@mpbraendle, hmmm... I am using the latest ojs-stable-2_4_8 branch and I cannot reproduce it -- the auto-suggest feature is working for me. Could it maybe be something else in your installation?

**Comment by mpbraendle** [comment]
Did both, to no avail.

Example:
http://sui-generis.ch/search  works with autocomplete (central search box)

But the search box in the right navigation bar of the same page does not.
You may figure out the difference between the two using Web inspector.
In the right box, the parameter searchField is missing in the "sourceUrl" of the javascript function above the form.

**Comment by bozana** [comment]
@mpbraendle, hmmm... I think that is OK i.e. I think it was always like this. Or do you know the small search input filed supported once auto-suggest?

**Comment by bozana** [comment]
Ah, I found the bug -- the form id was "simplesearchForm" instead of "simpleSearchForm" :-P Such a small typo can affect so much... ;-)
The fix/path is coming...

**Comment by bozana** [comment]
PRs:
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1572

**Comment by bozana** [comment]
@mpbraendle, could you maybe also test the fix/change?
I'll then merge and cherry-pick it to ojs-dev-2_4...
Thanks a lot!!!

**Comment by mpbraendle** [comment]
Thank you @bozana, fix tested both on test and production system, works! You can merge.
