### ISSUE TITLE
[OJS] issue with user_id and query table in Pre-Review Discussions

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#2857]
Hi, 
I found an issue in the Pre-Review Discussions, we made some proofs before start to receive submissions officially, at this moment, of course, we made some discussions and other things for try OJS. Now, we have this issue in which we think that a discussion not was deleted and appear now in another submission, but I review the database and this is the problem:

Submission_ID is the 29
Query_ID is the 6  
User for proofs ID is 6  (but not have query in database, see image)
Real User have ID 16  (his query is the 6)
Review in this submission have ID 26 

I think OJS is not reading all number of user_ID in Discussion, and just read 6 instead of 16 or something like that! Here is the query table:
![query](https://user-images.githubusercontent.com/5422984/31406054-5d5fc59c-add6-11e7-9fca-679055cf0c7c.png)

and here how we see this issue in the OJS:
![screen1](https://user-images.githubusercontent.com/5422984/31406180-cfd2226e-add6-11e7-9c11-99aa5b1e8690.png)
![screen2](https://user-images.githubusercontent.com/5422984/31406181-d352e342-add6-11e7-8a9d-818a1d4f68f4.png)

**Comment by asmecher** [comment]
@t4x0n, I can't reproduce this locally, but I think it's not likely that OJS is breaking a user ID of 16 up into 6 somehow -- I can't think of any string operation that happens on an ID that might do this. See if you can reproduce the behavior and describe it in steps that we might be able to reproduce here.

**Comment by t4x0n** [comment]
@asmecher, I am installing OJS for another journal on the same server, I will try to reproduce this behavior step by step... this behavior really is very weird!
