### ISSUE TITLE
remove citationOutput plugins

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2859]
s. https://github.com/pkp/ojs/pull/1568
check what everything can be safely removed

**Comment by bozana** [comment]
Maybe a few notes here, and to double check i.e. be 100% sure:
The citationOutput plugins were something different then citationFormats plugins: citationFormats were used for article citation and citationOutput for the conversion of article references into a required format. Thus, depending on what are we planing to do with submission reference list, we may re-use these plugins, or instead we maybe can use the new CSL plugin for that as well.
This plugins expect a reference to be in the NLM format. 
The conversion from the raw reference to the NLM format was done by citationLookup and citationParser plugin, both being used in so called Citation Assistant. The Citation Assistant and this kind of parsing and lookup is not used any more and if I understand correctly probably not in the future, right? If so can those also be removed? What are the plans for reference list parsing in OTS (@axfelix and/or @kaschioudi)? Will they be available in the same NLM format? If so, maybe to think of/see if these citatinOutput plugins should be kept? On the other side, the citationOutput plugins seem to be so complex and the code spread, that it would be maybe better to implement something anew, if needed?
The citationOutput plugins are part of the nlm30 metadata plugin (s. https://github.com/pkp/pkp-lib/blob/master/plugins/metadata/nlm30/PKPNlm30MetadataPlugin.inc.php#L52 and https://github.com/pkp/pkp-lib/blob/master/plugins/metadata/nlm30/PKPNlm30MetadataPlugin.inc.php#L60-L63). The  metadata plugins (at least DC) are still used in different places in the code (e.g. via OAI, but also in the new API), for the article metadata conversion into the different formats. Thus, I am afraid we can not remove the nlm30 metadata plugin completely yet, thus I will try to only figure out what parts we could remove.
This all is so confusing because the code is so complex and linked at 10000000.... places ;-)
So any thought/tip/idea would surely be very helpful and very welcome! :-)

@ctgraham, you are/were using the Citation Assistant, or? -- somehow I have this in my mind :-) If so, would it be maybe possible for you to send me an example of those DB tables relevant to it i.e. to that citations/references storage? Also, how are you using those references and different formats exactly? If you do not use it: sorry, just forget it! :-)

**Comment by ctgraham** [comment]
I don't think any of our journals are using the Citation Markup Assistant.  Our interest was primarily in fixes to the reference processing for users who are copy-and-pasting a bibliography to form references.  (c.f. https://github.com/pkp/pkp-lib/issues/2570).

In our data, we had folks pasting the reference list as instructed in 2.x, without the Citation Assistant, and ending up with very unexpected results.

This whole workflow is gone in 3.x, correct?

**Comment by bozana** [comment]
@ctgraham, I think your comments in that other issue #2570 make sense. I could take a deeper look into that (and merge and port to 3.1) short after the coming release 3.1 -- I will be working on Crossref reference linking and thus also on exactly that. 
The citation markup assistant and citation outputs are gone in 3.x i.e. the code is still there but not used, and as I understand not meant to be used in the future, at least not in the same way/using the same code.
Thanks a lot!

**Comment by bozana** [comment]
@asmecher, as far as I can see, we could remove also citationLookup and citationParser plugin, as well as metadata nlm30 plugin. What do you think? Or maybe to leave that for the next release -- for it not to be too short before the current release date -- and now to only remove minimum of citationOutput plugins?

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2871
ojs master: https://github.com/pkp/ojs/pull/1588

**Comment by bozana** [comment]
I decided to remove only the minimum now, if you @asmecher agree. After the release 3.1 I will work on citations for Crossref reference linking and can then remove all the other Citation Markup Assistant plugins (citationLookup and citationParser plugin, as well as metadata nlm30 plugin) and leave and adapt only the minimum code needed to parse the pasted/entered citations by line and save them as the raw plaintext single citations.
Those sophisticated features -- conversion to XML, NLM and other formats -- we can then leave to OTS or so... 
OK so?

**Comment by asmecher** [comment]
Yes, that sounds fine to me. Agreed with the safer minimal removal this close to the 3.1 release.

**Comment by bozana** [comment]
Merged without code review because nothing special...
Closing...

**Comment by mfelczak** [comment]
Hi @bozana, in a new OJS 3.1.0-1 install via git I'm still seeing the citation plugins on the main Plugins page (screenshot attached). Just wanted to confirm whether the plugins need to also be removed from the default set of plugins included with a git checkout?

![citation_plugins](https://user-images.githubusercontent.com/200793/34447120-03c6358a-ecaf-11e7-9d11-3bd0c15cd5ac.png)

**Comment by bozana** [comment]
Hi @mfelczak, the PRs were only for master branch -- because big changes -- and the 3.1.0-1 was made from the ojs-stable-3_1_0 branch, I think. Thus, they will be first removed with 3.2, I think....

**Comment by bozana** [comment]
Ah, sorry @mfelczak, this was the minimal removal -- only the citationOutput plugins, but the other are removed here: https://github.com/pkp/pkp-lib/issues/2874, only for master branch and for thus for 3.2.

**Comment by bozana** [comment]
Hmmm... I think I am confused now :-( It does seem to be considered for removal in 3.1.1 but the code is still there... :-P

**Comment by bozana** [comment]
Ah, OK, I see now, it is how I said before: this is the small change and the bigger change is still coming. Sorry! :-(

**Comment by mfelczak** [comment]
Ok, thanks @bozana!
