### ISSUE TITLE
[OJS] Dataverse plugin: publish Dataverses via API

### ISSUE THREAD

**Issue by jwhitney** [pkp/pkp-lib#286]
Dataverse SWORD API v1.1 adds method to publish unreleased Dataverses via API.

**Comment by asmecher** [comment]
Jen, it looks like this one never got turned into a pull request. Is it still in progress? It's also possible that I lost the link.

**Comment by jwhitney** [comment]
Already merged, I think: https://github.com/pkp/ojs/pull/394

**Comment by asmecher** [comment]
Gotcha, thanks!
