### ISSUE TITLE
Add galleys grid to author's production stage

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#2862]
To allow authors to view/download final versions of their articles, including for subscription journals where the authors may not have a subscription.

**Comment by mfelczak** [comment]
Care of https://forum.pkp.sfu.ca/t/fulltext-pdf-access-to-authors-to-their-own-articles-in-subscription-access-journal/34127

**Comment by ajnyga** [comment]
I think this is already in OJS and OMP master: https://github.com/pkp/ojs/blob/master/templates/controllers/tab/authorDashboard/production.tpl#L17

https://github.com/pkp/omp/blob/master/templates/controllers/tab/authorDashboard/production.tpl#L17

**Comment by NateWr** [comment]
I can confirm that authors have access to the galleys grid in the production stage in OJS 3.1.
