### ISSUE TITLE
Allow themes to override templates in plugins

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2872]
Plugin template files are loaded by passing an explicit file path, like `file:/var/www/html/ojs/plugins/paymethod/manual/templates/paymentForm.tpl`. This makes it harder to override them in themes.

Ideally, a theme should be able to overwrite a plugin template by adding a file to the template directory like `/templates/plugins/blocks/makeSubmission/templates/block.tpl`.

This will be useful for block plugins, some subscription templates and the citationStyleLanguage plugin.

**Comment by NateWr** [comment]
@asmecher Bringing out conversation from https://github.com/pkp/pkp-lib/issues/2714#issuecomment-339714421 over here, I've drawn up a quick Pull Request with one strategy for themes overriding templates in plugins.

https://github.com/pkp/pkp-lib/pull/2970

I looked into using the `template_dir` for this, but couldn't seem to figure out a way to make it happen given our current plugin loading approach, with the full filename (`file:<full-path>`). 

One possibility would be to add the whole `/plugins` directory as a valid `template_dir` with `PKPTemplateManager`, and then update the plugin template paths to be relative from there. But I'm not sure if that would have performance concerns.

If you like the approach in the PR, we can move it up to the `Plugin` class and allow generic plugins to optionally turn it on/off. Or just leave it for themes.

**Comment by asmecher** [comment]
Have you looked at Smarty resources? That's how we currently implement [both app and pkp-lib resources](https://github.com/pkp/pkp-lib/blob/ojs-3_1_0-0/classes/template/PKPTemplateManager.inc.php#L334..L349) (using [PKPTemplateResource](https://github.com/pkp/pkp-lib/blob/ojs-3_1_0-0/classes/template/PKPTemplateResource.inc.php).

I'm thinking we could move plugin templates into the same structure, then adding a hook call in the function that resolves resources into template filenames. That would improve consistency of implementation, and in the end it would be a single line added for the hook call.

**Comment by NateWr** [comment]
Ah ok, I think I've got it. A hook in `PKPTemplateResource::_getFilename()`, and then we refactor all plugins with templates to register their template directories as resources. :+1:

**Comment by NateWr** [comment]
Is this the approach that you had in mind? PR: https://github.com/pkp/pkp-lib/pull/2985

The only downside I see is that we'll need to refactor each plugin whose templates we want to be able to override, to use it's own resource. But not a big problem and we'll probably be better off for it. Thoughts?

**Comment by NateWr** [comment]
@asmecher Ok I think I've got them all as we discussed in https://github.com/pkp/pkp-lib/pull/2985.

PRs:
https://github.com/pkp/pkp-lib/pull/2985
https://github.com/pkp/ojs/pull/1704
https://github.com/pkp/pdfJsViewer/pull/20
https://github.com/NateWr/browseBySection/pull/2
https://github.com/asmecher/lensGalley/pull/17
https://github.com/pkp/orcidProfile/pull/27
https://github.com/pkp/staticPages/pull/27

**Comment by asmecher** [comment]
@NateWr, are you sure this covers all the required cases? I think a lot more form classes will be affected:

````
$ find . -name \*Form.inc.php | grep plugins
./plugins/pubIds/urn/classes/form/URNSettingsForm.inc.php
./plugins/pubIds/doi/classes/form/DOISettingsForm.inc.php
./plugins/importexport/doaj/classes/form/DOAJSettingsForm.inc.php
./plugins/importexport/crossref/classes/form/CrossRefSettingsForm.inc.php
./plugins/importexport/datacite/classes/form/DataciteSettingsForm.inc.php
./plugins/importexport/medra/classes/form/MedraSettingsForm.inc.php
./plugins/paymethod/paypal/PaypalPaymentForm.inc.php
./plugins/paymethod/paypal/PaypalPaymentSettingsForm.inc.php
./plugins/paymethod/manual/ManualPaymentSettingsForm.inc.php
./plugins/generic/addThis/AddThisSettingsForm.inc.php
./plugins/generic/markup/MarkupSettingsForm.inc.php
./plugins/generic/markup/MarkupProfileSettingsForm.inc.php
./plugins/generic/browse/classes/form/BrowseSettingsForm.inc.php
./plugins/generic/piwik/PiwikSettingsForm.inc.php
./plugins/generic/citationStyleLanguage/CitationStyleLanguageSettingsForm.inc.php
./plugins/generic/staticPages/controllers/grid/form/StaticPageForm.inc.php
./plugins/generic/googleAnalytics/GoogleAnalyticsSettingsForm.inc.php
./plugins/generic/fidusWriter/FidusWriterSettingsForm.inc.php
./plugins/generic/orcidProfile/OrcidProfileSettingsForm.inc.php
./plugins/generic/customBlockManager/controllers/grid/form/CustomBlockForm.inc.php
./plugins/generic/externalFeed/ExternalFeedForm.inc.php
./plugins/generic/externalFeed/ExternalFeedSettingsForm.inc.php
./plugins/generic/webFeed/WebFeedSettingsForm.inc.php
./plugins/generic/lucene/classes/form/LuceneSettingsForm.inc.php
./plugins/generic/announcementFeed/AnnouncementFeedSettingsForm.inc.php
./plugins/generic/phpMyVisites/PhpMyVisitesSettingsForm.inc.php
./lib/pkp/plugins/generic/usageStats/UsageStatsSettingsForm.inc.php
./lib/pkp/controllers/grid/plugins/form/UploadPluginForm.inc.php
````

**Comment by NateWr** [comment]
No, it only addresses frontend templates mentioned in the list [here](https://github.com/pkp/pkp-lib/pull/2985#issuecomment-341480181). I can work on covering every backend template as well, but I'll probably have a hard time testing most as I've never used them.

**Comment by NateWr** [comment]
Ok, I think I've got all of them except the PayPal plugin. I wasn't sure what is happening here:

https://github.com/pkp/ojs/blob/master/plugins/paymethod/paypal/PaypalPaymentForm.inc.php#L32

As far as I can tell, that `paymentForm.tpl` that's referenced is not in the plugin itself. I did find one under the OJS templates directory: https://github.com/pkp/ojs/blob/master/templates/payments/paymentForm.tpl

Is that an error, or is it somehow able to find the OJS template? I didn't want to update the template references without knowing better what's going on.

**Comment by NateWr** [comment]
@asmecher A reminder on the question above.

**Comment by asmecher** [comment]
Sorry, I missed that.

- `templates/payments/paymentForm.tpl` was dead code (I've [removed](https://github.com/pkp/ojs/commit/ba726387803e81f92197320d2cbaf7457d41f57c) it)
- Payment actions are implemented using `Form` classes, but rather than displaying form as per normal, the PayPal plugin's form class instead [redirects the user](https://github.com/pkp/ojs/blob/ojs-3_1_0-1/plugins/paymethod/paypal/PaypalPaymentForm.inc.php#L56). So the [template filename it references](https://github.com/pkp/ojs/blob/ojs-3_1_0-1/plugins/paymethod/paypal/PaypalPaymentForm.inc.php#L32) doesn't exist and that's OK. (I'll check to see whether I can provide a `null` or something less silly)

**Comment by asmecher** [comment]
All merged -- thanks, @NateWr!

**Comment by NateWr** [comment]
All merged (thanks Alec).
