### ISSUE TITLE
remove citationLookup, citationParser and nlm30 metadata plugin

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2874]
The code was used in Citation Markup Assistant and via OAI for the NLM format in OJS 2.4.x and it is not used any more in OJS 3.x. Thus it should/can be removed.
S. also https://github.com/pkp/pkp-lib/issues/2859

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2984
ojs master: https://github.com/pkp/ojs/pull/1649

**Comment by bozana** [comment]
@asmecher, could you take a look at the PRs?

**Comment by asmecher** [comment]
Wow. >13,000 unused lines of code removed! The tests will definitely need to pass, and this isn't suitable for the stable branch, but I'm all in favour of committing to master and porting to OMP.

**Comment by bozana** [comment]
@asmecher, I think this is ready to be merged. I think the tests passed, correct? -- the one OMP test had time out... Tanananaaaaaaaaaa... :-)

**Comment by bozana** [comment]
@asmecher, may I merge these changes?

**Comment by asmecher** [comment]
Yes, please do!
