### ISSUE TITLE
buildpkg.sh missing vendor dir

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2877]
I'm getting the following error when trying to run OJS from the package built by running `ojs/tools/buildpkg.sh 3.1 master`.

```
[Tue Oct 17 14:59:27.095809 2017] [:error] [pid 19228] [client ::1:57734] PHP Fatal error:  require_once(): Failed opening required 'lib/pkp/lib/vendor/autoload.php' (include_path='.:/var/www/html/ojs-3.1/classes:/var/www/html/ojs-3.1/pages:/var/www/html/ojs-3.1/lib/pkp:/var/www/html/ojs-3.1/lib/pkp/classes:/var/www/html/ojs-3.1/lib/pkp/pages:/var/www/html/ojs-3.1/lib/pkp/lib/adodb:/var/www/html/ojs-3.1/lib/pkp/lib/phputf8:/var/www/html/ojs-3.1/lib/pkp/lib/pqp/classes:/var/www/html/ojs-3.1/lib/pkp/lib/smarty:.:/usr/share/php') in /var/www/html/ojs-3.1/lib/pkp/classes/core/PKPApplication.inc.php on line 126
```

II took a look and there's no `vendor` dir at `lib/pkp/lib/vendor`. It doesn't appear to be in the excluded dirs in `buildpkg.sh`.

**Comment by bozana** [comment]
Maybe to add here some other comments about buildpkg.sh -- or shall I open a new issue?

This excluded plugin is not there any more i.e. it can be removed from the EXCLUDE:
plugins/generic/counter (this is now a report plugin and functioning)					
			
And these are there and functioning, thus why to exclude them:
plugins/generic/driver						
plugins/generic/openAIRE

Also, why is EXCLUDE excluded?

**Comment by bozana** [comment]
PR that considers the comments above:
ojs master: https://github.com/pkp/ojs/pull/1598

**Comment by bozana** [comment]
Why do we use composer.phar `update` for lib/pkp/? Maybe to also use the `install`?

**Comment by NateWr** [comment]
> Also, why is lib/ui-library excluded?

All of the assets there are compiled into `js/build.js` and `styles/build.css`. We don't do any run-time compilation.

**Comment by NateWr** [comment]
Oh, I just figured out why the error at the top happened for me. :)

```
 - lib/pkp ... /var/www/html/ojs/tools/buildpkg.sh: line 127: composer.phar: command not found
Done
```

I'll work on getting that sorted out.

**Comment by NateWr** [comment]
Another interesting warning message:

```
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
```

**Comment by NateWr** [comment]
Switching to `composer install --no-dev` instead of `composer update --no-dev` fixed the issue with the vendor dir. However, I'm now getting a related error message:

```
PHP Fatal error:  require_once(): Failed opening required '/home/nate/Projects/ojs-3.1/lib/pkp/lib/vendor/composer/autoload_real.php' (include_path='.:/home/nate/Projects/ojs-3.1/classes:/home/nate/Projects/ojs-3.1/pages:/home/nate/Projects/ojs-3.1/lib/pkp:/home/nate/Projects/ojs-3.1/lib/pkp/classes:/home/nate/Projects/ojs-3.1/lib/pkp/pages:/home/nate/Projects/ojs-3.1/lib/pkp/lib/adodb:/home/nate/Projects/ojs-3.1/lib/pkp/lib/phputf8:/home/nate/Projects/ojs-3.1/lib/pkp/lib/pqp/classes:/home/nate/Projects/ojs-3.1/lib/pkp/lib/smarty:.:/usr/share/php') in /home/nate/Projects/ojs-3.1/lib/pkp/lib/vendor/autoload.php on line 5
```

Do we need to add composer to the `composer.json` file?

**Comment by NateWr** [comment]
Hmm, I seem to remember some code in the `composer.json` file related to autloading, that looked like this:

https://getcomposer.org/doc/01-basic-usage.md#autoloading

@kaschioudi I think you were doing that. Is there something we need to add to our `composer.json` file?

**Comment by NateWr** [comment]
@bozana would you be able to cherry-pick the commits from these PRs into yours, so that we're working on the build errors in one PR:

https://github.com/pkp/pkp-lib/issues/2878#issuecomment-337554331

(And maybe also prepare an OMP PR with the fixes as well?)

**Comment by bozana** [comment]
@NateWr, I added your PR here as well and adapted the OMP buildpkg.sh as well.
I don't know what to do with those composer autoloads and excludes... thus, @asmecher you would maybe need to take a look -- maybe you can use the PRs above and build on top of them i.e. tell if we should merge them or...

**Comment by asmecher** [comment]
@NateWr and @bozana, I've rebuilt the exclusions list in the build tool to just focus on unit tests: https://github.com/pkp/ojs/commit/a23fc1ac0b1a567a5ab8c70fdc3b8d4d083f220b
The build size is up to 26M from 25M with the new exclusion list, which is up considerably from OJS 3.0.2's 18M, but I think the risk of trying to squeeze this down at the last minute is too high to tackle it for 3.1.

The patch for moving the `ui-library` less variables into the `pkp-lib` module seems to work for the back-end, but the front end is not showing a working stylesheet -- not sure why that is.

**Comment by asmecher** [comment]
Perhaps this is because there are still several references to `ui-library`:

- plugins/themes/default/DefaultThemePlugin.inc.php line 141
- plugins/themes/default/styles/index.less line 19
- lib/pkp/classes/template/PKPTemplateManager.inc.php line 178

**Comment by NateWr** [comment]
@asmecher Ah, woops! Here are some PRs which should resolve this so that you can continue to exclude `ui-library`.

https://github.com/pkp/pkp-lib/pull/2901
https://github.com/pkp/ojs/pull/1603
https://github.com/pkp/omp/pull/454

**Comment by asmecher** [comment]
Merged, thanks, @NateWr. @bozana, the remaining pieces of the above two PRs looked good to me; are you and Nate still working with them?

**Comment by bozana** [comment]
No, I they were so/finished...

**Comment by asmecher** [comment]
OK, closing this issue for now as I believe it's resolved.
