### ISSUE TITLE
Remove Lucene plugin from OJS3 release

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#2879]
The Lucene plugin has not yet been ported to OJS3. Remove it from the list of included plugins as it creates confusion for JMs trying to use/enable it.

**Comment by asmecher** [comment]
@mfelczak, it's already excluded from builds and thus from the 3.1.0 release -- I'm guessing you're interested in seeing it removed from the stable branch (once one is created for 3.1.0) for the sake of git checkouts?

**Comment by mfelczak** [comment]
Yep that would be great for us and other folks installing from git.

**Comment by asmecher** [comment]
Merging with https://github.com/pkp/pkp-lib/issues/2843.
