### ISSUE TITLE
5 messages in locale/pt_BR/user.xml needs translation

### ISSUE THREAD

**Issue by mrmorais** [pkp/pkp-lib#2880]
I'm working on this translation. The message keys are:
- user.apiKey
- user.apiKeyEnabled
- user.apiKey.generate
- user.apiKey.generateWarning
- user.apiKey.secretRequired

**Comment by mtub** [comment]
pkp/pkp-lib#2604

**Comment by mtub** [comment]
Merged, thanks @mrmorais !
