### ISSUE TITLE
Improve the reviewer selection list

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2894]
This issue aggregates a bunch of related issues around reviewer selection. The goal is to refactor the reviewer selection to use the new Vue.js components and the REST API in the process of improving reviewer selection.

- [x] Refactor selection grid to ListPanel or similar and use REST API.
- [x] Implement reviewer ratings and gossip field. https://github.com/pkp/pkp-lib/issues/372
- [x] Find a reviewer by Affiliation. https://github.com/pkp/pkp-lib/issues/2785

(edit - this issue has been repurposed specifically for replacing the reviewer selection grid. general reviewer management issues are now collected in the [Reviewer Selection and Management Project](https://github.com/pkp/pkp-lib/projects/7)).

**Comment by ajnyga** [comment]
Hi,

We got a related request. When you are adding a reviewer and select "Enroll an existing user", the system only shows a name. There is no way of telling if the person is the John Doe you are looking for. So maybe it could also show the email address and possible affiliation?

**Comment by NateWr** [comment]
:+1: Added it to the list at the top

**Comment by NateWr** [comment]
I'm working on the reviewer search filtering. Currently, we have four range sliders which allow editors to search with lower and upper limits (ie - at least X but no more than X):

![selection_051](https://user-images.githubusercontent.com/2306629/35513392-ca8d50aa-04fa-11e8-810a-851c03ecf365.png)

I'm wondering if the range is appropriate for all four of these. In particular:

1. Will anyone ever want to set a maximum on the completed reviews? Or will they always search for AT LEAST X reviews and never AT MOST X reviews?

2. The same question for the average days to complete a review? It seems an editor would always filter by a max (ie - it takes no longer than X) rather than a minimum (ie - it takes at least X days to complete).

Can anyone think of objections to changing these two from a range to a single value (at least X completed reviews; at most X days to complete)?

**Comment by jmacgreg** [comment]
Hi @NateWr: agreed on both assumptions, at least from my perspective. I think this would also simplify the interface a bit - just having the one range slider for each, instead of two.

**Comment by alexxxmendonca** [comment]
First off, this looks great! 👍 

I also agree with your assumptions and I second @jmacgreg's comments too.

If I may, I think it might be helpful to have a filter showing "Invitations Declined" and again, I think it would probably be just a "max number of invitations declined"

**Comment by NateWr** [comment]
Thanks @alexxxmendoca! Do you think the declined invitations should be a raw number (# of declined) or a ratio (X% of invitations declined)?

**Comment by alexxxmendonca** [comment]
That's a good question... I like the idea of percentage, simply because 5 declined invitations out of 5 has a different weight than 5 declined invitations out of 20.

I think we can go with percentage in this case.

**Comment by willinsky** [comment]
Great to see this simplified, as Active Reviews would very very rarely be more than 1, and editors would want only those who have no active reviews, unless it is a very special case. So none active is something of a default search, and you would not search for more (though in that special case, you would select someone with an already active). In terms of down the road, in refactoring [stats on reviewers](https://docs.google.com/document/d/1FT52m9G-ZgKdtLMRkjhhGir0YjtcM6SgVdnZGT-TcKE/edit?usp=sharing), I'm pushing for counts on "Requests" and "Completed" (because to "not decline" doesn't unfortunately mean you completed a review). The default version of editor search would then be "none active" and "one or more completed" (because they are only on the list if there's been a request, except for rare birds for volunteer). After that, the reviewer's interest is the selection driver (assisted in this refactoring by ORCID and Google Scholar links).

**Comment by NateWr** [comment]
> After that, the reviewer's interest is the selection driver (assisted in this refactoring by ORCID and Google Scholar links).

Adding an ORCID link is a great idea, I've got that noted down.

> Active Reviews would very very rarely be more than 1, and editors would want only those who have no active reviews

I think you're right on this, but I want to keep that slider filter in place just for now because it is the only way an admin or journal manager can get an overall view of active reviewers in the system. Eventually we may provide better tools for this in the user management or stats areas. But until then I think some editors may repurpose this tool to get that information, and I don't want to pull the rug out from them just yet.

**Comment by willinsky** [comment]
That makes sense, certainly, although I am assuming that with the Active sliders, the default opening would be both dots appearing as a single dot on zero (which will make sense visually, in terms of their being two dots, in relation to other sliders). On the other hand, I really like your idea above, of a day ago, of having a single value option, instead of a slider for Completed and Days, which in this case is set at zero by default  for active, as in Active: [0].

**Comment by NateWr** [comment]
The following PRs implement a new reviewer selection list panel. These changes include:

- `/users/reviewers` API endpoint that feeds the list panel.
- Searching extended to user affiliation, biography and orcid.
- Review assignment ratings introduced.
- Gossip/Editorial Notes introduced for reviewers. (Admins, editors and subeditors can view.)
- Expanded view of reviewers to view biography and gossip.
- Filtering by rating, reviews completed, days since last assignment, active reviews, average days to complete.
- A bunch of refactoring in the UI Library to share common components (buttons, badges, lists).

![reviewer-1](https://user-images.githubusercontent.com/2306629/35740879-1a2e5060-082e-11e8-9ec0-bf4ed7a4de23.png)

![reviewer-2](https://user-images.githubusercontent.com/2306629/35740889-1e2b650e-082e-11e8-9bea-937192776236.png)

![reviewer-selection](https://user-images.githubusercontent.com/2306629/35740896-25851f66-082e-11e8-9dd9-24a0a5c86422.gif)

PRs:
https://github.com/pkp/pkp-lib/pull/3341
https://github.com/pkp/ui-library/pull/9/
https://github.com/pkp/ojs/pull/1822
(omp coming)

**Comment by alexxxmendonca** [comment]
This looks great, @NateWr !

**Comment by ajnyga** [comment]
Just wow, our editors have been very pleased with the filters in the submission listings so I know they are going to love this!

**Comment by NateWr** [comment]
@bozana can you code review?

PRs:
https://github.com/pkp/pkp-lib/pull/3341
https://github.com/pkp/ui-library/pull/9/
https://github.com/pkp/ojs/pull/1822
https://github.com/pkp/omp/pull/501

**Comment by NateWr** [comment]
@bozana I think I covered everything in your initial code review of pkp-lib. I've rebased the PRs:

https://github.com/pkp/pkp-lib/pull/3341
https://github.com/pkp/ui-library/pull/9/
https://github.com/pkp/ojs/pull/1822
https://github.com/pkp/omp/pull/501

**Comment by aleskl** [comment]
Is it possible to sort reviewers eg. by number of reviews by clicking on the column headers in the reviewer selection table? That was possible in 2.4.X version (although not fully functional).

**Comment by bozana** [comment]
new PRs, with a few fixes and rebased, ready for merging:
https://github.com/pkp/pkp-lib/pull/3411
https://github.com/pkp/ui-library/pull/11
https://github.com/pkp/ojs/pull/1848
https://github.com/pkp/omp/pull/504

**Comment by bozana** [comment]
@aleskl, no this is not possible -- now it looks totally different -- but the reviewers are per default ordered by the number of completed reviews. Furthermore, there are other filter options. But currently no sorting options in the GUI.

**Comment by bozana** [comment]
everything merged, thus closing....

**Comment by ajnyga** [comment]
@NateWr 
Just checking: does this now allow searching reviewers with email addresses?

**Comment by NateWr** [comment]
Yep!
