### ISSUE TITLE
references from the submission settings should be called citations

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2896]
in order to be correctly handled in the submission metadata form validator: https://github.com/pkp/pkp-lib/blob/master/classes/submission/PKPSubmissionMetadataFormImplementation.inc.php#L66-L73

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2897
ojs master: https://github.com/pkp/ojs/pull/1600

**Comment by bozana** [comment]
@NateWr, could you take a look at these PRs? Thanks!!!

**Comment by NateWr** [comment]
@bozana Looks great! I tested both with no problems. Go ahead and merge when you're ready.
