### ISSUE TITLE
Test upgrades

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2900]
In particular, test...
- [ ] OJS 3.0.2 -> 3.1
- [ ] OJS 2.4.8-x -> 3.1

**Comment by asmecher** [comment]
@bozana, do you have time to give this a quick smoke test in the morning?

**Comment by bozana** [comment]
Yesterday I did some tests, but will do some further today... Can I maybe also do it on the weekend?

**Comment by asmecher** [comment]
:P I'll be working too!

**Comment by diegoabadan** [comment]
Hi! Do you have a .tar.gz so I can help with tests here?

**Comment by bozana** [comment]
I've tested it, but haven't double checked everything, so I will close the issue and keep testing till the release....
