### ISSUE TITLE
Updates to installation screen

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2924]
Has the minimum PHP version changed?

![selection_010](https://user-images.githubusercontent.com/2306629/31890464-23b0b714-b7fb-11e7-9114-d4410f35c171.png)

Should the default beacon identifier be changed?

![selection_011](https://user-images.githubusercontent.com/2306629/31890475-2c61b962-b7fb-11e7-93cc-bb5ecc0099c8.png)

**Comment by asmecher** [comment]
I've updated the required PHP version, thanks.

The `ojs2` identifier is a little trickier -- it's already filed at https://github.com/pkp/pkp-lib/issues/1839.
