### ISSUE TITLE
[OJS31] Wrong behaviour of Edit User Window

### ISSUE THREAD

**Issue by crosfield** [pkp/pkp-lib#2926]
The behavior of the Edit User window has changed. Now (in the current branch right now) when you try to save any changes, the user is ALWAYS prompted for a password even when nothing has changed in the window.
<img width="788" alt="screen shot 2017-10-23 at 21 06 32" src="https://user-images.githubusercontent.com/8432203/31905360-9b7abec6-b836-11e7-815d-232cc6b522b8.png">

**Comment by asmecher** [comment]
This was revealed by https://github.com/pkp/pkp-lib/commit/27c03dbc9f915accf93c3852cc150972b569dacd and fixed by https://github.com/pkp/pkp-lib/commit/225deff085abb241b09205e7f01f79e4caec624b.
