### ISSUE TITLE
access denied on the announcements setting page

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2930]
after the upgrade from 2.4.8-2, accessing it as admin

**Comment by bozana** [comment]
This part of code is leading to that: https://github.com/pkp/pkp-lib/blob/master/controllers/grid/announcements/AnnouncementGridHandler.inc.php#L36-L50

**Comment by bozana** [comment]
@asmecher, I am not sure what is the right fix:
-- either to return true also if the setting is not there in the code from the link above
or
-- to check if the setting is there in the template and then not to load the url in div (s. https://github.com/pkp/pkp-lib/blob/master/templates/controllers/tab/settings/announcements/form/announcementSettingsForm.tpl#L45-L46)

**Comment by bozana** [comment]
Ah I think I know...

**Comment by bozana** [comment]
Hmmm... No, I do not know -- I thought I could add one more "false" parameter here: https://github.com/pkp/pkp-lib/blob/master/controllers/grid/announcements/ManageAnnouncementGridHandler.inc.php#L91, but... I realize that I do not understand what is the purpose of the checkbox "Enable Journal Managers to add journal announcements. " :-P

**Comment by bozana** [comment]
Hmmm... I think there is no sense to require that the checkbox is selected to display the announcements grid. So I will change it so that it is not required...

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2932
ojs master: https://github.com/pkp/ojs/pull/1626

**Comment by bozana** [comment]
@asmecher, could you take a look?

**Comment by asmecher** [comment]
Merged, thanks -- this makes sense.
