### ISSUE TITLE
Site Admin Email Receiving Mail for All Actions

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2931]
When running some papers through the submission process (OJS 3.0.2 - https://journals.lib.sfu.ca), the Site Admin was receiving an email notification for each action. The account is registered as a Journal Manager but not as an Editor, so should not be receiving workflow notifications.

**Comment by asmecher** [comment]
Notifications are addressed differently depending on the notification. What kinds of notifications was the admin getting? (I suspect this was already fixed in 3.1.0, but a few typical ones would help confirm.)

**Comment by asmecher** [comment]
@stranack, waiting for your feedback.

**Comment by asmecher** [comment]
Thanks!
