### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by cristiaan3003** [pkp/pkp-lib#2937]
Hello.

Tutorial create Web application with  PKP Web Application Library? hello world for this library b or similar?

Regards

**Comment by asmecher** [comment]
@cristiaan3003, I'm afraid not -- we don't intend this as a general-purpose library, but as a shared resource for the existing PKP applications. In the future, please ask general questions on our forum at http://forum.pkp.sfu.ca/; this is for specific bug entries.
