### ISSUE TITLE
ldap doesn't work

### ISSUE THREAD

**Issue by baudryj** [pkp/pkp-lib#294]
I have installed the last version of OCS 2.3.6 with a LAMP Server (php 5 / ubuntu 14.04)
And LDAP authentification doesn't work with no explanations.

php5-ldap is installed

Any idea ?

Regards

**Comment by asmecher** [comment]
@baudryj, LDAP is not well supported and I'm not surprised to hear that it's not working. It will definitely need some experimentation or possibly coding to get working. FYI, most users who are interested in LDAP expect it to work as a single-sign-on tool, which it cannot do, so they opt not to use it.
