### ISSUE TITLE
[OJS] Infinite loop in upgrade from 2.4.8.2 to 3.1, failing to skip missing files

### ISSUE THREAD

**Issue by ianthe** [pkp/pkp-lib#2942]
When upgrading from 2.4.8.2 to 3.1.0.0, there was an infinite loop when attempting to skip a missing file:

> [lacddt@lac-php-test2 tools]$ php upgrade.php check
> Code version:      3.1.0.0
> Database version:  2.4.8.2
> Latest version:    3.1.0.0
> Database version is older than code version
> Run "upgrade.php upgrade" to update
> [lacddt@lac-php-test2 tools]$ php upgrade.php upgrade
> [pre-install]
> [load: upgrade.xml]
> [version: 3.1.0.0]
> [code: Installer Installer::syncSeriesAssocType]
> [data: dbscripts/xml/upgrade/2.4.0_preupdate_usageStatistics.xml (skipped)]
> [data: dbscripts/xml/upgrade/2.4.0_preupdate_usageStatistics2.xml (skipped)]
> [code: Installer Installer::removeReviewEntries]
> WARNING: Unable to find a match for "1167-4677-1-RV.docx" in "/home/lib/lacddt/hostedjournals/devojs-files//journals/7//articles/1167/". Skipping this file.
> WARNING: Unable to find a match for "1167-4677-1-RV.docx" in "/home/lib/lacddt/hostedjournals/devojs-files//journals/7//articles/1167/". Skipping this file.
> WARNING: Unable to find a match for "1167-4677-1-RV.docx" in "/home/lib/lacddt/hostedjournals/devojs-files//journals/7//articles/1167/". Skipping this file.
> WARNING: Unable to find a match for "1167-4677-1-RV.docx" in "/home/lib/lacddt/hostedjournals/devojs-files//journals/7//articles/1167/". Skipping this file.
> WARNING: Unable to find a match for "1167-4677-1-RV.docx" in "/home/lib/lacddt/hostedjournals/devojs-files//journals/7//articles/1167/". Skipping this file.
> ...

Looking in the files directory the file is missing from the submission folders even though there is an entry for it in the database. 

Unfortunately, it seems that the upgrade script is failing to skip the file and keeps trying to.

As a workaround, I created an empty file and placed it in the appropriate submission directory and this let the upgrade continue and complete successfully.

**Comment by bozana** [comment]
@ianthe, what comes after those warnings?

**Comment by bozana** [comment]
Oh I see... It's infinite...

**Comment by ianthe** [comment]
Exactly... it just goes on and on writing out the same error until I cancelled it.

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1635
ojs ojs-stabe-3_0_1: https://github.com/pkp/ojs/pull/1636

**Comment by bozana** [comment]
Everything merged, thus closeing
