### ISSUE TITLE
NavigationMenus - Issue with NMI with no displayable children

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#2947]
If a NMI has children which are not displayable, the navigationMenu.tpl still thinks it is a parent NMI and displays it accordingly.

**Comment by defstat** [comment]
@NateWr 
PR:
pkp-lib: #2950

**Comment by defstat** [comment]
@NateWr

**Comment by defstat** [comment]
@NateWr 
New PR:
pkp-lib: #3260

**Comment by NateWr** [comment]
Merged!
