### ISSUE TITLE
Locales in lib/pkp should not be referring "Journal" in texts 

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#2949]
The shared locales in lib/pkp should display a more general (Context maybe) text description for contextual references like "Journal" or "Press"

**Comment by ajnyga** [comment]
I agree, but a word like "context" is hard to translate and difficult for people to understand. I remember that it took me while to understand what it means in the context (pun intended) of OJS.

**Comment by defstat** [comment]
Maybe the "Context" related locales should be in the context level locale folder. 
Or maybe the shared locales should avoid referring to "Journal" or "Press" all together.

**Comment by ajnyga** [comment]
One option would be to use a context variable which would then be replaced with "journal" or "press" depending on the context. But I do not know if PKP wants to go to that direction.

**Comment by mtub** [comment]
Hi @defstat , do you have a few examples? You are right, everything that's addressing journals or books/presses in particular should be moved to the corresponding application. But I guess that a few mentions of journal or press in pkp-lib could be rephrased in a more agnostic way.

**Comment by defstat** [comment]
Hi @mtub! I filed this report mainly because of some NavigationMenu Locales, like lets say `manager.navigationMenus.about.conditionalWarning`. I am about to create a PR with them transferred to each of the context level locales with the appropriate rephrasing.
