### ISSUE TITLE
OJS and Google Scholar indexing problem

### ISSUE THREAD

**Issue by MagnoliaPress** [pkp/pkp-lib#295]
Hello:

Biotaxa.org is currently hosting academic journals with a mixed model or scholarly
society journals secured to members only.  Other platforms for journal publishing
(e.g. Wiley etc) can enable Google Scholar to index full text of secured contents. 
When users click the full text links referred by Google Scholar, it was re-directed
to the abstract page (with login on side bars).  This way the Google search
correctly directs the link to the searched paper.   OJS redirects the full text link
of Google to a login page (without any info of the searched paper).  This is not
acceptable to Google Scholar.  The redirection should be to the abstract page of the
paper (the user can then decide to login or purchase etc).  

Google Scholar is increasingly used by scholars as the main means of searching and
indexing (citation counts) of scholar papers (and it is a free tool). Biotaxa.org currently is the largest site
using OJS with secured contents. I am writing to report this problem to you and hope
this can be resolved so that OJS can be more google friendly.  This is probably an
issue of changing some scripts in OJS and may be easy for you. A representative from
Google Scholar will also contact PKP shortly regarding this issue.

Thank you for your attention.

Zhi-Qiang Zhang
Chief editor, Zootaxa

**Comment by asmecher** [comment]
@MagnoliaPress, I'll wait to hear from Google Scholar, as they generally have fairly specific recommendations. However, as we're an open source project -- if you have a strong preference for how this should work, one option would be to code the changes yourselves and submit them back to PKP for code review and potential inclusion in future releases.

**Comment by jalperin** [comment]
@asmecher: Is the problem here how we handle access to paywalled content? Or is the problem here actually with Google Scholar? I can confirm that the typical experience when one clicks a link to a paywalled article is to land on a page that has information about the article (typically the abstract) and a login link.

**Comment by asmecher** [comment]
@jalperin, I won't know what the best solution is until GS gives us some feedback -- they typically expect a fairly rigid approach. It might be e.g. a redirect back to the abstract page when the paywalled galley is requested, or metadata to indicate pay status, or that JMs add subscription IP ranges for Google Scholar, or something else.

**Comment by jalperin** [comment]
Have you reached out to GS? Do you want me to make contact?

**Comment by asmecher** [comment]
@jalperin, from the first message in the thread: "A representative from
Google Scholar will also contact PKP shortly regarding this issue."

**Comment by MagnoliaPress** [comment]
Hi Guys, Thanks for the replies.

Yes when user click on a non- open access paper pdf file on google search result, OJS should redirect to it's abstract page instead of a log in page.  Also after user logged in, browser should redirect to the page they opened before (the abstract page).

Regards

**Comment by jmacgreg** [comment]
I've given this some consideration, and I can't see how this can be an OJS fix - it has to come from the Google/Google Scholar side. Using http://biotaxa.org/Zootaxa/article/view/zootaxa.3779.1.2 as an example: 

- Google indexes the OJS site. This includes abstract/landing pages, which have the appropriate Google Scholar meta tags, including abstract *and* fulltext tags to PDF, HTML galleys, if present. 
- Google holds the index to this content. This means that it indexes the abstract page, plus the galley pages. If it doesn't have special (ie. subscriber) access to the galleys, it can't index them fully - but thanks to the GS meta tags, it knows they exist. 
- There's no way for us to somehow manage incoming links from Scholar or elsewhere to go to the abstract/landing page if they are requesting fulltext, without breaking fulltext access for subscribers. 
- Also, if something should be done differently, it can be done at their end once vs. "our" end for thousands of journal instances. 
- Finally, Google Scholar should easily be able to determine the main (ie. abstract/landing page) link for any article in OJS; and also the fulltext links, if available, from the citation_* meta tags. Examples from the above article: 

<meta name="citation_abstract_html_url" content="http://biotaxa.org/Zootaxa/article/view/zootaxa.3779.1.2"/>

- links to the abstract, which opens fine, and is correctly labeled;

<meta name="citation_pdf_url" content="http://biotaxa.org/Zootaxa/article/download/zootaxa.3779.1.2/7219"/>

- links to one of the article PDFs. 

... so unless we hear back something different from the Scholar folks, I can't see how this can be fixed from the OJS side.
