### ISSUE TITLE
NavigationMenus - NavigationMenu edit - unbind NavigationMenu from area 

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#2952]
The user has no way to unbind a NM from the given Area. 
A "none" option at NavigationMenu Form area dropdown control could be added in order for the user to be able to un-bind the edited NavigationMenu from the previously given area. 
Moreover, if the user chooses to assign an area that is already assigned to a NM, the NM that previously had the area could be assigned the "none" area automatically.

**Comment by defstat** [comment]
@NateWr 
I made some changes for that: I added a "none" dropdown option to the area control of the NavigationMenuForm. If the user tries to change the area of the last navigation menu that is bound to that area, the update validation fails. (defstat@5954515e1752b82a325ec7bc5a350ce1c369caa3)

**Comment by NateWr** [comment]
@defstat Hmm, I think it should be allowed to have an area with no navigation menus assigned. Someone may choose not to have a menu in a certain area.

Instead, I'd like to see it so that someone can't assign multiple menus to a single area. Can you adjust the validation to check for if a different menu is already assigned?

(The None dropdown looks good.)

**Comment by defstat** [comment]
@NateWr I will adjust the validation. Do you think that the user could remove all the NMs from all the areas?

**Comment by NateWr** [comment]
Yeah, I think so. It seems like an edge case but I think we should allow it. One case I can think of is a theme that registers lots of possible menu areas, but a site may only want to use some of them.

**Comment by defstat** [comment]
@NateWr 
PR:
PKP-LIB: #2963

**Comment by defstat** [comment]
@NateWr

**Comment by defstat** [comment]
@NateWr Changes made, rebased and added PR for OJS and OMP to run the tests

**Comment by NateWr** [comment]
Merged! Thanks @defstat!
