### ISSUE TITLE
Reference to chapters when editing component in OJS 3.1

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2955]
When editing a component, one of the options is " Allow files of this type to be sorted by chapter". We should remove this from OJS 3.x.

**Comment by bozana** [comment]
Hmmm... OTHER genre is sortable also in OJS, s. https://github.com/pkp/ojs/blob/master/registry/genres.xml#L30. What does that mean? Should then the text above be changed for OJS, or should the OTHER genre not be sortable for OJS? @asmecher, @stranack, do you know?

**Comment by asmecher** [comment]
Yes, "sortable" appears to be dead code, and even going back to the first release of OMP (where this code was first introduced) it doesn't appear to be used. I'd suggest removing it throughout.

**Comment by bozana** [comment]
@asmecher, do you mean to totally totally remove it from OJS and OMP?

**Comment by asmecher** [comment]
I suspect this goes way back to the original OMP spec. I don't recall what Sortable was for -- perhaps @stranack or @willinsky? If neither can remember, I think we can safely remove it.

**Comment by willinsky** [comment]
I can imagine that there was an idea that in OMP files associated with a book chapter might end up being uploaded out of order and that such files would need to be grouped and sorted by chapter. If we have a drag and drop means of re-ordering files or if we upload to a chapter folder, then we're good.

**Comment by bozana** [comment]
Yes, the files are assigned to chapters, so I will remove this unused "sortable" feature... THANKS!!!

**Comment by bozana** [comment]
@NateWr, could you code review the PRs?

**Comment by NateWr** [comment]
@bozana Looks great! I found a couple more remnants to remove. The following locale keys don't appear to be used anymore:

```
manager.setup.genres.sortable
manager.setup.sortableByComponent
```

And I couldn't find any reference to the constant `GENRE_SORTABLE_DESIGNATION` which is defined in `Genre.inc.php`.

:+1:

**Comment by bozana** [comment]
Wow @NateWr, great catch!!! :star:

**Comment by bozana** [comment]
I removed those locale keys and the constant and will now wait for tests to pass and then merge...
