### ISSUE TITLE
Problems with Add Item action in Sidebar control

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2960]
Under Settings > Website > Appearance. h/t @stranack 

![capture](https://user-images.githubusercontent.com/2306629/32042144-7b7ad6fc-ba2e-11e7-945e-db97b55ecab5.PNG)

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/2971

Tests:
https://github.com/pkp/ojs/pull/1643

**Comment by NateWr** [comment]
Tests  passed and I've refreshed the PR for this one. @bozana would you take a look at this one too?

**Comment by bozana** [comment]
@NateWr, I believe you will have to rebase -- the pkp-lib changed -- but else, everything fine, please go ahead then...

**Comment by NateWr** [comment]
:+1:
