### ISSUE TITLE
APC usability issues

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2964]
Currently APC configuration information exists under Subscriptions > Payment Types. From a user perspective, it doesn't make sense to place it under Subscriptions. We should consider moving this information somewhere else in a future version.

Perhaps creating a new left sidebar entry for "Payments" and put all things payment related there - including the current info under Settings > Distribution > Payment?

Also, in the Subscriptions > Payment Types, we refer to "Author Fees", "Author Processing Fees", and "Article Publishing Fees" all in the one small section. We should standardize around "Article Processing Charge" (from Wikipedia).

**Comment by asmecher** [comment]
Agreed, I wanted to improve this before 3.1 but didn't have time.

**Comment by asmecher** [comment]
@stranack, here's what I did for the settings rearrangement:

- Moved the main enable/disable toggle into the Payments form in Distribution settings
- Renamed the "Subscriptions" sidebar setting to "Payments", and made its visibility dependent on the aforementioned toggle

This way the sidebar doesn't get cluttered with payment concerns unless the journal enables payments via the more compact settings area. Does that sound reasonable?

**Comment by asmecher** [comment]
@stranack, I also made the APC language consistent as you suggested, *except* that I kept the "Author Fees" heading. We may add other author fees to this heading at some point, such as submission fees; it's intended as a category, not just for APCs.
