### ISSUE TITLE
[OJS] Adding section editors to a section and returning to add more editors later breaks the section form

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2965]
Hi,

One of our journals wants to discuss all incoming papers with the whole editorial board. I have instructed them to add themselves as section editors to the sections where such discussions are needed.

However, OJS3 seems to have a hard coded limit of 7 section editors per section. After adding 7 section editors to a section, the add item link does not work anymore.

Is there a reason for this, why not just allow as many as the journals need?

OJS 3.0.2

**Comment by asmecher** [comment]
I don't think there's anything hard coded, but I could be wrong -- were you able to track down the limit in the code?

**Comment by ajnyga** [comment]
Ok, so something else is preventing adding more section editors to two sections. In another section I was able to add all sections editors (9). 

Also, if I remove one of the section editors in the problematic sections, I can not add her back anymore. Very weird.

**Comment by ajnyga** [comment]
So basically:
If I edit a section and remove on of the editors, I can then add all remaining editors to that section except for the one I just removed.
But, if I remove one editor and then hit save and return to edit, the Add item button does not work.

**Comment by ajnyga** [comment]
It is a bug @asmecher, also in OJS 3.1

Try the following:
- Create three section editor users
- Go to edit a section and add two of those editors to that section, hit save
- Return to edit the section and now try to add the third one: at least for me it will not work

**Comment by asmecher** [comment]
@NateWr, this might be a good opportunity to start removing listbuilders (top of the list of creaky/painful pieces of our old JS framework IMO).

We just need a list with checkboxes, and I don't think we'll have so many entries in this case that we won't be able to feed them all to the browser. Is there a particular kind of control you'd advocate for?

If you do think consistency across user lists is important, then there is some functional cross-over with the reviewer select list, though that's a much more complicated beast with a much bigger data set in it.

**Comment by ajnyga** [comment]
I really hate the listbuilder, because it hides the available options.

I am not sure if simple checkboxes would work everywhere, but at least in this case it is hard to believe that the number of section editors would ever be more than 10. I could be wrong.

Regarding this case, I wonder if it is a general bug with all listbuilders?

**Comment by NateWr** [comment]
@ajnyga I know if the ListBuilder doesn't believe there's another available option to be added, clicking the Add link will do nothing -- not even provide a useful message. It sounds like you may be running into this alongside some other issue with a miscount of available options.

@asmecher Yes, there's already the `SelectListPanel` component in the UI Library and I think it would work for the majority of single-column ListBuilders. You can see it in use in the CitationStyleLanguage plugin. 

https://github.com/pkp/citationStyleLanguage/blob/master/CitationStyleLanguageSettingsForm.inc.php#L75-L85
https://github.com/pkp/citationStyleLanguage/blob/master/templates/settings.tpl#L22-L29

And if you spin up the UI Library itself (`cd lib/ui-library & npm install & npm run dev`), you should see the full range of data you can pass to configure it.

**Comment by NateWr** [comment]
ps - if anyone wants to compile a list of ListBuilders in the application, I'll happily run through and replace them. :)

**Comment by asmecher** [comment]
> ps - if anyone wants to compile a list of ListBuilders in the application, I'll happily run through and replace them. :)

Dangerous words, @NateWr :)

For OJS and pkp-lib: 

- plugins/generic/translator/controllers/listbuilder/LocaleFileListbuilderHandler.inc.php (the translator plugin's list of locale files)
- lib/pkp/controllers/listbuilder/users/UsersListbuilderHandler.inc.php (and parent class lib/pkp/controllers/listbuilder/users/StageUsersListbuilderHandler.inc.php) -- used in the "notify" form to choose who may receive an email
- lib/pkp/controllers/listbuilder/users/UserUserGroupListbuilderHandler.inc.php - See create/edit user
- lib/pkp/controllers/listbuilder/settings/SubEditorsListbuilderHandler.inc.php - See create/edit section
- lib/pkp/controllers/listbuilder/settings/reviewForms/ReviewFormElementResponseItemListbuilderHandler.inc.php - See review form construction tools
- lib/pkp/controllers/listbuilder/settings/BlockPluginsListbuilderHandler.inc.php
 and lib/pkp/controllers/listbuilder/admin/siteSetup/AdminBlockPluginsListbuilderHandler.inc.php (list of sidebar block plugins in website setup/administration)

OMP has a few more:
- controllers/submission/CategoriesListbuilderHandler.inc.php (for assigning categories to submissions)
- controllers/listbuilder/users/ChapterAuthorListbuilderHandler.inc.php (for assigning authors to chapters)
- controllers/listbuilder/settings/CategoriesListbuilderHandler.inc.php (for assigning categories to series)
- controllers/listbuilder/files/ChapterFilesListbuilderHandler.inc.php (for assigning files to chapters)

The two main modes of operation for listbuilders are drop-down and free text entry.

One special case to watch out for in free text entry is the multilingual listbuilder. This is currently only used in creating review form elements -- this allows you to enter text in potentially several languages.

**Comment by NateWr** [comment]
> One special case to watch out for in free text entry is the multilingual listbuilder. This is currently only used in creating review form elements -- this allows you to enter text in potentially several languages.

Yeah, I'll only be able to replace the basic ones with the `SelectListPanel` component. For the others with drag-and-drop (sidebars), free text entry, etc, we'll probably need an alternate component. But I'll crack on with this list and see what can go quickly.

**Comment by NateWr** [comment]
> Dangerous words, @NateWr :)

Ahhhhh, you were right. This turned into much more of a project than I anticipated. I was able to replace:

- UsersListbuilderHandler
- StageUsersListbuilderHandler
- UserUserGroupListbuilderHandler
- SubEditorsListbuilderHandler
- CategoriesListbuilderHandler (submissions)
- CategoriesListbuilderHandler (series)

In the process, I also introduced a new `UserService` class, along with a `/users` endpoint for the API. It would be good if @kaschioudi could cast an eye on the [spec for this endpoint](https://github.com/pkp/ojs/pull/1670/files#diff-af1378786616b9b87b3a35df297d4312). And this should be useful for work on the reviewer selection and users grid.

That leaves the following which I couldn't replace because they require more than just list selection. That includes those with free text entry:

- LocaleFileListbuilderHandler
- ReviewFormElementResponseItemListbuilderHandler

Those with drag-and-drop functionality:

- BlockPluginsListbuilderHandler
- AdminBlockPluginsListbuilderHandler

And those which need to be orderable:

- ChapterAuthorListbuilderHandler
- ChapterFilesListbuilderHandler

PRs:
https://github.com/pkp/pkp-lib/pull/3025
https://github.com/pkp/ui-library/pull/5
https://github.com/pkp/ojs/pull/1670
https://github.com/pkp/omp/pull/463

I'm not sure who to assign on this one, but @bozana or @asmecher would you take a look?

**Comment by NateWr** [comment]
(Oh, and this probably shouldn't get merged into `master` if we want to make a new release off of it soon.)

**Comment by asmecher** [comment]
Hi @natewr -- agreed, probably not a good candidate for merging right now, but maybe we could create a branch. Let's talk in the dev call. Excellent progress in any case.

**Comment by kaschioudi** [comment]
@NateWr : I took a look at your commit. Other than this comment (https://github.com/pkp/ojs/pull/1670/files#r149253472) , it looks good to me 👍 .

**Comment by NateWr** [comment]
Thanks @kaschioudi. Good spot. Eventually editors will need access to the endpoint for adding participants to the workflow, but I didn't want to deal with that yet, so I've just removed them from the list in the documentation. :smile:

**Comment by asmecher** [comment]
@NateWr, FYI, if you'd like to get this merged -- now isn't the worst time!

**Comment by asmecher** [comment]
> That's failing to find <label>Journal manager</label>. But when I create a user myself I can see it.

It's whitespace; edit `lib/pkp/tests/data/PKPCreateUsersTest.inc.php` and find:

    $this->click('//label[text()=\'' . $role . '\']');

Wrap the `text()` fetch in `normalize-space` to get:

    $this->click('//label[normalize-space(text())=\'' . $role . '\']');

**Comment by NateWr** [comment]
Merged! :tada:
