### ISSUE TITLE
[OJS] OJS 3.1 missing link from Site Administration to Journal Administration

### ISSUE THREAD

**Issue by dtwardy** [pkp/pkp-lib#2967]
In OJS 3.0 admins had access to site and journal administration at the same time. The drop down menu for selecting which journal you were working was only needed when there was more than one journal. Now in OJS 3.1 there's no connection anymore and no option to switch from site administration to journal administration. The drop down is fixed to "Open Journal Systems" and not offering anything when there's only one journal and the menu on the left is not showing any journal options. 

Admins now have to log in at frontend and click on their Dashboard link to reach journal specific settings.

That can't be right. I assume an if clause hasn't been updated to offer the drop down menu even if there's just one journal in an OJS instance.

**Comment by bozana** [comment]
How did you install OJS 3.1? -- It feels like something is missing for you... -- I have no such problems... -- I have the drop-down and journals listed...

**Comment by dtwardy** [comment]
I cloned the repository, checked out latest stable branch, submodule update and then ran composer in pkp/lib and in the new two plugin folders for payment s and citations. I've tried it several times on different machines. The drop down only actually "drops down" when there's more than one journal. It worked for me just like that in 3.0.2. I even installed a new 3.0.2 version to verify.

**Comment by bozana** [comment]
I am not sure if this might be the problem, but have you also install or update dependencies via NPM? -- It is now needed with using OJS 3.1 with git, s. also README:
# install [nodejs](https://nodejs.org/en/) if you don't already have it
npm install
npm run build

**Comment by bozana** [comment]
Oh, I see... you are right...

**Comment by bozana** [comment]
Was there the navigation link "Administration" for the admin user in OJS 3.0.2?

**Comment by dtwardy** [comment]
Yes. Before there were all options including Administration, now there's only Administration available on the left and no connection to the journal in case there's only one.

**Comment by bozana** [comment]
I mean in the top right navigation menu when being on the journal web page?

**Comment by dtwardy** [comment]
Yes. I check again later and can add screenshots.

**Comment by dtwardy** [comment]
I checked and can confirm that on the same server a fres OJS 3.0.2 installation shows the "Administration" link as well. Despite the triangle arrow there's not difference between 3.1.0 and 3.0.2. See attached screens.

Top right navigation (see URLs for differentiation):
![ojs3_user-drop_down](https://user-images.githubusercontent.com/13963250/32103562-3c0f2628-bb21-11e7-83ce-ed4530569acb.png)
![ojs31_user-drop_down](https://user-images.githubusercontent.com/13963250/32103565-3f0d0764-bb21-11e7-944e-2bb06f841c4d.png)

Administration backend (see URLs for differentiation):
![ojs3_administration](https://user-images.githubusercontent.com/13963250/32103587-6271c046-bb21-11e7-8540-0c837f1f1cb2.png)
![ojs31_administration](https://user-images.githubusercontent.com/13963250/32103595-668ca772-bb21-11e7-8fdb-62c919b211d9.png)

As of now there's no direct way to reaching journal specific settings when being on the general OJS administration page. You have to go back to the frontend and click on dashboard since that option isn't offered within top right navigation when using the backend.

**Comment by bozana** [comment]
Thanks a lot @dtwardy! I'll take a look...

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2973

**Comment by bozana** [comment]
@NateWr, could you take a look at this PR?
