### ISSUE TITLE
[OJS] OJS 3.1 fails to load user administration tools/table

### ISSUE THREAD

**Issue by dtwardy** [pkp/pkp-lib#2968]
I tried several setups but OJS 3.1 is reliably failing to show user administration tools. I can open user groups but not users. The module is simply not loading. I checked to rule out any misconfiguration on my server setups (I tried several) and OJS 3.0.2 works without issues.

Browser consoles logged the following errors, that might be related:

> GET http://localhost:8888/ojs31/styles/build.css net::ERR_ABORTED
contexts:11 GET http://localhost:8888/ojs31/js/build.js net::ERR_ABORTED
contexts?openWizard=1:11 GET http://localhost:8888/ojs31/js/build.js net::ERR_ABORTED
pkp.min.js:128 Uncaught ReferenceError: pkp is not defined
    at a.pkp.classes.Handler.bindGlobal (pkp.min.js:128)
    at a.pkp.controllers.grid.users.UserGridHandler [as constructor] (pkp.min.js:423)
    at a.pkp.classes.ObjectProxy.parent (pkp.min.js:119)
    at new a (pkp.min.js:117)
    at Function.a.pkp.classes.Helper.objectFactory (pkp.min.js:116)
    at HTMLDivElement.<anonymous> (pkp.min.js:443)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at n.fn.init.a.fn.pkpHandler (pkp.min.js:443)
    at HTMLDocument.eval (eval at <anonymous> (jquery.min.js:2), <anonymous>:3:61)
a.pkp.classes.Handler.bindGlobal @ pkp.min.js:128
a.pkp.controllers.grid.users.UserGridHandler @ pkp.min.js:423
a.pkp.classes.ObjectProxy.parent @ pkp.min.js:119
a @ pkp.min.js:117
a.pkp.classes.Helper.objectFactory @ pkp.min.js:116
(anonymous) @ pkp.min.js:443
each @ jquery.min.js:2
each @ jquery.min.js:2
a.fn.pkpHandler @ pkp.min.js:443
(anonymous) @ VM470:3
j @ jquery.min.js:2
add @ jquery.min.js:2
n.fn.ready @ jquery.min.js:2
n.fn.init @ jquery.min.js:2
n @ jquery.min.js:2
(anonymous) @ VM470:2
(anonymous) @ jquery.min.js:2
globalEval @ jquery.min.js:2
domManip @ jquery.min.js:3
append @ jquery.min.js:3
(anonymous) @ jquery.min.js:3
n.access @ jquery.min.js:3
html @ jquery.min.js:3
a.pkp.classes.Handler.html @ pkp.min.js:134
a.pkp.controllers.UrlInDivHandler.handleLoadedContent_ @ pkp.min.js:203
(anonymous) @ pkp.min.js:124
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
x @ jquery.min.js:4
b @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.(anonymous function) @ jquery.min.js:4
a.pkp.controllers.UrlInDivHandler.reload @ pkp.min.js:202
a.pkp.controllers.UrlInDivHandler @ pkp.min.js:202
a.pkp.classes.ObjectProxy.parent @ pkp.min.js:119
a @ pkp.min.js:117
a.pkp.classes.Helper.objectFactory @ pkp.min.js:116
(anonymous) @ pkp.min.js:443
each @ jquery.min.js:2
each @ jquery.min.js:2
a.fn.pkpHandler @ pkp.min.js:443
(anonymous) @ VM469:4
j @ jquery.min.js:2
add @ jquery.min.js:2
n.fn.ready @ jquery.min.js:2
n.fn.init @ jquery.min.js:2
n @ jquery.min.js:2
(anonymous) @ VM469:3
(anonymous) @ jquery.min.js:2
globalEval @ jquery.min.js:2
domManip @ jquery.min.js:3
append @ jquery.min.js:3
(anonymous) @ jquery.min.js:3
n.access @ jquery.min.js:3
html @ jquery.min.js:3
success @ pkp.min.js:443
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
x @ jquery.min.js:4
b @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
a.fn.pkpAjaxHtml @ pkp.min.js:443
a.pkp.controllers.modal.AjaxModalHandler.modalOpen @ pkp.min.js:327
a.pkp.controllers.modal.ModalHandler @ pkp.min.js:314
a.pkp.classes.ObjectProxy.parent @ pkp.min.js:119
a.pkp.controllers.modal.AjaxModalHandler @ pkp.min.js:326
a.pkp.classes.ObjectProxy.parent @ pkp.min.js:119
a @ pkp.min.js:117
a.pkp.classes.Helper.objectFactory @ pkp.min.js:116
(anonymous) @ pkp.min.js:443
each @ jquery.min.js:2
each @ jquery.min.js:2
a.fn.pkpHandler @ pkp.min.js:443
a.pkp.classes.linkAction.ModalRequest.activate @ pkp.min.js:141
a.pkp.controllers.linkAction.LinkActionHandler.activateAction @ pkp.min.js:336
a.pkp.classes.Handler.handleEvent @ pkp.min.js:124
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

**Comment by bozana** [comment]
How did you install OJS 3.1? -- It feels like something is missing for you... -- I have no such problems...

**Comment by dtwardy** [comment]
Code from github, checked out ojs-stable-3_0_0 branch, updated submodules, ran composer on the three specified folders just as the instructions noted. The issue was present on a local MAMP stack as well as on a Debian VM with a full Apache service that never had any issues with 3.0.0, 3.0.1 or 3.0.2.

**Comment by dtwardy** [comment]
I see. Composer AND mom are required. I'll check again later.

**Comment by dtwardy** [comment]
Ok, my bad. It wasn't clear to me that composer and npm were both required. After installing those dependencies it is working now and the user administration panel is being displayed. 

May I suggest though to make it clearer that both package managers are mandatory? Could be only me who misunderstood those instructions but I wouldn't be surprised if I wasn't.
