### ISSUE TITLE
[OJS] 

### ISSUE THREAD

**Issue by SunilLsagar** [pkp/pkp-lib#2969]
Warning: require(./lib/pkp/includes/bootstrap.inc.php): failed to open stream error is coming how to fix it please help me

**Comment by asmecher** [comment]
@SunilLsagar, I suspect you are working with OJS from git. There are instructions [here](https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors) for how to do that. Next time, please post questions on our [support forum](http://forum.pkp.sfu.ca/).
