### ISSUE TITLE
[OJS]Usability improvement: registration as author

### ISSUE THREAD

**Issue by felixgruender** [pkp/pkp-lib#297]
Often users who want to register as "author" erroneously register as "reader" because the "register as"-section is placed quite unremarkably at the bottom of the registration form (and "reader" is activated by default).
Thus these "authors" (who are then just "readers" in fact) are wondering why they can't make submissions etc...

To solve this problem, one could:
1) place the "register as"-section on the top (and not at the bottom) of the registration page (to make it more eye-catching) or
2) activate not only "reader", but also "author" by default.

Best regards,
Felix

**Comment by asmecher** [comment]
Felix, activating "author" by default would poison the author pool and I think it's important to some journals that they know who their authors are. Another option would be to help the system guide the right form defaults by providing hints based on where they're registering from -- for example, if they are viewing the "About > Submissions" area, then they're likely an author; likewise, if they're redirected from trying to view content that requires registration to read, then they're likely a reviewer.

**Comment by felixgruender** [comment]
Alec, thanks for your advice!
Just some remarks:
1) As for your suggestion to pre-select "author" only if there is an adequate referrer (about/submissions, or information/authors): yes, that makes sense in any case!
2) In addition, couldn't it be useful to place the "register as" section on the top of the registration form?
3) I'm not quite sure if a user can be identified as reviewer when he tries to view content that requires registration (couldn't it be possible that it's just a reader?)
Moreover, in this case the user isn't redirected to the registration form, but to the login page.

Best regards,
Felix

**Comment by asmecher** [comment]
Felix, I don't see the pull request; could you drop a link here?

**Comment by felixgruender** [comment]
Alec, that's the pull request: https://github.com/pkp/ojs/pull/413
Back then you suggested to keep it as a local modification and therefore closed this pull request.

**Comment by asmecher** [comment]
Ah, of course, thanks. I don't remember much of what happened before Monday.

**Comment by lilients** [comment]
Hi @asmecher ,

as you know, I took over from Felix and need to finish this task. 🏁 We have a very simple solution to the problem described. We would like to make the selection of a role mandatory and remove the default check of the reader role, so the user has to select to role on purpose. 

![img](https://raw.githubusercontent.com/lilients/img/master/registerAs.PNG)
Would that be a solution you would add to OJS 2? 

This way no registration without role would be possible. If that is wanted, I could add a checkbox "no role".

Best,
Svantje

**Comment by asmecher** [comment]
Hi @lilients -- we don't currently have any OJS 2.x releases planned (i.e. we're planning to react to demands, such as PHP7 support, but haven't hit one yet). All of our UI/UX type improvements are focusing on OJS 3.x. I think this is an OK proposal, but maybe best left as a local modification? Meanwhile we can try to make sure that the situation is improved longer-term in OJS 3.x.
