### ISSUE TITLE
Untranslated locale keys in Roles select menu

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#2972]
Using a new OJS 3.1 instance installed via git.

![roles](https://user-images.githubusercontent.com/200793/32112752-17509854-bb0c-11e7-9ae1-628ea2f6c57a.png)

**Comment by asmecher** [comment]
From `ojs-stable-3_1_0` or `master`?

**Comment by mfelczak** [comment]
ojs-stable_3_1_0

**Comment by mfelczak** [comment]
for both the ojs and pkp-lib repos

**Comment by asmecher** [comment]
@defstat, any ideas?

**Comment by asmecher** [comment]
Committed to both `ojs-stable-3_1_0` and `master`. For OJS 3.1.0, apply https://github.com/pkp/pkp-lib/commit/92bba5fdec1d056634c986e21338c9b6091f896c in `lib/pkp` and https://github.com/pkp/ojs/commit/6fe1663de8eb21a59821f9bce79c66be01c6c473 in the base directory.

**Comment by mfelczak** [comment]
Thanks @asmecher . It looks like 92bba5f includes 'Press Assistant' which sounds OMP-specific -- should this not be just 'Assistant' for OJS?

**Comment by asmecher** [comment]
Oops -- corrected, thanks (also squinting at as many of the locales as I can).
