### ISSUE TITLE
Citation Style plugin throws error for all users that are not logged in

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#2977]
When trying to change a citation style when not logged in:

`PHP Fatal error:  Uncaught Error: Call to a member function hasRole() on null in C:\\xampp\\htdocs\\site2\\plugins\\generic\\citationStyleLanguage\\pages\\CitationStyleLanguageHandler.inc.php:114\nStack trace:\n#0 C:\\xampp\\htdocs\\site2\\plugins\\generic\\citationStyleLanguage\\pages\\CitationStyleLanguageHandler.inc.php(36): CitationStyleLanguageHandler->_setupRequest(Array, Object(Request))\n#1 C:\\xampp\\htdocs\\site2\\lib\\pkp\\classes\\core\\PKPRouter.inc.php(372): CitationStyleLanguageHandler->get(Array, Object(Request))\n#2 C:\\xampp\\htdocs\\site2\\lib\\pkp\\classes\\core\\PKPPageRouter.inc.php(233): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)\n#3 C:\\xampp\\htdocs\\site2\\lib\\pkp\\classes\\core\\Dispatcher.inc.php(134): PKPPageRouter->route(Object(Request))\n#4 C:\\xampp\\htdocs\\site2\\lib\\pkp\\classes\\core\\PKPApplication.inc.php(243): Dispatcher->dispatch(Object(Request))\n#5 C:\\xampp\\htdocs\\site2\\index.php(68): PKPApplication->execute()\n#6 {main}\n  thrown in C:\\xampp\\htdocs\\site2\\plugins\\generic\\citationStyleLanguage\\pages\\CitationStyleLanguageHandler.inc.php on line 114, referer: http://localhost/index.php/psp/article/view/73`

Obviously, the error goes from theses lines:
`if ($user->hasRole([ROLE_ID_SUB_EDITOR, ROLE_ID_ASSISTANT], $contextId)) {`
`if ($user->hasRole(ROLE_ID_MANAGER, $contextId)) {`
When the user is not logged in, `$user` variable is null.

**Comment by NateWr** [comment]
Fixed with https://github.com/pkp/ojs/commit/9538dc257209b061b70c379c2a6bc089e30aa825 and https://github.com/pkp/citationStyleLanguage/pull/8
