### ISSUE TITLE
[OJS] authors not should be able to upload image in abstract

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#2979]
When the author is submitting a manuscript is able to upload an image, and this is saved in /public folder. Maybe this option can make disabled for the authors or at all; I can imagine that is possible one editor in one case very uncommon decide to use an image in an abstract but is not common. But for the authors is just a distraction. 

In this picture, an author upload two very big maps, I do not why but is possible some other authors make mistakes too. 
 
![image](https://user-images.githubusercontent.com/5422984/32154906-bdca4fba-bd12-11e7-8faf-6da06d8976fa.png)

**Comment by t4x0n** [comment]
Maybe a change in the TinyMCE Plugin, make the possibility of disabling some buttons in some textareas.

**Comment by asmecher** [comment]
@t4x0n, you could look at an approach similar to the one used in https://github.com/pkp/ojs/pull/1205 (but removing the JBImages tool for author accounts, not just logged-out user accounts).

Our overall strategy is going to be removing the JBImages plugin entirely at some point, in favour of another approach -- so fine-tuning the current approach is not a high priority for the team. PRs on this would be welcome.

**Comment by t4x0n** [comment]
@asmecher I was trying to generate another toolbar for the TinyMCE without JBImages tool, but I cannot be made it, maybe I will try again later. Thank you for the reply!

**Comment by NateWr** [comment]
This form was replaced in OJS 3.2 with the new publication forms and the image upload no longer appears.
