### ISSUE TITLE
Navigation Menus - not all default NMIs get translated upon install/upgrade

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#2987]
See also https://forum.pkp.sfu.ca/t/ojs-3-0-2-3-1-main-menu-is-corrupted/34668.
Possibly a case of AppLocale::requireComponents missing locales.

**Comment by defstat** [comment]
@asmecher
PRs:
pkp-lib: #2995
OJS: pkp/ojs#1655
OMP: pkp/omp#460

**Comment by asmecher** [comment]
Looks good, @defstat, please go ahead (and back-port if you're comfortable with this on the stable branch).

**Comment by defstat** [comment]
@asmecher 
PRs ojs-stable-3_1_0:
pkp-lib: #3023
OJS: pkp/ojs#1668

**Comment by asmecher** [comment]
@defstat, this looks good, please go ahead (and port as needed -- not just to OJS and pkp-lib master, but also to OMP).

**Comment by defstat** [comment]
@asmecher the later comment is for ojs-stable. The master branch PR are at https://github.com/pkp/pkp-lib/issues/2987#issuecomment-340827963. Should I do something for OMP too, except the master?

**Comment by asmecher** [comment]
Just for OMP master branch, @defstat!

**Comment by defstat** [comment]
@asmecher the OMP master branch had been updated along with the OJS master branch. [https://github.com/pkp/pkp-lib/issues/2987#issuecomment-340827963]. I rebased everything just now.

**Comment by asmecher** [comment]
All merged, thanks!

**Comment by defstat** [comment]
@asmecher The ojs-stable-3_1_0 PRs did not got merged. So I am afraid that the 3.1.0-1 does not have the changes.

**Comment by asmecher** [comment]
Yuck -- yes, it looks like I missed the `ojs-stable-3_1_0` PRs. Sorry, @defstat. Merged now.
