### ISSUE TITLE
Reveal more handler can fail to reveal more

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2994]
Some edge case resulted in the `max-height` property not being removed to reveal more. I've never been able to replicate this but it was reported here:

https://forum.pkp.sfu.ca/t/reviewer-comments-overlapped/33141/5?u=natewr

They [suggested](https://forum.pkp.sfu.ca/t/reviewer-comments-overlapped/33141/7?u=natewr) a change which seems like it would do the trick and not have any side-effects:

Change: `this.getHtmlElement().removeClass(‘isHidden’).css(‘max-height’, ‘auto’);`
To: `this.getHtmlElement().removeClass(‘isHidden’).removeAttr( ‘style’ );`

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/3085

Tests:
https://github.com/pkp/ojs/pull/1713
https://github.com/pkp/omp/pull/475

@bozana can you code review?

**Comment by bozana** [comment]
@NateWr, that looks good to me :wink: I do not know why you tests are failing :-O
I will merge it and then try to repair that JS linting error...

**Comment by bozana** [comment]
Can the issue be closed?

**Comment by NateWr** [comment]
Thx!
