### ISSUE TITLE
[OJS] Overriding locales with theme plugins always requires en_US locale in the theme folder

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2997]
OJS 3.0.2 and probably later as well.

This is not maybe a bug, but could be maybe fixed fairly easily.

If you want to override a locale key or create a custom locale key in OJS3 theme plugin, then you always seem to need a en_US locale file even if the default locale for the journals is something different.

**Comment by asmecher** [comment]
I think there are a couple things here that are potentially "out of spec"...
- Plugins without `en_US` locales. Some areas of the system (e.g. the translator plugin) expect English to be always available.
- Plugins overriding built-in locale keys. There was a recent discussion about this on the forum, but basically, whether or not locale keys can be overridden predictably will depend a lot on when the locale files are loaded, and in what order, and we haven't coded any guarantees about this yet. A "safe" mechanism for this may be needed.
