### ISSUE TITLE
[OJS] Archiving page changes 

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#2998]
OJS's archiving administration page should be able to change its functionality depending on PLN Plugin's state (installed/enabled)

**Comment by defstat** [comment]
@asmecher 
PR:
OJS: pkp/ojs#1509

**Comment by defstat** [comment]
I have changed the wording. I think I have changed all occurrences of 'PLN' to 'PL', along with the above mentioned changes.

Regarding the 'PLN Enabled' check box shown even though the PLN Plugin is not installed, unfortunately i have tried to reproduce it, but I couldn't. I get 

![pln](https://user-images.githubusercontent.com/560456/33388695-4fb775c2-d539-11e7-90b8-437371d5cf04.png)

After moving the pln folder in the plugins/generic folder I get 

![image2-pln](https://user-images.githubusercontent.com/560456/33388709-58d72b34-d539-11e7-8ab1-af86d32c46b3.png)

and a new row in the database, table versions [product: 'pln', product_class: 'PLNPlugin', current: 1]

Then, if I delete the plnPlugin from the OJS plugin management page, the pln plugin folder is removed from the file system and the above database row is updated to [current: 0]

The screenshot after that is the same as the first one.

Do we need another functionality for that?

**Comment by mjordan** [comment]
@defstat wording looks great. Running a `grep -r PLN` against the 3.x codebase should reveal any instances if there any left.

On the not installed issue, let me test again, paying attention to the plugins table. I'll try to do that today and will report back here.

**Comment by mjordan** [comment]
Woops, I just noticed in the "plugin in uninstalled" wording we have "PKP PLN plugin". That should be "PKP PN plugin".

**Comment by defstat** [comment]
@mjordan Do you mean when you uninstall the PLN Plugin? If yes I have not made any changes on that in this PR.

**Comment by mjordan** [comment]
No, when I tested, I had never cloned it into the `plugins/generic` folder. But, I'll test that state, when it's installed but not enabled, and also after I've uninstalled the plugin and document what I see.

**Comment by bronwens** [comment]
@defstat Thanks for updating the wording! Could you please add “The” before PKP Preservation Network at the beginning of both sentences (in the red boxes)?

**Comment by defstat** [comment]
@bronwens I changed the wording.

**Comment by asmecher** [comment]
@defstat, this looks good, but one big change is still needed -- many of the additions went into `pkp-lib`, which means they would also ship with OMP. I think pretty much everything here needs to apply only to OJS, correct?

**Comment by defstat** [comment]
@asmecher yes I think so.

**Comment by asmecher** [comment]
OK, the code needs to be ported into `ojs` rather than `pkp-lib` as much as possible.

**Comment by mjordan** [comment]
@asmecher we haven't started talking about it in a formal way, but we might want to allow OMP content into the PN some time in the future. Would it make sense to leave it in the pkp-lib as long as it didn't interfere with OMP otherwise?

**Comment by asmecher** [comment]
No objection, but I don't think these changes were written with release in OMP in mind. @defstat, how will these changes behave in OMP at the moment? Neither plugin is available for OMP, so there shouldn't be any visible reference to them OMP-side.

**Comment by defstat** [comment]
@asmecher the changes in pkp-lib are in ArchivingForm.inc.php and its related code (archivingForm.tpl and ArchivingSettingsFormHandler.js), which are not referenced in OMP. 

There has been a change in SettingsTabHandler.inc.php (https://github.com/pkp/pkp-lib/pull/2741/files#diff-d31c18ebfda449d7e1edc8db02eb121bR135), but I don't see someplace where that can effect OMP.

**Comment by asmecher** [comment]
@defstat, thanks, that makes sense; I forgot that OMP doesn't use the archiving form, even though it's in pkp-lib. I think we're ready to go.

Could you...
- Interactively rebase, and squash the commits into something shorter
- Change the commit messages to include the issue (e.g. `pkp/pkp-lib#1234 Some Description Here`)
- Commit and back-port to `ojs-stable-3_1_0`

Thanks!

**Comment by defstat** [comment]
@asmecher 

New PRs

**Master**
pkp-lib: #3150
OJS: pkp/ojs#1744

**Comment by defstat** [comment]
@asmecher 

**Stable**
pkp-lib: #3151
OJS: pkp/ojs#1745

**Comment by mjordan** [comment]
I won't get a chance to test this until the weekend (at a conference).

**Comment by asmecher** [comment]
@mjordan, I'm hoping to release 3.1.0-1 today, or it'll have to wait at least a week.

**Comment by asmecher** [comment]
Executive decision :) All merged. OJS 3.1.0-1 is on its way out the door.

**Comment by mjordan** [comment]
Just gave 3.1.0-1 (from tarball) a smoke test and everything looks good:

Plugin not present:

![pln_plugin_not_installed](https://user-images.githubusercontent.com/403918/33520676-88ebdaf8-d774-11e7-9ec0-975b663385f5.png)

Plugin present:

![pln_plugin_present](https://user-images.githubusercontent.com/403918/33520678-9202269c-d774-11e7-89cc-d56494beb75d.png)

Thanks!
