### ISSUE TITLE
Enabled plugins disabled after upgrade

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3002]
In the original OJS 3.0.2 install, the journal had enabled the custom block manger plugin which was then disabled following the upgrade to OJS 3.1

**Comment by asmecher** [comment]
@mfelczak, where can I find pre- and post-upgrade DB dumps for the journal?

**Comment by bozana** [comment]
This function could eventually be responsible for that: https://github.com/pkp/ojs/blob/master/classes/install/Upgrade.inc.php#L2439
If it is a site-wide plugin and if there was no plugin setting with setting_name = enabled, setting_value = 1 and context_id = 0 ... but I wonder why it was not there... However, maybe it is then correct so now -- now for site-wide plugin there should only be that setting i.e. only for context = 0, and for no other contexts...

**Comment by mfelczak** [comment]
Hi @asmecher, I'll ping you offline with the details.

**Comment by asmecher** [comment]
@bozana, could this also be a side-effect of https://github.com/pkp/pkp-lib/issues/1859 (e.g. https://github.com/pkp/customBlockManager/pull/21)?

**Comment by asmecher** [comment]
It looks like the 3.0.2 install had the custom block manager enabled in the DB for both context_id 0 (site-wide) and 1 (the journal).

**Comment by bozana** [comment]
Hmmm.... I think this plugin seems to be a special case, s. https://github.com/pkp/customBlockManager/blob/ojs-3_1_0-0/CustomBlockManagerPlugin.inc.php#L163.

**Comment by bozana** [comment]
Maybe then I should exclude that plugin from that upgrade SQL... ?

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1660

**Comment by bozana** [comment]
@asmecher, the other solution could maybe be to say that this plugin is a site plugin and to only save the blocks for specific contexts. But for some reason, when I wanted to try that out, the LoadComponentHandler hook is not registered properly i.e. the callback not called... and I cannot figure out why... :-\

**Comment by asmecher** [comment]
@bozana, are you working with an upgraded DB? If so, I wonder if the move from context-specific to site-wide plugin is reflected in the `versions` table -- is the `sitewide` flag set properly?

**Comment by bozana** [comment]
Aaaaa... good point, I'll check... 👍

**Comment by bozana** [comment]
Juhuuuuuuu, juhuuuuuuu, juhuuuuuuu... :tada: :fireworks: :dancer: :sparkles: :star: :triumph:

**Comment by bozana** [comment]
@asmecher, above are the new correct PRs. Could you take a look? OK so?

**Comment by bozana** [comment]
Ah, as @asmecher said, this plugin cannot be made only side-wide, because the journal managers without admin rights will not be able to use it. Thus the first solution, not to consider this plugin as side-wide in the upgrade is the only one.

**Comment by bozana** [comment]
Sorry, @asmecher, could you than take a look at these PRs:
ojs master: pkp/ojs#1660
ojs ojs-stable-3_1_0: pkp/ojs#1661

**Comment by asmecher** [comment]
Looks good -- thanks, @bozana. Is the problem with the custom block manager filed and open? @NateWr, not sure if you're following that conversation.

**Comment by bozana** [comment]
The custom block manager stays as it is -- the fix has to be done in the upgrade script.
Unfortunately this means some work for those already migrated and using the custom block manager -- they will have to manually enable it for journals they need...
