### ISSUE TITLE
remote galley and supp files are not displayed on the article page

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3007]
s also https://forum.pkp.sfu.ca/t/ojs-3-1-wont-show-remote-galleys/34816

**Comment by bozana** [comment]
@NateWr, should remote galleys and supp files be displayed in the same way as the others (just that they will call another URL)?

**Comment by NateWr** [comment]
Oooh... that's an oversight! And we have no way to determine if it represents a primary or supplementary galley. I suppose treated it visually as supplementary? Or maybe add an option to remote galleys to select the article component type?

**Comment by bozana** [comment]
Hmmm... yes, unfortunately... If we would add the component type to the remote galleys, how could we save it -- in the DB table submission_galley_settings?

**Comment by ronniebrito** [comment]
in our case it is always a final/primary galley, so adding ** an option to remote galleys to select the article component type** is a better option... 

We need a `pragmatic` solution, as our site needs to enter production soon. Changing the $galleys populating method seems to be easier than changing database, so could you tell me in what part of OJS code can I change this behaviour?

thank you

**Comment by NateWr** [comment]
> in the DB table submission_galley_settings?

I guess? I'm not that clear on how we determine galley type, but I imagine it will complicate some of the calls we have to the galley DAOs throughout the system, since we can't rely on a File existing to check the component type. 

https://github.com/pkp/ojs/blob/master/pages/article/ArticleHandler.inc.php#L106-L126

This might be a good candidate for a function in the `GalleyService` class for getting galleys, which would encapsulate some of this logic in a reusable way so we can consolidate how we're getting and grouping galleys.

**Comment by NateWr** [comment]
Oh, and @ronniebrito, the link above shows where the galleys are fetched for the article details view on the frontend.

**Comment by bozana** [comment]
According to the recent discussion also the remote supp file metadata are wished to be saved in the system...

**Comment by ronniebrito** [comment]
thank you @NateWr ,

in our situation a remote galley (that don`t has a file) is always a primary galley, so just changing code as follow worked fine

```
foreach ($galleys as $galley) {
				$file = $galley->getFile();
				if (!$file) {				
                                        $primaryGalleys[] = $galley;
					continue;					
				}
				if (in_array($file->getGenreId(), $primaryGenreIds)) {
					$primaryGalleys[] = $galley;
				} elseif (in_array($file->getGenreId(), $supplementaryGenreIds)) {
					$supplementaryGalleys[] = $galley;
				}
			}
```

**Comment by mfelczak** [comment]
Just adding a "me too" to @ronniebrito's remarks, we also have a client who is using remote URLs as primary galleys.

**Comment by bozana** [comment]
@NateWr, what do you think about remote files? Maybe only for the representation files? At the moment I do not have an overview in my head what would then mean for other functions in the system, but... I will think about it more...

**Comment by NateWr** [comment]
@bozana Do you mean a new subclass of `SubmissionFile`?

**Comment by bozana** [comment]
I mean to have that option/possibility for files -- to store it (remoteURL) for a file and not for a representaiton... I cannot think of consequences fully -- e.g. to have such an entry in the DB table submission_files, where there is actually no real file in the system there, because it is a remote file... Hmmm...

**Comment by NateWr** [comment]
I've decided to split the bigger issue of giving remote galleys a file component type and metadata into a different issue: https://github.com/pkp/pkp-lib/issues/3254.

This issue will focus on making sure remote and supplementary files are displayed on the article page for 3.1.1. Remote galleys will be treated as primary galleys.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/1787

@asmecher can you code review? Tests still running.

(And if anyone who's had this issue can test the PR that'd be great!)

**Comment by NateWr** [comment]
Tests passed.

**Comment by asmecher** [comment]
Looks good -- thanks, @NateWr. Does this need updating in plugins?

**Comment by NateWr** [comment]
Done. Closing.
