### ISSUE TITLE
Localization for placeholder attribute in fbvElement

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3008]
Right now the fbvElement of type _text_ supports automatic localization of the _label_ attribute. So you only have to enter the key of the specific item of the locale and get the localized message.

When you want to add a _placeholder_ for the input you are always adding the literal string as the placeholder. So you either have to hardcode the placeholder value or have to pass in the message from the locale as a template variable. It is totally possible to do it like that but I find it's not very straight forward.

I would suggest to handle the placeholder of a fbvElement of type text the same way as the label value. What do you think?

**Comment by asmecher** [comment]
@MarHerUMR, could you point me to an example or two?

**Comment by MarHerUMR** [comment]
@asmecher sure.

I'm working on a plug-in adding meta tags for Twitter Cards and the open graph protocol. One of the items for Twitter Cards is the _twitter:site_ property. On the settings form you should be able to state the Twitter handle the Twitter Card should be attributed to. So right now I have a _fbvElement_ of type _text_ with the label translating to "The Twitter username the card should be attributed to." As a placeholder I would want to have something like "Enter the twitter handle without the @.".

It would be great when this placeholder could use the same localization mechanism like the label.

I think that it would help to decouple the request for what goes into a textfield from the format you should be using. Right now you would add any hints about the format to the label of the textfield. This "wastes" some screen space because the information about the format isn't so important when you have already entered a value. Maybe a form could gain some readability/clarity by making the use of placeholder easier.

**Comment by asmecher** [comment]
Sure, I think that's a good idea. Note that we're not especially happy with the form builder vocabulary toolset, and are liable to replace it down the road, but this is a minor change that could be accommodated in whatever replaces it.

**Comment by MarHerUMR** [comment]
Fixed by #3079
