### ISSUE TITLE
always provide multipleContexts variable

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3009]
The variable multipleContexts is provided to the header.tpl only here: https://github.com/pkp/pkp-lib/blob/master/pages/admin/AdminHandler.inc.php#L67.
Thus these cases are not considered when the admin user is in a journal/press backend: 
https://github.com/pkp/pkp-lib/blob/master/templates/common/header.tpl#L37
https://github.com/pkp/pkp-lib/blob/master/templates/common/header.tpl#L109

The variable name suggests that it should be always set if there are several journals/presses in the one installation.

There is also one case where the current situation (having the Administration page within the journal/press backend) is a little bit confusing: when Site Settings > Plugins > Custom Block Manager is used: because it is used within the journal/press context it will be saves as a journal/press custom block. 

Thus, I will change the variable to be always set, in PKPTemplateManger class, and thus for those lines in the header.tpl above to be considered. This will make the "Administration" link in the journal/press backend to be always have the site/index path URL in a multiple-journal/multiple-press installation, as this is currently the case in the user nav.

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3010
ojs master: https://github.com/pkp/ojs/pull/1659 (only submodule update)

**Comment by bozana** [comment]
@NateWr, could you take a look at the PR? 
If OK, I'll cherry-pick it to ojs-stable-3_1_0.

**Comment by NateWr** [comment]
Not sure what the test issues are but the PR looks good. :+1:
