### ISSUE TITLE
[OJS] Plugin upgrade form broken after error

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#301]
The plugin upgrade web form does not work after an error.

To reproduce:

1. Set the tar command to an incorrect path in config.inc.php.
1. Attempt to upgrade a generic plugin via the web interface by uploading a .tar.gz file.
1. Note the error about the incorrect path to tar. The web form is displayed again.
1. Correct the path to tar in config.inc.php.
1. Use the form on the error page to try to upload the plugin again. 

Expected results: The plugin should upgrade successfully.
Actual results: A confusing error message:  "The uploaded plugin does not fit the category of the upgraded plugin."

**Comment by asmecher** [comment]
Fixed -- thanks for reporting.
