### ISSUE TITLE
REST API sends wrong http status code on authorization failure

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3014]
Yesterday I wanted to play a little with the REST API. Initially I wasn't really shure if I was handling the API endpoint URLs right because I kept getting 404 errors. Later I pasted the endpoint URL into the browser (where I was logged in) and got the requested data. So I think the problem isn't the endpoint URL, but it is a failed authorization.

I had a look into the APIRouter:

```
	/**
	 * @copydoc PKPRouter::handleAuthorizationFailure()
	 */
	function handleAuthorizationFailure($request, $authorizationMessage) {
		$dispatcher = $this->getDispatcher();
		$dispatcher->handle404();
	}
```

So the user is getting a _page not found_ error, even when the resource is actually there, but the user isn't unauthorized.

I think the user should get a 401 error instead of the 404. Or a least a 403. This would really improve the search for errors when dealing with the REST API.

**Comment by NateWr** [comment]
Hi @MarHerUMR, I just wanted to drop you a quick response. This is a known issue with our current authorization framework -- it wasn't designed to send back error response codes with a REST API, and so needs some deep plumbing to be refactored for use with our API. Kassim is looking into this, but in the meantime the error messages from the API are fairly limited.

**Comment by kaschioudi** [comment]
https://github.com/pkp/pkp-lib/pull/3035
https://github.com/pkp/ojs/pull/1676

@asmecher @NateWr 

Since a policy can return `AUTHORIZATION_DENY`under multiple circumstances, the idea here is to set an error code (`AUTHORIZATION_ERROR_BAD_REQUEST`, `AUTHORIZATION_ERROR_FORBIDDEN `, `AUTHORIZATION_ERROR_NOT_FOUND `) depending of the issue. I went through all policies and set error codes. I believe it would be great if someone else could take a second look to verify the error codes being set.

**Comment by NateWr** [comment]
I just had a very quick glance. The status codes look good, but we're still replying with HTML code. Is there any way to allow the API to respond with JSON, and for us to be able to inject a useful error message with the API response?

**Comment by kaschioudi** [comment]
@NateWr @asmecher Here are links to new PRs. 

https://github.com/pkp/pkp-lib/pull/3065
https://github.com/pkp/ojs/pull/1698

**Comment by kaschioudi** [comment]
> I just had a very quick glance. The status codes look good, but we're still replying with HTML code. Is there any way to allow the API to respond with JSON, and for us to be able to inject a useful error message with the API response?

looking into this.

**Comment by kaschioudi** [comment]
@NateWr See https://github.com/kaschioudi/pkp-lib/commit/17f3330238dd50efa26ba758e6797fe1396743b6

**Comment by NateWr** [comment]
🎉

**Comment by NateWr** [comment]
I think @asmecher will need to do the code review on this since I'm not great on the authorization stuff. But really happy to be able to deliver proper error messages with the REST API.

**Comment by asmecher** [comment]
@kaschioudi, did you run into the authorization framework's "advice" construct? I suspect it'll be possible to extend that rather than implementing another strategy. See e.g. the constructor in `lib/pkp/classes/security/authorization/internal/SubmissionRequiredPolicy.inc.php`.

**Comment by kaschioudi** [comment]
@asmecher I have explored `setAdvice()` feature and did not use it because it's not granular in the sense that the call back function will get called whenever there's a denial. But it won't be possible to distinguish between 400, 403 and 404 errors.

**Comment by NateWr** [comment]
This was implemented as part of https://github.com/pkp/pkp-lib/issues/3594. The API now returns `403` with an authorization failure.
