### ISSUE TITLE
New article components have NULL entry_key

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3015]
When I add new article components in OJS 3.1 the entry_key is set to NULL in the genres table. It's not possible to then use GenreDAO::getByKey to retrieve these new entries.

**Comment by bozana** [comment]
Is this then a problem somewhere?

**Comment by mfelczak** [comment]
Hi @bozana, I'm writing a plugin where I'd like to retrieve a custom article component by key.

**Comment by bozana** [comment]
Does the plugin then uses a controlled set of keys? -- just interested in requirements/cases...

**Comment by mfelczak** [comment]
Hi @bozana, a new article component would be created manually and then the component would be fetched by key within the plugin. That being said, another acceptable approach would be to create the article component within the plugin and then set/save the key for future retrievals.

**Comment by bozana** [comment]
@asmecher, do you think it would be a good solution to enable the editing/inserting of the custom keys for custom genres/components? I think they cannot be used in the core code -- because we do not know what they could be -- but maybe it will be helpful for other plugins that would need it?

**Comment by asmecher** [comment]
Hmm, I don't generally want to rely on keys for much, but I agree that plugins are a valid case.

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3031
ojs master: https://github.com/pkp/ojs/pull/1673 (only submodule update)

**Comment by bozana** [comment]
@mfelczak, would you like or could you test the PR?

**Comment by bozana** [comment]
One question maybe: I allow all characters for genre/component keys. Do you maybe see any problem in there? -- e.g. when I check that they are unique. @asmecher, @mfelczak ?

**Comment by bozana** [comment]
@asmecher, could you code review the PR above?

**Comment by mfelczak** [comment]
Hi @bozana, given that it's been possible to add new components with NULL keys up until now, allowing empty keys would follow that pattern. That being said we could always check that non-NULL keys are still unique so that lookup by non-NULL key will return a single result.

**Comment by bozana** [comment]
Yes, I see it the same way. Thanks @mfelczak!

**Comment by asmecher** [comment]
I'd also suggest encouraging the same limitations on these keys that we use elsewhere for symbolic names, e.g. see the regexp in `ContextSiteSettingsForm.inc.php`.

**Comment by asmecher** [comment]
Thanks, just a few comments!

**Comment by bozana** [comment]
Thanks @asmecher! I made the changes you have suggested and will merge when the tests pass...
