### ISSUE TITLE
supplementary files migration 

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3016]
The supp files in OJS 2.4.x had the filestage = 6 (ARTICLE_FILE_SUPP). 
When migrated to OJS 3.x those files get filestage = 2 (SUBMISSION_FILE_SUBMISSION). This leads to an error when the editor clicks on "Change File" galleys grid row action. 
Thus, the file stage of supp files should be changed to 10 (SUBMISSION_FILE_PROOF) when migrating to OJS 3.x. That would mean that they are not visible in the Submission Files grid.

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1667

**Comment by bozana** [comment]
@asmecher, could you take a look? Do you agree that those files should have the file stage = 10 (SUBMISSION_FILE_PROOF) instead of 2 (SUBMISSION_FILE_SUBMISSION)? Do you see any reason why it is not good to only have them in the Galley grid and not in Submission Files grid? THANKS!!!

**Comment by ajnyga** [comment]
Just wanted to know if this affects updating from 3.0.2/3.1 to 3.1.1?

And while I am here: I do not see any problem in storing the suppfiles only in the Galleys grid because in OJS2 there was no difference between the supplementary files in the submission stage and the production stage (can not remember the OJS2 terminology anymore). Connected to this is the problem that many OJS2 journals store sensitive data to the supplementary files, because they do not show up in the front end if the reader tools are disabled. Of course you can access them even without reader tools, but not without some knowledge of the system. So basically the OJS3 upgrade probably reveals sensitive supplementary files for many journals.

**Comment by bozana** [comment]
@ajnyga, yes, it affects that upgrade from 3.0.2/3.1 to 3.1.1.
And yes, the supp files are presented on the article page...

**Comment by ajnyga** [comment]
Ok. Because it turned out during our update that most of the supplementary files the journals had were not intended to be published. I could imagine this is the case also with a lot of other OJS2 journals as well.

So what I did is that I cretead excel lists of the supplementary files and asked all journals to check which files are meant to be public (not a lot of them were). Using these lists I did a small post upgrade script that remvoved the unwanted files from the galleys grid which I ran after the OJS2=>OJS3 upgrade in January. Meaning that I only removed the galley link - leaving all the files visible in the submission stage grid. 

So if I am reading this issue right, the suggested change would remove those unlinked files also from the submissions grid. Which is a bit problematic to some of our journals because with OJS2 they used the supplementary files feature to store some editorial documents (agreements etc.) and with this update those would be lost (because representing them in the galleys grid again is out of the question of course).

But I guess that with the OJS3.1.1 upgrade I will just remove or edit that part from the script, because the solution I made in january has worked fairly well.

**Comment by ajnyga** [comment]
The issue is discussed here: https://forum.pkp.sfu.ca/t/all-the-files-words-figures-letters-have-been-published-with-the-new-ojs-3-0-version/26533
I am fairly sure that more an more OJS2 journals will encounter this problem when upgrading.

**Comment by bozana** [comment]
Hmmm... I see... Maybe than the best solution would be to copy that files, so that they stay in the submission files grid and also be in the galleys grid... I'll take a look...

**Comment by ajnyga** [comment]
I think that @asmecher pointed out last year that the scenario I described is not the way the supplementary files feature in OJS2 was meant to be used like. I agree, but at the same time I have a feeling that our journals are not the only ones that have used it the wrong.

I am of course more than willing to just edit the 3.1.1. upgrade script to take into account the changes I made.

**Comment by asmecher** [comment]
@ajnyga, have you checked whether your supplementary files were inadvertently published e.g. via the Reading Tools or the OAI interface? I suspect they were. The change with OJS3 is that they're much more evident -- but I don't believe it publishes anything that wasn't already published in OJS2 one way or another.

**Comment by asmecher** [comment]
@jmacgreg may also be maintaining tweaks to work around this on our own upgrades. James?

**Comment by ajnyga** [comment]
hi @asmecher 
Yes, definitely the supplementary files were published in OJS2 as well. In technical sense. 

But most of our journal editors did not seem to understand that they were public because most of them did not use reading tools and did not see the files on the article page. Also OAI is something that the editors really do not know about. 

So when the OJS3 upgrade came, they were surprised to see those files so clearly visible. And as you can see from the forum issue I posted above, our journals were not the only ones.

I do not have a problem in handling this in our own server, but suspect that may bump into other similar situations where the journals want to preserve the supplementary files they had in OJS2, but do not want them to be public.

**Comment by bozana** [comment]
I realized that migrating the supp files so that they are both in submission files grid and galley grid does not bring much -- those use cases as @ajnyga mentioned will however have to adapt the upgrade code to remove those migrated as galleys.
Maybe a kind of upgrade configuration option, how to migrate supp files -- as submission files or galleys -- would be helpful. @asmecher, would that maybe be possible?

**Comment by ajnyga** [comment]
Hi,

Just to make things more difficult, in our case there were both journals that had used supplementary files correctly and those that had not. In this regard I would think that having them on both by default would be a good option. But as I said above, in our part the problem has been solved already.

**Comment by bozana** [comment]
Hmmm... So maybe to leave it then as it should be i.e. as galleys.
In that case, @asmecher, could you review the PR: https://github.com/pkp/ojs/pull/1667 ?

**Comment by asmecher** [comment]
@bozana, please go ahead. I'm still curious whether PKP hosting is maintaining a patch for different behavior when upgrading installs with supplementary files they don't want published -- @mfelczak, any idea?

**Comment by mfelczak** [comment]
Hi @asmecher and @bozana , yes it would be very helpful to have the option to not publish supp files during upgrade. Many OJS2 editors have been using these to collect additional submission files for internal use.

**Comment by bozana** [comment]
I will close the issue, but maybe @jmacgreg and @mfelczak can however write it here then. Eventually we could provide an explanation here what is to be done/changed a) if supp files should not be migrated, b) if they should be migrated only as submission files (and not galley files).

**Comment by bozana** [comment]
Oh, I see now the message from @mfelczak...

**Comment by bozana** [comment]
I will then provide an explanation, eventually a patch, how to change the code. The only thing that I cannot do is the general fix/explanation if the situation is journal specific, in an multi-journal installation...

**Comment by bozana** [comment]
Here is the patch to migrate supp files from OJS 2.4.x to OJS 3.1 as submission files, and not as galleys: https://github.com/pkp/ojs/pull/1718/files

**Comment by bozana** [comment]
I believe that the other option, not to migrate supp files at all is actually not needed -- it would mean to remove them also from different DB tables (e.g. submission_files, submission_supplementary_files, metrics) and from the files folder. The patch to migrate them as submission files seems fine/enough for all cases to me. What do you think, @jmacgreg and @mfelczak ?

**Comment by mfelczak** [comment]
Thanks @bozana, yes having the option to migrate the supp files as submissions files should be sufficient.

**Comment by israelcefrin** [comment]
@bozana  I've committed a new patch to be applied into OJS3.1.1, given new OJS version shows hunk fail when I attempt  apply current one:  https://github.com/israelcefrin/ojs/commit/26ac913eefa6076c5827455746e8cfa0bf4cd06e 
Should I create a pull request to master branch as you did?

**Comment by bozana** [comment]
@israelcefrin, I am not sure if GitHub will keep that link forever, also when you delete your branch or ... Maybe you could try? Else, in case of such a PR it will... THANKS!!!

**Comment by bozana** [comment]
@israelcefrin, I will put the link to the PR here: https://github.com/pkp/ojs/pull/1906/files, so the PR can be closed...

**Comment by israelcefrin** [comment]
Tks @bozana, I will use this link as source for future upgrades from OJS 2.4.x.

**Comment by bozana** [comment]
@israelcefrin, sorry, I think, this line should be also removed: https://github.com/bozana/ojs/blob/b942b210ce893e7714f226d1a912f1e14c3e7db9/dbscripts/xml/upgrade.xml#L162. Could you add it to your patch?

**Comment by bozana** [comment]
@asmecher, here are the PRs to remove the function `repairSuppFilesFilestage`:
ojs master: https://github.com/pkp/ojs/pull/1925
ojs ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/1926
OK so?

**Comment by ajnyga** [comment]
Hi @bozana to sum up: we will never migrate the old OJS2 supplementary files back to supplementary files in journals that have already upgraded to OJS3 earlier?

**Comment by bozana** [comment]
The function convertSupplementaryFiles, s. https://github.com/pkp/ojs/blob/master/classes/install/Upgrade.inc.php#L1054, is still there, for those migrating from OJS 2 now. It will migrate supp files from OJS 2 to the galleys grid. If this is not wished (because the journals actually never wanted those files to be public), that the patch above has to be applied first, before doing the upgrade.

**Comment by bozana** [comment]
Ah, yes, now I understand -- those files have SUBMISSION_FILE_PROOF and are in the proof folder, but they do not have an associated galley -- that function `repairSuppFilesFilestage` did not create a galley for such files... because the `convertSupplementaryFiles` did it before, but this is however not true for new supp files uploaded to OJS 3.x... Grrrr...
I actually should consider assoc_type and assoc_id in that function... Grrrr...

**Comment by bozana** [comment]
The function to find the wrongly migrated supp files using the old, buggy function `repairSuppFilesFilestage` would be:
```
SELECT ssf.*, s.context_id
FROM submission_supplementary_files ssf, submission_files sf, submissions s
WHERE sf.file_id = ssf.file_id AND sf.assoc_type IS NULL AND sf.file_stage = 10 AND sf.revision = ssf.revision AND s.submission_id = sf.submission_id
```
Then it have to be seen, in what file_stage those files actually are, in order to migrate them back correctly.

**Comment by bozana** [comment]
@asmecher, the PR from @israelcefrin would then be the right one -- to migrate supp files from OJS 2 to submission files grid only, and removing the function repairSuppFilesFilestage: https://github.com/pkp/ojs/pull/1906/files. Could you take a quick look i.e. confirm, if OK so?

**Comment by ajnyga** [comment]
(waiting for repairRepairRepairSuppFilesFilestage 🤣 )

**Comment by bozana** [comment]
:rofl:  Correct... Sorry... :worried:

**Comment by bozana** [comment]
@ajnyga, the latest decision is that we will not migrate supp files as galleys but only to submission files grid... -- it seems that this is the case how mostly the supp files were used in OJS 2...

**Comment by ajnyga** [comment]
So the supplementary files will not be added as galleys at all after upgrade from OJS2 to OJS3? Meaning that if there is an article that has actual supplementary files, these have to be added manually after the upgrade? Right?

**Comment by bozana** [comment]
Yes, I think so. S. https://forum.pkp.sfu.ca/t/ojs-3-1-1-bug-image-files-missing-for-all-papers-including-published-papers/40645/12.
We could then maybe provide a patch the other way around -- for those that do want to have them as galleys... :-)

**Comment by bozana** [comment]
I think I would still prefer the first solution...

**Comment by asmecher** [comment]
I trust your judgement and the code looks clean (though I haven't run a test upgrade). Please go ahead!

**Comment by bozana** [comment]
I am leaving the migration of supp files from OJS 2.4.x to galleys in OJS 3.1.1-1 as is and I've just merged the fix for the buggy repairSuppFilesFilestage function for those already updated to OJS 3. 
Thus, tagging @ajnyga and @israelcefrin here as well, for them to know.
Thus, if someone does not want the supp files from OJS 2.4.x to be publicly available and migrated as galleys in OJS 3, as till now, the patch that @israelcefrin provides is necessary: https://github.com/pkp/ojs/pull/1906/files.

**Comment by bozana** [comment]
@israelcefrin, here the patch for the 3.1.1-2: https://github.com/pkp/ojs/pull/2021/files

**Comment by t4x0n** [comment]
Hi, I have some questions about this issue... I have the OJS 3.1.1.0 and I found some files in the proof folder but the manuscript is only in the review stage, I think there are supplementary material because of the content of them (appendix and big table), but these files are not accessible from the OJS, I can access only in cPanel, my installation is not upgraded from OJS 2.x, this issue is resolved if upgrade to 3.1.1-2??

**Comment by bozana** [comment]
Hi @t4x0n, yes unfortunately I wrongly moved all supp files to the proof stage. This issue is solved in 3.1.1-2 but the affected 3.x installations will/cannot be repaired automatically :-( I hope you can fix those manually? -- That would be best and most secure way to solve it. Else, if you think that there are too many cases, let me know -- eventually you could try to run a script to move those supp files from the proof stage into the submission stage...

**Comment by t4x0n** [comment]
thanks, I think this is a not big deal, maybe just a few submissions have problems.

**Comment by spiderkga** [comment]
Good afternoon!

I made an update to version 3 but the articles are being appreciated by the public.

Is there a way to fix this, or do I need to do the update process again?

**Comment by asmecher** [comment]
@spiderkga, have a look at this thread in our support forum: https://forum.pkp.sfu.ca/t/issue-with-supplementary-files-in-upgrading-from-ojs-2-4-8-1-to-ojs-3-2-1-1/61683/2

**Comment by spiderkga** [comment]
@asmecher  I
![erro_seer](https://user-images.githubusercontent.com/69540483/89944962-04abe280-dbf7-11ea-907c-4d787f7fc142.PNG)
 think it was not what I asked for, I am sending a screenshot of the screen I need these files of the red frame to be hidden for public access

**Comment by asmecher** [comment]
@spiderkga, that thread discusses the same thing you're asking about: the content you're pointing out is actually published in your OJS 2.x, but is not easy to find. OJS 3.x is designed to make accessing that content easier, but does not publish anything that was not previously published. Some users misunderstood the feature in OJS 2.x, and only discovered that the documents were published when they upgraded to 3.x. The patch linked by Israel in the linked thread can be applied to change the behaviour when you run the upgrade. If you've already run the upgrade, you might need to review your submissions manually. In any case, that thread is the relevant place to continue the conversation.

**Comment by bdgregg** [comment]
OK - different error message on my end:

[cid:be355ae1-89fe-4e42-ad43-de959a29aaac]

I think I hit our production site on the first try.  Are we sending the same attributes that we are doing for pitt.primo.exlibrisgroup.com?

-Brian.


Brian D. Gregg

Solutions Architect
University Library System
University of Pittsburgh
7500 Thomas Blvd.
Pittsburgh, PA 15208
voice:   412-648-3264
fax:      412-648-3585

________________________________

**Comment by spiderkga** [comment]
@asmecher 
But can I apply this patch after updating?

Could you tell me how you do it?

**Comment by asmecher** [comment]
@spiderkga, sorry, the patch can only be effective if it's applied before the upgrade process is run. Afterwards you'll have to review your content manually.

**Comment by marcbria** [comment]
If somebody is still looking for a solution for this, take a look to this post:
https://forum.pkp.sfu.ca/t/ojs3-hide-all-supplementary-files/47247/32

Bozana made an script to move supplementary files from galleys to Submission and it could be applied even if you upgraded.
