### ISSUE TITLE
Allow reviewers to indicate availability

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3017]
Provide reviewers with an option to indicate their temporary unavailability (which would also make themselves invisible to editors for selection) for a specific time period.

This could be added to the user's Profile page.

This could be more generally useful for other roles (copyeditors, section editors, layout editors, proofreaders, etc.).

This would apply to OJS and OMP.

**Comment by NateWr** [comment]
I like the idea, but I wonder if reviewers would actually use it. Does this request come from reviewers themselves or editors? If it's just coming from editors, my fear is that it might be optimistic to think that reviewers would actually update their availability.

I can more easily imagine the other user roles you describe making use of it. 👍

**Comment by NateWr** [comment]
(Just noticed the original request is from several months ago. 😃

**Comment by alexxxmendonca** [comment]
A similar feature is available in ScholarOne and it is quite used by reviewers.

**Comment by aolney** [comment]
[Looks like this has been discussed for OJS for some time](https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=7925)

**Comment by NateWr** [comment]
Closing because we have not seen significant interest in this.

**Comment by asmecher** [comment]
After discussion with a SciELO pilot journal I've filed this as a Feature Request over here:

https://forum.pkp.sfu.ca/t/ojs-omp-allow-reviewers-to-indicate-availability/75064

Input is welcome over on that topic.
