### ISSUE TITLE
[OJS] OAI-PMH should not show results for journals with publishingMode set to PUBLISHING_MODE_NONE

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3026]
At the moment if a journal is just using OJS for editorial purposes in multi-journal installations, their articles still show up in OAI-PMH with links leading article pages that give 404.

I think that it would make sense that if publishingMode is set to PUBLISHING_MODE_NONE, no results from the journal are shown.

Discussion here: https://forum.pkp.sfu.ca/t/oai-pmh-and-access-to-journal-content-in-ojs-3-0/25809

Pr in a minute.

**Comment by asmecher** [comment]
Merged, thanks, @ajnyga -- though I do wonder whether we'll receive some pushback from journals that have replaced their front-end with some other toolset, thus have disabled publishing within OJS, but who may still want access to an OAI endpoint via OJS. (For that to work, we'd need to consider what data to suppress or delegate to external services, such as article URLs.)

**Comment by ajnyga** [comment]
Fair point. 

We could of course just have a journal specific setting for switching OAI on or off.

**Comment by ajnyga** [comment]
@asmecher your omen came to haunt this issue https://forum.pkp.sfu.ca/t/oai-pmh-and-access-to-journal-content-in-ojs-3-0/25809/12?u=ajnyga (or not exactly the same thing, but anyway).

Alternatives:
1. just hide article url's for journals that are PUBLISHING_MODE_NONE
2. my old suggestion above: a journal specific setting for enabling/disabling OAI

**Comment by asmecher** [comment]
I was about to propose both those things, @ajnyga. I've filed this for future attention: https://github.com/pkp/pkp-lib/issues/4149
