### ISSUE TITLE
CSL plugin fatal error if no last name

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3029]
Reports of a fatal error occurring if an article author has no last name.

https://forum.pkp.sfu.ca/t/problem-with-enable-citation-plugin/35022/6

**Comment by NateWr** [comment]
This is enforced by citeproc-php. We can't even detect a missing last name and pass an empty string, because it will still throw a fatal error.

Since we require a last name, and it seems a reasonable thing to require for a citation, I'll consider this not an issue and something to be fixed with the data.

@asmecher as a side note, this came up because the `admin` account has no last name. Should we add one during the install process?

**Comment by asmecher** [comment]
@NateWr, no harm in that, I suppose: edc2d3e
