### ISSUE TITLE
[OJS] The application name for OJS 3 is stated as "ojs2"

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3030]
I noticed it when a fatalerror() wrote this into the error log: _ojs2: 404 Not Found_

In the [Application.inc.php](https://github.com/pkp/ojs/blob/master/classes/core/Application.inc.php) the name is still set to ojs2.

```
	/**
	 * Get the symbolic name of this application
	 * @return string
	 */
	function getName() {
		return 'ojs2';
	}
```

**Comment by asmecher** [comment]
This is a known issue, but it's cosmetic and a little tricky to fix.  See https://github.com/pkp/pkp-lib/issues/1839.
