### ISSUE TITLE
[OJS] Untranslated label for default.groups.name.author and default.groups.name.translator

### ISSUE THREAD

**Issue by martibosch** [pkp/pkp-lib#3036]
Although the following label is correctly set as in:
```
./lib/pkp/locale/fr_FR/default.xml:45:	<message key="default.groups.name.author">Auteur</message>
```
it is not displayed in the browser in the `fr_FR` locale (see pic). I have already tried clearing the OJS and browser cache. The same happens for ` default.groups.name.translator' which makes me suspect that this is somehow related to the fact that both labels appear in the `registry/userGroups.xml` file.
![selection_040](https://user-images.githubusercontent.com/5831581/32662670-9dd24d6c-c62b-11e7-8188-c98a46775b44.png)
Thank you!

**Comment by asmecher** [comment]
@martibosch, some locale keys, including these, are installed into the database when the journal is created. To change the translation, go to Settings > Users & Roles > Roles.
