### ISSUE TITLE
editor actions for all managers and sub-editors

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3039]
Since I have introduced the editor recommendationOnly, the editor decisions are only displayed for editors/managers that are assigned to that submission. Earlier all managers and sub-editors could do the decision. Shall this then be changed as it was -- so that all managers and sub-editors can make a decision?

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3040
ojs master: https://github.com/pkp/ojs/pull/1677 (only submodule update)

**Comment by bozana** [comment]
This way, this could also happen: if an user has an editorial role that is recommendOnly and also a normal editorial role, and the user is not assigned to the submission, the user will see all action buttons, for recommendation and for decision making.

**Comment by bozana** [comment]
@NateWr, could you review this? THANKS!!!

**Comment by NateWr** [comment]
I'm getting an error with this code. I've assigned a recommending editor as the only editor for a submission. When I visit as that editor, the decisions appear. When I visit as an admin or journal manager, the decision buttons fail to load with the following error:

```
[Wed Nov 15 14:32:52.887235 2017] [:error] [pid 6072] [client 127.0.0.1:42314] PHP Notice:  Undefined variable: reviewRound in /var/www/html/ojs/lib/pkp/pages/workflow/PKPWorkflowHandler.inc.php on line 285, referer: http://localhost/ojs/publicknowledge/workflow/index/42/1
[Wed Nov 15 14:32:52.887365 2017] [:error] [pid 6072] [client 127.0.0.1:42314] PHP Fatal error:  Uncaught Error: Call to a member function getRound() on null in /var/www/html/ojs/lib/pkp/pages/workflow/PKPWorkflowHandler.inc.php:285
Stack trace:
#0 /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.inc.php(372): PKPWorkflowHandler->editorDecisionActions(Array, Object(Request))
#1 /var/www/html/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(233): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#2 /var/www/html/ojs/lib/pkp/classes/core/Dispatcher.inc.php(134): PKPPageRouter->route(Object(Request))
#3 /var/www/html/ojs/lib/pkp/classes/core/PKPApplication.inc.php(243): Dispatcher->dispatch(Object(Request))
#4 /var/www/html/ojs/index.php(68): PKPApplication->execute()
#5 {main}
  thrown in /var/www/html/ojs/lib/pkp/pages/workflow/PKPWorkflowHandler.inc.php on line 285, referer: http://localhost/ojs/publicknowledge/workflow/index/42/1
```

Also, I wasn't able to reproduce the initial problem. In `master`, I can take a submission and assign only a recommending editor. Then when I visit as an admin or journal editor, I can still make the decisions. What am I missing?

**Comment by bozana** [comment]
Hmmm.... I will take a look at the error...

Hmmm.... If an editor was assigned to a submission, I did not see the review actions/decisions when logged in as another editor...

**Comment by bozana** [comment]
Hmmm... @NateWr, could you please double check if you can reproduce the initial problem? -- If I assign an editor to a submission (no matter if recommend only or normal) but then visit the review stage of that submission as another editor, I see "Assign an editor to enable the editorial decisions for this stage. " :-(

**Comment by bozana** [comment]
@NateWr, I fixed the errors and also considered the issue https://github.com/pkp/pkp-lib/issues/3073 -- now no editor action is displayed if the user has a recommendOnly role. That user will however have all the other actions available, like uploading files, assigning participants and scheduling for publication -- because these actions do not consider recommendOnly... But this is maybe OK -- the manager and sub-editor role is supposed to do that and recommendOly should just not be able to make decisions, right? 
Thanks!!!

**Comment by NateWr** [comment]
@bozana That sounds good.

**Comment by bozana** [comment]
Thanks a lot @NateWr! Will merge and cherry-pick as soon as the tests pass...
