### ISSUE TITLE
Improve add discussion workflow for authors

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3041]
Currently authors need to manually add participants to the discussion when starting a new thread. 

Based on client feedback with OJS 3.0.2 editors have reported that sometimes authors aren't aware that they need to manually add editors as participants to the discussion. As a result, the editors don't receive a task notification that a new discussion has been created and may not see the discussion until they access the submission at a later date.

Possible improvements to make this process more clear for authors:
- Additional instructions at the top of the add discussion modal
- Auto-assignment of editors as participants to the new discussion

**Comment by asmecher** [comment]
Dupe: https://github.com/pkp/pkp-lib/issues/1619
