### ISSUE TITLE
PKP bugzilla forum is dead - update old links to bugzilla issues 

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#3044]
* OJS: `plugins/importexport/pubmed/filter/ArticlePubMedXmlFilter.inc.php`
* `lib/pkp/classes/session/SessionManager.inc.php`
* `lib/pkp/classes/core/PKPApplication.inc.php`

these include references to issues in the old bugzilla forum, they should be removed or replaced

(Also, some locales (cs_CZ, tr_TR) refer to the bugzilla forum, maybe we should remove those lines.)

**Comment by asmecher** [comment]
@mtub, we're trying to archive Bugzilla so that the URLs stay active but having some trouble with the details.

**Comment by asmecher** [comment]
I think the wayback archive of Bugzilla has been working without problems for a while now... Closing.
