### ISSUE TITLE
[OMP] User management blank and triggering warnings

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#3045]
In a fresh install of OMP 3.1, I can't seem to be able to handle users for some reason. Visiting the user management page for a press gives an empty page (see screenshot).

![screenshot from 2017-11-13 07-47-50](https://user-images.githubusercontent.com/11042981/32713192-6e47c3dc-c848-11e7-85eb-0705fc92c3a6.png)

It also triggers the following warnings in the error log:
```

PHP Warning:  Declaration of UserGridHandler::renderFilter($request) should be compatible with GridHandler::renderFilter($request, $filterData = Array) in /usr/local/omp/lib/pkp/controllers/grid/settings/user/UserGridHandler.inc.php on line 0, referer: [our host]/index.php/test/management/settings/access

PHP Warning:  Declaration of UserForm::execute($request) should be compatible with Form::execute() in /usr/local/omp/lib/pkp/controllers/grid/settings/user/form/UserForm.inc.php on line 18, referer: [our host]/index.php/test/management/settings/access

PHP Warning:  Declaration of & UserDetailsForm::execute($args, $request) should be compatible with UserForm::execute($request) in /usr/local/omp/lib/pkp/controllers/grid/settings/user/form/UserDetailsForm.inc.php on line 18, referer: [our host]/index.php/test/management/settings/access

PHP Warning:  Declaration of UserDetailsForm::display($args, $request) should be compatible with Form::display($request = NULL, $template = NULL) in /usr/local/omp/lib/pkp/controllers/grid/settings/user/form/UserDetailsForm.inc.php on line 18, referer: [our host]/index.php/test/management/settings/access

Declaration of UserDetailsForm::initData($args, $request) should be compatible with Form::initData() in /usr/local/omp/lib/pkp/controllers/grid/settings/user/form/UserDetailsForm.inc.php on line 18, referer: [our host]/index.php/test/management/settings/access

```
Any ideas?

OMP 3.1
PHP 7.0.19-1

**Comment by asmecher** [comment]
@martinpub, is there anything in your log beyond those warnings? You may have a separate PHP error and Apache error log -- make sure you're checking both.

**Comment by martinpub** [comment]
@asmecher Hmm, the warnings are written to /var/log/apache2/error.log, and I have set the php.ini according to [your instructions here](https://github.com/pkp/pkp-lib/issues/904#issuecomment-340114893). I can't seem to get any more output in the logs than what's already posted.

**Comment by asmecher** [comment]
@martinpub, hmm, I'm not sure why a useful error message wouldn't show up there somewhere. Can you try inspecting the request/response using a browser-based developer toolset, such as Firebug for Firefox? (Most modern browsers have developer tools built in.) I'd be interested in the response for the request that's supposed to render that tab -- it should be pretty much the last one listed.

**Comment by martinpub** [comment]
I see @asmecher, I will check with Firebug or similar.
________________________________
Från: Alec Smecher <notifications@github.com>
Skickat: den 16 november 2017 20:48:59
Till: pkp/pkp-lib
Kopia: Martin Persson; Mention
Ämne: Re: [pkp/pkp-lib] [OMP] User management blank and triggering warnings (#3045)


@martinpub<https://github.com/martinpub>, hmm, I'm not sure why a useful error message wouldn't show up there somewhere. Can you try inspecting the request/response using a browser-based developer toolset, such as Firebug for Firefox? (Most modern browsers have developer tools built in.) I'd be interested in the response for the request that's supposed to render that tab -- it should be pretty much the last one listed.

**Comment by martinpub** [comment]
OK, it seems there is a js error, which explains why the PHP error log doesn't give anything:

> ReferenceError: pkp is not defined http://books.lub.lu.se/lib/pkp/js/classes/Handler.js Line 506.

**Comment by asmecher** [comment]
Is this an install from git, or from the .tar.gz file?

**Comment by martinpub** [comment]
@asmecher It's a git install.

**Comment by asmecher** [comment]
Did you build the Node dependencies? I suspect they're missing.

**Comment by martinpub** [comment]
My bad, missed that part of the install instructions. It's working now, thanks for helping out @asmecher!
