### ISSUE TITLE
[OJS] Enhancement for uploading metadata to DOAJ

### ISSUE THREAD

**Issue by felixgruender** [pkp/pkp-lib#305]
At the moment, the DOAJ Export Plugin provides the possibility to generate an XML file containing all data of a journal (including all issues and articles).
But often it is necessary to upload just certain issues or articles - so in this case the XML file has to be edited manually.
So it may be difficult to keep track of whether an issue / article is already uploaded or not.
Furthermore there may be file size constraints in DOAJ which have to be considered.

To tackle this problem it would be beneficial to have the following features (at least number 1 and 2):
1) Export single issues / articles
2) Select several issues / articles an export them
3) Flag already exported issues / articles (in order to export just the hitherto untagged issues / articles)
4) Export all changed issues / articles

As this problem is part of our project we plan to implement it ourselves.

Best regards,
Felix

**Comment by asmecher** [comment]
Thanks, Felix -- I've passed this along to Dom from DOAJ for comment just in case it intersects with their plans.

**Comment by dommitchell** [comment]
Hi @felixgruender @asmecher 

Nothing here rings any alarm bells immediately. One comment just now and I'm going to consult with my technical partner so will update here.

> Furthermore there may be file size constraints in DOAJ which have to be considered.

Uploaded files must be < 50Mb. Remote files (we allow users to provide a URL where the file sits) must be < 250Mb.

**Comment by felixgruender** [comment]
Alright, thanks for the information so far!
- Felix

**Comment by dommitchell** [comment]
The only thing that we think might be useful to discuss is that DOAJ is developing an API this year and it would be good to ensure as many compatibilities as possible. Might that be something worth discussing? Dom

**Comment by felixgruender** [comment]
Hello  Dom,
OK, thanks - just some remarks/questions:

1) Are there already concrete plans concerning the API you are going to develop this year? 
If so, could you give us some basic information on the functionalities of this API?

2) When this API will be ready to go live, will it still be possible to use the hitherto existing file upload as well (and will the file format stay the same)? Or will the file upload be abandoned completely?
I just want to make sure that the upload enhancements we are going to implement aren't futile.

Best regards,
Felix

**Comment by dommitchell** [comment]
Hi Felix,

Sorry for the delay.

> 1) Are there already concrete plans concerning the API you are going to develop this year?
> If so, could you give us some basic information on the functionalities of this API?

We have no concrete plans but basically the API will be two way: facilitate content (article metadata) in from publishers; and facilitate content out for advanced searches or integrating a DOAJ-style search on a 3rd parties' page. This is as far as we have come although proper brainstorming should start end Feb.

> 2) When this API will be ready to go live, will it still be possible to use the hitherto existing file upload as well (and will the file format stay the same)? Or will the file upload be abandoned completely?

Yes, it will still be possible. We have a longtail of very small publishers who aren't interested in APIs, or even in XML but they do it because entering the data manually is a chore. The API will be another choice for uploading.

**Comment by felixgruender** [comment]
Hello Dom, thanks for the information!

**Comment by bozana** [comment]
Is there maybe a good way to split the exported XML data into several documents <50MB? Or could we assume that now, that a journal manager can select objects to be exported, this is not going to happen (that the exported file is >50MB) i.e. that the journal manager should take care and not select all issues at once, but e.g. issue by issue?

**Comment by asmecher** [comment]
Hi @dommitchell -- have you folks recently changed your XML schema? We're getting a report that suggests that -- see http://forum.pkp.sfu.ca/t/doaj-xml-failed-ojs-2-4-6-0 for details.

**Comment by dommitchell** [comment]
Hi @asmecher we haven't changed the schema but we did have a bug after our recent upload. This was fixed just today https://github.com/DOAJ/doaj/issues/686

Let me know if that doesn't answer the question

**Comment by asmecher** [comment]
Thanks, @dommitchell!
