### ISSUE TITLE
OAI record datestamp

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3051]
the datestamp of the OAI articles seems to be less than from parameter date...

s. also https://forum.pkp.sfu.ca/t/errors-validating-repository-in-openarchive/33185/9

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1684
ojs ojs-stable-3_1_0: https://github.com/pkp/ojs/pull/1685

**Comment by bozana** [comment]
@asmecher, could you please double think if this is OK? THANKS!!!

**Comment by asmecher** [comment]
As noted [here](https://github.com/pkp/ojs/pull/1685#issuecomment-344745882), this is a parallel to a fix already committed elsewhere. Thanks, @bozana!

**Comment by bozana** [comment]
That last change should probably go to the 3.1.0-1. I will make a PR...

**Comment by bozana** [comment]
PRs for using GRATEST for OAI until date:
ojs master: https://github.com/pkp/ojs/pull/1714
ojs ojs-stable-3_1_0: https://github.com/pkp/ojs/pull/1715

**Comment by bozana** [comment]
@asmecher, could you take a look at the PRs?

**Comment by asmecher** [comment]
Yes, I wasn't suggesting we change it to `LEAST` or something else, just connecting the two changes. Please go ahead, all looks good!
