### ISSUE TITLE
consider URL encoding for oai identifiers

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3052]
The oai identifiers in OJS are formed something like this: oai:ojs-domain.net:article/1. The harvester and OAI validators could use the URL encoding for the identifiers, which would then look something like: oai%3Aojs-domain%2Enet%3Aarticle/1. In that case OJS will not recognize the identifier and return "badArgument: Identifier is not in a valid format". 

s. also https://forum.pkp.sfu.ca/t/failed-to-register-database-at-oai/35252?source_topic_id=34166

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1686
ojs ojs-stable-3_1_0: https://github.com/pkp/ojs/pull/1687
omp master: https://github.com/pkp/omp/pull/467
omp omp-stable-3_1_0: https://github.com/pkp/omp/pull/468
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1688
ojs ojs-dev-2_4: https://github.com/pkp/ojs/pull/1689

**Comment by bozana** [comment]
@asmecher, I wonder how haven't we encounter this before :-O Could you take a look, if this all make sense?

**Comment by ctgraham** [comment]
My testing of OJS 2.4.8-2 resolved fine with urlencoded identifiers.  Are you sure this is needed for 2.x?

**Comment by bozana** [comment]
Hmmm... Yes you are right @ctgraham. Strange...

**Comment by bozana** [comment]
Ah, I've figured it out -- the solution should be different. The PR changes are coming...

**Comment by bozana** [comment]
@ctgraham, thanks a lot!!!

**Comment by bozana** [comment]
@asmecher, could you take a look at the PRs above?

**Comment by asmecher** [comment]
Good spotting, it looks like I removed a required reference thinking it wasn't necessary. I'll add a note in the code to help prevent this from happening again.
