### ISSUE TITLE
Some test cases still reference String instead of PKPString

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#3054]
In OJS 2.4.x, some test cases still reference String:: instead of PKPString:: classnames.

See:
https://github.com/pkp/pkp-lib/blob/655647849803c42ed4bbe795cf4c4e996db8b762/tests/classes/core/StringTest.php

https://github.com/pkp/ojs/blob/20a9ad5bd99486faba70a0648cfce3aa12f38a43/tests/functional/plugins/importexport/medra/FunctionalMedraExportTestCase.php

https://github.com/pkp/ojs/blob/20a9ad5bd99486faba70a0648cfce3aa12f38a43/tests/functional/plugins/pubIds/FunctionalDoiPubIdPluginTestCase.php

**Comment by asmecher** [comment]
Merged, thanks!
