### ISSUE TITLE
Compile source maps with CSS files

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3058]
http://lessphp.typesettercms.com/#source-maps

**Comment by asmecher** [comment]
@NateWr, would you mind reviewing https://github.com/pkp/pkp-lib/pull/3555? It adds source maps in the `cache` directory with the same name as the `.css` file, with `.map` appended.

**Comment by NateWr** [comment]
Hmm, after looking into this a bit, I realize I know much less about source maps than I thought I knew. :)

This change does create a source map and it does appear to be read by the browser:

![selection_127](https://user-images.githubusercontent.com/2306629/38502933-ac3ded86-3c08-11e8-8b06-0649118bda99.png)

But it points to the wrong paths for the source files, most likely because we don't load the CSS file directly but call a PHP file which loads it:

![selection_128](https://user-images.githubusercontent.com/2306629/38503030-e56e3bc4-3c08-11e8-9ddf-bcfa64fa0fa7.png)

In case that's hard to read, it's looking for the source file here: `http://localhost/ojs/publicknowledge/$$$call$$$/page/page/var/www/html/ojs/lib/pkp/styles/structure/body.less`.

`$this->getCachedLessFilePath()` does return an absolute URL, but this seems to get converted to a relative URL in the actual source maps:

```
"sources":["var\/www\/html\/ojs\/lib\/pkp\/styles\/utils.less","var\/www\...
```

So the source maps still provide a "trail" back to the original file, but they're not configured correctly. I'm not sure if they can be configured correctly given that we go through a PHP file to access the CSS file. We might have to revisit that if we want properly functioning source maps.

While looking into this, I noticed that it does produce a proper `.map` file and place it next to the CSS file. But it also appends this file directly to the generated CSS file. This makes the final compiled CSS file pretty large. As far as I can tell, the browser is not actually locating the `.map` file, but relying on this version appended to the compiled CSS file.

For this reason, I think we shouldn't be generating `.map` files unless the site is in dev mode or something. Maybe if `enable_minify` is off?

Adding the `sourceMapUrl` setting (as specified [here](http://lessphp.typesettercms.com/#source-maps)) didn't seem to make much of a difference, either.

**Comment by NateWr** [comment]
Also, when we add `.map` files we'll need to remove them when clearing the cache.

**Comment by asmecher** [comment]
Hrm, I thought this was going to be an easy one-liner. I'll take another look. (TBH I've never worked with source maps at all.)

**Comment by NateWr** [comment]
Closing as low priority.
