### ISSUE TITLE
wrong element attributes in oai_marc

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3062]
The OAI format oai_marc changed in OJS 2.4.6: the XML formatting i.e. construction was excluded to the new template record.tpl (s. https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/plugins/oaiMetadataFormats/marc/record.tpl). For some reason the new template contains wrong element attributes: `tag`, `ind1`, `ind2` instead of `id`, `i1` and `i2` (s. https://github.com/pkp/ojs/blob/ojs-stable-2_4_5/plugins/oaiMetadataFormats/marc/OAIMetadataFormat_MARC.inc.php#L119)
@asmecher, do you know a reason behind?

s. https://forum.pkp.sfu.ca/t/failed-to-register-database-at-oai/35252/9

**Comment by ctgraham** [comment]
I think the `tag`, `ind1`, and `ind2` are transposed from the corresponding attributes from marcxml.

**Comment by asmecher** [comment]
@bozana, I think @ctgraham's interpretation is probably right.

**Comment by bozana** [comment]
OK, I can then turn it back... THANKS!!!

**Comment by ctgraham** [comment]
@bozana, do you mean revert to the code before the template?  I think we want to keep the template but change the attributes.  I made a [commit](https://github.com/ulsdevteam/ojs/commit/027dbf8b2f2e7cbf16bb07f34e6baed48635f044) to do that in 2.4.x, but got sidelined while trying to write the test case.

**Comment by bozana** [comment]
Ah, yes, that is what I thought :-) Thanks @ctgraham! Maybe we can then first merge/fix that and then later write a test? One thing still to change: `varfield` should be used instead of that one `dataField` (dataField is not known in that schema)...

**Comment by bozana** [comment]
PRs:
ojs-dev-2_4: https://github.com/pkp/ojs/pull/1701
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1707
ojs-stable-3_1_0: https://github.com/pkp/ojs/pull/1708
master: https://github.com/pkp/ojs/pull/1709
