### ISSUE TITLE
Allow authors to delete from revisions grid

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3063]
Currently, authors can upload to the revisions grid, but cannot delete.

They should have this ability, for cases when they accidentally upload the wrong file.

**Comment by kaschioudi** [comment]
@asmecher I came across a bug while trying to fix this issue. It seems that the revision file deletion was also broken. see https://github.com/pkp/pkp-lib/issues/3088

**Comment by asmecher** [comment]
Merged, thanks -- don't forget to back-port to `ojs-stable-3_1_0` as needed!

**Comment by kaschioudi** [comment]
@asmecher here's the PR for ojs 3.1.0 back port
https://github.com/pkp/pkp-lib/pull/3093

**Comment by asmecher** [comment]
Merged, thanks!
