### ISSUE TITLE
[OMP] Add "Register as Reader" to bottom of Register page 

### ISSUE THREAD

**Issue by straderg** [pkp/pkp-lib#307]
Ref: bug 8849 at bugzilla, the reason Readers need to register is so they receive notifications when new issues in their preferred series publish. (Is this function working in OMP?) So 2 adjustments are needed. (1) Press should be able to allow users to register themselves as Readers at MANAGEMENT > USERS & ROLES > SITE ACCESS OPTIONS, where a third option under "User Registration" should read "Reader (can access published works)". (2) Once the Press checks that box, users should see a second "Register as" option at bottom of Register page: "Register as <box> Reader". (This coding is already built with how OMP allows the Press to set up "external reviewer".)
![users roles page_for final reader role bug](https://cloud.githubusercontent.com/assets/10745281/5976007/e3bafe64-a856-11e4-9850-53a2d70e36d5.png)

**Comment by asmecher** [comment]
@straderg, this is already implemented per <http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8849> -- as you've described. It'll be released in OMP 1.2.

**Comment by straderg** [comment]
Thanks, Alec.
