### ISSUE TITLE
[OJS] forms counter doesn't change 

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3071]
In review tab, exist two counter for determinate the current use of review forms, but the numbers don't change. The idea es great but always shows all as Completed and In Review, at the same time. This is important because if someone need disable a form (to change it) is important made it only if the reviews are finished.

![image](https://user-images.githubusercontent.com/5422984/32899033-93803ec2-cac8-11e7-8b54-7840f36f5f00.png)

**Comment by asmecher** [comment]
@t4x0n, could you try the attached patch (to be applied in the `lib/pkp` directory) and let me know whether it resolves the issue?

**Comment by t4x0n** [comment]
Yes @asmecher, I have been trying right now, and this is the result: 
![image](https://user-images.githubusercontent.com/5422984/34808307-cb93d808-f66c-11e7-8e56-4d904310c9c3.png)
it seems to have worked!!

**Comment by asmecher** [comment]
Thanks, @t4x0n!

@NateWr, would you mind reviewing this? PR: https://github.com/pkp/pkp-lib/pull/3257
OJS commit is for tests only (passed: https://travis-ci.org/asmecher/ojs/builds/327522055)
