### ISSUE TITLE
Prevent range requests

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3072]
See https://forum.pkp.sfu.ca/t/pdf-not-display/30369/14 for details.

**Comment by asmecher** [comment]
(There's also a suggested range-enabled readfile implementation at http://php.net/manual/en/function.readfile.php.)

**Comment by GrazingScientist** [comment]
Your solution worked perfect! Thanks! 👍

**Comment by asmecher** [comment]
Committed, thanks for confirming!
