### ISSUE TITLE
Published article title formatting tags escaped

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3078]
When an editor adds e.g. italics to an article title, these are correctly rendered when editing the submission but the tags are escaped when the article is published (screenshots attached).

Submission management:
![submission](https://user-images.githubusercontent.com/200793/32956807-e8baacf0-cb87-11e7-9dbe-94cefc6b7d00.png)

Article landing page:
![article](https://user-images.githubusercontent.com/200793/32956813-ed0cfcb8-cb87-11e7-8a47-9965ba04e6c7.png)

**Comment by asmecher** [comment]
Dupe! https://github.com/pkp/pkp-lib/issues/2564
