### ISSUE TITLE
[OJS] Dataverse plugin: deaccessioning not supported in API v1.1

### ISSUE THREAD

**Issue by jwhitney** [pkp/pkp-lib#308]
Deaccessioning datasets is no longer supported in Dataverse 4's SWORD API v1.1 -- only unpublished datasets can be deleted. Update plugin to check API version & study state before attempting to delete studies.

**Comment by asmecher** [comment]
Looks good -- merged. Thanks, Jen.

**Comment by jwhitney** [comment]
Great, thanks!
