### ISSUE TITLE
File deletion from revision grid is broken

### ISSUE THREAD

**Issue by kaschioudi** [pkp/pkp-lib#3088]
Even though the file gets removed, the request does not complete successfully causing the delete confirmation modal to remain on screen. 
Under the hood, the following error is output to the logs `PHP Fatal error:  Call to a member function getStatus() on a non-object in /<path-to-ojs-install>/lib/pkp/classes/submission/reviewRound/ReviewRoundDAO.inc.php on line 264`

**Comment by bozana** [comment]
Oh good catch! I think I inserted the bug... :-\

**Comment by kaschioudi** [comment]
https://github.com/pkp/pkp-lib/pull/3089

**Comment by kaschioudi** [comment]
@bozana I have a PR ready for you :)

**Comment by bozana** [comment]
Thanks @kaschioudi!!!

**Comment by asmecher** [comment]
@bozana and @kaschioudi, does this need to be back-ported to `ojs-stable-3_1_0`?

**Comment by bozana** [comment]
Uh, @asmecher, you are right!!! I thought I only made the bug in master :-P Will cherry-pick... THANKS!!! :star:
