### ISSUE TITLE
[OJS] Authors receive duplicated emails when editors use "Send email" functionality

### ISSUE THREAD

**Issue by gpieri** [pkp/pkp-lib#309]
When editors use the Send email funcionality (/editor/notifyUsers) and select "All published authors" as the recipients, some authors receive more than one email.

This happens for authors that have published more than one article with different data (different affiliation, middle name or other info).

The issue is that the list of authors to send email (AuthorDAO::getAuthorsAlphabetizedByJournal) does not avoid duplicated emails. 

If the author has different affiliations or the middle name is written in two ways (i.e. abbreviated), he will receive duplicate emails.

**Comment by asmecher** [comment]
@gpieri, OJS 2.x currently "disambiguates" author records by looking for entries with differing first name, middle name, last name, URL, email, country, and/or affiliation fields. We don't plan to improve this in OJS 2.x; for 3.x, we'll implement a proper disambiguation toolset including support for external disambiguators like ORCiD.

**Comment by gpieri** [comment]
@asmecher I see. Nice to know it will be fixed in 3.x

For the time being, I was thinking in changing this functionality to behave like this: select all unique emails from the authors table, then get the data of the latest entry for the email (in the authors table). 

This would solve the problem with the multiple emails in OJS 2.x. Would you be interested in a Pull Request with this change?

**Comment by asmecher** [comment]
Yes, that makes sense, and would be a useful change. Please do.

**Comment by asmecher** [comment]
Merged, thanks!
