### ISSUE TITLE
Sidebar blocks missing from search results

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3097]

**Comment by asmecher** [comment]
This was a tricky one. Basically:

- The search results page ends up invoking the metrics code
- The metrics code loads a set of report plugins with `context_id=0`
- This tricks subsequent plugin load code into thinking that future plugin loads should be done with `context_id=0`
- Thus the sidebar blocks don't show unless they're capable of displaying site-wide (which the language toggle is, thus it was still showing).

**Comment by asmecher** [comment]
@bozana, could you review this PR?
https://github.com/pkp/pkp-lib/pull/3098
Thanks!

**Comment by ajnyga** [comment]
Wondering if this could be somehow related to https://github.com/pkp/pkp-lib/issues/2217

**Comment by asmecher** [comment]
At a glance, I'm not sure it is, @ajnyga -- but it wouldn't hurt to try the changes in those PRs to see?

**Comment by asmecher** [comment]
@bozana, I fixed the issues you identified -- see https://github.com/pkp/pkp-lib/pull/3098/commits/11913b13e3fc8f9fdfd7f65ec6afc7537934893e -- mind taking another look? Thanks!

**Comment by bozana** [comment]
Good @asmecher, ready to be merged, please go ahead... :-)

**Comment by asmecher** [comment]
Thanks, @bozana!
