### ISSUE TITLE
Encourage the use of consistent galley labels

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3099]
**Describe the problem you would like to solve**
Typically, galley labels are intended to be consistent across all articles in a journal. However, the free text input field makes it easy to introduce inconsistencies due to human error or misunderstanding.

**Describe the solution you'd like**
Two solutions have been proposed in the discussion below:

1. Auto-generate labels based on the uploaded file type.
2. Use an autocomplete field so that common label names were easy to select instead of typing in manually.

**Who is asking for this feature?**
See below.

**Additional information**
The original post is below:

> As above. OJS 2.x would auto-generate labels for HTML and PDF files uploaded as galleys (per file mimetype). Though these labels were (and should still be) editable, it provided a reasonable default and minimized inconsistencies (typoes, etc.). Consider reimplementing this for: 
>
> HTML
> PDF
> ePuB
> XML
> other?

**Comment by ajnyga** [comment]
I totally agree, but I guess the problem here is that the file is uploaded after the label is given. But maybe that could be reversed.

**Comment by asmecher** [comment]
The order of entry (metadata first, then upload) is implemented as is so that the user can first identify whether the galley is a remote file or not, then if local, upload the file. It wouldn't be possible to reverse the order without considering this too.

**Comment by larsvilhuber** [comment]
Alternatively, allow for dropdown menu that pulls 
- from pre-defined list (configurable per component or globally)
- from previous entries (allowing de-facto standardization)

My key concern would be consistency across entries over time, not necessarily consistency with mime-types.

**Comment by larsvilhuber** [comment]
👍

**Comment by MarHerUMR** [comment]
I think a dropdown would be great for consistency purposes. We had the problem with `pdf`and `PDF` galleys. The recognition of the file file type would not be as useful for us.

**Comment by asmecher** [comment]
I think you're essentially proposing an autocomplete, @larsvilhuber? A dropdown wouldn't permit the entry of previously-unseen labels, so a dropdown offering only previous selections wouldn't work.

Most journals use the labels to identify the file format (PDF, HTML, etc), but we don't prescribe that, and I don't doubt that some journals use the labels in entirely different ways...

**Comment by larsvilhuber** [comment]
@asmecher I was proposing an autocomplete based on site-specific prior entries/ other entires. That way, sites can dynamically build up the ones they want, while keeping consistency.

**Comment by larsvilhuber** [comment]
That being said, I think it might also be feasible to have a configurable component that *forces* compliance with a pre-defined list. As you point out, some sites might use these in an entire different way, so that should be functionality that could be turned off (default) or on.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
