### ISSUE TITLE
Ojs3.1, how to set email

### ISSUE THREAD

**Issue by doudou911** [pkp/pkp-lib#3105]
I want to send email by ojs. (Not gmail) Can anybody help me where and how to set mail successful? I am a OJS novice. Please provide me more details about this. I’m looking forward to hearing from you. Thank you very much.

**Comment by asmecher** [comment]
@doudou911, I see you've already asked this question on [our forum](https://forum.pkp.sfu.ca/t/ojs2-4-8-2-how-set-email/35427). That's the best place to get feedback.
