### ISSUE TITLE
choose e-mail template when selecting a reviewer

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3106]
The e-mail template body is not changed in the textarea field -- this is not implemented in the JS handler...

S. https://forum.pkp.sfu.ca/t/review-request-subsequent-mails-not-doing/32102

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3115
ojs master: https://github.com/pkp/ojs/pull/1725 (only submodule update)

pkp-lib ojs-stable-3_1_0: https://github.com/pkp/pkp-lib/pull/3116
ojs ojs-stable-3_1_0: https://github.com/pkp/ojs/pull/1726 (only submodule update)

**Comment by NateWr** [comment]
@bozana the code looks good. I noticed that the Review Request Subsequent template is always used when adding a reviewer on the second round, even if the selected reviewer didn't participate in the first round.

Is that intentional? The language of the Review Request Subsequent template seems like it is only intended to be used when the same reviewer is added on the second round...

**Comment by bozana** [comment]
Hi @NateWr. Hmmm... It seems it is meant to be so, s. https://github.com/pkp/pkp-lib/issues/2655. But also, maybe I am reading/understanding it wrong, but the text of the email template REVIEW_REQUEST_SUBSEQUENT does not sound to me like it has to be the same reviewer. What part do you exactly mean? THANKS!!!

**Comment by NateWr** [comment]
If it's intended behaviour, go ahead and merge. I was just checking.

> Following the review of the previous version of the manuscript, the authors have now submitted a revised version of their paper.

The way that's phrased sounds to me like the recipient is expected to be familiar with the submission. Even changing the first "the" to "a" might make a difference. For example:

> Can you look at the commit I made?

You might think it is a commit on a PR we've talked about before.

> Can you look at a commit I made?

You'd assume I'm talking about something new.

I think? Now I want a second opinion. :)

**Comment by bozana** [comment]
Aaaaaaaaaa.... I see.... :-)
Maybe @stranack or @asmecher can better tell?
I will gladly fix it ;-)

**Comment by bozana** [comment]
I will then go ahead and merge the current changes and see what to do with that, OK?

**Comment by NateWr** [comment]
:+1:

**Comment by asmecher** [comment]
> Following the review of the previous version of the manuscript, the authors have now submitted a revised version of their paper.

Dangerous business, asking for more opinions :)

I would change to...

Following the review of the previous version of a manuscript, the authors have now submitted a revised version.

...i.e. go woth "a manuscript", but I've also removed "...of their paper".

**Comment by bozana** [comment]
:-D I think this starts to be metaphysical for me... :-DDD

**Comment by bozana** [comment]
I will close the issue -- just to know that it is ready for release, but discussion about the e-mail template text can goo on... And I can then change it, if necessary...
