### ISSUE TITLE
Duplicated literal

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#3108]
Same literal in same file:

```
<message key="submission.list.viewSubmission">Ver {$title}</message>
...
<message key="submission.list.viewSubmission">View Submission</message>
```
Code: https://github.com/pkp/pkp-lib/blob/61d894b4f7fa6865e5ccae3f6a34f058311acca9/locale/en_US/submission.xml#L604

**Comment by asmecher** [comment]
The one with the `{$title}` variable isn't used. I've removed it, thanks! (`master` and `ojs-stable-3_1_0`)
