### ISSUE TITLE
Provide authors with opportunity to proofread/preview their HTML and other non-PDF formats

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3109]
Asking authors to proofread galleys before publication works well for PDFs (upload a copy in a production discussion).

However, allowing authors to see HTML or XML in the context of the journal isn't possible. Sharing the raw HTML file (it doesn't even include the CSS) is often useless for most authors.

It would be great to have a way to allow an author access to a preview of just their article page before publication.

This would apply to both OJS and OMP.

**Comment by NateWr** [comment]
It is now possible for an author to access the preview of a submission.
