### ISSUE TITLE
[OJS] disable_path_info = on not respected in AJAX requests

### ISSUE THREAD

**Issue by garyross** [pkp/pkp-lib#3110]
Having logged in the AJAX requests don't respect disable_path_info = on with Version 3.1.0
with 
`disable_path_info = on`

Expected request is this:
`/index.php?journal=FOO&endpoint=/FOO/api/v1/_submissions`

Actual request is this:
`/index.php/FOO/api/v1/_submissions?journal=FOO&endpoint=/FOO/api/v1/_submissions`

The erroneous `/FOO/api/v1/_submissions` after the `/index.php` in the latter breaks setups using NGINX etc giving a 404 error, and popping up an error window. 

For now a workaround is to modify the `nginx.conf` file adding:

`rewrite ^/index.php/.* /index.php break;`

**Comment by kaschioudi** [comment]
@asmecher 

https://github.com/pkp/pkp-lib/pull/3251

https://github.com/pkp/ojs/pull/1784

**Comment by NateWr** [comment]
This has been fixed in more recent versions.
