### ISSUE TITLE
Select precedent reviewer for a new round failed

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3114]
Hi
i'm using ojs 3.1
For a new review round for a submission, i use advancedSearchReviewerForm.
I'm doing a search for ' Reviewers from this submission previous review rounds'.
I select the corresponding reviewer and, next I validate the form 'Add Reviewer' with email and important date.
And then i have this error in my log :` ojs2: Invalid reviewer id.`
I do some debug, and see that in th erequest, reviewerId = 'on', not the real id of the reviewer.

Thank you

**Comment by forgive38** [comment]
Maybe this is a workaround :
```
diff --git a/js/controllers/grid/users/reviewer/AdvancedReviewerSearchHandler.js b/js/controllers/grid/users/reviewer/AdvancedReviewerSearchHandler.js
index 3c7bef1..f13c733 100644
--- a/js/controllers/grid/users/reviewer/AdvancedReviewerSearchHandler.js
+++ b/js/controllers/grid/users/reviewer/AdvancedReviewerSearchHandler.js
@@ -60,7 +60,7 @@
 
                // Get the selected reviewer's ID
                var $selectedInput = this.getHtmlElement().
-                               find('#reviewerSelectGridContainer').find('input:checked'),
+                               find('#reviewerSelectGridContainer').find('input[type=radio]:checked'),
                                reviewerId = /** @type {string} */ ($selectedInput.val()),
                                reviewerName;
 

```

**Comment by asmecher** [comment]
Thanks for reporting and helping to narrow down the problem. I'd suggest this resolution:

- Patch https://github.com/pkp/pkp-lib/commit/767aadc7ea77a4f7d9f0a789a951757bec23c525 in `lib/pkp`
- If you're using minified JS, you may also have to patch https://github.com/pkp/ojs/commit/1a03e572226537b708ff7d16ad9f828bc5f25cea (in the application's installation directory)
