### ISSUE TITLE
Profile "change password" link is broken

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#312]
See http://pkp.sfu.ca/support/forum/viewtopic.php?f=40&t=13711

**Comment by asmecher** [comment]
Note: NOT ported to master, as http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8891 has not been ported yet. Sent @beghelli an email.

**Comment by straderg** [comment]
When should we expect 1.1.2 to be applied, or can PKP apply this fix to Open SI (on OMP) directly for me?

**Comment by asmecher** [comment]
@straderg, I've cherry-picked this commit into your installation. Let me know if you have any trouble.

**Comment by crism** [comment]
This really needs to be put into production; the [recommended download](http://pkp.sfu.ca/omp/download/omp-1.1.1-1.tar.gz) still has this bug.

**Comment by asmecher** [comment]
We decided to release OMP 1.2 rather than 1.1.2 but it's taken longer than expected.
