### ISSUE TITLE
Author name in export plugins

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3125]
Hi, OJS team! a little issue: at the page of DOAJ export plugin, when I was looking for a paper, I can note a change in the author of an article, but when I look the metadata all is OK! The issue is on the page "DOAJ Export Plugin", here the first author that is showing is Primary Contact instead of the first one.  

see the gif: 
![2017-11-28 12_23_54](https://user-images.githubusercontent.com/5422984/33327769-169308b8-d437-11e7-9a1c-db1f48340543.gif)

or the same video on YouTube: https://youtu.be/vXEjEmn_yjA

Again I want to thank the team, for all the advances in making OJS better every day!

**Comment by bozana** [comment]
Thanks @t4x0n!
I would agree that the first author name should be there -- it is usually how also the authors are cited and the article remembered -- the primary contact has a different function in the system, I believe. 
@asmecher, would you agree?

**Comment by asmecher** [comment]
Yes, agreed.

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3139
ojs master: https://github.com/pkp/ojs/pull/1734

**Comment by bozana** [comment]
@NateWr, could you take a look at the PRs?

**Comment by NateWr** [comment]
@bozana I had a look at how we're using `getShortAuthorString()` and actually I think it should list the first named author, the same as `getAuthorString()`.

We used `getShortAuthorString()` in our old submission grids, and I can see why the primary corresponding author might have been useful there. But we're using full author(s) strings now, and it makes sense to me to standardize on the first named author. In fact, when we move the export grids over to the new lists, we can probably get rid of `getShortAuthorString` entirely.

**Comment by bozana** [comment]
ok, so I will then change it to only i.e. always use the first author name, right? THANKS!!!

**Comment by NateWr** [comment]
:+1:

**Comment by asmecher** [comment]
^ Thanks for catching this, Nate -- I answered too quickly.
