### ISSUE TITLE
Single place for journal-wide and/or issue-wide article CSS upload

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3129]
It is great that OJS (and OMP) allow editors to upload a CSS file for each HTML galley (articles or chapters). This provides a lot of flexibility and allows each article to potentially have a different look. 

However, it would be additionally helpful to have **one** place to upload an article (or chapter) CSS file -- either journal-wide or issue-wide (or both). 

In my experience, I'm uploading the exact same article CSS file over and over again for each HTML galley (and if I need to make a change, need to re-upload for each and every HTML galley).

This isn't a huge priority but would be more efficient for most use cases.

**Comment by asmecher** [comment]
You should be able to refer to the journal-wide stylesheet from within the HTML galleys... We don't currently have a place for issue-specific CSS.

**Comment by NateWr** [comment]
Support for theme-specified galley styles was added in https://github.com/pkp/pkp-lib/issues/3691 but has not yet been documented. See https://github.com/pkp/pkp-docs/issues/156.
