### ISSUE TITLE
Section Policy is not shows on frontend

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3134]
Hello,

In Settings > Journal > Sections, in the popup for "Edit or add a Section" you can add a Section Policy. But this text really is not shown in any place on the website! 

![policy](https://user-images.githubusercontent.com/5422984/33359469-a6587b6a-d4ad-11e7-97cb-0580ceb563ec.png)

**Comment by t4x0n** [comment]
I ask in the forum, but no one answer... (https://forum.pkp.sfu.ca/t/ojs-3-1-jornal-section-policy/35660) 
 and I look again but I can't find one place where this text is shown.

**Comment by asmecher** [comment]
Hi @t4x0n -- I've posted a link from the forum to this github entry as well. (If you do post in multiple places, make sure they all link to each other -- otherwise the conversation can be divided into several places.)

**Comment by t4x0n** [comment]
Ok, thank you @asmecher

**Comment by budulinek** [comment]
Hi, I also need Section Policies being displayed. 
Thanks

**Comment by bozana** [comment]
I believe this issue means the same: https://github.com/pkp/pkp-lib/issues/2638

**Comment by t4x0n** [comment]
Yes @bozana,  is the same issue!

**Comment by NateWr** [comment]
Closing as duplicate.
