### ISSUE TITLE
a string was missed in locale.xml

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3141]
The string "log.editor.submissionExpedited" is missing, even in English. I just find it only in Norway translation (locale/nb_NO/locale.xml). I think this is a string from the legacy of OJS 2, and so when we update to OJS 3 some texts are missing in the article history. I try to replicate this in the current process but I can't so I think this is just for old articles history. 
![image](https://user-images.githubusercontent.com/5422984/33410919-578f6534-d561-11e7-8df1-98f4d18afc3b.png)

My suggestion is to add this string to the latest line in locale.xml, in a separate section like:
`<!-- legacy strings from OJS 2, for upgraded installations from OJS 2  -->`
`<message key="log.editor.submissionExpedited">{$editorName} has taken the edit process for the article {$submissionId}.</message>`

**Comment by asmecher** [comment]
Agreed, thanks -- I've committed your proposal.
