### ISSUE TITLE
Fix cyrillic support in citationStyleLanguage

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3143]
Just leaving a record of this change for the future. citeproc-php needs to be updated. See pkp/citationStyleLanguage#15.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/1738 (`master`)
https://github.com/pkp/ojs/pull/1739 (`ojs-stable-3_1_0`)

Tests running.

**Comment by asmecher** [comment]
This one didn't make it into OJS 3.1.0-1 -- scheduling for OJS/OMP 3.1.1. (Of course, if we do put together a 3.1.0-2 for some reason, it could go there, so no harm in committing it to the `ojs-stable-3_1_0` branch whenever you're ready.)

**Comment by NateWr** [comment]
The changes got pulled into `master` with some translation updates and I merged the changes to `ojs-stable-3_1_0`. Closing.
