### ISSUE TITLE
NavigationMenus - Warnings removed for custom menuItems

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#3144]
See also #3056

**Comment by defstat** [comment]
@asmecher I erased the warnings displayed at custom MenuItems edit, separately from the changes for the StaticPages vs CustomNavigationMenuItems.

PRs
pkp-lib: #3145
OJS: pkp/ojs#1741
OMP: pkp/omp#480

**Comment by defstat** [comment]
@asmecher 

**Stable**
PRs
pkp-lib: #3146
OJS: pkp/ojs#1742

**Comment by asmecher** [comment]
Merged all, thanks!
