### ISSUE TITLE
Licensing info in OTS-generated galleys

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3147]
One of the application requirements for the DOAJ is for journals to include licensing information on each of their published PDFs, HTML, etc.

https://doaj.org/application/new#license_embedded-container

Most of our journals are not doing this, and we can't currently enforce it, as galleys are created outside of OJS.

Would galleys generated by OTS be able to pull the licensing information from OJS and include it, either by default or as an option?

Alec notes: The OAI JATS plugin is already coded to stamp the JATS XML upon delivery with the licensing information from OJS.

More broadly, we need to figure out how to treat data that's stored both in OJS and in JATS XML, i.e. how to handle updates to each, whether one is to be considered "definitive", etc.  

Use:
Article::getCopyrightYear
Article::getLicenseUrl
Article::getCopyrightHolder (values are localized)

**Comment by ajnyga** [comment]
> More broadly, we need to figure out how to treat data that's stored both in OJS and in JATS XML, i.e. how to handle updates to each, whether one is to be considered "definitive", etc.

Regarding this issue, I think it would be the easiest if the whole `front` section of JATS XML would always be structured from the OJS metadata AND every time you would edit the OJS metadata, also the `front` section of existing JATS XML galleys would be changed automatically.

This would mean that the Texture editor would only apply to the `body` and `back` sections of the document. No point of having to interfaces for editing metadata.

Another option could of course be that JATS XML documents would be created dynamically when requested. Meaning that when one is requested OJS would create the `front` section from the available metadata and the rest (`body` and `back`) could be saved either in an actual galley file or in the database and attached to the served document.

**Comment by NateWr** [comment]
Closing this as outdated. The OTS is no longer receiving new features.
