### ISSUE TITLE
OAI 'dc:source'  locale issue

### ISSUE THREAD

**Issue by vasylOstrovskyi** [pkp/pkp-lib#3148]
When using multilingual site, the 'dc:source' field of record is written wrong: the second part (vol, no, year, title) is always given in the primary locale. Like this:

`
<dc:source xml:lang="uk-UA">Праці Інституту математики НАН України; Том 12 № 1 (2015): Спектральна теорія операторів та наборів операторів; 6-7</dc:source>
<dc:source xml:lang="en-US">Proceedings of Institute of Mathematics, NAS of Ukraine; Том 12 № 1 (2015): Спектральна  теорія операторів та наборів операторів; 6-7</dc:source>
`
I found, that the problem arises in the file `ojs/plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.inc.php`, line 168, where the function `getIssueIdentification()` is called which returns data in the same locale.

I suggest to add the $locale argument to `getIssueIdentification()` and modify its source slightly (I did it for myself but not sure that this wil not cause other problems)
Regards,
 Vasyl

**Comment by asmecher** [comment]
@vasylOstrovskyi, I presume you're asking about OJS. What version are you using?

**Comment by vasylOstrovskyi** [comment]
@asmecher Yes, OJS version 3.1.0 official production version

**Comment by asmecher** [comment]
@vasylOstrovskyi, your suggestion makes sense -- it sounds like you have a potential solution already coded, too. Could you open a PR and link it back to this issue?

**Comment by vasylOstrovskyi** [comment]
@asmecher  Created PR #1780 with a fix

**Comment by asmecher** [comment]
Thanks again, @vasylOstrovskyi!
