### ISSUE TITLE
Problems with version 3.0.0.0

### ISSUE THREAD

**Issue by tinde123** [pkp/pkp-lib#3152]
Hi, we just updated from version 2.4 something. I feel really stupid, but when I try to upload a new publication with Quick Submit Plugin, there's an error "At least one author must be added". The problem is that here's no fiekd for authors.

Other thing is that in the new version shows only the first page of the publiced papers with title, authors and abstract and a link to html-version. The link is broken.

We run our system at www.sjlas.org. 

I'd be more than happy if anyone had any answers.

thanks in advance

-tinde

**Comment by asmecher** [comment]
@tinde123, if you're using OJS 3.0.0.0, I'd strongly suggest working with the latest release (currently OJS 3.1.0-1). There are tons of bug fixes and improvements since 3.0.0.0.

**Comment by tinde123** [comment]
thanks, I'll do that and let's see what will be fixed.

-tinde

**Comment by tinde123** [comment]
I checked today and actually we're running on 3.1.0-0..

**Comment by bozana** [comment]
Hi @tinde123, I think this question is better suited for the PKP user support forum: https://forum.pkp.sfu.ca/. Could you maybe post it there? Once we realized for sure that it is a bug/issue, the GitHub Issue can be created.
Maybe you can also give us some more information, e.g. if it is a clean installation or an update, how did you upload those HTML galley files, etc.
The authors should be inserted using the "Add Contributor" link in the "List of Contributors" grid in the QuickSubmit plugin.
Thanks!
