### ISSUE TITLE
Error checking email format in profile page

### ISSUE THREAD

**Issue by alireza08** [pkp/pkp-lib#3154]
Hello,
I found that correct email format in the contact tab of user profile page in (OJS3.1.0.1), is not checked. so, I added this line to the correct PHP file and it works. 
`$this->addCheck(new FormValidatorEmail($this, 'email', 'required', 'user.profile.form.emailRequired'));`

However, a strange pop-up window occurs and I can' figure out where it comes from (attached screenshot)
![1](https://user-images.githubusercontent.com/7510737/33527801-20785c00-d86c-11e7-8351-1ed55f471583.png)

**Comment by asmecher** [comment]
Thanks, @alireza08, I've added your fix and another minor change that resolves the pop-up. Check the commits listed here (both are equivalent, just applied to different branches).
