### ISSUE TITLE
required tagit metadata fields not validated

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3157]
Those metadata fields that use tagit are not validated correctly.
S. also https://forum.pkp.sfu.ca/t/disciplines-required-not-passing-although-field-is-completed-ojs-3-1/34747/3

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3158
ojs master: https://github.com/pkp/ojs/pull/1747 (only submodule update)

pkp-lib ojs-stable-3_1_0: https://github.com/pkp/pkp-lib/pull/3159
ojs ojs-stable-3_1_0: https://github.com/pkp/ojs/pull/1748 (only submodule update)

**Comment by bozana** [comment]
@NateWr, could you take a look at the PR above?

**Comment by NateWr** [comment]
I left one comment in the code, just trying to get my head around it.

I also ran into a couple of related issues. I've added disciplines and set it to required. I've added some items to the discipline tag it and saved it. Now if I go back and remove them and save it, the form saves successfully, but the tags are still t here.

Also, if I go to a submission without any disciplines and I submit the form, I get an unhelpful error message:

![selection_058](https://user-images.githubusercontent.com/2306629/33605903-7a546398-d9b3-11e7-93cf-ff95bcf2a4f3.png)

Is there any way we can improve that?

**Comment by NateWr** [comment]
> Do you see the same error message but in the very background, on the page behind the modal, thus almost invisible? 

Oh I do see it. It looks like it is getting embedded into the body of the page instead of flying up the side. Looking at the response to the ajax request, it looks like it's returning an `inPlace` notification. Maybe there's some setting of the notification that's off?

![selection_059](https://user-images.githubusercontent.com/2306629/33610397-5893a39e-d9c3-11e7-991e-68a83765d1d2.png)

**Comment by bozana** [comment]
@NateWr, I've added the appropriate form validation locale keys.
I still do not understand why the errors are displayed on the page :-P -- will take a further look tomorrow...

**Comment by bozana** [comment]
@NateWr, now that the submission metadata form validation messages are correctly displayed, I think this issue is finished. Could you take a final look? THANKS!!!

**Comment by NateWr** [comment]
New PRs which I'll merge when the tests pass:
https://github.com/pkp/pkp-lib/pull/3241
https://github.com/pkp/ojs/pull/1781

**Comment by NateWr** [comment]
All merged.
