### ISSUE TITLE
Unchecked Volume / Issue / Year info should not appear on Archives page

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3160]
When an issue is created that has not checked Volume, Issue, or Year in Issue Data, they should not appear as zeros on the Archives page.

For example:
Fall 2017
Vol 0 No 0 (0)

See: http://journals.sfu.ca/courses/index.php/pub371/issue/archive

If those elements are not checked, could they be suppressed entirely from public display?

**Comment by stranack** [comment]
Only "title" is checked on the Issue Data tab.

**Comment by bozana** [comment]
Hmmm... For some reason I cannot reproduce it :-( -- When I only check "title", then I have to enter the title and then the title is also displayed on the archive page...
Do you maybe know exact steps how to reproduce it? THANKS!

**Comment by bozana** [comment]
I believe this was fixed/changed in this Issue: https://github.com/pkp/pkp-lib/issues/1907.
