### ISSUE TITLE
nl2br causes extra line breaks in copyright notice

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3161]
`nl2br` is called on the copyright notice, on the frontend submissions page. It shouldn't need this since it is a tinymce field.

Reported: https://github.com/NateWr/bootstrap3/issues/70

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/3162
https://github.com/pkp/ojs/pull/1749
https://github.com/pkp/omp/pull/482

@bozana can you code review?

**Comment by bozana** [comment]
Merged and closing...
