### ISSUE TITLE
[OJS] Adding methods to get width and height of the issue cover image

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3164]
Dear all,

right now the size of a issue cover is (no longer?) saved into the database. I tested reuploading issue covers with the latest code from github but no information for width and height get's saved. I had a look a the uploading code (and when I didn't overlook something) there's nothing in place to save the width and height.

The `SubmissionArtworkFile` actually provides `getWidth` and `getHeight` methods. I would propose to have `getCoverImageWidth` and `getCoverImageHeight` methods for the `issue` object, working like those of the `SubmissionArtworkFile`.

What do you think?? I can provide a pull request for that.

Best regards
Markus

**Comment by NateWr** [comment]
Closing for lack of interest but we'd be happy to have a PR that supported this.
