### ISSUE TITLE
[OJS] announcementFeed got lost in download version of ojs

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3165]
I noticed today that the announcement feed plugin was missing in my test installation, that was installed from the tar.gz download.

Comparing the plugins/generic folders from the repo and the tar.gz there are more plugins missing in the tar.gz:

* announcementFeed
* backup
* browse
* externalFeed
* lucene
* phpMyVisites
* recommendBySimilarity
* translator

Is there a reason why those plugins are missing??

**Comment by asmecher** [comment]
@MarHerUMR, the package biuld tool (`tools/buildpkg.sh`) lists several directories that should be excluded from the `.tar.gz` -- including a number of plugins that are present in the github repo but not the release. There are two reasons for these being listed...

- The plugin needs attention, e.g. a rewrite from the 2.x codebase level to the 3.x level, and that work hasn't been done yet, or
- The plugin is intended for installation via the Plugin Gallery. (We're trying not to distribute too many plugins with the `.tar.gz`.)

IIRC the Announcement Feed plugin needs some rewriting, so it's in the first category.
