### ISSUE TITLE
[OJS] New discussion canceled but still in discussion list

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3167]
Hi,
seems to be same issue as : #2794 
there is no csrf with the delete request.

Thank you
OJS 3.1

**Comment by asmecher** [comment]
@forgive38, are you using OJS 3.1.0-0, or 3.1.0-1? Is it an option to test with 3.1.0-1, which has a number of minor fixes and tweaks?

**Comment by forgive38** [comment]
I tested with 3.1.0-1, there is the same behavior
thanks

**Comment by asmecher** [comment]
Yes, I replicated this behavior myself. Try either of the two patches above -- they are equivalent -- applied in the `lib/pkp` subdirectory; they resolve it for me.

**Comment by forgive38** [comment]
I works for me too.
Thank you
