### ISSUE TITLE
Use vue-fontawesome in ui-library

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3170]
There's a useful npm module for integrating fontawesome with vue.js. 

https://www.npmjs.com/package/@fortawesome/vue-fontawesome

It's compatible with the new fontawesome5 and allows us to subset the full package easily with a "library".

**Comment by NateWr** [comment]
@jardakotesovec and @Devika008 feel free to close this if you want. It was something I intended to do but never got around to it. And Devika, I know you may want to change the icon library that we are using now.

**Comment by asmecher** [comment]
@blesildaramirez, I think you've addressed the base requirement here -- is this issue still necessary?

**Comment by jardakotesovec** [comment]
Closing as we moved to svg icons in vue.js
