### ISSUE TITLE
[OMP] Navigation menu items for new releases, categories and series

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3171]
Navigation menu item types should be available for linking to the new releases page, and any category or series page.

An example of how I did this for the OJS `browseBySection` plugin can be seen [here](https://github.com/pkp/browseBySection/blob/master/BrowseBySectionPlugin.inc.php#L218-L243).

**Comment by defstat** [comment]
@NateWr I added the following PRs regarding that Issue. 
The user has access to 3 more NMI types: for Category and Series the user can define the Category and Series he/she wants to point to.

I added some hooks to add the specific types for OMP categories and series and add functionality to the add/update NMIs form. (not sure if it was the "right" way to do it - maybe a derived class for OMP could be a better solution)

I didn't find a way to "hook" template+Javascript functionality to the lib-pkp form .tpl template. Do you have any examples regarding that?

pkp-lib: #4008
omp: pkp/omp#592

**Comment by NateWr** [comment]
Looks good @defstat. I think that you can avoid the extra hooks and reduce the app-specific code that is required by just creating a custom navigation menu item for each series and category.

The BrowseBySection plugin does something similar to create a NMI for each section's landing page. You can see here that two pre-existing hooks were used to create a custom NMI entry for each section:

https://github.com/pkp/browseBySection/blob/master/BrowseBySectionPlugin.inc.php#L38-L39

And those hooks are executed here:

https://github.com/pkp/browseBySection/blob/master/BrowseBySectionPlugin.inc.php#L213-L274

This way users can see an option for each section right in the list, you avoid having to use all the form hooks, and you don't need to modify the JS handler to show/hide extra form options.

Do you think that approach might work for this issue? If so, it might simplify some of the code we'll have to maintain in OMP.

**Comment by NateWr** [comment]
I can see the benefit of having a structure in place for NMI types with additional options. As you found, though, with our existing JS controllers, you still need to write bespoke code to conditionally display each set of options.

The new form system we're working on (#3594) should make it easier to write in conditional display logic, without having to do it for each form component that needs it. So I'm tempted to prefer the simpler approach in this case. 

But if you want to go forward with the editing-after-selecting approach, I can suggest some ways to keep the OMP-specific code out of pkp-lib.

**Comment by defstat** [comment]
I am working on a schema where a NMI type can be matched to a template (.tpl). That template could be added to the form tpl like 
`<div id='NMI_TYPE_SOMETHING'> {NMI Specific template} </div>` 

After that, the form's javascript could define a generic rule like: "if the NMI_TYPE_SOMETHING is selected, show the div with the correct id and hide all other divs"

I could add that to the PR to see how it works.

**Comment by NateWr** [comment]
:+1: go for it

**Comment by defstat** [comment]
@NateWr I added the mentioned functionality.

**Comment by defstat** [comment]
@NateWr I have concluded the review. 

I added the OMP specific form which I am calling from the grid handler in pkp-lib code. is that correct? if yes i should do the same for OJS, even though there are no additional types for OJS....

**Comment by NateWr** [comment]
:+1: Looks good @defstat. I did some manual testing and all is working as expected.

> I added the OMP specific form which I am calling from the grid handler in pkp-lib code. is that correct? if yes i should do the same for OJS, even though there are no additional types f'll or OJS....

Yeah you'll need a dummy class for OJS, but it can be empty like this:

```
class NavigationMenuItemsForm extends PKPNavigationMenuItemsForm { }
```

**Comment by defstat** [comment]
@NateWr review comments fixed.

Just adding that comment to have all PRs together. pkp-lib and omp PRs are the same that we where working on. OJS PR added. Waiting for tests to pass on OMP/OJS.

PRs:
pkp-lib: #4008
omp: pkp/omp#592
ojs: pkp/ojs#2118

**Comment by NateWr** [comment]
Great @defstat. It looks like you've just got one JS linting error to fix:

https://travis-ci.org/pkp/omp/jobs/428255357#L1086

Otherwise it's good to go!

**Comment by defstat** [comment]
@NateWr Tests have passed!

**Comment by NateWr** [comment]
:+1: merged! Nice work!
