### ISSUE TITLE
[OJS] enable_beacon and other little things

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3172]
In Template file for config file is setting enable_beacon = On, but when I do install process this "On" is changed by 1.

In the install, the instruction says to compare with TEMPLATE, so I change my olds installations to "On" but now, in a new installation OJS 3.1.0-1, the process change to 1 again... Probably some piece of code is not updated!

and, what is the right variable here? On or 1?  

Other Little Things, these variables "On" are in minuscules:
recaptcha = on
captcha_on_register = on

**Comment by asmecher** [comment]
@t4x0n, I've never seen a `1` get filled into the config file before -- is there anything unusual you're doing?

However, `On` (which `ConfigParser` maps to `true`) should work equivalently to `1`, as we're using tests like

    if (Config::getVar('general', 'enable_beacon', true)) { ... }

...which doesn't discriminate between `true` and `1`.

**Comment by asmecher** [comment]
@t4x0n, feel free to add feedback if this is still an issue, but I'll close it for now.

**Comment by t4x0n** [comment]
sorry @asmecher  for my delay and not replying before... is weird in my case always I see enable_beacon = 1  after configuring OJS
for now, I can't try anything but I will keep this in mind, and when I have time I will make some tests, for now, close is ok!

**Comment by asmecher** [comment]
Ah, never mind, I found it anyway! FYI, this is cosmetic -- `1` and `On` should both work equally well.

**Comment by t4x0n** [comment]
Excellent!
