### ISSUE TITLE
[OJS] Issues and improves for Announcements 

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#3176]
I have some proposals to improve the Announcements:

- **Delete the Expiry Date**: this is an issue, it is not possible to delete the Expiry Date of the announcement, it still exists in the database.
- **Allow changing the date**: There are ads that I would like to save to use later, for example an announcement for Scheduled Maintenance, but when is using it again the date that appears is the same as when the ad was created, it would be good to change the publication date.
- **Read more Optional**: There are announces that are very small and do not need a longer description. In that case, if you do not write a long description you should not show "Read more" in this announcement.
- **Show the date Optional**: There are announcements that do not need a date of publication, there should be the option of not showing date.

I hope I was clear...  If you have any questions, do not hesitate to ask me!

**Comment by asmecher** [comment]
@t4x0n, these all sounds like reasonable proposals to me! Is this something you intend to work on, or just a feature request for other devs?

**Comment by t4x0n** [comment]
Hi @asmecher, I would like to, but my php skills are limited, and I do not know either bootstrap or smarty ... at this moment I am working more as a journal editor (that's why I can find more issues than solve them 😅 ), I would really appreciate it if some developer made those improvements 💪

**Comment by asmecher** [comment]
@t4x0n, thanks, just making sure we don't end up with two groups working on the same thing!

**Comment by t4x0n** [comment]
of course! you can assign this to any developer that you want! 
thank you!

**Comment by NateWr** [comment]
A couple quick comments:

> Read more Optional: There are announces that are very small and do not need a longer description. In that case, if you do not write a long description you should not show "Read more" in this announcement.

It's good SEO and UX for each piece of content to have it's own URL. Even a brief announcement should still have a URL that is linked to.

> Show the date Optional: There are announcements that do not need a date of publication, there should be the option of not showing date.

If that's the case, it may not be right to make it an announcement. It's more likely that you should be using a custom page via Navigation Menu Items (or Static Pages). If you still want it to appear in your announcement feed, you can make an announcement about the new content that's been added. But announcements themselves should be pegged to a date for SEO reasons.

**Comment by suburban-journal** [comment]
I have another proposal to improve announcements:

- **Users should be able to filter announcements by type (as defined in announcements > announcement types) on the announcement page**. This would significantly enhance this page and could make the manual creation of custom pages obsolete. Find more background information and application scenarios here: https://forum.pkp.sfu.ca/t/filter-announcements-by-announcement-type-ojs-3-2-1-2/65671

Please ask me, if you have any questions.

**Comment by NateWr** [comment]
The request to allow users to browse by announcement types is filed at https://github.com/pkp/pkp-lib/issues/2222. The other suggestions here regarding announcement dates would be better implemented through custom pages rather than announcements. 

Closing this for now, but please open a new issue if there is a specific feature that you'd like to discuss.
