### ISSUE TITLE
Replace calls to deprecated "create_function"

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3177]
PKP's `create_function` function is depreacated as of PHP7.2, and real lambda functions are supported going back to PHP5.3ish. Replace calls to `create_function` with real lambda functions.

**Comment by asmecher** [comment]
Pulls:
- https://github.com/pkp/pkp-lib/pull/3183
- https://github.com/pkp/ojs/pull/1760
- https://github.com/pkp/staticPages/pull/29

**Comment by asmecher** [comment]
@bozana, would you mind reviewing these PRs? Thanks!

**Comment by bozana** [comment]
Great work @asmecher! Just a few minor comments...

**Comment by asmecher** [comment]
All merged. Thanks for the review, @bozana!
