### ISSUE TITLE
Link on context logo/title in frontend incorrect

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3178]
In a multi-journal setup, the logo or title of a journal links back to the site-wide index page instead of the journal index page. The conditional check that delivers different URLs for a single-journal or multi-journal setup is inverted.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/3179
https://github.com/pkp/ojs/pull/1756 (tests only)
https://github.com/NateWr/bootstrap3/pull/74

@bozana would you code review?

**Comment by bozana** [comment]
@NateWr, great! You can then merge... THANKS!!!

**Comment by NateWr** [comment]
Merged.
