### ISSUE TITLE
[OJS] Author can not see Editor decision if article get declined without peer-review

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#3187]
When a article gets declined without a peer-review there is not a notification section with reasons to such editorial decision. It would be  useful to author an editor record decision with reasons for future consult to them both.

Forum post: 
https://forum.pkp.sfu.ca/t/author-can-not-see-editor-decision-if-article-get-declined-without-peer-review-ojs-3-1/36127

**Comment by jmacgreg** [comment]
I think this is now taken care of with the distinction in separate editorial decisions (and emails) for rejecting at the Summary page vs. rejecting at the Review page.

**Comment by jmacgreg** [comment]
Reopening (see https://forum.pkp.sfu.ca/t/the-author-is-unable-to-see-the-editorial-decisions-recorded-at-submission-stage-on-ojs-3-2-0-3/61220/6). I misunderstood what the root problem was here - it wasn't that a desk reject option wasn't available, it's that the OJS interface included no information on that decision after the fact, so authors only have the decision notification email to go by - and sometimes, they may not get those.

**Comment by NateWr** [comment]
As part of #7265, the author notification will be logged and shown to authors as well. This can be closed once that is implemented.
