### ISSUE TITLE
Allow <script> tags in custom blocks

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3190]
By default new blocks created via the custom block manager strip out <script> tags. This prevents JMs from adding embed codes to custom blocks that rely on <script> tags to work, e.g. a Twitter timeline.

**Comment by asmecher** [comment]
I'm not enthusiastic about opening up TinyMCE controls for entering arbitrary JS; perhaps either a Twitter block (that isn't created via the custom block plugin), or a snippet of code that can be applied to allow `<script>` elements, but isn't part of the distributed software?

**Comment by linah-kareem** [comment]
how to add script tag to any custom block ?

**Comment by mfelczak** [comment]
Hi @asmecher, for the code snippet, are you thinking something generic that could be used across the custom block manager, e.g. "<embed-code>[Twitter embed code]</embed-code>? This would have the benefit of being more generally applicable relative to a dedicated sidebar block, i.e. for other embed codes and 3rd-party services.

**Comment by asmecher** [comment]
@mfelczak, I'm thinking of a stand-alone block plugin (like the "developed by" or "language toggle" blocks) that's custom-built to drop a Twitter feed into a block. You'd be able to use the configuration form for the plugin to determine details like whose feed should be displayed. That would probably be broadly useful and it's a safer approach than allowing `script` tags in TinyMCE controls.

**Comment by asmecher** [comment]
@mfelczak, here's the compromise I've come up with:

- Install the new [custom header plugin](https://github.com/asmecher/customHeader) (just written, works locally, needs testing beyond that)
- In the plugin settings, place the Twitter JS: `<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`
- In the sidebar block's source, drop the necessary Twitter anchor, e.g.: `<a class="twitter-timeline" href="https://twitter.com/asmecher?ref_src=twsrc%5Etfw">Tweets by asmecher</a>`

Let me know how that works?

I haven't built a package of the plugin (pending testing) so you'll need to make sure you install the plugin version descriptor. The easiest way to do that at the moment is using `lib/pkp/tools/installPluginVersion.php`.

**Comment by asmecher** [comment]
(This plugin needs a bit of further work on permitting it to function site-wide.)

**Comment by asmecher** [comment]
Added site-wide support, following the pattern of the custom block manager.

**Comment by asmecher** [comment]
@mfelczak, please confirm whether the 3.1.0-1 release of this plugin works for you. https://github.com/asmecher/customHeader/releases/tag/ojs-3_1_0-1

**Comment by asmecher** [comment]
Released and added to the plugin gallery.

**Comment by mfelczak** [comment]
Thanks @asmecher! Tested and confirmed working. There's a small type in the plugin gallery description: "This plugin permits the addition of custom headersto the website."

**Comment by asmecher** [comment]
@mfelczak, what version of OJS (or OMP) is having trouble installing? Do you get a message in the interface, or does it carry on as expected but without the plugin installed, or does the spinner turn endlessly? Is anything in the PHP error log?

**Comment by mfelczak** [comment]
Hi @asmecher, getting the following in the error log: "Incorrect MD5 checksum!"

**Comment by asmecher** [comment]
Try again? It looks like I had a typo in a filename in the gallery XML.

**Comment by mfelczak** [comment]
Fixed, thanks!
