### ISSUE TITLE
[OJS] Allow prepared email templates to be selectively available for discussions and participant assignment

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3193]
Editors would like to be able to create new prepared email templates, and have them available from the "Predefined message" dropdown when assigning a participant, and also generally when creating a Discussion thread. Something like the following for any newly-created prepared email template (eg. one that's not used somewhere in the system already): 

Make this template available to the following Discussions: 
[ ] Submission [ ] Review [ ] Copyediting [ ] Production

**Comment by NateWr** [comment]
@jmacgreg Is it important that templates be restricted to stages, or is that assignment intended to be a way to more easily find the desired template? Is the user story like this:

> As an editor, I want to be able to restrict an email template to a stage so that I can quickly find the template I'm interest in.

If it is, I think there may be an alternative approach to get to the "so that". For instance, it could be:

> As an editor, I want to be able to quickly search for any email template so that I can quickly find the template I'm interested in.

If our end goal is just: make it easier to find the template I'm interested in, I think a search/selection UI might be a better approach than building restrictions into the configuration process.

**Comment by jmacgreg** [comment]
Hi Nate, 

The parallel I was thinking of when I wrote this was with our ticket system, where we have a number of different queues, and can create templates and assign them to one or more of those queues. The result is that if you are responding to a queue, you have a short list of emails that you can review and choose from. You don't see unnecessary clutter, like eg. a copyediting request email in the production workflow. This is good for newer folks, or people who only occasionally use the system, and can't necessarily remember which email they might want to use. The short list acts as a prompt, and doesn't require pre-existing knowledge to undertake a search. So I guess the user story would be: 

> As a (new) editor, I want my email choices clear to me, so that I know what action to complete next. 

... or even: 

> As a journal manager, I want to ensure that participants have access to only relevant content for their particular stage. 

Does that make sense? I think a search component could also be useful, if for example the workflow-limited email set was still super long, but I can't see any stage having more than a dozen attached email templates - an amount that's relatively easy to scroll through.

**Comment by NateWr** [comment]
I posted a related mockup here: https://github.com/pkp/pkp-lib/issues/1432#issuecomment-357735815

**Comment by fgnievinski** [comment]
Just pigging back to the forum where a related feature wish has been posted:
https://forum.pkp.sfu.ca/t/predefined-messages/47962/3
I highlight especially the unavailability of predefined messages when notifying reviewers.

**Comment by primoz-svetek** [comment]
I would suggest to do do it in two steps:

1. In the next release just add possibility to search for all templates (in all phases) with a drop down menu (like in assign)

2. In scheduled OJS 3.2 implement full blown functionality as discussed above (I like it, btw)

**Comment by NateWr** [comment]
A simple way to add this feature would be to add predefined templates to the email dropdown list using an `<optgroup>`.

![other-templates](https://user-images.githubusercontent.com/2306629/95735418-ae056800-0c7c-11eb-95c0-d8f4b0376c09.png)

This would work in most cases where there are a dozen or fewer custom predefined templates. It will be easy enough to find and doesn't require much more work to implement (like a search utility). This would allow the work to get done sooner than waiting for the email sending refactor scheduled for 3.4/3.5.

No dropdown exists when creating a discussion, so the `<optgroup>` could be dropped there in favor of just a dropdown with all custom templates.

**Comment by jonasraoni** [comment]
PRs:
[pkp-lib](https://github.com/pkp/pkp-lib/pull/6730)
[OJS](https://github.com/pkp/ojs/pull/3037)
[OMP](https://github.com/pkp/omp/pull/927)
[OPS](https://github.com/pkp/ops/pull/118)

**Comment by NateWr** [comment]
@jonasraoni the formatting changes make this really hard to code review. Can you separate out the substantial changes into a separate commit for us?

**Comment by asmecher** [comment]
@NateWr, could you review this one?

**Comment by jonasraoni** [comment]
@NateWr I've created these PRs against stable-3_3_0

[PKP-LIB](https://github.com/pkp/pkp-lib/pull/6856)
[OJS](https://github.com/pkp/ojs/pull/3075)
[OPS](https://github.com/pkp/ops/pull/131)
[OMP](https://github.com/pkp/omp/pull/944)

Once everything is ok, I'll update the others for /main

**Comment by NateWr** [comment]
@asmecher This is almost ready for merge, but it's a 3.3.1 feature. Should we wait a bit to create that branch or go ahead soon?

**Comment by asmecher** [comment]
@NateWr, please go ahead and create a `stable-3_3_1` branch from `stable-3_3_0`. I'll drop a note in the pkp-dev channel to watch out for this new branch.

**Comment by NateWr** [comment]
Thanks @jonasraoni! All merged to the new `stable-3_3_1` branch and cherry-picked forward to `main`.

(Be careful about using "Closes" in commit messages as it will automatically close an issue. Because we have multiple branches, we don't necessarily want to close an issue with a single commit. This issue required 8 merges in all to complete.)

**Comment by jonasraoni** [comment]
Hmm, so it has the same effect of the "Linked pull requests" 🙈

**Comment by asmecher** [comment]
@jonasraoni, just a heads-up that this broke JS linting:
```
...lib/pkp/js/controllers/grid/queries/QueryFormHandler.js
	Line 49, E:0006: Wrong indentation: expected any of {6, 30, 33, 52, 56} but got 4
	jslint:lib/pkp/js/controllers/grid/queries/QueryFormHandler.js:82:13:Combine this with the previous 'var' statement.
```
I've added https://github.com/pkp/pkp-lib/commit/bf47536e27b590fddf24b6700913c3a4021f91c4 to fix that.

(It looks like JS linting problems don't break the Travis validation build -- worth looking into but hard to prioritize since it's the old JS framework only that goes through this process.)

**Comment by jonasraoni** [comment]
Ok, thanks! :)
