### ISSUE TITLE
Spanish locale is missing for the PKP PLN plugin

### ISSUE THREAD

**Issue by mjordan** [pkp/pkp-lib#3196]
Looks like the PKP PLN plugin is missing a Spanish translation:

![Non-English journal's deposit status table](https://forum.pkp.sfu.ca/uploads/default/optimized/2X/3/302ea37bad0e2ed60322ece827b402ac51def321_1_690x404.png)

Other locale files are at https://github.com/pkp/ojs/tree/ojs-stable-2_4_8/plugins/generic/pln/locale.

**Comment by asmecher** [comment]
@mjordan, are you suggesting that we use the 2.4.x PLN plugin's locale files as a basis for the 3.x plugin? Do you know that they're similar enough not to cause problems? (I haven't looked at them.)

**Comment by mjordan** [comment]
I wasn't suggesting that (I was only pointing out that the Spanish translation is missing) but I don't see why we couldn't use the 2.x locales as the basis for the 3.x locales. @defstat has already pointed things in that direction, I believe (compare https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/pln/locale/en_US/locale.xml and https://github.com/defstat/pln/blob/master/locale/en_US/locale.xml).

**Comment by mtub** [comment]
This is the OJS 2.4.x PLN plugin which doesn't have a Spanish translation so far. I've already let @marcbria know and we will see if there will be a translation soon.

**Comment by marcbria** [comment]
Not sure if we finally made it for 2.4.x but we are using weblate now and 2.x is legacy, so if they don't exist the translations won't be updated.

@asmecher do you mind to close this too?

**Comment by asmecher** [comment]
Sure!
