### ISSUE TITLE
make it easier to opt out of email notifications

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#3197]
I am part of a journal, and every time there is a new article published they send a notification. I assume they are using the issue notification feature. 

I cannot figure out how to opt out of receiving those. I've logged in, looked at my profile, gone to notifications and made sure none of the email boxes are checked. 

There should be an unsubscribe link in the email itself, but, failing that, a place to to take myself off the list.

**Comment by asmecher** [comment]
@jalperin, what version of OJS are they using?

**Comment by jalperin** [comment]
3.0.1. 

It's the [Stanford install](http://web.stanford.edu/group/ojs3/cgi-bin/ojs/)

**Comment by asmecher** [comment]
What's the subject of the email? (This might help me to confirm what template/notification you're running into.)

**Comment by jalperin** [comment]
[abbrev] New Notification from...

**Comment by NateWr** [comment]
Further discussion related to this can be found in https://github.com/pkp/pkp-lib/issues/2561.

**Comment by NateWr** [comment]
Related, maybe duplicate issue: #2805

**Comment by NateWr** [comment]
Closing in favor of #2805.
