### ISSUE TITLE
All authors should receive submission confirmation email

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3199]
Suggested by one of our hosted clients based on a recent experience where a lead author submitted a paper without the full consent of all listed authors.

It may be helpful to have two separate email templates here: a primary email that is sent to the primary author with links for accessing/managing the submission and a more generic email that is sent to non-primary authors confirming article submission to the journal.

**Comment by asmecher** [comment]
We already have that -- it's the `SUBMISSION_ACK_NOT_USER` email template. What version of OJS is this suggestion coming from?

**Comment by mfelczak** [comment]
Thanks @asmecher! This was for an OJS 2.4.x install. Closing.
