### ISSUE TITLE
Subscriptions page should not be accessible if payments are not enabled

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3206]
The frontend subscriptions page can be accessed when payments are not enabled under Settings > Distribution > Payments. This page should be disabled and a navigation menu item, if one exists, should not appear when payments are not enabled.

**Comment by defstat** [comment]
@NateWr are you referring to the /index.php/[journal]/payments admin page? 
Regarding the navigation menu item, are you proposing to add another NMI type which will not be displayed if the Payments are not enabled? Where will that NMI lead?

**Comment by NateWr** [comment]
Yeah, there are actually two frontend subscriptions pages, I believe. Alec can confirm. 

1. Public subscription page detailing available subscriptions. Conditions: subscriptions/payments enabled.
2. Frontend subscription page detailing the logged-in user's active subscriptions: Conditions: subscriptions/payments enabled `&&` user is logged in.

**Comment by defstat** [comment]
@NateWr PR

pkp-lib: #3364
ojs: pkp/ojs#1832

In https://github.com/pkp/ojs/blob/master/pages/user/UserHandler.inc.php#L30 there is one more check to enter the page: 

`$journal->getSetting('publishingMode') !=  PUBLISHING_MODE_SUBSCRIPTION` 

Should we add that too?

**Comment by NateWr** [comment]
👍 PRs look good. 

> Should we add that too?

Yeah, good catch.

**Comment by defstat** [comment]
@NateWr I have made the review changes

**Comment by NateWr** [comment]
👍 merged!
