### ISSUE TITLE
Add ability for editors to access editorial workflow when authoring a submission

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3208]
When a submission is created, a section editor (and maybe journal editor) is assigned as an Author if they have the role. When an author stage assignment is found, the submission lists link to the author dashboard ([here](https://github.com/pkp/pkp-lib/blob/master/classes/services/PKPSubmissionService.inc.php#L162-L167)). When choosing what to return, it should check to see if the user is _also_ assigned as an editor or section editor.

Discussed in the forum: https://forum.pkp.sfu.ca/t/stuck-with-submission-missing-file/36403/8

**Comment by ajnyga** [comment]
Maybe also cover the case where the editor acts also as a reviewer? I mean could there be a way to access any of the three workflows (editor, author, reviewer) if a user has all these stage assignments? Many journals seem to do some sort of "internal" reviewing and editors assign themselves as peer reviewers.

**Comment by asmecher** [comment]
@NateWr, I think this is a duplicate of https://github.com/pkp/pkp-lib/issues/3130.

**Comment by NateWr** [comment]
Arg I knew this sounded familiar.
