### ISSUE TITLE
Clarify bot identification

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#3209]
We are maintaining two different "robots" UA listings:
https://github.com/pkp/pkp-lib/blob/784a07352087abb4128b56d94de688787c525ebc/registry/botAgents.txt
and 
https://github.com/pkp/pkp-lib/blob/784a07352087abb4128b56d94de688787c525ebc/plugins/generic/usageStats/lib/counter/COUNTER_robot_txt_list_Jan_2011.txt
(now a reference to https://github.com/atmire/COUNTER-Robots)

These are processed/used by `Core::isUserAgentBot()`, c.f.: https://github.com/pkp/pkp-lib/blob/784a07352087abb4128b56d94de688787c525ebc/classes/core/Core.inc.php#L120-L145

These should probably be cumulative or superseding, probably via a hook in `Core::isUserAgentBot()`.

We should also be considering known IP ranges where crawlers are spoofing legitimate user agent strings.  C.f.: https://wiki.eprints.org/w/Robots, e.g. https://wiki.eprints.org/w/images/3/36/Bad_robots.txt

**Comment by NateWr** [comment]
@ctgraham and @bozana is this issue still relevant or can it be closed?

**Comment by bozana** [comment]
I am not 100% sure but I think this other issue solved it: https://github.com/pkp/pkp-lib/issues/4455. At least there we agreed to only use COUNTER bot list...
