### ISSUE TITLE
Unpublished books can still be accessed via their URL

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3210]
In OMP, if you add a book to the catalog, and then later remove it, it is removed from the catalog but still publicly accessible via direct URL. Removing the catalog entry should remove all public access to it and any galleys.

**Comment by asmecher** [comment]
@NateWr, are you logged in as a priveleged (e.g. Press Manager) user? If so, then the monograph will be viewable by URL even though it's been unpublished.

**Comment by NateWr** [comment]
Hmm, you're right, I can't reproduce this, even logged in as a journal editor. Must have confused myself.
