### ISSUE TITLE
Correct typo of namespace in oai-nlm metadata plugin (OJS 2.4.8)

### ISSUE THREAD

**Issue by tsnzdmr** [pkp/pkp-lib#3211]
The oai-nlm metadata plugin contains a typo:  http://td.nlm.nih.gov/publishing/2.3 (a "d" is missing in "dtd")

It should be: http://dtd.nlm.nih.gov/publishing/2.3

https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/oaiMetadataFormats/nlm/OAIMetadataFormatPlugin_NLM.inc.php#L50 

Although it seems to be a minor issue, harvesting systems that use this metadata-format can get validation errors.

If you want, we can create a pull request for this issue.

**Comment by asmecher** [comment]
Fixed, thanks for reporting!
