### ISSUE TITLE
CSL styles should receive DOI without URL

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3212]
The DOI plugin returns the full URL to the DOI when passing that data to the citation style language for generating a style. The CSL format expects the DOI without the URL, and some styles convert to URL while others don't. This should be changed on our end.

**Comment by NateWr** [comment]
Hey @bozana here's a quick one. Mind giving it a quick look for me?

https://github.com/pkp/ojs/pull/1767

**Comment by mtub** [comment]
HI @NateWr, I know that your reasoning is correct and that we are merely serving data to the different citation styles that all have their own interpretation of how to format stuff. I just feel a little bad that with this change we enable violating the DOI display guidelines (https://www.crossref.org/display-guidelines/#full).

**Comment by NateWr** [comment]
@mtub I felt the same, but I found this discussion about the issue in the CSL styles repo:

https://github.com/citation-style-language/styles/issues/2197

It sounds like the Zotero/Mendeley group have had a lot of backlash against that approach and have effectively put a hold on implementing it in every style. I'd prefer to stay aligned with them on this so we don't have to make our own decisions on this.

**Comment by mtub** [comment]
I understand. As I was very enthusiastic about supporting CSL, I guess I have to be happy with the bunch of autonomous styles that exist :smile:

**Comment by bozana** [comment]
Merged, thus closing...
