### ISSUE TITLE
Fix &nbsp; entity in Portuguese locale

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#3216]
Blank space is showing as entity at the "Round 1" tab in the Portuguese interface:

![image](https://user-images.githubusercontent.com/4059679/34297773-41b52832-e701-11e7-8f67-461c7605cc9f.png)

**Comment by alexxxmendonca** [comment]
@mtub

**Comment by mtub** [comment]
This is pt_BR, I presume? Will have a look...

**Comment by mtub** [comment]
Fixed in OJS 2 and OJS 3, thanks for reporting!
