### ISSUE TITLE
[OJS] Upgrade failed: DB: Can't DROP 'user_group_id'; check that column/key exists

### ISSUE THREAD

**Issue by ducquang92** [pkp/pkp-lib#3218]
Hi team,
I just performed an OJS upgrade from OJS 3.0.2 to 3.1.0.1 but the upgrade for database part failed with the error"
```
[data: dbscripts/xml/upgrade/3.1.1_update.xml]
ERROR: Upgrade failed: DB: Can't DROP 'user_group_id'; check that column/key exists
```
I then opened the file **3.1.1_update.xml** and saw that upgrade script tried to delete column user_group_id (line 38)
`<query>ALTER TABLE submission_files DROP COLUMN user_group_id</query>`

However, user_group_id column is not available in table submission_files of my database, which cause the error.
Please take a look to see if it's a bug or are there any problems with my database?
Also, is it possible to perform upgrade process just by commenting out these line?

**Comment by bozana** [comment]
Hmmm... That's interesting -- I do not get that error -- like my DB is not complaining about that. What DB and version do you use? -- just to know...

**Comment by ducquang92** [comment]
Hi @bozana ,
It's Mysql 5.1.73 on Centos 6.7.

**Comment by bozana** [comment]
Oh, I see... It is the same for me... Thanks!

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1778

**Comment by bozana** [comment]
@NateWr, could you review the PR above -- if I understand it correctly that column will be removed when the lib/pkp/xml/submissionFiles.xml is applied, correct?

**Comment by NateWr** [comment]
@bozana I'm actually not sure. Does it analyse the table and drop any columns that aren't mentioned? I trust you'd know better than me. Code looks fine so merge if you're happy with it.
