### ISSUE TITLE
[OJS 3.1.0.1] Upgrade gets stuck due to lack of MoveNext() in repairSuppFilesFilestage

### ISSUE THREAD

**Issue by ducquang92** [pkp/pkp-lib#3219]
Hi there,
I just found a bug in upgrade process. Please find description and the fix below.

**Description:** 
In upgrade process, function repairSuppFilesFilestage (in classes/install/Upgrade.inc.php) will be called. The codes to check if new file exists is at line 2561
```
if (file_exists($newFileName)) 
continue; // Skip existing files/links
```
If $newFileName really exists then the loop will continue without moving the SQL pointer to next element. That cause the current element being referenced again and again.

**Fix:**
The checking code should be
```
if (file_exists($newFileName)) {
$result->MoveNext();
continue; // Skip existing files/links
}
```

**Comment by bozana** [comment]
Thanks @ducquang92!!! I will then make a PR with the fix...

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1776
ojs ojs-stable-3_1_0: https://github.com/pkp/ojs/pull/1777
