### ISSUE TITLE
Unable to upload favicon in .ico format

### ISSUE THREAD

**Issue by brueyd** [pkp/pkp-lib#3226]
When trying to upload the favicon in the .ico format. The following error occurs:
File extension error.

![image](https://user-images.githubusercontent.com/34877697/34372450-a96bc40a-ea89-11e7-831b-702f3633141a.png)

**Comment by asmecher** [comment]
See https://forum.pkp.sfu.ca/t/ojs-3-cannot-upload-logo/28961 for another discussion. I'd suggest using a `.png` file instead of `.ico` -- relaxing this limitation is a low priority, as `.png` files will work wherever `.ico` files might be used.

**Comment by NateWr** [comment]
Closing this as low priority. We recommend use of .png files for favicons, which in the future may also be used for app icons, open graph tags, and other meta tags.
