### ISSUE TITLE
Non-anonymized reviewer files not able to be deleted

### ISSUE THREAD

**Issue by rcgillis** [pkp/pkp-lib#3228]
We've run into an issue with an OJS 3 journal not being able to delete the an uploaded reviewers' file that was not initially anonymized. The editors were enable to upload an anonymized version, but despite this, the first, non-anonymized version remains

**Comment by asmecher** [comment]
Copied over from slack, my response:

> I don't think OTOH we have tools to allow deletion of a specific revision, but I also don't think reviewers are given a list of previous revisions to access. I'd suggest deleting the review file wholesale, then re-uploading it -- or alternately leaving the old one in place, uploading a new one, and then editing the reviews to change the review files to exclude the unwanted one.

**Comment by mfelczak** [comment]
@rcgillis, can you confirm whether the above resolves this for you?

**Comment by bozana** [comment]
I've just tested this with the current master branch: 
a) All files a reviewer uploads are saved as extra files i.e. no revisions from earlier files.
b) Neither reviewer nor editor have the "Delete" option in the normal Reviewer/Reviewer Files grid. @asmecher , is this meant to be so for some reason?
c) But the "Delete" action is provided for the editor when he/she makes a decision: for example, if the editor chooses "Accept Submission" the reviewer files are listed for selection, to add them as attachment to the e-mail for the author. There the "Delete" action is provided. So there the editor can delete the reviewer files. @asmecher, is this meant to be so?
d) Using "Review Details" action from a reviewer assignment, the editor sees all reviewer files and can upload further ones.

Thus, the requirement here could be currently solved using c) and d).

**Comment by asmecher** [comment]
Thanks, @bozana -- I think in b) the editor should be able to delete these files. I'm less sure about the best approach for reviewers, but broadly speaking, I think someone should be able to delete what they've uploaded, as long as the review is still open.

**Comment by bozana** [comment]
Ah sorry @asmecher, I tested a finished review :-( You are right: the reviewer is able to delete the files as long as he/she is not finished with it. So this is OK, right?

**Comment by asmecher** [comment]
Yes, that sounds good.

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/3512
https://github.com/pkp/ojs/pull/1884 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look?

**Comment by asmecher** [comment]
Please go ahead -- I'm not sure why those would've been excluded, but there's no reason.
