### ISSUE TITLE
##plugins.categories.citationParser## not displayed properly

### ISSUE THREAD

**Issue by brueyd** [pkp/pkp-lib#3230]
Installation Info:
![image](https://user-images.githubusercontent.com/34877697/34477389-b92fa8b0-ef4e-11e7-811e-68d92bdded00.png)

Repro steps:
1) Open Dashboard
2) Click Settings, Website
3) Click the Plugins tab
4) Under the Installed tab scroll down to the section containing the citation extractors
5) Note the heading of that section: ##plugins.categories.citationParser##

![image](https://user-images.githubusercontent.com/34877697/34477412-ee78e6d0-ef4e-11e7-9cde-ff87d438d365.png)

**Comment by asmecher** [comment]
@brueyd, is this installation from github, or from the .tar.gz file?

**Comment by brueyd** [comment]
From the .tar.gz file

**Comment by asmecher** [comment]
That has already been resolved by https://github.com/pkp/pkp-lib/issues/2874 for the next release.
