### ISSUE TITLE
Change paymethod plugins to support multiple paymethods

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3231]
At the moment only one paymethod plugin can be activated at once. It would make sense to change the whole paymethod plugin structure to support multiple paymethods at once.

**Comment by asmecher** [comment]
@ajnyga, do you have a particular need for this? It sounds like a good thing to support but I wonder what the use case is in practice. I'd expect that journals might want to have all their records in one place (and hope we don't need to extend OJS with features that would be better in a financial suite), but I am aware that some regions don't support common payment methods.

**Comment by ajnyga** [comment]
I think that journals would like to have an option to use for example paypal and manual payment at the same time. 

In our case I have created an own payment plugin that enables users to pay a subscription with a code. This is something that learned societies need while they want to give a free subscription for their members. But some journal could ask support for paypal as well. At the moment this is a theoretical issue for us, but I can definitely see someone asking for this in the near future (as soon we get the 3.1 upgrade working that is...)

**Comment by asmecher** [comment]
For that case, it might be a tidier solution to allow the manual creation of payments while still allowing only a single payment method to be active at a time. IIRC there isn't a way to view the payment details of a completed payment, and creating a form to create/view/edit payment details would be useful for that too.

**Comment by NateWr** [comment]
Closing this as we have no plans to add enhancements to the subscription features in OJS at this time.
