### ISSUE TITLE
Manual payment plugin throws PHP Warning:  Missing argument 2 for Form::setData()

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3232]
`[02-Jan-2018 21:21:46 Europe/Berlin] PHP Warning:  Missing argument 2 for Form::setData(), called in plugins\paymethod\manual\ManualPaymentPlugin.inc.php on line 87 and defined in lib\pkp\classes\form\Form.inc.php on line 224`

**Comment by asmecher** [comment]
The warning is cosmetic and can be resolved with the attached patch. Thanks for reporting, @ajnyga!
