### ISSUE TITLE
[OJS] Crossref as-crawled URLs should only include PDF galley URLs (if multiple formats are published)

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3237]
If a journal publishes multiple galley types, and exports content out to Crossref, the current Crossref plugin includes an <item crawler="iParadigms"> link for each galley type. However it appears that Crossref/Turnitin requires a link to only the PDF galley, if it exists. From Crossref: 

> Note,  there are 4 collections with <item crawler="iParadigms">.  Our system is set up such that when you "redeposit" the same element multiple times, each new item overwrites the prior one.  So, it's the final iParadigms as-crawled URL in order that is actually indexed in the metadata record - in your case that is the article XML file. Unfortunately, that's not actually the correct, full-text as-crawled URL.   You'd want the as-crawled URL to point to the full-text PDF.

I'd really consider this a bug in the Turnitin system - we're simply providing links to all full-text content as previously specified, and it should be able to deal with multiple galley types. As a quick fix however, it might be worth considering adding some logic to the OJS plugin, like so: 

for all galleys: 
if galley is a PDF: include as as-crawled URL
otherwise: include all galleys as as-crawled URL

**Comment by jmacgreg** [comment]
A quick fix would be to just add an `if ($galley->isPdfGalley()` test to the code block that adds iParadigms content. Not super happy with the fix, but it would fix it.

**Comment by bozana** [comment]
@jmacgreg, hmmm... yes strange that they accept only one full-text URL :-O
Your proposed solution sounds good.
If there is a PDF galley, **only** provide its URL in the elements:
```
<collection property="crawler-based">
<item crawler="iParadigms">
<resource>http://ojs.bb/index.php/journal1/article/download/1/1</resource>
</item>
</collection>
<collection property="text-mining">
<item>
<resource mime_type="application/pdf">http://ojs.bb/index.php/journal1/article/download/1/1</resource>
</item>
```
If there is no PDF galley, provide all galleys.

If, for some reason, there are multiple PDF galleys, it does not matter which one to provide -- provide just one.

Correct? Are the XML elements mentioned above correct i.e. to be affected with the change?

**Comment by jmacgreg** [comment]
Hi Bozana, 

Yep, that's correct! I've added the above suggested fix to two journals already, and it works fine. I still think that this isn't our bug to fix, but this fixes it. :-)

**Comment by bozana** [comment]
@jmacgreg, shall we add the change or ask Crossref if they are planing to solve it differently?

**Comment by jmacgreg** [comment]
Hi Bozana, 

I think we have to resolve this on our end, unfortunately. Are you able to make the PR, or did you want me to?

**Comment by bozana** [comment]
I can do it -- I just was not sure... Thanks!!! :-)

**Comment by bozana** [comment]
Sorry @jmacgreg, one more question: the elements `<collection property="text-mining">` seem not to be affected by that, just `<collection property="crawler-based">`, is that right? -- I've just seen this example here: http://www.labs.crossref.org/documents/prospect/examples/annals_of_psychoceramics_b_515151_3.xml, linked from https://support.crossref.org/hc/en-us/articles/214298866...

**Comment by bozana** [comment]
I've also realized, that, in a rare case that someone removes all galleys, this would need to be deposited as empty collection elements in order to say Crossref to update that data, s. https://support.crossref.org/hc/en-us/articles/213022486-Updating-your-metadata bzw. https://support.crossref.org/hc/en-us/articles/115003564483. Thus I will consider this in the PR as well...

**Comment by bozana** [comment]
PR: https://github.com/pkp/ojs/pull/1879

**Comment by bozana** [comment]
@jmacgreg, I merged the PR above: It changes just the element `<collection property="crawler-based">`. If there is a PDF galley in the submission locale, this one will be taken; else if there is any other PDF, it will be taken; else all galleys will be taken. 
The element `<collection property="text-mining">` stays as it was i.e. containing all galley URLs.

**Comment by jmacgreg** [comment]
Thanks Bozana! As far as I understand it, you have it correct for the text-mining bit. It should only be the "crawler-based" item that should be affected.
