### ISSUE TITLE
PayPal fields missing Portuguese translations (pt_BR)

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#3238]
The PayPal fields are missing Portuguese translations (pt_BR):

![image](https://user-images.githubusercontent.com/4059679/34571361-7737b80e-f155-11e7-90f5-96fe4bc65587.png)

**Comment by alexxxmendonca** [comment]
@mtub

**Comment by asmecher** [comment]
@alexxxmendonca, I think the Paypal plugin is known not to have a complete `pt_BR` translation; when the translator works on updates, this will be part of what they finish. I think a separate issue entry like won't be seen by the translator so there's no need to create it -- unless you're planning to add a pull request yourself. @mtub, is that right?

**Comment by mtub** [comment]
Yes, that's right. Feel free to file a PR if you are working on this. Otherwise tagging @ronniebrito in case he knows of someone working on it.

**Comment by NateWr** [comment]
Translations can be contributed through out [translation system](https://translate.pkp.sfu.ca/).
