### ISSUE TITLE
[OMP] Remote galley links are not displayed unless there is a downloadable galley

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#3239]
With OMP 3.1.0-0, we published a book that’s only available online. When only the one remote galley was available, the catalog page displayed no content access links at all. When we added a dummy download file, both the download and the remote galley were presented on the catalog page.

**Comment by crism** [comment]
[This line in the template](https://github.com/pkp/omp/blob/master/templates/frontend/objects/monograph_full.tpl#L303) says make the `item files` section if there are files, but then [make a link for each format](https://github.com/pkp/omp/blob/master/templates/frontend/objects/monograph_full.tpl#L305). No files means no links, even if there are formats. What’s the right logic to replace that? Hmm…

**Comment by NateWr** [comment]
> I guess check if a remote format exists and add it to the conditional `{if $nonChapterFiles|@count}`. But I guess you'll also need to check if the remote format is attached to a chapter, if you can attach remotes formats to chapters... a bit hazy on all of that and it gets pretty complicated.

**Comment by crism** [comment]
@NateWr, I don’t think remote formats, or even formats _per se_, are attached to chapters, are they? Non-remote formats can have files, and some or all of those files might be associated with specific chapters, but a remote format is always whole-book and should always be presented, I think.

**Comment by NateWr** [comment]
That sounds right @crism. I think there's some talk of giving remote formats a dummy file in the system, for usage stats and other areas where remote formats introduce inconsistencies. So if that goes forward an additional check will be needed.

Your code looks good. Is there a PR somewhere? We may be able to get this into 3.1.1.

**Comment by NateWr** [comment]
Thanks @crism!
