### ISSUE TITLE
[OJS] Journal's H1 links to site-wide index instead of journal index

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#3244]
Hi,

After having upgraded from OJS 2.4.6 to 3.1.0-1, the header H1 element for all journals links to the site-wide index ([root]/index.php/index) instead of the journal's home page.

We would appreciate any help or pointers on how to fix.

Thanks!

**Comment by asmecher** [comment]
@martinpub, is the URL itself pointing to `[root]/index.php/index`, or are you redirected there upon clicking it? Is the installation online somewhere that you could share with me?

**Comment by martinpub** [comment]
Yes @asmecher, the URL itself is pointing to [root]/index.php/index. I have emailed you the URL of the installation.

**Comment by mczirfusz** [comment]
isn't it the same? #3178

**Comment by martinpub** [comment]
You are right, @mczirfusz, it seems like this is a duplicate of #3178, which has been fixed.
