### ISSUE TITLE
Update copyrights for 2018

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3246]

**Comment by asmecher** [comment]
Useful command lines:

    find . -type f -not -iwholename '*.git*' -exec sed -i -e "s/Copyright (c) \(....\)-.... John Willinsky/Copyright (c) \1-2018 John Willinsky/g" "{}" ";"
    find . -type f -not -iwholename '*.git*' -exec sed -i -e "s/Copyright (c) \(....\) John Willinsky/Copyright (c) \1-2018 John Willinsky/g" "{}" ";"
    find . -type f -not -iwholename '*.git*' -exec sed -i -e "s/Copyright (c) \(....\)-.... Simon Fraser University/Copyright (c) \1-2018 Simon Fraser University/g" "{}" ";"
    find . -type f -not -iwholename '*.git*' -exec sed -i -e "s/Copyright (c) \(....\) Simon Fraser University/Copyright (c) \1-2018 Simon Fraser University/g" "{}" ";"

**Comment by NateWr** [comment]
For the command lines, you might also want to exclude the `node_modules` directory (in app route and under `lib/ui-library`) since both of those will go very deep.

**Comment by NateWr** [comment]
All clear on my PRs if you want to go ahead with this.

**Comment by asmecher** [comment]
Merged! I didn't do `ojs-stable-3_1_0` for now.
