### ISSUE TITLE
[OJS] UI: reviewer page submission details - unnecessary information

### ISSUE THREAD

**Issue by mczirfusz** [pkp/pkp-lib#3247]
If the reviewer clicks on "View All Submission Details" under Review Step 1, the pop-up window contains misleading instructions which come from the submission form and have no relevancy for the Reviewer. 
Such as:
- choose the primary language;
- "Add additional information for your submission. Press 'enter' after each term."

My suggestion (which is perhaps the easiest solution) would be not to include the field explanations written in grey and only include the "main" elements written in black (Title, Subtitle, Keywords etc.).

I would perhaps also not inform the Reviewer about supporting agencies and the OpenAIRE ProjectID as these may corrupt the blindness of the review.

[OJS 3.1.0-1]

**Comment by asmecher** [comment]
@mczirfusz, I've [hidden the "Add additional information..." message](https://github.com/pkp/ojs/commit/0ac4ce332374e35ec070b7960bcdd5d4466b7e52) when the form is read-only, but I can't find where the "Choose the primary language" message would be displayed. Can you post a screenshot?

**Comment by mczirfusz** [comment]
@asmecher thank you for the patch. 
Here is the screenshot you asked for (it is perhaps only visible if a journal accepts submissions in different languages)

![image](https://user-images.githubusercontent.com/16511307/34906207-cf7129fa-f868-11e7-9ede-1948f2adafcd.png)

**Comment by NateWr** [comment]
This has been fixed at some point. I could not reproduce it in 3.3.0-8.
