### ISSUE TITLE
[OJS] submission emails: signature information is slightly duplicated

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3248]
With submission emails, the variable $editorialConactSignature pulls in the editor's full name, phone number and affiliation (see https://github.com/pkp/pkp-lib/blob/ojs-stable-3_1_0/classes/user/PKPUser.inc.php#L375). This can duplicate what's added to the editor's "Signature" field, which is appended to the email as well. I'm not sure the best course of action here, but I'd suggest making two values explicit, and available as separate variables: editorial name ($editorialName or $senderName maybe, and limited to just the editor's first and last name) and editorial signature ($editorialContactSignature, which should display the user's signature field contents). 

Side note - the journal where we're running into this issue doesn't have a journal-level signature implemented. It may be the case that if this were implemented it would override the editor's signature value. I *think* that's what code block https://github.com/pkp/pkp-lib/blob/ojs-stable-3_1_0/classes/mail/MailTemplate.inc.php#L222-L225 is doing, but I'm not 100% sure.

**Comment by alexxxmendonca** [comment]
This is something that we always (and still do) have trouble with.

**Comment by jmacgreg** [comment]
@alexxxmendonca I'm really just getting familiar with the problem now. Do you have any thoughts on 1) which variables you would like to see in place; 2) what information those variables should contain; and 3) whether some information (eg. site signature) should override others (user signature)?

**Comment by asmecher** [comment]
Yes, this should definitely be changed -- we should rely entirely on the user's signature field, rather than assembling our own signature. The relevant function (which needs grepping/removal) is `getContactSignature` in `lib/pkp/classes/user/PKPUser.inc.php`.

**Comment by jmacgreg** [comment]
Thanks @asmecher! What about doing something like: if there's a user signature, use that; otherwise, assemble a signature. Or should we just avoid that entirely?

**Comment by asmecher** [comment]
On balance, I would rather we just let the user specify a signature if they want one.

**Comment by alexxxmendonca** [comment]
@jmacgreg I think it's valid having variables with First, Middle and Last names, as well as Full Name. Pretty much all fields from the User Profile form.

Some journals like to dive really deep into e-mail customization and being able to standardize them.

It would be extremely helpful to have a glossary of variables available. Right now, one has to look up in other e-mail templates to copy a variable and paste it on another template -- and there is also the fact that not all variables work in every e-mail.

I believe in regards to e-mails the system should be flexible enough to allow journals to customize their own e-mail signatures or use a variable that bundles everything together, such as the $editorialConactSignature.

**Comment by jmacgreg** [comment]
@alexxxmendonca regarding the glossary: we've heard this request before, and I could have sworn that it was a feature request already in Github, but I can't file it. Please feel free to file it (and @ me)!

**Comment by asmecher** [comment]
Hi @jmacgreg and @alexxxmendonca -- any objections to the above proposal? (https://github.com/pkp/pkp-lib/issues/3248#issuecomment-356360962)

**Comment by jmacgreg** [comment]
None!

**Comment by asmecher** [comment]
Some email templates have the sending user's signature inhibited, so appending a signature explicitly is still appropriate. Think e.g. of emails that are sent by the system under editorial auspices based on an author's action, and shouldn't be signed by the current user, who is just the author.

Of those, the following use `{$editorialContactSignature}` without problems:
- `SUBMISSION_ACK`
- `SUBMISSION_ACK_NOT_USER`

The following had the potential for doubled-up signatures, and anything other than the optional user profile signature has been removed:
- `EDITOR_ASSIGN`
- `REVIEW_CANCEL`
- `REVIEW_ACK`
- `EDITOR_DECISION_...`
- `EDITOR_RECOMMENDATION`
- `COPYEDIT_REQUEST`
- `LAYOUT_REQUEST`
- `PROOFREAD_LAYOUT_REQUEST`

The various reviewer request templates use the following format:
> Dear xyz,
> (message)
> Thanks,
> `{$editorialContactSignature}`
>
> "SubmissionTitle"
>
> Submission Abstract...
> ...
> ...
This form has the signature in the middle of the message, which I argue is justifiable. I suggest we remove the potential for the user profile signature and stick with the `{$editorialContactSignature}` variable in the middle.

PRs:
- https://github.com/pkp/pkp-lib/pull/4692
- https://github.com/pkp/ojs/pull/2366
- https://github.com/pkp/omp/pull/662

**Comment by asmecher** [comment]
@NateWr, would you mind reviewing this one?

**Comment by NateWr** [comment]
:+1: Looks good to me. A couple of test failures. 

I just did an eyeball test, I didn't run through it myself, but the changes look straightforward and sensible.

**Comment by asmecher** [comment]
Thanks, @NateWr -- merged.
