### ISSUE TITLE
[OJS] Getting section editors results in db error

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3252]
Hi,

I'm getting an error database error when I want to get the editors for all sections with:
`$editorSections = $sectionDao->getEditorSections($journal->getId());`

The error is: DB Error: Unknown column 'se.journal_id' in 'where clause'.

When I'm not mistaken the column journal_id was renamed to context_id with [3.0.0](https://github.com/pkp/ojs/blob/master/dbscripts/xml/upgrade/3.0.0_preupdate.xml#L17)

**Comment by asmecher** [comment]
@MarHerUMR, what version of OJS are you using? Did you install it from the `.tar.gz`, or from git?

**Comment by MarHerUMR** [comment]
I've had the problem on a 3.1.0.0 instance that was installed from the .tar.gz and on an instance installed from git.

**Comment by MarHerUMR** [comment]
I've just updated the installation from .tar.gz to 3.1.0.1, with the same error.

**Comment by asmecher** [comment]
@MarHerUMR, do you know what's calling the `SectionDAO::getEditorSections` function? It's true that it refers to the since-renamed `journal_id` column, but nothing in the OJS codebase uses that function any more. Are you running custom code that uses it or something?

**Comment by MarHerUMR** [comment]
Oh, sorry that I didn't mention earlier. I'm using the function myself in a plugin to generate a list of section policies at our [about page](https://meta-journal.net/about). And I want to include the names of the section editors in the list as well.

**Comment by asmecher** [comment]
Sure, good enough for me. I'll fix the column name and leave the function in place.

**Comment by asmecher** [comment]
Fixed -- you can apply either patch. They're equivalent, just applied to different branches.
