### ISSUE TITLE
Glossary of e-mail variables

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#3253]
Add glossary of variables used across all e-mail templates.

Ideally, the list should include the variable, a description (expected value) and the e-mails templates where it can be used (in case it only works for certain e-mails).

This will be of real help when editing e-mail templates.

**Comment by alexxxmendonca** [comment]
@jmacgreg

**Comment by NateWr** [comment]
@defstat This issue may impact on some of your work we've discussed related to prepared email variables.

**Comment by asmecher** [comment]
The emails that are available should be available in the "compose" TinyMCE control using the 
![tmp](https://user-images.githubusercontent.com/200411/47182948-af913500-d2db-11e8-921b-d49cc6bd3554.png) icon. These are unfortunately unlabeled and confusing, though, so this issue could probably be resolved (at least when composing emails) with improvement there.

However, is the compose window the issue, or is it the "Prepared Emails" setup area?

**Comment by amandastevens** [comment]
We started putting this together during a PKP documentation sprint: https://docs.google.com/spreadsheets/d/1s19oi6xO_9pOwhWJkBEiTEOy8C02OcNuonBDIQPjKag/

Ping me if you would like editing access to the spreadsheet.

**Comment by marcbria** [comment]
Today an editor asked me about adding articleID in different email templates.
Looks like a reasonable petition to keep some variables global.

Thanks a for your work,
m.

**Comment by jonasraoni** [comment]
I was going to create an issue, but this one fits perfectly =]

A place to define global variables sounds good! And the glossary can be translated into a smart interface (e.g. a button/list where the user can view only the available variables with their descriptions and add them).
