### ISSUE TITLE
<li> tags in Masthead form HTML boxes polluted with class="show"

### ISSUE THREAD

**Issue by brueyd** [pkp/pkp-lib#3258]
![image](https://user-images.githubusercontent.com/34877697/34809258-b83e3c0e-f648-11e7-8725-33705c5d7f3a.png)
Installed from .tag.gz

Description: 
When `<li>` elements are present in the **Journal Summary**, **Masthead**, or **About the Journal** TinyMCE boxes, they are decorated on refresh with `class="show"`.

Repro Steps:
1) Navigate to Settings->Journal->Masthead
2) Click the `<>` button in the Journal Summary TinyMCE editor
3) Enter the following HTML
`<ul><li>test</li></ul>`
4) Click OK
5) Click Save
6) In another browser window, navigate the to Journal Summary and verify that the HTML is the same as what was entered. This demonstrates that the correct HTML was saved in the database.
![image](https://user-images.githubusercontent.com/34877697/34809443-d8abc1b8-f649-11e7-8335-bc6ab0a907e8.png)
7) Back at the Journal Settings->Masthead tab, **refresh the browser window**
8) Click the `<>` button in the Journal Summary TinyMCE editor
9) Confirm that the `<li>` tag has been rewritten as `<li class="show">`
![image](https://user-images.githubusercontent.com/34877697/34809505-38f874e4-f64a-11e7-8b4a-bd60d9bb5f99.png)

**Comment by NateWr** [comment]
Interesting... I didn't find anything about this in a quick Google search, so it doesn't seem to be part of TinyMCE's internals.

**Comment by brueyd** [comment]
I haven't noticed it in other TinyMCE edit boxes on other pages. My suspicion is that it is something to do with the java script on the Journal Settings page. Something that calls `.addClass` on `<li>` tags for a different reason, but is hitting the contents of the edit box by mistake. Unfortunately, I am just starting to learn about the OJS framework and don't have a good way to track it down.

**Comment by brueyd** [comment]
I have simplified the repro steps:
1) Navigate to the Journal Settings -> Masthead tab
2) Click the `<>` button in the Journal Summary edit box
3) Enter: `<ul><li>test</li></ul>`
4) Click `OK`
5) Clink `<>` again to verify that the code still reads `<ul><li>test</li></ul>`
6) Click `OK`
7) Click once inside the Masthead editor box
8) Go back to the Journal Summary edit box and click the `<>` button
9) Verify that the code is now: `<ul><li class="show>test</li></ul>`

Because there are no transactions with the server, I get the impression that it must be in the Javascript.

**Comment by brueyd** [comment]
I can recreate the same behavior on the Workflow Settings -> Submission tab, using the Author Guidelines and Privacy Statement edit boxes.

**Comment by NateWr** [comment]
Good hunting @brueyd! That is indeed the issue: https://github.com/pkp/pkp-lib/blob/master/js/controllers/SiteHandler.js#L264

I need to dig in to see if I can understand why this is here and whether it's safe to remove but you've saved me loads of time. :+1:

**Comment by brueyd** [comment]
@NateWr Right on! Let me know if it is safe to delete, and I will pull it out of my production install.

**Comment by NateWr** [comment]
I think it is but I'm still looking for some confirmation from others. It's very old code and I haven't ever run across a need for it.

**Comment by brueyd** [comment]
@NateWr I commented out the lines you identified in SiteHandler.js and uploaded the new version to the server, just to see if the issue goes away, but it did not. 
~~~~
tinyMCEObject.on('deactivate', function(tinyMCEObject) {
	// Show the placholder when the editor is deactivated
	if (!tinyMCEObject.target.getContent().length) {
		$('#mcePlaceholder-' + tinyMCEObject.id).show();
	}
	//Removed two lines to avoid polluting <li> tags in TinyMCE editor with class="show"
	//
	//tinyMCEObject.target.dom.addClass(
	//		tinyMCEObject.target.dom.select('li'), 'show');
});
~~~~

I also disabled server side caching and client side caching. Then, I waited overnight to be certain that any cache was updated. However, I still see the same behavior. Have you verified that these lines are the culprit? Am I missing something when trying to disable them?

I have verified that the lines are commented out using the file viewer in cPanel, so the file on the server should be the correct one.

**Comment by NateWr** [comment]
Hi @brueyd, I haven't verified these lines are the culprit yet. But you're probably running your production site with `enable_minify` on. If so, you'll need to recompile the `pkp.min.js` file as this doesn't get compiled automatically.

(And don't turn `enable_minify` off on a production server. It will cause a massive slowdown in your load times.)

**Comment by brueyd** [comment]
@NateWr I am trying to use buildjs.sh to rebuild pkp.min.js to test the fix to this bug. 

However, I am getting a bunch of warnings about doxygen flags `@brief, @defgroup, etc` .  Like this one:
~~~~
lib/pkp/js/pages/workflow/WorkflowHandler.js:14: WARNING - Parse error. illegal use of unknown JSDoc tag "brief"; ignoring it
 * @brief Base handler for the workflow pages.
   ^
~~~~
I also get this warning:
~~~~
lib/pkp/js/pages/workflow/WorkflowHandler.js:118: WARNING - Misplaced function annotation. This JSDoc is not attached to a function node. Are you missing parentheses?
}(jQuery));
  ^^^^^^
~~~~

Then it errors out on:
~~~~
lib/pkp/tools/closure-externs-check-only.js:42: ERROR - Variable JSONType declared more than once. First occurrence: externs.zip//es5.js
var JSONType = function() {};
~~~~

I am guessing there is a better place to ask this question. Is there a development forum, or should I ask questions like this in the general Questions section of the Community Forum? Just let me know and I will move this question to the appropriate place.

**Comment by brueyd** [comment]
@NateWr I commented out the following line in `closure-externs-check-only.js` because the comment in the code suggested the problem is known.
~~~~
// JQuery externs. These appear to be included in newer versions of Closure --
// see https://code.google.com/p/closure-compiler/source/browse/externs/es5.js
/**
 * A fake type to model the JSON object.
 * @constructor
 */
// Commented out variable definition because this definition is now in es5.js
//var JSONType = function() {};
~~~~

It seems like this would be better handled with a check for existence before declaration. Something like this:
~~~~
if (typeof JSONType === 'undefined' || JSONType === null) {
    // variable is undefined or null
    var JSONType = function() {};
}
~~~~

I cannot find this issue in GitHub project. Should I open this as another issue and move these comments to the new issue?

**Comment by brueyd** [comment]
@NateWr After recompiling pkp.min.js with the new version of SiteHandler.js, the `<li>` tag is no longer polluted with `class="show"`. If you find out there is a reason not to comment out that code, please let me know.

**Comment by NateWr** [comment]
Thanks @brueyd. I'm still waiting for feedback from someone who might know about this old code but if I don't hear anything soon I'll rip it out, do some testing myself, and hope for the best.

Don't worry too much about the linting errors from buildjs.sh. We run linting tests on the main pkp.min.js for every PR. Perhaps the linting errors in that build script are outdated or no longer used.

**Comment by NateWr** [comment]
@asmecher any update on the old Bugzilla archive?

**Comment by asmecher** [comment]
Sadly, no -- I've been prodding people about this and will try to get you an update.

**Comment by NateWr** [comment]
Flagging this one up again @asmecher. Any luck on the Bugzilla archive?

I do feel pretty confident about removing this code if we can't track down the original intent. It's impact would have most likely been on the frontend where the code was rebuilt from the ground up.

**Comment by asmecher** [comment]
@NateWr, Kurt is working to re-archive Bugzilla again, so it's temporarily back up. Here's what I was missing:

![image](https://user-images.githubusercontent.com/200411/37048426-b960b346-2122-11e8-88e6-47a6f1509b93.png)

So it looks like that line of code is related to the tag functionality we've added to TinyMCE. There's a nearby comment...

    // Show the placholder when the editor is deactivated

...so I'd suggest testing how the TinyMCE variable placeholders look when the input is deactivated, but at a glance, I don't see anywhere else in that code where a `show` class is used, so this is potentially dead code from an older integration with an earlier version of TinyMCE.

**Comment by NateWr** [comment]
Closing this as wontfix. As we refactor our UI, these cases will reduce and then disappear. And the impact on the resulting HTML code is minimal.
