### ISSUE TITLE
Notify after a revised version of submission (by author)

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#3259]
In OJS v 3.x i see the "REVISED_VERSION_NOTIFY" email key that could do what I would be interested in, ie send an email to the reference editor when the author uploaded a revised version of a text.

Now no email is sent after a revised version of the author as in the manual https://pkp.gitbooks.io/ojs3/content/en/responding_review.html where to inform the editor you need to click on "Add Discussion".

By checking the software, however, I find no reference to this key (REVISED_VERSION_NOTIFY).
Is the REVISED_VERSION_NOTIFY key a misprint and should it be deleted or can this automatic email be enabled?

**Comment by asmecher** [comment]
@eniocarboni, that email template is a hold-over from OJS2 and not currently used anywhere in the workflow. We have a few related issues already filed (see e.g. https://github.com/pkp/pkp-lib/issues/2665) and once those are resolved this text will either be used again, or more likely removed in favour of a different approach using the notifications tool.

**Comment by bozana** [comment]
The following PRs solve these issues #3278, #3326, https://github.com/pkp/pkp-lib/issues/3259 and #2618, using the PR #3169 as a basis (but changing it as discussed there):
pkp-lib master: #3399
ui-library master: pkp/ui-library#10
ojs master: pkp/ojs#1840

**Comment by bozana** [comment]
Thus I will close this issue...
