### ISSUE TITLE
Update SWORD plugin for OJS3

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3262]

**Comment by bakbalazs** [comment]
What is the expected due date for it to work?

**Comment by asmecher** [comment]
@bakbalazs, the OJS 3.x plugin will be over at https://github.com/kaschioudi/sword. There is a pull request there that's in progress. I don't have a specific due date to give you, but most of the work is already finished.

**Comment by bakbalazs** [comment]
Thanks for the reply.

**Comment by heike-r** [comment]
At the risk of annoying the OJS developers with constant community requests: is there any update on this? We have a MyCoRe based repository we want to connect to our OJS. My boss is building pressure since we do double entries in two separate systems. He is short on throwing money to the MyCoRe developers at our service partner institution to build some interface between OJS and MyCoRe. That would be unnecessary if the SWORD plugin is close to being finished. Would financial aid in form of 'sponsored development' help this along? (not promising anything yet!)

**Comment by asmecher** [comment]
@heike-r, the plugin is essentially complete but not yet tested and I haven't vetted the code thoroughly (it was written by someone else). However, it's here if you want to give it a try:

https://github.com/asmecher/sword

It may need a bit of additional troubleshooting beyond just testing, or it may just work. But I'd love a little bit of feedback -- it would help towards getting it released. I don't have a local copy of DSpace set up to try it with myself, and haven't had the time to prep my environment.

**Comment by heike-r** [comment]
Thanks @asmecher 
We have contacted one of the MyCoRe developer team members (say hi to @kkrebs) and forwarded the link to your GitHub repository. They have set up their own OJS for testing and will come back to you with more infos or questions.

**Comment by asmecher** [comment]
@kkrebs, did you install this in `plugins/importexport`? It should be installed in `plugins/generic`.

(I've just committed a fix to the code; please pull down the latest copy.)

With this, I've just used the Import/Export tools to deposit an article successfully into a fresh copy of DSpace.

**Comment by chiliego** [comment]
Hi, I'm testing the Sword-Plugin for @kkrebs. I just updated the code and move the plugin from importexport to generic and got an DB error
[Tue Aug 28 12:55:58.626449 2018] [php7:notice] [pid 1830] [client 127.0.0.1:60482] ojs2: DB Error: ERROR:  relation "deposit_points" does not exist\nLINE 1: SELECT * FROM deposit_points WHERE context_id =  $1  AND typ...\n                      ^, referer: http://localhost/ojs/index.php/neu/management/tools
What do I need to add to the DB? I'm using Postgres 10.5.

**Comment by asmecher** [comment]
@chiliego, I'm guessing you installed the plugin manually. The best thing to do is to install it via the Plugin Gallery inside OJS; that'll take care of creating the database table and email template for you.

**Comment by 1nthemist** [comment]
Hi there! Thanks for updating the Sword-Plugin, I'm now trying to test it. 

I first installed it manually and it didn't work (as mentioned in the previous comment). I'm now trying to install it using the Plugin Gallery in OJS and it shows me this message: 

"Plugin was not successfully copied. This may be a permissions problem. Please make sure that the web server is able to write to the plugins directory (including subdirectories) but don't forget to secure it again later." 

My plugin directory inside the ojs installation have permission 0777 as well as every sub directory, do you know how can I fix this error?

**Comment by asmecher** [comment]
@1nthemist, the best place to get support on this is our support forum (https://pkp.sfu.ca/support/forum).  If you can post this message there, I can follow up.

**Comment by kkrebs** [comment]
the posted link is outdated, you find the appropriate discussion here:
https://forum.pkp.sfu.ca/t/ojs-3-1-1-2-sword-plugin-not-installing-due-to-permissions/48280

**Comment by asmecher** [comment]
Oops! Thanks, @kkrebs, my earlier link has been outdated for at least a couple of years.
