### ISSUE TITLE
Add simple search form to site-wide homepage

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3264]
Currently the simple search form is suppressed from the sitewide homepage.

[This conditional](https://github.com/pkp/pkp-lib/blob/ojs-3_1_0-1/templates/frontend/components/header.tpl#L74) appears to be the culprit.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
