### ISSUE TITLE
OJS orcidProfile fix for 3.1 compatibility

### ISSUE THREAD

**Issue by isgrim** [pkp/pkp-lib#3266]
Hello everyone,

during the development of extensions for the https://github.com/pkp/orcidProfile Plugin, I found that the ORCID button was not displaying on the public user profile page for OJS 3.1.

I fixed it in the development and pushed to a branch here https://github.com/UB-Heidelberg/orcidProfile/tree/ojs-stable-3_1_0.
The branch is based on the tag https://github.com/pkp/orcidProfile/tree/ojs-3_1_0-1 .

Should I open a pull request for this on the official repository?

**Comment by asmecher** [comment]
Yes, please do, and link it here!

**Comment by isgrim** [comment]
@asmecher 
I found one more issue with the current version of the plugin.
The hook as registered here:
[pkp/orcidProfile/blob/ojs-3_1_0-1/OrcidProfilePlugin.inc.php#L51-L52](pkp/orcidProfile/blob/ojs-3_1_0-1/OrcidProfilePlugin.inc.php#L51-L52)
Does not seem to exist so the callback `collectAuthorOrcidId` will not be triggered.
Because of changes to the submission forms it is not a trivial fix of just changing to the correct hook for the submit form, as the hook parameters have also changed.

I could also fix this, and add it to the pull request, but I wanted to confirm with you before working further on this.

The extensions to the plugin, as dicussed in #2818, would probably change the logic behind collecting author ORCIDs. I want to change the sending of verification requests by email to authors optional.

Do you think I should quickly fix it to make the current version work again or add a new pull request after the development of the extensions have finished? That would be earliest in February, but more likely in March.

**Comment by asmecher** [comment]
@isgrim, I don't think anyone is working on this code at the moment -- so an expedient fix might be a good idea until we get time to work on larger plans.

**Comment by isgrim** [comment]
@asmecher I'm sorry, I probably wasn't very clear in my writing (language barrier ).
I meant I started working on code for the orcidProfile extensions for author verification and ORCID Profile updates through the Member API as diskussed in #2818, because this development is part of a project. We want to contribute this code back to the PKP repository to not create another ORCID plugin.

https://github.com/UB-Heidelberg/orcidProfile/tree/member-api is the branch for the extensions, so in this branch I have already changed the code concerning author ORCIDs. I wanted to know if I should try to backport this to the master branch and open a pull request or develop the changes further with  the hope that the enhancements will be accepted in the official plugin repository in a later pull request (probably not before March)

**Comment by asmecher** [comment]
Absolutely, please do! I'd be happy to review and merge these.

**Comment by isgrim** [comment]
@asmecher Thanks, will let open the PR as soon as it is finished and I am confident of the stability

**Comment by isgrim** [comment]
@asmecher Will close this, as a pull request is now open for the plugin additions

**Comment by asmecher** [comment]
Thanks, @isgrim!
