### ISSUE TITLE
NavigationMenus Site-wide unable to drop NMIs into empty NM edit areas. 

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#3267]
See also: https://forum.pkp.sfu.ca/t/how-to-add-menu-items-to-primary-navigation-menu-ojs-3-1/34537

It seems that there is a CSS override happening regarding the 
```
.pkp_nav_assigned > ul, .pkp_nav_unassigned > ul {
    padding-bottom: 64px;
} 
```
by 
https://github.com/pkp/pkp-lib/blob/master/styles/helpers.less#L188

at the Site level, which does not allow the drop-area to have the appropriate size for items to be dropped to it.

**Comment by defstat** [comment]
@NateWr 
PR
pkp-lib: #3268

Should I add the change to any other stable branch?

**Comment by NateWr** [comment]
:+1:

No, the next release is pretty soon and will be off of `master` so I don't think this needs back-porting.
