### ISSUE TITLE
[OJS PubMed plugin] Reminder: Tagging Investigators in PubMed Citation Data

### ISSUE THREAD

**Issue by MagnoliaPress** [pkp/pkp-lib#327]
Dear OJS developers:

Please see the info below. hope the next version of OJS is aware of this change in PubMed xml and update the plugin accordingly.

Dear PubMed Data Provider,

Investigators (also known as collaborators in PubMed) are individuals who contribute
to a scientific article but are not authors. They are a vital part of the
bibliographic citation. Please submit these names as part of the XML citation data
you send to NLM.

The pertinent XML elements in the Publisher DTD are in the GroupList (see
http://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.GroupList_O_R). Sample XML
is provided below.

The Authorship in MEDLINE Fact Sheet
(http://www.nlm.nih.gov/pubs/factsheets/authorship.html) explains the NLM policy for
individual authors, group or corporate authors, and investigators (i.e.,
non-authors).

Please note that a group name author (a collective name author, e.g., a study group
name) must exist in the bibliographic citation data in order for investigator names
to be supplied in the GroupList section. Investigator names should be listed in the
order in which they appear in the full-text article.

Thank you for your cooperation.

Sample XML:

If a citation includes two collective author names, e.g., North American Barley
Project and Cancer Genome Project, the XML citation data submitted would be:

<AuthorList>
<Author>
<CollectiveName>Cancer Genome Center</CollectiveName>
</Author>
<Author>
<CollectiveName>North American Barley Genome Project</CollectiveName>
</Author>
</AuthorList>
<GroupList>
<Group>
<GroupName>Cancer Genome Project</GroupName> <IndividualName>
<FirstName>John</FirstName> <LastName>Smith</LastName> </IndividualName>
<IndividualName> <FirstName>Jane</FirstName> <LastName>Smith</LastName>
</IndividualName> </Group> <Group> <GroupName>North American Barley Genome
Project</GroupName> <IndividualName> <FirstName>John Jacob</FirstName>
<LastName>Han</LastName> </IndividualName> <IndividualName>
<FirstName>Laura</FirstName> <LastName>Clancy</LastName> </IndividualName> </Group>
</GroupList>

Regards,

PubMed Publisher Data Provider Support Team NCBI/US NLM

**Comment by asmecher** [comment]
@MagnoliaPress, are you proposing to provide tagged investigators to CrossRef from an existing OJS field?

**Comment by jmacgreg** [comment]
Note also that OJS doesn't support group or corporate authors, though it does have limited support what PubMed calls Investigators ("contributors" in OJS' parlance, which can be arbitrary, eg. you can create translators or other roles to be displayed with the TOC online - though not yet currently included in export). See Issue #2958 for further info on this particular point. I think we have to solve #2958 first before this issue can be tackled.

**Comment by jmacgreg** [comment]
@MagnoliaPress if you could provide us with some discrete examples of these kinds of naming conventions, we'd really appreciate it. It doesn't have to be in XML - pointing to some published works online with corporate or other non-author names would be helpful.
