### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by dwisuseno** [pkp/pkp-lib#3271]
email sending do not work properly. how to fix it?
i have change smtp settings ojs. I installed it by softaculous from cpanel hosting. 
please help.

**Comment by asmecher** [comment]
Hi @dwisuseno -- please check our forum at https://forum.pkp.sfu.ca for guidance. If you can't find a solution there, post a new topic and include e.g. your version number.

**Comment by dwisuseno** [comment]
@asmecher Oke, I'll check it.
