### ISSUE TITLE
"Subscription" menu item only visible if the user signs in

### ISSUE THREAD

**Issue by mczirfusz** [pkp/pkp-lib#3272]
If the Subscription information page (/index.php/[JournalName]/about/subscriptions) is added as a menu item, it is only visible if the user signs in.
https://forum.pkp.sfu.ca/t/how-to-add-menu-items-to-primary-navigation-menu-ojs-3-1/34537/21

**Comment by asmecher** [comment]
See https://github.com/pkp/pkp-lib/issues/3206#issuecomment-357667977
