### ISSUE TITLE
When logged in, edit link on the announcement page is not working properly

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3273]
The link is pointing to the appearance tab in the admin dashboard, not the announcement page. Works properly after changing the `href` anchor:
https://github.com/Vitaliy-1/oldGregg/commit/4c7ed8cdf5d64172a77ade6bc2fc17dc49dad828

**Comment by asmecher** [comment]
@Vitaliy-1, I've applied a different fix -- to add the missing anchor names from the tabs, so they can be referred to by name, rather than by a programmatically-generated ID. See either of the attached (equivalent) patches. Thanks!
