### ISSUE TITLE
Redirect URI from Login as

### ISSUE THREAD

**Issue by AlHikamWolf** [pkp/pkp-lib#3274]
login with url like this.
https://e-journal.academic.edu/../../login?source=https://www.fbi.gov
https://e-journal.academic.edu/../../login?source=/robots.txt

**Comment by asmecher** [comment]
@AlHikamWolf, what of our software are you using, and what version?
It looks like you're suggesting that the `source` parameter be restricted so that arbitrary redirects are not possible; is that correct?

**Comment by AlHikamWolf** [comment]
does not seem to have any effect from the device I use, but I tested it from a site that has version 2.4.8.1, Yes, right.

**Comment by asmecher** [comment]
@bozana, assigning to you!

**Comment by bozana** [comment]
If I understand it correctly, the correct `source` parameter will always be in this form: /index.php/<contextPath>/<op>/<function>, s. https://github.com/pkp/pkp-lib/blob/master/classes/security/Validation.inc.php#L168. Correct?
Thus, would it be enough to just compare the two context paths for the redirection here https://github.com/pkp/pkp-lib/blob/master/pages/login/LoginHandler.inc.php#L110 -- from the current request and the source parameter -- i.e. something like:
```
$currentContextPath = $request->getContext() ? '/index.php/'.$request->getContext()->getPath() : '/index.php/.index';
if (strpos($source, $currentContextPath) === 0) {
$request->redirectUrl($source);
}
```
@asmecher, what do you think? Do I miss something?

**Comment by asmecher** [comment]
I don't think you can count on the `index.php` appearing in the URI in the case of `mod_rewrite`. Another approach would be to ensure that the URL is relative, i.e. that there's no `//` or `scheme://` in it -- I think the risk we're trying to mitigate is a URL that specifies a malicious user's server, not a "wrong" page on the OJS server.

**Comment by bozana** [comment]
Thanks @asmecher! Hmmm... Yes... I also the `source` would look differently for those using base URL override settings or disable_path_info = On... Hmmm... In that case, I suppose, we can only check if it is a relative URL. Would it then be enough to check if the `source` starts with `/` ?
In that case something like the example above (https://e-journal.academic.edu/../../login?source=/robots.txt) can not be considered. But this is maybe also OK...

**Comment by asmecher** [comment]
Yes, let's restrict it to only relative URLs. Beware, though, of protocol-relative URLs -- which start with `//` but may go to another domain.

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3331
ojs master: https://github.com/pkp/ojs/pull/1814 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look at the pkp-lib PR above?

**Comment by asmecher** [comment]
I think this needs to apply both to the login and registration functions.

**Comment by bozana** [comment]
Ah, sorry @asmecher, I thought I search for source parameter everywhere :-P
Now I considered it for registration too.
And I believe we don't have to change anything here https://github.com/pkp/pkp-lib/blob/master/pages/login/LoginHandler.inc.php#L144, because the redirect URL is constructed differently, correct?
THANKS!!!

**Comment by asmecher** [comment]
Looks good -- please go ahead!

**Comment by bozana** [comment]
The tests are failing because of something else, thus I merged the pkp-lib PR and I closed the OJS PR.
