### ISSUE TITLE
[OJS 3.1.0.0] Native XML import fails on batch insert

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#3276]
I use the Native XML import to batch insert multiple dummy submissions. All are created from the same template, where only a name changes for identification. We plan to use them for evaluation of OJS3 with our editorial board.

I try to import this [xml file](https://github.com/pkp/pkp-lib/files/1634443/many.xml.gz). After triggering the import, a GET request on `/management/importexport/plugin/NativeImportExportPlugin/import?temporaryFileId=29&_=1516095294046` returns with the following response from the server.
```
<br />
<b>Fatal error</b>:  Call to a member function setDescription() on null in <b>/var/www/html/plugins/importexport/native/filter/NativeXmlSupplementaryFileFilter.inc.php</b> on line <b>78</b><br />
```
This breaks the interface (can't be parsed as json) and results in the second article (Bivand.R) being partially uploaded. Author is set, but at least files and title are missing. The first (An.R) is inserted as intended, all others are missing completely.

**Comment by asmecher** [comment]
@pkel, have a look at [this forum thread](https://forum.pkp.sfu.ca/t/import-export-between-ojs-3-instances-failing/36420) -- you might be encountering the same situation.

**Comment by bozana** [comment]
Hmmm... it must be that the revision import did not work for some reason -- z. B. the submission_file id attributes are not unique, or a genre does not exist or... But there should be a better error handling at this part of the code, so that other other errors that happened earlier would be displayed...

**Comment by bozana** [comment]
@pkel, could you maybe apply these changes https://github.com/bozana/ojs/commit/22a58707d436dfb8ba8a8d9b87f1fe4445edf1d5 and see if you then get another import result message?

**Comment by bozana** [comment]
PRs:

ojs master: https://github.com/pkp/ojs/pull/1811

**Comment by bozana** [comment]
I will close the issue, but if there is a need it can be re-opened...

**Comment by pkel** [comment]
@bozana, I tried again to import the above file. The error is now handled properly and I get a nice error message in the frontend. It tells me that I try to insert all files with the same ID. That's true, but omitting the id gives a similar error.

I see messages like

> The revision "1" for submission file "42" would create a duplicate record

with repeating ids and

> The revision "1" for submission file "" would create a duplicate record

with omitted id attribute on <submission_file> and <supplementary_file>.

I fixed this by enumerating the files with unique ids starting from 1. Is this intentional? Shouldn't the importer be able to handle missing ids?

Afterwards, the result page shows success but does not list the imported submission. I see them on the submission overview though.

> The import completed successfully. The following items were imported:

**Comment by bozana** [comment]
@pkel, thanks a lot!
Yes, the `id` attribute for `submission_file` element is required -- it is referenced in the `article_galley` element -- to know which file exactly belongs to the galley. Then it is also used to keep track of the relationship with revisions and their sources -- submission files IDs from the import XML file are mapped to the actual inserted IDs in the DB. 
Here is a new issue and path for the result listing of successfully imported submissions: https://github.com/pkp/pkp-lib/issues/3334
THANKS!!!
