### ISSUE TITLE
Missing navigation menu item for the search page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3282]
We should also add a navigation menu item for accessing the search page, in case a theme does not bake that into its design.

**Comment by defstat** [comment]
@NateWr @asmecher 

PRs:
pkp-lib: #3310
ojs: pkp/ojs#1804
omp: pkp/omp#493

**Comment by asmecher** [comment]
Looks good to me, @defstat.

**Comment by NateWr** [comment]
Looks good, @defstat. The validation tests seem to be failing to the navigation menu XML:

https://travis-ci.org/pkp/ojs/jobs/332437946#L984

The other tests are also failing, but that may be due to an issue with `master` yesterday. Once the XML validation error is fixed and you rebase against current `master`, the tests may pass.

**Comment by defstat** [comment]
@NateWr it seems that its the NMs XML DTD that is failing. I will fix that and try the tests again.

**Comment by defstat** [comment]
@NateWr I have fixed the issue and rebased

**Comment by NateWr** [comment]
Looks like one of the OJS tests had a temporary hiccup. I've restarted it so let me know when it's passed and I'll merge them. 👍

**Comment by defstat** [comment]
@NateWr Rebased and all tests have passed.

**Comment by NateWr** [comment]
Sorry @defstat, been off the last few days. If you can rebase again I'll get it merged this time!

**Comment by defstat** [comment]
@NateWr Not a problem. I have rebased the branches. OJS is passing the tests, but OMP fails. See  https://travis-ci.org/pkp/omp/builds/339043409 where all tests have failed, but I am not sure if the problem is with the rebased branch.

**Comment by NateWr** [comment]
Hmm, looks like a failure to load node dependencies. I've restarted the OMP tests. Maybe it was just a fluke.

**Comment by defstat** [comment]
@NateWr OMP tests continue to fail (rebased again). Is that only me?

**Comment by NateWr** [comment]
Hmm, it looks like the JS build is failing on a required peer dependency. Why it's only happening in OMP, I'm not sure. Can you try runnign this in your OMP directory:

```
npm install file-loader --save-dev
```

Then try running the build script:

```
npm run build
```

If it's successful, try committing that change to see if it helps the OMP tests. If it does, we'll probably need to update OJS as well....

**Comment by NateWr** [comment]
This is basically done but I added the 3.1.1 milestone to it because the new theme will need this, so just to make sure it ships with 3.1.1.

**Comment by defstat** [comment]
@NateWr Followed your instructions. Rebased again. All tests have passed!

**Comment by NateWr** [comment]
🚢 Merged!
