### ISSUE TITLE
Make "path" fields more user friendly

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3286]
Concept of “path” is widely confusing.

Sonya notes: Can we copy what Wordpress does - user enters title first, the system then automatically creates the path (but the user can edit it)?

If not, then at least reword description text. Remove %path% - not meaningful to non-devs at all.

**Comment by NateWr** [comment]
We have made some improvements here by adding a prefix to the context path, which we'll roll out to other instances when those forms are converted.

![selection_026](https://user-images.githubusercontent.com/2306629/53561915-fcb5cb00-3b47-11e9-9230-94b9683e8aa4.png)

However, auto-generating would still be nice so I'll keep the ticket open.

**Comment by NateWr** [comment]
Closing this as low priority. A separate issue can be opened if/when automated path generation is considered.
