### ISSUE TITLE
Author `user_group_id` upgrade `UPDATE` is broken

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3289]
See https://forum.pkp.sfu.ca/t/fixauthorgroup-function-in-the-update/37281.

Rather than a quick fix to repair the missing `WHERE` statement, I'd suggest auditing the code to see whether the `authors.user_group_id` column is used. I suspect it may be dead code since the discussions rewrite.

**Comment by isgrim** [comment]
It is definetly still in use to distinguish types of contributors.
User group id for authors is populated from this form:
https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/author/form/AuthorForm.inc.php

**Comment by ajnyga** [comment]
Yes I think so too. Not sure if there are complications if the user_group_id is the same for all authors in all journals? Because that is what the upgrade does at the moment.

**Comment by asmecher** [comment]
@ajnyga, thanks -- I've applied the fix you suggested in [the forum thread](https://forum.pkp.sfu.ca/t/fixauthorgroup-function-in-the-update/37281/4) to `master` and `ojs-stable-3_1_0`. I don't think the implications for this in OJS are large -- OJS doesn't use different contributor groups in the same way that e.g. OMP does to distinguish between authors and series editors. However, to fix the data, the solution is to run the `Upgrade::fixAuthorGroup` function *again* to fix it properly this time -- and I've added that to the upgrade script for OJS 3.1.1.

**Comment by ajnyga** [comment]
Hmm, I think that the old code (the one without the WHERE clause) overwrote all cases where the authors contributor role was selected to be for example translator? I do not think it can be fixed anymore if someone has already done the upgrade with that sql?

**Comment by asmecher** [comment]
No, @ajnyga, not without referring to a backup, I'm afraid. But (unscientifically) I haven't seen translators designated this way in OJS -- it's much more common in OMP. Are you designating translators as contributors?

**Comment by ajnyga** [comment]
I have not checked, not sure. And in any case our upgrade did not overwrite that data if it existed. I was mainly thinking about other OJS users who are perhaps downloading an upgrade package from the PKP website.
