### ISSUE TITLE
Error 500 when I access page that included plugins. 

### ISSUE THREAD

**Issue by dwisuseno** [pkp/pkp-lib#3290]
I have upgraded ojs 2.4.8 to 3.0.2 but there is some problem, So I restore to ojs 2.4.8. and there is some issue about table, but I can solve it. And now there is problem in system plugin. I have google it, and have some recomendation:
1. installed curl
2. disable all plugins
3. check error, I checked it, got error ata crossref, but have no idea about it. 

Can anyone suggest me other option?

Thanks.

**Comment by asmecher** [comment]
I'd suggest posting your question in our forum (https://forum.pkp.sfu.ca) and posting as much information as possible, including your OJS version. This issue tracker is used for specific bugs and feature requests, and the forum is a better place for technical support.

**Comment by asmecher** [comment]
Glad to hear it's resolved!
