### ISSUE TITLE
Add timestamps to the upgrade script output

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3293]
A small suggestion to the upgrade script.

With larger installations the upgrade takes time finish and usually we "practice" the upgrade with a cloned test installation.

It would help a lot to plan an  upgrade schedule for the production server, if the upgrade script would print out timestamps when moving from one phase to another. 

This would also help in finding phases that take particularly long. In some cases the long waiting time could be because of a bug in the upgrade script and showing the running time clearly would help in finding these.

**Comment by NateWr** [comment]
@asmecher would this be difficult? Seems like maybe a quicky and easy improvement.

**Comment by asmecher** [comment]
Yes, this is trivial to do. @ajnyga, making this change:
```diff
diff --git a/classes/cliTool/UpgradeTool.inc.php b/classes/cliTool/UpgradeTool.inc.php
index 7c45b1e9b..1cdc5b7f9 100644
--- a/classes/cliTool/UpgradeTool.inc.php
+++ b/classes/cliTool/UpgradeTool.inc.php
@@ -220,7 +220,7 @@ class UpgradeTool extends CommandLineTool {
         * @param $message string
         */
        function log($message) {
-               printf("[%s]\n", $message);
+               printf("%s [%s]\n", date('Y-m-d H:i:s'), $message);
        }
 
 }
```
...results in output like:
```
$ php tools/upgrade.php upgrade
2021-12-09 16:29:25 [pre-install]
2021-12-09 16:29:25 [load: upgrade.xml]
2021-12-09 16:29:25 [version: 3.3.0.8]
2021-12-09 16:29:25 [code: Installer Installer::checkPhpVersion]
2021-12-09 16:29:25 [code: Installer Installer::installDefaultNavigationMenus]
2021-12-09 16:29:25 [code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
2021-12-09 16:29:25 [code: Installer Installer::addPluginVersions]
2021-12-09 16:29:25 [post-install]
Successfully upgraded to version 3.3.0.8
```
Does this suit your requirements?

**Comment by NateWr** [comment]
Committed to `main` in https://github.com/pkp/pkp-lib/commit/c802b392f4019ff3dd0d24b72d6bb64fef87e224.
