### ISSUE TITLE
Display additional submission metadata on article landing page

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3294]
At the moment, only keywords are displayed on the article landing page. Journal editors would like to publish additional submission metadata on the article landing page, e.g. supporting agencies

Extend the Submission Metadata grid on the Settings => Workflow => Submission page with a new column (e.g. 'Publish' or 'Display') to provide JMs/JEs with the ability to selectively publish additional metadata on the article landing page.

![submission_metadata](https://user-images.githubusercontent.com/200793/35156010-85760a52-fcfd-11e7-8e29-2936803e1222.png)

**Comment by NateWr** [comment]
There are two parts to this:

1. User control over what content is and is not displayed on the page.
2. Display of metadata that is not currently displayed by default.

For (1), I'd like to see us tackle this along with the article content blocks thing we've been talking about for years: a way for admins/editors to drag-and-drop blocks (abstract, keywords, doi, cover, etc) to re-order the display of information on the article page.

For (2), I'd want to see some examples of what the content might be like and what existing displays exist. For instance, with Supporting Agencies, will it just have the name of the agency? Or should the metadata be a sentence like "This article was funded by X."

At the moment we're only showing Keyword and References from that list above.

**Comment by ajnyga** [comment]
@mfelczak regarding the supporting agencies field, I warmly recommend the Funding plugin: https://github.com/ajnyga/funding :D

**Comment by kshuttle** [comment]
+1 from an SFU journal

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
