### ISSUE TITLE
switch to a supported Memcached library

### ISSUE THREAD

**Issue by benben159** [pkp/pkp-lib#3299]
i've set up an OJS 3.0 installation using PHP 7.1. when i want to use memcached cache backend, it does not find the correct library. I've searched for Memcache library and its compatibility with PHP 7.1, and I found that it only support PHP 5.x.

**Comment by asmecher** [comment]
@benben159, have you verified that this works (and results in a performance improvement over no caching or file caching)? The memcache support was added probably 10 years ago and has seen little use or maintenance; I'd be surprised if it worked so quickly. Thanks for looking at it!

FYI, our longer term plan is to replace the current caching infrastructure entirely, in favour of a third-party library.

**Comment by benben159** [comment]
I haven't measure any performance improvements here, but I wrote that so it just work and I currently do not have any idea on caching optimization with this Memcached library. The reason is that I don't really understand how caching is used in pkp-lib.

**Comment by asmecher** [comment]
Thanks, @benben159 -- I've merged your PR, as it looks good, but haven't tested the current level of memcache support for a long time. For the moment, I'd recommend against using memcache unless you have a specific need for it (file-based caching seems to work well for OJS users). Eventually our plans to replace our current cache implementation will be dealt with here: https://github.com/pkp/pkp-lib/issues/3304
