### ISSUE TITLE
2 URLs point to registration page

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3301]
The registration page is available by 2 URLs (in the latest OJS version):
`.../user/register` 
`../user/registerUser`
Is there a reason for that? 
I suspect that this causes a problem with redirection to `Registration complete` page minimum in one user (only with oldGregg theme), although I can't reproduce that on my local machine:
https://github.com/Vitaliy-1/oldGregg/issues/19#issuecomment-358842443

**Edit**: I can reproduce the problem. While the oldGregg theme is active and require_validation option in the config file is _on_, the user after registration is redirected to `../user/registerUser` instead of `.../user/register` . It is not the case with Default Theme.

As I understand, there were some changes made for this page in previous OJS versions. And that was kept for backward compatibility. On a handler level, this method seems not be enough for correct work:
https://github.com/pkp/pkp-lib/blob/master/pages/user/RegistrationHandler.inc.php#L117
On a template level for proper work, I have changed in my theme:
 https://github.com/Vitaliy-1/oldGregg/commit/8d8c65a80724417b181c34c4ea91bc9d85841b74

So, from my point of view there is a need either to fix the compatibility with 3rd party themes or refuse from `registerUser` requests.

**Comment by NateWr** [comment]
In the default template we submit the form to the `redirect` op. https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/userRegister.tpl#L17 So it looks like the change you made is the correct way to handle it. 

My understanding is that `registerUser` was just kept for temporary backwards compatibility but all themes should use `register` from here on in. We may remove support for `registerUser` in the future.

**Comment by NateWr** [comment]
(I'm closing this but feel free to continue discussing and I can re-open if necessary.)
