### ISSUE TITLE
[OJS] Call to undefined method PdfJsViewerPlugin::_registerTemplateResource()

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3303]
I have this error with ojs-stable-3_1_0
I think it's because of https://github.com/pkp/pkp-lib/commit/5d3ba1fed746e8741d7fbaaea4eaa6d3f17d2308 not reported on stable branch.

Thank you in advance

**Comment by forgive38** [comment]
@asmecher : what is the official release of the plugin ? 
I use branch master of pkp/pdfJsViewer

Thank you

**Comment by asmecher** [comment]
@forgive38, the PDF.js viewer should already be included in recent releases of OJS.

**Comment by forgive38** [comment]
Thank you, I saw my mistake
