### ISSUE TITLE
Create a "Manage Users" cli script.

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3306]
It should be a CRUD tool, able to do the following: 

* create user (with name, email, and role options)
* update user (with new information, incl. role in a specific journal, password reset, etc.)
* delete user (replacing the Merge User cli tool)

**Comment by jmacgreg** [comment]
Hi Alec, @israelcefrin and I would prioritize #3281 first. We're just adding a few other items to the CLI Project, which we can discuss during the dev call today.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
