### ISSUE TITLE
Create a cli backup tool

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3307]
Allow the cli tool to specify an export location.

**Comment by jmacgreg** [comment]
There is a backup plugin already available for OJS 3 - see https://github.com/asmecher/backup. I'm not sure if that could somehow be triggered from the cli or not. I'd consider this issue one of the lower priorities, for a few reasons: 1) it's easy to script in native environments; 2) it's potentially difficult to write up generically as a cli tool to fit all environments; and 3) there's already the plugin available for end-users who don't have cli access. I can review this issue and the others with you and provide some additional context when we meet on Friday, if that works?

**Comment by jnugent** [comment]
sounds good.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
