### ISSUE TITLE
"Subject" / "subjects" field "required" flag not behaving as expected

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3311]
In the Submissions area of the workflow settings, it's possible to define the Subjects field as required. This appears not to be working properly -- creating a submission and entering subjects does not satisfy the constraint.

At a glance, there seems to be a mismatch between the terminology used in the code. Some parts refer to "subjects", other parts refer to "subject".

**Comment by bozana** [comment]
Hmm... I thought it was solved with this issue: https://github.com/pkp/pkp-lib/issues/3157. But maybe something else is happening here... I can take a look...

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3312
ojs master: https://github.com/pkp/ojs/pull/1805
omp master: https://github.com/pkp/omp/pull/494

**Comment by bozana** [comment]
@asmecher, OK so? THANKS!!!

**Comment by asmecher** [comment]
Thanks, @bozana -- just a few minor changes needed.

**Comment by bozana** [comment]
@asmecher, gooooood catches! :-) I've considered the comments, so can I then merge when the tests pass? THANKS!!!

**Comment by asmecher** [comment]
Yes, please do!
