### ISSUE TITLE
Enabling plugins from plugin gallery

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3314]
I am unable to enable plugins that are in the plugin gallery.

I tried as a site admin from the Site Settings -- no enable function is available.

I tried as a journal manager from Settings -- no enable function is available.

http://vpstest2.lib.sfu.ca/index.php/publicknowledge/management/settings/website

**Comment by asmecher** [comment]
Which plugin are you trying to work with?

**Comment by stranack** [comment]
Quicksubmit.

**Comment by asmecher** [comment]
The QuickSubmit plugin is an import/export plugin, and these are only reachable from the import/export tools, so there's no need (or ability) to enable or disable them.

**Comment by stranack** [comment]
But it isn't in my list of import/export plugins.

**Comment by stranack** [comment]
Nor in my list of Tools.

**Comment by asmecher** [comment]
Yes, it's not installed by default (and it's usually installed using the Plugin Gallery). Since you're using pre-release code, I'll install it from github directly.

**Comment by NateWr** [comment]
Is there anything here that should be filed for the future or can it be closed?

**Comment by asmecher** [comment]
Closing before someone else answers this question :)
