### ISSUE TITLE
[OJS] can't access to editorial history of a submission with Firefox

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3322]
When I want to open the editorial history of a submission, the modal opens but the history is not displayed. there is just "Loading"
The received code does not seem to execute. Same thing under Opera but with Chrome it's ok.

I do not have a JS or PHP error.

thank you in advance

**Comment by ajnyga** [comment]
One of our users had similar problems with the editorial histy and the reason was an adblocker software in the browser.

**Comment by forgive38** [comment]
Thanks a lot : exactly the same thing for me.
