### ISSUE TITLE
REVIEW_ROUND_STATUS_RESUBMITTED message

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3326]
The review round status REVIEW_ROUND_STATUS_RESUBMITTED (https://github.com/pkp/pkp-lib/blob/master/classes/submission/reviewRound/ReviewRound.inc.php#L23) sounds wrong: it suggests that something is resubmitted, but actually the revisions are requested, that will then be subject of the new review round. The variable name is maybe not so important and must not be changed, but the review round status message "Submission has been resubmitted for review." should be changed.

**Comment by NateWr** [comment]
```
<message key="editor.submission.roundStatus.resubmitted">The submission must be resubmitted for another review round.</message>
```

**Comment by bozana** [comment]
The following PRs solve this as well as the issues #3326 and #2618, using the PR #3169 as a basis (but changing it as discussed there):
pkp-lib master: #3399
ui-library master: pkp/ui-library#10
ojs master: pkp/ojs#1840
