### ISSUE TITLE
[OJS] Edit issue modal, last link not visible with some locales

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3328]
Hi,

I noticed that in the edit issue modal the link leading to instructions hides the last tab link. See below. Probably this could happen with other locales as well.

![screenshot_8](https://user-images.githubusercontent.com/16347527/35511966-b5094318-0506-11e8-9d5c-b77777528eee.png)

**Comment by NateWr** [comment]
Note to self: `.pkp_modal .ui-tabs-nav` is overriding the right padding on `.ui-tabs-nav` that's supposed to create room for the help links.

**Comment by NateWr** [comment]
Closing this as outdated. There should be a maximum of 4 tabs in this particular modal. If you can still reproduce the problem in 3.3, please provide reproduction steps and we can reopen it.
