### ISSUE TITLE
Copyright Info with CC License Badge

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3329]
If there is a CC license badge for an article, only that badge (CC image and text) is displayed on the article page, s. https://github.com/pkp/ojs/blob/master/templates/frontend/objects/article_details.tpl#L369-L371
Display also the copyright info...

**Comment by bozana** [comment]
@NateWr, how should the copyright info be displayed in this case? Before the CC license badge? E.g. like this:
```
<div class="item copyright">
Copyright (c) 2016 Test Journal 1
<a href="http://creativecommons.org/licenses/by/4.0/" rel="license">
<img src="//i.creativecommons.org/l/by/4.0/88x31.png" alt="Creative Commons License">
</a>
<p>
This work is licensed under a
<a href="http://creativecommons.org/licenses/by/4.0/" rel="license">Creative Commons Attribution 4.0 International License</a>
.
</p>
</div>
```
i.e. without any HTML element? Or maybe with `<p>`?
:-) Thanks!

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1812

**Comment by bozana** [comment]
@NateWr, the PR above is mit `<p>` element...

**Comment by NateWr** [comment]
👍 merged!
