### ISSUE TITLE
CrossRef XML Export - Ability to handle roman numerals.

### ISSUE THREAD

**Issue by bdgregg** [pkp/pkp-lib#333]
As discussed on the forum here: http://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=12529&p=52679#p52679 the CrossRef XML Export needs to support the ability to handle roman numerals in the pages XML output.  

Additionally, we should include some guidance on the Editor page where you are editing the Table of Contents such that we provide a link to some help (maybe via a mouse over an ? icon) to accepted valid options for this column such as "i-iv", "a-s", "1-34", etc.  

If this is not resolved any CrossRef XML export is considered invalid (as OJS removes the first_page, other_pages attributes from the XML) if the journal chooses to use the CrossRef documented and allowed roman numerals in the pages field.

**Comment by asmecher** [comment]
This field is not just used for CrossRef, so the impact would need to be checked against other areas. For example:
- Resolver plugin: plugins/gateways/resolver/ResolverPlugin.inc.php
- URN Pub ID plugin: plugins/pubIds/urn/URNPubIdPlugin.inc.php
- DOI Pub ID plugin: plugins/pubIds/doi/DOIPubIdPlugin.inc.php
- DOAJ export: plugins/importexport/doaj/DOAJExportDom.inc.php
- DataCite export: plugins/importexport/datacite/classes/DataciteExportDom.inc.php
- PubMed export: plugins/importexport/pubmed/PubMedExportDom.inc.php
- MEDRA export: plugins/importexport/medra/classes/O4DOIExportDom.inc.php
- NLM OAI: plugins/oaiMetadataFormats/nlm/OAIMetadataFormat_NLM.inc.php

(These are the areas where OJS might try to tease apart the format of the page numbering; there are other areas, like DC11, native import/export, etc., where the contents of that field are passed along verbatim.)

**Comment by marcbria** [comment]
I agree with Clinton comment in forum: With CrossRef we are in schema violation.
http://www.crossref.org/schemas/common4.3.0.xsd

> [xsd:element name="pages"]
> The container for information about page ranges.
> When an entity has non-contiguous page information, you should capture the first page range in first_page and last_page. Any additional page information should be captured in other_pages.
> Punctuation is only allowed in other_pages. It should not appear in first_page and last_page.
> Page number letter prefixes or suffixes should be included. Roman numeral pages are permitted in both upper case and lower case.
> Data may be alpha, numeric or a combination.

Is it possible to isolate the change to CrossRef plugin?

**Comment by AhemNason** [comment]
Hey Alec, I'm mostly just chiming in here to say that if we had the granularity for page numbers it might be preferable to having other exporters having to split the content? But maybe not. I know that there are plenty of metadata standards for citations or articles that look for a first/last page and there are some that can handle a straight-up range. This is definitely going to come up in any conversations with Érudit for example. MODS also looks for first/last. Just a thought. 

I could be wrong, though. I know CrossRef isn't the only situation where folks run into this error and it's not the only place where changes would have to be made.

**Comment by asmecher** [comment]
Deferring from OJS 2.4.7 for now.

**Comment by ctgraham** [comment]
I plan to implement this as:

- Remove any "p{1,2}[.]? *" prefix from the pages, per the problematic former documentation for the input field.
- Split the string on commas to identify non-contiguous ranges
- Split the substrings on dashes to identify contiguous ranges

There are existing functions Article::getStartingPage() and Article::getEndingPage() which assume integer returns.

This processing can't be limited to integer returns, both because of allowing roman numerals, and allowing letter prefixes and suffixes.

There might be an internationalization issue assuming splitting on commas and dashes.  Are other punctuation marks used for range and list denotation in non-latin character sets?

Feedback welcome.

**Comment by ctgraham** [comment]
Proposed function:
```
        /**
         * get pages as a nested array of page ranges
         * for example, pages of "pp. ii-ix, 9,15-18,a2,b2-b6" will return array( array(0 => 'ii', 1, => 'ix'), array(0 => '9'), array(0 => '15', 1 => '18'), array(0 => 'a2'), array(0 => 'b2', 1 => 'b6') )
         * @return array
         */
        function getPageArray() {
                $pages = $this->getData('pages');
                // Strip any leading word
                if (preg_match('/^[[:alpha:]]+\W/', $pages)) {
                        // but don't strip a leading roman numeral
                        if (!preg_match('/^[MDCLXVUI]+\W/i', $pages)) {
                                // strip the word or abbreviation, including the period
                                $pages = preg_replace('/^[[:alpha:]]+[.]?/', '', $pages);
                        }
                }
                $ranges = explode(',', $pages);
                $pageArray = array();
                foreach ($ranges as $range) {
                        $pageArray[] = array_map('trim', explode('-', $range, 2));
                }
                return $pageArray;
        }
```

**Comment by asmecher** [comment]
@ctgraham, looks good -- and this might be a good candidate for some unit testing, if you have any interest in tinkering with that. Bet you never guessed you'd be writing code to parse language that's most of 3,000 years old...!

**Comment by ctgraham** [comment]
Yes!  I wanted to write a unit test for this, but when I searched the tests/ folder, I couldn't find anything to do with functional testing for Articles or for Submissions.  Where do I find them?

**Comment by asmecher** [comment]
They'd probably be best placed in `tests/classes/article` for `Article.inc.php`, or `lib/pkp/tests/classes/submission` for `Submission.inc.php`. Neither of these exist yet.

**Comment by ctgraham** [comment]
Test is written.

**Comment by asmecher** [comment]
@ctgraham, is there a PR open for this? If so, mind dropping a link here?

**Comment by ctgraham** [comment]
Cap'n!  There be pulls here!

**Comment by asmecher** [comment]
Thanks, @ctgraham! Sending to @bozana for review...

**Comment by bozana** [comment]
Aye aye Capt'n!

**Comment by bozana** [comment]
Thanks a lot @ctgraham!
I can then try to port it to master as well...

**Comment by bozana** [comment]
I reviewed and tested the changes -- they work well! Thanks a lot @ctgraham!
There are a few minor things, that I can add after the merge:
-- issue year is escaped in NativeFilterHelper, but not in O4DOIXmlFilter
-- e-mail is escaped in O4DOIXmlFilter and IssueCrossrefXmlFilter, but not in DOAJXmlFilter and PKPAuthorNativeXmlFilter
-- the escape for DOI in DataciteXmlFilter is missing
-- the escape for representation->getId() in the element `id` in RepresentationNativeXmlFilter is not needed

**Comment by bozana** [comment]
Hi @ctgraham, do you maybe know what is still left to do here? -- I lost the overview... :-\
For example, I believe, we still have to migrate it for Crossref in OJS master, right?

**Comment by ctgraham** [comment]
Yes, I think forward porting to master is the last missing piece.

**Comment by bozana** [comment]
OK, I can do that. Only Crossref?

**Comment by ctgraham** [comment]
I think so.  The other use cases should be already covered in pkp/pkp-lib#2075 and pkp/pkp-lib#2076.

**Comment by bozana** [comment]
Thanks a lot @ctgraham!!! :-)))

**Comment by bozana** [comment]
the improvement migrated to master: https://github.com/pkp/ojs/pull/1303
can this issue be closed now?

**Comment by ctgraham** [comment]
Yes, closing....
