### ISSUE TITLE
[OJS] Payments need to be enabled to change the length of journal embargo

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3330]
At the moment you need to enable payments to change the length of embargo. However, not all journals are selling online subscriptions even if they have an embargo. Maybe move the embargo length settings to under distribution?

**Comment by ajnyga** [comment]
Also the settings Author Self-Archiving Policy are in a very odd place now in Payments => Subscription Policies. A journal should be able to edit this setting even if they are Gold open access, so this really does not have much to do with subscription or payment settings?

**Comment by ajnyga** [comment]
@asmecher now that Nate has merged the new settings forms, how about these changes?

I think that everything under "Open Access Options For Subscription Journals" in Payments > Subscription policies should be moved somewhere else because they are not settings about payments at all.

So:
- Move embargo length setting from Payments to Settings > Distribution > Access (visible when publish mode subscription is enabled)
- Move "Delayed Open Access Policy" setting from Payments to Settings > Distribution > Access (visible when publish mode subscription is enabled)
- "Author Self-Archiving Policy" is actually available in Settings > Distribution > Permissions in OJS 3.1 but can not find it anywhere in master branch version with the new forms. I think the right place would be Settings >Workflow > Submission > Author guidelines. And we just need to remove that from Payment settings.

Wondering whether the "Registered readers will have the option of receiving the table of contents by email when an issue becomes open access." setting actually works? If it does I would add that to Settings > Distribution > Access  as well, and also visible if publish mode subscription is enabled of course.

**Comment by asmecher** [comment]
Your proposals make sense to me, thanks. 

The "Registered readers will have the option of receiving the table of contents by email..." option relates to `classes/tasks/OpenAccessNotification.inc.php`, which is kicked off by the scheduled tasks structure. I haven't specifically tested this recently but as far as I'm aware it should work.

**Comment by ajnyga** [comment]
Great, This is a good way to see how the new forms work. I will prepare a pr for the changes later this week.

**Comment by ajnyga** [comment]
I can see that the location of author self archive policy was discussed here: https://github.com/pkp/pkp-lib/issues/3562

In OJS 3.1 it was located in Settings > Distribution > Permissions 

However, with the merge of this https://github.com/pkp/pkp-lib/issues/3594 to master branch it was removed from the settings and also the translation keys for the label and description have been removed.

Was this intentional? @asmecher @NateWr ?

**Comment by NateWr** [comment]
Do you know what the setting name for "Author Self-Archiving Policy" is and where it is used? I may have gotten rid of it because I could find no uses of the setting in the system. This happened with a few dead context settings.

**Comment by ajnyga** [comment]
Yeah I noticed that it is removed from the about the journal page as well.

It is basically just a placeholder for a text where you can enter the journals self-archiving policy description. I was wondering if you had just decided to remove the field and let journals add the text to the general "about the journal" text? But in any case I think we should take into account in the upgrade process that the text gets moved from the old setting to the "about the journal" text? Some journals may have detailed descriptions there that they will lose otherwise.

The test above failed but it was just one test and during a specific submission test. Seems like a glitch?

**Comment by NateWr** [comment]
The text will still be in the database. If it was removed, it was probably because we do not use the text anywhere on the site. So a journal may have a custom theme using it, but we don't.

If you need it you can copy this plugin to get it back: https://github.com/NateWr/institutionalHome/blob/master/InstitutionalHomePlugin.inc.php

Otherwise I think I'd want to have a conversation about why we have it. If we think it's valuable, why weren't we showing it in any of our themes or during the workflow? If not, let's let it go.

**Comment by ajnyga** [comment]
I think what happened is that the setting was in a bad place under Payments and since those settings did not make it into original OJS3, the setting was neglected and was missing from the theme templates as well.

However, it has been available in OJS3.1 under Distribution > Permissions so probably some journals have filled it. I do not have a problem fetching the data from db, but there are a lot of journals who can not do that so they end up loosing the text they entered.

I do not have strong opinion whether we need this field. It was just one of the settings I noticed was in the wrong place under Payments so I suggested moving it a year ago.

This is a setting that is not used in the workflow like for example author guidelines is. I guess the real question here is that do we just 
a) let journals decide and think what kind of data they want to have in their "About the journal" descriptions or
b) use fields like this to guide them to fill in specific kind of data about their journal

This is important piece of information for online journals to have on their site, but of course they can always write it in their general about the journal description.

**Comment by ajnyga** [comment]
You know what, the same thing applies to the `delayedOpenAccessPolicy` setting that I moved in the pr. That is also a piece of text that used to be shown on the about the journal page, but now we only have the settings left.

So add that to the discussion.

Do we want to have these separate text fields and show them on the about the journal page if they are filled?

**Comment by NateWr** [comment]
The `delayedOpenAccessPolicy` is still used on the subscription policy form. If this information is wanted on the about page then journals can add it there. Only a tiny fragment of our journals would use such a field so it doesn't make sense for us to support it outside of the subscription policy stuff.

**Comment by ajnyga** [comment]
Yes I am planning to move that as suggested above. Payments is not the right place for it. The subscription policy form is actually broken in master branch at the moment. Seems like it is not converted to support the current way form are handled in master branch. Not sure.

But in general if we support a delayed open access setting under Settings > Distribution > Access, editors need to have an easy way to determine how long that delay is without enabling payments. Whether we need a separate field the describe their policy in more detail (delayedOpenAccessPolicy) is another question.

**Comment by ajnyga** [comment]
Just curious, do we have any figure on how many journals use delayed open access in OJS? In journal.fi it is around 20 journals out of 70.

**Comment by asmecher** [comment]
Broadly speaking, the OJS 2.x setup interface used to contain a lot of bespoke fields for various kinds of policies. We cut way back on these in OJS 3.x, to decrease the size of setup but also let journal managers design their "about" pages as they want using e.g. the nav menus tool. However, I think we'll still need to find a "best" balance, as some of those fields fed downstream tool/services like DOAJ and OJS 3.x doesn't have equivalents. It's likely that we still have fields in setup that aren't presented on the front end, and I think the best general approach is to remove them if they aren't used, but leave existing content in the DB in case we reconstitute them later.

**Comment by ajnyga** [comment]
Ok,

So remove both `delayedOpenAccessPolicy` and  `Author Self-Archiving Policy` from the settings?

**Comment by asmecher** [comment]
Yes, agreed that we can remove both of those. And I suspect they aren't commonly used enough to be worth concatenating into "About", as we do for other settings on the 2.x to 3.x upgrade; having them stick around in the database is enough to ensure they aren't lost to users who do use them IMO.

**Comment by ajnyga** [comment]
Ok, I will revise my pr above tomorrow then and re-run the tests. 
We will then just move the embargo length setting under distrobution settings. This enables journals to define embargo length without enabling payments. 

I will also drop all the translation keys related to those two settings we are removing.

**Comment by asmecher** [comment]
I don't see any open PRs remaining here -- is this one ready to be closed, @ajnyga?

**Comment by ajnyga** [comment]
There is still the setting for the embargo notification that I left in the payment form. Should we move that as well? If there is a general section for notification settings then that would be a better place.

**Comment by mukaanyes** [comment]
Hello,
Is there any option to set embargo time for each submission separately. When we use a publish-as-you-go model, setting embargo time to the issue wont make sense.

Regards

**Comment by NateWr** [comment]
Closing this as stale. Feel free to open a new issue if there is any more work to be done.
