### ISSUE TITLE
[OJS] if html part of mail too long, new line with exclamation mark is inserted

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3338]
Hello

This is related to this SO : https://stackoverflow.com/a/42777909

I think it's because new lines in the mail template are not considered, so the html part of a mail is in one line with sometimes longer than 998 characters like REVIEW_REQUEST_ONECLICK

One solution is to add in lib/pkp/classes/mail/Mail.inc.php (l464), $mailer->Encoding = 'base64';

PS: we use ojs-stable-3_1_0

**Comment by asmecher** [comment]
@forgive38, I was unable to replicate the problem behavior, but setting `base64` didn't have any negative side-effects, so I've merged that change. Thanks!
