### ISSUE TITLE
Make the review type visible in the review assignments grid

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3342]
After a review type is selected, we don't actually show that anywhere so it's not possible to know what kind of review was assigned.

**Comment by ajnyga** [comment]
@NateWr I have this in the open reviews pr: https://github.com/ajnyga/pkp-lib/blob/f0e5ab0b5ffcd06ac7047a55f727ce296c8d2438/controllers/grid/users/reviewer/AuthorReviewerGridCellProvider.inc.php#L61-L62

**Comment by NateWr** [comment]
👍 If you can remember, when it's merged can you check back here and I'll close it?

**Comment by NateWr** [comment]
@ajnyga is this implemented now?

**Comment by ajnyga** [comment]
yes https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/reviewer/AuthorReviewerGridCellProvider.inc.php#L61
