### ISSUE TITLE
[OJS] Missing geoLocationTool raises error

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#335]
The following checks in ojs-dev-2_4 are not enough to prevent calling the GeoLocationTool functions if the GeoLocationTool is missing:
https://github.com/pkp/ojs/blob/c140083134b2da5ca95804c05e072f50ae6c1eb3/controllers/statistics/form/ReportGeneratorForm.inc.php#L168
https://github.com/pkp/ojs/blob/c140083134b2da5ca95804c05e072f50ae6c1eb3/controllers/statistics/ReportGeneratorHandler.inc.php#L119
https://github.com/pkp/ojs/blob/c140083134b2da5ca95804c05e072f50ae6c1eb3/pages/manager/StatisticsHandler.inc.php#L294

In the call `$geoLocationTool =& StatisticsHelper::getGeoLocationTool();`, $geoLocationTool will be set to an object with null properties, making $geoLocationTool true.
Subsequent calls depending on a working GeoLocationTool will fail.

There is another unchecked call to `StatisticsHelper::getGeoLocationTool()` at:
https://github.com/pkp/ojs/blob/c140083134b2da5ca95804c05e072f50ae6c1eb3/plugins/generic/usageStats/UsageStatsLoader.inc.php#L75
This is used unchecked at:
https://github.com/pkp/ojs/blob/c140083134b2da5ca95804c05e072f50ae6c1eb3/plugins/generic/usageStats/UsageStatsLoader.inc.php#L199
via
https://github.com/pkp/ojs/blob/c140083134b2da5ca95804c05e072f50ae6c1eb3/plugins/generic/usageStats/UsageStatsLoader.inc.php#L154

**Comment by beghelli** [comment]
Thanks Clinton! :)
