### ISSUE TITLE
[OJS] homeHeaderTitleImage not migrated to pageHeaderLogoImage with OJS 2.4.6 --> 3.1.0.1

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#3356]
Hi,

When upgrading from OJS 2.4.6 to 3.1.0.1, our journals' logos (kept in homeHeadTitleImage) don't get migrated to the pageHeaderLogoImage of OJS 3. I know that there's a logo field in OJS 2.4, but that only displays an image on the homepage and not on all pages. Since pageHeaderLogoImage in OJS 3 displays on all pages, shouldn't homeHeadTitleImage be mapped to that field?

**Comment by martinpub** [comment]
Hi, still interested, closed by mistake, sorry!

**Comment by asmecher** [comment]
@NateWr, tagging for your thoughts, not necessarily for coding just yet.

**Comment by NateWr** [comment]
I'm not familiar with all of the different images OJS 2.x supported. But in OJS 3 we've got two:

- An image for your logo, nameplate or other branding that's displayed on every page.
- A general image, usually expected to be a picture, for display on the homepage.

If `homeHeaderTitleImage` fits one of these roles, it should probably be migrated. If not, it probably shouldn't be.

**Comment by martinpub** [comment]
OK, I see. Manual upload is not ideal for a big multi-journal site, but it'll solve our problem.
