### ISSUE TITLE
Disciplin element should be discipline

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3357]
Hi @bozana 

I am doing some additions to our excel to XML converter script and noticed this:
https://github.com/pkp/pkp-lib/blob/master/plugins/importexport/native/pkp-native.xsd#L324

I think that it Swedish? Should it be "discipline".

**Comment by bozana** [comment]
Ah, good catch @ajnyga! Unfortunately yes, you are right :-P Also here: https://github.com/pkp/pkp-lib/blob/master/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php#L351
I didn't know I can Swedish :-D ;-)

**Comment by ajnyga** [comment]
Tack så mycket!

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3358
ojs master: https://github.com/pkp/ojs/pull/1827 (only submodule update)
