### ISSUE TITLE
[OJS] COMPONENT_ROUTER_PATHINFO_MARKER request raises error in Request::getRequestedPage()

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#336]
An RPC request such as /$$$call$$$/statistics/report-generator/fetch-report-generator causes errors in each hook call for `TemplateManager::display` which calls `Request::getRequestedPage()`.  For example:
https://github.com/pkp/ojs/blob/c140083134b2da5ca95804c05e072f50ae6c1eb3/plugins/generic/externalFeed/ExternalFeedPlugin.inc.php#L176
or
https://github.com/pkp/ojs/blob/c140083134b2da5ca95804c05e072f50ae6c1eb3/plugins/generic/announcementFeed/AnnouncementFeedPlugin.inc.php#L76
if called from the Custom Report Generator.

An example stacktrace is:
```
[error] ojs2 has produced an error
  Message: WARNING: call_user_func_array() expects parameter 1 to be a valid callback, class 'PKPComponentRouter' does not have a method 'getRequestedPage'
  In file: /ojs-dev-2_4/lib/pkp/classes/core/PKPRequest.inc.php
  At line: 829
  Stacktrace: 
   File: (unknown) line (unknown)
     Function: PKPApplication->errorHandler(2, "call_user_func_array() expects parameter 1 to be a valid callback, class 'PKPComponentRouter' does not have a method 'getRequestedPage'", "/ojs-dev-2_4/lib/pkp/classes/core/PKPRequest.inc.php", 829, Array(5))
   File: /ojs-dev-2_4/lib/pkp/classes/core/PKPRequest.inc.php line 829
     Function: call_user_func_array(Array(2), Array(1))
   File: /ojs-dev-2_4/lib/pkp/classes/core/PKPRequest.inc.php line 723
     Function: PKPRequest->_delegateToRouter("getRequestedPage")
   File: /ojs-dev-2_4/plugins/generic/announcementFeed/AnnouncementFeedPlugin.inc.php line 76
     Function: PKPRequest->getRequestedPage()
   File: (unknown) line (unknown)
     Function: AnnouncementFeedPlugin->callbackAddLinks("TemplateManager::display", Array(5))
   File: /ojs-dev-2_4/lib/pkp/classes/plugins/HookRegistry.inc.php line 89
     Function: call_user_func(Array(2), "TemplateManager::display", Array(5))
   File: /ojs-dev-2_4/lib/pkp/classes/template/PKPTemplateManager.inc.php line 332
     Function: HookRegistry->call("TemplateManager::display", Array(5))
   File: /ojs-dev-2_4/lib/pkp/classes/form/Form.inc.php line 190
     Function: PKPTemplateManager->display("controllers/statistics/form/reportGeneratorForm.tpl", Null, Null, False)
   File: /ojs-dev-2_4/controllers/statistics/form/ReportGeneratorForm.inc.php line 211
     Function: Form->fetch(Object(Request))
   File: /ojs-dev-2_4/controllers/statistics/ReportGeneratorHandler.inc.php line 40
     Function: ReportGeneratorForm->fetch(Object(Request))
   File: (unknown) line (unknown)
     Function: ReportGeneratorHandler->fetchReportGenerator(Array(0), Object(Request))
   File: /ojs-dev-2_4/lib/pkp/classes/core/PKPRouter.inc.php line 362
     Function: call_user_func(Array(2), Array(0), Object(Request))
   File: /ojs-dev-2_4/lib/pkp/classes/core/PKPComponentRouter.inc.php line 246
     Function: PKPRouter->_authorizeInitializeAndCallRequest(Array(2), Object(Request), Array(0))
   File: /ojs-dev-2_4/lib/pkp/classes/core/Dispatcher.inc.php line 134
     Function: PKPComponentRouter->route(Object(Request))
   File: /ojs-dev-2_4/lib/pkp/classes/core/PKPApplication.inc.php line 178
     Function: Dispatcher->dispatch(Object(Request))
   File: /ojs-dev-2_4/index.php line 64
     Function: PKPApplication->execute()
```

There is dark voodo that I have not fully explored here.

Should RPC calls like this bypass the hook system?  Should PKPComponentRouter have a getRequestedPage which just returns COMPONENT_ROUTER_PATHINFO_MARKER?

**Comment by beghelli** [comment]
Clinton, couldn't reproduce this. You just open the report generator page and the error happens?

**Comment by ctgraham** [comment]
Hmmm.... my workflow was: checkout ojs-dev-2_4; enable display_errors in config.inc.php, login and navigate to Journal Manager -> Stats & Reports -> Generate Custom Report.

In my case, the ajax to fetch-report-generator is prepended by the OJS error, and javascript errors out.

**Comment by beghelli** [comment]
I see, well, the report generator it's not working only if I have a code error or warning and the display error is on, which I think it's expected, because the ajax answer receives the error string... but if I have no error (which is my default), the page just loads. I can't see the error you have... maybe I have to enable the announcement feed plugin? Did you tried disabling it?

**Comment by ctgraham** [comment]
Yes, correct.  The error is raised by the plugins which call `Request::getRequestedPage()`.  It's not really related to the stats/report framework other than that the report generator uses one of the few RPC calls.  The issue is really with the interaction of RPC handling and hook management.

**Comment by beghelli** [comment]
Can you confirm that if you have display error off you can access the report generator? If yes, I think we can defer that to 2.4.7.

**Comment by ctgraham** [comment]
Yes.  With display_errors off, the error only propagates to the log, and the Report Generator will work as expected.  I'm fine with deferring to 2.4.7.

**Comment by asmecher** [comment]
Deferred.

**Comment by asmecher** [comment]
@ctgraham, this should fix it:
https://github.com/pkp/ojs/pull/606

The problem is that the plugin is assuming that we're dealing with a page request and failing to behave gracefully when it's actually a component request. There are already similar checks in other plugins.

If you're still using an install where it's easy to check, could you try this out?

**Comment by ctgraham** [comment]
Yes, https://github.com/pkp/ojs/pull/606 resolves the error in the Announcement Feeds plugin for me.  The error in the External Feeds plugin remains, but I suppose this can be resolved by adding:
```php
                // Only pages requests interest us here 
                $request =& Registry::get('request');
                if (!is_a($request->getRouter(), 'PKPPageRouter')) return false;
```
to the top of ExternalFeedPlugin::displayHomepage()?

**Comment by asmecher** [comment]
Thanks, adding the above and merging.
