### ISSUE TITLE
Can't start review discussion as author

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3362]
I know Alec will hate me for assigning this to 3.1.1, but seems like a serious bug if others can reproduce it. 

When logged in as author, I'm unable to start a review discussion from the author dashboard. Clicking the ok button sends off a request, but when it returns nothing changes and there's no error message. The XHR request is returning:

```{"status":false,"content":"","elementId":"0","events":null}```

**Comment by ajnyga** [comment]
I have been doing that a lot with 3.1.0.1. while testing the open reviews and have not encountered this. But maybe this is something in the master branch?

**Comment by asmecher** [comment]
I'm also unable to duplicate this -- @NateWr, can you pass me a copy of your database? Unless it seems widespread I don't consider it a show-stopper for 3.1.1, but it's definitely worth tracking down.

**Comment by asmecher** [comment]
Assigning to you, @NateWr, to narrow down replicating this -- but I'm also happy to test, debug and fix, if you can send me a DB dump.

**Comment by NateWr** [comment]
Just tried to reproduce after updating things and it seems alright. Closing.
