### ISSUE TITLE
Internal usage report: article views/downloads

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3366]
Display article views/downloads in table form. 

**Display Notes**
* Table columns: Title (w/link to published work); # of views (abstract, galley(s), total).
* Default sort by: # of views, highest # first.
* Default display: top 25 articles. 
* Provide an option to filter by article, section, author, ??. 
* Provide an option to set date parameters. 
* Provide an option to export to csv. 

**Availability**
* Editor Dashboard (for all articles in journal; optionally filter for specific article)
* Admin Dashboard (for all articles on platform; optionally filter for specific journal, or article)
* Author Dashboard (for all authored articles; optionally filter for specific authored article)

**Comment by bozana** [comment]
I will put some comments i.e. thought on implementing the REST API for this and the issue https://github.com/pkp/pkp-lib/issues/3367 here:
There could be a 'generic' function usageStats with the required parameter "object" i.e. "assoc_type", that would be article per default and could be issue as well. Thus such a function usageStats with object=Article would return the records with e.g. following properties for each article:
id: article id
title: article title
views: abstract views
downloads: galley file downloads (total for all galley files, but we can still discuss it)
total: views + downloads
from: first date
until: last date
Then there could be additional parameters sectionId, authorId and eventual issueId that would filter the results i.e. provide the results only for articles belonging to that sectionId, authorId or issueId.

**Comment by NateWr** [comment]
Hi @bozana, that sounds good. Have you looked at the Service class approach we're using with the `/submissions` and `/issues` API endpoints? I think they follow a similar approach to what you describe, and it would make sense to have a generic `StatsService`, and have this use the same pattern as other objects throughout the system, so we didn't have a unique class with it's own internal structure.

In terms of API endpoints, I think we should try to follow the REST approach of having an endpoints represent stable objects. So it would be nice to have endpoints like this:

```
/stats/articles - delivers top X results by views or downloads
/stats/articles/<id> - delivers that article detail
/stats/issues - same for issues
/stats/issues/<id>
```

Filtering is then done by passing query args:

```
/stats/articles?sectionId=2
/stats/articles?dateFrom=YYYY-MM-DD&dateTo=YYYY-MM-DD
```

The `/stats` endpoint would be a repository for all of our stats work, so there would eventually be stuff like:

```
/stats/countries
/stats/reviewers
etc.
```

If you wanted, I could code up a sample of how I'd see the API endpoint being served, and you can take a look and see if it would work alright for what you had in mind?

**Comment by bozana** [comment]
Ah, I see :-) I do not know what I was thinking with this "generic" object bla bla :-) Thanks a lot @NateWr! No need to code it up now -- I just wanted to have a rough overview how it will be/is needed to be...

**Comment by NateWr** [comment]
Closing this as I think the initial request is already implemented. CSV downloads will be added in #7318.
