### ISSUE TITLE
Add UI to view usage stats for issues

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3367]
Display issue views/downloads in table form.

**Display Notes**
* Table columns: Issue title (w/link to published issue); # of articles; total # of views (issue TOC); * total # of views (all articles).
* Default sort by # of views.
* Default display top 5 issues.
* Provide an option to filter by issue.
* Provide an option to export to csv.

**Availability**
* Editor Dashboard (for all issues in journal; optionally filter for specific issue)
* Admin Dashboard (for all issues on platform; optionally filter for specific journal, or issue)

**Comment by bozana** [comment]
Similarly to the comment in this issue https://github.com/pkp/pkp-lib/issues/3366, the function `usageStats` with object=Issue would return the records with e.g. following properties for each issue:
id: issue id
title: issue identification
views: toc views
downloads: issue galley file downloads (total for all galley files, but we can still discuss it)
total: views + downloads
from: first date
until: last date
Then there could be additional parameters issueId that would filter the results i.e. provide the data only for the specified issueId.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
