### ISSUE TITLE
Add a table and map to show usage statistics by country, region and city

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3368]
Display geographic distribution in a table, and map. 

**Technical Notes**
* Use Chart.js or D3 for the map. 
* Enable only when OJS is collecting geographic data. 
* Warn if geographic data is not being collected. 

**Display Notes (table)**
* Columns should include Country name; total # of views/downloads
* Filter by: article ID/title; section; ??
* Default to all-time, but allow date parameters to be set
* Allow download to csv. 

**Display Notes (map)**
* Display # of total views by country
* Filter by: article ID/title; section; ??
 * Default to all-time, but allow date parameters to be set

**Availability**
* Editor Dashboard (for all articles in journal; optionally filter for specific article)
* Admin Dashboard (for all articles on platform; optionally filter for specific journal, or article)
* Author Dashboard (for all authored articles; optionally filter for specific authored article)

**Comment by NateWr** [comment]
Chart.js won't do maps but D3 would, I think.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
