### ISSUE TITLE
Add a UI to view institution statistics

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3369]
Add a page in the editorial backend where editors can view institutional usage statistics. This UI should only be available when institutional statistics are being recorded.

**Display Notes**
* Display a table in the usage dashboard, with the following columns: Institution (name); Type; # of views
* Default order by # of views
* Sort by column title
* Default to all-time, but allow date parameters to be set
* Default display of top 25 institutions

**Availability**
* Editor Dashboard (for all articles in journal; optionally filter for specific article)
* Admin Dashboard (for all articles on platform; optionally filter for specific journal, or article)
* Author Dashboard (for all authored articles; optionally filter for specific authored article)

**Comment by pmangahis** [comment]
+ 1 interest from Hosting

**Comment by NateWr** [comment]
Institutional stats will be available in CSV form as part of #6895. I've adapted this issue to request an editorial UI to view these stats.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
