### ISSUE TITLE
[OJS] Show keywords if available in any locale

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3370]
At the moment if you add for example keywords in English and look at the article with the Finnish UI, the keywords are not visible on the abstact page. For example the article title and the abstract are shown. It would make sense that keywords would be shown using the same logic meaning that there would be a fallback to any available content.

**Comment by asmecher** [comment]
Agreed, though of course this would need to apply consistently with other vocabulary-based metadata fields.

**Comment by NateWr** [comment]
This is because the templates look specifically for the keywords in the current locale.

https://github.com/pkp/ojs/blob/master/templates/frontend/objects/article_details.tpl#L128-L143

Should we instead be doing the fallback mechanism for `Submission::getLocalizedData()` which is, I believe:

1. Current locale
2. Submission locale
3. Primary locale
4. Any locale

**Comment by asmecher** [comment]
We don't have the `4. Any locale` fallback, and I'd argue that it would be confusing. Otherwise yes, I think you've got it (though OTOH I think we're not totally consistent on 2/3).

**Comment by NateWr** [comment]
> We don't have the 4. Any locale fallback, and I'd argue that it would be confusing.

That was what I thought too, but it appears we do:

https://github.com/pkp/pkp-lib/blob/master/classes/core/DataObject.inc.php#L61-L68

https://github.com/pkp/pkp-lib/blob/master/classes/submission/Submission.inc.php#L150-L154

**Comment by asmecher** [comment]
Huh, right you are. OK, let's stay consistent for now; it's not something we've received feedback about either way.

**Comment by asmecher** [comment]
The keyword display uses `getLocalizedData` since 3.2.0, so I think this is already resolved. (Tested `stable-3_2_1`.)
