### ISSUE TITLE
Submission lists don't load if journal section has been deleted

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3378]
If a JM or JE deletes a journal section that's assigned to an existing submission, the submission lists fail to load.

Suggest either preventing JM/JE from deleting assigned journal sections or updating submission list display to handle submissions without an assigned journal section.

**Comment by asmecher** [comment]
What version do you see this in, @mfelczak?

Possibly related: https://github.com/pkp/pkp-lib/issues/2415

**Comment by mfelczak** [comment]
Thanks @asmecher, this was a 3.0.2 install and it looks like #2415 will fix it, closing.
