### ISSUE TITLE
Article subtitles should appear in the issue TOC

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3379]
Can we enable the article subtitles to appear in the issue table of contents for OJS? It seems unconventional to exclude them.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/1868

**Comment by NateWr** [comment]
Tests passed. @asmecher any objections to merge here?

**Comment by asmecher** [comment]
@NateWr, this does a string concatenation (see `PKPString::concatTitleFields`) -- I wonder whether it wouldn't be a better idea to expose things in a way that would be better styled using CSS?

**Comment by NateWr** [comment]
Good idea. There isn't quite the typographic range for this to work great in the default theme but it's good to have it in place for child themes. I've made the changes now and prepared other themes for that too if you want to take another look.

Default:
![selection_080](https://user-images.githubusercontent.com/2306629/37090819-c1ca6f28-21fd-11e8-9f98-eeb26152e3e8.png)

Manuscript:
![selection_085](https://user-images.githubusercontent.com/2306629/37090861-e9735c56-21fd-11e8-819a-e99abea7abe6.png)

A couple of Bootstrap themes:
![selection_082](https://user-images.githubusercontent.com/2306629/37090870-ef9704c0-21fd-11e8-9f29-7b264c003119.png)

![selection_083](https://user-images.githubusercontent.com/2306629/37090871-f3427db6-21fd-11e8-8941-1c133351c792.png)

Health Sciences:
![selection_081](https://user-images.githubusercontent.com/2306629/37090877-fc697c96-21fd-11e8-9e59-7b10d1d1842b.png)

**Comment by asmecher** [comment]
Oops, followed up on the PR rather than the issue:

> @NateWr, this looks great! Please go ahead.

**Comment by NateWr** [comment]
Merged. :+1:
