### ISSUE TITLE
no context in LazyLoadPlugin get/setEnabled when using CLI

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3383]
For example: The native import allows DOIs to be imported. This requires the DOI pubId plugin to be enabled and registered for the hook articledao::getAdditionalFieldNames. The plugin register function is only called if the plugin is enabled, s. https://github.com/pkp/pkp-lib/blob/master/classes/plugins/PKPPubIdPlugin.inc.php#L28. This calls LazyLoadPlugin::getEnabled, s. https://github.com/pkp/pkp-lib/blob/master/classes/plugins/LazyLoadPlugin.inc.php#L56, which searches after the context in the request and does not find it, because all this is called from the CLI.
This case could be eventually fixed by providing the optional contextId parameter to the plugin register function here: https://github.com/pkp/pkp-lib/blob/master/classes/plugins/PluginRegistry.inc.php#L135, and then also to the getEnabled function.
@asmecher, what do you think about it? Is there maybe another/better way to solve this?  Is there maybe a way to fake the request object i.e. to have something like CLIRequst? -- I have no overview and especially about consequences :-/

**Comment by asmecher** [comment]
Hmm, generally speaking I think it would be good to avoid using a `Request` object in headless operations, so passing the optional `contextId` parameter in makes sense to me. (As we reduce the use of static calls to  `Request` functions, the reach of the `$request` object should become more logical -- right now it's peppered through the system, making it hard to work with command-line tools and other things that don't/shouldn't provide a `$request` object.)

**Comment by bozana** [comment]
@asmecher, could you please see these commits:
1) the first commit are minimal changes so that DOIs and URNs can be correctly imported using the CLI native import:
pkp-lib: https://github.com/bozana/pkp-lib/commit/4338f6f483893c67868dc4289511c3d11eee8cf5
ojs: https://github.com/bozana/ojs/commit/bfc8980ce013cb0dfd8934338e1424735bb5716d
2) second commit considers additionally all other plugins:
pkp-lib: https://github.com/bozana/pkp-lib/commit/d05d2c8ba47504f20d59a73a18edd9a7f8b5773c
ojs https://github.com/bozana/ojs/commit/59d2a54574b9358ad9625544f3bfac5bdc7dc11f

I just wanted to double check if considering/changing all of them immediately would be ok and make sense :-) If so I will proceed (test and also consider the plugins in other repositories)...

THANKS!!!

**Comment by asmecher** [comment]
Thanks, @bozana, that's a good solution! Please go ahead. I made one minor comment but I really don't mind either way on that one.

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/3430
https://github.com/pkp/ojs/pull/1853
https://github.com/pkp/omp/pull/506
