### ISSUE TITLE
[OJS 3.1.0-1] Very slow loading of Add Reviewer form

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#3384]
I am running an OJS 3.1.0-1 instance installed from published .tar.gz archive. I migrated a journal from 2.x with roughly 850 registered reviewers. When I try to assign a reviewer via the *Add Reviewer* button, the form only presents a 'Loading' statement. I have one XHR request pending:
```
http://localhost:8008/$$$call$$$/grid/users/reviewer-select/reviewer-select-grid/fetch-grid?submissionId=3415&stageId=3&reviewRoundId=35628&_=1518694633653
```
sqld is eating one full cpu core. After **8 minutes** the request succeeds and the form for reviewer selection shows up. Subsequent requests finish instantaneously, as long as I don't reset the php container.

Please tell me what information is needed for fixing this problem.

**Comment by asmecher** [comment]
@pkel, it sounds to me like MySQL is executing a nasty query, then caching the results internally for subsequent executes. (OJS itself doesn't do caching on this particular query.)

I would suggest using the `debug` setting in `config.inc.php` to get OJS to dump out the SQL queries it executes in the process. Note that once you enable this setting, SQL queries will be dumped to the browser (for all users!), and that'll break AJAX subrequests -- you'll need to manually request the URL you quoted above in order to get the queries you need.

Two main possibilities sprint to mind:
- The query is ill-behaved per a normal OJS3 database, or
- Your database is missing an index or has abnormal data.

**Comment by pkel** [comment]
@asmecher, I turned on the debug setting and triggered the request. [This](https://github.com/pkp/pkp-lib/files/1736235/fishy-grid-call-debug-censored.html.gz) is the result. A lot is happening there. Can you help to identify the problem? I see duplicate key errors on `controlled_vocab_symbolic`. Do you think they can cause the problem?

**Comment by asmecher** [comment]
@pkel, I'm not sure what's happening with the controlled vocabularies there -- I'm not sure why that page would be generating `INSERT` statements -- but I think the query that's most likely to be slow is this one:

    SELECT u.*, COUNT(DISTINCT rac.review_id) AS complete_count, AVG(DATEDIFF(rac.date_completed, rac.date_notified)) AS average_time, MAX(raf.date_assigned) AS last_assigned, COUNT(DISTINCT rai.review_id) AS incomplete_count FROM users u JOIN user_user_groups uug ON (uug.user_id = u.user_id) JOIN user_groups ug ON (ug.user_group_id = uug.user_group_id AND ug.role_id = 4096 AND ug.context_id = 1) JOIN user_group_stage ugs ON (ugs.user_group_id = ug.user_group_id AND ugs.stage_id = 3) LEFT JOIN review_assignments ras ON (ras.submission_id = 3415 AND ras.stage_id = 3 AND ras.review_round_id = 35628 AND ras.reviewer_id=u.user_id) LEFT JOIN review_assignments rac ON (rac.reviewer_id = u.user_id AND rac.date_notified IS NOT NULL AND rac.date_completed IS NOT NULL) LEFT JOIN review_assignments raf ON (raf.reviewer_id = u.user_id) LEFT JOIN review_assignments ran ON (ran.reviewer_id = u.user_id AND ran.review_id > raf.review_id) LEFT JOIN review_assignments rai ON (rai.reviewer_id = u.user_id AND rai.date_notified IS NOT NULL AND rai.date_completed IS NULL AND rai.declined = 0 AND rai.replaced = 0) WHERE ras.review_id IS NULL AND ran.review_id IS NULL GROUP BY u.user_id HAVING 1=1 ORDER BY last_name, first_name

Could you try running this in a MySQL client (hopefully flushing MySQL's cache first)?

**Comment by pkel** [comment]
That's indeed the problematic query!

**Comment by asmecher** [comment]
@pkel, good, this helps narrow it down. Now to distinguish between the two possibilities [outlined above](https://github.com/pkp/pkp-lib/issues/3384#issuecomment-365977055) -- could you run an `EXPLAIN` on that query to see if we can identify a missing index or similar?

**Comment by pkel** [comment]
```
MariaDB [ojs]> EXPLAIN SELECT u.*, COUNT(DISTINCT rac.review_id) AS complete_count, AVG(DATEDIFF(rac.date_completed, rac.date_notified)) AS average_time, MAX(raf.date_assigned) AS last_assigned, COUNT(DISTINCT rai.review_id) AS incomplete_count FROM users u JOIN user_user_groups uug ON (uug.user_id = u.user_id) JOIN user_groups ug ON (ug.user_group_id = uug.user_group_id AND ug.role_id = 4096 AND ug.context_id = 1) JOIN user_group_stage ugs ON (ugs.user_group_id = ug.user_group_id AND ugs.stage_id = 3) LEFT JOIN review_assignments ras ON (ras.submission_id = 3415 AND ras.stage_id = 3 AND ras.review_round_id = 35628 AND ras.reviewer_id=u.user_id) LEFT JOIN review_assignments rac ON (rac.reviewer_id = u.user_id AND rac.date_notified IS NOT NULL AND rac.date_completed IS NOT NULL) LEFT JOIN review_assignments raf ON (raf.reviewer_id = u.user_id) LEFT JOIN review_assignments ran ON (ran.reviewer_id = u.user_id AND ran.review_id > raf.review_id) LEFT JOIN review_assignments rai ON (rai.reviewer_id = u.user_id AND rai.date_notified IS NOT NULL AND rai.date_completed IS NULL AND rai.declined = 0 AND rai.replaced = 0) WHERE ras.review_id IS NULL AND ran.review_id IS NULL GROUP BY u.user_id HAVING 1=1 ORDER BY last_name, first_name;
+------+-------------+-------+--------+----------------------------------------------------------------------------------------------------+----------------------------------+---------+----------------------+------+----------------------------------------------+
| id   | select_type | table | type   | possible_keys                                                                                      | key                              | key_len | ref                  | rows | Extra                                        |
+------+-------------+-------+--------+----------------------------------------------------------------------------------------------------+----------------------------------+---------+----------------------+------+----------------------------------------------+
|    1 | SIMPLE      | ug    | ref    | PRIMARY,user_groups_user_group_id,user_groups_context_id,user_groups_role_id                       | user_groups_role_id              | 8       | const                |    1 | Using where; Using temporary; Using filesort |
|    1 | SIMPLE      | ugs   | ref    | user_group_stage_user_group_id,user_group_stage_stage_id                                           | user_group_stage_user_group_id   | 8       | ojs.ug.user_group_id |    1 | Using where; Using index                     |
|    1 | SIMPLE      | uug   | ref    | user_user_groups_pkey,user_user_groups_user_group_id,user_user_groups_user_id                      | user_user_groups_pkey            | 8       | ojs.ug.user_group_id |  149 | Using index                                  |
|    1 | SIMPLE      | u     | eq_ref | PRIMARY                                                                                            | PRIMARY                          | 8       | ojs.uug.user_id      |    1 |                                              |
|    1 | SIMPLE      | ras   | ref    | review_assignments_submission_id,review_assignments_reviewer_id,review_assignments_reviewer_review | review_assignments_submission_id | 8       | const                |    1 | Using where; Not exists                      |
|    1 | SIMPLE      | rac   | ref    | review_assignments_reviewer_id,review_assignments_reviewer_review                                  | review_assignments_reviewer_id   | 8       | ojs.uug.user_id      |    2 | Using where                                  |
|    1 | SIMPLE      | raf   | ref    | review_assignments_reviewer_id,review_assignments_reviewer_review                                  | review_assignments_reviewer_id   | 8       | ojs.uug.user_id      |    2 |                                              |
|    1 | SIMPLE      | ran   | ref    | PRIMARY,review_assignments_reviewer_id,review_assignments_reviewer_review                          | review_assignments_reviewer_id   | 8       | ojs.uug.user_id      |    2 | Using where; Using index; Not exists         |
|    1 | SIMPLE      | rai   | ref    | review_assignments_reviewer_id,review_assignments_reviewer_review                                  | review_assignments_reviewer_id   | 8       | ojs.uug.user_id      |    2 | Using where                                  |
+------+-------------+-------+--------+----------------------------------------------------------------------------------------------------+----------------------------------+---------+----------------------+------+----------------------------------------------+
```

**Comment by asmecher** [comment]
Hmm, @pkel, would you be willing to send me a database dump?

**Comment by asmecher** [comment]
@pkel, it looks like the problem query is [`getFilteredReviewers`](https://github.com/pkp/pkp-lib/blob/8fbedc94d8266ff76f2e1e030cb240e0f43209da/classes/user/PKPUserDAO.inc.php#L264..L331), implemented in `PKPUserDAO.inc.php`. This query explodes a number of joins combinatorially, then pieces them together with aggregate functions. As you've seen, it doesn't take long before that combinatorial explosion causes performance to fail. (I'm not sure why your installation, which has relatively small amounts of data, is first to turn up this problem, but it is.)

The problem query has already been refactored for OJS 3.1.1 into a [new form](https://github.com/pkp/pkp-lib/blob/80774e138d3072af5f78e8a1a40a6c220bb67b4d/classes/services/queryBuilders/UserListQueryBuilder.inc.php#L274..L436) that uses subqueries instead of `LEFT JOIN` / `GROUP BY`. A quick test shows this to perform much better, and I suspect that could be improved further (if needed) with the addition of an index or two that corresponds to the specific conditions in the query.

I'm hesitant to invest any effort in converting the older query over to subqueries, since it's already dead code and OJS 3.1.1 is due for release in a short time -- but if you need this to perform better before 3.1.1 is released, what you'll need to do is move the `LEFT JOIN` queries...
```
LEFT JOIN review_assignments ras ON (ras.submission_id = ? AND ras.stage_id = ? AND ras.review_round_id = ? AND ras.reviewer_id=u.user_id)
LEFT JOIN review_assignments rac ON (rac.reviewer_id = u.user_id AND rac.date_notified IS NOT NULL AND rac.date_completed IS NOT NULL)
LEFT JOIN review_assignments raf ON (raf.reviewer_id = u.user_id)
LEFT JOIN review_assignments ran ON (ran.reviewer_id = u.user_id AND ran.review_id > raf.review_id)
LEFT JOIN review_assignments rai ON (rai.reviewer_id = u.user_id AND rai.date_notified IS NOT NULL AND rai.date_completed IS NULL AND rai.declined = 0 AND rai.replaced = 0)
```
...into subqueries in the `SELECT` clause...
```
(SELECT COUNT(rac.review_id) FROM review_assignments rac WHERE rac.reviewer_id = u.user_id AND rac.date_notified IS NOT NULL AND rac.date_completed IS NOT NULL) AS complete_count,
(SELECT AVG(DATEDIFF(rac.date_completed, rac.date_notified)) FROM review_assignments rac WHERE rac.reviewer_id = u.user_id AND rac.date_notified IS NOT NULL AND rac.date_completed IS NOT NULL) AS average_time,
(SELECT MAX(ran.date_assigned) FROM review_assignments ran WHERE ran.reviewer_id = u.user_id) AS last_assigned,
(SELECT COUNT(rai.review_id) FROM review_assignments rai WHERE rai.reviewer_id = u.user_id AND rai.date_notified IS NOT NULL AND rai.date_completed IS NULL AND rai.declined = 0 AND rai.replaced = 0) AS incomplete_count
```
Hopefully that helps!

**Comment by pkel** [comment]
If it is included in the next minor release, I see no problem. Thanks.

**Comment by asmecher** [comment]
@pkel, great -- thanks for working with me on this one.
