### ISSUE TITLE
Remove gender fields

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3387]
I don't think there's any good reason to have these.

**Comment by stranack** [comment]
Strongly agree.

**Comment by mtub** [comment]
Thanks.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/3389
- https://github.com/pkp/ojs/pull/1839
- https://github.com/pkp/omp/pull/503

**Comment by asmecher** [comment]
@bozana, could you review these?

**Comment by bozana** [comment]
@asmecher, looks good, please go ahead and make a lot of merging conflicts for me, when rebasing the huge changes from Nate... -- just now this issue had to pop-up! ;-) :-) :-D

**Comment by asmecher** [comment]
Done -- with apologies, @bozana!
