### ISSUE TITLE
[OJS] Remote galleys are not used for statistics

### ISSUE THREAD

**Issue by alonsoj** [pkp/pkp-lib#339]
When a galley is a remote file ArticleHandler does:
`$request->redirectUrl($galley->getRemoteURL());`
and the request does not arrive to UsageEventPlugin.inc, that has code to manage the request:
`if ($galley->isHTMLGalley() || $galley->getRemoteURL()) {`
so the remote galley is not used for statistics.

Is this the proper functioning?

Regards

**Comment by beghelli** [comment]
Hi Alonso,

Thanks for you review. Looking at the code I think you are right, I think we need to create an specific hook to be able to count remote galley usages correctly. I am testing this to make sure and create a fix if that's the case. Thanks again for your help.

**Comment by asmecher** [comment]
Looks good, Bruno; please go ahead.

**Comment by beghelli** [comment]
Closing, since master branches doesn't implement remote galleys.
