### ISSUE TITLE
upgrade email templates

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3390]
Currently an e-mail template update will using the function installEmailTemplate in the upgrade.xml would lead to having several same e-mail templates -- with the same e-mail key -- if that e-mail template already exist in the DB table email_templates_default.
Thus, use UPDATE instead of INSERT when inserting an e-mail template here: https://github.com/pkp/pkp-lib/blob/master/classes/mail/EmailTemplateDAO.inc.php#L671

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3401
ojs master: https://github.com/pkp/ojs/pull/1841 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look at the pkp-lib PR above?

**Comment by asmecher** [comment]
Looks good to me -- please go ahead!
