### ISSUE TITLE
pkp-lib/classes/xslt/XMLTypeDescription.inc.php Doesn't work when behind HTTP proxy

### ISSUE THREAD

**Issue by imranh2** [pkp/pkp-lib#3391]
> PHP Warning: DOMDocument::schemaValidate(https://www.crossref.org/schemas/crossref4.3.6.xsd): failed to open stream: Connection refused in /var/www/html/lib/pkp/classes/xslt/XMLTypeDescription.inc.php on line 133, referer: https://ijpds.org/management/importexport/plugin/CrossRefExportPlugin

`if (!$xmlDom->schemaValidate($this->_validationSource)) return false;` Is the problem child.

I've fixed it by replacing that line with:
```

                                $curlCh = curl_init();
                                if ($httpProxyHost = Config::getVar('proxy', 'http_host')) {
                                        curl_setopt($curlCh, CURLOPT_PROXY, $httpProxyHost);
                                        curl_setopt($curlCh, CURLOPT_PROXYPORT, Config::getVar('proxy', 'http_port', '80'));
                                        if ($username = Config::getVar('proxy', 'username')) {
                                                curl_setopt($curlCh, CURLOPT_PROXYUSERPWD, $username . ':' . Config::getVar('proxy', 'password'));
                                        }
                                }
                                curl_setopt($curlCh, CURLOPT_URL, $this->_validationSource);
                                curl_setopt($curlCh, CURLOPT_RETURNTRANSFER, 1);
                                $output = curl_exec($curlCh);

                                if (!$xmlDom->schemaValidate($output)) return false;
```

**Comment by asmecher** [comment]
This would solve the problem for XSD-based schemata, but not e.g. DTDs. Perhaps it's possible to solve this more generally using [stream_context_set_default](http://php.net/manual/en/function.stream-context-set-default.php)?

**Comment by bozana** [comment]
S. also discussion in this issue: https://github.com/pkp/pkp-lib/issues/1955

**Comment by NateWr** [comment]
Is this issue still relevant or can it be closed?

**Comment by henriqueramos** [comment]
@asmecher Could you please check those PRs? Thank you!

https://github.com/pkp/omp/pull/1058
https://github.com/pkp/ojs/pull/3286
https://github.com/pkp/ops/pull/226
https://github.com/pkp/pkp-lib/pull/7638

**Comment by asmecher** [comment]
@henriqueramos, the approach you've proposed I think still won't work for DTDs per [this comment](https://github.com/pkp/pkp-lib/issues/3391#issuecomment-366367922), and won't work when a schema file references another schema file (`<xs:import ...>`). The suggestion to use [`stream_context_set_default`](https://github.com/pkp/pkp-lib/issues/3391#issuecomment-366367922) would be a general solution to problems of this type. Did you give it a try?

**Comment by henriqueramos** [comment]
@asmecher I've update the code to use `stream_context_create`. Could you please take a look? Thank you!

https://github.com/pkp/omp/pull/1058
https://github.com/pkp/ojs/pull/3286
https://github.com/pkp/ops/pull/226
https://github.com/pkp/pkp-lib/pull/7638

**Comment by asmecher** [comment]
Thanks, @henriqueramos!

The PRs change the default stream context to add proxy support, but this is only executed in the `XMLTypeDescription` class. That means the PHP environment before and after using this class may be quite different -- any PHP built-ins like `readfile` involving URLs will not use a proxy before the call, but will start using it afterwards, regardless of whether they have anything to do with XML files.

I would suggest moving this code from the `XMLTypeDescription` class into the application initialization. That way the proxy config will be applied consistently as a general solution to problems of this type.

**Comment by henriqueramos** [comment]
@asmecher Could you please take a look on those Pull Requests? Thank you!

https://github.com/pkp/omp/pull/1058
https://github.com/pkp/ojs/pull/3286
https://github.com/pkp/ops/pull/226
https://github.com/pkp/pkp-lib/pull/7638

**Comment by asmecher** [comment]
@henriqueramos, this is a case where 5-10 lines of unstructured PHP is going to be a lot more maintainable than 420loc of abstractions that aren't used elsewhere. Can you simplify this down to just what's needed to convert the Guzzle-like configuration that's supplied in `config.inc.php` to the form that PHP's stream context toolset expects? Please cap this at 4 hours -- if there's more work than that required, stop where you are and let me know. You might need to give up the unit test in the process; that's OK, this might be better covered with an end-to-end test including a configured proxy.

**Comment by henriqueramos** [comment]
Ok @asmecher, I will remove the OOP logic from this Pull request. Only leaving the parser as a function to be called on PKPContainer. Also, making it as a function I will could keep the unit tests for it, leaving a better code coverage and avoid issues with non-deterministic e2e tests.

For historical purposes, my idea behind the implementation here it's to use Objects rather than primitive types.

There's a few links telling about why we should avoid using primitive types.

https://betterprogramming.pub/why-you-should-avoid-using-primitive-types-cb55857baa39
https://refactoring.guru/smells/primitive-obsession
https://medium.com/the-sixt-india-blog/primitive-obsession-code-smell-that-hurt-people-the-most-5cbdd70496e9
https://blog.ndepend.com/code-smell-primitive-obsession-and-refactoring-recipes/
https://wiki.c2.com/?ValueObject

**Comment by asmecher** [comment]
Thanks, @henriqueramos, I've merged the pkp-lib PR!
