### ISSUE TITLE
[OJS] OJS 3.0.2 tries to send mails with too long lines

### ISSUE THREAD

**Issue by woodfighter** [pkp/pkp-lib#3393]
Our installation tries to send out mails with lines longer than the upper length defined in RFC 5321 of 998 bytes. As far as I can see PHPMailer tries to handle the matter (I didn't delve deep enough into the OJS source, to decide if the corresponding function is called by OJS), but fails; according to it's [changelog](https://github.com/PHPMailer/PHPMailer/blob/master/changelog.md) versions 6.0.2 and 5.2.16 both added fixes for bugs around this issue.

**Comment by asmecher** [comment]
There's a quick work-around for this that has already been committed to the master branch (https://github.com/pkp/pkp-lib/issues/3338) but as with #3392 I'll look into upgrading the library.
