### ISSUE TITLE
Consider renaming Submission List "Archives" to "Archived"

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3396]
Minor detail, but there can be confusion between the use of "Archives" to describe two different parts of OJS - 1) the back issues and 2) the rejected or published submission records.

We could make a bit of a distinction by changing the rejected or published submissions from "Archives" to "Archived".

**Comment by NateWr** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/8429
- https://github.com/pkp/ojs/pull/3619
- https://github.com/pkp/ops/pull/391

Tests only:
- https://github.com/pkp/omp/pull/1248

**Comment by NateWr** [comment]
Merged to `main`.
