### ISSUE TITLE
Add filter see submissions completed in date range

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3397]
Another UI/UX suggestion:

As a chief editor, I want to be able to see at a glace when submissions were originally made to ensure none are languishing in the workflow.

To do this, could we consider adding original submission date to the submission list entries? I know we want to keep this interface as clean as possible, but it would be invaluable for chief editors wanting to know at a glance if anything is languishing -- especially for journals with long submission lists.

Could this also be a filter choice -- e.g., More than 6 months; More than 12 months

**Comment by NateWr** [comment]
I believe that the user's aim (to track submissions languishing in the workflow) is supported by the last activity filter added in #4168.
