### ISSUE TITLE
Section Editor assignment creates duplicate Pre-Review Discussion entries

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3398]
When I add a section editor to the participants list, the Editorial Assignment pre-review discussion entry appears twice.

See: http://vpstest2.lib.sfu.ca/index.php/publicknowledge/workflow/index/64/1

**Comment by asmecher** [comment]
@stranack, that's currently by design. Would you expect a new recipient to be added to the existing discussion? I could foresee trouble if we assume that new assignments should be granted access to already-in-process discussions.

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/3434
https://github.com/pkp/ojs/pull/1859 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look at the pkp-lib PR above?

**Comment by stranack** [comment]
I just noticed this happening in other stage discussions too, just in case the fix needs to be applied elsewhere.

**Comment by bozana** [comment]
This should fix it all... :-)
