### ISSUE TITLE
[OJS] Articles from journals not intented for public display appear in search and browse author/title list

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#340]
Hi!

First, thank you for all your work on OJS!

I'm not sure, but we have encountered what I think is a bug in OJS. Article/author results from journals that are not enabled to "appear publicly on the site" still show up in search results as well as the the browse title/author lists. This has been causing indexing problems for our installation, with search engine crawlers being able to find articles that are not intended for public display.

If the setting "Enable this journal to appear publicly on the site" should toggle journals' display on the main page, content from those journals should really not show up in search/browse either.

OJS version: 2.4.2.0.

Best regards,
Martin Persson, Lund University Library, Sweden

**Comment by asmecher** [comment]
Thanks for reporting, Martin; this is an easy fix. Apply the patch at https://github.com/pkp/ojs/commit/373988c9600719f250a639ad98b8a3f1ed4f49d5.diff to your installation.

**Comment by martinpub** [comment]
Great, thank you!

**Comment by martinpub** [comment]
Hi again! After having upgraded to 2.4.6 on a test server (I can verify that our files have the code as shown in the commits above), we are still having the same problem. Articles/authors from journals that have enabled set to 0 are still showing up in site-wide search/browse results. This seems strange?

**Comment by asmecher** [comment]
@martinpub, can you try flushing your data cache first?

**Comment by martinpub** [comment]
@asmecher Oh yes, of course, didn't think of that. However, after having flushed cache through "Clear Data Caches" in the site admin interface, I still get hits on disabled journal content.

**Comment by asmecher** [comment]
Hmm, very strange. What is the URL to the page you're seeing this on? (I just need the parts after the index.php part of the URL.)

**Comment by martinpub** [comment]
/index/search/search.

(/index/search/titles and /index/search/authors seem to view proper results.)

**Comment by martinpub** [comment]
I don't know if this is related but I found an archived (not public) submission in /index/search/search as well as [journal-abbr]/search/search. Thanks for checking on this, I'll be happy to follow your instructions for further troubleshooting.

**Comment by asmecher** [comment]
@martinpub, I've created a new issue for this in order to avoid splitting the resolution between two versions of OJS. See: https://github.com/pkp/pkp-lib/issues/482
