### ISSUE TITLE
[OJS] changing citationStyleLanguage settings does not work

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3400]
Hi,

OJS 3.1.0.1. and the same release for the citationStyleLanguage plugin + the ojs default theme for 3.1.0.1.

I select APA as the primary style and select APA and Chicago from the alternatives list and hit save. if I now return to the settings form, the selections I made are not there anymore. The selections I made are saved to the database. 

There are settings for `primaryCitationStyle`, `enabledCitationStyles` and `enabledCitationDownloads` in the database and on the abstract page the correct alternatives are selected.

**Comment by asmecher** [comment]
@ajnyga, I couldn't duplicate this using a `master` install. Do you have one available to test on?

**Comment by ajnyga** [comment]
Thanks, this is happening in our production server which is unmodified 3.1.0.1. I will see if I can replicate the problem in our test server and if I can, I will send you the login information by email.

**Comment by Ph-We** [comment]
This has already been reported: 
https://github.com/pkp/pkp-lib/issues/3222

**Comment by asmecher** [comment]
Thanks, @Ph-We, that does indeed look like a duplicate.
