### ISSUE TITLE
[OJS] doubt about a translation

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3407]
Hi all,
in lib/pkp/locale/en_US/common.xml, there is a message which is :
"<message key="notification.email">Do not send me an email for these types of notifications.</message>"
this message is translated in most of other languages as "Send me an email ..."

What is the good sens for this message ?
Thank you

**Comment by mtub** [comment]
The English text is correct, the translations hadn't been updated. 

(The English text had been changed to its opposite meaning some time ago. This will be avoided in the future.)
