### ISSUE TITLE
[OJS] translate is not working with checklist Submission Requirements

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3409]
When you are submitting an article, and it shows the checklist of Submission Requirements, this list only is displaying just in English! even when you have activated before all options for the new language. 

this checklist is in this file (ojs/locale/xx_XX/default.xml) 

I tried with Spanish and Francaise translations.
I make a video for you: https://youtu.be/t_MpQNVZa1w

Would wonderful this issue can solve before OJS 3.1.1  (of course if this really is an issue)

**Comment by bozana** [comment]
@t4x0n, do you think it could be similar to the problem i.e. solution here: https://github.com/pkp/pkp-lib/issues/3156 i.e. if it is solved with the reload of the default localized context settings at locale reload?

**Comment by t4x0n** [comment]
maybe @bozana, but it's not possible for me to know until an update to the next version OJS 3.1.1

**Comment by bozana** [comment]
@t4x0n, I think this is related to the issue above, so I will close this issue for now. Please, feel free to reopen it, if it still does not work for you after you have upgraded to OJS 3.1.1 and used "Reload defaults" for those wished languages...
