### ISSUE TITLE
[OCS]  unable to login and create conference after installation. No errors only error.log

### ISSUE THREAD

**Issue by ststamil35** [pkp/pkp-lib#3410]
I am unable to login after OCS installation.

Error log shows the following error

[21-Feb-2018 11:35:42 Etc/GMT] ocs2 has produced an error
  Message: WARNING: Invalid argument supplied for foreach()
  In file: /home/psgimsbz/public_html/conference/classes/install/Install.inc.php
  At line: 117
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
[21-Feb-2018 11:35:42 Etc/GMT] ocs2 has produced an error
  Message: WARNING: Invalid argument supplied for foreach()
  In file: /home/psgimsbz/public_html/conference/classes/install/Install.inc.php
  At line: 117
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'a' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'em' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'strong' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'cite' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'code' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'ul' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'ol' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'li' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'dl' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'dt' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'dd' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'b' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'i' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'u' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'sup' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'sub' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'br' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log
[21-Feb-2018 11:35:49 Etc/GMT] ocs2 has produced an error
  Message: USER WARNING: Attribute '' in element 'p' not supported (for information on implementing this, see the support forums) 
  In file: /home/psgimsbz/public_html/conference/lib/pkp/lib/htmlpurifier/library/HTMLPurifier/HTMLDefinition.php
  At line: 324
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.31
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.6.36-82.0-log

It is working good in local(xampp). Server also have PHP5.6, Apache2, All PHP Extension. So I planned to ask server team about issue. Before I ask , I should know what kind of question I am going to asking for (like OCS needs few PHP extensions, so please add few php extension....). Why this is happening? Please give your suggestions......

**Comment by asmecher** [comment]
@ststamil35, the support forum is the best place to get general support -- could you post your question there? http://forum.pkp.sfu.ca/
