### ISSUE TITLE
getTemplateResourceName for plugins in pkp-lib

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3415]
s. https://github.com/pkp/pkp-lib/commit/619f4018a33ca2f6e328351282f28342c2439551#r27345626

**Comment by asmecher** [comment]
@NateWr, I think this is yours too?

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/3450

OMP PR for tests and removes what seems to be an unnecessary template:
https://github.com/pkp/omp/pull/509

**Comment by NateWr** [comment]
@bozana would you code review?

**Comment by bozana** [comment]
Great! Thanks a lot!!!
