### ISSUE TITLE
[OMP] Don't appears the download button to see the file .

### ISSUE THREAD

**Issue by alienmau** [pkp/pkp-lib#3417]
I need some assitance, im usind OMP v3.1.0 , and when i publish a press why appears "array" insted of the button to see the file or download?? any idea.
Here is a screenshot 
http://prntscr.com/iiih00

Any help i'll appreciate!!

**Comment by asmecher** [comment]
@alienmau, start out by searching our support forum (http://forum.pkp.sfu.ca/), and if you can't find the answer there, post a new topic with all the details.
