### ISSUE TITLE
Expose reviewer competing interests to editors during reviewer selection

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3418]
The reviewer's competing interests (if any) are not currently exposed to the reviewer selection process.

**Comment by asmecher** [comment]
@NateWr, assigning this to you, but it might make a good case for a walk-through for the rest of the team on working with the Vue toolset.

**Comment by NateWr** [comment]
My understanding is that competing interests are only entered when a reviewer selects a review assignment. I looked in the user profile area and couldn't see any area to input competing interests outside of a review assignment. Am I missing something?

**Comment by asmecher** [comment]
Ah, this clears up my misunderstanding.

We currently have two roles for competing interests declarations:
- When an author submits a submission, they can declare one
- When a reviewer accepts a review, they can declare one

I had thought that we supported another option: a reviewer could declare one in their user account, and the editor could see it during the reviewer selection process. We don't currently support that (and never have). I'll get back to the user who asked me about this, and if they have a need for the third option, we can perhaps file it as a feature request.

**Comment by bozana** [comment]
Are here maybe reviewing interests instead of competing interests meant?

**Comment by NateWr** [comment]
Reviewer interests are displayed during reviewer selection now.

**Comment by bozana** [comment]
As, sorry... yes... cool... then all alright... :+1:
