### ISSUE TITLE
OJS 3.1.0.1 "All reviews are in" notifications are not being sent anymore

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3423]
Hi,

@NateWr @asmecher 

One of our journal editors noticed that the "All reviews are in" notifications are not being sent in OJS 3.1.0.1.

The translation key for the notification is still here https://github.com/pkp/pkp-lib/blob/master/locale/en_US/common.xml#L547 but it seems that it is not being used? At least a search in gihthub with that key does not return any hits in php code.

Am I missing something here?

edit: seems that it was removed here https://github.com/pkp/pkp-lib/commit/f1a8b6c37eb2ee4f2d2cdaaaae052155f972c48a#diff-99cceb4bb3d30eb1895df2065f48ea52
There are a lot of changes there so should there be a replacing notification?

**Comment by asmecher** [comment]
@NateWr, that was removed in pkp/pkp-lib#2163 (https://github.com/pkp/pkp-lib/commit/f1a8b6c37eb2ee4f2d2cdaaaae052155f972c48a#diff-02c922ab8e8457421100758ec2d8b856L82) -- do you remember that detail?

**Comment by forgive38** [comment]
Hi,
It could be great if this behavior could re-run in ojs-stable. One of our editors asks for that too.
Thank you

**Comment by bozana** [comment]
I think this changed when the review round status was introduced -- so that there are no notifications but the current review round status will always be displayed. Thus, for example, now there is the "New reviews have been submitted." when there is one or more unread reviews.
So maybe the question is also, why is the old "All reviews are in" needed i.e. why the current one "New reviews have been submitted." is not enough?

**Comment by ajnyga** [comment]
If I understood correctly, the editor did not receive any notifications concerning the reviews. But I have to check.

**Comment by bozana** [comment]
Yes that could be -- I think there are no e-mail notifications since then -- so an e-mail notification is wished?

**Comment by ajnyga** [comment]
Yes, that was the original point here, but I realize I did not mention this properly in the first message. The editor thought that it takes a lot of time to go to OJS and check for the new reviews, compared to emails. It would be great to have an opt-out as well.

**Comment by bozana** [comment]
Hmmm.... If I understand it correctly from this code: https://github.com/pkp/pkp-lib/blob/ojs-3_1_0-1/classes/submission/reviewer/form/ReviewerReviewStep3Form.inc.php#L199-L212, there should be an e-mail notification also for the assigned editors, that a review has been done (`<message key="notification.type.reviewerComment">A reviewer has commented on "{$title}".</message>`).
Does this notification work? And is this notification enough? Or is something else needed/wished?
Sorry for asking so much :-\ -- Just to better know the problem i.e. what would be the right solution... :-)

**Comment by forgive38** [comment]
Yes, the notification  "reviewer has commented on "{$title}" works . But only by mail : not a task.
Before, if I remember, was a notification task with "All reviews are in and a decision is needed"
One editor asks me to have this notification, but maybe "reviewer has commented" is enough and it solves, in a certain sens, this question: 
https://forum.pkp.sfu.ca/t/ojs-3-proposition-to-change-a-reviewround-status-name/38556

**Comment by bozana** [comment]
Yes, I think this is true: earlier there was a task notification, now there is no task notification. 

@ajnyga and @forgive38, is then the current situation (that e-mail notification above and the review round status display on the dashboard and review page) enough? 

@forgive38, yes, then it would in a certain sense solve that question in the forum... Thanks for pointing at it!

**Comment by ajnyga** [comment]
I think that in our case the email was exactly what was requested. I just have not reached the editor again to ask for details. Originally I thought that she meant that there are no email notifications concerning reviews, but maybe there are but just the "all are in" is missing now (as it was planned).

**Comment by ajnyga** [comment]
So @NateWr if this is the reason for original issue, then I guess this could be easily fixed and closed. Unless there was something else in this thread that was about a different issue?

**Comment by NateWr** [comment]
I think @bozana took a closer look at this than me and she has a better sense of what needs to be done for this issue.

**Comment by ajnyga** [comment]
Ok sure, I think it is a fairly clear bug, I will add a pr here for you to review.

**Comment by ajnyga** [comment]
pr: https://github.com/pkp/pkp-lib/pull/3553

**Comment by bozana** [comment]
Yes, the PR from @ajnyga, solves the bug, but the task notification is still to be made, as wished by @forgive38. I wanted to check with others in the team when in general we create those task notifications... then that fix will come too...

**Comment by aguen** [comment]
If I understand the current discussion correctly, the original issue 

"All reviews are in" notifications are not being sent anymore

was replaced by 

"reviewer has commented on "{$title}" notifications/emails are not being sent"

However, there is a need (there are requests) for an "**All reviews** are in" email notification. (Section) Editors want to be alerted as soon as *all* reviews are available and they have to come to an editor decision. Thus, sending an "All reviews are in notification" should still be an issue.

**Comment by NateWr** [comment]
Thanks @aguen. From what I can tell, the bug with the "reviewer has commented" emails was fixed at https://github.com/pkp/pkp-lib/issues/3423#issuecomment-378951612. This issue remains open in order to reintroduce the "all reviews are in" email.

**Comment by NateWr** [comment]
Closing this in favor of https://github.com/pkp/pkp-lib/issues/4976.
