### ISSUE TITLE
ReCAPTCHA broken in OJS 2.4.8-3

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#3425]
The implementation of ReCAPTCHA in OJS 2.4.8-3 does not work for ReCAPTCHA v2 and notification list subscriptions.  It also breaks legacy ReCAPTCHA (though Google will shutdown v1 on March 1, 2018).

**Comment by asmecher** [comment]
Thanks, I've merged this and cherry-picked to `ojs-stable-2-4_8` (and removed an accidental editor swap file add).

**Comment by semteacher** [comment]
Have issue with this update:
1) got PHP Fatal error: Call to undefined function recaptcha_versioned_get_html()
2) in some reason submodule changes (https://github.com/pkp/pkp-lib/compare/6deab6e944111df58bafb75c8635e1272491bae4...98b92146a5d98c276ecf2a49db9633690d3a866b) have not being installed

**Comment by asmecher** [comment]
@semteacher, how did you apply the changes?

**Comment by semteacher** [comment]
I have merged ojs-stable-2-4-8 into my branch. And updated sub-modules as well

**Comment by semteacher** [comment]
I am sorry, I was wrong. Problem is solved.
I have not forced to switch to 2_4_8 in submodule on prod 
reCaptcha is working now.
Sorry that disturb you
