### ISSUE TITLE
browseBySection

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3429]
The plugin https://github.com/pkp/browseBySection uses functions that will be first available in OJS 3.1.1, so maybe to write it in the readme. Plus, maybe to write how the plugin is supposed to work -- for example I had to read the code to figure out what to do next when I have enabled the plugin. And I still do not know why I do not see the browsing possibility...
There is interest in the plugin, s. https://forum.pkp.sfu.ca/t/browse-articles-by-section-or-section-page-detail/38224/5

**Comment by asmecher** [comment]
Assigning to @NateWr. Strictly speaking this isn't a show-stopper for OJS 3.1.1 because the plugin will be distributed in the Plugin Gallery and can be released/tweaked afterwards.

**Comment by NateWr** [comment]
Yeah sorry it was very bare bones because we were rushing to get it working in time for a PS journal release last year. I'll try to document a bit better.

**Comment by NateWr** [comment]
Addressed in https://github.com/pkp/browseBySection/commit/1cfe1f20e8c085ff29716296d60b5a7d26eb6f2c

Can you take a look @bozana and see if you can get it working with the Usage instructions?

**Comment by bozana** [comment]
Cool @NateWr ! Everything perfect! :-)
