### ISSUE TITLE
[OJS] issues with emails notifications during the review to the production process

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#3431]
It is necessary to review the emails that can be sent as notifications to the different participants during the process, for example:
- To the author can be sent the same notifications as the editors, for example: Editorial Assignment, Copyediting Request, or others related to the Production process. 
- The Editorial Assignment notification appears in Submission tab and Review tab, but also this appears again on the Production tab, I think this is a mistake right? (because this is for assign editor for the process and then he or she assign reviewers)
- Al the Production tab: two notifications appears without name and without content (see the picture).
![image](https://user-images.githubusercontent.com/5422984/36770184-b9a04f38-1c27-11e8-89a9-7735d7a4aeea.png)

I hope this serves to continue with the improvements to the system. Ans I have OJS 3.1.0.1

Greetings.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still impacting a recent release, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
