### ISSUE TITLE
Empty discussion created when going back in the browser while viewing the modal "Add discussion"

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3432]
This issue is different from #3167, because the query is created before showing the form, and no delete request is sent.

Same thing when you upload a file or when you add a message in a discussion.
Thank you

**Comment by NateWr** [comment]
@forgive38 we're cleaning up old issues. Are you still able to reproduce this on the most recent 3.3.x stable build? If so, please provide some reproduction steps in the following format:

```
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

I'll close this for now but will reopen if you can provide reproduction steps in a stable version.
