### ISSUE TITLE
Adding a warning concerning misplaced files directory would save a lot of time

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3435]
I think this could be easily checked and a warning could be shown to the OJS admin with a link leading to instructions. Having this would save a lot of time for other topics in the forum.

**Comment by ajnyga** [comment]
For older installation we could use this: https://github.com/pkp/ojs/blob/ojs-stable-3_1_0/pages/management/SettingsHandler.inc.php#L84-L98
And for new installations this could also be checked when installing.

**Comment by asmecher** [comment]
How would we check for a misplaced files directory? Protecting a `files_dir` in the web root is a legit approach, especially for hosts that might not offer space outside the web space or might protect them from PHP access. We could suppress the warning if there's a `.htaccess`, but that would exclude `httpd.conf`-based protections, and the `.htaccess` might not be configured correctly. We could make the warning suppressible, I suppose.

**Comment by ajnyga** [comment]
Hi,

For checking the directory you could maybe do a compare between
`realpath(Config::getVar('files', 'files_dir'))` and `realpath($_SERVER["DOCUMENT_ROOT"])`.
If you find the whole document_root string inside the given files_dir path, then it is a folder in the webroot: `if (stristr(realpath(Config::getVar('files', 'files_dir')), realpath($_SERVER["DOCUMENT_ROOT"])))`

But I did not think of using htaccess. Checking for an htaccess file is a bad idea as you said, because it gives the user a false sense of security if the rules in the file do not actually work.

So maybe just check for the location of the files directory and give the admin the possibility to suppress the notification. There should also be a link to detailed instructions on how to a) move the files dir or b) protect it with htaccess/httpd.conf.

**Comment by asmecher** [comment]
Another option would be to try fetching a document placed inside the files directory. But my overall opinion on this is that our installation form and documentation are clear, and we don't have a huge obligation to someone who isn't reading them. It's entirely possible I'm grumpy about this subject.

**Comment by ajnyga** [comment]
I agree that people should read documentation. So I am not thinking that you are obliged to add this, just that it would most likely save you a lot of time. But it is really your call. I know how to keep our installations save without it as well.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider opening a [discussion](https://github.com/pkp/pkp-lib/discussions) on this topic.
