### ISSUE TITLE
"Send to Review" and "Send to Production" for reccomendOnly users

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3436]
The recommendOnly option first came in connection with the review stage i.e. not to allow some users to make the review decisions, but to just be able to make a recommendation.
Then the problem was that there were "Accept and skip review" and "Decline Submission" buttons that should not be available for recommendOnly users. So I wrongly disabled all the buttons, from all other workflow stages (other than review stage) for recommendOnly users. This way also the "Send to Review" button/action is not active for recommendOnly users.
It is wished that the "Sent to Review" button/action is available for recommendOnly users, s. https://github.com/pkp/pkp-lib/issues/3073#issuecomment-354000800.
This makes sense, I think, because those users are in a way responsible for the review and will at the end make their recommendations on it. Thus I will change that -- so that recommendOnly users also see "Send to Review" button. 
Also, according to the original issue https://github.com/pkp/pkp-lib/issues/2433, the recommendOnly option should apply only to the review stage, thus I will now also enable other buttons, i.e. "Send to Production" from editorial workflow stage.

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/3437
https://github.com/pkp/ojs/pull/1860
https://github.com/pkp/omp/pull/508

**Comment by bozana** [comment]
@asmecher, could you please take a look at the PRs above?

**Comment by bozana** [comment]
@jmacgreg, just to be sure: we wanted the recommendOnly editors to only recommend for the review decisions, but for all other workflow stages they would have normal buttons, right? -- For example the button "Send to Review" and "Send to Production" should be available also for the recommendOnly editors, correct?

**Comment by jmacgreg** [comment]
Hi @bozana I think that sounds fine!

**Comment by t4x0n** [comment]
@bozana @jmacgreg for me, send to production is not a task for recommendOnly editors, because they will be able only for send recommendations, like recommend Accept o recommend Reject a submission... thus, send to production seems even more permissive than Accept so it sounds confusing to me...

**Comment by asmecher** [comment]
@bozana, as for the code, just a minor suggestion -- the same needs to be applied to the OMP PR as well.

**Comment by bozana** [comment]
Hmmm... @t4x0n, I mean the button on the copyediting stage. Would you rather not provide that button for a recommendOnly editor?
I am also a little bit confused with all this roles and this recommendOnly option :-\
Theoretically you can create a new role with the permission level "Section Editor" + recommendOnly option, and chose that this role has only access to Submission and Review stage. Would that maybe solve that problem? 
Or, would you like recommednOnly editor to have access to the copyediting stage but cannot use that button "Send to Production"? What would be the benefit of that?
Somehow I also do not see the benefit of having a button "Recommend to Send to Production" on the copyediting stage for the recommendOnly editors.
Hmmm...

**Comment by t4x0n** [comment]
sorry @bozana, I think I understand now... permissions levels solve my confusion!!  You are right!
