### ISSUE TITLE
Update to ALM plugin

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#344]
From Bugzilla: http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8955

**Comment by asmecher** [comment]
@bozana, I suppose this is as good a home as any for the ImpactStory work.

**Comment by bozana** [comment]
The new version of the ALM plugin, for the OJS 3.1.1-4 can be found here: https://github.com/bozana/ALM/tree/ojs3

**Comment by bozana** [comment]
I think this issue is not relevant any more, now that we have the paperbuzz plugin? @asmecher, @NateWr, @jmacgreg?

**Comment by asmecher** [comment]
Agreed, thanks.
