### ISSUE TITLE
Duplicate translation keys in en_US

### ISSUE THREAD

**Issue by tgc** [pkp/pkp-lib#3443]
While developing a tool to do consistency checks on the danish translation I noticed that en_US locale files have several duplicated keys.
The tool is located here: https://github.com/tgc/ojstools
Running the tool with -u -l en_US parameters against a checkout of the master branch gives me this report:

`DUPLICATE: editor.notifyUsers.allUsers in ./locale/en_US/editor.xml`
`        <message key="editor.notifyUsers.allUsers">All users associated with this journal ({$count} users)</message>`
`        <message key="editor.notifyUsers.allUsers">Send this message to all users associated with this journal ({$count} users)</message>`
`DUPLICATE: notification.type.editorDecisionSendToProduction in ./lib/pkp/locale/en_US/submission.xml`
`        <message key="notification.type.editorDecisionSendToProduction">Production process started.</message>`
`        <message key="notification.type.editorDecisionSendToProduction">Production process started.</message>`
`DUPLICATE: submission.event.fileUploaded in ./lib/pkp/locale/en_US/submission.xml`
`        <message key="submission.event.fileUploaded">File "{$name}" (file ID {$fileId}-{$fileRevision}) was uploaded.</message>`
`        <message key="submission.event.fileUploaded">A file "{$originalFileName}" was uploaded for submission {$submissionId} by {$username}.</message>`
`DUPLICATE: grid.action.restoreDefaults in ./lib/pkp/locale/en_US/grid.xml`
`        <message key="grid.action.restoreDefaults">Restore Defaults</message>`
`        <message key="grid.action.restoreDefaults">Restore defaults</message>`

The tool also tells me that one or more of these are propagated into other translations, some even including indiviual translation of the diverging texts that two of the duplicates have.

**Comment by asmecher** [comment]
Confirmed and fixed, thanks!
