### ISSUE TITLE
Multilingual custom email template does not apply to email body

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3444]
In OJS 3.1.0 if a JE creates a custom email template in two languages (e.g. English and French), the custom email template appears in the email template select menu when e.g. assigning an Editor to a submission. However selecting the custom email template does not pre-populate the email body with the template text.

**Comment by bozana** [comment]
Hi @mfelczak, I cannot reproduce it at my local installations, neither using the current ojs-stable-3_1_0 branch nor master. 
Is that 3.1.0.0?

**Comment by mfelczak** [comment]
Hi @bozana, yes this was for a 3.1.0.0 install -- I'll upgrade it to 3.1.0-1 and confirm whether that resolves the issue.

**Comment by bozana** [comment]
Great! Thanks a lot!

**Comment by mfelczak** [comment]
Hi @bozana, we've upgraded the install to 3.1.0-1 and can confirm that the problem still persists. I'll email you the login details if you'd like to review the install.

**Comment by bozana** [comment]
Ah, I've figured it out @mfelczak: it is because of the variables that cannot be replaced: $editorialContactName, $submissionUrl and $editorUsername. They are assigned here: https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php#L242-L261, but only for those specific e-mail templates. I.e. the custom templates are not considered.

Thus, we would need a general solution/concept for the variables in the custom e-mail templates.
@asmecher and @defstat, are there any considerations so far?

THANKS!

**Comment by asmecher** [comment]
@bozana, I'm afraid I'm not following -- how is this affecting email template selection?

**Comment by bozana** [comment]
The e-mail template can be selected it is just that its body part is not displayed in the tinyMCE field. It is only not displayed when the variables cannot be replaced.

**Comment by asmecher** [comment]
Is it due to a JS or PHP error or something? Still not sure where this would be broken.

**Comment by bozana** [comment]
It is because of this code line: https://github.com/pkp/pkp-lib/blob/master/js/controllers/grid/users/stageParticipant/form/StageParticipantNotifyHandler.js#L121
Thus, maybe to just check if there are any variables before executing it? 
This would lead that the variables are displayed as such...

**Comment by bozana** [comment]
Yes, this could be maybe a solution: to display the variables as variables, then the user can edit them?
But maybe there could be another solution, something like having a pool of variables user can use for custom e-mail templates and that would be replaced appropriately?

**Comment by bozana** [comment]
For now, I can add an if statement in that JS code line, if jsonDataContent.variables exist, then use that code line... ?

**Comment by asmecher** [comment]
The quickest solution would be to have the variables presented as they are. I suspect it would be pretty quick/easy to get the custom TinyMCE PKP tags plugin (`plugins/generic/tinymce/plugins/pkpTags`) to format them nicely, though we'd need to sure there was a cue to the user that we don't have a value for them.

**Comment by bozana** [comment]
Hmmm... If OK I will then just fix that code line above, add the check and then later we can see... -- I would need to take a look at those pkpTags...

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_0_1: https://github.com/pkp/pkp-lib/pull/3470
ojs ojs-stable-3_1_0: https://github.com/pkp/ojs/pull/1873 (only submodule update)

pkp-lib master: https://github.com/pkp/pkp-lib/pull/3471
ojs master: https://github.com/pkp/ojs/pull/1874 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look?

**Comment by asmecher** [comment]
Looks good, @bozana -- please go ahead.
