### ISSUE TITLE
OJS Registering in multisite installations: "select all" option to journal roles

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3446]
We have had a request that would it be possible to get an email notification every time a journal in our whole installation publishes something.

This is of course possible, if you register as a reader to all the journals. But when you actually register, it is very unpleasant when you have to select the reader role from over 50 journals visible in the form. 

So maybe a "select all" option for the site-level registration form? You could just add an extra row before the first journal and name that "Register to all journals as".

**Comment by NateWr** [comment]
I'm going to close this as a low priority. If this is a request from an admin or site-wide editorial assistant, I'd recommend a site-level plugin to do this. If it is an ordinary user, it's probably not high enough priority for us to work on it. But a large site could implement something through a custom theme/plugin.
