### ISSUE TITLE
Task list shows too long

### ISSUE THREAD

**Issue by rcgillis** [pkp/pkp-lib#3447]
Have encountered an issue when a user has too many tasks in their task queue, it does not provide them an option to mark as read (which would lessen the task list), rendering the task list essentially useless. It also doesn't appear to be showing the correct number of tasks in the queue. Contact me outside of Github issues and I can show you an example of where this is occurring.

**Comment by forgive38** [comment]
Maybe you can change the number of items in lists in settings > website

**Comment by rcgillis** [comment]
Thanks, but no - I checked and there doesn't appear be an option for this.

**Comment by forgive38** [comment]
With ojs stable 3.1.0, I have this option at the end of tab 'Appearance'  in Website > Settings

"Lists
Limit the number of items (for example, submissions, users, or editing assignments) to show in a list before showing subsequent items in another page. Also, limit the number of links to display to subsequent pages of the list."

If I put 5 for number of list items, I have only 5 tasks displayed with a pager.

**Comment by rcgillis** [comment]
Thank you, Simon. But that's not what I'm referring to.  I'm referring to the "Tasks" queue at the top of the page.The list settings have no impact on that. If one of the pkp devs chime in, I can show them an example of a journal where its occurring.

**Comment by NateWr** [comment]
@rcgillis Am I right in thinking it's just a matter of the task list going too far, so that the buttons at the bottom are off the screen, and you can't scroll to them? Does it look like this?

![selection_076](https://user-images.githubusercontent.com/2306629/37036475-b4308ba6-2147-11e8-85d5-68b280a7b912.png)

If so I can take a look at that.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/3454

Tests:
https://github.com/pkp/ojs/pull/1866

**Comment by NateWr** [comment]
Tests passed. @asmecher can you code review?

**Comment by asmecher** [comment]
Looks good, @NateWr, please go ahead!

**Comment by mfelczak** [comment]
@NateWr: would it be possible to please also backport this to ojs-stable-3_1_0 ?

**Comment by NateWr** [comment]
@mfelczak I've merged this commit with `ojs-stable-3_1_0` now. :+1:

**Comment by mfelczak** [comment]
Thanks @NateWr!
