### ISSUE TITLE
[OJS] Submission listings only show title for selected locale

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3448]
Tagging @NateWr 

OJS 3.1.0.1 Two languages active in a journal, primary language Finnish and secondary English. All boxes are ticked for both.

Editor adds a new submission and selects English as the submission language.
If Finnish UI is selected, the editor can not see the English title of the submission in the submission listings. By switching the UI to English, the title appears.

(In overall I think (and I hope that you do not take this the wrong way) that there has been fairly many bugs in OJS related to multilingual data. I think that this is something that needs more attention in testing in the future because there are a lot of multilingual journals using OJS)

**Comment by NateWr** [comment]
The current behaviour is defined here: https://github.com/pkp/ui-library/blob/master/src/mixins/global.js#L47-L77

> It will search for the current locale value. If there's no value for the
> current locale, it will revert to the primary locale. If there's still
> no match, it will return an empty string.

I'm pretty sure this is how we do the localisation consistently throughout the system, including the PHP-based translations, as well as the `getLocalized*()` methods. I'm open to reconsidering how the `__()` function works or the localized data methods, but I want to keep the JS and PHP implementations consistent.

**Comment by bozana** [comment]
Submissions data has a slightly different "getLocalized" approach, I think: instead of journal primary locale the submission locale is required/considered...

**Comment by ajnyga** [comment]
That looks a lot different from this: https://github.com/pkp/pkp-lib/blob/master/classes/submission/Submission.inc.php#L140-L160

**Comment by NateWr** [comment]
You're right! Thanks both. I'll write an additional mix-in for the submission list components to localize submission data specially.

Know of any other objects with special localization rules?

**Comment by ajnyga** [comment]
I think that everything else should fall back to primary locale, but @bozana definitely has a better overall idea.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ui-library/pull/12
https://github.com/pkp/pkp-lib/pull/3453
https://github.com/pkp/ojs/pull/1865

@ajnyga this fixes the specific localization error. It also fixes the general localize method used in the new Vue.js components. They were treating empty strings as completed translations, so the usual fallback from current locale to primary locale to anything wasn't working properly. This may address some of the translation issues you've encountered.

I do run a multi-language journal in my local install, but my local dataset is so much noise it's common for me to not notice when a value is printed that shouldn't be, or vice-versa. If you could come up with some integration tests that would spot these kinds of errors that'd be really great. It probably is an area where our automated testing could do more.

**Comment by ajnyga** [comment]
Any chance to get this to 3.1.0.1 stable?

**Comment by NateWr** [comment]
Tests passed. @asmecher can you code review?

@ajnyga I'll prepare some PRs for 3.1.0-1.

**Comment by ajnyga** [comment]
Great thanks!

**Comment by asmecher** [comment]
Thanks, @NateWr, please go ahead, though I'm still concerned that I'm not up to speed on the Vue components enough to review these properly -- not sure why I'm complaining to you about this :)

**Comment by NateWr** [comment]
All merged. :+1:

**Comment by bozana** [comment]
> Know of any other objects with special localization rules?

@NateWr, I just found one more place i.e. the localization for submission files: https://github.com/pkp/pkp-lib/blob/master/classes/submission/SubmissionFile.inc.php#L45.
Maybe it is not important for this issue, but just that you know... :-)

**Comment by NateWr** [comment]
Thanks @bozana, good to know!
