### ISSUE TITLE
Add support for SASS compilation

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3449]
Actually, as Bootstrap has switched to SCSS, I'm wondering if it makes sense to add the support for server-side compilation, just like for LESS. I will make a pull request with proposed changes. Although I'm missing there something because the code is not working as I planned. 
**edit**: after some refactoring seems to work fine.

**Comment by NateWr** [comment]
PR: https://github.com/pkp/pkp-lib/pull/3451

**Comment by Vitaliy-1** [comment]
From my point of view, apart from the commit, there is a need only to add the support for including extra SCSS files before compiling.

**Comment by NateWr** [comment]
@Vitaliy-1 I'm going to close this as outdated for now. But if you'd still like us to consider adding SASS support, can you create a [discussion](https://github.com/pkp/pkp-lib/discussions) for it?
