### ISSUE TITLE
[OJS] Open the Help menu in the settings to plugins

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3456]
I had a closer look into the _Help_ menu in the _Website Settings_. So right now on every tab of the _Website Settings_ in the upper right the _Help_ link provides the possibility to display basic help for the settings tabs. The content for this help provided from the `HelpHandler.inc.php` and is generated from Markdown files in `docs/manual/LOCALE/`.
The HelpHandler does not call any hooks, therefore plugins with a settings tab (like the Static Pages plugin and the plugin I am developing) are not able to provide additional help to the user of the plugin. I think the HelpPanel is a great way to provide additional information/help to the user, without cluttering the whole settings form. So I would propose to add the possibility to provide a file path to a markdown file so that plugins are able to have it's own help contents.
I may be able to provide a pull request for that.

**Comment by NateWr** [comment]
I like this idea. One thing to consider is that the in-app help guide is linked together as a book with a table of contents. If plugins are able to use the help panel, I'd like them to be able to open their own book or a single markdown file if desired.

This could significantly simplify some of the plugin settings modals.

**Comment by MarHerUMR** [comment]
The structure of the _HelpHandler_ makes it fairly easy to add additional help chapters to the end of the toc. I played around a bit and two presentation possibilities came to my mind. Either just appending the additional help chapters to the `<ul>` (keeping it in the toc structure) or add their own list under a section heading. 

![Possibility 1](https://user-images.githubusercontent.com/23074158/37158199-1d75d27a-22eb-11e8-945b-76f07c14d6c8.png)
![Possibility 2](https://user-images.githubusercontent.com/23074158/37158200-1d97860e-22eb-11e8-9b56-323a624a75a4.png)

**Comment by NateWr** [comment]
That looks great @MarHerUMR! I think I prefer the version with Plugins in it's own header. Do you have a PR or work-in-progress where we can see what you're doing with this?

**Comment by MarHerUMR** [comment]
Yeah, I just added the handling for the next/previous links. I think it is a little bit rough. But it's a start. I'll add a .zip with the changed HelpHandler and the customized staticPages plugin.
[help-work-in-progress.zip](https://github.com/pkp/pkp-lib/files/1819028/help-work-in-progress.zip)

**Comment by NateWr** [comment]
Thanks @MarHerUMR, would you be able to work these up as Pull Requests? It's easier for us to get a sense of what's changed, and how, when it's provided as a Pull Request.

**Comment by MarHerUMR** [comment]
Ok. Please ignore the first commit (ed5fd64).

**Comment by NateWr** [comment]
This looks nice @MarHerUMR, can you show me what a link to open a plugin help chapter looks like on the template side of things?

**Comment by MarHerUMR** [comment]
I'm not quite sure how to answer the question.

Do you want to know how the link in the table of contents looks like??

```
<h1>Summary</h1>

<ul>
<li><a href="en/README.md">Introduction</a></li>
[...]
<li><a href="en/administration.md">Administration</a></li>
</ul>

<h2>Plugins</h2>

<ul>
<li><a href="en/plugins/generic/staticPages/help/static-pages.md">Static Pages</a></li>
</ul>
```

I tried to make it so it matches the structure of the other help documents by adding the locale at the beginning. The path to the help file would be "/plugins/generic/staticPages/help/en/static-pages.md" for the static pages help file.

Hope this is what you wanted to know.

**Comment by NateWr** [comment]
I'm wondering about how you open the help page directly to a plugin's help page. For example, to open the submissions section from within OJS, you include a link like this:

```
<a href="#" class="requestHelpPanel" data-topic="submissions.md">Help</a>
```

That opens the help panel to the submissions page. What's it look like when you open to a plugin help menu?

Thanks for sharing the internal URL structure, too. I like it. I haven't had a chance to actually test this out myself yet, but it all looks very good. 

We're in the final stages of getting 3.1.1 ready for release. Would you be able to remind me about this in a couple weeks? I can then give it more of my attention and maybe convert a few of our plugins over to the system and get it merged in.

**Comment by MarHerUMR** [comment]
Ah, now I get it. I just added it like in the other plugin templates:

```
{* Help Link *}
{help file="plugins/generic/staticPages/help/static-pages.md" class="pkp_help_tab"}
```

I'll remind you about this, when the new version is released.

**Comment by NateWr** [comment]
Hi @MarHerUMR, just coming back to take a look at this now. Can you share some example code of how you've modified the Static Pages plugin to make it compatible with this PR? That will give me a trail to follow when trying it out with some of our plugins.

**Comment by MarHerUMR** [comment]
Sure. Did you have a look into the [file](https://github.com/pkp/pkp-lib/files/1819028/help-work-in-progress.zip) file I previously uploaded? It contains the customized static pages plugin.

If it would be easier for you I could provide a work in progress pull request.

**Comment by NateWr** [comment]
Just linking the PR to this issue so it can be found more easily: https://github.com/pkp/pkp-lib/pull/3496

**Comment by MarHerUMR** [comment]
I just added the pr #3605, but screwed up the linking of the commit to the issue.

**Comment by NateWr** [comment]
So is #3496 now obsolete? Should that PR be closed?

**Comment by NateWr** [comment]
Closing this as outdated. Please see further discussions about the in-app help in https://github.com/pkp/pkp-lib/issues/7089. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
