### ISSUE TITLE
sitemap fix

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3459]
Sitemap has to consider the new URLs...

s. https://forum.pkp.sfu.ca/t/error-in-sitemaps/38844/

**Comment by bozana** [comment]
Hmmm... Now that the nav menus are dynamic, the sitemap could always change. What does this mean?

**Comment by bozana** [comment]
@NateWr or @defstat, is it possible to have other navigation menus than 'primary' and 'user', e.g. in other themes?
Is there a possibility to differentiate between the user URLs that should not be considered in the sitemap and the others, public URLs that should be considered in the sitemap?
Could a solution be to only consider the 'primary' menu in the sitemap?

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1869

**Comment by bozana** [comment]
@NateWr, could you take a look at the PR above?

**Comment by NateWr** [comment]
@bozana I don't think the navigation menus should be considered at all for the sitemap. An individual menu is completely arbitrary. A theme may contain several menus, and they probably won't link to everything that should be included in a sitemap. They may also contain duplicates.

Instead, I think you'll need to provide a link to every Navigation Menu Item Type. This will also catch plugins which add menu item types (like browseBySection). And then add every issue/article to that as you've done.

**Comment by bozana** [comment]
Ah, yes, I see... OK, then I will not consider nav menus but everything they consider... right?

**Comment by NateWr** [comment]
:+1:

**Comment by bozana** [comment]
@NateWr, theoretically a plugin could add any kind of menu item type, also the one that should not go to the sitemap, correct? -- Thus, maybe I should provide a hook in the sitemap function, so that plugins can add URLs there if needed?

**Comment by NateWr** [comment]
Yeah, I can see two approaches. You could hook the [exclusions list](https://github.com/pkp/ojs/pull/1869/files#diff-010b63053d4fff74cd337439930fd590R128). Or, ideally, the whole XML output of the sitemap should be hooked if it individual nodes can be removed, so that a plugin can tailor that.

**Comment by bozana** [comment]
@NateWr, I pushed the new changes: I decoupled it form nav manu items -- I think it is not necessary? -- and provided a hook for the plugins. Then a plugin that would like to add an URL would do something like:

```
$doc = $args[0];
$rootNode = $args[1];
$urlNode =& XMLCustomWriter::createElement($doc, 'url');
XMLCustomWriter::createChildWithText($doc, $urlNode , htmlentities('loc'), 'here comes the actual url', false);
XMLCustomWriter::appendChild($rootNode, $urlNode);
```

OK so?

**Comment by NateWr** [comment]
That sounds good @bozana. I had one comment about announcements in the code and I've filed [an issue in the browseBySection plugin](https://github.com/pkp/browseBySection/issues/6) to add the URLs.

We'll also need to consider navigation menu items that use the Custom Page type. Each of these should be included. But I think otherwise we're good.

**Comment by bozana** [comment]
@NateWr, thanks a lot!

I see that those custom page menu items are visible/accessible also if they are not assigned to a menu area. Is this correct/meant to be so? -- I.e. I can then just search after those items with that type for that journal and consider them, right?

I will add the URLs for each announcement and I will add the URLs in the browseBySection plugin...

**Comment by NateWr** [comment]
Yeah, every custom menu item page should be included, regardless of whether it's added to a menu or not. I think the goal is for this feature to eventually replace the Static Pages plugin. :+1:

**Comment by bozana** [comment]
@NateWr, I added a new function to the NavigationMenuItemDAO, so that now there is also the pkp-lib PR. I also replaced the custom XML with standard DOM functionality. Would you like to take a new look?
#3463
pkp/ojs#1869

**Comment by NateWr** [comment]
Cool, just a few tiny comments. I checked the sitemap and it validated on a third-party service I found so all :+1: to merge if you want.

Related thought: should we provide a link and description of this sitemap under Settings > Distribution > Indexing? Something like:

> A XML sitemap is available for submitting to Google at [http://.../sitemap](x).

**Comment by bozana** [comment]
@NateWr, I considered all your comments: I fixed the functions parameters descriptions, added the sitemap information to the form page Settings > Distribution > Indexing, but I also introduced the sitemap for OMP, s. https://github.com/pkp/pkp-lib/issues/555, so I moved the shared code to the pkp-lib, and I removed the search/authors URL form the OJS sitemap.
Sorry that the new changes came again and again i.e. that I didn't consider everything at once -- first with your suggestion to have the information on the indexing setting page, I realized that the page is shared between OMP and OJS and that it would make more sense to introduce the sitemap in OMP (because this was already required) than to separate that setting page.
So could you please take another look at all the PRs (also the new OMP PR) above? THANKS!!!

**Comment by NateWr** [comment]
No worries about the fresh PRs! I did a review of all three and tested it out in OJS. Looks good! I just had a few comments but merge when you're ready.
