### ISSUE TITLE
Add DOI year cutoff OR Crossref XML year cutoff

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#346]
From Bugzilla: http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=6625

**Comment by jnugent** [comment]
I've adjusted the pull request and fixed up your comments, Alec.  Just re-assigning for review and/or merge.

**Comment by asmecher** [comment]
Back to you, Jason, per:
https://github.com/pkp/ojs/pull/425#issuecomment-76257815

**Comment by jnugent** [comment]
Fixed, and merged in.
