### ISSUE TITLE
Style the author browsing index

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3465]
There's an author index at `/search/authors`. I never knew this (:rofl:) and it hasn't been styled in any of the themes.

**Comment by NateWr** [comment]
We also need a navigation menu item type pointing to this page.

**Comment by asmecher** [comment]
It's essentially dead code -- the method it uses to disambiguate authors is particularly silly. Until we fix that, I wouldn't suggest spending much time on the layout or knitting it into navigation.

**Comment by bozana** [comment]
Hmmm... So maybe to exclude it from the sitemap as well?

**Comment by asmecher** [comment]
Yes, for now.
