### ISSUE TITLE
not approved files should be displayed on the article page

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3467]
This code line does not look if a file is viewable i.e. approved, so that those files that are not approved can still be accessed, if the terms (e.g. Open Access) is already set for them: https://github.com/pkp/omp/blob/master/pages/catalog/CatalogBookHandler.inc.php#L197. They are not displayed on the book view page, but if their URL is known, they can be downloaded.

NOTE: approvement is only an internal 'flag', so that it shouldn't  influence, both on the publication format and file level, the file download/viewability.

**Comment by bozana** [comment]
@asmecher, OK so?

**Comment by asmecher** [comment]
Let's talk about this during the meeting in a few minutes -- I think both approaches may be valid (either having approval affect ability to access the file, or having it stay irrelevant) but we'll need to be consistent between listing and allowing access.

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR now, after the change of the concept?

**Comment by asmecher** [comment]
This looks good, please go ahead!
