### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by cibita** [pkp/pkp-lib#3468]
when I try instal ojs this happens

Errors occurred during installation 
A database error has occurred: Access denied for user 'cibita'@'localhost' (using password: YES) 

I tried many times please, help

**Comment by asmecher** [comment]
@cibita, the best place to get support is our support forum, http://forum.pkp.sfu.ca/ -- please search there for answers to your question, and if you don't find it, post a new topic with all available details.
