### ISSUE TITLE
Restrict SubmissionFileRequestedRevisionRequiredPolicy to revision files only

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3474]
Currently the `SubmissionFileRequestedRevisionRequiredPolicy` does not check what kind of file it's being applied to in the review stage. The intent of the policy is to allow the author to revise anything they want, but without a check on the file stage, this can apply to review files outside of the revisions grid. Limit it to `SUBMISSION_FILE_REVIEW_REVISION` files only.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/3475

@bozana, could you take a quick look?

**Comment by bozana** [comment]
All well, good catch!

**Comment by asmecher** [comment]
Thanks! Also cherry-picked to `ojs-stable-3_1_0`.
