### ISSUE TITLE
Disabled themes remain on Appearance page when disabled

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3476]
When a theme is disabled on the plugin page, it continues to show up on the Appearance tab dropdown menu. Ideally, it should no longer appear there.

**Comment by Vitaliy-1** [comment]
We need simply put this line: https://github.com/pkp/pkp-lib/blob/master/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php#L110
into an `if` condition:
something like:
```
if ($themePlugin->getEnabled()) {
  $enabledThemes[basename($themePlugin->getPluginPath())] = $themePlugin->getDisplayName();
}
```

**Comment by asmecher** [comment]
That was quick! Thanks, @Vitaliy-1!
