### ISSUE TITLE
[OJS] PDF Viewer fullscreen toggle not working

### ISSUE THREAD

**Issue by michael-pkp** [pkp/pkp-lib#348]
pdfView.css is missing from ArticleHandler.inc.php

**Comment by asmecher** [comment]
Michael suggests:

ArticleHandler.inc.php:114
    + $templateMgr->addStyleSheet($request->getBaseUrl() . '/styles/pdfView.css');

**Comment by asmecher** [comment]
Michael, isn't this already imported from articleView.css?
https://github.com/pkp/ojs/blob/ojs-dev-2_4/styles/articleView.css#L12

**Comment by michael-pkp** [comment]
Thanks -- yes, you're right. I must have clobbered it during my merging of styles.

Closing.
