### ISSUE TITLE
Missing sidebar items after upgrade from OJS 2.4.x with PostgreSQL

### ISSUE THREAD

**Issue by tgc** [pkp/pkp-lib#3485]
Upgrading from OJS 2.4.x to OJS 3.1.0-1 when using a PostgreSQL database leaves many sitebar items missing.
The issue is that the fix implemented in https://github.com/pkp/pkp-lib/issues/2310 fails to be applied because in PostgreSQL LIKE is case-sensitive so no matches are made since at least in my OJS 2.4.x instance plugin_name contents are all lowercase.
Please either use LOWER or UPPER to ensure case before matching or create a special case for PostgreSQL using ILIKE instead.

Reference:
https://forum.pkp.sfu.ca/t/ojs-3-0-choose-language-search-at-the-index-page/20864

**Comment by asmecher** [comment]
Good spotting, @tgc -- committed a fix to `master` and `ojs-stable-3_1_0`.
