### ISSUE TITLE
[OJS] OJS 3.1.0 has bug about opening the plugin

### ISSUE THREAD

**Issue by ekacahyaprima** [pkp/pkp-lib#3489]
We have tried to use OJS 3.1.0. We want to upluad the Theme plugin such as bootstraps, etc. However, the Plugin cannot be reopenend in the OJS dashboard afterward. it is just looping. Finally, we uninstall it.

Anybody help me please...

Thank you.

**Comment by asmecher** [comment]
@ekacahyaprima, please post on our support forum at http://forum.pkp.sfu.ca/ -- if it turns out to be a bug we can migrate the issue back here.
