### ISSUE TITLE
Do not use journal contct in reply-to when sending issue and announcement notification emails

### ISSUE THREAD

**Issue by mczirfusz** [pkp/pkp-lib#3490]
A quick feedback on the new issue notification. The principal contact is added in the new issue notification as well as notification e-mails as a "reply-to" which resulted in that our journal editor received a large number of automatic replies and mail delivery error e-mails.  

I would suggest not to have a "reply-to" in both new issue notifications and announcements.

Also referencing #2561

**Comment by ajnyga** [comment]
There is a bounce setting in Settings => Workflow => Emails. Do you have something there?

#2561 only added the option of not sending the notification and https://github.com/pkp/pkp-lib/pull/2402 changed the reply-to address from the site contact to journal contact if the latter is available. 

The question whether there should be a reply-to at all is of course debatable, I have no strong opinions here.

**Comment by mczirfusz** [comment]
@ajnyga Thanks for the clarification and for linking the useful [thread in the forum](https://forum.pkp.sfu.ca/t/ojs3-notifications-sender-and-reply-to-address/28703). I think #2402 makes sense, i.e. to use a context-specific reply-to address. 

We have a bounce address set. The issue was that mail delivery errors of the new issue notification (sent out by me as a journal manager) went both to the bounce address (which is fine) and to our principal contact editor-in-chief (who was not expecting those). 

I personally would not use reply-to at all in case of new issue notifications and announcements: in most of the cases the user who sends these e-mails expects an answer, and adding the reply-to is superfluous. But perhaps there are other workflows at other journals which make this setting essential.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
