### ISSUE TITLE
OJS Saving the access settings, ajax fails

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3493]
OJS 3.1.0.1 and master branch

Saving the Settings => Distribution => Access form is partly broken. When saving the form the whole page is reloaded and the change is not visible in the form. If you leave and return to the tab, you can then see the change you made to the setting. So it is connected to the ajax handler probably, but not sure how.

**Comment by bozana** [comment]
Hmmm... @ajnyga, somehow this is not the case with my local installation (master branch)... :-O

**Comment by ajnyga** [comment]
hmm, I am seeing the same thing for example here: https://demo.publicknowledgeproject.org/ojs3/testdrive
If you compare to the other forms under distribution, you can see that the access form first tries to reload using ajax but then reloads the whole page.

**Comment by ajnyga** [comment]
Also, if in the payments tab there you select "Payments will be enabled for this journal. " but do not select a payment plugin and hit save, the form gets stuck.

**Comment by ajnyga** [comment]
I have a clean install of OJS 3.1.0.1, no modifications or plugins and I am seeing this on that installation. But on the PKP test server which is also 3.1.0.1 the selection is saved. 

I am also seeing this (the selection not getting saved + ajax save not working properly) on a vagrant ojs I just created. I believe it always uses the latest master branch?

**Comment by ajnyga** [comment]
This is a screen capture from master branch (vagrant ojs):
![2018-03-19 18 32 02](https://user-images.githubusercontent.com/16347527/37608775-15cef6fc-2ba4-11e8-8b40-dd96dfe673b7.gif)

**Comment by ajnyga** [comment]
@bozana 
This depends on the server it seems. 
I tested this with a XAMPP (php 5.6, OS X) on a localhost + OJS 3.1.0.1 => the saved setting is visible after saving the form (meaning it works)
PKP Vagrant OJS and master branch => the saved setting is not visible after saving the form (not working)
My own online test server (php 5.6, 64-redhat-linux-gnu) + OJS 3.1.0.1 => the saved setting is not visible after saving the form (not working)

I used the OJS package available in the PKP site and made no modifications, just added a new journal after installing and the tested the setting.

In all cases the whole page is reloaded, which is something I think it should not do in any case?

**Comment by ajnyga** [comment]
For the issue that the whole page gets reloaded, in the indexing tab you get this response `{"status":true,"content":"","elementId":"0","events":null}` for the `save-form-data?tab=indexing` query.

For the `save-form-data?tab=indexing` query the response is empty.

**Comment by ajnyga** [comment]
also @bozana removing the access tab from the forced page reload fixes the other issue I am seeing here, I mean the fact that the setting is not saved (or it is saved, but the reloaded form has the old setting). This is of course understandable, because 

So the combination of a) certain server environments + b) the forced reload of the whole page + c) the ajaxform functionality seems to result into a problem.

So we can fix this by removing the access tab from the forced reload, **but it will not solve the actual problem which may occur in other settings pages. For example the paymethod setting.**

**Comment by NateWr** [comment]
@asmecher may have some insight into the reload on the access page. There is a toggle there about subscriptions, and it may have been intended to display the submissions nav link when that toggle is activated and payments is disabled. Just a guess.

**Comment by ajnyga** [comment]
Hi,

Yes I was thinking the same thing. I guess the page reload is not a problem, but the issue I show in the GIF above is. As I mention there, that only happens with some server environments, but the problem seems to happen at least with the OJS Vagrant. I am using Firefox there.

I think that part of the problem is that the form uses the ajaxform.js whereas the paymentmethod setting page uses a custom js handler and does not have the same problem.

I am in the process of moving some of the settings under payments to the access page, but it really has to work properly before I do.

**Comment by asmecher** [comment]
That reload is a hack [implemented here](https://github.com/pkp/ojs/blob/ojs-stable-3_1_0/controllers/tab/settings/DistributionSettingsTabHandler.inc.php#L39..L43) to force the sidebar menu to reload when subscriptions were enable/disabled, so that the payments area would be shown. We have a few of these awaiting a better inter-component means of communication that would allow a more graceful appearance/disappearance.

**Comment by ajnyga** [comment]
Hi @asmecher 

Yes I noticed that code in there. It is just that switching the setting in the access tab does not affect the visibility of the payment menu. Only the payment setting hides/shows the menu. So, that is why I was thinking why refresh the whole page on the access form as well?

But, as I said above, that is not actually the problem here. The problem is that the ajaxhandler does not seem to reload the changes you make on that form in some server environments, the OJS vagrant included. 

Also a third issue mentioned above is that in the payment form, if you just enable the payments but do not choose a payment plugin and hit save, the form gets stuck.

**Comment by asmecher** [comment]
@NateWr, do your form changes replace this code?

**Comment by NateWr** [comment]
Yes, all of this is replaced in #3594.

**Comment by asmecher** [comment]
Thanks, @NateWr -- I'll close this issue in preparation for that code to be merged.
