### ISSUE TITLE
Usage stats not displayed as view counts for published articles

### ISSUE THREAD

**Issue by michael-pkp** [pkp/pkp-lib#350]
Stats are being processed and available via the usage stats report in OJS 2.4.5

But both abstract and galley views are displayed as 0 in submission editing for objects included in the report with counts > 0, i.e.
editor/submission/<submission-id>
editor/submissionEditing/<submission-id>

**Comment by asmecher** [comment]
Michael, have you seen e.g. http://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=12483 on the support forum?

**Comment by michael-pkp** [comment]
Hi Alec, all of the stats are being correctly processed by acron and are available via the usage stats report.

**Comment by asmecher** [comment]
Passing to @beghelli.

**Comment by beghelli** [comment]
Hi Michael,

By any chance you have any other plugin that implementes a different metric type other than the usage statistics plugin?

Can you also take a look at your journal settings table and search for a setting named 'defaultMetricType' ? If you have only one metric type plugin, it shouldn't be there. If you have more than one and you defined something it should.

Thanks.

**Comment by michael-pkp** [comment]
Hi Bruno, Just the usage stats plugin (confirmed via journal settings). I assume that the old views, timed views, etc. report plugins that come out-of-the-box with OJS 2.4.5 don't matter wrt this issue.

**Comment by beghelli** [comment]
You're right, the old ones are not implementing a new metric type. I tested
already this and did it again right now and I do see numbers there. Are you
sure you the galleys you have in the report are the ones you are checking
on the editor page?

2015-02-19 17:10 GMT-02:00 michael-pkp <notifications@github.com>:

**Comment by michael-pkp** [comment]
Thanks Bruno. Just double-checked the report vs. view counts to confirm.

Would it matter that we have historical data in the metrics table? There are three different metric_types in the table:
- ojs::legacyDefault
- ojs::legacyCounterPlugin
- ojs::counter

**Comment by beghelli** [comment]
no, usage statistics report only shows data from ojs::counter metrics. So
if you see something on that report, it should be also visible in the
submission editing page.

2015-02-20 13:18 GMT-02:00 michael-pkp <notifications@github.com>:

**Comment by michael-pkp** [comment]
Hi Bruno, it looks to me like MetricsDAO.inc.php:61 should be:

if (count(array_diff(array_keys($columns), $validColumns)) > 0) return $nullVar;

as opposed to:

if (count(array_diff($columns, $validColumns)) > 0) return $nullVar;

For example, when trying to retrieve a galley count,
columns = [assoc_id => 2348]
and validColumns = [0 => context_id, 1 => issue_id, etc.)
so the above will always return null

**Comment by michael-pkp** [comment]
Sorry Bruno, figured it out -- I had made some other changes trying to debug this.

Closing.
