### ISSUE TITLE
Review overdue - move to end of the day

### ISSUE THREAD

**Issue by mczirfusz** [pkp/pkp-lib#3500]
A review is marked as overdue already during the day of the due date. It would be perhaps more convenient for the reviewers to mark a review as overdue only the next day and leave the whole day for them to complete the review.
[OJS 3.1.0-1]

**Comment by NateWr** [comment]
I believe this should already be the case.

https://github.com/pkp/pkp-lib/blob/master/classes/submission/reviewAssignment/ReviewAssignment.inc.php#L473-L482

@mczirfusz are you able to provide a reproducible set of steps for me to test out?

**Comment by bozana** [comment]
@NateWr, I am not sure, but: shouldn't the check be for the current date?

**Comment by mczirfusz** [comment]
@NateWr I was able to reproduce it also on the OJS testdrive. I added a reviewer with response and review due dates set for the current day (26 March), and then I see Overdue in the Editor workflow - both if the reviewer has already accepted the review (Test Reviewer), and in the case the reviewer has not even answered the request (test test); see the screenshot below with the two cases.
![image](https://user-images.githubusercontent.com/16511307/37930661-ad72be90-3143-11e8-8c96-9dfe159320e6.png)

(We were experiencing the same with our running OJS install, as one of our reviewers was complaining that he saw the Overdue message on the due date, although he was doing the review on that day.)

**Comment by NateWr** [comment]
You're both right. This check was a bit of a face-palm. I was trying to do a `<` comparison with `YYYY-MM-DD 00:00:00` strings. And then comparing against the wrong date.

PR:
https://github.com/pkp/pkp-lib/pull/3524

Tests:
https://github.com/pkp/ojs/pull/1891

@bozana can you code review?

**Comment by NateWr** [comment]
Merged to `master`, `ojs-stable-3_1_1` and `omp-stable-3_1_1`. :+1:
