### ISSUE TITLE
Untranslated locale key for scheduledTaskLogs log file

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3506]
This is in a clean OJS 3.1.0 install.

The log file is named ##admin.scheduledTask.openAccessNotification##-5aac1d15f3456-20180316.log

**Comment by bozana** [comment]
@mfelczak and what is the primary installation, site and journal locale?

**Comment by asmecher** [comment]
@mfelczak, I think the attached commit should resolve it; if possible, please apply it and confirm.
