### ISSUE TITLE
OJS Prevent editors from creating discussions if they are not stage participants

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3508]
Hi @NateWr this maybe is within your realm?

At the moment an editor can start and participate in a discussion even if she is not a stage participant.

This causes a problem. When discussion is started for example with the author, only the author is added as a participant to the discussion. Now, when the author answers the discussion message, the editor does not receive any notification about the new message because she is not a participant in the discussion.

This happens especially in the submission stage. In many cases the editor starts a discussion before adding any editor as a stage participant. These discussions usually concern the contents of the submission.

So my suggestion is that participating in discussions requires all users to be stage participants.

Alternatively, if you do not want to prevent editors from participating in the discussions without a stage assignment, the code that handles the discussion participant addition/listing should be extended so that editors are taken into account also when they are not stage participants.

**Comment by NateWr** [comment]
I remember we did something about this (or just talked about it) not that long ago. I think the concern then was that the current user should always be selected by default as a participant. If that's in place, the only additional thing we'll need to do is make sure that the current user is available as a participant, even if they're not assigned.

**Comment by ajnyga** [comment]
You are leaning towards the alternative solution, right? I think that is the more complicated solution but probably also more flexible. 

We did discuss this when I tried to explain the logic how available discussion participants are listed for open reviews. There by default blind reviewers should not be included in the listing but if the user herself is a blind reviewer, then her name should be included.

Adding editors without assigments to the mix would be a bit different I think.

**Comment by NateWr** [comment]
> You are leaning towards the alternative solution, right?

:+1: 

> Adding editors without assigments...

...but only the current user when a discussion is created.

**Comment by ajnyga** [comment]
I can look at this as part of the open reviews work. I am waiting for this to be merged https://github.com/pkp/pkp-lib/issues/3130#issuecomment-374895449 and the release of 3.1.1. and then aiming for that slot with my additions.

**Comment by NateWr** [comment]
While you're at it... from some UI/UX testing we recently finished:

> When creating a discussion, if the creator is the only user selected, provide a prompt to select at least one additional user (are you sure you only want to send this message to yourself?)

**Comment by asmecher** [comment]
> While you're at it... from some UI/UX testing we recently finished:
> 
>> When creating a discussion, if the creator is the only user selected, provide a prompt to select at least one additional user (are you sure you only want to send this message to yourself?)

That's already filed separately: https://github.com/pkp/pkp-lib/issues/1619

**Comment by ajnyga** [comment]
The new https://github.com/pkp/pkp-lib/pull/3548 includes addition that always adds the current user to the new discussion as participant. This means mahager roles without stage assignment and also reviewers in review stage.

What is still missing though is the modal window saying "are you sure you only want to send this message to yourself?" We should not block that totally like https://github.com/pkp/pkp-lib/issues/1619 suggests, because an editor may be using the feature for making notes?

**Comment by NateWr** [comment]
> We should not block that totally like #1619 suggests, because an editor may be using the feature for making notes?

I'm of two minds on this one. In general, I agree if someone wants to use a tool in a certain way we shouldn't block it unless we have a good reason. I send emails to myself all the time as a form of note taking. :)

However, I wonder if there are data-sanity reasons why we might want to enforce at least two participants in a discussion. The prospect of someone saving data in the system that would never be visible to anyone else (even another editor) could cause issues for auditing and record-keeping. And the activity log provides a nice run-down of all activity on a submission for an editor. Allowing another editor to save data only they can see might complicate this.

For these reasons, I'd be tempted to disallow discussions without two participants. We do already have an Editorial Notes area for editors who want to make comments.

**Comment by NateWr** [comment]
Closing as the main feature request has been implemented. If further work is desired, please open a new issue.
