### ISSUE TITLE
display last revisions of reviewer files

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3510]
Currently the first revision of a reviewer file is displayed (considered) in the reviewer files grid. 
In OJS 3 there is no possibility to upload a revision of a reviewer file -- every file upload will be saved as a new file, with the new file id. So here there is no problem.
However, in OJS 2 every reviewer file upload was saved as a revision of the same file. Thus, in order to be able to easier access the last revision of such a reviewer file and to see that there are other revisions (by seeing the last revision number), the last revision should be displayed in the grid, as this is the case for all other file grids too.

S. also discussion here: https://github.com/pkp/pkp-lib/issues/3502

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/3511
https://github.com/pkp/ojs/pull/1883 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look?

**Comment by asmecher** [comment]
Makes sense to me -- please go ahead!
