### ISSUE TITLE
[OJS] "Possible Duplication or Revision Detected" - confusing file upload process

### ISSUE THREAD

**Issue by mczirfusz** [pkp/pkp-lib#3518]
Enhancement request for warning "Possible Duplication or Revision Detected" in (author) file upload process.

Currently, uploaded files will be checked against existing files to identify possible revisions. ([State number 3](https://github.com/pkp/pkp-lib/blob/ffd8a58a62546a74a2ad0eb5da7f2c37261dd2de/templates/controllers/wizard/fileUpload/form/fileUploadForm.tpl))

This caused some confusion for an author uploading a file during a submission. Under Upload file Stage 1 user selected from the dropdown that this is not a revision of an existing file. The system checked the file against existing ones and came up with the "Possible Duplication or Revision Detected" message, although the user has previously chosen that this is not a new file. User clicked simply on Continue, uploading in fact a revision, as the dropdown default is not "This is not a revision of an existing file" but one file detected as a duplicate candidate. Editors had to do some digging to recover all files submitted by the author.

The case in question were figures attached to the submission. Users often name them as "figure_1.jpg" "figure_2.jpg" etc. If for example "figure_2.jpg" is uploaded, then it is detected as a possible revision of "figure_1.jpg", because of the file name, thus triggering the possible duplication warning.

A simple enhancement is that if the user chooses that this is not a revision in file upload Step 1, then upon detecting a possible duplicate, the default of the dropdown list shall be "This is not a revision of an existing file" rather than one possible duplicate file name.

[OJS 3.1]

**Comment by mczirfusz** [comment]
see also https://github.com/pkp/pkp-lib/issues/2055#issuecomment-264284264

**Comment by NateWr** [comment]
The "Possible Duplication or Revision Detected" screen was removed in 3.3.
