### ISSUE TITLE
[OJS] Paging in Submissions#active panel 

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#3521]
Hi, 

I just finally upgraded to OJS 3.1.0.1 from OJS 3.0.0 using the release tarball, which went very smoothly. Thanks for that. The upgrade.php upgrade only gave a warning at lib/pkp/classes/submission/PKPSubmissionFileDAO.inc.php and another *DAO. But the updated OJS works just fine and the Submissions view looks much nicer! A big thank you for that, too. 
Now, my question: in OJS 3.0.0 a made a small change to ./lib/pkp/controllers/grid/submissions/SubmissionsListGridHandler.inc.php to use PagingFeature instead of InfiniteScroll. It seems you refactored that part of OJS since this has been replaced by ./lib/pkp/controllers/list/submissions/PKPSubmissionsListHandler.inc.php, which looks very different and I can't see where the infiniteScroll comes in. Could you give me a hint on whether I could still switch from InfiniteScroll to Paging and which controller or config this ended up in for the 'active submissions' tab? 
Thanks, 
Andreas

**Comment by NateWr** [comment]
I'm going to close this issue since we won't be addressing it directly, but feel free to continue to comment if you have questions.
