### ISSUE TITLE
[OJS] How to change email template management 

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3523]
Hello,

Some thoughts on mail management, because our publishers are asking us for improvements.

First, as it says in
https://forum.pkp.sfu.ca/t/ojs-3-x-x-choice-to-pick-language-for-forms-and-templates-when-sending-e-mails/31849/4,
they want to be able to choose the email language: currently the email locale depends on the user interface language, even if the receiver has chosen a working language.

Second, they would like to be able to select their custom email templates in any case, as requested in https://github.com/pkp/pkp-lib/issues/3193

And thirdly, they want to see the final mail before sending it, as in https://github.com/pkp/pkp-lib/issues/2180.

In the first case, because by default, no working language is selected for users (possibly OJS could pre select a working language when the user registers according to the locale), I think add the possibility for users to select different languages ​​for a template.
Maybe the way to do it is just to add the locale in the subject of the email: "[en_US] [JOURNAL] Article Review Request"

And the presentation of different locales can be avoided by a setting in Settings> Website> Languages: a check box "Mails" like UI, Submissions, Forms.

In the second case, they want to have more than one model, for example they want a quick revision model and this, potentially in all cases where a model mail is proposed.

Now, when custom templates are offered - which is only the case in Add Reviewer and Notify Participant if I'm not mistaken - all custom templates are proposed, not limited by one type.

I propose for each predefined email template to add the ability to have our custom template linked to this email template key, perhaps by automatically creating the custom email key as CUSTOM_ $ original_tpl_key_COUNTER (1, 2 etc.)

And when the system proposes an e-mail template, it offers not only the main e-mail key but also customized templates with: LIKE CUSTOM_ $ original_tpl_key_%

Maybe the model that @NateWr offers https://github.com/pkp/pkp-lib/issues/1432#issuecomment-357735815 is a solution, but I do not know exactly what to do with it.

And for the third, the solution proposed by @defstat is a good way, but it should work all the time, regardless of the name of the variables, I think.

So for me, one way to do this is to implement an extra step (maybe that can be disabled as an option in the settings) with confirmation on the final email presented as a read-only mail .

A lot of questions, but I have to implement these three points, so I'm asking you for ideas or better ways to do it.

Thank you
(ps: we use ojs stable 3.1)

**Comment by NateWr** [comment]
Hi @forgive38, just to let you know I've created a Project to collect all of our requests and ideas around email templates, drafting and sending. It won't help you right now but it may give you a sense of what's going on around this. https://github.com/pkp/pkp-lib/projects/10

**Comment by NateWr** [comment]
Closing this in favor of https://github.com/pkp/pkp-lib/issues/5717, which will resolve the three points raised above.
