### ISSUE TITLE
Fix anonymised reviewers when user assigned as ROLE_ID_MANAGER

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3527]
See: https://github.com/pkp/pkp-lib/pull/3499#pullrequestreview-106487065

**Comment by NateWr** [comment]
The fix was exactly as you said, @bozana. :+1: Can you do a quick review on this?

PR:
https://github.com/pkp/pkp-lib/pull/3528

Tests:
https://github.com/pkp/ojs/pull/1893
https://github.com/pkp/omp/pull/518

**Comment by bozana** [comment]
That looks good, so when the tests pass we can merge...

**Comment by NateWr** [comment]
Merged!
