### ISSUE TITLE
Abstract submission word count is inaccurate

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#3529]
The word count method in 2.4.x incorrectly counts "empty" words when two or more spaces occur together in the abstract.  It also fails the boundary condition of allowing an abstract of exactly the allowed word count.
https://github.com/pkp/ojs/blob/d7a976e8c3108138f0254daa724481597a6d780d/classes/author/form/submit/AuthorSubmitStep3Form.inc.php#L43

The 3.x solution is better:
https://github.com/pkp/ojs/blob/0c7aafabcdf12dd896784e2dca77c5c94782c127/classes/submission/SubmissionMetadataFormImplementation.inc.php#L49

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by asmecher** [comment]
Also cherry-picked to `ojs-stable-2_4_8`.
