### ISSUE TITLE
CSL Plugin should use journal abbreviation for abbreviated journal title display

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3530]
Currently journal initials are being used as per https://github.com/pkp/citationStyleLanguage/blob/master/CitationStyleLanguagePlugin.inc.php#L319

This results in citations being formatted as e.g. "JIDC" as opposed to "J Infect Dev Ctries"

**Comment by NateWr** [comment]
I used the initials because we require that field, so we can be certain it exists. Journal abbreviation is not required. And, funny enough, our test data seems to put "publicknowledge" for Journal Initials and "JPK" for Journal Abbreviation.

Given this, what would you see as the appropriate behaviour when no Journal Abbreviation exists? Should it fall back to the Journal Initials or the Journal Name?

**Comment by mfelczak** [comment]
Hi @NateWr, might be good to fall back on the journal initials if the journal abbreviation is missing. This will preserve display for existing journals that may be using the initials for a custom short-title display or as a manual workaround for this bug.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/citationStyleLanguage/pull/30

Tests:
https://github.com/pkp/ojs/pull/1899

(I'm looking at a couple of other CSL issues #3546 and #3546. If they're easy I may roll them into this PR.)

**Comment by NateWr** [comment]
@bozana would you code review?

**Comment by asmecher** [comment]
> And, funny enough, our test data seems to put "publicknowledge" for Journal Initials and "JPK" for Journal Abbreviation.

@NateWr, I don't see that in the test scripts -- maybe custom data or old data?

**Comment by NateWr** [comment]
Yeah maybe! I haven't reset in a looong time. :+1:

**Comment by bozana** [comment]
@NateWr, everything all right, it can be merged.
And yes, it is true for the tests, s. https://github.com/pkp/ojs/blob/master/tests/data/20-CreateJournalTest.php#L62

**Comment by NateWr** [comment]
This was fixed in https://github.com/pkp/pkp-lib/issues/3769
