### ISSUE TITLE
Can't search by full name when enrolling existing user as reviewer

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3533]
1. Assign a new reviewer
2. Enroll existing user
3. When searching, if you write a first and last name, like `Domatilia Sokoloff`, it won't match. It appears to only match the search phrase against first or last names.

We can use the `/users` API endpoint to perform the search, but we'll need to figure out how to get it working with the autosuggest field. It may be best to wait until we refactor our forms using Vue.js.

**Comment by israelcefrin** [comment]
Just closing because it has been fixed in OJS 3.1.2.
