### ISSUE TITLE
Site level navigation menus should load also inside a context

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3539]
Hi @defstat @NateWr 

It seems that the site level navigation menus are only visible when context is 0.

It would make sense that site level menus would be visible also when inside another context, for example a journal. Because then you could create site wide navigation menus that you can access also when you are visiting a context. I think that many multijournal sites would like to have some sort of site wide navigation.

**Comment by NateWr** [comment]
As far as I can tell, the only navigation menu items that work in context `0` are Custom Pages and Remote URLs. There's also the user login, dashboard, etc. stuff.  What else would you see going in these menus?

Also, there's a complication around the fact that every theme defines its own navigation menu areas. So even if you create a site-wide navigation menu, it'd still have to be assigned to a specific navigation menu area for each journal independently.

**Comment by ajnyga** [comment]
Hi,

For example
- link to site front page (now not accessible from within a journal)
- link to site wide search form (index/search)
- link to site wide browse by issue (when available)
- link to site wide presentation pages, like About, Policies, Contact etc. (About is now pasted to the site front page template which is not a good place for longer text)

> Also, there's a complication around the fact that every theme defines its own navigation menu areas. So even if you create a site-wide navigation menu, it'd still have to be assigned to a specific navigation menu area for each journal independently.

Sure, but the situation where you would need this kind of menu is a situation where the site and the journals are using some uniform theme that ties the journals together visually and with the site wide navigation menu also in a concrete way.

Here few OJS2 sites that would benefit from such menu (they already use one in OJS2 which is hard coded in the ):
https://www.ajol.info
https://www.mongoliajol.info/
https://www.nepjol.info/
https://www.lamjol.info/

Also publishers using OMP would be probably interested.

**Comment by NateWr** [comment]
Ok, you've convinced me. :) I see a few parts to this, in descending order of priority:

1. There are some site-wide URLs that we don't have navigation menu items for, like site-wide search, site-wide front page, and any custom pages / remote urls. These should be available when building a context-specific navigation menu.

2. It would be nice if there were some way to assign a site-wide navigation menu to a menu area in a specific context.

3. It would be nice if there were some facility for a publisher with many journals to do (2) for every journal on the site.

I'm not sure where they rank in our priority list of new features. They may be edge cases, but I suspect these features will go along with some of the improvement work we want to do for SaaS providers.

Pinging @defstat for input on the nav menus and @asmecher for input on how high a priority it seems for SaaS providers.

**Comment by ajnyga** [comment]
Great, thanks for considering this!

For 2 and 3 the scenario I was thinking is that the site and the journals all use the same theme. But of course it would be even better if there would be an easy way of adding the site navigation to other journal themes as well.

What I am thinking is that the code would always check for context 0 menus, regardless of the current context. I actually think that this would not require much changes to the current code.

For 1, yes these are definitely needed!

**Comment by NateWr** [comment]
> What I am thinking is that the code would always check for context 0 menus, regardless of the current context. I actually think that this would not require much changes to the current code.

Do you mean that `{load_menu name="primary"}` would always load menus from the site-wide context if they were assigned? I think we'll run into issues with this, where a host runs many journals through a single install, but wants to use the site index for it's own site without impacting on the journals.

**Comment by ajnyga** [comment]
Hi,

I see what you mean. When I tried to implement a site wide menu, I created a new site menu called `sitewide` and added a new menu area to the template that was used both by the site and the journals. So there was no conflict between the default `primary` menus. 

What if a menu could have a "sitewide" setting and only these menus would be checked inside all contexts?

**Comment by asmecher** [comment]
I don't have an opinion on the SaaS question in https://github.com/pkp/pkp-lib/issues/3539#issuecomment-377898525 -- maybe @jmacgreg does?

**Comment by NateWr** [comment]
> What if a menu could have a "sitewide" setting and only these menus would be checked inside all contexts?

I try to avoid adding options which only work when other, undeclared conditions are met (I know we have lots of these). In this case, such an option would only work if every context was using a theme with the specified theme area.

I'd rather require more manual intervention to solve a problem up-front than create confusion with a only-sometimes-working automated solution.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
