### ISSUE TITLE
[OJS] Legacy whitespace (line breaks) stripped in reviewer comments when presented in UI

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#3540]
Hi,

We have an issue where editors are complaining that the formatting in reviewer comments got lost during the upgrade from OJS 2.4.6 to 3.1.0-1.

I checked the database and the whitespace is still present, but discarded in the UI presentation. I think it might be related to https://github.com/pkp/pkp-lib/issues/2641 and similar updates, and the addition of HTML-formatting possibilities to the reviewer comments field.

Can OJS be tweaked to consider both the legacy whitespace and the new formatting?

(We already discarded the patch to remove the nl2br filter from the abstract presentation to preserve line breaks in abstracts, but perhaps that's not the best solution?)

Thanks!

**Comment by ajnyga** [comment]
Does your `allowed_html ` setting in `config.inc.php` look like this: https://github.com/pkp/ojs/blob/master/config.TEMPLATE.inc.php#L269 ?

**Comment by martinpub** [comment]
Hi @ajnyga, yes it does.

**Comment by martinpub** [comment]
@ajnyga It's the same as with the reviewer comments, no HTML but newline-formatted.

**Comment by ajnyga** [comment]
So both for abstracts and reviewer comments, there is no html formatting saved in the database? Did you have tinymce editor disabled in OJS2?

**Comment by martinpub** [comment]
Probably, yes. And we have a lot of data of this kind. OJS 2 rendered it alright, so it was never discovered I guess. Is a fix possible do you think or do have to consider running some processing on the raw data?

**Comment by ajnyga** [comment]
Tagging @bozana here, she maybe has a better idea.

But I think that the easiest solution for your would be to make a small script that takes your current data (abstracts, reviewer comments) and runs that through nl2br and stores it back to the database. 

Probably you could also just do a mysql find and replace like this for the right fields https://stackoverflow.com/questions/7177007/sql-query-to-convert-new-line-character-to-a-html-br.

Just remember to do backups!

In any case I think that modifying OJS to support what you have now in your database is not possible, because all the new abstracts will be stored with html coding so leaving the nl2br there will cause double line breaks for the new abstracts.

**Comment by martinpub** [comment]
I see, thanks @ajnyga. Will see if @bozana has anything to add. We should probably reset our removal of the nl2br filter, as I understand it will produce redundant line breaks for new data.

**Comment by ajnyga** [comment]
In OJS3 disabling tinymce will cause a lot of errors. You basically can not use the settings area in OJS3 without it. So In my opinion it should be forced to be enabled (or move to whole tinymce plugin to the core)

**Comment by asmecher** [comment]
I think we should definitely force the TinyMCE plugin to remain enabled -- I've never heard of a good reason for disabling it -- or better yet, move it into the core and stop pretending it's an optional piece of OJS.

Are `nl2br` calls common for fields that are authored with TinyMCE? I wouldn't think so -- that combination would lead to a lot of extra whitespace, I think.

**Comment by bozana** [comment]
OK, thanks @asmecher and @ajnyga!
@martinpub, then yes, the solution @ajnyga suggested is the best way to solve the problem -- to write a script that will replace line breaks with html br elements in all those fields/values in the DB, if they do not already contain html.
Forcing TinyMCE to remain enabled can be then the separate issue...

**Comment by martinpub** [comment]
OK @bozana, thanks, we will get to it.

**Comment by bozana** [comment]
@martinpub, maybe you could post your solution here? -- for the others having the same problem, to have a start point... Or at least what DB fields are affected i.e. should be considered?

**Comment by martinpub** [comment]
@bozana, sure we can, will report back here when we've had a chance to look at it.
