### ISSUE TITLE
both editor actions "Accept and Skip Review" and "Accept Submission" are logged as "(Accept and Skip Review)"

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3543]
s. https://github.com/pkp/ojs/pull/1850

The action labels are taken here: https://github.com/pkp/pkp-lib/blob/master/controllers/modals/editorDecision/form/PromoteForm.inc.php#L81
That array is constructed from several arrays (s. https://github.com/pkp/ojs/blob/master/classes/workflow/EditorDecisionActionsManager.inc.php#L45-L48), where two of them contain the key SUBMISSION_EDITOR_DECISION_ACCEPT, but with different values: 
https://github.com/pkp/ojs/blob/master/classes/workflow/EditorDecisionActionsManager.inc.php#L145 (with skip review) and
https://github.com/pkp/ojs/blob/master/classes/workflow/EditorDecisionActionsManager.inc.php#L183.
Thus, the submission stage should be considered in the promote form when getting the decision action labels.
(Then provided for the editorial action record here: https://github.com/pkp/pkp-lib/blob/master/controllers/modals/editorDecision/form/PromoteForm.inc.php#L88
There here used for the log event: https://github.com/pkp/pkp-lib/blob/master/classes/submission/action/EditorAction.inc.php#L93)

**Comment by asmecher** [comment]
Thanks, @defstat, I can review this while Bozana is away from the computer. But it'll definitely need a PR for OMP too -- could you add one to the list?

**Comment by asmecher** [comment]
@defstat, thanks -- it looks like there's a problem with the tests that needs attention.

**Comment by defstat** [comment]
@asmecher Tests passed.

**Comment by asmecher** [comment]
Thanks, @defstat -- please go ahead with the merge!

**Comment by defstat** [comment]
@asmecher everything merged.

**Comment by asmecher** [comment]
Thank, @defstat!
