### ISSUE TITLE
CSL doesn't escape quotation marks properly

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3546]
The following title:

```
Est maximus eu donec congue felis amet "sollicitudin non sagittis" aćnd
```

Will be output as a citation with the second quote escaped like this:

```
Corino, Carlo, Test Contributor, and Test Another. 2017. “Est Maximus Eu Donec Congue Felis Amet "sollicitudin Non Sagittis&quot; Aćnd”. Journal of Public Knowledge 2 (3). https://doi.org/10.1234/publicknowledge.v2i3.30.
```

**Comment by NateWr** [comment]
@asmecher and @bozana I'm not too good at character encodings, but `htmlspecialchars` doesn't seem to be sufficient for this case. It's causing the `&quot;` addition.

Also, if HTML in titles (https://github.com/pkp/pkp-lib/issues/2564#issuecomment-377704207) is ever implemented, we won't be able to use it there anyway. Do you have alternative ideas for sanitizing the title here?

**Comment by vedranvucic** [comment]
I am willing to be very cooperative in order to solve this issue. I will prepare test environment for that purpose.

**Comment by NateWr** [comment]
Thanks @vedranvucic!

**Comment by NateWr** [comment]
Hmm, I'm not sure. Perhaps it had something to do with how it was processed for saving in the database? I will have to look into it a bit more to see if I can reproduce the issue still.
