### ISSUE TITLE
[OJS] Issue cover on issue view page links to the same page

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#3549]
Hi,

When viewing an issue in OJS, the cover image is currently linking to the exact same page (the path issue/view/[issue_id]). Is this intentional or something that could be removed in order to avoid linking confusion? Apparently, some of our editors expect the link to go to the issue galley, which I know is not possible due to the possibility of having multiple galleys.

Thanks for considering!

**Comment by asmecher** [comment]
@martinpub, what version of OJS are you using? (Please include this with your posts.)

Generally if you're asking a question it's best to use the forum (http://forum.pkp.sfu.ca/) but let me know what version you're using and we can have a look here.

**Comment by martinpub** [comment]
Hi, sorry @asmecher, it's 3.1.0-1. As I wasn't sure if this was a bug report or a feature request, I posted here.

**Comment by asmecher** [comment]
Thanks, @martinpub -- the link you're referring to is generated at https://github.com/pkp/ojs/blob/ojs-3_1_0-1/templates/frontend/objects/issue_toc.tpl#L32. Personally I use links like this all the time to grab/share URLs but I'm not sure if that's what was intended here. Tagging @NateWr for his opinion.

**Comment by NateWr** [comment]
Yeah I think the link could be removed. I think maybe once we linked to a full-resolution version of the cover image?
