### ISSUE TITLE
Labeling EPUB galleys according to their mime type

### ISSUE THREAD

**Issue by felixgruender** [pkp/pkp-lib#355]
In OJS, galley labels are suggested automatically according to the mime type of the galley file (for example PDF or HTML).
This should be extended to EPUB galleys - that means EPUB files should be recognized correctly and labeled as EPUB.
As this is part of our project, we are going to implement this ourselves.

Regards, Felix

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by asmecher** [comment]
(Also synced the mime_content_type implementation with master, which isn't really part of this issue, but needed doing)
