### ISSUE TITLE
[OJS] Mass assigning stage participants

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3554]
Some journals tend to discuss the submissions together with the whole editorial board. 

In these cases it would be nice, if you could assign multiple users to a stage at once. Basically, instead of having a radio button to choose the stage participant, there would be checkboxes in front of the user names. 

I did not check the details of the code, but I think that this would be a fairly straight forward change. 

edit: related old issue https://github.com/pkp/pkp-lib/issues/1447

**Comment by NateWr** [comment]
User selection could be addressed alongside #2860.

**Comment by NateWr** [comment]
Closing due to lack of interest.
