### ISSUE TITLE
Remove email requirement for authors/contributors

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3561]
Currently all authors/contributors to a submission (OMP, OJS, etc.) are required to have an email address. This is problematic for a few reasons: 

- in the case of historical metadata where email addresses aren't known or don't exist
- where authors don't want to share their email addresses
- where submitting authors should take reasonable proactive precautions in terms of sharing personally identifying information

This requirement should be removed from the following locations: 

- author submission form
- quick submit plugin form
- XML import/export tool
- any other import tools that might use it

Wherever the author email is pulled in, a conditional check should be added to confirm whether there is such an email. 

Note: this is a more extensive issue than #1864 and #3316; I'd suggest closing those in favour of this one. @stranack may have some further thoughts here.

**Comment by stranack** [comment]
Strongly agree. When OJS is used for displaying digitized back issues, we currently have to add fake email addresses for every article, which is bad practice.

**Comment by jmacgreg** [comment]
Notes from https://forum.pkp.sfu.ca/t/is-ojs-gdpr-compliant/37521/38: 

> I strongly believe that at least it should not be removed from author submission form (may be removed from quick submit form) as adding email id of all contributors during submission by author is very useful in preventing author dispute/fake authorship.
> There are multiple cases in COPE’s forum regarding authorship dispute and in this regard, the forum strongly adviced to email all authors regarding papers submitted for publication at all stages of the editorial communication.
> Currently due to the mandatory addition of email ids for all contributors, it’s possible to send the email by OJS to all co-authors e.g. submission acknowledgment, editor decision email which is in line with core practice of COPE.
> Even its mandatory still many authors add fake/nonexisting email ids of co-authors and a significant number of such authorship dispute exist. But if this email field would not exist at all there would be more chances to have submission without co-author’s knowledge and more author dispute cases will emerge.

**Comment by carzamora** [comment]
Hi everyone, I think you forget this. And the journals are currently filling up of false emails to complete the email for contributors when is used the QuickSubmit plugin. I believe this is not too important for now submissions but for QuickSubmit.  Maybe is possible to take a desition for OJS 3.2?

**Comment by jmacgreg** [comment]
Hi @carzamora - thanks for the note! We haven't forgotten about it, but the reminder and nudge is very welcome. :-)  We hope to have this requirement relaxed soon.

**Comment by amandastevens** [comment]
There is a new [Author Requirements plugin](https://github.com/ewhanson/authorRequirements) available for OJS and OMP that allows you to make the contributor email field not required on the submission form.

**Comment by jmvezic** [comment]
+1 for this feature request. This would be a huge help to existing journals transitioning to OJS, who have a large backlog of articles they wish to include in OJS. E-mail wasn't always as prevalent as it is today in the article metadata (in a lot of systems it is still optional).

As it stands right now (with stock OJS), if you wish to include a large number of existing articles that have authors with no e-mail information, you have to literally make up fake e-mails, which is a bad practice.

**Comment by fgnievinski** [comment]
@jmvezic have you tried the existing [Author Requirements plugin](https://github.com/pkp/pkp-lib/issues/3561#issuecomment-551204880) in conjunction with either [Using the Web-based Expedited Submission Process to Add Articles Quickly](https://docs.pkp.sfu.ca/importing-exporting/en/#using-the-web-based-expedited-submission-process-to-add-articles-quickly) or [Using the Quick Submit Plugin](https://docs.pkp.sfu.ca/importing-exporting/en/#using-the-quick-submit-plugin)?

**Comment by NateWr** [comment]
Closing this in favor of https://github.com/pkp/pkp-lib/issues/5955.
