### ISSUE TITLE
Add separate fields for submission and distribution copyright terms

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3562]
Settings > Distribution > Copyright Notice is often used for displaying copyright terms to a submitting author, such as on the submissions page. However, it is also displayed in the licensing terms of the published article landing page. Typically, the author-facing terms are longer and require more legalese, whereas the published article needs a more concise statement of copyright/licensing terms.

- [ ] Move the Copyright Notice and Self-Archiving policies to Settings > Submission.
- [ ] Create a new field for Licensing Terms under Settings > Distribution and copy the existing Copyright Notice content there on upgrade.
- [ ] Use the Licensing Terms content in the article details page.

**Comment by rcgillis** [comment]
For the licensing terms, we could possibly explore the usage of rights statements: http://rightsstatements.org/en/documentation/usage_guidelines.html 
Would need to include a few things: who is the copyright holder? (e.g. the authors, the journal, a publisher). A license on top of who owns the copyright (i.e. Creative Commons, or possibly the Rights statements that I've referred to).

**Comment by NateWr** [comment]
I'm addressing this as part of #3594. I will leave this open to ensure we have a track record for 3.2, since we'll need to advise themes to update what they display on the frontend.

**Comment by NateWr** [comment]
Just saw that @defstat was assigned. Hopefully that's alright with you that I've taken this. It's just easier as part of some big refactoring I'm doing to the settings area.

**Comment by NateWr** [comment]
@asmecher Now that we have a different Copyright Notice (intended for a submitting author, with all the legalese) and License Terms (intended to be displayed with published material), do you know which should be used in the OAIMetadataFormat. There are two places that `copyrightNotice` is currently used:

https://github.com/pkp/ojs/blob/master/plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php#L227

https://github.com/pkp/ojs/blob/master/plugins/oaiMetadataFormats/rfc1807/OAIMetadataFormat_RFC1807.inc.php#L78

Should either of these be changed to `licenseTerms`?

**Comment by NateWr** [comment]
@asmecher Same question for `templates/gateway/clockss.tpl` and `templates/gateway/lockss.tpl`.

**Comment by asmecher** [comment]
Those should be `licenseTerms` (they're to be displayed with the content).

**Comment by NateWr** [comment]
:+1: This is now done as part of #3594 and will be included when that is merged.

**Comment by mittinatten** [comment]
From the discussion it seems this will be part of 3.2, but the milestone says 3.1.2. Is there any way to get this feature in a fork of 3.1.x? (cherry-pick?)

**Comment by NateWr** [comment]
No, not really. #3594 was massive and there's no one (or two or three) commits you can pull in to get `licenseTerms`.

I hadn't noticed the milestone. @asmecher does this need to be implemented for 3.1.2 or can it wait until 3.2?
