### ISSUE TITLE
[OJS 3.1.1] missing string editor.article.coverImage (all languages)

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3565]
hi, 
in a submission, when you click on View Metadata is missing the string editor.article.coverImage
![imagen](https://user-images.githubusercontent.com/5422984/38534292-da212114-3c53-11e8-9aa3-5e643e29f4e4.png)

I looked in the repository, but only da_DK have this string: https://github.com/pkp/ojs/search?l=XML&q=editor.article.coverImage&type=

**Comment by bozana** [comment]
Hmmm... yes, it was removed with this change: https://github.com/pkp/ojs/commit/e0d97bc71491a5a9591eab6815de3572577c3ff8#diff-ee2e16995d3d642d898806a469e591d0. @NateWr, shall we reconstruct them?

**Comment by NateWr** [comment]
Arg! Yes, my bad. This should probably make it into any 3.1.1-1 release.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/1914
https://github.com/pkp/ojs/pull/1915 (`ojs-stable-3_1_1`)

@bozana I think I've restored all the translations that I removed. Can you give me another set of eyes on this?

**Comment by bozana** [comment]
@NateWr, I only took a look at the first PR assuming that the second is the same. Everything all right, just one comment/question :-) THANKS!

**Comment by NateWr** [comment]
Thanks @bozana. Good catch on that locale key! I've fixed that and redone the stable PR due to some rebasing issues. I'll merge when the tests pass.

**Comment by NateWr** [comment]
Merged to master and stable 3.1.1. :+1:
