### ISSUE TITLE
[OJS] One-click reviewer access not disabled after reviewer cancelled

### ISSUE THREAD

**Issue by aguen** [pkp/pkp-lib#357]
The one-click revierwer access link is still working and allows access to the submission even though the reviewer has been cancelled by editor. 
OJS version 2.3.8

**Comment by asmecher** [comment]
@aguen, it's more than likely that this issue has already been corrected in more recent versions of OJS. Please upgrade to a recent release, and if this is still an issue, report it again.

**Comment by aguen** [comment]
Hi Alec,

Unfortunately the issue still exists with OJS version 2.4.5.0 (just tested). Even if the user is unenrolled as reviewer the link is stll active.

Armin

**Comment by asmecher** [comment]
Armin, that may be by design. Reviewers should always have access to view their review assignments, even if they're cancelled. They should be prevented from recording a review, however, in the case of a cancelled review. Can you confirm that this is the case in your situation?

**Comment by mtub** [comment]
Alec, just commenting from the sidelines here: I'd also think of this as an unwanted behavior. If the review assignment has been cancelled, reviewers shouldn't be able to access the submission. Have the cancelled assignment in their history: yes, maybe. Access to a submission they are no longer involved with? No, rather not.

**Comment by aguen** [comment]
Alec, it seems that the form fields on the cancelled reviewer page are set to disabled="disabled" as well as the form fields of the review form - so a normal user should be prevented from recording a review. I did not test however what's the case if I manually remove this disabled attribute and submit the form.
 
I agree with @mtub that cancelled reviewers should be prevented not only from recording a review but from accessing the submission at all and I appreciate that you set the issue as a milestone for 2.4.7.

**Comment by asmecher** [comment]
I can't guarantee we'll change the current behavior in 2.4.7 -- but that's the soonest release it'll be considered for, as OJS 2.4.6 is currently in translation and feature freeze. There would be a few knock-on coding changes required, such as removing cancelled assignments entirely from the reviewer's Archive list.

**Comment by ojsbsb** [comment]
We have just checked this in a fresh install of OJS 2.4.8: The problem is still present. And as @mtub said, cancelled reviewers should not be able to access unpublished articles they are not involved with. In fact, editors will think that by cancelling the review, they take away the access right as well - especcially as there is no other function to do so.

@asmecher, would it be of interest if we contribute a solution to this, so that access rights are removed when a review is cancelled?

**Comment by asmecher** [comment]
Yes, @ojsbsb, please go ahead. I agree with the solution you've proposed, we just haven't had a chance to implement something yet.
