### ISSUE TITLE
Localization key typo

### ISSUE THREAD

**Issue by ambs** [pkp/pkp-lib#3570]
Not too important, but there is this typo
submission.submit.form.citaionsRequired
on submission.xml

**Comment by asmecher** [comment]
Good spotting -- fixed! (And cherry-picked back to `ojs-stable-3_1_1` and `omp-stable-3_1_1`.)

**Comment by t4x0n** [comment]
@asmecher look this PR: pkp/pkp-lib#3626 and consider it for fix the same issue in pt_PT
