### ISSUE TITLE
[OJS 3.1.1] Announcement not showing in main page

### ISSUE THREAD

**Issue by harpraam** [pkp/pkp-lib#3571]
halo all, can fix my problem?

![image](https://user-images.githubusercontent.com/26021475/38568957-3184317e-3d14-11e8-80f4-0bcf5399f159.png)

mainpage not showing 
![image](https://user-images.githubusercontent.com/26021475/38568992-4c0cf35a-3d14-11e8-886e-305a673b9c2d.png)

**Comment by asmecher** [comment]
Hi @harpraam -- I see you're already working on this on [our support forum](https://forum.pkp.sfu.ca/t/ojs-3-1-1-announcement-in-homepage-not-show/40786). Please don't post the same issue multiple times -- the forum is the best place to track this down.
