### ISSUE TITLE
Allow a review round to be canceled after it has been created

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3585]
See https://forum.pkp.sfu.ca/t/new-review-round-while-previous-review-round-has-not-been-finished-yet/37686 for several useful suggestions.

- Don't enable "create new round"  button until revisions have been submitted
- Allow an empty review round to be deleted

**Comment by forgive38** [comment]
Hi,
To complete the discussion about rounds, one of ours journals found a bug when they create a new round ( they use the first round to have some quick reviews and open a second round for asking complete reviews )
Even if there is a revision, the status of the first round become "New version of submission has been requested." and a notification is in the task list of the author (no mail are sending).
I think this is not a good behavior: the status should be something like "Round is close"  without creating a task for author.

Thank you in advance

**Comment by ajnyga** [comment]
I am fairly sure I have mentioned this earlier, but in some cases journals start a new review round by accident. This happens when the submission is already in the review stage and they go, for some reason, to the submission tab/stage. If they do not know that you can navigate with the tabs, they may click the "send to review" button again, creating a second round.

So in short: if there already is a review round, the submission stage should not show any button.

(sorry if this was already fixed in 3.1.1., had no easy way of checking and wanted to make sure I do not forget about this...)

**Comment by hcoussy** [comment]
Hi,
We are using OJS 3.1.2-1 at University of Bordeaux for several journals. Our main journal encounter a similar problem. I didn't see any change of this issue since a while and it's not assigned yet. Is it planned for sometime soon?
Thanks in advance four your answer.
Best regards.

**Comment by asmecher** [comment]
Unfortunately this hasn't been scheduled against a release yet, though it has been identified as a community priority using the tags, so it's likelier than other issues to get attention.

**Comment by rshiggin** [comment]
Weighing in that this really does present problems for editors and we are eager for a fix. In our present situation the editors **accidentally** opened a new review round even though the first wasn't complete. This now blocks them from initiating a decision based on the reviews received for the first round. All they want to do is to rollback from and/or delete review round 2. It looks like modifying a d/b table is the only solution? We really don't like touching the database unless it's absolutely necessary.

In terms of use cases, review rounds are relied on when 1) a submission receives a revise and resubmit decision; 2) the initial reviews were inconclusive; or 3) a journal's workflow includes an initial round for desk review prior to seeking external peer reviewers. We've been encouraging editors to use the multiple rounds feature for these different use cases, but it's a harder sell when editors aren't able to roll back to the previous round or to correct an accidentally created round.

Richard Higgins
Indiana University Libraries

OJS 3.1.2-0 
Multisite with 50 + titles

**Comment by asmecher** [comment]
@rshiggin, if you really want to revert the second review round, you'll need to intervene in the database by removing the relevant entry from the `review_rounds` table. Any dependent entries (e.g. in `review_round_files` and `review_round_files`) referring to that review round would need to be removed too.

Without doing that, you should be able to record whatever decision you like on the second round, and ignore the first. You can record a note on the submission to indicate what happened. Not perfect but should keep the submission moving.

**Comment by varnum** [comment]
Having accidentally started two rounds at once on an article (I got distracted and clicked "Send to review" from the Submission screen twice), another vote for the proposed solution. And for a way to end the unwanted second round.

**Comment by librariam** [comment]
+1 from PKP|PS for an ability to remove the second round started by accident. We receive this request every now and then and prefer not to go the database editing round out of concern for introducing db errors down the road, particularly when actions have already been taken in the 2nd round.

**Comment by librariam** [comment]
+1 from PKP|PS to remove a new round started by accident, and to also make reviewer comments from previous rounds selectable by editor when sending a decision to the author

**Comment by touhidurabir** [comment]
@asmecher As per our discussion I have added the ability to remove an `Empty` review round (both external and internal) when created accidentally . please review it . 

Here the word `Empty` emphasise that no reviewers has been assigned to that round . Also this is only applicable when there is more than one round as if there is only one round , then deleting that is not the correct approach but need to have the ability to `Move back to Submission or Previous Phase` as discussed in the pkp/pkp-lib#2890 .

PRs 
[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#3585 Allow a review round to be canceled after it has been created](https://github.com/pkp/pkp-lib/pull/7997)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#3585 Submodule Update ##touhidurabir/i3585_main##](https://github.com/pkp/ojs/pull/3421)
[omp](https://github.com/pkp/omp) --> [pkp/pkp-lib#3585 Submodule Update ##touhidurabir/i3585_main##](https://github.com/pkp/omp/pull/1137)

**Comment by touhidurabir** [comment]
@asmecher @NateWr I am wondering if I should move this entire PR to pkp/pkp-lib#2890 issue PR on which I am currently woking on . In my opinion this request is pretty much of a subset of pkp/pkp-lib#2890 and the PR for both of pkp/pkp-lib#2890 and pkp/pkp-lib#3585 have quite a bit shared code .

**Comment by NateWr** [comment]
@touhidurabir yeah whatever you think is best. Often it's easiest to make one set of PRs for two issues. I usually just drop a note in the other issue saying "this will be fixed as part of work on #<issue number>"

**Comment by touhidurabir** [comment]
@asmecher @NateWr the PR for this issue has been addressed in the PR of pkp/pkp-lib#2890 . see the PR details at https://github.com/pkp/pkp-lib/issues/2890#issuecomment-1166296553 . The mentioned PR of pkp/pkp-lib#2890 includes the most requested decisions that allow editor to remove/delete an empty review round . 

Here the word `Empty` emphasise that no reviewers has been assigned to that round . Also this is only applicable when there is more than one round as if there is only one round , then deleting that is not the correct approach but need to have the ability to Move back to `Submission or Previous Stage` as discussed in the https://github.com/pkp/pkp-lib/issues/2890 .

Also I have closed the previous PRs targeting this issue only as that is not needed anymore .

**Comment by asmecher** [comment]
Resolved by https://github.com/pkp/pkp-lib/issues/2890!
