### ISSUE TITLE
[OJS] Creating a new discussion when user has two assignments causes a duplicate key error

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3588]
Hi,

Scenario: user has two stage assignments editor and funding coordinator. The user starts a new discussion. In the participant list the user is mentioned twice and also selected twice by default:
<img width="335" alt="nayttokuva 2018-4-13 kello 10 55 24" src="https://user-images.githubusercontent.com/16347527/38723280-3c829ee8-3f09-11e8-9ffc-772f4f3d2e1a.png">

If the user leaves both those selections active and sends the message the window will not close and you get:
`[13-Apr-2018 09:47:07 Europe/Berlin] ojs2: DB Error: Duplicate entry '10-3' for key 'query_participants_pkey'`

Also the email notifications are not sent.

@NateWr this is the case at least with 3.1.0.1 that we are using. I wonder if it is the same with 3.1.1?

**Comment by ajnyga** [comment]
Ok, so we just need to make sure that in queryform and querynoteform that there are no duplicate users in the list. I will send a pr soon...

**Comment by NateWr** [comment]
If can, try to concatenate their roles so all roles are still visible:

> Nate Wright   Journal Editor, Funding Coordinator

**Comment by ajnyga** [comment]
Technically this seems to be enough: `$newParticipantIds = array_unique($this->getData('users'));` here https://github.com/pkp/pkp-lib/blob/master/controllers/grid/queries/form/QueryForm.inc.php#L281

**Comment by ajnyga** [comment]
Ok, so this is not a similar issue in 3.1.1. There if you have a user with two stage assignments, it seems that the last assignment "wins". For example a user with editor and author assignment will only be visible in the discussion list with the author role.

**Comment by ajnyga** [comment]
Ok, so I will do the fix above to our server (will be moving to 3.1.1 after a couple of weeks) and I will do a pr according to your suggestion for the master branch. This is basically a visual enhancement that will show all the assigned roles for the user in the listing there. As I said, 3.1.1 will not cause a similar error as 3.1.0.1.

**Comment by ajnyga** [comment]
Adding all the stage assignments besides the user name is actually more difficult I thought. The reason is that at the moment the code is looping through the assignments. And inside one assignment there is only one role.

You could do this, but I hate that you are calling stage assignments dao twice:
```
			$queryParticipantsList = new SelectUserListHandler(array(
				'title' => 'editor.submission.stageParticipants',
				'inputName' => 'users[]',
				'selected' => $selectedParticipants,
				'getParams' => array(
					'count' => 100, // high upper value
					'offset' => 0,
					'assignedToSubmission' => $query->getAssocId(),
					'assignedToSubmissionStage' => $query->getStageId(),
				),
				// Include the full name and role in this submission in the item title
				'setItemTitleCallback' => function($user, $userProps) use ($assignments, $stageAssignmentDao, $query) {
					$title = $user->getFullName();
					foreach ($assignments as $assignment) {
						if ($assignment->getUserId() === $user->getId()) {
							$userAssignments = $stageAssignmentDao->getBySubmissionAndStageId($query->getAssocId(), $query->getStageId(), null, $assignment->getUserId())->toArray();
							$userRoles = '';
							foreach ($userProps['groups'] as $userGroup) {
								foreach ($userAssignments as $userAssignment) {	
									if ($userGroup['id'] === (int) $userAssignment->getUserGroupId() && isset($userGroup['name'][AppLocale::getLocale()])) {
										$userRoles .= $userGroup['name'][AppLocale::getLocale()] . ", ";
									}
								}
							}
							$title =  __('submission.query.participantTitle', array(
										'fullName' => $user->getFullName(),
										'userGroup' => rtrim($userRoles, ", "),
							));
						}
					}
					return $title;
				},
			));
```

**Comment by ajnyga** [comment]
Ok take that back, this is a solution where you call the stageassignment dao for each user, but twice like above, what do you think @NateWr 

```
			import('lib.pkp.controllers.list.users.SelectUserListHandler');
			$queryParticipantsList = new SelectUserListHandler(array(
				'title' => 'editor.submission.stageParticipants',
				'inputName' => 'users[]',
				'selected' => $selectedParticipants,
				'getParams' => array(
					'count' => 100, // high upper value
					'offset' => 0,
					'assignedToSubmission' => $query->getAssocId(),
					'assignedToSubmissionStage' => $query->getStageId(),
				),
				// Include the full name and role in this submission in the item title
				'setItemTitleCallback' => function($user, $userProps) use ($stageAssignmentDao, $query) {
					$title = $user->getFullName();

					$usersAssignments = $stageAssignmentDao->getBySubmissionAndStageId($query->getAssocId(), $query->getStageId(), null, $user->getId())->toArray();
					$userRoles = '';

					foreach ($usersAssignments as $assignment) {

						if ($assignment->getUserId() === $user->getId()) {
							
							foreach ($userProps['groups'] as $userGroup) {

									if ($userGroup['id'] === (int) $assignment->getUserGroupId() && isset($userGroup['name'][AppLocale::getLocale()])) {
										$userRoles .= $userGroup['name'][AppLocale::getLocale()] . ", ";
									}
							}

						}
					}

					$title =  __('submission.query.participantTitle', array(
								'fullName' => $user->getFullName(),
								'userGroup' => rtrim($userRoles, ", "),
					));

					return $title;
				},
			));
```
(https://github.com/pkp/pkp-lib/blob/master/controllers/grid/queries/form/QueryForm.inc.php#L209-L237)

**Comment by ajnyga** [comment]
@NateWr the latter solution as a pr: https://github.com/pkp/pkp-lib/pull/3591
But unsure if that is the way to go...
