### ISSUE TITLE
[OJS3] API parameter year for issues does not work after update to 3.1.1.0

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3589]
The user _mlfct_ reported in the [german forum](https://forum.pkp.sfu.ca/t/rest-api-benutzen/39862/3) that the _year_ parameter for the issues endpoint does not work anymore:

> api/v1/issues?count=20&years=2017

The filter for volumes seems to be broken too.

I tested it myself with my development installation (updated to the current master branch yesterday) and could reproduce the error for the _year_ parameter. The API returned every published issue, not only the issues from the requested _year_.

**Comment by NateWr** [comment]
Confirmed.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/1912
https://github.com/pkp/ojs/pull/1913 (`ojs-stable-3_1_1`)

**Comment by NateWr** [comment]
Tests passed. Merged to `master` and `ojs-stable-3_1_1`.
