### ISSUE TITLE
When a reviewer decline an invitation, he/she is still flagged as having 1 active submission

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#3590]
Bonjour, 

Problem occurs in the master branch code.

When a reviewer decline an invitation to review, dateConfirmed is set to NOW but not dateCompleted, (see file ReviewerAction.inc.php ligne 59 à 62).

In UI, even if the reviewer decline, it still has an active status in the reviewer selection window.

Repro step: 
1) Make new submission 
2) Connect as editor and send it to review
3) Select a reviewer to assign to the submission
4) Connect as reviewer and decline submission.
5) As an Editor, send another submission in Review
6) Look for the same reviewer selected in step 3. He/she should have 1 active submission.

Thanks 
Pierre

**Comment by asmecher** [comment]
@pilasou, are you asking about OJS, OMP, or OCS? How recent is your master branch checkout?

**Comment by pilasou** [comment]
OJS, we last sync yesterday.

**Comment by pilasou** [comment]
@asmecher here the code we add to correct the problem (ligne 59 in ReviewerAction.inc.php)
   $currentDate = Core::getCurrentDate();
   $reviewAssignment->setDeclined($decline);
   $reviewAssignment->setDateConfirmed($currentDate);
   if ($decline == 1) {
                $reviewAssignment->setDateCompleted($currentDate);
   }
   $reviewAssignment->stampModified();
   $reviewAssignmentDao->updateObject($reviewAssignment);

**Comment by asmecher** [comment]
@pilasou, I think the solution is not to include declined reviews in the counts at all, rather than marking declined reviews as complete (which probably has other implications and would require updating previously declined reviews too). Have a look at https://github.com/pkp/pkp-lib/pull/3592 and see if applying it in `lib/pkp` resolves the issue.

@NateWr, would you mind reviewing this PR? https://github.com/pkp/pkp-lib/pull/3592

**Comment by asmecher** [comment]
@pilasou and @NateWr, thanks for the feedback -- I think I've found a solution that's shorter, better and easier: exclude declined reviews from consideration entirely by changing the join. Mind having another look at the PR (#3592)?

**Comment by NateWr** [comment]
This may complicate https://github.com/pkp/pkp-lib/issues/3344. Editors want to know the ratio of declined submissions, and maybe also a count (is it 2/3 or 40/60?), when selecting reviewers.

From an API standpoint, we should probably be delivering information on the number of declined review assignments at `/users/reviewers`.

**Comment by NateWr** [comment]
This splits active from declined review numbers in the reviewer API response, and displays the declined reviews in the breakdown table.

PRs:
https://github.com/pkp/pkp-lib/pull/3693
https://github.com/pkp/ui-library/pull/19
https://github.com/pkp/ojs/pull/1966

**Comment by NateWr** [comment]
@asmecher tests have passed. This should be an easy review to merge and clear out for 3.1.1-1.

**Comment by NateWr** [comment]
@asmecher tests have passed. This should be an easy review to merge and clear out for 3.1.1-1.

**Comment by asmecher** [comment]
Thanks, all -- merged into `master` and cherry-picked to `ojs-stable-3_1_1` (and `omp-stable-3_1_1 as needed).
