### ISSUE TITLE
Implement modals/tabs support in Vue.js

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3595]
Modals and tabs represent a tricky problem for converting to Vue.js, because they are containers for other components. The typical Vue.js approach is to write components nested inside of other components directly into their templates, but this will make it much harder for third parties to customize our UI. 

We'll need to think of a clever, consistent way of using [slots](https://vuejs.org/v2/guide/components.html#Content-Distribution-with-Slots) to implement more of a configuration/injection approach that exposes the UI's layout to customization in plugins.

Expected features:

- A plugin should be able to specify the desired components inside of a tab or modal from the server side. Or a simple way to override things should be created in the client side.
- It should be possible to navigate to any tab, including tabs nested inside of tabs, with a URL, and the browser history should update.
- Tabs should support the traditional tab view (up top) as well as a side-tab layout.
- Tab labels should support badges, to indicate things like number of items or the existence of alert notifications inside them.
- Modals should be able to communicate with the component which opened them.

**Comment by asmecher** [comment]
Forms are generally the lowest level of all the intertwingled JS handlers we use, so I think it'll make sense to work on some of those first (#3594) and then pick a fairly simple tab set to follow up with (e.g. the user profile tabs and/or the information center).

**Comment by NateWr** [comment]
[portal-vue](https://github.com/LinusBorg/portal-vue) may be a good option for implementing modals.

**Comment by NateWr** [comment]
Closing in favor of #5865.
