### ISSUE TITLE
The keywords and metadata Agencies if required block Submission

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#3596]
In "Settings" -> "Workflow" -> "Tab submission" -> "section Submission Metadata" if we add the metadata "Keyword (s)" and "Supporting Agencies" and select "Required" then during a "Submission" we will have problems as described below:

when an author clicks in "New Submission" and arrives at step 3 "3-Enter Metadata" it happens that:

CASE 1: keywords free, agencies free
  always ok

CASE 2: keywords required,  agencies free

 - If I do not enter anything in both fields and click on save, I am notified of the required field error in keywords => OK
 - If I enter only something in agencies and leave blank keywords and save the form, it makes me continue however not respecting the required field => NOT OK
 - If I fill in the keywords field, it keeps me going => OK

CASE 3: keywords free, agencies required

 - If I do not enter anything in both fields and click on save, I am notified of the required field error in agencies => OK
 - If I fill in any field between keywords and agencies it does not make me go on to indicate that the agencies field is mandatory by deleting the content on both fields => NOT OK
 In this case there is no way to continue!

CASE 4: keywords required, agencies required

 - If I do not enter anything in both fields and click on save, I am notified of the required field error in keywords and agencies => OK
 - If I fill in any field between keywords and agencies it does not make me go on to indicate that only the agencies field is mandatory by deleting the content on both fields => NOT OK
 Even in this case there is no way to continue

**Comment by asmecher** [comment]
Hi @eniocarboni -- what version of OJS (or OMP) are you using?

**Comment by eniocarboni** [comment]
ojs 3.1.0.1

**Comment by asmecher** [comment]
@eniocarboni, this is already fixed in OJS 3.1.1: https://github.com/pkp/pkp-lib/issues/3311

**Comment by eniocarboni** [comment]
Thank you very much, I will update soon
