### ISSUE TITLE
[OJS] Problem with announcement type setting/checking

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#360]
When an announcement is created, the announcement's type_id is currently set to 0 rather than left as NULL in the event that there is no announcement type associated with it. This is problematic, because when lib/pkp/pages/announcement/PKPAnnouncementHandler.inc.php assigns the $announcementTitle variable, it checks whether the announcement type is null or not, and prepends the type name (with a colon if not - see line 67 of the above file. If the type_id is 0, the check fails. I've created a workaround for one of our journals by changing line 67 from 

if ($announcement->getTypeId() == null) {

to 

if ($announcement->getTypeId() == (null || 0)) {

... but I don't think that's the correct change - those values should be null instead of 0. 

This does seem to be a recent problem, introduced by an upgrade - this journal was upgraded from 2.3.6 (where announcement type_id's were marked will NULL, and so this wasn't an issue).

**Comment by beghelli** [comment]
I think that the correct check should be if (!$announcement->getTypeId())
That way we get null and 0, which makes sense to me.

**Comment by beghelli** [comment]
I can fix that if this is ok to everyone

**Comment by asmecher** [comment]
Yes -- thanks, Bruno.

**Comment by beghelli** [comment]
No need to port to master.
