### ISSUE TITLE
Extend internal articles report round 1

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3601]
Add "URL" column (URL -> internal editor submission URL); add column for all metadata (eg. keywords should be a column; same w/subject; etc.); add DOIs (if available, even in draft form); add journal initials to .csv filename

**Comment by asmecher** [comment]
@jmacgreg, could you pass this proposed change along to Minnesota for testing? https://github.com/pkp/ojs/pull/1953

**Comment by asmecher** [comment]
Another (worthy) request: add a link to the published article, when applicable. https://forum.pkp.sfu.ca/t/exporting-article-urls/45777

**Comment by jmacgreg** [comment]
UMN notes - looks great! I think this is good to be merged.

**Comment by asmecher** [comment]
Merged, thanks!
