### ISSUE TITLE
Add context to reports

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3602]
Add descriptive text for each report to their listing on the Statistics page; break out menu item into its own menu item

**Comment by jmacgreg** [comment]
PR incoming on this, just getting preliminary review from UMN.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
