### ISSUE TITLE
edit review assignment to add review form

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3608]
Many times the editors have forgotten to select the review form when sending a manuscript for review, and it is not possible to attach the form after the reviewer was assigned, it would be very helpful to incorporate this option.

There is currently no way to send the form to the reviewers if this error has been made.

**Comment by ajnyga** [comment]
do you mean change the review form from default to a custom form the journal has?

**Comment by t4x0n** [comment]
No, I say when you send to review a manuscript without choosing a form (by mistake). After that, you (as editor) cannot choose a review form, and the reviewer cannot see any form to submit he or she review comments. Sorry but I am not good at English... do you understand?

**Comment by ajnyga** [comment]
just to make sure, do you have a custom form besides the default form OJS has? I did not know it is possible to do a review request without choosing a form. If that is possible, then I think it is a clear bug.

**Comment by t4x0n** [comment]
If I understand, OJS does not have a default form for reviews, and I talk about this kind of forms:
![imagen](https://user-images.githubusercontent.com/5422984/39089382-5b99257e-459c-11e8-83e6-cec5502e2397.png)

and about that, of course, we have customs forms for reviews, but the problem is when an editor forget to assign a review form, like in this picture:
![imagen](https://user-images.githubusercontent.com/5422984/39089641-eb396116-45a2-11e8-90c5-40bbe203c75c.png)
and press the button Add Reviewer, after then you can not to correct this mistake. And the only way to correct this is unassigned the Reviewer and assign it again.

For me is not a bug, is more like this function for correct an assignment without review form is not developed yet.

**Comment by ajnyga** [comment]
Sure

**Comment by t4x0n** [comment]
"OJS does have a hardcoded default form" sorry @ajnyga, I never saw this form except now that you tell me that it exists, everyday you learn something new 😄 

so, about my initial comment? when editor send to review a manuscript without choosing the custom form, if I understand, you are considering edit this part of the process for add the form?

thank you!!

**Comment by ajnyga** [comment]
This is what I have in my test installation now (I still have to do some testing before a do a pr, but almost ready):

<img width="793" alt="nayttokuva 2018-4-26 kello 6 55 23" src="https://user-images.githubusercontent.com/16347527/39285020-e0aafb2c-491e-11e8-9595-95c3159968c1.png">

@NateWr note that I changed the default label there and will also change it for the form used to assign a new review.

Currently when you have custom review forms and add a new review assignment the default label says "Select Review Form". It is hard for the user to determine that by leaving that selection alone you can use the default form  (this is probably why @t4x0n did not know about the default form!).

So I changed the default label to "None / Free Form Review". This label was already used in the section settings form so translations are available.

**Comment by ajnyga** [comment]
pr https://github.com/pkp/pkp-lib/pull/3649

**Comment by NateWr** [comment]
:+1: Merged!
