### ISSUE TITLE
Keywords and Agencies metadata: when one of the two is mandatory

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#3609]
With reference to the closed issue #3596, now with Ojs version 3.1.1.
If one of the keywords or Agencies metadata is a required field and this field is not filled in, it is notified perfectly but the content of the other field is also deleted (if it was compiled).

**Comment by bozana** [comment]
Hi @eniocarboni, what do you mean with "the content of the other field is also deleted (if it was compiled)" ? Thanks!

**Comment by bozana** [comment]
Ah, I think I see what you mean... the other tagit fields

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3614
ojs master: https://github.com/pkp/ojs/pull/1927 (only submodule update)

pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3615
ojs ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/1928 (only submodule update)

pkp-lib omp-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3616
omp omp-stable-3_1_1: https://github.com/pkp/omp/pull/525 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look?

**Comment by asmecher** [comment]
These tagit controls are such a pain :P Yes, please go ahead, just a couple of minor comments!

**Comment by bozana** [comment]
Hmmm... Actually this should be correct... Hmmm... Could you double check if the changes are in your file lib/pkp/controllers/tab/publicationEntry/PublicationEntryTabHandler.inc.php?

**Comment by eniocarboni** [comment]
Yes checked, there are in the file.

**Comment by bozana** [comment]
Hmmm... I've just checked it in my local master branch -- it should be the same as 3.1.1: I have keywords required and supporting agencies enabled but not required. Then I enter something in the supporting agencies field and nothing in keywords filed. I get the form error message, but the supporting agencies filed input is still there... :-O

**Comment by bozana** [comment]
Did you entered it so that a "tag" is made out of it i.e. adding a coma and a space after a word? Hmmm.... :astonished:

**Comment by eniocarboni** [comment]
Ok, maybe I understand that we are looking at 2 different parts.
If, as an editor, you go to an existing submission and then click on the top in "Metadata", then everything works perfectly (as you describe it).
If, instead, as an author, you creates a new "submission" and you get to step 3 "3-Enter Metadata", then here you have the problem as described in my first comment with reference to the issue #3596
Sorry if I have not explained well

**Comment by bozana** [comment]
Ah, OK, I see... will take a look... forget about that... :-P

**Comment by bozana** [comment]
I added the PRs above. @eniocarboni, would it be possible for you to test if these changes solve the problem: https://github.com/pkp/pkp-lib/pull/3630? THANKS!!!

**Comment by eniocarboni** [comment]
@bozana, yes, the problem no longer exists.
