### ISSUE TITLE
OMP-3.1.1.0 Payment side MENU does not appear

### ISSUE THREAD

**Issue by luisja58** [pkp/pkp-lib#3610]
When active  Payments  in Distribution Settings, the Payments menu does not appear on the left side.
If a user send notification of payment (Manual Fee Payment ), the manager can not see it.

**Comment by asmecher** [comment]
@luisja58, you're correct that the manual payment plugin currently doesn't have an area to manage payments. This plugin isn't currently intended for production use, unless you manually intervene in the database or code a plugin to do so -- is the Paypal plugin not an option?

**Comment by luisja58** [comment]
What we really need is that the user can choose the payment method they want, but if it is not possible, the first choice is to pay in cash (deposit account or bank transfer)

**Comment by NateWr** [comment]
Closing this as outdated.
