### ISSUE TITLE
[OMP-3.1.1.0] Payment send notification of payment Fatal error

### ISSUE THREAD

**Issue by luisja58** [pkp/pkp-lib#3611]
When  a user send notification of payment (Manual Fee Payment ): FATAL ERROR
Solution:
lack of library in lib\pkp\classes\payment\QueuedPaymentDAO.inc.php
add:   import('lib.pkp.classes.payment.QueuedPayment');

**Comment by asmecher** [comment]
@luisja58, are you able to send in a pull request for this? If not, I can take care of it.

**Comment by asmecher** [comment]
Resolved -- thanks for reporting, @luisja58.
