### ISSUE TITLE
[OMP-3.1.1.0] Payment send notification: name of the file is null

### ISSUE THREAD

**Issue by luisja58** [pkp/pkp-lib#3612]
When notification is sent to the press of the paid item, the field name of the file does not appear.
Solution: 
lack of library in: classes/payment/omp/OMPPaymentManager.inc.php
add lib in function getPaymentName
import('lib.pkp.classes.submission.SubmissionFile');

**Comment by asmecher** [comment]
@luisja58, are you able to send in a pull request for this? If not, I can take care of it.

**Comment by asmecher** [comment]
Fixed -- thanks for reporting, @luisja58!
