### ISSUE TITLE
Add link to Review page on Revisions Required email template

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3618]
Could we add a link to the submission's Review page in the body of the Revisions Required email? I have had a large number of authors creating a new submission to upload their revised paper. 

Some text and a link might help guide them in the right direction. E.g.,:

To upload your revised paper, go to the Revisions section of your original submission: 
https://yourjournal.ca/...

**Comment by NateWr** [comment]
This is implemented as part of #5730.
