### ISSUE TITLE
[OJS] Uploading supplementary file revisions fails in some circumstances

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3619]
Hi @bozana  and @asmecher 

Here is a nasty little bug, enjoy :wink: 

OJS 3.0.1 (probably also 3.1.1)

Scenario:
Author uploads revision files (probably applies to other uploading situations as well).
- Upload file A as a new file, select article component "other"
- Upload an almost similar file B and select "this is not a revision of an existing file" and article component "other"
- Continue => OJS asks if this is the same file as file A you just uploaded, because it is so similar (possible duplication detected...)
- Choose the option that the file _is_ the same => continue with upload
- result: file A gets a new revision (there is  a (2) behind the file name) but when you click it you get 500 error. This is because for some reason the second revision of the file is not uploaded at all.

This does not apply if you are uploading a "Article text" just the component "other" and possibly other supplementary files as well.

For a quick fix: I remember that there is a "file similarity" value in the config.inc.php file. What value would be needed there to stop OJS from comparing the files at all?

**Comment by bozana** [comment]
Phew, I am investigating... I think I found the bug... will come back soon...

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3625
ojs master: https://github.com/pkp/ojs/pull/1932 (only submodule update)

**Comment by bozana** [comment]
@ajnyga, could you maybe test the pkp-lib patch?

**Comment by ajnyga** [comment]
Well that was a long movie, but the good guys won in the end!

It worked very well, thank you!

**Comment by bozana** [comment]
OK, then I will rebase, merge and cherry-pick... THANKS!!!
