### ISSUE TITLE
OJS 3.1.1 Submission Library upload link error

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#3622]
see also: https://forum.pkp.sfu.ca/t/ojs-3-1-1-submission-library-upload-link-to-a-black-page

**Comment by defstat** [comment]
@asmecher 

PRs:
pkp-lib: #3623
OJS: pkp/ojs#1931

**Comment by asmecher** [comment]
Thanks, @defstat, please go ahead (and port to `ojs-stable-3_1_1` and `omp-stable-3_1_1` as needed)!

**Comment by defstat** [comment]
@asmecher 
Not sure if I did it correctly. I created 4 new branches, 
1. from pkp-lib/ojs-stable-3_1_1
2. from pkp-lib/omp-stable-3_1_1
3. from ojs/ojs-stable-3_1_1
4. from omp/omp-stable-3_1_1

I CherryPicked the changes from #3623 into 1. and 2. 
I added the submodule update commit on 3. and 4.

I created a PR for each branch

PRs:
[pkp-lib: ojs-stable-3.1.1] : #3669
[pkp-lib: omp-stable-3.1.1] : #3670
[ojs-stable-3.1.1] : pkp/ojs#1955
[omp-stable-3.1.1] : pkp/omp#531

**Comment by asmecher** [comment]
Thanks, @defstat, that's perfect. All merged.
