### ISSUE TITLE
[OJS] bad html on home page 

### ISSUE THREAD

**Issue by stuartyeates** [pkp/pkp-lib#363]
A number of OJS installs have bad HTML on their homepages. This is being generated by OJS in the list of journals being hosted by a server. 

The string is `"<p><p>"` as currently displayed on live sites such as http://ojs.st-andrews.ac.uk/ and http://ojs.victoria.ac.nz/

**Comment by beghelli** [comment]
Thanks Stuart. That content is controlled by users, via tinyMCE plugin, if that's enabled. If users use it only in WYSIWYG mode, then things like duplicated markup can happen. The best solution is to read the markup and manually remove any problems there, thought it might need some HTML knowledge.

**Comment by stuartyeates** [comment]
It seems to me that to generate sane HTML in the way we're trying to do, we need to know what the root element on the tinyMCE-generated content is (span, p, div, etc). 

I think we can do this as described at  http://www.tinymce.com/wiki.php/Configuration:forced_root_block

I'm guessing that this might be a bit of work, as the the tinyMCE plugin appears to assume that all uses are the same.

**Comment by beghelli** [comment]
You don't need to build everything in there, but you can also turn to the html view and check for the markup. Even if you know the root block you can always create something, delete the content and leave the markup still lying there alone.

**Comment by ctgraham** [comment]
I think the core issue here is that the Journal Description should not have been wrapped in a <p> tag at: https://github.com/pkp/ojs/blob/ojs-dev-2_4/templates/index/site.tpl#L43

It should have either been a <div> tag, or nothing.

**Comment by beghelli** [comment]
I agree that div should be better, but I think we are using <p> there also as a way to keep things with the right formating (align, font size, etc). This is not something used only there, it's spread all over the system, so I think that this issue can either be changed to something more general or closed and another one created. Not sure also about the priority to change this, as we are more focused in OJS 3 now.

**Comment by asmecher** [comment]
Dying of old age -- this is an OJS2 bug and doesn't appear to affect OJS3.
