### ISSUE TITLE
Ability to modify email before publishing a new issue

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3633]
When an editor chooses to notify readers when publishing a new issue, they do not see the email text that is going out and do not have the ability to modify the template text. 

It would be helpful if they could see/modify the email before hitting Send and having it go out.

**Comment by ajnyga** [comment]
There is no dedicated template when publishing a new issue. It uses a generic notification template. 

I agree that the message used now is too simple, see: https://github.com/pkp/pkp-lib/issues/2406
Also see

**Comment by librariam** [comment]
+1 from PKP|PS. Having the publish_notify email template is confusing because it implies that modifying the template will modify the new issue notification text when it in fact does not.

**Comment by asmecher** [comment]
This will be implemented as part of https://github.com/pkp/pkp-lib/issues/3646.
