### ISSUE TITLE
Add context to user profile "API Key" tab

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3635]
The "API Key" tab in the user profile may be confusing to users who don't know what it's there for. Some context should be provided. I'd suggest describing briefly what the key can be used for, and what is needed to complete configuration. If there is a permanent location to API documentation, consider linking to that.

**Comment by NateWr** [comment]
I think we shouldn't show the API Key tab in the user profile unless the `api_key_secret` is set in the config file. That should get it out of the way for 99% of users.

I also think there's a case, for now, for only showing it to Admins and Journal Managers. It's still in such a young state, and we're not aware of any third-party integrations. Anyone experimenting with it is likely to be an Admin or Journal Manager, and they may not want to expose it to users right away. When the API is more mature and we start experimenting with meaningful user-facing integrations outside of the app, we can bring it back.

Just my two cents. @asmecher any thoughts?

**Comment by asmecher** [comment]
@NateWr, I'd agree with hiding it unless the `api_key_secret` is enabled. Beyond that, I'd wait for feedback before assuming it was still causing confusion.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
