### ISSUE TITLE
[OJS] Introduce "Publish only" mode to OJS/OMP to simplify workflow

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3639]
Hi,

This is a large change in OJS, but I think that many journals would benefit from it.

There are a lot of journals that use OJS just for publishing purposes, meaning that they do not accept new submissions or use most of the editorial workflow.

These journals usually just use the quicksubmit plugin to add new manuscripts. However, the whole workflow is designed only thinking journals that do receive submissions. I suggest the following steps to better support journals that only publish in OJS:

1. Add new setting to control whether the journal accepts submissions
2. Move Quicksubmit plugin to the core
3. When "publish only" enabled, the "New submission" button in the submissions listing opens Quicksubmit. Only allow access for editors.
4. When "publish only" enabled, the public submissions page does not show the "Login or Register to make a submission" links on the top of the page. Other instructions on the page can still be visible so that the journals can describe how they receive submissions
5. When "publish only" enabled, hide all submission stages except "production"  and hide the stage participants listing (optional).
6. When "publish only" enabled, the "All active" tab is the default submissions listing tab and my queu and Unassigned are hidden (optional).

Probably there are other things that could be taken into consideration, but these changes would simplify OJS a lot for journals that do not need the submissions workflow.

**Comment by fgnievinski** [comment]
maybe it's done later as per https://github.com/pkp/pkp-lib/issues/5702?

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
