### ISSUE TITLE
[OMP] The DOI plugin fails to work for Monographs

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#364]
OMP allows for DOIs at both the Monograph and the Publication Format level.  Right now, only the latter is supported. The PubIdPlugin class currently generates an assertion failure because Monograph is not a supported class type.

**Comment by jnugent** [comment]
Also, this:
https://github.com/jnugent/pkp-lib/commit/071662f92ea2636450d68347b3aa92bf5d5d0483

**Comment by jnugent** [comment]
Alec, mind taking a quick look? Nothing dramatic, just fixing some things that were generating assertions (and putting subjects back in the native export within the ONIX component).

**Comment by asmecher** [comment]
Jason, mind linking to the PR from here?

**Comment by jnugent** [comment]
Yes indeed.  There are two:
OMP: https://github.com/pkp/omp/pull/104
PKP-lib: https://github.com/pkp/pkp-lib/pull/370

These are against master.  It's an easy port afterwards.  Thanks!

**Comment by asmecher** [comment]
Looks fine, Jason -- please go ahead.
