### ISSUE TITLE
When publishing new issue, PUBLISH_NOTIFY template not used

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3646]
I expected the email that goes out to readers when I publish a new issue to be based on the PUBLISH_NOTIFY template, but it does not. Instead, it uses the more basic notification email:

You have a new notification from Maximum Journal of Theme Testing:

An issue has been published.

Link: https://dev.publicknowledgeproject.org/ojs3/uiux/index.php/max/issue/current

Can we use the PUBLISH_NOTIFY template? And provide the editor with the opportunity to tweak the email before sending (which is filed as another issue).

**Comment by teenkung** [comment]
Ok

**Comment by eirikhanssen** [comment]
I just got an email from two of our frustrated journal editors, who are missing this feature of sending a custom email-notification after publishing an issue as was possible in OJS2. They had edited the PUBLISH_NOTIFY template only to discover that it was not used when publishing the issue.

**Comment by ajnyga** [comment]
Is this something that is worth looking at now, or should this be tackled later with a larger notifications/tasks redesign? Or should this be closed because of https://github.com/pkp/pkp-lib/issues/4017 ?

**Comment by asmecher** [comment]
We were talking about this recently -- this one can be incorporated without requiring a rewrite.

**Comment by ajnyga** [comment]
So would you be happy with a solution where I just extend the assignPublicIdentifiersForm and basically add the template text there. The same way regretMessage works now. https://github.com/pkp/ojs/blob/master/templates/controllers/grid/pubIds/form/assignPublicIdentifiersForm.tpl#L26 

We could have a similar control there like here:
<img width="797" alt="Screenshot 2020-03-26 at 21 28 35" src="https://user-images.githubusercontent.com/16347527/77688481-d069b980-6fa8-11ea-9028-76b8357ffcbf.png">
Where the default would not sending the email and selecting the send message option would reveal the email template available for edit.

**Comment by asmecher** [comment]
That form is confusingly named :) but yes, that's a good possibility. One downside: we may get requests for the ability to compose/send that email independently from the issue publication action. To resolve that, maybe instead a new published grid row action called "Notify"?

**Comment by ajnyga** [comment]
So it would only be available in the back issues grid? And all old issues would have that action?

Of course it will take a while for the editors to find it now that they are used to the existing way of sending the notification. But the separate action would be simpler.

**Comment by asmecher** [comment]
I could envision offering both options -- guiding the user to optionally send the email during the publication process, and offering a separate "Notify" action besides.

**Comment by primoz-svetek** [comment]
Do you have any idea when this will be fixed? I hope that you have in mind also a fix for the OJS 3.1.x since not everybody is on the 3.2.x

**Comment by drugurkocak** [comment]
Hi, I made a special email and saved it into PUBLISH_NOTIFY template for the special issue of COVID-19. I would sent a special message to the users and then restore the email template. However, when I published the issue, I saw that users were sent the standard NOTIFICATION email. New notification from {$siteTitle}, A new issu was published. …
System is OJS 3.2.0-3, the situation still looks the same.
Regards,

**Comment by asmecher** [comment]
@drugurkocak, this issue is still open, thus the behaviour you describe is expected. Watch for this issue to be updated.

**Comment by drugurkocak** [comment]
@asmecher Sorry for bothering you. I think the previous comment stating "not everybody is on the 3.2.x" confused me and expected that the situtation should be different. I will be watching all threads, 
Regards,

**Comment by librariam** [comment]
+1 more from PKP|PS, thank you!

**Comment by jmvezic** [comment]
Seeing as "Comprehensive improvements to sending emails" is in plan for version 3.4 (https://pkp.sfu.ca/2021/04/28/here-we-go-whats-planned-for-3-4/) it would be great to have this fix with that release. Our editors were also expecting the "New issue published" template to be sent out instead of the generic one.

**Comment by asmecher** [comment]
@jmvezic, I believe that's the intention; I've scheduled this for 3.4 to reflect that. (There are already some much-improved mass email tools in 3.3 that you can use to send out notifications with better control over the content, but this issue specifically still hasn't been implemented yet.)

**Comment by marcbria** [comment]
Arriving late to the conversation to report that I also got a complain today from a journal (ojs 3.2.1) that modified PUBLISH_NOTIFY expecting to email with this content... but got a simply notification.

As @amandastevens suggested [here](https://github.com/pkp/pkp-lib/issues/5953#issuecomment-770422832), if PUBLUSH_NOTIFY is not used in 3.2 and 3.3 (and feature will be implemented in 3.4), I also suggest removing the template from those releases to avoid confusions.

**Comment by librariam** [comment]
+1 more from PKP|PS to use an email template for the new issue notification

**Comment by Vitaliy-1** [comment]
Was implemented as part of https://github.com/pkp/pkp-lib/issues/7286. When a new issue is published, an automatic email is sent based on `PUBLISH_NOTIFY` template to all (not unsubscribed) users via job batches
