### ISSUE TITLE
Redirecting URL with anchors no working properly when not logged in

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#3650]
Hi,
Troubleshooting OJS2 install I've realized that a HTTP to HTTPS redirect is only working when I am logged in.
If  I am **not** logged im: 
acess this url: http://blakequarterly.org/index.php/blake/article/viewArticle/essick474/essick474html#7
redirects to: https://blakequarterly.org/index.php/blake/article/viewArticle/essick474/essick474html
It looses "#7" final part

if I am **logged** in:
acess this url: http://blakequarterly.org/index.php/blake/article/viewArticle/essick474/essick474html#7
redirects to: https://blakequarterly.org/index.php/blake/article/viewArticle/essick474/essick474html#7
It works properly.

@bozana or @asmecher , it is related to OJS2 but may happens on OJS3 (I have not tested on last one).

**Comment by asmecher** [comment]
@israelcefrin, the anchor (`#whatever` in the URL) should never get sent to the server and thus isn't available to OJS (without introducing some JS fanciness). I don't think the `#7` will get preserved either way.

**Comment by jmacgreg** [comment]
Closing - not a consideration we can take on at this time.
