### ISSUE TITLE
Locale strings for API errors don't seem to be getting translated

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3655]
The API error locale strings never seem to get translated. A response with `api.404` will render as `##api.404##`, which suggests the locale file is not getting loaded.

These are locale strings in the `api.xml` files, in both app and pkp-lib. I've added the `AppLocale::requireLocale` calls, so not sure what's happening.

**Comment by asmecher** [comment]
@NateWr, can you drop me a quick sample URL to demonstrate the problem?

**Comment by NateWr** [comment]
`/<context>/api/v1/submissions/9999` presuming a submission with ID `9999` doesn't exist.

**Comment by bozana** [comment]
@asmecher, and with `/api/v1/users/9999` ?

**Comment by NateWr** [comment]
Woops, that's actually returning a HTML page with the `404 Not Found` message, since our auth system doesn't yet do API responses right. The following should return our API error response message:

```
/anything-but-a-real-context-path/api/v1/submissions
```

**Comment by NateWr** [comment]
And to clarify, this is the response I get to pinging the above:

```
{
    "error": "api.submissions.404.resourceNotFound",
    "errorMessage": "##api.submissions.404.resourceNotFound##"
}
```

**Comment by asmecher** [comment]
Thanks, I see it now. There were duplicate locale component IDs; the patch linked here should resolve it. Cherry-picked so it's in both `ojs-stable-3_1_1` and `master`.
