### ISSUE TITLE
Reviewer's editorial notes made in one journal are visible in all

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3658]
1. A user has the reviewer role in two journals in the same install.
2. An editor in Journal A assigns a reviewer and records Editorial Notes.
3. An editor in Journal B can see the the Editorial Notes recorded by Journal A.

I think the editor in Journal A is unlikely to be aware that comments they make may be available to editors from Journal B, and may not even be aware that Journal B is being run on the same platform.

We should either a) add an entry for editorial notes to each context so that they can't be seen or b) implement a Notes-like approach where each note is saved separately, and only load those relevant to the appropriate context.

I think (b) is more likely to be useful in SaaS model where assistants and reviewers are shared between journals. In that model, it would be easy to specify linked journals for which notes should be shared.

**Comment by asmecher** [comment]
A short term tweak that would serve OK while we consider a better long-term fix: use the `Validation::canAdministerUser` check on the reviewer account, and if it comes back false, don't show the editorial notes.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
