### ISSUE TITLE
Journal statistics from previous years not available if no object was published

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#366]
see: https://github.com/pkp/ojs/commit/f40c57471ebd4cd939c975309f5d2e44910242ab#commitcomment-9955054

**Comment by asmecher** [comment]
You're still working on this, I think, Bruno?

**Comment by beghelli** [comment]
oups, yes, will commit today.

2015-03-06 13:47 GMT-03:00 Alec Smecher <notifications@github.com>:

**Comment by beghelli** [comment]
Can you please review it again Alec? Thanks.

**Comment by asmecher** [comment]
Is there a PR open for this, Bruno?

**Comment by beghelli** [comment]
yes, here https://github.com/pkp/ojs/pull/436

2015-03-06 17:44 GMT-03:00 Alec Smecher <notifications@github.com>:

**Comment by asmecher** [comment]
Merged, thanks!
