### ISSUE TITLE
Obfuscated access restriction for site administrator

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#3662]
There are a few places in the code where the role of the current user is tested with a construct that looks like:
```
if (!$user->hasRole(array(ROLE1, ..., ROLE_ID_SITE_ADMIN), $context->getId())) {
  // PROTECTED ACTION
}
```
, suggesting that a site administrator should be authorized to the action.

However `PKPUser::hasRole()` does not check for the `ROLE_ID_SITE_ADMIN` role as it only compare against the roles _in_ the given context.

For example at https://github.com/pkp/pkp-lib/blob/f42a78802b47682cc94ed142110e0c4d0ce5265f/api/v1/_submissions/PKPBackendSubmissionsHandler.inc.php#L80-L84
As a consequence a site administrator (with no manager role in the journal) is not allowed to view the 'Unassigned', 'All Active' or 'Archived' submissions, contradicting the comment.
The user can still click on the tabs but they are empty.

Tested on OJS 3.1.1.

**Comment by asmecher** [comment]
@ptrckb, you're correct that the `ROLE_ID_SITE_ADMIN` won't be found in `RoleDAO::userHasRole` -- something like this should add it: https://gist.github.com/asmecher/bab85892525ea2d919f38fc52286af8f

However, even forcing `userHasRole` to return `true` won't cause those grids to load for the site admin. @NateWr, mind taking a look?

**Comment by NateWr** [comment]
Thanks @ptrckb! Here are some PRs that should address this. Tests running.

PR:
https://github.com/pkp/pkp-lib/pull/3726
https://github.com/pkp/ojs/pull/1981

(@kaschioudi you may want to look at the OJS PR, as it may impact the OMP API work you're doing.)

**Comment by NateWr** [comment]
All tests passed. @bozana, another one sorry! :)

**Comment by kaschioudi** [comment]
alright @NateWr . thanks for letting me know.

**Comment by bozana** [comment]
@NateWr, everything fine I think, so you can merge and charry-pick/migrate to stable-3_1_1...

**Comment by NateWr** [comment]
Merged to `master`, `ojs-stable-3_1_1` and `omp-stable-3_1_1`.
