### ISSUE TITLE
Missing articleId/submissionId parameters in OJS editorial history events

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#3663]
In OJS 2.4 the article id is not recorded when logging several article events (for example `log.editor.decision`). This results in `articleId` parameters not substituted in the History view.

When upgrading to OJS 3.1.1, the Editorial History then displays unsubstituted `submissionId` parameters (see also #2160).

**Comment by NateWr** [comment]
Closing this as we are no longer working on fixes for 2.x.
