### ISSUE TITLE
Section Editor assigned as an Author (only) can access discussions that they are not participants in

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3666]
I have a General Editor role, is like a Section Editor role with this permissions:
![editorissue](https://user-images.githubusercontent.com/5422984/39658517-c4c8c3ac-4feb-11e8-88fd-ade49c3a2ac0.png)

First problem: A General Editor has permission for edit or delete discussions even when the discussion is not open by him/her, and can edit the content of the message.

You need to remember a Editor can submit a manuscript (in my case General Editors have these roles: General Editor, Author, Reviewer, Reader). 

Second problem: When a General Editor sends a submission as an Author, he/she is able to **view, delete and edit** discussion even when they are not assigned to this discussion.

If you need more info I am happy to help you!

**Comment by NateWr** [comment]
Are you using 3.1.1? We introduced significant permissions changes in #3130 so that permissions are now determined by the user's assigned role in the submission.

If you have a Section Editor who is making a submission, they should _not_ be assigned an editorial role in that submission. They should only be assigned an author role. This should prevent them from seeing submission details that an author would not normally be able to see.

**Comment by t4x0n** [comment]
Yes, I am using 3.1.1! I know about some of this changes and was weird when I found these problems... I thought maybe this was not seen before.

Of course, in this submission, this editor only has Author role. It's possible that issue just happens with past submission, I mean submissions submitted before updated to 3.1.1?  

Please don't close this issue yet; I need to try with another submission to verify, and check if this happened in news submissions, thanks @NateWr

**Comment by NateWr** [comment]
I was able to confirm this. A Section Editor assigned to a submission as an Author (only) is able to see discussions that they are not participants in.

**Comment by t4x0n** [comment]
But only able to see? in my case, I detect this user can see, edit or delete the discussions
![image](https://user-images.githubusercontent.com/5422984/39824777-8972145e-5386-11e8-92ff-dd96bbdfb949.png)

**Comment by NateWr** [comment]
According to `QueriesAccessHelper::getCanListAll()`, managers and subeditors are allowed to see all discussions. I'm wondering if this is too permissive.

Imagine a scenario where an Editor (JM) and Section Editor (SE) are both assigned to a submission. As an Author, I can open a discussion and only assign myself and the Editor (JM). At that point, I think I would have a reasonable expectation that the Section Editor (SE) would not have access to that discussion. However, it appears that they would.

Does anyone have thoughts about whether it's important that a Section Editor (SE) can see every discussion? @asmecher did you have any particular use-cases in mind? Are there any objections to limiting this to the Editor (JM) role?

**Comment by asmecher** [comment]
Long term, our policy for section editors is that they have the same rights as full editors, but only when they've been assigned to the submission. That's recently gotten eroded somewhat, e.g. with the option for section editors to recommend only rather than recording decisions. I have no objection to a change that requires SEs to be assigned in order to list/see discussions but I think some closer-to-the-users feedback might be needed, e.g. @jmacgreg and @stranack.

**Comment by NateWr** [comment]
> I have no objection to a change that requires SEs to be assigned in order to list/see discussions

Can I just clarify, do you mean assigned to the submission? So a SE should be able to see any discussion in a submission to which they're assigned, regardless of whether they're a participant?

I'm a little nervous about how this deviates from the kind of email-like behavior a user might expect, leading users to think a conversation is limited to some participants when it's not. Perhaps we should design the participants list with any assigned JM/SE pre-selected as a participant and unable to be removed?

**Comment by asmecher** [comment]
No, I meant to the discussion, not the submission. (As things currently stand, they get that permission by being assigned to the submission.) Just so I'm clear, you're proposing that full editors/managers should be able to create discussions that *don't* include SEs, and that in that case SE's would not be able to view/participate in the discussion, correct?

**Comment by NateWr** [comment]
> Just so I'm clear, you're proposing that full editors/managers should be able to create discussions that don't include SEs, and that in that case SE's would not be able to view/participate in the discussion, correct?

I'm proposing that _anyone_ assigned to the submission should be able to create a discussion and choose the participants. Only discussion participants would be able to access a discussion, _except_ Journal Managers, who can access any discussion.

(I also think there's a strong case for not giving Journal Managers this surveillance capability, but I appreciate that might impact on the day-to-day work of a lot of journals.)

**Comment by jmacgreg** [comment]
100% agreed with Nate's comment above. This is how I would expect this feature to work.

**Comment by NateWr** [comment]
@jmacgreg can I clarify: do you support the exception which allows Journal Managers to see any discussion?

**Comment by jmacgreg** [comment]
Sorry - I support having any assigned participant being able to start a discussion; and only discussion participants being able to see that discussion. I don't have much of an opinion on whether JMs should be able to see everything or not - I'd want to check with some production journals first (and can do so if you like).

**Comment by ajnyga** [comment]
Just raising the case of open reviews.
There the editor (journal editor or section editor) will probably want to see what the author and the reviewer are discussing.

**Comment by asmecher** [comment]
Agreed re: what you've described for section editors, Nate. I think we'd probably have to do quite a bit of a review and some work if we were to limit full editors, though (not to say it's impossible).

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/3712

Tests only:
https://github.com/pkp/ojs/pull/1974

**Comment by NateWr** [comment]
All checks have passed. @bozana sorry to pile on, but since Alec is away at a conference can you code review this one too?

**Comment by asmecher** [comment]
(Thanks for covering for me, @NateWr and @bozana! I'm trying to keep the backlog from growing too badly over this one.)

**Comment by NateWr** [comment]
Thanks @bozana. Just that one outstanding comment, others address. Tests re-running.

**Comment by NateWr** [comment]
All merged to `master`, `ojs-stable-3_1_1` and `omp-stable-3_1_1`.

**Comment by ajnyga** [comment]
Section editors can not see "comments for the editor" anymore, see https://forum.pkp.sfu.ca/t/ojs-3-1-1-2-comment-for-the-editor-not-showing/46426/6

This is a problem for journals that mainly use section editors instead of actual editors. Especially if submissions are assigned automatically.

**Comment by bozana** [comment]
@NateWr, would then be the solution to treat Pre-Review Discussions differently/extra?

**Comment by bozana** [comment]
Yes, this would then be needed every time an editor is assigned/unassigned?

**Comment by ajnyga** [comment]
Yeah I think so? Of course if there would be a way of adding a "type" to some discussions then you could target those instead of all discussions in a particular stage.

I mean something like

DISCUSSION_TYPE_PRIVATE
DISCUSSION_TYPE_PUBLIC (not a good name, but basically a type of discussion that becomes visible for all stage participants automatically)

At the moment only the "comments of the editor" would use the second type, but we would then have a ready solution to handle similar cases later if they appear.

Just a thought

**Comment by NateWr** [comment]
I'd like to see this as part of the assigning workflow. I think it makes sense to generalise this feature. When assigning a participant, the user should see a list of discussions with checkboxes to select which ones the new participant should be assigned to.

Anyone want to file that?

**Comment by ajnyga** [comment]
How about the automatic assignments. I mean situations where a section editor is responsible for a particular section and receives those submissions based on the section's settings?

**Comment by NateWr** [comment]
Wherever we're assigning users to the comments-to-the-editor discussion, we should make sure automatically assigned section editors are included.

**Comment by ajnyga** [comment]
Yes but the scenario I am thinking is that:
- you have section A with a responsible section editor B
- someone submits to section A and the submission is automatically assigned to the section editor B
- section editor B opens the submission, but does not see the comments to the editor, because she is not participant in the discussion

In these cases the actual editor who can see the comments may not even open the whole submission, because there is already a section editor taking case of it.

**Comment by NateWr** [comment]
Section editor B should be assigned to this discussion when the discussion is created.

**Comment by ajnyga** [comment]
But the discussion is created before the automatic assignment happens. It is created during the submission process in the step 1.

**Comment by t4x0n** [comment]
I think @ajnyga approach is a few more simple for Editors because do not affect the current process, they not need to think what they need to do, keeping the process like they know now

**Comment by NateWr** [comment]
> But the discussion is created before the automatic assignment happens. It is created during the submission process in the step 1.

Then we can update the discussion participants when the submission is completed.

It'd be good to capture any further discussion in its own issue, so I've opened one here: https://github.com/pkp/pkp-lib/issues/3910
