### ISSUE TITLE
[OJS] Task notification after finishing a review. 

### ISSUE THREAD

**Issue by josuevalrob** [pkp/pkp-lib#3668]
After finishing a review by the revisor, there is not the message of a new Task in the profile of the editor. 

Is there any way to enable it?
It is how it should work?
It could be a new feature request?

**Comment by bozana** [comment]
Hi @josuevalrob, thanks! See this issue: https://github.com/pkp/pkp-lib/issues/3423. I think it is considering what you described here. Currently only a notification e-mail is sent, but there will probably also be a task soon. Thus I will close this issue. You can reopen it, if you mean something different that that other issue describes...
