### ISSUE TITLE
[OJS] reviewer history is not ordered by date

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3672]
It's a minimal issue but could cause confusion, screenshots explain the issue:

this is the correct order (blue vector indicate the last entry):
![issueojshistor](https://user-images.githubusercontent.com/5422984/39716950-300aaf86-5208-11e8-960d-2c7a32618fe9.png)

in this case is not ordered:
![sdfdsfsf](https://user-images.githubusercontent.com/5422984/39717020-67882470-5208-11e8-83c1-242fe5306421.png)

**Comment by asmecher** [comment]
@t4x0n, that listing wasn't intended to be sorted, but sorting is quick enough to add. Try the attached patch and let me know if it resolves the issue.

**Comment by t4x0n** [comment]
thanks @asmecher, it works!

**Comment by asmecher** [comment]
Cherry-picked into `master`. Thanks for confirming!
