### ISSUE TITLE
Permit Editoral-level roles to decline workflow assignment

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3678]
Editors/Section Edtiors may want to be able to decline their own workflow assignment. Right now it's technically possible - they can click the "Remove" option for their name in the Participants list, and that will remove them - but it does so non-gracefully and without indication that they've been removed (they aren't provided with any sort of notice, and get an authorization error if they try to click on anything on the page), and there's no message that goes out to any editor/primary contact. This could be finessed a bit, I think. 

(Right now a workaround would be for the E/SE to request removal via Discussion.)

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
