### ISSUE TITLE
reviewReport sl_SI locale copied to the wrong folder

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3681]
for omp-stable-3_1_1 and omp master

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/reviewReport/pull/12
omp-stable-3_1_1: https://github.com/pkp/omp/pull/532
omp master: https://github.com/pkp/omp/pull/533

**Comment by bozana** [comment]
@asmecher, correct so, especially for omp-stable-3_1_1?

**Comment by asmecher** [comment]
Yes, thanks!
