### ISSUE TITLE
OMP-3.1.1.0 Duplicate books in list of a category

### ISSUE THREAD

**Issue by luisja58** [pkp/pkp-lib#3684]
If there are 2 languages in OMP, the list of books in a category appears duplicated.
The same book appears 2 times.
  In the total catalog listing it appears well

**Comment by bozana** [comment]
Hi @luisja58, I cannot reproduce it with the current omp-stable-3_1_1 branch. Could you maybe explain it more, when exactly this happens? -- for me to try to reproduce it...

**Comment by luisja58** [comment]
It seems that it is solved. In the omp311-1 version it appears well.
