### ISSUE TITLE
False review overdue notifications after upgrading to OJS3.1

### ISSUE THREAD

**Issue by mczirfusz** [pkp/pkp-lib#3685]
We recently upgraded from OJS2.3.6 via 2.4.8 to OJS 3.1.0-1.

For reviews which were initiated in the previous system but finished in OJS3, reviewers receive automatic overdue notification, although they submitted their reviews before the due date. 

These overdue notifications are not shown in the UI under Editorial history. 

Moreover, the timing of the notification is also quite strange: the users submitted their reviews end of March (this was approximately the due date), but received this notification only in the past days. (Automatic notifications are sent 7 days after expiration.)

Please indicate if you need more information to track this down,

Also referencing #2173 (issue 4 looks similar).

**Comment by bozana** [comment]
Hmmm...
Could you please give us an example how the review_assignments DB table row looks like for such a case, i.e. all the dates (date_assigned, date_notified, date_confirmed, date_completed, date_due, date_response_due, date_reminded), but also reminder_was_automatic and declined columns?
THANKS!!!

**Comment by mczirfusz** [comment]
Hi @bozana, here is one example
 
```
review_id 	submission_id 	reviewer_id 	competing_interests 	recommendation 	date_assigned 	date_notified 	date_confirmed 	date_completed 	date_acknowledged 	date_due 	date_response_due 	last_modified 	reminder_was_automatic 	declined 	replaced 	reviewer_file_id 	date_rated 	date_reminded 	quality 	review_method 	round 	step 	review_form_id 	review_round_id 	stage_id 	unconsidered 	

613	3036	1864	NULL	3	2018-01-25 22:09:29	2018-01-25 22:10:51	2018-01-25 22:20:51	2018-03-20 17:23:44	2018-03-20 23:18:06	2018-03-25 00:00:00	2018-03-25 00:00:00	2018-03-20 23:18:06	0	0	0	NULL	NULL	NULL	0	2	1	4	6	477	3	0	

```
And an automatic overdue review notification was received on Friday, May 11, 2018 10:52 AM (the user forwarded this e-mail to us, so it exits, but actually I do not see this e-mail server-side).

Additional info: as far as I remember we switched on automatic overdue notifications in our OJS 3 system and we did not use this function in our OJS 2 installation.

**Comment by bozana** [comment]
Hi @mczirfusz 

I copied your example, so I will delete it -- not to stay public.
It actually looks good so I do not understand why the reminder was sent :-\
Could you execute this SQL on your DB:
```
SELECT	r.*, r2.review_revision, u.first_name, u.last_name
FROM	review_assignments r
LEFT JOIN users u ON (r.reviewer_id = u.user_id)
LEFT JOIN review_rounds r2 ON (r.review_round_id = r2.review_round_id)
WHERE r.date_notified IS NOT NULL AND r.date_completed IS NULL AND r.declined <> 1
ORDER BY r.submission_id
```
Could it maybe be that the email notification was for another review assignment (of the same reviewer)?
Hmmm...

**Comment by mczirfusz** [comment]
thanks! 
I run the SQL query, it has some results, but none of them corresponds to the example above or that of the reviewers who indicated this strange behaviour.
(I checked the email notification, and it belongs to the example above - we use the one-click link version so it was easy to check.)

**Comment by mczirfusz** [comment]
I am deeply sorry, our mistake!
It turned out that the e-mails were sent by a backup copy we used during the upgrading process but have forgotten to switch it off.
