### ISSUE TITLE
Allow journals/presses to disable option for new users to register as reviewers

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3696]
Can we provide journals and presses with the option to disable the ability for new users to register as reviewers when registering? Perhaps configurable under Site Access Options?

**Comment by NateWr** [comment]
Self-registration can be turned off for any user group. Go to Users & Roles > Find the role > Edit > Role Options and un-check "Allow user self-registration".

(Closing but feel free to re-open if you want to discuss more.)
