### ISSUE TITLE
Improve / correct manuscript status in submission list for editors

### ISSUE THREAD

**Issue by heike-r** [pkp/pkp-lib#3697]
There are several things that would improve the submission listing in the editor's dashboard:

1. (this is actually a bug?) All reviewers have declined the request and the submission status says 'All reviews are in and a decision is needed'. I guess this is based on the fact that there are no reviews pending? Maybe add a condition like "and at least 1 review is in" for this status message? For the case that all reviewers declined (no review pending and no review in), make the status "a reviewer needs to be assigned".

2. When revisions are requested by the editor, the status sometimes says "revisions have been requested" and sometimes there is no status listed. I have not figured out, why its sometimes this way and sometimes that way. Also, do not display a warning symbol (triangle with exclamation mark) when the status is "revision have been requested" . This gives the impression that an editor action is required, which is not the case.

3. Change the counting of reviews from "reviews in / total open requests" to "reviews in / reviewer's confirmation pending / total open requests" or to "reviews in / review requests accepted / total open requests". This would give the editor a much better overview of how many reviewers actually accepted the request and if he either has to remind reviewers or recruit new ones.

Edit: this concerns OJS 3.1.0.

**Comment by heike-r** [comment]
Oh, I forgot: this concerns OJS 3.1.0.

**Comment by amandastevens** [comment]
A PKP|PS hosted client also pointed out that #1 is misleading and made another suggestion related to #3: "The editors also finds the message 'a review is overdue' to be confusing, as it is often the case that it refers to a reviewer being late to respond to the request rather than being late to submit the review."

**Comment by asmecher** [comment]
On point 1: I've tweaked the wording from "All reviews are in..." to "All reviewers have responded..." -- not a complete solution but a small start.

**Comment by NateWr** [comment]
I'm going to close this as outdated. These issues may have been resolved. But if there are any outstanding problems in 3.3.0-x or later, please file a new issue for each request.
