### ISSUE TITLE
either auto-save or have a "draft" option for reviews

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#3698]
From two people in the community at workshops I have heard that they would like to have an option to save a review for later. That they have heard complaints that reviewers start writing in the review, but it takes them a long time and that, if they wait too long, then when they hit save they lose all of their work. This happens elsewhere on the web, but it'd be nice if we could help address it with an auto-save/draft mode for reviews.

**Comment by asmecher** [comment]
I'm curious what version of OJS they're using when they encounter these data losses. There are several candidates, either fixed or already described in detail:

- https://github.com/pkp/pkp-lib/issues/2830
- https://github.com/pkp/pkp-lib/issues/2428
- https://github.com/pkp/pkp-lib/issues/2417

**Comment by jalperin** [comment]
Some version of 3. But, I can also attest as a reviewer, that I would also
like to be able to save the review and come back to it later.

Juan

**Comment by asmecher** [comment]
Noted. But if you do get the chance to grab a specific version number, it would be helpful.

**Comment by gcienfuegos** [comment]
Hi
The version is 3.1.0.1

**Comment by asmecher** [comment]
@NateWr, in your work on rewriting the forms, have you thought about auto-save functionality? The use case I find most compelling is the review form, where it may take quite a long time for a user to complete their input and the frustration from lost data can be very high. Currently the CSRF check limits input to an hour by default. (ping @ajnyga/https://github.com/pkp/pkp-lib/issues/2428)

**Comment by NateWr** [comment]
I've thought about using the browser's localStorage for some things. But I think for key things like this a proper autosave would be important -- and we should actually persist that autosave to the database.

It would be trivial to add an `autosaveInterval` prop to a form component which, when added, would fire off a save request at that interval. But how we should treat that request will differ according to context.

For reviews, we'll want to save the existing data but ensure we don't trip any flags which indicate the review is "done". In other cases that may not matter or we may not want to persist autosave data in the db at all (eg - context settings shouldn't be saved until the user "commits" the changes).

**Comment by ajnyga** [comment]
@NateWr sorry I missed this issue here.

I am planning to solve this because it is really affecting how our editors trust the system. Any last minute advice / ideas before I start working?

**Comment by NateWr** [comment]
I'm just thinking off the top of my head here, but I think you can just add a separate Save for Later button on that stage of the review. When clicked, it would save everything but not set the `date_completed` column in the database. Am I right in thinking that as long as this column is empty it is considered incomplete?

Then you'll just need to double-check that this is handled correctly everywhere we determine active/complete reviews. I can think of these places:

- Reviews grid should not show it as complete.
- Submissions lists should not count it as a complete review.
- API responses should not count it as a complete review (I think the backend submissions API may include these details).
- Open Reviews plugin should handle this where appropriate.
- I think there may be Review Reports that calculate data that will need to be taken into account.
- Reviewer selection grid (and API that services it) should count it as an Active Review until final submission, and not as a Completed Review until final submission.

**Comment by ajnyga** [comment]
Hi,

> When clicked, it would save everything but not set the date_completed column in the database. Am I right in thinking that as long as this column is empty it is considered incomplete?

I think that all those places rely on the existence of the date_completed value. What makes the autosave maybe complicated are the custom review forms. I have not used them much, so have to look into them. The basic review form should be easy enough.

I am thinking that I will first add a manual ajax save button to the bottom of the form. After that we can add javascript that will trigger that button for example every 60 seconds.

I started to think that should we have a parent function for `autoSave` here https://github.com/pkp/pkp-lib/blob/master/classes/form/Form.inc.php, but can not really come up with any other worthy use cases?

**Comment by ajnyga** [comment]
(fyi @jalperin the original issue with the loss of data you described is actually solved now here https://github.com/pkp/pkp-lib/issues/2428 but I will see if we can have the save button there as well in any case)

**Comment by NateWr** [comment]
> I am thinking that I will first add a manual ajax save button to the bottom of the form. After that we can add javascript that will trigger that button for example every 60 seconds.

A Save for Later button should provide a flying notification ("Review saved for later.") but an autosave should not. :+1:

**Comment by ajnyga** [comment]
We now have an almost ready fix for this:
https://github.com/pkp/ojs/pull/2694
https://github.com/pkp/pkp-lib/pull/5669

This does not include the autosave function, but it would be easy to add. I made a test where an autosave is triggered every 5 minutes in the background. When autosave is triggered, the reviewer does not see a notification like they would see when clicking the save button manually. 

However, there is a possible security issue involved: with autosave on, the user session would continue indefinitely in an open browser window. Not sure if that is a security issue though? (Also thinking whether it would be possible to have an autosave trigger once just before the session ends and the redirect the reviewer to a login page?)

Also: should we have a short description above the buttons now? And if yes, can some native speaker write a good text there ;)

**Comment by NateWr** [comment]
Let's go without autosave for now. I'd like to try it with the Save for Later option and see if people still run into the timeouts before implementing an autosave feature. If we find that there is still a UX issue arising from the review process, then we can address that separately.

**Comment by asmecher** [comment]
Looks good, @ajnyga; I added one comment that needs resolution before merging. I'm OK without a description above the buttons. The more you write, the less people read, and I think "save for later" (or perhaps "save draft") is already quite clear.

**Comment by ajnyga** [comment]
fixed/commented back: https://github.com/pkp/ojs/pull/2694

This does not seem to need a OMP pr

**Comment by asmecher** [comment]
Thanks, @ajnyga, that looks good to me. Ready for merge?

**Comment by ajnyga** [comment]
I am, but apparently pkp-lib now has a merge conflict?

**Comment by asmecher** [comment]
Merged PRs for `pkp-lib` and `ojs` (the latter manually due to merge conflict). Thanks, @ajnyga!
