### ISSUE TITLE
Make a "performed review" certificate available for download

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#3700]
In Latin America (and maybe elsewhere), people want to get a document (a PDF) that they can use to show they really did a peer review. This is similar to the certificates that people get when they go to conferences here. 

This would probably not be a core feature, but could be implemented as a plugin? 

Perhaps a good candidate for us helping to define an approach and then trying to see if someone from the community can make a first pass?

**Comment by asmecher** [comment]
Yes, it could be implemented as a plugin in any number of ways (e.g. a report plugin, an import/export plugin, or a generic plugin, just OTOH). I was recently contacted by a community member who may already have something like this written; waiting for details.

**Comment by NateWr** [comment]
Closing this in favor of https://github.com/pkp/pkp-lib/issues/3501.
