### ISSUE TITLE
Add an email notification to submitting author and all co-authors when their manuscript appears online

### ISSUE THREAD

**Issue by heike-r** [pkp/pkp-lib#3701]
It would be useful to have an email notification to all authors of a submission the moment this submission appears online. We do publish-as-you-go with OJS 3.1.0. This notification would give the authors a closure with the publishing of their work. We currently do this notification via the discussion tool but can only address the submitting author, not the co-authors.The text could be something like this:

Dear Authors,

your article “{$submissionTitle}”  has been published online and is freely accessible here

 _link to submission page_

It was a pleasure working with you on publishing your research. You are welcome to submit any future manuscripts you deem suitable for the _Journal X_.

Sincerely,
_Editor's name_

**Comment by NateWr** [comment]
Moved comment to https://github.com/pkp/pkp-lib/issues/3472. Closing.
