### ISSUE TITLE
Abstract class Submission

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3704]
If instantiating the `Submission` class: https://github.com/pkp/pkp-lib/blob/master/classes/submission/SubmissionDAO.inc.php#L91
is it needed to be abstract?
https://github.com/pkp/pkp-lib/blob/master/classes/submission/Submission.inc.php#L35

**Comment by asmecher** [comment]
Yes -- the `Submission` class is the parent of the Article class (OJS) and the `Monograph` class (OMP). If you want to instantiate one of these objects, use e.g.:

    $submissionDao = Application::getSubmissionDAO();
    $submission = $submissionDao->newDataObject();

But I'm not clear on the context of what you want to accomplish, so this might lead you astray :)

**Comment by asmecher** [comment]
(If this is just a clarification about that linked line of code, then it's never run because the subclasses all override it -- but I agree it would probably be clearer if that function were itself marked `abstract`.)
