### ISSUE TITLE
[OJS] Missing galley file breaks Crossref automatic deposts

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3706]
Hi @bozana 

Scenario:
User adds a new galley to an article then removes the actual file attached to the galley, but then leaves the galley place holder to the galleys grid.
The user then proceeds to publish the article and gives it a DOI.

What happens is that here: https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php#L186 the code does not get a value for `$galleyFile` and therefore line 187 gives a fatal error.

Solution:

```
$galleyFile = $galley->getFile();
if ($galleyFile) {
	$genre = $genreDao->getById($galleyFile->getGenreId());					
	if ($genre->getSupplementary()) {
		if ($galley->getStoredPubid('doi')) {
			// construct the array key with galley best ID and locale needed for the component node
			$componentGalleys[] = $galley;
		}
	} else {
		$submissionGalleys[] = $galley;
	}
}
```

Another question is that are there other places in the code where having a galley placeholder assumes that there is an actual file attached to that placeholder?

ArticleCrossrefXmlFilter

**Comment by bozana** [comment]
PRs:
master: https://github.com/pkp/ojs/pull/1970
ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/1971

**Comment by bozana** [comment]
Thanks a lot @ajnyga! I thought I had considered that :-P 
I checked the other places as well -- I think only these two are affected...
