### ISSUE TITLE
Display CC license badge for legacy CC license

### ISSUE THREAD

**Issue by mittinatten** [pkp/pkp-lib#3707]
Hi,
A lot of our journals have old articles published under CC 3.0 licenses. After upgrading to OJS 3.1.1 from OJS 2, no license badge is displayed for these articles. Adding them is simple: https://github.com/ubbdst/pkp-lib/commit/360710d4052434879d2a9ada393e13b9b750238b. I suspect others could have use for this patch, or a more general version including all legacy CC licenses.

Simon

**Comment by NateWr** [comment]
Yes, we've had a similar request before and just need a list of licenses to add: https://github.com/pkp/pkp-lib/issues/1818

Can you submit a PR for this? I'll close this as a duplicate and you can link your PR to the older issue.

(Also, if you can add any of the newer CC licenses that'd be great.)
