### ISSUE TITLE
Email notification for an Editor about review submitted from Reviewers and revised manuscript from Authors

### ISSUE THREAD

**Issue by Julio977** [pkp/pkp-lib#3714]
Hi, 
I have OJS 3.1.1. and I do not see in the email templates the possibility to receive an email that would inform automatically the editor of a journal when a Reviewer submits his comments to a manuscript or when an Author submits his revised version of a manuscript.
I apologize if both functions are already in place and in this case I would like to know how to make them work. Otherwise, I woud suggest to implement OJS 3.1.1 with these features.
Currently, I have to check everyday, even twice a day to see whether a reviewer has submitted his/her comments and whether an author has submitted a revised version of his/her manuscript.
Many thanks.

**Comment by bozana** [comment]
Hi @Julio977 

I think the following issues are related to this one:

https://github.com/pkp/pkp-lib/issues/3423: There was a problem when the custom review forms were used (is this also your case?) that was fixed and will be available in the next OJS version, that is coming soon, in a week or two. 
Here, there is no e-mail template, but the notification e-mail with the notification `<message key="notification.type.reviewerComment">A reviewer has commented on "{$title}".</message>`, to all editors assigned to the submission. 

https://github.com/pkp/pkp-lib/issues/3278: This fixes here should send the e-mail template REVISED_VERSION_NOTIFY to all editors assigned to the submission, when the author uploads a revision after the editor's decisions “Request revisions” or "Resubmit for review". This fix first came in 3.1.1 so could you see if you have that e-mail template in you DB email_templates_default i.e. email_templates_default_data, or in the e-mail template list (Settings > Workflow > Emails) -- it should be inserted with the upgrade.
For further improvements that will come see this issue https://github.com/pkp/pkp-lib/issues/2665.

Thus, I will close this issue for now...

**Comment by Julio977** [comment]
Hi @bozana, 

thank you for your reply.
Yes, I fabricated a custom review form for my journal.
Will be waiting for the next OJS version.
Thanks again.
Julio977
