### ISSUE TITLE
OMP-3.1.1.0 In view site there is no exit menu

### ISSUE THREAD

**Issue by luisja58** [pkp/pkp-lib#3717]
When a user has login in the View Site screen and wants to exit, the upper menu for EXIT does not appear

**Comment by asmecher** [comment]
That's intentional, @luisja58 -- you can get back into the workflow by following the Dashboard link.

**Comment by luisja58** [comment]
Not always a user wants to see the Dashboard. In fact, when a user buys a book, he does not want to see the Dashboard, but Manual Payment Instructions and since he had to identify, then he must exit.

**Comment by asmecher** [comment]
@luisja58, I actually consider the "view site" button to be a kind of "exit" button, and the administrative/dashboard area to be the area that is being left. But it sounds like there's a particular path through the system that you're finding confusing -- can you describe it?

**Comment by luisja58** [comment]
In OJS311 if a user buys an item, the system asks for login. Then the system presents the screen Manual Fee Payment (if manual fee option). The user has the option to exit (top corner).
 I expected the OMP to have the same behavior.
