### ISSUE TITLE
[OJS 3.1.1] RSS Feed plugin requires its own locale key for the displayed title

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#3718]
The current title displayed ('_Current Issue_') is misleading: some users try to open the current issue by clicking those links.

I'd propose something like 'RSS feed (Current Issue)'.
If there is a stand-alone plugin for announcements: 'RSS feed (Announcements)'.

See the discussion here: https://forum.pkp.sfu.ca/t/plugin-rename-rss-feed/13241/7

**Comment by Ph-We** [comment]
I am really sorry, @asmecher. And I would really be willing to help. 
But I'm afraid I'm not that tech-savvy((

**Comment by Ph-We** [comment]
@asmecher, that really might be an option if some users did not prefer to have to different feeds: for issues and for announcements. I swear I've seen such journals. 
However, I could not find the 'Announcements Feed' plugin you mentioned [here](https://forum.pkp.sfu.ca/t/last-announcement-in-block/24994/4).

**Comment by NateWr** [comment]
The original report from the forum is for an OJS 2.x journal. I'm going to close this as outdated but feel free to reopen is this is still an issue that needs to be addressed.
