### ISSUE TITLE
Introduce reviewer ratings and gossip

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#372]
Currently the rateReviewerOnQuality option is in setup, but never used. Either implement it (permitting ratings on reviewers), or hide it from the setup interface.

**Comment by asmecher** [comment]
Hidden for OJS 3.0b; rescheduling for a more fulsome solution at 3.0.

**Comment by prechelt** [comment]
In a few months, I will be able to offer a much more comprehensive approach to this topic:
https://reviewqualitycollector.org

**Comment by asmecher** [comment]
The reviewer gossip field also needs restoration.

**Comment by NateWr** [comment]
This was implemented as part of #2894
