### ISSUE TITLE
[OJS] clarify language on DOI/DOAJ registration

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#3720]
pkp/ojs#1967 claims that the language around DOI registration might be unclear. The strings right now state that it might take a short amount of time. Apparently this might be misunderstood as if there was some manual editorial task involved. The reason that DOIs might be registered a little later is mostly the cronjob configuration, maybe also latency, connection problems at the journal or the DOI registration site etc. I have shortly discussed this with @bozana and suggest to add a little piece of information to clarify what is meant here. 

(needs to be applied to OMP, too, after resolving this for OJS)

**Comment by bozana** [comment]
@mtub, I think this is good. I would have one question though: Could we maybe have something like `(depending on your cronjob execution)` or `(depending on your cronjob execution time)`  or `(e.g. depending on your cronjob configuration)`? -- Some users might use Acron plugin, which is triggered/executed/run when an user access a journal home page, an issue or an article page. Thus, in that case (when Acron plugin and not cron is used), it is even more unpredictable (not exactly configurable) when the scheduled task will be executed/done.
Or maybe "cronjob configuration" is enough and the users should just roughly know a reason... ?
THANKS A LOT!!!

**Comment by mtub** [comment]
Ah, good catch. I'd prefer to just add a "e.g." - there's the acron plugin, but also other reasons might lead to a delay, connection problems, problems at the DOI registration server etc.. Will update the PR and let you merge it.

**Comment by bozana** [comment]
PRs:
master: https://github.com/pkp/ojs/pull/1977
ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/1979
