### ISSUE TITLE
[OJS 3.1.1] missing locale key grid.action.schedulePublication

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#3721]
In Production stage, is missing a string of text grid.action.schedulePublication for html title:
![captura de pantalla 2018-05-22 00 22 57](https://user-images.githubusercontent.com/5422984/40342283-d9ce84ca-5d57-11e8-8bcb-df4caf840ff8.png)

(Edit: also `grid.action.viewEmail` https://github.com/pkp/pkp-lib/issues/3742)

**Comment by NateWr** [comment]
Hmm, I couldn't find any reference to that locale key in the current `master` branch of OJS. I did find one for `editor.article.schedulePublication`. What version are you on?

**Comment by bozana** [comment]
Ah, I believe those grid.action... are always missing... They seem to be constructed...

**Comment by t4x0n** [comment]
I have OJS 3.1.1

**Comment by NateWr** [comment]
> Ah, I believe those grid.action... are always missing... They seem to be constructed...

Strange though. This is outside of a grid... Is it attached to a `title` attribute or something?

**Comment by t4x0n** [comment]
yes, is a title attribute

**Comment by NateWr** [comment]
This button is no longer used from OJS 3.2.x and above.
