### ISSUE TITLE
"Subeditors" are not introduced to users

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#3723]
The gossip code mentions subeditors: https://github.com/pkp/pkp-lib/blob/32ddeb9cb92ac2800cef493e6dfce192732673c2/locale/en_US/user.xml#L45 

But they are not mentioned anywhere else, so users might not know what kind of users subeditors are.

Tagging @ajnyga , @NateWr

**Comment by NateWr** [comment]
Good point, and since we can't know what the actual user group names will be, it's pretty hard to be explicit. What do you think about:

> ...make visible to other editors...

Is it ambiguous enough that someone would interpret it safely as "any editorial-like role"?

**Comment by mtub** [comment]
Since we are covering remarks about other people I think it would be best to be as verbose as possible to avoid surprises. How about 

> … make visible to administrators, journal managers and all types of editors …

?

But journal manager is OJS language, so maybe 

> … make visible to administrators, managers, and all types of editors …

or even longer

> … make visible to administrators, journal and press managers, and all types of editors…

Maybe editors will suffice, but then I'd still recommend to put all three groups in there (admin, managament, editors).

**Comment by NateWr** [comment]
> Record notes about this reviewer that you would like to make visible to other administrators, managers and all editors. Notes will be visible for future review assignments.

That ok? I wanted to stay away from "types of" because I think users might not know what we mean by "types".

PR:
https://github.com/pkp/pkp-lib/pull/3728

**Comment by mtub** [comment]
Sounds good, thanks!

**Comment by NateWr** [comment]
Merged to `master` and `ojs-stable-3_1_1`.
