### ISSUE TITLE
Additional features for Open Reviews

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3738]
This is a ticket for the remaining enhancements planned here: https://github.com/pkp/pkp-lib/issues/2976
- [ ] Allow all reviewers to see the editorial decision and other reviews (request from a journal using the open review feature)
- [ ] Show discussion status in the submissions list for reviewers
- [ ] In blind and double blind prevent discussion messages iniated by the editor where both authors and reviewers get selected. **Do we want this?**
- [ ] Notify authors when new open reviews are ready...
- [ ] ... and add a new discussion
- [ ] Add fontawesome icons to visualize the review methods (https://codepen.io/anon/pen/LOerEW)

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making one or several proposal(s) in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.

You're also welcome to open an issue if you are actively working on some part of this.
