### ISSUE TITLE
[OMP] 3.1.1 upgrade scripts hard-code PostgreSQL-incompatible SQL statements

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#3739]
```
[data: dbscripts/xml/upgrade/3.1.1_update.xml]
ERROR: Upgrade failed: DB: ERROR:  column "ra" of relation "review_assignments" does not exist
LINE 1: UPDATE review_assignments ra SET ra.quality = NULL WHERE ra....
                                         ^
```
[This statement](https://github.com/pkp/omp/blob/master/dbscripts/xml/upgrade/3.1.1_update.xml#L47) is the problem, though I may find others after I fix this one.

**Comment by asmecher** [comment]
@crism, there's also a MySQL-related change in the PR (https://github.com/pkp/omp/pull/544/files) -- have you tested that with MySQL?

**Comment by crism** [comment]
I didn’t test it with MySQL, no… the table alias was only removed within the SET clause, not in any WHERE or anything else.

**Comment by crism** [comment]
Oh, sorry… I see. The change was within a `<query driver="mysql[i]">`. Um. I may have gotten carried away… though this syntax should be legal in any SQL system. I can take it out if we can’t easily test it. (I’d prefer to keep this change, though—it seems like a lot of these changes are copy-and-paste, and having good exemplars will minimize problems like this in the future.)

**Comment by asmecher** [comment]
Those MySQL queries are already implemented differently than the PostgreSQL ones, and they work for me with a local test. I'd rather avoid that change. I'll pull in your PostgreSQL change, though!

**Comment by asmecher** [comment]
Ported the equivalent OJS change (removing table aliases completely): https://github.com/pkp/omp/pull/544#issuecomment-393301267
