### ISSUE TITLE
[OJS 3.1.1] when a submission enter to review stage the files are duplicated

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3741]
Each time a submission enter in review stage the files are copied into a new folder named review, but not only they are copied, also are duplicated with names like this:

22-12--1-4-20171225.docx (without file ID )
22-12-193-1-4-20171225.docx (with file ID, in this case is 193)

I don't know... this is intentional?

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3747
ojs master: https://github.com/pkp/ojs/pull/1988 (submodule update only)

**Comment by bozana** [comment]
Yes, thanks @t4x0n! It seems that the file is copied twice, once before inserting it into the DB when the file ID is not known, and then after i.e. during the insertion in the DB, to the correct file path.

@asmecher, could you take a look? If OK, I can cherry-pick to stable-3_1_1 for the coming release...

**Comment by t4x0n** [comment]
Oh, I see... excellent! thanks to you for solving the issue!

**Comment by asmecher** [comment]
@bozana, please go ahead and merge for `master`, but I'd rather not merge into the OJS or OMP stable branches until we've had a bit more time to test for boundary conditions. The worst case here is unnecessary use of disk space, so I think the risk of introducing a regression is worse.
