### ISSUE TITLE
[OJS 3.1.1] missing locale key grid.action.viewEmail

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3742]
I found another locale key missed (grid.action.viewEmail) for `title` attribute at Editorial History

see the image:
![otro-mas](https://user-images.githubusercontent.com/5422984/40556441-a0a0c97c-601a-11e8-87b6-5eb027fcd88c.png)

**Comment by asmecher** [comment]
@NateWr, tagging you because I think you were active on another of these.

**Comment by NateWr** [comment]
Closing in favor of #3721.

**Comment by t4x0n** [comment]
sorry @NateWr but this locale key is another one

I found two locale key missing: grid.action.viewEmail and grid.action.schedulePublication

**Comment by NateWr** [comment]
Yes, they're all related to the same base problem, which is that they appear to be auto-generated. They'll all be connected to one fix when we figure it out. It may be that I hammered these locale keys by mistake. Or maybe they never existed...
