### ISSUE TITLE
[OJS] Establishing "Journal Collections" within an OJS Installation 

### ISSUE THREAD

**Issue by willinsky** [pkp/pkp-lib#3743]
Arising from reported editor concerns over their ability to log in as users, such as reviewers, who belong to multiple journals in an installation and to enable journals in related areas to form more of a publishing community or cooperative within a single OJS installation, the following suggestions are made to facilitate the setting up journal collections within an OJS installation:

1. From a list of other journals in the installation, including those that have already formed a "journal collection," a journal manager (JM) can (a) select and request to form a "journal collection" (to be named) with other titles, with all selected journals' JMs notified with an email option to join the journal collection that includes list of journal invited and all that this entails; or (b) the JM can select an existing journal collection, see what this entails, and send a request to the collection initiator to join. 
2. A collection entails (a) access to a reviewer pool shared by all journals; (b) ability of editors and JM to login-as for their users who are also part of the collected journals (e.g., all reviewers); (c) ability of editors to transfer a submission prior to acceptance to another journal in the collection, where it will appear as a new submission with a tag indicating the journal from which it had been forwarded, and a "history" that includes all previous steps taken, including access to all reviews submitted, and a note from the original editor (which was prompted on that editor clicking "Transfer to Another Journal in this Collection"; (d) articles in the journal collection are eligible to appear in a "Related Articles" feature on each article's home page, based on keywords; (e) under setup for entering Instructions to Authors, JMs have the option of establishing the Journal Collection's Common Instructions to Authors, if they initiated the collection or selecting it for their instructions on joining the collection.  
3. A collection is identified on the OJS installations' list of journals, and offers its own common landing page listing the collection's titles. 
4. On About the Journal, there is an entry for This Journal Belongs to the [Name] Journal Collection, which lists with links all of the journal titles in the collection.

**Comment by asmecher** [comment]
@willinsky, before jumping into design, I'm wondering if the original reporter of the problem wasn't actually encountering a bug in their specific version of OJS that was preventing them from logging in as a user. For example, there was a recent adjustment that has apparently caused the check to be pickier than intended: https://github.com/pkp/pkp-lib/commit/0fcb191b6bdbf3e5c9bc3fba35ca2b42c1397b93

**Comment by asmecher** [comment]
Also tagging @NateWr, who's been wrestling with the site-wide user administration toolset recently.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
