### ISSUE TITLE
Upgrade OJS 2.4.8.1 to 3.1.1.0 supplementary files lost for activ submissions

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#3744]
When I update migrate our OJS instance from 2.4.8.1 to 3.1.1.0, supplementary files of submissions in progress get lost.

We instruct our authors to upload program code and reproduction data as supplementary files during submission. These files then show up on the summary and editing pages. For published submissions, these files are migrated into galleys on the production stage and show up correctly on the public website.

For running submissions, ie submissions that are currently under review, the supplementary files seem to get lost on migration. There are no galleys on the (inactive) production stage and no entries in the submission files grid. This is problematic for us, because these files (code/replication material) should be   reviewed together with the manuscript.

**Comment by bozana** [comment]
Hi @pkel, thanks! 
I'll take a look. Could you see if they are in your database table submission_files?

**Comment by bozana** [comment]
OK, as far as I can see, those files would have file_stage = 10 (proof stage) but no assoc_id and assoc_type...

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1987

**Comment by asmecher** [comment]
In other words: thanks, please go ahead!

**Comment by bozana** [comment]
@asmecher -- I think not all supp files were available for review but those this option is selected for i.e. those that have show_reviewers = 1 in the DB table article_supplementary_files, ok?

**Comment by asmecher** [comment]
Hi @bozana -- thanks, I will have to refresh my memory during upgrade testing!

**Comment by pkel** [comment]
My migration ran into the following problem with the patch applied on top of 3.1.1.0

```
[code: Installer Installer::convertSupplementaryFiles]
[code: Installer Installer::provideSupplementaryFilesForReview]
[03-Jun-2018 19:59:37 UTC] PHP Warning:  assert(): Assertion failed in /var/www/html/lib/pkp/classes/submission/PKPSubmissionFileDAO.inc.php on line 285
[03-Jun-2018 19:59:37 UTC] ojs2: Invalid file!
```

**Comment by pkel** [comment]
Okay, I see. Latest revision is somehow less or equal zero. This might be due to false migration to ojs2 years back. I will check and keep you up to date.

**Comment by pkel** [comment]
The following query on the migration databaser after the above failure returns the emtpy set:

``` 
select * from (select max(revision) as max_revision from submission_files group by file_id) max where max_revision < 1
```
I cannot see why `getLatestRevisionNumber` failed on assertion `$latestRevision > 0`.

**Comment by pkel** [comment]
Dear @bozana, did you see my comments? I can't reopen the issue...

It think that your `provideSupplementaryFilesForReview` functions calls `getLatestRevisionNumber(file_id)` with a `file_id` that is not present in the `submission_files` table. How comes?

**Comment by bozana** [comment]
Sorry @pkel, I was traveling, now I can take a look...

**Comment by bozana** [comment]
Could it be, that you have an entry in your `article_supplementary_files` table with a `file_id` that is not in the `articles_files` table? -- This seems to be the problem, if the function `getLatestRevisionNumber` gets the file_id that does not exist. Could you please double check that? E.g. with this SQL:
`SELECT * FROM article_supplementary_files WHERE file_id NOT IN (SELECT file_id FROM article_files)`
The SQL from the function `provideSupplementaryFilesForReview` https://github.com/pkp/ojs/blob/master/classes/install/Upgrade.inc.php#L1479 finds all supp files that should be presented to the reviewers and are not remore supp files. The `file_id` that is then provided to the function `getLatestRevisionNumber` is from that SQL result.
And unfortunately I have no idea how it could happen that there is an entry in the `article_supplementary_files` but not in `article_files` :-\

**Comment by pkel** [comment]
```
> SELECT * FROM article_supplementary_files WHERE file_id NOT IN (SELECT file_id FROM article_files);
+---------+---------+------------+-------------+----------+------------+--------------+----------------+---------------------+-----+
| supp_id | file_id | article_id | type        | language | remote_url | date_created | show_reviewers | date_submitted      | seq |
+---------+---------+------------+-------------+----------+------------+--------------+----------------+---------------------+-----+
|    1949 |       0 |       2428 |             |          | NULL       | 2015-11-12   |              1 | 2015-11-12 07:58:16 |   0 |
|    2150 |       0 |       2500 | NULL        | NULL     | NULL       | 2016-01-05   |           NULL | 2016-01-05 19:17:23 |   0 |
|    2327 |       0 |       2574 | NULL        | NULL     | NULL       | 2016-03-02   |           NULL | 2016-03-02 16:45:36 |   0 |
|    2341 |       0 |       2529 |             |          | NULL       | 2016-03-08   |              1 | 2016-03-08 01:45:14 |   1 |
|    2343 |       0 |       2580 | NULL        | NULL     | NULL       | 2016-03-08   |           NULL | 2016-03-08 11:10:25 |   0 |
|    2360 |       0 |       2585 | Source Text | en       | NULL       | 2016-03-10   |              0 | 2016-03-10 23:30:45 |   1 |
|    2372 |       0 |       2533 |             |          | NULL       | 0000-00-00   |              0 | 2016-03-14 13:18:32 |   4 |
|    2452 |       0 |       2621 | NULL        | NULL     | NULL       | 2016-03-30   |           NULL | 2016-03-30 11:53:49 |   0 |
|    2997 |       0 |       2876 | NULL        | NULL     | NULL       | 2016-10-09   |           NULL | 2016-10-09 15:56:51 |   2 |
|    2999 |       0 |       2876 | NULL        | NULL     | NULL       | 2016-10-09   |           NULL | 2016-10-09 15:57:59 |   4 |
|    3001 |       0 |       2876 | NULL        | NULL     | NULL       | 2016-10-09   |           NULL | 2016-10-09 15:58:43 |   6 |
|    3002 |       0 |       2876 | NULL        | NULL     | NULL       | 2016-10-09   |           NULL | 2016-10-09 16:00:46 |   7 |
|    3670 |       0 |       3186 |             |          | NULL       | 2017-07-01   |              1 | 2017-07-01 12:51:35 |   2 |
|    3743 |       0 |       2621 |             |          | NULL       | 2017-08-01   |              1 | 2017-08-01 14:23:37 |   7 |
|    3780 |       0 |       3236 | NULL        | NULL     | NULL       | 2017-08-18   |           NULL | 2017-08-18 19:04:55 |   3 |
|    3926 |       0 |       3096 |             |          | NULL       | 2017-10-14   |              1 | 2017-10-14 20:33:53 |   3 |
|    3956 |       0 |       3289 | NULL        | NULL     | NULL       | 2017-10-22   |           NULL | 2017-10-22 06:27:20 |   3 |
|    4203 |       0 |       3345 | NULL        | NULL     | NULL       | 2017-12-15   |           NULL | 2017-12-15 14:16:18 |   2 |
|    4313 |       0 |       3364 |             |          | NULL       | 2018-03-05   |              0 | 2018-03-05 20:03:51 |   0 |
|    4480 |       0 |       3448 |             |          | NULL       | 2018-05-05   |              1 | 2018-05-05 16:28:03 |   1 |
|    4536 |       0 |       3476 | NULL        | NULL     | NULL       | 2018-06-07   |           NULL | 2018-06-07 00:06:41 |   0 |
+---------+---------+------------+-------------+----------+------------+--------------+----------------+---------------------+-----+
```

This is from our live system running 2.4.8 something. The timestamps indicate, that this was caused by OJS and not by our migration from another system to OJS.

**Comment by bozana** [comment]
I will close this issue and open the other one for that...
