### ISSUE TITLE
Template variable currentUrl returns wrong values for journals using custom base_url's

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3745]
Hi,

While doing a plugin I noticed that the `currentUrl` variable (basically `request->getCompleteUrl()`) returns wrong values for journals that have a custom base_url setting.

For example I have a context with base_url `journal1.domain.com`, but the value that I get is `journal1.domain.com/journal1/`.

Could this be fixed and/or is there an alternative variable I could use to get the current url of an OJS page inside a template?

**Comment by asmecher** [comment]
@ajnyga, can you describe what you need the current URL for? We've generally avoided the need for this kind of variable as a rule.

**Comment by ajnyga** [comment]
I actually needed it for the cookieNotification plugin I made, but realized that I can just add the parameter alone to the href and the browser will add that to the existing url. So I have no immediate need for this.

A larger picture here is that domain handling is something that could be refined in OJS in general. I am thinking something similar you have with Wordpress Multi Site feature. This would be extremely handy for SAAS providers but a huge change to the existing code. Maybe we should have a separate ticket for this?

**Comment by NateWr** [comment]
> Maybe we should have a separate ticket for this?

Probably. Can you also describe in more detail how the WordPress multi-site feature works, and which parts you would like to be available in OJS? My understanding is that it doesn't do domain mapping out-of-the-box, but that could be outdated info.

**Comment by ajnyga** [comment]
I have to check what the current status of WP domain mapping is. At least it supports subdomains (you of course need wildcards) so that you can define the url's from the admin panel. At the moment you need to edit the config.inc.php and if you have one subdomain then you need to define a base_url for ALL journals you have even if they use the regular url path. 

So getting rid of the config.inc.php editing and adding a native support + clear instructions for subdomains would be step 1. 

But I will do a ticket when my vacation is over :beach_umbrella:

**Comment by NateWr** [comment]
@ajnyga do you know if this is still an issue in 3.3.0-x?

**Comment by NateWr** [comment]
Closing this as outdated.
