### ISSUE TITLE
Pagination in search results: redundant pagination numbers

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3746]
When the query results items number (on the search page) goes beyond 1 page, there are redundant pagination numbers. OJS 3.1.1 
![search_pagination](https://user-images.githubusercontent.com/20665587/40621322-04697350-62a5-11e8-9565-6eea09ac39da.jpg)

**Comment by NateWr** [comment]
This looks familiar. Can you reproduce with the default theme?

**Comment by Vitaliy-1** [comment]
Yep

**Comment by asmecher** [comment]
Hrm, I can't reproduce this myself, either on the `ojs-stable-3_1_1` codebase or on `master`. @Vitaliy-1, is this still happening?

**Comment by Vitaliy-1** [comment]
@asmecher 
Yeah. E.g., way to reproduce on the search page: have enough data to paginate the results for the search query on several pages. [Example](http://dev-ojs.e-medjournal.com/index.php/sjt/search/search?query=article&searchJournal=1&authors=&title=&abstract=&galleyFullText=&discipline=&subject=&type=&coverage=&indexTerms=&dateFromMonth=&dateFromDay=&dateFromYear=&dateToMonth=&dateToDay=&dateToYear=&orderBy=score&orderDir=desc&searchPage=2#results) -> I'll keep the default theme active there for a couple of days.

**Comment by Vitaliy-1** [comment]
The problem is in [this method](https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L1069): `$smarty->getTemplateVars('itemsPerPage');` not returns actual number that is entered in the journal settings. In my case, it returns the one entered in the config file. 

I have rewritten that part of code with: 
```
$request = Application::getRequest();
$context = $request->getContext();

if (isset($params['itemsPerPage'])) {
  $itemsPerPage = $params['itemsPerPage'];
} elseif ($context) {
  $itemsPerPage = $context->getSetting('itemsPerPage');
} else {
  $itemsPerPage = Config::getVar('interface', 'items_per_page');
}
		
if (!is_numeric($itemsPerPage)) $itemsPerPage=25;
```
I used OJS-3.1.1-4 for testing. But as you say that is not reproducible in our case, I'll explore it more closely.

**Comment by Vitaliy-1** [comment]
@asmecher I've got it! 
In OJS 3.1.1-4 template variable `itemsPerPage` is assigned [here](https://github.com/pkp/pkp-lib/blob/ojs-stable-3_1_1/classes/template/PKPTemplateManager.inc.php#L363) but is not being overwritten [here](https://github.com/pkp/ojs/blob/ojs-stable-3_1_1/classes/template/TemplateManager.inc.php#L82). That's why `$smarty->get_template_vars('itemsPerPage');` returns result from the config.

But it is not the case for OJS master branch, because `TemplateManager` class overloads `__initialize()` method of the parent and no longer uses parent`s `__construct()`. The problem can be reproduced on the master branch only by switching to the former approach of inheritance.

**Comment by NateWr** [comment]
:+1:

**Comment by asmecher** [comment]
@Vitaliy-1, are you sure this affects `ojs-stable-3_1_1`? I don't see any references to `__initialize` there.

**Comment by Vitaliy-1** [comment]
I've compared master with the latest stable release. [This line](https://github.com/pkp/ojs/blob/master/classes/template/TemplateManager.inc.php#L27) in master makes the difference in comparison to this in [ojs-stable-3_1_1](https://github.com/pkp/ojs/blob/ojs-stable-3_1_1/classes/template/TemplateManager.inc.php#L28). That variable could be rewritten or not depending on what method is overloaded.

**Comment by Vitaliy-1** [comment]
Does that make sense? :)

**Comment by asmecher** [comment]
Fixed also in `ojs-stable-3_1_1` and `omp-stable-3_1_1`, thanks!
