### ISSUE TITLE
[OJS] In PKP PLN plugin, add date agreed to to terms of use exported with deposit

### ISSUE THREAD

**Issue by mjordan** [pkp/pkp-lib#375]
The PKP PLN plugin exports (in a simple XML file) the terms of use that the journal manager agrees to and packages them up with the issue content in the deposit Bag. Currently, we add an updated date attribute to each of the terms. We also need to add an agreed-to-on date attribute.

**Comment by asmecher** [comment]
Mark, I'm scheduling this for 2.4.7 -- but if it's suitable for 2.4.6 and is ready soon, I might be able to shoehorn it in.

**Comment by mjordan** [comment]
Michael is taking a look this morning, let's see what his assessment of the work involved is.

**Comment by asmecher** [comment]
Closing.
