### ISSUE TITLE
Passing invalid sort parameter executes malformed SQL

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#3754]
In 2.4.8, we form the SQL here without checking the result of `$this->getSortMapping($sortBy)`, which [could be null](https://github.com/pkp/ojs/blob/a8f3bd9ead5d9b28635d7ed183706a466dcdaf10/classes/security/RoleDAO.inc.php#L544):
https://github.com/pkp/ojs/blob/a8f3bd9ead5d9b28635d7ed183706a466dcdaf10/classes/security/RoleDAO.inc.php#L211
and
https://github.com/pkp/ojs/blob/a8f3bd9ead5d9b28635d7ed183706a466dcdaf10/classes/security/RoleDAO.inc.php#L279

Input to these functions does not guarantee a mapping of the `$sort` string.

Similarly, in 3.x:
https://github.com/pkp/pkp-lib/blob/37ae1318f17e6a33717ca85758d3013b533f4006/classes/user/PKPUserDAO.inc.php#L579
and
https://github.com/pkp/pkp-lib/blob/c3984f132c5822d8be07c6808c982929f87363cb/classes/security/RoleDAO.inc.php#L191

To reproduce in 2.4.8:
User Home -> Journal Manager -> Users Enrolled in this Journal -> (sort by a column) -> (replace `sort` parameter in URL with invalid string)

**Comment by asmecher** [comment]
Merged -- thanks, @ctgraham!
