### ISSUE TITLE
[OJS 3.1.1.0] TinyMCE calls for google font even when enable_cdn is disabled

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3759]
In to share as little data as possible we disabled the _enable_cdn_ option in the config. But it turns out that the backend still makes calls to `//fonts.googleapis.com/css?family=Noto+Sans:400,400italic,700,700italic`.

As far as I can see the call is made because the `plugins/generic/tinymce/styles/content.css` has the import:

`@import url('//fonts.googleapis.com/css?family=Noto+Sans:400,400italic,700,700italic');`

I would have assumed that the google fonts would be disabled in the front- and backend when disabling _enable_cdn_ (especially because of the advise to disable it because of GDPR). But I'm not quite shure how this can be disabled here.

**Comment by asmecher** [comment]
@MarHerUMR, at a glance it looks like there's a separate Noto Sans import that is dependent on the CDN setting being enabled -- you should be able to remove the reference in `plugins/generic/tinymce/styles/content.css` without any negative effects. Could you try this and confirm?

**Comment by NateWr** [comment]
`plugins/generic/tinymce/styles/content.css` loads styles that are only applied in the iframe of the tinymce editor. That means that the noto font isn't loaded separately, and removing it from `content.css` will cause the content inside the editor to not be styled properly.

However, @MarHerUMR, if you are already disabling the CDN, then you won't have this font anyway, so you're probably safe removing that line in `content.css` for the time being.

We'll probably need to figure out a solution that takes `enable_cdn` into account when loading the TinyMCE content CSS file. I'll take this into account with the TinyMCE work I'm doing in #3594.

**Comment by NateWr** [comment]
Ooh, it supports multiple stylesheets. :pray: https://www.tinymce.com/docs-3x/reference/configuration/Configuration3x@content_css/ Ok, let me address this real quick.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/3767

Tests:
https://github.com/pkp/ojs/pull/1999

**Comment by NateWr** [comment]
This needs a commit to the `tinymce` plugin to add the new/modified CSS.

**Comment by NateWr** [comment]
This was addressed as part of #3594
