### ISSUE TITLE
Image upload in TinyMCE hangs

### ISSUE THREAD

**Issue by rcgillis** [pkp/pkp-lib#3760]
It looks as though when you go to add an image in, say, the page footer or any other part of the setup process, the image upload hangs without any resolution. 
<img width="1038" alt="screen shot 2018-06-01 at 10 33 49 pm" src="https://user-images.githubusercontent.com/5053214/40869153-36d53474-65ec-11e8-93d1-0baad18b52a2.png">. Have tested in OJS instances that are running on 3.1.1 on two separate instances and two different server environments.

**Comment by Vitaliy-1** [comment]
Works fine on my OJS 3.1.1 instances (PHP 7.2 Ubuntu server and local machine with Windows). Is there any relevant information in PHP logs?

**Comment by rcgillis** [comment]
Ok, so apparently a fix for this is to add a `site` folder in `public` - but most users are not going to know how to do this.

**Comment by NateWr** [comment]
It is probably the case that that folder is created automatically as part of other actions (eg - logo upload), and so _usually_ exists. But in your case the sequence of actions meant it hadn't been created yet.

Worth getting this fixed but if we're not getting lots of reports of it, it's probably only occurring in edge cases.

**Comment by asmecher** [comment]
@rcgillis, I think OJS is already coded to do that upon installation (https://github.com/pkp/pkp-lib/blob/master/classes/install/PKPInstall.inc.php#L100..L102) -- are you sure the directory didn't get lost during some kind of administrative activity?

**Comment by jmacgreg** [comment]
Closing - was an issue with the public files dir being missing.
