### ISSUE TITLE
[OJS 3.1.1-1] nine missed plugins?

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3763]
I don't know if is some intentional, or these plugins are deprecated... but...

At the version of OJS 3.1.1-1, these plugins are not available:

Authorization Plugins: 
- LDAP 

Generic Plugin:
- Lucene Search Plugin
- Announcement Feed Plugin
- phpMyVisites Plugin
- Recommend Similar Articles
- Browse
- Backup Plugin
- External Feeds

Report Plugins:
- Subscriptions Report

**Comment by NateWr** [comment]
Yes, the `master` branch includes plugins that are not ready for release. The build script excludes them when creating a release package. You can review the exclusions here:

https://github.com/pkp/ojs/blob/master/tools/buildpkg.sh

**Comment by t4x0n** [comment]
thanks @NateWr for the explanation! I'm sorry if I ask too much but, we just have to wait for a new release to get these plugins?

**Comment by NateWr** [comment]
I don't actually know what the plans are for these. Some of them are in-progress, I think (eg - Lucerne). Others will probably retired in favor of other approaches (eg - Browse is superseded by BrowseBySection and other browsing plugins will follow).

If you have questions about a specific plugin, or are interested in porting one from OJS 2 -> OJS 3, you can search for issues related to that plugin. If none exist, create an issue and start a discussion.

**Comment by t4x0n** [comment]
Ok, I understand now... thanks!!
