### ISSUE TITLE
[OJS 3.1.1-1] QuickSubmit plugin does not change message "Can be upgraded"

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#3764]
Even after making the plugin upgrade, the message "Can be upgraded" not change:
![image](https://user-images.githubusercontent.com/5422984/40884043-47ca35ca-66d9-11e8-8d5c-abc1d023369f.png)

I think in OJS 3.1.1 this was similar

**Comment by isgrim** [comment]
https://github.com/pkp/pkp-lib/issues/4090 Seems related and maybe already fixed?

**Comment by asmecher** [comment]
See also https://github.com/pkp/pkp-lib/issues/3967. @carzamora, I'd suggest upgrading to the latest release and seeing if this is still an issue.

**Comment by israelcefrin** [comment]
Hi @asmecher, I've made a reasonable amount of upgrades this week and this wrong message doesn't show up in OJS3.1.2 anymore. It is working fine. 
Just adding this note to let you know that I will close this issue which is fixed.
