### ISSUE TITLE
README file: update localization information

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3765]
README file has wrong information, this folders `help/en_US` and `rt/en_US` not exist and are referenced in this location in the file:

```
Localization
------------
To add support for other languages, the following sets of XML files must be
localized and placed in an appropriately named directory (using ISO locale 
codes, e.g. "fr_FR", is recommended):

	* locale/en_US
	* lib/pkp/locale/en_US
	* help/en_US
	* registry/locale/en_US
	* rt/en_US
	* plugins/[plugin category]/[plugin name]/locale, where applicable
```
maybe `help/en_US` is really `docs/manual/en`?  but `rt/en_US` I don't know, maybe was in OJS 2?

**Comment by asmecher** [comment]
Thanks, @t4x0n, I've corrected that documentation -- though we do have plans for a localization manual that will replace the brief section in README.
