### ISSUE TITLE
Improve theme capabilities

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#377]
* Add a class to body element to permit targeting of specific pages in themes
* Permit easy overrides of built-in templates with theme-supplied templates
* Improve contract for front-end templates (e.g. can we auto-document smarty templates?)

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/omp/pull/105
https://github.com/pkp/pkp-lib/pull/378

**Comment by asmecher** [comment]
@jnugent, mind reviewing this?

**Comment by asmecher** [comment]
A third PR (this one for OJS master): https://github.com/pkp/ojs/pull/442

**Comment by jnugent** [comment]
Looks great, Alec.  I had a few comments, but no quibbles with the code.  Merge away.

**Comment by asmecher** [comment]
Thanks, Jason! Merged.
