### ISSUE TITLE
[OMP] Keep insertion order for chapters

### ISSUE THREAD

**Issue by isgrim** [pkp/pkp-lib#3772]
Hello PKP Team and contributors,

student workers and staff using OMP to enter volumes with a large amount of chapters ( > 10 ) found it very annoying that you have to manually arrange the chapters, even if you add the chapters in the correct order.

I looked in to the code for the [ChapterDAO](https://github.com/pkp/omp/blob/master/classes/monograph/ChapterDAO.inc.php) and [ChapterForm](https://github.com/pkp/omp/blob/master/controllers/grid/users/chapter/form/ChapterForm.inc.php) and it seems the initial sequence number is never set for a chapter.

Is it possible to keep the insertion order by initialising the chapter with the next sequence number?

Thanks for your great work and greetings from Heidelberg, Germany

Nils Weiher

**Comment by asmecher** [comment]
Hi @isgrim -- yes, we already have a pattern for that, but it seems like that pattern wasn't applied in this case. Here's an example:

```
$query->setSequence(REALLY_BIG_NUMBER);
$queryDao->insertObject($query);
$queryDao->resequence($assocType, $assocId);
```

See `lib/pkp/controllers/grid/queries/form/QueryForm.inc.php`. Would you mind opening a PR to adapt this to chapters? I'd be happy to review/merge.

**Comment by isgrim** [comment]
I will work on this as soon as I find some time.

**Comment by isgrim** [comment]
@asmecher Hi Alec,
I created a PR for omp-stable-3_1_1 with the fix.

**Comment by asmecher** [comment]
Thanks again, @isgrim!
