### ISSUE TITLE
Review and standardize all stats/reports terminology

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3774]
Eg.: downloads vs. views; submission file vs. galley file; article page vs. abstract page; and so on. We should clarify and standardized these in the reports and in any public stats display (eg. "All downloads" hover-over in the article download visualization).

**Comment by librariam** [comment]
+1 from PKP|PS re confusion about "submission file" vs "article" vs "galley" in Custom Report filters.

**Comment by NateWr** [comment]
Closing this in favor of https://github.com/pkp/pkp-lib/issues/7318, where the custom report generator is being rebuilt to use the new statistics API.
