### ISSUE TITLE
Move usage stats plugin into its own app-agnostic repository

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3775]
As part of removing the `plugins`/`lib/pkp/plugins` split, this plugin should be migrated to its own repository and made application-agnostic.

Partial motivation: https://github.com/asmecher/pkp-lib/commit/84b58e93745b85b07ded13bc72891ee9da9ea0c6#r29262817

**Comment by bozana** [comment]
@asmecher, would it be OK to add a function getApplicationName to the Application class, to differentiate a few things? Or shall I rather use other instruments? :-)

**Comment by bozana** [comment]
Ah, I see the PKPApplication already have getName()...

**Comment by bozana** [comment]
@asmecher, here are the current changes:
new repository: https://github.com/bozana/usageStats
needed changes in 
pkp-lib: https://github.com/bozana/pkp-lib/commit/2af78599c77fcfbd8ede1d2c21e207eb4284422b
ojs: https://github.com/pkp/ojs/compare/master...bozana:3775

Currently the OJS submodule points to my repository, thus I would first like to push my new repository usageStats to the new pkp repository, then I will adapt/update the links and make a PR for pkp-lib, OJS and OMP. OK?
Could you please create a new repository "usageStats" in pkp GitHub and give me the access to it?
Would you maybe also like to somehow review the code?

Thanks!!!

**Comment by asmecher** [comment]
Thanks, @bozana, I've cloned `usageStats` over to https://github.com/pkp/usageStats and granted you admin rights.

The `pkp-lib` and `ojs` repo changes look like plain removals, and I like those -- please let me know when you're ready for a review of the new code, though be warned that I don't know this aspect of OJS well at all!

**Comment by bozana** [comment]
@asmecher, I haven't changed the code, just the structure, maybe just this you could review:
-- Now there is only one class UsageStatsLoader and UsageStatsPlugin, and they contain application specific functions (parts). For example: I use this kind of construct to differentiate between the applications, e.g. https://github.com/pkp/usageStats/blob/master/UsageStatsLoader.inc.php#L256-L267 or https://github.com/pkp/usageStats/blob/master/UsageStatsLoader.inc.php#L442-L451. 
-- I left OJSUsageStatsReportPlugin.inc.php, OMPUsageStatsReportPlugin.inc.php, and PKPUsageStatsReportPlugin.inc.php as they were, and I am differentiating which one to call here: https://github.com/pkp/usageStats/blob/master/UsageStatsPlugin.inc.php#L38-L74.
-- There are a few application specific locale keys, so I added ".ojs2" i.e. ".omp" to them, and I provide the application name to the templates, like e.g.:
https://github.com/pkp/usageStats/blob/master/locale/en_US/locale.xml#L79-L80
https://github.com/pkp/usageStats/blob/master/templates/privacyInformation.tpl#L13 (`$applicationName` variable here)
-- the submodule "lib/counterBots" is now in the repository usageStats, and OJS and OMP will contain the submodule "plugins/generic/usageStats"

OK so?

**Comment by asmecher** [comment]
@bozana, yes, those look like OK ways to proceed. If you think it's worth enriching the `Application` object with some more tools to help, go ahead -- but I don't see those yet. We'll probably improve these aspects iteratively if we find more plugins working this way. Please go ahead!

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/3921
https://github.com/pkp/ojs/pull/2061

New usageStats repository/submodule: https://github.com/pkp/usageStats
