### ISSUE TITLE
Eventually consider base_url change in usage statistics

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3777]
s. https://forum.pkp.sfu.ca/t/reprocessing-usage-stats-after-base-url-has-changed/45596

**Comment by NateWr** [comment]
@bozana I think that the changes we're making to how usage statistics are recorded will mean that we no longer need to consider this, right? Can I close this issue?

**Comment by bozana** [comment]
Yes, true, thus closing... Thanks!!!
