### ISSUE TITLE
Remove unused default context settings

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3778]
The default settings for a context in `registry/journalSettings.xml` include a number of settings which I believe are not used anywhere. I did an audit of OJS and found the following:

```
copyeditInstructions
refLinkInstructions
metaCitations
keywordsEnabledSubmission
keywordsEnabledWorkflow
```

As well as the reading tools, which I believe are deprecated:

```
rtAbstract
rtCaptureCite
rtViewMetadata
rtSupplementaryFiles
rtPrinterFriendly
rtDefineTerms
rtAddComment
rtEmailAuthor
rtEmailOthers
```

Does anyone know any reason why these shouldn't be removed, including their associated locale strings?

(If no objections, I'll do a similar audit for OMP.)

**Comment by bozana** [comment]
I believe the keywordsEnabledSubmission and keywordsEnabledWorkflow are still in use, s. Settings > Workflow > Submission...

**Comment by NateWr** [comment]
These were removed as part of #3594.
