### ISSUE TITLE
possibility to set ssl version in WebService

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3779]
s. https://github.com/pkp/pkp-lib/issues/1959

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3780
ojs ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/2005 (submodule update only)

pkp-lib omp-stable-3_1_1: 
omp omp-stable-3_1_1:  (submodule update only)

pkp-lib master:
ojs master:  (submodule update only)
omp master:  (submodule update only)

**Comment by bozana** [comment]
@asmecher, could you take a look? If OK, I will cherry-pick to those other branches... THANKS!!!

**Comment by asmecher** [comment]
@bozana , that looks fine -- though I don't see anything in the PRs that actually uses the capabilities yet!

**Comment by bozana** [comment]
Yes, this class seems not to be currently used in OJS/OMP core. I will use it in the new ALM plugin... Can I then merge?

**Comment by asmecher** [comment]
Yes, please go ahead!
