### ISSUE TITLE
Corresponding author and contact email on article

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#3782]
A number of users and hosted clients have asked to have the option to indicate the corresponding author for an article and display their contact information on the article page in OJS 3.x.

Author contact information can be linked to through an ORCID profile if the author has entered their ORCID ID in their OJS user profile, but ORCID profiles are not always available or complete.

https://forum.pkp.sfu.ca/t/display-author-email/2317
https://forum.pkp.sfu.ca/t/ojs-3-0-2-display-corresponding-author/29993
https://forum.pkp.sfu.ca/t/how-to-display-or-highlight-a-corresponding-author-name-and-details/37690
https://forum.pkp.sfu.ca/t/solved-corresponding-author-name-and-affiliation-show-on-article-page/39849

**Comment by heike-r** [comment]
We have the experience that the corresponding author named on a manuscript is not always the submitting author, who uploads the manuscript.  Please consider this, when working further on this issue.

**Comment by fgnievinski** [comment]
It'd be useful to offer this as a theme configuration option.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
