### ISSUE TITLE
no migration of active supp files with file_id=0

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3783]
in ojs 2 a supp file could be created without uploading a file. that file would have file_id = 0. consider that for the migration -- the possibility that file_id can be 0 also if it is not a remote supp file -- those files will/can not be migrated...
s. https://github.com/pkp/pkp-lib/issues/3744#issuecomment-395052113

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/2008
ojs ojs_stable_3_1_1: https://github.com/pkp/ojs/pull/2009

**Comment by bozana** [comment]
@pkel, you can use the ojs_stable-3_1_1 patch, if you want... THANKS!!!

**Comment by pkel** [comment]
Perfekt, thanks. I will try the patch and report back.

**Comment by bozana** [comment]
@pkel, did the patch worked? Can I merge it? THANKS!

**Comment by pkel** [comment]
Sorry. I obviously forgot about the "... and report back" part.

**The patch worked. The upgrade went through.**

Thanks again.

**Comment by asmecher** [comment]
@bozana, did this get included in OJS 3.1.1-2 and/or OMP 3.1.1-3? If not, could you move the milestone to OJS 3.1.1-4?
