### ISSUE TITLE
consider site primary locale and the submission locale change

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3784]
For the issue #2958 ...

**Comment by bozana** [comment]
maybe this would be good to consider in 3.1.2...

**Comment by asmecher** [comment]
Sure, if you like!

**Comment by bozana** [comment]
PRs:
stable-3_1_2:
pkp-lib: https://github.com/pkp/pkp-lib/pull/4520
ojs: https://github.com/pkp/ojs/pull/2300 (only submodule update)
omp: (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR?

**Comment by asmecher** [comment]
Thanks, @bozana, I suggested a change to the locale key but otherwise it looks good!
