### ISSUE TITLE
[OJS 3.1.1-2] Editors can't Read Review with default form

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3788]
When you use the default form for reviews and the Reviewer send a recommendation, the Editor is not able to read any comment.
This is what I see as Editor:
![image](https://user-images.githubusercontent.com/5422984/41395363-655822b4-6f7b-11e8-83a2-17f5d88e749f.png)

**Comment by asmecher** [comment]
@t4x0n, what version of OJS is this? Please include this in issues you create.

**Comment by t4x0n** [comment]
it's a clean installation of 3.1.1-2

**Comment by bozana** [comment]
Hi @t4x0n,
I've just tested it with my local installation, using ojs-stable-3_1_1 branch and I could not reproduce it :-\
Could you maybe see where the reviewer entered his/her comments exactly?
Are you logged in as an editor that article is assigned to?
Was maybe a review form assigned to that review assignment?
Hmmm.... :thinking: 
Thanks!!!

**Comment by t4x0n** [comment]
mmm this is good, now I can't reproduce it!  

I think my problem was a server problem, maybe Comodo WAF, if the last word in the form is finished in `or`  the form content is not uploaded, so the forms were uploaded empty in this case! 

I'm closing this issue, sorry.
