### ISSUE TITLE
[OJS 3.1] Migration from 2: file history empty

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#3790]
During migration from OJS 2.4.8 to OJS 3.1.1-1 file upload date is lost or at least OJS3 does not show when files have been uploaded.

![files](https://user-images.githubusercontent.com/11337857/41405795-eaf82a50-6fca-11e8-9189-932c1b8f04e0.png)
![info](https://user-images.githubusercontent.com/11337857/41405797-ee169f8c-6fca-11e8-9233-8859f88c18cf.png)

Our investigation showed, that no entries to `event_log` table were added during migration. (Two files have been uploaded using the new version.)

```
select assoc_type, count(*) as count from event_log group by assoc_type;
+------------+-------+
| assoc_type | count |
+------------+-------+
|        515 |     2 |
|    1048585 | 13254 |
+------------+-------+
```

The correct file upload date is stored in `submission_files.date_modified`, but is not presented in the OJS3 Interface.

**Comment by asmecher** [comment]
@pkel, there are both file-specific event logs, and submission-wide event logs. I don't believe OJS changes which entries are allocated to each, so the OJS 2.x event log data is essentially the same as the OJS 3.x data for migrated submissions. Do you see the file uploads logged in the submission-wide event log?

**Comment by pkel** [comment]
File specific event logs have `assoc_type = 515` as far as I can judge. No such entries are generated during migration. The submissions Editorial History shows the uploads. I think that the Editorial History is built from `assoc_type = 1048585`, right?

**Comment by bozana** [comment]
Yes, the event_log table in OJS 2 only contained entries for assoc_type = 257 i.e. ASSOC_TYPE_ARTICLE. Those were migrated to 1048585 in OJS 3. So I am not sure if there is a possibility to differentiate those event logs and migrate them as event logs for files wit the assoc_type = 515 i.e. ASSOC_TYPE_SUBMISSION_FILE...

**Comment by pkel** [comment]
OJS3 adds multiple event_log entries per uploaded file. One with ASSOC_TYPE_ARTICLE and one with ASSOC_TYPE_SUBMISSION_FILE.  I think the editorial history is constructed from filtering the `event_log` table on `assoc_type = 1048585` and the submission id. The file history is built from filtering the same table on `assoc_type = 515` and the file id. 

The upgrade script could iterate over the submission files and add
ASSOC_TYPE_SUBMISSION_FILE entries in addition to the existing ASSOC_TYPE_ARTICLE entries.

**Comment by pkel** [comment]
In order to make things more clear: The 3.1 interface assumes that event_log entries on the file level exist. Upload dates and revisions are only accessible via the "File History" view. This view is generated from the event_log table. Unfortunately, the upgrade script does not generate any event_log entries for files. Thus, the file history of migrated files appears empty. Neither the upload date nor previous revisions are visible in 3.1.

A solution approach would be to go trough all submission_files, read their metadata and generate the missing event_log entries from scratch.

**Comment by NateWr** [comment]
Closing this as we are no longer providing fixes for 2.x.
