### ISSUE TITLE
Update list separator locale key

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3792]
@bozana it looks like there are still some areas where the `common.listSeparator` key is in use. You changed it in https://github.com/pkp/pkp-lib/commit/bdb830b0a9d1fe2288c0dbfb5f763d07b106abab#diff-3b5ac1283ce98563f3403a121de3d2e8R177

I'm seeing it in `PKPSubmissionSubmitStep1Form`, `QueryForm`, and two language's `common.xml`.

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/ojs/pull/2015
https://github.com/pkp/ojs/pull/2016 (only submodule update)

**Comment by asmecher** [comment]
@bozana, is any backporting required? Just noting a similar issue coming up in the forum recently: https://forum.pkp.sfu.ca/t/assign-evaluation-characters-appear-ojs-3-x/45721

**Comment by asmecher** [comment]
^ Never mind, the poster thought it was broken in English but it was just in the (incomplete) Spanish.

**Comment by bozana** [comment]
No backporting required...
