### ISSUE TITLE
BIBITEX missing last character

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#3797]
Download BIBITEX format of citation is generating a file missing last character "}" and it avoids to import into Reference manager.
I've tested on a OJS 3.1.1-2, please check it: Article detail page > More Citation Formats > Bibtex (last option).

**Comment by NateWr** [comment]
We use the official CSL style for this: https://github.com/citation-style-language/styles/blob/master/bibtex.csl

It looks like it is in active use but has not had any similar bug fixes recently: https://github.com/citation-style-language/styles/commits/master/bibtex.csl

You could try updating the file in `/plugins/generic/citationStyleLanguage/citation-styles` to see if that fixes it. If not, you can raise an issue with https://github.com/citation-style-language/styles or the parser that we're using https://github.com/seboettg/citeproc-php

**Comment by israelcefrin** [comment]
I've opened an issue on [citeproc-php Github project](https://github.com/seboettg/citeproc-php) and their answer has fixed this I've  reported here. 

As  they wrote, the following workaround  works fine. 
Editing  the style  on line 146,  replacing
`<group prefix="{" suffix="}" delimiter=", ">` 
with 
`<group prefix="{" suffix=" }" delimiter=", "> `
or 
`<group prefix="{" suffix="\n}" delimiter=", ">`

That has solved my issue.

For future reference, I will add  URL with solution bellow:
https://github.com/seboettg/citeproc-php/issues/51#issuecomment-399690462

**Comment by NateWr** [comment]
Great! I'm a little wary of modifying the style itself, since that is third-party work and, ideally, we want to be able to just pull an updated copy without managing modifications ourselves.

It might be worth opening an issue on the https://github.com/citation-style-language/styles repo pointing to the difficulties with `citeproc-php`, and seeing if they've encountered any solutions. If not, then we can go ahead and modify the `bibtex.csl` file. I just don't know how we'll make sure this bug doesn't reappear later when we update the csl files.

**Comment by NateWr** [comment]
It looks like the CSL people are open to modifying the base style, so I've raised a pull request there: https://github.com/citation-style-language/styles/issues/3568.

If all goes well, they'll merge and we'll update our CSL styles. Otherwise, we'll make the change manually.

**Comment by ambs** [comment]
Nice. Following that PR.

**Comment by NateWr** [comment]
The CSL people have updated the bibtex format in their repo and I've merged that change to our plugin: https://github.com/pkp/citationStyleLanguage/pull/40

@asmecher do I need to do anything special to get this into ojs stable? Or will you automatically pull the latest `master` branch of citationStyleLanguage when building a maintenance release?

**Comment by asmecher** [comment]
@NateWr, I created an `ojs-stable-3_1_1` branch in the `citationStyleLanguage` repo based on the current submodule hash (as there wasn't a stable branch there yet):

`co -b ojs-stable-3_1_1 ff4f20d`

Then I cherry-picked in your change:

`git cp 0460f021f94d8f08e0cbbd7e00ecb968b83f6ffe`

Then I went into the `ojs-stable-3_1_1` branch of the `ojs` repo and updated the submodule there:

```
git add plugins/generic/citationStyleLanguage
git commit -m "Citation style language submodule update"
git push
```

That should do it! This should be ready to close, correct?

**Comment by NateWr** [comment]
:+1: Thanks!
