### ISSUE TITLE
Verify submission archive process on rejection

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3798]
Described in UI/UX testing: https://docs.google.com/document/d/1PIbROcG64a19V5paSuGeSENSLS_OC8MP4DrMKyRMRz4/edit?disco=AAAAB9gQhWg&usp=todo_email_discussion&ts=5afdcb1b

**Comment by NateWr** [comment]
I don't believe this is an issue anymore in 3.3.0. But if it is it will be addressed in #7265.
