### ISSUE TITLE
Implement beacon

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#380]
- install tracking and statistics; security alerts (#8188)
- model already in existence in Wordpress: Jetpack plugin. Requires you to link your WP instance with phoning home, but provides additional capabilities.

**Comment by jalperin** [comment]
I still strongly believe some basics of the beacon should be implemented on OJS 2.4.x line.

**Comment by asmecher** [comment]
Agreed via the technical committee:

- New installs will have a checkbox on the Install form, checked by default, but permitting opt-out, with wording like: "Provide the Public Knowledge Project with a unique identifier for this installation, to be used for statistics purposes only." (Perhaps with a link to a PKP website page describing further and providing access to the stats.)
- Upgrades will have this option automatically enabled, with a prominent entry in the release notes.
- The setting can always be turned off in config.inc.php.

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/ojs/pull/526
https://github.com/pkp/pkp-lib/pull/573

Jason, could you review this?

**Comment by jnugent** [comment]
These look great, Alec.  Feel free to merge -- the submodule won't go cleanly any more.

**Comment by asmecher** [comment]
Thanks, Jason.

**Comment by asmecher** [comment]
Committed to ojs-stable-2_4_6 and cherry-picked to ojs-dev-2_4.

For forward-porting, filed:
https://github.com/pkp/pkp-lib/issues/579
https://github.com/pkp/pkp-lib/issues/580
