### ISSUE TITLE
Multiple duplicate names in "Enroll existing user" as reviewer search field

### ISSUE THREAD

**Issue by vasylOstrovskyi** [pkp/pkp-lib#3802]
I installed the latest OJS from github.
I ctreated some test users and uploaded test paper.
I moved the paper to the review stage, and pressed the "Add reviewer" button
I pressed "Enroll existing user"
When I start typing name in the search field, a list of users appear, which contains each user several times.

I found that the problem is in lib/pkp/classes/security/UserGroupDao.inc.php file, in function getUsersNotInRole(), where SELECT should be changed to SELECT DISTINCT at line 464.

I do not plan to submit PR for this, I would appreciate if you just check and add this fix.

Thanks for your great work.
 Vasyl

**Comment by asmecher** [comment]
@bozana, this appears to have come in with https://github.com/pkp/pkp-lib/commit/32d50e1a846d8c9493ec6a1f24661aa0b28371d7#diff-6993579cf500b691f53345aa057a4b02R466 -- mind taking a look?

**Comment by bozana** [comment]
@asmecher, those changes came with multilingual user names, i.e. this issue is for OJS 3.2...

@vasylOstrovskyi, you used the master branch, right?

I'll test it for both branches, stable and master...

**Comment by bozana** [comment]
the problem seems to exist only in the master branch...

**Comment by bozana** [comment]
PR: https://github.com/pkp/pkp-lib/pull/3818

**Comment by bozana** [comment]
@vasylOstrovskyi, thanks a lot!!! 
Are you testing the new feature "multilingual user and author names" ?

**Comment by bozana** [comment]
merged thus closing...
