### ISSUE TITLE
integrate new Crossref deposit and submissionDownload API

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3803]
New deposit API should immediately return the DOI registration status, which would significantly improves the current registration process. Here, each article DOI is registered using a separate, own XML file (i.e. no one XML file for several articles any more). This will change the user notification message display (pink box in the right top corner): one notification message (either "registration successful" or "errors occurred") is displayed per registration action (and not per article). 

New deposit API (for DOI registration) to be then found on:
https://api.crossref.org/v2/deposits
https://test.crossref.org/v2/deposits

SubmissionDownload API (for status check):
https://api.crossref.org/servlet/submissionDownload
https://test.crossref.org/servlet/submissionDownload

**Comment by ctgraham** [comment]
Information only:
> *Question:* Can you share the support timeline for this [deprecated endpoint](https://github.com/CrossRef/rest-api-doc/blob/c67ffb7e52e6d42a5754f113a09704679f93d526/deprecated/deposit_api.md)?

> *Crossref support:* There is no timeline to fully deprecate that endpoint. It's certainly possible that that endpoint is one day open to more than just OJS users. There's no timeline for that, but I mention it just to illustrate that there's potentially more life in it than the word deprecated would suggest.

**Comment by bozana** [comment]
Thanks for the information @ctgraham!
We plan to release the integration with the new Crossref deposit API with the next release 3.1.2 -- I will double check with Crossref that this is OK so. 
The new API is also needed for Reference Linking. And we hope that it will solve many problems regarding the status update/check.

**Comment by ctgraham** [comment]
@bozana, do you plan to fixes for the status update/check back to 2.4.x?

**Comment by ctgraham** [comment]
If PKP doesn't have plans to backport, I think Pitt may provide a patch for this.  As is, since articles don't generally progress in status from "submitted" to "completed", we're calling the Crossref API unnecessarily thousands of times per day, and the articles appear as if the registration is incomplete (when, in fact, it is completed).

**Comment by bozana** [comment]
Merged for stable-3_1_2. 
Once I get the master code running I will cherry-pick this with master...

**Comment by bozana** [comment]
Just a note, that this issue is finished for 3.1.2, just waiting to be ported to master...

**Comment by bozana** [comment]
I will then close this issue for now -- so it is not any more open for 3.1.2 -- but will provide PRs for master then later...
