### ISSUE TITLE
[OJS 3.x] expand width CSS class pkp_modal_confirmation

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3806]
My proposal is about width size of modal confirmations. Right now the modal size is set in 30 em and is ok only if the text is minimal, but if you need show some more is a little bit uncomfortable. I think just with set in at 40 or 45 em this problem disappear.

The CSS class is:   .pkp_modal_confirmation

Now (max-width: 30 em)
![aaaaadadadd](https://user-images.githubusercontent.com/5422984/41573682-e21907ea-734b-11e8-9e01-20a71631735a.png)

My proposal (max-width: 45 em)
![adadada2](https://user-images.githubusercontent.com/5422984/41573689-e87bf48a-734b-11e8-9cd5-2977cbaa339f.png)

**Comment by NateWr** [comment]
Hi @t4x0n, this won't really be appropriate for our typical usage, which is short text. Where is this example taken from? I can offer a couple of suggestions:

1. If it's a custom workflow, I might be able to suggest some CSS that will target confirmation modals on this page.

2. If you have control of the LinkAction which loads this confirmation modal, you could extend the `ConfirmationModalHandler.js` component to accept a size property, and then pass that in with the modals you want to be larger.

**Comment by t4x0n** [comment]
Sorry, I didn't give more info... this is a modal at Step 3 in the review process, when you click on Reviewer Guidelines
![revprocojs](https://user-images.githubusercontent.com/5422984/41670937-aed0fc10-7483-11e8-91c3-b6e471f18cbe.png)

and the Reviewer Guidelines are the Step 2, so we see a lot of space empty in Step 2 for Reviewer Guidelines and move forward to incorporate some instructions about how should be the reviewer process and the reviewer comments: 
(the English in the image is automatic translate just for explain to you)
![image](https://user-images.githubusercontent.com/5422984/41671286-a79aa31e-7484-11e8-9daf-4f1bfef593b4.png)

I do not understand what you say in point 2 control of LinkAction; this is for modify only this modal and no others? I tried with others, and I like how it looks if every modal change to 40 em, so in this case you suggest is using a custom CSS?

**Comment by NateWr** [comment]
The following CSS will restrict your changes to just confirmation modals in the reviewer pages:

```
.pkp_page_reviewer .pkp_modal_confirmation {
    max-width: 40em;
}
```

This is probably the easiest way to get what you want with minimal impact on the rest of the system.

**Comment by t4x0n** [comment]
thank @NateWr, but I tried uploading a CSS file in Website Settings > Appearance but this style sheet is only called in the frontend, not in the backend, is correct?

**Comment by NateWr** [comment]
Yes, that's correct. It may require a bit more intervention. You could spin up a small custom plugin to load in the additional CSS on the backend, but it may just be easier to open up https://github.com/pkp/pkp-lib/blob/master/styles/controllers/modal.less and chuck this into the bottom (of course, then you'll need to manage this change manually against updates).

If you want some hints on the custom plugin route let me know.

**Comment by t4x0n** [comment]
I made a similar question in the forum but for a form template... (https://forum.pkp.sfu.ca/t/how-to-customize-submission-form/45943) I know how works a theme but not a plugin, in a theme you replace some default template files for others, if I could be made this in the backend with a plugin I will be happy. I know PHP and CSS, but you use a framework (Symfony I guess) and I do not know any about PHP frameworks, so only if you have a little example or a manual for making plugins I could try, but if you not have, don't worry, maybe in the future with more time I will try...

**Comment by NateWr** [comment]
From that forum post, it looks like maybe you're already using a custom theme? If so, it might be easiest just to add the backend style there.

In the theming guide, there's a section "Theming the Editorial Backend". The first part of that describes how to load a custom LESS file on the backend:

https://pkp.gitbook.io/pkp-theming-guide/en/theme-backend

**Comment by t4x0n** [comment]
Thank you!! 
Now I need to try some code... and, maybe, learn some of LESS ;)  but I know CSS very well, thanks again!!

**Comment by NateWr** [comment]
:+1: I'm going to close this issue but feel free to reopen if you want to discuss things further.

**Comment by carzamora** [comment]
just an update, the new link: https://docs.pkp.sfu.ca/pkp-theming-guide/en/theme-backend for "Theming the Editorial Backend"

**Comment by carzamora** [comment]
@NateWr is the PHP framework Symfony 2 used in OJS? Or does it correspond to its own development?

**Comment by NateWr** [comment]
I'm not aware of any parts of Symphony being used in OJS at the moment. We have a couple of parts of Laravel being used (QueryBuilders and Validation).
