### ISSUE TITLE
Submission searching is case-sensitive in postgresql

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3807]
When searching in the submissions list, the search should be case-insensitive. In postgresql, the `LIKE` syntax is case-sensitive by default.

Is there a way to ensure case-insensitivity for MySQL/Postgresql/MSSQL?

Searching code is at: https://github.com/pkp/pkp-lib/blob/master/classes/services/queryBuilders/PKPSubmissionListQueryBuilder.inc.php#L305-L328

User list query builder should also be addressed: https://github.com/pkp/pkp-lib/blob/master/classes/services/queryBuilders/UserListQueryBuilder.inc.php#L396-L421

**Comment by NateWr** [comment]
Thanks @ctgraham! I had to work around some restrictions in the Laravel query builder we're using, so we run PHP's `strtolower()` on the query part. Are you aware of any discrepancies between SQL's `lower()` and PHP's `strtolower()` that will prevent matches?

(I also found and fixed a bug with searching assigned submissions.)

@asmecher, would you code review?

PR:
https://github.com/pkp/pkp-lib/pull/3815

Tests:
https://github.com/pkp/ojs/pull/2020

**Comment by ctgraham** [comment]
Pairing PHP's `strtolower()` with SQL's `lower()` seems reasonable.

**Comment by NateWr** [comment]
Merged. Thanks for the assist @ctgraham. :+1:
