### ISSUE TITLE
Implement author disambiguation toolset

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#381]
Permit (optional) associations to be created and maintained between author entries and user entries.

See:
- http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=4653
- http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=5329
- http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8615

**Comment by asmecher** [comment]
This might get resolved via https://github.com/pkp/pkp-lib/issues/1416

**Comment by asmecher** [comment]
For 3.0: need to implement a "by authors" browse, hopefully using ORCiDs rather than the flawed 2.4.x query.

**Comment by asmecher** [comment]
@NateWr, in https://github.com/pkp/ojs/commit/69ba94b99c1460a36fcbc9105860c74c74b246e4 I added the display of authors' ORCID identifiers to the article view page. Mind taking a quick look at styling? ORCID has some guidelines here: https://orcid.org/trademark-and-id-display-guidelines

**Comment by NateWr** [comment]
@asmecher PR:
https://github.com/pkp/ojs/pull/987

**Comment by asmecher** [comment]
Thanks, @NateWr; punting the rest to OMP 1.2.1. Note that https://github.com/pkp/ojs/pull/987 needs porting to OMP.

**Comment by NateWr** [comment]
Hmm, I looked for ORCiD in OMP but didn't see it. Maybe there's some set-up involved that I hadn't ticked, but happy to look at it for OMP 1.2.1.

**Comment by asmecher** [comment]
OMP and OJS share the same profile forms, IIRC, so whatever OJS gets OMP does too. It's possible (likely) that this is a post-1.2 sharing of code.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/omp/pull/394

Adds and styles ORCID id on the `monograph_full.tpl` template.

**Comment by NateWr** [comment]
Feeling merge-y today. Tests passed on this one. Also a tiny change, so just merged.
