### ISSUE TITLE
Can not edit review assignment

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3810]
When trying to edit a review assignment, a fatal error is thrown:

```
[Tue Jun 19 10:46:42.702762 2018] [:error] [pid 7058] [client 127.0.0.1:32984] PHP Notice:  Undefined property: ReviewAssignment::$getDateDue in /var/www/html/ojs/lib/pkp/controllers/grid/users/reviewer/form/EditReviewForm.inc.php on line 135, referer: http://localhost/ojs/publicknowledge/workflow/index/136/3
```

First reported: https://forum.pkp.sfu.ca/t/accepted-review-can-not-be-edited/45824

Reproduced in current `master` (after 3.1.1-2).

**Comment by bozana** [comment]
Seems like the other function calls in that code line should be fixed as well, i.e. getDateDue, getDateResponseDue, getReviewMethod

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3861
ojs ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/2031 (only submodule update)

pkp-lib omp-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3862
omp omp-stable-3_1_1: https://github.com/pkp/omp/pull/559 (only submodule update)

pkp-lib master: https://github.com/pkp/pkp-lib/pull/3863
omp master: https://github.com/pkp/omp/pull/560 (only submodule update)

**Comment by bozana** [comment]
@NateWr, could you take a look i.e. test? -- Somehow I haven't seen the message, but have found the place in the code... Thanks!!!

**Comment by NateWr** [comment]
:+1: This looks good, merge whenever you're ready.
