### ISSUE TITLE
Merge the user generates problems in the submission if he is a participant in the discussions

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#3811]
If a "myuser" user (editor, guest editor, or other) is one of the participants in the discussions on a submission and must be "merged" (to be deleted by Ojs) with the "newuser" user then we have a problem.
As soon as the merge is done, in the same "submission" the box to the right of the "Participants" no longer appears because here (ie in the "stage_assignments" table) the merge has not been made.

As a workaround just change (directly in SQL) the "user_id" no longer exists with that of "newuser" in the table "stage_assignments".

Tested on OJS 3.10-1 and OJS 3.1.1

**Comment by asmecher** [comment]
@eniocarboni, glancing at the code (https://github.com/pkp/ojs/blob/ojs-stable-3_1_1/classes/user/UserAction.inc.php#L139..L152), it looks like stage assignments should be transferred; have you run an example test case on this to make sure it's duplicated with OJS 3.1.1? What was the example test like?

**Comment by eniocarboni** [comment]
Hi @asmecher,
I am using OJS 3.1.1 as I see from "Administration" -> "System Information"
I checked and the UserAction.inc.php file matches.

A very simple test on journal "test":
1- make a submission (title: merge user example, submission_id=100)
2- create 2 users, olduser and newuser and grant role "Guest editor"
3- open the submission (id 100) at /index.php/test/workflow/index/100/1
4- at "Partecipants" click on "Assign" and select "olduser" than "ok" to save.
   Now "olduser" is in the "Partecipants" box.
5- go to "Users & Roles" -> "Users", expand the user "olduser" and click at "Merge user"
5.1 - select "newuser" as a merged user, confirm all messages.
6- come back to the submission (id 100) at /index.php/test/workflow/index/100/1
6.1 you can see the perennial "loading" instead of the Participants box

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3821
ojs ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/2023 (only submodule update)

pkp-lib omp-stable-3_1_1: 
ojs omp-stable-3_1_1:  (only submodule update)

pkp-lib master: 
ojs master:  (only submodule update)
omp master: (only submodule update)

**Comment by bozana** [comment]
Everything merged, thus closing...

**Comment by asmecher** [comment]
Good spotting, @bozana -- thanks, @eniocarboni!
