### ISSUE TITLE
Add option to display journal summary on homepage

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3817]
We're receiving repeat request for this from hosted journals. At the moment the workaround is to move additional homepage content to the top of the homepage which requires either modifying a system template or a custom theme.

Settings > Journal > Journal Summary already exists and could be used for this purpose instead.

**Comment by isgrim** [comment]
We stumbled open this same issue while testing the migration from OJS 2.4

**Comment by tothbog** [comment]
I also would like to change that in our journal. Could you give us a bit of advice on how to do that easily on the default theme?
Thanks, Bogi

**Comment by NateWr** [comment]
@tothbog we use the forum for support and technical advice. Can you post your question at https://forum.pkp.sfu.ca/? If you tag me (@NateWr there too), I will see it and jump in.

**Comment by thinkbulecount2** [comment]
I've added the journal description in between the header image and the announcements block (attaching the screenshot). Would love your feedback! @NateWr & anyone else! Thank you!

<img width="936" alt="Screen Shot 2019-04-10 at 07 25 04" src="https://user-images.githubusercontent.com/38994650/55874930-c82f2900-5b61-11e9-9792-e72d8d0ce595.png">

**Comment by NateWr** [comment]
:+1: Looks good. Let's add a heading to the section as well. Something like:

> **About the Journal**
>
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Use a `<h2>` tag for a good heading structure. I'll reach out on Slack for some details about how to add a localized string.

**Comment by thinkbulecount2** [comment]
Created a [pull request here](https://github.com/pkp/ojs/pull/2357), @NateWr

**Comment by NateWr** [comment]
Looks good!

![description-default](https://user-images.githubusercontent.com/2306629/55944899-8970a000-5c41-11e9-9d00-1e3410606c78.png)

![description-manuscript](https://user-images.githubusercontent.com/2306629/55944900-8970a000-5c41-11e9-8af8-e4dd753b3292.png)

**Comment by NateWr** [comment]
:tada: Merged!
