### ISSUE TITLE
Consider adding "Languages" to Settings Wizard

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3819]
This is a major missing piece from the settings wizard needed by a good proportion of our journals (i.e., non-English or multilingual). Adding it would be a good step away from being so anglo-centric. 

Also, I'm setting up a lot of Spanish course journals for PKP School students and it requires an extra step I'd like to avoid :)

**Comment by NateWr** [comment]
Language settings are available in the settings wizard. I think this was added in 3.3.0-x.
