### ISSUE TITLE
file_type of newly uploaded JATS XML

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3820]
After upgrading from OJS 3.1.1 to OJS 3.1.1-1, I've noticed some changes in the determination of file_type for JATS XML galley files. Now they get `text/xml` type instead of `application/xml`. 
I experience such behavior only on my local machine, but not on production site. Some users also report this problem, some not. This can cause some issues, like: https://github.com/Vitaliy-1/oldGregg/issues/63

**Comment by asmecher** [comment]
@Vitaliy-1, I suspect the change in behavior isn't related to OJS -- either the content of your XML is getting it detected differently than previous files, or your PHP mime detection toolset (and underlying OS tools it relies on) have changed. I tend to treat `application/xml` and `text/xml` synonymously, e.g. in the Lens Reader plugin.

In any case, the detection code hasn't changed within the 3.1.0-x line of releases (yet).

**Comment by Vitaliy-1** [comment]
In this case, for consistency, I suspect `text/xml` file type should be added here: https://github.com/pkp/ojs/blob/master/templates/controllers/grid/articleGalleys/form/articleGalleyForm.tpl#L42

**Comment by asmecher** [comment]
Good spotting -- added, @Vitaliy-1. You can apply https://github.com/pkp/ojs/commit/cef56ab20a6db70e3857d27eaaa0d00bb59d6c56 for `ojs-stable-3_1_1`, or `https://github.com/pkp/ojs/commit/34b900414fcc1472d60338f4ecf2086ff6381343` for `master`.
