### ISSUE TITLE
lack of privacy statement in register when there are several journals in site

### ISSUE THREAD

**Issue by luisja58** [pkp/pkp-lib#3828]
When a user register in a site with serveral journal (../index/user/register), the form does not contain the privacy statement.

**Comment by Vitaliy-1** [comment]
@NateWr, can the consent be moved out of the journal context? https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/userRegister.tpl#L31-L51

**Comment by Vitaliy-1** [comment]
Duplicates https://github.com/pkp/pkp-lib/issues/3836

**Comment by NateWr** [comment]
Closing in favor of https://github.com/pkp/pkp-lib/issues/3836
