### ISSUE TITLE
Override admin template

### ISSUE THREAD

**Issue by jafamo** [pkp/pkp-lib#3830]
Hi @NateWr , 
I have problems to override templates. I commented on the forum about this problem.
I followed all the links in this link.
[forum.pkp.sfu.ca](https://forum.pkp.sfu.ca/t/how-can-i-override-backend-templates-ojs-3/33512/6)
I tried to do in a new fresh install (ojs-stable3.1.1)

I attached my plugin.
[test.zip](https://github.com/pkp/pkp-lib/files/2137514/test.zip)

Thank you!!

**Comment by NateWr** [comment]
Closing as you seem to have got this part going.
