### ISSUE TITLE
Fix citation style language plugin where locales don't exist

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3833]
Currently the CSL plugin will fail if the user's locale doesn't exist in the CSL library.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/citationStyleLanguage/pull/36

@NateWr, would you mind reviewing this?

**Comment by wesambhaya** [comment]
Thank you very much, it works. Regards

**Comment by NateWr** [comment]
:+1: ready for merge whenever.
