### ISSUE TITLE
[OJS] Issue cover settings are too locale specific

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#384]
Generally, when displaying Issue or Article data in a non-primary locale, if the Issue or Article data is missing from that locale, the data is drawn from the site's primary locale.

The Issue Cover does not follow that precedent.  If an Issue Cover is missing from the current locale, the default locale settings are ignored.  C.f.
https://github.com/pkp/ojs/blob/ojs-dev-2_4/templates/issue/archive.tpl#L32
and
https://github.com/pkp/ojs/blob/ojs-dev-2_4/pages/issue/IssueHandler.inc.php#L442

**Comment by asmecher** [comment]
See also http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8180

**Comment by asmecher** [comment]
Clinton, is there a PR open for this?

**Comment by ctgraham** [comment]
C.f. https://github.com/pkp/ojs/pull/459

**Comment by asmecher** [comment]
Thanks, merged -- that solution makes sense to me.
