### ISSUE TITLE
NavigationMenu Feature - Locales for default NMIs retrieved from key and not database

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#3846]
The displayed title of the NMIs is retrieved from the database (navigation_menu_item_settings table). We also preserve the locale-key to the same table, for the default NMIs. 

As a generic to the NMIs displayed title we could use that locale-key and try to translate that to what ever the current locale is, depending on the native OJS/OMP translation mechanism.

See also: https://forum.pkp.sfu.ca/t/menu-problem-in-ojs-3-1-bug/35635

**Comment by defstat** [comment]
@NateWr @asmecher 

PR
[pkp-lib] #3849

**Comment by asmecher** [comment]
@defstat, Nate's busy until next week, but he's more familiar with this code than I am, so I'd rather wait for his return!

**Comment by defstat** [comment]
@NateWr 

After the code review fixes, I also made PRs for OJS and OMP for the tests to run

PRs
[pkp-lib] #3849 
[OJS] pkp/ojs#2045
[OMP] pkp/omp#567

**Comment by NateWr** [comment]
:heavy_check_mark: Tests passed. Thanks @defstat!
