### ISSUE TITLE
Ask two times a revision in a review round failed

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3851]
Hi,
I think this issue is related to #3399 .
When  a author has submitted a revision of his article, if an editor wants to ask another revision, the round status stays "revisions have been submitted" so the author does not know (in the UI) if he has something to do.

I think this behavior is because the round status is calculated from the presence of a revision file.

Thank you

(ojs 3_1_1_2 )

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3857
ojs ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/2030 (only submodule update)

pkp-lib omp-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3858
omp omp-stable-3_1_1: https://github.com/pkp/omp/pull/557 (only submodule update)

pkp-lib master: https://github.com/pkp/pkp-lib/pull/3859
omp master: https://github.com/pkp/omp/pull/558 (only submodule update)

**Comment by bozana** [comment]
@NateWr, could you please review the code when you are back again?

**Comment by forgive38** [comment]
@bozana 

I test the patch for ojs stable and it seems to have the expected behavior

thank you !

**Comment by NateWr** [comment]
:+1: merge whenever you want.
