### ISSUE TITLE
Keyword linking

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3853]
Currently, keywords are displayed as text in the sidebar of the article landing page:
https://demo.publicknowledgeproject.org/ojs3/demo/index.php/health-sciences/article/view/709

Could we make those keywords linked, taking the reader to the search results page for that keyword?

**Comment by NateWr** [comment]
The search doesn't actually match against keywords. If the keyword isn't also used in the title or abstract, no results will be found.

However, I think what you want is browsing by subject/keyword, which is filed here: https://github.com/pkp/pkp-lib/issues/2714

I'll close this as a duplicate but feel to reopen if I've missed something.
