### ISSUE TITLE
Punctuation error in citation generator

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3854]
The citation generator is currently unable to display the correct punctuation for article titles ending in a question mark (it adds a period). See, for example, here:

https://demo.publicknowledgeproject.org/ojs3/demo/index.php/health-sciences/article/view/713

Can the generator be made to identity when article titles end in a question mark (or exclamation mark) and automatically remove the period?

**Comment by asmecher** [comment]
@stranack, that's a question for the folks behind the citeproc-php library we use for citation formats (https://github.com/seboettg/citeproc-php). Mind filing something there?
