### ISSUE TITLE
[OJS] Email validation does not recognize @localhost 

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#3855]
Hi there,

i'm developing some stuff for OJS and the application is running on my local IIS. I also have a local mail server installed which provides email addresses ending with **@localhost**.

Now, while setting up OJS i have to enter the email address of user *admin* which is **admin@localhost**. Sadly in this case the validation fails and the following message is returned:

> A valid email address is required.

The culprit is the use of `PCRE_EMAIL_ADDRESS` in class `ValidatorEmail` which holds a regex that does not provide a matching rule for @localhost.

I suggest extending the regex from

`...@...`

to something like

`...*@(localhost|...)`

Should i provide a PR?

So lonG

**Comment by asmecher** [comment]
Hi @ViRuSTriNiTy -- I'd be happy to consider a PR, but rather than extending the regular expression, it might be better to move to the email validation tools that have been added to PHP since that part of OJS was written (e.g. `FILTER_VALIDATE_EMAIL`). Thanks!

**Comment by ViRuSTriNiTy** [comment]
@asmecher  Thanks for the reply.

Hmm validation tools, sounds good, never heard of it but I have hacked something together as a draft. What do you think?

		<?php

		$emails = [
			"admin@localhost \r\n user@localhost",
			"my@mail.com your@mail.com",
			"my@mail.com",
			"admin@localhost",
		];

		foreach ($emails as $email) {
			$email = trim($email);

			echo "validating <b>{$email}</b> ... "; 

			if (filter_var($email, FILTER_VALIDATE_EMAIL) === false)
			{
				// second try as FILTER_VALIDATE_EMAIL does not allow email adresses with loopback domains,
				// therefore try to match these email adresses via regex, inspired by https://stackoverflow.com/a/8426365/3936440
				$matchCount = preg_match(
					'/^' . // match start of string to ensure no line breaks are present
						'(.*)' . // match part before @ character
						'@' . // match @ character itself
						'(localhost|127(?:\.[0-9]+){0,2}\.[0-9]+|^(?:0*\:)*?:?0*1)' . // match part after @ character ...
						'$' . // ... up to string end 
					'/i' // ignore case
					, $email, $matches);

				if ($matchCount == 1)
				{
					$partBeforeAtChar = $matches[1];

					if (filter_var("{$partBeforeAtChar}@mail.com", FILTER_VALIDATE_EMAIL)) {
							echo "valid"; 
					} else {
							echo "invalid";
					}
				} else
					echo "invalid";
			}
			else
				echo "valid";

			echo "<br>";
		}

		?>

**Comment by asmecher** [comment]
Hmm, it's a shame that `@localhost` emails (technically valid but not used in production) aren't supported by `FILTER_VALIDATE_EMAIL`. This is discussed at https://bugs.php.net/bug.php?id=69140 and an improvement (not yet available) is proposed.

In the meantime, I would consider a PR that augments the regular expression that's currently used to validate emails in OJS.

**Comment by ViRuSTriNiTy** [comment]
Sorry for the doubled PR link, GitHub got it wrong. Sadly i cannot remove the first one.

**Comment by asmecher** [comment]
@ViRuSTriNiTy, thanks for all your work on this, and sorry to keep pulling the rug out from under you.

I did a little further looking into this, and on balance I think the `FILTER_VALIDATE_EMAIL` approach is the safest (risks false negatives where regular expressions risk false positives) and most future-proof (maintained by Zend, not by us).

However, I'm not enthusiastic about adding the additional checking permitting e.g. `whatever@locahost` -- it's useful for your dev environment but can be harmful on production environments where you definitely wouldn't want to allow someone to register an account using `root@localhost` as their email.

Three options come to mind for that:
- It may be possible to somehow extend PHP's `FILTER_VALIDATE_EMAIL`, and then use an OJS plugin to install that extension before any validation is done.
- I considered adding an additional `config.inc.php` option for a "dev mode" for this, but as there's no other use for it yet, I think it would be misleading and rarely used. (Perhaps other uses for this will come to mind.)
- Perhaps it's best leaving the extension to permit local emails as a local modification.

Thoughts?

**Comment by ViRuSTriNiTy** [comment]
Exactly my doubts in the beginning. Another suggestion: is it a valid approach to refactor the email address handling in a way that it provides a hook so that a plug-in can listen to that hook to allow additional patterns?

**Comment by asmecher** [comment]
@ViRuSTriNiTy, yes, there are several places to do that:
- In `lib/pkp/classes/validation/ValidatorRegExp.inc.php`, in `isValid`
- In `lib/pkp/classes/validation/ValidatorEmail.inc.php`, in `getRegexp`
- In `lib/pkp/classes/form/Form.inc.php`, in `validate`.

I would favour the `Form::validate` hook, as it would be the most generally useful hook, but it'll be a little trickier to use it to traverse the check list and find the right check to modify.

**Comment by asmecher** [comment]
Another option that would resolve this: https://github.com/pkp/pkp-lib/issues/3976

**Comment by NateWr** [comment]
A fix for this has been merged to `master` as part of the validation changes for #3594.

**Comment by ViRuSTriNiTy** [comment]
> A fix for this has been merged to `master` as part of the validation changes for #3594.

Which change in particular? I'm too lazy to go through all 600 commits.

**Comment by NateWr** [comment]
There's no one single change, unfortunately. We have integrated the validation library for Laravel 5.5 and deprecated our existing validation system.

The custom email validation rule that allows `@localhost` addresses is coded up here:

https://github.com/pkp/pkp-lib/blob/master/classes/validation/ValidatorFactory.inc.php#L44-L64

**Comment by ViRuSTriNiTy** [comment]
> There's no one single change, unfortunately. We have integrated the validation library for Laravel 5.5 and deprecated our existing validation system.
> 
> The custom email validation rule that allows `@localhost` addresses is coded up here:
> 
> https://github.com/pkp/pkp-lib/blob/master/classes/validation/ValidatorFactory.inc.php#L44-L64

Thx, much appreciated.
