### ISSUE TITLE
Allow to connect on custom ports / socket

### ISSUE THREAD

**Issue by j4rk0** [pkp/pkp-lib#3860]
Following two lines need to be added there, so the query is going to be correctly build in the Illuminate Database component for connections on custom ports / sockets.
```
'port' => Config::getVar('database', 'port'),
'unix_socket'=> Config::getVar('database', 'unix_socket'),
```
These properties could be then set in config file…

**Comment by asmecher** [comment]
@j4rk0, thanks -- would you mind opening a pull request to add this?

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/3943

**Comment by bozana** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/4247
https://github.com/pkp/ojs/pull/2171

**Comment by bozana** [comment]
@asmecher, OK so?

**Comment by asmecher** [comment]
Yes -- please go ahead!

**Comment by bozana** [comment]
Merged, thus closing...
Thanks @j4rk0 for contributing!!!
