### ISSUE TITLE
book double listed in a series, when ordered by title

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3864]
s. https://forum.pkp.sfu.ca/t/omp-3-1-1-1-upgrade-replicated-monographs/45796/12

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_1_1:
ojs ojs-stable-3_1_1: (only submodule update)

pkp-lib omp-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3865
omp omp-stable-3_1_1: (only submodule update)

pkp-lib master:
omp master: (only submodule update)

**Comment by bozana** [comment]
@NateWr, could you please take a look? I am not sure if this could harm any other place in the system... Thanks!

**Comment by NateWr** [comment]
I think that should be fine, though SQL is not my forte. Tests should show if there's a conflict with mysql or postgresql
