### ISSUE TITLE
lib/pkp/tools/installPluginVersion.php fails with SetCharSet() error

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3868]
Running into this issue with OJS 3.1.1-2 when trying to install a plugin, e.g.

```
$ php lib/pkp/tools/installPluginVersion.php plugins/generic/pln/version.xml

Dictionary driver '/usr/local/var/www/vhosts/ojs3_stable/lib/pkp/lib/adodb/datadict/datadict-.inc.php' not available

Fatal error: Call to a member function SetCharSet() on boolean in /usr/local/var/www/vhosts/ojs3_stable/lib/pkp/classes/plugins/Plugin.inc.php on line 708
```

```
$ php lib/pkp/tools/installPluginVersion.php plugins/generic/externalFeed/version.xml

Dictionary driver '/usr/local/var/www/vhosts/ojs3_stable/lib/pkp/lib/adodb/datadict/datadict-.inc.php' not available

Fatal error: Call to a member function SetCharSet() on boolean in /usr/local/var/www/vhosts/ojs3_stable/lib/pkp/classes/plugins/Plugin.inc.php on line 708
```

**Comment by asmecher** [comment]
Hmm, I've never seen this before -- is this occurring in a properly-installed OJS that's otherwise functioning properly?

**Comment by mfelczak** [comment]
Yes, initially ran into this with a hosted client install but also duplicated on my local install.

**Comment by mfelczak** [comment]
Hey @bozana, just confirming that I've tested with the following plugins:
- pln
- static pages

**Comment by bozana** [comment]
I can take a look...

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3877
ojs ojs-stable-3_1_1: (only submodule update)

pkp-lib omp-stable-3_1_1:
omp omp-stable-3_1_1: (only submodule update)

pkp-lib master:
ojs master: (only submodule update)

**Comment by bozana** [comment]
@mfelczak, would it be possible for you to test the PR above?
I did get another error message, but I think the error source could be the same as yours...
When OK, I will ask @asmecher for the review...
Thanks a lot!!!

**Comment by mfelczak** [comment]
Hi @bozana, that fixes it for me.

**Comment by bozana** [comment]
@asmecher, could you also please take a look at those changes? Thanks!!!

**Comment by asmecher** [comment]
Thanks, @bozana -- just one small question. The odd thing is that I used this tool pretty regularly, but as soon as Michael reported this bug, I started experiencing it too. I have no idea why! @mfelczak, careful with your newly discovered powers.

**Comment by mfelczak** [comment]
@asmecher, I had also used it in the past with no issues. A strange ending to a strange week.
