### ISSUE TITLE
Clean up overspecific/wrong subtitle language

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3874]
See https://forum.pkp.sfu.ca/t/ojs-3-1-1-1-titels-and-subtitels/46099/5 for details.

The metadata form includes a hint under the subtitle field stating that the subtitle will be attached to the title with a colon (":") character. However, the article view doesn't format them this way.

Proposed solution: Don't specify on the metadata form that a colon (":") will be used to join the title and subtitle.

**Comment by jamshidhashimi** [comment]
PR:
[#4258](https://github.com/pkp/pkp-lib/pull/4258)

Please review @asmecher. Thanks.

**Comment by asmecher** [comment]
Thanks, @jamshidhashimi!
