### ISSUE TITLE
Allow external issue galleys

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3875]
Consider allowing journals to link to external files for issue galleys, as they can for article galleys.

**Comment by asmecher** [comment]
Requested in the forum e.g. here: https://forum.pkp.sfu.ca/t/remote-issue-galleys/58170

**Comment by asmecher** [comment]
Also here: https://forum.pkp.sfu.ca/t/galley-of-the-whole-volume-at-a-separate-website/60704/2

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
