### ISSUE TITLE
import/export of HTML galley images

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3878]
this dependent relation seems not to be considered yet.

thus maybe either to 
a) consider/add the element submission_file_ref for the revision element
or
b) to consider/add two new attributes for the revision element, e.g. something like dependent_file_ref and dependent_revision_number.

**Comment by bozana** [comment]
@asmecher, what do you think would be better a) or b) above?

**Comment by asmecher** [comment]
Hmm, I don't have a strong preference, but I think it makes more logical sense for the HTML to list any files it includes rather than have the dependent files refer to the HTML -- so that would suggest a).

**Comment by bozana** [comment]
@asmecher, what do you think with HTML? -- we do not have the differentiation for html galleys -- they all use article_galley element. 
Then, usually, first the parent/HTML file is exported/listed (because it is usually first in the DB) and then the dependent files, thus I was thinking to add the new XML element to the dependent files, because we will need the DB file_id of the parent/HTML file. 
OK?

**Comment by asmecher** [comment]
Hi @bozana -- sure, I think there is code to track/map arbitrary IDs so that an XML file can refer to files with internal consistency and then the import process will re-map them to new IDs.

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3923
ojs master: https://github.com/pkp/ojs/pull/2062 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you review the PR above? If OK, I can cherry-pick to stable branches...
