### ISSUE TITLE
multilingual fields visibility - bug

### ISSUE THREAD

**Issue by mczirfusz** [pkp/pkp-lib#3887]
In the Metadata editing window if there are too many locales (=long text boxes), if editing one field, the next field is overlapping the previous one. 
![image](https://user-images.githubusercontent.com/16511307/42445207-b4f2bb3a-8372-11e8-9a13-f9f8318122a7.png)
In this case the Russian abstract's text box should be over the languages text boxes, and not underneath.
OJS 3.1.1.2

**Comment by NateWr** [comment]
This is a known limitation of the way we handle multilingual fields. We'll be addressing this alongside other improvements as we transition forms over to Vue.js: https://github.com/pkp/pkp-lib/issues/3594

I'm going to close this since we'll be fixing it alongside more significant refactoring.
