### ISSUE TITLE
Remove PHPUTF8 library

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3889]
It's outdated and there are alternatives. Its use in general needs review.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/3890
(No changes required to the applications)

This includes removing some long-standing core functions but I don't think they were being used (or at least, not effectively) and can't see much of a downside.

**Comment by asmecher** [comment]
@bozana, would you mind reviewing the attached PR once the tests run?
(Tests: https://travis-ci.org/asmecher/omp/builds/401943893 and https://travis-ci.org/asmecher/ojs/builds/401943538)

**Comment by asmecher** [comment]
@bozana, I finally fixed the tests on this -- could you have a look?

**Comment by bozana** [comment]
@asmecher, looks good, very nice cleaning :+1:  :-) You can merge...
