### ISSUE TITLE
Upgrading Prepared Emails Names from OJS2

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#3891]
An upgrade from OJS2 to OJS3 wasn' t allowing to load Prepared Emails list due names were upgraded with special characters like: &, ? or white space.

I think  we could run a search-replace on email_templates.email_key (table.column) to replace these special characters by underlines "_" .

**Comment by asmecher** [comment]
I think @jmacgreg ran into this a while ago... any recollection, James?

**Comment by NateWr** [comment]
Closing this as outdated. We're no longer providing fixes for OJS 2-3 upgrades unless they fix critical bugs.
