### ISSUE TITLE
Check downloadability of submission files from the submission history

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3892]
The original submission files (and possibly others) appear not to be downloadable from the editorial history area. At a glance, the files grid in the submission area (which does work) has a `stage_id` parameter, and the download link in the history listing (which does not) does not include it.

**Comment by NateWr** [comment]
Phew, this was harder than it looked! It was indeed the missing `stage_id`. I also had to add in an additional check for authors assigned as subeditors.

PR:
https://github.com/pkp/pkp-lib/pull/3896

Tests:
https://github.com/pkp/ojs/pull/2049

**Comment by asmecher** [comment]
Looks good, @NateWr -- please go ahead (and also port over to `ojs-stable-3_1_1` and `omp-stable-3_1_1`).

**Comment by NateWr** [comment]
Merged and ported. :+1:
