### ISSUE TITLE
[OJS] Running crossref scheduled task with Acron gives headers already sent error

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3893]
Hi @bozana 

It seems that running Crossref scheduled task gives an error on this line: https://github.com/pkp/pkp-lib/blob/master/classes/plugins/ImportExportPlugin.inc.php#L149

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/3904
ojs ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/2055

**Comment by bozana** [comment]
@ajnyga, somehow I couldn't reproduce it, but I now separated the display of the error messages when executed via CLI. Is there a possibility for you to test if that solves the problem? THANKS!

**Comment by ajnyga** [comment]
I use acron, did you use regular cron (if that would make a difference?)

We are still in 3.1.0, but once I upgrade to 3.1.1 later this month, I will add this change and see if errors still occur. It's just a warning, so not a big problem anyway.

**Comment by bozana** [comment]
Ah, yes, I thought you use a normal cron job... OK, I'll test it with acron...

**Comment by bozana** [comment]
@ajnyga, did you maybe encounter this error once again?
hmmm...

**Comment by ajnyga** [comment]
I don't think I've seen this. I will check our error log.

**Comment by bozana** [comment]
:+1:  Thanks!
Maybe we should consider the change above however... ?

**Comment by bozana** [comment]
@asmecher, do you think we should merge those changes? Could you take a look? -- it is a just a minor improvement...

**Comment by asmecher** [comment]
I think you can just check for the presence of the `SESSION_DISABLE_INIT` constant -- if present, it's a command-line invocation.

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/4292
https://github.com/pkp/ojs/pull/2213
