### ISSUE TITLE
Ensure overdue status of review assignments is calculated the same in all places

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3894]
When calculating the status we use `time()`: https://github.com/pkp/pkp-lib/blob/ojs-3_1_1-2/classes/submission/reviewAssignment/ReviewAssignment.inc.php#L481-L495

When searching in the db to filter results in the API, we check if it is overdue tomorrow: https://github.com/pkp/pkp-lib/blob/ojs-3_1_1-2/classes/services/queryBuilders/PKPSubmissionListQueryBuilder.inc.php#L238-L262

**Comment by NateWr** [comment]
@asmecher tests have passed here. I've just rebased so it should be a clean merge. :+1:

**Comment by asmecher** [comment]
Merged & back-ported, thanks!
