### ISSUE TITLE
Prevent deletion of active genres/components

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3899]
See https://forum.pkp.sfu.ca/t/missing-galley-links-in-some-issues/46332 for details.

Submission components (`genres` in the code) can be created and deleted, but once a submission file has been uploaded referring to it (`submission_files.genre_id` in the database), deleting a genre will cause trouble.

The manager should be prevented from deleting genres once they have files submitted to them.

**Comment by jnugent** [comment]
Hi @asmecher  just bumping this again since it remains a problem for some of our clients upgrading to OJS3 and being unaware that this causes problems.

**Comment by mfelczak** [comment]
I think we can apply a similar approach to what's currently in place for journal sections: check if there are any submission files with the genre id in question, report this to the JM, and block deletion of the genre id. If there are no submission files with the genre id, the genre can be deleted.

**Comment by ewhanson** [comment]
Hi @asmecher, could you have a look at these PRs? They implement the same pattern used when attempting to delete journal sections as @mfelczak described above. Thanks!

PRs:
`main`: #7480
`stable-3_3_0`: #7481
`stable-3_2_1`: #7482

**Comment by asmecher** [comment]
@ewhanson, I'd like to avoid the proliferation of single-use-case SQL queries -- once #7125 is merged, it'll be possible to use the filterByGenreIds function on the submission file collector, and call `->count` on the result. So if you like, we could go with the `3_3_0` and `3_2_1` PRs you've provided, but wait until #7125 for `main` and avoid the new function. Does that sound OK? (Normally I wouldn't back-port something past 3.3.0 but it sounds like hosting has run into data problems resulting from this, and it's non-invasive, so :+1)

**Comment by ewhanson** [comment]
@asmecher, that sounds great. I'll keep an eye on #7125 and update this once its merged. And yes, the backport to `stable-3_2_1` was specifically for hosting. Thanks!

**Comment by asmecher** [comment]
Great I've merged the two stable branch PRs, and will leave this issue open and scheduled against 3.4.0 for the rest.

**Comment by asmecher** [comment]
@ewhanson, the work on https://github.com/pkp/pkp-lib/issues/7125 is wrapped up, so I think this one is a good candidate for a bit of work to forward-port the fix that's already merged so it's compatible with the `main` branch.

**Comment by ewhanson** [comment]
Thanks @asmecher, I've updated the PR for `main` to use the SubmissionFile repository. Could you have a look?

PR:

- #7480

**Comment by asmecher** [comment]
Merged -- thanks, @ewhanson!
