### ISSUE TITLE
Remove artbitrary UI field length limitations

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#390]
Based on client requests, we are perpetually tweaking the field lengths in the smarty templates (particularly for metadata fields, but could be for arbitrary fields).  E.g., increasing the article title length to 512 characters, then to 1024 characters, the same with issue title lengths.  These limits are not based on database limits.

Why should the UI enforce field limits which are not based on underlying database limits?  Are there external constraints on metadata length that should be considered?

**Comment by asmecher** [comment]
These are largely for historical reasons -- the database used to make use of a lot more schema-defined columns, and now we're using key/value stores in many of those cases. The limits on these fields can generally be removed.

**Comment by ctgraham** [comment]
https://github.com/pkp/ojs/pull/524 was part of this.

**Comment by mpbraendle** [comment]
You should also revisit the user table in lib/pkp/xml/schema/common.xml . E.g. a field length of 40 for salutation may be in several cases not enough (e.g. for professors with several lengthy titles).

**Comment by asmecher** [comment]
@mpbraendle, I've just extended those columns (this will take effect with the upgrade to the next release).

**Comment by NateWr** [comment]
Is anyone aware of any arbitrary UI limits that remain or can this issue be closed?

**Comment by asmecher** [comment]
If there are, this bug entry won't be useful in finding/fixing them. Closing.
