### ISSUE TITLE
About this publishing system -- tiny wording fix

### ISSUE THREAD

**Issue by willinsky** [pkp/pkp-lib#3909]
On [About this Publishing System](https://journals.lib.sfu.ca/index.php/dvv/about/aboutThisPublishingSystem) change "a free-source journal management..." to "an open source (free) software journal management..."

**Comment by asmecher** [comment]
@willinsky, are you sure that's not an automatic (Google) translation from French courtesy of your browser?

**Comment by willinsky** [comment]
@asmecher, I'm so embarrassed, and apologetic for taking up your time.

**Comment by asmecher** [comment]
Not a problem, @willinsky!
