### ISSUE TITLE
Section editors can not access comments to editor discussion

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3910]
When comments to the editor are submitted, a discussion is created. If section editors are automatically assigned to the submission, they are not assigned to the discussion. Likewise, if a new editor is manually assigned to the submission, they are not assigned to the discussion.

It would be useful if an editor could grant access to discussions when assigning any participant. When assigning a participant, they should see a list of discussions to which they can assign the participant. This way, when a copyeditor or production assistant is brought into a submission, they can be granted access to relevant discussions.

- [ ] When an editor is automatically assigned to a submission, they should be assigned to any existing discussions.
- [ ] When a participant is assigned to a submission, it should be possible to assign them to any discussions in their allowed stages.

Original discussion: https://github.com/pkp/pkp-lib/issues/3666#issuecomment-404414305

**Comment by dihagan** [comment]
I would like to see the "Comments for the Editor" participants updated when the submission is completed, as @NateWr mentioned in [#3666](https://github.com/pkp/pkp-lib/issues/3666).  

Authors expect their "Comments for the Editor" to be seen by the editor assigned to their submission; and section editors should be able to have that information available to them as soon as they are notified of the submission. As an editor I'm having to try to check every new submission for comments before my section editors get to them. 
 
Perhaps the comments could be included in the submission acknowledgement if the pre-review discussion is a problem? Including them both places would be better.

Can the addition of new participants to existing conversations be handled separately?  I'm not even sure that's a good idea -- it's fairly easy now to add participants to discussions, and you don't want to make it too easy to add participants to discussions they shouldn't see.

**Comment by NateWr** [comment]
:+1: That's great jonas, thanks!

> But what should happen to the participants list if I later decide to assign a new section editor to the section (or remove the previous section editor)?

It depends on how much time PS wants to devote to this. If you have the time, I think this would still be useful:

> It would be useful if an editor could grant access to discussions when assigning any participant.

I'm thinking of something in the add participant form that shows the discussions and let's the editor check a box to add them to a discussion. I'm less worried about the case of an editor being removed, because I _believe_ they won't have access to the submission at all and this will block access to the discussion.

Having said that, it seems that there isn't really a consensus about this feature. (See @dihagan's comments.) So we may need to discuss it further before implementing.

**Comment by dihagan** [comment]
Thanks @jonasraoni!

> I'm thinking of something in the add participant form that shows the discussions and let's the editor check a box to add them to a discussion. 

This could be useful, I just felt that the initial assignment to section editors was a more essential fix.

**Comment by NateWr** [comment]
Thanks @dihagan! @jonasraoni I'd say go ahead and give us a PR with the fix for the automatic assignments, and we can sort out what we want to do further at a later date.

**Comment by jonasraoni** [comment]
@NateWr sounds good, here it is https://github.com/pkp/pkp-lib/pull/5148

**Comment by NateWr** [comment]
Thanks can you open a PR against `master` too?

**Comment by jonasraoni** [comment]
Done! #5159

**Comment by NateWr** [comment]
Thank you! I'm going to close this issue and we can open a new one if we want to explore a more general solution to assigning new participants to existing discussions.

**Comment by ajnyga** [comment]
What happens if the submission is not finalized? The subeditor will get a notification for a new discussion, but she probably can not access it?

**Comment by NateWr** [comment]
@ajnyga Good question. Can you test? Ideally, I think a discussion should be created with no participants and then when the submission is finalized the participants should be added.

**Comment by jonasraoni** [comment]
@NateWr, I'm just reviewing my open issues, should this one be closed?

**Comment by NateWr** [comment]
Thanks @jonasraoni. Yeah I'll close this and the behaviour will be reviewed as part of #7191.
