### ISSUE TITLE
NATIVE XML ekport/import plugin fails importing/exporting content with new serbian locale @latin

### ISSUE THREAD

**Issue by om-arino** [pkp/pkp-lib#3914]
When i import/export content with rs_SR@latin locale plugin fails, complaining that @latin does not match allowed content. Other content works ok,

Regards, Om 

``

( ! )  Fatal error: Uncaught TypeError: Argument 1 passed to  DOMDocument::importNode() must be an instance of DOMNode, null given in  /var/www/servers/srl/ojs/lib/pkp/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php  on line 258
--

1 | 0.0002 | 402136 | {main}(  ) | .../index.php:0
2 | 0.0089 | 1057136 | Application->execute(  ) | .../index.php:67
3 | 0.0091 | 1065736 | Dispatcher->dispatch(  ) | .../PKPApplication.inc.php:247
4 | 0.0523 | 2371048 | PageRouter->route(  ) | .../Dispatcher.inc.php:134
5 | 0.0557 | 2374832 | PageRouter->_authorizeInitializeAndCallRequest(  ) | .../PKPPageRouter.inc.php:233
6 | 0.0597 | 2391920 | ToolsHandler->importexport(  ) | .../PKPRouter.inc.php:372
7 | 0.0617 | 2575856 | NativeImportExportPlugin->display(  ) | .../PKPToolsHandler.inc.php:98
8 | 0.0618 | 2576984 | NativeImportExportPlugin->exportIssues(  ) | .../NativeImportExportPlugin.inc.php:200
9 | 0.0661 | 2714088 | IssueNativeXmlFilter->execute(  ) | .../NativeImportExportPlugin.inc.php:268
10 | 0.0661 | 2714112 | IssueNativeXmlFilter->process(  ) | .../Filter.inc.php:449
11 | 0.0662 | 2714264 | IssueNativeXmlFilter->createIssueNode(  ) | .../IssueNativeXmlFilter.inc.php:57
12 | 0.0744 | 2820528 | IssueNativeXmlFilter->addArticles(  ) | .../IssueNativeXmlFilter.inc.php:102
13 | 0.0975 | 3080144 | ArticleNativeXmlFilter->execute(  ) | .../IssueNativeXmlFilter.inc.php:192
14 | 0.0976 | 3145728 | ArticleNativeXmlFilter->process(  ) | .../Filter.inc.php:449
15 | 0.4837 | 3253656 | ArticleNativeXmlFilter->createSubmissionNode(  ) | .../SubmissionNativeXmlFilter.inc.php:65
16 | 0.4837 | 3253656 | ArticleNativeXmlFilter->createSubmissionNode(  ) | .../ArticleNativeXmlFilter.inc.php:61
17 | 0.5535 | 3253984 | ArticleNativeXmlFilter->addRepresentations(  ) | .../SubmissionNativeXmlFilter.inc.php:108

**Comment by asmecher** [comment]
@om-arino, try patching https://github.com/pkp/pkp-lib/issues/3873 -- I suspect it's the same issue.
