### ISSUE TITLE
Unable to enter ORCID url

### ISSUE THREAD

**Issue by willinsky** [pkp/pkp-lib#3915]
Pasting in ORCID url for ORCID field on author registration page cuts off last figure if https is used, which is what ORCID now provides. Removing s and adding final digit still provide "invalid" message. In "Edit Contributor" (off Submission page), it works fine if you cut off the s and add the final digit. 

![screen shot 2018-07-14 at 3 10 43 pm](https://user-images.githubusercontent.com/10342108/42728803-67d06c4e-8778-11e8-915b-81e42a827c68.png)

![screen shot 2018-07-14 at 3 11 17 pm](https://user-images.githubusercontent.com/10342108/42728799-5d67b9c4-8778-11e8-8b79-3fa979478c75.png)

**Comment by asmecher** [comment]
@willinsky, what version of OJS? This has been fixed since 3.1.1-0: https://forum.pkp.sfu.ca/t/orcid-field-in-ojs3-does-not-accept-https/32645/5?u=asmecher

**Comment by willinsky** [comment]
Yes, it is 3.1.0.0. I will take this into consideration with any future so-called "bugs" I encounter. Your patience is appreciated.
