### ISSUE TITLE
purchaseInstitutionalSubscription template: change page container element class

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3922]
https://github.com/pkp/ojs/blob/master/templates/frontend/pages/purchaseInstitutionalSubscription.tpl#L13

Currently, the `div` element for page container for purchase institutional subscription page has class `pkp_page_purchaseIndividualSubscription` that not discriminates it from the page with the same name (Default theme, OJS 3.1.1-2).

**Comment by asmecher** [comment]
Thanks for the heads-up, @Vitaliy-1!
