### ISSUE TITLE
[OJS] Review form elements grid, Order feature does not work

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#3926]
Hi there,

the review forms elements grid has a minor bug.

The user can click **Order** and can move the elements around.
But when clicking **Done**, nothing is updated in DB as `GridHandler::getDataElementSequence()` is not implemented / overridden.

As a results the items are displayed in the same order as before.

Should I provide a PR?

So lonG

**Comment by asmecher** [comment]
@ViRuSTriNiTy, thanks for the heads-up -- please do!

**Comment by ViRuSTriNiTy** [comment]
PR added

**Comment by asmecher** [comment]
Merged, thanks for contributing!
