### ISSUE TITLE
Fatal error calling DataObject::getLocalizedData() by reference if only non-locale specific data exists.

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#393]
DataObject::getData() returns mixed; in particular, it returns a string if the data is not localized and locale is NULL.
https://github.com/pkp/pkp-lib/blob/5ec6271b862718b332620240d0e0b07235131403/classes/core/DataObject.inc.php#L85

If DataObject::getLocalizedData() does not find localized data, it calls DataObject::getData() with a NULL locale and then treats the result as an array.
https://github.com/pkp/pkp-lib/blob/5ec6271b862718b332620240d0e0b07235131403/classes/core/DataObject.inc.php#L67

This causes a fatal error when called by reference because there is no reference to an array index of a string.

My particular use-case is OJS 2.4.5 with the authorBios plugin call to getLocalizedBiography() with a mixed dataset of localized and non-localized biographies.
https://github.com/pkp/ojs/blob/f4cf6ed7bb782c0c0a9f0afaa4e6fc1ecfccdd77/plugins/blocks/authorBios/block.tpl#L31
https://github.com/pkp/pkp-lib/blob/b0005fead5591a491e3034ef4debe3634da35ae3/classes/core/DataObject.inc.php#L85
https://github.com/pkp/pkp-lib/blob/b0005fead5591a491e3034ef4debe3634da35ae3/classes/core/DataObject.inc.php#L67

**Comment by asmecher** [comment]
Clinton, I consider mixed localized and non-localized data to be a data error -- do you know where this combination arose from?

**Comment by ctgraham** [comment]
I'm still working on identifying the source.  I have three of two dozen+ installs with between 13 and 10,000 users with the data error.  I post if I find something interesting.

BUT, even though it is a data error it's *also* a code error.  DataObject::getLocalizedData() is calling DataObject::getData() in a context which explicitly returns a string, and then treats it as an array.

**Comment by ctgraham** [comment]
Regarding the source of the data error, for what it's worth, the submission has a history with dates in 2008, long before we even have revision information for this install:

Version history
2.4.5.0 	2014-11-11
2.3.8.0 	2012-10-29
2.3.3.1 	2010-10-14
2.3.1.2 	2010-03-09
2.3.0.0 	2010-03-09

**Comment by asmecher** [comment]
Do you have a PR open for this?

**Comment by ctgraham** [comment]
C.f. https://github.com/pkp/pkp-lib/pull/394

**Comment by asmecher** [comment]
Thanks! Merged.
