### ISSUE TITLE
userSubscriptions template: incorrect if statement on an assigned variable 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3932]
In the Default theme (OJS 3.1.1-2), in a template for user subscription page, `$userInstitutionalSubscriptions` variable is an instance of an object, but for checking whether it includes any institutional subscription is used `{if $userInstitutionalSubscriptions}`: https://github.com/pkp/ojs/blob/master/templates/frontend/pages/userSubscriptions.tpl#L145

This shows the table head even if there are not any data in the table. Should be something like: `{if $userInstitutionalSubscriptions->getCount() > 0} or any other method that is usually used to check if this type of objects contains any items inside.

**Comment by NateWr** [comment]
Closing this as outdated. If you want to keep it flagged as a bug, I can reopen and assign it.
