### ISSUE TITLE
Issues with pages related to subscription

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3933]
I've encountered several small problems with these pages on OJS 3.1.1-2 (Default templates), apart from those described in 2 previous issues. Think they all can go in one issue:

1. `templates/frontend/pages/purchaseInstitutionalSubscription.tpl`: redundant curly braces on line -> https://github.com/pkp/ojs/blob/master/templates/frontend/pages/purchaseInstitutionalSubscription.tpl#L20
This leads to the problem when a user is redirected from a user subscription page by this link: https://github.com/pkp/ojs/blob/master/templates/frontend/pages/userSubscriptions.tpl#L209
The closing bracket appear on the frontend in this case (image attached)

2. `templates/frontend/pages/userSubscriptions.tpl`: different behavior of purchase individual and purchase institutional subscription buttons. The first one is put inside elseif loop, so if there are individual subscriptions this button just dissapears and the respective button appears from the right side of subscription: https://github.com/pkp/ojs/blob/master/templates/frontend/pages/userSubscriptions.tpl#L120
But it's not the case for purchasing institutional subscription button. It will appear in any case: https://github.com/pkp/ojs/blob/master/templates/frontend/pages/userSubscriptions.tpl#L220
Think it should be also wrapped in else-if loop. 

3. `templates/frontend/pages/userSubscriptions.tpl`: pushing renew submission buttons causes fatal error (or maybe I'm missing some checking some option in payments, in this case the button must not be visible): 
`PHP Fatal error:  Interface 'Symfony\\Component\\EventDispatcher\\EventSubscriberInterface' not found in /var/www/ojs-3.1.1-1/plugins/paymethod/paypal/vendor/guzzle/guzzle/src/Guzzle/Http/RedirectPlugin.php on line 19, referer: http://ojs-3.1.1-1.test/index.php/psp/user/subscriptions`
It might be related to: https://github.com/pkp/pkp-lib/issues/2996

4. `templates/frontend/pages/purchaseInstitutionalSubscription.tpl`: if user goes to purchase institutional subscription page from user subscription page by this link: https://github.com/pkp/ojs/blob/master/templates/frontend/pages/userSubscriptions.tpl#L209 in the IP ranges form word `Array` appears (should be empty or actual IP; image attached).
![subscription_issues](https://user-images.githubusercontent.com/20665587/42816753-8171a8e4-89d4-11e8-85f7-1b5fab1b3f42.jpg)

**Comment by asmecher** [comment]
1. Fixed: https://github.com/pkp/ojs/commit/9363b4a47e905f071b8198e925ef79cf05da4ba7
2. Would you mind sending in a PR for this?
3. Can you verify whether `plugins/paymethod/paypal/vendor/guzzle/guzzle/src/Guzzle/Http/RedirectPlugin.php` exists in your repo? It's included in OJS 3.1.1-2. (Or maybe you're hosting from a git checkout?)
4. (Not investigated yet)

**Comment by Vitaliy-1** [comment]
(3) @asmecher It seems that dependencies for PayPal plugin were not resolved for ojs 3.1.1-2 packed release. I used here the latest release from download page:  https://pkp.sfu.ca/ojs/ojs_download/
and after compose update: 
![paypal](https://user-images.githubusercontent.com/20665587/43407310-0db57bf8-9427-11e8-9455-acd93c25ac0e.jpg)

**Comment by asmecher** [comment]
@Vitaliy-1, that's not necessarily unexpected -- e.g. you're using `composer update` rather than `composer install`, and `tools/buildpkg.sh` excludes some parts of the Composer dependencies when building a .tar.gz release package.

**Comment by asmecher** [comment]
@Vitaliy-1, could you send in a PR for the second issue, and verify whether the 4th still applies on the `master` branch?

**Comment by Vitaliy-1** [comment]
The issue with IP ranges remains, although now this input is just empty, will take a closer look.

**Comment by Vitaliy-1** [comment]
The second issue was already fixed.
PR to OJS master: https://github.com/pkp/ojs/pull/2976
