### ISSUE TITLE
reload submission after saving the Schedule For Publication form

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3935]
in order for the pubID plugins to have the actual metadata...

s. https://forum.pkp.sfu.ca/t/ojs3-1-1-0-error-datacite-plugin/45817/5

**Comment by bozana** [comment]
PRs:
ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/2068
master: https://github.com/pkp/ojs/pull/2069

**Comment by asmecher** [comment]
This was already merged into `ojs-stable-3_1_1`, so I resolved a merge conflict on the `master` branch PR and committed it. Closing the issue. @bozana, when you get the chance, please let me know if I missed something here!
