### ISSUE TITLE
Registration page: Minor wording changes

### ISSUE THREAD

**Issue by willinsky** [pkp/pkp-lib#3940]
http://dev-ojs.e-medjournal.com/index.php/sjt/user/register 
CHANGE: “Yes, request the Reviewer role” 
TO: “Yes, I am willing to serve as a reviewer for this journal.” 

CHANGE: “Yes, I agree to have my data collected and stored according to the Policy Statement.” 
TO “Yes, I agree to having my data collected and stored in accord with the publisher's Privacy Statement.”

Also check that throughout "Policy Statement" is changed to "Privacy Statement"

**Comment by mtub** [comment]
Regarding John's last point see also discussion here: https://github.com/pkp/pkp-lib/pull/3761. Happy to go through the code and change it.
