### ISSUE TITLE
JSON responses do not consistently set content-type to application/json

### ISSUE THREAD

**Issue by navotera** [pkp/pkp-lib#3944]
seems like there is vuln as explained in this url : 

https://www.indoxploit.or.id/home/article/1

thanks

**Comment by asmecher** [comment]
Hmm, too bad this wasn't reported to us. The attached patch will correct it by setting the `content-type` -- apply it in the `lib/pkp` subdirectory. (All of the attached patches are the same -- just applied to different release branches.)

**Comment by asmecher** [comment]
Thanks for reporting, @navotera!
