### ISSUE TITLE
[OJS] 3.1.1-2 DB Error: Duplicate entry for key ‘sessions_pkey’

### ISSUE THREAD

**Issue by redukr** [pkp/pkp-lib#3947]
Hello everybody!
i hve next error due to acess to site: DB Error: Duplicate entry for key ‘sessions_pkey’

i have tryied to clean @sessions@ in my DB - no result
i have tryied to repair tables in my DB server - no result
i have tryied to add to .htaccess rows from one of topics at this forum - no result
i have triyed to clean @cache@ folder - no result
tryied to restore DB from backup - no result
tryied to replase OJS files - no result
tryied to fix CHMOD to files and directories, - no result

version of OJS - 3.1.1-2
version of PHP - PHP 5.6.36-1+0~20180715024311.1+jessie~1.gbpa3dade (cli)
verison of apache - Server version: Apache/2.4.10 (Debian)
version of mysql server - Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1
acess to php.ini file - http://uars.info/php.php

[Sat Jul 21 13:33:12.781175 2018] [:error] [pid 1323] [client 192.168.1.105:61697] ojs2: DB Error: Duplicate entry '3sbl6oofs121jg1phjslvc3tt0' for key 'sessions_pkey'
[Sat Jul 21 13:33:12.949519 2018] [:error] [pid 1326] [client 192.168.1.105:61707] PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /web/sites/uars/lib/pkp/classes/session/SessionManager.inc.php on line 35
[Sat Jul 21 13:33:12.950258 2018] [:error] [pid 1326] [client 192.168.1.105:61707] PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /web/sites/uars/lib/pkp/classes/session/SessionManager.inc.php on line 36
[Sat Jul 21 13:33:12.951063 2018] [:error] [pid 1326] [client 192.168.1.105:61707] PHP Notice:  A session had already been started - ignoring session_start() in /web/sites/uars/lib/pkp/classes/session/SessionManager.inc.php on line 58

**Comment by bozana** [comment]
Hi @redukr, I see you have also posted the question in the forum (https://forum.pkp.sfu.ca/t/db-error-duplicate-entry-for-key-sessions-pkey/46786), which is also the right place to start -- if we then figure out it is a bug, a GitHub Issue can be opened. Thus I will close this issue now, and the conversation can continue in the forum...
