### ISSUE TITLE
[OJS] webfeed Plugin rss2 missing XML namespace and date time issue

### ISSUE THREAD

**Issue by isgrim** [pkp/pkp-lib#3948]
Dear PKP-Team,

because a colleague was working with the RSS output of the webfeed plugin, we found that in the current Version of the webfeed Plugin in the template for rss2, there is the XML Namespace for "rdf" missing.

Some parsers ignore this, but we found that for example Firefox browser does not show the feed items, without the correct namespaces.

This line in rss2.tpl:
https://github.com/pkp/ojs/blob/master/plugins/generic/webFeed/templates/rss2.tpl#L12

I would open a PR with the fix for this.

But while checking the XML content, I also found that the date format used is not 100% valid, because it is expected to conform to RFC 822 with an English locale for month and weekday names, but the current version would use the locale of the OJS installation (which is de_DE for us, producing German names). I dont know an easy fix for this except setting the locale before formatting the date time values ?!

Cheers,
Nils

**Comment by isgrim** [comment]
@asmecher Thanks Alec, will try to fix this according to your suggestion and open the PR as soon as its ready.

**Comment by asmecher** [comment]
Good spotting! Why anyone is using a date standard with hard-coded English is beyond me, but anyway.

**Comment by isgrim** [comment]
I won't be able to work on this until September. I am on holiday starting next week.

**Comment by asmecher** [comment]
@ctgraham, does https://github.com/pkp/ojs/pull/2435 fully resolve this one?

**Comment by ctgraham** [comment]
I have not addressed the date/time formatting issue in my PR.

**Comment by asmecher** [comment]
These 3 should take care of the date issues:
- https://github.com/pkp/pkp-lib/pull/4972
- https://github.com/pkp/ojs/pull/2441/files
- https://github.com/pkp/omp/pull/693

@isgrim, if you can give these a look over, I'll get them merged and cherry-picked forward to `master`. Thanks!

**Comment by isgrim** [comment]
@asmecher I just found this issue again, because a colleague mentioned this. Thanks for fixing. I never actually responded.

**Comment by asmecher** [comment]
Forward-ported to the OJS `master` branch for release in OJS/OMP 3.3. (OPS not affected.)
