### ISSUE TITLE
Consider extending Smarty class rather than SmartyBC

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3949]
As I remember, the only problem that I've encountered while testing new Smarty library with OJS 3 was unsupported {php} tags. So, if all of them will be eliminated, there no reason to stick with Backward Compatability Class.

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1, that checks out for me too. Committed, and added PRs for the various theme plugins as well. I'm not sure if there are others?

**Comment by Vitaliy-1** [comment]
There is also Classic theme that is already released. I will make corrections there. I'm thinking about creating a separate branch for Smarty 3 updates

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1 -- see my recommendation on branches over e.g. at https://github.com/NateWr/bootstrap3/pull/99.
