### ISSUE TITLE
HTML 5 compliance

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3950]
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">` 
According to the HTML5 specification, was added new `charset` meta attribute for character encoding information, so it can be specified like `<meta charset="UTF-8">` (https://www.w3.org/TR/2010/WD-html-markup-20100304/meta.charset.html)
Although, I couldn't find their recommendation on a prefered approach.

**Comment by NateWr** [comment]
:+1: Got a PR?

**Comment by NateWr** [comment]
Looks like a PR was merged related to this. Closing.
