### ISSUE TITLE
 OJS PHP7 update error

### ISSUE THREAD

**Issue by Julianosmjl** [pkp/pkp-lib#3952]
I have a problem with php7

Fatal error: Uncaught Error: Call to undefined function xml_parser_create() in /lib/pkp/classes/xml/XMLParser.inc.php:271 Stack trace: #0 /lib/pkp/classes/xml/XMLParser.inc.php(220): XMLParser->createParser() #1 lib/pkp/classes/xml/XMLParser.inc.php(262): XMLParser->parseTextStruct('<?xml version="...', Array) #2 classes/db/XMLDAO.inc.php(55): XMLParser->parseStruct('dbscripts/xml/v...', Array) #3 /lib/pkp/classes/site/VersionCheck.inc.php(76): XMLDAO->parseStruct('dbscripts/xml/v...', Array) #4 /lib/pkp/classes/site/VersionCheck.inc.php(62): VersionCheck::parseVersionXML('dbscripts/xml/v...') #5 /lib/pkp/classes/install/form/MaintenanceForm.inc.php(37): VersionCheck::getCurrentCodeVersion() #6 /lib/pkp/classes/install/form/InstallForm.inc.php(124): MaintenanceForm->di in /lib/pkp/classes/xml/XMLParser.inc.php on line 271

**Comment by asmecher** [comment]
Your PHP is missing XML support; you'll need to either recompile PHP with XML support included, or edit your PHP configuration to add the missing module. Next time, please post general questions on our forum at https://forum.pkp.sfu.ca. Good luck!
