### ISSUE TITLE
Note and track which author fees have been paid

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#3955]
In OJS 2, when an author paid their publication fee, the payment record included the submission ID that the payment was made for, so you could tie it to a particular submission, and the JM or Editor would get a notification that a fee had been paid.  OJS 3 does not have these features and so it’s difficult to determine when the author fee for a publication has been paid. You can go to Payments to see the list of author publication fees paid, but the payments list doesn’t tie a payment to a submission record. Sometimes who pays the fees is not any of the authors on the paper. 

It would be ideal to either add a submission ID column to the Payments table in OJS 3 (although that may not make sense because it would not be relevant for other types of payments) or to be able to open the payment record to see more information about it, including the submission ID (like in OJS 2). 

Another possibility would be to have an indication of payment and link to the payment record somewhere in the submission record.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
