### ISSUE TITLE
[OJS 3.x] No carga la pagina de modulos

### ISSUE THREAD

**Issue by edazao** [pkp/pkp-lib#3956]
Hola a todos:

Estaba trabajando en la configuración de la OJS versión 3.X; pero de repente la pestaña asociada a módulos presenta la información.

Agradezco la ayuda para solucionar este fallo.

Abrazos,

CE.

![captura de pantalla 2018-07-27 a la s 8 48 33 p m](https://user-images.githubusercontent.com/41810157/43351974-0e58bf5e-91e1-11e8-9b11-1f43f1621757.png)

**Comment by asmecher** [comment]
@edazao, what specific version of OJS are you using? What do you find in the PHP error log?

**Comment by condecarolina** [comment]
Tengo el mismo problema. ¿Cómo pudiste resolverlo?

**Comment by asmecher** [comment]
@condecarolina, I have the same questions as above -- what version of OJS are you using? What do you find in the PHP error log?

**Comment by NateWr** [comment]
Closing this as outdated. If you need help with a similar problem, please post in our [community support forum](https://forum.pkp.sfu.ca/c/questions/5).
