### ISSUE TITLE
DC.Creator.PersonalName incorrect if there are Translators among Contributors

### ISSUE THREAD

**Issue by mczirfusz** [pkp/pkp-lib#3962]
If there are translators added as contributors to submissions, DC metadata (DC.Creator.PersonalName) is incorrect:

- one author, one translator: the translator is added to the author, separated with a semicolon; see example here: `view-source:https://tet.rkk.hu/index.php/TeT/article/view/243`;
- two authors, one translator: the first author is correctly displayed, translator is added to the second author, separated with a semicolon; see example here: `view-source:https://tet.rkk.hu/index.php/TeT/article/view/2561`;
- one author, two translators: the first translator is added to the author, as above, the second translator comes into a new line, see example here: `view-source:https://tet.rkk.hu/index.php/TeT/article/view/890`.

**Comment by ctgraham** [comment]
This also affects the public display, Crossref metadata, Citations, etc.

c.f. https://forum.pkp.sfu.ca/t/mix-with-authors-co-authors-and-translators

**Comment by NateWr** [comment]
This no longer appears to be the case. The first example, which is now running 3.3.x, shows two distinct DC metadata entries:

```
<meta name="DC.Creator.PersonalName" content="Benko Georges"/>
<meta name="DC.Creator.PersonalName" content="Barta Györgyi"/>
```
