### ISSUE TITLE
Misleading message when installing a new plugin

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3966]
When installing a plugin from the plugin gallery, the success message says:

> Successfully upgraded to 1.0.0.0.

This should be adjusted so that when installing a plugin for the first time it reflects that.

**Comment by asmecher** [comment]
Are you sure there wasn't maybe an entry already in the `versions` table for the plugin?

**Comment by NateWr** [comment]
Just double-checked with a plugin that definitely had no entries in the `versions` table and it still gave me that message.

**Comment by asmecher** [comment]
Hrm. Which plugin were you installing?

**Comment by NateWr** [comment]
First it was the new Classic theme, to test the `plugins.xml` file. Then I did `plagiarism` (iThenticate).

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
