### ISSUE TITLE
Latest compatible plugin release is not recognized in plugin gallery

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3967]
The plugin gallery will return the oldest compatible release for a plugin, so plugin updates are often not visible.

**Comment by NateWr** [comment]
I changed the comparison so that it always returns the highest version that is compatible. Tempted to self-merge this, but @bozana can you do a quick sanity check on this?

PR:
https://github.com/pkp/pkp-lib/pull/3968
https://github.com/pkp/pkp-lib/pull/3969 (`ojs-stable-3_1_1`)
https://github.com/pkp/pkp-lib/pull/3970 (`omp-stable-3_1_1`)

**Comment by NateWr** [comment]
@asmecher can you do a quick sanity check on this before merging?

**Comment by asmecher** [comment]
Please go ahead, @NateWr, that previous implementation was a thinko.

**Comment by NateWr** [comment]
:+1:
