### ISSUE TITLE
Implement cover image for a journal's section

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#3975]
I'm exploring this possibility for Immersion theme and think that it can make sense also for the OJS core.

**Comment by NateWr** [comment]
Two thoughts:

1. I think this is something that should be activated on a per-theme basis. We could include it in core, but a theme should have to indicate that it supports section images with something in it's `init()` method, like `supports('sectionCoverImage')`. That's a pattern from WordPress that's worked well ([add_theme_support](https://developer.wordpress.org/reference/functions/add_theme_support/)).

2. Did you intend for this to be for section browsing? Or for displaying sections in an issue? If the issue-based approach is still in play, then the section cover images probably need to be defined on a per-issue basis. It would be weird to have the same section cover image for every issue.

**Comment by Vitaliy-1** [comment]
2. @NateWr So, if per issue basis is considered, I believe creating a new table would be more suitable approach. right? I'm planning to populate it with such columns as issue_id, section_id, locale, settings_name and settings_value.

**Comment by NateWr** [comment]
You can create another table, but I'd be inclined to make use of the `issue_settings` table. It will keep things simple. 

You can store arrays/objects in the settings table and they will be serialized. This is not advised for any data that you have to run an efficient query against, but it should be ok for section images/colors.

So I'd recommend storing data like this:

```
$issue->setData('sectionCoverImages', [
  1: '/path/to/image.jpg',
  4: '/path/to/image2.jpg',
]);
```

Where `1` and `4` represent the section IDs. You can have a similar assoc array for `sectionColors`.

(If it needs to be localised, you'd use `setLocalizedData` instead.)

**Comment by Vitaliy-1** [comment]
@NateWr I have started to implement suggested approach for the theme through the hooks. I see that can add array to the issue_settings table through the `execute()` method, as described above. But how the array can be passed through the form and `readUserVars()`?

In the issueForm.tpl originally for the string I have:
```
{fbvElement type="colour" id="immersionColorPick" value=$immersionColorPick maxlength="7" label="plugins.themes.immersion.colorPickInstructions"}
```
I've assigned the array of Section objects there and can iterate like:
```
{foreach from=$sections item=section}
 {fbvElement ...} // how to assign here input to the array
{/foreach}
```

**Comment by Vitaliy-1** [comment]
And for `reafUserVars()` I have:
```
$issueForm->setData('immersionColorPick', $request->getUserVar('immersionColorPick'));
```

**Comment by Vitaliy-1** [comment]
Ended with: 
```
{foreach from=$sections item=section}
  {assign var=sectionId value=$section->getId()}
  {fbvElement type="colour" name="immersionColorPick[$sectionId]" value=$immersionColorPick[$sectionId] label="plugins.themes.immersion.colorPickInstructions"}
{/foreach}
```
Hope this is right approach :)

**Comment by NateWr** [comment]
:+1:

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
