### ISSUE TITLE
Introduce developer mode

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3976]
Add `config.inc.php` settings for developer tools. Some off-the-cuff ideas:
- Permit localhost email addresses (https://github.com/pkp/pkp-lib/issues/3855#issuecomment-403232067)
- Log hook calls (this is verbose)
- Logging SQL queries (this is verbose; would also replace the `debug` mode, which needs replacement as it chokes AJAX calls)
- Inhibit email sending

**Comment by NateWr** [comment]
Some more:

- Log emails when inhibited
- Clear template/css cache with each request
- Log request details, such as what `Handler` was invoked, what authorization checks passed/failed.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
