### ISSUE TITLE
NOTIFICATION_TYPE_REVIEW_ASSIGNMENT_UPDATED notification requires revision

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3983]
Hi,

After revisiting a code I wrote for the open reviews I realized that the NOTIFICATION_TYPE_REVIEW_ASSIGNMENT_UPDATED notification needs a fix.

I originally planned that the notification should be sent both to the reviewer who's assignment details are changed and to the author who's submission is being reviewed. BUT the url in the notification is a reviewer url the author can not access of course.

So should I add an independent notification type for authors OR should we just skip in sending such a notification for the author? 

And secondly, maybe I should add a brief info about the changes that have been made to the assignment? (review type changed / due date changed / review files changed etc.)?

@asmecher?

**Comment by asmecher** [comment]
@ajnyga, I would lean towards not notifying the author. No objections to providing some specifics, if it's easy enough to maintain and localize.

**Comment by asmecher** [comment]
Merged, thanks!
