### ISSUE TITLE
Table controls in TinyMCE not working on modal window

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#3986]
I've enabled table controls in TinyMCE by enabling the table plugin in `lib/pkp/js/controllers/SiteHandler.js`

It's  possible to add/edit tables via the new control but it doesn't work when trying to edit a table in a modal. 
For example, if you try to edit a navigation page  at Settings > Website > Navigation Menus and you place the cursor in the table on the page, clicking on the table control in TinyMCE, you will see that the table button does not correctly display the 'add row', 'add column' controls for the table.
If you switch modal window to full screen (clicking on properly button) it works fine as well.

@NateWr has debugged it and figured out that only modal to navigation page doesn't work, but metadata history does.

**Comment by NateWr** [comment]
After looking into this some, the table control dropdown is rendered far up the page, which is off-screen when the nav menu modal is open and the user has scrolled down some. No idea how to fix it at this time so it will take some looking into -- maybe worth seeing if the new approach to TinyMCE in #3594 fixes this.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
