### ISSUE TITLE
OJS appearance form includes OMP-centric options

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#399]
- manager.setup.newReleases
- manager.setup.displayFeaturedBooks
- manager.setup.displayInSpotlight

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/pkp-lib/pull/400
https://github.com/pkp/ojs/pull/445
https://github.com/pkp/omp/pull/107

Jason, mind giving this a quick review?

**Comment by jnugent** [comment]
Looks good, Alec, although they can't be automatically merged.  Feel free to commit.
