### ISSUE TITLE
Notify editor(s) when any review is completed

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3990]
Currently the editor receives a notification whenever all reviews are complete.
Add an (optional) notification to be sent when *any* review comes in, so that the editor knows there is activity even if e.g. a single reviewer does not respond in a timely fashion.

**Comment by alexxxmendonca** [comment]
This is very important, indeed.

I would assume the Section Editor would be notified as well as long as they are assigned to the paper.

**Comment by ajnyga** [comment]
This is already discussed here I think: https://github.com/pkp/pkp-lib/issues/3423

Basically email notification is already sent for all finished reviews, but there is no task notification until all are in, but Bozana has done something about it already in May: https://github.com/pkp/pkp-lib/issues/3423#issuecomment-380001418

**Comment by asmecher** [comment]
(@bozana, tagging you on this in case you don't have it on your list already!)

**Comment by pmangahis** [comment]
+ from PKP|PS. A client has inquired about email notification for this.

**Comment by pmangahis** [comment]
Would it also be possible to add some identifying information regarding the reviewer and manuscript to this type of notification in the subject or body of the email? Example email subject “Reviewer XXX has submitted comments on MS XXX”).

**Comment by NateWr** [comment]
It seems like this, or something similar, was introduced in #3423. If you feel that something is still missing, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
