### ISSUE TITLE
IssueEntryTabHandler causing a warning when no pubId plugins are active

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3992]
When no pubId plugins are enabled, this line
https://github.com/pkp/ojs/blob/master/controllers/tab/issueEntry/IssueEntryTabHandler.inc.php#L143

causes this warning:
`PHP Warning:  Invalid argument supplied for foreach() in /controllers/tab/issueEntry/IssueEntryTabHandler.inc.php on line 143
`
OJS 3.1.1.2

**Comment by asmecher** [comment]
Merged -- thanks, @ajnyga!
