### ISSUE TITLE
Static Pages management tab does not load

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3998]
In OJS 3.1.1-2 after enabling the Static Pages plugin and navigating to the Settings > Website > Static Pages tab, the management page is not displayed and a "Loading" message is displayed instead.

![static_pages](https://user-images.githubusercontent.com/200793/44280526-05395a80-a223-11e8-940b-f6d3274c3a2f.png)

**Comment by asmecher** [comment]
@mfelczak, is anything relevant in the PHP error log or browser console? I suspect there's a JS error.

**Comment by mfelczak** [comment]
Hi @asmecher, just a generic JS error in the console

```
SyntaxError: invalid escape sequence jquery.js:1
globalEval/<
http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js:339:5
globalEval
http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js:338:6
domManip
http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js:5931:9
append
http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js:5704:10
html/<
http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js:5830:5
jQuery.access
http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js:4108:5
html
http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js:5794:10
load/</<
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.js:15679:7
```

**Comment by asmecher** [comment]
@mfelczak, can you privately share a URL with me?

**Comment by ptrckb** [comment]
I think this has been fixed by pkp/staticPages@c7d0501902ae61d672a0440384e0af47ffde06ef

**Comment by asmecher** [comment]
Yes, that would explain it -- @mfelczak, please re-open if that doesn't do it for you.

**Comment by Laurencepublisher** [comment]
@asmecher https://jqcode.space/questions/how-to-include-loading-animation-in-jquery-ui-ajax-tabs
