### ISSUE TITLE
Usagestats not being processed if contextPath collides with "article"

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4009]
See: https://forum.pkp.sfu.ca/t/single-journal-in-multi-journal-installation-not-creating-statistics/47569

Fix in a moment...

**Comment by ajnyga** [comment]
pr: https://github.com/pkp/ojs/pull/2105

**Comment by ajnyga** [comment]
Magic! But I guess when you just compare two strings, that would work (I have a bad habit of using that a lot).

**Comment by asmecher** [comment]
The proposed fix makes sense to me (caveat: limited knowledge of stats code) and I've merged it and back-ported to `ojs-stable-3_1_1`. I added a comment at https://github.com/pkp/ojs/pull/2105#issuecomment-419206189 for potential broader review. Thanks, @ctgraham and @ajnyga!
