### ISSUE TITLE
[OJS] multi-byte issue in geoipcity.inc 

### ISSUE THREAD

**Issue by stuartyeates** [pkp/pkp-lib#401]
There is a multi-byte issue in geoipcity.inc. Please see attached patch.

``````
diff /var/www/ojs/plugins/generic/usageStats/lib/geoIp/geoipcity.inc*
130,134c130,132
<   $enc = "";
<   if (defined('ENABLE_MBSTRING')) {
<     $enc = mb_internal_encoding();  
<     mb_internal_encoding('ISO-8859-1'); 
<   } 

---
>   $enc = mb_internal_encoding();
>   mb_internal_encoding('ISO-8859-1'); 
> 
211,213c209
<   if (defined('ENABLE_MBSTRING')) {
<     mb_internal_encoding($enc);
<   }

---
>   mb_internal_encoding($enc);```
``````

**Comment by asmecher** [comment]
Stuart, at a glance it looks to me like this patch is generated backwards?

**Comment by stuartyeates** [comment]
Oops, sorry

    diff ojs/plugins/generic/usageStats/lib/geoIp/geoipcity.inc~ ojs/plugins/generic/usageStats/lib/geoIp/geoipcity.inc
    130,132c130,134
    <   $enc = mb_internal_encoding();
    <   mb_internal_encoding('ISO-8859-1'); 
    < 
    ---
    >   $enc = "";
    >   if (defined('ENABLE_MBSTRING')) {
    >     $enc = mb_internal_encoding();  
    >     mb_internal_encoding('ISO-8859-1'); 
    >   } 
    209c211,213
    <   mb_internal_encoding($enc);
    ---
    >   if (defined('ENABLE_MBSTRING')) {
    >     mb_internal_encoding($enc);
    >   }

**Comment by asmecher** [comment]
Stuart, is this to work around a situation where the server doesn't have the mbstring functions installed?
I hesitate to merge this because it's a modification of 3rd-party code, and not something we wrote. Shipping modified 3rd-party code is a problem e.g. for Debian packaging.
