### ISSUE TITLE
[OJS] Custom blocks not displayed in settings page after upgrading from OJS2.4.8 to 3.1.1.2

### ISSUE THREAD

**Issue by alireza08** [pkp/pkp-lib#4011]
Hi,
I upgraded our website from OJS 2.4.8 to 3.1.1.2 and the problem is that custom blocks are displayed on website homepage but I can not see them in the settings/appearance page for re-ordering. I tried enabling and disabling the custom block plugin which did not help. I also added a new custom block but even this newly added block is not displayed in settings page.
any ideas?

**Comment by asmecher** [comment]
@alireza08, can you double-check your OJS version? There was an issue like what you're describing in OJS 3.1.1-0 and possibly 3.1.1-1, but I think it was resolved in 3.1.1-2.

**Comment by alireza08** [comment]
@asmecher yes this is the code version: 

```
OJS 3.1.1-2 Release Notes
Git tag: ojs-3_1_1-2

Release date: June 11, 2018
```

our website was first updated to OJS 3.1.1-1 and this problem existed. Then, I updated to OJS 3.1.1-2 and this persists.

**Comment by asmecher** [comment]
@alireza08, have you installed the plugin someplace nonstandard? Is there an entry for it in the `versions` table?

**Comment by alireza08** [comment]
@asmecher , No it is an original version with default files and paths and I have set full permission for it.
This is from `versions` table:

```
(3, 1, 1, 1, '2018-08-25 18:02:51', 0, 'core', 'ojs2', '', 0, 1),

(3, 1, 1, 2, '2018-08-25 20:29:55', 1, 'core', 'ojs2', '', 0, 1),

(1, 1, 0, 0, '2015-09-30 11:34:44', 0, 'plugins.generic', 'customBlockManager', 'CustomBlockManagerPlugin', 1, 0),

(1, 2, 0, 0, '2018-08-25 18:09:31', 1, 'plugins.generic', 'customBlockManager', 'CustomBlockManagerPlugin', 1, 0);
```

**Comment by asmecher** [comment]
@alireza08, sorry for the delay in responding. Is this still an issue?

**Comment by alireza08** [comment]
Yes, I couldn't figure it out.

**Comment by asmecher** [comment]
Is there anything in the server log when you visit the appearance form?

**Comment by alireza08** [comment]
nothing specific. there are a lot of errors on missing css files and js scripts in the log that are from OJS2.
```
[Thu Oct 11 10:08:45 2018] [error] [client ...] File does not exist: /var/.../js/inlinePdf.js, referer: http://.../article/view/71/author
[Thu Oct 11 10:08:45 2018] [error] [client ...] File does not exist: /var/..../styles/articleView.css, referer: http://...../article/view/71/author
```

**Comment by asmecher** [comment]
This was also just reported [on the forum](https://forum.pkp.sfu.ca/t/problem-sidebar-managment-ojs3-1-1-4) -- interestingly it's only applying to a single journal. Do you have a single-journal installation or multi-journal? Can you think of any particular unusual configuration on your system, e.g. the use of a less common plugin or something similar?

**Comment by alireza08** [comment]
All our websites are single journals. I went through the database inside `plugin_settings` and `journal_settings` and `versions` tables and tried to check different conditions manually. but everything seems fine. may be it is the called API , I didn't go there.
By the way, why do you think there are calls to OJS2 css and js files in OJS3? these files are not found and just filling the log file.

**Comment by asmecher** [comment]
> By the way, why do you think there are calls to OJS2 css and js files in OJS3? these files are not found and just filling the log file.

I don't think these references exist in OJS any more -- the likeliest cause is that something in the wild has cached that URL from when OJS2 was running.

**Comment by mejiamariod** [comment]
I made the last post in [the forum](https://forum.pkp.sfu.ca/t/problem-sidebar-managment-ojs3-1-1-4), I still can not find a solution but this can be useful:

Before migrating to 3.1.1-4 in version 2.4.8 there were custom blocks of a single journal created with a name that contained spaces, for example: "Information of interest" ... in the new version when wanting to modify them not they were left to be deleted or edited, by clicking on those buttons the action seemed like clicking on a link assigned the symbol '#'.

The only way to delete them was to do it from the database, but it did not solve the problem.

In the management of the sidebar to which sql table does the query?

**Comment by mejiamariod** [comment]
Aún no se encuentra solución para esto... que lástima

**Comment by asmecher** [comment]
@mejiamariod, in answer to your question:
> In the management of the sidebar to which sql table does the query?

This will probably change with OJS 3.2, but for all OJS 3.x releases before that, the sidebar blocks are configured in `plugin_settings`. There are necessary settings for the custom block manager plugin:

```
mysql> select * from plugin_settings where plugin_name='customblockmanagerplugin';
+--------------------------+------------+--------------+------------------------------------+--------------+
| plugin_name              | context_id | setting_name | setting_value                      | setting_type |
+--------------------------+------------+--------------+------------------------------------+--------------+
| customblockmanagerplugin |          1 | blocks       | a:2:{i:0;s:3:"one";i:1;s:3:"two";} | object       |
| customblockmanagerplugin |          1 | enabled      | 1                                  | bool         |
+--------------------------+------------+--------------+------------------------------------+--------------+
2 rows in set (0.00 sec)
```
You will see `context_id` corresponding to your `journal_id`, then each custom block listed by name under `setting_name='blocks'`. Entries like this will be repeated for each journal.

Then you will also see entries for each custom block, by name:
```
mysql> select * from plugin_settings where plugin_name in ('one', 'two');
+-------------+------------+--------------+---------------------------------------------+--------------+
| plugin_name | context_id | setting_name | setting_value                               | setting_type |
+-------------+------------+--------------+---------------------------------------------+--------------+
| one         |          1 | blockContent | a:1:{s:5:"en_US";s:17:"<p>Number One</p>";} | object       |
| one         |          1 | context      | 1                                           | int          |
| one         |          1 | enabled      | 1                                           | bool         |
| two         |          1 | blockContent | a:1:{s:5:"en_US";s:17:"<p>Number Two</p>";} | object       |
| two         |          1 | context      | 1                                           | int          |
| two         |          1 | enabled      | 1                                           | bool         |
+-------------+------------+--------------+---------------------------------------------+--------------+
6 rows in set (0.00 sec)
```
In these entries:
- As above, `context_id` must match your `journal_id`
- `setting_name='context'` should be `1`, to indicate the sidebar (this is currently the only supported value)
- `plugin_name` should match the names listed in the `setting_name='blocks'` setting listed above
- `plugin_name` should be all lower case and not include any spaces

**Comment by asmecher** [comment]
For everyone encountering this problem, you can apply https://github.com/asmecher/pkp-lib/commit/5ef2c495be4927cf55077a31cb0a4563b7bf2d62 in `lib/pkp` to resolve it. I've committed this to git `master`, `ojs-stable-3_1_1`, and `omp-stable-3_1_1` branches, so if you're using git you can either cherry-pick it in or update to the latest from those branches.

**Comment by marcbria** [comment]
I confirm the issue with last release (ojs-stable-3_1_2_1).
Blocks names where uppercase and include spaces.
Only a few blocks so I removed every reference to "customblocks" in plugin_settings table, and added the blocks again manually (cut&paste from former version).

**Comment by marcbria** [comment]
Fall again with this issue some years after. 

Summarizing to close the issue with a workaround.

Process would be:
0. Backup the DB.
1. Save the content of the existing blocks.
2. Disable the CustomBlock plugin.
3. Remove all the customblock information in the DB (see Alec's queries below just replace "SELECT *" with "DELETE").
```
SELECT * FROM plugin_settings WHERE plugin_name='customblockmanagerplugin';
SELECT * FROM plugin_settings WHERE plugin_name IN ('one', 'two');
```
4. Reenable the CustomBlock plugin to create the required rows.
5. Recover the missing blocks.

Sounds like an inconsistency in the DB info so a better solution would be modify the wrong rows... but I didn't save the initial table to compare.
