### ISSUE TITLE
[OJS] "Submitter" cannot access it's own submission in production stage

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#4012]
Hi there,

we have the following account setup:

- Role with name *Submitter* and *Submission* permissions only
- *User X* assigned to Role *Submitter*

Now, lets say *User X* submits an article. Due to the OJS workflow this article then gets passed through the review process up to production stage. In the production stage the article is displayed as *Production* in the submission list.  When the user now clicks on the article in the submission list, the browser opens the review process page with the production stage tab but the user now gets several error messages like

> You don't currently have access to that stage of the workflow.

because the role *Submitter* does not have *Production* permissions.

Now i wonder why the production stage tab is opened in the first place? Is this feature still work in progress or is it a bug?

So lonG

**Comment by t4x0n** [comment]
Hi @ViRuSTriNiTy , the problem is that you restricted the author's permissions!  when you say Submitter I think in an author, and as an author, he/she must be able to follow all manuscript process. 

the support forum (https://pkp.sfu.ca/support/forum) is the best place for this kind of questions

**Comment by ViRuSTriNiTy** [comment]
@asmecher @t4x0n Thank you, we will fix the permissions then.
