### ISSUE TITLE
[OJS] Canot Stream PDF 

### ISSUE THREAD

**Issue by desawarna** [pkp/pkp-lib#4013]
I use **OJS 3.0.2.0**

I put the PDF file in `/ files`

PDF can be downloaded, but cannot stream on the browser,

What should I do ?

thanks :smile: :smile: 

![canot-stream-pdf](https://user-images.githubusercontent.com/1111630/44634436-56d0aa80-a9c4-11e8-8d84-3358d8419c1f.png)

**Comment by asmecher** [comment]
@desawarna, for next time, the support forum (https://pkp.sfu.ca/support/forum) is the best place to start with general debugging.

Is `files` located within your web root? If so, unless you've protected it with a `.htaccess` document or similar from direct download, it's likely a dangerous configuration. See "Recommended Configuration" in `docs/README`.

Did you upgrade your OJS from a previous version, or move it to a different server, or another administration activity that might have caused this?
