### ISSUE TITLE
Page numbers not appearing correctly on "how to cite"

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#4022]
Article page numbers are not appearing correctly on the "how to cite".

Example: this paper has 18 pages and on the "how to cite" appears as "1-8" instead of "1-18".

![image](https://user-images.githubusercontent.com/4059679/44802771-f6439800-ab92-11e8-8425-6ee43df0788c.png)

http://repository.scielo20.org/documents/article/view/85

**Comment by asmecher** [comment]
@alexxxmendonca, what version of OJS are you using?

**Comment by alexxxmendonca** [comment]
Apologies for lack of information: version 3.1.1-2.

**Comment by asmecher** [comment]
This looks like a bug in the citeproc-php library we use for citation formatting. Filed here: https://github.com/seboettg/citeproc-php/issues/60
