### ISSUE TITLE
Quote mark appearing as &quot on "How to cite"

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#4023]
Instead of appearing the quote mark itself, the system is showing a **&quot** on the "How to cite" feature:

![image](https://user-images.githubusercontent.com/4059679/44802825-1ecb9200-ab93-11e8-86a1-e44b818943fe.png)

http://repository.scielo20.org/documents/article/view/93

**Comment by asmecher** [comment]
@alexxxmendonca, what version of OJS are you using?

**Comment by alexxxmendonca** [comment]
Apologies for lack of information: version 3.1.1-2.

**Comment by diegoabadan** [comment]
Hi @asmecher ,

We have an example here:
https://revistadpers.emnuvens.com.br/defensoria/article/view/193

See the title inserted in the metadata:

![image](https://user-images.githubusercontent.com/15090895/106051246-f8451480-60c6-11eb-926b-050cb0fc713f.png)

And there is the problem that Alex reported.

I noticed that OJS converts to HTML when viewing the page's source code. An example:
`<meta name="DC.Title" content="Falsas memórias: Discussões acerca da prova penal a partir de &quot;The Good Wife&quot; "/>`

**Comment by asmecher** [comment]
Can anyone confirm that this is still a problem in OJS 3.3.0-9 or newer? I've tried locally and I can't replicate the problem. I suspect an update to citeproc-php may have fixed it in the meantime.

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this in a more recent version, please provide reproduction steps in a comment below.
