### ISSUE TITLE
Ensure RoleBasedHandlerOperationPolicy is used where addRoleAssignment is used

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4024]

**Comment by asmecher** [comment]
PRs/commits (master branch):
- https://github.com/pkp/pkp-lib/pull/4028
- https://github.com/pkp/ojs/pull/2110
- https://github.com/pkp/staticPages/commit/5b5eaac7c4a2c3f21dc29445b5bf50957cb82036
- https://github.com/pkp/customBlockManager/commit/13a4f753e197113752bc06e4a5eff0f9653a3f42
- https://github.com/pkp/translator/commit/ff153f5cb4733ce9723c0cf819f3aab78e14f370

**Comment by ctgraham** [comment]
This didn't make it (or didn't completely make it) into 3.1.1-4.  See: https://forum.pkp.sfu.ca/t/problem-when-uploading-site-logo/50132/6?u=ctgraham

E.g.:
https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/controllers/tab/settings/AdminSettingsTabHandler.inc.php#L28
vs.
https://github.com/pkp/pkp-lib/blob/ojs-3_1_1-4/controllers/tab/settings/AdminSettingsTabHandler.inc.php#L28
