### ISSUE TITLE
[OJS] Reviewer step 1, privacy consent error message is displayed as ##...##

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#4026]
Hi there,

this is a follow up of issue #3870.

The commits of the aforementioned issue mask the *missing* error translation. To reproduce this, just remove `privacyConsent` from `readInputData()` and try submit the form. It will still display `##...##` as an error message. To fix this the form needs to call `AppLocale::requireComponents(LOCALE_COMPONENT_PKP_USER)` as the translation is stored in `user.xml`. On other pages this is done by the handler or by some template stuff but in this case it is not. 

So i've added 

	/**
	 * @see Form::validate()
	 */
	function validate($callHooks = true) {
		AppLocale::requireComponents(LOCALE_COMPONENT_PKP_USER); // for user.profile.form.privacyConsentRequired

		return parent::validate($callHooks);
	}

and the message appears correctly.

Should i provide a PR?

So lonG

**Comment by asmecher** [comment]
@ViRuSTriNiTy, yes, please do -- it's best to send it to the `master` branch, and I'll take care of cherry-picking as needed.

**Comment by asmecher** [comment]
Merged -- thanks, @ViRuSTriNiTy!

**Comment by hblancoca** [comment]
I have installed 3.1.1.2 and have the same error with a some but not all  revisors. The form do not show the checkbox for consent. and when submit the first step appears the error about user privacy Consent Required.

Any idea? really appreciate your help

**Comment by hblancoca** [comment]
ViRuSTriNiTy: that its the code:
{* Privacy Statement *}
	{fbvFormSection list="true"}
		{capture assign="privacyUrl"}{url router=$smarty.const.ROUTE_PAGE page="about" op="privacy"}{/capture}
		{capture assign="privacyLabel"}{translate key="user.register.form.privacyConsent" privacyUrl=$privacyUrl}{/capture}
		{fbvElement type="checkbox" id="privacyConsent" required=true value=1 label=$privacyLabel translate=false checked=$privacyConsent}
	{/fbvFormSection}

But appears for certain users.
I cant understand Why

Humberto,

**Comment by ViRuSTriNiTy** [comment]
Did you clear the template cache after updating to 3.1.1.2? I think this might be the issue here otherwise i'm out of ideas really.
