### ISSUE TITLE
Missing Translations (Spanish)

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#4029]
##user.register.form.privacyConsent##
##user.register.form.emailConsent##
##user.reviewerPrompt.optin##

**Comment by t4x0n** [comment]
Hi @marcbria, 
can you provide some translation? To help you I pasted below the chain of text in English, and indicated the file in which you can find those:

**pkp-lib**/locale/en_US/user.xml
<message key="user.register.form.privacyConsent"><![CDATA[Yes, I agree to have my data collected and stored according to the <a href="{$privacyUrl}" target="_blank">privacy statement</a>.]]></message>

**pkp-lib**/locale/en_US/user.xml
<message key="user.register.form.emailConsent">Yes, I would like to be notified of new publications and announcements.</message>

**ojs**/locale/es_ES/locale.xml
<message key="user.reviewerPrompt.optin">Yes, I would like to be contacted with requests to review submissions to this journal.</message>

**Comment by marcbria** [comment]
Hi,

Thanks Kevin to rise it up and Carlos for the search.

I took a look and the 3 chains are included in the last delivery we made before vacations, and @mtub merged them all against **master** branch. Please, Marco, correct me if I'm talking rubbish.

* ##user.register.form.privacyConsent##
  * https://github.com/pkp/pkp-lib/blob/41208054f717490fb2eddd841661f57c4e81e0bc/locale/es_ES/user.xml#L163

* ##user.register.form.emailConsent##
  * https://github.com/pkp/pkp-lib/blob/41208054f717490fb2eddd841661f57c4e81e0bc/locale/es_ES/user.xml#L164

* ##user.reviewerPrompt.optin##
  * https://github.com/pkp/ojs/blob/7e4bf0c24489253196b03118873b2a174d8a0cf7/locale/es_ES/locale.xml#L974

Any way, thanks for the advice. We like to keep es_ES translation as complete as we can.

Cheers,
m.

**Comment by Moradnejad** [comment]
I can't find user.reviewerPrompt.optin anywhere. Are you sure it is included in English?

@carzamora @marcbria

**Comment by carzamora** [comment]
Hi @Moradnejad, 

is here in the English file: https://github.com/pkp/ojs/blob/4a71d1835e842d0e405f2683c773425331874981/locale/en_US/locale.xml#L205

**Comment by Moradnejad** [comment]
Thanks @carzamora

**Comment by marcbria** [comment]
If I remember well, all this was fixed.
@asmecher , do you mind to close the issue?

**Comment by asmecher** [comment]
Sure!
