### ISSUE TITLE
Permit nonresponsive reviewers to be "dismissed"

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4035]
When a reviewer confirms a review but does not complete it, it will be flagged as an overdue review. However, there is no way to "dismiss" the reviewer, so the alerts continue appear for editors (and authors).

Add a tool to record that a reviewer is not expected to respond, which can clear the alerts for editors and authors. It should include an optional email to the reviewer. Ideally this would also allow for an indication of nonresponsiveness for when the reviewer comes up in later searches, e.g. by allowing a low star rating to be assigned.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
