### ISSUE TITLE
Reviewers receive a 0 rating when a review assignment is accepted

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4036]
Steps to reproduce:

1. Create new reviewer.
2. Assign reviewer to a review.
3. Login as reviewer.
4. Accept review (but don't complete it).

What happens:

When assigning this reviewer to another review, they have a 1/5 star rating. When looking at the review assignment in the database, it has a `0` value for `quality`.

What should happen:

A review assignment should have a `NULL` value for `quality` until an editor manually rates the review assignment.

To correct past inaccurate data, we should reset all `0` quality ratings to `NULL` during the update process:

```
update review_assignments set quality=NULL where quality=0;
```

**Comment by asmecher** [comment]
@NateWr, would you mind having a look at this? The material change is the removal of an int cast in the OJS PR. This pointed to some really outdated code we're still using; I've filed some later cleanup at https://github.com/pkp/pkp-lib/issues/4040.

**Comment by NateWr** [comment]
:+1: looks good!

**Comment by NateWr** [comment]
> I suggest back-porting to 3.1.1 and relying on the existing reset.

That makes sense, but there will be bad data from people who have already upgraded to 3.1.1, since those upgrade scripts won't be run again, right? Maybe we can include something with 3.2?

**Comment by asmecher** [comment]
Merged and ported back to `ojs-stable-3_1_1`.

I'm leaning against selectively clearing the data; we would need to clear data only from 3.1.1-0 to 3.1.1-2 (this data will be fine for 2.x upgrades, for example), and clearing in that range would certainly take out good data with bad (the 0 is introduced on reviewer acceptance, so editors making heavy use of the rating feature will already be correcting it on review completion). IMO the cure is worse than the problem.

**Comment by NateWr** [comment]
I _think_ we can safely clear any ratings that are set to `0`. I don't believe it's possible to give a `0` rating between `3.1.1-0` and `3.1.1-2`. It should always be `NULL` or `1-5`. So I think the following would only clear out bad ratings:

```
update review_assignments set quality=NULL where quality=0;
```

I'd push for us to consider this because showing an incorrect 1-star rating could be pretty bad from a professional perspective. Consider the following scenario. I am a new section editor for a journal. I go to assign a colleague of mine as a reviewer, and I see that they have a 1-star rating for reviews. I do not have access to their past review history, so I begin to speculate on why they have a low rating. Are they unreliable, unkind, abusive?

It will only effect a tiny portion of installations, but there is the potential for it to have a significant impact on a single individual. So I'd argue for cleaning it up, even if that's just part of 3.2.

**Comment by asmecher** [comment]
Looks like you're right, @NateWr! I've committed that change, thanks.
