### ISSUE TITLE
Issue Data - Title Only Not Linked

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#4041]
When a journal has added issue data for volume, number, year, and title, but ONLY checked the Title checkbox, the issue entry is displayed on the public Archives page, but it is not linked.

**Comment by asmecher** [comment]
@NateWr, are the linked commits referencing the wrong issue number?

**Comment by NateWr** [comment]
Oh... Those are meant to go to #4081 and were done at the 2018 sprint in Heidelberg. I blame the frenetic pace of the sprint!

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
