### ISSUE TITLE
Editorial history should save the datestamp when a new review round starts

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4042]
At the moment it is hard to determine what has happened during review round 1 and what during review round 2.

**Comment by ajnyga** [comment]
Ok, so when you start a new review round, the editorial history says "An editor decision (Resubmit for Review) for article 48 was recorded by admin admin." which is the exact same entry as the one you get when you actually record a decision like that. This is a bug right?

**Comment by ajnyga** [comment]
@NateWr what do you think? I could do a quick pr for the new message if you agree.

**Comment by ajnyga** [comment]
That does not sound right, doing a "resubmit for review" decision and starting a new review round are really two totally different things. 

When an editor does a "resubmit for review" decision on Round 1, the editor explains to the author the changes needed based on review reports from round 1. The author then sends the new version of the manuscript including those changes to the Revisions box in round 1 and after that the editor starts a new review round using the changed manuscript (however, now the editorial history shows two "Resubmit for Review" decisions which does not make sense => the author has already resubmitted and a new review round has already started).

This is also indicated in Learning OJS although there is no example for a two round review: https://docs.pkp.sfu.ca/learning-ojs/en/editorial-workflow#review
"Resubmit for Review: This will require the Author to make major changes and another round of review will need to take place."

The editorial decision "resubmit for review" does not open a new round. It is just an indication that major revisions are needed, just a label really. Even if I do a "resubmit for review" decision, I can still just accept the changed manuscript without starting a new round.

**Comment by NateWr** [comment]
> Even if I do a "resubmit for review" decision, I can still just accept the changed manuscript without starting a new round.

My understanding is that "revisions requested" should be used when revisions are not expected to require another round of review. The ambiguity between these two is obviously a source of confusion.

**Comment by ajnyga** [comment]
Yes "revisions requested" is usually used if no new review round is expected. I just wanted to underline that the decision there is just a label.

If I do a "revisions requested" decision, I can still start a new review round when the revisions arrive
If I do a "resubmit for review" decision, I can still just accept the revised article without the new round.

If I would decide, I would change the labels to "Minor revisions" and "Major revisions".

**Comment by ajnyga** [comment]
@asmecher do you have time to check this. 

If I am wrong on the issue, then I have to quickly revise the translation for the Learning OJS guide and I think the original English version also needs some clarification (I think having the whole Round 2 process explained in the guide would be a good thing).

**Comment by ajnyga** [comment]
sorry for bugging you @asmecher but I am planning to continue translating the Learning OJS3 guide for the editors and having the above question solved would be nice...

**Comment by asmecher** [comment]
Sorry for the delay, @ajnyga! I agree with your first proposal, to log a "new review round" message that's distinct from "revisions requested". The major/minor distinction could be useful, but I'm hesitant to introduce new language when it's not used elsewhere.

**Comment by ajnyga** [comment]
Hi, the major/minor was really a secondary issue here. The main point is definitely that starting a new review round != resubmit for review decision, because that decision should have already taken place before the new review round is created.

I will make a pr where I suggest a new editor decision "SUBMISSION_EDITOR_DECISION_NEWROUND" and we can continue the discussion based on that.

**Comment by ajnyga** [comment]
@asmecher this is probably not solved yet? I see someone promised a pr back in sep 2018, but has not delivered...

**Comment by asmecher** [comment]
I don't think anyone has stepped on someone's toes yet :)

**Comment by ajnyga** [comment]
Can you assign this to me so I fo not forget!

**Comment by asmecher** [comment]
Done, thanks!

**Comment by ajnyga** [comment]
@asmecher 
ojs: https://github.com/pkp/ojs/pull/2697
pkp-lib: https://github.com/pkp/pkp-lib/pull/5677

If that looks good, I will prepare a pr for OMP as well. OPS does not require this.

**Comment by asmecher** [comment]
Thanks, @ajnyga, this looks good -- please prepare an OMP PR and I'll merge all three.

**Comment by ajnyga** [comment]
omp: https://github.com/pkp/omp/pull/794
tests running...

**Comment by ajnyga** [comment]
@asmecher one test failed here: https://github.com/pkp/omp/pull/794 if you can restart

**Comment by asmecher** [comment]
^ Restarted and passed! Is this ready for merge, @ajnyga?

**Comment by ajnyga** [comment]
Yes, this is all ready

**Comment by asmecher** [comment]
Thanks, @ajnyga (& @NateWr)! Merged to pkp-lib `master`, and manually to OJS and OMP `master` for release in OJS/OMP 3.1.1.
