### ISSUE TITLE
[OJS] lib/pkp/tools/buildjs.sh is not working in Windows Subsystem for Linux / Debian

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#4043]
Hi there, 

as already discussed in the [forums](https://forum.pkp.sfu.ca/t/ojs-3-how-to-recompile-pkp-min-js/48252) the script `lib/pkp/tools/buildjs.sh` does not work correctly in Windows Subsystem for Linux / Debian. The issue is the `sed` call whereas matching `(function(\$) {` does not work.

I will provide a PR.

So lonG
Daniel

**Comment by asmecher** [comment]
Thanks, @ViRuSTriNiTy -- this checks out for me in my Debian environment as well. Merged!
