### ISSUE TITLE
Cannot upload plugin

### ISSUE THREAD

**Issue by GasparPizarro** [pkp/pkp-lib#4049]
I just did a checkout of the OJS repo, checkout c83397088eebe1e63dcffc4af3fde87517105e7a, and did everything, create an admin, and when I try to upload a plugin as admin user (the first one I create, in the installation step), and the system responds with 

    The current role does not have access to this operation+

So I cannot upload plugins. Nevertheless, I can upload plugins successfully when downloading the production release (https://pkp.sfu.ca/ojs/download/ojs-3.1.1-2.tar.gz).

**Comment by asmecher** [comment]
@GasparPizarro, try fetching the latest code in the submodule in `lib/pkp`.

**Comment by asmecher** [comment]
(Closing pending further follow-up)
