### ISSUE TITLE
Add support for OJS 2.4.x-style metadata uploads for supplementary files

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#405]
For Dataverse (and presumably for the front-end, and for academic concerns) we need to attach richer metadata than is currently possible to supplementary files. Currently uploads in OJS pre-3.0 can either have a title (submission file) or artwork-related metadata (artwork files); suggest adding a third for supplementary content that includes a similar set to what was used in OJS 2.x.

**Comment by asmecher** [comment]
Bruno, could you review this? I'll present it at Thursday's UI/UX call:

https://github.com/pkp/pkp-lib/pull/418
https://github.com/pkp/ojs/pull/452

After that, if it looks good, I'll ask Kevin to put together some test data and work on a migration strategy from OJS 2.x.

**Comment by asmecher** [comment]
(@axfelix, you might want to take this for a spin)

**Comment by axfelix** [comment]
Noted!
