### ISSUE TITLE
Overridden plugin templates in theme not shown in child theme

### ISSUE THREAD

**Issue by mittinatten** [pkp/pkp-lib#4054]
Hi,
If a theme plugin overrides a template from another plugin, i.e. has a file `templates/plugins/.../templates/foo.tpl`, it will be shown correctly when using the theme itself, but in child themes the original template will be used instead. Copying the template from the parent theme to the child theme solves the issue.

See this issue for a specific example: https://github.com/pkp/healthSciences/issues/107

Simon

**Comment by asmecher** [comment]
@mittinatten, what version of OJS are you using?

**Comment by mittinatten** [comment]
OJS 3.1.1-2

**Comment by asmecher** [comment]
@NateWr, would you mind taking a look?

**Comment by NateWr** [comment]
_interesting..._ I'll assign this to 3.2 and consider it a personal priority. But 3.2 is already pretty overloaded so I can't promise it for that version just yet. But I do consider it important for the theme development!

**Comment by bricas** [comment]
This is a bit of a blocker for us -- we would like to have a set of UNB themed child themes.

Is there any chance this will be looked at soon?

**Comment by Vitaliy-1** [comment]
PR: https://github.com/pkp/pkp-lib/pull/4697
@NateWr, can you take a look? I'm not sure if it's the best option for the fix. I'm not providing here the check to all ancestors' templates.

**Comment by NateWr** [comment]
That looks good, Vitaliy. I've added a comment with some code we can use to check for all ancestors' templates.

@asmecher you handled this originally. Can you take a quick look and see if you're happy with the implementation going here?

**Comment by asmecher** [comment]
> @asmecher you handled this originally. Can you take a quick look and see if you're happy with the implementation going here?

Yes, this is making sense to me -- though I like your proposal for recursion support, which it looks like @Vitaliy-1 is working on.

**Comment by Vitaliy-1** [comment]
The previous PR can be closed. I've made a new one: https://github.com/pkp/pkp-lib/pull/4710
@NateWr, make a PR with a submodule update for ojs repo as well?

**Comment by Vitaliy-1** [comment]
Submodule update: https://github.com/pkp/ojs/pull/2373
Hope it's enough :)

**Comment by NateWr** [comment]
Merged, thanks!

**Comment by Vitaliy-1** [comment]
PR for the stable branch: https://github.com/pkp/pkp-lib/pull/5126

**Comment by NateWr** [comment]
Thanks!
