### ISSUE TITLE
[OJS] When uploading his/her revision file, the author cannot choose "revision of an existing file"

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#4058]
Bonjour, 

In OJS documentation (https://docs.pkp.sfu.ca/learning-ojs/en/authoring#responding-to-a-review), It is mentionned that the authors can use the dropdown menu to choose that you are uploading a revision of an existing file.

However, in our implementation and in OJS Testdrive, the upload window does not offer this opportunity. 

See print screen from OJS TestDrive
![upload_revision](https://user-images.githubusercontent.com/19291880/45498089-57e53400-b747-11e8-9a42-1191c7b55e64.PNG)

Can it be corrected?

Thank you very much.
cheers,  
Pierre

**Comment by asmecher** [comment]
Tagging @stranack (and feel free to pass it along to someone else if you're swamped, Kevin!)

**Comment by NateWr** [comment]
Closing this in favor of https://github.com/pkp/pkp-lib/issues/4976.
