### ISSUE TITLE
[OJS] No email sent to author when article goes to external review

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#4059]
Bonjour, 

In OJS, when sending an article to review, no email is sent to the author. However, a template exists in OJS to do so: "Editor Decision Send To External". This email should be sent to Author to notify them that their submission is being sent to an external review.

Can this email be added as part of the workflow?

Repro steps
Make new submission as Author
As editor, open the new submission and clic on Send to Review
Upload a file and clic on Send to review

The article goes to the Evaluation step, but the author does not receive an email.

Thanks.
Pierre

**Comment by pilasou** [comment]
We are on OJS 3.1 
I also test on OJS TestDrive Demo site.

**Comment by t4x0n** [comment]
Oh, I understood now!  really is not a bad idea, but I think this email is not sent because the author can see if the manuscript has reviewers or not

**Comment by forgive38** [comment]
Hello,
I agree, we would give too much information to the authors

**Comment by t4x0n** [comment]
@asmecher or @NateWr  can take desitions about that, we just propose it and wait ;)

**Comment by kshuttle** [comment]
I recommend adding two new email templates in the Review stage to let authors know that their submission is being sent to review, which contain information about what kind of review their submission will undergo (anonymous vs open). These would replace the "External Review" template.

Suggested title for new template for anonymous review: EDITOR_DECISION_SEND_TO_ANONYMOUS_REVIEW

Suggested title for new template for open review: EDITOR_DECISION_SEND_TO_OPEN_REVIEW

**Comment by felixhelix** [comment]
I subscribe to the need for an email to the author that his work is undergoing review.
As of OJS ver. 3.3.0.7. the "EDITOR_DECISION_SEND_TO_EXTERNAL" Email template is still without function.
I do not think that a separate template depending on the revision process is needed, as any journal can edit the content to fit its need.

**Comment by NateWr** [comment]
This is very likely to be included in 3.4, as part of work on #7265.

**Comment by felixhelix** [comment]
Thanks @NateWr,  
#7265 looks great!

**Comment by NateWr** [comment]
This was merged to the `main` branch as part of #7265 and will be included in 3.4.
