### ISSUE TITLE
[OJS] Editorial history does not work

### ISSUE THREAD

**Issue by Taomach** [pkp/pkp-lib#4062]
I am using the latest git version of OJS (currently 125e2fa468), and the editorial history dialog never finishes loading for me on any submission. I don't see any errors in the apache log file, and don't know where to look. How do I investigate and resolve this issue?

**Comment by asmecher** [comment]
@Taomach, next time it's better to post this kind of question on our support forum (http://forum.pkp.sfu.ca/). I suspect your PHP configuration is set to send warnings/errors to the browser rather than the log; I'd suggest changing your PHP configuration so that errors are logged and not displayed.

**Comment by Taomach** [comment]
Hello @asmecher!
I managed to catch the exception that is raised when the editorial history fails to load. Here it is:
```
HP Fatal error:  Uncaught Error: Call to a member function getFullName() on null in /var/www/ojs/lib/pkp/classes/user/PKPUserDAO.inc.php:465
Stack trace:
#0 /var/www/ojs/lib/pkp/classes/log/EmailLogEntry.inc.php(129): PKPUserDAO->getUserFullName('0', true)
#1 /var/www/ojs/lib/pkp/controllers/grid/eventLog/EventLogGridCellProvider.inc.php(96): EmailLogEntry->getSenderFullName()
#2 /var/www/ojs/lib/pkp/classes/controllers/grid/GridCellProvider.inc.php(49): EventLogGridCellProvider->getTemplateVarsFromRowColumn(Object(EventLogGridRow), Object(GridColumn))
#3 /var/www/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1096): GridCellProvider->render(Object(Request), Object(EventLogGridRow), Object(GridColumn))
#4 /var/www/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1003): GridHandler->_renderCellInternally(Object(Request), Object(EventLogGridRow), Object(GridColumn))
#5 /var/www/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(980): GridHandler->renderRowInternally(Object(Request), Object(EventLogGridRo in /var/www/ojs/lib/pkp/classes/user/PKPUserDAO.inc.php on line 465
```
I also made a [post](https://forum.pkp.sfu.ca/t/editorial-history-does-not-work/48959) on the support forum like you suggested. Can you please help me to get to the cause of this problem?

**Comment by asmecher** [comment]
@Taomach, I'll follow up on the support forum post. Please just keep the conversation to one place or the other -- it's more confusing when it's in both places.
