### ISSUE TITLE
SUBMISSION_ACK string is repeated in emailTemplates.xml (Spanish)

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#4064]
I made a PR with some changes, in order to improve the emails templates, thank @marcbria for your lasts changes in all xml Spanish files, there was a very good job! Can you review my Pull Request (https://github.com/pkp/ojs/pull/2119) and say me what do you think?  

Thanks!!

**Comment by carzamora** [comment]
Hi @marcbria,
now the emailTemplates.xml is ordered, and you can see the repeated string here: https://github.com/pkp/ojs/blob/master/locale/es_ES/emailTemplates.xml#L127#L154 now is necessary to decide on what message will be used, or maybe a mix between both, if you prefer I can make the PR with your preference ;)

**Comment by marcbria** [comment]
Thanks @carzamora.
@jordilacruz take a look and let us know, please.

**Comment by NateWr** [comment]
Closing this as outdated.
