### ISSUE TITLE
Issue ordering on the archive page

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4065]
OJS 3.1.1-4 PHP 7.2

If there was no prior ordering (through the dashboard), on the archive page issues appear in a random order. Replicated in the default and other themes. For example: https://e-medjournal.com/index.php/psp/issue/archive

**Comment by ajnyga** [comment]
So they do not follow the issue published date?

**Comment by Vitaliy-1** [comment]
Nope. It seems that the order is fully random on every page load until the user somehow manages ordering from a dashboard. For example, pressing order button and just saving the form resolves the problem.

**Comment by ctgraham** [comment]
See: https://forum.pkp.sfu.ca/t/ojs3-1-2-0-archive-front-page-change-ordering-of-back-issues-to-descending/54704/17

**Comment by TobiasWantzen** [comment]
Thanks ctgraham for pointing to the sources. As far as I understand this:
https://github.com/pkp/ojs/blob/754e833274e7ea89d76faacedb40ef0f60618fbd/classes/services/queryBuilders/IssueQueryBuilder.inc.php#L62-L80
correctly, OJS only allows 2 ways of sorting via `'orderBy'`: `lastModified`, `seq`. All other values are treated as `datePublished`.

So the base configuration `'seq'` in `pages/issues/IssueHandler.inc.php` (https://github.com/pkp/ojs/blob/754e833274e7ea89d76faacedb40ef0f60618fbd/pages/issue/IssueHandler.inc.php#L129-L137) should have a fallback to `datePublished`, when the database table `custom_issue_orders` (`seq`) is empty.

Furthermore I think it’d be best, to give the user the chance to configure the archive’s sorting order via backend options (which doesn’t exist up to now).

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this in the latest stable branch, please provide reproduction steps and we'll re-evaluate.
