### ISSUE TITLE
better Spanish translation  /locale/es_ES/manager.xml

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#4067]
Hi @marcbria,
I found two strings in [/locale/es_ES/manager.xml](https://github.com/pkp/pkp-lib/blob/master/locale/es_ES/manager.xml#L264) that are not correct, here I left the English version:
```
<message key="manager.plugins.installedVersionNewer">Plugin already installed, and is newer than the version available in the gallery.</message>
<message key="manager.plugins.installedVersionOlder">Plugin already installed, but can be updated to a newer version.</message>
```

but, currently in Spanish appear this:
```
<message key="manager.plugins.installedVersionNewer">Este módulo ya existe. Se trata de una versión posterior o igual que la que está instalada</message>
<message key="manager.plugins.installedVersionOlder">Este módulo ya existe. Se trata de una versión anterior o igual que la que está instalada</message>
```

I think is more correct, especially for the second one:
```
<message key="manager.plugins.installedVersionNewer">Este módulo ya existe, y es una versión posterior a la que está disponible en la galería.</message>
<message key="manager.plugins.installedVersionOlder">Este módulo ya existe, pero puede ser actualizado a una nueva versión.</message>
```
El contexto: estos textos solo aparecen cuando el editor llega a la seccion de plugins, pero como no puede instalarlos porque no es Admin le aparecen esos mensajes explicando el estado actual del plugin.

Gracias Marc

**Comment by marcbria** [comment]
You are right @t4x0n thanks.

Let us make a little style change in your first proposal. The coma after the conjunction is also right but we prefer avoiding it. 

From this:
`<message key="manager.plugins.installedVersionNewer">Este módulo ya existe, y es una versión posterior a la que está disponible en la galería.</message>`

To this:
`<message key="manager.plugins.installedVersionNewer">Este módulo ya existe y es una versión posterior a la que está disponible en la galería.</message>`

With this change, the PR is good for us to be merged.

**Comment by t4x0n** [comment]
perfect @marcbria, here is the PR: https://github.com/pkp/pkp-lib/pull/4075

**Comment by mtub** [comment]
thanks @carzamora and @marcbria
