### ISSUE TITLE
Uploading revisions creates an incomplete email_log entry

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4070]
Hi,

When the author uploads a new file the system sends a REVISED_VERSION_NOTIFY message to the editors. https://github.com/pkp/pkp-lib/blob/master/controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php#L362

However, in the email_log details like sender_id, ip_address and event_type are missing. The last two are saved as NULL and the sender_id as `0`.

OJS 3.1.1.2

**Comment by ajnyga** [comment]
Seems that $mail->send(); here https://github.com/pkp/pkp-lib/blob/master/controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php#L362 should be $mail->send($request);

After providing the $request there, the sender_id and ip_address are saved to the log.

**Comment by ajnyga** [comment]
For the event_type, it seems that no event_type is defined for the REVISED_VERSION_ NOTIFY message? https://github.com/pkp/pkp-lib/blob/master/classes/log/PKPSubmissionEmailLogEntry.inc.php#L22

**Comment by asmecher** [comment]
Fixed -- thanks as always, @ajnyga!
