### ISSUE TITLE
Submission metadata form: pressing save button triggers browser errors

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4072]
OJS 3.1.1-4

Tested with latest Chrome and Firefox. Reproduced on several OJS instances that was upgraded from v.3.0 and 3.1.1
Occurs on any stage except when an author submits an article. Nevertheless, the actual data entered in the form are saved. No errors in PHP logs. After pressing the save button form doesn't disappear: 
![metadataform](https://user-images.githubusercontent.com/20665587/45691503-7b521980-bb61-11e8-9850-7b2ec45af076.jpg)

**Comment by Vitaliy-1** [comment]
Related discussion on the forum: https://forum.pkp.sfu.ca/t/various-javascript-errors-in-ojs-3-1-1-2/48489

**Comment by NateWr** [comment]
@Vitaliy-1 can you check the Network tab in the devtools? You should see the request that was sent when saving the form, and the response that was sent back. It seems the JSON is malformed, so there should be some hint in the response.

**Comment by Vitaliy-1** [comment]
All request are successful but save-form request is taking 4 sec. When I'm clicking on it I get: 
`{"status":false,"content":"A workflow stage was not specified.","elementId":"0","events":null}`
Nothing else suspicious

**Comment by Vitaliy-1** [comment]
@NateWr 

Basically, the issue is present and in Health Sciences demo journal.

**Comment by Vitaliy-1** [comment]
Yes. Console error appears after request is successful and this response. Data entered in the form are saved, so the problem appears to be only with form dismissal.

**Comment by Vitaliy-1** [comment]
Actually, errors appear after all XHR are fired, so nothing associated with them in the console. Moreover, sometimes I see only the second one.

**Comment by Vitaliy-1** [comment]
Compared to the OJS 3.1.1-1, where no errors occur, there is missing request URL:
`http://ojs-3.1.1-1.test/index.php/ojs/$$$call$$$/grid/users/author/author-grid/fetch-grid?submissionId=1&stageId=5&_=1538664183467`

**Comment by Vitaliy-1** [comment]
@NateWr All form is affected, including references and identifiers tabs: https://forum.pkp.sfu.ca/t/ojs-3-1-1-4-references-extraction-loop/49103

**Comment by NateWr** [comment]
I've assigned this to the 3.2 milestone and given it a Critical Issue flag since several key forms are effectively broken.

I'm sorry I've let it drag on like this, but I just haven't been able to focus on too many different issues right now. I will look into it once my current workload is merged.

**Comment by ajnyga** [comment]
Also see https://forum.pkp.sfu.ca/t/ojs-3-1-1-2-error-while-editing-metadata/49424

**Comment by asmecher** [comment]
All, I've added a fix to `pkp-lib` (`lib/pkp` in your OJS install) that should resolve this. Please try applying https://github.com/asmecher/pkp-lib/commit/65475ba862e1ed5cad8f03ea34680be86a3dbe7e and confirm whether it works for you. Once I've gotten that through our Travis test environment I'll port it around to the various necessary branches.

Note that this only affects the front-end's parsing of the server response, so you won't have lost any metadata updates in the process.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/4187

**Comment by asmecher** [comment]
Note that if you're using `enable_minified` in `config.inc.php`, you'll also need to update your minified Javascript. You can do that by applying https://github.com/pkp/ojs/commit/322f3aef0ed1a6f4ddbe1d6fcd5266d272a41c92 (`ojs-stable-3_1_1`).

**Comment by Vitaliy-1** [comment]
Yep, it works.

**Comment by asmecher** [comment]
Note that this also affects OMP. For OMP 3.1.1-x prior to -5, patch...
- https://github.com/asmecher/pkp-lib/commit/65475ba862e1ed5cad8f03ea34680be86a3dbe7e
- https://github.com/pkp/omp/commit/f104db093a25a2dff1c91eb157ef36d959da1239
- https://github.com/pkp/omp/commit/b8c18b08af810e0424732844b4fed9c2a45b7a72 (minified JS including the above modifications)

**Comment by ViRuSTriNiTy** [comment]
I have hunted this bug also only to see that is already fixed. Darn. Here are my notes about where the bug originates for reference.

- create & finish submission
- open *review the submission"* page
- open metadata modal dialog
- click save
	- response with a json object containing flag `reloadContainer = true`
	- `AjaxFormHandler.js`, `handleResponse()` is triggered 
	- `TabHandler.js`, `tabsReloadRequested()` is called as a results of binding to the `containerReloadRequested` event
		- get request to reload tab, response is a json string with header `Content-Type: application/json` hence the browser automatically creates an 'Object' instead of a string from the response
		- now the success handler calls `$.parseJSON(data)` which throws an exception and the dialog breaks
