### ISSUE TITLE
[OJS] mergeUsers does not update user_id in all relevant tables in the database

### ISSUE THREAD

**Issue by eirikhanssen** [pkp/pkp-lib#4073]
**Describe the bug**
when merging user accounts, the **user_id** field is not updated in several tables in the database.

- email_log_users
- item_views

**To Reproduce**
1. Go to Settings > Users and Roles
2. Click "Merge User" on a user with entries in the tables listed above.
4. See error in db tables

**What application are you using?**
OJS 3.1.1.2

**Additional information**
This issue description has been updated from the original:

> In ojs 3.1.1.2 when merging user accounts, the **user_id** field is not updated in several tables in the database.
> 
> **Observed concequences**
> I noticed this initially as a section editor lost all the submissions from 'My Queue' after performing a merge into a new user account. Also, when opening a submission from the administration interface, the part of the interface where Participants would be listed would display a loading-icon, and it would be impossible to assign new participants because that part of the interface would never show up.
> 
> **Resolving the issue**
> In this case, after *changing* the **user_id** in **stage_assignments** to the *new* user_id where the user_id was the *old* user_id in the database for the user account in question, the issue was resolved.
> 
> **Tables where user_id is not updated during user account merging**
> Following, I checked if any tables using the user_id field still had the old user_id value, and discovered that the user_id is not updated during a user account merge for the following tables at least:
> 
> - email_log_users
> - group_memberships
> - item_views
> - notification_subscription_settings
> - notifications
> - query_participants
> - roles
> - stage_assignments

**Comment by asmecher** [comment]
@eirikhanssen, a few comments on these...
- The `roles` and `group_memberships` tables are probably left-over data from an OJS 2.x install; they aren't used in 3.x.
- The `stage_assignments` table is coded for transfer in `UserAction::mergeUsers` already. Are you sure it's not being transferred?
- The `notifications` table is now transferred (per recent commits to the `master` branch).

**Comment by NateWr** [comment]
I've updated the original issue description with the remaining tables that need to be investigated. I left out `notification_subscription_settings` because these probably should not be merged. However, the entries should probably be removed when a user is merged.

**Comment by jyhein** [comment]
In my commit merge user accounts now updates email_log_users table too. item_views table was removed after the latest update.

**Comment by asmecher** [comment]
@jyhein, I see a pull request for the OJS repo containing a submodule update (https://github.com/pkp/ojs/pull/3789); could you also open a PR against pkp-lib and drop a link here?

**Comment by jyhein** [comment]
Here: https://github.com/pkp/pkp-lib/pull/8694

**Comment by asmecher** [comment]
Merged -- thanks, @jyhein! And congratulations on fixing your first issue!
