### ISSUE TITLE
Access denied when trying to access some editorial/JM functions

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4074]
In OJS 3.1.1-4 when a JM navigates to Tools > Statistics and clicks on the 'Generate custom report' button an "Access Denied" pop-up is displayed and the report generator does not load.

**Comment by asmecher** [comment]
Also reported here: https://forum.pkp.sfu.ca/t/report-generator-access-denied/48503

**Comment by mfelczak** [comment]
Access also denied to Static Pages plugin tab under Settings > Website

**Comment by mfelczak** [comment]
May be worthwhile to review other plugins that add tabs to the JM Settings pages.

**Comment by asmecher** [comment]
Thanks, @mfelczak! Closing this issue unless other aspects crop up. The custom report generator issue has been resolved already.

**Comment by mfelczak** [comment]
Hey @asmecher, it looks like the customLocale plugin is also affected by this and throws and access denied error, re-opening.

**Comment by asmecher** [comment]
This should fix it: https://github.com/asmecher/customLocale/commit/6cd19694a36b827e0bf8cd91c1dff0b030081455

**Comment by asmecher** [comment]
This has already been resolved in `ojs-stable-3_1_1` in https://github.com/pkp/pkp-lib/issues/4024 -- see https://github.com/pkp/pkp-lib/commit/1e47ca6541c0f274778d58bd3adb2de78992ab2e.
