### ISSUE TITLE
Add link option for home page image

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#4082]
Currently, the Appearance page allows for a home page image upload. It would be helpful to add a URL field, to make the image linkable on the home page (Heidelberg sprinters).

**Comment by NateWr** [comment]
Can someone provide a use-case here?

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
