### ISSUE TITLE
“Select Library Files to attach” should not display if there are no files in the Publisher Library

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#4083]
Through the system, there is a button to “Select Library Files to attach” which allows for attaching files from the Publisher Library. This button should not appear when there are no files in the Publisher Library.
- Heidelberg sprinters

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
