### ISSUE TITLE
Bad template calls in master branch OAI metadataformats

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4084]
marc:
`[Mon Sep 24 08:55:32.973077 2018] [:error] [pid 28281] [client ::1:50989] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'app:/Applications/XAMPP/xamppfiles/htdocs/ojs-sprint/plugins/oaiMetadataFormats/marc/record.tpl' <-- \n  thrown in /Applications/XAMPP/xamppfiles/htdocs/ojs-sprint/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195`

marcxml:
`[Mon Sep 24 08:55:41.480171 2018] [:error] [pid 14659] [client ::1:50993] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'app:/Applications/XAMPP/xamppfiles/htdocs/ojs-sprint/plugins/oaiMetadataFormats/marcxml/record.tpl' <-- \n  thrown in /Applications/XAMPP/xamppfiles/htdocs/ojs-sprint/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195`

**Comment by asmecher** [comment]
Fixed; thanks for reporting, @ajnyga! (Does not affect any released code.)
