### ISSUE TITLE
[OJS] Plugins directory access

### ISSUE THREAD

**Issue by odolany** [pkp/pkp-lib#4085]
entering the plugin folder directly returns an error
https://demo.publicknowledgeproject.org/ojs3/demo/plugins/oaiMetadataFormats/dc/index.php

At worse server configurations it shows: Call to undefined function import() in /var/www/
maybe "index.html" files should be in all subfolders in standard release to avoid such problems?

**Comment by asmecher** [comment]
@odolany, the potential display of server configuration is the reason that it's recommended not to enable the `display_errors` setting in a production PHP environment: http://php.net/manual/en/errorfunc.configuration.php#ini.display-errors

Adding `index.html` files would not prevent this, as you could still enter `index.php` manually to get the error message.
