### ISSUE TITLE
Sorting catalog by title in OMP 3 multi-language installations

### ISSUE THREAD

**Issue by CFanselow** [pkp/pkp-lib#4086]
Ordering by title does not work for multi-language installations in OMP 3.1.1. See
https://forum.pkp.sfu.ca/t/sorting-catalog-by-title-in-multi-language-omp-3-1-1-installations/48423

**Comment by asmecher** [comment]
@CFanselow, I've added a PR for this that could use some testing: https://github.com/pkp/omp/pull/596
Can you clarify where in the system you are that's behaving badly?

**Comment by CFanselow** [comment]
@asmecher 

I get a sorting problem in both OMP 3.1.0 and 3.1.1.

In 3.1.1,  I am not quite sure what causes the problem. In 3.1.0 I _suppose_ that for all languages the main language is used for sorting. So for the main language the sorting is okay, for the others it isn't, depending on the translations. 

There are major differences in the CatalogHandler between these two versions (I did not notice these differences before, so sorry about the version confusion).

In 3.1.0 it is $publishedMonographs = $publishedMonographDao->getByPressId($press->getId());

In 3.1.1 it is $publishedMonographs = $submissionService->getSubmissions($context->getId(), $params);

PublishedMonographDOA->_getByAssoc only seems to be used in 3.1.0. But still the changes you made do not fix the problem in my 3.1.0 installation, instead $publishedMonographs = $publishedMonographDao->getByPressId($press->getId()) returns no monographs at all.

**Comment by asmecher** [comment]
@carola, do you have plans to upgrade to 3.1.1? I'd much rather fix issues there than in 3.1.0 -- if it's on your roadmap anyway, then there's no downside. And I could clean out old/unused code at the same time.

**Comment by CFanselow** [comment]
@asmecher 

I'll try upgrading!

**Comment by NateWr** [comment]
Closing this as outdated. If you need help with a similar problem, please post in our [community support forum](https://forum.pkp.sfu.ca/c/questions/5).
