### ISSUE TITLE
Make revision files available for selection at Copyediting stage

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4087]
**Describe the bug**
When trying to add a file to the Draft files area, I can not select Revision files. I would expect all files to be shown when the user clicks "Show files from all accessible workflow stage", but files cannot be moved from the Review stage to the Copyediting stage after the Review stage has been completed.

**To Reproduce**
1. Log in as the author of a submission that is in the Copyediting stage.
2. Go to the Review stage
3. Upload a file under Revisions
4. Log out as the author and log in as an editor or journal manager
5. Go to the Copyediting stage
6. Click Upload/Select Files under Draft Files
7. Click Show files from all accessible workflow stages in the popup
8. Notice that the file you just uploaded as an author does not appear

**What application are you using?**
3.3.0-x

**Additional information**
This report has been modified. The original report is below:

> A user reported that after a submission had been sent to copyediting, the author accidentally uploaded production-ready files to the Review stage, in the Revisions panel.  The editor tried to move them to the copyediting stage, but the files would not appear, even after checking off “Show files from all accessible workflow stages” in the Upload/Select Files dialogue.  It seems like the revision files should be available, in the case of user error or if an additional file needs to be retrieved that was not sent on when the editor recorded a decision and sent the submission to copyediting.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.

**Comment by amandastevens** [comment]
I see this as more of a bug than a feature request, as all files are not being shown when the user clicks "Show files from all accessible workflow stage" and files cannot be moved from the Review stage to the Copyediting stage after the Review stage has been completed.  

I just tested this in OJS 3.3 (on the testdrive site) and it hasn't changed. To reproduce:

1. Log in as the author of a submission that is in the Copyediting stage.
2. Go to the Review stage
3. Upload a file under Revisions
4. Log out as the author and log in as an editor or journal manager
5. Go to the Copyediting stage
6. Click Upload/Select Files under Draft Files
7. Click Show files from all accessible workflow stages in the popup
8. Notice that the file you just uploaded as an author does not appear

**Comment by asmecher** [comment]
@NateWr, maybe you were thinking of https://github.com/pkp/pkp-lib/issues/7705? That was just for default checkbox states, not what files are listed.

**Comment by NateWr** [comment]
Ah right. I've re-opened this. @amandastevens in your last comment, you said:

> files cannot be moved from the Review stage to the Copyediting stage **after the Review stage has been completed**. 

Is this important? Does the submission need to be moved from review to copyediting (for example with an accept decision) before you encounter this error?

**Comment by amandastevens** [comment]
Thanks for reopening, Nate.  I just tested whether this is also the case when the submission is still in the Review stage and hasn't been moved to the Copyediting stage with an editorial decision, and yes, the files uploaded as Revisions are still not available to upload under Draft Files in the Copyediting stage.  I don't know if there are many cases where a journal would start copyediting a submission before the review is completed, but maybe it happens sometimes.  

When an Editor records an editorial decision and moves the submission to the Copyediting stage, they do see files uploaded as Revisions that they can send on to the Copyediting stage.  But if they forget to send on a file at this point and need to send it later or an author uploads a revisions file after the review has been completed that the Editor wants to move to the Copyediting stage, that is when the file is not available.  Those are some use cases I can think of.  I hope that's helpful.

**Comment by NateWr** [comment]
The following PRs make revision files available when selecting files to promote to another stage. However, the UI does not distinguish between Files for Review and Revisions, so the editor won't know which file is before revision and which is after revision.

The example below illustrates the problem. Files with identical names exist in Files for Review and Revisions, so the editor will need to rely on the ids to know which one to send to copyediting.

![Screenshot 2023-01-18 at 10-43-18 admin test section editor priviliges Journal of Public Knowledge](https://user-images.githubusercontent.com/2306629/213151502-bf796a8d-7135-4ee9-b45e-8a2e8041b56b.png)

Although a problem, it's better than before where the files simply weren't available. @Devika008 I'm flagging this for you to note as a problem to resolve when we redesign the submission file panels in the workflow.

PR:
https://github.com/pkp/pkp-lib/pull/8549

Tests:
https://github.com/pkp/ojs/pull/3709

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and `main`.
