### ISSUE TITLE
View report does not remove linebreaks from titles

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4089]
This makes it hard to open the report for example in Excel, because the data of some articles is in two, or more, rows.

All linebreaks should be removed from the title when added to the view report. Fix in a sec.

OJS 3.1.1.2

**Comment by asmecher** [comment]
Merged, thanks, @ajnyga! I don't generally see line breaks in titles but this is a harmless change otherwise.

**Comment by ajnyga** [comment]
Great thanks, I think these usually come from XML imported articles. Probably something that could/should be fixed in the import process.
