### ISSUE TITLE
QuickSubmit Plugin latest version

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4090]
Hi @asmecher , when installing a fresh OJS and attempt to enable QuickSubmit Plugin from plugin gallery, it is not installing latest version of this plugin.
It keeps showing "Can be upgrade" message and clicking on this link, it reloads page but message remains and version `1.0.1.0` as well (latest version is  `1.0.2`).

**Comment by asmecher** [comment]
@israelcefrin, can you try upgrading it on the journal in question? I've bumped the version to 1.0.3. It's possible that we made changes without bumping the version number earlier, so hopefully this will resolve it.

**Comment by israelcefrin** [comment]
@asmecher it has worked, thanks!
I will deploy a fresh install to double check that it works as well.
