### ISSUE TITLE
[OJS] Problems with upgrade to 3.1.1 - css lose

### ISSUE THREAD

**Issue by danielflamia** [pkp/pkp-lib#4091]
When I upgrade the OJS current version 2.4.8 to 3.1.1, cli script launch warnings about "Can not use scalar value as an array in" in / var / www / html / lib / pkp / classes / core / DataObject. inc.php, and "Invalid argument supplied for foreach ()" in /var/www/html/classes/install/Upgrade.inc.php. "ERROR: Upgrade failed: DB: Duplicate entry '9402-3-1' for key 'review_rounds_submission_id_stage_id_round_pkey'". And when I try to access the web address to see how problems arrived, all CSS from page is broked.

I did all the things listed on "https://pkp.sfu.ca/ojs/README" but the errors continued.

Have another mode to export and import datas from 2.4.8 to 3.1.1 version?

**Comment by asmecher** [comment]
@danielflamia, I suspect this is the same problem already described here, with some SQL queries to run before upgrading to resolve it: https://github.com/pkp/pkp-lib/issues/1921#issuecomment-265585370
