### ISSUE TITLE
MassMail fails if using mail:send callback

### ISSUE THREAD

**Issue by terrasea2** [pkp/pkp-lib#4094]
If you use a plugin that uses the 'mail::send' hook which returns true to prevent the use of PKPs mailer, MassMail will only send one email in the batch.

```$success = $success && MailTemplate::send(false);```

Where `$success` will return NULL for the first pass because of the code in `Mail::send`

```if (HookRegistry::call('Mail::send', array($this))) return;```

The use of `$success && MailTemplate::send(false);` means `MailTemplate::send(false);` will never be reached, because NULL evaluates to `false` after the first pass.

Return true would be the obvious solution to this. 

```if (HookRegistry::call('Mail::send', array($this))) return true;```

**Comment by asmecher** [comment]
Hi @terrasea2 -- would you mind opening a PR with your proposed solution? Thanks!

**Comment by terrasea2** [comment]
Sure, simple change

https://github.com/pkp/pkp-lib/pull/4095

**Comment by asmecher** [comment]
Thanks, @terrasea2 -- merged! (I'll also cherry-pick it back to `ojs-stable-3_1_1` and `omp-stable-3_1_1` in case we release another build of that version before OJS 3.2 comes out.)

**Comment by terrasea2** [comment]
Not a problem for just a simple 1 line change
