### ISSUE TITLE
Assigned to the template variables don't work on the registration complete page

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4096]
After assigning a journal-specific variable to the templates, like:
```
if ($request->getContext()) {
  $templateMgr->assign('variable', $journal->getLocalizedSetting('variable'));
}
```

it doesn't work on the journal's registration page if registration is complete. The one that is journal specific, not site-wide.

**Comment by Vitaliy-1** [comment]
Ahh, it seems that variables assigned from the theme don't work on that page.

**Comment by Vitaliy-1** [comment]
The problem is still relevant for OJS 3.1.2-1. This page is out of scope for any variable/function assign to Smarty from plugins. Probably it happens because it bypasses `TemplateManager::display` hook. 

E.g., when introducing new Smarty function and assigning it site-wide, like active menu items that I'm using for Pragma, it leads to a fatal error after registration when a user is redirected to view `registrationComplete.tpl`:
```
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "app:app:frontendcomponentsnavigat"  on line 29 "<li class="{$navigationMenuItemAssignment->navigationMenuItem->getType()|lower} main-menu__nav-item{if $hasSubmenu} dropdown{/if} {pragma_item_active item=$navigationMenuItemAssignment->navigationMenuItem}">" unknown tag 'pragma_item_active' <-- 
  thrown in /var/www/ojs-3.1.2-1/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 29
``` 
The workaround that I've found for now is attaching a custom header for that template without this function.
@NateWr, can we do anything here?

**Comment by NateWr** [comment]
What happens if you change `fetch` to `display` here? https://github.com/pkp/pkp-lib/blob/master/pages/user/RegistrationHandler.inc.php#L46

**Comment by Vitaliy-1** [comment]
Yep, it works fine in this case.

**Comment by NateWr** [comment]
PR to `master` and `stable-3_1_2` please. :joy:

**Comment by Vitaliy-1** [comment]
PR for master: https://github.com/pkp/pkp-lib/pull/4977

How you usually make a commit to the other branch as well?

I need to: 
```
git checkout --track upstream/stable-3_1_2
git checkout -b stable_3_1_2_i4096_registration_complete stable-3_1_2
make changes
git add, commit and push to origin stable_3_1_2_i4096_registration_complete
```
and then make a PR to stable branch?

**Comment by Vitaliy-1** [comment]
I don't have stable-3_1_2 locally.

**Comment by NateWr** [comment]
:+1: merged and cherry-picked to stable. Thanks.
