### ISSUE TITLE
[OJS] Fix for #3705 breaks archives with PostgreSQL

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#4097]
The changes introduced to fix #3705 cause an error when PostgreSQL is the backing store: `DB Error: ERROR: column "o.seq" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...published" = $2 group by "i"."issue_id" order by "o"."seq" ... ^`

**Comment by cpockett** [comment]
We're in the process of setting up a production instance of ojs 3 and also ran into this issue. Is there a time frame or fix that could be applied?

**Comment by asmecher** [comment]
@cpockett, it hasn't been merged yet, but the fix https://github.com/pkp/ojs/pull/2123 is simple enough. I'd suggest patching with that.

**Comment by cpockett** [comment]
Thanks @asmecher this fixes the issue for me. As a side note we're running postgres, just to clarify.

**Comment by asmecher** [comment]
Yes, I believe the issue should only affect PostgreSQL installs. Thanks for the confirmation on the fix.

**Comment by asmecher** [comment]
With apologies, this fell out of my inbox. Thanks, @crism (and others), I've merged to `master` and ported to `stable-3_1_2` for the OJS 3.1.2-1 release.
