### ISSUE TITLE
Remove ArticleFileManager; clean up related classes

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#410]
As a precondition for issue #405, clean up ArticleFileManager etc., and move as much as possible into the shared library.

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/pkp-lib/pull/414/files
https://github.com/pkp/omp/pull/110/files
https://github.com/pkp/ojs/pull/451/files

Jason, mind reviewing?

**Comment by jnugent** [comment]
Looks great, Alec, especially with how much code this removes from the OJS library.  merge away.

**Comment by asmecher** [comment]
Thanks, Jason!
