### ISSUE TITLE
Show more submissions per page in the editorial submission lists

### ISSUE THREAD

**Issue by retostauffer** [pkp/pkp-lib#4100]
> Result of the UI/UX group from the Heidelberg Sprint 2018 (@stranack @NateWr).

Especially for large-volume journals the number of items in the queue on the dashboard is not suitable and old submissions can quickly "fall off page". We came up with two possible solutions:

- Let the user specify (user profile/buttons) the number of items to be displayed per page (pagination).
- Continuous scrolling. Would work here as there are no other items/elements below the queue.

**Comment by asmecher** [comment]
(@stranack and @NateWr!)

**Comment by NateWr** [comment]
Was there any discussion about how many would be a suitable default for large-volume journals?

**Comment by retostauffer** [comment]
Uh. Something inside my brain screams "50 or 100" but to be honest I am not sure. We have not discussed this in detail (the number).

**Comment by openacademia** [comment]
Hi @NateWr ! We currently have around 130 manuscript in review on Food & Nutrition Research. https://foodandnutritionresearch.net/index.php/fnr/index (currently being upgraded, so no submissions are showing at the moment!). Ideally, it would be good to be able to set the number of items per page, similar to what you can do on the Email Template page, see screenshot:
[screenshot.docx](https://github.com/pkp/pkp-lib/files/2433520/screenshot.docx)

**Comment by openacademia** [comment]
Hi Nate,

Our journals are hosted by PKP and we rely on them for all things too technical ;) The site is currently not functioning as normal (the submission lists are completely empty due to some residual issues from an upgrade), but as soon as it is up and running you or anyone of the PKP guys are welcome to do those modifications.

**Comment by NateWr** [comment]
:+1: Perfect!

**Comment by asmecher** [comment]
This is implicitly implemented by the new submission lists for 3.5.
