### ISSUE TITLE
[Sprint/UIUX] Add Contributor: Make Affiliation a Required Field

### ISSUE THREAD

**Issue by retostauffer** [pkp/pkp-lib#4104]
> Result of the UI/UX group from the Heidelberg Sprint 2018 (@stranack @NateWr).

For the sake of consistency: on the _registration_ form the _Affiliation_ is a required field, when _adding a contributor_ (during submission) this field is optional. Our suggestion is to make both _required_.

**Comment by ajnyga** [comment]
All users know their own preferred affiliation for sure, but they might not know the preferred affiliation of a co-author when they do a new submission.

**Comment by NateWr** [comment]
Yeah, this is an unfortunate one where I think we'll always have disagreement on the best default. In the future, I hope it will be easier to make a field required/optional with a small plugin.

**Comment by Ph-We** [comment]
Hi! I think the possible workaround would be to make the Affiliation always default at least for the primary contact during submission, which would mostly be the one who enters the metadata.

**Comment by asmecher** [comment]
> Hi! I think the possible workaround would be to make the Affiliation always default at least for the primary contact during submission, which would mostly be the one who enters the metadata.

Do you mean that the automatically-created first author should take the affiliation from the submitting user's account? That's already the case, I think.

**Comment by Ph-We** [comment]
> > Hi! I think the possible workaround would be to make the Affiliation always default at least for the primary contact during submission, which would mostly be the one who enters the metadata.
> 
> Do you mean that the automatically-created first author should take the affiliation from the submitting user's account? That's already the case, I think.

I rather mean that if the registered author tries to submit an article AND does not have the 'Affiliation' field filled, s/he should be redirected to the 'Edit User' window with the 'Affiliation' field marked as required.

**Comment by asmecher** [comment]
Hmm, I think that starts to get into territory where we'll satisfy 10% of the user community but annoy a different 10%. @NateWr did some work on custom pre-submission checks implemented as plugins, and I suspect field requirements might need some of the same work. (Setup-controlled user/author field requirements might warrant a setup form of their own, but in general, I worry that this will lead to an explosion of options.)

**Comment by NateWr** [comment]
Yeah, once the author form is converted to the new schema system, making a single field required can be done in 10 lines of plugin code.

I'd like to see these kinds of issues eventually addressed as small one-off plugins that can be used by the 10% who want them without getting in the way for the other 90%.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.

**Comment by diegoabadan** [comment]
In the next few days Lepidus will send a plugin with this functionality to the PKP gallery!

**Comment by LaisLepidus** [comment]
We made a [Pull Request](https://github.com/pkp/plugin-gallery/pull/163) for the gallery!
