### ISSUE TITLE
[Sprint/UIUX] Only allow to send a submission to new review round after decision

### ISSUE THREAD

**Issue by retostauffer** [pkp/pkp-lib#4105]
> Result of the UI/UX group from the Heidelberg Sprint 2018 (@stranack @NateWr).

At the moment it is possible to initiate a _New Review Round_ for submissions which are currently _in Review_ before a decision has been made (even before even reviewers have been added). This is confusing and led to several problems.

**Suggestion:** disable the _New Review Round_ tab/button as long as no decision has been made _or_ at least show a warning "Are you sure to send this submission to a new review round.".

**Comment by retostauffer** [comment]
Yes, did not find this one. The topic in the forum is a nice discussion, I personally like the suggestion by @asmecher , https://forum.pkp.sfu.ca/t/new-review-round-while-previous-review-round-has-not-been-finished-yet/37686/9

Thus, this issue can be seen as duplicated (feel free to close it). Thx for the hint!

**Comment by asmecher** [comment]
Thanks, @retostauffer!
