### ISSUE TITLE
[Sprint/UIUX] Author Notifications Should be Limited to Stage Assignment

### ISSUE THREAD

**Issue by retostauffer** [pkp/pkp-lib#4106]
> Result of the UI/UX group from the Heidelberg Sprint 2018 (@stranack @NateWr).

Authors should **only be informed** about the **current stage** of their submissions (detailed view of their submissions). Currently a lot of information is shared with the authors such as:
- _Waiting for reviewers to be assigned._
- _All reviews are in and a decision is needed._
- _New reviews have been submitted and are being considered by the editor._
- ...

**Personal comment:** I don't think it should be removed, I like the transparency :).

**Comment by ajnyga** [comment]
+1 for transparency. It will cut down the number of emailed questions concerning the status of the submission and does not endanger the review itself.

**Comment by NateWr** [comment]
Yeah, I am also strongly in favor of giving authors _more_ information about their submission status. Do you remember any of the details of the discussion around this? 

I'd like to know more. In some not too distant future, I can imagine giving the author a _lot_ more information (who's the editor assigned, how long does it take on average for a review round to be completed, have the reviewers been given a deadline and what is it, etc.)

**Comment by retostauffer** [comment]
Well, the thing was that they didn't want to show the author that reviews are overdue or that all reviews are here but nothing happened since few days as this might not look good for the publisher? I personally publish(ed) in journals with a very open process. And since 3 weeks a review is overdue, but at leas I know what's going on :).

One idea might be to allow the JM to set one flag in the journal settings "_Open submission process: provide detailed information to authors_" or "_"Closed" submission process: only provide minimal information to authors_". I personally think that the only good way is the open submission process!

**Comment by NateWr** [comment]
Closing this as it needs consensus. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
