### ISSUE TITLE
[Sprint/UIUX] Rephrase "This is not a revision of an existing file"

### ISSUE THREAD

**Issue by retostauffer** [pkp/pkp-lib#4107]
> Result of the UI/UX group from the Heidelberg Sprint 2018 (@stranack @NateWr).

The text "_This is not a revision of an existing file_" turned out to be slightly misleading. **Suggestion:** Rename it to "_New file, this file does not replace a previously upload file._" or something similar.

![screenshot from 2018-09-27 21-11-16](https://user-images.githubusercontent.com/13628564/46168864-e6a29680-c299-11e8-93b6-6d5ce0083833.png)

**Comment by ajnyga** [comment]
Like the "New file" part, but "replace" is maybe the wrong word while the old version is still in the system after you upload a new revision.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
