### ISSUE TITLE
Small additions to Add new reviewer and Enroll an existing user forms

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4110]
Hi,

1. When you open Add new reviewer and Enroll an existing user forms, they show the bottom of the form first. They should open so that the upper half of the form is visible and editors do not have to scroll to the top.

2. the buttons to these two functions could be on the top of the Add reviewer modal? Now when a journal has a long list of reviewers the two buttons are always hidden first. 

3. Or maybe when you do a local search for reviewers, instead of having a message "no results", the message could give hints on how to proceed: "No results. Try adding a new reviewer, click here". And if you try to add a new reviewer but the email collides with an existing one, the system could again give a hint: "Try enrolling the existing user, click here".

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
