### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by raulakh** [pkp/pkp-lib#4111]
We are currently running Open Journal Systems 3.0.2.0 and shibboleth authentication in place in our environment and I am just wondering if we upgrade it to the newest version of OJS, will it work with Shibboleth plugin?
Please advise

**Comment by asmecher** [comment]
@raulakh, rather than creating git issues (which are intended for bug postings), please post your question in the PKP support forum (http://forum.pkp.sfu.ca/).

**Comment by raulakh** [comment]
ok thanks
