### ISSUE TITLE
Problems with upgrade from 2.4.8 to 3.1.1

### ISSUE THREAD

**Issue by danielflamia** [pkp/pkp-lib#4113]
I have tried countless times to upgrade from version 2.4.8 to 3.1.1, but I did not succeed.

I am using the OS requirements in the following versions:
- SO - CentOS Linux release 7.5.1804
- PHP - 5.6.37
- Apache
- MySQL - 5.6.41

The procedures performed are:
1.1 Download the most current version of OJS
1.2 Move the package to the Apache directory
1.3 Copy the data from the file upload directory and from the public /
1.4 Set OJS to "Installed = Off"
1.5 Comparison of config.inc.php files and configuration replication, to use the same database and other configurations
1.6 Running the upgrade script "php tools / upgrade.php upgrade"
1.7 Set OJS to "Installed = On"

During execution of step 1.6, PHP Warnings are thrown for "Can not use scalar value as an array" and "Invalid argument supplied for foreach ()", and ERRORs for "ERROR: Upgrade failed: DB: Duplicate entry '9402-3-1' for key 'review_rounds_submission_id_stage_id_round_pkey' ". At Issue 4091, I reported this issue and performed the reported procedures, but I was unsuccessful.

Is there any procedure that I am not performing to perform the upgrade or installation of OJS? I searched several times for solutions to the problems that I encountered in the course of the proceedings, but in no way succeeded. I also noticed that the release I'm using should not report the ERRORs mentioned above.

Is there any documentation that can help me more systematically with the upgrade and installation procedures?

Are there other ways to migrate data from version 2.4.8 to 3.1.1, other than through upgrade scripts?

Is it possible to perform a backup / export of data from version 2.4.8 and later import in version 3.1.1?

**Comment by asmecher** [comment]
@danielflamia, did you try the queries I referred you to on https://github.com/pkp/pkp-lib/issues/4091?

Rather than opening a new issue, please follow up on the existing one, or open a topic on the support forum (http://forum.pkp.sfu.ca/).
