### ISSUE TITLE
[OJS] GatewayHandler setupTemplate() missing parameter

### ISSUE THREAD

**Issue by cpockett** [pkp/pkp-lib#4116]
Never submitted an issue before so apologies in advance.

In OJS 3.1.1.4 I get the following error when navigating to the '/management/settings/website' > 'Archiving' tab > 'Alternate Archiving Options' > 'Publisher Manifest'.
> Missing argument 1 for PKPHandler::setupTemplate(), called in /var/www/html/ojs/pages/gateway/GatewayHandler.inc.php on line 26 and defined in /var/www/html/ojs/lib/pkp/classes/handler/PKPHandler.inc.php

I've found this can be fixed by updating 'pages/gateway/GatewayHandler.inc.php' and adding the request to the function call. There is a second call in the file for clockss which also needs to be fixed.
`$this->setupTemplate();` to `$this->setupTemplate($request);`

**Comment by asmecher** [comment]
Thanks, @cpockett! I've committed that change to the OJS master branch, and also `ojs-stable-3_1_1`, OMP master, and `omp-stable-3_1_1`. This'll be included in the next release.
