### ISSUE TITLE
Possibility to set up the cover thumbnail size and position the thumbnails in the catalog

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#412]
Remove the white background for thumbnails in order to be able to position them (left, middle, right) in the catalog.
Implement the possibility to set up the max with and height of the cover thumbnails and also the possibility to resize the existing cover thumbnails.

**Comment by asmecher** [comment]
Bozana, have you created a pull request for the pkp-lib changes?

**Comment by asmecher** [comment]
Oops! Yes, both are here:
https://github.com/pkp/omp/pull/109
https://github.com/pkp/pkp-lib/pull/413

**Comment by asmecher** [comment]
Merged, thanks!
