### ISSUE TITLE
CSRF token missing for enable plugin action

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4120]
The CSRF token is missing in the request that's sent to enable a plugin.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/4121 (master)
https://github.com/pkp/pkp-lib/pull/4122 (OJS stable)
https://github.com/pkp/pkp-lib/pull/4123 (OMP stable)

Tests:
https://github.com/pkp/ojs/pull/2126 (OJS master)
https://github.com/pkp/ojs/pull/2127 (OJS stable)
https://github.com/pkp/omp/pull/597 (OMP stable)

**Comment by asmecher** [comment]
Looks good, @NateWr -- please go ahead with all of them. (This is one area where I wish PHP had more concise array operations.)

**Comment by NateWr** [comment]
PRs merged. Tests closed. :+1:
