### ISSUE TITLE
Subscriptions list is slow to load and does not apply row limit 

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4125]
In OJS 3.1.1-4, as reported in the forum:
https://forum.pkp.sfu.ca/t/ojs-3-1-1-4-subscriptions-tabs-loading-extremely-slowly/48862

**Comment by asmecher** [comment]
@mfelczak, @NateWr had a suggestion on Slack:
> Just a quick thought: what is their setting under Settings > Website > Appearance > Items per page? Presumably you've checked this and that's why you've said it "does not apply row limit". But just to double-check that.

Did you have a chance to check?

**Comment by mfelczak** [comment]
Yes, confirming that those settings have been set.

**Comment by NateWr** [comment]
On the forum, someone mentions that the User grid (and all grids) are effected. Can you check and confirmm whether the Settings > Website > Appearance > Items setting is respected by any other grids? 

I took a quick look at the subscriptions grid and didn't see any special code for the range info, so it might be an issue further up the chain.

**Comment by mfelczak** [comment]
Hi @NateWr, confirming that other grids, e.g. Users grid, are working as expected and that the issue is limited to the subscriptions grid for this journal.

**Comment by asmecher** [comment]
I'll investigate this and report back here.

**Comment by asmecher** [comment]
The patches for this are https://github.com/pkp/ojs/commit/9d9008c3fc47896a1df10b3371ba90aa98fa3108 (ojs-stable-3_1_1) and https://github.com/pkp/ojs/commit/43cb7e83f1c315a1c375860bca97826f5dc6a7b7 (master).

**Comment by mfelczak** [comment]
Thanks @asmecher!

**Comment by asmecher** [comment]
@NateWr:
> I took a quick look at the subscriptions grid and didn't see any special code for the range info, so it might be an issue further up the chain.

It turned out to be a specific problem with the subscriptions grids; if someone is seeing that behavior site-wide, then I suspect they haven't configured their items-per-page setting or similar.

**Comment by ajnyga** [comment]
is this the same issue https://github.com/pkp/pkp-lib/issues/3484
