### ISSUE TITLE
[OJS 3] Clarify reviewer state in ReviewerGrid

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#4126]
In our OJS 3.1.1.2 we had a misunderstanding the reviewers grid. The submission will be reviewed _open_. The grid contains two requests for review. One is in the state _Request Accepted_, the other in the state _Declined_.

The author of the submission asked if the submission itself was declined because of the state _Declined_, not knowing that only the request for review was declined. I think the misunderstanding could be avoided when it was clear _what_ was declined.

Right now the _Declined_ comes from [__('common.declined')](https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/reviewer/ReviewerGridCellProvider.inc.php#L166). I would suggest to create a new message _submission.review.status.declinedShort_ "Review declined". Maybe it would be also nice to have _submission.review.status.declined_ "The reviewer declined this review request." as a tooltip there.

So we would end up with:

`return '<span class="state declined" title="__('submission.review.status.declined')">'.__('submission.review.status.declinedShort').'</span>';`

What do you think?

**Comment by ajnyga** [comment]
Hi,

Actually the author should only see reviewers that have accepted the request. Does that make sense to you? So the authors only see open reviewers that have accepted the request.

This is how it was supposed to work, but I can see now that one sql needs a small addition.

**Comment by ajnyga** [comment]
Basically this:
https://github.com/pkp/pkp-lib/blob/master/classes/submission/reviewAssignment/ReviewAssignmentDAO.inc.php#L52

Should be:
			`' WHERE r.review_round_id = ? AND r.review_method = ? AND r.date_confirmed IS NOT NULL AND r.declined <> 1 ORDER BY review_id';`

Could you test that?

**Comment by ajnyga** [comment]
I made a pr about this: https://github.com/pkp/pkp-lib/pull/4128

But your original could be discussed as well I think. I mean making the declined label more clear for editors.

**Comment by asmecher** [comment]
@MarHerUMR, I've merged @ajnyga's PR (and cherry-picked it around) and Github has helpfully closed this issue as a result :)

However, I don't want to lose your suggestion. Could you file it as a new issue (and if possible open a PR)?

Thanks to you both!
