### ISSUE TITLE
Develop tools to review and notify of metadata quality issues

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#4129]
Develop a tool or set of tools that would review submission metadata and notify the journal's primary contact of potential quality or consistency issues. This is a two-part issue: 

1) identify some general metadata consistency and quality issues in OJS datasets. We've already identified a few problem areas, which I'll include in a follow-up post. 
2) develop heuristics to programmatically identify these kinds of issues in individual OJS installs, to be implemented in a quality assurance plugin by PKP developers. 
2b) develop a guidebook for publishers on improving metadata quality: best practices, common mistakes, etc. 

For now we can track stuff in this single issue, but we may want to split things up into a larger Project at a later date.

**Comment by jmacgreg** [comment]
Some known problem areas: 

- the date issue (eg. where an issue or article publication date doesn't match the volume's "year" field; or when the issue and article publication dates are off by more than one year). 
- a lack of license information
- there are issues with things entered in the wrong language (because of how poorly the UI handled multilingual in OJS 2)
- DOIs are with the % placeholders in place, as well as DOIs that have not been deposited
- empty fields (not errors, but missing data)

**Comment by ajnyga** [comment]
Titles and names in CAPITAL LETTERS.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
