### ISSUE TITLE
Enhance indexing and develop tools to truncate large metrics tables

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4130]
With large multi journal installation the metrics table tends to become very large especially if geolocations are used. When the table becomes larger than ca. 500 megabytes fetching data from the table becomes slow for example with queries using dates to limit the result.

This could be solved with two solutions

1. **Enhance metrics table indexing**

We should carefully consider the different ways of querying the table and test with EXPLAIN that an index is used for the kind of query needed. If not, a new index should be added to the table. At the same time we need to make sure that adding new rows to the table is still fast enough. (https://dev.mysql.com/doc/refman/8.0/en/using-explain.html)

@ctgraham suggest that all columns should be indexed. Could be worth testing what the performance difference is for adding rows and how it affects the table size.

2. **Create a tool for truncating older metrics data**

Overall view seems to be that daily data is not needed in older metrics, expressed for example by @jmacgreg and I have a similar view as well. Usually monthly data is enough.  However, if the indexing provides a solution for faster metrics table, truncating the metrics data should be regarded as a secondary option.

We could have a tool that truncated the daily data into "monthly rollups" for a given time period. This means losing also the geographical data, but will make the data considerably smaller.

The tool could be:
- something admins can run from the command line if needed OR
- automatically triggered as a task if enabled in config.inc.php  OR
- both

However, we need to consider the following:
- Fetching statistics has to work also if only month is available. Consider the current statistics plugins and the new API. @NateWr saw two approaches here: a) adjust sql's b) build an assumption to the API calls that for example only the last 12 months has daily data. 
- COUNTER compliance and the SUSHI protocol need to be taken into account. COUNTER requires 24 months of monthly data, but SUSHI is rapidly moving towards more granular data with lightweight but highly detailed RESTful requests.

The key question is (as visible above): a) do we define a certain time period that can be used for truncating the data (setting you can switch on and you end up having 1 years worth of daily data) or b) do we allow users to decide what they want to truncate and design the system that it works with both kinds of data (daily and monthly).

Other remarks:
- Note that the metrics table already includes truncated data from the old metrics types. How are these considered when for example the total download counts are shown?

---

**Other solutions include:**
- An own metrics table for each context (problems with site wide metrics queries?)
- Two metrics tables: `metrics` contains the same data as now `metrics_monthly` only contains the truncated data. Depending on the request we can use either of these.

(feel free to edit this original message, you probably can?)

**Comment by asmecher** [comment]
Tagging @ctgraham and @bozana!

**Comment by isgrim** [comment]
I just checked our biggest OJS instance, which is still on version 2.4.8 and the metrics table is also around 800 MB.
Let me know if I can help test something. We want to upgrade this instance beginning of next year, probably to OJS 3.2 then.

**Comment by marcbria** [comment]
following... :-)

**Comment by ctgraham** [comment]
One oversight in 2.4.8 at least is the missing combination of `assoc_id`, `assoc_type` index:
```
mysql> show indexes from metrics;
+---------+------------+----------------------------------------------+--------------+---------------+-----------+-------------+----------+--------+------+------------+---------+
| Table   | Non_unique | Key_name                                     | Seq_in_index | Column_name   | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment |
+---------+------------+----------------------------------------------+--------------+---------------+-----------+-------------+----------+--------+------+------------+---------+
| metrics |          1 | metrics_load_id                              |            1 | load_id       | A         |        1141 |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_journal_id               |            1 | metric_type   | A         |           3 |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_journal_id               |            2 | context_id    | A         |           3 |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_assoc_type_submission_id |            1 | metric_type   | A         |           3 |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_assoc_type_submission_id |            2 | assoc_type    | A         |           8 |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_assoc_type_submission_id |            3 | submission_id | A         |        9988 |     NULL | NULL   | YES  | BTREE      |         |
| metrics |          1 | metrics_metric_type_context_id_assoc_type    |            1 | metric_type   | A         |           3 |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_context_id_assoc_type    |            2 | context_id    | A         |           3 |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_context_id_assoc_type    |            3 | assoc_type    | A         |           8 |     NULL | NULL   |      | BTREE      |         |
+---------+------------+----------------------------------------------+--------------+---------------+-----------+-------------+----------+--------+------+------------+---------+
9 rows in set (0.00 sec)
```

Aside: Why the paring of `assoc_type` and `submission_id` in `metrics_metric_type_assoc_type_submission_id`?

The addition of `create index metrics_metric_type_assoc_type_assoc_id on metrics (metric_type, assoc_type, assoc_id);` reduces the fetch time for [`PublishedArticle::getViews()`](https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/templates/sectionEditor/submission/management.tpl#L96) from 15 seconds to less than 1 second in one of my installs.

Unless something were to construct the query without the `$contextId`, this should be ok in 3.x because of the oddly named `metrics_metric_type_submission_id_assoc`:
```
mysql> show indexes from metrics;
+---------+------------+----------------------------------------------+--------------+---------------+-----------+-------------+----------+--------+------+------------+---------+
| Table   | Non_unique | Key_name                                     | Seq_in_index | Column_name   | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment |
+---------+------------+----------------------------------------------+--------------+---------------+-----------+-------------+----------+--------+------+------------+---------+
| metrics |          1 | metrics_load_id                              |            1 | load_id       | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_context_id               |            1 | metric_type   | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_context_id               |            2 | context_id    | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_submission_id_assoc_type |            1 | metric_type   | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_submission_id_assoc_type |            2 | submission_id | A         |        NULL |     NULL | NULL   | YES  | BTREE      |         |
| metrics |          1 | metrics_metric_type_submission_id_assoc_type |            3 | assoc_type    | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_submission_id_assoc      |            1 | metric_type   | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_submission_id_assoc      |            2 | context_id    | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_submission_id_assoc      |            3 | assoc_type    | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
| metrics |          1 | metrics_metric_type_submission_id_assoc      |            4 | assoc_id      | A         |        NULL |     NULL | NULL   |      | BTREE      |         |
+---------+------------+----------------------------------------------+--------------+---------------+-----------+-------------+----------+--------+------+------------+---------+
10 rows in set (0.08 sec)
```

**Comment by ajnyga** [comment]
So I did a couple of test queries before and after the index, but could not see much difference.

What kind of queries were taking you 15 secs that were reduced to 1 sec?

I think that the index I added was to the day and month colums and these reduced the size of the db as well.

**Comment by ctgraham** [comment]
In 2.4.8 there is a call to `$publishedArticle->getViews()` in the Editor's view of the article Summary page.
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/templates/sectionEditor/submission/management.tpl#L93-L98

**Comment by ajnyga** [comment]
So it has to be this in OJS3: `SELECT month, representation_id, SUM(metric) AS metric FROM metrics WHERE submission_id = '9373' AND assoc_type = 515 AND metric_type = 'ojs::counter' GROUP BY month, representation_id ORDER BY month ASC LIMIT 5000` (btw. why the limit 5000 in the end?)

**Comment by bozana** [comment]
With this issue https://github.com/pkp/pkp-lib/issues/6782 we separated the metrics by assoc type, and added some indexes, which should improve it... So once that work is merged I will close this issue...

**Comment by bozana** [comment]
I hope this is improved with the changes here https://github.com/pkp/pkp-lib/issues/6782. Thus closing.
