### ISSUE TITLE
Make OJS2 to OJS3 metrics upgrade faster on large installations

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4131]
Discussion here: https://forum.pkp.sfu.ca/t/ojs-upgrade-from-3-0-2-to-3-1-0-1-stuck-on-slow-query/36706

The single sql query used to update the assoc_id's of assoc_type 531 is extremely slow in larger metric tables. For example a 900 megabyte metrics table takes around 34 hours to run the given query.

The query should be broken into smaller parts using an upgrade function. Pull request soon.

**Comment by ajnyga** [comment]
ping @bozana and @asmecher 
I have used this to upgrade a 2 gigabyte metrics table with around 160 000 531's and 7000 supplementary file hits. This took a little over an hour. I am running a new test with the same database right now.

**Comment by ajnyga** [comment]
The second test run with the 2 gigabyte metrics table now took 1.3 hours. The whole upgrade around 9 hours (not sure what the exact time was since it was finished during the night). The whole database was around 3.2 gigabytes.

For reference a  2 gigabyte db with 1 gigabyte metrics table took 34 hours with the old code.

**Comment by bozana** [comment]
merged, thus closing....
