### ISSUE TITLE
Fix review assignment updated notification recipient

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4133]
Ping @asmecher, the Saga continues.

See https://forum.pkp.sfu.ca/t/review-assignment-updated/49082/10

pr in a moment

**Comment by ajnyga** [comment]
edit: ok so this was actually already fixed in the master branch but committing a small addition to the code anyway (comparing the changed dates was not working because the other returned value included the time stamp 00:00:00)

**Comment by asmecher** [comment]
(PR: https://github.com/pkp/pkp-lib/pull/4134)

**Comment by asmecher** [comment]
Thanks, @ajnyga, I've merged that into `master`!
