### ISSUE TITLE
Lens Galley Plugin shows the wrong date

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4136]
For example, if JATS XML meta contains date in this format:
```
<pub-date date-type="pub">
  <day>10</day>
  <month>9</month>
  <year>2018</year>
</pub-date>
```
Lens Viewer will show 09 September 2018, thus, always substracting "1"
Related to: https://forum.pkp.sfu.ca/t/publication-date-in-lens-viewer/49077

**Comment by asmecher** [comment]
@Vitaliy-1, I suspect this is a problem with Lens Reader, not the OJS Lens Reader Plugin (which just integrates that software with OJS, and doesn't parse the XML itself). Maybe this should be filed at https://github.com/elifesciences/lens? (I wonder whether there's some time zone math done on that date by accident.)
