### ISSUE TITLE
Legacy SMTP connection can fail silently

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4137]
`SMTPMailer::connect()` captures the error number and string, but does not do anything with it:
https://github.com/pkp/pkp-lib/blob/e406013b405be3a1d887ec8dad9c4247b1ab7367/classes/mail/SMTPMailer.inc.php#L164-L169

If this function returns false, the caller (`Mail::send()`) doesn't do any logging with the failure unless `display_errors` is `On`.
https://github.com/pkp/pkp-lib/blob/e406013b405be3a1d887ec8dad9c4247b1ab7367/classes/mail/Mail.inc.php#L586-L596

**Comment by asmecher** [comment]
Thanks, @ctgraham!

**Comment by asmecher** [comment]
(Also cherry-picked to `ojs-stable-2_4_8`.)

**Comment by asmecher** [comment]
Hmm, I wonder why the linting tests didn't catch this...

**Comment by asmecher** [comment]
...of course, because the 2.x braches didn't get updated for the new Travis image and tests are disabled. And my local testing had SMTP set to `Off`.

Merged both, thanks, @ctgraham!
