### ISSUE TITLE
Prevent review form radio button preselection

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4147]
See https://forum.pkp.sfu.ca/t/ojs-3-reviewers-form-filled/46893 for details.

**Comment by asmecher** [comment]
@primoz-svetek, feel free to leave feedback here if you're able to test the fix, thanks!

**Comment by primoz-svetek** [comment]
@asmecher Thank you for the fix. I have verified it and it works.

**Comment by asmecher** [comment]
Thanks for checking, @primoz-svetek!
