### ISSUE TITLE
OCS paper detail page not loading locale keys

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4148]
The required locale file (manager.xml) is not being loaded by the page that displays the schedule. 
It is the following page:
`https://[domain]/index.php/conference/[conf_path]/paper/view/[id]`

It displays:
**##manager.scheduler.building##**: ...
**##manager.scheduler.room##**: ...
Date: 2018-12-06 09:15 AM – 10:00 AM 
Last modified: 2018-10-13 

In locale file there are both keys, and in correct language (english). However it is not being loaded.
I edited  fc-locale... to double check and include it manually as workaround.

**Comment by asmecher** [comment]
@israelcefrin, what version is this? (2.3.6 from `tar.gz`, 2.3.6 from `ocs-2_3_6-0` tag, 2.3.6 from `ocs-stable-2_3_6`, ...)

**Comment by israelcefrin** [comment]
Hi @asmecher it is a 2.3.6.0 (ocs-stable-2_3_6) version.
