### ISSUE TITLE
Enrich OAI-PMH options for journals that do not publish online

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4149]
Build on #3026, but consider @ajnyga's proposals added in response to https://github.com/pkp/pkp-lib/issues/3026#issuecomment-430249379:

> 1. just hide article url's for journals that are PUBLISHING_MODE_NONE
> 2. my old suggestion above: a journal specific setting for enabling/disabling OAI

**Comment by pigeonm** [comment]
Thanks @asmecher! So I can tell the librarian that this is not possible at the moment, but that it will be possible with a next release?

**Comment by asmecher** [comment]
@pigeonm, yes, that's correct.

**Comment by asmecher** [comment]
(Watch for the "Milestone" field to indicate which release it'll come out in -- that's not designated yet.)

**Comment by asmecher** [comment]
PR: https://github.com/pkp/ojs/pull/2167

@NateWr, would you mind reviewing this? It adds a checkbox to the Access form permitting the manager to enable OAI even though records won't be published with OJS. For journals that use this, the OJS article URLs are removed from the OAI records.

I'd like to merge this to `ojs-stable-3_1_1`, but the setting will need to be rewritten for the new forms you're working on -- hence why I'm giving the review to you :) (and why I'm using inline styles etc. for an expedient fix to the existing stable branch).

**Comment by asmecher** [comment]
(This is getting prioritized as it's a Coalition Publi.ca requirement for some journals.)

**Comment by NateWr** [comment]
By chance, I just noticed that there is an OAI setting in the config file. Does this need to be changed, removed, used during migration?

**Comment by asmecher** [comment]
No -- that's the "global" enable/disable setting. As long as it's turned off, the OAI interface will be totally unavailable. It's a big circuit breaker.

**Comment by NateWr** [comment]
@asmecher I've looked over the discussion here and in https://github.com/pkp/ojs/pull/2167 and it's not clear to me what remains to be done. Does the PR just need review and rebasing against `stable-3_1_2`?

**Comment by asmecher** [comment]
Did an equivalent to https://github.com/pkp/ojs/pull/2167 get included in the `master` branch with your form rewrite? If so, and you're OK with https://github.com/pkp/ojs/pull/2167 going into `stable-3_1_2`, then let me know and I'll merge and close.

**Comment by NateWr** [comment]
Ok, I remember now. It looks like the property and the form are in `master`, but not the changes to the OAI and metadata handlers. I've merged your PR to the stable branch. For master, I've cherry-picked your commit in and discarded the form changes.

PR:
https://github.com/pkp/ojs/pull/2261

Once the tests pass this can be merged and closed.

**Comment by asmecher** [comment]
The `disable_path_info` test failed, but the rest are OK. Merging and closing, thanks!
