### ISSUE TITLE
Custom Reviewer Form: TinyMCE field is missing

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4154]
OJS 3.1.1-4

Default reviewer form. As can be seen, under "Enter (or paste) your review of this submission into the form below." the input field is present :
![default_review](https://user-images.githubusercontent.com/20665587/47082988-08979500-d218-11e8-8612-dcc0a0a82783.png)

Custom reviewer form. The label is still there, but the input field is missing:
![custom_review](https://user-images.githubusercontent.com/20665587/47083048-38469d00-d218-11e8-8c15-8bbc168c82b4.png)

**Comment by asmecher** [comment]
That's intentional -- the custom review form replaces the built-in TinyMCE fields.

**Comment by asmecher** [comment]
Do you mean the label `Enter (or paste) your review of this submission into the form below`? This label applies to the form as a whole, whether it's the default review form or the custom one.

**Comment by Vitaliy-1** [comment]
Ahh, OK.
