### ISSUE TITLE
Review Forms: hide review forms that are no longer in use

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4155]
This form in OJS 3.1.1-4:
![review_forms](https://user-images.githubusercontent.com/20665587/47083969-e5bab000-d21a-11e8-9a8f-c37b099df8b4.png)

Proposals:
- when user removes a mark from "active" checkbox, hide the form.
- add a menu button for viewing inactive forms
- if the form wasn't used anywhere, add an option to delete or edit it.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
