### ISSUE TITLE
Empty query lingers after closing new query modal

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4157]
@asmecher I think you've said you have killed a bunch of these. I think I found one more. If open the new query modal and then reload the page (without closing the modal), the empty query doesn't get removed.

**Comment by asmecher** [comment]
@NateWr, quick sanity check on the approach? I don't like using the `window` global but anyway.

PRs:
- https://github.com/pkp/pkp-lib/pull/4163
- https://github.com/pkp/ojs/pull/2140 (tests + JS minification only)

**Comment by NateWr** [comment]
:+1: I am not aware of any other way to account for this scenario.

One thing to test: are there any side effects that are produced when you open/close several modals and then open and refresh? I believe `$(window).on('unload', ...)` will register an event listener each time a modal is opened, but won't unregister the event when closed. So you may have several events firing for each time the modal was opened.

In `handleCancelAction` you may need to do `$(window).off()`. If so, the [namespacing for events](http://api.jquery.com/off/) might be important. I think that would look something like this:

`$(window).on('unload.pkp', ...)`

Then:

`$(window).off('.pkp')`

**Comment by asmecher** [comment]
@NateWr, have a look at https://github.com/asmecher/ojs/commit/a1b38787425f89ed65184b56a0ddf077c21a218a -- it should take care of this safely by using specific handler objects as second parameters to the `.on` / `.off` calls.

**Comment by NateWr** [comment]
Yes, I think that will work. :+1:

**Comment by asmecher** [comment]
Thanks, @NateWr!
