### ISSUE TITLE
Update of Italian transaltion in master

### ISSUE THREAD

**Issue by ztajoli** [pkp/pkp-lib#4159]
If fact we need to update master italian transaltion

**Comment by ztajoli** [comment]
I plannig to update the present.
I will do PR in 1-2 hours.
Thank you.
----- Messaggio originale -----
Da: Alec Smecher <notifications@github.com>
A: pkp/pkp-lib <pkp-lib@noreply.github.com>
Cc: Zeno Tajoli <z.tajoli@cineca.it>, Mention <mention@noreply.github.com>
Inviato: Wed, 17 Oct 2018 21:27:27 +0200 (CEST)
Oggetto: Re: [pkp/pkp-lib] Update of Italian transaltion in master (#4159)

@ztajoli, can you clarify? Are you asking for an updated translation, or planning to create one?

**Comment by asmecher** [comment]
Thanks, @ztajoli, updates are always welcome!

**Comment by mtub** [comment]
Tracking here: pkp/pkp-lib#4185
