### ISSUE TITLE
Support generating DMARC compliant mails

### ISSUE THREAD

**Issue by tgc** [pkp/pkp-lib#4164]
The DMARC RFC seems quite clear, the RFC5322.From (the From: header) must have domain alignment with either the RFC5321.MailFrom (envelope sender) domain that passed SPF validation and/or the domain in a valid signed DKIM d= tag.

Currently OJS puts a user provided email address into the RFC5322.From field, an email address which can be in any random domain. This is basically spoofing the RFC5322.From which is exactly what spammers have done for decades and it makes mail from OJS indistinguishable from spam in the eyes of DMARC since the sending OJS host cannot by default provide a valid SPF record and/or DKIM signature on behalf of a user provided 3rd party domain.

There must be a facility to ensure that the RFC5322.From header is not spoofed or DMARC compliance is not possible.

**Comment by tgc** [comment]
I have submitted two pull requests for discussion that would implement something like this.
Please see:
https://github.com/pkp/pkp-lib/pull/4165
https://github.com/pkp/ojs/pull/2142

**Comment by ctgraham** [comment]
Hi, @tgc.  The way we are currently targeting this is by the use of `default_envelope_sender` and `force_default_envelope_sender`.  This provides you the option to set a domain-aligned and DKIM-signed envelope From.

Can you clarify why it is important to also allow the option to munge the From field independently?  Is there a reason you cannot sign and use the envelope from?

**Comment by tgc** [comment]
Because DMARC only looks at the RFC5322.From and from that it derives a domain, and that domain must match the SPF validated domain or the DKIM signing domain (d= tag).
I cannot SPF validate or DKIM sign mails on behalf or 3rd party RFC5322.From domains without their cooperation.

What OJS seems to be doing now is what is described here in the DMARC FAQ:
https://dmarc.org/wiki/FAQ#Why_are_messages_I_send_on_behalf_of_visitors_to_my_website_being_blocked.3F

You cannot do that and be DMARC compliant.

The DMARC RFC is here:
https://datatracker.ietf.org/doc/rfc7489/?include_text=1

**Comment by ctgraham** [comment]
Hmmmm.... yes, I concur.  RFC 7489 3.1 explicitly states:

> DMARC authenticates use of the RFC5322.From domain by requiring that it match (be aligned with) an Authenticated Identifier.  The RFC5322.From domain was selected as the central identity of the DMARC mechanism because it is a required message header field and therefore guaranteed to be present in compliant messages, and most Mail User Agents (MUAs) represent the RFC5322.From field as the originator of the message and render some or all of this header field's content to end users.

If further investigation confirms no way around this, I'm inclined to retool the existing `force_default_envelope_sender` parameter to re-write the `From` directly, rather than adding a new config.inc.php parameter.  The new semantic would be something like "force default envelope sender [to also be the From]".

**Comment by ajnyga** [comment]
For some reason I missed this ticket.

I would like to second the suggestions made here. See my recent test with a Finnish university email server: https://github.com/pkp/pkp-lib/pull/4165#issuecomment-431028800

**Comment by asmecher** [comment]
Thanks, everyone! See https://github.com/pkp/pkp-lib/pull/4165#issuecomment-457383779 for a summary.

**Comment by bdmckay** [comment]
The config file changes in #2142 include a field %s in dmarc_compliant_from_displayname for localized sitename, but the new code in Mail.inc.php (#4164) does not substitute anything there.  Brendan.

**Comment by Velliz** [comment]
So... i must upgrade OJS to version 3.1.2 to resolve the error?

```
SMTP Error: data not accepted.
SMTP server error: DATA END command failed 
Detail: STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message.
```

**Comment by bdmckay** [comment]
We applied [this](https://github.com/pkp/pkp-lib/pull/4165/commits/8a4bd765470b4011a5d877e1bbf074b144739fa2) and [this](https://github.com/ptrckb/ojs/commit/f9a45c1679cb6b8676f91a3412075a9527c52ad7)  manually to OJS 3.1.1-4 and it works fine. That doesn't mean it will work for you.
Set force_default_envelope_sender and force_dmarc_compliant_from to On, and define a value for dmarc_compliant_from_displayname.  If %s doesn't give what you want, just put in a fixed value.

**Comment by Velliz** [comment]
Thanks for pointing the commits and config template file. My OJS installation is meet version 3.1.1-4 as you mentioned. 

I will try to change that part and report the results here later.

**Comment by Velliz** [comment]
@bdmckay your sugestion is worked perfectly on my OJS installation! Thanks!

**Comment by micheljp** [comment]
Is there a solution for this problem on 2.4.x? I'm on 2.4.8.1

**Comment by ctgraham** [comment]
@micheljp , I'm using the following patch to accomplish this in 2.4.8.x:
https://github.com/ulsdevteam/pkp-lib/commit/c17673c390e16a9914d7c38c42e612278d248994
