### ISSUE TITLE
[OJS] getPublishedArticleIdsByJournal() can return unpublished objects

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#417]
When an article is scheduled against an upcoming issue, it receives an entry in the published_articles table, along with a publication date. The function getPublishedArticleIdsByJournal() checks for this publication date, but doesn't check whether the issue itself has been published, which allows it to conceivably return unpublished articles. 

The function getPublishedArticleIdsBySection() just below checks that "i.published = 1", which this function should also do ... a bit beyond my ability level to do this nicely in the SQL for getPublishedArticleIdsByJournal() though. Any assistance appreciated!

**Comment by asmecher** [comment]
James, have you confirmed that behavior through the UI?

**Comment by asmecher** [comment]
Fixed -- and confirmed that this function isn't going to cause problems. It's only used in the JM's PubMedExportPlugin.
