### ISSUE TITLE
All authors are listed as "First" in Crossref Metadata

### ISSUE THREAD

**Issue by ncorlett** [pkp/pkp-lib#4171]
When the crossref XML export plug in generates XML meta data, every author has: `<person_name contributor_role="author" sequence="first">` rather than just the first author with additional authors having `<person_name contributor_role="author" sequence="additional">`

As far as I am aware this can be reproduced by exporting the Crossref XML for an article with multiple authors.

**Comment by asmecher** [comment]
@ncorlett, thanks for reporting. Could you try the attached patch (both are equivalent) and report whether it fixes the issue for you?

**Comment by ncorlett** [comment]
Thanks for the patch. It works!

Sorry for the delay, it took as a while to implement the patch.

**Comment by asmecher** [comment]
Thanks, @ncorlett!
