### ISSUE TITLE
Add review assignment details and progress tracking to submission lists

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4172]
**Describe the problem you would like to solve**
As an editor
I want to get a rough sense of a submission's progress through peer review _at-a-glance_
so that I can more easily manage and track a large number of submissions, and compare their progress quickly.

**Describe the solution you'd like**
Include detailed information about the review assignments in the submission list. This should include the days remaining until the due date, whether the review has been completed or not, and the ability to fetch more details about each review without leaving the page.

See screenshots below.

**Who is asking for this feature?**
This has been identified as a major priority for editors in focus groups, UX research, and partner feedback.

**Additional information**
The following mockups suggest how this information could be added to the submission lists in order to give an overall view of progress as well as quick access to more detailed information.

An overview of reviews would give quick information about the review stage.

![reviews-overview](https://user-images.githubusercontent.com/2306629/143866179-558c799e-9c93-4c8c-8c19-8de7c5fb3530.png)

- Review / 1 = submission is in round one of review
- 72 days ago = submission entered the round of review 72 days ago

For each review assignment, a circle will appear to indicate the deadlines and incomplete/complete status.

![reviews-status](https://user-images.githubusercontent.com/2306629/143866504-377f329e-4e1c-4548-a212-6643cbc5fb6f.png)

- Green = complete
- Red = overdue
- Red outline = recently overdue
- Orange outline = will be overdue soon
- Blue outline = waiting for the reviewer to accept or complete the review

To help editors understand and learn the indicators, each circle can be clicked on to learn more about the review.

![reviews-completed](https://user-images.githubusercontent.com/2306629/143866808-51bd4070-d2e6-4348-927b-9e1a71c55b0c.png)
![review-accepted](https://user-images.githubusercontent.com/2306629/143866970-1dd8cdee-faed-4b2a-9a6f-75090c5b90ac.png)
![reviews-deadline-soon](https://user-images.githubusercontent.com/2306629/143866975-e0bc249b-6b46-415d-9265-6af0936eacd6.png)
![reviews-overdue](https://user-images.githubusercontent.com/2306629/143866976-980e954e-1780-449f-908e-b353a43118e2.png)

This issue description has been rewritten to reflect proposed changes for 3.5. The original issue description is below.

> This issue builds on UI/UX feedback and discussions in https://github.com/pkp/pkp-lib/issues/4103 and https://github.com/pkp/pkp-lib/issues/1662, which highlight the desire for more fine-grained status reporting from the submissions list.
> 
> Most of this feedback focuses on the Review stage and it is the stage with the fewest technical obstacles to providing more fine-grained status. Within the review stage we have the following indicators we can use to signal progress:
> 
> - How many reviewers are assigned in the current round
> - How many reviewers have accepted/declined in the current round
> - How many reviewers have completed their review in the current round
> - Has a request revisions editorial decision been made since the current round was initiaited
> - Have revisions been submitted since the last editorial decision was made
> - How many review rounds have been initiated
> - How many days a submission has been in a review round or the whole review stage
> 
> Figuring out how best to represent progress will require some experimentation. We discussed the possibility of using a progress bar, which would give a very quick comparison but lacks detail about why a particular progress level is calculated. This could maybe be compensated with information it the dropdown display. A dot-system has been proposed at https://github.com/pkp/pkp-lib/issues/4103 with the caveat that interpretation of the dots be difficult without specific training. 
> 
> I have assigned this to the 3.2 milestone because it was considered a high priority for UI/UX improvements. However, because that milestone is already overloaded this shouldn't be taken as a promise that it will make the deadline.

**Comment by twakeford** [comment]
@NateWr I'd be happy to help try and spec this with you (I'm coming from a non-tech perspective). The need for having higher resolution overview of submissions in review from the submission dashboard has been flagged as the top priority from our editors. The key feedback we have had is that a) they want to see the stage of the review process from an overview dashboard, not have to go into each submission, b) they don't want to have to click drop-down/additional menu to see the information on a submission level (as they'd have to do it for every submission), and c) they would like the system to highlight relative urgency/delayed tasks in this overview.

One thing that we have found very useful for editors is a 'days at stage' metric, so that editors can easily see from this dashboard whether the submission has got a little stuck. e.g. Having 2 reviewers submitted looks ok, but if they have sat there for a long time then there is an urgency for the editor to act, which is invisible from the currently submission list.

We customised OJS 2 to do something similar, and your list above seems spot on in the stages that we log. In the old OJS 2 table view, we added a stage name as a column where each stage had set parameters, with a column next to it showing the number of days that it had been at that stage.

For the review stages, something like the below may be useful:
- Ready for review: in the review queue, but a minimum number of reviews have not been invited (the minimum reviewers required could be a journal setting)
- Reviews invited: the minimum number of reviewers have been invited, but not yet accepted
- Reviews outstanding: the minimum number of reviewers have accepted an invitation to review but not yet submitted the review
- Reviews complete: the minimum number of reviews have been provided
- Awaiting Revisions: the editorial decision for revisions has been logged but the author has not yet submitted a revised file
- Revisions submitted: the author has provided the revisions and the editor needs to make a decision or start a new round of review (which brings us back to 'Ready for Review')

If such parameters could be well defined, could the current stage/filter button show the higher resolution stage? e.g. 'Reviews outstanding' rather than 'Review'. This would have the added benefit of allowing senior editors/Managing Editors to filter so that they can focus on specific aspects of the workflow.

**Comment by alexxxmendonca** [comment]
This is all very nice and very welcome.

We did a customization at the SciELO install in which we used a color system and some instructions at the bottom of the page explaining what each color meant. It has proven to be quite helpful and journals tend to rely and get used to what each color means.

_One thing that we have found very useful for editors is a 'days at stage' metric, so that editors can easily see from this dashboard whether the submission has got a little stuck._ 

In the past I have asked whether it would be possible to set deadlines for each task individually. It seems that this would require a lot of development so this solution -- days at stage, instead of days to become overdue -- seems to be a good solution.

I fully agree that having a days count (increasing or decreasing) would be very helpful.

**Comment by NateWr** [comment]
Thanks @twakeford! That's really helpful and it sounds like we're looking for the same things.  I'll be circling back to this probably sometime early next year to work on it in earnest. In the meantime, here are a few quick thoughts.

Text labels can be difficult to design around because they can vary significantly from language to language, but figuring out a reliable way to signal the review steps, and where it's currently at, will be very important, and will almost certainly require text.

I'd like to breakdown the steps you describe into two categories: the editor needs to do something and the editor needs to wait. We can then highlight those which fit the first category and (hopefully) help editors hone in on the things awaiting their attention.

> I fully agree that having a days count (increasing or decreasing) would be very helpful.

We're planning a filter to view the submissions by those last modified more than X ago (https://github.com/pkp/pkp-lib/issues/4168). I hope that will work as a catch-all to help discover those languishing in review as well as other stages for too long.

**Comment by twakeford** [comment]
thanks @NateWr, happy to be of help. 

Good point on the text labels and language issues. Perhaps a universal/language non-specific stage icon would be an option, with a key located elsewhere?

Breaking the steps into editorial action / no editorial action seems ok, but that context may change without system changes - e.g. awaiting review = no editor action if they have only recently been accepted, but there would be editor action is the reviewers had missed their deadlines.

The 'last modified' filter sounds like a good start.

Give me a shout when you're nearer to looking into this and happy to discuss.

**Comment by NateWr** [comment]
Feedback from the UI/UX group in the Pittsburgh sprint, when we were able to talk to an editor at a high-volume journal:

- Revise and resubmit decisions should be clearly separated from other review tasks. About 50% of revise and resubmit never come back, so these pile up over time.

**Comment by PeterfordUP** [comment]
![Screenshot 2020-06-19 at 17 12 29](https://user-images.githubusercontent.com/43379772/85313421-e99edb00-b4af-11ea-9e21-f852730ffac3.png)
@NateWr In our custom forked OJS2.x platform, we have developed a display that shows the sub-stages of the articles in the 'Review' stage (see image), and importantly, the number of days each article has been in that stage (both circled in green in this screenshot). The list can be both filtered and ranked according to these metrics.
The 'sub-stages' that we identified, were presented by Tim Wakeford earlier in this thread, but I will list them again here for completeness:

- **Ready for review**: editor has been assigned but the minimum number of reviewers have not been invited
- **Reviewers invited**: the minimum number of reviewers have been invited, but they have not yet responded/accepted
- **Reviews outstanding**: the minimum number of reviewers have accepted review invitations but have not yet completed their task
- **Reviews complete**: the minimum number of reviewers have submitted their review feedback
- **Awaiting revision**: the editorial decision of 'Request revisions' or 'Resubmit for Review' has been made but the revisions have not yet been provided
- **Revision submitted**: the author has submitted their revisions after the 'revisions' decision was made

When an 'accept' or 'reject' decision is recorded, the article leaves the Review stage and appears in the 'Editing' stage. This display allows editors to visualise the article list according to those needing the most urgent attention and gain a quick understanding of the actions required for each article, without leaving the submission list to further investigate the status articles.

**Comment by NateWr** [comment]
Thanks @PeterfordUP! There's a whole bunch to unpack here -- I'm going to keep the comments here focused on improving the review stage data. But I'd like to have a broader conversation with you about the submission lists.

First, I want to review what we've got so far in the submissions lists and then discuss what we're missing and how best to add that in.

![review-submissions](https://user-images.githubusercontent.com/2306629/85382092-8310d000-b536-11ea-9866-483746cf3a11.png)

Each submission in the review stage has an indicator, such as 3/3 in the first submission. This says that 3 reviews have been assigned and 3 reviews have been completed. The second submission (0/2) shows that 2 reviews have been assigned but 0 have been completed.

In addition, we show an alert message when we determine that there is work outstanding for the editor. This is shown when no reviewers are assigned, when new reviews have been submitted, when all reviews have been submitted and a decision is needed, and when revisions have been submitted.

When authors are viewing their own submission, they see similar messages when revisions are requested.

These messages cover much of the same ground as the sub-stages. But we have had community requests for a more explicit description following the sub-stage model that you have implemented -- in part, I suspect, because when the alert messages don't appear editors feel uncertain about the status.

One way to address this that we've considered is to add filters for these sub-stages. We've tried to reduce the number of different stages to a more easily digestible set, and have suggested the following:

![63331966-a7a48600-c32e-11e9-8d8e-ea72fe4141a7](https://user-images.githubusercontent.com/2306629/85383243-a720e100-b537-11ea-9c5e-0d941c9826a5.png)

This would provide a quick way for an editor to keep tabs on what seem to be the key task breakdowns during the review stage.

---

So the question is whether you think these approaches might satisfy some of your requirements and what additional information or tooling needs to be implemented to support your other requirements. Looking at what you've provided, I think we're still missing the following:

1. An indicator of how many days a submission has been in the review stage.
2. We have no concept of "minimum required reviewers". This strikes me as an interesting feature that might be worth adding (probably configured on a per-section basis).
3. Information about review assignment due dates and completion dates.
4. Information about review round.
5. If you think the filters won't satisfy your needs for sub-stage indications, then some info on a review sub-stage.
6. Ordering the list by these parameters.

The challenge will be providing some of this information in a dense format that is not a table. It is our ambition to some day make submission lists usable on mobile devices, so we're avoiding table layouts which have minimum width requirements. (This is something to maybe talk about.)

One option is to include some of this information in a brief description.

![review-notice](https://user-images.githubusercontent.com/2306629/85385633-72faef80-b53a-11ea-954b-fe9602020121.png)

Another option is to use icons to display the information. I have to admit I'm not very confident in the legibility of this approach and would prefer to avoid using stuff like this to display dense information.

![review-icons](https://user-images.githubusercontent.com/2306629/85386484-92dee300-b53b-11ea-84c7-c6fac1f8dc86.png)

If a setting for minimum required reviewers was added I think this could be integrated with the notices to highlight when enough reviewers have been added. That just leaves out ordering the list, which has some bigger challenges in regards to the list's UI architecture. We probably need to be talking more broadly about the submission lists before we can tackle that.

In the meantime, maybe have a think about this and then we can discuss further where your work could fit in. We'd probably want to do some mockups and UI/UX tests on any major revisions to the submission lists, but we have some experience doing that and would benefit from having a committed development partner willing to work through the delicate parts of the application like these lists. :+1:

**Comment by NateWr** [comment]
I have updated the original issue description to reflect improvements we have scheduled for 3.5. Please review the description and mockups above to see if the reflect your need.

Improvements related to filtering submissions will be filed separately.

**Comment by twakeford** [comment]
@NateWr this looks v promising. From a quick review I just had the below questions/points:

1 - re
- Red = overdue
- Red outline = recently overdue

I'm not sure that having two options is required. If something is overdue then it is overdue. The number clearly informs the editor on how overdue it is and whether they should act or give a bit of leeway = having only 1 'overdue' option may help to simplify things.

2 - I'm wondering whether there is a need to differentiate between invitations that have been accepted and those that have not had a response to the invitation. I can imagine that editors would prefer to be able to know _at a glance_ whether they need to chase invitations that haven't had a reply or a reviewer who has already agreed to complete the review. As they will have separate actions, a visual difference may be worth considering.

**Comment by twakeford** [comment]
interesting - our editors are the opposite, they want to chase immediately! (long-term, we actually want to add auto emails that will send to a reviewer _before_ the due date as a pre-chase/reminder that the deadline is fast approaching)

**Comment by fgnievinski** [comment]
> > I'm wondering whether there is a need to differentiate between invitations that have been accepted and those that have not had a response to the invitation
> 
> I'm inclined to say no. They both have due dates and if we encourage people to use these well, then the status indicator can clearly indicate overdue status in both cases. If we try and distinguish these, I worry we're going to be adding another visual dimension to the already complex indicators. And I'm not sure how we would make the distinction without adding visual noise.

+1 for differentiating between reviewers who have committed to provide a review and those who have just ignored the invitation, as the latter are more likely to end up unassigned, while the former normally get an extension. I'd suggest the following labels:
- "Invited": after first invitation and before first invitation reminder
- "No Response": after the RSVP date or first invitation reminder
- "Overdue" (or Outstanding or Pending): only after a positive response confirming reviewer's availability and after the review due date.

**Comment by NateWr** [comment]
> I'd suggest the following labels

Ah, yes, that's good. I was thinking of a visual distinction in the small circular icons. But yes, the text label in the red "badge" here should change between "Overdue" and "No Response":

![](https://user-images.githubusercontent.com/2306629/143866976-980e954e-1780-449f-908e-b353a43118e2.png)

**Comment by asmecher** [comment]
A note about the pop-overs that provide more detail about individuals (e.g. reviewers): a SciELO pilot journal raised affiliations as a particularly useful detail.

**Comment by NateWr** [comment]
Can you say more about why affiliations would be useful? I would think affiliations would be useful when selecting and assigning a reviewere. But the pop-overs here appear after that's already been done.

**Comment by Devika008** [comment]
I agree with Nate. On the pop-overs we should stick to the minimum details whereas other information about the reviewers can be found in the reviewer panel wherein more information about the reviewers can be given on expanding the detail.

**Comment by NateWr** [comment]
That makes sense. Devika has already designed such a quick-access panel and I think her user research will help identify the information most valuable to show in that panel.

In this case, I'm guessing the Scielo pilot was interested in seeing the author affiliations -- maybe to see a submission's title and authors similar to how it might be presented in a public display.

**Comment by Devika008** [comment]
What I am also thinking is that in the new table we are designing, there is a column for assigned which includes circular images of those assigned. Just the way we click on review boxes for a pop-up to come, maybe if its an issue which is needed, in the panel that opens on hovering over the images of the assigned, we can show the affiliations or any details that are shown

**Comment by Devika008** [comment]
This has been incorporated in the new submission dashboard by @jardakotesovec
