### ISSUE TITLE
Custom Block Manager does not work in site settings

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4173]
Reproduce:

1. Go to Administration > Site Settings > Plugins
2. Enable Custom Block Manager
3. Open Custom Block Manager actions and click "Manage Custom Blocks"

The settings modal does not open and an error message appears:

"No journal in context"

**Comment by asmecher** [comment]
Either of the attached patches, to be applied in `plugins/generic/customBlockManager`, should resolve the problem.

**Comment by ajnyga** [comment]
Coming to 3.1.2?

**Comment by NateWr** [comment]
I believe all the commits to a `3_1_1` branch were included in the `3_1_2` branch.
