### ISSUE TITLE
OJS Integration with Dryad Data Repository

### ISSUE THREAD

**Issue by dlowenberg** [pkp/pkp-lib#4176]
Feature Request: Integrate, in a similar fashion as you did with Dataverse, with Dash. Dash is the open source platform that Dryad is moving onto. 

The Dash API: https://dash.ucop.edu/api/docs/ 

In this integration we envision that OJS could support deposits to Dryad (sending the article metadata) so that Dryad can send back the data citation (and a private for peer review URL).

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
