### ISSUE TITLE
[OJS] Filter article's references field to link urls

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#4178]
This is a feature request... so is not something dramatic, but we think will make editor's life easier.

The point is, when the authors or the editor fills metadata in the article's references field, urls are publish as text, but not linked. The field is plain text but accepts html tags, so I trained my editors to add an html <a> tag to make the url functional... but it's a machine work, that would be nice if is done by a machine.

This is how this looks like: https://papers.uab.cat/article/view/v103-n4-oca-sanchez

So, is it possible to filter this field to add <a href="http://whatever.dot" target="_blank">http://whatever.dot</a> to every http/https field?

Thanks for your time,
m.

**Comment by marcbria** [comment]
As a bonus pack, with an extremely low priority... could this be extended to DOIs? I mean, most of us are publishing DOIs as urls (ie: to crossref proxy), but APA recommends using DOI format, so would be nice filtering "10.????/" and link to the proxy the admin set in ojs's config file or whatever?

**Comment by bozana** [comment]
@marcbria, the following part of the code, should parse a reference and look for http, https and ftp ... and make a link out of it: https://github.com/pkp/pkp-lib/blob/ojs-stable-3_1_1/classes/citation/Citation.inc.php#L55-L65. Does it not work for you? Which OJS version are you using? Or did I misunderstood the first comment above?

**Comment by bozana** [comment]
Hmmm... regarding the second feature I am not sure if we would like to do that, because the journal could use any citation format... I'll see with the others i.e. wait for their comments here...
But a Crossref DOI linking will come with this issue, probably in 3.2 release: https://github.com/pkp/pkp-lib/issues/3804

**Comment by marcbria** [comment]
Let's make it simple: Forget the second feature. Is not well though yet... :-)
What do you think about the http/https filter?

**Comment by marcbria** [comment]
First feature is implemented in ojs 3 and Bozana's argument made us notice second feature request was not generic enough to be implemented, so it need to be closed.
