### ISSUE TITLE
[OJS] delete a note with a file in a query cause error500 for editorialhistory

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#4179]
Hi all,

I think I have found a bug (OJS 3_1_1_2 not tested on other versions).
When you add a message in a query with a file, an EventLog is recorded.
But when you delete the message, corresponding EventLog is not deleted and when you want to see editorial history, which it seems to be the list of EventLog for a submission, you have an error 500.

I think that record an EventLog when a file is upload in a query is not necessary ?

Best regards,

**Comment by asmecher** [comment]
This is not a great solution, but the attached patch will remove the "Download" link from event log entries involving files that relate to deleted queries. These will remain on the server, thus auditable, but it'll need to be done from there for now.

**Comment by forgive38** [comment]
Thanks !
