### ISSUE TITLE
Modals can disappear in RTL languages

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4182]
Modals cause a horizontal scrollbar to appear in RTL languages and this can effectively "hide" the modal. See https://forum.pkp.sfu.ca/t/ojs-3-looses-pop-up-form-in-right-to-left-locales/49320/4?u=natewr

**Comment by NateWr** [comment]
PR from @jamshidhashimi:
https://github.com/pkp/pkp-lib/pull/4227

**Comment by NateWr** [comment]
Thanks @jamshidhashimi! I'm not sure about this technique, because we have cases where content may overflow the modal in the `x` direction. For example, a file table inside of a modal will sometimes exceed the modal's width. It's not ideal, but I believe `overflow-x: hidden` would make that content impossible to access.

Looking at the CSS code for the modal and the rtl stuff, it seems likely to me that there is something extending the width of the `<body>`. Most likely, it is something automatically positioned "off screen" to the left, which needs to be adjusted to the right for rtl languages.

But that wouldn't explain why your fix addressed the problem...

**Comment by jamshidhashimi** [comment]
@NateWr Thank you. Good questions and concerns. I found the issue. I noticed in many files: grid.less, notification.less, form.less and head.less whenever the element is required to be off screen, the following is used:

`left: -9999px;` [here](https://github.com/pkp/pkp-lib/blob/master/styles/form/form.less#L189) in form.less

and changing that to:

`right: -9999px;`

in RTL fixes the issue in the RTL UI.

Although my initial solution is fixing the issue by disabling that `-9999px` value of `<div class="input" data-pkp-editable-view="input">...</div>` but this looks a better solution to address it.

Additionally, later at some point, we can explore ways on how we can reduce the usage of all these `left` and `right` properties and adapt a more naturally RLT compatible solutions.

**Comment by NateWr** [comment]
:+1: Yes, that sounds about right. I suppose if any of the content inside of a modal has `left: -9999px`, it might cause that issue in the modal.

I'd definitely be open to suggestions you have for replacing the use of absolute positioning in these UI components. I use off-screen absolute positioning to keep an item in the DOM accessible for assistive technology (ie - screen readers) where a `display: block` would create accessibility problems. If you think there's a better way to solve this that's great.

I know that some CSS pre-processors have a toolset for automatically generating RTL changes for `margin`, `padding`, `text-align` and other positioning properties. But I'm not aware of a specific tool that will work with our PHP-based LESS-to-CSS compiler.

There's a suggestion to [use a mix-in](https://stackoverflow.com/a/9148570) here, which might be an interesting approach. We might be able to adapt that so that we override the mix-in inside the `rtl` styles. If not, we could consider compiling a separate RTL stylesheet.

**Comment by NateWr** [comment]
I think in these cases the additional `width`, `height`, `overflow` and `overflow-x` properties are not required. And when implementing it in RTL we would still need something like this:

```
body[dir="rtl"] {
  [data-pkp-editable-view="input"],
  [data-pkp-editable-view="input"] label:not(.error),
  &.isEditing [data-pkp-editable-view="display"] {
    left: auto;
    right: -9999px;
  }
}
```

Is that what you were thinking? Or am I misunderstanding something?

**Comment by jamshidhashimi** [comment]
In the example above, I am implementing those additional properties to the element itself (the element we want to hide from screen but visible to assistive technologies). Implementing that to the element itself makes sure we are not affecting any other element anywhere, including the Modal.

Let's say we are in the RTL UI, as we are implementing `overflow-x: hidden` to the element itself, it doesn't matter if it is `right` or `left`, it does the work.

The resource I shared in my last comment was really helpful. Please let me know if there are still concerns around it.

**Comment by NateWr** [comment]
Have you tested this and does it fix the problem? If so, then go for it. I must be misunderstanding the issue, because I thought it was the positioning, not the width or overflow, that was causing the issue. But if it solves the problem then :+1:!

**Comment by jamshidhashimi** [comment]
@NateWr, everything was working with the above solution but during my tests, I noticed the file name edit feature inside Modals were not working in RTL UI. It was somehow creating problem there. 

I then went the solution you were pointing in this [comment](https://github.com/pkp/pkp-lib/issues/4182#issuecomment-440606858) and that implementation worked well. The current PR resolves both the [reported problem](https://forum.pkp.sfu.ca/t/ojs-3-looses-pop-up-form-in-right-to-left-locales/49320/4?u=natewr) and also doesn't interrupts with file name edit feature and I tested them both.

Please let me know if you had any questions.

**Comment by NateWr** [comment]
:+1: Looks good @jamshidhashimi. Thanks for tracking all that down. Our usual approach is, when you open a PR, add a link here and ask for a code review from myself, Alec or Bozana. Like this:

PR:
https://github.com/pkp/pkp-lib/pull/4254

Usually, just rotate who you're asking for review, but sometimes one of us will be more appropriate to review something. In this case, since it's CSS, I'm probably the right person to review. I'll take a look now.

**Comment by NateWr** [comment]
Merged!

**Comment by jamshidhashimi** [comment]
Thank you @NateWr for the merge and instructions. I will follow those steps in my future PRs.
