### ISSUE TITLE
Trouble installing Open Journal Systems

### ISSUE THREAD

**Issue by SarahEditorialAssistante** [pkp/pkp-lib#4183]
I download the latest Open Journal Systems and it just gives me the folder and does not install the programme. I have a mac desktop computer. Please help.

**Comment by asmecher** [comment]
@SarahEditorialAssistante, I'd suggest posting on our support forum (http://forum.pkp.sfu.ca/) -- this area is more for bug fixes and discussion of new features. But do you have a web server running on your computer? If not, you'll need something like MAMP in order to run OJS.
