### ISSUE TITLE
Submission and Publication Metadata window freezes after editing

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4184]
In OJS 3.1.1-4, when you are in the submission dashboard and you click on Metadata to open the Submission and Publication Metadata window, edit the metadata, and click Save, the window does not close.  A notification message displays saying "Submission metadada saved" and the Save button greys out, but there is a scrolling wheel on the bottom right, suggesting something is still working.  If you try to make additional changes to the metadata you can't save them.  You have to close the window and open it again to do further editing.

Reported on the forum: https://forum.pkp.sfu.ca/t/ojs-3-1-1-4-submission-metadata-form-save-button/49121

**Comment by asmecher** [comment]
I think this is already filed here: https://github.com/pkp/pkp-lib/issues/4072#issuecomment-432740688

**Comment by bozana** [comment]
Can this issue then be closed @amandastevens?

**Comment by amandastevens** [comment]
Oh yes, I thought Alec had closed it already.
