### ISSUE TITLE
Missing files in default theme

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#4189]
A browser's JavaScript error console reports for OJS 3.1.x installations the same 3 missing files for the default theme (or derivatives of it):

/plugins/themes/default/js/lib/popper/popper.js.map
/plugins/themes/default/js/lib/bootstrap/dropdown.js.map 
/plugins/themes/default/js/lib/bootstrap/util.js.map

**Comment by NateWr** [comment]
Thanks @mpbraendle! These missing files are only used for development and won't effect the end-user in any way.

However, it'd still be good to either add them or remove the references to the source maps, so we're not generating unnecessary 404 requests to the server. :+1:
