### ISSUE TITLE
Statistics page broken after upgrade from 2.4.5 to 2.4.6

### ISSUE THREAD

**Issue by atremba** [pkp/pkp-lib#419]
After upgrade from 2.4.5 to 2.4.6 (by copying whole ojs-2.4.6 folder, copying config.inc.php from 2.4.5, upgrading database via web-interface)
the statistics page (under Journal Management -> Management Pages -> Stats & Reports ) appears to be broken.
Displayed error 
`DB Error: ERROR: syntax error at or near "WHERE" LINE 7: WHERE a2.article_id IS NULL AND ^`

Short lookup reveals that the problem connected with file `classes/journal/JournalStatisticsDAO.inc.php` 

If old 2.4.5 version of the file is used (directly copied into installed ojs 2.4.6), the statistic is displayed well.

Assumptions:
* either some bad changes made into `JournalStatisticsDAO.inc.php` in 2.4.6,
* either database upgrade went bad

**Comment by beghelli** [comment]
Hi Andrey,

Thanks for your help.

I don't think it's a database issue. I did that change and tested, it went fine. I tested the same page again and it's also working. But I am not sure that our automated tests were running this page to test it with postgreSQL. Maybe you're using it?

Cheers,
Bruno

**Comment by atremba** [comment]
Indeed, we use postgeSQL (version 9.3.6). 

But the problem seems to be with forgotten ON (...) part after INNER JOIN command.
I tried to correct it and made a pull request https://github.com/pkp/ojs/commit/7d31cf8613ec2e6adc71fcf68407b045d5121c95

but I still not sure if I'm doing it in a right way.

Please correct my actions if needed.

**Comment by marchitelli** [comment]
I am using Postgres and I confirm both the bug
`DB Error: ERROR: syntax error at or near "WHERE" LINE 7: WHERE a2.article_id IS NULL AND ^`
and that the proposed solution works.

**Comment by atremba** [comment]
Let's summarize current issue state here (from pull request pkp/ojs@7d31cf8 discussion):
interim solution for intended behaviour (`getFirstActivityDate($journalId)` function) is
`articles a CROSS JOIN users u`
(without ON (...) condition)

and a subquery would be better result (@beghelli, @ctgraham )

**Comment by ctgraham** [comment]
I think this is resolved by https://github.com/pkp/ojs/pull/655 for https://github.com/pkp/pkp-lib/issues/856.

**Comment by asmecher** [comment]
Thanks, @ctgraham.
