### ISSUE TITLE
remove reviewer assignments for declined articles

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#4198]
Thanks to all contributors of this Project. We are using ojs for our journal for 2 years. I have a request for future versions.

An article may be declined due to some reviewer reports or other reasons when there are other reviewers accepting to review. However, the reviewers may send reports for articles that are already been declined previously. There is no way to remove an assignment of a reviewer who have accepted to review previously.
System should give permisson to remove the assignments of reviewers accepting to review. This may be needed for other reasons, too.

Thank you for your attention in advance.

**Comment by asmecher** [comment]
@Baytan, what version of OJS are you using? (Please include this in your reports.)

**Comment by Baytan** [comment]
We are using ojs 3.1.1.4.

**Comment by asmecher** [comment]
@Baytan, I think our recommended practice is that you notify the reviewer that the review is cancelled, rather than revoking permission e.g. by denying access to declined submissions.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
