### ISSUE TITLE
[OJS] Mails sent via Cron have filepath rather than URL

### ISSUE THREAD

**Issue by garyross** [pkp/pkp-lib#4201]
When emails are sent out they have the filepath rather than the URL like this:

> Please log into the journal web site … is http://localhost/path/to/ojs/htdocs/tools/index.php?journal=JCJ

Note the 'localhost' written before the path. 

I have the correct base_url set in the OJS Configuration:

```
; The canonical URL to the OJS installation (excluding the trailing slash)
base_url = http://jcj.example.org
```

and the OJS Configuration in the Admin area shows:

```
base_url	http://jcj.example.org
base_url[index]	http://jcj.example.org
```

This is 3.1.1.0 running on Ubuntu 18.04.1 LTS PHP 7.1

This happens on mails sent out by the cron job ( scheduled_tasks = On )
0 * * * * php /path/to/ojs/tools/runScheduledTasks.php

but not on mails such as password reset that are sent through the website suggesting that it is a bug rather a settings issue.

**Comment by asmecher** [comment]
@garyross, I'd suggest posting questions like this on our support forum rather than the issue tracker -- but briefly, you might need to add an entry for `base_url[JCJ]` to your `config.inc.php`.

**Comment by asmecher** [comment]
@garyross, can you drop the link to the forum post here?

**Comment by garyross** [comment]
@asmecher Here goes:
https://forum.pkp.sfu.ca/t/emails-have-wrong-url-show-file-path-instead-possible-bug/49528

**Comment by asmecher** [comment]
@garyross, essentially generally OJS tries to use the URLs it gleans from the `$_SERVER` variable in the PHP environment. If it can't do that, it'll use the `base_url` (no suffix) setting. However, any `base_url[...]` settings (*with* the suffix) are considered "hard overrides" and will always be used preferentially.

If you're seeing `localhost` URLs used in contravention of `base_url` (no suffix) when no `base_url[...]` directives are specified, it probably means your CRON job is using the CGI PHP binary instead of the CLI one. I suspect specifying a hard path to a CLI PHP binary would fix it, as would specifying a full set of `base_url[...]` directives.

**Comment by garyross** [comment]
@asmecher 
Thanks for taking the time to reply. 


```
$ php --version 
PHP 7.1.18-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun 11 2018 14:22:30) ( NTS )
```

However, I'm not 100% sure that `php` in a `www-data` crontab would get the same path, so I've updated my Crontab to `/usr/bin/php` to ensure the cli version. 

`3 * * * *    /usr/bin/php /www/vhosts/ojs.jaltcall.org/htdocs/tools/runScheduledTasks.php`

and let you know if that fixes the issue. (Perhaps a [note in the docs would be helpful](https://pkp.sfu.ca/ojs/docs/userguide/2.3.3/systemAdministartionScheduledTasks.html)).

I wonder if there's any way I can test this to see what path my environment returns now rather than waiting on emails to be sent out.

**Comment by asmecher** [comment]
Off the top of my head, you could write up a quick PHP script to be kicked off by cron doing something like...
```
<?php file_put_contents('/tmp/tmp.txt', print_r($_SERVER,true));
```

**Comment by garyross** [comment]
Here's what I get when I run that command via Cron:

Doing with both the  full path `/usr/bin/php /home/gary/www-data-test.php` and the short path  `php /home/gary/www-data-test.php` gave the same results 

```
$ cat /tmp/tmp.txt 
Array
(
    [HOME] => /var/www
    [LC_CTYPE] => en_US.UTF-8
    [LOGNAME] => www-data
    [PATH] => /usr/bin:/bin
    [LANG] => en_US.UTF-8
    [SHELL] => /bin/sh
    [LC_ALL] => en_US.UTF-8
    [PWD] => /var/www
    [PHP_SELF] => /home/gary/www-data-test.php
    [SCRIPT_NAME] => /home/gary/www-data-test.php
    [SCRIPT_FILENAME] => /home/gary/www-data-test.php
    [PATH_TRANSLATED] => /home/gary/www-data-test.php
    [DOCUMENT_ROOT] => 
    [REQUEST_TIME_FLOAT] => 1541811661.228
    [REQUEST_TIME] => 1541811661
    [argv] => Array
        (
            [0] => /home/gary/www-data-test.php
        )

    [argc] => 1
)
```
