### ISSUE TITLE
Reviewers cannot access submission for review in OJS 3.0.2

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4206]
With latest back-ported fixes in OJS 3.0.2

Reviewers get a blank page when trying to access an assigned submission for review.

PHP Fatal  error:  Uncaught ArgumentCountError: Too few arguments to function PKPPageRouter::getRequestedOp(), 0 passed in pages/reviewer/ReviewerHandler.inc.php on line 48 and exactly 1 expected in lib/pkp/classes/core/PKPPageRouter.inc.php:107

**Comment by asmecher** [comment]
@mfelczak, this is a [backwards-incompatible change introduced with PHP7.1](http://php.net/manual/en/migration71.incompatible.php). Is an OJS upgrade possible? I'd recommend that as the best solution.

**Comment by mfelczak** [comment]
Thanks @asmecher -- unfortunately we have some hosted clients with extensive OJS 3.0.2 customizations who will only be upgrading once 3.2 is released, e.g. submission list customizations that are incompatible with OJS 3.1.1.

**Comment by mfelczak** [comment]
P.S. Does the fix here entail something other than adding the $request param to the PKPPageRouter::getRequestedOp() calls in pages/reviewer/ReviewerHandler.inc.php:48?

**Comment by bozana** [comment]
I think you could try that fix @mfelczak...

**Comment by mfelczak** [comment]
Hi @bozana, confirming that adding the $request param fixed the error. The affected install has been running PHP 7.1 with their OJS 3.0.2 from the beginning on a dedicated server, i.e. it looks like this issue was triggered by pulling-in the latest changes from ojs-stable-3_0_2.

**Comment by bozana** [comment]
OK, I can do the commit(s)... Thanks!!!

**Comment by bozana** [comment]
PR:
ojs-stable-3_0_2: https://github.com/pkp/ojs/pull/2172

**Comment by bozana** [comment]
merged, thus closing...
