### ISSUE TITLE
PKPTemplateManager::initialize() redundant variable

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4212]
This variable is never used: https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L352
Is the idea to assign `hasSystemNotifications` to the Smarty outside of `if` loops?

**Comment by asmecher** [comment]
Yup, I've removed the dead code -- thanks, @Vitaliy-1!
