### ISSUE TITLE
After thanking, reviewer decisions is not seen on Review page

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#4213]
Thanks to all contributors of this Project. We are using ojs (3.1.1.4) for our journal for 2 years. I have a request for future versions.
After thanking reviewers, the reviewer decision is not shown on the Review page. Seeing all reviewer decisions together was better for an editör to decide about article especially when conflicting decisions are present. I would be grateful if I can see the reviwer decisions after thanking them, as well.

Thank you for your attention in advance.

**Comment by bozana** [comment]
Hi @Baytan, when you open the arrow for that review, there is the action "Review Details". There you can see the reviewer recommendation. Is this what you are looking for?

**Comment by Baytan** [comment]
I may explained wrongly. After I confirm the reviewer report using "Review Details" button, the reviewer decision written beside reviewer name (like Revisions Required, Accept Submission) is lost. It was good to see the reviewer decision beside his/her name to understand the generel opinions about the submission. I do not like to confirm reviewer reports due to this. However, without confirming reviewer report I cannot send thank you mail. I hope I explained what I meant.

**Comment by Baytan** [comment]
As this is very annoying for me I want to explain it again. Before Confirming reviewer report the line for the reviewer looks like this
![1](https://user-images.githubusercontent.com/27674815/52519865-0ea3fc80-2c73-11e9-84f6-3ea2c0876f7a.jpg)

After confirm it looks like this
![2](https://user-images.githubusercontent.com/27674815/52519886-57f44c00-2c73-11e9-8703-6f2366d246c0.jpg)

But after thank you is clicked it looks like this
![3](https://user-images.githubusercontent.com/27674815/52519895-a1449b80-2c73-11e9-908f-2ad9d8fb0033.jpg)


the reviewer decision info is lost. Why it should be effected by thanking the reviewer. It is very convinient for the editör to see all decisions together. I think after thanking reviewer we should also able to see the decision. I will appriciate if it can be corrected. Thanks to everybody in this Project.

**Comment by Baytan** [comment]
As I wrote a new one. I close this.

**Comment by asmecher** [comment]
@Baytan, I assume you re talking about https://github.com/pkp/pkp-lib/issues/4554. Why have you re-filed this?

**Comment by Baytan** [comment]
> @Baytan, I assume you re talking about #4554. Why have you re-filed this?

I see that no one responded and I tihin no one noticed it. To draw attention I opened a new one and closed the old one.

**Comment by asmecher** [comment]
@Baytan, that clutters the issue list -- it would be better to e.g. just add a comment here asking for an update. We are a small team and get a lot of reports, so aren't often able to respond as quickly and fully as we'd like.

**Comment by Baytan** [comment]
To whom it may concern,

As participant of this communication, if I may, I want to express my opinion. This is certainly a bug for my sake. When there are many assigned reviewers (with and without submitted reports) and many reports present, it may get things significantly more difficult when you don’t see the reviewer opinions at once.

 

By this chance, thanks all the contributors of this great project.

 

Best regards.

 

Dr. Hayri Baytan Ozmen

Editor-in-Chief

Research on Engineering Structures and Materials

**Comment by asmecher** [comment]
Hi all -- to apply this change to OJS or OMP, apply either of the above commits in the `lib/pkp` subdirectory. (They are identical, just applied to different branches.)
