### ISSUE TITLE
[OJS] IssueEntrySubmissionReviewForm, missing parameter in execute hook call

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#4215]
Hi there,

as the issue title already tells, there is a missing parameter in the execute hook call in `IssueEntrySubmissionReviewForm`.

I will demonstrate the issue based on call stacks. The following call stack is working:

```
SubmissionSubmitStep3Form::execute($args, $request) 
PKPSubmissionSubmitStep3Form::execute($args, $request) 
SubmissionSubmitForm::execute($submission)  <- parameter changes to submission ...
Form::execute($submission)
HookRegistry::call('submissionsubmitstep3form::execute'), array($this, $submission, $returner)) <- submission is passed as second argument to hook
```

and now another call stack with correct behavior when using the issue entry review form:

```
IssueEntrySubmissionReviewForm::execute($request)
 -> parent::execute($request)
SubmissionMetadataViewForm::execute($request)
PKPSubmissionMetadataViewForm::execute($request)
Form::execute($submission)
HookRegistry::call('issueentrysubmissionreviewform::execute'), array($this, $submission, $returner)) <- submission is also passed as second argument to hook
```

but now the call stack with incorrect behavior as the submission parameter is missing:

```
IssueEntrySubmissionReviewForm::execute($request)
-> HookRegistry::call('issueentrysubmissionreviewform::execute', array($this)); <- hook is called without $submission parameter
```

So, a hook method will break when it is
- registered to `issueentrysubmissionreviewform::execute` and
- accesses the hook argument with index 1 (submission argument)

I fixed the hook call like

```
$submission = $this->getSubmission();
HookRegistry::call('issueentrysubmissionreviewform::execute', array($this, $submission));
```

Should r provide a PR?

So lonG
Danieö

**Comment by bozana** [comment]
@asmecher, I see you have added those ...form::execute hook calls in this commit: https://github.com/pkp/ojs/commit/2a5ad807ca1338f50d97ed9498a642cc4ebe80ef. That slightly differ from what we used to use, the parent::execute which then provides the hook for all parent forms, or?
Is this then just a special case, or what is our general concept?
Thanks!

**Comment by bozana** [comment]
merged, thus closing...

**Comment by asmecher** [comment]
@bozana, you're right, it's probably better to rely on `Form::execute`. I suppose I probably noticed that `PKPSectionForm::execute` didn't exist and removed the `parent::execute` call, forgetting about `Form::execute`. But the two approaches are equivalent, so no rush to standardize -- unless you have the itch :)

**Comment by bozana** [comment]
:+1:  No itching, just to know... Thanks!!!

**Comment by asmecher** [comment]
Agreed, the `parent::execute` call should be responsible for the hook. Go ahead, thanks!
