### ISSUE TITLE
Expiry date announcements editing not work

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4216]
Once expiry date field is set and save it is not possible to leave it blank. Even cleaning and saving it will keep last expiry date set.

Reproducing this issue:
 Settings > Announcements (tab)> Scroll down to announcements listing 
 

1. Edit one with expiry date  &  Save
3. Edit it again
4. Clear expiry date field & save
5. Re-open to check that the previous date remains.

**Comment by asmecher** [comment]
@israelcefrin, the attached patch (https://github.com/asmecher/pkp-lib/commit/e83fdc285dc74c1edef842d2dbed278a31a32229) should fix it. However, it's a little hacky and points to some bigger problems with date handling...
- The affects of changing the default formats
- Handling of empty date fields in other places
- Inadvertent/broken double-posting of date fields (see `textInput.tpl`)

@NateWr, has your rewrite done away with the announcements area of the setup forms? If so, I can commit this to `ojs-stable-3_1_1` and let your work fix it on `master`.

**Comment by NateWr** [comment]
The add/edit announcement forms are still using the old system. Only the announcement settings (enable/disable, # on homepage) have been converted.

(That'd be an easy change following on from the API/ListPanel work to replace announcements that Dmitris and I did during the sprint.)

**Comment by israelcefrin** [comment]
Thanks for the patch @asmecher , I applied and it is working fine.
Checking this announcement listing I realized that we don't have a "Expiry date" column in listing,is it worth to open an issue? Or is it covered in @NateWr / Dmitris API/listPanel work?

**Comment by NateWr** [comment]
> Checking this announcement listing I realized that we don't have a "Expiry date" column in listing,is it worth to open an issue? Or is it covered in @NateWr / Dmitris API/listPanel work?

Yeah our work covered this. Let's leave it be for now.

**Comment by israelcefrin** [comment]
Ok, thanks @NateWr and thanks again @asmecher .

**Comment by asmecher** [comment]
OK, thanks --

**Comment by asmecher** [comment]
OK, thanks -- I've committed the fix to `ojs-stable-3_1_1` and `omp-stable-3_1_1` branches, and will work more generally on fixes to date handling in the `master` branch. This will probably have some overlap with @NateWr's recent work, but nothing substantial.

**Comment by asmecher** [comment]
The above commits should additionally fix the `master` branch so that nonstandard date formats are properly working, in addition to empty dates, and the per-use-case kludges are removed.
