### ISSUE TITLE
[OMP] new user registration not working without reader role in DB

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4217]
Hi @asmecher and @NateWr , OMP allows to edit and remove roles, but when _reader_ role is removed from it, any attempt to register a new user will return a 500 error code from server.
Likewise, ticking the reviewer checkbox, error will persist, eventhough user is registered, but no role in system.

To reproduce this issue in OMP is required admin permission to remove _reader_ role and attempt to register a new user.

**Comment by NateWr** [comment]
Upon reflection, we should probably disable deletion of a user group of the `ROLE_ID_MANAGER` or `ROLE_ID_READER` role when no other user groups with that role exist. Maybe `ROLE_ID_AUTHOR` too? Though I can imagine the app technically functioning without it.

**Comment by ajnyga** [comment]
+1 for preventing deletion. A journal should always have at least one group with those permission levels.

Some journal may for example try to block new submissions by deleting the author role (but of course there should be other ways of handling that).

**Comment by asmecher** [comment]
@israelcefrin, do you have a stack trace for the problem? I think I may have already committed a fix that'll improve behavior when no `ROLE_ID_READER` roles exist, but can check.

As for other user groups, I think the `is_default` column could be helpful here? I'd advocate that the default user groups probably shouldn't be deletable at all.

**Comment by asmecher** [comment]
I suspect this was already resolved by https://github.com/pkp/pkp-lib/commit/1e281e31357e63ff2f35f195313430b950dea77e; a quick test would be helpful!

**Comment by NateWr** [comment]
Closing this as outdated. If you need help with a similar problem, please post in our [community support forum](https://forum.pkp.sfu.ca/c/questions/5).
