### ISSUE TITLE
Fix report generator character encoding problem in RTL languages

### ISSUE THREAD

**Issue by jamshidhashimi** [pkp/pkp-lib#4219]
Exported reports (.csv) in Arabic UI when opened in Excel shows rubbish characters. See: https://forum.pkp.sfu.ca/t/reports-shows-rubbish-characters-in-arabic-ui/49321

This issue similarly exists in Farsi UI as well.

**Comment by asmecher** [comment]
Looks good -- merged all 3, @jamshidhashimi. By convention it's best to include the issue number in the PR title, e.g. "`pkp/pkp-lib#4219 Add BOM (byte order mark) to fix UTF-8 in Excel`", but I see you linked them in the description, which works too. Thanks!

**Comment by jamshidhashimi** [comment]
Thank you @asmecher. I noticed the naming after submitting the PR. Will do so after this.
