### ISSUE TITLE
Enable Theme Plugins by Default

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#4226]
We've received feedback that editors and journal managers often don't understand or want to go near the plugins in OJS. Can we enable new theme plugins by default in new releases, to ensure they are available in the Themes dropdown menu on the Appearance page? That will make them much more discoverable by non-technical users.

**Comment by NateWr** [comment]
I think that we only ship the `default` theme. All others have to be installed. It might be worth having a UI/UX conversation about what we want to ship as part of the main OJS project.

**Comment by asmecher** [comment]
I think the plugins area being too scary is a legit criticism needing its own solution. A drastic reduction of the number of plugins there would be helpful, but it's been slow to achieve. (OJS 2.4.8 has >130 plugins included; OJS 3.1.1 has fiftysomething. But that's still too many.)

**Comment by stranack** [comment]
The reasoning for which plugins are enabled by default and which are not isn't clear. Until we figure out the long-term issue of plugin display, I'd like to argue for enabling all PKP-created themes by default in 3.2.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
