### ISSUE TITLE
Limit the number of revisions uploaded messages received by editors

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4228]
Editors receive an email every time a revision file is uploaded. This can mean several emails for one set of revisions.

This has been raised as part of related issues ([here](https://github.com/pkp/pkp-lib/issues/2665#issuecomment-435460969)).

There is some code which has not been merged due to issues with the tests. https://github.com/pkp/ojs/pull/2152#issuecomment-436995534. It would address this by checking whether the editor has been logged in and active since the last email was sent out, and only sending out a new email if they have been active.

**Comment by ajnyga** [comment]
The linked comment looks great "I give up, this is taking way too much time" 🤣 Sorry, got a bit tired with it. I will do another try tomorrow with a fresh master branch...

**Comment by NateWr** [comment]
No worries, we've all been there with the tests. :)

**Comment by ajnyga** [comment]
Just a disclaimer that I did not loose it again during the weekend, just did not have time to try again. Today probably...

**Comment by ajnyga** [comment]
and the tests failed again. This time because on npm dependencies, but I thought those are handled during the tests. If I now do npm install and try to push changes to the branch, there are no changes. 

Just want to point out again, that I am using tens of times more time to trying to make these tests work that doing actual coding. A clear guide how to do this would be wellcome.

**Comment by ajnyga** [comment]
or it is probably a larger problem with the build state? https://github.com/pkp/ojs ?

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/4423

Tests passed:
https://github.com/pkp/ojs/pull/2263

Merged and closing!

**Comment by ajnyga** [comment]
@NateWr 

This is a better version of the changes above. Tests passed.
OJS: https://github.com/pkp/ojs/pull/2264
pkp-lib: https://github.com/pkp/pkp-lib/pull/4425

The new logic is:

> If no prior notification exists OR if editor has logged in after the last revision upload OR the last upload and notification was sent more than a day ago, send a new notification

**Comment by NateWr** [comment]
:+1:

**Comment by asmecher** [comment]
@ajnyga, the tests can indeed be time-consuming to debug :P Let me know if I can walk you through part of this sometime!

**Comment by ajnyga** [comment]
sure, there are plenty of failed tests here, no idea why since I only changed one file: https://github.com/pkp/pkp-lib/issues/3340

**Comment by asmecher** [comment]
@ajnyga, https://travis-ci.org/pkp/ojs/builds/489693357 failed because the changes appear to break the installation form; it looks like the changes result in the DB being accessed before the install form has been submitted.

**Comment by ajnyga** [comment]
yeah, saw that. Just do not understand how this affects the installation: https://github.com/pkp/pkp-lib/pull/4441/files

**Comment by asmecher** [comment]
Ah: the version information is stored in the database. Adding code to fetch it in the template manager results in an attempt to access the DB before it's created, when the installation form is built.

To avoid this, you can put the version fetch code into a conditional:

    if (!defined('SESSION_DISABLE_INIT')) {
        ...
    }

This constant will be defined in situations where we can't trust that a DB/user session will exist, including on the install form.

**Comment by ajnyga** [comment]
ok, will do that tomorrow...

**Comment by fgnievinski** [comment]
How about if OJS offers a form with multiple `<input type="file">` fields?  Then all the files are upload at once and the editor would get a single notification for the whole file batch.

If the user later decides to replace uploaded files, that's almost a new revision, and the editor would get another email.

**Comment by asmecher** [comment]
@fgnievinski, something like that is eventually the plan, particularly in order to better support the batch upload of dependent files (e.g. images to go with an HTML galley).
