### ISSUE TITLE
Submission list won't display submission in review stage with no review round

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4231]
If a submission in the review stage does not have any round, it will not add some stage information that the submission list expects. This leads to a missing `files` prop which causes a JS error and prevents the submission from displaying. (See https://forum.pkp.sfu.ca/t/missing-not-showing-articles-after-upgrade-to-ojs-3-1/47909/6?u=natewr).

https://github.com/pkp/pkp-lib/blob/master/classes/services/PKPSubmissionService.inc.php#L777-L803

Although I don't know under what circumstances a submission will have no review round, the submissions list should handle that more gracefully.

**Comment by ctgraham** [comment]
The use case we have on this is reported as follows:
> The ones that are missing were submitted last year, went through an initial review, and then were delayed until the next issue since the authors wanted more time to work on the feedback they received.

**Comment by ctgraham** [comment]
@NateWr , I have the feeling I'll be cherry-picking this workaround into a bunch of new 3.1.2 installs.  Given parallels in:
https://github.com/pkp/pkp-lib/blob/65d0936cc884f8c176c07af7147304ad7bb8bb1b/classes/services/PKPSubmissionService.inc.php#L773-L776
and
https://github.com/pkp/pkp-lib/blob/65d0936cc884f8c176c07af7147304ad7bb8bb1b/classes/services/PKPSubmissionService.inc.php#L820-L822
I'm thinking maybe this isn't a temporary workaround, but just the actual expectation of the datastructure.   Should I PR this?

**Comment by NateWr** [comment]
Yes, can you PR that? 

Eventually I'd like to have a proper data model for stages and adhere to that but this seems like the most sensible solution for now.
