### ISSUE TITLE
Remove email from DOAJ export

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4236]
c.f. https://forum.pkp.sfu.ca/t/doaj-plugin-exports-author-email-addresses-data-security-issue/49869

DOAJ notes:
>PLEASE NOTE that DOAJ does not display or have any need for author email addresses. Publishers should not send email addresses to us in the XML. Recent restrictions on the use of personal data, as laid out by the GDPR, mean that it is your responsibility to ask authors' consent before you distribute their email addresses. DOAJ kindly requests that you DO NOT send any email addresses to us at all. Thank you.

https://doaj.org/publishers#upload

The code exporting email addresses in OJS is here:
https://github.com/pkp/ojs/blob/21e564b267ef3ed4094ad619f2f812a7e48fb7f2/plugins/importexport/doaj/filter/DOAJXmlFilter.inc.php#L208-L209
and here:
https://github.com/pkp/ojs/blob/21e564b267ef3ed4094ad619f2f812a7e48fb7f2/plugins/importexport/doaj/filter/DOAJJsonFilter.inc.php#L127-L128

**Comment by asmecher** [comment]
All 3 PRs merged, thanks, @ctgraham!
