### ISSUE TITLE
[OCS] Font Size sidebar block is blank

### ISSUE THREAD

**Issue by bricas** [pkp/pkp-lib#424]
It seems like at some point the block template for the font size changer was essentially removed (in 2.3 stable and dev branches):

https://github.com/pkp/ocs/blob/ocs-dev-2_3/plugins/blocks/fontSize/block.tpl

All that's left is a header.

The master branch version actually has some content, FYI.

**Comment by asmecher** [comment]
@bricas, have a look at https://github.com/pkp/pkp-lib/blob/ocs-dev-2_3/templates/common/header.tpl#L45 -- the sizer is attached via Javascript; all it needs is a <div> to hook into.

**Comment by bricas** [comment]
AH! Our output is actually blank, BUT, after further inspection, this is actually related to a change we just happened to make: we switched to ssl-only for our site, and now this fails:

	<script src="http://www.google.com/jsapi"></script>
	<script>
		google.load("jquery", "1");
		google.load("jqueryui", "1");
	</script>

because it's non-ssl.

I can patch our local templates, but should that be moved to protocol agnostic //www.google.com/jsapi urls?

**Comment by asmecher** [comment]
Yes, that's already been done for our other apps. See http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=6620 for something that could be easily adapted.

**Comment by bricas** [comment]
Right. A quick grep shows

    templates/paper/header.tpl
    lib/pkp/templates/common/header.tpl

as offending files. I've patched mine locally.

**Comment by asmecher** [comment]
Thanks, I've also committed those to the ojs-dev-2_3 branch.

**Comment by skalume** [comment]
> @bricas, have a look at https://github.com/pkp/pkp-lib/blob/ocs-dev-2_3/templates/common/header.tpl#L45 -- the sizer is attached via Javascript; all it needs is a div to hook into.

I used the JavaScript code on my localhost and it worked but when I moved to my work place server the sizer was still blank
