### ISSUE TITLE
Errors unclear when Plugin upload fails

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4243]
Method `PluginHelper::extractPlugin()` [takes](https://github.com/pkp/pkp-lib/blob/164758310831fcfac6931c1e6fc1b51f66ff0793/classes/plugins/PluginHelper.inc.php#L43) and [manipulates](https://github.com/pkp/pkp-lib/blob/164758310831fcfac6931c1e6fc1b51f66ff0793/classes/plugins/PluginHelper.inc.php#L66) a error string by reference, but this error string is unused by the caller `UploadPluginForm::execute()`, because it is simply [overwritten](https://github.com/pkp/pkp-lib/blob/164758310831fcfac6931c1e6fc1b51f66ff0793/controllers/grid/plugins/form/UploadPluginForm.inc.php#L102-L104).

`PluginHelper::extractPlugin()` also does not actually consider whether the `exec` of `tar` actually [succeeded](https://github.com/pkp/pkp-lib/blob/164758310831fcfac6931c1e6fc1b51f66ff0793/classes/plugins/PluginHelper.inc.php#L64).

As a result, the error returned to the user is almost always `manager.plugins.invalidPluginArchive`, which ([as currently translated](https://github.com/pkp/pkp-lib/blob/164758310831fcfac6931c1e6fc1b51f66ff0793/locale/en_US/manager.xml#L335)) doesn't reflect these error conditions.

To reproduce:
* Upload a .zip file containing  plugin filestructure in the "Upload A New Plugin" dialog

Expected result:
* Message indicating this is not a tar file and only tar files are supported

Actual result:
* The uploaded plugin archive does not contain a folder that corresponds to the plugin name.

To reproduce:
* Upload a valid plugin .tgz file in the "Upload A New Plugin" dialog, but without a tar executable specified in config.inc.php

Expected result:
* The tar command is not available. Please correctly configure it in your "config.inc.php".

Actual result:
* The uploaded plugin archive does not contain a folder that corresponds to the plugin name.

**Comment by asmecher** [comment]
Merged -- thanks, @ctgraham!

**Comment by asmecher** [comment]
Also cherry-picked to `ojs-stable-3_1_1`.
