### ISSUE TITLE
Reviewer information missing in selection grid when adding reviewer to round 2

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4245]
In OJS 3.1.1-4, when you open a second round of review and add reviewers, a reviewer selection list is presented, but next to every reviewer it says "Never assigned," even if the reviewer has been assigned to other submissions or was assigned to the previous round of the submission. 

![select reviewer for round 2](https://user-images.githubusercontent.com/35044512/48860816-5c0d7d80-ed98-11e8-8ddb-2092e09013a8.png)
.

**Comment by mcfarland-ubc-library** [comment]
Affecting our 3.1.1.4 as well.

**Comment by NateWr** [comment]
@amandastevens and @mcfarland-ubc-library, I know it's been a while, but can either of you determine whether it might be the same issue as https://github.com/pkp/pkp-lib/issues/4312? Were the reviewers with "Never assigned" just assigned on the same day?

**Comment by amandastevens** [comment]
I'm not 100% sure, but since I first learned of this bug from Open Academia and they confirmed that was the case for them, it's probably true.  When I tested it on another install, I would have assigned the reviewer the same day.

**Comment by NateWr** [comment]
Thanks @amandastevens. I've copied the labels over to #4312 and will close this issue in favor of that one (which more closely describes the problem).
