### ISSUE TITLE
References set to null

### ISSUE THREAD

**Issue by lennycarl** [pkp/pkp-lib#4248]
Already post this problem at:
https://forum.pkp.sfu.ca/t/ojs-3-1-1-4-submission-tab-set-references-to-null/49977

References will be set to NULL (submissions.citations) if metadata was saved through “Submission” tab.
Tested on clean 3.1.1.4.

**Comment by bozana** [comment]
@lennycarl, actually there should not be the references field in the Submission tab. Are you logged in as an editor?
Could you please double check if these changes are contained in your OJS code: 
https://github.com/pkp/pkp-lib/pull/3839/files and https://github.com/pkp/ojs/pull/2025/files ?
Else, could you maybe explain step by step what did you do, what do you see, etc. -- For me to be able to reproduce it...

**Comment by bozana** [comment]
Oh, I think I see...

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/4250
ojs ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/2173 (only submodule update)

**Comment by bozana** [comment]
@lennycarl, could you maybe apply these changes and test if now OK: https://github.com/pkp/pkp-lib/pull/4250/files ?

**Comment by bozana** [comment]
merged thus closing

**Comment by lennycarl** [comment]
Yes, this work.
Thank You!
