### ISSUE TITLE
Keywords form section lost focus

### ISSUE THREAD

**Issue by lennycarl** [pkp/pkp-lib#4249]
Already post this problem at:
https://forum.pkp.sfu.ca/t/ojs-3-1-1-4-keywords-focus-on-inner-elements/49984

If keywords localization fields was changed, keywords section start to act weird, if any input localization field focused, except main locale, such as delete symbol, keywords section just slide up.
Tested on clean 3.1.1.4.

**Comment by NateWr** [comment]
Closing this as outdated. If you need help with a similar problem, please post in our [community support forum](https://forum.pkp.sfu.ca/c/questions/5).
