### ISSUE TITLE
Adding reviewer affiliation to the reviewer report

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#4255]
Thanks to all contributors of this Project. We are using ojs (3.1.1.4) for our journal for 2 years. I have a request for future versions.

The reviewer reports that is provided by OJS system do not include the reviewer affiliation. However, we list the reviewers of our journals in our website with affiliation and country information. It will be very useful to us if the reviewer report includes the reviewer affiliation and country information, as well.

**Comment by bozana** [comment]
This is again part of and will come with this issue: https://github.com/pkp/pkp-lib/issues/2820. Thus closing...
