### ISSUE TITLE
[OJS] Cannot complete installation

### ISSUE THREAD

**Issue by hernandelafuente** [pkp/pkp-lib#4257]
Hello, I'm new in OJS. I'm trying to install it locally in my Mac (Yosemite 10.10.5) but i can't get progress in the installation page. After complete the form with the user name, pass, languages, data base, etc etc press the "Install Open Journal Systems"button but nothing happens, I returns to the top of the installation page again and again, with no message or alert indicating the problem.

I'm attaching some screen Shots with my OS system profile, the view of Xampp application Manager (showing all servers green lights), and the root where i placed ojs folder. 

I would be grateful if someone could guide me with this problem. I don't know if the problems is with my osx system or mysql database access.

![screen shot 2018-11-26 at 10 32 35 am](https://user-images.githubusercontent.com/42556565/49017971-e541fd00-f168-11e8-91ca-d08ea368c92d.png)
![screen shot 2018-11-26 at 10 31 33 am](https://user-images.githubusercontent.com/42556565/49017972-e541fd00-f168-11e8-9bf8-442059139d13.png)
![screen shot 2018-11-26 at 10 31 54 am](https://user-images.githubusercontent.com/42556565/49017973-e541fd00-f168-11e8-9e20-1d58f431a961.png)
![screen shot 2018-11-26 at 10 31 24 am](https://user-images.githubusercontent.com/42556565/49017974-e5da9380-f168-11e8-9b90-6968f40c574e.png)

**Comment by asmecher** [comment]
@hernandelafuente, can you post in our support forum at https://forum.pkp.sfu.ca/ rather than in this issue tracker? That's the best place to get general help.
