### ISSUE TITLE
Make page numbers part of Metadata

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#4260]
Right now, changing page numbers in published articles is hard to do. You must select the Schedule for Publication button on the Production stage. Could we consider making the page numbers part of the article metadata? This would, I believe, be easier for users to find.

**Comment by isgrim** [comment]
This would be nice for chapters in OMP as well, for collected works with several authors to create correct citations from the metadata.

**Comment by NateWr** [comment]
This is obsolete after the changes to publication workflow coming in v3.2. Page numbers can be edited until a publication is published, after which a new version must be created to change them, like all other publication data.
