### ISSUE TITLE
No user for some reviewer actions in a submission event log

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#4263]
With OJS 2.4 the log entries for reviewer actions have no user associated if the reviewer used the one-click access.

With one-click access the current user can not be extracted from the request object when the log entry is created.

**Comment by asmecher** [comment]
Many thanks, @ptrckb -- one comment on your [PR](https://github.com/pkp/ojs/pull/2197) needs attention. Otherwise, this looks great (and thanks for tackling the upgrade scripts; that's particularly thankless work).

**Comment by ptrckb** [comment]
Created pkp/ojs#2204 for fixing the event log after upgrade to OJS 3.x.

**Comment by asmecher** [comment]
Thanks, @ptrckb, I've merged this!
