### ISSUE TITLE
Reviewers do not have access to files uploaded in review discussions

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4266]
See https://forum.pkp.sfu.ca/t/ojs-3-the-current-role-does-not-have-access-to-this-operation/24614/41 for details.

**Comment by asmecher** [comment]
To fix this issue, apply any of the 3 above patches in the `lib/pkp` subdirectory. (The patches are identical, just applied to different branches.)

**Comment by NjaniLizwi** [comment]
I am sorry for cross-posting. Is this solution still relevant for OJS version 3.3.0.11? I have a user who gets an error when trying to open a document.

**Comment by asmecher** [comment]
@NjaniLizwi, no, this is not relevant to OJS 3.x. I'd suggest posting on the support forum with details -- https://forum.pkp.sfu.ca
