### ISSUE TITLE
[OJS] Required asterisk missing

### ISSUE THREAD

**Issue by GrazingScientist** [pkp/pkp-lib#4268]
Comparable to #909 , the asterisk for required fields in the metadata in the submission process is missing, although e.g. keywords were set as required.

I am running OJS 3.1.1-4.

**Comment by ViRuSTriNiTy** [comment]
The `required` attribute is missing in the `fbvFormSection` calls in `lib\pkp\templates\submission\submissionMetadataFormFields.tpl`. This would also require an additional style introduced in pull request [#4262](https://github.com/pkp/pkp-lib/pull/4262). Providing a PR for this issue should be easy, shall I provide one?

**Comment by asmecher** [comment]
Contributions are always welcome, @ViRuSTriNiTy!

**Comment by ViRuSTriNiTy** [comment]
PRs finished. Let me know if something is missing.

**Comment by GrazingScientist** [comment]
Wow! That was fast! o.O Awesome, @ViRuSTriNiTy !

**Comment by ViRuSTriNiTy** [comment]
@GrazingScientist Hehe, i couldn't sleep this night, so i thought, why not doing something productive :)

**Comment by asmecher** [comment]
Merged/cherry-picked, thanks, @ViRuSTriNiTy! Have more coffee :)
