### ISSUE TITLE
Bulk editing of email templates

### ISSUE THREAD

**Issue by felixgruender** [pkp/pkp-lib#427]
One requirement of our project contains bulk editing of email templates. 
That means it should be possible to export all email templates into an XML file.
After editing this file (e.g. by search/replace) the journal manager can upload it again in OJS (whereby the relevant database tables are updated).
As this issue is part of our project we are going to implement it ourselves.
Regards, Felix

**Comment by ctgraham** [comment]
How is this different than running a search-and-replace across locale/*/emailTemplates.xml and using the currently built in tools to reload the email templates?

**Comment by felixgruender** [comment]
1) I think locale/*/emailTemplates.xml should be left as it is - the original state of the email templates is useful if someone wants to "reset all templates" 
2) I suppose the "currently built in tools" you mentioned are tools for site admins - but it would be good to enable journal managers to tackle this issue.

**Comment by asmecher** [comment]
Merged, thanks!
