### ISSUE TITLE
HTML galley CSS stylesheet not applied in article view

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4276]
In OJS 3.1.1 when I upload a stylesheet for an HTML galley the CSS file is not included when accessing the article via the HTML Galley Viewer (styles are not applied to the article).

**Comment by asmecher** [comment]
Does the HTML refer to the CSS file by name?

**Comment by mfelczak** [comment]
It did not, once it was added the HTML galley the stylesheet was applied. Thanks @asmecher!
