### ISSUE TITLE
Permit lowercase X in ISSN journal field

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4281]
When adding/creating or editing a Journal, ISSN field allows 0000-000X but doesn't accept 0000-000x (lowercase **x**).
I've checked ISSN validator code and it seems that is not adjusted to handle this ISSN mask:
https://github.com/pkp/pkp-lib/blob/ojs-stable-3_1_1/classes/validation/ValidatorISSN.inc.php#L52

It is not critical, but it would be great if this field should be case insensitive, even though stores a uppercase format.

**Comment by NateWr** [comment]
Are we sure that a lowercase `x` is valid in an ISSN? I did a quick look and everywhere that mentions the check digit uses an uppercase `X`. Some of the resources ([1](http://www.bl.uk/bibliographic/issn.html), [2](https://en.wikipedia.org/wiki/International_Standard_Serial_Number)) explicitly mention an "uppercase X".

**Comment by israelcefrin** [comment]
You are right @NateWr , valid ISSN mask is uppercase `X`. I  think that a friendly message could be added with this instruction bellow the field, i.e: "Valid ISSN check digit, when a X, must be uppercase format", would be enough.

**Comment by asmecher** [comment]
I'm going to close this -- we haven't had requests for this in the wild, and the `x` is technically invalid.
