### ISSUE TITLE
OJS 3.1. Files uploaded to to discussion show up in Copyediting under Upload/Select files

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4282]
Hi,

OJS 3.1.1.2

Scenario:
- In Submission stage author uploads manuscript files
- Editor asks for new versions and author uploads those to a discussion
- move on to Review stage and editor selects Upload/Select Files from Review Files modal
- The files uploaded to the discussion show up under "Copyeding"

**Comment by asmecher** [comment]
@ajnyga, could you try/review this change? https://github.com/pkp/pkp-lib/pull/4351

**Comment by asmecher** [comment]
I went ahead and merged and cherry-picked this around (`ojs-stable-3_1_1`; `omp-stable-3_1_1`; `ojs-stable-3_1_2`; `omp-stable-3_1_2`; `master`)

**Comment by ajnyga** [comment]
hah, would not had the time to test before Thursday...

**Comment by asmecher** [comment]
Retrospective feedback is always welcome!

**Comment by ajnyga** [comment]
That's the best kind.
