### ISSUE TITLE
Reviewers should view their comments from previous rounds of review process

### ISSUE THREAD

**Issue by alireza08** [pkp/pkp-lib#4284]
Hi,
Reviewers should see their own reviews and comments from round 1 when completing round 2 of review. Currently, this is not possible and a reviewer has no idea about what his own comments was in a previous round of review process.
This is discussed before [in the forum.](https://forum.pkp.sfu.ca/t/reviews-of-previous-rounds/49730/6)
Best,

**Comment by alireza08** [comment]
Hello,
Does any one know a work around for this problem? currently, we are asking reviewers to take a note for themselves.
@asmecher , can you inform us whether this issue could be included in new version of OJS or not? 

Cheers,

**Comment by Potomac54** [comment]
pending resolution of the bug : a quick and relatively easy workaround may be implemented, with a plugin which purpose is to generate a summary of the discussions of all previous rounds, and put the results on a file which can be downloaded by all reviewers, in the current round of review process

all discussion messages are stored in the database, so it should be not very complicated to retrieve these messages and display them to the reviewers

**Comment by librariam** [comment]
Adding a related request from an editor to be able to select reviewer comments from previous rounds to be attached to a decision sent to the author. Currently only current round files are available to be attached.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
