### ISSUE TITLE
Issue management and submissions order misplacement

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4286]
Hi @NateWr 

If a section with 2 submissions is ordered before to appear over other section with just one submission, the latter section will fetch one from the former. It is just a visual issue, because metadata shows that submissions are correclty under their section.

I have worked around it re-ordering sections, bringing the "one submission only" section to the first position in sections ordering.

You may reproduce it via:
Dashboard > Issues > back Issue > "Edit" an issue

Note that you need to set a section with one submission and other with 2, and put this second one just above the first.

at-id: 1092

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this in the latest stable version, please post reproduction steps.
