### ISSUE TITLE
Should we remove "[]" from sent email subject line

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#4288]
We are using OJS 3.1.1.4 and thank all contributors of the Project. I have searched for this subject but not found a relevant one. So I open a new issue.

One of our editors was alerted, by some colleagues that are invited to review articles, that the invitation emails went directly to the spam box.  He checked and the same happens to him too. 
The technical director of his University told that the “problem”, perhaps is in the subject of the email (the journal abbreviation between brackets “[RESM]” enhances recognition as a spam). He also told me that publishers such as Elsevier, did it in the past but no longer identify their mails in this way to prevent recognition as spam.

So I want to submit this matter to your and all OJS users’ attention.

**Comment by Baytan** [comment]
I cannot find any setting for that. If there is I prefer to remove "[]" from subject line of the sent emails.

**Comment by asmecher** [comment]
@Baytan, this is the "acronym" setting on the masthead form; currently that's a required field, and it's hard-coded to be included in email templates in `lib/pkp/classes/mail/MailTemplate.inc.php` (look for `getLocalizedAcronym`). Do you have any information on prefixes like this generally being identified as spam? It's a fairly standard practice as far as I'm aware.

**Comment by Baytan** [comment]
@asmecher Thank you for your interest. I do not have information on prefixes like this generally being identified as spam. But I got the above discussion with one of our editors. And we had problems with our emails being recognized as spam. I think this may be one of the reasons. I prefer to change it just in case. Lack of brackets may not be a problem for us. thanks.

**Comment by Baytan** [comment]
I did it and it worked perfect. I do not know anything with php or what you use for OJS. I just know some C++ bu you guys are great for developing OJS and helping us to use it. many thanks :)

**Comment by Baytan** [comment]
If you want we can close this issue as it seem to be solved.

**Comment by asmecher** [comment]
Sure, @Baytan, sounds good. If you do have some general evidence that this causes emails to be marked spam, then we'd be interested in capturing that for a possible change in the software; otherwise you're welcome to maintain it as a local modification.
