### ISSUE TITLE
Announcements don't respect date_posted ("published") setting

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#429]
See http://forum.pkp.sfu.ca/t/published-field-under-announcements-doesnt-work

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/pkp-lib/pull/430
https://github.com/pkp/ojs/pull/461
Bruno, mind taking a quick look?

**Comment by beghelli** [comment]
I couldn't open the forum thread but I left some comments there.

**Comment by asmecher** [comment]
Merged!
