### ISSUE TITLE
Distinguish the user's URL field from the ORCID field

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4293]
Apparently users have been misunderstanding the ORCID and URL fields on the registration/profile forms as being related (e.g. expecting to enter the numeric part of the ID in the ORCID field, and the full ORCID URL in the URL field).

To avoid this confusion, distinguish the two fields.

A couple of quick ideas:
- Move one of the two, so they aren't adjacent
- Rename the "URL" field to "Homepage URL" to clarify its purpose

**Comment by alexxxmendonca** [comment]
This happens to our users quite often. I like the two suggestions and I think they could both be applied for an effective solution.

**Comment by asmecher** [comment]
Merged and cherry-picked to `stable-3_1_2`, thanks!
