### ISSUE TITLE
JournalManager/Author metadata edit error: "Please enter the references."

### ISSUE THREAD

**Issue by lennycarl** [pkp/pkp-lib#4295]
Greetings!
When user is trying to edit metadata on published article he will get this notification: "Please enter the references.", even if references is set, this problem can be bypassed if uncheck 'Author' role from user or uncheck 'Required' flag for 'References' in workflow settings.
Tested on 'clean' 3.1.1.4.
Is this a bug, role conflict or authors shouldn't be allowed to change metadata?

**Comment by bozana** [comment]
PRs:
pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/4296
ojs ojs-stable-3_1_1: (only submodule update)

pkp-lib omp-stable...
omp  omp-stable...: (only submodule update)

pkp-lib master:
ojs master: (only submodule update)
omp master: (only submodule update)

**Comment by bozana** [comment]
Thanks @lennycarl! Could you maybe test the changes: https://github.com/pkp/pkp-lib/pull/4296/files -- this should fix it...

**Comment by lennycarl** [comment]
@bozana, this fix doesn't help, still getting notification.

**Comment by bozana** [comment]
Hi @lennycarl, hmmm... strange... :thinking: 
You also have this fix, from earlier/another issue: https://github.com/pkp/pkp-lib/pull/4250/files, correct?
When the submission metadata modal is used, there should be a hidden form field metadataModal with the value=1. With the change above there should be no check for references in the case of metadataModal. The check should only exist at a new submission...
Hmmm...

**Comment by bozana** [comment]
I've just tested it on my local installation again and it works for me. I am using ojs-stable-3_1_1 branch, that has a few more fixes than the 3.1.1-4 release, but I think for this issue only those two commits/changes (s. above) are needed... Hmmm...
