### ISSUE TITLE
Uploading logo to customize theme - allowed file formats

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4305]
According to what has been mentioned in this [thread](https://forum.pkp.sfu.ca/t/ojs-3-cannot-upload-logo/28961/6), from the forum,  gif image format is not allowed to be uploaded in OJS3. 
Instead to allows it, I think that would be helpful if we could add a friendly tip and validation message to this task. 

Something like (bellow input field):
 "PNG and/or JPG formats allowed only, gif image are not allowed to upload". 
Also, when an user uploads a GIF, instead  "File extension error" it could  returns in red color "GIF images are not allowed".

![deepinscreenshot_select-area_20181214122347](https://user-images.githubusercontent.com/4992902/50009354-efa02b80-ff9d-11e8-9f24-94d951a3a3e4.png)

**Comment by asmecher** [comment]
This error message unfortunately comes from the plupload uploader that we use -- IMO the "right" fix would be for the upstream tool to use a more descriptive error message, though I'm not sure how willing they'd be to accept that proposal.

**Comment by asmecher** [comment]
(https://www.plupload.com/docs/v2/File-Filters)

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
