### ISSUE TITLE
Make consent statements less "Canadian" / more declarative

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#4307]
1) Change: 

> Yes, I would like to be contacted about this submission.

TO: 

> I agree to be contacted about this submission.

2) Change: 

> Yes, I would like to be contacted with requests to review submissions to this journal.

TO: 

> I agree to be contacted with requests to review submissions to this journal.

@NateWr / @ajnyga, any concerns with the above phrasing change? We've had this request from a client who had some editors who were confused by the vagueness of the original text. Alternatively we could use "consent to" instead of "agree to".

**Comment by ajnyga** [comment]
Sounds good to my non-native ear. I can see how that works better.

**Comment by ajnyga** [comment]
(also, I promise to use "more Canadian" and "less Canadian" from now on here in Github)

**Comment by jmacgreg** [comment]
Hi @NateWr, any chance you can have a quick review here? Probably mostly just to make sure I'm doing the whole PR process correctly (including tagging the commits with the bug ID, etc.). I'll have more to come later today, so I just want to make sure my procedure looks good. I can apply these to master + OMP as well.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
