### ISSUE TITLE
Privacy checkbox appears during submission even if no privacy statement exists

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4308]
If no privacy statement exists for a journal, the privacy checkbox is still presented during step 1 of the submission. The link in the checkbox label goes to a 404 page.

The checkbox should not appear if no privacy statement exists.

**Comment by NateWr** [comment]
@asmecher should I be looking into this in `ojs-stable-3_1_1` or in `stable-3_1_2` or `master`?

**Comment by asmecher** [comment]
If it's easy to do (or if it's resolving a missing piece of the back-porting), then all three. Otherwise, fall back to `stable-3_1_2` and `master`.

**Comment by NateWr** [comment]
Also caught a regression from #3594 here. :eyes: 

PRs:
https://github.com/pkp/pkp-lib/pull/4362
(backports coming)

Tests:
https://github.com/pkp/ojs/pull/2240

**Comment by asmecher** [comment]
Looks good, @NateWr -- please go ahead.

**Comment by NateWr** [comment]
Merged!
