### ISSUE TITLE
[OMP] bogus pagination on catalog-page if 1+ submission/form language

### ISSUE THREAD

**Issue by paflov** [pkp/pkp-lib#4309]
OMP 3.1.0.0

Look at PKPSubmissionService.inc.php, l. 7, function getSubmissionsMaxCount. Here a very complicated query is constructed to get the total numbers of items in catalog.
An item will be counted twice or even more often, if it has different titles in different languages.

But in CatalogHandler.inx.php, l. 102 (and 260) we find

```
$publishedMonographs = $submissionService->getSubmissions($context->getId(), $params);
$total = $submissionService->getSubmissionsMaxCount($context->getId(), $params);
```

In my case $total is 16 and count($publishedMonographs) is 10. So I have ten books but 6 of them have different (or omitted) titles in different languages, the other 4 have the same title in English and German.

The result is a bogus pagination in catalog.tpl template. It says " 1-10 of 16 Next ". If I click on next,
I get a empty page naturally, since there are no further items.

It's event worse. If I enable Spanish as a third language for submissions and forms, open and store one catalog entry there is is third setting named "title" in the table submission_settings" - so the complicated counting query above counts one item more. Even if I disable Spanish again! It was very hard to debug this, because Spanish was disabled, and it was not possible to change the Spanish title anymore.

PS my OMP is on Commit 2971ff0151e8dff1ec7af4aa35c1c3347046d591 (Jul 23 2018)

**Comment by NateWr** [comment]
Closing this as outdated. If you need help with a similar problem, please post in our [community support forum](https://forum.pkp.sfu.ca/c/questions/5).
