### ISSUE TITLE
Journal manager never gets their authored submissions in my submissions grid

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#431]
This happens because as they upload the submission as journal managers, they have no author assignment to the submission, removing the only way we identify now if a submission is authored or not by an user.

**Comment by asmecher** [comment]
Bruno, I'm tempted to call this "you get what you asked for". I thought of a few ways around it -- e.g. re-introducing a way to track the submitter outside of stage assignments -- but nothing clean and understandable. I think this might be OK behavior as it is.
