### ISSUE TITLE
Don't allow discussion messages to be edited after they are created

### ISSUE THREAD

**Issue by ezeferrero** [pkp/pkp-lib#4310]
**Describe the problem you would like to solve**
After a discussion is created, the user who created it can modify the message. This is the case for all messages, including replies. This allows a user to falsify the discussion record.

This is especially problematic because comments for the editor which were created during submission may be edited later. For example, an author who suggested referees or requested closed or open review could modify their request after review.

**Describe the solution you'd like**
After a discussion is created or a reply is posted, it should not be possible to edit the message.

**Who is asking for this feature?**
Journal managers concerned about the editorial record of the submission.

**Additional information**
The original request is below.

> By suggestion of Amanda Stevens, I'm hereby initiating this issue. My original concern was about the after-submission edition of "Comments for the Editor”, but it equally applies to any "discussion" in the editorial flow.
> 
> https://forum.pkp.sfu.ca/t/bug-comments-for-the-editor-fied-stays-modifiable-during-the-review-process/49956?u=ezeferrero
> (cut & pasted below)
> 
> let me report what I think may be a bug in OJS 3.1.1.4 (at least).
> We have noticed that the “Comments for the Editor” field at submission time, produces a “Discussion” entry that can be later on edited and modified by the author. This means that an author can submit a manuscript giving some information [e.g., suggested referees, desired review treatment (we offer both blind and open)] and then MODIFY it, for example, after a first review round. This is strange and can lead to problems.
> 
> I assume that the “Comments for the Editor” field is there to play the role of a front letter accompanying the submission and therefore shouldn’t be an editable field after submission.
> 
> [....]
> 
> At least in our journal, “Comments for the Editor” is the letter accompanying the manuscript where the authors make some choices. In particular, they have to choose among two different editorial treatments: open review or traditional review (blind). Further, they’re expected to suggest in there possible reviewers, or even to state people who shouldn’t be selected as reviewers for their manuscript for justified reasons.
> 
> Imagine if an author submit a manuscript asking for an open review treatment (it may end in the publication of reviewer comment together with the article), we start the edition process accordingly, then the author changes his/her mind and (not honestly) chooses to modify the statement of his/her selection.
> That’s a problem.
> Similarly, with reviewers suggestions or discouragements. Imagine if after review “Peter” criticizes an article, the authors decide to ADD to their front letter their will to avoid Peter as a reviewer because of their historical dispute on the topic (and make it looks as if the Editors had ignored their demand) .
> 
> So, it will be always clearer, less confusing and desirable to have a correspondence that cannot be modifiable. You can send as many messages as you want, but the record of the previous messages remains as sent. Currently, that doesn’t hold in the OJS system without a version control of Discussions.
> Actually, I have troubles trying to find an example in which allowing the edition of discussions entries is a plus (besides typo corrections after click).
> 
> Thanks for your concern.

**Comment by ajnyga** [comment]
I agree with the last comment: why would we allow authors/reviewers to edit any discussion entries? Correcting typos there is not a big issue and they can always post a new entry if needed.

Honestly I did not even notice that they actually can edit the entries so this was definitely not taken into account when the comments for editor feature was designed to work as a discussion thread.

**Comment by ajnyga** [comment]
Another option would be to allow edits for a specific amount of time for authors and editors. For example an hour or so. I think this is a common practice in software with commenting features.

**Comment by asmecher** [comment]
Also suggested: an "edited" flag.

**Comment by jyhein** [comment]
Based on above discussion I made changes so that assistants, authors and reviewers have 60 minutes to edit their own discussions. Add and update discussion windows show time left. The time limit is hard coded.
Is this ok?  Should admins be able to set the time limit? 
<img width="512" alt="add_discussion_window" src="https://user-images.githubusercontent.com/124268211/220349086-38d3f740-43e2-4596-b048-29ed883d5f7d.png">

**Comment by ezeferrero** [comment]
Thanks @jyhein  !
A time limit for the edition of discussions is a very welcomed modification to OJS. Thanks for taking care of this.
If you ask me as a Managing Editor, I'd set the time limit to 0 (zero) in our journal if I have the chance to chose it. Meaning, once it's sent, a message is perpetual and there's no room for ambiguities in editorial discussions. But I understand that a finite time window for editions can me useful to other journals/users.
Bests,
Ezequiel

**Comment by asmecher** [comment]
@jyhein, I'd be happy to review a pull request if you can send one in!

**Comment by asmecher** [comment]
@jyhein, I see a pull request for the OJS repo containing a submodule update (https://github.com/pkp/ojs/pull/3788); could you also open a PR against pkp-lib and drop a link here?

**Comment by jyhein** [comment]
Here: https://github.com/pkp/pkp-lib/pull/8695

**Comment by Vitaliy-1** [comment]
Thanks @jyhein!

The proposal and implementation look good to me. It's simple and, think, is the best what can be done as an intermediate solution. 

I'd suggest when refactoring (I hope soon) discussions, to revise the permissions to edit the message and the option to change this behaviour. If allow editing, I like the idea of an "edited" flag, ideally with an option to see the editing history. 

@asmecher, except missing quotes I think it's good to go.
