### ISSUE TITLE
[OJS] Licence badge not showing when referring https://creativecommons.org

### ISSUE THREAD

**Issue by GrazingScientist** [pkp/pkp-lib#4311]
Today I ran into the issue that an editor included the link https://creativecommons.org/licenses/by-sa/4.0/ into the licence field. This caused the article not to show the proper licence badge but only a text link. When I substituted the "https" by an "http" in the database, it worked.

Can you reproduce / fix this problem?

**Comment by asmecher** [comment]
@GrazingScientist, what version of OJS are you using?

**Comment by GrazingScientist** [comment]
@asmecher, the most current one. So OJS 3.1.1-4

**Comment by asmecher** [comment]
@GrazingScientist, you can adapt the list coded in `lib/pkp/classes/core/PKPApplication.inc.php` in the `getCCLicenseOptions` function. I'll leave this open for a more comprehensive fix, as existing data would need to be corrected.

**Comment by asmecher** [comment]
Proposal: change the list of licenses from `http` URLs to `https` in the code, and add an upgrade script to correct `http` to `https` for already-assigned licenses.

**Comment by GrazingScientist** [comment]
I will give this a try! Thanks for the insight!

**Comment by asmecher** [comment]
Also added upgrade scripts to convert `http` URLs to `https`.

**Comment by GrazingScientist** [comment]
You are amazing Sir! (I am sure you hear this daily! 😄 )

**Comment by asmecher** [comment]
Not every day. Much appreciated, @GrazingScientist!
