### ISSUE TITLE
Reviewer shown as "never assigned" when they have active review assignments

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4312]
**Describe the bug**
A reviewer may be shown as "never assigned" when they have active review assignments. This occurs when a reviewer's first invitation was on the same day.

**To Reproduce**
1. Go to a submission in the review stage.
2. Click on Add Reviewer
3. Create a new reviewer and assign them.
4. Go to another submission in the review stage.
5. Find the new reviewer and see they are "never assigned", even though they've just been assigned.

**What application are you using?**
OJS 3.3.0-x

**Additional information**
From @openacademia, https://github.com/pkp/pkp-lib/issues/4246#issuecomment-448314183:

> Sidenote: the current messages in the selection list is a little confusing. It says "Never assigned" when in fact a reviewer has active reviews, see screenshot.

<img width="960" alt="50173380-8e5abe00-02f7-11e9-8dff-57ea9d51f51f" src="https://user-images.githubusercontent.com/2306629/50212455-06b29500-0373-11e9-92b9-980b1abf71a9.png">

@openacademia, can you confirm whether the active reviews were assigned on the same day? Looking at the code, that's my best guess.

**Comment by NateWr** [comment]
Still a bug we want to solve, just confirming the source of it. :+1:

**Comment by librariam** [comment]
+1 from PKP|PS. Also the case with reviewers assigned on the same day.

**Comment by juliaflanders** [comment]
I have experienced this problem as well (see https://forum.pkp.sfu.ca/t/days-since-last-review-errors-in-ojs/72558) but it affects all reviewers, not just those recently assigned. When I view the list of reviewers, all of them show as "never assigned" whereas my colleague viewing the same list sees actual review assignments. Not sure whether this is the same bug or a related one.

**Comment by NateWr** [comment]
No, I don't think that it is the same issue.

**Comment by eczheng** [comment]
+1 one of our journals has also observed this bug.
