### ISSUE TITLE
Upgrading directly from ojs2.4 to OJS3.1.1-4 causing a menu navigation and static pages incompatibility 

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4314]
A Journal installation which has 12Gb of files and a reasonable number of Static Pages were showing issues to manage Menu itens after upgrade. 
Enable new itens or reorganize them was not possible. When I ran a upgrade first to OJS3.0.1 and, next , 3.1.1 this issue were not shown up e nenu got manageable again.
I can provide database and files from OJS2.4 version if it helps to reproduce this issue.

**Comment by asmecher** [comment]
@israelcefrin, can you describe in more detail what you were trying to do, and what wasn't working? Anything in the logs (either PHP error or browser console)?

**Comment by israelcefrin** [comment]
Hi @asmecher uupgrading from OJS2 => 3.1.1 ran smoothly. When I tried to edit, create, delete itens from menu, this function didn't work. Menu in frontend doesn't show what is set in backend (existing items don't appear).

Error_log file totally clear, this is console error msg:

 `Failed to load resource: the server responded with a status of 404 (Not Found)             CUR_Tutorial.png`

In home , console error log:
```Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/notosans/v7/o-0NIpQlx3QUlC5A4PNjXhFVZNyB.woff2
jmbe:1 
Slow network is detected. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0
jmbe:1 
Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/notosans/v7/o-0OIpQlx3QUlC5A4PNr4ARCQ_k.woff2```

this error msgs in admin panel:

```Failed to load resource: net::ERR_CONNECTION_RESET
jquery.validate.min.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
spectrum.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
pkp.min.js:236 Uncaught TypeError: b.validate is not a function
    at a.pkp.controllers.form.FormHandler [as constructor] (pkp.min.js:236)
    at a.pkp.classes.ObjectProxy.parent (pkp.min.js:118)
    at a.pkp.controllers.form.AjaxFormHandler [as constructor] (pkp.min.js:250)
    at a.pkp.classes.ObjectProxy.parent (pkp.min.js:118)
    at a.pkp.controllers.tab.settings.form.FileViewFormHandler [as constructor] (pkp.min.js:381)
    at a.pkp.classes.ObjectProxy.parent (pkp.min.js:118)
    at new a (pkp.min.js:116)
    at Function.a.pkp.classes.Helper.objectFactory (pkp.min.js:115)
    at HTMLFormElement.<anonymous> (pkp.min.js:442)
    at Function.each (jquery.min.js:2)
/index.php/jmbe/$$$call$$$/grid/notifications/task-notifications-grid/fetch-grid?_=1541522574687:1 Failed to load resource: net::ERR_CONNECTION_RESET
3pkp.min.js:121 Uncaught Error: There is no handler bound to this element!
    at Function.a.pkp.classes.Handler.getHandler (pkp.min.js:121)
    at HTMLFormElement.<anonymous> (pkp.min.js:209)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at a.pkp.controllers.TabHandler.tabsBeforeActivate (pkp.min.js:209)
    at HTMLDivElement.a.pkp.classes.Handler.handleEvent (pkp.min.js:123)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)
    at HTMLDivElement.<anonymous> (jquery.min.js:3)```

Also, It certainly has static pages, they have been migrated during upgrade.

**Comment by asmecher** [comment]
@defstat, would you be able to take a look at this?

**Comment by defstat** [comment]
Hi @israelcefrin !

From the error log, I don't see any message related to navigation menus (I think).
Could you provide some screenshots on that, and/or the state of the navigation_menu_* tables in the db for the journal that has the issue? 
Do you have the problem you describe when trying to edit every navigation menu item or just the ones that came from Static Pages? 
Do you see the titles of the menus?
Can you check if there is any javascript/PHP log related to "NavigationMenus" key word?

Thanks!!

**Comment by israelcefrin** [comment]
Hi @defstat 

Unfotunately I don't have this install upgrade b/c I re-ran and solve it doing a two steps process (ojs2.4=> 3.0.1 => 3.1.1-4) and it has succeeded. 

>> Do you have the problem you describe when trying to edit every navigation menu item or just the ones that came from Static Pages?

Every navigation item. In fact, didn't matter what I edited the menu didn't show my items order or enabled ones.

>> Do you see the titles of the menus?

Yes, all titles were shown up.

>>Can you check if there is any javascript/PHP log related to "NavigationMenus" key word?

Unfortunately as I said, I can't no more. 

I still have original DB and files (there is a final data sync to still happen). I can send you a link to download it if you like.

Israel

**Comment by defstat** [comment]
Hi @israelcefrin .

It seems that you encountered one of the first Navigation Menu's version bugs, that was related to the translation keys and the way that that version was handling them. In the case that the originated version of OJS had different languages installed from the targeted (upgrated) OJS version, or if a new language was introduced to the upgraded OJS version after the upgrade process, then the Navigation Menu Items translated values did not work properly. 
That was fixed at the 3.1.1.4 version, by applying the native translate mechanism of OJS to the Navigation menu Items, instead of relying on the upgrade method. 

Is the above description ringing any bells on the issue you are facing? After upgrading to 3.1.1.4 was the issue fixed?

**Comment by israelcefrin** [comment]
Hi @defstat , it sounds familiar to me for my first attempt to upgrade. On my last (successful) attempt I used OJS 3.0.1 then OJS 3.1.1-4 and issue didn't show up anymore.

Cheers!

**Comment by defstat** [comment]
Hi @israelcefrin! Should I close that?

**Comment by israelcefrin** [comment]
Hi, yes, go for it!
Best,

--
Israel Cefrin





Em seg, 11 de fev de 2019 às 15:08, Dimitris Efstathiou <
notifications@github.com> escreveu:
