### ISSUE TITLE
Blocks remain in the appearance menu despite being deactivated

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4318]
Tested with OJS 3.1.1-1, 3.1.1-4 and master branch (not most recent). To reproduce: deactivate block plugins (developed by, information block, language toggle block etc.), go to the appearance form, block still can be moved to the sidebar and are visible on the front-end.

Deactivation triggers JS error in the console, like: 
```
Uncaught Error: Row with id subscriptionblockplugin not found!
    at a.pkp.controllers.grid.GridHandler.resequenceRows (pkp.min.js:271)
    at a.pkp.controllers.grid.GridHandler.replaceElementResponseHandler (pkp.min.js:279)
    at Object.success (pkp.min.js:123)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.b (jquery.min.js:4)
```
This error is not block plugins specific.
Nothing special in the PHP error log.

**Comment by asmecher** [comment]
@Vitaliy-1, I think this is intentional. Moving the plugin off the sidebar in the Appearance form is equivalent to disabling the plugin in the Plugins list. Moving it back onto the sidebar is equivalent to enabling it.

**Comment by Vitaliy-1** [comment]
My concern here is that the blocks are present despite plugins deactivation and this behavior is not consistent as blocks from generic plugins like Custom Block Manager and Web Feed Plugin disappear from the appearance form after deactivation. But this shouldn't harm in any way.

**Comment by asmecher** [comment]
The distinction is that you're disabling the custom block *manager* plugin, not the custom blocks it creates. Likewise with the web feed plugin, which offers more than just the sidebar block -- even if the block is disabled/hidden, then web feeds are still available by URL (making it possible to add links in other places, rather than only the sidebar).

**Comment by Vitaliy-1** [comment]
OK. Closing then.
