### ISSUE TITLE
Simplify journal defaults

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#432]
Two areas where the installed defaults on journal creation are too complex...
- "Genres" (submission file types): https://github.com/pkp/ojs/blob/master/registry/genres.xml and https://github.com/pkp/omp/blob/master/registry/genres.xml
- User groups: https://github.com/pkp/ojs/blob/master/registry/userGroups.xml and https://github.com/pkp/omp/blob/master/registry/userGroups.xml

Both of these currently include a comprehensive set of defaults which could be trimmed down to size by deleting the extras, but I think that'll look too scary for most users. On the flip side, if we leave the defaults mostly empty, then users won't know what a "recommended" set would look like.

My suggestion: in the journal setup wizard, allow users to check off which of the defaults they'd like. Perhaps even suggest a default set that's already checked when you get there.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
