### ISSUE TITLE
[OJS] Bad placement of error messages for check-boxes

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#4320]
Hi there,

as the title already points out, there is bad placement of error messages for check-boxes. The error text is displayed right between the check-box itself and the text associated to the check-box:

![image](https://user-images.githubusercontent.com/12170676/50347407-c2bbbd80-0535-11e9-9170-340ee101c57c.png)

Imho the error message should be displayed below the text like

![image](https://user-images.githubusercontent.com/12170676/50347472-f5fe4c80-0535-11e9-9406-8767ad27e32b.png)

I'm going to provide a PR.

So lonG

**Comment by NateWr** [comment]
Merged! :+1:
