### ISSUE TITLE
Add Smarty shim functions for theme compatibility

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4323]
In issue #3242 we moved to Smarty 3, which includes a lot of function name changes (generally to move from `underscored_function_names` to `lowerCamelCase`). For compatibility with plugins and code (e.g. themes) that used the Smarty 2 functions, add shim functions (with deprecation warnings).

**Comment by Vitaliy-1** [comment]
@asmecher, I've noticed that the files path assigned to the Smarty through `PKPTemplateResource` and `PKPTemplateManager` has changed from like `plugins/blocks/languageToggle/block.tpl` to `plugins/blocks/languageToggle/templates/block.tpl`. Have you considered to add backward compatibility? 2 additional lines to the `Plugins::_overridePluginTemplates()` should work. I can make a pull request.

**Comment by asmecher** [comment]
@Vitaliy-1, a PR for this would be welcome!

**Comment by asmecher** [comment]
@Vitaliy-1, assigning this to you -- I've committed the shim functions already, so it's just the backward-compatibility addition you mentioned [above](https://github.com/pkp/pkp-lib/issues/4323#issuecomment-449988204).

**Comment by Vitaliy-1** [comment]
@asmecher 
PR: https://github.com/pkp/pkp-lib/pull/4371
Basically, I'm not sure if there is a need to additionally look up by the old path, but if someone forgot to move templates accordingly with a new path, it should work.

**Comment by NateWr** [comment]
@asmecher I've got new PRs for this drawing on @Vitaliy-1's work and implementing [your recommendation](https://github.com/pkp/pkp-lib/pull/4371#issuecomment-455611382). Can you review and merge when you get a chance?

PRs:
https://github.com/pkp/pkp-lib/pull/4407 (master)
https://github.com/pkp/pkp-lib/pull/4408 (3.1.2)

**Comment by asmecher** [comment]
@NateWr, looks good, but the warning message needs updating!

**Comment by NateWr** [comment]
Woops! Obviously not paying enough attention! I've fixed and merged. :+1:
