### ISSUE TITLE
NotificationHandler, wrong handling of fadeOut callback causes unbindPartial exception

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#4330]
Hi there,

as part of my investigation of issue #4072 i found out that there is also an error in the `NotificationHandler` which causes and exception in the browser console due to wrong callback handling:

1) The callback function is called directly due to the presence of `()` instead of passing it as reference parameter to the `fadeOut()` method, see https://github.com/pkp/pkp-lib/blob/master/js/controllers/NotificationHandler.js#L302

2) When the callback function gets called `this` is refering to the notification element hence `this.unbindPartial()` fails as this is not referring to the `NotificationHandler` anymore. It can be fixed like so

		var self = this; // remember "this" reference for later use in close

		var removeNotification = function() {
			var $notification = $(this);
			self.unbindPartial($notification);
			$notification.remove();
		};

The exception can be reproduced by executing the steps mentioned in comment https://github.com/pkp/pkp-lib/issues/4072#issuecomment-449591952

I will provide a PR.

So lonG

**Comment by asmecher** [comment]
Thanks, @ViRuSTriNiTy -- I'll bet that was fun to track down.
