### ISSUE TITLE
[OJS] Section drop down is displayed with multiple required asterisks

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#4332]
Hi there,

the section drop down is displayed with multiple required asterisks:

![image](https://user-images.githubusercontent.com/12170676/50385194-83c26f00-06d1-11e9-902b-734173f803ce.png)

This is a minor regression caused by https://github.com/ViRuSTriNiTy/pkp-lib/commit/f5be8f975009246980b4844f90b76e0d5319ae6e added as PR of issue #4268. This commit ensures that an asterisk is displayed for each section having the attribute `required` set to `true`.

Now, the template `templates/submission/form/section.tpl` contains a `fbvFormSection` tag with attribute `required=true` which causes a display of an asterisk. So far so good but unfortunately the `{fbvElement}` tag that follows also has an attribute `required=true` which is passed in consequent calls down to `subLabel.tpl` witch then renders an asterisk. Removing the asterisk from `subLabel.tpl` is not an option as this would remove the asterisks from the user forms for example. 

So the only option is to ensure that `{fbvFormSection}` does not render an asterisk by removing the required attribute which results in

![image](https://user-images.githubusercontent.com/12170676/50385278-74dcbc00-06d3-11e9-8de2-753d4feec9bf.png)

This would then conform to forms like the aforementioned user form where an asterisk is displayed by the label instead of the section:

![image](https://user-images.githubusercontent.com/12170676/50385281-8c1ba980-06d3-11e9-9f9d-2c971fdfa4fa.png)

I will provide a PR.

So lonG

**Comment by asmecher** [comment]
No harm, no foul -- thanks, @ViRuSTriNiTy!
