### ISSUE TITLE
ojs2: 404 Not Found error

### ISSUE THREAD

**Issue by mehrozrana1** [pkp/pkp-lib#4333]
[23-Dec-2018 06:34:28 America/New_York] ojs2: 404 Not Found
[23-Dec-2018 06:39:41 America/New_York] ojs2 has produced an error
  Message: WARNING: unlink(/home/jhidtcpq/public_html/cache/fc-pluginSettings-1-timedviewplugin.php): No such file or directory
  In file: /home/jhidtcpq/public_html/lib/pkp/classes/cache/FileCache.inc.php
  At line: 56
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.39
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 10.1.37-MariaDB-cll-lve

**Comment by asmecher** [comment]
@mehrozrana1, this is an occasional race condition in the file caching code. It's cosmetic, i.e. it's just an occasional error log message, but won't actually interfere with the operation of your install. It'll be resolved as part of https://github.com/pkp/pkp-lib/issues/3304. I'll make a note there, and close this issue.

**Comment by kallewesterling** [comment]
This was still happening on an OJS install that I manage. Tried updating to the latest stable version just now, and will try to remember to report back here in case it keeps happening @asmecher.

**Comment by WitsDeveloper** [comment]
Still getting this issue on OJS 3.3.0-17

**Comment by asmecher** [comment]
@WitsDeveloper, the logging of 404s in the PHP error log is expected behaviour until we merge [#10027](https://github.com/pkp/pkp-lib/issues/10027), probably for OJS/OMP/OPS 3.5.
