### ISSUE TITLE
[OJS 3.1.1.4] Some translations missing (submission stage)

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#4335]
https://forum.pkp.sfu.ca/t/ojs-3-1-0-1-3-1-1-4-some-translations-missing/49722

Hi! After upgrading to 3.1.1.4 some translations in the Submission form are missing (Russian locale). 
Those are:
##submission.submit.availableUserGroups##
##submission.submit.userGroupDescriptionManagers##
##user.register.form.privacyConsent##

@ppv1979, who did the translation, says it should still be there. So it might be something wrong in the code and it may affect some other locales.

**Comment by mtub** [comment]
Hi @Ph-We, all of the keys you have mentioned are part of the Russian translation of OJS in both the stable branch (`stable_3_1_2`) and in the `master` branch. The translations should be part of your installation even when you install from the git repository. Could you check if your locale files are the same as the ones on GitHub?

**Comment by Ph-We** [comment]
Hi @mtub, thank you! We use only the released packages. Those keys seems to have disappeared from many translations in `sumbission.xml` in the 3.1.1.4 release:
![capture1](https://user-images.githubusercontent.com/22288161/52396844-56385600-2ac4-11e9-95e0-f7b8b8347012.PNG)

Thus, the `submission.submit.availableUserGroups` is **only** present in the following locales:
![capture2](https://user-images.githubusercontent.com/22288161/52396837-4e78b180-2ac4-11e9-93d7-91dd54c8721f.PNG)

It is strange that now they are reappeared again in the `stable_3_1_2`. The same happened with some keys in `user.xml`. I think it is worth investigating.

**Comment by mtub** [comment]
Those lines have been added last year to the `master` branch. They have been introduced (to the English locale) ~10 months ago in this commit: https://github.com/pkp/pkp-lib/commit/e6f96344a4afaf960b5f30d9e70d61a47b293f49. The new stable release (now maintained in `stable-3_1_2`) has been built from the `master` branch. Apparently, the ru_RU locale update to the master branch has never been ported/cherry-picked to the previous stable branch (`ojs-stable-3_1_1`).

I don't think the translations "disappeared" from your installation, they were probably never a part of it. If you continue to run OJS 3.1.1, you could copy the lines from the translation file in OJS 3.1.2.

**Comment by Ph-We** [comment]
Dear @mtub, thank you so much for this clarification.  It was my memory, which played me a trick, I was 100% sure I had already seen those keys translated earlier. 
The issue may be closed then. Sorry for bothering you.
