### ISSUE TITLE
Submissions can be uploaded without article files

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#4336]
We are using OJS 3.1.1.4. When I examine a submission, I see that it is uploaded without any doc or pdf file including the article. I had to ask it with email. It would be better if the system checks whether a document file (doc, or pdf) is included in the submission.
Thanks to the contributors of this great Project and happy new year to all.

**Comment by NateWr** [comment]
Another issue has been filed with more details about this request. Please follow https://github.com/pkp/pkp-lib/issues/6241.
