### ISSUE TITLE
Unable to access note files after upgrade

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#4339]
After upgrading an OJS 2.4 installation to 3.1.1, the 'Notes' tab of the 'Editorial History' does not have links to files attached to the old notes.

It seems this has been already reported (#1932) and fixed (8170fa2b5664afc06a50ad251e65401719c4793f) but then mostly lost during #2163 (specifically 6027981071e1c1c53a4b2d9cc83868bd8167b09c).

When I try to reintroduce a `DownloadFileLinkAction` as a template variable on these notes, the link fails with the message:
> The current role does not have access to this operation

Files of notes are not attached to a particular workflow stage. But the file access policy requires one or the access is denied.

**Comment by asmecher** [comment]
@ptrckb, would you mind attaching a patch for the code change to re-add `DownloadFileLinkAction`?

**Comment by ptrckb** [comment]
@asmecher This [patch for pkp-lib](https://github.com/pkp/pkp-lib/files/2817557/notes.txt) re-adds the links to the notes in Editorial History.

And they do work with pkp-lib up until fd816017658e0fd7f5abcaca9f3e84dcad4e14ac (ojs pkp/ojs@73a8f07027b74ef1ce86faab4110c533bfef3c20). After that they fail with the message:
> The current role does not have access to this operation.

You can create a dummy note file on a recent installation with:
```sql
INSERT INTO submission_files (submission_id,original_file_name,assoc_type,assoc_id,revision,file_type,file_size,file_stage,date_uploaded,date_modified) VALUES (<SUBMISSIONID>, 'myfile', '520', <NOTEID>,1,'text/plain',1,3,'2019-1-01','2019-01-01');
```
after replacing `<SUBMISSIONID>` and `<NOTEID>`.

**Comment by NateWr** [comment]
Closing this as outdated. If you need help with a similar problem, please post in our [community support forum](https://forum.pkp.sfu.ca/c/questions/5).
