### ISSUE TITLE
quell array/variable warning in template

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#4341]
https://github.com/pkp/pkp-lib/blob/ab639aff793b535f72c43b9eccef7d6a0ecdfcd7/templates/header/usernav.tpl#L89

This line should look like:

`{if isset($supportedLocales) && $supportedLocales|@count}`

to quell a warning during a new installation.  The variable isn't set at this point in the user navigation.

**Comment by asmecher** [comment]
Thanks, @jnugent -- mind opening a PR?

**Comment by jnugent** [comment]
Allow me a moment to remember how :)

**Comment by asmecher** [comment]
Merged -- thanks, @jnugent!
