### ISSUE TITLE
[OJS] The license url should be validated

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4342]
Hi,

When an editor chooses Schedule for publication she can add a license url for the article. However, the url is not validated at all. This means that an editor can enter any text to the field. If the journal uses Crossref DOIs, this will lead into a validation error during DOI registration (`Element '{http://www.crossref.org/AccessIndicators.xsd}license_ref': [facet 'pattern'] The value 'THE VALUE GIVEN TO THE FIELD' is not accepted by the pattern '([hH][tT][tT][pP]|[hH][tT][tT][pP][sS]|[fF][tT][pP])://.*'.`)

Suggestion: add at least a simple validator that makes sure the data entered there is an url.

**Comment by jamshidhashimi** [comment]
[Here](https://github.com/pkp/ojs/blob/60bc4c39ceb6279a891070a133139378f807053e/controllers/tab/issueEntry/form/IssueEntryPublicationMetadataForm.inc.php#L55) the URL is getting validated. In the form, I entered a non-url text in `License URL` field and I got validation error. Am I missing something? @ajnyga

**Comment by ajnyga** [comment]
ok, thanks. Somehow an unvalidated value had been added there. Not sure then how.

**Comment by asmecher** [comment]
Yup, looks like this is a non-issue.

**Comment by ajnyga** [comment]
Not in quicksubmit it seems: https://github.com/pkp/quickSubmit/blob/master/QuickSubmitForm.inc.php

I will test that later today

**Comment by asmecher** [comment]
Thanks, @ajnyga -- merged (and created an `ojs-stable-3_1_2` branch with this as well).
