### ISSUE TITLE
Declined submissions not moved to archive

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4345]
In the current `master` branch, submissions that are declined are not moved to the author's or editor's archived list and do not show their declined status in the My Queue submissions list.

Declined submissions should appear in the archived submissions lists and indicate their declined status.

This comment, https://github.com/pkp/pkp-lib/issues/3386#issuecomment-399986066, also highlights that when declined in the submission stage there is no indication on the workflow.

Related to but distinct from https://github.com/pkp/pkp-lib/issues/3339 and https://github.com/pkp/pkp-lib/issues/3386. I think this is a more critical problem and should be scheduled against the next maintenance release.

**Comment by asmecher** [comment]
This was as simple as a `$submission->setSomeProperty(...)` without the attendant `$submissionDao->updateObject($submission)`. The attached patches add the missing `updateObject` call, and archive submissions whose last decision was a decline but are still `STATUS_QUEUED`.

PRs:
- https://github.com/pkp/pkp-lib/pull/4374
- https://github.com/pkp/ojs/pull/2245
- https://github.com/pkp/omp/pull/620

**Comment by asmecher** [comment]
@NateWr, would you mind taking a look? Thanks!

**Comment by NateWr** [comment]
Looks good! Go ahead. :+1:

**Comment by asmecher** [comment]
Merged, thanks!
