### ISSUE TITLE
Crossref deposit status check doesn't make sense

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4350]
In 3.x:

https://github.com/pkp/ojs/blob/1334c517d83cb825aaf2e3ea5f69494a96b24ea4/plugins/importexport/crossref/CrossrefInfoSender.inc.php#L129-L140

In 2.x:

https://github.com/pkp/ojs/blob/e09d8c61c226a04cad41effe21a01f88b2fb580d/plugins/importexport/crossref/CrossrefInfoSender.inc.php#L72-L84

Shouldn't the first check of `$currentStatus = $article->getData($plugin->getDepositStatusSettingName());` come *before* `$plugin->updateDepositStatus(....);`?

There is nothing to change the status between that and the second call of `$newStatus = $article->getData($plugin->getDepositStatusSettingName());`

**Comment by ctgraham** [comment]
Based on 2.4.x code, the intended logic appears to be:

1. Get the status as currently recorded in OJS
2. Update the status from Crossref
3. If there is no updated status, queue for registration
4. If the updated status is now "failed" but wasn't "failed" before, notify Manager

**Comment by ctgraham** [comment]
@bozana , can you review this interpretation?

**Comment by ajnyga** [comment]
(I think Bozana noticed the same thing earlier today, see https://forum.pkp.sfu.ca/t/ojs-3-0-2-crossref-xml-export-plugin-status-not-refreshed-properly/32874/21)

**Comment by ctgraham** [comment]
Serendipity.  Nice spotting, @ajnyga.  I haven't been trolling the forum today as I've been refreshing all of our metadata with Crossref.

**Comment by bozana** [comment]
everything merged, thus closing...
