### ISSUE TITLE
Archived articles can be submitted for DOI assignment

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4366]
# Steps to reproduce:
- Configure Crossref plugin with automatic registration
- Schedule an article against an issue
- Archive the article
- Run the Crossref plugin cron export

# Expected result
- Article is not exported for registration

# Actual result
- Article is exported for registration

# Cause
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/plugins/importexport/crossref/CrossrefInfoSender.inc.php#L59
calls
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/plugins/importexport/datacite/classes/DOIExportPlugin.inc.php#L1185
which does not filter archived articles:
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/classes/article/PublishedArticleDAO.inc.php#L460-L484

Secondary check
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/plugins/importexport/crossref/CrossrefInfoSender.inc.php#L63
calls
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/plugins/importexport/crossref/CrossRefExportPlugin.inc.php#L277-L279
calls
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/plugins/importexport/datacite/classes/DOIExportPlugin.inc.php#L766
and nothing checks the article status.

Also
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/plugins/importexport/crossref/CrossRefExportPlugin.inc.php#L219
filters to exclude archived articles
but
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/plugins/importexport/crossref/CrossRefExportPlugin.inc.php#L208
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/plugins/importexport/crossref/CrossRefExportPlugin.inc.php#L216
do not.

This is "caught" by:
https://github.com/pkp/ojs/blob/82dbd165a4c4c6158bf5154c357fdc8fb928bd94/plugins/importexport/crossref/CrossRefExportPlugin.inc.php#L230-L236
But causes the pagination counts in the UI to diverge across statuses.

This does not occur in 3.x because of `PublishedArticle::getExportable()`:
https://github.com/pkp/ojs/blob/4c969dbd45bb7aa25de881a49afb8de74d8692fe/classes/article/PublishedArticleDAO.inc.php#L773

**Comment by ctgraham** [comment]
@asmecher, What do you think of this one: https://github.com/pkp/ojs/pull/2244 ?

Certainly only one pull or the other required, but I think both stand on their own.

N.b.: I wonder if adding the `<> STATUS_ARCHIVED` filter to other getters may have the unintended consequence of breaking access to articles with inconsistent data (e.g. assigned to an issue, but archived).

**Comment by asmecher** [comment]
> @asmecher, What do you think of this one: pkp/ojs#2244 ?
> Certainly only one pull or the other required, but I think both stand on their own.

I've assigned @bozana to review that one -- she generally takes care of the CrossRef/DOI stuff. (I merged this one because it was trivial, and I know the DAO code well.)

> N.b.: I wonder if adding the <> STATUS_ARCHIVED filter to other getters may have the unintended consequence of breaking access to articles with inconsistent data (e.g. assigned to an issue, but archived).

That is possible -- but I think the risk is low. The `a.status` check already existed in several getters in `PublishedArticleDAO`, so I'd expect articles that were both `STATUS_ARCHIVED` and `i.published` would have been behaving inconsistently already. I haven't heard of that happening.

**Comment by bozana** [comment]
Can this issue be closed?

**Comment by ctgraham** [comment]
Yes, all merged.
