### ISSUE TITLE
OJS error 301 Moved Permanently (Deposit was not successful! The DOAJ API returned an error: '1

### ISSUE THREAD

**Issue by MartyCZ-MA** [pkp/pkp-lib#4372]
Hi,

I started work with DOAJ and OJS as I am executive editor of one journal. So far everything with OJS worked well. But recently we have been accepted to DOAJ and when I was trying to use API key to register our content this error appeared: error 301 Moved Permanently (Deposit was not successful! The DOAJ API returned an error: '1.

Could you help me to sove this? DOAJ was surprised by this. 
Just for your information I am kind a newcomer with OJS and everything learning while working with it.
Thank you.

**Comment by bozana** [comment]
Hi @MartyCZ-MA, I see you have also posted a question in the support forum. That is the right place to start with, first when we realize that it is a bug, then a GitHub Issue should be opened. Thus, I will close this issue for now, till we figure out some more details and ...
