### ISSUE TITLE
ajaxOptions deprecated in recent releases of JQuery/JQueryUI

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4375]
Several parts of the JS (e.g. TabHandler.js) use `ajaxOptions` to specify the AJAX configuration for requests made by JQueryUI widgets. That has been [deprecated/removed](https://jqueryui.com/upgrade-guide/1.9/#deprecated-ajaxoptions-and-cache-options-added-beforeload-event) and likely no longer works. Replace it with the newly supported approach (described in the link).

**Comment by asmecher** [comment]
(I'm not sure, but I suspect fixing this might trigger some cases where the Javascript code attempts to decode JSON twice.  Some similar fixing was required for https://github.com/pkp/pkp-lib/issues/4072.)

**Comment by asmecher** [comment]
I haven't looked into this in detail, but at a glance, something like that; does it seem to run OK?

**Comment by jamshidhashimi** [comment]
PR:

Pkp/pkp-lib#4397

Please review @asmecher.

**Comment by asmecher** [comment]
@NateWr, would you mind looking at this?

**Comment by NateWr** [comment]
This looks great, @jamshidhashimi! I'm confident the tests would have failed if there was a problem so I've gone ahead and merged it.

**Comment by jamshidhashimi** [comment]
Thank you @NateWr!
