### ISSUE TITLE
Unable to upload review revision

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4376]
As Editor, trying to upload a review revision results in an error. (This appears to be an unreleased regression.)

**Comment by asmecher** [comment]
It appears that the problem is a `ReviewRoundRequired` auth policy depending on a submission being present in the authorized context when none has been added/checked.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/2246
- https://github.com/pkp/omp/pull/621

**Comment by asmecher** [comment]
@bozana, would you mind having a look? Thanks!

**Comment by bozana** [comment]
@asmecher, yes, everything fine, you can merge and cherry-pick...

(Do I understand correctly, that the problem was access on submission object in ReviewRoundRequiredPolicy that was not there yet?)

**Comment by asmecher** [comment]
Thanks, merged and cherry-picked! Yes, that was the problem, though I'm not sure exactly when the regression happened -- it seems like that always should have been a  problem with the way it was coded...
