### ISSUE TITLE
[OJS] Add Arabic (ar_IQ) to OJS

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#438]
Recently received from Mohammed M. Ali.

**Comment by vormia** [comment]
Thanks a lot, wishing every one interested in scientific publishing to try it.

![ojs arabic](https://cloud.githubusercontent.com/assets/11721197/6898777/acaf55dc-d704-11e4-9762-7349bcc4fc91.png)

**Comment by omarmm** [comment]
Hi @vormia  , can you please help me . I want to use this arabic version how can i try or download it!

**Comment by vormia** [comment]
Hi;
It was sent to the PKP team about a month ago, and I think it was scheduled to appear in the next release, nevertheless, I'm pleased to attach it for you if you provide me with your email.
Me also, I can't wait to see the new version of OJS containing this language pack, so that every Arabic speaking person can use it freely.
Many regards.

**Comment by asmecher** [comment]
@mtub and @jmacgreg, did one of you get the language pack by email? (Just making sure it isn't forgotten.)

**Comment by omarmm** [comment]
Thank you for replying .. and I will be delighted if you send it to me on
eng.omarmm@gmail.com,

And I'll be very happy to see our Arabic language in the next OJS release

Thank you again :)

**Comment by vormia** [comment]
Pull request was added to merge the *Arabic* translation files.

**Comment by mtub** [comment]
Arabic translation has been added via #524 and pkp/ojs#498. Thanks again, @vormia .

**Comment by salmoomen** [comment]
Dear Sir 
Is it possible to send a copy to me on
salmoomen@yahoo.com
I really appreciate that
Regards
Saad

**Comment by vormia** [comment]
Hi, @salmoomen.
You may download the whole project from the link:
[Open Journal Systems](http://pkp.sfu.ca/ojs/download/ojs-2.4.8.tar.gz) containing the Arabic language pack fully customized, but you need to add it to the system interface after installation.
Many regards.
