### ISSUE TITLE
counter bot list not properly cached and used with PHP 7.2

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#4390]
Trying to change array elements via references in the filter function here https://github.com/pkp/pkp-lib/blob/ojs-stable-3_1_1/classes/core/Core.inc.php#L426 is not working in PHP 7.2, so the function should be re-written.

**Comment by bozana** [comment]
PRs:
pkp-lib stable-3_1_2: https://github.com/pkp/pkp-lib/pull/4391
ojs stable-3_1_2: https://github.com/pkp/ojs/pull/2250 (only submodule update)
omp stable-3_1_2: (only submodule update)

pkp-lib ojs-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/4392
ojs ojs-stable-3_1_1:  https://github.com/pkp/ojs/pull/2251 (only submodule update)

pkp-lib omp-stable-3_1_1: https://github.com/pkp/pkp-lib/pull/4393
omp omp-stable-3_1_1: https://github.com/pkp/omp/pull/622 (only submodule update)

pkp-lib master:

**Comment by bozana** [comment]
@ajnyga, could you please test the patch?

**Comment by ajnyga** [comment]
got a 500 error, not sure yet why

**Comment by ajnyga** [comment]
@bozana an user agent called `"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.4.2661.102 Safari/537.36; 360Spider"` is still getting through.

Should `/spider/` take care of that? Does the current code work with strings that have capital letters? I thought they do because SemrushBot is gone, but not sure anymore?

**Comment by bozana** [comment]
@ajnyga, I'll take a look...

**Comment by bozana** [comment]
@ajnyga, sorry for the delay :-\
It seems that the regex match is currently case-sensitive: s. https://github.com/pkp/pkp-lib/blob/stable-3_1_2/classes/core/Core.inc.php#L112, and the $regex there is "/spider/" because we only add "/" to each line. In order for it to be case insensitive the $regex should be "/spider/i".
The documentation here https://github.com/atmire/COUNTER-Robots, last sentence, says: "When matching against the patterns in this list, we recommend to use case-insensitive matching.". Thus I think we should make it case insensitive. I would just have to check if this would work with the botAgents.txt in the same way, because isUserAgentBot is a core function... but why actually not... ? :thinking:  @asmecher, do you maybe see a reason why adding "i" to the reg expressions in botAgents.txt, for the matching/searching to be case-insensitive, would not work i.e. be wrong?

**Comment by ajnyga** [comment]
i++

**Comment by bozana** [comment]
I've opened a new issue for that (s. https://github.com/pkp/pkp-lib/issues/4403), so I will close this one...
