### ISSUE TITLE
Improve CrossRef deposit XML filename

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#4394]
When you deposit to CrossRef, OJS creates an unique "filename" as follows:
`a6b26378-f7f0-4c2d-a2ad-602f39884946.xml`

If something fails, whey you review your deposits in Crossref, the only reference is the filename... so a prefix with the journal tag will help a lot to identify records in your deposit list.

This is clearly a "feature request" to be discussed and developed if you also think it's useful.

@bozana what do you think?

**Comment by marcbria** [comment]
@NateWr do you mind to tag as "Feature request"?

**Comment by NateWr** [comment]
@marcbria this is the file generated when you use the Crossref export tool under Tools > Import/Export > Crossref in order to generate a XML file for manual deposit. Not when someone is depositing just by clicking a button in OJS. Is that right?

**Comment by marcbria** [comment]
Yes, to both.

**Comment by marcbria** [comment]
I don't know how I closed this. :-)

Sorry. It's still open... but with a low priority.

**Comment by marcbria** [comment]
This screenshoot is a better example about what happens when you have multiple journals asking for DOIs at same time...

![imagen](https://user-images.githubusercontent.com/2779168/124143691-9fb9df00-da8b-11eb-8f24-1d6777cb5e39.png)

Would be nice to add journal's tag at the beginning of the file, but as said... low priority for this.

Cheers,
m.

**Comment by bozana** [comment]
@marcbria, the last number is journal ID, isn't this enough? -- because all our exported files have a structure like that: export plugin name - date ('Ymd-His') - object part (e.g. articles - article ID) - context ID...

**Comment by marcbria** [comment]
I didn't know the syntax. :-)
Now it's clear to me but it's not obvius.

Why not adding the journal tag instad of a number? It's also unique and it's short, isn't it?
And probably make more sense to sort differently... to distinguish the journal faster?

My proposal would be:
pluginName - journalAlias - date ('Ymd-His') - objectPart (articles - artID) - contextID

**Comment by asmecher** [comment]
Sorry for the wait and lack of feedback, but I have no strong preference. Generally I'd prefer we avoid trying to load everything someone may want into a filename; from my perspective the plugin name, journal alias/ID, timestamp, and object type and ID are already plenty.
