### ISSUE TITLE
Allow editors to have saved views for the submissions list

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#4396]
**Describe the problem you would like to solve**
Editors tend to perform routine tasks on a regular basis. For example, they may look for all overdue submissions once a week or once a month. Or they may want to review all new submissions to a certain section each week.

In such cases, the editors must remember the unique combination of filters and re-apply them each time.

**Describe the solution you'd like**
Allow editors to save a "view" of the submissions list and reload it any time. A view would be any combination of filters that the editor has applied to the submissions list.

See the screenshots below.

**Who is asking for this feature?**
Editorial staff who perform routine tasks that require them to filter the submissions list.

**Additional information**
The following mockups show how saved views could work in the submissions list. Whenever the editor has one or more filters applied, a button appears at the bottom of the filters list to save the view.

![views-save](https://user-images.githubusercontent.com/2306629/143894458-c4e10dc9-dcb5-4edc-b39f-cec3150f1892.png)

The editor is then given an opportunity to name the view. Once it is named and saved, it appears under a new section, "Saved Views":

![views-list](https://user-images.githubusercontent.com/2306629/143894669-51309cca-17df-4e92-9a6b-39d9667d7a47.png)

This issue has been edited to add proposals for improvements scheduled for 3.5. The original comment is below:

> Some editors are asking for notifications for certain situations.
> 
> They like to be warned if an article "stays too long in a specific stage" or "reviews of certain section refuse to review" or "articles arrive to production"... who knows.
> 
> Looks to me as a reasonable petition, so thinking in who it could be done with less effort I thought it can be implemented as an RSS output for each filter. I mean, don't look trivial, but with RSS you won't need to bound events to cron and discover if the notification was sent or not... and so on, just output the list as xml and let RSS do it's job.
> 
> Going further with idea, "saved filters" (understood as personalized filters each user can create) sounds like a nice complement to the former petition... although they make sense even without notifications.
> 
> As tagged in subject, this is a "feature request".
> 
> @NateWr let me know if you need something.

**Comment by NateWr** [comment]
@marcbria I've hijacked this issue for the saved filters and I moved your feature request for notifications to https://github.com/pkp/pkp-lib/issues/7493.

**Comment by asmecher** [comment]
@Devika008, I believe we moved away from this design due to the requirements being met implicitly with the selection of queues. I'll close this as a WONTFIX, but please reopen if I've got it wrong.

The current set of queues and filters are bookmarkable, so those wanting saved views can simply set them up then bookmark the page.
