### ISSUE TITLE
User Import tries to assign user groups without a user id

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4398]
The assignment of user groups within the `UserXMLPKPUserFilter` depends on the persistence of a `User` via a `$userId`.
https://github.com/pkp/pkp-lib/blob/a15388c36aa6f2fff03ad34c107d07c8ed56aa89/plugins/importexport/users/filter/UserXmlPKPUserFilter.inc.php#L242

This `$userId` was only assigned, however, if the user was created:
https://github.com/pkp/pkp-lib/blob/a15388c36aa6f2fff03ad34c107d07c8ed56aa89/plugins/importexport/users/filter/UserXmlPKPUserFilter.inc.php#L213
or matched by username and email:
https://github.com/pkp/pkp-lib/blob/a15388c36aa6f2fff03ad34c107d07c8ed56aa89/plugins/importexport/users/filter/UserXmlPKPUserFilter.inc.php#L159

The case of a mismatch of username and email is unhandled, and results in an unset `$userId` variable.

**Comment by bozana** [comment]
merged, thus closing...
