### ISSUE TITLE
orphan notes

### ISSUE THREAD

**Issue by gurumelo** [pkp/pkp-lib#4402]
If you click on “Create a discussion” but you close the form (unfilled). Orphan note is created in table ```notes```

**Comment by asmecher** [comment]
@gurumelo, what version of OJS is this?

**Comment by gurumelo** [comment]
Thanks @asmecher 
OJS 3.1.1.4.
Sorry, i always forget it

**Comment by asmecher** [comment]
Hmm, there's already code in place to remove notes when queries are deleted (https://github.com/pkp/pkp-lib/blob/ojs-3_1_1-4/classes/query/QueryDAO.inc.php#L253..L255); do you see anything in your PHP error log?

**Comment by gurumelo** [comment]
Thanks @asmecher 

No errors in error.log

## Before:
SELECT * FROM notes WHERE assoc_type = 1048586 AND assoc_id NOT IN (SELECT query_id FROM queries) 
**100 rows**

## Action:

![action](https://i.imgur.com/lRBlSJL.gif)

## After:
SELECT * FROM notes WHERE assoc_type = 1048586 AND assoc_id NOT IN (SELECT query_id FROM queries) 
**101 rows**

Consequence:
Editorial history doesn't load.
error.log → Call to a member function getStageId() on null in /ojs/lib/pkp/classes/submission/PKPSubmissionFileDAO.inc.php on line 762, referer: https://xxxxxxxxxxxx/ojs/index.php/ramd/workflow/index/549/3

**Comment by asmecher** [comment]
@gurumelo, yes, you can delete all these cases (but please take a DB backup before you do). I suspect the case of a cancelled/deleted query may not be the case that causes it, but in any case, it shouldn't cause harm to remove these notes.

**Comment by gurumelo** [comment]
Thanks @asmecher. I am going to delete this entries and i will comment results with Editorial History.

**Comment by gurumelo** [comment]
Hi @asmecher 

```
DELETE FROM notes WHERE assoc_type = 1048586 AND assoc_id NOT IN (SELECT query_id FROM queries);
```

Same result. Editorial History doesn't work. Always loading.

I look that, in this issue, with all roles. I can download files attached. Click on it
But if i display file → More Information → display → download → error (no roles)

![https://i.imgur.com/HQPC2Y0.png](no)

**Comment by gurumelo** [comment]
Hi @asmecher .
I can reproduce it, doing:
OJS 3.1.1.4 clean
Administration Panel → Submission→ New submission
Do the process.
Then, at the finish review the submissión
https://XXXXXXXXXX.com/index.php/nailos/workflow/index/7/1

And Editorial history always loading..........

**Comment by asmecher** [comment]
@gurumelo, I'm sorry, but I still can't replicate that behaviour using the current `ojs-stable-3_1_1` branch (which is essentially OJS 3.1.1-4)... I'm curious whether you're planning to upgrade to OJS 3.1.2, and if so, whether it shows the same behaviour?

**Comment by bdmckay** [comment]
Version 3.1.1.4 here.

I get “Call to a member function getStageId() on null in lib/pkp/classes/submission/PKPSubmissionFileDAO.inc.php:762” when “Editorial History” is clicked on some submissions.  Then it hangs.

Both submissions that I know to have this problem date from 2.4.8-2 days.

How can I identify entries in the notes table that belong to a particular submission?  Is it just that notes.assoc_id equals the submission_id?

Thanks.

**Comment by asmecher** [comment]
I think this is possibly https://github.com/pkp/pkp-lib/issues/4179 -- is it possible for either of you to try upgrading to the latest release to see if that resolves the issue?

**Comment by bdmckay** [comment]
I'm in the wrong country for another two months and can't consider upgrading while I'm this far from the server.

Meanwhile, I made a bold change like this (lines up to 762 of lib/pkp/classes/submission/PKPSubmissionFileDAO.inc.php):

` case SUBMISSION_FILE_QUERY:
        $noteDao = DAORegistry::getDAO('NoteDAO');
        $note = $noteDao->getById($submissionFile->getAssocId());
        $queryDao = DAORegistry::getDAO('QueryDAO');
        $query = $queryDao->getById($note->getAssocId());
-       return $query->getStageId();
+       if ($query) { return $query->getStageId(); } else { return false; }`

This appears to make the two misbehaving submissions behave correctly, but is it going to screw up other things?

**Comment by asmecher** [comment]
@bdmckay, I've confirmed that this is in fact issue #4179. There's a resolution already applied to OJS 3.1.2 and newer that's functionally the same as what you did: https://github.com/pkp/pkp-lib/commit/174bf109a2bcca73df0b4658d014afbc078696fd

Feel free to keep your change, or apply the equivalent one in the patch linked above, or upgrade to OJS 3.1.2 or newer.
