### ISSUE TITLE
Show "New Submission" button on dashboard for reviewers

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4412]
All registered users in OJS are able to make a submission and can see the "Make a Submission" button on a journal's homepage, regardless of whether they have the Author role (in standard configurations).  However, on the backend submissions dashboard, the "New Submission" button is only visible to users in the Author role and not to Reviewers.  This can be confusing when someone registers for a user account, selects the Reviewer role during registration (when this is an option), logs in for the first time, and is immediately taken to the submissions dashboard with no "Make a Submission"/"New Submission" option.  The user will not necessarily think to go to the site's homepage and may assume they can't make a submission.  I can't think of a reason why the "New Submission" button shouldn't show on the submissions dashboard for Reviewers as well as Authors.

**Comment by nim0x** [comment]
+1

As Assistant Editor I've received messages from confused reviewers who wanted to make submissions from within the backend and weren't able to find the button.

**Comment by ptrckb** [comment]
We had the same request from one of our journals and ended up writing a [plugin enabling the 'New Submission' button also for reviewer](https://gricad-gitlab.univ-grenoble-alpes.fr/bernaupa/ojs-would-be-author).

**Comment by NateWr** [comment]
@ptrckb That's some clever monkey patching in the `SubmissionsListPanel`!! :heart:

**Comment by NateWr** [comment]
This is unintentional so I've labeled it a bug.

**Comment by amandastevens** [comment]
A comment from a PKP|PS hosted client: "This is a big problem. I would expect most users to tick the reviewer box when they register. This leads to a lot of confused authors when they get to the site, and there is no "new submission" button. Indeed, I've answered four inquiries already in the past week. When will this bug be fixed?"

**Comment by NateWr** [comment]
The next most likely release for a fix is 3.2. In the meantime, for individual clients you can use @ptrckb's plugin. You'll just need to note to disable it when upgrading to the version with the fix in.

**Comment by NateWr** [comment]
Fixed in https://github.com/pkp/ui-library/commit/87d28b7647c8beed85f0ac7416c67087217ff142.
