### ISSUE TITLE
Context path property creates conflict when disable_path_info is enabled

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4414]
From @asmecher:

> A problem introduced with the form rewrite: previously the "create journal" form used the POST variable "journalPath" to contain the URL slug, because the `path` URL variable (like `page` and `op`) are reserved by the router for `disable_path_info` mode. The rewrite uses `path` for both, so there's a collision when `disable_path_info` is turned on (which I've recently added testing for). See https://travis-ci.org/pkp/ojs/jobs/487629930 for an example.

In this case we can rename the `path` property of a context to `urlPath`.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/4437
https://github.com/pkp/ojs/pull/2269
https://github.com/pkp/omp/pull/629

@asmecher This fixes the issue for contexts. They're the only entity using the prop as an API param, so the only ones with the conflict now. However, I noticed that Categories, NavigationMenuItems and UserGroups also have a `path` property. 

Should I refactor those now to avoid causing the issue down the line or should we deal with them when we get there?

**Comment by asmecher** [comment]
That looks good -- please go ahead.

I don't have a strong opinion on fixing this now or when it becomes a problem. If it's quick & easy for you to tack on, then go ahead and fix the others in the `master` branch (but don't get too fussed about porting to `stable-3_1_2`).

**Comment by NateWr** [comment]
:+1: I've gone ahead and merged as-is. I've only done this for `master`, not `stable-3_1_2`, because this should only be a problem in `master`, right? I don't think `stable-3_1_2` has any of the schema/api/form stuff that lead to this.

**Comment by NateWr** [comment]
@asmecher, for some reason this hasn't fixed the `disable_path_info` tests. (Shouldn't have been merged but I got my PRs/tests mixed up and thought they'd passed.)

The tests are returning an error which I can't reproduce locally:

```
Failed command: waitForElementPresent('css=#context-urlPath-error:contains('The path can only include letters')')
```

I'm having some issues with the vagrant for testing, which I've posted in Slack.

I've lost my own testing VM (it auto-upgraded Ubuntu and broke everything :cry:). Until I can run the tests and interact with the VM, I can't do much more with it. So I'll hope for a solution for the Vagrant and if I can't get that going I'll try to recreate my VM.

**Comment by asmecher** [comment]
@NateWr, you're right, `stable-3_1_2` tests are working (though not especially reliably). This issue only seems to affect `master`.

I'll work with the tests locally to see if I can figure out what's happening.

**Comment by asmecher** [comment]
@NateWr, the problem I get in `master` when creating a journal is this:

![ss](https://user-images.githubusercontent.com/200411/52441331-2f365000-2ad5-11e9-88fc-2ee62345e130.png)

It looks to me like the Slim routing for the `POST` request to create a journal isn't working. I get a warning in the PHP error log:
```
PHP Warning:  assert(): assert(!empty($requestedOperation)) failed in /home/asmecher/git/ojs/lib/pkp/classes/security/authorization/HandlerOperationPolicy.inc.php on line 78
```
I can replicate this behaviour locally by trying to create a context with `disable_path_info` turned `On` -- no fancy footwork required.

Does that give you something to work with?

**Comment by NateWr** [comment]
Hmm... I can't seem to reproduce that, either the `403` or the `assert`. I'm curious, what does the `POST` request look like in the dev tools. Can you post a screenshot like this if you get a chance?

![selection_015](https://user-images.githubusercontent.com/2306629/52563418-42109380-2df9-11e9-9710-c2fea8ab51cc.png)

**Comment by asmecher** [comment]
Here it is in all its glory. Note that the invalid characters in the path aren't necessary to trigger the error -- I tested with `publicknowledge` as usual and it still complained. I wonder if this has something to do with inconsistent escaping in the POST URL? It's shown as `http://localhost/git/ojs/index.php?journal=%2A&endpoint=/*/api/v1/contexts` -- note one `*` escaped as `%2A` and the other unescaped.

![ss](https://user-images.githubusercontent.com/200411/52652140-63798a00-2ea2-11e9-887b-ebcf41f5ec50.png)

**Comment by NateWr** [comment]
That could very well be it! The `*` character is used to set up the site-wide context level, and without it the handler will refuse to serve the `POST` endpoint for `/contexts`.

Any idea why it might not be escaped on my system?

**Comment by NateWr** [comment]
@asmecher I checked back in on this today and I still can't reproduce the problem where the `*` character is escaped. Do you mind trying to reproduce this again and see if the problem persists for you? Reproductions steps:

1. Set disable_path_info to on.
2. Go to admin.
3. Try to create a journal.

**Comment by asmecher** [comment]
> can't reproduce the problem where the * character is escaped

Do you mean escaped or *not* escaped? I think the `*` should appear escaped as `%2A` in requests -- in fact it'll cause problems if not; I suspect IIS is refusing to handle unescaped `*` in paths in this forum post: https://forum.pkp.sfu.ca/t/save-button-keeps-processing-and-does-not-create-new-journal/65018/7

**Comment by NateWr** [comment]
Thanks @asmecher, I had that completely wrong! :joy: I didn't realize that `*` would be a problematic character in paths. I think it's best to avoid it altogether if so. What about `_`? Would that be a safe path to use? We could use something simpler like `index`, but then we have to be careful that we don't have conflicts with a context's urlPath.

The following PRs implement `_`, but easy to change this to whatever we want.

PRs:
https://github.com/pkp/pkp-lib/pull/6659
https://github.com/pkp/ojs/pull/3007
(no omp/ops required)

**Comment by asmecher** [comment]
I have no problem with `_`, @NateWr, and the PRs are clean. Please go ahead! Can you also cherry-pick this back to `stable-3_2_1` for the (interminably imminent) 3.2.1-3 release?

**Comment by NateWr** [comment]
@asmecher I'm off tomorrow but I've added PRs for the stable version in case you want to get 3.2.1-3 released before Monday.

**Comment by asmecher** [comment]
:+1: Thanks, will merge!
