### ISSUE TITLE
Update COUNTER robot list

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4418]
The upstream repository is well ahead of us:
https://github.com/atmire/COUNTER-Robots/tree/7134f6dbc157ecbf44c8f6829f13b4f873fdd805

vs. 

https://github.com/pkp/pkp-lib/issues/3204

**Comment by asmecher** [comment]
Assigning to you, @bozana, since you're already working with the COUNTER bot list :)

**Comment by bozana** [comment]
I would then do the same for stable-3_1_2... OK?
