### ISSUE TITLE
Unpublish issue: JSON parsing error

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4419]
OJS 3.1.1-4.
After pressing `unpublish issue` button I'm getting: 
```
Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Function.n.parseJSON (jquery.min.js:4)
    at Object.success (pkp.min.js:3582)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.b (jquery.min.js:4)
```
But issue is actually beeing unpiblished. 
I don't see any relevent information under the network Chrome's tab. There are 3 responses with status code 200. @NateWr I suppose you know better where the problem might be.

**Comment by NateWr** [comment]
What happens to the user interface? Does it just hang on the loading spinner or does it complete the process?

**Comment by asmecher** [comment]
@Vitaliy-1, I'm pretty sure this is an already-resolved issue (https://github.com/pkp/pkp-lib/issues/4072) -- do you still see it with the `ojs-stable-3_1_1` branch (both `ojs` and `pkp-lib` repos)?

**Comment by Vitaliy-1** [comment]
Yes, this is the same error and is resolved. I see that stable 3.1.1 branch already contains necessary changes. Closing.
