### ISSUE TITLE
Journal Settings: confusing message

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4420]
OJS 3.1.1-4.
Upon deleting the section, user receives the message: 
`Before this section can be deleted, you must move articles published within it into other sections.`
But actually, I was able to remove the section when all _submitted_ articles were moved to another section or deleted.

**Comment by jamshidhashimi** [comment]
@Vitaliy-1 do you think changing the word _published_ with _submitted_ will resolve the confusion?

**Comment by Vitaliy-1** [comment]
Think it should be enough.

**Comment by NateWr** [comment]
Fixed in https://github.com/pkp/ojs/commit/7a4db84d4e02cf9f6433bd028aaecf7954454bd1
