### ISSUE TITLE
Permit API key to be used for content exposure (OAI/article view)

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4428]
Currently (since https://github.com/pkp/pkp-lib/issues/4149) the OAI interface only exposes published content URLs if the publishing front-end is enabled. Likewise, the article URLs don't work if publishing is disabled.

However, some journals want a way to expose content via OAI even when it's not published via OJS. (e.g. Coalition Publi.ca).

Proposal: Use the HTTP `Authentication` header and API key in conjunction to allow requests to the OAI endpoint and article view pages to indicate that they are being performed "as" a particular user, even though that user does not have a logged-in session.

That would permit journals that wish to expose "unpublished" content via OAI to make OAI requests with the `Authentication` header including a journal manager's API key, thus causing the OAI interface and front end to behave as though a logged-in Journal Editor was making the request. Journal Editors have permission to view article content via the front end when logged in, even if it's not "published".

**Comment by NateWr** [comment]
Just double-checking: these OAI requests would be owned by the journal manager or admin? Anyone with a journal manager's API key will be able to perform read _and_ write requests to all API endpoints.

**Comment by fabiobatalha** [comment]
The other use case is related to the under embargo journal contents. To expose the content that have their access controlled by embargo.

**Comment by asmecher** [comment]
@NateWr, good point. Actually, a "subscription manager" role would be enough for this -- I suggest we recommend a user account with just that role. And this will be worth considering for more granular API key generation in the future, which I understand the JWT spec we're using supports.

@fabiobatalha, yes, thanks -- the proposed approach would work for that too.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/4444
- https://github.com/pkp/ojs/pull/2272

How to use it:
- Ensure that an `api_key_secret` has been entered in your `config.inc.php` configuration file.
- As a journal manager, create a new user with a "Subscription Manager" role.
- Log in as that user.
- Go to the "API Key" tab of the User Profile.
- Turn on both the settings:
   [x] Enable external applications with the API key to access this account
   [x] Generate new API key
- Save the form
- Grab the newly-generated API key from the field.
- Make requests for OAI-PMH content using the new API key, e.g.:
    `curl -H "Authorization: Bearer YOUR_TOKEN_GOES_HERE" "YOUR_OAI_URL?verb=ListRecords&metadataPrefix=oai_dc"`

**Comment by asmecher** [comment]
@NateWr, would you mind taking a look at the PRs?

**Comment by NateWr** [comment]
Looks good. I left a few minor comments. I was a bit nervous about opening it up to every page handler so I like how you've made the API key "opt-in" for each handler. :+1:

**Comment by asmecher** [comment]
@NateWr, yes, there's a little bit of code duplication but not much -- if it needs using more than twice maybe a helper in `PKPHandler` is justified.

Thanks for the review -- I've addressed your notes and merged the PRs and will forward-port to `master` shortly.

**Comment by asmecher** [comment]
Cherry-picked forward to `master`.

**Comment by Vitaliy-1** [comment]
@asmecher
Regarding `getallheaders()` in this commit: this method is not working with nginx. Possible workaround: http://php.net/manual/en/function.getallheaders.php#84262

**Comment by NateWr** [comment]
Reopening, moving to 3.2, and assigning to you @asmecher. :)

**Comment by asmecher** [comment]
@NateWr, does this still need some work? Maybe you missed @Vitaliy-1's edit? Thanks!

**Comment by NateWr** [comment]
Yep, I missed the edit. :laughing:
