### ISSUE TITLE
Wrap orcid url in a div instead of span

### ISSUE THREAD

**Issue by amerritt14** [pkp/pkp-lib#4430]
In `ojs/templates/frontend/objects/article_summary.tpl:47` the code calls
```
{$article->getAuthorString()}
```
to retreive the author information. This string is not formatted in the same way as it is in `article_details.tpl`.
The major flaw is that the author's orcid url is wrapped in 
```html
<span class="orcid"> <a href ... </a> </span>
```
Span's do not (by default) force line breaks like divs do, and as such it is pulling the next line of text up on the same line as the url. 
http://theologyofleadership.com/index.php/tlj/article/view/25
![image](https://user-images.githubusercontent.com/16766681/52307194-eca33500-2967-11e9-9739-9d2dfde15691.png)
Simple solutions would be to wrap it in a div, or to include some custom css 
```
span .orcid { display: block; }
```
A more involved fix (and what I believe would be preferred) is to change `getAuthorString()` to return the section formatted exactly the same as in the `article_details.tpl`, as an Unordered list. Then you could extract that code and use `{$article->getAuthorString()}` in both places.
I've searched for the source of this `getAuthorString()` method to try to modify it myself, but I can't find it anywhere. I'm happy to open a PR if anyone is able to point me in the right direction.

Thanks!

**Comment by asmecher** [comment]
@NateWr, would you mind popping a few suggestions in here? @amerritt14, in the meantime, the `getAuthorString` function is implemented in `lib/pkp/classes/submission/Submission.inc.php`. Thanks all!

**Comment by NateWr** [comment]
Hi @amerritt14! It looks like you are using the Bootstrap3 theme. The `article_summary.tpl` and `article_details.tpl` files will be [different with that theme](https://github.com/NateWr/bootstrap3/tree/master/templates/frontend/objects).

It looks like 10 months ago the `<span>` was changed to a `<div>` in that theme for precisely the reasons you specify: https://github.com/NateWr/bootstrap3/issues/68.

Check what version of the Bootstrap3 theme you're using. You should be on v1.1.1 or above to get this fix.

I'll close this issue for now but let us know if that doesn't resolve things for you.

**Comment by amerritt14** [comment]
Perfect, I'll work on updating that theme to the fixed version! Thanks so much for the help.
