### ISSUE TITLE
consider username and email import mismatch

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#4432]
When importing user, we look if that user already exists, s. https://github.com/pkp/pkp-lib/blob/stable-3_1_2/plugins/importexport/users/filter/UserXmlPKPUserFilter.inc.php#L157-L159. 
1) In the case where that user already exists, we also send the e-mail USER_REGISTER: https://github.com/pkp/pkp-lib/blob/stable-3_1_2/plugins/importexport/users/filter/UserXmlPKPUserFilter.inc.php#L248-L255. This should not be the case, because the user is already registered.
2) If `$userByUsername` ad `$userByEmail` exist, but `$userByUsername->getId() != $userByEmail->getId()`, an error  should be added -- both username and e-mail are unique so it should be one and the same user.

**Comment by bozana** [comment]
PRs:
stable-3_1_2:
pkp-lib: https://github.com/pkp/pkp-lib/pull/4433
ojs: https://github.com/pkp/ojs/pull/2268 (only submodule update)
omp: https://github.com/pkp/omp/pull/628 (only submodule update)

master:
pkp-lib: https://github.com/pkp/pkp-lib/pull/4434

**Comment by bozana** [comment]
@asmecher, I created a new issue for the discussion here: https://github.com/pkp/pkp-lib/pull/4399

And, me crazy, I already merged the PRs :-\ Could you take a look if OK so?

**Comment by asmecher** [comment]
Not a problem -- thanks, @bozana! Closing now.
