### ISSUE TITLE
Update Articles & Issues import/export plugin (and others?) for new author name options

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#4435]
This relates to the work done in #2958, where we now have the option for given name, family name, and preferred public name. If I try and import XML from an older OJS 3.x install (< 3.1.2), the old firstname/middlename/lastname fields are used, and don't match what's now expected in the plugin; so I get the following error: 

`Element '{http://pkp.sfu.ca}firstname': This element is not expected. Expected is ( {http://pkp.sfu.ca}givenname ).`

The plugin should probably handle this a bit more gracefully. I don't think it's a blocker for OJS 3.1.2, but it should be resolved at some point. A workaround would be to edit the XML file and replace all instances of `firstname` with `givenname`, `lastname` with `familyname`, etc. 

Note that I haven't tested the user import/export plugin, but I'm guessing there's probably the same issue there.

**Comment by asmecher** [comment]
@jmacgreg, the native import/export toolset isn't intended to maintain backwards- or forwards-compatibility; t'was ever thus. Manual work may be required to adapt XML between different versions of OJS.
