### ISSUE TITLE
Support categories in default theme

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4446]
#4158 introduced categories and browsing by categories to OJS. Our default theme should style these pages. Ideally, all of our themes will support this, but at the very least our default theme should with 3.1.2.

Sorry to chuck this into 3.1.2 so late, @asmecher, but it just occurred to me.

**Comment by NateWr** [comment]
PRs (master):
https://github.com/pkp/pkp-lib/pull/4453
https://github.com/pkp/ojs/pull/2275
https://github.com/pkp/omp/pull/632

PRs (3.1.2):
https://github.com/pkp/pkp-lib/pull/4454
https://github.com/pkp/ojs/pull/2276
https://github.com/pkp/omp/pull/633

**Comment by NateWr** [comment]
Finally, tests passing, no merge conflicts. Thanks for the assist on the OMP tests, @asmecher. Merged.

**Comment by asmecher** [comment]
Woo!
