### ISSUE TITLE
[OJS] Newly created journals do not have publishingMode setting

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4447]
When a new journal is created in OJS3, it does not get a publishingMode setting. The setting is only saved when the publishing mode form is saved for the first time.

To avoid possible existing and future problems with checks related to publishingMode (like `if ($journal->getSetting('publishingMode') == PUBLISHING_MODE_OPEN)` ) we should

1. Change the creation of new journals so that a default (0) is saved when a journal is created
2. Add a upgrade sql that adds the missing publishing mode settings to journals that do not have a value

**Comment by ajnyga** [comment]
hmm, or does that actually return false which is == 0? You can close this right away if so.

**Comment by asmecher** [comment]
Yes, a missing setting is equivalent to `PUBLISHING_MODE_OPEN` (0) because we're not using strict comparisons here. But thanks for the eagle eyes :)
