### ISSUE TITLE
[OJS] when display old notes, date can be confusing

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#4452]
Hi all,

When we have a query with old notes older than a year, the date is always displayed with M / d. So you do not have the year and sometimes (several times;)) the deadline for managing a submission is more than one year.
Like in :
https://github.com/pkp/pkp-lib/blob/e39592b3725cd1c7977a98ad27f9fabe3aef4ffb/controllers/grid/queries/QueryNotesGridCellProvider.inc.php#L49

I propose something like if node older than a year, display the year too.
Maybe it will be better if we use date format described in config.inc.php:
date_format_trunc and date_format_short 

Thanks
[ojs 3 1 1 4]

**Comment by asmecher** [comment]
Thanks, merged and cherry-picked forward!
