### ISSUE TITLE
Addition of corporate name field. 

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#4461]
The modifications of usernames ( #2958 ) are greatly appreciated, I think they'll help a lot with metadata flexibility. We still need a corporate name field for institutional authors or broader research units. Crossref has a specific attribute for corporate name fields (and so do a great number of other schemas, including JATs, the Érudit Article Schema, MODS...).

**Comment by NateWr** [comment]
To clarify: this field should be for contributors or any user?

**Comment by NateWr** [comment]
And how does it differ from Affiliation?

**Comment by AhemNason** [comment]
Oh, sorry, I missed these comments. I must have notifications turned off. I'll remedy that. Apologies! 

So, it's not uncommon for an organization or research group to be listed as an "author" of a document. "Contributor" is maybe a more appropriate synonym. I'd recommend checking out the Crossref schema here because they've really developed this for journal publication. There's associated metadata in JATS as well. 

http://data.crossref.org/reports/help/schema_doc/4.4.1/JATS1.html#contrib 

You'll see that options in Crossref allow for "organization", "person_name", and "anonymous". 

Their use case for an organization is as follows: 

>The name of an organization (as opposed to a person) that contributed to authoring an entity. If multiple organizations authored an entity, each one should be captured in a unique organization element. If an entity was authored by individuals in addition to one or more organizations, person_name and organization may be freely intermixed within contributors. contributor_role should be set, as appropriate, to author or editor. When a contributor translated a work, set contributor_role to "translator". "chair" should only be used for conference proceedings to indicate a conference chair.

And here's an example of the metadata: 

```
<contributors xmlns="http://www.crossref.org/schema/4.4.1">
  <organization contributor_role="" language="" name-style="" sequence="">{1,1}</organization>
  <person_name contributor_role="" language="" name-style="" sequence="">{1,1}</person_name>
  <anonymous contributor_role="" language="" name-style="" sequence="">{1,1}</anonymous>
</contributors>
```

I understand that we have resisted untethering attribution from actual user accounts with email addresses but, increasingly what this means is people insert inappropriate metadata into fields to shoehorn it. Right now what people do in this space is make up a first and last name that just spreads and organization name across two fields.

**Comment by NateWr** [comment]
We do now have a "preferred name" field, which can be used to get around the spreading-across-two-fields problem. But if JATS and Crossref both expect it, it's worth considering on our end.

**Comment by AhemNason** [comment]
Right, and that's great! The issue is that without signifying (via attribute) what _kind_ of preferred name it is, that could end up just going into a ``<surname>`` field like it does with Crossref. We need to disambiguate between types of contributors. Not all contributors are people. 

Further to this, not all _contributions_ have authors. Currently (and this is a different issue) we collect - but simply opt to not display - author names for things like "errata" or other such articles. Those don't typically have authors associated. We often require users to jam metadata where it shouldn't be.

**Comment by isgrim** [comment]
Yes we also stumbled upon this in OMP, as some volumes are edited by a whole organization and they would like to have it shown in the catalog.

**Comment by NateWr** [comment]
Closing this in favor of https://github.com/pkp/pkp-lib/issues/5955.
