### ISSUE TITLE
URI update (https)

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#4466]
Some of the links contained in `pkp-lib` can (should) be updated so that they use https. In most cases the maintainers of the website redirect from http to https, in some other cases they at least deliver the website via https as well as via http. 

Will send PR.

**Comment by mtub** [comment]
PR here: https://github.com/pkp/pkp-lib/pull/4467

**Comment by ctgraham** [comment]
This appears to be a reverted change in 3.1.2-1.  Should this issue be closed?

C.f.: https://forum.pkp.sfu.ca/t/error-register-magazine-oai-pmh/55155

**Comment by asmecher** [comment]
Yes, thanks!
