### ISSUE TITLE
Update Norwegian (nb_NO) translation

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#4470]
Commit new translation update from Norwegian universities

**Comment by asmecher** [comment]
@mtub, I think this one is ready for closing...

**Comment by asmecher** [comment]
Closing -- but also tagging @mtub just in case!

**Comment by mtub** [comment]
yeah about that… I expect a OJS 3.1.2 version, but can open a new PR for that, so you can keep this closed. don't have a time yet for when I will get the translation, so should not keep us from releasing…
