### ISSUE TITLE
[OJS] Review method fallback should be double blind instead of blind

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4474]
If no review method can be found from the settings, blind review is used by default: https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/reviewer/form/ReviewerForm.inc.php#L160

This should be changed to double blind, because it will cause to less harm if things go south.

**Comment by ajnyga** [comment]
ping @asmecher any reason for not changing the above to double blind?

**Comment by asmecher** [comment]
No objections, @ajnyga, that seems like a safer fallback.

**Comment by ajnyga** [comment]
pkp-lib: https://github.com/pkp/pkp-lib/pull/5676
ojs (only submodule): https://github.com/pkp/ojs/pull/2696

**Comment by asmecher** [comment]
Thanks, merged and cherry-picked back to `stable-3_2_0`!
