### ISSUE TITLE
Site-level browse block prevents display of other blocks

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4478]
Testing with a pre-release 3.1.2 install.

When I include the browse block in the sidebar other blocks are no longer displayed.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/2290 (master)
https://github.com/pkp/ojs/pull/2291 (stable)

@bozana can you code review? 

This seems like just a temporary stop-gap. Plugins should have some way of saying they don't work at the site level, and they shouldn't be visible at the site plugins list, similar to how we have `isSitePlugin`. I have a vague recollection that you may have worked on this problem once upon a time. Do you have any ideas for handling this better in the future?

**Comment by NateWr** [comment]
@bozana FYI: https://github.com/pkp/pkp-lib/issues/4501

**Comment by bozana** [comment]
@NateWr, all well, you can merge when ready...

Unfortunately, I have no idea now -- will put a few comments in the other issue...

**Comment by bozana** [comment]
For block plugins, we could eventually also work with getBlockContext($contextId) and define a NO_CONTEXT and if the plugin returns NO_CONTEXT for getBlockContext(0) than it should not be listed in the sidebar manaement on the site setup page i.e. it should not be possible to move it to a sidebar.

**Comment by NateWr** [comment]
Merged.
