### ISSUE TITLE
Site-level information block not displayed

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4479]
Testing with a pre-release 3.1.2 install.

When I include the Information block in the sidebar no content is displayed for the block.

**Comment by NateWr** [comment]
It doesn't do anything at the site-wide level. Like the Browse block, these should probably be hidden from the site-wide plugins list. But to my knowledge we don't have a facility for that yet.

I'm going to close this and I've filed the general problem (for the future, not 3.1.2) here: https://github.com/pkp/pkp-lib/issues/4501. Feel free to reopen if you want to discuss anything.
