### ISSUE TITLE
Site-level 'Make a submission' block leads to error message

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4480]
Testing with a pre-release 3.1.2 install.

Block link directs to an error page with the following:
"You cannot call this operation without a context (press, journal, conference, etc)."

If the block requires a context maybe we should remove it from site settings.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/makeSubmission/pull/22 (master)
https://github.com/pkp/makeSubmission/pull/23 (stable)

Tests:
https://github.com/pkp/ojs/pull/2292 (master)
https://github.com/pkp/ojs/pull/2293 (stable)

@bozana can you review this one too since it's the same sort of thing?

> If the block requires a context maybe we should remove it from site settings.

Agreed.

**Comment by bozana** [comment]
@NateWr, you can merge when ready. Similar to https://github.com/pkp/pkp-lib/issues/4478: For block plugins, for now, we could eventually also work with getBlockContext($contextId) and define a NO_CONTEXT and if the plugin returns NO_CONTEXT for getBlockContext(0) than it should not be listed in the sidebar management on the site setup page i.e. it should not be possible to move it to a sidebar.

**Comment by NateWr** [comment]
Merged.
