### ISSUE TITLE
Journal settings inaccessible after other journals deleted

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4481]
Testing with a pre-release 3.1.2 install.

If there are 2 journals (e.g. production journal and test journal) and the SA deletes one of the journals so that only a single journal remains then it's not possible to navigate to the journal settings for the remaining journal. The journal select dropdown in the left sidebar only displays the site title and includes only a single Administration link. The remaining journal is not included in the dropdown options.

**Comment by asmecher** [comment]
Can you navigate to the settings e.g. by logging out and logging back in, or by going to the homepage and returning to the settings area? I think this is probably a long-standing navigational quirk

**Comment by mfelczak** [comment]
Yes, logging out and then in returns the user to the journal back-end.

**Comment by asmecher** [comment]
OK, thanks -- I'm going to defer this from 3.1.2.

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.
