### ISSUE TITLE
Web feed plugin includes untranslated copyrightStatement locale key

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4482]
Testing with a pre-release 3.1.2 install.

When I enable the Web Feed plugin for the current issue RSS, the feed includes the following untranslated tag text:

`<rights>##submission.copyrightStatement##</rights>`

**Comment by asmecher** [comment]
Thanks, @mfelczak -- fixed for OJS and OMP, both `master` and `stable-3_1_2`.
