### ISSUE TITLE
Information block pages include relative and invalid URLs

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4483]
Testing with a pre-release 3.1.2 install.

When I click on e.g. Information > For Readers the resulting page includes links to the journal's Registration and Privacy Statement pages but the links are relative and lead to 404s, e.g.
- http://localhost/index.php/journalpath/about/submissions#privacyStatement
- http://localhost/index.php/journalpath/user/register

This issue applies as well to the 'For Authors' and 'For Librarians' pages.

**Comment by asmecher** [comment]
I don't see this beaviour, and that code hasn't changed for a long time -- and the links you quote look fine to me. Can you describe the problem in more detail?

**Comment by mfelczak** [comment]
In our 3.1.2 test install the links reference a localhost base_url, e.g.
- http://localhost/index.php/publicknowledge/user/register
- http://localhost/index.php/publicknowledge/about/submissions#privacyStatement

Just confirmed with @jmacgreg that this may have been inherited from the DB image used to populate the test install. Closing.
