### ISSUE TITLE
Acron plugin enable checkbox stays unchecked

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4485]
Testing with a pre-release 3.1.2 install.

When I click on the enable checkbox for the Acron plugin the plugin is enabled on the back-end but the checkbox remains unchecked on the front-end and looks like it's still disabled.

**Comment by mfelczak** [comment]
This only happens some of the time, e.g. if I first enable another plugin before trying to enable the Acron plugin.

**Comment by asmecher** [comment]
This is also https://github.com/pkp/pkp-lib/issues/1923.
