### ISSUE TITLE
Rewrite phpMyVisites plugin for OJS/OMP 3.x

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4487]
Testing with a pre-release 3.1.2 install.

When I enable the plugin there's no Settings link to the settings modal.

**Comment by asmecher** [comment]
This plugin hasn't yet been updated for the 3.x codebase. It's filtered from being included with the distribution `.tar.gz`, but does show up in git-based installs.

**Comment by jamshidhashimi** [comment]
As per [phpMyVisites](http://www.phpmyvisites.net/), they are changing (already changed) into [Piwik/Matomo](https://matomo.org/). It is also mentioned [here](https://matomo.org/faq/general/faq_437/). We already have an independent [Piwik plugin](https://github.com/pkp/piwik). So maybe it is the time to remove the phpMyVisites plugin from source code. 

Happy to provide a removal PR!

**Comment by jamshidhashimi** [comment]
PR:

https://github.com/pkp/ojs/pull/2288

Please review @asmecher. Thanks!

**Comment by asmecher** [comment]
Merged, thanks!
