### ISSUE TITLE
Paypal plugin missing link to settings modal

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4489]
Testing with a pre-release 3.1.2 install.

When I enable the plugin there's no Settings link to set the PayPal account settings.

**Comment by asmecher** [comment]
Try going to Settings > Distribution > Payments, and enabling the payments system and configuring the plugin there.

**Comment by mfelczak** [comment]
Hi @asmecher, I'm not seeing the PayPal account settings in Settings > Distribution > Payments

![screen shot 2019-02-13 at 4 07 14 pm](https://user-images.githubusercontent.com/200793/52744066-99edfc80-2fa9-11e9-81bb-c2504ab0a29c.png)

**Comment by asmecher** [comment]
Good spotting -- fixed with the attached commit, thanks!
