### ISSUE TITLE
Navigation Menus - Custom Templates not available

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#4491]
When the user tries to add or update a NMI that has a custom template attached (custom url and custom page with content NMIs specifically), the related edit custom templates are not getting displayed.

**Comment by defstat** [comment]
@NateWr for some reason the code for loading the customTemplates was missing.

[master] PRs 
[pkp-lib]: #4493
[OJS]: pkp/ojs#2285
[OMP]: pkp/omp#2285

**Comment by NateWr** [comment]
Looks good. Just one mysql test needed to be restarted but seems like it won't be a problem. Can you create a pkp-lib PR for `stable-3_1_2` as well?

**Comment by defstat** [comment]
@NateWr 

[stable-3-1-2] PRs
[pkp-lib]: #4500
[OJS]: [pkp/ojs#2289]
[OMP]: [pkp/omp#641]

**Comment by NateWr** [comment]
All tests passed! I merged the stable PRs but there's a merge conflict on the `master` branch PRs. Can you just rebase those and ping me on Slack so I can merge them?

**Comment by NateWr** [comment]
All merged!
