### ISSUE TITLE
Navigation menu - can't enter remote URL

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4494]
Testing pre-release of OJS 3.1.2, I found an error in creating a Navigation Menu item.  If you create a new menu item that's a remote URL, there is no field where you can enter the URL.  If you try to save it without the URL, you get an error saying you must enter the URL but there is nowhere to enter it.

**Comment by NateWr** [comment]
@defstat is this fixed with #4491?

**Comment by defstat** [comment]
@NateWr Yes that's the fix. Also the same fix applies to the "no path and content fields for the custom pages" problem, if you encounter one.

**Comment by NateWr** [comment]
:+1: 

@amandastevens I'll close this as it's just been fixed as part of a separate issue. Thanks!
