### ISSUE TITLE
Navigation menu - title missing when editing item

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4495]
Testing pre-release of OJS 3.1.2, I found an error in editing a Navigation Menu item. On the list of menu items each item has a title, but when you edit a menu item, there is nothing entered in the title field.  It is blank.

**Comment by defstat** [comment]
@NateWr For that I added a new field on the NMI form, displaying the default Locale Key if any. The translation of that default key can be overridden by adding a custom title.
 
[stable-3_1_2] PRs
[pkp-lib]: #4513
[OJS]: pkp/ojs#2297
[OMP]: pkp/omp#644

**Comment by NateWr** [comment]
I'm worried that the end user doesn't really understand what a translation key is and won't easily interpret what is happening with these fields. Would it be possible instead to put the translated title into the input field's value?

Then, in the form's `execute` method, check the value of each title field locale against the default title. When they match, discard the value and don't save it. When they differ, save the custom title.

**Comment by defstat** [comment]
@NateWr thanks. Made the change and rebased.

**Comment by NateWr** [comment]
Looks good. I made just a few minor comments on the PR.

Can you port this to the `master` branch as well?

**Comment by defstat** [comment]
@NateWr Stable3-1-2 Branches tests passed.

Working on master branch now.

**Comment by defstat** [comment]
@NateWr 

[master] PRs
[pkp-lib]: #4519
[OJS]: [pkp/ojs#2299](https://github.com/pkp/ojs/pull/2299)
[OMP]: [pkp/omp#645](https://github.com/pkp/omp/pull/645)

**Comment by NateWr** [comment]
Merged!
