### ISSUE TITLE
HTML code in email templates and email signature

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4496]
Testing pre-release of OJS 3.1.2.  In Workflow Settings > Emails, HTML code appears in email templates if you edit them and in the email signature field. I don't think this is intentional.

**Comment by asmecher** [comment]
@amandastevens, is it possible that you've disabled the TinyMCE plugin?

**Comment by amandastevens** [comment]
Ah, that must have been it.  It's enabled now and everything is fine.  I didn't think to check that.  I will close this issue.
