### ISSUE TITLE
List users according to account creation date

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#4499]
Some softwares create bot users in the websites they encounter, may be to try to hack the website. For some reasons I encounter many fake user accounts in the journal system and delete them on regular basis. However, as the users always listed alphabetically I always have to scan from the start of the list. If I can list the users according to creation date, I can only scan the recently created ones and my job becomes substantially easier. Every once in a while, I have to remove tens of users after selecting them from hundreds of them.

Therefore, please add a function to list the users according to the account creation date. Thanks all the contributors of this great. project.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
