### ISSUE TITLE
Do not automatically send editor decision emails to all co-authors

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4507]
Currently when the editor records a decision and sends a notification email, all authors on the submission are added to the message and there is no way to remove authors.  

When an author makes a submission they have to add the email addresses of all co-authors and they can check off who is the corresponding author.  But regardless of that, all authors receive correspondence about the submission.  

I think ideally the message would automatically have the corresponding author filled in as the recipient, and then the editor could optionally add the other authors to the message.  

This could be a privacy issue as the co-authors often do not have user accounts in OJS and can’t log in to control their notifications.

**Comment by alexxxmendonca** [comment]
Is this a popular request? In my experience, most cases all authors want to receive a copy of the Decision Letter.

**Comment by heike-r** [comment]
As an editor, I would vote for the contrary and even send the submission confirmation email to all co-authors. This would ensure that all are informed about a manuscript with their name on it ... at least when the submitting author entered valid email addresses for their co-authors, which is not always the case.
If this is a GDPR issue, then the submission check list should contain an item where the submitting author agrees on behalf of their co-authors that they receive information regarding this specific manuscript (same as he/she agrees on their behalf to the terms and conditions for publishing in this specific journal).

**Comment by amandastevens** [comment]
Maybe the ideal is instead to include all of the authors in the message by default, but to make it possible for an editor to remove co-authors from the recipient list if desired.

**Comment by withanage** [comment]
> Maybe the ideal is instead to include all of the authors in the message by default, but to make it possible for an editor to remove co-authors from the recipient list if desired.

I like this suggestion very much!
This is  also relevant in OMP,  when lots of chapter authors are included in edited-volumes.
In some cases there are definite requests for exclusion, which is currently  achieved by temporary chaning the email adresses, either manually of through database quieries.

**Comment by NateWr** [comment]
As part of #7265, a new setting was added to enable/disable a notification to all contributors when an editorial decision is made. More details here: https://github.com/pkp/pkp-lib/issues/2524#issuecomment-1060770901.

**Comment by ej2432** [comment]
@NateWr is this a feature in OJS 3.5? It'd be extremely useful for our workflow! I will open a new issue with more information about our use-case.
