### ISSUE TITLE
3.1.1-4 add galley endless spinner

### ISSUE THREAD

**Issue by vvkorotkikh** [pkp/pkp-lib#4510]
OJS 3.1.1-4, postgres.
When I try add galley to published article after set type "pdf" and press "save" there is endless spinner in the end of the galley form. If I close this form, there is no added galley in this article. 
OJS update path: 2.4.5 -> 3.0,2 -> 3.1.1-4.
In old articles with added under OJS 2.4.5 galleys I can create/edit/delete galleys. In articles added under OJS 3.0.2 I can add galley only for full issue.
How can I add galley to new articles under 3.1.1-4 version?

**Comment by vvkorotkikh** [comment]
![spinner](https://user-images.githubusercontent.com/10060590/52916535-da26e500-32f1-11e9-8f3c-dbae75aa9a6c.png)

**Comment by asmecher** [comment]
@vvkorotkikh, can you check your PHP error log for details?

**Comment by vvkorotkikh** [comment]
[error.log](https://github.com/pkp/pkp-lib/files/2886327/error.log)
Here my error log during adding new galley.

**Comment by asmecher** [comment]
@vvkorotkikh, the relevant error log message is
```
DB Error: \xd0\x9e\xd0\xa8\xd0\x98\xd0\x91\xd0\x9a\xd0\x90:  \xd0\xbd\xd1\x83\xd0\xbb\xd0\xb5\xd0\xb2\xd0\xbe\xd0\xb5 \xd0\xb7\xd0\xbd\xd0\xb0\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb2 \xd0\xba\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xbd\xd0\xba\xd0\xb5 "file_id" \xd0\xbd\xd0\xb0\xd1\x80\xd1\x83\xd1\x88\xd0\xb0\xd0\xb5\xd1\x82 \xd0\xbe\xd0\xb3\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 NOT NULL\nDETAIL:  \xd0\x9e\xd1\x88\xd0\xb8\xd0\xb1\xd0\xbe\xd1\x87\xd0\xbd\xd0\xb0\xd1\x8f \xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd0\xba\xd0\xb0 \xd1\x81\xd0\xbe\xd0\xb4\xd0\xb5\xd1\x80\xd0\xb6\xd0\xb8\xd1\x82 (1443, ru_RU, 1548, null, pdf, 0, , 0).
```
...which decodes to...
```
DB Error: ОШИБКА:  нулевое значение в колонке "file_id" нарушает ограничение NOT NULL\nDETAIL:  Ошибочная строка содержит (1443, ru_RU, 1548, null, pdf, 0, , 0)
```
...or, in English...
```
DB Error: ERROR:  null value in column "file_id" violates not-null constraint\nDETAIL:  Failing row contains (1443, ru_RU, 1548, null, pdf, 0, , 0)
```
That message is also discussed here, with a solution:
https://forum.pkp.sfu.ca/t/ojs-3-0-2-cant-add-galley/30708
