### ISSUE TITLE
[OJS] Support for internal editorial guides 

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4511]
Hi,

I received an enquiry whether there is a way in OJS to have a place for internal editorial instructions. There is of course the submission library, but adding documents there make them available for authors as well I think and it is too much work to add them for each submission. Also section editors can not access the main library so uploading the documents there is not enough.

What I was thinking is a simple internal forum available for editoria staff. It could simply be a discussion grid without a submission available on a specific page in the dashboard. There you could also upload documents like instructions if you want. This could be a plugin I think.

What do you think?

**Comment by NateWr** [comment]
Section editors can access files in the publisher library by going to an assigned submission > Submission Library > View Document Library.

A journal-wide discussion grid sounds like a bad solution to this problem. Old messages, where instructions are likely to be placed, will drop out of view over time. There is no clear way to surface messages from a global grid in the normal editorial workflow, which is tightly scoped around the submissions grid (tasks are easily missed).

If you need a one-off solution, I would recommend one of these options:

1. When a submission is created (or moved to a stage), automatically create a discussion with the message/file you want to share.
2. Update the Email Template for when an editor is assigned to include a link to the editorial guidelines. Files in the Publisher Library can be made public for easier access.
3. Add a notification to the appropriate workflow stage with a link to the editorial guidelines file.

I'm going to close this as a `wontfix` but of course feel free to continue discussing.

**Comment by ajnyga** [comment]
Ok, document library in general is not really a solution, because authors can access that as well through a submission. The journal wanted their instructions to be visible only for editorial staff.

**Comment by sabrinaeck** [comment]
Hi to all,

we solved this by creating a submission just visible for all editors with the editorial guide as manuscript. We waited until a well memorable sumission Id was going to be assigend. In this submisison we can exchange new versions and every editor will be noticed of these changes. This seems to work well (no complaints :-))

Sabrina
