### ISSUE TITLE
columns array is null when generating stats report

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#4512]
The $columns variable used in this in_array() call:

https://github.com/pkp/pkp-lib/blob/f3973837d127dfd6bfddea23fa9a1bffd1916140/pages/management/PKPToolsHandler.inc.php#L215

is null when generating a report via the PKP Usage Statistics link in the Tools interface.  It is set before the getMetrics() call and I think this is because there's some use of references within the MetricsDAO classes that unsets the variable.  A quick workaround is to reuse the $request->getUserVar('columns') call in this statement.

I can submit a PR for this if it is useful.

**Comment by asmecher** [comment]
@jnugent, what branch/version are you using? Is there a warning/error message associated with the problem?

**Comment by jnugent** [comment]
Sure, the error is:

[Mon Feb 18 08:13:15 2019] [error] [client 47.55.87.210] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/home/journal/www/lib/pkp/pages/
management/PKPToolsHandler.inc.php on line 215

(repeated)

Version is OJS 3.1.1.0 in this case.

**Comment by asmecher** [comment]
I don't see any relevant reference use at a glance -- are you sure it's not just a case of no columns being selected in the interface?

**Comment by jnugent** [comment]
No, definitely columns.  This particular report is being generated by selecting the "PKP Usage Statistics Report" from within the stats admin interface, without going into the custom report options.  The generated URL looks like:

http://journal-url.org/index.php/fsj/management/tools/generateReport?metricType[]=ojs%3A%3Acounter&columns[]=assoc_id&columns[]=assoc_type&columns[]=file_type&columns[]=submission_id&columns[]=context_id&columns[]=pkp_section_id&columns[]=city&columns[]=region&columns[]=country_id&columns[]=month&columns[]=metric_type&columns[]=metric&columns[]=assoc_object_id&filters=a%3A1%3A%7Bs%3A10%3A%22context_id%22%3Bs%3A1%3A%221%22%3B%7D&orderBy=a%3A1%3A%7Bs%3A5%3A%22month%22%3Bs%3A3%3A%22ASC%22%3B%7D

And if variable dumping is turned on, the columns variable has content before the call to getMetrics() but not after.

**Comment by asmecher** [comment]
Hrm, the only candidate function for this looks to me like `getMetrics`, but I don't see any function headers where `$columns` is passed in by reference. Did you spot anything?

**Comment by jnugent** [comment]
Hmmm.  I see that in the Metrics DAO there's some reference use here:

https://github.com/pkp/ojs/blob/7a8905827a96eb072d6015fe8119be6c22cca25b/classes/statistics/MetricsDAO.inc.php#L26

where $columns is accessed with a reference, and then unset here:

https://github.com/pkp/ojs/blob/7a8905827a96eb072d6015fe8119be6c22cca25b/classes/statistics/MetricsDAO.inc.php#L36

Could that be it?

**Comment by jnugent** [comment]
but yes, you're right - there aren't references in the headers.

**Comment by asmecher** [comment]
What version of PHP are you running this on?

**Comment by jnugent** [comment]
PHP 5.6.27, running as a CGI.  This is a gossamer threads server.

**Comment by asmecher** [comment]
Would you mind tracking into it a little further? PHP should always pass arrays by value, unless a reference is specified, and I don't see a reference in this case. So I wonder whether it's a PHP bug, or whether I'm missing the place where the array is modified.

**Comment by jnugent** [comment]
Sure, I'll dig into it!

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.
