### ISSUE TITLE
Administration Pages - Language Change Issue

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#4516]
Trying that configuration [https://github.com/pkp/pkp-lib/issues/4462#issuecomment-464776988] on OJS 3.1.2 stable branch I came across an issue when trying to change the language  
![image](https://user-images.githubusercontent.com/560456/53037897-05d9d480-3484-11e9-89e7-ec0dc9bcf4ce.png)

I get that response:
![image](https://user-images.githubusercontent.com/560456/53037783-c8754700-3483-11e9-8ffc-26497ee3b1cc.png)

**Comment by asmecher** [comment]
I think this is the same as https://github.com/pkp/pkp-lib/issues/1116#issuecomment-461947138.

**Comment by defstat** [comment]
Yes it is the same - closing that one..
