### ISSUE TITLE
Improve report download options for very large reports

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#4517]
We're running into a variety of issues with some clients' very large statistics/report downloads, which can consist of .csv files well in excess of 50k rows. Mostly we're exceeding PHP's various execution time and memory limit directives, resulting in timeouts, 500 errors, and occasionally non-transparent partial downloads (eg. where the .csv file stops being outputted at a particular line when the given PHP limit is hit). Increasing these PHP directives is only a temporary solution - we can't keep raising them. These limits aren't an issue for cli-run PHP processes. Our suggestion would be to provide a cli option for creating these reports, and optionally a daily scheduled task + some sort of means to download them through the reports interface.

**Comment by jmacgreg** [comment]
@ajnyga I would be interested if you have given this any thought at all, as you probably run into these same issues!

**Comment by jmacgreg** [comment]
@jnugent, @israelcefrin and @NateWr and I just had an interesting conversation about using the new API to manage stuff, and the consensus was that using it to either generate reports via CLI, or to provide a report download button option from Nate's most recent stats visualization tool would be the way to go. I'm not quite sure where this leaves the "old" reports: folks have, for better or worse, settled on them as the standard, and they would probably need to at least continue to compare the downloads across different report types. I'm not sure if this means they should be maintained as-is, or rewritten to use the API, or what. Worth further discussion.

**Comment by NateWr** [comment]
If you want users to be able to go in their browser and get a report, there are really only two ways to address this issue:

1. You can fire off successive AJAX requests, each one of which compiles a chunk. If the end result that we want is for the user to get a download prompt, this may not be appropriate. But it works in cases where you're processing large volumes of material and the user is prepared to wait or wants to know the progress.

2. The user interaction can fire off a process that runs in the background, disconnected from their HTTP request. This is how, for example, MailChimp handles exports of its mailing lists. The server puts the task into a queue and executes it on its own time, and the user is then alerted when it is finished. (MailChimp emails you the file.)

For the case you describe in this issue, I think (2) is the better route. I know that OJS has scheduled tasks, but I don't know if it actually has a queue runner. If not, such a thing would be a good thing to have. (Another future use-case for a queue runner would be caching internal workflow stats like average time to review.)

**Comment by ajnyga** [comment]
Actually no one has reported such issues in our case. It could be that although our metrics table is fairly large, we also have many journals, so the size per journal is not that high.

The only similar problem I ran into was the STATISTICS_MAX_ROWS limit that was set to 5000. That is now removed in master and I have changed our current value to a value that is definitely never broken. However, no editors have reported 500 errors or anything that would suggest memory limit being reached. 

It could very well be that the new stats UI means that most editors do not even bother to download those files anymore.

**Comment by bozana** [comment]
Just a not that this issue is partly connected: https://github.com/pkp/pkp-lib/issues/7318

**Comment by bozana** [comment]
I would close this issue, because stats and reporting are refactored. We can then see how the new reports are doing and if there is any problem we can open a new issue.
If there is still a problem with huge reports download and timeout, we will need to consider a new approach -- e.g. to save the report settings/filters, dispatch a job to get the data and save the report in the file system, then provide a report file download via the UI... which means a new design and further implementation...
