### ISSUE TITLE
Correct missing escaping of template variable

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4522]
Primarily for getAuthorString and getLocalizedTitle.

PRs:
- `ojs-stable-3_1_1`:
  - https://github.com/pkp/ojs/pull/2308
  - https://github.com/pkp/omp/pull/647
  - https://github.com/pkp/pkp-lib/pull/4530

Patches:
- OJS 3.1.1-4, OJS 3.1.1-2, OJS 3.1.1-1:
  - https://github.com/pkp/ojs/pull/2308/commits/2c219ff0e7a9d378f13739aea5596dcac7d1e208.diff
  - https://github.com/pkp/pkp-lib/pull/4530/commits/48c7f5b6cf1814a438d3a27d03104a77601753f9.diff (`lib/pkp` submodule)
- OJS 3.1.1-0, OJS 3.1.0-1, or OJS 3.1.0-0:
  - https://gist.github.com/asmecher/421e42837919d5e9dd934cf8808b3322/raw/3fcd714d0907881dca3cec9c3903f116ef3f3a32/i4522-ojs-3_1_1-0.diff
  - https://github.com/pkp/pkp-lib/pull/4530/commits/48c7f5b6cf1814a438d3a27d03104a77601753f9.diff (`lib/pkp` submodule)
- OJS 3.0.2-0, OJS 3.0.1-0:
  - https://gist.github.com/asmecher/421e42837919d5e9dd934cf8808b3322/raw/3fcd714d0907881dca3cec9c3903f116ef3f3a32/i4522-ojs-3_1_1-0.diff
  - https://gist.github.com/asmecher/a5298d24d4711c616b4da3d61b745d17/raw/c41417d139068de25bbd3510788f798ab369b293/i4522-ojs-3_0_2-0-lib-pkp.diff (`lib/pkp` submodule)
- OJS 3.0.0-0:
  - This release may be affected. Rather than back-porting the patch,we recommend upgrading.

**Comment by mfelczak** [comment]
Hi @asmecher, to help us with patching, would you be able to commit the gists above to their respective ojs-stable-* branches?

**Comment by asmecher** [comment]
I've just cherry-picked/committed all the way back to 3.0.1.

**Comment by mfelczak** [comment]
Thanks @asmecher!
