### ISSUE TITLE
Frontend archive listing and backend archive listing ordered with different logic

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4523]
Hi,

Since this change https://github.com/pkp/ojs/blob/master/pages/issue/IssueHandler.inc.php#L132 the frontend issue listing has been ordered only according to the seq setting. 

It seems that there is no fallback, so if seq is missing the order is random. Or at least the fallback is not the pubdate as it used to be.

In the backend the listing still uses pubdate as a fallback.

The result is that for issue archives that have no seq it seems in the backend that the order is ok, but on the frontend the order is random. Editors do not understand that they should save the order again in the background to get seq stored to the db. Since we upgraded to 3.1.1.4 which probably introduced this change, I have been contacted by about ten journals that their archive is in random order and they do not know what to do.

The best solution would be that the frontend listing would fallback to the pubdate if seq is missing.

**Comment by asmecher** [comment]
@ajnyga, are you dealing with data where `seq` is `0` for multiple issues (unless a manual re-order kicks off resequencing)?

**Comment by ajnyga** [comment]
Imports do not usually get seq I think. 

Seq is missing from the custom_issue_order table.

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.
