### ISSUE TITLE
Update list of countries

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#4526]
`countries.xml` contains a list of countries. For pragmatic reasons, this is based on an ISO standard. The files say:

>   * Localized list of countries. Based on ISO 3166-1:2006.

The ISO standard has been updated, so maybe both the comment and the content of that file should be revised.

See https://www.iso.org/standard/39719.html and https://www.iso.org/standard/63545.html.

**Comment by asmecher** [comment]
This is now taken from a 3rd-party libary, so a composer update will take care of this automagically.
