### ISSUE TITLE
[OJS] Suggestions for the plugin section

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#4534]
**Comments based on the master branch** 
- Sorting the plugin list by name would be nice, since sometimes they move their positions after being updated
- I think the search feature should be made on the client-side or be removed in favor of Ctrl+F (if there's no paging). Or maybe instead of searching, maybe the user could mark what he uses often with a "star" (which would change the position of the plugin to the top/make it appear in favorites tab)
- I found strange that I can't disable some plugins, but I can remove them
- Avoid submitting forms with errors on the client-side
- Find a way to offer a reliable "Update available!"
- Hide the categories which have no plugins under them
- As a new user, I found out that the expanding/collapsing to access the options is a bit annoying, also I missed seeing all the available options of a plugin without being required to expand and enable it

**Comment by asmecher** [comment]
> I found strange that I can't disable some plugins, but I can remove them
The plugins that can't be disabled are ones that don't have any effect unless they're invoked manually, e.g. the import/export plugins, which need to be clicked from the list. I suppose it would be possible to add enable/disable controls for plugins like this but it would only result in e.g. the plugin not being listed in the import/export list.
