### ISSUE TITLE
Public URL Identifier breaks with a slash character

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4542]
In 3.1.x, entering a slash into the Public URL Identifier breaks the page routing.

Steps to reproduce (OJS 3.1.2):

- Schedule a Submission against an Issue
- In the Submission Metadata, assign a Public URL Identifier of "test/123"
- Preview the Issue
- Click on the link to the Submission

Results:
HTTP 404

**Comment by asmecher** [comment]
@ctgraham, this is an Apache configuration issue. See http://httpd.apache.org/docs/current/mod/core.html#allowencodedslashes for details. I don't think this is part of a specification, just a decision by the folks at Apache.

**Comment by ctgraham** [comment]
Yes(ish).  But in my experience, `AllowEncodedSlashes` Off provides the expected Apache 404; `AllowEncodedSlashes` On passes an unexpected array to `ArticleHandler:initialize()`, generating an OJS 404; and, `AllowEncodedSlashes` NoDecode passes an escaped string to `ArticleHandler:initialize()`, which doesn't match the ID, and generates an OJS 404.

What is the expected working condition?

**Comment by asmecher** [comment]
Hrm, I'm using lighttpd and the PHP internal server over here, so I don't have an Apache setup to tinker with. But I'd expect encoded slashes to be passed into the arguments array, rather than treated as a `/` separator.

**Comment by ctgraham** [comment]
Confirmed in Apache 2.2 and Apache 2.4.

`AllowEncodedSlashes On`:
```
File: /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.inc.php line 387
Function: ArticleHandler->initialize(Object(Request), Array(2))
```
`Array(2)` is `array ( 0 => 'test', 1 => '1234', )`.

`AllowEncodedSlashes NoDecode`:
```
File: /var/www/html/ojs/lib/pkp/classes/core/PKPRouter.inc.php line 387
Function: ArticleHandler->initialize(Object(Request), Array(1))
```
`Array(1)` is `array ( 0 => 'test%2F1234', )`.

In lighthttpd and the PHP internal server the value of the `Array(1)` is `array ( 0 => 'test/1234', )` ?

**Comment by asmecher** [comment]
Ah, looks like Lighttpd has the same issue -- tracked this down to https://redmine.lighttpd.net/issues/2340. And from there, the CGI spec apparently says that `PATH_INFO` should not be urlencoded. On second thought, since we can be pretty sure nobody's relying on this, maybe it would be better to overtly disallow that character.

**Comment by asmecher** [comment]
Merged both PRs, thanks!
