### ISSUE TITLE
Vue Vtooltip stays open even if you change settings tab

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4555]
The vtooltip used in the new settings forms is sticky. It will only close by clicking the tooltip icon again, it will even stay open when switching to other settings tabs.

Expected behaviour would be that it would close when clicked outside the tooltip box. 

However, it seems that `defaultTrigger` `click` does not allow alternative closing actions. The only solution would be to use `defaultTrigger` `manual` which allows to define separate opening and closing methods.

ping @NateWr

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
