### ISSUE TITLE
Auto-assign editors to discussions that they reply to

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4556]
At the moment editors can see and reply to all discussions regardless if they are participants in those discussions.

This leads to situations where the editor does not get any notifications for new replies in those discussions.

I suggest that once an editor participates in a discussions, she is automatically assigned as participant in that discussion.

We could also discuss whether editors who are not stage participants should be allowed to participate in discussions at all? I mean we could just allow them to see what is happening there, but require them to be stage participants to write replies.

@NateWr @asmecher @jmacgreg  thoughts?

**Comment by NateWr** [comment]
I like auto-assign on participation. Ideally, a quick opt-in where they click a button to join the conversation before replying. But either one is good.

**Comment by ajnyga** [comment]
Do you mean a checkbox just before the send button? Would we otherwise prevent editors from answering to the message, I mean if they do not opt-in?

Or did you think a separate modal window that opens when you click "Add message"? Something like "You will be added as a participant in this discussion. Ok Cancel".

**Comment by NateWr** [comment]
I would say just do the auto opt-in. I was thinking something like a "Join Conversation" button that, when clicked, shows the reply area. But let's not get bogged down in the UX of it for now. :)

**Comment by ajnyga** [comment]
Ok!

**Comment by ajnyga** [comment]
the 3.1.2 train is probably already gone? So I will pr against master?

**Comment by NateWr** [comment]
:+1:

**Comment by ajnyga** [comment]
ojs: https://github.com/pkp/ojs/pull/2318
pkp-lib: https://github.com/pkp/pkp-lib/pull/4559

**Comment by ajnyga** [comment]
ping @NateWr / @asmecher test passed if you want to review

**Comment by asmecher** [comment]
OJS 3.1.2 hasn't gone out yet -- soon. But I wonder if there isn't a use case e.g. for managing editors to use conversations to delegate work to others, that they legitimately don't want to be part of. For example, editor spots problem in layout version, then creates a discussion for author and layout editor to resolve it, but doesn't want to be copied.

To accommodate that, I would suggest having the checkbox for the current user pre-checked when a discussion is created, but allowing the user the option of un-checking it when filling in the form. (This may already be the case?)

**Comment by ajnyga** [comment]
They can always remove themselves from the discussion if they want?

In general I think it is a bit of a bad practice that we allow editors without a stage assignment to participate in discussions.

**Comment by ajnyga** [comment]
Oh and to clarify, the current situation is that if an editor without a stage assignment creates a totally new discussion, they are included in the participants list. They can remove the selection from their checkbox if they want.

However, if for example the is a discussion created by the author and the editor is not participant in that discussion, the editor can still answer the discussion but does not become a participant. Meaning that they do not get notified of new messages.

**Comment by NateWr** [comment]
I kind of agree that anyone making a contribution to a discussion (new or reply) should be opted into it, and they should have to opt out of it if they don't want. That follows the patterns I'm aware of in other workflow/task management software, like GitHub, Trello or Slack (obviously weighted towards techies).

That said, I think Alec's use-case is common. It's good to know that, as is, editors can opt out even as they create a discussion. But there is probably good justification for us to make it easier to leave or mute a discussion. 

I've filed a separate issue for that: https://github.com/pkp/pkp-lib/issues/4568.

**Comment by ajnyga** [comment]
Ok, so if we do not want automatic opt-in when editor replies to a discussion, then should we have the checkbox alternative?

I mean in the form that is used to answer a discussion, we could have:
`[] Notify me when someone replies to this discussion`

This would be visible if the user is not yet a participant in the discussion and it would be hidden if the editor is already a participant or has opted out from ALL discussion notifications in their user settings.

This would allow editors to participate in the discussion and opt-out from being added to the participants list if they wanted. 

This does not however cover #4568, namely the situation where the editor wants to opt-out without answering the discussion. That opt-out mechanism I would somehow place to the grid. We could even have mute button for all users visible in the grid, but have not thought through all the implications. Also worth thinking is that whether muting a discussions is the same thing as removing yourself from the participants list or something different?

**Comment by NateWr** [comment]
> Ok, so if we do not want automatic opt-in when editor replies to a discussion, then should we have the checkbox alternative?

I think we do want to opt them in when they reply to a discussion. We also want to provide an easier way for them to opt out.

Instead of adding the opt out to the grid, let's add a "Leave Discussion" button on the right in the row of buttons at the bottom of the discussion modal.

**Comment by ajnyga** [comment]
@NateWr how about this:

<img width="804" alt="Screen Shot 2019-03-21 at 19 16 49" src="https://user-images.githubusercontent.com/16347527/54771437-f29a6000-4c0d-11e9-927b-28441582f54a.png">

**Comment by NateWr** [comment]
:+1: Can you use a `.pkp_button_link_offset` instead to make it less prominent? I'm also worried about the split positioning. Can we try all buttons aligned on the left, like this:

```
[ Add Message ]   Leave Discussion
```

**Comment by ajnyga** [comment]
sure
note that currently the Add message button is on the right

**Comment by ajnyga** [comment]
I will do a pr later today, but started thinking: do some editors think that using the "Leave discussion" button means closing the modal window?

So it is probably a good idea to a separate confirmationModal that says "Leaving this discussion means that you will not be notified of new messages" (feel free to revise)

**Comment by ajnyga** [comment]
@NateWr see these changes: https://github.com/pkp/pkp-lib/pull/4559/files

Those changes now include the auto assign code and the leave query button. The button is only visible for editors at the moment, but started to think whether it should be visible for all? 

What is currently not working is that once you click the button and click OK for the confirmation, the query modal window should close I think. I just could not figure out an easy way of doing that and thought that you probably know an easy solution? 

(also while writing this I realized that the button should first check if the user is assigned to the discussion, but I can add that easily, the javascript part for closing the modal is another thing)

If you can help me with that, I can add the last changes and start tests?

**Comment by NateWr** [comment]
> So it is probably a good idea to a separate confirmationModal 

:+1:  Here's some text: "If you leave this conversation you will no longer be notified of new messages. Would you like to leave the conversation?"

> The button is only visible for editors at the moment

Yes, let's leave it like that for now.

> the button should first check if the user is assigned to the discussion

:+1: Also, it shouldn't be possible to leave a discussion that is only between the editor and one other participant. Otherwise we will end up with orphaned discussions where an author can write a message but no one receives it.

> once you click the button and click OK for the confirmation, the query modal window should close I think

You can pass a global event to with the JSON response and then listen for that. 

https://github.com/pkp/pkp-lib/pull/4559/files#diff-50bd16539ef6ac24ae91e96f90d70c6aR559
```
$json = new JSONMessage();
$json->setGlobalEvent('user-left-discussion');
return $json;
```

Then, in `ReadQueryHandler.js` (probably the constructor), you would listen to the global event and close the modal when it fires. Something like this (just off the top of my head):

```
this.bindGlobal('user-left-discussion', this.closeModal);
```

**Comment by ajnyga** [comment]
thanks, that is pretty much the javascript I tried. But I got an error saying that closeModal is not a function. I think the problem there is that "this" is not a reference to the modal window, or something?

But I will add the things you suggested and let you know what exactly happens with the js.

**Comment by ajnyga** [comment]
yeah, with that I get` Uncaught TypeError: Cannot read property 'user-left-discussion' of null`

**Comment by NateWr** [comment]
can you share the actual code you've got? `user-left-discussion` is not a property in the code I shared above.

You might also need to use the wrapper... I think something like this:

```
this.bindGlobal('user-left-discussion', this.callbackWrapper(this.closeModal));
```

Although I don't see it on any of the other `bindGlobal` calls. Maybe just share your full code and I'll take a look.

**Comment by ajnyga** [comment]
Here:

https://github.com/pkp/pkp-lib/pull/4559/files#diff-50bd16539ef6ac24ae91e96f90d70c6aR560

https://github.com/pkp/pkp-lib/pull/4559/files#diff-13929f6279b5503c29c948a69b582b87R48

Maybe I am missing somethin obvious.

**Comment by ajnyga** [comment]
hmm it should probably be this.modalClose

**Comment by ajnyga** [comment]
Because if I am understanding this right, the js there extends $.pkp.classes.Handler and it should extend $.pkp.controllers.modal.ModalHandler for that to work?

**Comment by NateWr** [comment]
Ahh, I see, you're right, `ReadQueryHandler.js` is not the modal itself. It's inside the modal. So another approach you can take is to trigger an event and let it bubble up to the parent modal. It would be something like this:

```
this.bindGlobal('user-left-discussion', function() {
  this.getHtmlElement().trigger('modalFinished');
});
```

If that doesn't work, you could try firing the event on the parent, like `this.getHtmlElement().parent().trigger(...)`.

**Comment by ajnyga** [comment]
```
this.bindGlobal('user-left-discussion', function() {
  this.getHtmlElement().trigger('modalFinished');
});
```

and

```
this.bindGlobal('user-left-discussion', function() {
  this.getHtmlElement().parent().trigger('modalFinished');
});
```

both gave me

`Uncaught TypeError: Cannot read property 'user-left-discussion' of null`

**Comment by ajnyga** [comment]
wuhuu!

The winning combination is:

```
		$containerElement.bind('user-left-discussion', function() {
			$containerElement.parent().trigger('modalFinished');
		});
```

**Comment by ajnyga** [comment]
Hi @NateWr @asmecher 

The latest version is now here: https://github.com/pkp/pkp-lib/pull/4559/files

The code now shows the "Leave discussion" button for editors, if they are participants in the current query and there are more than two participants.  Clicking the button will remove the editor from the query and closes the modal.

The code will also automatically assign an user that answers a query but is not a current participant. This means that editors that answer queries are assigned as query participants (the original issue here).

**What is missing**: the Gods of jQuery have not been in a good mood today. Currently if you manually edit the participants (push the edit button next to the participants list) and add the current editor user as a participant, the "Leave query" button will not appear. 

I tried several things but could not get it working. For example adding 

```
$json = new JSONMessage();
$json->setEvent('dataChanged', array($query->getId()));
$json->setEvent('toggle-leave-query-button', $toggleLeaveQueryButton);
return $json;
```
here https://github.com/pkp/pkp-lib/blob/master/controllers/grid/queries/QueriesGridHandler.inc.php#L508

and then adding a bind here https://github.com/pkp/pkp-lib/blob/master/js/controllers/grid/queries/ReadQueryHandler.js#L42 

But I am obviously missing something fundamental on how the query forms there work. My event is not getting through and it is neither getting through with `setGlobalEvent`. 

So any suggestions on how to achieve that are welcome.

**Comment by NateWr** [comment]
The participants list is loaded in with a separate request that is handled here: https://github.com/pkp/pkp-lib/blob/master/controllers/grid/queries/QueriesGridHandler.inc.php#L441. I _think_ you could try passing an event back with that request like this:

```
$json->setEvent('participantsChanged', [array-of-participant-ids])
```

Then in the constructor for `ReadQueryHandler.js` you should be able to do something like:

```
$containerElement.bind('participantsChanged',
this.callbackWrapper(this.maybeHideLeaveButton_));
```

You can inspect the JSON response directly in this code: https://github.com/pkp/pkp-lib/blob/master/js/controllers/grid/queries/ReadQueryHandler.js#L129-L139.

(Also, if you're not familiar with it, I encourage you to explore the Network tab in your browser developer tools. You can restrict it to XHR requests and look at the exact response that comes back. This helps cut out a lot of confusion -- but not all of it. :) ).

**Comment by ajnyga** [comment]
hmm, with 

```
		$json = new JSONMessage();
		$json->setStatus(true);
		$json->setContent($templateMgr->fetch('controllers/grid/queries/participants.tpl'));
		$json->setEvent('participantsChanged', $participants);
		return $json;
```

I get
 ```
Handler.js:622 Uncaught TypeError: Cannot read property 'triggerHandler' of null
    at proxyConstructor.$.pkp.classes.Handler.trigger (Handler.js:622)
```

**Comment by ajnyga** [comment]
but it seems that I can do

```
		$json = new JSONMessage();
		$json->setStatus(true);
		$json->setContent($templateMgr->fetch('controllers/grid/queries/participants.tpl'));
		**$json->setAdditionalAttributes(array('toggleLeaveQuery' => true));**
		return $json;
```

**Comment by ajnyga** [comment]
@asmecher @NateWr running tests:

https://github.com/pkp/ojs/pull/2318
https://github.com/pkp/pkp-lib/pull/4559

**Comment by ajnyga** [comment]
thanks @NateWr for the review, I will do the changes tomorrow!

**Comment by ajnyga** [comment]
tests failed, but no idea what it is about.

**Comment by ajnyga** [comment]
going to try the test again now...

**Comment by ajnyga** [comment]
@NateWr tests passed now
ojs: https://github.com/pkp/ojs/pull/2318
lib: https://github.com/pkp/pkp-lib/pull/4559

**Comment by NateWr** [comment]
:+1: Merged. Thanks @ajnyga!
