### ISSUE TITLE
Submission file permissions and multiple author stage assignments

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4558]
OJS supports the feature that a single submissions has multiple author stage assignments. 

However, if author1 uploads a file to the system, author2 can not upload a new version of that same file because of file permissions.

Should we relax this check so that instead of checking to whom the file belongs to, we would check that the uploading user has the required stage assignment to upload a new version.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
