### ISSUE TITLE
Disabled plugins when upgrading from OJS 2.4.8 

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4563]
In a testing upgrade some plugins were not enabled by default:

- Dublin  Core Indexing Plugin
- Google Scholar Indexing Plugin
- Block plugins

**Comment by asmecher** [comment]
See https://github.com/pkp/pkp-lib/issues/4561 for the GS and Dublin Core plugins. For block plugins, there's a default set that's enabled by default, and others are intentionally left available but disabled. Are there some in particular you expect to see enabled by default?

**Comment by israelcefrin** [comment]
Hi Alec,

Thanks for the update.  No special reason for the Block plugin, it is just a report regarding plugins when upgrading a real client. First two plugins are a kind of required be enabled (at least I always enabled them if they aren't so in a fresh install).

Cheers,
Israel

**Comment by asmecher** [comment]
OK -- in that case, I think this is resolved in #4561.
