### ISSUE TITLE
QuickSubmit Error

### ISSUE THREAD

**Issue by hrace009** [pkp/pkp-lib#4564]
I just installed quick submit and got this fatal Error:

`[01-Mar-2019 09:41:22 Asia/Jakarta] PHP Fatal error:  Call to undefined method TemplateManager::registerPlugin() in /plugins/importexport/quickSubmit/QuickSubmitPlugin.inc.php on line 63`
OJS version: 3.1.1.4 (January 7, 2019 - 10:49 AM)

please help.

Thank you

**Comment by asmecher** [comment]
@hrace009, you've probably installed the wrong version of the plugin for your version of OJS. Best to install it via the Plugin Gallery inside OJS, or to download the appropriate version from the "Releases" area of the git repository.

**Comment by hrace009** [comment]
i used this one, https://github.com/pkp/quickSubmit

**Comment by hrace009** [comment]
can you tell me witch version should i used?

**Comment by hrace009** [comment]
@asmecher btw, i never seen plugin gallery inside OJS

**Comment by hrace009** [comment]
Where i can find plugin gallery here?
![image](https://user-images.githubusercontent.com/7691118/53713502-ab764600-3e7d-11e9-8a52-400f26c96057.png)

**Comment by asmecher** [comment]
@hrace009, you can find the Plugin Gallery in Settings > Website > Plugins. If you're logged in as an administrator, you can install plugins directly from there.

**Comment by ViRuSTriNiTy** [comment]
> @hrace009, you can find the Plugin Gallery in Settings > Website > Plugins. If you're logged in as an administrator, you can install plugins directly from there.

... or click **Site Settings** and then navigate to the **Plugins** tab to enabled / disable a plugin for the whole site.

**Comment by hrace009** [comment]
![image](https://user-images.githubusercontent.com/7691118/53776516-dec1df00-3f28-11e9-9226-d5dabae50604.png)
![image](https://user-images.githubusercontent.com/7691118/53776546-eda89180-3f28-11e9-88bb-174782781aed.png)
![image](https://user-images.githubusercontent.com/7691118/53776557-f600cc80-3f28-11e9-88ef-0a819816f7ed.png)
![image](https://user-images.githubusercontent.com/7691118/53776566-fd27da80-3f28-11e9-98f4-fce7fb338b73.png)
@asmecher @ViRuSTriNiTy 
i don't see quicksubmit plugin or plugin gallery here. i only seen currently installed plugin

**Comment by hrace009** [comment]
@ViRuSTriNiTy 
i wanted to install quicksubmit plugin, not enable or disable plugin.

**Comment by hrace009** [comment]
`[05-Mar-2019 11:51:20 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined method Application::getMetadataFields() in /journalv3/plugins/importexport/quickSubmit/QuickSubmitForm.inc.php:104
Stack trace:
#0 /journalv3/plugins/importexport/quickSubmit/QuickSubmitPlugin.inc.php(88): QuickSubmitForm->display(false)
#1 /journalv3/lib/pkp/pages/management/PKPToolsHandler.inc.php(98): QuickSubmitPlugin->display(Array, Object(Request))
#2 /journalv3/lib/pkp/classes/core/PKPRouter.inc.php(390): PKPToolsHandler->importexport(Array, Object(Request))
#3 /journalv3/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#4 /journalv3/lib/pkp/classes/core/Dispatcher.inc.php(134): PKPPageRouter->route(Object(Request))
#5 /journalv3/lib/pkp/classes/core/PKPApplication.inc.php(252): Dispatcher->dispatch(Object(Request))
#6 /h in /journalv3/plugins/importexport/quickSubmit/QuickSubmitForm.inc.php on line 104`

I have upgrade OJS to latest version: 3.1.2.0 (February 28, 2019) and trying to resintall QuickSubmit plugin, and when i go to as Journal Manager **TOOLS > IMPORT & EXPORT > QuickSubmit Plugin** i got white screen, and that message show in the error LOG.

**Comment by hrace009** [comment]
and how do i reopen this case? since it not solving my problem 👎

**Comment by hrace009** [comment]
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/gvFYqK2l3Ks/0.jpg)](https://www.youtube.com/watch?v=gvFYqK2l3Ks)

**Comment by asmecher** [comment]
@hrace009, the problem you're encountering is [caused by installing the wrong version of the plugin](https://github.com/pkp/pkp-lib/issues/4564#issuecomment-468552920). The solution is to install the correct version, [e.g. from the Plugin Gallery](https://github.com/pkp/pkp-lib/issues/4564#issuecomment-469323988). First you'll have to manually remove the incorrect version you installed, by deleting `plugins/importexport/quickSubmit` and its contents.

**Comment by hrace009** [comment]
@asmecher you not watch video that i have shared.
Please take a look https://youtu.be/gvFYqK2l3Ks

i can't install or uninstall plugin at plugin gallery

**Comment by asmecher** [comment]
Did you try deleting the directory I suggested above?

**Comment by hrace009** [comment]
i have delete it. and i am the administrator can't install the plugin from plugin gallery

**Comment by hrace009** [comment]
i have try everything you suggest, but no result

**Comment by hrace009** [comment]
i only have this at my administration dashboard
![image](https://user-images.githubusercontent.com/7691118/53847373-12f9d600-3fe3-11e9-8383-77dc9e1be7cc.png)

**Comment by asmecher** [comment]
@hrace009, it looks like you're going to the Plugin Gallery with a Journal Manager user, not a Site Administrator user. Log in as a user with a Site Administer role, then go to the Plugin Gallery and view the QuickSubmit plugin.

**Comment by hrace009** [comment]
@asmecher i login with journal manager or site administrator, it give the same view! and when i login with site administrator i don't have plugin gallery on my dashboard.

can you watch the video i shared? can you get it?

**Comment by hrace009** [comment]
i'am the one who installed this OJS for the lecture. and my ID is the ID #1 (SITE ADMINISTRATOR)
when the first time i install that OJS, it give that menu for me!

**Comment by asmecher** [comment]
@hrace009, I have watched your video. When you log in as a Site Administrator, you go only to Administration, not to Dashboard > Settings > Website > Plugins > Plugin Gallery. (If you don't see "Settings" when you get to your dashboard, you may need to choose a journal from the top-left drop-down.)

The Plugin Gallery is currently only available through Settings > Website > Plugins, not Administration. In order to be able to install a plugin, you must be logged in as an account that has a Site Administrator role.

**Comment by moherhayem** [comment]
I have an issue when i use quick submit. it shows white page without processing of submission ..  
. management/importexport/plugin/QuickSubmitPlugin/saveSubmit
I upgrade it but not working.
what should we do?

**Comment by asmecher** [comment]
@moherhayem, could you post instead on our support forum (https://forum.pkp.sfu.ca)? Include what version of OJS you're using, and whether you found anything relevant in the PHP error log.
