### ISSUE TITLE
XML-imported issues are missing the option to be set to 'current'

### ISSUE THREAD

**Issue by heike-r** [pkp/pkp-lib#4566]
We are using OJS 3.1.0.1
For one journal, we imported all issues via the xml native import and we noticed, that the option to set the current issue (dashboard, in the back issue gallery) is not there for all of them. So, the last imported issue is now the 'current' one and we can not change it.

The same has been reported here [https://forum.pkp.sfu.ca/t/ojs3-cannot-choose-current-issue-after-import/49540] last October, but there where no replies.

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.
