### ISSUE TITLE
OJS 3.1.2 Empty section policy in submission step 1

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4570]
Scenario: only one section in a journal and no section policy given to that section. The submission form step 1 shows an empty Section policy title:

<img width="517" alt="screen shot 2019-03-05 at 10 51 11" src="https://user-images.githubusercontent.com/16347527/53792632-cbb50c00-3f34-11e9-900e-672c190ff081.png">

**Comment by NateWr** [comment]
PR
https://github.com/pkp/ojs/pull/2387 (master)
https://github.com/pkp/ojs/pull/2388 (stable)

**Comment by NateWr** [comment]
Merged.
