### ISSUE TITLE
OMP 3.1.2 Call to undefined method SiteSetupForm::getFormLocale() 

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4571]
Getting this error when trying to save site settings form in OMP 3.1.2
`PHP Fatal error:  Uncaught Error: Call to undefined method SiteSetupForm::getFormLocale() in lib/pkp/classes/admin/form/PKPSiteSettingsForm.inc.php:135`

This is a totally new install.

**Comment by ajnyga** [comment]
Should be `getDefaultFormLocale`?

**Comment by ajnyga** [comment]
OJS: https://github.com/pkp/ojs/pull/2328 (just submodule)
pkp-lib: https://github.com/pkp/pkp-lib/pull/4586

**Comment by asmecher** [comment]
(The `master` branch does not need any changes. Thanks, @ajnyga!)
