### ISSUE TITLE
OMP 3.1.2 about/submissions gives Unknown locale component 259 error

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4572]
Opening that public page gives an error. 

Probably because of this section of code here: https://github.com/pkp/pkp-lib/blob/stable-3_1_2/pages/about/AboutContextHandler.inc.php#L89-L97

That looks like OJS specific code in the shared library? There are no sections in OMP right?

**Comment by ajnyga** [comment]
Probably these changes created the problem: https://github.com/pkp/pkp-lib/issues/2638

**Comment by NateWr** [comment]
OMP has Series which I believe are just an extended class of Sections. But still that code is probably not correct for OMP.

**Comment by asmecher** [comment]
This only applies to presses with no series that can be submitted to. The attached patch should fix it.
