### ISSUE TITLE
"Smarty: Unable to load template" fatal errors

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4576]
`PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'app:plugins/generic/pdfJsViewer/templates/display.tpl' <-- \n  thrown in /lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195, referer: http://myomptest.com/index.php/test/catalog/book/2
`
[Ed: Also applies to web feed plugin, payment settings forms, ONIX and CSV exports, with various template names in the error message. -AS]

**Comment by NateWr** [comment]
Are you sure that you have updated that plugin to the appropriate commit for 3.1.2? If you're running OMP off of git, you may need to run `git submodule update --init --recursive`.

**Comment by ajnyga** [comment]
I downloaded OMP 3.1.2 from the PKP website and installed that.

**Comment by ajnyga** [comment]
OMP has it's own pdf.js plugin: https://github.com/pkp/omp/tree/stable-3_1_2/plugins/generic/pdfJsViewer

**Comment by asmecher** [comment]
@ajnyga, looks like I missed a grep/replace when doing the Smarty3 updates, and some important parts of OMP didn't get testing before release. Try applying https://github.com/pkp/omp/commit/cccc763e2afdf2e9c8fc360c81ac46f9c7f5721b to correct the errors. This will likely mean an OMP 3.1.2-1 build sooner rather than later, but I'd like to give a little more time for early feedback before we do that. Thanks for reporting!

**Comment by ajnyga** [comment]
I think I tried that already and did not work, but will check again

**Comment by ajnyga** [comment]
works, thanks!

**Comment by ajnyga** [comment]
One thing I noticed. The CSV plugin calls for a index.tpl file, but I can not find such file in the directory. It seems that it has never been there since 1.0. Does that only work from command line? 

https://github.com/pkp/omp/blob/stable-3_1_2/plugins/importexport/csv/CSVImportExportPlugin.inc.php#L70****

**Comment by asmecher** [comment]
Ah -- yes, it's command-line only. That's filed for change over at https://github.com/pkp/pkp-lib/issues/1352.

**Comment by asmecher** [comment]
@jorgenavarrobeltran, can you describe what changes you made?
