### ISSUE TITLE
OMP 3.1.2 Information block plugin has a link that leads to 404

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4579]
The information block plugin in OMP has a link called `Notifications` https://github.com/pkp/omp/blob/master/plugins/blocks/information/templates/block.tpl#L41 that leads to a 404 page.

Looks like it has been there since OMP 1.2

**Comment by NateWr** [comment]
This page is deprecated and the link should be removed.

**Comment by ajnyga** [comment]
Hi, I did not run the tests since this is a very minor pr: https://github.com/pkp/omp/pull/652

**Comment by NateWr** [comment]
Gracias. Do you mind opening a PR that just stages your commit against `stable-3_1_2`? That will ensure it goes out with 3.1.2-1.

**Comment by ajnyga** [comment]
https://github.com/pkp/omp/pull/653
