### ISSUE TITLE
No translation for TinyMCE 3.x editor in pkp-lib 2.x

### ISSUE THREAD

**Issue by atremba** [pkp/pkp-lib#458]
The TinyMCE library (`lib/tinymce/jscripts/tiny_mce`, version 3.x) lacks all translations except the English one. This is quite inconvenient, as TinyMCE plugin is turned on by default, having all buttons and fields in TinyMCE dialogs are in  `{#cancel}`-like form.

The translation for the TinyMCE 3.x is provided by multiple files stored in multiple `langs` folders, and are available for download http://www.tinymce.com/i18n3x/index.php?ctrl=lang&act=download&pr_id=1
The most translations are not full, there are non-localized plugins in 3.x (it is TinyMCE development bug/fail). Nevertheless main function of TinyMCE is localized for many languages.

Should the translation packs be provided (in its current state, as is) in pkp-lib package or are they intended to be installed manually?

**Comment by asmecher** [comment]
@atremba, an additional complication is that we're using Composer to manage dependencies, and I don't think anyone has packaged up the translations for Composer. I'd suggest asking TinyMCE how they recommend working with translations and Composer...

**Comment by atremba** [comment]
Dear Alec. As far as I understand, the Composer is used in planned OJS 3.0, while OJS 2.4.x branches still use old TinyMCE 3.4.9, provided with distribution pack direclty, so adding translations would be technically simple. Or the OJS 2.4.x also implicitly uses Composer?

On the other hand as translation of TinyMCE 3.4.9 is still partial for almost all languages, thus upgrading to TinyMCE 4.x in OJS 2.4.x branches may be considered as well.

**Comment by asmecher** [comment]
@atremba, sorry, I misread the TinyMCE version as the OJS version.

Yes, we could merge the translation packs for TinyMCE 3.x into the OJS 2.4.x repo -- would you mind sending a pull request in? It doesn't solve our problem for OJS 3.0 and Composer, but is a good interim solution.

**Comment by atremba** [comment]
Yes, I'll prepare the pull request in a couple of days. Is it right that the OJS target would be **ojs-dev-2.4** branch (which at some moment become OJS 2.4.7)? 

And if some contribution is to be applied to OJS 3.0 release, it should be pulled into **master** branch?

**Comment by asmecher** [comment]
Yes, ojs-dev-2_4 is the branch to submit against. The ojs-dev-2_4 branch will be released as OJS 2.4.7 (we'll create an ojs-stable-2_4_7 branch at the point of release); the master branch is what will eventually be released as OJS 3.0b and then 3.0. Thanks!

**Comment by asmecher** [comment]
@atremba, thanks -- I've given this some thought and decided to merge in your PR for the OJS 2.4.x line. We'll need to take a different approach for OJS 3.x, but while it adds a little bloat, this is an easy solution and disk space is relatively cheap. Thanks for contributing!
