### ISSUE TITLE
[OJS] OJS 3.1.2 Wrong header in default/styles/pages/indexSite.less

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#4580]
Cosmetic change: The header part of default/styles/pages/indexSite.less was copied over from default/styles/pages/indexJournal.less . file, brief and link should be corrected.

**Comment by mpbraendle** [comment]
The same is true for plugins/themes/default/styles/pages/category.less , where the header was copied over from plugins/themes/default/styles/pages/contact.less

**Comment by asmecher** [comment]
Fixed, thanks!
