### ISSUE TITLE
Missing escaping in submission checklist

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#4584]
The labels for items of the submission checklist are not escaped.

See also #4522.

**Comment by asmecher** [comment]
Thanks, @ptrckb, I see the PR adding the submodule update: https://github.com/pkp/ojs/pull/2326
Can you also add a PR to pkp/pkp-lib for the change?

**Comment by ptrckb** [comment]
@asmecher PR pkp/pkp-lib#4589

**Comment by asmecher** [comment]
Thanks, @ptrckb -- merged to `stable-3_1_2`, and forward-ported manually to `master`.
