### ISSUE TITLE
"Mark Registered" in Crossref Plugin ineffectual 

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#459]
If I pull up the list of all "unregistered articles" in the crossref plugin and select "mark as registered", it doesn't actually appear to do that at all. Clicking on "unregistered articles" seems to always pull up a full list of all articles, even ones already submitted to crossref and marked as such.

**Comment by asmecher** [comment]
@AhemNason, I can't duplicate this behavior locally -- selecting an unregistered article and marking it registered moves the submission out of the unregistered list. Do you have a DB dump you could send me? What version of OJS are you working with?

**Comment by AhemNason** [comment]
Hey @asmecher , this didn't actually end up being the real issue here anyway, which I know we've talked about in detail out of this issue text. The biggest problem with "mark as registered" is that it actually assigned DOIs to articles that didn't have them, using OJS's default DOI pattern. 

I assumed it would actually just remove it from the "unsubmitted list" and nothing else. I wasn't expecting it to give everything DOIs. 

> This issue as originally reported is sort of problematic... I think we sort of discovered a bug within a bug.

**Comment by asmecher** [comment]
@AhemNason, @jmacgreg -- what do you guys suggest we do with this WRT OJS 2.4.7?

**Comment by jmacgreg** [comment]
I think this can be closed - @bozana, @AhemNason?

**Comment by bozana** [comment]
Yes, I would say :-)

**Comment by jmacgreg** [comment]
closing!
