### ISSUE TITLE
No parameter substitution in email after selecting another template

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#4590]
When changing the email template in the form for adding a reviewer, the parameters are not replaced in the new template. The parameter names are shown instead.

Tested with OJS 3.1.1-4.

**Comment by ptrckb** [comment]
ojs PR pkp/ojs#2329
pkp-lib PR pkp/pkp-lib#4591

**Comment by asmecher** [comment]
Thanks, @ptrckb! I've merged this and cherry-picked forward to both `stable-3_1_2` and `master`.
