### ISSUE TITLE
OJS 3.1.1-4 to 3.1.2 upgrade problem

### ISSUE THREAD

**Issue by alvgalrus** [pkp/pkp-lib#4592]
Hello.

I've been trying to upgrade our current OJS installation (PHP 5.6 + mysqli) to the latest version. But every time I try, I get an instantaneous blank page. The following warnings are recorded in the error log:

```
[Tue Mar 12 16:25:28.681226 2019] [fcgid:warn] [pid 628390:tid 140653173053184] (104)Connection reset by peer: [client ***] mod_fcgid: error reading data from FastCGI server, referer: index.php/index/install/upgrade
[Tue Mar 12 16:25:28.681305 2019] [core:error] [pid 628390:tid 140653173053184] [client ***] End of script output before headers: index.php, referer: index.php/index/install/upgrade
```

I'm getting the following line when I navigate the between the install pages:

```
[Tue Mar 12 16:26:01.258433 2019] [fcgid:warn] [pid 628390:tid 140653173053184] [client ***] mod_fcgid: stderr: PHP Warning:  Declaration of InstallHandler::validate($request) should be compatible with PKPHandler::validate($requiredContexts = NULL, $request = NULL) in public_html/lib/pkp/pages/install/InstallHandler.inc.php on line 118, referer: index.php/index/install/upgrade
```

The second time I try to run the script I get those other errors (I suppose they are related to garbage left in the database by the first try):

```
[Tue Mar 12 16:26:01.258515 2019] [fcgid:warn] [pid 628390:tid 140653173053184] [client ***] mod_fcgid: stderr: Table 'users_tmp' already exists, referer: index.php/index/install/upgrade
[Tue Mar 12 16:26:01.992040 2019] [fcgid:warn] [pid 628390:tid 140653173053184] [client ***] mod_fcgid: stderr: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in public_html/cache/t_compile/e8ea13aa559bf8604ca823015b397a28d8666486^28682bb3d6b6e750ebd3d458abc8f92b4da9ea9f_0.app.headerusernav.tpl.php on line 136, referer: index.php/index/install/installUpgrade
```

I've tried PHP versions 7.0.x, 7.1.x and 7.2.x with exact same results. I've already set the DB driver to mysqli in the config. The prior OJS 3.1.1-4 doesn't work with PHP 7 either, throwing the following errors:

```
[Tue Mar 12 16:50:50.593547 2019] [fcgid:warn] [pid 628390:tid 140653164660480] (104)Connection reset by peer: [client ***] mod_fcgid: error reading data from FastCGI server
[Tue Mar 12 16:50:50.593739 2019] [core:error] [pid 628390:tid 140653164660480] [client ***] End of script output before headers: index.php
```

Regards.

P.S. We have a custom and pretty lightweight frontend theme installed. But I don't think it has anything to do with this problem.

**Comment by asmecher** [comment]
@alvgalrus, make sure you completely drop and restore your database from backup -- you're correct that trying to re-run an upgrade on a database that already experienced a failed upgrade will cause problems.

Beyond that, I wonder if you're hitting a resource limit in your FastCGI configuration. If it's an option, use the command-line upgrade tool.

The best place to get support is in our support forum -- https://forum.pkp.sfu.ca -- rather than this issue tracker. If something turns out to be a bug, then we'll migrate it here for you. I'd suggest continuing over there (maybe with a link to this issue) to continue, if you haven't resolved this already.
