### ISSUE TITLE
Stats can't process Issues with unique identifiers

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#460]
If an usage event comes with an url using unique identifier, the stats processing tool doesn't count the entry.

**Comment by beghelli** [comment]
Actually this is not an stats bug. It's a DAO bug. For instance, IssueDAO cache miss is not using getIssueByBestId. So, when the stats processing uses getIssueByBestId using cache, the first request for that object hits cache miss but the cache is not filled because the _cacheMiss is trying to retrieve the Issue object using getById, not considering any public id.

**Comment by asmecher** [comment]
Reviewed, thanks!

**Comment by beghelli** [comment]
merged and ported to master
