### ISSUE TITLE
[OJS] Review form problem : authors can always see the entire review form

### ISSUE THREAD

**Issue by Potomac54** [pkp/pkp-lib#4602]
Hello,

I use the last version of OJS (3.1.2),  I created a review form, and I notice (in open review mode) that the author can still read the entire review form when he logs in the site (review tab), this doesn’t seem normal because the checkbox "included in message to author” was not checked for some elements during the creation of the review form,

the checkbox "included in message to author” doesn't seem to have an effect when the review is set to "open mode", author can click on the link "read the review" and then he can see all the elements of the review form, even if this element has the checkbox "included in message to author” unchecked during the creation of the review form.

The bug is present also in the previous version of OJS (3.1.1-4)

**Comment by ajnyga** [comment]
thanks, found the problem and will do a pr soon. It would be good if you could test it.

**Comment by Potomac54** [comment]
Ok I will test the fix

**Comment by ajnyga** [comment]
Hi

One possible solution in this pr. What do you think @asmecher? If that is ok, I can pr against master branch as well.

ojs: https://github.com/pkp/ojs/pull/2331 (submodule only)
pkp-lib: https://github.com/pkp/pkp-lib/pull/4606

This is of course not the only possible solution, we could:
1. edit the `reviewFormResponse.tpl` template and add some new rules there. `AuthorReviewerGridHandler.inc.php` would pass a new variable and we would check `$reviewFormElement->getIncluded()` inside the template. (but moving such logic to templates is a bad practice I think)
2. In reviewFormElementDao and reviewFormResponseDao we could add a new parameter that you could use to control whether to send the all the form fields or just the ones visible for everyone. Then we would use those in AuthorReviewerGridHandler.inc.php and the templates would be left as they are now.

**Comment by asmecher** [comment]
@ajnyga, thanks! I think I would prefer the approach in 2. -- that way the "extra" information would never extend beyond the DAO. We might have future calls to fetch items, e.g. via the API, and it makes sense to restrict return values right where the data is fetched from the DB.

**Comment by ajnyga** [comment]
@asmecher running tests on the new fix

OJS: https://github.com/pkp/ojs/pull/2331  (bara submodule update)
pkp-lib: https://github.com/pkp/pkp-lib/pull/4606

**Comment by ajnyga** [comment]
@Potomac54 try https://github.com/pkp/pkp-lib/pull/4606/files

**Comment by Potomac54** [comment]
Hello Ajnyga,

I tested your commit, it works, author can now see (in open mode review) only the allowed fields in the review form,

thanks

**Comment by asmecher** [comment]
That's great -- thanks, @ajnyga! -- and I've forward-ported to `master` as well.

**Comment by Potomac54** [comment]
I notice an error message when I log  in OJS : 
##api.submissions.unknownError##

Is it related to this new feature ?

when the error occurs it's impossible to do someting in the administration panel

**Comment by Potomac54** [comment]
false alert, all is ok if I close and restart firefox, 

the error message was probably due to a cookie or a problem with sessions variables

**Comment by ajnyga** [comment]
Search the forum with "##api.submissions.unknownError##". There are a quite a few different reasons why it shows up, but I do not think that this change in the code could have affected it.

**Comment by Potomac54** [comment]
I think the message error was due to a cookie or session variable, because my firefox was running for several days with a lot of tabs (including OJS), and for testing I tried to log with different user accounts (who have different rules, author, reviewers etc...) 

if I try with another browser (chromium) then there is no errors, it's ok also if I close and restart firefox

**Comment by seonghobae** [comment]
Hello guys, I have a trouble to make alert review comments what "Included in message to author" field checked when make a decision "Accept" or "Decline" during I using "Double-blinded" mode.
"Accept submission" or "Decline submission" couldn't delivery reviewer's message to author during using "Double-blinded" mode?

**Comment by asmecher** [comment]
@seonghobae, I'd suggest posting your question on our forum at https://forum.pkp.sfu.ca -- that's the best way to get this sort of help.
