### ISSUE TITLE
[OJS] OJS 3.1.2: Translation keys missing in ca_CA and fr_FR user.xml

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#4603]
Translation keys in locale/ca_CA/user.xml and  locale/fr_FR/user.xml are missing or different from locale/en_US/user.xml

(Oxygen XML editor has a nice XML file diff in which text nodes can be exluded from diff -> easy to spot differences on keys only )

**Comment by mpbraendle** [comment]
I'm ready to help with fr_FR translation (although not native French speaker)

**Comment by mpbraendle** [comment]
See https://github.com/pkp/pkp-lib/commit/746c63f7c6e968a0e9c5381888910353f08abe5d for fr_FR

**Comment by asmecher** [comment]
(Tagging @mtub)

**Comment by NateWr** [comment]
Closing this as outdated. We now use [weblate](https://translate.pkp.sfu.ca/) to manage our translations.

**Comment by mpbraendle** [comment]
tx!
