### ISSUE TITLE
Undefined variable when retrieving submission by status

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#4604]
With OJS 3.1.1, using `SubmissionDAO`'s `getByStatus()` triggers an error for an undefined variable in `getSearchWhere()`.

629e7ecc8b25429abe01ea51dc088ec465cdbef3 introduced the helper function but failed to rename one occurence of an old variable (`$search` -> `$phrase`).

This has already been fixed as part of 32d50e1a846d8c9493ec6a1f24661aa0b28371d7 in 'stable-3_1_2' and 'master'.

**Comment by ptrckb** [comment]
pkp-lib: pkp/pkp-lib#4605
ojs: pkp/ojs#2330

**Comment by asmecher** [comment]
Thanks, @ptrckb!
