### ISSUE TITLE
Cannot edit discussions

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#4607]
We are just upgraded to 3.1.2 and cannot edit present discussion messages in the system. When I press the edit button in the menu under the message, a warning appears as "Failed Ajax request or invalid jason returned". I logged in as journal manager and I should have full authority to edit messages.

Is there solution for that? Thank you all.

Authors still can delete messages after they sent. For example, author may delete the copyright form sent in a journal system message. And, claim that he/she did not permit the publication of the article. For this reason, we edit important messages and remove author name from participan list. So author cannot edit previously sent message.

**Comment by asmecher** [comment]
Hi @Baytan -- what kind of messages are you referring to?

**Comment by Baytan** [comment]
Hi @asmecher 
Thank you for your interest. I refer to all messages under Discussion title in the submission page. I mean the pages of the each submission.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/4616

@Baytan, you can use the attached patch (applied in `lib/pkp`) to correct the problem.

**Comment by Baytan** [comment]
thank you very much:)
