### ISSUE TITLE
Message field in Discussion not visible

### ISSUE THREAD

**Issue by willysr** [pkp/pkp-lib#4609]
I have just upgraded to latest OJS 3.1.2.0 and now in the discussion menu, the message field is not visible anymore. It happened in all stages (submission, review, copyediting, and production).

![image](https://user-images.githubusercontent.com/240100/54504436-3a975980-4966-11e9-8410-6f1e9be1179c.png)

**Comment by asmecher** [comment]
@willysr, try a hard reload on your browser. If that doesn't work, check your browser's error console for details.

**Comment by willysr** [comment]
I had flushed the cache and tried to use private browsing as well, but no luck

**Comment by willysr** [comment]
well, i tried again this morning and it worked. Strange...
closing now
