### ISSUE TITLE
OJS Reset Article Permissions action is unclear

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4618]
In journal settings we have a button that says "Reset article permissions".

The description is:

> Reset Article Permissions
> Copyright statement and license information will be permanently attached to published content, ensuring that this data will not change in the case of a journal changing policies for new submissions. To reset stored permissions information already attached to published content, use the button below.

Many journal managers (and me) think that this means they can change all article permissions with one bulk command to the settings they have defined in the same form. We have had similar situations and have seen questions concerning this in the forum. 

However, what the Reset button actually does is that it just removes all the attached permissions from all articles.

I am not a native speaker, but for me "reset" means something else than "remove" or "delete". I, and many others, expect that "reset" means resetting the permissions to the given default values. 

I suggest that we:

1. Change the language there and use the word "Delete" or "Remove":

> **Delete** all article permissions

> "To **remove** stored permissions information already attached to published content, use the button below."

AND

2. Add a secondary button that allows journals to bulk set all published article permissions to match the defaults given in the settings.

> Reset all article permissions using the default values

I think that we definitely need to do at least number 1.

**Comment by asmecher** [comment]
@ajnyga, I agree with your assessment of the problem. I'm not sure two buttons are justified, though -- what about making the button behave as you expect (to reset all permissions on published content)? If someone wants to clear permissions and leave them empty, they can empty the journal settings first and use the button.

**Comment by ajnyga** [comment]
Sounds good.

**Comment by ajnyga** [comment]
@asmecher 
ojs: https://github.com/pkp/ojs/pull/2353
lib: https://github.com/pkp/pkp-lib/pull/4651

Noticed that a close issue (https://github.com/pkp/pkp-lib/issues/1466) has been dealt with recently so tagging @NateWr here as well. 

I think that the new description text in master branch does not need any revision? The desrciption there mentions "current default settings" and that is actually what has been fixed now with this pr.

**Comment by asmecher** [comment]
@NateWr, may I leave this one with you?

**Comment by NateWr** [comment]
:+1: merged. Thanks @ajnyga!

@asmecher since this fix _will_ go out with 3.2, should I assign it to the 3.2 milestone now that it's closed, so that we know which milestone it contributed to?

**Comment by ajnyga** [comment]
One small thing to consider left here. 

With the license and copyright holder you can now empty the fields by leaving the default settings blank and running reset. However, with the copyright year you have a radio button selection. If you have already chosen one of the two options, then you can not reset the articles to have no copyright year. You can only reset the value to one of the two options available...

**Comment by NateWr** [comment]
I believe this is correct. When resetting, it will use the `copyrightYearBasis` setting for the context, which will set the year to either the article's publication date or the issue's publication date.

I notice that the `copyrightYearBasis` property is `nullable` and has no default value. In such a case that would lead to an `assert(false)` in `Article::_getContextLicenseFieldValue()`. Perhaps that's something that should be addressed, by preventing it from being nullable and setting a default value to `issue`.

If you agree I'll open a  new issue.

**Comment by ajnyga** [comment]
yes I noticed that when I was doing this pr, see https://github.com/pkp/pkp-lib/issues/4654

And I guess that fixes this minor issue as well. I am thinking a (maybe non-existing) situation where a journal wants to *remove* all copyright year data from all articles. Now they can only choose between the two available options.

**Comment by NateWr** [comment]
Excellent, it's already filed! I'll drop a quick note in about how to do this in the schema system.

> Now they can only choose between the two available options.

That sounds reasonable but maybe a separate use-case. I like that we've aligned things here along the "reset" use case. That they can delete is ok, but if they need full deletion, maybe it's best to make them jump through a few hoops. It seems like it would be something to discourage except under extraordinary circumstances.

**Comment by ajnyga** [comment]
yes agreed, even resetting all article permissions is something that has to be a bit difficult to do.

**Comment by asmecher** [comment]
@NateWr:

> since this fix will go out with 3.2, should I assign it to the 3.2 milestone now that it's closed, so that we know which milestone it contributed to?

Yes, I've done that!

**Comment by asmecher** [comment]
Thanks, @ajnyga, this is great! (And thanks for tackling the review, @NateWr.)
