### ISSUE TITLE
[OJS 3.1.2] QuickSubmit: Changing a locale may trigger error 500 in Multilingual Journal

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#4621]
Here is the way to reproduce:
1) In a multilingual journal go to QuickSubmit, change anything in the form (e.g.  Submission Language),
2) Switch a locale,
3) If you choose 'Leave', you would get a blank page (error 500)

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.
