### ISSUE TITLE
[OJS 3.1.2] QuickSubmit: Failed Ajax request when adding a Cover image

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#4623]
Here is the way to reproduce:
1) Go to QuickSubmit, upload a cover image.
2) You would get something like this:
![image](https://user-images.githubusercontent.com/22288161/54751872-49dc0880-4bed-11e9-8662-b2efc6dc9574.png)

**Comment by gabeLon** [comment]
I'm having the same issue.

**Comment by asmecher** [comment]
Either of the above patches should fix it (they're equivalent, just applied to different branches). I'll put together a new build and place it in the plugin gallery shortly. Thanks for reporting!

**Comment by asmecher** [comment]
Built v1.0.4-1 and added to the plugin gallery. (https://github.com/pkp/quickSubmit/releases/tag/v1.0.4-1)
