### ISSUE TITLE
No assignment for copyeditor/layout editor/proofreader after upgrade

### ISSUE THREAD

**Issue by ptrckb** [pkp/pkp-lib#4625]
When upgrading from OJS 2.4.8 to OJS 3.1, the assignments of copyeditors, layout editors and proofreaders on submissions are lost.

**Comment by ptrckb** [comment]
OJS: pkp/ojs#2337

**Comment by asmecher** [comment]
Ah! Correct -- good spotting, @ptrckb. I'll forward-port this to `stable-3_1_2` and `master`.
