### ISSUE TITLE
OJS 3.1.1.4 to 3.1.2 upgrade problem

### ISSUE THREAD

**Issue by JosephELKHOURY** [pkp/pkp-lib#4626]
Hello,

When trying to upgrade, I get this error: 
A database error has occurred: ERROR: relation "users_tmp" already exists.

Any help?

**Comment by asmecher** [comment]
@JosephELKHOURY, the Support Forum (https://forum.pkp.sfu.ca) is the best place to get help -- this issue tracker is more for bug fixes and feature discussion.
