### ISSUE TITLE
[OJS 3.1.2] Journal Manager cannot add Cover image to Article

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#4627]
When trying to upload a cover image for an article, _which is not yet linked to any issue_, the Journal manager gets a 'HTTP error'. This behavior cannot be reproduced by the Administrator (s/he can upload cover images for any articles without problems).
Also, the Journal manager does not get any error when trying to upload a cover image for an article already linked to an issue.

**Comment by asmecher** [comment]
@Ph-We, I wasn't able to replicate this behaviour using a recent checkout of OJS 3.1.2-x. I suspect the most likely cause is file permissions in the `public` directory. Is this still affecting you, and if so, can you double-check your file permissions?

**Comment by Ph-We** [comment]
@asmecher, you must be right, since we cannot reproduce it either on our production instance now. 
So it only appeared on the test one, which does not exist anymore, so I cannot confirm it was related to file permissions.
Thank you anyway. I close it now.
