### ISSUE TITLE
Stats processing needs tweaks and fixes on master 

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#463]
Some application classes lacks implementation, some fixes from ojs stable were not ported.

**Comment by asmecher** [comment]
Bruno, is this entry complete?

**Comment by beghelli** [comment]
no, it is not. I couldn't finish before beta release, have some commits here that I need to finish. Working on them today.

**Comment by beghelli** [comment]
Duplicated #1000. Closing.
