### ISSUE TITLE
[OJS] OJS 3.1.2 fails to display archive page with Bootstrap 3 plugin

### ISSUE THREAD

**Issue by briho** [pkp/pkp-lib#4635]
While setting up a fresh installation of OJS 3.1.2 with a Bootstrap 3 plugin theme, the journal fails to display the archive page (issue/archive) with a public http 500 error and this in the site error log:

```
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "app:app:frontendpagesissueArchive"  on line 45 "{url|assign:"prevUrl" router=$smarty.const.ROUTE_PAGE page="issue" op="archive" path=$prevPage}" unknown modifier 'assign' <-- 
  thrown in /[XXX]/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 45

```
I had thought that perhaps this was a problem with my specific local installation, but the same failure occurs on our official PKP-hosted journal website. This does appear to be a genuine bug, and one that breaks websites hosted by PKP.

**Comment by asmecher** [comment]
@briho, closing this in favour of https://github.com/NateWr/bootstrap3/issues/115.
