### ISSUE TITLE
Translator plugin doesn't work with new settings tabs

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4637]
It looks like I forgot to update the Translator plugin to work with the new settings tabs introduced in #3594. Activating it doesn't add any UI to the settings screens.

It needs to be migrated to the new tab system before the forms stuff goes out in 3.2.

**Comment by carzamora** [comment]
@NateWr this mean the plugin is not working? because for me is working without problems, or is when you change some settings?

**Comment by NateWr** [comment]
@carzamora are you working off the `master` branch or off of 3.1.2? The problem doesn't exist in 3.1.2. It will only exist in the current `master` branch, so we plan to resolve it before we release from there (which will be 3.2 in the summer some time).

**Comment by carzamora** [comment]
oh, ups... sorry, my mistake!

**Comment by asmecher** [comment]
Cosing -- the translator plugin has been obsoleted by the move to Weblate.

**Comment by ronniebrito** [comment]
@asmecher  some custom translation are needed on certain circunstances where the standard translation isnt the ideal, so I think this plugin shoudnt be discontinued :/

**Comment by asmecher** [comment]
@ronniebrito, have you looked at the custom locale plugin?

**Comment by ronniebrito** [comment]
it solves the problem 
thank you @asmecher
