### ISSUE TITLE
Error on favicon upload, when determining the favicon type

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#464]
When uploading the favicon in setup 5, there is an error when determining the mime type.
S. https://github.com/pkp/ojs/commit/6146c3b041ebeed1566b36f2df440c0eba0a1f32#commitcomment-10737408
This issue is also reported here: S. http://forum.pkp.sfu.ca/t/error-on-uploading-image-on-journal-step-5/232
The pull request is comming :-)

**Comment by asmecher** [comment]
PR: https://github.com/pkp/ojs/pull/471

**Comment by asmecher** [comment]
Thanks, Bozana!
