### ISSUE TITLE
Wrong french translation for email templates "editor_decision_revisions" and "editor_decision_resubmit"

### ISSUE THREAD

**Issue by Potomac54** [pkp/pkp-lib#4644]
Hello,

In OJS 3.1.2 I notice errors in emailTemplates.xml for the french translation, 

there is a reversal of messages between templates ""editor_decision_revisions" and "editor_decision_resubmit", 

the fix is simple : just switch the content of "editor_decision_revision" template to "editor_decision_resubmit" (and vice versa),

I propose a patch for this problem, see the attached file
[patch_request_revisions_messages.zip](https://github.com/pkp/pkp-lib/files/3034226/patch_request_revisions_messages.zip)

**Comment by NateWr** [comment]
Closing this as outdated. We now manage translations through [weblate](https://translate.pkp.sfu.ca/).
