### ISSUE TITLE
Check and fix language settings during upgrade from OJS 2

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4645]
OJS 2.4.x journals may have primary locale settings configured in such a way that only the 'UI' setting for the locale is enabled, with 'Submissions' and 'Forms' unchecked (likely as a result of a prior OJS 2 upgrade and the introduction of those settings), i.e.

![ojs2_locale_settings](https://user-images.githubusercontent.com/200793/55412431-6d7c4880-5535-11e9-9893-e1d94dc8354b.png)

Even though 'Submissions' and 'Forms' are unchecked, authors are still able to complete submissions using the primary locale in the OJS 2.4.x journal.

When the journal is upgraded to OJS 3.1.2, the above locale settings remain unchanged, but authors are no longer able to complete the submission process.

It would be helpful to check these locale settings during upgrade to ensure that at least one locale has 'Submissions' and 'Forms' enabled if the journal also has online submissions enabled (and adjust these settings if needed).

![post_upgrade_locale_languages](https://user-images.githubusercontent.com/200793/55412734-fd21f700-5535-11e9-94c6-fa79223160e3.png)

![post_upgrade_locale_submission_broken](https://user-images.githubusercontent.com/200793/55412751-027f4180-5536-11e9-9787-b072164afa6f.png)

**Comment by asmecher** [comment]
@mfelczak, this is really a case of OJS just doing what it's told. Is this something you're encountering frequently? I've never heard of a journal configured that way before.

**Comment by mfelczak** [comment]
Hi @asmecher, yes we've had this crop-up a few times now with journals that we've upgraded from OJS 2.4.x

**Comment by asmecher** [comment]
Do you have any idea why/how the language settings in OJS 2.x got to be set that way? The real problem in my opinion is those settings.

**Comment by mfelczak** [comment]
I'm not really sure, although I would be doubtful that JMs would uncheck them that way on purpose. My assumption, and this may be incorrect 😄, was that these were older OJS 2.x journals that were upgraded to newer versions of OJS 2.x that included the additional locale checkboxes, and these were never explicitly enabled by either the upgrade script or JMs.

**Comment by asmecher** [comment]
Hrm, it'll be a nasty little bit of upgrade scripting and will definitely need some testing intermixed with dev. Especially if it's uncommon and tied to very old releases, is it something you could add to your upgrade checklist instead?

**Comment by mfelczak** [comment]
Yep, we can add it to our upgrade workflow. Having a placeholder for this in github should also help other folks who bump into this issue.

**Comment by asmecher** [comment]
@mfelczak, I'm going to close this as a WONTFIX now that we're removing the OJS 2.x to 3.x upgrade mechanism.
