### ISSUE TITLE
Email validation breaks registration page

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4649]
See: https://forum.pkp.sfu.ca/t/registration-does-not-work-ojs-3-1-1-4/

Reported against 3.1.1-4, but unconfirmed there.  Confirmed against 3.1.2.

Call to notification includes `$request->getUser()->getId()`, but `$request` has not had a user set at this point.
https://github.com/pkp/pkp-lib/blob/a508f9744c20521e1884c2dbc4668621d86c9788/classes/user/form/RegistrationForm.inc.php#L326

Steps to reproduce:

1. Clean install of OJS 3.1.2
2. Enable `require_validation` in config.inc.php
3. Complete the new user registration form

**Comment by NateWr** [comment]
Looks like this has been fixed in stable and master: https://github.com/pkp/pkp-lib/pull/4650. @ctgraham can this one be closed?
