### ISSUE TITLE
[OJS] Empty copyright holder

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#465]
If the copyright holder article metadata field is empty for a language it will be also displayed empty (e.g. in RT), instead of displaying the value for the journal primary language. 
S. https://github.com/pkp/ojs/commit/44198ed444730014e9af1deba9792c059575d33c#commitcomment-10753530
Pull request is coming :-)

**Comment by asmecher** [comment]
Merged, thanks!
