### ISSUE TITLE
ojs 3.1.1-4 users page endless spinner

### ISSUE THREAD

**Issue by vvkorotkikh** [pkp/pkp-lib#4652]
OJS 3.1.1-4, postgres.
When I trying to manage users in OJS via Users & Roles -> Users, I see only endless spinner under page title. Users & Roles -> Roles work perfect, I see all user roles. Log attached. Please check [03-Apr-2019 14:06 UTC] and [03-Apr-2019 14:13 UTC]. Such error was not detected earlier.

**Comment by vvkorotkikh** [comment]
[11.log.gz](https://github.com/pkp/pkp-lib/files/3039403/11.log.gz)

**Comment by asmecher** [comment]
@vvkorotkikh, could you post your question in our support forum (https://forum.pkp.sfu.ca)? That's the best place for general technical support.
