### ISSUE TITLE
ojs 3.1.1-4 uploadiing new plugin

### ISSUE THREAD

**Issue by vvkorotkikh** [pkp/pkp-lib#4653]
OJS 3.1.1-4, postgres.
When I trying to upload new plugin 
https://github.com/Ph-We/GOST/releases/tag/v0.1.1.1
in OJS via site administrator tools I see this notification.
   Notification The uploaded plugin archive does not contain a folder that corresponds 
   to the plugin name. 
Log attached. Please check [03-Apr-2019 14:18 UTC].
Thank you.
[11.log.gz](https://github.com/pkp/pkp-lib/files/3039413/11.log.gz)

**Comment by asmecher** [comment]
@vvkorotkikh, please use our support forum (https://forum.pkp.sfu.ca) for general technical support. Thanks!
