### ISSUE TITLE
Resolve assert() failure for journals without a saved copyright basis setting

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4654]
For journals that have not saved the permissions form, the following warning will show up when permission (copyright) details are retrieved:
```
PHP Warning: assert(): assert(false) failed in classes/article/Article.inc.php on line 87
```
Suggested resolution: Make article-based copyright date a default for when new contexts are created.

For existing contexts, I would rather not introduce a default e.g. during upgrade. Permission settings are sensitive enough that a journal really should be making that decision intentionally. This means an ongoing `assert()` warning for journals that have not done so.

(Thanks for reporting, @ajnyga!)

**Comment by NateWr** [comment]
:+1: Now that contexts are on the schema system, this can be changed by modifying [the schema definition](https://github.com/pkp/ojs/blob/master/schemas/context.json#L21-L26) from:

```json
"copyrightYearBasis": {
  "type": "string",
  "validation": [
    "nullable"
  ]
},
```

To:

```json
"copyrightYearBasis": {
  "type": "string",
  "default": "issue",
  "validation": [
    "in:issue,article"
  ]
},
```

If we want to handle missing values in existing databases, a db upgrade script will need to be run.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/2392 (master)
https://github.com/pkp/ojs/pull/2391 (stable)

**Comment by NateWr** [comment]
Merged.
