### ISSUE TITLE
Fix editorial history for emails with sender_id=0

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4655]
Some emails that are sent by the system automatically (e.g. automatic reminders) go out with `sender_id=0` in the database. It appears that the editorial history grid is not prepared to handle these:

https://forum.pkp.sfu.ca/t/editorial-history-does-not-work/48959/24

Fix the display so that these emails are displayed without breaking the listing.

**Comment by asmecher** [comment]
(Requested feedback at https://forum.pkp.sfu.ca/t/editorial-history-does-not-work/48959/26)

**Comment by asmecher** [comment]
Ah, I think this was already fixed: https://github.com/pkp/pkp-lib/commit/1b5d4239852ff376638339025ff7af523b4441cc

**Comment by NateWr** [comment]
Looks like this fix is in stable and master. Closing.
