### ISSUE TITLE
CSL processor turns all journal names to uppercase in some formats

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4658]
Hi,

One of our journals noticed that the current CSL processor turns all journal names to uppercase in citations for example with APA standard.

So a journal called `Historiska och litteraturhistoriska studier` turns into `Historiska Och Litteraturhistoriska Studier` which looks very weird because Swedish does not have a convention of turning titles into uppercase.

**Comment by asmecher** [comment]
@ajnyga, that'll be coded into the CSL file itself, which is not something we maintain as part of our repo. See the CSL spec around [here](http://docs.citationstyles.org/en/stable/specification.html) (look for text-case) and find the CSL files themselves in `plugins/generic/citationStyleLanguage/citation-styles`.
