### ISSUE TITLE
Fix/change PDF viewing

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#466]
Apparently there are problems with iPad readers:
http://forum.pkp.sfu.ca/t/omp-and-ipad-download-problems/270/2

Additionally, PDFObject is known not to work with IE11 and is not currently being actively maintained.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/omp/pull/118

**Comment by asmecher** [comment]
@beghelli, mind reviewing this? I've removed the PDFObject-based PDF embedding in favour of PDF.js.

**Comment by beghelli** [comment]
reviewed, but why no need to change display.tpl?

**Comment by asmecher** [comment]
@beghelli, that did change -- see:
https://github.com/asmecher/omp/blame/i466-fix/plugins/viewableFiles/pdfJsViewer/templates/display.tpl
The whole diff probably didn't display in your browser, since it's large (lots of pdf.js files).

**Comment by beghelli** [comment]
were you waiting for me to finish the review? I am looking to the files
still :)

2015-04-16 18:23 GMT-03:00 Alec Smecher <notifications@github.com>:

**Comment by asmecher** [comment]
Sorry, I thought you were finished! Keep going.

**Comment by beghelli** [comment]
inside pdfViewer.tpl you use  $(document).ready(function(). This might be executed before all page elements are loaded. AJAX calls (OMP and OJS master use them a lot, of course) will not interfere on when this event is triggered. Not sure if that's a concern though.

**Comment by beghelli** [comment]
release date in version.xml file is <date>2013-07-02</date>. Needs update I think :)

**Comment by beghelli** [comment]
ok, finished.

**Comment by asmecher** [comment]
Thanks! I'll fix the version, and the document.ready thing isn't currently an issue as that's just adding the PDF.js presentation to the PDF (which doesn't care about AJAX requests etc).
