### ISSUE TITLE
[OJS] Contact form suggestions

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#4660]
Here are some suggestions for Settings > Journal > Contact:

- the mailing address field could be internationalized (e.g., the city name could change from language to language);

- the affiliation field (already internationalized) could allow multi-line input (e.g., department and university)

- the name for Technical Support Contact could be internationalized and made optional, as sometimes it's not a person, rather a generic team name (e.g., Editorial Support Team)

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
