### ISSUE TITLE
[OJS] Native export / import of issues with only full issue galleys not possible

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4661]
We have a journal that has a series containing both issues with articles but also monographs. When I tried to export an issue that only had the full issue galley in place, I get an error concerning missing sections. Sections are of course missing, because there are no single articles within the issue.

The reason is probably because sections are required here https://github.com/pkp/ojs/blob/master/plugins/importexport/native/native.xsd#L30. Is there a reason why we could not lower the bar here and allow issue exports without sections?

(a bigger issue is that OJS and OMP should be merged so that you can have a series that allows you to publish both issues with articles and monographs. We can probably do that by 3.2. right?)

**Comment by ajnyga** [comment]
edit: no actually you need to have `minOccurs="0"` here https://github.com/pkp/ojs/blob/master/plugins/importexport/native/native.xsd#L194

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.
