### ISSUE TITLE
Changing galley is not reflected in search index

### ISSUE THREAD

**Issue by Stefanvdb** [pkp/pkp-lib#4664]
If a submission is edited and a galley file is changed, these changes are not reflected in the search index. 
Pull request will follow.

**Comment by asmecher** [comment]
Thanks, @Stefanvdb! Also cherry-picked to `stable-3_1_2` for the OJS 3.1.2-1 release (due fairly soon).

**Comment by asmecher** [comment]
Oops, I had to back this out of `stable-3_1_2` and will need to fix it in `master`. It adds OJS-specific concepts to `pkp-lib`, which is also used by OMP.

**Comment by asmecher** [comment]
@Stefanvdb, I've just reverted the PR to fix the tests -- this will need a little more work to support both OJS and OMP codebases. Mind if I leave this with you? I have some ideas for how to approach it if you're not sure.

**Comment by Stefanvdb** [comment]
@asmecher: oops, didn't realise that - unfortunately i am not familiar with OMP yet. 
I don't mind giving it a go, but currently I do not have an idea yet how to solve this issue. So if you could point me in the right direction I will try after easter.

**Comment by asmecher** [comment]
@Stefanvdb, thanks for your patience -- I've just merged some changes that allow you to use Application::getSubmissionSearchIndex() and then call functions on that object independent of whether it's being used in OJS or OMP. If you have a look at the abstract functions in SubmissionSearchIndex, that'll resolve it. Mind taking a look and adjusting the PR to use that?

**Comment by asmecher** [comment]
(Rescheduling for 3.2, as this will be dependent on some refactoring that's only in `master`.)

**Comment by Stefanvdb** [comment]
@asmecher 
Sorry it took me so long to get back to this issue - vacation and a lot of other stuff to do...
As I was not able to test the Lucene Plugin against master branch of OJS yet, I couldn't test this code yet. But this should do the job, i think.
https://github.com/pkp/pkp-lib/pull/4794

**Comment by asmecher** [comment]
Thanks, @Stefanvdb! Just one change to suggest -- rather than using `$articleSearchIndex`, rename the variable to `$submissionSearchIndex`. That way it's accurate for all apps. (OMP doesn't have articles, it has monographs -- "submission" is the abstract term in either case.)

**Comment by Stefanvdb** [comment]
Hi @asmecher 
I have pushed the renamed variable.

**Comment by asmecher** [comment]
Thanks for contributing and sticking with this through all the twists and turns, @Stefanvdb! Merged.
