### ISSUE TITLE
Change the cli install to also receive args from enviroment variables

### ISSUE THREAD

**Issue by arturluizbr** [pkp/pkp-lib#4671]
Recently i had to create a new version of OJS image, but i wasn't able to complete install script from terminal because it requires interaction with user.

Docker build does not support such thing.

So it would be nice if we could define environment variables and the install script uses them to perform an automated install.

My docker image is build from this repo: https://github.com/arturluizbr/docker-pkp-ojs

*I openned an issue here because the OJS repo does not have the issue tab*

**Comment by asmecher** [comment]
@arturluizbr, have you seen this docker image? https://github.com/lucasdiedrich/ojs

It uses a CURL request to complete the installation. It's not an "official" docker image, but has gotten a lot of uptake, and some of our closer partners work directly with its maintainer. It may become an official image at some point.

That said, I agree that the installer should be able to run autonomously.

**Comment by arturluizbr** [comment]
> @arturluizbr, have you seen this docker image? https://github.com/lucasdiedrich/ojs

Really good approach he used there.

> It may become an official image at some point.

Nice! It'll really save us a lot of time, I work at UFCA (ufca.edu.br), and i had to create a new image each time our server structure changed, so i was kinda forced to create something that works ok in different kinds of environment.

> That said, I agree that the installer should be able to run autonomously.

I was checking the code for importing interactive CLI variables in pkp-lib, i think we could add a quick check if is there a setted environment variable before asking user to input value.

**Comment by asmecher** [comment]
> I was checking the code for importing interactive CLI variables in pkp-lib, i think we could add a quick check if is there a setted environment variable before asking user to input value.

Good idea! We might be able to align this with some of our testing toolset, which uses environment variables ([getenv](https://www.php.net/manual/en/function.getenv.php)). The conventions we use there (see e.g. `lib/pkp/tools/travis/prepare-tests.sh`) are:
* DBHOST
* DBNAME
* DBUSERNAME
* DBPASSWORD
* FILESDIR

I'd recommend adding a flag to the command line installer allowing the caller to specify that environment variables should be checked (e.g. `php tools/install.php -e`, where the `-e` flag says "check for environment variables before asking").

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [discussions](https://github.com/pkp/pkp-lib/discussions).
