### ISSUE TITLE
[OJS 3.1.2] When sending email with uploaded image then the recipient will not see the image

### ISSUE THREAD

**Issue by Potomac54** [pkp/pkp-lib#4673]
Hello,

I notice that if the admin wants to send an email to a user with OJS (menu "user and roles", "users", "email") then if an image is uploaded by him (with "justboiled.me plugin") then the image seems uploaded, but the recipient will receive a text-only email (no image inside),

the image should be present in the mail, why it is missing for the recipient ?
Is it an expected behaviour ?

thanks

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
