### ISSUE TITLE
[OJS 3.1.2] Use english help manual by default if local language has no manual

### ISSUE THREAD

**Issue by Potomac54** [pkp/pkp-lib#4678]
Hello,

I use OJS 3.1.2 and I notice that french help manual is not available : 
https://github.com/pkp/ojs-user-guide/tree/master/fr

that means that the help menu will not work (empty items when I click on the help button), 

my suggestion : use by default english help manual if the local language (like french) has no help manual,

currently as a workaround I had to copy english manual to the french help directory on my server : 

cp -r /var/www/html/docs/manual/en/* /var/www/html/docs/manual/fr/

**Comment by asmecher** [comment]
@Potomac54, the linked patch corrects this for the forthcoming 3.2 release. For 3.1.2, the best solution is simply to remove `docs/manual/fr` entirely, or else to complete the translation of course :)
