### ISSUE TITLE
Add option in default theme to use homepage image as header background

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4683]
It is common for journals to want to use an image in the header. We discourage this because many journals try to use long text in the image that then becomes unreadable on a small device.

However, we could add an option to the default theme to use the homepage image as a header background. This image would have the journal text (or logo) displayed on top of it, so it would discourage putting too much text into the header. But it would allow journals to add a more distinctive visual mark on each page.

Example:
![background-header](https://user-images.githubusercontent.com/2306629/56220227-0051d280-6060-11e9-934a-c74bedec2e31.png)

Some additional options, like changing the text color to white or dark, might be needed when this option is activated to ensure the text is legible on the image. It may also be prudent to apply some shading to the background image to improve legibility.

**Comment by thinkbulecount2** [comment]
PR here, @NateWr https://github.com/pkp/pkp-lib/issues/4683

**Comment by thinkbulecount2** [comment]
PR here, @NateWr: https://github.com/pkp/ojs/pull/2376

**Comment by NateWr** [comment]
Merged!
