### ISSUE TITLE
Add mobile-friendly header and nav menu to default theme

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4684]
Currently, the default theme doesn't fully collapse the navigation menu on a small screen. All items appear at the top of the page, which means users often have to scroll before they see content.

![header-current](https://user-images.githubusercontent.com/2306629/56221609-748d7580-6062-11e9-8f0d-a86c9868097d.png)

We should implement a collapsed header for mobile with an icon to open the nav menu.

![header-mobile](https://user-images.githubusercontent.com/2306629/56221690-9f77c980-6062-11e9-8b63-8bd75a1ebb33.png)

And a more comfortable nav menu on phones when open.

![header-mobile-out](https://user-images.githubusercontent.com/2306629/56221712-abfc2200-6062-11e9-817d-6397d5c2e616.png)

**Comment by thinkbulecount2** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/4922
https://github.com/pkp/ojs/pull/2430

**Comment by NateWr** [comment]
Looks good @thinkbulecount2! I've added some comments for an initial code review.

I also took the liberty to work up some changes to the styles to fix the header height, improve the click area of the button, and support journal titles of unlimited length.

![out](https://user-images.githubusercontent.com/2306629/61288859-eee3a800-a7bf-11e9-913d-7ff19ee4692c.gif)

There were some tricky issues to solve here. I've annotated my commit if you want to learn some of the tricks I used:

https://github.com/NateWr/ojs/commit/e741ab223f3131c4006aa8cb4217c7c63b378239

And there was one small commit to pkp-lib:

https://github.com/NateWr/pkp-lib/commit/5d7200506e1314f8648b8f9ebd432e3291eb50fa

You can cherry-pick these changes by adding my remote in git, fetching from it, and then cherry-picking:

```
git remote add NateWr git@github.com:NateWr/ojs.git
git fetch NateWr
git checkout <your-branch>
git cherry-pick e741ab223f3131c4006aa8cb4217c7c63b378239
cd lib/pkp
git remote add NateWr git@github.com:NateWr/pkp-lib.git
git fetch NateWr
git checkout <your-branch>
git cherry-pick 5d7200506e1314f8648b8f9ebd432e3291eb50fa
```

Let me know if you have any questions or want to talk through anything! :+1:

**Comment by thinkbulecount2** [comment]
Awesome, thanks @NateWr!

**Comment by NateWr** [comment]
Great! The progress on this is looking really nice. The next step is to figure out the UI styles and interactions for the mobile nav menu, and separate those out from the one on the desktop.

I've gone ahead and written some code that will add Bootstrap's dropdown feature on large screens and remove it on small screens. You should be able to cherry-pick that in:

```
cd <ojs-root>
git fetch NateWr
git checkout <your-branch>
git cherry-pick 7342afc6b8e8a659ebfa07973a252e9a38157a15
```
You can see that commit here: https://github.com/NateWr/ojs/commit/7342afc6b8e8a659ebfa07973a252e9a38157a15

That will remove the dropdown-on-click functionality from the nav menu items. But you'll still need to show the missing nav submenus. I'd recommend starting out by moving the `.pkp_nav_list` helper into a media query so that the styles only work on a desktop:

https://github.com/pkp/ojs/blob/master/plugins/themes/default/styles/helpers.less

That will give you something like this:

![Selection_091](https://user-images.githubusercontent.com/2306629/61642784-7ab27400-ac99-11e9-9115-455eb278d88c.png)

From there, you'll need to style up the list and sublists to look better. We're aiming for something like this:

![Selection_092](https://user-images.githubusercontent.com/2306629/61643285-6f137d00-ac9a-11e9-8925-4b64bab0a577.png)

To get there, you'll need to write a bunch of new styles. And you'll probably need to think about what HTML changes are required to get the search at the bottom. Off the top of my head, I think it's likely we'll have to duplicate the search form in two places in the HTML code, and show one of them in mobile and one of them in desktop.

**Comment by NateWr** [comment]
Here's a quick look at the improved mobile nav menu for the default theme.

![mobile-nav](https://user-images.githubusercontent.com/2306629/62937260-03698f00-bdc4-11e9-91bf-75d9107fe380.gif)

Glad to finally get this sorted out! :+1:

**Comment by NateWr** [comment]
Hey @asmecher, I'm getting test failures for the PRs here (https://github.com/pkp/pkp-lib/issues/4684#issuecomment-511442026). I can't reproduce the issue locally and when I run the tests they get through that test without any problem.

It looks like the right submodule commit is getting checked out: https://github.com/pkp/pkp-lib/issues/4684#issuecomment-511442026

Can you reproduce the failure with these PRs?

**Comment by asmecher** [comment]
Will take a look...

**Comment by asmecher** [comment]
@NateWr, I think you need to rebase your `pkp-lib` on top of the latest `master` and update the submodule commit in OJS -- it looks like your `i4684_nav_menu` branch is missing https://github.com/pkp/pkp-lib/commit/c8a97f64206cf2ae16b759edd7d6e8bf8bcabfb5.

**Comment by NateWr** [comment]
I have rebased to include that commit (https://github.com/NateWr/pkp-lib/commits/i4684_nav_menu) and that fixed the installation process, but OJS tests are failing after installation when looking for the Login button.

Do you know what resolution the tests run in? The new mobile nav menu puts the login link in a toggle on small screens (below 992px wide). Is it possible it's running at a resolution smaller than that?

**Comment by NateWr** [comment]
Hey @asmecher, just a quick reminder on this one. Specifically, this question:

> Do you know what resolution the tests run in? The new mobile nav menu puts the login link in a toggle on small screens (below 992px wide). Is it possible it's running at a resolution smaller than that?

**Comment by asmecher** [comment]
> Do you know what resolution the tests run in?

Sorry, I missed that. It's specified [here](https://github.com/pkp/pkp-lib/blob/cbff3a1d9bdcc3a8aefa7c4b43617489b99e9690/tools/travis/start-xvfb.sh#L28) as 1920x1080.

**Comment by asmecher** [comment]
(That's the screen resolution -- the browser is left to its own devices, which I expect will be a "comfortable" fraction of the screen by default. If certainty is an issue, I can see about explicitly maximizing the window or something.)

**Comment by NateWr** [comment]
I'm lost as to what could be the issue with the tests here. I will try to rebase and run the tests again next week to see if that fixes anything.

**Comment by asmecher** [comment]
Hi all! In case it helps, I added code to support a fixed/standard browser size (`master` branch only). Default is now 1280x768, and can be overridden with the `BROWSERSIZE` environment variable. https://github.com/pkp/pkp-lib/commit/21ccf3127038ce3ae00c4411ad1102895a19fdf1 for details.

**Comment by NateWr** [comment]
Merged!
