### ISSUE TITLE
Add support for issue galleys to HTML galley plugin

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4685]
See https://forum.pkp.sfu.ca/t/viewing-full-issue-html-galleys-in-the-browser/52664 for details.

**Comment by librariam** [comment]
+1 from U of T and also https://forum.pkp.sfu.ca/t/htmlarticlegalley-plugin-ojs-3-3-0-8/70809

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
