### ISSUE TITLE
[OJS] SearchIndexing: Submissions marked dirty are immediately marked clean again

### ISSUE THREAD

**Issue by Stefanvdb** [pkp/pkp-lib#4686]
If Submission is changed, ArticleSearchIndex::articleMetadataChanged is called.  
If indexing is asynchronous (pull-indexing), the article is only being marked as dirty (IndexingState=1), so a cron job can later index the new version.
But after the call of ArticleSearchIndex::articleMetadataChanged, the submisison that had been read before the call is updated, resulting in marking it clean again.
Pull Request with fix will follow.

**Comment by asmecher** [comment]
PR (https://github.com/pkp/ojs/pull/2362) merged -- thanks, @Stefanvdb! I'll also back-port to `stable-3_1_2`.
