### ISSUE TITLE
Fatal error with method signature changes in PublicFileManager

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4688]
In https://github.com/pkp/ojs/commit/6d4b794cf3f98fbe5a41d1bc9e96aa84f0d574d1#diff-b45e02fe828b9d22e618ca5dfee22435 and https://github.com/pkp/ojs/commit/6d4b794cf3f98fbe5a41d1bc9e96aa84f0d574d1 calls to `PublicFileManager::copyJournalFile()` were changed to `PKPPublicFileManager::copyContextFile()` (and other similar calls). The new method has an extra argument, so the calls need to be updated.

(It looks like `$assocType` is not being used in `PKPPublicFileManager::copyContextFile()` so it may be best to remove it there, but not sure.)

@asmecher I'll assign this to you since you did the initial change and have a better situational awareness but happy to tackle it myself. (Also, I'm trying not to assign issues to 3.2 but since this one is a regression specifically in master I thought I should?)

**Comment by asmecher** [comment]
Thanks, @NateWr, fixed. This is definitely something needing fixing in `master` so it's appropriate to file against `3.2`. I'll check over OMP as well.
