### ISSUE TITLE
[OJS] Searchindexing: pull-indexing problem with schedule for publication

### ISSUE THREAD

**Issue by Stefanvdb** [pkp/pkp-lib#4689]
If a submission is added to an existing issue and scheduled for publication, the submission is marked dirty and then immediately marked clean again.  This results in the submission not being reindexed if asynchrounous pull indexing is configured in lucene plugin.
Pull request will follow.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/ojs/pull/2363

**Comment by asmecher** [comment]
Thanks as always, @Stefanvdb! Also ported to `stable-3_1_2`.
