### ISSUE TITLE
Move pnotify to composer dependency

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#469]
PNotify 2.0.1 is available via composer:
https://github.com/alex198710/pnotify

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/omp/pull/119
https://github.com/pkp/ojs/pull/474
https://github.com/pkp/pkp-lib/pull/470

**Comment by asmecher** [comment]
Needs work -- the pulls aren't passing travis testing, though they're OK locally.

**Comment by asmecher** [comment]
Not a high priority.

**Comment by asmecher** [comment]
@NateWr, mind taking a quick look at the PRs listed above?

**Comment by NateWr** [comment]
I can see the new package in `composer.json`, but when I run `composer install` it doesn't get installed. And when I run `composer show` it doesn't appear in the list of libs. Any idea what's going on?

**Comment by asmecher** [comment]
Not a clue, `NateWr`! I ran `composer.phar update` and it worked.

**Comment by NateWr** [comment]
Update seemed to have worked! Sorry, not too familiar with composer.

**Comment by NateWr** [comment]
@asmecher This looks good. I was able to test without minification on and all went fine.

I think I've found a bug with minification, though, which is unrelated. When loading the JS lib, I get the [$basePath](https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L552), then use that in [file_exists() checks](https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L599). But the `$basePath` doesn't appear to be a file path, so maybe minified scripts for the JS pkp lib have been broken all along?

If so, that will be a huge performance gain for 3.1. Am I crazy or does this need to be changed?

**Comment by asmecher** [comment]
Hmm, @NateWr, I could've sworn I checked the minification settings was working not too long ago -- but right now yes, that existence check is preventing it from working over here. I've fixed it over at https://github.com/pkp/pkp-lib/issues/2364. That's embarrassing, good spotting!

**Comment by asmecher** [comment]
Merged the pnotify change into master.
