### ISSUE TITLE
Bad locale key for Crossref validation option

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4693]
C.f.: https://forum.pkp.sfu.ca/t/text-rendering-issue-in-crossref-xml-export-plugin/52747/2

Introduced by: https://github.com/pkp/ojs/commit/d186c5913c3d80c999a7d29f25cb6ff105af06c9

**Comment by ctgraham** [comment]
Already correct in master per:
https://github.com/pkp/ojs/commit/80d19234c3d55ab7ba8134edafa0994a212897f3#diff-490fd5d28d9d62d1f9bd2e6cbf12848bL81

**Comment by asmecher** [comment]
Thanks, @ctgraham!
