### ISSUE TITLE
[OJS] using MariaDB as database generate a 500 internal server

### ISSUE THREAD

**Issue by maxram** [pkp/pkp-lib#4699]
**Server** 

- Debian GNU/Linux 9.8 (stretch)
- Apache/2.4.29
- PHP 7.1.11
- MariaDB 10.1

I followed the installation steps, after click on install. I get a blank page with network response: 500 internal server.

I test with PostgreSQL and installed suscessfully.

**Comment by asmecher** [comment]
@maxram, what do you get in your PHP error log?

**Comment by maxram** [comment]
FULL ERROR OUTPUT:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ADODB_Cache_File has a deprecated constructor in /path/to/ojs/lib/pkp/lib/adodb/adodb.inc.php on line 263

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ADOConnection has a deprecated constructor in /path/to/ojs/lib/pkp/lib/adodb/adodb.inc.php on line 359

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ADORecordSet has a deprecated constructor in /path/to/ojs/lib/pkp/lib/adodb/adodb.inc.php on line 2921

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ADORecordSet_array has a deprecated constructor in /path/to/ojs/lib/pkp/lib/adodb/adodb.inc.php on line 3939

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /path/to/ojs/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php:456 Stack trace: #0 /path/to/ojs/lib/pkp/lib/adodb/adodb.inc.php(558): ADODB_mysql->_connect('localhost', 'sodofior_ptolom...', '[@zni5oz-8fO', 'journal_name...') #1 /path/to/ojs/lib/pkp/classes/db/DBConnection.inc.php(151): ADOConnection->Connect('localhost', 'sodofior_ptolom...', '[@zni5oz-8fO', 'journal_name...', false) #2 /path/to/ojs/lib/pkp/classes/db/DBConnection.inc.php(126): DBConnection->connect() #3 /path/to/ojs/lib/pkp/classes/db/DBConnection.inc.php(83): DBConnection->initConn() #4 /path/to/ojs/lib/pkp/classes/db/DBConnection.inc.php(52): DBConnection->initDefaultDBConnection() #5 /path/to/ojs/lib/pkp/classes/db/DBConnection.inc.php(227): DBConnection->__construct() #6 /path/to/ojs/lib/pkp/classes/core/PKPApplication.inc.php(175): in /path/to/ojs/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php on line 456

**Comment by diegoabadan** [comment]
in config.inc.php change mysql to mysqli. 

Like https://github.com/pkp/ojs/blob/master/config.TEMPLATE.inc.php#L131

**Comment by asmecher** [comment]
^ @diegoabadan's suggestion is the correct solution -- use the mysqli driver.

**Comment by maxram** [comment]
Thanks. it works. The installer selection to mysqli not work, as you suggest we need manual edit.

**Comment by asmecher** [comment]
@maxram, can you describe that issue in more detail? What happens when you choose MySQLi in the installer form?

**Comment by YUG3N** [comment]
me funciono la selección de driver mysqli manualmente en windows10
