### ISSUE TITLE
Make Purchase New Subscription link more visible and visible when not logged in

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4700]
For journals using subscriptions in OJS 3.1, the Subscriptions page created dynamically by OJS displays the different subscription types and, if the user has an account and is logged in, a link to "Purchase New Subscription" below each type.  A user must have an account and be logged in to purchase a subscription.  It would be better if the link to "Purchase New Subscription" appeared to the right of each subscription type, to be more visible, and maybe say something brief like "Buy."  It would also be preferable if all users could see this link and if a non-logged-in user clicks on it they are taken to a page to create an account or log in and then can buy a subscription.  Otherwise it's not clear that non-logged-in users can buy a subscription.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
