### ISSUE TITLE
Create new reviewer "suggest username" button is broken

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4702]
See https://forum.pkp.sfu.ca/t/ojs-3-1-2-suggest-a-username-for-new-reviewer-outputs-uundefined/52437 for details.

When pressing the "suggest" button, the field is filled with "uundefined".

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/4703

@NateWr, would you mind reviewing this?

**Comment by NateWr** [comment]
:+1:

**Comment by NateWr** [comment]
Merged and cherry-picked to `master`.
