### ISSUE TITLE
modifyStyle() from grandchild removes child's LESS styling

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4704]
Tested on OJS 3.1.2 with the child of Manuscript child theme, e.g.: https://github.com/Vitaliy-1/manuscriptCaprew
Adding `$this->modifyStyle('stylesheet', array('addLess' => array('styles/variables.less')));` and a variable.less to correspondent directory removes original styling from a child theme - original Default Manuscript theme that is a child of the Default.
Related to: https://forum.pkp.sfu.ca/t/trouble-creating-grandchild-theme/52803

**Comment by reaganch** [comment]
Just wanted to check if anyone's managed to take a look at this. This issue is really holding our site development up. Any advise would be much appreciated. Thanks!

**Comment by reaganch** [comment]
Sorry for the repeated comments here, but any chance this may be fixed any time soon? This is really holding us up at the moment. Thanks!

**Comment by Vitaliy-1** [comment]
I think changing `array_merge` function to `array_merge_recursive` here in `modifyStyle` [method of ThemePlugin class](https://github.com/pkp/pkp-lib/blob/ab6ac9fbc58b5a700c80410011032b546aea08e4/classes/plugins/ThemePlugin.inc.php#L229) will solve the problem.

**Comment by NateWr** [comment]
PR from @reaganch:
https://github.com/pkp/pkp-lib/pull/6191

Tests:
https://github.com/pkp/ojs/pull/2861

**Comment by NateWr** [comment]
Thanks @reaganch! Merged and backported to `stable-3_2_1`. :tada:
