### ISSUE TITLE
Fix issue cover image size in default theme

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4705]
The styles for the issue cover image were changed in a commit for 3.1.2 (https://github.com/pkp/ojs/commit/fa16697d1f5e77562f349df98e32c376d0dca28b#diff-20b130338b52d8575cb07eafd972d63a), and the size of the issue cover image is no longer restricted. ([Reported](https://forum.pkp.sfu.ca/t/manuscript-child-theme-issue-cover-is-too-big/52758/4))

They were probably removed by accident while cleaning up other `.cover` styles, and should probably just be restored.

**Comment by thinkbulecount2** [comment]
Hi @NateWr, PR here: https://github.com/pkp/ojs/pull/2397

**Comment by NateWr** [comment]
Thanks @thinkbulecount2! Merged.

**Comment by NateWr** [comment]
It looks like we missed the styles for desktop when we restored the cover image styles. See: https://forum.pkp.sfu.ca/t/manuscript-child-theme-issue-cover-is-too-big/52758/6

The styles that need to be restored are here:

https://github.com/pkp/ojs/commit/fa16697d1f5e77562f349df98e32c376d0dca28b#diff-20b130338b52d8575cb07eafd972d63aL90-L141

They should be applied to media queries larger than `@screen-tablet` and `@screen-desktop`, respectively.

**Comment by thinkbulecount2** [comment]
PR: https://github.com/pkp/ojs/pull/2518

cc: @NateWr
