### ISSUE TITLE
update for fr_FR

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#4707]
Hi all, 

Some PRs:
pkp-lib: #4706
ojs: pkp/ojs#2371
makeSubmission: pkp/makeSubmission#27
translator : pkp/translator#50

mainly based on fr_CA with minor adaptations

I think there are usable for 3_1_2 too

**Comment by NateWr** [comment]
Closing this as outdated. We are now managing translations through [weblate](https://translate.pkp.sfu.ca).
