### ISSUE TITLE
Add option to include git repo for plugins installed via plugin gallery

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4708]
Hi @asmecher and @NateWr, adding a placeholder here to track our discussion.

Background: For git-based OJS/OMP installs, it would be helpful to be able to track plugin gallery installed plugins via git. This would allow systems staff to track plugin customizations via commits against their respective plugins and branches. Likewise, it would allow systems staff to be able to systematically apply patches to plugin gallery plugins as bugs are fixed and patches are released (e.g. for security vulnerabilities).

One option would be to allow systems staff to disable the plugin gallery so that all plugins have to be managed manually via git as part of the wider install environment (i.e. SA/JM would no longer be able to install plugins via the gallery). 

Another option would be to allow systems staff to toggle a new set of config.inc.php settings (i.e. git path, include plugin git repos) that would enable the inclusion of git repos along with plugin files for plugins installed via the gallery. If enabled, the plugin gallery installer/updater could download the plugin .git folder and checkout the plugin branch that corresponds to the OJS/OMP version.

See also [Auto-upgrade installed plugin gallery plugins during upgrade](https://github.com/pkp/pkp-lib/issues/4679)

**Comment by mfelczak** [comment]
Note: made a few edits above.

**Comment by asmecher** [comment]
Will need some consideration related to https://github.com/pkp/pkp-lib/issues/1832 -- some plugins have composer dependencies that are not "safe" for distribution within the web root of the application, so a straight-up git clone might expose those. Plus the installer would need to take care of dependency installs, e.g. composer but also Vue compilation, etc.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [discussions area](https://github.com/pkp/pkp-lib/discussions).
