### ISSUE TITLE
Navigation Menu Item Edit - Custom NMIs lose title after submitting form with same title

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#4709]
When editing a custom NMI, by leaving the title as is, the update function resets the "title" setting for that NMI, erasing the title because no titleLocaleKey setting is found for custom NMIs (and no fallback title translation exists for custom NMIs)

**Comment by defstat** [comment]
@NateWr 

**PRs**

[pkp-lib]: #4711
[OJS]: pkp/ojs#2372
[OMP]: pkp/omp#665

**Comment by NateWr** [comment]
Looks good @defstat. The same test failed on OJS/OMP so I've restarted them. Let me know when they pass and I'm happy to merge this. :+1:

**Comment by defstat** [comment]
@NateWr Tests have passed but a rebase was needed. Waiting for the tests to pass again.

**Comment by defstat** [comment]
@NateWr Tests have passed - Branches have no conflicts.

**Comment by NateWr** [comment]
Thanks @defstat, merged to master! It doesn't cherry-pick cleanly into `stable-3_1_2` so would you pull your changes in there and issue a PR to pkp-lib's `stable-3_1_2` branch, as well as a quick PR to run the tests in OJS?

**Comment by defstat** [comment]
@NateWr 

PRs [Stable 3.1.2]
[pkp-lib]: #4719 
[OJS]: pkp/ojs#2378
[OMP]: pkp/omp#667

**Comment by NateWr** [comment]
Thanks! Merged, closing.
