### ISSUE TITLE
Search default's today's date as Start Date / End Date

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4713]
**Describe the bug**
Search results screen / advanced search screen populates todays date into the earliest and latest publication date field.  This will truncate all subsequent searches.   Probably the result of Smarty 2 to Smarty 3 migration.

Smarty 3 [`html_select_date`](https://www.smarty.net/docs/en/language.function.html.select.date.tpl) `time`:
> Omitting this parameter or supplying a falsy value will select the current date. To prevent date selection, pass in NULL

Smarty 2 [`html_select_date`](https://www.smarty.net/docsv2/en/language.function.html.select.date.tpl) `time`:
No mention of empty-ish values.

**To Reproduce**
1. Enter content in frontend search input.
2. Retrieve results, note that "Published After" and "Published Before" is today.
3. Click search again.
4. Note that anything not published today is removed.

**What application are you using?**
 OJS 3.1.2

**Additional information**
https://github.com/pkp/ojs/blob/e54ef30ed4bc7db2178c67e4afd53401b49d8344/pages/search/SearchHandler.inc.php#L70
sets the empty-ish value of "--".

**Comment by asmecher** [comment]
Committed and back-ported -- thanks, @ctgraham!
