### ISSUE TITLE
[OJS] Generic issues

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#4717]
Environment: OJS/master
Browser: Chrome

- Generic: Absolute URLs in the help sidebar are being considered as relative URLs, so they are not redirecting to the right resource.
- Issues: When creating a new issue, it's missing validation on the fields (if I set the volume field with "XYZ" and save, it will raise an internal error which is not forwarded to the user).
- Issues: When trying to upload a cover image to an issue it raises an error.
- User & Roles: Missing the translation for the "grid.action.removeUserGroup" key.
- Submissions: After expanding a submission and clicking on the button "Activity Log & Notes", the modal window is displayed with the title "undefined".
- Add/Update discussion: Participants are displayed as "Name, Role", the administrator is displayed as "Name,"

**Comment by asmecher** [comment]
@jonasraoni, could you file these one at a time? I think several have already been resolved, and they'll be easier to manage if each issue gets its own entry. Thanks!

**Comment by jonasraoni** [comment]
I was in doubt if I should spam or not. I'll pull the updates and check what's already solved :)
