### ISSUE TITLE
PKPString and Stringy\Stringy objects

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4722]
**Describe the bug**
`PKPString` promises to return `string` types, but actually returns `Stringy\Stringy` objects.

**To Reproduce**
1. Read the docs.
* https://github.com/pkp/pkp-lib/blob/41216c3b54791beb0199eae2bb4c849487ecd45d/classes/core/PKPString.inc.php#L164
* https://github.com/pkp/pkp-lib/blob/41216c3b54791beb0199eae2bb4c849487ecd45d/classes/core/PKPString.inc.php#L173
* https://github.com/pkp/pkp-lib/blob/41216c3b54791beb0199eae2bb4c849487ecd45d/classes/core/PKPString.inc.php#L182
* https://github.com/pkp/pkp-lib/blob/41216c3b54791beb0199eae2bb4c849487ecd45d/classes/core/PKPString.inc.php#L191
2. Read the code.
* https://github.com/pkp/pkp-lib/blob/41216c3b54791beb0199eae2bb4c849487ecd45d/classes/core/PKPString.inc.php#L167
* https://github.com/pkp/pkp-lib/blob/41216c3b54791beb0199eae2bb4c849487ecd45d/classes/core/PKPString.inc.php#L176
* https://github.com/pkp/pkp-lib/blob/41216c3b54791beb0199eae2bb4c849487ecd45d/classes/core/PKPString.inc.php#L185
* https://github.com/pkp/pkp-lib/blob/41216c3b54791beb0199eae2bb4c849487ecd45d/classes/core/PKPString.inc.php#L194
3. Scratch head.

**What application are you using?**
 OJS or OMP version 3.1.2

**Additional information**
These `Stringy\Stringy` objects can make their way into illegal array indexes:
https://github.com/pkp/pkp-lib/issues/4720

**Comment by ctgraham** [comment]
@asmecher , are the `Stringy\Stringy` objects intended for use downstream anywhere, or can we just cast to strings in these functions?

**Comment by asmecher** [comment]
I'm OK with a cast to string; I don't think we have any downstream use for them (and can deal with that later).

**Comment by asmecher** [comment]
Merged and cherry-picked back to `stable-3_1_2` -- thanks, @ctgraham!
