### ISSUE TITLE
Decision dates in Articles report are possibly busted

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#4725]
**Describe the bug**
In reviewing the articles report and what was implemented in #2820, @alexxxmendonca and @johnbarneson1 and I have stumbled upon some possible bugs with editor decisions and decision dates: 

- dates may not be listed in order
- having editors make decisions to move to production or elsewhere may create a "decision" column in the csv file, but with a blank date - these shouldn't be recorded as such, as they aren't actual decisions. 

Note to self/others: we need to review and test this further. 

**To Reproduce**

**What application are you using?**
 OJS or OMP version X.X.X

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.
