### ISSUE TITLE
[Sprint/UIUX] New User Registration - New User Landing Page Exploration

### ISSUE THREAD

**Issue by robertbeanstalk** [pkp/pkp-lib#4729]
**Describe the problem you would like to solve**
A new self registered user is assigned the "Reader" role by default. What is the appropriate page for this user to be directed to after registration? Should they be directed to the "start a submission" page?

**Describe the solution you'd like**
Is there an opportunity for an orientation page for all new self registered users to go to that provides orientation information?

**Who is asking for this feature?**
UIUX Spring Sprint  

**Additional information**
What is the purpose that most users log in for? Is it to become a registered user of the journal or to submit an article?

**Comment by NateWr** [comment]
This is the current page where the user is directed after orientation.

![Selection_060](https://user-images.githubusercontent.com/2306629/57368009-0aa84d80-7182-11e9-800a-e07189ffcd15.png)

Can you let me know what you'd like to see added, removed, changed?

> Is it to become a registered user of the journal or to submit an article?

In most cases, I think most users are registering to submit an article. In some cases, they may be registering to express an interest to be a reviewer. The Reader role is not used much any more, but it may be used to receive email notifications of new issues (though few journals advertise this so few readers know about it).

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
