### ISSUE TITLE
[Sprint/UIUX] New User Self Registration Form - Not All Required Fields Marked

### ISSUE THREAD

**Issue by robertbeanstalk** [pkp/pkp-lib#4730]
**Describe the bug**
Agreement to privacy statement should be clearly marked as a required field (currently does not have a red asterisk, looks optional). Easily confused with optional fields located in the same area of the form. Failure to check the box results in failure of submission of the form.

**To Reproduce**
Do the new user self registration process.

**What application are you using?**
 OJS  3.2

**Additional information**
﻿
<img width="501" alt="Screen Shot 2019-05-07 at 2 26 31 PM" src="https://user-images.githubusercontent.com/39746089/57334286-235a2a00-70d4-11e9-886c-cc69519c291a.png">

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
