### ISSUE TITLE
[Sprint/UIUX] Add list of of associated files to choose what to send during next round of reviews

### ISSUE THREAD

**Issue by thinkbulecount2** [pkp/pkp-lib#4731]
**Describe the problem you would like to solve**
When going to the next round of reviews, often the files originally associated with the review are not automatically attached. This requires an extra workflow or could be a missed step by editors for them to be able to easily access or find those files.

**Describe the solution you'd like**
When going to the next round of review(s), add the list of associated files with check boxes so that the editors can choose what to send to the next round of reviews.

**Who is asking for this feature?**
Journal Editors

**Comment by NateWr** [comment]
The typical workflow is that an author will submit revisions, and it is these revisions that should be automatically forwarded to a second round of reviews. I just did a quick test and revision files are being forwarded by default (they are pre-selected for forwarding during the new review round modal).

I'll close this as already fixed but let me know if I've misunderstood the report!
