### ISSUE TITLE
[Sprint/UIUX] New Submission Step 1 - Consider confirming all required fields with one button

### ISSUE THREAD

**Issue by robertbeanstalk** [pkp/pkp-lib#4732]
**Describe the problem you would like to solve**
A check box for each requirement seems redundant and perhaps not a great use of the user's time.

**Describe the solution you'd like**
Since agreement is required for all fields, use just one button for the whole set of the requirements rather than requiring confirmation for each requirement. 

**Who is asking for this feature?**
UIUX Spring Sprint

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by NateWr** [comment]
I presume you mean the "Submission Requirements" list, correct?

**Comment by NateWr** [comment]
This is solved in #7191, which will be included in 3.4.
