### ISSUE TITLE
[Sprint/UIUX] Reviewer Assignment vs. Adding Participant

### ISSUE THREAD

**Issue by thinkbulecount2** [pkp/pkp-lib#4733]
**Describe the problem you would like to solve**
There are two ways to assign a reviewer in the Review section. (Add Reviewer under the "Reviewers" column, and the "Assign" button on the "Participants" column on the right) What is the difference between a participant and a reviewer? This confuses editors, and often if they add a reviewer through the Participants column, this does not kick off the Reviewer workflow which is what they usually want to access.

<img width="599" alt="Screen Shot 2019-05-07 at 14 46 57" src="https://user-images.githubusercontent.com/38994650/57335305-04a96280-70d7-11e9-9b59-da62cbe558b0.png">

**Describe the solution you'd like**
Consider revising or re-implementing all text links as buttons, differentiating them, or maybe even removing or moving the Participants column and re-evaluating their use case on this view.

**Who is asking for this feature?**
Journal Editors

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.
