### ISSUE TITLE
[Sprint/UIUX] New Submission Step 1 - General UIUX interface considerations

### ISSUE THREAD

**Issue by robertbeanstalk** [pkp/pkp-lib#4734]
**Describe the problem you would like to solve**
Shows submission steps across the top of the page with current step highlighted, looks like a tabbed navigation menu, but it is not.

Save and continue button is at the bottom of page and featured in low contrast. List at top of page may confuse user as to how to navigate to the next step in the process. 

**Describe the solution you'd like**

Make the list of steps across the top of the view port look less like a navigation menu and more like a status notice.

Make the "save and continue" button higher contrast or possibly more prominent in some way.

**Who is asking for this feature?**
UIUX Spring Sprint

**Additional information**

**Comment by NateWr** [comment]
These suggestions were implemented as part of https://github.com/pkp/pkp-lib/issues/7191.
