### ISSUE TITLE
Add autocompletion of search phrase to lucene plugin

### ISSUE THREAD

**Issue by Stefanvdb** [pkp/pkp-lib#4741]
In order to add autocompletion to the Lucene Plugin some changes are needed in .tpl files. 
Pull request will follow.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/ojs/pull/2380

**Comment by asmecher** [comment]
Thanks, @Stefanvdb! That's a good new pattern established. I've merged and also ported to `stable-3_1_2` for the OJS 3.1.2-1 release.
