### ISSUE TITLE
Unable to Upload/Select Files from Copyediting stage

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#4754]
If, in a submission, a file is attached to a discussion then in Copyediting it is not possible to use “Upload/Select Files” from Copyediting stage.

It happens that the window opens but does not load the part for uploading or selecting files.
![Screenshot-2018-12-17 Web of Science  v 5 31  - Citation Report](https://user-images.githubusercontent.com/27674815/57630400-36726b80-75a6-11e9-90e8-e676ef1c60d7.png)
Picture is taken from a different user with same problem at https://forum.pkp.sfu.ca/t/unable-to-upload-select-files-from-copyediting-stage/53195

Thanks to the contributors of this great Project. Best regards.

**Comment by ptrckb** [comment]
This is the same issue as #4179 but resurfacing when uploading/selecting files: deleting/cancelling a query has left a file orphan. The fix below makes the file selector ignores these files.

OJS: pkp/ojs#2396
PKP: pkp/pkp-lib#4761

**Comment by eniocarboni** [comment]
Yes, I too have locally fixed the problem temporarily in this way, ignoring the problem file.
But the problem is that in this way we exclude from the list all the files that are attached to any discussion (and not just those of deleted discussions).

**Comment by ptrckb** [comment]
Are you sure? The purpose of this patch is to list a file **only** if it can be linked to a discussion. So it effectively filters out any dangling files but does include any regular one.

**Comment by eniocarboni** [comment]
@ptrckb  I have just redone the tests and everything works.
I apologize but I don't know why it seemed to me that I had done the same test a few days ago and it seemed negative.
I agree that it works for me

**Comment by Baytan** [comment]
I also approve that with the revision at https://github.com/pkp/ojs/pull/2396/files the problem is solved. thank you very much.

**Comment by asmecher** [comment]
Thanks, all, and particularly to @ptrckb for contributing!
