### ISSUE TITLE
Adding a Custom Page NMI with a slash in the path fails on display

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4756]
**Describe the bug**
Adding a Navigation Menu Item (e.g. Custom Page) with a path which contains a slash will save correctly and resolve correctly, but will not display correctly.  When displayed as a NMI, the path's slash character will be escaped. 

**To Reproduce**
1. Go to Settings, Website, Navigation Menus.
2. Add a new Navigation Menu Item, type Custom Page, with path "test/path/here".
3. Add new NMI to a menu.
4. View the menu.
5. Click on the NMI, directed to `base_url` + "test%2fpath%2Fhere".
6. Change %2F to "/" to confirm that routing would have worked.

**What application are you using?**
 OJS or OMP version 3.1.2

**Additional information**
Call stack:

https://github.com/pkp/pkp-lib/blob/b67bc930695bcd67f8ed469ef37f597203998f0f/classes/services/PKPNavigationMenuService.inc.php#L330-L336

parameter 4 (`$handler`) is "test/path/here":

https://github.com/pkp/pkp-lib/blob/b67bc930695bcd67f8ed469ef37f597203998f0f/classes/core/Dispatcher.inc.php#L157

parameter 3 (`$page`) is "test/path/here" until encoded:

https://github.com/pkp/pkp-lib/blob/b67bc930695bcd67f8ed469ef37f597203998f0f/classes/core/PKPPageRouter.inc.php#L307-L309

See also https://github.com/pkp/pkp-lib/issues/4542 for a similar but distinct scenario.

**Comment by ctgraham** [comment]
The static pages plugin gets away with this because it never constructs a URL though the router.  It only interprets URLs.

How much to we trust the user's entry here?  If we allow slashes and pass them to the Dispatcher as a `$path` instead of the `$handler`, do we open ourselves to URL injection?  I don't think so, because each path component is urlencoded:
https://github.com/pkp/pkp-lib/blob/b67bc930695bcd67f8ed469ef37f597203998f0f/classes/core/PKPPageRouter.inc.php#L255-L259

**Comment by NateWr** [comment]
Not necessary for 3.1.2-1, but before we close this issue, can we add some validation here that tells the user if they enter too many slashes? It looks like maybe we just support 2 slashes in the path at most?

**Comment by ctgraham** [comment]
The first two path components need to move to the page and op, but all remaining path components can be (and are) stacked in the params.  It should work with an arbitrary number of slashes.

**Comment by NateWr** [comment]
Merged and cherry-picked into `master`. Thanks @ctgraham!
