### ISSUE TITLE
Add support for COUNTER 5 Unique_Item_Requests specification

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4760]
**Describe the problem you would like to solve**
The [Counter 5 specification](https://www.projectcounter.org/code-of-practice-five-sections/4-1-usage-reports/#titlereports) identifies a `Unique_Item_Requests` metric, which de-duplicates multiple requests to different galleys in a submission, but we do not store metrics in the database in this way.

**Describe the solution you'd like**
The metrics table should store metrics in a way that allows us to de-duplicate these requests.

**Who is asking for this feature?**
Publishing services and partners that provide COUNTER reports.

**Additional information**
The specification says:

> The Unique_Item_Requests provides comparable usage across journal platforms by reducing the inflationary effect that occurs when an HTML full text automatically displays and the user then accesses the PDF version. The Total_Item_Requests shows overall activity.

My understanding of the specification (which is not at all certain!) is that it addresses this situation:

1. User visits the article's abstract page _when it is also the full-text HTML galley_.
2. User visits the article's PDF galley.
3. These two visits should be counted as one.

**Comment by NateWr** [comment]
A few thoughts:

1. If I read this correctly, it should only apply in cases where the abstract page also displays the full-text. Since this is up to the theme, we can not determine when it should be applied. It will be up to the journal.

2. We probably want to keep the counts distinguished for our own UI, so that journal managers can see how many times a PDF vs a landing page have been accessed. We won't want to hide views from them, because the comparison may be important. For this reason, we probably need a new row in the metrics table to count this combined total.

3. I don't have a clear grasp of the spec, but this may only apply to the Journal Report, which would significantly reduce the number of rows needed in the metrics table. If we also track it on a per-submission basis, we may want to consider offering only monthly, if that's permissible according to the COUNTER specs.

**Comment by bozana** [comment]
Closing this issue because it is handled here https://github.com/pkp/pkp-lib/issues/6781
