### ISSUE TITLE
piwik (matomo) plugin -  malformed URL

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4763]
**Describe the bug**
https://forum.pkp.sfu.ca/t/ojs-v3-1-2-piwik-plugin-error/53349/2
> OJS seems to change the piwik url which I insert into the configuration of the plugin. It changes the url from `https://piwik.ub.uni-muenchen.de` to `//https://piwik.ub.uni-muenchen.de/`

**To Reproduce**
1. Enable and configure piwik plugin
2. View HTTP requests made against matomo URL

**What application are you using?**
 OJS or OMP version 3.1.2

**Additional information**
Piwik plugin Settings form requires a URL:
https://github.com/pkp/piwik/blob/910bfd6b6464fb383dc7d476771d9551b8d6b308/PiwikSettingsForm.inc.php#L38
as of
https://github.com/pkp/piwik/commit/e78646c16512070379884df6c82d983de49355b1

This setting is used as if it is a DNS name, or DNS name + path:
https://github.com/pkp/piwik/blob/910bfd6b6464fb383dc7d476771d9551b8d6b308/PiwikPlugin.inc.php#L122

**Comment by ctgraham** [comment]
If we let (require) the user enter a full URL with protocol, we'll need to either require this be https to prevent failure of mixed protocol requests, or we'll need to strip the protocol before usage.

If we let the user enter just a arbitrary DNS + path, we need to clarify the expectation within the form.  The form error currently says "http://" is required.
https://github.com/pkp/piwik/blob/910bfd6b6464fb383dc7d476771d9551b8d6b308/locale/en_US/locale.xml#L24

**Comment by ctgraham** [comment]
@dennmuel , @mpbraendle, can you test the proposed PR?

**Comment by mpbraendle** [comment]
Works on our test server. Thank you.

**Comment by dennmuel** [comment]
Same here. :) Thanks!

**Comment by asmecher** [comment]
Thanks, @ctgraham!

**Comment by asmecher** [comment]
Added a new release of Piwik ([v1.0.2-1](https://github.com/pkp/piwik/releases/tag/v1.0.2-1)) to the plugin gallery with this fix included.
