### ISSUE TITLE
[OCS]

### ISSUE THREAD

**Issue by ipaddr** [pkp/pkp-lib#4764]
Hi happy to join the community, 

I just jump into ocs and this is awesome software. Happy to learn to develop using it.
I face some issue thought, when a paper has been reviewed by reviewer and assign back to track director and then followup back to author, when author click the review link, the page shown nothing. Screen shot as below:

After got revision, author login back to system to see the review detail
![Screenshot (1)](https://user-images.githubusercontent.com/5902218/57746303-cc1f0f80-76fa-11e9-9c9a-fabc72a1b0fb.png)

Author wan to see the review detail by clicking the review link
![Screenshot (2)](https://user-images.githubusercontent.com/5902218/57746307-d17c5a00-76fa-11e9-8ae7-77250f17d5f8.png)

Some how the link did not show nothing
![Screenshot (3)](https://user-images.githubusercontent.com/5902218/57746309-d5a87780-76fa-11e9-90a5-1a4b064fbf2e.png)

Looking forward to any support on how to resolve this and thank in advance

**Comment by asmecher** [comment]
@ipaddr, is there anything in your PHP error log?
