### ISSUE TITLE
OJS Manual payment plugin should notify the subscription manager and not the primary contact

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4770]
**Describe the bug**
At the moment the manual payment plugin sends emails to the journal primary contact. It should send them to the subscription manager instead.

https://github.com/pkp/ojs/blob/master/plugins/paymethod/manual/ManualPaymentPlugin.inc.php#L145-L149

Should be (and maybe use the primary contact address as a backup if subscription manager address not given):

```
$subscriptionName = $context->getSetting('subscriptionName');
$subscriptionEmail = $context->getSetting('subscriptionEmail');
$mail = new MailTemplate('MANUAL_PAYMENT_NOTIFICATION');
$mail->setReplyTo(null);
$mail->addRecipient($subscriptionEmail, $subscriptionName);
```

**What application are you using?**
OJS 3.1.1.4 and any later version

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
