### ISSUE TITLE
Record editorial desition button don't work. Process freeze and still waiting

### ISSUE THREAD

**Issue by cmmartinezm** [pkp/pkp-lib#4771]
![error](https://user-images.githubusercontent.com/49250425/57862747-ddcde900-77c6-11e9-87aa-2991f1609453.jpg)

When you press the record editorial desition button. The form dont' do nothing and freeze waitining,  any ideas to check ?

**Comment by asmecher** [comment]
@cmmartinezm, this area is more for feature requests and bug tracking than for general support. The support forum (https://forum.pkp.sfu.ca) is a better place to get assistance. I'd suggest checking your PHP error log for details, and posting your question plus the results from the log over there.
