### ISSUE TITLE
Permit the "merge users" CLI tool to handle multiple users at once

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4772]
Currently the "merge users" CLI tool can only handle a single user at a time. Users must also be specified by username, and it may be desirable to specify them by user ID.

Extend it to potentially handle several users at a time, and to handle specifying users by ID as well as by name.

**Comment by asmecher** [comment]
Also shares the merge users tool in pkp-lib, where it was previously duplicated in each application.

PRs:
- https://github.com/pkp/ojs/pull/2402
- https://github.com/pkp/pkp-lib/pull/4773/files

**Comment by asmecher** [comment]
@NateWr, would you mind having a look at this?

**Comment by NateWr** [comment]
Looks good! :+1:

**Comment by asmecher** [comment]
Thanks, @NateWr!

**Comment by asmecher** [comment]
(Also ported to OMP master.)
