### ISSUE TITLE
Fix magic numbers in SubmissionsListItem.vue

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4774]
There are magic numbers in `SubmissionsListItem.vue`: https://github.com/pkp/ui-library/blob/eb97681747bfa6d5e12de7df56c082bfd0f6d0ce/src/components/ListPanel/submissions/SubmissionsListItem.vue#L390

Use defined constants instead.

**Comment by NateWr** [comment]
Implemented in #5865
