### ISSUE TITLE
jquery is loaded from Google and cannot be accessed from China

### ISSUE THREAD

**Issue by hsluoyz** [pkp/pkp-lib#4778]
When I open the install page, I keep seeing the eternally loading. Then I found the page is trying to load jquery libraries from googleapis.com, which is blocked in China.

http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js

![image](https://user-images.githubusercontent.com/3787410/57961458-b0597a80-7941-11e9-8354-ab616faf2c0d.png)

![image](https://user-images.githubusercontent.com/3787410/57961562-61601500-7942-11e9-88ea-578edece10a6.png)

Can we change this (and any other dependency on googleapis.com if exists) to: https://code.jquery.com/ as this is enough fast in China? Thanks.

**Comment by asmecher** [comment]
@hsluoyz, I don't have an opinion on one CDN vs. another, but you should be able to turn off `enable_cdn` in `config.inc.php` to use local copies.

**Comment by hsluoyz** [comment]
Thanks @asmecher , I have solved it by setting ``enable_cdn`` to off.
