### ISSUE TITLE
Add additional details to email notification subject

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4782]
**Describe the problem you would like to solve**

Editors would like to easily distinguish different types of notification emails.

From one of our hosted journals:
"Could you kindly change the default subject of "New Activity Notification" to the ACTUAL activity? For instance, when someone reviews, "New Review submitted on Paper 212..." Similarly when someone accepts to review. The 'New activity notification' is quite meaningless otherwise. Some of these are urgent activities that we should look at and others can wait."

**Describe the solution you'd like**
Replace generic activity notification email subjects with detailed email subjects that refer to the submission id, stage, and activity.

**Who is asking for this feature?**
Editors

**Comment by NateWr** [comment]
We have converted some of these "new notification" emails to more specific mailables for 3.4. I'll close this but feel free to open an issue with a specific proposal about a specific email that could be improved.
