### ISSUE TITLE
[OJS] Modal window with "undefined" title

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#4785]
A modal window is displayed with the title "undefined"

**Reproduction**
Access a submission, expand it, then click on the button "Activity Log & Notes"

**Environment**
OJS/master
PHP 7

**Comment by asmecher** [comment]
@jonasraoni, do you see anything relevant in the PHP error log?

**Comment by jonasraoni** [comment]
@asmecher I've already fixed these issues that I opened, I'll send a PR tomorrow. The other problems that I saw were fixed by previous commits :)

**Comment by asmecher** [comment]
@jonasraoni, ah, good -- if you already have a fix for something you're filing, maybe just add "PR coming soon" in the description.

**Comment by asmecher** [comment]
Thanks, @jonasraoni! Merged and cherry-picked back to `stable-3_1_2` as well for the 3.1.2-1 releases (due next week).
