### ISSUE TITLE
Validation broken on front end institutional subscription purchase form

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#4788]
The validation on the front end user subscription form is broken in 3.1.2. To reproduce, enable manual payments and create an institutional subscription type, and then attempt to sign up for one using only a range of IP addresses. 

This form class is one of the only places in the OJS code base that uses a FormValidatorArrayCustom validator for the ip range, and I'm not sure it works correctly.  Because the form uses a single line text field for IP addresses, the call to explode that splits on \r\n doesn't work and certain arrays are never created.  

Fix incoming.

**Comment by asmecher** [comment]
Thanks, @jnugent. Does this resolve https://github.com/pkp/pkp-lib/issues/3439#issuecomment-428845953?

**Comment by jnugent** [comment]
@asmecher  I believe so!  With this fix, if you submit the form with a malformed IP range you receive the error:

"Please enter a valid IP range"

Importantly, the fix also still correctly validates the IP field if a valid domain is also entered i.e. you can't submit the form, even if a domain is entered, when the IP field fails validation.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/ojs/pull/2408/commits
Merged and cherry-picked forward to `master`. Thanks, @jnugent!

**Comment by AndrewSwann** [comment]
Thanks, this looks very promising, but I am just an end user, and can't test the code.  However line 152 of classes/subscription/form/UserInstitutionalSubscriptionForm.inc.php now reads
```
) return false; return true;
```
which seems strange and/or redundant.

**Comment by asmecher** [comment]
Thanks, @AndrewSwann. The `return true;` should be on the next line, and I've fixed that, but it's just cosmetic. The `return false` is attached to the `if` statement; the `return true` applies otherwise.
