### ISSUE TITLE
[OJS] APA plugin shouldn't include "capitalize" Smarty parameter for journal name

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#479]
Line 22 of plugins/citationFormats/apa/citation.tpl is: 

<em>{$journal->getLocalizedTitle()|capitalize} ... etc.

The journal title shouldn't be capitalized by any APA convention I know, and its usage is causing some problems with journal titles with accented characters. I would recommend that the capitalize parameter be removed entirely. But should that title be otherwise sanitized?

**Comment by asmecher** [comment]
No objections to removing it here, James. No sanitization required.

**Comment by jmacgreg** [comment]
Thanks, will do.

J



On Wed, Apr 22, 2015 at 9:15 AM, Alec Smecher <notifications@github.com>
wrote:

> No objections to removing it here, James. No sanitization required.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pkp/pkp-lib/issues/479#issuecomment-95252999>.
>



-- 

James MacGregor
Publishing Services Coordinator
Public Knowledge Project (PKP)
Twitter: @jmacgreg
Skype: j.macgreg

**Comment by asmecher** [comment]
James, I suspect this one slipped off the side of your desk. If you want me to tackle it, feel free to reassign to me.

**Comment by jmacgreg** [comment]
Oops, thanks - will fix!

**Comment by jalperin** [comment]
We really should just implement citeproc js

Juan

**Comment by asmecher** [comment]
@jmacgreg, I've cherry-picked the following commit into ojs-dev-2_4:
https://github.com/jmacgreg/ojs/commit/9f6c64b1ea09f53fa90f85bc062764b5345bac82

Is that all that's required for this issue? If so, please close it.

**Comment by jmacgreg** [comment]
Thanks!
