### ISSUE TITLE
Filter email templates by workflow stage

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4796]
**Describe the problem you would like to solve**
Editors would like to be able to filter the email templates list by those which are related to one or another workflow stage.

**Describe the solution you'd like**
Add filters to the existing email templates list. Since some templates are not used in the workflow, there should be one or more filters or other templates (eg - Registration).

**Who is asking for this feature?**
It was part of the initial request of #2906 and is a common community request.

**Additional information**
Information on the workflow stage has been added to the docs hub. https://docs.pkp.sfu.ca/learning-ojs/en/settings-workflow#template-descriptions

**Comment by Vitaliy-1** [comment]
@NateWr, is the information about what workflow stage template is associated with stored somewhere? Cannot find it in `email_templates...` tables.

**Comment by NateWr** [comment]
No, this information doesn't exist in the application yet. A list was created at a sprint and now lives on the docs hub here: https://docs.pkp.sfu.ca/learning-ojs/en/settings-workflow#template-descriptions

Some discretion will probably need to be used to determine which stages identify there make sense, and then they'll need to be added to the email template xml files and an update script will need to provide the data.

**Comment by Vitaliy-1** [comment]
Should those stages correspond to `WORKFLOW_STAGE_ID_...` constants? I see some differences in the number of stages, e.g., 2 review stages in the latter (internal and external), and semantics - published instead of postproduction.  

Regarding templates XML file, it should look something like:
```
<email key="SUBMISSION_ACK" can_edit="1" can_disable="1" to_role_id="65536" workflow_stage="1" subject="emails.submissionAck.subject" description="emails.submissionAck.description" body="emails.submissionAck.body"/>
```
?

**Comment by NateWr** [comment]
Yeah, some work will need to be done to reconcile the list in the docs with technical requirements. I'd recommend `stage_id` instead of `workflow_stage_id`, but you've got the idea.

**Comment by Vitaliy-1** [comment]
If join by OJS's workflow stage id, it should be 1 (submission), 3 (external review), 4 (copyediting) and 5 (production) and null (other). I don't see that 0 (production) is used anywhere in the code. I'm not sure about (2) internal review as not familiar with other apps that use the shared library, is it safe to assume that we don't have associated templates? @NateWr, does it make sense?

**Comment by NateWr** [comment]
You'll need to implement this for OMP as well, which uses the internal review stage. You can get a list of all stages in an application with `Application::get()->getWorkflowStages()`. I think this is the only difference between OJS/OMP. OPS only has one stage, production.

I'm not aware of `0` (production) but I'm guessing it's deprecated code. Where does it appear?

Since you won't have the constants available in the XML file, you need to add a comment with the constant name so that we can identify its use. Like this:

```
<email ... stage_id="1"  /><!-- WORKFLOW_STAGE_ID_SUBMISSION -->
```

**Comment by NateWr** [comment]
Sorry missed this one:

>  is it safe to assume that we don't have associated templates?

I suspect there will be some custom templates for OMP and OPS. The best way to find these is probably to look in their email template registry and in the email templates list. If you have questions about which stage a particular template is used in, ask here and we can coordinate with Dulip and Antti-Jussi, who know those applications pretty well.

**Comment by Vitaliy-1** [comment]
> I'm not aware of 0 (production) but I'm guessing it's deprecated code. Where does it appear?
Sorry, I meant `WORKFLOW_STAGE_ID_PUBLISHED` that is defined in shared library (PKPAplication) but not used in OJS.

**Comment by NateWr** [comment]
I just did a search across all applications and it looks like this constant is dead code. It should be removed.

**Comment by Vitaliy-1** [comment]
This is mostly done. What I don't understand is how I can provide filter by `Other` category. 
Even if I leave `null` intact here: https://github.com/Vitaliy-1/pkp-lib/blob/12c53e7a8128c9939cccf2b7fb0653d52fab262a/api/v1/emailTemplates/PKPEmailTemplateHandler.inc.php#L116
Search results are still empty as if DAO class retrieve method cannot accept null as a search parameter. @NateWr, do you have an idea?

**Comment by Vitaliy-1** [comment]
The idea is to show all templates that have null value for `stage_id` in Other category

**Comment by Vitaliy-1** [comment]
Done. @NateWr, can you remind me how to make a PR to ojs and pkp-lib repo in this case? 
1. Make PR from my pkp-lib branch
2. Make PR from my ojs branch (don't include changes in pkp-lib)
3. Make PR from my ojs branch that includes only changes in pkp-lib for tests.
Or I'm missing something?

**Comment by Vitaliy-1** [comment]
PR to pkp-lib: https://github.com/pkp/pkp-lib/pull/5935

**Comment by NateWr** [comment]
Doing a code review now. The submodule commit looks good to me. What happens is that it displays _any_ changes to the submodule since the last time a submodule commit was merged. 

Since we only use the submodule commits for testing, we don't merge them to `master` when they contain no changes in OJS/OMP. We often just close that PR without merging it. Then when you load up the next submodule commit you'll see some changes to pkp-lib from those other recent changes to `master`.

Generally you don't have to worry about this. Alec or I will manage the merge itself and if there's a conflict with lib/pkp GitHub will flag this up and not let us merge.

**Comment by NateWr** [comment]
Good work! I had just a few comments to consider. Do you know if these email template changes are applied automatically during the upgrade or do we need to write an upgrade script?

**Comment by NateWr** [comment]
(I also created an OJS PR to be able to review it: https://github.com/pkp/ojs/pull/2784. I guess we'll still need one for OMP too.)

**Comment by Vitaliy-1** [comment]
Yeah, I'll need to review templates for OMP/OPS too. 
> Do you know if these email template changes are applied automatically during the upgrade or do we need to write an upgrade script?
`stage_id` column is created automatically during the upgrade but is populated with values only by the installation script. I guess it means to trigger the `installEmailTemplate` method during the upgrade, or not?

> Since we only use the submodule commits for testing, we don't merge them to `master` when they contain no changes in OJS/OMP
And if the PR contains a submodule update and commits to the app, you'll just merge those by IDs?

**Comment by NateWr** [comment]
@asmecher in this work Vitaliy has added an attribute `stage_id` to the email template XML definitions, which will go into a new table column. Will the upgrade script automatically apply that change or do we need to write an upgrade script?

**Comment by NateWr** [comment]
> And if the PR contains a submodule update and commits to the app, you'll just merge those by IDs?

We'll merge the whole PR, including the submodule commit, in those cases.

**Comment by Vitaliy-1** [comment]
In this case, should I update the submodule once again with new a commit?

**Comment by asmecher** [comment]
> @asmecher in this work Vitaliy has added an attribute stage_id to the email template XML definitions, which will go into a new table column. Will the upgrade script automatically apply that change or do we need to write an upgrade script?

This will need adjustment after I merge https://github.com/pkp/pkp-lib/issues/2493. Is this one ready to be merged soon?

**Comment by asmecher** [comment]
> @asmecher in this work Vitaliy has added an attribute stage_id to the email template XML definitions, which will go into a new table column. Will the upgrade script automatically apply that change or do we need to write an upgrade script?

This will need adjustment after I merge https://github.com/pkp/pkp-lib/issues/2493. Is this one ready to be merged soon?

**Comment by NateWr** [comment]
Vitaliy is still working on OMP/OPS but an example of how to do this for OJS would be useful for me too.

**Comment by Vitaliy-1** [comment]
I see only 1 conflict in pkp-lib and its regarding tools/schema/common.xml which is no longer present, @asmecher, should I define column name somewhere else or what is the current concept?

**Comment by Vitaliy-1** [comment]
@NateWr,

The only difference that I see in OMP is that it has internal and external review stages. If talking about email templates, it seems that there are those that can be assigned to both of these stages (e.g., reviewer assignment - REVIEW_REQUEST). Does it make sense to assign them to the external review stage just like in OJS?

**Comment by NateWr** [comment]
Hmm, good question. Are there any OMP templates that are only used in internal review? If not, then I suggest we just use external review as the `stageId` and in the UI hide the distinction (ie - call it "Review" not "External Review" in the filters list).

If there are OMP templates that are only used in internal review, but some are used in both, we may need to think about allowing more than one `stageId` per template.

**Comment by asmecher** [comment]
> I see only 1 conflict in pkp-lib and its regarding tools/schema/common.xml which is no longer present, @asmecher, should I define column name somewhere else or what is the current concept?

This is only going into OJS 3.3, correct? If so, you can add the new column to `lib/pkp/classes/migration/CommonMigration.inc.php` (for new installs), and to `lib/pkp/classes/migration/upgrade/v3_3_0UpgradeMigration.inc.php` (for upgrades). You'll also need to populate the new column on upgrade (not sure if you've worked through that yet).

**Comment by Vitaliy-1** [comment]
PR to master branch of
pkp-lib: https://github.com/pkp/pkp-lib/pull/5935
OJS: https://github.com/pkp/ojs/pull/2784
OMP: https://github.com/pkp/omp/pull/837
OPS: https://github.com/pkp/ops/pull/43

@NateWr, can you review those and merge if everything looks OK?

**Comment by Vitaliy-1** [comment]
(I've squashed commits to pkp-lib for readability)

**Comment by NateWr** [comment]
Thanks for squashing the commits! Very helpful. All PRs are merged. Nice work! :+1:

**Comment by NateWr** [comment]
@amandastevens and @kaitlinnewson this may or may not effect documentation. The docs include a list of templates with the stage they are part of at https://docs.pkp.sfu.ca/learning-ojs/en/settings-workflow#template-descriptions. But the email templates list will support filters by the stages from 3.3.

![email-template-stages](https://user-images.githubusercontent.com/2306629/84645168-17a47e00-aef8-11ea-83fe-a0cf58104072.png)

(This is thanks to the work done at a sprint or by the DIG to generate that list!)
