### ISSUE TITLE
Make download option more obvious for Citation Style Language plugin

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4799]
When a journal is using the Citation Style Language plugin to display the citation for an article and allow users to download it to a reference management tool, the download option is not easy to find. Underneath the citation is a button that says "More Citation Formats" and if you click that you get a drop-down menu with links to download the citation in various formats.  But if a user wasn't interested in seeing more citation formats and only wanted to download the citation, they could easily miss the download option.  

I suggest changing "More Citation Formats" to "Download Citation."  

A PKP|PS hosted client suggested this and I think it makes sense.

**Comment by NateWr** [comment]
Just dropping a note in here to say that a contributor updated the Bootstrap3 theme to separate these. So there were two dropdown menus: "More Citation Formats" and "Download Citation". https://github.com/NateWr/bootstrap3/pull/158 That might be a good way to handle it.

**Comment by NateWr** [comment]
Closing this as low priority. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
