### ISSUE TITLE
Allow Lucene Plugin to add Syntax-Instructions to search page

### ISSUE THREAD

**Issue by Stefanvdb** [pkp/pkp-lib#4800]
The Search syntax instructions were removed from the OJS3 standard search. But are requested for the Lucene Plugin.  In order for the lucene plugin to show the syntax instructions, a change to search.tpl is needed. Pull request will follow.
Would be great if it could be cherry-picked for OJS 3.1.2-1.

**Comment by asmecher** [comment]
Done: https://github.com/pkp/ojs/pull/2411
Thanks for contributing, @Stefanvdb!
