### ISSUE TITLE
Missing spaces in Endnote RIS template for Citation Style Language plugin

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4802]
A few OJS 3.1.1-4 users have reported that when they try to import a citation into Endnote that was downloaded from OJS with the Citation Style Language plugin, the citation does not import.  The user is asked to choose a filter but no filter results in a successful import.

One user found that adding spaces to the RIS tags in the RIS template, per the standard RIS format, solves the problem.  The solution is detailed here: https://forum.pkp.sfu.ca/t/citation-style-language-plugin-problem/49755/5

**Comment by asmecher** [comment]
Hi @amandastevens -- that's already been fixed in OJS 3.1.2 (see https://github.com/pkp/pkp-lib/issues/4448).

**Comment by amandastevens** [comment]
Ah, how did I miss that?  Thank you!
