### ISSUE TITLE
Hook PluginRegistry::loadCategory is ineffective for category jumping

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4803]
**Describe the bug**
The hook `PluginRegistry::loadCategory` is documented for allowing plugins to register a subsidiary plugin in another category:
https://github.com/pkp/pkp-lib/blob/73930d781a0e97fa5d5c9779502b868755952fa0/classes/plugins/PluginRegistry.inc.php#L131-L132

This used to be common, e.g.:
https://github.com/pkp/ojs/blob/6a61604e364217d12c56855a1b7e61f77e9e10a5/plugins/generic/externalFeed/ExternalFeedPlugin.inc.php#L38-L39
for
https://github.com/pkp/ojs/blob/6a61604e364217d12c56855a1b7e61f77e9e10a5/plugins/generic/externalFeed/ExternalFeedPlugin.inc.php#L107-L125

and

https://github.com/ojsde/shariff/blob/de375f098e25fe1cb89fbebae4f5bd3cbea2aa1e/ShariffPlugin.inc.php#L50-L51
for
https://github.com/ojsde/shariff/blob/de375f098e25fe1cb89fbebae4f5bd3cbea2aa1e/ShariffPlugin.inc.php#L78-L97

but now plugins need to accomplish this otherwise:
https://github.com/pkp/customBlockManager/blob/acd62abe6f3b4e6e2494476c0988bc9b1d121d97/CustomBlockManagerPlugin.inc.php#L60-L68

**To Reproduce**
1. Install a clean copy of OJS 3.1.x
2. Enable the Usage Statistics plugin
3. Install and configure a plugin which depends on this "category jumping" functionality for "blocks"
4. Breakpoint the callback watching for the category "blocks".

**What application are you using?**
 OJS or OMP version 3.1.x

**Additional information**
This is caused because we can't guarantee that the registration of "generic" plugins (to listen to the hooks) is complete before other plugin categories are loaded.

For example, the Usage Statistics plugin registers the "themes" plugins:
```
classes/plugins/PluginRegistry.inc.php.PluginRegistry::loadCategory:134	
classes/template/PKPTemplateManager.inc.php.PKPTemplateManager::getManager:911	
classes/plugins/Plugin.inc.php.UsageStatsPlugin->_registerTemplateResource:347	
plugins/generic/usageStats/PKPUsageStatsPlugin.inc.php.UsageStatsPlugin->register:100	
classes/plugins/PluginRegistry.inc.php.PluginRegistry::register:69	
classes/plugins/PluginRegistry.inc.php.PluginRegistry::loadCategory:140	
classes/core/Dispatcher.inc.php.Dispatcher->dispatch:132	
classes/core/PKPApplication.inc.php.Application->execute:247	
index.php.{main}:68
```
and calls registration of the "blocks" plugins:
```
classes/plugins/PluginRegistry.inc.php.PluginRegistry::loadCategory:134	
classes/template/PKPTemplateManager.inc.php.TemplateManager->initialize:393	
classes/template/PKPTemplateManager.inc.php.PKPTemplateManager::getManager:913	
classes/plugins/Plugin.inc.php.UsageStatsPlugin->_registerTemplateResource:347	
plugins/generic/usageStats/PKPUsageStatsPlugin.inc.php.UsageStatsPlugin->register:100	
classes/plugins/PluginRegistry.inc.php.PluginRegistry::register:69	
classes/plugins/PluginRegistry.inc.php.PluginRegistry::loadCategory:140	
classes/core/Dispatcher.inc.php.Dispatcher->dispatch:132	
classes/core/PKPApplication.inc.php.Application->execute:247	
index.php.{main}:68	
```
all prior to completing registration of the "generic" plugins.

**Comment by ctgraham** [comment]
See also:
https://github.com/pkp/customBlockManager/issues/43

and:
https://github.com/pkp/pkp-lib/issues/3336#issuecomment-429988715

and:
https://github.com/pkp/pkp-lib/issues/3336#issuecomment-430012004

Can the effort to introduce Hook Sequencing in https://github.com/pkp/pkp-lib/commit/158cefdc04206ddab3966c71dcd1afac5bcfd44d help here?  The load of the `PKPTemplateManager` doesn't directly relate to a `HookRegistry::register()` call.  Perhaps if UsageStats were sequenced at the very end of the "generic" plugin registration?

**Comment by asmecher** [comment]
@ctgraham, we used to rely on plugins being loaded in a certain sequence, but as the plugin ecosystem has gotten richer it's more common for unusual interactions to disrupt that. Generally I'd like to rely on the new approach, which makes fewer assumptions about the order of loading and relies instead on hook sequencing tools where that's necessary. Is there a particular plugin that's currently broken that I could consider?

**Comment by ctgraham** [comment]
The plugin with my current attention is [Shariff](https://github.com/ojsde/shariff).  With this confirmation of the changing paradigm, I'll convert my [patch](https://github.com/ulsdevteam/shariff/commit/fc027f14afeebd079d23e26872fe5f326d7ed039) into a pull request.

In the meantime, might we resequence the UsageStats plugin to load late enough to generally allow other plugins still using this legacy method to continue to work?  Or should we just use this as an "breaking" opportunity to discover these plugins?

**Comment by asmecher** [comment]
I'd rather that plugins using the risky approach break outright, rather than having it work in some cases and not in others. Load order can sometimes be affected by aspects as subtle as filesystem ordering of plugins in their directories, so that would be a nightmare to debug!

**Comment by ctgraham** [comment]
Do we want to just edit the comment here to indicate that the purpose of this hook is not for category jumping as was previously used, or do we want to deprecate the hook?

**Comment by asmecher** [comment]
I'd suggest removing that comment -- we don't necessarily recommend depending on the ordering of categories being consistent, but the hook could still be useful for other things.
