### ISSUE TITLE
[OJS] CrossRef plugin should allow for batch exemptions and batch clears

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#481]
On an articles "Edit Metadata" page, there's an option to skip DOI assignment for a specific article, as well as an option to "Clear DOIs". These should be available in the same subset of options as "Marked Registered" on the CrossRef Plugin list. This way, users can make exempt entire older back-issues of journals en masse and safely. This is what I assumed "mark as registered" did before I used it, and it definitely didn't.

**Comment by AhemNason** [comment]
Related to @jmacgreg post https://github.com/pkp/pkp-lib/issues/501

**Comment by asmecher** [comment]
Likewise, @AhemNason and @jmacgreg -- suggestions for OJS 2.4.7 release?

**Comment by mfelczak** [comment]
@AhemNason, is this still an issue in OJS 3.1?

**Comment by AhemNason** [comment]
closing
