### ISSUE TITLE
PKPTemplateManager::smartyIterate() - support for keys is broken

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4814]
Tested with OJS 3.1.2-1.

When using iterate function inside a template, e.g., iterating through journals:
```
{iterate from=journals item=journal key=journalKey}
  {$journalKey}
{iterate}
```
`$journalKey` variable would be null.
I've tracked down the problem to this assignment: https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L1172

**Comment by asmecher** [comment]
The JournalDAO doesn't return an iterator that currently supports keys. That's easy to add -- but what key are you expecting? The numeric `journal_id`, or the `path`, or something else like a synthetic counter?

**Comment by Vitaliy-1** [comment]
I've expected just default consecutive numerical keys.

**Comment by asmecher** [comment]
I would argue that, if anything, the journal ID should be exposed. To add support for that would require adding a 4th parameter to the constructor of `DAOResultFactory` in e.g. `ContextDAO.inc.php`, specifying `array('journal_id')`.

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.
