### ISSUE TITLE
Cannot use 'String' as class name (OCS)

### ISSUE THREAD

**Issue by msiraj83** [pkp/pkp-lib#4816]
I am trying to install the OCS system but i got the following error. 
![ocs_installation_error](https://user-images.githubusercontent.com/8863047/58862396-cce40980-86da-11e9-8200-ccea5707ae83.png)

I download the latest verstion (Download Open Conference Systems 2.3.6 (.tar.gz) (5908 KB)) from the (https://pkp.sfu.ca/ocs/ocs_download/)

Can somebody help me

**Comment by asmecher** [comment]
@msiraj83, the current .tar.gz package release of OCS isn't compatible with your version of PHP. The issue has been fixed in github, but be warned that we're not currently maintaining OCS at the moment, so your mileage may vary.
