### ISSUE TITLE
Contributor form shows wrong validation error for "Given Name" with multiple languages enabled

### ISSUE THREAD

**Issue by nils-stefan-weiher** [pkp/pkp-lib#4818]
**Describe the bug**
Author metadata form shows that all enable languages/locales of a journal are required for the "Given Name" field, although the form can be saved without entering any

**To Reproduce**
1. Go to any contributor metadata form
2. Click on the "Given Name" text input 
3. Focus a field for a secondary language by clicking or Tab-key
4. Leave the field emtpy, by clicking or Tab-key
4. The field is visually marked as invalid and the message "This field is required." is shown.

**What application are you using?**
 OJS or OMP version 3.1.2

**Additional information**

![Edit Contributor form with wrong visual indication](https://user-images.githubusercontent.com/2169369/58946373-0160cf80-8786-11e9-8e59-69fd93e603f5.png)

@NateWr Here have this finely prepared issue!

**Comment by NateWr** [comment]
Thanks @isgrim! In this case, the preferred functionality is that alternate languages are not required, so the user only has to enter one language.

**Comment by marcbria** [comment]
Related with:
https://forum.pkp.sfu.ca/t/changing-default-language-impacts-on-users-given-family-names/67739
https://forum.pkp.sfu.ca/t/configure-author-name-conventions/53738

**Comment by bozana** [comment]
This issue is not any more relevant for the branch 3_3_0 and main... The contributor given name is now only required in the submission locale.
Thus, I will close this issue...
