### ISSUE TITLE
[OJS] Make ManagementHandler more easily extensible and fix access and archiving settings bug in OJS

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4819]
ManagementHandler in pkp-lib needs to more easily extensible when adding app specific settings tabs.

Also the current SettingsHandler extension for access and archiving settings tab has a bug and the forms do not appear.

pr to follow soon

**Comment by ajnyga** [comment]
@asmecher I prepared this together with Nate.

It might break some setting forms in OMP, but I can fix those right after the merge if it does.

OJS: https://github.com/pkp/ojs/pull/2418
lib: https://github.com/pkp/pkp-lib/pull/4821/files

**Comment by asmecher** [comment]
Thanks, @ajnyga -- I presume if Nate has worked on this then it has his blessing? He knows the new structures better than I do. I've taken a skim and just had a few comments on the most superficial of syntax inconsistencies, but otherwise had no problems with it.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [discussions](https://github.com/pkp/pkp-lib/discussions) section.
