### ISSUE TITLE
[OJS] Articles from journals not intented for public display appear in search results

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#482]
Continued from this entry: https://github.com/pkp/pkp-lib/issues/340#issuecomment-93974000

Issue #340 resolved this for author and title browse lists; this one will resolve it for search results.

**Comment by asmecher** [comment]
@martinpub, can you verify whether the patch resolves the issue? It should prevent disabled journals' contents from appearing in the site-wide search.

The other issue you mentioned is that archived content may appear in the search results. Can you provide more information on that?

**Comment by martinpub** [comment]
Great, results from disabled journals no longer show up in site-wide search results.

However, the article I've been using to test this still show up in the list of articles by an author with that name (index/search/authors/view?firstName=Martin&middleName=&lastName=Persson&affiliation=&country=). It seems this happens only when there are multiple articles from the same author name and some of them belong to a disabled journal. Authors from disabled journals do not trigger an entry in index/search/authors alone.

We will get back to you with details on the other issue.

**Comment by asmecher** [comment]
@martinpub, thanks for your ongoing efforts here -- we'll get it yet. This patch should exclude articles from disabled journals from the author's sitewide listing: https://github.com/asmecher/ojs/commit/de3223bdb1e8da65cccd399ce56b65328038ac34.diff

**Comment by martinpub** [comment]
Thanks for this patch, it did the trick.

Regarding the other issue (sorry for using the same issue thread, please make another one if you find this not so related), I seem to have found an article record that's not published, but still somehow show up in the search results. Looking in this journals archive ([journal-shortname]/editor/submissions/submissionsArchives) the article is highlighted as the other published articles are. However, checking its status, it says "Archived". In the database, the status code is 0.

**Comment by asmecher** [comment]
@martinpub, would you be able to send me a DB dump and an article ID? Feel free to change e.g. the "password" and "email" columns in the users table and anything else you want to obscure.

**Comment by martinpub** [comment]
Sure, I've emailed you a link to the dump and the ID.

**Comment by asmecher** [comment]
@martinpub, did you edit the database dump after creating it? It appears to contain duplicate indexes:

    ERROR 1062 (23000) at line 1988698: Duplicate entry 'wilsontd' for key 'users_email'

**Comment by martinpub** [comment]
I've sent you a link to an updated dump.

**Comment by asmecher** [comment]
Thanks, @martinpub -- I've added an additional commit. See https://github.com/pkp/ojs/commit/dbd23a5e6443159a148e97962aea1d2949ebb9aa for a patch.

**Comment by martinpub** [comment]
Great!
