### ISSUE TITLE
Variable type warning for UsageStats optionalColumns

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4820]
**Describe the bug**
Quoting https://forum.pkp.sfu.ca/t/bug-in-usagestats-plugin-2-4-8-3/53923
I noticed that running manually the usageStats I was getting lots of repeated errors:
```
ojs2 has produced an error
  Message: WARNING: in_array() expects parameter 2 to be array, null given
  In file: /usr/home/seer/public_html/plugins/generic/usageStats/UsageStatsLoader.inc.php
  At line: 190
  Stacktrace:
  Server info:
   OS: FreeBSD
   PHP Version: 5.6.38
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.7.26-log
ojs2 has produced an error
  Message: WARNING: in_array() expects parameter 2 to be array, null given
  In file: /usr/home/seer/public_html/plugins/generic/usageStats/UsageStatsLoader.inc.php
  At line: 191
  Stacktrace:
  Server info:
   OS: FreeBSD
   PHP Version: 5.6.38
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 5.7.26-log
```
It seems to be because I haven’t set to generate statistics for City and Region, and thus the array that should contain what options are set is null instead of empty.

**To Reproduce**
1. Disable statistics generation for City and Region in UsageStats plugin
2. Run the usage statistics file loader
3. Review PHP warnings

**What application are you using?**
 OJS version 2.4.x

**Additional information**
n/a

**Comment by asmecher** [comment]
Both PRs merged, thanks, @ctgraham -- is this ready to close?
