### ISSUE TITLE
installation successful but blank page on visiting the site in brower

### ISSUE THREAD

**Issue by msiraj83** [pkp/pkp-lib#4824]
**Describe the bug**
I have installed OJS 3.1.2 successfully from command prompt just by typing (php tools/install.php) and the installation have successful. 
`[data: dbscripts/xml/indexes.xml]
[code: Installer Installer::createData]
[code: Installer Installer::createConfig]
[code: Installer Installer::addPluginVersions]
[code: Installer Installer::installDefaultNavigationMenus]
[post-install]
PHP Notice:  Only variables should be passed by reference in /var/www/html/ojs/lib/pkp/lib/adodb/adodb-xmlschema.inc.php on line 267
PHP Notice:  Only variables should be passed by reference in /var/www/html/ojs/lib/pkp/lib/adodb/adodb-xmlschema.inc.php on line 267
PHP Notice:  Only variables should be passed by reference in /var/www/html/ojs/lib/pkp/lib/adodb/adodb-xmlschema.inc.php on line 267
PHP Notice:  Only variables should be passed by reference in /var/www/html/ojs/lib/pkp/lib/adodb/adodb-xmlschema.inc.php on line 267
PHP Notice:  Only variables should be passed by reference in /var/www/html/ojs/lib/pkp/lib/adodb/adodb-xmlschema.inc.php on line 267
PHP Notice:  Only variables should be passed by reference in /var/www/html/ojs/lib/pkp/lib/adodb/adodb-xmlschema.inc.php on line 267
PHP Notice:  Only variables should be assigned by reference in /var/www/html/ojs/lib/pkp/classes/cliTool/InstallTool.inc.php on line 75
Successfully installed version 3.1.2.0
`
Now when i visit the site than i get blank page. Can anybody help me please..

I have ubuntu 16.04 OS
php `PHP 7.0.33-0ubuntu0.16.04.5 (cli) ( NTS )` 
mysql `mysql  Ver 8.0.16 for Linux on x86_64 (MySQL Community Server - GPL)`

I set the permission of for all folder and files 

chmod -R 777 ojs

Regards,
Siraj

**Comment by asmecher** [comment]
@msiraj83, I see you've also posted this at https://forum.pkp.sfu.ca/t/ojs-ohs-installation-shows-blank-page/676/15 -- that's the best place to get help with issues like this.
