### ISSUE TITLE
registrationform::execute lost $user argument

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4829]
**Describe the bug**
Another use-case for https://github.com/pkp/pkp-lib/issues/4612.

Hook `registrationform::execute` is substantially crippled.  Plugins cannot reasonably be re-written to work around this because the `$user` object which was formerly passed is not persisted at the time of call.

**To Reproduce**
1. Implement hook `registrationform::execute`.
2. Before 3.1.2:
    https://github.com/pkp/pkp-lib/blob/1657d92ae5b3dbbd4c549e2eca0aeb40cff3a6a9/classes/user/form/RegistrationForm.inc.php#L249-L255
    https://github.com/ulsdevteam/pkp-akismet/blob/6dfd2e873bc830f071a2c894170fb46d7fd66915/AkismetPlugin.inc.php#L241-L243
3. After 3.1.2:
    https://github.com/pkp/pkp-lib/blob/1d13a0687bb31fee71b22b49d5cbeade75725030/classes/user/form/RegistrationForm.inc.php#L258-L264
    https://github.com/ulsdevteam/pkp-akismet/blob/6dfd2e873bc830f071a2c894170fb46d7fd66915/AkismetPlugin.inc.php#L241-L243

**What application are you using?**
 OJS or OMP version 3.1.2

**Additional information**
Note that not all arguments were removed in the cleanup, e.g.:
https://github.com/pkp/pkp-lib/blob/1d13a0687bb31fee71b22b49d5cbeade75725030/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php#L769

Note that some don't provide a route back to `Form::execute`:
https://github.com/pkp/pkp-lib/blob/1d13a0687bb31fee71b22b49d5cbeade75725030/controllers/grid/files/copyedit/form/ManageCopyeditFilesForm.inc.php#L34
https://github.com/pkp/pkp-lib/blob/1d13a0687bb31fee71b22b49d5cbeade75725030/controllers/grid/files/form/ManageSubmissionFilesForm.inc.php#L72-L98

https://github.com/pkp/pkp-lib/blob/1d13a0687bb31fee71b22b49d5cbeade75725030/controllers/grid/users/reviewer/form/EmailReviewerForm.inc.php#L72-L91

https://github.com/pkp/pkp-lib/blob/044e7e2059a2c5f4b88d53c1bf8c7d0dd6079b98/controllers/modals/submissionMetadata/form/PKPSubmissionMetadataViewForm.inc.php#L169
is a `Form`, but:
https://github.com/pkp/pkp-lib/blob/master/classes/submission/PKPSubmissionMetadataFormImplementation.inc.php
is not.

**Comment by ctgraham** [comment]
@asmecher , @NateWr , I'm tempted to re-sig `Form::execute()` as `Form::execute(...$args)` to re-allow this usage.  I can't see a good alternative to providing the caller insight into the unpersisted data.  In my plugin, for example, I need to modify the User object to add new fields/attributes at registration.

See also:
https://github.com/pkp/pkp-lib/blob/1d13a0687bb31fee71b22b49d5cbeade75725030/classes/submission/form/PKPSubmissionSubmitStep3Form.inc.php#L97-L100
and
https://github.com/pkp/pkp-lib/blob/1d13a0687bb31fee71b22b49d5cbeade75725030/classes/submission/form/PKPSubmissionSubmitStep4Form.inc.php#L44-L47
for similar calls to the hook prior to persistence (in a Submission context).

**Comment by ctgraham** [comment]
Hrm.  This is clever, but is this the solution we really want?
https://github.com/pkp/orcidProfile/pull/66/files

**Comment by asmecher** [comment]
@ctgraham, I've already resolved that in the `master` branch: https://github.com/pkp/pkp-lib/issues/4601#issuecomment-474985786

The work-around will only be needed for the stable branch, and was written for backwards-compatibility with existing releases that had a need for the work-around.
