### ISSUE TITLE
[OJS] Issue galley file upload doesn't detect HTML mimetype

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#483]
Same problem as described here:

https://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=14090

I've confirmed this on my local install, and I believe on one of our hosted installs as well. Basically, when I upload an HTML file as an issue galley, it's identified as "Untitled"; then it's downloaded instead of viewed inline from the TOC. I'm using a very simple HTML file, nothing that doesn't work as an article HTML galley.

**Comment by asmecher** [comment]
@jmacgreg, is the "mime_database_path" setting commented out in config.inc.php?

**Comment by jmacgreg** [comment]
Hey Alec, just tried with the line commented out (on my local install - the hosted install is on 2.4.5, which IIRC doesn't have that parameter) and got the same result.

**Comment by asmecher** [comment]
@jmacgreg, mind emailing me your HTML?

**Comment by jmacgreg** [comment]
I cannot replicate, nor remember, this issue. Closing.
