### ISSUE TITLE
[OJS] Reviewing interests "tagit" results not styled properly on registration 

### ISSUE THREAD

**Issue by sssoz** [pkp/pkp-lib#4830]
From issue: https://github.com/pkp/healthSciences/issues/152

This was originally reported as an issue related to a theme, but it is appearing in the default theme as well. Search result contents appear in a div outside of the page’s content (below the footer). It should either not appear at all, or appear directly below the corresponding tagit field. 

![5e1b369522ddba4c6df4028bf2a65565](https://user-images.githubusercontent.com/6668406/59520118-34f7d400-8ec1-11e9-861f-05c11fa593d4.gif)

**Comment by thinkbulecount2** [comment]
[Pull Request](https://github.com/pkp/ojs/pull/2444), cc: @NateWr

**Comment by NateWr** [comment]
Merged.
