### ISSUE TITLE
[OJS] Reviewer Rating Stats Missing

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#4832]
Reviewer Rating is currently not included in the Review Report [Tools > Report Generator]

@NateWr

**Comment by NateWr** [comment]
Requested here: https://forum.pkp.sfu.ca/t/ojs-3-1-1-1-reviewer-rating/54093/2

**Comment by NateWr** [comment]
Requested here: https://forum.pkp.sfu.ca/t/ojs-3-1-1-1-reviewer-rating/54093/2

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
