### ISSUE TITLE
Re-add "blind copy reviewers on editor decision" feature

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4834]
**Describe the problem you would like to solve**
Editors would like a way to copy reviewers on the editor decision email sent to the author including the review details.

**Describe the solution you'd like**
OJS 2.x used to have a checkbox for this purpose (and still has some related locale keys). Reconstitute this feature the way it used to work in OJS 2.x.

**Who is asking for this feature?**
See e.g.: https://github.com/pkp/pkp-lib/issues/743#issuecomment-503595345

**Comment by dgardnerHK** [comment]
From an editor. We've just moved up to OJS v3.1 and I was so surprised to find that copying reviewers into the editorial decision is no longer a simple button click. I have had so much positive feedback over the years from reviewers about being able to see the editorial decision and the other reviewer's feedback that I must keep this going but it is going to be extra work and might get forgotten sometimes. I also worry that if I don't do it reviewers might begin to wonder whether their efforts are worthwhile and getting sufficient reviewers is my biggest headache.
Hope you can bring it back soon.

**Comment by NateWr** [comment]
The following mockup suggests a a simple checkbox to be added to the editor decisions modal. When implementing this checkbox, the following things should be checked:

- Only reviewers with completed reviews should be listed here. It is common for there to be many reviewers assigned but only a few (sometimes less than half) actually completing a review.
- The option to BCC reviewers should be hidden when the option "do not send email notification" is selected.

![bcc-reviewers](https://user-images.githubusercontent.com/2306629/95735708-16ece000-0c7d-11eb-93a1-7ba214fffa3a.png)

**Comment by ajnyga** [comment]
+1 for this, some journals have asked for this. Apparently it is a common practice in some journals that the reviewers get to see the reports from other reviewers.

**Comment by alexxxmendonca** [comment]
+1

and maybe have a non-blind copy as well, thinking about open review.

**Comment by asmecher** [comment]
(Comments here: https://github.com/pkp/pkp-lib/pull/6728#issuecomment-774704610)

**Comment by jonasraoni** [comment]
@asmecher I've created a PR for stable-3_3_0. If everything is ok, I can update the one for /main...

[PKP-LIB](https://github.com/pkp/pkp-lib/pull/6855)

But the [PR to run the tests](https://github.com/pkp/ojs/pull/3073/checks?check_run_id=2087215240) had a strange result :)

**Comment by asmecher** [comment]
The code looks good, @jonasraoni! Please go ahead and forward-port to `main`.

**Comment by asmecher** [comment]
> But the PR to run the tests had a strange result :)

I thought this was just a race condition -- in fact restarting the tests did fix one of the broken PHP7.x tests -- but the 8.x tests appear to be failing on https://github.com/pkp/pkp-lib/pull/6855/files#diff-292418b042047b0b51e9084eee6931fbab4e76fb45f171010fdc8ce309d594fdR12:
```
[11-Mar-2021 18:42:49 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /home/travis/build/pkp/ojs/cache/t_compile/690e812ff452b7e03c7305ace893860ee4c93d06^32ff1066ce03ba06db492913fd0e6f222fcf1f6d_0.app.controllersmodalseditorDe.php:24
Stack trace:
#0 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_604a649c4c4ff4_63093318(Object(Smarty_Internal_Template))
#1 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#4 /home/travis/build/pkp/ojs/cache/t_compile/690e812ff452b7e03c7305ace893860ee4c93d06^f98a67abb74c9aa755e1eb9577e5d7f9f966bd33_0.app.controllersmodalseditorDe.php(125): Smarty_Internal_Template->_subTemplateRender('app:controllers...', NULL, '690e812ff452b7e...', 0, 3600, Array, 0, false)
#5 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_604a649c494609_64128568(Object(Smarty_Internal_Template))
#6 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#7 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#8 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#9 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, '690e812ff452b7e...', NULL, 0)
#10 /home/travis/build/pkp/ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php(1072): Smarty_Internal_TemplateBase->fetch('controllers/mod...', NULL, '690e812ff452b7e...', NULL)
#11 /home/travis/build/pkp/ojs/lib/pkp/classes/form/Form.inc.php(197): PKPTemplateManager->fetch('controllers/mod...')
#12 /home/travis/build/pkp/ojs/lib/pkp/classes/controllers/modals/editorDecision/form/EditorDecisionForm.inc.php(122): Form->fetch(Object(Request), NULL, false)
#13 /home/travis/build/pkp/ojs/lib/pkp/controllers/modals/editorDecision/form/EditorDecisionWithEmailForm.inc.php(169): EditorDecisionForm->fetch(Object(Request), NULL, false)
#14 /home/travis/build/pkp/ojs/lib/pkp/classes/controllers/modals/editorDecision/PKPEditorDecisionHandler.inc.php(444): EditorDecisionWithEmailForm->fetch(Object(Request))
#15 /home/travis/build/pkp/ojs/lib/pkp/classes/controllers/modals/editorDecision/PKPEditorDecisionHandler.inc.php(154): PKPEditorDecisionHandler->_initiateEditorDecision(Array, Object(Request), 'PromoteForm')
#16 /home/travis/build/pkp/ojs/lib/pkp/classes/core/PKPRouter.inc.php(395): PKPEditorDecisionHandler->promote(Array, Object(Request))
#17 /home/travis/build/pkp/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#18 /home/travis/build/pkp/ojs/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route(Object(Request))
#19 /home/travis/build/pkp/ojs/lib/pkp/classes/core/PKPApplication.inc.php(364): Dispatcher->dispatch(Object(Request))
#20 /home/travis/build/pkp/ojs/index.php(68): PKPApplication->execute()
#21 {main}
  thrown in /home/travis/build/pkp/ojs/cache/t_compile/690e812ff452b7e03c7305ace893860ee4c93d06^32ff1066ce03ba06db492913fd0e6f222fcf1f6d_0.app.controllersmodalseditorDe.php on line 24
```

**Comment by jonasraoni** [comment]
@asmecher I even didn't watch this build's output, because the other PRs I submitted had the same race condition issue... Thanks for noticing, and also for talking about "restarting the tests", now I found the small restart link =]
```
count(null)
PHP < 7.2 = Great
PHP 7.2 = Warning...
PHP 8 = Die!
```

There's nothing in the documentation about the fatal error yet, but better to search across the code base to find more cases before they pop.

**Comment by asmecher** [comment]
Merged PRs for both `main` and `stable-3_3_0`, thanks!

> Also, did someone investigate these race conditions?

Not recently -- we have some outstanding planning and refactoring to do on the future of our test system (i.e. potentially migrating from Travis to Github Actions) and that'll need to happen before we dig into debugging the quirks.

**Comment by jonasraoni** [comment]
@asmecher what about the fatal error in PHP 8? Are you going to proceed with a global check? Just asking because I didn't commit the fix.

About the Github Actions, I checked fast and it looks promising, looks like it supports Docker too, so we could have some slim pre-built images with all the tooling installed to speedup the process.

**Comment by asmecher** [comment]
@jonasraoni, sorry, I had assumed there was a fix in place now. Can you look into a specific fix for this? (i.e. making sure that `$reviewers` is set in all cases where the new template is called?) There is some discussion of a global fix here, but it's too invasive for `stable-3_3_0`: https://github.com/pkp/pkp-lib/issues/6783

**Comment by asmecher** [comment]
Never mind, I got it: https://github.com/pkp/pkp-lib/commit/295fbe35a1332921dbf394a33f4e99ecbd74105e

**Comment by jonasraoni** [comment]
I've skimmed the code and for me it should be working, so I was going to investigate it better...
Anyway thanks, I'm a bit disabled after falling over my hand 😂
