### ISSUE TITLE
Custom NMI content field should be compatible with Static Pages Field 

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#4836]
The upgrade process is trying to copy any existing Static Page to a Custom NMI with the same path and content. 
The content field for Static Pages plugin is of type "longtext", while the same field for the NMIs is "text". That could result loss of data when coping a static page to a NMI.

**Comment by defstat** [comment]
@asmecher 

**PR**
[PKP-LIB]: #5812

**Comment by asmecher** [comment]
Merged and cherry-picked back to `stable-3_2_0`, thanks!
