### ISSUE TITLE
[OJS 3.1.2-1] Statistics/Articles wouldn’t work properly when base url is set

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#4837]
Hi! When the `base url` of the journal is set in the config, the journal manager will only get the default graph. Setting any date ranges or filters would result in this error: “An unexpected error has occurred. Please reload the page and try again.”.
See here: https://forum.pkp.sfu.ca/t/ojs-3-1-2-1-statistics-articles-wouldnt-work-properly-when-base-url-is-set/54112

**Comment by asmecher** [comment]
@Ph-We, I think this is probably related to your rewriting configuration; I suspect the API URL is not getting routed to OJS, which is why the server is responding with a 404.

**Comment by dunnleaddress** [comment]
@asmecher hello!

Do you by chance have an example of rewrite-rules to help me write mine?

Best Regards,

Dung.

**Comment by dunnleaddress** [comment]
Solution is posted here https://forum.pkp.sfu.ca/t/ojs-3-1-2-1-journal-statistic/54224/19
