### ISSUE TITLE
Allow blind discussions in review stage

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4838]
Currently all participants who are added to a new discussion topic can see the identity of other participants in the discussion. An editor requested the option of having blind discussions during the review stage, where the identities of participants are hidden.  

The editor said, "You can include multiple users and have a record of discussions without disclosing the identity of the discussants (other than being identified as Reviewer A/B/C, etc.). A number of reviewing systems I am aware of (for example the one that IEEE uses for VisWeek reviewing) do implement blind discussions for juried reviews. Their system has reviewers collectively discuss the reviews to come to a final decision on any submission. Disclosing the identity of reviewers can lead to reviewers sometimes not honestly expressing their views on a submission, depending on who else is participating in the discussion.

I have had a few submissions lately where it would be helpful to have a blind discussion because there were widely divergent views on the paper and it's an area in which I personally don't have deep expertise, so I am really reliant on the reviewers to understand the contributions and shortcomings of the manuscript."

**Comment by asmecher** [comment]
@amandastevens, what version of OJS are you using? I think blinding has been implemented for discussions since https://github.com/pkp/pkp-lib/issues/2976 (which is at least partially in 3.1.1, and probably more significantly in 3.1.2).

**Comment by amandastevens** [comment]
Thanks, @asmecher. I missed this since it was part of the mega-issue.  The journal who requested the feature is using 3.1.2 so they must not be aware that the feature is available. How does it work exactly? I can add something to documentation after I understand it.

**Comment by asmecher** [comment]
I believe it should work automatically -- depending on the reviewer's assignment (i.e. blind, double-blind, etc).

**Comment by amandastevens** [comment]
Thanks, I will tell the client and close this issue.

**Comment by amandastevens** [comment]
The client created a discussion topic for all 3 reviewers informing them of the editorial decision and the identities of the other reviewers are visible to each reviewer when they open the discussion topic.  I logged in as the reviewers and could clearly see the names of the other reviewers.  They review type is double blind.  This is not intended, is it?  Issue 2976 has "In blind reviews, reviewers do not see other reviewers" as a checked off item.

**Comment by amandastevens** [comment]
@asmecher, I tested this on the testdrive install also and reviewers can see the names of other reviewers in discussion topics, in both blind and double blind reviews.  I'm going to open a new issue about it.
