### ISSUE TITLE
[OJS] Search form and keywords

### ISSUE THREAD

**Issue by juanmaiquez** [pkp/pkp-lib#4846]
Hello all!

Our editors have asked us to improve the search form as OJS 3 is much simpler than OJS 2.
Specifically, one of the requests is to recover the field to search by keywords, present in the OJS 2 search form.

Reviewing the code in depth I found some joys and disappointments.

At first, I saw that the search process takes into account a form field whose name is `subject`, which corresponds to the keywords search field defined in OJS 2. I added it to the form and was glad to see that even the translation `search.subject` corresponded to what I was looking for. In addition, the backend returned the field when it was set to pre-fill the form after a search. Great!

But there are no search results :(

I saw that the search process was carried out using the `submission_search_*` tables. The search process uses the constant `SUBMISSION_SEARCH_SUBJECT` to identify the objects where the keywords should be indexed. However, there do not seem to be indexed keywords in the database.

The following query confirmed the problem:

```
SELECT 
    object_id,
    type,
    case `type`
	when 1 then 'SUBMISSION_SEARCH_AUTHOR'
        when 2 then 'SUBMISSION_SEARCH_TITLE'
        when 4 then 'SUBMISSION_SEARCH_ABSTRACT'
        when 8 then 'SUBMISSION_SEARCH_DISCIPLINE'
        when 16 then 'SUBMISSION_SEARCH_SUBJECT'
        when 32 then 'SUBMISSION_SEARCH_TYPE'
        when 64 then 'SUBMISSION_SEARCH_COVERAGE'
        when 128 then 'SUBMISSION_SEARCH_GALLEY_FILE'
        when 256 then 'SUBMISSION_SEARCH_SUPPLEMENTARY_FILE'
        when 512 then 'SUBMISSION_SEARCH_INDEX_TERMS'
	end type_const,
    submission_id,
    ( SELECT GROUP_CONCAT(kl.keyword_text SEPARATOR ',') words FROM submission_search_keyword_list kl
	WHERE kl.keyword_id IN (
		SELECT keyword_id FROM submission_search_object_keywords ok
		WHERE ok.object_id = so.object_id ORDER BY ok.pos
	) ) eso
FROM submission_search_objects so
WHERE submission_id = ?;
```

Where "?" is replaced by a submission with assigned keywords. The query result always returns `NULL` in `SUBMISSION_SEARCH_SUBJECT` object types.

Digging a little deeper, I decided to review the indexing process, and on line 74 of the file `classes/search/ArticleSearchIndex.inc.php` I found this:

```
self::_updateTextIndex($articleId, SUBMISSION_SEARCH_SUBJECT, (array) $article->getSubject(null));
```

This does not seem to have any effect, as neither the `ArticleDAO` nor `SubmissionDAO` `_fromRow` function incorporates anything into the article subject when it is loading.

I think the keywords could be retrieved (and indexed later) using the `SubmissionKeywordDAO` class. But I don't know if this goes against your planning.

My question is: is this a bug or is it a deliberate decision? Are you changing the search process?

Thank you very much for your work!

**Comment by asmecher** [comment]
@juanmaiquez, this was fixed in https://github.com/pkp/ojs/commit/a59fea40fc85a7747e126fb0dd34d3f4421265e0 and https://github.com/pkp/ojs/commit/427f068e43d90308f0fce4865ec363813528ccd0, and released in OJS 3.1.2-2 and later!
