### ISSUE TITLE
Revise OJS’ subscription model to permit "Subscribe to Open" or S2O functionality

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#4848]
Placeholder issue, but in rough form: 

- add a subscription and payment toggle to the current subscription tool, so that journals can choose whether content is protected, and whether payments are required (or accepted) to become a subscriber. 
- include some language massaging to reflect the S2O model. 
- permit institutional subscribers to self-register (registrations would need to be reviewed and activated). This functionality is already included but would need review. 
- permit journal editors to add subscribers. This second option would allow journals to create reports described in 1) above for institutions that are not yet funders. (Journal editors or marketing managers would be able to retrieve IP ranges from public institution listings, eg. OCUL’s.) This functionality is already included but would need review. 
- Note: while this sounds like it might not be a lot of work, my sense is that the subscriptions module is still in pretty rough shape and would probably need a serious overhaul to be able to support this. Alec noted in particular that subscription management would have to be decoupled from payments.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
