### ISSUE TITLE
User register but did not get email...

### ISSUE THREAD

**Issue by msiraj83** [pkp/pkp-lib#4850]
I have installed ojs-3.1.2-1 successfully. The problem i faced in registering to the site. When a user only register and not perform any task like Make a New Submission than the user not get any email in response and the default role is reviewer. 

I would like the default role should be reader or visitor and and the user should get the email only for registration. 

Or 

How i can change the default role i.e. reviewer to reader and the user get the email as well ??

Can any body help me in this regards please.

**Comment by asmecher** [comment]
@msiraj83, can you post your question on our support forum at https://forum.pkp.sfu.ca? That's the best place to get general help.
