### ISSUE TITLE
CitationStyleLanguage: Please provide example for hook-in 

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#4851]
I dont understand https://github.com/pkp/citationStyleLanguage/blob/66fd62e6cad88fe29345c6563a38e5b8177721cd/CitationStyleLanguagePlugin.inc.php#L119

Please provide an example.

Can't just the $defaults array be extended with an additional CSL style and the style be placed in directory citation-styles?

**Comment by asmecher** [comment]
@NateWr, do you have an example handy for `useCsl` permitting an override of the regular CSL style list?

**Comment by NateWr** [comment]
Hi @mpbraendle,

You can do this, but then your custom .csl file will be deleted whenever the plugin is updated. It is better to keep your modifications separate from other application parts.

For example, here's a custom plugin class that would add the CSL style:

```php
<?php
import('lib.pkp.classes.plugins.GenericPlugin');
class CustomCSLPlugin extends GenericPlugin {

	public function register($category, $path, $mainContextId = NULL) {
    $success = parent::register($category, $path);
		if ($success && $this->getEnabled()) {
      HookRegistry::register('CitationStyleLanguage::citationStyleDefaults', [$this, 'addCustomCsl']);
    }
		return $success;
	}

  public function addCustomCsl($hookName, $args) {
    $defaults =& $args[0];
    $citationStyleLanguagePlugin = $args[1];

    $defaults[] = [
      'id' => 'my-custom',
      'title' => __('plugins.generic.customCSLPlugin.styleName'),
      'isEnabled' => true,
      'useCsl' => $this->getPluginPath() . '/my-custom.csl',
    ];
  }
}
```

Then you can place the `my-custom.csl` file directly in your own plugin's directory and it will be loaded from there. That way your work won't get blown away during updates and you can also keep a clean separation between your own code and the core application/plugin code.

You can learn more about setting up a custom plugin for your own work in the [Plugin Guide](https://docs.pkp.sfu.ca/dev/plugin-guide/en/).

I'll try to add a fully-working example in the future.
