### ISSUE TITLE
Citation Style Language Plugin: bibtex encoding error

### ISSUE THREAD

**Issue by annakuglerin** [pkp/pkp-lib#4853]
German umlaute are not encoded, e.g. ‘ä’ should be encoded as ‘{"a}’.
Thus, during import e.g. into endnote it generates errors.

**Comment by asmecher** [comment]
@annakuglerin, I think this is a limitation in the third-party Citeproc-php tool we use to format citations. I'd suggest filing this at https://github.com/seboettg/citeproc-php/issues/new instead.
