### ISSUE TITLE
[OJS] First letter displayed in search Author Index

### ISSUE THREAD

**Issue by hcoussy** [pkp/pkp-lib#4854]
Hi,
We are using OJS 3.1.2-1 at University of Bordeaux for several journals. 
We noticed that First letter displayed in search Author Index is initialized with the first letter of the givenName instead of the first letter of the familyName.
In file "templates/frontend/pages/searchAuthorIndex.tpl", the value of the variable firstLetter is initialized with the 1st letter of getLocalizedGivenName instead of getLocalizedFamilyName.
Best regards.

**Comment by asmecher** [comment]
Thanks for catching this, @hcoussy! I've fixed it for the next release.

**Comment by asmecher** [comment]
(Filed from: https://forum.pkp.sfu.ca/t/first-letter-displayed-in-search-author-index/54536)
