### ISSUE TITLE
Implement publishing in the new publication UI (OJS complete)

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4858]
In the publication tab, the act of publishing needs to be implemented. Most of this involves the action button at the right of the publication tab:

![Selection_076](https://user-images.githubusercontent.com/2306629/60532911-48df6a80-9cf6-11e9-9d70-b875af3ca833.png)

## Acceptance Criteria (OJS)
- [x] As an editor, I can schedule a publication to be published under the Publication tab in the submission's workflow.
- [x] After a publication is published, I can not make changes to the publication details.
- [x] After a publication is published, I can create a new version.
- [x] After a new version is created, I can make changes to that version and publish it.
- [x] When more than one version exist, I can view all versions in the workflow.
- [x] When I try to publish a publication that is not assigned to an issue, I am told that I must schedule it in an issue first.
- [x] When I try to publish a publication that is still in the submission stage, I am told that it must pass the review stage.
- [x] When I try to publish a submission that has been declined, I am told that I can not publish a declined submission.
- [ ] ~When I click "Preview" at the top of the submission workflow screen, it always shows me the details for the latest _published_ publication.~

## Acceptance Criteria (OMP)
- [x] As an editor, I can schedule a publication to be published under the Publication tab in the submission's workflow.
- [x] After a publication is published, I can not make changes to the publication details.
- [x] After a publication is published, I can create a new version.
- [x] After a new version is created, I can make changes to that version and publish it.
- [x] When more than one version exist, I can view all versions in the workflow.
- [ ] When I try to publish a submission that has been declined, I am told that I can not publish a declined submission.
- [ ] ~~When I click "Preview" at the top of the submission workflow screen, it always shows me the details for the latest _published_ publication.~~

**Comment by NateWr** [comment]
This has been implemented for OJS. A short video demonstrating the state of things can be seen here:

https://youtu.be/NDCnBiRSFmc

**Comment by asmecher** [comment]
That looks great, @NateWr! For curiosity's sake, can you drop a link to the spot where the constraints are added?

**Comment by NateWr** [comment]
That's `PKPPublicationService::validatePublish()` [pkp-lib](https://github.com/NateWr/pkp-lib/blob/i2072_versioning/classes/services/PKPPublicationService.inc.php#L270-L307) and `PublicationService::validatePublishPublication()` [ojs](https://github.com/NateWr/ojs/blob/i2072_versioning/classes/services/PublicationService.inc.php#L116-L137).

**Comment by librariam** [comment]
**Testing acceptance criteria for OJS:**
 
**[pass]** As an editor, I can schedule a publication to be published under the Publication tab in the submission's workflow.

 **[pass]** After a publication is published, I can not make changes to the publication details.

 **[pass]** After a publication is published, I can create a new version.
_Comment: Version numbering is unclear. I created the first new version of a newly published article and the version number was 135, with the original being 131. It would make sense for the version numbers to say 1 and 2 respectively in this case._

 **[pass]** After a new version is created, I can make changes to that version and publish it.

 **[pass]** When more than one version exist, I can view all versions in the workflow.
_Comment: UI - when toggling between previous versions in the workflow, it is hard to tell at a glance which version I’m in at any given moment. I see that the distinction is supposed to be in the version number, but that alone is not descriptive enough. I’m also finding the grey-blue toggle under All Versions rather confusing. The public article page has a publication timestamp for each version - maybe it could be added to the workflow display as well to help distinguish between versions?_

 **[pass]** When I try to publish a publication that is not assigned to an issue, I am told that I must schedule it in an issue first.

**Comment by NateWr** [comment]
Thanks @librariam!

> The public article page has a publication timestamp for each version - maybe it could be added to the workflow display as well to help distinguish between versions?

Yes, this is the plan! So far just in my head and not down in an issue somewhere. :)

**Comment by NateWr** [comment]
> It would make sense for the version numbers to say 1 and 2 respectively in this case.

Sorry, missed this comment. Yes, the plan is to go with dates as the main tool with numbers only when two of the same date exist. :+1:

**Comment by NateWr** [comment]
Sorry, i should pay more attention! I see there are additional acceptance criteria so re-opened this. Thanks, your comments are very clear, I'm just being an idiot. :+1:

**Comment by librariam** [comment]
Sorry @NateWr , I should have mentioned that @israelcefrin and I split the criteria for testing. All should be done now!

**Comment by NateWr** [comment]
Thanks!

> in fact the system warns me that I need to proceed into the Copyediting or Production stages before to be able to publish it

That's the behaviour I was expecting so I'm going to call this one passed. :joy: We can always make changes later based on UX testing.

> It shows always the current submission details, neither the latest or published.
I clicked preview for a declined submission and it has shown me the declined one. Is this expected to happen?

Sorry, I realize that this acceptance criteria actually makes no sense. The "Preview" button only appears before a submission is published, in which case there is only one Publication, so there's no possibility to show the wrong publication. I've gone ahead and crossed this one out as irrelevant.

**Comment by withanage** [comment]
@NateWr 
in the follwing  requirement  from the ticket header.

- [ ] After a publication is published, I can not make changes to the publication details.

In OMP, I tried Enter key on the Publications ->  Identifiers -> Public URL Identifier and, it redirected me to the API. May be we can disable the  enter fields there.

![public_uri](https://user-images.githubusercontent.com/1921992/71424745-7ac5fe00-2695-11ea-9979-cddc77de598e.gif)

**Comment by NateWr** [comment]
Good catch Dulip! I also finally nailed that weird issue where pressing enter would toggle the locales in in a multilingual setup.

PR:
https://github.com/pkp/ui-library/pull/58

Tests:
https://github.com/pkp/ojs/pull/2572
