### ISSUE TITLE
Update search and search indexing for versioning

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4859]
Searching, and the search index, have not been updated to account for the split between submissions and publications. This will need to be updated and tested.

## Acceptance Criteria OJS
All of these acceptance criteria refer to the reader-facing search interface for the journal.
- [x] When I search for an article by title, it will return an appropriate match.
- [x] When I search for an article by author's first name or last name, it will return an appropriate match.
- [x] When I search for a term that doesn't exist, no results will be returned.
- [x] When I publish an article that wasn't published, it will appear in search results.
- [x] When I unpublish an article's publication, and the article is no longer published, it does not appear in search results.
- [x] When I create and publish a new version with a different title, the search results return a match for the most recent version. For example, if the original version is titled "Lorem" and the new version is titled "Ipsum", a search for "Lorem" will not return the article in results but a search for "Ipsum" will return the article in results.

## Acceptance Criteria OMP
All of these acceptance criteria refer to the reader-facing search interface for  a press.
- [x] When I search for a submission  by title, it will return an appropriate match.
- [x] When I search for an submission  by author's first name or last name, it will return an appropriate match.
- [x] When I search for a term that doesn't exist, no results will be returned.
- [x] When I publish an submission  that wasn't published, it will appear in search results.
- [x] When I unpublish an submission's publication, and the article is no longer published, it does not appear in search results.
- [x] When I create and publish a new version with a different title, the search results return a match for the most recent version. For example, if the original version is titled "Lorem" and the new version is titled "Ipsum", a search for "Lorem" will not return the article in results but a search for "Ipsum" will return the article in results.

**Comment by NateWr** [comment]
I think that the search index can continue to be tied to submissions, not publications. Search terms should match a submission if any of that submission's publications match.

Take the following example:
- Submission's current publication ID: 2
- Publication 1 title: "Lorem ipsum dolor sit amet"
- Publication 2 title: "Ipsum dolor sit amet"

A search for "lorem" should return the submission. The search results UI should show the submission's current title, "Ipsum dolor sit amet", and link to the current version of the article.

**Comment by NateWr** [comment]
Tests in `CatalogSearchTest` are currently commented out and need to be restored once search is working again.

**Comment by asmecher** [comment]
@ajnyga, I'm still working on this issue, but https://github.com/pkp/ojs/commit/10245904854e8c0ca4021bd4be872e62c40161f3 contains a fix to the SQL error that searching has been generating since the versioning merge. This won't apply to PPS directly, since it involves code related to issues, but the relevant change will be the addition of the `publications` table as a new join. I can either flag these changes for you, or if you're ready for another set of hands on the PPS codebase, I can port it there too and send in a PR.

**Comment by asmecher** [comment]
Basic port of pkp/ojs@1024590 to PPS: https://github.com/ajnyga/ojs/pull/2

**Comment by asmecher** [comment]
Working again for OJS and OMP; needs some progress on the testing infrastructure before I'll close this for PPS!

**Comment by asmecher** [comment]
Testing stuff works too!

**Comment by jmacgreg** [comment]
@NateWr, @asmecher - I see this is closed, but still in Ready for review/testing, and the Acceptance Criteria are unchecked. Did you want someone to test those?

**Comment by NateWr** [comment]
Yes please! :)

**Comment by asmecher** [comment]
Yup, please; I forgot that part.

**Comment by withanage** [comment]
@NateWr 

I added the test scenarios for OMP to the header. From the 6 scenarios,  
3 went fine, in other 3 I have seen the following issues.

omp commit 4cb5638455e515084ca334071330fa643ae8f12a
lib/pkp c137018a8ab606c7cfd51e9b6c0a38b5e10ff9dc

| Scenario | Observations |
| --- | ---|
|When I search for an submission by author's first name or last name, it will return an appropriate match. | No results are found |
 | When I unpublish an submission's publication, and the article is no longer published, it does not appear in search results. | The  submission is still in the results|
 When I create and publish a new version with a different title, the search results return a match for the most recent version. For example, if the original version is titled "Lorem" and the new version is titled "Ipsum", a search for "Lorem" will not return the article in results but a search for "Ipsum" will return the article in results. | |

![omp](https://user-images.githubusercontent.com/1921992/72202292-d813ca80-345d-11ea-91a3-de648982d02a.gif)

**Comment by NateWr** [comment]
Thanks @withanage! I'm looking into the OMP problems that you had. With your OJS issue, it look like you may need to clear the cache. What you're seeing is the HTML from the new mobile nav header, but the new CSS doesn't look like it is being applied.

**Comment by withanage** [comment]
Thanks @NateWr . Sure, will try after clearing the cache.

**Comment by NateWr** [comment]
I think I've got the OMP issues sorted out. Going to take another look at OJS right now. One thing I noticed is that the search result cache was interfering with the results. Changing `$resultCacheHours` to `0` [here](https://github.com/pkp/pkp-lib/blob/master/classes/search/SubmissionSearch.inc.php#L207) helped clarify that during testing.

@asmecher do you know if there is a way to clear the search result cache from the code? We are updating the search index when a publication is published or unpublished, so it would be nice to be able to clear out the search result cache when that happens, rather than waiting for the hour to expire.

**Comment by asmecher** [comment]
> @asmecher do you know if there is a way to clear the search result cache from the code? We are updating the search index when a publication is published or unpublished, so it would be nice to be able to clear out the search result cache when that happens, rather than waiting for the hour to expire.

Yes -- you can use `DAO::flushCache()` (which calls on the corresponding function upstream in the ADODB library).

**Comment by NateWr** [comment]
:raised_hands: Just in time, Alec, thanks! Here are PRs that address the issues with OMP and improve behaviour around the search index and unpublishing. I added the cache busting and tried to push some code into pkp-lib.

PRs:
https://github.com/pkp/pkp-lib/pull/5393
https://github.com/pkp/ojs/pull/2576
https://github.com/pkp/omp/pull/741

I've marked the acceptance criteria complete but a second pair of eyes is always appreciated. :)
