### ISSUE TITLE
Migrate support for cover images to publications

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4861]
Cover images are not yet migrated from submissions to publications.

- [x] Add upgrade script to migrate them.
- [x] Link up the cover image field in the publication UI to the temporary file ID, and get it loaded correctly when a cover image is saved. (See Website Settings > Appearance for examples.)
- [x] Make sure cover images show correctly in the reader-facing UI.

## Acceptance Criteria
- [x] In OJS and OMP, I can upload a cover image to a submission. When published the cover image appears on the article/book landing page.
- [x] When I create a new version, I can change the cover image. When the new version is published, the new cover image appears on the article/book landing page.
- [x] When I upgrade an existing journal/press, any cover images that existed before the upgrade still appear for the correct article/book after upgrading.

**Comment by NateWr** [comment]
I ended up making some significant changes to OMP to align it with how OJS handles cover images. The plus side is that OMP now supports multilingual cover images with alt text for submissions. This was just easier than doing everything separately -- particularly the image upload form field, which expects to receive a certain set of information about an image.

@asmecher would you mind just glancing over this, particularly the OMP stuff where the substantive changes are to see if you can spot any problems with this?

PRs:
https://github.com/pkp/pkp-lib/pull/5102
https://github.com/pkp/ui-library/pull/39
https://github.com/pkp/ojs/pull/2477
https://github.com/pkp/omp/pull/707

**Comment by NateWr** [comment]
@asmecher just a reminder to look over the OMP changes here. We talked briefly about this a while ago and while you were hesitant to move the cover images into `/public`, you were alright with it if it was just aligning how it works with OJS.

**Comment by asmecher** [comment]
Thanks, @NateWr -- and yuck, this is a lot of unpleasant-to-maintain code (not your doing). I'm happy that we're centralizing around a single approach but will be happier still when a lot of this is done away with. In any case, yes, please go ahead and merge -- I didn't test the upgrade process, did you? If not (and probably regardless), we should put it on our list.

**Comment by asmecher** [comment]
(With apologies -- this is caused by my delay -- there is now a minor merge conflict on the converted locale files.)

**Comment by thinkbulecount2** [comment]
Tested all acceptance criteria and we are good! 👍

**Comment by NateWr** [comment]
Thanks!
