### ISSUE TITLE
Re-add support for supporting agencies

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4862]
Supporting agencies haven't been migrated to the new publication setup. Investigate what needs to happen for migration, data entry, and display to make it work.

**Comment by NateWr** [comment]
Also, can I just verify if supporting agencies are actively used? It was a new piece of metadata that I just found in the code but haven't seen before in the UI.

**Comment by asmecher** [comment]
"Supporting agencies" is one of the submission metadata fields that can be disabled/enabled in setup.

**Comment by NateWr** [comment]
This is addressed as part of #4863.
