### ISSUE TITLE
Support publications/versioning for DOIs and verify depositing

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4867]
Support for specifying a DOI needs to be added to the new publication UI. We also need to check that DOIs are getting deposited correctly.

Also, when a new version is created, DOIs should not be copied over. A new one should be created and deposited when a new version is published, probably? We should seek some advice from the Crossref/DOI people in the team.

## Acceptance Criteria
This acceptance criteria presumes that you have the DOI plugin installed and activated.
- [ ] I can assign a DOI to a publication when using the default DOI pattern setting.
- [ ] I can assign a DOI when set to enter a custom DOI each time.
- [ ] When set to enter a custom DOI, if I enter a DOI that doesn't match the DOI prefix, I get an error message.
- [ ] When a custom DOI pattern is set, I can assign a DOI to a publication if all of the pattern requirements are met (ie - if `%x` is used, a publisher-id must be set).
- [ ] When a custom DOI pattern is set and one or more pattern requirements are not met, I receive an error message.
- [ ] With either of the three DOI pattern settings (default, custom pattern, or custom entry), I can still add a DOI to issues, galleys, chapters, publication formats and files when enabled.

The acceptance criteria below presumes that you have the Crossref and DataCite plugins installed and activated.
- [ ] When a DOI is saved to a published publication, I can export it from the Crossref and DataCite import/export tools.
- [ ] When a DOI is saved to a published publication, I can register it from the Crossref and DataCite import/export tools.

The acceptance criteria below presumes that you are upgrading a site that has enabled DOIs for submissions and uses a custom DOI suffix pattern.
- [ ] After upgrading the site, DOIs are enabled for publications and my custom DOI suffix pattern for submissions is now used for publications.

**Comment by AhemNason** [comment]
I feel like I need to know a little more about what we mean by versioning when we talk about this. Once something is published, any changes to the metadata or content are covered by Crossref (and specifically using CrossMark). You'd keep the same DOI. 

But, with pre-prints that's not the case. https://www.crossref.org/blog/included-registered-available-let-the-preprint-linking-commence./ 

We've been working increasingly closely with Crossref so I might suggest that we could tap them for some advice on the execution here. I'm happy to reach out to our working group and pull someone into this conversation.

**Comment by NateWr** [comment]
> what we mean by versioning

For now, our primary use-case is to track changes after something is published. But as a distributed platform we should expect that others will move ahead before we fully embrace other use cases, such as:

- Pre-prints
- Early access
- Public peer review
- 2nd Editions (OMP)

Regarding our primary use-case, there are still some things that need to be worked out. If we think that all post-publication versions should have the same DOI, we should:

- Make sure the deposit happens with the URL to the article, not to the particular version of the article. (See https://github.com/pkp/pkp-lib/issues/4870)
- Consider whether the publisher ID is used in the URL that is deposited. If so, we have to update the record when the publisher ID of the current publication changes. (See https://github.com/pkp/pkp-lib/issues/4871)
- Disallow changing the DOI once any version has been published with a DOI.
- Figure out how, if at all, we are handling publication types in our deposits, and what to do when a new version with a different publication type is published. (See https://github.com/pkp/pkp-lib/issues/4860)

**Comment by AhemNason** [comment]
Addressing the primary, this sounds a lot like what Crossmark is for. I know @jnugent was working on a Crossmark plugin for a client so maybe he could chime in. I think Crossmark integration in our own Crossref plugin would be excellent. 

https://www.crossref.org/services/crossmark/ 

I'll address each... 

- Currently, if we have an article assigned a DOI on publication and anything changes, the URL is to the article itself, not a specific version. 
- DOIs do not currently (I think) automatically update if there's a change to record metadata, but users can push any changes. Anytime a URL changes, DOIs need to be updated. The URL really doesn't matter much in the long run so long as there is one that works and the registered DOI gets updated. 
- Disallowing a change to a DOI is good generally. I think from the UI-side we should only allow very, very limited DOI suffix options anyway. A surprising amount of DOI issues are due to human error and nothing about them needs to be machine readable. Crossref themselves may be limiting the ways in which DOI suffixes can be minted in the future, but Crossref are not the only DOI registration agency. 
- I'm very much into handling more publication "types". This is part of the crossref preprint service. We'd have to flag preprints specifically for their DOIs to be linked to the final published DOIs. Crossref has different schema for different content (conference proceedings, datasets, articles, preprints)... the relationship between a preprint and a final article should be handled on the Crossref side if things are done properly. 

James is away but we've identified interest in working together with Crossref here. I'll check with Kevin just to make sure there's no objections but I might pull Geoffrey in just to see if he has opinions and insights. We're hoping to have Crossref review the way the plugin functions anyway, and if we can get in front of issues with the versioning stuff, all the better.

**Comment by jnugent** [comment]
@AhemNason  - the crossmark plugin was shelved, the client didn't want to pursue the custom development it would have required.

**Comment by AhemNason** [comment]
> @AhemNason - the crossmark plugin was shelved, the client didn't want to pursue the custom development it would have required.

That's a bummer.

**Comment by NateWr** [comment]
Ok, so my understanding is that we don't need to do lots of new work related to versioning and DOIs. Once a DOI is set, new versions will not need to generate a new DOI and should be encouraged to keep the same DOI. It would be good, if possible, to automatically update a DOI record when metadata changes with a new version. But this is not offered right now and it can be done manually if desired.

As far as I can see, we need the following:

- [ ] Restore ability to assign a DOI to a publication.
- [ ] Create a custom input field with a button that can generate a DOI matching a pattern. Require the user to click a button to "enable" editing the DOI manually, and include a warning message to discourage this.
- [ ] DOIs copied when a new version is entered.
- [ ] (Maybe) notify the depositing plugin when a new version is published, so that it can automatically update the metadata records.

@AhemNason if you have a moment can you let me know if I've forgotten anything?

**Comment by AhemNason** [comment]
>     * [ ]  Restore ability to assign a DOI to a publication.

Restore? I'm not sure what you mean by restore here. 

>     * [ ]  Create a custom input field with a button that can generate a DOI matching a pattern. Require the user to click a button to "enable" editing the DOI manually, and include a warning message to discourage this.

Yeah, I think a warning is a good call. I think we ought to broadly discourage people from really touching DOIs manually in any way whenever we can. 

>     * [ ]  DOIs copied when a new version is entered.

Mmm hmm. 

>     * [ ]  (Maybe) notify the depositing plugin when a new version is published, so that it can automatically update the metadata records.

Yeah, both Crossref and Datacite plugins will probably need this. My recommendation is that, if a user has "automatic registration" enabled in the Crossref settings, it should also automatically update that DOI's registered metadata _any time the metadata in OJS changes_.

>     * [ ]  The URL to galleys will change when a new version is released, so DOI records need to be updated.

Same as above. 

>     * [ ]  A DOI gets automatically generated when something is published, even if the user has not visited the identifiers tab, unless they’ve selected the “I’ll write in my suffix” option in the DOI plugin

Yup. Most users do not want to think about DOIs. It would be _nice_, if users had to review the DOIs that were about to be minted when they publish, though. I get the sense that 3.2 has some intervention for metadata related to a publication and users seeing what DOIs are about to be minted for a whole issue would likely be good for both literacy and pre-empting registration headaches. 

> @AhemNason if you have a moment can you let me know if I've forgotten anything?

We should be as clear as we can possibly be that pre-prints are not yet supported. I suspect lots of people will try to put a square peg in this round hole and, if they do, it means they'll have the same DOI for both a pre-print and a final version. Crossref expects pre-print DOIs to be different from the DOIs of a published version.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/5153
https://github.com/pkp/ui-library/pull/43
https://github.com/pkp/ojs/pull/2496
https://github.com/pkp/omp/pull/715

(These PRs also address #4905).

**Comment by NateWr** [comment]
Merged

**Comment by NateWr** [comment]
@jmacgreg and @AhemNason I took the liberty of assigning this one to you two for testing. In addition to the specified criteria, please give it a real stress test. I was able to test the exports but not the registering or automatic depositing because I don't have the test setup that I need.

**Comment by navotera** [comment]
Dear @NateWr 
We just upgrade our journal from OJS 2 to OJS 3.2.1-4. We have upgrade it on other server and migrate it to the real server after we finish the upgrade, unfortunately the DOI record URL is mistakenly updated to the staging server location. 

Is there any mechanism on the OJS such as on its cron or when the upgrade process is being process connecting the DOI server to update the article URL ?

**Comment by AhemNason** [comment]
Hi @navotera 

The current OJS plugin has no method for batch _updating_ of DOI metadata. At the moment, the best method is to update the records issues-by-issue. If you submit too many at a time, the plugin will time out. To speed things up, I recommend turning off the validation check. 

It's worth noting that our crossref plugin is in the process of getting overhauled so this functionality (which would be appreciated by many users) will hopefully make it into the next iteration of the plugin when it is released. It's in development but yet to be scheduled. 

Mike

**Comment by navotera** [comment]
Thank you so much @AhemNason for your detailed explanation.
