### ISSUE TITLE
Restore support for parsed citations

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4875]
Parsed citations are not working since the introduction of versioning. The citations are not shown on the frontend and there's no field for entering them on the backend.

## Acceptance Criteria
- [x] I can add and edit references under the Submission Workflow > Publication.
- [x] When I have added references to a publication, I can see the references on the reader-facing landing page for the submission.
- [x] When I have added references to a publication that include URLs, they show up as links on the reader-facing landing page for the submission.
- [x] When I remove references from a publication, no references appear and the heading for the references section does not appear.

And if you have time test:
- [x] When I use real-life references from an active journal's submission in my test submission, the references in the reader-facing frontend are the same in my test site as in the active journal's website. (ie - the parsed citations are parsed the same in `master` and `stable-3_1_2`).

**Comment by NateWr** [comment]
A textarea field was put on the backend in a319fc92a but there is still no parsing of citations.

Citations don't seem to be multilingual. Shouldn't citations be multilingual? If so, we'll need to:

- [ ] Copy citations to all languages on upgrade.
- [ ] Change the input form to be multilingual.
- [ ] Update parsing to parse citations for each language.

**Comment by asmecher** [comment]
> Citations don't seem to be multilingual. Shouldn't citations be multilingual?

I would bet that this is a can of worms we should leave closed until we're really sure we need an open can of worms. We don't have multilingual support [solved on the citation producing side](https://forum.pkp.sfu.ca/t/ojs-how-to-cite-uses-wrong-language/55081/3), which is simpler than the citation parsing side.

**Comment by NateWr** [comment]
Ok, something to be addressed later then. :+1:

**Comment by crosfield** [comment]
This is a necessary thing for multilingual Cyrillic journals which should show citations in Russian in the special GOST format, but in English - in a different format. From this point of view, it is desirable the input form for citations to be multilingual, but parsing for non-English part of the form is not necessary.

**Comment by asmecher** [comment]
@crosfield, you are talking about multilingual citations, correct?

My concern is that simply transforming a text "citations" field into a multilingual input would inevitably lead to data synchronization problems between the two sets of citations when they were processed or updated manually, leading to different sets of citations being presented depending on what language you browse the site in.

In my opinion the "correct" way to do this would be to permit each citation to be individually enriched with multilingual data, e.g. alternate author names or titles, when that data is available. But I wonder if it would be better to integrate a third-party tool for that kind of data entry/management -- I wonder if Texture has a rich enough toolset?

**Comment by jmacgreg** [comment]
Hi @NateWr, I tested the first set of acceptance criteria, and they all pass. There's one unrelated issue though: if I provide references as an author during submission, the references field in the post-submission manuscript area is blank. In fact, I don't see any references recorded in the `citations` table at all for that particular submission. Should that be flagged as a separate issue?

**Comment by NateWr** [comment]
Thanks @jmacgreg! Exactly the kind of thing I'm hoping these tests will surface. Filed at https://github.com/pkp/pkp-lib/issues/5219.
