### ISSUE TITLE
Support previewing of metadata in the author/reviewer workflows

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4877]
When publications were introduced, the metadata form was removed. A new way for authors to preview the metadata (but not edit it) needs to be introduced.

We also need to make sure that the newly introduced feature to selectively permit users to edit metadata also works (https://github.com/pkp/pkp-lib/issues/3758) for authors. (This concern is also filed as part of the versioning work in #4874).

Previewing the metadata is also used in some capacity for reviewers, and this needs to be re-implemented.

## Acceptance Criteria
- [x] As an author, after I make a submission I can see my submission's information (title, abstract, contributors, metadata, references and galleys). But I am not able to edit them.
- [x] As an editor, I can edit an author's participant details to allow them to edit their publication.
- [x] After an editor has allowed the author to edit the publication, when I log in as the author I am able to edit all the publication details except the galleys.
- [x] After an editor has removed permission for the author to edit the publication, when I log in as the author I am not able to edit the publication details.
- [x] When revisions have been requested, the author sees an "Upload File" button at the top of the workflow, and is able to use that to upload revisions.
- [x] As a reviewer, I am able to preview the publication details such as title and abstract, but not see the author's details if it is a blind review.

**Comment by ajnyga** [comment]
Initial work for previewing metadata for reviewers. Is this concept ok @NateWr? If it is, I will add the rest of the metadata.

See https://github.com/NateWr/pkp-lib/pull/7 and https://github.com/NateWr/ojs/pull/6

**Comment by NateWr** [comment]
Yeah that looks great. A couple of comments:

- Let's call it `ViewSubmissionMetadataHandler` if that's not already taken. That way we can re-use for authors or other users who might want a non-editable view.
- Presumably you're just returning `$metadata` as a test. You'll use a template, yeah?

Thanks!

**Comment by ajnyga** [comment]
thanks, whether or not to use a template was one thing I was wondering. I can of course use one. Should I use a layout where for example I have a table with two columns, the first one for the field name and the second for the value? Or some other kind of display?

I will rename it. I will also probably divide the handler to two parts, one in pkp-lib and the second in ojs/omp so that the one in the app will only have the display function to deal with app specific metadata (if there are differences?). If we use a template I descrived above, we can just have a loop there that ouputs the table cells based on an array given to it. This way the template can be in pkp-lib.

**Comment by NateWr** [comment]
Maybe a reader-like view. Something like:

**Lorem ipsum: the submission title**
Antti-Jussi, University of Finland; Other Author, Public Knowledge Project

**Abstract**
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Keywords**: lorem ipsum, dolor sit amet
**Subject**: Eiusmod Tempor
**Discipline**: Cupidatat Non Proident
**Etc**: ...

-----
I guess the only thing we miss there is chapter details. Maybe the metadata (keywords/etc) can be in a table, and so you can add chapters to the array of table rows?

**Comment by ajnyga** [comment]
somehow I got things messed up when I pulled your recent changes.

But here it is anyway: https://github.com/NateWr/pkp-lib/pull/8

Still missing the OMP support for chapters. Noticed that it gives a notice for $additionalMetadata, but let me know if you want to change something else besides fixing that.

The thing I started to wonder is how do the versions affect the ongoing reviews? I mean if I do a review request and during that review the title and the abstract changes, is that reflected to the reviewer? Probably is? Not thinking that it would be too common though.

**Comment by NateWr** [comment]
The reviewer should always see the title/abstract of the "current publication". Before a version is published, that can be changed at any time and they'll see the changes.

If it happens to be published before or during the review stage, changes to that publication are locked. Any further changes must be made to a new version. And the new version does not become the "current publication" until it is published.

**Comment by ajnyga** [comment]
@NateWr probably not the final product, but here:
https://github.com/pkp/ojs/pull/2500
https://github.com/pkp/pkp-lib/pull/5165
https://github.com/pkp/ui-library/pull/45

**Comment by NateWr** [comment]
Looks great! I haven't yet taken it for a test run but I will do that soon. Are you able to do a PR for OMP as well?

**Comment by NateWr** [comment]
This looks great, thanks for doing this. It's been a big help! There are a couple of remaining things I had trouble with:

1. I can't get the revisions grid to reload after I upload a revision as an author. It doesn't seem like `AuthorReviewRevisionsGridHandler` loads at all. Maybe that's the problem you were talking about in terms of getting it to load properly?

2. When a journal manager makes a submission, AND they are assigned as an author with no other assignments, AND their stage assignment does not have permission to edit publications, they can still edit the publication data. They should be blocked from editing in this case.

Also, let's change the description of the option to enable/disable a stage assignment's permissions.

> **Submission metadata edit permission.**
> - [ ] Allow submission metadata changes by this user

Change this to:

> **Permissions**
> - [ ] Allow this person to edit the publication details.

**Comment by ajnyga** [comment]
Hi,

1) Weird, it does work for me? See https://recordit.co/ooThggfuob

2) Ok, will look into that now

**Comment by ajnyga** [comment]
I think 2 was actually fixed in one of your review suggestions. Saving does not seem to work under those conditions, but sure enough the button is visible. I will see on how to hide it.

**Comment by ajnyga** [comment]
Oh god, it took way too long to figure out why `canEditPublication` did not work as expected in hiding the edit button. The reason of course was that the variable used to be `disableSave` so logic there was of course opposite 🤣 

@NateWr all things in review should be considered now.
https://github.com/pkp/ojs/pull/2500
https://github.com/pkp/pkp-lib/pull/5165
https://github.com/pkp/ui-library/pull/45

**Comment by NateWr** [comment]
Great work @ajnyga! This is looking really good, with all the permissions handled properly and everything. I found one regression that impacted the regular workflow, which requires us to pass `canEditPublication` to that workflow component. I've prepared some diffs for you to apply:

OJS:
```diff
diff --git a/templates/workflow/workflow.tpl b/templates/workflow/workflow.tpl
index f2420284e7..e286311dee 100644
--- a/templates/workflow/workflow.tpl
+++ b/templates/workflow/workflow.tpl
@@ -77,7 +77,7 @@
 					{load_url_in_div id="submissionProgressBarDiv" url=$submissionProgressBarUrl}
 				</div>
 			</tab>
-			{if $canAccessPublication}
+			{if $canEditPublication}
 				<tab id="publication" label="{translate key="submission.publication"}">
 					<div class="pkpPublication" ref="publication" aria-live="polite">
 						<pkp-header class="pkpPublication__header">
```

pkp-lib:
```diff
diff --git a/pages/workflow/PKPWorkflowHandler.inc.php b/pages/workflow/PKPWorkflowHandler.inc.php
index 4a97c8ded..c34ce4873 100644
--- a/pages/workflow/PKPWorkflowHandler.inc.php
+++ b/pages/workflow/PKPWorkflowHandler.inc.php
@@ -124,15 +124,15 @@ abstract class PKPWorkflowHandler extends Handler {
 		$accessibleWorkflowStages = $this->getAuthorizedContextObject(ASSOC_TYPE_ACCESSIBLE_WORKFLOW_STAGES);
 		$workflowRoles = Application::getWorkflowTypeRoles();
 		$editorialWorkflowRoles = $workflowRoles[WORKFLOW_TYPE_EDITORIAL];
-		$canAccessPublication = false; // Access to title, abstract, metadata, etc
+		$canEditPublication = false; // Access to title, abstract, metadata, etc
 		$canAccessProduction = false; // Access to galleys and issue entry
 		// unassigned managers
 		if (!$accessibleWorkflowStages && array_intersect($this->getAuthorizedContextObject(ASSOC_TYPE_USER_ROLES), [ROLE_ID_MANAGER])) {
-			$canAccessPublication = true;
+			$canEditPublication = true;
 			$canAccessProduction = true;
 
 		} elseif (!empty($accessibleWorkflowStages[$currentStageId]) && array_intersect($editorialWorkflowRoles, $accessibleWorkflowStages[$currentStageId])) {
-			$canAccessPublication = true;
+			$canEditPublication = true;
 			$canAccessProduction = (bool) array_intersect($editorialWorkflowRoles, $accessibleWorkflowStages[WORKFLOW_STAGE_ID_PRODUCTION]);
 		}
 
@@ -267,6 +267,7 @@ abstract class PKPWorkflowHandler extends Handler {
 		}
 
 		$workflowData = [
+			'canEditPublication' => $canEditPublication,
 			'components' => [
 				FORM_CITATIONS => $citationsForm->getConfig(),
 				FORM_PUBLICATION_LICENSE => $publicationLicenseForm->getConfig(),
@@ -328,7 +329,7 @@ abstract class PKPWorkflowHandler extends Handler {
 		}
 
 		$templateMgr->assign([
-			'canAccessPublication' => $canAccessPublication,
+			'canEditPublication' => $canEditPublication,
 			'canAccessProduction' => $canAccessProduction,
 			'metadataEnabled' => $metadataEnabled,
 			'requestedStageId' => $requestedStageId,
```

ui-library:
```diff
diff --git a/src/components/Container/WorkflowContainer.vue b/src/components/Container/WorkflowContainer.vue
index e6d6299..a0a85b7 100644
--- a/src/components/Container/WorkflowContainer.vue
+++ b/src/components/Container/WorkflowContainer.vue
@@ -21,7 +21,7 @@ export default {
 	data() {
 		return {
 			contributorsGridUrl: '',
-			canEditPublication: '',
+			canEditPublication: true,
 			csrfToken: '',
 			currentPublication: null,
 			editorialHistoryUrl: '',
```

Once that's done, go ahead and prepare a PR for OMP and I'll merge it all in. :+1:

**Comment by ajnyga** [comment]
https://github.com/pkp/omp/pull/722

**Comment by ajnyga** [comment]
> Great work @ajnyga! This is looking really good, with all the permissions handled properly and everything. I found one regression that impacted the regular workflow, which requires us to pass `canEditPublication` to that workflow component. I've prepared some diffs for you to apply:
> Once that's done, go ahead and prepare a PR for OMP and I'll merge it all in. 👍

I made those changes, also for OMP.

**Comment by NateWr** [comment]
Thanks, I've had a look at the OMP stuff and it looks good. I think the author should be able to edit the chapters when they can edit publication data. One of the main use-cases for this is to ask the author to put final title/details after review, and it's possible that chapter names will be changed or even that whole chapters will be dropped/added.

I notice that the tests are failing consistently on finding the publication button: https://travis-ci.org/pkp/omp/jobs/602982627#L2831  It looks ok to me but i'll try to run the tests locally to see if i can pick out what's going wrong.

**Comment by NateWr** [comment]
Ok, the test failures are happening because OMP has a JS grid handler at `$.pkp.controllers.grid.files`. So when `AuthorReviewRevisionsGridHandler` is set up, it clashes with the namespacing. What I would recommend is to change the namespace declaration at the top of `ApprovedProofFormHandler.js` to:

```
$.pkp.controllers.grid.files.proof = { form: { } };
```

**Comment by NateWr** [comment]
Looks good! I have a couple of PRs that will fix the test failure in OMP. They also use the `canAdminister` methods to block direct access to the author/chapter grid ops.

https://github.com/ajnyga/omp/pull/1
https://github.com/ajnyga/pkp-lib/pull/1

You shuold be able to merge these in and they'll be added onto the PR. After merge, you'll probably need to add the submodule commit to run the tests. Let me know if you need help with this.

**Comment by NateWr** [comment]
New PRs:
https://github.com/pkp/ui-library/pull/50
https://github.com/pkp/pkp-lib/pull/5242
https://github.com/pkp/ojs/pull/2523
https://github.com/pkp/omp/pull/725

**Comment by NateWr** [comment]
@ajnyga The tests were failing because of a permissions error when the discussions grid was loading for reviewers during the review process. I've fixed it but you know these permissions better than me. Can you look over this commit for me?

https://github.com/pkp/pkp-lib/pull/5242/commits/85f0c1ac47274c5e689c5db4140282da82890d42

**Comment by NateWr** [comment]
All merge! :tada: A big thanks on this one @ajnyga!

**Comment by ajnyga** [comment]
> @ajnyga The tests were failing because of a permissions error when the discussions grid was loading for reviewers during the review process. I've fixed it but you know these permissions better than me. Can you look over this commit for me?
> 
> [85f0c1a](https://github.com/pkp/pkp-lib/commit/85f0c1ac47274c5e689c5db4140282da82890d42)

I wonder why that did not cause problems before? It is part of older changes.

But looking at it now, I think the old way I did it unnecessarely called the same policy twice. Your changes made it a lot better. Not seeing any problems there.

**Comment by NateWr** [comment]
> I wonder why that did not cause problems before? It is part of older changes.

It kicked in when I asked you to move that method into the `UserService` class. Woops. :)

**Comment by ajnyga** [comment]
Great thanks with the help on this. I will now proceed to apply this (and the hundred other recente commits) to PPS

**Comment by quoideneuf** [comment]
@NateWr All seems to work as described, however it does seem like the author can edit the metadata fields in the form even though the submit button has been removed (items 1 and 4 in the criteria list). Further, I was able to save the metadata changes by typing ``$('.pkpForm').submit()`` in the console...

**Comment by NateWr** [comment]
Thanks @quoideneuf. Can you check the stage assignment for the author to see if the checkbox to permit editing metadata is on/off?

**Comment by quoideneuf** [comment]
@NateWr Oops, looks like I was wrong about this. I do in fact get 403 responses when I try to post the metadata form with JS as the author after the checkbox has been unticked. Sorry about that!

**Comment by NateWr** [comment]
No worries! Thanks for taking a look.
