### ISSUE TITLE
Check production status notification with versioning features

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4879]
It looks like maybe there was a task or some kind of notification sent to production editors when galleys were removed from a submission. I couldn't quite untangle what's happening in `PKPEditingProductionStatusNotificationManager::updateNotification()`.

We need to look into it and figure out what's supposed to happen when galleys are removed from a publication. Should production user's get notified? Who and with what notification template? 

Then make sure that's implemented properly.

**Comment by asmecher** [comment]
@NateWr, we used to have functions called `updateNotification` that both created *and* deleted notifications, depending on the circumstances. Then every time a notification needed to be created or deleted, we'd just call the one helper function. I'm speculating without diving into it in detail but I suspect in this case there was a notification guiding the user through the end of the workflow process (in response to UI/UX testing revealing that users tended to get lost there). This would probably have guided the user to schedule the submission after a galley was created or something similar.

**Comment by NateWr** [comment]
I ~think~ hope that this is no longer necessary, now that the Publication tab has been designed with a clearer publishing workflow in mind. So this has been removed for now.
