### ISSUE TITLE
[OMP] redirecting of registered users to their home instead to the dashboard

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#488]
The registered users are redirected to the dashboard, which sometimes i.e. for some user groups/roles (e.g. for reader) leads to this message:
"
Open Monograph Press

The current role does not have access to this operation.
" 
Thus, "$request->redirectHome();" should be used instead.
The pull request is coming...

**Comment by asmecher** [comment]
Cherry-picked to omp-dev-1_1 and master. Thanks!
