### ISSUE TITLE
Implement support for publications in XML import/export

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4880]
The XML imports and exports need to be adjusted to support the submission/publication split.

**Comment by NateWr** [comment]
Part of the `ImportIssueTest` is currently commented out. This needs to be restored.

**Comment by NateWr** [comment]
`PKPStatsTest::generateUsageStats()` includes some code that should be able to be removed when `ImportIssueTest` is working.

**Comment by asmecher** [comment]
PRs from @defstat (I'll review them shortly):
- https://github.com/pkp/pkp-lib/pull/5555
- https://github.com/pkp/ojs/pull/2646

OMP to follow tomorrow (chapter support in progress).

**Comment by asmecher** [comment]
@defstat, I've reviewed both PRs above -- looking very good. I'll put some time into testing tomorrow (I can add some integration testing stuff in the process; it's currently disabled awaiting this fix). That's a lot of work!

**Comment by defstat** [comment]
@asmecher @NateWr 

OMP PR (with chapters): pkp/omp#775

**Comment by defstat** [comment]
@asmecher 

New pkp-lib PR: #5567
