### ISSUE TITLE
Support versioning for the subscriptions/payments features

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4883]
None of the subscription or payments features have been tested with the introduction of publications. Change/test/fix things as necessary.

## Acceptance Criteria
- [x] Galleys that should not be accessible due to payment and subscription settings can not be accessed.
- [x] Galleys that should be accessible due to payment and subscription settings can be accessed.
- [X] PayPal payments can be processed.

**Comment by asmecher** [comment]
Tested and fixed subscription purchase, article purchase, issue purchase, APC. I don't think Paypal will be automatable with Cypress due to pop-ups and redirects for authorization.
