### ISSUE TITLE
Long URLs not wrapping and overlapping contents in sidebar in the theme frontend

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#4889]
**Describe the bug**
In some browsers, long URLs in citations are not wrapping appropriately. This causes links to overlap with Copyright Notice statements in the right sidebar.

**To Reproduce**
Add a really long URL in an Abstract content and check how it goes over the sidebar of the Classis and Manuscript themes.

**What application are you using?**
 OJS 3.X.X

**Additional information**
I've fixed it including the following chunk in a stylesheet file and uploaded it:

```
div.item.references a {
	overflow-wrap: break-word
}
```

**Comment by NateWr** [comment]
:+1: Use the following instead, which will target it specifically on the article landing page:

```
.obj_article_details .references a {
	overflow-wrap: break-word;
}
```

**Comment by amandastevens** [comment]
This also seems to be happening with the Default theme. See https://patientsafetyj.com/index.php/patientsaf/article/view/99

**Comment by NateWr** [comment]
@amandastevens I'm unable to see a problem at the URL that you sent. It may be browser-specific. Can you send a screenshot of the issue and let me know what browser/OS you are using?

**Comment by israelcefrin** [comment]
@NateWr I´ve already fixed it applying a new rule to CSS, i.e.:

```
 .item.references a {
    word-break: break-all;
}
```

It fixes the long URL in the References section.

**Comment by israelcefrin** [comment]
And now I read your recommendation in https://github.com/NateWr/bootstrap3/pull/134#pullrequestreview-291703033 for using Sohpy´s CSS code from: https://github.com/pkp/pkp-docs/pull/263/files

I will adjust this client. Thanks!

**Comment by NateWr** [comment]
Closing this as outdated. If you can reproduce this with the default theme on a recent stable version, please provide reproduction steps and we can re-open this.
