### ISSUE TITLE
Too few arguments to function in PKPUserHandler::getUser

### ISSUE THREAD

**Issue by vitormattos** [pkp/pkp-lib#4891]
**Describe the bug**
The application return _Too few arguments to function_ in [UserService::getProperties](https://github.com/pkp/pkp-lib/blob/stable-3_1_2/classes/services/UserService.inc.php#L245) because the method [User::signature](https://github.com/pkp/pkp-lib/blob/stable-3_1_2/classes/user/User.inc.php#L75) need a argument.

**To Reproduce**
1. Authenticate or use `apiToken`
2. Make a request to path: /api/v1/users/1
2. See error

**What application are you using?**
 OJS version 3.1.2

**Additional information**
```ArgumentCountError: Too few arguments to function User::getSignature(), 0 passed in lib/pkp/classes/services/UserService.inc.php on line 245 and exactly 1 expected in lib/pkp/classes/user/User.inc.php:75```

**Comment by asmecher** [comment]
Merged and forward-ported to `master` -- thanks, @vitormattos!
