### ISSUE TITLE
Remove "blind" from review types

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4895]
Currently the review types in OJS are Double Blind, Blind, and Open, based on what has traditionally been used in academic publishing. Some people have pointed out that the term "blind" has ableist connotations, and more specifically "While this term has been used for quite some time, a growing body of scholars now recognize that it relies upon and perpetuates the stereotype that equates blindness with ignorance."

The current blind/double blind terminology can also be confusing to users who aren't familiar with it, compared to something more explicit such as author anonymous/author and reviewer anonymous.

I am not sure which new terminology is best or would be most widely understood, but I think the terminology needs to change. 

## Proposed replacement terms
| Double-blind | Blind |
| --- | --- |
| Author and Reviewer Anonymous | Reviewer Anonymous |
| Double Anonymous | ... |
| Mutually Anonymous | Anonymous Reviewer |
| Anonymous | Author Disclosed |
| Fully Anonymous | Partially Anonymous |
| Fully Anonymous | Semi-Anonymous |
| Anonymous Peer Review (APR) | Author Anonymous Peer Review (AAPR) |
| Author and Reviewer Identities Closed | Author Identity Open |

**Comment by LoriWalter** [comment]
I agree! I provide support for an OJS instance, and my faculty and student editors welcome a change in terminology. They have suggested, for example, double-anonymous peer review, etc. Thank you so much for being responsive to the community's needs.
Lori Walter
University of British Columbia, Okanagan campus

**Comment by NateWr** [comment]
Following up on a point raised during @thinkbulecount2's PKPBCN19 presentation about how we can communicate such considerations to translators. In WordPress, it's possible to add a contextual note to a translated string with `_x()` (see the example at the bottom):

https://developer.wordpress.org/reference/functions/_x/

It looks like this is passed to `gettext`. I'm not sure if it's included in the `.po` file or not. @asmecher do you know if there is any way to include instructions like this in a `.po` file and to have them presented in weblate?

**Comment by NateWr** [comment]
I've added a short list of proposed replacement terms to the original post.

**Comment by alexxxmendonca** [comment]
What about playing around with "closed", as opposed to "open" (peer review).

Although I agree that it may fall in the same issue of it "confusing to users who aren't familiar with it, compared to something more explicit such as author anonymous/author and reviewer anonymous.".

**Comment by dihagan** [comment]
Can you handle it like user roles so that journal managers can name their own review types?

**Comment by NateWr** [comment]
> What about playing around with "closed", as opposed to "open" (peer review).

I thought about that with "Anonymous / Author Disclosed". I think that "Reviewer Closed" or "Both Closed" maybe doesn't come across very clearly. Did you have any ideas here?

> Can you handle it like user roles so that journal managers can name their own review types?

I'd like to avoid this if possible. We only support the three types, and this needs to stay as-is because it's how we know what information to hide/reveal. If journals want to rename them, they can do so with the custom locale plugin to overwrite the text itself. But having a flexible review type system, like user roles, involves a lot of maintenance overhead on the technical side of things.

**Comment by alexxxmendonca** [comment]
> Did you have any ideas here?


Double-blind | Blind
-- | --
Author and Reviewer Identities Closed | Author Identity Open

Too long?

**Comment by sssoz** [comment]
Piggybacking off this issue to share the NHS’ content writing guide: https://beta.nhs.uk/service-manual/content/inclusive-language 

It’s a very simple and succinctly-written guide for using inclusive language in their digital service, part of a bigger document on content writing. 

@thinkbulecount2 and I thought that it could be something worth including in PKP’s guidelines (in the brand refresh?) as well, as a bigger effort to use inclusive language in all of PKP’s services.

**Comment by NateWr** [comment]
I think we've stalled on this because it's hard to choose one from all of the options. I suggest that we move forward with one of the options. We can always change it later.

I suggest we use Mutually Anonymous to replace Double-blind and Anonymous Reviewer/Disclosed Author to replace Blind. Does anyone feel we should choose one of the other options?

**Comment by alexxxmendonca** [comment]
> I suggest we use Mutually Anonymous to replace Double-blind and Anonymous Reviewer/Disclosed Author to replace Blind. Does anyone feel we should choose one of the other options?

I'm fine with that.

**Comment by mfelczak** [comment]
My vote would be for options that explicitly spell everything out so that there's no ambiguity in either role or access given that we're introducing new terminology, e.g. Anonymous Author/Anonymous Reviewer for Double-blind and Anonymous Reviewer/Disclosed Author for Blind.

**Comment by willinsky** [comment]
This goes beyond the wording for reviews but provided a way of working out the implications of using "anonymity."

[Untitled 2.pdf](https://github.com/pkp/pkp-lib/files/4854617/Untitled.2.pdf)

**Comment by asmecher** [comment]
I second @mfelczak's proposal:
> My vote would be for options that explicitly spell everything out so that there's no ambiguity in either role or access given that we're introducing new terminology, e.g. **Anonymous Author/Anonymous Reviewer** for Double-blind and **Anonymous Reviewer/Disclosed Author** for Blind.

It's a little longer but unambiguous and we can probably count on clearer translations.

@NateWr, would you be OK with that?

**Comment by willinsky** [comment]
Given "anonymous author" has another point of reference in publishing, I'd make a last pitch (and then happily let it go) that it is preferable to describe our peer-review process as employing "author and reviewer anonymity" rather than an "Anonymous Author/Anonymous Reviewer" as well as a second option of "reviewer anonymity" over  "Anonymous Reviewer/Disclosed Author" (as per my description above). Your call, @NateWr, as I agree that we do need this in place.

**Comment by asmecher** [comment]
@willinsky, thanks, I can see how that might be taken in the wrong context. I'm OK with your suggestion too.

**Comment by NateWr** [comment]
Thanks everyone! I have not forgotten this and we will get the change into 3.3. :+1: At the moment I'm leaning towards spelling things out as explicitly as possible, as Michael suggested and especially with regards to translations, as Alec pointed out. John's point about anonymous authorship in publishing is a good one to consider. However, I think the context of these options -- and especially they're position side-by-side -- will adequately address that ambiguity.

**Comment by NateWr** [comment]
When making this change, we can also apply [this recommendation](https://forum.pkp.sfu.ca/t/ensuring-a-blind-review-link-how-to-ensure-a-blind-review/61725) to change the "ensuring a blind review" links:

> I have been asked by an editor to change the (translated fr_CA version) of the link “Ensuring a blind review”... for something more interrogative/informative such as “How to ensure a blind review?” The editor argued that this link opens an informative text box and does not constitute an action as such (i.e. clicking on the link does not anonymize the document nor does it make this step mandatory, it only informs the user on how to do it).
>
> I was thinking of implementing that in the localized version of my journals (both en_US and fr_CA; OJS 3.1.x) but I must say I agree with a more interrogative phrasing and I thought that perhaps it could even be changed at the original terminology level? Would that make sense? Better yet, something like “How to ensure all files are anonymized ?” would be, IMHO, even more accurate…

**Comment by NateWr** [comment]
The following PRs replace the Blind/Double-blind terminology used throughout our applications.

- **Blind** is now **Anonymous Reviewer/Disclosed Author**
- **Double-blind** is now **Anonymous Reviewer/Anonymous Author**

![anon-reviewer-list](https://user-images.githubusercontent.com/2306629/98024244-ee7d7f00-1dff-11eb-8b6c-d0e78d7829f6.png)
![anon-reviewer-selection](https://user-images.githubusercontent.com/2306629/98024247-ef161580-1dff-11eb-8b2b-3d8a50633601.png)
![anon-reviewer-setting](https://user-images.githubusercontent.com/2306629/98024249-efaeac00-1dff-11eb-8739-d16e9b356f90.png)

I've also applied the [recommended change](https://github.com/pkp/pkp-lib/issues/4895#issuecomment-658124153) for the "Ensuring a blind review" language.

![anon-reviewer-upload](https://user-images.githubusercontent.com/2306629/98024272-f9381400-1dff-11eb-9306-194e0dd76bfb.png)
![anon-reviewer-instructons](https://user-images.githubusercontent.com/2306629/98024270-f89f7d80-1dff-11eb-8e51-1486b1118c4a.png)

Heads up for developers: I've also updated the `SUBMISSION_REVIEW_METHOD_BLIND` and `SUBMISSION_REVIEW_METHOD_DOUBLEBLIND` constants.

PRs:
https://github.com/pkp/pkp-lib/pull/6314
https://github.com/pkp/ui-library/pull/119
https://github.com/pkp/ojs/pull/2894
https://github.com/pkp/omp/pull/873
(OPS did not need a PR, and changes to the `doc/manual` submodules were pushed directly to those repositories' `master` branches)

**Comment by NateWr** [comment]
:tada: All merged! This change will go out with 3.3. Thanks to everyone for the team effort on this one. I'm really excited to see us leading the way here.

@amandastevens and @kaitlinnewson this will effect documentation.
