### ISSUE TITLE
[OJS3.1.2-1] Statistics/Articles: Titles do not match Locales chosen

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#4899]
**Describe the bug**
When you choose any locale (except English) the article titles would not match it. That is, they would always stay English. While the author names would change according to the locale chosen.

**To Reproduce**
1. In a multilingual journal go to 'Statistics --> Articles'
2. Choose any locale/language except 'English'
3. See the titles stay English in the 'Article Details'. While the author names change according to the locale chosen.

**What application are you using?**
 OJS version 3.1.2-1

**Additional information**
![image](https://user-images.githubusercontent.com/22288161/60708812-97b81a80-9f17-11e9-813f-7824d347a351.png)

**Comment by asmecher** [comment]
It looks like a hard-coded `en_US` snuck in. This has already been fixed in master but here is a PR that should fix it for `stable-3_1_2`: https://github.com/pkp/pkp-lib/pull/4913

@Ph-We, can you verify that this resolves the issue for you?

**Comment by Ph-We** [comment]
@asmecher, I cannot verify that, since we only use packages. Though I hope it will help. Thank you!

**Comment by asmecher** [comment]
It works here so I merged it. Thanks for reporting, @Ph-We!
