### ISSUE TITLE
Fix open access notification

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#490]
The open access notification settings (and associated task) are currently broken. Fix/remove/?

**Comment by asmecher** [comment]
@mfelczak, I think you were tinkering with this, correct?

**Comment by mfelczak** [comment]
Hi @asmecher, the scheduled tasks for subscription/open access notifications were removed as part #1838 but it looks like the email templates are still there, I'll remove them as well.

**Comment by asmecher** [comment]
I'd suggest we leave the templates there, in case they're useful when we re-introduce the feature.

**Comment by mfelczak** [comment]
Sounds good, closing then.

**Comment by asmecher** [comment]
I would suggest removing it. It should be rewritten rather than reintroduced.
