### ISSUE TITLE
Missing translation key category.noTitlesSection

### ISSUE THREAD

**Issue by tgc** [pkp/pkp-lib#4901]
While testing with OMP 3.1.2 we noticed that when browsing categories with no manuscripts associated it would show this text:
##catalog.noTitlesSection##

Looking at the history I see that this key was removed in #4446 and from the looks of it replaced with catalog.category.noItems.
Only the two templates using the old key was not updated to reflect this.

[edited for speling]

**Comment by tgc** [comment]
PR: https://github.com/pkp/omp/pull/689

**Comment by tgc** [comment]
Cleanup in pkp-lib
PR: https://github.com/pkp/pkp-lib/pull/4911

**Comment by NateWr** [comment]
All merged, thanks @tgc!
