### ISSUE TITLE
Remove published_submissions dependency in OAIDAO

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4906]
`OAIDAO::_getRecordsRecordSet()` looks in the `published_submissions` table. This needs to be rewritten to fetch records without that table now that it has been removed.

**Comment by asmecher** [comment]
@NateWr, I'm pretty familiar with that interface; let me know when the underlying schema etc. has stabilized enough, and I can adapt this query.

**Comment by NateWr** [comment]
The schema should be pretty settled now. You can tell a submission is published if it has the `STATUS_PUBLISHED` status. This should be set whenever it has one publication with the same status.

The `current_publication_id` column in the `submissions` table points to the most recent published version.

Issue and section assignments are attached to the `publication` object instead of the `submission` object.

**Comment by asmecher** [comment]
(Also fixed a small issue with OAI DC11 related to versioning)
