### ISSUE TITLE
Article list in new statistics page does not show multilingual article titles

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4916]
**Describe the bug**
In multilingual journals only the article title’s given in English are visible in the statistics page. All other title’s are missing so they are just showing the author’s name.

In 3.1.2 stable https://github.com/pkp/pkp-lib/blob/stable-3_1_2/templates/stats/publishedSubmissions.tpl#L138 should be
`<span class="pkpStatistics__itemTitle" v-html="localize(row.object.fullTitle, row.object.locale)"></span>`

In master https://github.com/pkp/pkp-lib/blob/master/templates/stats/publications.tpl#L184 should be
`<span class="pkpStats__itemTitle" v-html="localize(row.publication.fullTitle)"></span>`

**To Reproduce**
See the statistics page for a multilingual journal

**What application are you using?**
 OJS or OMP version 3.1.2

@NateWr

**Comment by asmecher** [comment]
I think this was recently resolved here: https://github.com/pkp/pkp-lib/issues/4899

**Comment by ajnyga** [comment]
yes!
