### ISSUE TITLE
Problem with searching reviewer name with accented character 

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#4917]
**Describe the bug**
While searching for a reviewer whose name is "José", the system returns an error message.

I believe the issue must be with the accented character "é" since everything is fine while typing "jos". The error message arises after the "é" is typed in.

**To Reproduce**
https://drive.google.com/file/d/1DYTJfWIMF6aFhhzkQQf61vJ_H49fDy_x/view

**What application are you using?**
 OJS version 3.1.2.1

**Additional information**
I tested it with a Demo journal, typing "José" on the reviewer search, but the problem did not occur. Said user is not registered on the demo journal, though.

**Comment by asmecher** [comment]
@alexxxmendonca, is there anything relevant in the PHP error log? (Also, I know it's in the video, but it's best to put the error message here in text form for searchability.)

**Comment by alexxxmendonca** [comment]
@asmecher yes, I think:

[erro-ojs.txt](https://github.com/pkp/pkp-lib/files/3387658/erro-ojs.txt)

> Also, I know it's in the video, but it's best to put the error message here in text form for searchability.

Sure, sorry about that! The message is:

_An unexpected error has occurred. Please reload the page and try again._

**Comment by asmecher** [comment]
@alexxxmendonca, I just tested this with a local install and I don't see the same problem. Is it possible that your database character set isn't properly configured as UTF-8 or that there is corrupted user profile data in your database where accented characters are used?

**Comment by carolinatanigushi** [comment]
hey @asmecher, we tried setting the database to UTF-8 and it did solve that problem (plus the other issue we previously talked about not being shown a reviewer list when trying to pick a reviewer).

So the database was set as follows:
```
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```
Then changed into:

```
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | utf8                       |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```

As I previously said, we can now see find the reviewer and see the reviewer list, however, the characters have all lost their encoding (eg "É" has turned into "Ã‰") and we get the following PHP error:

```
[Tue Jul 16 15:15:19.340561 2019] [php7:notice] [pid 126787] [client 192.168.1.91:63340] PHP Notice:  unserialize(): Error at offset 237 of 1352 bytes in /var/www/submission_scielo_br/htdocs/lib/pkp/classes/db/DAO.inc.php on line 352, referer: https://homolog-submission.scielo.br/index.php/rbedu/submissions
```

Do you know of a way we can fix this?

**Comment by asmecher** [comment]
@carolinatanigushi, setting all the database encodings to UTF8 is only half the solution -- the other half is converting the data that's already there, or you'll end up with garbled accented characters as you describe. See https://medium.com/@jesseproudman/getting-out-of-mysql-character-set-hell-8431e75383db for a comprehensive article on fixing this.
