### ISSUE TITLE
[OJS3] Submission numbers jumped for 100 to 100 000

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#4918]
Bonjour, 
We use OJS 3 (one instance for multiple journals) since January 2019. We have 4 journals: 2 productions and 2 that are being implemented. 
So far, submission numbers were under 100 but since 2 weeks, it jumps to 100 000...Is there any know explaination for this?

Thank you very much.
Best, 
Pierre

**Comment by asmecher** [comment]
Pierre, are you using PostgreSQL? If so, I'd suggest checking the sequences that are used in the DB to implement autonumbers (for the `submission_id` column in `submissions`).

**Comment by pilasou** [comment]
Hi Alec, No, we are still using MS SQL. I understand this maybe a database problem. I will fill an issue on our side.

**Comment by NateWr** [comment]
Closing this because we do not currently support MS SQL.
