### ISSUE TITLE
[OMP] make ONIX list available to all locales

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#492]
OMP's publication workflow needs */locale/en_US/ONIX_BookProduct_CodeLists.xsd*. While the list itself can be shipped with OMP, it cannot be translated without permission.

We could
a) insert a symlink to that file from the other locales or
b) remove the file from the en_US locale directory and point *classes/codelist/ONIXCodelistItemDAO.inc.php* to the (identical) copy of the ONIX code list in *plugins/importexport/onix30/*

**Comment by asmecher** [comment]
@mtub, I think this might've been resolved already -- see:
http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8660

**Comment by bozana** [comment]
I could see if the patch could also be used in OMP stable... Because else, OMP stable cannot be used only in another language...

**Comment by asmecher** [comment]
@bozana, agreed -- I've ported it to omp-dev-1_1 and omp-stable-1_1_1. We might well not release OMP 1.1.1-2 or 1.1.2 based on those branches; we might go to OMP 1.2 from master. But anyway.
