### ISSUE TITLE
Submission event log should record when a new version has been created

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4921]
The submission's editorial history should include an event when a new version of a publication has been created.

This should go into `PKPPublicationService::version()`.

## Acceptance Criteria
- [x] After I create a new version of a publication, when I open the Activity Log I see an entry for the new version that I created.

**Comment by thinkbulecount2** [comment]
Just keep getting the Loading screen... Am I possibly missing something?

<img width="286" alt="Screen Shot 2019-12-12 at 21 14 10" src="https://user-images.githubusercontent.com/38994650/70715031-5cbade00-1d24-11ea-8130-7626395a1111.png">

**Comment by NateWr** [comment]
Looks like there's an error happening. Can you check for a) a fatal error in the server error log and b) an error in the browser console?

**Comment by thinkbulecount2** [comment]
`TypeError: "this.loadRevisionsGrid is not a function"
    workingPublication http://localhost:8000/js/build.js?v=3.2.0.0:8
    run http://localhost:8000/js/build.js?v=3.2.0.0:20
    Qn http://localhost:8000/js/build.js?v=3.2.0.0:20
    _t http://localhost:8000/js/build.js?v=3.2.0.0:20
    dt http://localhost:8000/js/build.js?v=3.2.0.0:20`

Did I miss something in my Vue build?

**Comment by NateWr** [comment]
That shouldn't be effecting the activity log, but it does indicate that you may need to rebuild the JS package (`npm run build`), or that one of the repos needs to be synced with upstream/master.
