### ISSUE TITLE
OJS 3.0b cannot be tested because of installation/deploying error

### ISSUE THREAD

**Issue by atremba** [pkp/pkp-lib#494]
There is an error when trying to test OJS 3.0 beta.

How to reproduce (without extra details):
- clone `pkp/ojs` repository by `git clone git@github.com:your-username/ojs.git ojs-master-clone` 
- update modules: `git submodule update --init --recursive`
- make server access (DocumentRoot etc) to the folder `ojs-master-clone`
- try to access the installation via `http:\\some-server-address\` and get error in logs: 
`PHP Warning:  require_once(./lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php): failed to open stream: No such file or directory in /home/some-path/ojs-master-clone/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 25`

There is no such folder `vendor` in `./lib/pkp/lib/` indeed, in fact, it is ignored in `pkp/.gitignore`.

That's because smarty is not included as submodule or beta nature of OJS 3 or else?
Is it possible to test OJS 3?

**Comment by asmecher** [comment]
@atremba, see this post: http://forum.pkp.sfu.ca/t/how-to-install-ojs-from-github/184
