### ISSUE TITLE
[OJS] Prefix fallback in article title

### ISSUE THREAD

**Issue by GrazingScientist** [pkp/pkp-lib#4945]
We came across the issue that when we have a multi-language journal (german [main language] and english in our case), the title prefix in the article detail page does not work properly.

When there is only a title prefix given in one language and the other one is left empty, the given prefix is displayed in both languages in the title on the article page. This seems to be a bug in the getLocalizedTitle() function, I guess.

Best Regards,

Adrian

**Comment by asmecher** [comment]
@GrazingScientist, try out this pull request (applied in lib/pkp) -- it should prevent the fallback from coming from a different language. If you're able to confirm, I'll see about getting it into the next release.

https://github.com/pkp/pkp-lib/pull/4970

**Comment by GrazingScientist** [comment]
Your commit seems to fix the issue! Thanks a lot! 👍

**Comment by asmecher** [comment]
Merged and cherry-picked forward, thanks for confirming!
