### ISSUE TITLE
ABNT citation style needs location

### ISSUE THREAD

**Issue by diegoabadan** [pkp/pkp-lib#4946]
The Citation Style Language Plugin supports the ABNT citation format, but I couldn't find where to set _publisher-place_ variable.

In the old plugin it was possible to make this configuration, as #2694

OJS version 3.1.2-1

**Comment by asmecher** [comment]
@diegoabadan, this PR will add a "publisher place" setting to the Citation Style Language plugin's settings form:

https://github.com/pkp/citationStyleLanguage/pull/55

If you enter a value, you'll see it showing up in e.g. the Bibtex citation download. However, it doesn't seem to be added to ABNT. Would you mind poking around in the CSL to see what the issue might be?

**Comment by NateWr** [comment]
@asmecher where is this `publisherLocation` setting? I've never seen it and its not in the `context` schemas:

https://github.com/pkp/pkp-lib/blob/master/schemas/context.json
https://github.com/pkp/ojs/blob/master/schemas/context.json

Should it be?

**Comment by NateWr** [comment]
Oh... I see now it's in the CSL plugin settings. Got it. :+1:
