### ISSUE TITLE
[OJS] More accurate name for Site Navigation region's Search region

### ISSUE THREAD

**Issue by spudthebud** [pkp/pkp-lib#4948]
Looking at this [OJS 3.0 example](https://demo.publicknowledgeproject.org/ojs3/demo/index.php/demojournal/issue/view/1) `/html/body/div[3]/header/div/nav[1]/div/form` has `role="search"`.  

However the label is not set and so defaults to "Search"

I suggest adding `aria-label="Article Search"` as it's a more precise about what the search is doing. For example, it's not searching the entire site (e.g., About Pages); rather, it's just searching for articles. 

A more accurate label will save screen reader users time.  For sighted users, it is easy to understand what it's doing with a quick glance. But when you use a screen reader, you have to inspecting the results of the search serially to determine what it is doing.

**Comment by thinkbulecount2** [comment]
Will need to do in OMP as well, but instead of `Article Search`, it would be `Book Search`

**Comment by thinkbulecount2** [comment]
PRs:
[OJS](https://github.com/pkp/ojs/pull/2445)
[OMP](https://github.com/pkp/omp/pull/695)
cc: @NateWr

**Comment by NateWr** [comment]
All merged, thanks!
