### ISSUE TITLE
[OJS] Search results should return a List

### ISSUE THREAD

**Issue by spudthebud** [pkp/pkp-lib#4949]
Looking at the [OJS 3.0 example,](https://demo.publicknowledgeproject.org/ojs3/demo/index.php/demojournal/index), conduct a search for "open".  This returns 3 articles.

Programmatically, the search results are  structured as nested divs (`div.search_results` which contains 3 `div.obj_article_summary`). However, visually, it is styled as a list of results. 

Better to use HTML5 semantics. This will facilitate navigation with screen readers and other assistive technologies that rely on semantics tagging.

Example: 

```
<section aria-label="Search results">
<h2>Search results</h2>
<ul>
<li>
    <div class="obj_article_summary">
        <div class="title"><h3>Scholarly Associations and the Economic Viability of Open Access Publishing</h3></div> <!-- H3 to navigate results by article title -->
        <div class="authors"><h4>John Willinsky<h4></div> <!-- H4 to navigate results by author -->
        <div class="published"><h4>2001-01-1<h4></div> <!-- H4 to navigate by date of publication -->
    </div>
</li>
<li>etc. etc. </li>
</ul>
</section>
```

**Comment by NateWr** [comment]
Thanks for the review @spudthebud! 

Providing a section with an `aria-label` seems like a good idea, but I wonder if it becomes verbose when it duplicates the `<h2>` text. I agree that, for screen readers, it is usually better to be too verbose than to be unclear. But in this case, I'm not sure if we're adding any additional navigation benefits with the `aria-label`. Do you know?

A similar concern is why I haven't made the search results into a `<ul>`. My (non-expert) understanding is that the benefit of lists for screen readers are:

1. Can jump to next list item in one command.
2. The total list count is read out ("List. 6 items.")
3. The screen reader stops or pauses between list items.

Regarding (1), in our search results each result has only one link, so navigating from one to the next should be pretty quick. 

Regarding (2), I wonder if this would be considered inaccurate information when there is more than one page of search results. For example, if 50 results were returned but the screen reader read out "List. 30 items." that might be confusing. Do you know anything about standard practices for screen readers in such circumstances when the presented list is partial?

On reviewing our default theme, we don't really indicate the total number of found items before the list. Doing this might ameliorate the confusion for screen readers, but also make the extra text read out from a list unnecessary.

**Comment by spudthebud** [comment]
I don't rely on screen readers, so would defer to consensus of those who do.

Regarding (1).  Each result has 2-4 links: title, PDF, XML, HTML.  If there are 10 results, that's 20-40 links a person would have to navigate.  It seems common for people to wanted to navigate quickly by title, author, or date of publication. That's what I'm suggesting be made equivalent. 

Regarding (2). Good point. I don't know. 

New thing...  

The PDF/HTML/XML link's aren't well named. They all appear with the name PDF/HTML/XML in VoiceOver. What about this:

```
<div class="title" id="1">Scholarly Associations and the Economic Viability of Open Access Publishing</a>
...
<a class="obj_galley_link file" href="...." aria-labelledby="1">PDF</a>
```

Although that might clash with XML/HTML names.

Ideally. I wonder if might be read as: 

> PDF: Scholarly Associations and the Economic Viability of Open Access Publishing 
> HTML: Scholarly Associations and the Economic Viability of Open Access Publishing 
> XML: Scholarly Associations and the Economic Viability of Open Access Publishing 
>

**Comment by NateWr** [comment]
Thanks @spudthebud!

1. In the demo example that you sent, no galley links (PDF/XML/HTML) appear in the search results, so there is only one link per entry. Are you seeing something different?

> The PDF/HTML/XML link's aren't well named.

I agree it would be nice to improve the naming here somehow for lists where these appear. However, not all galleys are necessarily a PDF, HTML or XML version of the article. We also support attached data sets, supplementary files, artwork and other files that aren't necessarily galleys.

In lists of submissions, only the primary galleys are usually shown. Although we can't know for sure that these are PDF/HTML/XML, etc (some might have more useful names), it might be a reasonable assumption for us to make in our stock themes.

I don't think `aria-labelledby` is the correct attribute. My understanding is that this gets read out _instead of_ the text. So it would never say PDF, HTML, XML, etc. I think `aria-describedby` is more correct here, but I don't know if this solves the original problem, which is the way that all links on a page can be collected in a list for quick navigation for screen readers. Do they include `aria-describedby` in these lists or not? If not, we may not be adding much helpful information here.

I would be interested in hearing from active screen reader users or professional accessibility consultants before making changes on a whim here. Perhaps we can improve things through more use of `<section>` or other faceting of the page. But I'm not sure.

**Comment by spudthebud** [comment]
I'm a certified Web Accessibility Specialist.

The WCAG 2.x guidelines and supporting documents were written by consultants and people with disabilities.

Any format (PDF, HTML, etc.) should have a meaningful label.  As it stands, the current techniques being used is triggering a known failure ([F30](https://www.w3.org/WAI/WCAG21/Techniques/failures/F30.html#tests))

Aria-labelledby is appropriate:

> The aria-labelledby attribute is similar to the aria-describedby in that both reference other elements to calculate a text alternative, but a label should be concise, where a description is intended to provide more verbose information. [(source](https://www.w3.org/TR/wai-aria-1.1/#aria-describedby))

I've also consulted the [Accessible Name and Description computation](https://www.w3.org/TR/accname-1.1/#mapping_additional_nd_te
) algorithm, and recommend this. 

```
<div class="title" id="name1">Scholarly Associations and the Economic Viability of Open Access Publishing</a> ...
<a id="pdf1" class="obj_galley_link file" href="...." aria-labelledby="pdf1 name1">PDF</a>
```

That will produce an alt text label like:

> PDF Scholarly Associations and the Economic Viability of Open Access Publishing

**Comment by NateWr** [comment]
Thank you @spudthebud, that's great! And thanks for letting me know you've got experience with this stuff! There is a lot of well-intentioned but inappropriate application of aria out there, so I have learned to be cautious about taking on every suggestion without thinking it through.

We are currently having a third-party accessibility specialist audit our default theme so we should get some actionable feedback to work from there. A small accessibility working group is forming in the community (or has formed) to help us devise and follow through on timelines for audits and fixes, starting with the reader-facing frontend and working towards the backend. Would you be willing to help us in a more sustained fashion by talking with @israelcefrin, who is heading up that group? He can be contacted privately on our forums (https://forum.pkp.sfu.ca/) where his username is `israel.cefrin`.

So, in terms of actions we've definitely decided to take, I've got:

- [ ] Use `aria-labelledby` in galley links to better describe PDF/HTML/XML buttons.
- [ ] Add text indicating "1-20 of 30 results" _above_ the list so it is read out before the list.

Things for further discussion are:

- [ ] Consider a `<section aria-label="Search Results">` and maybe link the "1-20 of 30" text to this, by using `aria-describedby`? Is there an appropriate pattern you're aware of for linking total counts to the search results?
- [ ] Consider using a `<ul>` for search results instead of `<div>`s. If we have better visibility of "1-20 of 30", will that negate the problem of a list saying "List. 20 Items." when there are 30 possible results?

cc @thinkbulecount2 I think we're starting to land on some actionable items here.

**Comment by spudthebud** [comment]
I've reached out to Israel. 

    On Monday, August 5, 2019, 8:05:42 a.m. EDT, Nate Wright <notifications@github.com> wrote:  
 
 
Thank you @spudthebud, that's great! And thanks for letting me know you've got experience with this stuff! There is a lot of well-intentioned but inappropriate application of aria out there, so I have learned to be cautious about taking on every suggestion without thinking it through.

We are currently having a third-party accessibility specialist audit our default theme so we should get some actionable feedback to work from there. A small accessibility working group is forming in the community (or has formed) to help us devise and follow through on timelines for audits and fixes, starting with the reader-facing frontend and working towards the backend. Would you be willing to help us in a more sustained fashion by talking with @israelcefrin, who is heading up that group? He can be contacted privately on our forums (https://forum.pkp.sfu.ca/) where his username is israel.cefrin.

So, in terms of actions we've definitely decided to take, I've got:
   
   -  Use aria-labelledby in galley links to better describe PDF/HTML/XML buttons.
   -  Add text indicating "1-20 of 30 results" above the list so it is read out before the list.

Things for further discussion are:
   
   -  Consider a <section aria-label="Search Results"> and maybe link the "1-20 of 30" text to this, by using aria-describedby? Is there an appropriate pattern you're aware of for linking total counts to the search results?
   -  Consider using a <ul> for search results instead of <div>s. If we have better visibility of "1-20 of 30", will that negate the problem of a list saying "List. 20 Items." when there are 30 possible results?

cc @thinkbulecount2 I think we're starting to land on some actionable items here.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/2447

**Comment by NateWr** [comment]
We determined these two issues didn't apply to OMP, so I've merged the OJS pull request. I'll close this issue for now, in the knowledge that we'll have a more comprehensive list of changes coming up from the audit.
