### ISSUE TITLE
QuickSubmit plugin increments submission ID by 2 for each submission

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4950]
**Describe the bug**
For some journals, the submission ID is used not only in OJS but also in several external systems and data exports (including DOI creation and DOI pattern). In these external systems, the increment for each new submission is 1. In OJS 2.x the increment was also 1 for the process via QuickSubmit, so submission IDs in OJS matched IDs in all other systems. But since the upgrade to OJS 3, the increment is now 2 (IDs created under number 1, then number 3, then 5, then 7, etc.).

**To Reproduce**
This "additional" increment happens when you choose the section in the metadata. The system seems to register a first time when you select the section (and this ID number is then "lost", does not appear at all in the OJS system), and a second time when you hit the "save" button to effectively create your submission.

**What application are you using?**
OJS 3.1.1-2

**Comment by asmecher** [comment]
@mfelczak, the submission ID is supposed to be "informationless", i.e. nothing should depend on its behavior beyond uniqueness.

**Comment by asmecher** [comment]
This is a quirk that will be resolved with https://github.com/pkp/pkp-lib/issues/7224.
