### ISSUE TITLE
lib/pkp/tools/installPluginVersion.php install data issue when running from command line

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#4953]
**Describe the bug**
When trying to execute `lib/pkp/tools/installPluginVersion.php` on a plugin that overrides the `getInstallDataFile()` function, a fatal exception is being thrown because of the `$installer->dataXMLParser` being null (the exception occurs at `https://github.com/pkp/pkp-lib/blob/master/classes/plugins/Plugin.inc.php#L543`).

When the tool script is executed, the `preInstall()` function (`https://github.com/pkp/pkp-lib/blob/master/classes/install/Installer.inc.php#L130`) is not executed, causing the `dataXMLParser` not being initialized. 

**Workaround**
The web tool to initiate the upgrade process for OJS is working as expected.

**What application are you using?**
 That may correlate to all 3.x.x versions

**Additional information**
`PHP Fatal error:  Uncaught Error: Call to a member function parseData() on null in /lib/pkp/classes/plugins/Plugin.inc.php:515
Stack trace:
#0 /lib/pkp/tools/installPluginVersion.php(104): Plugin->installData('Installer::post...', Array)
#1 /lib/pkp/tools/installPluginVersion.php(112): InstallPluginVersionTool->execute()
#2 {main}
  thrown in /lib/pkp/classes/plugins/Plugin.inc.php on line 515`

**Comment by asmecher** [comment]
@defstat, try this PR: https://github.com/pkp/pkp-lib/pull/4968

**Comment by asmecher** [comment]
Merged and cherry-picked forward to `master` -- thanks for the review, @defstat!
