### ISSUE TITLE
Change translation description plugin gallery

### ISSUE THREAD

**Issue by colfreepress** [pkp/pkp-lib#4954]
**Describe the bug**
Please translation description plugin gallery in Spanish and others languages

![image](https://user-images.githubusercontent.com/53481401/62138415-9cbd7f00-b2b5-11e9-9db3-da77bce3aaf2.png)

**To Reproduce**
1. Go to settings website
2. Click on Plugins and Plugin Gallery
3. See  the information in English

**What application are you using?**
 OJS  version 3.1.2.1

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by asmecher** [comment]
@colfreepress, this list of descriptions comes from the PKP website:
http://pkp.sfu.ca/ojs/xml/plugins.xml
We unfortunately don't have much of  a workflow at the moment for managing translations of these, but if you're willing to contribute some, I'll happily add them manually.

**Comment by asmecher** [comment]
(Will be resolved when plugin description management is moved out of the plugins.xml flatfile and into the plugin git repos -- this work will happen over at https://github.com/pkp/pkp-lib/issues/4598.)
