### ISSUE TITLE
Native Export for articles with supp files broken in PHP7 in OJS 2.4.8

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#4955]
There appears to be a PHP7 compatibility issue with OJS 2.4.8-5 and the native import export plugin.  When exporting an issue that contains articles with supplementary files, the code attempts to build a supplementary file DOM and enters here:

https://github.com/pkp/ojs/blob/a8a2804e507fa3b350b924108201d4356e7ebc3d/plugins/importexport/native/NativeExportDom.inc.php#L425

Because the switch statement uses cases that depend on translated locale keys, the export fails with:

PHP Fatal error:  Uncaught Error: Using $this when not in object context in lib/pkp/classes/i18n/PKPLocale.inc.php:96

Running the export with a PHP5 binary works fine.

**Comment by jnugent** [comment]
Worth mentioning that this affects the PKP PLN plugin and the network, since the PLN plugin relies on the NativeImportExportPlugin to export issues before bundling them up and sending them to the PLN staging server.

**Comment by asmecher** [comment]
Fixed by fca4731. I left a `null` first parameter in the hook arguments so as not to accidentally reorder things.
