### ISSUE TITLE
For consideration: what is the purpose of the task list drop-down?

### ISSUE THREAD

**Issue by alex-wreschnig** [pkp/pkp-lib#4961]
Nobody in the UI/UX group at the 2019 Pittsburgh sprint was entirely sure what the use-case was for the task list. Nobody in the group felt it was particularly useful.

The criticism of the list as it currently exists was that it’s full of all sorts of notifications and only the occasional urgent task appears--but you really need to dig in order to find them.

This is not at all a priority from the UI/UX group; just an observation to help the team decide where to go with it or whether it's worth removing.

**From PKP Sprint Pittsburgh (2019/07): UI/UX group**
[UI/UX group notes from the Pittsburgh sprint](https://docs.google.com/document/d/1oWcsyHX2Ww5tHPpSN_-c2KaIhmAdaGYcZn3gFHjMEpc/edit?usp=sharing)

**Comment by asmecher** [comment]
@alex-wreschnig, the original purpose of the task list was to compliment the submission lists (which list content by submission) with another view that lists content by "need", i.e. a to-do list.

You've noted some user-facing problems with it, and I'll build on that by adding some dev-facing problems with it -- essentially it's complicated and too easy to introduce a wobble, and doesn't have good test coverage.

Essentially it's an area that needs a rewrite.

**Comment by asmecher** [comment]
@alex-wreschnig, do you think this issue and https://github.com/pkp/pkp-lib/issues/4958 can be combined, possibly into https://github.com/pkp/pkp-lib/issues/4962?

**Comment by alex-wreschnig** [comment]
> @alex-wreschnig, do you think this issue and #4958 can be combined, possibly into #4962?

I took a little liberty with creating this issue. It didn't seem like the task list is actively solving any problems--at least for any of the users I pinned down. And it's always nice to be able to remove a feature.

If there isn't a lot of value in keeping this around as a standalone issue, #4958 is attacking the same problem from a different angle and is probably the clearest fit. #4962 is meant to represent a larger project Nate keeps hinting at here and there, so is probably not a great fit for something as narrow as this thing is.

**Comment by NateWr** [comment]
Yeah, I do think the existing Tasks panel will become more useful when we implement #4962 throughout the workflow stage. In the meantime, I'm happy to leave it be because someone somewhere will be relying on it.

I'm going to close this for now because I think this tasks list will get handled appropriately as part of other issues. But thank you for filing all of these Alex. :+1:
