### ISSUE TITLE
Author could see blind reviewer names when they have a role as editor in the journal

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4964]
**Describe the bug**
During the UI/UX group in the Pittsburgh sprint, there was one person who was Author and Editor in a journal. From the author dashboard, she was able to view Blind Reviewer names when adding a new discussion.

**To Reproduce**
Has not been reproduced

**What application are you using?**
Not sure, but probably OJS 3.1.x.

**Additional information**
This needs to be confirmed and addressed if the issue still exists.

**Comment by asmecher** [comment]
Tested (using zwoods promoted to editor and manager in the test data set, phudson and amccrae as reviewers) and couldn't duplicate the issue. I suspect it's already been fixed.
