### ISSUE TITLE
[OJS] Upgrading plugins results in a 500 code

### ISSUE THREAD

**Issue by kallewesterling** [pkp/pkp-lib#4969]
Hello,

We need to upgrade some of the plugins in our Plugin Gallery in OJS installation, but every time we click "Upgrade," nothing happens. On reloading of the page, here's the error message displayed as "popup messages" in the admin interface:

<img width="215" alt="error-messages-1" src="https://user-images.githubusercontent.com/7298727/62320606-958da100-b46e-11e9-8afb-b03424cc0c55.png">

On further inspection, when clicking the "Upgrade" link, the jQuery request seems to generate a 500 error:

What could be causing this?

<img width="566" alt="error-messages-2" src="https://user-images.githubusercontent.com/7298727/62320624-9f170900-b46e-11e9-9f11-01ba526ce392.png">

**Comment by asmecher** [comment]
@kallewesterling, do you see anything relevant in your PHP error log? A `500` error should generally coincide with an error message there.

**Comment by kallewesterling** [comment]
Thank you for quick response. I cannot find any PHP error logs on our web hosting but I have contacted our support and will be back in touch soon.

**Comment by asmecher** [comment]
Closing for lack of follow-up -- we can re-open if you have more details, @kallewesterling.

**Comment by kallewesterling** [comment]
Unfortunately, no new comments from my support.

From the [screenshot above](https://user-images.githubusercontent.com/7298727/62320624-9f170900-b46e-11e9-9f11-01ba526ce392.png), however, it seems that there might be a problem with a deprecated `XMLHttpRequest`? 

Running a jQuery POST request "manually" on the same URL does _not_ generate a 500 error... Here's my console:

![image](https://user-images.githubusercontent.com/7298727/64205830-e9711880-ce66-11e9-83b9-c80bb56105cf.png)

**Comment by kallewesterling** [comment]
I will also make note here that this does NOT concern third-party plugins but @asmecher's `QuickSubmit` and `Backup`, for instance... Is there a way for me to upgrade them manually if this admin-interfaced oriented way does not work?

**Comment by asmecher** [comment]
@kaitlinnewson, there should definitely be something logged in the PHP error log, and without that this will be a lot tougher to debug... Were you able to find something there?

(The manually-executed `$.post` call as you've done it is missing the POST parameters; it is probably resulting in a `200` response that contains some kind of "access denied" message.)

**Comment by kallewesterling** [comment]
My provider does not give access to the PHP error log... it is so frustrating :/

**Comment by kallewesterling** [comment]
To me, judging from the [first picture I posted above](https://user-images.githubusercontent.com/7298727/62320606-958da100-b46e-11e9-8afb-b03424cc0c55.png), it looks as though the system does not provide a valid path to a `tar` binary. Would that generate a 500 error like this?

**Comment by asmecher** [comment]
@kallewesterling, you'll definitely need to configure the `tar` command in `config.inc.php` to get the Plugin Gallery working -- but off the top of my head I would expect a warning message, not a warning message *and* a 500 response. But yes, do try configuring `tar` and seeing if it improves things.

A service provider that doesn't provide PHP error log access is a very rare thing; I'm sure you'll find yourself in need of this again in the future, so it's worth doing what you can to see if you can gain access to this.

**Comment by kallewesterling** [comment]
Holy crap, it worked! I was able to finagle the error logs through the `.htaccess` file, and here we are - LOGS:

```
[03-Sep-2019 23:13:24 Europe/Stockholm] PHP Strict Standards:  Declaration of PKPUsageEventPlugin::getEnabled() should be compatible with LazyLoadPlugin::getEnabled($contextId = NULL) in /hsphere/local/home/lambda/lambdanordica.org/lib/pkp/plugins/generic/usageEvent/PKPUsageEventPlugin.inc.php on line 0
[03-Sep-2019 23:13:24 Europe/Stockholm] PHP Strict Standards:  Declaration of CustomBlockPlugin::getBlockContext() should be compatible with BlockPlugin::getBlockContext($contextId = NULL) in /hsphere/local/home/lambda/lambdanordica.org/plugins/generic/customBlockManager/CustomBlockPlugin.inc.php on line 0
[03-Sep-2019 23:13:24 Europe/Stockholm] PHP Strict Standards:  Declaration of CustomBlockPlugin::getEnabled() should be compatible with BlockPlugin::getEnabled($contextId = NULL) in /hsphere/local/home/lambda/lambdanordica.org/plugins/generic/customBlockManager/CustomBlockPlugin.inc.php on line 0
[03-Sep-2019 23:13:26 Europe/Stockholm] PHP Deprecated:  Non-static method VersionCheck::getValidPluginVersionInfo() should not be called statically, assuming $this from incompatible context in /hsphere/local/home/lambda/lambdanordica.org/lib/pkp/classes/plugins/PluginHelper.inc.php on line 196
[03-Sep-2019 23:13:26 Europe/Stockholm] PHP Fatal error:  Call to a member function getProductType() on string in /hsphere/local/home/lambda/lambdanordica.org/lib/pkp/classes/plugins/PluginHelper.inc.php on line 200
```

**Comment by asmecher** [comment]
@kallewesterling, that's getting closer -- but it still seems like OJS is unable to unpack the downloaded plugin, either because `tar` is not working or perhaps because of file permissions in the `plugins/importexport` directory not allowing PHP to upload a plugin there.

**Comment by kallewesterling** [comment]
Why would the `plugins/importexport` directory be implicated, you mean?

To me, it seems that this is the culprit, no?
> Call to a member function getProductType() on string

**Comment by kallewesterling** [comment]
I've been able to add a plugin that my client needs, finally: the `customHeader` plugin. I did it by uploading it the the `plugins/generic` directory. I can even enable the plugin.

However, then I select "Settings" under the dropbox:
<img width="344" alt="Screen Shot 2019-09-03 at 9 22 09 PM" src="https://user-images.githubusercontent.com/7298727/64218746-f7d42a00-ce90-11e9-80b6-bc81681d007f.png">

And the following happens:

![image](https://user-images.githubusercontent.com/7298727/64218781-12a69e80-ce91-11e9-99dc-a360f92dfc84.png)

> Failed Ajax request or invalid JSON returned.

**Comment by asmecher** [comment]
> Why would the plugins/importexport directory be implicated, you mean?
>
> To me, it seems that this is the culprit, no?
>
>> Call to a member function getProductType() on string

That message is a downstream effect of OJS being unable to load the version descriptor of the plugin you're trying to install. I don't recall off the top of my head, but OJS is either trying to load it from the directory it's unpacked into using the `tar` tool (suggesting a problem with the `tar` configuration if it can't do that) or from the directory it moves it into afterward (the `plugins/importexport` directory in the case of the quick submit plugin). So either of those causes could plausibly be behind the error message.

> I've been able to add a plugin that my client needs, finally: the customHeader plugin. I did it by uploading it the the plugins/generic directory. I can even enable the plugin.

I'd recommend working to debug the plugin gallery installation process before trying to install plugins manually. It's very easy to install the wrong plugin version for your OJS, and in many cases just placing the plugin in the right place will miss important installation steps.

**Comment by kallewesterling** [comment]
Thanks for the updates. I'm going to move along and try to get this whole thing going, based on your comments. I have multiple service requests in with the client's provider to see what's going on with the `tar` configuration. Something tells me that they won't be super helpful when it comes to that as well (they haven't been, as you've noticed, with the logs.)
