### ISSUE TITLE
Separate editorial, review and author assignments in submissions lists

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4975]
**Describe the problem you would like to solve**
Editors, authors and reviewers who have more than one role in the system struggle to identify which submissions they have to review, edit or follow-up on. This is especially difficult for editors who handle more than one role.

**Describe the solution you'd like**
Separate out editorial, review and author assignments into separate submissions lists.

**Who is asking for this feature?**
Editors who were also reviewers and authors.

**Additional information**
The UI/UX group at the Pittsburgh Sprint in 2019 suggested that these submissions should appear in separate lists.

The API endpoint for submissions has a lot of conditional logic to determine the user's currently assigned role. This is used, for example, to anonymize data about the submission for reviewers. Because the API endpoint returns editorial, review and author assignments, the logic has to sit deeply inside the submissions schema map and other places. Once there are separate API endpoints for editorial, review and author assignments, this logic can be removed, which will simplify the schema map and the API endpoints.

**Comment by NateWr** [comment]
During a review of other platforms, @israelcefrin noted that Janeway visually distinguishes between incomplete and complete submissions in the author dashboard. This is a distinction we should also make clear when we separate author assignments from editorial assignments.

![janeway-author-submissions](https://user-images.githubusercontent.com/2306629/120339111-bcc48c00-c2ec-11eb-9810-25159b154a11.png)

**Comment by NateWr** [comment]
The following mockups have been prepared as a suggestion for how these lists can be split up, and what the new author and reviewer lists should look like. Changes to the submissions list will be handled in a separate issue.

### Navigation Menu
When a user has more than one role, they will see a menu item for each list. They will only see the menu items appropriate for their role.

![lists-menu](https://user-images.githubusercontent.com/2306629/143890589-f8608090-e930-4a32-b62a-f861b72239b5.png)

- Submissions: any `ROLE_ID_MANAGER`, `ROLE_ID_SUB_EDITOR` or `ROLE_ID_ASSISTANT` role (eg - Journal Manager, Section/Series Editor, Moderator, Copyeditor, Layout Editor, etc.)
- Review Assignments: any `ROLE_ID_REVIEWER` role.
- My Submissions: any `ROLE_ID_AUTHOR` role (eg - Author, Translator)

### Author List
The My Submissions page shows the author a simplified list of submissions.
![lists-author](https://user-images.githubusercontent.com/2306629/143891077-19a599f7-f6c0-4f3a-816d-90367912ace2.png)

### Reviewer List
The Review Assignmentss page shows the reviewer a list with the appropriate information shown/hidden.
![lists-reviewer-active](https://user-images.githubusercontent.com/2306629/143891297-affdd6c7-641a-4997-b21c-33bfaadc5181.png)

Once a review assignment is completed, declined, or cancelled by the editor, it is moved to the reviewer's archived list.
![lists-reviewer-archive](https://user-images.githubusercontent.com/2306629/143891486-a88e3dc5-6535-4f41-8859-f60ef6f671e1.png)

**Comment by Devika008** [comment]
This has already been incorporated and worked on as a part of the New Submission Dashboard :D
