### ISSUE TITLE
Issue galleys have bullet points in default theme

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4978]
**Describe the bug**
When using an issue galley in OJS, the default theme shows the galleys in bullet points.

**To Reproduce**
1. Add an issue galley under Issues > Back Issues > (Edit an Issue) > Galleys.
2. The galleys will show using bullet points.

![IssueGalleys](https://user-images.githubusercontent.com/2306629/62692820-42b16d80-b9c9-11e9-8d6b-9d29109957d3.PNG)

**What application are you using?**
 OJS 3.1.2

**Additional information**
Probably, we just need to copy the `.galley_links` styles over to `issue_toc.less`: https://github.com/pkp/ojs/blob/master/plugins/themes/default/styles/objects/article_summary.less#L56-L68

**Comment by thinkbulecount2** [comment]
[Pull Request](https://github.com/pkp/ojs/pull/2443)

**Comment by NateWr** [comment]
Merged.
