### ISSUE TITLE
Request Revisions modal (and possibly others) broken if TinyMCE plugin is disabled

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#4981]
We had an issue reported by a hosted journal were reviews were not being added to the email body when revisions were requested, when the "add reviews" button was clicked.  The TinyMCE plugin was disabled in the journal, and with the plugin disabled clicking "add reviews to email" or also toggling the radio button choice for "Require New Review Round" generates the following error in console:
`
ReferenceError: tinyMCE is not defined`

And the message body is not updated. It appears that some workflow functionality is now dependent on the plugin being enabled.

Tested in OJS 3.1.2-1

**Comment by asmecher** [comment]
I prevented disabling of the TinyMCE plugin.
