### ISSUE TITLE
Typo in locale key "grid.action.deleteNotification" (or invalid LinkAction ID)

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#4982]
**Describe the bug**
There's a typo in the locale key "grid.action.deleteNotification", which should be  "grid.action.deleteNotifications".

**To Reproduce**
1. Raise a notification
2. Hover the mouse over the "Delete" link/button

**What application are you using?**
OJS: /master

**Additional information**
![image](https://user-images.githubusercontent.com/361921/62833836-a946bd80-bc4d-11e9-9a84-5b0c3d43d645.png)

**Comment by asmecher** [comment]
@jonasraoni, is there a PR open for this? Don't forget to drop the link into the issue when it's ready!

**Comment by asmecher** [comment]
Ah, I suppose it's this one: https://github.com/pkp/pkp-lib/pull/4983
Merged, thanks!
