### ISSUE TITLE
[OJS] Notifications/tasks popover being displayed unexpectedly

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#4984]
**Describe the bug**
The list of notifications is displayed unexpectedly after being opened and closed.

**To Reproduce**
1. Click on the `Tasks` link to display the notifications.
2. Click again to close it.
3. Click anywhere in the page and the notifications will be displayed again.

**What application are you using?**
 OJS: /master
Browser: Chrome

**Comment by asmecher** [comment]
This got merged -- thanks, @jonasraoni!
