### ISSUE TITLE
[OJS] Right clicking on an action of the notifications popover is executing it 

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#4985]
**Describe the bug**
Right clicking on Mark New/Mark Read/Delete executes the action.

**To Reproduce**
1. Click on the Tasks link
2. Right-click on any action of its footer.

**What application are you using?**
OJS: /master
Browser: Chrome

**Comment by asmecher** [comment]
Merged -- thanks, @jonasraoni! Cherry-picked back to `stable-3_1_2` as well.
