### ISSUE TITLE
variable {$submissionLayoutUrl} not replaced 

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#4988]
Hi,

I think submissionLayoutUrl should be submissionUrl in email templates ( id : LAYOUT_REQUEST )

https://github.com/pkp/ojs/blob/a02168b8feb358f5c3931490df8a30baab6eac20/locale/en_US/emailTemplates.xml#L532
(v3.2)
Thank you

**Comment by asmecher** [comment]
Thanks, @forgive38!
