### ISSUE TITLE
Call superclass when overriding methods in Form and DAO subclasses

### ISSUE THREAD

**Issue by gpieri** [pkp/pkp-lib#499]
Some methods are overridden in the subclass and their parents are not called.

Therefore, superclass functionality (such as firing hook events) are not performed.

I've found the following methods in OJS that do not call their superclass implementation:

- UserDAO::getAdditionalFieldNames
- RegistrationForm::execute
- ProfileForm::initData
- ProfileForm::execute
- SubscriptionForm::initData
- SubscriptionForm::execute
- CreateReviewerForm::execute
- UserManagementForm::initData
- UserManagementForm::execute
- LanguageSettingsForm::initData
- LanguageSettingsForm::execute
- MetadataForm::getLocaleFieldNames
- AuthorSubmitStep3Form::getLocaleFieldNames

**Comment by asmecher** [comment]
Thanks for contributing, @lepidus!
