### ISSUE TITLE
[OJS] Crossref plugin: simplify list displays to two lists: all issues; article status

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#500]
This would be under "Export Data" in the CrossRef plugin. Right now there's three options: 
- unregistered articles;
- all issues; 
- all articles. 

We propose to simplify these listings to two: 
- All issues (never hide issues from this list, regardless of registration; allow people to manually export on an issue or article-level basis from here; possibly also allow a "mark as exempt" option on an issue-level basis). 
- Article status (list all articles, and their associated status from Crossref; also allow users to update; or manually mark as registered).

**Comment by asmecher** [comment]
@AhemNason and @jmacgreg, suggestions for 2.4.7?

**Comment by jmacgreg** [comment]
I think this has since been resolved.
