### ISSUE TITLE
SSL Termination Support

### ISSUE THREAD

**Issue by alvinchevolleaux** [pkp/pkp-lib#5002]
**Describe the problem you would like to solve**
I'd like to use SSL termination on a load balancer in front of a server hosting OJS. Currently if you attempt to do this, OJS will detect that you're communicating with it via port 80 and not realise SSL termination is in use and will return all links as HTTP instead of HTTPS.

**Describe the solution you'd like**
If you were to add the HTTP_X_FORWARDED_SSL and / or HTTP_X_FORWARDED_PROTO in the routing mechanism that determines the $baseUrl, then the correct protocol will be returned in any links.

**Who is asking for this feature?**
This feature is for system administrators hosting OJS in an enterprise cloud environment.

**Comment by asmecher** [comment]
@alvinchevolleaux, what version of OJS are you using?

**Comment by alvinchevolleaux** [comment]
3.1.2

**Comment by alvinchevolleaux** [comment]
The baseUrl protocol seems to be ignored and is replaced with whatever protocol is being used to access the site otherwise this would also work.

**Comment by asmecher** [comment]
@alvinchevolleaux, the `base_url` directive (by itself, without a journal name) is only applied when OJS can't detect the URL based on server variables, e.g. in the case of a command-line invocation that kicks off scheduled tasks to do things like send emails. Have you tried the `base_url[...]` directives, one for each journal (with the journal path in place of the `...`), and an extra `base_url[index]` for the site-wide (portal) URL?

**Comment by alvinchevolleaux** [comment]
Sorry I didn't end up having time to test this in the end. Closing this issue now.
