### ISSUE TITLE
[OMP] Jquery missing 3_1_2-1

### ISSUE THREAD

**Issue by lucasdiedrich** [pkp/pkp-lib#5003]
Hello guys, i'm building an Docker environment using the [buildpkg script](https://github.com/pkp/omp/blob/master/tools/buildpkg.sh). The build run smoothly, the full log can[ be read here](https://paste.fedoraproject.org/paste/xqPwaNH7DH0rsQqHgEyegw). The problem is that when i enter install page Jquery is missing, can't be loaded. 

Any ideas why?

OMP Docker repo: https://github.com/lucasdiedrich/omp
Error:
![image](https://user-images.githubusercontent.com/817482/63175563-a3b8f100-c01a-11e9-85dc-73e0944c1c36.png)

Thanks.

**Comment by lucasdiedrich** [comment]
Actually i think the problem is that the [exclude list](https://github.com/pkp/omp/blob/6e88bef8d7a859910a32b177a3917e188abc2fa2/tools/buildpkg.sh#L62) is removing the js, why?

**Comment by lucasdiedrich** [comment]
Removing the above lines from **exclude**  fixed the problem.

![image](https://user-images.githubusercontent.com/817482/63180832-702f9400-c025-11e9-816e-9717b6e846bc.png)

**Comment by asmecher** [comment]
I've removed those exclusions -- thanks, @lucasdiedrich!
