### ISSUE TITLE
StageAssignmentDao _getByIds can return a factory by default, but default can't be overridden

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#5004]
We had a hosted client report a problem assigning a stage participant, and this was tracked down to a fatal error because of:
```

[Sat Aug 17 21:40:47.301623 2019] [cgi:error] [pid 25694:tid 47647052318464] [client 172.255.60.50:38801] AH01215: PHP Fatal error:  Uncaught Error: Call to undefined method DAOResultFactory::getId() in 
/var/home/journal/www/lib/pkp/controllers/grid/users/stageParticipant/form/AddParticipantForm.inc.php:155: 
```

The StageAssignmentDAO build function calls, in turn, getBySubmissionAndStageId, which in turn calls _getByIds() but it does not seem possible to pass in the $single attribute in order to only return one record, instead of a factory.

**Comment by asmecher** [comment]
@jnugent, can you describe the circumstances that lead to this bug? It's odd that this has only been reported one, if it's a fundamental issue like it seems to be. Also, what version of OJS is the client using?

**Comment by jnugent** [comment]
Hi @asmecher 

I had some time to dig into this a bit more.  This is on a 3.1.2-1 installation.  I'll walk backwards and you can tell me if this makes sense.  The short answer is that this is likely a data problem, but:

The AddParticipantForm calls:

$stageAssignment = $stageAssignmentDao->build($submission->getId(), $userGroupId, $userId, $recommendOnly);

On line 155. The assumption being made in the code there is that the DAO returns a stage assignment class, because a few lines further down ->getId() is called on it.  In our case, the call to build() was returning a factory, not an object.  This is because:

StageAssignmentDAO::build takes those four arguments and then calls getBySubmissionAndStageId internally.  This method takes those same four arguments and calls _getByIds() and passes in those same four arguments.  But _getByIds() can take 6 arguments, including an optional last one called $single.   That variable is used this way:

```
                if ($single) {
                        // all four parameters must be specified for a single record to be returned
                        if (!$submissionId && !$stageId && !$userGroupId && !$userId) return false;
                        // no matches were found.
                        if ($result->RecordCount() == 0) return false;
                        $returner = $this->_fromRow($result->GetRowAssoc(false));
                        $result->Close();
                        return $returner;
                } else {
                        // In any other case, return a list of all assignments
                        return new DAOResultFactory($result, $this, '_fromRow');
                }
```
If single is true, it pulls the top record off of the factory and returns it.  But it seems that it is possible for that method to build a query that potentially returns more than one row, and since there are no calls to that internal method in StageAssignmentDAO that ever pass in the optional single parameter (and it defaults to false), that if statement will never be true and  a factory is returned.  There's one case where that method gets five arguments, but never the 6th.

This seems to be what was happening in our client install, resulting in the fatal error. The three values eventually making it to the getBySubmissionAndStageId method are $submissionId, $userGroupId, and $userId, and the second parameter, stageId, is null.

This implies that in this installation a query limited to a submission, a user group, and a user id is returning more than one row.  This sounds like a data problem to me, so feel free to close if this seems like a data problem, and not a code problem, to you also.  It does seem a little weird that the if() statement in _getByIds is never true, though.

 Cheers, Jason

**Comment by asmecher** [comment]
@jnugent, yes, I think that is a data error -- there should be a unique index preventing that condition: https://github.com/pkp/pkp-lib/blob/stable-3_1_2/xml/schema/rolesAndUserGroups.xml#L172..L177

**Comment by jnugent** [comment]
@asmecher, Weird, because that index exists on the table.

**Comment by asmecher** [comment]
Is there any way you could try to duplicate this on a stock 3.1.2-1 installation?

**Comment by jnugent** [comment]
@asmecher I'm inclined to mark this as not a bug, because I've not seen it before or since on any hosted site, and this particular install has had some customizations, and has gone through numerous upgrades.  I still find it a little odd that there is no way to pass in anything to affect the $single variable in _getByIds() but that probably doesn't matter.

**Comment by asmecher** [comment]
OK, that sounds fine. Feel free to re-open of it resurfaces.
