### ISSUE TITLE
[ojs 3.1.2] OpenAIRE plugin bug

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#5006]
Hi,

in stable-3_1_2, after enable openAIRE plugin, projectId from a new submission isn't saved.
possibly link to #4612 

submission object is no more accessible for hook in :
https://github.com/pkp/pkp-lib/blob/cbff3a1d9bdcc3a8aefa7c4b43617489b99e9690/classes/submission/form/PKPSubmissionSubmitStep3Form.inc.php#L97

Thank you

**Comment by forgive38** [comment]
Hi,
PR #5036  for this issue
(I see how PKPSubmissionSubmitStep3Form.inc.php->execute is written to propose this solution)

**Comment by asmecher** [comment]
@forgive38, thanks -- merged to `stable-3_1_2` and cherry-picked foward to `master`. Is there a change in the OpenAIRE plugin required to make use of this change?

**Comment by forgive38** [comment]
@asmecher I test it and no change is required.

**Comment by asmecher** [comment]
Great -- thanks for contributing, @forgive38!
