### ISSUE TITLE
Reduce size of jquery-ui package

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5008]
jQuery UI allows us to get a package with just the elements we need: https://jqueryui.com/download/. Using this, we can get the package size down considerably.

I've attached files which include 1.12.1 that only supports:

- Autocomplete
- Datepicker
- Tabs

There a couple places in the codebase that call `.button()` but these should be removed.

The attached files need to be tested against our use of autocomplete (including the tag-it component, which relies on autocomplete), datepicker and tabs. If it works, use it to replace the existing files.

(Argh, Github won't allow me to attach the files. Anyway, they can be generated from the download link above.)

**Comment by kallewesterling** [comment]
Out of curiosity, what's the reason for using a 2014 version of jQuery?

**Comment by NateWr** [comment]
Hi @kallewesterling, currently, our `master` branch uses jQuery 3.3.1 and jQueryUI 1.12.1. It looks like there is a [newer version of jQuery](https://www.npmjs.com/package/jquery) we can upgrade to, but looking at [the changes](https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/) nothing pops out as necessary. As far as I'm aware 1.12.1 is the [most recent version of jQueryUI](https://www.npmjs.com/package/jquery-ui).

We are slowly refactoring away from jQuery towards our [UI Library](https://github.com/pkp/ui-library), which uses Vue.js, Babel and webpack. We'll still have jQuery around for a while (hopefully we can get jQueryUI out sooner), but absent critical security fixes, there's less incentive to update since new code is not making extensive use of it.

**Comment by kallewesterling** [comment]
Interesting! Thank you for the response :) I'm just diving a bit into development for academia and it's good to hear these things :)

**Comment by NateWr** [comment]
Closing this as outdated. It's our plan to remove the jQuery dependency completely. cc @jardakotesovec
