### ISSUE TITLE
[OJS] Crossref plugin: update information that is displayed in lists

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#501]
Nothing should ever be hidden. 

Article lists should have the following columns: 
- article ID
- title (truncated)
- issue
- authors (truncated)
- DOI 
- DOI external status (via Crossref API)
- DOI internal status (whether manually marked as registered or not)
- Actions: Mark as submitted; update; submit; export (manual XML) 
- Action (optional): clear/exempt DOIs in batch (this may not be the appropriate place for this)

Issue lists: 
- Issue title
- date published
- # of articles
- Actions: submit; mark as submitted; export (manual XML); mark as exempt/clear (optional)

**Comment by asmecher** [comment]
@AhemNason @jmacgreg whee

**Comment by jmacgreg** [comment]
Resolved or no longer relevant as of 2.4.8.
