### ISSUE TITLE
[OJS 3.1.2] some events are not logged

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#5010]
all events need to be recorded in order to sort submissions by date.
linked to : https://github.com/pkp/pkp-lib/issues/4168#issuecomment-523507825

- [ ] when a reviewer post a review, an event needs to be recorded (I don't think it's useful when an editor read or thank reviewer : maybe when the review is confirmed ?)

**Comment by forgive38** [comment]
I'm not sure to understand the utility of this code : 
https://github.com/pkp/pkp-lib/blob/cbff3a1d9bdcc3a8aefa7c4b43617489b99e9690/classes/submission/reviewer/ReviewerAction.inc.php#L72-L76

**Comment by forgive38** [comment]
see PRs
#5012 
pkp/ojs#2449

**Comment by asmecher** [comment]
> I'm not sure to understand the utility of this code...

That's dead code! Could you remove it as part of your pull request? Good spotting...

**Comment by NateWr** [comment]
Looks great @forgive38. I just had one requested change to move stuff from OJS into pkp-lib but otherwise this looks clean and easy to apply. :+1:

**Comment by NateWr** [comment]
Merged to `master` and `stable-3_1_2`.

**Comment by NateWr** [comment]
Oops, I should have test it out, but it did pass tests in the stable branch... :thinking:

**Comment by NateWr** [comment]
Uff, yeah, I didn't notice there was no submodule commit so it just ran against pkp-lib `master`.
