### ISSUE TITLE
w3 validator warnings

### ISSUE THREAD

**Issue by dennmuel** [pkp/pkp-lib#5014]
Hi everyone,

we ran our instance (ojs 3.1.2-1) through the w3 validator. The results can be seen [here](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmajournals.bib.uni-mannheim.de%2F). We are using a custom theme, so some of the warnings will be fixed somewhere else.

There are some warnings and errors, some of which seem to be minor and are addressed in #5013.
However, I'm not sure about the role attribute warnings. They are marked as unnecessary, so does that mean, that a `<header>` is automatically recognized as a `banner` by screenreaders and thus doesn't need to be marked as such? It feels kinda odd to remove it, though.

I'm not so sure, either, what can be done about the "Bad value en_US for attribute lang on element li: The language subtag en_us is not a valid language subtag." error. It seems to come from [here](https://github.com/pkp/ojs/blob/53808da03b46575ec1fa9adde2c7d99223c15f39/plugins/blocks/languageToggle/templates/block.tpl#L19). Is there a way to retrieve values compliant with [this list](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)?

Best regards
Dennis

**Comment by dennmuel** [comment]
@NateWr was so nice as to answer my questions in a related issue in the bootrap3 theme repo. The language attribute is now adressed in #5015. I'll update this issue and my mentioned PR accordingly.

**Comment by NateWr** [comment]
Oh, I didn't notice this issuee, @dennmuel! Yeah I think we've covered everything in the Bootstrap issue: https://github.com/NateWr/bootstrap3/issues/130. I'll close this in favor of that issue but do let me know if there's anything further that needs to be filed.

**Comment by dennmuel** [comment]
That's absolutely fine, thank you! I think that should be it, but I'll come back to it if I come across something else. :)
