### ISSUE TITLE
[OJS] Crossref plugin: improve documentation

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#502]
1) add mouse-over text explaining Crossref status statements ("found"; "complete"; "submitted"; maybe more). 
2) clarify "mark as registered" and the general "registered" terminology; probably change to "submitted". 
3) possibly clarify what OJS provides when receiving Crossref errors and other notifications (which are XML-based and not user-friendly). **This may not be the preferred solution - we will want to check with Crossref to see if they can actually return readable errors instead. 
4) Add configuration documentation currently in wiki into plugin.

**Comment by asmecher** [comment]
@jmacgreg etc

**Comment by jmacgreg** [comment]
Closing - documentation aplenty these days.
