### ISSUE TITLE
[OJS] Export of bibliographic data

### ISSUE THREAD

**Issue by felixgruender** [pkp/pkp-lib#503]
In order to cite an article in OJS, there is the "How to cite item" tool in "Article tools".
However, it would be good to provide the possibility export the metadata, and not only on article level, but also on issue or journal level (in formats such as MARC, BibTeX or RDF).
As this is part of our current project, we are going to implement this issue ourselves.

**Comment by bozana** [comment]
The motivation behind this is the movement to open the bibliographic data (open access bibliographic data).
S. for example http://openbiblio.net/principles/why/
Or how some institutes are providing them:
http://openmetadata.lib.harvard.edu/bibdata
http://datahub.io/de/dataset/cern-library-bibliographic-data

**Comment by asmecher** [comment]
Hi all -- I just mentioned this thought to Felix via email:

> Why not use the OAI interface directly? It has an XSL-based browser-friendly presentation and it would be easy to link directly to it in any of the OAI formats. You could drop a link there from somewhere in the reading tools and otherwise no changes would be needed.

**Comment by bozana** [comment]
Hmm... I am not sure about the OAI interface, because the most libraries provide the data for download, so a person can do something with them, they can be integrated into other systems,... For the OAI interface you need an OAI harvester, otherwise you cannot 'easily' download the data, right? Furthermore, I believe, the bibliographic data is slightly different than the data via OAI. Of course, I am not sure about all this -- this is above all a movement of the libraries and their catalog data... Maybe to ask somebody... ?

**Comment by asmecher** [comment]
Have you seen the front end to the OAI interface? It's point-and-clickable.

**Comment by bozana** [comment]
Hihihihi :-) -- No, I work only with the code, like a machine ;-) :-D
I am joking, yes I have seen it -- I hope I see the same things as you :-) But how could I, for example, download all the data from the journal FQS (http://www.qualitative-research.net/) in the MARCXML-Format using the OAI interface i.e. http://www.qualitative-research.net/index.php/fqs/oai?verb=ListRecords&metadataPrefix=marcxml ?

**Comment by asmecher** [comment]
You can't do that via the OAI interface. I was thinking more of its presentation of single article metadata; if you want to allow complete downloads, then it'll take some custom coding. You could re-use the same metadata format plugins that the OAI code uses to avoid duplication of effort... but IMO a full-journal metadata harvest is the kind of thing OAI was originally supposed to permit.

**Comment by bozana** [comment]
Yes, we will have to see... The other thing is, that you get the OAI-Format and not the pure MARCXML or RIS or BibTex, right?
But this is maybe minor thing... 
Hmmm... I will ask in a mailing list what is the main purpose and how to best provide the data, if the OAI interface is enough... OK?

**Comment by asmecher** [comment]
Sure, sounds good to me. I'd be interested to hear the requirements too.

**Comment by asmecher** [comment]
Thanks, @felixgruender, and sorry to be a pain about some of the structural aspects here.

I think the "best" way to solve this would be to gather together the various ways of formatting metadata into one area. Currently we have import/export formats, citation formats, and OAI metadata formats, and the formats you need to support span at least two of those categories. I worry about adding yet another for the sake of this metadata export task.

We've partially reconciled this already in the OJS 3.0 codebase (the master branch) using the filter framework, documented here: https://pkp.sfu.ca/wiki/index.php?title=Metadata_and_Filter_Framework

It's proably not reasonable for us to expect you to tackle this as part of your work, nor to wait for OJS 3.0 to base it off the filter framework, so I think the best compromise is probably to maintain this as a local modification and revisit it once we're ready to start adapting it to OJS 3.0.

Alternately, have you considered using the OAI interface as your data source? It already provides for extracting a journal's metadata via XML. It doesn't support BibTeX, but that would be a relatively small addition.

**Comment by felixgruender** [comment]
@asmecher, your concerns about the abundance of metadata plugins are comprehensible for me.
So I agree to your proposal to keep this new plugin as a local modification for now.

**Comment by asmecher** [comment]
Thanks, @felixgruender. Let's come back to this when OJS 3.0 is released and we can collaborate on moving this over to that release in an ideal way; much of the groundwork is already in place.

**Comment by felixgruender** [comment]
Agreed!

**Comment by bozana** [comment]
Hello,

Maybe just a general info about open bibliographic data that I've found out: in general, the OAI is enough for the smaller amount of data. For the huge amount of data, like this is the case in libraries, the download possibility of all the data should be provided. 
Thus, OJS does already support the concept via OAI pretty well. (It is maybe just to continuously take care about the metadata standards and their interoperability.)
However, there is also a need for a download possibility for the 'simple'/human user -- that's why the currently local modification of Felix... 

Best!

**Comment by asmecher** [comment]
That makes sense, @bozana. I think something conceptually close to the OAI interface would be the most maintainable way to do this -- have you seen e.g. the download tool at http://validator.oaipmh.com/ ?

**Comment by bozana** [comment]
@asmecher, thanks!!! I think this is a good solution. There is just a minor disadvantage -- one downloads the whole OAI-XML, so one will maybe first have to get rid of it in order to insert the data into his/her bibliographic database, but... :-)

**Comment by asmecher** [comment]
That's just an example; there must be other tools that do this with a bit better configurability. I think an XSL filter would quickly deal with the OAI-PMH wrapper if needed.
