### ISSUE TITLE
CitationStyleLanguage settings refer to obsolete/removed SelectListPanel

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5032]
In the `master` branch of OJS, the citationStyleLanguage plugin refers to the SelectListPanel, which was removed with https://patch-diff.githubusercontent.com/raw/pkp/pkp-lib/pull/4638.

**Comment by NateWr** [comment]
Fixed in https://github.com/pkp/citationStyleLanguage/commit/ad5a8e70fc59c29db6441629d789fb20c02a8fee
