### ISSUE TITLE
upgrade v.2.4.6 t 3.1.1 all supp files show as galley file for all users.

### ISSUE THREAD

**Issue by samarabbani** [pkp/pkp-lib#5037]
Hi everyone, i upgrade ojs 2.4.6 to 3.1.2-1, after updating, all suup file show as galley list file for all.
how to fix this problem after upgrading?
i remove codes that show supp file in galley_link.php file in my template. if this is a good solution or not? if not, how to fix this big problem?

**Comment by asmecher** [comment]
Hi @samarabbani -- see the discussion and links e.g. here: https://forum.pkp.sfu.ca/t/all-the-files-words-figures-letters-have-been-published-with-the-new-ojs-3-0-version/26533/1
