### ISSUE TITLE
Content alignment

### ISSUE THREAD

**Issue by vormia** [pkp/pkp-lib#504]
Just a reminder of the content alignment issue that emerged to the surface when browsing OJS pages after installing Right-to-Left languages, such as Arabic.
In these cases, css files need to be modified in multiple locations, but also must be returned to the original state if the user wished to get back to Left-to-Right language, English for instance.

My suggestion is adding a tag with every locale registered in "locales" file and us it to determine correct css files needed for that particular locale... or any other solution possible.

Content aligned Left-to-Right is quite NOT accepted in OJS pages with Arabic language because some paragraphs containing numbers or mixed languages are difficult to be read.

**Comment by asmecher** [comment]
@vormia, have you tried adding a locale-specific CSS file? In registry/locales.xml, you can add a "stylesheet=..." attribute to cause a CSS file to be included only when that locale is used.

**Comment by vormia** [comment]
Great, @asmecher . your suggestion is what I was looking for. I managed to duplicate the css file:
(../lib/pkp/styles/common.css), then edit some lines to get the desired Right-to-Left alignment.
After saving it with a new name, I added the "stylesheet=..." attribute in registry/locales.xml, but it's written at the header of (common.css) file: "DEPRECATED. DO not modify", nevertheless, it solved my problem.
One thing left, what if it's needed to customize more than one CSS file, for instance: text in notification balloons that appear when enabling a plugin, may also need to be realigned properly. I followed the script, and found its CSS dependencies, but to be honest, I couldn't manage to change alignment there... while font size, padding, position... etc. were easy to get changed.

Thanks again @asmecher for your support.

**Comment by asmecher** [comment]
Hi @vormia -- it should be necessary only to override the specific tyles that need some right-to-left hinting, rather than copying and modifying whole stylesheets. This stylesheet is applied late in the page rendering so it should be possible to use it to override the usual styles. If you're having trouble overriding something, look up CSS's "!important" flag.

**Comment by vormia** [comment]
Thanks @asmecher, things now got better. Arabic language pack fits well in the system for now.
