### ISSUE TITLE
Restore SubmissionFileDAO unit tests

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5040]
`SubmissionFileDAO::testSubmissionFileCrud()` is currently skipped because there are inconsistencies in the way that the DAOs are mocked. When pulling a file out of the database, it does not properly retrieve the `submissionLocale` or `name` properties of the submission file. For this reason, the comparison asserts do not work.

These tests need to be fixed and restored to ensure the versioning changes have not introduced a regression.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/omp/pull/703

**Comment by asmecher** [comment]
Just needed a Publication to go with the Submission.

**Comment by NateWr** [comment]
:tada:
