### ISSUE TITLE
Add Mailing Address, primary contact info to email signature

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5049]
**Describe the problem you would like to solve**

Email signatures automatically include the publisher name, hyperlinked with a URL for the journal; but the journal's mailing address and other organizational contact info as required by CASL isn't also automatically included. This can be added manually via Settings > Workflow > Emails, in the Signature field, but should be included automatically. It may also be worth indicating that this is legally required information. [See item 3 here](https://fightspam.gc.ca/eic/site/030.nsf/eng/00008.html): 

> **3. Remember that your message must include:**
> 
>     your business name and the name of anyone on whose behalf you’re sending the message
>     a current mailing address and either a phone number, email or website address
>     accurate contact information that will be valid for at least 60 days after you send the message
>     an unsubscribe mechanism in accordance with subsection 11(1) of CASL

**Describe the solution you'd like**

If the journal has a mailing address, this should be automatically added. Additionally, the primary contact email address should probably also be included. 

Optionally, there could also be some sort of indication on the **Email** configuration page that this information is required to conform to CASL legislation. 

**Who is asking for this feature?**

Folks who are concerned about Canada's Anti-Spam Legislation ([CASL](https://laws-lois.justice.gc.ca/eng/acts/E-1.6/page-3.html#docCont)).

**Comment by defstat** [comment]
@NateWr 

PRs
OJS: pkp/ojs#2497
pkp-lib: pkp/pkp-lib#5154

**Comment by NateWr** [comment]
This looks good @defstat. I'm wondering about this line:

```
<p><a href='mailto: {$contactEmail}''>{$contactName}</a></p>
```

That will mean under the address users will just see a linked name, like:

> 123 Anywhere St
> Vancouver, CA
> 
> [Nate Wright](#) 

What should this say to be clearer to the user? I just took a quick look at some of the bulk emails I've received recently and found they often include this in some way like this:

![Selection_136](https://user-images.githubusercontent.com/2306629/66920505-57d6f800-f01b-11e9-861f-e76ef09f60b3.png)

Maybe we should include some text like:

> 123 Anywhere St
> Vancouver, CA
> 
> Email us at [contact@email.com](#). 

On a separate note, @jmacgreg, can we have a broader conversation at some point about these disclaimers? I think a lot of the legal systems we have to accommodate will want this information. But it might make sense to think about what different legal disclaimers different jurisdictions may require. I don't want to get too far ahead of ourselves but I also don't want to just go too far down the road of doing whatever Canada says because that's where the project happens to be based.

**Comment by jmacgreg** [comment]
Hi @NateWr , yep, down for a broader conversation or review any time. I think at a minimum though the mailing address and primary contact email address should be included (if available), along with subscription management options. I feel like that should satisfy most/all jurisdictions.

**Comment by jmacgreg** [comment]
Hi @defstat, given that the sender name should already be in the email, I'd suggest just making sure that we display journal name, mailing address, and primary contact email - something like: 

```{if journal name}journal name{/if}
{if journal mailing address}journal mailing address{/if}
{if primary contact email}primary contact email{/if}```

Note that the important thing here is to display identification and contact info for the organization sending the info - ie. the journal - rather than the user.

**Comment by NateWr** [comment]
@defstat if I understand James correctly, the final syntax should look like this:

> Journal of Public Knowledge
> 123 Anywhere St
> Vancouver, CA
> [primarycontact@email.com](#)

**Comment by asmecher** [comment]
@defstat, this is not a priority for 3.3, but please don't forget this issue!

**Comment by defstat** [comment]
@asmecher 

**PRs**
ojs: pkp/ojs#3044
pkp-lib: #5154

I think that needs at least 2 more improvements:
1. a way to update already existing journals (as the emailSignature is a context settings field). Perhaps during upgrade, and only if the value is the same as the old default?
2. perhaps the locale could reside at the PKP-LIB locales (and not be app-specific)?

**Comment by asmecher** [comment]
Thanks, @defstat!

> 1. a way to update already existing journals (as the emailSignature is a context settings field). Perhaps during upgrade, and only if the value is the same as the old default?

No, I don't think we should change signatures when users have been working with them already. It's up to journal managers to be legally compliant in whatever region they're working (@jmacgreg's notes about CASL are helpful for motivating the changes but I'm against adding a link to the legislation when most of our community is non-Canadian). Changing the signature in any way for a working journal is likely to be an unpleasant surprise for someone.

> 2. perhaps the locale could reside at the PKP-LIB locales (and not be app-specific)?

Yes, the locale key should definitely move to the shared library -- but watch for other comments on this in my review!

**Comment by asmecher** [comment]
This one looks great, @defstat, please go ahead and merge!

**Comment by defstat** [comment]
Thank @asmecher - Merged

**Comment by asmecher** [comment]
Thanks, @defstat -- closing!
