### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [pkp/pkp-lib#5051]
There is no LICENSE or COPYING file for this project. The default is copyright.

The webpage says that the license for these projects is GPLv2 or later [here](https://pkp.sfu.ca/ojs/ojs_download/), [here](https://pkp.sfu.ca/gpl/), [here](https://pkp.sfu.ca/omp/omp_download/), [here](https://pkp.sfu.ca/ocs/ocs_download/), and [here](https://pkp.sfu.ca/ohs/ohs_download/).

Several files in this repository mention the license say that the license can be found in docs/COPYING, but there is no copying file.

    pkp-lib$ grep -Ri "gnu" . | wc -l
    2061

Directions on how to apply the license are at the bottom of the license file under the `How to Apply These Terms to Your New Programs` heading.  There is [a helpful guide for the GPL](https://www.gnu.org/licenses/gpl-howto.en.html).  If you would like me to submit a PR to make this easier, I would be happy to do that.

**Comment by asmecher** [comment]
Hi @TechnologyClassroom! This repository contains code that's shared by our applications (OJS and OMP) and the `docs/COPYING` that's referred to in the documentation can be found in those repos. When the packages are built, the contents of this repo appear in `lib/pkp`, so the reference to `docs/COPYING` is accurate.

However, I agree that this doesn't help users who come across the pkp-lib repo in its github context. A pull request would be welcome!

**Comment by TechnologyClassroom** [comment]
That makes sense.  I submitted a PR for a GPLv2 LICENSE file in the root directory.  That will help github browsers know which license the project is under.

**Comment by asmecher** [comment]
Thanks, @TechnologyClassroom!
