### ISSUE TITLE
Wrong mEDRA endpoint TEST web service on OJS mEDRA Export Plugin

### ISSUE THREAD

**Issue by njikonga-med** [pkp/pkp-lib#5057]
**Describe the bug**
The mEDRA endpoint of the web service test is worng, can I please replace it with the right one?
**To Reproduce**
1. Go to '@file plugins/importexport/medra/classes/MedraWebservice.inc.php'
2. Fine the line 22 with the following definition on the endpoint: 'define('MEDRA_WS_ENDPOINT_DEV', 'https://medra.dev.cineca.it/servlet/ws/medraWS');'
3. the correct endpoint is 'https://www-medra-dev.medra.org/servlet/ws/medraWS'

**What application are you using?**
 OJS the newer version

**Comment by asmecher** [comment]
Thanks, @njikonga-med, committed the change as suggested.

**Comment by njikonga-med** [comment]
Dear @asmecher , I have another question: how can i instruct the the mEDRA's plugin to set the endpoint test?. In the class @file plugins/importexport/medra/MedraExportPlugin.inc.php, there is a condition to be satisfy in the line 96, $endpoint = ($this->isTestMode($context) ? MEDRA_WS_ENDPOINT_DEV : MEDRA_WS_ENDPOINT); but i couldn't find the signature or method isTextMode($context), I need help please...

**Comment by asmecher** [comment]
@njikonga-med, `isTestMode` is implemented in the parent class (`classes/plugins/PubObjectsExportPlugin.inc.php`). It depends on an entry in the `journal_settings` table called `testMode`. (In the future, please try the forum https://forum.pkp.sfu.ca for general Q&A -- that'll help us build up the knowledge base there and keep this resource free for development. Thanks!)
