### ISSUE TITLE
OJS master branch: Saving publication data gives a warning in StageRolePolicy

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5060]
Saving publication data in OJS 3.2 master branch resultus into warning:
`PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in lib/pkp/classes/security/authorization/StageRolePolicy.inc.php on line 52`

**Comment by ajnyga** [comment]
Basically the ASSOC_TYPE_ACCESSIBLE_WORKFLOW_STAGES authorizedContextObject does not exist.

One solution is to edit the PublicationWritePolicy and add $this->addPolicy(new UserAccessibleWorkflowStageRequiredPolicy($request)) which will set the object above.

**Comment by ajnyga** [comment]
Like so:

```
<?php
/**
 * @file classes/security/authorization/PublicationWritePolicy.inc.php
 *
 * Copyright (c) 2014-2019 Simon Fraser University
 * Copyright (c) 2000-2019 John Willinsky
 * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
 *
 * @class PublicationWritePolicy
 * @ingroup security_authorization
 *
 * @brief Class to permit or deny write functions (add/edit) on a publication
 */

import('lib.pkp.classes.security.authorization.internal.ContextPolicy');
import('lib.pkp.classes.security.authorization.PublicationAccessPolicy');
import('lib.pkp.classes.security.authorization.internal.UserAccessibleWorkflowStageRequiredPolicy');
import('lib.pkp.classes.security.authorization.StageRolePolicy');

class PublicationWritePolicy extends ContextPolicy {
	/**
	 * Constructor
	 * @param $request PKPRequest
	 * @param $args array request arguments
	 * @param $roleAssignments array
	 */
	function __construct($request, &$args, $roleAssignments) {
		parent::__construct($request);

		// Can the user access this publication?
		$this->addPolicy(new PublicationAccessPolicy($request, $args, $roleAssignments));

		// Can the user access this stage?
		$this->addPolicy(new UserAccessibleWorkflowStageRequiredPolicy($request));

		// Is the user assigned to this submission in one of these roles, and does this role
		// have access to the _current_ stage of the submission?
		$this->addPolicy(new StageRolePolicy([ROLE_ID_MANAGER, ROLE_ID_SUB_EDITOR, ROLE_ID_ASSISTANT]));
	}
}

```

**Comment by ajnyga** [comment]
But not sure how this fits the policy setup in general.

Note that at the moment editing the line 		$this->addPolicy(new StageRolePolicy([ROLE_ID_MANAGER, ROLE_ID_SUB_EDITOR, ROLE_ID_ASSISTANT])); probably does not affect anything because of the warning here meaning that only editors can edit the publication metadata and save. At least I think so, did not test yet.

**Comment by NateWr** [comment]
It looks like the PHP Notice was addressed in this commit: https://github.com/pkp/pkp-lib/commit/c43e52b9df0c0b688fcb8a33aa4a565580424b43#diff-d7e98838a52e1a8ec6892e843a29b2df.

The `PublicationWritePolicy` does not include the `UserAccessibleWorkflowStageRequiredPolicy`. However, the only place it is used is in the API where it is applied alongside the `SubmissionAccessPolicy`. That policy applies `UserAccessibleWorkflowStageRequiredPolicy` to authors, assistants and subeditors, so the array should be there for other .

These kinds of dependencies between policies are hard to manage, but I don't see a way around it for now. I'm going to close this as resolved for now.
