### ISSUE TITLE
XHTML files reported as text/xml on upload

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#5063]
This probably isn't a bug so much as it is a general problem with journals uploading XHTML content. The galley display plugins depend on the mime type being correctly set to text/html in order to render the file, and if the mime detection code reports text/xml instead then a) the HTML galley plugin isn't used, and b) the XML galley plugin fails to render anything.  Ideally journals would no longer use XHTML but in some cases there is a back catalogue of XHTML files or a lack of technical resources to edit them or convert the documents.

**Comment by asmecher** [comment]
Thanks, @jnugent -- merged and cherry-picked back to `stable-3_1_2`.
