### ISSUE TITLE
[OMP]

### ISSUE THREAD

**Issue by gingermink** [pkp/pkp-lib#5073]
Smithsonian Institution Scholarly Press has had its OMP-based "Open SI" instance hosted by PKP since 2013. (We are still on the old platform due to plans to migrate to another provider.) We are now moved to another platform and require the export of all our portal's data. James MacGregor provided this on August 23, 2019: 

"[W]e can provide you with a full backup of your system. This comes in three parts: the OMP system backup; the submission files directory; and the system database (MySQL). We can provide this to you at any time - just send an inquiry to the support team through the usual channels, and they can package it up and send it on."

Please provide this data package by September 30, 2019. Thank you.

Ginger Minkiewicz
Director, Smithsonian Scholarly Press  
MinkiewiczG@si.edu

**Comment by asmecher** [comment]
Hi Ginger -- this is the issue tracker for our open source software, which is separate from the hosting operation. However, I'll mention this to the hosting team.
