### ISSUE TITLE
Copyedit/Layout files from OJS 2 have wrong URL text after OJS 3 upgrade

### ISSUE THREAD

**Issue by njn315** [pkp/pkp-lib#5078]
**Describe the bug**
In OJS 2, there are three copyedit files, Initial Copyedit, Author/Creator Copyedit, and Final Copyedit and a Layout Version file. After upgrading to OJS 3, these files have the wrong URL text but the URL link points to the correct file. There are screenshots showing this in this forum post, https://forum.pkp.sfu.ca/t/ojs-3-1-2-1-copyedit-files-from-ojs-2-dont-appear-in-ojs-3/55617/3.

I'd expect the URL text to represent the actual file name of the URL link.

**To Reproduce**
1. In OJS 2, the Copyedit files are in the Editing > Copyediting section for a submission. The Layout Version file is in the Editing > Layout section for a submission.
2. Upgrade from OJS 2.4.8.0 to OJS 3.1.2.1
3. In OJS 3, the Copyedit files are located in the Copyediting > Copyediting Discussions > Copyediting. The Layout file is located in Production > Production Discussions > Layout Editing.
4. The files in OJS 3 look wrong because they have the wrong URL text but it appears the actual files did transfer over.

**What application are you using?**
 OJS 3.1.2.1

**Additional information**
https://forum.pkp.sfu.ca/t/ojs-3-1-2-1-copyedit-files-from-ojs-2-dont-appear-in-ojs-3/55617

**Comment by asmecher** [comment]
@njn315, I suspect you're seeing the difference between OJS 2.x's presentation of its own server-side filenames, versus OJS 3.x's presentation of the file name as it existed on the uploading user's system. For example you see a file called `320-2822-2-CE watson review.docx`; this has doubtlessly been downloaded from OJS, renamed to add the `watson review` part of the filename, then re-uploaded into OJS. When it was uploaded to OJS 2.x again, it would've received a new server-side filename (e.g. `320-2823-1-CE.docx`) even though the filename on the uploader's system would have had a different ID (`320-2822-2-CE watson review.docx`).

**Comment by njn315** [comment]
Ah, OK. I think I understand now. So that is expected behavior in OJS 3 and not a bug. Closing.
