### ISSUE TITLE
Upgrade from 3.1.1.4 to 3.1.2-1 Error: Blank page

### ISSUE THREAD

**Issue by kallewesterling** [pkp/pkp-lib#5081]
I am now trying to update the OJS version to the most recent stable release but when I upgrade, I end up with a blank page. The PHP error log says:

> [23-Sep-2019 16:40:11 Europe/Stockholm] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/lambdanordica.org/public_html/cache/t_compile/e8ea13aa559bf8604ca823015b397a28d8666486^28682bb3d6b6e750ebd3d458abc8f92b4da9ea9f_0.app.headerusernav.tpl.php on line 136
> [23-Sep-2019 16:40:12 Europe/Stockholm] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/lambdanordica.org/public_html/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php:456
> Stack trace:
> #0 /var/www/lambdanordica.org/public_html/lib/pkp/lib/adodb/adodb.inc.php(558): ADODB_mysql->_connect('mysql61.unoeuro...', 'lambdanordica_o...', 'xxxxxxxx', 'lambdanordica_o...')
> #1 /var/www/lambdanordica.org/public_html/lib/pkp/classes/db/DBConnection.inc.php(151): ADOConnection->Connect('mysql61.unoeuro...', 'lambdanordica_o...', 'xxxxxxxx', 'lambdanordica_o...', false)
> #2 /var/www/lambdanordica.org/public_html/lib/pkp/classes/db/DBConnection.inc.php(126): DBConnection->connect()
> #3 /var/www/lambdanordica.org/public_html/lib/pkp/classes/db/DBConnection.inc.php(83): DBConnection->initConn()
> #4 /var/www/lambdanordica.org/public_html/lib/pkp/classes/db/DBConnection.inc.php(52): DBConnection->initDefaultDBConnection()
> #5 /var/www/lambdanordica.org/public_html/lib/pkp/classes/db/DBConnection.inc.php(227): DBConnection->__construct()
> #6 /var/www/lambd in /var/www/lambdanordica.org/public_html/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php on line 456

The PHP version on the server where I'm trying to install the system is 7.3.9.

**Comment by kallewesterling** [comment]
Looks like the mysql driver has been discontinued in php7: https://github.com/ADOdb/ADOdb/issues/310

**Comment by kallewesterling** [comment]
#1118 had the solution for me.

**Comment by suprayogi20** [comment]
open config.inc.php on your ojs 
and 
change script
[database]
driver = mysql
to
[database]
driver = mysqli
