### ISSUE TITLE
[OJS] public galley ID validation

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#509]
The validation of the public galley ID in the ArticleGalleyForm is wrong -- it checks if there is a galley with the same public galley ID, but doesn't check if that galley is the currently edited galley -- thus, there is always the error ("The public identifier 'pdf' already exists for another galley of this article. Please choose an unique galley identifier within this article.") when editing a galley.
The pull request is coming... :-)

**Comment by asmecher** [comment]
Also cherry-picked to master, thanks!

**Comment by bozana** [comment]
When the public galley id is missing, then there is:
WARNING: assert(): Assertion failed\n  In file: classes/article/ArticleGalleyDAO.inc.php\n  At line: 140
The pull request is coming...

**Comment by asmecher** [comment]
Thanks, looks good to me!
