### ISSUE TITLE
Remove XML-based locale file fallback

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5090]
OJS 3.x will/should introduce the use of PO files for locale contents, along with a fallback on older-style XML files as a fallback.

Starting with OJS/OMP 3.3, remove the fallback and just use PO files.

Compatibility code will be in LocaleFile::load and Plugin::getLocaleFilename.

**Comment by NateWr** [comment]
@asmecher do you still plan to remove this for 3.3 or should I defer it for 3.4?

**Comment by asmecher** [comment]
I'll take care of it, thanks!

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/6358
- https://github.com/pkp/ojs/pull/2911 (tests only)

**Comment by asmecher** [comment]
Merged!
