### ISSUE TITLE
NOTIFICATION email key missing on upgrade of OJS 2 to OJS 3.1.2

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5094]
**Describe the bug**
NOTIFICATION email key is missing on OJS3.1.2.0 and it results in empty notification emails, i.e.: for new submission to editors, announcements to users.

**To Reproduce**
Upgrade OJS2.4x directly to OJS 3.1.2.0
1. Go to 'Dasboard > Settings > Workflow > Emails tab'
2. Scroll down to 'Prepared Email Templates'
4.  Set 100 'tens per page'
5. Search for NOTIFICATION: you will realized that **Notification Mailist** , which has been removed from locale file oj OJS is kept, but **Notification** doesn't exist

**What application are you using?**
 OJS 3.1.2-1

**Additional information**
See below the screenshot showing the first **Notification** email template added manually.
![image](https://user-images.githubusercontent.com/4992902/65614534-2de76400-df8e-11e9-86bc-d1359a559e97.png)

**Comment by asmecher** [comment]
@israelcefrin, what specific version of OJS 2.x was this upgraded from?

**Comment by israelcefrin** [comment]
@asmecher it was an OJS 2.4.8.2 to 3.1.2.0

**Comment by asmecher** [comment]
@israelcefrin, `NOTIFICATION` should exist in OJS 2.4.8 (and in fact all the way back to 2.3.0); maybe it was missing from that database as well?

**Comment by israelcefrin** [comment]
@asmecher the editors realized that empty emails started being delivered only after upgrade (and it was missing the `Submission Ack` also). Does OJS2 use different templates for these notifications distinct than `NOTIFICATION `and `SUBMISSION_ACK`?

**Comment by asmecher** [comment]
@israelcefrin, OJS 2.x and 3.x should behave the same in both regards, i.e. that a missing `NOTIFICATION` email template will result in empty emails. Both OJS 2.4.x and 3.x make pretty heavy use of that template. I have two hypotheses...
1. The `NOTIFICATION` template was actually present in OJS 2.x but somehow got removed during the upgrade process (unlikely, but easy to check if you have a dump from 2.x)
2. The editors are using the system with a different mix of languages in 3.x than they did in 2.x, and `NOTIFICATION` is missing from one or more secondary languages

**Comment by israelcefrin** [comment]
Hi @asmecher , it was most likely the second option. Thanks for the clarification.
