### ISSUE TITLE
Embed announcement content into notification message body

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5096]
**Describe the problem you would like to solve**
I would like to embed the announcement content into notification email message body. Currently, this notification has only a link to the website announcement detail page. On that note, embed the announcement lead into email subject also.

**Describe the solution you'd like**
A check-box saying for "include content in the email body" on announcement editing modal/form.  And a specific template for this notification to customize even with journal logo. The current template is used by "new submission" message to editors. 

**Who is asking for this feature?**
Journal editor would like to send the content along the link for the website.

**Additional information**
It is a request that has came as a side effect from an issue of empty email messages:  https://github.com/pkp/pkp-lib/issues/5094

This issue is the same request from here: 
https://github.com/pkp/pkp-lib/issues/4746

**Comment by asmecher** [comment]
This is a duplicate of issue #4746, no? Why not just add to that issue rather than opening another?

**Comment by israelcefrin** [comment]
I was not sure whether I should file an issue using the new template, but I can close this one and paste the same content there. Does it sound ok?

**Comment by asmecher** [comment]
Please do, thanks!
