### ISSUE TITLE
OMP "Download all files" not working

### ISSUE THREAD

**Issue by straderg** [pkp/pkp-lib#510]
I've tried to bulk download for a new submission in IE, Firefox, and Chrome. All resulting .zip files have been invalid and will not open. The project link is http://opensi.si.edu/index.php/smithsonian/workflow/submission/107. There are ~30 files in the submission, so I'd like to avoid downloading individual files if possible.

**Comment by asmecher** [comment]
@straderg, this appears to be a problem with the version of PHP we're running on that server; I'm looking into it and will report back.

**Comment by asmecher** [comment]
Hi @straderg -- we've got some server-side tinkering to do and will report back in a few days. Thanks for being patient.
