### ISSUE TITLE
Remove sexist language

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5103]
See https://forum.pkp.sfu.ca/t/removing-sexist-language/56014:
> Can the default email notification message that comes with the software be revised to ensure all pronouns are gender neutral? For example, for an editor decline template email, it has the text, “This email is send to the author if the editor declines his submission initially, before the review stage.” I would vote in favour of using “their submission.” Thanks!

**Comment by alexxxmendonca** [comment]
👍

**Comment by asmecher** [comment]
Fixed. Fortunately this doesn't appear in the default email text -- it's in the description presented to the journal manager in the "Prepared Emails" area.
