### ISSUE TITLE
Deprecated error messages  V 2.4.8.5

### ISSUE THREAD

**Issue by radjr2** [pkp/pkp-lib#5112]
Hello, we are getting the following errors on a V2.4.8.5 installation running php 7.2.2.0. We have turned off error messages with changes to /usr/local/lib/php.ini and error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT but we still get the messages. Is this controlled somewhere else and IS this a problem moving forward. It was mentioned that 2.4.8.5 was tweaked for php 7 so I really do not know what to check next. Thanks.

: Deprecated: Non-static method PKPApplication::defineExposedConstant() should not be called statically in /home/radjr1/domains/wmpllc.org/public_html/ojs/lib/pkp/classes/core/PKPApplication.inc.php on line 545

Deprecated: Non-static method PKPApplication::getExposedConstants() should not be called statically in /home/radjr1/domains/wmpllc.org/public_html/ojs/lib/pkp/classes/core/PKPApplication.inc.php on line 513

**Comment by asmecher** [comment]
Hi @radjr2 -- please just stick to one venue; you'll reach the same people either way. There's a response to your latest forum post already at https://forum.pkp.sfu.ca/t/deprecation-error-messages/56079.
