### ISSUE TITLE
journals with no custom base_url ignored if at least one journal in an install has one when stats are processed

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#5121]
We have a hosted installation running 3.1.2-1 that has 15 or so journals.  14 of these journals have no custom base_url entry and just use the general base_url for the installation.  On June 25, however, the 15th journal was added to the installation and it has a custom base_url.   Since that date, it is the only journal in the installation getting records added to the metrics table. All other log entries in the usage stats logs get flagged with:

    The line number {line number} from the file {file path} contains an url that the system can't remove the base url from.

It appears that there is an either/or situation because the call to Core::removeBaseUrl($url) in UsageStatsLoader calls _getBaseUrlAndPath which does:

```
                // Check for override base url settings.
                $contextBaseUrls = Config::getContextBaseUrls();
```

and if that's not empty, it only iterates over the customized base_urls, ignoring the general ones.

The workaround for this journal was to make sure that all journals had a custom base_url entry, even if it just duplicated the general base_url, and then to reprocess the stats logs.  At that point all journals received metrics entries.

**Comment by jnugent** [comment]
Also, perhaps this is intentional in the stats framework, but I don't see it mentioned in the documentation.

**Comment by ajnyga** [comment]
We encoutered this very early with OJS3: https://forum.pkp.sfu.ca/t/usage-stats-warnings-system-cant-remove-the-base-url/28553

Basically if one journal has a custom base_url, then _every_ journal needs to have a custom base_url even if that base_url is the default url of the journal. Otherwise you end up loosing stats.

**Comment by asmecher** [comment]
@ajnyga, since you've run into this before, could you give https://github.com/pkp/pkp-lib/pull/6461 a look? Thanks!

**Comment by ajnyga** [comment]
looks safe to me. $baseUrl = Config::getVar('general', 'base_url'); is also used if no context base_url's are set in config, so falling back to that should work in all cases I can think of.

**Comment by asmecher** [comment]
Thanks, @jnugent and @ajnyga -- merged!
