### ISSUE TITLE
Issue published notification email should include issue table of contents

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#5125]
**Describe the problem you would like to solve**
Some editors coming from OJS 2 expect the issue published notification email to include the issue TOC within the body of the email sent to users.

**Describe the solution you'd like**
Allow editors to selectively include the TOC in issue notification emails or include it by default.

**Who is asking for this feature?**
Editors

**Additional information**
n/a

**Comment by asmecher** [comment]
This is already filed at https://github.com/pkp/pkp-lib/issues/3646 (that template is already worded to include the table of contents).

**Comment by mfelczak** [comment]
Thanks @asmecher!
