### ISSUE TITLE
Permit promotion of files into publication formats.

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#513]
Files will sometimes be promoted directly from submission stages into publication formats (e.g. supplementary content, which will stay in its raw form, e.g. CSV)

**Comment by asmecher** [comment]
Pulls: https://github.com/pkp/pkp-lib/pull/514
https://github.com/pkp/omp/pull/125

**Comment by asmecher** [comment]
Bruno, I've cleaned up all the issues you flagged -- thanks. Is it ready to port to OJS and merge?

**Comment by beghelli** [comment]
Alec, did last few comments related to the authorization... Sorry, I missed some points there, but it's an easy fix. After that feel free to go ahead. Thanks.

**Comment by asmecher** [comment]
Thanks, @beghelli!

**Comment by asmecher** [comment]
Merged.
