### ISSUE TITLE
Upgrade fails when database server has GTID enabled

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#5133]
The scripts that migrate the database when upgrading causes the upgrade to fail when the server has GTID enabled (due to replication needs). GTID enabled servers block queries containing statements like the ones currently used (CREATE ... SELECT). See: https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-restrictions.html

I'm performing an upgrade from 2.4.8.4 to the latest version OJS 3.1.2.1.

This issue has also been posted on : https://forum.pkp.sfu.ca/t/error-upgrade-failed-db-statement-violates-gtid-consistency/56158

One of the problematic files is: `dbscripts/xml/upgrade/3.1.0_preupdate_review_assignments.xml` that contains the following query:
`CREATE TABLE review_assignments_tmp AS (SELECT review_id FROM review_assignments WHERE cancelled = 1)
`

**Comment by asmecher** [comment]
@luizbgomide, we don't use statements like this in the normal operation of OJS, but as you've noted we sometimes do use these formulations during the upgrade process. I'm not sure there will be an easy alternative. Is it possible to disable replication during the upgrade process?

**Comment by luizbgomide** [comment]
>  Is it possible to disable replication during the upgrade process?

Unfortunately not, the server where I have a database is one of the main servers in the university, and it has some mirrroring/replication/etc running all the time.

One alternative that was mentioned to me, was the creation of a new temporary server where I could upload the old database, perform the migration and the dump it and upload to the correct server. Not ideal but it could work and solve my problem.

Since this might impact other users that might not be able to have another server running, I think it would be a good idea to break the statements in such way that it doesn't use a CREATE ... SELECT sintax.

**Comment by asmecher** [comment]
`SELECT ... CREATE` is a pretty big piece of the upgrade toolset to remove (and standard SQL to boot) -- I'm pretty sure even if we were to remove that query that the way ADODB implements schema changes would similarly fail. Do you have a suggestion for an alternative approach?

**Comment by luizbgomide** [comment]
I don't know much SQL besides basic queries, so I'm not of much help here.

I can workaround my problem with the in-house temp server.

I don't know how prevalent is the GTID setting. If that is something that is used in all servers with replication/mirroring I can see that as being a problem for a lot of users and I would still consider it a bug.

**Comment by asmecher** [comment]
@luizbgomide, I'm going to declare this a WONTFIX -- for OJS 3.3 we'll be removing the OJS 2.x to 3.x upgrade scripts entirely. I'll be working towards replacing our current upgrade structure with a Laravel (migrations/schema builder) toolset. For existing users who encounter this, they can work around it by performing the upgrade outside the replicated environment.

**Comment by vasmedv** [comment]
After Upgrading FreeBSD to 12.2, Mysql to 8.0.25, Php to 7.4.21, i managed to upgrade ojs from 3.1.1.4 to 3.3.0.7.
And the problem with GTID which was with Mysql 5.7  is disappeared.

**Comment by asmecher** [comment]
:+1: Thanks for the follow-up, @vasmedv!
