### ISSUE TITLE
OJS 3.1.2 OAI datestamp is always the current date

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5135]
**Describe the bug**
The OAI record datestamp should show the date when the item was last edited. However, at the moment it seems that the field is always populated with the current datestamp ie. the datestamp of the request.

The datestamp is used to check if the details of the item have changed. This means that the system now sends out a signal that all items change all the time.

**To Reproduce**
1. Go to OAI and see the datestamp of an item

**What application are you using?**
 OJS 3.1.2

**Comment by NateWr** [comment]
If you can add to the reproduction steps how to "Go to OAI" and what field to look in to find the date stamp, I'll confirm it and add it to the stable milestone.

**Comment by ajnyga** [comment]
For example: https://journal.fi/index/oai?verb=ListRecords&metadataPrefix=oai_openaire_jats&set=afs

See the OAI Record Header

**Comment by ajnyga** [comment]
For the correct use of that field see https://www.openarchives.org/OAI/openarchivesprotocol.html#header

**Comment by ajnyga** [comment]
I mean maybe this is not working as expected (surprisingly difficult to track down where the current stamp is set) https://github.com/pkp/pkp-lib/blob/756bb61da00a7fb51313e762b8db1c4d736c7da0/classes/oai/PKPOAIDAO.inc.php#L242

**Comment by ajnyga** [comment]
Ok, so seems that $row['last_modified'] is not set for some records and if that value is empty the function there will return the current stamp. Not sure yet what is missing or different with those entries that do not return $row['last_modified']

**Comment by ajnyga** [comment]
Ok, so @NateWr if the last_modified field is NULL in the issue table, then this seems to return null as well: https://github.com/pkp/ojs/blob/master/classes/oai/ojs/OAIDAO.inc.php#L225

And that results to a situation where datestamp is set to the current date.

I tested and confirmed this. Not sure in what situations issues do not have a last_modified value?

**Comment by ajnyga** [comment]
So unless you have an idea how last_modified could end up being null for published issues, then this was just a local issue. We have a lot of old content and I do not know the details how some of the content has been added to the service over the years. Feel free to close this if you think the same.

**Comment by NateWr** [comment]
:man_shrugging: Not sure myself. I'll close for now.
