### ISSUE TITLE
Description of Paperbuzz Plugin in Plugin Gallery talks about Hypothes.is plugin

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#5137]
In the OJS Testdrive install, when you click on the Paperbuzz Plugin in the Plugin Gallery, the description is about the Hypothes.is plugin

**Comment by asmecher** [comment]
Did you search for the plugin before clicking on it, or find it in the full list?

**Comment by jalperin** [comment]
searched

**Comment by asmecher** [comment]
That's a duplicate of https://github.com/pkp/pkp-lib/issues/4636.

**Comment by jalperin** [comment]
ack! Sorry, I should have searched.
