### ISSUE TITLE
[OJS] plugin metadata dc11 : maybe a typo

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#5138]
Hi,

https://github.com/pkp/ojs/blob/25200e002d6843d548b3e697ed4f0029f97b9222/plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.inc.php#L225

Hookregistry or HookRegistry,

Thanks

**Comment by asmecher** [comment]
Fixed capitalization -- thanks, @forgive38!
