### ISSUE TITLE
Google results showing private Supplementary Files

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#5140]
I just found out that Google is indexing private supplementary files with address like: `/article/downloadSuppFile/`. I'm using OJS 2.4.8.3, the supplementary files are not available even to reviewers and I could find the link for it anywhere on  the site.

Where is that link showing in the article? How can I stop that?

**Comment by luizbgomide** [comment]
I just found out one place that is showing this information, the OAI interface for the article lists every galley and supplementary file within a <dc:relation> element.

**Comment by asmecher** [comment]
@luizbgomide, the supplementary files in OJS 2.x *are* available for download, they're just tough to find (you can see them listed in the Reading Tools on the OJS 2.x sidebar). OJS 3.x just exposes them more visibly.

**Comment by luizbgomide** [comment]
Is that always the case? Many of our journals have supplementary files that are not meant to be public, and many require the authors to supply additonal information or even documentation throught the supplementary files.

If that is meant to be public (althouth nowhere it says so explicitly), how can we require those files privately?

**Comment by asmecher** [comment]
@luizbgomide, in OJS 3.x there's now a "submission library" area which is intended for things like contracts that are not part of the submission. In addition, you can upload a set of files throughout the workflow (rather than a single submission file). Those are options that OJS 2.x didn't have.

**Comment by luizbgomide** [comment]
Great, this will solve our problems, but now I have another question. When I migrate to OJS 3.x how can make the supplementary files become "workflow files" or even part of the submission library, and NOT become public supplementary files?

If this is not possible, how can I delete every supplementary files from every submission already published or archived? Because I would rather lose all the files, than have them easily visible.

**Comment by asmecher** [comment]
@luizbgomide, see this discussion: https://github.com/pkp/pkp-lib/issues/3016#issuecomment-346047020
