### ISSUE TITLE
Update for fr_CA translation 3.1.2-1

### ISSUE THREAD

**Issue by mhvezina** [pkp/pkp-lib#5145]
Hi @jmacgreg , @asmecher 

As promised : New PRs for updated fr_CA translation.

pkp-lib: https://github.com/pkp/pkp-lib/pull/5143
ojs: https://github.com/pkp/ojs/pull/2494 

I have reviewed every files from locale/fr_CA/  and lib/pkp/locale/fr_CA/

I haven't done any of the plugins files however.

**Comment by kaitlinnewson** [comment]
Closing as both PRs were reviewed/merged.
