### ISSUE TITLE
Missing hook call for submissionfilesuploadform::execute

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#5146]
**Describe the bug**
`SubmissionFilesUploadForm::execute()` never calls its parent, so it can never be called from a plugin hook.
https://github.com/pkp/pkp-lib/blob/d0d3534fecfdedbf1c4a1dabf46d6bd840d317e7/controllers/wizard/fileUpload/form/SubmissionFilesUploadForm.inc.php#L125-L182

**To Reproduce**
1. Add a hook for `submissionfilesuploadform::execute` into a plugin
2. Break on the supplied function
3. Upload a submission file
4. Never enter the function

**What application are you using?**
 OJS 3.1.2

**Additional information**
For this hook to be truly useful, the caller needs to be able to inspect and manipulate the submission file which was created within the `execute()` method, so we need to expose that with an accesssor.

**Comment by asmecher** [comment]
Thanks, @ctgraham! Committed and forward-ported to `master`.
