### ISSUE TITLE
Reduce the number of options to choose from under notifications

### ISSUE THREAD

**Issue by neffe** [pkp/pkp-lib#5150]
Is it in any way possible to reduce the number of options to choose from given to the registered **readers** when they go to Notifications under their profile. For instance I would like to remove the possibility of choosing the Submission Events. 

Make it possible for the editors to enable / disable any kind of mail sent by the system. As it is now, in the regular upload and release function, there are some messages that are optional, while others are sent by itself, unless the individual user (not the editor) has deleted the check mark exactly the right place during their own registration.

Below you see the **default settings**. Hope it will be changes in the near future:

![image](https://user-images.githubusercontent.com/10085388/66742457-f591c200-ee77-11e9-9405-c2b802b9b2ab.png)

**Comment by NateWr** [comment]
Closed in favor of https://github.com/pkp/pkp-lib/issues/6133.
