### ISSUE TITLE
OJS/master: creating new versions and publishing not working as expected

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5160]
**Describe the bug**
In latest master branch, publishing and creating new errors causes some javascript related errors where the workflow screen is not updated as expected. Most likely a problem in the workflowcontainer.vue

**To Reproduce**
1. As journal editor or site admin or any other role capable of publishing go the publication tab 
2. Click on Publish: error message "You are not authorized to access the requested resource." appears and the create a new version button does not become visible. It will become visible if you manually refresh the page.
3. Click on "Createa new version" button. The publication tab will get stuck while trying to reload. Refreshing the whole page shows that a new version has been created.

Submission stage does not seem to affect this.

**What application are you using?**
 OJS master branch

**Comment by ajnyga** [comment]
The "you are not authorized" message comes after publishing and is the result of a call to:
api/v1/issues/undefined?_=1571316691702

Note that the issueId is missing in the API call. So thinking that the issueId is not passed here: https://github.com/pkp/ui-library/blob/master/src/components/Container/WorkflowContainerOJS.vue#L21

**Comment by NateWr** [comment]
This _may_ be part of the little bugs here: https://github.com/pkp/pkp-lib/issues/5122#issuecomment-544904796. I'll try to reproduce after that gets merged.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ui-library/pull/46

Tests:
https://github.com/pkp/ojs/pull/2514
