### ISSUE TITLE
GatewayHandler generates fatal error because of missing method

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#5163]
In 3.1.2 stable, this commit was added:

https://github.com/pkp/ojs/commit/8d28a1827a41288eeaf203f8996c0113a7022e60#diff-9fd5ed2f28ec6a055543015216690140

Which calls getPolicies() on the gateway plugins, but the WebFeedGatewayPlugin does not have such a method.   This results in the following error:

PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method WebFeedGatewayPlugin::getPolicies() in pages/gateway/GatewayHandler.inc.php:38

**Comment by asmecher** [comment]
It looks like the `getPolicies` default implementation in `GatewayPlugin` wasn't added. @quoideneuf, mind taking a look at this?

**Comment by quoideneuf** [comment]
Sorry about that - this should take care of it:

https://github.com/pkp/pkp-lib/pull/4677
