### ISSUE TITLE
Request for a development of a new plugin as the mEDRA one

### ISSUE THREAD

**Issue by njikonga-med** [pkp/pkp-lib#5172]
**Describe the problem you would like to solve**
mEDRA Registration agency needs a new plugin for another DOI registration agency (OP DOI RA). 
**Describe the solution you'd like**
What is the correct procedure for that? We have to do (develop) it on our own (by downloading the OJS CMS, make a clone of the existing one, modifying it to suit the request for the new DOI registration agency, and publish it), or we have to make a request to you in order to develop the new plug-in on your own and release it?

**Who is asking for this feature?**
mEDRA Registration agency for another registration agency (OP DOI Registration Agency)

**Comment by asmecher** [comment]
Hi @njikonga-med! We prefer to have third parties develop and maintain plugins for OJS as much as possible -- we can add them to the Plugin Gallery inside OJS in order for OJS users to discover and install them. These plugins are typically managed in their own github repositories (see e.g. https://github.com/asmecher/customHeader).

If you've got more questions, I'd suggest moving the conversation over to the support forum (https://forum.pkp.sfu.ca).
