### ISSUE TITLE
Fix use of <h1> in header

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5175]
Currently, on the homepage, about page and login page, the journal logo is wrapped in a `<h1>` tag.

```html
<div class="pkp_site_name_wrapper">
	<h1 class="pkp_site_name">
		<a href="https://uiux.publicknowledgeproject.org/ojs/index.php/index" class="is_img">
			<img src="https://uiux.publicknowledgeproject.org/ojs/public/journals/1/pageHeaderLogoImage_en_US.png"
				alt="Journal of Public Knowledge Logo" width="9033" height="2563">
		</a>
	</h1>
</div>
```

Our accessibility audit said that we can not use the alt text as a `<h1>`, so we need to separate this from the `<h1>` tag and hide the `<h1>` tag for everyone except screen readers. Something like this:

```
<div class="pkp_site_name_wrapper">
	<a class="pkp_site_name" href="https://uiux.publicknowledgeproject.org/ojs/index.php/index" class="is_img">
		<img src="https://uiux.publicknowledgeproject.org/ojs/public/journals/1/pageHeaderLogoImage_en_US.png"
		alt="Journal of Public Knowledge Logo" width="9033" height="2563">
	</a>
	<h1 class="pkpScreenReader">Journal of Public Knowledge</h1>
</div>
```

Also, the `<h1>` should not be attached to the header on the about or login pages. The `<h1>` should be attached to a title on the main page area.

- [x] Move `<h1>` away from logo on homepage.
- [x] Remove `<h1>` from header on about and login pages and make sure a `<h1>` exists above the main content on those pages.

**Comment by thinkbulecount2** [comment]
Hi @NateWr,

Regarding this part:
[ ] Remove <h1> from header on about and login pages and make sure a <h1> exists above the main content on those pages.

Are we talking about moving the <h1>s in `about.tpl` and `userLogin.tpl` (e.g.:
`	<h1>
		{translate key="user.login"}
	</h1>
`
?

**Comment by NateWr** [comment]
In `header.tpl`, we use a `<h1>`: https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/header.tpl#L41-L45

This is appearing on some pages other than the homepage. But it should only be used on the homepage itself. I think you'll need to check `$requestedPage` instead of `$requestedOp`.

**Comment by thinkbulecount2** [comment]
I've moved it down after `<div class="pkp_site_name">`

Like this:
https://github.com/pkp/pkp-lib/commit/dec77397714fa1739730a5104e001788622ca5ba#diff-3453ca2bb365a2ddfe92fbffa6cb44bc

**Comment by NateWr** [comment]
Yeah that looks good. You can remove the outdated comment here:

https://github.com/pkp/pkp-lib/blob/dec77397714fa1739730a5104e001788622ca5ba/templates/frontend/components/header.tpl#L42-L43

**Comment by thinkbulecount2** [comment]
PR: https://github.com/pkp/pkp-lib/pull/5343
cc: @NateWr

**Comment by israelcefrin** [comment]
`H1` has been moved away from the logo, and it has been recognized using keyboard and screenreader software.  I'd just recommend to move the `H1` tag before the journal logo tag.
Internally the H1 has been correctly removed from the logo as well.

**Comment by NateWr** [comment]
:+1: @thinkbulecount2 can you take care of that when you get a chance?

**Comment by thinkbulecount2** [comment]
PR: https://github.com/pkp/pkp-lib/pull/5765

cc: @NateWr

**Comment by NateWr** [comment]
Merged!
