### ISSUE TITLE
Issue archive pages should add headings to issue titles

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5177]
On the issue archives page, each issue identification (both the title and the identifier like volume/number/year) should be wrapped in a `<h2>` tag.

Here is some fake code demonstrating what it should look like:

```
<div class="issue">
  <h2>
    <span>Inagural Issue</span>
    <span>Vol 1, No 1 (2019)</span>
  </h2>
  ...
</div>
```

**Comment by thinkbulecount2** [comment]
Is this what you meant @NateWr:
https://github.com/pkp/ojs/compare/master...thinkbulecount2:i5175_fix_h1_header?expand=1#diff-37f53c218e39b9c6c437efaa5ef649f7

**Comment by NateWr** [comment]
Yep! We will probably need to add a class and some styles to that `<h2>` to remove any extra margins and font sizing it is adding to the issue title.

**Comment by thinkbulecount2** [comment]
@NateWr Removed extra margins and set font size to 18px `@font-lead`

**Comment by thinkbulecount2** [comment]
PR: https://github.com/pkp/pkp-lib/pull/5343
https://github.com/pkp/ojs/pull/2547
cc: @NateWr

**Comment by israelcefrin** [comment]
@NateWr  all issue titles with H2 tag. No code change required to this one.

One side note, I think we should consider to add the Issue title to Cover image when JM enables both (title and Cover image). Assuming that the cover image is just a link to the issue, it makes sense to announce where that cover image is pointing to. If no ALT text is provided we can use it as fallback.

Currently, if no ALT text is provided then only a number is announced if a user skims the page link by link.
Maybe a new issue only to this improvement? Let me know what you think.

**Comment by NateWr** [comment]
Ok, so the `default` should be "View {$issue->getLocalizedTitle()|escape}"?

**Comment by israelcefrin** [comment]
Yes, exactly.

**Comment by thinkbulecount2** [comment]
@NateWr: How do I use string literals (to add the "View $issue->LocalizedTitle" in this case?

https://github.com/pkp/ojs/compare/master...thinkbulecount2:i5177_headings_issue?expand=1#diff-6e97ba30b7e9b915cf13d0729bacc6c0R33

**Comment by NateWr** [comment]
I think you'll need to capture some output and assign it to a variable. In Smarty that works like this:

```html
{capture assign="defaultAltText"}
  {translate key="my.locale.key" title=$issue->getLocalizedTitle()|escape}
{/capture}
<img ... alt="{$issue->getLocalizedCoverImageAltText()|escape|default:$defaultAltText"}
```

**Comment by thinkbulecount2** [comment]
PR:
[OJS](https://github.com/pkp/ojs/pull/2719)
[pkp-lib](https://github.com/pkp/pkp-lib/pull/5779)

cc: @NateWr

**Comment by NateWr** [comment]
Looks good @thinkbulecount2, but since this is related to an issue, the locale key needs to be in OJS, not pkp-lib. I think you can move that key to `locales/en_US/locale.po` in OJS and get rid of the pkp-lib PR.

**Comment by thinkbulecount2** [comment]
Hi @NateWr, made the change to OJS, but changed it from `issue.title` to `issue.localTitle` because the former already exists and don't wanna break anything. :)

**Comment by NateWr** [comment]
Sorry to nitpick, but can you change it to `issue.viewIssue`?

**Comment by thinkbulecount2** [comment]
Sure!

**Comment by thinkbulecount2** [comment]
Done @NateWr

**Comment by NateWr** [comment]
Merged! :tada:

**Comment by asmecher** [comment]
This was merged into `master` only, right? Please don't forget to designate issues against milestones!
