### ISSUE TITLE
Add headings to article titles when they are listed in table of contents and search results

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5178]
When an article summary appears in an issue's table of contents or in search results, the article title should be given an `<h*>` tag.

```
<article>
  <h2><a href="...">This is the article title</a></h2>
  ...
</article>
```

This presents a tricky problem for how we display cover images within an article summary:

```
<article>
  <img src="...">
  <h2>...</h2>
  ...
</article>
```

In such cases, the image will no longer be contained _under_ the article heading, so it will be improperly nested. We will probably need to change the HTML so that the cover image comes after the title, and figure out a new CSS layout solution for article summaries with cover images.

**Comment by thinkbulecount2** [comment]
PR: https://github.com/pkp/ojs/pull/2692

cc: @NateWr

**Comment by thinkbulecount2** [comment]
PR for OMP: https://github.com/pkp/omp/pull/795

cc: @NateWr

**Comment by thinkbulecount2** [comment]
Bumping this because I've made changes, cc: @NateWr

**Comment by NateWr** [comment]
Thanks, just took a look. Almost there just a couple more things. Can you apply this to OPS as well?

**Comment by thinkbulecount2** [comment]
[PR for OPS](https://github.com/pkp/ops/pull/23)

cc @NateWr

**Comment by thinkbulecount2** [comment]
Just put a [link](https://github.com/pkp/ops/pull/23) to the OPS PR in the original issue

**Comment by NateWr** [comment]
All PRs ready for merge once the tests pass:
https://github.com/pkp/ojs/pull/2751
https://github.com/pkp/ops/pull/23
https://github.com/pkp/omp/pull/795
