### ISSUE TITLE
Address alt text / link location confusion in the OJS/OMP branding image on themes

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5180]
At the bottom of our default theme (and our own core themes) there is an image:

![Selection_138](https://user-images.githubusercontent.com/2306629/67103110-758f9300-f1bc-11e9-94aa-8316f7cc1912.png)

This links to a page on the OJS system about the publishing workflow.

Our accessibility audit pointed out that the alt text on the image does not describe the image, because it is describing the text. The auditor suggested a more complete alt text like:

> More information about the publishing system, Platform and Workflow by OJS/PKP.

We can implement that now, but we should consider an alternative approach that separates the image from the link, so that valid alt text can be placed on the image and the link has text that will describe where it goes.

Also, we should consider whether the "About this publishing system" page should be deprecated, and instead we should consider where on our own `pkp.sfu.ca` website (or docs hub) such a link should point towards.

**Comment by NateWr** [comment]
@thinkbulecount2 for now, just focus on updating the alt text as described above. The image/link separation will have to wait.

**Comment by thinkbulecount2** [comment]
[Pull Request](https://github.com/pkp/ojs/pull/2648) (just for alt text portion)
cc: @NateWr

**Comment by NateWr** [comment]
All good here. :+1: Can you do this for OMP as well?

**Comment by thinkbulecount2** [comment]
OMP Pull Request: https://github.com/pkp/omp/pull/774
cc: @NateWr

**Comment by NateWr** [comment]
Merged!

**Comment by israelcefrin** [comment]
Reviewed with VoiceOver. Nothing to add, it's all fine.
