### ISSUE TITLE
Advanced search form has fieldset, legend and label errors

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5182]
The advanced search form has several errors with its fieldset, legend and label HTML markup. Details are available in the accessibility audit document and I will expand on this issue with further recommendations at a later date.

**Comment by NateWr** [comment]
We also need to remove the italics on the labels in the advanced form. These should have no italics.

**Comment by NateWr** [comment]
The main input field should not use a placeholder and the label should be visible.

**Comment by thinkbulecount2** [comment]
Hi @NateWr, is our current to-do list for this one:

- [ ] fieldset, legend and label HTML markup errors in advanced form
- [ ] remove italics on labels in advanced form
- [ ] remove placeholder in main input field
- [ ] main input field label should be visible

**Comment by NateWr** [comment]
Yes, I think so. Let's hold off on this for now, though. Once the In Progress tasks are done on the Accessibility project I'd like to shift you on to some Vue.js work.

**Comment by NateWr** [comment]
Fixed as part of work in https://github.com/pkp/pkp-lib/issues/5187
