### ISSUE TITLE
Add aria-required to register and login forms

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5186]
Wherever the `required` attribute exists on a field in the registration and login forms, the `aria-required="true"` attribute should also be included:

```
<input type="email" name="email" required aria-required="true">
```

**Comment by thinkbulecount2** [comment]
[Pull Request](https://github.com/pkp/pkp-lib/pull/5557/files)
cc: @NateWr 

Hope I got them all!

**Comment by thinkbulecount2** [comment]
Submodule update PR for OJS: https://github.com/pkp/ojs/pull/2650
cc: @NateWr

**Comment by NateWr** [comment]
Merged!

**Comment by israelcefrin** [comment]
Code reviewed and aria-required="true" element is set to all mandatory fields. Testing with a screenreader it announces that the input field is Required.

@NateWr and @thinkbulecount2 , testing the whole form the element "*" is announced as "star" while reading the Label for each mandatory field. For example: "Given name _star_ required" when focused on the _Given Name_ label. 

I'd suggest to add the the _aria-hidden=true_ to prevent to announce star for every mandatory field, e.g.:
`<span class="required" aria-hidden="true">*</span>`.

**Comment by thinkbulecount2** [comment]
Updated! PR: https://github.com/pkp/pkp-lib/pull/5766

cc: @NateWr

**Comment by NateWr** [comment]
Merged!
