### ISSUE TITLE
Restore checklist icon in submission requirements on small screens

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5191]
On small screens, the submission checklist icon is hidden from view. Our accessibility audit suggested that these should still be present. We should also do a little work to ensure that the checklist isn't too narrow on small screens (320px).

**Comment by NateWr** [comment]
The submissions page shows the checkmarks on a large screen.

![Selection_218](https://user-images.githubusercontent.com/2306629/74958398-c92b1b00-5400-11ea-9640-7f5e83511806.png)

But hides them on a small screen.

![Selection_219](https://user-images.githubusercontent.com/2306629/74958416-cf20fc00-5400-11ea-8089-fe2d1cbda0b9.png)

The CSS needs to be adjusted to so that the checkboxes always appear and the lies around the checklist could be removed on small screens so that the checklist goes closer to the edge of the screen.

**Comment by thinkbulecount2** [comment]
[Pull Request](https://github.com/pkp/ojs/pull/2647)
cc: @NateWr

**Comment by NateWr** [comment]
@thinkbulecount2 I think we're ready for merge on this one. Did you ever create a pull request for OMP?

**Comment by thinkbulecount2** [comment]
[OMP PR](https://github.com/pkp/omp/pull/791)

cc: @NateWr

**Comment by NateWr** [comment]
Merged

**Comment by israelcefrin** [comment]
@NateWr and @thinkbulecount2 it is visually correct, however when you use this CSS chunk:
```
 li:before {
content: "\f00c";
}

```
VoiceOver announces twice or 3 times the same element on Unordered List before to move to the next while you interact the page with keyboard. Despite the fact it is  annoying, it seems that the list has more itens that it really has.
Also, using list-style:none is causing the ScreenReader can't count and announce the total of elements of list. I've tested with VoiceOver only, I will check whether my windows laptop has Jaws enabled to test it as well. 

Maybe it is a issue of Mac, however, Apple is well known for accessibility features and many screenreader users rely on their technology to navigate.

**Comment by NateWr** [comment]
Ok, so I think we'll need to adjust this to an actual element in the `<li>` with `aria-hidden`. Like this:

```html
<li>
  <span class="fa fa-check" aria-hidden="true"></span>
  ...
</li>
```

> Also, using list-style:none is causing the ScreenReader can't count and announce the total of elements of list. I've tested with VoiceOver only, I will check whether my windows laptop has Jaws enabled to test it as well.

Can you say a little bit more about this? Are you sure it's `list-style: none` that is causing the issue? Use of this CSS property/value is extremely common and I've never heard of this before. It seems to contradict advice to use lists as semantic elements even when you don't want to style them with bullet points.

**Comment by israelcefrin** [comment]
@NateWr it seems that voiceOver can manage `list-style: none`. However, the` li:before ` is still active.
I've made a test using your suggestion:
```
<li>
  <span class="fa fa-check" aria-hidden="true"></span>
  ...
</li>
```
It works perfectly, announcing the total of list items and jumping correctly one by one as you press the VoiceOver and arrow keys.
I think that doing this adjustment is good enough to accomplish it.

**Comment by NateWr** [comment]
Thanks, moving this back into in progress. @thinkbulecount2 in addition to adding the `<span>` that Israel mentions above, you'll need to find and remove the CSS styles that use the `:before` attribute on these lists to add the icons.

(Side-note: that's used in a lot of places in the default theme to add icons, unfortunately. I don't think it's a high priority but good to document for later that this is a bad practice.)

**Comment by thinkbulecount2** [comment]
PRs:
[pkp-lib](https://github.com/pkp/pkp-lib/pull/5834)
[ojs](https://github.com/pkp/ojs/pull/2736)
[omp](https://github.com/pkp/omp/pull/808)
[ops](https://github.com/pkp/ops/pull/20)

cc: @NateWr

**Comment by NateWr** [comment]
Great! I love that were you were able to do it with such surgical changes to the code. :+1: All merged.
