### ISSUE TITLE
Skip to main nav link broken in default theme

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5202]
In the default theme, the skip to main navigation link (`#pkp_content_nav`) does not lead to anything. An anchor needs to be added to the main navigation menu.

**Comment by thinkbulecount2** [comment]
This is already fixed in master.

**Comment by israelcefrin** [comment]
Just reviewing and confirming that it is all fine. I've realized that the  `#pkp_content_nav` has changed to `#siteNav `though.
