### ISSUE TITLE
Removing editorial role from user should clean stage assignments and section settings

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5207]
**Describe the bug**
Removing an editorial role from a user does not affect the old stage assignments.

**To Reproduce**
1. Create a user and add for example section editor role
2. In section settings, select the user as the section editor
3. In submission workflow, assign the user as section editor
4. Remove the section editor from the user
5. The user is still listed in the section settings as a section editor and can see the submission where she was assigned to listed in submissions listing.

**What application are you using?**
 OJS 3.1.2

**Suggested fix**

Removing an editorial role should clean the stage assignments corresponding the removed role and for section editors, should also clean the assignments in section settings.

**Comment by asmecher** [comment]
Hmm, I'm ambivalent about this change. If a user is removed from a role by accident (or without knowledge of the impact it'll have on existing submissions), then the removal of assignments from all submissions will be a hard-to-reverse change. I can see two viable alternatives...
- Wherever the stage assignment is used, add a join to the `user_user_groups` table (etc) to ensure that there is a live user group and not just a submission stage assignment. That would make a removal from a user group effective, but permit the restoration of the previous state if e.g. it was an accident or temporary change.
- Continue with the current behaviour, i.e. past submission assignments are not affected by a journal-level removal of the user group assignment. However, we could prompt the user when removing the user group whether they also want to remove existing assignments.

**Comment by alexxxmendonca** [comment]
> Continue with the current behaviour, i.e. past submission assignments are not affected by a journal-level removal of the user group assignment. However, we could prompt the user when removing the user group whether they also want to remove existing assignments.

I like this approach. Giving the option to remove or retain existing assignments would be the best scenario but if that's too complicated to achieve, a simple confirmation such as "this action will remove any current section editor assignments this user might have, are you sure you want to proceed" or something along these lines.

**Comment by ajnyga** [comment]
I did not actually test what happens with the section settings when you remove a section editor role. I mean you keep seeing the removed section editor listed as the corresponding editor in the sections listing. When you open a section to edit it, the name is not there. You can remove the name from the listing by saving the section's settings.

The question there is that if the already removed section editor is left in the section settings, does she keep getting automatic stage assigments for that section?

**Comment by dihagan** [comment]
> Giving the option to remove or retain existing assignments would be the best scenario
While we're at it: an option to reassign all that person's current assignments to another section editor.

**Comment by NateWr** [comment]
I'm closing this in favor of #5396. I've copied some of the key points of discussion over to that issue. Please subscribe to that issue if you want updates.
