### ISSUE TITLE
Publisher Library: Deleted Files Should Also be Deleted on the Webserver

### ISSUE THREAD

**Issue by TobiasWantzen** [pkp/pkp-lib#5212]
**OJS 3.1.2-1** (and before)

**Description**
When I delete a file inside OJS backend in
```Settings > Workflow Settings > Publisher Library```
it physically stays on the webserver in
```/files/context/[journal-id]/library```

**Expected behaviour**
When a file is deleted in the OJS backend, it should also be physically deleted on the webserver.

Thanks, Tobias

**Comment by Tyl13** [comment]
I think this has been fixed. From testing on the current branch of stable-3_3_0. This is my results:
![image](https://user-images.githubusercontent.com/48526589/161621917-a805bce6-9854-43cd-9493-2224d83d2d13.png)
![image](https://user-images.githubusercontent.com/48526589/161621925-014d7100-d03d-47ef-9a7a-773aaa360794.png)
![image](https://user-images.githubusercontent.com/48526589/161621937-6f0cc65b-abac-44b5-9e74-5caf407b4bb9.png)
Then after deleting on ojs:
![image](https://user-images.githubusercontent.com/48526589/161621975-47e054d8-cf2a-45f5-9f00-018ce5602ff5.png)

**Comment by asmecher** [comment]
(Assigning to the next build -- I'll close this as "already fixed" if I don't hear anything to the contrary by then. Thanks for checking, @Tyl13!)
