### ISSUE TITLE
References added during submission are not stored with the publication

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5219]
**Describe the bug**
if I provide references as an author during submission, the references field in the post-submission manuscript area is blank. In fact, I don't see any references recorded in the citations table at all for that particular submission.

**To Reproduce**
1. Make a submission with references
2. Go to the submission workflow, click on Publication > References.
3. The references entered during submission do not appear here.

**What application are you using?**
OJS 3.2 (pre-release)

**Comment by NateWr** [comment]
Fixed in 9140daf. Thanks @jmacgreg!

**Comment by jmacgreg** [comment]
No problem Nate - did you want me to test and confirm all is good?

**Comment by NateWr** [comment]
I think it's ok but if you've got time always good to have a second look.
