### ISSUE TITLE
[OJS] Link to current issue does not redirect to public id

### ISSUE THREAD

**Issue by alonsoj** [pkp/pkp-lib#522]
From archives page the current issue link redirects to public id but from navbar links to not friendly url.

Changing pages/issue/IssueHandler.inc.php
`$request->redirect(null, 'issue', 'view', array($issue->getId(), "showToc"), $request->getQueryArray())`
to
`$request->redirect(null, 'issue', 'view', array($issue->getBestIssueId(), "showToc"), $request->getQueryArray());`
solves the problem.

Regards

**Comment by asmecher** [comment]
Thanks, @alonsoj; see the attached patch. This change needed to be made in a couple of places -- and a journal variable specified in order to improve performance slightly.
