### ISSUE TITLE
Updated fr_CA translation

### ISSUE THREAD

**Issue by mhvezina** [pkp/pkp-lib#5225]
New PRs for updated fr_CA translation.

`master` branch:

pkp-lib: #5223
ojs: https://github.com/pkp/ojs/pull/2517 

`stable-3_1_2` branch:

pkp-lib: #5224

(Note that, a couple of fixes, when relevant, were made to both branches. Hence there is no need to foward-port those changes from stable-3_1_2 (`*.xml` files) to the master branch (`*.po` files))

**Comment by asmecher** [comment]
All merged, thanks; and thanks for forward-porting the changes; it makes life a lot easier over here!
