### ISSUE TITLE
[OJS] Editor Decision Decline fails in Spanish language

### ISSUE THREAD

**Issue by arleysoto** [pkp/pkp-lib#5226]
Bug found on 3.1.2.1, only with Spanish version

The email template "Editor Decision Decline" does not charge in the UI when I click the button “No publicable” (Decline submission) under the “Envío” tab (Submission). 

If I click “No publicable” from the "Revisión" tab (Review) it works fine. 

I have added some images for better understanding
![1](https://user-images.githubusercontent.com/48956524/67518371-4cfb1380-f66a-11e9-8f61-1cef5af415fa.png)
![2](https://user-images.githubusercontent.com/48956524/67518373-4cfb1380-f66a-11e9-8cc6-08cea5f60494.png)

**Comment by asmecher** [comment]
@arleysoto, what the history of this installation? Is it a fresh install from 3.1.2-1, or was it upgraded from a previous release?

**Comment by arleysoto** [comment]
@asmecher that's the story:

<img width="705" alt="Captura de Pantalla 2019-10-24 a la(s) 2 37 53 p  m" src="https://user-images.githubusercontent.com/48956524/67519264-1faf6500-f66c-11e9-83c3-2cd20e0fe438.png">

**Comment by arleysoto** [comment]
@asmecher you are right. It happens only with instances upgraded from previous versions. Any suggestion?

**Comment by asmecher** [comment]
Found it! See the attached patch. This will only fix the upgrade process, so if you've already performed the upgrade, you'll need to create the email template manually in the "Prepared Emails" area. See `locale/es_ES/emailTemplates.xml` for the default text. The affected templates are `EDITOR_DECISION_INITIAL_DECLINE` and `EDITOR_RECOMMENDATION`.
