### ISSUE TITLE
[OJS] PDF not shown due to jQuery conflict when ALM plugin is activated

### ISSUE THREAD

**Issue by gpieri** [pkp/pkp-lib#523]
There is a jQuery version conflict when ALM plugin is used.

ALM Plugin loads jQuery 1.10 while OJS load jQuery 1.4.

This conflict leads to PDF not being shown sometimes, depending on which version of jQuery is active when $.ready event is fired. 

If jQuery 1.10 is active, an error occurs because $.browser (used in the PDF view) was removed in jQuery 1.9

I can reproduce this bug consistently in this journal:
http://raep.emnuvens.com.br/raep/article/view/8/6

**Comment by gpieri** [comment]
Forgot to mention that I'm using Chrome 42.0.x to reproduce this issue.

**Comment by asmecher** [comment]
Bruno, could you have a look at this and the attached PR?

**Comment by asmecher** [comment]
@beghelli, should this still be open?
