### ISSUE TITLE
Editing stage assignment in OMP leads to fatal DB error

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5233]
Editing the stage assignment in OMP gives an error:

```
omp: DB Error: Unknown column ‘date_status_modified’ in ‘field list’ Query: UPDATE submissions SET context_id=?,current_publication_id=?,date_status_modified=?,date_submitted=?,last_modified=?,stage_id=?,status=?,submission_progress=? WHERE submission_id = ?
```

This is related to the change from `date_status_modified` to `date_last_activity`. Should check for any remaining references to `date_status_modified`.

**Comment by asmecher** [comment]
Could this be an out-of-date pkp-lib submodule? I don't see any references to `date_status_modified` in the `master` branches outside of the upgrade scripts.

**Comment by NateWr** [comment]
Definitely possible. I am unable to reproduce this now.
