### ISSUE TITLE
"Journal Entry" tab name is confusing

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5236]
The "Journal Entry" tab in a submission's publication details caused some confusion. A new name for that tab maybe needed, or it may need to be broken up into more than one form.

**Comment by NateWr** [comment]
I'm a little stumped on an alternate name for this tab. This is the tab with settings in the new publication UI, where the following details about a published submission are set:

- Issue
- Section
- Cover Image
- Pages
- Date Published

Here's what the tab looks like in context:

![Selection_181](https://user-images.githubusercontent.com/2306629/71820489-1f2d4480-3087-11ea-9912-76faab7e3f8f.png)

Some ideas for a new name to replace "Journal Entry":

- Publication Entry
- Distribution
- ...

Anyone else have any ideas?

**Comment by amandastevens** [comment]
What about "Issue Data" or just "Issue"?  This may be what users look for, since most of the information here seems to be about the issue.

**Comment by mfelczak** [comment]
+1 for "Issue"

**Comment by librariam** [comment]
"Issue" or "In issue" makes sense to me.

**Comment by NateWr** [comment]
Issue it is! Thanks everyone. :+1:

PR:
https://github.com/pkp/ojs/pull/2568
