### ISSUE TITLE
Publisher Library: Allow file replacement

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#5239]
It'd be useful to be able to replace existing files in Settings > Workflow Settings > Publisher Library.

Currently the only workaround is to delete the existing file, which unfortunately breaks incoming links.

**Comment by cpockett** [comment]
We've found that uploading a file via the Submission Library via an existing submission with the same file name as the uploaded file, will overwrite the existing publisher library one. Granted I don't recommend this as a work around :)

**Comment by ctgraham** [comment]
Active work is in #5780.
