### ISSUE TITLE
Strange behavior with article cache in OJS3 ?

### ISSUE THREAD

**Issue by sourcedump** [pkp/pkp-lib#5247]
Hello,
I have a strange problem with a couple of articles of OJS 3.1.2.1. The articles are present on the database and are displayed in the admin backend, but when I try to reach them on the frontend (eg.: https://[hostname]/index.php/[journal]/article/view/3) I have a 404 error.
I've made some debugging and I've found that if I change the file 'pages/article/ArticleHandler.inc.php' at line 66:

`$publishedArticle = $publishedArticleDao->getPublishedArticleByBestArticleId((int) $journal->getId(), $articleId, true);`

to

`$publishedArticle = $publishedArticleDao->getPublishedArticleByBestArticleId((int) $journal->getId(), $articleId, false);`

The articles are visible again. The last parameter is the '$useCache'.
I've checked the file 'classes/article/PublishedArticleDAO.inc.php' and found that if '$useCache' is 'true', the 'getPublishedArticleByPubId' method can perform the following query to build its cache, without using the '$journalId'/'context_id':

```
SELECT
ps.*, s.*, COALESCE(stl.setting_value, stpl.setting_value) AS section_title, COALESCE(sal.setting_value, sapl.setting_value) AS section_abbrev
FROM
published_submissions ps
JOIN submissions s ON ps.submission_id = s.submission_id
JOIN sections se ON se.section_id = s.section_id
LEFT JOIN section_settings stpl ON (se.section_id = stpl.section_id AND stpl.setting_name = 'title' AND stpl.locale = 'it_IT')
LEFT JOIN section_settings stl ON (se.section_id = stl.section_id AND stl.setting_name = 'title' AND stl.locale = 'it_IT')
LEFT JOIN section_settings sapl ON (se.section_id = sapl.section_id AND sapl.setting_name = 'abbrev' AND sapl.locale = 'it_IT')
LEFT JOIN section_settings sal ON (se.section_id = sal.section_id AND sal.setting_name = 'abbrev' AND sal.locale = 'it_IT')
INNER JOIN submission_settings sst ON s.submission_id = sst.submission_id
WHERE
sst.setting_name = 'pub-id::publisher-id' AND sst.setting_value = '3'
ORDER BY ps.issue_id, s.submission_id;
```

that returns the wrong article and leading to the 404 error.
When '$useCache' is 'false' the 'getBySetting' method is used and the right article is found. The performed query is the following:

```
SELECT
ps.*, s.*, COALESCE(stl.setting_value, stpl.setting_value) AS section_title, COALESCE(sal.setting_value, sapl.setting_value) AS section_abbrev
FROM
published_submissions ps
JOIN submissions s ON ps.submission_id = s.submission_id
JOIN sections se ON se.section_id = s.section_id
LEFT JOIN section_settings stpl ON (se.section_id = stpl.section_id AND stpl.setting_name = 'title' AND stpl.locale = 'it_IT')
LEFT JOIN section_settings stl ON (se.section_id = stl.section_id AND stl.setting_name = 'title' AND stl.locale = 'it_IT')
LEFT JOIN section_settings sapl ON (se.section_id = sapl.section_id AND sapl.setting_name = 'abbrev' AND sapl.locale = 'it_IT')
LEFT JOIN section_settings sal ON (se.section_id = sal.section_id AND sal.setting_name = 'abbrev' AND sal.locale = 'it_IT')
INNER JOIN submission_settings sst ON s.submission_id = sst.submission_id
WHERE
sst.setting_name = 'pub-id::publisher-id' AND sst.setting_value = '3' AND s.context_id = 53
ORDER BY ps.issue_id, s.submission_id;
```

with the 'context_id' the result is correct. What do you think about that? Is this a bug?

Thank you very much

**Comment by asmecher** [comment]
@sourcedump, are you using the object cache (configured in `config.inc.php`)?

**Comment by sourcedump** [comment]
I think not, I've found this directive:

`object_cache = none`

**Comment by asmecher** [comment]
Are you using memcache?

**Comment by sourcedump** [comment]
Yes, we have it.

**Comment by asmecher** [comment]
I suspect that's the issue. Please disable it -- that code hasn't been tested/refined for quite a while.

See https://github.com/pkp/pkp-lib/issues/3304 for some future plans.

Meanwhile, I'll mark those options "not recommended" in `config.TEMPLATE.inc.php`.

**Comment by sourcedump** [comment]
Hello @asmecher,
I've disabled memcache, but the problem is still there. For now I've used a workaround for the affected submission ids. Let me know if you need further / other details.
Thank you

**Comment by asmecher** [comment]
@sourcedump, this has also been reported on the forum (https://forum.pkp.sfu.ca/t/500-error-on-some-articles-after-upgrade-to-ojs3/56887) but I've been unable to replicate the behaviour locally. If you're able to track down more information about the cause, I'd be very interested.

**Comment by sourcedump** [comment]
For now, I don't know more information about that beside the fact that the query involved in the problem doesn't use the journal_id to retrieve the article. Do you think that the behavior I've described above is correct?

**Comment by asmecher** [comment]
Are there articles in the same installation that share the same article ID in different journals?

**Comment by sourcedump** [comment]
I've checked the 'submission_id' in the 'submissions' table and there are no duplicates. 
Instead I've found that there are two articles with the same value ('3') in 'submission_settings' with the 'setting_name' = 'pub-id::publisher-id'. Could that be the error in the data?
I've tried this simplified query directly on the Database:
```
SELECT
ps.*, s.*
FROM
published_submissions ps
JOIN submissions s ON ps.submission_id = s.submission_id
JOIN sections se ON se.section_id = s.section_id
INNER JOIN submission_settings sst ON s.submission_id = sst.submission_id
WHERE
sst.setting_name = 'pub-id::publisher-id' AND sst.setting_value = '3'
ORDER BY ps.issue_id, s.submission_id;
```
And I have two articles returned. That can be why I have the wrong article in the OJS3 code (the wrong one has lower 'issue_id' and 'submission_id' so it's always returned as first).

**Comment by asmecher** [comment]
Yes, that's very likely the cause! It looks like there needs to be an added test for `context_id` on that fetch.

**Comment by asmecher** [comment]
It actually looks like this is already fixed in the `master` branch for release in OJS 3.2: https://github.com/pkp/pkp-lib/blob/e9902f9a2edbc12034296f03fabc550315f6f3c1/classes/services/queryBuilders/PKPPublicationQueryBuilder.inc.php#L86..L89
