### ISSUE TITLE
'reportxml.tpl' template don't found in OJS3

### ISSUE THREAD

**Issue by sourcedump** [pkp/pkp-lib#5248]
Hello!
I'm using OJS 3.1.2.1 and I've found a possible problem here:
plugins/reports/counter/classes/LegacyJR1.inc.php at line 354:

`$templateManager->display($this->_templatePath . 'reportxml.tpl', 'text/xml');`

This method is called when I ask an 'XML Version' of 'Journal Report 1 (R3)' in 'Older Site Reports' at the page of 'COUNTER Reports'
(ex. link: https://[hostname]/[journal]/management/tools/report?pluginName=CounterReportPlugin)

The error is that the 'reportxml.tpl' template is not found because, at the end, Smarty try to read this files:

- 'templates/plugins/reports/counter/templatesreportxml.tpl'
- 'lib/pkp/templates/plugins/reports/counter/templatesreportxml.tpl'

but the real path is 'plugins/reports/counter/templates/reportxml.tpl'

this lead to '$source->exists = FALSE' in 'smarty_resource_custom.php' that lead to the error.

**Comment by asmecher** [comment]
@sourcedump, thanks for reporting -- please try either of the attached patches (they're equivalent, just committed to different branches). This fix will be released in OJS 3.1.2-2 (very soon).
