### ISSUE TITLE
Updated fr_CA locale

### ISSUE THREAD

**Issue by mhvezina** [pkp/pkp-lib#5253]
New PRs for updated fr_CA translation. Small fixes.

`master` branch:

pkp-lib: https://github.com/pkp/pkp-lib/pull/5251
ojs: https://github.com/pkp/ojs/pull/2527

`stable-3_1_2` branch:

pkp-lib: https://github.com/pkp/pkp-lib/pull/5252
ojs:https://github.com/pkp/ojs/pull/2528

(All changes made to both branches. No need to foward-port those changes from stable-3_1_2 to the master branch)

**Comment by asmecher** [comment]
All merged -- thanks, @mhvezina!
