### ISSUE TITLE
Bug in RoleDAO::getUsersByRoleId

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#5256]
**Describe the bug**
The method RoleDAO::getUsersByRoleId fails when called with a null $roleId

**To Reproduce**
$roleDao->getUsersByRoleId(null, $context->getId());

**What application are you using?**
 OJS 3.1.2

**Comment by jonasraoni** [comment]
PRs:
`/stable-3_1_2` #5257
`/master` #5258

**Comment by asmecher** [comment]
Thanks, @jonasraoni -- both merged!
