### ISSUE TITLE
Upload of SVG images fails

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#5261]
OJS 3.1.2-1

I'm trying to upload SVG image through the website settings as a logo but receive a message about the unsupported format. According to [this conversion](https://github.com/pkp/pkp-lib/issues/2513) this format should be supported.

I think the problem is that PHP, particularly 7.2 version, which I'm using, detects svg as `image/svg`. It can be reproduced with `mime_content_type` method, although, following the documentation, the correct type should be `image/svg+xml`.  

It can be easily fixed by adding case here: https://github.com/pkp/pkp-lib/blob/master/classes/file/FileManager.inc.php#L464

**Comment by asmecher** [comment]
@Vitaliy-1, that makes sense; please send in a PR with that change!

**Comment by Vitaliy-1** [comment]
PR: https://github.com/pkp/pkp-lib/pull/5262

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1! Merged and back-ported to `stable-3_1_2`.
