### ISSUE TITLE
Crossref error message is not translated

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#5265]
**Describe the bug**
When running the Crossref export from the CLI, the locale key "plugins.importexport.common.register.error.mdsError" is not processed.

**To Reproduce**
1. Export articles via the Crossref plugin's CLI
2. Cause an error which reports via `__("plugins.importexport.common.register.error.mdsError", array('param' => $detail)`
3. Check the scheduled task log
4. See error such as:
```
[2019-11-11 14:39:28] http://servername.tld
[2019-11-11 14:39:28] [Notice] Task process started.
[2019-11-11 14:59:08] [Warning] ##plugins.importexport.common.register.error.mdsError##
[2019-11-11 14:59:26] [Warning] ##plugins.importexport.common.register.error.mdsError##
[2019-11-11 14:59:44] [Warning] ##plugins.importexport.common.register.error.mdsError##
[2019-11-11 15:00:02] [Warning] ##plugins.importexport.common.register.error.mdsError##
[2019-11-11 15:00:24] [Warning] ##plugins.importexport.common.register.error.mdsError##
[2019-11-11 15:00:42] [Warning] ##plugins.importexport.common.register.error.mdsError##
[2019-11-11 15:01:00] [Warning] ##plugins.importexport.common.register.error.mdsError##
[2019-11-11 15:01:00] [Notice] Task process stopped.
```

**What application are you using?**
 OJS version 3.1.2

**Additional information**
Could have been:
https://github.com/pkp/ojs/blob/e8811dc8ff11bc99e6bca0b07d0e1d4f3be13379/plugins/importexport/crossref/CrossRefExportPlugin.inc.php#L316
or
https://github.com/pkp/ojs/blob/e8811dc8ff11bc99e6bca0b07d0e1d4f3be13379/plugins/importexport/crossref/CrossRefExportPlugin.inc.php#L142
or
???

Parallel logic (selected) is here:
https://github.com/pkp/ojs/blob/e8811dc8ff11bc99e6bca0b07d0e1d4f3be13379/classes/plugins/PubObjectsExportPlugin.inc.php#L588
and
https://github.com/pkp/ojs/blob/e8811dc8ff11bc99e6bca0b07d0e1d4f3be13379/plugins/importexport/datacite/DataciteInfoSender.inc.php#L166
and
https://github.com/pkp/ojs/blob/e8811dc8ff11bc99e6bca0b07d0e1d4f3be13379/plugins/importexport/datacite/DataciteExportPlugin.inc.php#L237

`PubObjectsExportPlugin` as the parent (and with usage) deserves the `AppLocale::requireComponents(LOCALE_COMPONENT_APP_MANAGER);`

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/2570

@ctgraham do you have any time to test this PR? I'm not that familiar with the crossref export stuff or how to produce an error.

**Comment by ctgraham** [comment]
An easy way to reproduce the error is to munge the Crossref URLs in CrossRefExportPlugin.inc.php.  Cherry-picking 525a39d into 3.1.2-4 does not resolve the error for me, for reasons I can't yet explain.

I've been mostly distracted by finding https://github.com/pkp/pkp-lib/issues/5375 when I was trying to test this, so I haven't spent much time on looking at this one yet.

**Comment by ctgraham** [comment]
I lied in the description.  It isn't a problem with the CLI.  The problem occurs when running the scheduled task, which I was doing from the CLI as `php tools/runScheduledTasks.php plugins/importexport/crossref/scheduledTasks.xml`.  The `LOCALE_COMPONENT_PKP_MANAGER` may still be relevant, but the fact that it is missing is not the cause of this problem.  This key lives in `LOCALE_COMPONENT_APP_MANAGER`, and we should load it (and `LOCALE_COMPONENT_PKP_MANAGER`?) as part of `PubObjectsExportPlugin::addLocaleData()`.  PR forthcoming.

**Comment by ctgraham** [comment]
Hrm.  [QuickSubmit runs `AppLocale::requireComponents()` when `addLocaleData()` is called in the `register()` method](https://github.com/pkp/quickSubmit/blob/cf374b7c9b94eae47bcd66f916084b142397c8a3/QuickSubmitPlugin.inc.php#L25-L32), but other plugins generally don't.  They instead defer adding locales to Handlers or methods that explicitly deal with output.  Am I missing something?  Wouldn't a parallel call to `AppLocale::requireComponents()` when `addLocaleData()` is called in the plugin's `register()` method be a good way to guarantee a plugin has the locale keys it knows it will need?  Or is the register method called to frequently (making this extra loading a liability)?

**Comment by NateWr** [comment]
Yeah it looks like QuickSubmit is not written correctly. The `register` method is called on every plugin that is loaded (ie - when `PluginRegistry::loadCategory`) is called. This means that even if the plugin is not enabled, that code will run.

A plugin is supposed to check the result of the parent's `register` method before doing anything:

```php
function register($category, $path, $mainContextId = null) {
	$success = parent::register($category, $path, $mainContextId);
	if ($success && Config::getVar('general', 'installed')) {
		// Do stuff
	}
	return $success;
}
```

Also, keep in mind that a plugin category made be loaded but that doesn't mean all of its functionality will be used. For example, a report plugin may be loaded so that it appears in the list of available reports, but that particular request doesn't mean the report is being generated.

For this reason, it may be best to only load locale files when they are needed for the action that's being performed.

**Comment by NateWr** [comment]
@ctgraham do you recall how we left this? Is there a particular plugin where we need to rewrite the register function or was there more to it? I'm afraid this will get deferred again if there is more investigation that needs to happen.

**Comment by defstat** [comment]
This could be resolved if we added this line `AppLocale::requireComponents(LOCALE_COMPONENT_APP_MANAGER);` here https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/CrossrefInfoSender.inc.php#L33

We could also add the same code in the `register` function of the `PubObjectsExportPlugin` (resolving the same issue for `Medra`, `Datacite` and `Crossref` Plugins)

I am proposing a PR that somehow tries to incorporate the logic of adding PKP Locales to make them available through the plugin, and doing that within the `Plugin::addLocaleData` - Not sure if that may add more time (perhaps unnecessary load time) when the locales are loaded - The other approach would be to load the locales whenever needed (following the first solution for this particular issue)

@asmecher @NateWr @ctgraham 

**PRs**
[pkp-lib]: #5938
[OJS]: pkp/ojs#2782

To test that, try adding the line `$this->_addLogEntry(array(array('plugins.importexport.common.register.error.mdsError', 'test')));` here https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/CrossrefInfoSender.inc.php#L123

and then run the `php tools/runScheduledTasks.php plugins/importexport/crossref/scheduledTasks.xml` command 

You have to have 
- submissions to deposit, 
- the crossref plugin enabled and 
- `plugins.importexport.crossref.CrossrefInfoSender` `class_name` column value at the `scheduled_tasks` DB table set to let's say a day ago.

**Comment by asmecher** [comment]
@defstat, I'm leaning towards the simpler solution at the top of your last comment; there's very little overhead from duplicate calls to `AppLocale::requireComponents`, and eventually I'd like to look into relying more on the `gettext` toolset and removing our `AppLocale` and `PKPLocale` classes (at least the parts of them relating to locale file loading and translation). Ideally all locale content would be loaded automatically with acceptable resource overhead, removing the need for explicit component loads. So I'm hesitant to add more infrastructure at this point that might lead to deprecations in the mid-future.

**Comment by defstat** [comment]
@asmecher 

**PRs**
[OJS]: pkp/ojs#2783
[OPS]: pkp/ops#36

**Comment by asmecher** [comment]
All merged -- thanks, @defstat!
