### ISSUE TITLE
Missing GROUP BY in UserStageAssignmentDAO::filterUsersNotAssignedToStageInUserGroup causing paging problems in add participants grid

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5269]
**Describe the bug**
`filterUsersNotAssignedToStageInUserGroup` here 
https://github.com/pkp/pkp-lib/blob/master/classes/user/UserStageAssignmentDAO.inc.php#L72-L93 is used to list the users in the assign participants grid.

The SQL has two left joins `LEFT JOIN user_settings usgs ON (usgs.user_id = u.user_id AND usgs.setting_name = 'givenName')
LEFT JOIN user_settings usfs ON (usfs.user_id = u.user_id AND usfs.setting_name = 'familyName')`

Now that OJS supports multilingual user names, those left joins will return more than one match per user. This causes a problem with the itemCount which is used for the grid's paging feature. Basically each user is counted several times, depending on the amount of installed locales.

The SQL probably needs a GROUP BY.

It seems that saving the user profile form in multilingual sites will save an entry for each installed locale in the user_settings table. Meaning that the user could have several empty `givenName` and `familyName` entries.

**What application are you using?**
 OJS 3.1.2

**Additional information**
<img width="792" alt="Screen Shot 2019-11-13 at 14 44 38" src="https://user-images.githubusercontent.com/16347527/68774360-ac2ec100-0635-11ea-8f21-de60f5206e86.png">

**Comment by asmecher** [comment]
Good spotting, @ajnyga.

PRs:
- https://github.com/pkp/pkp-lib/pull/5278
- https://github.com/pkp/ojs/pull/2531 (tests only)

Can you try the pkp-lib PR and verify that it fixes the issue for you? It tests out OK here.

**Comment by ajnyga** [comment]
Works! thanks!

**Comment by asmecher** [comment]
Great! All merged, thanks.
