### ISSUE TITLE
Failure message for FormValidatorLength references site password length

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#5270]
**Describe the bug**
Class `FormValidatorLength` is structured to almost be a generic validator, except that it explicitly references `$site->getMinPasswordLength()` in the `getMessage()` method.

https://github.com/pkp/pkp-lib/blob/f4eed2b5cce527e4dacb26ce623306e910f8c7b6/classes/form/validation/FormValidatorLength.inc.php#L52

**To Reproduce**
1. Implement a form which uses a `FormValidatorLength` check.
2. Fail validation.
3. Error message reports the site min password length rather than the supplied length

**What application are you using?**
 OJS or OMP version 3.1.2

**Additional information**
n/a

**Comment by asmecher** [comment]
Thanks, @ctgraham!
