### ISSUE TITLE
User validation email references {$contextName}, which is not resolved before sending

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5273]
The `USER_VALIDATE` email template includes the `{$contextName}` variable, but that variable is not replaced before sending.

This is because the `{$contextName}` variable is only available to emails that are sent within a particular context (e.g. journal), but user creation and validation is not (it is site-wide).

**Comment by jonasraoni** [comment]
What about connecting the email with its available variables? Then we can display and make it easier for the user to insert them, as well as displaying a warning in case an undefined variable is used.

**Comment by asmecher** [comment]
Committed for release in 3.2.1, but if someone can test this against 3.1.2-x or 3.2.0-x, I can back-port there.
