### ISSUE TITLE
Provide averages for editorial statistics

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5275]
The new [editorial report statistics](https://github.com/pkp/pkp-lib/issues/4844) originally planned to include an Average/Year for each recorded statistic. This was dropped due to uncertainty about how the averages should be calculated.

These should be added again after considering the points raised in [this comment](https://github.com/pkp/pkp-lib/issues/4844#issuecomment-554011922).

Instead of adding a new table column, I thought it might be better to add averages as a part of the Total column:

| | Date Range | Total |
|---|---|---|
| Submissions Received | 10 | 50 (12/year) |

That might help clarify the difference between stats that are part of the date range and stats that aren't.

**Comment by NateWr** [comment]
These PRs add yearly averages to the editorial stats. They're added next to the totals.

![Selection_237](https://user-images.githubusercontent.com/2306629/76336144-7c46b000-62ed-11ea-9c96-6971d7a0f53d.png)

When an average can't be calculated (either because there hasn't been a full year of stats or because the total is zero) the averages do not appear.

![Selection_238](https://user-images.githubusercontent.com/2306629/76336216-92ed0700-62ed-11ea-9aa3-d66aab25185f.png)

PRs:
https://github.com/pkp/ui-library/pull/80
https://github.com/pkp/pkp-lib/pull/5609

Tests only:
https://github.com/pkp/ojs/pull/2675

**Comment by NateWr** [comment]
Merged

**Comment by NateWr** [comment]
The following PRs address a couple of issues that arose when testing with live data. 

- Prevent averages of `-1/year` from appearing when no average can be calculated
- Adds a missing check to some stats to ensure averages aren't calculated on invalid date ranges
- Fix a floating point rounding issue.

PRs
https://github.com/pkp/pkp-lib/pull/6012 (`stable-3_2_1`)
https://github.com/pkp/ui-library/pull/102 (`stable-3_2_1`)
(PRs for `master` coming)

Tests
https://github.com/pkp/ojs/pull/2812 (`stable-3_2_1`)

**Comment by asmecher** [comment]
All merged (submodules updated manually). Closing!
