### ISSUE TITLE
CSRF token is included in GET request in the search form

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#5276]
OJS master branch, 3.1.2 stable branch

Search form in `search.tpl` file after [this PR](https://github.com/pkp/ojs/pull/2437) sends GET request instead of POST. It includes [CSRF token](https://github.com/pkp/ojs/blob/master/templates/frontend/pages/search.tpl#L31), however, according to [OWASP guidelines](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#disclosure-of-token-in-url), there is usually no need to include it into GET requests and it remains logged in several places.

**Comment by asmecher** [comment]
Good spotting -- thanks, @Vitaliy-1!
