### ISSUE TITLE
Add "Obsolete version" notice to PDF viewer when new version available

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5277]
Currently, if I view an obsolete version of an abstract/landing page in OJS 3.2, I see the following text above the article info: 

"This is an outdated version published on [date]. Read the [most recent version]."

This text is very helpful, especially when a user visits the URL from the wild/out of context. It would be useful to have this same text available in the PDF reader interface when using the PDF.js viewer plugin, which provides a header strip that could include this info. The "most recent version" URL could just go to the canonical landing page URL. 

(Semi-related to the work in #4870.)

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/2567
https://github.com/pkp/omp/pull/738
