### ISSUE TITLE
OMP 3.1.2 getEditorTakenActionInReviewRound called with context gives a fatal error

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5279]
**Describe the bug**

EditorDecisionActionsManager::getEditorTakenActionInReviewRound in OMP does not use $context, but pkp-lib calls the function with a context. This causes an error and breaks the review stage for authors.

OMP: https://github.com/pkp/omp/blob/master/classes/workflow/EditorDecisionActionsManager.inc.php#L71

OJS: https://github.com/pkp/ojs/blob/master/classes/workflow/EditorDecisionActionsManager.inc.php

Also the translation key "submission.round" used in the authorDashboard review round tab seems to be just in the OJS locale files. There are probably two keys with a similar name in the system, the other only in OJS and the other in pkp-lib locale files.

**To Reproduce**
1. Create a new review and a new editorial decision in the review stage
2. As an author, try to access the review tab => Error

**What application are you using?**
OMP version 3.1.2

@NateWr 
https://github.com/pkp/pkp-lib/issues/4578#issuecomment-553554135

**Comment by asmecher** [comment]
On this aspect:
> Also the translation key "submission.round" used in the authorDashboard review round tab seems to be just in the OJS locale files. There are probably two keys with a similar name in the system, the other only in OJS and the other in pkp-lib locale files.

I've just corrected that by duplicating the locale keys from OJS into OMP (`stable-3_1_2` and `master`). Normally I'd push them into pkp-lib but between the translation freeze (3.2) and in-process shift from XML to PO this seemed less disruptive.

Other aspects to be handled separately...

**Comment by asmecher** [comment]
Resolved the rest by adding the `$context` variable for consistency. Thanks for catching this, @ajnyga!
