### ISSUE TITLE
Handle open translation pull requests before updating everything to .po files

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#5281]
Identify open pull requests containing locale XML files to handle those before merging everything to .po files

**Comment by mtub** [comment]
tagging #4779 as well…

List of open PRs:
- [ ] https://github.com/pkp/pkp-lib/pull/4912
- [ ] https://github.com/pkp/pkp-lib/pull/4631
- [ ] https://github.com/pkp/pkp-lib/pull/4628
- [ ] https://github.com/pkp/pkp-lib/pull/4581
- [ ] https://github.com/pkp/pkp-lib/pull/2528

**Comment by asmecher** [comment]
Remainders are outdated; closing.
