### ISSUE TITLE
Make sure remote galley URLs are included in Crossref "text-mining" and "crawler-based" elements

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5283]
Remote URLs currently aren't included as values in the "crawler-based" or "text-mining" elements in the Crossref deposit XML, but should be.

**Comment by bozana** [comment]
@AhemNason, is this still relevant? I think the remote URLs are now considered in text-mining, but not in crawler-based element, which I think is correct, right?

**Comment by AhemNason** [comment]
Gee, I really have no idea! And it's been a very long time since I thought about this in any way whatsoever! I defer to your expertise! I suppose I can add that I haven't heard of this being an issue or problem to be addressed in the recent past.

**Comment by bozana** [comment]
I would then close this issue, and we can consider it again if it appears to be a problem, but I do not think so... OK?
