### ISSUE TITLE
[OJS] Stop collecting user IP to email and event logs

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5285]
OJS/OMP will store users IP to the email and event logs. This is not required and we should make sure that we do not collect personal data that we do not use.

https://github.com/pkp/pkp-lib/blob/master/xml/schema/log.xml
https://github.com/pkp/pkp-lib/blob/master/classes/log/EmailLogDAO.inc.php
https://github.com/pkp/pkp-lib/blob/master/classes/log/EventLogDAO.inc.php
https://github.com/pkp/pkp-lib/blob/master/classes/log/EmailLogEntry.inc.php
https://github.com/pkp/pkp-lib/blob/master/classes/log/EventLogEntry.inc.php

**Comment by asmecher** [comment]
Merged, thanks!
