### ISSUE TITLE
ISSN Validator doesn't handle 0 or X checkdigits

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#529]
We're just doing an integer comparison of `11 - ($check % 11)` for the checkdigit, when the checkdigit should be '0' if `$check % 11` is 0 and 'X' if `$check % 11` is 10, and `11 - ($check % 11)` otherwise.

https://github.com/pkp/pkp-lib/blame/ojs-dev-2_4/classes/validation/ValidatorISSN.inc.php#L47

**Comment by asmecher** [comment]
Clinton, are you working on this one?

**Comment by ctgraham** [comment]
Not until tomorrow.  It's quitting time out here!

**Comment by asmecher** [comment]
OK, just making sure we're not stepping on toes.

**Comment by asmecher** [comment]
Merged and cherry-picked to ojs-dev-2_4 and ojs-stable-2_4_6. Thanks -- also for including tests!

**Comment by ctgraham** [comment]
The RegExp still doesn't handle X as the checkdigit.

**Comment by asmecher** [comment]
Merged and cherry-picked. Thanks, @ctgraham.
