### ISSUE TITLE
Updated fr_CA locale

### ISSUE THREAD

**Issue by mhvezina** [pkp/pkp-lib#5293]
New PRs for updated fr_CA translation. Small fixes. Hope I'm not too late for inclusion in 3.1.2-2....

master branch:

pkp-lib: https://github.com/pkp/pkp-lib/pull/5291
ojs: https://github.com/pkp/ojs/pull/2535

stable-3_1_2 branch:

pkp-lib: https://github.com/pkp/pkp-lib/pull/5292
ojs: https://github.com/pkp/ojs/pull/2536

All changes made to both branches (comments/grouping in commits may differ though). No need to foward-port those changes from stable-3_1_2 to the master branch.

@mtub : I'm not sure how https://github.com/pkp/pkp-lib/issues/5281 applies here...

**Comment by asmecher** [comment]
All merged above, thanks, @mhvezina!
