### ISSUE TITLE
Illegal string offset causing data to not be stored in DataObject

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#5294]
Hi there,

there is a possibility for an illegal string offset situation in `DataObject.inc.php` which might cause data loss.

This can be easily reproduced via the following code lines:

	$oldSubmission = ... // a submission with empty title

	$submissionDao = \Application::getSubmissionDAO();
	$newSubmission = $submissionDao->newDataObject();
	$newSubmission->setTitle($submission->getData('title'), null);

The line above results in passing `null` twice to `setTitle()` and then in `DataObject.setData()` the following line is called:

`$this->_data[$key] = $value;`

This adds `('title' => null)` to `$this->_data` as `$locale` has been passed as `null`.

Now the following line

	$newSubmission->setTitle("foo", "en_US");

will result in a `PHP Warning:  Illegal string offset 'en_US'` as a subsequent call to `DataObject.setData()` tries to set the data via

`$this->_data[$key][$locale] = $value;`

which fails as the second dimension if the `$this->_data` array at index `$key` is not an array.

A possible fix would be to add the following lines before accessing the data array:

	// remove data associated with the given key that has been set before
	// without a locale to avoid illegal string offset warning which would
	// cause the data to not be set (as second dimension of the array is
	// not an array at this point but it is accessed with the local key)
	if (array_key_exists($key, $this->_data)) {
		if (!is_array($this->_data[$key])) {
			unset($this->_data[$key]);
		}
	}

What do you think? Shall i provide a PR?

**Comment by asmecher** [comment]
@ViRuSTriNiTy, have a look at [SchemaDAO](https://github.com/pkp/pkp-lib/blob/master/classes/db/SchemaDAO.inc.php) in the `master` branch -- this is the new parent class underpinning e.g. `PKPSubmission` (for release with OJS 3.2). I think it'll at least partially address what you're working on here.

**Comment by ViRuSTriNiTy** [comment]
@asmecher  Ok, then i have to wait for OJS 3.2 i guess. I will keep the change as long as it isn't released.

**Comment by asmecher** [comment]
Sounds good, thanks! Closing this...
