### ISSUE TITLE
[OJS] Upgrade table does not exist

### ISSUE THREAD

**Issue by KRONWALLED1134** [pkp/pkp-lib#5296]
When trying to upgrade our OJS installation following error occured:

```
[data: dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml]
ERROR: Upgrade failed: DB: Table 'ojs3.submission_categories' doesn't exist
```

I looked through the schema files for various OJS versions and couldn't find a single CREATE script for the table submission_categories. 

Is there something completely out of sync on our side and we somehow lost a whole table?

**Comment by KRONWALLED1134** [comment]
I reset everything to original state and started the upgrade procedure for 3.1.2. Now the table is there as it should be. Sorry for the inconvenience.

**Comment by asmecher** [comment]
Not a problem, glad it worked out!
