### ISSUE TITLE
Fix issues with citation style language author and pages

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5297]
See https://forum.pkp.sfu.ca/t/is-this-a-bug-in-the-citationstylelanguage-plugin/57065:
> we’re using OJS 3.1.2.1 and we’ve noticed some issue with the citationStyleLanguage-Plugin. If we export the data as a .ris file for Zotero or Endnote, the page numbers are missing. I’ve looked into the code and I noticed the line for page numbers is missing there as well. Is this a bug or is this intentional? I’ve noticed I can add the page numbers with the line “SP - {$citationData->page}”, but I’m not sure if there’s some kind of collateral damage if I do this.
>
> Edit: Another thing we noticed: After importing the .ris file into Endnote, the author’s famliy name was jused as given name and vice versa.

**Comment by asmecher** [comment]
For OJS pre-3.1.2-2, you can fix this by applying https://github.com/pkp/citationStyleLanguage/commit/18a558afb66f35c3f4579fb42ec2b9af55611705.

**Comment by isgrim** [comment]
@asmecher Thanks for the quick reply and fix!
