### ISSUE TITLE
Author names missing in OMP

### ISSUE THREAD

**Issue by neffe** [pkp/pkp-lib#5300]
Hi
In our OMP setup, we have chosen a Danish and an English user interface. Danish is the primary locale. Our current version is 3.1.2.1

When our anthologies appear in the English UI, only one author name appears next to the individual chapters, even though several authors are registered. In the Danish UI everyone is shown. See:
![image](https://user-images.githubusercontent.com/10085388/69638987-0a0ed000-105c-11ea-9f11-259849d7e164.png)

How do I solve that problem?
Best
Niels Erik

**Comment by asmecher** [comment]
(Also filed at https://forum.pkp.sfu.ca/t/omp-is-not-showing-all-authors-in-the-chapter-field/57086 -- @neffe, let's continue the conversation there.)
