### ISSUE TITLE
Adjust Travis testing for PHP7.3/PHP7.4

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5323]
As of the planned OJS 3.2 release date, PHP7.2 will be EOL; PHP7.3 and 7.4 will be supported.

The Travis tests currently support PHP7.2/7.3; deprecate 7.2 and add 7.4.

This may require a bit of an overhaul -- the VM image that the CI framework currently uses does not support PHP7.4 at the moment, and will not go gracefully.

(WIP: my travis-versions-update OJS/pkp-lib branches.)

**Comment by diegoabadan** [comment]
Hi Alec,

Ubuntu 18.04 LTS comes with PHP 7.2 and will be supported until April 2023 (https://ubuntu.com/about/release-cycle). Wouldn't it be interesting to maintain PHP 7.2 support any longer in this case?

CentOS is also common on servers and CentOS-8 comes with php 7.2 with even longer official support time: https://wiki.centos.org/About/Product

**Comment by asmecher** [comment]
@diegoabadan, hmm, yes, that's helpful -- I had been going by https://www.php.net/supported-versions.php. Do you know how security fixes are managed (e.g. in the LTS releases) once the PHP team is no longer maintaining the release?

**Comment by diegoabadan** [comment]
Yes, Linux distributions and other projects share efforts to apply security fixes on their own in these cases. For example, Ubuntu 16.04 LTS maintains PHP 7.0.x and applies appropriate patches as seen at: http://changelogs.ubuntu.com/changelogs/pool/main/p/php7.0/php7.0_7.0.33 -0ubuntu0.16.04.7 / changelog

Usually Linux distributions avoid introducing incompatibilities within the same version. In this sense, hardly a software version (eg PHP) is updated, but only security paches or major fixes are applied to the originally distributed version.

**Comment by asmecher** [comment]
OK, thanks! Just trying to figure out a good policy for when to end support for an old PHP. Historically we've been too conservative and it's made it difficult for us to evolve the software as quickly as we'd like, but it's hard to know *how* dynamic we can be without forgetting our community, which relies on commodity hosting and shouldn't be dragged too close to the bleeding edge.

Ubuntu's LTS releases are a good data point, but I don't think it's practical to support everything they still support as a baseline -- Xenial (16.04) still includes PHP7.0 and requires intervention to upgrade, for example, and I think we'd find PHP7.0 to 7.4 too difficult to support. We'd need to support several major releases of PHPUnit, for example, just to bridge 7.0.

**Comment by diegoabadan** [comment]
I understand perfectly.

Perhaps a reasonable option is:

a) Strive to maintain the same requirements within a major version (eg OJS 3.1.x avoids requiring new requirements)

b) When releasing a major update (eg OJS 3.2 is lunched) we adopt the latest requirements that are well-supported (eg PHP 7.2 meets current CentOS and Ubuntu LTS).

c) Eventually a popular Linux distribution may not be serviced. For example, Debian 9 (stable) uses PHP 7.0 and may be a little far from maintaining compatibility. Users of it will need to use a newer external PHP in this case.

General Comments:

 Shared hosting providers (like Dreamhost, hostgator, CPanel based in general) often allow you to choose the version of PHP in a few clicks without the need for any advanced technical knowledge. In this case, needing to use a newer PHP should not bring any difficulty.

- Who installs OJS / OMP / etc on a dedicated (virtual) server, as is the most common case in Brazil, tends to be simpler to update their distribution to use the latest OJS, as long as this is infrequent. Item b) seeks to bring a good balance between updated and supported.

**Comment by asmecher** [comment]
Thanks, that sounds sensible. From a purely technical standpoint, we also have to make sure our testing framework works with current stable releases of PHP (https://www.php.net/supported-versions.php, plus whatever long-term versions we now want to support). For the moment we can satisfy those requirements using PHPUnit 7, and not conflict with what you outlined above.

**Comment by asmecher** [comment]
(Correction: PHPUnit 8. PHPUnit 7 doesn't support PHP7.4. Details: https://phpunit.de/supported-versions.html)

**Comment by asmecher** [comment]
`master` branch testing now working with PHP7.2, 7.3, and 7.4. Thanks for your feedback, @diegoabadan!

**Comment by asmecher** [comment]
(@ajnyga, I'm not sure how often you're rebasing PPS from OJS `master` -- if you'd like any help/guidance on porting these changes, please let me know.)
