### ISSUE TITLE
Provide accurate archiving options in OJS 3

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#5324]
Right now in OJS 3.x under Website Settings > Archiving, the PKP PN is listed with a checkbox to enable. It is not available for OJS 3 and may not be for some time, so when someone checks that box nothing happens. We repeatedly get inquiries and reports from users who want to enable the PKP PN in OJS and don't know it's not available or who try to enable it and are confused when nothing happens. 

I suggest  changing the text here to indicate the PKP PN is not available and possibly hiding the Enable check box until the PKP PN is actually available.

**Comment by alexxxmendonca** [comment]
I just want to add we get the same inquiries at SciELO.

**Comment by NateWr** [comment]
I think this will be addressed adequately in v3.2. Here's what it looks like when the plugin is not installed:

![pln-not-enabled](https://user-images.githubusercontent.com/2306629/70247484-5602f880-1771-11ea-902b-bc310f503992.png)

If it is installed, a checkbox will appear to enable/disable it, along with a button to open up the settings.

Closing as fixed but post if the text should be changed or this doesn't cover what you expected and I'll reopen it.

**Comment by amandastevens** [comment]
This looks great.  Thanks, @NateWr!
