### ISSUE TITLE
Services::get() does not define its return object

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5328]
Currently, the services container works by fetching a container by its identifier:

```
Services::get('submission')->anyMethod(...);
```

This means the `get()` method can't specify the type of object returned. Code editors are then unable to offer autocomplete, documentation, or jump-to-method features for the codebase.

We should change this so that each service is provided by its own method:

```
Services::submission()->anyMethod(...);
```

In order to support editor features like autocomplete, the `submission()` method should specify its return object:

```
/**
 * Get submission service class
 * @return SubmissionService
 */
static public function submission() : SubmissionService {
  return Services::get('submission');
}
```

**Comment by asmecher** [comment]
Agreed, getters seem to be the best way of doing this (see e.g.: https://stackoverflow.com/questions/6395737/how-do-i-make-my-php-ide-understand-dependency-injection-containers/6418373#6418373).

**Comment by NateWr** [comment]
Ok, thanks to @Vitaliy-1's work on integrating Laravel's service container, I think we can use this to create and instantiate service providers, and easily override them in our apps (OJS/OMP/OPS overriding pkp-lib) or mock them for unit tests. We can then use the service container with only a little bit of boilerplate to create facades which provide good type hinting.

Here's an example of how they would work. 

1. Define a `Query` class to get data about an object: https://github.com/NateWr/pkp-lib/commit/577f0508a6d95137ec50d8af515991fae67a751a#diff-345e98de2afff46e5a5df37941e9296f10948ee34470d16ecb5307e72f13f7c4
2. A facade class will provide type-hinted getter functions to load that class, so we get code completion: https://github.com/NateWr/pkp-lib/commit/577f0508a6d95137ec50d8af515991fae67a751a#diff-f951150659bb666611058e79eb4c7622d0168a70f618cfadf1b0998b31959d74
3. For unit testing, we can create a mock of that class: https://github.com/NateWr/pkp-lib/commit/577f0508a6d95137ec50d8af515991fae67a751a#diff-ccfc528863f689e63e4243544907ee4502226d71d05c746aad8d905d625a3468
4. And then tell the container to load the mocked class whenever it is requested: https://github.com/NateWr/pkp-lib/commit/577f0508a6d95137ec50d8af515991fae67a751a#diff-653e215d1b7baa6e35a73026f8301bd377e9a7e857cae5d136fb9f12d183baecR132-R137

I haven't tested, but I'm pretty sure that this will work for extending these classes in OJS/OMP/OPS. So we can for example ask the container for a query class related to submissions using the `PKP\` namespace:

```php
$query = App::make(\PKP\submissions\Query::class);
```

And in OJS we can tell the container to load `\APP\submissions\Query::class` instead.

I think that this addresses @asmecher's concerns about using static methods and puts us in a good place to make more use of [Laravel's service container](https://laravel.com/docs/8.x/container). In particular, this container gives us additional tools that allow us to [automatically inject dependencies](https://laravel.com/docs/8.x/container#automatic-injection). 

So I think that we could eventually move things like the `Request` object into the container and have it automatically injected. As well as inject dependencies like the `Context` when appropriate, which might help internalize much of the code and reduce boilerplate, especially for things like the `Map` classes.

What do you think? If it sounds promising, I'll try to work this up into a full example bringing queries, commands, DAOs, collectors and maps together.

**Comment by NateWr** [comment]
> So I think that we could eventually move things like the Request object into the container and have it automatically injected. 

Yes, this worked. We tell the container to [return the current request](https://github.com/pkp/pkp-lib/commit/57f9a4c5d973808e9027b6949bf6c0469e3116c3#diff-0f8d29025c583747ba8023ea056b974ac6de8e638c2dd2154c155f287bf7b7b0R16-R18) whenever it is asked for a `Request` object. Add a typehinted argument to the [Query constructor](https://github.com/pkp/pkp-lib/commit/57f9a4c5d973808e9027b6949bf6c0469e3116c3#diff-345e98de2afff46e5a5df37941e9296f10948ee34470d16ecb5307e72f13f7c4R22-R25). And whenever the container instantiates the `Query` class, it automatically passes the request into it.

Pretty cool. Should make it easy to mock the request or anything else in unit tests.

**Comment by asmecher** [comment]
@NateWr, excellent, this ties together a bunch of concurrent concerns nicely. Looking forward to walking through an example.

**Comment by NateWr** [comment]
Here is a fully-working example of this pattern applied to Announcements. The key is understanding Laravel's [Service Container](https://laravel.com/docs/8.x/container). It allows us to define how dependencies should be resolved, and then have those dependencies injected automatically.

First, we define a class with a type-hinted dependency ([example](https://github.com/NateWr/pkp-lib/commit/092f5492cbf273f79a1654ef2acf829c10e9af2e#diff-828cc202338393df8461dd2bc5a3032685902d84eef927baecd89ac6432e1517R39)):

```php
use PKP\announcements;

class Map {
  public $request;
  public function __construct(PKPRequest $request)
  {
    $this->request = $request;
  }
}
```

We then use a `ServiceProvider` to tell the container how to resolve this dependency ([example](https://github.com/NateWr/pkp-lib/commit/092f5492cbf273f79a1654ef2acf829c10e9af2e#diff-79308d3915f34d09bc92323605cc26b94554a5b5efd966098d7be21dffc7a47dR28-R30)):

```php
class AppServiceProvider extends ServiceProvider {
  public function register()
  {
    $this->app->singleton(PKPRequest::class, function ($app) {
      return Application::get()->getRequest();
    });
  }
}
```

Then we instantiate the class using the app container and have access to the dependencies ([example](https://github.com/NateWr/pkp-lib/commit/092f5492cbf273f79a1654ef2acf829c10e9af2e#diff-f1fc55c108c37d8914aed87e7f2a10ecf56db1744c3b1424ff914691e305df8dR40)):

```php
use Illuminate\Support\Facades\App;

$map = App::make(PKP\announcements\Map);
$request = $map->request;
```

We only need to register service providers for objects like `Requests` that can not be loaded directly based on their namespace/class name. When a class is instantiated with `App::make(...)`, the container will automatically inject any type-hinted objects that it can load from the namespace. For example, our Query classes can simply declare their associated DAOs and have them injected (see [example](https://github.com/NateWr/pkp-lib/commit/092f5492cbf273f79a1654ef2acf829c10e9af2e#diff-345e98de2afff46e5a5df37941e9296f10948ee34470d16ecb5307e72f13f7c4R30-R33)).


## DAO

The announcement DAO has been lightly refactored to support type hints and simplify basic read/write operations based on the JSON schemas (see [example](092f5492cbf273f79a1654ef2acf829c10e9af2e)).

A DAO now returns a generator (a [LazyCollection](https://laravel.com/docs/8.x/collections#lazy-collections)) instead of a `DAOResultIterator` (see [example](https://github.com/NateWr/pkp-lib/commit/092f5492cbf273f79a1654ef2acf829c10e9af2e#diff-7000423b8dc09265850f680b9280404589a0828a52a884d80691aaec948b2111R95-R98)).

Our `QueryBuilder`s have been renamed `Collector`s and designed to support type-hinting. We used to do something like this:

```php
$items = Services::get('announcements')
    ->getMany([
        'contextIds' => [1]
    ]);
```

Now we instantiate a `Collector`, configure it, and pass it in directly:

```php
$collector = Query::announcements()->getCollector();
$collector->filterByContextIds(1);
$items = Query::announcements()->getMany($collector);
```

See a [full example](https://github.com/NateWr/pkp-lib/commit/092f5492cbf273f79a1654ef2acf829c10e9af2e#diff-653e215d1b7baa6e35a73026f8301bd377e9a7e857cae5d136fb9f12d183baecR132-R1580).

## Service is now Query / Command

The announcement service class has been split into a `Query` and `Command` class. Each class is meant to offer a method for each action someone can make.

A query action is any action that does not modify the database. It can include getting objects from the database or any other source (like a list of valid submission file stages).

A command action is any action that does modify the database. Typically this will be just add, edit and delete. But may also include things like bulk assignment of DOIs, publishing and unpublishing, etc.

This is a lightweight refactor to make the purpose of the classes clearer. It was not always clear what should go into a service class. But all actions should go into either a `Query` or `Command` class.

These classes provide a top-level API to interact with an object. In theory, someone should not need to touch a DAO directly in order to work with objects. They should always be able to go through the `Query` and `Command` classes.

## Maps

Maps are still under discussion at https://github.com/pkp/pkp-lib/issues/6867. For now, the pattern supports our latest discussions, though it's still not finalised.

## Facades

Facades provide easy, type-hinted access to our `Query`, `Command` and `Map` classes. Laravel's `ServiceContainer` helps us manage dependency injection, but when instanting a class we get no information about that class back in our editors:

```php
use Illuminate\Support\Facades\App;

$query = App::make(\PKP\announcements\Query);
$query->... // No hints about what methods are available!
```

The facades are an easy, consistent way to discover what entities you can work with and what methods already exist to help you:

```php
use App\facades\Query;

$query = Query::announcements();
$query->... // Hints: get(), getIds(), getCount(), getMany(), etc.
```

In most cases, the return value of the facade will not be assigned to a variable, but used directly like this:

```php
use App\facades\Query;

$item = Query::announcements()->get($id);
```

## Evaluate

A working example can be found in these commits:

[pkp-lib](https://github.com/NateWr/pkp-lib/commit/092f5492cbf273f79a1654ef2acf829c10e9af2e)
[ojs](https://github.com/NateWr/ojs/commit/22364b8086dd20d73ad4969bb3e589f3455127c3)

@asmecher next I'm going to work on submissions/publications to prove these concepts on more complex objects. But I think there is enough here for you to evaluate the overall approach.

**Comment by NateWr** [comment]
@asmecher I've refactored publications and submissions now, in order to demonstrate the patterns on some more complex objects. There's a lot of code churn in these PRs (primarily due to replacing calls to `DAORegistry::getDAO('SubmissionDAO')`). The best overview of how this works is my [last comment](https://github.com/pkp/pkp-lib/issues/5328#issuecomment-832022628) and I've left the refactor of announcements in their [own commit](https://github.com/pkp/pkp-lib/pull/7064/commits/84c7a1c220c5df84d6d01008bb54bbb332b8d79f) to show a simple example.

I'm going to work up some documentation on this. But before going further, I think the overall approach needs a careful review -- especially in relation to our [discussion on maps](https://github.com/pkp/pkp-lib/issues/6867#issuecomment-827495588).

PRs:
https://github.com/pkp/pkp-lib/pull/7064
https://github.com/pkp/ojs/pull/3131

Here are a few questions I have:

1. I like the Command/Query distinction. But it seems like a Repository pattern is commonly used with Laravel (see repository [injected as dependency](https://laravel.com/docs/8.x/container#automatic-injection) and the [frequency of related search results](https://www.google.com/search?channel=fs&client=ubuntu&q=laravel+repository+pattern). Should we stick with the Command/Query classes or consider merging them into a Repository (basically, what our Service classes do now). The way I see it, having one Repository could lead to some large classes, but splitting into Command/Query is one more level of abstraction. I could see going either way, and maybe have begun to think using a pattern common in the Laravel community may make sense.

2. There are still some functions on the base DAO class like `convertFromDB` and `convertToDB`. But I don't want the new `EntityDAO`s to extend the old DAO, because there are a lot of functions that we want to discourage use of (eg - doing `retrieve` or `retrieveRange` directly), even though we still need them in some cases (for example, the pubId stuff is all intertwined and hard to refactor away for just one object). I want to keep the list of `public` methods clean in the DAOs, so that code completion can be useful. I opted to instantiate a root `DAO` in the [constructor](https://github.com/pkp/pkp-lib/pull/7064/files?file-filters%5B%5D=.php&hide-deleted-files=true#diff-36046ce37e2c72a6ecb17dc3ab52171b23911bf9d8244f2a20aff13a0888b84fR70) and then be [use it directly](https://github.com/pkp/pkp-lib/pull/7064/files?file-filters%5B%5D=.php&hide-deleted-files=true#diff-8959531c346d2c6c8be043795f18061d1f163c235f749e380430f872a3c68a22R250). This is a bit hacky, but hopefully we can eventually remove this as the old code goes away?

**Comment by asmecher** [comment]
> 1. I like the Command/Query distinction. But...

I also like the idea in theory but I'm concerned about the number of files associated with each entity (I know, that may not actually be a problem...) and the number of places someone will have to look in order to work with the database, e.g. changing its structure. If you're on the fence, I'd tip the balance towards the Repository pattern, particularly since Laravel already adopts it.

> 2. There are still some functions on the base DAO class...

I've read over the code but I'm still a little foggy on the eventual role for the DAOs. Are they to be the low-level access upon which the Service / Repository / Command / Query layer (which we end up with) embellishes for downstream code?

**Comment by NateWr** [comment]
Thanks for the code review, @asmecher. It was very helpful! And thanks @henriqueramos as well!

> If you're on the fence, I'd tip the balance towards the Repository pattern, particularly since Laravel already adopts it.

Ok, I think I will try that route and see how it goes.

> I've read over the code but I'm still a little foggy on the eventual role for the DAOs. Are they to be the low-level access upon which the Service / Repository / Command / Query layer (which we end up with) embellishes for downstream code? 

Yes, exactly. I see them as "dumb" classes that only know how to interact with the data store. For example, a submission DAO will know to write a data object to the `submission` and `submission_settings` table. It may also know that at least one publication needs to be created, and the ID set in the `current_publication_id` column. But it's the Service / Repository / Command / Query layer that knows to fire an event, update a cached count, etc, when a submission is created.

Having built out the Command / Query separation, I've noticed that this layer is important for commands (add/edit/delete/etc) but not for queries (get/getMany/getIds/getCount). There's no "extra business logic" that needs to be encapsulated when requesting data.

I think that this further undermines the case for Command / Query separation, and argues in favor of a Repository pattern. I've even thought about rolling the DAO itself into the Repository, so there is only one class per entity. This would be nice and simple. But I worry that we would encounter cases where we want to perform an action without firing the additional business logic (eg - QuickSubmit may want to add a submission but not send an email notification to authors). I'll play around with it and see. 

> (I ask because I see the DB facade being used both in the DAOs and elsewhere, which I'm finding confusing.)

It should only be used in the `DAO`s and the `Collector`s. Of course, you'll also see it in migrations. I had a look and I notice that I did include it once in a Query class, as I was juggling what to do with those pubId methods. I can sort that out.

As currently written the `DAO`s are probably not as "dumb" as they should be. For example, our publication DAO's `fromRow()` method automatically fetches and attaches authors, galleys, citations and controlled vocabulary. That's a lot of database requests for each publication, and contributes to the performance problems we have with the submissions list. In the future, they should probably be refactored to get less data, or to cache common information (for example, a submission could store a cached value for its current title and authors, preventing the need to lookup publications or any of its dependent objects for the submissions list).

**Comment by asmecher** [comment]
:+1: Good, based on this we can clearly and briefly define the distinction between DAOs and Repositories (DAOs dumb, Repositories smart) and I like the idea of slimming down the DAOs as much as possible not just from a pattern perspective but it also makes the refactoring progress fairly clear.

Have you got a pattern in mind for relationship classes, e.g. `stage_assignments`, `review_files`, or `user_user_groups`? Those have often been quirky -- in those particular cases there's a separate DAO, but we often align CRUD operations in with the DAO for whatever entity class we find most "proximate". It looks like Illuminate supports both implicit definition of relationship tables by declaring the many-to-many [at both ends of the relationship table](https://laravel.com/docs/8.x/eloquent-relationships#many-to-many-model-structure) with no further implementation required, or for richer cases, implementing the relationship [as its own model](https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models) (extending the `Illuminate\Database\Eloquent\Relations\Pivot` class rather than the normal `Illuminate\Database\Eloquent\Model` class). This latter approach seems richest to me -- to implement relationship tables in their own DAO/repository classes.

**Comment by NateWr** [comment]
> Have you got a pattern in mind for relationship classes

No, not really. I think they could be handled using the `Collector` approach. So a user's stage assignments might be retrieved like this:

```php
$collector = Repository::userGroups()->getCollector();
$collector
    ->filterByUserId($userId)
    ->assignedTo($submissionId);
$assignedUserGroups = Repository::userGroups()->getMany($collector);
```

In these cases, no DAO is needed. But I'd be happy to look at other options. A separate repository/dao could work just as well:

```php
$collector = Repository::stageAssignments()->getCollector();
$collector
    ->filterByUserIds([$userId])
    ->filterBySubmissionIds([$submissionId]);
$submissionAssignments = Repository::stageAssignments()->getMany($collector);
```

I think this could be more or less intuitive on a case-by-case basis. A `stageAssigment` feels like a separate "thing" from a user group. But a review file doesn't feel like a separate "thing" from a `submissionFile`, it is more like a group of files.

**Comment by NateWr** [comment]
@asmecher I've refactored the Command/Query classes to use a `Repository` class for each entity. Code can get a `Repository` using the facade:

```php
$submission = Repo::submission()->get($id);
```

Or where dependency injection is supported, classes can type hint the repository in the constructor arguments:

```php
use APP\submission\Repository;

class A
    public Repository $repo;
    public function __construct(Repository $repo)
    {
        $this->repo = $repo;
    }
}
```

This is looking pretty simple, although some classes do get [a bit large](https://github.com/NateWr/pkp-lib/blob/i5328_service_providers/classes/publication/Repository.inc.php). I think that we can improve this by identifying code that could be extracted to a separate class. The [validate() methods](https://github.com/NateWr/pkp-lib/blob/i5328_service_providers/classes/publication/Repository.inc.php#L134-L238) are a good candidate for this: each entity could have its own validator class, and the Repository can simply load and execute it.

I've also decided to abandon the `Maps` facade. Instead, a `MapsContainer` class manages plugin extensions and each map is instantiated from the entity's repository. This makes the repository a central location for interacting with an entity, and cuts down on the boilerplate needed to maintain the facade classes.

A repository simply uses Laravel's app helper to load it through the `MapsContainer`:

```php
class Repository
{
    /** @var string $schemaMap The name of the class to map this entity to its schema */
    public $schemaMap = maps\Schema::class;

    /**
     * Get an instance of the map class for mapping
     * submissions to their schema
     */
    public function getSchemaMap(): maps\Schema
    {
        return app('maps')->withExtensions(maps\Schema);
    }
}
```

Plugins can use the `app('maps')` helper method to extend a map:

```php
app('maps')->extend(PKP\submission\maps\Schema::class, function($output, Submission $item, PKP\submission\maps\Schema $map) {
    $output['example'] = 'test';
    return $output;
});
```

And those extensions are applied to child classes, so we can easily have a base pkp-lib map and [extend it in the app](https://github.com/NateWr/ojs/blob/i5328_service_providers/classes/submission/maps/Schema.inc.php), and plugins' extensions will still be applied.

We never totally settled the mapping discussion we had in https://github.com/pkp/pkp-lib/issues/6867. Does this look alright?

If you're happy with this approach, I'll start working on rolling this out to OMP/OPS too. But have a look and let me know what you think.

**Comment by asmecher** [comment]
@NateWr, you have my blessing -- I'm sure some of the details will crystallize as I start working with this, but considering it's a clean refactor of one of the most frequently-used entities, it looks very good.

**Comment by NateWr** [comment]
The following PRs convert announcements, submissions and publications to repositories in OJS, OMP and OPS. I expect the tests to fail. I'll get them passing, provide PRs for a few plugins before merging, and prepare updates to the docs before merging.

PRs:
https://github.com/pkp/pkp-lib/pull/7064
https://github.com/pkp/ojs/pull/3131
https://github.com/pkp/omp/pull/979
https://github.com/pkp/ops/pull/158

**Comment by NateWr** [comment]
All PRs merged! 

@asmecher I had to skip one test in OMP to get this over the finish line. That test is here: https://github.com/pkp/omp/blob/main/tests/classes/monograph/SubmissionFileDAOTest.php

It's failing on an attempt to mock the new submission DAO: https://github.com/pkp/omp/blob/main/tests/classes/monograph/SubmissionFileDAOTest.php#L73-L83

I wasn't sure how to fix this. Basically, the new DAOs are not accessed through `DAORegistry` but instead through their repository: `Repo::submission()->dao`. It wasn't clear to me how to make this happen in the unit tests, but hopefully it's nothing too difficult. Thanks!

**Comment by asmecher** [comment]
@NateWr, the disabled test is re-enabled and fixed by https://github.com/asmecher/lensGalley/commit/af127875cf5bb8b2e32f756bd581899afac28a46 (already committed to `main`).
