### ISSUE TITLE
Feature and Release checkboxes not sticking

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5333]
See https://forum.pkp.sfu.ca/t/omp-dont-show-feature-and-new-release-books-in-homepage/56247/11 for details.

The Featured and New Releases checkboxes in Catalog Management appear aways unchecked, regardless of the Featured / New Release status of a submission. Clicking causes the box to change state for a moment, then return to the state it was in before.

**Comment by asmecher** [comment]
@NateWr, this was a strange one, not least because it didn't affect the `master` branch, which is coded in the same way. Perhaps one of the Vue-template-processing dependencies in `stable-3_1_2` is less mature than in `master`?

In any case, the fix works for me, but the bug never appeared to affect `master`. (I suspect the implementation of Features / New Releases was developed against `master` then cherry-picked back to `stable-3_1_2`, and as a result this problem wasn't caught until it got released.)

**Comment by NateWr** [comment]
The underlying list panels changed a lot between `stable-3_1_2` and `master`, so probably in `master` the data structure changed a little bit or something.
