### ISSUE TITLE
Separate licenses for each chapter in OMP

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5338]
**Describe the problem you would like to solve**
From a [comment](https://github.com/pkp/omp/pull/729#issuecomment-562558225) by @withanage.

> For  Heidelberg,  there is a requirement to  support chapter-wise licenses and I will be able to implement the backend functionality during the next weeks.
> 
> I was thinking ,  it may be  better to define per submission basis, whether the   submission would support chapter-wise licenses as we did for the chapter dates.
> 
> ---
> ![Screenshot from 2019-12-06 13-57-12](https://user-images.githubusercontent.com/1921992/70324789-b73dd100-1830-11ea-813f-1804c1c91e08.png)
> 
> If the user selects "per chapter license" setting, he/she will get the opportunity to either add a url or a text in the chapter setting modal.
> 
> What will be your thought on it ? Is it something for the main OMP code or for a plugin?

**Comment by withanage** [comment]
thanksa lot @NateWr . For  3.1.2, I can  implement it.

**Comment by NateWr** [comment]
Please do this for `master`. We are trying to avoid adding features to stable releases unless they are really needed.

**Comment by withanage** [comment]
sure, I will do  in master.

**Comment by withanage** [comment]
@ nongenti  from  Heidleberg University will contribute to this ticket.

**Comment by asmecher** [comment]
Thanks for https://github.com/pkp/omp/pull/1166/files, @nongenti! @withanage, could you review this PR?

**Comment by withanage** [comment]
@asmecher  will  review  and @nongenti and  will give you a feedback next week.

**Comment by NateWr** [comment]
@withanage it looks like this was merged. Can this be closed?

**Comment by withanage** [comment]
@NateWr  sure, please go ahead!
