### ISSUE TITLE
[OJS] Error in Add Reviewer

### ISSUE THREAD

**Issue by phximenes** [pkp/pkp-lib#5353]
Hi there!

When I add a reviewer, the wheel that indicates server processing keeps spinning and never ends.

I analyzed the browser console and the error that appears is:

"POST https://mysite.com/index.php/myjournal/$$$call$$$/grid/users/reviewer/reviewer-grid/update-reviewer 500 (Internal Server Error)"

![image](https://user-images.githubusercontent.com/6383823/70932884-853f2280-2019-11ea-99d8-2eb85230a463.png)

The version of my OJS is 3.1.2.1.

Could you help me identify the problem and solve it?

Thank you!

**Comment by asmecher** [comment]
Hi @phximenes -- Please check your PHP error log  for details.

**Comment by phximenes** [comment]
It was my php.ini at the memory_limit parameter.
