### ISSUE TITLE
Add confirmation prompt when creating a new version

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5355]
**Describe the problem you would like to solve**
When I click on the "Create New Version" button, a new version is created immediately without asking me to confirm whether I intended to do that.

**Describe the solution you'd like**
A confirmation prompt should appear and if I don't confirm it no new version should be created.

## Acceptance Criteria
- [x] When I click the "Create New Version" button for a published submission, I am asked to confirm my intention before a new version is created.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/5357
https://github.com/pkp/ui-library/pull/55
https://github.com/pkp/ojs/pull/2557

**Comment by quoideneuf** [comment]
I am able to create a new version after confirming in the modal window.
