### ISSUE TITLE
Use human-friendly numbers for versions

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5356]
Each version has a unique ID in the publications table. However, users expect to see versions indicated relative to each submission. So each submission would have version 1, 2, 3, etc.

When a publication is created a `versionNumber` should be assigned that is incremented with each publication. So if it is the first publication, the number should be `1`. If it is the second publication, the number should be `2`.

When a publication is deleted, the `versionNumber` should be recalculated for all publications to ensure there are no gaps in numbering.

The version number should be used instead of the publication ID on the article landing page:

![Selection_176](https://user-images.githubusercontent.com/2306629/70987772-7c515e00-20b8-11ea-9bc4-c86cfec256d7.png)

Here the versions should read:

```
2019-12-11 (2)
2019-11-19 (1)
```

The version date and number should be used to identify the publication in the workflow in the same way as on the article landing page. Instead of the following:

![Selection_175](https://user-images.githubusercontent.com/2306629/70987848-9b4ff000-20b8-11ea-9411-7a508793e8b9.png)
 
Here the versions should say:

```
1 / 2019-11-19
2 / 2019-12-11
3 / Unpublished
```

## Acceptance Criteria

- [ ] When I create more than one version of a publication, I can see clearly in the editorial workflow which version is the original, second, third, etc., when they were published or if they are unpublished.
- [ ] When I visit an article as a reader and it has more than one version of a publication I can see clearly which published version is the original, second, third, etc, and when they were published.
- [ ] The version numbers increment sequentially so that the first, second and third versions are given numbers 1, 2 and 3.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/5371
https://github.com/pkp/ojs/pull/2569
https://github.com/pkp/omp/pull/739

![Selection_184](https://user-images.githubusercontent.com/2306629/71915402-96d89d80-3173-11ea-89b1-afecc7b0d738.png)

![Selection_183](https://user-images.githubusercontent.com/2306629/71915361-80324680-3173-11ea-972b-56e80cf59b81.png)

**Comment by quoideneuf** [comment]
It looks to me like there may be some pitfalls with the state of the DOM and the JS. See the screenshots below. All looks ok after a refresh (last screenshot).

Create a 3rd version, unpublish the 2nd.
![image](https://user-images.githubusercontent.com/1626547/73549946-a74a0400-4411-11ea-87d4-1bbafb5c8011.png)

Create a 4th version. Now I can't create any more versions
![image](https://user-images.githubusercontent.com/1626547/73550089-f3954400-4411-11ea-9a55-cc75582504a6.png)

After refreshing the browser it all seems ok:
![image](https://user-images.githubusercontent.com/1626547/73550127-04de5080-4412-11ea-83ec-ddc595ab9d8c.png)

**Comment by NateWr** [comment]
Thanks @quoideneuf!

PR:
https://github.com/pkp/ui-library/pull/63

Tests:
https://github.com/pkp/ojs/pull/2604

**Comment by NateWr** [comment]
Merged! :ship:
