### ISSUE TITLE
[OJS] Already Paid option missing for manual payment if waiver text not set

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#536]
Author cannot complete submission and ends up stuck in Step 5 of the submission process.

Courtesy of:
http://forum.pkp.sfu.ca/t/paypal-manual-payment-featuring-not-working-properly/859/12

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by asmecher** [comment]
(Are any more pulls forthcoming? I see you've tagged OCS.)

**Comment by mfelczak** [comment]
Yes, I'll have the OCS pulls shortly.

**Comment by mfelczak** [comment]
Not applicable to OCS, closing.
