### ISSUE TITLE
[OJS] abstracts fail to be displayed

### ISSUE THREAD

**Issue by ghost** [pkp/pkp-lib#5368]
I wonder if anyone else has experienced this odd behaviour. I have recently deployed OJS (v. 3.1.2.1) for a new journal and cannot get it display the abstract, keywords, etc. when pressing on the individual article titles/links. All the information is entered, but absolutely nothing at all is displayed, not even the title of the article and the author. I suspect a fundamental installation issue, though everything else seems to work ok.

System info:
PHP 7.1.33

screenshot of issue:

image.png
![image](https://user-images.githubusercontent.com/25158314/71550543-fa700780-29ca-11ea-96bf-9dbfe11a1f47.png)

**Comment by asmecher** [comment]
Check your PHP error log for details.

**Comment by NateWr** [comment]
If you don't find anything in your PHP error log, or aren't sure how to check it, I'd encourage you to try posting on the [community forum](https://forum.pkp.sfu.ca/). You'll find a community more able to assist you in tracking down things like this there.
