### ISSUE TITLE
Implement public and internal pages classification

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#537]

**Comment by NateWr** [comment]
This looks great @beghelli. Is there some way that I can pull these changes into my `header_ui` branch, without a bunch of merge conflicts down the road? Or would it be better to hold off until this work is merged upstream?

**Comment by beghelli** [comment]
Nate, I think you can move all your changed templates into a theme, restore the system default template files, and then run "git pull --rebase git://github.com/beghelli/ojs.git 537-public-internal" on your local branch. It shouldn't give you any merge conflict.

Then you can override the frontend ones insid your theme plugin. Let me know if that works.

**Comment by NateWr** [comment]
Alright, I was able to `git cherry-pick` your commits into the `header_ui` branch of my forks. No conflicts! My first `cherry-pick`. :)

**Comment by beghelli** [comment]
I think this can be closed, right @NateWr . Feel free to reopen if needed.

**Comment by NateWr** [comment]
Kind of a historic moment in commit history here! Thanks for kicking it all off at the beginning. :)

**Comment by beghelli** [comment]
It's been refreshing and motivating seeing you working @NateWr :) Thanks.
