### ISSUE TITLE
Unported CC licenses 3.0

### ISSUE THREAD

**Issue by mhvezina** [pkp/pkp-lib#5373]
I stumbled on this while doing some translation work...

Shouldn't the 3.0 CC licenses in https://github.com/pkp/pkp-lib/blob/e9902f9a2edbc12034296f03fabc550315f6f3c1/locale/en_US/submission.po#L1644 (and 5 more) be referred to as "Creative Commons ... 3.0 Unported License" instead of "Creative Commons .... 3.0 International License" ?

For what I can understand version 2.0 and 2.5 of CC used the term "Generic", then in 3.0 it was "Unported", and in 4.0 "International" for those versions not ported into local juridictions.

**Comment by asmecher** [comment]
I'd have to ask a librarian friend -- @AhemNason, maybe?

**Comment by sarahpearson** [comment]
This is correct. Unported was the terminology used for version 3.0. Thanks!

**Comment by NateWr** [comment]
I can make this change easily in English. It looks like some other languages still use the English term (`ar_IQ`). But what do we do about other languages? French is translated as "non transposé", which I'm guessing is a translation for unported? 

@asmecher is there a way to contact translators and ask them to check this? Or should I just remove all non-English translations and have them translate it again?

**Comment by asmecher** [comment]
Now that we're using `gettext`/Weblate, you can mark translation keys as needing review by adding the `fuzzy` flag: https://www.gnu.org/software/gettext/manual/gettext.html#PO-Files

I haven't used this yet but support seems widespread and this is a textbook use case :)

**Comment by mhvezina** [comment]
@NateWr Yes, "non transposé" is the official French name for the unported licence (https://creativecommons.org/licenses/by/3.0/deed.fr ). I had already made this translation when I reported the issue. 
It seems that some languages do use the English term "Unported" (e.g. Italian version : https://creativecommons.org/licenses/by/3.0/deed.it)

**Comment by NateWr** [comment]
@asmecher I think I've done it right but can you glance over it? I have:

- All `3.0 International License` changed to `3.0 Unported License`.
- All locales except `en_US` have `#, fuzzy` added so that they are reviewed.

I'll wait until after 3.2.0-1 to merge this in.

PR:
https://github.com/pkp/pkp-lib/pull/5603

**Comment by NateWr** [comment]
Merged. Thanks for the report @mhvezina
