### ISSUE TITLE
Port integration testing framework to Cypress

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5374]
Our integration testing toolset is getting rickety. It fails intermittently and doesn't use a well-trodden stack (the Facebook/Chromedriver/PHPUnit combo seems just about unique to us).

Instead, try [Cypress](https://www.cypress.io/). It's widely used and claims to take integration testing out of async browser hell.

**Comment by NateWr** [comment]
I took a quick look at Cypress and it looks great! I noticed that we can change the viewport size during tests so that will be great for running mobile tests for the default theme. :+1:

**Comment by asmecher** [comment]
Progress: Tests working in OJS! https://travis-ci.org/asmecher/ojs/builds/634523305

Remaining work:
- [ ] Statistics test needs to be ported
- [ ] OMP test code needs to be adapted
- [ ] Preprint server test code needs to be adapted
- [ ] Plugin tests need to be adapted

**Comment by asmecher** [comment]
Aaaaand we're done!
