### ISSUE TITLE
Issue while Installing QuickSubmit Plugin via Plugin Gallery in OJS 3.1.2.4

### ISSUE THREAD

**Issue by milind4computing** [pkp/pkp-lib#5378]
While Installing QuickSubmit Plugin v1.0.4.1 via Plugin Gallery in OJS 3.1.2.4, the following error occurs:
"`The uploaded plugin archive does not contain a folder that corresponds to the plugin name.`"

Same occurs when installed through "Upload Plugin" option.

Please help.

**Comment by asmecher** [comment]
See https://forum.pkp.sfu.ca/t/issue-while-installing-quicksubmit-plugin-via-plugin-gallery-in-ojs-3-1-2-4/57969/10
