### ISSUE TITLE
possibility for additional multi lingual metadata for a submission

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#538]
There is no possibility to add (e.g. from a plug-in) additional multi lingual metadata fields for a submission. The call "parent::getLocaleFieldNames()" in the function SubmissionDAO::getLocaleFieldNames is missing.
The pull request is coming...

**Comment by bozana** [comment]
Ah sorry -- it seems that this is only missing in omp_stable_1_1_1 i.e. it is already there in the master branch. Thus, the issue can be closed. (Or shall I make a pull request for omp_stable_1_1_1?)
Sorry, sorry, sorry! :-\

**Comment by asmecher** [comment]
That's OK! We'll (almost certainly) release OMP 1.2 next from the master branch, so no need to submit a PR for omp-dev-1_1.
