### ISSUE TITLE
Submission remains "unscheduled" despite being assigned to issue

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5380]
With the test data...
* Go to the "Journal Entry" for the Corino submission
* Under "Issue", select "Vol 1. 1 No. 2 (2014)
* Save the form

The "Status" at the top of the page will remain Unscheduled, even after a page reload:
![image](https://user-images.githubusercontent.com/200411/72179455-c49f2b80-3399-11ea-83f2-508947978cd5.png)

The submission does not appear in the published table of contents.

It does not seem possible to resolve this, as there is no "Publish" button available in the workflow.

**Comment by asmecher** [comment]
It turns out this was at least partially a permissions problem -- I was logged in as `admin`, rather than an (assigned) editor/manager.

However, I was confused by the "Unscheduled" state when the submission was scheduled against an issue (see screenshot above).

@NateWr, is this a PEBCAK or would a terminology change be helpful?

**Comment by NateWr** [comment]
There should be a "Schedule for Publication" button that appears where the publish button would be. The article is not considered "scheduled" until that process has been complete. This ensures that the pre-publication checks can be run before a publication is ready to go, and a publication without a required pre-publication check is not published with an issue.

There is a fix for this permissions issue waiting to go in with these PRs: https://github.com/pkp/pkp-lib/issues/4874#issuecomment-567915219

**Comment by NateWr** [comment]
(It's probably worth keeping this open to ensure the bug is fixed after those PRs are merged.)
