### ISSUE TITLE
Hooks for extending notification settings

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#5382]
Hi there,

i extended my OJS instance by a plugin that adds some notifications. These notification should be configurable under the *Notifications* tab in the user profile like the default notifications. Therefore i have added some hooks to the [notification form](https://github.com/pkp/pkp-lib/blob/master/classes/notification/form/PKPNotificationSettingsForm.inc.php) class to intercept the calls in the plugin. I think these hooks are useful for other users too hence i will create a PR.

So lonG
Daniel

**Comment by asmecher** [comment]
Merged https://github.com/pkp/pkp-lib/pull/5383 -- thanks, @ViRuSTriNiTy!
