### ISSUE TITLE
OAI Interface listRecords (OMP, Masterbranch)

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#5384]
Hi @asmecher  and @NateWr ,

In the OAI interface in OMP, listRecords  does not seem to be working in the master branch.
In OJS it works fine.

**To Reproduce**
OMP Version : https://github.com/pkp/omp/commit/4cb5638455e515084ca334071330fa643ae8f12a
lib/pkp :  https://github.com/pkp/pkp-lib/commit/c137018a8ab606c7cfd51e9b6c0a38b5e10ff9dc

1.  http://localhost:8002/index.php/test/oai?verb=ListRecords&metadataPrefix=oai_dc
2. See error
```sql
DB Error: Unknown column 'STATUS_DECLINED' in 'where clause' Query: SELECT ms.last_modified AS last_modified, pf.publication_format_id AS data_object_id, p.press_id AS press_id, pub.series_id AS series_id, NULL AS tombstone_id, NULL AS set_spec, NULL AS oai_identifier FROM publication_formats pf JOIN publications pub ON (pub.publication_id = pf.publication_id) JOIN submissions ms ON (ms.current_publication_id = pub.publication_id) LEFT JOIN series s ON (s.series_id = pub.series_id) JOIN presses p ON (p.press_id = ms.context_id) WHERE p.enabled = 1 AND p.press_id = ? AND ms.status <> STATUS_DECLINED AND pf.is_available = 1 AND pub.date_published IS NOT NULL UNION SELECT dot.date_deleted AS last_modified, dot.data_object_id AS data_object_id, tsop.assoc_id AS press_id, tsos.assoc_id AS series_id, dot.tombstone_id, dot.set_spec, dot.oai_identifier FROM data_object_tombstones dot LEFT JOIN data_object_tombstone_oai_set_objects tsop ON (tsop.tombstone_id = dot.tombstone_id AND tsop.assoc_type = 512 AND tsop.assoc_id = ?) LEFT JOIN data_object_tombstone_oai_set_objects tsos ON tsos.assoc_id = null WHERE 1=1 ORDER BY press_id, data_object_id
```

**What application are you using?**
OMP

**Additional information**

This line is the reason.
https://github.com/pkp/omp/blob/master/classes/oai/omp/OAIDAO.inc.php#L217

press_name = test

| API End Point| Stats |
| --- | --- |
| http://localhost:8002/index.php/test/oai?verb=Identify |  error|
| http://localhost:8002/index.php/test/oai?verb=ListRecords&metadataPrefix=oai_dc | error |
| http://localhost:8002/index.php/test/oai?verb=ListSets | :ok: |
| http://localhost:8002/index.php/test/oai?verb=ListMetadataFormats | :ok: |
http://localhost:8002/index.php/test/oai?verb=ListIdentifiers&metadataPrefix=oai_dc | errror|

**Comment by asmecher** [comment]
@withanage, I haven't tested the other issues, but [this commit](https://github.com/pkp/omp/commit/7e1f669a625b35d88e83ff13ef695ca3702ab266) should resolve the following error:
```
DB Error: Unknown column 'STATUS_DECLINED' in 'where clause' Query: SELECT ms.last_modified AS last_modified, pf.publication_format_id AS data_object_id, p.press_id AS press_id, pub.series_id AS series_id, NULL AS tombstone_id, NULL AS set_spec, NULL AS oai_identifier FROM publication_formats pf JOIN publications pub ON (pub.publication_id = pf.publication_id) JOIN submissions ms ON (ms.current_publication_id = pub.publication_id) LEFT JOIN series s ON (s.series_id = pub.series_id) JOIN presses p ON (p.press_id = ms.context_id) WHERE p.enabled = 1 AND p.press_id = ? AND ms.status <> STATUS_DECLINED AND pf.is_available = 1 AND pub.date_published IS NOT NULL UNION SELECT dot.date_deleted AS last_modified, dot.data_object_id AS data_object_id, tsop.assoc_id AS press_id, tsos.assoc_id AS series_id, dot.tombstone_id, dot.set_spec, dot.oai_identifier FROM data_object_tombstones dot LEFT JOIN data_object_tombstone_oai_set_objects tsop ON (tsop.tombstone_id = dot.tombstone_id AND tsop.assoc_type = 512 AND tsop.assoc_id = ?) LEFT JOIN data_object_tombstone_oai_set_objects tsos ON tsos.assoc_id = null WHERE 1=1 ORDER BY press_id, data_object_id
```

**Comment by withanage** [comment]
@asmecher 

thanks a lot. The fix worked.

| API End Point| Stats |
| --- | --- |
| http://localhost:8002/index.php/test/oai?verb=Identify |  ok|
| http://localhost:8002/index.php/test/oai?verb=ListRecords&metadataPrefix=oai_dc | ok |
| http://localhost:8002/index.php/test/oai?verb=ListSets | :ok: |
| http://localhost:8002/index.php/test/oai?verb=ListMetadataFormats | :ok: |
http://localhost:8002/index.php/test/oai?verb=ListIdentifiers&metadataPrefix=oai_dc | ok|


Although all scenarios worked, the console braught that this is undefined. I was not sure,  It was 

https://github.com/pkp/omp/blob/7e1f669a625b35d88e83ff13ef695ca3702ab266/classes/oai/omp/OAIDAO.inc.php#L240
```
PHP Notice: Undefined variable: submission in /media/wit/addd5813-d553-4435-bdd2-62c71ff19ec6/projects/omp/classes/oai/omp/OAIDAO.inc.php on line 240
```
Fixed it with submissionId, I will send a seperate PR  for that.
