### ISSUE TITLE
Submission keywords are not indexed/searchable

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5388]
The built-in search index does not index the "Keywords" metadata field and thus it is not searchable. (The "Subjects" field, which also uses the Controlled Vocabulary tools, is indexed and searchable.)

Make sure that all the metadata fields are indexed and searchable.

**Comment by asmecher** [comment]
(Meanwhile, the Lucene integration is available for richer searching, for those who are able to run it.)

**Comment by JazzyA** [comment]
Did Categories used to be called Subjects, as that is the only controlled vocabulary I see? Many thanks.

**Comment by asmecher** [comment]
@JazzyA, check Settings > Workflow > Metadata to see which fields are enabled.

**Comment by JazzyA** [comment]
Hi Alec,

 

Many thanks for such a quick response!

Although Subjects was ticked, the subsidiary setting: Do not request subjects from the author during submission was selected.

I will check what becomes available after switching this to: Ask the author to provide subjects during submission.

 

Kind regards, Adrian

 

AR Samuels

 <mailto:adrian@iTibet.co.uk> adrian@iTibet.co.uk

07792 201 772

**Comment by JazzyA** [comment]
Hi Alec,

 

Sorry but I cannot see where to define the Subjects controlled vocabulary.

Although as it appears to be an author feature I am assuming this is possible?

Many thanks. 

 

Kind regards, Adrian

 

AR Samuels

 <mailto:adrian@iTibet.co.uk> adrian@iTibet.co.uk

07792 201 772

**Comment by asmecher** [comment]
@JazzyA, are you looking for a way to constrain entries in that field to a defined set? That's not currently possible -- see https://github.com/pkp/pkp-lib/issues/1550 for some related discussion.

**Comment by JazzyA** [comment]
Yes Alec, precisely. So Categories are still the only controlled vocabulary options it seems then?

**Comment by asmecher** [comment]
"Controlled Vocabulary" is the term we use for any field that has a pick list/autocomplete, as opposed to a plain text field. This includes subjects/keywords, even though authors can extend the list with new entries during the submission process. For staff-limited controlled vocabularies, yes, Category and Section are your current options. In #1550 we'll be looking at more flexibility around this. One of the main impediments to just constraining some of these fields to a 3rd-party standard is the availability of that standard in a permissive license with broad, high-quality translations.

**Comment by JazzyA** [comment]
Thanking you Alec, so I think we will stay with Categories for now. 
I'll just sign off by saying its great we are both drummers, what are the chances!?

**Comment by asmecher** [comment]
I'm more of a drum owner than a drum player this year, but a return is imminent!

**Comment by ewhanson** [comment]
Hey @asmecher, it looks like adding keyword indexing will require a new search type constant. Do you have any recommendations or are there any best practices around what the value should be for the constant? I didn't know if they were used in any other way other than as an identifier. Thanks!

https://github.com/pkp/pkp-lib/blob/649c07b140e06d4b5120d78b56b3aab83e8e1e62/classes/search/SubmissionSearch.inc.php#L19-L29

**Comment by asmecher** [comment]
@ewhanson, these were originally coded (in the early days of OJS 2.x) so they could potentially be used as bitmasks, but that has never happened (and I consider it unlikely). I'd recommend e.g. using `0x00000011` and adding it between `SUBJECT` and `TYPE`.

**Comment by ewhanson** [comment]
Hey @asmecher, I've created PRs for this for 3.2.1 that cover this issue and #6626. For the OJS PR, it includes a code change and a submodule update. Should the submodule update be added separately as its own commit? If so, could you remind me of the preferred format for those?

If this looks okay, I'll make against master as well.

PRs:
#6693
pkp/ojs#3027

Thanks!

**Comment by asmecher** [comment]
Looks good -- thanks, @ewhanson! If you're able to forward-port this to `master` before approx. mid-day Monday, I can get this included in 3.3.0 as well.

**Comment by ewhanson** [comment]
Thanks, @asmecher! Will do.

**Comment by ewhanson** [comment]
Hi, @asmecher. Here are the PRs for `master`. Thanks!

PRs:
#6697
pkp/ojs#3028

**Comment by asmecher** [comment]
Thanks, @ewhanson! Merged for OJS 3.3.0, but this will also need porting for OMP and OPS; could you look at those? It's almost a trivial port, but both will need testing since we're about to release 3.3.0. (If you don't get around to the ports by the time I release 3.3.0, that's OK, we can merge for OMP/OPS 3.3.0-1.)

**Comment by ewhanson** [comment]
Hey, @asmecher. Still working on OPS, but here is the PR for OMP. Thanks.

PR:
pkp/omp#923

**Comment by ewhanson** [comment]
Hey, @asmecher. Here's the OPS PR. Thanks.

PR:
pkp/ops#115

**Comment by asmecher** [comment]
Merged (and cherry-picked for OMP and OPS to `stable-3_3_0`, which was created in the meantime) -- thanks, @ewhanson!
