### ISSUE TITLE
Statistics > Editorial Report : Graph does not update after change of date range

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#5391]
1. In the administration backend, go to Statistics > Editorial
2. Change date range to "All dates"

In the tables below, the numbers are updated, but the graph above does not update.

**What application are you using?**
 OJS 3.1.2-4

**Comment by asmecher** [comment]
@mpbraendle, can you check both your PHP error log (for a server-side error) and your browser console (for a front-end Javascript error)?

**Comment by mpbraendle** [comment]
Have not seen any errors (PHP and JavaScript) when trying to reproduce the behaviour. It just seems that the callback for the graph display is not triggered anymore.

Behavior is independent of browser used (Safari, Firefox).

**Comment by mpbraendle** [comment]
Hmm. My fault. It displays statistics on "Active submission". If you increase the date range back to the past, of course nothing changes.
If you enable the filters and filter by section, then the graph changes. 

I somehow assumed that the graph above and the table below are connected. Only partially, via the filters.

**Comment by asmecher** [comment]
Not a problem, always happy to have people looking this stuff over!
