### ISSUE TITLE
Strange folders in pkp-lib code

### ISSUE THREAD

**Issue by temin** [pkp/pkp-lib#5397]
I noticed there are three folders in [pkp-lib/plugins](https://github.com/pkp/pkp-lib/tree/master/plugins) folder that probably don't belong there:

- citationLookup and citationParser / containing only pl_PL and sl_SI locale files
- oaiMetadataFormats/dc / containing what looks like a plugin

Folders are also present in latest OMP and OJS releases.

**Comment by NateWr** [comment]
Thanks @temin! Looks like the `citationLookup` and `citationParser` plugins were removed in https://github.com/pkp/pkp-lib/issues/2874. Those locale files probably got merged in with a bit of lag time after the plugin had been removed.

I've removed everything for those two plugins. @asmecher heads up that I manually modified a couple of locale files: https://github.com/pkp/pkp-lib/commit/ab6ac9fbc58b5a700c80410011032b546aea08e4.

I'm not sure about the `oaiMetadataFormats/dc`. I'll defer to Alec on that one.

**Comment by asmecher** [comment]
`lib/pkp/plugins/oaiMetadataFormats/dc` contains some shared aspects of the application-specific `plugins/oaiMetadataFormats/dc` code. This is old stuff and we've moved away from splitting plugins between repositories, but a few cases remain awaiting refactoring.

@NateWr has addressed the others you noted, so I'll close this issue.

Thanks, @temin!
