### ISSUE TITLE
Custom date ranges in statistics report generator ignored

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#5398]
In stable-3_1_2, the custom date ranges when creating a custom stats report are currently being ignored. This seems to be a result of the recent conversion to JSON for the passing of the parameters.  The date range is normally supposed to be included in the filter variable as an array within that larger array, but it's coming in as a stdClass instead. The is_array test in the MetricsDAO getMetrics class is therefore skipping it.  Dumping the filter variable, it looks like this:

```
stdClass::__set_state(array(
'from' => '201901',
'to' => '202001',
)),
```

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/5399

@jnugent, does this need forward-porting to the `master` branch?

**Comment by jnugent** [comment]
@asmecher yep!  Right in here:  https://github.com/pkp/pkp-lib/blob/master/classes/statistics/PKPMetricsDAO.inc.php#L133

**Comment by asmecher** [comment]
OK, thanks -- would you mind putting together a PR for that?

**Comment by asmecher** [comment]
Thanks, @jnugent!
