### ISSUE TITLE
Payments tab does not appear when payments are enabled in settings

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5408]
When the payment options in OJS are configured, a new left-hand menu becomes available called "Payments".

However, when the payment settings are configured, it doesn't become visible -- it's necessary to reload the page before it'll be visible.

(See `cypress/tests/integration/Subscriptions.spec.js` for a work-around that should be removed when this is fixed.)

**Comment by asmecher** [comment]
@NateWr, is there a new preferred mechanism for this kind of thing that you could point me to?

**Comment by NateWr** [comment]
No, not yet. Things are still pretty ugly when tying the parts of Vue.js together with the old stuff. I hope in the next major version to bring the nav menus into Vue.js. For now, the ugly workaround is to reload the page on the form submission.

You can do this with a custom form component in Vue that reloads the page when the form returns successfully. You can see an example of a form with a custom save action [here](https://github.com/pkp/ui-library/blob/master/src/components/Form/context/LicenseForm.vue). I think what you want would be like this:

```js
<script>
import PkpForm from '../Form.vue';

export default {
	extends: PkpForm,
	mounted() {
		pkp.eventBus.$on('form-success', (formId, context) {
			if (formId === pkp.const.FORM_PAYMENT_SETTINGS) {
				window.location.reload(true);
			}
		});
	}
};
</script>
```

If the constant isn't available, look at where `PKPPaymentSettingsForm` is instantiated and you'll see where some constants are passed to the settings template.

If you want to explore some better UX options let me know. We can add a link into the form success notification, or add a custom HTML field that only appears when the settings are enabled, etc.

**Comment by NateWr** [comment]
On second thought, I think that you could add the event listener to the `SettingsContainer` component. So in `SettingsContainer.vue` that would look like:

```js
export default {
	...
	mounted() {
		pkp.eventBus.$on('form-success', (formId, context) {
			if (formId === pkp.const.FORM_PAYMENT_SETTINGS) {
				window.location.reload(true);
			}
		});
	}
};
</script>

**Comment by asmecher** [comment]
Thanks, @NateWr -- this needed a few tweaks to get running. I'm not confident this is the best place to be exposing the form constant. Would you mind taking a look?

- https://github.com/pkp/pkp-lib/pull/5452
- https://github.com/pkp/ui-library/pull/62

**Comment by NateWr** [comment]
Looks good. I'd put the `$templateMgr->setConstants(...)` call next to where the form is added in `ManagementHandler`:

https://github.com/pkp/pkp-lib/blob/master/pages/management/ManagementHandler.inc.php#L270

**Comment by asmecher** [comment]
Done -- thanks, @NateWr!
