### ISSUE TITLE
Upgrade the OJS but homepage does not work properly 

### ISSUE THREAD

**Issue by Adnanpij** [pkp/pkp-lib#5412]
![image](https://user-images.githubusercontent.com/60043094/72668080-f3826500-3a5d-11ea-87ba-15618c1fbd68.png)
how to fix this issue

**Comment by ViRuSTriNiTy** [comment]
Try clearing the cache folder or go to administration and clear template cache there.

**Comment by Adnanpij** [comment]
Tried, but doesn't work, i upgraded OJS, after that it happened.

**Comment by Adnanpij** [comment]
> Try clearing the cache folder or go to administration and clear template cache there.

Tried, but doesn't work, i upgraded OJS, after that it happened. Is there any other way?

**Comment by asmecher** [comment]
@Adnanpij, I suspect the upgrade did not complete successfully. Do you have the output from the upgrade process?

**Comment by Adnanpij** [comment]
> @Adnanpij, I suspect the upgrade did not complete successfully. Do you have the output from the upgrade process?

Upgrade was complete, there was no issue,

**Comment by asmecher** [comment]
@Adnanpij, can you check what version of OJS your database reports? See these instructions: https://forum.pkp.sfu.ca/t/how-do-i-determine-my-pkp-softwares-version/28534

Follow the instructions for "From the command line", "From the Web", or "From the Database".

The "From the Source Code" instructions will not help in this case -- that's not what we're looking for.

**Comment by Adnanpij** [comment]
> @Adnanpij, can you check what version of OJS your database reports? See these instructions: https://forum.pkp.sfu.ca/t/how-do-i-determine-my-pkp-softwares-version/28534
> 
> Follow the instructions for "From the command line", "From the Web", or "From the Database".
> 
> The "From the Source Code" instructions will not help in this case -- that's not what we're looking for.

I am using 3.1.2.4

**Comment by Adnanpij** [comment]
I upgraded from 3.1.2.1 to 3.1.2.4,So there is this issue, Please guide me how to fix

**Comment by asmecher** [comment]
@Adnanpij, how did you check your version?

**Comment by Adnanpij** [comment]
> @Adnanpij, how did you check your version?

Through Site administration, system information

**Comment by asmecher** [comment]
OK, good. Can you check your PHP error log for relevant messages?

**Comment by Adnanpij** [comment]
![aaaa](https://user-images.githubusercontent.com/60043094/72675545-b0a5a900-3ac0-11ea-9119-ebecff1bc552.PNG)
Here is error log screenshot

**Comment by Adnanpij** [comment]
> OK, good. Can you check your PHP error log for relevant messages?

![aaaa](https://user-images.githubusercontent.com/60043094/72675548-d6cb4900-3ac0-11ea-9d4c-ba35370e6a30.PNG)
Here is error log screenshot

**Comment by asmecher** [comment]
@Adnanpij, I don't see anything relevant there (though there might be something further up in the log).

It looks like you might be missing some files in plugins/themes/default (looking at https://forum.pkp.sfu.ca/t/upgraded-ojs-there-is-error-with-homepage/58095/4). Check to make sure all the files in the download package are present.

**Comment by Adnanpij** [comment]
> @Adnanpij, I don't see anything relevant there (though there might be something further up in the log).
> 
> It looks like you might be missing some files in plugins/themes/default (looking at https://forum.pkp.sfu.ca/t/upgraded-ojs-there-is-error-with-homepage/58095/4). Check to make sure all the files in the download package are present.

https://ss0109.hostingcare.net:2083/cpsess4953354460/frontend/paper_lantern/filemanager/showfile.html?file=error_log&fileop=&dir=%2Fhome%2Fpacificinternati%2Fpublic_html&dirop=&charset=&file_charset=&baseurl=&basedir=
can you please help me check this. log error file
I could not found default theme

**Comment by asmecher** [comment]
@Adnanpij, that's behind a CPanel login (please don't send me credentials). Did you check the directory I listed above?

**Comment by ViRuSTriNiTy** [comment]
@asmecher It really seems like there is no theme enabled at all as the web page does not load any theme related CSS or javascript. @Adnanpij Please check whether a theme plugin is enabled in the plugin settings.

**Comment by Adnanpij** [comment]
> @Adnanpij, that's behind a CPanel login (please don't send me credentials). Did you check the directory I listed above?

Okay, that doesn't work.

**Comment by Adnanpij** [comment]
> @asmecher It really seems like there is no theme enabled at all as the web page does not load any theme related CSS or javascript. @Adnanpij Please check whether a theme plugin is enabled in the plugin settings.

Yes, i installed two new themes and tried both, was enable

**Comment by ViRuSTriNiTy** [comment]
@Adnanpij The classic theme clearly includes additional files like CSS, fonts and stuff but the web page currently does not serve those so i guess the plugin isn't loaded. Is it possible for you to provide the full PHP error log as a file?

**Comment by Adnanpij** [comment]
> @Adnanpij The classic theme clearly includes additional files like CSS, fonts and stuff but the web page currently does not serve those so i guess the plugin isn't loaded. Is it possible for you to provide the full PHP error log as a file?

Thanks, it is resolved.

**Comment by Adnanpij** [comment]
Thanks everyone for help. Mr. "ViRuSTriNiTy" was correct, that theme was not enabled, So installed new theme, and enabled and it start working, even i couldn't find the default theme, but its fine.
