### ISSUE TITLE
CSS file upload error when saving 

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5423]
**Describe the bug**
When there is a current CSS file uploaded and you change other setting and try to save it returns an error saying "The file yo uploaded could not be found". 

**To Reproduce**
1. Go to 'Settings / Appearance / Advanced / upload a CSS file and save'
2. Go to other section or reload the page.
3. Go to 'Settings / Appearance / Advanced / upload a favicon or add content and click save'

**What application are you using?**
 OJS or OMP version 3.2

**Additional information**
Screenshot of error:
![Screen Shot 2020-01-23 at 15 29 59](https://user-images.githubusercontent.com/4992902/73021318-52950080-3df5-11ea-9a99-019baae9fc30.png)

**Comment by NateWr** [comment]
Thanks @israelcefrin, good catch!

PRs:
https://github.com/pkp/pkp-lib/pull/5429
https://github.com/pkp/ui-library/pull/60
https://github.com/pkp/ojs/pull/2586
https://github.com/pkp/omp/pull/749

**Comment by NateWr** [comment]
Merged, thanks!
