### ISSUE TITLE
Saving the Crossref plugin settings seems to hang, but in fact completes

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5427]
If I go to Tools > Import/Export > Crossref XML Export Plugin, make some changes, and click "Save" at the bottom of the page, nothing appears to happen. There's no spinner, and no indication that the page has been saved. However if I navigate away from that page by eg. clicking on another link in the sidebar, I get the "settings have been saved" notification on the subsequent page. If I return to the settings page, those settings changes have in fact been saved. so it's just a weird glitch with the notification display. 

OJS 3.2 / most recent code pulled today.

**Comment by asmecher** [comment]
@jmacgreg, can you check whether there's something in the error log corresponding to this?

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/2600

**Comment by jmacgreg** [comment]
Sorry @NateWr , just saw your request now. I can confirm that this is no longer an issue - problem solved. Thanks!
