### ISSUE TITLE
"Save" button is not available for my own submission's Publication tabs

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5431]
If I submit an article under my role as journal manager, assign myself as the editor, and move it all the way to production, and then try to edit any of the Publication tabs, I don't have access to the "Save" button for any of those tabs. So I can't for example, assign it to an issue. I am, however, able to create and upload a galley. That "Save" button should be available to me, especially if I'm assigned as an editor.

**Comment by NateWr** [comment]
Thanks! This was a permissions gap in cases where an admin with the journal manager role submits as journal manager and is never give a stage assignment but is implicitly granted access to the workflow stages. Tricky one. Nice catch. :+1: 

PR:
https://github.com/pkp/pkp-lib/pull/5440

Tests:
https://github.com/pkp/ojs/pull/2590

**Comment by NateWr** [comment]
Hmm, I see now that in the original report you said that you assigned yourself as editor. I was unable to reproduce the problem in that way. Once this fix is merged I'll ask you to try to reproduce it one more time.

**Comment by NateWr** [comment]
I've merged that in now. If you get a chance to update your test install and try again that'd be great. :+1:

**Comment by jmacgreg** [comment]
I think this is working as expected now - thanks!
