### ISSUE TITLE
Editorial Activity page is broken - PHP syntax error

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5433]
OJS 3.2, code from today. 

If I go to Statistics > Editorial Activity in the OJS backend, I receive a blank page with the following PHP error: 

`'PHP message: PHP Parse error:  syntax error, unexpected ')' in [...]/lib/pkp/classes/components/PKPStatsEditorialContainer.inc.php on line 56\n'`

If I change https://github.com/pkp/pkp-lib/blob/master/classes/components/PKPStatsEditorialContainer.inc.php#L55 from: 

`$this->i18n,`

to: 

`$this->i18n`

the problem disappears. I'm not sure if that's the best fix, syntax-wise, though.

**Comment by asmecher** [comment]
Fixed just as you suggested -- thanks, @jmacgreg.
