### ISSUE TITLE
Users report unavailable - PHP Fatal Error

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5434]
OJS 3.2, code from today. 

If I go to Statistics > Users, I get a blank page with the following in the error log: 

`'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method APP\\Services\\QueryBuilders\\UserQueryBuilder::get() in [...]/lib/pkp/classes/services/PKPUserService.inc.php:561\nStack trace:\n#0 [...]/lib/pkp/classes/services/PKPUserService.inc.php(585): PKP\\Services\\PKPUserService->count(Array)\n#1 [...]/lib/pkp/pages/stats/PKPStatsHandler.inc.php(315): PKP\\Services\\PKPUserService->getRolesOverview(Array)\n#2 [...]/lib/pkp/classes/core/PKPRouter.inc.php(391): PKPStatsHandler->users(Array, Object(Request))\n#3 [...]/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)\n#4 [...]/lib/pkp/classes/co...\n', referer: https://smoketest.publicknowledgeproject.org/index.php/bcn2019health2/management/settings/website`

I am not sure how to fix this issue.

**Comment by asmecher** [comment]
I think this is just a remaining bit of cleanup after https://github.com/pkp/pkp-lib/commit/69d6681832 resolved some ambiguous function naming. @NateWr, mind taking a quick glance at https://github.com/pkp/pkp-lib/commit/ad031d6f20140d7c9fb3c7ba0079deb10df03d7b to confirm that I don't need to involve `UserQueryBuilder::appGet`?

**Comment by NateWr** [comment]
That change looks correct, thanks! `appGet()` should never need to be called directly as it should be called during `$qb->getQuery()`.
