### ISSUE TITLE
Call to nonexistent function SubmissionDAO::deletePubId

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5437]
Scrutinizer report of missing function:
```
IssueId: 42851278  Message: The method ``deletePubId()`` does not exist on ``SubmissionDAO``. Did you maybe mean ``deleteById()``?  Filename: classes/plugins/PubIdPlugin.inc.php  LineNumber: 269  Link: https://scrutinizer-ci.com/g/pkp/ojs/inspections/59159ac1-c648-44a9-badd-6d0c23c142b5/issues/files/classes/plugins/PubIdPlugin.inc.php?status=new&selectedSeverities%5B0%5D=10&orderField=path&order=asc&fileId=classes/issue/IssueAction.inc.php&honorSelectedPaths=0&issueId=42851278
```
This appears to be a call to `SubmissionDAO` for a function that was migrated to `PublicationDAO`. See `classes/plugins/PubIdPlugin.inc.php` in the `clearIssueObjectsPubIds` function:
```
if ($submissionPubIdEnabled) { // Does this option have to be enabled here for?
    $submissionDao->deletePubId($submissionId, $pubIdType);
}
```
`$deletePubId` does not exist on `SubmissionDAO`, but it does on `PublicationDAO`.

**Comment by NateWr** [comment]
This should do it. We loop over the publications and delete the pub ids for each publication of a submission, and each representation of a publication, and file of a representation.

PR:
https://github.com/pkp/ojs/pull/2591

**Comment by asmecher** [comment]
I balked slightly at clearing DOIs from old versions, but since this is a user explicitly requesting a clear, I think this approach is sensible even though it affects all versions. Please go ahead.

**Comment by NateWr** [comment]
Merged!
