### ISSUE TITLE
Submission sequence no longer appears to be supported

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5438]
It appears that the addition of versioning (at least partially) removed support for submission ordering.

Previously the ordering of submissions within a section (in the table of contents) was designated using the `published_articles.seq` column. That has been removed and no equivalent has been added to `submission` / `publications`.

(The ordering tools in the Issues > Back Issues > Table of Contents grid appear to be broken.)

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/5462
https://github.com/pkp/ojs/pull/2605
https://github.com/pkp/omp/pull/757

**Comment by asmecher** [comment]
There's a FIXME flagged against this issue in `QuickSubmitForm`: https://github.com/pkp-translations/quickSubmit/blob/14b76fc0ae3eb87cc4cc2425c3734e940d4e8375/QuickSubmitForm.inc.php#L333..L348

**Comment by asmecher** [comment]
@NateWr, not sure if you missed this one -- https://github.com/pkp/pkp-lib/issues/5438#issuecomment-594215680

**Comment by NateWr** [comment]
Ah ok, I didn't realize you wanted me to look into it. I can do that, just never worked with the QuickSubmit plugin so will get up-to-speed on it.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/quickSubmit/pull/44

I found another issue while fixing this one, filed at https://github.com/pkp/pkp-lib/issues/5663.

**Comment by NateWr** [comment]
@asmecher does pkp/quickSubmit need a `stable-3_2_0` branch or is merging this to `master` enough?

**Comment by asmecher** [comment]
`master` is enough -- I haven't created a `stable-3_2_0` branch on repos like this where it isn't warranted (yet).

**Comment by NateWr** [comment]
Merged!
