### ISSUE TITLE
new Harvester install gives duplicate session pkey on first login

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#544]
After no errors on installing a new instance of the PKP harvester from Git (using the ohs-stable-2_3 branch), the first attempt at login gives the following error: 

`DB Error: Duplicate entry '0' for key 'sessions_pkey'`

**Comment by asmecher** [comment]
Does the 2.3.2 tarball show the same behavior?

**Comment by jalperin** [comment]
I have not installed from the tarball. I expected to be able to run the install from git...

Here's with debug on: 

(mysql): SELECT * FROM sessions WHERE session_id = '0cbcl65df4i59f19r2728k9a67'  
(mysql): INSERT INTO sessions (session_id, ip_address, user_agent, created, last_used, remember, data) VALUES (0, '96.49.33.214', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36', 1433375431, 1433375431, 0, '')  
1062: Duplicate entry '0' for key 'PRIMARY'
                        ADOConnection._Execute(INSERT INTO sessions 				(session_id, ip_address, user_agent, created, last_used, remember, data) 				VALUES 				(0, '96.49.33.2...) % line 1032, file: adodb.inc.php
                     ADOConnection.Execute(INSERT INTO sessions 				(session_id, ip_address, user_agent, created, last_used, remember, data) 				VALUES 				(?, ?, ?, ?, ?,..., Array[7]) % line  221, file: DAO.inc.php
                  DAO.update(INSERT INTO sessions 				(session_id, ip_address, user_agent, created, last_used, remember, data) 				VALUES 				(?, ?, ?, ?, ?,..., Array[7]) % line   83, file: SessionDAO.inc.php
               SessionDAO.insertObject(Object:Session) % line   80, file: SessionManager.inc.php
            SessionManager.SessionManager(Object:SessionDAO, Object:Request) % line  112, file: SessionManager.inc.php
DB Error: Duplicate entry '0' for key 'PRIMARY'

(mysql): UPDATE sessions SET user_id = NULL, ip_address = '96.49.33.214', user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36', created = 1433375431, last_used = 1433375431, remember = 0, data = '' WHERE session_id = '0cbcl65df4i59f19r2728k9a67'

**Comment by jalperin** [comment]
note: I'd dropped and re-added the indexes, which is why the index name is different here.

**Comment by asmecher** [comment]
Could you try the tarball? The ohs-stable-2_3 branch was forked long before our current policies on branches, so that would be a quick potential cause to eliminate.

**Comment by jalperin** [comment]
tarball is fine.

**Comment by asmecher** [comment]
Were you using the ohs-stable-2_3 head in lib/pkp, or the submodule version from the last harvester repo commit?

**Comment by jalperin** [comment]
I did a `git submodule update` after checking out ohs-stable-2_3 on the main repo.

**Comment by asmecher** [comment]
That's probably the last commit, not the current head version. If you're still tinkering with this, could you try the branch head instead?

**Comment by jalperin** [comment]
I set up my install from the tarball, so I am not playing with git anymore.

**Comment by asmecher** [comment]
I've committed a submodule update; I suspect that'll resolve it.
