### ISSUE TITLE
[OJS] journal/article metrics API

### ISSUE THREAD

**Issue by garymotz** [pkp/pkp-lib#5447]
We're running a local implementation of OJS at Indiana University and my department hosts a new journal using the OJS system. Is there an API for accessing metrics and statistics for faculty reporting that would allow me to query a user's profile to determine the number of articles submitted/accepted/published, etc.?

**Comment by asmecher** [comment]
Hi @garymotz -- would you mind posting questions at https://forum.pkp.sfu.ca? We use git issues more for bug reports and fully-specified feature requests; once there's been some Q&A-type discussion on the forum, we'd move here as a next step.
