### ISSUE TITLE
Author list does not work

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5449]
The `/path/to/ojs/index.php/publicknowledge/search/authors` list does not work; nor does the individual author listing given by clicking on an author.

**Comment by asmecher** [comment]
@NateWr, https://github.com/pkp/ojs/commit/ef95447f74c0f4dcde01ba3616d8d766aaedf93c fixes both on my installation, but could you take a quick glance at the code?

**Comment by NateWr** [comment]
Looks good. I was under the impression that we didn't support `/search/authors` but the PR looks alright. I left a couple of comments.

**Comment by asmecher** [comment]
I had a recent conversation (Slack with the hosting team maybe?) about this that elbowed me into supporting it, at least for now. And generally if something is broken I'd rather see it removed if not fixed. Thanks as always for the review, I've addressed your comments!
