### ISSUE TITLE
saving settings on fresh PKP Harvester install leads to blank page

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#545]
Specifically, it gives this error

    [Wed Jun 03 21:45:19.951803 2015] [:error] [pid 6611] [client 96.49.33.214:36294] harvester2 has produced an error\n  Message: WARNING: Invalid argument supplied for foreach()\n  In file: /var/www/harvester/lib/pkp/classes/i18n/PKPLocale.inc.php\n  At line: 138\n  Stacktrace: \n  Server info:\n   OS: Linux\n   PHP Version: 5.5.9-1ubuntu4.4\n   Apache Version: Apache/2.4.7 (Ubuntu)\n   DB Driver: mysql\n   DB server version: 5.5.38-0ubuntu0.14.04.1
    [Wed Jun 03 21:45:25.396726 2015] [:error] [pid 6120] [client 96.49.33.214:36353] harvester2 has produced an error\n  Message: WARNING: Invalid argument supplied for foreach()\n  In file: /var/www/harvester/lib/pkp/classes/i18n/PKPLocale.inc.php\n  At line: 138\n  Stacktrace: \n  Server info:\n   OS: Linux\n   PHP Version: 5.5.9-1ubuntu4.4\n   Apache Version: Apache/2.4.7 (Ubuntu)\n   DB Driver: mysql\n   DB server version: 5.5.38-0ubuntu0.14.04.1, referer: http://tkbr.ccsp.sfu.ca/harvester/index.php/admin

**Comment by asmecher** [comment]
That's bug 8423: http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8423

**Comment by dagosalas** [comment]
404 Page 👎

**Comment by asmecher** [comment]
I see you've also noted this at https://forum.pkp.sfu.ca/t/error-ohs-2-3-2-pkplocale-inc-php-line-138/5400/4 -- I'll follow up there.
