### ISSUE TITLE
Ensuring Blind Review directions need updating

### ISSUE THREAD

**Issue by greenr21** [pkp/pkp-lib#5450]
When reviewers or authors click on the "Ensuring Blind Review" hyperlink, they are given directions for how to remove identifying information from files they intend to upload. This information is invaluable but it seems to be written for older versions MS Office products. Newer versions - MS Word 2010, 2016, Office 365 - seem to have new method. 

Would be possible to update the directions to be somthing like this:

.......done by taking the following steps:

Newer versions of Microsoft Office (PC): File>Info>Inspect Document> Check for Issues> Inspect Document. If the inspection finds any results under Document Properties and Personal Information, select "Remove All", then save the document.
Newer versions of Microsoft Office (Mac): Review>Protect> Protect document> Under 'Privacy' tick 'Remove personal information from this file on save', then save document. 
Older versions of Microsoft Office (PC or Mac): File > Save As > Tools (or Options with a Mac) > Security > Remove personal information from file property on save > Save.
PDFs: With PDFs, the authors' names should also be removed from Document Properties found under File on Adobe Acrobat's main menu.

**Comment by asmecher** [comment]
@greenr21, would you be willing to open a pull request with your suggested change?

**Comment by greenr21** [comment]
@asmecher I'm willing, but that looks over my head. I'm not a coder, just a journal manager noticing a content issue. When I went to pull request, I got a bit lost in the jargon of push/pull, branches, and such. Any tips or is above my not-even-novice status?

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/5458

@greenr21 can you give this a close look for spelling/grammar/clarity? 

![Selection_197](https://user-images.githubusercontent.com/2306629/73470422-c730e780-437f-11ea-8783-26ff2de1e00d.png)

(Scheduling against 3.2 so it doesn't get forgotten but this can get bumped if there are any problems that would delay merge.)

**Comment by NateWr** [comment]
@greenr21 Someone pointed out that we have other guidance in our docs hub as well:

https://docs.pkp.sfu.ca/learning-ojs/en/editorial-workflow#removing-identifying-information

It looks like there are a few minor differences. Would you be able to check your guidance against that in the docs hub to see if one or the other is more accurate for your version of Office?

**Comment by greenr21** [comment]
The guidance in the document hub is very clear and accurate. To be utterly consistant, so let's just take the doc hub guidance text and use it to replace the current directions in the Enabling Blind Review link that authors and reviewers see. 
I reviewed the guidance in the doc hub and compared to the current text in the Enabling Blind Review link. 

I've made revised text below. I'm also attaching a doc with the original, edited revision, and final version.

[Revision to Ensuring Blind Review Directions OJS.docx](https://github.com/pkp/pkp-lib/files/4137904/Revision.to.Ensuring.Blind.Review.Directions.OJS.docx)

**PROPOSED REVISION – FINAL VERSION**
To ensure the integrity of the blind peer-review for submission to this press, every effort should be made to prevent the identities of the authors and reviewers from being known to each other. This involves the authors, editors, and reviewers (who upload documents as part of their review) checking to see if the following steps have been taken with regard to the text and the file properties:

•	The authors of the document have deleted their names from the text, with "Author" and year used in the references and footnotes, instead of the authors' name, article title, etc.
•	The authors of the document have removed personal information from the file properties by taking the following steps:

Microsoft Word for Windows:
1.	Go to File
2.	Select Info
3.	Click on Check for Issues
4.	Click on Inspect Document
5.	In the Document Inspector dialog box, select the check boxes to choose the type of hidden content that you want inspected.
6.	Click Remove All
7.	Click Close
8.	Save the document

Microsoft Word for MacOS:
1.	Go to Tools
2.	Click Protect Document
3.	Select Remove personal information for this file on save
4.	Click OK and save the file

PDF:
1.	Go to File
2.	Select Properties
3.	Remove any name in the author field
4.	Click OK
5.	Save the document

**Comment by NateWr** [comment]
Thanks @greenr21! @asmecher I've updated the PR above. How do you feel about this locale string change? Should we defer to 3.2.1?

**Comment by asmecher** [comment]
I'm OK to merge it, since it's an interation/improvement on what we already have, which is still solid (if outdated) guidance.

**Comment by NateWr** [comment]
Merged! Thanks for your contribution @greenr21.
