### ISSUE TITLE
PHP7 issue with 2.4 custom report generator, 'continue' out of context

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#5451]
This is another low priority fix for OJS 2.4, for PHP7 compatibility.  The custom report generator uses "continue" in a few places, but outside of switch or while statements, which is no longer allowed in PHP7.  So these generate Fatal Errors:

>  PHP Fatal error:  'continue' not in the 'loop' or 'switch' context

Small pull request inbound.

**Comment by jnugent** [comment]
PR for this:  https://github.com/pkp/ojs/pull/2596

**Comment by asmecher** [comment]
Merged, thanks, @jnugent!
