### ISSUE TITLE
Replace homegrown country, language, and currency codes with a 3rd-party library

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5453]
We currently maintain our own lists of countries, languages, and currencies, each with their respective DAOs. It would be better to delegate the maintenance of these lists to a 3rd-party library to ease translation demands and decrease the amount of out-of-date information.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/5454
- https://github.com/pkp/ojs/pull/2598

**Comment by asmecher** [comment]
@NateWr, would you mind taking a look at the PRs above (https://github.com/pkp/pkp-lib/issues/5453#issuecomment-579988179)? Thanks! (The incentive: 17,000 lines of code removed.)

**Comment by NateWr** [comment]
Looks great! And looks like we'll trim even more lines of code once we remove the deprecated DAOs. :+1:

This might be a good thing to get recorded in our main documentation. How to get a list of language and currency options, and how we store this information in the database. If there's any conditional logic that needs to be applied to the available options (see [comment](https://github.com/pkp/pkp-lib/pull/5454#pullrequestreview-352168116)), that could be documented as well.

**Comment by asmecher** [comment]
Thanks, @NateWr! All merged. Yes, the only list that required conditionals was the language list, and it would've been nice for the upstream library to permit easier fetching of subsets (and document this aspect better) but they seem content to refer to the ISO639-3 documentation: https://github.com/sokil/php-isocodes#languages-database-iso-639-3
That said, I favour referring to the 3rd party resource rather than reiterating their documentation; this would be a good change to include in the 2.3 notes you've been building.
