### ISSUE TITLE
Fix language field cardinalities

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5455]
The submission metadata form's languages field appears to be multilingual, when in fact it's a controlled vocabularly limited to the ISO639-2 language list, and should store an equivalent value (based on the ISO symbolic codes) regardless of the language the user is working with.

The API language listing appears to likewise provide locale-specific language lists.

**Comment by asmecher** [comment]
(https://github.com/pkp/pkp-lib/issues/5453 should be merged before this is fixed!)

**Comment by NateWr** [comment]
This was discussed a bit with Mike Nason in https://github.com/pkp/pkp-lib/issues/5000. This issue seems to specify a more specific outcome. Shall I close the other?

**Comment by NateWr** [comment]
That issue does have the following [commen](https://github.com/pkp/pkp-lib/issues/5000#issuecomment-544431931) which may or may not be tackled in this one.

> The last thing that needs to happen is the consistent use of this data in metadata distribution. At the moment, the Google Scholar tags use the languages metadata but do not fall back to locale. The DataCite and Medra exports seem to use languages but fall back to locale if it's not specified. And the DOAJ export uses locale and never checks for languages metadata.

**Comment by asmecher** [comment]
Actually, the other issue already covers it better. I knew I discussed this stuff somewhere recently...
