### ISSUE TITLE
Resolve redundant email template XML files

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5461]
Since the move to PO files for email templates, there are two lists of email templates:
- `registry/emailTemplates.xml`, and
- `locale/xx_YY/emailTemplates.xml`

Since `locale/xx_YY/emailTemplates.xml` now just refers to locale contents in the email PO file, it is redundant (and will very likely get out of sync, causing missing templates). Get rid of this category of file and clean up related code.

**Comment by asmecher** [comment]
One-liner [ha!] to annotate the new format with the necessary data from the old one:
```
for key in `sed -n -e "s/^\W<email_text key=\"\(.*\)\">$/\1/p" < locale/en_US/emailTemplates.xml`; do 
    OUT=`xmllint --xpath "//email_texts/email_text[@key=\"${key}\"]" locale/en_US/emailTemplates.xml`
    BODY=`echo $OUT | sed -n -e "s/.*<body>{translate key=\"\(.*\)\"}<\/body>.*/\\1/p"`
    SUBJECT=`echo $OUT | sed -n -e "s/.*<subject>{translate key=\"\(.*\)\"}<\/subject>.*/\\1/p"`
    DESCRIPTION=`echo $OUT | sed -n -e "s/.*<description>{translate key=\"\(.*\)\"}<\/description>.*/\\1/p"`
    sed -i -e "s/\(<email key=\"$key\".*\)\/>$/\\1 subject=\"$SUBJECT\" description=\"$DESCRIPTION\" body=\"$BODY\"\/>/" registry/emailTemplates.xml
done
```

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/orcidProfile/pull/90
- https://github.com/pkp/pkp-lib/pull/5472
- https://github.com/pkp/ojs/pull/2610

**Comment by asmecher** [comment]
@NateWr, could you have a look at the PRs above? If they're OK, I'll take care of porting this to OMP and OPS as well.

**Comment by NateWr** [comment]
I had a look over the code and it all looks good. :+1: Would you like me to run a manual install on it to check or happy with a eyes-only code review?

**Comment by asmecher** [comment]
Eyes-only is fine, thanks, I've done a bunch of testing already!
