### ISSUE TITLE
OJS 3.2 citations error on upgrade

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5465]
Using the latest checkout from master, attempting to upgrade a fairly straightforward test journal. When I check out the latest code from master and run the upgrade, the upgrade process quits on the following error: 

`ERROR: Upgrade failed: DB: Duplicate entry '0-1' for key 'citations_publication_seq'`

(This happens just after the lib/pkp/xml/schema/metadata.xml step.)

It looks like this has something to do with the fact that there's data in the `citations` table. If I restore the DB, remove the data there (not recommended except for test instances!) and re-run the upgrade, I don't encounter the issue. I can provide a test DB dumb if that's helpful, but chances are just ensuring that there's some data in the `citations` table by saving a few article reference fields with data should also ensure that this is reproduced. 

(@asmecher - this also relates in a way to our recent discussion re: references for Coalition Publica. I could meet on Thursday or Friday to review if you like.)

**Comment by NateWr** [comment]
@jmacgreg Can you share this test db with me via Slack?

**Comment by jmacgreg** [comment]
On its way!

**Comment by NateWr** [comment]
@asmecher can you take a look at this `ALTER` statement to see if its compatible with all our supported databases? https://github.com/pkp/omp/pull/759/commits/527fdb5daa8712dbbf6d3e3d4f52a3f614d4ab9b#diff-4969856a1022f0d5d7b0aee5dca9a5abR54

Fix for this is part of PRs here: https://github.com/pkp/pkp-lib/issues/4856#issuecomment-582528375.

**Comment by asmecher** [comment]
Thanks, @NateWr -- I added a comment on that here: https://github.com/pkp/omp/commit/527fdb5daa8712dbbf6d3e3d4f52a3f614d4ab9b#r37183334

**Comment by asmecher** [comment]
This issue is in the development branch only of OJS pre-3.2.0. For anyone encountering a similar message with OJS 3.2.0-0, see: https://github.com/pkp/pkp-lib/issues/5626
