### ISSUE TITLE
Submitting file to Submission Library overwrites Publisher Library files

### ISSUE THREAD

**Issue by cpockett** [pkp/pkp-lib#5471]
**Describe the bug**
We've found that when you upload a file to the submission library with the same file name as a file already in the publisher library it overwrites the publisher library copy. This happens at the file system level so the publisher library metadata additionally become out of date.

**To Reproduce**
0. Upload a file to the 'Publisher/Document Library'
1. Go to an open submission
2. Click on 'Submission Library'
3. Click 'Add a file' 
4. Supply file name and type (I suspect these don't matter but I've made them the same as the existing publisher library file).
5. Upload a file with the same filename as one already existing in the 'Publisher/Document Library'
6. Click 'Ok'
7. Go to 'View Document Library' and download the Publisher File
8. This file will be identical to the 'Submission Library' one (the timestamp on the server side file confirms this)

**What application are you using?**
 OJS version 3.1.1.4 and 3.1.2.1

**Additional information**
Let me know if you need more than this, apologies as I've only submitted a bug once or twice.

**Comment by asmecher** [comment]
Good spotting, @cpockett! To fix this, you'll need to apply https://github.com/pkp/pkp-lib/commit/a3690848857025808a9790f32dcd9ec1b76019be in `lib/pkp`. Existing files will need to be moved/copied -- the added upgrade script will take care of that, and will warn the admin about possible filename collisions during the upgrade.

**Comment by cpockett** [comment]
I'm not quite sure how to run the upgrade script to be honest. I upgraded my test OJs instance to the newest version. I'm using a github checkout for it currently (easier for patching). I've cherry-picked the commit onto the detached head version of lib/pkp. And reran the upgrade via php tools/upgrade.php upgrade. 

I'm sure I'm just missing something but not sure what. Currently when I try to click any files from either library I just get a 200 response with a blank page via the following url pattern '/$$$call$$$/api/file/file-api/download-library-file?libraryFileId=7&submissionId=368'

**Comment by asmecher** [comment]
@cpockett, that upgrade step will be run with the upgrade to OJS/OMP 3.2; the upgrade script can't selectively run upgrade steps outside that greater framework (without a manual work-around that'll require some coding). I'd suggest waiting for 3.2 to be released at the end of this month. Do you use the library extensively? If not, if you need to fix this before the next release, it might just be easiest to re-upload existing files individually. Otherwise, if you have some PHP skills, I can suggest how to dive into that work-around.

**Comment by cpockett** [comment]
@asmecher I'm comfortable with PHP. I could wait but I wouldn't mind knowing the work-around in case it become relevant in the future.

**Comment by cpockett** [comment]
I guess since it's a public function I could probably just call it directly, via command-line come to think of it.
