### ISSUE TITLE
[OJS] Assign DOIs action in DOI plugin broken

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5473]
Selecting the action causes the following error:
`PHP Fatal error:  Uncaught Error: Call to undefined method Services::getMany() in classes/plugins/PubIdPlugin.inc.php:52`

**Comment by ajnyga** [comment]
The description of feature says:

```
Assign DOIs
Are you sure you wish to assign DOIs to all published objects that have not been assigned DOIs?

```
With that feature, do we want to assign a DOI 
a) just for the latest publication or 
b) to all the publications within the submission?

@jmacgreg  @AhemNason ?

**Comment by ajnyga** [comment]
(thinking that if we at some point have DOI versioning in OJS, then option B will continue working but choosing option A now, will probably mean that function needs to be checked)

**Comment by AhemNason** [comment]
The intent is that it assigns a DOI to all content that doesn't currently have one. It's for situations where someone has back-issues that they now want to mint DOIs for. It's pretty common when we, for example, pick up a client who didn't have a Crossref membership before they signed up. 

Both of those options terrify me broadly, though. Especially the "REASSIGN DOIs" button. That should be command-line only or at least pop up 3 modal warnings about how, if you do that, you should really understand what's about to happen. Of the two, "assign" is far less problematic. It's just a thing that someone might click and then not ever bother actually registering the DOIs they've assigned.

**Comment by ajnyga** [comment]
Sure, we use assign DOIs a lot when importing back issues as well.

**At the moment in 3.2 Reassign DOIs will delete all DOIs in the system**. Not sure why the label still is reassign and not "Delete all DOIs". It is connected to this function here, which will leave nothing behind: https://github.com/pkp/pkp-lib/blob/master/classes/publication/PKPPublicationDAO.inc.php#L257

It says in the description: "If you change your DOI configuration, DOIs that have already been assigned will not be affected. Once the DOI configuration is saved, use this button to clear all existing DOIs so that the new settings will take effect with existing objects."

Concerning the Assign DOIs action removing the action totally is of course another matter, but even if it would be a command line option, the question I made above still stands, but I now solved it according to B in my pr.

**Comment by AhemNason** [comment]
Wait, I thought "reassign DOIs" deleted all DOIs and _replaced them with new ones as per the patterns dictated in the DOI plugin_. Is that not the case?

**Comment by ajnyga** [comment]
The Reassign button is tied to `clearPubIds` action here https://github.com/pkp/ojs/blob/master/plugins/pubIds/doi/classes/form/DOISettingsForm.inc.php#L90

Which will fire the action here:
https://github.com/pkp/pkp-lib/blob/master/classes/plugins/PKPPubIdPlugin.inc.php#L86-L90

Which will call `deleteAllPubIds` here
https://github.com/pkp/ojs/blob/master/classes/journal/JournalDAO.inc.php#L68-L85

And that will delete pubIds from all objects, for example for Publications:
https://github.com/pkp/pkp-lib/blob/master/classes/publication/PKPPublicationDAO.inc.php#L257-L270

So there is nothing that would add new DOIs there.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/5511
- https://github.com/pkp/ojs/pull/2624

PRs for OMP and OPS not required.

@NateWr, could you give this a quick once-over? I had to change a directly-coded `UPDATE` SQL query back to an `ADODB::replace` call, which will `INSERT` when no rows are affected by an `UPDATE`.

**Comment by AhemNason** [comment]
Just tested this and I'm seeing a modal that stays up and inactive when clicked. 

1) had a published article that hadn't been assigned a DOI
2) clicked "assign DOIs" from the DOI plugin
3) opens modal with warning/ok/cancel
4) can click button, but nothing happens... not frozen, window closes properly when "cancel" is clicked.

**Comment by jmacgreg** [comment]
Back to the conversation regarding the "Reassign" function: This issue may be causing some of the confusion in #5514. I'll echo what @AhemNason said: the "reassign" function should 1) clear and 2) reinstate DOIs based on the current pattern. Maybe this should split into a separate ticket, or #5514 can be expanded to address this.

**Comment by asmecher** [comment]
@AhemNason, are you testing with our testing installation? I haven't updated it to include the PRs.
@jmacgreg, yes, I'd favour splitting the change of functionality into another entry, and leaving this one (scheduled against 3.2) just for the bugfix.

**Comment by jmacgreg** [comment]
Hi @asmecher, I've updated the test instance with a fresh checkout as of about an hour ago. I'll split the reassign issue into another entry, though I'll note that this isn't so much a change of functionality requested but a confirmation that the traditional behaviour remains the same.

**Comment by asmecher** [comment]
@AhemNason/@jmacgreg, I've cherry-picked the changes into the test installation. They should be visible there now.

**Comment by NateWr** [comment]
@asmecher The code looks good to me. :+1: 

@AhemNason do you have time to do a test today now that Alec has updated the test installation? Definitely need to get these ticked off ASAP so we can hit our release schedule.

**Comment by AhemNason** [comment]
Works great! Just tested!

**Comment by wrandtkeflvc** [comment]
> Just tested this and I'm seeing a modal that stays up and inactive when clicked.
> 
> 1. had a published article that hadn't been assigned a DOI
> 2. clicked "assign DOIs" from the DOI plugin
> 3. opens modal with warning/ok/cancel
> 4. can click button, but nothing happens... not frozen, window closes properly when "cancel" is clicked.

I have a similar issue that @AhemNason  had had in the quote above.  I wrote that up here https://forum.pkp.sfu.ca/t/ojs-3-1-1-4-cant-edit-article-metadata-to-add-a-custom-doi-spinner-icon-stays-indefinitely-and-the-doi-does-not-save-to-metadata/59364 .

Could anyone confirm here that @AhemNason 's issue was resolved here in issue 5473, and would be resolved in the OJS 3.2.0 release (which includes issue 5473)?

One thing that's giving me pause is that some of this got moved to issue 5514, and 5514 (not in the OJS 3.2.0 release and still open) includes "Clear DOI button function for any individual DOI".  That's not my issue, but that's activity with the DOI at the article level.  So, I want to check whether resolution of 5473 affects me and after upgrade whether I would be able to assign a DOI from the article level.

**Comment by wrandtkeflvc** [comment]
So... My biggest problem was solved by optimizing the database.  After optimizing the database, this is the behavior in OJS 3.1.1-4 :

When an article is published, and I go to add a DOI at the article level, a spinner spins and spins and spins, and the DOI never gets saved in metadata.  I assume that the desired behavior would be that an error message would pop up and tell me that I'm not allowed to add a DOI to a published article, because in the testdrive (as of today the PKP testdrive is on OJS 3.2.0) an error message pops up.

When an article is published, and I go to add a DOI at the article level, a spinner spins and spins and spins.  When I close the metadata editting window and reopen it, I can see that the DOI actually did save on the article metadata.  (It doesn't matter whether the article has ever been previously published or not.  As long as the article is unpublished when I go to add the DOI, it will save.  The bug is that I never get a success message.)

Anyway, optimizing database tables made it possible for me to save the DOI to metadata at the article level as long as the article is unpublished when I go to add the DOI.

I believe that the bug in OJS 3.1.1-4 is that there will never be either an error message nor a save successful message when saving a DOI to metadata at the article level.  If anyone could confirm that that's a known bug and that that lack of a success/error message is what's fixed in GitHub issue no. 5473, I would be very grateful?

**Comment by asmecher** [comment]
(Cross-linking the various places this conversation is taking place: https://forum.pkp.sfu.ca/t/ojs-3-1-1-4-cant-edit-article-metadata-to-add-a-custom-doi-spinner-icon-stays-indefinitely-and-the-doi-does-not-save-to-metadata/59364/12)
