### ISSUE TITLE
Test/fix CrossRef / DOI implementations

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5481]
A tracking issue to flag this for attention before the release. These may not be working.

**Comment by asmecher** [comment]
(See also: https://github.com/pkp/pkp-lib/issues/5473 and https://github.com/pkp/pkp-lib/issues/5474)

**Comment by ajnyga** [comment]
(also: https://github.com/pkp/pkp-lib/issues/5505)

**Comment by asmecher** [comment]
(Closing this in favour of specific entries.)
