### ISSUE TITLE
Newly assigned editors are not permitted to edit metadata

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5482]
When assigning a Journal Editor, the assignment is created without metadata editing permission. However, the Journal Editor role does not allow the metadata edit checkbox to be set (presumably since that role should always have that permission).

Steps to reproduce:
- Create a new submission
- Remove any automatically-assigned journal editors
- Use the participants grid to add a new Journal Editor (noting that the "Allow this person to edit the publication details" checkbox is not shown)
- Note that the newly-created assignment does not permit metadata editing:
  `SELECT can_change_metadata FROM stage_assignments ORDER BY stage_assignment_id DESC LIMIT 1;`

There is also a UI quirk that should be fixed at the same time: once a user has been selected in the "add participant" form, changing the role ID in the dropdown can give mistaken impression that the user can be assigned under the selected role (even though they may not have it). Should changing the user group dropdown apply the changed filter immediately, rather than requiring a click on the "Search" button?

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/2621 (tests only)
- https://github.com/pkp/pkp-lib/pull/5508

**Comment by asmecher** [comment]
@NateWr, would you mind taking a quick look at the PR above? Thanks!

**Comment by NateWr** [comment]
Looks good!
