### ISSUE TITLE
[OJS] Published After and Published Before filters in search have every year from 0 to 2020

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5483]
With the latest master branch OJS I publish an issue with articles and go to the advanced search.

The Published After and Published Before filters in search have every year from 0 to 2020.

<img width="836" alt="Screen Shot 2020-02-06 at 20 06 08" src="https://user-images.githubusercontent.com/16347527/73965077-2791cd00-491c-11ea-9611-f8120db4f9cb.png">

**Comment by asmecher** [comment]
It appears that `PKPPublicationQueryBuilder::getDateBoundaries` is not working.

**Comment by ajnyga** [comment]
@asmecher, fix for this:

lib: https://github.com/pkp/pkp-lib/pull/5492
ojs: https://github.com/pkp/ojs/pull/2614 (just submodule)

**Comment by NateWr** [comment]
Thanks!
