### ISSUE TITLE
[OHS] Records are missing the datestamp field. 

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#5490]
Describe the bug
After harvesting an archive, the datestamp column of the records remain empty.

To Reproduce
Harvest any archive

What application are you using?
OHS 2.3
PHP 7.1

**Comment by jonasraoni** [comment]
PR: https://github.com/pkp/harvester/pull/24

**Comment by asmecher** [comment]
Thanks, @jonasraoni!
