### ISSUE TITLE
[OHS] Navigation performance

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#5495]
Describe the bug
The Harvester is taking too long to process some listings when the instance has many archives, especially when not using SSD disks.

What application are you using?
OHS 2.3
PHP 7.1

**Comment by ainulrafiq** [comment]
Dear @jonasraoni , I am new to use the OHS 2.3, PHP 5.6. Since installing the system, it is passed 5 hours and the archives still 0 records. I checking the error log, but there is no mention about this.

Let's sharing.

Thank you!

Regards,
Rafiq

**Comment by jonasraoni** [comment]
Hi @ainulrafiq!

I've been testing it against PHP 7.2 - 7.4 and MySQL 5.7 it worked fine. So, considering there's no issues in your setup, maybe the archive you're trying to index is faulty or timing out (I've added some extra things to the code, to help monitoring errors and also to setup the timeouts, but I'm unable to merge at this moment).

You can try to run the command below in the console to see the output/errors:
```php
php PATH_TO_HARVESTER/tools/harvest.php all from=last
```
