### ISSUE TITLE
Upgrading process returning error on getFileId

### ISSUE THREAD

**Issue by AndreLZGava** [pkp/pkp-lib#5496]
**Describe the bug**
I'm facing problem to migrate my OJS from 2.4.8-5 to 3.1.4-x 
Its always returning error on getFileId

**To Reproduce**
I believe that its caused by an corrupted file, or something in my database, but the system must deal with it.
1. Copy database from original OJS and install it on another server
2. Copy OJS 3.1.4 files to your server/computer
3. try to install it

**What application are you using?**
 OJS 2.4.8-5

**Additional information**
Here you will find more details about my issue.

https://forum.pkp.sfu.ca/t/ojs-migrate-from-2-4-8-5-to-any-verson-on-3-x-x-returning-error-php-fatal-error-uncaught-error-call-to-a-member-function-getfileid-on-null-in/58427

**Comment by asmecher** [comment]
@AndreLZGava, let's work on this in the forum rather than posting it to two places. You'll reach the same team either way.
