### ISSUE TITLE
[OJS] Disabled journals exposed in site-wide OAI

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#550]
Hi!

Journals that are not enabled to appear publicly on the site are still exposed in the site-wide OAI (index/oai). My suggestion is that sets from journals that are not enabled should not be exposed for harvesting here, which will reduce confusion in the case of site-wide metadata collection. If there is a need for harvesting data from journals that are not enabled, the per journal OAI interface should be enough.

Best,
Martin

**Comment by asmecher** [comment]
Hi @martinpub -- What version of OJS are you running? This should've already been fixed by...
http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=6733

**Comment by martinpub** [comment]
I see. But we're on 2.4.6, so we should have the fix.

**Comment by asmecher** [comment]
Hmm, interesting; would it be possible for you to (privately) send me a DB dump, and the OAI URL you're using to fetch content from the disabled journal?

**Comment by martinpub** [comment]
Perhaps it's only the sets that are exposed, but no records? I will get back to you later this week, can't test right now.

**Comment by martinpub** [comment]
Hi again! Sets from journals not enabled show up, but I can't find a case of a record that is exposed. Is displaying the sets of disabled journals in the site-wide OAI intentional?

**Comment by asmecher** [comment]
No, that sounds like a bug. I'll take a look; it should be a relatively easy fix. Thanks for tracking this down.

**Comment by asmecher** [comment]
Sure enough, it's a pretty trivial fix. @martinpub, could you give this a quick test?
https://github.com/pkp/ojs/pull/516

**Comment by martinpub** [comment]
Thanks @asmecher, it did the trick!

**Comment by asmecher** [comment]
Thanks -- ported to various other branches.
