### ISSUE TITLE
[OJS] Clean special characters from journal acronym when used in DOI suffix

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5505]
Hi,

The DOI plugin allows you to use `%j` in the DOI suffix pattern, which means the journal `acronym`.

This journal metadata field can contain characters like `&`. However, for exampe Crossref does not allow such characters in the DOI suffix.

Solution: always clean all special characters from `%j` if it is used in the DOI suffix pattern.  

@AhemNason @jmacgreg I can do a pr, if you give a go ahead on this.

@NateWr this probably needs work also in vue stuff?

**Comment by NateWr** [comment]
I don't _think_ this needs work in Vue.js. The context initials are passed into `FieldPubId` and should be cleaned before they are passed: https://github.com/pkp/ojs/blob/master/plugins/pubIds/doi/DOIPubIdPlugin.inc.php#L427

**Comment by ajnyga** [comment]
Great, that makes it easy then. Once Mike and James react I will do a pr on this.

**Comment by ajnyga** [comment]
Thinking of using: `$str = PKPString::regexp_replace('/[^A-Za-z0-9]/', "\n", $str);`

**Comment by jmacgreg** [comment]
This sounds fine to me. Happy to test if/when there's a PR.

**Comment by ajnyga** [comment]
Tests running: https://github.com/pkp/ojs/pull/2620 (and going to sleep...)

**Comment by NateWr** [comment]
@asmecher this looks good to me but do you mind double-checking that regex for me? PR in comment above.

**Comment by AhemNason** [comment]
Looks good to me!

**Comment by NateWr** [comment]
@ajnyga I notice there's a submodule commit on that PR but I don't see a lib/pkp PR. Are there any changes needed for lib/pkp?

**Comment by ajnyga** [comment]
none needed, I was under the impression that a submodule update was needed to start the tests, but I was wrong?

**Comment by NateWr** [comment]
Merged, thanks!

**Comment by jmacgreg** [comment]
Tested - works a-ok! One minor note for a future documentation revision - it might be worth changing the statement, in the DOI Plugin setup page, from "Use %j for journal initials" to "Use %j for journal initials (note that special characters such as '&', '$' etc. will be automatically removed)". Not necessary for now though, especially given the locale freeze.
