### ISSUE TITLE
Users registration for non-displayed journals

### ISSUE THREAD

**Issue by Varachkina** [pkp/pkp-lib#5506]
https://forum.pkp.sfu.ca/t/ojs-3-1-2-user-registration-impossible-if-a-journal-is-not-on-the-site/58315
We have a multi-journal instance. One of the journals is a showcase.
Users who want to register for another journal cannot do that if its presence on the site is not enabled: "Administration > Hosted Journals > JOURNALNAME Edit > Enable this journal to appear publicly on the site (ticked). It would be great if this were possible.

**Comment by asmecher** [comment]
@Varachkina, let's keep this conversation in the forum. If someone isn't responding to a post, feel free to reply with a reminder on the existing thread.
