### ISSUE TITLE
[OJS] Months with 4 or less letters in ABNT citations are handled incorrectly

### ISSUE THREAD

**Issue by gpieri** [pkp/pkp-lib#551]
According to ABNT specs, months with four or less letters should not be abbreviated.

The current implementation in OJS alway abbreviates the month.

Example:
- Correct text for may: "maio"
- Incorrect text for may: "mai."

**Comment by gpieri** [comment]
Hi, @asmecher. I've updated the PR with your suggestions. 

If there are any improvements left to be done that you feel important, let me know.


Best Regards
Giovani

**Comment by asmecher** [comment]
Thanks, @gpieri. Just a couple of minor comments this time.

**Comment by gpieri** [comment]
Nice, @asmecher. I'm waiting for your comments in order to improve the PR and have it merged.

Thanks,
Giovani

**Comment by asmecher** [comment]
I've added everything I could spot -- once you've pushed up changes to those, I'll be ready to merge it in for OJS 2.4.6-1. Thanks again!

**Comment by gpieri** [comment]
@asmecher, I've updated the PR with the changes you proposed! Thanks for the feedback.

**Comment by asmecher** [comment]
Merged! Thanks for contributing, @gpieri.

**Comment by asmecher** [comment]
(Also cherry-picked forward to master)
