### ISSUE TITLE
Add a ##section.policy## for Italian translation (missing string)

### ISSUE THREAD

**Issue by leonardomancini87** [pkp/pkp-lib#5513]
Hi everyone, 

I am writing here in order to ask if it is possible to add a string ##section.policy## in the locale/it_IT/locale.xml
At the moment it is missing. The Italian translation would be "Politiche delle sezioni". 
Thank you very much
Leonardo

ps.: here is a link to the forum: https://forum.pkp.sfu.ca/t/section-policy-missing-translation-cant-find-where-to-add-edit-it/58635

**Comment by asmecher** [comment]
@leonardomancini87, have a look at https://pkp.sfu.ca/2020/01/22/introducing-weblate-a-new-path-for-ojs-omp-translations/ for information on contributing translations. Checking the recent translation contributions, that key has already been translated and will be released with OJS 3.2.
