### ISSUE TITLE
[OJS] Error when changing time range in article statistics

### ISSUE THREAD

**Issue by GrazingScientist** [pkp/pkp-lib#5520]
**Describe the bug**
When going to Statistics -> Articles in the backend, the statistics for the previous 30 days is generated and shown. However, when I want to change the time range, this gives me the error message.

> An unexpected error has occurred. Please reload the page and try again.

When checking the logs, it shows this:

> PHP Fatal error:  Uncaught RuntimeException: Unexpected data in output buffer. Maybe you have characters before an opening <?php tag? in /srv/www/htdocs/journals/testling-3114/lib/pkp/lib/vendor/slim/slim/Slim/App.php:621\nStack trace:\n#0 /srv/www/htdocs/journals/testling-3114/lib/pkp/lib/vendor/slim/slim/Slim/App.php(317): Slim\\App->finalize(Object(APIResponse))\n#1 /srv/www/htdocs/journals/testling-3114/lib/pkp/classes/core/APIRouter.inc.php(109): Slim\\App->run()\n#2 /srv/www/htdocs/journals/testling-3114/lib/pkp/classes/core/Dispatcher.inc.php(134): APIRouter->route(Object(Request))\n#3 /srv/www/htdocs/journals/testling-3114/lib/pkp/classes/core/PKPApplication.inc.php(252): Dispatcher->dispatch(Object(Request))\n#4 /srv/www/htdocs/journals/testling-3114/index.php(68): PKPApplication->execute()\n#5 {main}\n  thrown in /srv/www/htdocs/journals/testling-3114/lib/pkp/lib/vendor/slim/slim/Slim/App.php on line 621

**What application are you using?**
OJS 3.1.2-4

**Comment by NateWr** [comment]
I was unable to replicate this with the latest `stable-3_1_2` branch. @GrazingScientist do you have a sample database (preferably not a live one) that you could share with us to try to reproduce this?

**Comment by GrazingScientist** [comment]
Thank you @NateWr,
I just realized that this was probably an issue with too few (or none) datapoints in the database. Could this be the case? Otherwise, it may be the problem that my test journal is behind a login wall.... :/

**Comment by NateWr** [comment]
Seems likely. Given the error message, it may be that you have PHP notices/warnings printing to the screen (rather than logged quietly).
