### ISSUE TITLE
Link in journal health report task notification may be wrong

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5522]
**Describe the bug**
A scheduled task will create a task in the dropdown tasks for journal managers which says "This is a kind reminder for you to check your journal's health through the editorial report." The link leads to `/stats/editorialReport` but it should be `/stats/editorial`.

This may have already been fixed, or maybe only in the email template. This needs to be checked. 

**To Reproduce**
I'm not exactly sure of the reproduction steps but I think a scheduled task creates the notification for journal managers and journal editors.

**What application are you using?**
 OJS or OMP version 3.2 pre-release

**Additional information**
![Selection_217](https://user-images.githubusercontent.com/2306629/74768267-2ea3ce00-5280-11ea-8f8f-69721d789f9d.png)

**Comment by asmecher** [comment]
(This was a trivial fix.)
