### ISSUE TITLE
Custom Block Plugin upgrade 2.x to 3.x leaves invalid block contexts

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#5523]
**Describe the bug**
The upgrade from 2.x to 3.x does not modify the block context of custom blocks, leaving them orphaned if they existed in `BLOCK_CONTEXT_RIGHT_SIDEBAR` or `BLOCK_CONTEXT_HOMEPAGE`

**To Reproduce**
1. Add custom blocks to a context other than the left sidebar in OJS 2.x
2. Upgrade to OJS 3.1.2
3. Navigate to Website Settings -> Appearance
4. Custom blocks to not appear in the Sidebar or Unselected section of Sidebar Management. 

**What application are you using?**
 OJS 3.1.2

**Additional information**
Original contexts were:
https://github.com/pkp/pkp-lib/blob/097e08e6d06698999eaa270e6e1ae456e1d5a22c/classes/plugins/BlockPlugin.inc.php#L16-L18
Contexts for 3.1.2 were:
https://github.com/pkp/pkp-lib/blob/957d926b7c1d5066de141085b7da8b0c88d4287e/classes/plugins/BlockPlugin.inc.php#L16-L17
But, only `BLOCK_CONTEXT_SIDEBAR` is considered:
https://github.com/pkp/pkp-lib/blob/957d926b7c1d5066de141085b7da8b0c88d4287e/controllers/listbuilder/settings/BlockPluginsListbuilderHandler.inc.php#L89-L91
But then this constant is entirely removed in 3.2:
https://github.com/pkp/pkp-lib/commit/a76bac72ed068a1d1866398d20cdf28c4977249f#diff-70caff5ef9a513397af1833a3e2a3c7c

**Comment by ctgraham** [comment]
Other blocks are handled here:
https://github.com/pkp/ojs/blob/a4768a0a5c7cf12618574eefdb7557f8c38ebc29/dbscripts/xml/upgrade/3.1.0_update.xml#L20-L22

**Comment by asmecher** [comment]
@ctgraham, forgive me for losing track of this one -- what is the status of the open PRs linked here?

**Comment by ctgraham** [comment]
Heh.  I was just looking for that horrible `installFilters` hijack yesterday.  There it is.

I think these are still good for merge.  `stable-3_1_2` is releasable as 1.3 for 3.1.2, and `master` is releasable as 1.3.1 for 3.2.  I haven't actually run the plugin in 3.2, though.

**Comment by asmecher** [comment]
I've added Travis tests to `stable-3_2_1` and `master` branches of the custom block plugin, and will now start looking at the PRs for the `stable-3_2_1` branch, thanks!

**Comment by asmecher** [comment]
With apologies, @ctgraham, I'm deferring this yet again -- I'm about to release 3.2.1-3 on more urgent matters and don't want to bring in a large last-minute merge. My fault!

**Comment by asmecher** [comment]
After many deferrals -- and with apologies to @ctgraham, who put a lot of thought and effort into this -- I'm going to close this issue. We removed the 2.x to 3.x upgrade toolset with the release of 3.3.0, so this would need to be fixed in 3.2.x or older, which we're not actively maintaining. For anyone encountering this issue, there is a proposed fix in https://github.com/pkp/customBlockManager/pull/61.
