### ISSUE TITLE
Category nesting not reflected in submission form, OJS

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#5525]
The Categories feature recently introduced in OJS 3.1.2 allows nesting categories under a parent category. The nesting structure is visible in the Workflow settings as well as in the front-end when categories are displayed publicly.

![image](https://user-images.githubusercontent.com/45104797/74800748-74718e00-52a2-11ea-89a1-1c75079aab66.png)

However the list of categories in submission metadata presented to the author is flat:

![image](https://user-images.githubusercontent.com/45104797/74800710-560b9280-52a2-11ea-8811-aea24fd54b4d.png)

This makes for a confusing selection, particularly where category lists are long or have multiple children.

It will make sense for the nesting structure to be reflected in the submission form.

The issue is reported by PKP|PS.

**Comment by asmecher** [comment]
@NateWr, this would just require adding a class to the `ListPanelItem` depending on whether it had a parent category ID -- but I don't see any way in a `ListPanelItem` to add a class and there must be another use case for something similar in the codebase. Anything come to mind?

**Comment by NateWr** [comment]
This also effects the category selection after submission is completed, but there we use a `FieldOptions`. The `ListPanel` here is a bit of a hack to weave the new in with the old.

I can think of ways to address this visually but I'm not sure about accessibility -- how would someone using a screenreader understand which categories are nested? One fairly easy way around this for now would be to prepend the parent category, like:

> - [ ] Peer reviewed
> - [ ] Peer reviewed > Open
> - [ ] Peer reviewed > Anonymous

I think this is a pretty good solution for now and maybe after 3.2 I can do some research on how to express hierarchy semantically in checkbox lists...

**Comment by NateWr** [comment]
PRs with the simple suggestion above:
https://github.com/pkp/pkp-lib/pull/5535
https://github.com/pkp/ojs/pull/2632
https://github.com/pkp/omp/pull/768

**Comment by NateWr** [comment]
Merged!
