### ISSUE TITLE
Selected value not loaded in Vue FieldOptions component

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5526]
In Vue based forms preselecting a value is not working with the FieldOptions component.

A working fix is to add 
```
		value(newVal, oldVal) {
			if (newVal !== oldVal) {
				this.selectedValue = this.isMultilingual
					? this.value[this.localeKey]
					: this.value
			}
		},
```
after https://github.com/pkp/ui-library/blob/master/src/components/Form/fields/FieldOptions.vue#L208

**Comment by NateWr** [comment]
Assigning this to 3.2 because it will be a pre-requisite for work @ajnyga is doing on the OPS beta.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ui-library/pull/67

Tests:
https://github.com/pkp/ojs/pull/2631
