### ISSUE TITLE
Editors fail to schedule for publication

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5532]
**Describe the problem you would like to solve**
In UX tests of the new publication/versioning workflow, several users assigned a publication to an issue and saved the form, but failed to schedule the article for publication.

Users will quickly learn that they need to schedule a submission for publication because it is not archived or published in an issue until that happens. However, it would be good to make this more intuitive.

**Describe the solution you'd like**
@israelcefrin and I discussed a few ideas:

1. Add another button beside the save button for each form that says "Save and Schedule for Publication".
2. After a publication is assigned to an issue (the issue form is saved with a selected issue) a prompt could appear asking if they want to schedule for publication.
3. Move the Save buttons for each form up next to the Schedule for Publication button. The risk here is that some data (like authors and galleys) is saved without ever clicking the save button, so there would be inconsistency regarding when data is saved.

**Who is asking for this feature?**
Editors and editorial managers.

**Comment by NateWr** [comment]
I thought of a fourth option: replace the Issue select field with a button to schedule for publication, and put the issue selection into the Schedule for Publication form. This would look like this:

![Selection_254](https://user-images.githubusercontent.com/2306629/77062597-184e7680-69d4-11ea-8557-b9e297ec6ec0.png)

This would take some reworking of the PublishForm, because we need to be able to tell users that it will be published immediately when they select a Back Issue. But I don't think it would be too much work.

@israelcefrin what do you think about this idea?

**Comment by israelcefrin** [comment]
Hi @NateWr  I think it is more friendly. Also, it streamlines the publishing process. The immediate publishing for back issues can be managed with an embedded instruction AND a warning like a double-checking flow. 

My only concern is to have or show two buttons with the same label.  But we can think whether we should adapt it. Since, this second button has 2 functions: **schedule** for future issue OR **immediate publishing** to past issue.

**Comment by NateWr** [comment]
This required a little bit of technical hoop-jumping because we're juggling the old modals and the new form system. As a temporary solution I have gone with a two-step process where the user assigns a publication to an issue and is then presented with the publish confirmation UI.

This works from the main Schedule for Publication button.
![schedule-for-publication](https://user-images.githubusercontent.com/2306629/82344614-2dec1680-99ec-11ea-8d4f-33905405af65.gif)

It follows the same workflow if they click the Assign to Issue button from the issue form. If the publication is already assigned to an issue and they click the Schedule for Publication button it will skip the issue selection and go straight to the publish confirmation UI.

@israelcefrin do you think this addresses the concern raised during the UX tests?

v3.3 will introduce Vue.js modals and it will be easier to design a smoother workflow, without modals opening/closing. I've made a note in #5865 to improve this workflow.

The following PRs also address #5631 and #5306 

PRs:
https://github.com/pkp/ui-library/pull/90
https://github.com/pkp/ojs/pull/2756

**Comment by israelcefrin** [comment]
Hi @NateWr I think it manages our initial concern since it is setting a step-by-step process for scheduling. User will be presented with mandatory tasks in a friendly way.

**Comment by NateWr** [comment]
Merged!
