### ISSUE TITLE
Unclear language for setting to allow participants to edit metadata

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5533]
**Describe the problem you would like to solve**
During UX testing, users were confused about the setting which allows an editor to grant or revoke someone's permission to edit a submission's metadata. 

**Describe the solution you'd like**
Better language could be written to make it clear what this setting does.

**Who is asking for this feature?**
Editors

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/5889

@israelcefrin not sure if you remember this, but it came up in the last round of UX testing. Here's the new description.

![edit-metadata](https://user-images.githubusercontent.com/2306629/82236619-4268da00-992c-11ea-9b0b-05097aa772e3.png)

Does that seem like a sufficient improvement?

**Comment by NateWr** [comment]
Merged.

**Comment by israelcefrin** [comment]
Hi @NateWr , apologize for not answering before. But just confirming, it seems suffice in deed.
