### ISSUE TITLE
Plugins/themes to package and release before 3.2

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5536]
The following plugins or themes should be packaged, released and added to the `plugins.xml` file before 3.2 is released.

| Name | Whose | Repository | Translations | Release | `plugins.xml` | Notes |
| --- | ---| --- | --- | --- | --- | --- |
| controlPublicFiles | @NateWr | Ready | 2020-03-02 | 1.0.0.0 | ✓ | |
| textEditorExtras | @NateWr | Ready | 2020-03-02 | 1.0.0.0 | ✓ | |
| browseBySection | @NateWr | Ready | N/A | | NOT FOR PLUGIN GALLERY | |
| paperbuzz | @NateWr | Ready | N/A | | [Release XML](https://github.com/pkp/pkp-lib/issues/5536#issuecomment-590833085) | |
| classic | @NateWr | Ready | N/A | 1.0.3 | ✓ | |
| immersion | @NateWr | Ready | N/A | 1.0.4 | ✓ | |
| healthSciences | @NateWr | Ready | N/A | 1.0.6 | ✓ | |
| bootstrap3 | @NateWr | Ready | N/A | 3.2.0.0 | ✓ | |
| defaultManuscript | @NateWr | Ready | N/A | 1.0.3 | ✓ | |
| hypothesis | @asmecher | Ready | 2020-02-27 | [v1.0.2-0](https://github.com/asmecher/hypothesis/releases/tag/v1.0.2-0) | ✓ | |
| shibboleth | @asmecher | | | | | |
| backup | @asmecher | Ready | 2020-02-27 | [v2.0.2-0](https://github.com/asmecher/backup/releases/tag/v2.0.2-0) | ✓ | |
| plagiarism | @asmecher | Ready | 2020-03-18 | [v1.0.3-0 | ✓ | |
| coins | @asmecher | Ready | 2020-02-27 | [v1.0.3-0](https://github.com/pkp/coins/releases/tag/v1.0.3-0) | ✓ | |
| quickSubmit | @asmecher | Ready | 2020-02-27 | [v1.0.5-0](https://github.com/pkp/quickSubmit/releases/tag/v1.0.5-0) | ✓ | |
| allowedUploads | @ajnyga  | Ready | N/A | [1.0.0.5](https://github.com/ajnyga/allowedUploads/releases/tag/1.0.0.5) | ✓ | |
| piwik | @asmecher | Ready | 2020-02-27 | [1.0.3.0](https://github.com/pkp/piwik/releases/tag/v1.0.3-0) | ✓ | |
| shariff | FU Berlin | | | | | |
| addThis | @asmecher | Ready but version.xml needs updating | 2020-02-27 | [1.0.3-0](https://github.com/pkp/addThis/releases/download/v1.0.3-0/addThis-v1.0.3-0.tar.gz) | ✓ | |
| Copernicus | Third party | | | | | |
| subscriptionSSO | @asmecher | | | | | |
| funding | @ajnyga  | Ready | N/A | | ✓ | |
| customHeader | @asmecher | Ready | 2020-02-27 | [v1.0.2-0](https://github.com/asmecher/customHeader/releases/tag/v1.0.2-0) | ✓ | |
| jatsTemplate | @asmecher | Ready | 2020-02-27 | [v1.0.2-0](https://github.com/pkp/jatsTemplate/releases/tag/v1.0.2-0) | ✓ | |
| sword | @quoideneuf  | Ready | 2020-03-18 | 1.0.2-1 | ✓ | |
| oaiJats | @asmecher | Ready | 2020-02-27 | [v1.0.2-0](https://github.com/pkp/oaiJats/releases/tag/v1.0.2-0) | ✓ | |
| ojs3-keywordcloud-plugin | Third party | | | | | |
| texture | @withanage  | Ready | | 2.2.1.0 and 2.2.2.0 | ✓ |  |
| crossrefReferenceLinking | @asmecher | | | | | |
| orcidProfile | @asmecher | Ready | 2020-02-27 | [v1.1.2-0](https://github.com/pkp/orcidProfile/releases/tag/v1.1.2-0) | Added | OJS and OPS compatible (what about OMP?) |
| defaultTranslation | @asmecher | Ready | 2020-02-27 | [v1.1.1-0](https://github.com/pkp/defaultTranslation/releases/tag/v1.1.1-0) | ✓ | |
| openAIRE | @ajnyga  | | | | ✓ | |
| lensGalleyBits | @withanage  | | | | | |
| reviewercredits-ojs | Third party | | | | | |
| ojs-plum-plugin | @ctgraham | | | | | |
| ojs-sushiLite-plugin | @ctgraham | | | | | |
| pkp-betterPassword | @ctgraham | | | | | |
| pkp-akismet | @ctgraham | | | | | |
| pkp-formHoneypot | @ctgraham | | | | | |
| authorRequirements | @ewhanson | Ready | | [1.0.0-1](https://github.com/ewhanson/authorRequirements/releases/tag/v1.0.0-1) | [XML](https://github.com/pkp/pkp-lib/issues/5536#issuecomment-591526050) ✓ | |
| registrationNotification | @asmecher | | | | | |

**Comment by NateWr** [comment]
Base XML for the `controlPublicFiles` plugin.

```xml
	<plugin category="generic" product="controlPublicFiles">
		<name locale="en_US">Control Public Files</name>
		<homepage>https://github.com/pkp/controlPublicFiles</homepage>
		<summary locale="en_US">Limit who can upload public files and what kind of files they can upload.</summary>
		<description locale="en_US"><![CDATA[
			<p>Users can upload images wherever they are presented with a rich text editor that includes the image upload control. This includes places like the About the Journal section as well as the user biography in every user's profile area.</p>
			<p>This plugin provides settings to restrict who can upload, what kind of files they can upload, and how large their directory of files can grow.</p>
		]]></description>
		<maintainer>
			<name>Public Knowledge Project</name>
			<institution>Public Knowledge Project</institution>
			<email>pkp.contact@sfu.ca</email>
		</maintainer>
		<release date="2020-02-27" version="1.0.0.0" md5="[INSERT]">
			<package>[INSERT]</package>
			<compatibility application="ojs2">
				<version>3.2.0.0</version>
			</compatibility>
			<compatibility application="omp">
				<version>3.2.0.0</version>
			</compatibility>
			<certification type="official" />
			<description>Initial release for OJS/OMP v3.2.</description>
		</release>
	</plugin>
```

**Comment by NateWr** [comment]
Base XML for the `textEditorExtras` plugin.

```xml
	<plugin category="generic" product="textEditorExtras">
		<name locale="en_US">Text Editor Extras</name>
		<homepage>https://github.com/pkp/textEditorExtras</homepage>
		<summary locale="en_US">Add controls to the rich text editor to upload images, manipulate the HTML code, and add tables.</summary>
		<description locale="en_US"><![CDATA[
			<p>This plugin provides settings to turn on extra controls for the rich text editor and to specify which fields should receive the additional controls.</p>
		]]></description>
		<maintainer>
			<name>Public Knowledge Project</name>
			<institution>Public Knowledge Project</institution>
			<email>pkp.contact@sfu.ca</email>
		</maintainer>
		<release date="2020-02-27" version="1.0.0.0" md5="[INSERT]">
			<package>[INSERT]</package>
			<compatibility application="ojs2">
				<version>3.2.0.0</version>
			</compatibility>
			<compatibility application="omp">
				<version>3.2.0.0</version>
			</compatibility>
			<certification type="official" />
			<description>Initial release for OJS/OMP v3.2.</description>
		</release>
	</plugin>
```

**Comment by NateWr** [comment]
Additional XML for `paperbuzz` release.

```xml
		<release date="2020-02-27" version="1.0.2.0" md5="[INSERT]">
			<package>[INSERT]</package>
			<compatibility application="ojs2">
				<version>3.2.0.0</version>
			</compatibility>
			<certification type="official"/>
			<description>Update for compatibility with OJS v3.2.</description>
		</release>
```

**Comment by NateWr** [comment]
Release XML for `classic`, `immersion`, `healthSciences`, `boostrap3` and `defaultManuscript` themes.

```xml
		<release date="2020-02-27" version="1.0.3.0" md5="[INSERT]">
			<package>[INSERT]</package>
			<compatibility application="ojs2">
				<version>3.2.0.0</version>
			</compatibility>
			<certification type="official" />
			<description>Update theme to support multiple article versions in OJS v3.2.</description>
		</release>
```

**Comment by ajnyga** [comment]
Release XML for `allowedUploads`.

```
<release date="2020-03-25" version="1.0.0.5" md5="f518e21a670df0ae612b3d15a1c49f59">
<package>https://github.com/ajnyga/allowedUploads/releases/download/1.0.0.5/allowedUploads.tar.gz
	</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
	</compatibility>
	<compatibility application="omp">
		<version>3.2.0.0</version>
	</compatibility>
	<compatibility application="ops">
		<version>3.2.0.0</version>
	</compatibility>
	<certification type="reviewed"/>
	<description>Allowed Uploads plugin for 3.2.</description>
</release>
```

**Comment by ajnyga** [comment]
How about https://github.com/pkp/citationStyleLanguage

**Comment by asmecher** [comment]
> How about https://github.com/pkp/citationStyleLanguage

That's included in OJS as a submodule so it gets shipped in the OJS .tar.gz. So as long as it's been tested, it doesn't need to be packaged and distributed.

**Comment by Vitaliy-1** [comment]
HTML Article Galley, PDF.JS PDF Viewer, and Life Lens Article Viewer plugin also require an update because of the new article versioning feature, I mean viewing galleys of previous versions of published articles. I'm not sure if it's addressed somewhere.

**Comment by ewhanson** [comment]
Release XML for `authorRequirements`.

```xml
<plugin category="generic" product="authorRequirements">
	<name locale="en_US">Author Requirements</name>
	<homepage>https://github.com/ewhanson/authorRequirements</homepage>
	<summary locale="en_US">This plugin allows certain author fields to be made optional.</summary>
	<description locale="en_US">The plugin makes it possible to add an author to a list of contributors without using certain requried fields (e.g. email). This is useful in cases where required information does not exist for authors.</description>
	<maintainer>
		<name>Erik Hanson</name>
		<institution>Public Knowledge Project</institution>
		<email>hansonew@gmail.com</email>
	</maintainer>
	<release date="2020-02-26" version="1.0.0-1" md5="b4678522339100227e2a2770f7041e08">
		<package>https://github.com/ewhanson/authorRequirements/releases/download/v1.0.0-1/authorRequirements-1.0.0-1.tar.gz</package>
		<compatibility application="ojs2">
			<version>3.2.0.0</version>
		</compatibility>
		<certification type="partner"/>
		<description>Release of the authorRequirements plugin for OJS/OMP 3.2.0</description>
	</release>
</plugin>
```

**Comment by asmecher** [comment]
@Vitaliy-1, are you just flagging those for checking, or have you observed an issue with them?

**Comment by Vitaliy-1** [comment]
@asmecher, sorry, yes, I observed an issue while testing themes. 
If an article has several versions, it can be viewed from a front-end on the article landing page. In this case, URL will have additionally `.../version/versionId`. If this older version has galleys, when trying to view them, it redirects to `.../version/versionId/galleyId`, where I see only empty iframe with no found message. I think those plugins weren't modified to handle this request.  
I've tested it on yesterday's master branch with the Default theme.

**Comment by Vitaliy-1** [comment]
@asmecher, sorry, yes, I observed an issue while testing themes. 
If an article has several versions, it can be viewed from a front-end on the article landing page. In this case, URL will have additionally `.../version/versionId`. If this older version has galleys, when trying to view them, it redirects to `.../version/versionId/galleyId`, where I see only empty iframe with no found message. I think those plugins weren't modified to handle this request.  
I've tested it on yesterday's master branch with the Default theme.

**Comment by ajnyga** [comment]
<release date="2020-02-27" version="2.1.3.0" md5="c0da8298261b602bfeb093cbc3e788e6">
	<package>https://github.com/ajnyga/funding/releases/download/2.1.3.0/funding.tar.gz</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
	</compatibility>
	<compatibility application="omp">
		<version>3.2.0.0</version>
	</compatibility>
	<certification type="reviewed"/>
	<description>Update for compatibility with v3.2.</description>
</release>

**Comment by ajnyga** [comment]
note https://github.com/pkp/pkp-lib/issues/5536#issuecomment-590852768 had the wrong date before, I corrected it here but needs to be checked in the xml file as well.

**Comment by asmecher** [comment]
Thanks, all, I'll start wrapping up plugins and adding all this stuff to the XML today to clear the decks for OJS/OMP/OPS tomorrow.

**Comment by ajnyga** [comment]
New Funding version:

```
<release date="2020-02-27" version="2.1.3.1" md5="a6bda6d071894aa276116507e1d01345">
	<package>https://github.com/ajnyga/funding/releases/download/2.1.3.1/funding.tar.gz</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
	</compatibility>
	<compatibility application="omp">
		<version>3.2.0.0</version>
	</compatibility>
	<certification type="reviewed"/>
	<description>Update for compatibility with v3.2.</description>
</release>
```

**Comment by ajnyga** [comment]
New version for `OpenAIRE`. Still using some deprecated methods, but will get rid of those soon.

```
<release date="2020-02-27" version="2.0.2.0" md5="e96c552aefb633aea32a181c3bd29eac">
<package>https://github.com/ojsde/openAIRE/releases/download/2.0.2.0/openAIRE.tar.gz</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
	</compatibility>
	<certification type="reviewed"/>
	<description>Update for compatibility with v3.2.</description>
</release>
```

**Comment by asmecher** [comment]
@ewhanson, I've added your XML per https://github.com/pkp/pkp-lib/issues/5536#issuecomment-591526050 but noticed that it doesn't specify compatibility with OMP. Shall I add that?

**Comment by asmecher** [comment]
All the above XML has been reviewed and added *except*...
- controlPublicFiles: https://github.com/pkp/pkp-lib/issues/5536#issuecomment-590830258 still needs package details filled in
- textEditorExtras: https://github.com/pkp/pkp-lib/issues/5536#issuecomment-590831846 still needs package details filled in
- paperbuzz: https://github.com/pkp/pkp-lib/issues/5536#issuecomment-590833085 needs package details filled in
- classic, immersion, healthSciences, boostrap3 and defaultManuscript: https://github.com/pkp/pkp-lib/issues/5536#issuecomment-590834708 needs release details filled in

**Comment by ewhanson** [comment]
@asmecher, Yes OMP should be included. Thanks.

**Comment by asmecher** [comment]
Added OMP compatibility statements for `authorRequirements` for both releases, thanks!

**Comment by asmecher** [comment]
There are some leftovers for next week, most notably the themes.

**Comment by NateWr** [comment]
Themes went up last week. I've put `controlPublicFiles` and `textEditorExtras` up this morning.

**Comment by asmecher** [comment]
Moved shibboleth, subscriptionSSO, crossrefReferenceLinking, registrationNotification, and lensGalleyBits to https://github.com/pkp/pkp-lib/issues/5578; the rest are third-party maintenance. Closing this issue.
