### ISSUE TITLE
Submission::getViews() method missing

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5537]
It seems that we used to have a `getViews` method for submissions which showed the number of abstract page hits for that submission.

It is still used here: https://github.com/pkp/ojs/blob/master/plugins/reports/views/ViewReportPlugin.inc.php#L80

However, it seems that the whole method is missing: `PHP Fatal error:  Uncaught Error: Call to undefined method Submission::getViews()`

**Comment by asmecher** [comment]
Re-added that helper to `PKPSubmission`.
