### ISSUE TITLE
Add ISSN field to series setup in OMP

### ISSUE THREAD

**Issue by summerhayss** [pkp/pkp-lib#554]
Monographs on our instance of OMP (Open SI) are all volumes in assigned "series" (Smithsonian Contributions to Zoology, Contributions to Botany, etc.). These series all have ISSNs--essentially, serial numbers that identify the series and link all the publications in a single series together. Also, all of our series (Contributions to Zoology, Contributions to Botany, etc.) have two ISSNs: one for the print edition and one for the PDF/digital edition. This is very normal, since ISSNs are assigned to periodicals based on format (print, digital, etc.).

ISSNs are an important piece of metadata for our publications, so it should probably be a metadata field in the series setup pages (i.e., where we name the series and upload the “cover” image for the series). We’d like to be able to enter both the ISSNs (print and digital) for every series. We’d also like for the ISSNs to display as part of the metadata on the individual publication pages.

Also note that, any publications released in our series DON'T have ISBNs since they are part of a series with an assigned ISSN. Any of the books we publish through OMP that have ISBNs aren't published through one of our series and are therefore not going to have ISSNs.

**Comment by asmecher** [comment]
Also from SI: "Add wildcard for ISSN, so SISP may automate DOI assignment. SISP’s DOI pattern is “prefix + ISSN + vol/issue no."

**Comment by bozana** [comment]
@asmecher: if I understand it correctly, not all books will have an ISSN. If someone chooses a DOI suffix pattern that contain the ISSN, there could be a problem for the books that don't have it. Is there a way i.e. rule we could use to solve it? Or shall I ignore it at the moment and just consider the additional wildcard?

**Comment by asmecher** [comment]
Given that we're hitting a number of possible exceptions where information isn't entirely present, I think we'll probably have to make the DOI attachment/deposit process smart enough to know what to do when it's asked to assign a DOI when information is missing. The most logical behavior, I think, is to skip that item, continue with the rest of the batch, and notify somebody.

**Comment by bozana** [comment]
@asmecher, if OK, I would separate this issue into two steps:
1. add ISSNs fields for series + display
2. ISSN wildcard for pub id plugins
?

@NateWr, I added the online and print ISSN fields for the series and I currently display them on the catalog series page just behind the series description, in separate div elements, s:
![seriesissns](https://cloud.githubusercontent.com/assets/378421/12817074/655edc66-cb50-11e5-975f-98951ec8b297.png)

Is this OK, or should I display them somewhere else on that page?

Also, the requirement/wish above is to display them on the book page, if they exist. Would you like to tell me where and how?

Thanks!

**Comment by NateWr** [comment]
That's a good place for them @bozana. Can you ping me once the PR goes in and I can test it out and adjust as needed.

On the book page, I'd expect them to be listed alongside other pubIds or identifiers. Are the ISSN's included alongside the other stuff shown in the screenshots on this comment?

https://github.com/pkp/pkp-lib/issues/958#issuecomment-179246777

**Comment by bozana** [comment]
Hi @NateWr, they belong to a series i.e. would maybe be displayed where the series link is?

**Comment by NateWr** [comment]
Ah ok I've had a read over the ticket now. Is it right to hard-code an "online" and "print" ISSN? Shouldn't they instead be attached to pub formats if that's how they are assigned?

Seems like one more edge case for which we're adding very specific and inflexible code. What happens when someone comes along and says they have series ISSNs for PDF, ePub and hardback?

**Comment by asmecher** [comment]
@NateWr, these ISSNs are for series, not pub formats or submissions. For OMP, someone would normally assign an ISBN (B=book) to the book/chapter/etc., and an ISSN (S=serial) to the series.

**Comment by NateWr** [comment]
> Also, all of our series (Contributions to Zoology, Contributions to Botany, etc.) have two ISSNs: one for the print edition and one for the PDF/digital edition. This is very normal, since ISSNs are assigned to periodicals based on format (print, digital, etc.).

**Comment by mtub** [comment]
Great, a lengthy ISSN discussion :).

IMHO, there are two things to consider:

1. a series that is published in printed form and electronically needs (as in 'required') two ISSNs
2. a series published in different electronic formats (HTML, EPUB...) does not need (as in 'should refrain from doing so') different ISSNs for those publication formats

So having a print and an electronic ISSN sound about right to me.


Further reading:

> If your electronic publication is a version of an existing printed publication, it must have its own ISSN, even if the title is identical.
(http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-for-electronic-media/)

> The same ISSN must be used irrespective of the formats your publication is distributed in (HTML, PDF, etc.).
(http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-for-electronic-media/)

If a publisher wants to dig into the whole ISSN business, there's also the 'linking ISSN' (ISSN-L):

> The linking ISSN, or ISSN-L, is a specific ISSN that groups the different media of the same serial publication.
(http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-l-for-publications-on-multiple-media/)

**Comment by NateWr** [comment]
Thanks @mtub! That clears up my confusion. If print and electronic are the only two formats ISSN requests then it makes sense to have them this way.

**Comment by bozana** [comment]
@NateWr, I inserted the ISSNs below the series link on the book page, s.:
![bookpageissns](https://cloud.githubusercontent.com/assets/378421/12848697/bc52a9c8-cc1b-11e5-902c-c3b11c6a5fc2.png)

If I can improve/change something, just tell me. Else, I've made a PR and you will maybe style it then differently... :-)

**Comment by mtub** [comment]
Hi @bozana, what do you think about displaying a warning to the user if the two ISSN numbers are the same?

**Comment by bozana** [comment]
@asmecher, do you maybe have an idea how to best proceed with the wildcards for the pub id plugins -- the intuitive letters are running out :-) I.e. what to take for ISSNs? %i would work for OMP, but maybe to take something that could be used in OJS too (%i stands there for issues)? Just to randomly take the next letter?
Should there be two place holders, one for the online and one for the print ISSN, or would just one be enough and we could say "take first the online ISSN, and if it doesn't exist, take the print ISSN"?
As far as I understand from the requirement above, the missing ISSN is not an error i.e. some books can have no ISSN. Thus, when resolving the pub id place holders and the ISSN is missing, maybe to just omit it? For example, if the DOI suffix pattern is %p.ISSN.%m.%f and the ISSN is missing the DOI, for example, would be 10.12345/press1.1.1, and when the ISSN is there then 10.12345/press1.1234-1234.1.1.
Above you wrote:
> SISP’s DOI pattern is “prefix + ISSN + vol/issue no."

Where do they use this pattern (OMP or OJS)? For what objects? It is not unique for the OMP books and/or for the OJS articles, right?
# THANKS!!!

**Comment by bozana** [comment]
@mtub, OK :-)

**Comment by mtub** [comment]
If you adapt this issue to talk about pub id plugins, I might as well continue to add comments to this issue ;) - I am quite skeptical of all these attempts to enable people to put some presumed meaning into their DOI generation. I understand that there are users' demands to have this, but let's not forget that the one important requirement for DOI generation is that it creates unique DOIs. It's important to be able to build your DOI from article or galley numbers, but we don't need variables for everything. Especially ISSN - the DOI generation pattern is configured on journal level - and the ISSN of a particular journal will probably stay the same for a very long time, so every journal manager who wants to increase the length of their DOIs by adding redundant code to it can do so by typing in (hard-code) their ISSN in the DOI generation pattern. Why the need to have a variable for this?

**Comment by bozana** [comment]
@mtub, I see, there is no ISSN wildcard need for OJS, but then for OMP, I suppose...

**Comment by mtub** [comment]
Ok, you got me. OMP is a different case. I tend to stand by my "I don't think it's necessary", but who am I to say sth like that ;)

**Comment by bozana** [comment]
Of course you can say that! ;-) I am also not sure, but Alec will surely know! :-)))

**Comment by asmecher** [comment]
We could also standardize the variables we're using that they are {$variableName} (as we do in email templates etc.) rather than the %x syntax, which isn't used anywhere else as far as I know.

**Comment by NateWr** [comment]
@bozana Looks good. There is an HTML markup pattern for including sub-sets of label/value pairs in the book details area:

https://github.com/pkp/omp/blob/master/templates/frontend/objects/monograph_full.tpl#L29-L39

If you use that pattern with `sub_item`, you should get the appropriate spacing in place for ISSN's.

I don't put them on the same line because labels can be very different lengths in different languages (I'm looking at you, Germans. :wink: ).

**Comment by bozana** [comment]
@NateWr, I changed it, now it looks like this:
![bookpageissns2](https://cloud.githubusercontent.com/assets/378421/12944902/74fa576a-cfea-11e5-9925-cd02d7431274.png)

If it is better now, I will make a new PR... :-)
THANKS!!!

**Comment by NateWr** [comment]
Looks great. :+1:

**Comment by asmecher** [comment]
Thanks, @bozana! All merged.
