### ISSUE TITLE
Show usage stats for galleys that are not full-text galleys

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5543]
- [x] consider ASSOC_TYPE_SUBMISSION_FILE_COUNTER_OTHER in the background/API
- [x] consider suppFileViews in UI

**Describe the problem you would like to solve**
Currently, the publication statistics UI shows article/monograph stats for the "Abstract", "File Views", "PDF", "HTML", "Other" and "Total".

![Selection_225](https://user-images.githubusercontent.com/2306629/75239022-d9087d80-57b9-11ea-8006-919f92b1d216.png)

However, these counts exclude any galleys that are not full-text galleys. Usage stats for these are stored under a different assoc type, `ASSOC_TYPE_SUBMISSION_FILE_COUNTER_OTHER`. These do not count towards the totals and are not shown anywhere.

**Describe the solution you'd like**
Since we collect these stats, it would be nice to show them for journals where such files exist. Many journals will never have any, though, so it would be good to not show a column for this if no such stats exist. 

A cached journal setting that updates each time that metrics are processed could be good for determining whether to show/hide the column. Or perhaps this is something that should only be shown on an individual article view, which we may implement some day for authors.

**Who is asking for this feature?**
No one.

**Comment by bozana** [comment]
This is done with the Issue https://github.com/pkp/pkp-lib/issues/6782. Thus closing.
