### ISSUE TITLE
[OMP] Apostrophe replaced by HTML code in breadcrumbs

### ISSUE THREAD

**Issue by racemochridhe** [pkp/pkp-lib#5547]
We're running the current version of OMP and just published a new book to our catalog. It is the first volume in a series, and the configuration of series is new to us. The name displays properly everywhere across our site (see image 1) except in the breadcrumbs on the series page (see image 2), where the apostrophe in the title is replaced by its HTML code (`&#039;`).

![image](https://user-images.githubusercontent.com/55748624/75280972-0530f800-57d4-11ea-959b-17a2f4365937.png)

![image](https://user-images.githubusercontent.com/55748624/75280689-8b007380-57d3-11ea-9a8c-fba862e89e95.png)

I haven't had any luck in finding the cause of this error yet, though I did notice that there was [another recent problem with breadcrumb display](https://github.com/NateWr/bootstrap3/issues/140) following accessibility updates. That was an error in displaying the hierarchy, however, and implicated Bootstrap 3, while our site is running on the default theme.

If anyone has experienced this, or has a suggestion of a lead toward a solution, we'd be very grateful.
![image](https://user-images.githubusercontent.com/55748624/75281017-1bd74f00-57d4-11ea-8357-36fa1f7c2317.png)

**Comment by asmecher** [comment]
To fix this, apply https://github.com/pkp/omp/commit/77b70fac0b842fc8c60a568e3c647b109236e580 to your installation. Thanks for reporting so clearly, @racemochridhe!
