### ISSUE TITLE
[OMP] Port OJS' XML Sitemap functionality to OMP

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#555]
OJS includes XML sitemap functionality (see eg. http://www.globalhealthaction.net/index.php/gha/sitemap). We've heard from Google Scholar that this would be useful to be included for OMP as well. I'm not sure how much work it would be to move over, but we should consider it. 

Further information on how the sitemap works can be found here: https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/docs/README-SITEMAP. Note that OJS, OMP etc. can't include all supported tags in the sitemap, as we can't automatically infer what they should be.

**Comment by asmecher** [comment]
@jmacgreg, I'm deferring this as an apparently low priority, but let me know if that would make someone particularly unhappy.

**Comment by jmacgreg** [comment]
Totally cool by me!

**Comment by bozana** [comment]
Because I have been working on the fixing the sitemap for OJS 3, s. https://github.com/pkp/pkp-lib/issues/3459, I could similarly add a sitemap to OMP now. However, if I accidentally miss an URL (because I am not aware of every one at the moment) would it be a problem?

**Comment by jmacgreg** [comment]
Less of a problem than OMP not having a site map. :-)

**Comment by bozana** [comment]
This issue is closely related to the https://github.com/pkp/pkp-lib/issues/3459, so I will list all PRs here and there:
PRs:
https://github.com/pkp/pkp-lib/pull/3463
https://github.com/pkp/ojs/pull/1869
https://github.com/pkp/pkp-lib/issues/3459
https://github.com/pkp/browseBySection/pull/7
