### ISSUE TITLE
[OJS 3.1.2-1] PubMed OtherAbstract tag

### ISSUE THREAD

**Issue by diegozmweb** [pkp/pkp-lib#5556]
Hi all:

I'm trying to add an adicional abstract in Spanish with <OtherAbstract Language="es"> tag but It breaks.

The lines what I trying to add are:

$spanishAbstract = PKPString::html2text($publication->getLocalizedData('abstract', 'es_ES');
$articleNode->appendChild($doc->createElement('OtherAbstract Language=\'es\'', $spanishAbstract ));

Regards

**Comment by asmecher** [comment]
Hi @diegozmweb -- are you reporting a bug in OJS, or are you looking for guidance in a modification? If you're looking for help with a modification, https://forum.pkp.sfu.ca/ is the best place to go.

**Comment by diegozmweb** [comment]
Hi @asmecher, yes, I trying to do a modification. I'll copy the message in forum.

Regards,
Diego

**Comment by diegozmweb** [comment]
Hi @asmecher , yes, I trying to do a modification. I'll copy the message in forum.

Regards,
Diego
