### ISSUE TITLE
Tasks scheduled hourly cannot have a frequency greater than 24 hours

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#556]
Scheduling a task to run every 25 hours should work with the following bit of XML:
```xml
<scheduled_tasks>
	<task class="plugins.generic.pln.classes.tasks.Depositor">
		<descr>Deposit content with the PLN</descr>
		<frequency hour="25"/>
		<arg>autoStage</arg>
	</task>
</scheduled_tasks>
```

`checkFrequency()` in the `ScheduledTaskHelper` class checks if a task has been run recently enough. To do that, it calls _isInRange(), and passes a date that is 24 hours in the past as `$cutoffTimestamp`. It should, in this case, check if the task has been run in the past 25 hours.

https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_6/classes/scheduledTask/ScheduledTaskHelper.inc.php#L109-L115

_isInRange() compares the last time the task was run against $cutoffTimestamp. No task can run with a frequency of more than 24 hours, because of this $cutoffTimestamp.

https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_6/classes/scheduledTask/ScheduledTaskHelper.inc.php#L231-L234

**Comment by asmecher** [comment]
Bruno, could you look at this and advise? I'm not sure this is the source of the failure of one journal to submit stuff to the PLN plugin at the moment.

**Comment by ubermichael** [comment]
I don't think this is related to the journal not submitting.

**Comment by asmecher** [comment]
@ubermichael, are you still tracking down the problem with the non-submitting journal? Just making sure it's not stalled between desks.

**Comment by ubermichael** [comment]
I've been away for a week, so haven't looked at it. I don't think the stalled journal is related to this - it seems like a problem in the pln plugin. The cron job is definitely firing, but the plugin isn't responding as it should.

**Comment by ubermichael** [comment]
A thought. Does <frequency hour="25"/> mean every 25 hours, or does it mean on the 25th hour of each day?

**Comment by beghelli** [comment]
@ubermichael Not sure if you're still looking into this, but just for the record, the number means the specific hour in the day. So you can't define anything outside the 0 to 23 range.
