### ISSUE TITLE
Files for old versions don't load

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5560]
**Describe the bug**
Attempts to load the files for galleys attached to old versions fail. This problem exists for downloads as well as files loaded by the PDF and HTML viewer plugins.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/2649
(looking into omp now)

**Comment by Vitaliy-1** [comment]
@NateWr, is it working for you? I'm testing it on the default before updating Classic theme accordingly but galleys aren't fetched. 

For the pdf viewer I get: 
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```
in the console. The url that fails is: `.../index.php/psp/article/download/127`; should have fileId at the end. 

For HTML I have:
```
.../journals/1//articles/127/submission/proof/127-1-969-1-10-20190417.html): failed to open stream: No such file or directory
```
Or is it just on my end?

**Comment by NateWr** [comment]
Make sure you have the latest commits from the master branch for
pdfjsviewer and that template cache is cleared. The version part of the URL
was added in to the templates.

**Comment by asmecher** [comment]
It seems to work for me. (Corrected an [accidental hook parameter change](https://github.com/ajnyga/ojs/commit/71b1c7b826f49eea3de1ad15b6f3194f789e01e9) in PreprintHandler -- but that wouldn't have caused 404s and is fixed now.)

**Comment by Vitaliy-1** [comment]
Looks like a false alarm, sorry. Regarding PDF viewer I have forgotten to pull 2 latest commits, as for HTML galley - probably something on my end. I've tested with new submission and it works well.
