### ISSUE TITLE
OJS 3.2.0 - OAI ListRecords causes PHP Fatal Error

### ISSUE THREAD

**Issue by epistemehealth** [pkp/pkp-lib#5573]
When we go to the OAI repository for our journal and click on 'ListRecords', we get a blank page. The OAI repository seems fine for "Identify", "ListSets", "ListMetadataFormats" and "ListIdentifiers".

We checked our PHP error logs (7.2.27) and we got the following message:

> PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getProperties() on null in /var/www/ojs/lib/pkp/plugins/oaiMetadataFormats/dc/PKPOAIMetadataFormat_DC.inc.php:31
> Stack trace:
> #0 /var/www/ojs/plugins/oaiMetadataFormats/dc/OAIMetadataFormat_DC.inc.php(28): PKPOAIMetadataFormat_DC->toXml(Object(Submission), NULL)
> #1 /var/www/ojs/lib/pkp/classes/oai/OAI.inc.php(788): OAIMetadataFormat_DC->toXml(Object(OAIRecord))
> #2 /var/www/ojs/lib/pkp/classes/oai/OAI.inc.php(531): OAI->formatMetadata('oai_dc', Object(OAIRecord))
> #3 /var/www/ojs/lib/pkp/classes/oai/OAI.inc.php(85): OAI->ListRecords()
> #4 /var/www/ojs/pages/oai/OAIHandler.inc.php(39): OAI->execute()
> #5 /var/www/ojs/lib/pkp/classes/core/PKPRouter.inc.php(391): OAIHandler->index(Array, Object(Request))
> #6 /var/www/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
> #7 /var/www/ojs/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPPageRouter->route(Object(R" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: journaldomain.tld, request: "GET /index.php/journal/oai?verb=ListRecords&metadataPrefix=oai_dc HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "journaldomain.tld"

**Comment by edisutoyo** [comment]
Hi @epistemehealth May I know, have you solved this issue?

**Comment by epistemehealth** [comment]
Hi @edisutoyo Sorry, no, I don't know how to solve this issue. My fix was to continue using OJS 3.1.2-2.

**Comment by asmecher** [comment]
In the log file, are there any warnings or other errors above the Fatal Error quoted above?

**Comment by edisutoyo** [comment]
Yes @asmecher this is the error log. I am using ojs 320-1 and php 7.2
When I use chrome and opera the error is 

> This page isn’t working
> currently unable to handle this request.
> HTTP ERROR 500

But when I use firefox I get a blank page

`Fatal error: Uncaught Error: Call to a member function getProperties() on null in /home/u6976116/public_html/ijadis.org/lib/pkp/plugins/oaiMetadataFormats/dc/PKPOAIMetadataFormat_DC.inc.php:31 Stack trace: #0 /home/u6976116/public_html/ijadis.org/plugins/oaiMetadataFormats/dc/OAIMetadataFormat_DC.inc.php(28): PKPOAIMetadataFormat_DC->toXml(Object(Submission), NULL) #1 /home/u6976116/public_html/ijadis.org/lib/pkp/classes/oai/OAI.inc.php(788): OAIMetadataFormat_DC->toXml(Object(OAIRecord)) #2 /home/u6976116/public_html/ijadis.org/lib/pkp/classes/oai/OAI.inc.php(531): OAI->formatMetadata('oai_dc', Object(OAIRecord)) #3 /home/u6976116/public_html/ijadis.org/lib/pkp/classes/oai/OAI.inc.php(85): OAI->ListRecords() #4 /home/u6976116/public_html/ijadis.org/pages/oai/OAIHandler.inc.php(39): OAI->execute() #5 /home/u6976116/public_html/ijadis.org/lib/pkp/classes/core/PKPRouter.inc.php(391): OAIHandler->index(Array, Object(Request)) #6 /home/u6976116/public_html/ijadis.org/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter- in /home/u6976116/public_html/ijadis.org/lib/pkp/plugins/oaiMetadataFormats/dc/PKPOAIMetadataFormat_DC.inc.php on line 31`

**Comment by asmecher** [comment]
@edisutoyo, could you answer [my question above](https://github.com/pkp/pkp-lib/issues/5573#issuecomment-602720384)?

**Comment by edisutoyo** [comment]
Hi @asmecher sorry for my answer before, after I check carefully there is no other error besides fatal error for OAI

**Comment by jmacgreg** [comment]
Hi @asmecher, I've replicated this with our demo OJS 3 install; I can DM you the access info to check if you like. Our error: 

`[Tue Mar 24 07:27:21.108806 2020] [proxy_fcgi:error] [pid 8462:tid 47420357596928] [client 204.187.13.88:39567] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getProperties() on null in [...]/lib/pkp/plugins/oaiMetadataFormats/dc/PKPOAIMetadataFormat_DC.inc.php:31\nStack trace:\n#0 [...]/plugins/oaiMetadataFormats/dc/OAIMetadataFormat_DC.inc.php(28): PKPOAIMetadataFormat_DC->toXml(Object(Submission), NULL)\n#1 [...]/lib/pkp/classes/oai/OAI.inc.php(788): OAIMetadataFormat_DC->toXml(Object(OAIRecord))\n#2 [...]/lib/pkp/classes/oai/OAI.inc.php(531): OAI->formatMetadata('oai_dc', Object(OAIRecord))\n#3 [...]/lib/pkp/classes/oai/OAI.inc.php(85): OAI->ListRecords()\n#4 [...]/pages/oai/OAIHandler.inc.php(39): OAI->execute()\n#5 ...\n', referer: https://demo.publicknowledgeproject.org/ojs3/demo/index.php/manuscript/oai`

**Comment by asmecher** [comment]
Hi all -- could you try the following SQL query and confirm whether it resolves the issue?
```
UPDATE filter_groups SET input_type = 'class::classes.submission.Submission' WHERE input_type = 'class::classes.article.Article';
```

**Comment by edisutoyo** [comment]
Hi @asmecher thank you very much for the solution, that query has resolved the problem

**Comment by asmecher** [comment]
Thanks for confirming -- I've added this for the next releases of OJS and OMP!

**Comment by asmecher** [comment]
To resolve this (and the similar https://github.com/pkp/pkp-lib/issues/5681), you can execute the following database queries.

For OJS:
```
UPDATE filter_groups SET input_type = 'class::classes.submission.Submission' WHERE input_type = 'class::classes.article.Article';
UPDATE filter_groups SET output_type = 'class::classes.submission.Submission' WHERE output_type = 'class::classes.article.Article';
UPDATE filter_groups SET input_type = 'class::classes.submission.Submission[]' WHERE input_type = 'class::classes.article.Article[]';
UPDATE filter_groups SET output_type = 'class::classes.submission.Submission[]' WHERE output_type = 'class::classes.article.Article[]';
```
For OMP:
```
UPDATE filter_groups SET input_type = 'class::classes.submission.Submission' WHERE input_type = 'class::classes.monograph.Monograph';
UPDATE filter_groups SET output_type = 'class::classes.submission.Submission' WHERE output_type = 'class::classes.monograph.Monograph';
UPDATE filter_groups SET input_type = 'class::classes.submission.Submission[]' WHERE input_type = 'class::classes.monograph.Monograph[]';
UPDATE filter_groups SET output_type = 'class::classes.submission.Submission[]' WHERE output_type = 'class::classes.monograph.Monograph[]';
```
Make a backup of your database before running queries on it manually!
