### ISSUE TITLE
Can't download supplementary galleys when publication has urlPath

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5575]
**Describe the bug**
When the publication has been assigned a `urlPath`, links to supplementary galleys that are not PDFs or HTMLs will redirect to a download URL that that lacks the `urlPath` which then leads to an incorrect redirect: `/article/download/<submission_url_path>`.

This only effects supplementary galleys for the current version that are not PDF or HTML files.

Credit to @ajnyga for discovering this bug. :)

**What application are you using?**
 OJS 3.2

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/2657

**Comment by asmecher** [comment]
@ajnyga, it looks like you've already been active on this one -- has it been ported to OPS?
