### ISSUE TITLE
Can't upload image in user profile bio

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5576]
**Describe the bug**
A user can not upload an image through the tinymce text editor in their user profile bio because the URL contains a trailing slash (`/`). Trailing slashes are ignored for `GET` requests but this is a `POST` request.

There is a pattern to [make trailing slashes optional](determineRouteBeforeAppMiddleware) across all routes in Slim, but we can't use this because our authorization framework relies on the route being determined before middleware is called (see `determineRouteBeforeAppMiddleware`). For this reason, the route does not match before our middleware can step in and remove the trailing slash.

This also prevents the image upload option in [textEditorExtras](https://github.com/pkp/textEditorExtras) from working.

**What application are you using?**
 OJS/OMP/OPS 3.2

**Comment by NateWr** [comment]
The following PRs fix this by just removing the trailing slash where it appears. However, it would be nice to resolve this at the `APIHandler` level, so that trailing slashes would be discarded for all endpoints, not just those in a `GET` request. Doing this would require that we drop the trailing slashes before the route is determined, and I'm not sure how we do that.

PRs:
https://github.com/pkp/pkp-lib/pull/5577
https://github.com/pkp/ui-library/pull/70
https://github.com/pkp/textEditorExtras/pull/3

Tests:
https://github.com/pkp/ojs/pull/2658

**Comment by NateWr** [comment]
Merged this fix in, but I'm interested in your thoughts on this trailing slash issue (see original comment). Do you think we should file this as a Dev Housekeeping issue?

**Comment by asmecher** [comment]
There also appears to be a case in `TinyMCEPlugin.inc.php` that causes this: https://forum.pkp.sfu.ca/t/ojs-3-2-0-the-requested-url-was-not-recognized-image-upload-problem/58985

**Comment by asmecher** [comment]
^ that is to say, I think this fixes the issue in everything except the reported TinyMCE-based case...?

**Comment by asmecher** [comment]
As for the trailing-slash issue in general, I'm tempted to declare it a "known limitation" until we can simplify the number/compatibility needs of the routing tools we're using. I don't think we're out of spec, strictly speaking, if we don't handle a trailing slash as though it weren't present, and I suspect fixing it would further entangle our interventions into the Slim toolset.

**Comment by NateWr** [comment]
@asmecher That case in TinyMCE is what the PRs above are supposed to fix. Have you been able to reproduce the problem with the fixes applied?

Also, +1 for enforcing no trailing slashes for now.

**Comment by asmecher** [comment]
@NateWr I was looking at this case, which isn't listed in the PRs: https://github.com/pkp/tinymce/blob/master/TinyMCEPlugin.inc.php#L89

**Comment by NateWr** [comment]
Good spot! I had made the fix but didn't realize tinymce was a submodule. Fixed and merged there: https://github.com/pkp/tinymce/pull/57.

**Comment by msaadm06** [comment]
Good work. It solved the issue. It should be considered in the upcoming updates.

**Comment by NateWr** [comment]
It will go into 3.2.0-1 which we expect to put out in the next couple of weeks. :crossed_fingers:
