### ISSUE TITLE
Plugins to package and release

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5578]
The following plugins or themes should be packaged, released and added to the `plugins.xml` file before 3.2.0-1 is released.

| Name | Whose | Repository | Translations | Release | `plugins.xml` | Notes |
| --- | ---| --- | --- | --- | --- | --- |
| textEditorExtras | @NateWr | ✓ | ✓ | ✓ | ✓ | See #5576 |
| shibboleth | @asmecher | | | | | |
| subscriptionSSO | @asmecher | ✓ | ✓ | ✓ | ✓ | |
| crossrefReferenceLinking | @asmecher | | | | | |
| registrationNotification | @asmecher | | | | | |
| lensGalleyBits | @withanage  | | | | |@withanage  [Answer in Forum](https://forum.pkp.sfu.ca/t/miss-imagen-on-texture-xml-on-ojs-3-2-actualization/59446/6) |

**Comment by asmecher** [comment]
Did subscriptionSSO, deferring the rest to 3.2.0-2.

**Comment by NateWr** [comment]
Released `textEditorExtras`.

**Comment by Vitaliy-1** [comment]
Immersion theme:
```
<release date="2020-03-18" version="1.0.4.1" md5="b8f79cd49ce34add7e71127026a56a87">
	<package>https://github.com/pkp/immersion/releases/download/1.0.4.1/immersion-1.0.4.1.tar.gz</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
		<version>3.2.0.1</version>
	</compatibility>
	<certification type="official"/>
	<description>Bugfix release.</description>
</release>
```
Classic theme:
```
<release date="2020-03-18" version="1.0.3.1" md5="2a28097057cb44cd57b034fe50853370">
	<package>https://github.com/pkp/classic/releases/download/1.0.3-1/classic-1.0.3-1.tar.gz</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
		<version>3.2.0.1</version>
	</compatibility>
	<certification type="official"/>
	<description>Bugfix release.</description>
</release>
```
Health Sciences:
```
<release date="2020-03-20" version="1.0.6.1" md5="beaf512d288f19edd3bc227a736e2269">
	<package>https://github.com/pkp/healthSciences/releases/download/1.0.6.1/healthSciences-1.0.6.1.tar.gz</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
		<version>3.2.0.1</version>
	</compatibility>
	<certification type="official"/>
	<description>Bugfix release.</description>
</release>
```

**Comment by NateWr** [comment]
Thanks @Vitaliy-1! All three of those are now on the `plugins.xml` file.

**Comment by NateWr** [comment]
@asmecher is this list up-to-date for 3.2.0-3? I can't recall any changes for Text Editor Extras that will go into 3.2.0-3...

**Comment by asmecher** [comment]
@NateWr, I just bumped along the things that didn't get completed for earlier 3.2.0-x builds (based on the big 3.2.0 list)... That one's already checked off based on https://github.com/pkp/pkp-lib/issues/5578#issuecomment-602549769.

**Comment by asmecher** [comment]
Outdated -- closing.
