### ISSUE TITLE
[OJS] search function should remember state

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#558]
This is for all applications generally, but has been requested specifically for OJS. The search page should remember state, but doesn't. If a user tries a search and clicks a search result, hitting the "back" browser button won't work, and there's effectively no way to return to the search. I think this is because search is done by GET rather than POST, and returning to the previous URL doesn't retain the search values sent by GET.

**Comment by asmecher** [comment]
Note that GET is good for other reasons -- http://forum.pkp.sfu.ca/t/passing-query-string-by-get/1155/5

**Comment by jmacgreg** [comment]
Hey Alec, can I close this? It looks like #540 already suffices?

J

On Tue, Jun 16, 2015 at 1:43 PM, Alec Smecher <notifications@github.com>
wrote:

> Note that GET is good for other reasons --
> http://forum.pkp.sfu.ca/t/passing-query-string-by-get/1155/5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pkp/pkp-lib/issues/558#issuecomment-112563893>.
>



-- 

James MacGregor
Publishing Services Coordinator
Public Knowledge Project (PKP)
Twitter: @jmacgreg
Skype: j.macgreg

**Comment by asmecher** [comment]
Have you tested with #540 in place? OTOH I don't think it'll do what's requested here.

**Comment by asmecher** [comment]
Just checked -- #540 actually does cover this. Closing.
