### ISSUE TITLE
[OMP] Error upgrading from version 3.1.2-4 to 3.2.0

### ISSUE THREAD

**Issue by ovillamx** [pkp/pkp-lib#5583]
**Describe the bug**
I'm trying to upgrade OMP from version 3.1.2-4 to 3.2.0. I've followed the steps in documentation like with other upgrades, I excecuted the script from command line and the proccess is broken with the message: 'ERROR: Upgrade failed: DB: Column 'publication_id' cannot be null', it referes to any sql query in file 'dbscripts/xml/upgrade/3.2.0_versioning.xml'

**To Reproduce**
1. Follow upgrade steps
2. Upgrade from command line with: `php tools/upgrade.php upgrade`

**What application are you using?**
OMP version 3.1.2-4

**Additional information**
Extract of lastest logs in the terminal:

[data: dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml]
[data: dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml]
[data: dbscripts/xml/upgrade/3.2.0_preupdate_versioning_add_ps_seq.xml]
[data: dbscripts/xml/upgrade/3.2.0_preupdate_last_activity.xml]
[schema: lib/pkp/xml/schema/common.xml]
[schema: lib/pkp/xml/schema/scheduledTasks.xml]
[schema: lib/pkp/xml/schema/temporaryFiles.xml]
[schema: lib/pkp/xml/schema/log.xml]
[schema: lib/pkp/xml/schema/notes.xml]
[schema: lib/pkp/xml/schema/controlledVocab.xml]
[schema: lib/pkp/xml/schema/metadata.xml]
[schema: lib/pkp/xml/schema/announcements.xml]
[schema: lib/pkp/xml/schema/reviews.xml]
[schema: lib/pkp/xml/schema/reviewForms.xml]
[schema: lib/pkp/xml/schema/submissions.xml]
[schema: lib/pkp/xml/schema/submissionFiles.xml]
[schema: lib/pkp/xml/schema/tombstone.xml]
[schema: lib/pkp/xml/schema/genres.xml]
[schema: lib/pkp/xml/schema/libraryFiles.xml]
[schema: lib/pkp/xml/schema/rolesAndUserGroups.xml]
[schema: lib/pkp/xml/schema/views.xml]
[schema: lib/pkp/xml/schema/metrics.xml]
[schema: lib/pkp/xml/schema/navigationMenus.xml]
[schema: lib/pkp/xml/schema/categories.xml]
[schema: dbscripts/xml/omp_schema.xml]
[code: Installer Installer::installDefaultNavigationMenus]
WARNING: The NavigationMenu (ContextId: 1, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
WARNING: The NavigationMenu (ContextId: 1, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
WARNING: The NavigationMenu (ContextId: 0, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
[code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
[code: Installer Installer::migrateUserAndAuthorNames (skipped)]
[data: dbscripts/xml/upgrade/3.2.0_update.xml]
[data: dbscripts/xml/upgrade/3.2.0_stylesheet.xml]
[data: dbscripts/xml/upgrade/3.2.0_navigation_menu_items_locale_change.xml]
[code: Installer Installer::migrateSiteLocales]
[code: Installer Installer::migrateSidebarBlocks]
PHP Notice:  Array to string conversion in /var/www/html/omp/lib/pkp/classes/install/Installer.inc.php on line 828
[code: Installer Installer::migrateMetadataSettings]
[code: Installer Installer::installEmailTemplate]
[code: Installer Installer::changeUserRolesAndStageAssignmentsForStagePermitSubmissionEdit]
[data: dbscripts/xml/upgrade/3.2.0_versioning.xml]
ERROR: Upgrade failed: DB: Column 'publication_id' cannot be null

**Comment by asmecher** [comment]
@ovillamx, at a glance, it looks like you may have a data error in your OJS 3.1.2-4 installation. On that database (that is, *before* you attempt the upgrade) can you try the following query and tell me what the result is?
```
SELECT COUNT(*) FROM authors a LEFT JOIN submissions s ON (a.submission_id = s.submission_id) WHERE s.submission_id IS NULL;
```

**Comment by felcaetano** [comment]
I'm having exactly the same problem.
Running your query returned 2 results. Both author_id and submission_id are very low values, so I'm guessing it is probably something related to a test someone did when OJS was installed for the first time. 
The question now is how do we safe clean this mess. 
```

+-----------+---------------+---------+-------------+------+-----------------+-----+---------------+-------------------+---------------+------------+------------+----------+----------------+---------------+----------------------+--------+---------------------+-------+-------------+--------+-----------+----------+
| author_id | submission_id | country | email       | url  | primary_contact | seq | user_group_id | include_in_browse | submission_id | context_id | section_id | language | date_submitted | last_modified | date_status_modified | status | submission_progress | pages | hide_author | locale | citations | stage_id |
+-----------+---------------+---------+-------------+------+-----------------+-----+---------------+-------------------+---------------+------------+------------+----------+----------------+---------------+----------------------+--------+---------------------+-------+-------------+--------+-----------+----------+
|         1 |             2 |         | ommitted    | NULL |               0 |   1 |          NULL |                 1 |          NULL |       NULL |       NULL | NULL     | NULL           | NULL          | NULL                 |   NULL |                NULL | NULL  |        NULL | NULL   | NULL      |     NULL |
|        15 |             7 | BR      | ommitted    |      |               1 |   1 |          NULL |                 1 |          NULL |       NULL |       NULL | NULL     | NULL           | NULL          | NULL                 |   NULL |                NULL | NULL  |        NULL | NULL   | NULL      |     NULL |
+-----------+---------------+---------+-------------+------+-----------------+-----+---------------+-------------------+---------------+------------+------------+----------+----------------+---------------+----------------------+--------+---------------------+-------+-------------+--------+-----------+----------+

```

**Comment by asmecher** [comment]
@felcaetano, that identifies two `author` records that don't have corresponding `submissions` entries. You can safely delete them:
```
DELETE FROM authors WHERE author_id IN (1, 15);
DELETE FROM author_settings WHERE author_id IN (1, 15);
```

**Comment by NateWr** [comment]
Closing for now but let us know if that doesn't work.

**Comment by felcaetano** [comment]
@NateWr Thanks for the help. And sorry I didn't reply earlier. Our environment  is huge and took hours for the script to finish. I had to leave it running for the weekend. 
The error was actually solved, but the script didn't succeed. When I came back to work, the script exited with the following error:
```
[data: dbscripts/xml/upgrade/3.2.0_url_path.xml]
ERROR: Upgrade failed: DB: Data too long for column 'url_path' at row 13
```
I don't have any more information about this one because I was running it in CLI mode, but I wouldn't be surprise if we have some more data errors in our database.
I think it is safe to close the issue because it doesn't really have to do with OJS development. I'll seek help somewhere else.

Thanks

**Comment by NateWr** [comment]
@felcaetano that means that you have a publisher ID that is longer than 64 characters. In 3.2, the publisher ID for articles, galleys, issues and issue galleys is being copied to a URL path, and this can only be 64 characters.

We decided not to truncate the publisher IDs automatically because these cases may lead to URL changes. A long publisher ID could lead to a URL like this for an article:

```
/article/view/loremipsumdolorsitametconsecteturadipiscingelitseddoeiusmodtempo
```

That will need to be truncated in 3.2 to a url_path under 64 characters:

```
/article/view/loremipsumdolorsitametconsecteturadipiscingelitseddoeiusmodtemp
```

To find these publisher ids, you can use the following SQL commands:

```
SELECT submission_id FROM submission_settings WHERE setting_name="pub-id::publisher-id" AND LEN(setting_value) > 64;
SELECT galley_id FROM submission_galley_settings WHERE setting_name="pub-id::publisher-id" AND LEN(setting_value) > 64;
SELECT issue_id FROM issue_settings WHERE setting_name="pub-id::publisher-id" AND LEN(setting_value) > 64;
SELECT galley_id FROM issue_galley_settings WHERE setting_name="pub-id::publisher-id" AND LEN(setting_value) > 64;
```

You should truncate them before upgrading and set up 301 Redirects for the old URLs after you've upgraded.

**Comment by felcaetano** [comment]
Thanks a lot! I'll do so!

**Comment by andjsmit** [comment]
Back to the original error. Could there be any other causes for `ERROR: Upgrade failed: DB: Column 'publication_id' cannot be null` ?

I ran the query from https://github.com/pkp/pkp-lib/issues/5583#issuecomment-594824850, but it return 0.

**Comment by asmecher** [comment]
@andjsmit, can you restore your database from backup, turn on the `debug` option in `config.inc.php`, and re-run the upgrade? This should dump all SQL queries during the upgrade, and will let you know what the problem query was.

**Comment by andjsmit** [comment]
Here are the last lines before error with debug on.

```
PKP-Database-Logger 1584636522.6557: -----
(mysql):
			UPDATE citations as c
			SET c.publication_id = (
				SELECT s.current_publication_id
				FROM submissions as s
				LEFT JOIN temp_citations as tc
					ON s.submission_id = tc.submission_id
				WHERE c.citation_id = tc.citation_id
			)


-----

PKP-Database-Logger 1584636522.6557: 1048: Column 'publication_id' cannot be null
							ADOConnection._Execute( 			UPDATE citations as c 			SET c.publication_id = ( 				SELECT s.current_publication_id 				FROM submissions as s 			LEFT JOI..., false)% line 1246, file: /home/ojs/sites/ojs-3.2.0/htdocs/lib/pkp/lib/vendor/adodb/adodb-php/adodb.inc.php
						ADOConnection.Execute( 			UPDATE citations as c 			SET c.publication_id = ( 				SELECT s.current_publication_id 				FROM submissions as s 				LEFT JOI...)% line  442, file: /home/ojs/sites/ojs-3.2.0/htdocs/lib/pkp/classes/install/Installer.inc.php
					Installer.executeSQL( 			UPDATE citations as c 			SET c.publication_id = ( SELECT s.current_publication_id 				FROM submissions as s 				LEFT JOI...)% line  437, file: /home/ojs/sites/ojs-3.2.0/htdocs/lib/pkp/classes/install/Installer.inc.php
				Installer.executeSQL(Array[30])% line  395, file: /home/ojs/sites/ojs-3.2.0/htdocs/lib/pkp/classes/install/Installer.inc.php
			Installer.executeAction(Array[3])% line  263, file: /home/ojs/sites/ojs-3.2.0/htdocs/lib/pkp/classes/install/Installer.inc.php
ERROR: Upgrade failed: DB: Column 'publication_id' cannot be null
```

Thanks.

**Comment by asmecher** [comment]
@andjsmit, I wonder if you have `citation` entries that don't have corresponding `submission` entries. In your pre-upgrade database, try the following query:
```
SELECT c.citation_id FROM citations c LEFT JOIN submissions s ON (c.submission_id = s.submission_id) WHERE s.submission_id IS NULL;
```
It should return no entries; if it does, you should remove those entries from `citations` before trying the upgrade.

**Comment by andjsmit** [comment]
This returns 482 rows out of 13307 for me. I'll try deleting them and running upgrade. Any guesses how we might have ended up with so many orphaned citations?

Thanks!

**Comment by asmecher** [comment]
> Any guesses how we might have ended up with so many orphaned citations?
Not off the top of my head -- possibly an error occurred mid-way through deleting a submission? Or a manual data clean-up in the database that left some entities behind?

**Comment by andjsmit** [comment]
@asmecher Deleting the those citations row allowed my to complete the upgrade. Thanks!

**Comment by ibnusulaiman83** [comment]
I got same errrors but i dont under how you fixed that issue?

**Comment by ibnusulaiman83** [comment]
> Back to the original error. Could there be any other causes for `ERROR: Upgrade failed: DB: Column 'publication_id' cannot be null` ?
> 
> I ran the query from [#5583 (comment)](https://github.com/pkp/pkp-lib/issues/5583#issuecomment-594824850), but it returned 0.

me too how to fix that issue? I already restore old database

**Comment by ibnusulaiman83** [comment]
> I'm having exactly the same problem.
> Running your query returned 2 results. Both author_id and submission_id are very low values, so I'm guessing it is probably something related to a test someone did when OJS was installed for the first time.
> The question now is how do we safe clean this mess.
> 
> ```
> 
> +-----------+---------------+---------+-------------+------+-----------------+-----+---------------+-------------------+---------------+------------+------------+----------+----------------+---------------+----------------------+--------+---------------------+-------+-------------+--------+-----------+----------+
> | author_id | submission_id | country | email       | url  | primary_contact | seq | user_group_id | include_in_browse | submission_id | context_id | section_id | language | date_submitted | last_modified | date_status_modified | status | submission_progress | pages | hide_author | locale | citations | stage_id |
> +-----------+---------------+---------+-------------+------+-----------------+-----+---------------+-------------------+---------------+------------+------------+----------+----------------+---------------+----------------------+--------+---------------------+-------+-------------+--------+-----------+----------+
> |         1 |             2 |         | ommitted    | NULL |               0 |   1 |          NULL |                 1 |          NULL |       NULL |       NULL | NULL     | NULL           | NULL          | NULL                 |   NULL |                NULL | NULL  |        NULL | NULL   | NULL      |     NULL |
> |        15 |             7 | BR      | ommitted    |      |               1 |   1 |          NULL |                 1 |          NULL |       NULL |       NULL | NULL     | NULL           | NULL          | NULL                 |   NULL |                NULL | NULL  |        NULL | NULL   | NULL      |     NULL |
> +-----------+---------------+---------+-------------+------+-----------------+-----+---------------+-------------------+---------------+------------+------------+----------+----------------+---------------+----------------------+--------+---------------------+-------+-------------+--------+-----------+----------+
> ```

can you share your sql script to show this result?

**Comment by asmecher** [comment]
@ibnusulaiman83, please post your question on the support forum (https://forum.pkp.sfu.ca); that's the best place to get help.

**Comment by ajnyga** [comment]
> This returns 482 rows out of 13307 for me. I'll try deleting them and running upgrade. Any guesses how we might have ended up with so many orphaned citations?
> 
> Thanks!

Just FYI that I got 644 rows.

**Comment by brunocampos87** [comment]
> @andjsmit, I wonder if you have `citation` entries that don't have corresponding `submission` entries. In your pre-upgrade database, try the following query:
> 
> ```
> SELECT c.citation_id FROM citations c LEFT JOIN submissions s ON (c.submission_id = s.submission_id) WHERE s.submission_id IS NULL;
> ```
> 
> It should return no entries; if it does, you should remove those entries from `citations` before trying the upgrade.

Friend, i almost the same problem:  

In my debug shows: 
PKP-Database-Logger 1613733245.0274: -----
(mysqli):
                        UPDATE submission_chapters as sc
                        SET publication_id = (
                                SELECT s.current_publication_id
                                FROM temp_submission_chapters as tsc
                                LEFT JOIN submissions as s
                                        ON (tsc.submission_id = s.submission_id)
                                WHERE sc.chapter_id = tsc.chapter_id
                        )


-----

PKP-Database-Logger 1613733245.0274: -----
(mysqli):
                        UPDATE publication_formats as pf
                        SET publication_id = (
                                SELECT s.current_publication_id
                                FROM temp_publication_formats as tpf
                                LEFT JOIN submissions as s
                                        ON (tpf.submission_id = s.submission_id)
                                WHERE pf.publication_format_id = tpf.publication_format_id
                        )


-----

PKP-Database-Logger 1613733245.0274: Query:
                        UPDATE publication_formats as pf
                        SET publication_id = (
                                SELECT s.current_publication_id
                                FROM temp_publication_formats as tpf
                                LEFT JOIN submissions as s
                                        ON (tpf.submission_id = s.submission_id)
                                WHERE pf.publication_format_id = tpf.publication_format_id
                        )
                 failed. Column 'publication_id' cannot be null
PKP-Database-Logger 1613733245.0274: 1048: Column 'publication_id' cannot be null
                                                        ADOConnection._Execute(                         UPDATE publication_formats as pf                      SET publication_id = (                          SELECT s.current_publication_id                              FROM temp_publication_for..., false)% line 1246, file: /srv/www/sistema/teste5/lib/pkp/lib/vendor/adodb/adodb-php/adodb.inc.php
                                                ADOConnection.Execute(                  UPDATE publication_formats as pf             SET publication_id = (                           SELECT s.current_publication_id                                 FROM temp_publication_for...)% line  442, file: /srv/www/sistema/teste5/lib/pkp/classes/install/Installer.inc.php
                                        Installer.executeSQL(                   UPDATE publication_formats as pf                     SET publication_id = (                           SELECT s.current_publication_id                                 FROM temp_publication_for...)% line  437
ERROR: Upgrade failed: DB: Column 'publication_id' cannot be null

How can i fix?

**Comment by ibnusulaiman83** [comment]
> @ibnusulaiman83, please post your question on the support forum (https://forum.pkp.sfu.ca); that's the best place to get help.



> > @andjsmit, I wonder if you have `citation` entries that don't have corresponding `submission` entries. In your pre-upgrade database, try the following query:
> > ```
> > SELECT c.citation_id FROM citations c LEFT JOIN submissions s ON (c.submission_id = s.submission_id) WHERE s.submission_id IS NULL;
> > ```
> > 
> > 
> > It should return no entries; if it does, you should remove those entries from `citations` before trying the upgrade.
> 
> Friend, i almost the same problem:
> 
> In my debug shows:
> PKP-Database-Logger 1613733245.0274: -----
> (mysqli):
> UPDATE submission_chapters as sc
> SET publication_id = (
> SELECT s.current_publication_id
> FROM temp_submission_chapters as tsc
> LEFT JOIN submissions as s
> ON (tsc.submission_id = s.submission_id)
> WHERE sc.chapter_id = tsc.chapter_id
> )
> 
> PKP-Database-Logger 1613733245.0274: -----
> (mysqli):
> UPDATE publication_formats as pf
> SET publication_id = (
> SELECT s.current_publication_id
> FROM temp_publication_formats as tpf
> LEFT JOIN submissions as s
> ON (tpf.submission_id = s.submission_id)
> WHERE pf.publication_format_id = tpf.publication_format_id
> )
> 
> PKP-Database-Logger 1613733245.0274: Query:
> UPDATE publication_formats as pf
> SET publication_id = (
> SELECT s.current_publication_id
> FROM temp_publication_formats as tpf
> LEFT JOIN submissions as s
> ON (tpf.submission_id = s.submission_id)
> WHERE pf.publication_format_id = tpf.publication_format_id
> )
> failed. Column 'publication_id' cannot be null
> PKP-Database-Logger 1613733245.0274: 1048: Column 'publication_id' cannot be null
> ADOConnection._Execute( UPDATE publication_formats as pf SET publication_id = ( SELECT s.current_publication_id FROM temp_publication_for..., false)% line 1246, file: /srv/www/sistema/teste5/lib/pkp/lib/vendor/adodb/adodb-php/adodb.inc.php
> ADOConnection.Execute( UPDATE publication_formats as pf SET publication_id = ( SELECT s.current_publication_id FROM temp_publication_for...)% line 442, file: /srv/www/sistema/teste5/lib/pkp/classes/install/Installer.inc.php
> Installer.executeSQL( UPDATE publication_formats as pf SET publication_id = ( SELECT s.current_publication_id FROM temp_publication_for...)% line 437
> ERROR: Upgrade failed: DB: Column 'publication_id' cannot be null
> 
> How can i fix?

I got same issues to upgrade from version 3.2.1.4 to 3.3.0.3.

**Comment by ibnusulaiman83** [comment]
> @andjsmit, can you restore your database from backup, turn on the `debug` option in `config.inc.php`, and re-run the upgrade? This should dump all SQL queries during the upgrade, and will let you know what the problem query was.

Hello sir. I got this error while run upgrade from version 3.2.1.4 to 3.3.0.3
`[data: dbscripts/xml/upgrade/3.2.0_versioning.xml]
ERROR: Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'publication_id' cannot be null (SQL:
			UPDATE publication_formats as pf
			SET publication_id = (
				SELECT s.current_publication_id
				FROM temp_publication_formats as tpf
				LEFT JOIN submissions as s
					ON (tpf.submission_id = s.submission_id)
				WHERE pf.publication_format_id = tpf.publication_format_id
			)
		)`
So can you share hpw to fix this issue?

**Comment by asmecher** [comment]
@ibnusulaiman83, as I said on https://github.com/pkp/pkp-lib/issues/6767#issuecomment-780978018, please post your question on our support forum (https://forum.pkp.sfu.ca) instead of in Github Issues. That's the best place to get help.

**Comment by ibnusulaiman83** [comment]
> @ibnusulaiman83, as I said on [#6767 (comment)](https://github.com/pkp/pkp-lib/issues/6767#issuecomment-780978018), please post your question on our support forum (https://forum.pkp.sfu.ca) instead of in Github Issues. That's the best place to get help.

Already submit my questions on https://forum.pkp.sfu.ca
Here is my questions

https://forum.pkp.sfu.ca/t/ojs-upgrade-error-db-column-publication-id-cannot-be-null-from-3-1-0-0-to-3-2-1-1/

**Comment by marcbria** [comment]
I was saving for the end the most damaged of our journals (that passed by some institutions till it arrive to our hands) and when I upgrade from 3.1 to 3.2, this is what I found:

- 890 missing files.
- 2436 articles with review assignation issues.
- 3446 orphan authors.
- 11693 orphan citations.

Data was lost some time ago (no idea where and/or when) and there is nothing I can do to fix this so I created 890 fake/empty files and removed the wrong assignations, but I'm unsure about doing the same about authoring and the citations.

3446 sounds like a reasonable amount of authors for 890 files/articles (and I think the same for the citations) so looks like next step is running the delete queries to remove them all but I'm wondering if, instead of delete this data, I can keep it in some way (if it make any sense).

Thanks for your time,
m.

PD to @ajnyga : I see your 644 rows and I rise to 3446. ;-)

**Comment by NateWr** [comment]
I think the best way to preserve this data is to keep it in a permanent
database backup. In an ideal world you might have one for every year of
operation and even now could go back and identify where some of the deleted
submissions came from (maybe deleted journals?). But either way I wouldn't
recommend keeping them in your production database.

**Comment by marcbria** [comment]
Thanks Nate.

Yes, this was the plan, but I was wondering about a better solution. :-(

BTW, one thing I like from our new docker approach is that I will keep each journal with their historic database:
![imagen](https://user-images.githubusercontent.com/2779168/120315091-415ade80-c2dc-11eb-844d-a4cf1ce6e1c6.png)

I know I will never use them, but it gives me peace of mind. ;-)

Deleting authors and citations right now. Let's see how it goes...

**Comment by marcbria** [comment]
Could somebody confirm those cleaning-queries will do the work:

```
## Cleaning orphan authors:

SELECT count(*) as 'Orphan authors BEFORE...'
  FROM authors a 
      LEFT JOIN submissions s 
      ON (a.submission_id = s.submission_id) 
  WHERE s.submission_id IS NULL;

CREATE TEMPORARY TABLE IF NOT EXISTS authors2delete AS (
  SELECT a.author_id 
  FROM authors a 
      LEFT JOIN submissions s 
      ON (a.submission_id = s.submission_id) 
  WHERE s.submission_id IS NULL
);

DELETE FROM authors WHERE authors.author_id IN (
    SELECT a.author_id 
    FROM authors2delete a
);

DELETE FROM author_settings WHERE author_settings.author_id IN (
  SELECT a.author_id 
  FROM authors2delete a
);

SELECT count(*) as 'Orpahn authors AFTER...'
  FROM authors a 
      LEFT JOIN submissions s 
      ON (a.submission_id = s.submission_id) 
  WHERE s.submission_id IS NULL;


## Cleaning orphan citations:  

SELECT count(*) as 'Orphan Citations BEFORE...' 
    FROM citations c 
        LEFT JOIN submissions s 
        ON (c.submission_id = s.submission_id) 
    WHERE s.submission_id IS NULL;

CREATE TEMPORARY TABLE IF NOT EXISTS citations2delete AS (
    SELECT c.citation_id 
    FROM citations c 
        LEFT JOIN submissions s 
        ON (c.submission_id = s.submission_id) 
    WHERE s.submission_id IS NULL
);

DELETE FROM citations WHERE citations.citation_id IN (
    SELECT c.citation_id
    FROM citations2delete c
);

SELECT count(*) as 'Orphan Citations AFTER...' 
    FROM citations c 
        LEFT JOIN submissions s 
        ON (c.submission_id = s.submission_id) 
    WHERE s.submission_id IS NULL;
```

**DISCLAIMER for others who fall in this thread with this same problem:** 
PLEASE do not run these queries until someone more savvy can confirm that they are safe. 
Note that they are removing data from your DB so it may break your system.

Cheers,
m.

**Comment by murilodbva** [comment]
> 

Hello @marcbria , you code helped me. Thanks.
I think you maybe also can include that another tables and drop the temporary tables in the end:
Below is what I'm doing in MariaDB:

**1) For Cleaning orphan authors:**

- books_for_review_authors
- submission_comments

```
CREATE TEMPORARY TABLE IF NOT EXISTS authors2delete AS (
  SELECT a.author_id
  FROM authors a
      LEFT JOIN submissions s ON (a.submission_id = s.submission_id)
  WHERE s.submission_id IS NULL
);

DELETE FROM authors WHERE  EXISTS (
    SELECT a.author_id
    FROM authors2delete a
);

DELETE FROM author_settings WHERE  EXISTS (
  SELECT a.author_id
  FROM authors2delete a
);

DELETE FROM books_for_review_authors WHERE  EXISTS (
  SELECT a.author_id
  FROM authors2delete a
);

DELETE FROM submission_comments WHERE  EXISTS (
  SELECT a.author_id
  FROM authors2delete a
);

DROP TABLE authors2delete;
```

**2) For Cleaning orphan citations:**

- citation_settings
```
CREATE TEMPORARY TABLE IF NOT EXISTS citations2delete AS (
    SELECT c.citation_id
    FROM citations c
        LEFT JOIN submissions s ON (c.submission_id = s.submission_id)
    WHERE s.submission_id IS NULL
);

DELETE FROM citations WHERE  EXISTS (
    SELECT c.citation_id
    FROM citations2delete c
);

DELETE FROM citation_settings WHERE  EXISTS (
    SELECT c.citation_id
    FROM citations2delete c
);

DROP TABLE citations2delete;
```
