### ISSUE TITLE
Enable/disable journal setting not available in 3.2.0

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5584]
**Describe the bug**
In previous versions, the journal edit form included a checkbox to enable/disable the journal. When disabled, the journal would be accessible to logged in editors but not to logged out visitors.

This does not appear in 3.2.0.

**To Reproduce**
1. Login as admin
2. Go to Administration > Hosted Journals
3. Click "Edit" on a Journal
4. The checkbox should appear in this form but it doesn't.

**What application are you using?**
 OJS/OMP/OPS 3.2.0

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ui-library/pull/78
https://github.com/pkp/ojs/pull/2665

@asmecher I added a test for this in a new integration tests file, `MultipleContexts.spec.js` ([here](https://github.com/pkp/ojs/pull/2665/files#diff-72d70619d1c4b883d37f3cce9ae26e73)). Does that seem like a sensible place for it? I thought this spec file could get extended down the line with more tests for multi-journal setups, and any SaaS/multi-tenant features we work on.

**Comment by asmecher** [comment]
@NateWr, yes, that looks good -- we're currently missing some tools that reload the database/files between integration tests where necessary, but that shouldn't hold you back in the meantime.

**Comment by NateWr** [comment]
Thanks, merged!
