### ISSUE TITLE
Author list: author name is empty if not included in submission's metadata

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#5588]
OJS 3.2

If it's possible to include author name for several locales, `PKPAuthor::getLocalizedFamilyName()` returns an empty string if the name isn't specified in a submission in its locale. 
E.g., the primary locale is English, submission is in Ukrainian, it's mandatory to include only given name in Ukrainian locale. When viewing the page with the English interface, those names are missing and [this statement](https://github.com/pkp/ojs/blob/a76f4ecb515320711169b69fe731e7afd61e06f0/templates/frontend/pages/searchAuthorIndex.tpl#L23) becomes true. 
![authorindex](https://user-images.githubusercontent.com/20665587/75989421-ea5d3280-5efb-11ea-8635-7cadf4dc64a2.png)

1. If only the given name is mandatory, should sorting be done by it rather than a family name; or at least if the latter is missing? 
2. If author doesn't include name for a specific locale, I think it's better to exclude all associated info from the list.

Also, the same applies to the list of authors on issue/article page, where the method is used. Names are not included if they aren't specified for an interface locale, thus, from a front-end, it seems that published article doesn't have authors (issue page) or it's was written by an institution if the latter is specified:
![articlepage](https://user-images.githubusercontent.com/20665587/75990304-63a95500-5efd-11ea-8ff5-80016008f280.png)

**Comment by solojano** [comment]
Es una pena saber que la versión OJS 3.2.0-2 no resolvió este error :( . La gente que habla otros idiomas tendrá que esperar...

**Comment by ajnyga** [comment]
Is there a reason why givenName is called here: https://github.com/pkp/pkp-lib/blob/master/classes/identity/Identity.inc.php#L141-L161

Or should it be:
```
	function getLocalizedFamilyName($defaultLocale = null) {
		$locale = AppLocale::getLocale();
		$familyName = $this->getFamilyName($locale);
		if (empty($familyName)) {
			if (is_null($defaultLocale)) {
				// the users register for the site, thus
				// the site primary locale is the default locale
				$site = Application::get()->getRequest()->getSite();
				$defaultLocale = $site->getPrimaryLocale();
			}
			$locale = $defaultLocale;
			assert(!empty($this->getFamilyName($locale)));
		}
		return $this->getFamilyName($locale);
	}
```

**Comment by ajnyga** [comment]
I don't think `$this->getSubmissionLocale()` is available here
https://github.com/pkp/pkp-lib/blob/master/classes/submission/PKPAuthor.inc.php#L66 or here https://github.com/pkp/pkp-lib/blob/master/classes/submission/PKPAuthor.inc.php#L32 or here https://github.com/pkp/pkp-lib/blob/master/classes/submission/PKPAuthor.inc.php#L59

Or at least can not figure out where it is set.

**Comment by ajnyga** [comment]
We could do `Services::get('publication')->get($this->getData('publicationId'))->getData('locale')`
But not sure how big the weight would be.

One alternative is of course to always call these functions with a given locale.

**Comment by ajnyga** [comment]
For example this seems to work:
```
	/**
	 * Get submission locale.
	 * @return string
	 */
	function getSubmissionLocale() {
		return Services::get('publication')->get($this->getData('publicationId'))->getData('locale');
	}
```

**Comment by asmecher** [comment]
Hi all -- I've drafted a PR here: https://github.com/pkp/pkp-lib/pull/5805 (to be applied in the `lib/pkp` subdirectory).

Your confirmation on whether this works would be helpful in getting this merged for the 3.2.0-3 release, which is coming very soon!

**Comment by quartelmestre** [comment]
It didn't work here (more details on PR #5805 ).

**Comment by solojano** [comment]
I am waiting for this bug to be resolved @quartelmestre

**Comment by asmecher** [comment]
@solojano, I'm working to fix the bug with the help of @quartelmestre's testing (they're a community member volunteering their efforts on this). There's active discussion at the PR -- see https://github.com/pkp/pkp-lib/pull/5805. If you're interested in testing, please read the conversation there and add details; that'll help keep the conversation from being split in two places.

**Comment by asmecher** [comment]
Fixed via https://github.com/pkp/pkp-lib/pull/5805. Thanks, all!
