### ISSUE TITLE
[OJS] PostgreSQL can not recognize update SQL queries

### ISSUE THREAD

**Issue by seonghobae** [pkp/pkp-lib#5589]
Hello,
I had trouble updating SQL queries via updater, 3.1.1.4, to 3.2.0.

https://github.com/pkp/ojs/blob/master/dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml#L31-L40

PostgreSQL can not recognize alias 'etd' where ```SET etd.email_id = (``` line. 

Moreover, In some points, PostgreSQL can not recognize double quotation mark if something were mean as value, as not column name. I modified these things by manual; however, I forgot where I edited them. Anyway, that's an awful experience.

**Comment by seonghobae** [comment]
https://github.com/pkp/pkp-lib/blob/0ac6d36008b5eef09b8fac67b74f9c59a63a80fa/classes/publication/PKPPublicationDAO.inc.php#L258

See also here: ```DELETE ps from publication_settings ps``` isn't available in Postgresql.

**Comment by seonghobae** [comment]
https://github.com/pkp/pkp-lib/blob/0ac6d36008b5eef09b8fac67b74f9c59a63a80fa/classes/publication/PKPPublicationDAO.inc.php#L258-L265
PostgreSQL can not delete statement with join directly; please see here:
https://stackoverflow.com/a/35344190
https://stackoverflow.com/a/33723604

**Comment by asmecher** [comment]
@seonghobae, thanks for reporting -- it looks like there are a number of PostgreSQL incompatibilities in the upgrade scripts. I'll work on them as part of this issue. We're planning to release a new build later this week and I'll try to have a fix included there.

**Comment by asmecher** [comment]
OJS upgrade script fixes: https://github.com/pkp/pkp-lib/commit/641fd104740dc9f369b8f45f50853fc2c1c2db9c (in `lib/pkp` subdirectory) and https://github.com/pkp/ojs/commit/dbf319e8ffce87d447a3a57dad6c398e1705fca3.

DAO fixes for PostgreSQL-incompatible query: https://github.com/pkp/pkp-lib/commit/34ea0f1cc542fc5e6703ff0fbb2b571c2d8e5524 and https://github.com/pkp/pkp-lib/commit/66b986b734e3296d33cb2ea1f5d23dfe51ea1b89 (both in `lib/pkp`)
