### ISSUE TITLE
[OJS] Block plugins and cacheing problem

### ISSUE THREAD

**Issue by bkawula** [pkp/pkp-lib#5592]
Hi PKP,

@Vitaliy-1 told me to post this issue here:
https://forum.pkp.sfu.ca/t/immersion-theme-and-template-caching-problems/59069

Basically, cached block templates from one journal are being pulled into other journals with different themes and it's causing display / layout issues because of misplaced CSS classes and HTML tags.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/6218
- https://github.com/pkp/ojs/pull/2869 (tests only)

**Comment by asmecher** [comment]
@bkawula, are you able to test this? I'd love to have 3rd-party confirmation that the fix works, though I've tested it with your use case here.

**Comment by asmecher** [comment]
Merged and closed (though 3rd-party testing is still welcome).
