### ISSUE TITLE
[OMP] Can't DROP 'setting_type' when upgrading from version 3.1.2-4 to 3.2.0

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5594]
**Describe the bug**
When upgrading from OJS 3.1.2-4 to OJS 3.2 the process stops when it need to drop column.

**To Reproduce**
git clone OMP master branch and run all the git init submodule and npm build...

**What application are you using?**
 OJS or OMP version 3.1.2-4 => 3.2.0

**Additional information**
Bellow is the log :
```
[code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
[code: Installer Installer::migrateUserAndAuthorNames (skipped)]
[data: dbscripts/xml/upgrade/3.2.0_update.xml]
[data: dbscripts/xml/upgrade/3.2.0_setting_type.xml]
ERROR: Upgrade failed: DB: Can't DROP 'setting_type'; check that column/key exists

I've checke that the last XML file attempt to drop columns from diferent tables, and both exists.
```

**Comment by asmecher** [comment]
@israelcefrin, are you sure this is an up-to-date checkout? `dbscripts/xml/upgrade/3.2.0_setting_type.xml` was removed prior to the release of OJS and OMP 3.2.0-0.

**Comment by israelcefrin** [comment]
@asmecher I've cloned it on March 5th, I will re-clone it to double-check and branch it from OJS 3.2.0 tag instead master branch.

**Comment by jonasraoni** [comment]
This file was removed in 2019 (https://github.com/pkp/pkp-lib/issues/2072), before the creation of the tag `3.2.0-0`, and doesn't exist on the latest tags `3.2.0-4` nor in the `3.2.1-5`, so I'll close this issue.
