### ISSUE TITLE
“The file could not be uploaded or revised”

### ISSUE THREAD

**Issue by ravi25388** [pkp/pkp-lib#5595]
After installing ojs 3.1.2.4 successfully and creating journal I am unable to upload any file. It kept saying “The file could not be uploaded or revised.” I don’t know what to do… I give permission to all the folders as suggested in the information file… Still can’t upload… I am quite unhappy :frowning:
Also, while trying to delete my assigned in submission I receive this message “An unexpected error has occurred. Please reload the page and try again.”

Anyone who can help me I would be really grateful. It'surgent too…

Thanks in advance…

![Screenshot 2020-03-08 09 41 36](https://user-images.githubusercontent.com/61901562/76156486-26bda800-6121-11ea-944d-ed48b8b034c1.png)

![Screenshot 2020-03-08 09 41 45](https://user-images.githubusercontent.com/61901562/76156487-2de4b600-6121-11ea-9b30-c63d91e88d65.png)

 ![Screenshot 2020-03-08 09 39 18](https://user-images.githubusercontent.com/61901562/76156468-dcd4c200-6120-11ea-9ac7-5d864637a61a.png)

**Comment by asmecher** [comment]
Hi @ravi25388 -- I see you've also posted this here:
https://forum.pkp.sfu.ca/t/the-file-could-not-be-uploaded-or-revised-what-should-i-do/59106

That's the best place to work through this problem.
