### ISSUE TITLE
[OJS] error submit DOI Crossreff

### ISSUE THREAD

**Issue by muhammadhamdani** [pkp/pkp-lib#5596]
**Describe the bug**
if submit article in doi crossref, response This page isn’t working

**To Reproduce**
1. klik tools -> import/export -> choose CrossRef XML Export Plugin
2. Click on tabs article
3. select acticle
4. klik submit
5. This page isn’t working

**What application are you using?**
 OJS 

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
![image](https://user-images.githubusercontent.com/12347039/76164805-6a95c900-6184-11ea-983b-e34fb36a2c74.png)

**Comment by muhammadhamdani** [comment]
![image](https://user-images.githubusercontent.com/12347039/76165032-33281c00-6186-11ea-96d8-a716ee104d4b.png)
this error log

**Comment by asmecher** [comment]
@muhammadhamdani, which version of OJS are you using? (Please include this when you create an issue.)

**Comment by muhammadhamdani** [comment]
i using ojs 3.1.2.4

**Comment by asmecher** [comment]
Hi @muhammadhamdani -- check further back in the log file. Those entries aren't relevant but there should be something containing the word "error".

**Comment by muhammadhamdani** [comment]
mod_fcgid: stderr: PHP Warning:  Declaration of CrossRefSettingsForm::execute() should be compatible with Form::execute(...$functionArgs) in /home/ojstes/public_html/plugins/importexport/crossref/classes/form/CrossRefSettingsForm.inc.php on line 19, referer: https://journal2.unusa.ac.id/index.php/CEJ/management/tools
[Sun Mar 08 14:44:44.999188 2020] [fcgid:warn] [pid 14893] [client 66.249.71.14:45596] mod_fcgid: stderr: PHP Warning:  Declaration of SubmissionKeywordEntryDAO::getByControlledVocabId($controlledVocabId, $rangeInfo = NULL) should be compatible with ControlledVocabEntryDAO::getByControlledVocabId($controlledVocabId, $rangeInfo = NULL, $filter = NULL) in /home/ojstes/public_html/lib/pkp/classes/submission/SubmissionKeywordEntryDAO.inc.php on line 20
[Sun Mar 08 14:44:45.472528 2020] [fcgid:warn] [pid 14355] [client 36.90.222.97:62416] mod_fcgid: stderr: PHP Warning:  Declaration of UploadPluginForm::execute() should be compatible with Form::execute(...$functionArgs) in /home/ojstes/public_html/lib/pkp/controllers/grid/plugins/form/UploadPluginForm.inc.php on line 22, referer: https://journal2.unusa.ac.id/index.php/CEJ/management/importexport/plugin/CrossRefExportPlugin
[Sun Mar 08 14:44:45.472590 2020] [fcgid:warn] [pid 14355] [client 36.90.222.97:62416] mod_fcgid: stderr: PHP Warning:  Declaration of CrossRefSettingsForm::execute() should be compatible with Form::execute(...$functionArgs) in /home/ojstes/public_html/plugins/importexport/crossref/classes/form/CrossRefSettingsForm.inc.php on line 0, referer: https://journal2.unusa.ac.id/index.php/CEJ/management/importexport/plugin/CrossRefExportPlugin

**Comment by NateWr** [comment]
@muhammadhamdani we'll probably need more of the error log. Each entry starts with the date and time like this:

```
[Sun Mar 08 14:44:44.999188 2020] ...
```
GIve us all the log entries for the minute of 14:44.
