### ISSUE TITLE
Native import/export plugin adds a blank citation when importing submissions with citations

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5597]
**Describe the bug**
Native import/export plugin adds a blank citation when importing submissions with citations

**To Reproduce**
1. Import a submission with citations
2. Check the DB - one citation more is being added with blank `raw_citation`

**What application are you using?**
 OJS - OMP version 3.1.2, 3.2

**Comment by defstat** [comment]
@asmecher 

PRs

**v3.1.2**
[PKP-LIB]: #5598
[OJS]: pkp/ojs#2671
[OMP]: pkp/omp#780

**v3.2**
[PKP-LIB]: #5599
[OJS]: pkp/ojs#2672
[OMP]: pkp/omp#781

**Comment by asmecher** [comment]
@defstat, I just had one comment -- otherwise, please go ahead and merge!

**Comment by asmecher** [comment]
Thanks, merge when you're ready!

**Comment by defstat** [comment]
Merged...
