### ISSUE TITLE
pkp-native.xml uses publication element instead of pkppublication

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5600]
At `https://github.com/pkp/pkp-lib/blob/master/plugins/importexport/native/pkp-native.xsd#L223` change `publication` to `pkppublication`

**Comment by asmecher** [comment]
@defstat, would you mind opening a PR to correct this?

**Comment by defstat** [comment]
@asmecher 

PR
[PKP-LIB]: #5649

**Comment by asmecher** [comment]
Thanks, @defstat!
