### ISSUE TITLE
Add range slider for filter by last activity in submissions list

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5601]
**Describe the problem you would like to solve**
A filter to view submissions that have been inactive for the last 30 days was added to 3.2 (#4168). The server side is already implemented to support any inactive threshold (30 days, 50 days, etc). But we need to build an accessible [range input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) filter for this.

I didn't have time to take this on before 3.2 but we should implement it as soon as possible to complete this feature.

cc @forgive38

**Who is asking for this feature?**
Editors and Managers, particularly those overseeing large journals.

**Comment by thinkbulecount2** [comment]
Polyfill for multirange inputs for the slider: https://github.com/LeaVerou/multirange

**Comment by NateWr** [comment]
It's a good find! I did a bit of digging through its issues, though, and found this:

https://github.com/LeaVerou/multirange/issues/37

It looks like the polyfill was based on a `multiple` attribute that was once part of the range input spec but is no longer supported. For that reason, I'm hesitant to use it.

**Comment by thinkbulecount2** [comment]
Ahhh that's too bad :< will keep doing some digging if I find anything else!

**Comment by thinkbulecount2** [comment]
PR: https://github.com/pkp/ui-library/pull/93

**Comment by NateWr** [comment]
The PRs below change the last activity filter to a slider. @thinkbulecount2 converted our existing range input sliders over to a more accessible format that uses the native `<input type="range">` HTML element.

![filter-slider](https://user-images.githubusercontent.com/2306629/83036868-04a63880-a033-11ea-8623-b1a61e7415b6.gif)

Unfortunately, the native range inputs do not support multiple range values, which we use in the reviewer selection. I did a little bit of work to re-implement them in an accessible format using a `<fieldset>` and multiple `<input type="range">`. 

![filter-slider-multirange](https://user-images.githubusercontent.com/2306629/83037064-40410280-a033-11ea-934f-f064c740fe39.gif)

It's a little bit awkward in the way that moving one slider adjusts the position of the other. But it preserves our existing functionality, improves accessibility, and allows us to step away from a third-party library that would fail upcoming accessibility audits.

PRs:
https://github.com/pkp/ui-library/pull/94
https://github.com/pkp/pkp-lib/pull/5924
https://github.com/pkp/ojs/pull/2777
https://github.com/pkp/omp/pull/825
https://github.com/pkp/ops/pull/32

**Comment by NateWr** [comment]
All merged!
