### ISSUE TITLE
JournalManager/Author metadata edit error: "Please enter the references."

### ISSUE THREAD

**Issue by verzunov** [pkp/pkp-lib#5602]
Hello!
Ups, we did it again:
[JournalManager/Author metadata edit error: "Please enter the references."](https://github.com/pkp/pkp-lib/issues/4295)
When user is trying to edit metadata on published article he will get this notification: "Please enter the references.", even if references is set, this problem can be bypassed if uncheck 'Author' role from user or uncheck 'Required' flag for 'References' in workflow settings.
Tested on ' not clean' 3.2.0.0.
Is this a bug, role conflict or authors shouldn't be allowed to change metadata?

**Comment by NateWr** [comment]
Hi @verzunov, can you follow the bug report template? In particular, please set out some detailed reproduction steps for us. It should not be possible to edit metadata of a published publication in 3.2, so I think there's just a miscommunication here and some detailed reproduction steps would probably clear that up. Here's the bug report template:

**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**What application are you using?**
 OJS or OMP version X.X.X

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by verzunov** [comment]
Ok, so.
**Describe the bug**
I fill all fields on stage 3. Enter metadata include required field 'References', but when I click "Save and continue", I get error  'Please enter the references.'

**To Reproduce**
Steps to reproduce the behavior:
    Log in as Journal manager role.
    Go to Site Administration ->User&Roles->Users.
    **Click User->Login as-> Ok for change you role.**
    Click on New Submission .
    Fill all fields on stage 1. Start and click Ok.
    Upload any submission file.
    Fill all fields on stage 2. Enter metadata ** include field References as 'Required' ** .
    **If you uncheck 'Required' flag for 'References' in workflow settings then you don't see error.**
    Click 'Save and continue'  and see error.



What application are you using?
OJS  version 3.2.0.0

Additional information
![Снимок экрана от 2020-03-10 18-21-50](https://user-images.githubusercontent.com/30140013/76311926-2decdd80-62fc-11ea-8b9f-4456ef0a4643.png)

**Comment by NateWr** [comment]
Thanks @verzunov! That's cleared things up. I was able to reproduce it and find the issue.

PR:
https://github.com/pkp/pkp-lib/pull/5606

Tests only:
https://github.com/pkp/ojs/pull/2673

**Comment by verzunov** [comment]
> Thanks @verzunov! That's cleared things up. I was able to reproduce it and find the issue.

NateWr, I test you fix,

Tests only:
pkp/ojs#2673

 but it not work in my case.

**Comment by NateWr** [comment]
These are the changes you'll need to apply: https://github.com/pkp/pkp-lib/pull/5606/files
