### ISSUE TITLE
Port native import/export plugin's integration tests to v3.2

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5607]
**Describe the problem you would like to solve**
Port native import/export plugin's integration tests to v3.2

Port `https://github.com/pkp/ojs/blob/stable-3_1_2/tests/data/60-content/ImportIssueTest.php` test to v3.2

**Comment by defstat** [comment]
@asmecher 

PR:

[OJS]: pkp/ojs#2674

**Comment by asmecher** [comment]
Merged -- thanks, @defstat!
