### ISSUE TITLE
AddThis refuses to install

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#5608]
**Describe the bug**
On a clean OJS (master, aka. 3.2.0-0), when I install AddThis plugin (from the Gallery, via web interface), system refuses to install it and log shows following error:

```
Unable to install AddThis plugin due checksum issue:
[php7:notice] [pid 56] [client 172.20.0.1:35154] ojs2: Incorrect MD5 checksum!, referer: http://localhost:8082/test/management/settings/website?r=5e63d4be5e6c2
```

**Comment by asmecher** [comment]
Fixed, thanks!

**Comment by marcbria** [comment]
That was fast!! Thanks to you. ;-)
