### ISSUE TITLE
Themes shown when installed, even if they are not enabled

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#5617]
**Describe the bug**
Themes are available in Appearance to be activated just when they are installed.
This is wrong because themes should be enabled first at journal level.

**To Reproduce**
1. Setup a clean OJS 3.2 installation.
2. Go to Settings > Website > Plugins > [Plugin Gallery](http://yourjournal.org/management/settings/website)
3. Click on any theme (ie: Classic) to install it.
4. You will be redirected to Appearance.
5. Classic will be shown in the dropdown.

**Expected behavior**
As said, installing is not enough to show to allow you activate the theme.
Themes should be enabled first at journal level to be shown in this list... otherwise we will show and let journal managers use a theme that we still don't want them to use.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser Firefox
 - Version: Dockerized OJS 3.2 (over alpine-apache-php73)

Initially posted by error here: https://github.com/pkp/classic/issues/66

**Comment by NateWr** [comment]
@asmecher I've tracked this down to this query in VersionDAO:

https://github.com/pkp/pkp-lib/blob/master/classes/site/VersionDAO.inc.php#L225-L232

In particular, it's the `OR v.lazy_load <> 1` part. All of our themes except the default theme have a `0` for `v.lazy_load`.

I notice that the `ThemePlugin` extends the `LazyLoadPlugin`. However, all of our themes (except the default) have the following in the `version.xml` file:

```
	<!-- This should always be 0 -->
	<lazy-load>0</lazy-load>
```

Can you tell me more about lazy loading, how it's supposed to work, and whether a theme plugin is supposed to have that set to 0 or 1?

**Comment by NateWr** [comment]
Just so this doesn't get forgotten, here's a diff with a fix for a SQL statement VersionDAO that didn't seem to be having an impact but should probably be cleared up anyway:

```diff
diff --git a/classes/site/VersionDAO.inc.php b/classes/site/VersionDAO.inc.php
index 0c4a1afbe..bcd21f2ca 100644
--- a/classes/site/VersionDAO.inc.php
+++ b/classes/site/VersionDAO.inc.php
@@ -217,7 +217,7 @@ class VersionDAO extends DAO {
                $contextColumn = Application::getPluginSettingsContextColumnName();
                if (count($context)) {
                        assert(count($context)==1); // Context depth > 1 no longer supported here.
-                       $contextWhereClause = 'AND (' . $contextColumn . ' = ? OR v.sitewide = 1)';
+                       $contextWhereClause = 'AND (ps.' . $contextColumn . ' = ? OR v.sitewide = 1)';
                } else {
                        $contextWhereClause = '';
                }
```

**Comment by asmecher** [comment]
@NateWr, the "lazy loading" feature was introduced a long time ago when we started relying more heavily on plugins in the 2.4 codebase. Prior to lazy loading, all plugins were loaded from disk depending on their category (e.g. `generic` for every request), then each checked their `enabled` status in `journal_settings` (if that's what they were coded to do) before intervening e.g. registering hooks. That was starting to weigh a lot so lazy loading was introduced. It instead uses the `versions` table and `enabled` settings to determine which plugins need loading, and only loads them if they are as expected.

**Comment by NateWr** [comment]
@asmecher What should the `<lazy-load>` tag be in theme's `version.xml`? Our documentation says it should be `0`. But I wrote that and can't remember why it was set that way.

**Comment by asmecher** [comment]
The default theme plugin is (and has always been) a lazy-load plugin, and where possible, I recommend using that feature -- it'll reduce server load. So I would think that theme plugins work just fine as lazy-load plugins. I'm not sure why that recommendation against lazy-load is there, I'm afraid.

**Comment by NateWr** [comment]
That recommendation comes from me, and most likely resulted from me misunderstanding something years and years ago. Unfortunately, it's been our recommendation in docs and examples for ages, so probably every theme out there has this problem.

I've written upgrade scripts for 3.2.1 to manually fix all theme records in the `versions` table, and I've updated each of our themes: defaultManuscript, bootstrap3, healthSciences, classic, immersion and pragma. I'll let the theme team know but I'll probably wait to issue new releases.

I've also updated the docs hub and our example child theme.

@marcbria if you want to fix this before 3.2.1 is out, you can run the following SQL command: https://github.com/pkp/ojs/pull/2688/files#diff-a9a55a700cac452af47b370af830e42dR18

PRs:
(to be merged after `stable-3_2_0` branch created)
https://github.com/pkp/ojs/pull/2688
https://github.com/pkp/omp/pull/790

**Comment by marcbria** [comment]
I don't have any hurry, but thanks a lot for the fix. ;-)
And yes, I can confirm bad news... it happens with all the themes I enabled. :-(

thanks for your work Nate.

**Comment by NateWr** [comment]
Merged.
