### ISSUE TITLE
Implement automatic review reminders

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#562]
See http://forum.pkp.sfu.ca/t/no-automated-review-reminders-in-omp for details.

**Comment by asmecher** [comment]
A common request to consider here: use different templates for request reminders and review reminders.
http://forum.pkp.sfu.ca/t/different-templates-for-automated-review-request-reminder-and-automated-review-reminder/4540

**Comment by asmecher** [comment]
And also see the implementation of the above comment:
https://github.com/pkp/ojs/pull/701

**Comment by bozana** [comment]
@asmecher, is there a reason why these two select fields start with different numbers:
https://github.com/pkp/pkp-lib/blob/master/controllers/tab/settings/reviewStage/form/PKPReviewStageForm.inc.php#L77-L78
Does "0" make sense? 
Shall I make them equal and starting from "1"?
THANKS!!!

**Comment by bozana** [comment]
@asmecher, sorry, one more question :-) The reviewer reminders seem to be different in master and in OJS stable -- in master the manager can define the number of weeks (for the response as well as for the review) and the response due date is immediately calculated and inserted into database. Thus, should the automatic reminder happen X days after this due date? Namely, in OJS stable it happens X days after the reviewer notification...

**Comment by bozana** [comment]
@asmecher, sorry, one more question: In OMP master, when I execute runScheduledTasks.php from command line, I get 'strange' URLs in email body, e.g. like: http://localhosttools/index.php/press1/reviewer/submission... i.e. the baseUrl is not correct. In OJS stable I don't have this problem. Any tip/idea where to look...?
THANKS!!!

**Comment by asmecher** [comment]
For the reminder ranges: I don't think those defaults had too much thought put into them. Does that form have a way to disable the reminders? If not, there should be one -- probably a checkbox.

For the # of weeks vs. # of days: I don't remember well. Maybe the # of weeks sets the default for the due date, which is presented to the Editor for fine-tuning before it's inserted into the database?

I'll have a look at URL generation from the command-line tools; I suspect it's never worked on the OMP codebase, since no reminders were written.

**Comment by bozana** [comment]
@asmecher, thanks!
1) 
-- There is "Never Remind" select option that leads to not sending the emails
-- I will then change those ranges...

2) I decided for reminders in master to be sent after the due date i.e. response due date ;-)

3) I will then ignore this URL issue, make a pull request tomorrow and you could then see if you see something... 

OK? :-)

**Comment by asmecher** [comment]
OK, thanks!

**Comment by bozana** [comment]
@asmecher, guess what! :-) I have one more question :-) I don't have to copy email templates in other languages, in order to provide them, because there will be a translation round for OMP 1.2. and OS 3.0, right?

**Comment by asmecher** [comment]
Pulls (just to keep things organized):
https://github.com/pkp/omp/pull/215
https://github.com/pkp/pkp-lib/pull/1120

**Comment by asmecher** [comment]
Thanks, @bozana! I've merged the pkp-lib part. https://github.com/pkp/omp/pull/215 has a small typo that I've mentioned. Once that's fixed, please go ahead and merge. Then could you port it over to OJS master branch and test quickly?

**Comment by asmecher** [comment]
Thanks, @bozana! I'm glad to see this one finished.

**Comment by fgnievinski** [comment]
> @asmecher, guess what! :-) I have one more question :-) I don't have to copy email templates in other languages, in order to provide them, because there will be a translation round for OMP 1.2. and OS 3.0, right?

A lot of locales in OJS3 (e.g., pt_BR) remain without these two new email templates:

REVIEW_REQUEST_REMIND_AUTO_ONECLICK
REVIEW_REQUEST_REMIND_AUTO:

They are present in OJS2, thanks to the following commit:

https://github.com/pkp/ojs/pull/701/commits/4767a379cf7cb33d282fbe6722c31742d01f14d9

Could it be ported to OJS3, please?

**Comment by fgnievinski** [comment]
For the default locale (en_US), the template text borrowed from REVIEW_REQUEST for use in REVIEW_REQUEST_REMIND_AUTO (and similarly for *_ONECLICK) was later modified as part of the following commit:

https://github.com/pkp/omp/pull/215/commits/5f145844ec60f1c841caea8690004c9dd79d3dae

It'd be great if it could be ported to OJS2.

**Comment by asmecher** [comment]
@fgnievinski, the dev team doesn't maintain the translations -- we typically have a code freeze during which the other teams and community get a chance to update things like translations, documentation, etc. For the OJS 3.2 release, the freeze will begin soon (November 1st, though it may slip a little later) in preparation for a release early next year. Our pt_BR translation is a little out of date but we're always happy to receive PRs to improve it!

**Comment by fgnievinski** [comment]
@asmecher it's en_US that needs a fix in v2:

https://github.com/pkp/ojs/pull/2502

**Comment by fgnievinski** [comment]
in v3, the two new email templates are missing for up to 33 locales:

https://github.com/pkp/ojs/commit/4767a379cf7cb33d282fbe6722c31742d01f14d9

are there any tools to adjust the $variableNames? some are slightly different between v2 and v3.

**Comment by asmecher** [comment]
@fgnievinski, the devs will generally adjust the variable names manually when it's quick and easy to do so, but more complex changes are left to the translators. Unfortunately there's no automated toolset to do that.

**Comment by fgnievinski** [comment]
I've checked all locales and only 10 out of 33 have not been fixed yet.

so I've borrowed texto from REVIEW_REQUEST for use in REVIEW_REQUEST_REMIND_AUTO, as done in v2 by @bozana 

you should be getting these pull requests now, sorry they're separate, I'm doing it on the web.

**Comment by asmecher** [comment]
Thanks, @fgnievinski, received and merged; I just saw your note about sending them separately. That's not a problem, we're always happy to receive contributions.

**Comment by fgnievinski** [comment]
@asmecher: should pull request #2502, applied to branch ojs-stable-2_4_8, be applied to ojs-dev-2_4, too?

**Comment by asmecher** [comment]
@fgnievinski, I'd consider the `ojs-dev-2_4` branch to be abandoned; we have no plans to release anything more from it. We might revise `ojs-stable-2_4_8` with a particularly grievous security fix if something should arise, but that's not likely.
