### ISSUE TITLE
Installing a plugin redirects to Apparence

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#5620]
**Describe the bug**
On a clean OJS 3.2.0-0, when you install a new plugin from Gallery, you get redirect to Appearance > Theme.

**Expected behavior**
You should stay in the "Plugin Gallery" (if you think that most of the users like to install more plugins) or redirect to "Installed Plugins" (if you expect the normal use is enable what you install).

**Comment by NateWr** [comment]
This is a problem with the switch to the new tabs in the settings forms. We no longer support the `#tabname` in URLs.

Tabs can be opened by [firing an event](https://github.com/pkp/ui-library/blob/master/src/components/Tabs/Tabs.vue#L137-L146) on the global event bus. We just need to add something to the global page handling that fires this event.

So far, we don't use Vue.js across a page. But that's something I'd like to change in 3.3 or 3.4. Meanwhile, we should be able to do this in `SiteHandler.js`.

**Comment by NateWr** [comment]
The open-to-tab functionality is restored as part of #5865. Deferring this to 3.3 since that won't land until then.

**Comment by asmecher** [comment]
@NateWr and @marcbria, I don't recall seeing this behaviour recently; has this already been resolved?
