### ISSUE TITLE
Updates/corrections needed to ALM Plugin

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#563]
There are several updates needed to the [ALM plugin](https://github.com/pkp/ojs/tree/ojs-stable-2_4_6/plugins/generic/alm) that ships with OJS 2.4.6

(James removed items 1 and 2 and added to another issue)
 3. Check JS to see why monthly and yearly are not being displayed in some cases (see, for example, FB and Scopus of [this article](http://epaa.asu.edu/ojs/article/view/1724))
 4. Check bottom alignment of graph bars, they seem to be a pixel too low. 

It would be great, if possible, to also update expected API response to [v5 API](http://pkp-alm.lib.sfu.ca/docs/api/) (note change of endpoint to "works" from "articles"). This would help future-proof installations that have the plugin. 

**EDIT:** removed a couple of items and added them as [new issue](https://github.com/pkp/pkp-lib/issues/564) flagged for 2.4.7 release instead

**Comment by asmecher** [comment]
@jalperin, that's a lot of work for OJS 2.4.6-1; can you separate out the bug fixes that are necessary for this release? Tagging @jmacgreg since he was in on the conversation about this too.

**Comment by jalperin** [comment]
updated entry, there are still 4 issues, but all of them, I think, are pretty small/easy. The JS might actually not have any issues, it may be caused by CSS from the install I point to in the example, and the base install might be OK.

**Comment by asmecher** [comment]
Thanks, @jalperin. @beghelli, this is probably the biggest task holding us back from releasing OJS 2.4.6-1; could you take a look and see what you think?

**Comment by jmacgreg** [comment]
Looks good @jalperin. @beghelli, if you want help fixing/testing, just let me know.

**Comment by beghelli** [comment]
I am not sure if the social media metrics visualization by year, month or day ever worked. Only the total (comments, likes, etc) is aggregated by time, so we can't really provide likes aggregated by time because we don't have this info.

**Comment by beghelli** [comment]
To be able to upgrade to V5 would be nice if I could use any server to fetch stats from to test.

**Comment by jalperin** [comment]
pkp-alm.lib.sfu.ca  has v5.

time does work for many sources, but not all

**Comment by beghelli** [comment]
ok, I will make a conditional then. Right now we are assuming separated sources for all stats in time aggregation. I will check for that and if we don't have I will just remove the graphs and show the total. Does that sounds ok?

**Comment by asmecher** [comment]
@beghelli, is anything still active here? As far as I know, the plugin has been moved out of the main repo and we should be ready to go with OJS 2.4.7 WRT ALMs.

**Comment by jmacgreg** [comment]
Hi all, just doing a review of some ALM issues. @beghelli, can this be closed?

**Comment by beghelli** [comment]
@jmacgreg item 1 from Juan's first comment wasn't solved. There is no stats by time in the events (likes, comments), just for sources (facebook, etc). Not sure what to do.

**Comment by beghelli** [comment]
@jmacgreg @jalperin Is this still relevant? I am closing now, please, reopen if needed. Thanks.
