### ISSUE TITLE
[OMP] Chapter PDF will not display

### ISSUE THREAD

**Issue by FSaldanha** [pkp/pkp-lib#5632]
As @amandastevens said [here](https://forum.pkp.sfu.ca/t/omp-3-1-2-chapter-pdf-will-not-display/57585):

> I have encountered an issue in more than one OMP 3.1.2 installation where I add a publication format for a chapter and upload a PDF file for the chapter, then create a catalog entry for it, but on the published book page the catalog entry appears with no chapter PDF file link below it. I think I’m following the right steps and I wonder if this is a bug in OMP 3.1.2.
> 
> Are there any users of OMP 3.1.2 who have successfully uploaded chapter publication formats and made the file links available on their site - since upgrading to 3.1.2?
> 
> If yes, can you think of anything I’m doing wrong to explain why the links do not appear?

Other reports [here](https://forum.pkp.sfu.ca/t/omp-displaying-chapters-as-individual-pdfs-whole-book/36987/16) and [here](https://forum.pkp.sfu.ca/t/omp-displaying-chapters-as-individual-pdfs-whole-book/36987/19).

I found that, in `submission_file_settings` table, records were inserted with `setting_type` set as `int`. Once I change it to `string`, like before upgrade, chapter files become to be shown.

OMP version: 3.1.2-4

**Comment by asmecher** [comment]
(See in particular https://forum.pkp.sfu.ca/t/omp-3-1-2-chapter-pdf-will-not-display/57585/6.)

**Comment by asmecher** [comment]
Also cherry-picked to `stable-3_1_2`.
