### ISSUE TITLE
Handler adjustments for new versions

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5636]

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/2685
https://github.com/pkp/omp/pull/787

**Comment by NateWr** [comment]
Merged

**Comment by asmecher** [comment]
This flushed out a matching issue in `quickSubmit`, which I'll build and release shortly -- hooray for automated regression testing!

**Comment by asmecher** [comment]
@NateWr, [this check](https://github.com/pkp/ojs/blob/3_2_0-1/pages/article/ArticleHandler.inc.php#L376) means that the `download` operation can't serve up dependent files like CSS and images for HTML galleys (see https://forum.pkp.sfu.ca/t/issue-with-embedded-images-in-the-html-galleys-in-upgrading-from-ojs-2-4-8-1-or-3-1-2-4-to-ojs-3-2-x/59524). The `fileId` check needs to be broadened to include the galley's file ID *or* any of the galley's dependent files. PR coming in a sec.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/ojs/pull/2702
Could you have a look over this, @NateWr?

**Comment by NateWr** [comment]
That looks great, thanks for figuring that out!

**Comment by asmecher** [comment]
Thanks, @NateWr, also ported to OPS.
