### ISSUE TITLE
Integration tests for versioning in OPS

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5638]
OJS runs integration tests for most of the publishing and versioning workflow, and these tests will suffice to catch errors across applications. However, it would be good to add integration tests for those features which are unique to OPS. Some ideas:

- [ ] Author can not self-publish by default.
- [ ] Moderator can publish author's submission.
- [ ] Author can self-publish once they have had one submission published.
- [ ] Author [can/can't] unpublish (depending on what our default rules are).

**Comment by asmecher** [comment]
See: https://github.com/pkp/ops/pull/16 (I'll take a look, so assigning to me to clean those up)

**Comment by ajnyga** [comment]
Thanks! If I remember correctly, the tests do no cover all bullet points in Nate's list.

**Comment by asmecher** [comment]
Thanks, @ajnyga, I've updated and merged the tests based on the PR above!
