### ISSUE TITLE
Updates to the ALM plugin

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#564]
1. Either a) separate out OJS internal ALM (views) from the ALMs that come from the service; or b) make setting to disable attempting to fetch from service unless enabled. 
2. Include links to explanation of how to sign up, and to terms of service (once drafted)
3. Look at PLN model for serving up the Terms of Service from PKP servers. 
4. Make deposit checkbox OFF by default
5. Do not serve images from the remote server, put source images locally and serve using appropriate protocol (http or https, depending on settings). _note_: some images are currently broken, as they do not exist on current version of Lagotto.

**Comment by jalperin** [comment]
tagging @jmacgreg because he probably cares.

**Comment by jmacgreg** [comment]
Thanks, Juan. Some of this work may be done in collaboration with Co-Action as well, as they have some ideas on how the separating out could work (and would be able to help fund development). I'll try and get a full spec with them shortly.

**Comment by asmecher** [comment]
James, is this something that's likely to get into OJS 2.4.8, or should I defer?

**Comment by jmacgreg** [comment]
Defer!

J

**Comment by jalperin** [comment]
This issue is out of date and contains no relevant info and can probably be closed.
