### ISSUE TITLE
Language installation features hidden from single-journal installations

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5640]
When an installation only has a single language, the site-wide setup features are hidden. This includes the site-wide languages grid, which is currently the only place where languages can be installed.

From: https://forum.pkp.sfu.ca/t/install-locale-button-not-show-in-administrator-setting/58719/6

Proposed solution: When working with a single-journal installation, and when logged in as an administrator, the locale installation tools should be presented on the journal's languages grid.

Until this is resolved, the best work-around is to...
- Go into Administration
- Temporarily create a second journal
- Return to Administration and find the Settings area
- Install the additional language
- Return to Administration and delete the temporary secondary journal.

(Same applies to OMP and OPS.)

**Comment by NateWr** [comment]
This is related to https://github.com/pkp/pkp-lib/issues/5640. Maybe it makes sense to figure out precisely which site settings need to be available in a single-journal installation and separate them out -- or even just adjust the Site Settings form.

**Comment by andrzejwachalowicz** [comment]
It worked. Thanks.

**Comment by defstat** [comment]
@NateWr @asmecher 

The proposed PR, allows the code to declare the SiteSettings form tabs that should be available to a single context site. (namely the Languages Tab for now). 

Firstly I tried to add a `visible` attribute to `tabs` and `tab` Vue components, but did not succeed on that.

**PR**
[pkp-lib]: 5896

**Comment by NateWr** [comment]
Looks good @defstat, can you add a PR for OJS to run the tests?

**Comment by defstat** [comment]
@NateWr 

**PRs**
[pkp-lib]: #5896
[OJS]: pkp/ojs#2761

**Comment by NateWr** [comment]
Merged, thanks!

**Comment by asmecher** [comment]
@defstat, I'm still not seeing language installation tools when logged in as Administrator in a single-journal installation... Where should I be seeing them?

**Comment by asmecher** [comment]
Found it (with @defstat's help) -- it's still in the Administration area, now exposed for single-journal installations.
