### ISSUE TITLE
The command `npm run build` is not working since updating to OJS 3.2

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#5641]
Hi there,

i've updated the sources to OJS 3.2 and the command `npm run build` mentioned in `README.md` returns with errors.

I followed the error description and i have to execute the following commands first:

```
npm install eslint-plugin-html
npm install eslint-config-standard
npm install eslint-plugin-import
npm install eslint-plugin-node
npm install eslint-plugin-promise
npm install eslint-plugin-standard
```

This seems to be exactly the packages removed in https://github.com/pkp/ojs/commit/74eaa059e7d041a1c0daac2175c202ca9dce3388#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 which is part of https://github.com/pkp/pkp-lib/issues/3594.

Did i miss something that requires me to install the dependencies manually first?

So lonG
Daniel

**Comment by asmecher** [comment]
@ViRuSTriNiTy, I wonder if this is related to https://github.com/nodejs/node/issues/32107; I recently ran into trouble due to that. I was able to work around it by removing both `node_modules` and `package-lock.json` before installing/building, and it's been resolved since then by a node update.

**Comment by ViRuSTriNiTy** [comment]
@asmecher, yeah right. I always forget deleting the `node_modules` folder first. Issue solved, thx.

**Comment by ViRuSTriNiTy** [comment]
Faced the issue today again, deleted `node_modules` and the lock file. Sadly does not work, still the same missing modules. I can live with it as the steps required are documented here.

**Comment by asmecher** [comment]
@ViRuSTriNiTy, are you able to downgrade node to v12.16.1 or so?

**Comment by asmecher** [comment]
(@NateWr, now that we have the `master` branch independent of the `stable-3_2_0` branch, I suggest we bump our eslint toolset on the `master` branch to a newer release to solve this.)

**Comment by NateWr** [comment]
We piggy-back on the configuration of `vue-cli` that we use for UI Library and we need to keep those in sync. Usually I run updates for the cli on the ui-library repo and then copy over the config changes to `package.json`.

I just did a fresh clone of OJS off the `master` branch and I'm unable to reproduce the problem. I don't think installing those dependencies manually is the right solution, because I think those are supposed to be bundled with `eslint-plugin-vue`.

Happy to look into this further if I can get some reproduction steps. Otherwise, I could check for updates on the `vue-cli` side of things and see if that makes any difference

**Comment by asmecher** [comment]
@NateWr, I did encounter this when upgrading to NodeJS v13.12; I downgraded to v12.16.1 and was able to build without problems. From https://github.com/nodejs/node/issues/32107, it seems like the resolution is either to downgrade NodeJS (as I did), or to update the package lock and allow eslint to bump to a newer version.

**Comment by NateWr** [comment]
Yeah I am not sure if it's the same problem as the one you mention, @asmecher. I wouldn't expect it to ask to install those packages. @ViRuSTriNiTy can you provide me with the full output after running `npm run build`?

**Comment by ViRuSTriNiTy** [comment]
@NateWr I'm sorry but `npm` seems to make fun of me. I tried to reproduce the issue today but everything is fine now. I will report back with the full output when i face the issue again.
