### ISSUE TITLE
Error in journal settings form when locale active in Form but not UI

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5643]
**Describe the bug**
When a language is activated for Forms and Submissions but not active for the UI, it is not possible to save journal settings.

See the initial report and use case: https://forum.pkp.sfu.ca/t/ojs-3-2-config-issue-with-several-locales/59276

**What application are you using?**
 3.2

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/5644
https://github.com/pkp/ojs/pull/2686
https://github.com/pkp/omp/pull/788

@asmecher I resolved this by moving all of the settings forms over to `supportedFormLocales` and the publication details over to `supportedSubmissionLocales`. I think the only place that `supportedLocales` is used at the context level is for the public UI. Does that sound right to you?

I think our existing tests should catch any significant regressions here but I added a test specifically for this use-case, which I had never really considered.

**Comment by asmecher** [comment]
Thanks, @NateWr -- the changes look clean and logical. Yes, I think `supportedLocales` (as opposed to `supportedFormLocales` and `supportedSubmissionLocales`) only controls what UI locale is selected. That's actually good news, because eventually I'd like to be able to facilitate the entry of data in languages that aren't supported by the UI. (Just because the software isn't translated into a language doesn't mean metadata can't potentially be entered in that language.)

**Comment by NateWr** [comment]
> That's actually good news, because eventually I'd like to be able to facilitate the entry of data in languages that aren't supported by the UI.

I think that, with these changes, we do. That is the case that was causing the problems originally reported on the forum. They have `supportedFormLocales` and `supportedSubmissionLocales` that are not available in `supportedLocales`. So it should be possible to enter data in languages that aren't available in reader-facing UI. I'm not sure how that data would be distributed but it can be there.

**Comment by NateWr** [comment]
Merged.

**Comment by NateWr** [comment]
Found another instance of the problem when saving email templates.

PR:
https://github.com/pkp/pkp-lib/pull/5670

Tests only:
https://github.com/pkp/ojs/pull/2695

This will need to be cherry-picked to stable after merge.

**Comment by NateWr** [comment]
Merged and cherry-picked to `stable-3_2_0`.
