### ISSUE TITLE
[OPS] Unable to post preprint as a Site Admin/Moderator/Editor

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5645]
**Describe the bug**
As an author who is also the site's administrator, I am unable to post a preprint.

**To Reproduce**
1. Make sure you have the _Returning Author Screening Plugin_ installed and enabled.
2. Submit a preprint using a user that has both author and site administrator roles.
3. Attempt to post the preprint using the same user.
4. Notice the following message:

![image](https://user-images.githubusercontent.com/4059679/77097256-44c3bc00-69ef-11ea-9e81-ff9f5ce7a46b.png)

**What application are you using?**
Open Preprint Systems 3.2.0 Beta

**Additional information**
Seems to me a deadend given that as an author, I need to have at least 1 preprint posted to automatically post any subsequent preprints. However as a Site Administrator/Moderator/Editor I cannot override the plugin's behavior and manually approve.

The Moderator/Editor should be able to override any plugin behavior should they consider the preprint fit for posting. Perhaps allowing a comment to those particular cases in which the preprint fails to meet all screenings (regardless of which), justifying the reason for approving a preprint that failed the screening checks.

**Comment by asmecher** [comment]
@ajnyga, I think this is an issue in the https://github.com/pkp/returningAuthorScreening plugin...

**Comment by ajnyga** [comment]
So when you start the submission, in the first step of the submission form, which role did you choose? Manager or author?

**Comment by ajnyga** [comment]
<img width="889" alt="Screenshot 2020-03-19 at 20 46 57" src="https://user-images.githubusercontent.com/16347527/77103255-cd0f8480-6a22-11ea-8261-d9da9767c6c8.png">
I mean this selection.

**Comment by alexxxmendonca** [comment]
> Screenshot 2020-03-19 at 20 46 57I mean this selection.

Author

**Comment by ajnyga** [comment]
Yeah, so the plugin applies the rules to any user who selects the author role there. If you select manager you can publish.

We could add an override that is always applied to managers even without a stage assigment. But not sure if there are scenarious where this is not a good idea? What if it is a screening plugin that checks for example publications, I think we want to make sure that also manager users go through the same screening if they choose to submit as authors?

**Comment by ajnyga** [comment]
I want to underline that this:

> The Moderator/Editor should be able to override any plugin behavior should they consider the preprint fit for posting. Perhaps allowing a comment to those particular cases in which the preprint fails to meet all screenings (regardless of which), justifying the reason for approving a preprint that failed the screening checks.

Is of course a problem with any submissions coming from other authors. 

You can get the best idea of how things are working by creating a separate author user to the server and use that to submit stuff. And then use the another user account with manager role to look at the admin stuff and how that works. That is closer to what happens in a production site.

**Comment by alexxxmendonca** [comment]
> I think we want to make sure that also manager users go through the same screening if they choose to submit as authors?

Agreed, but much as it happened to me, I can see the same issue happening with others. I chose "Author" because I thought that was the most appropriate option.

Having another Moderator to approve it can be an alternative, but there should be an instructive text telling the user what's preventing them from posting their own preprint.

As a user, I felt like reaching a dead end.

> You can get the best idea of how things are working by creating a separate author user to the server and use that to submit stuff. And then use the another user account with manager role to look at the admin stuff and how that works. That is closer to what happens in a production site.

Correct. I want to point out that publication/post occurs normally when the author is a separate user.

**Comment by ajnyga** [comment]
But how common is it in preprint server that a manager is submitting preprints?

**Comment by alexxxmendonca** [comment]
Take SciELO Preprints for example. We are considering having Journal Editors as Moderators.

So to answer your question, if one of said Editors/Moderators decide to submit a preprint, this would happen.

**Comment by ajnyga** [comment]
> So to answer your question, if one of said Editors/Moderators decides to submit a preprint, this would happen.
But if the editor decides to submit a preprint of her own as a normal author, why would you not apply the normal screening plugin policies to that preprint as well?

**Comment by alexxxmendonca** [comment]
You would, but why was I not allowed to post the preprint when I tried to simulate that?

**Comment by asmecher** [comment]
@alexxxmendonca, I think I see @ajnyga's point in this... generally speaking we need to pick a strategy for role sharing that is consistent or we risk losing a coherent model that anyone (including us devs) can understand.

The current approach is this: when a user with several roles starts a submission, they choose what "hat" they're wearing. In your case, you chose Author, so the screening policies apply to you as though you were an author. The logic behind this strategy is clear when you consider e.g. OJS, where a manager would normally have complete control over content but when they're submitting as an author things like peer review details need to be hidden from them.

I could see an argument for preprints following the same pattern; if a manager wants to submit as an author, and didn't have a submission yet published by the press, it would fall to another manager to approve that first submission. It essentially means that the press insiders need to follow the same policies as outsiders, like in the case of peer review.

I think we should keep this issue open, though, and collect feedback if it seems to be a wide issue.

**Comment by ajnyga** [comment]
If you have a user account with both Editor and Author roles, and during the submission you choose the Author role the system will create an Author stage assigment to that submission. After that, the system will treat you as an Author when it comes to that particular submission. 

This is the same in OJS. If an Editor chooses the Author role during the submission, she will not see for example what happens in the review stage of that submission.

So if you in your test chose the Author role, the system created an Author stage assigment and the screening policies apply like they would with any other author.

If as an Editor you want add a preprint and bypass any screening policy, you can choose one of the managerial roles in the submission form. This is of course a selection that is not visible for ordinary authors with just the author role.

If any other user with an author role submits a preprint to the system, the editor user can always come in and publish on their behalf.

**Comment by alexxxmendonca** [comment]
Just pointing out that the application gave me no feedback whatsover that an extra moderation was needed, other than my own.

It felt like a bug and others might feel the same way.

**Comment by ajnyga** [comment]
Can you describe what kind of feedback and at which point of the process is needed?

**Comment by alexxxmendonca** [comment]
![image](https://user-images.githubusercontent.com/4059679/77110423-55326180-6a04-11ea-830a-cf746f591b5e.png)

This message could be updated to add something along the lines of:

_If you are a Moderator, your submission must be approved by another Moderator._

**Comment by ajnyga** [comment]
If the screening plugin is enabled and you submit as an author, the submission process will show this in the end:

<img width="910" alt="Screenshot 2020-03-19 at 22 21 09" src="https://user-images.githubusercontent.com/16347527/77111418-f7b40a00-6a2f-11ea-89a2-98af8f24fde9.png">

We can of course change the text in the screening plugin easily and add a text saying "The first submission must be approved by a Server Moderator" to the end of that sentence. I would not add "If you are a moderator", because this applies to any user who is submitting as an author.

**Comment by alexxxmendonca** [comment]
I don't think that should suffice but I'll leave that as it is and let the community respond, I might be nitpicking and overly cautious.

**Comment by ajnyga** [comment]
What would be sufficient?

**Comment by alexxxmendonca** [comment]
That is open for discussion.

Just pointing out that me, as both author and moderator, might read this "The first submission must be approved by a Server Moderator" and think "hey, I am a moderator myself so I should be able to approve my own preprint".

But that's not the case.

**Comment by asmecher** [comment]
No need to resolve this *right* now. I'd suggest giving it some thought and coming back with a few ideas.

**Comment by NateWr** [comment]
Sorry if I'm off-base here, but the confusion probably lies in the pre-publication requirement message:

> You need to have at least one published publication...

Shouldn't that be something more like this?

> A moderator must approve your first preprint before it can be posted. Once you have one approved preprint you will be allowed to publish your own updates.

And then it could just check if the user has a moderator role and, if so, return a different message:

> A moderator must approve your first preprint before it can be posted. You are not allowed to approve your own preprints.

**Comment by alexxxmendonca** [comment]
I agree with that, @NateWr.

**Comment by ajnyga** [comment]
Changed accroding to Nate's suggestion in the latest master: https://github.com/ajnyga/returningAuthorScreening

@asmecher I think you forked that and used your repo for creating a release?

This can be closed I think after the changes are taken into account the next release of the plugin.

**Comment by asmecher** [comment]
Thanks, I've cherry-picked a09372543ddbc08221007dddfc629a81af0e8d1d into pkp/returningAuthorScreening and that feature will go out with the next release of the plugin.
