### ISSUE TITLE
[OPS] Unable to add checklist item

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5651]
**Describe the bug**
As a Server Administrator, I am unabled to add Submission Preparation Checklist items. It keeps loading _ad eternum_.

**To Reproduce**
![Workflow Settings](https://user-images.githubusercontent.com/4059679/77169212-e69ee380-6a97-11ea-9a0d-aefdbbd67a74.gif)

**What application are you using?**
OPS 3.2.0 Beta

**Comment by asmecher** [comment]
@alexxxmendonca, check the server's error log for details.

**Comment by alexxxmendonca** [comment]
`[Fri Mar 20 10:44:08.246335 2020] [php7:warn] [pid 117815] [client 10.81.235.10:54924] PHP Warning: Declaration of SubmissionChecklistForm::initData($args) should be compatible with Form::initData() in /var/www/preprint_scielo_org/htdocs/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php on line 19, referer: https://homolog-preprints.scielo.org/index.php/scielo/management/settings/workflow
[Fri Mar 20 10:44:08.246489 2020] [php7:warn] [pid 117815] [client 10.81.235.10:54924] PHP Warning: array_keys() expects parameter 1 to be array, null given in /var/www/preprint_scielo_org/htdocs/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php on line 98, referer: https://homolog-preprints.scielo.org/index.php/scielo/management/settings/workflow
[Fri Mar 20 10:44:08.246512 2020] [php7:warn] [pid 117815] [client 10.81.235.10:54924] PHP Warning: max(): When only one parameter is given, it must be an array in /var/www/preprint_scielo_org/htdocs/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php on line 98, referer: https://homolog-preprints.scielo.org/index.php/scielo/management/settings/workflow
[Fri Mar 20 10:44:08.246518 2020] [php7:warn] [pid 117815] [client 10.81.235.10:54924] PHP Warning: Invalid argument supplied for foreach() in /var/www/preprint_scielo_org/htdocs/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php on line 101, referer: https://homolog-preprints.scielo.org/index.php/scielo/management/settings/workflow
[Fri Mar 20 10:44:08.247837 2020] [php7:notice] [pid 117815] [client 10.81.235.10:54924] ops: DB Error: Unknown column ‘setting_type’ in ‘field list’ Query: INSERT INTO journal_settings\n\t\t\t\t\t(journal_id, setting_name, setting_value, setting_type, locale)\n\t\t\t\t\tVALUES (?, ?, ?, ?, ?), referer: https://homolog-preprints.scielo.org/index.php/scielo/management/settings/workflow`

**Comment by asmecher** [comment]
@alexxxmendonca, I only see warnings, not errors -- I would expect something with the word "Error" to be logged. If that's not the case, I'd double-check that your PHP errors/warnings are directed to the log rather than the web browser.

**Comment by alexxxmendonca** [comment]
Our tech guy was unable to assist. According to him, there are no errors.

**Comment by ajnyga** [comment]
This is the error:

```
[23-Mar-2020 16:06:40 Europe/Berlin] PHP Fatal error:  Uncaught Exception: DB Error: Unknown column 'setting_type' in 'field list' Query: INSERT INTO journal_settings
					(journal_id, setting_name, setting_value, setting_type, locale)
					VALUES (?, ?, ?, ?, ?) in /Applications/XAMPP/xamppfiles/htdocs/ops-test/lib/pkp/classes/db/DAO.inc.php:703
```
Suspect that the code is in pkp-lib so could apply to OJS as well. I will check this later today. I am just fixing another bug in OJS.

**Comment by ajnyga** [comment]
It was due to a missed cherry-pick. OJS restored the setting_type column in late February, but I missed that change. This commit is a fix for the problem, but requires OPS to be installed again or alternatively the database table needs to be edited to include the missing column.

https://github.com/ajnyga/ojs/commit/0b3b9cdcf0bc4fe62169cbe0d41bd8dd6c1366bb

**Comment by alexxxmendonca** [comment]
Thanks for picking the error, @ajnyga !

**Comment by alexxxmendonca** [comment]
I believe this can be closed as well, @ajnyga?

**Comment by asmecher** [comment]
I can confirm!

**Comment by ajnyga** [comment]
yes sure! I just can't close tickets here. Unless they are my own of course...
