### ISSUE TITLE
Migrate Google Scholar plugin to OPS and update for preprints

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5654]
From GS: here's a firm list of preprint metatags for indexing: 

> citation_author 
> citation_author_institution
> (note that the affiliation tag would immediately follow the corresponding author tag) 
> citation_title
> citation_online_date // effectively the same as citation_date or citation_publication_date
> citation_pdf_url
> 
> All else is optional. 

Steps needed for Scholar tags to be added to OPS: 

1. migrate plugin over. 
2. update plugin's date fields to reflect "online" vs. "published". 
3. test/review with GS.

**Comment by jmacgreg** [comment]
CCing @alexxxmendonca.

**Comment by diegoabadan** [comment]
Perhaps it would be interesting to have a unified plugin, which, depending on the application, includes the appropriate tags.

If application = OJS
_OJS meta tags_

If application = OPS
_OPS meta tags_

**Comment by ajnyga** [comment]
yeah I was looking at this a couple of weeks ago and also think that @diegoabadan's approach is the best one. @asmecher this requires that we move the gs plugin to a separate repo. What do you think?

Also, worth considering if we combine the DC plugin and the GS plugin while we are at it? We have them separately when most people just enable both?

**Comment by asmecher** [comment]
Hi all -- totally in favour of having a shared plugin for OJS and OPS. I'll move it to its own repo and set up a submodule in OJS `master`.

**Comment by asmecher** [comment]
Done -- https://github.com/pkp/googleScholar

I'm not in favour of combining the Google Scholar and Dublin Core plugins, though; one is a standard and one is proprietary. Both should be enabled by default.

@ajnyga, should I transform the Dublin Core plugin into a submodule as well?

**Comment by ajnyga** [comment]
Why not. I was just thinking if we could have one plugin that takes care of both. "Landing page metadata plugin" or something?

**Comment by ajnyga** [comment]
Also considering:

```
<meta name="citation_doi" content="">
<meta name="citation_abstract_html_url" content="">
<meta name="citation_keywords" content="">
<meta name="citation_language" content="">
<meta name="citation_publisher" content="">
```

**Comment by ajnyga** [comment]
Initial pr: https://github.com/pkp/googleScholar/pull/1

**Comment by ajnyga** [comment]
@asmecher also a separate plugin for Open Graph: https://github.com/ajnyga/openGraph

I first thought of adding these to the dc plugin, but realized that some themes might be adding these already. So maybe better allow journals/servers to control the way they want to add these by using a separate plugin.

You are free to copy that to pkp github.

**Comment by asmecher** [comment]
Great, nice and clean! I'm perfectly happy to have it stay on your account, unless you'd rather it move to PKP -- but do you think we should add a submodule and distribute this by default?

**Comment by ajnyga** [comment]
Really up to you, I am not sure what your criteria has been in the past?

**Comment by asmecher** [comment]
Generally we want to facilitate third-party maintenance of the plugin ecosystem. I'm hoping to build the sense that there are good quality, well-maintained 3rd-party plugins; there was a sense in OJS 2.x that we only kind of had a plugin ecosystem and it was not very lively. But of course this does presume a maintenance burden on your part. In the end it's not a big deal either way and it's up to you. Do you have any interest in tinkering with automated testing?

**Comment by ajnyga** [comment]
In general I am happy to maintain plugins and I guess this one won't be a lot of work. Can you do a review and I will do a release for the gallery.

**Comment by asmecher** [comment]
@ajnyga, is this issue ready to be closed? openGraph is in the plugin gallery, and https://github.com/pkp/googleScholar/pull/1 was merged.

**Comment by ajnyga** [comment]
Just thinking if we should handle OMP in in the separate GS plugin as well?

But I could handle it here once @jmacgreg  hears from Google: https://github.com/pkp/pkp-lib/issues/5686

**Comment by ajnyga** [comment]
@asmecher this is still open...

**Comment by asmecher** [comment]
Got it, thanks!
