### ISSUE TITLE
OPS: Add article links to sitemap XML file

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5656]
Since there is no "issue" context in OPS, there is no great way for a crawler to crawl OPS' sitemap and find article link lists. Google Scholar recommends adding all article URLs to the sitemap. We discussed how this might work with a very large set of links (see #5655) but for now at the very least, the articles themselves should be included in the top-level sitemap.

**Comment by ajnyga** [comment]
This has been added to both OPS master and 3.2.0 stable, so closing. The sitemap will now just list all available links so #5655 needs to be considered at some point.

**Comment by asmecher** [comment]
Thanks, @jmacgreg!

**Comment by asmecher** [comment]
Oops, I mean thanks, @ajnyga!

**Comment by diegoabadan** [comment]
I applied this update to a test OSP and unpublished submissions were also inserted. Can you please check?

**Comment by asmecher** [comment]
Thanks, @diegoabadan -- reopening for review of the above comment, @ajnyga!

**Comment by ajnyga** [comment]
Thanks! Status parameter was missing, I will let the tests run and will merge to master + cherry-pick to stable.

**Comment by ajnyga** [comment]
@asmecher this should be closed as well

**Comment by asmecher** [comment]
Closing!
