### ISSUE TITLE
Setting up new custom block failed because in consistent warning

### ISSUE THREAD

**Issue by navotera** [pkp/pkp-lib#5658]
I am using OJS 3.2.0-1. 

Here is the problem. 
When creating a new custom block on we cannot use the space. For example, this is invalid and failed : 
**Make Submission**

![image](https://user-images.githubusercontent.com/1424851/77246895-33341b80-6c5e-11ea-914b-d23a6141db23.png)

However, when I try to create new custom block **with underscore** it is saved on the database but when to try to activate it lead to the failure process because it does not allow to activate any custom block if it has any underscore. 

![image](https://user-images.githubusercontent.com/1424851/77246939-a8075580-6c5e-11ea-9215-58f835152614.png)

This is a confusing and inconsistent error. 

The other problem is : 
When the user has created a new custom block from custom block manager and get back to activation of those custom block. The Appearance -> setup menu does not refresh automatically, need to hard refresh the browser to show the additional custom block. This is a downgrade feature from the previous OJS version. 

.

**Comment by navotera** [comment]
The other character also error :
![image](https://user-images.githubusercontent.com/1424851/77247295-392bfb80-6c62-11ea-8b30-9f8d9a4ecb2f.png)

**Comment by asmecher** [comment]
Thanks for reporting, @navotera -- this will be fixed as part of https://github.com/pkp/customBlockManager/issues/17.

**Comment by navotera** [comment]
Hi @asmecher 

Thank for your response, by visiting the URL you have provided. 
"Have the symbolic name auto-generated (using e.g. uniqid) and not presented to the user anywhere."

Please make the custom block name appear on HTML generated on the ojs frontend presentation. By using this any ojs user can make any CSS custom modification for any block that he had created on the admin panel. 

For example the current method is fine : 
1. User create the makeSubmission block on the back panel
2. The makeSubmission block would appear on the HTML code as : 
![image](https://user-images.githubusercontent.com/1424851/77376931-3b966e80-6da4-11ea-915a-53a2566a36f5.png)

By implementing this any user can create or map any custom block that can be styled on custom css or by any theme. 

Thanks
