### ISSUE TITLE
Save button disabled after unpublishing a version

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5659]
**Describe the bug**
After unpublishing a version, the save buttons remain disabled and the version can not be edited until the page is reloaded. The grids (contributors, galleys) do not reload into their editable state.

**To Reproduce**
1. Go to a published submission.
2. Click on the Publication tab.
3. Click Unpublish.
4. See that the Save buttons for the forms are disabled.

**What application are you using?**
 OJS

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ui-library/pull/82

Tests only:
https://github.com/pkp/ojs/pull/2691

**Comment by NateWr** [comment]
Merge and cherry-picked to `stable-3_2_0`.

**Comment by ajnyga** [comment]
I am still seeing this happening with the Contributors grid and the Galleys grid. The form save button does work now but the grid's have to be refreshed with a page reload.

**Comment by asmecher** [comment]
This got re-opened after https://github.com/pkp/pkp-lib/milestone/41 was closed -- moving up to https://github.com/pkp/pkp-lib/milestone/43 so it doesn't get forgotten.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ui-library/pull/91

Tests only:
https://github.com/pkp/ojs/pull/2759

**Comment by NateWr** [comment]
Merged!

**Comment by mkrt-oleg** [comment]
I'm using OJS 3.2.0.2 and this problem still exists.

**Comment by asmecher** [comment]
@mkrt-oleg, this has already been fixed in newer releases.
