### ISSUE TITLE
[OMP] Creating a submission without an author role results in an error

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#566]
It is currently possible to begin a new submission process in OMP with just Press Manager privileges.  On Step two, it is possible to upload a file, but submitting the modal results in the following SQL error for notifications:

Input Array does not match ?: SELECT * FROM notifications WHERE assoc_type = 1048585 AND assoc_id = 1
 AND user_id = 1 AND context_id = 16777238 AND type = 

This is because the DAO methods for fetching ROLE_ID_AUTHOR for submissions for author notifications return an empty set.  This causes null author ids to be propagated, resulting in an argument shift for some methods.  In the previous example, the user_id of 1 is actually the context_id and type should be 16777238.

Suggest removing the submission start button from the dashboard unless the user has author privileges within the press.

**Comment by asmecher** [comment]
Actually, that's a mis-diagnosis. This commit fixed it: https://github.com/pkp/pkp-lib/commit/275d9d8dfb501ff8fbbfe3d57b964083570fc49d
The problem was that we were using an implicit boolean cast in one case, and `isset(...)` in another.
