### ISSUE TITLE
[OJS] In some cases discussions grid not loading for reviewers, 3.2 master

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5661]
The comparison here https://github.com/pkp/pkp-lib/blob/master/classes/security/authorization/internal/QueryUserAccessibleWorkflowStageRequiredPolicy.inc.php#L41 does not work in all environment leading into an error 
"You don’t currently have access to that stage of the workflow"

Simple fix is to compare with ==

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/5662

Tests only:
https://github.com/pkp/ojs/pull/2690

**Comment by ajnyga** [comment]
the tests passed

**Comment by NateWr** [comment]
Merged and cherry-pick to `stable-3_2_0`.
