### ISSUE TITLE
Can't upload cover image in Quick Submit with v3.2

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5663]
**Describe the bug**
It is not possible to upload a cover image when making a submission with the [Quick Submit](https://github.com/pkp/quickSubmit) plugin in OJS 3.2. The plugin uses a form class that extends the `SettingsFileUploadForm`, which was removed in OJS 3.2.

**To Reproduce**
1. Install and enable the Quick Submit plugin.
2. Go to Tools > Import/Export > QuickSubmit.
3. Click the button to uplload a cover image.
4. See the error message.

**What application are you using?**
 3.2

**Additional information**
@asmecher I'm not sure what the right approach is here. I tried just adding a `<input type="file" ...>` field for a simple workaround, but the `$_FILES` global is empty upon form submission. :confused:

**Comment by asmecher** [comment]
Restored the guts of the missing class, but only in the plugin repo. Uploading cover images works again.
