### ISSUE TITLE
Add config.inc.php parameter to override system cURL's certification failure issue (error code 60)

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5664]
**Describe the problem you would like to solve**
When a `curl` call is made to an `https` url, a default certification file should be defined, in order for the call to succeed. (for example at the `curl.cainfo` parameter of `php.ini` configuration file). This parameter is not defined by default.

**Describe the solution you'd like**
A `config.inc.php` parameter could be added to OJS/OMP/OPS, and get a default value on an installation folder, in order for the code to try to use this by default, and if that fails, use the system configuration. The user can comment this configuration parameter as well, in order for the system configuration to be used.

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**
[PKP-LIB]: #5821
[OJS]: pkp/ojs#2734
[OMP]: pkp/omp#805

That can be applied to **orchidProfile** plugin and **pln** plugin as well.

**Comment by asmecher** [comment]
Looks good, @defstat, please go ahead and merge (and please port this to the PLN plugin -- I suppose this will justify the creation of a `stable-3_2_0` branch that does not include this change). @withanage, a heads-up about porting this to the ORCID plugin.

**Comment by NateWr** [comment]
Does this need to be added to OMP as well?

**Comment by defstat** [comment]
@NateWr There is a PR for OMP as well, having the configuration parameter added on config.template.

**Comment by NateWr** [comment]
Sorry! Yes, I meant OPS. :joy: All these acronyms...

**Comment by defstat** [comment]
@asmecher I added this PR for PLN, but I am sure I had to add the PR another way...

**PR**
[PLN Plugin]: defstat/pln#48

**Comment by defstat** [comment]
@asmecher @NateWr 

**PR**
[OPS]: pkp/ops#19

**Comment by asmecher** [comment]
@defstat, could you create a `stable-3_2_0` branch on the PLN repo? If I merge defstat/pln#48 now, it'll break compatibility with 3.2.0-x.

**Comment by defstat** [comment]
@asmecher I think there is already a stable-3_2_0 branch at pkp/pln repository.

I added this PR for the issue
[PLN]: pkp/pln#5
