### ISSUE TITLE
OJS 3.2.01 Article report can't generat

### ISSUE THREAD

**Issue by zalamuia** [pkp/pkp-lib#5665]
OJS 3.2.0-1

OS platform | Linux
-- | --
PHP version | 7.2.17
Apache version | Apache/2.4.6 (CentOS)
Database driver | mysqli
Database server version | 5.5.60-MariaDB

![ojs-1](https://user-images.githubusercontent.com/61810595/77380723-db5cf800-6db6-11ea-8ea1-071294c46f4f.jpg)
![ojs-2](https://user-images.githubusercontent.com/61810595/77380725-dc8e2500-6db6-11ea-827d-f4adad5f1ac4.jpg)

Browser used : Chrome, Mozilla, Edge

OJS 3.2.0-1 Article report can't generate

ALL plugin are updated,

It produce CSV file with single line "

<h1>Unrecognized DAO ArticleDAO!</h1>
--

"
View Report results "Unrecognized DAO PublishedArticleDAO!"

Counter Article report results "Unrecognized DAO ArticleDAO!"

with ENABLE plugin paper can't be accepted (never ended loop) however OJS 3.1.2.4 it is O

Custom report generation never ending but fresh installation is ok.

Can't view Activity Log & Notes using Chrome 64 browser

Thanking you.

Zahirul

**Comment by asmecher** [comment]
@zalamuia, I suspect you have a plugin installed that's not updated for compatibility with OJS 3.2.x. You can find out which by turning on `show_stacktrace` in `config.inc.php` and getting the error message again.

**Comment by zalamuia** [comment]
Dear Mr Alec,

Thanks for your advise. I have checked and found following info

<h1>Unrecognized DAO ArticleDAO!</h1><h4>Stack   Trace:</h4>
--
<strong>File:</strong>   /home/ojs/ejournal/plugins/reports/articles/ArticleReportDAO.inc.php line   27<br />
<strong>Function:</strong>   DAORegistry::getDAO("ArticleDAO")<br />
<br/> |   |   |   |   |   |  
<strong>File:</strong>   /home/ojs/ejournal/plugins/reports/articles/ArticleReportPlugin.inc.php line   67<br />
<strong>Function:</strong>   ArticleReportDAO->getArticleReport(1)<br />
<br/> |   |   |   |   |   |  
<strong>File:</strong>   /home/ojs/ejournal/lib/pkp/pages/management/PKPToolsHandler.inc.php line   155<br />
<strong>Function:</strong>   ArticleReportPlugin->display(Array(0) | Object(Request))<br /> |   |   |  
<br/> |   |   |   |   |   |  
<strong>File:</strong>   /home/ojs/ejournal/lib/pkp/pages/management/PKPToolsHandler.inc.php line   58<br />
<strong>Function:</strong>   PKPToolsHandler->report(Array(0) | Object(Request))<br /> |   |   |  
<br/> |   |   |   |   |   |  
<strong>File:</strong>   /home/ojs/ejournal/lib/pkp/classes/core/PKPRouter.inc.php line 391<br   />
<strong>Function:</strong>   PKPToolsHandler->tools(Array(0) | Object(Request))<br /> |   |   |  
<br/> |   |   |   |   |   |  
<strong>File:</strong>   /home/ojs/ejournal/lib/pkp/classes/core/PKPPageRouter.inc.php line 231<br   />
<strong>Function:</strong>   PKPRouter->_authorizeInitializeAndCallRequest(Array(2) | Object(Request) | Array(1) | False)<br /> |   |  
<br/> |   |   |   |   |   |  
<strong>File:</strong>   /home/ojs/ejournal/lib/pkp/classes/core/Dispatcher.inc.php line 143<br   />
<strong>Function:</strong>   PKPPageRouter->route(Object(Request))<br />
<br/> |   |   |   |   |   |  
<strong>File:</strong>   /home/ojs/ejournal/lib/pkp/classes/core/PKPApplication.inc.php line 278<br   />
<strong>Function:</strong>   Dispatcher->dispatch(Object(Request))<br />
<br/> |   |   |   |   |   |  
<strong>File:</strong>   /home/ojs/ejournal/index.php line 68<br />
<strong>Function:</strong>   PKPApplication->execute()<br /> |  
<br/> |   |   |   |   |   |  

I have deleted the report plugin and copied from newly downloaded OJ3.2.0-1 but I got following error
This site can’t be reached The webpage at https://journals.iium.edu.my/ejournal/index.php/iiumej/management/tools/report?pluginName=ArticleReportPlugin might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

HOWEVER, other ojs site is replaced with new reports plugin without deletion works fine.

Thanks.

Zahirul

**Comment by asmecher** [comment]
@zalamuia, that was definitely code older than 3.2.0-1 running in your OJS installation; I'd double-check the method you used to update your code to ensure you're not mixing two versions together.

For the new problem, check your PHP error log for details.

**Comment by zalamuia** [comment]
I have updated through update process. 
Some of the journal sites have no problem but few have problem.
However, I got followings


<br />
--
<b>Fatal error</b>:  Uncaught Error: Call to a member function   getLocalizedGivenName() on null in   /home/ojs/ejournal/plugins/reports/articles/ArticleReportPlugin.inc.php:114
Stack trace:
#0   /home/ojs/ejournal/lib/pkp/pages/management/PKPToolsHandler.inc.php(155):   ArticleReportPlugin-&gt;display(Array
#1   /home/ojs/ejournal/lib/pkp/pages/management/PKPToolsHandler.inc.php(58):   PKPToolsHandler-&gt;report(Array
#2   /home/ojs/ejournal/lib/pkp/classes/core/PKPRouter.inc.php(391):   PKPToolsHandler-&gt;tools(Array
#3   /home/ojs/ejournal/lib/pkp/classes/core/PKPPageRouter.inc.php(231):   PKPRouter-&gt;_authorizeInitializeAndCallRequest(Array
#4   /home/ojs/ejournal/lib/pkp/classes/core/Dispatcher.inc.php(143):   PKPPageRouter-&gt;route(Object(Request))
#5   /home/ojs/ejournal/lib/pkp/classes/core/PKPApplication.inc.php(278):   Dispatcher-&gt;dispatch(Object(Request))
#6 /home/ojs/ejournal/index.php(68):   PKPApplication-&gt;execute()
#7 {main}
thrown in   <b>/home/ojs/ejournal/plugins/reports/articles/ArticleReportPlugin.inc.php</b>   on line <b>114</b><br />


Thanking you.

**Comment by asmecher** [comment]
@zalamuia, this looks like a data error to me. What do you get for the following query?
```
SELECT e.editor_id FROM section_editors e LEFT JOIN users u ON (u.user_id = e.editor_id) WHERE u.user_id IS NULL;
```
If you get any results, you'll need to remove those entries from the `section_editors` table.

**Comment by zalamuia** [comment]
Dear Mr Alec,

generate error #1054 - Unknown column 'e.editor_id' in 'field list' after ruining the query.

Only one entry is there in section_editors. 

 `section_editors` (`context_id`, `section_id`, `user_id`) VALUES (1, 14, 616);

after deleting this entry also not helping to obtain the report.

Other journal without any data in section_editors and another journal with data can managed to obtain report. 

few other journals I can't get the result. I have around 25 installation journal. 

Thanks.

Zahirul

**Comment by asmecher** [comment]
@zalamuia, can you try this database query?
```
SELECT stage_assignments.* FROM stage_assignments LEFT JOIN users ON stage_assignments.user_id = users.user_id WHERE users.user_id IS NULL;
```
This will identify any stage assignments that correspond to nonexistent users. If any results are shown, try removing them. (Please make a backup of your database before doing this!)

**Comment by zalamuia** [comment]
Dear Mr Alec,

I have tried the query and found two entries. After removing those entries I can generate report. Thanks for your support for solving this issue.

Thanking you.
Zahirul

**Comment by asmecher** [comment]
Glad to hear it!
