### ISSUE TITLE
Edit User, the password may not blank ??

### ISSUE THREAD

**Issue by navotera** [pkp/pkp-lib#5666]
**Describe the bug**
Journal Manager when edit any user should fill the user password, even it is not intended to to do

**To Reproduce**
1. Go to User and Roles
2. Click on Edit User
3. Scroll down to Edit Role / User

![image](https://user-images.githubusercontent.com/1424851/77381228-e2ccd300-6daf-11ea-8868-903ac57b591e.png)

**What application are you using?**
 OJS 3.2.0-1

**Comment by asmecher** [comment]
@ctgraham, this issue is a regression introduced by https://github.com/pkp/pkp-lib/commit/797a89bbf4fa52fbc08c9961d4f72a3835180032 -- do you have time to take a look at this?

**Comment by ctgraham** [comment]
Concur with the observation in Slack:
https://github.com/pkp/pkp-lib/commit/797a89bbf4fa52fbc08c9961d4f72a3835180032#r38075906

**Comment by ctgraham** [comment]
Resolved with direct commit.

**Comment by asmecher** [comment]
Thanks, @ctgraham -- I've also cherry-picked this to `stable-3_2_0` for release with OJS/OMP 3.2.0-2 and OPS 3.2.0-1 [unless we skip directly to -2 for OPS].
