### ISSUE TITLE
[OPS] Searching doesn't work

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5673]
**Describe the bug**
Searching for preprints doesn't work.

**To Reproduce**
1. Have at least 1 preprint posted
2. Click on 'Search'
3. Search for a posted preprint by title, for example.
4. No results are matched.

**What application are you using?**
OPS 3.2.0 Beta

**Additional information**
![SciELO Preprints](https://user-images.githubusercontent.com/4059679/77660382-03d02800-6f58-11ea-8800-27480fd56a45.gif)

**Comment by asmecher** [comment]
@alexxxmendonca, search results are cached for 24 hours unless you flush the database cache. Is it possible that the cache is causing this? Can you try either flushing the cache in the administration interface, or trying again once 24 hours have elapsed?

**Comment by alexxxmendonca** [comment]
I flushed the cache in the administration interface but the issue persists.

The preprint I'm trying to search for was submitted on March 19.

**Comment by asmecher** [comment]
OK, next steps to debug this...
- Take a backup of your database so we can investigate later
- Then, try running `php tools/rebuildSearchIndex.php` on the command line
- Flush your data cache in the admin interface
- Try searching again.

**Comment by alexxxmendonca** [comment]
Hi @asmecher 

Thanks for the instructions, it worked.

Do you think this will happen again?

**Comment by alexxxmendonca** [comment]
Hi @asmecher 

Just FYI, the issue happened again on the production site.

We did as you suggested (runned the `php tools/rebuildSearchIndex.php` command line) but the problem persists.

Try searching for "covid" here:

https://preprints.scielo.org/

**Comment by ajnyga** [comment]
hmm, @asmecher , when does OJS build search index for a new submission?

**Comment by asmecher** [comment]
See the `publish` and `unpublish` functions in `PKPPublicationService`.

**Comment by alexxxmendonca** [comment]
Apparently this was fixed. It's no longer happening on OPS 3.2.1.

Can we close this issue?

**Comment by asmecher** [comment]
Happy to, thanks!
