### ISSUE TITLE
Introduce code formatter to enforce code style

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5678]
Use https://github.com/squizlabs/PHP_CodeSniffer or https://github.com/FriendsOfPHP/PHP-CS-Fixer to format the PHP codebase according to a particular coding style. Add this check to the validation tests in Travis so that all pull requests are checked for consistency. And if possible, create a pre-commit hook so that formatting occurs automatically on commit.

**Comment by NateWr** [comment]
Codesniffer has a beautifier and fixer that can automatically apply formatting changes: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically

**Comment by NateWr** [comment]
This looks like it won't be that difficult after all. Here is some initial work that applies an automated formatter to OJS and pkp-lib:

https://github.com/pkp/ojs/pull/3030
https://github.com/pkp/pkp-lib/pull/6699

OJS runs as a pre-commit hook by using the husky node package. It's a little bit harder to do this in pkp-lib, because we don't have any node dependencies in that repository. I believe something could be done by using [composer-git-hooks](https://github.com/BrainMaestro/composer-git-hooks) but I'm not sure how to only lint the changed files. There's some bash scripting to do this [here](https://tech.zumba.com/2014/04/14/control-code-quality/), but it probably isn't compatible with all OS's.

**Comment by henriqueramos** [comment]
> This looks like it won't be that difficult after all. Here is some initial work that applies an automated formatter to OJS and pkp-lib:
> 
> [pkp/ojs#3030](https://github.com/pkp/ojs/pull/3030)
> #6699
> 
> OJS runs as a pre-commit hook by using the husky node package. It's a little bit harder to do this in pkp-lib, because we don't have any node dependencies in that repository. I believe something could be done by using [composer-git-hooks](https://github.com/BrainMaestro/composer-git-hooks) but I'm not sure how to only lint the changed files. There's some bash scripting to do this [here](https://tech.zumba.com/2014/04/14/control-code-quality/), but it probably isn't compatible with all OS's.

We could create a [`composer script`](https://getcomposer.org/doc/articles/scripts.md) to call the linter, and add it into [`git pre-commit hook`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks).

The only downside using `pre-commit` could be on Windows, there's a [few workarounds](https://www.tygertec.com/git-hooks-practical-uses-windows/) for this, but I don't have experience using those workarounds.

**Comment by henriqueramos** [comment]
> but I'm not sure how to only lint the changed files. There's some bash scripting to do this [here](https://tech.zumba.com/2014/04/14/control-code-quality/), but it probably isn't compatible with all OS's.

Seems there's a package called [Symplify//easy-coding-standard](https://github.com/symplify/easy-coding-standard) doing this by default [ref: https://stackoverflow.com/a/44102546].

**Comment by NateWr** [comment]
Thanks @henriqueramos. It looks like this runs on a cache file, and the php-cs-fixer is doing this automatically as well. This might be enough, but isn't quite the same as running the fixer only against the committed files. For example, if I make changes to 10 files but only commit 2 of them, it will still run on all 10.

Maybe this doesn't matter and the cache feature is enough. In that case it shouldn't be too difficult to add a pre-commit hook to lib/pkp too.

**Comment by NateWr** [comment]
Ok, I've made some progress with the [composer-git-hooks](https://github.com/BrainMaestro/composer-git-hooks) libary. It's easy to add a pre-commit hook. However, I'm struggling to figure out how run the php fixer on only the files that are modified, and then how to add those modifications to the commit.

Here's the hook that I have now:

```
		"hooks": {
			"pre-commit": [
				"./lib/vendor/bin/php-cs-fixer fix --config .php_cs --allow-risky=yes"
			]
		}
```

This runs the fixer, but the changes aren't applied to the commit. So you end up with the changes you committed and then the changes from the fixer still waiting to be committed.

I've tried using this example that I found online:

```
		"hooks": {
			"pre-commit": [
				"echo committing as $(git config user.email)",
				"./lib/vendor/bin/php-cs-fixer fix --config .php_cs --allow-risky=yes",
				"git add ."
			]
		}
```

This adds the files after they've been changed so that the fixes are committed too. But `git add .` adds every changed file, whether or not they were staged for commit.

The way that Husky works (the node package running on OJS), it only runs the php-cs-fixer on the files staged for commit. There must be some way to do the same, but I'm struggling to imagine how to do this. My command line skills are not that great. But is there a set of commands we could use that would identify the files staged for commit, run `php-cs-fixer` against them, then add _only those files_ to the commit?

@asmecher and @henriqueramos do you have any ideas?

**Comment by NateWr** [comment]
@asmecher and @jonasraoni I wanted to bring [our conversation](https://github.com/pkp/pkp-lib/pull/6728/files/90f1771d045a8af30af545a1bec9adc457ef6357#r571642125) about docblocks and type declarations over here. With type hinting, there is a php-cs option to [remove superflous @param](https://cs.symfony.com/doc/rules/phpdoc/no_superfluous_phpdoc_tags.html) tags.

So, where we are able to add type hinting, we can end up with `@param` tags that don't provide useful info:

```php
/**
 * Example
 *
 * @param string $str
 * @return string
 */
function (string $str) : string
{
	...
}
```

In such cases, php-cs will remove the the tags:

```php
/**
 * Example
 */
function (string $str) : string
{
	...
}
```

But it would leave the tags in cases where additional descriptions were provided:

```php
/**
 * Example
 *
 * @param string $str A file ID or URL
 * @return string The full path to the file
 */
function (string $str) : string
{
	...
}
```

Would that be a problem for doxygen? Should we always enforce these declarations even when they provide no useful info? As I work on some of the facade/type hinting stuff, I'm finding it can be very convenient to not have to write the param declarations out:

```php
class Query
{

	public function get(int $id) : Context
	{
		return DAO::get($id);
	}

	public function getCount(Collector $query) : int
	{
		return DAO::getCount($query);
	}

	public function getIds(Collector $query) : Collection
	{
		return DAO::getIds($query);
	}

	public function getMany(Collector $query) : Collection
	{
		return DAO::getMany($query);
	}

	public function getCollector() : Collector
	{
		return new Collector();
	}
}
```

**Comment by jonasraoni** [comment]
Since the tags aren't required, I support omitting them if there's nothing special to describe.

In fact, I'd like the standard to be smarter and forward the task of guessing to the tooling... So a function with a well defined return type could use such tag `@return Return should be part of the description`. But the odds of getting such compatibility break accepted must be very small =]

**Comment by asmecher** [comment]
Thanks, @NateWr, I support that. Doxygen appears to behave fine when docblocks are omitted. And Laravel appears to use phpDocumentor, which is enough justification IMO to move to that toolset anyway.

**Comment by defstat** [comment]
@NateWr just a small note regarding a rule: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/doc/rules/comment/comment_to_phpdoc.rst#rule-comment_to_phpdoc

**Comment by asmecher** [comment]
@NateWr, to apply the formatter to only the files modified by the commit, try:
```
"pre-commit": [
    "git diff --name-only --cached | xargs ./lib/vendor/bin/php-cs-fixer fix --allow-risky=yes && git add -u"
]
```
- `git diff --name-only --cached` lists all filenames that are in the staged commit
- `xargs ./lib/vendor/bin/php-cs-fixer` uses `xargs` to pass those filenames as arguments to the `php-cs-fixer` command
- `git add -u` then stages any modified files for inclusion in the current commit.

But do we want to jam the code formatting into the same commit, or do we want it to go into a commit of its own?

**Comment by NateWr** [comment]
Thanks @asmecher! I'll play around with that. But would it work on a Windows machine? Do they have access to `xargs`?

> But do we want to jam the code formatting into the same commit, or do we want it to go into a commit of its own?

The way it works in UI Library is that it goes straight into the same commit. This keeps the commit history really clean because you get one commit, properly formatted.

**Comment by jonasraoni** [comment]
FYI there's also [Psalm](https://psalm.dev), which is a kind of TypeScript for PHP. I guess that at this moment it will create a lot of pollution, but I think it might be useful later.

**Comment by jonasraoni** [comment]
> But would it work on a Windows machine? Do they have access to `xargs`?

Maybe we can assume the user has the PHP executable accessible, and use it instead of shell commands 🤔

About Windows, it has [PowerShell](https://docs.microsoft.com/en-us/powershell) and it also got [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10), which allows users to run Linux executables natively, so I can have a window with Ubuntu without using Docker:
![image](https://user-images.githubusercontent.com/361921/113710989-1180c780-96ed-11eb-815e-0460d7a55b59.png)

**Comment by NateWr** [comment]
Thanks @jonasraoni. Would you be able to test the pre-commit hook that Alec posted above? I think the key question is whether the commands can be invoked successfully wherever someone is creating a commit. 

I remember from back in the day that on Windows I needed to use a program called GitBash to do git on the command line. Is that still required and if so, will the pre-commit hook work from that environment? I think we also need to check if GUI tools for git can also make use of this. I think there are a couple team members we can bring in on this once.

**Comment by asmecher** [comment]
> The way it works in UI Library is that it goes straight into the same commit. This keeps the commit history really clean because you get one commit, properly formatted.
>
I think this'll be fine once we get everything converted to the new syntax. However, I'd like to watch out for evolutions to the style guide that cause changes outside the commit's intended modifications -- if that happens we may have to plan to periodically re-run the code formatter on the codebase in order to keep PRs readable.

> But would it work on a Windows machine? Do they have access to `xargs`?

I think we're already requiring some GNU command-line tools that'll need separate installation on Windows. The `xargs` command is available here: http://gnuwin32.sourceforge.net/packages/findutils.htm

I'd like confirmation from someone working on Windows of how well this works, and if it's a problem, we can look at porting this into PHP. But if we can avoid that as a non-problem I'll be happier. Meanwhile, I don't mind if this evolves on the `main` branch.

**Comment by NateWr** [comment]
Ok, so this is more or less working now! :tada: I haven't applied the formatting to the codebase yet, but the pre-commit hooks are doing their job.

PRs:
https://github.com/pkp/pkp-lib/pull/6699
https://github.com/pkp/ojs/pull/3030


I'd like to get a couple of Windows users to test this out first (cc @ajnyga, @withanage, @defstat, @Vitaliy-1 (if you have Windows machines you can use to test)). If you have time, can you run the following tests and report back?

## Test pkp-lib:

```
cd lib/pkp
git checkout -b NateWr-i5678_cs main
git pull https://github.com/NateWr/pkp-lib.git i5678_cs
composer install
```

Check if the pre-commit hook was set up:

```
./lib/vendor/brainmaestro/composer-git-hooks/cghooks list-hooks
```

If you don't see a pre-commit hook, post a comment here to tell me. Then run:

```
/lib/vendor/brainmaestro/composer-git-hooks/cghooks update
```

You should now have the pre-commit hook set up. Make a small change to a PHP file (like adding a comment), then:

```
git add <the-file>
git commit -m "Test"
```

You should see output that confirms the file was formatted. It will look like this:

```
$ git commit -m "Test"             
Loaded config default from "/home/nate/Projects/pkp/ojs/lib/pkp/.php_cs".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
   1) api/v1/_email/PKPEmailHandler.inc.php

Fixed all files in 0.103 seconds, 16.000 MB memory used
[i5678_cs bd0ec9e7d] Test
 1 file changed, 237 insertions(+), 235 deletions(-)
 rewrite api/v1/_email/PKPEmailHandler.inc.php (92%)
```

## Test OJS:

```
cd <ojs-root>
git checkout -b NateWr-i5678_cs main
git pull https://github.com/NateWr/ojs.git i5678_cs
npm install
```

You should now have the pre-commit hook set up. Make a small change to a PHP file (like adding a comment), then:

```
git add <the-file>
git commit -m "Test"
```

You should see output that shows the file was formatted:

```
$ git commit -m "Test"
husky > pre-commit (node v15.9.0)
  ↓ Stashing changes... [skipped]
    → No partially staged files found...
  ✔ Running linters...
[i5678_cs 78d870ad4b] Test
 1 file changed, 1 insertion(+)
```

**Comment by NateWr** [comment]
One downside, which I don't see a way around, is that php-cs-fixer has to be run one file at a time. This leads to a lot of output:

```
$ git commit -m "pkp/pkp-lib#5678 Add pre-commit hook to run formatter on commited changes"
Loaded config default from "/home/nate/Projects/pkp/ojs/lib/pkp/.php_cs".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
Loaded config default from "/home/nate/Projects/pkp/ojs/lib/pkp/.php_cs".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.

Fixed all files in 0.008 seconds, 16.000 MB memory used
Loaded config default from "/home/nate/Projects/pkp/ojs/lib/pkp/.php_cs".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.

Fixed all files in 0.018 seconds, 18.000 MB memory used
[i5678_cs 8f74f0a76] pkp/pkp-lib#5678 Add pre-commit hook to run formatter on commited changes
 3 files changed, 1446 insertions(+), 254 deletions(-)
```

For large commits this will be pretty annoying. Does anyone know a way to reduce the output noise? It's not possible to pass multiple paths to php-cs-fixer when calling it from the command line.

**Comment by asmecher** [comment]
@NateWr, I think the `-q` option to `php-cs-fixer` will reduce noise.

**Comment by NateWr** [comment]
@asmecher, the `-q` option makes it go completely silent, not even printing error messages. I'm trying to figure out how to make the pre-commit hook bail on the commit if there's a fatal syntax error that prevents php-cs-fixer from running.  But I can't even seem to get the simplest `if` statement working in bash:

```bash
git diff --name-only --cached | xargs -L 1 ./lib/vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run

echo exitcode ${?}

if [ $? -ne 0 ]; then
	echo fail
	exit 1
else
	git diff --name-only --cached | xargs git add -u
fi
```

This is printing the following, which shows that the `else` block is being called:

```
$ git commit -m "Test"
Loaded config default from "/home/nate/Projects/pkp/ojs/lib/pkp/.php_cs".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.

Checked all files in 0.001 seconds, 14.000 MB memory used
Loaded config default from "/home/nate/Projects/pkp/ojs/lib/pkp/.php_cs".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.

Checked all files in 0.003 seconds, 14.000 MB memory used

Files that were not fixed due to errors reported during linting before fixing:
   1) /home/nate/Projects/pkp/ojs/lib/pkp/api/v1/_submissions/PKPBackendSubmissionsHandler.inc.php
exitcode 123
[i5678_cs 0fa24b9ad] Test
 2 files changed, 442 insertions(+), 436 deletions(-)
 rewrite api/v1/_email/PKPEmailHandler.inc.php (92%)
 rewrite api/v1/_submissions/PKPBackendSubmissionsHandler.inc.php (90%)
```

I must be missing something obvious, but it looks like the `$?` is `123` but `[if $? -ne 0]` is not true...?

**Comment by NateWr** [comment]
Ok, I think we're almost there. I have:

- Centralized all rule declarations in pkp-lib so all apps share the same ruleset.
- Adjusted the pre-commit scripts so that they abort the commit when a fatal syntax error is found and php-cs-fixer can not format a file.

Aborting the commit was tricky, because php-cs-fixer doesn't distinguish between two errors: "this file needs to be formatted" and "I can't format this file". So unfortunately it means we run php-cs-fixer twice: once to format, and a second time to detect if any formatting remains that can't be run. It shouldn't be too time-consuming except on very large commits.

Because of this two-run situation, I was able to make the pkp-lib output a little bit cleaner.

![format-message](https://user-images.githubusercontent.com/2306629/113904898-75c58900-97ca-11eb-9d63-dc44e9c3555a.png)

**Comment by NateWr** [comment]
@defstat confirmed that this was working on Windows using this [windows utility for git](https://git-scm.com/download/win). He did need to manually install the pre-commit hook, so I'll prep some docs with that info. Otherwise, I think we're good to go. :tada:

**Comment by NateWr** [comment]
:tada: All merged!
