### ISSUE TITLE
Fix "New Review Round" tab presentation

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#568]
In the Editor's "Review" workflow tab, the review round tab for "New Review Round" looks garbled. Valign issues, cropping...

**Comment by asmecher** [comment]
Consider this FIXME while fixing: https://github.com/pkp/pkp-lib/blob/5ec6271b862718b332620240d0e0b07235131403/templates/controllers/tab/workflow/review.tpl#L34

**Comment by NateWr** [comment]
Is this urgent? It's going to get re-done pretty soon in my fork, but changes there probably won't be merged in for some time.

If you want me to port in a solution to current master, let me know.

**Comment by asmecher** [comment]
No, nothing urgent at all. It would be nice to get it fixed for the beta, since it's an obvious visual glitch.

**Comment by NateWr** [comment]
Fixed in my fork and will be rolled in with UI changes eventually.
