### ISSUE TITLE
Fatal error in RecommendByAuthor plugin

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5683]
**Describe the bug**
A fatal error was reported in the RecommendByAuthor plugin:

```


    29-Mar-2020 12:44:12 Europe/Berlin] PHP Fatal error: Uncaught Error: Call to a member function getJournalId() on null in …/classes/issue/IssueAction.inc.php:31

    Stack trace:

    #0 …/classes/search/ArticleSearch.inc.php(274): IssueAction->subscriptionRequired(NULL, Object(Journal))

    #1 …/plugins/generic/recommendByAuthor/RecommendByAuthorPlugin.inc.php(137): ArticleSearch->formatResults(Array)

    #2 …/lib/pkp/classes/plugins/HookRegistry.inc.php(107): RecommendByAuthorPlugin->callbackTemplateArticlePageFooter(‘Templates::Arti…’, Array)

    #3 …/lib/pkp/classes/template/PKPTemplateManager.inc.php(1237): HookRegistry::call(‘Templates::Arti…’, Array)

    #4 …/cache/t_compile/42362804174f266c598cdb32c3208fc745b92101^1c372c95cd85572e0fbc9a53d0323a0b229cfc78_0.app.frontendpagesarticle.tpl.php(43): PKPTemplateManager->smartyCallHook(Array, Object(Smarty_Internal_Template))

    #5 …/lib/pkp/lib/vendor/smarty/smarty/libs/ in …/classes/issue/IssueAction.inc.php on line 31
```

See report: https://forum.pkp.sfu.ca/t/costume-block-manager-blocks-cannot-be-activated-after-upgrade-to-ojs-3-2-0-1/59559/3?u=natewr

**To Reproduce**
Steps to reproduce the behavior: unknown.

**What application are you using?**
 3.2.0-1

**Comment by NateWr** [comment]
It looks like this will arise if there is no `issueId` on a publication or the `issueId` points to an issue that doesn't exist. https://github.com/pkp/ojs/blob/master/classes/search/ArticleSearch.inc.php#L268-L275

A quick look suggests that this may occur if an author has an unpublished submission. https://github.com/pkp/ojs/blob/master/plugins/generic/recommendByAuthor/RecommendByAuthorPlugin.inc.php#L64-L88

And these are not excluded by ordering by stats. https://github.com/pkp/ojs/blob/master/plugins/generic/recommendByAuthor/RecommendByAuthorPlugin.inc.php#L105-L107

I suspect this might be solved by checking the published status of a publication before collecting its submissionId into `$submissionIds` here: https://github.com/pkp/ojs/blob/master/plugins/generic/recommendByAuthor/RecommendByAuthorPlugin.inc.php#L84

**Comment by asmecher** [comment]
See also these forum reports:
- https://forum.pkp.sfu.ca/t/error-the-article-display-is-different-from-the-others/59567/8
- https://forum.pkp.sfu.ca/t/error-the-article-display-is-different-from-the-others/59567/8

**Comment by asmecher** [comment]
Pull request: https://github.com/pkp/ojs/pull/2708

**Comment by asmecher** [comment]
Confirmed working;  merged and cherry-picked to `stable-3_2_0`.
