### ISSUE TITLE
Fatal error in usageStats plugin calling for PublishedMonograph

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5685]
**Describe the bug**
The usageStats plugin may result in a fatal error due to a call to a bad method (`getID()` instead of `getId()`).

```
Fatal error: Uncaught Error: Call to a member function getID() on null in C:\wamp64\www\omp\plugins\generic\usageStats\UsageStatsPlugin.inc.php:585
Stack trace:
#0 C:\wamp64\www\omp\lib\pkp\classes\plugins\HookRegistry.inc.php(107): UsageStatsPlugin->displayReaderMonographGraph(‘Templates::Cata…’, Array)
#1 C:\wamp64\www\omp\lib\pkp\classes\template\PKPTemplateManager.inc.php(1237): HookRegistry::call(‘Templates::Cata…’, Array)
#2 C:\wamp64\www\omp\cache\t_compile\4838d1eb315c43da6fc0c608df23899f50941f69^1a43403fc96a795020edfbc1cc6004aa859621c9_0.app.frontendobjectsmonographf.php(302): PKPTemplateManager->smartyCallHook(Array, Object(Smarty_Internal_Template))
#3 C:\wamp64\www\omp\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_5e7dbc06c4b8d7_03005189(Object(Smarty_Internal_Template))
#4 C:\wamp64\www\omp\lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRend
```

It also seems like it is still expecting a `PublishedMonograph`, which doesn't exist in 3.2.

https://github.com/pkp/usageStats/blob/master/UsageStatsPlugin.inc.php#L583-L585

See the original report from the forum: https://forum.pkp.sfu.ca/t/multiple-issues-in-omp3-2-0-1-after-upgrade-from-3-1-2-2/59519/5

**To Reproduce**
Steps to reproduce the behavior: uncertain, but appears to happen on the article landing page.

**What application are you using?**
OMP 3.2

**Comment by asmecher** [comment]
There were still some references to `PublishedMonograph` that were also breaking this section of code; fixed that as well.
