### ISSUE TITLE
OMP: Google Scholar tags only appear on PDF view page, not on landing page

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5686]
**Describe the bug**
If I enable the Google Scholar plugin in OMP, the GS citation_* tags only appear on PDF galley view pages, if a PDF galley exists - not on the catalog entry/landing page. Take this article for example: 

- https://demo.publicknowledgeproject.org/omp3/demo/index.php/aup-demo/catalog/book/14 - no GS citation_* metatags in this HTML source (although the DC tags are there);
- https://demo.publicknowledgeproject.org/omp3/demo/index.php/aup-demo/catalog/view/14/39/41-1. (the "Free PDF" page view): GS tags are available. 

It looks like the problem is the following line in OMP: https://github.com/pkp/omp/blob/master/plugins/generic/googleScholar/GoogleScholarPlugin.inc.php#L53. I am not sure if this should be fixed here, or fixed in the new OJS/OPS (and OMP?) plugin at https://github.com/pkp/googleScholar.

**Comment by ajnyga** [comment]
I was just looking at this when I ported the OpenGraph plugin for OMP.

A single book in OMP can contain several publication formats, and each publication format can have it's own ISBN. I think this is the reason why the landing page does not show the GS tags and they are shown in galley page instead.

If we were to show GS tags on the book landing page, then how should books with multiple publication formats / ISBN's be treated?

**Comment by jmacgreg** [comment]
Good question - I'll check with GS.

**Comment by ajnyga** [comment]
Of course a simple solution would be to list all ISBN's attached to a book. If we would do this, then would it be better to remove the output from the galley page altogether.

Probably it is not that usual to have several ISBN's per book.

**Comment by mwestin-googlescholar** [comment]
Hi, Monica Westin with Google Scholar here. It's completely fine to have multiple ISBN metatags. 

Please let me know if I can be of help in creating this patch. The main thing would be to display the metadata for the monograph, along with a citation_pdf_url metatag to the full PDF of the book (for fulltext indexing).

**Comment by withanage** [comment]
@mwestin-googlescholar 

Hi Monica,
I am  implementing  the support for  Google scholar tags  and have some questions.

In the documentation here
https://scholar.google.com/intl/en/scholar/inclusion.html#indexing
The google-scohlar only defines journal and publication titles  `citation_journal_title` or `citation_conference_title`,   is there also a tags for books and edited volumes titles ? or  will  the citation_journal_title will be  identified as the title of the book ?

under the section 2. configuring metadata  part D , there is a way to add a first and last page of  a conference 
can I also use this for the book pages  citation_firstpage, and citation_lastpage ?

Another question is , if there is a tag to explicitly define, if the book is a monograph or an edited volume ? 


We don't have a chapter landing page currently, but is it then ok to have all the editors and chapter authors in the monograph/edited-volume landing page, cause the Section 2. B defines, that only the actual authors has to be listed?

**Comment by mwestin-googlescholar** [comment]
Thanks, @withanage! It is great to hear that you're working on these metatags. 

Regarding book types, there are some really useful additional setups for distinguishing edited volumes from monographs, using URL markers rather than metatags. 

I'll be happy to discuss the various ways that OMP could be set up for Google Scholar indexing. Perhaps we could set up a time to chat? I had a number of calls over the last year about the new OJS release with the group working on these updates, and those were extremely useful for exploring different directions. 

mwestin@google.com

My very best,
Monica

**Comment by withanage** [comment]
This requirement was implemented  for OMP 3.2.1 and is currently  reviewed.

https://github.com/pkp/omp/pull/915/

Thanks  a lot Monica @mwestin-googlescholar  for the  valuable support with specification !

The support will be added to  OMP 3.3  in the coming days.

**Comment by withanage** [comment]
OMP 3.3 PR https://github.com/pkp/omp/pull/916

**Comment by asmecher** [comment]
Both PRs merged -- thanks, @withanage and @mwestin-googlescholar!
