### ISSUE TITLE
Allow subeditors to be assigned to Categories

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5694]
Categories can be regarded as the main taxonomy for browsing and managing content in OPS. Therefore it is likely that Servers will want to assign incoming submissions based on selected Categories. Currently this is not possible. The ability will be added to the shared library so other apps can use it as well.

Some of the related discussion can be found here: https://github.com/pkp/pkp-lib/issues/5622

This could also be a partial solution for special issue management: https://github.com/pkp/pkp-lib/issues/5215

**Comment by ajnyga** [comment]
@asmecher I did some additional changes and a preliminary upgrade script:
https://github.com/pkp/ojs/pull/2699
https://github.com/pkp/ojs/pull/2699/files#diff-70befd998b9e811165b9f0eab0369752R1

But github is determined that there is a conflict in pkp-lib, just not seeing it here https://github.com/pkp/pkp-lib/pull/5684

**Comment by asmecher** [comment]
@ajnyga, on the conflict, did you do a `git fetch official master` / `git rebase official master`? The conflict might be in the schema descriptor in pkp-lib; I recently moved some additional tables there. It should be trivial to resolve.

**Comment by ajnyga** [comment]
Rebasing did not help. Also tried creating a new pr in pkp-lib with a new branch and that did not help.
The pkp-lib pr says there are no conflicts: https://github.com/pkp/pkp-lib/pull/5700 but the ojs pr says there is a conflict in pkp-lib: https://github.com/pkp/ojs/pull/2699. I can not access the Resolve conflicts button so no idea what is causing it.

**Comment by ajnyga** [comment]
ojs: https://github.com/pkp/ojs/pull/2704
pkp-lib: https://github.com/pkp/pkp-lib/pull/5700

**Comment by asmecher** [comment]
That looks good, @ajnyga! Do you mind porting this to OMP and OPS?

**Comment by ajnyga** [comment]
@asmecher @NateWr 
Some big changes had to happen. So when porting this for OMP I found this bug in 3.2.0 https://github.com/pkp/pkp-lib/issues/5704. 

When going through the code, I could not find any reason for having OJS specific `UserService` and `UserQueryBuilder`. The only thing they were doing was to handle the subeditors' assignments to sections. And since that was handled in OJS and not the shared library, they were broken in OMP which did not have it's own app specific  `UserService` and `UserQueryBuilder`.

So I ended up moving it all to pkp-lib which meant totally removing both.

Nate: let me know if I missed something here.

So
OJS https://github.com/pkp/ojs/pull/2704
OMP https://github.com/pkp/omp/pull/796
pkp-lib https://github.com/pkp/pkp-lib/pull/5700

I will prepare OPS pr when I hear these changes are ok.

**Comment by NateWr** [comment]
:+1: Looks good to me. I left a couple of minor comments.

**Comment by ajnyga** [comment]
Thanks @NateWr 

Running new tests:
OJS https://github.com/pkp/ojs/pull/2704
OMP https://github.com/pkp/omp/pull/796
pkp-lib https://github.com/pkp/pkp-lib/pull/5700

**Comment by ajnyga** [comment]
Hi @asmecher and @NateWr 
Is there something here that needs to be fixed before merging?

When everthing is merged, I will make sure that OPS master is working with the new changes as well.

**Comment by NateWr** [comment]
Now that we're on concurrent releases with OPS, I think we want to have PRs for all three applications so that their `master` branch stays in sync. So go ahead and work up a PR for OPS as needed. 

I am a little backed up on work at the moment but I will try to kick this around and merge it soon.

**Comment by ajnyga** [comment]
Running tests for OPS: https://github.com/pkp/ops/pull/9

**Comment by ajnyga** [comment]
@NateWr 
OJS https://github.com/pkp/ojs/pull/2704
OMP https://github.com/pkp/omp/pull/796
OPS: https://github.com/pkp/ops/pull/9
pkp-lib https://github.com/pkp/pkp-lib/pull/5700

**Comment by NateWr** [comment]
This looks good, @ajnyga, nice work! I had one comment about renaming the assigned editor selection list panels.

I'm sure we've discussed this, but what did we decide about subcategories inheriting category editors? If I have the following categories:

```
Red
 - Purple
 - Pink
```

And I have assigned an editor, "Rachel", to the Red category. When a submission is made to the Purple or Pink category, no editor is assigned. Should "Rachel" be assigned to submissions in any subcategory, if that subcategory hasn't explicitly assigned editors?

**Comment by ajnyga** [comment]
I am not sure we discussed this particular scenario. I think we discussed more a situation where several categories are selected.

I can see how inheritance you describe would make sense. But is it transparent enough for users? Is it more transparent that you only receive the submissions from the subcategory if you have a direct assignment?

**Comment by NateWr** [comment]
Ok, let's leave it as-is for now. This way it can be manually configured to support either use case.

**Comment by NateWr** [comment]
It looks like the OJS tests are all failing early on, during the install process:

https://travis-ci.org/github/pkp/ojs/jobs/689203316#L2383

**Comment by ajnyga** [comment]
yes saw, that not sure yet what it is about. It's an error in version.inc.php which of course has not been changed...

**Comment by ajnyga** [comment]
Guessing it's this https://github.com/pkp/pkp-lib/commit/51bf8bf063fa4360f29c8748ba3bd4b4461baced

**Comment by asmecher** [comment]
Sorry, @ajnyga, I broke `master`. It should be fixed now. (See https://github.com/pkp/pkp-lib/issues/5740#issuecomment-631437099 and down.)

**Comment by ajnyga** [comment]
Hi @asmecher @NateWr 

I have tried to rebase my branches for ojs/omp/ops but keep on running to failed tests.

In OJS some of the tests work, others fail with unclear reasons: https://github.com/pkp/ojs/pull/2704
In OPS all tests work: https://github.com/pkp/ops/pull/9
In OMP all tests fail after running for about 40 minutes, but I can not find any particular error: https://github.com/pkp/omp/pull/796

Any advice?

**Comment by NateWr** [comment]
@ajnyga I've restarted the two failing OJS tests. It looks to me like the OMP tests are failing on a unit test and this may be related to the changes in how `DataObject::setData()` works:

https://travis-ci.org/github/pkp/omp/jobs/690274650#L3803-L3826

@asmecher can you take a look? I think maybe this unit test in OMP needs updating as well...

**Comment by ajnyga** [comment]
Thanks, OJS tests passed now.

**Comment by NateWr** [comment]
Hurrah! All the tests have finally passed! :joy: It looks like they just need a final rebase and then I can merge (no need to wait for tests).

**Comment by ajnyga** [comment]
Everything should be rebased and tests are running

https://github.com/pkp/ops/pull/9
https://github.com/pkp/omp/pull/796
https://github.com/pkp/ojs/pull/2704
https://github.com/pkp/pkp-lib/pull/5700

**Comment by NateWr** [comment]
Thanks, all merged!

**Comment by asmecher** [comment]
Thanks, @ajnyga and @NateWr, this was a long-storied one!
