### ISSUE TITLE
OJS - Extra space below empty submission list

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5695]
**Describe the bug**
When submission list is empty there is a empty space bellow sidebar which generates an unnecessary scroll.

**To Reproduce**
1. Install / upgrade OJS to version 3.2
2. Create an user or select one with no submissions
3. Go to dashboard
4. See error below tabs and sidebar

**What application are you using?**
 OJS  3.2.0

**Additional information**
It is a forum request that affects PKP-PS as well:
https://forum.pkp.sfu.ca/t/a-problem-after-upgrading-the-ojs-3-2-01/59539/18?u=israel.cefrin

![image](https://user-images.githubusercontent.com/4992902/78144657-e25eb880-73fd-11ea-9cf5-9835c3e1bbc3.png)

**Comment by NateWr** [comment]
This is resolved as part of #5865 so I would prefer to close this and leave the fix for 3.3.
