### ISSUE TITLE
Permit "edit galley" form to be viewed after publication

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5697]
Currently once an article is published the "edit galley" form is not available (the link is hidden).

However, that form contains valuable information that is not available elsewhere, in particular the dependent files grids for XML and HTML-based articles.

I propose making the "Edit Galley" form available, but read-only, once the article has been published.

---
**PRs**

**Branch `main`**
ojs: pkp/ojs#3526
omp: _Feature will not be implemented_
ops: pkp/ops#366
pkp-lib: #8228

**Branch `stable-3_3_0`**
ojs: pkp/ojs#3535
omp: _Feature will not be implemented_
ops: pkp/ops#347
pkp-lib: #8234

**Comment by librariam** [comment]
+1 from PKP|PS - this would be very valuable for troubleshooting galley issues without having to unpublish the article every time

**Comment by NateWr** [comment]
Looks good, @defstat. The OJS/OPS work seems like a small enough intervention that I'm happy for it to go into `stable-3_3_3`. I've left some comments on a few things that need to be resolved, but I don't expect they'll take you more than a couple hours.

After reviewing the OMP stuff, I think there's a lot more work there to get this feature going. Let's abandon it for OMP.

**Comment by NateWr** [comment]
Sorry, I forgot to mention one thing in my review: The form in the identifiers tab is not disabled. You can enable the publisher id under Settings > Workflow > Submission > Metadata to make the tab appear when editing a galley. You'll also want to enable DOIs for galleys (Settings > Website > Plugins > DOI > Settings) and make sure that can't be edited.

**Comment by defstat** [comment]
@NateWr I pushed the review changes for the `stable-3_3_0` branch for OJS.

**Comment by defstat** [comment]
@NateWr the identifiers form with both the settings you mention [here ](https://github.com/pkp/pkp-lib/issues/5697#issuecomment-1252136257) enabled seems like that 
![image](https://user-images.githubusercontent.com/560456/192758476-39180448-8897-4ee9-bbfe-ebcd6eb68fe2.png) (after disabling the Published ID form) 

I understand that there are 2 cases there:
1. The DOI is not yet assigned
2. The DOI is assigned

The form for the second case looks like that:
![image](https://user-images.githubusercontent.com/560456/192759580-067b7968-f5ce-4322-9457-7de29dbacfaf.png)

For the second case, I suppose I just hide the "Clear" button. 
For the first case

- Should I also change the message, along with hiding the checkbox or
- Should I show nothing?

**Comment by NateWr** [comment]
Yes, I'd say for both cases the input field should be disabled and the DOI field should just present the DOI without any checkboxes or buttons.

**Comment by defstat** [comment]
@NateWr 

**Case 1**
![image](https://user-images.githubusercontent.com/560456/192767308-70ee9d9f-9594-4a56-a89f-c14f454b7994.png)

**Case 2**
![image](https://user-images.githubusercontent.com/560456/192767678-36f089b9-6c36-4601-a3df-e5e6d8ec6c57.png)

**Comment by defstat** [comment]
@NateWr I have pushed the changes for the review and [this ](https://github.com/pkp/pkp-lib/issues/5697#issuecomment-1252136257) comment in two different commits (to separate the second mainly), for OJS and pkp-lib `stable-3_3_0` branch.

**Comment by defstat** [comment]
@NateWr, just a reminder, both OPS and OJS `stable-3_3_0` are ready for another review round. Tests are passing for both

**Comment by NateWr** [comment]
Thanks @defstat, it looks great. Just a couple of final changes. We talked before about not applying these changes to the `main` branch because the galley grids were going to be replaced in 3.4. However, that's no longer going to happen so we will need these changes applied to 3.4. I think just OJS and OPS is enough.

**Comment by defstat** [comment]
@NateWr @asmecher I have resolved the PRs review comments and ported the changes from `stable-3.3.0` to `main` branch for OJS, OPS and PKP-LIB. They are ready for another round of review

**Comment by NateWr** [comment]
Thanks @defstat. The stable PRs look good to go. I had just a couple questions on the ones for `main` before we merge.

**Comment by defstat** [comment]
Thanks @NateWr.. Good points, replied to all, and updated the PRs.
