### ISSUE TITLE
Update the citation library to solving the citation problem. 

### ISSUE THREAD

**Issue by navotera** [pkp/pkp-lib#5698]
Please read the issue for this problem regarding the citationStyleLanguage. 

https://github.com/seboettg/citeproc-php/issues/80

Thank you.

**Comment by NateWr** [comment]
Thanks for letting us know, @navotera. That sounds like it explains some of the issues in https://github.com/pkp/pkp-lib/issues/5629. I'm going to close this issue in favor of that one, but they'll both lead to the same result.
