### ISSUE TITLE
Static page preview

### ISSUE THREAD

**Issue by ramli01** [pkp/pkp-lib#5699]
**Describe the bug**
Creating Static Page could not be previewed before saved.

**To Reproduce**
1. Go to 'Settings -> Website'
2. Click on 'Tab Static Page'
3. Then 'Create Static Page'
4. Before Save it, ckick 'Preview'
5. No change but succeeded create the Static Page when clicking 'Save' bottom

**What application are you using?**
 OJS version 3.2.0-1

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by asmecher** [comment]
@ramli01, the "Preview" button opens a pop-up that shows a preview using Javascript; I suspect you have a popup-blocker installed.

**Comment by ramli01** [comment]
Ok. I will check it first. Thanks @asmecher

**Comment by ramli01** [comment]
Succeeded to preview static page by testing on my android.
Thank you

**Comment by asmecher** [comment]
Thanks for confirming!
