### ISSUE TITLE
Upgrade process performs slowly

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5703]
The upgrade process to 3.2 performs slowly on large data sets.
One cause for this is the lack of indexes in the `temp_`... tables used for content migration.
Resolve this by adding some indexes.

**Comment by NateWr** [comment]
Looks like you've made progress here. Is there still more work to be done?

**Comment by asmecher** [comment]
It's merged and I'll close it, but @israelcefrin and @jnugent, please let me know if this is helpful for upgrades to 3.2.0 as well. (You'll have to apply https://github.com/pkp/ojs/commit/bc1b4d95b171fe223f515696e537d4733911d2ab manually before running the upgrade -- this is only in `master`, not `stable-3_2_0`.)
