### ISSUE TITLE
Journal Masthead and Website Setup Information not Updated

### ISSUE THREAD

**Issue by omar-khan** [pkp/pkp-lib#5708]
**Describe the bug**
I am not able to see any changes I carry out to the following Text Areas. 

**To Reproduce**
1. Go to Settings > Website > Setup
2. Change text in "For Readers", "For Authors", "for Librarians" to anything
3. Click on Save. Receive message "The information for this journal was updated"
4. However, none of the changes appear in the text areas I just edited.

Similar behaviour occurs here:
1. Go to Settings > Journal > Masthead
2. Change any text-field/text area (for example, Editorial Team)
3. Click on Save. Receive message: The masthead details for this journal have been updated.
4. However, none of the changes appear in the text areas I just edited. 

**What application are you using?**
 OJS version 3.2.0.1

**Additional information**
1. My Error logs seem to be clean. I flushed the logs, went and made the changes, and no new message appears in the error log. 
2. As a precaution, file permissions on cache folder are even set to 777. 
3. The only text visible is that which appears after a clean install. No changes can be made to these contents. 
4. This is a new installation.

**Comment by asmecher** [comment]
@omar-khan, when you say you have provisionally set permissoins on the `cache` folder to `777`, do you mean just the `cache` directory or all of its contents as well?

**Comment by omar-khan** [comment]
> @omar-khan, when you say you have provisionally set permissoins on the `cache` folder to `777`, do you mean just the `cache` directory or all of its contents as well?

sorry it was not clear before-hand. I meant all of its contents (of cache folder)

**Comment by asmecher** [comment]
@omar-khan, can you check the `journal_settings` table to see if the changes you're making are reflected there?

**Comment by omar-khan** [comment]
@asmecher Good Idea. Here is what I tried. In `Settings > Journal`, I changed the Journal Abbreviation. Afterwards, I accessed the `journal_settings` table using PhpMyAdmin. It still reflects the old contents. 

The next thing I did was change the abbreviation directly in the table. When I refreshed the website, the database change appeared in the abbreviation text field.

**Comment by asmecher** [comment]
@omar-khan, OK, this means that caching is not the problem. I'd suggest opening your web developer tools to see how the request looks that saves the data to the server, and what the server's response looks like. We've had some cases where server-side security rules were falsely triggering, preventing data from being saved, but in those cases there was an error message, so yours seems a little different.

**Comment by omar-khan** [comment]
@asmecher Okay carried out the procedures. Seems something is wrong with the cookie. 
[reply-headers.txt](https://github.com/pkp/pkp-lib/files/4440296/reply-headers.txt)
[request-headers.txt](https://github.com/pkp/pkp-lib/files/4440297/request-headers.txt)
[request.txt](https://github.com/pkp/pkp-lib/files/4440299/request.txt)

**Comment by asmecher** [comment]
@omar-khan, what is the response code?

**Comment by omar-khan** [comment]
@asmecher sorry i thought it was not needed. attached. 
[response.txt](https://github.com/pkp/pkp-lib/files/4440486/response.txt)

**Comment by omar-khan** [comment]
I saw OJSSID=deleted in the reply headers but then noticed that its set later on. 

I am at odds on how to debug this. Prepared a small gif to get a visual idea. 
![ojs](https://user-images.githubusercontent.com/2735837/78608447-612e7800-787a-11ea-9de8-36ce94b2ec25.gif)

**Comment by NateWr** [comment]
Hi @omar-khan, can I ask you to check on a detail? In the `request.txt` we see the following:

```
name[en_US]=Pashto
```

But in the gif I can see you put `Pashto Journal Name`. This makes me wonder about whether the input details are not getting updated in the request that is sent. Can you do a test for me?

1. Go to Journal  > Settings > Masthead.
2. Enter `Pashto Journal Name` into the journal's name.
3. Save it.
4. Post the request payload (`request.txt`) for this exact request.

**Comment by omar-khan** [comment]
@NateWr . I have carried out the following. 

Current Journal name is "Pashto" and initials / abbreviation are "Ps". I have changed it to `Pashto Journal Name` in the browser and the request payload is attached:

[response-header.txt](https://github.com/pkp/pkp-lib/files/4449853/response-header.txt)
[response.txt](https://github.com/pkp/pkp-lib/files/4449854/response.txt)
[request.txt](https://github.com/pkp/pkp-lib/files/4449855/request.txt)
[request-headers.txt](https://github.com/pkp/pkp-lib/files/4449856/request-headers.txt)

Page refresh shows that the change has not been made. I did change the following settings
```show_stacktrace = On
display_errors = On
deprecation_warnings = Off
log_web_service_info = On```

and now the server log shows the following:

```PKP-Database-Logger 1586335307.0794:  
(mysqli): SELECT * FROM journal_settings WHERE jou 
20200408T062615: khyber.org/pacademy/journal2/index.php/*/api/v1/site 
PHP Warning:  Use of undefined constant VALIDATE_ACTION_EDIT - assumed 'VALIDATE_ACTION_EDIT' (this will throw an Error in a future version of PHP) in /hermes/walnaweb12a/b1423/pow.omerkh/htdocs/pacademy/journal2/lib/pkp/classes/services/PKPSiteService.inc.php on line 97 
PHP Warning:  Use of undefined constant VALIDATE_ACTION_ADD - assumed 'VALIDATE_ACTION_ADD' (this will throw an Error in a future version of PHP) in /hermes/walnaweb12a/b1423/pow.omerkh/htdocs/pacademy/journal2/lib/pkp/classes/validation/Va ```

This log entry was not there a few moments ago.

**Comment by NateWr** [comment]
Thanks @omar-khan, that rules out my theory. I can see the correct input is being sent in the request:

```
name[en_US]=Pashto+Journal+Name
```

I don't think either of those warnings are going to be related to this issue. Are you comfortable digging into the code to add some logging? If so, can you find the following line of code:

https://github.com/pkp/pkp-lib/blob/master/classes/services/PKPContextService.inc.php#L426

And add two quick logs to that line:

```
error_log('New context: ' . print_r($newContext->_data['name'], true));
error_log('New params: ' . print_r($params, true));
```

This will let us check the values just before they're assigned to the database, which should tell us if they're getting dropped in the process.

When you've added those lines, try to update again and then check the server log for the results.

**Comment by omar-khan** [comment]
@NateWr sure thing. After the changes, I changed the name to `Pashto Journal Name` and the output in the log shows:
```
New context: Array 
( 
    [en_US] => Pashto 
) 
 
New params: Array 
( 
    [id] => 3 
) 
```

**Comment by NateWr** [comment]
Fascinating! So it's probably not a database issue. Can you find this line:

https://github.com/pkp/pkp-lib/blob/master/api/v1/contexts/PKPContextHandler.inc.php#L345

And add these error logs:

```php
error_log('body: ' . print_r($slimRequest->getParsedBody(), true));
error_log('params: ' . print_r($params,true));
```

Then let me know the output in the log.

**Comment by omar-khan** [comment]
Log shows:
```
body: Array 
( 
) 
 
params: Array 
( 
    [id] => 3 
) 
```
is the server side even receiving the modified data ?? seems not.

**Comment by NateWr** [comment]
Yeah, it seems like the parsed body of the request is not being read. See if this is available in PHP at all with the following code:

```
$body = file_get_contents('php://input');
error_log(print_r($body,true));
error_log(print_r($POST,true));
```

If it's not coming through to either of those, then I would guess there's some server issue at play...

**Comment by omar-khan** [comment]
Changed to `$_POST$ and coming as blank:
```
body:  
post: Array 
( 
) 
```

**Comment by NateWr** [comment]
Ok this seems to me like a server configuration issue. @asmecher do you have any idea why the server wouldn't be passing along a post body?

**Comment by asmecher** [comment]
That's very odd -- @omar-khan, I'd suggest removing this example from the OJS context entirely:
1. Create a `test.php` script alongside your `index.php` with the following contents:
    ```
    <?php print_r($_POST);
    ```
2. Using the browser's web developer tools, edit the `PUT` request to point to `test.php` instead of `index.php`
3. Send the modified request and see whether the request variables show up in the script output.

If they don't, I think you're dealing with a web server configuration issue. If the PHP environment isn't getting the variables that are being sent to it, there's not much OJS can do about it!

**Comment by omar-khan** [comment]
Okay I tried:
```
<?php
	$method = $_SERVER['REQUEST_METHOD'];
	if ('PUT' === $method) {
		echo "Put Request";
		parse_str(file_get_contents('php://input'), $_PUT);
		var_dump($_PUT);
	} else {
		echo "Post Request";
		var_dump($_POST);
	}
?>
```
and gave `curl -X POST -d 'name=omar&email=abc@gmail.com' http://khyber.org/pacademy/journal2/test2.php`. Output is: 
```
Post Request array(2) {
  ["name"]=>
  string(4) "omar"
  ["email"]=>
  string(13) "abc@gmail.com"
}
```
whereas for `curl -X PUT -d 'name=omar&email=abc@gmail.com' http://khyber.org/pacademy/journal2/test2.php`. Output is: 
```
Put Request array(0) {
}
```
So it's a server issue !!!. Well I am extremely obliged for both @asmecher and and @NateWr for looking into this. Do you reckon there is need for a patch patch which can display a server configuration error if the array size received from client side is empty.

**Comment by asmecher** [comment]
@omar-khan, I suppose that check could be added to `lib/pkp/classes/form/validation/FormValidatorPost.inc.php` (for POST requests using our older form code). For the API endpoints I'm not sure it's appropriate to add a check, as an empty POST is essentially a `NOP` in many cases.

I'm not terribly fussed about this as it's the first time we've ever seen it, so I think it's a pretty rare configuration -- but please do document what the server config was and what needed changing, so it's findable in the future!
