### ISSUE TITLE
OMP - Upgrade error function getSupportedFormLocales()

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5713]
**Describe the bug**
When trying to run an upgrade to OMPS 3.2, via CLI, the scripts crashes and stops the process.

**To Reproduce**
1. Git clone and run the steps for local installation of OMP 3.2.0-1
2. Run the script php tools/upgrade.php upgrade
3. After `[code: Installer Installer::migrateSubmissionCoverImages]` it crashes

**What application are you using?**
 OMP version 3.2.0-1

**Additional information**
See the error log bellow:
```
PHP Fatal error:  Uncaught Error: Call to a member function getSupportedFormLocales() on null in omp3/demo/classes/install/Upgrade.inc.php:799
Stack trace:
#0 omp3/demo/lib/pkp/classes/install/Installer.inc.php(417): Upgrade->migrateSubmissionCoverImages(Object(Upgrade), Array)
#1 omp3/demo/lib/pkp/classes/install/Installer.inc.php(263): Installer->executeAction(Array)
#2 omp3/demo/lib/pkp/classes/install/Installer.inc.php(186): Installer->executeInstaller()
#3 omp3/demo/lib/pkp/classes/cliTool/UpgradeTool.inc.php(88): Installer->execute()
#4 omp3/demo/lib/pkp/classes/cliTool/UpgradeTool.inc.php(64): UpgradeTool->upgrade()
#5  omp3/demo/tools/upgrade in  omp3/demo/classes/install/Upgrade.inc.php on line 799 
```

**Comment by asmecher** [comment]
@israelcefrin, I think this is a data error (submissions that are in a non-existent press). Try the following SQL query:
```
SELECT s.submission_id FROM submissions s LEFT JOIN presses p ON (p.press_id = s.context_id) WHERE p.press_id IS NULL;
```
If you get any results, they'll be the problem rows.

**Comment by israelcefrin** [comment]
@asmecher no results returned.

**Comment by asmecher** [comment]
@israelcefrin, how about...
```
SELECT ps.submission_id FROM published_submissions ps LEFT JOIN submissions s ON (ps.submission_id = s.submission_id) WHERE s.submission_id IS NULL;
```

**Comment by israelcefrin** [comment]
@asmecher that's it. A missing submission. Thanks!

**Comment by ccmaria** [comment]
Hello,
I m sorry. But, how do I import a table into omp? what are the formats?

**Comment by asmecher** [comment]
@ccmaria, could you post your question (with details) on our support forum at https://forum.pkp.sfu.ca? That's the best place to get help.
