### ISSUE TITLE
Refactor email templates to better support discovery, reuse and documentation

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5716]
**Describe the problem you would like to solve**
Journal managers want to be able to configure email templates to support a wide range of needs throughout the applications. These include:

- Define when custom templates are/aren't available for use. 
  - #3523
  - #3193 
- Have a documented glossary of what variables are available and when.
  - #3253 

**Describe the solution you'd like**
We'll need a list in the application that defines each possible event that results in an email, and this must be hooked so that plugins can add their own events. Each event can define what variables are available in the email template.

Email templates, including the default templates, should define which events they can be used for. This should be configurable for custom templates but not for default templates, so that journal managers can not accidentally configure no templates for an event.

With this information, it should be possible to accomplish the following:

- Filters in the email templates list for workflow stage or event that allow managers to quickly find the email template they want.
- The ability to call up a list of valid templates for each email event, such as a new discussion, request for revisions, etc. And then let the user select from the allowed templates.
- The ability for journal managers to configure which templates are valid for which events.

As part of longer-term refactoring, it probably makes sense to refactor this so that it is distinct from the `Notification` and `NotificationManager` classes that exist. 

It may also be worth investigating [Laravel's Notification](https://laravel.com/docs/5.6/notifications) system to see if it might replace our existing system or inspire our refactor.

**Who is asking for this feature?**
This is a requirement to implement some of the features described above, which have been requested by community members and PS.

**Pull Requests**
See [comment](https://github.com/pkp/pkp-lib/issues/5716#issuecomment-1305718000):
- https://github.com/pkp/ui-library/pull/227
- https://github.com/pkp/pkp-lib/pull/8407
- https://github.com/pkp/ojs/pull/3609
- https://github.com/pkp/omp/pull/1242
- https://github.com/pkp/ops/pull/387

**Comment by ajnyga** [comment]
Not sure if this is included in the suggestions above. But the list should somehow show which templates are used based on chosen settings. For example if one-click is enabled, only some of the review templates are used (should we combine some of those templates is of course another question).

**Comment by NateWr** [comment]
The following are some preliminary mockups of how the new email management UI will work.

# Manage emails
This looks similar to the existing email templates UI, except it only lists email events. For example, a single email is shown for "Submission Accepted", but the editor will be able to assign more than one email template to use for that event.

![Manage Emails](https://user-images.githubusercontent.com/2306629/184111493-1c29ce39-c831-4625-98a0-9207914ff791.png)

# Emails with just one template
When an email is sent automatically, the editor doesn't have an opportunity to edit the email or select a different template. In such cases, the email will only have one template. The edit button will open a modal to edit that template.

(Some emails the editor can edit will still only support one template until we can refactor them.)

![Edit Automatic Email](https://user-images.githubusercontent.com/2306629/184111714-f21e6568-4ed4-4942-aeca-4f2b1344677f.png)

# Emails with many templates
When editing an email that the editor previews and edits, such as when recording an editorial decision, they can edit the default template and create custom templates. See a mockup of the new [Load Template UI](https://github.com/pkp/pkp-lib/issues/5717) when writing an email.

![Edit Email with Many Templates](https://user-images.githubusercontent.com/2306629/184112128-7501e7ba-39ec-4c4d-94f4-5a342e4d9abb.png)

# Email template variables
When editing an email template, the user will be able to see all of the variables they can use.

![Variables](https://user-images.githubusercontent.com/2306629/184112270-b2689eb6-0bc2-4edf-9684-85ac77da9b64.png)

**Comment by NateWr** [comment]
@Vitaliy-1 could you do a code review of the PRs above? (I've also linked them to the first comment in the issue.) Some of the upgrade tests are failing, but I think you can go ahead and start the review.

**Comment by Vitaliy-1** [comment]
@NateWr, I've reviewed it for all 3 apps and the UI library. Regarding the latter, I'm getting myself familiar with Vue more than reviewing it :)
Looks good! Great to see it all tight together

**Comment by NateWr** [comment]
@asmecher I'm running into a problem with the upgrade tests due to a change in the code that installs email templates. I've added a `name` attribute to the templates defined in `emailTemplates.xml` and updated [PKP\emailTemplates\DAO::installEmailTemplateLocaleData()](https://github.com/pkp/pkp-lib/pull/8407/files#diff-417c2d61820cffdf12a9da7f46020802e9740669f44f577343cf62fdf24bd6f9L291) to use that attribute.

As a result, migrations that call `<code function="installEmailTemplate" ... />` before the 3.4 upgrade now fail. What's the best way to handle this? Should I modify `PKP\emailTemplates\DAO::installEmailTemplateLocaleData()` so that it supports older versions? Or should I deprecate `Installer::installEmailTemplate()` and bring email template install code into the 3.4 migration classes? 

Seems we need some way to segment the code, or we risk breaking old migrations.

**Comment by NateWr** [comment]
@asmecher sounds good. Just to clarify: once this is deprecated, we'll not use `<code function="installTemplate" ...>` in `upgrade.xml` from 3.4 onwards, right?

**Comment by asmecher** [comment]
That's what I'm proposing -- but this would mean essentially duplicating the code for email installation for every release we need to include it with. Are you content that it'll be a streamlined/small enough block of code to not impose maintenance headaches?

**Comment by NateWr** [comment]
Yep, I don't have a good alternative idea so we'll go with that for now. :)

**Comment by NateWr** [comment]
@asmecher it was a little bit messy because the same code is used for installing and migrations. For minimal impact, I just duplicated some code into `Installer.php` and then into the individual migrations. See https://github.com/pkp/pkp-lib/pull/8407/commits/a8bfeae2c6847e83523a9b7dfae60aaa8a603caa and https://github.com/pkp/ojs/pull/3609/commits/643e9791362ff4aba141792ba0e074c2459cd09b.

**Comment by NateWr** [comment]
I forgot to add a migration script to `upgrade.xml`. The following PRs add this:

- https://github.com/pkp/ojs/pull/3652
- https://github.com/pkp/omp/pull/1272
- https://github.com/pkp/ops/pull/408

**Comment by NateWr** [comment]
All merged.
