### ISSUE TITLE
Supporting Agencies field does not appear in submission process

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5718]
The Supporting Agencies field can be enabled in the Workflow settings so that it appears during the author's submission process.

However, it does not appear there.

This is like https://github.com/pkp/pkp-lib/issues/5628, but that issue affected the editorial workflow metadata form; this is for the author's submission metadata form.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/5719
@NateWr, could you take a quick look? I'm not sure if this field was removed intentionally during the workflow form rewrite.

**Comment by NateWr** [comment]
Looks good to me. :+1:

**Comment by asmecher** [comment]
Thanks, merged and cherry-picked to `stable-3_2_0`.
