### ISSUE TITLE
Unable to install /update OJS 3202 version

### ISSUE THREAD

**Issue by zalamuia** [pkp/pkp-lib#5721]
Tried to fresh install or updating given this error
This page isn’t working journals.iium.edu.my is currently unable to handle this request.
HTTP ERROR 500
I have tested in other sites also gives above mentioned error.
find the logged error one of my server

[Fri Apr 10 13:11:52.808596 2020] [ssl:warn] [pid 1524:tid 140141096384384] AH01909: ojs.mynetgear.com:443:0 server certificate does NOT include an ID which matches the server name [Fri Apr 10 13:11:52.878599 2020] [ssl:warn] [pid 1861:tid 140141096384384] AH01909: ojs.mynetgear.com:443:0 server certificate does NOT include an ID which matches the server name [Fri Apr 10 13:12:16.033028 2020] [:error] [pid 1890:tid 140140638803712] [client 10.36.2.124:3200] PHP Warning: Declaration of DefaultTranslationPlugin::register($category, $path) should be compatible with LazyLoadPlugin::register($category, $path, $mainContextId = NULL) in /home/ojs/public_html/ojs/plugins/generic/defaultTranslation/DefaultTranslationPlugin.inc.php on line 88 [Fri Apr 10 13:12:16.394378 2020] [:error] [pid 1890:tid 140140697552640] [client 10.36.2.124:3200] PHP Warning: Declaration of DefaultTranslationPlugin::register($category, $path) should be compatible with LazyLoadPlugin::register($category, $path, $mainContextId = NULL) in /home/ojs/public_html/ojs/plugins/generic/defaultTranslation/DefaultTranslationPlugin.inc.php on line 88, referer: http://ojs.mynetgear.com/ojs/index.php/ajeee [Fri Apr 10 13:15:20.065979 2020] [:error] [pid 1890:tid 140140903421696] [client 10.36.2.124:3249] PHP Warning: require_once(/home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php): failed to open stream: No such file or directory in /home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php on line 17 [Fri Apr 10 13:15:20.066445 2020] [:error] [pid 1890:tid 140140903421696] [client 10.36.2.124:3249] PHP Fatal error: require_once(): Failed opening required '/home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php on line 17 [Fri Apr 10 13:15:26.385059 2020] [:error] [pid 1890:tid 140140655589120] [client 10.36.2.124:3250] PHP Warning: require_once(/home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php): failed to open stream: No such file or directory in /home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php on line 17 [Fri Apr 10 13:15:26.385402 2020] [:error] [pid 1890:tid 140140655589120] [client 10.36.2.124:3250] PHP Fatal error: require_once(): Failed opening required '/home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php on line 17 [Fri Apr 10 13:43:15.930547 2020] [:error] [pid 1890:tid 140140647196416] [client 10.36.2.124:3411] PHP Warning: require_once(/home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php): failed to open stream: No such file or directory in /home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php on line 17 [Fri Apr 10 13:43:15.930880 2020] [:error] [pid 1890:tid 140140647196416] [client 10.36.2.124:3411] PHP Fatal error: require_once(): Failed opening required '/home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php on line 17 [Fri Apr 10 13:43:16.340127 2020] [:error] [pid 1890:tid 140140764694272] [client 10.36.2.124:3412] PHP Warning: require_once(/home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php): failed to open stream: No such file or directory in /home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php on line 17 [Fri Apr 10 13:43:16.340469 2020] [:error] [pid 1890:tid 140140764694272] [client 10.36.2.124:3412] PHP Fatal error: require_once(): Failed opening required '/home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /home/ojs/public_html/ojs3202/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php on line 17 

Server Info: 

Setting Name | Setting Value
-- | --
OS platform | Linux
PHP version | 7.3.16
Apache version | Apache/2.4.41 (Unix) OpenSSL/1.0.2k-fips
Database driver | mysqli
Database server version | 10.1.44-MariaDB

**Comment by asmecher** [comment]
@zalamuia, try to manually install the citation style language's Composer dependencies manually with...
```
cd plugins/generic/citationStyleLanguage
composer install
```
It looks like these were accidentally excluded from the build package; I'll rebuild and post a new copy.

**Comment by asmecher** [comment]
(New copy posted, including the missing Composer dependencies.)

**Comment by zalamuia** [comment]
Managed to install. Thanks
