### ISSUE TITLE
[OMP] File mapping for chapters

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#5722]
#### Description
Chapter file association removes   associated files of the rest of the chapters.

#### Reproduce
* Add two chapter files from type "Chapter Manuscript" into production stage in workflow.
* Create 2 chapters under chapters in   Publication.
* Associate fist  chapter file to the first chapter and save.
* Associate second  chapter file to the second chapter and save. 
* Open the fist chapter again and the associated file is no more associated.

#### Links
* Reported in [forum](https://forum.pkp.sfu.ca/t/problem-of-file-association-with-respective-chapters-in-omp3-2-0-2/59814)

**Comment by withanage** [comment]
Hi @asmecher  @NateWr 

I have investigated this issue.

Removing the not explicitly set settings in the data object is the reason for this issue.

https://github.com/pkp/pkp-lib/blob/master/classes/db/DAO.inc.php#L553

Did not remove it, without knowing the consequences.

**Comment by withanage** [comment]
Hi @asmecher @NateWr

I have investigated this issue.

The reason for replacing other files is caused by this setting.

https://github.com/pkp/pkp-lib/blob/master/classes/db/DAO.inc.php#L553

Did not remove it, without knowing the consequences, it could have on the other areas.

**Comment by NateWr** [comment]
Can this be fixed in the chapter form? So when updating chapter file associations, make sure you get the full submission file object, including any pre-existing chapter file associations, and update that object?

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/omp/pull/802
https://github.com/pkp/omp/pull/803 (stable)

**Comment by asmecher** [comment]
Both merged -- thanks, @withanage and @NateWr!
