### ISSUE TITLE
OJS 3.2.0-1/2 Website setting - Setting and Advance caused error and failed to load syetem info

### ISSUE THREAD

**Issue by zalamuia** [pkp/pkp-lib#5724]
![Error-Saving](https://user-images.githubusercontent.com/61810595/79101605-76843480-7d9b-11ea-8f56-9a926f1be540.jpg)

![Error-Saving-2](https://user-images.githubusercontent.com/61810595/79101618-7edc6f80-7d9b-11ea-8c47-da0ff0fbcac5.jpg)

OJS OJS 3.2.0-1 and OJS 3.2.0-2

PHP 7.2.x

**Comment by asmecher** [comment]
@zalamuia, I expect this will be the same issue as https://github.com/pkp/pkp-lib/issues/5723; let's continue to debug it there, and if it turns out to be a separate issue, we can re-open this one.
