### ISSUE TITLE
Notification query getByUserId often run with no indexes used

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#5725]
We've had slow query logging enabled for a while just to see what the culprits are and it seems that the NotificationDAO::getByUserId query can be run without indexes.  In the schema, the largest index is created with:

```
		<index name="notifications_context_id_user_id">
			<col>context_id</col>
			<col>user_id</col>
			<col>level</col>
		</index>
```
But the query that often runs is:
`
SELECT * FROM notifications WHERE user_id = xxxx AND level = 1 ORDER BY date_created DESC;`

which results in no index being used.  The solution may be to create an independent index just on user_id and level, or else re-arrange that first index so it reads:

```
		<index name="notifications_context_id_user_id">
			<col>user_id</col>
			<col>level</col>
			<col>context_id</col>
		</index>
```

So the first part of the index can be used if the context_id is not specified. 

Noticed in 3.1.2-4.

**Comment by asmecher** [comment]
@jnugent, there are valid calls for both cases where `context_id` is set and cases where it isn't, so I think another index is warranted (and this is a very frequent call, so it'll likely have a positive impact for a lot of people)! Could you open a PR to introduce the new index via the schema file?

**Comment by asmecher** [comment]
Thanks, merged and cherry-picked back to `stable-3_2_0`.
