### ISSUE TITLE
[OPS] Add ability to send "acceptance" letter

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5727]
**Describe the problem you would like to solve**
Example: Add ability to send an "approval" letter to authors when a preprint gets posted, in a similar way of the Acceptance letter in OJS.

**Describe the solution you'd like**
Ideally the message should be configurable (template) and allow editing before sending it.

**Who is asking for this feature?**
This would benefit authors as they would know the moment when their preprint gets posted online.

**Comment by ajnyga** [comment]
pr 
ops: https://github.com/pkp/ops/pull/67

**Comment by asmecher** [comment]
PR reviewed and merged. Thanks, all!

**Comment by JhonathanLepidus** [comment]
Hi! We were trying to use the feature implemented in this issue, but we noticed a strange behavior with it. In [this line](https://github.com/pkp/ops/blob/ffc51352642f31c100c3792e5ebcf7f6c0ca3879/classes/services/PublicationService.inc.php#L300) you can see that the e-mail is sent to the current user, who is posting the preprint.

However, it's common that in preprint servers the preprints are posted by moderators, so the e-mail isn't sent to any author, but instead to who is posting. To fix this, it shouldn't be sent to the primary author of the preprint?

**Comment by asmecher** [comment]
@JhonathanLepidus, yes, that sounds correct to me. Could you file this as a new issue entry?

**Comment by diegoabadan** [comment]
Thank you @alec

I created the #7176 adapting the report of the problem discovered by @JhonathanLepidus
