### ISSUE TITLE
[OPS] Authors names don't appear in all languages interface when data isn't filled accordingly

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5728]
**Describe the bug**
When name and last name data are not filled in all languages available, the names don't appear in the public reader interface in which the language wasn't filled.

**To Reproduce**
1. Have multi-languages enabled to your Server.
2. Submit a preprint but only fill out the name and last name on the default language fields.
3. Post the preprint.
4. Check public interface on the language interface for which you did not fill the name data.
5. See how the names don't appear.

**What application are you using?**
Open Preprint Systems 3.2.0 Beta

**Comment by asmecher** [comment]
@alexxxmendonca, I believe this is a duplicate of https://github.com/pkp/pkp-lib/issues/5588, can you confirm?

**Comment by alexxxmendonca** [comment]
Hi @asmecher, yes it is the same issue! Terribly sorry for the duplicate issue.

I'm gonna close this one.
