### ISSUE TITLE
Improve subject and body of the default email templates

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5730]
**Describe the problem you would like to solve**
Emails that are sent out are often missing useful information. Sometimes useful information that could appear in the subject is only available in the body of the email. Sometimes it requires the user to click a link to see it.

The style of the text is often unnecessarily robotic and alienating.

Some examples:
- The subject of emails for editorial decisions say "Editor Decision". The subject should include the decision, such as "Your submission has been accepted."
- When a discussion is created, the subject says "You have a new notification" and only a link is provided. The email's subject should be the discussion's subject and the body of the message should be in the body of the email, so the user does not have to login to read it.

**Describe the solution you'd like**
I'd like to see an audit and rewrite of all of our default email templates. The audit should determine what information should be included in the subject and body that is currently missing. And the rewrite should prepare sample content including this content.

I'd suggest that we aim for the following from the email copy:

1. Messages should be kind: use words like "declined" instead of "rejected".
2. Messages should be informative: the reader should know what it is about from the subject and get all the information they need from the body.
3. Messages should be human: instead of "Our decision: Request Revisions" it should say something like "Pleased to accept your paper upon revisions"
4. Messages should be warm: instead of "Your submission was successful" it should say "Thank you for your submission"

**Who is asking for this feature?**
Since PKP aims to promote best-practices in scholarly publishing, I think it's important that we demonstrate a warmer, friendlier character in our default messaging. I am particularly interested in promoting a less stressful experience for authors. 

**Additional Information**
Collecting feedback and requests here:
- Link to submission (or directly to discussion) should be included in all discussion emails. See [[Forum](https://forum.pkp.sfu.ca/t/pre-review-discussions-include-link-to-entry-in-ojs/50899)]

**Comment by kshuttle** [comment]
This document contains new wording for all email templates related to the workflow in OJS: https://docs.google.com/document/d/1LY9258IgcU80wqlmasRfby7veQb7T-W3Gnhu-ti50Mk/edit?usp=sharing

Email templates that require changes to move than just the wording (ie templates to be added, removed, or integrated into other systems changes) are indicated through individual GitHub issues in the ["Email: Notifications, templates, drafting, sending" project](https://github.com/pkp/pkp-lib/projects/10#card-71507040). The above Google doc only contains new wording (and in some cases new names, descriptions, and subjects) for email templates that are not already included in individual GitHub issues linked to this project. The current / old template name, description, subject, and email text are indicated alongside the new / re-written version for each template.

**Comment by NateWr** [comment]
@kshuttle I'm working on attaching reviewer comments to decision emails now and I had a question. Most of the emails have text that says:

> The reviewers’ comments are included at the bottom of this email. 

These will be added like an email template variable. I'm wondering how we should format this? At the end of each email is:

> Kind regards,
> 
> {$signature}

Should we just go straight into the reviewer comments?

> Kind regards,
>
> {$signature}
>
> {$allReviewerComments}

Or should the email template introduce them like this?

> Kind regards,
>
> {$signature}
>
> ----
>
> The following comments were received from reviewers.
>
> {$allReviewerComments}

**Comment by kshuttle** [comment]
Sorry for the oversight with this, @NateWr. I think leading into the reviewer comments with the suggested statement (The following comments were received from reviewers) would be my preferred option.

**Comment by NateWr** [comment]
@defstat, @Vitaliy-1 and I have divided up the emails in the document above so we'll each take:

Dmitris: `SUBMISSION_ACK`, `SUBMISSION_ACK_NOT_USER`, `COPYEDIT_REQUEST`, `LAYOUT_REQUEST`
Vitaliy: All review assignments emails such as `REVIEW_REQUEST_*`, `REVIEW_REMIND_*` and `REVIEW_REINSTATE`
Nate: All editorial decision emails such as `EDITOR_DECISION_*`.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/7541
OJS: https://github.com/pkp/ojs/pull/3248

**Comment by Vitaliy-1** [comment]
@asmecher, these PRs contain changes to all locales, what is the best way to proceed with them?

**Comment by asmecher** [comment]
@Vitaliy-1, I've just merged the translations from Weblate into OJS `main`, and it looks like there's a conflict with `locale/ja_JP/emails.po`. Can you rebase and fix it? Then I'll be ready to merge.

Does this also need porting to OPS and OMP?

**Comment by Vitaliy-1** [comment]
Thanks, @asmecher. Yes, this requires porting to other applications.
@NateWr, can you take a look at these PRs first? They include new wording for email templates, renaming template variables throughout the code, migration and installation.

**Comment by Vitaliy-1** [comment]
While reviewing email template variables for OMP, I found the following templates: 

- `EDITOR_DECISION_ACCEPT`
- `EDITOR_DECISION_SEND_TO_EXTERNAL`
- `EDITOR_DECISION_REVISIONS`
- `EDITOR_DECISION_RESUBMIT`

Have an identical issue in the English localization - missing decision itself. E.g., for the first one it's:
```
"{$authorName}:<br />\n"
"<br />\n"
"We have reached a decision regarding your submission to {$contextName}, &quot;{$submissionTitle}&quot;.<br />\n"
"<br />\n"
"Our decision is to:<br />\n"
"<br />\n"
"Manuscript URL: {$submissionUrl}"
```
In the PR I'm modifying only `EDITOR_DECISION_SEND_TO_EXTERNAL` as I suspect @kshuttle is already working on other ones.

Templates in OMP are more or less the same as in OJS, except `COPYEDIT_REQUEST`, which at the first glance contains older instructions in OMP and `LAYOUT_REQUEST`, where the instruction to upload the file is missing from the list

**Comment by Vitaliy-1** [comment]
Upgrade tests for OJS 3.1 are failing with a fatal error:
```
php tools/upgrade.php upgrade
2021-12-20 09:58:53 [pre-install]
2021-12-20 09:58:53 [load: upgrade.xml]
2021-12-20 09:58:53 [version: 3.4.0.0]
2021-12-20 09:58:53 [code: Installer Installer::checkPhpVersion]
2021-12-20 09:58:53 [data: dbscripts/xml/upgrade/3.1.2_preupdate_user_author_names.xml]
2021-12-20 09:58:53 [code: Installer Installer::migrateSubmissionCoverImages]
2021-12-20 09:58:53 [data: dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml]
2021-12-20 09:58:54 [data: dbscripts/xml/upgrade/3.2.0_preupdate_versioning_articleGalleySettings.xml (skipped)]
2021-12-20 09:58:54 [data: dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml]
2021-12-20 09:58:54 [data: dbscripts/xml/upgrade/3.2.0_preupdate_last_activity.xml]
2021-12-20 09:58:55 [schema: lib/pkp/xml/schema/common.xml]
PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_runtime() in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/adodb/adodb-php/adodb-xmlschema.inc.php:1307
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(405): adoSchema->__construct()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(285): PKP\install\Installer->executeAction()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(200): PKP\install\Installer->executeInstaller()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(99): PKP\install\Installer->execute()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(72): PKP\cliTool\UpgradeTool->upgrade()
#5 /home/doc/OJS/development/ojs/tools/upgrade.php(21): PKP\cliTool\UpgradeTool->execute()
#6 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/adodb/adodb-php/adodb-xmlschema.inc.php on line 1307
``` 
It looks like not related to this PR and likely is fixed by this commit: https://github.com/pkp/pkp-lib/commit/469ea6a181c57dc0b9422a359aa250ca2ae7575a
I've updated PR for OJS and restarted tests just in case.

**Comment by asmecher** [comment]
@Vitaliy-1 -- shoot, I thought I had the upgrade problems ironed out on Friday. Let me look into it this morning.

**Comment by Vitaliy-1** [comment]
@asmecher, the PR was done also on Friday, at the end of my day, probably before the fix you've introduced. After re-basing PR on the fresh main branch, upgrade tests are passing.

**Comment by fgnievinski** [comment]
great improvement, I've tried something similar in the past, but not nearly as thorough:
https://github.com/pkp/ojs/pull/2501 insert "dear" before user name

**Comment by fgnievinski** [comment]
can translators start working on localizing the modified text -- is the version in English frozen yet?

btw: the modified text already appears in weblate but it seems not all localizations are flagged as "needs editing", confirm?

**Comment by NateWr** [comment]
@fgnievinski I think it is safe to begin translation work now. However, please be aware that these have not been tested beyond a few key stakeholders. That means that although they've had a good review, they may still receive minor changes (eg - bug fixes and typos). And once 3.4 enters its main testing phase,  more editorial professionals will start using them and may suggest more significant changes. However, I don't expect it to be a complete rewrite, so most translation work done now should still be useful later.

(Also, we haven't yet integrated all of the new text into the `main` branch. We're working email-by-email.)

**Comment by kshuttle** [comment]
Hi @NateWr,

Thanks for drafting these and sharing them with me! I think they look good. The only edits I would suggest are very minor wording choices which don't really impact the messaging overall, so feel free to take-or-leave these.

In various emails, instead of:

>I apologize for the confusion this has caused. 

Replace with:

>I apologize for any confusion this may have caused.

In the editorDecisionNewReviewRound email:

Instead of:

>Your submission, {$submissionTitle}, has been sent for a new round of peer review. An editor will send your revised submission to reviewers and we will contact you when the reviews are in and a decision is made.

Replace with:

>Your revised submission, {$submissionTitle}, has been sent for a new round of peer review. You will hear from us with feedback from the reviewers and information about the next steps.

(This wording is closer to that used in the email to authors when their submission goes for the first round of review).

**Comment by NateWr** [comment]
That's great, thanks @kshuttle!

**Comment by NateWr** [comment]
@kshuttle here's another new email template, for when a submission is sent to the review stage. I feel like it should have some more information about what the author can expect, maybe a note on the challenges of finding reviewers who complete in a timely manner, etc. But I'm struggling to think of what to say. Can you take a pass at it?

> Dear {$recipientName},
>
> I am pleased to inform you that your submission, {$submissionTitle}, meets our requirements for submission to {$contextName}. It has now be sent for a round of peer review.
> 
> You will hear from us with feedback from the reviewers and information about the next steps.
>
> If you have any questions, please contact me from your <a href=\"{$submissionUrl}\">submission dashboard</a>.
>
> Kind regards,
> 
> {$signature}

**Comment by kshuttle** [comment]
Hi @NateWr,

Is there some overlap with this new template and the ones proposed here? https://github.com/pkp/pkp-lib/issues/7356

This other one is split into three templates depending on the type of peer review being conducted, but we could simplify this down to one template by removing that detail. We could leave in the following details for authors about what to expect:

> All reviewer comments will be sent to the editor, who will share the reviewers’ feedback with you and correspond with you about the next steps.

> Please note that sending the submission to peer review does not guarantee that it will be published. We will consider the reviewers’ recommendations before deciding to accept the submission for publication. You may be asked to make revisions and respond to the reviewers’ comments before a final decision is made.

I'll give some thought to some possible wording about the timing, as well.

**Comment by NateWr** [comment]
Ah, yes, I had forgotten about those. I'll follow those templates, thanks!

**Comment by NateWr** [comment]
Most of the work in this issue is complete. I will leave it open because I'd like to do a final review before 3.4 RC1 to make sure all of the new email messages have been updated -- especially in OMP where I may have forgotten one or two.

**Comment by NateWr** [comment]
I've gone through and done a final pass to make sure all of the edited email templates have been applied across all three apps. Thanks again to @kshuttle for leading the rewrites, Emma and Veronica (@openacademia) for contributing their expertise, and @Vitaliy-1 for the implementation. Reviewing all of these was a good reminder of just how big a project this was and how much they've been improved. :1st_place_medal: 

PRs:
https://github.com/pkp/pkp-lib/pull/8626
https://github.com/pkp/ojs/pull/3759
https://github.com/pkp/omp/pull/1335
https://github.com/pkp/ops/pull/470

**Comment by NateWr** [comment]
:tada: All merged to `main`. Thanks everyone!
