### ISSUE TITLE
Error messages and failed loading after upgrade to 3.2.0.1

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5737]
_Originally posted by @dudu9999 in https://github.com/pkp/pkp-lib/issues/5690#issuecomment-613612943_

@NateWr 
Application Version - OJS 3.2.0.1

Description of issue:
Any list that I access does not appear.

Example:
1 - When I am going to edit a user, the list of papers (Review and page editor) does not appear like this, making it impossible to save after editing.
2 - The list of roles for me to create a new role does not appear.
3 - The navigation pages do not appear the list with all to edit.
4 - Some settings do not save, the loading icon is rotating and does not perform the save function.

Everything I said is shown in the prints I took from the system.
Note: I was with version 3.1.2.4 and acted for version 3.2.0.1 but the bugs did not resolve, on the contrary it resulted in the bug item 2.

Screenshots

![image](https://user-images.githubusercontent.com/17937849/79260394-9895b980-7e64-11ea-8751-cc5312bbd934.png)

![image](https://user-images.githubusercontent.com/17937849/79260415-9f243100-7e64-11ea-8b6d-59918ad0e4e0.png)

![image](https://user-images.githubusercontent.com/17937849/79260454-ad724d00-7e64-11ea-8e6d-bd6ce561faf8.png)

![image](https://user-images.githubusercontent.com/17937849/79260472-b531f180-7e64-11ea-9fa2-52f4fcecdf59.png)

Link
https://www.institutoventuri.org.br/ojs/

Log

    Notice: Deprecated call without request object. in /home/venturi/public_html/ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 954

    firs:1 Unchecked runtime.lastError: The message port closed before a response was received.(https://www.institutoventuri.org.br/ojs/index.php/firs/management/settings/access#roles)

    For testing I did a new installation and researching I managed to solve the part of symbols that appear instead of accents.

    **Notice** : Deprecated call without request object. in**/home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php**  on line **954**

    **Warning** : Cannot modify header information - headers already sent by (output started at  /home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php:954) in  **/home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php**  on line  **898**

    **Warning** : Cannot modify header information - headers already sent by (output started at /home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php:954) in   **/home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php**  on line  **899**

    Method PKPApplication::getRequest() should not be called statically in /home/venturi/public_html/ojsf/plugins/themes/bootstrap3/BootstrapThreeThemePlugin.inc.php on line 107

    Deprecated: Non-static method PKPApplication::getRequest() should not be called statically in /home/venturi/public_html/ojsf/plugins/themes/bootstrap3/BootstrapThreeThemePlugin.inc.php on line 129

    Warning: Cannot modify header information - headers already sent by (output started at /home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php:954) in /home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 898

    Warning: Cannot modify header information - headers already sent by (output started at /home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php:954) in /home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 899

    [08-Apr-2020 17:29:51 America/Sao_Paulo] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php:954) in /home/venturi/public_html/ojsf/lib/pkp/classes/core/PKPRouter.inc.php on line 408

    [08-Apr-2020 17:29:51 America/Sao_Paulo] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php:954) in /home/venturi/public_html/ojsf/lib/pkp/classes/core/PKPRouter.inc.php on line 408

    [08-Apr-2020 17:32:18 America/Sao_Paulo] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/venturi/public_html/ojsf/lib/pkp/classes/template/PKPTemplateManager.inc.php:954) in /home/venturi/public_html/ojsf/lib/pkp/classes/core/PKPRouter.inc.php on line 408

    [08-Apr-2020 17:33:17 America/Sao_Paulo] PHP Deprecated:  Non-static method PKPApplication::getRequest() should not be called statically in /home/venturi/public_html/ojsf/plugins/themes/bootstrap3/BootstrapThreeThemePlugin.inc.php on line 107

    [08-Apr-2020 17:33:17 America/Sao_Paulo] PHP Deprecated:  Non-static method PKPApplication::getRequest() should not be called statically in /home/venturi/public_html/ojsf/plugins/themes/bootstrap3/BootstrapThreeThemePlugin.inc.php on line 129

    [access_compat:error] [pid 3806353] AH01797: client denied by server configuration: /home/venturi/public_html/index.php, referer: http://www.institutoventuri.org.br/ojs/index.php/firs/issue/archive
    [access_compat:error] [pid 3806353] AH01797: client denied by server configuration: /home/venturi/public_html/ojs/index.php, referer: http://www.institutoventuri.org.br/ojs/index.php/firs/issue/archive
    [access_compat:error] [pid 3781497] AH01797: client denied by server configuration: /home/venturi/public_html/index.php, referer: http://www.institutoventuri.org.br/ojs/index.php/firs/issue/archive
    [access_compat:error] [pid 3781497] AH01797: client denied by server configuration: /home/venturi/public_html/ojs/index.php, referer: http://www.institutoventuri.org.br/ojs/index.php/firs/issue/archive
    [access_compat:error] [pid 3760476] AH01797: client denied by server configuration: /home/venturi/public_html/ojs/index.php
     [access_compat:error] [pid 3760458] AH01797: client denied by server configuration: /home/venturi/public_html/ojs/index.php
     [access_compat:error] [pid 3154520] AH01797: client denied by server configuration: /home/venturi/public_html/ojs/index.php
     [authz_core:error]    [pid 2875782] AH01630: client denied by server configuration: /home/venturi/public_html/ojs/plugins/generic/pdfJsViewer/pdf.js/web/images/toolbarButton-search.png
     [access_compat:error] [pid 1847420] AH01797: client denied by server configuration: /home/venturi/public_html/index.php, referer: http://www.institutoventuri.org.br/ojs/index.php/firs/article/view/653
     [access_compat:error] [pid 1847420] AH01797: client denied by server configuration: /home/venturi/public_html/favicon.ico, referer: http://www.institutoventuri.org.br/ojs/index.php/firs/article/view/653
    [access_compat:error] [pid 1847420] AH01797: client denied by server configuration: /home/venturi/public_html/ojs/index.php, referer: https://www.google.com/

![image](https://user-images.githubusercontent.com/17937849/79260795-3ab5a180-7e65-11ea-859e-9c0563c2a558.png)

![image](https://user-images.githubusercontent.com/17937849/79260813-41441900-7e65-11ea-83c2-0e0a84c93c50.png)

![image](https://user-images.githubusercontent.com/17937849/79261055-a4ce4680-7e65-11ea-94e8-6d3ba9fedb8c.png)

![image](https://user-images.githubusercontent.com/17937849/79261067-aac42780-7e65-11ea-9555-aa37e68eb1a2.png)

![image](https://user-images.githubusercontent.com/17937849/79261078-b0ba0880-7e65-11ea-98da-3492760b9b1c.png)

![image](https://user-images.githubusercontent.com/17937849/79261118-be6f8e00-7e65-11ea-8c9d-fc6bc8a6bc67.png)

![image](https://user-images.githubusercontent.com/17937849/79261309-05f61a00-7e66-11ea-9135-92a0df5b05b7.png)

-------------------------------------------------------------------------------------------------------
language Portuguese
![image](https://user-images.githubusercontent.com/17937849/79261156-cd564080-7e65-11ea-83ad-32c332556065.png)

english language
![image](https://user-images.githubusercontent.com/17937849/79261277-f8d92b00-7e65-11ea-84f5-06593abde8f0.png)

thanks again for your help and attention.

**Comment by NateWr** [comment]
Hi @dudu9999,

It looks like PHP notices and warnings are being displayed. This is going to cause issues with ajax requests and could be the source of the problems that you're experiencing.

In your `config.inc.php` file, find the `[debug]` section and make sure all of those options are set to `Off`. 

Once you do that, you shouldn't see error messages printed to the screen like in [this screenshot](https://user-images.githubusercontent.com/17937849/79260795-3ab5a180-7e65-11ea-859e-9c0563c2a558.png). If you do, you may need to check your server configuration to hide notices and warnings.

**Comment by dudu9999** [comment]
Hi @NateWr 
To get new logs I did the steps below.

**1 - I accessed the page.**
![image](https://user-images.githubusercontent.com/17937849/79494995-51413180-7ffa-11ea-9b6e-9ad86c881109.png)

**2 - I accessed the login page**
![image](https://user-images.githubusercontent.com/17937849/79495086-72a21d80-7ffa-11ea-92c5-0ab796d2ca06.png)

**3 - I accessed the settings page / Website**
![image](https://user-images.githubusercontent.com/17937849/79495607-3ae7a580-7ffb-11ea-8b8b-c55962e6d92f.png)

![image](https://user-images.githubusercontent.com/17937849/79495638-43d87700-7ffb-11ea-8313-eeee51d33c80.png)

![image](https://user-images.githubusercontent.com/17937849/79496061-fc061f80-7ffb-11ea-8ccf-3048da42c33a.png)

**thanks again for your help and attention Nate.**

**Comment by NateWr** [comment]
Can you show me the database records for your journal settings for the locales? The following command should do it:

```
select * from journal_settings where setting_name LIKE '%Locales%' OR setting_name="primaryLocale"
```

**Comment by dudu9999** [comment]
hi @NateWr 

![image](https://user-images.githubusercontent.com/17937849/79808266-af944a00-8343-11ea-845d-1b85c83be17c.png)

thanks again for your help and attention Nate.

**Comment by NateWr** [comment]
Hmm, it looks like maybe the array keys are off. Can you expand the `setting_value` column so we can see the whole thing?

Also, can you remind me if you had this problem in 3.1.x as well? Or only when you upgraded to 3.2?

**Comment by NateWr** [comment]
In the end, I think that this _is_ the same problem as #5690. You can read about the solution in [this comment](https://github.com/pkp/pkp-lib/issues/5690#issuecomment-617688409).

I will close this for now but let me know if the fix described there does not solve the problem for you.
