### ISSUE TITLE
[OPS] New notification email link returns "A workflow stage was not specified."

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5738]
**Describe the bug**
When a Series Editor receives an email about a new notification, the link to the submission returns a "A workflow stage was not specified."

**To Reproduce**
1. Assign a Series Editor to a preprint.
2. Send them a message via "Production Discussions"
3. Check the email sent to the Section Editor and click on the submission link.
4. See message.

**What application are you using?**
Open Preprint Systems 3.2.0 Beta

**Additional information**
![c2371949-d4e1-41c2-bfa8-c65861c8b82f](https://user-images.githubusercontent.com/4059679/79336473-312a4900-7efa-11ea-80bd-041744a141e4.jpg)

**Comment by ajnyga** [comment]
ok, thanks. I will look into this.

**Comment by ajnyga** [comment]
I tested this with both the master branch and stable and the link leads to the right place.

What does the link look like?
Are you logged in to the system when you click it?
If you are logged in, with what account?

**Comment by alexxxmendonca** [comment]
Hi @ajnyga 

_What does the link look like?_
https://preprints.scielo.org/index.php/scielo/workflow/submission/42

_Are you logged in to the system when you click it?_
Yes.

If you are logged in, with what _account?_
Both the Server Admin account and Section Editor account assigned to the preprint:
![image](https://user-images.githubusercontent.com/4059679/79358994-62b20d00-7f18-11ea-954e-613b4266292f.png)

**Comment by ajnyga** [comment]
hmm, ok it should look like https://preprints.scielo.org/index.php/scielo/workflow/access/42

What does your template look like in Settings > Workflow > Emails. The name of the template in English is Moderator Assignment. The current version looks like this.

<img width="1101" alt="Screenshot 2020-04-15 at 19 11 44" src="https://user-images.githubusercontent.com/16347527/79360773-0ae1c900-7f4d-11ea-8975-00afc4893ef2.png">

**Comment by ajnyga** [comment]
(note to myself that https://github.com/pkp/ops/blob/master/controllers/grid/users/stageParticipant/form/StageParticipantNotifyForm.inc.php needs some editing)

**Comment by alexxxmendonca** [comment]
It looks like this:

![image](https://user-images.githubusercontent.com/4059679/79367971-10c3b400-7f25-11ea-95ad-24e7a265140a.png)

We haven't upgraded to the version that was released yesterday yet.

**Comment by alexxxmendonca** [comment]
> hmm, ok it should look like https://preprints.scielo.org/index.php/scielo/workflow/access/42

For the record, me as a Server Administrator am getting this when clicking on this link:

![image](https://user-images.githubusercontent.com/4059679/79368074-3781ea80-7f25-11ea-9c53-39a3de82e08b.png)

Should Server Administrators have full access to all?

**Comment by ajnyga** [comment]
Sure admins have access to everything, but for some reason the link in your case is probably leading into a stage that does not exist in OPS.

**Comment by ajnyga** [comment]
Ok, so I was looking at the wrong template. I have a fix for this ready.

**Comment by ajnyga** [comment]
OPS: https://github.com/pkp/ops/pull/12

Will cherry pick to OPS stable 3.2.0 after I merge to master.

**Comment by alexxxmendonca** [comment]
This has been fixed so I'm closing this issue.
