### ISSUE TITLE
Different Contributor roles like translators are not taken into account when displaying and exporting metadata

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5739]
OJS/OMP/OPS should present different contributor roles more clearly. At the moment there is a theoretical ability to create different kinds of contributor roles, but in reality they are all treated as "authors".

When you add for example a translator and photographer contributors to an article, these contributors are shown the same way as the author in OJS templates and in the metadata exports. 

### Current approach to distinguish roles:

UserGroups have a `showTitle` attribute. When it is selected, the name of the role should be visible behind the contributors name. This is used in the `getAuthorString` function. https://github.com/pkp/pkp-lib/blob/master/classes/publication/PKPPublication.inc.php#L130

### Shortcomings of the current approach:

Almost the only place where `getAuthorString` is used is the TOC. This means that for example in the Landing Page and the Crossref Metadata exports **all contributors are presented as regular authors**. This is especially bad when data is exported. 
 
With citation formats the Translator always has a fixed position in the citation and Google Scholar specifically mentions that _only_ actual authors should be listed in the tags https://scholar.google.com/intl/en/scholar/inclusion.html#indexing which is not happening now.

### New approach:

This is open to discussion, but IMO we need a UserGroup setting for defining which of the existing userGroups are actual **Author** roles (usually just one) and which are auxiliary roles. And for some Auxiliary roles, like **Translator**, we need to have specific ways of handling the contributors assigned to that role/userGroup ie. showing/listing them in the correct place and with the correct metadata attributes.

**So in short, we need the ability to apply a taxonomy to the UserGroups and we need to code some functionalities to some of the roles listed in the taxonomy.**

The setting could be for example a pull down / radio group with labels like "Treat the Contributors in this group as Authors", "Treat the Contributors in this group as Translators" etc.

For visual presentation in the TOC and Landing page, the showTitle attribute is probably a good approach, but it needs to be taken into account also in getFullName https://github.com/pkp/pkp-lib/blob/master/classes/submission/PKPAuthor.inc.php#L65. 

### Places where the contributor role needs to be considered:

- If enabled in userGroup settings, show the contributor name and the contributor role in parenthesis: TOC, Landing page, Contributors grid
- Follow the citation standard: citationStyleLanguage plugin
- Follow the used metadata schema: OAI-PMH, DOAJ export, Crossref export, ORCID, Google Scholar, DC, etc.

### Taxonomy:

Using the CASRAI CRediT standard is suggested here: https://github.com/pkp/pkp-lib/issues/857

However, I do not see how it would help a lot with this problem. The important thing here is that we need to tie different actions to specific contributor roles. For this we need a more simple taxonomy with the most usual roles.

Different citation standards usually distinquish at least between the author, editor and translator.

DC has a huge list of possible roles: http://memory.loc.gov/diglib/loc.terms/relators/dc-contributor.html

Crossref has these contributor_role values: author, editor, chair, reviewer, review-assistant, stats-reviewer, reviewer-external, reader, translator

ORCID has these contributor_role values: author, assignee, editor, chair-or-translator, co-investigator, co-inventor, graduate-student, other-inventor, principal-investigator, postdoctoral-researcher, support-staff

**IMO we could go far just by having the ability to define between three types of Contributors: authors, translators, other.**
- Contibutors belonging to a userGroup marked as "Author" would be listed as authors are listed now. We could have a function for calling just these types of contributors and leaving out other types.
- Contibutors belonging to a userGroup marked as "Translator" would be listed in the landing page with the given UserGroupName mentioned after the Contributor name and shown according to the standards defined in citation styles and different metadata schemas.
- Contibutors belonging to a userGroup marked as "Other" would *only* be listed in the landing page with the given UserGroupName mentioned after the Contributor name. This type could be used for all kinds of contributors that do not need to be mentioned in metadata exports, like illustrators, photographers etc.

**Comment by ajnyga** [comment]
missed this when looking through existing issues: https://github.com/pkp/pkp-lib/issues/3962
tagging @ctgraham

**Comment by ajnyga** [comment]
Related forum discussions:
https://forum.pkp.sfu.ca/t/mix-with-authors-co-authors-and-translators/49848
https://forum.pkp.sfu.ca/t/crossref-export-contributor-role-translator-is-not-used/47033
https://forum.pkp.sfu.ca/t/ojs3-user-roles/23372

**Comment by ajnyga** [comment]
also ping @withanage because this is also an issue in the ORCID plugin.

Currently the plugin defines the difference between an Author and a Translator based on the userGroup en_US name: https://github.com/pkp/orcidProfile/blob/master/OrcidProfilePlugin.inc.php#L37 and https://github.com/pkp/orcidProfile/blob/master/OrcidProfilePlugin.inc.php#L1147.

This of course breaks if some OJS installation decides to rename one of these groups. The logic should be based on something else than the group name label.

**Comment by fgnievinski** [comment]
> Different citation standards usually distinquish at least between the author, editor and translator.

for example, in [APA style](https://apastyle.apa.org/blog/citing-translated-works):

> Credit the translator or translators in the reference by writing the abbreviation “Trans.” after the translator’s name and placing both the name and abbreviation in parentheses after the title of the work...
> 
> > 
> > Piaget, J. (1972). Intellectual evolution from adolescence to adulthood (J. Bliss & H. Furth, Trans.). Human Development, 15(1), 1–12. https://doi.org/10.1159/000271225 (Original work published 1970)

**Comment by asmecher** [comment]
@fgnievinski, we use the citeproc-php library (via the Citation Style Language plugin) to format citations, and it supports translator/editor designations. @ajnyga makes reference to this plugin in the initial entry, so that requirement should be covered by his notes.

**Comment by asmecher** [comment]
@ajnyga, I put together a PR for this during the Bogota sprint; would it serve your needs?

https://github.com/pkp/ojs/pull/3446

**Comment by ajnyga** [comment]
Thanks! It does seem to fix the presentation on the landing page. 

I think we still have a problem with upstream uses of the data. For example DOAJ, ORCID, Crossref, OAI-PMH. All these do not consider that some contributors are not authors. IMO to only viable solution here is to have the ability to define a usergroup to be an `author usergroup` using some taxonomy. This will enable us to query the database by saying that "give me all contributors that are authors", instead of just listing all contributors that exist.

We really would not need an official taxonomy for this either. We could go a long way just by distinquishing between "author", "translator" and "other". 

As long as we do not have some sort of a taxonomy in place, we really just have labels like "author" that we can use, which is of course very problematic: https://github.com/pkp/orcidProfile/blob/main/OrcidProfilePlugin.inc.php#L51

**Comment by asmecher** [comment]
Agreed about taxonomy and non-author contributions. We looked into this pretty heavily during the CRediT sprint sessions, and while CRediT is being widely adopted and at least adds a common vocabulary (good), it's not goot at all at distinguishing between e.g. translator and author (probably our biggest use case). So we'll be stuck with half-measures for the moment, and I'm hoping the PR is a step in the right direction.

**Comment by asmecher** [comment]
I'm choosing to resolve this *only* for OJS 3.4.0, not OMP and OPS, as the display requirements there haven't been vetted and are likely different (especially OMP for chapters).

**Comment by ajnyga** [comment]
@asmecher I reopened this issue, because it is closely related to the Contributor Role changes we are suggesting and I the changes above have only resolved the visual display of the role in the landing. The metadata level and the upstream use are imo more important and have not been resolved.

**Comment by asmecher** [comment]
@ajnyga, could you file a new issue for future work? Some implementation did go into 3.4.0 for this, and I'd like to keep the closed issue record an accurate reflection of what happened when.
