### ISSUE TITLE
[OJS] Notification subscription (mailing list) source is confusing

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#574]
The Notification mailings are handled by PKPNotificationManager, and is the source of NOTIFICATION_MAILLIST emails and NOTIFICATION_MAILLIST_WELCOME emails:
https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_6/classes/notification/PKPNotificationManager.inc.php#L466
https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_6/classes/notification/PKPNotificationManager.inc.php#L498

These functions are called from the Journal level:
https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/classes/manager/form/AnnouncementForm.inc.php#L84
https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/pages/editor/IssueManagementHandler.inc.php#L989

Though not exposed in any link of which I'm aware, it almost seems like subscribing to notification at the Site level could work, since the handler makes it available:
https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_6/pages/notification/index.php#L27

But in actually trying it, we die here:
https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_6/classes/notification/form/PKPNotificationSettingsForm.inc.php#L42
with `PHP Fatal error:  Call to a member function getId()`

All this to say, I don't think there is a way to be sent notifications at the Site level, and I'm not convinced one would want to.  Notification seems appropriate at the Journal (context specific) level.

The NOTIFICATION_MAILLIST and NOTIFICATION_MAILLIST_WELCOME emails reference `$siteTitle` instead of `$journalName`, however.
https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/locale/en_US/emailTemplates.xml#L27
https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/locale/en_US/emailTemplates.xml#L41

We've found that to be confusing to journal managers and to end-users.

If my reading is correct, I propose changing these templates to default to `$journalName` instead of `$siteTitle`.

**Comment by asmecher** [comment]
@ctgraham, that's OK with me -- but I think the whole piece needs to be rewritten for the 3.0 level. It's a bit of a mess.

**Comment by asmecher** [comment]
That makes sense. Merged, thanks!
