### ISSUE TITLE
[OPS] Upgrade to OPS 3.2.0-1 does not sync database schema descriptors

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5742]
From https://forum.pkp.sfu.ca/t/fatal-error-after-upgrading-ops3-2-0beta-to-ops3-2-0-1-beta/59877:
> I upgraded with a successful screen message from 3.2.0 to 3.2.0-1 today, but when browsing it gives HTTP ERROR 500 with following php error log.
> ```
>[15-Apr-2020 03:19:40 UTC] PHP Fatal error: Uncaught Exception: DB Error: Unknown column ‘s.locale’ in ‘field list’ Query: SELECT DISTINCT
>sf.file_id AS submission_file_id, sf.revision AS submission_revision,
>af.file_id AS artwork_file_id, af.revision AS artwork_revision,
>suf.file_id AS supplementary_file_id, suf.revision AS supplementary_revision,
>COALESCE(p.locale, s.locale) AS submission_locale, sf., af., suf.*
>FROM submission_files sf
>LEFT JOIN submission_artwork_files af ON sf.file_id = af.file_id AND sf.revision = af.revision
>LEFT JOIN submission_supplementary_files suf ON sf.file_id = suf.file_id AND sf.revision = suf.revision
>LEFT JOIN submissions as s ON s.submission_id = sf.submission_id
>LEFT JOIN publications p ON s.current_publication_id = p.publication_id LEFT JOIN submission_files sf2 ON sf.file_id = sf2.file_id AND sf.revision < sf2.revision
>WHERE sf2.revision IS NULL AND sf.file_id = ? ORDER BY sf.submission_id ASC, sf.file_stage ASC, sf.file_id ASC, sf.revision DESC in C:\wamp64\www\ops\lib in C:\wamp64\www\ops\lib\pkp\classes\db\DAO.inc.php on line 703
>```

This can be solved by running the following SQL query:
```
ALTER TABLE submissions ADD COLUMN locale VARCHAR(14);
```

**Comment by ajnyga** [comment]
who removed the schema files from upgrade.xml!

**Comment by ajnyga** [comment]
IMO we should release 3.2.0-2 as soon as possible, some of Scielos problems were probably due to this bug.

**Comment by asmecher** [comment]
I can do this today; let me know if/when you're finished pulling anything else into the stable branch for it.

**Comment by ajnyga** [comment]
I am working on the galley editing issue you mentioned in Slack. Otherwise I cherry-picked these to stable branch today https://github.com/pkp/ops/pull/12 and https://github.com/pkp/ops/pull/11
