### ISSUE TITLE
\APP\components\forms\context\MetadataSettingsForm does not exists

### ISSUE THREAD

**Issue by Pawel9903** [pkp/pkp-lib#5746]
Hello,
in /lib/pkp/pages/management/ManagementHandler.inc.php line 215 class try import not existing class \APP\components\forms\context\MetadataSettingsForm.
Shouldn't create an instance \PKP\components\forms\context\PKPMetadataSettingsForm ?

**Comment by asmecher** [comment]
@Pawel9903, do you see `classes/components/forms/context/MetadataSettingsForm.inc.php` in your installation? I suspect that file is missing.

If that's not the problem, please include which of our apps you're using, what version, and how you installed it (e.g. from `.tar.gz` download, from `git` checkout, or something else).
