### ISSUE TITLE
Correct URLs to HTML galleys in CrossRef export

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#575]
See http://forum.pkp.sfu.ca/t/viewfile-url-in-crossref-xml-export/1800

The bug is in...
https://github.com/pkp/ojs/blob/ojs-2_4_6-0/plugins/importexport/crossref/classes/CrossRefExportDom.inc.php#L471
...which is hard-coded to use `viewFile`, when `view` is probably more appropriate for HTML galleys.

**Comment by jmacgreg** [comment]
This may not be a bug - for text-mining purposes, viewFile (ie. a direct link to the file, rather than to the page and its other contents) may be more appropriate. Following up with CrossRef about this now.

**Comment by jmacgreg** [comment]
CrossRef prefers the raw galley file in all cases (even HTML) - so "viewFile" is correct here. Closing.
