### ISSUE TITLE
Submission checklist "edit" link leads to 404

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5753]
See https://forum.pkp.sfu.ca/t/404-not-found-after-upgrade-ojs-to-version-3-2-0-2/59922 for details:
> click on a journal -> about -> submissions -> and on edit of Submission Preparation Checklist and of Privacy Statement, delivers to this link:
> https://[domain]/index.php/[journal path]/management/settings/publication#submissionStage
> and shows 404 not found

Other similar "edit" links should be checked and fixed, as the settings rewrite probably broke a few of them.

**Comment by NateWr** [comment]
Good catch! Looks like there are a few themes effected by this as well. I'll let the theme team know.

PRs:
https://github.com/pkp/pkp-lib/pull/5802 (stable)
https://github.com/pkp/pkp-lib/pull/5803

Tests:
https://github.com/pkp/ojs/pull/2731 (stable)
https://github.com/pkp/ojs/pull/2732

**Comment by Vitaliy-1** [comment]
@NateWr, anchor part of URL doesn't open a tab to which it points, e.g., 
```
{url page="management" op="settings" path="website" anchor="setup" }
```
 won't open setup tab of the website settings.

**Comment by NateWr** [comment]
This is a known issue with the tabs, though I can't find an issue filed for it yet. The links will fallback to the op/path which is the best URL we can provide now, and when the tabs issue is fixed the links will get better.

**Comment by NateWr** [comment]
Merged to `master` and `stable-3_2_0`.

**Comment by vinitkumargunjan** [comment]
@NateWr @asmecher Could you please guide how to fix this issue, The files you highlighted in the fix are not available on the location templates/frontend/pages/ . I added them manually but problem is persisting. Could you help me with a fix for this issue. I am using ver 3.2.1.1

**Comment by NateWr** [comment]
The files that you want to work with are probably in `lib/pkp`. Templates that are shared with our other applications are located in `/lib/pkp/templates/frontend/pages`.
