### ISSUE TITLE
OJS 3.2.0.2 Unable to import CrossRef data

### ISSUE THREAD

**Issue by zalamuia** [pkp/pkp-lib#5755]
Dear Sir,

S platform | Linux
-- | --
PHP version | 7.2.17
Apache version | Apache/2.4.6 (CentOS)
Database driver | mysqli
Database server version | 5.5.60-MariaDB

After updating to OJS3.2..0.2 from 3.1.2.4 I am unable to import CrossRef data even can not download xml data also. 

It gives

This page isn’t working

XXXXXXX is currently unable to handle this request.
HTTP ERROR 500

And it looks like other IMPORTExport  also gives me same result except USER XML Plugin

Thanking you.

**Comment by asmecher** [comment]
Check your PHP error log for details; there should be a message there corresponding with the 500 response code you received.

**Comment by zalamuia** [comment]
**display_errors = on**


Fatal error: Uncaught Error: Call to a member function saveXml() on null in /home/ojs/ejournal/classes/plugins/PubObjectsExportPlugin.inc.php:372 Stack trace: 
#0 /home/ojs/ejournal/classes/plugins/PubObjectsExportPlugin.inc.php(195): PubObjectsExportPlugin->exportXML(Array, 'article=>crossr...', Object(Journal), true) 
#1 /home/ojs/ejournal/plugins/importexport/crossref/CrossRefExportPlugin.inc.php(267): PubObjectsExportPlugin->executeExportAction(Object(Request), Array, 'article=>crossr...', 'exportSubmissio...', 'articles', true) 
#2 /home/ojs/ejournal/classes/plugins/PubObjectsExportPlugin.inc.php(176): CrossRefExportPlugin->executeExportAction(Object(Request), Array, 'article=>crossr...', 'exportSubmissio...', 'articles', true) 
#3 /home/ojs/ejournal/classes/plugins/DOIPubIdExportPlugin.inc.php(29): PubObjectsExportPlugin->display(Array, Object(Request)) 
#4 /home/ojs/ejournal/lib/pkp/pages/management/PKPToolsHandler.inc.php(104): DOIPubIdExportPlugin->display(Array, Object(Request)) #5 /home/ojs/ejournal/lib/pkp/classes/ in /home/ojs/ejournal/classes/plugins/PubObjectsExportPlugin.inc.php on line 372



Fatal error: Uncaught Error: Call to a member function saveXml() on null in /home/ojs/ejournal/classes/plugins/PubObjectsExportPlugin.inc.php:372 Stack trace: 
#0 /home/ojs/ejournal/classes/plugins/PubObjectsExportPlugin.inc.php(195): PubObjectsExportPlugin->exportXML(Array, 'article=>doaj-x...', Object(Journal), false) 
#1 /home/ojs/ejournal/plugins/importexport/doaj/DOAJExportPlugin.inc.php(196): PubObjectsExportPlugin->executeExportAction(Object(Request), Array, 'article=>doaj-x...', 'exportSubmissio...', 'articles', false) #2 /home/ojs/ejournal/classes/plugins/PubObjectsExportPlugin.inc.php(176): DOAJExportPlugin->executeExportAction(Object(Request), Array, 'article=>doaj-x...', 'exportSubmissio...', 'articles', false) 
#3 /home/ojs/ejournal/plugins/importexport/doaj/DOAJExportPlugin.inc.php(52): PubObjectsExportPlugin->display(Array, Object(Request)) 
#4 /home/ojs/ejournal/lib/pkp/pages/management/PKPToolsHandler.inc.php(104): DOAJExportPlugin->display(Array, Object(Request)) 
#5 /home/ojs/ejournal/lib/pkp/classes/core/PK in /home/ojs/ejournal/classes/plugins/PubObjectsExportPlugin.inc.php on line 372


Fatal error: Uncaught Error: Call to a member function saveXml() on null in /home/ojs/ejournal/plugins/importexport/native/NativeImportExportPlugin.inc.php:253 Stack trace: 
#0 /home/ojs/ejournal/plugins/importexport/native/NativeImportExportPlugin.inc.php(197): NativeImportExportPlugin->exportSubmissions(Array, Object(Journal), Object(User)) 
#1 /home/ojs/ejournal/lib/pkp/pages/management/PKPToolsHandler.inc.php(104): NativeImportExportPlugin->display(Array, Object(Request)) 
#2 /home/ojs/ejournal/lib/pkp/classes/core/PKPRouter.inc.php(391): PKPToolsHandler->importexport(Array, Object(Request)) 
#3 /home/ojs/ejournal/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false) 
#4 /home/ojs/ejournal/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPPageRouter->route(Object(Request)) 
#5 /home/ojs/ejournal/lib/pkp/classes/core/PKPApplication.inc.php(278): Dispatcher->dispatch(Object(Request)) 
#6 /home/ojs/ejournal/index.php(68): PKPApplication->execute() 
#7 in /home/ojs/ejournal/plugins/importexport/native/NativeImportExportPlugin.inc.php on line 253


**Error Log file from other server**

 [Sat Apr 18 23:34:39.175280 2020] [:error] [pid 4554:tid 140207294723840] [client 10.36.2.1:48346] , referer: https://ojs.mynetgear.com/ojs3202/index.php/iiumej/submissions 
 [Sat Apr 18 23:34:39.465942 2020] [:error] [pid 1975:tid 140207521195776] [client 10.36.2.1:48352] Malformed UTF-8 characters, possibly incorrectly encoded, referer: https://ojs.mynetgear.com/ojs3202/index.php/iiumej/submissions 
 
 [Sun Apr 19 09:08:59.526837 2020] [:error] [pid 22110:tid 139976800921344] [client 10.36.2.1:49356] PHP Fatal error: Uncaught Error: Call to a member function saveXml() on null in /home/ojs/public_html/ojs3202/classes/plugins/PubObjectsExportPlugin.inc.php:372, referer: http://ojs.mynetgear.com/ojs3202/index.php/iiumej/management/importexport/plugin/CrossRefExportPlugin 
 
 [Sun Apr 19 09:08:59.526890 2020] [:error] [pid 22110:tid 139976800921344] [client 10.36.2.1:49356] Stack trace:, referer: http://ojs.mynetgear.com/ojs3202/index.php/iiumej/management/importexport/plugin/CrossRefExportPlugin 
 
 [Sun Apr 19 09:08:59.527019 2020] [:error] [pid 22110:tid 139976800921344] [client 10.36.2.1:49356] #0 /home/ojs/public_html/ojs3202/classes/plugins/PubObjectsExportPlugin.inc.php(195): PubObjectsExportPlugin->exportXML(Array, 'article=>crossr...', Object(Journal), false), referer: http://ojs.mynetgear.com/ojs3202/index.php/iiumej/management/importexport/plugin/CrossRefExportPlugin 
 
 [Sun Apr 19 09:08:59.527192 2020] [:error] [pid 22110:tid 139976800921344] [client 10.36.2.1:49356] 
 #1 /home/ojs/public_html/ojs3202/plugins/importexport/crossref/CrossRefExportPlugin.inc.php(267): PubObjectsExportPlugin->executeExportAction(Object(Request), Array, 'article=>crossr...', 'exportSubmissio...', 'articles', false), referer: http://ojs.mynetgear.com/ojs3202/index.php/iiumej/management/importexport/plugin/CrossRefExportPlugin 
 
 [Sun Apr 19 09:08:59.527346 2020] [:error] [pid 22110:tid 139976800921344] [client 10.36.2.1:49356] 
 
 #2 /home/ojs/public_html/ojs3202/classes/plugins/PubObjectsExportPlugin.inc.php(176): CrossRefExportPlugin->executeExportAction(Object(Request), Array, 'article=>crossr...', 'exportSubmissio...', 'articles', false), referer: http://ojs.mynetgear.com/ojs3202/index.php/iiumej/management/importexport/plugin/CrossRefExportPlugin 
 
 [Sun Apr 19 09:08:59.527439 2020] [:error] [pid 22110:tid 139976800921344] [client 10.36.2.1:49356] 
 
 #3 /home/ojs/public_html/ojs3202/classes/plugins/DOIPubIdExportPlugin.inc.php(29): PubObjectsExportPlugin->display(Array, Object(Request)), referer: http://ojs.mynetgear.com/ojs3202/index.php/iiumej/management/importexport/plugin/CrossRefExportPlugin [Sun Apr 19 09:08:59.527590 2020] [:error] [pid 22110:tid 139976800921344] [client 10.36.2.1:49356] 
 
 #4 /home/ojs/public_html/ojs3202/lib/pkp/pages/management/PKPToolsHandler.inc.php(104): DOIPubIdExportPlugin->d in /home/ojs/public_html/ojs3202/classes/plugins/PubObjectsExportPlugin.inc.php on line 372, referer: http://ojs.mynetgear.com/ojs3202/index.php/iiumej/management/importexport/plugin/CrossRefExportPlugin

**Comment by asmecher** [comment]
Hi @zalamuia -- see https://github.com/pkp/pkp-lib/issues/5681 for details and a solution.

**Comment by zalamuia** [comment]
Thanks. Problem solved.
