### ISSUE TITLE
Display galley pubIds on abstract and indexing metadata page

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#577]
The current problem some DE journals have now is that they use DOIs on
the article level and URNs on the galley level (e.g. it is the policy of
the German National Library), so the DOIs are displayed in the
'Indexing metadata' and URNs not, because the 'Indexing metadata' are
only on the article level (and only for the current GUI language). The
same problem would exist for the DOIs, if they would be assigned on
the galley level. 
Also, they would like to display those identifiers also on the abstract page.
Thus, it would maybe make sense to consider all identifiers (also the galleys pubIds) in the 'Indexing metadata' and on the abstract page. For the galleys pubIds the galley label should be displayed too -- in order to exactly know what the identifier is for.
The pull request is coming... :-)

**Comment by bozana** [comment]
Here the changes according to the alec's comments...

**Comment by asmecher** [comment]
Thanks, @bozana -- merged and also cherry-picked over to ojs-stable-2_4_6.
