### ISSUE TITLE
Add upgrade script to reset array keys for context locales

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5772]
Supported locale arrays are serialized in the database. Some old installations have arrays with non-sequential keys and this causes problems when the data is passed through `json_encode`, which turns it into an array. See #5690.

A stop-gap was put in place (https://github.com/pkp/pkp-lib/pull/5771/commits/de789013fb374d1cb4550a343bead67a3211fd37) by running it through `array_values()`. However, the data format should be updated in the database and the `array_values()` workaround should be removed.

**Comment by asmecher** [comment]
(We discussed swapping out `serialize` for `json_encode` for objects that are stored in serialized form in the database; that would solve this too.)

**Comment by NateWr** [comment]
I don't think that just swapping over to `json_encode` would solve this. The locales from the database would be decoded to an object in PHP, and then encoded into a JSON object when passed to the browser, so the error would persist. At some point, we need to reset those array keys.

**Comment by asmecher** [comment]
Yes, I was thinking they'd be reset when the conversion to JSON happened, and thereafter keeping things in the DB as a JSON array would prevent the ambiguity.

**Comment by Vitaliy-1** [comment]
@asmecher, just to clarify, is the idea to write an upgrade script that will transform serialized PHP arrays and objects to JSON analogs (with arrays being reset) in `setting_value` columns of settings tables with appropriate changes in `DAO::convertToDB` and `DAO::convertFromDB` alongside with other tables that use those methods to serialize values in DB (like `site` and `review_form_responses` in OJS)? Or just store new such data as JSON and add a check when unserialize, leaving the current DB intact? Sorry, I've missed the discussion.

**Comment by Vitaliy-1** [comment]
PRs 
OJS: https://github.com/pkp/ojs/pull/2873
pkp-lib: https://github.com/pkp/pkp-lib/pull/6247

**Comment by Vitaliy-1** [comment]
PR includes an upgrade script that converts serialized arrays and objects in `_settings` tables as well as other tables that are dependent from `DAO::convertToDB/convertFromDB` to JSON. Where is possible, the script relies on the data type coded in schema.json, in other cases - `setting_type` column. The latter identifies both arrays and objects as objects, thus there isn't reliable way from the script to distinguish between them. The workaround is upon data retrieval from the database unserialize JSON as associative array. I'm not experiencing problems with this approach on my test instance.

Also, it resets array keys for all associative arrays where keys are integers (not recursively). I'm not sure if it better to be done just for `journal_settings` or all setting values in the database: https://github.com/pkp/ojs/blob/a5a767917f02afdc74883a400b52dea0985e0d95/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php#L119
I was able to identify the problem with non-sequential array keys for locales and submission checklist setting values and assuming it may affect other settings of older OJS instances. I'm wondering if there are places when non-sequential array keys shouldn't be reseted and are used as a part of data.

**Comment by Vitaliy-1** [comment]
Forgot to mention that I've added a fallback condition here: https://github.com/pkp/pkp-lib/blob/f5d0ca454d0597b217bd4878ddcb5a33100ebae5/classes/db/DAO.inc.php#L359 to ensure that upgrade scripts that are executed alongside with this one don't brake anything

**Comment by asmecher** [comment]
> I'm wondering if there are places when non-sequential array keys shouldn't be reseted and are used as a part of data.

I'm not aware of any cases where numeric keys are used for anything beyond sequencing. You should be OK to reset numeric keys.

**Comment by asmecher** [comment]
Looks good overall, @Vitaliy-1! I've made a few small comments. Would you like a PostgreSQL sample database to test with?

**Comment by Vitaliy-1** [comment]
Yes. I have only MySQL dump of OJS database for testing.

**Comment by asmecher** [comment]
What version of OJS would you like me to send you a PostgreSQL DB dump for?

**Comment by Vitaliy-1** [comment]
3.2.1

**Comment by Vitaliy-1** [comment]
@asmecher, can you take another look at the PRs ones tests are finished? If all looks ok, I'll make similar changes for OMP and OPS

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1, comments made to the OJS PR -> https://github.com/pkp/ojs/pull/2873#issuecomment-703783321

**Comment by Vitaliy-1** [comment]
OMP master: https://github.com/pkp/omp/pull/870
OPS master: https://github.com/pkp/ops/pull/70
@asmecher, can you also take a look at these and merge all 4 if they are ok?

**Comment by asmecher** [comment]
All 4 merged -- thanks, @Vitaliy-1!
