### ISSUE TITLE
[OPS] Ammend preprint relations and submission conditions on preprint PDF

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5775]
**Describe the problem you would like to solve**
The relations of a preprint and the conditions to which it was submitted to the server are only shown on the web interface (HTML). These are not included on the PDF.

These PDFs can be posted and shared elsewhere, sometimes even out of context, which may raise trusting issues to preprints.

There needs to be clear indication of the status of the preprint and the full conditions to which it was submitted, not only on the platform, but also on the PDFs.

On the same note, the "Submission Checklist" serves as a "safety net" for preprint servers who are not responsible for its posted contents. It is important to inform readers who happen to get hold of the PDF out of the server context, the conditions to which the preprint was submitted and approved, as well as the relationships of that version.

**Describe the solution you'd like**
Ammend preprint "Relation" status before the PDF contents (as a small stripe, for instance, or a title page).
Ammend "Submission Checklist" that was in place for the time when that preprint was submitted to the server (after the PDF original contents or on the title page mentioned above).

**Who is asking for this feature?**
This comes more as a concern of Server runners, whose interests are to provide a trustful preprint platform and its offspring contents.

**Comment by asmecher** [comment]
This is something that would need to be implemented as a plugin, I think, because commodity servers may not reliably have tools present to add watermarks. There's some discussion of potential toolsets here: https://stackoverflow.com/questions/3983432/applying-watermarks-on-pdf-files-when-users-try-to-download-the-files

**Comment by ajnyga** [comment]
John had a related request on an automatically generated PDF cover page.

I agree that it would be problematic to offer this as a core feature, but a plugin would be possible. 

I think a plugin creating automatic cover pages would be a wellcome feature for OJS as well.

**Comment by alexxxmendonca** [comment]
Thank you! We are already looking into outsourcing a plugin development.

Agreed on being useful for OJS as well.

**Comment by ajnyga** [comment]
Did the plugin you created for cover pages also cover this issue?

**Comment by alexxxmendonca** [comment]
Hi @ajnyga, yes it does exactly that.

I think this issue can be closed, unless you want to wait until the plugin is in the public plugin gallery.

**Comment by asmecher** [comment]
I'm OK to close it for now; looking forward to seeing how the plugin works!
