### ISSUE TITLE
Sort country lists by country name, not code

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5776]
See https://forum.pkp.sfu.ca/t/changing-the-list-of-countries-displaying-on-registration/60031:
> Since they’re not in alphabetical order it’s hard to find some of them. I don’t think anybody would look for Switzerland under C. Also I’d only need like 6 countries and maybe ‘Other’.

**Comment by asmecher** [comment]
Commits to fix this for OJS 3.2.0 (before 3.2.0-3, in which the fix will be released):
- https://github.com/pkp/ojs/commit/a33f60c41b7d6108b43da6b835e9bf4bff0c2e9b (in the OJS installation directory)
- https://github.com/pkp/pkp-lib/commit/3982020dc8b00ac084eacba5decb4ae0566a3955 (in the `lib/pkp` subdirectory)

**Comment by eniocarboni** [comment]
On Medra importexport plugin at https://github.com/pkp/ojs/blob/a33f60c41b7d6108b43da6b835e9bf4bff0c2e9b/plugins/importexport/medra/classes/form/MedraSettingsForm.inc.php#L188 the **asort** method return **bool** not array. 
I think we can add: 
`return $countries;`
after line 188.
See https://www.php.net/asort

**Comment by asmecher** [comment]
Good catch, @eniocarboni -- I've fixed that in the `stable-3_2_0` and `master` branches. Interesting that there was no `return` before this issue introduced changes -- it looks like that was already broken to me!

**Comment by eniocarboni** [comment]
Yes, I think the "return" should have gone before the last commit.
The problem also exists for the OJS version 3.2.0-1 before this issue
