### ISSUE TITLE
Suppress SMTP authentication in PHPMailer

### ISSUE THREAD

**Issue by HongPong** [pkp/pkp-lib#5781]
**Describe the problem you would like to solve**
The client SMTP mailer had a certificate that could not be tuned to the expected host.

**Describe the solution you'd like**
An optional switch in the configuration file to adjust the PHPMailer parameters to skip checking the certificate of the contacted SMTP server.

**Who is asking for this feature?**
Server administrator/developer

**Additional information**
I was able to get this working and will attach the PR.

**Comment by HongPong** [comment]
Both PR's are required to get the expected behavior here. Thank you for considering the issue!

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/2720
- https://github.com/pkp/pkp-lib/pull/5782

Minor comments left on each; thanks, @HongPong. Please drop a note here when you've had a chance to go over them!

**Comment by HongPong** [comment]
PRs updated thanks for the review :)

**Comment by asmecher** [comment]
Merged for release in OJS 3.2.1 -- thanks for contributing!
