### ISSUE TITLE
UI could warn users that multiple file upload is not supported in OJS 2

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#5783]
As per previous discussions:

https://github.com/pkp/pkp-lib/issues/2097#issuecomment-268339436
> Basically the authors have used the " Upload Author Version" function to upload not only a revision of the actual manuscript but also revisions of other files and also new files altogether, like reports on the changes they have done etc. 

https://github.com/pkp/pkp-lib/issues/3789#issuecomment-397364092
> The v2 interface clearly allows to upload multiple files as reviewer. (...) After the upload, they are visible as separate files without any notion of revision. While the v2 database stores the files as revisions, the average user will not notice this. The fact that visibility options could be set separately undermines the impression of two separate files.

https://github.com/pkp/pkp-lib/issues/3502#issuecomment-374706203
> to be honest I also thought that we are uploading two files in OJS2, not one file and a revision.

It'd seem that authors and reviewers would benefit from a note in the user interface warning about this often misunderstanding:

_Multiple distinct files (e.g., cover letter and revised manuscript) should be uploaded as a single zipped file._

After all, OJS 2 supports versioning of a single file, in which case only the latest one will be shared between authors and reviewers (although editors will see all file versions).

Please note this issue affects users who wish to remain in OJS 2, without consideration for possible migration to OJS 3.

**Comment by asmecher** [comment]
@fgnievinski, this is an issue that affects only OJS 2.x, correct?

We're definitely not going to devote more time as a team to developing OJS 2.x, although community maintenance is welcome (e.g. if you'd like to submit a pull request).

> Please note this issue affects users who wish to remain in OJS 2, without consideration for possible migration to OJS 3.

That's going to be a limited-time strategy, I'm afraid, as the server platforms move on (e.g. PHP) and backwards-compatibility gets broken. If there's a particular reason journals aren't planning to upgrade to 3.x, that might be worth discussing further e.g. on the support forum.

**Comment by fgnievinski** [comment]
sure, here are two pull requests:
https://github.com/pkp/ojs/pull/2724
https://github.com/pkp/ojs/pull/2725

w.r.t. reasons for not upgrading at this time, 
the main one currently is incomplete translations.

thanks.

**Comment by asmecher** [comment]
@fgnievinski, have you tested those PRs? I don't think they'll work without either `<![CDATA` ... `]]>` escaping or using `&lt;` / `&gt;` style entities in place of `<` and `>` etc.

Is there a particular translation you're waiting for? We launched Weblate as a replacement for our old translation management tools early this year -- see [Introducing Weblate, A New Path for OJS/OMP Translations](https://pkp.sfu.ca/2020/01/22/introducing-weblate-a-new-path-for-ojs-omp-translations/) for details. This has made it much easier to collaboratively update translations and there's been a ton of uptake.

**Comment by fgnievinski** [comment]
weblate is great, I've contributed already to pt-BR.

**Comment by asmecher** [comment]
Agreed, thanks; closing.
