### ISSUE TITLE
H1 for screen readers not available in Site level if site logo is given

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5789]
**Describe the bug**
In multijournal installations adding a site logo means that there is no H1 title available in site level index.

This is because `$site->getLocalizedPageHeaderTitle()` can return either a string or a logo image. When a Site logo is given, the value of `displayPageHeaderTitle` is an array containing the image data and the template here does not work as expected:
https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/header.tpl#L41

The `$context->getLocalizedPageHeaderTitle()` will always return just a string so you will not see the same problem inside a Context.

You will also see a warning:
`PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /lib/pkp/lib/vendor/smarty/smarty/libs/plugins/modifier.escape.php on line 39`

**To Reproduce**
1. Create and installation with two journals
2. Add a site logo
3. Go to the index and see the warning in log and the missing H1 in the source.

**What application are you using?**
 OJS/OPS master branch

**Comment by ajnyga** [comment]
Initial solution is to make `$site->getLocalizedPageHeaderTitle()` behave like `$context->getLocalizedPageHeaderTitle`, meaning that it would only return a string containing the Site name.

**Comment by NateWr** [comment]
Yes, that sounds like a solution for 3.2.1, where a lot of these accessibility changes are going. For 3.3. I'd like to refactor the logo/title logic in the header, so that we just check for a logo and use the title instead at both the site and journal level.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/5899

Tests:
https://github.com/pkp/ojs/pull/2762

**Comment by NateWr** [comment]
I've filed the more substantial changes to how we do the header at https://github.com/pkp/pkp-lib/issues/5917.
