### ISSUE TITLE
[OPS/OJS] Better placing of ORCID iD information (Contributor modal window)

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5790]
**Describe the problem you would like to solve**
The area reserved to show whether an author has associated or not their ORCID iD is currently sitting right next to the "Homepage URL" field. This is source of massive misinterpretation as authors tend to believe that field is reserved for the ORCID profile URL, even though that's not the case.

9 out of 10 authors add their ORCID profile URL on that field, thinking that this should suffice as far as informing their ORCID iD goes.

![image](https://user-images.githubusercontent.com/4059679/80397246-3ab59880-888c-11ea-94d7-3b807c8a7573.png)

**Describe the solution you'd like**
A better solution to dissociate these two things, which are two separate things but the interface is confusing the majority of authors. There is another area about ORCID at the bottom of the modal window of adding contributors.

![image](https://user-images.githubusercontent.com/4059679/80397528-a435a700-888c-11ea-92c0-001b4b874e5a.png)

Perhaps moving the ORCID iD portion that is currently beside the "Homepage URL" field to this ORCID area above would give more context to it and prevent authors from mistakenly adding their ORCID profile URL on the "Homepage URL".

**Who is asking for this feature?**
Journal Editors, Journal Managers, Preprint Server Managers, Preprint Server Moderators. A lot of energy is spent in asking authors to properly associate their ORCID IDs.

**Comment by alexxxmendonca** [comment]
@withanage please feel free to move this issue to the appropriate repository if you see it fit.

**Comment by alexxxmendonca** [comment]
@Devika008 I think this issue has been solved in face of the recent improvements of 3.5.

cc @asmecher 

I think we can close this issue.

**Comment by asmecher** [comment]
Thanks!
