### ISSUE TITLE
Vue js error after choosing a file for uploading

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#5791]
OJS 3.2.0-2.
After choosing a file for uploading though any file upload form, I'm receiving:
```
TypeError: Cannot read property ‘length’ of undefined
```
the message isn't informative as the file is minified.

To Reproduce
1. Go to website settings -> appearance -> setup
2. Click on Upload file, after picking up a file the message appears in the log. The same happens if pressing Remove button.

It's a minor bug that doesn't affect uploading.

**Comment by asmecher** [comment]
@Vitaliy-1, I wonder if this is the same issue as https://github.com/pkp/pkp-lib/issues/5690#issuecomment-617688409 addresses?

**Comment by Vitaliy-1** [comment]
Looks like the different one by the message:
```
TypeError: Cannot read property 'length' of undefined
    at o.setFieldErrors (build.js?v=3.2.0.2:8)
    at rt (build.js?v=3.2.0.2:14)
    at o.n (build.js?v=3.2.0.2:14)
    at rt (build.js?v=3.2.0.2:14)
    at o.On.e.$emit (build.js?v=3.2.0.2:14)
    at o.setErrors (build.js?v=3.2.0.2:8)
    at onAddFile (build.js?v=3.2.0.2:8)
    at rt (build.js?v=3.2.0.2:14)
    at o.n (build.js?v=3.2.0.2:14)
    at rt (build.js?v=3.2.0.2:14)
```
and it's associated with file upload forms, not those with text editing.

**Comment by asmecher** [comment]
The message is slightly different, but it should be quick enough to check by applying this patch: https://github.com/pkp/pkp-lib/pull/5771/commits/cb43d7d2a08407c86cb434113ffd7b91514ea467
Just to eliminate the possibility.

**Comment by NateWr** [comment]
```
at o.setFieldErrors (build.js?v=3.2.0.2:8)
```

That suggests to me that the server is returning an error response but there's no errors array. Open the Network tab in your browser's dev tools, then try an upload, and let me know what the response is. You may see two requests, an `OPTIONS` and then a `POST`.

**Comment by Vitaliy-1** [comment]
Yes, the patch doesn't resolve it.
Request URL: `http://ojs-3.2.0-2.test/index.php/psp/api/v1/temporaryFiles`
Response: `{"id":227}`
It's the only one.

**Comment by NateWr** [comment]
The response looks correct. Is the HTTP status 200 on the response?

**Comment by Vitaliy-1** [comment]
Yes. I also don't see anything suspicious in it.

**Comment by NateWr** [comment]
Ah, this is a `warning`, and you're only seeing it because you've built the JS package for development (`npm run dev`) rather than production (`npm run build`).

I don't think it's causing any problems, but it happens because we don't check if `errors` is an array before checking the length:

```
<field-error
	v-if="currentValue && errors.length"
	:id="describedByErrorId"
	:messages="errors"
/>
```

I think this should do it:

```
<field-error
	v-if="currentValue && !!errors && errors.length"
	:id="describedByErrorId"
	:messages="errors"
/>
```

That should be updated in every one of our fields.

**Comment by NateWr** [comment]
Fixed in https://github.com/pkp/ui-library/commit/14da7d4127d52f7d3dd03e11be534914d8c1adb6
