### ISSUE TITLE
OJS Missing DOIs when importing XML via CLI

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5794]
**Describe the bug**
When exporting submissions to import into another installation, DOIs metadata are missing on target DB.

**To Reproduce**
1. Export submissions via CLI from OJS A
2. Import submissions via CLI into OJS B
3. Login to OJS B, pick an imported submission 
4. Open metadata modal
5. Check Identifiers tab
4. See error (empty or no DOI)

**What application are you using?**
 OJS  version 3.1.2-1

**Additional information**
![image](https://user-images.githubusercontent.com/4992902/80423384-f509c780-88ad-11ea-884b-0f12ccd57fcf.png)

**Comment by asmecher** [comment]
@israelcefrin, is the DOI present in the exported XML?

**Comment by israelcefrin** [comment]
Hi @asmecher it is not. At least I've searched for it and can't find it.

**Comment by asmecher** [comment]
:+1: That helps, thanks. @defstat, could you put this on your list? I'd suggest coding it against 3.2.x (i.e. the `stable-3_2_0` branch) and back-porting it to 3.1.2 only if that's more or less trivial. Unless the hosting team needs it for `stable-3_1_2`, that is.

**Comment by israelcefrin** [comment]
@asmecher I've reviewed the original XML and it has the DOI recorded, however when I've imported it the resulting submission was missing the DOI metadata info.  I've sent the file to @defstat for checking.

**Comment by defstat** [comment]
Hi @asmecher.. The v3.2 does not seem to have that problem - I will check the 3.1.2 branch. @israelcefrin when the import takes place, is the DOI plugin enabled?

**Comment by defstat** [comment]
@israelcefrin I confirm that the DOIs are exported but they are not imported unless the target journal has the DOI plugin enabled. Could that be the issue?

@asmecher That is true for v3.1.2 and v3.2.

**Comment by israelcefrin** [comment]
@defstat it is likely the DOI plugin was not enabled on the target installation.  I will add it as a note for future migrations. Tks!

**Comment by defstat** [comment]
@asmecher @israelcefrin should I close that

**Comment by israelcefrin** [comment]
No objection from me.

**Comment by asmecher** [comment]
Thanks, @defstat!
