### ISSUE TITLE
Duplicate key value violates unique constraint in citations on upgrade with PostgreSQL

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5795]
From https://github.com/pkp/pkp-lib/issues/5626#issuecomment-611946149:
> I am trying to upgrade from version 3.1.1-4 to 3.2.0. I am getting
>
> ERROR: Upgrade failes: DB: ERROR: duplicate key value violates unique constraint "citations_publication_seq" DETAIL: Key (publication_id, seq)=(xx, yy) already exists.
>
> I can not apply pkp/ojs@47ea8db because I am using PostgreSQL.

This is a continuation of https://github.com/pkp/pkp-lib/issues/5626, but for PostgreSQL users (I had thought that PostgreSQL performed atomic batch updates, but it looks like not).

**Comment by asmecher** [comment]
Proposed PR: https://github.com/pkp/ojs/pull/2722

@adrianojam and @jpcv222, I don't have a PostgreSQL setup at the moment, but believe this should fix the issue -- your confirmation would be very helpful in getting this into the next release!

**Comment by jpcv222** [comment]
@asmecher and @adrianojam, the patch proposed in https://github.com/pkp/ojs/pull/2722/commits/bbc7686ac330a28c8e8715f2264ce62a47d2a03b fix the issue on upgrade with PostgreSQL setup. Thanks!

**Comment by asmecher** [comment]
Thanks for the confirmation, @jpcv222! I've committed the patch and cherry-picked into the `stable-3_2_0` branch for release in OJS 3.2.0-3 (hopefully this week).
