### ISSUE TITLE
Metadata sections in submission form

### ISSUE THREAD

**Issue by mhvezina** [pkp/pkp-lib#5796]
Context : OJS 3.1.2-4 [_also tested with the 3.2.x OJS demo test drive : same issues_]

Regarding metadata sections in submission form:

1) Even when no metadata fields are specified/activated in the journal's configuration, the heading (“Submission Metadata”) and info (“These specification are …”) for this section appear. Maybe test first if no-null values for these fields exists before displaying the heading&info?

2) It looks like the ‘submission.submit.metadataForm.tip’ string (which explains to the user the not-so-intuitive way to enter multiple keywords, that is to press ‘enter’ after each term) is not displayed when only keywords metadata field is activated for a journal.

![image](https://user-images.githubusercontent.com/10760472/80425038-e53fb280-88b0-11ea-9ff9-bc698bb6a00f.png)

Actually this tip is displayed only when the language metadata field is activated (but would also be relevant for other fields such as subjects, disciplines, keywords, etc.). 

![image](https://user-images.githubusercontent.com/10760472/80425432-9a726a80-88b1-11ea-9ced-afcc114a53ae.png)

Could it be displayed for the whole section?

[See forum entry [here](https://forum.pkp.sfu.ca/t/metadata-sections-in-submission-form/60126)]

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**
[pkp-lib]: #5877
[OJS]: pkp/ojs#2753
[OMP]: pkp/omp#816
[OPS]: pkp/ops#27

**Comment by asmecher** [comment]
@defstat, looks good to me -- please merge, and cherry-pick back to `stable-3_1_2`!

**Comment by defstat** [comment]
@asmecher everything merged except the OPS PR (for which I don't have permission to merge) (tagging @ajnyga for that merge)

**Comment by defstat** [comment]
For reference:

**PRs - 3.1.2**
[pkp-lib]: #5882
[OJS]: pkp/ojs#2754
[OMP]: pkp/omp#817

**Comment by NateWr** [comment]
@asmecher just double checking but did you mean to backport to `stable-3_2_0`? Does it still need to be cherry-picked over?

**Comment by asmecher** [comment]
Good catch, @NateWr -- yes, this should be in 3.1.2 (since it's back-ported already), 3.2.0 *and* `master`. @defstat, could you cherry-pick into `stable-3_2_0` (and merge wherever needed)?

**Comment by defstat** [comment]
For reference:

**PRs - 3.2.0**
[pkp-lib]: #5902
[OJS]: pkp/ojs#2764
[OMP]: pkp/omp#819

**Comment by NateWr** [comment]
Thanks! Closing.
