### ISSUE TITLE
Make it possible to move a submission back into review

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5798]
**Describe the problem you would like to solve**
If an editor accepts a submission in the review stage, then changes their decision to request revisions, the submission remains in the copyediting stage and indicates on the workflow page that the submission was accepted.

When an editor reconsiders a decision in the review stage, the submission should be moved back into review and the UI should reflect that.

**Describe the solution you'd like**
When a submission is accepted or declined in the submission and review stages, the editorial decision options should be removed. Instead, it should have an option to "reopen stage", which will reset the active stage ID and make other actions available.

This will make it clearer to the editor what they're doing when they override a previous action and make it easier for us to present an appropriate UI for that workflow stage.

**Who is asking for this feature?**
See the [report on the forum](https://forum.pkp.sfu.ca/t/ojs-3-2-change-of-editorial-decision-is-handled-inconsistently-or-at-least-confusing-by-ojs/60037) with screenshots describing the problem.

**Additional Info**
> In the short run, confusion could be reduced, IMO, if the indication of the editorial decision... would be updated after that decision has been changed. [Source](https://forum.pkp.sfu.ca/t/ojs-3-2-change-of-editorial-decision-is-handled-inconsistently-or-at-least-confusing-by-ojs/60037)

**Comment by asmecher** [comment]
@NateWr, did this get mooted by your editorial decision changes?

**Comment by NateWr** [comment]
Yes, this is sorted out with @touhidurabir's work on moving back to the review stage.
