### ISSUE TITLE
Recommend by Author Plugin duplicates entries

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#5801]
OJS 3.2.0-2. 
See related forum post: https://forum.pkp.sfu.ca/t/immersion-theme-article-by-the-same-author-plugin-repeats-the-article-itself/60120
I was able to reproduce it - screenshot (bottom of the page)
![duplicate](https://user-images.githubusercontent.com/20665587/80479135-40c47b80-8957-11ea-9249-a6106c6c1615.png)

There 2 problems:
1. Entries can be duplicated if share the same authors.
2. The current article isn't excluded 
Think, it can be fixed by modifying [this line](https://github.com/pkp/ojs/blob/32c01dfa5775d9011e3aaa3cdf74c63410ddf7aa/plugins/generic/recommendByAuthor/RecommendByAuthorPlugin.inc.php#L87) to:
```
$foundArticles = array_unique(array_merge($foundArticles, $submissionIds));
```
Plus skipping or excluding current publication id from the results, e.g., by a check [here](https://github.com/pkp/ojs/blob/32c01dfa5775d9011e3aaa3cdf74c63410ddf7aa/plugins/generic/recommendByAuthor/RecommendByAuthorPlugin.inc.php#L81).

**Comment by Vitaliy-1** [comment]
PR to master: https://github.com/pkp/ojs/pull/2745

**Comment by NateWr** [comment]
Looks like this got merged. Can we close this?

**Comment by asmecher** [comment]
Yup!
