### ISSUE TITLE
OJS 3.2 Error exporting issues to XML

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5808]
**Describe the bug**
Exporting issues is returning an error via GUI admin or CLI.

**To Reproduce**
1. Go to Dashboard > Tools > Import /Export
2. Click on **Native XML Plugin** > Export Issues (tab)
3. Select an issue and click export

OR
1. Via CLI go to web folder
2. Run `php tools/importExport.php NativeImportExportPlugin export ...`
3. See the error

**What application are you using?**
 OJS version 3.20-1

**Additional information**
See the log:

```
Validation errors:
Element '{http://pkp.sfu.ca}issue': Missing child element(s). Expected is ( {http://pkp.sfu.ca}articles ).
Invalid XML:
<?xml version="1.0"?>
<issue xmlns="http://pkp.sfu.ca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" published="1" current="0" access_status="1" url_path="" xsi:schemaLocation="http://pkp.sfu.ca native.xsd">
  <id type="internal" advice="ignore">37</id>
  <issue_identification>
    <volume>1</volume>
    <number>1</number>
    <year>2018</year>
  </issue_identification>
  <date_published>2018-10-30</date_published>
  <last_modified>2018-10-30</last_modified>
  <sections>
    <section ref="ARED" seq="2" editor_restricted="0" meta_indexed="1" meta_reviewed="1" abstracts_not_required="1" hide_title="0" hide_author="0" abstract_word_count="0">
      <id type="internal" advice="ignore">51</id>
      <abbrev locale="en_US">ARED</abbrev>
      <policy locale="en_US">&lt;p&gt;Proin volutpat rutrum iaculis. Ut aliquet lectus et diam laoreet pulvinar. Phasellus augue massa, facilisis tincidunt auctor et, iaculis a nunc.&amp;nbsp;&lt;/p&gt;</policy>
      <title locale="en_US">Art/Research Editorial</title>
    </section>
    <section ref="ARTM" seq="3" editor_restricted="0" meta_indexed="1" meta_reviewed="1" abstracts_not_required="0" hide_title="0" hide_author="0" abstract_word_count="0">
      <id type="internal" advice="ignore">52</id>
      <abbrev locale="en_US">ARTM</abbrev>
      <title locale="en_US">Art/Research Theoretical Musings</title>
    </section>
    <section ref="ARIA" seq="4" editor_restricted="0" meta_indexed="1" meta_reviewed="1" abstracts_not_required="0" hide_title="0" hide_author="0" abstract_word_count="0">
      <id type="internal" advice="ignore">53</id>
      <abbrev locale="en_US">ARIA</abbrev>
      <title locale="en_US">Art/Research In Action</title>
    </section>
  </sections>
  <issue_galleys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pkp.sfu.ca native.xsd"/>
</issue>

<h1>Could not convert selected objects.</h1>ojs2: Could not convert selected objects.
```

**Comment by asmecher** [comment]
@defstat, could you take a look at this?

**Comment by defstat** [comment]
@israelcefrin I may need more data for that. I can't reproduce the issue on a clean OJS 3.2 installation. The exported file lacks a `<articles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pkp.sfu.ca native.xsd"/>` element, but the code seems to add that when using the 3.2.0-1 stable branch (or the master branch)

Is that an export from a journal that was upgraded from a previous version?

**Comment by israelcefrin** [comment]
@defstat yes, it was upgraded to OJS 3.2 from OJS 3.1.2. It is from our Demo install actually.

**Comment by defstat** [comment]
@israelcefrin do you have access to the installation's DB? is yes could you share the result of 
`SELECT * FROM filter_groups where symbolic like '%native-xml%'`

**Comment by defstat** [comment]
I think that the issue is that after upgrading to a version prior to 3.2.1, the `filter_groups` still have the `Article` class defined for the `article=>native-xml` filter, instead of the `Submission` class. 

That is resolved by `https://github.com/pkp/ojs/blob/master/dbscripts/xml/upgrade/3.2.1_update.xml`

**Comment by israelcefrin** [comment]
@defstat this is the result from running 
`SELECT * FROM filter_groups where symbolic like '%native-xml%'
`

![image](https://user-images.githubusercontent.com/4992902/80833029-c0528480-8bbb-11ea-8d61-8f5f28acd1b5.png)

Should I exclude or edit something?

**Comment by israelcefrin** [comment]
@defstat I've got to sort it out. I've replaced on DB and now it is working. Tks!
