### ISSUE TITLE
Tasks list drop-down not showing up in Arabic on OJS 3.2.0.2

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#5811]
**Describe the bug**
Tasks list drop-down does not show up when the interface is set to Arabic. It works in English on the same journal. The instance is on OJS 3.2.0.2

**To Reproduce**
Set the language to Arabic and click on Tasks (assuming the task list has something in it). The drop-down does not expand:
![image](https://user-images.githubusercontent.com/45104797/80813608-5379c300-8b98-11ea-8b2e-8d2f583e3b55.png)

Change the language to English for comparison. The drop-down expands:
![image](https://user-images.githubusercontent.com/45104797/80813563-3ba23f00-8b98-11ea-87f7-253ef04f4a39.png)

**What application are you using?**
 OJS 3.2.0.2

**Additional information**
Reported by PKP|PS

**Comment by NateWr** [comment]
Thanks!

PRs:
https://github.com/pkp/pkp-lib/pull/5828
https://github.com/pkp/pkp-lib/pull/5827 (stable)

Tests:
https://github.com/pkp/ojs/pull/2735 (stable)

**Comment by NateWr** [comment]
Merged to `master` and `stable-3_2_0`.
