### ISSUE TITLE
Journal ordering no longer works

### ISSUE THREAD

**Issue by sssoz** [pkp/pkp-lib#5815]
# Describe the bug

In a multi-journal installation’s administration tab: hosted journal ordering doesn’t save changes in the order. Clicking on _Done_ reloads the page without registering the chosen journal order. Seen on the OJS demo site. 

---

# To Reproduce

1. Go to the _Administration_ section of a [multi-journal OJS installation](https://demo.publicknowledgeproject.org/ojs3/demo/index.php/index/admin/index).
2. Click _Order_
3. Change the order of journals 
4. Click _Done_
5. Changes are not saved; no Javascript errors are shown either. 

---

# What application are you using?

On MacOS, Chrome & Firefox latest versions, using OJS 3.2.0.0.

---

# Additional information

![Journal ordering](https://i.gyazo.com/82a557689ae34a629998ab43f61d416f.gif)

**Comment by defstat** [comment]
@sssoz does this problem continue to show-up? I am asking because I can't reproduce the issue not on `master` branch nor on `stable-3_2_0`. (clean installs both)

**Comment by sssoz** [comment]
@defstat Tried it just now, I’m still having the issue on the demo install, which is on 3.2.0.0.  Here’s the exact link to it: https://demo.publicknowledgeproject.org/ojs3/demo/index.php/index/admin/contexts

**Comment by defstat** [comment]
I think that this is addressed here #5847
