### ISSUE TITLE
[OMP] All Categories get selected/unselected when creating new series

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#5817]
When trying to add a new series in **OMP 3.2.0.2** (on Test Drive site), when trying to select a category for the series all available series are being selected. When unselecting all are unselected.

To Reproduce
1. Setting> Press > Series
2. Add Series
3. Select 1 category, all get selected. Unselect, all get unselected.

![image](https://user-images.githubusercontent.com/50342731/81016177-cee7a880-8e14-11ea-8d62-15d0705457c3.png)

**Additional information**
However, once the series is created with all the categories selected. You can edit the series and unselect the irrelevant categories without issue.

**Comment by NateWr** [comment]
Thanks for the report @pmangahis! I've found a fix for this and will merge once the tests pass.

PRs:
https://github.com/pkp/pkp-lib/pull/5824
https://github.com/pkp/pkp-lib/pull/5825 (stable)
https://github.com/pkp/omp/pull/806
https://github.com/pkp/omp/pull/807 (stable)

**Comment by NateWr** [comment]
Merged to `master` and `stable-3_2_0`.
