### ISSUE TITLE
[OJS/OPS/OMP] "submission.metadataDescription" translation key needs to be different for each application

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5818]
**Describe the bug**
The translation key `submission.metadataDescription` needs to be different for each application.

Here's what the translation key shows for OJS:
These specifications are based on the Dublin Core metadata set, an international standard used to describe **journal** content.

Here's what the translation key shows for OPS:
These specifications are based on the Dublin Core metadata set, an international standard used to describe **server** content.

Here's what the translation key shows for OMP:
(I don't have OMP installed but I assume it has something to do with ONIX)

For OJS it's ok, but I don't think Dublin Core metadata set is a standard for Preprints, in which case this text needs to be changed not only from **journal** to **server**.

**Comment by asmecher** [comment]
Would it be clearer if the OPS text was changed from...
```
These specifications are based on the Dublin Core metadata set, an international standard used to describe server content.
```
...to...
```
These specifications are based on the Dublin Core metadata set, an international standard used to describe content.
```

**Comment by alexxxmendonca** [comment]
Hi @asmecher 
For now I think so!

There is ongoing conversation about metadata best practices for preprints. ASAPBio is coming up with a minimun metadata requirements list but it's not public yet. Once that is out, we should definitely take a look at it.

**Comment by asmecher** [comment]
@alexxxmendonca, I've made that change in Weblate, thanks.
