### ISSUE TITLE
Cannot hide TinyMCE toolbar when adding textarea directly to a template

### ISSUE THREAD

**Issue by salmanm2003** [pkp/pkp-lib#5820]
Hi @asmecher ,

I have created a plugin that adds textarea field to submission metadata area.
I was trying to hide the texteditor _toobar_ to prevent any extra format except the new lines, but sounds like there is no option for that when the field is added directly to the template.
I have checked _TinyMCE_ options in __smartyFBVTextArea()_ function but nothing there related to _toolbar_ param.
Would be great to have the ability of controlling the toolbar items or hiding it completely.
I am using _OJS 3.2.0-3_ and the template code as below: 
`{fbvElement type="textarea" height=$fbvStyles.height.SHORT multilingual=true name="" id="" value=$value readonly=$readOnly }`

Thanks 
Salman

**Comment by asmecher** [comment]
@salmanm2003, I'd suggest looking into adding some plugin-specific JS to override the current TinyMCE behaviour -- it would probably only be a few lines of code, and wouldn't require changes to the core app.

**Comment by salmanm2003** [comment]
Perfect - Thanks @asmecher
