### ISSUE TITLE
Fix locale it_IT (locale/it_IT/user.po)

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#5826]
**Describe the bug**
In the stable  branch 3.2.0 on https://github.com/pkp/pkp-lib/blob/3cbc385fc8ebd07f6117810fe72fc7abfa8abf5a/locale/it_IT/user.po#L432 and in the master on https://github.com/pkp/pkp-lib/blob/e3d03713ecb558c1dad93dacbbe7e4d3bf87c72d/locale/it_IT/user.po#L432
the first word "Yes, dò il mio consenso ..." should be replaced with "Sì, dò il mio consenso ..."

**What application are you using?**
 OJS 3.2.0-3

**Comment by asmecher** [comment]
@eniocarboni, could you make this change through Weblate? See https://pkp.sfu.ca/2020/01/22/introducing-weblate-a-new-path-for-ojs-omp-translations/ for details.

**Comment by eniocarboni** [comment]
Ok done as suggestion.

**Comment by asmecher** [comment]
Accepted, thanks!
