### ISSUE TITLE
Can't edit user details without changing the password

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5829]
**Describe the bug**
When editing a user's details, the form returns an error message:

> The password must be at least 6 characters.

This happens even if you leave the field blank, in which case it should not make any changes. Because of this, it is not possible to edit a user without changing their password.

This has not been confirmed on latest `master` but needs to be investigated.

**To Reproduce**
1. Go to Users & Roles > Users > Edit a user.
2. Click save.
3. See error

**What application are you using?**
3.2

**Comment by asmecher** [comment]
@NateWr, is this a duplicate of https://github.com/pkp/pkp-lib/issues/5666?

**Comment by NateWr** [comment]
Yes!
