### ISSUE TITLE
User profile API form is broken

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5831]
**Describe the bug**
The user profile API form does not work; changes do not stick.

**What application are you using?**
OJS 3.2.0-3

**Comment by asmecher** [comment]
There were several problems here:
- The call to `parent::execute` in `APIProfileForm` clobbered the newly-saved user settings (not stored in the DataObject) via `UserDAO::updateObject`
- The form, when a new API key is generated, does not immediately display it; the form must be reloaded to see the new key

**Comment by NateWr** [comment]
@asmecher can this one be closed?

**Comment by asmecher** [comment]
Yes, thanks!
