### ISSUE TITLE
Article statistics aren't being generated?

### ISSUE THREAD

**Issue by kallewesterling** [pkp/pkp-lib#5832]
We are trying to keep track of our views on the articles on the website but the Statistics page on the admin interface display 0 article views ever since January 2019 despite log files on our FTP server showing other information.

**To Reproduce**
1. Log in to admin interface
2. Click on "Statistics" > "Articles"
3. See the following information in the admin interface:
<img width="1031" alt="admin-interface" src="https://user-images.githubusercontent.com/7298727/81232575-24fa4e80-8fc3-11ea-95ae-f63d70236c17.png">

4. Log in to FTP site
5. Navigate to `files` > `usageStats` > `reject`
6. See the following information in one of the `.log` files:
<img width="2094" alt="log-file" src="https://user-images.githubusercontent.com/7298727/81232725-62f77280-8fc3-11ea-96c1-8dedfc0d2127.png">

**What application are you using?**
 OJS or OMP version 3.1.2.4

**Comment by ctgraham** [comment]
Can you share the message from your scheduledTaskLogs file that corresponds to this rejected log file?  It is probably "Usagestatisticsfileloadertask-*-20200419.log"

**Comment by kallewesterling** [comment]
There are no such files available on our server. Perhaps that's where the problem lies...?

**Comment by ctgraham** [comment]
These should exist in a "scheduledTaskLogs" folder parallel to the "usageStats" folder where you found the "reject" folder containing the logs.  If this folder does not exist, create it and ensure it is writeable by your web process (or by your cron process, if you use a different user to run cron).  The message in the corresponding file(s) within scheduledTaskLogs should indicate why the usagesStats file was moved to the reject folder.

**Comment by kallewesterling** [comment]
Nevermind, I found it. I don't know why but it wasn't showing up. Now, after restarting the Acron plugin (which I found in the manual as an instruction), it shows.

Here are the contents of `Usagestatisticsfileloadertask-5e9c7698653a5-20200419.log`:

> [2020-04-19 18:04:40] http://www.lambdanordica.org
> [2020-04-19 18:04:40] [Notice] Task process started.
> [2020-04-19 18:04:48] [Error] Cannot load record: submission file is not associated with a representation object.
> [2020-04-19 18:04:48] [Notice] Task process stopped.

**Comment by kallewesterling** [comment]
How can I find which "submission file" is causing this error...?

**Comment by ctgraham** [comment]
Yeah, that error is pretty worthless.  If you are OK with modifying the PHP code, you could output the `$submissionId` and `$assocId` in the error message here:
https://github.com/pkp/pkp-lib/blob/3bd3773e6b9414a317dc66de32c70e791936be02/classes/statistics/PKPMetricsDAO.inc.php#L365

Otherwise, if you can run a database query, we can try to come up with some SQL which will identify the missing data.

**Comment by kallewesterling** [comment]
Able to do either! I suspect that it's more than one, however, so perhaps an SQL query might be a better solution...

**Comment by kallewesterling** [comment]
Any ideas on how I can try to resolve this?

**Comment by ctgraham** [comment]
Sorry, hijacked a bit here by local emergencies.  This forum [post](https://forum.pkp.sfu.ca/t/usage-statistics-file-loader-task-5904933971a42-error/30678/12?u=ctgraham) suggests the query would be:
> DB table submission_files where file_stage = 10 and assoc_type != 521

**Comment by kallewesterling** [comment]
I was just able to run the command, and it returns zero results...

**Comment by kallewesterling** [comment]
In fact, the `submission_files` table does not look like it's correct at all.. I was not involved in the OJS upgrade to version 3, and I wonder if something went wrong in the transfer of the database to the upgraded version..?

![image](https://user-images.githubusercontent.com/7298727/82831802-6c1f8500-9e87-11ea-9d41-eb75fa3db084.png)

What's weird to me, is that the website is fully functioning.. So there's some kind of connection between the database's file references, and the ones on the server, so they're accessible through the front-end...

**Comment by ctgraham** [comment]
I think your `submission_files` table might be fine.  The `assoc_id` may be null.  It is a dynamic foreign key dependent on the `assoc_type`.  This allows the foreign key of `assoc_id` to point to different tables, perhaps representing articles, issues, galleys, etc.  An `assoc_type` of "521" indicates a 'ASSOC_TYPE_REPRESENTATION' (c.f. https://github.com/pkp/pkp-lib/blob/db87554563595bbd65fe44788135bf9457d91701/classes/core/PKPApplication.inc.php#L34).

In OJS, I think this is a Galley, so the associated table would probably be `submission_galleys`.

The file stage of 10 is 'SUBMISSION_FILE_PROOF' (c.f. https://github.com/pkp/pkp-lib/blob/db87554563595bbd65fe44788135bf9457d91701/classes/submission/SubmissionFile.inc.php#L29).

So, the query Bozana suggests seems to be asking what submission files are proofs, but not representations.  I'm not familiar enough with this portion of the workflow to know specifically what this is describing.

Can you share the full `submission_file` row data for `file_id` "25"?

**Comment by kallewesterling** [comment]
Here's the row data for that `file_id`:

![image](https://user-images.githubusercontent.com/7298727/82960987-07991e80-9f8a-11ea-9bf2-aa246eaf8d62.png)

**Comment by ctgraham** [comment]
Does your Exception line now read:
```
throw new Exception('Cannot load record: submission file '.$submissionId.') is not associated ('.$assocId.') with a representation object.');
```
?

This would mean that the input to this function is to lookup `ASSOC_TYPE_SUBMISSION_FILE` id "25" or `ASSOC_TYPE_SUBMISSION_FILE_COUNTER_OTHER` id "25", and the result is Submission id "25".  But, when we look at Submission File id 25, there is no `assoc_type`.  It is null.

What do the production galleys look like for Submission #25 in your editorial workflow?  Does everything look normal there?

**Comment by kallewesterling** [comment]
When I login to the admin interface and look at the "back-end front-end" this is what shows up:

![image](https://user-images.githubusercontent.com/7298727/83053327-8f306d00-a01e-11ea-9d88-824c232e98fc.png)

Under "Review," "Copyediting," and "Production," all the information available is: `Stage not initiated.`

This does not look normal, I guess... Does it look like something got lost in the database in an upgrade? How can I rectify that?

**Comment by ctgraham** [comment]
So, from OJS's editorial perspective, this article has not been published.  It is fine to not have used the initial workflow stages, if the Production stage is active.  Can you confirm whether this article appears as published in the reader front-end?

Is seems like your usage statistics log is referencing access to this article, but with inconsistent (or unset?) publication status, the process is failing when the log line is translated to a metric.

I suspect the published galley access would look something like:
base_url + /article/view/25/25

Does this appear in your failed usage statistics log?  Is the article currently publicly accessible?

**Comment by kallewesterling** [comment]
Right—I sort of gleaned that from the database... But yes, to all your questions:
- It [appears in the front-end](http://www.lambdanordica.org/index.php/lambdanordica/article/view/25) as accessible.
- My visit also registers in the usage statistics log (see image below)

![image](https://user-images.githubusercontent.com/7298727/83071506-38855c00-a03b-11ea-8221-f56c7d6a9d4e.png)

**Comment by kallewesterling** [comment]
So it seems to me that the `file_stage` and `assoc_type` just need to be fixed for each of these galley files, to be `file_stage`=`18` and `assoc_type`=`520`. Do you think I could make those manual changes to the database..?

**Comment by kallewesterling** [comment]
Quick update on that, to clarify: The galleys seem to exist in the `submission_galleys` for all of these wayward `submission_files`... Here's a screenshot:

![image](https://user-images.githubusercontent.com/7298727/83072065-1dffb280-a03c-11ea-9809-50c42bab3fcb.png)

**Comment by ctgraham** [comment]
If using an `assoc_type`, the `assoc_id` will be required.  This will presumably be your `submission_galley.galley_id`.

If making manual changes to the database, be sure to perform a full database backup beforehand, and test in a development copy of the installation when possible.

I don't think the `file_stage` of 'SUBMISSION_FILE_QUERY' (18) sounds right.

I would submit a new article with a new production galley via the QuickSubmit plugin (or run one all the way through the workflow) and compare the `file_stage` and presence (or absence) of an `assoc_id` and `assoc_type` pair for that `submission_file`.

Someone like @NateWr or @asmecher might be more directly familiar with the expectations for the stage and association of a production galley submission file.  But folks at PKP are also super-busy right now preparing the 3.2.1 release.

Out of curiosity, how did you import these old articles from before OJS into OJS?  Were they all carryovers from the 2.x upgrade as well?

**Comment by kallewesterling** [comment]
It's a good question. I was not in charge of the import of the articles so I couldn't tell you...

I will try to set up a dev environment and transfer the whole thing over there and see how it works out.

**Comment by NateWr** [comment]
I just took a quick look at my local database to see what the connection is. For each galley I have a record in the `submission_galleys` table that looks like this:

```
+-----------+---------------+---------+
| galley_id | submission_id | file_id |
+-----------+---------------+---------+
|         2 |            17 |      24 |
```

The `submission_id` and `file_id` corresponds to a record in the `submission_files` table like this:

```
+---------+---------------+------------+----------+
| file_id | submission_id | assoc_type | assoc_id |
+---------+---------------+------------+----------+
|      24 |            17 |        521 |        2 |
```

The only records in the `submission_files` table which include `assoc_type`/`assoc_id` values are `521` (galleys) and `517` (issue galleys -- _I think_).

**Comment by kallewesterling** [comment]
Thank you so much @NateWr, this is exactly what I was trying to find in the documentation! I was surprised to not be able to find a database schema.

**Comment by kallewesterling** [comment]
Here's what I ended up doing, so far:

```php
$query1 = "SELECT * FROM `submission_files` WHERE `file_stage`=10 AND `assoc_id` IS NULL AND `assoc_type` IS NULL";
if ($result = $mysqli -> query($query1)) {
  while ($row = $result -> fetch_assoc()) {
    $submission_files_file_id = $row["file_id"];
    $submission_id = $row["submission_id"];
    $query2 = "SELECT * FROM `submissions` WHERE `submission_id`=" . $submission_id;
    if ($result2 = $mysqli -> query($query2)) {
      while ($row2 = $result2 -> fetch_assoc()) {
        $query3 = "SELECT * FROM `submission_galleys` WHERE `file_id`=" . $submission_files_file_id;
        if ($result3 = $mysqli -> query($query3)) {
          while ($row3 = $result3 -> fetch_assoc()) {
            $galley_id = $row3["galley_id"];
            $queries_back = array(
              "UPDATE `submission_files` SET `uploader_user_id` = 10 WHERE `file_id`=" . $submission_files_file_id . ";",
              "UPDATE `submission_files` SET `assoc_type` = 521 WHERE `file_id`=" . $submission_files_file_id . ";",
              "UPDATE `submission_files` SET `assoc_id` = " . $galley_id . " WHERE `file_id`=" . $submission_files_file_id . ";",
              "UPDATE `submissions` SET `status` = 3 WHERE `submission_id`=" . $submission_id . ";",
              "UPDATE `submissions` SET `stage_id` = 5 WHERE `submission_id`=" . $submission_id . ";",
            );
            foreach ($queries_back as $query) {
              print($query . "<br />");
            }
          }
        }
      }
    }
  }
  // Free result set
  $result -> free_result();
}

$mysqli -> close();
```

Not the prettiest code—sure! But it got the job done. I got it to spit out individual MySQL queries for all of the faulty rows in the database, tested it on a dev server that I had set up, and didn't notice any problems. I then made a backup of the production server, and implemented the changes there.

Everything seems to be running fine so far. But I have yet to see if it resolves our issues with the statistics.

In the process, I found that there were a couple of rows in our `submissions` table that didn't have any `galleys` attached to them (or any other files for that matter) so that's next up for me to tackle.

I'll report back as soon as I know more.

**Comment by NateWr** [comment]
Great, glad you were able to sort that out. Ill close this for now but if it doesn't resolve your issue feel free to post again and we can open it back up.
