### ISSUE TITLE
[OMP] Order catalog by series position leads to database error

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5833]
**Describe the bug**
From https://forum.pkp.sfu.ca/t/3-2-0-3-3-2-0-2-catalog-listing-error/60282/3:
When the catalog is configured to display by series position, viewing the catalog causes a fatal error.

**To Reproduce**
1. In Setup, configure the catalog to sort by series position.
2. View the catalog.
3. Encounter a fatal error.

**What application are you using?**
 OJS or OMP version 3.2.0

**Additional information**
This is caused by the SubmissionQueryBuilder still being implemented to expect `series_position` in the `submissions` table. It has been moved to the `publications` table.

**Comment by NateWr** [comment]
The following diff does fix the fatal error. However, I found that books in the catalog were still not sorted correctly. So this issue is going to take a little bit more work to get sort-by-series working again.

I'm putting this aside for the moment.

```diff
diff --git a/classes/services/queryBuilders/SubmissionQueryBuilder.inc.php b/classes/services/queryBuilders/SubmissionQueryBuilder.inc.php
index b06004135..096ddca31 100644
--- a/classes/services/queryBuilders/SubmissionQueryBuilder.inc.php
+++ b/classes/services/queryBuilders/SubmissionQueryBuilder.inc.php
@@ -55,7 +55,7 @@ class SubmissionQueryBuilder extends \PKP\Services\QueryBuilders\PKPSubmissionQu
 		import('classes.submission.SubmissionDAO');
 		switch ($column) {
 			case ORDERBY_SERIES_POSITION:
-				$this->orderColumn = 's.series_position';
+				$this->orderColumn = 'po.series_position';
 				break;
 			default:
 				return parent::orderBy($column, $direction);
@@ -88,6 +88,13 @@ class SubmissionQueryBuilder extends \PKP\Services\QueryBuilders\PKPSubmissionQu
 			$q->whereIn('publication_s.series_id', $this->seriesIds);
 		}
 
+		// order by series position
+		if ($this->orderColumn === 'po.series_position') {
+			$this->columns[] = 'po.series_position';
+			$q->leftJoin('publications as po', 's.current_publication_id', '=', 'po.publication_id');
+			$q->groupBy('po.series_position');
+		}
+
 		if (!empty($this->orderByFeaturedSeq)) {
 			if (!empty($this->seriesIds)) {
 				$assocType = ASSOC_TYPE_SERIES;
```

**Comment by defstat** [comment]
@asmecher @NateWr 

**PR**
[OMP]: pkp/omp#820

**Comment by defstat** [comment]
@asmecher everything merged

**Comment by asmecher** [comment]
Thanks, @defstat (& @NateWr)!
