### ISSUE TITLE
Investigate behavior of review assignments in "My Assigned" queue

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#584]
These OTOH should move into the archive after the reviewer has completed their work. However, they seem to be staying in Assigned -- presumably until the submission is published? Investigate.

**Comment by beghelli** [comment]
After the review is sent, the submission is still assigned. After archived, the submission is gone from the assigned list, but it doesn't appear on the archived one.

If we change to the archived list when the submission isn't really archived, there will be room for confusion. The grid is called "Archived Submissions" anyway.

I think we can add an extra grid column with a checkbox for the completed ones. And we move to archived when it is really an archived submission.

**Comment by beghelli** [comment]
After discussing with Alec, decided to go on with the first option. 

For reviewers, the archived list will show the submissions that they already worked on (sent the review).

**Comment by beghelli** [comment]
Fixed also a couple of problems (data loading and filter) with the general archived submissions list.
