### ISSUE TITLE
Keywords go missing after submititng the metadata form

### ISSUE THREAD

**Issue by netsensei** [pkp/pkp-lib#5842]
**Describe the bug**

Editors can add metadata to submissions in the editorial workflow through the 'Submission and Publication metadata' pop-up form. When enabled, the 'additional refinements' field group contains a 'keywords' field.

When an editor submits the form with keywords, the keywords are missing when the form reloads. The field is just empty.

**To Reproduce**

1. Ensure the "keywords" field is enabled for the "additional refinements" section of the journal.
2. A submission has entered the editorial workflow.
2. Click on "metadata"
3. Fill out the required fields for the form.
4. Enter a keyword (and optionally press tab to turn it into a proper tag)
5. Click on the "save" button.
6. The form gets processed and a popup "Submission metdata saved" appears.
7. The form reloads again (not the entire page!!)
8. Scroll down the form. Notice how other fields are correctly saved, but the "keywords" field is empty.

**What application are you using?**

OJS 3.1.2.1

I'm running  OJS on this stack:

* Centos 7
* postgresql-9.2.24-2.el7_7.x86_64
* php-7.3.15-1.el7.remi.x86_64
* httpd-2.4.6-90.el7.centos.x86_64 (apache)

**Additional information**

I have done a deep dive into the pkp/pkp-lib code and what happens at the database backend. 

[PKPSubmissionMetadataFormImplementation](https://github.com/pkp/pkp-lib/blob/ojs-3_1_2-1/classes/submission/PKPSubmissionMetadataFormImplementation.inc.php) does the heavy loading of fetching and saving data from/to the daabase and passing it onto the form.

Saving data works fine. I can see that the keywords are correctly saved in the `controlled_vocab_entries`, `controlled_vocab_entry_settings` and `controlled_vocabs` tables. I see any and all keywords I submitted into those tables, and I can see the submissionId in `controlled_vocabs` in the `assoc_id` column. So far, so good.

The problem seems to appear when fetching data from the database. This happens when the form is loaded and displayed.

An instance of [SubmissionKeywordDAO](https://github.com/pkp/pkp-lib/blob/ojs-3_1_2-1/classes/submission/SubmissionKeywordDAO.inc.php) is instantiated and the [getKeywords()](https://github.com/pkp/pkp-lib/blob/b264ffb0a0538f70e9f455d41c087738428200fd/classes/submission/SubmissionKeywordDAO.inc.php#L47-L64) function gets called.

It contains these three lines:

```php
$keywords = $this->build($submissionId);
$submissionKeywordEntryDao = DAORegistry::getDAO('SubmissionKeywordEntryDAO');
$submissionKeywords = $submissionKeywordEntryDao->getByControlledVocabId($keywords->getId());
```
The [build()](https://github.com/pkp/pkp-lib/blob/b264ffb0a0538f70e9f455d41c087738428200fd/classes/submission/SubmissionKeywordDAO.inc.php#L28-L31) function calls the [ControlledVocabDAO::_build()](https://github.com/pkp/pkp-lib/blob/b264ffb0a0538f70e9f455d41c087738428200fd/classes/controlledVocab/ControlledVocabDAO.inc.php#L54-L67) function which has these lines:

```php
...
$id = $this->insertObject($controlledVocab, false);
if ($id !== null) return $controlledVocab;
...
```

**Every time the "metadata" form is opened and rendered, these lines are executed. In my case, instead of just fetching the existing, previously inserted row from the `controlled_vocabs` table, it just creates a new row in the table that has absolutely no connection to any already submitted keywords whatsoever.**

The net result is that the `controlled_vocabs` table contains a lot of entries that don't have any connection to any existing data:

```
 controlled_vocab_id |     symbolic      | assoc_type | assoc_id 
---------------------+-------------------+------------+----------
             7353653 | submissionKeyword |    1048585 |    15971
             7353648 | submissionKeyword |    1048585 |    15971
             7353593 | submissionKeyword |    1048585 |    15971
             7353588 | submissionKeyword |    1048585 |    15971
             7353583 | submissionKeyword |    1048585 |    15971
             7353577 | submissionKeyword |    1048585 |    15971
             7353573 | submissionKeyword |    1048585 |    15971
             7353568 | submissionKeyword |    1048585 |    15971
             7353566 | submissionKeyword |    1048585 |    15971
             7353561 | submissionKeyword |    1048585 |    15971
             7353556 | submissionKeyword |    1048585 |    15971
cont'd for as many times as hit on the "metadata" link
```

Code comments state that ithe _build function either creates a new entry, or fetches already entered entries from the database. Which seems weird to me because the underlying `insertObject` and `DAO::update()` functions don't seem to do any checks whether an object already exists. It just executes the INSERT query verbatim without first checking whether the object exists separately.

The real culprit - to my mind - seems to be the `controlled_vocab_id` auto-increment which makes it impossible for the insertObject to error and return FALSE on insert with a "duplicate row" error. It will just keep on creating new unique entries.

While I do understand the rationale behind the `build()` function as a whole, I don't really understand why it is called in a pure retrieval context - `getKeywords()` called during generation and subsequent rendering of the metadata form - where there's no need for insertions, deletions or updates.

**Comment by asmecher** [comment]
@netsensei, I suspect you're missing an index on `controlled_vocabs`; the `build` function relies on an index collision to return the existing object. You should have something like
```
MariaDB [ojs-master]> show indexes from controlled_vocabs;
+-------------------+------------+---------------------------+--------------+---------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table             | Non_unique | Key_name                  | Seq_in_index | Column_name         | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-------------------+------------+---------------------------+--------------+---------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| controlled_vocabs |          0 | PRIMARY                   |            1 | controlled_vocab_id | A         |         113 |     NULL | NULL   |      | BTREE      |         |               |
| controlled_vocabs |          0 | controlled_vocab_symbolic |            1 | symbolic            | A         |          28 |     NULL | NULL   |      | BTREE      |         |               |
| controlled_vocabs |          0 | controlled_vocab_symbolic |            2 | assoc_type          | A         |          28 |     NULL | NULL   |      | BTREE      |         |               |
| controlled_vocabs |          0 | controlled_vocab_symbolic |            3 | assoc_id            | A         |         113 |     NULL | NULL   |      | BTREE      |         |               |
+-------------------+------------+---------------------------+--------------+---------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
4 rows in set (0.000 sec)
```

**Comment by netsensei** [comment]
@asmecher Thanks! I'm actually on PostgreSQL.  So, this is how it looks on my end:

```
oa_ojs_journals=# \d controlled_vocabs
                                        Table "public.controlled_vocabs"
       Column        |  Type   |                                    Modifiers                                    
---------------------+---------+---------------------------------------------------------------------------------
 controlled_vocab_id | bigint  | not null default nextval('controlled_vocabs_controlled_vocab_id_seq'::regclass)
 symbolic            | text    | 
 assoc_type          | numeric | default (0)::numeric
 assoc_id            | numeric | default (0)::numeric
```

**Comment by asmecher** [comment]
I don't see any indexes listed there; you should see two:
```
ojs-master=> \d controlled_vocabs
                                                  Table "public.controlled_vocabs"
       Column        |         Type          | Collation | Nullable |                            Default                             
---------------------+-----------------------+-----------+----------+----------------------------------------------------------------
 controlled_vocab_id | bigint                |           | not null | nextval('controlled_vocabs_controlled_vocab_id_seq'::regclass)
 symbolic            | character varying(64) |           | not null | 
 assoc_type          | bigint                |           | not null | 0
 assoc_id            | bigint                |           | not null | 0
Indexes:
    "controlled_vocabs_pkey" PRIMARY KEY, btree (controlled_vocab_id)
    "controlled_vocab_symbolic" UNIQUE, btree (symbolic, assoc_type, assoc_id)
```

**Comment by netsensei** [comment]
Thanks! Adding the indexes works for me.

Putting out how I did this for future reference / others who stumble upon this:

1/

Without the indexes present, controlled_vocabs will end up having duplicate entries. I had to remove those first. I used this query:
```sql
DELETE FROM controlled_vocabs 
WERE controlled_vocab_id not in ( 
    SELECT MAX(controlled_vocab_id) FROM controlled_vocabs 
    WHERE 
          symbolic = 'submissionKeyword' AND assoc_type = '1048585' 
    GROUP BY assoc_id
);
```
I also had a duplicate row with controlled_vocab_id = '1'. I had to do this:
```sql
DELETE FROM controlled_vocabs WHERE symbolic = 'nlm30-publication-types'
```
Not sure how that ended up in controlled_vocabs.

2/ Then I could add the indexes with these queries:

```sql
CREATE UNIQUE INDEX controlled_vocabs_pkey 
    ON controlled_vocabs USING btree(controlled_vocab_id);
ALTER TABLE controlled_vocabs 
    ADD CONSTRAINT controlled_vocabs_pkey PRIMARY KEY 
    USING INDEX controlled_vocabs_pkey;
CREATE UNIQUE INDEX controlled_vocab_symbolic 
    ON controlled_vocabs USING btree (symbolic, assoc_type, assoc_id);
```

After all of that, I have the indices on my table. Going back to OJS, the feature now works as intended. Keywords won't disappear in the metadata form.

I don't recall other PHP based applications using index collisions to implement idempotent I/O operations in this fashion. It makes sense to maintain data integrity through the database backend itself instead of writing extra PHP code.

**Comment by asmecher** [comment]
> I don't recall other PHP based applications using index collisions to implement idempotent I/O operations in this fashion. It makes sense to maintain data integrity through the database backend itself instead of writing extra PHP code.

@netsensei, yes, this is a weird approach, which I arrived at due to the limits of ADODB and the need to support both PostgreSQL and MySQL/MariaDB. I'm currently working on [gradually removing the ADODB dependency](https://github.com/pkp/pkp-lib/issues/2493) in favour of Illuminate/Database, and perhaps it will have some better tools for DBMS-agnostic tasks like this.

Thanks for following up with the detailed solution!
