### ISSUE TITLE
Enable rich text in site-wide "About" field

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5844]
See https://forum.pkp.sfu.ca/t/enable-text-formatting-in-the-ojs-site-about-field/60278/3:
> The About field of the OJS 3.1.x site doesn’t support text formatting and is plain text only. On the contrary a single journal About field support formatting as well as HTML code editing.
>
>I think it makes sense to have consistent behavior and as far as I understand it should not be difficult to support it.

**Describe the solution you'd like**
- Add rich-text editing tools to the site-wide "About" field
- Make sure that the front end templates that use this field expect rich text
- If the format of this field goes from plain-text to HTML, ensure that existing contents are escaped upon upgrade.

**Comment by henriqueramos** [comment]
Hey @NateWr and @asmecher.

There's the pull requests for this task, and the evidence too. Could someone please review it? Thank you!

[ojs](https://github.com/pkp/ojs/pull/3045)
[pkp-lib](https://github.com/pkp/pkp-lib/pull/6769)

![Screenshot from 2021-02-18 03-58-52](https://user-images.githubusercontent.com/1243634/108319650-7bc2c480-71a0-11eb-8349-309a96bf1a03.png)

**Comment by asmecher** [comment]
Looks good overall, @henriqueramos! I made a couple of small request changes on the two PRs; when that's ready, could you also open PRs against OMP and OPS `main` for the same changes?

**Comment by asmecher** [comment]
I just reviewed the cases where this data is used, and they're currently presented without escaping (`lib/pkp/templates/frontend/pages/about.tpl`):
```
{$currentContext->getLocalizedData('about')}
```
This means that in the past we expected users to manually enter HTML into a non-rich text field. The PRs you've proposed will resolve this so the entry is HTML-based, but because the migration escapes existing settings, it'll cause users who worked with this field to have their HTML escaped after upgrade.

On second thought I think it would be less disruptive if we left existing content unchanged, so that existing presentations of content won't change.

**Comment by henriqueramos** [comment]
@asmecher I've removed the migration.

**Comment by henriqueramos** [comment]
@NateWr and @asmecher seems CI ran properly. It's time for another code review round. :tada: :tada: :tada:

Once it's approved, I will create PRs against the OMP and OPS repositories.

**Comment by NateWr** [comment]
It looks like you've only got changes to pkp-lib, so you shouldn't need to create PRs against OMP and OPS. Once the test passes for OJS, we're usually satisfied to merge it to the `main` branch.

**Comment by asmecher** [comment]
Thanks, @henriqueramos! This ended up being such a trivial change that I also cherry-picked it back to `stable-3_3_0`. I hope you didn't mind the detour through the migrations code -- that was a good opportunity to get to know it.

**Comment by davidjb** [comment]
Just opened https://github.com/pkp/ojs/pull/3079 to handle the change in this field from plaintext to rich text; same issue as https://github.com/pkp/ojs/pull/3043

**Comment by NateWr** [comment]
Thanks @davidjb! I've merged that PR and cherry-picked to all of our applications in the `stable-3_3_0`, `stable-3_3_1` and `main` branches.
