### ISSUE TITLE
Journal order resets after reordering

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#5847]
The journal order under the admin/journals page resets after the journals are reordered. Referenced on the [PKP community forum](https://forum.pkp.sfu.ca/t/ojs-3-2-0-2-problem-with-saving-reviewing-guidelines-and-journal-reordering/60322/2).

**Comment by ewhanson** [comment]
Hi @asmecher, could you review these pull requests that address this issue? Thanks.

PRs:
#5854
#5855 (stable)

**Comment by asmecher** [comment]
That's one of those wonderful fixes that involves finding the right 5-byte change in a multi-megabyte codebase... Good spotting!
