### ISSUE TITLE
Some of the Tiny MCE Editor have limited feature

### ISSUE THREAD

**Issue by navotera** [pkp/pkp-lib#5848]
**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

**To Reproduce**
1. Go to 'Site Settings' on multiple journal enviroments
2. Click on 'Appearance -> Setup'
3. Scroll down to 'Page Footer'
4. See error (no button to show any HTML code)

![image](https://user-images.githubusercontent.com/1424851/81467243-118cf480-920a-11ea-8de9-c41c689d43fd.png)

**What application are you using?**
 OJS 3.2.0-3

**Comment by asmecher** [comment]
@navotera, which of our applications (I assume OJS) and what version are you using? (Please include this information when filing a bug entry/feature request.)

**Comment by navotera** [comment]
I am sorry I forget to tell the version. 

I tested it on version 3.2.0-3 but I believe it happen for the version below 3.2.0-3 such as 3.2.0-1 and -2

Thank

**Comment by asmecher** [comment]
@NateWr, what do you think about standardizing the vue.js-based TinyMCE options with the tools provided by the non-vue.js config? There are a few more tools in the non-vue.js stuff (see [SiteHandler.js](https://github.com/pkp/pkp-lib/blob/stable-3_2_0/js/controllers/SiteHandler.js#L160..L161)).

**Comment by NateWr** [comment]
You can use the TextEditorExtras plugin. It's available in the plugin gallery and allows you to configure the new TinyMCE editor to include support for tables, a code editor, and more.

(A longer discussion of why we've gone this route with the new controls is here: https://github.com/pkp/pkp-lib/issues/4890).

**Comment by asmecher** [comment]
:+1: Thanks, @NateWr!

**Comment by navotera** [comment]
Thank you @NateWr for your explanation

**Comment by navotera** [comment]
I have activate this plugin 
![image](https://user-images.githubusercontent.com/1424851/82106146-d6327e80-9751-11ea-85d4-484cc0829521.png)

But somehow, the code button on the main site setting on the Footer Text Editor is not appear 
![image](https://user-images.githubusercontent.com/1424851/82106173-f82c0100-9751-11ea-99bf-2465761f9c80.png)

Any ideas or the HTML code is not supported on the main index page setting ?

**Comment by NateWr** [comment]
Have you configured the plugin settings yet? You enable the fields you want for each field, as shown in this screenshot:

https://github.com/pkp/textEditorExtras

To get to settings go to Settings > Website > Plugins > Text Editor Extras > (Click the arrow to open options) > Settings.

If there is a field that's not included in the plugin, let us know and we can add it.

**Comment by navotera** [comment]
Hi @NateWr 
Thank for your respond 
In the Site Settings (the main site of OJS) there is no setting for the TextEditorExtras as you have told me. 
![image](https://user-images.githubusercontent.com/1424851/82273219-7b965e00-99af-11ea-878a-b553c4bbf1f9.png)

And when users (domain/index.php/index/admin/settings) access this URL to add footer on the main site of the OJS the button that should available as HTML source button does not appear on the text editor. 
![image](https://user-images.githubusercontent.com/1424851/82273284-af718380-99af-11ea-93a0-f115b2b3d68c.png)

Any ideas regarding this ?

**Comment by NateWr** [comment]
Ah I see, the settings are only available for each context (journal), not at the site-wide level. You'll need to configure it for each journal.

**Comment by navotera** [comment]
Yes it does not work on side wide level when we want to add footer on the side wide level. 
Is it possible to do it on the side wide level ?

**Comment by NateWr** [comment]
I'd like to but I don't know if I will get to it soon. We would accept a pull request with this change at https://github.com/pkp/textEditorExtras.

**Comment by kerimsarigul** [comment]
Same issue (no button to show any HTML code) persists in OJS 3.3.0.10.

**Comment by asmecher** [comment]
@kerimsarigul, see above: https://github.com/pkp/pkp-lib/issues/5848#issuecomment-627884957

**Comment by kerimsarigul** [comment]
Hi @asmecher, 
I have extra text editor an I activated it.
It works on any journal's website settings.
But on "Administration > Site Settings" page can not see.
![image](https://user-images.githubusercontent.com/54417583/172449210-f70555ab-b72e-4755-97e0-7c134d345144.png)

**Comment by progiri** [comment]
Hi, I have same trouble in my ojs ((
Is there any solution for this? 
My ojs version is 3.4.0.4

**Comment by asmecher** [comment]
@progiri, this issue is closed; if none of the content here helps you, I'd suggest posting in the support forum (https://forum.pkp.sfu.ca).
