### ISSUE TITLE
Problems when using multilingual FieldRadioInput form field

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#5849]
OJS 3.2.0-3

When working with new forms, particularly, with radio input field (`FieldRadioInput` class), I've noticed several non-critical issues associated with this field being multilingual:
1. It's possible to pick only 1 value between languages per time. E.g., when selecting a value for another language the item from a prior locale becomes not selected. Thus a value for 1 language will always be passed empty. 
2. `label` property for this field is displayed only for primary locale.
3. I'm getting an error in the console:
```
TypeError: this.options.filter is not a function
    at o.isInputSelected (build.js?v=3.2.0.2:8)
    at ri.get (build.js?v=3.2.0.2:14)
    at ri.evaluate (build.js?v=3.2.0.2:14)
    at o.isInputSelected (build.js?v=3.2.0.2:14)
    at o.mounted (build.js?v=3.2.0.2:8)
    at rt (build.js?v=3.2.0.2:14)
    at Nn (build.js?v=3.2.0.2:14)
    at Object.insert (build.js?v=3.2.0.2:14)
    at C (build.js?v=3.2.0.2:14)
    at Li.__patch__ (build.js?v=3.2.0.2:14)
```
BTW, is it possible to use unminified version of this library?

Screenshot for the first 2 issues:
![radio_input](https://user-images.githubusercontent.com/20665587/81572123-7e8bc000-93ab-11ea-9cae-177c1fe935b7.png)

**Comment by Vitaliy-1** [comment]
@NateWr, my comments here while trying to resolve the issue:

- Shouldn't localized name for input field be used: https://github.com/pkp/ui-library/blob/680d529ff059837b94185fcbf4510006683b3f72/src/components/Form/fields/FieldRadioInput.vue#L59 and https://github.com/pkp/ui-library/blob/680d529ff059837b94185fcbf4510006683b3f72/src/components/Form/fields/FieldRadioInput.vue#L71. I mean something like `localizedOptions`?

- by similarity with `FieldOptions`, shouldn't here https://github.com/pkp/ui-library/blob/680d529ff059837b94185fcbf4510006683b3f72/src/components/Form/fields/FieldRadioInput.vue#L124 `localizedOptions` be used?

I don't know underlying code, so just guessing.

**Comment by Vitaliy-1** [comment]
Something like in this PR: https://github.com/pkp/ui-library/pull/108

**Comment by NateWr** [comment]
I think that looks correct, @Vitaliy-1. What happens to the value that is emitted when you use it in multilingual field. When the value of the field changes, it should emit a `changed` event which you can track in the Vue.js dev tools. When the field is multilingual, that event should also pass the locale that is changed.

**Comment by Vitaliy-1** [comment]
@NateWr, the value for the multilingual of the `set` event :
```
{"en_US":"%d-%m-%Y","uk_UA":"%d.%m.%Y"}
```
Which is the correct value.

The same for the `changed` event:
```
["dateFormatShort","value","%d.%m.%Y","uk_UA"]
```

**Comment by NateWr** [comment]
Looks correct to me.

**Comment by Vitaliy-1** [comment]
Would it be ok to merge that PR?

**Comment by NateWr** [comment]
Merged! Is that all that's needed for this issue or is there still more work to be done here?

**Comment by Vitaliy-1** [comment]
Thanks! Yeah, looks like it's fixed, closing.

**Comment by Vitaliy-1** [comment]
@NateWr, sorry, I think I forgot to make here another change alongside with the one proposed.
Now, when `isInputSelected()` is working as expected for multilingual fields, I believe the assignment of `inputValue` should be changed upon Vue instance mount: https://github.com/pkp/ui-library/blob/ffe9d8a5aab143509e00ea414f34051db1b0c4dd/src/components/Form/fields/FieldRadioInput.vue#L165
If field is multilingual:
```
this.inputValue = this.value[this.localeKey];
```
else leave as is.

**Comment by Vitaliy-1** [comment]
PR: https://github.com/pkp/ui-library/pull/112

**Comment by NateWr** [comment]
Merged, thanks!
