### ISSUE TITLE
Review Form not getting the correct title and description

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5856]
**Describe the bug**
Check https://forum.pkp.sfu.ca/t/ojs-3-2-0-3-review-forms-not-displaying-title-and-description-instructions/60424 for a bug description

**Comment by defstat** [comment]
@asmecher 

**PRs**
[PKP-LIB]: #5857
[OJS]: pkp/ojs#2740
[OMP]: pkp/omp#810
[OPS]: pkp/ops#21

**Comment by asmecher** [comment]
Merged for 3.2.1 -- thanks, @defstat!
