### ISSUE TITLE
OJS 3.2 - Access alert for Submissions with Pre-review discussions of Editorial Team

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5863]
**Describe the bug**
When a submission is on the first stage of workflow and there are pre-review discussions among Editorial staff it shows a Javascript alert to the author when it loads the submission detail page. It occurs if the author also posts a pre-review discussion topic. At the end the page loads showing only the author's post for pre-review. 

**To Reproduce**
1. Go to Users and roles
2. Pick up an author and log in as him/her
2. Click on a submission with pre-review discussion posts
3. When page loads it shows the alerts

**What application are you using?**
 OJS  version 3.2.0-3

**Additional information**
Screenshots of the alerts:
![image](https://user-images.githubusercontent.com/4992902/81744912-d987ea80-9471-11ea-8e24-93c5a7e4da13.png)

![image](https://user-images.githubusercontent.com/4992902/81744922-de4c9e80-9471-11ea-98a2-be708277f213.png)

**Comment by ewhanson** [comment]
**Bug description**
If an author user doesn't have permissions for workflow stages assigned to their user group, the following happens: when loading the author dashboard to view a submission, a `fetchGrid` request from a `GridHandler` will result in an `AUTHORIZATION_DENY` decision from the `UserAccessibleWorkflowStagePolicy`.

Current offenders for access alerts in author submission workflow:

- `ArticleGalleyGridHandler`
- `CopyeditFilesGridHandler`

**Comment by ewhanson** [comment]
Hi @NateWr, could you review the pull request that addresses this issue? Thanks.

PR:
#5926

**Comment by ewhanson** [comment]
No fix for OPS as this bug does not affect OPS.

**Comment by NateWr** [comment]
Thanks @ewhanson! The OJS tests look good but the OMP ones are failing on installation. I think this is due to a typo introduced to OMP master and fixed a few days ago. So if you just rebase your PRs the tests will run again.

**Comment by ewhanson** [comment]
Thanks @NateWr. It looks like all the test are passing now expect for PHP 7.4 with pgsql for OMP.

**Comment by NateWr** [comment]
This has been merged to `master`. Erik is backporting to 3.2.1 and then we can close this. :+1:

**Comment by ewhanson** [comment]
Backport for `stable-3_2_1`.

PRs:
#5958
pkp/ojs#2789
pkp/omp#832

**Comment by NateWr** [comment]
Thanks @ewhanson!
