### ISSUE TITLE
Blank page when attempting step 1 of Peer Review process

### ISSUE THREAD

**Issue by smorello87** [pkp/pkp-lib#5864]
**Describe the bug**
After assigning a peer review, the reviewer is unable to accept it because the request gets processed as a blank page. 

**To Reproduce**
1. Log in as user with a peer review assigned Go to 'My Queue --> My Assigned'
2. Click on 'Title of the essay..'
3. We're supposed to be able to accept/reject the assignment here, but the page just shows up as blank (see attached) – it's happened twice on two different submissions, everything worked fine before then (I think we sent something in peer review last week?) 

Any idea what it could be? 

**What application are you using?**
 OJS 3.1 

**Additional information**
![Screen Shot 2020-05-13 at 7 43 42 AM](https://user-images.githubusercontent.com/35434644/81809231-03cbbd80-94ef-11ea-9a20-bf6eb4e34ae6.png)

**Comment by asmecher** [comment]
@smorello87, check your PHP error log for details.
