### ISSUE TITLE
Clean up plugin installation error handling

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5869]
Plugin installation problems are frequent on the forum; users often have trouble with file permissions, `tar` tool configuration, the `exec` function being disabled, etc. The error messages OJS/OMP/OPS currently gives are inscrutable.

Clean up the error handling, adding messages as needed.

**Comment by asmecher** [comment]
Changes:
- Use exceptions for error handling
- Remove code treating `lib/` in plugin archive specially (an occasional gotcha)
- (Add a bit of similar error handling to the log file management code)
- Remove some of the convoluted use of `FileManager` et al
- Minor self-doc improvements

PRs:
- https://github.com/pkp/pkp-lib/pull/5870
- https://github.com/pkp/ojs/pull/2747 (tests only)

**Comment by asmecher** [comment]
@NateWr, could you have a look at this for potential inclusion into OJS 3.2.1? I know this is a fair-sized change, but [given](https://forum.pkp.sfu.ca/t/solved-custom-block-manager-didnt-save/41800) [the](https://forum.pkp.sfu.ca/t/after-upgrade-ojs-3-1-1-4-to-ojs-3-0-2-0-change-language-problem/59830/7) [sheer](https://forum.pkp.sfu.ca/t/ojs-3-2-0-0-files-of-this-type-can-not-be-uploaded/59381) [amount](https://forum.pkp.sfu.ca/t/plugin-gallery-dont-work/48833/28) [of](https://forum.pkp.sfu.ca/t/themes-for-ojs-3-1-1-0/43373/4) [confusion](https://forum.pkp.sfu.ca/t/install-quick-submit-from-gallery-ojs-3-1-2-2-windows/55328) [the](https://forum.pkp.sfu.ca/t/cant-upload-a-output-flag/45450/3) [current](https://forum.pkp.sfu.ca/t/issues-after-update-to-ojs-3-0-2-file-upload-new-submission-not-working/29688/17) [error](https://forum.pkp.sfu.ca/t/unable-to-install-defaultmanuscript-and-other-plugins/51457) [handing](https://forum.pkp.sfu.ca/t/quicksubmit-plugin-not-working/30462/10) [causes](https://forum.pkp.sfu.ca/t/addthis-plugin-doesn-t-work-ojs-3-0-2/32816/11) [and](https://forum.pkp.sfu.ca/t/ojs-3-1-1-2-issue-when-try-to-install-a-plugin-from-plugin-gallery/50007) [the](https://forum.pkp.sfu.ca/t/code-pubidplugins-at-home-page-ojs-3-1-1/45415/3) [time](https://forum.pkp.sfu.ca/t/trying-to-install-the-addthis-plugin/38880/3) [it](https://forum.pkp.sfu.ca/t/ojs-generates-error-500-after-orcid-plugin-update/53452/5) [costs](https://forum.pkp.sfu.ca/t/plugins-wont-install-in-cpanel-but-can-be-installed-in-linux-solved/54271/4) [to](https://forum.pkp.sfu.ca/t/quick-submit-missing-corresponding-folder-for-plugin/55478/6) [work](https://forum.pkp.sfu.ca/t/quicksubmit-plugin-not-installing/48543) [through](https://forum.pkp.sfu.ca/t/ojs-3-1-2-plugin-gallery-error-cannot-install-any-plugin/55989/11) [it](https://forum.pkp.sfu.ca/t/issue-while-installing-quicksubmit-plugin-via-plugin-gallery-in-ojs-3-1-2-4/57969/10) [on](https://forum.pkp.sfu.ca/t/the-tar-command-is-not-available-please-correctly-configure-it-in-your-config-inc-php/55307/3) [an](https://forum.pkp.sfu.ca/t/translator-plugin-displaying-blank-page/50469/2) [individual](https://forum.pkp.sfu.ca/t/tar-problem-any-other-config/59660/4) [basis](https://forum.pkp.sfu.ca/t/ojs-3-1-2-4-no-file-uploaded-while-using-plugin-gallery/58916), [I](https://forum.pkp.sfu.ca/t/defaultmanuscript-problem/60412/28) [think](https://forum.pkp.sfu.ca/t/plugins-does-not-installed-or-upgraded-3-1-1-4/49118) [it's](https://forum.pkp.sfu.ca/t/i-cant-install-anything-directly-from-the-plugin-gallery/54661/4) [justifiable](https://forum.pkp.sfu.ca/t/error-instal-plugin-quicksubmit/59200).

**Comment by asmecher** [comment]
(@quoideneuf, you might be interested in this too...)

**Comment by quoideneuf** [comment]
Looks like a positive change to me...really hard to find the origin of those old errorMsg values if you aren't familiar with the code flow.

**Comment by NateWr** [comment]
:+1: Yep, definitely a justified inclusion I think and a great improvement.

**Comment by asmecher** [comment]
Merged, thanks!
