### ISSUE TITLE
DOI Plugin Deleted

### ISSUE THREAD

**Issue by SamiullahSarwar** [pkp/pkp-lib#5873]
Hi,

I have mistakenly deleted the DOI plugin from Plugins > Public Identifier Plugins.
Please let me know how to retrieve it. Or is there any other appropriate solution for that.

Regards,
Samiullah Sarwar

**Comment by asmecher** [comment]
@SamiullahSarwar, could you post this on our support forum at https://forum.pkp.sfu.ca? That's the best place to go for tech support.
