### ISSUE TITLE
OJS3.2 Editorial activity stats counting submissions from removed journals

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5876]
**Describe the bug**
When a journal is deleted on OJS2 all submissions that didn't start the review stage are kept in the database. These lost submissions are counted on the Editorial activity stats chart of remaining journal  even though they have different context_id.

**To Reproduce**
1. Go to 'Statistics > Editorial Activity'
2. Check Submission number
3. Go to Dashboard > Submissions
4. Filter "Active"tab by submissions
5. Check the discrepant number of submissions

**What application are you using?**
 OJS  version 3.2.0-3

**Additional information**
The removal of journal in OJS3.2 works fine. It only happens for upgrades from OJS2 that already remove the journal.

**Comment by israelcefrin** [comment]
Maybe could be a good ideia, during upgrade process, check whether the context_id of a submission does exist on journal database.

**Comment by israelcefrin** [comment]
A quick note: It seems that for multi-journal installation the Editorial activity is counting all journals. When I have different journals it was supposed to show only stats for one journal per time.

See the screenshot bellow for  journal without any submission for the last 2 years and showing active submissions:
![image](https://user-images.githubusercontent.com/4992902/82239845-6fef5c80-9907-11ea-9d90-7fd6220e2a9f.png)

**Comment by jonasraoni** [comment]
**PRs:**
stable-3_2_0: #5908
master: #5909

**Comment by asmecher** [comment]
Thanks, @jonasraoni! @israelcefrin, is this something you can try out without too much screaming?

**Comment by israelcefrin** [comment]
Hi @asmecher, I've already patched some installation and they are working smoothly. 
Thank you @jonasraoni.

**Comment by asmecher** [comment]
Thanks, @israelcefrin and @jonasraoni! Merged both.
