### ISSUE TITLE
[OJS] "How to cite" has missing space between surname and first name

### ISSUE THREAD

**Issue by wujastyk** [pkp/pkp-lib#5880]
**Describe the bug**

![image](https://user-images.githubusercontent.com/762246/81984739-783b5500-95f2-11ea-8374-9239881ef920.png)

There's no space between "Verdon" and "Noémi".  This is the case for all authors and all citation formats.  It should read "Verdon, Noémi and Michio Yano."  

**What application are you using?**
 OJS version 3 point something.

**Comment by asmecher** [comment]
@wujastyk, can you check the specific version of OJS? See https://forum.pkp.sfu.ca/t/how-do-i-determine-my-pkp-softwares-version/28534 for details.

**Comment by wujastyk** [comment]
Sorry, I can't help.  I am a journal editor but not administrator. I'm using an installation that is managed by my university.  The OJS interface for journal editors bizarrely doesn't expose the OJS version number.  The instructions you pointed to do not solve this limitation.
In October last year I was told we were moving to OJS 3.1.2 "in a few weeks."  I will write to the administrators and ask, but it will take some days.

**Comment by asmecher** [comment]
@wujastyk, if you right-click on the page and hit "View Page Info", you should see the version of OJS used.

**Comment by wujastyk** [comment]
That was easy!  Thank you :-)

Open Journal Systems 3.1.2.4

**Comment by asmecher** [comment]
@wujastyk, I suspect this is a bug in the citeproc-php library we use to format citations. OJS 3.1.2-4 includes version 2.1.6 of that library, and 3.2.0-3 (the latest stable release) includes the newer version 2.2.0. I'd suggest upgrading to the latest OJS if that's feasible; alternately you may be able to update the citeproc-php library using Composer. See the `composer.json` / `composer.lock` files in `plugins/generic/citationStyleLanguage`.

**Comment by asmecher** [comment]
Closing as out of date.

**Comment by wujastyk** [comment]
I confirm that this is fixed:
![image](https://user-images.githubusercontent.com/762246/229305200-e798d3ca-2b89-43bf-90cd-72a1f3ce50a0.png)

Many thanks!
Dominik
