### ISSUE TITLE
[OPS] Can authors create a new version of their published submissions without the publish permission?

### ISSUE THREAD

**Issue by AdSuzs** [pkp/pkp-lib#5883]
Based on the [Returning Author Screening Plugin](https://github.com/pkp/returningAuthorScreening), we want to know if we can authorize authors to create versions of their published works with the rule that they still can't publish their submissions.

[Here](https://github.com/pkp/returningAuthorScreening/blob/master/ReturningAuthorScreeningPlugin.inc.php#L76) we see that is easy to give the permission to authors to publish and with this they can also create versions. The idea is to give only the permission to create versions, but we didn't find a Hook to call a function to enable this permission. We also wants know if this is possible. 

Thanks!

**Comment by alexxxmendonca** [comment]
Hi @AdSuzs !

I think your issue is similar to mine. Please check #5867.
