### ISSUE TITLE
[OJS/OMP] Ability to send review reminders prior to due date

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5885]
**Describe the problem you would like to solve**
Reviewers are informed only after the review deadline has reached, not before. If they are notified before, it could increase chances of getting reviews before the deadline and by extent shortening the overall manuscript evaluation time.

**Describe the solution you'd like**
Ability to send review reminders prior to the due date.

**Who is asking for this feature?**
See:
https://forum.pkp.sfu.ca/t/automatic-reminder-for-upcoming-review-deadline/50580
https://forum.pkp.sfu.ca/t/reminder-for-reviewers-that-the-review-is-due-soon/51907

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9612
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/333
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4141
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1555
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/749 [TEST ONLY]

**Screenshots**
New look based on @Devika008 's design
<img width="768" alt="CleanShot 2024-04-22 at 18 08 28@2x" src="https://github.com/pkp/pkp-lib/assets/2587979/96ee7ff3-3968-4a80-9713-ecd367b43acc">

**Comment by NateWr** [comment]
Probably what we want here is a tool for configuring reminders that lets the journal set up a reminder, define when it occurs (X days before/after due date), and configure the email that is sent.

**Comment by pmangahis** [comment]
+ 1 from Hosted journal

**Comment by pmangahis** [comment]
+1 from Hosted journal

**Comment by librariam** [comment]
+1 more from PKP|PS

**Comment by twakeford** [comment]
Reminders before the due date as well after gets a big thumbs up from Ubiquity. We get this request very frequently.

**Comment by trobb49** [comment]
Actually, I'm surprised that this function is not already available.  It is must "friendlier" to remind reviewers early, than to embarrass them afterward by telling them that they have already missed their deadline.  Also, the chances are that they are notified after the due date, they will not produce as good a review since they will feel rushed.
 The major journal publishers have their own dedicated systems that do include this feature.

**Comment by forgive38** [comment]
+1 from our editors

**Comment by forgive38** [comment]
Do you think reminder before date should be only for review due date or for review request due date too ?

Should we have a dedicated email template ?

I propose to extend the current management of delay for reminder: 
![sample](https://user-images.githubusercontent.com/31130607/193288210-a56ffdb0-36f0-4762-84eb-7164ec5b126b.png)

**Comment by NateWr** [comment]
> I propose to extend the current management of delay for reminder:

We only support one email at the moment. If we extend it to support more than one email, we should turn it into a more flexible system that allows journals to configure as many reminders as they want.

Given our timeline for 3.4, we don't have time to work on multiple emails. So I would suggest extending the existing field to support negative numbers. That would be one email which could be sent before or after the deadline, depending on the setting.

**Comment by forgive38** [comment]
Why not ... but this implies that there is no other reminder when the reviewer is late, and the template mail of reminder should be modified by editors in case of negative delay (verb tense future vs past tense)

**Comment by touhidurabir** [comment]
@Vitaliy-1 can you please review the PR at https://github.com/pkp/pkp-lib/issues/5885#issue-619100309 . 

The above PR contains several update as follow 
- ability to set up review response and submit remainder for both before and after days as proposed at https://github.com/pkp/pkp-lib/issues/5885#issuecomment-1263626451 .
- update of the previous settings name as remainder mail was sent after but name was defined as before which is confusing.
- when adding a new reviewer, it is possible to set a lower review submit date than the review response date which seems bit off logic as reviewer first need to respond to request and then submit review if accepted . The corresponding validation added to backend to avoid this case.
- moved the logic to send remainder mail to queue job . 

More possible enhancement : 
- add a fronted validation also to handle review response due date must be before the review submit due date that match up with the backed validation . 
- when adding a new reviewer, the notification in case of any issue does not show up immediately but after a page reload . this can be fixed also .

**Comment by Vitaliy-1** [comment]
@touhidurabir, I would vote for allowing users a custom number of reminders they want to send to reviewers. We can have only one form field type that accepts negative number as a number of days before the due date occurs. That gives more flexibility although I don't think that creating a high number of reminders would be a frequent use-case.

**Comment by pilasou** [comment]
Hi! This is not the same need, but it is related : we proposed to offer the ability to set up multiple reviewer reminder (see [#9455](https://github.com/pkp/pkp-lib/issues/9455)). I had a quick chat with @asmecher and he mentioned me a strategy I agree with which is to approach by "levels":
•	First, as part of 5885 (this issue), implement a second reminder that is sent a configurable time before the deadline. This would limit the reminders to a maximum of 2, but would meet most of the need expressed in [#9455](https://github.com/pkp/pkp-lib/issues/9455).
•	Later, if demand is sufficient, we add more generalized support for users to be able to create an arbitrary number of reminders scheduled for specific times before or after the date.

Thanks!

**Comment by touhidurabir** [comment]
@asmecher all rebased and updated . Tests are all passing so ready for final review .

**Comment by touhidurabir** [comment]
@asmecher all rebased . If all tests passes, should be good to merge .

**Comment by pilasou** [comment]
Thanks @touhidurabir, this is a great improvment. As part of it I suggested to offer the ability to set a 2nd reminder. See my whole comment on this issue: https://github.com/pkp/pkp-lib/issues/5885#issuecomment-1949317971. Is this part of this improvment? Thank you.

**Comment by asmecher** [comment]
@touhidurabir, all merged, thanks! Closing this issue.

**Comment by touhidurabir** [comment]
> Thanks @touhidurabir, this is a great improvment. As part of it I suggested to offer the ability to set a 2nd reminder. See my whole comment on this issue: [#5885 (comment)](https://github.com/pkp/pkp-lib/issues/5885#issuecomment-1949317971). Is this part of this improvment? Thank you.

@pilasou This is close but not exactly what describe in https://github.com/pkp/pkp-lib/issues/9455 . For this one, reviewer can get max 2 sets of reminder as 
1. one before x days of response due date and one after x days after the response due date
2. one before x days of submit due date and one after x days after the submit due date 

If I am not mistaken, what https://github.com/pkp/pkp-lib/issues/9455 propose is multiple reminder occurrences before/after due dates which will JM/Editor can configure has not been implemented in it . 

But perhaps this compensate enough what proposed in https://github.com/pkp/pkp-lib/issues/9455 as reviewer get 2 reminder for response and 2 reminders for submit and configureable by x number of days .

**Comment by pilasou** [comment]
Hi @touhidurabir thanks. I tend to consider that with your new feature the reminders (4 reminders can be configured) can be an answer to https://github.com/pkp/pkp-lib/issues/9455. Our journals have mainly configured 2 reminders per type (response due, submission due). For this reason, I think https://github.com/pkp/pkp-lib/issues/9455 may be closed as well.
