### ISSUE TITLE
[OPS] New discussion notifications leads to 404

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5890]
**Describe the bug**
When an author adds a message to a discussion from a preprint that has been already posted, the link leads to a 404 error.

**To Reproduce**
1. Post a preprint
2. As the preprint author, add a new comment to a discussion
3. As the moderator, see the notification in "Tasks" and attempt to access the submission

**What application are you using?**
Open Preprint Systems 3.2.0.3

**Additional information**
![Untitled_ May 18, 2020 1_29 PM](https://user-images.githubusercontent.com/4059679/82237621-54d31b80-990c-11ea-9f37-ffeb92c9501b.gif)

**Comment by alexxxmendonca** [comment]
Update: this issue is affecting non-posted preprints as well.

**Comment by alexxxmendonca** [comment]
Could be related: 

The email notification sent to inform new activities such as new discussion added no longer included the submission link.

> You have a new notification from {$siteTitle}:
> 
> {$notificationContents}
> 
> Link: **{$url}**
> 
> Kind regards,

Here's how the emails are coming:

> There is new activity in the discussion titled "[SciELO Preprints] Comprobación inicial | Ajustes solicitados" regarding the submission "Clinical and epidemiological characterization of COVID-19 in the Ciego de Ávila province".
> 
> Link:
> 
> Kind regards,

Notice the blank after "Link"

**Comment by ajnyga** [comment]
But you can access the discussion if you go to the workflow of a submission?

**Comment by alexxxmendonca** [comment]
@ajnyga Yes.

I have to search for the submission by its title or author, given that the link doesn't work, but once I am there yes, I am able to open the discussion just fine.

**Comment by NateWr** [comment]
@ajnyga can you double-check my fix here? It looks like a fallback to the parent method was missing, but maybe you removed it on purpose.

PR:
https://github.com/pkp/ops/pull/34

**Comment by ajnyga** [comment]
probably by mistake!

**Comment by asmecher** [comment]
Tested and merged! Closing.

**Comment by asmecher** [comment]
(Also cherry-picked to `stable-3_2_0`.)
