### ISSUE TITLE
[OJS] KeywordCloudPlugin to 3.2 Version of OJS _cache miss not working anymore

### ISSUE THREAD

**Issue by mbarros64** [pkp/pkp-lib#5891]
Hello, we were adapting the KeywordCloudPlugin and the function _cacheMiss does not working anymore. Can someone help us to identify something has changed of OJS 3.1 in relation to 3.2 version?
Here the original code that works fine on version 3.1:
https://github.com/lepidus/ojs3-keywordcloud-plugin/blob/master/KeywordCloudBlockPlugin.inc.php#L76
And that is the code with our modifies, in this case, the funciont _cacheMiss doesn’t works:
https://github.com/matheuslepidus/ojs3-keywordcloud-plugin/blob/ojs3.2/KeywordCloudBlockPlugin.inc.php#L77

Thanksss!

**Comment by mbarros64** [comment]
@asmecher

**Comment by Vitaliy-1** [comment]
Hi @mbarros64,

Have you explored where it's failing? It may be related to [this issue](https://github.com/pkp/pkp-lib/issues/5892) related to block plugins

**Comment by mbarros64** [comment]
Hi @Vitaliy-1 , we found another way to make the plugin work, we verify if cache is empty, if is, we call the function that returns a list of kewords and put it on cache. And now, the code no more depends of _cacheMiss function.
