### ISSUE TITLE
Group archive issues by year (as in OJS3)

### ISSUE THREAD

**Issue by peter-parkerr** [pkp/pkp-lib#5893]
Hi @fgnievinski @NateWr
I want to show archives issues by year either in menu or in sidebar.
I have seen this & tried but it's not working .
https://forum.pkp.sfu.ca/t/ojs-3-archives-group-by-year/28848/17

Can you help me to resolve this issue. Looking forward.

**I am using**
OJS 3.2.0-3

Thanks & Regards

**Comment by NateWr** [comment]
HI @peter-parkerr, we reserve the issues here on GitHub for bug fixes and feature requests. If you post in the forum thread we can try to help you there. You can tag me (@NateWr) if you want to make sure that I see it.

Also, you may have seen this, but we have a separate issue filed for this feature request here: https://github.com/pkp/pkp-lib/issues/4667.
