### ISSUE TITLE
[OPS] Give author permissions

### ISSUE THREAD

**Issue by mbarros64** [pkp/pkp-lib#5900]
Hello, we are developing a plug-in for anyone who can create and publish publicly and would like to have some idea of ​​how to get author permission to publish only versions that  that he created, and not that any submission has been published. The OPS dont have any hook to use for gives author permission only once he created a version of a submission. 
So, we have the ideia of modificate the permission via template that make acess to this permission, they are all relationed to author. Anyone have a better idea or a feedback of this solution?

**Comment by asmecher** [comment]
@mbarros64, the support forum (https://forum.pkp.sfu.ca) is the best place for this kind of question; have you posted there? This is more for bug entries and feature requests that have been fully specified, not Q&A.
