### ISSUE TITLE
Reorder OPS archive/browse handlers

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5903]
After moving to a category centric OPS default theme, we also need to redesign the frontend handlers.

The new archive/browse paths are the following

`/preprint/ `- path to single preprint views
`/preprints/` - path to archive listings, by default show all preprints starting from the latest
`/preprints/category/name` - path to a category archive
`/preprints/section/name` - path to a section archive

**Comment by ajnyga** [comment]
ping @asmecher and @NateWr 

pr of OPS master: https://github.com/pkp/ops/pull/29

**Comment by ajnyga** [comment]
tests above are passing...

**Comment by NateWr** [comment]
This looks good. So is the idea to roll this out for OPS in 3.2.1 and then for 3.3 to try to align all three apps?

**Comment by NateWr** [comment]
Also, just want to confirm: this only adjusts the collections (archive, section, category). Not the URL for a single preprint, right?

**Comment by ajnyga** [comment]
Yes, I think this should go to 3.2.1. For OJS and OMP I am happy to pr if the general concept is agreed on.

Yes, I have not touched the single preprint handlers.

**Comment by NateWr** [comment]
Ok, so for 3.2.1 we'll just merge this to OPS and plan to align everything for 3.3. Let me bring @asmecher in on some of the conversations we've been having.

Alec, the goal is to further align how OJS/OMP/OPS handle their archive, category and preprints pages, share code across the three applications, and migrate to some nicer, more SEO-friendly URLs. In the long term we'd also seek to align this with the [SubmissionGroups](https://github.com/pkp/pkp-lib/issues/4415) proposal.

What I'm thinking is that we'll have a parent class in pkp-lib that is something like `PKPPublicationsHandler` with three methods: `index` (all publications), `section` (browse by section), and `category` (browse by category).

Then each application will define its own page path and route to a handler that implements the `index`/`section`/`category` ops. In this way, each application would have a similar URL structure but a unique page path.

- `/<page>` (all publications)
- `/<page>/page/X` (paginated publications)
- `/<page>/section/<section-name>` (publications in section)
- `/<page>/section/<section-name>/page/X` (publications in section paginated)
- `/<page>/category/<category-name>` (publications in category)
- `/<page>/category/<category-name>/page/X` (publications in category paginated)
- `/<page>/category/<category-name>/<sub-category-name>` (publications in subcategory)
- `/<page>/category/<category-name>/<sub-category-name>/page/X` (publications in subcategory paginated)

So OPS would be `/preprints/...`, OMP would be `/catalog/...` and OJS would be `/articles/...`. (In OJS, the `/archive` would continue to exist as an issue archive.)

Does that sound sensible? It's not on our roadmap for 3.3 but I think @ajnyga has a good handle on what needs to be done and could do it relatively quickly. We'd just need to make sure we're redirecting from the old URLs where appropriate.

**Comment by asmecher** [comment]
Yes, this is sensible, and a good stepping stone towards the distant goal of unifying the applications. Please go ahead!

**Comment by NateWr** [comment]
Merged this for 3.2.1 and filed a new issue for the work in 3.3: https://github.com/pkp/pkp-lib/issues/5932
