### ISSUE TITLE
Journal ordering no longer working? why?

### ISSUE THREAD

**Issue by Jirehnutrilife** [pkp/pkp-lib#5906]
In a multi-journal installation’s administration tab: hosted journal ordering doesn’t save changes in the order. Clicking on Done reloads the page without registering the chosen [journa]([url]https://jirehnutrilifesport.com/(url))l order. Seen on the OJS demo site.

**Comment by Jirehnutrilife** [comment]
visit https://jirehnutrilifesport.com/

**Comment by asmecher** [comment]
@Jirehnutrilife, see: https://github.com/pkp/pkp-lib/issues/5847
