### ISSUE TITLE
CrossRefExportPlugin Article Search not filtering by `Status`

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5907]
**Describe the bug**
CrossRefExportPlugin Article Search not filtering by `Status`

**To Reproduce**
1. Enable CrossRef Plugin
2. Go to CrossRef XML Export Plugin
3. Go to Articles Tab
4. Click Search, and change the status DropDown list to `Marked active` for example (having some `Marked active` submissions on the grid.
5. Click Search - no submissions will be displayed.

**What application are you using?**
 OJS v3.2.x

**Additional information**
Check also https://forum.pkp.sfu.ca/t/problem-with-the-search-tool-in-crossref-xml-export-plugin-and-doaj-export-plugin/60724

**Comment by defstat** [comment]
At https://github.com/pkp/pkp-lib/blob/master/classes/submission/PKPSubmissionDAO.inc.php#L363
the query searches in the `publication_settings` table for `pubIdSettingName` and `pubIdSettingValue`, the "Mark active" button at `importexport/plugin/CrossRefExportPlugin#exportSubmissions-tab`, adds the `markedActive` indication to `submission_settings` table under the `crossref::status` setting_name (at https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/CrossRefExportPlugin.inc.php#L379).

Should check:

- [ ] Where other possible statuses are preserved
- [ ] How the upgrade process works (from 3.1.2 to 3.2.0)

**Comment by defstat** [comment]
After discussing with @NateWr on that, the best way is to leave the `crossref::status` in the `submission_settings` (even though the `doi` data is in the `publication_settings` table)

@NateWr @asmecher 

**PR**
[pkp-lib]: #5915
[OJS]: pkp/ojs#2771 (Submodule only)
[OMP]: pkp/omp#822 (Submodule only)

**Comment by asmecher** [comment]
I'll take @NateWr's word for it -- thanks, @defstat!
