### ISSUE TITLE
OJS 3.2 - Themes can be select while disabled on Plugin gallery

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5914]
**Describe the bug**
It is possible to select any theme from Appearance > Themes drop-down menu even they are disabled on the Plugins gallery.

**To Reproduce**
1. Go to 'Dashboard > Appearance > Plugins'
2. Scroll down to 'Theme Plugins' and disable all themes but Default Theme.
3. Go to 'Dashboard > Appearance'
4. Click the "select theme" drop-down and select a theme that was disabled
5. Save and test on live site
6. The Theme will be still disabled from Plugins gallery, and working though.

**What application are you using?**
 OJS  version 3.2.0-3

**Additional information**
Disabled Theme Plugins
![image](https://user-images.githubusercontent.com/4992902/82836497-99266480-9e94-11ea-99cc-ebf3435ffd8b.png)

All themes available:
![image](https://user-images.githubusercontent.com/4992902/82836603-d0951100-9e94-11ea-97a6-669d3f5bb297.png)

**Comment by NateWr** [comment]
@israelcefrin this may just be an issue whereby the theme options don't update when a theme is disabled. Can you try refreshing the page after the themes are disabled and let me know if the problem persists?

**Comment by NateWr** [comment]
I thought this sounded familiar! I think this has been addressed for 3.2.1: https://github.com/pkp/pkp-lib/issues/5617.
