### ISSUE TITLE
Simplify use of journal title and logo in theme header templates

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5917]
**Describe the problem you would like to solve**
The theme templates use a complex mix of variables, such as `displayPageHeaderLogo` and `displayPageHeaderTitle`, to determine when to display a logo or the journal title in the header. These variables refer to obsolete features from OJS 2.x and they are not consistently set between the site and context level, which led to #5789.

This is unnecessarily complicated for deciding whether to show a logo or journal title.

**Describe the solution you'd like**
The templates should receive a variable, such as `$logo`, which is `null` or an assoc array with the url and alt text. They can then decide what they want the display logic to be:

```
{if $logo}
  <img ...>
{else}
  <a ...>...</a>
{/if}
```

This is simpler and will work consistently across the site and context levels.

**Who is asking for this feature?**
Just me.

**Additional information**
This is a more substantial refactor to address #5789 which should go into a major release (3.x).

**Comment by Vitaliy-1** [comment]
@NateWr, am I understanding this right that on the site level `getLocalizedPageHeaderTitle()` returns image first or title if the latter is absent. If yes, why the assignment of the image is duplicated here: https://github.com/pkp/ojs/blob/a896e727b355a924ebd00f2f1db9fd51bfc83855/classes/template/TemplateManager.inc.php#L88? Or does it cover some circumstances that I'm not aware of?

And the second question regarding this line: https://github.com/pkp/pkp-lib/blob/4a6178abcd77e73fcaf27981fb8868b1ff725560/templates/frontend/components/header.tpl#L53
Can you clarify when we need additional checks if `$displayPageHeaderLogo` is array? As I understand it can be null or array,  so the first check should be enough, shouldn't it?

**Comment by NateWr** [comment]
> If yes, why the assignment of the image is duplicated 

I think this probably refers to some outdated use-cases from OJS 2.x. I think we can get rid of both variables completely.

> Can you clarify when we need additional checks if `$displayPageHeaderLogo` is array?

Probably at one point in time it could be other things, but I don't think the check is needed any longer.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib master: https://github.com/pkp/pkp-lib/pull/6388
OJS master: https://github.com/pkp/ojs/pull/2924
OMP master: https://github.com/pkp/omp/pull/887
OPS master: https://github.com/pkp/ops/pull/87

**Comment by NateWr** [comment]
All merged, thanks @Vitaliy-1!

**Comment by efcjunior** [comment]
I upgraed ojs from 2 to 3.4 but this code changed is not there.

**Comment by asmecher** [comment]
@efcjunior, it's probably been rewritten since this merge. If you have a specific question, I'd suggest posting on our support forum: https://forum.pkp.sfu.ca

**Comment by efcjunior** [comment]
It is okay. I can not use title and logo together. But if this is a
business rule, then it is correct.
