### ISSUE TITLE
I cant see my administrator site after update from 3.1 to 3.2.0-3

### ISSUE THREAD

**Issue by miguel-obando-s4e** [pkp/pkp-lib#5919]
I updated my OJS with the help of this fix: https://github.com/pkp/pkp-lib/issues/5626 
 but now i am unable to see my administrator site. Can anyone help me? i also tried to delete the cache but i am unable to see the option for the same reason.  I attach an image about how the page stay

![Uploading js error.jpg…]()

 

**What application are you using?**
OJS 3.2.0-3

**Inspector logs**

[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/notosans/v9/o-0NIpQlx3QUlC5A4PNjXhFVZNyB.woff2
build.js?v=3.2.0.3:14 TypeError: Cannot read property 'itemsMax' of undefined
    at Li.eval (eval at Hu (build.js?v=3.2.0.3:14), <anonymous>:3:159)
    at Li.e._render (build.js?v=3.2.0.3:14)
    at Li.i (build.js?v=3.2.0.3:14)
    at ri.get (build.js?v=3.2.0.3:14)
    at new ri (build.js?v=3.2.0.3:14)
    at In (build.js?v=3.2.0.3:14)
    at Li.$mount (build.js?v=3.2.0.3:14)
    at Li.$mount (build.js?v=3.2.0.3:14)
    at Li.e._init (build.js?v=3.2.0.3:14)
    at new Li (build.js?v=3.2.0.3:14)
ot @ build.js?v=3.2.0.3:14
submissions:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/notosans/v9/o-0IIpQlx3QUlC5A4PNr5TRA.woff2
iframe.js:246 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0
pageHeaderLogoImage_es_ES.png:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load SourceMap: Could not load content for chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Server logs**

[logs from server.txt](https://github.com/pkp/pkp-lib/files/4683615/logs.from.server.txt)

**Comment by miguel-obando-s4e** [comment]
![js error](https://user-images.githubusercontent.com/65356742/82925675-0a751e80-9f4c-11ea-8c71-b397fb838222.jpg)

**Comment by asmecher** [comment]
@miguel-obando-s4e, are you sure you're using OJS 3.2.0-4? That version hasn't been released yet.

**Comment by miguel-obando-s4e** [comment]
My bad 3.2.0-3

**Comment by asmecher** [comment]
@miguel-obando-s4e, have you checked your PHP error log? (I only see your web server's access log attached to this issue.)

**Comment by miguel-obando-s4e** [comment]
How can i see or activate the php logs on OJS ? Or is this activated by default? if this is the case php didn't create any log error

**Comment by asmecher** [comment]
@miguel-obando-s4e, see https://forum.pkp.sfu.ca/t/how-do-i-find-my-php-error-log/29374 for information on finding your PHP error log. Would you mind moving this question over to our support forum (https://forum.pkp.sfu.ca)? We use git issues for active development, and the support forum for general support.

**Comment by miguel-obando-s4e** [comment]
Hello @asmecher here is the post, please check it out 
https://forum.pkp.sfu.ca/t/i-cant-see-my-administrator-site-after-update-from-3-1-to-3-2-0-3/60865
