### ISSUE TITLE
Native ImportExport Plugin: Importing a localized publication causes an error

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5920]
**Describe the bug**
Importing a localized publication causes a 500 server error: `getLocale` function undefined.

See also https://forum.pkp.sfu.ca/t/error-500-on-trying-to-import-issues-articles-native-xml-plugin/60797

**Comment by defstat** [comment]
@asmecher 

**PR**
[pkp-lib]: #5921

**Comment by asmecher** [comment]
Users encountering this problem in OJS 3.2.0-0 to OJS 3.2.0-3 can resolve the issue by applying this change in the `lib/pkp` subdirectory: https://github.com/pkp/pkp-lib/pull/5921/files

**Comment by defstat** [comment]
@asmecher  #5921 merged.

**Comment by asmecher** [comment]
Closing, thanks!
