### ISSUE TITLE
PostgreSQL 12 not properly supported

### ISSUE THREAD

**Issue by tgc** [pkp/pkp-lib#5923]
**Describe the bug**
The bundled version of ADOdb has a bug which causes notices to be generated when the database is PostgreSQL 12.

**To Reproduce**
Do anything that touches the database, e.g. php tools/upgrade.php upgrade
The output will be full of errors like this:
```
PKP-Database-Logger 1588586280,8606: ==> SQL => SELECT d.adnum as num, d.adsrc as def from pg_attrdef d, pg_class c where d.adrelid=c.oid and c.relname='users' order by d.adnum
PHP Notice:  Undefined offset: 1 in /srv/ojs/ojs3-eval/webroot/lib/pkp/lib/vendor/adodb/adodb-php/drivers/adodb-postgres64.inc.php on line 595
```
**What application are you using?**
OJS 3.2.0-3

**Additional information**
The fix is to either upgrade ADOdb or cherry-pick this commit to the current version used:
https://github.com/ADOdb/ADOdb/commit/a4876f100602c2ce4760bb72d3050f73387adcca

**Comment by asmecher** [comment]
Thanks for reporting (and tracking down the solution) -- I'll see if we can bump ADODB from 5.20.14 to 5.20.17 (plus our modifications, managed in https://github.com/ADOdb/ADOdb/compare/v5.20.17...asmecher:v5.20.17-mods). Note that longer-term, we're moving away from ADODB; see https://github.com/pkp/pkp-lib/issues/2493.

**Comment by asmecher** [comment]
Tests passed; merged: https://github.com/pkp/pkp-lib/pull/5927
