### ISSUE TITLE
[OPS] Editorial Statistics "Active Submissions" don't match actual number

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5933]
**Describe the bug**
I currently have 7 active preprints:

![Sem Título-1](https://user-images.githubusercontent.com/4059679/83179378-58c72080-a0f8-11ea-9eeb-02063201be94.png)

However, the number of "Active Submissions" in the Editorial Statistics section say 23:

![image](https://user-images.githubusercontent.com/4059679/83179173-0554d280-a0f8-11ea-885b-e6cad6016f5a.png)

**What application are you using?**
Open Preprint Systems 3.2.0.3

**Comment by defstat** [comment]
@alexxxmendonca can you run this 

`select stage_id, count(*) from submissions a
where a.status = 1
group by stage_id`

on your db and share the result?

Also can you confirm the numbers that you see today on both the Dashboard and the Stats page?

**Comment by alexxxmendonca** [comment]
Hi @defstat 

This was the result:

Bom dia, 

Segue o resultado do comando:

```
MariaDB [preprints_scielo_org]> select stage_id, count(*) from submissions a where a.status = 1 group by stage_id;
+----------+----------+
| stage_id | count(*) |
+----------+----------+
|        1 |      172 |
|        5 |       39 |
+----------+----------+
2 rows in set (0.00 sec)

```

_Also can you confirm the numbers that you see today on both the Dashboard and the Stats->Editorial page?_

Dashboard: 

My Queue: 11
Active: 211

There is actually only **9** submissions active and on my queue if I count them manually.

Stats->Editorial page: 39

**Comment by defstat** [comment]
Thanks @alexxxmendonca .. To rule out a possible difference in interpretation, can you describe how are you counting the 9 active ones? I mean how are they tagged? Or is there another way that you consider them `Active`?

The result of the query and the `Stats->Editorial page` count seems to work, technically, as expected.

**Comment by alexxxmendonca** [comment]
Hi @defstat 

I am counting them manually, one by one. There are only 9 in both tabs (My Queue and Active) so it's easy to count.

On the active tab, not only it shows 211 submissions but also multiple pages. But when I go to page 2, it's empty.

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**
[pkp-lib]: #6009
[OJS]:  pkp/ojs#2811
[OMP]: pkp/omp#839
[OPS]: pkp/ops#45

**Comment by asmecher** [comment]
Thanks, @defstat -- just a couple of minor comments. This is ready for merge when you've had a look at those, plus I think this could be cherry-picked to `stable-3_2_1` for release in OJS/OMP/OPS 3.2.1.

**Comment by defstat** [comment]
@asmecher 

**PRs**
**[3.2.1]**
[pkp-lib]: #6023
[OPS]: pkp/ops#46

**Comment by asmecher** [comment]
Thanks, all resolved!
