### ISSUE TITLE
Custom DOI field forces user error in publishing workflow. 

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#5936]
If a user has "custom DOI patterns" enabled in the DOI plugin (where you write in your DOI suffix on an article-by-article basis), the "identifiers step" in the publishing workflow will ask the user to include the whole prefix and suffix in the identifiers field. 

The prefix will always be the same, even if your suffix field is custom. Users shouldn't be asked to provide anything from PR.EFIX/ 

The other big issue here is that syntax for a DOI is 

prefix/suffix

The identifiers field will throw up an error if you input a slash, however. It _requires_ you to write a period instead. That would be 

prefix.suffix

https://www.dropbox.com/s/54legk2m9m96t7d/Screenshot%202020-05-29%2011.54.52.png?dl=0

But, prefix.suffix is not a DOI. So custom users are currently required to either skip this step and not submit a DOI or generate one that won't work. Because users have to **unpublish** to fix this, they may just skip it entirely.

**Comment by AhemNason** [comment]
@ctgraham has indicated to me that adding the prefix for a custom DOI is a desired thing, so really the copy here should be clear that they need to insert the whole DOI. The issue with the required "period" remains, however.

**Comment by ctgraham** [comment]
Manually keying the prefix is most plausible with entering DOIs for backissues acquired from an earlier publisher.  If we drop the validation of the entered prefix against the prefix specified in the DOI plugin, we are still protected by the registration agency from registering a bad DOI.  It would be unfortunate, though, to defer all validation onto the registration authority, though.

**Comment by AhemNason** [comment]
I didn't describe what's happening quite right. I'm going to make a new ticket that's more clear.
