### ISSUE TITLE
Investigate/improve file download icons when dealing with .docx

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#594]
DOCX files can be detected as ZIP (which is technically correct but not useful) e.g. on the UI/UX install. See if there's an easy way to force DOCX files to have more useful icons.

**Comment by NateWr** [comment]
Note: they've temporarily gone away and will need to be added back in after beta. We have a pretty good [selection](http://fortawesome.github.io/Font-Awesome/icons/) of icons at our disposal now.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1688

![selection_023](https://cloud.githubusercontent.com/assets/2306629/17457052/a27a9328-5be3-11e6-843c-d338c17058c7.png)

**Comment by asmecher** [comment]
Merged, thanks. I think you're OK in this case, but when using `anyhtml`, I'm extra careful to wrap user-supplied text in `htmlspecialchars` when building cell contents.

**Comment by asmecher** [comment]
Closing!
