### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by Kolesar** [pkp/pkp-lib#5941]
` $this->getCurrentPublication()` can be null and `$this->getCurrentPublication()->getData('urlPath')` will thrown error!

Quick solution is:
```
	function getBestId() {
		return $this->getCurrentPublication() && $this->getCurrentPublication()->getData('urlPath')
			? $this->getCurrentPublication()->getData('urlPath')
			: $this->getId();
	}
```

https://github.com/pkp/pkp-lib/blob/050afe9bb3a1e87157b8b2c7dccccd88d87aa2c0/classes/submission/PKPSubmission.inc.php#L54

**Comment by asmecher** [comment]
See https://github.com/pkp/pkp-lib/issues/5942#issuecomment-636222461.
