### ISSUE TITLE
Publication object DOI data not getting loaded

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5944]
**Describe the bug**
When a process like `CrossRefAutomaticRegistrationTask` is being executed as a `ScheduledTask` the `Publication` object is not loaded with its `pub-id::doi` data. That results to a failure during export. That does not happen when exporting the same submission from the user interface.

**To Reproduce**
See also https://forum.pkp.sfu.ca/t/ojs-3-2-0-2-crossref-xml-validation-error-for-article-already-registered-with-crossref/60198

**What application are you using?**
 OJS version 3.2.X

**Additional information**
It appears that the full life-circle of the request is not getting executed when within a ScheduledTask - so, for this case, the `HookRegistry::register('Publication::getProperties::fullProperties', array($this, 'modifyObjectProperties'));` from the `DOIPubIdPlugin` never gets called, and so the `pub-id::doi` is not added to the `Publication` object - which means that the respective doi export field remains empty.

**Comment by NateWr** [comment]
My first thought is that this is probably because the pub id plugins are not being loaded in the request. You will probably need to specially load them in the scheduled task.
