### ISSUE TITLE
Static Page

### ISSUE THREAD

**Issue by muhammadhamdani** [pkp/pkp-lib#5946]
**Describe the bug**
After Upgrade OJS . static pages list is empty. before not empty

**To Reproduce**
1. After Upgrade OJS Version from 3.1.2.4 to 3.2.0.3 
2. Click Settings -> Website
3. Click on Tabs Static Page
4. Static Page List empty
**What application are you using?**
 OJS 3.2.0.3

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
![image](https://user-images.githubusercontent.com/12347039/83365485-9070e980-a3d2-11ea-9b58-4f43959ef508.png)

**Comment by asmecher** [comment]
@muhammadhamdani, see https://forum.pkp.sfu.ca/t/static-pages-database-is-empty-after-upgrade-to-3-1-2-bug/53340 for details. In general, that support forum is the best place to post tech support questions.
