### ISSUE TITLE
Write integration tests for unpublishing an issue

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5948]
In #5837 @defstat identified cases where the submission, publication and issue status can fall out of sync. Integration tests should be written to ensure there are no future regressions in these cases.

Tests should be written to check:
- [ ] Correct submission and publication statuses when issue is unpublished.
- [x] Correct submission and publication statuses when an issue is published, unpublished and the republished.
- [x] Correct submission and publication statuses when submission removed from a published issue from the issue grid.
- [x] Correct issue table of contents in each of these cases.

**Comment by bozana** [comment]
Hi @NateWr, I've taken a look how the submissions and publications work now in OJS and without taking a look how the tests are currently written (and thus what does this may imply) yet: 
Do we really need both of these:

- Correct submission and publication statuses when issue is unpublished.
- Correct submission and publication statuses when an issue is published, unpublished and the republished.

Wouldn't it be enough to just test unpublishing and publishing (the order depending on the initial situation) of the issue? :thinking:
Or should maybe also unpublishing and publishing of the publication be covered?
Also, should this be covered too:

> ...where a submission has two publications and each one is assigned to a different issue. Not ideal but technically possible. In such cases, the current logic will ensure that unpublishing an issue won't unpublish the submission if its published in another published issue.

Thanks!

**Comment by NateWr** [comment]
In theory it shouldn't need testing, but I'd like to test the full process of publish -> unpublish -> republish to make sure that no submissions are accidentally dropped in the process. That's because publications need a special status, `STATUS_SCHEDULED`, to be published when an issue is published. So if during the unpublish process a publication gets set to the wrong status or something, it's possible that it wouldn't be republished when the issue is republished.

> Or should maybe also unpublishing and publishing of the publication be covered?

This should be covered in the existing tests: https://github.com/pkp/ojs/blob/master/cypress/tests/data/60-content/AmwandengaSubmission.spec.js#L180-L204

> where a submission has two publications and each one is assigned to a different issue.

Let's leave it for now. I think that it's a very unlikely use-case and, given all of the implications that would have for depositors, probably one that we want to discourage.

**Comment by bozana** [comment]
PR: https://github.com/pkp/ojs/pull/2995
@NateWr, could you please take a look?
