### ISSUE TITLE
Refine file upload -> metadata entry process for single-file case

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#595]
For cases where a single file is uploaded for a submission (common for OJS articles), review and streamline the submission process.

- Review the prompts on file uploads to make sure they make sense (e.g. suggested file title)
- Consider assuming that the file upload is the submission title in this case. Provide the single file's name as a default for the submission title in the metadata form, if it feels intuitive.

**Comment by NateWr** [comment]
For the beta I just did a really rough re-skin of the plupload's all-in-one component. But I'd really like to work out a better single file upload pattern in general, so feel free to assign this one to me. I've worked with the plupload API before and it's pretty handy.

**Comment by NateWr** [comment]
Closing this as I think we covered this in other issues. We now generate a title from the uploaded file, and we have a more straightforward single file upload control, and we cleaned up the metadata.
