### ISSUE TITLE
Can't download ojs from site

### ISSUE THREAD

**Issue by suporte-sbcm** [pkp/pkp-lib#5952]
Hi, I've always download OJS from this page and never have problem with this, but the last 2 weeks I can't anymore.

I wanna download the last OJS version.

I've tried from another computer and from another connection. But the problem stays the same.

It starts and it goes well until you expects to finish the download.
In Google Chrome acuse fail after a minute. In Edge simplily doens't finish.

**Comment by asmecher** [comment]
@suporte-sbcm, where specifically are you trying to download OJS from?

**Comment by suporte-sbcm** [comment]
@asmecher , from https://pkp.sfu.ca/ojs/ojs_download/

I sucessfully download one, but its 4 times bigger than the discribed on site.
Size: 163mb (but I'he expected 40mb)
Is this correct?

**Comment by asmecher** [comment]
@suporte-sbcm, your browser may have unzipped the `.tar.gz` file into a `.tar` file. What kind of file are you looking at?

**Comment by suporte-sbcm** [comment]
@asmecher , the last version of OJS. Thats what i want it.

The downloads that do not corrupted are with this extensions .tar.gz and .tar.gz.tar, but the two of them are 163mb.

**Comment by asmecher** [comment]
@suporte-sbcm, I've just retried the OJS 3.2.0-3 download and it's ~40MB as expected and compares as identical with the version I generated on my local machine as part of the release process.
```
$ wget "http://pkp.sfu.ca/ojs/download/ojs-3.2.0-3.tar.gz"
--2020-06-01 12:10:00--  http://pkp.sfu.ca/ojs/download/ojs-3.2.0-3.tar.gz
Resolving pkp.sfu.ca (pkp.sfu.ca)... 204.187.13.80
Connecting to pkp.sfu.ca (pkp.sfu.ca)|204.187.13.80|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41545876 (40M) [application/x-tar]
Saving to: ‘ojs-3.2.0-3.tar.gz’

ojs-3.2.0-3.tar.gz                              100%[=======================================================================================================>]  39.62M  1.20MB/s    in 34s     

2020-06-01 12:10:34 (1.16 MB/s) - ‘ojs-3.2.0-3.tar.gz’ saved [41545876/41545876]

$ diff ojs-3.2.0-3.tar.gz ~/git/distrib/ojs/ojs-3.2.0-3.tar.gz 
$
```

**Comment by suporte-sbcm** [comment]
@asmecher , ok.
I will try to check what is happening. 
I installed wget on my windows and tried with it.
The download connetion doesn't stay stable for all process, it loses stats of mb/s.
But completed with this size 39,62Mb (not corrupted).
Do you think it is ok to use it?

C:\Users\suporte\Downloads>wget "http://pkp.sfu.ca/ojs/download/ojs-3.2.0-3.tar.gz"
--2020-06-01 16:50:13--  http://pkp.sfu.ca/ojs/download/ojs-3.2.0-3.tar.gz
Resolving pkp.sfu.ca (pkp.sfu.ca)... 204.187.13.80
Connecting to pkp.sfu.ca (pkp.sfu.ca)|204.187.13.80|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41545876 (40M) [application/x-tar]
Saving to: 'ojs-3.2.0-3.tar.gz'

ojs-3.2.0-3.tar.gz            100%[=================================================>]  39,62M  5,83MB/s    in 2m 8s

2020-06-01 16:52:21 (318 KB/s) - 'ojs-3.2.0-3.tar.gz' saved [41545876/41545876]

**Comment by asmecher** [comment]
@suporte-sbcm, yes, it should be!

**Comment by suporte-sbcm** [comment]
@asmecher ,great!
Thanks a lot!
