### ISSUE TITLE
Issue published notification email should include table of contents

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5953]
**Describe the problem you would like to solve**
The notification email that can be sent when an issue is published is not as useful as it could be. 

**Describe the solution you'd like**
The email should include full issue details including the table of contents, with links to each item in the issue.

**Who is asking for this feature?**
Community partners and publishing services passing on requests from journal managers.

**Additional information**
Pitt has a plugin that does this, mentioned in [this comment](https://github.com/pkp/pkp-lib/issues/4746#issuecomment-637040203):

> In the near term, for sending the TOC with published issues, we recently wrote a plugin to embed this. It needs a functional review, but should be nearly good to go:
https://github.com/ulsdevteam/pkp-emailIssueToc

**PRs**
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3952

**Comment by ctgraham** [comment]
Plausible implementation:
Abstract `IssueHandler::_setupIssueTemplate()` to a static method, based on input of a user, issue, and showToc flag:
https://github.com/pkp/ojs/blob/a901ba484ed4d7976c7617f27e8dfa6decb1541c/pages/issue/IssueHandler.inc.php#L270-L385

Have the `NotificationManager::getNotificationMessage()` call this static method to populate the template here:
https://github.com/pkp/ojs/blob/a901ba484ed4d7976c7617f27e8dfa6decb1541c/classes/notification/NotificationManager.inc.php#L57-L58

Then embed the templated result, as per example:
https://github.com/ulsdevteam/pkp-emailIssueToc/blob/6b7f73f3d5092c83acb7aca453c89a0f162921f2/emailIssueTocPlugin.inc.php#L132-L133

**Comment by NateWr** [comment]
@ctgraham have you not run into layout problems when using the `issue_toc.tpl` as-is? As far as I'm aware it uses floats and a bit of positioning, and these parts of HTML/CSS are often not supported in email clients. I'd love to get a forward of an example email to see what it looks like, but my sense is that we'll need a separate HTML template designed for emails. ([This guide](https://www.smashingmagazine.com/2017/01/introduction-building-sending-html-email-for-web-developers/#building-html-email-templates) includes a helpful overview of the awful state of email client renderers.)

In terms of refactoring `IssueHandler::_setupIssueTemplate()`, I'd love to see that method broken up into a few different methods (maybe in the `IssueService` class), which aren't tied so closely to the template. For example, the need to get submissions broken down by section and to determine subscription access would probably be useful elsewhere if they weren't tied to the template prep.

Otherwise this looks good! :+1:

**Comment by ctgraham** [comment]
True, it is not pretty without any CSS, but it also seems a pity to have to re-template a component when we want to use it in email, but it would improve the appearance.

Sample sent.

**Comment by NateWr** [comment]
Ah, I see! So you're using the HTML but not the CSS. Since the default template uses `<ul>` this kind of works out. It seems like list support in emails is [not too bad](https://www.litmus.com/blog/the-ultimate-guide-to-bulleted-lists-in-html-email/).

![email-gmail](https://user-images.githubusercontent.com/2306629/87651941-7b1a0980-c74b-11ea-8de5-3077bad8a586.png)

This probably won't work out as well with themes that do not use list elements ([classic](https://github.com/pkp/classic/blob/master/templates/frontend/objects/issue_toc.tpl), [bootstrap3](https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/objects/issue_toc.tpl)). And I suspect if a journal is using cover images it will get messier.

Are the links to the galleys important to you? If not, I think it would be easy to draft up a simple template that was a stripped back version of this: just a list of titles/authors with the title linked.

I mention the galley links because there's quite a bit of complex logic around whether or not the user has access to it. That probably shouldn't be part of the emails, since a journal wants the user to click through and see the sign-up/subscription prompt.

**Comment by amandastevens** [comment]
There is also [an open issue](https://github.com/pkp/pkp-lib/issues/3646) to use the PUBLISH_NOTIFY template instead of the generic NOTIFICATION template when a new issue is published. Is it possible that the PUBLISH_NOTIFY template will be used or is it better to add the publication information to the NOTIFICATION template? If the PUBLISH_NOTIFY template will not be used, I suggest we remove it from OJS to reduce confusion among users who think the template is used for new issue published notifications.

**Comment by NateWr** [comment]
Yes, we should use the `PUBLISH_NOTIFY` template. The `NOTIFiCATION` template can't be changed because it is a generic template used for a lot of different cases.

**Comment by librariam** [comment]
+1 from a PKP|PS journal that would like to display the ToC in the new issue notification

**Comment by mhvezina** [comment]
Upvote

**Comment by touhidurabir** [comment]
@asmecher forgot to tag you , PRs to review at https://github.com/pkp/pkp-lib/issues/5953#issue-629011818

**Comment by asmecher** [comment]
Merged -- thanks, @touhidurabir!

**Comment by mirthquake** [comment]
Just looking to check whether the functionality of the pkp-emailIssueToc plugin has indeed been merged with the main application in v3.5. I ask since I just looked at the contents of the Issue Published Notify email template under Manage Emails in v3.5.0.3 (just upgraded from v3.3.0.8), and it doesn't seem to include a table of contents:

Readers:

{$contextName} has just published its latest issue at {$contextUrl}. We invite you to review the Table of Contents here and then visit our web site to review articles and items of interest.

Thanks for the continuing interest in our work,
{$signature}

**Comment by touhidurabir** [comment]
Hi @reaganch , it should look like [this](https://github.com/pkp/ojs/pull/3952#discussion_r1280516050) .

**Comment by mirthquake** [comment]
@touhidurabir - Thanks for your response. Are you saying the email will include the table of contents despite the Issue Published Notify email template looking like what I described in my last message? If yes, that seems rather confusing.

**Comment by touhidurabir** [comment]
@reaganch yes thats how it should look , the mail content thay have you have describe does not match with what it should be . Wondering if there is any issue with upgrade (as you have mentioned of upgrading from 3.3 to 3.5) . Also there is a mention of a plugin `pkp-emailIssueToc` so wondering if that has modified the mail content or something like that .

**Comment by ctgraham** [comment]
The `pkp-emailIssueToc` plugin doesn't modify any email templates in the database; rather it hijacks the email sending mechanism and modifies the output in memory.

@reaganch , here is the updated email template you would expect to see:
https://github.com/pkp/ojs/blob/bcd106ddbcd03aaeb5ec7b289d8255b8e1ebe557/locale/en/emails.po#L92-L101

**Comment by mirthquake** [comment]
Gosh! That's weird. I can definitely see the following in the `locale/en/emails.po` file of the new installation:

```
msgid "emails.issuePublishNotify.subject"
msgstr "Just published: {$issueIdentification} of {$contextName}"

msgid "emails.issuePublishNotify.body"
msgstr ""
"<p>Dear {$recipientName},</p>"
"<p>We are pleased to announce the publication of <a href=\"{$issueUrl}\">{$issueIdentification}</a> of {$contextName}. "
" We invite you to read and share this work with your scholarly community.</p>"
"<p>Many thanks to our authors, reviewers, and editors for their valuable contributions, "
"and to our readers for your continued interest.</p>"
"<div>{$issueToc}</div>"
"<p>Thank you,</p>"
"{$signature}"
```

Nevertheless, the template visible on the website is the same as what I'd mentioned above. Do you think this implies that the upgrade might have been bungled somehow? Does this point to an issue with the database upgrade, you reckon? Would you be able to suggest the right steps to troubleshoot this please?

**Comment by ctgraham** [comment]
Email templates are loaded from the .po files to the database.  This would have been done initially when you installed OJS, and what you see in the website is what is loaded from the database.

If the upgrade did not overwrite the template in the database, you can manually update the template using the editor in the Email Templates tab.  Note that the escaped quotes are part of the .po file and should not appear in the editor, e.g.:
not
```
"<p>We are pleased to announce the publication of <a href=\"{$issueUrl}\">{$issueIdentification}</a> of {$contextName}. "
```
but
```
<p>We are pleased to announce the publication of <a href="{$issueUrl}">{$issueIdentification}</a> of {$contextName}. 
```
