### ISSUE TITLE
Possible to circumvent author requirement in UI

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#5956]
In the publishing workflow, authors are required. However, if you: 

1. unpublish an article
2. refresh your browser window
3. delete all authors from author metadata
4. save metadata and republish

It's possible to publish material without an author. This, in turn, breaks themes in a weird way. This is what it looks like in default. 

![screenshot](https://www.dropbox.com/s/ozgbrybciz5f5l8/Screenshot%202020-06-02%2011.47.24.png?raw=1)

I suspect this is an oversight and a bug, but, also, worth suggesting that:

Editors either need to have some ability to declare empty author metadata in the publishing workflow (thereby removing the need for section-based ommissions [https://github.com/pkp/pkp-lib/issues/5955](https://github.com/pkp/pkp-lib/issues/5955)), or they shouldn't be able to remove all authors in a way that breaks citations, exports, article landing pages, and ToCs in such an unsupported way.

**Comment by NateWr** [comment]
It should not be possible to publish with no contributor records. That should be pretty easy to add as a pre-publish check. It's probably a good idea to backport this change to 3.2.0-x, so I've assigned it to that milestone.

**Comment by NateWr** [comment]
Ok, based on discussion in #5955 I'm pulling this off as a pre-publish requirement. I'd like to consolidate this issue with that one since the way we handle this will depend on our decision there.
