### ISSUE TITLE
[OPS] Allow Authors to update "Relation" field

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5957]
**Describe the problem you would like to solve**
Currently, authors are not allowed to update the "Relation" field, which indicated whether a preprint has been already submitted to a journal or has been published elsewhere in a Version of Record (VoR). 
This makes it harder for Admins, since it's not always clearly stated in the manuscript or in the "Comments to the Moderator" area whether this submission was already submitted to a journal. Admins pretty much have to **assume** the manuscript hasn't been submitted to any journal, but that is a complete guess based on lack of evidence proving otherwise.

**Describe the solution you'd like**
It would be good if authors themselves could inform that at the end of the submission process and let this option open for update for both Authors and Admin even after the preprint has been posted. As Server runners, we do want Authors to be able to update their preprint records with the DOI number. Server runners don't always know the outcome of a preprint, but their authors most certainly do and could be willing to update the record to point to the VoR.

**Who is asking for this feature?**
Server Admins and Authors.

![image](https://user-images.githubusercontent.com/4059679/83545271-5ccab800-a4d5-11ea-9ab8-914b0841dc33.png)

**Comment by alexxxmendonca** [comment]
An update to this: authors are mistakenly creating new versions of the preprint and replacing the PDF file for the version of record. This results in unnecessary new versions of the preprints while all they had to do was update the "Relations" field with the DOI of the Version of Record.

**Comment by NateWr** [comment]
Confirmed that this is not available from the AuthorDashboard, even if the author has permission to self-publish.

**Comment by willinsky** [comment]
I think calling the button “Standing” will make far more sense to authors than “Relations” (although I recognize the Dublin Core aspect to “relations”). There is also a fourth category "Preprint has been accepted for publication" which would open a box for the title of the journal. This information is of interest to readers, as it reveals the state (or standing) of the preprint, and I assume we would display the latter two options (as well as my addition) on the article landing page.

**Comment by ajnyga** [comment]
The old default was that an author was able to change the relation status if she was allowed to publish (which is defined by screening plugins on the server).

The new default in the pr below is now that an author can always edit the relation status of her own submission regardless of whether she can publish by herself.

pr: https://github.com/pkp/ops/pull/68

**Comment by asmecher** [comment]
Merged https://github.com/pkp/ops/pull/68 -- thanks, @ajnyga (and all)!
