### ISSUE TITLE
enabling crossrefReferenceLinking (even master branch) makes doi disappear

### ISSUE THREAD

**Issue by bricas** [pkp/pkp-lib#5961]
OJS 3.2.0-3

I've been trying to track down why our DOIs weren't showing up in the templates. I found out that having the crossrefReferenceLinking plugin enabled makes them disappear. 

I thought perhaps our plugin was just outdated, so i grabbed the master branch, but there was no change.

Found this note on the forum saying the same thing: https://forum.pkp.sfu.ca/t/doi-dissapear-after-installing-crossrefreferencelinking/60420

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**
[OJS]: pkp/ojs#2792
[OPS]: pkp/ops#39

**Comment by asmecher** [comment]
@defstat, can you check that this won't cause a regression in https://github.com/pkp/pkp-lib/issues/5474?

**Comment by defstat** [comment]
@asmecher, following the description of #5474, I tried to `Mark registered` a submission using the `CrossRefExportPlugin`. The submission is marked and the `crossref::registeredDoi` and `crossref::status` data are added to the `submission_settings` table. 

I also tried the same for `medra` and `doaj` plugins. 

Do I have to check anything else regarding #5474?

**Comment by asmecher** [comment]
@defstat, thanks for checking -- that should do it -- and I like that we're landing on an existing pattern with `addToSchema`. Please go ahead and merge, and close the two related issues.

**Comment by defstat** [comment]
@asmecher everything merged. Ported to 3.2.0 and 3.2.1 also (along with master branch)

Closing this and #5944 for now

**Comment by asmecher** [comment]
Excellent, thanks, @defstat!
