### ISSUE TITLE
Notification when author creates a version

### ISSUE THREAD

**Issue by diegoabadan** [pkp/pkp-lib#5964]
**Describe the problem you would like to solve**
When an author creates a version of your preprint, there is no notification in "Tasks"

**Describe the solution you'd like**
A notification would be created, allowing the Editor / Moderator to click and view a new version of submission.

**Who is asking for this feature?**
Server Admins

**Additional information**
Scielo wants this feature on its preprint server. We thought that it could ideally be part of OPS (and OJS), and not part of a plugin.

If they agree, we can send a PR.

**Comment by asmecher** [comment]
Yes, I think a PR would be welcome on this, thanks!

**Comment by asmecher** [comment]
https://github.com/pkp/pkp-lib/pull/6020 is a patch for the `stable-3_2_1` branch -- I'll leave that open for the moment.

@JhonathanLepidus, reviewing this again, I think it might need tweaking around who receives the notifications. I would expect the users assigned to the submission to receive notifications, but it looks like all managerial users are currently coded to be notified. For large installations that receive a lot of submissions, it might cause too much noise for managing editors.

**Comment by JhonathanLepidus** [comment]
@asmecher , we added another commit that modifies the notification to be sent only to the users assigned to the submission. You could check it in the PR #6020

**Comment by asmecher** [comment]
Thanks, @JhonathanLepidus, could you send that change in as a PR against `master`?

**Comment by JhonathanLepidus** [comment]
I just sent it: #6025 

You could merge only the last commit (that modifies the notification) because the other commits were already merged in a previous PR (#5983 )

**Comment by asmecher** [comment]
Thanks, I merged the last commit to `master`: https://github.com/pkp/pkp-lib/commit/df5d56b870b56e6d0ce0c8d88a6f413a67eba16b

**Comment by asmecher** [comment]
The `master` branch should now have all the relevant changes in, but `stable-3_2_1` does not (I'm just finishing the release of `3.2.1-0`). I'll leave https://github.com/pkp/pkp-lib/pull/6020 for `3.2.1-1` (and have moved this issue to that milestone). Thanks, @JhonathanLepidus!

**Comment by asmecher** [comment]
Merged https://github.com/pkp/pkp-lib/pull/6020 to `stable-3_2_1` for release in 3.2.1-2 -- thanks, all!
