### ISSUE TITLE
SQL error on 3.2.0->3.2.1RC upgrade

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5967]
Attempting an upgrade from 3.2.0 to 3.2.1RC and I get the following error (@ajnyga, @asmecher thinks it may be due to a recent commit of yours, will let him elaborate if necessary): 

```
[pre-install]
[load: upgrade.xml]
[version: 3.2.1.0]
[code: Installer Installer::checkPhpVersion]
[data: dbscripts/xml/upgrade/3.2.1_preupdate_subeditor_categories.xml]
ERROR: Upgrade failed: DB: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
```

**Comment by ajnyga** [comment]
Ah, a typo here: https://github.com/pkp/ojs/blob/master/dbscripts/xml/upgrade/3.2.1_preupdate_subeditor_categories.xml#L23

**Comment by ajnyga** [comment]
https://github.com/pkp/ojs/pull/2794

**Comment by ajnyga** [comment]
https://github.com/pkp/omp/pull/833

**Comment by ajnyga** [comment]
@asmecher was planning to do a pr for OPS as well, but forgot that I have write permissions to the repo, so by mistake I committed the change already. sorryyy...

**Comment by jmacgreg** [comment]
Confirming that this fixes the issue- thanks!

**Comment by asmecher** [comment]
Not a problem -- all committed, thanks!

**Comment by asmecher** [comment]
All cherry-picked to `stable-3_2_1`.

**Comment by asmecher** [comment]
Also rearranged the order of renames (column first, then table) to circumvent some kind of ADODB caching issue. (https://forum.pkp.sfu.ca/t/upgrade-from-ojs-2-8-4-1-to-3-2-1rc1/61045/3)
