### ISSUE TITLE
[OJS] Misleading information for authors regarding review process

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5970]
Please see: https://forum.pkp.sfu.ca/t/clearer-information-about-review-status/56577

Needs to check what is in fact a bug and what may fall into better phrasing.

**Comment by asmecher** [comment]
@alexxxmendonca, that was posted in 2019, and doesn't specify what version of OJS they're using; can you confirm that it's still an issue in the 3.2.x line of releases?

**Comment by alexxxmendonca** [comment]
I was asked by Nate to file it as an issue. 

I will check with the author of the original post.

**Comment by alexxxmendonca** [comment]
According to the original post's author, the problem seems to not be occuring anymore but another related problem was found and they will file it as a separate issue.

I will be closing this issue for the time being.
