### ISSUE TITLE
Medra Issue export does not validate against XSD

### ISSUE THREAD

**Issue by testman57** [pkp/pkp-lib#5971]
**Describe the bug**
In the mEDRA Export/Registration Plugin, Issues tab, when trying to export the XML (or trying to register) with the Validation checkbox checked, the export/registration fails due to a bad sequence of RelatedWork vs RelatedProduct. Indeed, all RelatedWork should appear first, and then all RelatedProduct, but the generated XML alternates both...

**What application are you using?**
 OJS version 3.2.0-3

**Comment by imartin-UPC** [comment]
In our case, we have the same problem, with the same version of OJS. The reported error is the following:

Element '{http://www.editeur.org/onix/DOIMetadata/2.0}RelatedWork': This element is not expected. Expected is ( {http://www.editeur.org/onix/DOIMetadata/2.0}RelatedProduct )

Is there any workaround we can apply?

**Comment by imartin-UPC** [comment]
Is there any progress on this issue?

**Comment by bozana** [comment]
Hi @imartin-UPC, I first now see this issue, so I will take a look... Can you just tell me what do you try to export, an article? And as work? Thanks!

**Comment by imartin-UPC** [comment]
Hi @bozana. Thanks for your interest. Articles are registered fine (as works). However, when I try to register a full issue of the journal, I get the error shown above.

**Comment by bozana** [comment]
PR: https://github.com/pkp/medra/pull/3 (include a commit for updating the copyright year)

**Comment by bozana** [comment]
Hi @imartin-UPC, here are the changes needed to fix the problem: https://github.com/pkp/medra/commit/4052477c794616892ec5331535bcd08e97e19eac
You could maybe create a diff and apply it as patch for your installation.
I will release the new plugin version and the release soon, that will be then available for 3.3.0.6 and coming 3.3.0.7 via the plugin gallery.

**Comment by imartin-UPC** [comment]
It worked like a charm. Thanks a lot!!!
