### ISSUE TITLE
Empty submission grids should not display.

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#598]
On the dashboard, submission grids without contents should not display. (Can this be done without a lot of overhead/complexity? If not, reconsider?)

**Comment by asmecher** [comment]
(OTOH, this can probably be best fixed by having the grid load, and if empty, self-destruct. This will be much more maintainable than informing the containing template file of whether or not it should load the grid.)

**Comment by jnugent** [comment]
Alec, could the grid handler return an empty JSON block if there were no submissions?   The URL In Div Handler wouldn't even need to know.  the fetchGrid method could just check and see if loadData did anything useful, probably.

**Comment by asmecher** [comment]
Yes, something like that.

**Comment by NateWr** [comment]
This could have some potentially weird side-effects if the behaviour is standardized across grids. Many grids are designed to be empty and have items added to them. If all three grids on the dashboard were empty the screen would be completely confusing.

On a more general note, I feel that this is UI logic that is not internal to the component, and so shouldn't be nested there. At the very least, the self-destruct mechanism should be an option passed in at the template level. But to be honest, the grid component is already overloaded with exceptions and special use-cases which make it an exceedingly complex and bulky chunk of code.

After the beta the dashboard is the first thing I want to tackle with a new approach that moves away from the grid. So I'd recommend just holding off on this for now.

**Comment by asmecher** [comment]
Makes sense, Nate. Agreed.

**Comment by asmecher** [comment]
Assigning to @NateWr -- dependent on his submission lists work.

**Comment by NateWr** [comment]
This should be obsolete once the new submissions lists are in place (#2163).
