### ISSUE TITLE
Filter submissions by assigned editor

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5982]
**Describe the problem you would like to solve**
Journal managers would like to see how many submissions are assigned to an editor and track what they are working on.

**Describe the solution you'd like**
A filter in the submissions list to filter by assigned editor.

**Who is asking for this feature?**
See https://github.com/pkp/pkp-lib/issues/2612#issuecomment-328014371, https://github.com/pkp/pkp-lib/issues/2612#issuecomment-328201605 and https://github.com/pkp/pkp-lib/issues/2612#issuecomment-386259242, https://github.com/pkp/pkp-lib/issues/4102. On the forum: [one](https://forum.pkp.sfu.ca/t/display-editors-assigned-on-list-of-articles/45726), [two](https://forum.pkp.sfu.ca/t/filter-by-editor/45717).

**Comment by thinkbulecount2** [comment]
PR: https://github.com/pkp/ui-library/pull/101

cc: @NateWr

**Comment by thinkbulecount2** [comment]
PR for pkp-lib: https://github.com/pkp/pkp-lib/pull/6040

cc @NateWr

**Comment by thinkbulecount2** [comment]
PR for OJS: https://github.com/pkp/ojs/pull/2823

**Comment by thinkbulecount2** [comment]
@NateWr The rebase went south so I just created a new branch fresh off of master. PR: https://github.com/pkp/pkp-lib/pull/6053

**Comment by NateWr** [comment]
All the PRs in one place:
https://github.com/pkp/pkp-lib/pull/6053
https://github.com/pkp/ui-library/pull/101

Tests:
https://github.com/pkp/ojs/pull/2830

**Comment by NateWr** [comment]
All merged! :tada:

**Comment by NateWr** [comment]
@amandastevens and @kaitlinnewson not sure if this is worth documenting but in v3.3 admins and journal managers will be able to filter the All Active list by the assigned editor.

(This is one of a few new filters that will be coming in v3.3.)
