### ISSUE TITLE
Suggested improvements for About this Publishing System page

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#5984]
**Describe the problem you would like to solve**

A standard footer for all themes contains a "Platform & Workflow by OJS/PKP" logo that leads to the About this Publishing System page, e.g. https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php/testdrive-journal/about/aboutThisPublishingSystem. The page contains a link to the PKP website and an image of OJS editorial workflow.

![image](https://user-images.githubusercontent.com/45104797/84311902-178c3300-ab32-11ea-89ca-ba7122bc2e92.png)

In my experience at PKP|PS, it is extremely common for authors to click on the OJS/PKP logo in the footer when they want to contact the journal editors. They then navigate to the PKP website, from there to contacts at the bottom and end messaging PKP|PS. We get these several times a week, it's one of our most popular emails to respond to.

**Describe the solution you'd like**
1) I suggest adding wording to clarify the separation between PKP and the journal. Something along the lines of `"If you want to contact the [Journal name], check the [About page = URL] for a list of contacts and contact them directly."`

2) I also suggest removing the image of the OJS workflow from this page. It outlines the workflow OJS can support, but can be misunderstood as the process followed by that specific journal, which is not always the case. It makes more sense for this image to be on the PKP website or Docs Hub.

**Who is asking for this feature?**

PKP|PS on behalf of authors who get confused about journal contacts.

**Comment by NateWr** [comment]
Agreed. It's time to deprecate this page. If we want to replace it that could go into the docs hub. @amandastevens and @kaitlinnewson what's your thoughts on this? Should we migrate this to the docs hub or just dump it in favour of better information that already exists?

**Comment by amandastevens** [comment]
I suppose we could add this flow chart to the start of the Editorial Workflow chapter in Learning OJS 3. I like the idea of having a visual representation of the workflow.

**Comment by NateWr** [comment]
I suppose this overlaps a bit between comms and DIG. I'll reach out to Marisa and see if she has any thoughts on what we want this link to do...

**Comment by kaitlinnewson** [comment]
As an FYI, we do currently have this image in the Instructors guide here at the bottom of the page, but perhaps it should be added in Learning OJS as well: https://docs.pkp.sfu.ca/instructor-guide/en/setup-workflow

**Comment by NateWr** [comment]
This is a quick dev task, but we need a decision to be taken about what to do so that we have a clear direction to take.

**Comment by amandastevens** [comment]
The DIG is working on updating the workflow diagram and it will be added to documentation. So we can remove it from this page and just make the addition suggested by Mariya above in point 1. 

Or the text could say, "This journal uses Open Journal Systems [version], which is open source journal management and publishing software developed, supported, and freely distributed by the Public Knowledge Project (PKP) under the GNU General Public License. Visit [PKP's website](https://pkp.sfu.ca/) to learn more about the software. Please contact the journal [About page = URL] directly with questions about the journal and submissions to the journal."

**Comment by NateWr** [comment]
Ok, we can make that change. But do we need this page at all? We can have the "Workflow By" image link to a PKP website rather than a stub page with just a couple of sentences.

**Comment by amandastevens** [comment]
Ah yes, that's true.  I hope that will not still lead authors to contact PKP about their submissions, but we can try it and see.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/6379
https://github.com/pkp/ojs/pull/2921
https://github.com/pkp/omp/pull/884
https://github.com/pkp/ops/pull/85

These pull requests remove the workflow diagram from OJS and update the page title and text in line with the recommendations above. Here it is on a journal.

![about-software](https://user-images.githubusercontent.com/2306629/100375854-5d688500-3006-11eb-963f-8f6211b1a245.png)

And here at the site-wide level, where there is no contact page to link to.

![about-software-site](https://user-images.githubusercontent.com/2306629/100375917-796c2680-3006-11eb-9e85-81e65e116035.png)

**Comment by NateWr** [comment]
Merged!

**Comment by amandastevens** [comment]
Thanks, Nate, this looks excellent!

**Comment by marcbria** [comment]
Great. I arrive to the conversation two years later. :-(

Any chance to reopen this discussion?
I asked because some editors compain about missing this diagram.

I don't know if it's because they were already used to seeing that diagram... or because redirecting to PKP's website sounds a bit like getting rid of responsibilities, but they prefer the diagram to be in their OJS than in an external website.

Personally I share the preference for a "self-contained" OJS and it also allows us to add some image to the interface, as text-only is quite austere.

But obviously, all this is not a problem and they are just preferences... 
Maybe it would be a question we could now ask Devika?
Or even a question that could be added to the next round of UI/UX testing?

Whether in OJS or in PKP's website, we need a diagram, so I opened a thread in #8939 discussing possible solutions to facilitate the maintenance and translation of this image.
