### ISSUE TITLE
Improve Arabic translation in Registration error message

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#5991]
A hosting client has brought to our attention that the translation in the error message from English to Arabic is a bit confusing and has resulted in a number of users being unable to successfully register to their journal.

Our client mentioned that while it does mention alphanumeric in Arabic but is not translated as clearly. They've provided improve the translation for the username and password

اسم المستخدم يجب ان يكون مكون من ثمانية رموز على الأقل وان تكون الرموز من الحروف أو الأرقام اللاتينية فقط

And the password:
 
كلمة المرور يجب ان تكون مكونة من ثمانية رموز على الأقل وان تكون الرموز من الحروف أو الأرقام اللاتينية فقط

**Comment by asmecher** [comment]
@pmangahis, could you ask them to submit that through Weblate?

**Comment by NateWr** [comment]
Just following up on this. Any luck getting this through weblate? Otherwise @vormia has provided some Arabic translations for us in the past and may be able to make this happen.

**Comment by pmangahis** [comment]
@NateWr they had a hard time navigating through Weblate. We ended up making the translation using the custom locale plugin for them on their installation.
