### ISSUE TITLE
pkp-native.xsd problem, submission status attribute should be required

### ISSUE THREAD

**Issue by jhennig** [pkp/pkp-lib#5992]
During an xml import into OJS 3.2.0.3. When the status attribute on the article element is omitted the submission will import successfully however it will not be displayed anywhere.  It will be lost.
The submissions.status field is set to 0 in the DB.  I believe the  status attribute for article (submissions) element  should at least be a required field in the plugins/importexport/native/pkp-native.xsd. This way the uploader doesn't lose the submission unless they actually set the status to 0.

I'm not sure what implications that has on OMP.

To Reproduce
1) Take a valid OJS XML import file.
2) Remove the Article status attribute.  Note that this still makes for a valid file
3) Upload

**What application are you using?**
 OJS  3.2.0.3

**Comment by defstat** [comment]
@jhennig thanks for spotting this.

Please check if the PR bellow fixes the issue.

**PR**
[PKP-LIB]: #6504
