### ISSUE TITLE
Upgrade OJS Version 3.2.0.3

### ISSUE THREAD

**Issue by rajeevrnt** [pkp/pkp-lib#5997]
Dear Friends

I am new to Git hub. I am requesting you to please share step by step guide "How to upgrade OJS Version 3.2.0.3"

**Comment by redukr** [comment]
if you need upgrade from OJS2 to OJS3 read this article  docs.pkp.sfu.ca/upgrading-ojs-2-to-3/en/upgrading-ojs

**Comment by asmecher** [comment]
@rajeevrnt, if that doesn't help, I'd suggest posting on our support forum (https://forum.pkp.sfu.ca) with any further questions; that's the best place to get support.
