### ISSUE TITLE
embedded images with spaces in original names are broken in HTML galleys

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#5999]
Reported in 3.1.2

If an editor uploads an HTML galley (not an XML galley using the conversion plugin), and they've included embedded images with spaces in their original filenames, such as e.g.  "Zichi HW Curfew Pass 2.jpg", the call to rawurlencode() here:

https://github.com/pkp/ojs/commit/a6633bcb6dd3da3bc54864aff4a3fd9f6f002f3c

converts the file name into: Zichi%20HW%20Curfew%20Pass%202\\.jpg

which is not matched in the preg further down.   If the rawurlencode() call is there for security reasons, perhaps there can be a second quick search to convert %20 into a single space character afterwards.

**Comment by asmecher** [comment]
@jnugent, I'm not sure I'm on the right track, but wouldn't it be a solution to properly encode the filenames in the image URLs in the HTML? Spaces [technically shouldn't be allowed](https://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space) in `href`s.

**Comment by jnugent** [comment]
@asmecher Sure, and I agree about spaces in URLs.  However, in this particular case we've got an installation that upgraded to OJS3 from 2.4.8, and they've got hundreds of HTML galleys with image URLs that would need changing, or manual intervention on our part (we can search and replace in the HTML, and then update the database original file names accordingly), but then also an educational component so it does not keep reoccurring.

**Comment by jnugent** [comment]
And also, this isn't really about a malformed URL.  Yes, the original filename is not semantically correct in the original HTML, but we're replacing it with a standardized link to a handler, so the generated HTML is clean and correct.  We just need to be a bit more forgiving on how we get there.

**Comment by asmecher** [comment]
Did the old install get modified to remove the `rawurlencode` or something? Doing some archaeology, it looks like the `rawurlencode` was introduced to OJS 2.2 via [Bugzilla #2977](http://wayback.archive-it.org/7100/20180508114220/https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=2977) (https://github.com/pkp/ojs/commit/dc49839188aee2f6a1d9f9e5f538c39dbb8ca77a).

**Comment by jnugent** [comment]
That's a good question.  This install was originally on one of the old lib-ojs servers, upgraded, and then moved to the new ones.  The old machines are decommissioned now so being able to find out is no longer possible unfortunately. 

If you are at all uncomfortable about replacing the %20 with spaces, that's fine - we can track this as a local customization for the install.   Just trying to think of situations where this conversion may break the preg_replace in other unexpected ways.  A plus sign, for example, would get converted to %2B and ampersands get converted to %26.  They also are not recommended in URLs, but people use them in file names and then insert them into the HTML they upload.  We see all sorts of weird behaviour.

**Comment by asmecher** [comment]
I suspect this was a customization before and should best be kept that way. If it's an issue with freshly-generated HTML, we can come back to it, but I think this is just old-data legacy.
