### ISSUE TITLE
Error "Could not instantiate mail function." interfering with Ajax calls

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#600]
I've talked about this with @asmecher before. But I'm more convinced now that this is the source of problems for several of our Ajax calls, when testing in an environment with no mail server.

Here are steps to reproduce on my fork using the `header_ui` branch, with what seems to be a pretty clear and reliable case:

1. Make sure you're running in a development environment with no email server configured.
2. Browse to *Dashboard > Issues* and create a test *Future Issue*.
3. Click on *Publish Issue* for this issue.

**What is expected to happen?**
The modal should close and the issue should be published.

**What actually happens?**
The modal never closes but the issue is published. You must hop over to published issues to see it.

**My theory**
The `Could not instantiate mail function.` error is getting printed to the screen, so the `ajax` call is not returning. As a result, the response handler in `RemoteActionConfirmationModalHandler.js` is not getting run.

If you take a look at the remoteAction parameter, it will tell you the URL where the remote action is being sent. It is `http://192.168.0.8/ojs/index.php/publicknowledge/$$$call$$$/grid/issues/future-issue-grid/publish-issue?issueId=3` (last integer changes based on issue). As far as I can tell, no `post` data is sent.

So I checked it out in Postman, which lets me fire off custom ajax requests and view the response. Submitting a `post` action to that URL returns `<h1>Could not instantiate mail function.</h1>`.

If I fire off the same request when logged out, it returns a properly formatted JSON string, `{"status":false,"content":"The current role does not have access to this operation.","elementId":"0"}`.

It seems to me that this email error is calling `exit` or `die` or otherwise killing the process early, and printing the error to the buffer, causing the response parser to fail and therefore breaking the modal handler.

I suspect this is connected to broken modal interactions for me in several places. It'd be great to get this sorted because it could fix a number of different problems I'm tracking.

**Comment by asmecher** [comment]
Nate, I'm using Firebug over here, which allows me to inspect the results of AJAX subrequests. If I see an action fail, it's often because a PHP-land error message wasn't formatted in JSON and thus caused problems.

I think we'll definitely have to address this eventually; as we start to deal with end-user troubleshooting it won't be practical to ask them to install Firebug and learn to use it in order to get an error message. We might need to go through the system and somehow get it to format responses in HTML or AJAX depending on how it's being invoked.

**Comment by NateWr** [comment]
The error is an exception that's being thrown at `/lib/vendor/phpmailer/phpmailer/class.phpmailer.php:1160`:

```
throw new phpmailerException($this->lang('instantiate'), self::STOP_CRITICAL);
```

I decided to look at how WordPress handles this, since they use PHP Mailer too. It looks like they have simply [wrapped the call](https://core.trac.wordpress.org/browser/tags/4.2.2/src/wp-includes/pluggable.php#L529) in a `Try {} Catch {}`.

I also noticed that we call on `fatalError()`, which is echoing the error wrapped in a `<h1>` tag. I wonder if we can bypass this, and just print the error to the standard error log. Since it's the mail function that failed, we probably don't need to kill everything and print a full stacktrace, right?

So we might get everything we need here to handle a development environment without a mail server by changing this code in [Mail.inc.php](https://github.com/pkp/pkp-lib/blob/master/classes/mail/Mail.inc.php#L497-L502):

```
if (!$mailer->Send()) {
	if (Config::getVar('debug', 'display_errors')) {
		fatalError($mailer->ErrorInfo);
	}
	return false;
}
```

To this code:

```
try {
	$mailer->Send();
	return true;
} catch (phpmailerException $e) {
	error_log($mailer->ErrorInfo);
	return false;
}
```

Or maybe `pkp-lib` already has a less-than-fatal error routine that can be run here?

**Comment by NateWr** [comment]
I tested this a bit this morning and it did seem to help -- although it just unearthed new layers of problems. :) But the email server problem is no longer blocking things.

**Comment by asmecher** [comment]
Nate, I like the try/catch solution you've proposed. Can you include it in your branch (if you haven't already) so it doesn't get forgotten?

**Comment by NateWr** [comment]
Done. Should I close this issue or do you prefer to wait until it's merged?

**Comment by asmecher** [comment]
Your preference. FYI, you can get git to close issues when commits are merged using commit messages. See: https://help.github.com/articles/closing-issues-via-commit-messages/
