### ISSUE TITLE
Undefined const SCHEMA_PUBLICATION during upgrade

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6000]
OJS 3.2.1 stable branch, didn't test master. 
(according to forum posts appears earlier)
PHP 7.4.6
`installed` should be set to `off` during the upgrade 

Tested with an upgrade from OJS 3.2.0-3. Cosmetic warning:
```
PHP Warning:  Use of undefined constant SCHEMA_PUBLICATION - assumed 'SCHEMA_PUBLICATION' (this will throw an Error in a future version of PHP) in /home/doc/OJS/testing/ojs-stable-3_2_1/lib/pkp/includes/functions.inc.php on line 224
```
It doesn't affect upgrade directly but, apparently, it may be changed to the error in one of the next PHP major releases, probably 7.5
.
The problem is that when `PublicationDAO` is initialized, the aforementioned const is not yet defined as `PKPSchemaService` isn't imported at that time.

**Comment by asmecher** [comment]
@Vitaliy-1, were you able to identify where the constant was used but not imported (i.e. which line of code)? Unfortunately the warning message doesn't include it.

**Comment by Vitaliy-1** [comment]
Yeah, it's not informative but putting something like:
```
if (!defined('SCHEMA_PUBLICATION')){
	import('lib.pkp.classes.services.PKPSchemaService');
}
```
before this return statement: https://github.com/pkp/ojs/blob/9cc0a567aecdaab0395277c4940ea0d6efdf0381/classes/plugins/PubObjectsExportPlugin.inc.php#L728
solves the issue.

**Comment by asmecher** [comment]
@Vitaliy-1, can you confirm whether https://github.com/pkp/pkp-lib/commit/5f0765fc8e41ffa8b6155e2121fe919c0643a42a resolves it for you?

**Comment by Vitaliy-1** [comment]
Yes, don't see this warning during a test upgrade anymore.

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1!
