### ISSUE TITLE
Redundant space under submission page's content

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6001]
OJS 3.2.1 stable branch. First appears in OJS 3.2.0.

Extra space occupies a part of the submissions page under the footer:
![screencapture-localhost-8000-index-php-psp-submissions-2020-06-16-15_25_02](https://user-images.githubusercontent.com/20665587/84773866-b2c75180-afe5-11ea-880f-49e59cfc43a7.png)

It's triggered by the styling applied to the element with class `.pkpListPanel__sidebar` here: https://github.com/pkp/ui-library/blob/a3cb759eecdcca96528ee0fc89c5d6cbc4b5bb7a/src/components/ListPanel/ListPanel.vue#L778

Tested with Google Chrome version 83.0.4103.61 and Firefox 77.0.1

**Comment by asmecher** [comment]
@Vitaliy-1, is this the same as https://forum.pkp.sfu.ca/t/a-problem-after-upgrading-the-ojs-3-2-01/59539/19?

**Comment by Vitaliy-1** [comment]
It looks like the same as in post 18 and appears as described in post 19 (appears despite the presence of queued submissions). 
It's purely layout problem and removing `width: 0` from `.pkpListPanel__sidebar` in the browser resolves it. But I'm not sure about other implications. I'm working with yesterday's copy of the stable 3.2.1 branch (and referenced ui-library).

**Comment by asmecher** [comment]
@NateWr / @israelcefrin, pinging you on this one as you worked on https://github.com/pkp/ui-library/pull/83.

**Comment by NateWr** [comment]
This is fixed in `master` as part of the UI refactor and will go into 3.3. Israel's fix might work if we wanted to backport a fix, but I am a little hesitant because I've never seen that approach and would need to investigate the implications.

**Comment by asmecher** [comment]
Agreed! Closing this one -- thanks, all.
