### ISSUE TITLE
Plugin Updates for OJS 3.2.1

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6004]
URL | Translations merged | Release (XML / submodule commit)
---|---|---
**Submodules**
https://github.com/pkp/browse | 2020-06-16 | OJS, OPS
https://github.com/pkp/makeSubmission | (no new) | (no new)
https://github.com/pkp/citationStyleLanguage | 2020-06-17 | OJS
https://github.com/pkp/customBlockManager | 2020-06-17 | OJS, OMP, OPS
https://github.com/pkp/googleAnalytics | 2020-06-17 | OJS, OMP, OPS
https://github.com/pkp/googleScholar | 2020-06-17 | OPS, OJS
https://github.com/asmecher/lensGalley | 2020-06-17 | OJS
https://github.com/pkp/orcidProfile | 2020-06-16 | OJS, OPS
https://github.com/pkp/pdfJsViewer | 2020-06-17 | OJS, OPS
https://github.com/pkp/staticPages | 2020-06-17 | OJS, OMP
https://github.com/pkp/tinymce | (no new) | (no new)
https://github.com/pkp/usageStats | 2020-06-17 | OJS, OMP, OPS
https://github.com/pkp/reviewReport | 2020-06-17 | OJS, OMP
**Plugin Gallery**
https://github.com/asmecher/hypothesis | 2020-06-17 | 2020-06-19
https://github.com/pkp/shibboleth | **NOT UPDATED FOR 3.2**
https://github.com/asmecher/backup | 2020-06-16 | 2020-06-19
https://github.com/asmecher/plagiarism | (no new) | (marked existing compatible)
https://github.com/pkp/coins | 2020-06-16 | 2020-06-19
https://github.com/pkp/quickSubmit | 2020-06-17 | 2020-06-19
https://github.com/pkp/piwik | 2020-06-17 | 2020-06-19
https://github.com/pkp/addThis | 2020-06-17 | 2020-06-19
https://github.com/asmecher/subscriptionSSO | 2020-06-17 | 2020-06-19
https://github.com/asmecher/customHeader/ | 2020-06-17 | 2020-06-19
https://github.com/pkp/customLocale/ | 2020-06-17 | 2020-06-19
https://github.com/pkp/jatsTemplate/ | (no new) | (marked existing compatible)
https://github.com/pkp/sword/ | 2020-06-16 | 2020-06-19
https://github.com/pkp/oaiJats/ | (no new) | (marked existing compatible)
https://github.com/NateWr/bootstrap3 | | 2020-06-24
https://github.com/pkp/classic | 2020-06-19 | 2020-06-19
https://github.com/pkp/healthSciences | 2020-06-19 | 2020-06-19
https://github.com/NateWr/defaultManuscript | | 2020-06-24
https://github.com/pkp/crossrefReferenceLinking | 2020-06-18 | 2020-06-19
https://github.com/pkp/immersion | 2020-06-19 | 2020-06-19
https://github.com/pkp/orcidProfile | 2020-06-16 | 2020-06-19
https://github.com/pkp/defaultTranslation | 2020-06-17 | 2020-06-19
https://github.com/pkp/paperbuzz | 2020-06-18 | 2020-06-19
https://github.com/pkp/registrationNotification | **NOT UPDATED FOR 3.2**
https://github.com/pkp/controlPublicFiles | 2020-06-17 | 2020-06-19
https://github.com/pkp/textEditorExtras | 2020-06-17 | 2020-06-19
https://github.com/pkp/swordServer | 2020-06-17 | 2020-06-19
https://github.com/pkp/returningAuthorScreening | (no new) | (marked existing compatible)
https://github.com/pkp/pragma | | 2020-06-24
https://github.com/pkp/texture | 2020-06-17 | (marked existing compatible)

**Comment by Vitaliy-1** [comment]
Immersion:
```
<release date="2020-06-19" version="1.0.5" md5="2d9315eeb98e759ea0e83f1c26c4bffb">
	<package>https://github.com/pkp/immersion/releases/download/1.0.5.0/immersion-1.0.5.tar.gz</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
		<version>3.2.0.1</version>
		<version>3.2.0.2</version>
		<version>3.2.0.3</version>
		<version>3.2.1.0</version>
	</compatibility>
	<certification type="official"/>
	<description>This release includes minor bugfixes</description>
</release>
```

Classic
```
<release date="2020-06-19" version="1.0.4.0" md5="c9945a4c6ca7b6e98ce5be8aa2639d44">
	<package>https://github.com/pkp/classic/releases/download/1.0.4/classic-1.0.4.tar.gz</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
		<version>3.2.0.1</version>
		<version>3.2.0.2</version>
		<version>3.2.0.3</version>
		<version>3.2.1.0</version>
	</compatibility>
	<certification type="official"/>
	<description>This update includes better contrast for some elements, support for catalog category page and minor bugfixes</description>
</release>
```

Health Sciences:
```
<release date="2020-06-19" version="1.0.7.0" md5="d89a9b246b11bd91f2e6b649b6f0d862">
	<package>https://github.com/pkp/healthSciences/releases/download/1.0.7.0/healthSciences-1.0.7.0.tar.gz</package>
	<compatibility application="ojs2">
		<version>3.2.0.0</version>
		<version>3.2.0.1</version>
		<version>3.2.0.2</version>
		<version>3.2.0.3</version>
		<version>3.2.1.0</version>
	</compatibility>
	<certification type="official"/>
	<description>This update contains fixes for small layout and javascript bugs, adds encoding of emails on the contact page with Smarty native plugin and includes localization files converted to Weblate</description>
</release>
```
As for the Pragma theme, Sophy is working on support for the catalog category page, which I would like to include in the release. Also, I don't see any breaking features in 3.2.1, so new themes are compatible with 3.2.0.

**Comment by asmecher** [comment]
@withanage, it looks like there is a validation problem in the Plugin Gallery XML related to lensGalleyBits:
```
pkp_docs/ojs/xml/plugins.xml:2712: element release: Schemas validity error : Element '{http://pkp.sfu.ca}release': This element is not expected. Expected is ( {http://pkp.sfu.ca}name ).
pkp_docs/ojs/xml/plugins.xml fails to validate
```
Could you review http://pkp.sfu.ca/ojs/xml/plugins.xml against http://pkp.sfu.ca/ojs/xml/plugins.xsd and make sure the missing data (name, homepage, etc) is filled in?

**Comment by asmecher** [comment]
@Vitaliy-1, added the information above, thanks!

**Comment by asmecher** [comment]
@NateWr, do we need new releases of `bootstrap3` and `defaultManuscript`, or is 3.2.1 compatible with existing releases?

**Comment by NateWr** [comment]
I'm not aware of any changes that would break compatibility but I haven't tested yet.

**Comment by NateWr** [comment]
Plugins.xml updated with new compatibility tag for defaultManuscript and new release for bootstrap3.

**Comment by NateWr** [comment]
Plugins.xml was updated with a new release for `pragma` that's compatible with all 3.2+ releases.

**Comment by asmecher** [comment]
AddThis needs a new release plus compatibility statement for OPS 3.2.1 after https://github.com/pkp/addThis/commit/4f1af46a2255f4e20eadc0720d9ad43081d0a00f!

**Comment by asmecher** [comment]
@jonasraoni confirms that the registration notification plugin is working with 3.2.1 and ready for a compatibility statement!
