### ISSUE TITLE
User roles can be passed to the browser as an object instead of array

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6007]
**Describe the bug**
The user roles are available globally in the browser as `pkp.currentUser.roles`. These should be an array, but in some cases can be an object. This leads to errors in JavaScript when it calls an array method.

![errors](https://user-images.githubusercontent.com/2306629/84871067-01bdc700-b078-11ea-817a-86bfcf819bc8.png)

The template manager calls `array_unique` on the roles which can result in non-sequential array keys.

https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L1106-L1109

This will get converted to an object instead of an array with `json_encode`. The fix is to change this:

```php
array_unique($userRoles)
```

To this:

```php
array_values(array_unique($userRoles))
```

That will ensure the array keys are reset.

**To Reproduce**
I'm not sure but it probably involves having duplicate user roles. Perhaps that's caused when the user is assigned to two user groups with the same role id.

**What application are you using?**
3.3 pre-release

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**
**[master]**
[pkp-lib]: #6031
[OJS]: pkp/ojs#2819 (Submodule update)
[OMP]: pkp/omp#841 (Submodule update)
[OPS]: pkp/ops#47 (Submodule update)

**Comment by NateWr** [comment]
Thank you sir! The OMP tests failed but it looks like that's my mistake for committing directly to OMP yesterday. Everything else passed and looks good. :+1:
