### ISSUE TITLE
PHP Notice when compiling LESS from a theme plugin

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6008]
**Describe the bug**
I'm receiving multiple PHP Notices when any theme compiles LESS, with the content:
```
PHP Notice:  Trying to access array offset on value of type null in /home/doc/OJS/testing/ojs-stable-3_2_1/lib/pkp/lib/vendor/wikimedia/less.php/lib/Less/Parser.php on line 1927
```

**To Reproduce**
1. In the website settings, appearance menu, choose the Default theme if isn't yet chosen.
2. Clear template cache from an administration form. 
3. Visit index journal page, the second step ensures that LESS will be recompiled.
4. Notices appear in logs.

**What application are you using?**
 OJS 3.2.1 stable branch

**Comment by Vitaliy-1** [comment]
Not the OJS issue.
It looks like been fixed on the `wikimedia/less.php` master branch.

**Comment by NateWr** [comment]
Hmm, I notice that we're on v1.* of the compiler. v2.0 was released in February and then v3.0 just a month later. It looks like v2.0 and v3.0 each have a higher PHP version requirement than us.

https://packagist.org/packages/wikimedia/less.php

@asmecher what do you think is the best course here? Should we stick with what we've got for now or bump our minimum version requirement and update this dependency?

**Comment by asmecher** [comment]
PHP 7.2.9 (released in August 2018) is the base requirement for less.php 3.0.0; that feels too recent for my tastes. However, less.php 2.0.0 requires PHP 7.1.x or newer, which is already met by our current baseline for OJS/OMP/OPS 3.2.1.x. Does less.php 2.0.0 include the fix we're interested in?

**Comment by NateWr** [comment]
I'm not sure if 2.0 addresses this, but I'd be curious to know why that version line was abandoned only a month after it was released. There's no 2.0.1 or anything. I've asked the question at https://github.com/wikimedia/less.php/issues/42.

**Comment by NateWr** [comment]
It looks like this is what 2.0 is for. I notice that 7.2 is losing security support in November. Should we aim to bump our requirement to 7.3 for our 3.3 release? In that case we could go to straight to less.php 3.0 in `master` and backport the 2.0 to our stable branches.

**Comment by asmecher** [comment]
Yes, I'm OK to bump `master` to a base of PHP 7.3.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/6338

Tests:
https://github.com/pkp/ojs/pull/2903

@asmecher just double-checking again that we're ok to bump PHP requirement to 7.3 for the next major release.

**Comment by asmecher** [comment]
Just confirming, yes, we can targeting PHP7.3 for OJS/OMP/OPS 3.3. By the time the Q1 release is made, PHP7.2 will no longer be receiving security fixes. (https://www.php.net/supported-versions.php)

**Comment by NateWr** [comment]
All merged! :tada: 

@kaitlinnewson and @amandastevens this will have a minor impact on documentation. The minimum required PHP version for running OxS is now PHP 7.3.

**Comment by amandastevens** [comment]
I don't think any of the documentation refers to specific system requirements or PHP version. Guides that have a section about installing always refer to the README or software download page on the website for requirements
