### ISSUE TITLE
Without ordering child categories don't appear under their parents

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6010]
Tested with OJS 3.2.1 stable branch.

By default, if ordering of any sort isn't applied, child categories in the sidebar appear not under their parents but either by a sequence as they were added by a user:
![screencapture-localhost-8000-index-php-pft-index-2020-06-16-17_13_06](https://user-images.githubusercontent.com/20665587/84785898-b6160980-aff4-11ea-93c3-34df12afbb49.png)
Or before their parents (child of the first category was added after the second category):
![screencapture-localhost-8000-index-php-pft-index-2020-06-16-17_14_13](https://user-images.githubusercontent.com/20665587/84786135-03927680-aff5-11ea-8e11-a32602d37248.png)

**Comment by asmecher** [comment]
(This worked for me; closing)

**Comment by Vitaliy-1** [comment]
@asmecher, sorry that I haven't checked the fix earlier. Just installed public release with the fix and the issue remains
![screencapture-ojs-3-2-1-test-index-php-psp-issue-archive-2020-06-23-17_13_06](https://user-images.githubusercontent.com/20665587/85414685-1963e680-b575-11ea-9702-52b4b03f16da.png)
![screencapture-ojs-3-2-1-test-index-php-psp-management-settings-context-2020-06-23-17_13_35](https://user-images.githubusercontent.com/20665587/85414723-2254b800-b575-11ea-9689-8affee67c177.png)

**Comment by asmecher** [comment]
@Vitaliy-1, could you send me a dump of your `categories` and `category_settings` tables?

**Comment by asmecher** [comment]
@Vitaliy-1, are you still seeing this problem?

**Comment by asmecher** [comment]
@Vitaliy-1, I'm closing this for lack of feedback, but please do let me know if you see it again.
