### ISSUE TITLE
Imported submissions throw off editorial statistics

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6011]
**Describe the problem you would like to solve**
Imported submissions that are published directly cause problems for the editorial statistics. This is because they lack editorial decisions and typically do not include an accurate `date_submitted` value.

For example, there will be discrepencies between the number of submissions receives and the number of submissions accepted, declined or published when viewing within a date range. Submissions will be counted as received based on when they were imported, but published depending on their `date_published` value.

**Describe the solution you'd like**
This is tricky because any solution that we use may have unintended consequences for other data. However, I believe it _may_ be safe to exclude all submissions which have a `date_published` _after_ their `date_submitted`.

Such cases suggest a submission that was either imported or added using the QuickSubmit plugin. And in such a scenario, where the submitted date is after the published date, the editorial stats can not really be accurate anyway. So even if we end up excluding some submissions that were not imported, they probably represent submissions with corrupted data anyway.

**Who is asking for this feature?**
It is very common for journals to import back catalogues to OJS. Publishing Services does this a lot. Some accounting for this will be necessary to make editorial statistics accurate for these journals.

**Comment by NateWr** [comment]
This commit includes some code that would exclude such submissions from _all_ editorial stats. It probably needs to be reviewed for unintended consequences.

https://github.com/NateWr/pkp-lib/commit/cdfbd52c3976e91c55ac59cebae66a49f5593859

**Comment by asmecher** [comment]
Merged https://github.com/NateWr/pkp-lib/commit/cdfbd52c3976e91c55ac59cebae66a49f5593859 after discussion/testing; closing.
