### ISSUE TITLE
OJS 3.2 Tab "Help" overlapping top bar menu in the dashboard

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6013]
**Describe the bug**
The tab "help" of dashboard grid forms is overlapping visually the menu items of language top bar menu.

**To Reproduce**
1. Go to 'Dashboard > Settings > Website > Appearance'
2. Scroll down to 'save' button
4. See error when the upper right tab stays over the language menu

**What application are you using?**
 OJS  3.2.0

**Additional information**
![image](https://user-images.githubusercontent.com/4992902/85035003-b3302b80-b150-11ea-8ff7-be8120abe703.png)

**Comment by NateWr** [comment]
I _think_ this is no longer the case after #5865.
