### ISSUE TITLE
A lot of extra space at the bottom of Submissions page

### ISSUE THREAD

**Issue by sssoz** [pkp/pkp-lib#6017]
# Describe the bug

See screen capture below. 

It seems to come from the Archive tab, the `pkpListPanel__filterSet`. 

Seen on the demo installation: https://demo.publicknowledgeproject.org/ojs3/demo/index.php/pragma/submissions 

# To Reproduce

1. Go to the OJS dashboard 
2. Click Submissions
3. There’s a lot of white space at the bottom 

# What application are you using?

 OJS 3.2.0.0 on MacOS Chrome, latest version. 

# Additional information

![4632dd6f84686daa8a84c16b727c0a84](https://user-images.githubusercontent.com/6668406/85041756-459cf300-b182-11ea-99ba-be0f92bdea5c.gif)

**Comment by Vitaliy-1** [comment]
Yeah, I filled it out for attention yesterday: https://github.com/pkp/pkp-lib/issues/6001
