### ISSUE TITLE
v2: REVIEW_REQUEST_REMIND_AUTO* should be different than REVIEW_REQUEST in translations too

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#6019]
email reminders REVIEW_REQUEST_REMIND_AUTO (and *_ONECLICK) were split from REVIEW_REQUEST, as per issues #562 and #1054.

initially, the email content was simply copied as is.

later, it was adapted in English and for v3 only:
https://github.com/pkp/omp/commit/5f145844ec60f1c841caea8690004c9dd79d3dae

then I backported the adaptation in English from v3 to v2:
https://github.com/pkp/ojs/pull/2502

unfortunately, the translations of REVIEW_REQUEST_REMIND_AUTO* are still identical to those of REVIEW_REQUEST in most or all other languages for v2, e.g.:
https://github.com/pkp/ojs/blob/ojs-dev-2_4/locale/pt_BR/emailTemplates.xml

eventually, the adaptation was done in v3, e.g:
https://github.com/pkp/ojs/blob/stable-3_2_1/locale/pt_BR/emails.po
now, ideally they'd be backported to v2.

**Comment by NateWr** [comment]
When you say v3 and v2 are you referring to OJS 3 and OJS 2?

**Comment by fgnievinski** [comment]
sorry for the abbreviation.
yes, v2 and v3 refer to 
OJS versions: OJS2, OJS3.

**Comment by NateWr** [comment]
I don't think there are any plans to backport translation changes to OJS 2. At this point it will only receive critical security updates.
