### ISSUE TITLE
Crossref plugin not receiving title metadata in most recent 3.2.1 testing. 

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#6021]
Running a test on client data with Crossref test credentials and I'm running into a failure with this error on submission with the Crossref plugin... 

```
<?xml version="1.0" encoding="UTF-8"?>
<doi_batch_diagnostic status="completed" sp="a-cs1">
   <submission_id>1430036899</submission_id>
   <batch_id>_1592519078</batch_id>
   <record_diagnostic status="Failure" msg_id="56">
      <doi>none</doi>
      <msg>Deposit contains title error(s): Title name value is missing from the title element</msg>
   </record_diagnostic>
   <batch_data>
      <record_count>1</record_count>
      <success_count>0</success_count>
      <warning_count>0</warning_count>
      <failure_count>1</failure_count>
   </batch_data>
</doi_batch_diagnostic>
```

If I check the XML export, title field looks like this: 

```
        <titles>
          <title/>
        </titles>
```

The article _has a title_ and I've never seen this happen before, so I suspect it's a hiccup with the latest 3.2.1 build we're testing.

**Comment by asmecher** [comment]
@AhemNason, what is the language setup on that journal? Are you navigating the install in a language other than the journal's primary language?

**Comment by AhemNason** [comment]
primary only... bilingual metadata is enabled but this was all default and using existing metadata... and because it's live data, I also know that it successfully registered prior. The DOIs were marked "active" before I tried a test deposit using our test creds.

**Comment by asmecher** [comment]
And the journal was previously (seemingly) working fine with OJS 3.2.0-3?

**Comment by AhemNason** [comment]
They were previously on 3.1.2-4. Not sure when the update was applied for this test instance by @jmacgreg

**Comment by asmecher** [comment]
Thanks, @AhemNason! @defstat, could you take a look at this? It's possible that it affects 3.2.0 as well, since this upgrade went from 3.1.2-4 to pre-3.2.1.

**Comment by asmecher** [comment]
(@defstat, a reminder about this)

**Comment by defstat** [comment]
**PR**
**[master]**
[OJS]: pkp/ojs#2816

**[3.2.1]**
[OJS]: pkp/ojs#2817

**Comment by asmecher** [comment]
Both merged -- thanks, @defstat.

**Comment by gemusehandler** [comment]
I run into the same problem described as above. Crossref refuses the registration of the DOI due to a missing title. Working with OJS 3.3.0.7.

```
[03-Jan-2022 11:48:39 Europe/Amsterdam] PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /Users/gemusehandler/Sites/ojs3307/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php on line 100
[03-Jan-2022 11:48:39 Europe/Amsterdam] PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /Users/gemusehandler/Sites/ojs3307/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php on line 101
[03-Jan-2022 11:48:39 Europe/Amsterdam] PHP Warning:  strip_tags() expects parameter 1 to be string, array given in /Users/gemusehandler/Sites/ojs3307/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php on line 165
```
Is it solvable?
