### ISSUE TITLE
Crossref plugin does not validate export

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6027]
**Describe the bug**
Even if the "validate" is checked on the crossref export article page, invalid xml files get downloaded.

**What application are you using?**
 OJS version 3.2.x

**Additional information**
this has impact on https://github.com/pkp/pkp-lib/issues/6006 which, for its last test, depends on XML validation

**Comment by defstat** [comment]
@asmecher I can't reproduce the issue any more but I am reopening #6006 to fix a bug that could be related to failed crossref export test error

**Comment by asmecher** [comment]
Sure, that's OK with me.
