### ISSUE TITLE
OJS 3.2.1 not visible in download section

### ISSUE THREAD

**Issue by zalamuia** [pkp/pkp-lib#6028]
OJS 3.2.1 not visible in download section. May I know whether it is available in download area.

Thanks.

Zahirul
![OJS-3 2 1-missing](https://user-images.githubusercontent.com/61810595/85215315-6004e580-b3a9-11ea-9763-4d275779d262.png)

**Comment by asmecher** [comment]
@zalamuia, it'll be there soon!
