### ISSUE TITLE
Report Generator doesn't return any results when custom range is selected with a single day

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#6029]
**Describe the bug**
The OJS Report Generator doesn't return any results when a custom range is selected with the same day for "From" and "Until".

**To Reproduce**
1. Go to "Statistics -> Report Generator -> Generate Custom Report"
2. Go to "Or select range by" and choose "Day"
3. Use the same day for "From" and "Until"
4. Click "Generate Custom Report"

**What application are you using?**
 I reproduced the bug for OJS 2.4.8 and OJS 3.1.2

**Additional information**
The generated SQL statement (as grepped from mysql log) is incorrect:
`SELECT assoc_type, country_id, month, SUM(metric) AS metric FROM metrics WHERE assoc_type = '259' AND context_id = '1' AND month = '20200522' AND metric_type = 'ojs::counter' GROUP BY assoc_type, country_id, month;`

The column "month" is compared with a day string. It should read "day = '20200522'"

**Comment by asmecher** [comment]
@defstat, could you look this over? It might be a legacy issue (it's reported in 3.1.2).

**Comment by defstat** [comment]
@asmecher 

**PRs**
**[master]**
[pkp-lib]: #6049
[OJS]: pkp/ojs#2826 (Submodule update only)
[OMP]: pkp/omp#843 (Submodule update only)
[OPS]: pkp/ops#49 (Submodule update only)

**Comment by asmecher** [comment]
All merged -- but unfortunately I just released 3.2.1-1 without it! It'll be included in 3.2.1-2.

**Comment by ronste** [comment]
Hi Alec and Dimitris,

thanks for handling this so quickly. Do you think that the patch would also be applicable to OJS 3.1.2? E.g. can I just cheery-pick this commit or are there any specifics to OJS 3.2 in there?

**Comment by defstat** [comment]
@ronste, please try, it should work.
