### ISSUE TITLE
OJS 3.2.1 Plugin Intall/Update - failed - Issue preview details failed to show

### ISSUE THREAD

**Issue by zalamuia** [pkp/pkp-lib#6032]
OJS 3.2.1 updated recently from OJS 3.2.0.3 

* Plugin Install/Update - failed - gives null error

* Issue preview details failed to show (Preview possible from OJS 3.2.0.3 but details are not visible. It is visible for 3.1.2.4 version
![OJS3 2 1_error](https://user-images.githubusercontent.com/61810595/85384055-54651a80-b573-11ea-85f3-5a70be77c5ee.png)

**Comment by asmecher** [comment]
@zalamuia, could you start by posting these questions in our support forum (https://forum.pkp.sfu.ca)? That way we can help our git issues curated and it's generally the best place to go for support. The first issue is already addressed here: https://forum.pkp.sfu.ca/t/upgrade-plugin-not-working-in-web/61323
