### ISSUE TITLE
Announcements can be viewed even when disabled

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6033]
**Describe the bug**
Announcements can be viewed even if announcements have been disabled for the journal.

**To Reproduce**
1. Go to Settings > Website > Announcements and enable announcements.
2. Create an announcement and view it on the frontend.
1. Go to Settings > Website > Announcements and disable announcements.
4. Reload the announcement on the frontend. It is still available but should not be.

**What application are you using?**
3.2.1 (`master`)

**Comment by NateWr** [comment]
@asmecher is this ok or would you prefer I write up a `Policy` for this?

https://github.com/NateWr/pkp-lib/commit/ecdc612200530dbb1e0ba21474f562ed7b2f5eb0

**Comment by asmecher** [comment]
@NateWr, I'm OK with it as is -- it's a single use case and will probably always be.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/6037

Tests:
https://github.com/pkp/ojs/pull/2822

**Comment by NateWr** [comment]
Merged and cherry-picked to `stable-3_2_1`.
