### ISSUE TITLE
[UI] Workflow issues

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#604]
The following are outstanding issues in the [new UI fork](https://github.com/NateWr/pkp-lib/tree/header_ui) related to the workflow screens.

**Urgent**
- [x] Workflow > Editorial. See [PR 648](https://github.com/pkp/pkp-lib/pull/648)
- [x] Workflow stages can be initiated or completed. Currently the little dot only shows initiated. Need to rethink UI handling of these stages. <sup>[1](#workflowStages)</sup> 
- [ ] ~~The review request response page (when a reviewer is prompted to accept a review request) is pretty wonky. Needs some styling and testing of modals.~~ See #1488

**Improvements**
- [x] Workflow > Production > Galley Files: When two gallery types exist, upload a file from the second galley tab and the page reloads and resets the tab back to the first.
- [x] The Participants panel's handler is attached to a "header", but the participants panel is actually embedded into the tab content. In order for the handler to access everything, the whole page content (header, tabs, tab content) has to be "in the header". That breaks consistency in page markup that we have to account for through exceptions in the styling.
- [x] The Participants panel can be taller than the tab it's in.
- [x] There can be two notifications, in which case the icons overlap each other. Eg - "New reviews ready." and "All reviews are in"

<a name="workflowStages">1.</a> The workflow stage set up seems a bit odd. Judging from the test data, only one stage ever receives a [statusKey](https://github.com/pkp/pkp-lib/blob/master/templates/workflow/submissionProgressBar.tpl#L33) value at a time. But the `statusKey` doesn't necessarily reflect the status it's attached to. For instance, in the test data, an article that's reached the Production stage, "Genetic transformation of forest trees", is assigned a `statusKey` of `submission.initiated`. The submission stage has no `statusKey` attached to it. We'll probably leave things as they are for 3.0b, since the UI seems to reflect the "current" stage. But we'll need to sort out what this actually means and how to best use it.

**Comment by asmecher** [comment]
@NateWr, could you give this a look over to see what's still relevant?

**Comment by NateWr** [comment]
Obsolete. Closing.
