### ISSUE TITLE
[OJS] License override formatting error

### ISSUE THREAD

**Issue by alexdryden** [pkp/pkp-lib#6041]
Summary: When entering a license for a particular article that is not cc 3.0 or cc 4.0, the formatting on the article page does not list the copyright holder's name and includes the text 'Array' at the end of the link to the license. 

OJS version: 3.2.1

Steps to reproduce:

1. Add an article and push up to publication stage
2. Under permissions and disclosures, enter override for copyright holder, copyright year and enter a license url for anything other than cc 3.0 or cc 4.0.
3. Publish

Issue:
License information is malformed and some information is missing:
<img width="1291" alt="Screen Shot 2020-06-24 at 3 28 10 PM" src="https://user-images.githubusercontent.com/47127862/85618832-5ee4ea00-b62f-11ea-9dd9-f241743908ae.png">

**Comment by asmecher** [comment]
@alexdryden, here's a pull request that should resolve the problem: https://github.com/pkp/ojs/pull/2827

Can you confirm your success? If so, I'll get this added to a new build ASAP.

**Comment by alexdryden** [comment]
Awesome. Looks like that does the trick. Just to confirm to make sure this is the desired behavior: 
1. All the text is a link which resolves to the license url entered into the form.
2. Text reads "Copyright (c) <year_from_form> <copyright_holder_from_form>"

Thanks for the quick turn around!

**Comment by asmecher** [comment]
Great, I'll get this committed for the 3.2.1-1 line of releases (which should come out shortly). Thanks for the clear reporting!
