### ISSUE TITLE
Error on setting a editor recommendation in OJS 3.2.0.3

### ISSUE THREAD

**Issue by edersotto** [pkp/pkp-lib#6044]
Hello, I am getting the following error when setting a recommendation for an article that is under review. When saving the "request resend" recommendation, I am getting the following error: "
"There was a problem sending an email message". Please try again later, or contact your system administrator ". This error only appears when I check the option to send notification to the author. The error in OJS and the error in PHP are attached.

**To Reproduce**
1. Go to 'set recommendation with editor account'
2. Select option "Request resend"
3. Click on button "Registry editorial recommendation"
4. See error "There was a problem sending an email message"

Note: The emails of this OJS journal are sending normally.

![image](https://user-images.githubusercontent.com/19962752/85730571-221cff80-b6d0-11ea-955a-7cb68fd6b6a4.png)

![image](https://user-images.githubusercontent.com/19962752/85730616-2d702b00-b6d0-11ea-8a93-cd0845a69c33.png)

![image](https://user-images.githubusercontent.com/19962752/85730676-3b25b080-b6d0-11ea-98da-dc5f95246072.png)

Regards,

Thank you!

**Comment by asmecher** [comment]
@edersotto, are there any editors assigned to the submission?

**Comment by edersotto** [comment]
> @edersotto, are there any editors assigned to the submission?


Hello @asmecher, my sections was with no an editor. After define, it was solved. Thank you so much. Sorry by confusion.

**Comment by carzamora** [comment]
hi @edersotto, you get that error when you are in the First Round of Review or in the Second Round?  because @asmecher, just right now an Editor have the same problem, and my journal is working fine about sending emails and all workflow but the problem is when click on button "Registry editorial recommendation" on the Round 2. 

I could reproduce the issue just activating the second review, I am using OJS 3.1.2.4

**Comment by carzamora** [comment]
ooh, I understand now! is necessary to assign not just an Editor without permission for Accept manuscript and make a recommendation, also is necessary to assign an Editor with all permission, is correct??

**Comment by Selvakumarari** [comment]
@asmecher 
Dear Sir,
OJS version 3.2.1.1. shows mailing error. "There was a problem sending an email message. Please try again later, or contact your system administrator". Please help me to fix the error. I have assigned editor. But same issue has came. I have checked with error_log file and it showed "Could not instantiate mail function"
![Screenshot from 2021-03-02 17-14-49](https://user-images.githubusercontent.com/79926379/109674095-a3e8f500-7b9c-11eb-9722-277263eda993.png)

Thanks with regards
Dr. Selvakumar

**Comment by asmecher** [comment]
@Selvakumarari, please have a look through our support forum (https://forum.pkp.sfu.ca) for posts related to this; if those don't resolve the issue, create a new topic there. If it leads to a bug in the system, then we can use this issue tracker to resolve it, but until then the forum is the best place to get help.

**Comment by Selvakumarari** [comment]
@asmecher 
I have posted the same comment in PKP forum 
https://forum.pkp.sfu.ca/t/smtp-e-mail-error/65733/21

**Comment by Selvakumarari** [comment]
Dear@asmecher
Issue is not able to resolve. Please help me in this regard.
www.jinagri.com
agrosciencetoday.com
Thanks
