### ISSUE TITLE
[OPS] EDITOR_ASSIGN e-mail not triggered

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6047]
**Describe the bug**
The e-mail `EDITOR_ASSIGN` is not being triggered when assigning an editor.

According to the e-mail's description:

_This email notifies a Series Editor that the Editor has assigned them the task of overseeing a submission through the editing process. It provides information about the submission and how to access the server site._

**To Reproduce**
1. Assign an editor
2. Notice how the email `EDITOR_ASSIGN` does not appear within the available options.

**What application are you using?**
OPS 3.2.1.0

**Comment by NateWr** [comment]
I was not able to reproduce this in a test with the latest `master` branch. When I assign a "Moderator" one of my email template choices is "Moderator Assignment", which is the subject of the `EDITOR_ASSIGN` email template in OPS.

Is it possible that this email template has been disabled under Settings > Workflow > Emails > Email Templates?

**Comment by alexxxmendonca** [comment]
I don't think so. This is how it appears to me:

![image](https://user-images.githubusercontent.com/4059679/86133796-2c1f7380-babf-11ea-9429-b4296503ef44.png)

**Comment by NateWr** [comment]
I just had a look at the code and it looks like which email templates are available depends on the stage. https://github.com/pkp/ops/blob/master/controllers/grid/users/stageParticipant/form/StageParticipantNotifyForm.inc.php#L34

Are you sure that this submission has been completed (ie - the author has fully submitted it) and it is in the Production stage?

**Comment by alexxxmendonca** [comment]
> Are you sure that this submission has been completed (ie - the author has fully submitted it) and it is in the Production stage?

Yes, positive!

**Comment by NateWr** [comment]
Based on our Slack chat I think this is resolved, yeah? Closing for now.

**Comment by alexxxmendonca** [comment]
Hi @NateWr 

Thanks to your heplp, I think what may have happened is that I was in the Portuguese interface and given that there was no translation for that email template, it didn't came up as an option to choose. I got into the wrong conclusion that the email wasn't being triggered, but it was just a missing translation problem.

Indeed there was not a problem here. Sorry!
