### ISSUE TITLE
File upload and Image upload fields are not working.

### ISSUE THREAD

**Issue by gopalkildoliya** [pkp/pkp-lib#6052]
**File upload and Image upload fields are not working.**
Upload logo or custom style CSS file no longer working. This is related to UI Library

**To Reproduce**
1. Go to 'Website Settings'
2. Click on 'Click Setup tab'
3. Now upload your logo
4. Now save
5. The logo doesn't change

**What application are you using?**
 OJS  master

**Additional information**
Issue is related to pkp/ui-library

**Comment by NateWr** [comment]
Thanks for reporting, @gopalkildoliya! I've located the issue and prepared a fix. This only effects the `master` branch so shouldn't need to be backported to any stable branch.

PR:
https://github.com/pkp/ui-library/pull/104

Tests:
https://github.com/pkp/ojs/pull/2832
