### ISSUE TITLE
Add a filter by assigned issue to OJS submission lists

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6054]
**Describe the problem you would like to solve**
Editors and assistants would sometimes like to filter their submission lists by the issue a submission is assigned to. This can help them identify submissions that are urgent (ie - for the upcoming issue), or identify submissions planned for a special issue, or locate submissions from published issues (in the Archived submissions list).

**Describe the solution you'd like**
Add an autosuggest filter that allows the editor/assistant to search for and apply one or more issues as a filter. When one or more issues is applied as a filter, submissions should only appear in the list if they are assigned to these issues.

**Who is asking for this feature?**
A publishing services client has requested this. See https://github.com/pkp/pkp-lib/issues/2612

**Comment by NateWr** [comment]
@thinkbulecount2 you've already done most of the work for this by implementing the `FilterAutosuggest` component in #5982. Here are the steps I think you'll need to take to add a similar filter for issues.

1. Create a `FieldSelectIssues.vue` component based on `FieldSelectUsers.vue`. You can use the [api docs](https://docs.pkp.sfu.ca/dev/api/ojs/3.2) to see what a request to `/issues` will look like when it is returned from the API. (Note: there's already a `FieldSelectIssue.vue`, but don't use that.)
2. Modify the `FilterAutosuggest.vue` component so that it can use any autosuggest field, not just `FieldSelectUsers`. (Use `PreviewFilterAutosuggest` to show previews for both types of fields at the same time.)
3. Extend `PKPBackendSubmissionsHandler::getMany()` to accept the `issueIds` param. You can look at `PKPSubmissionsHandler::getMany()` for an example.
4. Add the filter to all submission lists whenever the user is an admin, manager, editor and assistant.
5. Make sure the filter only appears in OJS.

**Comment by NateWr** [comment]
@thinkbulecount2 I have implemented the `searchPhrase` param for the `/issues` REST API endpoint in https://github.com/NateWr/ojs/commit/a829195b3d5c1b350841c83d58cb4f37ac3a67ff. You should be able to cherry-pick it in.

**Comment by thinkbulecount2** [comment]
pkp-lib PR: https://github.com/pkp/pkp-lib/pull/6090
ojs PR: https://github.com/pkp/ojs/pull/2837

**Comment by NateWr** [comment]
Looks good! It was all working for me, just a few minor changes and getting this working for the right set of submission lists.

Can you change some styling in the `Badge.vue`? Where it says `padding: 0 1em;` and `line-height: 2em`, let's change that to `line-height: 1.5em` and `padding: 0.25em 1em`. This will make a two-line badge look a little better.

**Comment by thinkbulecount2** [comment]
> Looks good! It was all working for me, just a few minor changes and getting this working for the right set of submission lists.
> 
> Can you change some styling in the `Badge.vue`? Where it says `padding: 0 1em;` and `line-height: 2em`, let's change that to `line-height: 1.5em` and `padding: 0.25em 1em`. This will make a two-line badge look a little better.

Resolved this in `ui-library`: https://github.com/pkp/ui-library/pull/107/commits/0e9b0ffeb86ed4d70445ec07c195befba75d8613

**Comment by thinkbulecount2** [comment]
Resolved all oustanding PR comments.

cc @NateWr

**Comment by NateWr** [comment]
All merged! :tada:
