### ISSUE TITLE
Category selection not reloaded when submission step 1 form doesn't validate

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6055]
**Describe the bug**
If step 1 of the submission form does not pass validation, the form is reloaded but the category selection no longer appears.

**To Reproduce**
1. Make sure you have at least one category defined.
2. Go to Submissions and click New Submission.
3. Open the browser's dev tools and delete the submission checklist elements from the inspector. Then complete step 1 and submit the form.
4. The form will reload with a validation error but the category selection will be gone.

**What application are you using?**
3.3 pre-release (`master`)

**Comment by taslangraham** [comment]
@asmecher I added a PR to fix this
pkp-lib(stable 3.3.0): https://github.com/pkp/pkp-lib/pull/10295/files
ojs(test): https://github.com/pkp/ojs/pull/4395

**Comment by asmecher** [comment]
@taslangraham, I merged https://github.com/pkp/ojs/pull/4395 as I saw that https://github.com/pkp/pkp-lib/pull/10295 was already merged -- but it looks like https://github.com/pkp/pkp-lib/pull/10295 might've been merged accidentally. Was https://github.com/pkp/pkp-lib/pull/10295 ready to go?

**Comment by asmecher** [comment]
:+1: Great, thanks!
