### ISSUE TITLE
Unread notifications aren't being shown on the front-end

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6058]
OJS master branch.
Task count blob in the header is empty in the presence of unread tasks
`unreadNotificationCount` variable was removed from `TemplateManager` as part of backend UI refactoring in this commit: https://github.com/pkp/ojs/commit/842096987251d154cc6d3c0f7c3f010e091f8aef but it's used on the front-end part also.

**Comment by NateWr** [comment]
Ah good catch. I tried to separate out the backend template stuff so that the code wouldn't run for frontend pages, but I forgot about this one. I guess this needs to go into PKPTemplateManager somewhere.

I'll assign this one to you if that's alright but can reassign if you find your other assignments keep you busy.

**Comment by Vitaliy-1** [comment]
@NateWr, previously there was an import statement:
```
import('lib.pkp.controllers.grid.notifications.TaskNotificationsGridHandler');
```
before the assignment to the template, what it was used for? According to the comment: `// Exclude certain tasks, defined in the notifications grid handler` but I don't see where it's used.

**Comment by NateWr** [comment]
Usually an import statement like that, when `TaskNotificationsGridHandler` is not actually used, is done to bring in a constant. If you leave it out, you can check your server logs for undefined constant warnings. If they're not there, it may no longer be necessary.

**Comment by Vitaliy-1** [comment]
pkp-lib master: https://github.com/pkp/pkp-lib/pull/6345
Tests OJS master: https://github.com/pkp/ojs/pull/2907

Thanks @NateWr, sorry for the late response. In that case, the initial commit should do! I don't see any warnings in logs.

**Comment by NateWr** [comment]
Thanks! The code looks good. Once the tests are passing I'll merge.

**Comment by NateWr** [comment]
Thanks @Vitaliy-1, all merged!
