### ISSUE TITLE
Error message while uploading native xml file to ojs 3.2.1.0

### ISSUE THREAD

**Issue by MuhammadFahadMukhtar** [pkp/pkp-lib#6059]
Element '{http://pkp.sfu.ca}title': This element is not expected. Expected is one of ( {http://pkp.sfu.ca}id, {http://pkp.sfu.ca}submission_file, {http://pkp.sfu.ca}artwork_file, {http://pkp.sfu.ca}supplementary_file, {http://pkp.sfu.ca}pkppublication, {http://pkp.sfu.ca}publication ).

can anyone help me with the above error? i face this issue while importing native xml file to ojs 3.2.1.0

**Comment by NateWr** [comment]
@defstat does this ring any bells for you?

**Comment by defstat** [comment]
@MuhammadFahadMukhtar could you share the file that has the import issue? Is the import file created by the same ojs version that you are trying to import?

**Comment by MuhammadFahadMukhtar** [comment]
@defstat that was a sample file downloaded from github for ojs3.2 which I have replaced now and also I have rolled back ojs3.2.1.0 to 3.2.0 to resolve the issues and now everything is going smooth.
