### ISSUE TITLE
quicksubmit 1.0.5.3 unable to insta on ojs 3.2.1.0 it just says notification (null)

### ISSUE THREAD

**Issue by MuhammadFahadMukhtar** [pkp/pkp-lib#6061]
whenever i try to install quicksubmit from plugins gallery a notifification pop up is there with null value

**Comment by NateWr** [comment]
Hi @MuhammadFahadMukhtar, can you please provide the information requested below? In particular, identify the steps you're taking to install it in the Reproduction steps.

**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**What application are you using?**
 OJS or OMP version X.X.X

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by MuhammadFahadMukhtar** [comment]
@NateWr thanx for your response, but I have rolled back my OJS from to 3.2.1.0 to 3.2.0 and it fixed my issue.
But this problem should be addressed that why "Quicksubmit" plugin being not installed in ojs3.2.1.0.
