### ISSUE TITLE
[OJS] Text color does not respond to background color selection on mobile

### ISSUE THREAD

**Issue by alexdryden** [pkp/pkp-lib#6064]
Issue: If you select a white color for the header, then the dropdown menu options are white-on-white on mobile or small screens. Same for low-contrast combinations.

Steps to reproduce:

1. From Setting>Website>Appearance>Theme go to color and select #FFFFFF
2. Visit the journal from mobile or shrink browser window till hamburger menu appears.
3. Tap/click on the hamburger menu

**Comment by NateWr** [comment]
What version of OJS are you using? What theme are you using?

**Comment by alexdryden** [comment]
Here are the missing details @NateWr 
Theme: Default
OJS Version: 3.2.1.0
example: https://scp.library.illinois.edu/journals/index.php/test2/index

**Comment by NateWr** [comment]
Thanks!

**Comment by NateWr** [comment]
PRs for `stable-3_2_1`:
https://github.com/pkp/ojs/pull/2840
https://github.com/pkp/omp/pull/850
https://github.com/pkp/ops/pull/55

**Comment by NateWr** [comment]
All merged to `stable-3_2_1` and cherry-picked to `master`.
