### ISSUE TITLE
Missing STATUS constants in IssueDAO class

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6065]
Can we please get the fix that Alec committed here:

https://github.com/pkp/ojs/commit/8411fb081e50428cef1efd22ec6a644c04033b61

Backported to stable-3_2_0 please?  The rest of the code for issue #5837 has been already, and perhaps this was just missed.  

@NateWr asked for the assign.  Thanks!

**Comment by NateWr** [comment]
Done in https://github.com/pkp/ojs/commit/c9b1bce881e616afaa574380d91ef8f08bc42d81.
