### ISSUE TITLE
Submission Checklist - Reordering doesn't save

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6067]
**Version - OJS 3.2.0-1**

Based on the following forum thread - https://forum.pkp.sfu.ca/t/checkist-items-ordering/61458/3

Went to Workflow Setting >Submission >Checklist. Attempted to re-order the submission checklist by clicking order, and dragging around the order. After clicking done the order would revert back to the original. I tested this on 1 change and multiple as well as rearranging a newly added item. 

![Reordering submission checklist_v2](https://user-images.githubusercontent.com/50342731/86414762-cfb48380-bc79-11ea-887e-527f48109db7.gif)

**Comment by NateWr** [comment]
Confirmed.

**Comment by asmecher** [comment]
Fixed -- thanks for the clear report!

Existing users can fix this by applying [this change](https://github.com/pkp/pkp-lib/commit/60b5511da4cb28b154e15dcd99d26b81522b6214) to `lib/pkp/controllers/grid/settings/submissionChecklist/SubmissionChecklistGridHandler.inc.php`.
