### ISSUE TITLE
package-lock.json contains wrong version number

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#6069]
Hi there,

the file `package-lock.json` contains the version number `3.2.0` but I assume that it should be `3.2.1` as the branch name implies. So after running `npm install` the file contains `3.2.1` and it is listed as changed file. Most likely you guys forgot to update the file. I will provide a PR.

So lonG
Daniel

**Comment by NateWr** [comment]
This was fixed a while back. @asmecher and @jardakotesovec, just a heads-up to add this to a release checklist or procedure. I notice that UI Library still says version 0.1.0. Not consequential, but probably worth keeping in sync with our releases.
