### ISSUE TITLE
[UI] Issues around LESS files and compilation

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#607]
An effort has been made to clean up the LESS files, structure their loading in a way that reduces specificity battles, and reduce the number of files we're managing. There are still a lot of lingering files around, and the shift has only been partly successful. The goal is for a load priority that looks like the following:

- reset
- variables
- helpers
- base (body, a)
- structure
- components (navbar, grid, modals, etc)
- pages

After beta it would be nice to spend some time really cleaning out all of the unused files and rationalizing their structure.

This list is short for now but may get added to later.

**Improvements**
- [x] Our new LESS compiler does not strip comments. And as far as I can tell the only setting to have it strip comments will also minify it. Not sure if we want to ship minified CSS.

**Comment by asmecher** [comment]
@NateWr, I don't have any problem shipping minified CSS -- in fact, it may help dissuade people from modifying the compiled CSS directly, which believe me, they will try to do. Any objections to doing that, at least for the sake of 3.0?

**Comment by NateWr** [comment]
:+1: Would love to ship minified CSS.

**Comment by asmecher** [comment]
Minified CSS. @NateWr, is there anything else active on this issue, or is it resolved?

**Comment by NateWr** [comment]
We'll need to keep this in mind when we get around to merging #1468. The LESS compilation has been moved around and refactored considerably there. But there's only one place where it happens so that's good.

In terms of other stuff on this issue. I still think there's a lot of old CSS lingering in our backend styles, but it's really hard to determine what's still in use and what's not. I'm fine closing this since it's not really got any specific targets.

**Comment by asmecher** [comment]
OK, this is a trivial fix so it'll be easy to migrate. Closing for now.
