### ISSUE TITLE
XMLParser bug when parsing text nodes

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6070]
**Describe the bug**
The following structure, with texts nodes mixed with element nodes, will not be parsed right by the [XMLParser](https://github.com/pkp/pkp-lib/blob/master/classes/xml/XMLParser.inc.php): `<a>X<b>Y</b>Z</a>`, and will internally result in `<a>Z<b>Y</b></a>`.

I imagine that fixing it will do more harm than good, so I'm just documenting the issue... I've got it replaced by the native DOMDocument + DOMXPath for my own needs.

**What application are you using?**
 OJS/stable-3_2_1

**Comment by asmecher** [comment]
@jonasraoni, you're right, and better to use DOMDocument + DOMXPath. The XMLParser code is very old and should be considered deprecated. I'll close this as a WONTFIX.
