### ISSUE TITLE
Tag-It based submission metadata fields may collide with other multilingual metadata popovers

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6073]
From https://forum.pkp.sfu.ca/t/error-after-migratin-ojs-2-4-8-to-3-1-2-1/60665/13...

**Describe the bug**
When multilingual inputs based on tag-it appear in the submission metadata form (including Step 3 of the submission process), the multilingual drop-down is opened by default, e.g.:
![image](https://user-images.githubusercontent.com/200411/86847810-cf452f80-c061-11ea-9018-67fb21a56e9d.png)
(This is the case since https://github.com/pkp/pkp-lib/issues/3003.)

However, when many languages are enabled, they may collide with other multilingual inputs further up the page.

When many languages are enabled, multilingual elements above the tag-it field may collide with the tag-it field. For example, the following submission form is fine when initially loaded:
![image](https://user-images.githubusercontent.com/200411/86848190-6c07cd00-c062-11ea-93e7-0c3163a56687.png)

However, clicking "Abstract" to expand that field results in the following:
![image](https://user-images.githubusercontent.com/200411/86848244-7cb84300-c062-11ea-8a4d-58cf96985d50.png)

The tag-it-based Keywords fields appear over top of the abstract fields.

**To Reproduce**
1. Configure the journal for many submission and form languages.
2. Enable at least one tag-it-based metadata field on submission (e.g. Keywords)
3. Begin a new submission; continue to Step 3 (the metadata form)
4. Observe the Abstract and Keywords fields
5. Click "Abstract" to cause the abstract multilingual fields to collide with the keyword multilingual fields.

**What application are you using?**
Reported in OJS 3.1.2, but affects up to and including OJS 3.2.1-1.

**Comment by NateWr** [comment]
This is probably a `z-index` issue. I think the best way to address this would be to override the `z-index` for the multilingual panel of the metadata fields in the submission form. Reducing the `z-index` _should_ address this.

**Comment by asmecher** [comment]
@NateWr, any objections to https://github.com/pkp/pkp-lib/pull/6078/files? I used `90` (the normal multilingual popover is `99`).

**Comment by NateWr** [comment]
Looks good to me!

**Comment by asmecher** [comment]
Merged, thanks!

Users who encounter this in OJS/OMP/OPS 3.1.x, 3.2.0, 3.2.1-0, or 3.2.1-1 can apply https://github.com/pkp/pkp-lib/pull/6078/files in `lib/pkp`, and cause the CSS to be rebuilt by removing `cache/*.css`.
