### ISSUE TITLE
Missing or strange affiliation values for newly registered users

### ISSUE THREAD

**Issue by dennmuel** [pkp/pkp-lib#6076]
Hi everyone :)

I just noticed an unexpected behavior concerning affiliations in OJS 3.2.1-0 and I'd be glad about some help. Maybe I got something wrong, but it might also be a bug.

**Describe the bug**
I registered a new OJS user with information about institution/affiliation, but it did not show up at all in the user profile and it showed up as JSON (I guess?) in the metadata of a submission made by this user.

**To Reproduce**
1. Register a new OJS account for a journal, fill out the affiliation field. Complete the activation of the account.
2. Look into the profile of the new account; the affiliation field is empty. I would expect it to be filled with the value I entered in the registration form.
3. Make a submission with the new account.
4. As e.g. a journal manager, look at the submissions "list of contributors", edit the author derived from the new account, find the affiliation field filled with some strange value somewhat containing the value entered in the registration form.

**What application are you using?**
 OJS version 3.2.1-0

**Additional information**
Screenshot of the contact tab in the user profile:
![grafik](https://user-images.githubusercontent.com/21078769/86924962-7bede280-c130-11ea-8ee7-0e7d76851343.png)

Screenshot of the author metadata:
![grafik](https://user-images.githubusercontent.com/21078769/86921554-983b5080-c12b-11ea-84aa-a1191a54d6dd.png)

The journal is bilingual: German (primary) and English. The registration form was filled out in German. The above screenshot is from the English backend, but looks the same in German.

Any help is much appreciated. :)

Kind regards
Dennis

**Comment by asmecher** [comment]
@dennmuel, what theme are you using?

**Comment by dennmuel** [comment]
Hi @asmecher,
we're using a modified Bootstrap3-Theme. I could not reproduce the issue with the Default Theme, but with the unmodified [Bootstrap3-Theme](https://github.com/NateWr/bootstrap3). I guess I'll head over there to pursue this further then.
Thanks for the hint!
