### ISSUE TITLE
Reduce dependency on `exec`

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6077]
Errors relating to `exec` are frequent on the forum:
- Confusion over how to configure the `tar` binary (used in the plugin installation toolset)
- Disabled `exec`, `open_basedir` warnings, etc

Currently `exec` is used in several cases, documented here: https://forum.pkp.sfu.ca/t/ojs-3-2-0-0-unable-to-upgrade-plugins-through-the-interface-500-open-basedir-restriction-manually-upgrade-plugins/61482

However, there seem to be decent PHP-based alternatives to each of those cases.

Investigate removing reliance on the `exec` toolset.

**Comment by asmecher** [comment]
@NateWr, this PR (https://github.com/pkp/pkp-lib/pull/7075) uses PharData (built into any modern PHP, apparently) to extract plugins rather than depending on `exec()`; can you have a quick look? The relevant changes are here: https://github.com/pkp/pkp-lib/pull/7075/commits/f03c9f34ba0d4d9815d1f376eec7ce0bf09edec8#diff-15610b2b0d4270f5d74eb05245533740010391e1f29ec4a5346f46d960e832e9R67

**Comment by NateWr** [comment]
Looks like a good improvement to me! I noticed this line from the PHP docs for `extractTo`:

> Extracted files and directories preserve permissions as stored in the archive.

Any chance that's going to catch some people by surprise? Or does `tar` preserve permissions as well?

**Comment by asmecher** [comment]
This behaviour is the same as `tar`; I think we're OK. Thanks!

**Comment by asmecher** [comment]
The plugin dependency on `exec` has been removed for release in 3.4.0; closing this issue with the remainder filed at https://github.com/pkp/pkp-lib/issues/7083, since those are far less important priorities (based on support forum posts).
