### ISSUE TITLE
[UI] Change pnotify submodule to a composer lib

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#608]
The `pnotify` submodule pulls in absolutely tons of pre-build assets. It would be nice to switch a compiled composer wrapper, like [this one](https://github.com/alex198710/pnotify).

**Comment by asmecher** [comment]
See also https://github.com/pkp/omp/pull/119

**Comment by asmecher** [comment]
In fact, closing this in favour of the already-filed one linked above. One reason I haven't leaped on this yet is that there isn't an official composer package for pnotify (yet).
