### ISSUE TITLE
Ability to rename locales (removing/changing country names)

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#6080]
**Describe the problem you would like to solve**
Journal Managers would like to remove or change the country designations from the locales as named in `registry/locales.xml`, but this is not configurable by the Journal Manager or Site Administrator.  Currently it can only be accomplished by a local code change.

**Describe the solution you'd like**
First preference: a plugin which can modify the locale names; Second preference: a setting to point to an alternate locales.xml file.

**Who is asking for this feature?**
Journal Managers, Site Administrators

**Additional information**
The PKP plugin approach is implausible, as the locales are loaded as the generic plugins are loaded.
```
  00 : 'lib/pkp/classes/cache/GenericCache.inc.php:63' called 'PKPLocale::_allLocalesCacheMiss',
  01 : 'lib/pkp/classes/cache/FileCache.inc.php:115' called 'GenericCache->get',
  02 : 'lib/pkp/classes/i18n/PKPLocale.inc.php:671' called 'FileCache->getContents',
  03 : 'lib/pkp/classes/i18n/PKPLocale.inc.php:381' called 'PKPLocale::_getAllLocalesCacheContent',
  04 : 'lib/pkp/classes/context/Context.inc.php:265' called 'PKPLocale::getAllLocales',
  05 : 'classes/template/TemplateManager.inc.php:76' called 'Context->getSupportedLocaleNames',
  06 : 'lib/pkp/classes/template/PKPTemplateManager.inc.php:885' called 'TemplateManager->initialize',
  07 : 'lib/pkp/classes/plugins/Plugin.inc.php:352' called 'PKPTemplateManager::getManager',
  08 : 'lib/pkp/classes/plugins/Plugin.inc.php:118' called 'Plugin->_registerTemplateResource',
  09 : 'lib/pkp/classes/plugins/LazyLoadPlugin.inc.php:28' called 'Plugin->register',
  10 : 'plugins/generic/lensGalleyBits/LensGalleyBitsPlugin.inc.php:23' called 'LazyLoadPlugin->register',
  11 : 'lib/pkp/classes/plugins/PluginRegistry.inc.php:69' called 'LensGalleyBitsPlugin->register',
  12 : 'lib/pkp/classes/plugins/PluginRegistry.inc.php:143' called 'PluginRegistry::register',
  13 : 'lib/pkp/classes/core/Dispatcher.inc.php:132' called 'PluginRegistry::loadCategory',
  14 : 'lib/pkp/classes/core/PKPApplication.inc.php:252' called 'Dispatcher->dispatch',
  15 : 'index.php:68' called 'PKPApplication->execute'
```

It would be possible to use a composer dependency to pre-set the constant `LOCALE_REGISTRY_FILE`:
https://github.com/pkp/pkp-lib/blob/6d3edaa3ad9ee19182dc4d4e849635062c6a1a9a/classes/i18n/PKPLocale.inc.php#L24-L25
That seems kludgy.

A guaranteed, but unwelcome, solution would be to add a new `config.inc.php` setting where the location of the locales.xml could be set, allowing an administrator to point that to a copy in the `files_dir` instead.

**Comment by asmecher** [comment]
@ctgraham, if it comes down to a `config.inc.php` adjustment, I'm not sure we've gained much beyond just modifying the `registry/locales.xml` file.

Off the top of my head, you should be able to edit the list of locales in memory, after the first load, by looking in the `Registry` for `allLocalesCache`.

**Comment by ctgraham** [comment]
The benefit to the config.inc.php setting would be that we segment the code from data: that is, the modified data of the new locale.xml file can live in the `files_dir`, rather than in the code.  But in general I do loathe config.inc.php settings for anything that shouldn't be restricted to a OS-level administrator.

The trick with the cache in my mind is that we'd need to intercept every time it is re-written.  This means adding a hook/s to `GenericCache::setEntireCache()` / `GenericCache::setCache()`, which seems heavy-handed given the frequency of caching, and error prone due to needing to duplicate the logic across both.

My current thinking is to refactor PKPLocale.inc.php and PKPLanguageAction.inc.php to not depend on `LOCALE_REGISTRY_FILE` as a constant, but for the file location to be an exposed property of PKPLocale.  Then, add a hook caller to the getter, allowing a plugin with a very, very low `seq` to modify it.  It works in my head, but hasn't been tried in code.

I was really hopeful for some black magic with:
```
define('RENAME_LOCALES_LOCALE_REGISTRY_FILE', 'plugins/generic/renameLocales/locales.xml');
if (!defined('LOCALE_REGISTRY_FILE')) {
        define('LOCALE_REGISTRY_FILE', RENAME_LOCALES_LOCALE_REGISTRY_FILE);
}
use const RENAME_LOCALES_LOCALE_REGISTRY_FILE as LOCALE_REGISTRY_FILE;

import('lib.pkp.classes.plugins.GenericPlugin');

class RenameLocalesPlugin extends GenericPlugin {
```
but the `use` appears to only affect this PHP file, not the current PHP context.  So, `LOCALE_REGISTRY_FILE` is re-defined to my new value with `plugins/generic/renameLocales/RenameLocalesPlugin.inc.php`, but is back to the original value everywhere else.

**Comment by NateWr** [comment]
@ctgraham out of curiosity, can you describe the use-case here? What is the language name that needs to be changed?

Do we have any other data files like this that should be exposed to replacement in urgent cases? Two approaches come to mind:

1. WordPress has support for what it calls a `sunrise.php` file. This is a file dropped into the root directory that if found will be loaded very early during the bootstrap. It's not installed/managed like a plugin but it provides an opportunity to hook into things before other plugins are loaded. For obvious reasons, it is only used in extremis. Perhaps something similar could be supported for us?

2. If we determine that there are other things (data files, constants like the plugin gallery URL, etc) that we should support overriding through a safe, reliable technique, perhaps it is worth thinking about a file fallback similar to the template loading hierarchy. If we designated a special directory for these files, we could check there for them first before loading the defaults shipped with the application. I'm thinking of cases where a host may want to set up journals with a different set of default user roles or email templates, for example.

**Comment by ctgraham** [comment]
The journal is asking "to change the default names of some of the languages in OJS so that they do not reference a specific country", which I suspect means that they want to select a single variant from among the options and to just list, "French", "Portuguese", etc.

**Comment by asmecher** [comment]
@ctgraham, the country name is removed from the locale list as of 3.4 (https://github.com/pkp/pkp-lib/issues/7871); for customizing the country list; would that resolve the issue for you?

**Comment by ctgraham** [comment]
Yes, I think so.

**Comment by asmecher** [comment]
Great, thanks! There are also some relevant discussions over here if you're interested: https://github.com/pkp/pkp-lib/issues/7352
