### ISSUE TITLE
[OMP] Catalog links to the wrong monograph and breaks format

### ISSUE THREAD

**Issue by alexdryden** [pkp/pkp-lib#6081]
Version: OMP 3.2.0-3

Issue: Under particular circumstances, the catalog page formatting is broken and thumbnails link to the wrong book. 

Example of broken formatting seen with the 'I just really like ham' book. 
<img width="1440" alt="Screen Shot 2020-07-09 at 2 55 27 PM" src="https://user-images.githubusercontent.com/47127862/87079583-43174180-c1f4-11ea-8f6d-e5f7157a29b1.png">
Also, the "Construction Aggregate" thumbnail links to the 'ham' book's detail page. See [here](https://scp.library.illinois.edu/books/index.php/sandbox/catalog).

Steps to reproduce:

1. Have at least two books
2. Assign the book with the second highest id as 'featured' and 'new release'
3. Assign the book with the highest id as *neither* 'featured' nor 'new release'
4. Below is the configuration that produced the catalog page above

<img width="1434" alt="Screen Shot 2020-07-09 at 2 59 06 PM" src="https://user-images.githubusercontent.com/47127862/87079959-de101b80-c1f4-11ea-9388-50afec1ad35c.png">

**Comment by alexdryden** [comment]
Update: the links are actually being generated incorrectly by the php, what is happening is that the featured book is sitting on top of the non-featured book and the featured book's url extends across the whole content area. We did a quick fix by restyling the `#is_featured` class.

<img width="1176" alt="Screen Shot 2020-07-09 at 3 51 00 PM" src="https://user-images.githubusercontent.com/47127862/87084446-3eef2200-c1fc-11ea-8697-558d46acaa36.png">

**Comment by asmecher** [comment]
@alexdryden, is the quick fix generally useful? If so, please consider opening a pull request!

**Comment by alexdryden** [comment]
@asmecher It wasn't before, but I just made the css selector a bit more restrictive so it only catches cases where the first child is not `.is_featured` and is followed by `.is_featured`. I **think** that won't have any side-effects and will catch all of the bad cases, but I'll do some testing on Monday and open the pull request if it is alright.

**Comment by asmecher** [comment]
That would be much appreciated, thanks!

**Comment by NateWr** [comment]
@alexdryden would you be willing to share a database dump for your sandbox site so that I can reproduce what's happening here? You can share it with me privately by DM at our forum (https://forum.pkp.sfu.ca/ -- I'm @NateWr there too). Otherwise you can sanitize the user details and post it publicly.

**Comment by alexdryden** [comment]
@NateWr it is a fresh install with just dummy data, so I don't think there is too much to sanitize. But there were a few other people testing, so I'll send it as a DM just in case.

**Comment by alexdryden** [comment]
@NateWr you should have a link to the dbdump. And I think I found the root problem [here](https://github.com/pkp/omp/blob/e473815f8d4de18b58b8f0e14f134bd14cef656d/classes/services/queryBuilders/SubmissionQueryBuilder.inc.php#L98-L107)

`$assocIds = array(1); // OMP only supports a single press`

The issue won't reproduce on the other press that is set up on our sandbox. And it is fixed when just passing an empty `$assocIds = array()` to the join statement. So I'm guessing this is some leftover technical debt from a time when OMP only supported a single press maybe? At any rate, I don't think there is a case where the press id passed should be hard coded. And removing it eliminates the stacking issue.

**Comment by NateWr** [comment]
Thanks for the test data @alexdryden! You're right it was the `array(1)` line. OMP is still in a kind of in-between place when it comes to supporting more than one press. It should be possible, but we don't know of many places doing this at the moment and so there are likely to be some bugs popping up. Please let us know if you encounter more!

I know that @ajnyga is planning to improve the multi-press support for his institution, but I'm not sure how far along that is.

The following PR should this bug. Once the tests pass and it's merged, I'll backport it to `stable-3_2_1` and `stable-3_2_0`.

PR:
https://github.com/pkp/omp/pull/848

**Comment by NateWr** [comment]
Merged and cherry-picked to `stable-3_2_1` and `stable-3_2_0`.
