### ISSUE TITLE
OJS - Editorial report email with wrong locale

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6085]
**Describe the bug**
The editorial report sent to editors is presenting wrong locale. It seems to be showing Arabic locale instead English.

**To Reproduce**
Activate the editorial report plugin and wait for the monthly email. They will show Arabic locale and the report with weird characters.

**What application are you using?**
 OJS 3.2.0

**Additional information**

**Notification**:
![task-menu-notification](https://user-images.githubusercontent.com/4992902/87195682-bccc2f80-c2c7-11ea-88f9-9a67d37afed3.png)

**Report**:
![report-locale](https://user-images.githubusercontent.com/4992902/87195873-cd7ca580-c2c7-11ea-885b-10a957d368af.png)

**Comment by asmecher** [comment]
Cross-linking to https://forum.pkp.sfu.ca/t/right-to-left-languages-improvement/61640 (and tagging @NateWr) as something similar was reported there.

**Comment by jonasraoni** [comment]
Hi @asmecher!

Here's a PR to fix it in stable-3_2_1: #6087 
Once everything is ok (maybe @israelcefrin can help us with testing), let me know which branches, besides the /master, need the correction.

---

The code isn't taking into consideration the context's primary locale. I've applied some fixes, but let me just raise some minor points =]

1. I've checked fast and looks like there isn't a place to persist the user's preferred locale in the database (I think we should), right? So I discarded the need of customized reports per user...

2. I saw the locales are missing random entries, wouldn't it be interesting to create/find a tool to fill these blank keys, maybe using Google Translate? We could mark them as "draft" somewhere to help the translators.

**Comment by NateWr** [comment]
Thanks @jonasraoni! Once we get confirmation on the fix I think we'll just need `master`, unless PS has a client on `stable-3_2_0` that particularly needs this. We may not do another 3.2.0.x release.

1. There is a `locales` column in the `users` table which stores a serialized array of working languages (one or more). These can be configured under the User Profile > Contact settings. I suspect that very few users make use of this. However, the email notification work that we plan for 3.4/3.5 will draw on this, so probably a good idea to use it when available.

2. We use weblate to manage translations now at https://translate.pkp.sfu.ca/. This should give an indication of how many strings are missing for each language.

**Comment by asmecher** [comment]
And just a note about machine translation (e.g. Google Translate) -- Weblate does have support for this, but the services that are feasibly good (e.g. Google Translate and DeepL) require paid API access, and I would very definitely want to have everything that was proposed reviewed by a good translator. Many of our locale keys are short and very dependent on the context of scholarly publishing, so I would expect a GIGO problem.

**Comment by jonasraoni** [comment]
TIL GIGO 😂

I agree, Google Translate would be just a filler, and at least a delayed review would be needed, but as an user I *think* I'd rather have this than the octothorpes...
Negative point: Awkward translations (but maybe it's better for a person with zero English knowledge?) + extra expenses.
Positive point: All languages from the translator would be somehow supported, which in turn could bring new users (and possibly translators).

**Comment by asmecher** [comment]
Merged for release in OJS/OMP/OPS 3.3.0. For users of 3.2.1-x, this commit can be applied: https://github.com/pkp/pkp-lib/pull/6087#issuecomment-662123506
