### ISSUE TITLE
OJS : email subject improvement when subject = Article Review Request 

### ISSUE THREAD

**Issue by mhvezina** [pkp/pkp-lib#6089]
_Context : OJS 3.x
(somehow related to closed issue https://github.com/pkp/pkp-lib/issues/6019)_

Just want to bring to your attention the actual suggestions in the PKP Weblate (made by [https://translate.pkp.sfu.ca/user/fgnievinski/](https://translate.pkp.sfu.ca/user/fgnievinski/)) @fgnievinski regarding email subjects :

[https://translate.pkp.sfu.ca/translate/ojs/emails/en_US/?type=suggestions](https://translate.pkp.sfu.ca/translate/ojs/emails/en_US/?type=suggestions)

emails.reviewRequestRemindAuto.subject => Article Review Request **- Reminder**
emails.reviewRequestRemindAutoOneclick.subject => Article Review Request **- Reminder**
emails.reviewRequestSubsequent.subject => Article Review Request **- Revised Version** 

I think those precisions make sense and would help better manage emails for reviewers/editors hence I'm voting for those suggestions to be adopted! (I will be glad to provide fr_CA translation afterwards)

**Comment by NateWr** [comment]
Thanks @mhvezina! One of the things that I've placed on our [roadmap](https://docs.google.com/spreadsheets/d/1QqFWdjuygCpzGcboo41h07fQDFY-3HEav74UTRXI0VA/edit#gid=1413181525) (tentatively for 3.4) is a comprehensive audit of our email subjects and content. Please keep these suggestions coming. :+1:

**Comment by fgnievinski** [comment]
related to #5730

**Comment by fgnievinski** [comment]
I think this issue could be closed as a result of #5730.

**Comment by asmecher** [comment]
Agreed. Thanks, all!
