### ISSUE TITLE
Encapsulate the global constants into classes

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6092]
**Describe the problem you would like to solve**
Having global constants is a possible source of collision. By encapsulating them into classes, they will get an improved meaning/context without the need of long names, e.g. `Role::ADMIN` instead of `ROLE_ADMIN`.
Another benefit is that an auto_loader will be able to locate the right file to load in order to use the constant.

**Describe the solution you'd like**
Replace all global constants by public class constants.
Instead of:
```php
define('SUBMISSION_FILE_PUBLIC', 1);
```

We would have:
```php
class SubmissionFile extends PKPFile {
  public const FILE_PUBLIC = 1;
}
```

**Comment by asmecher** [comment]
(Autoloading is filed here: https://github.com/pkp/pkp-lib/issues/6091)

**Comment by asmecher** [comment]
Here is a proposal for an approach we could roll out with low impact: https://github.com/asmecher/pkp-lib/commit/563f5e7e549eaef49869ec1ac272c0a7e36b0162

- Introduces a `strict` mode, enabled in `config.inc.php`, in which referring to constants globally will cause errors. Devs wanting to clean up can enable it as they work, and eventually we can turn on strict mode in automated tests.
- Preserves compatibility by continuing to use `define` to expose global constants when `strict` mode is disabled.

**Comment by jonasraoni** [comment]
That's a good transitioning state for me 👌

Just one comment before moving the constants into related classes:
Given the introduction of [enums](https://wiki.php.net/rfc/enumerations), perhaps we should check whether the `define` is a constant (such as `PI`) or an enumeration. If it's an `enum`, we can create a new file/class to host it (which can be transformed/extended into an `enum` later, as the basic usage is similar).

**Comment by asmecher** [comment]
Because there's a large outstanding merge for OPS, I'll hold off making the changes there and instead document them here:
- Need `strict` mode option added to `config.TEMPLATE.inc.php`
- Need to convert `ROUTE_` constants in Smarty templates to new syntax:
  ```
  find . -name \*.tpl -type f -exec sed -i -e "s/\$smarty.const.ROUTE_/PKPApplication::ROUTE_/g" "{}" ";"
  ```
- Need to convert `ROUTE_` constants in PHP code to new syntax (PKPApplication::ROUTE_...)
  To list candidates for manual correction (there aren't many):
  ```
  grep -l -e "[^:]ROUTE_" `find . -name \*.php`
  ```

**Comment by asmecher** [comment]
^ Actually, the changes on OPS weren't so widespread, so I went ahead and merged the initial changes. I'll leave this issue open and chip away at the remaining constants after the OPS changes and code reformatting stuff goes in.

**Comment by NateWr** [comment]
I think this was closed by accident?

**Comment by NateWr** [comment]
@asmecher Can you keep track of what has changed in this issue in our docs hub, https://github.com/pkp/pkp-docs/issues/663, so that we can make sure to update our docs and include this info in the next Release Notebook?

**Comment by defstat** [comment]
@NateWr sorry, no idea how that happened.. I never close issues in general.

**Comment by NateWr** [comment]
@asmecher I had a look at the changes to the `$templateMgr->setConstants()` method. I can see how it's meant to work, but it does permit a disconnection between constant names in PHP and JS. One of the benefits of the old approach was that the constant name on the server and client was always the same.

It looks like it is possible to get the value of a class constant from a string. The example in the [php docs](https://www.php.net/manual/en/function.constant.php) show this:

```php
constant('bar::'. $const);
```

Could this be used to revert to the old approach of passing in a string with the full constant reference? eg:

```php
$templateMgr->setConstant(['PKPSubmission::STATUS_QUEUED']);
```

I know this isn't the nicest way to handle constants across the system, but I haven't been able to come up with a better way to make these available to the UI.

**Comment by asmecher** [comment]
That would be possible -- but it would need to be...
```
$templateMgr->setConstants(['\PKP\submission\PKPSubmission::STATUS_QUEUED']);
```
...with the `setConstant` function presumably parsing `PKPSubmission::STATUS_QUEUED` part off, unless we wanted to force the use of the fully qualified classname in the JS side as well. (The class needs to be in the current namespace list in order for `constant('ClassName::xyz')` to work, and in this case, the namespace list would be defined by the `TemplateManager` class that `setConstants` is implemented in.)

(As a general practice I'm trying to move away from things involving classnames in strings.)

**Comment by NateWr** [comment]
Ok, you're right. That's ugly on the JS side. I guess we just need to think through how we're handling on the JS side a bit more... I'll have a think.
