### ISSUE TITLE
OJS3 - DB field type  TEXT is cutting off long content

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6096]
**Describe the problem you would like to solve**
As  a editor, I would like to past a long editorial team listing with pictures and bios in `HTML` (tags).

**Describe the solution you'd like**
It would be nice be able to past content over the limit of 64Kb. Changing the field type to `MEDIUM TEXT`.

**Who is asking for this feature?**
Journal Managers and Editors who add editorial team in "About"section.

**Additional information**
Table: journal_settings

![image](https://user-images.githubusercontent.com/4992902/87676071-26c05b00-c746-11ea-9e09-e085640d479b.png)

**Comment by Vitaliy-1** [comment]
Just mentioning here related issue: the same would be great to achieve for the `publication_settings` table as the full-text of the article will often exceed 64Kb.

**Comment by asmecher** [comment]
The following tables have had `settings_value` converted to `MEDIUMTEXT` for the 3.3 release:
- Context settings (`journal_settings` for OJS/OPS and `press_settings` for OMP)
- `publication_settings`
