### ISSUE TITLE
Move curl uses to Guzzle

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6097]
Guzzle supports a superset of what `curl` does (and doesn't require server-side `curl` support, which isn't always present).

The two have slightly different proxy configurations, and the `config.TEMPLATE.inc.php` doesn't properly capture both.

To resolve this, convert uses of `curl` over to using Guzzle instead.

**Comment by asmecher** [comment]
Draft PRs:
- https://github.com/defstat/pln/pull/49
- https://github.com/pkp/pkp-lib/pull/6175
- https://github.com/pkp/ojs/pull/2857

Needs testing:
- PLN plugin
- CrossRef deposits/status checks
- DataCite test [?dead test?]
- DOAJ deposit via API
- MEDRA plugin API exchange

Needs implementing:
- OPS CrossRef plugin adaptation

**Comment by isgrim** [comment]
https://github.com/pkp/orcidProfile also uses PHP curl.

**Comment by asmecher** [comment]
Thanks for the heads-up, @isgrim -- see https://github.com/pkp/orcidProfile/pull/154.

**Comment by asmecher** [comment]
@bozana, in line with https://github.com/pkp/ojs/pull/2597#issuecomment-756492977, could you look at porting the (updated) mEDRA plugin to using Guzzle?

**Comment by bozana** [comment]
You have already move it for mEDRA ca. 4 months ago :-) So mEDRA is done :-)

**Comment by asmecher** [comment]
@bozana, I have no recollection of that :) thanks for checking!

**Comment by asmecher** [comment]
All resolved, closing!
