### ISSUE TITLE
Make remote URL navigation menu item type multilingual

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [pkp/pkp-lib#6098]
We ran into an issue related to the inability to set a multilingual remote link for each specific language in the navigation menu item.

Expected:
Remote URL navigation menu item:
Title:
- for en_US: foo
- for other_lang: bar

URL for each language:
- for en_US: https://foo.com/en_US/bar
- for other_lang: https://foo.com/other_lang/bar

Actual:
Remote URL navigation menu item:
Title:

- for en_US: foo
- for other_lang: bar

And there is a problem URL for each language is the same because there is no option to set different URLs for other languages:
- for every_lang: https://foo.com/every_lang/bar

And we have created the possibility to set URL for each language, of course, I can make pull request (If anyone is interested necessary changes will be available here soon) but there is a problem - for now, it is not compatible with previous versions of OJS. 
It is using the navigation_menu_item_settings table to set a different URL for each language:

| navigation_menu_item_id | locale     | setting_name | setting_value                  | setting_type |
|-------------------------|------------|--------------|--------------------------------|--------------|
| 141                     | en_US      | remoteUrl    | https://foo.com/en_US/bar      | string       |
| 142                     | other_lang | remoteUrl    | https://foo.com/other_lang/bar | string       |

But making it this way will force every user of OJS after upgrade to set all remote links in the menu items again.

So maybe there is someone who can advise on this matter? I would love to see this feature in stock OJS and I would be very happy to contribute to this project. :)

**Comment by NateWr** [comment]
Hi @mariuszsienkiewicz, I think we'd accept a PR for this in the core application. The missing link is going to be a database migration. These migrations are run during upgrade and you can use them to convert data during the upgrade process.

In this case, you'll need to write a database migration that copies the URL to a setting in every language for each remote URL menu item. Here is an example of some of the migrations written for 3.3:

https://github.com/pkp/pkp-lib/blob/master/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php

**Comment by mariuszsienkiewicz** [comment]
Hi @NateWr :)
Thank you for your advice, do you think doing it this way would be enough?
``` php
private function _makeRemoteUrlLocalizable() {
		$siteDao = DAORegistry::getDAO('SiteDAO'); /* @var $siteDao SiteDAO */
		$site = $siteDao->getSite();
		$installedLocales = $site->getInstalledLocales();
		$navigationItems = Capsule::table('navigation_menu_items')->where('type', 'NMI_TYPE_REMOTE_URL')->get()->toArray();
		
		foreach($navigationItems as $navigationItem) {
			foreach($installedLocales as $locale) {
				Capsule::table('navigation_menu_item_settings')->insert([
					'navigation_menu_item_id' => $navigationItem->navigation_menu_item_id,
					'locale' => $locale,
					'setting_name' => 'remoteUrl',
					'setting_value' => $navigationItem->url,
					'setting_type' => 'string'
				]);
			}
		}
	}
```
Hmm... siteDao... Maybe there is a better option to get all the languages used for a specific context?
Of course for for every navigation item that has been changed we can set Url column to null and even we can drop this column if it is not used anywhere else.
What do you think about it? :)

**Comment by NateWr** [comment]
Looks like you've got the right idea!

```php
Capsule::table('navigation_menu_items')->where('type', 'NMI_TYPE_REMOTE_URL')->get()->toArray();
```

Try using `->pluck('url')`. See [Laravel docs](https://laravel.com/docs/7.x/queries#retrieving-results).

> Hmm... siteDao... Maybe there is a better option to get all the languages used for a specific context?

You'll want to get every context and loop over them. (Context is what we call a journal in OJS, a press in OMP, and a server in OPS.)

```
$contextIds = Services::get('context')->getIds();
foreach ($contextIds as $contextId) {
  $locales = $context->getData('supportedLocales');
  ...
}
```

And then you'll also need to do it at the site level because there can be navigation menu items there too.

> Of course for every navigation item that has been changed we can set Url column to null and even we can drop this column if it is not used anywhere else.

Yeah, once the `remoteUrl` has been moved to the settings table we'll want to drop the table column.

**Comment by mariuszsienkiewicz** [comment]
Thank you! :)
So what do you think about this peace of code? From what I can see it works as it should.
```  php  
private function _makeRemoteUrlLocalizable() {
    $contextService = Services::get('context');
    $contextIds = $contextService->getIds();
    foreach ($contextIds as $contextId) {
        $context = $contextService->get($contextId);
        $locales = $context->getData('supportedLocales');
        $navigationItems = Capsule::table('navigation_menu_items')->where('context_id', $contextId)->pluck('url', 'navigation_menu_item_id')->filter()->all();
        foreach ($navigationItems as $navigation_menu_item_id => $url) {
            foreach ($locales as $locale) {
                Capsule::table('navigation_menu_item_settings')->insert([
                    'navigation_menu_item_id' => $navigation_menu_item_id,
                    'locale' => $locale,
                    'setting_name' => 'remoteUrl',
                    'setting_value' => $url,
                    'setting_type' => 'string'
                ]);
            }
        }
    }
    
    $siteDao = DAORegistry::getDAO('SiteDAO'); /* @var $siteDao SiteDAO */
    $site = $siteDao->getSite();
    $supportedLocales = $site->getSupportedLocales();
    $navigationItems = Capsule::table('navigation_menu_items')->where('context_id', '0')->pluck('url', 'navigation_menu_item_id')->filter()->all();
    foreach ($navigationItems as $navigation_menu_item_id => $url) {
        foreach ($supportedLocales as $locale) {
            Capsule::table('navigation_menu_item_settings')->insert([
                'navigation_menu_item_id' => $navigation_menu_item_id,
                'locale' => $locale,
                'setting_name' => 'remoteUrl',
                'setting_value' => $url,
                'setting_type' => 'string'
            ]);
        }
    }

    Capsule::schema()->table('navigation_menu_items', function (Blueprint $table) {
        $table->dropColumn('url');
    });
}
``` 
Thanks in advance

**Comment by NateWr** [comment]
Looks good at first glance. Can you open a PR that makes all the changes necessary to support a multilingual remote URL?

**Comment by asmecher** [comment]
Sorry, @NateWr, it looks like I might've stepped on your toes -- I've worked through a code review on https://github.com/pkp/pkp-lib/pull/6132 and it's ready to merge as far as I'm concerned. Any objections?

**Comment by NateWr** [comment]
Great! No objections here!

**Comment by asmecher** [comment]
Thanks, @NateWr. @mariuszsienkiewicz, I've merged https://github.com/pkp/pkp-lib/pull/6132 into the `master` branch for release in OJS, OMP, and OPS 3.3 -- currently scheduled for release in Q4. Thanks for contributing!
