### ISSUE TITLE
Add a "country" field to journal setup

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6099]
Add a country field to journal setup.

**Comment by bozana** [comment]
where should the new country field appear:
- in settings > journal > masthead > in the journal identity part?
- when creating and editing a journal (together with title, initials, abbrev...)

**Comment by bozana** [comment]
@asmecher, do you maybe know more about this requirement -- where/how is this information used, an use case this is for, is this a required field,... ?

**Comment by asmecher** [comment]
Hi @bozana! Actually, I think this is no longer a requirement -- I had forgotten we have an entry here. It's possible to identify the country using the ISSN with a high degree of reliability. See: https://github.com/asmecher/beacon/blob/master/updateBeacon.php#L155

So I'll close the issue for now...

**Comment by stranack** [comment]
Because ISSNs aren't mandatory, we will still need to have a mandatory Country field. I'd suggest including it in the Journal Identity section of the Masthead.

**Comment by jonasraoni** [comment]
Hi!

I've created these initial PRs:
[pkp-lib](https://github.com/pkp/pkp-lib/pull/6832)
[OJS](https://github.com/pkp/ojs/pull/3067)
[OPS](https://github.com/pkp/ops/pull/130)
[OMP](https://github.com/pkp/omp/pull/941)

**Comment by asmecher** [comment]
Thanks, @jonasraoni!

Back in https://github.com/pkp/pkp-lib/issues/4946 we added a field in the Citation Style Language plugin for publisher place; I wonder if it would be possible to move that setting alongside this one, call it City, and use both the city and country fields to inform the CSL plugin. I would feel a little better about this field, especially making it mandatory, if it were more than single-use.

@stranack and @NateWr, I'm wondering what your opinions are for making the field required. As it stands, existing users who upgrade to a release with this change in place will be required to choose a country before they can save the form. I think that's the only way to get good data coverage, but it'll be annoying.

**Comment by jonasraoni** [comment]
@asmecher Ok, I can take a look at the citation plugin. A migration/cleanup script will be needed there 😁

About the required field, another option to decrease the annoyance (considering there might be users with several contexts to update), is to offer the user to just confirm a default country (we can take it from the ISSN/domain/IP) using a "post-upgrade" interface + notification.

**Comment by NateWr** [comment]
> Back in #4946 we added a field in the Citation Style Language plugin for publisher place; I wonder if it would be possible to move that setting alongside this one, call it City, and use both the city and country fields to inform the CSL plugin. I would feel a little better about this field, especially making it mandatory, if it were more than single-use.

I like this idea, but is there any risk of muddying the data? My understanding is that the data we're adding now is meant to be the journal's location. But I think the CSL property is meant to be the city of the publisher. There's a good chance these won't necessarily be the same...

**Comment by asmecher** [comment]
> There's a good chance these won't necessarily be the same...

Hmm, yes, let's leave this change for now, @jonasraoni -- I think there's room to gather these somehow but not the way I proposed earlier.

> offer the user to just confirm a default country

Hmm, that's possible... What about adding the Country field to the settings wizard, and making it required there, so that all new journals will require an entry -- but making the field optional in the regular settings form so it doesn't force a choice for existing journals?

**Comment by asmecher** [comment]
@NateWr, it looks like @jonasraoni has updated the PRs; would you mind taking another look (especially WRT your comments above about #5980 / #6042)?

@jonasraoni, don't forget to drop a note on the issue when you're ready for another round of review -- otherwise we're not sure when you're ready.

**Comment by NateWr** [comment]
@asmecher @stranack @jonasraoni I thought that we had settled on making this field not required? There are a couple of things we need to address about usability, not code:

1. Should the country field be required when creating a journal? That means an admin creating a new journal for, say, a client, would have to enter a country. My sense is that they are not the right people to do this, and so we'll end up with a lot of wrong data from an admin just putting something in to get past the form.

2. Once set, how will it be updated? Right now, it's only available to the admin in the edit context form (Admin > Hosted Journals > Edit). This field should exist alongside the ISSN fields, right?

**Comment by asmecher** [comment]
From @stranack:
> It should be in Journal Settings > Masthead
> in Publishing Details
> From there, a JM or Editor can update it easily

**Comment by asmecher** [comment]
Also, @stranack's opinion is that the field should be required.

**Comment by NateWr** [comment]
So correct me if I'm wrong, but I think the remaining changes are:

1. Make country field not required in the add/edit journal form.
2. Add country field to Settings > Journal > Masthead > Publishing Details and make it a required field in that form.

**Comment by NateWr** [comment]
Thanks @jonasraoni, all merged! In the future, when moving a locale key from OJS to pkp-lib, go ahead and move it in all languages. I went ahead and did this in https://github.com/pkp/pkp-lib/commit/a8989ad97e99b796c06ffc18a519959225c24c8b and https://github.com/pkp/ojs/commit/dd8afd3db2d18ee8107aa10f73ccd6bbb5b7e3fc.

Hopefully when https://github.com/pkp/pkp-lib/issues/6328 is solved we won't need to do this anymore! :joy:

**Comment by asmecher** [comment]
Heads-up that https://github.com/pkp/ops/pull/130 and https://github.com/pkp/omp/pull/941 didn't get merged, which broke the tests when submodules updated in OMP and OPS -- I've cherry-picked in the relevant changes.

**Comment by asmecher** [comment]
The OPS tests were breaking on a check on the country field being required -- I've committed a change that removes the check to get tests working again, but can you have a look, @jonasraoni? https://github.com/pkp/ops/commit/490bb83c035e927abb97cb5492879397e883779a
