### ISSUE TITLE
Submission::getSectionTitle doesn't return any value

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6102]
OJS 3.2.1

Submission object doesn't include sectionTitle property, only sectionId. Noticed it when was working on an article landing page in one of the themes.
The getter is also used In Citation Style Plugin and it, apparently, fails: https://github.com/pkp/citationStyleLanguage/blob/072cf2775a727ecb41fa66022f89429142835849/CitationStyleLanguagePlugin.inc.php#L330

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1 -- I've removed the broken/little-used `Submission:getSectionTitle` / `Submission::getSectionAbbrev` functions (and unused setters) and implemented this a different way where required. Committed to OJS, OPS, and citationStyleLanguage (`master` and `stable-3_2_1` for each).
