### ISSUE TITLE
Is the OJS Native XSD broken?

### ISSUE THREAD

**Issue by GrazingScientist** [pkp/pkp-lib#6113]
**Describe the bug**
I have a custom generated XML. When validating this XML with the OJS importexport [native.xsd](https://github.com/pkp/ojs/blob/master/plugins/importexport/native/native.xsd), the parser starts crying and yells at me that for the `article` element, it is not expecting `title` or `type`. Seriously, this is wrong!

Hence, I looked into the [native.xsd](https://github.com/pkp/ojs/blob/master/plugins/importexport/native/native.xsd) and it's included files and found it strange that a `article` is a extension of `submission`, which is defined as:

```
	<complexType name="submission">
		<sequence>
			<element ref="pkp:id" minOccurs="0" maxOccurs="unbounded" />

			<!-- Metadata -->
			<element ref="pkp:submission_file" minOccurs="0" maxOccurs="unbounded" />
			<element ref="pkp:pkppublication" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
		<attribute name="status" type="string" use="optional" />
		<attribute name="current_publication_id" type="int" use="optional" />
		<attribute name="date_submitted" type="date" use="optional" />
		<attribute name="submission_progress" type="int" use="optional" />
	</complexType>
```

No word of `title` or `type`.
On the other side, `pkppublication` has the searched declarations in it:

```
<complexType name="pkppublication">
		<sequence>
			<element ref="pkp:id" minOccurs="0" maxOccurs="unbounded" />

			<!-- Metadata -->
			<element ref="pkp:title" minOccurs="1" maxOccurs="unbounded" />
			<element name="prefix" type="pkp:localizedNode" minOccurs="0" maxOccurs="unbounded" />
			<element name="subtitle" type="pkp:localizedNode" minOccurs="0" maxOccurs="unbounded" />
			<element name="abstract" type="pkp:localizedNode" minOccurs="0" maxOccurs="unbounded" />
			<element name="coverage" type="pkp:localizedNode" minOccurs="0" maxOccurs="unbounded" />
			<element name="type" type="pkp:localizedNode" minOccurs="0" maxOccurs="unbounded" />
			<element name="source" type="pkp:localizedNode" minOccurs="0" maxOccurs="unbounded" />
			<element name="rights" type="pkp:localizedNode" minOccurs="0" maxOccurs="unbounded" />
			<element name="licenseUrl" type="anyURI" minOccurs="0" maxOccurs="1" />
			<element name="copyrightHolder" type="pkp:localizedNode" minOccurs="0" maxOccurs="unbounded" />
			<element name="copyrightYear" type="int" minOccurs="0" maxOccurs="1" />
			<element ref="pkp:keywords" minOccurs="0" maxOccurs="unbounded" />
			<element ref="pkp:agencies" minOccurs="0" maxOccurs="unbounded" />
			<element ref="pkp:disciplines" minOccurs="0" maxOccurs="unbounded" />
			<element ref="pkp:subjects" minOccurs="0" maxOccurs="unbounded" />
			<element ref="pkp:authors" minOccurs="1" maxOccurs="1" />
			<element ref="pkp:representation" minOccurs="0" maxOccurs="unbounded" />
			<element ref="pkp:citations" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="locale" type="string" use="optional" />
		<attribute name="language" type="string" use="optional" />
		<attribute name="date_submitted" type="date" use="optional" />
		<attribute name="date_published" type="date" use="optional" />
		<attribute name="version" type="int" use="optional" />
		<attribute name="status" type="int" use="optional" />
		<attribute name="primary_contact_id" type="int" use="optional" />
		<attribute name="url_path" type="string" use="optional" />
	</complexType>
```

Could it be that something was forgotten, when introducing the `pkppublication`?

**Comment by GrazingScientist** [comment]
I made a small code sample to run for reproducibility: [Download](https://drive.google.com/file/d/1RVIY16Y5LDONiLX3PPUiTwQTJsq9L28G/view?usp=sharing)

You need to install `lxml` to run it.

**Comment by asmecher** [comment]
@GrazingScientist, our integration testing includes an XML import test using this example document:
https://github.com/pkp/ojs/blob/stable-3_2_1/cypress/fixtures/export-issues.xml

The test is implemented here...
https://github.com/pkp/ojs/blob/stable-3_2_1/cypress/tests/data/60-content/ImportIssue.spec.js

...and currently passes in our [Travis CI test environment](https://travis-ci.org/github/pkp/ojs/jobs/711284602):
![image](https://user-images.githubusercontent.com/200411/88420562-e7c08400-cd9b-11ea-92ca-3c9c5ce74d42.png)

For another data point, I just ran an xmllint check:
```
$ xmllint --noout --schema plugins/importexport/native/native.xsd cypress/fixtures/export-issues.xml 
cypress/fixtures/export-issues.xml validates
```

**Comment by GrazingScientist** [comment]
I suspected you guys would have a unittest for this thing, but hoped you just forgot in this case. O:-)

Then probably there is something wrong with the `lxml` in Python. I will check out, your test (still hoping something is wrong there :-P) and close the issue later!

Thanks for your time @asmecher !

**Comment by asmecher** [comment]
Not a problem, @GrazingScientist. Note that starting with OJS 3.2.0 a lot of the metadata has been moved to the `publication` entity, in order to support metadata versioning. If you've been working with OJS pre-3.2.0 and updated to 3.2.x, you'll need to adapt older XML (thus also the tools that generate it) -- it's not intended to be a backwards-compatible format.

**Comment by GrazingScientist** [comment]
> it's not intended to be a backwards-compatible format.

I thought so! :) Thank you anyway!
