### ISSUE TITLE
OJS 3.2 - File not being available to reviewers when upload after review assignment

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6116]
**Describe the bug**
It is not possible to assign a file for reviewers when this file is upload after the review assignment. It lists the file with a "pink" label of warning related to the day it has been uploaded. However, it is not possible to add it to the existing review.

**To Reproduce**
1. Go to 'Dashboad > Submissions > Any submission in review stage active'
2. Click on 'Upload/Select files'
3. In the Modal click "Upload Review File" and upload a new one
4. Save and close the modal
5. See error

**What application are you using?**
 OJS  version 3.2.1

**Additional information**
![image](https://user-images.githubusercontent.com/4992902/88357256-a0ed7280-cd38-11ea-834d-ba83e618fbc1.png)

**Comment by NateWr** [comment]
> 5. See error

What's the error message? The description indicates that there's a problem with a review assignment but the reproduction steps only talk about uploading it to Review Files... can you clarify? What is the thing that you expect to happen that's not happening?

**Comment by israelcefrin** [comment]
Hi @NateWr 
In fact the editor just see the warning message but doesn't know why that file has the warning (it is not clear what is the error).

Then, when they attempt to assign the uploaded file to the current review round (to a newer reviewer) the system doesn't allow it. It is only possible to assign files that already had been uploaded before the review round has begun.

**Comment by NateWr** [comment]
> In fact the editor just see the warning message but doesn't know why that file has the warning (it is not clear what is the error).

Do you know what appears on screen to make them think there is an error? To debug, we'll need something to search for. Even if you don't know what the error message means, take a screenshot of it so that we can see.

**Comment by israelcefrin** [comment]
Hi @NateWr , it is required to switch the role to reviewer. It is possible to upload a document in review stage for reviewing assignment as a JM. However, the document won't be available to the reviewer. 
It seems a matter of privacy similar to this issue:
https://github.com/pkp/pkp-lib/issues/5134

**Comment by NateWr** [comment]
I think this is how it is supposed to work. When creating a Review Assignment, the editor has an opportunity to select which files should be available to the reviewer. Files that are uploaded later are not automatically available. The editor would need to click Edit for each Review Assignment to make the file available.

Whether that is the _best way_ to do it or not, I'm not sure. Ideally, when uploading a Review File, the editor would be able to choose to make it available to reviewers.

**Comment by israelcefrin** [comment]
Hi @NateWr , I think it was not possible to edit and make available after uploading it. That's the issue in fact. 
The editor or JM uploaded it and edit to make it available, the reviewer doesn't have access to it though.

**Comment by NateWr** [comment]
I'm unable to reproduce this with the current `master` branch. I did the following steps:

1. Submission is in review stage with one file for review.
2. Assign reviewer.
3. Upload new file for review.
4. Click "Edit" for reviewer and select both files to make them available to the reviewer.
5. Login as reviewer.
6. Download both files.

I was able to do this without any problem. Are you able to reproduce it following the steps you indicated in the original message? I had to improvise after step 4 because there aren't any details about the "see error" step.

**Comment by israelcefrin** [comment]
Hi Nate, could it be just a system glitch?
We had to fix it manually adding records to the review_files table. When we ran `SELECT * FROM review_files where file_id = FILE_ID;`  It returned no records.

**Comment by NateWr** [comment]
It sounds like maybe something failed during the original upload process, and the record in `review_files` didn't get added properly. Maybe there was an error the editor didn't notice? If you know the date/time (maybe you can get it from the `dateUploaded` column) you can check the error log for a fatal error.
