### ISSUE TITLE
[OJS] ImportExport XML sample file deprecated

### ISSUE THREAD

**Issue by GrazingScientist** [pkp/pkp-lib#6121]
I had issues with creating an import XML file for OJS using the [sample.xml](https://github.com/pkp/ojs/blob/master/plugins/importexport/native/sample.xml) file (#6113). Now I realized that it is the sample file that is still in the old schema. This should be updated...

**Comment by NateWr** [comment]
Thanks for reporting! @defstat do you happen to have an updated file lying around that could be used?

**Comment by asmecher** [comment]
Maybe we should just deprecate this in favour of `cypress/fixtures/export-issues.xml`?

**Comment by GrazingScientist** [comment]
> Maybe we should just deprecate this in favour of `cypress/fixtures/export-issues.xml`?

I would second this propsal, if I may contribute.

**Comment by asmecher** [comment]
Resolved -- thanks, all: https://github.com/pkp/ojs/commit/2b76a563299c73444f8296ce455e37505be1b40b
