### ISSUE TITLE
Error message when running incremental update to 2.4.8 using patch

### ISSUE THREAD

**Issue by OyvindLGjesdal** [pkp/pkp-lib#6123]
**Describe the bug**
When I attempt to upgrade ojs 2.3.7 to 2.4.8-5 from the command line, using the instructions from UPGRADE, I receive the following error message:

```
PHP Parse error:  syntax error, unexpected '[' in /prosjekt/wab/public_html/ojs/lib/pkp/classes/core/PKPString.inc.php on line 723
``` 
**To Reproduce**
Download patch from https://pkp.sfu.ca/ojs/ojs_download/ to OJS home.

Use php 5.4 (default in centos 7)

```
# Run from ojs home and change installed to off in settings.inc.php
patch -p1 < ojs-2.3.7._to_2.4.8-5.patch
sudo -u apache php tools/upgrade.php upgrade
```
**What application are you using?**
OJS 2.3.7 (trying to upgrade with latest patch from download page)

When I change https://github.com/pkp/pkp-lib/blob/2f26e48a636162d3e2e2e66a7e7a7665c25795b5/classes/core/PKPString.inc.php#L723

from `matches[0]` to `$matches[0]` the update begins and returns 

```
Successfully upgraded to version 2.4.8.5
```

**Comment by asmecher** [comment]
@OyvindLGjesdal, I suspect the patch didn't apply correctly -- I can't find any sign of that typo existing in the OJS codebase (or the patch file).

**Comment by OyvindLGjesdal** [comment]
Hi @asmecher 

I don't have much experience in php, so I'm not sure if this is an issue.
However I clicked through from https://github.com/pkp/ojs/tree/ojs-stable-2_4_8/lib to the corresponding pkp-lib, where I found the matches without prefixed sigil. (`code2utf(matches[0]); `)

 [See link to pkp-lib](https://github.com/pkp/pkp-lib/blob/2f26e48a636162d3e2e2e66a7e7a7665c25795b5/classes/core/PKPString.inc.php#L723)

The first and the second change introduced in https://github.com/pkp/pkp-lib/commit/bc78143e2f5bf6da99008dfd037a1073f753dc1e (Apr 9, 2019) uses sigil and no sigil on the same construct.
 
I find the same line in the patch: (ojs-2.3.7._to_2.4.8-5.patch)
```
284367:+                $str = PKPString::regexp_replace_callback('~&#([0-9]+);~', function ($matches) { return PKPString::code2utf(matches[0]); }, $str);
```
From grepping, I see there are other unsigiled matches vars, but it looks like they are in javascript.

I do have some other conflicts  to resolve from applying the patch to have a working upgrade.

Thanks for helping out :)

**Comment by OyvindLGjesdal** [comment]
I forked pkp-lib to create a pull request, but as you pointed out the sigil is present in pkp-lib  at pkp.lib origin/ojs-stable-2_4_8

I think the issue is that the ojs repo at pkp/ojs ojs_stable_2_4_8 points at the submodule of pkp-lib at 2f26e48a63, but has later been fixed without updating the pointer.

```
iff --git a/classes/core/PKPString.inc.php b/classes/core/PKPString.inc.php
index 4c4620b4e..9d24f6ade 100644
--- a/classes/core/PKPString.inc.php
+++ b/classes/core/PKPString.inc.php
@@ -720,7 +720,7 @@ class PKPString {
 
                // use PCRE-aware replace function to replace numeric entities
                 $str = PKPString::regexp_replace_callback('~&#x([0-9a-f]+);~i', function ($matches) { return PKPString::code2utf(hexdec($matches[0])); }, $str);
-                $str = PKPString::regexp_replace_callback('~&#([0-9]+);~', function ($matches) { return PKPString::code2utf($matches[0]); }, $str);
+                $str = PKPString::regexp_replace_callback('~&#([0-9]+);~', function ($matches) { return PKPString::code2utf(matches[0]); }, $str);
```

**Comment by asmecher** [comment]
> I think the issue is that the ojs repo at pkp/ojs ojs_stable_2_4_8 points at the submodule of pkp-lib at 2f26e48, but has later been fixed without updating the submodule

@OyvindLGjesdal, I think you're right, but I'm going to mark this a WONTFIX -- that upgrade is quite old, and we've deprecated patch-based upgrades anyway (as they don't include binaries e.g. images) and `git` provides better tools for merging modifications.
