### ISSUE TITLE
Send a weekly email to editors of pending tasks

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#6126]
**Describe the problem you would like to solve**
Editors are often busy and would benefit from a reminder of pending tasks.

**Describe the solution you'd like**
Every two weeks or so OJS could email editors about submissions needing attention.

**Who is asking for this feature?**
As editor in chief, I'd prefer if OJS reminded associate editors instead of having to do it myself.

**Additional information**
Competing manuscript management systems already offer a similar feature.

**Comment by NateWr** [comment]
Thanks @fgnievinski. I'd love to have a better system for indicating when tasks are overdue, as well as a way for editors to configure how they want to receive notifications.

The devil's in the details. Do you have any ideas about what tasks should trigger reminders and when those reminders should be triggered? If we can build up some good feedback from the community on how something like this should work, it might get included in our plans to work on emails and notifications over 3.4/3.5/3.6.

**Comment by fgnievinski** [comment]
I think the main use case would be when a submission stays with the designated editor more than one or two weeks awaiting for either:
- reviewer invitation and confirmation (where the editor in chief can set the minimum, normally two or three)
- a decision (acceptance, rejection, modification)

**Comment by fgnievinski** [comment]
A simpler alternative would be a reminder sent every monday or every other monday with a summary of pending tasks.

**Comment by NateWr** [comment]
That could be a good idea for an optional "here's what's happening" email on a regular basis. An editor could opt in to receiving a weekly or monthly round-up email that says how many submissions they have in each stage and when the last activity was on each submission (ie - 10 days ago, 92 days ago). It would be similar to the journal health report that Journal Managers now receive every month.

Can we compile a list of what would go into this email? I can think of:

- Number of active submissions in each stage.
- List of assigned submissions ordered by date of last activity (oldest first).

**Comment by fgnievinski** [comment]
in another manuscript handling system I get the following groups:
- New Assignments
- Submissions with One or More Late Reviews
- Submissions Requiring Additional Reviewers
- Reviewers Invited - No Response
- Submissions Under Review
then for each group there is a list of the manuscript title, authors and further details.

**Comment by NateWr** [comment]
Thanks @fgnievinski. Is that a weekly or monthly email?

**Comment by fgnievinski** [comment]
that's a weekly email update

**Comment by NateWr** [comment]
> Is 30 days long enough for inactive submissions?

The consensus in a brief poll in our slack community is that 30 days is the right length of time.

**Comment by NateWr** [comment]
The PRs have been merged to the `main` branch for OJS and OMP. The email was not added to OPS because the editorial activity is very different. If OPS needs an email like this, more work needs to be done to identify what tasks our outstanding and to test the email appropriately.

For now, the email is sent once a month. Our initial research suggested every 2 weeks was better, but our scheduled tasks system doesn't support this currently. When we improve our scheduled tasks system, we may want to send this email more often.

**Comment by NateWr** [comment]
I forgot to install the new email template in upgrades. Needs to be added to https://github.com/pkp/ojs/blob/main/dbscripts/xml/upgrade.xml.

**Comment by fgnievinski** [comment]
thanks @NateWr!

just for information: I get weekly reminders for a Springer journal using Editorial Manager. 

I'm afraid monthly might be too infrequent.

**Comment by NateWr** [comment]
Yeah @fgnievinski, at the sprint we discussed how different journals have different editorial rhythms. I'd like each editor to be able to set their own schedule. But we don't support that in our notifications system and we didn't have time during the sprint to work on that. Hopefully we'll be able to add that feature in some day.
