### ISSUE TITLE
DB Error: ERROR:  null value in column "submission_id" (database PostgreSQL)

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#6131]
**In Submission Wizard in first step the "Save and continue" button does not continue to the next step**
In Apache error log i see:
`PHP Fatal error:  Uncaught Exception: DB Error: ERROR:  null value in column "submission_id" violates not-null constraint\nDETAIL:  Failing row contains (104, null, 0, my-email@my-domain, 70, 1, 73). Query: INSERT INTO authors (email, include_in_browse, publication_id, user_group_id) VALUES (?, ?, ?, ?) in /data/ojswork/ojs-3.2.1-1/lib/pkp/classes/db/DAO.inc.php:703\nStack trace:\n#0 /data/ojswork/ojs-3.2.1-1/lib/pkp/classes/db/DAO.inc.php(231): DAO->handleError()\n#1 /data/ojswork/ojs-3.2.1-1/lib/pkp/classes/db/SchemaDAO.inc.php(79): DAO->update()\n#2 /data/ojswork/ojs-3.2.1-1/lib/pkp/classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php(428): SchemaDAO->insertObject()\n#3 /data/ojswork/ojs-3.2.1-1/lib/pkp/pages/submission/PKPSubmissionHandler.inc.php(171): PKPSubmissionSubmitStep1Form->execute()\n#4 /data/ojswork/ojs-3.2.1-1/lib/pkp/classes/core/PKPRouter.inc.php(391): PKPSubmissionHandler->saveStep()\n#5 /data/ojswork/ojs-3.2.1-1/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallReques in /data/ojswork/ojs-3.2.1-1/lib/pkp/classes/db/DAO.inc.php on line 703, referer: https://my-site:10443/index.php/compol/submission/wizard`

**What application are you using?**
 OJS 3.2.1-1, php 7.4.3 and **PostgreSQL** 11.8

**Additional information**
Seeing from [the forum](https://forum.pkp.sfu.ca/t/error-when-updating-from-3-1-2-4-to-3-2-0-1-with-postgres/59661/6) and therefore eliminating the "Not Null" from the "submission_id" column of the "authors" table the wizard continues but I don't know if there are unexpected consequences.

I use: `alter table authors alter column submission_id DROP NOT NULL;`

Doing so I find the _submission_id_ column always empty in the "_authors_" table.
All this applies only to an installation with PostgreSQL while in others with Mysql I don't have this problem at least it seems to me.

**Comment by asmecher** [comment]
The `submission_id` column in `authors` is deprecated and shouldn't be filled in for new submissions. Removing the constraint should be fine.

**Comment by eniocarboni** [comment]
Thank you so much.
If I have other problems related to this I will report them below.
