### ISSUE TITLE
The statistics notification is sent to roles that have no access to the interface

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6134]
**Describe the bug**
The statistics notification is sent to `ROLE_ID_MANAGER` and `ROLE_ID_SUB_EDITOR`, but the page is limiting the access to `ROLE_ID_SITE_ADMIN` and `ROLE_ID_MANAGER`.

**To Reproduce**
Send a notification by calling the "StatisticsReport" task, then as a `ROLE_ID_SUB_EDITOR` try to access the received link.

**What application are you using?**
OJS/master

**Comment by jonasraoni** [comment]
The proposal/original issue can be seen here #4844.

**Comment by asmecher** [comment]
Thanks, @jonasraoni! Merged to `master` and cherry-picked to `stable-3_2_1`.

**Comment by NateWr** [comment]
I don't think this is going to be enough. For these pages to work we also need to enable access to the API endpoints where some of this information is drawn from.

Are we sure that we want to enable all of the stats for subeditors? I don't think this came up at all during the lengthy scope and review process we did for stats, and I don't think we've received a request for it since launching, so I'm hesitant to chuck it in without checking first with some users.

What do you think? Can we ask around first?

**Comment by NateWr** [comment]
Looking back at the [original discussion document about the journal health reports](https://docs.google.com/document/d/19IYU37-SQIZNKNfGnPet1sN-xcJB63VcpFp96oVxyMo/edit#), it looks like it was presumed that all editors would receive the email, and that the email should indicate the number of assigned submissions.

So I think we're ok opening it up. We just need to add the role to the API endpoints. 

(I've asked for some feedback in our slack channel so we'll see if we get any dissenting opinions, but I suspect it will be ok.)

**Comment by jonasraoni** [comment]
> I don't think this is going to be enough.

I should've opened it as a draft PR, since it was late here and I didn't test =]

> So I think we're ok opening it up

Yeah, I remember that I've asked something about it to James and he said it was ok, but better to confirm.

**Comment by jonasraoni** [comment]
I saw the permission for section editors was confirmed, so I've linked a new PR to this issue, basically just added the permissions to the API endpoints and adjusted the administration menu.

**Comment by asmecher** [comment]
Thanks, @jonasraoni and @NateWr! I've merged https://github.com/pkp/pkp-lib/pull/6141 into `master`. I had previously merged https://github.com/pkp/pkp-lib/commit/c36073b3dc57abbf9b1bed4657cfcb860434b417 to `stable-3_2_1` -- @jonasraoni, should I revert that? Alternately, https://github.com/pkp/pkp-lib/pull/6141 would need adaptation to `stable-3_2_1`, I think.

**Comment by jonasraoni** [comment]
@asmecher as you wish, it won't cause any harm =]
I've linked the PR for `stable-3_2_1`.

**Comment by asmecher** [comment]
Merged -- thanks, @jonasraoni!
