### ISSUE TITLE
No published/unpublished list in Quicksubmit form

### ISSUE THREAD

**Issue by Tawffeek2** [pkp/pkp-lib#6138]
I have been using the Quicksubmit plugin without any problems but recently I have noticed that the form allows me to fill in all the details and upload the galley and save it. Then, it no longer gives me the published/unpublished option.
![galley](https://user-images.githubusercontent.com/69080918/89103268-d79a4b80-d410-11ea-900d-f5851edc091a.png)

When i go to the submission section, I can see the schedule for publication button but once I click, it does not allow me to proceed to the issue. Here how it looks like
![image1](https://user-images.githubusercontent.com/69080918/89103301-0dd7cb00-d411-11ea-99bf-7918776d6918.png)

Once I click on the schedule for publication, this is all what i see

![image 2](https://user-images.githubusercontent.com/69080918/89103315-2647e580-d411-11ea-96fc-02a2a48e6c1e.png)

Your assistance is highly appreciated.

**Comment by asmecher** [comment]
@Tawffeek2, some questions...
- What version of OJS are you using?
- What version of the QuickSubmit plugin are you using?
- Does anything appear in your PHP error log?
- Did anything change on your system when you started noticing this problem, e.g. an upgrade?

**Comment by Tawffeek2** [comment]
I have just upgraded to the latest version of OJS and I have also uploaded the quicksubmit plugin from the plugin directory.  However, i still see that the quicksubmit plugin can be upgraded even though I have installed the latest version.

**Comment by Tawffeek2** [comment]
As for PHP, I have little knowledge of PHP but I contacted my host and this is the response I get from them

Hey Tawffeek,

Thank you for contacting us, I hope that you're doing well!

Going through your cPanel account I am unable to find anything in the error_log of your site.

What you're referring to seems more like a development issue with your site and is not directly related to your hosting setup.

For this, it would be best to consider bringing this to the attention of an OJS or PHP developer.

If you have any further questions, please do not hesitate to contact us back at any time.

**Comment by asmecher** [comment]
@Tawffeek2, are you sure you're using OJS 3.2.1-2? That hasn't been released yet. See...
- [How do I find my PHP error log?](https://forum.pkp.sfu.ca/t/how-do-i-find-my-php-error-log/29374) (There should definitely be something there)
- [How do I determine my PKP software's version?](https://forum.pkp.sfu.ca/t/how-do-i-determine-my-pkp-softwares-version/28534)

**Comment by Tawffeek2** [comment]
Thanks for your assistance. I will check the above links. Sorry my version is 3.2.1.1

**Comment by Tawffeek2** [comment]
These are the errors I found in my PHP error log
[27-Jul-2020 18:59:32 Europe/Berlin] PHP Warning:  Declaration of QuickSubmitForm::display() should be compatible with Form::display($request = NULL, $template = NULL) in /home/qmufmkkn/public_html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.inc.php on line 23

[27-Jul-2020 18:59:32 Europe/Berlin] PHP Warning:  Declaration of QuickSubmitForm::validate() should be compatible with Form::validate($callHooks = true) in /home/qmufmkkn/public_html/ojs/plugins/importexport/quickSubmit/QuickSubmitForm.inc.php on line 23

**Comment by asmecher** [comment]
@Tawffeek2, those are just warnings and shouldn't cause problems (unless your PHP is configured to send them to the browser, which is not recommended). Look for something containing the word "error".
