### ISSUE TITLE
Easier to find upgrade button on install page

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#6140]
**Describe the problem you would like to solve**
When you upgrade a site using the web interface, at first sight is not clear where to find the upgrade section.

![imagen](https://user-images.githubusercontent.com/2779168/89111598-ff60d200-d457-11ea-942a-9dc5a3807429.png)

**Describe the solution you'd like**
Would be nice to highlight the upgrade section in the former page... or even better, rethink the page to make it clear that you can upgrade or install (accordion tabs?). 

**Who is asking for this feature?**
I'm thinking in the tech users that are asked to do the task but are not very familiar with OJS

**Additional information**
This is not a real issue. It's a potential feature request for an UI/UX interface improvement.

**Comment by NateWr** [comment]
Just dropping in a recommendation. In the current `master` branch (3.3 pre-release), you can use a new `<notification>` element on any backend page.

```
<notification>
  Whatever I want to say.
</notification>
```

**Comment by henriqueramos** [comment]
@NateWr Hello Nate, could you please check my pull requests to address this issue?

https://github.com/pkp/ojs/pull/2985
https://github.com/pkp/pkp-lib/pull/6571

Thank you!

**Comment by NateWr** [comment]
Thanks @henriqueramos, this is looking good! Just the one comment about the `$upgradeUrl`. Once that is done, can you also prepare pull requests for OMP and OPS?

**Comment by henriqueramos** [comment]
@NateWr Of course!

There's the pull requests for both repositories:

https://github.com/pkp/omp/pull/908
https://github.com/pkp/ops/pull/107

**Comment by NateWr** [comment]
:tada: all merged! Thanks @henriqueramos!
