### ISSUE TITLE
Move Report Generator out of Tools

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6145]
The Report Generator is available from two places in the sidebar menu ("Tools" and its own "Report Generator" link).

Move it out of Tools, and into its own page, possibly under the existing statistics handler.

**Comment by NateWr** [comment]
Added to 3.3 because the new navigation menus make this an obvious win.

**Comment by bozana** [comment]
@asmecher and @NateWr, do you maybe know/remember what happened with this functionality (choosing a preferred metric type): https://github.com/pkp/pkp-lib/blob/master/templates/management/tools/statistics.tpl#L14-L16 - I cannot find the file management/tools/form/statisticsSettingsForm.tpl, but lib/pkp/templates/statistics/defaultMetricTypeFormElements.tpl, both introduced here: https://github.com/pkp/pkp-lib/commit/ee04f6e43c7ab10cbde652b4880a73d0623692d0
It seems not to be used anywhere. 
We currently only have one metric type *_METRIC_TYPE_COUNTER, used in *UsageStatsReportPlugin, so I think we do not need it now, but...
If so, can I remove those lines? Also the file lib/pkp/templates/statistics/defaultMetricTypeFormElements.tpl?

**Comment by NateWr** [comment]
Yeah, I think it's ok to remove it. For a long time now we've only had one metric type.

**Comment by bozana** [comment]
PRs:
usageStats: https://github.com/pkp/usageStats/pull/40
pkp-lib: https://github.com/pkp/pkp-lib/pull/6403
ojs: https://github.com/pkp/ojs/pull/2928
omp: https://github.com/pkp/omp/pull/889
ops: https://github.com/pkp/ops/pull/88

**Comment by bozana** [comment]
@NateWr, could you take a look at the PRs?
