### ISSUE TITLE
[OPS] Allow submission search by ORCID ID 

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6146]
**Describe the problem you would like to solve**
As a moderator, I can't search for preprints from a given author by their ORCID ID.

**Describe the solution you'd like**
Allow ORCID ID to be searchable and retrieve preprints of the author with the ORCID ID I searched for.

**Who is asking for this feature?**
Moderators

[Edit: I adapted this from a more general description that included also end users (readers) and recommended the main search bar rather than the submission (back-office) submission list. -AS]

**Comment by asmecher** [comment]
@alexxxmendonca, this might be a problem best solved for readers by following the link to the ORCiD site, where the author will have a comprehensive list of their work; it's not a common case for us to need to limit searches by author to what's published within a specific installation, which is all we can hope to provide by coding in a search within our apps. I could see a need for a back-office search for moderators, though, who might want to review an author's previous contributions to the server in vetting a fresh submission. Could you describe the use cases a little more?

**Comment by alexxxmendonca** [comment]
@asmecher very useful for moderators, yes.

But for instance, if I want to search how many preprints a given author has, I would have to search for their name and there could be:

a) many ways in which an author has added their names (or many ways a submitting author added their names)
b) homonymous

**Comment by asmecher** [comment]
Would adding it to the search field on the submission list satisfy the requirement?
![image](https://user-images.githubusercontent.com/200411/89459353-5cd97500-d71d-11ea-8ec7-edc7a9db4041.png)

Currently the search field [accepts author given/family names](https://github.com/pkp/pkp-lib/blob/stable-3_2_1/classes/services/queryBuilders/PKPSubmissionQueryBuilder.inc.php#L399..L406):
```
->orWhere(function($q) use ($word) {
	$q->where('aus.setting_name', IDENTITY_SETTING_GIVENNAME);
	$q->where(Capsule::raw('lower(aus.setting_value)'), 'LIKE', "%{$word}%");
})
->orWhere(function($q) use ($word, $isAssignedOnly) {
	$q->where('aus.setting_name', IDENTITY_SETTING_FAMILYNAME);
	$q->where(Capsule::raw('lower(aus.setting_value)'), 'LIKE', "%{$word}%");
});
```

...but adding support for a full ORCID there would be pretty easy.

**Comment by alexxxmendonca** [comment]
It would be useful for the moderator, yes, but it would still require the action of searching for it. But I think highlighting previous submissions is a different feature on its own.

**Comment by asmecher** [comment]
@alexxxmendonca, I've adapted the issue's description to refer more to the moderator use case. If the public search is still of significant interest, could you file it separately and describe the use case? Meanwhile I've implemented the addition of ORCID searches in the submission list, which should serve the moderator use case. Thanks!
