### ISSUE TITLE
"Locate Reviewer" form not displaying search results

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6151]
In 3.2.1-1

If you perform a search for a reviewer, the results are not displayed if there is a problem with affiliations.  @NateWr and I worked through this and it appears that there's a "Error in render: "TypeError: can't convert null to object".  Fix inbound.

**Comment by NateWr** [comment]
Thanks! I've merged https://github.com/pkp/ui-library/pull/114 and backported it to `stable-3_2-1`.
