### ISSUE TITLE
[OJS] logout random problem with domain but not with ip address

### ISSUE THREAD

**Issue by molavy** [pkp/pkp-lib#616]
recently user reported logout from website randomly specific on post data to server
i check it and when i use domain address of website if must login on every post data 
but on accessing website with ip address there is no such problems

**Comment by asmecher** [comment]
@molavy, could you post this on our support forum (http://forum.pkp.sfu.ca/) rather than creating a bug entry?

**Comment by molavy** [comment]
thanks
http://forum.pkp.sfu.ca/t/logout-random-problem-with-domain-but-not-with-ip-address/2582
but there is no answer

**Comment by asmecher** [comment]
@molavy, there's a response now. Please be patient -- we're a small team, but we'll get to your question when we can.
