### ISSUE TITLE
Announcement mailout can fail if any user is unsubscribed from notifications

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6165]
Seen in 3.2.1-2

We have a large installation (17K+ users) and there was a report of the announcement mail failing.  Looking through logs, I found:

`PHP Fatal error:  Uncaught TypeError: Return value of AnnouncementNotificationManager::notify() must be an instance of PKPNotification, null returned`

which was being generated when the Announcement mail out tried to create an email for a user that did not want announcement notification emails.  There appears to be a check in the Announcement form, so I am not sure what specific combination of blocked notification setting was letting the user pass into the notification creation, but `PKPNotificationOperationManager.inc.php`  can return null from `createNotification` if it's handed a userId that does not want the notification, which creates the error.  Updating the Type hinting in `AnnouncementNotificationManager.inc.php` for the `notify` solves the problem.  Pull request forthcoming.

**Comment by asmecher** [comment]
Merged and cherry-picked to `stable-3_2_1`. Thanks, @jnugent!
