### ISSUE TITLE
Permit email header to include sender identity

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#617]
See http://forum.pkp.sfu.ca/t/email-header-add-name/1591

From Carola:
> I only added code to resolve the variable in the email header:

    if (!(strstr($header, '{$senderName}') === false)) {
        $header = str_replace('{$senderName}', Request::getUser()->getFullName(), $header);
    }

> but for general purpose, it may be better to resolve the variable in the whole body after the header and signature have been added:

    if (!(strstr($this->getBody(), '{$senderName}') === false)) {
          $this->setBody(str_replace('{$senderName}', Request::getUser()->getFullName(), $this->getBody()));
    }

> By the way: The default press setting for 'emailHeader' is

    "The following message is being delivered on behalf of {$pressName}."

> But in management->settings->workflow->emails only

    "The following message is being delivered on behalf of ."

> appears, the variable or press name is not visible (and also does not show up in the emails). If I add {$pressName} to the email header via the user interface, the variable is not resolved. Is this a bug?

> It would also be nice to add another line break after the email header. The mail body currently starts immediately behind the
    ______________________.
    Dear Mr xyz

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/pkp-lib/pull/618
https://github.com/pkp/omp/pull/132

Bruno, could you take a look?

**Comment by asmecher** [comment]
Carola, this code is for OMP 1.2, and there have been quite a few changes around email handling (for example, they're now HTML-enabled, and there's support for listing and selecting the variables that will appear in TinyMCE controls). For OMP 1.1.1, I think all you'll need are the changes to MailTemplate.inc.php that move the replacement of email variables with the associated text into the `send()` function instead of `assignParams()`. And the addition of the `senderEmail` and `senderName` parameters to `assignParams`.

**Comment by beghelli** [comment]
Done reviewing.

**Comment by asmecher** [comment]
Also ported to OJS master.
