### ISSUE TITLE
Many editorial statistics are not appropriate for OPS

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#6171]
The current internal statitics page is designed based on OJS and needs to be revised for OPS.

Related issues:
https://github.com/pkp/pkp-lib/issues/6119

**Comment by NateWr** [comment]
@ajnyga do you know if this work is resourced and scheduled to be done soon? Or just for tracking later?

**Comment by ajnyga** [comment]
First step here is to remove unnecessary editoria stats from OPS: 
pr: https://github.com/pkp/ops/pull/69

@asmecher 

I will probably create a new ticket for tracking any OPS specific editorial stat requirements

**Comment by asmecher** [comment]
Merged; thanks, @ajnyga!
