### ISSUE TITLE
[OPS/OJS] Support DOI for translations

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6172]
**Describe the problem you would like to solve**
Currently, DOIs are assigned at the submission level. However, some submissions have multiple galleys, such as translations, and yet the same DOI is associated to all translations.

As a workaround, we've been asking authors with translation of preprints to make new a submission. That way the translation has its own DOI. But it would be much better to have everything under the same ID but treat the DOIs differently.

**Describe the solution you'd like**
Ideally, the translation would have its own DOI or some way to identify in the metadata that it is a translation of another object.

See: https://0-support-crossref-org.libus.csd.mu.edu/hc/en-us/articles/214357426-Relationships-between-DOIs-and-other-objects 

**Who is asking for this feature?**
This would make sure the platforms are following best practices for assigning DOIs and it would benefit readers, authors and editors in general.

**Comment by isgrim** [comment]
It seems to me, that the doipubidplugin allows assignments of DOIs per Galley, if you have one Galley per Translation it should be possible to have one DOI per translation.

Maybe the theme you are using does not show Galley pubIDs?

![Screen Shot 2020-08-17 at 09 49 05](https://user-images.githubusercontent.com/2169369/90371429-401f3480-e06f-11ea-85dc-fc6fbaaa5988.png)

**Comment by alexxxmendonca** [comment]
Hi @isgrim !

That makes a lot of sense. I completely forgot about this option.

So, considering a submission with 2 PDFs, should we assign one DOI for the submission as a whole and one for each galley -- 3 DOIs in total?

Or should we assign one DOI for each galley and no DOI for the submission itself?

**Comment by NateWr** [comment]
I think it will be best to ask your DOI registration and metadata deposit organisation what they expect. For example, if you're using Crossref, you should probably ask them how they expect such information to be identified.

I'm going to close this as it's not an issue with the software. But this would be a great topic for our [Publishing Practices forum](https://forum.pkp.sfu.ca/c/publishing-practice/24).

**Comment by ajnyga** [comment]
Hi,

I do not think the posted content schema used for preprints supports registering galley DOIs. https://www.crossref.org/education/content-registration/content-type-markup-guide/posted-content-includes-preprints/

In effect a Crossref DOI is an identifier for the Landing page. This is very apparent in OMP where the Crossref DOI points to a landing page that might have different versions of the same book even with different ISBNs. 

I am not sure if the OJS Crossref plugin handles galley DOIs, we do not use them.

But like Nate mentions above, this is really a discussion with Crossref and if their schema changes, then we can see how to implement those changes to OPS.

**Comment by alexxxmendonca** [comment]
Just an FYI, we tested this in OPS and it really didn't behave as we expected.

The DOIs assigned to the galleys did not appear anywhere in the public interface and they were not registered in Crossref at all.

We used the "main" submission DOI for Galley 1 and the "translation" DOI for Galley 2.

Galley 1 worked well since it used the "main" DOI and it redirected to preprint the landing page (not the actual Galley).
Galley 2 didn't work, the DOI was not registered.

**Comment by ajnyga** [comment]
Yeah, Crossref to my knowledge only supports preprint DOIs that resolve to a landing page. I did leave the option to add galley DOIs to the DOI plugin in OPS because in theory someone could use something else to register DOIs and that some other service might have a different solution.

**Comment by alexxxmendonca** [comment]
Makes sense.
