### ISSUE TITLE
[OPS] Support for preprint withdrawal and removal

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6173]
**Describe the problem you would like to solve**
Currently there isn't a formal method of withdrawal and removal of a preprint that has been posted.

The only way of doing it is changing the PDF file with a thumbstone-like file with information of withdrawal. See an example here: https://preprints.scielo.org/index.php/scielo/preprint/view/528

However, the metadata are not updated to include the information that the preprint has been removed or withdrawn and the removal/withdrawal is not reflected on the statistics either.

**Describe the solution you'd like**
ASAPBio has came up with a set of best practices and recommendations for preprint withdrawal and removal at the **Defining preprint withdrawal & removal** section of this document: https://osf.io/8dn4w/

**Who is asking for this feature?**
It would be important for OPS to follow best practices of preprint withdrawal and removal. Readers, indexing services and the community in general would benefit from this.

**Comment by asmecher** [comment]
@alexxxmendonca, I think this is already covered by https://github.com/pkp/pkp-lib/issues/1813, no?

**Comment by alexxxmendonca** [comment]
@asmecher possibly yes! 

I did not remember of that issue, but perhaps that one is more geared towards journal articles? In general, the behavior is very close to preprints, so perhaps I should just add a comment that preprints should be considered and then link to the ASAPbio report as a reference?

**Comment by asmecher** [comment]
John has made a proposal for how OPS would handle this (with more author control) -- see https://github.com/pkp/pkp-lib/issues/1813#issuecomment-669427522. Yes, please follow up over there with input on OPS. Closing this one in favour of that!
