### ISSUE TITLE
new review round could suggest previous reviews to add

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#6177]
**Describe the problem you would like to solve**
When starting a new review round, the first step is to add reviewers.  Most often, we'd select the same reviewers as in the previous round.  

**Describe the solution you'd like**
The add reviewers dialog could highlight reviewers from previous round.

**Who is asking for this feature?**
journal associate editor

**Additional information**
-

**Comment by asmecher** [comment]
@fgnievinski, I think this is already filed at https://github.com/pkp/pkp-lib/issues/4246 -- does that issue capture your requirements?

**Comment by NateWr** [comment]
Closing this as I think it is a duplicate, but feel free to add more specifications to #4246 if you think it doesn't capture what you need.

**Comment by fgnievinski** [comment]
sorry for the duplicate, I should have searched.
