### ISSUE TITLE
Support text directionality in TinyMCE for RTL languages

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6181]
See https://forum.pkp.sfu.ca/t/rtl-support-in-emails/62348 for details:
> When using the Arabic locale, email contents are aligned from left to right. Is there a way to force emails to be aligned from right to left when using the Arabic locale?

The screenshot shows a TinyMCE email compose window with directionality defaulting to LTR, even though the rest of the interface is RTL.

TinyMCE appears to support directionality as a configuration option: https://www.tiny.cloud/docs-3x/reference/configuration/Configuration3x@directionality/

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/6190
https://github.com/pkp/ui-library/pull/116

Tests:
https://github.com/pkp/ojs/pull/2860

**Comment by NateWr** [comment]
Merged to `master`. I don't _think_ this needs to be backported to `stable-3_2_1`, does it?

**Comment by asmecher** [comment]
No, I'm OK with this just going to `master`. Thanks!
