### ISSUE TITLE
[OJS] 3.2.1.1 QuickSubmit Plugin not working

### ISSUE THREAD

**Issue by anton-vrba** [pkp/pkp-lib#6182]
I have installed OJS 3.2.1.1 and download from https://github.com/pkp/quickSubmit Version: 1.0.5 and installed on server public_html/physnew-com/plugins/importexport, but obtain below error:

Uncaught  --> Smarty: Unable to load template 'app:layouts/backend.tpl' in 'plugins-plugins-importexport-quickSubmit-importexport-quickSubmit:index.tpl' <--  thrown in /home/npn/public_html/physnew-com/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195

**Comment by anton-vrba** [comment]
and here is my system info:

Version | Major | Minor | Revision | Build | Date installed
3.2.1.1 | 3 | 2 | 1 | 1 | 2020-08-15


Setting Name | Setting Value
OS platform | Linux
PHP version | 7.2.33
Apache version | Apache
Database driver | mysqli
Database server version | 10.2.33-MariaDB

**Comment by asmecher** [comment]
@anton-vrba, which specific build of QuickSubmit 1.0.5 are you using? There are currently 1.0.5-0, 1.0.5-1, 1.0.5-2, and 1.0.5-3.

**Comment by anton-vrba** [comment]
It was 1.0.5.1 (quickSubmit-master.zip)  but now have found and installed 1.0.5.3 (quickSubmit-stable-3_2_1,zip) in the branches and it seems to work.  

Thanks for your quick reply.

**Comment by asmecher** [comment]
@anton-vrba, yes, 1.0.5-1 is not compatible with OJS 3.2.1-1. I'd recommend using the Plugin Gallery to discover and install plugins; it'll make sure the version you're downloading is appropriate for your version of OJS.
