### ISSUE TITLE
[OPS] PDF view showing "##article.pageTitle##" tag instead of the actual title page

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6188]
**Describe the bug**
When viewing a PDF file on the browser, the browser windon title is showing "##article.pageTitle##" instead of the actual title page.

**To Reproduce**
1. Go to any preprint.
2. Click on the PDF galley view.
3. Check window/tab name.
4. Quick link: https://preprints.scielo.org/index.php/scielo/preprint/view/1106/1661

**What application are you using?**
OPS 3.2.1.0

**Additional information**
![image](https://user-images.githubusercontent.com/4059679/90515636-51cd0e80-e139-11ea-87e1-d879d9cea311.png)

I am not sure what page title is expected here. Is there a standard behavior for OJS?

**Comment by NateWr** [comment]
Thanks @alexxxmendonca! I have resolved this and backported the fix to `stable-3_2_1`. I've filed a related issue to clean this up further in the future. https://github.com/pkp/pkp-lib/issues/6193
