### ISSUE TITLE
[OMP] Series is not saved when editing publication

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6194]
**Describe the bug**
When saving a publication's details in OMP, the `seriesId` is not saved properly. This bug was probably introduced when `seriesId` was moved from submissions to publications.

**To Reproduce**
1. Go to a submission's workflow.
2. Click Publication
3. Click Catalog Entry
4. Edit the Series and save.
5. Reload page and see that series was not saved.

**What application are you using?**
OMP 3.2.1

**Comment by asmecher** [comment]
@NateWr, I wasn't able to replicate this using `stable-3_2_1`. Are you using the tarball or the stable branch?

**Comment by NateWr** [comment]
My bad. This was filed from a note to myself as I was clearing out old emails. I can't reproduce in `master`.
