### ISSUE TITLE
Revenge of the edit links

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#6203]
**Describe the bug**
The edit links on the front-end submissions template fixed in #5753 may still fail after the 3.3 changes.

**To Reproduce**
1. Go to *default*/about/submissions
2. Click on Submission Preparation Checklist
    * *default*/management/settings/workflow#submission%2FsubmissionChecklist
    * target fails due to url encoding of anchor
3. Click on Author Guidelines
    * *default*/management/settings/publication#submission%2FauthorGuidelines
    * 404 not found
    * should be *default*/management/settings/workflow#submission/submissionChecklist
4. Click on Copyright Notice
    * *default*/management/settings/workflow#submission%2FsubmissionChecklist
    * target fails due to url encoding of anchor
4. Click on Privacy Statement
    * *default*/management/settings/website#setup%2Fprivacy
    * target fails due to url encoding of anchor

**What application are you using?**
 OJS 3.3 pre-release (HEAD https://github.com/pkp/ojs/tree/305239d6ae905bfd0d78ba738cc296162399c3b0)

**Additional information**
Running under Apache 2.4, PHP 7.2.14, with `restful_urls` on.

**Comment by NateWr** [comment]
Thanks! I'll get it sorted for 3.3!

**Comment by NateWr** [comment]
@asmecher to fix this I had to allow a `/` in a URL anchor. I think this is safe because this is how Vue Router works (see our [UI Library](https://docs.pkp.sfu.ca/dev/ui-library/dev/#/component/Badge)). Can you just confirm that [this regex](https://github.com/pkp/pkp-lib/pull/6348/files#diff-b1feaca85ec221df062297be3df0a42f7ccfb8e01654114fe8a83a71d803da4fR356) is an ok replacement for `rawurlencode`?

PR:
https://github.com/pkp/pkp-lib/pull/6348

Tests:
https://github.com/pkp/ojs/pull/2909

**Comment by asmecher** [comment]
It would be nice to rely on an outside toolset for validating anchors (your regexp would probably work for our purposes, but is missing e.g. `%xx` encodings). What about https://github.com/laminas/laminas-uri/blob/2.9.x/src/Uri.php#L994? The Zend Framework [also implements](https://framework.zend.com/apidoc/2.2/classes/Zend.Uri.Http.html) a `validateQueryFragment` function, though I'm not sure it's available without dragging in the whole enchilada.

**Comment by NateWr** [comment]
laminas-uri will validate the anchor but it won't perform a replacement on it. By the time we hit `PageRouter::url()` we're passed the validation stage and we need to return the most well-formatted URL given the input... Alternatively I could copy the regex over into our `preg_replace` for a cheap fix.

**Comment by asmecher** [comment]
No sense bikeshedding here when our required vocabulary for anchors is very limited. I'm OK with your original regexp.

**Comment by NateWr** [comment]
Merged!

**Comment by NateWr** [comment]
Re-opening this issue and assigning to the Themes project so that other themes can address this for 3.3.
