### ISSUE TITLE
Ensure stage in URL matches file ID

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6206]
In file download (and possibly elsewhere), several query variables are required:
```
http://localhost/.../index.php/journalPath/$$$call$$$/api/file/file-api/download-file?fileId=34&revision=1&submissionId=16&stageId=5
```
The `stageId` does not appear to be checked against the file's stage ID. Ensure that they match.

**Comment by asmecher** [comment]
This looks like a combination of
- ambiguity between submission stage (`WORKFLOW_STAGE_ID_`...) and file stage (`SUBMISSION_FILE_`...), both of which are called `stageId` at various points in the system, and
- access policies that are not defined to the level of detail that @NateWr and I expected after not looking into this for a while (in my case).

@NateWr's steps to duplication involve the file access policies for assistant roles (copyeditor, proofreader, etc). Those are defined for submission files in `lib/pkp/classes/security/authorization/SubmissionFileAccessPolicy.inc.php` ([code for 3.2.1-1](https://github.com/pkp/pkp-lib/blob/3_2_1-1/classes/security/authorization/SubmissionFileAccessPolicy.inc.php#L181..L208) shown):
```
// 1) Assistants can access whitelisted operations...
$contextAssistantFileAccessPolicy = new PolicySet(COMBINING_DENY_OVERRIDES);
$contextAssistantFileAccessPolicy->addPolicy(new RoleBasedHandlerOperationPolicy($request, ROLE_ID_ASSISTANT, $roleAssignments[ROLE_ID_ASSISTANT]));

// 2) ... but only if they have been assigned to the submission workflow as an assistant.
// Note: This loads the application-specific policy class
import('lib.pkp.classes.security.authorization.WorkflowStageAccessPolicy');
$contextAssistantFileAccessPolicy->addPolicy(new WorkflowStageAccessPolicy($request, $args, $roleAssignments, 'submissionId', $request->getUserVar('stageId')));
import('lib.pkp.classes.security.authorization.AssignedStageRoleHandlerOperationPolicy');
$contextAssistantFileAccessPolicy->addPolicy(new AssignedStageRoleHandlerOperationPolicy($request, ROLE_ID_ASSISTANT, $roleAssignments[ROLE_ID_ASSISTANT], $request->getUserVar('stageId')));

// 3) ...and if they meet one of the following requirements:
$contextAssistantFileAccessOptionsPolicy = new PolicySet(COMBINING_PERMIT_OVERRIDES);

// 3a) ...the file not part of a query...
import('lib.pkp.classes.security.authorization.internal.SubmissionFileNotQueryAccessPolicy');
$contextAssistantFileAccessOptionsPolicy->addPolicy(new SubmissionFileNotQueryAccessPolicy($request, $fileIdAndRevision));

// 3b) ...or the file is part of a query they are assigned to...
import('lib.pkp.classes.security.authorization.internal.SubmissionFileAssignedQueryAccessPolicy');
$contextAssistantFileAccessOptionsPolicy->addPolicy(new SubmissionFileAssignedQueryAccessPolicy($request, $fileIdAndRevision));

// Add the rules from 3
$contextAssistantFileAccessPolicy->addPolicy($contextAssistantFileAccessOptionsPolicy);

$fileAccessPolicy->addPolicy($contextAssistantFileAccessPolicy);
```
Essentially the implementation doesn't rely on the `stageId` for the file access policy -- that's used at other parts of the access policy tree, and is actually the workflow stage ID, not the file stage. The limitations on downloading a file are implemented as above, trusting users with an assistant role to be able to access submission files as long as they are assigned to a stage.

Making this finer-grained would require a mapping from file stage ID (which every file specifies) to workflow stage ID (which the request URL supplies in `stageId`). We have that in `SubmissionFileDAO::getWorkflowStageId`, but it needs to be checked to ensure that it's comprehensive.

**Comment by asmecher** [comment]
PRs **against `stable-3_2_1`** (maybe don't merge there!):
- https://github.com/pkp/ojs/pull/2866
- https://github.com/pkp/pkp-lib/pull/6208

I propose that we don't port this (at least immediately) to `stable-3_2_1`. Our integration tests don't cover download behaviour, so I think we'll need better testing than a build can afford us -- e.g. OJS/OMP/OPS 3.3.

**Comment by NateWr** [comment]
I've applied this to the changes for #6057 and this appears to close the gap for assistances, thanks!

**Comment by asmecher** [comment]
Thanks, @NateWr! Merged to `master`.
