### ISSUE TITLE
Multiple use of id="setup-button" in website settings

### ISSUE THREAD

**Issue by RBoelter** [pkp/pkp-lib#6209]
**Describe the bug**
id="setup-button" is used twice.
You can find it in the top tablist and in the side tabs.

**To Reproduce**
1. Go to '.../management/settings/website'

**What application are you using?**
 OJS 3.2.1

**Additional information**
![double_id](https://user-images.githubusercontent.com/7657717/91295016-afe19d80-e79a-11ea-9bd5-07f58f6acca1.jpg)

@NateWr

**Comment by touhidurabir** [comment]
@asmecher @NateWr  Just wondering as we plan to update the `id` for one of the mentioned case to remove the duplication, should we also rename the view `tab` name ? For example , if we plan to change the `id` for the section `Website Settings --> Appearance --> Setup` from `id="setup"` to `id="appearance-setup"`, should we also update it to `Website Settings --> Appearance --> Appearance Setup` to keep things cleaner and make sure `id` `name` reflect the name of `tab` ?

**Comment by NateWr** [comment]
@touhidurabir we don't need to change it. But we have had some UX feedback that having two tabs that both say "Setup" is confusing. I just haven't thought of a good replacement. 

I don't want to duplicate the word "Appearance" there. Both "Setup" tabs contain miscellaneous settings, so any name I can think of, like "Website Setup", kind of applies to both. I've just left this for us to solve later when we have the time to focus more on the settings area. But if you have some other ideas, happy to hear them.

**Comment by touhidurabir** [comment]
@NateWr in that case, I will not update it and better to wait to determine what will be proper replacement wording for it as I don't have any good one in my mind either . just going to fix the `id` duplication for now .

**Comment by touhidurabir** [comment]
Updated the `id` name for the `Website Settings --> Appearance --> Setup` section to `appearance-setup` .  

Pull requests

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/7853
[ojs](https://github.com/pkp/ojs)       -->  https://github.com/pkp/ojs/pull/3371
[customBlockManager](https://github.com/pkp/customBlockManager) --> https://github.com/pkp/customBlockManager/pull/70

for some reason it seems the tests for the [customBlockManager](https://github.com/pkp/customBlockManager) --> https://github.com/pkp/customBlockManager/pull/70 has failed even through it passed for my local tests , looking into it .

**Comment by touhidurabir** [comment]
`main` branch pull requests

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/7860
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3373
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/269
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1103
[customBlockManager](https://github.com/pkp/customBlockManager) --> https://github.com/pkp/customBlockManager/pull/71
