### ISSUE TITLE
Failed Ajax request or invalid JSON returned

### ISSUE THREAD

**Issue by akkadhim** [pkp/pkp-lib#6210]
Hi,
I have problem in loading email templates (or send any email) and tasks in the system, I tried to follow the solution in this thread :
[https://forum.pkp.sfu.ca/t/tasks-not-loading-for-certain-users/32074](url)
however it seems that my situation is not the same! please see below pictures

OJS version 3.0.2.0
OS platform : Linux
PHP version :  5.6.40

![image](https://user-images.githubusercontent.com/16191790/91296625-95f98800-e7a5-11ea-91a9-a1f49985b4c7.png)

![image](https://user-images.githubusercontent.com/16191790/91295047-1e2a5e00-e7a3-11ea-832d-9cb06c2de8db.png)

![image](https://user-images.githubusercontent.com/16191790/91294968-03f08000-e7a3-11ea-9651-d8108e4fc7d0.png)

**Comment by NateWr** [comment]
Hi @akkadhim, OJS 3.0.2 more than three years old now. We won't be backporting any fixes to that version and we strongly encourage you to update to OJS 3.2.1. You will need to check the server requirements as PHP 5.6 has reached end of life and is no longer supported.
