### ISSUE TITLE
Quick Submit Plugin notification error problem

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6212]
OJS 3.2.1,

Related to: https://forum.pkp.sfu.ca/t/errors-with-the-quicksubmit-plugin/62419

Under certain circumstances, the Quick Submit Plugin produces a fatal error:
```
Fatal error: Uncaught Error: Call to a member function assign() on null in /web/ojs-next/lib/pkp/classes/notification/PKPNotificationManager.inc.php:195
```
I'm not sure how to reproduce but I think the problem is that TemplateManager isn't defined here: https://github.com/pkp/pkp-lib/blob/523633b606f4d345dd328a0533a33c496af5f073/classes/notification/PKPNotificationManager.inc.php#L193 when notification type is `NOTIFICATION_TYPE_ERROR`

**Comment by asmecher** [comment]
Fixed, thanks!
