### ISSUE TITLE
Simplify 4-step reviewer process 

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6219]
A hosted client on OJS 3.1.2.4 has requested to simplify the reviewer process. Currently, it is a 4 step process to accept and complete. They would like to be able to remove/hide step 2 - Guidelines if no guideline has been provided. This ends up being an extra step for reviewers.

**Comment by asmecher** [comment]
@pmangahis, do they *really* not want to provide reviewer guidelines? It seems like a pretty important thing to establish with reviewers...

**Comment by pmangahis** [comment]
@asmecher A peculiar request indeed.

**Comment by asmecher** [comment]
It's possible to modify the code to drop the Guidelines step, but I don't think it'll be a high priority for us, as I think reviewer guidelines are a good practice and we should encourage their use.

**Comment by pmangahis** [comment]
Thanks, Alec. I'll let them know that there are no plans to change this.

**Comment by NateWr** [comment]
Closing for now.
