### ISSUE TITLE
[OJS] copyAccessLogFileTool reports "Success" even when shell command fails

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#622]
`exec` status should be checked
https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/tools/copyAccessLogFileTool.php#L180
and
https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/tools/copyAccessLogFileTool.php#L190

**Comment by ctgraham** [comment]
The associated PR is here: https://github.com/pkp/ojs/pull/551

**Comment by ctgraham** [comment]
This can be scheduled against 2.4.8 and closed based on https://github.com/pkp/ojs/pull/551

**Comment by beghelli** [comment]
Already fixed with pkp/ojs#551 merge
