### ISSUE TITLE
 Open Preprint Systems Installation

### ISSUE THREAD

**Issue by suresh-parabhoi** [pkp/pkp-lib#6220]
Dear all,

I am new user Open Preprint Systems. I am trying install this software  and i have not found any manual kindly help me. We are currently using OJS as We are planning to implement this for our unpublished documents kindly help me.   

Lambodara Parabhoi

**Comment by asmecher** [comment]
For general help, please post on our support forum: https://forum.pkp.sfu.ca
Please include as much information as you can about where you got stuck.
