### ISSUE TITLE
Warnings produced from PKPCurlHelper

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6223]
**Describe the bug**
Undefined variable: curlCh in \lib\pkp\classes\helpers\PKPCurlHelper.inc.php on line 45

**Comment by defstat** [comment]
@asmecher 

PR
[pkp-lib]: #6224

**Comment by asmecher** [comment]
Merged, thanks, -- though this code will be replaced by #6097 before 3.3 is released.
