### ISSUE TITLE
[OJS] copyAccessLogFileTool confuses Solaris with *.*

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#623]
https://github.com/pkp/ojs/blob/ojs-stable-2_4_6/tools/copyAccessLogFileTool.php#L116

`glob('*.*')` returns unwanted results in Solaris, but `glob('*')` works fine in Solaris and elsewhere.

See previous related discussion in Bugzilla:
http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8962

**Comment by ctgraham** [comment]
The associated PR is here: pkp/ojs#551

**Comment by ctgraham** [comment]
This can be scheduled against 2.4.8 and closed based on https://github.com/pkp/ojs/pull/551

**Comment by beghelli** [comment]
Already merged fix in pkp/ojs#551
