### ISSUE TITLE
Default theme ->  homepage image as the header background

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6231]
**Describe the bug**

Setting "Homepage image" as "header background" does not show the image in default theme.

**To Reproduce**

1.  Go to : settings -> appearance -> setup" 
1. Upload "homepage image"
1. Click Apperance  -> theme
1. Set :   "settings  -> apperance -> theme -> Show the homepage image as the header background."
1. Check the   header image on the frontend

**What application are you using?**

-  OJS 3.2.1
-   Multilingual installation: 2 languages

**Additional information**
* Tested tihs functionality on immersion theme, it works.
' 
FYI @NateWr

**Comment by NateWr** [comment]
It looks like this was fixed in f0a9c5d7f022c08ef6d50f40c4694a8fbdd77ea6. I've now backported it to `stable-3_2_1`.

**Comment by withanage** [comment]
Thanks Nate!
