### ISSUE TITLE
Update jQuery to 3.5.1

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6232]
It looks like jQuery versions less than 3.5 are throwing a security warning (see [forum post](https://forum.pkp.sfu.ca/t/is-it-possible-to-point-ojs-3-2-1-1-to-jquery-version-3-5-instead-of-using-jquery-version-3-3-1/62575?u=natewr) and [3.5 release notes](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/)). I don't believe that this effects us but we should upgrade with our next major release.

**Comment by NateWr** [comment]
@asmecher while trying to update just the jQuery composer dependency, I notice that it updated a bunch of dependencies in the `composer.lock` (and got rid of some that weren't used anymore, like pnotify). Is this ok to just run the composer updates or do we need to take more care here?

PR:
https://github.com/pkp/pkp-lib/pull/6233

Tests:
https://github.com/pkp/ojs/pull/2871

**Comment by asmecher** [comment]
@NateWr: On the `master` branch, yes, it's a good time to do a broad update. I'm sure there's a lot of dependencies needing re-resolving...

**Comment by NateWr** [comment]
There weren't any dependency conflicts (phew!) and the tests seem to be passing so :crossed_fingers:.
