### ISSUE TITLE
Authors should be reassured when reviewers are overdue or completed

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6235]
**Describe the problem you would like to solve**
The author is shown a message when reviews are overdue, but this message does not tell them what to expect. Authors should be given some additional contextual information so that they know editors have been made aware and will work to get the necessary reviews completed.

Similar information should be provided when reviews are completed, so that authors know that editors may need to seek further reviews, discuss the recommendations, and make a collective decision.

**Describe the solution you'd like**
The following is a mockup I did a long time ago. It provides a rough outline of what this could look like in a slighly different author view for their submission.

![author-review-status](https://user-images.githubusercontent.com/2306629/92401553-cfc37a80-f125-11ea-8fcb-40c70161c6aa.png)

**Who is asking for this feature?**
This arose out of feedback about the confusing status of the overdue reviews message that authors see. Initial work to remedy that is at https://github.com/pkp/pkp-lib/issues/6234. This issue provides a more involved solution.

**Comment by NateWr** [comment]
A [comment](https://forum.pkp.sfu.ca/t/the-status-message-a-review-is-overdue-shall-not-be-visible-to-the-author/62491/9?u=natewr) on the forum:

> To be honest, I do not think that it makes much sense (for us) to provide authors with more automatically generated status information (as is given in your mockup). I fear that this will result in even more emails to editors, asking for clarification etc. and add even more work on them. Review processes are very diverse, e.g., for some subjects it is much more difficult to find reviewers as for others, there are unforeseen delays etc. I would prefer to give authors a general description of the review process (which can be done already on the public journal website) and same broad time ranges or mean turn-around times. That’s it.

**Comment by aguen** [comment]
See also issue [https://github.com/pkp/pkp-lib/issues/4092](https://github.com/pkp/pkp-lib/issues/4092): "Hide Review Round status from author". As Alec wrote there

> we're not going to be able to find a balance of information that'll work for every journal, but in general I think authors find journals too opaque. 

And John Willinsky asked for basing decisions on openess/closedness of information on

> a larger strategy that follows from the responsibilities for making research publically available

The problem I see is that automatically generated status messages sometimes (often?) fail to communicate the more specific context information relevant for the respective submission and ask for even further additional explanations.

**Comment by NateWr** [comment]
Thanks for finding that discussion, @aguen! These issues overlap so I have added the comments here to that issue. I'll close this one in favor of that one. All future discussion can be added to:

https://github.com/pkp/pkp-lib/issues/4092
