### ISSUE TITLE
Crossref export XML problem

### ISSUE THREAD

**Issue by luanvardar** [pkp/pkp-lib#6236]
I have this problem in Crossref export XML, what i need to make to slow this problem?

[05-Sep-2020 20:47:37 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /home/cqdhhdvh/prizrenjournal.com/plugins/generic/funding/FundingPlugin.inc.php:207
Stack trace:
#0 /home/cqdhhdvh/prizrenjournal.com/lib/pkp/classes/plugins/HookRegistry.inc.php(107): FundingPlugin->addCrossrefElement('articlecrossref...', Array)
#1 /home/cqdhhdvh/prizrenjournal.com/lib/pkp/classes/filter/Filter.inc.php(451): HookRegistry::call('articlecrossref...', Array)
#2 /home/cqdhhdvh/prizrenjournal.com/classes/plugins/PubObjectsExportPlugin.inc.php(371): Filter->execute(Array, true)
#3 /home/cqdhhdvh/prizrenjournal.com/classes/plugins/PubObjectsExportPlugin.inc.php(195): PubObjectsExportPlugin->exportXML(Array, 'article=>crossr...', Object(Journal), false)
#4 /home/cqdhhdvh/prizrenjournal.com/plugins/importexport/crossref/CrossRefExportPlugin.inc.php(267): PubObjectsExportPlugin->executeExportAction(Object(Request), Array, 'article=>crossr...', 'exportSubmissio...', 'articles', false)
#5 /home/cqdhhdvh/prizrenjournal.com/classes/plugins/PubO in /home/cqdhhdvh/prizrenjournal.com/plugins/generic/funding/FundingPlugin.inc.php on line 207

**Comment by NateWr** [comment]
Asked and answered in the [forum](https://forum.pkp.sfu.ca/t/problem-after-upgrading-to-ojs-3-2-0-2-crossref-plugin-and-another-errors/59840/45).
