### ISSUE TITLE
[OJS] Published journal table of contents mixes up articles/reviews

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#624]
The test data shows 4 articles and 1 review for the back issue (Vol 1, No 1). But if you view the issue on the frontend it shows 1 article and 4 reviews.

It isn't actually swapping the reviews/articles, though. The item in the articles section is an article and the reviews section contains 3 articles and 1 review.

**Comment by asmecher** [comment]
Fixed. This turned out to be a couple of things -- an incorrectly named column name, and the way that sections were getting created we had duplicate sequence numbers in the database. To fix the latter, you'll need to reorder your sections:

Settings > Journal > Sections, Order, Save.
