### ISSUE TITLE
Change in documentation for page numbers in setup

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#625]
In **Setup > Step 4.3** the bit about page numbers could use an adjustment. The example includes pp. and then the page range, but based on export capability for things like CrossRef, those pp.s end up being problematic. I'd recommend just showing the basic page number range here so people don't take the example literally and end up having to change all their page numbers if they decide to use DOIs. 

Here's the bit: 

> Page numbers for items will be calculated and entered manually in the Table of Contents (e.g., pp. 13-26).

I'd propose: 

> Page numbers for items will be calculated and entered manually in the Table of Contents (e.g., 13-26).

Alternatively, I'd actually just recommend a first page and last page metadata option here in general. I know that's been suggested in [other tickets](https://github.com/pkp/pkp-lib/issues/333).

**Comment by asmecher** [comment]
Scheduling for OJS 2.4.7 for the sake of keeping it with issue #333.

**Comment by asmecher** [comment]
Done.
