### ISSUE TITLE
Add relations information to OPS CrossRef data

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6251]
Open Preprint Systems allows the entry of relation data, including the DOI of a published journal article from the preprint:
![image](https://user-images.githubusercontent.com/200411/94158708-91bd9a80-fe37-11ea-9b44-f7c5a5926bfc.png)

This data is not currently deposited to CrossRef from OPS. It would be great to add it to CrossRef relationship data:
https://www.crossref.org/education/content-registration/structural-metadata/relationships/

**Comment by NateWr** [comment]
I think it _might_ be added here: https://github.com/pkp/ops/blob/master/plugins/importexport/crossref/filter/PreprintCrossrefXmlFilter.inc.php#L270-L284. The obvious caveat is that this is likely to be updated after metadata is initially deposited and so some kind of status will be needed to identify preprints that need to be redeposited.

cc @ewhanson. Nothing you need to do here right now, just tagging you to let you know.

**Comment by ajnyga** [comment]
The piece of code referenced above handles the relationship between the different versions of the preprint. Each version in OPS can have their own DOI. I wrote the `PreprintCrossrefXmlFilter` when the `relations` data did not exist in OPS. 

I will add VoR DOI to the XML export as well, but like Nate points out above we will need to have means to redeposit as well. This is not only the case here, but also in other applications. Whenever the metadata of a published submission is changed, the DOI should be redeposited.

I will do a simple fix for OPS.

**Comment by ajnyga** [comment]
OPS: https://github.com/pkp/ops/pull/103

**Comment by ajnyga** [comment]
Closing this, merged some time ago.
