### ISSUE TITLE
[OJS 2.4.8.5] Reviewer Interest not showing properly in most browsers

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#6252]
**Describe the bug**
I think the javascript is broken in the script that retrive interests on the profile page, only Internet Explorer 11 is actually displaying these correctly at the moment.

**To Reproduce**
Open a Reviewer profile in a browser that is not Internet Explorer and the "Reviewing interest" will be blank.

**What application are you using?**
OJS 2.4.8.5

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
Internet Explorer 11:
![image](https://user-images.githubusercontent.com/18707781/94260928-62765e80-ff07-11ea-965e-6deb57e05029.png)

Firefox:
![image](https://user-images.githubusercontent.com/18707781/94260947-699d6c80-ff07-11ea-9964-dacd3a2a88cf.png)

Chrome (the textarea sometimes appear, it seems to show up when it doesn't detect javascript, I don't know why that would happen just reloading the page):
![image](https://user-images.githubusercontent.com/18707781/94260970-77eb8880-ff07-11ea-86f8-e9449a8d619f.png)

Edge:
![image](https://user-images.githubusercontent.com/18707781/94260979-7c17a600-ff07-11ea-9b0b-cf4a797baae0.png)

**Comment by luizbgomide** [comment]
Investigating further, if I disable the `enable_cdn` setting it seems to work again. I still think that something is odd since it work with IE11 with that setting on.

So this might not be an OJS issue. Maybe this is related to my server restrictions somehow? It worked before and the `enable_cdn` was on.

**Comment by asmecher** [comment]
Thanks for digging into this, @luizbgomide -- this is either due to the older versions of libraries used by 2.4.8-5 being taken offline as CDNs get rid of older content, or as you've suggested, browsers getting pickier about CDN usage. In any case, disabling the CDN is a good resolution, and I'd recommend upgrading to 3.x if you'd like to re-enable CDNs at some point.
