### ISSUE TITLE
Multilingual keywords not supported by PKP themes

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6254]
The way that multilingual keywords are retrieved was changed with the new versioning system. To get multilingual keywords, themes should use the approach adopted in the default theme:

https://github.com/pkp/ojs/blob/master/templates/frontend/objects/article_details.tpl#L147-L160

The following themes need to be updated:

- [x] Health Sciences
- [x] Classic
- [x] Immersion
- [x] Pragma
- [ ] Bootstrap3

**Comment by NateWr** [comment]
@Vitaliy-1 I've assigned this to you but let me know if you've got too much on your plate at the moment.

**Comment by Vitaliy-1** [comment]
@NateWr, I see you've already made changes regarding keywords for the Bootstrap theme: https://github.com/NateWr/bootstrap3/commit/5faec99cd17dd55ba88fbc9c3dfb9dfb2a477617. Can this issue be closed then?

**Comment by NateWr** [comment]
Although "fixed" in bootstrap3, it uses a different implementation from the default theme. I think I'd prefer to update that so that we're consistent. I can take this one for 3.3, shouldn't take long.
