### ISSUE TITLE
Privacy consent opt-in doesn't work in some themes

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6255]
**Describe the bug**
Each journal may have a separate privacy statement. In such cases, when registering through the site-wide registration form, the user must be able to opt-in to each one separately. This works in the default them but doesn't work in Bootstrap3 and may not work in other PKP themes (Health Sciences, Classic, Immersion, Pragma).

**To Reproduce**
1. Create more than one context in your instance.
2. Add a privacy statement to each one through the settings.
3. Go to the site-wide login form and opt-in to roles in more than one journal..
4. See that the opt-in checkboxes do not appear.

**What application are you using?**
OJS 3.2.x

**Additional information**
See the [forum post](https://forum.pkp.sfu.ca/t/user-registration-several-journals-privacy-statement-issue/62829?u=natewr).

**Comment by Vitaliy-1** [comment]
Should work fine for other themes but I'll take a look.

**Comment by NateWr** [comment]
Thanks!

**Comment by Vitaliy-1** [comment]
Health Sciences, Classic, Immersion and Pragma are not affected.
