### ISSUE TITLE
[OPS] Publication relate method should use service class to ensure hooks are fired

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6256]
**Describe the problem you would like to solve**
The `PublicationService::relate` method does not offer any way to hook into this event. That means plugins can not fire an update when this action is taken.

**Describe the solution you'd like**
The `PublicationService::relate` method should make use of the `PublicationService::edit` method instead of going directly to the DAO, [as it does now](https://github.com/pkp/ops/blob/master/classes/services/PublicationService.inc.php#L294-L299). This will ensure that the `PublicationService::edit` hook is fired and plugins have an opportunity to respond to the event.

**Who is asking for this feature?**
See the [forum post](https://forum.pkp.sfu.ca/t/ops-how-to-trigger-an-action-in-publications-relations-changing/62327/5).

**Comment by NateWr** [comment]
@ajnyga would you mind taking care of this one? Should be a pretty quick change.

**Comment by ajnyga** [comment]
@NateWr https://github.com/pkp/ops/pull/72

If you know a better way of fetching the Request object let me know.

**Comment by NateWr** [comment]
Looks good! That's becoming the standard way to get it now that Alec changed the `Application` from a static class to a singleton.

**Comment by ajnyga** [comment]
Thanks, good to know. You can close this?
