### ISSUE TITLE
copyrightHolder should be assigned as localized data

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6259]
OJS 3.2.1

Exposing `copyrightHolder` variable in Smarty, which was left for compatibility reasons, on the article landing page returns an array. Related to: https://github.com/pkp/healthSciences/issues/192
In the database, `copyrightHolder` is a localized setting.

The line: https://github.com/pkp/ojs/blob/ddd664f11f79c333d43b346667732cca62c43e00/pages/article/ArticleHandler.inc.php#L238
Should be changed to 
```
'copyrightHolder' => $publication->getLocalizedData('copyrightHolder'),
```

**Comment by asmecher** [comment]
Merged (`stable-3_2_1` and `master`), thanks!
