### ISSUE TITLE
Reduce access logic handling in issue template files

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#626]
`/templates/issue/view.tpl` includes a long chunk of code that handles access logic in the template:

```
		{if $issueGalleys}

			{* Determine access permission *}
			{if (!$subscriptionRequired || $issue->getAccessStatus() == $smarty.const.ISSUE_ACCESS_OPEN || $subscribedUser || $subscribedDomain || ($subscriptionExpiryPartial && $issueExpiryPartial))}
				{assign var=hasAccess value=1}
			{else}
				{assign var=hasAccess value=0}
			{/if}
			<h3>{translate key="issue.fullIssue"}</h3>
			<div class="tocArticle">
				<div class="tocTitle">{translate key="issue.viewIssueDescription"}
					<span class="tocGalleys">
					{if $hasAccess || ($subscriptionRequired && $showGalleyLinks)}
						{foreach from=$issueGalleys item=issueGalley}
							{if $issueGalley->isPdfGalley()}
								<a href="{url page="issue" op="viewIssue" path=$issue->getBestIssueId()|to_array:$issueGalley->getBestGalleyId($currentJournal)}" class="file">{$issueGalley->getGalleyLabel()|escape}</a>
							{else}
								<a href="{url page="issue" op="viewDownloadInterstitial" path=$issue->getBestIssueId()|to_array:$issueGalley->getBestGalleyId($currentJournal)}" class="file">{$issueGalley->getGalleyLabel()|escape}</a>
							{/if}
							{if $subscriptionRequired && $showGalleyLinks && $restrictOnlyPdf}
								{if $issue->getAccessStatus() == $smarty.const.ISSUE_ACCESS_OPEN || !$issueGalley->isPdfGalley()}
									<img class="accessLogo" src="{$baseUrl}/lib/pkp/templates/images/icons/fulltext_open_medium.gif" alt="{translate key="article.accessLogoOpen.altText"}" />
								{else}
									<img class="accessLogo" src="{$baseUrl}/lib/pkp/templates/images/icons/fulltext_restricted_medium.gif" alt="{translate key="article.accessLogoRestricted.altText"}" />
								{/if}
							{/if}
						{/foreach}
						{if $subscriptionRequired && $showGalleyLinks && !$restrictOnlyPdf}
							{if $issue->getAccessStatus() == $smarty.const.ISSUE_ACCESS_OPEN}
								<img class="accessLogo" src="{$baseUrl}/lib/pkp/templates/images/icons/fulltext_open_medium.gif" alt="{translate key="article.accessLogoOpen.altText"}" />
							{else}
								<img class="accessLogo" src="{$baseUrl}/lib/pkp/templates/images/icons/fulltext_restricted_medium.gif" alt="{translate key="article.accessLogoRestricted.altText"}" />
							{/if}
						{/if}
					{/if}
					</span>
				</div>
			</div>
		{/if}
```

I'd love to see as much of that logic as possible offloaded into the issue handler PHP file. Ideally, each galley might have its own flag indicating if it's available or not, so that the code can be simplified to something like this:

```
{if $issueGalleys}
	{foreach from=$issueGalleys item=issueGalley}
		{if $issueGalley->hasAccess}
			<a href="{url ...}" class="file {$issueGalley->getType()} has_access">
				{$issueGalley->getGalleyLabel()|escape}
			</a>
		{else}
			<span class="file {$issueGalley->getType()} no_access">
				{$issueGalley->getGalleyLabel()|escape}
			</a>
		{/if}
	{/foreach}
{/if}
```

As a template author I might not understand all the potential access control parameters. It would be easy for me to accidentally expose a file that shouldn't be exposed.

It would be better to encapsulate that information within the data so that I only have to look at a yes/no flag and I know what to do.

**Comment by asmecher** [comment]
Absolutely. There's some encapsulation of this in IssueAction for OJS 2.x, but that's also not very well written.

**Comment by NateWr** [comment]
Speaking of this access logic, are [these lines](https://github.com/pkp/ojs/blob/master/templates/issue/view.tpl#L62-L68) supposed to be *outside* of the `foreach` loop? Been trying to make sense of it but can't really understand the use-case, or what kind of information is meant to be displayed here.

**Comment by asmecher** [comment]
@NateWr, it looks to me like those lines are supposed to provide a legend explaining the icons that are used further down on each published article to indicate the article's access status.

**Comment by NateWr** [comment]
I've been trying to wrap my head around this a bit. The legend appears above, so I don't think those lines are it.

Also, I'm not entirely sure if `$restrictOnlyPdf` is correct [here](https://github.com/pkp/ojs/blob/master/templates/issue/view.tpl#L54-L60). Shouldn't the restricted/unrestricted access images appear beside a galley regardless of whether the payment gateway is only set up to restrict access to PDFs?

**Comment by asmecher** [comment]
@mfelczak is probably the best guy to ask -- he wrote that stuff. Michael, mind taking a look?

**Comment by NateWr** [comment]
I think I figured it out. It adds access icons to each galley only if `$restrictOnlyPdf` is true. Otherwise it just adds one icon to the whole row of galleys. I'll move forward on that assumption so hopefully someone will tell me if it's wrong.

**Comment by NateWr** [comment]
Closing this as several improvements have been made and the subscription stuff is going to be rewritten anyway.
