### ISSUE TITLE
Slim Application Error & An unexpected error has occurred. Please reload the page and try again.

### ISSUE THREAD

**Issue by IWCMoussaS** [pkp/pkp-lib#6261]
**Describe the bug**
This error is only on 
https://journal.iwc.int/index.php/jcrm/submissions#

**To Reproduce**
https://journal.iwc.int/index.php/jcrm/api/v1/_submissions?status[]=1 --> Ok
https://journal.iwc.int/index.php/jcrm/api/v1/_submissions?status[]=2 --> Ok
https://journal.iwc.int/index.php/jcrm/api/v1/_submissions?status[]=3 --> OK
https://journal.iwc.int/index.php/jcrm/api/v1/_submissions?status[]=4 --> Error - to Produce "Slim Application Error"
https://journal.iwc.int/index.php/jcrm/api/v1/_submissions?status[]=5 --> OK

**What application are you using?**
 OJS Current version: 3.2.1.1 (July 30, 2020 - 08:24 AM)

**Additional information**
https://journal.iwc.int/index.php/jcrm/api/v1/_submissions?status%5B%5D=4&status%5B%5D=3&status%5B%5D=5&searchPhrase=&count=20&offset=0&_=1601557281780
[HTTP/2 500 Internal Server Error 1380ms]

and this error
Uncaught TypeError: b is undefined
    modalOpen https://journal.iwc.int/js/pkp.min.js?v=3.2.1.1:315

**Comment by asmecher** [comment]
@IWCMoussaS, please check your PHP error log for details.

**Comment by IWCMoussaS** [comment]
https://github.com/pkp/pkp-lib/commit/b1932908f81749cf2698cb8b5a1744304b197ff9
