### ISSUE TITLE
Remove ADODB

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6264]
Remove ADODB.

**Comment by asmecher** [comment]
WIP branch: https://github.com/asmecher/pkp-lib/tree/remove_adodb

**Comment by asmecher** [comment]
@NateWr, I've finally got this [passing tests](https://travis-ci.org/github/asmecher/ojs/builds/741974952); could you take a preliminary review? There are notes on the coding implications at https://github.com/pkp/pkp-lib/issues/6264#issuecomment-702926627 (these should be adapted into the release notebook).

I'm OK to wait to merge this until after your submission file stuff is done, if that makes life easier.

**Comment by NateWr** [comment]
Looks really good @asmecher! I've done a review of those PRs with a few comments but nothing major. Thanks for the helpful guide to the changes in your comment. :+1: I've got a running list for the release notebook and I've added your comment to that.

**Comment by asmecher** [comment]
Thanks, @NateWr! I've run through the issues you flagged and fixed some minor ones, flagging a couple bigger ones with specific commits to resolve them. If you're OK with the result, next step will be to port to OMP and OPS, but I suggest holding off on that until you get the submission file stuff merged; then I'll rebase my OJS work on top of that before porting to the other apps.

**Comment by NateWr** [comment]
Great! Looks good to me. If that lastInsertId thing is ok as-is, I can have the submission file stuff merged tomorrow.

**Comment by asmecher** [comment]
@NateWr, I've added pulls for OPS and OMP to https://github.com/pkp/pkp-lib/issues/6264#issuecomment-702926627 -- could you have a quick look at these? They're essentially straight adaptations of the OJS PR (that is to say, lots of DAO class clean-up and little else).

**Comment by asmecher** [comment]
All PRs merged, not including the testing-purposes-only commits.

**Comment by asmecher** [comment]
Closing this; there will doubtlessly be related errors but they can either reopen this issue with details or file new entries.
