### ISSUE TITLE
New sample file for Native Import/export  

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6265]
**Describe the bug**
The `plugins/native/tests/functional/testIssue.xml` file was not getting imported by the native import/export plugin.

**What application are you using?**
 OJS version 3.2

**Comment by defstat** [comment]
@asmecher @NateWr 

**PR**
[OJS]: pkp/ojs#2876

Made a test file by completing the test suite of OJS and exporting the result. I also changed the placement of ImportIssue.spec.js test file from `Data Suite` to `Integration` which seems more appropriate.

**Comment by NateWr** [comment]
@defstat it looks like OMP may  need an update to its sample.xml file too? https://forum.pkp.sfu.ca/t/sample-xml-file-for-native-xml-plugin-for-omp/63183

**Comment by defstat** [comment]
@NateWr I have created a new native export/import file for OMP as well and backported both OJS and OMP to v3.2.1[https://github.com/pkp/pkp-lib/issues/6265#issuecomment-703234733]

**Comment by NateWr** [comment]
Thanks @defstat, I've gone ahead and merged it all in. :+1:
