### ISSUE TITLE
QuickSubmit Plugin [OJS 3.2.1.1] Keywords in a non-primary locale can’t be deleted

### ISSUE THREAD

**Issue by TobiasWantzen** [pkp/pkp-lib#6276]
**Description**
Keywords entered in a secondary locale can’t be deleted with the little red cross (x), only by hitting the backspace key.

**To Reproduce**
1. Go to 'QuickSubmit Plugin' to make a new submission
2. Add all must-have fields, and add keywords in all language locales
4. Try to delete a keyword of a non-primary locale by clicking on the litte red cross (x)

**Application**
 OJS 3.2.1.1

Thanks, Tobias

**Comment by asmecher** [comment]
@TobiasWantzen, can you check whether this is also fixed by https://github.com/pkp/pkp-lib/issues/6073? There's a patch and instructions to rebuild the CSS noted at the bottom of the issue.

**Comment by TobiasWantzen** [comment]
@asmecher I added the `z-index: 90;` for `.pkp_form .localization_popover_container_focus_forced .localization_popover`, which overwrites a `z-index: 99;` of `.pkp_form .localization_popover`. The bug stays the same: Clicking on a keyword item will close the non-primary locale field completely, and the keyword isn’t deleted.

**Comment by NateWr** [comment]
@TobiasWantzen can you confirm that the change took effect? CSS is compiled and cached, so you will need to go into Administration and click Clear Template Cache after changing the `.less` file. You may also need to clear cache on your browser.

**Comment by TobiasWantzen** [comment]
@NateWr I tested https://github.com/pkp/pkp-lib/pull/6078/files now on OJS3.1.2.1 and OJS3.2.1.1 – no effect. The bug stays the same: If I try to delete a keyword with the red x of the secondary language, the secondary language form imediately closes, and the keyword is still there.

**Comment by NateWr** [comment]
Thanks I will try to look at this soon to confirm the bug and find a fix.

**Comment by NateWr** [comment]
It looks like this was being caused because the focus drops out of the input field briefly when deleting an item, and the localisation popover was closing before the focus was put back into the input field. Fixed in https://github.com/pkp/pkp-lib/commit/8320f0e1172729ecae8552e46d2ac213a6823660 and merged to `stable-3_2_1` in https://github.com/pkp/pkp-lib/pull/6290.
