### ISSUE TITLE
Add filter for submission file grids

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#628]
Add a filter for these; according to Heidelberg it's useful for when lists get long.

**Comment by asmecher** [comment]
A commit: https://github.com/asmecher/pkp-lib/commit/a3be70fb7951f6db823fb93c72226b2a31ecf501
(Copyedit queries stuff needs merging first)

**Comment by asmecher** [comment]
Pull: https://github.com/pkp/pkp-lib/pull/635

Jason, mind reviewing this?

**Comment by asmecher** [comment]
Reassigning to Bruno for review.

**Comment by beghelli** [comment]
Reviewed.
