### ISSUE TITLE
Section Editors appear to be able to publish, but actually cannot

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6283]
Found in 3.2.1 stable.

We had a report of an issue where a user had assigned themselves to a submission as a Section Editor, and went through every stage, and in the Copyediting stage attempted to Schedule for Publication.  Clicking the Issue sub tab lets you appear to assign the submission to an issue, but after being told that all conditions are met and that they could publish immediately, they get told that they lack privileges.  Should they even be able to attempt all of this if they cannot do it in the last step?

**Comment by NateWr** [comment]
Hmm, a Section Editor assigned to the Production stage should be permitted to publish. In this setup, does the Section Editor map to `ROLE_ID_SUB_EDITOR`? Is this user group assigned to the Production stage? I'm not sure what other restrictions would prevent them from publishing.

**Comment by jnugent** [comment]
Hi @NateWr  this is an install that was a direct upgrade from OJS 2.4, with no other modifications.  Reassigning the user as a full journal editor to the submission fixed the problem.  They were indeed assigned to the Production stage.

**Comment by NateWr** [comment]
Can you reproduce it on that instance with another section editor or a new section editor? When I assign a section editor and login as them, I am able to publish.

**Comment by jnugent** [comment]
I'll get back to you.  This instance has no other articles in the copyediting stage that are ready to be published, and I don't want to unpublish/publish on their live install. I'll ask the editor to give me a heads up when they have another article ready to go.

**Comment by NateWr** [comment]
Closing for now but feel free to follow up when you can and we can reopen this.
