### ISSUE TITLE
[OMP] During upgrade to 3.3 script tries to drop submissions.section_id which doesn't exist

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6285]
OMP 3.3 (current master branch).

Upgrade from 3.2.0 throws error:
```
ERROR: Upgrade failed: DB: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'section_id'; check that column/key exists (SQL: alter table `submissions` drop `section_id`)
```
I don't think OMP has sections, at least I don't see the correspondent table and row in `submissions` and `publications` on my test instance. Think, [this statement](https://github.com/pkp/pkp-lib/blob/be20999f5ebee89d970ef42f6092a56b4f275d14/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php#L29)  should be moved from the shared library.

**Comment by asmecher** [comment]
@Vitaliy-1, a 3.2.0 database should have a `section_id` column in the `submissions` table; see https://github.com/pkp/pkp-lib/blob/3_2_0-0/xml/schema/submissions.xml#L164...L166. Was this database already partially upgraded from 3.2.x to 3.3.x? If so, maybe the column was already dropped?

**Comment by Vitaliy-1** [comment]
Yes, table `section_editors` contains a column named `section_id` but I don't see the same in the `submissions` table.
Just made a test installation of 3.2.0-3 downloaded from the site to confirm that.
```
SHOW COLUMNS FROM submissions

submission_id	bigint(20)	NO	PRI	
    NULL
	auto_increment	
context_id	bigint(20)	NO	MUL	
    NULL
		
locale	varchar(14)	YES		
    NULL
		
current_publication_id	bigint(20)	YES		
    NULL
		
date_last_activity	datetime	YES		
    NULL
		
date_submitted	datetime	YES		
    NULL
		
last_modified	datetime	YES		
    NULL
		
stage_id	bigint(20)	NO		1		
status	tinyint(4)	NO		1		
submission_progress	tinyint(4)	NO		1		
work_type	tinyint(4)	NO		0		

```

**Comment by asmecher** [comment]
> Yes, table section_editors contains a column named section_id but I don't see the same in the submissions table.

Sorry, you're right, I was looking under the wrong table. The definition of `section_id` in `submissions` [was in `dbscripts/xml/ojs-schema.xml` in 3.2.0-3](https://github.com/pkp/ojs/blob/3_2_0-3/dbscripts/xml/ojs_schema.xml#L453) but moved to `lib/pkp/xml/schema/submissions.xml` with https://github.com/pkp/pkp-lib/issues/2493.

I've just installed a fresh 3.2.0-3 from the .tar.gz package and `submissions`.`section_id` is definitely there -- do you see it in your XML descriptor before installing?

**Comment by Vitaliy-1** [comment]
> I've just installed a fresh 3.2.0-3 from the .tar.gz package and submissions.section_id is definitely there -- do you see it in your XML descriptor before installing?

I see it in OJS but not in OMP (in [3.2.0-3](https://github.com/pkp/omp/blob/3_2_0-3/dbscripts/xml/omp_schema.xml#L359)). As I mentioned, the problem is relevant only for OMP.

**Comment by Vitaliy-1** [comment]
Sorry, you mean moved to `lib/pkp/xml/schema/submissions.json`?

**Comment by Vitaliy-1** [comment]
My bad; but I also don't see it in the `lib/pkp/xml/schema/submissions.xml`

**Comment by Vitaliy-1** [comment]
This is the shared library timestamp that corresponds to OMP 3.2.0-3 version: https://github.com/pkp/pkp-lib/blob/3cbc385fc8ebd07f6117810fe72fc7abfa8abf5a/xml/schema/submissions.xml

**Comment by asmecher** [comment]
> My bad; but I also don't see it in the `lib/pkp/xml/schema/submissions.xml`

You're right again; `submissions.section_id` only appears in OMP 3.2.1-x. This drop should be made conditional as well on the column's existence.

**Comment by Vitaliy-1** [comment]
PR to pkp-lib: https://github.com/pkp/pkp-lib/pull/6312
Tests for OMP: https://github.com/pkp/omp/pull/872
