### ISSUE TITLE
[OPS] During upgrade to 3.3 script refers to nonexistent table review_forms

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6286]
OPS upgrade from 3.2.1 to 3.3 (current master branch).

During upgrade receiving the error message:
```
[pre-install]
[load: upgrade.xml]
[version: 3.2.1.0]
[code: Installer Installer::checkPhpVersion]
[code: Installer Installer::changeSubmissionStageToProduction]
[code: Installer Installer::installEmailTemplate]
[migration: PKPv3_3_0UpgradeMigration]
ERROR: Upgrade failed: DB: There is no column with name 'assoc_type' on table 'review_forms'.
```
Looks like the table `review_forms` doesn't exist in OPS and this part of the upgrade script should be moved from the shared library to OJS and OMP: https://github.com/pkp/pkp-lib/blob/be20999f5ebee89d970ef42f6092a56b4f275d14/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php#L83-L85

**Comment by asmecher** [comment]
@Vitaliy-1, do you want to take a crack at this one too? Your proposal makes sense to me.

**Comment by Vitaliy-1** [comment]
@asmecher, looking at this code once again, I don't see that this script changes the table in any way. Am I understand this correctly that here and in other places of the Migration script, it's expected the column to not be nullable? Although I can't find this on Laravel's site, `...->nullable(false)->change()` does the trick, at least on MySQL.

**Comment by asmecher** [comment]
@Vitaliy-1, I'm still learning the ins and outs of the Laravel schema toolset -- it appears that nullable is [presumed false](https://laravel.com/docs/7.x/migrations#column-modifiers) during schema creation, but it's possible that for already-existing columns you need to manually reset it using `nullable(false)` or no change will be made. Does your testing confirm this?

**Comment by Vitaliy-1** [comment]
@asmecher, yes, my test shows that nullable default value already exists, it should be explicitly changed. 

And for the JSON result of the statement on `authors` table: `$table->bigInteger('publication_id')->change();`:
```
{"type":"bigInteger","name":"publication_id","autoIncrement":false,"unsigned":false,"change":true}
```
And for `nullable(false)`:
```
{"type":"bigInteger","name":"publication_id","autoIncrement":false,"unsigned":false,"nullable":false,"change":true}
```
Underlying code presumably proves that. E.g.: [here](https://github.com/laravel/framework/blob/9c047344505da509c2b893eed7aac369a73e07eb/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L938) if the default value is true (as per [docs](https://github.com/laravel/framework/blob/9c047344505da509c2b893eed7aac369a73e07eb/src/Illuminate/Database/Schema/ColumnDefinition.php#L19)), only changing the correspondent `ColumnDefinition`'s property to the value that is interpreted as false will generate the needed query. For MySQL, it additionally checks `virtualAs` and `storedAs` properties.

**Comment by Vitaliy-1** [comment]
But I can be mistaken regarding the code interpretation, it's hard to read for me without digging.

**Comment by asmecher** [comment]
:+1: Thanks, please continue!

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib master: https://github.com/pkp/pkp-lib/pull/6347
OJS master: https://github.com/pkp/ojs/pull/2908
OMP master: https://github.com/pkp/omp/pull/878

**Comment by asmecher** [comment]
@Vitaliy-1, some of the columns you've changed to `NOT NULL` are indeed intended to be nullable (see e.g. `announcements.date_expire`, which should be `NULL` if the announcement doesn't expire). Could you review these again? For schema elements that haven't changed since `stable-3_2_1`, you can check for the `NOTNULL` XML element in the XML-based schema descriptors.

**Comment by Vitaliy-1** [comment]
Oops, sorry, don't know why I've changed that.

**Comment by Vitaliy-1** [comment]
@asmecher, done! 
I've rechecked and updated only where schema has a comment, like `<!-- Nullable for upgrade purposes only -->`. I cannot find related issues that are mentioned in some of those comments but I suspect they are resolved.

**Comment by asmecher** [comment]
That's great -- yes, it should be possible to change the columns flagged `Nullable for upgrade purposes only` to actually `NOT NULL` once the upgrade to 3.3 has otherwise been completed. Many of these are due to the way the versioning capabilities were introduced in the upgrade to 3.2.0.

**Comment by Vitaliy-1** [comment]
I've made the requested changes and hope that now it can be merged. @asmecher, please let me know if I still missing something.

**Comment by Vitaliy-1** [comment]
@asmecher, I've updated PRs once again. Can you merge if all looks good there? Regarding `edit_decisions.review_round_id` I suggest leaving it as is for this PR, anyway the issue was about another problem. If changes to that column needed, I mean use `null` instead of `0` for editor decisions outside of a review and explore related code, I can do that in another PR.

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1, I've merged the 3!
