### ISSUE TITLE
OJS Citation Style Language - Download option does not appear on frontend

### ISSUE THREAD

**Issue by IWCMoussaS** [pkp/pkp-lib#6287]
Hi, The download optons is not appear on the front-end even the "Downloadable Formats" are" active"

The third-party plugin is working(Citation Style Language)
.....
Downloadable Formats
Select which downloadable formats you'd like to offer your readers. Downloadable formats are typically used for importing into third-party bibliography management software, like EndNote or Zotero.
Endnote/Zotero/Mendeley (RIS) 
BibTeX
.......

Endnote/Zotero/Mendeley (RIS)  and BibTeX options are "active", but the option to download does not appear on the article page:
https://journal.iwc.int/index.php/jcrm/article/view/253

I believe the download "Endnote/Zotero/Mendeley" is working by entering the URL manually:
https://journal.iwc.int/index.php/jcrm/citationstylelanguage/download/ris?submissionId=253

Is there any extra configuration?

Thank you for your support as usual!

**Comment by IWCMoussaS** [comment]
I have changed the theme in our journal to use "default theme" and the download option appeared on the front-end:
..
 Download Citation
    Endnote/Zotero/Mendeley (RIS)
    BibTeX
...
So I believe the issue is related to "Bootstrap 3 Base Theme"
![Screenshot_2020-10-16 Blue whales off the Southern coast of Sri Lanka during the Southwest Monsoon Season IWC Journal of Ce](https://user-images.githubusercontent.com/61149934/96254208-d3f87880-0fac-11eb-91bc-a3418990838a.png)
![Screenshot_2020-10-16 Report of the workshop on chemical pollution and cetaceans J Cetacean Res Manage ](https://user-images.githubusercontent.com/61149934/96254278-ed012980-0fac-11eb-8c26-026f0e43e293.png)

**Comment by NateWr** [comment]
This bug waas specific to the Bootstrap3 theme. It has been fixed at https://github.com/NateWr/bootstrap3/issues/160 and the fix should be included in the next theme release.

**Comment by IWCMoussaS** [comment]
Hi @NateWr Thank you very much!
I have updated the new version, yes I would like to confirm it.
Just in case,  I would like to know is there any configuration that, the download citation is adding HTML characters on abstract section:

TY  - JOUR
AU  - Reijnders, P. J. H. 
AU  - Donovan, G. P. 
AU  - Aguilar, A. 
AU  - Bjorge, A.
PY  - 1999/01/01
Y2  - 2020/10/19
TI  - Report of the workshop on chemical pollution and cetaceans 
JF  - J. Cetacean Res. Manage.
JA  - JCRM
VL  - 
IS  - 
SE  - 
DO  - 10.47536/jcrm.v1i1.253
UR  - http://localhost/journal/index.php/jcrm/article/view/253
SP  - 01-30
AB  - **&lt;p&gt;**Report of the Workshop on Chemical Pollution and Cetacean**s&lt;/p&gt;**
ER  -


 http://localhost/journal/index.php/jcrm/citationstylelanguage/download/ris?submissionId=253&publicationId=283


https://journal.iwc.int/index.php/jcrm/citationstylelanguage/download/ris

Thank you!

![Screenshot_2020-10-19 Report of the workshop on chemical pollution and cetaceans J Cetacean Res Manage ](https://user-images.githubusercontent.com/61149934/96460270-f1cb1500-121a-11eb-883e-5f98ead39c2c.png)
?submissionId=253

**Comment by NateWr** [comment]
There's no configuration for this right now. I think that most citation formats don't support the HTML characters, so we [strip them](https://github.com/pkp/citationStyleLanguage/blob/master/CitationStyleLanguagePlugin.inc.php#L322), and there is not currently any logic in the code that would check the citation style and leave the HTML in for some. That's maybe an improvement we could consider separately.
