### ISSUE TITLE
Problem loading localized string in production galley approval

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#629]
The strings `manager.emails.disable` and `manager.emails.enable` are not loading in [ArticleGalleyGridCellProvider:71](https://github.com/pkp/ojs/blob/master/controllers/grid/articleGalleys/ArticleGalleyGridCellProvider.inc.php#L71).

Although the text isn't visibly displayed in current master, it is in my UI branch.

I'm going to chunk this into the beta milestone because without this text I spent nearly an hour trying to figure out how to get article galleys to appear on the frontend. :)

**Comment by NateWr** [comment]
Related commit: [NateWr/ojs:header_ui](https://github.com/NateWr/ojs/commit/df877d0a7788460ff5807c3722ad2dec9fea7dd9)

**Comment by asmecher** [comment]
Nate, locale components are brought in using...

   AppLocale::requireComponents(component1, component2, component3, ...);

...where each component is a `LOCALE_COMPONENT_...` constant (see `PKPLocale.inc.php` for definitions of these). You can grep for the locale file that contains the key, then find the matching constant. Make sense?

**Comment by NateWr** [comment]
Yeah I don't have any problem finding and modifying the strings. But this one doesn't seem to be getting "found". I get that occasionally throughout, where some strings just mysteriously don't load on one page load. But in this case it happens with every page load, so I figure something is missing.

**Comment by asmecher** [comment]
Adding...

    AppLocale::requireComponents(LOCALE_COMPONENT_PKP_MANAGER);

...to `ArticleGalleyGridCellProvider::getCellActions` resolves this for me, using your branch.

**Comment by NateWr** [comment]
Ahh ok, my mistake. I just assumed that all the locale strings would be loaded in for each page load. I'll take a look. May not make much sense to be using the manager strings there.

**Comment by asmecher** [comment]
Agreed, manager keys probably shouldn't be used. There's also `common.enable` and `common.disable`, which should already be loaded, so no need for another `AppLocale::requireComponents` in the bargain

**Comment by NateWr** [comment]
Forgot to reference from the commit. This is addressed in [PR #555](https://github.com/pkp/ojs/pull/555)
