### ISSUE TITLE
OJS is unable to tell phpMailer to work with protocol but without user authentication

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#6298]
**Describe the bug**
OJS is unable to configure phpMailer with some protocol (ie: SMTPSecure='tls) but without user authentication (SMTPAuth = false). 

**Why**
OJS params don't let you this combination because code forces user's authentication if you set any kind of "smtp_auth" (tls, ssl...):
https://github.com/pkp/pkp-lib/blob/1e4116c4f36b559fceceadd3073723fbbffe7d4c/classes/mail/Mail.inc.php#L479

It happens because in some cases OJS don't forward variables literally to phpMailer.
Specifically, in this case:

| OJS                      | --> phpMailer                                         |
|:-------------------:|:------------------------------------------- |
| smtp_auth = ssl   |  SMTPAuth = true & SMTPSecure=ssl   |

**What application are you using?**
 OJS, but affect all tools based on pkp-lib.

**Solutions**
As a temporary solution, a PR is attached to only set "smtpAuth=true" (in phpMailer) if you set a value for "smtp_username" (in OJS).

Existing configurations should keep working and make more sense to keep variables independent instead of forcing user authentication for all protocols.

The downside of this solution is the naming: OJS config variable "smtp_auth" will be potentially confusing... but is also confusing now because is SMTPAuth but also SMTPSecure.

A better final solution may be "introduce a syntax to config.inc.php that supports structured objects so that they can be passed down into dependent libraries (see also proxy syntax for Guzzle)".

**More info**
A similar/related issue can be found here:
https://github.com/pkp/ojs/pull/2720

**Comment by NateWr** [comment]
@asmecher I'll leave this one to you since I don't know much about our email handling. ;)

**Comment by asmecher** [comment]
https://github.com/pkp/pkp-lib/pull/6299 is actually fine as a long-term solution; I've merged it to the `master` branch. Thanks, @marcbria!

**Comment by marcbria** [comment]
Thanks to you both for the great work you are doing for the community.
