### ISSUE TITLE
[OJS] internal server error 500 on ListRecords/Identifiers/Identify

### ISSUE THREAD

**Issue by ezeqd** [pkp/pkp-lib#6302]
Hi, i have problems in my site https://revistas.imarpe.gob.pe/index.php/boletin/oai when i try to list the next

- ListRecords
- Identify
- ListIdentifiers

return to me a error 500, i don't know what happens, because ListSets & ListMetadataFormats it's ok

i'm running this on ubuntu 18.04 with:
`php -v
PHP 7.3.23-4`

`ojs-3.2.1-1`

And the php error log

[Sat Oct 24 02:28:40.002578 2020] [php7:error] [pid 9896] [client 181.29.101.229:60656] PHP Fatal error:  Uncaught Exception: DB Error: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '=' Query: SELECT\tGREATEST(a.last_modified, i.last_modified) AS last_modified,\n\t\t\t\ta.submission_id AS submission_id,\n\t\t\t\tj.journal_id AS journal_id,\n\t\t\t\ts.section_id AS section_id,\n\t\t\t\ti.issue_id,\n\t\t\t\tNULL AS tombstone_id,\n\t\t\t\tNULL AS set_spec,\n\t\t\t\tNULL AS oai_identifier\n\t\t\tFROM\n\t\t\t\tsubmissions a\n\t\t\t\tJOIN publications p ON (a.current_publication_id = p.publication_id)\n\t\t\t\tJOIN publication_settings psissue ON (psissue.publication_id = p.publication_id AND psissue.setting_name='issueId')\n\t\t\t\tJOIN issues i ON (CAST(i.issue_id AS CHAR) = psissue.setting_value)\n\t\t\t\tJOIN sections s ON (s.section_id = p.section_id)\n\t\t\t\tJOIN journals j ON (j.journal_id = a.context_id)\n\t\t\t\tJOIN journal_settings jsoai ON (jsoai.journal_id = j.journal_id AND jsoai.setting_name=? AND jsoai.setting_value='1')\n\t\t\tWHERE\ti.published = 1 AND j.enabled = 1 AND a.status = ?\n\t\t\t\t AND j.journal_id = ?\n\t\t\t\t\n\t\t\t\t\n\t\t\t\t\n\t\t\t\t in /home/ojs/lib/pkp/classes/db/DAO.inc.php on line 703, referer: https://revistas.imarpe.gob.pe/index.php/boletin/oai?verb=ListMetadataFormats

**Comment by asmecher** [comment]
@ezeqd, this is a character set/collation configuration issue, not a bug in OJS. I'd recommend reviewing these threads on the forum: https://forum.pkp.sfu.ca/search?q=implicit

**Comment by ezeqd** [comment]
@asmecher ohh i didn't noticed it... i will see this threads soon, thanks for the reply!

**Comment by ezeqd** [comment]
Thanks, that forum help me a lot, i posted a solution here https://forum.pkp.sfu.ca/t/ojs-3-2-1-1-blank-white-page-search-function/61536/27

**Comment by asmecher** [comment]
Thanks for following up -- I'm sure it'll be useful for someone else!
