### ISSUE TITLE
[OMP] Review attachments are fowarded as review files from internal to external review

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6304]
**Describe the bug**
When promoting a submission from internal to external review, the editor performs two steps:

1. Select files to share with the author, which includes files uploaded by reviewers.
2. Select files to carry over to the external review stage.

Files selected in step 1 and 2 are promoted to the Review Files in the external review stage, but only files in step 2 should be promoted.

**To Reproduce**
1. Create a submission and forward to internal review.
2. Create a review assignment and upload one file to it.
3. Upload a file to revisions.
4. Click Send to External Review.
5. Under the option to share files with the author, select the reviewer's file.
6. Click next.
7. Under the option to select files to forward to external review, select the revision file.
8. Click next.
9. See that both files are now in the Review Files grid in the External Review stage.

**What application are you using?**
OMP 3.2.1

**Comment by taslangraham** [comment]
The issue exists in 3.3 but, is not present in 3.4. Also, step 5 is not a part of the flow in 3.4 therefore only files selected(step 7) to be carried over to external review are forwarded to that stage.

**Comment by asmecher** [comment]
Thanks, @taslangraham! Closing as fixed -- this is not critical to address in 3.3.
