### ISSUE TITLE
The registration link stopped working (Giving HTTP 500 error). Earlier it was working

### ISSUE THREAD

**Issue by enthuvs** [pkp/pkp-lib#6308]
The registration link stopped working (OJS 3.2.0.3). Earlier it was working. Even the add user option from Users/Roles is not working.
![Capture-OJS](https://user-images.githubusercontent.com/8370546/97846602-3fb04480-1d14-11eb-93d6-74a50ae9990a.PNG)

**Comment by NateWr** [comment]
Please check your server's error log and post the logs recorded when encountering this error.
