### ISSUE TITLE
"Omit author names for section items from issues' table of contents" is ignored

### ISSUE THREAD

**Issue by eocarragain** [pkp/pkp-lib#6310]
**Describe the bug**
When configuring a journal section, there is an option to "Omit author names for section items from issues' table of contents". However, even when this is ticked, author names for items in the relevant section are still displayed in the issues' table of contents 

**To Reproduce**
1. Go to Settings -> Journal -> Sections
2. Edit a section & ensure "Omit author names for section items from issues' table of contents" is ticked
3. Go to the public page for an issue
4. The author names for section items are visible in the issues' table of contents

**What application are you using?**
 OJS 3.2.1-1

**Additional information**
See also #5955 
cc @AhemNason @NateWr

**Comment by NateWr** [comment]
This effects the default theme and likely other PKP themes.

**Comment by NateWr** [comment]
Fix from @eocarragain merged, thanks! It looks like our other themes already support this, it was just the property that was missing.
