### ISSUE TITLE
Health Science Theme 'Edit' button

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6313]
**Describe the bug**
When a JM is logged into the journal and goes to the front end submission page and clicks the 'Edit' links on this page it returns a 404 Not Found error.

![image](https://user-images.githubusercontent.com/50342731/98014718-d9c5ca80-1db0-11eb-9b0b-5f9b96f57ed4.png)

Users are still being directed to https://domain.co/index.php/abbreviation/management/settings/publication#submissionStage

Whereas the URL for the backend is now https://domain.co/index.php/abbreviation/management/settings/workflow

**What application are you using?**
Health Science Theme 1.0.7.0
Open Journal Systems 3.2.0.2

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
![Health Science Theme 1 0 7 0 broken link](https://user-images.githubusercontent.com/50342731/98014386-6de36200-1db0-11eb-8f27-d29706684a52.gif)

**Comment by Vitaliy-1** [comment]
Thanks! It was fixed for the Health Sciences, Classic, Pragma, and Immersion theme; for the former as a part of this commit: https://github.com/pkp/healthSciences/commit/22c7ed3e377805bcdbd4340d7150396d48209016. Those changes will be applied from the next release.

**Comment by NateWr** [comment]
Thanks @Vitaliy-1. I'm going to close this as fixed and I've assigned it to the 3.3 milestone since the theme will almost certainly make a new release for that.
