### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/html/ojs_journals/classes/install/Upgrade.inc.php:2504

### ISSUE THREAD

**Issue by RRafael** [pkp/pkp-lib#6319]
Hello, I'm trying to update OJS from version 3.0.2 to version 3.2.1-1, but when I run the update script it stops running and sends the error below. I have no idea what it is. Please ask for help if anyone knows what the solution is.

`Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/html/ojs_journals/classes/install/Upgrade.inc.php:2504 Stack trace: #0 /var/www/html/ojs_journals/lib/pkp/classes/install/Installer.inc.php(417): Upgrade->fixGenreIdInFileNames(Object(Upgrade), Array) #1 /var/www/html/ojs_journals/lib/pkp/classes/install/Installer.inc.php(263): Installer->executeAction(Array) #2 /var/www/html/ojs_journals/lib/pkp/classes/install/Installer.inc.php(186): Installer->executeInstaller() #3 /var/www/html/ojs_journals/lib/pkp/classes/install/form/UpgradeForm.inc.php(42): Installer->execute() #4 /var/www/html/ojs_journals/lib/pkp/pages/install/InstallHandler.inc.php(106): UpgradeForm->execute() #5 /var/www/html/ojs_journals/lib/pkp/classes/core/PKPRouter.inc.php(391): InstallHandler->installUpgrade(Array, Object(Request)) #6 /var/www/html/ojs_journals/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false) #7 /var/www/html/ojs_journals/lib in /var/www/html/ojs_journals/classes/install/Upgrade.inc.php on line 2504`

**Comment by asmecher** [comment]
@RRafael, could you begin in our support forum (https://forum.pkp.sfu.ca)? We'll move the conversation here if it turns out to be a bug rather than e.g. a data problem. I'd suggest starting with a look at this thread/post: https://forum.pkp.sfu.ca/t/ojs-html-articles/32902/28
