### ISSUE TITLE
File metadata should include DOIs

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#632]
Based on previous conversations. File metadata should include hooks into the public identifiers, especially DOI.

**Comment by jnugent** [comment]
Commits:  

https://github.com/pkp/omp/pull/134
https://github.com/pkp/pkp-lib/pull/633

**Comment by asmecher** [comment]
Thanks, Jason. I've passed this along to FUB to see if they've got any comments.

**Comment by asmecher** [comment]
Closing; I didn't get anything specific, so I'll assume it's OK.

**Comment by asmecher** [comment]
(Reopening per today's conversation so this doesn't get lost)

**Comment by asmecher** [comment]
@jnugent, a reminder to have a look at this one!

**Comment by bozana** [comment]
This issue can be closed -- the public identifiers on the file level are implemented in OMP master...
