### ISSUE TITLE
[OJS] CAST AS CHAR i postgres

### ISSUE THREAD

**Issue by majaroenne** [pkp/pkp-lib#6320]
I found a problem when using postgres.

A few places, using sql joins where issue_id is cast as char
f.x. in
OAIDAO.inc.php
AuthorDAO.inc.php

The problem is that cast as char in postgres works as 
cast as char(1) 
 so the join dosen't work for issus_id's bigger than nine

**Comment by NateWr** [comment]
cc @asmecher

**Comment by asmecher** [comment]
See also:
- https://forum.pkp.sfu.ca/t/search-not-working-after-upgrade-to-ojs-3-2-1-1/63239
- https://forum.pkp.sfu.ca/t/oai-not-working-ojs-3-2-1-1/63958

**Comment by asmecher** [comment]
Unfortunately MySQL won't accept the change from `CHAR` to `TEXT`, so this will need to be made database dependent.

**Comment by asmecher** [comment]
Trying the reverse approach: convert int-to-string conversions into string-to-int. This apparently has performance benefits too, according to https://github.com/pkp/pkp-lib/issues/6321.

PRs:
- https://github.com/pkp/ojs/pull/2910
- https://github.com/pkp/pkp-lib/pull/6356

**Comment by asmecher** [comment]
This tests fine for me (and Travis-ci), but confirmation based on real-world data would be wonderful!

**Comment by asmecher** [comment]
Unfortunately MySQL and PostgreSQL disagree fundamentally about whether `INTEGER` or `UNSIGNED` are types. `INTEGER` seemed like a good fit, and it worked locally on my MariaDB install, but Travis's MySQL install failed despite https://bugs.mysql.com/bug.php?id=62926 apparently being fixed long ago. Reverting to cast to `CHAR`, but with length specified; both seem to like that. I expect it won't perform as well as an `INTEGER` cast would have but that'll need to be addressed elsewhere.

**Comment by asmecher** [comment]
Merged and closing -- but additional testing on the changes posted at https://github.com/pkp/pkp-lib/issues/6320#issuecomment-730597845 is welcome!

**Comment by asmecher** [comment]
See also: https://github.com/pkp/ojs/pull/2961
