### ISSUE TITLE
Add a join on journal ID for search performance

### ISSUE THREAD

**Issue by hcoussy** [pkp/pkp-lib#6321]
Hi,
From https://forum.pkp.sfu.ca/t/search-is-slow-and-not-always-working-after-upgrade-to-ojs-3-2-1-1/63524/10
It appears that search queries are imposing a heavy load.
Adding a join on journal ID: 
improve performance: AND i.journal_id=s.context_id
Best regards
Helene

**Comment by asmecher** [comment]
@hcoussy, do you have a pull request coming for this issue? If you haven't done this before, I can help walk you through it.

**Comment by hcoussy** [comment]
Hi, @asmecher,
Yes can you help me to pull request for this issue?
Thanks

**Comment by NateWr** [comment]
Thanks @hcoussy! I'm going to suggest that you address all three of your recommendations together in this issue. @asmecher is the best one to evaluate them. I've copied them below for convenience.

> It appears that search queries are imposing a heavy load.
> The existing UNIQUE index from publication_settings table contains this 3 columns:
> publication_id
> locale
> setting_name
> 
> This condition in this query:
> JOIN publication_settings ps ON (ps.publication_id = p.publication_id AND ps.setting_name='issueId')
> doesn't use the UNIQUE index because the column ps.locale is missing
> 
> Adding a condition AND ps.locale IS NULL would cause the existing UNIQUE index to be used
> In Mysql we have to write AND ps.locale=''
>
> https://github.com/pkp/pkp-lib/issues/6322

> In Mysql this condition:
> JOIN issues i ON (CAST(i.issue_id AS CHAR) = ps.setting_value)
> implies that a query with condition k0.keyword_text LIKE ‘%%%’
> never ends
> 
> Replacing this condition by
> JOIN issues i ON (i.issue_id = ps.setting_value)
> OR
> JOIN issues i ON (i.issue_id = CAST(ps.setting_value AS UNSIGNED))
> permits the query to ends
> 
> As PostgreSQL doesn’t like to implicitly convert between strings and numbers, it could be a solution to use option 2 to make happy both Mysql and PostgreSQL
> 
> https://github.com/pkp/pkp-lib/issues/6323

**Comment by asmecher** [comment]
Thanks, @NateWr and @hcoussy! The `CAST` issue (previously filed as #6323) is separately filed at https://github.com/pkp/pkp-lib/issues/6320 -- apparently it's not just causing slowdowns. I have some PRs over there for testing.

**Comment by asmecher** [comment]
@hcoussy, for the remaining two issues:
> This condition in this query:
> ```
> JOIN publication_settings ps ON (ps.publication_id = p.publication_id AND ps.setting_name='issueId')
> ```
> doesn't use the UNIQUE index because the column ps.locale is missing
> 
> Adding a condition AND `ps.locale IS NULL` would cause the existing `UNIQUE` index to be used
> In Mysql we have to write `AND ps.locale=''`

...and...

> It appears that search queries are imposing a heavy load.
> Adding a join on journal ID:
> ```
> AND i.journal_id=s.context_id
> ```

...the best next step would be to open a separate Pull Request for each change.

You can do this either using the command line `git` tool on your own system: https://opensource.com/article/19/7/create-pull-request-github)

You can also do this without using the command line by using github.com...
1. Create your own fork of the repository you want to propose a change to
2. Edit the file on your fork (using the edit tool on the github.com website)
3. Create a pull request against the official PKP version of the repository you forked in step 1.

This is a great opportunity to learn about git/github but if you have too much on your plate I'm happy to take care of it!

**Comment by hcoussy** [comment]
Hi @asmecher,
Thank you for telling me what to do.
I don't know if I will be able to make time to do it.
I would appreciate you to take care of it this time.
Thanks again.
Best regards.
Helene

**Comment by asmecher** [comment]
Thanks, @hcoussy, I've committed all of these to the `master` branch; we're about to release the Release Candidate for OJS 3.3 and will test this thoroughly!
