### ISSUE TITLE
Add a condition for search performance

### ISSUE THREAD

**Issue by hcoussy** [pkp/pkp-lib#6322]
Hi,
From https://forum.pkp.sfu.ca/t/search-is-slow-and-not-always-working-after-upgrade-to-ojs-3-2-1-1/63524/10
It appears that search queries are imposing a heavy load.
The existing UNIQUE index from publication_settings table contains this 3 columns:
publication_id
locale
setting_name

This condition in this query:
JOIN publication_settings ps ON (ps.publication_id = p.publication_id AND ps.setting_name='issueId')
doesn't use the UNIQUE index because the column  ps.locale is missing

Adding a condition AND ps.locale IS NULL would cause the existing UNIQUE index to be used
In Mysql we have to write AND ps.locale=''

Best regards
Helene

**Comment by NateWr** [comment]
To be addressed in https://github.com/pkp/pkp-lib/issues/6321
