### ISSUE TITLE
Replace numeric to string cast for search performance

### ISSUE THREAD

**Issue by hcoussy** [pkp/pkp-lib#6323]
Hi,
From https://forum.pkp.sfu.ca/t/search-is-slow-and-not-always-working-after-upgrade-to-ojs-3-2-1-1/63524/10
It appears that search queries are imposing a heavy load.

In Mysql this condition:
JOIN issues i ON (CAST(i.issue_id AS CHAR) = ps.setting_value)
implies that a query with condition k0.keyword_text LIKE ‘%%%’
never ends

Replacing this condition by
JOIN issues i ON (i.issue_id = ps.setting_value)
OR
JOIN issues i ON (i.issue_id = CAST(ps.setting_value AS UNSIGNED))
permits the query to ends

As PostgreSQL doesn’t like to implicitly convert between strings and numbers, it could be a solution to use option 2 to make happy both Mysql and PostgreSQL

Best regards
Helene

**Comment by NateWr** [comment]
To be addressed in https://github.com/pkp/pkp-lib/issues/6321
