### ISSUE TITLE
Lens Galley XML views not tracked in usage statistics

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6330]
There's a small bug with respect to the lens galley plugin.  It registers a hook called LensGalleyPlugin::articleDownloadFinished that is not in the list of hooks checked by the Usage Stats and Usage Events plugin, so XML views are not registered. The fix is small, pull requests forthcoming.

Noticed in 3.2.1 but also in master.

**Comment by NateWr** [comment]
Looks ok to me. @asmecher?

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/2900
- https://github.com/pkp/usageStats/pull/36
(Don't forget to list these in a comment on the issue when you open them -- unless they're in the same repository, GitHub won't do this automatically!)

All merged and cherry-picked to `stable-3_2_1` -- thanks, @jnugent!
