### ISSUE TITLE
a lot of cookie-related errors appearing in javascript console

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#6336]
**Describe the bug**
I cannot see any consequences of this, but the Course Journals install at SFU is leaving behind a long set of javascript errors in the console: 

* ```Some cookies are misusing the recommended “SameSite“ attribute 45```
** ```Cookie “OJSSID” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 3```
* ```Cookie “OJSSID” has been rejected because it is already expired. fetchNotification``` (this one appears a lot of times)
* ```Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ jquery.min.js:2:79419```

**To Reproduce**
Log in to [this install](https://course-journals.lib.sfu.ca/index.php/pdc2018/issue/view/14) and go to any submission

**What application are you using?**
 OJS, 3.2.1.1

**Comment by NateWr** [comment]
Those are just warnings. I can't speak to the cookie ones, but the XMLHttpRequest warning is a deprecation notice that appears when we inject HTML into the site with a `<script>` tag. This is a central part of the old JS framework and will be with us until we have finished migrating away from it.

**Comment by jalperin** [comment]
Right. I should have written warnings, not errors. The cookie ones might be
worth addressing?

>

**Comment by asmecher** [comment]
Closing this one in favour of https://github.com/pkp/pkp-lib/issues/6340, which proposes some concrete changes.
