### ISSUE TITLE
[OJS] Update PubMED XML export to include affiliation info, keywords

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#634]
1) The PubMED XML export plugin only includes affiliation information for the first author. It should include affiliation information for all authors. 

2) The plugin should also include keyword information in an ObjectList element set after the abstract - see http://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.Can_I_submit_author_keywor.

**Comment by asmecher** [comment]
1) @jmacgreg -- the affiliation is only included for the first author by design -- see http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=7774

2) Implemented.

**Comment by ashourian** [comment]
Have you found any solution to the problem of exporting pubmed with including all the 
authors affiliations?

**Comment by asmecher** [comment]
@ashourian, see the above comment.
