### ISSUE TITLE
Session/cookie management improvements

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#6340]
**Describe the problem you would like to solve**
This is a meta-issue to help us track possible session/cookie management improvements that have been flagged in the past, including the following:

1) [x] Setting the [HTTP-only flag](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-httponly) since there's no requirement for cookie access via JS (done: https://github.com/pkp/pkp-lib/issues/7373)
2) [x] Setting the [secure flag](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-secure) if a site has force_ssl enabled
3) [x] Setting a strict [samesite option](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-samesite) to block cross-site cookie requests
4) [ ] Others requirements missing from the above list

**Describe the solution you'd like**
Review our current session management to add the above if feasible.

**Who is asking for this feature?**
- Journals that need to adhere to strict cookie policies, GDPR, etc.
- Universities that need to meet more secure session management requirements

**Comment by mfelczak** [comment]
@ajnyga, tagging you here in case you have any additional requirements to add.

**Comment by mfelczak** [comment]
@ctgraham, tagging you here as well in case you have any additional requirements to add.

**Comment by ajnyga** [comment]
Thanks! From a GDPR viewpoint I think the most important thing is to make the OJS session cookie optional.
However, we should find out whether it would be enough to hash the IP that is stored to the sessions table. If that is enough for GDPR purposes, then the OJS cookie does not need consent while no other personal data is stored to the cookie/session.

**Comment by asmecher** [comment]
@ajnyga, is the cookie consent thing already covered by https://github.com/pkp/pkp-lib/issues/3624?

**Comment by ajnyga** [comment]
Yes, I believe that is what @mfelczak means with the first point here?

**Comment by mfelczak** [comment]
Yes, that was the intention with 1) which I've updated with a few more details.

**Comment by asmecher** [comment]
Gotcha, thanks. I'd suggest removing it from this entry, then, and letting #3624 handle it (since there's already a lot of discussion over there).

**Comment by mfelczak** [comment]
Thanks @asmecher and @ajnyga, removed 1) here in favour of continuing discussion via #3624.

**Comment by fradeve** [comment]
@NateWr @asmecher issue # 2 (setting the "secure flag") has been raised by one of our customers.
Would it be ok if we submitted a PR to fix _just that_ in the next 3 weeks?

**Comment by jonasraoni** [comment]
I've updated some of these settings locally (the http only, same site and the secure flag) while I was testing some things, perhaps I can create a PR 🤔

**Comment by asmecher** [comment]
@fradeve, I'd be happy to review a PR on that specific piece of it!

**Comment by jonasraoni** [comment]
@asmecher Here are some PRs for `main`, once it's reviewed, I can port it to the other branches (this is supposed to also solve the https://github.com/pkp/pkp-lib/issues/8524):
https://github.com/pkp/ojs/pull/3696
https://github.com/pkp/pkp-lib/pull/8533

**Comment by asmecher** [comment]
@jonasraoni, I've merged in https://github.com/pkp/pkp-lib/pull/8487; please make sure not to accidentally revert it with your PRs.

**Comment by asmecher** [comment]
@salmanm2003, I've merged in your proposed change for the secure flag; thanks!

**Comment by salmanm2003** [comment]
@asmecher perfect -- thanks.

**Comment by jonasraoni** [comment]
@asmecher I've reverted the modifications related to the http://wayback.archive-it.org/7100/20180509190857/https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8921 at the `pkp-lib` (I'll create another issue to handle it) and created the remaining PRs, here's all of them:

- **`main`**
- https://github.com/pkp/pkp-lib/pull/8533
- https://github.com/pkp/ojs/pull/3696
- https://github.com/pkp/omp/pull/1303
- https://github.com/pkp/ops/pull/437
- **`stable-3_3_0`**
- https://github.com/pkp/pkp-lib/pull/8542
- https://github.com/pkp/ojs/pull/3700
- https://github.com/pkp/omp/pull/1304
- https://github.com/pkp/ops/pull/438

**Comment by jonasraoni** [comment]
Merged the PRs at https://github.com/pkp/pkp-lib/issues/6340#issuecomment-1382385231

Extra fixes have been moved to https://github.com/pkp/pkp-lib/issues/8544
