### ISSUE TITLE
PHP 7.4.12 is giving with call_user_func_array()

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#6341]
**Describe the bug**
After updating to the latest PHP I'm getting the following error constantly and the site became **very** slow when loading the first page of every journal.

```
[Mon Nov 16 17:04:14.372074 2020] [php7:warn] [pid 82273] [client 54.36.148.122:19044] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php on line 63
[Mon Nov 16 17:05:27.948460 2020] [php7:warn] [pid 82273] [client 185.191.171.39:2790] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php on line 63
[Mon Nov 16 17:05:28.618451 2020] [php7:warn] [pid 63671] [client 200.145.66.44:3227] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php on line 63
[Mon Nov 16 17:06:13.716837 2020] [php7:warn] [pid 18020] [client 179.108.23.78:31512] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php on line 63, referer: https://www.google.com.br/
[Mon Nov 16 17:06:18.716155 2020] [php7:warn] [pid 81497] [client 185.191.171.39:21514] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php on line 63
[Mon Nov 16 17:06:29.572400 2020] [php7:warn] [pid 92317] [client 66.249.64.18:58588] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php on line 63
[Mon Nov 16 17:06:30.585351 2020] [php7:warn] [pid 90662] [client 2804:431:d701:59d:55dd:7e32:c89c:3aba:51764] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php on line 63, referer: https://www.google.com/
[Mon Nov 16 17:06:38.132419 2020] [php7:warn] [pid 1355] [client 3.219.188.134:30306] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php on line 63

```

**To Reproduce**
You can check my installation on http://periodicos.fclar.unesp.br

**What application are you using?**
 OJS 3.2.1-1

**Comment by asmecher** [comment]
@luizbgomide, have you changed your caching configuration away from the default? Are your file permissions configured properly so that OJS can store files in `cache/`? It seems as though file-based caching is not working in your installation, which would explain the low performance.

**Comment by luizbgomide** [comment]
No change in OJS whatsoever. The only thing that I did today was run `portmaster -a` which updated a few PHP components.

Also it is only slow on the initial page of journals, everything else (main site page, issues, articles, administration, dashboard, etc) is as fast as ever. After those problems begin occuring I cleared all my cache, but no change.

**Comment by asmecher** [comment]
@luizbgomide, unfortunately the warning doesn't contain enough information to know what specific case is causing the warning. If you're handy with PHP, could you make a couple of changes?
- Turn on `show_stacktrace` in `config.inc.php`
- Edit `lib/pkp/classes/cache/GenericCache.inc.php` and change...
  ```
  function get($id) {
    $result = $this->getCache($id);
    if (is_object($result) && get_class($result) === 'generic_cache_miss') {
      $result = call_user_func_array($this->fallback, array($this, $id));
    }
    return $result;
  }
  ```
  ...to...
  ```
  function get($id) {
    $result = $this->getCache($id);
    if (is_object($result) && get_class($result) === 'generic_cache_miss') {
      if (!is_array($this->fallback) && !is_string($this->fallback)) {
        fatalError('Unknown fallback type: ' . print_r($this->fallback,true));
      }
      $result = call_user_func_array($this->fallback, array($this, $id));
    }
    return $result;
  }
  ```
Then trigger the error and see what the page output looks like (it should be a fatal error with stack trace). This will help identify the problem code.

Note that I *have not* tested the above changes for syntax errors etc.

**Comment by luizbgomide** [comment]
I did as you requested, but the page still loaded just fine and I got nothing different on the logs:
```
[Tue Nov 17 08:20:02.378050 2020] [php7:notice] [pid 78856] [client 200.145.66.44:4556] ojs2: Unknown fallback type: , referer: https://periodicos.fclar.unesp.br/
[Tue Nov 17 08:20:38.826169 2020] [php7:notice] [pid 92672] [client 200.145.66.44:4576] ojs2: Unknown fallback type: , referer: https://periodicos.fclar.unesp.br/
[Tue Nov 17 08:21:28.163491 2020] [php7:notice] [pid 8703] [client 200.145.66.44:4601] ojs2: Unknown fallback type: , referer: https://periodicos.fclar.unesp.br/
[Tue Nov 17 08:22:56.965896 2020] [php7:notice] [pid 78856] [client 200.145.66.44:4612] ojs2: Unknown fallback type: , referer: https://periodicos.fclar.unesp.br/
[Tue Nov 17 08:23:04.718432 2020] [php7:notice] [pid 3376] [client 200.145.66.44:4614] ojs2: Unknown fallback type: , referer: https://periodicos.fclar.unesp.br/
[Tue Nov 17 08:23:06.545058 2020] [php7:notice] [pid 99805] [client 200.145.66.44:4616] ojs2: Unknown fallback type: , referer: https://periodicos.fclar.unesp.br/

```

Where the stack trace was supposed to appear?

**Comment by asmecher** [comment]
Hmm, there should have been a failure and a stack trace there, not a notice. Maybe try converting the `fatalError(...)` to `throw new Exception(...)`?

**Comment by luizbgomide** [comment]
Got it, it is the exact same trace everytime it fails.

`Fatal error: Uncaught Exception: Unknown fallback type: in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php:64 Stack trace: #0 /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/FileCache.inc.php(115): GenericCache->get(NULL) #1 /usr/home/luizborges/www/public_html/plugins/blocks/keywordCloud/KeywordCloudBlockPlugin.inc.php(61): FileCache->getContents() #2 /usr/home/luizborges/www/public_html/lib/pkp/classes/template/PKPTemplateManager.inc.php(1033): KeywordCloudBlockPlugin->getContents(Object(Smarty_Internal_Template), Object(Request)) #3 /usr/home/luizborges/www/public_html/lib/pkp/classes/plugins/HookRegistry.inc.php(107): PKPTemplateManager->displaySidebar('Templates::Comm...', Array) #4 /usr/home/luizborges/www/public_html/lib/pkp/classes/template/PKPTemplateManager.inc.php(1254): HookRegistry::call('Templates::Comm...', Array) #5 /usr/home/luizborges/www/public_html/cache/t_compile/00a0a0910209607cb33eb0fe6474f30ed7399ed7^4dffb64063bb972c37e05619a2ccd9d0ea7473ac_0.app.frontend in /usr/home/luizborges/www/public_html/lib/pkp/classes/cache/GenericCache.inc.php on line 64`

**Comment by asmecher** [comment]
@luizbgomide, this appears to be a coding error in the keyword cloud block plugin, which PKP doesn't maintain; I'd suggest contacting the author of that plugin.
