### ISSUE TITLE
[OMP] Graph not showing views on book landing page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6343]
**Describe the bug**
When the usage stats plugin is configured to show a graph/chart on the book landing page, the stats are not appearing because the plugin tries to get stats for the `Publication` instead of the `Submission`. This can be seen [here](https://github.com/pkp/usageStats/blob/master/UsageStatsPlugin.inc.php#L585-L588). 

The OJS/OPS stats appear to correctly retrieve the submission instead of the publication.

**To Reproduce**

**What application are you using?**
3.3 (`master` pre-release)

**Additional information**
See [report](https://forum.pkp.sfu.ca/t/omp-3-2-1-1-problem-with-usagestats/63484/2) in the forum.

**Comment by NateWr** [comment]
Usage event logs do not appear to be getting written when viewing a publication format.

**Comment by bozana** [comment]
@NateWr, here is the change/fix taken from your other PR: https://github.com/pkp/usageStats/pull/39. OK so?

**Comment by NateWr** [comment]
Perfect, thanks!
