### ISSUE TITLE
Problems with enabling/disabling usage event and usage stats plugins from plugin grid

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6350]
**Describe the bug**
If you click the checkbox to disable the Usage Event plugin, it says that the plugin has been disabled but the status does not change in the plugin grid. In the database the `enabled` setting is set to `0`, but this is not taken into account in the plugin grid because the method `PKPUsageEventPlugin::isEnabled()` is set to always return `true`.

I think that the `getCanDisable()` and `getCanEnable()` need to return `false` for this plugin. @ctgraham can you think of any problem with this? 

**What application are you using?**
3.3 pre-release (`master`)

**Comment by ctgraham** [comment]
Sounds reasonable to me.

**Comment by NateWr** [comment]
Fixed in https://github.com/pkp/pkp-lib/commit/6a3e451e8b7c284180188a828ffb1ce7c5277388
