### ISSUE TITLE
Usage event not getting logged when viewing file

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6352]
**Describe the bug**
A usage event is not being logged when viewing/downloading a file. Reproduced this on OMP but I think it effects OJS as well.

**To Reproduce**
1. Make sure usage events are being logged when you visit a book landing page.
2. Go to a file for that book.
3. See that no event was logged for this.

**What application are you using?**
3.3 pre-release (`master`)

**Comment by NateWr** [comment]
The following PRs fix some issues where usage events were not getting recorded or processed correctly after the submission file refactor. I resolved this by simplifying how usage events are fired. We no longer try to track only when a file's download has finished. The usage event is recorded as soon as the download request is received.

On the plus side, we no longer need to add hooks to register usage events for PDF/HTML galleys. These events are automatically recorded successfully from a hook in the core app.

@bozana I think you have the most experience with this. Is it ok if we drop the `downloadFileFinished` hooks in favor of a simpler usage event registering?

PRs:
https://github.com/pkp/pkp-lib/pull/6364
https://github.com/pkp/ojs/pull/2913
https://github.com/pkp/omp/pull/879
https://github.com/pkp/usageStats/pull/37
(OPS coming)

**Comment by NateWr** [comment]
@ctgraham Bozana said that this may have some compliance issues with COUNTER rules:

> We no longer try to track only when a file's download has finished. The usage event is recorded as soon as the download request is received.

Do you have any thoughts on this?

**Comment by bozana** [comment]
PR: 
https://github.com/pkp/omp/pull/882

@NateWr, could you take a look?

**Comment by NateWr** [comment]
Thanks @bozana! All merged.
