### ISSUE TITLE
Submission files migration does not update item_views

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6359]
The submission files update in #6057 changes the way `submission_files` are referred to from other parts of the system. (No more compound ID!)

The `item_views` table (`ViewsDAO`) is used to track user views of submission files using `assoc_type = ASSOC_TYPE_SUBMISSION_FILE`. Previously `assoc_id` used to be a compound `fileId-fileRevision`. The upgrade process doesn't rewrite this to the new structure.

(Only very vaguely related: https://github.com/pkp/pkp-lib/issues/6320#issuecomment-730597845)

**Comment by NateWr** [comment]
@asmecher when looking into this, I could not find anywhere that the views were used outside of review responses. Views are recorded for submisssion files and notes, but these last viewed dates are never checked anywhere else in the code (with `ViewsDAO::getLastViewDate()`. 

Is it possible that this usage is deprecated and I could remove the recording of views for submission files and notes and clean up the table by removing those?

**Comment by asmecher** [comment]
Yes, I think it was used for files back in the early days of OMP, but I think that might've been replaced by the stats framework. Anyway, even grepping a reasonably old release of OMP it's not used, so I agree that removing that data should be fine.

**Comment by NateWr** [comment]
The following PR removes item views for all items except `ASSOC_TYPE_REVIEW_RESPONSE`, which appears to be the only place they are still used.

PR:
https://github.com/pkp/pkp-lib/pull/6373

Tests:
https://github.com/pkp/ojs/pull/2916

**Comment by NateWr** [comment]
@Vitaliy-1 heads-up here: I noticed that JatsParserPlugin uses the `recordView` method. This is no longer used and can be removed.

**Comment by NateWr** [comment]
Merged.
