### ISSUE TITLE
OMP OAI interface - relation support

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6361]
**Describe the problem you would like to solve**

In OJS, the galley file is linked in the OAI interface as `dc:relation`. It is not yet implemented in OMP.

**Describe the solution you'd like**

Public format has to be added to the  OMP OAI interface.

**Who is asking for this feature?**

Reported in forum https://forum.pkp.sfu.ca/t/no-relation-url-when-running-oai-in-omp/56886

**Additional information**
https://github.com/pkp/omp/blob/master/plugins/metadata/dc11/filter/Dc11SchemaPublicationFormatAdapter.inc.php#L182

**Comment by asmecher** [comment]
Merged for `stable-3_2_1`, but needs forward-porting to `master`.

**Comment by asmecher** [comment]
Merged forward-port to `master`: https://github.com/pkp/omp/pull/896
