### ISSUE TITLE
upgrade from OJS 3.1.2.4 to OJS 3.2.1.2 error Duplicate entry '0-1' for key 'citations_publication_seq'

### ISSUE THREAD

**Issue by sworld-guy** [pkp/pkp-lib#6365]
During upgrade from OJS 3.1.2.4 to OJS 3.2.1.2 I receive the following database error:
Upgrade error: Duplicate entry '0-1' for key 'citations_publication_seq'
Linux, 7.2.34 Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/5.4.16 mysqli 5.5.68-MariaDB

Explain step by step what I should do to update our scientific journal. Something I didn't succeed.
Help a newbie in this matter
![submissions](https://user-images.githubusercontent.com/47277235/100023451-ad203400-2ded-11eb-952c-ff6f1efbf289.jpg)
![citations](https://user-images.githubusercontent.com/47277235/100023455-ae516100-2ded-11eb-83ac-3f5784ee6881.jpg)
![file1](https://user-images.githubusercontent.com/47277235/100023456-ae516100-2ded-11eb-869e-4f6276a1d8f6.jpg)

As I understand it, the problem is in the relationships of these tables (attached)
There are citations entries and submissions indicate null
Maybe I’m wrong about something else. But it’s definitely wrong
I really hope for your qualified opinion, opinion and help.

also error for: php lib/pkp/tools/parseCitations.php all
with respect
Ph.D. Kuprienko Sergey

**Comment by NateWr** [comment]
Hi @sworld-guy! We welcome support requests on the [support category of our forum](https://forum.pkp.sfu.ca/c/questions/5). We try to keep the issues on this repository focused on bug reports and feature requests.
