### ISSUE TITLE
Interstitial issue download not working

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#637]
There's an authorization problem that I figured it out already, but on top of this there's a double execution of the viewDownloadInterstitial operation, and the second time the issue galley id parameter is passed as an array.

The download operation is also not being able to deliver the file:
Fatal error:  Call to undefined method IssueFile::getFileName() in /home/beghelli/dev/pkp-workspace/ojs/classes/file/IssueFileManager.inc.php on line 114

**Comment by asmecher** [comment]
@beghelli, FYI, @NateWr is tinkering around in the same area. Maybe the two of you should coordinate if you're interested in working on this.

**Comment by NateWr** [comment]
Hopefully the merge will come in today and then we'll all be looking at the same thing.

**Comment by beghelli** [comment]
This is duplicating the above issues. Closing and handling the bug there.
