### ISSUE TITLE
[OJS 3.2.1-2] Site administrator gets "does not have access to this operation" on Users tab

### ISSUE THREAD

**Issue by jmvezic** [pkp/pkp-lib#6375]
**Describe the bug**
When the site administrator has no role in a journal, the tab Users & Roles still appears but throws the error:

`"The current role does not have access to this operation."`

The issue's source is controllers/grid/settings/roles/UserGroupGridHandler.inc.php where it states on line 40:

`array(ROLE_ID_MANAGER),`

If the intention is not to offer the site administrator to handle users in a journal where he/she has no other role, the tab option "Users & Roles" should be removed.

If the intention is that the site administrator should still be able to access users and roles and change them, the line should be replaced with:

`array(ROLE_ID_MANAGER, ROLE_ID_SITE_ADMIN),`

**To Reproduce**
1. Remove the site administrator from a journal (remove all roles)
2. Go to "Users & Roles"
3. The warning will appear

**What application are you using?**
 OJS 3.2.1-2

**Comment by NateWr** [comment]
@asmecher I have a vague recollection of us having tackled the admin/manager permissions thing before. Did we resolve that by assigning the admin to a managerial role in every context or by granting them a dummy role as a manager in the authorization code?

**Comment by jmvezic** [comment]
@NateWr There seems to have been a fix for that: https://github.com/pkp/pkp-lib/commit/9e35b17fd7c7c721ef5de4cf3d57f52b4980288a but that file no longer exists in the new version.

**Comment by asmecher** [comment]
It's the perfect time to tag @bozana :) See related: https://github.com/pkp/pkp-lib/issues/440

**Comment by jmvezic** [comment]
@asmecher As far as I can tell, this logic is handled differently in 3.3 (from the administration - hosted journals) and it works fine there. If you want, I can make a PR for this for the 3.2 branch?

**Comment by asmecher** [comment]
@jmvezic, please feel free, thanks!

**Comment by asmecher** [comment]
Thanks, @jmvezic, I've merged that change for `stable-3_2_1`!
