### ISSUE TITLE
[OJS] - Orcid plugin error, OJS core out of date

### ISSUE THREAD

**Issue by arturbonnett** [pkp/pkp-lib#6377]
Hi guys!!!!

I believe it's necessary to release a new version with the core changes. In the current release (3.2.1-2) the "orcidProfile" plugin is already using "Guzzlehttp", but in the core of the release it's not deployed yet

**Describe the bug**
After a user tries to validate the ORCID the return page fails ( .../orcidapi/orcidVerify )

The plugin calls the "getHttpClient" function on 'plugins/generic/orcidProfile/pages/OrcidHandler.inc.php:59'
`$httpClient = Application::get()->getHttpClient();`

However, in 'lib/pkp/classes/core/PKPApplication.inc.php' the function 'getHttpClient()' doesn't exist yet

**To Reproduce**
Authenticate someone account with ORCID

**What application are you using?**
OJS 3.2.1-2

**Comment by withanage** [comment]
Hi @artorbonnett,
thanks for the report.
I will revert the 3.3 code. Meanwhile please use the  latest one from the plugin gallery. 1.1.25 for  OJS 3.2. There it is not included.

**Comment by asmecher** [comment]
@withanage, it looks like the tests in the `stable-3_2_1` branch are configured to run against OJS `master`, or the tests would've caught this. Could you fix that too? https://github.com/pkp/orcidProfile/blob/stable-3_2_1/.travis.yml#L12..L15

**Comment by withanage** [comment]
@asmecher  thanks for  pointing out.

I have fixed  the  tests and retagged the 3_2_1-2.

@arturbonnett   I have tested it with the sandbox API. It would be nice, if you could also test it.

**Comment by asmecher** [comment]
(Closing old/fixed entry)
