### ISSUE TITLE
Bump node dependencies

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6378]
The node dependencies should be updated for 3.3. This issue is just for tracking PRs/tests.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ui-library/pull/130
https://github.com/pkp/ojs/pull/2920

**Comment by NateWr** [comment]
Arg! Sorry @asmecher, the tests got me again. The tests are failing around the keywords input during the workflow (not submission) and I've been unable to sort it out. I've removed all references to the keywords metadata control from the tests, so the OJS test should pass. Can you merge this in once those have passed?

I've filed a separate issue for me to fix and restore the metadata tests at https://github.com/pkp/pkp-lib/issues/6387. But this can wait until after the RC.

**Comment by asmecher** [comment]
All merged -- will bump submodules in the repos, but the tests on your PRs worked. Thanks!
