### ISSUE TITLE
Convert plugin locale files to .po

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6385]
The following plugins still have locale files in XML format, which is not compatible with v3.3. See https://github.com/pkp/pkp-lib/issues/5090

Plugin | Done
--- | ---
CacheBusterPlugin | ✔
MailLoggerPlugin | ✔
AllowedUploadsPlugin | 
AuthorRequirementsPlugin | [PR](https://github.com/ewhanson/authorRequirements/pull/6)
InstitutionalHomePlugin | ✔
BrowseBySectionPlugin | ✔
MissingLocaleExceptionPlugin | ✔
SushiPlugin | ✔
DocxToJatsPlugin | 
JatsParserPlugin | 
FundingPlugin | 
PluginTemplatePlugin | ✔
ExampleImportExportPlugin | ✔
DefaultChildThemePlugin | ✔
CulanthThemePlugin | ✔

**Comment by NateWr** [comment]
Ok, I've updated the PKP ones and all of my little test plugins. @ajnyga and @Vitaliy-1 just a heads up here. There is no urgency to this, but you'll want to convert your plugins' locale files from XML to PO for a 3.3-compatible release. You can generate the PO file with:

```
php lib/pkp/tools/xmlToPo.php plugins/generic/yourPlugin
```

**Comment by ajnyga** [comment]
could assign me to this so that I won't forget
