### ISSUE TITLE
Unable to install due to plugin XML schemata

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6386]
**Describe the bug**
When I try to install the latest master branch I get an error:

```
[27-Nov-2020 15:09:37 Europe/London] PHP Fatal error:  Uncaught Exception: XML-based plugin schemata not supported. in /home/nate/Projects/pkp/ojs/lib/pkp/classes/plugins/Plugin.inc.php:713
Stack trace:
#0 /home/nate/Projects/pkp/ojs/lib/pkp/classes/plugins/HookRegistry.inc.php(107): Plugin->updateSchema('Installer::post...', Array)
#1 /home/nate/Projects/pkp/ojs/lib/pkp/classes/install/Installer.inc.php(192): HookRegistry::call('Installer::post...', Array)
#2 /home/nate/Projects/pkp/ojs/lib/pkp/classes/install/Installer.inc.php(178): Installer->postInstall()
#3 /home/nate/Projects/pkp/ojs/lib/pkp/classes/install/form/InstallForm.inc.php(194): Installer->execute()
#4 /home/nate/Projects/pkp/ojs/lib/pkp/pages/install/InstallHandler.inc.php(79): InstallForm->execute()
#5 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPRouter.inc.php(391): InstallHandler->install(Array, Object(Request))
#6 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#7 /home/nate/ in /home/nate/Projects/pkp/ojs/lib/pkp/classes/plugins/Plugin.inc.php on line 713
```

This seems to be pretty late in the install process.

**To Reproduce**
Try to install a new instance.

**What application are you using?**
`master`

**Comment by asmecher** [comment]
@NateWr, I think you have a plugin in your codebase that implements the removed `getInstallSchemaFile` function. It's not part of the OJS repo or submodule set, as those test fine with Travis. Can you check if it's a 3rd-party plugin or old code?

**Comment by NateWr** [comment]
Yep! It was an old copy of the SWORD plugin. I do see references to this still in `Plugin.inc.php` and `lib/pkp/tools/installPluginVersion.php`. Those ok?

**Comment by asmecher** [comment]
> Those ok?

I just made that function `final` in `Plugin.inc.php` rather than enforcing it in the surrounding code. That'll force plugin devs to fix up their code.
