### ISSUE TITLE
Restore keywords tests

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6387]
With https://github.com/pkp/pkp-lib/issues/6378 the tests for inputting keywords in the backend have been failing. The tests pass on my machine, so I think the UI control is still working. I removed the tests in https://github.com/pkp/ojs/pull/2920/commits/a1a0bfbb6679819bfa2943e766a5e1584b36e2a3 so that the changes could be merged for 3.3's RC. But they should be fixed and restored before 3.3 is released.

**Comment by asmecher** [comment]
@henriqueramos, this is currently assigned to OJS/OMP/OPS 3.3.0, which is due for release on Monday; it's not a show-stopper for that release, so I can defer it if you need more time, but please let me know either way, thanks!

**Comment by henriqueramos** [comment]
@NateWr The PR it's available here. Seems everything ran smoothly.

https://github.com/pkp/ojs/pull/3029

**Comment by henriqueramos** [comment]
> @henriqueramos, this is currently assigned to OJS/OMP/OPS 3.3.0, which is due for release on Monday; it's not a show-stopper for that release, so I can defer it if you need more time, but please let me know either way, thanks!

Won't be necessary @asmecher, the pull request it's on code review step.

**Comment by NateWr** [comment]
All merged, thanks @henriqueramos!
