### ISSUE TITLE
indicate equal author contribution and corresponding author

### ISSUE THREAD

**Issue by heike-r** [pkp/pkp-lib#6395]
The succession of names in the author list is very important in our field of research. Usually, the first author gets the most credit. Thus, it is very important that we can indicate if the first and the second author contributed equally to an article. We can do this in the pdf but to see this directly on the article's website in OJS would be also important.

_Suggestion for solution_
Maybe add a checkbox were author details are entered during submission that says "This author is the first author or contributed equally as the first author". I phrased it like this in case the authors get re-ordered after entering all of them into the system.
In case more than one author gets a checked box, the phrase "These authors contributed equally" appears at all those authors were their affiliations are listed. 

_Who is asking for this feature_
Journal Editors and Journal Managers and I am sure, authors would greatly appreciate the addition.

_Additional information_
This request might be related to issue #857 

In this same instance, it would also be nice if the corresponding author would be indicated on an article's website in the list of names.

**Comment by epistemehealth** [comment]
One issue that I wonder about with co-first authorship, is whether Crossref metadata can work with multiple "first" authors. I have tried testing this using the Crossref [Metadata Quality Check](https://www.crossref.org/02publishers/parser.html) with two authors with the attribute `sequence="first"`. It didn't throw any errors, but I don't know if anyone has ever registered co-first authors via Crossref. If it is OK, then I think that would be another argument in favour of implementing this feature in OJS and its metadata plugins.

**Comment by NateWr** [comment]
This is going to be a really difficult one for us to do adequately across so many different disciplinary norms. (For example, in some disciplines there are distinctions to be made from last author.) 

I think we are more likely to go in the direction of the CRediT standard, as you linked to #857, since we can implement a sensible UI for that and have it work across all disciplines.

Where first or last author designations are needed, it may be necessary to think about a plugin that could be developed to indicate this.

**Comment by asmecher** [comment]
This will be resolved with implementation of CRediT. There is an optional capability suggested there for degree of contribution:

> Degree of Contribution Optional – Where multiple individuals serve in the same role, the degree of contribution can optionally be specified as ‘lead’, ‘equal’, or ‘supporting’;

Therefore I'll note this feature on the issue for CRediT integration, and close this issue in favour of https://github.com/pkp/pkp-lib/issues/857.
