### ISSUE TITLE
Use display() instead of fetch() to pass front-end templates to Smarty

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6397]
OJS 3.2.1 and the master branch, other versions are also affected

**Describe the bug**
In `RegistrationHandler::register` several templates are passed to Smarty/TemplateManager depending on the condition, 2 templates, `frontend/pages/message.tpl` and `frontend/pages/error.tpl` are passed with the fetch method, which contracts with other front-end templates, which are assigned with the display method. 

This leads to problems with passing additional variables from plugins, e.g., themes or Custom Header Plugin, that are using the `TeamplateManager::display` hook. Described on the forum: https://forum.pkp.sfu.ca/t/display-variable-viatemplatemanager-display-doesnt-work-everywhere/64418/3 

**To Reproduce**
The easiest way would be:
1. Install the Custom Header Plugin: https://github.com/asmecher/customHeader
2. Add any content to the header
3. Turn on email validation in config
4. Go to the registration page, fill forms, and press the Register button
5. See that on the redirected page (with email verification message) the data from a Custom Header Plugin is absent

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib master: https://github.com/pkp/pkp-lib/pull/6398
Tests for OJS master: https://github.com/pkp/ojs/pull/2927

**Comment by asmecher** [comment]
This is some very old behaviour, and I wonder if changing it wouldn't lead to other code missing expectations in hard-to-debug ways. Are there cases where plugins aren't able to use both hooks to get the job done? Perhaps we could continue the current pattern, but as a deprecated behaviour, and propose something else for new code.

**Comment by NateWr** [comment]
@asmecher I thought that `fetch` was only meant to be used when the template needs to be returned in a JSON response. Is that not right?

**Comment by Vitaliy-1** [comment]
I considered that 1) there is already a similar fix to the registration complete template that was done some time ago: https://github.com/pkp/pkp-lib/pull/4977 and it didn't lead to any issue, 2) using `::fetch` hook will cause code duplication and, 3) not using `::fetch` hook may cause a fatal error that isn't quite apparent, e.g., when a variable or custom smarty plugin/function /block is assigned to the header or footer (or otherwise site-wide).  

On the other hand, I can't find much info on how those methods are different, besides a thread on the Smarty forum where only mentioned that fetch() caches results

**Comment by Vitaliy-1** [comment]
Aha, according to the code, `fetch()` also [returns a template](https://github.com/smarty-php/smarty/blob/c295786e43735802a1a22d22bc6d72153d19af46/libs/sysplugins/smarty_internal_templatebase.php#L117) (in contrast to `display()`) and differs by passing different last parameter that leads to different rendering somewhere deeper in the code.

**Comment by Vitaliy-1** [comment]
Yeah, looks like the aim of `fetch()` is to reuse the output in a variable later. Also, `display()` has [an additional check](https://github.com/smarty-php/smarty/blob/c295786e43735802a1a22d22bc6d72153d19af46/libs/sysplugins/smarty_internal_template.php#L220) if the cache is modified. In the if condition referenced above `display` variable is `0` in case if `fetch()` method is used and `1` if `display()`.

**Comment by NateWr** [comment]
@asmecher any objection here? If there's a concern about breaking things, I guess 3.3 is the right time to introduce this change.

**Comment by asmecher** [comment]
@NateWr, I think the two options we have are
1. Maintain the current behaviour until we introduce a 3rd-party toolset to replace hooks (or even replace the Smarty toolset)
2. Change the current behaviour and work on more modern solutions separately

Replacement of hooks or templating is a long time out, so if you think this will make things easier, then I'm OK to merge it for 3.3.

**Comment by NateWr** [comment]
Ok, I've merged this in for now, since it's a minimal change that I think just aligns the rendering of this template with the others in the same handler. It should suffice for now...
