### ISSUE TITLE
Update themes to be compatible with OJS 3.3.0

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6400]
Changes from OJS 3.2.1 that can affect themes (may be updated):

1. **Support for the ROR plugin**. The plugin adds `rorId` property to the author object as well as `$rorIdIcon`. Pages affected: article landing page. Related issue: https://github.com/pkp/pkp-lib/issues/5912
2. **Categories**. Not a new feature but check if this information is included in the article. Pages affected: article landing page
3. **ORCID icon**. Check if doesn't conflict with the same icon handled by themes. Pages affected: article landing page. Related issue: https://github.com/pkp/classic/issues/82
4. **About this publishing system**.  `$currentJournal` variable rename to `$currentContext` and `$pubProcessFile` is substituted to the `$contactUrl`. Pages affected: aboutThisPublishingSystem. Related issue: https://github.com/pkp/pkp-lib/issues/5984
5. **Remove dependency from counting iterators**. There are places where an array is assigned to the template instead of DAOResultFactory object, they should use simple foreach iterator and count() method, instead of `iterator` TemplateManager plugin and `wasEmpty()` method. Pages affected: indexSite (itaration through journals), subscriptions, category; Check how Immersion theme handles Publications. Related issue: https://github.com/pkp/pkp-lib/issues/6264
6. **Simplify logo display**. A simpler way to handle the header logo and title, journal and site-wide. Pages affected: header of all pages. Related issue: https://github.com/pkp/pkp-lib/issues/5917
7. **Registration form inputs - autocomplete** (Optional). Add autocomplete attributes to the registration form inputs. Pages affected: Site-wide and journal's registration page.
8.  **Set anchors for edit links**. Anchors are allowed for the dashboard's pages. Affected pages: announcements, information, submissions. Related issue: https://github.com/pkp/pkp-lib/issues/6203
9. **Drop tag-it support** (Optional). Tag-It support is dropped in the Default theme, simple text input is used instead, each word separated by a comma. Pages affected: journal and site-wide registration page.

**Comment by NateWr** [comment]
Is this issue still pending or have you completed the theme updates?

**Comment by Vitaliy-1** [comment]
Completed, Thanks for the reminder!
