### ISSUE TITLE
Unable to pick a year in the advanced filters of the search form

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6406]
**Describe the bug**
Search form: dateFromYear and dateToYear select input is empty and doesn't contain any options to choose from. 

**To Reproduce**
1. Go to the search page, advanced filters
2. Pick published after or published before year input
3. See that they don't contain any options

**What application are you using?**
 OJS 3.3

**Additional information**
See screenshot
![Untitled](https://user-images.githubusercontent.com/20665587/100881315-72d22900-34b6-11eb-8704-b623d2c6267d.png)

**Comment by asmecher** [comment]
@Vitaliy-1, does your installation have any published content? The `SearchHandler` calls on [`PublicationService::getDateBoundaries`](https://github.com/pkp/pkp-lib/blob/master/classes/services/PKPPublicationService.inc.php#L253) to determine the oldest and newest published content, and the date options in the drop-down are populated from there.

**Comment by Vitaliy-1** [comment]
Yes, it has. Moreover, this works properly with the other themes than the Default. I think it's related to the replacement of `html_select_date` with a new function `html_select_date_a11y`

**Comment by NateWr** [comment]
Yes, the new function is necessary to comply with accessibility requirements. It was working in the default theme when this change was made (recently, at https://github.com/pkp/pkp-lib/issues/5182).

@Vitaliy-1, since you've got a database where this isn't working, can I assign you to investigate? I suspect either the `getDateBoundaries` are not returning something valid, or the `html_select_date_a11y` is breaking on some particular date boundary.

**Comment by Vitaliy-1** [comment]
@NateWr, on my test instance `start_year` is a current year (2020) and `end_year` is a year of a first publication (2016). Changing [this](https://github.com/pkp/pkp-lib/blob/c7bf76903d29210e042f982391f6a4ec22031314/classes/template/PKPTemplateManager.inc.php#L2286-L2289) to:
```
while ($i >= $endYear) {
	$years[$i] = $i;
	$i--;
}
```
Solves the issue for me. Smarty documentation also suggests that `start_year` is a current one. But this looks like a different implementation, is here the same case?

**Comment by NateWr** [comment]
It looks like I reversed `$startYear` and `$endYear`! https://github.com/pkp/ojs/blob/master/pages/search/SearchHandler.inc.php#L94-L95

Do you mind fixing that? It should start with hthe earliest year and end with the latest year.

**Comment by Vitaliy-1** [comment]
OJS master: https://github.com/pkp/ojs/pull/2934

**Comment by asmecher** [comment]
@Vitaliy-1, I've merged https://github.com/pkp/ojs/pull/2934 and cherry-picked/ported to OJS `stable-3_2_1`, OMP `stable-3_2_1`, and OMP `master` (where the identical fix is needed) -- but should the same accessibility requirement not also apply to OMP? The `getDateBoundaries` function is not used in `SearchHandler.inc.php` in OMP.

**Comment by NateWr** [comment]
Thanks both! @asmecher OMP does not have a search option to limit by publication date (or any search options).
