### ISSUE TITLE
User-facing category page is inaccessible 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6408]
**Describe the bug**
A category page cannot be viewed. Receiving a fatal error while trying to access:
```
127.0.0.1:36424 [500]: GET /index.php/psp/catalog/category/first-category - Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'publication_tlpl.locale' in 'where clause' in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare()
#1 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(361): Doctrine\DBAL\Driver\PDOConnection->prepare()
#2 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback()
#4 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(373): Illuminate\Database\Connect in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
``` 

**To Reproduce**
1. Create a category page, e.g., accessible by URL `../first-category`
2. Check the page available at: `.../[journal_path]/catalog/category/first-category`

**What application are you using?**
 OJS 3.3

**Comment by asmecher** [comment]
Fixed! @Vitaliy-1, this affects theme plugins that override `templates/frontend/pages/catalogCategory.tpl` and use the `$subcategories` template variable (see the identical patches for [OJS](https://github.com/pkp/ojs/commit/02762bef7006cc5d39566105f7da5209c92e3ec3), [OMP](https://github.com/pkp/omp/commit/359e95b8963dac3e2d166e2cd71ed6e850503475), and [OPS](https://github.com/pkp/ops/commit/15e00c992497dc88f83682b183e26d8732c4af0f)).

@NateWr, are you documenting this level of detail in the Release Notebook? Note that the template self-documentation was incorrect, but with this change, is now correct.

**Comment by NateWr** [comment]
Thanks, I've noted it down as something to mention around the ADODB removal.
