### ISSUE TITLE
OMP Payments menu does not display when enabled

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6409]
**Describe the bug**
The Payments menu does not always appear when it should on the back-end menu.

**To Reproduce**
1. Go to Settings > Distribution
2. Enable Payments and configure e.g. the manual payment plugin
3. Save the form.

You will see the Payments link appear on the sidebar as expected :+1: 

Now reload the page, and it will disappear again when it should stay present.

**What application are you using?**
OMP 3.3.0rc1

**Comment by asmecher** [comment]
@NateWr, I think this is related to the change of the backend to a single Vue container.

**Comment by NateWr** [comment]
There's no Payments page in OMP or OPS, so this was code that should have only been in OJS. These PRs move the relevant code out of the shared lib.

PR:
https://github.com/pkp/ui-library/pull/132
https://github.com/pkp/pkp-lib/pull/6415
https://github.com/pkp/ojs/pull/2932

**Comment by asmecher** [comment]
> There's no Payments page in OMP

Ah! No wonder I was confused. Thanks, @NateWr!
