### ISSUE TITLE
[OJS] NativeImportExportPlugin errors on OJS 3.1.2

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6410]
**Describe the bug**
I've got some errors when trying to export an issue. I'm not sure they are connected with unexpected things in the installation 🤔
As it's an "old" OJS version and not important at all for me at this moment (I was just checking what it's outputted by the plugin), I'll skip debugging it further.

- Warning:
PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /lib/pkp/plugins/importexport/native/filter/NativeExportFilter.inc.php on line 89

- Fatal error:
PHP Fatal error:  Uncaught Error: Call to a member function getUsername() on null in /lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php:108
Stack trace:
#0 /lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php(54): SubmissionFileNativeXmlFilter->createSubmissionFileNode(Object(DOMDocument), Object(SubmissionFile))
#1 /lib/pkp/classes/filter/Filter.inc.php(449): SubmissionFileNativeXmlFilter->process(Object(SubmissionFile))
#2 /lib/pkp/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php(292): Filter->execute(Object(SubmissionFile))
#3 /lib/pkp/plugins/importexport/native/filter/SubmissionNativeXmlFilter.inc.php(107): SubmissionNativeXmlFilter->addFiles(Object(DOMDocument), Object(DOMElement), Object(PublishedArticle))
#4 /plugins/importexport/native/filter/ArticleNativeX in /lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php on line 108

- Memory exhausted (nothing special in the log, but I get a page only with the texts below)
Validation errors:
Memory allocation failed
Memory allocation failed
[...]

**What application are you using?**
OJS 3.1.2

**Additional information**
I have a plugin to import submissions/issues from other formats, and I think the best way to avoid (errr decrease) it breaking on each iteration over the API is to make it deeply connected with the native plugin by interacting with it or producing content in the expected format...

After taking a fast look at the code, I think it needs some refactoring. Follow some general ideas:
- Replace the DOM tree by a lightweight XML generator (e.g. [XMLWriter](https://www.php.net/manual/en/book.xmlwriter.php)).
- Break the XML into pieces, so maybe a XML for each issue/submission (I consider it's easier to deal with smaller files) and tar/ zip it.
- Following the idea above, we can also skip serializing the files into the XML as it will be faster to produce/consume (if useful, we could keep a hash of the file content to optionally validate its integrity).
- As it's a long running task, we've got to architect a general processing scheme.

**Comment by asmecher** [comment]
@jonasraoni, see https://github.com/pkp/pkp-lib/issues/5372 -- there are also patches e.g. for 3.1.2. This adds support for XML exports that do not contain base64-encoded binaries, but instead reference URLs or files externally. I think that'll be a sufficient solution, and the resulting XML is much more pleasant to work with.
