### ISSUE TITLE
Datacite plugin not up to date : different credentials for test site vs prod site

### ISSUE THREAD

**Issue by mhvezina** [pkp/pkp-lib#6411]
_Context OJS 3.1.2-4_

_Datacite plugin version 2.0_

Datacite has abandonned the test prefix (https://blog.datacite.org/test-prefix-10-5072-retiring-june-1/) and now has 2 different and separated environments : one for testing and one for production, hence different credentials.

If I am not wrong it seems that the DataCite Export/Registration Plugin hasn’t been updated to take this change into account (i.e. “Use the DataCite test prefix for DOI registration”)

Here is the workaround I did while waiting for the plugin to be updated : https://forum.pkp.sfu.ca/t/ojs-3-1-1-4-datacite/58783/2 

Regards,
Marie-Hélène

**Comment by asmecher** [comment]
Hi @bozana! Could you have a look at this one?

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/2958

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR?

**Comment by asmecher** [comment]
@bozana, sorry for the wait, but I merged the PR -- is this issue ready to be closed?

**Comment by bozana** [comment]
Yes, thanks!
