### ISSUE TITLE
[OJS] Fattal error! when install OJS-master from github

### ISSUE THREAD

**Issue by Ge2C** [pkp/pkp-lib#6413]
First I will explain that i new here, and i want to try to fix some problem in ojs template system and then i try download the source code. I already run all command in "Using Git development source" section and everything run well, but when i try to run ojs trough my local server, it show some fatal error. I try to look the problem it seem that vendor helper function crashing with PKP local function. I can try add `if (!function_exists('___')){ code... }` to PKP local function but then local translation will not be working so it will be not working, and when i remove vendor function in run but some template not process correctly, any suggestion?

**Comment by NateWr** [comment]
What version of composer are you using? We use composer to [apply a patch](https://github.com/pkp/pkp-lib/blob/master/composer.json#L44-L50) to one of the dependencies so if composer is not doing this you may run into an issue.

**Comment by Ge2C** [comment]
I use composer version 2.0.7, I try again and got a message patching error like this
`  ...
 - Installing laravel/framework (v7.29.3): Extracting archive
 - Applying patches for laravel/framework
    lib/laravel-helper-4017.diff (Inhibit __ Laravel helper)
   Could not apply patch! Skipping. The error was: Cannot apply patch lib/laravel-helper-4017.diff
`

**Comment by NateWr** [comment]
cc @asmecher

**Comment by asmecher** [comment]
@Ge2C, what operating system are you using? Does it have the GNU patch tool installed?

**Comment by Ge2C** [comment]
I use windows, with WSL with PHP 7.4 and unfortunately I don't install GNU patch tool, and never use it

**Comment by asmecher** [comment]
@Ge2C, you'll need to install GNU Patch and add it to your system's PATH environment variable.

**Comment by matheusotoni** [comment]
> I use composer version 2.0.7, I try again and got a message patching error like this
> ` ...
> 
> * Installing laravel/framework (v7.29.3): Extracting archive
> * Applying patches for laravel/framework
>   lib/laravel-helper-4017.diff (Inhibit __ Laravel helper)
>   Could not apply patch! Skipping. The error was: Cannot apply patch lib/laravel-helper-4017.diff
>   `

I had the same error and resolved by installing the patch package: **`yum install patch`**

**Comment by swabsape** [comment]
> @Ge2C, you'll need to install GNU Patch and add it to your system's PATH environment variable.

how to install the gnu patch to windows?

**Comment by Ge2C** [comment]
@swabsape you can use [chocolatey](https://chocolatey.org) to install GNU
