### ISSUE TITLE
error when creating a counter AR1 report

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6414]
**Describe the bug**
The COUNTER AR1 report cannot be created.
Will try to figure out why -- if it is only in my installation...

**To Reproduce**
1. Go to Reports > COUNTER Reports
2. Click on 'Article Report 1:   2020'
3. The report is not created, see error in the PHP error log

**What application are you using?**
 OJS version 3.3 master branch

**Additional information**
`PHP Fatal error:  Uncaught Exception: Invalid string: integer in /.../ojs-master/plugins/reports/counter/classes/COUNTER/COUNTER.php:186\nStack trace:\n#0 /.../ojs-master/plugins/reports/counter/classes/COUNTER/COUNTER.php(1383): COUNTER\\ReportBuilder->validateString()\n#1 /.../ojs-master/plugins/reports/counter/classes/reports/CounterReportAR1.inc.php(165): COUNTER\\Identifier->__construct()\n#2 /.../ojs-master/plugins/reports/counter/classes/reports/CounterReportAR1.inc.php(107): CounterReportAR1->_createReportItem()\n#3 /.../ojs-master/plugins/reports/counter/CounterReportPlugin.inc.php(169): CounterReportAR1->getReportItems()\n#4 /.../ojs-master/lib/pkp/pages/stats/PKPStatsHandler.inc.php(449): CounterReportPlugin->display()\n#5 /.../ojs-master/lib/pkp/pages/stats/PKPStatsHandler.inc.php(394): PKPStatsHandler->report()\n#6 /.../ojs-master/lib/pkp/classes/core/PKPRouter.inc.php(391): PKPStatsHandler->reports()\n#7 /.../ojs-mast in /.../ojs-master/plugins/reports/counter/classes/COUNTER/COUNTER.php on line 186`

**Comment by NateWr** [comment]
If it is expecting to get a string but gets an integer instead, it's possible this is the new submission file ids. They used to use a `fileId-revision` syntax (string) but now use a `submissionFileId` (int).

**Comment by bozana** [comment]
PR:
ojs: https://github.com/pkp/ojs/pull/2938

**Comment by bozana** [comment]
@NateWr, true. Would this be the correct fix?

**Comment by NateWr** [comment]
Looks right to me! I guess in the counter specification the ID might be a string, so yeah just casting our submission ids to string should do it.

Not sure what's going on with that OJS test. That subscription test has gotten unstable, but the failure looks like a race condition (element detached from dom). I restarted them just to see if they'll pass or if we need to sort this out.
