### ISSUE TITLE
Publication APC Fee indication not present

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6419]
**Describe the bug**
Publication APC Fee indication not present when "Schedule For Publication" action is selected

**To Reproduce**
1. If the journal is set to ask for APC Fee, try Schedule the submission for publication
2. At v3.1.2 the form had the following indication (and actions)
![image](https://user-images.githubusercontent.com/560456/101147446-0e81a780-3625-11eb-9edf-1180a7379b0c.png)
3. version >= 3.2 don't show the same form when "Schedule For Publication" Action is selected - The indication is not shown

**What application are you using?**
 OJS, OMP version 3.3

**Additional Info**
Could perhaps be added to the `PublishForm` form

**Comment by NateWr** [comment]
This should probably be implemented as a pre-publication check in 3.3. (See `Publication::validatePublish`.) And the UI for marking a payment received or waived could be a new form in a new tab in the publication forms area.

**Comment by NateWr** [comment]
I see now that `stable-3_2_1` does not have this feature either (I missed that part on first read of the issue). It looks like the Editor Decision form lets you request payment when the submission is accepted. But there is no warning that payment has not been received.

@asmecher can you confirm whether the feature as it is in 3.2.x is sufficient? We haven't yet had an issue filed from someone using this.

**Comment by asmecher** [comment]
I've implemented something like you described in your comment, @NateWr. It's a bigger feature than I'd like to be adding so close to 3.3.0 being released, but I think it's important and the changes are almost all additions without impact on existing features. Could you have a look?

PRs:
- https://github.com/pkp/ui-library/pull/141
- https://github.com/pkp/ojs/pull/3018

I'm not thrilled about adding the save code in the handler class, but it didn't seem like something that should be added to the API, at least this late in the 3.3.0 release cycle. But I'm open to ideas there.

This is the first time I've worked with some of these structures, so please let me know if I've gone astray from your plans!

UI:
- The "Payments" modal has been added to the top of the workflow, when processing fees are enabled and configured.
  ![image](https://user-images.githubusercontent.com/200411/105937898-501e4580-600b-11eb-8dab-38d3014f426b.png)
- It currently provides the status of the article processing fee:
  ![image](https://user-images.githubusercontent.com/200411/105937946-6b895080-600b-11eb-8908-d743c27d46a8.png)
- If it is unpaid, the submission cannot be published:
  ![image](https://user-images.githubusercontent.com/200411/105938011-8f4c9680-600b-11eb-874a-1e16a38c14fb.png)

I tried to avoid adding locale keys, but there are two new ones. (These will only appear if processing fees are enabled.)
