### ISSUE TITLE
Institutional Subscription: failure to add IP-range

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6420]
**Describe the bug**
When Subscriptions are enabled, the Journal manager can't add IP-range.

**To Reproduce**
1. Go to Payments > Institutional Subscriptions
2. Create New Subscription
4. Try add IP ranges
5. Save
6. No error is displayed - you get a notice in the PHP Logs
7. Edit the newly created Subscription
8. IP Range is missing

**What application are you using?**
 OJS version 3.3

**Comment by defstat** [comment]
@asmecher 

**PR**
OJS: pkp/ojs#2937

**Comment by asmecher** [comment]
Thanks, @defstat, good spotting!
