### ISSUE TITLE
ONIXCodelist retrieval fails when running under Windows server

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6422]
**Describe the bug**
Getting ONIXCodelist fails when running under Windows server

**To Reproduce**
1. Go to Submission > Publication > Publication Formats > Add publication format
2. The UI does not display an error but the for never get's loaded
3. A fatal error is added to the PHP logs: `PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\RequestException: cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in lib\\pkp\\lib\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php:201`

**What application are you using?**
OMP 3.3

**Additional information**
The issue seems to be related to the pattern that file's full path is represented when operating inside a Windows machine. The paths are like `C:\\full\\path\\name`. 
The `https://github.com/pkp/pkp-lib/blob/master/classes/xml/XMLParser.inc.php#L110` seems to parse the file's full path as it where a URL, thus causing the file path to go into `GuzzleHttp`

**Comment by defstat** [comment]
@asmecher 

**PR**
pkp-lib: #6423

**Comment by NateWr** [comment]
Nice catch. @asmecher do you mind reviewing this?

**Comment by asmecher** [comment]
Looks good to me -- merged, thanks, @defstat!
