### ISSUE TITLE
emptry review report

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6424]
**Describe the bug**
The review report is empty, although data exists.

**To Reproduce**
Having some reviews in your system
1. Go to Reports > Review Report
2. See empty (with no data) document

**What application are you using?**
 OJS version 3.3 master branch 

**Additional information**
'retrieve' calls in ReviewReportDAO do not return anything :-O

**Comment by asmecher** [comment]
@bozana, https://github.com/pkp/reviewReport/commit/123f4ad8c366248429e8494da1b9242e4d70ad02 should have fixed it -- can you run a quick test? (I've already tested and committed to `master` in the review report repo.)

**Comment by bozana** [comment]
All good, thanks! :+1:
