### ISSUE TITLE
PHP server freeze and constraint violation when creating/editing issues

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6426]
**Describe the bug**
Testing issue creation with PHP built-in server. After filling the data of a new issue form and pressing the save button leads to a substantial server freeze - 7 min in my case. PHP error log is empty, except a notice, which, I think, isn't related:
```
[Fri Dec  4 17:14:08 2020] PHP Notice:  Undefined property: Generator::$seq in /home/doc/OJS/development/ojs/classes/issue/IssueDAO.inc.php on line 727
```
Headers general data:
```
Request URL: http://localhost:8000/index.php/psp/$$$call$$$/grid/issues/future-issue-grid/update-issue?issueId=
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:8000
Referrer Policy: strict-origin-when-cross-origin
```
The waiting time for a response was 7.6 min. During this time server didn't respond on any request
Nevertheless, the issue itself is successfully created.

A similar problem appears when editing the issue, although here, there is an error message:
```
27.0.0.1:59924 [500]: POST /index.php/psp/$$$call$$$/grid/issues/future-issue-grid/update-issue?issueId=16 - Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '15' for key 'custom_issue_orders_pkey' in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(115): PDOStatement->execute()
#1 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(489): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback()
#4 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(496): Illumina in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
```
I'm testing on an instance with a history of upgrades from 3.0, thus may be a data problem.

**To Reproduce**
1. Go to 'issue'
2. Click on 'Create issue button'
3. See the freeze in PHP server response

**What application are you using?**
 OJS master branch

**Additional information**
![screencapture-localhost-8000-index-php-psp-manageIssues-2020-12-04-17_33_33](https://user-images.githubusercontent.com/20665587/101182550-e743ce00-3656-11eb-9a14-b44a4795cbdf.png)

**Comment by Vitaliy-1** [comment]
I don't see anything suspicious in the `custom_issue_orders` table except the new issues that I'm trying to create on the master branch have a suspiciously high `seq` value
```
issue_id	journal_id	seq	
1	1	15	
2	1	14	
3	1	13	
4	1	12	
5	1	11	
6	1	10	
7	1	9	
8	1	8	
9	1	7	
10	1	6	
11	1	5	
12	1	4	
13	1	2	
14	1	3	
15	1	1	
16	1	67976	
17	1	16694	
18	1	105844	
```

**Comment by Vitaliy-1** [comment]
Able to reproduce on a clean install:
1. Create 2 empty issues.
2. Publish them.
3. Apply a new issue ordering.
4. Create a new issue and try to edit it.

**Comment by asmecher** [comment]
@Vitaliy-1, the above fix (committed to OJS master) works for me, but can you please double-check that it resolves the hang on your system too?

**Comment by Vitaliy-1** [comment]
@asmecher, yes, it fixes the issue.

**Comment by asmecher** [comment]
Great, thanks, @Vitaliy-1!
