### ISSUE TITLE
[UI] Strings missing in backend navigation menu

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#643]
The manager context isn't loaded in, so Settings > Website/Workflow/Distribution strings aren't available.

I took a stab at this by adding a check for user roles in `PKPHandler::setupTemplate()`:

```
		$userRoles = $this->getAuthorizedContextObject(ASSOC_TYPE_USER_ROLES);
		if (array_intersect(array(ROLE_ID_MANAGER), $userRoles)) {
			AppLocale::requireComponents(LOCALE_COMPONENT_APP_MANAGER);
		}
```

But the `ROLE_ID_MANAGER` wasn't yet defined. Ideally this would only get loaded in on the backend, and only when a manager is viewing. But I didn't see an easy way to query user roles in `PKPTemplateManager`.

I figure someone else can fix this a lot quicker than me, so I'm moving on to more low-hanging fruit.

**Comment by asmecher** [comment]
I'll fix this.
