### ISSUE TITLE
OMP 3.3 General testing unloaded template variables

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6433]
**Describe the bug*

### Template variable form.dropzone.dictCancelUpload  was not loaded, although it was defined.

**To Reproduce**
upload a  file which exceeds maximum file upload limit.

**Additional information**
![Screenshot from 2020-12-05 12-03-02](https://user-images.githubusercontent.com/1921992/101240915-9c779400-36f2-11eb-9073-d88d8cb20a61.png)

###   Template variable grid.category.categories  was not loaded, although it was defined.

**To Reproduce**

management/settings/context#sections

**Additional information**

![Screenshot from 2020-12-06 16-10-42](https://user-images.githubusercontent.com/1921992/101283900-a7f3b980-37dd-11eb-847e-594d81e4415a.png)
###   Template variables in order of monographs 

**To Reproduce**

management/settings/website#appearance/setup

**Additional information**

![Screenshot from 2020-12-06 16-47-00](https://user-images.githubusercontent.com/1921992/101284999-3f0f4000-37e3-11eb-87d2-952a510f20c0.png)

**Comment by NateWr** [comment]
The missing file upload key was fixed in https://github.com/pkp/pkp-lib/commit/81237fc7530dc36146f43b87a5f262c005caa2fd. The following PR fixes the other two issues in OMP.

PR:
https://github.com/pkp/omp/pull/898
