### ISSUE TITLE
OMP External review discussion

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6434]
**Describe the bug**
Add external reviewer discussion to submission in OMP in the external review stage.

The error repeats also in Copyediting and production discussions.

**What application are you using?**
OMP 3.3 

**Additional information**

Error message:

`[Sat Dec 05 12:52:05.894221 2020] [php7:notice] [pid 6540] [client ::1:58988] PHP Fatal error:  Uncaught Error: Call to undefined method QueryDAO::getAffectedRows() in /var/www/html/omp-master/lib/pkp/classes/query/QueryDAO.inc.php:238\nStack trace:\n#0 /var/www/html/omp-master/lib/pkp/classes/query/QueryDAO.inc.php(218): QueryDAO->deleteById()\n#1 /var/www/html/omp-master/lib/pkp/controllers/grid/queries/QueriesGridHandler.inc.php(320): QueryDAO->deleteObject()\n#2 /var/www/html/omp-master/lib/pkp/classes/core/PKPRouter.inc.php(391): QueriesGridHandler->deleteQuery()\n#3 /var/www/html/omp-master/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()\n#4 /var/www/html/omp-master/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route()\n#5 /var/www/html/omp-master/lib/pkp/classes/core/PKPApplication.inc.php(303): Dispatcher->dispatch()\n#6 /var/www/html/omp-master/index.php(64): PKPApplication->execute()\n#7 {main}\n  thrown in /var/www/html/omp-master/lib/pkp/classes/query/QueryDAO.inc.php on line 238, referer: http://localhost/omp-master/index.php/publicknowledge/workflow/index/3/3
`

![omp](https://user-images.githubusercontent.com/1921992/101241708-dfd50100-36f8-11eb-987c-9ea2481035a8.gif)

**Comment by NateWr** [comment]
I think this was fixed in https://github.com/pkp/pkp-lib/issues/6392. Can you try updating with the latest changes and see if you can reproduce this?

**Comment by withanage** [comment]
@NateWr  

 I  have tested the scenarios again and it is  already fixed.
