### ISSUE TITLE
OMP Ordering Submission Preparation Checklist

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6437]
**Describe the bug**
Submission preparation checklist  ordering 
![omp](https://user-images.githubusercontent.com/1921992/101285499-c78ee000-37e5-11eb-8d21-003f09b083a5.gif)
triggers Error. 

**To Reproduce**
1. Go to _management/settings/workflow#_ then Checklist

**What application are you using?**
 OMP  3.3.

**Additional information**
`PHP Fatal error:  Uncaught Error: Call to undefined method Application::getContextSettingsDAO() in /var/www/html/omp-master/lib/pkp/classes/context/Context.inc.php:424\nStack trace:\n#0 /var/www/html/omp-master/lib/pkp/controllers/grid/settings/submissionChecklist/SubmissionChecklistGridHandler.inc.php(226): Context->updateSetting()\n#1 /var/www/html/omp-master/lib/pkp/classes/controllers/grid/feature/OrderGridItemsFeature.inc.php(62): SubmissionChecklistGridHandler->setDataElementSequence()\n#2 /var/www/html/omp-master/lib/pkp/classes/controllers/grid/GridHandler.inc.php(963): OrderGridItemsFeature->saveSequence()\n#3 /var/www/html/omp-master/lib/pkp/classes/controllers/grid/GridHandler.inc.php(752): GridHandler->callFeaturesHook()\n#4 /var/www/html/omp-master/lib/pkp/classes/core/PKPRouter.inc.php(391): GridHandler->saveSequence()\n#5 /var/www/html/omp-master/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()\n#6 /var/www/html/omp-master/lib/pkp/classes/core/Dispatcher.inc.php(143): in /var/www/html/omp-master/lib/pkp/classes/context/Context.inc.php on line 424, referer: http://localhost/omp-master/index.php/publicknowledge/management/settings/workflow
`

**Comment by NateWr** [comment]
This should be fixed by the PR here: https://github.com/pkp/pkp-lib/issues/6451#issuecomment-739945567

**Comment by NateWr** [comment]
Fixed in https://github.com/pkp/pkp-lib/commit/a3de66ff9f8718f5917b9d2bba228e3c987b534b
