### ISSUE TITLE
OMP Adding new roles

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6439]
**Describe the bug**
Adding a new role in OMP triggers an error.

**To Reproduce**

management/settings/access#roles

**What application are you using?**
OMP  3.3

**Additional information**
`[Sun Dec 06 17:24:37.828795 2020] [php7:notice] [pid 15641] [client ::1:36782] omp: Invalid user group id!, referer: http://localhost/omp-master/index.php/publicknowledge/management/settings/access
`
![omp](https://user-images.githubusercontent.com/1921992/101286027-9e238380-37e8-11eb-84a4-566f7acbbec2.gif)

**Comment by bozana** [comment]
PR:
pkp-lib: https://github.com/pkp/pkp-lib/pull/6450

**Comment by bozana** [comment]
@NateWr, would/could you take a look?

**Comment by bozana** [comment]
after the "fix php error, using stdClass as array", the new error appears when removing a group, but this is maybe a separate issue:
`PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /.../omp-master/lib/pkp/classes/security/UserGroupDAO.inc.php:417\nStack trace:\n#0 /.../omp-master/lib/pkp/controllers/grid/settings/roles/UserGroupGridHandler.inc.php(318): UserGroupDAO->getContextUsersCount()\n#1 /.../omp-master/lib/pkp/classes/core/PKPRouter.inc.php(391): UserGroupGridHandler->removeUserGroup()\n#2 /.../omp-master/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()\n#3 /.../omp-master/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route()\n#4 /.../omp-master/lib/pkp/classes/core/PKPApplication.inc.php(353): Dispatcher->dispatch()\n#5 /.../omp-master/index.php(64): PKPApplication->execute()\n#6 {main}\n  thrown in /.../omp-master/lib/pkp/classes/security/UserGroupDAO.inc.php on line 417, referer: http://omp-master.bb/index.php/press1/management/settings/access`

**Comment by NateWr** [comment]
Merged, thanks everyone!
