### ISSUE TITLE
DOI Plugin - Settings Form - Assign DOIs Action fails

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6441]
**Describe the bug**
DOI Plugin - Settings Form - Assign DOIs Action fails

**To Reproduce**
1. Go to Plugins > Public Identifier Plugins > DOI > Settings
2. Click on "Assign DOIs"
3. No UI Error - PHP Error: ` PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setting_type' in 'field list'`

**What application are you using?**
 OJS v3.3

**Comment by defstat** [comment]
@asmecher @NateWr 

**PR**
OJS: pkp/ojs#2942

**Comment by NateWr** [comment]
Thanks!
