### ISSUE TITLE
DOI Plugin - Settings Form - Reassign DOIs Action fails

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6442]
**Describe the bug**
DOI Plugin - Settings Form - Reassign DOIs Action fails

**To Reproduce**
1. Go to Plugins > Public Identifier Plugins > DOI > Settings
2. Click on "Reassign DOIs"
3. No UI Error - PHP Error: `PHP Fatal error:  Uncaught Error: Call to undefined method PublicationDAO::getDriver() in \\ojs-3-dev\\lib\\pkp\\classes\\publication\\PKPPublicationDAO.inc.php:283`

**What application are you using?**
 OJS, OMP v3.3

**Comment by defstat** [comment]
@asmecher 

**PR**
OJS: pkp/ojs#2943
OMP: pkp/omp#895

**Comment by NateWr** [comment]
Merged, thanks!
