### ISSUE TITLE
OMP 3.3. Published file download link triggers error.

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6445]
**Describe the bug**
Published Galleys link does not work e.g. 
http://localhost/omp-master/index.php/publicknowledge/catalog/view/4/3/25

**To Reproduce**

Create galley and publish a file  in Backend
Download galley file in backend

**What application are you using?**
OMP 3.3

**Additional information**
` PHP Fatal error:  Uncaught Error: Call to undefined method SubmissionFile::getAssocId() in /var/www/html/omp-master/plugins/generic/usageEvent/UsageEventPlugin.inc.php:114\nStack trace:\n#0 /var/www/html/omp-master/lib/pkp/plugins/generic/usageEvent/PKPUsageEventPlugin.inc.php(171): UsageEventPlugin->getUsageEventData()\n#1 /var/www/html/omp-master/lib/pkp/plugins/generic/usageEvent/PKPUsageEventPlugin.inc.php(110): PKPUsageEventPlugin->buildUsageEvent()\n#2 /var/www/html/omp-master/lib/pkp/classes/plugins/HookRegistry.inc.php(107): PKPUsageEventPlugin->getUsageEvent()\n#3 /var/www/html/omp-master/pages/catalog/CatalogBookHandler.inc.php(308): HookRegistry::call()\n#4 /var/www/html/omp-master/pages/catalog/CatalogBookHandler.inc.php(216): CatalogBookHandler->download()\n#5 /var/www/html/omp-master/lib/pkp/classes/core/PKPRouter.inc.php(391): CatalogBookHandler->view()\n#6 /var/www/html/omp-master/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()\n#7 /var/www/html/omp-master/lib/pkp/classes in /var/www/html/omp-master/plugins/generic/usageEvent/UsageEventPlugin.inc.php on line 114, referer: http://localhost/omp-master/index.php/publicknowledge/catalog/book/4`

**Comment by NateWr** [comment]
@withanage can you update your OMP copy and try again? I think that this was fixed recently and the line of code in the `master` branch looks ok: https://github.com/pkp/omp/blob/master/plugins/generic/usageEvent/UsageEventPlugin.inc.php#L114

**Comment by withanage** [comment]
@NateWr 
Sory, yes. It was already fixed. I have updated and tested it for the  publication formats and works well.
