### ISSUE TITLE
OMP 3.3 Create new version of a published monograph

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6446]
**Describe the bug**
Create a new version of a published monograph

**To Reproduce**
![omp](https://user-images.githubusercontent.com/1921992/101292460-dab6a580-380f-11eb-965d-5cf552721365.gif)

**What application are you using?**
OMP 3.3

**Additional information**
` Slim Application Error:\nType: TypeError\nMessage: Argument 2 passed to PKP\\Services\\QueryBuilders\\PKPSubmissionFileQueryBuilder::filterByAssoc() must be of the type array, int given, called in /var/www/html/omp-master/lib/pkp/classes/services/PKPSubmissionFileService.inc.php on line 107\nFile: /var/www/html/omp-master/lib/pkp/classes/services/queryBuilders/PKPSubmissionFileQueryBuilder.inc.php\nLine: 124\nTrace: #0 /var/www/html/omp-master/lib/pkp/classes/services/PKPSubmissionFileService.inc.php(107): PKP\\Services\\QueryBuilders\\PKPSubmissionFileQueryBuilder->filterByAssoc()\n#1 /var/www/html/omp-master/lib/pkp/classes/services/PKPSubmissionFileService.inc.php(56): PKP\\Services\\PKPSubmissionFileService->getQueryBuilder()\n#2 /var/www/html/omp-master/classes/services/PublicationService.inc.php(275): PKP\\Services\\PKPSubmissionFileService->getMany()\n#3 /var/www/html/omp-master/lib/pkp/classes/plugins/HookRegistry.inc.php(107): APP\\Services\\PublicationService->versionPublication()\n#4 /var/www/html/omp-master/lib/pkp/classes/services/PKPPublicationService.inc.php(485): HookRegistry::call()\n#5 /var/www/html/omp-master/lib/pkp/api/v1/submissions/PKPSubmissionHandler.inc.php(630): PKP\\Services\\PKPPublicationService->version()\n#6 [internal function]: PKPSubmissionHandler->versionPublication()\n#7 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()\n#8 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#9 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke()\n#10 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\\Route->callMiddlewareStack()\n#11 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\\Route->run()\n#12 /var/www/html/omp-master/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.inc.php(77): Slim\\App->__invoke()\n#13 [internal function]: ApiAuthorizationMiddleware->__invoke()\n#14 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#15 [internal function]: Slim\\DeferredCallable->__invoke()\n#16 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#17 /var/www/html/omp-master/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.inc.php(46): Slim\\App->Slim\\{closure}()\n#18 [internal function]: ApiCsrfMiddleware->__invoke()\n#19 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#20 [internal function]: Slim\\DeferredCallable->__invoke()\n#21 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#22 /var/www/html/omp-master/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.inc.php(82): Slim\\App->Slim\\{closure}()\n#23 [internal function]: ApiTokenDecodingMiddleware->__invoke()\n#24 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#25 [internal function]: Slim\\DeferredCallable->__invoke()\n#26 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#27 /var/www/html/omp-master/lib/pkp/classes/handler/APIHandler.inc.php(68): Slim\\App->Slim\\{closure}()\n#28 [internal function]: APIHandler->{closure}()\n#29 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#30 [internal function]: Slim\\DeferredCallable->__invoke()\n#31 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#32 /var/www/html/omp-master/lib/pkp/classes/handler/APIHandler.inc.php(127): Slim\\App->Slim\\{closure}()\n#33 [internal function]: APIHandler->{closure}()\n#34 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#35 [internal function]: Slim\\DeferredCallable->__invoke()\n#36 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#37 /var/www/html/omp-master/lib/pkp/classes/handler/APIHandler.inc.php(132): Slim\\App->Slim\\{closure}()\n#38 [internal function]: APIHandler->{closure}()\n#39 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#40 [internal function]: Slim\\DeferredCallable->__invoke()\n#41 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#42 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}()\n#43 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack()\n#44 /var/www/html/omp-master/lib/pkp/classes/handler/APIHandler.inc.php(124): Slim\\App->process()\n#45 [internal function]: APIHandler->{closure}()\n#46 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#47 [internal function]: Slim\\DeferredCallable->__invoke()\n#48 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#49 /var/www/html/omp-master/lib/pkp/classes/handler/APIHandler.inc.php(132): Slim\\App->Slim\\{closure}()\n#50 [internal function]: APIHandler->{closure}()\n#51 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()\n#52 [internal function]: Slim\\DeferredCallable->__invoke()\n#53 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()\n#54 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}()\n#55 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack()\n#56 /var/www/html/omp-master/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\\App->process()\n#57 /var/www/html/omp-master/lib/pkp/classes/core/APIRouter.inc.php(115): Slim\\App->run()\n#58 /var/www/html/omp-master/lib/pkp/classes/core/Dispatcher.inc.php(143): APIRouter->route()\n#59 /var/www/html/omp-master/lib/pkp/classes/core/PKPApplication.inc.php(303): Dispatcher->dispatch()\n#60 /var/www/html/omp-master/index.php(64): PKPApplication->execute()\n#61 {main}\nView in rendered output by enabling the "displayErrorDetails" setting.\n, referer: http://localhost/omp-master/index.php/publicknowledge/workflow/index/4/5
`

**Comment by NateWr** [comment]
I think this has been fixed. Can you update your copy and try to reproduce? The current code is at https://github.com/pkp/omp/blob/master/classes/services/PublicationService.inc.php#L274-L275.

**Comment by withanage** [comment]
@NateWr  I have tested the versioning feature again and  it works.
I have tested this  issue on the 

OMP https://github.com/pkp/omp/commit/dbe9cc2d899f59d2de86f8509f163844401db9b0
lib/pkp https://github.com/pkp/pkp-lib/commit/538dc7ad6856f47b860a79b870ddf7db852ecbca

and confirm it works.

Only small remark is that, it took a very long time (which can be any other cause) , but after a refresh of  the page, the new version version was correctly created.

**Comment by NateWr** [comment]
Hmm, if it requires a page refresh to see that the new version was created, that's a bug of some kind. Can you try checking your browser's console log? Maybe there was a JS error of some kind that prevented it from refreshing properly.

**Comment by asmecher** [comment]
(@withanage, assigning to you for feedback!)

**Comment by withanage** [comment]
@asmecher  @NateWr 

I have tested  on a fresh OMP installation

OMP https://github.com/pkp/omp/commit/c05c4e2819819ec777d4ba8bc17701a3c963c1af
pkp-lib https://github.com/pkp/pkp-lib/tree/3945761b44436b021189ee90c8d58749ab859c85

I can confirm this is fixed without errors in javascript and also in the PHP level.

My tests ran  on Google-chrome and  the redirect works  too! 

Longer taking of the redirection can still occur in  a developer environment due to the depreciation of the  Synchronous XMLHttpRequest  in Firefox  and it is not a  functional error.

We can close this issue.

**Comment by NateWr** [comment]
Thanks!
