### ISSUE TITLE
CrossRef Plugin: Settings page - Articles Tab - fails to load grid

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6447]
**Describe the bug**
CrossRef Plugin: Settings page - Articles Tab - fails to load grid

**To Reproduce**
1. Go to Plugins > Import/Export > Crossref Plugin > Settings > Articles tab
2. The Articles Grid has failed to load

**What application are you using?**
 OJS version 3.3

**Comment by defstat** [comment]
@asmecher 

**PR**
OJS: pkp/ojs#2944

**Comment by NateWr** [comment]
Thanks @defstat!
