### ISSUE TITLE
Crossref Plugin - Posting deposit metadata fails

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6448]
**Describe the bug**
Posting deposit metadata fails with 400 http bad request error. 

**To Reproduce**
1. Go to Plugins > Import/Export Plugins > Crossref plugin
2. Click on Articles tab
3. Select an Article to Deposit
4. Click Deposit
5. The UI displays a communication error with the server

**What application are you using?**
 OJS version 3.3

**Additional information**
https://www.crossref.org/education/member-setup/direct-deposit-xml/https-post/
https://docs.guzzlephp.org/en/stable/request-options.html#multipart

**Comment by defstat** [comment]
@asmecher 

**PR**
OJS: pkp/ojs#2945

**Comment by asmecher** [comment]
Thanks, @defstat -- looks good at a glance and we'll give it good test coverage during the RC stage.

This needs porting to OPS, so I've merged it for `master` but won't close the issue yet. Can you have a look at porting?

**Comment by asmecher** [comment]
(@defstat, don't forget to port this to OPS, please!)

**Comment by defstat** [comment]
@asmecher 

**PR**
OPS: pkp/ops#102

**Comment by asmecher** [comment]
Merged, thanks! Did you test it with OPS?

**Comment by defstat** [comment]
@asmecher yes I successfully deposited on a test account

**Comment by asmecher** [comment]
Perfect, thanks!
