### ISSUE TITLE
HTML Notification message is rendered  as HTML

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6449]
Split off from #6433:

> management/settings/access#users
> 
> **Additional information**
> ![omp](https://user-images.githubusercontent.com/1921992/101285844-bb0b8700-37e7-11eb-8d47-158559634db3.gif)

**Comment by asmecher** [comment]
@NateWr, I can get the notifications to display with the following change (I'm not even going to draft PR it):
```
diff --git a/templates/layouts/backend.tpl b/templates/layouts/backend.tpl
index d29113e4a..dde710e6d 100644
--- a/templates/layouts/backend.tpl
+++ b/templates/layouts/backend.tpl
@@ -206,7 +206,7 @@
                >
                        <transition-group name="app__notification">
                                <notification v-for="notification in notifications" :key="notification.key" :type="notification.type" :can-dismiss="true" @dismiss="dismissNotification(notification.key)">
-                                       {{ notification.message }}
+                                       <div v-html="notification.message"></div>
                                </notification>
                        </transition-group>
                </div>
```
...but I'm not at all sure whether opening this up so broadly will cause problems, or whether there are other places that `<notification>` is used that need similar consideration. What's your take?

**Comment by NateWr** [comment]
For accessibility reasons, the toast notifications can not contain links or buttons. That's because a link or button (or any interaction) which only appears for a set time is not accessible to those who might take longer to move their focus into the area. I'm having trouble locating the precise WCAG rule at the moment, but this is documented in the [notification section](https://docs.pkp.sfu.ca/dev/ui-library/dev/#/utilities/Notify) of the UI Library (under the Accessibility heading).

The toast notifications use [aria/role markup](https://github.com/pkp/pkp-lib/blob/master/templates/layouts/backend.tpl#L201-L205) that ensures the message will be read out with assistive technology. But I've deliberately not supported HTML code in the template to highlight these cases so we can refactor them.

The challenge in this case (and others like it) is that the linked notification is embedded deeply into the form system. I believe the links in the notifications may work for a regular form but not an ajax form. There's a lot to unpick here with a high potential of unintended side effects.

**Comment by asmecher** [comment]
Gotcha, I hadn't even thought of the accessibility implications here. So would you recommend looking for HTML-bearing notifications and adapting them for plain-text?

**Comment by NateWr** [comment]
Yeah, I think we'll need to do that for our accessibility reviews. In some cases, a link or other thing is a really useful thing, so we may need to come up with alternative approaches for the UI. For example, after a theme is changed, it'd be really nice to give a quick link to view it. But we'll need a permanent place to show that, not a toast notification.

**Comment by NateWr** [comment]
@asmecher I think I've found a safe way to address this for all form errors that result in a toast notification. From what I can see, this code only deals with toast notifications attached to a JSONMessage, so there shouldn't be a lot of room here for an unexpected side efffect. Does it look ok?

PR:
https://github.com/pkp/pkp-lib/pull/6662

Tests:
https://github.com/pkp/ojs/pull/3009
https://github.com/pkp/omp/pull/913

**Comment by asmecher** [comment]
I ... think that's it! I was expecting something much more complicated but I don't think there are other kinds of HTML-bearing notifications. Confirmed working for both toasty (edit user as manager) and non-toasty (user profile with high res screen) notifications. Please go ahead!
