### ISSUE TITLE
error when removing a user group

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6452]
**Describe the bug**
I created a new user group and then try to remove it.

**To Reproduce**
1. Go to User & Roles > Roles > a User Group
2. Click on "Remove" action
3. See error in the php error log file

**What application are you using?**
 OMP version 3.3

**Additional information**
`PHP Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /.../omp-master/lib/pkp/classes/security/UserGroupDAO.inc.php:408\nStack trace:\n#0 /.../omp-master/lib/pkp/controllers/grid/settings/roles/UserGroupGridHandler.inc.php(319): UserGroupDAO->getContextUsersCount()\n#1 /.../omp-master/lib/pkp/classes/core/PKPRouter.inc.php(391): UserGroupGridHandler->removeUserGroup()\n#2 /.../omp-master/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()\n#3 /.../omp-master/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route()\n#4 /.../omp-master/lib/pkp/classes/core/PKPApplication.inc.php(353): Dispatcher->dispatch()\n#5 /...omp-master/index.php(64): PKPApplication->execute()\n#6 {main}\n thrown in /.../omp-master/lib/pkp/classes/security/UserGroupDAO.inc.php on line 408, referer: http://omp-master.bb/index.php/press1/management/settings/access `

after the fix below the following error appears:
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\\Database\\Connection::prepareBindings() must be of the type array, int given, called in /.../omp-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 487 and defined in /.../omp-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:593\nStack trace:\n#0 /.../omp-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(487): Illuminate\\Database\\Connection->prepareBindings()\n#1 /.../omp-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()\n#2 /.../omp-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()\n#3 /.../omp-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(496): Illuminate\\Datab in /.../omp-master/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 593, referer: http://omp-master.bb/index.php/press1/management/settings/access
s`

**Comment by bozana** [comment]
PR:
pkp-lib: https://github.com/pkp/pkp-lib/pull/6453

**Comment by bozana** [comment]
@asmecher, would/could you take a look?

**Comment by asmecher** [comment]
Merged -- thanks, @bozana!

**Comment by bozana** [comment]
@asmecher, sorry, I wrote a wrong second error message above -- I've just edited it again. That is still not solved... Any idea?

**Comment by asmecher** [comment]
Fixed, thanks!
