### ISSUE TITLE
Discussions Grid produces a warning

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6458]
**Describe the bug**
Discussions Grid produces a warning `PHP Warning:  Declaration of QueryNoteFilesGridHandler::authorize($request, $args, $roleAssignments) should be compatible with SubmissionFilesGridHandler::authorize($request, &$args, $roleAssignments)`

**Comment by defstat** [comment]
@asmecher 

**PR**
pkp-lib: #6459

**Comment by asmecher** [comment]
Thanks, @defstat!
