### ISSUE TITLE
Inconsistency in JWT (API key) encoding/decoding

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6462]
https://github.com/NateWr/pkp-lib/commit/26da3ca2d588085ef80638eb292542c128a60991 changed the format of encoded user secrets that were stored in JWTs. [Previously they were created JSON-encoded](https://github.com/NateWr/pkp-lib/commit/26da3ca2d588085ef80638eb292542c128a60991#diff-ec34dc745a443ad1651bf482674cb6be78ffd4f7ec46ba5d22e778a2476a1e0aL60), and [passed through `json_decode`](https://github.com/NateWr/pkp-lib/commit/26da3ca2d588085ef80638eb292542c128a60991#diff-d524f6d316024b2a19c7abb550d3081256a0c6896a5e823caa6d9b5d084a7bceL41) where they were used; https://github.com/NateWr/pkp-lib/commit/26da3ca2d588085ef80638eb292542c128a60991 removes both the JSON encoding and decoding and presumes the result of `JWT::decode` is a string (the decoded user's secret).

However, there are a couple of problems...
- There are still some places where the result of `JWT::decode` is passed through `json_decode`:
  - https://github.com/pkp/swordServer/blob/master/SwordServerAccessPolicy.inc.php#L63
  - https://github.com/pkp/ojs/blob/stable-3_2_1/pages/article/ArticleHandler.inc.php#L49
  - https://github.com/pkp/ojs/blob/stable-3_2_1/pages/oai/OAIHandler.inc.php#L57
- API keys generated prior to https://github.com/NateWr/pkp-lib/commit/26da3ca2d588085ef80638eb292542c128a60991 will not work afterwards, and no conversion is performed on upgrade. (Fortunately it should be possible to resolve this upgradelessly with a slight performance hit -- it should be possible to check whether the returned item looks like it was JSON-encoded, and if so, decode it before use. Or similar.)

**Comment by NateWr** [comment]
>  it should be possible to check whether the returned item looks like it was JSON-encoded

Do you think use of API keys are widespread enough yet to warrant including this? Needing to regenerate an API key doesn't seem like a big task to undertake...

**Comment by asmecher** [comment]
API keys are used by some Coalition Publica journals, and we have a set of instructions to walk them through setting up the required plugins. Many of them will be non-technical so I'd rather not impose a requirement to regenerate tokens, if we can avoid it.

**Comment by NateWr** [comment]
Ahh, got it. Does this look like an adequate solution, @asmecher? I think that the API key will always be a string, which is encoded in json with double quotes. And I don't think double quotes can appear in the API key generated from JWT.

If this looks alright, I'll merge and cherry-pick to `stable-3_2_1`. I notice that the swordServer plugin does not have a stable branch. Should it get one (and a release) for this?

PRs:
https://github.com/pkp/pkp-lib/pull/6583
https://github.com/pkp/ojs/pull/2988
https://github.com/pkp/ops/pull/105
https://github.com/pkp/swordServer/pull/2
(OMP not needed)

**Comment by asmecher** [comment]
Thanks, @NateWr, that looks good! The sword server plugin needs work -- it's on my plate -- so don't worry about creating additional branches there, I'll do that once I've had a chance to clean it up a little.

**Comment by NateWr** [comment]
All merged and cherry-picked to `stable-3_2_1`.
