### ISSUE TITLE
3.3 - unable to close window with "x" in export users

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#6468]
Tested in the 3.3 demo instance being used by the DIG, using Firefox for MacOS. Did not test other browsers.

In the Users Export window for exporting users to CSV, clicking the "x" to close the window does not work. It also does not work when trying to close via keyboard. The window does close by clicking other inactive parts of the window.

**What application are you using?**
 OJS 3.3.0.1

**Additional information**

![Screen Shot 2020-12-11 at 2 11 44 PM](https://user-images.githubusercontent.com/6903515/101939080-79495a80-3bb2-11eb-9617-0a7cf663faba.png)

**Comment by NateWr** [comment]
Ugh, there's also an untranslated string in there: https://github.com/pkp/pkp-lib/blob/master/templates/stats/users.tpl#L48

My bad.

**Comment by NateWr** [comment]
Fixed in 140cecd.
