### ISSUE TITLE
3.3 - Exporting users "Slim application error"

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#6469]
Tested in the OJS 3.3.0.1 demo instance being used by the DIG, using Firefox for MacOS. Did not test other browsers.

**Describe the bug**
When trying to export users to CSV after selecting all user roles, an error message appears and the exported file does not download.

**To Reproduce**
1. Go to Statistics > Users
2. Click on Export
3. Click Export again in the new window
4. See error message: "Slim Application Error"

**What application are you using?**
OJS 3.3.0.1 

**Additional information**

![Screen Shot 2020-12-11 at 2 21 49 PM](https://user-images.githubusercontent.com/6903515/101940054-e3163400-3bb3-11eb-9278-bcdd7d644022.png)

**Comment by asmecher** [comment]
Here's the more detailed error report:
![image](https://user-images.githubusercontent.com/200411/102286462-3d353300-3eed-11eb-8791-a432c2012d9c.png)
This is happening because the server is running PHP7.2, but there is syntax in the report plugin that requires PHP7.3 or newer.

The 7.3 requirement is not reflected in the README etc -- I'll double-check and update those.

**Comment by asmecher** [comment]
(Pinged Michael and Israel to find a hosting solution for this.)

**Comment by odkr** [comment]
We have just hit the same bug on an OJS v3.3.0-6 instance running Debian v10.9 using Apache v2.4.38, MariaDB v10.3.27 und PHP v7.3.27-1.

**Comment by asmecher** [comment]
@odkr, this probably isn't the same issue, though it might look the same. Can you include the error message you received?

**Comment by kaitlinnewson** [comment]
We had this issue crop up again on an upgraded install, and found that user exports didn't work until we upgraded to PHP 7.4 (from 7.3), and [another forum user ran into this as well](https://forum.pkp.sfu.ca/t/slim-application-error-when-exporting-users-from-statistics-ojs-3-3-0-5/67674). This may need to be updated in the release docs.

**Comment by asmecher** [comment]
@kaitlinnewson, are you getting the exact error message in the image above? I suspect it's something similar but different. Can you include the full message you're getting?

**Comment by kaitlinnewson** [comment]
@asmecher I think it was the same, the beginning of the error in the logs is below. It's the same error the user in the forum post had as well, and [a reply there](https://forum.pkp.sfu.ca/t/slim-application-error-when-exporting-users-from-statistics-ojs-3-3-0-5/67674/5) indicated a PHP 7.4 requirement:

`[Wed May 26 10:39:29.217401 2021] [php7:notice] [pid 4794] [client ...] Slim Application Error:\nType: ParseError\nMessage: syntax error, unexpected '...' (T_ELLIPSIS), expecting ']'\nFile: /data/apache-html/1_stable-3_3_0-western/lib/pkp/classes/user/Report.inc.php\nLine: 67\nTrace: #0 /data/apache-html/1_stable-3_3_0-western/lib/pkp/classes/core/PKPApplication.inc.php(175): customAutoload('/data/apache-ht...', 'PKP\\\\', 'User\\\\Report')\n#1 [internal function]: PKPApplication->{closure}('PKP\\\\User\\\\Report')\n#2 /data/apache-html/1_stable-3_3_0-western/lib/pkp/classes/services/PKPUserService.inc.php(629): spl_autoload_call('PKP\\\\User\\\\Report')\n#3 /data/apache-html/1_stable-3_3_0-western/lib/pkp/api/v1/users/PKPUserHandler.inc.php(322):` ....

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson -- I misread the missing PHP feature as starting in PHP7.3 when actually it's PHP7.4. To resolve this, either upgrade to PHP7.4 or apply this change: https://github.com/pkp/pkp-lib/commit/bcf058116776569876bf6b5624f0b585ba79bbb6

The change will be released in OJS/OMP/OPS 3.3.0-7.

**Comment by odkr** [comment]
Sorry, for the late reply! I am not sure, whether our issue is the as @kaitlinnewson's:

> Wed Jun 02 12:20:37.477427 2021] [proxy_fcgi:error] [pid 26162:tid 140698391148288] [client 131.130.49.168:58731] AH01071: Got error 'PHP message: Slim Application Error:
Type: ParseError
Message: syntax error, unexpected '...' (T_ELLIPSIS), expecting ']'
File: /var/www/journals_phl_univie_ac_at/ojs-3.3.0-6/lib/pkp/classes/user/Report.inc.php
Line: 67
Trace: #0 /var/www/journals_phl_univie_ac_at/ojs-3.3.0-6/lib/pkp/classes/core/PKPApplication.inc.php(175): customAutoload('/var/www/journa...', 'PKP\\', 'User\\Report')
#1 [internal function]: PKPApplication->{closure}('PKP\\User\\Report')
#2 /var/www/journals_phl_univie_ac_at/ojs-3.3.0-6/lib/pkp/classes/services/PKPUserService.inc.php(629): spl_autoload_call('PKP\\User\\Report')
#3 /var/www/journals_phl_univie_ac_at/ojs-3.3.0-6/lib/pkp/api/v1/users/PKPUserHandler.inc.php(322): PKP\Services\PKPUserService->getReport(Array)
#4 [internal function]: PKPUserHandler->getReport(Object(Slim\Http\Request), Object(APIResponse), Array)
#5 /var/www/journals_phl_univie_ac_at/ojs-3.3.0-6/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(...', referer: https://journals.phl.univie.ac.at/meicogsci/stats/users/users

(It might be, of course.)

**Comment by asmecher** [comment]
@odkr, yes, I think it is the same. If you can try applying the patch [linked above](https://github.com/pkp/pkp-lib/issues/6469#issuecomment-852272720), it should resolve the issue!

**Comment by odkr** [comment]
Will do! Thanks!

**Comment by Rifaldi145** [comment]
@asmecher  hello, I have a problem like this, do you know bro?  Slim Application Error:\nType: Error\nMessage: Call to a member function getFullName() on null\nFile: /var/www/html/jurnal/lib/lib/pkp/classes/submission/reviewAssignment/ReviewAssignmentDAO.inc.php\nLine: 480\nTrace: #0 /var/www/html/jurnal/lib/lib/pkp/classes/submission/reviewAssignment/ReviewAssignmentDAO.inc.php(69): ReviewAssignmentDAO->_fromRow(Array)\n#1 /var/www/html/jurnal/lib/lib/pkp/classes/submission/reviewAssignment/ReviewAssignmentDAO.inc.php(217): ReviewAssignmentDAO->_getReviewAssignmentsArray('SELECT r.*, r2....', Array)\n#2 /var/www/html/jurnal/lib/lib/pkp/classes/services/PKPSubmissionService.inc.php(310): ReviewAssignmentDAO->getBySubmissionId('238')\n#3 /var/www/html/jurnal/lib/lib/pkp/classes/services/PKPSubmissionService.inc.php(343): PKP\\Services\\PKPSubmissionService->getReviewAssignments(Object(Article))\n#4 /var/www/html/jurnal/lib/lib/pkp/classes/services/PKPSubmissionService.inc.php(628): PKP\\Services\\PKPSubmissionService->canUserViewAuthor(Object(User), Object(Article))\n#5 /var/www/html/jurnal/lib/lib/pkp/api/v1/_submissions/PKPBackendSubmissionsHandler.inc.php(161): PKP\\Services\\PKPSubmissionService->getBackendListProperties(Object(Article), Array)\n#6 [internal function]: PKPBackendSubmissionsHandler->getSubmissions(Object(Slim\\Http\\Request), Object(APIResponse), Array)\n#7 /var/www/html/jurnal/lib/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\\Http\\Request), Object(APIResponse), Array)\n#8 /var/www/html/jurnal/lib/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(APIResponse), Array)\n#9 /var/www/html/jurnal/lib/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(APIResponse))\n#10 /var/www/html/jurnal/lib/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(APIResponse))\n#11 /var/www/html/jurnal/lib/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\\Route->run(Object(Slim\\Http\\Request),
