### ISSUE TITLE
Error when I try to add or edit a component

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#6470]
In the OJS 3.3 Release Candidate, when I go to Workflow Settings > Components and try to add or edit a component, I get an error "Failed Ajax request or invalid JSON returned."

Ordering components works.  Deleting a component seems to work.

**Comment by asmecher** [comment]
@amandastevens, could you try this again? The genre form currently causes a warning...
```
PHP Warning:  Declaration of GenreForm::initData($args) should be compatible with Form::initData() in /home/asmecher/git/ojs/lib/pkp/controllers/grid/settings/genre/form/GenreForm.inc.php on line 65
```
...but that's just a warning, not an error. However, the testing server was previously configured to display warnings to the browser (which is not recommended) where they'll cause trouble with AJAX requests. Israel fixed that and I suspect this has gone away as a result.

**Comment by asmecher** [comment]
(The warning itself is resolved in this commit: https://github.com/pkp/pkp-lib/commit/0c2be384eba0734db94a0a31262b4a27fda46404)

**Comment by asmecher** [comment]
Actually, I was able to confirm on the install myself -- it's resolved. Closing, thanks!
