### ISSUE TITLE
3.3 - UI/UX button Issue when logged in as other users

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6472]
The username variable appears when using the login as a feature as shown below. 

![image](https://user-images.githubusercontent.com/50342731/101955792-4fdcfe80-3bb3-11eb-947c-b1a27e9ee5ef.png)

Noted on rc2.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/6527

Tests:
https://github.com/pkp/ojs/pull/2972
