### ISSUE TITLE
Submission files upgrade step is slow

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6474]
During upgrade to 3.3, the following step appears to hang for a long time:
```
[migration: PKPv3_3_0UpgradeMigration]
```
Review it for opportunities to improve performance.

**Comment by asmecher** [comment]
I encountered a data problem in the dataset I was testing with:
```
ERROR: Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child
row: a foreign key constraint fails (`ejop`.`#sql-404_193d5`, CONSTRAINT
`review_files_submission_file_id_foreign` FOREIGN KEY (`submission_file_id`) REFERENCES
`submission_files` (`submission_file_id`)) (SQL: alter table `review_files` add constraint
`review_files_submission_file_id_foreign` foreign key (`submission_file_id`) references `submission_files`
(`submission_file_id`))
```
This was resolved by cleaning up the relationship between `review_files` and `submission_files` before upgrading:
```
SELECT DISTINCT rf.file_id FROM review_files rf LEFT JOIN submission_files sf ON (rf.file_id = sf.file_id) WHERE sf.file_id IS NULL;
+---------+
| file_id |
+---------+
|   16827 |
|   24889 |
|   28635 |
+---------+
3 rows in set (0.011 sec)

MariaDB [ejop]> DELETE FROM review_files WHERE file_id IN (16827, 24889, 28635);
Query OK, 40 rows affected (0.015 sec)
```

**Comment by NateWr** [comment]
Does that foreign key constraint look like a similar problem to https://github.com/pkp/pkp-lib/issues/6337? That was addressed in the migration by removing all `review_round_files` that pointed to a non-existent submission file: https://github.com/pkp/pkp-lib/pull/6372/files

Can we add something like that to the migration for `review_files`?

**Comment by asmecher** [comment]
A representative test with ~27k submission files gets through a complete upgrade in 24 minutes. That's good enough for the moment, I think.

**Comment by asmecher** [comment]
> Can we add something like that to the migration for `review_files`?

Done! https://github.com/pkp/pkp-lib/commit/dde63cd8c6d4aad84c6d37bce0826a41141486df
