### ISSUE TITLE
Remove use of Google Font CDN

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6478]
The default theme uses the Google Font CDN if the `enable_cdn` config option is set. The performance gains from that have diminished over the years and with [browser changes](https://wicki.io/posts/2020-11-goodbye-google-fonts/) coming soon or implemented already that will go away.

We should remove dependency on the Google Font CDN by downloading the files and self-hosting them. Care needs to be taken to ensure we offer all the different font formats that are necessary. By default, Google will only show you the font formats you need for your specific browser.

The [FontAwesome directory](https://github.com/pkp/pkp-lib/tree/master/styles/fontawesome) contains all of the formats that were necessary several years ago. But browser requirements may have changed.

**Comment by NateWr** [comment]
The following PRs remove all uses of `enable_cdn` for Google fonts as well as the jQuery assets. It removes all uses of `enable_cdn` completely. However, I've left the config option in place for custom themes that may still use it. @asmecher two questions:

1. Is this too much of a change this late in RC2? A major release feels like the right time to make the jump, but it's also a fair bit of code churn.
2. Should we remove `enable_cdn` and the `CDN_JQUERY_VERSION`/`CDN_JQUERY_UI_VERSION` constants? Or is it best to deprecate them as I have?

PRs:
https://github.com/pkp/pkp-lib/pull/6612
https://github.com/pkp/ui-library/pull/139
https://github.com/asmecher/lensGalley/pull/47
https://github.com/pkp/tinymce/pull/83
https://github.com/pkp/ojs/pull/2993

I'll work up PRs for OMP/OPS and PKP's other themes.

**Comment by asmecher** [comment]
@NateWr, I'd support merging this in time for 3.3 rather than waiting for another major release. I'd suggest removing the `config.TEMPLATE.inc.php` variable and documenting the removal in the release notes, rather than leaving it in and deprecated. Code that's not updated will still work if the setting is present, but the less old config/code we can have hanging around the better.

Is there a dependency of some kind that you can use in place of manually adding the binary fonts?
I presume the font license is compatible with ours -- is there a need to add licensing information about the fonts?

**Comment by NateWr** [comment]
> Is there a dependency of some kind that you can use in place of manually adding the binary fonts?

Good question. It looks like there is a [webpack plugin](https://www.npmjs.com/package/google-fonts-plugin) that might help with this. But that would only work with the default theme since other themes don't implement webpack, and in the default theme the font selection is customizable so we can't bake it into the CSS generation, which happens at run-time.

I think the way forward is maybe to build a CLI through webpack to update these files easily. But my take is that this is going to be a rare task so it's not really worth figuring this out right now. Happy to look into it further if you'd like.

> I presume the font license is compatible with ours -- is there a need to add licensing information about the fonts?

Oh yeah, I should have checked this. Here are the licenses for the used fonts:

Apache 2.0
- Noto sans
- Noto serif
- Open Sans
- Roboto (Immersion)

Open Font License
- Lato
- Lora
- Cardo (Classic)
- Montserrat (Classic/Manuscript)
- Spectral (Immersion)
- Alegreya (Pragma)
- Work Sans (Pragma)

Do you think we need to include a license statement and how should we do this?

**Comment by NateWr** [comment]
@asmecher I've removed the enable_cdn and `CDN_JQUERY_...` constants. I went ahead and merged these PRs, but let me know if there is anything additional I should do regarding the license info.

I'll leave this issue open because I still need to update the assets in:
- Bootstrap3
- HealthSciences (see [issue](https://github.com/pkp/healthSciences/issues))

**Comment by asmecher** [comment]
> Do you think we need to include a license statement and how should we do this?

Apache and GPLv3 are compatible, and Open Font License doesn't raise any red flags over at [gnu.org](https://www.gnu.org/licenses/license-list.en.html). I would recommend just noting in a README that font resources are taken from other sources, noting their licenses, and including a URL.

**Comment by NateWr** [comment]
Changes to Health Sciences and Bootstrap3 have been merged, and I added a readme with license information to the directories were our core fonts are stored. I think that's everything! :tada:
