### ISSUE TITLE
Posting as an author in OPS 3.3. does not refresh the authorDashboard view

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#6481]
**Describe the bug**
OPS 3.3. Trying to Post as an author will not close the publishing requirements window and does not refresh the authorDashboard.

**To Reproduce**
1. Allow authors to post using a screening plugin
2. Log in as an author and try to post your preprint
3. The form will show that the selection was saved, but the view is not refreshed. The window shown below stays open.
<img width="799" alt="Screenshot 2020-12-14 at 13 09 58" src="https://user-images.githubusercontent.com/16347527/102074826-063c2000-3e0e-11eb-902d-b613f9a7aac1.png">

**What application are you using?**
OPS 3.3.

**Comment by NateWr** [comment]
Can you check the console log for any errors that might be preventing this?

**Comment by ajnyga** [comment]
I am just looking into this

**Comment by ajnyga** [comment]
No errors present. None in javascript console or the error log

This is what is loaded when I click on Post

![Uploading Screenshot 2020-12-14 at 14.13.42.png…]()

**Comment by ajnyga** [comment]
Noticed that when I click Post as a moderator, I also get this call `http://localhost/ops-master/index.php/publicknowledge/api/v1/submissions/1` which is totally missing when I do the same thing as an author.

**Comment by ajnyga** [comment]
@NateWr 
OPS:  https://github.com/pkp/ops/pull/95
pkp-lib: https://github.com/pkp/pkp-lib/pull/6485

This is a fix for two issues:
1. allow authors to access production stage actions (like relate form and post, unpost).
2. Close the publish form and refresh the view when author does post

**Comment by NateWr** [comment]
Thanks, it looks good. Can you add a PR for OJS to run the tests there, just in case the `pkp-lib` change has any side effects?

**Comment by ajnyga** [comment]
OJS: https://github.com/pkp/ojs/pull/2952

Tests running

**Comment by NateWr** [comment]
Thanks, all merged!
