### ISSUE TITLE
Native Import/Export Plugin - Several Changes

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6490]
**Describe the problem you would like to solve**

Native Import/Export plugin
- [ ] Has duplicate code across applications
- [ ] When the import process fails, the process may leave the DB with garbage data
- [ ] The Export process does not display possible process errors in app 
- [ ] OPS Import/Export Implementation

### Has duplicate code across applications
The duplication is dealt in two ways:
1. Code was transferred in `pkp-lib` project
2. Repetitive code is processed through a toolkit of functions

### The Export process does not display possible process errors in app 
1. All the import/export process is contained inside a `Deployment` process. That allows all process to run inside the context of a try-catch block.
2. In the case of an in-process error or exception, a new tab is added with information about the process. (Like import process tab - export tabs are added also) 

### When the import process fails, the process may leave the DB with garbage data
All the import/export process is contained inside a `Deployment` process. That process runs within a DB transaction, which allows a `rollback` in case of an import `error` or `exception` (with the help of above feature)

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**
[PKP-LIB]: #6491
[OJS]: pkp/ojs#2955
[OMP]: pkp/omp#901
[OPS]: pkp/ops#98

**Comment by NateWr** [comment]
Thanks @defstat. The CLI stuff looks interesting. Can you share the commands to use to run imports/exports from the terminal?

**Comment by defstat** [comment]
### Test CLI commands
## OJS

- `php importexport.php NativeImportExportPlugin export --xmlFileName test_issues_export_1.xml --journal_path publicknowledge issue 1`
- `php importexport.php NativeImportExportPlugin export --xmlFileName test_articles_export_1.xml --journal_path publicknowledge article 3`
- `php importexport.php NativeImportExportPlugin export --xmlFileName test_articles_export_2.xml --journal_path publicknowledge articles 3 4`

- `php importexport.php NativeImportExportPlugin import --xmlFileName test_issues_export_1.xml --journal_path publicknowledge --user_name admin`
- `php importexport.php NativeImportExportPlugin import --xmlFileName test_articles_export_2.xml --journal_path publicknowledge --user_name admin`
- `php importexport.php NativeImportExportPlugin import --xmlFileName test_articles_export_1.xml --journal_path publicknowledge --user_name admin`


## OMP

- `php importexport.php NativeImportExportPlugin export --xmlFileName test_monographs_export_1.xml --journal_path publicknowledge monograph 3`
- `php importexport.php NativeImportExportPlugin export --xmlFileName test__monographs_export_2.xml --journal_path publicknowledge monographs 3 4`
- `php importexport.php NativeImportExportPlugin import --xmlFileName test__monographs_export_1.xml --journal_path publicknowledge --user_name admin`
- `php importexport.php NativeImportExportPlugin import --xmlFileName test__monographs_export_2.xml --journal_path publicknowledge --user_name admin`

**Comment by defstat** [comment]
@NateWr @asmecher 

We should probably consider submission-publication-issue states when adding submissions-publications-issues through the import/export.

Having in mind (https://github.com/pkp/pkp-lib/issues/5837), maybe an issue to discuss is whether the submissions-publications-issues should keep the "published" statuses. (This could be related to other indicators like submissions::progress)

**Comment by NateWr** [comment]
I think yes, the import should import it in precisely the same state it was in when it was exported.

**Comment by asmecher** [comment]
@defstat, I've added some comments -- some work needed on the OMP and particularly OPS ports; just a few things on OJS and pkp-lib.

**Comment by defstat** [comment]
Hi @asmecher.. I concluded the review changes, and added some more fixes.

**Comment by asmecher** [comment]
Looks good, @defstat! Just a few more comments -- also see the ONIX-related OMP issue I assigned you; I suspect the OMP changes proposed here break the ONIX export plugin. (Are there other import/export plugins that will be affected?)

**Comment by defstat** [comment]
@asmecher I tried to contain the changes within the Native Import/Export. 

I am proposing some changes in order to "extend" the UI error handling to ONIX plugin (and others if need be), which affects the issue https://github.com/pkp/pkp-lib/issues/6610.

**Comment by asmecher** [comment]
Thanks, @defstat; still some broad clean-up needed, and it's getting closer, but we're on the verge of needing to either merge this for 3.3.0 or defer it for 3.3.1. Please have another good run through it, clear out some of the comments, and give it another test (I'm worried that the OMP implementation [might be broken](https://github.com/pkp/omp/pull/901#discussion_r562180863)) and let's see what we can do for 3.3.0!

**Comment by defstat** [comment]
Hi @asmecher, @NateWr

Rebased the PRs for OJS, OMP and PKP-LIB and fixed some issues:

**PRs**
pkp-lib: #6960
ojs: #pkp/ojs#3109
omp: #pkp/omp#961

We could probably check them and merge them to main, and start working on main afterwards, for more features/fixes.

There is still [this issue](https://github.com/pkp/pkp-lib/issues/6925) that needs to be merged (and is related to this one)

**Comment by asmecher** [comment]
Thanks, @defstat -- I just made a couple very minor comments, but otherwise please rebase and merge ASAP and we'll get the code formatting in place!

**Comment by asmecher** [comment]
@defstat, is this issue ready to be closed?

**Comment by defstat** [comment]
Not yet. Waiting for some @ajnyga work for rebasing ops pr.

**Comment by ajnyga** [comment]
Go ahead @defstat I am happy to rebase mine after your changes!

**Comment by defstat** [comment]
@ajnyga @asmecher 

Added the 

**PR**
[ops]: pkp/ops#149

**Comment by asmecher** [comment]
I have merged https://github.com/pkp/ops/pull/149 -- thanks to you both! I see reference to changes made by both of you -- what's left to do on this issue?

**Comment by asmecher** [comment]
Whoops! @defstat, the PR broke OPS Travis tests:
```
PHP Fatal error:  Class CrossRefExportPlugin contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (PKP\plugins\ImportExportPlugin::getImportFilter, PKP\plugins\ImportExportPlugin::getExportFilter, PKP\plugins\ImportExportPlugin::getAppSpecificDeployment) in /home/travis/build/pkp/ops/plugins/importexport/crossref/CrossRefExportPlugin.inc.php on line 37
```
I had forgotten about the other PRs linked here:
https://github.com/pkp/pkp-lib/issues/6490#issuecomment-746749675

...of which at least one needs rebasing. I've reverted https://github.com/pkp/ops/pull/149 for the moment. Could you rebase these as needed?

**Comment by asmecher** [comment]
Resolved via #6976 and re-applied the commits in https://github.com/pkp/ops/pull/149. We'll see if that does it.

**Comment by defstat** [comment]
@asmecher After merging ops also I think we could close this issue for now.

**Comment by asmecher** [comment]
Thanks, closing!
