### ISSUE TITLE
OJS 3.2 Email Signature not populating in reviewer request

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6492]
**Describe the bug**
In OJS 3.1 the user-provided signature (**{$editorialContactSignature}**)would populate in the review request. However, in OJS 3.2 it only populates the user's name and email address.

Screencapture recording available here: https://share.getcloudapp.com/12uKPXBz

**To Reproduce**
Steps to reproduce the behaviour
1. Assign reviewer in manuscript
2. Generate request
3. User-provided signature no longer populates

**What application are you using?**
Observed in OJS 3.2.1-1 and OJS 3.2.1-2

**Additional information**
If a journal has custom email templates set up and switch to these other templates during the review invitation stage and switch back to the review request the user signature appears.

**Comment by asmecher** [comment]
This appears to be a long-standing behaviour -- there are both `$user->getSignature` / `$user->getLocalizedSignature` functions (for the user's signature from their profile), plus `$user->getContactSignature` (which constructs a fixed signature based on the user's name, affiliation, etc).

I would favour getting rid of `getContactSignature` and using the user's specified signature throughout, but as it appears in a few places more than just the reviewer assignment form, I'd favour deferring it until a later release.

**Comment by NateWr** [comment]
This has been fixed in the `main` branch and will be released with 3.4.
