### ISSUE TITLE
Google Scholar's indexing of OMP is still not working

### ISSUE THREAD

**Issue by gemusehandler** [pkp/pkp-lib#6493]
OMP = version 3.1.2.4

I think the issue is well described Monica Westin, Google Scholar partnerships lead/technical program manager
I picked the information up from this thread:
https://forum.pkp.sfu.ca/t/how-to-make-google-scholar-harvest-the-omp-metadata/3987/16

Simply put: OMP adds the Dublin Core metadata to the "head" of the abstract page of the book, elements like:
link rel="schema.DC" href="http://purl.org/dc/elements/1.1/"
meta name="DC.Creator.PersonalName" content="Santiago del Hierro"
meta name="DC.Date.created" scheme="ISO8601" content="2020-12-01"
meta name="DC.Date.dateSubmitted" scheme="ISO8601" content="2020-12-01"

but the citation_xx metatags are added to the <head> of the download page that has the PDF plugin.
Here you find elements like:
meta name="citation_isbn" content="9789463663427"
meta name="citation_author" content="Santiago del Hierro"
meta name="citation_author_institution" content="TU Delft, Architecture and the Built Environment"

Monica describes this as a bug.

I notice that OJS puts the Dublin Core and the citation_xx metatags BOTH in the "head" of the ABSTRACT page.
I understand the comment by Monica that OMP needs a similar solution.
The citation_xx metatags need to go to the <head> of the abstract page like the Dublin Core metadata.

**Comment by asmecher** [comment]
@withanage, could you take a look at this one?

**Comment by withanage** [comment]
@asmecher, sure, I will take a look into it.

**Comment by ajnyga** [comment]
Note: https://github.com/pkp/pkp-lib/issues/5686

**Comment by withanage** [comment]
Note : https://github.com/pkp/omp/pull/915/

**Comment by withanage** [comment]
Note : https://github.com/pkp/omp/pull/916/

**Comment by asmecher** [comment]
This should be resolved by the above PRs, which have been merged -- thanks, @withanage!
