### ISSUE TITLE
Future Issues - Reordering does not save

### ISSUE THREAD

**Issue by gustavotonini** [pkp/pkp-lib#6494]
We have the same problem as #6067 (grid reordering does not save) at Issues -> Future Issues. When editing the sections' order, it does not save the new configuration.

Path: /index.php/<journal>/manageIssues#futureIssues

**Comment by asmecher** [comment]
@gustavotonini, what version of OJS are you using? (Please include this with issue reports.)

**Comment by gustavotonini** [comment]
We are using 3.2.1.1

**Comment by asmecher** [comment]
https://github.com/pkp/pkp-lib/issues/6067 is fixed in OJS 3.2.1-2. Did you try applying the patch provided there?

**Comment by gustavotonini** [comment]
Yes, I applied but it didn't work. Do I have to expire the template's cache or something?

**Comment by asmecher** [comment]
Ah, I understand now -- this is a similar issue with re-ordering, but affecting the Future Issues list instead of the Submission Checklist. I'll see if I can reproduce the issue locally using OJS 3.2.1-2 (the latest stable release).

**Comment by asmecher** [comment]
I'm afraid I wasn't able to reproduce this behaviour with 3.2.1-2; I'd recommend upgrading to the latest stable release, and if the problem still appears, add a note here.

**Comment by NateWr** [comment]
Closing this for now, but we're happy to reopen this when there are reproduction steps to confirm the bug.
