### ISSUE TITLE
Galley url_path not imported in Native XML Import/Export

### ISSUE THREAD

**Issue by eocarragain** [pkp/pkp-lib#6501]
**Describe the bug**
When importing via Native XML, I have set a url_path attribute on the article_galley element. This is supported in the XSD: https://github.com/pkp/pkp-lib/blob/master/plugins/importexport/native/pkp-native.xsd#L224

However when importing the XML, the url_path attribute is ignored

**To Reproduce**
1. Go to Import/export 
2. Import an xml file containing galleys with "url_path" attribute set on the article_galley elements
3. Look at the imported articles
4. Note that galleys do not have the desired url_path

**What application are you using?**
 OJS 3.2.1-1

**Comment by NateWr** [comment]
Thanks @eocarragain! @defstat can you review the PR linked above?

**Comment by eocarragain** [comment]
Thanks @NateWr 
New pull request against pkp-lib incorporating @defstat's advice here: https://github.com/pkp/pkp-lib/pull/6521

Cheers, Eoghan

**Comment by NateWr** [comment]
Merged, thanks @eocarragain!
