### ISSUE TITLE
OAI _getRecordsRecordSet sql query becomes very slow in larger sites

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#6503]
**Describe the bug**
I a larger multijournal installation calls to OAI can get very slow. The reason is the `_getRecordsRecordSet` class which cases slow queries https://github.com/pkp/ojs/blob/master/classes/oai/ojs/OAIDAO.inc.php#L207-L265. 

Dividing the query to two parts will make `_getRecordsRecordSet` considerably faster.

**What application are you using?**
OJS 3.1.2, same should apply to newer versions and probably other applications, at least OPS.

**Comment by ajnyga** [comment]
OJS: https://github.com/pkp/ojs/pull/2964

Ping @asmecher, if you check this I can prepare it for OPS and OMP as well (although I do not think there are any large sites that are hit by this yet)

**Comment by asmecher** [comment]
Merged -- thanks, @ajnyga!

**Comment by marcbria** [comment]
Thanks a lot @ajnyga!

@asmecher any plan to include this in older 3.x stable branches?

**Comment by asmecher** [comment]
@marcbria, the changes at https://github.com/pkp/ojs/pull/2964 do apply cleanly to `stable-3_2_1`. If you can confirm that they work as expected, I can commit them there.
