### ISSUE TITLE
OMP download statistics chart uses wrong id

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6508]
The front end download statistics chart in OMP (version 3.2.1, but also master branch) is using a Publication object instead of a monograph object when fetching stats.  

https://github.com/pkp/usageStats/blob/master/UsageStatsPlugin.inc.php#L613

The visible symptom of this problem is that the chart displays sporadically, or perhaps not at all, depending on whether or not the publication id also corresponds to a valid monograph id.  For example, we had a bug report where stats were only displaying on the first book in the catalog (with catalog id #1).  It turns out that that catalog entry was the only one in the database with the same publication id.

**Comment by asmecher** [comment]
Good spotting, @jnugent! Are you working with a specific installation I can test with? If so, please send me the details privately.

**Comment by jnugent** [comment]
Master PR: #https://github.com/pkp/usageStats/pull/42

**Comment by NateWr** [comment]
I've merged that PR, cherry-picked to the `stable-3_2_1` branch of pkp/usageStats, and updated in the submodule in OMP's `stable-3_2_1` branch. Thanks @jnugent!
