### ISSUE TITLE
Non-expiring institutional subscription can't be added

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6510]
**Describe the bug**
The form requires the start and end date to be included, after inclusion and trying to save the form - message appears that states that those fields shouldn't be specified.
Also `required` label is missing for the input field `Institution name`.

**To Reproduce**
1. Enable payments: Distribution -> Payments -> Enable
2. Go to Payments -> Subscription Types -> Create New Subscription Type
3. In the `Create New Subscription Type` form check `Institutional` subscription, fill other required fields, leave field `Duration` empty and save the form
4. Go to Payments -> Institutional Subscriptions -> Create New Subsciptions
5. In the `Create New Subscription` form pick a newly created non-expiring subscription. Trying to save the form with dates filled out triggers a pop-up date picker and `this field is required` message.

**What application are you using?**
 OJS, current master branch (3.3)

**Additional information**
![screencapture-localhost-8000-index-php-publicknowledge-payments-2020-12-24-19_16_53](https://user-images.githubusercontent.com/20665587/103100719-9ce1bb80-461c-11eb-976a-22e1e3a196bb.png)

**Comment by asmecher** [comment]
Fixed -- thanks, @Vitaliy-1!
