### ISSUE TITLE
web_cache = on does not work in OJS 3.2

### ISSUE THREAD

**Issue by diegoabadan** [pkp/pkp-lib#6512]
When activating the `web_cache = on` option in OJS 3.2 the error occurs:

```
2020/12/28 18:04:45 [error] 13299 # 13299: * 5640637 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to a member function getUserVar () on null in pathToOJS / classes / i18n / AppLocale.inc.php: 75
Stack trace:
# 0 pathToOJS / lib / pkp / classes / core / PKPPageRouter.inc.php (127): AppLocale :: getLocale ()
# 1 pathToOJS / lib / pkp / classes / core / Dispatcher.inc.php (207): PKPPageRouter-> getCacheFilename (Object (Request))
# 2 pathToOJS / lib / pkp / classes / core / Dispatcher.inc.php (120): Dispatcher -> _ displayCached (Object (PageRouter), Object (Request))
# 3 pathToOJS / lib / pkp / classes / core / PKPApplication.inc.php (281): Dispatcher-> dispatch (Object (Request))
# 4 pathToOJS / index.php (68): PKPApplication-> execute ()
# 5 {main}
```

Reference: https://github.com/pkp/ojs/blob/stable-3_2_1/config.TEMPLATE.inc.php#L180

In the PKP forum more people had the same problem:

https://forum.pkp.sfu.ca/t/ojs-3-0-2-fatal-error-getuservar-on-null/29923

https://forum.pkp.sfu.ca/t/upgrade-ojs-2-4-6-to-ojs-3-x-error/40193/11

**Comment by Vitaliy-1** [comment]
Hi @diegoabadan,

Can you describe the steps needed to reproduce the error, like in the template? I'm unable to reproduce it on my test 3.2.0 instance, so I'm assuming you have additional plugins or settings enabled or something else.

**Comment by diegoabadan** [comment]
I tested it on an OJS instance that was upgraded from 2.4.8-5 to 3.2.x. Next I will confirm in an installation made from the current OJS.

I noticed now that not all pages and in not all situations the error 500 occurs.

How to reproduce the problem:
1) Open a private window in your browser, without logging in to OJS
2) Try with any of these resources:
/issue/current
/issue/archive
/about/editorialTeam

Thanks for the return @Vitaliy-1 !

**Comment by diegoabadan** [comment]
I confirmed the same problem in an instance with OJS 3.1.2.4 and without having undergone upgrades.

**Comment by Vitaliy-1** [comment]
Thanks! Now I'm able to reproduce it also. Master branch is also affected

**Comment by Vitaliy-1** [comment]
PR to pkp-lib master: https://github.com/pkp/pkp-lib/pull/6519
Tests OJS master: https://github.com/pkp/ojs/pull/2968

**Comment by NateWr** [comment]
Thanks for the report and the fix!

**Comment by diegoabadan** [comment]
I confirm the correction.

thanks!
