### ISSUE TITLE
[OJS] Removing a nav menu item causes an error

### ISSUE THREAD

**Issue by salmanm2003** [pkp/pkp-lib#6516]
Hi,
I have an issue with removing a nav menu item from OJS settings > website > setup > navigation , as the system throwing an error:
```PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\Database\Connection::prepareBindings() must be of the type array, int given, called in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 487 and defined in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:593```

OJS version: 3.3.0.1

Thanks
Salman

**Comment by amandastevens** [comment]
I also can't remove a navigation menu item. I can't check the error log so I'm not sure if I received the same error. But when I tried to remove the item a box appeared that said "Are you sure you wish to delete this item? This action cannot be undone," I clicked "OK," and nothing happened.  The box did not disappear.  I refreshed the page and the menu item was still there.

**Comment by salmanm2003** [comment]
I think I know what it is causing the issue.
You just need to add the id to an array inside the query here:
[https://github.com/pkp/pkp-lib/blob/master/classes/navigationMenu/NavigationMenuItemDAO.inc.php#L240-L241](url)

**Comment by NateWr** [comment]
All merged, thanks @salmanm2003!
