### ISSUE TITLE
OPS 3.3 - Author can't edit metadata / submission locale error

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#6517]
On the site there are 4 languages installed: English, Espanol, Portuguese, and Francais. English is the primary locale and the other languages are enabled for the UI and forms. English is the only language for submissions.

I was testing whether an author can edit the metadata for their own submission. I granted metadata editing permission to the author as an administrator. 

I logged in as the author and opened my submission, which was in the Production stage. The submission was made in English.

I edited the abstract field.

When I clicked Save, I got an error message that said "Please correct 4 errors. Jump to next error."

I clicked "Jump to next error" and the Espanol metadata fields appeared. I entered metadata in Espanol and clicked Save again. I got new errors below each Espanol field that said "This language is not accepted." I could not save the form.

**Comment by NateWr** [comment]
Thanks for the report! Confirmed and fixed in the following PRs.

PR:
https://github.com/pkp/pkp-lib/pull/6547

Tests:
https://github.com/pkp/ojs/pull/2982

**Comment by NateWr** [comment]
Merged.
