### ISSUE TITLE
OPS 3.3 - Assign DOI button is blank

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#6518]
I'm testing assigning DOIs in OPS 3.3. I have enabled and configured the DOI plugin. When I go to the Identifiers tab, the DOI preview appears and there appears to be a button next to the preview field to assign the DOI, but the button is blank.  

![Assign DOI](https://user-images.githubusercontent.com/35044512/103321877-64b5f080-4a01-11eb-9b36-ede2c4f2eed4.png)

When I click the button, the DOI preview disappears and there is nothing there. 

![Assign DOI 2](https://user-images.githubusercontent.com/35044512/103321929-99c24300-4a01-11eb-8cde-b6c55a4bc07a.png)

If I click Save it says "Saved" but I still don't see the DOI.

When I post the preprint, I get a message that says "A DOI has not been assigned to this publication." There is no DOI on the published article.

When I later posted a new version of the preprint, a DOI was automatically assigned to the article. Maybe the missing button text isn't supposed to be "Assign DOI."  I can't find the Identifiers tab anywhere else to compare.

**Comment by asmecher** [comment]
This should be resolved -- though an update to the OPS repository on your testing installation will be required to confirm. (It worked for me locally.)
