### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by rajeevrnt** [pkp/pkp-lib#6523]
Why don't you sent reset password link on registered email id? This practice is commonly used by banks or other institutions.

**Comment by asmecher** [comment]
@rajeevrnt, please include all the information we might need to understand your bug report or feature request; see the templates here: https://github.com/pkp/pkp-lib/issues/new/choose

**Comment by NateWr** [comment]
Duplicate of https://github.com/pkp/pkp-lib/issues/6524.
