### ISSUE TITLE
Forget Admin Password

### ISSUE THREAD

**Issue by rajeevrnt** [pkp/pkp-lib#6524]
Why don't you sent reset password link on registered email id or registered mobile? This practice is commonly used by banks or other institutions.
I was trying to reset the password for (ADMIN ), but I am not receiving password on my registered email id.

**Comment by NateWr** [comment]
Hi @rajeevrnt! We prefer to handle support queries on our [community forum](https://forum.pkp.sfu.ca/c/questions/5). Can you post your question there? We reserve the GitHub issues for confirmed bugs or more technical queries.

**Comment by rajeevrnt** [comment]
Why don't you sent reset password link on registered email id or registered mobile? This practice is commonly used by banks or other institutions.
I was trying to reset the password for (ADMIN ), but I am not receiving password on my registered email id.

**Comment by asmecher** [comment]
@rajeevrnt, see Nate's [comment above](https://github.com/pkp/pkp-lib/issues/6524#issuecomment-753955480). Please don't re-post the same content.

**Comment by rajeevrnt** [comment]
Dear Asmecher 
But my problem is not resolved. What to do?

**Comment by rajeevrnt** [comment]
> Dear Asmecher
> But my problem is not resolved. What to do?
I have already posted on the name of **IJELLH**. please find the below link

https://forum.pkp.sfu.ca/t/forget-password-email-not-receiving/36574/2

**Comment by asmecher** [comment]
Someone will follow up on that post.
