### ISSUE TITLE
Author can not upload revisions when decision is to resubmit for review

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6529]
**Describe the bug**
When requesting revisions, the editor can choose whether or not the revisions will be subject to another round of review. If the editor chooses the resubmit for review option (`SUBMISSION_EDITOR_DECISION_RESUBMIT`), then the author will not have permission to upload revisions.

**To Reproduce**
1. Create a submission and move it to the review stage.
2. Click on Request Revisions, select resubmit for review, and save.
3. Login as the author
4. Click the Add File link in the revisions grid.
4. See authorization error.

**What application are you using?**
3.2.1-2 and 3.3 RC2

**Additional information**
This bug was introduced with 3.2.1-2 as part of https://github.com/pkp/pkp-lib/issues/6257. It also exists in 3.3RC2. Fixes are needed in both places.

See the [forum report](https://forum.pkp.sfu.ca/t/revisions-upload-file-access-denied-for-author-in-ojs-3-2-1-2/64727/8).

**Comment by NateWr** [comment]
Merged to master and stable-3_2_1.

**Comment by apacetech** [comment]
I am using Open Journal Systems 3.2.1.2 and I still facing same issue
![image](https://user-images.githubusercontent.com/6003206/104094969-3d410c80-52ba-11eb-9197-e9b61ebe9729.png)

Please help

**Comment by NateWr** [comment]
This fix will not be available until 3.2.1-3 is out.

**Comment by jmvezic** [comment]
@NateWr I think this might have been a bug only when the author also has a reviewer role when submitting the article. It doesn't show up in 3.2.1-2 for me when submitting only with the "author" role. In any case, glad it's fixed.

**Comment by jmvezic** [comment]
@apacetech If you can't pull the fix from GitHub, you can follow these steps to circumvent the issue:.

- Login as editor and go to the submission with this issue
- Go to review, round 1
- Click Request Revisions
- Click "Revisions will not be subject to a new round of peer reviews" - this will nullify the previous new round decision
- Inform the author they can now upload the new submission as "Revision"
- After the author uploads the revision, manually add a new review round and choose the revision file to transfer to new round
