### ISSUE TITLE
[OJS] native import causes fatal error during Issue cleanup after failure

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#653]
If importing multiple issues with one or more issues being successful and a later issue failing, the native importexport plugin will call `NativeImportDom::cleanupFailure ($dependentItems)` and then try to individually delete the successful issues.
https://github.com/pkp/ojs/blob/f4cf6ed7bb782c0c0a9f0afaa4e6fc1ecfccdd77/plugins/importexport/native/NativeImportDom.inc.php#L72

The iteration through the issue's `deleteIssue()` fails at
https://github.com/pkp/ojs/blob/f4cf6ed7bb782c0c0a9f0afaa4e6fc1ecfccdd77/classes/issue/IssueDAO.inc.php#L491
because IssueFileManager can't be instanciated against an non-existent issue.
https://github.com/pkp/ojs/blob/f4cf6ed7bb782c0c0a9f0afaa4e6fc1ecfccdd77/classes/file/IssueFileManager.inc.php#L38

As I read it, `NativeImportDom::cleanupFailure ($dependentItems)` should clean up all created items, and the calls to `$issueDao->deleteIssue($issue)` should be unnecessary.  Not having fully tested this, I propose deprecating this functionality.

**Comment by asmecher** [comment]
Resolved this by removing the whole clause.
