### ISSUE TITLE
Trying to set Georgia font in OMP

### ISSUE THREAD

**Issue by neves01** [pkp/pkp-lib#6532]
**Describe the bug**

Im trying to add a custom font (Georgia) on my OMP install. The default font Noto-sans always overrides.

**To Reproduce**

1. Edit **DefaultThemePlugin.inc.php** and add/modify:

```
if (Config::getVar('general', 'enable_cdn')) {
			$this->addStyle(
				'fontGeorgia',
				'https://fonts.googleapis.com/css?family=Georgia:400,400italic,700,700italic',
				array('baseUrl' => '', 'contexts' => 'htmlGalley')
			);
			$additionalLessVariables[] = '@font-georgia: Georgia, sans-serif;';
}
```

2. Edit **styles/variable.less**:

```
// Typography
//
@font:			 "Georgia", sans-serif;
```

3. Refresh the omp website, and inspect some body element.

**What application are you using?**

  OMP
  Code version:      3.2.1.2
  Database version:  3.2.1.2
  Latest version:    3.2.1.2

**Additional information**

Result from element inspect:

```
body {
    font-family: "Noto Sans",-apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Oxygen-Sans","Ubuntu","Cantarell","Helvetica Neue",sans-serif;
...
}
```

PS: I already read the issue https://github.com/pkp/healthSciences/issues/165

Thanks in advance.

**Comment by NateWr** [comment]
A couple of things to check:

1. This line indicates that the `<link>` tag will only be added to an HTML galley view: `array('baseUrl' => '', 'contexts' => 'htmlGalley')`. You can get rid of the `contexts` property if you want it to appear everywhere.
2. What is `enable_cdn` set to in your config.inc.php?
3. Have you cleared the template cache under Administration > Clear Template Cache? This will ensure the CSS files are recompiled.

**Comment by neves01** [comment]
The changes happened with step **3**. Thanks @NateWr!
