### ISSUE TITLE
Optionally require reCaptcha during the login

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6539]
**Describe the problem you would like to solve**
In order to pass through some auditing, the editors need to increase the application security by requiring the reCaptcha validation in the login page.

**Describe the solution you'd like**
As the reCaptcha is already working in the register page, we just need to port it to the login page.
An extra configuration (`captcha_on_login`) might be added to the config.inc.php.

**Comment by jonasraoni** [comment]
PRs:
[PKP-LIB](https://github.com/pkp/pkp-lib/pull/6541)
[OMP](https://github.com/pkp/omp/pull/905)
[OJS](https://github.com/pkp/ojs/pull/2981)
[OPS](https://github.com/pkp/ops/pull/101)

**Comment by asmecher** [comment]
Thanks, @jonasraoni -- I've left some comments here: https://github.com/pkp/pkp-lib/pull/6541#pullrequestreview-563102644

**Comment by asmecher** [comment]
Thanks, @jonasraoni! The PRs listed above are ready for merge once the `master` branch has been forked to `stable-3_3_0`.

**Comment by jonasraoni** [comment]
Hi @asmecher, these PRs should be merged as well, I've just updated the `config.TEMPLATE.inc.php`:
[OMP](https://github.com/pkp/omp/pull/905)
[OPS](https://github.com/pkp/ops/pull/101)
[OJS](https://github.com/pkp/ojs/pull/2981)

**Comment by asmecher** [comment]
@jonasraoni, those three need to be rebased because of conflicts in the `lib/pkp` submodule. If you keep the submodule update in its own commit I can cherry-pick the rest in the future (this isn't an infrequent problem). Please also add some documentation of the new configuration file parameter in `docs/release-notes/README-3.4.0` (see other release notes for the format to use).

**Comment by jonasraoni** [comment]
@asmecher Since the pkp-lib changes were already merged, I've just removed the submodule from the commit and updated the release notes.

**Comment by asmecher** [comment]
Thanks, @jonasraoni -- merged!
