### ISSUE TITLE
Section editors listbuilder entries can't be deleted

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#654]
When editing a section, entries in the section editor listbuilder cannot be deleted. There should be a delete icon of some sort on each row.

**Comment by asmecher** [comment]
See also https://github.com/pkp/pkp-lib/issues/666

**Comment by NateWr** [comment]
The commit above adds the missing icon, but clicking it still does nothing.

**Comment by asmecher** [comment]
Fixed.
