### ISSUE TITLE
OMP 3.3 Reviewers don't have access to review files

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6540]
**Describe the bug**
When a Press Manager sends a review request, files are selected as part of the request. However, when a reviewer goes to the Review request no files are provided to them.

**To Reproduce**
1. Add reviewer
2. Confirm files to be reviewed - all files have been selected
3. Send request

**What application are you using?**
OMP 3.3 r2

**Additional information**
Logged in as reviewer following request and noticed that there is no review files included. 

https://user-images.githubusercontent.com/50342731/103819043-87a65d00-501e-11eb-98f8-ad4f2220a20d.mp4

**Comment by asmecher** [comment]
Good spotting, @pmangahis! This actually affects 3.2.x as well -- there was an assumption in a piece of the code that all reviews are external reviews, but yours is an internal review.

@israelcefrin, could you update the testing install to the latest `master` (both `ops` and `pkp-lib` repositories) so the fix (which has been committed) can be verified?

**Comment by israelcefrin** [comment]
@asmecher is it required to recreate the database also?

**Comment by asmecher** [comment]
Yes, I'm afraid so!

**Comment by pmangahis** [comment]
Just tried this now on an internal review request, the reviewers are still not getting access to the files in the request even though files were selected by the Section Editor in the Reviewer request. 

![image](https://user-images.githubusercontent.com/50342731/104228188-5901fb00-53ff-11eb-953f-4a8b63823002.png)

The option to grant access after the request has been sent seems to work now though.

**Comment by asmecher** [comment]
Thanks, @pmangahis, you caught an additional case of a similar problem! Fixed with https://github.com/pkp/pkp-lib/commit/d9925ea288135d769253cc5153fc22e84f3d7be2. I've tested it locally and will close this issue, but if you see anything else similar, please add a note here.

**Comment by asmecher** [comment]
(Correction: this did not affect 3.2.x, where `SUBMISSION_FILE_INTERNAL_REVIEW_FILE` had not been introduced to distinguish internal from external review files. Those commits have been reverted.)
