### ISSUE TITLE
OMP 3.3 Review Confirmation Status - no change

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6543]
**Describe the bug**
After a Press reviewer views the internal reviewer comments, there is no change in the interface. 

https://user-images.githubusercontent.com/50342731/103832771-078af200-5034-11eb-8373-6851538a980c.mp4

**To Reproduce**
1. Click Read Review
2. Confirm

**What application are you using?**
OMP 3.3 r2

**Additional information**
Compared this against OMP 3.2 which does give the Press Editor the option to Thank Reviewer or Revert Decision after reviewing the comments.

![image](https://user-images.githubusercontent.com/50342731/103832948-7cf6c280-5034-11eb-9a03-c5425f8adfc3.png)

**Comment by asmecher** [comment]
It looks like after you clicked "Confirm" you had to click outside the modal to get it to close (i.e. there was a problem saving the changes) -- can you confirm?

**Comment by pmangahis** [comment]
Tried clicking confirm and waiting for the screen to close on its own and there's still shows 'Read Review.'

**Comment by asmecher** [comment]
So just to confirm -- the window does close on its own? Could you PM me a link to the installation via Slack?

**Comment by pmangahis** [comment]
Just retested this now, and yes, the screen closes on its own after clicking confirm.  The dashboard seems to update properly now that Israel updated the OMP test installation.

**Comment by asmecher** [comment]
OK! I'm not sure what the initial cause of this was, but it seems to be fixed, correct?

**Comment by pmangahis** [comment]
I believe so!

**Comment by asmecher** [comment]
Thanks!
