### ISSUE TITLE
Allow authors to specify a license for their preprints

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6544]
**Describe the problem you would like to solve**
Authors are not able to specify license/copyright information for their preprints. The manager can configure the preprint server to assign licensing information when the preprint is posted, but the author does not have any control over this.

**Describe the solution you'd like**
It should be possible for the author to choose a license. It may also be important for the author to be able to adjust the copyright holder and year, in case these do not match what is generated by the system.

Some questions:

1. Should authors be able to enter their own license or only choose from a list of licenses allowed by the preprint server?
2. Should a license be required before a preprint can be posted? In OJS, we automatically apply a license because this is typically something configured by the journal and kept the same for all articles. But in OPS it may be better to require the author to specify a license as a pre-publication check.
3. Does the author need control over the copyright holder and year? It is automatically set to the authors, but are there cases where this might not match the named authors of the preprint? And if so, is this common enough that authors need control or can it be dealt with by moderators?
4. Currently, a preprint server can choose who to assign copyright to: the author or the server. This is a holdover from how OJS works, but is it inappropriate for OPS? Are there any cases where the preprint server, and not the author, should be assigned copyright?

cc @alexxxmendonca 
 
**Who is asking for this feature?**
We received a request about this from a potential OPS adopter.

**Comment by ajnyga** [comment]
This is a very basic implementation of the issue: https://github.com/pkp/ops/pull/169

1. The current approach allows authors to choose from a predefined list of CC licenses. 
2. Currently not a required field, but we could add the same controls for the field like we have for other metadata.
3 and 4 Did not include this, can we have a situation where a server demands copyright?

**Comment by NateWr** [comment]
Hey @alexxxmendonca, @ajnyga did some work on this, but we still don't know enough about your use cases. Can you provide any answers for the four questions in the original post above?

**Comment by alexxxmendonca** [comment]
> 1. Should authors be able to enter their own license or only choose from a list of licenses allowed by the preprint server?

It's more likely that authors are asked to choose from a list of licenses that match the server's policy.

> 2. Should a license be required before a preprint can be posted? In OJS, we automatically apply a license because this is typically something configured by the journal and kept the same for all articles. But in OPS it may be better to require the author to specify a license as a pre-publication check.

This can be dealt with at the submission level. The authors should be aware of the server's policy before submitting a manuscript. There is no need to require that again before posting.

> 3. Does the author need control over the copyright holder and year? It is automatically set to the authors, but are there cases where this might not match the named authors of the preprint? And if so, is this common enough that authors need control or can it be dealt with by moderators?

I am not sure about this one. It never happened with this even after 1000+ preprints posted.

> 4. Currently, a preprint server can choose who to assign copyright to: the author or the server. This is a holdover from how OJS works, but is it inappropriate for OPS? Are there any cases where the preprint server, and not the author, should be assigned copyright?

For this one I am also not sure. It would be rare for the copyright to be with the server and not the authors, specially within open science context. But I can see it happening if OPS is being used outside an open science context. 

I should note that it's very difficult to speak on behalf of every preprint server.

**Comment by NateWr** [comment]
Thanks @alexxxmendonca!

> It's more likely that authors are asked to choose from a list of licenses that match the server's policy.

Currently, the list of licenses is not editable. These are the only licenses supported by default: https://github.com/pkp/pkp-lib/blob/main/classes/core/PKPApplication.inc.php#L758-L763. Would that work for you or does the list of valid licenses need to be editable by the preprint server?

@ajnyga is the license editable at all after submission? I think we are going to run into cases where a license needs to change, even if it is just due to human error (accidentally selecting the wrong one).

**Comment by ajnyga** [comment]
It is editable the same way as in OJS, meaning that there is a text field where you can currently enter any license url.

**Comment by alexxxmendonca** [comment]
@NateWr that looks fine.

There is also the option of adding a URL to another license, right?
![image](https://user-images.githubusercontent.com/4059679/128862207-a507a478-e60d-4af2-9324-80bc00b2c7c6.png)

This should cover everything.

**Comment by ajnyga** [comment]
Yes, we optionally have that extra selection in the submission form as well. Just thinking that some users might prefer the limited set of options.

**Comment by NateWr** [comment]
Great, thanks to both of you. I've merged it in! :tada: 

I don't think we'll be able to specify an optional other license URL _during submission_, because it uses the old forms system. But in 3.4 this will be converted over to the new forms so it should be pretty easy to add that in.
