### ISSUE TITLE
Remove use of fileId when referring to submissionFileId

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6545]
In `ArticleHandler` and `PreprintHandler`, the variable name `fileId` is used to refer to the `submissionFileId` when viewing a galley. This is confusing because elsewhere `fileId` is used to refer to the underlying file in the `files` table. This should be cleaned up to prevent bugs from occurring in the future.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/3545
- https://github.com/pkp/ops/pull/352

@jonasraoni, when these finish testing, could you have a look?

**Comment by asmecher** [comment]
Merged, thanks Jonas!
