### ISSUE TITLE
Bug in DB upgrade script (OJS 3.1.2-4 --> OJS 3.2.1-2) --> data loss!

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#6549]
In the upgrade for the OJS 3.1.2-4 --> 3.2.1-2, journal e-mail template data get lost due to wrong SQL queries:

https://github.com/pkp/ojs/blob/9ca2e7a8df939de7c89599ecdd4ae067869f2845/dbscripts/xml/upgrade/3.2.0_update.xml#L38-L51

There is no column "email_id" in the table email_templates_data (OJS 3.1.2)!

±-----------±-------------±-----±----±--------±------+
| Field | Type | Null | Key | Default | Extra |
±-----------±-------------±-----±----±--------±------+
| email_key | varchar(64) | NO | MUL | NULL | |
| locale | varchar(14) | NO | | en_US | |
| assoc_type | bigint(20) | YES | | 0 | |
| assoc_id | bigint(20) | YES | | 0 | |
| subject | varchar(120) | NO | | NULL | |
| body | text | YES | | NULL | |
±-----------±-------------±-----±----±--------±------+

Several installations have lost data because of this, see 

https://forum.pkp.sfu.ca/t/upgrade-from-ojs-3-1-2-4-to-ojs-3-2-1-2-email-templates-several-problems-and-questions/64932

**Comment by asmecher** [comment]
@mpbraendle, the `email_id` column is added in a previous upgrade step (dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml).

**Comment by mpbraendle** [comment]
Thank you, will try those steps on our restored OJS 3.1.2-4 DB and see what happens then.

**Comment by mpbraendle** [comment]
How are the dropindex statements carried out?

**Comment by mpbraendle** [comment]
OK, found it in lib/pkp/lib/vendor/adodb/adodb-php/datadict/datadict-postgres.inc.php:	function DropIndexSQL ($idxname, $tabname = NULL)

**Comment by mpbraendle** [comment]
OK, found it in lib/pkp/lib/vendor/adodb/adodb-php/adodb-datadict.inc.php:	function DropIndexSQL ($idxname, $tabname = NULL)

**Comment by mpbraendle** [comment]
I have now carried out manually the steps in dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml on a backup of the 3.1.2-4 DB.

No how can I create the table email_templates_settings that is defined in lib/pkp/xml/schema/common.xml ? Is there a script / method I can lookup? There seems to be no instruction in dbscripts/xml/upgrade/3.2.0_update.xml - this assumes that the table already exists.

**Comment by mpbraendle** [comment]
OK, I found this nice tool dbXMLtoSQL.php in tools - all fine :-)

**Comment by mpbraendle** [comment]
I could create the table and replicate the steps in dbscripts/xml/upgrade/3.2.0_update.xml 
The data seems to look fine - no idea what had happened during migration of the production DB that has damaged the data.
We will try to copy over this data from the migrated backup table to the new production DB next week.

**Comment by asmecher** [comment]
:+1: Closing for now -- but if you can shed any light on what happened during the migration, please add it and I'll re-open!

**Comment by mpbraendle** [comment]
Actually, in my understanding, the first column in table email_templates_default should not be called email_id, but email_default_id

email_id in email_templates and email_id in email_templates_default do describe two entirely different datasets.

**Comment by jmvezic** [comment]
@mpbraendle perhaps you're encountering a variation of this issue: https://github.com/pkp/pkp-lib/issues/6432 ?

**Comment by mpbraendle** [comment]
Yes, this is exactly that. Thanks for hint.

**Comment by delzimar** [comment]
Qual foi a solução? Estou com o mesmo problema

**Comment by asmecher** [comment]
@delzimar, could you be a little more specific? What are you doing (e.g. if an upgrade, specify the source and target versions) and what error messages/problems result?

**Comment by delzimar** [comment]
The update has been successfully done, but the system is sending blank emails to editors when subjected articles. In Settings -> Workflow -> E-mail Templates, Multiple E-mail Appears in Arabic.
`<a href="https://ibb.co/vhwmhW6"><img src="https://i.ibb.co/cwgtw9S/arabic.png" alt="arabic" border="0"></a>`

**Comment by asmecher** [comment]
@delzimar, I don't think that's anything to do with this bug entry; maybe have a look at https://github.com/pkp/pkp-lib/issues/6432.
