### ISSUE TITLE
ONIX 3.0 Monograph Export Plugin - wrong instructions

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6551]
**Describe the bug**
In OMP 3.2.0.2, the message on the ONIX plugin if the Press information is not properly filled in is inaccurate. It refers to a path that doesn't actually exist. I think this should tell users to complete the Press information in Setting > Press > Publisher Identity

![image](https://user-images.githubusercontent.com/50342731/103937364-838d4480-50dd-11eb-8565-c31e01056c19.png)

**Comment by asmecher** [comment]
This has already been fixed as part of https://github.com/pkp/pkp-lib/issues/5865 for release in OMP 3.3; fixing it for 3.2.x isn't a high priority.
