### ISSUE TITLE
OMP 3.3 Open HTML galley asking to log in to the system

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6552]
**Describe the bug**
The HTML galley for the book is redirecting to the login form. If you are logged in, it redirects you to the main catalog page.

**To Reproduce**
1. Go to Catalog > Any book
2. Click on HTML on the sidebar
3. See error

**What application are you using?**
 OMP 3.3

**Additional information**

https://user-images.githubusercontent.com/4992902/103945637-7d11c380-5103-11eb-91f8-7a6740b993b2.mov

**Comment by asmecher** [comment]
@israelcefrin, did the installation get updated since https://github.com/pkp/pkp-lib/issues/6502 was resolved? That change introduced a database change, so content that was created with 3.3rc1/rc2 will be missing the relevant entries.

**Comment by asmecher** [comment]
Alternately, do you have the payment system enabled but not fully configured? For example, if you've chosen the PayPal plugin but not fully configured it, this kind of behaviour may result.

**Comment by israelcefrin** [comment]
> @israelcefrin, did the installation get updated since #6502 was resolved? That change introduced a database change, so content that was created with 3.3rc1/rc2 will be missing the relevant entries.

I will have to update it, since this is install was deployed in December 17th. I will let this for the last and run a few more tests because I will have to recreate the base and re-add content to make it work properly.

**Comment by NateWr** [comment]
Did this get tested again to confirm a bug?

**Comment by israelcefrin** [comment]
@NateWr I've update the install and it is resolved. I will close this issue. Tks!
