### ISSUE TITLE
Fatal Error when calling getPath for files 

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6554]
**Describe the bug**
When trying to Set Availability for a Publication Format, a fatal error occurs.

**To Reproduce**
1. Go to Submission > Publication > Publication Formats
2. Click "Not Available" button to change availability
3. The process does not end, and the PHP error log has the fatal errro

**What application are you using?**
 OJS, OMP or OPS version 3.3

**Additional information**
The fatal error is `PHP Fatal error:  Uncaught Error: Call to undefined method PKP\\Services\\PKPFileService::getPath() in \\controllers\\grid\\catalogEntry\\PublicationFormatGridRow.inc.php:51`

**Comment by defstat** [comment]
@NateWr @asmecher 

**PR**
[pkp-lib]: #6555

**Comment by NateWr** [comment]
`PKPFileService::getPath()` was removed as part of [these changes](https://github.com/pkp/pkp-lib/issues/6502#issuecomment-755267086). The call to the method shouldn't be there anymore in `PublicationFormatGridRow`. Can you update and check to see if you can still reproduce this?

**Comment by defstat** [comment]
I can't reproduce it. Closing the issue and the PR
