### ISSUE TITLE
OMP 3.3 - Creating categories in backend crashes the sidebar in the frontend

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6557]
**Describe the bug**
The categories are being created correctly in backend. However, it is not possible to navigate through them because the sidebar doesn't show the respective blocks when exist categories.

**To Reproduce**
1. Go to 'Dashboard > Settings Press > Categories'
2. Click on 'Add Category'
3. Create a category
4. Save
5. Reload the public reader interface
6. Check the sidebar

**What application are you using?**
OMP version 3.3

**Additional information**

https://user-images.githubusercontent.com/4992902/104066415-63d64900-51cf-11eb-8c4d-015801f6dbd4.mov

**Comment by jnugent** [comment]
I've debugged this on the back end and the fatal error being generated here is:

[Sat Jan 09 10:06:08.402419 2021] [cgi:error] [pid 30058:tid 47449582774016] [client 142.134.185.19:35488] AH01215: PHP Fatal error:  Uncaught Error: Call to a member function getId() on string in /www/omp3/testing-3_3/cache/t_compile/e9acfaa63992be8b73da417127735d220ff56549_0.plugins-1-plugins-blocks-browse-blocks-browse.block.tpl.php:55

For some reason Smarty doesn't seem to like the `{$category->getId()}` syntax.  If I remove that one, it then complains about the next one, calling -`>getParentId()`.

**Comment by NateWr** [comment]
Thanks for the fatal error! The problem is that `$category` is a `string` but the template expects it to be a `Category` object.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/omp/pull/906
