### ISSUE TITLE
Authorization header with JWT can cause fatal error

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6563]
**Describe the bug**
The ArticleHandler permits access to unpubllished content when an API key is passed in an Authoriziation header (see [here](https://github.com/pkp/ojs/blob/master/pages/article/ArticleHandler.inc.php#L48-L55)).
However, if an authorization header is passed but it is not a JWT or formatted so that a value gets assigned to `$jwt`, it cases an exception in `JWT::decode()`.

I think just checking for a non-empty value in `$jwt` will fix this.

**To Reproduce**
Untested, but i think:
1. Create an unpublished submission.
1. Send a GET request to the article's page with an Authorization header with some dummy text, like `asdf`.

**What application are you using?**
 OJS, OMP or OPS version 3.3RC2

**Additional information**
See [report in the forum](https://forum.pkp.sfu.ca/t/php-fatal-error-uncaught-invalidargumentexception-key-may-not-be-empty/65164).

**Comment by asmecher** [comment]
Deferring to later.

**Comment by NateWr** [comment]
@asmecher can you double-check I haven't done something stupid here? Not urgent for 3.3.

PR:
https://github.com/pkp/ojs/pull/3022

**Comment by asmecher** [comment]
Looks good to me, @NateWr, and feel free to merge to `master` now that I've created `stable-3_3_0` branches.

**Comment by NateWr** [comment]
This did not get cherry-picked into `stable-3_3_0` so it didn't make it into 3.3.0.3. I've cherry-picked it now and updated the milestone.
