### ISSUE TITLE
Changing Journals in multiuser OJS throws a 404 error

### ISSUE THREAD

**Issue by janiosarmento** [pkp/pkp-lib#6564]
**Describe the bug**
When changing Journals, in a multijournal installation, OJS throws a 404 rather than going to the new Journal home, because it tries to return to the same object in a context it is invalid.

**To Reproduce**
1. Go to any object particular to a given Journal (a submission, e.g.)
2. Click on the Journal selection icon, and change the context.
3. See error

**What application are you using?**
 OJS 3.3.0

**Additional information**

https://user-images.githubusercontent.com/7367281/104189315-44baff80-53f9-11eb-9862-b2ca1db8f4d1.mov

**Comment by NateWr** [comment]
@janiosarmento can you tell me what roles you have in each journal?

**Comment by janiosarmento** [comment]
At the moment of the test, I was a superadmin user.

**Comment by NateWr** [comment]
Thanks @janiosarmento! Looks like there are more cases than I expected where a clean switch can't be made. The following PRs only allow the page-to-page switch to happen for whitelisted pages that are always available across all contexts.

PR:
https://github.com/pkp/pkp-lib/pull/6660

Tests:
https://github.com/pkp/ojs/pull/3008
