### ISSUE TITLE
Upgrade to 3.3 from 3.2.1-2 generates a warning for every submission file

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6565]
I tested a very large upgrade from OJS 3.1.2, going first to 3.2.1-2, which ran successfully with no warnings. Taking that upgraded installation and then upgrading to the current master branch for 3.3 generated a warning about "A submission file was expected but not found at ...." for every file in the files_dir directory.

![Screenshot from 2021-01-11 13-37-28](https://user-images.githubusercontent.com/218719/104219672-cbc9a100-5414-11eb-9f91-15d49b86e160.png)

However this seems to have no noticeable impact on the workflow or the public side after the upgrade.  Links work, and so on.  The files for the warnings are definitely present in the correct place, since the warning message helpfully includes the expected file path so this is easy to test.

**Comment by asmecher** [comment]
Hmm, I just tried it and didn't get any warnings -- could it be a file permission problem or something? The 3.2.x to 3.3.x upgrade just checks for the presence of files, it doesn't actually do anything to rearrange the filesystem.

**Comment by jnugent** [comment]
No, same thing just happened when I tried it again.  This time I rolled back to 3.1.2, and upgraded straight to 3.3.  To ensure that I had no file permissions issues I chowned the entire files_dir tree 777 and ran the upgrade as root.  Same result - everything works fine, and while those warnings are printing I can check the database log and see the correct queries running.

**Comment by asmecher** [comment]
Hmm, interesting. Are you using the RC2 package or the `master` branch? If the former, can you try the latter?

**Comment by jnugent** [comment]
This was with the `master` branch.  I'm about to go offline for the night but tomorrow I can stick some debugging in the upgrade code and see why I am getting that warning.

**Comment by asmecher** [comment]
Please do, thanks!

**Comment by NateWr** [comment]
That's interesting. Because these file paths are saved into the database and then used to access the files for downloading. Can you try taking one of the paths it says it can't find and looking for the file in the database, then working backwards to see if you can download the file in the UI?

```
select submission_file_id,submission_id from submission_files as sf
join files as f on (sf.file_id = f.file_id)
where f.path = 'journals/1/articles/...';
```

That should give you the submission file id and the submission id, so then go to the submission's workflow, find the file and try to download it?

**Comment by jnugent** [comment]
@NateWr the warning appears for every single file in the files_dir.  In my test installation, with a 23Gb files_dir tree, there are thousands of warnings.  I can find every file in the UI without problem.  The warnings appear whether I upgrade directly from 3.1.2 to 3.3, or I go through an intermediate 3.2.1-2 step. I am about to start debugging it.

**Comment by jnugent** [comment]
Hehe.  So, the test in:

`./lib/pkp/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php`

at: 

```
if ($fileService->fs->has($path)) {
     error_log("A submission file was expected but not found at $path.");
}
```
Shouldn't that test be negated?  Right now the error message prints if it does indeed fine the file at the `$path` in question.

**Comment by NateWr** [comment]
:laughing: Yep! Good spot, fixed in https://github.com/pkp/pkp-lib/commit/1406e4051b878a55583275ce17be98be6e41e362.

**Comment by asmecher** [comment]
:open_mouth: ...so I have to check why I didn't see those warnings during my own test! Will look into it...

**Comment by NateWr** [comment]
It was probably after your tests, alec: https://github.com/pkp/pkp-lib/commit/9578d9a11756f655ff406510d10d22ff6ea179ce#diff-f4951b8d90b205bf60a1111a761b62eb75f598c0c536738da01d027561a33f1cR320

**Comment by asmecher** [comment]
That's possible -- thanks, @NateWr. Anyway, I'll verify while working on some other upgrade stuff.
