### ISSUE TITLE
move mEDRA plugin to its own repository, accessible via plugin gallery

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6566]
s. https://github.com/pkp/ojs/pull/2597#issuecomment-756492977

**Comment by bozana** [comment]
@asmecher, here is the new medra repository: https://github.com/bozana/medra. Shall we take it over to the pkp?

**Comment by bozana** [comment]
I have forgotten how are the steps for the plugin gallery. I prepared the XML part to insert into the plugins.xml, but when do we insert it and when do we make a release/package and md5? :thinking: 
Also, I am using the next major number (3.0.0.0) for this plugin version. Is that OK?
I haven't rung the tests. Do you maybe know if they are/were working? -- I would need to take a look...

**Comment by asmecher** [comment]
> Shall we take it over to the pkp?

Yes, please transfer it across!

> I have forgotten how are the steps for the plugin gallery.

See: https://docs.pkp.sfu.ca/dev/plugin-guide/en/release
The RC2 OJS package is version 3.0.0.1, so if you want to test, you can use that version in the plugin gallery's OJS compatibility field. OJS 3.0.0 will formally be released as 3.0.0.2, just FYI.

> Can we take GNU General Public License v3 instead of v2 (used till now)?

Yes, please change the license from GPLv2 to GPLv3. All code in the OJS repo should be GPLv3 already, so this would be consistent.

> Also, I am using the next major number (3.0.0.0) for this plugin version. Is that OK?

Yes, that's fine!

**Comment by njikonga-med** [comment]
Hi guys, Waiting for this to be done, is there any thing that can i do in the meanwhile? 
And I noticed that another advantage of being in the Plugin Gallery is the updating process of the plugin, there will be no more the requirements to install a compress file "*.tar.gz" in order to update as it's performed now, right?

Best regards,
Jehu Njikonga

**Comment by bozana** [comment]
PR:
https://github.com/pkp/ojs/pull/3016 (deletion of the medra plugin from ojs core code)

**Comment by bozana** [comment]
New medra repository: https://github.com/pkp/medra
PR for the plugin gallery: https://github.com/pkp/ojs/pull/3016

**Comment by bozana** [comment]
@asmecher, I hope I have considered/done everything for this movement. Could you please take a look, and can we then merge the PR (above) that deletes the medra plugin from the ojs core? Thanks a lot!

**Comment by bozana** [comment]
Hmmm... Maybe one more question:
There can be some entries in the DB tables: filters, filter_settings, plugin_settings, scheduled_tasks, versions, as well as issue_settings, submission_settings, publication_galley_settings. Can they stay as they are? -- The users using medra plugin will then need to install it from the plugin gallery in the next version, right?

**Comment by bozana** [comment]
@njikonga-med, this will come with the next 3.3 release, which is coming in a week or so. And yes, the updates will then be easier - no more deal with .tar.gz.

**Comment by asmecher** [comment]
Those all look good, thanks, @bozana! Please go ahead and merge. Yes, the settings can stay where they were.

**Comment by bozana** [comment]
Thanks @asmecher! Merged and tested, everything seems to be OK, thus closing...

**Comment by asmecher** [comment]
Sorry, one problem due to data in `filter_groups`! See https://github.com/pkp/ojs/commit/f32d0e227ca30f11229e3fac0f3fcf433b938dd4.

**Comment by bozana** [comment]
@asmecher, could you please take a look at the PR: https://github.com/pkp/ojs/pull/3025 ?

**Comment by asmecher** [comment]
Thanks, @bozana, that should do it!
