### ISSUE TITLE
OJS 3.3rc - Cannot Delete Journal Sections

### ISSUE THREAD

**Issue by emmauhl** [pkp/pkp-lib#6567]
**Describe the bug**
Journal sections have the option to be deleted, but when the deletion confirmation pops up, nothing happens when "OK" is pressed/there is no response. Refreshing will show that the section remains undeleted, so the lack of response is not just on the UI end. Checked in both Admin and Journal Manager roles.

**To Reproduce**
1. Go to Journal > Sections.
2. Click on the blue arrow beside a journal section (does not seem to matter if it contains submissions or not).
3. Click "Delete".
4. Click "OK".
![image](https://user-images.githubusercontent.com/45881692/104229157-1ba26b00-5409-11eb-9b07-5a28b27d246f.png)

**What application are you using?**
OJS 3.3cr
Checked in Chrome & Edge.

**Comment by asmecher** [comment]
Could you take a look, @bozana? I suspect this'll be a pretty straight forward fatal error.

**Comment by bozana** [comment]
PR: https://github.com/pkp/ojs/pull/2996
@asmecher, could you please take a look?

**Comment by asmecher** [comment]
Thanks, @bozana! One change to make -- not something you introduced but worth fixing at the same time.
