### ISSUE TITLE
OMP 3.3 - Searching for keyword is returning no value, even with data

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6570]
**Describe the bug**
Using the search tool to search by keywords is not returning any result. 

**To Reproduce**
1. Go to the 'Search form'
2. Type any know keyword you may have used in submissitons
3. Click "search: 

**What application are you using?**
 OMP  version 3.3

**Additional information**

https://user-images.githubusercontent.com/4992902/104243472-9af66580-542e-11eb-909b-3979ddab0c5c.mov

**Comment by NateWr** [comment]
This is a known limitation: https://github.com/pkp/pkp-lib/issues/5388
