### ISSUE TITLE
OMP 3.3 - Disable/enable press for public appearing is not available

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6576]
**Describe the bug**
It is not possible to disable a press from public view. The section/option when editing a Press is not available.

**To Reproduce**
1. Go to 'Administration'
2. Click on the clue arrow beside any press title 
3. Click on 'Edit'
4. See the error in the modal (missing optio)

**What application are you using?**
OMP 3.3

**Additional information**
![image](https://user-images.githubusercontent.com/4992902/104342652-10167900-54c9-11eb-88f6-5850348b1170.png)

**Comment by NateWr** [comment]
This was dropped as far back as 3.2.0. The following PRs add it back for OMP and OPS:

PRs:
https://github.com/pkp/ops/pull/106
https://github.com/pkp/omp/pull/907

**Comment by NateWr** [comment]
Merged.
