### ISSUE TITLE
OMP 3.3 - Removing presses is not updating the list automatically

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6577]
**Describe the bug**
When a press is removed, neither the modal closes or the list is automatically update. It seems that didn't work the request.

**To Reproduce**
1. Go to 'Administration'
2. Click on the blue arrow beside any press title 
3. Click on 'remove' 
4. Click on 'ok' in the modal
4. See the error

**What application are you using?**
 OMP 3.3

**Additional information**

https://user-images.githubusercontent.com/4992902/104345905-d47dae00-54cc-11eb-98df-2f3bc4caa25a.mov

**Comment by NateWr** [comment]
Found a bunch of bugs with that one, thanks @israelcefrin!

PR:

**Comment by NateWr** [comment]
Merged.

**Comment by aftechro** [comment]
have the same thing on ojs 3.4 but regardless of reloading the page, the journal is still there.
any ideas?

**Comment by israelcefrin** [comment]
> have the same thing on ojs 3.4 but regardless of reloading the page, the journal is still there. any ideas?

I've filed a new issue and included a video that shows the bug as well.
