### ISSUE TITLE
Update TinyMCE

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6578]
See Dependabot PR: https://github.com/pkp/ui-library/pull/135
See security issue listing: https://github.com/pkp/ui-library/security/dependabot/package-lock.json/tinymce/open

(There are probably other open PRs from Dependabot on the same issue in e.g. pkp-lib)

**Comment by NateWr** [comment]
@asmecher it looks like we bumped TinyMCE to 5.x in the composer but not the UI library. This updates the UI Library dependencies, fixes a cypress dependency incompatibility with the file upload plugin, and updates our UI component to reflect changes in 5.x.

Once I get this passing in OJS I'll prepare PRs for OMP/OPS.

PRs:
https://github.com/pkp/ui-library/pull/164
https://github.com/pkp/pkp-lib/pull/7192
https://github.com/pkp/ojs/pull/3161

**Comment by asmecher** [comment]
Whoops, thanks for catching that, @NateWr. I don't think this is a major one for us.

**Comment by NateWr** [comment]
Merged to `main` for all three apps.
