### ISSUE TITLE
OMP 3.3 - Pagination setting not working

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6581]
**Describe the bug**
Limiting the number of listed items/pagination is not working. It keeps showing the total of items up to 25 at least.

**To Reproduce**
1. Go to 'Websiste > Setup > Lists'
2. Adjust the items per page and Page links to a lower number, i.e.: 2
3. Go to 'Submissions'
4. Check a tab with more than 2 items
5. See the error

**What application are you using?**
OMP 3.3

**Additional information**

https://user-images.githubusercontent.com/4992902/104372224-f89db700-54ed-11eb-8222-b7a370334194.mov

**Comment by asmecher** [comment]
I think this is superseded by https://github.com/pkp/pkp-lib/issues/2037.
