### ISSUE TITLE
when a submission is removed from the issue TOC the publication still contains issueId

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6584]
**Describe the bug**
When a submission is removed from the issue TOC, the issueId still remains in the db table publication_settings.

**To Reproduce**
1. Go to a back issue > a submission > click on the action "Remove"
2. see the db table publication_settings

**What application are you using?**
 OJS version 3.3, master branch 

**Additional information**
-

**Comment by bozana** [comment]
@NateWr, actually I am not sure what is the right behavior for this case -- because the submission was published and then removed -- maybe it is correct so (to have the issueId bounded to the publication, but somehow I don't think so)? (I found the issue when writing the tests for https://github.com/pkp/pkp-lib/issues/5948).

**Comment by NateWr** [comment]
Yes, this is how it is meant to work. It can be a little bit confusing. But when an issue is published, it only publishes the submissions that are assigned to it and have the `STATUS_SCHEDULED` status. So it's possible for a submission to be assigned to an issue but not scheduled for publication.

With the versioning, we've introduced a new status, `STATUS_SCHEDULED`. So now a submission can be queued, scheduled or published. The scheduled status indicates when something is ready to be published (ie - it has passed pre-publication checks and been scheduled for publication).

This distinction is useful for identifying submissions that are part of an issue but haven't yet been signed-off as scheduled for publication.
