### ISSUE TITLE
Upgrade fails if submission file has revisions on restructuring submission_files table

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6585]
**Describe the bug**
Upgrade from OJS 3.2.1-2 to OJS 3.3 fails with a fatal error:
```
ERROR: Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'PRIMARY' (SQL: alter table `submission_files` add primary key `submission_files_submission_file_id_primary`(`submission_file_id`))
```

**To Reproduce**
Upgrade OJS instance which contains submission files with revisions

**What application are you using?**
 OJS 3.3 - state of the current master branch

**Additional information**
AS far as I understand `submission_file_id` should contain unique incremental values. All revisions should be recorded in the separate table `submission_file_revisions` and duplicate (revisions') IDs should be removed from the `submission_file` table

**Comment by NateWr** [comment]
Can you find reproduction steps from a clean database? The migration should account for files with revisions so I'm wondering if there's something else going on...

**Comment by Vitaliy-1** [comment]
@NateWr, I'm using the OJS instance with a history of updates from OJS 3.0. It contains submission_files associated with non-existing submission_id, which is failing here: https://github.com/pkp/pkp-lib/blob/b904caeb2cca079ff546ef32a68b444c0b09b430/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php#L287. 
I mean that the entries that do not fall under this condition are never updated and `new_file_id` isn't assigned to those rows, which leads to the error pointed above. 

By the way, it's related to the first submission. Is there any interest in fixing such cases during the upgrade? I can assume that only a very small percent of OJS intances may be affected here.

**Comment by NateWr** [comment]
I'm sure that a number of old OJS installs will have submission files attached to a submission id that no longer exists. So yeah, we should definitely try to fix this. In my view, these files can maybe be skipped with an `error_log`. @asmecher any thoughts here? Should we try to preserve the data for these files or consider them "lost"?

**Comment by asmecher** [comment]
Ah, I actually just filed/fixed this based on SciELO's dataset. See https://github.com/pkp/pkp-lib/issues/6615 -- confirmation that the PRs fix this for you would be very helpful, @Vitaliy-1!

**Comment by asmecher** [comment]
(We're going to deal with a lot of messy data like this as we start to use proper foreign key declarations -- I suggest we clear out "bad" data whenever we add a foreign key in the upgrade process.)
