### ISSUE TITLE
[UI] Issue and article galleys don't load

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#659]
We have some critical problems with issue and article galleys that need to be fixed for OJS 3.0b.

- [x] Non-pdf Issue galleys load 404. `viewInterstitial` op seems to be broken
- [x] PDF Issue galleys load template but not PDF file. `Call to undefined method IssueFile::getFileName()` See #637
- [x] All article galleys fail to load
- [x] `issue/interstitial.tpl` needs to be refactored into new template structure or removed
- [ ] `$pubIdPlugins` is defined in issue views. But it's not been tested in any way.

**Comment by asmecher** [comment]
The remaining issue was covered by Bozana's pub IDs rewrite. Closing.
