### ISSUE TITLE
OJS 3.3 - Submission for multilingual journal stuck in the file upload step

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6591]
**Describe the bug**
When a journal is a multilingual install, it fails to create new submission being stuck in the upload file step.

**To Reproduce**
1. Go to Settings > Website > Setup > Languages and configure a journal to support French, English and German, with German as the journal’s primary language.
2. Create a submission and select French as the submission’s language.
3. Choose a file to uploaded (second tab)
4. See the error

**What application are you using?**
 OJS  version 3.3

**Additional information**

https://user-images.githubusercontent.com/4992902/104506278-28fb5900-55b3-11eb-89a1-92ccefc7fcaf.mov

**Comment by asmecher** [comment]
@israelcefrin, I think there's probably a fatal error to go with this; can you check the PHP error log?

**Comment by asmecher** [comment]
Actually, I was able to reproduce this myself. There's just a warning:
```
PHP Notice:  Undefined index: en_US in .../lib/pkp/classes/validation/ValidatorFactory.inc.php on line 280
```
It looks like the validators is assuming that the primary language is present, when the upload occurs using the currently selected (in this case non-primary) locale.

**Comment by asmecher** [comment]
Does this make sense to you, @NateWr? https://github.com/pkp/ui-library/pull/138

**Comment by NateWr** [comment]
Yep, good catch!

**Comment by asmecher** [comment]
Merged, thanks!
