### ISSUE TITLE
Allow SVG in TinyMCE uploads

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6595]
**Describe the problem you would like to solve**
When uploading an image to a rich text field, the file selector does not allow you to select SVG files. An example is the Page Footer field under Settings > Website > Appearance > Setup.

**Describe the solution you'd like**
It should be possible to upload SVG files using the rich text editor's image upload tool.

**Who is asking for this feature?**
Hosting

**Comment by asmecher** [comment]
This might have very undesirable side-effects; see: https://stackoverflow.com/questions/33387722/is-there-any-way-to-make-user-uploaded-svg-images-safe-from-code-injection-etc

**Comment by asmecher** [comment]
Closing; see https://github.com/pkp/pkp-lib/issues/9315.
