### ISSUE TITLE
[UI] Journal logos and alternate header not loading on journal index page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#660]
`$currentJournal` is available but all of the variables that should be assigned from it, like `$displayPageHeaderLogo`, are not defined on the journal index page. As a result, several things don't appear which should.

Only seems to effect `index.tpl`. The logo appears on other pages.

Alternate header also affected.

**Comment by asmecher** [comment]
I suspect this relates to the distinction we used to have between "home header logo" (only on the homepage) and  "page header logo" (everywhere else).

**Comment by asmecher** [comment]
See also https://github.com/pkp/pkp-lib/issues/867

**Comment by nmpx** [comment]
Should I make a different issue for the fact that the Alternate Header doesn't seem to display anywhere?

**Comment by asmecher** [comment]
Thanks, @nmpx, I've flagged it here too.

**Comment by NateWr** [comment]
Site-wide journal logo works now. And the alternate header option has been removed. Closing.
