### ISSUE TITLE
Portico plugin for OJS includes unexpected contrib-id element

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6603]
See https://github.com/jmacgreg/portico/pull/16#issuecomment-759754416 for details.

**Comment by jonasraoni** [comment]
@asmecher The `contrib-id` element came from this [newer version](https://jats.nlm.nih.gov/archiving/tag-library/1.2d1/element/contrib-id.html).

I've tried to discover which version Portico supports, but I couldn't find anything [in their guidelines](https://www.portico.org/wp-content/uploads/2018/02/P_JournalSubmissionGuidelines_180205.pdf) nor in Google.

I suppose we're safe to upgrade the doctype, but I'll contact Portico to confirm...

**Comment by asmecher** [comment]
Hi @jonasraoni -- I've asked a contact there as well.

**Comment by asmecher** [comment]
Hi @jonasraoni ! Here's Portico's feedback:
> You are currently using NLM archiving 3.0 in the OJS export, which is the version of NLM we are expecting. You are correct that the problem was with the introduction of ORCID in contrib which is not supported in NLM versions.
>
> Our preference is to  continue to receive OJS content deposits in NLM 3.0 (without the ORCID that makes content invalid). However,  if you are going to provide in JATS we can support all versions: 1.0, 1.1, or the latest stable version 1.2.

Can you give me more information on the client's interest in adding ORCIDs, since Portico seems to prefer not to have them?

**Comment by jonasraoni** [comment]
@asmecher They are using the Portico plugin solely as a way to get articles in the JATS format for https://acm.org.

But well, since Portico accepts the latest version of JATS, we're safe to upgrade the doctype, keep the `contrib-id`, and maybe add something else (I'd need to take a look at the available tags and compare with what we have).
Pity that there isn't an universal transform tool out there, I'm dealing often with converting from one format to another.

I'll send PRs later! I'm just not sure I'll include the tests, I still need to check how to work with it.

ps: I still didn't get an answer from Portico 👀

**Comment by jonasraoni** [comment]
PR for master: https://github.com/pkp/portico/pull/1
As I'll have to update the 3.1.2 branch, I'll create more PRs.

**Comment by asmecher** [comment]
@jonasraoni, I'm in the process of adding support for multiple recipients in order to support deposit with LOC as well as Portico (https://github.com/asmecher/portico/tree/support-multiple-endpoints-and-sftp) -- I haven't factored in a change of DTD in the process, and would not rather move an "official" Portico plugin away from the DTD they'd rather support without doing some more digging first.

I think the best solution will be to revert the ORCID addition so that the plugin works with the current DTD, get the multiple endpoint support added and merged, then come back to a potential DTD change with a little more consultation after that.

Can you revert the ORCID addition for the moment, and create a new issue for consideration of the DTD change with a quick description of what's involved? Then we can get a few stakeholders to discuss there.

Have you looked at the [JATS Template plugin](https://github.com/pkp/jatsTemplate/) as a potentially better source for JATS from OJS?

**Comment by jonasraoni** [comment]
Ok! Let's postpone this update =]

---

Once there's a confirmation, it would be better to replace the local serialization by this plugin, as it will decrease the maintenance/code duplication.

Ideally the plugin should provide different serialization formats, then we could already adopt it here.
It's just needed to come up with a good idea to decrease the maintenance of updating every format (turning the elements into reusable "Lego bricks" would help).

**Comment by jonasraoni** [comment]
@asmecher I've updated the PR to remove the tag, but I've left some fixes.

**Comment by asmecher** [comment]
@jonasraoni, with apologies for the whiplash, Portico has double-checked and actually they are fine with JATS -- as is LOC. Could you re-add the DTD change and ORCID? Last time, I promise :)

**Comment by jonasraoni** [comment]
The ORCID is back, should I send PRs for the 3.x branches?

**Comment by asmecher** [comment]
> The ORCID is back. Should I send PRs for the 3.x branches?

Thanks, @jonasraoni! Yes, please do back-port to `stable-3_2_1`, `stable-3_1_2`, and `stable-3_1_1`.

**Comment by jonasraoni** [comment]
@asmecher Follow the PRs:
[3.1.1](https://github.com/pkp/portico/pull/4)
[3.1.2](https://github.com/pkp/portico/pull/2)
[3.2.1](https://github.com/pkp/portico/pull/3)

**Comment by asmecher** [comment]
Thanks, @jonasraoni! Closing for now -- though I'll do a round of testing with Portico before I release an updated plugin.

**Comment by jonasraoni** [comment]
@asmecher Ok! I just tested fast (created a submission, added some data, published and exported), it's better to do a real test with them. Would be nice to add some automated tests =]
