### ISSUE TITLE
OMP 3.3 - Delete Warning pop-up

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6606]
**Describe the bug**
In OJS 3.3 if a user tries to delete a submission it does not currently show a proper warning notification for the user. 
![image](https://user-images.githubusercontent.com/50342731/104642864-52be8980-5660-11eb-8d3a-867e728a8408.png)

**To Reproduce**
1. Click Blue arrow of declined submission
2. Click on Delete

**What application are you using?**
OMP 3.3 r2

**Comment by asmecher** [comment]
Moved the locale key to `pkp-lib` so it can be shared between OJS, OMP, and OPS. (It was previously in just OJS.)
