### ISSUE TITLE
OJS 3.3rc - cannot upload file into discussion

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#6608]
**Describe the bug**
When trying to upload a file into discussion at any stage, I cannot go past 2.Review details step. Pressing the "Continue" button does nothing. Observed from different roles - editor, assistant editor.

![image](https://user-images.githubusercontent.com/45104797/104672934-afe12c00-56ae-11eb-95c3-c59c9c9f0cfc.png)

**To Reproduce**
1. Go to the any stage of the workflow as an editor / copyeditor, etc.
2. Start a discussion
3. Upload a file to the discussion
4. In 2.Review details click "Continue"

**What application are you using?**
OJS 3.3rc

**Comment by asmecher** [comment]
@librariam, I couldn't replicate this problem locally; is this on the PKP test install? If so, could you (privately) send me the URL you're trying this on?

**Comment by librariam** [comment]
@asmecher hmm just retested again before sending you the link and now it's working.... Must have been an intermittent thing. Will close the issue now.

**Comment by asmecher** [comment]
OK, thanks! Please let me know if it shows up again...
