### ISSUE TITLE
When importing Apache logs: "issue/view/xxx/yyy" will yield "invalid issue" error and break import process

### ISSUE THREAD

**Issue by netsensei** [pkp/pkp-lib#6611]
**Describe the bug**

My apache log file contain this string:

```
192.168.1.2 - - [31/Dec/2019:00:10:00 +0100] "GET /foobarjournal/issue/view/646/15 HTTP/1.1" 200 850 "-" "user agent"
```

Trying to import the  log file will break execution of the `php /tools/runScheduledTasks.php /plugins/generic/usageStats/scheduledTasksExternalLogFiles.xml` command. The  `Usagestatisticsloadertask` log file contains this error:

```
[2021-01-14 17:02:27] [Error] Cannot load record: invalid issue id.
```

**To Reproduce**

1. Import an apache log file with lines matching the above URL
2. execute `php /tools/runScheduledTasks.php /plugins/generic/usageStats/scheduledTasksExternalLogFiles.xml`
3. Observe the `[Error] Cannot load record: invalid issue id.`  error message.

**What application are you using?**

OJS 3.1.2.1

**Additional information**

I've investigated the cause of the issue.

The URL `/foobarjournal/issue/view/646/15` contains two parameters: `issueId` and `galleyId`. So, this URL would request a specific galley of a specific journal issue.

The error is triggered in the `foreignKeyLookup` method of the `MetricsDAO` class. This method contains a switch based on the `assocType` of the entry:

```php
switch ($assocType) {
    case ASSOC_TYPE_ISSUE_GALLEY:
        $issueGalleyDao = DAORegistry::getDAO('IssueGalleyDAO');
        $issueGalley = $issueGalleyDao->getById($assocId);
        if (!$issueGalley) {
            throw new Exception('Cannot load record: invalid issue galley id.');
        }

        $assocObjType = ASSOC_TYPE_ISSUE;
        $assocObjId = $issueGalley->getIssueId();
        $isFile = true;
        // Don't break but go on to retrieve the issue.
    case ASSOC_TYPE_ISSUE:
        if (!$isFile) {
            $assocObjType = $assocObjId = null;
            $issueId = $assocId;
        } else {
            $issueId = $assocObjId;
        }

        $issueDao = DAORegistry::getDAO('IssueDAO');
        $issue = $issueDao->getById($issueId);

        if (!$issue) {
            throw new Exception('Cannot load record: invalid issue id.');
        }

        $contextId = $issue->getJournalId();
        break;
}
```

When importing an external logfile with the above URL, the `getExpectedPageAndOp` method in the `UsagesStatsLoader` class will match the `issue/view` op against the `ASSOC_TYPE_ISSUE` constant.  Further down the call stack, this willt rigger the second switch case in the `foreignKeyLookup`  look up. **this is incorrect**

The `$assocId` variable in the second switch case should be the `issueId`. However, the `galleyId` is passed instead. This id is matched against the `issues` table through the `getById` method.  Worst case scenario would be that the passed `galleyId` (in the example above: 15) matches with an `issueId` that's also 15. **this would imply that the metric saved with an incorrect `issueId` through the inserted through the `StatsDAO` object**

In my case, I happened to stumble on this issue as the passed `galleyId` - 15 - accidentally doesn't exist in the `issues` table. At some point in time, an `issue` was probably deleted, creating the potential for this bug to be tripped.

This problem only pops up when importing Apache logs.

The `PKPUsageEventPlugin` will yield log files that don't have the `galleyid` in the `issue/view` URLs. When an `UsageEvent` is triggered, the `PKPUsageEventPlugin` will deconstruct the entire request and artificially rebuild the URL before writing it to the `usage_event` log file.  In doing so, the `galleyId` will be omitted.

As a result, when feeding these files to the `UsageStatsLoader` class, they will be processed in working order by the above code.

Oddly enough, the definition of the various ops in `UsageStatsLoader::getExpectedPageAndOp()` does match the `issue/download` op with the `ASSOC_TYPE_ISSUE_GALLEY` constant. This would trigger the first switch case in the `foreignKeyLookup` method. So, URL's like `issue/download/646/15` - containing an `issueId` and a `galleyId` will be processed correctly.

**Comment by netsensei** [comment]
So, in `UsageStatsLoader`, the `getOJSAssoc` does this:

```php
case ASSOC_TYPE_ISSUE:
case ASSOC_TYPE_ISSUE_GALLEY:
    if (!isset($args[0])) break;
    $issueId = $args[0];
    $issueDao = DAORegistry::getDAO('IssueDAO');
    if (isset($this->_contextsByPath[current($contextPaths)])) {
        $context =  $this->_contextsByPath[current($contextPaths)];
        $issue = $issueDao->getById($issueId, $context->getId());
        if ($issue) {
            $assocId = $issue->getId();
        } else {
            break;
        }
    } else {
        break;
    }

    $assocTypeToReturn = $assocType;
    // Allows next case.
case ASSOC_TYPE_ISSUE_GALLEY:
    if (!isset($issue) || !isset($args[1])) break;
    $issueGalleyId = $args[1];
    $issueGalleyDao = DAORegistry::getDAO('IssueGalleyDAO');
    $issueGalley = $issueGalleyDao->getById($issueGalleyId, $issue->getId());
    if ($issueGalley) {
        $assocId = $issueGalley->getId();
    } else {
        // Make sure we clean up values from the above case.
        $assocId = $assocTypeToReturn = null;
    }
    break;
```

As a result, the first `ASSOC_TYPE_ISSUE` case - triggered by the URL in my apache logs - will fall through the and end up processing the subsequent `ASSOC_TYPE_ISSUE_GALLEY` case as well.  The original `assocId` which was first set with the correct `issueId` for `arg[0]` is going to get overwritten in the second case with the `galleyId` from `$issueGalley->getId()`.

A working solution would be to treat the `ASSOC_TYPE_ISSUE` in a distinct case:

```php
case ASSOC_TYPE_ISSUE:
    if (!isset($args[0])) break;
    $issueId = $args[0];
    $issueDao = DAORegistry::getDAO('IssueDAO');
    if (isset($this->_contextsByPath[current($contextPaths)])) {
        $context =  $this->_contextsByPath[current($contextPaths)];
        $issue = $issueDao->getById($issueId, $context->getId());
        if ($issue) {
            $assocId = $issue->getId();
        } else {
            break;
        }
    } else {
        break;
    }

    $assocTypeToReturn = $assocType;
    break;
case ASSOC_TYPE_ISSUE_GALLEY:
    if (!isset($args[0])) break;
    $issueId = $args[0];
    $issueDao = DAORegistry::getDAO('IssueDAO');
    if (isset($this->_contextsByPath[current($contextPaths)])) {
        $context =  $this->_contextsByPath[current($contextPaths)];
        $issue = $issueDao->getById($issueId, $context->getId());
        if ($issue) {
            $assocId = $issue->getId();
        } else {
            break;
        }
    } else {
        break;
    }

    $assocTypeToReturn = $assocType;
    // Allows next case.
case ASSOC_TYPE_ISSUE_GALLEY:
    if (!isset($issue) || !isset($args[1])) break;
    $issueGalleyId = $args[1];
    $issueGalleyDao = DAORegistry::getDAO('IssueGalleyDAO');
    $issueGalley = $issueGalleyDao->getById($issueGalleyId, $issue->getId());
    if ($issueGalley) {
        $assocId = $issueGalley->getId();
    } else {
        // Make sure we clean up values from the above case.
        $assocId = $assocTypeToReturn = null;
    }
    break;
```

Yes, it duplicates code. But I think that's par for the course without an architectural overhaul of how the different cases are handled.

I haven't touched the original cases and left them as-is. The main question here is whether the second case - which retrieves the actual `issueId` for `ASSOC_TYPE_ISSUE_GALLEY` is even relevant as that gets subsequently overwritten with a `galleyId` in the last case.

I've noticed that this issue still is present in the latest commit for `UsageStatsLoader`:
https://github.com/pkp/usageStats/blob/0f55cbc597779cf6dfe54918d2cfb9b63333ce53/UsageStatsLoader.inc.php

**Comment by asmecher** [comment]
@Vitaliy-1, can you have a look at this? (It's a lower priority than the issues currently assigned to you against 3.3.0-0.)

**Comment by bozana** [comment]
PR:
usageStats: https://github.com/pkp/usageStats/pull/54

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR above? It also solves the issue https://github.com/pkp/pkp-lib/issues/6573.

**Comment by asmecher** [comment]
My apologies for the delay! I don't know this aspect of the code well, but it makes sense to me. Please go ahead.
