### ISSUE TITLE
OMP 3.3 - Changing password after password reset can generate unstylized error page

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6613]
After requesting a password reset in OMP 3.3, you are required to change your password when you log in.  If you fail to enter the password twice in the new password/confirm password fields, the resulting error page with the form validation errors is unstylized.

![Screenshot from 2021-01-15 12-27-56](https://user-images.githubusercontent.com/218719/104753040-d7c3a480-572d-11eb-91a1-b4bf97fe589d.png)

Interestingly, even on that unstylized page, you can then proceed to submit the form correctly and you are redirected to the user's profile page with styling correctly displayed.

**Comment by NateWr** [comment]
I was not able to reproduce this. Here's what it is meant to look like.

![change-password](https://user-images.githubusercontent.com/2306629/104939222-0e0c5880-59a8-11eb-9d08-331fe6c135e5.png)

Your screenshot suggests to me that there is an error when rendering the Vue.js template or something. Can you try to:

1. Run `npm install && npm run dev` again from the root directory to make sure it is compiled.
2. Try again and check your console log for errors.
3. Share the OS/Browser you are using when you run into this issue.

**Comment by jnugent** [comment]
Hey @NateWr 

Same problem after rebuilding and redeploying.  This is in Firefox on Ubuntu.  Web console shows the following:

![Screenshot from 2021-01-18 12-24-55](https://user-images.githubusercontent.com/218719/104940697-7d725000-5988-11eb-9390-f2a283bab7e4.png)

And the original password change page is showing a 404 for the following request:

https://sfulib710.publicknowledgeproject.org/omp3/testing-3_3/lib/pkp/js/controllers/wizard/fileUpload/form/RevisionConfirmationHandler.js?v=3.3.0.1

I don't know if that's relevant since it pertains to file uploads but the file is not present in the lib/pkp file tree for the 3.3 OMP candidate.

**Comment by NateWr** [comment]
Can you click on savePassword:10 and show me the code there? I'm wondering what is calling `$` here. I suspect it might be a theme/plugin conflict where it is expecting to be loading a frontend-facing page but is actually loading a backend-facing page.

The `RevisionConfirmationHandler.js` was recently removed. Probably the `pkp.min.js` file has not yet been updated to reflect this and may need to be recompiled.

**Comment by jnugent** [comment]
That's this line:

`	<script src="https://sfulib710.publicknowledgeproject.org/omp3/testing-3_3/lib/pkp/lib/vendor/tinymce/tinymce/tinymce.js?v=3.3.0.1" type="text/javascript"></script><script type="text/javascript">$.pkp.plugins.generic = $.pkp.plugins.generic || {};$.pkp.plugins.generic.tinymceplugin = [];</script><script type="text/javascript">pkp.const = {"LISTBUILDER_SOURCE_TYPE_TEXT":0,"LISTBUILDER_SOURCE_TYPE_SELECT":1,"LISTBUILDER_OPTGROUP_LABEL":"optGroupLabel"};</script>
`

**Comment by NateWr** [comment]
Thanks @jnugent! I'm not sure why I wasn't encountering this error at first but the following should fix it.

PR:
https://github.com/pkp/pkp-lib/pull/6636

Tests:
https://github.com/pkp/ojs/pull/3004

**Comment by jnugent** [comment]
@NateWr confirming the fix on our test 3.3 OMP install. thanks!
