### ISSUE TITLE
OJS 3.3 - Unassigned reviewer still have access to an unaccepted reviewing task

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6614]
**Describe the bug**
When unassigning a reviewer, before they accept the task, they still have access to it via their dashboard, and can even submit Review.

**To Reproduce**
1. Go to 'Submission >  Review ' and assign a new reviewer
2. Before the reviewer accepts, unassign them from the task.
3. Log as the reviewer
4. See error (the submission on the dashboard, accessible the step 3 directly)

**What application are you using?**
 OJS version 3.S

**Additional information**

Reviewer test and reviewer 4 are assigned.
![image](https://user-images.githubusercontent.com/4992902/104772901-36931900-5742-11eb-9e30-cd22091c73d1.png)

**Reviewer 2** with access to the submission:
![image](https://user-images.githubusercontent.com/4992902/104773028-680be480-5742-11eb-8b3f-133c2027c814.png)

**Comment by asmecher** [comment]
Good spotting, thanks! The changes to `pkp-lib` added here will
1) remove cancelled reviews from the reviewer's list
2) prevent reviewer access to cancelled review assignments.
