### ISSUE TITLE
Submission files referencing nonexistent submissions break upgrade to 3.3

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6615]
If the database contains a reference from `submission_files` to `submissions` where  the submission doesn't exist...
```
SELECT sf.* FROM submission_files sf LEFT JOIN submissions s ON (sf.submission_id = s.submission_id) WHERE s.submission_id IS NULL;
```
...then the upgrade will break when adding foreign key constrants:
```
ERROR: Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (xyz, CONSTRAINT `publication_galleys_submission_file_id_foreign` FOREIGN KEY (`submission_file_id`) REFERENCES `submission_files` (submission_file_id)) (SQL: alter table `publication_galleys` add constraint `publication_galleys_submission_file_id_foreign` foreign key (`submission_file_id`) references `submission_files` (`submission_file_id`))
```
**What application are you using?**
OPS 3.3rc2

(Reported by SciELO)

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/6616
- https://github.com/pkp/ops/pull/110
- https://github.com/pkp/ojs/pull/2994
- (OMP is not affected)

**Comment by asmecher** [comment]
@NateWr, could you have a look at the above PRs? THey test OK for me and I'm pretty sure I got these right according to the `file_id` / `submission_file_id` discrepancy, but another look can't hurt.

**Comment by asmecher** [comment]
OPS pre-release testers can apply the proposed changes with these commands...
```
cd /path/to/ops
cd lib/pkp
wget -O - "https://github.com/asmecher/pkp-lib/commit/68f5fcbfcc9745b3ee051e1d2b2dd6260a6a1d7a.diff" | patch -p1
cd ../..
wget -O - "https://github.com/asmecher/ops/commit/b182107783cdd7ed8aaf3b40f87950ba87b6f874.diff" | patch -p1
```
...in other words, apply https://github.com/asmecher/ops/commit/b182107783cdd7ed8aaf3b40f87950ba87b6f874 in the OPS installation directory and https://github.com/asmecher/pkp-lib/commit/68f5fcbfcc9745b3ee051e1d2b2dd6260a6a1d7a in the `lib/pkp` subdirectory.

These should be applied before running the upgrade command. If an upgrade has already been attempted but failed, please restore the database from backup before trying again.

**Comment by Vitaliy-1** [comment]
Yes, it was these 2 places where my OJS instance also failed to upgrade. 
But I'm receiving 
```
ERROR: Upgrade failed: DB: SQLSTATE[HY000]: General error: 1093 You can't specify target table 'submission_files' for update in FROM clause (SQL: DELETE FROM submission_files WHERE submission_id IN (SELECT sf.submission_id FROM submission_files sf LEFT JOIN submissions s ON sf.submission_id = s.submission_id WHERE s.submission_id IS NULL))
```
mysql  Ver 14.14 Distrib 5.7.32, for Linux (x86_64)

**Comment by asmecher** [comment]
@Vitaliy-1, I've changed the implementation to avoid the `You can't specify target table` message, and send warnings to the log during upgrade about what content is removed. Can you take a look and test it again with the database that was causing trouble?

**Comment by Vitaliy-1** [comment]
@asmecher, I can confirm that these PRs to OJS and shared library have resolved the problem with the upgrade

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1! Merging and closing.
