### ISSUE TITLE
ORCID profile plugin needs version bump/release

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6617]
The currently released version of the ORCID plugin is 1.1.2-6, but the `master` branch version in github is 1.1.2-5. This will lead to a "downgrades not supported" message when trying to upgrade OJS/OMP/OPS with the current master branch ORCID profile plugin in place (e.g. using a git checkout, which has the plugin included as a submodule).

- [x] Verify that the plugin works with the `master` branch
- [x] Bump the version number in the `master` branch of the ORCID profile plugin (and build a compatible release)
- [ ] Update the submodules in the application repositories accordingly

**Comment by withanage** [comment]
Hi @asmecher ,

I released the orcidPfrofile Plugin  [1.1.2.8](https://github.com/pkp/orcidProfile/releases/tag/v1_1_2-8 ) in

**PR :**
https://github.com/pkp/plugin-gallery/pull/27

Current version supports:
- [x] OJS 3.3. support 
- [x] OPS 3.3. support 
- [x] Error handling Guzzle 
- [x] Member API publication update  


**Notes:**

CSL  plugin  does not support OPS  at the moment https://github.com/pkp/citationStyleLanguage/

I confirmed that with @ajnyga  and specifically disabled the addition of a bibtex citation for publishing with member-api for the OPS . e.g. in the [sandbox](https://sandbox.orcid.org/0000-0002-5308-4346)

**Comment by withanage** [comment]
Hi @asmecher ,

What would be the procedure for the submodule update ?

- [ ] Update the submodules in the application repositories accordingly

I have checked the git submodules https://github.com/pkp/ojs/blob/master/.gitmodules  or is it in another place.

**Comment by asmecher** [comment]
Thanks, @withanage!

**Comment by asmecher** [comment]
Please do commit a submodule update in the `master` branch corresponding to the version you just released. Like this:
```
cd /path/to/application
cd plugins/generic/orcidProfile
git checkout master
git pull
cd ../../..
git add plugins/generic/orcidProfile
git commit -m "Update orcidProfile plugin submodule"
git push
```

**Comment by withanage** [comment]
Thanks  @asmecher 

PRS for submodule update

- https://github.com/pkp/ojs/pull/3023
-  https://github.com/pkp/ops/pull/114

**Comment by asmecher** [comment]
All merged, thanks!
