### ISSUE TITLE
[UI] Untouched search templates

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#662]
There are four templates in `/search/` which haven't been touched and may not work. It wasn't clear to me what they do: `authorDetails.tpl`, `authorIndex.tpl`, `categories.tpl`, `category.tpl`.

Do these need to be up and running for 3.0b?

**Comment by asmecher** [comment]
authorIndex and authorDetails are part of a "browse by author" interface that used to be linked from the navigation sidebar block. It'll be necessary for OJS 3.0, but not necessarily OJS 3.0b.

The categories.tpl and category.tpl templates are part of a means to organize large collections of journals by subject; in OJS 2.4.x it's possible to enable an option permitting journal managers to assign entries in a controlled vocabulary to their journal (e.g. subjects); users can then browse by these. Not required for the beta, not sure if we'll address it the same way in 3.0.

**Comment by NateWr** [comment]
Ok, I'll assign this to the OJS 3.0 milestone then.

**Comment by asmecher** [comment]
All of these templates have been removed from the master branch (good), and the only critical one for 3.0 is the "Browse By Author" interface, which will be covered by https://github.com/pkp/pkp-lib/issues/381. Closing.
