### ISSUE TITLE
Issue with WebFeed plugin

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6620]
Discovered in 3.2.1-1 but also present in 3.3.

The  WebFeedGatewayPlugin calls the submission Service's getMany method but does not pass a 'status' parameter to restrict to STATUS_PUBLISHED.  

https://github.com/pkp/ojs/blob/stable-3_2_1/plugins/generic/webFeed/WebFeedGatewayPlugin.inc.php#L116

This causes the feed to include unpublished content.  PR incoming.

**Comment by asmecher** [comment]
Thanks, @jnugent! Back-ported to `stable-3_2_1`; OMP is not affected by the bug, and OPS doesn't have a web feed plugin yet.

**Comment by asmecher** [comment]
Users of OJS 3.2.x that encounter this issue can apply https://github.com/pkp/ojs/commit/3fcdf82866f1dc743bb2eeee47df5d17adb3033b to resolve it.
