### ISSUE TITLE
Remote galleys are broken

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6621]
**Describe the bug**
Galleys with remote URLs (instead of local files) are broken.

**To Reproduce**
1. Create a galley with a remote URL
2. Edit the galley
3. The page doesn't load

PHP error log:
```
PHP Fatal error:  Uncaught Error: Call to a member function getData() on null in xyz/controllers/grid/articleGalleys/form/ArticleGalleyForm.inc.php:70
Stack trace:
#0 xyz/controllers/grid/articleGalleys/ArticleGalleyGridHandler.inc.php(366): ArticleGalleyForm->fetch()
#1 xyz/lib/pkp/classes/core/PKPRouter.inc.php(391): ArticleGalleyGridHandler->editGalleyTab()
#2 xyz/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()
#3 xyz/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route()
#4 xyz/lib/pkp/classes/core/PKPApplication.inc.php(353): Dispatcher->dispatch()
#5 xyz/index.php(68): PKPApplication->execute()
#6 {main}
  thrown in xyz/controllers/grid/articleGalleys/form/ArticleGalleyForm.inc.php on line 70
```

**What application are you using?**
OPS 3.3rc2

**Comment by jnugent** [comment]
Hey @asmecher  there appears to be either this same bug or a similar one in 3.2.1.  If you create  a remote galley, the publications -> Galleys grid fails to load because the link action classes attempt to use a null submission file to build the link (getting the submission id, the label, etc).  Is that this same bug?  If so, is there a back port to stable-3_2_1 available? Thanks!

**Comment by asmecher** [comment]
@jnugent, do you have an error log entry for this?

**Comment by jnugent** [comment]
@asmecher sure:

```
PHP Fatal error:  Uncaught Error: 
Call to a member function getFileId() on null in www/lib/pkp/controllers/api/file/linkAction/FileLinkAction.inc.php:46
Stack trace:
#0 www/lib/pkp/controllers/api/file/linkAction/DownloadFileLinkAction.inc.php(37): FileLinkAction->getActionArgs(NULL, 5)
#1 www/controllers/grid/articleGalleys/ArticleGalleyGridCellProvider.inc.php(90): DownloadFileLinkAction->__construct(Object(Request), NULL, 5, 'PDF')
#2 lib/pkp/classes/controllers/grid/GridCellProvider.inc.php(56): ArticleGalleyGridCellProvider->getCellActions(Object(Request), Object(ArticleGalleyGridRow), Object(GridColumn))
#3 lib/pkp/classes/controllers/grid/GridHandler.inc.php(1104): GridCellProvider->render(Object(Request), Object(ArticleGall
eyGridRow), Object(GridColumn))'
```

In this particular submission, one of the galleys is a PDF and one is a Remote Galley with a link to a dropbox file.  The Remote Galley has a null file_id which means that the FileLinkAction calls null on what it's expecting is a submission file object.

**Comment by jnugent** [comment]
These are the two entries in publication_galleys for this submission.

![Screenshot from 2021-02-24 17-24-10](https://user-images.githubusercontent.com/218719/109067694-38e37e00-76c5-11eb-92fc-0cfde84aa904.png)

**Comment by asmecher** [comment]
The line of code https://github.com/pkp/ojs/blob/stable-3_2_1/controllers/grid/articleGalleys/ArticleGalleyGridCellProvider.inc.php#L80 prevents the error you list above from happening in the case of a remote galley. I think the problem is actually the other entry (`file_id=59607`); make sure that entry exists in `submission_files`.

**Comment by jnugent** [comment]
Yes, the file is there and is downloadable.  They've now published this article. And yes, I have that line of code you referenced.

**Comment by asmecher** [comment]
OK, but note that it's `PDF` that's referenced in the log, not `Video Abstract`. Is this error still happening, or did it get resolved some other way?

**Comment by jnugent** [comment]
I resolved it by adding some checks for a valid submission file in a few places in the LinkAction code.
