### ISSUE TITLE
Allow users to unsubscribe from emails sent using the notify tool

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6627]
**Describe the problem you would like to solve**
The new notify feature which lets managers send an email to all users in a role may be abused to send unsolicited email or email that does not meet privacy requirements in all jurisdictions. At the very least, users must be able to unsubscribe from these emails.

**Describe the solution you'd like**
After some [discussion](https://github.com/pkp/pkp-lib/issues/6536), we think it would be best to offer users the ability to unsubscribe by their assigned user groups. The opt-out can describe the emails using terminology like "Occasional emails sent to {$userGroup}".

Not all user groups should be able to opt out, though, because some user groups (like section editors or copyeditors) could be reasonably required to receive email in order to fulfil their role. The behaviour for each role should be:

- Author and Reader user groups will receive an opt-out in the notification settings. They should also receive an unsubscribe link at the bottom of the email.
- Reviewer user groups will not have an opt-out, but emails sent to them will have a footer that tells them how to be removed as a reviewer in order to unsubscribe: "This email was sent to all Reviewers. If you do not want to receive emails as a reviewer, please [contact the journal](#) and ask to be removed as a reviewer."
- Assistants/Editors will not have an opt-out, but emails sent to them will have a footer explaining why these emails are necessary (ie - non-optional parts of the role).

An attempt was made to implement this for 3.3, but the current structure of the notification subscription settings can not accommodate an opt-out for each user group. The notification subscription settings will need to be refactored in order to implement this. The refactor should probably incorporate the unsubscribe work undertaken as part of https://github.com/pkp/pkp-lib/issues/5048.

A further complication is that the way that the notify emails are scheduled means that a single user might be included in the email in more than one role. An attempt will need to be made to ascertain why an email is being sent to a particular user (ie - which role(s) caused them to be included in this email). The user should be sent the email as long as they have one role that is not opted out.

**Who is asking for this feature?**
This is a requirement for GDPR and to limit the problems arising from [abuse of the notify feature](https://github.com/pkp/pkp-lib/issues/6536).

**Comment by mfelczak** [comment]
Hello @asmecher, this will likely require review in light of upcoming mail policy changes at Gmail (February, 2024) and Yahoo ("Early 2024").

The most relevant new requirement for our user community is that both providers will require a one-click unsubscribe, which should be clearly visible in the body of the email and the list-unsubscribe header.

An email sender who does not implement Gmail and Yahoo’s new requirements may see a potential impact in its email performance on either platform, including increases in bounce rates that result in delayed or non-delivery of emails, or emails being sent to the designated bulk folder.

**Comment by mfelczak** [comment]
The above requirements may also apply to other bulk mail features, e.g. new announcement email notification, issue published notification.

**Comment by asmecher** [comment]
It looks like the relevant policies are here:
- gmail: https://blog.google/products/gmail/gmail-security-authentication-spam-protection/
- yahoo: https://blog.postmaster.yahooinc.com/post/730172167494483968/more-secure-less-spam

@Vitaliy-1, could you have a look over these and see what we'd need to cover?

**Comment by Vitaliy-1** [comment]
Gmail expects additional header: 
```
List-Unsubscribe-Post: List-Unsubscribe=One-Click
List-Unsubscribe: <https://solarmora.com/unsubscribe/example>
```
Which is quite easy to implement for the main and 3.4 with a few lines of code. However, 3.3 doesn't have new mailing system and it might be burdensome.

**Comment by Vitaliy-1** [comment]
PRs
**main**
pkp-lib: https://github.com/pkp/pkp-lib/pull/9757
tests: https://github.com/pkp/ojs/pull/4198

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1! What are the implications for 3.3.0? Do we expect users will suddenly have difficulties delivering emails with the new policies in place?

I'm planning to release a new build of 3.4.0 tomorrow; the `main` contribution looks good at a glance, so thumbs up for back-porting it for inclusion.

**Comment by Vitaliy-1** [comment]
> Do we expect users will suddenly have difficulties delivering emails with the new policies in place?

That requirement is already in place but I haven't seen any issues/report yet. I think it may cause emails of journals with a big user base ending up in a spam folder, when sending bulk email like, e.g., new issue published notification. Maybe not immediately.

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1! It looks like this is now merged into `stable-3_4_0`, correct? I've moved it to the 3.4.0-5 milestone. Is anything else needing to be done on this issue?

**Comment by Vitaliy-1** [comment]
Yes, the part related to new gmail and yahoo policies for bulk email is merged. But the issue describes a broader problem that hasn't been solved

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1! I'll close this issue against 3.4.0-5 for the sake of change tracking, but can you file a new issue documenting the rest of the work that needs doing?
