### ISSUE TITLE
 None of the links on the For Readers, For Authors and For Librarians pages seem to work.

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#663]

**Comment by asmecher** [comment]
- Renamed the about/about page back to about/index (trusting you don't mind, @NateWr; this makes /about sufficient for the index page)
- Re-added IDs so anchors can jump to the relevant section

The contents of those sections are just defaults and can be tweaked in setup after journal creation; they may refer to sections of About that won't exist, if no content is specified for them in Setup.

**Comment by NateWr** [comment]
Looks good. :+1:
