### ISSUE TITLE
Entering a space in journal path breaks site

### ISSUE THREAD

**Issue by benaltair** [pkp/pkp-lib#6633]
**Describe the bug**
When experimenting with how to simplify the URL aesthetically, I decided to enter a space character as the path. Specifically, I changed it from "online" to " ". When I saved this, it broke everything. I could no longer access the front end website, and I couldn't save anything else as the path to fix it. To fix it, I had to enter the SQL database and revert the change manually. Once the database was changed directly, everything worked again right away.

**To Reproduce**
1. Go to **Administration** > **Journals**
2. Expand a journal in the list and click **Edit**
3. Scroll down to the **Path** field
4. Replace all the contents with a single space character " "
![image](https://user-images.githubusercontent.com/17771229/105123833-a7fa0100-5a8d-11eb-8744-94ea04ade644.png)
5. Click save
6. Watch chaos ensue

**What application are you using?**
 OJS version 3.2.1.2

**Additional information**
The front end rendering of the site tries to escape the space character like any URL - maybe that's the issue? I'm not sure what's causing it, or if spaces in other parts of the field would cause the same issue. It seems like this should not allow saving such an entry - perhaps no spaces at all?

**Comment by jmvezic** [comment]
Space is considered unsafe in URLs, so there should be a regex validation there. Or, there should be urlencode before storing it in the database.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/6678

Tests:
https://github.com/pkp/ojs/pull/3020
https://github.com/pkp/omp/pull/919
