### ISSUE TITLE
Block names aren't being updated to the lowercase during OJS upgrade

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6634]
**Describe the bug**
Upgrade from OJS 3.2.1 to 3.3 (recent master branch) doesn't update block names to the lowercase, as per phpdoc here: https://github.com/pkp/pkp-lib/blob/master/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php#L540-L549
Instead, I'm receiving a warnings: 
```
PHP Warning:  Invalid argument supplied for foreach() in /home/doc/OJS/development/ojs/lib/pkp/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php on line 558
PHP Warning:  Invalid argument supplied for foreach() in /home/doc/OJS/development/ojs/lib/pkp/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php on line 599
```

**To Reproduce**
1. Upgrade an OJS instance with custom blocks
2. See warning and correspondent entries in the database

**Additional information**
This upgrade script tries to unserialize `setting_value` as JSON, while at the time it's executed the `setting_value` is still stored as php serializered array.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib master: https://github.com/pkp/pkp-lib/pull/6657
tests OJS master: https://github.com/pkp/ojs/pull/3005

**Comment by Vitaliy-1** [comment]
@NateWr, do you have time to review the PR? Looks straightforward to me, later in the update script setting values should be transformed to JSON representation.

**Comment by NateWr** [comment]
Looks good to me. Where are the values transformed to JSON?

**Comment by Vitaliy-1** [comment]
For OJS it's here: https://github.com/pkp/ojs/blob/dc22ed3f2996841b061dbae80efdeebe0fe56a2c/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php#L37

**Comment by NateWr** [comment]
Thanks @Vitaliy-1!
