### ISSUE TITLE
The fileStages filter of the submission files API is ignored for managers

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6638]
**Describe the bug**
The `fileStages` filter has no effect when accessing the API `/submissions/{id}/files` with a manager role, all files are retrieved.

**What application are you using?**
OJS 3.3

**Comment by NateWr** [comment]
Thanks @jonasraoni!

PR:
https://github.com/pkp/pkp-lib/pull/6658

Tests:
https://github.com/pkp/ojs/pull/3006
