### ISSUE TITLE
Can't edit or overwrite issue galley file

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#664]
1. Dashboard > Issues > Edit Issue > Issue Galleys > Edit
2. Upload an image. Then Save.
3. Then go and try to change the image.

It seems to upload, but when clicking the save button, the file doesn't change. A fatal error appears in my Apache error log:

```
[Fri Aug 07 16:03:57.111911 2015] [:error] [pid 14131] [client 192.168.0.8:54975] PHP Fatal error:  Call to undefined method IssueFile::getFileName() in /var/www/html/ojs/classes/file/IssueFileManager.inc.php on line 87, referer: http://192.168.0.8/ojs/index.php/publicknowledge/dashboard
```

**Comment by asmecher** [comment]
Fixed -- good spotting.
