### ISSUE TITLE
Unable to update/delete files that the author had access using the API

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6640]
**Describe the bug**
*Probably it's just a misunderstanding/typo in the test description.*
I could update/delete files created by the author. But I couldn't do it with the other files the author had access.

**To Reproduce**
Using the author role, try to update/delete a file the author has access, and that wasn't uploaded by him, using the API `/submissions/{id}/files/{file_id}`.

**What application are you using?**
OJS 3.3

**Comment by NateWr** [comment]
The author only has read access to some of the files. Can you check the table at the [bottom of this page](https://docs.pkp.sfu.ca/dev/documentation/en/submission-files#file-access) to see if it corresponds with the ability to delete from the API that you found?
