### ISSUE TITLE
Escaped HTML content in a notification

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6649]
**Describe the bug**
The notification has escaped HTML content:

![error](https://user-images.githubusercontent.com/361921/105314878-8bfe7880-5bcf-11eb-8b28-1fb9cc5a7698.PNG)

**To Reproduce**
Try to insert an user with an existing username.

**What application are you using?**
OJS 3.3

**Comment by NateWr** [comment]
Duplicate of https://github.com/pkp/pkp-lib/issues/6449
