### ISSUE TITLE
[OJS 3.3] Include journal sidebar after creating a new journal

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6650]
**Describe the problem you would like to solve**
After creating a new journal, I think it would be more user friendly to already redirect to it, so the sidebar would be displayed here:

![image](https://user-images.githubusercontent.com/361921/105315339-31b1e780-5bd0-11eb-8267-e471b43193b8.png)

**Describe the solution you'd like**
Redirect to the journal page or maybe add a button "Go to Journal Administration".

**Comment by NateWr** [comment]
I think we'll keep this as-is. The person creating the journal is often different from the person managing the journal. The settings wizard presents the most common settings an admin needs after they have created a journal, including at least one setting that is not available in the general journal settings area.
