### ISSUE TITLE
Visual glitch that appears sometimes while navigating

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6652]
**Describe the bug**
Sometimes after navigating, a `ui-datepicker-div` appears in the bottom:

```html
<div id="ui-datepicker-div" class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all"></div>
```

![datepicker](https://user-images.githubusercontent.com/361921/105315763-e1875500-5bd0-11eb-8608-6a26744f47d2.PNG)

**Fix**
As its an old component which will be replaced sooner or later, I suggest to just add a
```css
#ui-datepicker-div:empty { display: none }
```

**To Reproduce**
1. Access a back issue
2. Click on the `Edit` link
3. Proceed to the tab `Issue Data`

**What application are you using?**
OJS 3.3
OJS /main

**PRs**
- https://github.com/pkp/pkp-lib/pull/7667
- https://github.com/pkp/pkp-lib/pull/7668

**Comment by NateWr** [comment]
Is this the QuickSubmit plugin? I think that's the only place the old datepicker is still used.

**Comment by jonasraoni** [comment]
I didn't install/enable anything... I was just navigating and saw it, I thought it was a video card glitch, but devtools showed me the empty div with this class o_O
