### ISSUE TITLE
The cancel button at the "Change Password" has no purpose

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6654]
**Describe the bug**
Once an user lands at the forced "Change Password" interface, there's a `Cancel` button, which does nothing.

It should probably redirect the user back to the login interface.

**To Reproduce**
Create an user and mark the option to force him to change his password on the first login

**What application are you using?**
OJS 3.3

**Comment by NateWr** [comment]
Thanks! Fixed in https://github.com/pkp/pkp-lib/commit/e141d7fb8fdf6ecdd5d061a7126343a47fd54be7.
