### ISSUE TITLE
Swagger generator creates invalid content

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6655]
**Describe the bug**
When opening the swagger.json file generated by the tool in the [online editor](https://editor.swagger.io), it accuses some invalid escapes (`\/`) and warnings.

**To Reproduce**
Generate a swagger file
```bash
php lib/pkp/tools/buildSwagger.php swagger.json
```

Open it in the [online editor](https://editor.swagger.io)

**What application are you using?**
OJS 3.3

**Comment by NateWr** [comment]
We're no longer using the Swagger editor. We've switched to redoc and added a couple of vendor-specific tags supported by redoc.  See https://github.com/pkp/pkp-docs#generate-rest-api-references
