### ISSUE TITLE
Can't delete role from user

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#666]
Settings > Users > Edit User > Roles.

1. To the left of the role there should be a delete button which is not appearing. Needs some CSS work to attach a delete icon.

2. Even with content attached, clicking on the delete button doesn't seem to delete role from the user.

**Comment by asmecher** [comment]
See also https://github.com/pkp/pkp-lib/issues/654

**Comment by NateWr** [comment]
The commit above adds the icon, but clicking it still does nothing.

**Comment by asmecher** [comment]
Fixed.
