### ISSUE TITLE
OJS 3.3rc - HTML galley does not pick up the dependent CSS

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#6663]
**Describe the bug**
All galley tests on 3.3rc have passed except for HTML + CSS. The HTML is displayed fine, but does not pick up the dependent CSS. It does pick up other dependent files, like images.

The same HTML + CSS pair of files was tested on 3.1.2 and is picked up as it should.

**To Reproduce**
1. Go to a submission in production stage on 3.3rc
2. Upload an HTML galley that references a CSS
3. Upload the referenced CSS as a dependent file
4. See the HTML displayed without the CSS changes

**What application are you using?**
 OJS 3.3rc, testing site

**Additional information**
Galley tests were done based on Nate's scenarios and acceptance criteria. Israel tested this one as well, to confirm my sanity.

**Comment by Vitaliy-1** [comment]
I can confirm that the `mimetype` of the CSS file attached to the galley is identified as `text/plain` instead of `text/css`

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib master: https://github.com/pkp/pkp-lib/pull/6666
tests OJS master: https://github.com/pkp/ojs/pull/3013

**Comment by Vitaliy-1** [comment]
What is happening here is that original Flysystem's  `Filesystem::getMimetype()` method [uses finfo](https://github.com/thephpleague/flysystem/blob/1.x/src/Adapter/Local.php#L323), which I  suppose has problems identifying the MIME type of a file without any internal pointers; at least it's relevant for CSS and JS, according to my tests. The new mime type detector class allows falling back to the file extension.

**Comment by asmecher** [comment]
@Vitaliy-1, I'm hoping to release 3.3.0 on Monday, so please see if you can resolve this soon, thanks!

**Comment by Vitaliy-1** [comment]
I've updated PR, tests are in progress

**Comment by NateWr** [comment]
Thanks @Vitaliy-1, all merged!

**Comment by Vitaliy-1** [comment]
Not resolved completely, although mimetype is identified and recorded in the database correctly, CSS is still recognized by the browser as `text/plain`. See related forum thread: https://forum.pkp.sfu.ca/t/issue-with-dependent-css-in-the-html-galley-in-ojs-3-3-0-3-and-3-3-0-2/65768 (able to reproduce)

**Comment by Vitaliy-1** [comment]
Yep, another place where the mimetype detection relies just on Flysystem's tool. I can simply implement a similar workaround. @NateWr, I'm wondering why we can't rely on the mimetype recorded in the database here if it's available? E.g., pass `fileId` as an optional parameter to the `download` operation.

**Comment by NateWr** [comment]
@Vitaliy-1 yes, good find, please use the mimetype in the database. Just forgot to change this over. The only time we should use Flysystem's mimetype check is when storing the file into the database.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib main: https://github.com/pkp/pkp-lib/pull/6786
OJS main: https://github.com/pkp/ojs/pull/3050
OMP main: https://github.com/pkp/omp/pull/934
OPS main: https://github.com/pkp/ops/pull/124

**Comment by NateWr** [comment]
Thanks @Vitaliy-1, this looks good. In order to be extra careful with the stable branch, when you port it to `stable-3_3_0`, can you make the download method except a string (path) or int (fileId)? So if the first argument is a string, treat it like a path and leave the code as-is. That will hopefully prevent any bugs from third-party code which may already be using this method in 3.3.0.

**Comment by Vitaliy-1** [comment]
PRs to stable-3_3_0:
pkp-lib: https://github.com/pkp/pkp-lib/pull/6790
OJS: https://github.com/pkp/ojs/pull/3052
OMP: https://github.com/pkp/omp/pull/936
OPS: https://github.com/pkp/ops/pull/126

@NateWr, did you mean something like this?

**Comment by NateWr** [comment]
Yep, thanks. Just a couple comments but looks good.

**Comment by jnugent** [comment]
Hi everyone, this bug may have reappeared.  We have a client on 3.3.0.7, upgraded from 3.2, and now uploaded CSS files for HTML galleys are getting a "text/plain" MIME type stored in the files table:

![Screenshot at 2021-09-27 12-02-17](https://user-images.githubusercontent.com/218719/134934558-45fa1e45-e462-474e-9ce4-c7f23b24b775.png)

This file was correctly uploading as text/css in 3.2 and has not changed. Further, after doing some debugging it doesn't look like any of the ambiguity code for MIME type detection added in PKPString is being used when files are uploading.  My debug statements in that class are not being logged.

I'm attaching a zip file containing the style sheet that used to work but now does not.  I've confirmed this in my own 3.3.0.7 test installation. It's easy to reproduce, just create a new submission and upload this as a submission file and look at the files table.

I'll leave the reopening to others if it is deemed necessary.

[stylesheet.zip](https://github.com/Vitaliy-1/pkp-lib/files/7237357/stylesheet.zip)

**Comment by NateWr** [comment]
I've filed this separately at https://github.com/pkp/pkp-lib/issues/7344 and I'll close this. That way we can keep this issue as a record of work committed to the 3.3.0-4 milestone and any additional work will get flagged to that milestone.
