### ISSUE TITLE
Error An unexpected error occurred. You may have been logged out. Please reload the page and try again when create journal

### ISSUE THREAD

**Issue by muhammadhamdani** [pkp/pkp-lib#6667]
**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

**To Reproduce**
after Upgrade from 3.2.0.3
1. Go to menus administration
2. Click on Hosted Journal
3. Click on Create Journal
4. Fill out the Form
3. Klik Save

**What application are you using?**
I Using OJS 3.2.1.2

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

![WhatsApp Image 2021-01-24 at 7 49 32 PM](https://user-images.githubusercontent.com/12347039/105630952-6a76e880-5e7e-11eb-8edd-e0a184a5d9f2.jpeg)

**Comment by asmecher** [comment]
@muhammadhamdani, could you post your question on our support forum at https://forum.pkp.sfu.ca? That's the best place to get help.
