### ISSUE TITLE
Submission metadata that uses tag-it component isn't saved

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#667]
This includes Languages, Subjects, Discipline(s), Keywords, Supporting Agencies.

Improvements to the tag-it component styles exist in [this PR](https://github.com/pkp/pkp-lib/pull/646), but don't address the problem with saving. See [this comment](https://github.com/pkp/pkp-lib/pull/646#issuecomment-128343057).

**Comment by asmecher** [comment]
Fixed. This was probably caused by a change of behavior in the tag-it library.
