### ISSUE TITLE
Error Create Journal

### ISSUE THREAD

**Issue by muhammadhamdani** [pkp/pkp-lib#6670]
**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

**To Reproduce**
1. Go to menu administration
2. Click on Hosted Journal
3. Click on Create Journal
4. Fill Out The Form
3. Click on Save

**What application are you using?**
 OJS version 3.2.1.3

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
![image](https://user-images.githubusercontent.com/12347039/105778071-2b3fb900-5f9e-11eb-94fb-ebfa23e52188.png)

**Comment by asmecher** [comment]
@muhammadhamdani, see https://github.com/pkp/pkp-lib/issues/6667#issuecomment-766402671.
