### ISSUE TITLE
no router object when executing scheduled tasks

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6671]
**Describe the bug**
when executing a scheduled task via cli i.e. not using web interface (e.g. as a cron job) that uses guzzle http client (e.g. medra, datacite, crossref, doaj) the following error occur:
Error: Call to a member function getContext() on null
/home/bozana/pkp/ojs-master/lib/pkp/classes/core/PKPApplication.inc.php:422
/home/bozana/pkp/ojs-master/lib/pkp/classes/core/PKPApplication.inc.php:460
/home/bozana/pkp/ojs-master/lib/pkp/classes/core/PKPApplication.inc.php:296

**To Reproduce**
e.g.  php tools/runScheduledTasks.php plugins/importexport/datacite/scheduledTasks.xml

**What application are you using?**
 OJS, OMP or OPS version 3.3 master branch 

**Additional information**

**Comment by bozana** [comment]
PR:
pkp-lib: https://github.com/pkp/pkp-lib/pull/6672

**Comment by bozana** [comment]
@asmecher, I've tested it with medra and datacite scheduled tasks and it worked, so I merged. OK so?

**Comment by asmecher** [comment]
Yes, and looks like it's already merged, so please go ahead and close this if you're ready!
