### ISSUE TITLE
Add autocomplete attributes to password fields

### ISSUE THREAD

**Issue by benaltair** [pkp/pkp-lib#6676]
I would like to suggest that proper autocomplete attribute tags be added to the password fields of sign-in and registration forms in OJS. Chromium now provides the following warning in the console when visiting an OJS journal:
```
[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) 
<input type=​"password" class=​"form-control" name=​"password" id=​"passwordModal" value maxlength=​"32" required>​
```
This is an extension of the accessibility work done on https://github.com/pkp/pkp-lib/issues/5185

Specifically, all password fields should either:
- Use `autocomplete="new-password"` for the password input in a sign-up form or reset-password form.
- Use `autocomplete="current-password"` for a sign-in password inputs.

For example:
```
<input type=​"password" class=​"form-control" name=​"password" id=​"passwordModal" value maxlength=​"32" required autocomplete="current-password">​
```
This would apply to all password fields in the sign-in / registration forms. I'm not familiar enough with the platform yet to submit find all the relevant template files, but I'd be happy to submit a PR if someone could point me to the right files. It seems one example of a file this would apply to is `templates/frontend/components/registrationForm.tpl`

**Comment by benaltair** [comment]
Created PR https://github.com/pkp/healthSciences/pull/206

**Comment by benaltair** [comment]
I made a PR for [healthSciences](https://github.com/pkp/healthSciences) -- is there another place for the main theme where this should be done? Couldn't see it in any repo.

**Comment by asmecher** [comment]
@benaltair, thanks! The built-in templates are in the OJS repository, and you can find them e.g. for the `master` and `stable-3_3_0` branches:
- `lib/pkp/templates/frontend/pages/userLogin.tpl`
- `lib/pkp/templates/frontend/components/registrationForm.tpl`

(I'm guessing these ones might have been tricky to find because they're hidden in the `lib/pkp` submodule; this is done because these parts of the system are shared between OJS, OMP, and OPS.)

**Comment by benaltair** [comment]
Are there any other PRs needed on my part for this?

**Comment by asmecher** [comment]
I've just added a reminder to that PR, but no, I don't think anything else is required.

**Comment by asmecher** [comment]
Thanks, the other PR has now been merged, so I'll close this one.
