### ISSUE TITLE
Fatal error with googleScholar plugin when previewing article

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6679]
**Describe the bug**
When previewing an unpublished article I receive a fatal error from the Google Scholar plugin. I am logged in as a manager.

**To Reproduce**
1. Find an unpublished submission (ex - in Production stage)
2. Open workflow page
3. Click preview

**What application are you using?**
3.3 RC2

**Additional information**
The error:
```
27-Jan-2021 12:22:06 Europe/London] PHP Fatal error:  Uncaught Error: Call to a member function getYear() on null in /home/nate/Projects/pkp/ojs/plugins/generic/googleScholar/GoogleScholarPlugin.inc.php:102
Stack trace:
#0 /home/nate/Projects/pkp/ojs/lib/pkp/classes/plugins/HookRegistry.inc.php(107): GoogleScholarPlugin->submissionView('ArticleHandler:...', Array)
#1 /home/nate/Projects/pkp/ojs/pages/article/ArticleHandler.inc.php(300): HookRegistry::call('ArticleHandler:...', Array)
#2 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPRouter.inc.php(395): ArticleHandler->view(Array, Object(Request))
#3 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#4 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route(Object(Request))
#5 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPApplication.inc.php(364): Dispatcher->dispatch(Object(Request))
#6 /home/nate/Projects/pkp/ojs/index.php(68): PKPApplication->execute( in /home/nate/Projects/pkp/ojs/plugins/generic/googleScholar/GoogleScholarPlugin.inc.php on line 102
```

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/googleScholar/pull/5

Tests:
https://github.com/pkp/ojs/pull/3021

@amandastevens and @librariam, this probably indicates something to add to the testing list for future rounds: the feature to preview unpublished submissions. Often if data is missing (in this case, an issue assignment) it can cause problems on the article landing page (or galleys). It may also be worth documenting what plugins need to be activated and set up for a testing instance.

**Comment by amandastevens** [comment]
@NateWr , we have "Preview an issue" on the list of tests already, with "Issue can be previewed" as the intended result. Is there anything further that should be added?

**Comment by NateWr** [comment]
Often a fatal error will lead to either a white screen or an "unfinished page" (ie - you can see the article title and some content, but maybe you notice that the sidebar or footer is gone). In addition, I can think of the following things to check:

- The how-to-cite plugin either shows the correct thing or doesn't appear
- Anything like DOIs, a published date, or an issue assignment that may not be available when previewing. Make sure these are not saved in the publication and then try to preview.

**Comment by amandastevens** [comment]
I added a note about this in the Preview Issue test, but we may want to break this into a few different tests next time.
