### ISSUE TITLE
OPS should support tombstones for deleted content

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6685]
**Describe the problem you would like to solve**
The OAI feed provides data about published items. When a published item is later removed from publication, a tombstone appears in the feed identifying the item that was removed. This works for OJS, which lists articles, and OMP, which lists publication formats. But OPS does not support tombstones in its OAI feed.

**Describe the solution you'd like**
OPS should add tombstones when a preprint that was posted is no longer available.

**Who is asking for this feature?**
It is necessary to comply with the spec for OAI feeds.

**Comment by ajnyga** [comment]
Running tests: https://github.com/pkp/ops/pull/170

While debugging my code I noticed that both OJS and OPS have a table called `submission_tombstones`. It does not seem to be used anymore? I can not find any code interacting with that table. @asmecher?

**Comment by asmecher** [comment]
@ajnyga, good spotting -- that's dead code. The `data_object_tombstones` table is the working form of the tombstone implementation. If you're working with that code, please feel free to remove it; if not, let me know and I'll take care of it.

**Comment by asmecher** [comment]
Thanks, @ajnyga, I've merged the PR (https://github.com/pkp/ops/pull/170). About the `submission_tombstones` clean-up -- do you have plans to remove that, or shall I?

**Comment by ajnyga** [comment]
Is this enough https://github.com/pkp/pkp-lib/pull/7237

**Comment by asmecher** [comment]
That's good -- but I think you'll also need to remove references to `submission_tombstones` from `classes/migration/OPSMigration.inc.php` and `classes/migration/upgrade/v3_4_0/I6759_RenameVariables.inc.php` in the OPS repo. (And equivalent for OJS and OMP -- I'm happy to do any of this you'd rather leave.)

**Comment by ajnyga** [comment]
@asmecher 
OPS: https://github.com/pkp/ops/pull/177
OJS: https://github.com/pkp/ojs/pull/3179
OMP did not have it.

**Comment by asmecher** [comment]
All merged -- thanks, @ajnyga!
