### ISSUE TITLE
 Problem upgrade release candidate ojs-3.3.0rc2

### ISSUE THREAD

**Issue by elton557** [pkp/pkp-lib#6698]
When I upgrade to the candidate release, I get the following error

PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: '' in /var/www/submission_scielo_br/htdocs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 /var/www/submission_scielo_br/htdocs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare('set names '' co...', Array)
#1 /var/www/submission_scielo_br/htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(76): Doctrine\DBAL\Driver\PDOConnection->prepare('set names '' co...')
#2 /var/www/submission_scielo_br/htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(32): Illuminate\Database\Connectors\MySqlConnector->configureEncoding(Object(Doctrine\DBAL\Driver\PDOConnection), Array)
#3 /var/www/submission_scielo_br/htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\Database\Connectors in /var/www/submission_scielo_br/htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671

Upgrade version: ojs-3.3.0rc2

thank you

**Comment by asmecher** [comment]
@elton557, what is `connection_charset` set to in your `config.inc.php`?

**Comment by elton557** [comment]
hello, we never touched it, but it looks like this:
; Database connection character set
; Must be set to "Off" if not supported by the database server
; If enabled, must be the same character set as "client_charset"
; (although the actual name may differ slightly depending on the server)
connection_charset = Off

; Database storage character set
; Must be set to "Off" if not supported by the database server
database_charset = Off


Should we change?

**Comment by asmecher** [comment]
The recommended settings are:
```
; Client output/input character set
client_charset = utf-8

; Database connection character set
; Must be set to "Off" if not supported by the database server
; If enabled, must be the same character set as "client_charset"
; (although the actual name may differ slightly depending on the server)
connection_charset = utf8
```
However, if you've been using the system with both set to `Off`, double-check that any special (accented) characters show up as you expect when using these settings. If not, you may need to transcode your database to UTF-8 before they will work. This can be a pain but it's well worth the work -- good UTF-8 support is pretty much universal, both server side and client side.

**Comment by NateWr** [comment]
I'll close this and assume the suggested fix has solved the problem.
