### ISSUE TITLE
Upgrade OJS 3.1.2 -> 3.2.1-3 error; no backup

### ISSUE THREAD

**Issue by Geeermy** [pkp/pkp-lib#6701]
Hi! I know this has been asked before, if there is an existing issue that describes exactly this problem please, share it with me. If that's not the case, please, help me out!

After finishing with the configuration details for the upgrade from 3.1.2 to 3.2.1, I clicked the upgrade button before doing a backup of the database (my mistake). Afterwards, the page showed this error:

```
Unknown column 'et.assoc_type' in 'on clause'
```

I tried to run the upgrade again, and the error changed to:

```
Duplicate column name 'email_id'
```

Which I think happens because the database is in a state between versions 3.1.2 and 3.2.1. So, knowing that I cannot use a backup to restore my database to its initial state (as I didn't make one), is there any way I can solve this? Maybe running the missing migrations manually? Any info is greatly appreciated!

Thanks in advance!

**Comment by asmecher** [comment]
@Geeermy, I would suggest following up on one of the existing threads on this in our support forum (https://forum.pkp.sfu.ca/t/ojs-3-1-2-0-to-3-2-upgrade-error-duplicate-column-name-email-id/59174). The forum is probably a better place for this kind of discussion -- if it results in a bug fix or code change, we'll re-migrate that aspect of it here. Thanks!

**Comment by Geeermy** [comment]
Perfect! Thank you! 😄
