### ISSUE TITLE
Upgrade to 3.3.0.2 fails when a journal has no supportedFormLocales

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6710]
**Describe the bug**
When a journal has no supportedFormLocales, a `NULL` value will be passed to a `whereNotIn` method that expects an array. This will cause a fatal error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given, called in \lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php on line 919 and defined in \lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:3088
Stack trace:
#0 \lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(919): Illuminate\Database\Query\Builder->cleanBindings(NULL)
#1 \lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(946): Illuminate\Database\Query\Builder->whereIn('js.locale', NULL, 'and', true)
#2 \lib\pkp\classes\migration\upgrade\PKPv3_3_0UpgradeMigration.inc.php(191): Illuminate\Database\Query\Builder->whereNotIn('js.locale' in \lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php on line 3088
```

**To Reproduce**
1. Remove the supportedFormLocales row from the journal_settings table and then run an upgrade.

**What application are you using?**
3.0

**Additional information**
See report in [forum](https://forum.pkp.sfu.ca/t/issue-on-the-upgrade-from-ojs-3-2-1-2-to-3-3-0-2/656080).

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/6711

**Comment by Vitaliy-1** [comment]
Looks like in my test case it leads to:
```
ERROR: Upgrade failed: DB: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'as `js` where `js`.`journal_id` = ? and `js`.`setting_name` in (?, ?, ?, ?, ?, ?' at line 1 (SQL: delete from `journal_settings` as `js` where `js`.`journal_id` = 1 and `js`.`setting_name` in (authorInformation, librarianInformation, openAccessPolicy, privacyStatement, readerInformation, submissionChecklist, clockssLicense, lockssLicense) and 1 = 1)
```

**Comment by NateWr** [comment]
Can you inspect it to see if it's because there's an empty array? I wonder how an empty array could happen and, if so, what we do about it. It seems like other things on the site are going to break in such cases, so we may need to either log the problem or throw an exception.

**Comment by Vitaliy-1** [comment]
I recall that at the time the shared library's upgrade script is executed, settings are serialized with PHP serializer rather than JSON encoding. Let me check.

**Comment by Vitaliy-1** [comment]
Before that loop, the row looks like:
```
 [0] => stdClass Object
                (
                    [id] => 1
                    [locales] => a:2:{i:0;s:5:"en_US";i:1;s:5:"uk_UA";}
                )
```

**Comment by Vitaliy-1** [comment]
(it's the only row in the array, as only 1 journal)

**Comment by NateWr** [comment]
Does changing it to `unserialize` fix the problem for you?

**Comment by Vitaliy-1** [comment]
No, I'm still receiving `DB: SQLSTATE[42000]` error:
```
ERROR: Upgrade failed: DB: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'as `js` where `js`.`journal_id` = ? and `js`.`setting_name` in (?, ?, ?, ?, ?, ?' at line 1 (SQL: delete from `journal_settings` as `js` where `js`.`journal_id` = 1 and `js`.`setting_name` in (authorInformation, librarianInformation, openAccessPolicy, privacyStatement, readerInformation, submissionChecklist, clockssLicense, lockssLicense) and `js`.`locale` not in (en_US, uk_UA))
```

**Comment by elton557** [comment]
Hello now presented this error

ERROR: Upgrade failed: DB: SQLSTATE [42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `js` where` js`.` journal_id` =? and `js`.`setting_name` in (?,?,?,?,?,? 'at line 1 (SQL: delete from` journal_settings` as `js` where` js`.`journal_id` = 1 and `js `.`setting_name` in (authorInformation, librarianInformation, openAccessPolicy, privacyStatement, readerInformation, submissionChecklist, clockssLicense, lockssLicense) and 1 = 1)

**Comment by Vitaliy-1** [comment]
new PR pkp/lib: https://github.com/pkp/pkp-lib/pull/6715
tests OJS: https://github.com/pkp/ojs/pull/3033
WIll make PR to stable branch if all is ok here.

**Comment by NateWr** [comment]
Thanks @Vitaliy-1! It looks good to me. @asmecher can you take a quick look just to confirm this is ok? Once bitten, twice shy or something... :)

**Comment by elton557** [comment]
Thanks, now it's ok.

Successfully upgraded to version 3.3.0.2

**Comment by drugurkocak** [comment]
Dear @NateWr 
I also get similar error during upgrade from OJS 3.2.1.3 to 3.3.0.2 (git install) via command line.

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given, called in /home/sehirtipdergisi/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 919 and defined in /home/sehirtipdergisi/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3088
> Stack trace:

 But when I check the journal_settings table, I can see the supportedFormLocales row, and it is filled with these values.

> a:2:{i:0;s:5:"en_US";i:1;s:5:"tr_TR";}

I go on watching and reading discussions about this, but wanted to report it here.

 I can share user information with you if it helps you solve the problem.
Regards,

**Comment by asmecher** [comment]
@drugurkocak, have you tried the patch linked above? (https://github.com/pkp/pkp-lib/pull/6715/files)?

**Comment by asmecher** [comment]
@Vitaliy-1, the PR uses OJS and OPS table names (`journal_settings`) but will break OMP upgrades. Could you either move this part of the migration to the application-specific migration class, or use something like...
```
$contextDao = Application::getDAO('ContextDAO');
$settingsTableName = $contextDao->settingsTableName;
```

**Comment by drugurkocak** [comment]
> @drugurkocak, have you tried the patch linked above? (https://github.com/pkp/pkp-lib/pull/6715/files)?

Dear @asmecher 
Thank you very much for your kind support. Now, after applying that patch, I got the message "Successfully upgraded to version 3.3.0.2".
Since I made a fresh git install from master branch only 2 hours ago, I mistakenly thought that pacth has already been applied. Thanks to everyone.
Reegards.

**Comment by asmecher** [comment]
@drugurkocak, thanks for the confirmation! We'll be wrapping up OJS 3.3.0-3 within the next couple of days to incorporate this patch.

**Comment by Vitaliy-1** [comment]
I vote for leaving this in the shared library. I've updated PR (and tests)

**Comment by Vitaliy-1** [comment]
Builds are successful. Added PR to the stable branch:
https://github.com/pkp/pkp-lib/pull/6721
@NateWr, think it's ready to go!

**Comment by Vitaliy-1** [comment]
Something isn't right here. While exploring possible issues related to upgrading of older OJS version, I realized that getting the same error on versions < 3.2.

The journal settings are being serialized as JSON before the migration code related to clearing unused localized settings. I suspect it happens because `DAO::convertToDB` is triggered somewhere in the upgrade script.

**Comment by Vitaliy-1** [comment]
Yes, from the ContextDAO it's called in `Installer::migrateSidebarBlocks()`. When the Context is updated with `ContextDAO::updateObject`, it causes settings to be serialized as JSON.

**Comment by Vitaliy-1** [comment]
Hmm, this brings some uncertainty: site and journal/press settings are being serialized as JSON earlier than they should. I don't see any other places in the code where it can lead to a problem. I think, simple checks for locales row should do the trick. I mean something like:
```
if (@unserialize($locales) !== false) unserialize(...)
else json_decode(...)
```
Plus avoid warnings where setting values are being unserialized in places like https://github.com/pkp/ojs/blob/b85c552b55a9428e65c9f7f21b062c7940128b0e/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php#L137

**Comment by Vitaliy-1** [comment]
Updated and new PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/6715
OJS master: https://github.com/pkp/ojs/pull/3033
OMP master: https://github.com/pkp/omp/pull/926
OPS master: https://github.com/pkp/ops/pull/117

**Comment by Vitaliy-1** [comment]
@asmecher, can you take a look at these and merge/backport to stable 3.3.0 if all is ok?

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1, I've merged these to `master` and cherry-picked to `stable-3_3_0`. I'll run an upgrade smoke test on all three apps form `stable-3_3_0` to make sure.
