### ISSUE TITLE
[OPS] Method to easily extract preprint statistics

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6717]
**Describe the problem you would like to solve**
Currently there is no easy method of extracting the most accessed and downloaded preprint statistics.

The list is limited to 30 results per page and one needs to copy + paste the information in a spreadsheet if one wants to manipulate the data.

**Describe the solution you'd like**
An option to download all data into a CSV file.

**Who is asking for this feature?**
Preprint Server Managers who need to keep track of most accessed/downloaded content.

**Additional information**
![Sem Título-2](https://user-images.githubusercontent.com/4059679/106780428-bec05c00-6626-11eb-83d7-b0f112a678c0.png)

It would be desired to have author information and manuscript title separated by two different columns. It's easier to work with these two data separated.

**Comment by ajnyga** [comment]
There are the Reports tools that allow you to export CSV data. With OJS I usually instruct the editors to use the custom report tool.

**Comment by alexxxmendonca** [comment]
@ajnyga I don't know if that's necessarily the same.

The "Preprints" statistics page show an overall filtered by the date range you selected. You get exactly what you want.

The "Reports" tool you can't specify a date range and there is no overall sum of accesses. You need to work on a spreadsheet manager in order to get that.

It's doable, but it's a lot harder and not everyone has the skills.

**Comment by ajnyga** [comment]
You can define a date range in the custom report generator, but it is true that it will not directly show you any total numbers so you need to count them in a spreadsheet app.

I actually discussed this issue (export option in the stats page) with @NateWr back when the new stats page was introduced to OJS, but thanks to Slack's short memory I do not recall what the conclusion was.

**Comment by NateWr** [comment]
This is covered (briefly) in https://github.com/pkp/pkp-lib/issues/3366.

**Comment by bozana** [comment]
merged into main branch -- implemented for 3.4 -- thus closing...
