### ISSUE TITLE
Can't add new conversation in copyediting

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#672]
The form doesn't load the grids/listbuilders for users and files, and when you submit it returns an invalid JSON response, it seems.

**Comment by asmecher** [comment]
Bruno, this seems OK to me -- could you inspect the responses with FireBug and see if there's an error message in there or something? (BTW, I did remove the unused but not-null queries.user_id column from the database -- not sure if that's causing what you reported, but I don't think so.)

**Comment by beghelli** [comment]
I tested that using the pkp test instance. But locally is working fine also.
