### ISSUE TITLE
monograph export as native xml fails

### ISSUE THREAD

**Issue by gemusehandler** [pkp/pkp-lib#6722]
**Describe the bug**
I successfully installed the OMP 3.3.0.2. To test the press I have uploaded two books, one monograph and one edited volume with some chapters. The monograph can't be exported as Native XML and generates the following message:

Validation errors:
Element '{http://pkp.sfu.ca}chapters': Missing child element(s). Expected is ( {http://pkp.sfu.ca}chapter ).
Invalid XML:

The edited volume downloads fine.

It seems that the plugin expects in both cases some chapters.

**To Reproduce**
1. Login
2. Go to tools
3. Select the Native XML Plugin
4. Click export
5. Select the monograph
6. click export submissions

**What application are you using?**
 OMP version 3.3.0.2

**Additional information**
![Screenshot 2021-02-04 at 18 04 38](https://user-images.githubusercontent.com/4614219/106928533-919da780-6713-11eb-966f-f7f91ab301f4.jpg)

**Comment by asmecher** [comment]
@defstat, could you have a look at this?

**Comment by defstat** [comment]
@asmecher 

**PR**
[OMP]: pkp/omp#925

@gemusehandler can you check the above change against your installation, to see if that fixes your issue?

**Comment by gemusehandler** [comment]
I am now able to download and xml file for the monograph. I also tested the edited volume. That one is also downloadable. The issue seems solved. Thanks.

Just a short question. How much work would it be to adapt the plugin to make it produce an XML I can upload to Crossref? (The was actually the reason I immediately started to try the Native XML plugin. I wanted to see the structure of the file to compare it to what Crossref might accept)

**Comment by asmecher** [comment]
Thanks for the fix and confirmation, @defstat and @gemusehandler!
