### ISSUE TITLE
Submissions orphaned when context is deleted

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#6723]
**Describe the bug**
Submissions are orphaned when deleting a context.

**To Reproduce**
1. Call `JournalDAO::deleteById()` with `$id`
2. Query "select * from submissions where context_id = ?" with `$id`

**What application are you using?**
 OJS, 3.1.2

**Additional information**
The cause is that `JournalDAO::deleteById()` processes Sections before Articles:
https://github.com/pkp/ojs/blob/29089e5ffd0f3dc743eb4d7a949334f166fe97aa/classes/journal/JournalDAO.inc.php#L77-L101

So, when `SubmissionDAO::getByContextId()` fetches joins and uses a inner join on 'sections', there is no match:
https://github.com/pkp/pkp-lib/blob/1e6a456808133ae541720bbd0bdd41ad0aaca61e/classes/submission/SubmissionDAO.inc.php#L456-L477
https://github.com/pkp/ojs/blob/29089e5ffd0f3dc743eb4d7a949334f166fe97aa/classes/article/ArticleDAO.inc.php#L351-L360

This may be resolved in 3.2 and later, because [`Submission::getByContextId()`](https://github.com/pkp/pkp-lib/blob/6a84023bc829df10a20761cb130d58a783423f07/classes/submission/PKPSubmissionDAO.inc.php#L217-L229) no longer references joins.  The logic flaw, however, could remain, as sections are deleted before submissions, and submissions should be deleted before sections:
https://github.com/pkp/ojs/blob/b85c552b55a9428e65c9f7f21b062c7940128b0e/classes/services/ContextService.inc.php#L149-L164

And why is this all done "after" the context has been deleted?  Shouldn't the context be serially emptied, and then deleted?

**Comment by asmecher** [comment]
> And why is this all done "after" the context has been deleted? Shouldn't the context be serially emptied, and then deleted?

We'll have to resequence the deletions as we introduce more foreign key constraints (https://github.com/pkp/pkp-lib/issues/6093).

**Comment by asmecher** [comment]
@ctgraham, are you able to check if this affects more recent releases? (PR: https://github.com/pkp/ojs/pull/3036)

**Comment by ctgraham** [comment]
Still pending building a PHP 7.3 / 7.4 environment to test this against `main`.

I've also noticed, however, nothing currently deletes metrics.  This ought to be done when the submission is deleted, but also might need to be done at the context level to clean up orphans left by already-deleted submissions, when deleting the context.

**Comment by NateWr** [comment]
Closing until we can reproduce it in a more recent version.
