### ISSUE TITLE
Failed assert warning in Section settings page

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#6731]
**Describe the bug**

When I access the Section settings page, I get: 
`PHP Warning: assert(): assert(is_a($element, 'Section') &amp;&amp; !empty($columnId)) failed in /controllers/grid/settings/sections/SectionGridCellProvider.inc.php on line 30
`
The `$element` there seems to be a regular array, so probably the `assert` needs to be removed?

**To Reproduce**
1. Go to Sections settings and make sure that Sections exist
2. See the warning in log

**What application are you using?**
 OJS master branch (3.3.)

**Comment by asmecher** [comment]
You're right, @ajnyga! Fixed (`ops-stable-3_3_0`, `ojs-stable-3_3_0`, and OPS and OMP `master`)
