### ISSUE TITLE
I am unable to give line break in OJS 3.2.1.3. 

### ISSUE THREAD

**Issue by imaazahmed** [pkp/pkp-lib#6734]
![linebreak](https://user-images.githubusercontent.com/78767924/107296244-cb173f80-6a92-11eb-8024-65fea700c21a.png)

Hi mate!

I am trying to give line break in abstract but it doesn't work. I got spaces instead of line break. Can someone help me out? (I am using tinyMCE editor.
.
Thank you!

**Comment by asmecher** [comment]
I see you have already posted this on our support forum at https://forum.pkp.sfu.ca/t/i-am-unable-to-give-line-break-in-ojs-3-2-1-3/65744 -- that's the best place to get help.
