### ISSUE TITLE
How can i Add DOI and Keywords field in OJS 3.2.1.3

### ISSUE THREAD

**Issue by imaazahmed** [pkp/pkp-lib#6735]
Hi,

Please see this attachment. I want to add DOI and Keywords fields in the content page of Article but i don't have any field in OJS backend to add DOI and Keywords. 

Can anyone guide me that how can i add these two options?

Please see attachment.

Thank you!
![DOI and Keyword](https://user-images.githubusercontent.com/78767924/107296626-95268b00-6a93-11eb-9705-e460510a90da.png)

**Comment by asmecher** [comment]
@imaazahmed, I see you've already posted this to our support forum at https://forum.pkp.sfu.ca/t/how-can-i-add-doi-and-keywords-field-in-ojs-3-2-1-3/65745 -- that's the best place to get help.
