### ISSUE TITLE
Issue upgrading OPS 3.3.0-3

### ISSUE THREAD

**Issue by jameswill** [pkp/pkp-lib#6737]
**Describe the bug**
After applying necessary changes when I visit http://domain.com/[[DIR]]/index.php/index/install/installUpgrade it gives blank page.

On further debugging I found following error.

**_Uncaught Error: Class 'GenericPlugin' not found in [[PATH]]/[[DIR]]/plugins/generic/crossrefDeposit/CrossrefDepositPlugin.inc.php:14_**

**To Reproduce**
1. Back up your files and database
2. Remove files of existing installation.
3.  Restore your config.inc.php with all new changes present in new version.
4. Visit http://domain.com/[[DIR]]/index.php/index/install/upgrade and click on "Upgrade" throws above error.

**What application are you using?**
 OPS version 3.3.0.3

**Additional information**
Using PHP 7.3 and Mysql 5.5

**Comment by asmecher** [comment]
@jameswill, do you see the `GenericPlugin` class defined in `lib/pkp/classes/plugins/GenericPlugin.inc.php`?

**Comment by jameswill** [comment]
Hello,

Upgrade from 3.2.1.3 to 3.3.0-3 works fine by applying the patch i.e https://github.com/pkp/pkp-lib/pull/6719/files. However found that there are few new tables present in fresh install of 3.3.0.3, which are not created post upgrade from 3.2.1.3 to 3.3.0.3 i.e : 

review_forms
review_form_elements
review_form_element_settings
review_form_responses
review_form_settings

Will this cause any issues or is it fine?

**Comment by asmecher** [comment]
@jameswill, that's a different issue than the one first reported here (`Class 'GenericPlugin' not found`) -- could you post your question in our support forum (https://forum.pkp.sfu.ca)? That's the best place to get help. If something turns out to be a bug we can migrate it here for dev work.

**Comment by jameswill** [comment]
I have posted the issue on forum

[https://forum.pkp.sfu.ca/t/ops-upgrade-from-3-2-1-3-to-3-3-0-3-does-not-create-some-tables-which-are-created-in-fresh-install-of-ops-3-3-0-3/65950/2](url)
