### ISSUE TITLE
Issue installation OJS 3.3.0-3

### ISSUE THREAD

**Issue by ziekz** [pkp/pkp-lib#6738]
Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "app:app:frontendpagesuserLogin.tp" on line 11 "{include file="frontend/components/header.tpl" pageTitle="user.login"}" unknown tag 'include' <-- thrown in /home/********/avj.tusadam.com/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 11
I get this error. what should I do?

**Comment by asmecher** [comment]
I see this is already posted at https://forum.pkp.sfu.ca/t/http-error-500-installation-ojs-3-3-0-3/65754 -- that's the best place to start, and we can migrate back to Github if/when a bug is identified.
