### ISSUE TITLE
OJS update from version 3.2.1.4 to 3.3.0.3 fails when performed by the Web

### ISSUE THREAD

**Issue by leehreche** [pkp/pkp-lib#6739]
**Describe the bug**
Receiving a fatal error when the update starts with the installation set to Off. After trying to update OJS, I am redirected to an internal error 500 webpage.
Below is the error found in the error_log file:

`[09-Feb-2021 13:13:52 America/Fortaleza] PHP Fatal error:  Uncaught Error: Call to a member function getConnection() on null in /home2/hg2ou127/socibracom.com/ojs3303/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74
Stack trace:
#0 /home2/hg2ou127/socibracom.com/ojs3303/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php(200): Illuminate\Database\Capsule\Manager::connection()
#1 /home2/hg2ou127/socibracom.com/ojs3303/lib/pkp/classes/db/DAO.inc.php(65): Illuminate\Database\Capsule\Manager::__callStatic('raw', Array)
#2 /home2/hg2ou127/socibracom.com/ojs3303/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(106): DAO->retrieve('SELECT setting_...', Array)
#3 /home2/hg2ou127/socibracom.com/ojs3303/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(86): PluginSettingsDAO->getPluginSettings('0', 'lensgalleyplugi...')
#4 /home2/hg2ou127/socibracom.com/ojs3303/lib/pkp/classes/cache/GenericCache.inc.php(63): PluginSettingsDAO->_cacheMiss(Object(FileCache), 'enabled')
#5 /home2/hg2ou127/socibracom.com/ojs3303/lib/ in /home2/hg2ou127/socibracom.com/ojs3303/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php on line 74`

**To Reproduce**
1. Set installed to Off in config.inc.php
2. I open the OJS installation location via the web
3. Select the "Upgrade" link
4. Select the "Upgrade Open Journal Systems" link
5. See error

**What application are you using?**
 OJS 3.2.1-4 to OJS 3.3 upgrade (Full Package)

**Comment by asmecher** [comment]
See: https://github.com/pkp/pkp-lib/issues/6703#issuecomment-775320730

**Comment by ibnusulaiman83** [comment]
I got this error 
![Screenshot 2021-03-04 at 11 04 58 AM](https://user-images.githubusercontent.com/656929/109905333-9422fb00-7cd9-11eb-96a1-ee82003a5444.png)
How to fix that issue?

**Comment by asmecher** [comment]
@ibnusulaiman83, please stop posting the same issue in multiple places. I've already directed you to the support forum; that's the best place to get help.

**Comment by ibnusulaiman83** [comment]
> @ibnusulaiman83, please stop posting the same issue in multiple places. I've already directed you to the support forum; that's the best place to get help.

but no solutions.
