### ISSUE TITLE
Validation errors are not displayed when uploading files during submission

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6741]
**Describe the bug**
If a submission file upload returns a 400 response with validation errors, the `SubmissionFilesListPanel` can not handle these errors correctly. The response will be formatted like this:

```
{
  'genreid' => ['This is an invalid genre']
}
```

This is preventing the allowedUploads plugin by @ajnyga from working correctly.

**What application are you using?**
3.3.0-3

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ui-library/pull/143 (stable)

Tests:
https://github.com/pkp/ojs/pull/3038 (stable)

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry picked to `master.

**Comment by ajnyga** [comment]
I think I have to wait for this to be in an official release before I can do a new release for the plugin?

**Comment by NateWr** [comment]
If you want, you can assign your error like this:

```
$errors = [
  'error' => 'your.error.locale.key',
  'errorMessage' => __('your.error.locale.key')
];
```

That will override any other validation errors, but for your purposes it will probably suffice until 3.3.0-4 is out. Or you can release your plugin and just know that it will "work" but without a clear error message in versions before 3.3.0-4.
