### ISSUE TITLE
Import/Export OMP plugin extended

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6742]
**Describe the problem you would like to solve**
Extend the OMP import export functionality to include

- [ ] Chapter level DOI
- [ ] Book Series Title (for series attached to publications) (for series we only have path and Series Position for each publication.)
- [ ] Book Series description (for series attached to publications)
- [ ] eISSN for series attached to publications

**Comment by defstat** [comment]
@asmecher 

I have change the functionality for importing series attached to a publication. 

Before the PR, the code was looking for an existing series with the given path at the target installation. If no object found, the series is not added.

This PR changes that, trying to insert the given series. 

[OMP]: pkp/omp#929

**Comment by asmecher** [comment]
Thanks, @defstat, I've made one comment on https://github.com/pkp/omp/pull/929 but otherwise it's ready for merging.

**Comment by defstat** [comment]
@asmecher should this be closed or there is more to do?

**Comment by asmecher** [comment]
No, thanks, closing it!
