### ISSUE TITLE
Email Templates - The form was not saved

### ISSUE THREAD

**Issue by claytondf** [pkp/pkp-lib#6746]
**Describe the bug**

The OMP system does not allow you to change and save email templates.
The form was not saved because 1 error(s) were encountered. Please correct these errors and try again.

**To Reproduce**
WorkFlow->Emails->Email Templates

https://user-images.githubusercontent.com/8274709/107549757-f68f4c80-6bae-11eb-94c2-ce9e150313b5.mp4

**What application are you using?**
OMP Code version:      3.3.0.3
         Database version:  3.3.0.3

**Additional information**
Log to Apache2:

[Wed Feb 10 14:23:03.147849 2021] [:notice] [pid 21927] ModSecurity: Status engine is currently disabled, enable it by set SecStatusEngine to On.
[Wed Feb 10 14:23:03.232939 2021] [mpm_prefork:notice] [pid 21928] AH00163: Apache/2.4.38 (Debian) OpenSSL/1.1.1i configured -- resuming normal operations
[Wed Feb 10 14:23:03.232992 2021] [core:notice] [pid 21928] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 10 14:24:47.494142 2021] [php7:notice] [pid 21930] [client 170.150.1xx.x:56637] PHP Notice: Trying to access array offset on value of type null in /var/www/html/plugins/themes/default/DefaultThemePlugin.inc.php on line 151, referer: https://xxx.xxx.xxx/index.php/editoraunb/management/settings/workflow
[Wed Feb 10 14:24:47.744830 2021] [php7:notice] [pid 21930] [client 170.150.1xx.x:56637] PHP Notice: Trying to access array offset on value of type null in /var/www/html/plugins/themes/default/DefaultThemePlugin.inc.php on line 151, referer: https://xxx.xxx.xxx/index.php/editoraunb/management/settings/workflow
[Wed Feb 10 14:24:48.199674 2021] [php7:notice] [pid 21930] [client 170.150.1xx.x:56637] PHP Notice: Trying to access array offset on value of type null in /var/www/html/plugins/themes/default/DefaultThemePlugin.inc.php on line 151, referer: https://xxx.xxx.xxx/index.php/editoraunb/management/settings/workflow
[Wed Feb 10 14:24:48.303025 2021] [php7:notice] [pid 21929] [client 170.150.1xx.x:56642] PHP Notice: Trying to access array offset on value of type null in /var/www/html/plugins/themes/default/DefaultThemePlugin.inc.php on line 151, referer: https://xxx.xxx.xxx/index.php/editoraunb/management/settings/workflow
[Wed Feb 10 14:24:48.315518 2021] [php7:notice] [pid 21933] [client 170.150.1xx.x:56640] PHP Notice: Trying to access array offset on value of type null in /var/www/html/plugins/themes/default/DefaultThemePlugin.inc.php on line 151, referer: https://xxx.xxx.xxx/index.php/editoraunb/management/settings/workflow
[Wed Feb 10 14:24:48.319620 2021] [php7:notice] [pid 21929] [client 170.150.1xx.x:56642] PHP Notice: Undefined index: en_US in /var/www/html/lib/pkp/controllers/grid/settings/submissionChecklist/SubmissionChecklistGridHandler.inc.php on line 98, referer: https://xxx.xxx.xxx/index.php/editoraunb/management/settings/workflow
[Wed Feb 10 14:24:48.321980 2021] [php7:notice] [pid 21931] [client 170.150.1xx.x:56641] PHP Notice: Trying to access array offset on value of type null in /var/www/html/plugins/themes/default/DefaultThemePlugin.inc.php on line 151, referer: https://xxx.xxx.xxx/index.php/editoraunb/management/settings/workflow
[Wed Feb 10 14:24:48.352248 2021] [php7:notice] [pid 21932] [client 170.150.1x.x:56639] PHP Notice: Trying to access array offset on value of type null in /var/www/html/plugins/themes/default/DefaultThemePlugin.inc.php on line 151, referer: https://xxx.xxx.xxx/index.php/editoraunb/management/settings/workflow
[Wed Feb 10 14:24:57.612411 2021] [php7:notice] [pid 21995] [client 170.150.1xx.x:56643] PHP Notice: Trying to access array offset on value of type null in /var/www/html/plugins/themes/default/DefaultThemePlugin.inc.php on line 151, referer: https://xxx.xxx.xxx/index.php/editoraunb/management/settings/workflow

**Comment by asmecher** [comment]
@claytondf, can you review your language settings in your press and make sure that there is at least one form language enabled?

**Comment by claytondf** [comment]
@asmecher  Thank you!

    Resolved after enabling the form and submission checkbox.

![image](https://user-images.githubusercontent.com/8274709/107552969-f09b6a80-6bb2-11eb-8766-092e27635c33.png)
