### ISSUE TITLE
[OJS] 3.3.0.3 TypeError: e.availableLocales is null

### ISSUE THREAD

**Issue by otuoma** [pkp/pkp-lib#6749]
I have a new OJS installation of version 3.3.0.3. I get a blank section when I click on “journal” under settings. Masthead and Contact tabs are blank but Sections and Categories show their content.

![image](https://user-images.githubusercontent.com/12611023/107616539-56453080-6c5f-11eb-9397-1aad4f467c02.png)

The error I am seeing in the browser console is `TypeError: e.availableLocales is null` in the file build.js

Why is `availableLocales `coming up empty?

I have the setting `locale = en_US` in the config file and English is set as the primary locale in site settings as shown below

![image](https://user-images.githubusercontent.com/12611023/107616655-8e4c7380-6c5f-11eb-8353-58d8d3e6c9a7.png)

But I am also not sure that the JavaScript error is the reason why there is a blank section

**Comment by asmecher** [comment]
Hi @otuoma -- I see you've also posted this at https://forum.pkp.sfu.ca/t/ojs-3-3-0-3-typeerror-e-availablelocales-is-null/65811. That's the best place to get help.
