### ISSUE TITLE
[OJS 3.3] Plugin search in gallery misbehaving

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#6750]
[OJS 3.3]

When you search for a plugin the gallery and click in one the results, the plugin information display is not correct, instead it shows the information from the plugins that were in that position when the Gallery opened.

For example, this is my Gallery:
![image](https://user-images.githubusercontent.com/18707781/107630743-c2656b80-6c42-11eb-854e-eae1fc9e7cdf.png)

If I search for something (say "block"), this is what I get:
![image](https://user-images.githubusercontent.com/18707781/107630796-d3ae7800-6c42-11eb-8bf6-cb0f98c5ef69.png)

But when I click in any of the search results the information is from the plugins in first list. So if I click on **Immersion** I get **Hipothes.is**, if I click on **Twitter** I get **Backup**, and if I click on **Announcement** I get **iThenticate**, and so on.

**Comment by asmecher** [comment]
@luizbgomide, which application are you using, and what version? (Please include this when creating an issue.)

**Comment by luizbgomide** [comment]
@asmecher my bad, I usually put on the title, I missed this time. It is on OJS 3.3.

**Comment by asmecher** [comment]
Thanks for reporting, @luizbgomide -- either of the above commits should fix it in the `lib/pkp` submodule. (They are equivalent, just applied to different branches.)
