### ISSUE TITLE
Upgrade failure with PHP 8.0: conflicts with XMLParser class

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6751]
**Describe the bug**
When trying to upgrade OJS with PHP 8.0, receiving a fatal error:
```
PHP Fatal error:  Cannot declare class XMLParser, because the name is already in use in /home/doc/OJS/development/ojs/lib/pkp/classes/xml/XMLParser.inc.php on line 28
```

**To Reproduce**
1. Install PHP 8.0, e.g., `apt install php8.0`
2. Use php8.0 cli, e.g.,  `update-alternatives --set php /usr/bin/php8.0`
3. `php tools/upgrade.php upgrade`

**What application are you using?**
 OJS 3.2.1 upgrade to 3.3.0

**Additional information**
Use namespaces instead?

**Comment by asmecher** [comment]
- Renamed XMLParser to PKPXMLParser. (This class should be considered deprecated in favour of standard PHP built-ins and will be removed in the future.)
- Created a class alias where possible for backwards compatibility.

PRs:
- https://github.com/pkp/pkp-lib/pull/6755
- https://github.com/pkp/ojs/pull/3042 (submodule update; enables PHP8 Travis testing)
