### ISSUE TITLE
Incompatibility with PHP 8.0:  mb_substitute_character() no longer supports passing empty string

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6752]
**Describe the bug**
Tested on the upgrade attempt from OJS 3.2.1 to OJS 3.3.0. Receiving a fatal error:
```
PHP Fatal error:  Uncaught ValueError: mb_substitute_character(): Argument #1 ($substitute_character) must be "none", "long", "entity" or a valid codepoint in /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPString.inc.php:62
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPString.inc.php(62): mb_substitute_character()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(161): PKPString::init()
#2 /home/doc/OJS/development/ojs/lib/pkp/includes/bootstrap.inc.php(41): PKPApplication->__construct()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/CliTool.inc.php(32): require('...')
#4 /home/doc/OJS/development/ojs/tools/bootstrap.inc.php(17): require('...')
#5 /home/doc/OJS/development/ojs/tools/upgrade.php(18): require('...')
#6 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPString.inc.php on line 62
```

**To Reproduce**
1. Install PHP 8.0, e.g., `apt install php8.0`
2. Use php8.0 cli, e.g., `update-alternatives --set php /usr/bin/php8.0`
3. `php tools/upgrade.php upgrade`

**What application are you using?**
OJS

**Additional information**
According to the function's description: 

> Passing an empty string to substitute_character is no longer supported; "none" should be passed instead.

See: https://www.php.net/manual/en/function.mb-substitute-character.php

**Comment by Vitaliy-1** [comment]
Looking at the method's implementation, should int 63 be passed as an argument instead of a string? https://github.com/pkp/pkp-lib/blob/b373058ca0e5a181928ce7a4b06389f0e3419d1d/classes/core/PKPString.inc.php#L62

**Comment by Vitaliy-1** [comment]
And it looks like the default character is question mark anyway:  https://github.com/php/php-src/blob/f0b387d1e42a5d7e9f5ebda1bec428fc0e7374be/ext/mbstring/mbstring.c#L862. I can trace it until at least PHP-7.0 branch. Removing this setting if no objections.

**Comment by Vitaliy-1** [comment]
PR pkp-lib master: https://github.com/pkp/pkp-lib/pull/6754
Tests: https://github.com/pkp/ojs/pull/3041

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1, merged and cherry-picked back to `stable-3_3_0` and `stable-3_2_1`.
