### ISSUE TITLE
Supported form locales can be serialized as associative array

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6757]
**Describe the bug**
As part of 3.3.0 upgrade arrays and objects (in setting values) are serialized in JSON format. To simplify it, all arrays with integer keys are serialized as simple indexed arrays. Nevertheless, some forms may process data in the way it's serialized as associative arrays with integer keys, which may be sequential but starting not from a zero value, e.g.: `[2 => value1, 3 => value1]` or non-sequential with no apparent need.

In particular, the former is true for supportedFormLocales input in Languages form/Website settings. 
 
**To Reproduce**
1. 2 installed locales, English is primary, uncheck all boxes for `Forms` and `Submissions`.
![screencapture-localhost-8000-index-php-psp-management-settings-website-2021-02-12-17_48_32](https://user-images.githubusercontent.com/20665587/107789680-93421d80-6d5a-11eb-85ef-b98a6c85b6df.png)
2. Check `Submissions` box for the secondary locale, `Forms` locale box for the correspondent locale will be checked automatically. 
3. Check `Forms` box for the primary locale. Until this step `supportedFormLocales` is serialized as a non-associative array: `["uk_UA","en_US"]`
4. Uncheck `Forms` box for the secondary locale. Data is serialized as `{"1":"en_US"}`. `data` passed in the response:
``` 
{
  "1": {
    "key": "en_US",
    "label": "English"
  },
  "isGlobalEvent": true
}
```

The similar inconsistency happens with `submissionChecklist` after reordering

**What application are you using?**
 OJS 3.3.0

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by asmecher** [comment]
Assigning this to you, @Vitaliy-1 -- though I'm on the fence about whether it should be fixed in 3.3.0-3. If you can look at it tomorrow and the fix is small, please do; otherwise let's leave it to 3.3.0-5.

**Comment by Vitaliy-1** [comment]
Let's plan the fix for 3.3.0-5. I don't think that I'd able to provide a reliable solution today.

**Comment by asmecher** [comment]
@Vitaliy-1, I'm deferring again to 3.3.0-6, but please don't forget this one.

**Comment by Vitaliy-1** [comment]
@NateWr, do you remember our discussion regarding this issue? 
This doesn't have any side effects, so I'd better leave this as-is for the stable branches and targeted directly 3.4, where the simplest solution would be to render this form with Vue with slight re-design according to our UI library.

**Comment by NateWr** [comment]
@Vitaliy-1 for 3.3.0-6, can we just fix `LanguageGridHandler::saveLanguageSetting()` or is that harder than it looks? I was thinking we could just run `array_values` on any of the settings before we save them (`$contextService->edit(...)`).

**Comment by Vitaliy-1** [comment]
Yes, for this particular issue this fix should work, I'll take a look on Friday

**Comment by Vitaliy-1** [comment]
Tests OJS: https://github.com/pkp/ojs/pull/3097
stable-3_3_0 pkp-lib: https://github.com/pkp/pkp-lib/pull/6919
stable-3_3_1 pkp-lib: https://github.com/pkp/pkp-lib/pull/6923
main pkp-lib: https://github.com/pkp/pkp-lib/pull/6924

@NateWr, can you take a look? This solves issues with the form on my local instance. Although I'd revise the language data processing in the first place, this should be enough for now. 
`array_unique` is for removing locale duplicates, which I'm receiving sometimes when checking/unchecking UI locales alongside with other options.

**Comment by NateWr** [comment]
Thanks @Vitaliy-1! All three PRs merged. :+1:
