### ISSUE TITLE
[OPS] Rename OJS related variables in the code

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#6759]
The OPS code still has some references to things like articles and journals. Rename these to OPS related terminology or neutral terminology.

**Comment by asmecher** [comment]
@ajnyga, I've merged the rebase of your PR after it passed tests: https://github.com/pkp/ops/pull/132
Is this one ready to be closed?

**Comment by ajnyga** [comment]
I think is ready to be closed, can not think of anything else right now.
