### ISSUE TITLE
 [OJS 3.3] getting  error while uploading review file in revisions section

### ISSUE THREAD

**Issue by nuhnaci** [pkp/pkp-lib#6763]
OJS version : 3.3.0.3
PHP version: 7.4
the error the user received : Failed Ajax request or invalid JSON returned.
PHP log:
PHP Fatal error: Uncaught Error: Call to undefined method SubmissionFileDAO::getAllFileStages() in /var/www/…/lib/pkp/controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php:75
Stack trace:
#0 /var/www/…/lib/pkp/classes/core/PKPRouter.inc.php(387): PKPFileUploadWizardHandler->authorize()
#1 /var/www/…/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()
#2 /var/www/…/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route()
#3 /var/www/…/lib/pkp/classes/core/PKPApplication.inc.php(364): Dispatcher->dispatch()
#4 /var/www/…/index.php(68): PKPApplication->execute()
#5 {main}
thrown in /var/www/…/lib/pkp/controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php on line 75

**Comment by asmecher** [comment]
I think this has already been posted on the support forum (https://forum.pkp.sfu.ca/t/ojs-3-3-0-3-upload-of-article-flag-not-possible/65757) -- closing this issue in favour of discussion there.

**Comment by nuhnaci** [comment]
> I think this has already been posted on the support forum (https://forum.pkp.sfu.ca/t/ojs-3-3-0-3-upload-of-article-flag-not-possible/65757) -- closing this issue in favour of discussion there.

Yes, I wrote to the forum before, the inability to upload reviews affected the usage, so I wanted to draw attention to the problem here.
