### ISSUE TITLE
[OMP] Cannot upgrade using command line 

### ISSUE THREAD

**Issue by ibnusulaiman83** [pkp/pkp-lib#6767]
Hello. Iam using OMP version 3.1.0.0 and need to upgrade 3.2.1.4. I am using command line 
`php tools\upgrade.php upgrade`

But i got this error 
`[data: dbscripts/xml/upgrade/3.2.0_versioning.xml]
ERROR: Upgrade failed: DB: Column 'publication_id' cannot be null`

How to fix that issues?

**Comment by asmecher** [comment]
@ibnusulaiman83, please post your question on the support forum (https://forum.pkp.sfu.ca); that's the best place to get help.
