### ISSUE TITLE
[OJS] Access denied when clicking on "Administration" menu

### ISSUE THREAD

**Issue by nekoto-kun** [pkp/pkp-lib#6768]
**Describe the bug**
I'm having difficulties accessing Admin page through "Administration" menu under User menu despite logged in as the admin user. This happened after upgrading OJS version 3.1.2.0 to 3.3.0.3.

**To Reproduce**
1. Login as admin user
2. Open Profile menu dropdown on navigation bar
3. Click on "Administration"
4. Get the error "Access denied"

**However...**
I can actually access admin page through "Dashboard" and "Edit Profile" menu.

**What application are you using?**
 OJS version 3.3.0.3 with Health Sciences theme.

**Additional information**
The profile menu screenshot
![image](https://user-images.githubusercontent.com/40553075/108300500-015f6800-71d3-11eb-8857-f63603201a06.png)

The actual link in "Administration" menu: `../my-journal-name/admin/index`
The redirected link after clicking on "Administration" menu: `../my-journal-name/user/authorizationDenied?message=user.authorization.accessDenied`

I think it should be redirected to `../my-journal-name/submissions` since I only have a single journal. Or perhaps should it be redirected to `my-domain/index.php/index/admin`?

**Comment by asmecher** [comment]
@nekoto-kun, can you confirm whether this is still an issue when using the default theme?

**Comment by drugurkocak** [comment]
Dear @asmecher 
I can confirm that I get access denied message when I click Administration link on right top menu in frontend of OJS 3.3.0.3 using Default Theme too.
Regards,

**Comment by asmecher** [comment]
PR:
- https://github.com/pkp/pkp-lib/pull/6771

@defstat, could you review this, please?

**Comment by asmecher** [comment]
This will be fixed in OJS/OMP/OPS 3.3.0-4. Users who are affected can resolve the problem by applying this change:
https://github.com/asmecher/pkp-lib/commit/e9f5360ffe6638ff77e7c76db9496094eaf7759a
(The file to edit is `lib/pkp/classes/services/PKPNavigationMenuService.inc.php`.)

**Comment by Helyfoxer** [comment]
After upgrading to **3.3.0-10** this bugs with broken link to administrative page and "Access Denied" on it (then manually fixed URL to `/index.php/index/admin`) are still present.
And `lib/pkp/classes/services/PKPNavigationMenuService.inc.php` in this version already looks like https://github.com/asmecher/pkp-lib/commit/e9f5360ffe6638ff77e7c76db9496094eaf7759a
How can I fix this?

**Comment by ibnusulaiman83** [comment]
i am login as site admin but still access denied to access Administration Menu. Can you guide me

**Comment by asmecher** [comment]
@ibnusulaiman83, please post your question on our support forum at https://forum.pkp.sfu.ca; that's the best place to get help.
