### ISSUE TITLE
[OPS] Can't locate preprint via search

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6770]
**Describe the bug**
It's not possible to find this preprint using the search tool.

https://preprints.scielo.org/index.php/scielo/preprint/view/746

Attempted using title in Portuguese, English and using the author names but no success.

**To Reproduce**
1. Go to https://preprints.scielo.org/
2. Try searching for metadata for this posted preprint https://preprints.scielo.org/index.php/scielo/preprint/view/746
3. See that it doesn't appear in search results.

**What application are you using?**
OPS version 3.2.1.0

**Comment by ajnyga** [comment]
The search in OPS is basically the same as you would have in OJS. Have you tried to rebuild the search index? Thinking whether something has gone wrong when that particular preprint was published (and added to the index).

**Comment by alexxxmendonca** [comment]
This is an old issue and since then we did several adjustments including rebuilding the search index.

However, for some reason that particular preprint is still not searchable.

**Comment by NateWr** [comment]
Closing this as an issue specific to Scielo for now. Feel free to reopen if there are reproduction steps on a clean install of OPS.
