### ISSUE TITLE
Sections in Journal Settings keep loading in OJS 3.3.0.3

### ISSUE THREAD

**Issue by loadbrain** [pkp/pkp-lib#6775]
**Describe the bug**
If I click the Sections tab in Journal Settings the "Loading spinner" is shown, nothing else happens.
Same happens under Settings -> Workflow -> Submission -> Checklist

![checklist](https://user-images.githubusercontent.com/5653662/108508332-eddbfc00-72bb-11eb-8133-b853fab7ca3e.png)
![sections](https://user-images.githubusercontent.com/5653662/108508334-ef0d2900-72bb-11eb-8c5f-c6428f06b3c7.png)

**Comment by asmecher** [comment]
@loadbrain, could you post this in our support forum (https://forum.pkp.sfu.ca), and include any relevant entries from your PHP error log? That's the best place to get help.
