### ISSUE TITLE
usage event: the book abstract pages are not logged correctly

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6776]
**Describe the bug**
Instead of logging the URL .../catalog/book/{submissionId} the URL .../catalog/book is logged. This leads to book abstract views not to be counted at all.

**To Reproduce**
1. Go to a book abstract page
2. See the current usage log file in the folder `usageStats/usageEventLogs/`
3. See the wrong URL 

**What application are you using?**
 OMP 3.2.0 and 3.2.1

**Additional information**
S. also forum post https://forum.pkp.sfu.ca/t/catalog-entries-shows-flat-line-in-omp-3-2-0-3/65354

**Comment by bozana** [comment]
PRs:
stable-3_2_0: https://github.com/pkp/omp/pull/932
stable-3_2_1: https://github.com/pkp/omp/pull/933

**Comment by bozana** [comment]
@asmecher, could you please take a look?

**Comment by asmecher** [comment]
Oof, that's unfortunate -- but the fix looks good to me. I think in the future we should get rid of `publishedSubmission` terminology entirely in favour of just calling it a `submission` (this is a throwback to code before versioning/publications were introduced) but a minimal fix makes sense for everything up to `main`. Please go ahead!
