### ISSUE TITLE
Whitespace around author names should be trimmed

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6778]
**Describe the bug**
From the [forum](https://forum.pkp.sfu.ca/t/trailing-spaces-in-authors-name-result-in-a-ghost-abbreviation-point-in-citation-formats/65782):

> Trailing spaces in the author’s first name (Field “Given Name”) are not trimmed and will lead to “ghost” abbreviation points in several citation formats.
> 
> ...
> 
> In the Harvard Citation Style format this will lead to “Ljaljevic, A. .” with a ghost abbreviation point in the citation

Author name information should get trimmed before it is saved to the database and a migration should run to ensure existing data conforms to this.

**To Reproduce**
1. Create an author with a given name with a space at the end.
2. Enable the citation style language plugin and enable the Harvard format.
3. Preview the article, look at the how to cite block, and switch to Harvard format.

**What application are you using?**
3.3

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by mpbraendle** [comment]
Can confirm this behavior. Unfortunately, for our journal this happened with an article that had many authors, quite tedious to fix manually. https://ojs.chimia.ch/chimia/article/view/643

**Comment by mpbraendle** [comment]
Any bug fix for this - where can I investigate myself?

**Comment by NateWr** [comment]
@mpbraendle, no fix for this yet but I have added it to the 3.3.0-9 milestone. That doesn't mean it will get fixed for 3.3.0-9 but it will get noticed in future maintenance releases.

If you're willing to contribute a fix to the `stable-3_3_0` branch, you can take a look at PKPAuthorForm: https://github.com/pkp/pkp-lib/blob/stable-3_3_0/controllers/grid/users/author/form/PKPAuthorForm.inc.php

You could either add a `validate()` method to the form that checks for whitespace in fields. Or just `trim()` the values before they are saved in the `execute()` method.

I _think_ this problem won't exist in the `main` branch, because we use the schema system there. But you'll need to test there too and, if the problem does exist, fix it in the `main` branch as well.

**Comment by asmecher** [comment]
Thanks, @Tyl13! See: https://github.com/pkp/pkp-lib/pull/7758

**Comment by ajnyga** [comment]
Is this issue going to be fixed in a migration? I mean trim the already existing values?

**Comment by asmecher** [comment]
I'm open to contributions there, but at the moment, no -- the trimming is applied in the "edit author" form.
