### ISSUE TITLE
Awaiting approval notification in production doesnt go away after submission is approved

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#678]

**Comment by asmecher** [comment]
The approval checkbox for approving galley files has been removed and I don't think we need it. For now I've removed the getViewable() check on galley files from the front end (this used to distinguish between approved and unapproved galley files). We'll have to see if anyone wants this -- I don't think we've had may requests for it in OJS 2.4.x.

**Comment by beghelli** [comment]
Can I just remove this notification then?

**Comment by asmecher** [comment]
Yes, for OJS. For now at least, OMP will probably still need it.

**Comment by beghelli** [comment]
Needs more work to remove all the notification code (creation, update, etc). This change also BREAKS OMP until we add an application workflow tab handler there.

**Comment by asmecher** [comment]
Bruno, I've added a copy of the OJS version of the file for now, but I wasn't sure how it should be different for OMP. The basics are now working, so this is ready to continue.

**Comment by asmecher** [comment]
This should be resolved.
