### ISSUE TITLE
Wrong nesting in pkp-lib/templates/frontend/pages/navigationMenuItemViewContent.tpl

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#6780]
pkp-lib/templates/frontend/pages/navigationMenuItemViewContent.tpl
h1 should be inside div class="page", not outside. That would format the page similar to about.tpl

**Comment by asmecher** [comment]
@NateWr, what's your preference? If this is accepted, it looks like `plugins/generic/staticPages/templates/content.tpl` would need the same change.

**Comment by NateWr** [comment]
Yes, that's correct. The format for the default templates is:

```
<div class="page">
  <!-- breadcrumbs -->
  <h1>...</h1>
  <!-- page content -->
</div>
```

This is the format we should use for static pages and nav menu items.

**Comment by asmecher** [comment]
Both fixed for `main` and `stable-3_3_0`, thanks!
