### ISSUE TITLE
Crossref validation error when the author only has a given name

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6784]
**Describe the bug**
When an author only has/enters the given name, the Crossref XML export/deposit will result in an validation error, that the surname is missing. 

**To Reproduce**

**What application are you using?**
 OJS version 3.2.1, 3.3

**Additional information**
This is because we check if the family name is set ('isset') which it is always, but it can be empty. Instead we should check if the family name is empty ('empty')

**Comment by bozana** [comment]
PRs:
main: https://github.com/pkp/ojs/pull/3047
stable-3_2_1:

**Comment by bozana** [comment]
@asmecher, could you please review if the change is OK, i.e. if I can only use empty instead of isset here? Does it covers both: 1) when the array key (that locale) is not there, and 2) when the value is an empty string (the value is never NULL I think, but empty would handle that correctly as well, or?)? If OK so I will also fix stable branches... Thanks a lot!

**Comment by asmecher** [comment]
Yes, thanks, `empty` is the right thing to use in this case!

**Comment by bozana** [comment]
@mfelczak, everything merged...

**Comment by mfelczak** [comment]
Thank you @bozana!
