### ISSUE TITLE
[OPS] upgrade failure to 3.4: review_forms doesn't exist

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6785]
**Describe the bug**
Upgrade attempt from 3.2.1 to 3.4 (current master branch). Upgrade log:
```
php tools/upgrade.php upgrade
[pre-install]
[load: upgrade.xml]
[version: 3.4.0.0]
[code: Installer Installer::checkPhpVersion]
[code: Installer Installer::changeSubmissionStageToProduction]
[code: Installer Installer::installEmailTemplate]
[migration: PKPv3_3_0UpgradeMigration]
[migration: OPSv3_3_0UpgradeMigration]
[note: docs/release-notes/README-3.3.0]
[migration: PKPv3_4_0UpgradeMigration]
ERROR: Upgrade failed: DB: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ops-dev2.review_forms' doesn't exist (SQL: select `ra`.`review_form_id`, `ra`.`review_id` from `review_assignments` as `ra` left join `review_forms` as `rf` on `ra`.`review_form_id` = `rf`.`review_form_id` where `rf`.`review_form_id` is null and `ra`.`review_form_id` is not null)
```

**To Reproduce**
Run upgrade from a command line

**What application are you using?**
 OPS master branch

**Additional information**
Move queries associated with the `review_forms` table, like [this one](https://github.com/pkp/pkp-lib/blob/230395ba891878a62e319c2ff9c9edfc931907bd/classes/migration/upgrade/PKPv3_4_0UpgradeMigration.inc.php#L47) from shared library

`review_form`*-like tables are created only during installation of OPS instances 3.3 as described here: https://forum.pkp.sfu.ca/t/ops-upgrade-from-3-2-1-3-to-3-3-0-3-does-not-create-some-tables-which-are-created-in-fresh-install-of-ops-3-3-0-3/65950

**Comment by asmecher** [comment]
This has already been resolved elsewhere (evidenced by automated upgrade testing).
