### ISSUE TITLE
Updates to a customised journal stylesheet (css file) are not reflected in the HTML source

### ISSUE THREAD

**Issue by kasioumis** [pkp/pkp-lib#6793]
[OJS 3.2.1.1 but possibly later versions also]

Users can upload customised stylesheets (`.css` files) per journal (see [documentation](https://docs.pkp.sfu.ca/designing-your-journal/en/creating-stylesheet.html#upload-your-css-file)). There is only the option to upload a new stylesheet and once uploaded to remove it, but not to update it or re-upload it.

Customised stylesheets go into the DB as follows:
```sql
DB [ojs]> SELECT setting_name, setting_value FROM journal_settings WHERE journal_id = 1 AND setting_name = 'styleSheet';
+--------------+----------------------------------------------------------------------------------------------------------------------------+
| setting_name | setting_value                                                                                                              |
+--------------+----------------------------------------------------------------------------------------------------------------------------+
| styleSheet   | a:3:{s:4:"name";s:10:"custom.css";s:10:"uploadName";s:14:"styleSheet.css";s:12:"dateUploaded";s:19:"2020-02-20 01:23:45";} |
+--------------+----------------------------------------------------------------------------------------------------------------------------+
```
and appear in the HTML source as follows:
```html
<link rel="stylesheet" href="http://localhost/public/journals/1/styleSheet.css?v=3.2.1.1" type="text/css" />
```
Notice how the suffix of the `href` reflects the OJS version.

If the user removes the customised stylesheet and uploads an updated one (under the same OJS version) then the `href` will remain the same since neither the original filename of the customised `.css` file is refelcted in the `href`, nor the upload date. Instead the href is composed of the `styleSheet.css` generic (safe) name and the OJS version.

Most browsers will cache the first `.css` file they ever come across with the `http://localhost/public/journals/1/styleSheet.css?v=3.2.1.1` `href` and will not bother refreshing it unless the `href` changes. As a result, even if the customsied stylesheet is updated, end users will likely not use the updated stylesheet since their browser will be serving the old cached one for efficiency.

Suggested fix: the `href` of the customised stylesheet should be suffixed with the timestamp of the upload date, rather than the OJS version.

**Comment by kasioumis** [comment]
Example in action: <https://foodandnutritionresearch.net/index.php/fnr/index> (taken from <https://pkp.sfu.ca/2018/04/12/open-journal-system-3-examples/>). See:
```html
<link rel="stylesheet" href="https://foodandnutritionresearch.net/public/journals/1/styleSheet.css?v=3.1.2.4" type="text/css" />
```
in the HTML source.

**Comment by NateWr** [comment]
This turned out to be a pretty easy fix. We're storing the datetime that the file was uploaded, so by appending that to the URL we can ensure the URL path changes with each change to the file.

@kasioumis the PR below is against the `stable-3_3_0` branch but you should be able to apply the same changes to earlier versions if you are still on the 3.2.x line.

PR:
https://github.com/pkp/pkp-lib/pull/6795

Tests:
https://github.com/pkp/ojs/pull/3054

**Comment by kasioumis** [comment]
@NateWr awesome! Exactly what I had in mind :-) I was trying to figure out where the version string was being suffixed but it's not important; this works like a charm. I'll patch it in for now, thanks!

**Comment by NateWr** [comment]
@kasioumis this is where the version string is appended. It is only added if no `?` exists already: https://github.com/pkp/pkp-lib/blob/main/classes/template/PKPTemplateManager.inc.php#L1899-L1902

**Comment by kasioumis** [comment]
@NateWr Aha! I completely missed it. Many thanks for taking the time to point that out :-)

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `main`.
