### ISSUE TITLE
[OJS] site.tpl nest at least two <p> in journal description

### ISSUE THREAD

**Issue by samueloph** [pkp/pkp-lib#680]
If you go to /index/admin/editJournal/1 and edit the journals description, your homepage will get at least 1 error per journal with description at the W3C validator because you can't nest \<p\> tags. Also, for every breakline that the description have, one more nested \<p\> will be generated.

It's something like this:
site.tpl creates one \<p\>, then the text inserted in /index/admin/editJournal/1 gets another \<p\> on the surroundings plus one for each breakline.

**Comment by asmecher** [comment]
@samueloph, try the attached patch (both are equivalent, just for different branches) and please report back if it resolves the problem for you.

**Comment by samueloph** [comment]
Thank you @asmecher .

I didn't think the fix would be so simple, I should have checked before, I could've made the PR to don't occupy you with this trivial things, sorry.
