### ISSUE TITLE
Backend Favicon defaults to PKP logo

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6800]
**Describe the problem you would like to solve**
In OJS 3.1.2.0, the backend favicon defaults to the PKP logo even though a journal has uploaded a favicon image file. This seems to only work for the front end.

**Describe the solution you'd like**
Journal favicon should also display on the backend when logged in.

**Who is asking for this feature?**
Journal Managers

**Additional information**
Also tested with OJS 3.3 where the issue still persists.

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `main`.
