### ISSUE TITLE
Links to dependent files referenced in HTML/JATS XML galleys are broken

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6801]
**Describe the bug**
As part of submission files refactoring `originalFileName` property was dropped and is only stored in the `event_log_settings`. `name` property is used instead. This causes incorrect links to the dependent files referenced in HTML and XML galleys/submission files added before the upgrade as now the code, e.g., in HTML galley plugin, tries to link files using regex and relying on the `name` property: https://github.com/pkp/ojs/blob/3fecde2c940371d88838e983d0395b3c56983cb3/plugins/generic/htmlArticleGalley/HtmlArticleGalleyPlugin.inc.php#L157 

**To Reproduce**
Consider situations when a user adds a new HTML galley in OJS 3.2.1 and attaches images as dependent files with original file names, like `fig1.jpg`, `fig2.jpg`, etc... In HTML galleys those images also are referenced by original filename: `<img src="fig1.jpg">`. During upload OJS autosuggests to name those files in the format: `[username], filename`. After upgrade to 3.3.0 those links are not more valid. Relevant for HTML Article Galley Plugin, Lens Viewer Plugin, JATS Parser Plugin. Didn't check Texture but suspect it's also the case. 
 

**What application are you using?**
 OJS 3.3.0

**Additional information**
Related issues:
https://github.com/pkp/pkp-lib/issues/4957
https://github.com/pkp/pkp-lib/issues/6288

**Comment by Vitaliy-1** [comment]
@NateWr, do you have any ideas regarding this issue? Not sure how to manage this in regards to instance, already upgraded to 3.3.0. Ideally, in my opinion, during migration `originalFileName` should replace `name` at least for all images and stylesheets attached to galleys.

**Comment by Vitaliy-1** [comment]
`name` localization may also lead to problems and confusion. I mean HTML Article Galley Plugin in regex pattern provides search, depending on a current locale:
```
$pattern = preg_quote(rawurlencode($embeddableFile->getLocalizedData('name')));
```
In this scenario, the `name` should be identical for all locales and correspond to the reference to the file (image, css) in source HTML.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib main: https://github.com/pkp/pkp-lib/pull/6816
pkp-lib stable-3_3_0: https://github.com/pkp/pkp-lib/pull/6817
tests OJS main: https://github.com/pkp/ojs/pull/3062

**Comment by Vitaliy-1** [comment]
@NateWr, can you take a look?

**Comment by NateWr** [comment]
Looks ok to me, @Vitaliy-1. I just noticed the one thing for Alec to comment on. Can you run the tests against `stable-3_3_0`? That's the more important one to check against, I think. Although I don't think any migrations are run during the tests...

**Comment by Vitaliy-1** [comment]
I've updated the PR and added the test for 3.3.0 branch. Yes, I test migration script on my local instance because of this (but master branch only in this case).

**Comment by Vitaliy-1** [comment]
I think that it's ready to be merged but tests for the OJS main branch are failing. I suspect it's caused by an earlier commit to the shared library. I can merge it to a stable branch and wait until the issue with the main is resolved. @asmecher, what do you think?

**Comment by asmecher** [comment]
@Vitaliy-1, I've posted that here: https://github.com/pkp/pkp-lib/issues/5048#issuecomment-791603728

Feel free to go ahead and merge this to `main` in advance of the tests being fixed.
