### ISSUE TITLE
OAI reports "now" for last modification when submission last modification date is null

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6807]
**Describe the bug**
See: https://forum.pkp.sfu.ca/t/oai-pmh-with-datestamp-updated-daily-on-ojs-3-1-1-2/48080/19

- OAI `Identify` requests show the current time/date as earliest datestamp when any `null` value for `last_modified` exists in `submissions`
- OAI record timestamp shows current time/date when listing records or identifiers when that record's `last_modified` is `null` in `submissions`.

Apparently `last_modified` can be `null` for submissions made when the system was running OJS 2.x (and was subsequently upgraded).

**To Reproduce**
Set `last_modified` to `null` for any submission.
View the OAI `Identify` verb and check the earliest listed timestamp.

**Comment by marcbria** [comment]
Alec... don't know much how the upgrade script works.

I tested locally and this query does the job:

```
UPDATE `issues` SET `last_modified` = `date_published` 
WHERE last_modified IS NULL;
```

Do you think add the query to "[ojs/dbscripts/xml/upgrade/3.1.1_update.xml](https://github.com/bozana/ojs/blob/f3bea01cf87481133df2ba99f6176374a86fbd12/dbscripts/xml/upgrade/3.1.1_update.xml)" will be enough?

In what branches should I apply the changes?

Cheers,
m.

**Comment by asmecher** [comment]
Hi @marcbria! Actually I think you'll find that the issue appears in both `issues` and `submissions` -- a `null` in either place will cause the same problem.

The best place to put this will be in a new class in `classes/migration/upgrade` -- see https://github.com/pkp/ojs/tree/stable-3_3_0/classes/migration/upgrade. Then refer to it from `dbscripts/xml/upgrade.xml` so it's run on the upgrade from 3.x to 3.3:
```
<upgrade minversion="3.0.0.0" maxversion="3.2.9.9">
  <migration class="lib.pkp.classes.migration.upgrade.PKPv3_3_0UpgradeMigration" />
  <migration class="classes.migration.upgrade.OJSv3_3_0UpgradeMigration" />
  (...add your new migration here...)
  <note file="docs/release-notes/README-3.3.0" />
</upgrade>
```
Include the issue number in the class/file name for easy reference.

This would be best added to the `stable-3_3_0` branch, and I can forward-port from there to `main`.

**Comment by marcbria** [comment]
Thanks a lot Alec for the "min-howto" :-)

Does it means that won't be included in 3.2 branches?
I know about people that like to upgrade soon to 3.2 and won't jump to 3.3 is a little bit more stable.

**Comment by asmecher** [comment]
@marcbria, we don't currently plan to release another 3.2.x package unless there is a critical security issue. So we could merge it into the git `stable-3_2_1` and `stable-3_2_0` branches, but unless we release new packages, most users will never get the change.

**Comment by ajnyga** [comment]
I found this problem back in 2019 https://github.com/pkp/pkp-lib/issues/5135 but thought it was due to some non-native import of articles to our installation.

**Comment by marcoblancas** [comment]
Hi, #6829 has been closed as duplicated with this issue but I'm not sure that it was the same problem. In my case I get the current time/date as earliest datestamp but I have none `null` value in `last_modified` in `submissions` or `issues`.

`OJS version 3.3.0.3` from a previous 2.4

**Comment by asmecher** [comment]
@marcoblancas, can you check if there are any unset or invalid-looking dates in the `date_deleted` column of the `data_object_tombstones` table?

**Comment by marcoblancas** [comment]
Sure. I've checked and no nulls or invalid dates in `date_deleted` column of the `data_object_tombstones` table.

**Comment by asmecher** [comment]
@marcoblancas, are there any "zero" dates (`0000-00-00` or `1969-12-31`) in `issues.last_modified` or `submissions.last_modified`?

Are you using any plugins that modify the OAI interface, like DRIVER?

**Comment by marcoblancas** [comment]
None "zero" dates present. I attach you my dates in database. [last_modified.txt](https://github.com/pkp/pkp-lib/files/6093215/last_modified.txt)

DRIVER module is disabled in my journal.

**Comment by marcoblancas** [comment]
Could it be related with the date formats set in the journal (management/settings/website#setup/dateTime)?

![imagen](https://user-images.githubusercontent.com/5545390/110170345-5ff32b80-7dfa-11eb-8702-b64c87ed7f97.png)

**Comment by asmecher** [comment]
Ah, @marcoblancas, I suspect you're running into https://github.com/pkp/pkp-lib/issues/6803. There's a patch over there.

**Comment by marcoblancas** [comment]
> Ah, @marcoblancas, I suspect you're running into #6803. There's a patch over there.

Thank you. That solved my problem.

**Comment by asmecher** [comment]
@marcbria, are you planning to open a PR for this? I'd like to get 3.3.0-4 out on Friday and can take this over if you're busy.

**Comment by marcbria** [comment]
Sorry Alec... I'm in a mess now. Our first journal of the service with upgraded to ojs 3 is going to be released today.
Please, take this if you have time for it.

**Comment by marcbria** [comment]
Thanks Alec.

**Comment by marcbria** [comment]
Hi @asmecher 

I'm trying to test if this to be included in OJS stable-3.2.1... but I'm not able to find what I need to test.

I thought don't make much sense to spend time on the upgrade scripts, so I focused in code... but only code I found is this:
https://github.com/pkp/pkp-lib/commit/38175ecdffb98781c4d9faa48a1e24f59b1b53fc

I cherry-picked it and is not making any difference in the OAI datestamp output (that is still now, when data is null).

I took a look to the upgrade scripts and I had the sensation that won't work "as is" for ojs 3.2... but I can test them if you like.

Cheers,
m.

**Comment by asmecher** [comment]
https://github.com/pkp/pkp-lib/commit/38175ecdffb98781c4d9faa48a1e24f59b1b53fc is a different issue and only affects OJS/OMP/OPS 3.3.0-2 and 3.3.0-3; it doesn't affect 3.2.x.

The only changes for this issue are database changes; you could port this back to 3.2.x by adding the two relevant queries (see e.g. https://github.com/pkp/ojs/commit/ad7c3564e58a6edfe1b9907bda4e7a02d8693dca) to the upgrade scripts for 3.2.x, such as `dbscripts/xml/upgrade/3.2.1_update.xml`.

**Comment by marcbria** [comment]
Ok. 
I have doubts about including this in 3.2 because this version will be a pit-stop for older migrations (I mean, you can't upgrade directly to 3.3) but in the other hand, if somebody does a migration today they will like to finish at 3.3 so changes will be applied in this second upgrade.


I don't know if I explained myself, I mean, do you think is relevant to include this in stable-3.2.1?

Asking because testing an upgrade like this will take some time, but I will do if you think is important. 

BTW, do you want a PR for this?

**Comment by asmecher** [comment]
I normally wouldn't back-port this change to `stable-3_2_1`, but you were interested in it here: https://github.com/pkp/pkp-lib/issues/6852#issuecomment-874222885

I'm ambivalent about it, as I don't think we're likely to release another 3.2.x package.

**Comment by marcbria** [comment]
Ok. If no 3.2 will be released, don't make any sense the effort.
Feel free to close Alec. Thanks.

**Comment by asmecher** [comment]
Gotcha, thanks, @marcbria!
