### ISSUE TITLE
Untranslated locale key notification.type.submissionNewVersion in new version notification email

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6808]
**Describe the bug**
See: https://forum.pkp.sfu.ca/t/translation-missing-in-weblate/66116/3
> We noticed after an upgrade to 3.2.1-3 that we have an untranslated string in one of the mails sent by the system:
> ##notification.type.submissionNewVersion##

**Comment by NateWr** [comment]
@asmecher looks like this one might be done?

**Comment by asmecher** [comment]
Yup, closing!
