### ISSUE TITLE
Add submissions filter by category

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6809]
**Describe the problem you would like to solve**
Preprint servers and journals that use categories would like to be able to filter the submission lists by assigned category.

**Describe the solution you'd like**
Add a filter to the submissions list that allows the submissions list to be filtered by categories. This can use the same format as the sections filter: when there are fewer than 5 categories, show filters as a list, otherwise use the autosuggest filter.

The following users should have access to this filter:

- Admins
- Managers
- Subeditors
- Assistants

This filter should not appear unless at least one category has been configured in the journal, press or preprint server.

**Who is asking for this feature?**
Ubiquity Press, cc @salmanm2003.

**Comment by NateWr** [comment]
PRs (from @salmanm2003):
https://github.com/pkp/pkp-lib/pull/6814
https://github.com/pkp/ui-library/pull/145

**Comment by salmanm2003** [comment]
@NateWr the test is running here:
https://github.com/pkp/ojs/pull/3064

**Comment by salmanm2003** [comment]
@NateWr the test is done, here is the result:
https://travis-ci.com/github/pkp/ojs

**Comment by NateWr** [comment]
All merged, thanks @salmanm2003! (It looks like the tests timed out, but I can see from the logs that they ran ok right up to the end, so pretty confident we're safe here.)

**Comment by NateWr** [comment]
Adding a note here, so we don't forget, that this will need to be backported to `stable-3_3_1` once we've begun work on that branch.

**Comment by NateWr** [comment]
I've cherry-picked this feature into our new `stable-3_3_1` branch so it will go out with the first 3.3.1.x release.

**Comment by salmanm2003** [comment]
Thanks @NateWr
