### ISSUE TITLE
TinyMCE content placeholder dropdown needs to be aligned and styled

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#681]
This can be seen in the Review > Add Reviewer modal, with the email message.

![selection_005](https://cloud.githubusercontent.com/assets/2306629/9226854/79a11770-4108-11e5-808b-4d5b7cb0ac0a.png)

**Comment by asmecher** [comment]
(FYI, that widget is implemented in `plugins/generic/tinymce/plugins/pkpTags`.)

**Comment by NateWr** [comment]
Already fixed! https://github.com/pkp/pkp-lib/issues/990#issuecomment-191800885
