### ISSUE TITLE
[OMP] undefined STATUS_PUBLISHED error on Press delete

### ISSUE THREAD

**Issue by sourcedump** [pkp/pkp-lib#6811]
Hello!
Using OMP 3.2.1-2 I have an error if I try to delete a press at the page:
https://<DNS-NAME>/index.php/index/admin/contexts

The error is:
`invalid input syntax for integer: "STATUS_PUBLISHED" Query: select "s".* from "submissions" as "s" where "s"."context_id" = ? and "s"."status" in (?) group by "s"."submission_id" order by "s"."date_submitted" desc in /lib/pkp/classes/db/DAO.inc.php`

The fatal error is caused by this:
`PHP Warning: Use of undefined constant STATUS_PUBLISHED - assumed STATUS_PUBLISHED'`

Following the hint I’ve found on:
https://github.com/pkp/ojs/commit/8adcdcca085dc7a685c5954a69e1080ebf05b81d

I’ve added this workaround code at line 83 and 108 of the file

- classes/publicationFormat/PublicationFormatTombstoneManager.inc.php

`import('lib.pkp.classes.submission.PKPSubmission');`

PKP Forum issue:

- https://forum.pkp.sfu.ca/t/omp-undefined-status-published-error-on-press-delete/65134

**Comment by asmecher** [comment]
Merged https://github.com/pkp/omp/pull/938/commits and cherry-picked forward to `stable-3_3_0` and `main`, thanks!
