### ISSUE TITLE
Mail on submission to author fails everytime and an error message comes on screen in ojs 3.2.1 for all author

### ISSUE THREAD

**Issue by hammadkhan07** [pkp/pkp-lib#6812]
![image](https://user-images.githubusercontent.com/75437312/109803042-6343b700-7c42-11eb-9b90-546ccb041473.png)

Everytime when i try to upload a new submission in this platform this gives something like this even I have changed all the settings in php.ic file which were described in pkp community as it is I did all the changes it still gives the same email error for all authors I can anybody report what is this issue and how can it be solved all the other mails are working totally fine

**Comment by asmecher** [comment]
@hammadkhan07, could you search for this message on our support forum (https://forum.pkp.sfu.ca), and if you don't find a solution there, create a new forum topic? That's the best place to get help.

**Comment by hammadkhan07** [comment]
I searched for it and applied all the possible solutions that were given on
pkp forum still it has the same problem.

But I will post on forum as well and thanks
