### ISSUE TITLE
Bug at Layout After Upgrade Journal From OJS 3.2 to OJS 3.3.0.3

### ISSUE THREAD

**Issue by tjmarpaung** [pkp/pkp-lib#6813]
**Describe the bug**

Please help me with bugs in the layout in my journal when I was updating my journal from OJS 3.2 to OJS 3.3.0.3. I updated my journal with softaculous in Cpanel. I use the multi journal in my journal. You can visit my journal in "http://bulletin.indoms-acehsumut.org". Thanks.

**What application are you using?**
 I use OJS 3.3.0.3

**Additional information**
![Screenshot (1082)](https://user-images.githubusercontent.com/64982204/109808577-e15f8800-7c59-11eb-8717-af97b4f10bd1.png)

**Comment by asmecher** [comment]
@tjmarpaung, please post your question on our support forum (https://forum.pkp.sfu.ca); that's the best place to get help.
