### ISSUE TITLE
TinyMCE can overwrite public images in other contexts

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6824]
If a user with journal manager roles in more than one context in a multi-context install uses TinyMCE to add images directly to a rich text field, and they add those images directly  from clipboard content such as that created with a screenshot tool, TinyMCE will automatically  assign a filename, such as mceclipX.png, where X is an autoincremented integer.  These images are automatically saved in the public/site/images/username folder upon paste, not when the form is saved.

If this same user performs the same thing in a different context, TinyMCE will overwrite the older mceclipX.png image, since the directory is shared. This can lead to cross contamination across contexts. 

It's not possible to use this to overwrite private submission data since that is stored elsewhere.

Seen in 3.3.0 and 3.2.1-3.

**Comment by NateWr** [comment]
@jnugent can you identify what form fields this happens in? The URL where uploaded images are saved is configured differently for each field, so we'll need to track down which ones this is happening to. (Typically, if a form is for a specific context, it should be uploading to a context directory, not the site directory.)

**Comment by jnugent** [comment]
Hi @NateWr  That doesn't seem to be what happens.  For instance, I just used our Test Drive install here:

https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php/testdrive-journal/about/editorialTeam

and uploaded that "testing" image while logged in, and editing the Editorial Team field in Journal Settings.  If you examine the path to that file, you'll see that it isn't in a context directory, but rather the public/site directory instead.

**Comment by NateWr** [comment]
Ah, right, I understand now. I forgot that the TinyMCE uploads all go into a user-specific directory, so they will be shared across contexts. I've added some checks to prevent filename clashes when using the public file API.

PR:
https://github.com/pkp/pkp-lib/pull/6854 (stable-3_3_0)

Tests:
https://github.com/pkp/ojs/pull/3072 (stable-3_3_0)

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `main`.
