### ISSUE TITLE
Introduce a "home" for JATS

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6825]
**Describe the problem you would like to solve**
Currently there is no single "home" for a JATS document in OJS. Tools wanting to work with JATS need to [go hunting](https://github.com/pkp/oaiJats/blob/stable-3_3_0/OAIMetadataFormat_JATS.inc.php#L35..L58) for candidate files, and XML producers (either plugins or third parties) have nowhere specific to put finished JATS files.

**Describe the solution you'd like**
- Introduce a new tab beside "Workflow" and "Publication" in the Editor's interface called "JATS".
- The new tab should be accessible to anyone who can currently access "Publication".
- The presence of the new tab can be enabled/disabled in setup.
- Implement a file upload for a single JATS XML file, for which the resulting file ID is associated with the publication.

**Who is asking for this feature?**
- Coalition Publica
- Groups that work with outsourced XML generation

**Comment by asmecher** [comment]
@NateWr, this entry is the result of our conversation this morning. One thought: the Publication tab already manages versioning, and we want the XML file to be versioned (a.k.a. associated with the Publication, not the Submission). Is this a motivation for keeping the new area inside Publication, rather than in its own freestanding tab? Or would we have a version dropdown on the JATS tab as well?

**Comment by asmecher** [comment]
(Related: https://github.com/pkp/pkp-lib/issues/6684)

**Comment by NateWr** [comment]
> Is this a motivation for keeping the new area inside Publication, rather than in its own freestanding tab?

Yes, I think you're right. A new left-hand tab under Publication is probably the best place for this.

**Comment by NateWr** [comment]
> The new tab should be accessible to anyone who can currently access "Publication".

This should be anyone with a manager, subeditor or assistant assignment to the Production stage. That's how access is controlled at the moment.

**Comment by asmecher** [comment]
@NateWr, is this a duplicate of https://github.com/pkp/pkp-lib/issues/7505?

**Comment by NateWr** [comment]
Yes, I think so.
