### ISSUE TITLE
New sections added to an Issue can't be custom ordered if the issue has already been custom ordered

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6828]
**Describe the bug**

If an issue is created, and articles in various sections are added to this issue, and then the issue is ordered in a custom way so that sections are moved around, new sections added later on can't be ordered. It's possible to move them around in the TOC grid, but when you click save they will revert partially.  The grid will remember the order for the first time you customize ordering, but not for anything you add to that issue later on.  I believe this is because `setDefaultCustomSectionOrders` is only called initially, in `setDataElementSequence` in `TocGridHandler` if the `sectionDao` does not detect an existing custom order.  There's no other entry point to insert the records needed for ordering in custom_section_orders after that first go around, and future calls to `resequenceCustomSectionOrders` will not find the newly added sections to the issue's table of contents.

**To Reproduce**
1. Create a new empty issue.
2. Ensure that you have at least three journal sections created.
3. Publish an article in one of those sections and add it to the issue.
4. Publish a second article in a different section and add it to the same issue.
5. Edit the issue and re-order the two sections.  This will save correctly.
6. Publish a third article in a new section, and add it to the issue.
7. attempt to reorder the issue's table of contents, by moving this new section to the top. 
8. It should not save and will revert when ordering is finished.

**What application are you using?**
Seen in 3.3.0, 3.2.1-3

**Comment by jonasraoni** [comment]
PR for [ojs/main](https://github.com/pkp/ojs/pull/3157).

**Comment by jonasraoni** [comment]
@asmecher Here's the PR to fix the `stable-3_3_0`: https://github.com/pkp/ojs/pull/3187

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by amandastevens** [comment]
We have to apply this patch to a client's journal site about once every 2 weeks. Can the fix be backported to OJS 3.2?

**Comment by jonasraoni** [comment]
@asmecher I've created two extra PRs for this issue:
stable-3_2_1 https://github.com/pkp/ojs/pull/3257
stable-3_2_0 https://github.com/pkp/ojs/pull/3258

**Comment by asmecher** [comment]
Both merged, thanks!
