### ISSUE TITLE
[OJS] Upgrade to  OJS 3.3.0-3 issue

### ISSUE THREAD

**Issue by altafnagar** [pkp/pkp-lib#6835]
Fatal error: Uncaught Error: Call to a member function getConnection() on null in /home/xxx/public_html/new/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74 Stack trace: #0 /home/xxx/public_html/new/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php(200): Illuminate\Database\Capsule\Manager::connection() #1 /home/xxx/public_html/new/lib/pkp/classes/db/DAO.inc.php(65): Illuminate\Database\Capsule\Manager::__callStatic('raw', Array) #2 /home/xxx/public_html/new/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(106): DAO->retrieve('SELECT setting_...', Array) #3 /home/xxx/public_html/new/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(86): PluginSettingsDAO->getPluginSettings('0', 'tinymceplugin') #4 /home/xxx/public_html/new/lib/pkp/classes/cache/GenericCache.inc.php(63): PluginSettingsDAO->_cacheMiss(Object(FileCache), 'enabled') #5 /home/xxx/public_html/new/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(57): GenericCache->get('enabled') #6 /home/ in /home/xxx/public_html/new/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php on line 74

**Comment by asmecher** [comment]
@altafnagar, please have a look at our support forum (https://forum.pkp.sfu.ca), and if you don't see an answer to this issue there, post a new topic there. That's the best place to get help.
