### ISSUE TITLE
Import/Export plugin - SubmissionFiles lose doi data on import

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6839]
**Describe the bug**
The DOIs are not correctly exported/imported for submission files

**To Reproduce**
1. Try to export a submission file with doi

**What application are you using?**
 OJS, OMP or OPS version 3.3

**Comment by defstat** [comment]
@asmecher 

pkp-lib: #6840

**Comment by asmecher** [comment]
@defstat, should this be included in `stable-3_3_0` as well?

**Comment by asmecher** [comment]
I'm content to leave this for 3.4 unless we get specific requests to back-port.
