### ISSUE TITLE
Section Editor gets email with wrong template notification

### ISSUE THREAD

**Issue by lexfati** [pkp/pkp-lib#6846]
Hello!
version OJS 3.1.1.0 
After new submission - sending a notification email to journal section editor  with wrong template “Submission Ack” (email key SUBMISSION_ACK)
How to fix ? need change template to “Editorial Assignment” template
**Thanks in advance!**
Actual options:
![image](https://user-images.githubusercontent.com/26622770/110632272-79a8c000-81b8-11eb-96e0-94a468cc8fde.png)

**Comment by NateWr** [comment]
Hi @lexfati, unfortunately we are no longer providing bug fixes for 3.1.x. If you can upgrade to 3.3.x and reproduce this problem we can take a closer look.
