### ISSUE TITLE
Call to undefined method SubEditorsDAO::getBySectionId() in Series.inc.php:271

### ISSUE THREAD

**Issue by nongenti** [pkp/pkp-lib#6847]
**Describe the bug**
I work on a OMP version of the csl-plugin.
I tried to use the method getEditorsString() from the Series-class and got a php fatal error. The reason is the call to undefined method getBySectionId() in line 271.

**To Reproduce**
Use Series::getEditorsString().

**What application are you using?**
 OMP 3.3

**Additional information**
[https://github.com/pkp/omp/blob/3_3_0-3/classes/press/Series.inc.php#L271](https://github.com/pkp/omp/blob/3_3_0-3/classes/press/Series.inc.php#L271)

**Comment by NateWr** [comment]
Thanks for reporting @nongenti. The method name was changed in https://github.com/pkp/pkp-lib/commit/558220e1ff451fd37d271d291caabd023c3cc76a#diff-d0e7721d555e1401484f10b09458db9568e2ba2d6b2c90d3fa5baa676f0f6ce8L61 and it looks like we didn't get this updated.

PR:
https://github.com/pkp/omp/pull/943 (stable-3_3_0)

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `main`.
