### ISSUE TITLE
Data Privacy Option for Statistic Plugin

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#685]
Add the data privacy option to the statistic plugin:
-- the logged IP address shall be hashed with a daily randomly generated salt,
-- the user shall be informed about tracking,
-- there should be an opt-out possibility for the users.

**Comment by beghelli** [comment]
I reviewed the code already, but I think that Bozana is going to change one thing still right @bozana?

**Comment by bozana** [comment]
Yes, true, this change is coming end of this week...

**Comment by bozana** [comment]
@beghelli: I changed some things: The salt can now be saved in a file and the information for the users/readers is improved. Could you please review it too?

**Comment by asmecher** [comment]
@beghelli, it looks like this one was merged but not closed. If it is complete, please move back to 2.4.7 and close.

**Comment by beghelli** [comment]
Needs to forward port to master

**Comment by beghelli** [comment]
This is already integrated in both stable and master.
