### ISSUE TITLE
Move creator (author) management tools to API and new form structures

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6850]
Currently the author (contributor) forms in submission metadata use both the old Smarty-based forms toolset, and the old controller handler for CRUD operations.

Adapt the author forms to the new form toolset (see e.g. `lib/pkp/classes/components/forms/publication/PKPTitleAbstractForm.inc.php`) and implement CRUD operations using the API (see e.g. https://github.com/pkp/pkp-docs#generate-rest-api-references).

There is an existing mapping of author/creator metadata to the API in the publication `GET` endpoint; this can be used as an example.

(Note: this will affect the author requirements and ORCID plugins, so those will need to be adapted after this work is done.)

**Comment by NateWr** [comment]
I'd like to see the API endpoints added on to the end of the publication endpoint at: 

```/submissions/{submissionId}/publications/{publicationId}/contributors```

> There is an existing mapping of author/creator metadata to the API in the publication GET endpoint; this can be used as an example.

There's also a JSON schema that exists at [author.json](https://github.com/pkp/pkp-lib/blob/main/schemas/author.json), but this will need to be tested in more detail and may need additional validation rules applied.

**Comment by NateWr** [comment]
@defstat in addition to the work you're doing to move the author tools over, I'd also like you to migrate the AuthorService to the new repository/dao pattern. Here's a list of tasks to add, we can talk about them on our next pair programming session:

- [ ] Convert the DAO to extend `EntityDAO` and use type hints.
- [ ] Convert the `PKPAuthorService` to a repository .
- [ ] Convert `PKPAuthorService::getProperties()` to a Map that extends `PKP\core\maps\SchemaMap`. 
- [ ] Add any necessary methods to `PKPAuthorService` so that direct access to the DAO is not required.
- [ ] Refactor existing uses of `DAORegistry::getDAO('AuthorDAO')` to use the repository instead.

**Comment by defstat** [comment]
**PRs**
[pkp-lib]: #7211
[OJS]: https://github.com/pkp/ojs#3167

**Comment by NateWr** [comment]
Thanks @defstat, that looks really good. I've done a code review and left some minor comments. In addition to those, there are a couple more things:

1. It looks like you've removed all references to `Services::get('author')`. You can now remove `PKPAuthorService` as well as remove it from `OJSServiceProvider`.
2. I found a number of references remaining in the code to `AuthorDAO`. Can you do a search and refactor any remaining instances? There were a bunch in the [ORCID profile plugin](https://github.com/pkp/orcidProfile). Can you provide a PR for that?

**Comment by defstat** [comment]
Thanks @NateWr 

1. `PKPAuthorService` and `PKPAuthorQueryBuilder` removed
2. Removed `AuthorDAO` 
Waiting for the tests to finish.

1. Will prepare a PR for ORCID Plugin
1. Will prepare PRs for OMP, OPS

**Comment by defstat** [comment]
@NateWr @withanage I prepared a PR for OrcidProfile plugin 

**PR**
[OrcidProfile]: pkp/orcidProfile#185

**Comment by NateWr** [comment]
@asmecher I've reviewed the PRs above (https://github.com/pkp/pkp-lib/issues/6850#issuecomment-891312061) and left a few comments. If you get a chance, it would probably be a good idea for you to have a look over it, particularly the database interactions.

**Comment by asmecher** [comment]
:+1: Thanks, Nate -- I've had a look over it as well, @defstat. Getting very close.

**Comment by defstat** [comment]
@asmecher @NateWr 

I addressed the review changes. Tests are passing.

Check this [comment ](https://github.com/pkp/pkp-lib/pull/7211#discussion_r692007278) about the `getAuthors()` function

**Comment by asmecher** [comment]
Thanks, @defstat! I've added some more comments on the PR, and responded to the question about `getAuthors()`.

**Comment by asmecher** [comment]
@defstat, it looks good, but there are still a few comments needing to be reviewed -- once they are done, I'm content to have it resolved as is. Thanks!

**Comment by asmecher** [comment]
Thanks, @defstat! I've merged all the PRs listed above -- actually, cherry-picked due to merge requests. Tests are running fine-ish locally and I expect they'll come through OK on Travis. Thanks for all this work!

**Comment by asmecher** [comment]
There are still some outstanding details -- reopening at Dimitris' request.

**Comment by defstat** [comment]
@NateWr @asmecher 

Author Grid and new Author API Calls

**PRs**
OJS: pkp/ojs#3204
pkp-lib: #7376
ui-library: pkp/ui-library#167

![image](https://user-images.githubusercontent.com/560456/136828011-9f311f02-01a1-43ee-901b-5f6122d1c597.png)
![image](https://user-images.githubusercontent.com/560456/136828079-cf70aa61-e16f-4eb0-8aa6-95bbfd4bb1f8.png)

**Comment by defstat** [comment]
@NateWr @asmecher

I am copying the previous comment containing the PRs, in order to find it more easily. I also added all changes to a single commit (in all PRs) in order to "merge" changes from different review rounds that where referring to the same code part. 

In the meanwhile I will prepare the PRs for OMP and OPS. 

**PRs**
OJS: pkp/ojs#3204
pkp-lib: #7376
ui-library: pkp/ui-library#170

I think its ready for the a final review round

**Comment by NateWr** [comment]
Looks good! I've left some comments but it's mostly clean-up at this point. Nothing should effect OMP/OPS too much.

Thanks for squashing the commits! I really appreciate that. If you do it again, can you give the single commit a better name? Something like:

> pkp/pkp-lib#6850 Add contributors API and replace grid with ListPanel

**Comment by NateWr** [comment]
Oh, and I also found that the ORCID validation error needs something to work. Not something you introduced in your code, but now that we're using the schema it showed itself. Can you get this added?

```diff
diff --git a/classes/validation/ValidatorFactory.inc.php b/classes/validation/ValidatorFactory.inc.php
index c5134cb4d..457e82554 100644
--- a/classes/validation/ValidatorFactory.inc.php
+++ b/classes/validation/ValidatorFactory.inc.php
@@ -203,6 +203,7 @@ class ValidatorFactory
                 ],
                 'not_in' => __('validator.not_in'),
                 'numeric' => __('validator.numeric'),
+                'orcid' => __('user.orcid.orcidInvalid'),
                 'present' => __('validator.present'),
                 'regex' => __('validator.regex'),
                 'required' => __('validator.required'),
```

**Comment by defstat** [comment]
@NateWr I have added the final commits for your review.

**Comment by NateWr** [comment]
All PRs merged to `main`. :tada: 

There's one more thing that still needs to be fixed, but it's not causing a major issue so I wanted to get this merged before the winter break. @defstat if you could take care of this soon that'd be great: https://github.com/pkp/pkp-lib/issues/7561
