### ISSUE TITLE
Slim application error on submissions endpoint - multilingual journal

### ISSUE THREAD

**Issue by rodrigoesborges** [pkp/pkp-lib#6861]
**Describe the bug**

I am having an issue similar to [the one reported here](https://forum.pkp.sfu.ca/t/an-unexpected-error-occurred-please-reload-the-page-and-try-again-and-in-the-active-tab-always-loads/62825/3), with a multilingual journal setup with OJS.

**How to reproduce**
Sign in as admin
Click on the journal's submissions link - the submissions pane opens empty, even though the were submissions completed.

**My Setup**
Debian Buster, php 7.3 ; POSTGRES database; running from git 3.4; node 15.

**What application are you using?**
 OJS 3.4

**Additional information**

When I access my journal submissions page, I get an error message box:

>An unexpected error has occurred. Please reload the page and try again.

So after a lot of searching, I went to check if the api endpoint was working at _/journalname/api/v1/submissions_  . There I get:

> # Slim Application Error
> 
> A website error has occurred. Sorry for the temporary inconvenience.

Other endpoints, as issues or contexts, work well.

In my php error log, I have this that seems to be related:

    [error] 3363#3363: *23105 FastCGI sent in stderr: "PHP message: Slim Application Error:
    Type: Illuminate\Database\QueryException
    Code: 42703
    Message: SQLSTATE[42703]: Undefined column: 7 ERROR:  column &quot;locale&quot; does not exist
    LINE 1: select &quot;locale&quot; from &quot;submissions&quot; as &quot;s&quot; where &quot;s&quot;.&quot;submiss...
                   ^ (SQL: select &quot;locale&quot; from &quot;submissions&quot; as &quot;s&quot; where &quot;s&quot;.&quot;submission_id&quot; = 1 limit 1)
    File: /home/jname/domains/domain.jname.org/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php
    Line: 671
    Trace: #0 /home/jname/domains/domain.jname.org/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback('select "locale"...', Array, Object(Closure))
    #1 /home/jname/domains/domain.jname.org/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\Database\Conn" while reading response header from upstream, client: 177.235.11.42, server: domain.jname.org, request: "GET /jname/api/v1/submissions HTTP/1.1", upstream: "XXXXXX", host: "domain.jname.org"

I double checked with psql , the column *does not* exist in submissions table. 

I double checked charset configs, and have all set to utf8 in config.inc.php, database is UTF-8.

Not sure how could I investigate further. Any help appreciated.

**Comment by asmecher** [comment]
@rodrigoesborges, are you using the `main` branch from github? If so, that's unreleased code and likely to be buggy. I would recommend either installing from the `.tar.gz` package, or if you'd like to work with git, use the `stable-3_3_0` branch.

**Comment by NateWr** [comment]
> I double checked with psql , column exists in submissions table.

I'm sure you've checked and double-checked, but the error really does seem to be saying that the column `locale` does not exist on the `submissions` table. Is it possible that OJS is connected to a different database than you're looking at?

**Comment by rodrigoesborges** [comment]
@asmecher would it be safe to downgrade?

@NateWr , thanks for your reply. And you are totally right. The column does not exist in the database . I had issued the wrong query to check it (late at night, sorry). I will update the opening issue. Why would that column be missing then?

**Comment by asmecher** [comment]
@rodrigoesborges, we don't support downgrades; the upgrade scripts only go from older to newer, and as the `main` branch has not been released yet, we don't formally support it. There aren't huge differences between the 3.3.x releases and `main` yet, but you'll have to experiment.

**Comment by rodrigoesborges** [comment]
Ok I ended up starting from scratch. Probably the db upgrade from ~3.1 or ~3.2 directly to 3.4 did not complete correctly somehow.
Thanks for your patience and replies.
