### ISSUE TITLE
Upgrade Open Journal Systems

### ISSUE THREAD

**Issue by shahreahang** [pkp/pkp-lib#6864]
Hello,

I want to upgrade from version  3.1.1.4 to 3.3.0.4 but when i use php tools/upgrade.php upgrade i got this error :
ERROR: Upgrade failed: DB: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'apjcc1.email_templates_data' doesn't exist (SQL: UPDATE email_templates_data SET body=REPLACE(body, '{$submissionLayoutUrl}', '{$submissionUrl}'))

I follow instructions and now i don't know how to fix this ?

**Comment by asmecher** [comment]
@shahreahang, could you post your question on our support forum (if you don't already see an answer there)? That's the best place to get help.
https://forum.pkp.sfu.ca
