### ISSUE TITLE
SQL logic error in upgrade when using PostgreSQL

### ISSUE THREAD

**Issue by tgc** [pkp/pkp-lib#6870]
**Describe the bug**
There is a logic error in the PostgreSQL branch of the code in Installer::changeUserRolesAndStageAssignmentsForStagePermitSubmissionEdit.

After the upgrade every single entry in the stage_assignments table has can_change_metadata=1 instead of just the subset with the right role.

**To Reproduce**
We are upgrading from 3.1.1-4 to 3.2.1-3 and to reproduce we simply run the upgrade from the CLI.

**What application are you using?**
OJS 3.2.1-3

This bug however is present also on 3.3 and main branch.

**Additional information**
The issue stems from the differences between mysql and postgresql syntax when using joins as part of an UPDATE.

This statement is not equivlant to the MySQL branch of the same:
```
UPDATE stage_assignments SET can_change_metadata=1 FROM stage_assignments sa JOIN user_groups ug ON (sa.user_group_id = ug.user_group_id) WHERE ug.role_id IN ' . $roleString
```
I think the problem is that the 'stage_assignments' in the UPDATE part, becomes disconnected from the 'stage_assigments' table in the FROM part because there it is named as 'sa'.

I believe the correct PostgreSQL syntax equivalent to what is used for MySQL is this:
```
UPDATE stage_assignments sa SET can_change_metadata=1 FROM user_groups ug WHERE sa.user_group_id = ug.user_group_id AND ug.role_id IN ' . $roleString
```

With this statement only a subset of entries end up with can_change_metadata = 1.

Here is the explain output for the broken statement:
```
ojs3_stage=# explain UPDATE stage_assignments SET can_change_metadata=1 FROM stage_assignments sa JOIN user_groups ug ON (sa.user_group_id = ug.user_group_id) WHERE ug.role_id IN (16);
                                                    QUERY PLAN                                                     
-------------------------------------------------------------------------------------------------------------------
 Update on stage_assignments  (cost=91.62..53060623.11 rows=4244039242 width=62)
   ->  Nested Loop  (cost=91.62..53060623.11 rows=4244039242 width=62)
         ->  Seq Scan on stage_assignments  (cost=0.00..4451.26 rows=155126 width=48)
         ->  Materialize  (cost=91.62..5087.32 rows=27359 width=12)
               ->  Hash Join  (cost=91.62..4950.53 rows=27359 width=12)
                     Hash Cond: (sa.user_group_id = ug.user_group_id)
                     ->  Seq Scan on stage_assignments sa  (cost=0.00..4451.26 rows=155126 width=14)
                     ->  Hash  (cost=83.09..83.09 rows=682 width=14)
                           ->  Bitmap Heap Scan on user_groups ug  (cost=17.57..83.09 rows=682 width=14)
                                 Recheck Cond: (role_id = 16)
                                 ->  Bitmap Index Scan on user_groups_role_id  (cost=0.00..17.40 rows=682 width=0)
                                       Index Cond: (role_id = 16)
(12 rows)
```
The smoking gun is that it creates a nested loop.

Here is explain output for the rewritten statement:
```
ojs3_stage=# explain UPDATE stage_assignments sa SET can_change_metadata=1 FROM user_groups ug WHERE sa.user_group_id = ug.user_group_id AND ug.role_id IN (16);
                                              QUERY PLAN                                               
-------------------------------------------------------------------------------------------------------
 Update on stage_assignments sa  (cost=91.62..4950.53 rows=27359 width=56)
   ->  Hash Join  (cost=91.62..4950.53 rows=27359 width=56)
         Hash Cond: (sa.user_group_id = ug.user_group_id)
         ->  Seq Scan on stage_assignments sa  (cost=0.00..4451.26 rows=155126 width=48)
         ->  Hash  (cost=83.09..83.09 rows=682 width=14)
               ->  Bitmap Heap Scan on user_groups ug  (cost=17.57..83.09 rows=682 width=14)
                     Recheck Cond: (role_id = 16)
                     ->  Bitmap Index Scan on user_groups_role_id  (cost=0.00..17.40 rows=682 width=0)
                           Index Cond: (role_id = 16)
(9 rows)
```
This is straight forward as expected, no nested loop.

Besides fixing a bug it also cuts our upgrade runtime by an hour.

**Comment by NateWr** [comment]
Hi @tgc, thanks for the good bug report. I was able to run your suggested queries and it does look like there's an issue in postgres. The postgres query was introduced to resolve some compatiblity issues in https://github.com/pkp/ojs/commit/dbf319e8ffce87d447a3a57dad6c398e1705fca3, so I'm going to leave this for @asmecher to look at more closely.

**Comment by asmecher** [comment]
@tgc, thanks for catching this -- could you open a pull request including the proposed change?

**Comment by tgc** [comment]
Done. See https://github.com/pkp/ojs/pull/3080
Should apply to 3.2 and 3.3 branches as well.

**Comment by NateWr** [comment]
Thanks @tgc, I've merged that to `main` and cherry-picked to `stable-3_3_1` and `stable-3_3_0` for both OJS and OMP. OPS did not have the upgrade code.
