### ISSUE TITLE
[OJS] remove commercial URL from config.TEMPLATE.inc.php

### ISSUE THREAD

**Issue by AndrewGearhart** [pkp/pkp-lib#6874]
We should replace myurl.com urls with IETF compliant URLs that won't cause confusion if errors occur in the config.inc.php such as example.com or www.journalname.example

**Comment by NateWr** [comment]
Sounds like a good idea. Would you be willing to make a PR with this change?

**Comment by asmecher** [comment]
PR: https://github.com/pkp/ojs/pull/3154

@AndrewGearhart, would you mind opening similar PRs for the OMP and OPS repos too? Or I can do it if you're busy!

**Comment by AndrewGearhart** [comment]
Can do. :)

**Comment by asmecher** [comment]
Perfect, thanks!

**Comment by AndrewGearhart** [comment]
@asmecher 
OMP PR: https://github.com/pkp/omp/pull/985
OPS PR: https://github.com/pkp/ops/pull/164

**Comment by asmecher** [comment]
That's perfect -- thanks, @AndrewGearhart!
