### ISSUE TITLE
[Plugin][Portico] Integration with other providers

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6876]
Since exporting JATS content seems be useful for other archiving providers, it might be interesting (I have one case 😁) to rename the plugin to something more generic and allow the user to:
- Enter more credentials (in case he needs to export to more than one place)
- Setup the file format with variables (e.g. "%acronym%-%volume%-%date%")
- Setup the FTP base path

Perhaps it's better to have a custom export "walker" for each provider (in case they have too different expectations).

**Comment by asmecher** [comment]
This is already implemented per https://github.com/asmecher/portico/commit/89fee48568cf67b1522da3a94decdf6985784cb3.
