### ISSUE TITLE
site settings not visible for usage statistics plugin when only one context exists

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6879]
**Describe the bug**
When only one context exists, the tab Plugins under Administration > Site Settings is not visible and the usage statistics plugin settings under the context Website Settings > Plugins do not contain the site settings, only context settings. Thus the admin can not set the site settings.

**To Reproduce**
When only one context exists, as admin
1. Go to Website Settings > Plugins > Usage Statistics > Settings
2. See no plugin site settings (e.g. access log options, archives, data privacy)

**What application are you using?**
 OJS, OMP or OPS version 3.3.0-4

**Additional information**
(just a note that the usage statistics plugin is a site-wide plugin, i.e. it can only be enabled and set by admin)

**Comment by bozana** [comment]
PRs:

stable-3_3_0:
usageStats: https://github.com/pkp/usageStats/pull/45
ojs: https://github.com/pkp/ojs/pull/3081 (only submodule update)
omp:
ops:

master:
usageStats:
ojs:
omp:
ops:

**Comment by bozana** [comment]
@NateWr, could you take a look at the PR?
If OK I would provide the other PRs, for other applications and master branch...

**Comment by NateWr** [comment]
Are we sure that all of the settings that exist at the admin level should be available to the journal manager? Some of the settings available from the admin plugins list might be meant for only admins. I can't remember, but just checking. I think what we want is for the admin plugins list to be available, right?

**Comment by bozana** [comment]
The journal manager will never see the site-wide plugins, thus this one neither.
Thus, I think i.e. it seems that that was the idea when having only one context not to show the admin plugins list at all, but have everything at that one place.
(The specifics of this plugin are that there are options/settings that can differ for each context. So if there are several context, admin will be able to set the plugin (especially those general options like access log options, archives, data privacy) in the same way for all contexts in the admin plugins list, and admin will be able to set the context specific options like the statistics display in the context plugins list.)
I am not sure how other site-wide plugins work when several contexts are there... I could check...

**Comment by NateWr** [comment]
Ok, I see what you're saying. Yeah, let's go ahead with this approach.
