### ISSUE TITLE
QuickSubmit Plugin doesn't create article publication dates

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#688]
There's an outstanding issue where folks are trying to register something for CrossRef and they hit an error about publication date. If articles were submitted via quicksubmit plugin, article publication dates aren't included in the metadata.

**Comment by mfelczak** [comment]
@AhemNason, does this apply to both OJS 2.4.8 as well as OJS 3.1?

**Comment by AhemNason** [comment]
I'm actually unsure about 3.1. I can check in the next day or two. When I wrote this, it was related to 2.4.8. It used to be a big issue for Crossref export but I think now we just don't use the dates the same way.

**Comment by mfelczak** [comment]
@AhemNason, does this still apply to OJS 3.1+?

**Comment by AhemNason** [comment]
Nope!
