### ISSUE TITLE
Double forward slashes ("//") on URL returned from Dispatcher

### ISSUE THREAD

**Issue by BiatrizAlb** [pkp/pkp-lib#6881]
When we use the `lib.pkp.classes.handler.PKPHandler.getDispatcher()`  method to obtain the base URI of the application, it returns double forward slashes in the URI. The [RFC of the URI is clear](https://tools.ietf.org/html/rfc4395) in pointing out that "//" are only allowed in the schema part (https: //, ftp: //). 

**Implementation:** 
`$request->getDispatcher()->url($request, ROUTE_COMPONENT) `.

**Example of return:**
```
[Fri Mar 19 16:33:01 2021] http://localhost:8080/index.php/revista-libras/$$$call$$$//
```
**Application:**
 OJS 3.3.

**Comment by NateWr** [comment]
HI @BiatrizAlb, can you reproduce this problem when calling an actual component? The URL example doesn't go to anywhere in the OJS system. It requires a component and op name after `/$$$call$$$/`. So any URL using this syntax in OJS would need to be, at a minimum, `/$$$call$$$/<component>/<op>`.

**Comment by NateWr** [comment]
Our docs have a more detailed explanation of these [controller routes](https://docs.pkp.sfu.ca/dev/documentation/en/architecture-routes#controller-routes).

**Comment by asmecher** [comment]
I think this is a custom code issue, so closing it -- but if you think it's a bug in the software, please add details.
