### ISSUE TITLE
[OJS] Publisher Library doesn't load in Firefox (3.2 and 3.3)

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/pkp-lib#6884]
When I try accessing the Publisher Library on instances of OJS 3.2. and 3.3 using Firefox for PC (my main browser), the page gets stuck showing that it's loading. However, when I try access the Publisher Library in these same instances using Chrome, the pages load and I am able to view the file libraries.

**Comment by NateWr** [comment]
Hi @tmrozewski-york, I was unable to reproduce this using Firefox for Linux (I don't have a PC to test). Can you try to clear your cache in the browser and try again to see if the problem is still there?

**Comment by tmrozewski-york** [comment]
That didn't do it but I then cycled through my add-ons and it turns out that AdBlocker causes the interference. Sorry I didn't think of that before reporting!


Tomasz Mrozewski (he/him)

Digital Publishing Librarian


***@***.******@***.***> | yorku.ca<http://www.yorku.ca/>

https://orcid.org/0000-0001-7423-4465

Use https://calendly.com/ydj/ to see my availability for meetings and to book me.


York University Libraries | YORK UNIVERSITY

Digital Scholarship Centre, Scott Library 205

4700 Keele Street Toronto ON, Canada M3J 1P3

[https://docs.google.com/uc?export=download&id=1dNOGR0DtofiU3os3IYQ8vnrwn4F7p2qH&revid=0B5KeYmFKLLIPQVpSd2F0RVVlYUdvVnM1Z1huUzNSTFFtY2Q0PQ][X]

Ranked 33rd in the World in the

Times Higher Education 2020 Impact Rankings

Out of respect and care for library staff and for our community, York University Libraries have reduced in-person services until further notice. For updated information and details about our online and other services, see https://www.library.yorku.ca/web/covid-19-york-libraries-services-and-operations-update/.

We recognize that many Indigenous Nations have longstanding relationships with the territories upon which York University campuses are located that precede the establishment of York University. York University acknowledges its presence on the traditional territory of many Indigenous Nations. The area known as Tkaronto has been care taken by the Anishinabek Nation, the Haudenosaunee Confederacy, and the Huron-Wendat. It is now home to many First Nation, Inuit and Métis communities. We acknowledge the current treaty holders, the Mississaugas of the Credit First Nation. This territory is subject of the Dish with One Spoon Wampum Belt Covenant, an agreement to peaceably share and care for the Great Lakes region.

This electronic mail (e-mail), including any attachments, is intended only for the recipient(s) to whom it is addressed and may contain information that is privileged, confidential and/or exempt from disclosure. No waiver of privilege, confidentiality or any other protection is intended by virtue of its communication by the internet. Any unauthorized use, dissemination or copying is strictly prohibited. If you have received this e-mail in error, or are not named as a recipient, please immediately notify the sender and destroy all copies of it.

________________________________

**Comment by asmecher** [comment]
Not a problem!
