### ISSUE TITLE
UsageStats README is outdated

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#6885]
**Describe the bug**
Instructions for usageStats plugin are outdated:
https://github.com/pkp/usageStats/blob/main/README

- Installation instructions are partial.
- The link to geoLiteCite is broken (and I'm unsure if is need any more).

Make sense to link installation instructions section to documentation?
https://docs.pkp.sfu.ca/admin-guide/en/statistics#appendix-c-processing-log-files

**Comment by asmecher** [comment]
See also: https://github.com/pkp/pkp-lib/issues/1833

**Comment by asmecher** [comment]
Closing in favour of https://github.com/pkp/pkp-lib/issues/6895, which will fix/rewrite the underlying geolocation problem.
