### ISSUE TITLE
[OJS] issue with orcid id formatting in crossref export

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#689]
As per [this forum discussion](http://forum.pkp.sfu.ca/t/problems-with-the-doi-crossref-automatic-registration/3437/3), it seems like there's an issue with the way the CrossRef plugin is pulling in orcid IDs? The most relevant part of the error is this: 

> Value 'https:\/\/orcid.org\/0000-0002-6281-9981' is not facet-valid with respect to pattern 'http:\/\/orcid.org\/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[X0-9]{1}|http:\/\/orcid.org\/[0-9]{15}[X0-9]{1}' for type 'orcid_t'. Error: cvc-complex-type.2.2: Element 'ORCID' must have no element [children], and the value must be valid."

It sounds like the user has the rest of their content handled properly.

**Comment by asmecher** [comment]
See this thread: http://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=13004
