### ISSUE TITLE
OMP Allow easier ISBN editing in Publication Formats

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#6893]
**Describe the problem you would like to solve**
The most common piece of metadata in Publication Formats is the ISBN. At the moment adding an ISBN requires a very complicated workflow where you first add the publication format, then edit it, move to the metadata tab and add the ISBN from a selection of different identifiers. Most of the metadata editable here is ONIX related and publishers probably do not edit it so often.

We need a more fluent workflow for adding ISBN's while they are so central in Book metadata.

**Describe the solution you'd like**
Add an ISBN field to the Publication format metadata form. Automatically recognise if the ISBN is ISBN-10 or ISBN-13. The ISBN field would still be editable also from within the Metadata tab.

**Who is asking for this feature?**
Book publishers

**Additional information**
<img width="715" alt="Screenshot 2021-03-30 at 10 52 21" src="https://user-images.githubusercontent.com/16347527/112953286-086c8500-9146-11eb-93b8-4e6dc2cc6c30.png">

**Comment by ajnyga** [comment]
@NateWr Could not figure a way of doing this with a single field. It was easy to check the length of the ISBN when it was being stored. But the user will expect that emptying the text field and saving the form will delete the ISBN and this was difficult to handle with a single ISBN field while there are two possible ISBN types, ISBN10 and ISBN13.

So instead I chose to show both fields side by side.

Also saving and editing this through the form was not that straigtforward, but I think I have a fairly clean solution here.

OMP: https://github.com/pkp/omp/pull/953

**Comment by NateWr** [comment]
All merged! Thanks @ajnyga!

@amandastevens and @kaitlinnewson this may effect documentation (for 3.4). See the screenshot in @ajnyga's second comment.
