### ISSUE TITLE
OMP allow selection of files when adding a new chapter

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#6894]
**Describe the problem you would like to solve**
Currently Chapter files can only be selected by first creating the chapter and the returning to edit the chapter again. This is an unnecessary extra step and makes adding chapters a lot slower.

**Describe the solution you'd like**
Allow users to select chapter files when adding the chapter for the first time.

**Who is asking for this feature?**
Book publishers

**Comment by ajnyga** [comment]
omp: https://github.com/pkp/omp/pull/952

ping @NateWr can you check and review this. This was easier than I thought and thinking I might have missed something.

**Comment by NateWr** [comment]
Merged to `main`. Thanks @ajnyga!
