### ISSUE TITLE
Upgrad ojs from 3.1.2.4 to 3.3.0.4

### ISSUE THREAD

**Issue by Eliasssaber** [pkp/pkp-lib#6896]
upgrad ojs from 3.1.2.4 to 3.3.0.4

Errors occurred during installation :

A database error has occurred: SQLSTATE[42S21]: Column already exists: 1060 Nom du champ 'email_id' déjà utilisé (SQL: ALTER TABLE email_templates_data ADD email_id BIGINT)

![upgrade ojs from 3 1 2 4 to 3 3 0 4](https://user-images.githubusercontent.com/77052557/113051062-798b5700-919d-11eb-9205-cd46498cd68a.JPG)

**Comment by asmecher** [comment]
Cross posted: https://forum.pkp.sfu.ca/t/upgrade-ojs-from-3-1-2-4-to-3-3-0-4/66791
It's best to use the forum, and to only post an issue in once place. Otherwise it's hard to keep our resources organized.
