### ISSUE TITLE
Editorial Activity email is sometimes attributed to a regular user

### ISSUE THREAD

**Issue by aukondk** [pkp/pkp-lib#6899]
**Describe the bug**
Sometimes the Editorial Activity email is attributed to a regular user (presumably the user who loaded the page that triggered the scheduled task). The signature is that of the primary contact but the name in the header is the user.

**To Reproduce**
Don't know how to reproduce but it has happened twice now. January and March this year.

**What application are you using?**
 OJS version 3.2.1.0

**Additional information**
Also had an issue where the report for February was sent twice. Once on the 1st March and the second on 29th March. The 29th date suggests something to do with leap years(?)

**Comment by NateWr** [comment]
Hi @aukondk, do you know how the scheduled tasks are run? Do you have a cron job set up on the server or do you use the Acron plugin?

**Comment by aukondk** [comment]
Acron is enabled and I haven't set up a cron task on the server. 
The name of the user in the mail header also made a submission shortly afterwards so they would have been using the site at the time. I assume they triggered the scheduled task with a page load.

**Comment by NateWr** [comment]
@asmecher does this sound like the likely culprit? If `$request->getUser()` is called in a scheduled task, it will presumably be the wrong user?

**Comment by asmecher** [comment]
Yes, the acron plugin and a `$request->getUser()` call is a likely cause. This is a gotcha for coders that will need to be solved long term, I think -- by getting rid of "global" style calls in favour of more comprehensive passing around of the `$request` object, and then if we continue to use an Acron-style plugin for queue handling, we can ensure that it passes around a mock `$request` object that does not include a current user (to bring it in line with cron-based execution).

**Comment by asmecher** [comment]
@aukondk, what specific editorial activity (log entry) shows the wrong user? Are the two cases the same type of event?

**Comment by aukondk** [comment]
@asmecher This was the email of the Editorial Activity statistics report that gets sent every month.
Since this instance has been running, all but two had the correct name (the primary contact) in the header.

**Comment by NateWr** [comment]
> The signature is that of the primary contact but the name in the header is the user.

Can you explain what you mean by the header? Is this the FROM or REPLY-TO header in the email?

**Comment by aukondk** [comment]
> Can you explain what you mean by the header? Is this the FROM or REPLY-TO header in the email?

Both. In fact I'm seeing now, looking at the raw email, that in Reply-to there is both the user and the principal contact.
```
From: {user full name} via {context name} <{noreplyaddress}>
Reply-To: {user full name} <{user email}>, {primary contact name} <{primary contact email}>
```

**Comment by NateWr** [comment]
Hmm, strange. I can't find anywhere that the current user might be added to the REPLY-TO:

https://github.com/pkp/pkp-lib/blob/main/classes/notification/PKPNotificationOperationManager.inc.php#L374-L378

But it looks like there's some special handling related to DMARC and REPLY-TO:

https://github.com/pkp/pkp-lib/blob/main/classes/mail/Mail.inc.php#L534-L565

@asmecher is there any chance the DMARC stuff is at play here?

**Comment by asmecher** [comment]
@aukondk, thanks, identifying the problem email is helpful. I suspect you're using the Acron plugin to trigger scheduled tasks (rather than a cron job and tools/runScheduledTasks.php). You should be able to resolve it by applying:

https://github.com/pkp/pkp-lib/pull/7184

If you can confirm that this behaves as expected, I can commit it for the next release!

**Comment by aukondk** [comment]
> If you can confirm that this behaves as expected, I can commit it for the next release!

Yes this appears to work. Thanks!

**Comment by asmecher** [comment]
Thanks! Merged to `stable-3_3_0`, `stable-3_3_1`, and `main`.
