### ISSUE TITLE
force_login_ssl setting should not allow HTTPS form on HTTP page

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#690]
My security folks are griping about this, and they are right:
http://blogs.msdn.com/b/ie/archive/2005/04/20/410240.aspx
(see Critical Mistake 1)

With the force_login_ssl setting, the login form should not be presented over HTTP, even if the form's target is HTTPS.

**Comment by asmecher** [comment]
Agreed, good spotting.

**Comment by asmecher** [comment]
Merged and cherry-picked, thanks!
