### ISSUE TITLE
Error modifying email template

### ISSUE THREAD

**Issue by leolucena22** [pkp/pkp-lib#6908]
When editing an email template in OMP, version: 3.3.0.4, I get the following error.

![image](https://user-images.githubusercontent.com/53834464/113476960-30652c80-9455-11eb-8c02-4427b9d29c2d.png)

**Comment by asmecher** [comment]
@leolucena22, please post your question on the support forum at https://forum.pkp.sfu.ca -- that's the best place to get technical support. Include your OJS version and any relevant messages from your PHP error log.
