### ISSUE TITLE
mEDRA: the calculation of the file size is different for issue and article galleys

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6909]
**Describe the bug**
When exporting issue as manifestation using mEDRA plugin an error occurs. S. https://forum.pkp.sfu.ca/t/ojs-3-3-0-4-medra-plugin-show-fatal-error/66847.

**To Reproduce**
...

**What application are you using?**
 OJS version 3.3.0-4

**Additional information**
-

**Comment by bozana** [comment]
PR: https://github.com/pkp/medra/pull/2

**Comment by bozana** [comment]
@NateWr, could you please take a look at the PR -- just to be sure the file size calculation is supposed to be so...

**Comment by NateWr** [comment]
Looks good, @bozana!

**Comment by asmecher** [comment]
(This isn't actually distributed with OJS anymore, but deferring to the 3.3.0-6 milestone so it's not forgotten.)

**Comment by bozana** [comment]
merged and released + updated the plugins.xml
