### ISSUE TITLE
Use proper identification when issuing HTTP requests

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6910]
When issuing HTTP requests, OJS is presenting itself using the default `GuzzleHttp` agent (e.g. `GuzzleHttp/6.5.5 curl/7.64.0 PHP/7.2.31`).

I think we should recover the previous behavior, at least partially, when OJS presented itself as `ojs2/3.2.1.1`, that will help externals tools to extract some meaningful statistics.

**Comment by asmecher** [comment]
It looks like the default headers were being provided to Guzzle in a 5.3-friendly manner, but we're using Guzzle 6.5. This affects OJS 3.3.0-0 to 3.3.0-4 (thus we can assume anything mentioning Guzzle in the user agent is 3.3.0).

**Comment by jonasraoni** [comment]
Thanks @asmecher for inspecting when it was introduced.
Also, perhaps the user agent of OJS should be updated from `ojs2/3.3.0.3` to `ojs/3.3.0.3`?

**Comment by asmecher** [comment]
The `ojs2` comes from the application's self-identification and is tricky to change; I don't think we're likely to prioritize it. See e.g.: https://github.com/pkp/pkp-lib/issues/3030
