### ISSUE TITLE
[OJS] CC buttons not displaying (broken URLs)

### ISSUE THREAD

**Issue by melat0nin** [pkp/pkp-lib#6911]
The embedded CC URLs in OJS (3.3.0) are no longer valid. Calls to `i.creativecommons.org` images are being redirected to `licensebuttons.net`, but this doesn't resolve without `www.` at the beginning.

**Comment by asmecher** [comment]
Was this maybe resolved already? The `i.creativecommons.org` URLs appear to work for me, and they are still used e.g. at https://creativecommons.org/choose/results-one.

**Comment by melat0nin** [comment]
Yes indeed, I must have caught them as they were migrating domains. Will close this.
