### ISSUE TITLE
[OMP] Spotlight autocomplete layout broken

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#6916]
The autocomplete suggestions in the OMP Spotlight form has a broken layout. This is caused by the inline setting in the form elements. Also, the suggestions include unnecessary labels like "MONOGRAPH" which you can select but will cause an error when used.

The inline setting from the form fields should be removed together with the unnecessary labels.

**Comment by ajnyga** [comment]
OMP: https://github.com/pkp/omp/pull/955

**Comment by NateWr** [comment]
Merged, thanks @ajnyga!
