### ISSUE TITLE
Usage stats: error when executing migration UsageStatsMigration

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6920]
**Describe the bug**
When trying to install OPS from the `main` branch, using the `main` branch of the usageStats plugin, the installation fails with the following error:

```
Error executing the migration class <tt>UsageStatsMigration</tt>.
```

The Exception's error message is:

```
SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "usage_stats_temporary_records" already exists (SQL: create table "usage_stats_temporary_records" ("assoc_id" bigint not null, "assoc_type" bigint not null, "representation_id" bigint null, "day" bigint not null, "entry_time" bigint not null, "metric" bigint not null default '1', "country_id" varchar(2) null, "region" varchar(2) null, "city" varchar(255) null, "load_id" varchar(255) not null, "file_type" smallint null))
```

**To Reproduce**
1. Edit the following line of `Plugin.inc.php` to display the exception error message:

```
$installer->setError(INSTALLER_ERROR_DB, __('installer.installMigrationError', ['class' => get_class($migration)]));
```

Add the following line after this:

```
$installer->setError(INSTALLER_ERROR_DB, __('installer.installMigrationError', ['class' => get_class($migration)]));
error_log($e->getMessage());
```

2. Try to install OPS from the `main` branch.
3. See error in log.

**What application are you using?**
OPS `main` branch (pre-3.4)

**Comment by NateWr** [comment]
@bozana would you be able to investigate this when you have a minute? It's not urgent.

**Comment by bozana** [comment]
@NateWr, I've just tried to install the OPS anew and I can do it :thinking: 
I removed my old DB and created it anew.
I took the main branch of the ops, pkp-lib and usageStats plugin.
I changed the installe = Off in config.inc.php.
I called the ops web site and install it manually there without a problem.

Thus, I am wondering if you maybe already had that table in the DB when doing the installation?
Do you maybe have an idea how else I could/should test it?
Thanks!

**Comment by NateWr** [comment]
Hmm, I've tried again with the same error. I'll look into it later, thanks for checking!

**Comment by asmecher** [comment]
@NateWr, I ran into this once myself with OMP but the problem seemed to go away once I did some general cleanup (updated all submodules to latest `main`, reinstalled Composer dependencies, rebuilt JS, etc).
