### ISSUE TITLE
Set default user for CLI tool

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6925]
**Describe the problem you would like to solve**
There are times where the CLI tools need access to a Request dependent resource (like an API call), but the CLI Tool does not define a user at the Request level 

**Describe the solution you'd like**
We could search the CLI command for a username and if none provided we could add an admin user as default

**Comment by defstat** [comment]
@NateWr @asmecher 

see also [that](https://github.com/pkp/pkp-lib/pull/6491/files#r558640851)

**PRs**
[pkp-lib]: #6926
[OJS]: pkp/ojs#3099

**Comment by NateWr** [comment]
Both merged to `main`. @asmecher there are no plans to backport this, right?

**Comment by asmecher** [comment]
No, just for `main` is fine with me.
