### ISSUE TITLE
Quicksubmit cover image preview is broken

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#6927]
**Describe the bug**
When adding a Cover image for an article in Quicksubmit plugin no preview of the added image is visible although the code suggests that it should be visible. Also, there is no way of deleting an already added cover image.

The cover image is saved correctly to the database and the file system. Just the js handling the preview is broken.

**To Reproduce**
1. Go to Quicksubmit
2. Add a cover image
3. No feedback or errors visible but also the preview of the cover is hidden

**What application are you using?**
Quicksubmit plugin for OJS3.3.

---
**PRs**

**Branch `main`**
QuickSubmit: pkp/quickSubmit#62

**Comment by asmecher** [comment]
@defstat, following today's meeting: this isn't as closely related to https://github.com/pkp/pkp-lib/issues/7792 as I remembered, but anyway.

**Comment by defstat** [comment]
@asmecher a PR for that is added [here](https://github.com/pkp/pkp-lib/issues/6927#issue-852575891).

Fixes:
1. Uploaded image was not shown
2. Uploaded image alt text was not added to as parameter of the `img` tag
3. Deletion of uploaded image was failing
4. Uploaded image alt text could not be edited after initial upload

**Comment by asmecher** [comment]
Thanks, @defstat!
