### ISSUE TITLE
[OJS] Recurring use of function name __() in Laravel helper file and PKPLocale file

### ISSUE THREAD

**Issue by TheMechanicalButterfly** [pkp/pkp-lib#6937]
After local installation for development purposes, the OJS installation cannot start due to the following problem:

```
PHP Fatal error:  Cannot redeclare __() (previously declared in {installation root}\lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:893) in {installation root}\lib\pkp\classes\i18n\PKPLocale.inc.php on line 924
```
It looks like the Laravel installation uses a helper function `__()` which then conflicts with the similarly named function in `PKPLocale.inc.php`.

The problem occurred with the `main` branch as well as with the stable 3.3.1 branch, under PHP 7.3.27 as well as under PHP 8.0.0, all in a WAMP setup.

Removing the function from the Laravel helper file solves the problem temporarily but is of course no sustainable solution, as changes to the vendor files will be overwritten with the next vendor package update via composer.

**Comment by asmecher** [comment]
@TheMechanicalButterfly, there is a patch described in `lib/pkp/composer.json` that resolves the collision. It should have been applied automatically by Composer. (Future work on this is described at https://github.com/pkp/pkp-lib/issues/6328.)

**Comment by TheMechanicalButterfly** [comment]
@asmecher 

Yes, seen it now. The patches are not applied, though. When running, e.g.,  ` composer --working-dir=lib/pkp install`, what I get is:

```
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing moxiecode/plupload (v2.3.7): Extracting archive
  - Installing laravel/framework (v7.30.4): Extracting archive
  - Applying patches for moxiecode/plupload
    lib/safen-plupload-example-6888.diff (Make plupload example safe)
   Could not apply patch! Skipping. The error was: Cannot apply patch lib/safen-plupload-example-6888.diff

  - Applying patches for laravel/framework
    lib/laravel-helper-4017.diff (Inhibit __ Laravel helper)
   Could not apply patch! Skipping. The error was: Cannot apply patch lib/laravel-helper-4017.diff
```
Unfortunately no further details on why the patches can't be applied. Composer version is 2.0.8.

**Comment by TheMechanicalButterfly** [comment]
@asmecher 

Looks like it's a problem with the Windows environment. On the Windows Command Prompt and in Windows PowerShell patch application fails.

Running the same through composer in git bash applies at least the Laravel patch without error:

```
Gathering patches for dependencies. This might take a minute.
  - Installing moxiecode/plupload (v2.3.7): Extracting archive
  - Installing laravel/framework (v7.30.4): Extracting archive
  - Applying patches for moxiecode/plupload
    lib/safen-plupload-example-6888.diff (Make plupload example safe)
   Could not apply patch! Skipping. The error was: Cannot apply patch lib/safen-plupload-example-6888.diff

  - Applying patches for laravel/framework
    lib/laravel-helper-4017.diff (Inhibit __ Laravel helper)

Generating autoload files
```

I suppose it's not worth the time trying to cover all possible environments in which these patches could to be applied. 

I'll make a note for our documentation for now, that should be fine. https://github.com/pkp/pkp-lib/issues/6328 will hopefully make this particular problem redundant at some point.

**Comment by asmecher** [comment]
I think you'll just need to install the GNU `patch` tool somewhere in your path and it'll work for Windows environments -- but if you're able to confirm that would be helpful!

**Comment by TheMechanicalButterfly** [comment]
@asmecher 

Confirmed, it works with GNU Patch as expected via the Windows PowerShell. (One needs to execute the shell as admin, took me a few trials to figure that out.)

Many thanks!
