### ISSUE TITLE
Email templates can not be saved because of data from disabled locales

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6938]
**Describe the bug**
When a site has been configured to support several languages, but a journal only supports some of them, a default email template can not be customized. This happens because all localized data for that template is returned with the email template object, and this causes the form validation to expect input in unsupported languages.

See [forum report](https://forum.pkp.sfu.ca/t/ojs-3-3-0-3-error-when-saving-email-template/66840/2).

**To Reproduce**
1. Go to Admin > Site Settings > Setup > Languages and enable three languages (it can be any three, but I used `en_US`, `fr_CA`, `pt_BR`). You may need to install a new locale.
2. Go to a journal's settings at Settings > Workflow > Emails > Email Templates.
3. Try to edit a default email template (eg - Article Review Request).
4. In the Edit form, click on the red globe icon and it will say something like 3/2 languages completed.
5. Click the save button and see the error.
6. Click the link to "jump to an error" and it will try to open a form for an unsupported language. You will see an empty space on the right of the form.

**What application are you using?**
3.3.0-3

**Additional information**
@asmecher I can think of a couple ways to deal with this:

1. In `EmailTemplateDAO`, override the `_fromRow` method to ensure that only the right locale information is retrieved. Upsides are that this would only load the correct data depending on the context. However, it will be challenging to ensure that the correct locales for each context are passed into the `_fromRow` method. And we'll be duplicating code in the `SchemaDAO::_fromRow`.
2. In the `EmailTemplateService::getProperties`, pass in the desired locales and strip out other locale data. Upside is that this will be much easier to control. The downside is that it only occurs at the point where we map the object to JSON for the API. The other locale data will still exist in the `DataObject` when retrieved from the database.

Do you have a preference or an alternative? I'm leaning towards the second method, especially because it is the least disruptive for a 3.3.0-x release and doesn't involve tampering with the "guts" of the Schema/DataObject system.

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `stable-3_3_1` and `main`.

**Comment by NateWr** [comment]
A couple people have asked ([1](https://github.com/pkp/ui-library/commit/1771b3e302c2d25aba090e30fb29a343740d16f5#commitcomment-49853206), [2](https://forum.pkp.sfu.ca/t/after-upgrade-to-ojs-3-2-1-3-orcid-plugin-producing-fatal-error/65473/35?u=natewr)) how to apply this fix manually rather than wait for the next release (3.3.0-6):

> Unfortunately this change requires that the JavaScript package is rebuilt from the source. If you have installed OJS from a release package you won't find this file.
> 
> In order to apply this update, you'll need to check out OJS's git repository, switch to the stable-3_3_0 branch, update the submodules, rebuild the JS package, and use it to replace your existing js/build.js file.
> 
> You can learn more about working from the git repository in our [developer documentation](https://docs.pkp.sfu.ca/dev/documentation/en/getting-started). The main difference is that you'll want to be working from the `stable-3_3_0` branch instead of the `main` branch, for OJS and the pkp-lib / ui-library submodules.

**Comment by rsauls** [comment]
We are on 3.3.0.5 and had this same issue.   A temporary workaround that an editor found and we tested was to enable all languages on the form column in language settings.   It has to be done for each journal,  but it seems to allow email templates to save and turned red globes green.

**Comment by Vitaliy-1** [comment]
@NateWr, I'm receiving JS error when trying to save an email template (only on the main branch):
```
build.js?v=3.4.0.0:170519 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at build.js?v=3.4.0.0:14634
    at Array.forEach (<anonymous>)
    at VueComponent.submitValues (build.js?v=3.4.0.0:14622)
    at Watcher.get (build.js?v=3.4.0.0:173112)
    at Watcher.evaluate (build.js?v=3.4.0.0:173214)
    at VueComponent.computedGetter [as submitValues] (build.js?v=3.4.0.0:173466)
    at VueComponent.submit (build.js?v=3.4.0.0:14705)
    at VueComponent.nextPage (build.js?v=3.4.0.0:14665)
    at invokeWithErrorHandling (build.js?v=3.4.0.0:170485)
```
is it related?

**Comment by Vitaliy-1** [comment]
Looks like it's related, without the line added by the referenced commit I'm able to save.
