### ISSUE TITLE
Reconcile registration/login forms with form builder vocabulary (and fix multilingual fields)

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#694]
On second thought, filing the linked comment as an issue for better tracking.

See https://github.com/pkp/pkp-lib/commit/f30ae0e68bd391464655300fa5001a761112f690#commitcomment-12792961

Assigning to you for a heads-up, Nate, though that doesn't necessarily mean you're on the hook for fixing it.

**Comment by NateWr** [comment]
*shakes fist at the sky*

Ok, so ideally I'd like to see this separated from backend dependencies like the FBV, especially since there are really only a few forms to worry about on the frontend (login, registration, search).

Frameworks like Bootstrap have utility classes for designing forms, and I'd like to not get in the way of that with all the helper classes that FBV chucks into things.

So, two things:

1. Should `affiliation` really be multi-lingual? I'd think that most institutions have a name and that name would be appropriate regardless of the language it's used in. I'd also think that end-users (subscribers, authors) shouldn't be the ones responsible for that kind of multi-lingual input. What if I only speak one of the supported languages and don't know the appropriate affiilation in another language?

2. My assumptions above may be wrong. So if we do need multi-lingual affiliation on the frontend, maybe I can just implement that directly on that field, rather than resorting to the FBV? What say you?

**Comment by asmecher** [comment]
@NateWr, I think we should probably address the FrameBuilderVocabulary as a whole. There are some parts of it that need review. It had a few laudable goals, IIRC:
- Decrease repetition of markup
- Standardize form appearances
It hasn't done either of these very well, and I suspect you'd have a much better idea of how to accomplish both. I do think there's value in keeping the front end forms and back end forms consistently implemented, but I'd bet that lightweight plain-old-HTML with a bit of strategic javascript and CSS will do it better.

I do think affiliations should be multilingual-capable. See the request that originally led to this:
http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=5550

Think e.g. of Freie Universität Berlin / Free University Berlin.

**Comment by bozana** [comment]
I accidentally saw this issue i.e. this affiliation example :-) Freie Universität Berlin is not multilingual -- the university policy at the moment is that the name is only Freie Universität Berlin -- even FU is not correct -- earlier there was no policy so the peple tried to translate it and used the acrony, but now everybody should use only the one long version... :-)

**Comment by NateWr** [comment]
So I'm still not convinced it's a good idea to make this field multilingual *on the frontend*. It seems very unusual to ask the user to supply a translation for an institution's name. It assumes that a) the user knows the other language or b) they are capable of providing a translation in that language.

Both of these strike me as edge cases -- even though I understand there are several countries (like Canada) with strong and widely used bilingual practices. But if I were submitting to a French journal and was asked to provide the name of my university in French during signup, I'd feel pretty odd. Am I supposed to actually go and figure that out? Or do I just enter some mumbo jumbo? Or do I just leave the field blank?

I imagine this would get confusing quickly in places like Europe, where there is a lot of cross-cultural academic output. A Dutch academic might be affiliated with a French institution with English and French names, and be submitting to a Spanish journal that publishes in English and Spanish. It wouldn't be at all clear what she ought to write in the Spanish affiliation field.

I can understand having it as an optional field on the user profile page. But as a default required field on the registration page, I'm really not convinced.

**Comment by asmecher** [comment]
Makes sense. I'd suggest making it single-language on the registration page, but supporting multiple languages within the profile form. When we get down to the level of published article metadata I do think it's important to (optionally) support multilingual institution names; but because we pre-fill author records from user profiles, unless we facilitate storing this information at the user level, someone would have to keep re-entering alternative languages for the same data.

As the form is currently implemented, it causes PHP warnings because the PHP side expects array data. Changing the field name to `affiliation[{$currentContext->getPrimaryLocale()]` would tell the PHP side that we're specifying an affiliation in the context (journal)'s primary locale.

**Comment by NateWr** [comment]
:+1: 

I switched milestone to OMP 1.2 since that will be first and we'll probably want to sort it out for that.

**Comment by asmecher** [comment]
I'll go ahead and fix the current form control since I'm working with testing anyway.

**Comment by asmecher** [comment]
^ The affiliation field works again on the registration form; it's single-language and fixed to the context's primary locale, which I think will be expected behavior.

**Comment by NateWr** [comment]
Is there anything left on this issue or are we comfortable making a break with the FBV on the frontend now?

**Comment by asmecher** [comment]
Let's talk about it on Monday. I don't see why we'd want a different form toolset on the front end vs. back end -- IMO we should fix the FBV and use it throughout.

**Comment by NateWr** [comment]
@asmecher Should we clear the 1.2 milestone from this Issue or close it and create a new issue to discuss the FBV?

**Comment by asmecher** [comment]
The affiliation field issue needs to get fixed for OMP 1.2 (see the link to the comment in the original posting).

**Comment by NateWr** [comment]
I thought that you fixed the affiliation field starting from [this comment](https://github.com/pkp/pkp-lib/issues/694#issuecomment-144489569)...

**Comment by asmecher** [comment]
I'm still not totally satisfied that the field is monolingual during registration, but multilingual thereafter. But not so dissatisfied that I won't defer this to OMP 1.2.1.

**Comment by NateWr** [comment]
@asmecher Are you still unhappy about the affiliate field being monolingual during registration? I'm still in favor of keeping it that way, and ready to close this unless you still want to work at making it multi-lingual.

**Comment by asmecher** [comment]
Let's go ahead with it as is unless we get vocal feedback.
