### ISSUE TITLE
Problems with the content table in the imported issue

### ISSUE THREAD

**Issue by martinmesa** [pkp/pkp-lib#6943]
Hello,
I upgraded my OJS from 3.3.0-3 to 3.3.0-5 and after that OJS only shows the first article in the table of contents of each issue. I tried to sort the articles by moving the second to the first and continue to show the first article.
This problem occurs with some issue that I imported before the update but that were displayed correctly.
I have been looking in the database and I do not find differences between imported articles and those entered using the workflow.

Greetings

**Comment by asmecher** [comment]
@martinmesa, could you post your question in the support forum (https://forum.pkp.sfu.ca)? That's the best way to get support.
