### ISSUE TITLE
UsageStats rejects a whole logfile, even with only one malformed line

### ISSUE THREAD

**Issue by melat0nin** [pkp/pkp-lib#6945]
**Describe the bug**
When processing access logs, UsageStats will reject a whole log file if even one line is malformed (usually a bad useragent string). This is excessive and skews the stats dramatically (data showing with hundreds or thousands of accesses is rejected on the basis of a single entry), and the manual fix is complicated for non-technical users: accessing the plugin's `reject` director in OJS' `public` directory, finding the offending log and the malformed line within it, removing it, and moving the log into the `staging` directory.

**To Reproduce**
N/A

**What application are you using?**
OJS 3.3.0.4 (and prior)

**Additional information**
The processing should simply step over a malformed line in the log, or perhaps more helpfully this behaviour should be tied to OJS `debug` configuration option -- when the latter is enabled, logs are rejected to aid web server debugging, but otherwise such errors are stepped over.

The exception handling is done at lines 157-160 of `UsageStatsLoader.inc.php`: https://github.com/pkp/usageStats/blob/422cfc8d3aa528ad220e25e73c2ad75c1253d49e/UsageStatsLoader.inc.php#L157

I have been manually getting round this by replacing 158-159 with a `continue;`, but this is a hack of course.

**Comment by asmecher** [comment]
@melat0nin, are you this user on the forum? https://forum.pkp.sfu.ca/t/usagestats-discarding-whole-logs-for-one-bad-entry/64815

Would you be willing to open a pull request with the change you've suggested?

**Comment by bozana** [comment]
Hi @melat0nin, it would be really useful for us to know why the log file entry is not valid. Do you use the OJS or apache logs?
That function `_isLogEntryValid` only checks if the entry is empty and if the date is a numeric > 0. Thus one of those two cases should be the problem in your log files?
If you take a look into the usage stats scheduled task log files (under scheduledTaskLogs/Usagestatisticsfileloadertask-...-YYYYMMDD.log in your files folder), there should be the error message containing the file path and the line number? Could you please double check just one or few of them to see what is wrong?
Thanks a lot!

**Comment by bozana** [comment]
Hi @asmecher, 
I am not sure why the usageStats plugin is implemented this way -- to throw exception if a log file like is not valid. Do you maybe have an idea?
However, because I did not get any answer how is that possible at all, I would not change it for the current usageStats plugin, but would consider it in our new implementation for 3.4. OK?

**Comment by asmecher** [comment]
Sorry, I can't think of any context that might help -- but I can't think of a good reason to reject a whole logfile because of an invalid entry.

**Comment by bozana** [comment]
Ah, I've just seen that in the new implementation I have already considered this, s. https://github.com/pkp/pkp-lib/blob/main/classes/task/PKPUsageStatsLoader.php#L301-L307 -- The error is logged but the processing continues...
Thus I will close this issue...
