### ISSUE TITLE
Plugin gallery build failing with bad credentials error on some Pull Requests that execute "pkp-plugin generate-site" command

### ISSUE THREAD

**Issue by pablovp86** [pkp/pkp-lib#6947]
Some of the [Plugin Gallery Pull Requests builds are failing](https://github.com/pkp/plugin-gallery/pulls
). 

As shown [in this build example](https://travis-ci.com/github/pkp/plugin-gallery/builds/222553194), The error occurs upon the execution of [this command](https://github.com/pkp/plugin-gallery/blob/main/.travis.yml#L15):

`  - if [ $TRAVIS_BRANCH == 'main' ]; then pkp-plugin generate-site $TRAVIS_BUILD_DIR/plugins.xml; fi`

Which returns a non-zero result with a bad credentials error, probably trying to fetch some github resources:

> Generating site out of /home/travis/build/pkp/plugin-gallery/plugins.xml
> HttpError: Bad credentials

This [Pull Request](https://github.com/pkp/plugin-gallery/pull/61/commits), seems to fix it, by setting the github token before executing the command.

Sorry if this issue is duplicated, i really haven't found one that addresses this problem.

**Comment by asmecher** [comment]
@pablovp86, I fixed something related to this yesterday -- are you seeing pulls requested since then?

**Comment by pablovp86** [comment]
> @pablovp86, I fixed something related to this yesterday -- are you seeing pulls requested since then?

@asmecher: 
[This Pull Request was april 12](https://github.com/pkp/plugin-gallery/pull/64), and [failed with bad credentials](https://travis-ci.com/github/pkp/plugin-gallery/builds/222826392).

**Comment by asmecher** [comment]
Yes, the fix was added after that PR was tested (and it has already been merged). Do you have an open PR that this issue is showing up on?

**Comment by pablovp86** [comment]
Yes, this PR: https://github.com/pkp/plugin-gallery/pull/62

Opened 6 days ago.

It's possible to run again the build process?

**Comment by NateWr** [comment]
@pablovp86 I've restarted the build. However, you may need to rebase the PR against the latest changes in the `main` branch. Otherwise the tests will be run against the old build.

**Comment by pablovp86** [comment]
@NateWr same problem after the rebase: https://github.com/pkp/plugin-gallery/pull/62/checks

Not quite sure, maybe this new PR solves the problem?
https://github.com/pkp/plugin-gallery/pull/65/

**Comment by asmecher** [comment]
Yes, https://github.com/pkp/plugin-gallery/pull/65 should resolve the issue -- it should be resolved in the coming days.

**Comment by pablovp86** [comment]
Thanks @asmecher.

**Comment by pablovp86** [comment]
Problem [solved](https://github.com/pkp/plugin-gallery/pull/62/checks?check_run_id=2383583459).
