### ISSUE TITLE
[OPS] Upgrade error: servers table doesn't exist

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6948]
**Describe the bug**
During upgrade from terminal 3.2.1 -> 3.4.0 receiving a fatal error 
```
ERROR: Upgrade failed: DB: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ops-dev2.servers' doesn't exist (SQL: select `c`.`server_id` from `servers` as `c` left join `server_settings` as `cs` on `cs`.`server_id` = `c`.`server_id` group by `c`.`server_id`)
```

**To Reproduce**
run `php tools/upgrade.php upgrade` from 3.2.1 instance
see:
```
[pre-install]
[load: upgrade.xml]
[version: 3.4.0.0]
[code: Installer Installer::checkPhpVersion]
[code: Installer Installer::changeSubmissionStageToProduction]
[code: Installer Installer::installEmailTemplate]
[migration: PKPv3_3_0UpgradeMigration]
ERROR: Upgrade failed: DB: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ops-dev2.servers' doesn't exist (SQL: select `c`.`server_id` from `servers` as `c` left join `server_settings` as `cs` on `cs`.`server_id` = `c`.`server_id` group by `c`.`server_id`)

```
**What application are you using?**
OPS 3.2.1 -> 3.4 upgrade, suspect affects upgrades to 3.3 too because the error is thrown during `PKPv3_3_0UpgradeMigration` execution

**Additional information**
I noticed that renaming from `journals` to `servers` is happening in https://github.com/pkp/ops/blob/bb8bc290cab396562b3b5275151f1615709bd70f/classes/migration/upgrade/3_4_0/I6759_RenameVariables.inc.php#L53. Maybe it should happen earlier?

**Comment by asmecher** [comment]
@ajnyga, I suspect some of your recent work to rename entities in the codebase introduced this; would you mind having a look?

**Comment by ajnyga** [comment]
@asmecher can you please assign this to me so that I do not keep forgetting about it!

**Comment by asmecher** [comment]
Assigned, thanks!

**Comment by ajnyga** [comment]
So it looks like the change to upgrade.xml never made it for some reason.

OPS: https://github.com/pkp/ops/pull/151

Everything seems to migrate correctly now, but right after this script is finished, you get a new error:
```
[migration: I6759_RenameVariables]
PHP Warning:  Class '\PKP\migration\upgrade\v3_4_0\I6807_SetLastModified' not found in /Applications/XAMPP/xamppfiles/htdocs/ops-upgrade/classes/migration/upgrade/v3_4_0/I6807_SetLastModified.inc.php on line 40
```
The path seems to be correct and the file is there so not sure what that is about?

**Comment by asmecher** [comment]
> PHP Warning:  Class '\PKP\migration\upgrade\v3_4_0\I6807_SetLastModified' not found...

Sorry, that's my typo. Fixed: https://github.com/pkp/ops/commit/b825618a626f0f01db2c27ebd6e42a1ff5d91a8e

**Comment by ajnyga** [comment]
ah ok, could not see that!

**Comment by asmecher** [comment]
Should be fixed, thanks @ajnyga!
