### ISSUE TITLE
Security issue: various flaws with password hashes and reset

### ISSUE THREAD

**Issue by UTSLibraryITS** [pkp/pkp-lib#695]
Hi there,

There is several flaws in the way the PKP \ OJS library handles password hashes:

1. **Password Reset** 
 
 https://github.com/pkp/pkp-lib/blob/master/classes/security/Validation.inc.php#L274

 Firstly, the most serious issue relates to the password reset hash / token. Not only is the token only 6 characters long, it's generated from the user ID, username and password hash! Therefore, if someone has access to a user's password hash, they can just use the hash to reset their password. Any security provided by the one-way hash is basically negated.

 I think it's fair to assume that any attacker who has access to a user's password hash, probably also has access to the user ID and username (especially with regards to the admin, ie. user ID = 1).

 Furthermore, best practice suggests that the password reset token should also have some sort of expiration component.

2. **Password hash algorithm \ salt**

 https://github.com/pkp/pkp-lib/blob/master/classes/security/Validation.inc.php#L229

  PKP \ OJS only provides the option of using MD5 or SHA1 hashing algorithm - neither of which is recommended for storing passwords. Furthermore, rather than using a proper salt, only the username is concatenated before hashing. This provides very little extra security - if an attacker had access to a user's password hash, it's likely they also have access to the username.

 Rather than using this custom hashing / salting method, I'd suggest switching to something like [Password Compat](https://github.com/ircmaxell/password_compat) by @ircmaxell

3. **Password comparison \ verification**
 
 https://github.com/pkp/pkp-lib/blob/master/classes/security/Validation.inc.php#L71

 As above, I'd suggest using @ircmaxell's password_verify()

Please let know if you'd like me to submit a pull request / patch.

Thanks,

Josh.

**Comment by asmecher** [comment]
Hi @UTSLibraryITS -- good to have another set of eyes on this, as this aspect of the code has changed very little since OJS 2.0 was released a decade ago. A PR would be welcome. (The ojs-stable-2_4_6 and ojs-dev-2_4 branches are probably best -- either one is good and I'll cherry-pick to the other.) Please maintain backwards compatibility for already-generated hashes if at all possible.

Note that we're decreasing the amount of home-grown code in the master branch (currently 3.0 beta, to be released as OJS 3.0). There are composer dependencies etc. so if you'd like to propose a third-party library it would be a welcome change.

**Comment by asmecher** [comment]
@UTSLibraryITS, thanks, I've given this a first review and made a few comments. It looks very well considered.

@ctgraham, how do you feel about taking a look? It would be nice to get another set of eyes on it.

**Comment by UTSLibraryITS** [comment]
Thanks for the feedback. I've committed some changes which should address the issues you've raised.

**Comment by asmecher** [comment]
Hi all -- just a heads-up that I'd like to put the wraps on OJS 2.4.7 and would love to include this change. @UTSLibraryITS, if you could give this a once-over and open a pull request against the `ojs-dev-2_4` branch, I'd be happy to take it from there. I really appreciate your contributions on this, @UTSLibraryITS, @ctgraham and @samueloph!

**Comment by UTSLibraryITS** [comment]
I think I've successfully switched the pull request to the dev branch (after a few failed attempts).

Please let me know if that's okay.

**Comment by asmecher** [comment]
@UTSLibraryITS, thanks -- I've taken your PR and added a couple of trivial tweaks to it:
https://github.com/pkp/ojs/pull/615

I'll let this run through a little testing before I merge it, but generally it's looking good!

**Comment by asmecher** [comment]
@UTSLibraryITS, this fails an installation test -- it looks like the administrator account's password isn't correctly set or something similar.

**Comment by UTSLibraryITS** [comment]
Can you provide a link to the build log?

**Comment by asmecher** [comment]
Here it is: https://travis-ci.org/asmecher/ojs/builds/81492916

**Comment by asmecher** [comment]
I looked a little further into the problem; it was caused by the `password` field in the `users` table not being extended in the main schema descriptor. I've updated my branch to suit and created a branch in the `lib/pkp` submodule where the main descriptor is:

https://github.com/pkp/pkp-lib/compare/ojs-dev-2_4...asmecher:i695-fix
https://github.com/pkp/ojs/compare/ojs-dev-2_4...asmecher:i695-fix

I also cleaned the commit history up.

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/pkp-lib/pull/780
https://github.com/pkp/ojs/pull/624

**Comment by asmecher** [comment]
Merged. Thanks for contributing, @UTSLibraryITS! This will be included in OJS 2.4.7.

**Comment by asmecher** [comment]
Filed a forward-porting issue: https://github.com/pkp/pkp-lib/issues/781

**Comment by asmecher** [comment]
This appears to have broken the password reset process (!) -- see:
https://github.com/pkp/pkp-lib/issues/831

**Comment by UTSLibraryITS** [comment]
The submodule changes mustn't have come through when we switched branches.

Because the password reset functionality was definitely working pre-2.4.7.

It's in production at https://epress.lib.uts.edu.au/journals/index.php/index/login/lostPassword

**Comment by asmecher** [comment]
Not to worry, @UTSLibraryITS -- that's what regression tests are for. I'll see about putting together a test for the password reset process.
