### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by noni90** [pkp/pkp-lib#6950]
hi  i  have problem in  new ojs 3.3.0-5 the log out icon disappear from the dashboard how can  i  fix it

**Comment by asmecher** [comment]
@noni90, can you post your question on the support forum (https://forum.pkp.sfu.ca)? That's the best place to get help.

**Comment by noni90** [comment]
> @noni90, can you post your question on the support forum (https://forum.pkp.sfu.ca)? That's the best place to get help.

I fixed it thank you so much
