### ISSUE TITLE
Remove file naming test from the shared library

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6952]
**Describe the bug**
OPS Travis builds are failing because Cypress test containing the script to change the name of the file on the submission stage in the shared library: https://github.com/pkp/pkp-lib/blob/eae0b1b98604f25eda79cb13f8e2785870477217/cypress/tests/integration/Filenames.spec.js

**To Reproduce**
Run build, see:
```
Filename support for different character sets
       #6898 Tests submission file download name is correct:
     AssertionError: Timed out retrying: Expected to find content: 'Submission' within the element: <a#ui-id-1.ui-tabs-anchor> but never did.
      at Context.eval (http://localhost/__cypress/tests?p=lib/pkp/cypress/tests/integration/Filenames.spec.js:13:31)
```

**What application are you using?**
OPS main branch

**Additional information**
Related to: https://github.com/pkp/pkp-lib/issues/6898

**Comment by NateWr** [comment]
The following PR should make the test work across all three applications. I also made use of the REST API so it should be faster now.

PR:
https://github.com/pkp/pkp-lib/pull/6966

Tests:
https://github.com/pkp/ops/pull/147
https://github.com/pkp/ojs/pull/3111
https://github.com/pkp/omp/pull/964

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `stable-3_3_1` and `main`.
