### ISSUE TITLE
[Portico] Issues with the stable-3-1-2 branch

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6955]
I've updated to the latest version of the stable-3-1-2 branch and caught/fixed some issues:
- The composer.json is missing the `league/flysystem-ftp`
- Missing loading composer autoloader
- Update readme with the new steps (e.g. composer)
- When submitting forms (e.g. Deposit Issues), a warning about leaving the window with unsaved data pops up
- Spread the updates to the newer branches

PRs:
- https://github.com/pkp/portico/pull/7 [edit: for stable-3_2_1]
- https://github.com/pkp/portico/pull/8 [edit: for main]
- https://github.com/pkp/portico/pull/9 [edit: for stable-3_1_2]

**Comment by jonasraoni** [comment]
As I've already fixed/tested, I can create PRs later, I just didn't check one issue (unsaved data popup).

**Comment by asmecher** [comment]
@jonasraoni, just a reminder that you might have code needing contribution here.

**Comment by jonasraoni** [comment]
I found the code 😅

https://github.com/pkp/portico/pull/7

I didn't find updates related with the "unsaved data popup" in the code, maybe I was busy with other tasks and it ended up forgotten.
I also can take a look at the last item of this issue (update the other branches) as soon as I get some free time.

**Comment by asmecher** [comment]
Thanks, @jonasraoni. What parts of this need forward-porting to later releases?

**Comment by jonasraoni** [comment]
The main issue I see is that `stable-3_1_2` has more features (e.g. multiple endpoints) than `stable-3_2_1` and `main`.
So, let me know if I should tackle this.

**Comment by asmecher** [comment]
Whoops, it looks like we have a fork! I didn't realize that @jmacgreg moved the repo to `pkp`, and I released the most recent plugins to the plugin gallery from `asmecher/portico`. I'll take a look at this tomorrow. Those features did get ported to `stable-3_2_1` and `main` (which was 3.3.0-x at the time).

**Comment by asmecher** [comment]
@jonasraoni, just checking on some of the details here -- what message were you getting about autoloading? There should be an existing include for the autoloader here: https://github.com/pkp/portico/blob/26d5c358e572680f8a81e7fd6629d28789d88fbf/PorticoExportPlugin.inc.php#L132

Also, Flysystem 2.0.0 comes with an FTP adapter; I think this may have been separated out only with 3.0.

**Comment by jonasraoni** [comment]
As I've tested this a long time ago, I had to recheck and basically:
`stable-3_3_0`: Its `pkp-lib` already have the sftp package (^1.0), which includes the FTP adapter. So this branch doesn't need the `composer`.
`stable-3_x_x`: Requires the composer, and the sftp ^2.0 doesn't include the FTP adapter.

I'll downgrade the packages for `stable-3_x_x` just to standardize the code.

About the autoloader, I didn't have issues with it, perhaps I just didn't notice it was inside the code 🤔

**Comment by jonasraoni** [comment]
Hi @asmecher, please check if there's anything missing, I'll need these updates 😁

As a summary:
All branches: added extra information to the output/XML + code formatter
`/main (stable-3_3_0)`: Fixed a bug
`< stable-3_3_0`: Downgraded the SFTP package to 1.0, mostly to keep the code similar.

**Comment by asmecher** [comment]
I've merged the PRs on https://github.com/pkp/pkp-lib/issues/7807, and the ones here appear to be closed -- is something more awaiting merging?

**Comment by asmecher** [comment]
I think https://github.com/pkp/pkp-lib/issues/7807#issuecomment-1240271357 was supposed to be on this issue. If that's the case -- can this be closed?

**Comment by jonasraoni** [comment]
I've created the other PRs based on these ones, so I'm closing this issue :)
