### ISSUE TITLE
Improve OAI performance

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6963]
There are FIXMEs in PKPOAIDAO regarding inefficiency in seeking through a result set to the correct subset. For large repositories these will perform poorly.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/7073
- https://github.com/pkp/ojs/pull/3134

@bozana, would you mind taking a look at this (before I adapt them for OPS and OMP)?  Essentially they convert the raw SQL to Laravel's querybuilder which permits better augmentation of the queries by calling code for counts etc. This doesn't improve the performance of the DRIVER plugin, though -- that'll still need attention, but I'm kind of waiting for someone to tell me it's a problem first.

**Comment by jonasraoni** [comment]
@asmecher, one thing that I've noticed in the wild: The "Identity" verb of https://raco.cat (OJS 3.1.1.4) takes a long time to return, but other "limited" verbs (`ListSets`, `ListRecords` with a `set` argument) are ok.

**Comment by asmecher** [comment]
> The "Identity" verb of https://raco.cat (OJS 3.1.1.4) takes a long time to return

That's likely due to the query determining the date of the first record. To make that query performant we'll either need to use functional indexes (not yet supported in our MySQL baseline), or move to using soft deletes (Illuminate supports these nicely but we don't use them yet). Or cache that value somewhere.

**Comment by asmecher** [comment]
@bozana, I've addressed your review comments; could you take a second look? Thanks!

**Comment by asmecher** [comment]
Thanks, @bozana! I've addressed all your comments; in addition to the earlier PRs...
- https://github.com/pkp/pkp-lib/pull/7073
- https://github.com/pkp/ojs/pull/3134

...I've ported this to OPS and OMP:
- https://github.com/pkp/ops/pull/162
- https://github.com/pkp/omp/pull/983

I don't think these need separate review, so I'll merge them.
