### ISSUE TITLE
PKPString missing at Citation.inc.php

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6972]
**Describe the bug**
A fatal error is produced from Publication edit if the References are enabled.

**To Reproduce**
1. Go to Submissions
2. Go to publication
3. see the error (if references are enabled)

**What application are you using?**
 OJS, OMP or OPS version 3.3

**Comment by defstat** [comment]
@asmecher 

**PR**
[pkp-lib]: #6973

**Comment by NateWr** [comment]
:+1: merged.
