### ISSUE TITLE
Fix Filter Test Brake

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6974]
**Describe the bug**
The `FilterTest::testInstantiationAndExecute` is failing

**What application are you using?**
 OJS, OMP or OPS main branch - after #6490 merge

**Comment by defstat** [comment]
@asmecher @NateWr 

**PR**
[pkp-lib]: #6975

**Comment by NateWr** [comment]
@defstat can you add an OJS PR with the submodule update so the tests are run?

**Comment by defstat** [comment]
> @defstat can you add an OJS PR with the submodule update so the tests are run?

Everything passed
https://travis-ci.com/github/pkp/ojs/builds/223846455

**Comment by NateWr** [comment]
Thanks @defstat, all merged!
