### ISSUE TITLE
Remove abstract methods from ImportExportPlugin 

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6976]
**Describe the problem you would like to solve**
The ImportExportPlugin was provided with 3 abstract methods as part of the Native Import/Export plugin changes (#6490). That adds complications to 3rd party plugins. That could be part of a larger change that takes into account every existing and future plugins. 

**Describe the solution you'd like**
Leave the changes only to Native Import/Export plugin

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**
[pkp-lib]: #6977
[OJS]: pkp/ojs#3114
[OMP]: pkp/omp#965
[OPS]: pkp/ops#148

OMPs tests are failing with 

```
1) SubmissionFileDAOTest::testSubmissionFileCrud
tempnam(): file created in the system's temporary directory

C:\xampp\htdocs\omp-3-dev\tests\classes\monograph\SubmissionFileDAOTest.php:51
```

Are you getting this also?

**Comment by asmecher** [comment]
@defstat, I think you can fix that message by setting e.g. `upload_tmp_dir = C:\php\temp\` in `config.inc.php`. It's just a notice/warning but seems to be interfering with PHPUnit, which is picky about these things.

**Comment by asmecher** [comment]
Merged all 4 PRs above ^^ Thanks, @defstat!
