### ISSUE TITLE
DataCite plugin silently fails to handle titles with more than 255 characters  

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#698]
I am not sure if that's a requirement, but even if it is, the plugin should not just silently fail, it should warn the user about that and let it export the other objects.

**Comment by asmecher** [comment]
From: http://forum.pkp.sfu.ca/t/problem-with-dara-export-plugin/3568/5
Bruno, did you confirm where the 255-character limit is coming in? I didn't spot anything at a glance.

**Comment by beghelli** [comment]
I had nothing to do with DataCite, instead was something related to a closed source plugin based on DataCite.
