### ISSUE TITLE
On password change, invalidate other sessions

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6983]
When a user changes their password, it should invalidate any other open sessions from the user.

**Comment by touhidurabir** [comment]
@asmecher 2 PR added targeting the `pkp-lib` and `ojs` `stable-3_3_0` branch . please review and if all ok and test passes properly , I will make PR then for other repos . 

[pkp-lib](https://github.com/pkp/pkp-lib) `stable-3_3_0` --> [pkp/pkp-lib#6983 On password change, invalidate other sessions](https://github.com/pkp/pkp-lib/pull/7877) 
[ojs](https://github.com/pkp/ojs) `stable-3_3_0` --> [pkp/pkp-lib#6983 Submodule Update ##touhidurabir/i6983_fix_stable_3_3_0##](https://github.com/pkp/ojs/pull/3378)

Also as I have noticed , this change can be pushed to `main` branch also . So in that case should I prepare the PRs also for the main branch for all the repos(`pkp-lib`, `ojs`, `ops`, `omp`) for this issue ?

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I've added comments here: https://github.com/pkp/pkp-lib/pull/7877

Once you've addressed those, I'd say it's ready for submodules for OMP and OPS, and forward-porting to `main` as well.

**Comment by touhidurabir** [comment]
@asmecher I have made new pull request as I made a mess of the last one during the git rebase twice mistakenly and force push . 

New Push list 

[pkp-lib](https://github.com/pkp/pkp-lib) stable-3_3_0 --> [pkp/pkp-lib#6983 On password change, invalidate other sessions](https://github.com/pkp/pkp-lib/pull/7883)
[ojs](https://github.com/pkp/ojs) stable-3_3_0 --> [pkp/pkp-lib#6983 Submodule Update ##touhidurabir/i6983_fix_stable_3_3_0##](https://github.com/pkp/ojs/pull/3380)

This new pull request takes into the all password update case considerations as 

1. User password update .
2. User password update by admin/journal manager from journal settings
3. user password reset
4. user password force update on login as password updated or reset

Here is the last pull request reference https://github.com/pkp/pkp-lib/pull/7877 as that has some discussion going on . 

Once the test passes , please review and if all ok , then I will move forward with these changes to push to `ops` and `omp` and port to `main` branch .

**Comment by asmecher** [comment]
@touhidurabir, this issue is scheduled against 3.4.0 so it should be coded against `main` rather than `stable-3_3_0`. Could you port the changes forward and open PRs against `main`?

**Comment by touhidurabir** [comment]
@asmecher PRs are done for `main` branches . for now I have it only forward it `ojs` . once the test passes and you review and confirm, I will forward the changes to `ops` and `omp` also . 

`main` branch PR lists 

1. [pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#6983 On password change, invalidate other sessions](https://github.com/pkp/pkp-lib/pull/7886)
2. [ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#6983 Submodule Update ##touhidurabir/i6983_fix_main##](https://github.com/pkp/ojs/pull/3382)

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I've added a few small comments on https://github.com/pkp/pkp-lib/pull/7886; none of these are substantial, so once you've reviewed them, feel free to go ahead and send in submodule updates for the other apps too.

**Comment by touhidurabir** [comment]
@asmecher done fixing and made 2 more PR for `ops` and `omp` `main` branch . so here is the full PR list

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#6983 On password change, invalidate other sessions](https://github.com/pkp/pkp-lib/pull/7886)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#6983 Submodule Update ##touhidurabir/i6983_fix_main##](https://github.com/pkp/ojs/pull/3382)
[ops](https://github.com/pkp/ops) --> [pkp/pkp-lib#6983 Submodule Update ##touhidurabir/i6983_fix_main##](https://github.com/pkp/ops/pull/274)
[omp](https://github.com/pkp/omp) --> [pkp/pkp-lib#6983 Submodule Update ##touhidurabir/i6983_fix_main##](https://github.com/pkp/omp/pull/1109)

for some reason for a new commit , there is conflict in the `OJS` that need manual resolve . 

One question, as this issue targeted for the `main` branch and I already have 2 PR for the `stable-3_3_0` for the `pkp-lib` and `ojs`, should I close those ? or should I port those for the `stable-3_3_0` of `ops` and `opm` also ?

**Comment by asmecher** [comment]
@touhidurabir, I've added a comment at https://github.com/pkp/pkp-lib/pull/7886 -- looks like the code formatter isn't working.

I'd suggest closing the `stable-3_3_0` PRs; this is scheduled against 3.4.0, so won't be included in the next 3.3.0-x release.

**Comment by touhidurabir** [comment]
@asmecher the code formatting issue should be fixed now . please review .

**Comment by asmecher** [comment]
Thanks, @touhidurabir! Merged the pkp-lib PR and resolved the lib/pkp submodule updates manually.
