### ISSUE TITLE
HTML entities displayed in journal title by citationStyleLanguage plugin

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#6986]
**Describe the bug**
Some characters in the journal title are converted into HTML entities in citations displayed by the citationStyleLanguage plugin on the article landing page, e.g. `Journal of Knowledge & Open Access` is displayed as  `Journal of Knowledge &amp; Open Access`

**To Reproduce**
Add special characters to the journal title under Settings > Journal > Journal title

**What application are you using?**
OJS 3.2.1

**Comment by asmecher** [comment]
@mfelczak, could you double-check that this entry is rendered as you expected? Looks like Github unescaped the entity you were trying to include.

**Comment by mfelczak** [comment]
Thanks @asmecher, updated! The irony has also been noted.

**Comment by asmecher** [comment]
For OJS 3.3.0-x users who are affected by this, here is the relevant fix (to be applied in `plugins/generic/citationStyleLanguage`):
https://github.com/pkp/citationStyleLanguage/commit/c9e2d12242fc182729dd5083f5aeb9336a6f8e15

**Comment by sarontt** [comment]
It looks like that didn't fix it completely.

We also removed the call to htmlspecialchars on the next line regarding {'container-title'} and that seemed to resolve it.  I am not sure what all the repercussions that may have though.  I also tested the other characters (", ', < and >) which that function performs translations on and those characters displayed correctly without the call to htmlspecialchars.

On a side note, I noticed there were some added capitalization even though the journal title did not have capitalization in those places.  Here is the journal title I tested with:  journal & title and testing " and ' and < and >.  And here is how it displayed:  How to Cite
admin, admin. (2021). submission title: submission subtitle. Journal & Title and Testing " and ’ and < And >, 1(2). Retrieved from http://localhost:8000/ji/article/view/1

**Comment by asmecher** [comment]
@sarontt, thanks, that proposed additional fix is correct. Could you open a pull request for it? (If not, I can take care of it.)

**Comment by asmecher** [comment]
Thanks, @sarontt! I'll cherry-pick that around to the appropriate branches.

**Comment by faheemhameed** [comment]
Can we also remove htmlspecialchars from the below line for the abstract?

Line 322: CitationStyleLanguagePlugin.inc.php

$citationData->abstract = htmlspecialchars($publication->getLocalizedData('abstract'));


Thanks
