### ISSUE TITLE
OAuth2 authentication

### ISSUE THREAD

**Issue by frafra** [pkp/pkp-lib#6988]
**Describe the problem you would like to solve**
It would be useful to rely on external services to log in: it would make life easier for both editors and system administrators.

**Describe the solution you'd like**
OAuth2 would be a good candidate.

**Who is asking for this feature?**
Journal Administrators, system administrators.

**Comment by asmecher** [comment]
Related: https://github.com/leibniz-psychology/openid

**Comment by NateWr** [comment]
:+1: I'm going to close this since there is a third-party plugin available to do this. But we're happy to revisit this topic if/when the plugin does not meet the needs of our community.
