### ISSUE TITLE
[OJS] Class "PKP\xslt\DOMDocument" not found

### ISSUE THREAD

**Issue by TheMechanicalButterfly** [pkp/pkp-lib#6989]
When trying to use the native XML Plugin to import issue data, the following error message appears:

`Class "PKP\xslt\DOMDocument" not found`

I remember seeing some recent commits about namespacing and I wonder, whether it could be related to this. 

A quick code search brought up this:

```
D:\{installation path}\lib\pkp\classes\xslt\XSLTransformer.inc.php:
   16  namespace PKP\xslt;
   17  
   18: use DOMDocument;
   19  use FileManager;
   20  
```

If the namespace `PKP\xslt` for `XSLTransformer` is declared, the `use` statements should also be namespaced, otherwise PHP will attempt to find them in `PKP\xslt` as well.

**Comment by asmecher** [comment]
@TheMechanicalButterfly, are you working with the main branch? There is some comprehensive work on #6051 & #6052 that will cause some instability over the next weeks.

**Comment by TheMechanicalButterfly** [comment]
@asmecher 

Currently yes. Sounds like I should better stick to `ojs-stable-3_1_1`...

**Comment by asmecher** [comment]
@TheMechanicalButterfly, if you're looking for the latest released stable branch, it's `stable-3_3_0`.

**Comment by asmecher** [comment]
In any case, I've adjusted the statements that were causing this specific problem (https://github.com/pkp/pkp-lib/commit/9d88bba8425573460497bcd35e3b8e77f5e8b437) but it'll be tough to work with `main` for a little while yet!
