### ISSUE TITLE
[OJS] Publishers- too many files for the account - stable management and removal

### ISSUE THREAD

**Issue by lcentrone** [pkp/pkp-lib#6993]
Our publisher manages multiple journals.  We appear to have too many files (66.000) on our account. We would like to limit the number of files per submission, keeping trace of the necessary editorial activity.

Are there other publisher users who have the same amount of files or even more? if so, do you adopt a particular workflow limiting the number of files per submission?

Is there a way to add a box at the submission level that generates links redirecting to a dedicated outside cloud where files can be stored?

Is there a way to remove in bulk a certain number of old files avoiding manual removal?

Journal Editors and Journal Administrators

**Comment by asmecher** [comment]
@lcentrone, this is more of a discussion than a feature request -- could you post it on our support forum (https://forum.pkp.sfu.ca)?
