### ISSUE TITLE
The assignedTo parameter in the REST API should not mix types 

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6998]
The `assignedTo` query parameter in the `/submissions` and `/_submissions` endpoints accepts an array of user IDs or `-1` to get unassigned submissions. This query parameter shouldn't mix types.

Introduce a new query parameter, `isUnassigned`, to get unassigned submissions.

**Comment by asmecher** [comment]
Rescheduling for 3.5.0 -- where this may already be done as a result of the submission list work (and API changes).

**Comment by asmecher** [comment]
Confirming that this still does need cleanup. The constant in question is `UNASSIGNED` (easily grepped).

**Comment by taslangraham** [comment]
I can take a look at this @asmecher

**Comment by taslangraham** [comment]
Ready for review @asmecher 

pkp-lib: https://github.com/pkp/pkp-lib/pull/10711

**submodule updates**:
ojs - https://github.com/pkp/ojs/pull/4560
ops - https://github.com/pkp/ops/pull/828
omp - https://github.com/pkp/omp/pull/1788

**Comment by asmecher** [comment]
Thanks, @taslangraham, added a comment: https://github.com/pkp/pkp-lib/pull/10711#pullrequestreview-2507555957

**Comment by taslangraham** [comment]
@asmecher Thanks for the review. Updated and ready to go!

**Comment by asmecher** [comment]
Nice and clean, thanks -- all merged (except I'll handle the submodules separately)!
