### ISSUE TITLE
[OMP] Native import/export: import of publication formats does not work

### ISSUE THREAD

**Issue by hcuser12** [pkp/pkp-lib#6999]
**Description**
I'm trying to import a large set of files. For this task I have generated XML for native import/export plugin.
When I try to import files does not appear under publication format - publication form itself is created, but without file. Even though submission files/file itself is created in database/on disk.
Moreover, after preparing sample submission with publication and creating exported XML from such publication, that file also produces error - file is missing from publication format.

**How to reproduce**
1. Choose any press
2. Import attached file via 'Tools / Native XML Plugin'
3. Open imported publication on tab 'Publication / Publication Formats'
4. See that the file is missing under 'Open Access' publication format

**Application**
OMP, official 3.3.0-5 version - default locale 'pl_PL' (with 'en_US' also installed).

**Attachments**
XML attachment not supported - see my gist: https://gist.github.com/hcuser12/2fd617a94337d567543b6ddcb4ee1c36

**Comment by NateWr** [comment]
Thanks for a great report and the XML to reproduce it. @defstat would any of your recent work have fixed this already?

**Comment by hcuser12** [comment]
> Thanks for a great report and the XML to reproduce it. @defstat would any of your recent work have fixed this already?

@NateWr @defstat any news? It's important part of our work - we have hundreds of books to migrate to OMP.

**Comment by defstat** [comment]
Hi @hcuser12, I think it could be the name of the file genre that produces the problem (it is `Manuskrypt ksi&#x105;&#x17C;ki`). I am preparing a PR for this - when ready, are you able to apply the change and give it a try?

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**
[3.3.0]
pkp-lib: #7019 (@hcuser12 could you check if these changes fix your issue?)

[main]
pkp-lib: #7020

**Comment by NateWr** [comment]
I haven't tested, but code looks good. Let's see if @hcuser12 can confirm the fix before merging.

**Comment by hcuser12** [comment]
It is not working...

In example XML I changed `genre="MANUSCRIPT"` and the file was imported. 
But "Publication format" is still without any file. Moreover this file cannot be selected using "select file" link.

I have uploaded new file and looked inside database to see what's the difference. The only difference I have noticed is inside table `submission_files`:
![submission_file](https://user-images.githubusercontent.com/42377068/117282791-6c7d1a00-ae65-11eb-95de-490332ba8fab.png)
_(upper one is original imported via XML file, the other is uploaded manually via publication form)_

To be sure that's not working I did export XML for that submission and imported once again. Still without attached file.

**Comment by defstat** [comment]
Thanks for the test @hcuser12.. Could you apply and check the OMP and pkp-lib PRs found [here](https://github.com/pkp/pkp-lib/issues/6999#issuecomment-832585800)?

**Comment by defstat** [comment]
Ηι @hcuser12 thanks for testing and confirming - regarding the Open Access issue, I can see in your export file that a 

`source_submission_file_id="38"`

See bellow:

`<submission_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="39" created_at="2021-05-10" date_created="" file_id="12" stage="proof" updated_at="2021-05-10" viewable="false" genre="MANUSCRIPT" sales_type="openAccess" **source_submission_file_id="38"** uploader="admin" xsi:schemaLocation="http://pkp.sfu.ca native.xsd">`

Does the initial database entry of the submission file has a value in the `source_submission_file_id` column? If yes please try to export the submission and check whether the `source_submission_file_id=""` is missing.

**Comment by hcuser12** [comment]
I've updated 2 files from your latest commit. It's still not viewable - not it asks for logging in/payment before viewing.
But I've also found probable cause - it's `direct_sales_price` that makes it inaccessible. Submission file is imported with _empty value_ (not `NULL` or `0` but just empty value). When I do update that file to "Open access" (or change directly in database to `0`) that database field is set to `0` and the file becomes accessible.
Moreover such submission with _empty value_ in above database field cannot be exported - it generates error: `Element '{http://pkp.sfu.ca}submission_file', attribute 'direct_sales_price': '' is not a valid value of the atomic type 'xs:decimal'.`

**Comment by hcuser12** [comment]
After exporting and comparing XMLs it seems that the only difference is attribute `direct_sales_price="0"` for `<submission_file/>` node.
After adding this attribute my XML file is properly imported and the submission file works.
I'll do more test for your changes in next few days.

Regarding `source_submission_file_id` you mentioned earlier - there is no such attribute in my original XML file.

**Comment by hcuser12** [comment]
@defstat 
Is there any chance it will be soon ready for production?

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**
pkp-lib: #7875
OMP: pkp/omp#1106

**Comment by asmecher** [comment]
Merged the above PRs -- thanks, @defstat!
