### ISSUE TITLE
Clean up plugin API

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#700]
There's lots of room for plugin API cleanup, much of it stemming from quasi-backwards compatibility with OJS 2.x. Clean it up.

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/pkp-lib/pull/701
https://github.com/pkp/ojs/pull/578
https://github.com/pkp/staticPages/pull/4
https://github.com/pkp/customBlockManager/pull/3

Bruno, could you take a look at this?

**Comment by beghelli** [comment]
Done!

**Comment by asmecher** [comment]
Merged and ported to OMP.

**Comment by asmecher** [comment]
Summary of the changes:

- The `Plugin::getManagementVerbLinkAction` function has been removed.
- The `Plugin::getActions` function has been added.
- The `Plugin::manage` function has been simplified.

See e.g. https://github.com/pkp/translator/pull/3 for an example of these changes applied to an existing OMP 1.1.x-level plugin.

In the management interface, plugins can use `Plugin::getActions` to return a list of link actions permitting the manager or administrator to interact with the plugin. Interactions can be caught by the plugin using the `manage` function, as before, but with simplified calling conventions.

The legacy classes (e.g. AjaxLegacyPluginModal) have been removed.
