### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by oumnia24** [pkp/pkp-lib#7007]
<img width="930" alt="Screen Shot 2021-04-30 at 3 31 57 PM" src="https://user-images.githubusercontent.com/76491075/116760208-36551b80-a9c9-11eb-8903-3a008b3aaeac.png">
The system is adding more characters whenever it sees accents: https://ojs.stanford.edu/ojs/index.php/intersect/management/settings/workflow#emails/emailTemplates

**Comment by asmecher** [comment]
@oumnia24, could you post this on our support forum at https://forum.pkp.sfu.ca? That's the best place to get help. The technical term for this problem is "mojibake" -- you might try searching for that too, to see if there's already a solution posted.
