### ISSUE TITLE
Distribution tab is not working in both latest versions. I.e 3.3.5 and 6

### ISSUE THREAD

**Issue by Nokiae71** [pkp/pkp-lib#7008]
**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

While using OJS version 5 and even in 6 distribution tab is not working. It's shows error HTTP ERROR 500

**Comment by asmecher** [comment]
@Nokiae71, do you mean OJS 3.3.0-5 and 3.3.0-6?
Can you check your PHP error log for details?

**Comment by Nokiae71** [comment]
yes, 3.3.0-5 &6, i mean exactly.
below is the link tht is not working
https://lmrc.com.pk/ojs/index.php/thejas/management/settings/distribution
 i m not IT expert, plz guide how to check PHP error log

**Comment by Nokiae71** [comment]
Core99 - HTTP error 500 , i think this is what to were asking

**Comment by asmecher** [comment]
See: https://docs.pkp.sfu.ca/faq/en/errors-troubleshooting#first-check-your-php-error-log

**Comment by NateWr** [comment]
I'm going to close this here and ask that you report further details at our support forum, including the PHP error log. You can find the forum at https://forum.pkp/sfu.ca.
