### ISSUE TITLE
PKPTemplateManager.inc.php errors after successfully upgraded 3.3.0.6

### ISSUE THREAD

**Issue by frodocat** [pkp/pkp-lib#7013]
Hello,

I have just upgraded my OJS from version 3.2.1-4 to 3.3.0.6. The upgrade ends with "Successfully upgraded to version 3.3.0.6" in the comment line, but when I navigate through the website I get a lot of errors on every page also in the admin. Some forms keep loading and never stops. I don't see my journals at the homepage.

My errors are:

- Deprecated call without request object. in ojs-3.3.0-6/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 1235

- Deprecated call to Smarty2 function get_template_vars in ojs-3.3.0-6/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 2296

This is what I use:

OS platform | Linux
PHP version | 7.4.16
Apache version | Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips PHP/7.4.16
Database driver | mysql
Database server version | 5.5.68-MariaDB

Hopefully you can help me.

**Comment by asmecher** [comment]
@frodocat, see e.g.: https://forum.pkp.sfu.ca/t/hi-im-havin-an-error-installing-ojs-on-mi-server/52492/8

The support forum is the best place to get assistance.

**Comment by frodocat** [comment]
I get this message on that website: This site is in read only mode. Please continue to browse, but replying, likes, and other actions are disabled for now.

**Comment by asmecher** [comment]
Yes, we're doing some server work, which should be completed soon. But did you try the suggestion at the linked thread?

**Comment by frodocat** [comment]
Yes, it works, thanks! I am only missing my summary of all journals on the homepage, but I'm guessing this is how it should be now?

**Comment by asmecher** [comment]
Could you follow up on that separately? I expect the forum will be available for posting again within a few hours -- but if not, a separate github issue with complete details would be OK too.
