### ISSUE TITLE
PayPal payment fails for amounts greater than 999

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7015]
**Describe the bug**
If you attempt to use the PayPal payment to send a payment for anything and the amount is greater than 999, the plugin fails with a general transaction error.  Looking at the logs, we see:

` Got error 'PHP message: PayPal transaction exception: Invalid integer part 1,000. Invalid digit , found`

**What application are you using?**
Found in OJS 3.3, but probably in all versions of OJS3.

**Additional information**
The reason this is happening is because the PaypalPaymentForm uses PHP's `number_format` method to format the payment amount before sending it on to the transaction:

https://github.com/pkp/ojs/blob/stable-3_3_0/plugins/paymethod/paypal/PaypalPaymentForm.inc.php#L49

The problem is the method does not override the default "thousands separator" which defaults to a comma, and so an amount like "1000" becomes "1,000" which fails.

**Comment by asmecher** [comment]
@jnugent, are you planning a PR to fix this? (You've pinned the problem down and it seems a shame to steal a commit to fix it!)

**Comment by jnugent** [comment]
@asmecher coming up!

**Comment by jnugent** [comment]
@asmecher that PR is for 3.3.0 - let me know if you'd like one for `main` or 3.3.1 as well.

**Comment by asmecher** [comment]
Cherry-picked to stable-3_3_1 and forward-ported to main. Thanks, @jnugent!

**Comment by asmecher** [comment]
Also ported to OMP.
