### ISSUE TITLE
Code formatter is skipping some files

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7017]
The code formatter is skipping some files because the exclusion rules do not declare top-level directories but any matching files. So excluding `plugins` is excluding anthing with that in the name.

We probably should use `notPath` rather than `exclude`: https://symfony.com/doc/current/components/finder.html

(h/t @asmecher)

**Comment by NateWr** [comment]
When fixing this, we should also introduce a new formatting rule that orders `use` imports alphabetically: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/doc/rules/import/ordered_imports.rst

**Comment by jonasraoni** [comment]
Perhaps there's a Smarty template formatter out there as well :)
Also, I think such cases will probably to be manually fixed:
```php
$sql = '
<tab>SELECT ...
';
```

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/7123
https://github.com/pkp/ojs/pull/3153
https://github.com/pkp/omp/pull/984
https://github.com/pkp/ops/pull/163

**Comment by NateWr** [comment]
All merged to `main`.
