### ISSUE TITLE
[UI] Switching form language while registering as a new user doesn't work

### ISSUE THREAD

**Issue by dtwardy** [pkp/pkp-lib#702]
Occuring in OJS 2.4.6

When registering as a new user switching form language doesn't work. If there's nothing entered in the required fields trying to switch the language produces an error message and if all the required information are entered instead of changing the language it just saves the information and the system creates a new user.

**Comment by asmecher** [comment]
@dtwardy, thanks for reporting. Try applying either of the attached patches -- they're equivalent, just applied to different branches. Either should work.
