### ISSUE TITLE
[OJS]Offline App: Creating the PHP Fatal error

### ISSUE THREAD

**Issue by gireeshcse** [pkp/pkp-lib#7022]
If we run the application offline i.e without internet, It is creating the following error

PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ConnectException: cURL error 28: Failed to connect to pkp.sfu.ca port 443: Connection timed out

**Error Stack**

[Fri May 07 17:10:19.658742 2021] [php7:error] [pid 71142] [client 127.0.0.1:52436] PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ConnectException: cURL error 28: Failed to connect to pkp.sfu.ca port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/msg/projects/longrun/ojs/lib/pkp/lib/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200\nStack trace:\n#0 /home/msg/projects/longrun/ojs/lib/pkp/lib/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)\n#1 /home/msg/projects/longrun/ojs/lib/pkp/lib/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#2 /home/msg/projects/longrun/ojs/lib/pkp/lib/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactor in /home/msg/projects/longrun/ojs/lib/pkp/lib/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 200, referer: http://localhost/ojs/index.php/index/admin/wizard/1

**Working around, I am using is the following**

* Downloaded the following file and made the file accessible to locally running application

                
                http://pkp.sfu.ca/ojs/xml/ojs-version.xml

     Locally accessible url

                http://localhost/ojs/xml/ojs-version.xml

                or
                http://<baseurl>/ojs/xml/ojs-version.xml

* Edited the file **classes/core/Application.inc.php** and updated the following function
```
public function getVersionDescriptorUrl()
{
        return('http://pkp.sfu.ca/ojs/xml/ojs-version.xml');
}
```
to
```
public function getVersionDescriptorUrl()
{
        return('http://localhost/ojs/xml/ojs-version.xml');
}
```

**Comment by asmecher** [comment]
@gireeshcse, you can resolve this by setting `enable_beacon` and `show_upgrade_warning` to `Off` in `config.inc.php`.

**Comment by gireeshcse** [comment]
Thanks @asmecher. Setting both ```enable_beacon``` and ```show_upgrade_warning``` to ```Off``` in config.inc.php solved the issue.
