### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by dinaJamal11** [pkp/pkp-lib#7023]
Can you please support
I want to modify the information under each reviewer from the list to include the reviewer country under each reviewer. (add /assign reviewer tab)
I am currently using v3.3.0.4

**Comment by asmecher** [comment]
You're already getting support with this question at https://forum.pkp.sfu.ca/t/add-reviewers-country-in-add-reviewer-tab/67504. Please don't post the same question in several places.
