### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by loloapaige** [pkp/pkp-lib#7024]
Hello
I want some help. I have a requirement to send a PDF file in anemail sent to the author when his publication is accepted in the journal.

i think I have turned on sending emails to the authors when the publication is approved by this 
$notificationTypes = array(
	**NOTIFICATION_TYPE_APPROVE_SUBMISSION => true,**
		NOTIFICATION_TYPE_FORMAT_NEEDS_APPROVED_SUBMISSION => false,
			NOTIFICATION_TYPE_VISIT_CATALOG => true,);

I want to send the same text (approval message) that will be used in that notification but as PDF file to the author via email.
i hop my question is clear

**Comment by asmecher** [comment]
The support forum is the best place to ask questions like this; try posting there: https://forum.pkp.sfu.ca
