### ISSUE TITLE
[UI] Switching between languages in setup step 4 deletes OA Policy

### ISSUE THREAD

**Issue by dtwardy** [pkp/pkp-lib#703]
Occuring in 2.4.6

When entering setup step 4 and changing the form language and switching it back again, the field "Open Access Policy" gets deleted.

**Comment by asmecher** [comment]
@dtwardy, I can't reproduce this locally. Can you try the following query in MySQL to determine if perhaps there's something wrong with your locale settings?

    SELECT * FROM journal_settings WHERE setting_name='openAccessPolicy';
