### ISSUE TITLE
Import/Export plugin - remove get_class dependency for filter retrieval 

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#7034]
**Describe the bug**
There are some cases where the `get_class()` function is being used for retrieving class specific filter.  Namespaces introduction may result to unspecified filter when the get_class is being used

**What application are you using?**
 OJS, OMP or OPS main branch

**Comment by defstat** [comment]
@asmecher @NateWr 

**PR**
[pkp-lib]: #7035

**Comment by asmecher** [comment]
No, closing!
