### ISSUE TITLE
Can't access all journals from dropdown when exceeds viewport height

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7052]
**Describe the bug**
When the list of journals from the dropdown menu in the header is taller than the viewport, you can't access all journals unless you scroll to the bottom of the page. One user reported not being able to access them even on the bottom of the page from the plugins list.

**To Reproduce**
1. Have a bunch of journals in the journal switcher.
2. Reduce the viewport size so that not all journals appear on the screen when the dropdown is open.

**What application are you using?**
3.3.0-6

**Additional information**
See report in the [forum](https://forum.pkp.sfu.ca/t/3-3-0-6-journals-list-menu-not-scrolling-properly-when-there-are-too-many-hosted-journals/67516).

**Comment by librariam** [comment]
+1 from an institution with a large multi-journal install and long list to scroll through

**Comment by wangra8** [comment]
Hi All, I appreciate the suggested fix from the forum thread. I applied it to our build.css file although it works I have been reading that the build.css gets overwritten and it not the most "stable" way to apply the fix. If I add the css changes to one of the less files in /lib/pkp/styles/ folder. How would I rebuild the build.css file? Is there a tool for this? Or should I simply run lessc file.less file.css and move it to the appropriate location. I'd be happy to prepare a PR if I can get clarification on the build process. Thank you, take care.

**Comment by NateWr** [comment]
Hi @wangra8, I'm not sure if we'll merge the overflow solution suggested in the forum. I try to avoid multiple distinct scroll areas on the screen, as they tend to be UX hurdles for people. Our preferred solution will be a journal search feature like what is suggested in [this comment](https://github.com/pkp/pkp-lib/issues/6747#issuecomment-862181470):

![journal-switcher](https://user-images.githubusercontent.com/2306629/122189406-ce7b6700-ce88-11eb-8af7-13a401bd33bd.png)

This is something I hope to get to in 3.4, but I'm not yet sure it will happen.

> the build.css gets overwritten and it not the most "stable" way to apply the fix

Yes, each time you update this file will be overwritten. The most stable way to apply a CSS change would be to write a small plugin that loaded a CSS file on every backend page. You can learn more about writing a plugin in the [plugin guide](https://docs.pkp.sfu.ca/dev/plugin-guide/en/).

**Comment by pmangahis** [comment]
+1 from PS hosted institution with a large multi-journal install and long list to scroll through

**Comment by dallibs** [comment]
+1

**Comment by jardakotesovec** [comment]
We will include short-term fix to minor release of 3.4. Which is really just enabling scrolling when the menu gets higher than the screen and making maximum width bigger, so longer names are also readable. That should make it usable short term.

@Devika008 will look into, how we could rework it to improve overall UX for larger installs. That would come to some future version.


@asmecher Its minor change, maybe it could go to the next minor 3.4 release?
ui-library: https://github.com/pkp/ui-library/pull/278
ojs: https://github.com/pkp/ojs/pull/3993
omp: https://github.com/pkp/omp/pull/1434
ops: https://github.com/pkp/ops/pull/549

**Comment by asmecher** [comment]
Agreed, thanks! I merged the `ui-library` PR and cherry-picked it forward to `main`; I closed the other PRs.
