### ISSUE TITLE
OMP Google Scholar Plugin generates incorrect (not functioning) download link

### ISSUE THREAD

**Issue by gemusehandler** [pkp/pkp-lib#7054]
**Describe the bug**
The Google Scholar OMP plugin produces in the head incorrect download links.
In this way the plugin will not work.

This is de code in lines 121 to 128
```
switch ($availableFile->getData('mimetype')) {
case 'application/pdf':
$templateMgr->addHeader('googleScholarPdfUrl' . $i++, '<meta name="citation_pdf_url" content="' . $request->url(null, 'catalog', 'download', array($submission->getData('id'), $availableFile->getData('assocId'), $availableFile->getData('fileId'))) . '"/>');
break;
case 'text/xml' or 'text/html':
$templateMgr->addHeader('googleScholarPdfUrl' . $i++, '<meta name="citation_fulltext_html_url" content="' . $request->url(null, 'catalog', 'download', array($submission->getData('id'), $availableFile->getData('assocId'), $availableFile->getData('fileId'))) . '"/>');
break;
}
```

Changing the 'fileID' into 'id' solves the issue in my installation (line 123 and 126).
see for instance [BookRxiv](https://bookrxiv.ac/index.php/monograph/catalog/book/27) where this change is applied.

**fieldID** produces the link that results into a 404 File Not Found:
`<meta name="citation_pdf_url" content="https://bookrxiv.ac/index.php/monograph/catalog/download/27/62/159">
`

**id** produces a link that indeed downloads the correct file:
`<meta name="citation_pdf_url" content="https://bookrxiv.ac/index.php/monograph/catalog/download/27/62/246">
`
```
switch ($availableFile->getData('mimetype')) {
case 'application/pdf':
$templateMgr->addHeader('googleScholarPdfUrl' . $i++, '<meta name="citation_pdf_url" content="' . $request->url(null, 'catalog', 'download', array($submission->getData('id'), $availableFile->getData('assocId'), $availableFile->getData('id'))) . '"/>');
break;
case 'text/xml' or 'text/html':
$templateMgr->addHeader('googleScholarPdfUrl' . $i++, '<meta name="citation_fulltext_html_url" content="' . $request->url(null, 'catalog', 'view', array($submission->getData('id'), $availableFile->getData('assocId'), $availableFile->getData('id'))) . '"/>');
break;
}
```

**Comment by withanage** [comment]
@gemusehandler 

Hi  Frank,

thanks a lot for pointing out. Have created the PRs and  this will be roiled out with 3.3.0-7

**Comment by asmecher** [comment]
@withanage, don't forget the `stable-3_3_1` branch too!

**Comment by withanage** [comment]
@asmecher

stable-3_3_1 is also  added.

@gemusehandler  , also appreciate a testing round   and can you confirm and close ;-)

**Comment by gemusehandler** [comment]
@asmecher
It works, so I can confirm!

**Comment by asmecher** [comment]
Thanks, @gemusehandler! @withanage, please go ahead and merge anything that's still remaining, and close the issue.
