### ISSUE TITLE
Bug: Misspelling of `Separate` in OJS default text

### ISSUE THREAD

**Issue by benaltair** [pkp/pkp-lib#7059]
# Description 
Fairly simple but, if I'm not mistaken, the default text in the **Submission Preparation Checklist** has a typo. In the item below, the bold **seperate** should read sep**a**rate.

> All figures are placed within the text at the appropriate points. Figures should additionally be submitted as **seperate** files (see Author Guidelines).

I couldn't find this in any repos - I'm not sure where it's kept but happy to submit a PR.

# What application are you using?
 OJS version 3.2.1.2

# Screenshot
![image](https://user-images.githubusercontent.com/17771229/118176726-a52d6e00-b3e6-11eb-8daf-158e95bb28e8.png)

**Comment by asmecher** [comment]
@benaltair, I think this is customized text, i.e. not something in the OJS default text.

**Comment by benaltair** [comment]
@asmecher That would make sense 🤦🏼‍♂️ Thanks!
