### ISSUE TITLE
ONIX schema reference in native.xsd is no longer valid

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#7065]
**Describe the bug**
In https://github.com/pkp/omp/blob/main/plugins/importexport/native/native.xsd the [ONIX schema reference](http://ns.editeur.org/onix/3.0/reference) is no longer valid and leads to a 404. We're currently using `http://ns.editeur.org/onix/3.0/reference` which looks like it needs an update.

**What application are you using?**
OMP 3.3.0

**Additional information**
With the exception of [schema resources available for download](https://www.editeur.org/93/Release-3.0-Downloads/#Schema%20defs), I wasn't able to find an up-to-date URL replacement for the above at first glance.

**Comment by asmecher** [comment]
That's a namespace URI and doesn't actually have to resolve to a file. Is there a validation problem or something that you're running into?

**Comment by mfelczak** [comment]
Yes, we're working with a typesetter trying to validate XML ahead of importing content into OMP.

**Comment by mfelczak** [comment]
The typesetter ran into the following error:

`Failed to read schema document 'ONIX_BookProduct_3.0_reference_notstrict.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.`

**Comment by asmecher** [comment]
That file is available e.g. here: https://github.com/pkp/omp/blob/stable-3_3_0/plugins/importexport/native/ONIX_BookProduct_3.0_reference_notstrict.xsd

I don't think an XML validator will be looking for it at the URI in the initial description; the typesetter should be able to put it in the same place as the `native.xsd` schema, as `native.xsd` refers to `ONIX_BookProduct_3.0_reference_notstrict.xsd` as a local file.

**Comment by mfelczak** [comment]
Perfect, thanks!
