### ISSUE TITLE
Error in XML Schema for Import/Export

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#7093]
OJS 3.x

When loading the XML schemas for import/export into the Oxygen XML Editor
https://github.com/pkp/ojs/blob/main/plugins/importexport/native/native.xsd 
https://github.com/pkp/pkp-lib/blob/main/plugins/importexport/native/pkp-native.xsd
https://github.com/pkp/pkp-lib/blob/main/xml/importexport.xsd

the following validation error is reported by the Xerces processor for https://github.com/pkp/ojs/blob/main/plugins/importexport/native/native.xsd

"http://pkp.sfu.ca":citations and "http://pkp.sfu.ca":citations (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.

See https://www.xml.com/articles/2018/06/13/upa-xml-schema/ for an explanation.

Probably the error occurs because <element ref="pkp:citations" {...} already has been defined in  https://github.com/pkp/pkp-lib/blob/main/plugins/importexport/native/pkp-native.xsd and doesn't need to be defined again 
https://github.com/pkp/ojs/blob/main/plugins/importexport/native/native.xsd  (in <extension base="pkp:pkppublication" ..., line 47ff.)

**Comment by asmecher** [comment]
Thanks, @mpbraendle, I've removed the duplicate line (also for OMP and OPS). Ported to `stable-3_3_0` and `stable-3_3_1` where needed.
