### ISSUE TITLE
Update from OJS v3.2.1-1 fails with PHP fatal error

### ISSUE THREAD

**Issue by apcshields** [pkp/pkp-lib#7097]
I've been trying to update a production OJS server from v3.2.1-1 to any v3.3.0(-x). Each time, the update process fails with the error:

`mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function getConnection() on null in /[****]/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74`

I thought it was possible that something about the database had been corrupted, so I created a new database, made a fresh install of OJS v3.2.1-1, and then tried to update it to v3.3.0. The update failed with the same error.

We're using:

OJS v3.2.1-1
PHP v7.2.34
MySQL v5.7.29, using 'mysqli'

**Comment by NateWr** [comment]
Hi @apcshields, have a look at https://github.com/pkp/pkp-lib/issues/6703 where similar issues were addressed (particularly the recommendations in https://github.com/pkp/pkp-lib/issues/6703#issuecomment-771555833). It may be an issue with the web-based upgrade process and there is a suggestion at https://github.com/pkp/pkp-lib/issues/6703#issuecomment-772868354.

I'm going to close this as a duplicate. But if you aren't able to resolve the issue based on the comments in the other issue, please post in our [community support forum](https://forum.pkp.sfu.ca/c/questions/5) with details of what you've tried.
