### ISSUE TITLE
Custom email templates lost upon changing language configuration

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7098]
From https://forum.pkp.sfu.ca/t/records-in-email-templates-settings-are-deleted-when-enabling-forms-language-in-any-journal/68053 and https://forum.pkp.sfu.ca/t/ojs-3-2-1-1-email-templates-were-restored-to-default:

> I have found the email templates in OJS 3.2.1-1 dissapear immediatly after enabling one language on Website Settings → Setup → Language in the column “Forms”, at that moment all the personalized templates in that language on email_templates_settings are deleted (from all journals in the installation).

It appears that the email templates are removed when a locale is enabled (under "Forms" but probably elsewhere). This is happening due to...

1. [`LanguageGridHandler::saveLanguageSetting` calls `PKPContextService::restoreLocaleDefaults`](https://github.com/pkp/pkp-lib/blob/e6494e1b6c1798aa1d8e791e25f0df03a5733cef/controllers/grid/languages/LanguageGridHandler.inc.php#L86) (this call is context specific; see also [another similar call a few lines later](https://github.com/pkp/pkp-lib/blob/e6494e1b6c1798aa1d8e791e25f0df03a5733cef/controllers/grid/languages/LanguageGridHandler.inc.php#L94))
2. [`PKPContextService::restoreLocaleDefaults` then calls `PKPLocale::reloadLocale`](https://github.com/pkp/pkp-lib/blob/e6494e1b6c1798aa1d8e791e25f0df03a5733cef/classes/services/PKPContextService.inc.php#L556), which axes email templates _for all contexts_ (!)

**Comment by asmecher** [comment]
Applying this change in `lib/pkp` will prevent language resets in one journal from affecting templates site-wide: https://github.com/pkp/pkp-lib/commit/421ed8406b09fa01851296c8a0c7653e1a333554

**Comment by ajnyga** [comment]
Any change this can be ported for 3.2 as well?

**Comment by asmecher** [comment]
@ajnyga, https://github.com/pkp/pkp-lib/commit/421ed8406b09fa01851296c8a0c7653e1a333554 will apply directly to 3.2.x releases as well, but we're unlikely to release any more 3.2.x .tar.gz packages. Or are you working from the `stable-3_2_0` git branch and need that updated?

**Comment by jmvezic** [comment]
@asmecher Can this fix safely be applied to 3.2.1-4 manually? We're going to upgrade to 3.3 soon but this is an important fix to have until then.

**Comment by asmecher** [comment]
@jmvezic, the relevant change is a different one -- https://github.com/pkp/pkp-lib/commit/421ed8406b09fa01851296c8a0c7653e1a333554 -- and should apply to 3.2.1-4 cleanly.

**Comment by ajnyga** [comment]
Just leaving a note here that this same bug caused a situtation where reloading a locale in one context erased Component/Genre labels from all contexts.
