### ISSUE TITLE
Impossible to create institutional subscription if membership is required

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7100]
**Describe the bug**

This is sort of related to pkp/pkp-lib#4271 

If a journal manager defines an institutional subscription type and checks off the box requiring membership

"Subscriptions require membership information (e.g. of an association, organization, consortium, etc.) "

And then proceeds to attempt creation of a new institutional subscription, the form fails validation because the form lacks the membership field.  This isn't a problem if a user attempts to purchase a subscription themselves on the front end, because that form has it.  This is just in the management interface.

**What application are you using?**
Reported by hosted client in OJS 3.2.1 but appears to also be in 3.3

**Comment by jnugent** [comment]
Update.  I looked at this in 3.3 and it seems that what was implemented in 4271, the disabling of that checkbox if an institutional subscription is chosen, is working fine.  I thought that was merged into 3.2.1?

**Comment by asmecher** [comment]
Is this maybe a subscription type that was created before #4271 was merged in? It shouldn't be possible to create an institutional subscription type that requires membership information since 3.1.1-5.

**Comment by jnugent** [comment]
Hi @asmecher no, this is a newish 3.2.1-2 installation (upgraded to 3.2.1 in Nov 2020, using stable-3_2_1 at the time).  The subscription was created a week or so ago.  Looking at the subscription type form, there might be a small bug in the JS handler added in #4271 - when creating a new subscription type, if I select "institutional" in the radio button, the option to require membership greys out.  However, editing the existing one that they have created, the "institutional" radio button is selected already and cannot be changed, but I can toggle the membership option. 

I think this can be closed, though, unless you think that's still a bug from that.  If it's worth testing in 3.3, I can.

**Comment by asmecher** [comment]
Would you mind checking in 3.3? Thanks!

**Comment by jnugent** [comment]
Hey @asmecher  feel free to close this.  Things are fine in 3.3.

**Comment by asmecher** [comment]
Great, thanks!
