### ISSUE TITLE
Make the journal health report (STATISTICS_REPORT_NOTIFICATION) respect the template enabled/disabled flag

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7101]
See https://forum.pkp.sfu.ca/t/disabled-email-are-sent-out/68105/2:
> Despite having disabled the Editorial Activity email, there are still “journal helath reports” going out.

Since the journal editor can enable and disable the email template, the task should check this flag before sending the notification.

**Comment by NateWr** [comment]
This email is one of the notifications that each user can enable/disable in their user profile. Shouldn't that be the primary source of information on whether this email is sent?

I know that right now, we have several email templates that can be enabled/disabled, and this results in the underlying email notification being enabled/disabled. But this is counterintuive, because many email templates do not have a 1-to-1 relationship with email notifications. As part of the refactoring work that Vitaliy is doing in 3.4, we are splitting up email templates and events, so this approach to disabling the journal health report won't translate well to the next major version.

**Comment by asmecher** [comment]
I think we're seeing forum posts about this because many users have started receiving notifications that they aren't used to receiving, and are probably passing negative feedback to the journal. The journal is finding the "disable" button on that template, expecting it to inhibit the notifications entirely, but the button isn't doing anything.

If adjusting the code so that disabling the email template inhibits the task won't translate well to Vitaliy's 3.4 work, then agreed, we shouldn't introduce it now. But there probably should be a way to disable tasks entirely, rather than requiring each user to opt out of a notification. Maybe this would be better resolved as part of https://github.com/pkp/pkp-lib/issues/7105?

**Comment by NateWr** [comment]
Yeah I think that the email work for 3.4 is going to try to refactor how users opt-in/out of emails, which should make it easier for each user to opt-out of that email. I can see that a journal may wish to disable it completely, especially if some of their section editors are guest editors or other roles that they don't want to have data about the journal.

In my view, an optimal solution would be to provide a more prominent opt out in the email itself. Something like:

> Don't want to receive this report next month? You can [unsubscribe from this report](#).

Of course, we'd still need a way for journal managers to disable it completely. If you're ok waiting for 3.4 for this to be fixed, then @Vitaliy-1 and I can try to address it alongside the general notification management UI.

**Comment by asmecher** [comment]
Thanks, @NateWr, and I'm OK to wait for 3.4. I think this could be disabled entirely either on the level of the scheduled task or the notification, and don't have a preference for which is better in this case, but both kinds of disables will be needed elsewhere in the system.

**Comment by Vitaliy-1** [comment]
`canDisable` was moved from `EmailTemplate` to `Mailable` after refactoring, from this template specifically to  `PKP\mail\mailables\StatisticsReportNotify`. Leaving a reminder to test it in the new Mailable UI after implementation.

**Comment by NateWr** [comment]
I'm sorting this out now as part of #5716.

**Comment by NateWr** [comment]
This will be included in 3.4. As part of #5716, a new setting has been added to Settings > Workflow > Emails to enable/disable this email. On upgrade from 3.3, it will be set correctly according to the email template's enabled flag.
