### ISSUE TITLE
[OJS 3.3] Language parameter user.authorization.journalDoesNotPublish does not exist.

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#7102]
The language parameter user.authorization.journalDoesNotPublish does not exist in any PO files in OJS. I cannot find it on Weblate.
It is displayed when the journal has configured the Distribution option : "OJS will not be used to publish the journal's contents online.". If a user try to access an issue page or an article page, the parameter is displayed....this is not to happen quite often...
I would suggest, as a start, the following text: 

EN: Journal does not publish its content online.
FR_CA: La revue ne publie pas ses contenus en ligne.

Thanks!

**Comment by NateWr** [comment]
Confirmed in `stable-3_3_0`. In addition to adding the missing key in the `.po` file, let's also add a test to check this setting works.

**Comment by asmecher** [comment]
Thanks, @pilasou! I've added the two keys, and tested the feature.
