### ISSUE TITLE
[OJS] Failed Ajax Request or invalid JSON Request

### ISSUE THREAD

**Issue by goncalocruz77** [pkp/pkp-lib#7107]
Hi, I have an error in an application made with OJS. When I try to include magazine sessions I get the error Failed Ajax Request or invalid JSON Returned.

![Erro OJS](https://user-images.githubusercontent.com/14839168/121096684-0fa8b280-c7c9-11eb-983e-95d3e859d7b4.jpg)

![Erro OJS 2](https://user-images.githubusercontent.com/14839168/121096877-6a420e80-c7c9-11eb-8be6-c634c1f46ebe.jpg)

Has anyone had this problem and can you help me on how to solve it?

Note: I can create the categories, it works normal. The error is only in sessions.

**Comment by NateWr** [comment]
I'm going to close this for now, @goncalocruz77, but once you've checked your PHP error log feel free to post in our [support forum](https://forum.pkp.sfu.ca/c/questions/5) for more help.
