### ISSUE TITLE
The pubIds plugins not loaded for CLI in ImportExportPlugins

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#7108]
**Describe the bug**
When executing:
`php tools/importExport.php  MedraExportPlugin register journalPath articles articleId`
the error occurs:
"The specified objects could not be found."

Also, when exporting an article via CLI using NativeImportExportPlugin, the DOIs are not exported.

**To Reproduce**
s. above

**What application are you using?**
 OJS version 3.3.0.6 

**Additional information**
The `pub-id::doi` of the publications is not returned when using: `Services::get('submission')->get($submissionId);`
so the `$submission->getStoredPubId('doi')` in this line https://github.com/pkp/ojs/blob/main/classes/plugins/DOIPubIdExportPlugin.inc.php#L203 is not returning the correct result.
The DOIPubIdExportPlugin does not add the property `pub-id::doi` to the schema.

**Comment by bozana** [comment]
PRs:
ojs stable-3_3_0: https://github.com/pkp/ojs/pull/3145
ojs stable-3_3_1:
ojs main:

**Comment by bozana** [comment]
@NateWr, could you please take a look? If OK I will port to other branches...

**Comment by bozana** [comment]
@withanage, could you maybe test the fix with your OJS version?

**Comment by NateWr** [comment]
Hmm, I'm not that familiar with this plugin type. But the DOI object property should get added to the object's schema by the DOI plugin itself: https://github.com/pkp/pkp-lib/blob/main/classes/plugins/PKPPubIdPlugin.inc.php#L49. This should get loaded automatically by the dispatcher: https://github.com/pkp/pkp-lib/blob/main/classes/core/Dispatcher.inc.php#L157

Maybe the DOI export plugin bypasses the dispatcher when run in CLI?

**Comment by bozana** [comment]
Ah, OK, this is a good point @NateWr! This issue is then relevant for all ImportExport plugins, when using the CLI, because yes, the CLI does not use dispatcher, router,...
At least it is definitely relevant for DOIPubIdExportPlugin, but probably also for NativeExportImportPlugin, executeCLI function.
But, one more thing: it is not enough to just load the pubIds plugins, the register method should be called, right?

**Comment by bozana** [comment]
@NateWr, I have changed the solution, could you please take a look? Thanks a lot!

**Comment by NateWr** [comment]
@bozana that looks good to me. I wonder if every CLI tool should load these plugins, but that's a discussion for another issue.

**Comment by withanage** [comment]
@bozana 

thanks a lot for your fix. :+1: 

Actually,  where I found the bug in  OJS 3.2.1.

I applied your patch locally to OJS 3.2.1 and  am confirming  it works for the crossref plugin.

Actually, I am thinking, how this went unnoticed, cause may be everybody is using the acron plugin ;-)

Just created a PR from your changes.

PR
https://github.com/pkp/ojs/pull/3151
