### ISSUE TITLE
Use keywords (and subjects) in DataCite export

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#7109]
**Describe the bug**
A string is expected but array given in this line: https://github.com/pkp/ojs/blob/stable-3_3_0/plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php#L175
Write each subject into its own XML element.

**To Reproduce**

**What application are you using?**
 OJSS version 3.3.0.6

**Additional information**
Except that one XML element should be used for each subject, also keywords should be considered for this element, s. original implementation https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/importexport/datacite/classes/DataciteExportDom.inc.php#L463 (eventually also schema element description http://schema.datacite.org/meta/kernel-4/metadata.xsd)

Some function calls on SubmissionFile ($galleyFile) object is wrong and will be fixed with this issue.

**Comment by bozana** [comment]
PRs:
ojs stable-3_3_0: https://github.com/pkp/ojs/pull/3146
ojs stable-3_3_1:
ojs main:

**Comment by bozana** [comment]
@NateWr, may I ask you to take a look at this PR too?

**Comment by NateWr** [comment]
Looks good to me. :+1:
