### ISSUE TITLE
Reconsider data caching mechanisms

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7111]
**Describe the problem you would like to solve**
There are several places in the code that may suffer performance issues and can benefit from data caching. E.g.:

- Event Discovery uses Reflection classes/method to link listeners with events, which are rather slow. [Related issue](https://github.com/pkp/pkp-lib/issues/6970) and [discussion](https://github.com/pkp/pkp-lib/pull/7005#discussion_r625310974), Laravel docs: https://laravel.com/docs/7.x/events#event-discovery

- Locale files loading where it would be possible to move away from `AppLocale::requireComponents(...)` call; [Related issue](https://github.com/pkp/pkp-lib/issues/6328) 

**Describe the solution you'd like**
Consider implementing 3rd party tool, which will also reduce the maintenance burden. 
Think the least effortless path would be continuing integration of Laravel services and replace our CacheManager with Laravel's CacheServiceProvider. Without digging deep in the code the only outstanding work might be in binding Flysystem's filestorage (integrated as part of https://github.com/pkp/pkp-lib/issues/6057) with a container to use file cache without much code modification of the service itself; Laravel uses the same driver for filestorage, so shouldn't be a problem. 

Documentation on Laravel Cache and supported drivers: https://laravel.com/docs/7.x/cache

As part of this task, it's also needed to clean the cache from times to times, see: https://github.com/pkp/pkp-lib/issues/8922

**Additional information**
Despite the solution chosen, it would be great to have caching tool to be integrated through bindings with a [Container](https://github.com/pkp/pkp-lib/blob/129a6db5d9e1f6a98c2f022652a13a6cfaeb2dac/classes/core/PKPContainer.inc.php) to be available through Facade.

**Comment by diegoabadan** [comment]
Related to: https://github.com/pkp/pkp-lib/issues/3304

**Comment by asmecher** [comment]
I had to stop work on #3304 because it degraded performance compared with our old file-based caching; I suspect implementing https://github.com/pkp/pkp-lib/issues/6328 will decrease the reliance on that toolset and permit us to return to it without the same performance hit.

**Comment by jonasraoni** [comment]
I've added an `OPcache` cache driver to Laravel at #6328, but it has some drawbacks.

It can store any primitive data type and simple objects (`stdClass`), but if you're willing to store a more complex object it will require implementing the `__set_state` method.

**Comment by jonasraoni** [comment]
Think about ways to invalidate the cache if its internal data structure gets modified.

Example of breaking changes that might pass unnoticed, until new code gets deployed over an old cache, and something fails:
- User stores an object `/namespace/classA` which is later on renamed to `/namespace/classB`
- User stores array `['name' => 'Jonas']` which is later on changed to `['firstName' => 'Jonas']`
- Any addition/modification/removal has the potential to break the cache

Considering it might be costly/not simple to grab an object signature to use as a version, the simplest idea to address this issue is to invalidate the whole cache whenever an update is executed against the system.

**Comment by asmecher** [comment]
> the simplest idea to address this issue is to invalidate the whole cache whenever an update is executed against the system.

Absolutely, I don't think we want to add upgrade considerations to our "live" caches.

We do have a few cases where we're serializing data into the relational database, though, and need to be a little more careful there about things like class renames. I think our only current case is serialized payment information.

**Comment by asmecher** [comment]
@Vitaliy-1, any objections to deferring this issue past the release of 3.4? I don't think the uptake of events/listeners is so large and widespread yet that performance issues will surface.

**Comment by Vitaliy-1** [comment]
No objections! Event discovery works with our standard caching and it should be enough for now.

**Comment by asmecher** [comment]
Draft PRs (WIP):
- https://github.com/pkp/pkp-lib/pull/10109
- https://github.com/pkp/ojs/pull/4333
- https://github.com/pkp/omp/pull/1612
- (No PR required for OPS)

**Comment by asmecher** [comment]
I've replaced the old caching toolset (`lib/pkp/classes/cache/`) with Laravel's cache facade on an opcode cache -- I'll close this issue as resolved, though there's probably more work to do on caching closer to the 3.5 release.
