### ISSUE TITLE
A preview of metadata and uploaded files at step 4 of submission

### ISSUE THREAD

**Issue by Gypsop** [pkp/pkp-lib#7112]
Could you please add a preview of the metadata inputted and files uploaded before the author finish the submission? Now there is only a text notice and authors need to click on each step to make confirmation.

Some authors told us that it is stressful when they are making a submission, and hope there could be an overall preview of all the contents in the submission before clicking the "confirm and submit" button.

**Comment by NateWr** [comment]
Thanks  @Gypsop. We are planning to redesign our submission wizard in 3.4 and hope to include this.

**Comment by NateWr** [comment]
This is implemented in #7191, which will be included in 3.4.
