### ISSUE TITLE
Email template "Reset All" don't remove old templates

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#7115]
**Describe the bug**
When you upgrade a journal to 3.2.1-4 (and probably also to the last stable) old email_templates are kept.
This is fine (you don't want to lose your personalizations), but if you decide to reset them and you click on "Reset All" you expect old templates (for instance, refering to plugins that don't exist any more) will be removed, and they are not.

**To Reproduce**
1. Migrate to 3.x an old 2.x journal (that include old plugins like books for review) 
2. Go to https://foo.journal.org/management/settings/workflow
3. Click on 'Reset All'

**What application are you using?**
OJS 3.2.1-4.

**Additional information**

This is the list of templates AFTER clicking the "Reset All" button:

![imagen](https://user-images.githubusercontent.com/2779168/121570756-74ab1500-ca22-11eb-8422-82d10f59db35.png)

**Comment by marcbria** [comment]
As a temporary solution, I TRUNCANTE all email_templates table and then I INSERT the content of a clean OJS 3.2.1-4 installation (with same lang)... but I suspect not all journals will be allowed to reach the DB to do this.

**Comment by asmecher** [comment]
I think this is a defensible intended behaviour -- it resets any *used* email templates to their defaults but doesn't remove anything it doesn't know about. In cases where e.g. OJS 2.x supported a template but 3.x doesn't, it leaves the old templates in place in case we later re-introduce the same functionality, which would permit the 2.x template customizations to be maintained.

Is there an underlying problem you're looking to solve, e.g. the list of email templates is too long?

**Comment by marcbria** [comment]
Ok. I understand and I can buy it.

List is not much long, so is not really a big deal.
It's only that I though in this as an good opportunity to clean old data in the DB... as far is something final users will see but I can also buy arguments to keep it.

To documented it in detail: notice email_templates table also keep email_templates from langs enabled in any moment, that now are disabled. That is not a real problem because disabled lang templates are not shown, but is useless.

Closing the issue as it works as expected.

Thanks a lot Alec.
