### ISSUE TITLE
Add an optional email to notify reviewers of the results (accept/reject/revisions) of the review stage

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7118]
**Describe the problem you would like to solve**
Reviewers want to feel like reviewing is worth their time. Editors want to reward reviewers for their participation. 

**Describe the solution you'd like**
Reviewers should get an automated email letting them know the decision of the review (accept/reject/revisions). This should be configurable at the journal level to be automated. If no automated email is sent, editors could have an option to send it manually on a round after a decision is made.

**Who is asking for this feature?**
This was mentioned multiple times in the free text fields of the Tech Committee's community survey.

**Comment by asmecher** [comment]
This might be a dupe of: https://github.com/pkp/pkp-lib/issues/4834

**Comment by NateWr** [comment]
Ahh, ok. That's not exactly how I imagined it working (new email instead of BCC), but if this satisfies the demand for now, good enough for me.
