### ISSUE TITLE
Error submitting an article

### ISSUE THREAD

**Issue by luis575497** [pkp/pkp-lib#7121]
When trying to upload an article, nothing appears in the metadata section and I cannot continue the upload process.

OJS: 3.3.0.6

System info:
PHP: 8.0.6
Apache/2.4.47 (Unix) PHP/8.0.6
5.5.5-10.5.10-MariaDB

Log in php error_log
```[Mon Jun 14 17:50:48.768473 2021] [php:error] [pid 480] [client 127.0.0.1:43172] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /srv/http/ojs/lib/pkp/classes/submission/PKPSubmissionMetadataFormImplementation.inc.php:73\nStack trace:\n#0 /srv/http/ojs/classes/submission/SubmissionMetadataFormImplementation.inc.php(34): PKPSubmissionMetadataFormImplementation->addChecks()\n#1 /srv/http/ojs/lib/pkp/classes/submission/form/PKPSubmissionSubmitStep3Form.inc.php(34): SubmissionMetadataFormImplementation->addChecks()\n#2 /srv/http/ojs/classes/submission/form/SubmissionSubmitStep3Form.inc.php(27): PKPSubmissionSubmitStep3Form->__construct()\n#3 /srv/http/ojs/lib/pkp/pages/submission/PKPSubmissionHandler.inc.php(130): SubmissionSubmitStep3Form->__construct()\n#4 /srv/http/ojs/lib/pkp/classes/core/PKPRouter.inc.php(395): PKPSubmissionHandler->step()\n#5 /srv/http/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()\n#6 /srv/http/ojs/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()\n#7 /srv/http/ojs/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch()\n#8 /srv/http/ojs/index.php(68): PKPApplication->execute()\n#9 {main}\n  thrown in /srv/http/ojs/lib/pkp/classes/submission/PKPSubmissionMetadataFormImplementation.inc.php on line 73, referer: http://localhost/ojs/index.php/prueba/submission/wizard/2?submissionId=1```

**Comment by asmecher** [comment]
OJS 3.3.0-x users before 3.3.0-7 can resolve this by applying https://github.com/pkp/pkp-lib/commit/50a8e8970131fcebf6db036e49b8321650f2157a in the lib/pkp subdirectory, or by downgrading from PHP8 to PHP7.
