### ISSUE TITLE
Convert SubmissionFileService to the new Repository/DAO/Map pattern

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7125]
The `submissionFile` entity needs to be converted to use the new pattern for DAOs, Maps and Repositories introduced in #5328. This requires the following:

- [ ] Convert the DAO to extend `EntityDAO` and use type hints.
- [ ] Convert the `SubmissionFileService` to a repository .
- [ ] Convert `SubmissionFileService::getProperties()` to a Map that extends `PKP\core\maps\SchemaMap`. 
- [ ] Add any necessary methods to `SubmissionFileService` so that direct access to the DAO is not required.
- [ ] Refactor existing uses of `DAORegistry::getDAO('SubmissionFileDAO')` to use the repository instead.

**Comment by henriqueramos** [comment]
Hello everyone!

Below are the pull requests on pkp-lib, omp, ops and ojs for this task. Code review and comments are appreciated.

https://github.com/pkp/omp/pull/995
https://github.com/pkp/ops/pull/167
https://github.com/pkp/ojs/pull/3160
https://github.com/pkp/pkp-lib/pull/7166

Thank you!

**Comment by henriqueramos** [comment]
Forgot to add those other pull requests.

https://github.com/pkp/usageStats/pull/50
https://github.com/asmecher/lensGalley/pull/51

**Comment by NateWr** [comment]
Great work @henriqueramos! I've had a look over the PRs to check for style/consistency with the new patterns and it all looks great. I've left a few comments, but I didn't do a full review or test the code in operation. I think Alec has been working with you on that so I'll leave it to him to do the final review and determine when to merge. :+1:

**Comment by henriqueramos** [comment]
Hey @asmecher, @NateWr ! So, we are in time for another code review round!

I think this is will be the latest one for this task.

Thank you!!

[pkp/omp#995](https://github.com/pkp/omp/pull/995)
[pkp/ops#167](https://github.com/pkp/ops/pull/167)
[pkp/ojs#3160](https://github.com/pkp/ojs/pull/3160)
[pkp/usageStats#50](https://github.com/pkp/usageStats/pull/50)
[asmecher/lensGalley#51](https://github.com/asmecher/lensGalley/pull/51)
#7166

**Comment by henriqueramos** [comment]
@asmecher Every PR it's green. We could merged it?

[pkp/omp#995](https://github.com/pkp/omp/pull/995)
[pkp/ops#167](https://github.com/pkp/ops/pull/167)
[pkp/ojs#3160](https://github.com/pkp/ojs/pull/3160)
[pkp/usageStats#50](https://github.com/pkp/usageStats/pull/50)
[asmecher/lensGalley#51](https://github.com/asmecher/lensGalley/pull/51)
#7166

**Comment by asmecher** [comment]
@henriqueramos, I've merged all the PRs referenced [in the comments above](https://github.com/pkp/pkp-lib/issues/7125#issuecomment-932831159):

- pkp/omp#995
- pkp/ops#167
- pkp/ojs#3160
- #7166
- pkp/usageStats#50
- asmecher/lensGalley#51

Did I miss any?

Thanks!!!

**Comment by NateWr** [comment]
Sorry, I should have caught this in the code review. These PRs rename the Repo accessor method from `Repo::submissionFiles()` (plural) to `Repo::submissionFile()` (singular) to match the other method names.

I also ran into a bug with the `fromRow` method's array key setting. See https://github.com/pkp/pkp-lib/pull/7536/commits/44161850e301217449b2cb525de8ca9e0f15891f.

Finally, I found a reference to `Services::get('submissionFile')` in the QuickSubmit plugin so there's a PR for that.

https://github.com/pkp/pkp-lib/pull/7536
https://github.com/pkp/ojs/pull/3247
https://github.com/pkp/omp/pull/1038
https://github.com/pkp/ops/pull/205
https://github.com/asmecher/lensGalley/pull/52
https://github.com/pkp/usageStats/pull/51
https://github.com/pkp/quickSubmit/pull/56
