### ISSUE TITLE
Convert the GalleyService to the new Repository/DAO/Map pattern

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7126]
The `galley` entity needs to be converted to use the new pattern for DAOs, Maps and Repositories introduced in #5328. This requires the following:

- [ ] Convert the DAO to extend `EntityDAO` and use type hints.
- [ ] Convert the `GalleyService` to a repository .
- [ ] Convert `GalleyService::getProperties()` to a Map that extends `PKP\core\maps\SchemaMap`. 
- [ ] Add any necessary methods to the galley Repository so that direct access to the DAO is not required.
- [ ] Refactor existing uses of `DAORegistry::getDAO('...')` for `ArticleGalleyDAO` and `PreprintGalleyDAO` to use the repository instead. (An exception can be made for the `getExportable` method and the pub ID methods. See `PKP\publication\DAO`.)

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/issues/7126

**Comment by NateWr** [comment]
The following PRs adapt @withanage's work on the Galley repository, move the galley classes into pkp-lib, and remove references to the `ArticleGalley` classes. If the tests pass, I will roll out these changes to OPS/OMP.

@asmecher are you ok with me moving the `Galley` classes into pkp-lib? This will save us some code duplication across OJS and OPS. And in the future, I hope to [use galleys in OMP](https://github.com/pkp/pkp-lib/issues/6702).

PRs:
https://github.com/pkp/pkp-lib/pull/7821
https://github.com/pkp/ojs/pull/3357
https://github.com/asmecher/lensGalley/pull/57

**Comment by asmecher** [comment]
> @asmecher are you ok with me moving the Galley classes into pkp-lib? 
Yes -- we could perhaps revisit the use of `Representation` as the abstract term for galley-like concepts in each app? Galley is already confusing enough.

**Comment by NateWr** [comment]
@asmecher sure. Can we revisit the name at a later date or did you want to try to get it in for this 3.4 refactor? (I've left "article galley" in place for the grids and things, so would take a lot of work to unpick everything.)

**Comment by NateWr** [comment]
@asmecher do you have time to do code review on the PRs in this comment? https://github.com/pkp/pkp-lib/issues/7126#issuecomment-1087385627

It's mostly straightforward, but there is a fair amount of work in some gnarly places, like import/export filters. It'd be good to get a second eye at least on those parts.

(Now that I think of the import/export filters, I remember that the names get saved to the database. Do I need a migration to update them or do they get updated automatically during an upgrade?)

**Comment by asmecher** [comment]
> (Now that I think of the import/export filters, I remember that the names get saved to the database. Do I need a migration to update them or do they get updated automatically during an upgrade?)

Not yet -- though we'll have to cross that bridge before we remove the namespace compatibility stuff. The type descriptions (e.g. `inputType="class::lib.pkp.classes.galley.Galley"` in the filter XML) are checked by `lib/pkp/classes/filter/ClassTypeDescription.inc.php`. It takes the type and splits it into package name (`lib.pkp.classes.galley`) and class name (`Galley`). Only the class name is checked using `instanceof`; the package name is currently not used.

**Comment by asmecher** [comment]
Also, thanks, @NateWr -- I've reviewed the PRs linked above. It looks fairly clean to me; if there's something else in particular you're uncertain about, please point me to it.
