### ISSUE TITLE
Convert the SectionService to the new Repository/DAO/Map pattern 

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7128]
The `section` entity needs to be converted to use the new pattern for DAOs, Maps and Repositories introduced in #5328. This requires the following:

- [ ] Convert the DAO to extend `EntityDAO` and use type hints.
- [ ] Convert the `SectionService` to a repository .
- [ ] Adapt the schema for add/edit operations and add methods to add/edit/delete users to the DAO/Repository.
- [ ] Convert `SectionService::getProperties()` to a Map that extends `PKP\core\maps\SchemaMap`. 
- [ ] Add any necessary methods to `SectionService` so that direct access to the DAO is not required.
- [ ] Refactor existing uses of `DAORegistry::getDAO('SectionDAO')` to use the repository instead.

PRs:
- https://github.com/pkp/pkp-lib/pull/8604
- https://github.com/pkp/ojs/pull/3741
- https://github.com/pkp/omp/pull/1319
- https://github.com/pkp/ops/pull/455

**Comment by bozana** [comment]
@NateWr, could you please review the PRs above?

**Comment by bozana** [comment]
Thanks a lot @NateWr!
