### ISSUE TITLE
Convert the IssueService to the new Repository/DAO/Map pattern

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7129]
The `issue` entity needs to be converted to use the new pattern for DAOs, Maps and Repositories introduced in #5328. This requires the following:

- [ ] Convert the DAO to extend `EntityDAO` and use type hints.
- [ ] Convert the `IssueService` to a repository .
- [ ] Adapt the schema for add/edit operations and add methods to add/edit/delete users to the DAO/Repository.
- [ ] Convert `IssueService::getProperties()` to a Map that extends `PKP\core\maps\SchemaMap`. 
- [ ] Add any necessary methods to `IssueService` so that direct access to the DAO is not required.
- [ ] Refactor existing uses of `DAORegistry::getDAO('IssueDAO')` to use the repository instead.

**Comment by ewhanson** [comment]
Hey @asmecher and @NateWr, I've put together a set of draft PRs for review on everything Issue EntityDAO related. I have a few specific questions remaining and I've added these as comments within the code in each PR. I don't think there should be anything for OMP or OPS as the Issue work was specific to OJS, but let me know if there's anything that would need updating there as well. Thanks!

PRs:
pkp/ojs#3162
#7195
pkp/crossref-ojs#3
pkp/citationStyleLanguage#81
pkp/orcidProfile#184
asmecher/lensGalley#50

**Comment by ewhanson** [comment]
Hey @NateWr and @asmecher, I've gone through and and addressed your feedback. The last major thing to sort out now is how to handle ordering by current issue now that I've refactored that to be part of the journal rather than each individual issue. I left a comment at the specific place in the Issue collector where that had previously been happening. Thanks!

**Comment by asmecher** [comment]
All merged -- congratulations and thanks, @ewhanson!
