### ISSUE TITLE
Add chapter landing pages and support switching between versions

### ISSUE THREAD

**Issue by nongenti** [pkp/pkp-lib#7132]
**Describe the bug**
A URL that leads to a chapter with no version should always go to the most recent published version of that chapter.  For now, every new version the chapter id changes and there is no way to get the id from the source chapter. To build a chapter landing page with the possiblity to show different versions of a chapter, a chapter needs to know its source chapter id. Thats also important for urls of registered chapter DOIs.
A solution could be to add a source_chapter_id property.

**What application are you using?**
 OMP 3.3.0

**Additional information**
***Example***
I've a chapter with id 8986. I register the chapter DOI by datacite. That way datacite saves an url for a chapter landing page. Part of this url will be the chapter id (https://omp.example.org/index.php/{press}/catalog/book/{book_id}/chapter/8986).
Now I create a new version and the chapter id changes to 9643. So the url by datacite is wrong now. 

Or I'm on https://omp.example.org/index.php/{press}/catalog/book/{book_id}/chapter/9643 and want to show version 1 with version id 411 of this chapter, but there exists no https://omp.example.org/index.php/{press}/catalog/book/{book_id}/version/411/chapter/9643, there is only https://omp.example.org/index.php/{press}/catalog/book/{book_id}/version/411/chapter/8986.

That's no problem, if it would be possible to identify the source chapter id. Chapter 9643 has to know, that its source id is 8986.

**Comment by NateWr** [comment]
cc @withanage this is going to be related to #7003. I think core OMP doesn't support chapter landing pages, right? Is this a modification you've made @nongenti?

**Comment by nongenti** [comment]
That's right. I'm still working on this modification and can't finished it without a solution for the problem above. Some days ago @asmecher told me, he would prefer this modification as a part of OMP than as a plugin. So, if the solution with a source_chapter_id property is fine  for all, I can do these changes as part of the chapter landing pages modification.

**Comment by NateWr** [comment]
That's great, @nongenti. Yes, I think the `source_chapter_id` property is good approach. One thing to think through is what happens in cases where chapters change between versions. So two cases to consider:

- A chapter in a new version that doesn't exist in an old version.
- A chapter in an old version that doesn't exist in a new version.

**Comment by nongenti** [comment]
Hi @NateWr,
if a chapter exists in a new version and not in an old version there will be no link to the old version and an short information on the chapter landing page.
![Screenshot 2021-09-22 at 11-33-03 Test Chapter 2 d Ups TestPress](https://user-images.githubusercontent.com/78475910/134320185-28e14211-48b3-47cb-9cf8-d04af7ef924b.png)

If you use an url to get a version of a chapter, that not exists, there is a redirect to the most recent version of the chapter and a notice.

![Screenshot 2021-09-22 at 11-33-33 Test Chapter 2 d Ups TestPress](https://user-images.githubusercontent.com/78475910/134320845-2e9ff729-0590-4acb-943b-59aedca164bb.png)

You can also find a parameter in the new url that contains the requested version.
Example: 
Requested url: https://.../catalog/book/1/version/1/chapter/3
But there is no chapter with source_chapter_id 3 in version 1.  
So redirect to: https://.../catalog/book/1/chapter/3?reqVersion=1

A Chapter in an old version that doesn't exists in a new version should not happen in many cases. If it happen, then it works like above. The most recent version in this case is the last existing version of the chapter.


I also have two questions:

1. Viewer back link
A viewer, like the pdf-viewer, needs to know whether the call was from a book or a chapter landing page. The viewer need this information to create the correct back link. To solve this I would prefer to add chapter information in url if a viewer is called by a chapter landing page.
Example:
On a book landing page link to file looks like this: https://.../catalog/view/{submissionId}/{publicationFormatId}/{fileId}
On a chapter landing page link to the same file could looks like this: https://.../catalog/view/{submissionId}/chapter/{sourceChapterId}/{publicationFormatId}/{fileId}
or with version: https://.../catalog/view/{submissionId}/version/{publicationId}/chapter/{sourceChapterId}/{publicationFormatId}/{fileId}
Do you agree with this solution?

2. Issue [#5338](https://github.com/pkp/pkp-lib/issues/5338):  Separate licenses for each chapter in OMP
If you agree, then I would include this too. For me it makes sense do it together, because I've to make changes at the same files. If you prefer a separate solution, its okay for me, too.

I think, I can finish chapter landing page enhancement next week.

**Comment by NateWr** [comment]
Thanks @nongenti, that all sounds good. When an older version exists without this chapter, can we adjust the message to appear when the chapter was first created? That would look like:

> *Versions*
> 2017-02-22 (3)
> [2017-02-14 (2)](#) — Chapter created
> 2017-02-11 (1)

> If you use an url to get a version of a chapter, that not exists, there is a redirect to the most recent version of the chapter and a notice.

That works. Although I'd be tempted to just return a 404 in these cases. 

> Viewer back link

The URL approach you describe could work. However, I'm concerned that the URL routing is getting really complicated. I also want to avoid too many duplicate URLs for the same content. I wonder if for OMP we shouldn't consider an alternative approach that always provides backlinks based on the file. If the file is not assigned to a chapter, it would be like it is now:

> 🠐 Back to [{$submissionTitle}](#)

If the file is assigned to a chapter, it would look like:

> 🠐 Back to [{$chapterTitle}](#) in [{$submissionTitle}](#)

This way our URLs don't need to get any more complicated, and users can benefit from both navigation options regardless of how they got to the page.

>  Separate licenses for each chapter in OMP

:+1:  sounds good. Beware though that may impact our import/export scripts, so you may need to dive into that to add support for the additional license data.

**Comment by nongenti** [comment]
Hi @NateWr,
I've made my commits for the chapter landing pages. Would you review them?

For now it's without separate licenses for chapters and without  backlinks based on file. I'm still working on both.
Should I write a function in SubmissionFile.inc.php like "getBacklink( $context ) : array"? I would return an array. First entry is a backlink to volume landing page. Second entry exists only if the file is assigned to a chapter and contains the backlink to chapter landing page.

**Comment by NateWr** [comment]
Can you open a PR for each repository where changes need to be made, and add a comment with the links here? Open the PRs against the `main` branch.

**Comment by nongenti** [comment]
https://github.com/pkp/pkp-lib/pull/7370
https://github.com/pkp/omp/pull/1012

**Comment by NateWr** [comment]
Thanks @nongenti, all merged! :tada: Thanks for your patience working through all the details and your diligent responses to code reviews. I've filed a separate issue to write some integration tests for chapter landing pages at https://github.com/pkp/pkp-lib/issues/7462. You're not obligated to work on it but it would be good to get some basic tests in place before too long.

**Comment by isgrim** [comment]
Woohooo! Major work thanks Christian @nongenti and Nate @nate !

**Comment by nongenti** [comment]
Thanks @NateWr for the good cooperation!

**Comment by NateWr** [comment]
@amandastevens this may effect documentation for OMP 3.4.
