### ISSUE TITLE
[OPS] Request authors to inform preprint "relation" during submission

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#7134]
**Describe the problem you would like to solve**
When authors submit a manuscript, there is nowhere where they can inform about the status of the preprint. As server managers, we can't tell whether the manuscript has been submitted or not to a journal. We can only _guess_ that it hasn't been submitted to a journal at the point of submission to our server, but that is nothing but a guess. 

**Describe the solution you'd like**
We need authors to fill out the "Relations" field during the submission process.

**Who is asking for this feature?**
Server managers, authors.
This would overall increase transparency of submitted and posted preprints.

**Comment by NateWr** [comment]
Thanks @alexxxmendonca. Some additional information about the reason behind this request: authors can set the relations field before or after they post their preprint, but they are never prompted to do so. Most will never see or consider it, so there needs to be a prompt before the item is posted. 

The submission wizard seems like the best place for this, but it could also be requested at the moment a preprint is posted, which would provide a prompt with every new version.

**Comment by ajnyga** [comment]
Which solution do you prefer?
1) Adding this to the submission wizard
2) Adding this to the publishing form?
3) both

**Comment by NateWr** [comment]
For now, I'd suggest adding information to the publishing form, similar to DOIs in OJS, which says what the current relations status is. We can add an item to the submission wizard separately as part of #7191.

The information added to the publishing form can look something like this:

| | Related Publication |
| --- | --- |
| ✘ | This preprint has not been published elsewhere. |

| | Related Publication |
| --- | --- |
| ✔ | This preprint has been published, but no DOI is available yet. |

| | Related Publication |
| --- | --- |
| ✔ | This preprint has been [published](#). |

**Comment by ajnyga** [comment]
OPS: https://github.com/pkp/ops/pull/206
@NateWr can you review. I did not add all the new translations like in your sketch, happy to do so if needed.
