### ISSUE TITLE
OJS don't replace the galley postfix in the url

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#7138]
**Describe the bug**
After moving from 2.x to 3.2.1-4, in some journals I'm getting reports from google complaining about 404 pages. Those errors are raised because OJS is only translating partially the "numbered-url", missing the galley  "URL Path".

**To Reproduce**
Let me describe with a real example. When you visit a "numbered-URL" like this one:

1. https://revistes.uab.cat/periferia/article/view/645/434

OJS will notice you have a "URL Path" chunk for the article, so will translate it and will redirect you to this url:

- https://revistes.uab.cat/periferia/article/view/v23-n2-prat/434

Instead of going to the full path:

- https://revistes.uab.cat/periferia/article/view/v23-n2-prat/645-pdf-ca

As you will notice, the article's part is perfectly translated, but last postfix (the galley chunk) it's not. OJS keeps "/434" instead of going to "/645-pdf-ca".

**What application are you using?**
 OJS 3.2.1-4 (single tenant)

**Additional information**
Even in some cases we got this error because editors published before setting the public_url, the "numbered-url" should still be valid (and used to be in ojs 2.x). Not setting the public_url is a usual practice in journals with a "forthcoming" section, where public_url of the galleys are semantic (include volume, number, whatever...) and are not set until the article is published in a final number.

This was initially posted in forum at:
https://forum.pkp.sfu.ca/t/ojs-dont-replace-the-galley-postfix-in-the-url/68149?u=marc

**Comment by NateWr** [comment]
Some things have changed in 3.3.x, so it would be worth trying to reproduce this in 3.3.0-6.

**Comment by NateWr** [comment]
I was able to reproduce this in 3.3.

**Comment by NateWr** [comment]
The following PR fixes this issue. However, it's not clear to me that it should every arise. These URLs shouldn't exist in the wild, and they may just be old entries from Google. @marcbria did OJS 2.x not support named urls? And if not, where are your named URLs coming from? Are these publisher IDs that were used internally, that as part of the upgrade to 3.2 have become public urlPaths? It could be that the better solution in your case is to revert to the original URLs (ie - remove the `urlPath` from these publications). If those are the original URLs, the new URLs may be accidental rather than intentional.

PR:
https://github.com/pkp/ojs/pull/3156

**Comment by marcbria** [comment]
Hi Nate,

Thanks a lot for your time and your work.

Those url are following the recommendations we gave our journals to make the urls more semantic. 

Taking this example:
https://revistes.uab.cat/periferia/article/view/v23-n2-prat/645-pdf-ca

- The "v23-n2-prat" segment is talking about the article (volume 23, number 2, author surname is prat).
- The "645-pdf-ca" segment is talking about the galley (id 645, format pdf, lang catalan).

Removing the urlPath of those articles (for 50 journals with 10 years of history) is a huge task and will impoverish the SEO quality.

> These URLs shouldn't exist in the wild, and they may just be old entries from Google.  And if not, where are your named URLs coming from?
I don't know if I catch you. Those are the regular urls we like to use refer a PDF... (coming from OJS from the urlPath submitted by editors).

> Are these publisher IDs that were used internally, that as part of the upgrade to 3.2 have become public urlPaths? 
They are not internal urls. Is the public name assigned by OJS to the galleys.
You can see them shared to the public in any of our journals:
https://papers.uab.cat/article/view/v106-n2-poy

>  If those are the original URLs, the new URLs may be accidental rather than intentional.
Sorry, but I'm completely lost here. :-/

**Comment by marcbria** [comment]
> The following PR fixes this issue.

I missed to say that I don't have any ojs 3.3 yet (too much upgrade issues) but if you like I can try the patch in 3.2 and see what happens.

**Comment by NateWr** [comment]
> I can try the patch in 3.2 and see what happens.

I think there's a good chance this will apply to 3.2 without too much trouble.

> Sorry, but I'm completely lost here.

That's my bad. So, the original problem you described is when someone visits the following URL:

```
/article/view/645/434
```

However, you described articles that have a `urlPath` for both the article and the galley:

```
/article/view/v23-n2-prat/645-pdf-ca
```

So I'm wondering when would someone find and visit the first URL? OJS should always use the second one. For lack of a better way to put it, the first URL should not be considered valid.

**Comment by marcbria** [comment]
> So I'm wondering when would someone find and visit the first URL? 
> OJS should always use the second one. For lack of a better way to put it, the first URL should not be considered valid.

I don't see any problem in keeping both if the alias ("/article/view/v23-n2-prat/645-pdf-ca") is permanent redirected to the final url ("/article/view/645/434")... I also find benefits in this double naming because you can keep the semantic naming for SEO and the numeric one for management (when doing editorial work).

Probably it's because I come from drupal (that keeps old urls like "/node/645" even when you create an alias like "/about").

> I think there's a good chance this will apply to 3.2 without too much trouble.

Ok. I will test it this week.

Thanks a lot Nate!

**Comment by marcbria** [comment]
Sorry for the delay.

I replaced the modified file in ojs 3.2.1 fails.
When I cherry-picked the changes it worked like a charm.

@NateWr do you want me to make a PR to stable-3.2.1?

**Comment by NateWr** [comment]
If it's easy to cherry-pick then I will backport to `stable-3_2_1` after I merge to `stable-3_3_0`.

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `stable-3_2_1`, `stable-3_3_1` and `main`.
