### ISSUE TITLE
failed ajax request or invalid json returned OMP

### ISSUE THREAD

**Issue by jmjaimesa** [pkp/pkp-lib#7142]
Hello, I installed the latest version of OMP and when adding new users I get the following error: " failed ajax request or invalid json returned".
Would someone be so kind to tell me how to solve this problem, Thank you.

**Comment by asmecher** [comment]
@jmjaimesa, could you post on our support forum (https://forum.pkp.sfu.ca), including your specific OMP version? That's the best place to get help. (Search there to see if someone else has answered your question first.)
