### ISSUE TITLE
[OMP] Native import CLI not working

### ISSUE THREAD

**Issue by hcuser12** [pkp/pkp-lib#7143]
**Description**
Incorrect use of method `importSubmissions` when running via CLI.
Error is in file `NativeImportExportPlugin.inc.php`, method `executeCLI` at line 304 - it should be called like: `$this->importSubmissions($xmlString, $deployment)` - without `$filter` (or should be change to match import plugin for OJS).

**How to reproduce**
1. Run this command: `php7.4 tools/importExport.php NativeImportExportPlugin import omp-sample.xml test admin` - where:
* `omp-sample.xml` is https://gist.github.com/hcuser12/03db549d27782bd1a601cb295f94c8b0
* `test` is my test press
* `admin` is my user
2. In console we get error `PHP Fatal error:  Uncaught Error: Call to a member function getSubmissionsNodeName() on string` which means nothing, abut true error.

**Application**
OMP, official 3.3.0-6 version - default locale 'pl_PL' (with 'en_US' also installed).

**Comment by asmecher** [comment]
@defstat, could you take a look when you're available?

**Comment by hcuser12** [comment]
@asmecher @defstat 
Any news? Is there any chance it will be fixed soon?

**Comment by defstat** [comment]
@asmecher 

**PR**
[OMP] : pkp/omp#1119

@hcuser12 Thank you for finding this. Could you check whether the above change resolves your issue?

**Comment by asmecher** [comment]
@defstat, I've merged https://github.com/pkp/omp/pull/1119, but there are some additional things here to be looked over...
- [ ] Does https://github.com/pkp/omp/pull/1119 need forward-porting to `main`?
- [ ] Could you review https://github.com/pkp/pkp-lib/pull/7201?
- [ ] Could you review https://github.com/pkp/omp/pull/994?
Thanks!

**Comment by defstat** [comment]
Thanks @asmecher. The `main` branch has a totally different code than `stable-3.3.0`. This change does not seem to need porting to `main` branch. Also reviewed the PRs above

**Comment by asmecher** [comment]
@jonasraoni, I see @defstat has reviewed your PRs above (https://github.com/pkp/pkp-lib/pull/7201 and https://github.com/pkp/omp/pull/994) but I'm not sure if you've addressed his questions; also it's hard to know what parts of this need forward-porting to `main`; I'd recommend...
 - Make sure PRs address the issue they're filed with (update the issue to include a list of addressed issues if necessary -- checkboxes are useful for this)
 - Maintain fixes in separate commits
 - Co-develop against `main` and `stable-3_3_0` to ensure that you keep parity at the same time.

**Comment by jonasraoni** [comment]
@asmecher As the @defstat's PR has been merged, I'll close this issue. The PRs I've mentioned above already have their own issue.
