### ISSUE TITLE
[OJS 3.3.0.3] Some user_settings values cannot be edited out due to errors in the database

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#7146]
This is related to: https://forum.pkp.sfu.ca/t/null-values-in-user-settings-safe-to-remove/68272

I noticed that my `user_settings` table has  a lot of NULL values in `assoc_type` and `assoc_id` columns. If a user has such setting with a NULL value in one of those columns he cannot update his profile. Even though the new value is saved on the database (usually with `assoc_id` and `assoc_type` equal to 0) the row with NULL values remain there and is prefered when displaying information.

This has an effect even on displaying lists, where the same profile can appear multiple times due to those NULL values rows being processed more than once (I guess). There were many users on our "select reviewer list" that were listed 2, 3 or even 4 times.

Is NULL a proper value for those columns? On my table I've seem only NULL, 0 and 256 for the `assoc_type`, and NULL, 0 and the journals ids for the `assoc_id`.

**Comment by asmecher** [comment]
@luizbgomide, I'll close this issue in favour of the forum discussion that's already open, and send a reminder to the support team to have a look.

**Comment by luizbgomide** [comment]
Ok, I just opened the issue because I think there must be some bug in the migration procedure, and I thought that maybe o should have posted here first instead of the forum. But it is fine to continue over there.
