### ISSUE TITLE
Copyeditor sometimes gets "The current role does not have access to this operation." for assigned articles

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#7148]
**Describe the bug**
A copy editor reported that is unable to reach some articles (with others all is fine) and gets this error:
![imagen](https://user-images.githubusercontent.com/2779168/122777119-067d1280-d2ac-11eb-9cb9-6882706a8365.png)

**To Reproduce**
It happens in a journal that we just migrated from ojs 2.4 to 3.2.
I was not able to reproduce it in a clean installation, so it could be related with the data integrity.

**What application are you using?**
OJS 3.2.1-4

**Additional information**
As was suggested in forum for similar cases, I checked the `submission_files` table for an article that works (2965) and other that does NOT work (2933) with the following query:

```
SELECT file_id, revision, source_file_id, source_revision, submission_id, file_stage, viewable, date_uploaded, date_modified, assoc_id, genre_id, uploader_user_id, assoc_type, original_file_name
FROM `submission_files`
WHERE (`submission_id` = '2933' OR `submission_id` = '2965')
AND file_stage = 4 AND revision = 2
ORDER BY `submission_id` DESC
LIMIT 50

```

And I can't see anything relevant between both rows:

![imagen](https://user-images.githubusercontent.com/2779168/122778340-34af2200-d2ad-11eb-916c-61caae38ae98.png)

I can package (truncate some tables and overwrite files to 0) deliver the full journal (inside a docker?) if you like.

Issues that could be related:
- https://forum.pkp.sfu.ca/t/copyeditor-may-download-some-files-and-some-not-dont-understand-why/46345/9
- https://forum.pkp.sfu.ca/t/designer-sometimes-has-no-rights-to-download-files-the-current-role-does-not-have-access-to-this-operation-ojs-3-1-2-4/58347
- https://forum.pkp.sfu.ca/t/designer-sometimes-has-no-rights-to-download-files-the-current-role-does-not-have-access-to-this-operation-ojs-3-1-2-4/58347

**Comment by asmecher** [comment]
@marcbria, if you could privately send me a database dump and files directory (truncated to 0 bytes is fine), I can try to take a look.

**Comment by marcbria** [comment]
Sure, but I'm on vacations right now... till second 6th of sept.

I don't remember the journal that reported this. I fill find it and package the journal then.

**Comment by marcbria** [comment]
Sorry for the delay. Sent by slack.

**Comment by ajnyga** [comment]
Also encountered this, is there a known solution?

**Comment by asmecher** [comment]
@marcbria and @ajnyga, are you still encountering this on the latest 3.3.0-x?

**Comment by ajnyga** [comment]
have not seen this with 3.3 or 3.4 but then again last time I saw this was back in 2019 so the circumstances the generate the problem can be hard to track

**Comment by marcbria** [comment]
Sorry... I'm still in 3.2. Moving to LTS is planned for this Q4 (after rebuild of the infrastructure).
As far as I know there is no workaround but it only happens with "migrated" articles so it's a problem that tends to disapear.

**Comment by asmecher** [comment]
OK, I'm going to close this as outdated, but if anyone is able to reproduce it in 3.3.0 or newer I'd love to get more details.

**Comment by ajnyga** [comment]
@marcbria what do you mean by "migrated"?

**Comment by marcbria** [comment]
Sorry. Upgraded from 2.x.
Jump was so big to only say "upgrade" :-P
