### ISSUE TITLE
Rebuild search index tool fails in OMP 3.3.0-6

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7153]
From https://forum.pkp.sfu.ca/t/rebuilt-search-index-fails-on-omp3-3-0-6/68447:
> I run the tools/rebuildSearchIndex.php on the OMP and I got this error message:
>
> ```
> $php tools/rebuildSearchIndex.php 
> 
> PHP Notice: Undefined property: MonographSearchDAO::$_dataSource in /web/htdocs/libros/classes/search/MonographSearchIndex.inc.php on line 187
> 
> PHP Fatal error: Uncaught Error: Call to a member function CacheFlush() on null in /web/htdocs/libros/classes/search/MonographSearchIndex.inc.php:187
> 
> Stack trace:
> #0 /web/htdocs/libros/tools/rebuildSearchIndex.php(33): MonographSearchIndex->rebuildIndex()
> #1 /web/htdocs/libros/tools/rebuildSearchIndex.php(38): rebuildSearchIndex->execute()
> #2 {main} thrown in /web/htdocs/libros/classes/search/MonographSearchIndex.inc.php on line 187
> ```
> So, at this moment I´ have empty submission_search_* tables

**Comment by asmecher** [comment]
For affected users, you can apply this change: https://github.com/pkp/omp/commit/1fc5682903b8eebd9ee12010df076289bd0b6d4a

To apply it manually, edit the file `classes/search/MonographSearchIndex.inc.php`, find the line:
```
$searchDao->_dataSource->CacheFlush();
```
...and delete or comment this line.

**Comment by dagosalas** [comment]
Thanks! The searcj It´s working fine now!
