### ISSUE TITLE
missing review round policy when uploading a revision of a submission revision

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7154]
**Describe the bug**
Reported by a hosted client.  In a review round, if a new file is uploaded to the Revisions grid, and then if that file is revised, a fatal error occurs because getReviewRound in the PKPFileUploadWizardHandler returns null because there is no authorized object of ASSOC_TYPE_REVIEW_ROUND.

Observed in OJS 3.2.1.  Does not seem to be present in 3.3.

Adding a ReviewRoundRequiredPolicy in the case that a) there is a file id to validate and b) we are dealing with a file in a review round fixes the error.

**Additional information**
I believe that @NateWr  said that a fix could be merged into 3.2 if the patch still passes all of Nate's file upload access testing guide, and @ewhanson has worked through all of that now.

**Comment by NateWr** [comment]
Thanks @jnugent. Is there a PR?

**Comment by jnugent** [comment]
Hi @NateWr  yes, and I'm not sure why it didn't link into this issue:

https://github.com/pkp/pkp-lib/pull/7155

**Comment by NateWr** [comment]
Thanks @jnugent. Merged to `stable-3_2_1`.
