### ISSUE TITLE
A tool to detect faulty database entries to prevent code malfunction

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#7160]
First of all thanks to the contributors of this great project.

I am the editor and journal manager of a journal using OJS.

The faulty database entries seems to create many problems such as given in https://github.com/pkp/pkp-lib/issues/7156 and https://github.com/pkp/pkp-lib/issues/6774 and probably more. In many occasions faulty database entries may prevent the OJS code to work properly. As I see in https://github.com/pkp/pkp-lib/issues/6774 it is possible to detect and remove some of these faulty entries by some queries.

It would be nice to have a tool in OJS among other tools to examine the journal database and diagnose or remove/correct faulty database entries. It may be very helpful to the users to solve problems before reflecting to the developers.

Thank you all.

**Comment by NateWr** [comment]
Hi @Baytan, I agree this would be nice! We've also talked before about implementing a pre-flight check for upgrades, that would try to check some constraints in the database. The main challenge is defining the correct constraints and writing the checks.

We're refactoring a lot of our database structure to make more use of foreign keys, which will impose stricter constraints on the data and therefore help surface these problems. Any help along these lines is much appreciated.

**Comment by NateWr** [comment]
A pre-flight check in the upgrade process was introduced for 3.4: https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.inc.php. Further improvements should be filed as new issues.
