### ISSUE TITLE
My site has broken ! Can someone help me?

### ISSUE THREAD

**Issue by saricob** [pkp/pkp-lib#7162]
Link: https://eajltls.com/
The journal site has broken and I do not know what I can do. Can someone help me with this issue?

**Comment by saricob** [comment]
Thank you so much. How can i define it on cPanel? Do you know how to do it?

**Comment by NateWr** [comment]
Hi @saricob, You can find the `baseUrl` setting in the `config.inc.php` file, which will be in the root directory where you installed OJS. I'll close this for now but you can follow up in the [Community Forum](https://forum.pkp.sfu.ca) if you need.
