### ISSUE TITLE
Add an interface for viewing processing queue status

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7171]
As we rely more on Laravel queues for day-to-day tasks like email sending, CrossRef deposits, etc., it'll be necessary to give the user a way to see whether the queues are running, how much work is left, and whether any errors came up.

Add an interface to allow the user to view the processing queue, probably admin/journal manager only, and possibly even to control the queue (initiate processing for a queue that's not running yet).

**Comment by NateWr** [comment]
There's one more requirement for this, which should maybe be its own issue. We need a way to track jobs that are queued _as a batch_. In some cases we will want to break a single task down into several jobs, such as sending an email to lots of recipients or building a large export file. When we do that, we'll want a way to identify the progress of _this batch of jobs_.

Example:
1. There are 20 jobs in the queue.
2. I send a bulk email to 500 users.
3. Five more jobs are added to the queue, each one sending 100 emails.
4. While these jobs are being processed, another 5 jobs are added to the queue that are not related to my bulk email.

In order to provide feedback to the user, we want to be able to identify how many of the 5 bulk email jobs have been completed (eg - 1/5 or 3/5). This would allow us to show a progress bar or a spinner in the UI, so that the user knows the task is still incomplete.

Should I file this separately or is it ok to keep this here?

**Comment by henriqueramos** [comment]
@asmecher 

Could you please do a check on those PRs? 
[OMP](https://github.com/pkp/omp/pull/1043/files), [OJS](https://github.com/pkp/ojs/pull/3254/files), [OPS](https://github.com/pkp/ops/pull/209) and [pkp-lib](https://github.com/pkp/pkp-lib/pull/7553). 

Upgrade tests for OJS, using PHP 8.0 are failing due to removed `get_magic_quotes_runtime` on this version.

**Comment by asmecher** [comment]
@henriqueramos, I've given a first look at these and added some comments; @NateWr, could you have a look over the ListPanel aspects?

**Comment by henriqueramos** [comment]
@asmecher Regarding the `DB::table(jobs)` on `pages/management/PKPToolsHandler.inc.php`

Unfortunately, at this point of code history, we doesn't have a Domain/DAO/Repository/Collector for the `jobs` table.

I've created a Eloquent Model for `jobs` at #4622. It was two months before the starting of global Repository refactoring.

Right now I don't know if I should wait for the #4622 being merged, with his Eloquent Model stuff, or create a Repository here for the `jobs`. Both patterns are conflicting, in my view.

**Comment by asmecher** [comment]
I'm open to ideas for new patterns, but handler classes should definitely be insulated from the database structure.

**Comment by henriqueramos** [comment]
@asmecher I've updated only the OJS and pkp-lib pull requests. 

https://github.com/pkp/ojs/pull/3254/files
https://github.com/pkp/pkp-lib/pull/7553/files

**Comment by asmecher** [comment]
Thanks, @henriqueramos, I've added a few comments.

**Comment by NateWr** [comment]
@henriqueramos Alec asked me to take a look at the UI part of this. It looks good! I've opened a couple PRs to your repos that just remove some unnecessary code and simplify the setup of the `JobsPage` component. 

https://github.com/henriqueramos/ui-library/pull/1
https://github.com/henriqueramos/pkp-lib/pull/2

I also noticed that pagination isn't implemented yet for the table. You'll want to take a look at the `Pagination` component for how to make use of that in `JobsPage`.

**Comment by henriqueramos** [comment]
@NateWr I've added few comments on those PRs, could you please take a look on it?

**Comment by henriqueramos** [comment]
@asmecher I've updated the PRs and replied your comments, could you please take a look? Thank you!

https://github.com/pkp/ojs/pull/3254/files
https://github.com/pkp/pkp-lib/pull/7553/files
https://github.com/pkp/omp/pull/1043
https://github.com/pkp/ops/pull/209

**Comment by asmecher** [comment]
I just made a couple small comments; if you can resolve those, let me know and I'll check it out for some first-hand testing!

**Comment by henriqueramos** [comment]
I think I've covered each topic mentioned on your comments @asmecher.

There a few replies on it, please, check those. Thank you!

**Comment by NateWr** [comment]
I forgot to mention one other thing. This creates a new page in the navigation menu that can be accessed by a Journal Manager. @asmecher what do you think about this? My first thought was that this should be in admin tools and only accessible to the admin. It seems like an overly technical thing to expose to the Journal Manager.

**Comment by asmecher** [comment]
I think the queue management tools should be for the administrator only, until we have a requirement to make it available to managers as well.

**Comment by henriqueramos** [comment]
Thank you @NateWr! I've moved it to admin section.

Could you please take a look @asmecher? Obrigado!

https://github.com/pkp/ojs/pull/3254/files
https://github.com/pkp/pkp-lib/pull/7553/files
https://github.com/pkp/omp/pull/1043
https://github.com/pkp/ops/pull/209

**Comment by NateWr** [comment]
@henriqueramos there are a couple of approaches you can take to implement pagination:

1. Add an API endpoint and update the items in your table through an API request.
2. Reload the jobs page each time you change the page.

The first is the way the `Pagination.vue` component is expected to work. But it can work just as well with the second way.

To get started, add the `Pagination` component to the `JobsPage` component:

```js
...
import Pagination from ...;

export default {
    ...,
    components: {
        PkpTable,
        Pagination
    },
    ...
}
```

And add the markup to the template:

```html
<pkp-table
    ...
/>
<pagination
    :current-page="currentPage"
    :last-page="lastPage"
    :isLoading="isLoadingItems"
    @set-page="setPage"
/>
```

Next, add a `setPage` method to the `JobsPage` component that will do something when the `Pagination` component emits a `set-page` event:

```js
methods: {
    setPage(page) {
        // ...
    }
}
```

Now, it depends on whether you want to go the API route or just reload the page. The easiest way is to reload the page:

```js
setPage(page) {
    this.isLoadingItems = true;
    window.location = this.url + '?page=' + page;
}
```

If you want to use the API approach, you'd need to make an AJAX request, and then update `this.rows` with the response. Hope that helps!

**Comment by henriqueramos** [comment]
Thank you for the help @NateWr!
 I've followed the idea of reloading the page with querystring.
 
 @asmecher Could you please take a look on those PRs?
 
https://github.com/pkp/ojs/pull/3254/files
https://github.com/pkp/pkp-lib/pull/7553/files
https://github.com/pkp/omp/pull/1043
https://github.com/pkp/ops/pull/209

**Comment by henriqueramos** [comment]
@asmecher I've fixed the points. Could you please do a check? Thank you!

https://github.com/pkp/ojs/pull/3254/files
https://github.com/pkp/pkp-lib/pull/7553/files
https://github.com/pkp/omp/pull/1043
https://github.com/pkp/ops/pull/209

**Comment by henriqueramos** [comment]
@asmecher I've changed that 'mea culpa'. Could you please take a look on those? Thank you!

https://github.com/pkp/ojs/pull/3254/files
https://github.com/pkp/pkp-lib/pull/7553/files
https://github.com/pkp/omp/pull/1043
https://github.com/pkp/ops/pull/209

**Comment by henriqueramos** [comment]
@asmecher There's anything else I could do on this subject? Thank you!

**Comment by asmecher** [comment]
All merged, thanks!

**Comment by jonasraoni** [comment]
@asmecher It's missing this one: https://github.com/pkp/ui-library/pull/172

**Comment by asmecher** [comment]
Yes, I've just merged that & just about to update submodules.
