### ISSUE TITLE
Method names with underscore as prefix

### ISSUE THREAD

**Issue by pablovp86** [pkp/pkp-lib#7172]
I'm trying to understand the rationale behind the nomenclature of methods that are prefixed with an underscore.

Some [legacy coding style guides](https://www.php-fig.org/psr/psr-2/) used underscores to specify method visibility on older versions of PHP, but this not seems to be the case, because the examples i saw have different visibility: [private](https://github.com/pkp/pkp-lib/blob/0462408c0a7e0537f1fdcd5c6588fde651fb14ce/api/v1/users/PKPUserHandler.inc.php#L211), [public](https://github.com/pkp/pkp-lib/blob/ede753267bd9ff162c981d88d0db31e86988900c/classes/db/SchemaDAO.inc.php#L235) or [protected](https://github.com/pkp/pkp-lib/blob/ede753267bd9ff162c981d88d0db31e86988900c/classes/db/DAO.inc.php#L196). 

Sorry if this is not the right place to post this question, but it seems to be too development specific for the forum scope!

**Comment by asmecher** [comment]
@pablovp86, the forum is actually fine for questions like this. But I'll answer your question here: essentially ours is a large, old codebase (spread over many repositories), and some coding standards still hark back to earlier eras. New code is much more modern and we're gradually revamping older parts of the system, including old conventions like `_` prefixing.

**Comment by pablovp86** [comment]
Thanks @asmecher for your explanation. Next time I'll try the Forum.
