### ISSUE TITLE
[OMP] No cover images after upgrading to 3.3.0.7

### ISSUE THREAD

**Issue by bkawula** [pkp/pkp-lib#7173]
[Seems like a few people have been having this issue](https://forum.pkp.sfu.ca/t/omp-cover-images-disappear-after-upgrade/66115), myself included.

I finally got the images to migrate after appending the file directory info to the cover and thumbnail path variables in the migrateSubmissionCoverImages() function of the upgrade script.

**Comment by asmecher** [comment]
Thanks for tracking this down, @bkawula! Would you be willing to open a pull request including that change?

**Comment by bkawula** [comment]
Done! https://github.com/pkp/omp/pull/991

**Comment by asmecher** [comment]
Thanks, @bkawula! I've merged to `main` and back-ported to `stable-3_3_0` and `stable-3_3_1`.
