### ISSUE TITLE
[OPS] Send "acceptance" letter to authors

### ISSUE THREAD

**Issue by diegoabadan** [pkp/pkp-lib#7176]
Hey! We were trying to use the feature implemented in issue #5727 , but we noticed some strange behavior. In [line 300 the email is sent to the current user](https://github.com/pkp/ops/blob/ffc51352642f31c100c3792e5ebcf7f6c0ca3879/classes/services/PublicationService.inc.php#L300) who is posting the preprint.

However, it is common for preprints to be posted by moderators, so the email is not sent to the authors, but to whoever is posting.

To fix this, we hope it will be sent to the preprint authors.

Versions affected: OPS 3.3.0 through 3.3.0-7

**Comment by ajnyga** [comment]
pr of OPS: https://github.com/pkp/ops/pull/168

**Comment by asmecher** [comment]
Thanks, @ajnyga!
