### ISSUE TITLE
Make the plugin gallery XML only load when it's needed

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7182]
Currently the plugin gallery XML is loaded when the settings area is loaded. This is expensive and usually unnecessary. Make the plugin gallery XML load only happen when it's needed.

**Comment by asmecher** [comment]
@NateWr, only assigning to you because it's likely at your fingertips. See also related issue: https://github.com/pkp/pkp-lib/issues/7181

**Comment by henriqueramos** [comment]
The cached version implemented on [5998](https://github.com/pkp/pkp-lib/issues/5998) avoid the external request of plugin gallery XML.

**Comment by asmecher** [comment]
Closing in favour of the solution nearly ready in #5998.
