### ISSUE TITLE
Drag and Drop fails on dependent files

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7187]
**Describe the bug**
Original forum post: https://forum.pkp.sfu.ca/t/drag-and-drop-of-dependent-files-of-html-galleys-are-not-working-properly/68793
Attempts to drag and drop dependent files with the file upload wizard fail. Tested on galleys/production-ready files uploads. Note that the issue is relevant only when uploading dependent files altogether with the main document.

**To Reproduce**
1. Go to the Submission -> Workflow -> Production
2. Click on 'Upload File' and through the file upload wizard upload a HTML or XML file and click continue
3. On step 2, under `Review Details`, on Dependent Files grid click `Upload File` and repeat the process
4. See that Drag and Drop doesn't work in this case
![dependent_files_upload](https://user-images.githubusercontent.com/20665587/125652441-b770e13a-55b3-46ae-a354-aa21812d42ae.png)

**What application are you using?**
 the current master branch of OJS (3.4), originally reported for 3.2.0 and 3.2.1. 

**Additional information**
There is nothing relevant in the browser console or PHP log. On the front-end side, the only suspicious thing that I noticed is 2 HTML elements with the same id `pkpUploaderDropZone`. But I really don't know if 2 dropzones on one page with the same `id` may conflict with each other, I see that the wrappers have different `id`s

**Comment by touhidurabir** [comment]
@asmecher RPs 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7187 Drag and Drop fails on dependent files](https://github.com/pkp/pkp-lib/pull/7934)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7187 Submodule Update ##touhidurabir/i7187_fix_main## ](https://github.com/pkp/ojs/pull/3404)

let me know if this need to be forwarded to `OMP` and `OPS` .

**Comment by asmecher** [comment]
Thanks, @touhidurabir, that's perfect as is! I don't mind if the OMP and OPS submodules aren't updated on the `main`  branch; they'll get updated soon enough.

**Comment by radekgomola** [comment]
Hi there, will this fix work even for OJS 3.2.1-4? I've tried it, but it completely messed up with whole drag and drop area and even the upload button. Is there something else what need to be done with some other files? Thank you very much for your help with it.

**Comment by asmecher** [comment]
@radekgomola, unless you turn off JS minification in `config.inc.php`, OJS will use the pre-compiled `js/pkp.min.js` version of all the JS classes instead of the version that gets modified by the above patch. You can compile the JS by running
```bash
sh lib/pkp/tools/buildjs.sh -n
```
However, this fix is for release in 3.4, so I'm not sure there won't be side-effects to back-porting it to older versions.
