### ISSUE TITLE
Disabling reinstate reviewer email template has no effect

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7189]
**Describe the bug**
The `REVIEW_REINSTATE` email template can be disabled from Settings > Workflow > Emails > Email Templates. However, this has no effect. The option to reinstate a reviewer still remains, and the editor can still choose whether or not to send the email when they reinstate the reviewer.

This is the case with other review emails. I have found this to be so with:

- `REVIEW_REQUEST`
- `REVIEW_DECLINE`
- `REVIEW_CONFIRM` (reviewer doesn't preview the email, but it seems to be sent either way)

**To Reproduce**
1. Go to Settings > Workflow > Emails > Email Templates.
2. Search for `REVIEW_REINSTATE`.
2. Expand the options for that template and disable the template.
3. Go to a submission with a review assignment already accepted or completed.
4. Cancel the review assignment.
5. Reinstate the review assignment.
4. See that the template is still there and the editor can choose to send the email or not.

**What application are you using?**
3.4 pre-release

**Additional information**
I think probably this email template shouldn't have the `canDisable` flag set. It doesn't make sense to disable emails that the editor can opt not to send.

**Comment by NateWr** [comment]
Yes, this probably needs a comprehensive review. For example, `REVIEW_REQUEST` can be disabled but not `REVIEW_REQUEST_ATTACHED`.

**Comment by Vitaliy-1** [comment]
`REVIEW_REQUEST` is checked if enabled in `ReviewerForm::execute`, i.e. when the mail is sent. But this doesn't make sense, it should be before form initialization.

**Comment by Vitaliy-1** [comment]
`canDisable` was moved from `EmailTemplate` to `Mailable`. Ensure this works as expected after email refactoring and new Mailable UI implementation.

**Comment by NateWr** [comment]
I'm investigated this as part of #5716. These fields won't be disable-able but they can be skipped in the UI. I consider it done, so closing.
