### ISSUE TITLE
ImportExportPlugins do not export PubIds via ScheduledTaskTool

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#7194]
**Describe the bug**
When metadata is exported via the ScheduledTaskTool the pubIds are missing. They do appear though when exported from the backend.
I was able to reproduce this for the DNBExportPlugin and the DOAJExportPlugin.

The DOIs are queried via ["$doi = $pubObject->getStoredPubId('doi');"](https://github.com/pkp/ojs/blob/465b1a0044f1c8bc24217bc5e14c2f604f65f109/plugins/importexport/doaj/filter/DOAJJsonFilter.inc.php#L113) which returns an empty object when called via the ScheduledTasksTool. The pubIds are not contained in the publication data property. It seems they are not read from the database.
From the backend the same function call returns the pubIds as expected.

**What application are you using?**
 OJS version 3.2 and 3.3 (missing DOIs confirmed for both) 

Can anyone confirm this?

**Comment by NateWr** [comment]
It sounds like the `pubId` plugin category is not being loaded during a scheduled task. The plugins are loaded in the `Dispatcher`:

https://github.com/pkp/pkp-lib/blob/main/classes/core/Dispatcher.inc.php#L157

**Comment by ronste** [comment]
I also played around with loading the plugin category myself but it didn't work either. I always ended up with a missing context or missing request in case I provided the context.

**Comment by ronste** [comment]
I looked a little deeper into the issue. I don't think its got to do with the dispatcher. Its not called from the ScheduledTaskTools as far as I can tell.

By comparison to OJS 3.1.2-4 (where pubId export works) I figured the class/function responsible for fetching the data changed from 

PublishedArticleDAO::getExportable in OJS 3.1.2-4

to

PKPSubmissionDAO::getExportable in OJS > 3.2

The SQL-query in PKPSubmissionDAO::getExportable is correctly executed via the ScheduledTaskTool but does not return the pubIds from the publication_settings table.

How could we proceed from here?

We have different clients in Germany waiting for the DNB Export Plugin for OJS > 3.2. The German National Library meanwhile stopped importing metadata from OJS 3.2. I'd like to handle this rather sooner than later.  Any ideas?

**Comment by ronste** [comment]
I looked a little deeper into the issue. I don't think its got to do with the dispatcher. Its not called from the ScheduledTaskTools as far as I can tell.

By comparison to OJS 3.1.2-4 (where pubId export works) I figured the class/function responsible for fetching the data changed from 

PublishedArticleDAO::getExportable in OJS 3.1.2-4

to

PKPSubmissionDAO::getExportable in OJS > 3.2

The SQL-query in PKPSubmissionDAO::getExportable is correctly executed via the ScheduledTaskTool but does not return the pubIds from the publication_settings table.

How could we proceed from here?

We have different clients in Germany waiting for the DNB Export Plugin for OJS > 3.2. The German National Library meanwhile stopped importing metadata from OJS 3.2. I'd like to handle this rather sooner than later.  Any ideas?

**Comment by NateWr** [comment]
Thanks for digging into this @ronste. I'm not very familiar with that code, but it should be used by other ImportExportPlugins like the Crossref one. I'll see if we can get someone to look into this further and see what's happening. 

In the meantime, can you provide some reproduction steps? This would be step-by-step instructions on setting up the DAOJPlugin, adding a DOI, exporting a submission, and inspecting the result that's missing a DOI.

**Comment by ronste** [comment]
Dear @NateWr ,

these are the steps to reproduce the issue:

1) Enable the DOI-Plugin
2) Go to plugin settings:
      - enable articles and galleys
      - provide DOI prefix
      - otherwise use defaults and save
3) Create a submission with appropriate test data including DOIs
4) Go to DOAJ-Plugin
    - type in a dummy DOAJ API Key (the issue arises before the connection to DOAJ is made)
    - enable automatic deposit and DOAJ test API
5) Go to the "Articles" Tab and export as XML as a reference (DOIs will be included here)
6) Switch to a debugging environment (from the command line no files are created to verify the exported data)
7) Comment out the \<frequency\>-Tag in scheduledTasks.xml to enable multiple test runs from the command line
8) Place a breakpoint on line 112 in DOAJXMLFiler.inc.php
7) Run "php tools/runScheduledTasks.php plugins/importexport/doaj/scheduledTasks.xml" from the ojs main folder and look for the value of $doi

On my system this results in the $doi variable to return NULL for both, DOAJ and DNB plugins.

I also adapted my phpunit test case from the DNB plugin to DOAJ. Its tests all the exported metadata against an native xml export. I attach this as a zip below. 
[DOAJ XMLExportFilterTest.zip](https://github.com/pkp/pkp-lib/files/6878947/DOAJ.XMLExportFilterTest.zip)

If the issue takes longer to be fixed I will in the meantime release a DNB-Plugin version disabling automatic deposit. However, I would like to avoid this because of all the additional communication (and plugin installations) required with all the customers and the DNB. If you could give me an update on the estimated time frame as soon as you have an idea about it that would help me with this decision. 

Thanks and best wishes,
Ronald

**Comment by CFanselow** [comment]
@ronste, @NateWr 

I had a look at the code. 

In https://github.com/pkp/ojs/blob/main/classes/plugins/PubObjectsExportPlugin.inc.php#L564

_registered_ DOIs are returned in the submission object (e.g.  [datacite::registeredDoi] => 10.1234/cl.v1i1.2), but no _unregistered_ DOIs. 

But the DOAJ Json Filter tries to get the unregistered DOIs from the submission object with getStoredPubId:

https://github.com/pkp/ojs/blob/main/plugins/importexport/doaj/filter/DOAJJsonFilter.inc.php#L113

In Representation.ini.php, there is a function to get the unregistered DOIs:

https://github.com/pkp/pkp-lib/blob/95d550bc2f6238aa6a2fa4a96f2bbea1f41cf5b1/classes/submission/Representation.inc.php#L117

but no get function for registered DOIs. 

In general, I think only registered DOIs should be exported. I think when articles are exported to DOAJ without using scheduled tasks, unregistered DOIs are exported. 

Regards, 
Carola

**Comment by asmecher** [comment]
Thanks for looking into this, @CFanselow! @ronste, can you confirm that this is the behaviour that you're seeing?

**Comment by ronste** [comment]
Hi @asmecher 

Yes, this is confirmed behaviour. 

If triggered via the UI "Register" button you get:
![DOAJ export doi via RegisterButton](https://user-images.githubusercontent.com/54445456/128995590-16eb68c4-d429-4b24-8a66-ea8dad0e42ae.png)

The $publication->_data object contains datacite::RegisteredDoi and pubId::doi. The call to getStoredPubId calls  $this->getData('pub-id::' . $pubIdType) and only returns "10.1111/dnb32.v1i2.6".

If triggered via runScheduledTasks.php you get:
![DOAJ export doi via ScheduledTasks](https://user-images.githubusercontent.com/54445456/128996451-2b061b99-9c50-441c-80e1-a5eaed078d5a.png)

The $publication->_data object only contains the datacite::registeredDoi and the call to getStoredPubId returns "null".

Note that the call stack in case of runScheduledTasks confirms that the Dispatcher (where as @NateWr mentioned above the plugin category 'pubIds' is loaded) is not called. 

In both cases only "pubIds::" are (would be) exported independent of whether they are registered or not. 
What is the intended behaviour here? From our point of view only registered Ids should be exported.  

Best wishes,
Ronald

**Comment by ronste** [comment]
Dear @asmecher ,

I went another layer deeper into the issue and again compared OJS 3.1.2 with OJS 3.2.

In OJS 3.1.2 the pubIds are loaded via `PublishedArticleDAO::getExportable` which via `SubmissionDAO::_fromRow()` explicitly loads the submission settings (including the pubIds) on top of the prior SQL query as:

`$this->getDataObjectSettings('submission_settings', 'submission_id', $submission->getId(), $submission);`

In OJS 3.2 this changed. pubIds are stored in the table publication_settings and `PKPSubmissionDAO::_fromRow` now calls `PKPPublicationService::getMany`. As far as I can tell, the executed SQL query in getMany only queries the publications table but not the table publication_settings:

`$publicationQO->toSql()` yields
`select * from publications as p where p.submission_id in (?) order by p.version asc`

I hope that further helps to fix this issue.

Best wishes,
Ronald

**Comment by ronste** [comment]
Dear Alec,

I meanwhile got to the bottom of it. This issue is related to:

https://github.com/pkp/pkp-lib/issues/7108

and

https://github.com/pkp/ojs/pull/3151

Its the same story just for the CliTool/ScheduledTask classes used by runScheduledTasks.

That means it can easily be fixed by manually loading the pubIds plugin category. I can do this for the DNB plugin but the issue remains for the DOAJ plugin.

Buy the way, the other export plugins are not affected because they either manually loaded the pubIds plugin category for other reasons (already in OJS 3.1.2) or because they don't offer a cli export.

Best wishes,
Ronald

**Comment by asmecher** [comment]
Hi @ronste & @CFanselow -- thanks for doing the digging here, I haven't had the time to look into it. And @ronste, thanks for identifying the problem and fix; can you open a pull request for it? If so, can take care of the DOAJ plugin.

**Comment by ronste** [comment]
Hi @asmecher ,

I could certainly open a pull request for this one-liner fixing the DOAJ plugin. But I think this would be merely another work-around and wouldn't address the main issue. Most likely this issue would come up in the future again in some other context.

From my point of view the main issue is either that:

a) it doesn't seem to be possible to add data to the schema without a context ID (DOIPubIdPlugin::register is essentially skipped), or
b) the CliTool class is not aware of the context it is running for (otherwise it could load the pubIds category providing the context).

This creates a situation in which developers have to be aware of which data is loaded under which circumstances (also for other extensions to schemata by plugins). I think loading of schema data provided by other plugins should be a transparent process.

The issue could be addressed by either providing a means for plugins of registering schema variables (for reading) without a context ID (which will be provided at a later stage by the plugin calling the CLITool) or by providing the context ID to the CliTool class, e.g. as parameter in the scheduledTasks.xml file.

What is your opinion on this? Are there improvements planned in future versions of OJS where these kind of questions could be addressed?

Best wishes,
Ronald

**Comment by ronste** [comment]
Hi @asmecher ,

I created the pull request: https://github.com/pkp/ojs/pull/3173

**Comment by asmecher** [comment]
Thanks, @CFanselow and @ronste -- I've merged the PR for `stable-3_2_1`, and forward-ported it to `stable-3_3_0`, `stable-3_3_1`, and `main`. It'll come out in the next release -- OJS 3.3.0-8 -- very soon.
