### ISSUE TITLE
Upgrade script - multiple same use clauses

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#7209]
**Describe the bug**
When trying `php upgrade.php upgrade` a fatal error occurs. 

> Cannot use APP\core\Application as Application because the name is already in use in C:\xampp\htdocs\ojs-3-dev\classes\install\Upgrade.inc.php on line 20

**What application are you using?**
 OJS main branch

**Comment by defstat** [comment]
@NateWr @asmecher 

**PR**
[OJS]: pkp/ojs#3166

I also checked OMP and OPS and they seem not to have the same issue

**Comment by NateWr** [comment]
Merged to `main`. Thanks @defstat!
