### ISSUE TITLE
Tiny MCE corrupts DOAJ XML

### ISSUE THREAD

**Issue by dommitchell** [pkp/pkp-lib#721]
We've been alerted to a bug in the creation of DOAJ XML for those journals using the Tiny MCE editor.

For those publishers who copy their abstracts from Word into the Tiny MCE editor, the cut 'n' paste action also copies the MS Word stylesheet junk into the abstract field.  This gets pulled into the XML when the XML is generated using the plugin.  See the sample below from an OJS publisher.

<p class="AbstractText"> is also seen often.

The generated XML also contains invalid special characters copied from Word, such as accented characters, double-inverted commas, html tags for bold etc, which do not validate against our xsd. We can only accept plain text abstracts.

One such abstract that contains the junk:
http://journal.seriousgamessociety.org/index.php?journal=IJSG&page=article&op=view&path[]=74

@jmacgreg said: "It looks like a sanitization issue that should be relatively easy to fix."

Thanks in advance
![tiny_mce](https://cloud.githubusercontent.com/assets/5955396/9654324/4b7b8d7a-522a-11e5-8005-9720e0fcbd87.jpg)

Dom, DOAJ

**Comment by asmecher** [comment]
Thanks, @dommitchell -- I've updated the XML generator to strip any HTML from abstracts (including some very trivial text-to-html conversion to cover things like line breaks and paragraphs). Existing users can apply https://github.com/pkp/ojs/commit/e4a80292871b44d17516a75134024e02f3c2de43 and the change will be included in OJS 2.4.7. Invalid characters are a data problem and this won't address it; it's much better for those journals to deal with the data at the source. My suspicion is that it comes from older versions of OJS that included older versions of TinyMCE; that stack has become a lot better at providing sane input.
