### ISSUE TITLE
No email is sent when creating a new announcement

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7213]
**Describe the bug**
If an announcement is created in OJS 3.3, and the check box for sending an email to all registered users is checked, no email is sent. 

This appears to be because the API end point for creating an announcement doesn't do anything with the "sendEmail" form parameter.   I've looked through the code and the path seems to be that the `add` method in `PKPAnnouncementHandler`  validates the request, and if it passes, the `AnnouncementDAO` creates the new object and adds it via the `Service` and then returns with a `200` status code.  No notification or email is created.  

**What application are you using?**
 OJS 3.3.0.7

**Additional Information**

There's a forum thread: https://forum.pkp.sfu.ca/t/announcement-mass-email-in-not-working-on-ojs-3-3-x/67472

The work around seems to be to use the Bulk Email feature in 3.3 and reposting the contents of the announcement.

**Comment by Vitaliy-1** [comment]
Can take Announcement notification next for refactoring, which will fix this.
If I correctly remember such cases with non-editable mails, it was agreed to create an event in the Announcement Repository when an announcement is added and write a listener that sends an email if form data contains send mail option; right, @NateWr?

**Comment by NateWr** [comment]
Yes, I think that makes sense. This will be the case whenever the content of the event (announcement title/content) is the same as the body/subject of the email. The same would be true, for example, when a message is sent in a discussion.

**Comment by rahmanramsi** [comment]
here the pull request @NateWr
pkp/pkp-lib#7547
pkp/ojs#3253

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and ported to `main`. Thanks for the PR @rahmanramsi! :tada:

**Comment by luizbgomide** [comment]
I applied the PR #7547 that, but my announcements still aren't being sent via e-mail.

Nothing is reaching the SMTP server. Any ideias?

**Comment by luizbgomide** [comment]
@NateWr, does that only work when creating a new Announcement or can I retroactively edit an Announcement and tick the box to send the e-mail (this is what I've done, because I didn't want to spam my users).

If I cannot send an e-mail after the creation, I suggest that this check box be removed from the edit window to avoid confusion.

**Comment by NateWr** [comment]
Yeah it only works when creating an announcement. I'd suggest filing a new issue about the checkbox.

**Comment by OhnO395** [comment]
I applied the PR https://github.com/pkp/pkp-lib/pull/7547 that, 2 case.
1. test journal have 3 user can sent via email
2. The Journal have 990 user aren't being sent via e-mail.

**Comment by mdsoft123456** [comment]
hello,
I have the same problem i can't send email from annoncements however all other mail where send. any idea please!!!

**Comment by asmecher** [comment]
@mdsoft123456, please take questions like this to our support forum: https://forum.pkp.sfu.ca
