### ISSUE TITLE
OAI resumption token empty after first page of results [OJS 3.3.0]

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7214]
**Describe the bug**
When fetching OAI results via the `ListIdentifiers` verb, if there are more results than are shown a resumption token is provided. Currently a resumption token is only created upon loading the first page of records and all subsequent pages will have an empty resumption token.

`PKPOAIDAO->getIdentifiers()` (and `PKPOAIDAO->getRecords()`) do not correctly calculate the total number of records. When attempting to count the number of records for the second + page, this function will return a lower number of total records than actually exist, making the application think it is at the end of the list of records.

https://github.com/pkp/pkp-lib/blob/6a16c519f38f503f9ce4b4d722f1dc029d8fa5d9/classes/oai/PKPOAIDAO.inc.php#L155-L172

**To Reproduce**
1. Go to [journal-url]/oai?verb=ListIdentifiers&metadataPrefix=oai_dc
2. Click on 'resume' at bottom of page next to resumptionToken value
3. Scroll down to bottom of second page
4. See empty resumption token with non-functional resume button at bottom of page.

**What application are you using?**
OJS 3.3.0

**Comment by ewhanson** [comment]
Hi @NateWr and @asmecher,

Could you have a look at these pull requests? As far as I know this issue only affects 3.3 specifically as the way this is handled has been changed for 3.4. Thanks!

PRs:
pkp/ojs#3168
#7215

**Comment by NateWr** [comment]
I'm going to leave this for @asmecher because I'm not familiar with this code at all.

**Comment by asmecher** [comment]
Very good spotting, @ewhanson; this has already been fixed as part of a rewrite in 3.4, so it'll just be 3.3. I've merged it and it'll come out in the next build.
