### ISSUE TITLE
Default user search does not include username

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#7217]
**Describe the bug**
Searching for a user by username within the Users management interface does not return matches for known usernames.

**To Reproduce**
1. In the testdrive, login, then
2. Select "Users and Roles", then
3. Observe (or create) the username of a user which does not also appear in the name and email, e.g. "sburkitt", then
4. Select "Search"
5. Observe results with no match.

**What application are you using?**
 OJS, OMP or OPS version 3.2.+

**Additional information**
This ultimately comes down to a call to `UserGroupDAO:: _getSearchSql()` with no `$searchType`:
https://github.com/pkp/pkp-lib/blob/0190a3a7b0a9acfe1be335366385c130b7d4e173/classes/security/UserGroupDAO.inc.php#L930

Adding username here should resolve, unless that introduces unwanted side effects to other calls to this function.

**Comment by NateWr** [comment]
This may be impacted by work on https://github.com/pkp/pkp-lib/issues/6991. I think the plan is to move searching in the users grid over to the same code as searching in the API, which does search the username.

**Comment by jonasraoni** [comment]
Closing this issue, as I've added the username to the issue mentioned above.
