### ISSUE TITLE
Review use of {$principalContactSignature} in email templates

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7225]
**Describe the problem you would like to solve**
Many default email templates include a variable, `{$principalContactSignature}`. This variable gets the context's `contactName`. This duplicates the `{$contactName}` variable, and isn't very helpful.

**Describe the solution you'd like**
Use of a default or fallback contact signature should be reviewed. There are a couple of options for a default contact signature for a journal:

1. The context's `emailSignature` setting, configured under Settings > Workflow > Emails. This should probably be used in most cases, especially automated emails.
2. Automatically constructing a signature from the context's `contactName`, `contactEmail` and `contactPhone`, `contactAffiliation` and `mailingAddress`.

My preference would be to use the first one in most cases, but we'll need to review how `{$principalContactSignature}` is used first.

**Who is asking for this feature?**
This came up in the email refactor that is part of #5717.

**Comment by NateWr** [comment]
A related issue with the context's signature setting is that it suggests that it always supports `{$sendername}` and `{$senderEmail}` variables. However, this is not true. See https://github.com/pkp/pkp-lib/issues/7496.

My preference would be for the context's signature setting to not rely on any variables, or to only rely on variables related to the `Context` object, since no other variables are guaranteed to exist.

**Comment by Vitaliy-1** [comment]
That was done during email refactoring. `$principalContactSignature` was renamed to user `signature`  or `contextSignature` depending on a email template, see: https://github.com/pkp/pkp-lib/blob/27e11f887c244ab858e5c74555850933fdd246e1/classes/migration/upgrade/v3_4_0/I7264_UpdateEmailTemplates.php#L146
The `signature` is assigned to all mailables, where sender is registered user and `contextSignature` where email is sent on behalf of context.
