### ISSUE TITLE
Fix .editorconfig file after code formatting change

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7227]
Our `.editorconfig` still specifies tabs (see [here](https://github.com/pkp/ojs/blob/main/.editorconfig)). We should update the `.editorconfig` to support spaces for `.php` and tabs for `.js`, `.vue`, `.json`, and `.less`.

**Comment by defstat** [comment]
@NateWr @asmecher 

**PRs**
[OJS]: pkp/ojs#3170
[OMP]: pkp/omp#996
[OPS]: pkp/ops#171

**Comment by NateWr** [comment]
Thanks @defstat!
