### ISSUE TITLE
OJS 3.3.0.7 No longer sending Submission Notification email to JM or Editors

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#7228]
**Describe the bug**
In OJS 3.3.0.7, JM and Editors are no longer receiving the Submission notification email they would have in 3.2. JM would like to continue receiving these types of notifications. 

Requested in https://forum.pkp.sfu.ca/t/ojs-3-3-new-submission-notification/69028

**To Reproduce**
1. Author submits a new manuscript
2. Author receives Submission Acknowledgment email
3. Journal Manager and Editor does not receive any emails

**Additional information**
Email notification from OJS 3.2.1.1

![image](https://user-images.githubusercontent.com/50342731/129401548-55f24fd5-1f39-4588-8551-a957ad4a33da.png)

**Comment by asmecher** [comment]
@pmangahis, have you been able to replicate this behaviour in 3.3.0-x, or are you relying on user reports?

**Comment by pmangahis** [comment]
Hi @asmecher,

I tested this on the PKP 3.3 demo install which has the emails enabled and confirmed that the JM and Editors didn't seem to be getting the emails anymore.

**Comment by NateWr** [comment]
I had a look at the code and this is the logic describing who gets an email notification in 3.3.0-7:

1. If there is only one user assigned to a manager or assistant role that is assigned to the submission stage, that user will be automatically assigned and notified. (eg - if there are two or more journal manager, no automatic assignment is made and therefore no notification is sent).
2. If one or more section editors are assigned to the section the submission was made in, they are automatically assigned to the submission and notified.
3. The same as (2) except for categories. If a submission is assigned to more than one category, all related section editors are assigned and notified.
4. The submitting author is sent a submission acknowlegment email.
5. Every author listed in the submission is sent a separate submission acknowlegment email.

The report on the forum says: "I no longer receive a copy of the new submission confirmation sent to the author (I used to receive this with our previous installation)." That would be different from the email described in this issue. The email that user seems to be talking about is the one that was re-added in https://github.com/pkp/pkp-lib/issues/6272.

**Comment by NateWr** [comment]
I believe the email shown in this issue (screenshot in the original post) is the task-level notification. Editors should be able to opt in or opt out of that under their User Profile > Notifications. @pmangahis can you test to see if you get an email when enabling those settings?

**Comment by pmangahis** [comment]
Tested this again based on your notes on the PKP School 3.3 Install. Even with only 1 JM and 1 Editor and all notifications enabled, neither of these users seemed to get a submission notification.

**Comment by asmecher** [comment]
@pmangahis, I tested it locally, and the single editor did receive a notification message:
```
Subject: [t2] Submission Acknowledgement

Au Thor:<br />
<br />
Thank you for submitting the manuscript, &quot;asdffadsdfasa&quot; to t2. With the online journal management system that we are using, you will be able to track its progress through the editorial process by logging in to the journal web site:<br />
<br />
Submission URL: <a href='http://localhost/git/ojs-stable-3_3_0/index.php/t2/authorDashboard/submission/22' class='submissionUrl-style-class'>http://localhost/git/ojs-stable-3_3_0/index.php/t2/authorDashboard/submission/22</a><br />
Username: author<br />
<br />
If you have any questions, please contact me. Thank you for considering this journal as a venue for your work.<br />
<br />
<br/><br/>
________________________________________________________________________<br/>
<a href="http://localhost/git/ojs-stable-3_3_0/index.php/t2">t2</a>
```
I suspect the notification email is being sent by the system but getting spam-trapped or something similar.

**Comment by NateWr** [comment]
After reviewing with @pmangahis, we determined this wasn't a bug and that the [submission acknowledgement](https://github.com/pkp/pkp-lib/issues/6272) emails added back in 3.4 will address the remaining issues the editor was facing.
