### ISSUE TITLE
DAO::convertToDB() requires pass by reference for a string?

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#7235]
**Describe the bug**
https://github.com/pkp/pkp-lib/blob/0f727b565929b04ddcbc0620cfa05f7471635364/classes/db/DAO.inc.php#L382
Why in the name of all that is pointy would we do this?

**To Reproduce**
1. Write `$this->convertToDB($value, 'date')` like a sane person.
2. Execute code.
3. Die with `PHP Fatal error:  Uncaught Error: Cannot pass parameter 2 by reference`

**What application are you using?**
 OJS, OMP or OPS version 3.2.1, but exists in `main`

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by asmecher** [comment]
I think we can consider this function deprecated, as our DAO rewrites for 3.4 (https://github.com/pkp/pkp-docs/issues/812) don't use it -- but the purpose of the reference on `$type` was so that the type could be provided back to the calling code when it was automatically detected.
