### ISSUE TITLE
Copyright info not published using quicksubmit plugin 

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#7236]
**Describe the bug**
When editors use the Quicksubmit plugin, the copyright info (author) is not published with the article. It requires to unpublish and publish it again to make the info public. It causes that LICENSE block title sticks to the CC badge.

**To Reproduce**
1.  Publish a new submission using Quick Submit Plugin
2. Goes to the article landing page
3. Scroll down to 'License'
4. See the missing info regarding the author

**What application are you using?**
 OJS version 3.3

**Additional information**
This is a issue discussed in the Forum: https://forum.pkp.sfu.ca/t/copyright-image-sticks-to-license-info-title/69383

Missing author info:
![image](https://user-images.githubusercontent.com/4992902/130245385-abcf9bb3-d7a9-4e69-b0d5-dfab907d6316.png)

**Comment by asmecher** [comment]
@israelcefrin, I was able to replicate this by leaving the "copyright holder" field blank during the Quick Submit form -- but if I fill in that field during the quick submit process, it displays fine. Are you able to replicate it without leaving the copyright holder field blank? If not, I think this is expected behaviour.

**Comment by israelcefrin** [comment]
@asmecher if we leave the copyright field blank, shouldn't it be filled with authors' info as it does when publishing via regular workflow?

**Comment by asmecher** [comment]
No, I don't think so -- unless we pre-fill the field when presenting a blank Quick Submit form. The quick submit plugin is not intended for the "normal" workflow so stamping it after submission with the defaults feels counter-intuitive to me. What about pre-filling the fields when the form is blank?

**Comment by israelcefrin** [comment]
+1 for the pre-filling when blank! I think it would prevent missing copyright info when using the plugin.

**Comment by asmecher** [comment]
Done, thanks!
