### ISSUE TITLE
Recommend-only editors can change own assignment privileges

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#7238]
**Describe the bug**
Normally section editor's privileges can be set to only recommend (not record) a decision, in roles globally and per individual submission. When assigned to a submission, a section editor can edit their own assignment, removing the flag to recommend decision - thus gaining full access to record decision

**To Reproduce**

1. Assign a section editor/guest editor to a submission (the account has no access to other roles)
2. During assignment ensure that this checkbox is checked _"This participant is only allowed to recommend an editorial decision and will require an authorised editor to record editorial decisions."_
3. Log in as the assigned section editor. You should only see the button "Make recommendation"
4. Under Participants in the submission go to "Edit" under your (section editor's) name
5. Uncheck the checkbox _"This participant is only allowed to recommend an editorial decision and will require an authorised editor to record editorial decisions."_
6. You can now see the buttons to Accept/Reject/Request Revisions for the submission

![image](https://user-images.githubusercontent.com/45104797/130496816-1f372d12-08d7-4388-b78f-696ab6997fbd.png)

**What application are you using?**
Tested in OJS 3.3 & 3.2 (not happening in 3.1 - no option to "Edit" own assignment)

**Additional information**
Reported by PKP|PS client from a journal where only editors should be allowed to record decisions.

**Comment by asmecher** [comment]
My first reaction was to call this behaviour-as-expected -- section editors are journal insiders and the ability to make recommendations vs. decisions is less about enforcing privileges than accommodating a two-level workflow. But I see in your screenshot that the use case is for a guest editor, who may not be an insider.

Proposed solution: Limit assigned section editors so that they cannot disable the "recommend only" checkbox once it is set. Likewise, limit them from enabling the "make changes to the publication" checkbox when it is disabled.

This will have the side effect of allowing section editors to disable permissions that they can not later re-enable. They would have to ask a full editor/manager to make that change. But I believe this would be a rare source of confusion and easily resolved.

@librariam, does that resolution make sense?

**Comment by librariam** [comment]
Thank you for considering, @asmecher. The request comes from a journal where a section editor enabled their permission when they were not supposed to and recorded a decision on a submission. This is part communication issue, but part functionality issue as well. And of course guest editors would be a step removed from the core as well.

Would it make sense to just not let assistant editors use these controls at all? I don't know that it would be useful to let them limit their own privileges - and as you pointed out, it could lead to a situation where they would have to ask the JM/JE to undo that. I wonder if it would make sense to not show the "Edit" option for own accounts in this case at all, like it was in 3.1?

**Comment by asmecher** [comment]
@librariam, that's also a possible solution, but I'm wondering whether it wouldn't be confusing for Section Editors who were automatically assigned. But yes, the more I think about it, the more that would at least be consistent.

**Comment by asmecher** [comment]
> In either case, the user would need to ask someone else to intervene.

In the case I'm describing, a full Editor would always be able to edit their own assignment, so a third party wouldn't need to intervene. Only section editors would need to request the intervention of a third party, as they should never be able to modify their own assignments. The distinction is based on the role, not the status of the current assignment.

**Comment by asmecher** [comment]
@NateWr, unless you have any objections, I'll defer this to 3.3.0-13.

**Comment by NateWr** [comment]
I have gone with the least disruptive change for 3.3.0-x. The following PRs prevent a subeditor from changing their own permissions and assignment privileges. Managers can still change their own permissions and assignment privileges.

I think this will fix the main issue without significantly changing things in a stable version. If we get further feedback, we can explore other things like when subeditors should be able to change other assigned editors' permissions.

PR:
https://github.com/pkp/pkp-lib/pull/8546

Tests:
https://github.com/pkp/ojs/pull/3705

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and ported to `main`.
