### ISSUE TITLE
Password Change form overwrites user input on failed change

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#7244]
**Describe the bug**
When the user changes their own password, if the form errors (e.g. current password is invalid, new password entries don't match, new password requirements not met) all three password fields are filled with the value of the old password entry.

The expected result would be either to fill the password fields with what was originally present, or to erase the contents of the password fields to force re-entry.

**To Reproduce**
1. Go to Edit Profile -> Password
2. Enter a correct Password as the Old Password, enter "1" as the New Password and "2" as the Repeat new password.
3. Save.
4. Endpoint `.../$$$call$$$/tab/user/profile-tab/save-password` returns HTML with all three fields filled with the Old Password value.

**What application are you using?**
 OJS, OMP or OPS version 3.3.0

**Additional information**
Fault appears to be here:
https://github.com/pkp/pkp-lib/blob/a7fe3795bb572c83774d56fe2a32f995513f2249/templates/user/changePassword.tpl#L33-L34

**Comment by asmecher** [comment]
I resolved this by removing the password bounce-back entirely. It's not a good practice to pre-fill password fields using `value=`.
