### ISSUE TITLE
users.locales incorrect serialization

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7245]
**Describe the bug**
In `users` table, `locales` column, values should be serialized as JSON or PHP array depending on a version. But instead, on my test instances, starting from 3.1.1 and till 3.3.0 it's either a single value, or values separated by a colon, e.g.  en_US:uk_UA . New values on the main branch are serialized as JSON.  

**To Reproduce**
1. Go to `user profle`
2. Check working languages
3. If 1 value is checked, e.g., English, it's seriazed as `en_US`.
4. If several are checked, e.g., English and Ukrainian, it's serialized as `en_US:uk_UA`

**What application are you using?**
 OJS < 3.4

The current main (3.4) branch upgrade script should reflect this serialization change.

**Comment by touhidurabir** [comment]
@asmecher PRs to review
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8322
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3569

**Comment by asmecher** [comment]
Thanks, @touhidurabir! Just one typo to correct (https://github.com/pkp/pkp-lib/pull/8322#discussion_r1003666070) and it's ready to merge. Can you fix the typo and also port to OMP and OPS?

**Comment by touhidurabir** [comment]
@asmecher PRs to merge if all tests pass
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8322
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3569
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1226
[ops](https://github.com/touhidurabir/ops) --> https://github.com/pkp/ops/pull/375

**Comment by asmecher** [comment]
All merged/cherry-picked, thanks!
