### ISSUE TITLE
Fatal error when register a new user

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7246]
**Describe the bug**
A fatal error occurs when trying to register a new user (tested during site-wide registration):
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'date_last_login' doesn't have a default value in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(112): PDOStatement->execute()
#1 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback()
#4 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(465): Illuminate\Database\Connecti in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671
```

**To Reproduce**
1. Go to the registration page and fill out the form
2. Click on the `Register` button
3. See error

**What application are you using?**
 OJS current main branch (3.4)

**Comment by Vitaliy-1** [comment]
@asmecher, I think it's related to a recent PR regarding User Repository

**Comment by asmecher** [comment]
@Vitaliy-1, can you double-check that you've got up-to-date checkouts of the `main` branch for all repos, and a clean database? The Travis tests exercise registering new accounts, and it's running OK locally here.

**Comment by Vitaliy-1** [comment]
Finally, I've got my database upgraded to the latest checkout, although I don't think it was something missing in the migration. Still see the error. It makes sense to me. `date_last_login` doesn't have a default value and when `User` object is inserted during registration, `dateLastLogin` data property isn't set. 

On a clean database, `date_last_login` has a default NULL value and that's why tests are OK. So, looks like a migration issue.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/7256
tests OJS: https://github.com/pkp/ojs/pull/3176
@asmecher, this resolves the error on my test instance. `setting_type` column in `user_settings` is removed on the fresh install but don't see the same during migration. It also causes issue with the default value.

**Comment by asmecher** [comment]
Ah, thanks, @Vitaliy-1 -- I didn't realize you were working with the upgrade toolset, which hasn't been tested/refined for a while. (We usually get to that later in the release cycle.) The fixes look good -- merged!

**Comment by asmecher** [comment]
(I didn't wait for the tests as they don't exercise the upgrade code.)
