### ISSUE TITLE
Fix bugs introduced in Issue EntityDAO refactor

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7247]
**Describe the bug**
I found a few bugs and other improvements after the Issue EntityDAO refactor changes were merged.

**Issues**

- [x] add PR for usageStats plugin updates
- [x] journal/context does not remove previous `current_issue_id` when an issue is unpublished
- [x] update CLOCKSS implementation to mirror LOCKSS in `GatewayHandler`
- [x] typo in Issue Collector causes a fatal error when using `searchPhrase`

**Comment by ewhanson** [comment]
Hi @asmecher, as a heads up: I found a few other things that need fixing with the Issue EntityDAO changes that need fixing. I have fixes for them all and will get a PR in tomorrow. The typo in the issue collector will likely cause Issue API requests to fail until then.

**Comment by asmecher** [comment]
Thanks, please ping me on the PR and I'll have a look!

**Comment by ewhanson** [comment]
Hi @asmecher, I've pinged you on each PR individually, but thought I would do so here as well. Here are the PRs for the above mentioned fixes. Thanks!

PRs:
pkp/usageStats#49
pkp/ojs#3174

**Comment by asmecher** [comment]
Thanks, @ewhanson! Merged the one, I had a question on the other.

**Comment by asmecher** [comment]
Closing.
