### ISSUE TITLE
Unable to install OPS 3.3.0.8

### ISSUE THREAD

**Issue by jameswill** [pkp/pkp-lib#7248]
**Describe the bug**
On trying to install OPS 3.3.0.8 on my test server with php 7.3 and Mysql 5.5 it gives following error.

Array ( [type] => 1 [message] => Uncaught Error: Class 'GenericPlugin' not found in [[PATH]]/ops3308/plugins/generic/crossrefDeposit/CrossrefDepositPlugin.inc.php:14 

**To Reproduce**
1. Upload the package at desired location
2. Give appropriate permissions to cache/ and public/ directories and visit the installer.
3. See error

**What application are you using?**
OPS version 3.3.0.8.

**Comment by NateWr** [comment]
Hi @jameswill. I was unable to reproduce this using the release package at https://pkp.sfu.ca/ops/ops_download/ and following the steps above. Can you provide a more detailed copy of your error log with some of the messages leading up to the fatal error? That might help diagnose the problem

**Comment by asmecher** [comment]
@jameswill, you can probably resolve this by applying [this change](https://github.com/pkp/ops/commit/ae3fa463b0112ed750d9690fd373f6157204db8e). I'm not sure why the ordering of plugin loads on your system is different than our dev/test/production environments, but anyway, it is -- this should resolve it.
