### ISSUE TITLE
Upgrade errors due to attempt to retrieve non-existing DAO 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7250]
**Describe the bug**
Encountering fatal errors when upgrading OJS to the current main branch. Calls to deprecated Illuminate Database Manager instead of Database Facade in 2 places and a failed attempt to [get DAO](https://github.com/pkp/ojs/blob/487cac8c6c5e013f6d23096499bd232a76e04b96/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php#L94) with the message:
```
[migration: OJSv3_3_0UpgradeMigration]
PHP Fatal error:  Uncaught Exception: Unrecognized DAO PKP\announcement\DAO! in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAORegistry.inc.php:73
Stack trace:
#0 /home/doc/OJS/development/ojs/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php(94): PKP\db\DAORegistry::getDAO()
#1 /home/doc/OJS/development/ojs/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php(48): APP\migration\upgrade\OJSv3_3_0UpgradeMigration->_settingsAsJSON()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(445): APP\migration\upgrade\OJSv3_3_0UpgradeMigration->up()
#3 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(282): PKP\install\Installer->executeAction()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/install/Installer.inc.php(197): PKP\install\Installer->executeInstaller()
#5 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(99): PKP\install\Installer->execute()
#6 /home/doc/OJS/development/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(72): PKP\cliToo in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAORegistry.inc.php on line 73
``` 

**To Reproduce**
1. Upgrade to the current main branch from a command line
2. See error

**What application are you using?**
 OJS main branch

**Comment by Vitaliy-1** [comment]
pkp-lib: https://github.com/pkp/pkp-lib/pull/7251
OJS: https://github.com/pkp/ojs/pull/3175

**Comment by Vitaliy-1** [comment]
@asmecher, can you take a look?

**Comment by asmecher** [comment]
This looks good, thanks -- I've merged the PRs for pkp-lib and OJS, but could you also port the change to OMP and OPS?

**Comment by Vitaliy-1** [comment]
OMP: https://github.com/pkp/omp/pull/1002
OPS: https://github.com/pkp/ops/pull/174

**Comment by Vitaliy-1** [comment]
OMP and OPS required additional touch. Merged!
