### ISSUE TITLE
All entity collections should use IDs as keys

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7254]
When refactoring to support entity collections, it was agreed that `getMany` methods should return a collection with each item's ID used as the key.

```php
return LazyCollection::make(function () use ($rows, $query) {
    foreach ($rows as $row) {
        yield $row->user_id => $this->fromRow($row, $query->includeReviewerData);
    }
});
```

Before 3.4 is shipped, we should check that each entity DAO uses this technique. We also need to make sure that anywhere the objects are converted to JSON (eg - to be returned in the REST API or passed as state to Vue) the array keys are reset in order to avoid converting the array into a JSON object.

```php
$users = Repo::user()->getMany(...);
$items = Repo::user()->getSchemaMap()
    ->summarizeMany($users)
    ->values(); /* Reset the array keys */
return $response->withJson(['items' => $items]);
```

**Comment by asmecher** [comment]
The following PRs convert all entities to yielding by ID, *except* email templates, because `email_id` is `null` in some cases (see the `UNION` query). In that case I've left it using indexes as before.

PRs:
- https://github.com/pkp/ojs/pull/3560
- https://github.com/pkp/pkp-lib/pull/8302
