### ISSUE TITLE
Rename email template variables

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7264]
**Describe the problem you would like to solve**
1. Unify variable names across templates
2. Better reflect the content of variables

**Describe the solution you'd like**

- `editors` -> `decidingEditors`
- `journalName` -> `contextName`
- `passwordResetUrl` -> `passwordLostUrl`; only declared in PKPreviewerGridHandler and ReviewerForm as there it only provides the URL to the lost password page.
- all instances with a meaning of a recipient full name, like `authorName`, `subscriberName`, `participantName` or `editorialContactName` -> `userFullName`
- all instance with a meaning if recipient username, like `reviewerUserName`, `userName`, `editorUsername` or `participantUsername` -> `username`
- `abstractTermIfEnabled` -> `submissionAbstract`
- `authorName` in sense of full names of authors of a submission -> `authorsFull` 
- `url` in sense of URL to the notification -> `notificationUrl`

**Who is asking for this feature?**
Me

**Additional information**
The list may be expanded

**Comment by NateWr** [comment]
Thanks @Vitaliy-1. There is also a Variables section in [this document](https://docs.google.com/document/d/15fYHs5ESFDbH0VAVsG5uftLKXerH1OQ_DNqHCBDfbcA/edit#) from @kshuttle. The following comments are derived from it:

- `submissionTitle` should always include full title with prefix and subtitle.
- `editorialContactSignature` -> `signature`: If the sender (or editor for automated emails) has no signature, use their full name instead.
- `submissionReviewUrl` -> `reviewAssignmentURL`
- New: `issue` This will be something like: Vol. 1 No. 3 (2019). Or if there is a title like: Vol. 1. No. 3 (2019) Special issue on bat skeletons

A few more comments:

> decidingEditors

Is this only ever used for a recommendation? Is that why it's called deciding editors? If so, that's fine. But if `editors` is in other contexts, we may want to leave it. Also, should we call this `decidingEditorsFullNames` to align with the other changes related to names?

> journalName -> contextName

If possible, we should try to support keeping these as `journalName`, `pressName` and `serverName`. "Context" is not a term that is understood by end users.

Would it be possible to do this with a `ContextEmailVariable` class in the `APP` namespace that overrides `ContextEmailVariable` in the `PKP` namespace?

> userFullName, username

When this is associated with a recipient, we should call it `recipientFullName` and `recipientUsername`.  (This should correspond to `senderFullName` and `senderUsername` variables.)

> authorsFull

What about just `authors` for the full names with affiliation and `authorsShort` for the short string (eg - Wright et al).

**Comment by Vitaliy-1** [comment]
PRs:
pkp-lib https://github.com/pkp/pkp-lib/issues/5730
OJS: https://github.com/pkp/ojs/pull/3248
OMP: https://github.com/pkp/omp/pull/1044
OPS: https://github.com/pkp/ops/pull/210

**Comment by asmecher** [comment]
Excellent, @Vitaliy-1, really happy to see this merged!
