### ISSUE TITLE
Improve workflow for making an editorial decision

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7265]
**Describe the problem you would like to solve**
While implementing improvements to email sending in #5717, it was necessary to build out step-by-step workflows for editorial decisions. These workflows can be short, one-step actions or long, multi-step actions. 

In the future, we will likely want to expand on these workflows with more options, such as kicking off file conversions, adding notifications, or automating pre-publication deposits in third-party repositories.

The more complicated workflows are difficult to manage in a pop-up window. There is not much space to provide guidance through the process, and it's easy to accidentally close the pop-up.

**Describe the solution you'd like**
Add a new full-page workflow for making an editorial decision. This will provide the room to implement a full step-by-step wizard, and make it easier to extend editorial decision workflows with new form fields, notification emails, and more.

To date, all editorial decisions involve one or more steps in one of the following types:

- A form to select or enter information.
- One or more emails to be sent.
- A UI to promote files from the current stage to the next stage.

The full-page workflow that I describe would permit each decision to define its own workflow. So a new decision type can define its own workflow requirements, and existing types can be overwritten by a plugin to define more workflows.

**Who is asking for this feature?**
As a developer, it will help reduce the complexity of the submission workflow page and make it easier to maintain different editorial decision workflows.

**Additional information**

Draft PRs:
https://github.com/pkp/ui-library/pull/176
https://github.com/pkp/pkp-lib/pull/7631
https://github.com/pkp/ojs/pull/3279
https://github.com/pkp/omp/pull/1071
https://github.com/pkp/ops/pull/240

After you have the PRs, run the following:

```
cd <ojs-root>
npm run dev
php lib/pkp/tools/migration.php APP\\migration\\upgrade\\v3_4_0\\I7265_EditorialDecisions up
```

**Mockups**
The following mockups show examples of simple and complex editorial decision workflows.

## Accept for Publication
This is a complex workflow, with 3-4 steps (a payment step is added in OJS).

![ Payment](https://user-images.githubusercontent.com/2306629/132342659-8a82a4b3-88e5-4ea0-89fb-ea710ddf5305.png)
![ Notify Author](https://user-images.githubusercontent.com/2306629/132342668-9e50c64b-6ecb-44eb-bb7e-667e024c97a7.png)
![ Notify Reviewers](https://user-images.githubusercontent.com/2306629/132342678-23686b62-3ae6-4a88-99da-f0da077462e5.png)
![ Promote Files](https://user-images.githubusercontent.com/2306629/132342688-04fc88f5-095e-49ed-ba62-bc7e6339ecec.png)
![ Complete](https://user-images.githubusercontent.com/2306629/132342697-f436e3a9-eb2d-40a1-af2d-cfb76d3bc686.png)

## Send for Review
This a simple workflow with two steps.

![ Notify Author](https://user-images.githubusercontent.com/2306629/132342810-0fbc9719-1f6c-4e85-b72d-0e732b7bc227.png)
![ Promote Files](https://user-images.githubusercontent.com/2306629/132342813-75c1d3a0-646f-4724-a15d-ad59ccde625b.png)

## Decline without Review
This is the simplest form of review, with only one step.

![ Notify Author](https://user-images.githubusercontent.com/2306629/132342865-baf51e23-15df-4a94-a50b-f3c67e712473.png)

**Comment by NateWr** [comment]
@israelcefrin recommended that we add the current step to the page title, based on UX tests of a similar pattern with the new [submission wizard](#7191).

**Comment by asmecher** [comment]
There should be tools to import peer reviews, and to skip sending any email, but otherwise this looks good. In most cases there will not be APCs so the first step of the first mock-up should be hidden. I suspect it'll take a little getting used to seeing the email composition given so much space but the current email composition fields are definitely undersized.

**Comment by NateWr** [comment]
:+1: Import peer reviews and skip sending email are on my list. The goal here is that each decision defines its own workflow. So any steps can be added/removed (eg - to support APCs in one app or not), including by plugins.

**Comment by alexxxmendonca** [comment]
This looks great, @NateWr 

I think "Notify Reviewers" should not be restricted to Accept submission. Many journals like to share the reviews amongst the reviewers for every decision taken (including Revision and Declined).

**Comment by NateWr** [comment]
It will be available on all review stage decisions. That's the way it works now (sort of, there's a BCC Reviewers option).

**Comment by willinsky** [comment]
This looks very clean and helpfully laid out. And while I do not want to complicate the page too much, when an editor makes a decision there's going to often be a need to consult the reviews and look at the record perhaps including previous rounds and the reviewers who have been involved. I see there will be an "import reviews" function, but importing reviews into the email is not something that an editor would necessarily want to do in responding to a revised copy or with reviews from an earlier round. I think the editor as having all the pertinent documents before her on a desktop in writing up her decision, so perhaps series of preview windows for reviews or a way to the see the review history.

**Comment by NateWr** [comment]
Thanks @willinsky. The moment you describe will still occur on the submission workflow page, where the editor can view reviews, discussions, files, etc. When the editor has chosen a decision (eg - Accept), they will be taken to this UI to complete the process.

I can see that the editor might want to consult the reviews while writing the email. But this was not possible in the current UI either (editor would need to close the pop-up to view reviews). The proposed UI would make it easier to support this in the future. And in the meantime, having two distinct pages will make it easier to "open in a new window/tab" for those more technically savvy.

**Comment by pilasou** [comment]
@NateWr  Hi! I really like this idea! It may be necessary to think incrementally though, as there is a lot of stuff that can be imagined with this new way of managing editorial decisions. I would suggest that a first step would be get ride off the pop up window and implement workflows (revision, accept, reject) as is. The idea to let editors select which emails they want to send (as shown is the mockup) is also something we are asked by the journals we host.

**Comment by NateWr** [comment]
@asmecher Here are early draft PRs for the new editorial decisions. There's lots of UI work left to do, and OMP and OPS, but the new decisions are in place and working in OJS. This is a massive PR and will likely shift as a I work on OMP/OPS. However, I wanted you to take an initial look at the overall approach.

PRs:
https://github.com/pkp/ui-library/pull/176
https://github.com/pkp/pkp-lib/pull/7631
https://github.com/pkp/ojs/pull/3279

After you have the PRs, run the following:

```
cd <ojs-root>
npm run dev
php lib/pkp/tools/migration.php PKP\\migration\\upgrade\\v3_4_0\\I7265_EditorialDecisions up
```

Outline of the new Decision classes:
- Every decision is a class that extends a [root Type](https://github.com/NateWr/pkp-lib/blob/i7265_decisions/classes/decision/Type.inc.php). All decisions can be found in `classes/decisions/types`.
- Each decision class implements methods like `getNewStatus()` to change submission status, change stage id, etc.
- When a decision is recorded, a `callback()` method is fired on the decision class, so it can perform any additional actions (sending emails, recording payments, etc).
- Each decision class implements a `getWorkflow()` method. This defines the step-by-step UI for recording that decision (ie - drafting emails, choosing payment waivers, promoting files, etc).

With this approach, I think that we are a few steps closer to how you once described designing the workflow to be a kind of configurable state machine. Each decision class is responsible for determining the state after a decision is recorded. Plugins can add new decisions to modify the workflow.

There are several known issues that I will sort out before or after merge:
- In the new email composer UI, the button to add variables into the email is a nightmare.
- Can't add email variables when editing an email template in the settings area.
- Email template descriptions aren't installed correctly.
- Previews in UI Library probably won't work -- haven't tested in a while.

Apologies, there is a lot of code here. 

cc @Vitaliy-1 you may be interested to see the email side of this, which you will find by looking at a given decision type's `callback()` method (and `getWorkflow()` for how the mailable is used to pass data to the email composer).

**Comment by asmecher** [comment]
Thanks, @NateWr, that's a huge amount of work! I've added comments to the PRs but a few general comments...
- There's a bit of cardinality creep in the decisions, i.e. they multiply out the options for the source and destination stage. I thiiiiink this will be OK because the cardinalities are not huge -- though you may find a bunch more are necessary in OPS because of the additional review stage option -- but I'm curious if you considered teasing these apart.
- Tests are failing but you probably knew that.
- This is a ton of new code, but I'm so happy to see a lot of red around some big classes that are older than dirt (e.g. `classes/workflow/PKPEditorDecisionActionsManager.inc.php` is deleted completely!!)
- The file attachment stuff looks really slick.
- There are some extra clicks involved compared to our current toolset, and this might cause some griping, but I don't think editorial decision recording is such a high-volume activity that we really have to worry about it.
- I took a spin around the workflow and it looks ***great***, a few layout quirks and one error when publishing a submission scheduled to a back-issue:
   ```
   Message: Too few arguments to function PKP\submission\maps\Schema::summarize(), 2 passed in /home/asmecher/git/ojs-main/classes/issue/maps/Schema.inc.php on line 99 and exactly 3 expected
   File: /home/asmecher/git/ojs-main/lib/pkp/classes/submission/maps/Schema.inc.php
   Line: 114
   Trace: #0 /home/asmecher/git/ojs-main/classes/issue/maps/Schema.inc.php(99): PKP\submission\maps\Schema->summarize()
   #1 /home/asmecher/git/ojs-main/classes/issue/maps/Schema.inc.php(33): APP\issue\maps\Schema->mapByProperties()
   #2 /home/asmecher/git/ojs-main/api/v1/issues/IssueHandler.inc.php(240): APP\issue\maps\Schema->map()
   #3 [internal function]: IssueHandler->get()
   #4 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
   #5 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
   #6 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke()
   #7 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
   #8 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
   #9 /home/asmecher/git/ojs-main/lib/pkp/classes/security/authorization/internal/ApiAuthorizationMiddleware.inc.php(90): Slim\App->__invoke()
   #10 [internal function]: PKP\security\authorization\internal\ApiAuthorizationMiddleware->__invoke()
   #11 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
   #12 [internal function]: Slim\DeferredCallable->__invoke()
   #13 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
   #14 /home/asmecher/git/ojs-main/lib/pkp/classes/security/authorization/internal/ApiCsrfMiddleware.inc.php(54): Slim\App->Slim\{closure}()
   #15 [internal function]: PKP\security\authorization\internal\ApiCsrfMiddleware->__invoke()
   #16 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
   #17 [internal function]: Slim\DeferredCallable->__invoke()
   #18 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
   #19 /home/asmecher/git/ojs-main/lib/pkp/classes/security/authorization/internal/ApiTokenDecodingMiddleware.inc.php(131): Slim\App->Slim\{closure}()
   #20 [internal function]: PKP\security\authorization\internal\ApiTokenDecodingMiddleware->__invoke()
   #21 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
   #22 [internal function]: Slim\DeferredCallable->__invoke()
   #23 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
   #24 /home/asmecher/git/ojs-main/lib/pkp/classes/handler/APIHandler.inc.php(80): Slim\App->Slim\{closure}()
   #25 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
   #26 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
   #27 [internal function]: Slim\DeferredCallable->__invoke()
   #28 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
   #29 /home/asmecher/git/ojs-main/lib/pkp/classes/handler/APIHandler.inc.php(139): Slim\App->Slim\{closure}()
   #30 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
   #31 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
   #32 [internal function]: Slim\DeferredCallable->__invoke()
   #33 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
   #34 /home/asmecher/git/ojs-main/lib/pkp/classes/handler/APIHandler.inc.php(144): Slim\App->Slim\{closure}()
   #35 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
   #36 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
   #37 [internal function]: Slim\DeferredCallable->__invoke()
   #38 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
   #39 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
   #40 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
   #41 /home/asmecher/git/ojs-main/lib/pkp/classes/handler/APIHandler.inc.php(136): Slim\App->process()
   #42 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
   #43 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
   #44 [internal function]: Slim\DeferredCallable->__invoke()
   #45 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
   #46 /home/asmecher/git/ojs-main/lib/pkp/classes/handler/APIHandler.inc.php(144): Slim\App->Slim\{closure}()
   #47 [internal function]: PKP\handler\APIHandler->PKP\handler\{closure}()
   #48 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
   #49 [internal function]: Slim\DeferredCallable->__invoke()
   #50 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
   #51 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
   #52 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
   #53 /home/asmecher/git/ojs-main/lib/pkp/lib/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
   #54 /home/asmecher/git/ojs-main/lib/pkp/classes/core/APIRouter.inc.php(129): Slim\App->run()
   #55 /home/asmecher/git/ojs-main/lib/pkp/classes/core/Dispatcher.inc.php(166): PKP\core\APIRouter->route()
   #56 /home/asmecher/git/ojs-main/lib/pkp/classes/core/PKPApplication.inc.php(337): PKP\core\Dispatcher->dispatch()
   #57 /home/asmecher/git/ojs-main/index.php(68): PKP\core\PKPApplication->execute()
   #58 {main}
   ```

This is really exciting, @NateWr!

**Comment by NateWr** [comment]
Thanks!

> There's a bit of cardinality creep in the decisions, i.e. they multiply out the options for the source and destination stage.

Can you explain a bit more what you mean by this? Are you referring to the fact that what was one decision type before (Accept) is now two decision types (Accept, Accept and Skip Review)?

> There are some extra clicks involved compared to our current toolset, and this might cause some griping

I'm sure we're going to get some push-back on this. But we get a lot of requests to be able to do more stuff when taking a decision (send other emails, assign/reassign reviewers, send files for processing, assign copyeditors, etc). There's no way we could sensibly support these features in the tiny modal that we were using.

**Comment by NateWr** [comment]
Yeah that makes sense. Thanks for the review. I think I've handled all of the review comments, and fixed the fatal error you got. I'll now work on porting to OMP/OPS. :+1:

**Comment by fgnievinski** [comment]
In the Request Revisions form, it's not super clear if "Select review files to share with the author(s)" would actually attach the files in the email message or only make the files available for download from the journal website.

And after the decision is recorded and the Round N Status is updated (e.g., "The submission must be resubmitted for another review round."), then the decision buttons could be disabled (Request Revisions, Accept Submission, Decline Submission), to avoid a re-decision.

**Comment by NateWr** [comment]
> In the Request Revisions form, it's not super clear if "Select review files to share with the author(s)" would actually attach the files in the email message or only make the files available for download from the journal website.

Sharing review files is now done entirely through the "Attach Files" UI. I'll try to share a short video of that at some point.

> the decision buttons could be disabled... to avoid a re-decision.

Unfortunately, a re-decision is too common to disable them completely. The current UI hides the decision buttons and the user must click a button "Change decision" to see them and take a new decision.

**Comment by fgnievinski** [comment]
> The current UI hides the decision buttons and the user must click a button "Change decision" to see them and take a new decision.

That's great, looking forward to the new UI design! For the record, here's the screenshot after a decision is made in version 3.3.0.8:

![image](https://user-images.githubusercontent.com/5018500/152037938-75d50f39-6db2-4570-91d2-f894795118d2.png)

**Comment by NateWr** [comment]
Ah, you're right. The "change decision" UI doesn't appear when a resubmit or request revisions decision is made. That's because we expect one more decision to be taken in this review round: accept, decline, or create new round.

**Comment by NateWr** [comment]
All PRs merged to `main`. :tada:  There is still some work to do on the UI/UX, but I will file those in a separate issue.

@amandastevens this will impact documentation. I plan to record a short video of the new editorial decision workflow, so I will post that here when it is available.

**Comment by NateWr** [comment]
The following is a short video that describes the changes to recording an editorial decision. This is a very brief overview intended for internal use, but please ask any questions you have in the support forum or other community spaces.

(Sorry, I forgot to record my cursor so it is sometimes difficult to see what I have clicked on.)

https://user-images.githubusercontent.com/2306629/157087347-199d476d-1726-4fa4-a768-dfd2b33bcc2e.mp4

**Comment by mrqorib** [comment]
Hi @NateWr , is this new editorial decision workflow available in OJS 3.3.0-10? If not, is it possible to add this feature to a running OJS 3.3.0-10 that I currently use? Thank you.

**Comment by asmecher** [comment]
@mrqorib, no, this isn't possible to add to 3.3.0-10; too much development has happened since the 3.3.0 branch was forked from `main`. This workflow will be released in 3.4.0, which will likely be released in Q1 next year.

**Comment by mrqorib** [comment]
@asmecher Thank you for your quick reply. Is it possible to just add cc and bcc functionality to OJS 3.3.0-10? I tried the code from this forum https://forum.pkp.sfu.ca/t/add-bcc-field-to-mail-forms/58868/4 but it doesn't show any cc/bcc form when sending the email for submission acceptance/rejection.

**Comment by asmecher** [comment]
That feature is discussed/implemented in https://github.com/pkp/pkp-lib/issues/5717 and it wouldn't be easy to back-port to 3.3.0, unfortunately. A lot of work has gone into the `main` branch, resulting in the two being widely forked. Can I recommend asking questions like this on our support forum (https://forum.pkp.sfu.ca)? That'll help keep these issue discussions organized.

**Comment by Devika008** [comment]
Since we are furthering the email composer to various other places in the system, I refined it after doing some more user interviews and feedback from @marcbria. I think these new tweaks in the email composer make it much more intuitive and user friendly, giving the right indications.

![image](https://github.com/pkp/pkp-lib/assets/112014397/7cd99fb1-fbc8-4261-8cf4-7ab08e4a0a72)
