### ISSUE TITLE
Allow period/full-stop in url paths

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7267]
**Describe the bug**
The `.` character was permitted in URL paths as far back as OJS 2.x This was restricted from OJS 3.2.x in order to support better URLs. However, this prevents changes from being made to an old publication, effectively forcing a long-standing URL to change.

The regex for URL paths should be relaxed to permit the `.` character.

**To Reproduce**
This can be reproduced in the publication settings under the Issue Entry tab. See screenshots in [this forum post](https://forum.pkp.sfu.ca/t/allow-point-capture-in-article-path-url/69367).

**What application are you using?**
Effects 3.2.x-3.3.x. This change should be back-ported to 3.2.1 if possible.

**Comment by NateWr** [comment]
@asmecher can you look over this for me? I wanted to port it back to `stable-3_2_1`, since it's a potential upgrade blocker, but it got a little complicated because there was a locale string change. We're not set up for translations against 3.2.1, right?

1. I allowed `.` in all URL paths _except_ the context. A `.` in a context URL path will break API requests (I'm guessing it's an issue in the router).
2.  I included the locale string change in the `stable-3_3_0` PRs but _not_ in the `stable-3_2_1` PRs.

3.3.0.x PRs:
https://github.com/pkp/pkp-lib/pull/7268
https://github.com/pkp/ojs/pull/3177
https://github.com/pkp/omp/pull/1004
https://github.com/pkp/ops/pull/175

3.2.1.x PRs:
https://github.com/pkp/pkp-lib/pull/7269
https://github.com/pkp/ojs/pull/3178
https://github.com/pkp/omp/pull/1005
https://github.com/pkp/ops/pull/176

**Comment by asmecher** [comment]
Please go ahead, @NateWr (and don't forget to merge to `main` too). I'm OK with the locale string changes not being made in older branches. The text is incomplete, not incorrect.

**Comment by NateWr** [comment]
@asmecher the 3.2.1 unit tests are failing because they expect `http` to be a valid protocol for ORCID, but the validator enforces `https`. It looks like @withanage made this change back in May: https://github.com/pkp/pkp-lib/commit/ab8f6abb8a0274e23f6a0f5ec35c08bffef90d7c.

But more recent merges to 3.2.1 have passing tests: https://app.travis-ci.com/github/pkp/ojs/branches

Am I missing something here? My PR doesn't change the test in any way.

**Comment by NateWr** [comment]
@withanage no worries, I'll take care of this.

**Comment by NateWr** [comment]
@asmecher the tests are passing for everything except OMP 3.2.1, which is failing because the log exceeds the maximum length for PHP 7.3 and PHP 7.4. It looks like the unit tests are finished, though. https://app.travis-ci.com/github/pkp/omp/jobs/537048347

What do you think? Should I merge this or just leave it alone? I feel like the time v. reward ratio has run out on porting this back to 3.2.1.

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and `stable-3_2_1`, and adapted/committed to `main`.

**Comment by Vitaliy-1** [comment]
@NateWr, build on main is failing after this commit during editing publication data: `publication -> issue -> URL path`

**Comment by NateWr** [comment]
Thanks! I think this is happening because I forgot to update the submodule when I ported the changes forward to `main`. I've updated the submodule in `main` now. Let me know if the OJS tests still fail.
