### ISSUE TITLE
[OMP] Can't create publication format

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#727]
There are no publication formats to select from when trying to create a publication format for a book.

![omp-no-pub-format](https://cloud.githubusercontent.com/assets/2306629/9684811/f9aa269e-5311-11e5-853c-ce07aeffe8b2.png)

**Comment by asmecher** [comment]
@NateWr, double-check to see if your PHP installation has XSL support. You might need to install a PHP module.

**Comment by NateWr** [comment]
That fixed it.
