### ISSUE TITLE
Ojs

### ISSUE THREAD

**Issue by Zain-UlAbdin** [pkp/pkp-lib#7271]
How can I get to my ojs file upload settings?

**Comment by asmecher** [comment]
@Zain-UlAbdin, please post your question on our support forum (https://forum.pkp.sfu.ca), including more details:
- What version of OJS are you using?
- What are you trying to do when you encounter a problem?
- What are the details of the problem or error message you encounter?

**Comment by Zain-UlAbdin** [comment]
Ojs 3.3.06

**Comment by asmecher** [comment]
@Zain-UlAbdin, please post these details on our support forum (https://forum.pkp.sfu.ca) -- if it turns out to be a bug we'll open an issue here.
