### ISSUE TITLE
[OPS] Validate DOI field in "Relations" form

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#7274]
**Describe the problem you would like to solve**
The field where it's expected the DOI for the preprint Version of Record doesn't have any conditional formatting:

![image](https://user-images.githubusercontent.com/4059679/132686706-1bdc3b97-8101-44bf-ab9a-6d386fc0bd30.png)

In the above example, because the URL doesn't start with "https://doi.org/", it gives an error when clicking on the URL that appears at the public interface.

Users can type anything, including things that are not DOI (e.g. text strings).

This results in errors when showing the link to the published article:

![image](https://user-images.githubusercontent.com/4059679/132687136-825e96bb-bca7-4fb0-b1e4-2cd343bcf7ce.png)

(in the image above you can see that a text string has been entered. The link is, therefore, broken).

**Describe the solution you'd like**
Ideally there would be a conditional formatting on this field that would look for DOI URLs, preventing users from typing anything other than a DOI URL.

**Who is asking for this feature?**
Readers, Authors, Server Admins.

**Comment by NateWr** [comment]
The following PRs validate the input to make sure it is a valid URL. However, I'm not sure if we can do any further validation in terms of the DOI format. @asmecher should we add a DOI validator to `ValidatorFactory`? Can we assume it will be `0000.000/xxxxx` or might DOIs looks different?

PRs:
https://github.com/pkp/ops/pull/179 `stable-3_3_0`
https://github.com/pkp/ops/pull/180 `main`
https://github.com/pkp/pkp-lib/pull/7278 `main`

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and `main`.

**Comment by asmecher** [comment]
@Nate, here's some regexps for DOIs from the horse's mouth: https://www.crossref.org/blog/dois-and-matching-regular-expressions/

**Comment by asmecher** [comment]
Actually, scratch that -- it would only be for Crossref DOIs. The DOI spec itself allows very broad DOIs -- prefix and suffix can contain anything printable. I think all you can really assert without really getting into the weeds is that it starts with "10." and contains a slash.

**Comment by NateWr** [comment]
Ok, thanks. cc @ewhanson (see above)
