### ISSUE TITLE
User can register using login containing an underscore symbol "_", but cannot log in

### ISSUE THREAD

**Issue by dogsleg** [pkp/pkp-lib#7276]
It is possible for a user to (self-) register and choose a login containing an underscore symbol "_" (e.g. "someone_else"), but it is not possible to log in with such a login. OJS keep telling that user with "someone_else" login does not exist.

1. Register a new user, choose login with an underscore symbol (e.g., "someone_else")
2. Try to log in after the registration
3. See error

OJS 3.3.0-8

My server runs under Debian GNU/Linux 10. I use MariaDB (package version 1:10.3.29-0+deb10u1).

**Comment by Tyl13** [comment]
I'm not sure this is still an issue? At least on stable-3_3_0. I can successfully register as someone_else: 
![image](https://user-images.githubusercontent.com/48526589/157726702-4f77f659-8694-41ad-83b8-b56a4e99caa3.png)
After sign out, I can login successfully as someone_else:
![image](https://user-images.githubusercontent.com/48526589/157726866-dd537b13-2842-4f9d-8326-f15051fffb09.png)

**Comment by asmecher** [comment]
@dogsleg, can you confirm whether this is still an issue?

**Comment by dogsleg** [comment]
@asmecher, I've just upgraded to 3.3.0-10 and tried with someone_else. It works perfectly. Thanks! Closing the bugreport.

**Comment by asmecher** [comment]
It must've gotten fixed incidentally. Thanks, @dogsleg!
