### ISSUE TITLE
Discussion participants include declined open reviewers

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7277]
**Describe the bug**
When a review assignment is open, the author can create a discussion with reviewers. However, the author can open a discussion even with reviewers who have declined the review assignment.

Reviewers should only be available as discussion participants when they have been assigned an open review and after they have accepted the review assignment.

**To Reproduce**
I haven't reproduced this myself, but I suspect:
1. Add an open review assignment.
2. Login as author.
3. Create a discussion.
4. See reviewer who hasn't accepted request.

**What application are you using?**
Unknown

**Additional information**
See [report in forum](https://forum.pkp.sfu.ca/t/start-a-discussion-in-ojs/69517).

**Comment by ajnyga** [comment]
At least this does not apply, can not see a reviewer who is not assigned:
Add an open review assignment.
Login as author.
Create a discussion.
See reviewer who hasn't accepted request.

**Comment by ajnyga** [comment]
Ok so @NateWr the whole feature for adding reviewers seems to be broken in the current main branch. 
As an editor I can not see an assigned reviewer, a reviewer who has accepted nor a reviewer who has declined in the discussion form.
Also as an author  I can not see an assigned reviewer, a reviewer who has accepted nor a reviewer who has declined in the discussion form.

**Comment by ajnyga** [comment]
Also the unassigned journal editor initiating a discussion is not added to the participants list. Something is broken around here: https://github.com/pkp/pkp-lib/blob/main/controllers/grid/queries/form/QueryForm.inc.php#L342-L343
The `includeUsers` array is set correctly but the users are not fetched.

**Comment by ajnyga** [comment]
OJS https://github.com/pkp/ojs/pull/3182 (only tests)
pkp-lib https://github.com/pkp/pkp-lib/pull/7295

**Comment by ajnyga** [comment]
Note that editors see all reviewers - pending, accepted, declined - in the discussion participants list

**Comment by asmecher** [comment]
Merged -- thanks, @ajnyga! I also back-ported the relevant change to `stable-3_3_0`.
