### ISSUE TITLE
Redundant and not escaped special characters in locale files

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7281]
**Describe the bug**
Special characters, which should be escaped in localization files, like double quotes: https://github.com/pkp/ops/blob/99bf5b9dde17f3484dda82a3207029b0dbb76254/locale/en_US/manager.po#L348

Redundant  characters: https://github.com/pkp/ops/blob/99bf5b9dde17f3484dda82a3207029b0dbb76254/locale/en_US/author.po#L17

Likely only in `en_US` locale files. 

**What application are you using?**
Noticed when working with main branches of OPS and OMP. 

**Additional information**
Found in several files. Probably a systematic issue, e.g., with how localizations are updated there.

**Comment by asmecher** [comment]
I fixed the typos I could find (of both kinds identified above) and linted the PO files successfully using `po2txt`. The commits that introduced these appear to have been manually, i.e. not using gettext/Weblate toolsets, so I think we're systematically OK. I couldn't find anything in OJS, OMP, or pkp-lib. Thanks for spotting these, @Vitaliy-1!

**Comment by asmecher** [comment]
(Cherry-picked to `stable-3_3_0` for release in OPS 3.3.0-9)

**Comment by Vitaliy-1** [comment]
OMP has at least in `manager.po`: https://github.com/pkp/omp/blob/c66ce205159a908df706c4169fdf87e6dcace0ca/locale/en_US/manager.po#L918

**Comment by Vitaliy-1** [comment]
If not systematic, I'll fix if find other

**Comment by asmecher** [comment]
The `po2txt` doesn't identify missing escaping on `"` characters, but it also appears to be able to read them just fine. Yes, these don't appear to be systematic; please fix them when you see them.
