### ISSUE TITLE
Missing rights for internal reviewer to download  files.

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#7284]
**Describe the bug**

-   Editor / Journal manager assign an internal  reviewer for a submission.
-  Reviewer gets a notification  for review.
-  When accessing the review process, the assigned reviwe file cannot be downloaded.

**To Reproduce**

 As  Press Manager or Series Editor
1. Login to OMP 
2. Select a  Submission in internal review stage and select "Internal Review"
3. Under Round X (default 1)  and click on "Add reviewer"  under Reviews Table.
4. Select  a reviewer by clicking "select reviewer"  in  the "Add reviewer modal"

As reviewer

1. Login in to OMP as the select reviewer in the preivous step.
2. Click on ' "My Queue" and click on "view" on the "Review Assignment"
3. You will be redirected to Tab "3. Downalod and Review"
4. Click on the file under  Table "Review Files"

An error message will appear  "The current role does not have access to this operation."
```json
{"status":false,"content":"The current role does not have access to this operation.","elementId":"0","events":null}
```

URL of the error message is  similar to the following:
http://localhost/omp-330/index.php/publicknowledge/$$$call$$$/api/file/file-api/download-file?submissionFileId=16&submissionId=6&stageId=2

**What application are you using?**
OMP  3.3.0-8

**Additional information**

-  originally reported in [forum](https://forum.pkp.sfu.ca/t/omp-3-3-0-4-and-3-3-0-7-internal-reviewer-has-no-rights-to-download-files-the-current-role-does-not-have-access-to-this-operation/69147)

**Comment by withanage** [comment]
FYI @NateWr

**Comment by asmecher** [comment]
@withanage, I've committed this directly to `master` and `stable-3_3_0`, as the changes are minimal and I tested them. However, could you take a look, particularly at the `stable-3_3_0` change (https://github.com/pkp/pkp-lib/commit/347432f8a892401d721a3dc172f94817e3800a00)?

**Comment by withanage** [comment]
@asmecher 
apologies, this one went unnoticed by me.  I  tested this  workflow on  OMP 3.3.0-8  and can confirm  the  problem is fixed.

**Comment by asmecher** [comment]
Thanks, both!
