### ISSUE TITLE
Investigate how to handle cases where sendmail executable can not be invoked

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7285]
Sendmail was introduced in #7141 as part of the adoption of Swift Mailer. This relies on `proc_*` functions which may not be supported in all environments where OJS/OMP/OPS is run. A comment from @asmecher:

> We are likely to run into two categories of support issues with users who previously relied on the default mail()-based PHPMailer transport and who are thus moved to the sendmail-based Swiftmailer equivalent:
>
> - Users who will run into problems because of the proc_* functions being disabled by the hosting environment. I propose that we direct these users to either using SMTP, or convincing their host to enable the proc_* functions. They will probably have better luck with SMTP.
> - Users whose hosts don't have sendmail configured in the place it's expected to be per the default configuration. This would be helped through sensible error handling -- please make sure if the binary path is misconfigured or can't be executed, that an error message results. Also, I suggest putting the default setting in the Config::getVar call as well, so that it'll behave nicely if the user doesn't remember to add the new config.inc.php setting after upgrading.

We need to investigate how widespread this impact may be and/or implement mechanisms (like a pre-flight check) to highlight the new dependency during upgrade.

There is more discussion in [this pull request](https://github.com/pkp/ojs/pull/3169#pullrequestreview-726309811).

**Comment by Vitaliy-1** [comment]
As Swift Mailer is deprecated and no longer supported, I'm planning to move to Symfony Mailer, which also relies on `proc_*` functions:  https://github.com/symfony/mailer/blob/391a2ac6bf8ab298caa7b63826edc9500412ed16/Transport/Smtp/Stream/ProcessStream.php#L41
And it doesn't support `mail()` function either.

**Comment by Vitaliy-1** [comment]
What about keeping PHPMailer's `mail` transport for cases when `proc_open` function is disabled? Basically, it requires porting our current Mail::send implementation to Symfony's Transport interface. Is it expected that such cases for shared hosting providers are common?

**Comment by asmecher** [comment]
> Is it expected that such cases for shared hosting providers are common?

Yes, I expect so, unfortunately :( and adopting Symfony Mailer without a "plan B" for hosts that can't use it will turn this into a complaint megathread like this one: https://github.com/swiftmailer/swiftmailer/issues/866#issuecomment-289291228

So I would support a work-around that permits users who can't use `proc_open` functions to continue somehow.

However, I'm not a fan of including both PHPMailer and Symfony Mailer just for this work-around. What do you think about a plugin that adds PHPMailer for those who need it? That way we wouldn't have to ship that whole set of dependencies for our "preferred" implementation.

**Comment by asmecher** [comment]
OK, I can be convinced to back away from the plugin approach -- but I would love to have a sunset plan for shipping both libraries.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8179
OJS: https://github.com/pkp/ojs/pull/3498

**Comment by Vitaliy-1** [comment]
Ready to be merged. @asmecher, do you have time to review it? These PRs add PHPMailer transport to send emails with PHP mail().

**Comment by asmecher** [comment]
All PRs reviewed! https://github.com/pkp/pkp-lib/pull/8179#pullrequestreview-1081000212

**Comment by Vitaliy-1** [comment]
Thanks, merged!
