### ISSUE TITLE
Convert all configurable emails to Mailables

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7286]
Laravel's Mailables class was introduced in #7141. These replace our previous Mail and MailTemplate classes with a new system to support configurable emails, events and email variables.

All existing email templates in the system need to be converted to Mailables, with their variables pre-defined. Once this is completed, the email templates editing UI needs to be changed to support editing templates by their associated Mailables.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8116
OJS: https://github.com/pkp/ojs/pull/3469

**Comment by Vitaliy-1** [comment]
@NateWr, can you take a look? These PRs refactor the remaining email sending code to use Mailables; mostly notification- and subscription-related and several others. Also, it adds job batching.

**Comment by NateWr** [comment]
Looks good @Vitaliy-1! I think it's pretty much ready for merge. Mostly minor changes.

**Comment by Vitaliy-1** [comment]
PRs
OJS: https://github.com/pkp/ojs/pull/3469
OMP: https://github.com/pkp/omp/pull/1167
OPS: https://github.com/pkp/ops/pull/323
pkp-lib: https://github.com/pkp/pkp-lib/pull/8116

**Comment by NateWr** [comment]
Thanks @Vitaliy-1. All merged. What a big milestone on this marathon refactor! :tada:
