### ISSUE TITLE
Remove old code for sending email

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7287]
Issue #7141 introduced Laravel's mailer to send email. After #7286 is done, most of the emails in the system will have been converted to use this new mailer.

Convert any emails send using the old mail system to the new mailer from Laravel, and then remove the code for our old mail sending system.

The following classes will need to be removed:

- `Mail`
- `MailTemplate`
- `SubmissionMailTemplate`
- and probably others...

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8252
OJS: https://github.com/pkp/ojs/pull/3541

**Comment by Vitaliy-1** [comment]
Finally, the migration tests went through.
@NateWr, can you take a look at these two PRs? If it looks ok, I port it to other applications

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8252
OJS: https://github.com/pkp/ojs/pull/3541
OPS: https://github.com/pkp/ops/pull/357
OMP: https://github.com/pkp/omp/pull/1208
