### ISSUE TITLE
Implement DMARC compliant features in new mail service

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7288]
Laravel's mail system was introduced in #7141. In order to be comply with DMARC requirements, we need to implement some of the code related to this from the old mail handler: https://github.com/pkp/pkp-lib/blob/main/classes/mail/Mail.inc.php#L630-L642

**Comment by Vitaliy-1** [comment]
PR to pkp-lib: https://github.com/pkp/pkp-lib/pull/8201
tests: https://github.com/pkp/ojs/pull/3506
