### ISSUE TITLE
Ensure the correct context is used in mailables sent in queued jobs

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7289]
In order to determine the correct `envelopeSender`, we need to know what context an email is related to. This context is passed down in the [MessageSendingContext](https://github.com/pkp/pkp-lib/blob/main/classes/observers/events/MessageSendingContext.inc.php) event.

After work on the queue (#6368) is completed, it will be possible to send jobs to the queue. We need to run some tests to ensure that if an event is fired, and the listener is sent to the queue, that any emails sent within the listener make use of the context of the original event and not the context when the job is completed. That's because a job will be completed with a different `Request` from when it was queued.

**Comment by Vitaliy-1** [comment]
Implement as part of: https://github.com/pkp/pkp-lib/issues/8204
