### ISSUE TITLE
Announcements fail to load

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#7290]
**Describe the bug**
When clicking on Announcements menu the following error occurs

Uncaught TypeError: Argument 1 passed to PKP\\announcement\\Collector::filterByContextIds() must be of the type array or null, int given, called in lib\\pkp\\pages\\announcement\\AnnouncementHandler.inc.php on line 67 and defined in lib\\pkp\\classes\\announcement\\Collector.inc.php:40

**To Reproduce**
1. Go on Announcements menu
2. See error

**Comment by defstat** [comment]
@NateWr @asmecher 

**PR**
[pkp-lib]: #7291

**Comment by NateWr** [comment]
Thanks @defstat! Can you add a test to `lib/pkp/cypress/tests/integration/Announcements.spec.js` that will catch this in the future? I think a new test between "Add an Announcement" and "Edit an Announcement" that looks for the announcement on the homepage and then follows it to see if the announcement loads would be perfect.

**Comment by NateWr** [comment]
You can run a single test by doing the following:

```
npx cypress open --config integrationFolder=lib/pkp/cypress/tests/integration
```

This will open a UI where you will see the announcements test, you can click it and run it.

**Comment by NateWr** [comment]
> looks for the announcement on the homepage and then follows it to see if the announcement loads

Woops, that wouldn't catch the error. I think you need to visit the page that lists all announcements.

**Comment by defstat** [comment]
@NateWr I have added the test.

**Comment by NateWr** [comment]
Thanks! I've merged that in without running the tests. :crossed_fingers:
