### ISSUE TITLE
Publication not published if new version created and is assigned to a new issue

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#7292]
**Describe the bug**
When an article is published in Issue A and a new version of the article is created and scheduled to Issue B, publishing Issue B will not make the new version of the article public. It is visible in Issue B TOC but the second version of the article remains unpublished.

**To Reproduce**
1. Publish a new article in Issue A and publish the issue
2. Create a new version of the article and assign it to Issue B
3. Publish Issue B and visit the issue in the frontend

**What application are you using?**
 OJS main branch, applies to all versions with the versioning feature

**Comment by ajnyga** [comment]
Just for OJS, tests running: https://github.com/pkp/ojs/pull/3181

@NateWr ping for review. A very simple fix, I just fetch submissions with two statuses and in the publications loop there was already a check for status_scheduled and issue_id

**Comment by ajnyga** [comment]
The issue item count problem I mentioned in Slack seems to have been fixed in the last couple of commits!

**Comment by ajnyga** [comment]
@NateWr added the comment and running tests again

**Comment by NateWr** [comment]
Merged to `main`. I think this is a rare use case, so I'm tempted not to backport it to `stable-3_3_0`. Any objections?

**Comment by asmecher** [comment]
No objections here, thanks!

**Comment by ajnyga** [comment]
no problem, I can do my own backport for our installation

**Comment by bozana** [comment]
It seems this issue is solved? Can I then close the issue?

**Comment by asmecher** [comment]
I think so, thanks!
