### ISSUE TITLE
Can't access API by apiKey because Repo::user()->getByApiKey() doesn't exist

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7294]
**Describe the bug**
When trying to access the REST API and use the `apiKey`, a fatal error is thrown because the request tries to call `Repo::user()->getByApiKey($apiToken)` but this method doesn't exist.

It exists on the user DAO, but looking at the method, it was probably intended to be put at the Repo level.

@asmecher just filing this quickly while I have time, but this is probably a quick fix. (We probably should have at least one test against the API using the `apiKey`.)

**What application are you using?**
`main`

**Comment by asmecher** [comment]
Thanks, I'll take a look at this. It'll be a quick fix.

**Comment by ewhanson** [comment]
Hey @asmecher , I also just noticed some additional odd behaviour with this. When saving user API settings, the `user_settings` table is no longer being updated. When attempting to save any other user settings, I receive this fatal error:

```
[Wed Sep 15 10:05:29.709223 2021] [php7:error] [pid 16965] [client 127.0.0.1:56206] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'setting_type' doesn't have a default value in /Users/erikhanson/www/ojs/crossref/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112
Stack trace:
#0 /Users/erikhanson/www/ojs/crossref/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(112): PDOStatement->execute(NULL)
#1 /Users/erikhanson/www/ojs/crossref/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#2 /Users/erikhanson/www/ojs/crossref/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('insert into `us...', Array)
#3 /Users/erikhanson/www/ojs/crossref/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#4 /Users/erikhanson/www/ojs/crossref/lib/pkp/ in /Users/erikhanson/www/ojs/crossref/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671, referer: http://localhost/ojs/crossref/index.php/tjo/user/profile
```

Not sure if this is a missing migration on my part or of it's related to this, but wanted to flag just in case.

**Comment by asmecher** [comment]
@ewhanson, I think your problem (`Field 'setting_type' doesn't have a default value`) is caused by an out-of-date database schema; the `user_settings` table shouldn't have that column anymore.

**Comment by ewhanson** [comment]
Perfect, thanks @asmecher!

**Comment by NateWr** [comment]
Fixed in https://github.com/pkp/pkp-lib/commit/0b4147cb94562c2caecf78d83b3e1ff4ebe9d7c1.

**Comment by asmecher** [comment]
Ah! I was actually working on a test for this in preparation for fixing the bug, but I see you beat me to it. I'll finish the test anyway as a bonus.
