### ISSUE TITLE
Add test that uses the API key

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7297]
Our integrated tests do not cover usage of the API key to access the REST API. The following tests should be added:

- Editor (dbarnes) can create an API key.
- Editor can use the API key to access the REST API when logged out.
- Author (ccorino) can create an API key.
- Author only sees their own submissions when they access the /submissions API endpoint.

**Comment by asmecher** [comment]
Implemented -- the editorial test in pkp-lib and the author test in each application. OMP has a different set of authors in the test dataset than OJS and OPS, so it wasn't possible to do everything in pkp-lib. (I think down the road we should standardize the test dataset across the apps a little more.)
