### ISSUE TITLE
Automatic DOI registration to DataCite

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#730]
Enable, similar to the CrossRef import/export plugin, the automatic DOI registration to DataCite i.e. using a cron job or Acron plugin.

**Comment by asmecher** [comment]
@beghelli, could you have a look? Thanks!

**Comment by ojsde** [comment]
@beghelli, what shall I do? :-\

**Comment by bozana** [comment]
@beghelli, what should I do? :-)

**Comment by bozana** [comment]
@beghlli, oh, I see, I have to change the frequency...

**Comment by bozana** [comment]
@beghelli, I hope I did it correctly this time?

**Comment by asmecher** [comment]
@beghelli, I'm not sure if this was completed; if so, please move back to OJS 2.4.7 and close.

**Comment by marchitelli** [comment]
Can you add the same feature for mEDRA registration? I think that could be useful
