### ISSUE TITLE
Assess 3.4.0 performance with large databases

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7304]
OJS 3.4.0 introduces a lot of SQL changes that should improve performance but need to be tested.

In particular, assess the performance with a large database and the following operations/tasks:
- Submission lists/filters
- **Reviewer selection**
- **User management**
- OAI Identify ("first record date")
- **Merge Users**
- 3.3.x to 3.4.x upgrade
- Large tables of contents (@diegoabadan may have test data)
  - https://github.com/pkp/ojs/commit/75d8dfd8faab8b65d2f818e4d196a057eee88dc5 for stable-3_3_0 should improve performance somewhat (to be included in `stable-3_3_0-15`)

**Comment by asmecher** [comment]
(@alexxxmendonca, I think this captures the pain points identified by the SciELO/OJS working group, but please let me know if there were others.)

**Comment by diegoabadan** [comment]
@asmecher , is better performance expected when there are many articles published in the table of contents?

Referring to https://github.com/pkp/pkp-lib/issues/6511

Is it desirable to run these tests now, from the git code?

**Comment by asmecher** [comment]
@diegoabadan, it's too early to start tests, but I've added that scenario to the list. I may ping you later for some test data; we don't have anything with that large a number of articles in a single TOC.

**Comment by diegoabadan** [comment]
Thanks Alec.

We have more than one case to test. :)

**Comment by mpbraendle** [comment]
Hi Alec - if that helps: we have a journal with about 6000 articles, but issues usually have 10-40 articles (so not a very large TOC).

**Comment by asmecher** [comment]
@mpbraendle, that's a fairly typical size and not likely to turn up bottlenecks in our environment. I think the delays you're experiencing will need to be resolved separately from this issue -- as posted here: https://forum.pkp.sfu.ca/t/submissions-again-loading-slowly/72688/8?u=asmecher

**Comment by ajnyga** [comment]
We are going to 3.3 soon and will try to do testing with 3.4 right after that. This would mean probably october(ish).

**Comment by asmecher** [comment]
We'll need to audit warnings encountered with a large upgrade database. The categories of warnings from the SciELO data set are...
- [ ] `Nulling non-existent genre_id ### in submission_files.`
- [ ] `Nulling non-existent source_submission_file_id ### in submission_files.`
- [ ] `Nulling non-existent uploader_user_id ### in submission_files.`
- [ ] `Removing orphaned controlled_vocab_entry_settings for missing controlled_vocab_entry_id ###`
- [ ] `Removing orphaned edit_decisions entries for missing submission_id ###`
- [ ] `Removing orphaned edit_decisions entry for missing editor_id ###`
- [ ] `Removing orphaned email_templates_settings for missing email_id ###`
- [ ] `Removing orphaned filters for missing filter_group ###`
- [ ] `Removing orphaned library_files for missing context_id ###`
- [ ] `Removing orphaned library_files for missing submission_id ###`
- [ ] `Removing orphaned note entry ID ### with nonexistent query ###`
- [ ] `Removing orphaned query_participants for missing user ID ###`
- [ ] `Removing orphaned review_assignments entry ID ### with submission_id ###`
- [ ] `Removing orphaned review_files for missing review_id ###`
- [ ] `Removing orphaned settings for missing library_file ###`
- [ ] `Removing orphaned settings for missing notification ID ###`
- [ ] `Removing orphaned settings for missing submission file ID ###`
- [ ] `Removing orphaned submission_comments entry for missing author_id ###`
- [ ] `Removing orphaned submission_comments entry for missing submission_id ###`
- [ ] `Removing orphaned submission_files entry ### with non-existent submission.`
- [ ] `Removing orphaned submission ID ### with nonexistent context ID ###.`
- [ ] `Removing orphaned user_interests for missing user_id ###`
- [ ] `Reset ### announcements with orphaned (non-null) announcement types to no announcement type.`

**Comment by asmecher** [comment]
These seem fine at a glance with a large data set. Closing for internal testing.
