### ISSUE TITLE
missing unregistered articles URL in crossref plugin settings 

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#731]
I solved it like this: https://github.com/bozana/ojs/commit/a701c6a60fe59bd84fe8005ce648e3cc16608f9a
If OK so, I can make a pull request...

**Comment by asmecher** [comment]
Please do, and could you translate the German string as well?

**Comment by bozana** [comment]
I can even translate all the languages containing this key :-) Because I know how to tell "<a href="{$unregisteredURL}">" in all languages :-)

**Comment by asmecher** [comment]
Typical European, knows how to speak every language... ;)

**Comment by bozana** [comment]
Hihihihi :-)

**Comment by asmecher** [comment]
Merged! Thanks, @bozana.
