### ISSUE TITLE
Update the PHP CS Fixer

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7313]
**Describe the problem you would like to solve**
The CS Fixer v2 isn't maintained anymore

**Describe the solution you'd like**
Migrate to the version 3

**Comment by NateWr** [comment]
Thanks, we'll probably want to time this when the team doesn't have many large PRs coming, because I imagine it will involve some additional formatting across the codebase.

**Comment by NateWr** [comment]
Ugh, I tried to do this today but in the process I somehow broke the pre-commit hooks. :sob: These are the changes that I think need to be made to get from 2.x to 3:

https://github.com/pkp/pkp-lib/pull/7319
https://github.com/pkp/ojs/pull/3188

But more work will need to be done to apply the updates (it does effect a lot of files) and make sure the pre-commit hooks work.

**Comment by NateWr** [comment]
Status is marked as under discussion, right? Has this been adopted for 8.2?

**Comment by jonasraoni** [comment]
Yep! It's not discussed/voted yet. I just think the "{$xxx}" is a better default :)

**Comment by NateWr** [comment]
It looks like this was updated in #7815.
