### ISSUE TITLE
Notify users by role offers an option to CC instance admin, should be journals' primary contact instead

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#7316]
**Describe the problem you would like to solve**
When notifying users by role, journal editors are offered an option to "Send a copy of this email to me at [instance admin email]"

In many cases, instance admin is not the journal manager/editor. Specifically in case of multi-journal instances having the admin email is not useful to individual journals, and can results in lots of unnecessary email notifications if checked.

![image](https://user-images.githubusercontent.com/45104797/134403505-01284e22-162f-4999-8584-0e158e324145.png)

OJS version: 3.3.0.8

**Describe the solution you'd like**
It would make sense for this email to either go to the individual journal's primary contact, or for the JM/JE to be able to enter the email at which they want to receive a copy.

**Who is asking for this feature?**
PKP|PS and multi-instance admins.

**Comment by NateWr** [comment]
This is a CC to the person sending the email. So if the journal manager sends the email, the option will be to CC themselves. Basically, whoever you are logged in as when sending the email.

**Comment by librariam** [comment]
Well I feel silly now :-) Thank you for explaining!
