### ISSUE TITLE
CSV user export includes roles from other journals

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#7317]
**Describe the bug**
Exporting users by role on a multi-journal instance produces a CSV with multiple hundreds of Role columns (e.g. a CSV produced from the OJS demo site had 400+ columns). It looks like it perhaps contains a Yes/No for a role in each journal on the instance...?

**To Reproduce**
1. Log in as a JM/JE in a journal on a multi-journal instance on OJS 3.3
2. Go to Statistics > Users > Export
3. Select all (or some) roles and export the CSV
4. Open the CSV and enjoy the horizontal scrolling journey

**What application are you using?**
 OJS 3.3.0.8

**Comment by asmecher** [comment]
We can't collapse each journal's role list into the same column, since roles are installed the same by default but can be customized per journal. So we can't guarantee that Journal A's "Reviewer" role will be the same as Journal B's (or that Journal B will even have one, for example).

**Comment by librariam** [comment]
This is meant to be an export for only one journal though. The JM who generates the report only wants to know which role the user holds in their journal.

**Comment by jonasraoni** [comment]
**PRs**

- `main`
  - `pkp-lib` https://github.com/pkp/pkp-lib/pull/7825
  - `ojs` https://github.com/pkp/ojs/pull/3358
- `stable-3_3_0`
  - `pkp-lib` https://github.com/pkp/pkp-lib/pull/7826
  - `ojs` https://github.com/pkp/ojs/pull/3359
