### ISSUE TITLE
DataCite DOI registration via OJS plugin screws up „first page“ and „last page“ metadata

### ISSUE THREAD

**Issue by heike-r** [pkp/pkp-lib#7326]
We noticed that, when a DOI we registered via the DataCite plugin in OJS 3.3.0.6, is used for metadata import in CITAVI, that the metadata fields “first Page” and “last page” contain information about the issue, but not about the page numbers of the respective article. A look into DataCite Fabrica confirmed that these fields are filled with wrong data. DataCite xml schema 4.4 and the JSON schema do have the fields “first Page” and “last page”, but I assume that OJS does not deliver data for these fields. The page numbers we enter in OJS on article level end up in the “sizes” field.

It is not clear to me if DataCite screws up by just putting random metadata into these fields because they are not filled or if the OJS plugin delivers wrong data for these fields. A problem might also be that OJS (in our case 3.3.0.6) does not have two separate fields for “first page” and “last page”. Does this have to be changed to correct the problem?

AFAIK the CrossRef scheme also has “first page” and “last page” metadata. Can someone who registers DOIs via CrossRef plugin check if they have the same problem with their metadata?

**Comment by asmecher** [comment]
@heike-r, the first page and last page that OJS provides to CrossRef are parsed (when OJS can figure out their formatting) from the single "pages" field in the submission metadata. The parsing is a little convoluted:

https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/publication/PKPPublication.inc.php#L277

Are your page ranges something that this parser will be able to understand?

**Comment by NateWr** [comment]
Closing for now. Will reopen when we get more details.
