### ISSUE TITLE
CSS file mimetype not correctly recognized

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7344]
**Describe the bug**
A CSS file uploaded as a dependent file is assigned the `text/plain` mimetype instead of the `text/css` mimetype. This prevents it from being loaded correctly into a HTML galley.

**To Reproduce**
1. Create a galley and upload a HTML file.
2. Upload the file attached below as a dependent stylesheet
3. View the mimetype in the `files` table in the database.

**What application are you using?**
 3.3.0-7

**Additional information**
[Report](https://github.com/pkp/pkp-lib/issues/6663#issuecomment-927967392) from @jnugent:

> Hi everyone, this bug may have reappeared.  We have a client on 3.3.0.7, upgraded from 3.2, and now uploaded CSS files for HTML galleys are getting a "text/plain" MIME type stored in the files table:
> 
> ![Screenshot at 2021-09-27 12-02-17](https://user-images.githubusercontent.com/218719/134934558-45fa1e45-e462-474e-9ce4-c7f23b24b775.png)
> 
> This file was correctly uploading as text/css in 3.2 and has not changed. Further, after doing some debugging it doesn't look like any of the ambiguity code for MIME type detection added in PKPString is being used when files are uploading.  My debug statements in that class are not being logged.
>
> I'm attaching a zip file containing the style sheet that used to work but now does not.  I've confirmed this in my own 3.3.0.7 test installation. It's easy to reproduce, just create a new submission and upload this as a submission file and look at the files table.
> 
> I'll leave the reopening to others if it is deemed necessary.
> 
> [stylesheet.zip](https://github.com/Vitaliy-1/pkp-lib/files/7237357/stylesheet.zip)

**Comment by NateWr** [comment]
@Vitaliy-1 I've assigned you just because you might remember the work that went into the last fix. But I know you've got enough to do at the moment. If it takes more than an hour of tinkering to figure out, let me know and I can unassign you.

**Comment by Vitaliy-1** [comment]
The main branch has a fallback extension-based method for determining a MIME type when a file is added, which isn't implemented for the stable branch.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib stable 3.3.0: https://github.com/pkp/pkp-lib/pull/7347
OJS tests only: https://github.com/pkp/ojs/pull/3195

**Comment by NateWr** [comment]
@jnugent it looks like part of the fix in the `main` branch never made it into `stable-3_3_0`. Can you test the PR above to see if it resolves the issue for you?

**Comment by jnugent** [comment]
@NateWr  confirming fixed!

![Screenshot at 2021-09-28 11-27-44](https://user-images.githubusercontent.com/218719/135107263-cebe415d-f684-447e-a459-fdd4c0be9f76.png)

**Comment by NateWr** [comment]
Thanks to both of you!

**Comment by Alex2394** [comment]
Hello everyone. It is possible that this bug is present again for version 3.3.0.13. Uploaded CSS files to HTML galleys, MIME type getting value of: "text/x-asm". Results from files table

![Screenshot 2023-09-12 124906](https://github.com/pkp/pkp-lib/assets/6422793/27b50673-e279-45d8-a3fb-dc05fa831608)

**Comment by asmecher** [comment]
@Alex2394, with apologies for the late reply, can you share the contents of the CSS file? This will be relevant to how it's being detected as `text/x-asm`.

**Comment by jonasraoni** [comment]
I was testing this yesterday, and I can confirm the code is analyzing the content to infer its mime-type.

One problem is that edge cases might fail, for example, I've uploaded a `test.html` with the content below (which is a valid HTML markup), and it was detected as `text/plain` instead of `text/html`.
```html
Test <img src="test.jpg">
```

**Comment by asmecher** [comment]
@jonasraoni, yes, we infer the type from its content using the `finfo` tools, but we already have supports for specific overrides to the detected file types for cases where `finfo` gets it wrong. It may just be necessary to add some overrides to `lib/pkp/classes/core/PKPString.php` in the `getAmbiguousExtensionsMap` function.
