### ISSUE TITLE
[OJS 3.3.0.3] OAI-PMH Error: “No incremental harvesting (day granularity) of ListRecords”

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#7348]
I'm getting this error in all my journals OAI interface when testing using: http://oval.base-search.net/

![image](https://user-images.githubusercontent.com/18707781/135101514-a2a75a68-db15-49ca-b231-5be2d3da92a2.png)

I'm not sure when this started, but we now got the demand from our editors and opened a forum post, but had no luck so far (https://forum.pkp.sfu.ca/t/oai-pmh-error-no-incremental-harvesting-day-granularity-of-listrecords/69885)

I looked everywhere for what could be causing this error, but since this is happening in all journals I'm assuming this is a bug in the OAI interface or maybe some incompatibility with my server settings.

**Comment by asmecher** [comment]
@luizbgomide, I would suggest updating to the latest 3.3.0-x release and testing there; it includes some OAI-PMH related fixes such as https://github.com/pkp/pkp-lib/issues/7214.

**Comment by luizbgomide** [comment]
BTW, @asmecher when I 3.4 arriving?

**Comment by luizbgomide** [comment]
@asmecher, just updated to the latest 3.3.0-8 and the error persists. This (day and full granularity) is affecting all our journals, so it is probably something site wide and not journal specific. Any ideas?

**Comment by asmecher** [comment]
@luizbgomide, I think you're encountering this issue: https://github.com/pkp/pkp-lib/issues/6807

**Comment by luizbgomide** [comment]
I've found that issue (and this is what made me notice the "now" issue), but what bugs me is that I ran the upgrade script from 3.3.0-8 but my DB didn't change...

> [pre-install]
> [load: upgrade.xml]
> [version: 3.3.0.8]
> [code: Installer Installer::checkPhpVersion]
> [code: Installer Installer::installDefaultNavigationMenus]
> WARNING: The NavigationMenu (ContextId: 68, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 68, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 56, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 56, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 59, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 59, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 22, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 22, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 67, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 67, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 18, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 18, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 19, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 19, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 15, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 15, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 24, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 24, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 23, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 23, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 63, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 63, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 21, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 21, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 61, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 61, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 16, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 16, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 65, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 65, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 20, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 20, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 62, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 62, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 60, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 60, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 66, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 66, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
> WARNING: The NavigationMenu (ContextId: 0, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
> [code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
> WARNING: The StaticPage "Fontes de Indexação" uses a path (fontesindexacao) that conflicts with an existing Custom Navigation Menu Item path. Skipping this StaticPage.
> [code: Installer Installer::addPluginVersions]
> [post-install]
> Successfully upgraded to version 3.3.0.8

**Comment by asmecher** [comment]
@luizbgomide, that output says you're already on 3.3.0-8, so the relevant upgrade step will not be executed. The best solution is to manually run the two database queries coded here:

https://github.com/pkp/ojs/commit/ad7c3564e58a6edfe1b9907bda4e7a02d8693dca

(Please take a backup before manually running DB updates.)

**Comment by luizbgomide** [comment]
The same happened when I updated from 3.3.0.3 to the newest, I just reapplied without any different result.

I ran the queries manually and it worked.
