### ISSUE TITLE
OMP does not display version

### ISSUE THREAD

**Issue by diegoabadan** [pkp/pkp-lib#7349]
This affects at least OMP 3.3.0.8

It can be seen in the instances maintained by PKP at:

https://demo.publicknowledgeproject.org/omp3/demo/index.php/aup-demo/about/aboutThisPublishingSystem

https://demo.publicknowledgeproject.org/omp3/testdrive/index.php/td-press/about/aboutThisPublishingSystem

**Comment by asmecher** [comment]
This should already be fixed for release in OMP 3.4.0 by https://github.com/pkp/omp/commit/2af8043007545590c46d5835573569c17eed0253. I'll cherry-pick this back to `stable-3_3_0`, though.
