### ISSUE TITLE
Allow for labels be added to article versions 

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#7354]
Requested by Journal Manager using OJS 3.3.

Instead of using only a default version number and date, the journal is also allowed to add an additional name in front of the date for each new version. So, version 1 could be “Accepted Manuscript, 2021-03-09 (1)” and version 2 to be “Version of Record, 2021-09-15 (2)”.

![image](https://user-images.githubusercontent.com/50342731/135319647-663b6cf7-ae36-4d42-9554-804fa2753dd4.png)

There are currently other publishing platforms that do have this labelling mechanism.

![image](https://user-images.githubusercontent.com/50342731/135320062-292dfc09-6193-485c-83d0-f3314ae1be24.png)

![image](https://user-images.githubusercontent.com/50342731/135320007-7892cc19-0432-4b8c-be12-f3675b89451f.png)

**Comment by asmecher** [comment]
@NateWr, I think you recently responded to a forum post or issue requesting named versions -- if that rings a bell, do you have a link handy?

**Comment by NateWr** [comment]
This overlaps some with #4860, where we discuss version types and summaries. The more recent discussion was #7280, where Scielo is asking for "version notes".

The main hiccup to date is that downstream providers do not really distinguish between major/minor revisions. And the distinction between Accepted Manuscript and Version of Record is not handled in OJS at all (Antti-Jussi has a Forthcoming plugin that acts as a workaround). So while a general version note/label/summary would be widely useful, I think the specific use case in this issue probably requires more substantial work with downstream metadata.

**Comment by nils-stefan-weiher** [comment]
A colleague of mine also has been contacted by a journals manager asking about version notes. But mainly for the reader audience to inform them of the changes to the articles.

It seems they are hesitating to use the versioning because of communicating to the reader "there was something wrong with the previous versions so there had to be a new revision". But sometimes the new published version just includes an additional galley which was released at a later date or additional meta data.

**Comment by NateWr** [comment]
Hi @nils-stefan-weiher, we've _just_ adopted a new policy where we are asking feature requests to be made on our forum. (It's brand new, we [announced it yesterday](https://pkp.sfu.ca/2022/07/20/improving-how-we-collect-community-feedback/)).

Would you be willing to compile a concise description of this request and post it with the screenshots above in our [feature requests forum](https://forum.pkp.sfu.ca/c/questions/feature-requests/8)? I can then close this issue and more of our community will be able to vote on this proposal.

**Comment by NateWr** [comment]
I've converted this to a [feature request](https://forum.pkp.sfu.ca/t/support-different-version-types-such-accepted-manuscript-and-version-of-record/74211) on the forum. Please add any future comments there.
