### ISSUE TITLE
New email templates notifying authors that their submission is being sent to review

### ISSUE THREAD

**Issue by kshuttle** [pkp/pkp-lib#7356]
Currently authors are not notified when their submission is sent to review (#4059)

I suggest three new email templates be created to address this, with alternative wording depending on the type of peer review that will be undertaken. These can be incorporated into the workflow changes addressed in #7265  

**Template 1: Double-anonymous review**

This template replaces the old one: EDITOR_DECISION_SEND_TO_EXTERNAL

Suggested title for new template: EDITOR_DECISION_SEND_TO_DOUBLE_ANONYMOUS_REVIEW

Sent by: Editor
Received by: Author
Should the sender be able to preview and customize this email? Yes
Should the recipient be able to opt out of receiving this email? No

**The following has been drafted for this new email template:**

**Email subject**
Your submission was sent for review

**Email body**
Dear {$authorName},

I am pleased to inform you that an editor has reviewed your submission, {$submissionTitle}, and has decided to send it for peer review. An editor will identify qualified reviewers who will provide feedback on your submission. 

This journal conducts double-anonymous peer review. The reviewers will not see any identifying information about you or your co-authors. Similarly, you will not know who reviewed your submission, and you will not hear from the reviewers directly. All reviewer comments will be sent to the editor, who will share the reviewers’ feedback with you and correspond with you about the next steps.

Please note that sending the submission to peer review does not guarantee that it will be published. We will consider the reviewers’ recommendations before deciding to accept the submission for publication. You may be asked to make revisions and respond to the reviewers’ comments before a final decision is made.

If you have any questions, please contact me from your submission dashboard.

{$signature}

**Email description**
This email from the Editor or Section Editor to an Author notifies them that their submission is being sent to the peer review stage, when the journal is configured for double anonymous peer review.

The following work needs to be done:

- [ ] Add this to [OJS/OMP].

**Template 2: Reviewer-anonymous review**

Suggested title for new template: EDITOR_DECISION_SEND_TO_REVIEWER_ANONYMOUS_REVIEW

Sent by: Editor
Received by: Author
Should the sender be able to preview and customize this email? Yes
Should the recipient be able to opt out of receiving this email? No

**The following has been drafted for this new email template:**

**Email subject**
Your submission was sent for review

**Email body**
Dear {$authorName},

I am pleased to inform you that an editor has reviewed your submission, {$submissionTitle}, and has decided to send it for peer review. An editor will identify qualified reviewers who will provide feedback on your submission. 

This journal conducts “reviewer anonymous” peer review. Your name, and those of your coauthors, will be visible to the reviewers; however, the reviewers’ identities will remain anonymous. All reviewer comments will be sent to the editor, who will share the reviewers’ feedback with you and correspond with you about the next steps.

Please note that sending the submission to peer review does not guarantee that it will be published. We will consider the reviewers’ recommendations before deciding to accept the submission for publication. You may be asked to make revisions and respond to the reviewers’ comments before a final decision is made.

If you have any questions, please contact me from your submission dashboard.

{$signature}

**Email description**

This email from the Editor or Section Editor to an Author notifies them that their submission is being sent to the peer review stage, when the journal is configured for reviewer-anonymous peer review.

The following work needs to be done:

- [ ] Add this to [OJS/OMP].

**Template 3: Open review**

Suggested title for new template: EDITOR_DECISION_SEND_TO_OPEN_REVIEW

Sent by: Editor
Received by: Author
Should the sender be able to preview and customize this email? Yes
Should the recipient be able to opt out of receiving this email? No

**The following has been drafted for this new email template:**

**Email subject**
Your submission was sent for review

**Email body**
Dear {$authorName},

I am pleased to inform you that an editor has reviewed your submission, {$submissionTitle}" and has decided to send it for peer review. An editor will identify qualified reviewers who will provide feedback on your submission.

This journal conducts open peer review. The reviewers will see your name and affiliation, as well as the names and affiliations of your co-authors. Similarly, you will see the names and affiliations of the reviewers. You will hear from us with feedback from the reviewers and information about the next steps. 

Please note that sending the submission to peer review does not guarantee that it will be published. We will consider the reviewers’ recommendations before deciding to accept the submission for publication. You may be asked to make revisions and  respond to the reviewers comments before a final decision is made.

If you have any questions, please contact me from your submission dashboard.

{$signature}

**Email description**

This email from the Editor or Section Editor to an Author notifies them that their submission is being sent to the peer review stage, when the journal is configured for open peer review.

The following work needs to be done:

- [ ] Add this to [OJS/OMP].

**Comment by NateWr** [comment]
Thanks @kshuttle. I'm doing work now that will make it easy to get this in for 3.4. :tada: 

I'd like to use present tense in the subject, because at the time the email is sent the editor won't have assigned reviewers and may not do so right away. So it's like "your submission _is going_ to review" instead of _was sent_ for review. A minor distinction.

Rather than have 3 separate email templates, I'd like to see us use one email template that changes depending on what the journal has selected for their default review type. We would use a template variable, `{$reviewTypeDescription}`, to inject the different description. So the template could be like this:

> Key: `EDITOR_DECISION_SEND_TO_REVIEW`
> Subject: You submission is being sent for peer review
> Body:
>
> Dear {$recipientName},
> 
> I am pleased to inform you that an editor has reviewed your submission, "{$submissionTitle}" and has decided to send it for peer review. An editor will identify qualified reviewers who will provide feedback on your submission.
> 
> {$reviewTypeDescription} You will hear from us with feedback from the reviewers and information about the next steps.
> 
> Please note that sending the submission to peer review does not guarantee that it will be published. We will consider the reviewers’ recommendations before deciding to accept the submission for publication. You may be asked to make revisions and respond to the reviewers comments before a final decision is made.
> 
> If you have any questions, please contact me from your submission dashboard.
> 
> {$signature}

Then `{$reviewTypeDescription}` will be replaced with the appropriate description.

Double Anonymous:

> This journal conducts double-anonymous peer review. The reviewers will not see any identifying information about you or your co-authors. Similarly, you will not know who reviewed your submission, and you will not hear from the reviewers directly. 

Anonymous:

> This journal conducts “reviewer anonymous” peer review. Your name, and those of your coauthors, will be visible to the reviewers; however, the reviewers’ identities will remain anonymous.

Open:

> This journal conducts open peer review. The reviewers will see your name and affiliation, as well as the names and affiliations of your co-authors. Similarly, you will see the names and affiliations of the reviewers.

**Comment by kshuttle** [comment]
This all looks great, Nate! Thank you.

**Comment by fgnievinski** [comment]
a little embarrassed to admit, but journal editors sometimes (often?) are slower than authors would like to think. so I'm unenthusiastic about these new email templates, as they may cause more grief than good. maybe disable by default?
