### ISSUE TITLE
An embedded link in Google scholar directing to a false address

### ISSUE THREAD

**Issue by umithcl** [pkp/pkp-lib#7359]
Hellow,

We were using OJS's 3.2.1.1 version. After publishing our current issue, we realized that all papers in the current issue only were directed to the wrong address via google scholar. Original source( content provider) is SSBFNET but it leads to a different/wrong destination (jhvzbatt.id).

I checked the installed Google Scholar Indexing plugin on OJS. There is no problem. There is no problem on our website also.

How do you help me on solving this problem?

Wrong link on google scholar

<h3 class="gs_rt" ontouchstart="gs_evt_dsp(event)"><a id="2Gumn3Oa6MUJ" href="http://jhvzbatt.id/ojs/index.php/ijrbs/article/view/1327" data-clk="hl=tr&amp;sa=T&amp;ct=res&amp;cd=2&amp;d=14260818041459076056&amp;ei=krlaYdygFIqAmwGVo53QCQ" data-clk-atid="2Gumn3Oa6MUJ">Investigating the interplay between <b>social </b>presence, motivation, and knowledge sharing behaviour in virtual learning environment</a></h3>

Correct one
<h3 class="gs_rt" ontouchstart="gs_evt_dsp(event)"><a id="2Gumn3Oa6MUJ" href="http://ssbfnet.com/ojs/index.php/ijrbs/article/view/1327" data-clk="hl=tr&amp;sa=T&amp;ct=res&amp;cd=2&amp;d=14260818041459076056&amp;ei=krlaYdygFIqAmwGVo53QCQ" data-clk-atid="2Gumn3Oa6MUJ">Investigating the interplay between <b>social </b>presence, motivation, and knowledge sharing behaviour in virtual learning environment</a></h3>

Thanks in advance

Umit Hacioglu

Managing Editor of IJRBS at
www.ssbfnet.com/ojs

**Comment by NateWr** [comment]
Please post requests for help in our [community support forum](https://forum.pkp.sfu.ca/).
