### ISSUE TITLE
[Feature Request]Change encryption on upgrade to OJS3

### ISSUE THREAD

**Issue by samueloph** [pkp/pkp-lib#736]
Hi all,

In OJSs installations prior to the version 3, the default password encryption schema chosen was MD5. Every sysadmin should have the responsibility to enforce the SHA1 option, but we all know a lot of people just went with the default MD5 one.

I saw a few times Alec saying that the devteam is working hard on OJS3 to make sure the transition go as smooth as possible to everyone. BTW congrats on the new beta, it looks amazing!

What I'm requesting is that the upgrade process have an option to convert the old MD5 schema to use the new SHA1 one, this will make possible to a lot of sysadmins to upgrade their OJS security without much trouble.

Obviously one can do it manually, but there ins't documentation of such thing and neither someone at the forum saying they did it. I honestly believe the best approach would be the team making the transition (MD5 to SHA1) together with the OJS transition (2.x to 3.x).

Now, about the best technique to do this, is your decision, I would suggest that every passwords gets resetted and users receive an email asking to reset their password. This will guarantee that OJS will not be left with old MD5 hashes from inactives users, and even if somebody tries to login with their old password, they will fail to and have to reset their passwords.

I know that this means more responsibility to you, but thats what this feature request is. Maybe it won't be hard to do.

I'm gonna go further and also suggest that, if this feature request gets accepted, it becomes the default one, thus making sure all OJS3 installations are SHA1 by default (the fresh install of OJS3 already is).

A couple readings on this:
http://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=13352

http://arstechnica.com/security/2015/09/once-seen-as-bulletproof-11-million-ashley-madison-passwords-already-cracked/

**Comment by ctgraham** [comment]
+1, see also: https://github.com/pkp/ojs/pull/584

**Comment by asmecher** [comment]
Agreed, @samueloph. I'll close this issue in favour of the one Clinton referenced (https://github.com/pkp/pkp-lib/issues/695) -- could you take a look at that issue (and the pull request) and see if it's satisfactory for you?

**Comment by ctgraham** [comment]
Aside from https://github.com/pkp/pkp-lib/issues/695, this issue should also affect this config.inc.php option:
https://github.com/pkp/ojs/blob/master/config.TEMPLATE.inc.php#L251

Remove that setting from 3.x maybe?

**Comment by samueloph** [comment]
Yeah, in my opinion it should, but this got more complicated since there's somebody already working on the encryption schema.

I'm gonna comment in their PR to see If we can get into an agreement.
