### ISSUE TITLE
OMP Sitemap produces 404 not found pages

### ISSUE THREAD

**Issue by diegoabadan** [pkp/pkp-lib#7360]
Problem reported on the PKP forum at:
https://forum.pkp.sfu.ca/t/omp-sitemap-produces-404-not-found-pages/67210

We had the same problem with OMP 3.3.0-8.

**Comment by NateWr** [comment]
**Describe the bug**
The sitemap produced by OMP includes URLs that lead to 404 errors.

**To Reproduce**
Steps to reproduce the behavior:
1. Publish at least one book.
2. View the sitemap at `<journal-url>/sitemap`
3. Look for entries like `http://localhost:8000/publicknowledge/catalog/view/15`
4. Follow the URL to get a 404

**What application are you using?**
OMP 3.3.0-8

**Additional information**
From the forum:

> By looking the code, I could fix the 404 error by replacing view by book. But I have no idea if this is a correct fix, or it will screw things up any more.
> OMP Root–> Pages → sitemap → SitemapHandler.inc.php Line 36;
> `$root->appendChild($this->_createUrlTree($doc, $request->url($press->getPath(), 'catalog', 'view', array($submission->getBestId()))));`

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/omp/compare/stable-3_3_0...NateWr:i7360_sitemap?expand=1

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and applied to `main`.
