### ISSUE TITLE
[OJS 3.3.0.3] Reviewer missing when searching for her full name

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#7368]
When searching for the full name:
![image](https://user-images.githubusercontent.com/18707781/136199588-9ccfcfc7-06ab-448c-b8ca-397c8f80c9e4.png)

Nothing is found, but when searching by parts of the name it works just fine:
![image](https://user-images.githubusercontent.com/18707781/136199720-5b263606-9554-40d2-a706-a6808303b031.png)

What is odd is that similar name is found when using a similar search:
![image](https://user-images.githubusercontent.com/18707781/136199906-94a0e426-756c-4d4f-bb11-b943c4ac98b8.png)

Looking at the metadata from the two reviewers I noticed that they filled name and surname differently:
![image](https://user-images.githubusercontent.com/18707781/136200132-650b08a8-8a86-4665-b1fd-afebce5aa62a.png)

Considering the rest of their information (e-mail and username) I think that the system is ignoring the first name in combination with the surname.

**Comment by NateWr** [comment]
Please provide reproduction steps when reporting a bug. These steps should cover how to reproduce the bug in a clean database or, if that's not available, in a "fresh case". For example, with this bug, a "fresh case" might involve creating a new user under similar conditions and reproducing the bug with that user.

I tried to reproduce this and failed with the following steps:

1. Edit existing reviewer's given name to `Diana Luz Pessoa de` and family name to `Barros`.
2. Search for Diana Luz Pessoa de Barros in a reviewer selection list.

![reviewer-search](https://user-images.githubusercontent.com/2306629/136375128-2ecbba09-97a8-4576-b4b2-b84c85bb92d1.png)

![reviewers](https://user-images.githubusercontent.com/2306629/136375137-22d296df-57e9-454f-bdea-cea2b811eacc.png)

**Comment by NateWr** [comment]
Can you reproduce this problem on 3.3.0-8? You should be able to do set up a test instance and import your database to test against the latest release.

**Comment by luizbgomide** [comment]
BTW, I'm on MySQL 8.0.25.
