### ISSUE TITLE
Other languages required when they shouldn't be

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#7369]
**Describe the bug**
When clicking to advance on a new submission while the Title or Abstract field is selected, OJS says that the other language fields must be filled, when clicking away and the title (or abstract) popup closes the user can continue normally.

**To Reproduce**
**Steps to reproduce the behavior:**
1- Create a new submission in a journal with more than one language
2- Fill just the first language in the popup fields
3- Click Save and Continue
4- It will say that Required fields are missing (INCORRECLY).
5- Click away to close the popup
6- Click again on Save and Continue
7- I will allow you to continue as it should.

**What application are you using?**
OJS 3.3.0.3 (it is in the title)

**Additional information**
> When clicking to advance on a new submission while the Title or Abstract field is selected, OJS says that the other language fields must be filled, when clicking away and the title (or abstract) popup closes the user can continue normally.
> 
> ![image](https://user-images.githubusercontent.com/18707781/136201201-14c40448-eda4-46ae-a631-041067ba8af4.png)
> 
> This is confusing our users and some of them are complaining that they cannot complete the submission without every language being filled.

**Comment by luizbgomide** [comment]
Ah, forgot to mention, this happens in all our journals (all of them accept submissions at least in Portuguese and English).

**Comment by asmecher** [comment]
@luizbgomide, sorry, one more question -- what is the site's primary language? (Available in Site Settings when logged in as Administrator.)

**Comment by luizbgomide** [comment]
Here is one new journal I just created and posted above:
![image](https://user-images.githubusercontent.com/18707781/137305654-b0208cc0-373d-42ca-a72b-946105bbc4be.png)

The second query got no results, those are the distinct `setting_name` I have in the `site_settings` table:
![image](https://user-images.githubusercontent.com/18707781/137306085-54bb097a-f454-44ba-99b5-99102efa720f.png)

**Comment by luizbgomide** [comment]
@asmecher probably related, but the steps taken are different. A fix for one would probably fix both.

In #4818 it is just showing the message but if you tab enough you would get out of the input panel the validation error would go away and you will be able to click the Ok/Save/Continue/Next button. My issue arised from author clicking Continue directly and getting stuck thinking they had to fill all of the languages.

**Comment by xawery79** [comment]
I have a question when can we expect this fix to be published. In journals that have several languages enabled having to complete file descriptions in all languages is extremely cumbersome.

**Comment by fgnievinski** [comment]
On the other hand, the opposite is also frequently asked for in the discussion forum: 
submission metadata in secondary languages may be mandatory for a given journal.
basically, a new column for "mandatory metadata" in the journal languages table.

How to make title and abstract in second language required?
https://forum.pkp.sfu.ca/t/how-to-make-title-and-abstract-in-second-language-required/50185

How to make title and abstract required in all languages during submission
https://forum.pkp.sfu.ca/t/how-to-make-title-and-abstract-required-in-all-languages-during-submission/68405

Should this be filed in a separate issue?

**Comment by touhidurabir** [comment]
@asmecher PRs to review 
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8440
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3626 [TEST ONLY]

**Comment by touhidurabir** [comment]
@NateWr will do but does it need to be ported to `main` ? I thought `main` has different implementation with your latest changes of submission process that I think already got merged in . Just curious .

**Comment by NateWr** [comment]
Only the submission wizard has been changed in `main`. So we still need these changes as they effect submission file uploads during the workflow and in galleys.

**Comment by NateWr** [comment]
And actually I think the QuickSubmit plugin still uses the old submission wizard so the submission form itself might still be in the codebase.

**Comment by asmecher** [comment]
As elsewhere -- my apologies for the broken `main` tests; that should be fixed now!

**Comment by touhidurabir** [comment]
@NateWr all tests have passed, should be good to merge .

**Comment by NateWr** [comment]
All merged to `stable-3_3_0` and `main`. Thanks @touhidurabir!
