### ISSUE TITLE
"Patch" upgrading should not be a recommended path

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#737]
Patch based upgrading is deeply flawed:
* it is technically complicated, yet is presented as the "first" option in our documentation
* it is unable to address binary files
* it misrepresents the relationship between the upstream codebase and local modifications
 * upstream should always be represented as the authority
 * generally valuable local modifications should be encouraged to be pushed upstream
 * install-specific local modifications should be applied on top of the upstream codebase
 * *the patch-based upgrade path inverts this relationship*

Our first upgrade suggestion should be the "Full Package".  If local modifications are involved, we should *recommend* version control, such as Git.  If version control is unwanted, we can offer patches as the *last resort* for upgrading.

**Comment by asmecher** [comment]
Thanks, @ctgraham, this is an obvious improvement now that you've pointed it out.

**Comment by asmecher** [comment]
Ported around to various branches (and OMP).

**Comment by ctgraham** [comment]
3.x would be a great opportunity to remove the patch upgrade "option" entirely.  If we really wanted to keep some form of it, perhaps replace it with brief, generic instructions on how to run a diff of the existing install against a clean codebase and then apply that diff against the new version.

**Comment by asmecher** [comment]
@ctgraham, agreed again. We're currently carting around 4GB of patch files between various versions, and each new release generates another >300M of them. Will remove from the master branch documentation; IMO this stuff has been supplanted culturally by git/github.
