### ISSUE TITLE
No paging on OMP search results

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7372]
**Describe the bug**
As it stands right now, the search feature in OMP does not do any paging of search results, so if there are more than `SUBMISSION_SEARCH_DEFAULT_RESULT_LIMIT` (as defined in `lib/pkp/classes/search/SubmissionSearch`), all you ever get are the first 20 results.

**To Reproduce**
See https://www.thecommonwealth-ilibrary.org/index.php/comsec/search/search?query=gender

**What application are you using?**
 OMP 3.3.0.3

**Comment by asmecher** [comment]
Thanks, @jnugent! Merged and back-ported to `stable-3_3_0`.

**Comment by dagosalas** [comment]
Tested in 3.3.0-8, works OK. No errors.
