### ISSUE TITLE
Fix submission filtering by issue and section ID

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#7383]
**Describe the bug**
The articles can appear double in the issue TOC. The filtering by issue and section ID in getQueryBuilder() in classes/submission/Collector considers all submission publications, but does not check for distinct ones. 

**To Reproduce**
Publish several publications of a submission and check the TOC

**What application are you using?**
 OJS main

**Additional information**
s. https://github.com/pkp/ojs/commit/9fcf84215758ec5d22128d2cb40574bb3a4b4378#commitcomment-58010754

**Comment by bozana** [comment]
@asmecher, it seems the following change solves this issue: https://github.com/pkp/ojs/commit/f7c4b7f13bc502762e369300148e4578090dc725#diff-0d5648e42f792f4e2708196d4f19a19513723681d7ff9db588194ae8099abdc3, correct?

**Comment by NateWr** [comment]
Seems like this was fixed. I was unable to reproduce it in `main`.
