### ISSUE TITLE
ViewReport: provide PDF, HTML, Other stats instead of stats for each artilce galley

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#7384]
One expects the counts in ViewReport to be the same with the counts in the GUI. This is not the case, because the ViewReport provides counts for each article galley, but it considers only the current publication. The statistics in the GUI however consider all submission files, for all publications and classify them for the different file types i.e. PDF, HTML and Other.
Thus, change the ViewReport to export/provide the same i.e. counts for PDF, HTML and Other file types of a submission (additionally to the abstract views).

**Comment by NateWr** [comment]
Could (or should) this be implemented as part of https://github.com/pkp/pkp-lib/issues/7318? I imagine that it could maybe just be a download link from the statistics table itself... Or does the ViewReport provide something more than the table?

**Comment by bozana** [comment]
I will close this issue, because we can then remove the ViewReport plugin once the CSV reporting in #7318 is implemented.
