### ISSUE TITLE
Allow new COUNTER Releases and Reports

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#739]
Refactor reports/counter plugin to allow recent updates to COUNTER releases and reports.  New implementation should support external calls to COUNTER, such as from SUSHI-Lite.

**Comment by asmecher** [comment]
@beghelli, could you have a look at this?

**Comment by beghelli** [comment]
Clinton, finished reviewing it. I left some questions that will help me to get a final review, feel free to answer them here or contact me directly. Thanks!

**Comment by ctgraham** [comment]
I think this is back to you, @beghelli .

**Comment by ctgraham** [comment]
@beghelli, I removed the unused method for multiple releases that you pointed out, and I changed this plugin to no longer be a site-level plugin.  With the new structure, it can be useful to Journal Managers as well.

**Comment by beghelli** [comment]
Great. Is there a pull request to look at? Thanks.

**Comment by ctgraham** [comment]
Same PR as above: https://github.com/pkp/ojs/pull/535
