### ISSUE TITLE
Ensure Site Administrators have "global" access within journals

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7392]
**Describe the problem you would like to solve**
A user with the admin role is not able to take all actions in a journal unless they are enrolled as a Journal Manager. In multi-journal instances, this means they must be enrolled in every journal as a Journal Manager.

This also leads to sharing of site administrator accounts, since that means only one account must be kept enrolled as Manager in each journal.

**Describe the solution you'd like**
Site Administrators should be treated as Journal Managers within all journals and when taking any action.

**Who is asking for this feature?**
Scielo, PKP|PS, and other hosts who manage many journals in one installation.

**Additional information**
(There has been previous work on this, so it may just need verification.)

**Comment by NateWr** [comment]
This may be a related issue: https://github.com/pkp/pkp-lib/issues/1516 -- Allow more than one administrator

**Comment by asmecher** [comment]
PRs:
- pkp-lib: https://github.com/pkp/pkp-lib/pull/7906
- ojs: https://github.com/pkp/ojs/pull/3390
- ops: (needs porting)
- omp: (needs porting)

The approach here was just to list out, brute force, the site administrator role alongside the journal manager. I considered hacking the role system to make an exception for the site administrator, but judged that to have more technical debt if e.g. we move to another role system.

@NateWr, with apologies -- I know you're quite busy, but you have been active on this issue -- could you review this for general approach before I port to OMP and OPS?

**Comment by NateWr** [comment]
:+1:  reviewed.

**Comment by asmecher** [comment]
Thanks, @NateWr! I grepped for more changes and found yours and others; they were resolved in the same way. I went ahead and merged.
