### ISSUE TITLE
Submission with no contributors leads to minor display issues

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7397]
**Describe the bug**
When a submission is made with no contributors, there are some areas of the editorial UI which do not adapt nicely. In each of the screenshots below, the missing author creates an empty space, or a vertical misalignment, or an extra `/` or `|` character. 

![image](https://user-images.githubusercontent.com/560456/138083958-902e0ff0-4e3d-413c-9b79-d92cdec89eee.png)
![image](https://user-images.githubusercontent.com/560456/138084035-66a0f0ff-06c7-4ea9-902b-e18480f4f515.png)
![image](https://user-images.githubusercontent.com/560456/138084094-4ad374e8-5328-493e-8651-e039dcbd7c17.png)

**To Reproduce**
1. Go to any submission and remove all authors.

**What application are you using?**
 3.4 pre-release (`main`)

**Additional information**
Identified as part of https://github.com/pkp/pkp-lib/issues/7388.

---
**PRs**

**Branch `main`**
OJS: pkp/ojs#3587
OMP: pkp/omp#1228
OPS: pkp/ops/pull/377
pkp-lib: pkp/pkp-lib#8368
ui-library: pkp/ui-library#225

**Comment by defstat** [comment]
@NateWr I have added PRs [here](https://github.com/pkp/pkp-lib/issues/7397#issue-1034877317).

**Comment by defstat** [comment]
@NateWr I resolved the PR's review comments. It's ready for another round

**Comment by NateWr** [comment]
Thanks @defstat! I've merged the submodules to `main` and cherry-picked in the OJS/OMP/OPS commits because of a merge conflict. :+1:
