### ISSUE TITLE
Error when searching for a keyword in a language not enabled in the UI

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#7407]
If the language is not enabled for the UI in the settings (italian here):
![image](https://user-images.githubusercontent.com/18707781/139078246-9babc24a-445d-4d50-9c93-29a66d3860e5.png)

It gives me a warning on every keystroke when filling the metadata (keywords) in Itallian of an Itallian submission:
![image](https://user-images.githubusercontent.com/18707781/139078476-eb07ba0e-edc2-4ed2-be22-5b4d55205567.png)

Enabling the Itallian language for the UI removes the warning, but that is an undesirable behavior when we want to accept submissions in many languages but have the interface available in just a few languages.

**Comment by NateWr** [comment]
Thanks @luizbgomide! Even though you included the information in your original report, it wasn't until I read the reproduction steps that I realized we were talking about keywords. The issue template really does help.

PR:
https://github.com/pkp/pkp-lib/pull/7441

Tests:
https://github.com/pkp/ojs/pull/3222

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and manually applied to the `main` branch.
