### ISSUE TITLE
Use Laravel-style method names for Mailables

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7408]
The custom function names in our Mailable classes are a little more PKP-style (`setXXXX`). But when we create a mailable, they sit alongside Laravel's function names:

```php
$mailable = (new DecisionAcceptNotifyAuthor($context, $submission, $decision))
    ->setSender($sender)
    ->setRecipients($recipients)
    ->subject($email->subject)
    ->body($email->body);
```

We should change these to sit more comfortably next to the Laravel names:

```php
$mailable = (new DecisionAcceptNotifyAuthor($context, $submission, $decision))
    ->sender($sender)
    ->recipients($recipients)
    ->subject($email->subject)
    ->body($email->body);
```

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/7423
tests OJS: https://github.com/pkp/ojs/pull/3215
