### ISSUE TITLE
Make Google Analytics available at the Site level

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#741]
Google Analytics, as a context specific plugin, does not output on the site homepage level.  It's pretty reasonable that the Site Administrator would want it to.

http://forum.pkp.sfu.ca/t/google-analytics-homepage/3561/6

**Comment by ctgraham** [comment]
https://github.com/pkp/ojs/pull/599

**Comment by asmecher** [comment]
Thanks, @ctgraham, looks good! Merged for OJS 2.4.7.
