### ISSUE TITLE
Permit editors to change submission locales

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#742]
Currently it's not possible for editors to change the primary locale of a submission. Add it to the Editor's metadata form.

**Comment by asmecher** [comment]
Added a partial fix adding the field to the editor's form -- but I'm not committing it because of unresolved quirks with form validation:

- Create a submission in an English-language journal, with an English primary locale.
- Change the submission's primary locale to French. The change will stick, even though no French abstract or title have been entered.
- Try to change it back to English. Now it can't be changed back, because the validator complains about the missing French required fields.

**Comment by fgnievinski** [comment]
forum discussion:

https://forum.pkp.sfu.ca/t/ojs-does-the-crossref-export-plugin-registeres-doi-with-two-titles/3929/19

**Comment by NateWr** [comment]
Closing this because we are not going to be working on OJS 2.x further.

**Comment by MiKoko856** [comment]
Unfortunately, I have the same problem in OJS 3.3.0.10.

Please explain how to solve this problem without deleting the submission and creating a new one (by entering all data manually).

**Comment by bozana** [comment]
@MiKoko856, that feature is not implemented in OJS 3.3. Follow this issue to be informed about that feature that should come with 3.5: https://github.com/pkp/pkp-lib/issues/5502.

**Comment by MiKoko856** [comment]
And when is version 3.5 planned to be released?

**Comment by bozana** [comment]
I think end of next year. 
However, maybe someone having the same problem could write here how you could best fix it for now...
