### ISSUE TITLE
Clarify field description for Preferred Public Name

### ISSUE THREAD

**Issue by kshuttle** [pkp/pkp-lib#7426]
**Describe the problem you would like to solve**
The current field description for the "Preferred Public Name" field is unclear, leading authors to incorrectly use this field in the author-entered metadata. The field description does not indicate that anything entered in this field will OVERRIDE the author's given name and family name as displayed on the article record page. Authors sometimes add just shortened given names (e.g. Tom) or salutations only (e.g. Dr.)---when they should be entering their entire name (e.g. Dr. Tom Wilson). This impacts the item metadata downstream. This is addressed in the [metadata better practices guide](https://docs.pkp.sfu.ca/metadata-practices/en/issue-article-metadata#contributors), but can be clarified for authors in the field description.

**Describe the solution you'd like**
Update the field description to direct authors to include their "complete preferred name," or indicate that the preferred name will override the given and family name entered above, or both.

More user testing around the preferred name field may be useful in the future as well.

**Who is asking for this feature?**
This is a concern for journal editors who are looking to ensure that metadata fields are used correctly and consistently, and for authors who do not realize that this field will override their given name on article pages. This issue was raised by a Publishing Services client.

**Comment by NateWr** [comment]
@kshuttle did you have a suggestion for the wording of the description?

cc @defstat, your work on https://github.com/pkp/pkp-lib/issues/6850) can roll this in once we have a recommended description for the field.

**Comment by kshuttle** [comment]
I would suggest the following wording for the Preferred Name field description:

> How do you prefer to be addressed? Please use your full name exactly as you would like it to appear on the published article page, including any salutations, middle names, and suffixes.

**Comment by NateWr** [comment]
Thanks @kshuttle! Is "salutations" what you call "Dr" or "Professor"? I think we would call those "titles" over here. Sometimes an example is easier to construct than a description. What do you think about this?

> Please provide the full name as the author should be identified on the published work. Example: Dr Kathryn J. Shuttle

(I took our "you" because the submitting author or editor may be entering author details for someone else.)

**Comment by kshuttle** [comment]
I think what you suggest sounds great, @NateWr. Let's go with this wording for the field description.

**Comment by NateWr** [comment]
@defstat ok, let's add this to the field's `description` in the new form. But let's change the name from `Dr. Kathryn J. Shuttle` to `Dr. Alan P. Mwandenga` to match some of our test data. (Unless you want to be immortalized in OJS, @kshuttle! :))

**Comment by kshuttle** [comment]
@NateWr @defstat please go ahead and use `Dr. Alan P. Mwandenga` -- I will seek fame through other means ;)

**Comment by librariam** [comment]
+1 from a PKP|PS client where multiple authors are putting nothing other than "Prof" and "Dr" in the preferred name field.

Also, I hope it's an ok temp solution to modify the field prompt via the Custom Locale plugin:

File: lib/pkp/locale/en_US/user.po
Key: user.preferredPublicName.description

**Comment by NateWr** [comment]
This is improved in the `main` branch and will go out with 3.4 like this:

![contributor-form](https://user-images.githubusercontent.com/2306629/149302728-e09e75e9-f25e-4c9e-bd04-3b768fd1192d.png)
