### ISSUE TITLE
Add recipient control on email forms

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#743]
...for extra CC, BCC, or recipient entries.

See: http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8908

**Comment by amandastevens** [comment]
I get requests for this feature fairly often. Most recently Open Academia commented, "We have noticed that the previous (OJS 2) function of emailing a copy of the decision letter to reviewers is missing in OJS 3.  [One of our journals] likes to send such emails to reviewers, and it is generally a function that is commonly used and exists in other systems. The journal has a review form in which they specifically ask reviewers: 'Do you wish to receive a copy of the decision email? (Your anonymity will be protected).' Most reviewers answer 'Yes' to that question and I think reviewers in general are very interested to see what the outcome of the manuscripts that they help improve is. (and seeing the other reviewer(s) comments must also be quite interesting for reviewers/researchers)."

**Comment by leofontenelle** [comment]
"Journals should notify reviewers of the ultimate decision to accept or reject a paper, and should acknowledge the contribution of peer reviewers to their journal. Editors are encouraged to share reviewers’ comments with co-reviewers of the same paper, so reviewers can learn from each other in the review process." -- [ICMJE recommendations](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/responsibilities-in-the-submission-and-peer-peview-process.html)

**Comment by amandastevens** [comment]
Comment from a user: "I am very much missing the ability to inform reviewers about my decision on the paper efficiently and in a blind fashion like I was able to do with the BCC on the reviewer email on [OJS2]."

**Comment by asmecher** [comment]
Hi all -- while we do get general requests for better control around email recipients (and I'll leave this issue open for that), most of the requests here are about copying reviewers on the editor decision email. I've hived that off to a new issue: https://github.com/pkp/pkp-lib/issues/4834

**Comment by librariam** [comment]
+1 from PKP|PS to add a CC field on reviewer reminders (different from CC on editorial decision). This is to help editors keep track of reminders that were sent via their mailbox without having to check Editorial History every time.

**Comment by asmecher** [comment]
(Here's a user-contributed draft of the necessary code changes: https://forum.pkp.sfu.ca/t/add-bcc-field-to-mail-forms/58868/5)

**Comment by asmecher** [comment]
The different email compose boxes in the system (searching the OJS 3.2 codebase) are:
- Submission workflow forms:
  - The editor decision forms (`RecommendationForm.inc.php`, `EditorDecisionWithEmailForm.inc.php`, `SendReviewsForm.inc.php`)
  - The participant "Notify" form (`PKPStageParticipantNotifyForm.inc.php`, `StageParticipantNotifyForm.inc.php`)
  - The reviewer forms (`ThankReviewerForm.inc.php`, `ReviewReminderForm.inc.php`, `CreateReviewerForm.inc.php`, `ReviewerForm.inc.php`, `ReviewerNotifyActionForm.inc.php`, `EmailReviewerForm.inc.php`)
- Management forms:
  - The Users & Groups "Notify" form (`UserEmailForm.inc.php`) (available to managers/admins)

Did I miss any? Are any of these more important than others? My sense is that the submission workflow forms are the important ones.

**Comment by pmangahis** [comment]
+1 from PKP|PS to add a CC field on reviewer reminders (different from CC on editorial decision).

**Comment by fgnievinski** [comment]
just for clarification: is the goal to offer empty cc/bcc fields where the editor can input arbitrary email addresses or are you intending to pull coauthors' or reviewers' email addresses from the database? The former would be much simpler and would meet most of the needs.

**Comment by NateWr** [comment]
I think initial work on the email workflow will seek to support arbitrary CC/BCC fields. Bringing in related email addresses for autocomplete will also be useful and may or may not be part of an initial implementation.

**Comment by pmangahis** [comment]
+1 from PKP|PS to add a CC field on editorial decisions

**Comment by librariam** [comment]
+1 from PKP|PS to add a CC field on email sent in the editorial workflow
