### ISSUE TITLE
Restrict what languages are available for new submissions

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7431]
**Describe the problem you would like to solve**
A journal can select what languages are supported for submissions and each submission has a primary locale. This permits a journal to publish articles, for example, in German and English.

However, in some cases, a journal wants to change the languages it publishes in. For example, a journal may have published in German, then published in German and English, and now wants to only publish in English. In such cases, the back content only exists in German. The articles are not translated into both languages. They are either German or English. 

When this journal disables German as a submission language, all of the German article metadata is no longer displayed. Although it exists in the database, it is "hidden" from the user.

If the journal leaves German enabled as a submission language, authors can continue to submit in German and editors must deal with this.

**Describe the solution you'd like**
It should be possible to select what languages new submissions can be made in. This would allow a language to be enabled for historical submission metadata, but allow ongoing editorial activity to continue without receiving new submissions in that language.

**Who is asking for this feature?**
Journals with back content in languages in which they no longer publish, or any journals that want to remove a language they currently publish in.

**Additional information**
cc @mfelczak, @amandastevens 

<hr>

PRs from @jyhein, s. https://github.com/pkp/ojs/pull/4040#issuecomment-1728219429:
PKP: https://github.com/pkp/pkp-lib/pull/9309
OJS: https://github.com/pkp/ojs/pull/4040
OMP: https://github.com/pkp/omp/pull/1461

**Comment by bozana** [comment]
This was done in the issue https://github.com/pkp/pkp-lib/issues/9425.
