### ISSUE TITLE
Duplicate foreign key error when creating a new version in OMP

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7439]
**Describe the bug**
When a new version of a publication is created in OMP, a fatal error is encountered due to a foreign key constraint on the chapter authors table.

```
Message: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint &quot;chapter_authors_pkey&quot;
DETAIL:  Key (author_id, chapter_id)=(70, 79) already exists.
File: /home/nate/Projects/pkp/omp/lib/pkp/lib/vendor/doctrine

...

#7 /home/nate/Projects/pkp/omp/classes/author/DAO.inc.php(35): Illuminate\Database\Query\Builder->insert(Array)
#8 /home/nate/Projects/pkp/omp/classes/author/Repository.inc.php(40): APP\author\DAO->insertChapterAuthor(70, 79, true, 0)
#9 /home/nate/Projects/pkp/omp/classes/publication/Repository.inc.php(192): APP\author\Repository->addToChapter(70, 79, true, 0)
#10 /home/nate/Projects/pkp/omp/lib/pkp/api/v1/submissions/PKPSubmissionHandler.inc.php(666): APP\publication\Repository->version(Object(APP\publication\Publication), Object(APP\core\Request))
#11 [internal function]: PKPSubmissionHandler->versionPublication(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
```

**To Reproduce**
1. Go to a submission's workflow 
2. Go to Publication > Contributors and create two authors
3. Go to Publication > Chapters, create a chapter, and assign both authors.
4. Click Create New Version
4. See error in apache error log

**What application are you using?**
OMP 3.4 pre-release (`main` branch)

---
**PRs**

**Branch `main`**
[ui-library]: pkp/ui-library#218

**Branch `stable-3_3_0`**
[OMP]: pkp/omp#1217 (***TESTS ONLY***)
[ui-library]: pkp/ui-library#220

**Comment by NateWr** [comment]
Along with the bug fix we should include at least one test that creates a new version of a submission with multiple chapters, publication formats and authors.

**Comment by asmecher** [comment]
@NateWr, can you still replicate this using the current `main` branch? I tried using the existing bbeaty submission (ID#4) by publishing it and then creating another version (it already has multiple authors and multiple chapters) and I didn't encounter any problems.

**Comment by NateWr** [comment]
Yes, I was just able to reproduce it from a clean install. I'm using postgres, so maybe that's the difference? I didn't use the test data, but after installing I did the following:

1. Created a press
2. Created a new submission while logged in as admin user.
3. During submission I created a second author, and assigned both authors to a chapter.
4. I skipped review and send it to copyediting.
5. Published it.
6. Clicked create new version.
7. Got the same error.

```
Previous error:
Type: PDOException
Code: 23505
Message: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint &quot;chapter_authors_pkey&quot;
DETAIL:  Key (author_id, chapter_id)=(3, 2) already exists.
File: /omp/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php
Line: 112
```

**Comment by touhidurabir** [comment]
@NateWr @asmecher I can say with solid confirmation that this issue only associated with Postgres and not mysql or MariaDB . This is something that I have faced previously 2/3 time . This mainly happened in my case when my table primary key become out of sync . The solutions describe in this `SO` thread https://stackoverflow.com/questions/4448340/postgresql-duplicate-key-violates-unique-constraint helped me previously to resolve this issue . But weirdly I have faced this issue even with postgres 12+ .

**Comment by NateWr** [comment]
Yes, go ahead and swap those two lines.

**Comment by defstat** [comment]
@NateWr 

Find [here](https://github.com/pkp/pkp-lib/issues/7439#issue-1047669814) PRs for `stable-3_3_0` and `main` branches

**Comment by defstat** [comment]
@NateWr the tests are passing for OMP stable-3_3_0

**Comment by NateWr** [comment]
Thanks @defstat! Merged to `main` and `stable-3_3_0`.
