### ISSUE TITLE
composer install for pkp fails for OMP on stable-3_1_2

### ISSUE THREAD

**Issue by OyvindLGjesdal** [pkp/pkp-lib#7443]
**Describe the bug**
We are upgrading omp from 1.2 and after we've met some issues with the full upgrade,  are now trying to incrementally upgrade it.

`composer install` in pkp/lib gives the error:

```
 Applying patches for moxiecode/plupload     lib/safen-plupload-example-6888.diff (Make plupload example safe)    Could not apply patch! Skipping. The error was: Cannot apply patch lib/safen-plupload-example-6888.diff`
``` 

When we remove the patch from *composer.json* and rerun *composer* the *upload.php* example now contains
in *./lib/vendor/moxiecode/plupload/examples/upload.php* in the patch location
```
#!! revise it and customize to your needs.
die("Make sure that you enable some form of authentication before removing this line.");
```
which is similar to the patch?

**To Reproduce**
1. checkout *stable-3_1_2* and submodules
2. run `composer install` in lib/pkp
3. See error

**What application are you using?**
 OMP 3_1_2 (for incremental upgrading from 1.2 to 3.3)

**Comment by OyvindLGjesdal** [comment]
We tried to jump up one stable version to *stable-3_2_1* and the same applies here.

**Comment by asmecher** [comment]
@OyvindLGjesdal, do you have the GNU `patch` tool available on your system? If not, that might explain why the patch is failing to apply. Alternately, maybe you're mixing `composer install` (which will install the exact dependency versions specified in the Composer lockfile) and `composer update` (which will potentially install newer versions than those specified)?

The line in `lib/vendor/moxiecode/plupload/examples/upload.php` that you quoted is equivalent to the patch, so you're safe if it's present.

**Comment by OyvindLGjesdal** [comment]
Doh, I had removed the lockfile, and that explains why the patch can't be applied to the newer version. Thanks for helping!

**Comment by asmecher** [comment]
Not a problem, thanks for following up!
