### ISSUE TITLE
OMP specific email templates appear in OJS in the add participant form

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7447]
**Describe the bug**
Described here: https://forum.pkp.sfu.ca/t/removing-index-request-and-index-complete-from-assign-participant-option-to-active-submission/70326
In OJS, when assigning a new participant to a submission on a production stage, 2 blank email templates appear in the form's correspondent option: `INDEX_REQUEST` and `INDEX_COMPLETE`. This 2 templates are specific 2 OMP and shouldn't appear in other applications

**To Reproduce**
1. Make a submission and pass it to the production stage
2. Click on the `assign` button near `participants`
3. Open the list of available email templates
4. See 2 empty templates

**What application are you using?**
 OJS main branch

**Additional information**
Looks like it's enough to remove unused templates keys from here: https://github.com/pkp/ojs/blob/03739022189649c8bbaa04d231401f084b301de4/controllers/grid/users/stageParticipant/form/StageParticipantNotifyForm.inc.php#L43

**Comment by withanage** [comment]
Hi @NateWr ,

Can you review the following PRs:

- https://github.com/pkp/ojs/pull/3425
- https://github.com/pkp/ojs/pull/3426
