### ISSUE TITLE
Passwords should not be emailed.  Ever.

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#745]
Multiple email templates email the password to the user.  This is insecure and entirely avoidable, especially considering the improved password reset process of https://github.com/pkp/ojs/pull/584

See at least OJS:
https://github.com/pkp/ojs/blob/master/locale/en_US/emailTemplates.xml#L783
https://github.com/pkp/ojs/blob/master/locale/en_US/emailTemplates.xml#L124
https://github.com/pkp/ojs/blob/master/locale/en_US/emailTemplates.xml#L99
https://github.com/pkp/ojs/blob/master/locale/en_US/emailTemplates.xml#L87
And OMP:
https://github.com/pkp/omp/blob/master/locale/en_US/emailTemplates.xml#L122
https://github.com/pkp/omp/blob/master/locale/en_US/emailTemplates.xml#L97
https://github.com/pkp/omp/blob/master/locale/en_US/emailTemplates.xml#L85
And OCS:
https://github.com/pkp/ocs/blob/master/locale/en_US/emailTemplates.xml#L75
https://github.com/pkp/ocs/blob/master/locale/en_US/emailTemplates.xml#L65

Additional references to this workflow will be found the the locale files (https://github.com/pkp/ojs/blob/ojs-dev-2_4/locale/en_US/emailTemplates.xml#L215), templates (https://github.com/pkp/ojs/blob/ojs-dev-2_4/templates/user/register.tpl#L200), and code (https://github.com/pkp/ojs/blob/ojs-dev-2_4/classes/user/form/RegistrationForm.inc.php#L348).

**Comment by asmecher** [comment]
@ctgraham, I agree, but also suspect we'll get some users adamant that passwords *should* be emailed. I suggest the following small change: Remove the password from the default email templates, but leave support in the code for the `{$password}` variables if the JM wants to make use of them. I don't think any other change would be required.

**Comment by ctgraham** [comment]
That possible divergence of opinion is why I opened this here well before doing any work on the task.

Do you think we wouldn't be able to convince users accustomed to the password being emailed to instead expect a single-use access token such as the password reset?

Perhaps we could target just the quick fix for OJS 2.x, and ensure better practices for master?

**Comment by asmecher** [comment]
I'm just guessing, based on the amount of confusion that we've heard regarding the two-step password reset process.

> Perhaps we could target just the quick fix for OJS 2.x, and ensure better practices for master?

That sounds ideal to me!

**Comment by samueloph** [comment]
Great!

**Comment by asmecher** [comment]
@samueloph and @ctgraham, I've removed the `{$password}` variable from the email templates in `ojs-dev-2_4`. They'll still be supported for users who already have them in the templates. For OJS 3.0 and OMP 1.2, I've filed this issue to remove support for emailed passwords entirely: https://github.com/pkp/pkp-lib/issues/750

Note that the manager's "hello, you're now a reviewer, here's your account info" email still has this in the template, but I made it so that the email must be reset upon the first login.

**Comment by asmecher** [comment]
(Let me know if that missed any of your concerns!)

**Comment by ctgraham** [comment]
Isn't the USER_REGISTER template used for both self-registration and for mediated registration?  If we really remove the password from this template by default, I think the default locale keys of
https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/locale/en_US/manager.xml#L116
and
https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/locale/en_US/user.xml#L120
will need to be adjusted.

I'm not nearly as opposed to sending a plaintext password that must be reset on login as my issue title would make me appear.

Given the locale changes that would be required (and the the translation round), I would be happy with just applying defaults so that if someone really wants to email a password, they have to explicitly do it.

**Comment by asmecher** [comment]
Thanks, @ctgraham, that approach also makes sense to me. Merged.

**Comment by asmecher** [comment]
Oops -- I should've checked the Travis test results. @ctgraham, this breaks the tests, which register a number of users through the user registration form.

Consider a normal user self-registration. With this change merged in...
- User enters information, including a password
- The password is mailed back to the user
- The user must immediately change the password again (!)

**Comment by ctgraham** [comment]
Looking into this, @asmecher .  I'm not sure why the password reset would be triggered in normal user self-registration; I didn't intend for it to be.

**Comment by ctgraham** [comment]
My read is that the failure is actually coming from dbarnes' login.  The editorial users are being created by the journal manager, and now each of these are being created with a temporary password.

I think we need to simulate the Journal Manager unchecking the "Must Change Password" box here:
https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/tests/data/PKPCreateUsersTest.inc.php#L48

**Comment by asmecher** [comment]
Yes, @ctgraham, it looks like you're correct. Are you tinkering with this or would you like me to fix it?

**Comment by ctgraham** [comment]
I'd be interested in fixing it, but I have a couple of things to attend to locally, and then will need to read up on the test framework a bit.  I imagine it will just be something like:
```php
$this->removeSelection('id=mustChangePassword');
```
but I have not even looked at the available methods yet.

**Comment by asmecher** [comment]
I'll tinker with it and let you know what the exact change was, @ctgraham. I appreciate your contributions here.

**Comment by asmecher** [comment]
@ctgraham, the above commits should cover it. This was necessary to fix the tests:
https://github.com/pkp/pkp-lib/commit/5fc23e40d76bfe88be98682fb61ddcb99ed0c469
