### ISSUE TITLE
Information Disclosure via Forget Password

### ISSUE THREAD

**Issue by twakeford** [pkp/pkp-lib#7451]
**Describe the bug**
There is an information leak that allows an outside attack to check whether an email address is associated with an account.

**To Reproduce**
1. Go to '/login/lostPassword'
2. Entering a registered email address gives the message '_A confirmation email has been sent to your email address. Please check the instructions in the email to reset your password_'
3. Entering an unregistered email address gives the message  'No user exists with the specified email address'

When the input creates a different response, an attacker can test a large number of email addresses to find those that are registered within the journal website and those which are not. 

Impact:

Attackers will be able to identify which accounts are registered on your website

**What application are you using?**
 OJS 3.3

**Comment by asmecher** [comment]
I've committed this to the `main` branch for release in 3.4.0, but it's not hard to back-port to 3.2.x or 3.3.x if needed. Because it involves a change to the meaning of a locale key, we can't commit it to earlier branches unless we have a translation update round.

**Comment by fradeve** [comment]
@asmecher thanks for looking into this!

If you are interested in having a more "formal" reference to issues like this, there is a description here: https://cwe.mitre.org/data/definitions/204.html, also known as `CWE-204`.

We would really like to see this in 3.3.X if that doesn't take too much of your time.

Thanks again! :handshake:
