### ISSUE TITLE
Missing Rate Limit On Login / User's Account Hacking

### ISSUE THREAD

**Issue by twakeford** [pkp/pkp-lib#7452]
**Describe the bug**
There is no lockout mechanism in the login page to stop access attacks. A malicious minded user can target a site and input infinite attempts on the password without being locked out. Accounts with weak passwords would be particularly at risk.

Other websites generally have a lockout mechanism for a user to be logged out if they breach a set number of incorrect. passwords. For security reasons, there should be a lockout mechanism after trying X wrong password requests, so the attacker will not be able to hack a user account by making random password requests. 

**What application are you using?**
 OJS 3.3

**Comment by jonasraoni** [comment]
Hi @twakeford!

There's a plugin which provides some extra security measures available here: https://github.com/ulsdevteam/pkp-betterPassword/

**Comment by asmecher** [comment]
@twakeford, does the above plugin meet your needs?

Longer term I'd like us to adopt session/user management tools from the Laravel platform, which will provide a lot of built-ins like this.

**Comment by twakeford** [comment]
@asmecher I haven't been able to get it installed yet to be 100% sure, but the description sounds like it will do the job.

**Comment by asmecher** [comment]
OK, great! I'll close this issue.
