### ISSUE TITLE
Unexpected error when assigning a submission to an issue

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7458]
**Describe the bug**
When assigning a submission to an issue, a modal appears that says "An unexpected error occurred". This doesn't seem to prevent the submission from being assigned to an issue or from publishing the submission. But it does lead to a fatal error in the database.

**To Reproduce**
1. Go to an unpublished submission in the copyediting or production stages.
2. Click on Publication > Issue.
3. Click the button to assign it to an issue.
4. After an issue is selected, the Publish popup will appear. Just before this appears, and below the publish popup, there will be another small popup that says "an unexpected error has occured.

**What application are you using?**
OJS 3.4 pre-release (`main` branch)

**Additional information**
The following error appears in the logs:

```
[16-Nov-2021 11:55:19 Europe/London] Slim Application Error:
Type: Error
Message: Call to a member function getContext() on null
File: /ojs-main/classes/services/SectionService.inc.php
Line: 78
Trace: #0 /ojs-main/classes/services/SectionService.inc.php(101): APP\services\SectionService->getProperties(Object(APP\journal\Section), Array, NULL)
#1 /ojs-main/classes/issue/maps/Schema.inc.php(137): APP\services\SectionService->getSummaryProperties(Object(APP\journal\Section))
#2 /ojs-main/classes/issue/maps/Schema.inc.php(33): APP\issue\maps\Schema->mapByProperties(Array, Object(APP\issue\Issue))
#3 /ojs-main/api/v1/issues/IssueHandler.inc.php(240): APP\issue\maps\Schema->map(Object(APP\issue\Issue))
#4 [internal function]: IssueHandler->get(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
```

**Comment by asmecher** [comment]
@NateWr, I'm pretty sure this will have been fixed by now. But please re-open if you've seen it lately.
