### ISSUE TITLE
AdminHandler function missing arguments

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7459]
**Describe the bug**
Running 'Clear Scheduled Task Execution Logs' from admin pages throws a fatal error.

AdminHandler::clearScheduledTaskLogFiles() is missing arguments for CSRF check against request.

**To Reproduce**
1. Go to Administration tab
2. Click on 'Clear Scheduled Task Execution Logs'

**What application are you using?**
OJS main branch

**Comment by ewhanson** [comment]
Hi @asmecher, could you have a look at this? It adds in the needed arguments for `$request->checkCSRF()`. Will OMP and OPS need submodule commits as well? Thanks!

PRs:
#7460
pkp/ojs#3228

**Comment by asmecher** [comment]
Looks good, thanks, @ewhanson! I didn't merge the OJS submodule update because I didn't want to create conflicts with other PRs that are open and include submodule updates. I checked `stable-3_3_0` and it doesn't have the same problem.
