### ISSUE TITLE
Port notification fixes from OMP stable to master

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#746]
See: http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8969

**Comment by asmecher** [comment]
@beghelli, I think this is probably ready for attention.

**Comment by asmecher** [comment]
@beghelli, FYI, this is a priority for OpenSI for OMP 1.2.

**Comment by asmecher** [comment]
Note to self (etc): To direct all notification emails (not mailing list emails!) to a single account, edit `lib/pkp/classes/notification/PKPNotificationOperationManager.inc.php`, find `function sendNotificationEmail`, and change...

    $mail->addRecipient($user->getEmail(), $user->getFullName());

**Comment by beghelli** [comment]
@asmecher Thanks Alec, I will take care of this.

**Comment by asmecher** [comment]
Thanks, @beghelli -- I'm not sure if this is part of the back-porting work that needs doing, but all the notification emails I'm getting are showing empty contents (getNotificationContents returns an empty string, apparently falling back on the `lib/pkp/classes/notification/NotificationManagerDelegate.inc.php` default implementation).
