### ISSUE TITLE
Review OJS/OMP/OPS readme and docs files

### ISSUE THREAD

**Issue by Daxx367** [pkp/pkp-lib#7466]
**Describe the problem you would like to solve**
I recently had to update the version of OJS for a client. I was not the one who had installed OJS and I have never worked with it before.
Once I had updated the site using the docs found in the git repo all theming was broken so I reverted the site using a backup. 
After some probing and checking the changes between the clients version and the same release on the downloads page of the site I found the client had a theme installed. The docs do not mention that the theme folder should be copied.

**Describe the solution you'd like**
That some mention of the theme folder be included in the updating docs.

**Who is asking for this feature?**
New OJS system admins

**Additional information**
None.

**Comment by NateWr** [comment]
Hi @Daxx367, our Technical Committee has just published a [big guide on upgrading OJS/OMP/OPS](https://docs.pkp.sfu.ca/dev/upgrade-guide/en/). We should probably replace our in-app upgrade document with a link to this.

**Comment by NateWr** [comment]
After a quick look at what we've got in OJS, here are some changes we should make to the `.md` files distributed with OJS, OMP and OPS:

1. Refer to our technical documentation: docs.pkp.sfu.ca/dev
2. Change "using Git development source" to a link to the getting started section of our technical documentation
3. Change "running tests" to a link to our testing docs
4. Remove outdated files in the docs folder https://github.com/pkp/ojs/tree/main/docs
5. Make sure RELEASE, UPGRADE and FAQ documents are current and link to relevant documentation.

**Comment by NateWr** [comment]
Now that we have published the contributor's guide in the docs hub, @asmecher suggested that we may be able to remove some of the following info:

> I think with this addition we should remove some of the built-in documentation in the repo -- `docs/dev/TechnicalReference.pdf` and `.odt`, and some of the documentation from the main `index.php` wrapper, at a glance.

**Comment by asmecher** [comment]
Removed the Technical Reference and `index.php` self-documentation.

**Comment by asmecher** [comment]
I've taken a quick look over the documentation and done some standardization and removed some outdated/extra material. I don't consider this complete, so I'll leave it open, but it's good enough for 3.4.

**Comment by NateWr** [comment]
@asmecher I have taken a pass at updating the main readme for OJS to refer to existing documentation elsewhere. I've also removed a bunch of documents in the `/docs` directory that I felt were obsolete. They are covered in more detailed in our docs hub, which is linked from the main readme.

Can you take a look and let me know if you're ok with this clear-out?

PR:
https://github.com/pkp/ojs/pull/3842

Also, I had a question about https://github.com/pkp/ojs/blob/main/docs/RELEASE. It looks like this is a template for the files in the `release-notes` directory. Can I move it into `/docs/dev` and replace the "Configuration Changes" section with a link to the release notebook?

**Comment by asmecher** [comment]
Please go ahead, @NateWr -- I'm a bit of a hoarder when it comes to this stuff, but looking at the proposed result, it's a lot clearer and sane when it comes to directing folks to existing resources where we're better able to maintain them. Thanks!

**Comment by asmecher** [comment]
Oh, about `RELEASE` -- historically, `docs/RELEASE` should be a copy of `docs/release/README-3.4.0`. But this is a long-standing practice that is probably ready for change.

**Comment by NateWr** [comment]
Thanks! I've merged those changes and updated the links/descriptions that appear in the sidebar of each github repository. I'll close this as done now, but let me know if you find any other documentation to be updated/removed.
