### ISSUE TITLE
Announcements tool does not send email

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/pkp-lib#7469]
**Describe the bug**
The announcements tool does not send email to all registered users, even when the required checkbox is selected.

**To Reproduce**
1. Go to Announcements
2. Click Add Announcement
3. Populate Add Announcement form
4. Click "Send an email about this to all registered users."
5. Click "Save"

**What application are you using?**
 OJS 3.3.0.8

**Additional information**
The journal reporting this problem has experienced the bug since 3.3.0.5

**Comment by asmecher** [comment]
@tmrozewski-york, can you set a title for this entry?

**Comment by tmrozewski-york** [comment]
Whoops, thanks! Fixed.

**Comment by NateWr** [comment]
Looks like the following code was missed when announcements move to the REST API:

https://github.com/pkp/pkp-lib/blob/stable-3_2_1/controllers/grid/announcements/form/AnnouncementForm.inc.php#L188-L203

This should be added to the `PKPAnnouncementHandler::add()` method.

**Comment by Vitaliy-1** [comment]
I think it's a similar issue to: https://github.com/pkp/pkp-lib/issues/7213

**Comment by NateWr** [comment]
You're right. Closing this in favor of #7213.

**Comment by tmrozewski-york** [comment]
My IT head says: "It looks like the patch is for OJS 3.2. Could you ask them for 3.3.0.8 patch please?"

**Comment by tmrozewski-york** [comment]
Please disregard last comment, we both spoke too soon.

**Comment by tmrozewski-york** [comment]
Hi @Vitaliy-1 and @NateWr my IT team implemented the fix described in #7213 in 3.3.0.8 and found that the problem is not resolved.

When I repeated the steps described in the original post, no email was sent. In addition, when I tried to add a new announcement, I clicked Save and got an error saying "An unexpected error has occurred. Please reload the page and try again." The announcement itself was created but the Title, Short Description, and Announcement fields are blank. You can see the blank announcements created by this process in our OJS sandbox: https://jat.journals.yorku.ca/index.php/default/announcement

My IT support believes that the problem continues because the fix described in #7213 is for OJS 3.2.1 and does not work in 3.3.0.8. He requests a patch for 3.3.0.8.

**Comment by asmecher** [comment]
@tmrozewski-york, there is no completed patch for 3.3.0-x yet; watch https://github.com/pkp/pkp-lib/issues/7213 for a patch to be posted with directions. I'm not sure which patch your IT support applied, but it's probably not right.
