### ISSUE TITLE
Fair Copy files not migrated when upgrading from OJS 2 to 3

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7470]
**Describe the bug**
If an installation is upgraded from OJS2, there's a good chance that submissions contain fairCopy files, which had an old file stage of 7.  This file stage is no longer used in OJS3, but these files stay in the database.  If an article that has these files is exported, it fails validation because there is no SUBMISSION_FILE_FAIR_COPY constant and corresponding map entry in getStageNameStageIdMapping in PKPNativeImportExportDeployment.inc.php, even though the pkp-native.xsd schema defines fair_copy as a valid enumeration for the stage attribute on a submission_file element.  The validation error is that a stage of '' is not a valid facet.

While fair copy files are no longer used in OJS3, it'd be nice that upgraded submissions can still be exported if the editors want the XML for other reasons.

**What application are you using?**
OJS 3.3.0.8

I know that upgrades aren't really being worked on now, but a fix for this wouldn't require any changes to the upgrade code.

**Comment by jnugent** [comment]
Hi @NateWr  We've actually been grappling with this recently, and have had a few discussions internally about where to put them. @ewhanson and I have been thinking that maybe moving them to SUBMISSION_FILE_FINAL is a possibility. They get completely lost in the upgrade process otherwise, even though they continue to exist in the files directory and in the database.  OJS2 doesn't create the necessary activity log entries when they are uploaded so there's no mention of them in the activity log after the upgrade.

Tagging @mfelczak as well here; I'm not sure what "fair copy" was supposed to mean.

**Comment by mfelczak** [comment]
In OJS 2 these look to be files that have undergone corrections and updates following submission acceptance so migrating them as SUBMISSION_FILE_FINAL makes sense to me. In OJS 3 they would then appear as files in the copyediting stage.

**Comment by NateWr** [comment]
Ok thanks. We don't do database migrations in a 3.x.x.x release, so the next possible candidate for this migration is 3.4 (the `main` branch). Is someone from PS able to provide a PR with this migration? 

You should be able to backport the PR for your specific client without too much hassle, though the constants will have changed from `SUBMISSION_FILE_FAIR_COPY` to `SubmissionFile::SUBMISSION_FILE_FAIR_COPY`.

**Comment by ewhanson** [comment]
@mfelczak, is this something you'd like me to add?

**Comment by georgd** [comment]
The same applies to file stage 8 `SUBMISSION_FILE_EDITOR` . Which would be the appropriate file stage in OJS 3?

**Comment by asmecher** [comment]
(The above question is cross-posted here: https://forum.pkp.sfu.ca/t/mapping-for-obsolete-file-stage-8/73166/3)

**Comment by georgd** [comment]
I’m sorry to annoy you by bumping this, but we’d like to fix this locally for our installation and need to know which stage to choose instead of stage 8.

**Comment by ewhanson** [comment]
Hey @georgd, I've followed up via the forum post mentioned above.

**Comment by jonasraoni** [comment]
Just confirming that I've met this issue in the wild, it's breaking some deposits for the preservation network.

**Comment by mpbraendle** [comment]
Just experienced that case for a journal that we are trying to submit to PKP PN. This journal was created when we were on OJS 2.4.8.

I can change the file_stage of the "offending" file (7 = fair copy) in the database, but to what should I change it?
Can't the map in getStageNameStageIdMapping() in lib/pkp/plugins/importexport/native/PKPNativeImportExportDeployment.inc.php i just include SUBMISSION_FILE_FAIR_COPY - the XML schema lib/pkp/plugins/importexport/native/pkp-native.xsd  still says that fair_copy would be an allowed value.

**Comment by mpbraendle** [comment]
I decided to change the value to SUBMISSION_FILE_FINAL (6).

**Comment by asmecher** [comment]
@jnugent / @ewhanson, did either of you bash around a PR for this? I'm loath to allocate someone from the dev team to it, as we haven't touched 2.x issues for a very long time -- maybe it's fresher in hosting's memories.

**Comment by ewhanson** [comment]
@asmecher, I had something as a diff somewhere. I'll try and dig it up.

**Comment by jonasraoni** [comment]
FYI I've advised a couple of users of the PKP PN plugin to do the cleanup at the database.

Another issue, perhaps with the same origin, affecting users of OJS 3.3.0, is the absence of submission files (they've got some files on the database, but not on the disk), I'll investigate, but maybe it's already handled by the "foreign key fixes" 🤔

**Comment by asmecher** [comment]
Bumping from 3.4.0 to 3.4.x -- but if there's something small and concrete that we can do for 3.4.0, I'm open to bumping it back.

**Comment by asmecher** [comment]
Thanks, @jonasraoni (and all), I've merged that!
