### ISSUE TITLE
Upgrade optimizations: submission locales, submission event logs, delete old revisions

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7471]
Issue to collect optimization PRs that came out of #6724.

**Comment by ewhanson** [comment]
@asmecher, could you have a look at these PRs? 

They came out of the upgrade issues Elton was having outlined in #6724. Since then I caught another small bug where the upgrade helper function `_fileStageToPath()` was not correctly being called and completed testing with both mysql and postgres9. Thanks!

PRs:
main: #7178
stable-3_3_0: #7179

**Comment by asmecher** [comment]
Thanks, @ewhanson, I hadn't forgotten those -- I'm still pondering which to merge and whether to leave others as patches for users to apply if they run into upgrade problems. But it's helpful to have them gathered here. Where is the `_fileStageToPath` problem? I don't see it in the PRs at a glance.

**Comment by ewhanson** [comment]
Sorry if I doubled up on issues for this. I've been working through a backlog of PRs I needed to test with Postgres and lost track of things a bit.

This should have included OJS PRs as well. I had initially thought everything was included within pkp-lib. The `_fileStageToPath` issue is in the OJS repo in `Upgrade.inc.php`. Thanks!

Additional PRs:
OJS main: #3233
OJS stable-3_3_0: #3234

**Comment by asmecher** [comment]
@ewhanson, the first PR (`main`) is showing test failures and the second needs a rebase to resolve a conflict. Can you take a look?

**Comment by ewhanson** [comment]
@asmecher, they should be good to go now!

For reference, the PRs are:

- `main`: pkp/ojs#3233, #7178
- `stable-3_3_0`: pkp/ojs#3234, #7179

**Comment by asmecher** [comment]
Excellent -- thanks, @ewhanson! Is this issue ready to be closed?

**Comment by ewhanson** [comment]
Yep!
