### ISSUE TITLE
Author localization in CitationStyleLanguagePlugin different from other elements in multilingual settings

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7477]
**Describe the bug**
In a multilingual settings, the author given and family names can be out of sync with the rest of the citation elements (e.g. article title, journal title). This is visible when the locales use different scripts (e.g. English and Arabic).

For publication data like the title, the fallback when no preferred locale is provided in `getLocalizedData` is to next try and use the user's current locale, whereas localized author names (`getLocalizedGivenName`, `getLocalizedFamilyName`) fall back to the submission's set locale.

This leads to a situation where a user views the generated citation with the language set to Arabic, and the publication title, etc. are presented in Arabic and the author names are presented in English.

**What application are you using?**
 OJS 3.2.1, but applicable for `stable-3_3_0` and `main`

**Additional information**

English name appearing where Arabic name should.
![Screen Shot 2021-11-24 at 16 01 44](https://user-images.githubusercontent.com/20844845/143327772-3989f5ee-2657-4436-9811-3e1f920180b4.png)

**Comment by ewhanson** [comment]
Hi @asmecher, this is an issue that came up with a hosting client. Could you have a look at these PRs and see if this fix makes sense? This only seems to come up in rare circumstances in the CitationStyleLanguage plugin and not more broadly. Thanks!

PRs:
`main`: pkp/citationStyleLanguage#85
`stable-3_3_0`: pkp/citationStyleLanguage#86

**Comment by asmecher** [comment]
@ewhanson, it looks at a glance like something might not be working as expected in the `Identity` class based on what you've described. The current locale (`AppLocale::getLocale`) should already be preferred to the default locale; see https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/identity/Identity.inc.php#L149.

**Comment by ewhanson** [comment]
Thanks @asmecher. Based on that, it looks like it's only a problem in `stable-3_2_1` and has since been fixed. Would it be worthwhile for me to create a PR for addressing that against `stable-3_2_1` or is it better to leave it be.

**Comment by NateWr** [comment]
@ewhanson I think we'd be happy to merge a change to `stable-3_2-1` that brought `Identity::getLocalizedFamilyName()` in line with `stable-3_3_0`.

**Comment by ewhanson** [comment]
Hi @NateWr, here's the PR that updates it and the corresponding OJS submodule PR. Thanks.

PRs:
#7478
pkp/ojs#3237

**Comment by asmecher** [comment]
@ewhanson, I've merged those, thanks. Generally I don't think we should be porting non-critical fixes back this far, but if you're needing to do it for the hosting group, then we can make exceptions.
