### ISSUE TITLE
User::getContactSignature() should be removed

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7479]
**Describe the problem you would like to solve**
When an email template supports an `{$editorialContactSignature}` it uses the `User::getContactSignature()`. This uses `User::getSignature()` or, if the user hasn't defined a signature, derives an automated signature from the user details.

The automated signature includes some questionable fields (phone) and misses out other useful ones (like their role in the journal). This is code that could be removed and the signature could be left in the user's control.

**Describe the solution you'd like**
Remove `User::getContactSignature()` and always use `User::getSignature()` instead. If the user has not set up a signature, the email template variable can be empty. When the user is editing the email, they will have an opportunity to complete the email as they like.

**Who is asking for this feature?**
As a dev, I'd like to clean up some old code and simplify the email template variables.

**Additional information**
cc @Vitaliy-1

**Comment by withanage** [comment]
@NateWr 

If I understood correctly, we are removing the function [getContactSignature](https://github.com/pkp/pkp-lib/blob/main/classes/user/User.inc.php#L418) altogether and the references to it ?

**Comment by Vitaliy-1** [comment]
Associated issue: https://github.com/pkp/pkp-lib/issues/7787

**Comment by NateWr** [comment]
@withanage yes, I think that's the idea. Where it is used, we probably want to use `User::getSignature()` or an empty string.

**Comment by withanage** [comment]
@NateWr can you review these PRs

- https://github.com/pkp/pkp-lib/pull/7872
-  https://github.com/pkp/ojs/pull/3376

**Comment by withanage** [comment]
@NateWr 

I sent a submodule update to the PR

https://github.com/pkp/ojs/pull/3376

After doing the changes in 

https://github.com/pkp/pkp-lib/pull/7872

**Comment by withanage** [comment]
@NateWr
I have checked both the OMP and OPS man branches and   could not find any usage of  the  getContactSignature()

**Comment by NateWr** [comment]
Thanks @withanage!
