### ISSUE TITLE
Increase the usage of expressions with combined operators

### ISSUE THREAD

**Issue by elfring** [pkp/pkp-lib#7487]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.arithmetic "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's#(?<target>\$\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+/%^.]|-(?!>)|&(?!&)|\|(?!\|)|\*\*?|<<|>>|\?\?)#$+{target} $+{operator}=#gm' $(find ~/Projekte/pkp-lib/lokal -name '*.php')
```

:crystal_ball: How will development interests evolve further also according to update candidates in 25 lines of this software?

**Comment by asmecher** [comment]
Hi @elfring! Apologies for the late response. Just my personal bias, but I'm not super excited about syntactical changes for their own sake -- they add churn and make it harder for us to e.g. cherry-pick between branches. But if it's easy enough to generate a sample PR for me to look over, and if it does increase quality-of-life for developers, I'll consider it. We're about to enter the beginning of a new dev cycle, so it's probably as good a time as any to consider something like this.

**Comment by elfring** [comment]
:crystal_ball: Will any more developers get into the mood to try a variant of the shown Perl command example out in another test repository for potentially desirable source code transformations?

**Comment by asmecher** [comment]
Folks are welcome to add their two cents, but until the two conditions I set out above are met, I'll close this issue.
