### ISSUE TITLE
Add filters to track submissions within the review stage

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7488]
**Describe the problem you would like to solve**
Currently, the editor can not identify from the submissions list whether a submission in the review stage is waiting for the editor to do something, waiting for reviewers to take action, or waiting for the author to take action. As a result, editors have to jump in and out of the submission's full editorial workflow page in order to track submissions in the review stage.

**Describe the solution you'd like**
Add filters to the submissions list that help an editor identify when they need to take some action and when they are waiting for responses from authors or reviewers.

This is related to https://github.com/pkp/pkp-lib/issues/4172.

**Who is asking for this feature?**
UX research, focus groups and community feedback have identified this as a high priority for journal editors. 

**Additional information**
The following mockup has been prepared following discussion in https://github.com/pkp/pkp-lib/issues/4103.

![filters-review-stage](https://user-images.githubusercontent.com/2306629/143869011-7d972df2-7888-4631-a6a4-21751536ddef.png)

The three filters would correspond to the following review round statues:

- Needs Action (`REVIEW_ROUND_STATUS_PENDING_REVIEWERS`, `REVIEW_ROUND_STATUS_REVIEWS_COMPLETED`, `REVIEW_ROUND_STATUS_REVIEWS_OVERDUE`)
- Revisions Requested (`REVIEW_ROUND_STATUS_REVISIONS_REQUESTED`, `REVIEW_ROUND_STATUS_RESUBMIT_FOR_REVIEW`)
- Revisions Submitted (`REVIEW_ROUND_STATUS_REVISIONS_SUBMITTED`, `REVIEW_ROUND_STATUS_RESUBMIT_FOR_REVIEW_SUBMITTED`)

**Comment by Devika008** [comment]
We’ve integrated filters directly into the primary navigation, and there are no longer any stage-related filters in the filter section, as most can now be managed through the main navigation filters and sorting options on the submissions list. Given these updates, I am closing this issue.

![Image](https://github.com/user-attachments/assets/d77531b4-b3a6-4696-9066-1e08b4b35b8e)

![Image](https://github.com/user-attachments/assets/13661d89-abd1-4deb-8d0a-678e7b6cb148)
