### ISSUE TITLE
Allow editors and editorial assistants to be assigned from the submissions list

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7490]
**Describe the problem you would like to solve**
Managing editors frequently review new submissions and assign an editor. Or they identify submissions at certain stages of the editorial process, like copyediting and production, and assign editorial assistants. To do this, they must open the full submission workflow for each submission. This can be time-consuming when the managing editor is handling several submissions at once.

**Describe the solution you'd like**
Allow the managing editor to assign editors and editorial assistants from the submissions list. A button could open a modal window with the participant assignment workflow.

**Who is asking for this feature?**
This has not been identified as a specific priority, but fits the broader feedback we have that managing editors want to do more from the submissions list when they manage a large number of submissions.

**Comment by Devika008** [comment]
Based on user research conducted in 2022 for the Submission Lists, we found that many users felt the display of all participants, along with a button to assign participants directly from the submission list, made the interface feel overly complex. Users expressed a preference for displaying the "Assign Participant" button only when a submission lacks an assigned editor.

In the updated submission lists, users now see the "Assign Participant" button only when no editor is assigned, and they can also assign additional participants seamlessly through the submission workflow side panel without leaving the dashboard. Given these enhancements, I am closing this issue
