### ISSUE TITLE
Allow editors to assign reviewers from the submissions list

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7491]
**Describe the problem you would like to solve**
During the peer review process, editors must frequently identify review requests that have been declined or ignored and assign replacement reviewers. This process can be tedious because the editor must go to the submission's full workflow in order to view and assign reviewers.

**Describe the solution you'd like**
Allow editors to assign reviewers from the submissions list. A button would open a modal with the workflow to assign a reviewer.

Alongside https://github.com/pkp/pkp-lib/issues/4172, which adds more review information to the submissions list, this would allow editors to complete a common action more quickly.

**Who is asking for this feature?**
This has not been identified as a specific priority, but fits the broader feedback we have that managing editors want to do more from the submissions list when they manage a large number of submissions.

**Comment by Devika008** [comment]
Based on user research conducted in 2022 for the Submission Lists, we found that many users felt the "Assign Reviewers" button, placed along with the reviewer status bubbles directly on the submission list, made the interface feel overly complex. Users expressed a preference for displaying the "Assign Reviewers" button only when a submission lacks an assigned reviewer.

In the updated submission lists, users now see the "Assign Reviewer" button only when no reviewer is assigned. Additionally, they can assign more reviewers seamlessly through the submission workflow side panel without leaving the dashboard. Given these enhancements, I am closing this issue.
