### ISSUE TITLE
Empty Email Variables on System Emails

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#7496]
A hosted client on OJS 3.2 has pointed out that when they add the email variable options for available on the email signature and the system sends an email where there is no actual send (i.e., password reset) it sends an email variable as is. 

![image](https://user-images.githubusercontent.com/50342731/143931485-78847cb7-2c1c-4c3f-974e-a3d045ef2993.png)

![image](https://user-images.githubusercontent.com/50342731/143931688-02ee199c-f37c-4681-8e96-f390dc9012d1.png)

They have suggested the following improvements

- Add a toggle to the email templates indicating if the email signature should be added. 
- Add a 2nd email signature for system emails where there is no sender
-  To not display the template tag if the tag is not defined (preferred)

This issue is also noted on OJS 3.3

**Comment by NateWr** [comment]
Thanks @pmangahis. This looks like it overlaps with https://github.com/pkp/pkp-lib/issues/7225, where we are trying to figure out a more consistent way to handle the signature in emails. I suspect we'll sort this out for 3.4 as part of #7225, but I'll leave this open just in case PS needs to craft a solution for 3.3.x.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib (main): https://github.com/pkp/pkp-lib/pull/8402
tests: https://github.com/pkp/ojs/pull/3604

**Comment by Vitaliy-1** [comment]
Sender-related variables aren't always set. Password reset email is automatically sent from the context/site. I suggest to remove those 2 variables from the context signature

**Comment by Vitaliy-1** [comment]
@NateWr, can you take a look at these?

**Comment by NateWr** [comment]
@Vitaliy-1 it looks like this got merged to `stable-3_3_0` but not to `main`. Is the `main` PR ready for merge?

**Comment by Vitaliy-1** [comment]
Oops
