### ISSUE TITLE
Adjust publication API endpoint

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7509]
This is a placeholder for some work on the publication API endpoint. More details soon.

**Comment by defstat** [comment]
@asmecher @NateWr 

**PR**
pkp-lib: #7530

**Comment by defstat** [comment]
If that be merged, how should we add the change forward until main branch?

**Comment by defstat** [comment]
@NateWr 

The review comments are resolved and the following cases where tested (api side - on Postman)

- Journal Manager can edit publication
- Section Editor can edit publication when stage assignment permits it
- Section Editor can not edit publication when stage assignment permits it
- Author can edit publication when stage assignment permits it
- Author can not edit publication when stage assignment permits it
-Layout Editor (assistant with production stage access) can edit publication when stage assignment permits it
- Layout Editor can not edit publication when stage assignment permits it
- Copyeditor (assistant with no production stage access) can edit publication when stage assignment permits it
- Copyeditor can not edit publication when stage assignment permits it

Also added the OJS PR only for the tests.

**Comment by NateWr** [comment]
Thanks @defstat! Merged to `stable-3_3_0` and ported to `main`.
