### ISSUE TITLE
Use the Accept-Language header when assigning a default language to a new user session

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7512]
**Describe the problem you would like to solve**
When a user accesses an OJS (OMP, OPS) website, OJS creates a session and assigns the primary locale to it. This becomes the default language the user will work with while interacting with the website, until he changes it. However, this may not correspond to the user's preferred language.

**Describe the solution you'd like**
Instead of using the primary locale, we should use the `Accept-Language` header to detect the user's current locale and automatically select that (if available).

**Who is asking for this feature?**
No user requests yet.

**PRs**
- https://github.com/pkp/pkp-lib/pull/10611
- https://github.com/pkp/ojs/pull/3447

**Additional information**
Reference: https://github.com/pkp/pkp-lib/pull/7336#discussion_r760303433

**Comment by NateWr** [comment]
@jonasraoni the link isn't taking me directly to the comment. This happens sometimes as GitHub hides some comments. Can you copy/paste the discussion or reasoning into this issue?

**Comment by asmecher** [comment]
You can access it by clicking "Show Resolved" links until you find the right one (:man_facepalming:) but to save you the trouble it's this conversation:
![image](https://user-images.githubusercontent.com/200411/144602289-1a656b3f-8abf-4c5d-9870-1af823ccbc9a.png)

**Comment by NateWr** [comment]
Ah, so this is during installation. I've updated the issue title/description, thanks!

**Comment by asmecher** [comment]
@NateWr, no, this isn't for during installation -- it's for when a user without a session first hits the OJS website.

**Comment by NateWr** [comment]
Ok, then I'm not understanding the issue description. Can one of you (@jonasraoni, @asmecher) update this with a clearer description of the problem and solution?

**Comment by asmecher** [comment]
@jonasraoni and @NateWr, I've updated the description. @jonasraoni, did I capture what you were proposing?

**Comment by NateWr** [comment]
Got it, thanks!

**Comment by jonasraoni** [comment]
@asmecher PRs
- https://github.com/pkp/pkp-lib/pull/8063
- https://github.com/pkp/ojs/pull/3447

**Comment by jonasraoni** [comment]
@asmecher Some older PRs which I've rebased recently, so they are still ok to be merged.

**Comment by asmecher** [comment]
@jonasraoni I don't think anyone has identified this as a priority so I haven't reviewed it; strategically, I would much rather we considered e.g. adopting Laravel's session management toolset rather than refining our own.

**Comment by asmecher** [comment]
Merged, thanks! This will make a nice addition.
