### ISSUE TITLE
Remove settings pages from DOI management page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7513]
**Describe the problem you would like to solve**
The DOI management page introduced in #6062 duplicates the settings pages under Settings > Distribution > DOIs.

**Describe the solution you'd like**
Remove the settings pages from the DOI management page and add settings for each registration agency to the registration form.

**Who is asking for this feature?**
Split from #6062.

**Additional information**
Currently, the Crossref settings are configured through an old form that's put into the tab. However, this should be converted to a new form and added to the registration agency. The form fields can be part of `IPKPDoiRegistrationAgency`:

```php
use PKP\components\forms\Field;

interface IPKPDoiRegistrationAgency
{
    /**
     * @return Field[]
     */
    public function getSettingsFields(): array
}
```

When no agency is selected, no settings fields show.

![settings-agency-none](https://user-images.githubusercontent.com/2306629/144271938-76246362-8933-448c-8388-34661c87a298.png)

When an agency is selected, its settings fields show (the example below just shows one field but there would be more)

![settings-agency-crossref](https://user-images.githubusercontent.com/2306629/144271999-f4dcf270-da6e-449b-83b8-556e456ec19a.png)

cc @ewhanson

**Comment by bozana** [comment]
Hi @NateWr, Erik and me had a look at this issue today and we are not sure how to solve it best and with minimum effort for 3.4.
The solution suggested here would mean that:
- we would somehow need to get the setting fields from the active or selected plugins, currently Crossref, DataCite, MEDRA (but there could be others out there too) -- they are/have not to be the same
- we would need to save them in context_settings, which again means that we need to take care when the plugin is deleted to delete those settings so that they not accumulate, so we would need to find a mechanism for that
- it would be needed to extend the schema to consider those fields.

The other possibility would be that:
- the plugin would need to extend the form
- the plugin would need to extend the schema

This first two solutions have some unknowns that we need to figure out and seem to be more complicated. We need to take a look at a few things, what is needed, how to solve it like that...

The third possibility would be to 'just' add a tab, for example "Crossref Settings" below the "Registration" tab (when that registration agency is selected) that will open that plugin settings form. 
The problem with this last solution is that a page reload is needed in order to see the new tab.
And we are not sure what all that means from the UI/UX/usability point of view...

What do you think?

**Comment by ewhanson** [comment]
We looked at the possibility of moving the Crossref settings over to the Distribution management page. This would be an easy change to make (especially given the context of the upcoming 3.4 release), but wouldn't address the larger integration of the settings into the application. Here are some screenshots of what that would look like:

![Screenshot 2023-01-31 at 09 19 45](https://user-images.githubusercontent.com/20844845/215835836-574c565d-a63f-4362-abb6-9112ac0fb047.png)

![Screenshot 2023-01-31 at 09 20 10](https://user-images.githubusercontent.com/20844845/215835854-f6c21b4c-9024-4660-a3b9-63ad912d0562.png)

**Comment by NateWr** [comment]
I'd recommend using the theme settings as an example here. All of the themes' fields are passed to the form's state. When the theme field is changed, the form is [updated to show just those fields](https://github.com/pkp/ui-library/blob/main/src/components/Form/context/ThemeForm.vue). 

If you don't want to try that, I'd recommend instead of using the tab that you create link to the settings and load it in a new page. The tab will just be a nightmare to try to show-hide at the correct time. But you can add a `FieldHTML` with a `showWhen` prop to only show it when an agency is selected, and it can open the settings page in a new window.

However, I'd still recommend trying to get the form working. It's not as difficult as it seems, you just need to be willing to pass the fields into a new Vue form, show the right fields at the right time, and post the form to a new API endpoint that knows how to handle it.

Here's a very rough pass at what would be involved:

1. Pass all registration fields into the forms in `PKPDoiRegistrationSettingsForm`:

```php
        $registrationAgencies = collect();

        Hook::call('DoiSettingsForm::setEnabledRegistrationAgencies', [&$registrationAgencies]);

        $options = [
            [
                'value' => Context::SETTING_NO_REGISTRATION_AGENCY,
                'label' => __('doi.manager.settings.registrationAgency.none')
            ]
        ];

        $this->forms = [];

        $registrationAgencies->each(function($agency) use ($options, $forms, $context) {
            $options[] = [
                'value' => $agency->getName(),
                'label' => ...,
            ];

            $forms[$agency->getName()] = $agency->getSettingsForm($context);
        });
```

Then pass the forms into the state in the `getConfig()` method:

```php
    public function getConfig()
    {
        $config = parent::getConfig();
        $config->agencyForms = $this->formFields;
    }
```

2. Create a custom Vue component for the form that loads the correct settings form when an agency is selected (you may need to add a `created` hook that sets up the form when the page is loaded with an agency already selected):

```html
<script>
import PkpForm from '../Form.vue';

export default {
	name: 'RegistrationAgencyForm',
	extends: PkpForm,
	props: {
		agencyFields: Object,
	},
	methods: {
		fieldChanged: function (name, prop, value, localeKey) {
			if (name === 'registrationAgency') {
				this.changeFields(value);
			} else {
				PkpForm.methods.fieldChanged.apply(this, [name, prop, value, localeKey]);
			}
		},
		changeFields: function (agency) {
			this.$emit('set', this.id, {fields: this.fields.slice(0, 1)});
			this.$nextTick(() => {
				const agencyFields = this.agencyFields[agency] || [];
				this.$emit('set', this.id, {
					fields: [
						{
							...this.fields[0],
							value: agency,
						},
						...agencyFields,
					],
				});
			});
		},
	},
};
</script>
```

3. Add a REST API endpoint that receives this data and saves it to the correct plugin settings area:

```php
// In PKPContextHandler, add the route for `editDOIRegistrationAgencyPlugin` at the top, then the following function
    public function editDOIRegistrationAgencyPlugin($slimRequest, $response, $args)
    {

        // Look at PKPContextHandler::editTheme for full list of checks
        // to perform to validate the request.

        $params = $slimRequest->getParsedBody();

        // Check if plugin is valid and activated
        $plugins = PluginRegistry::loadCategory('generic', true);
        $selectedPlugin = null;
        foreach ($plugins as $plugin) {
            if ($params['agency'] === $plugin->getName()) {
                $selectedPlugin = $plugin;
                break;
            }
        }

        // Check it's a registration agency
        if (!is_a($selectedPlugin, /* the registration agency interface */)) {
            return /* $reponse with an error */
        }

        // Validate plugin settings
        $plugin->validateSettings($params);

        // Save settings
        foreach ($params as $param) {
            $plugin->updateSetting($param, ...);
        }

        return $response->withJson(...);
    }
```

Ideally, we will eventually have a generic plugin settings API endpoint. But for now we can just add this one for registration agencies and leave it undocumented. (We do this with a couple of endpoints that we expect to change some day.)

**Comment by ewhanson** [comment]
@NateWr, thanks so much for the skeleton. I'm making my way through it pretty well. I'm working on putting together validation and editing of plugin settings now in the `edit` API endpoint, and I'm wondering what the best approach would be. (I couldn't find any specific examples of themes doing validation, but if you could point me to one, that would be helpful.) It would seem to be a good idea to take advantage of all the validation tools that revolve around the schemas and validator factory. 

I'm leaning towards detailing the plugin settings in a schema somewhere. What do you think of including the schema in an associate array in the plugin code rather than as a separate JSON file? Something like `$plugin->getSettingsSchema()`. Or is there an established way to use schema files for plugins/plugin settings? Thanks!

**Comment by NateWr** [comment]
> What do you think of including the schema in an associate array in the plugin code rather than as a separate JSON file? Something like $plugin->getSettingsSchema()

Yeah, that sounds good. :+1:

**Comment by ewhanson** [comment]
Thanks for the guidance, @NateWr. Would you be able to give this a review? I've also worked in the Crossref settings-related documentation outlined in #8258 into this as well since I already had to redo the settings forms.

PRs:

- `pkp-lib`: #8610
- `ui-library`: pkp/ui-library#253
- `crossref-ojs`: pkp/crossref-ojs#24
- `ojs`: pkp/ojs#3745
- `omp`: pkp/omp#1320
- `crossref-ops`: pkp/crossref-ops#21
- `ops`: pkp/ops#456

**Comment by NateWr** [comment]
@ewhanson I posted reviews for pkp-lib, crossref-ojs, and ojs. (I looked at ui-library but no comments.) I'll finish the rest tomorrow and do a manual test. Not many comments, but I thought you might want to get started.

**Comment by NateWr** [comment]
Looks good @ewhanson. I ran into a few minor issues when doing some manual testing:

1. If the registration agency form has errors, these errors are not cleared when switching the select field back to "none". To reproduce, go to Settings > Distribution > DOI > Registration, select Crossref as the agency, don't fill out Depositor Name, click save, see form errors, select None in registration agency, see that errors still prevent form submission.

2. There are two `FormGroup`s in `DoiRegistrationSettingsForm` when no agency is selected. It looks like one of the groups (`agencySpecificSettings`) may be a duplicate? It's `showWhen` property is `undefined` instead of a `bool`. See screenshot.

![form-groups](https://user-images.githubusercontent.com/2306629/217508927-ff5a6ff9-f223-400d-bf31-53cae2e88e55.png)

3. I got a fatal error when trying to access the DOI management page. These were my settings at the time:

```
ojs=# select * from plugin_settings where plugin_name = 'crossrefplugin';
  plugin_name   | context_id |  setting_name  |   setting_value    | setting_type 
----------------+------------+----------------+--------------------+--------------
 crossrefplugin |          1 | enabled        | 1                  | bool
 crossrefplugin |          1 | depositorName  | PKP                | string
 crossrefplugin |          1 | depositorEmail | example@pkp.sfu.ca | string
 crossrefplugin |          1 | username       |                    | string
 crossrefplugin |          1 | password       |                    | string
 crossrefplugin |          1 | testMode       | 1                  | bool
(6 rows)

ojs=# select * from journal_settings where setting_name LIKE '%doi%';
 journal_id | locale |  setting_name   |    setting_value     | setting_type 
------------+--------+-----------------+----------------------+--------------
          1 |        | doiSuffixType   | default              | 
          1 |        | doiCreationTime | copyEditCreationTime | 
          2 |        | doiSuffixType   | default              | 
          1 |        | doiPrefix       | 10.1234              | 
          2 |        | doiCreationTime | copyEditCreationTime | 
          2 |        | doiVersioning   | 0                    | 
```

And this is the error:

```
[08-Feb-2023 10:31:52 UTC] PHP Fatal error:  Uncaught TypeError: Cannot assign null to property PKP\components\listPanels\PKPDoiListPanel::$versionDois of type bool in /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/components/listPanels/ListPanel.php:68
Stack trace:
#0 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/components/listPanels/ListPanel.php(54): PKP\components\listPanels\ListPanel->set(Array)
#1 /home/nate/Projects/pkp/ojs-main/pages/dois/DoisHandler.php(48): PKP\components\listPanels\ListPanel->__construct('submissionDoiLi...', 'Article DOIs', Array)
#2 /home/nate/Projects/pkp/ojs-main/lib/pkp/pages/dois/PKPDoisHandler.php(96): APP\pages\dois\DoisHandler->getAppStateComponents(Object(APP\core\Request), Array, Array)
#3 [internal function]: PKP\pages\dois\PKPDoisHandler->index(Array, Object(APP\core\Request))
#4 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#5 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#6 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#7 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#8 /home/nate/Projects/pkp/ojs-main/index.php(21): PKP\core\PKPApplication->execute()
#9 {main}
  thrown in /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/components/listPanels/ListPanel.php on line 68
```

I was able to fix it by casting that to `(bool)`, but it may require further investigation. The problem went away when I used the latest `main` dataset.

4. When using the `main` [dataset](https://github.com/pkp/datasets/tree/main/ojs), I got a console error (no tabs) when trying to access the DOI management screen. It seems to be related to having DOIs enabled but no types enabled. Might be good to add some validation to the form so that's not possible. Or at least to update the tests so that the resulting dataset works.

5. Some suggestions for the DOI filter descriptions:

| Filter | Description |
| --- | --- |
| Needs DOI | Any published or unpublished item that does not have a DOI for all enabled published objects. |
| Unpublished | Any unpublished items with assigned DOIs. |
| Unregistered | Any published items with assigned DOIs that have not been deposited with a registration agency. |
| Stale | Any items that have been republished since they were last deposited with a registration agency. They need to be resubmitted to the registration agency to update their metadata records. |

**Comment by ewhanson** [comment]
Hi @NateWr, thanks for the thorough review. I've gone through and addressed everything. Would you mind having another look?

To your questions above:

1) I've updated the form component to clear the errors.
2) I've updated the `showWhen` to only show agency specific settings when a registration agency is selected.
3) If no doiVersioning is set in the database, it would previously return null, which is the error you've run into. This is part of the migration and is set by default on a fresh install, so it shouldn't ever happen, but I've updated the code to return false when the setting comes back as null.
4) I've updated the validation/authorization policy for DOI management to include a check for any enabled DOI types.
5) Thanks! Updated.

**Comment by NateWr** [comment]
Looks good @ewhanson. I ran into two problems:

1. I'm getting the following console error when I interact with the registration agency form:

```
[Vue warn]: Invalid prop: type check failed for prop "errors". Expected Object, got Array 

found in

---> <DoiRegistrationSettingsForm> at lib/ui-library/src/components/Form/context/DoiRegistrationSettingsForm.vue
       <Tab> at lib/ui-library/src/components/Tabs/Tab.vue
         <Tabs> at lib/ui-library/src/components/Tabs/Tabs.vue
           <Tab> at lib/ui-library/src/components/Tabs/Tab.vue
             <Tabs> at lib/ui-library/src/components/Tabs/Tabs.vue
               <Root>
```

This usually happens when an empty assoc array gets passed in to a prop. So it is expecting something like `['a' => 'b']` which would convert to a JS object but gets `[]` which converts to a JS array.

The form still works but would be good to clean up if it's a quick fix.

2.  I'm unable to save the registration agency form. This is happening because `$contextParams` in `PKPContextHandler` is empty. As a result, it's returning 200 early here:

```php
if ($contextParams[Context::SETTING_CONFIGURED_REGISTRATION_AGENCY] === null) {
    return $response->withStatus(200);
}
```

I believe I sent you down the wrong path with my suggestion. The problem stems from here:

```php
$contextParams = array_intersect(
    $schemaService->getFullProps(PKPSchemaService::SCHEMA_CONTEXT),
    $params,
);
```

The `$schemaService` is returning an array, `['a', 'b']`, but `$params` is an assoc array, `['a' => ..., 'b' => ...]`. I think `array_intersect` won't work here, but maybe `array_intersect_key` will? https://www.php.net/manual/en/function.array-intersect-key.php

You would probably need to do something like `array_flip($schemaService->getFullProps(PKPSchemaService::SCHEMA_CONTEXT))` to turn the values into array keys for comparison with `$params`.

Lastly, take a close look at how `array_intersect_key` works. It might only take the values from the first array, in which case you'd need to use `$params` as the first argument to retain the request param info. I'm not 100% sure here, but maybe take a look.

Otherwise, looks good. :+1:

**Comment by ewhanson** [comment]
Thanks @NateWr. Took care of the invalid prop type check and updated the sanitizing of props using `array_intersect_key` as you suggested. Feel free to have another look; otherwise, it's ready for merge on my end.

**Comment by NateWr** [comment]
All merged to `main`. :tada:
