### ISSUE TITLE
Remove the DOI preview table from the publishing preview

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7516]
**Describe the bug**
The DOI preview still appears when publishing a submission. This no longer works in all cases because a DOI might not have been created yet.

**To Reproduce**
1. Go to any submission ready for publication.
2. Click on Publication
3. Click on Publish
4. See screenshow below.

![doi-preview](https://user-images.githubusercontent.com/2306629/144276122-aed4bf0f-aa12-4381-a72d-e83b5550a5ff.png)

**What application are you using?**
This is part of #6062 and is not yet merged to `main`.

**Additional information**
cc @ewhanson

**Comment by ewhanson** [comment]
Hey @bozana, this is a quick PR to remove the DOI section from the `PublishForm`. Could you have a look? Thanks.

PR: 
- pkp/ojs#3692

**Comment by bozana** [comment]
This looks good to me. It can be merged... :-) Thanks a lot!

**Comment by ewhanson** [comment]
Thanks. Done!

**Comment by wrapper** [comment]
For the sake of anyone googling hopelessly in the future, this *appears* to have fixed the PHP error I was encountering when hitting Schedule for Publication on submissions in OJS v3.4:

`PHP Fatal error:  Uncaught Error: Call to undefined method Closure::getDoi() in /ojs/public/classes/components/forms/publication/PublishForm.inc.php:170
Stack trace:
#0 /ojs/public/classes/components/forms/publication/PublishForm.inc.php(114): APP\components\forms\publication\PublishForm->_getDoiMessage()
#1 /ojs/public/lib/pkp/controllers/modals/publish/PublishHandler.inc.php(97): APP\components\forms\publication\PublishForm->__construct('https://stolent.../', Object(APP\publication\Publicatio$
#2 [internal function]: PublishHandler->publish(Array, Object(APP\core\Request))
#3 /ojs/public/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#4 /ojs/public/lib/pkp/classes/core/PKPComponentRouter.inc.php(288): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#5 /ojs/public/lib/pkp/classes/core/Dispatcher.inc.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#6 /ojs/public/lib/pkp/classes/core/PKPApplication.inc.php(376): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#7 /ojs/public/index.php(70): PKP\core\PKPApplication->execute()
#8 {main}
  thrown in /ojs/public/classes/components/forms/publication/PublishForm.inc.php on line 170`
