### ISSUE TITLE
Allow users to mark DOIs unregistered

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7518]
**Describe the problem you would like to solve**
As part of the new DOI management page in #6062, editors can bulk mark items as registered. It's possible that an editor will mark a submission registered by accident and there is no way to undo this.

**Describe the solution you'd like**
Implement a bulk action to mark items unregistered.

If possible, there should probably be bulk actions for status that can be assigned by a user (ie - not automatic). These would be:

- Set Unregistered (in case it was mistakenly marked registered)
- Set Registered (same as "Mark Registered")
- Set Stale (in case they want to force an automatic deposit to redeposit this item)

**Who is asking for this feature?**
This is part of #6062.

**Additional information**
cc @ewhanson

**Comment by ewhanson** [comment]
PRs:

- `ui-library`: pkp/ui-library#208
- `pkp-lib`: pkp/pkp-lib#8029
- `ojs`: pkp/ojs#3437

**Comment by ewhanson** [comment]
Hey @NateWr, I've gotten all the DOI tests consolidated and updated, so this is ready for review. Could you have a look? [PRs linked above.](https://github.com/pkp/pkp-lib/issues/7518#issuecomment-1164988628) Thanks!

**Comment by NateWr** [comment]
Looks good @ewhanson! I left a few comments but nothing critical. I did a functional test and didn't find any problems. The error messaging really helps! :+1:

**Comment by ewhanson** [comment]
Hey @NateWr, I've gotten your feedback worked in and got the tests passing. Could you have another look? [PRs linked above](https://github.com/pkp/pkp-lib/issues/7518#issuecomment-1164988628). Thanks!

**Comment by NateWr** [comment]
Looks good. I've left a few small comments. I haven't done a functional test but I think you've got a good handle on that and this will get tested well before 3.4, so happy to merge once the final comments are addressed.

**Comment by ewhanson** [comment]
Hey @NateWr, thanks for the feedback. These should be ready to go now. The tests are all failing on the DC OAI tests, but I've run all the rewritten tests locally. Thanks!

**Comment by NateWr** [comment]
Great, @ewhanson. I've merged those PRs now. I also made a couple of commits you might want to be aware of: https://github.com/pkp/ui-library/commit/eb5f5478f6eb9d2a8dacf8194b5697676ed17fb2 and https://github.com/pkp/pkp-lib/commit/e36e72df21bdc1d7048b0267beb6836b08bdaf0a.

Finally, I have temporarily skipped the OAI tests in the `main` branch, so that we can make sure the tests are passing alright. Let's keep an eye on these builds in case there's a failure related to the DOI/Crossref tests:

- https://app.travis-ci.com/github/pkp/ojs/builds/254175208
- https://app.travis-ci.com/github/pkp/omp/builds/254175309
- https://app.travis-ci.com/github/pkp/ops/builds/254175378

I'll leave this issue open until the tests are passed.

**Comment by NateWr** [comment]
DOI.spec.js passed in OJS and OPS. Still having test issues in OMP so it hasn't run, but happy to close this.
