### ISSUE TITLE
Document new DOI endpoints in the API documentation

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7519]
**Describe the problem you would like to solve**
Several new API endpoints were added for managing DOIs as part of #6062. These are not documented in the `swagger-source.json` file.

**Describe the solution you'd like**
Document all endpoints in the `swagger-source.json` file.

cc @ewhanson

**Comment by bozana** [comment]
Deferring for after RC1...

**Comment by ewhanson** [comment]
Hey Nate, I've updated the DOI API documentation. Could you have a look? Thanks!

PRs:

- #8793
- pkp/ojs#3831

**Comment by NateWr** [comment]
Thanks @ewhanson! I recently merged in some changes to the `swagger-source.json` file. I don't think it should cause too many problems for you, but have a look at the new `x-tagGroups` property:

https://github.com/pkp/ojs/blob/main/docs/dev/swagger-source.json#L19-L59

Let me know once you've rebased and I'll give the docs a review.

**Comment by NateWr** [comment]
This was included in #8844, which has been merged to `main`. Thanks @ewhanson!
