### ISSUE TITLE
Increase issue galley label length to match publication galley labels

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7520]
**Describe the bug**
There's a discrepancy in the length between issue galley labels (varchar 32) and publication galley labels (varchar 255).  Can issue galley labels please also get the longer definition?

OJS 3.3.0.8

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/3242

To apply this to `stable-3_3_0`, copy the migration class file (`I7250_...`) into the same directory in your install and run the following command:

```
php lib/pkp/tools/migration.php APP\\migration\\upgrade\\v3_4_0\\I7520_IssueGalleyLabelLength up
```
