### ISSUE TITLE
Can save DOI settings with no suffix selected

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7523]
**Describe the bug**
With the new DOI settings form introduced in #6062, it is possible to save the form with no suffix selected (or to send an empty value to the REST API). When DOIs are enabled, the suffix setting should be required to be one of the expected types.

(This can be done with the "in:a,b,c" validation type in the schema files.)

**To Reproduce**
1. Make sure there is no existing setting for the suffix in the database.
2. Go to Settings > Distribution > Dois
2. Enable DOIs
3. Save form
4. See lack of validation error

**What application are you using?**
3.4 pre-release (`main` after #6062 is merged)

**Additional information**
cc @ewhanson

**Comment by NateWr** [comment]
We discussed this today and we think it's best if DOIs are enabled by default, and only for the publication, when a new journal is created. 

Until the journal has entered a DOI prefix, a `<notification>` should be shown at the top of the DOIs screen that says:

> DOI's can not be assigned unless you provide the journal's assigned DOI prefix. <a href="#">Add DOI Prefix</a>.

(Link going to the DOI settings page)

**Comment by ewhanson** [comment]
Hi @bozana, could you have a look at this one? It adds a warning to the DOI management page if the plugin is configured but does not have a prefix configured (which will be the default on a fresh installation). It also adds checks and removes the option to assign DOIs when no prefix is assigned. Thanks!

PRs:

- `pkp-lib`: #8538
- `ui-library`: pkp/ui-library#249
- `ojs`: pkp/ojs#3699
- `omp`: pkp/omp#1302
- `ops`: pkp/ops#436

**Comment by bozana** [comment]
Hi @ewhanson, just one question and one comment :-)
(And maybe another question: What happens when someone tries to export or register an unasigned DOI? Are we still planing to consider it i.e. to differentiate between unassigned and unregistered?)

**Comment by ewhanson** [comment]
Thanks, @bozana! All updated. Let me know if there's anything else needed before merge.

**Comment by bozana** [comment]
Hi @ewhanson, it can be merged :-)

**Comment by ewhanson** [comment]
Merged!
