### ISSUE TITLE
All DOI endpoints that perform actions should be PUT methods

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7525]
**Describe the problem you would like to solve**
New API endpoints were added for DOIs in #6062. Several of these perform actions that do not create new objects but modify existing ones. These are currently `POST` methods but should be `PUT` to follow HTTP conventions.

**Describe the solution you'd like**
Change all API endpoints for these actions (eg - depositAll, exportSubmissions, etc) to `PUT` methods. The DOI list panel will need to be updated as well to reflect this change.

**Who is asking for this feature?**
This is part of #6062.

**Additional information**
cc @ewhanson

**Comment by ewhanson** [comment]
Hey @asmecher, could you have a look at these PRs? It's mostly reshuffling the HTTP verbs with a few response code changes. Thanks!

PRs:

- `pkp-lib`: #7998
- `ui-library`: pkp/ui-library#205
- `ojs`: pkp/ojs#3422
- `omp`: pkp/omp#1138
- `ops`: pkp/ops#294

**Comment by ewhanson** [comment]
Hey @NateWr, could you have a look at [these PRs](https://github.com/pkp/pkp-lib/issues/7525#issuecomment-1151429481)? I've recently rebased/got the tests passing again. Thanks!

**Comment by NateWr** [comment]
Looks good! All merged, thanks!
