### ISSUE TITLE
Cancelling or unassigning a reviewer who is also an editor should restore editor's access to submission

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#7534]
**Describe the problem you would like to solve**
A journal editor assigns themselves as a reviewer to a submission, either as a test or by mistake. This locks them out of editorial controls. However even when cancelled or unassigned as a reviewer, they still can't get control back - they keep receiving the "role does not have access" error.

Apparently an incoming review may unlock that access based on [this Forum post](https://forum.pkp.sfu.ca/t/editor-as-well-as-reviewer-with-trouble-reading-other-reviewers-reviews/30696/6) but that's not a reliable solution.

**Describe the solution you'd like**
There should be a mechanism for an editor to remove themselves from the reviewer role and regain access to the submission. 

**Who is asking for this feature?**
PKP|PS client on 3.3.0.8
Forum users  - https://forum.pkp.sfu.ca/t/editor-as-well-as-reviewer-with-trouble-reading-other-reviewers-reviews/30696

**Comment by librariam** [comment]
@NateWr I did more testing and I should amend my initial ticket description - the locking out happens only in the scenario where the editor/reviewer declines the review (details below). In my other tests, where the editor/reviewer either assigned themselves as a reviewer and then unassigned or accepted to review and then cancelled, the submissions dashboard provided an option to re-gain editorial access via the prompt _"You have been assigned an editorial role for this submission. Would you like to access the Editorial workflow?"_

**Steps to replicate the editor being locked out of a submission (tested OJS 3.3.0.8):**
1. Start logged into an account that has JM/JE and reviewer roles
2. Assign yourself to a submission as a JE and send it to review
3. Add yourself as a reviewer (OJS will show a warning that you are an editor and you need to "unlock" the reviewer option)
4. Go to your submissions and access this submission as a reviewer (notice also there is a prompt to _access the Editorial workflow_ instead)
5. Decline to review
6. Go back to your submissions and try accessing this submission again. You get an error _"The current user is not assigned as a reviewer for the requested document"_. There is **no** prompt to access the Editorial workflow instead.
7. Have another JE cancel you as a reviewer
8. Repeat step 6. You are still getting the same error and can't access the editorial workflow for this submission.
9. Have another JE remove you as an editor from the submission.
10. Repeat step 6. You are still getting the same error and can't access the editorial workflow for this submission.

As a bonus, I've tested whether an incoming review would "unlock" the submission as per [this Forum post](https://forum.pkp.sfu.ca/t/editor-as-well-as-reviewer-with-trouble-reading-other-reviewers-reviews/30696). It worked in one of my tests but not in the other, both were done after all 10 steps.

Considering the reviewer declined to review, I wonder if the above lock out could be by design? But I can also see an editor who assigned themselves as a reviewer by mistake attempting to decline the review as a way to undo their mistake and gain editorial access again.

**Comment by NateWr** [comment]
Thanks @librariam! Very helpful reproduction steps. I was able to reproduce the problem and fix the access issue.

Now, after the editor's review assignment has been declined or cancelled, they will be sent to the editorial workflow when they click the "View" button. However, if they were assigned an anonymous review, they still won't see the author of the submission in the submissions list. It will just be listed by the title.

Fixing this carries a risk of accidentally exposing author information to an anonymous reviewer, so I don't want to add it to the 3.3.0-x line of stable releases. I think we can solve that problem better with #4975, where the UI will be clearer and the code will be more straightforward and less likely to expose data meant to be kept anonymous. To roll that out to the 3.3 or even 3.4 releases will require more testing work than I'd like to put into this right now.

PR:
https://github.com/pkp/pkp-lib/pull/7544

Tests:
https://github.com/pkp/ojs/pull/3251

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and ported to `main`.
