### ISSUE TITLE
Task list is not sorted with most recent tasks at the top

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#7538]
**Describe the bug**
Before 3.3, tasks where "order by date_created desc" : for our users, it was better than now in 3.3, because you can immediately see what is the last event in your tasks list.

But maybe there is a reason behind this new behavior ?
Thank you in advance
 

**What application are you using?**
 3.3.0-8

**Additional information**
https://github.com/pkp/pkp-lib/commit/f34c440#r61568503

**Comment by NateWr** [comment]
@forgive38 can you please add some reproduction steps so that a developer who is assigned to work on it can quickly set up a working test environment?

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/7634

Tests:
https://github.com/pkp/ojs/pull/3282

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and ported to `main`.
