### ISSUE TITLE
Permissions error when uploading a file to a discussion

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#754]
When I try to upload a file to a discussion from the view discussion modal I get the following access permissions error:

`##user.authorization.invalidReviewRound##`

Logged in as editor (`dbarnes`)

**Comment by asmecher** [comment]
What stage are you on when you try to do the upload? (e.g. internal review?)

**Comment by NateWr** [comment]
Error occurs on Internal and External Review. The upload dialogue loads up for Submission and Editorial stages.

**Comment by asmecher** [comment]
Fixed:
https://github.com/pkp/ojs/commit/05cfbcd28bbb442e89843f6b6a9e345e303f2be7
https://github.com/pkp/omp/commit/e167e1414d51fbabb1aa83fbbf48dc401c6f2213
https://github.com/pkp/pkp-lib/commit/0ab739e6a9e412ed40c922d2b80f6dc55ac5f89e

Nate, let me know if you have any more trouble with this.

**Comment by NateWr** [comment]
The upload modal opens now. However, I get an error when I try to upload a file. The ajax `post` request returns a `500` error:

```
POST http://192.168.0.8/omp/index.php/publicknowledge/$$$call$$$/wizard/file-upl…bmissionId=2&stageId=3&fileStage=18&reviewRoundId=&assocType=520&assocId=1 500 (Internal Server Error)
```

The following JSON is returned:

```
{"status":false,"content":"Missing or invalid component!","elementId":"0"}
```

And the following error message is displayed.

```
HTTP Error. 
Upload URL might be wrong or doesn't exist.
```

**Comment by asmecher** [comment]
Sorry, Nate, I still can't duplicate this. Can you give me the specifics you're working with? If the OMP test database, what submission, and what user account? Is this the modal where you create a discussion, or the one you use after that to compose additional replies? (They're subtly different.)

**Comment by NateWr** [comment]
Sorry for the late response. I just ran through a test locally and was unable to reproduce, so must have been something off in my last test.

**Comment by asmecher** [comment]
No worries; I'll keep an eye out for trouble here too.
