### ISSUE TITLE
PHP Warning in error log

### ISSUE THREAD

**Issue by hammadkhan07** [pkp/pkp-lib#7542]
I am working with OJS last i installed in Feb 2021 the latest version currently im facing a php warning in my error log i need to know exactly what caused and what is it regarding to 

PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'PKPComponentRouter' does not have a method 'getRequestedPage' in /home/ylg85dki0kn4/public_html/GATRJournals/submissions/ojs/lib/pkp/classes/core/PKPRequest.inc.php on line 760

Any help regarding this will be much appreciated Thanks.

**Comment by asmecher** [comment]
@hammadkhan07, could you include the exact version number of OJS you're using? What URL are you requesting when this warning appears?

**Comment by NateWr** [comment]
Please provide all of the information requested in the issue template:

> **Describe the bug**
> Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **What application are you using?**
>  OJS, OMP or OPS version X.X.X
> 
> **Additional information**
> Please add any screenshots, logs or other information we can use to investigate this bug report.
