### ISSUE TITLE
Enabling "display_errors" in config.inc.php may break AJAX/JSON request

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#7548]
**Describe the bug**
I encountered the bug when opening the URN plugin settings dialogue failed with "Failed Ajax request or invalid JSON returned.". The DOI plugin just worked fine on the same installation.

The Ajax request returned with status 200 OK. However, Raw message looks like this:
`
<br />
<b>Warning</b>:  Declaration of URNSettingsForm::fetch($request) should be compatible with Form::fetch($request, $template = NULL, $display = false) in <b>/var/www/html/ojs/plugins/pubIds/urn/classes/form/URNSettingsForm.inc.php</b> on line <b>106</b><br />
{"status":true,"content":"<div id=\"description\">Bitte konfigurieren Sie das URN-Plugin, damit Sie URN in OJS verwalten und benutzen k\u00f6nnen:<\/div>\n\n ... ### ... <p><span class=\"formRequired\">Mit * gekennzeichnete Eingabefelder sind Pflichtfelder.<\/span><\/p>\n","elementId":"0","events":null}
`

The part "... ### .." I removed to shorten this post.

The issue is that because "display_errors" is enabled in config.inc.php the PHP warning is put out before start of the json message.

Expected behaviour would be that the PHP error message is included in the content part of the json message.

**What application are you using?**
 OJS version 3.3.0-8

**Comment by jonasraoni** [comment]
Hi @ronste!

This behavior is expected. This setting shouldn't enabled unless you're trying to debug/fix something in the system.
The warnings are real, but they are benign (in the sense that they won't break the system when they are hidden).

Therefore I'm closing this issue.

**Comment by ronste** [comment]
Hi @jonasraoni ,

sorry, but I don't see how breaking a form that works when the "display_error" feature is disabled could be expected behaviour?
What do you expect to gain breaking the URN settings form (or any other Ajax request in case it coincides with a PHP warning) instead of just displaying the warning at the top of the form as is done on normal page loads? 

Apart from that. I am debugging/developing a plugin. That's why I enabled this feature.

Anyhow, its not a big issue that only affects developers under special circumstances. It just took me a couple of hours to find out why the URN settings form fails loading. Thought I could save others some time.

Best wishes,
Ronald

**Comment by jonasraoni** [comment]
I understand your pain. In a perfect scenario, all of these warnings shouldn't exist, but they still do, and the fact is that enabling the `display_errors` will just slow you down.

If you just want to ensure there's no unexpected warnings in your code, I suggest watching the error log and/or using `xdebug`.

To fix the `display_errors` in the way that you expect, it would require some workarounds (e.g. caching the output/adding a `set_error_handler()`) to catch the error, then make it appear in a "good spot", but the good spot is already available (the error log).
