### ISSUE TITLE
pnotify error panels appear after fixed when adding a new note

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#756]
Seen in OMP > Review > Discussion > Add Note > Try to add empty note to cause error. Fix the error, then save. A pnotify error panel will appear after the save is successful and the modal is closed.

**Comment by asmecher** [comment]
@NateWr, I wasn't seeing quite the same behavior as you, but could you try re-creating the problem with the above commit to master included? (Update your `lib/pkp` checkout.)

**Comment by NateWr** [comment]
I was able to reproduce the problem with the latest master. Here's a gift showing it.

![pnotify-panels-error](https://cloud.githubusercontent.com/assets/2306629/10063000/c0e966b8-6260-11e5-988d-e2ed11eaeba6.gif)

**Comment by asmecher** [comment]
Ah, thanks. Will look at it.

**Comment by asmecher** [comment]
Fixed, thanks!
