### ISSUE TITLE
Multiple submissions on submission grid

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#7560]
**Describe the bug**
There are cases where the Dashboard submission grid displays the the same submission multiple times

**To Reproduce**
1. As a Journal Manager, go to Dashboard -> Users & Roles
2. Edit your user (the journal manager) and give your user the Editor Role.
3. Go to Dashboard -> Submissions
4. As a Journal Manager create a new submission (selecting Journal Manager as submission role [Submit As**])
5. Finalize the submission and go to Dashboard -> Submissions
6. You will see 2 grid rows with the same submission (the submission has 2 stage assignments -> Manager and Editor)
7. Go to Dashboard -> Users & Roles
8. Edit your user and give your user the Author Role.
9. Go to Dashboard -> Submissions
10. Select the newly created submission (step 4)
11. At stage assignments add as author your self
12. Go to Dashboard -> Submissions
13. You will see 3 grid rows with the same submission (the submission has 3 stage assignments -> Manager, Editor and Author)

**What application are you using?**
 OJS, OMP or OPS main branch (3.4 pre-release)

**Additional information**
![image](https://user-images.githubusercontent.com/560456/146734999-c8ef3de2-8f1a-4919-a7d4-6e56874a5ea3.png)

It seems that the cause of that is multiple stage assignments for the same user. The query that fetches the data is 
```
select *
from `submissions` as `s` 
left join `publications` as `po` on `s`.`current_publication_id` = `po`.`publication_id` 
left join `stage_assignments` as `sa` on `s`.`submission_id` = `sa`.`submission_id` and `sa`.`user_id` in (1) 
left join `review_assignments` as `ra` on `s`.`submission_id` = `ra`.`submission_id` and `ra`.`declined` = 0 and `ra`.`cancelled` = 0 and `ra`.`reviewer_id` in (1) 
where `s`.`context_id` in (1) 
and `s`.`status` in (1) 
and (`sa`.`stage_assignment_id` is not null or `ra`.`review_id` is not null) 
order by `s`.`date_submitted` desc 
limit 30
```

which will return multiple lines for the same submission if the user is assigned to different roles/stages (because of `left join stage_assignments as sa on s.submission_id = sa.submission_id and sa.user_id in (1)` )

https://github.com/pkp/pkp-lib/blob/main/classes/submission/Collector.inc.php#L294-L297

**Comment by NateWr** [comment]
Thanks @defstat. Can you add to your reproduction steps how to create this condition in the database? (ie - create the user roles and make the assignments)

**Comment by defstat** [comment]
@NateWr In my installation I can reproduce it like so:
1. As a Journal Manager, go to Dashboard -> Users & Roles
2. Edit your user and give your user the Editor Role.
3. Go to Dashboard -> Submissions
4. As a Journal Manager create a new submission (selecting Journal Manager as submission role)
5. Finalize the submission and go to Dashboard -> Submissions
6. You will see 2 grid rows with the same submission (the submission has 2 stage assignments -> Manager and Editor)
7. Go to Dashboard -> Users & Roles
8. Edit your user and give your user the Author Role.
9. Go to Dashboard -> Submissions
10. Select the newly created submission (step 4)
11. At stage assignments add as author your self
12. Go to Dashboard -> Submissions
13. You will see 2 grid rows with the same submission (the submission has 2 stage assignments -> Manager, Editor and Author)

If you need anything else I can investigate more.

**Comment by NateWr** [comment]
Thanks, I was able to reproduce the problem following those steps. I can confirm it's not reproducible in `stable-3_3_0`.

**Comment by asmecher** [comment]
@defstat and @NateWr, I replicated the problem locally and confirmed that the attached commit (direct to `main`) solved it, but please have a quick look if you have a moment: https://github.com/pkp/pkp-lib/commit/8434802adad899a39cb8708f98bd6439f89c1cdc

**Comment by Vitaliy-1** [comment]
@asmecher, This breaks tests. With subquery join, this `where` statement points to the column which doesn't exist: https://github.com/pkp/pkp-lib/blob/8434802adad899a39cb8708f98bd6439f89c1cdc/classes/submission/Collector.inc.php#L354

What I can't understand here, is the purpose of this left join: https://github.com/pkp/pkp-lib/blob/8434802adad899a39cb8708f98bd6439f89c1cdc/classes/submission/Collector.inc.php#L301-L306
It translates into something like:
```sql
SELECT `sa`.`submission_id` FROM `stage_assignments` AS `sa` 
LEFT JOIN `review_assignments` AS `ra` 
ON `sa`.`submission_id` = `ra`.`submission_id` AND `ra`.`declined` = 0 AND `ra`.`cancelled` = 0 AND `ra`.`reviewer_id`  IN (27)
```
Should it be something like?
```sql
SELECT `sa`.`submission_id` FROM `stage_assignments` AS `sa` 
LEFT JOIN `review_assignments` AS `ra` 
ON `sa`.`submission_id` = `ra`.`submission_id` 
WHERE `ra`.`declined` = 0 AND `ra`.`cancelled` = 0 AND `ra`.`reviewer_id` IN (27)
```
If the idea is to filter assigned editors and reviewers, the `assignTo` filter should be changed as it only filters editors.

**Comment by Vitaliy-1** [comment]
PR to pkp-lib: https://github.com/pkp/pkp-lib/pull/7566
tests: https://github.com/pkp/ojs/pull/3260

**Comment by asmecher** [comment]
@Vitaliy-1, whoops, thanks for catching that. I think the purpose of the problem line:

https://github.com/pkp/pkp-lib/blob/8434802adad899a39cb8708f98bd6439f89c1cdc/classes/submission/Collector.inc.php#L354

...is to avoid exposing e.g. author identities to users who are assigned as reviewers via the keyword search mechanism. To do that, I think it'll be necessary to add a join alongside the include submissions that the user is assigned to as e.g. a section editor, but *exclude* submissions they may be assigned to as a reviewer. The right fix for that, preserving the current logic, would be to add a join in the keyword search subquery like the one used in the submission assignment subquery:

```php
$q->leftJoin('review_assignments as ra', function ($table) {
    $table->on('sa.submission_id', '=', 'ra.submission_id');
    $table->on('ra.declined', '=', DB::raw((int) 0));
    $table->on('ra.cancelled', '=', DB::raw((int) 0));
    $table->whereIn('ra.reviewer_id', $this->assignedTo);
});
```

Does that make sense to you too? Would you like me to run that through tests?

**Comment by Vitaliy-1** [comment]
Ahh, yes, I can reproduce the problem you describe on the branch I've experimented with. If you think that it will fix it, please go ahead.

**Comment by asmecher** [comment]
@Vitaliy-1, I've just pushed up a fix for this in `pkp-lib`; it tests fine locally and I'll watch Travis.

**Comment by asmecher** [comment]
Hrm, working with PostgreSQL but not MySQL. I'm looking into it.

**Comment by asmecher** [comment]
Hrm, the MySQL problem was introduced after I broke the tests by some other change. I'll track it down as penance for breaking the tests :)

**Comment by asmecher** [comment]
@Vitaliy-1, the tests on `main` actually work -- the MySQL failure was a hiccough in the Travis infrastructure or something. You should be good to carry on.

**Comment by NateWr** [comment]
A quick follow-up to explain the `assignTo` filter. Unfortunately, that does mean "assigned to in an editorial role or as a reviewer". That's used to deliver the "My Queue" submissions lists, which includes submissions assigned as an author, editorial role, or a reviewer.

Once #4975 is implemented, we'll be able to clean up some of this complicated logic (as well as all the code that anonymises submission data).
