### ISSUE TITLE
typo in /locale/it_IT/submission.po (branch stable-3_2_1)

### ISSUE THREAD

**Issue by bolelligallevi** [pkp/pkp-lib#7565]
Hi, in line 1530 [here](https://github.com/pkp/pkp-lib/blob/stable-3_2_1/locale/it_IT/submission.po) "TQuesto" has to be changed to "Questo".
Best regards
Stefano

Row 1530: msgstr "<a rel=\"license\" href=\"https://creativecommons.org/licenses/by/4.0/\"><img alt=\"Creative Commons License\" src=\"//i.creativecommons.org/l/by/4.0/88x31.png\" /></a><p>TQuesto lavoro è fornito con la licenza <a rel=\"license\" href=\"https://creativecommons.org/licenses/by/4.0/\">Creative Commons Attribuzione 4.0 Internazionale</a>.</p>"

**Comment by jonasraoni** [comment]
Hi @bolelligallevi!

FYI in case you find translating issues within the latest OJS versions, you can contribute with fixes directly here:
https://translate.pkp.sfu.ca/languages/it_IT/ojs/ (there's a search tab to find a specific text).

**Comment by bolelligallevi** [comment]
Hi @jonasraoni, this typo has been fixed in current version, i can use weblate for older versions as 3.2.1?
I'm suggesting to correct because 3.2.1 is not so old and maybe will be downloaded for some time.
Best regards

**Comment by jonasraoni** [comment]
As far as I can tell, Weblate just keeps the latest translations, so this will probably require a manual update... I'll create a PR to fix this, then we'll discover :)

**Comment by jonasraoni** [comment]
@asmecher I'm not sure how far we're going with backwards fixes, so I've created the PRs mostly to raise a discussion.
PRs:
https://github.com/pkp/pkp-lib/pull/7573
https://github.com/pkp/ojs/pull/3261
https://github.com/pkp/ops/pull/211
https://github.com/pkp/omp/pull/1045

**Comment by asmecher** [comment]
@jonasraoni, no harm in cherry-picking a trivial typo fix like this back to earlier releases -- but it's not worth investing more than a few seconds in, since we're not planning further releases e.g. from `stable-3_2_1`.
