### ISSUE TITLE
Remove deprecated PHP code

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7576]
**Describe the problem you would like to solve**
Remove deprecated PHP features from the code base.

**Describe the solution you'd like**
Pass through the deprecated features, available at the PHP manual, and remove/replace them.

**Who is asking for this feature?**
Developer

**Comment by NateWr** [comment]
@jonasraoni do you have some specific deprecated features in mind? If not, I might close this unless we have some more details to work from. I think we're all for removing deprecated code, but I'd like to keep the issues for specific tasks.

**Comment by jonasraoni** [comment]
I've created this issue to move some code from another PR, but the code is already merged...

I was thinking about reviewing the PHP's changelog to search for other issues, but then I found a better solution, which I'll investigate, so let's close it for now =]
