### ISSUE TITLE
Reviewer grid needs UI/UX overhaul

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#758]
There's a whole lot going on here in terms of various states and state-dependent actions. I think this is a good candidate for cleaning up for OMP 1.2 because some changes in the UI swept away the old icon s which were used to display this status.

I think we might do better by adding a column so there are three in the grid:

- Reviewer
- Available action (nothing, send reminder, accept, unconsider)
- Current status (incomplete, overdue, submitted (ie - unread), awaiting acceptance)

Right now the info and functions of the last two columns get intermingled in ways that aren't always very clear. This shouldn't be too difficult and I can probably do it myself if you'd like.

**Comment by asmecher** [comment]
SI has requested that we add the review due date, when one is set, to the grid view. Worth considering, no decision made yet.

**Comment by NateWr** [comment]
Sounds sensible.

**Comment by NateWr** [comment]
@bozana I just realized that we have this issue which covers similar terrain to what we discussed the other day. I'd say let's go with whatever we settled on after talking and ignore this issue.

Does that sound good? Where's the issue you're working on which impacted the reviewer grid?

**Comment by bozana** [comment]
@NateWr, I think that this issue builds upon my changes i.e. there is no conflict between them: I only added the new action in the second, expended raw and these are changes for the first row. The "Reviewer" and "Available action" column from above are already there. You said you would style them i.e. the "Available action" column. The column "Current status" with the due date should be added. I think I could make a pull request for the other issue https://github.com/pkp/pkp-lib/issues/788 today, but probably late in the evening first.

**Comment by bozana** [comment]
Ah, on the second glance, maybe the second and third column above are interconnected -- depending on the status the appropriate action is displayed...

**Comment by bozana** [comment]
Hihihihi :-) And on the third glance, you already mentioned it above @NateWr

**Comment by asmecher** [comment]
Assigning to @bozana -- I think she and @NateWr were going to hash out a solution here.

**Comment by NateWr** [comment]
Just cross-referencing bozana's related PR: https://github.com/pkp/pkp-lib/pull/1065

**Comment by bozana** [comment]
Just to add a note here for the requirement on reviewer recommendation in OJS :-)

**Comment by NateWr** [comment]
PR https://github.com/pkp/pkp-lib/pull/1177

This pull request:
- Separates the status and actions and improves clarity of both
- Adds contextual data depending on status (due dates, recommendations)
- Touches up the formatting of the review display modal

Here's an example showing all the statuses in OMP. In OJS, the recommendation is shown when available (where the due dates appear otherwise).

![review-status](https://cloud.githubusercontent.com/assets/2306629/13252209/4db30222-da2d-11e5-8e05-445177c0e731.png)

There are a few more issues I came across but I'm going to open a new issue with them.

**Comment by asmecher** [comment]
Are there outstanding pieces of work on this issue now that https://github.com/pkp/pkp-lib/pull/1177 has been merged?

**Comment by NateWr** [comment]
I think not. All other issues are separated into #1178.

**Comment by asmecher** [comment]
Woo! Down to 16 issues, with some big ones closed off.
