### ISSUE TITLE
Fatal error when importing XML article in PHP8

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7580]
**Describe the bug**
Some errors crop up when using the import/export plugin with PHP8.

**To Reproduce**

**What application are you using?**
3.3.0-8

**Additional information**
https://forum.pkp.sfu.ca/t/native-xml-plugin-ojs-3-3-0-8-imported-xml-article-published-with-error/71243/4

OJS 3.3.0.8 works fine with PHP 7.3/7.4 so these are probably due to PHP 8 running with stricter error reporting by default or just generally stricter typecasting:

Tue Dec 28 14:38:01.648869 2021] [lsapi:error] [pid 21808:tid 139823565649664] [client 213.110.123.20:0] [host chiffa.org] Backend fatal error: PHP Fatal error:  Uncaught Error: Non-static method Core::removeBaseUrl() cannot be called statically in /home/chiffa/domains/public_html/JournalEngine/engine/plugins/generic/usageStats/UsageStatsLoader.inc.php:777

[Tue Dec 28 14:38:25.334773 2021] [lsapi:error] [pid 21808:tid 139823834216192] [client 213.110.123.20:0] [host chiffa.org] Backend fatal error: PHP Fatal error:  Uncaught TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given in /home/chiffa/domains/public_html/JournalEngine/engine/plugins/generic/googleScholar/GoogleScholarPlugin.inc.php:91

There may be more of these elsewhere in the code.

**Comment by asmecher** [comment]
Thanks, @jnugent! @defstat, could you take a look at this?

**Comment by NateWr** [comment]
@jnugent can you add some reproduction steps to the issue report?

**Comment by jnugent** [comment]
@NateWr other than what's in the forum post, no I can't, because I don't have a PHP8 install handy. The import works fine on PHP7.

**Comment by defstat** [comment]
@NateWr @asmecher @jnugent 

**PRs**
[3.3.0]
pkp-lib: #7699
googleScholar: pkp/googleScholar#8
