### ISSUE TITLE
Consider replace Swift Mailer with Symfony Mailer

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7581]
**Describe the problem you would like to solve**
Swift Mailer was stoped being maintained in November 2021. It's used only in the current main branch instead of PHP Mailer. 
Swift Mailer is already replaced with Symfony Mailer in the Laravel Mail Service and is going to be released with Laravel Framework v. 9.0. Consider implementation of Symfony Mailer on the basis of this work to avoid using unmaintained dependency in 3.4 releases.    

**Describe the solution you'd like**
Patch Laravel framework. Adapt existing Mailer and Mailable implementation to support Symfony Mailer 

**Additional information**
This likely will have an impact on the following open issues:
https://github.com/pkp/pkp-lib/issues/7285
https://github.com/pkp/pkp-lib/issues/7288

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/7582
OJS: https://github.com/pkp/ojs/pull/3264

**Comment by Vitaliy-1** [comment]
Tests are failing, the relevant error:
```
PHP Fatal error:  Uncaught Symfony\Component\Mailer\Exception\TransportException: Connection to "process /usr/sbin/sendmail -bs" has been closed unexpectedly. in /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/symfony/mailer/Transport/Smtp/Stream/AbstractStream.php:84
Stack trace:
#0 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(316): Symfony\Component\Mailer\Transport\Smtp\Stream\AbstractStream->readLine()
#1 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(252): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->getFullResponse()
#2 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(194): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->start()
#3 /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/symfony/mailer/Transport/AbstractTransport.php(71): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doSend(Object(Symfony\Component\Mailer\SentMessage))
#4 /home/travis/build/pkp/ojs/lib/ in /home/travis/build/pkp/ojs/lib/pkp/lib/vendor/symfony/mailer/Transport/Smtp/Stream/AbstractStream.php on line 84
```

**Comment by Vitaliy-1** [comment]
This replaces Swift Mailer with Symfony Mailer by patching Laravel's framework version that we are currently using, i.e. current state Symfony Mailer integration on Laravel framework master branch on top of the v.7.30.4 tag: https://github.com/Vitaliy-1/framework/commits/symfony-7.x. 

I think it would be better to just replace Mail Service with a fork through composer's vcs repository but we are dependent on Illuminate Foundation, which isn't distributed as a separate package, only as a part of framework.

Symfony Mailer version 5.4 is used instead of 6.0, the latter requires PHP 8.0 or higher: https://github.com/symfony/mailer/blob/6.0/composer.json#L19

Failures with sendmail transport are just surrounded with a try catch block. The limitations here are the same as with Swift Mailer, described in this issue: https://github.com/pkp/pkp-lib/issues/7285

**Comment by Vitaliy-1** [comment]
@asmecher, can you take a look at this PR?

**Comment by asmecher** [comment]
@Vitaliy-1, could you document the steps you took to create that patch?

Also, could you write a little more about the exception try/catch/error_log? I would like us to more broadly adopt exceptions and I'm not sure why it's necessary here to drop everything into an `error_log`. Is this for smoother handling of client-level errors e.g. incorrectly entered emails?

**Comment by Vitaliy-1** [comment]
> @Vitaliy-1, could you document the steps you took to create that patch?

I've reviewed what is currently done on the master branch of Laravel framework to integrate Symfony Mailer and applied these modifications to version 7.30.4. It completely replaces Swift Mailer and its transports with correspondent code from Symfony. Apart from that, there is a change in the Laravel Mail Contract to exclude unused method.

The work on the framework main branch on Symfony Mailer looks more or less complete except error handling. I'm planning to monitor it until the official release, which is expected this month. My own additions to the Symfony Mailer integration only support for PHP 7.4, including usage of version 5.4 instead of 6.0

The patch doesn't include any other change

> Also, could you write a little more about the exception try/catch/error_log? I would like us to more broadly adopt exceptions and I'm not sure why it's necessary here to drop everything into an error_log. Is this for smoother handling of client-level errors e.g. incorrectly entered emails?

It's for handling Symfony Mailer's sendmail and SMTP transport-related exceptions. I've changed that.

**Comment by Vitaliy-1** [comment]
For recreating the patch clone the fork: https://github.com/Vitaliy-1/framework.git and run
```
git diff tags/v7.30.4 symfony-7.x
```
The latter was created by comparing the current state of Laravel Mail Service with v7.30.4

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1; that patch process is OK for now, but let's leave an issue open against 3.4.0 to review it before release. Hopefully by that point there will be a more standard approach.

**Comment by NateWr** [comment]
I filed the review issue at https://github.com/pkp/pkp-lib/issues/7612.

**Comment by Vitaliy-1** [comment]
Closing this one then
