### ISSUE TITLE
Bug of “urlPublished” in JSON data via API of OPS

### ISSUE THREAD

**Issue by tanabem** [pkp/pkp-lib#7583]
**Describe the bug**
Looking at the JSON returned via the OPS API, it seems that the “urlPublished” is still in the OJS specification.
Specifically, the place where the URL of the paper should be “/preprint/” is “/article/” as shown below.

In case of OJS: https://my-ops-site/ops/index.php/test/**article**/view/62/102
In case of OPS: https://my-ops-site/ops/index.php/test/**preprint**/view/62/102
*These are dummy URLs.

**To Reproduce**
1. Click on such as the following URL from your browser. 
https://my-ops-site/ops/index.php/test/api/v1/submissions/62?apiToken=XXXXXXXXXX

2. See such as the following Json returned from API.
"urlPublished":"https:\/\/my-ops-site\/ops\/index.php\/test\/**article**\/view\/62\/version\/85\/102"

**What application are you using?**
OPS version 3.3.0.7

**Additional information**
See also my post in PKP Cummunication Forum.
https://forum.pkp.sfu.ca/t/error-of-urlpublished-in-json-data-via-api/71305

**Comment by asmecher** [comment]
It looks like this was corrected in `main` but not `stable-3_3_0` in this commit:

https://github.com/pkp/ops/commit/0cc844c694f6aba42adbea6e554952222da8f7b6

I'll port this to `stable-3_3_0` in a moment.

**Comment by asmecher** [comment]
@tanabem, thanks for reporting -- you can fix this by applying the following change:

https://github.com/pkp/ops/commit/8948276382aa6a40bf8b1e0f027deb3c36f33e09

This will be released with OPS 3.3.0-9 (or 3.4.0, whichever comes first).

**Comment by tanabem** [comment]
@asmecher , Thank you for the correction.
I confirmed that "urlPublished" in "galleys" has been fixed. However, the other “urlPublished” is still "/article/". 
Is it possible to correct with this as well?
```
"urlPath": null,
"urlPublished": "https://my-ops-site/ops/index.php/test/article/view/XX/version/XX",
"version": 1,
"vorDoi": null 
```
Regards,

**Comment by asmecher** [comment]
@tanabem, https://github.com/pkp/ops/commit/ee80dc4edc18f29d8e4902bb80583ce2f6db5c1f will fix the additional case.

**Comment by tanabem** [comment]
@asmecher , 
I confirmed that it was fixed.
Thanks lot.
