### ISSUE TITLE
Synchronize submodules across main repositories

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7585]
**Describe the problem you would like to solve**
The /main branch of OPS/OMP/OJS are using different versions of the submodules.

**Describe the solution you'd like**
Attempt to use the same versions, if possible the latest, in order to keep a homogeneous environment (similar code, errors, etc).

**Who is asking for this feature?**
Developer

**Comment by asmecher** [comment]
@jonasraoni, do you mean to simply update the submodule hash, or change the way we're linking the `lib-pkp` repo somehow?

**Comment by jonasraoni** [comment]
Just a reminder to update the hashes =]
I think there's an issue somewhere to discuss alternatives for the submodules 🤔

**Comment by asmecher** [comment]
OK! No need to file an issue for a submodule update -- and while we're using submodules it doesn't hurt to update them only when needed, otherwise it forces other devs to rebase their PRs.
