### ISSUE TITLE
Authorization (Login) 

### ISSUE THREAD

**Issue by p6steve** [pkp/pkp-lib#7588]
As mentioned on [PKP Community Forum](https://forum.pkp.sfu.ca/t/authorization-login/63199)

**Describe the bug**
From time to time a user reports a "stuck logon", they enter username/password and submit but do not advance or get a browser error message.

**To Reproduce**
I have observed (via screen share) a bad cookie conflict that is resolved by removing one of the cookies. Please see attached bug report for details.

**What application are you using?**
 OJS 3.3.0.6 on PHP 7.3.33

**Additional information**
[HCC Review-OJSStuckLogon-v1.01.docx](https://github.com/pkp/pkp-lib/files/7807195/HCC.Review-OJSStuckLogon-v1.01.docx)

**Comment by asmecher** [comment]
I'll re-open this if the conversation on the support forum (https://forum.pkp.sfu.ca/t/authorization-login/63199) progresses a little further towards a reproducible bug.
