### ISSUE TITLE
[OJS] Inspect if the LDAP plugin is working properly

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7589]
**Describe the bug**
The LDAP plugin is using an outdated/broken version of the `ldap_sasl_bind` function.
The newer function introduced a new and bad positioned parameter (not added to the end) which is likely to break something.

**Questions**
I've fixed (without testing) in another PR, but as I couldn't find this plugin in OMP/OPS, I got a question... Is this plugin deprecated?

**What application are you using?**
 OJS /main

**PRs**
https://github.com/pkp/ojs/pull/3269

**Comment by asmecher** [comment]
I don't recommend spending much time on the LDAP plugin without a) confirmation that it's needed by the community and b) thinking about future plans for single sign on.

My sense is that we get occasional requests from users about the LDAP plugin who don't realize that it doesn't provide single-sign-on services but only shared user accounts. Tools like Shibboleth and OpenID/OpenAuth are generally what users are actually looking for.

**Comment by jonasraoni** [comment]
I've just added the missing parameter and a setting for it. So I was just curious if the PR should attempt to fix it or remove it altogether if it's just forgotten code :)

**Comment by asmecher** [comment]
I'm not against fixing it, but it's a low priority for investing time at the moment.

**Comment by jonasraoni** [comment]
Ok! As I had already addressed it in another PR I've just cherry picked it and created a PR pkp/ojs#3269.
