### ISSUE TITLE
Submitted Competing Interest data can go missing

### ISSUE THREAD

**Issue by twakeford** [pkp/pkp-lib#7594]
When invited to complete a peer review, the review task invitation interface, asks the Reviewer to declare whether they have Competing Interests or not, with the Reviewer being given the options

- 'I do not have any competing interests'
- 'I may have competing interests (Specify below)' with an associated text box.

It looks like the 'no CIs' option can be selected **as well as** text being added into the text box. If this happens then the text entered is not saved/displayed to the editor. This seems to lead to the risk that a reviewer will enter potential CIs but the Editor will not see them.

Presumably, if text is entered into the text box then the 'I may have competing interests' should be auto-checked and the content passed to the Editor.

**What application are you using?**
3.3.0.7

![Screenshot 2021-12-31 at 11 26 25](https://user-images.githubusercontent.com/15159847/148262595-de38b7c4-cc36-4101-88d1-be181d7ce955.png)

**Comment by NateWr** [comment]
@asmecher it looks like maybe you've committed a fix for this to `stable-3_3_0` and `main`. Can this be closed?
