### ISSUE TITLE
Valid special characters are stripped from DOI suffix 

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#7595]
**Describe the bug**
Starting in OJS 3.3, all special characters present in a journal acronym are stripped from the DOI suffix - as per [#5505](https://github.com/pkp/pkp-lib/issues/5505)

This includes the characters that are recognized as [valid by Crossref](https://www.crossref.org/documentation/member-setup/constructing-your-dois/#afewrules), in particular: "hyphen, period, underscore, semicolon, parentheses, forward slash".

This affects, in particular, bilingual journals that have a hyphenated abbreviation in both languages. Example: 

On 3.1 - https://doi.org/10.33137/cjal-rcbu.v6.34621
On 3.3 - https://doi.org/10.33137/cjalrcbu.v7.37566

To note - both old and new DOIs resolve fine and the change did not create issues with Crossref registration or conflicts.

There is an MR to add these permitted characters back [#3202](https://github.com/pkp/ojs/pull/3202). Tagging @ewhanson re adding this to 3.4 and back-porting to 3.3.

**To Reproduce**
1. Add a journal acronym with a hyphen or another permitted character to the masthead
2. Generate a DOI for an article
3. See DOI generated with no permitted character

**What application are you using?**
OJS 3.3

**Comment by asmecher** [comment]
@ajnyga, can you confirm that the PR (https://github.com/pkp/ojs/pull/3202) doesn't unexpectedly run counter to your intentions in limiting special characters in the first place (https://github.com/pkp/pkp-lib/issues/5505)?

**Comment by dennmuel** [comment]
In case the regex is okay, I prepared PRs for OMP and OPS as well.
Btw: OMP did not have a regex as suggested in #5505, so I just added the more lax one in the PR. I don't know if it even makes sense there, but did it just in case.

pkp/ojs#3202
pkp/omp1050
pkp/ops#217

**Comment by kristinmhoffmann** [comment]
We also host a handful of bilingual journals whose journal initials contain a hyphen or underscore, so would like to see the permitted characters added back. Example:
On 3.1: [https://doi.org/10.5206/cjsotl-rcacea.2020.2.9415](https://doi.org/10.5206/cjsotl-rcacea.2020.2.9415)
On 3.3: [https://doi.org/10.5206/cjsotlrcacea.2021.1.14255](https://doi.org/10.5206/cjsotlrcacea.2021.1.14255)

**Comment by ajnyga** [comment]
This is from the DOI ISO standard:
"Characters which cannot be handled directly in a specific network or reference context, or where ambiguity can arise (e.g. minus sign, the hyphen, and the en-dash all look similar on the screen but carry different character values) should be avoided or encoded in an appropriate way"

**Comment by bozana** [comment]
Hmmm... Actually, it seems to me that the standard allows any characters:
s. https://cdn.standards.iteh.ai/samples/43506/c7e86e8847e24b9fa2ac2ae25de435d3/ISO-26324-2012.pdf
In 4.1.1 General characteristic: 

> The DOI name is case-insensitive and can incorporate any printable characters from the legal graphic
> characters of Unicode. Further constraints on character use (e.g. use of language-specific alphanumeric
> characters) can be defined for an application by the ISO 26324 Registration Authority.

In 4.1.3 DOI suffix:

> The DOI suffix shall consist of a character string of any length chosen by the registrant... 

and Example 2 there:

> 10.1038/issn.1476-4687 

Also other examples in the document contain the period sign.


The paragraph about the characters that should be avoided is in the section `4.2.3 Other representations` (= other than screen, print and URI).

It seems to me that Crossref removed the possibility of ambiguity allowing only hyphen (and not minus, em and en dash).

Thus, maybe we should also see how other agencies i.e. DataCite and mEDRA deal with it and then decide...

**Comment by bozana** [comment]
Here a DataCite link, s. the chapter Suffix there: https://support.datacite.org/docs/doi-basics. Thus, they suggest the same characters as Crossref (and additionally ':').

**Comment by bozana** [comment]
Regarding URN -- because the changes made applied to it too -- s. https://www.rfc-editor.org/rfc/rfc2141, chapter 2.2 Namespace Specific String Syntax.
It allows: "(" | ")" | "+" | "," | "-" | "." | ":" | "=" | "@" | ";" | "$" | "_" | "!" | "*" | "'"
Plus, added in 2017, s. https://www.rfc-editor.org/rfc/rfc8141#appendix-B: "/", "~", and "&"

I believe that if we constrain it to the characters supported by Crossref it will not lead to a problem. 
The special characters (other than '.' that is used in our default suffixes) only appear in journal i.e. context acronym and the acronym mostly does not contain other characters than those supported by Crossref.

**Comment by bozana** [comment]
Thus, I think, we are OK to consider those Crossref characters in the changes made here https://github.com/pkp/pkp-lib/issues/5505.
Eventually we would like to consider them also for the custom suffixes.

**Comment by dennmuel** [comment]
@bozana, yes, I'm quite occupied with other tasks right now so please go ahead and change as needed. :) Thanks!

**Comment by bozana** [comment]
PRs stable-3_3_0:
ojs: https://github.com/pkp/ojs/pull/3531
omp: https://github.com/pkp/omp/pull/1195
ops: https://github.com/pkp/ops/pull/343

**Comment by bozana** [comment]
@asmecher, could you take a look at the PRs above?

**Comment by asmecher** [comment]
All merged. Thanks, @bozana & all who participated!
