### ISSUE TITLE
HTTP 500 error

### ISSUE THREAD

**Issue by Adnanpij** [pkp/pkp-lib#7598]
I was trying to install a plugin, after that there is an error occurred. Please guide me on how to fix it.
![2222](https://user-images.githubusercontent.com/60043094/148628550-f81ba95a-6638-456c-8191-bfc9a4764855.JPG)
![Capture](https://user-images.githubusercontent.com/60043094/148628552-c86807ae-f5e9-40a0-ad72-069d1ccca2eb.JPG)

**Comment by asmecher** [comment]
@Adnanpij, please include...
- What version of OJS you're using
- What plugin you installed (including its version and where you got it)
- How you installed the plugin (e.g. through the plugin gallery, by uploading it into OJS, or by unpacking the archive manually)
- What you're doing when the error message appears.

**Comment by Adnanpij** [comment]
I am using the latest version 3.3.0.8 of OJS
I am not sure due to which plugin I got this error, As  installed multiple plugins
I installed it through plugin gallery, It was already installed, I was trying to activate it by Mark. 
I am unable to browse the site. therefore I am looking for suggestion how to fix it

**Comment by asmecher** [comment]
Judging by the error message, this is a problem with the OpenID plugin. We don't maintain that plugin; I'd suggest contacting its author by filing an issue here:

https://github.com/leibniz-psychology/openid/issues
