### ISSUE TITLE
Submission wizard asks for languages that are not enabled

### ISSUE THREAD

**Issue by twakeford** [pkp/pkp-lib#7605]
**Describe the bug**
When setting language settings for a second language, I have turned on _Forms_ but not _Submissions_, as I want to have duel language frontend and UI but I do not wish to receive submissions with multiple language data. But, when an author submits, despite not being asked what language their submission is in on page 1 of the submission process, they do see all the metadata options for both languages.

This appears to be a bug, as presumably if _Submissions_ is disabled then the author should not be presented with the option to add data in that language.

Currently it appears that there is not a way to have multiple languages turned on for the frontend website but not present the author with all the different language fields during submission.

**To Reproduce**
1. Go to '.Website > Setup > Languages': disable _Submissions_ and enable _Forms_
![submissions-disabled](https://user-images.githubusercontent.com/15159847/148840874-ec3dc8d7-116f-498b-a2f0-d4ee693b7a17.png)

2. Start a new submission (no option for language is shown)
![submission-page-1(no language)](https://user-images.githubusercontent.com/15159847/148840928-aa4c89f3-29c1-4008-b41e-4f936f7993c1.png)

3. Move through the stages > at Stage 3, metadata is being asked for in languages that have _submissions_ disabled
![Submission-page-3(languages)](https://user-images.githubusercontent.com/15159847/148840976-c3a60a36-ebd5-4362-bd14-b4d5b4562f8d.png)

**What application are you using?**
 OJS 3.3.0.7

**Comment by NateWr** [comment]
@asmecher does this fix look ok to you? Seems straightforward but I haven't touched any of this in a long time.

PR:
https://github.com/pkp/pkp-lib/pull/7614

Tests:
https://github.com/pkp/ojs/pull/3272

**Comment by NateWr** [comment]
Not sure why, but this did break the tagit autosuggest fields in the submission wizard...

**Comment by NateWr** [comment]
Found the problem with the keywords fields. I've now merged this to `stable-3_3_0` and manually ported it to the `main` branch.

**Comment by asmecher** [comment]
Late to the game, but a glance this looks fine, @NateWr. I remember distinguishing submission and form locales and needing to add code like this to numerous places; no surprise that we missed this one.
