### ISSUE TITLE
Dublin Core subject tag only shows last keyword when more than one keyword entered

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7607]
**Describe the bug**
When more than one keyword exists, the DC metatag at the top of the article landing page only shows the last keyword instead of several. For example, if the keywords are: `apple`, `bird`, and `cat`, the DC metatag should be:

```
<meta name="DC.subject" xml:lang="en" content="apple">
<meta name="DC.subject" xml:lang="en" content="bird">
<meta name="DC.subject" xml:lang="en" content="cat">
```

However, what is actually shown is:

```
<meta name="DC.subject" xml:lang="en" content="cat">
```

**To Reproduce**
1. Make sure that keywords are enabled in metadata under Settings > Workflow > Submission> Metadata.
2. Go to any unpublished submission.
2. Click on Publication > Metadata.
3. Enter more than one keyword.
4. Publish the submission.
4. Go to the public page for the published submission and view source.
5. See there is only one DC.subject meta tag. 

**What application are you using?**
3.3.0-8

**Additional information**
See the [forum report](https://forum.pkp.sfu.ca/t/keywords-meta-tags-for-3-1-2-4-versus-3-3-0-8/71455)

_Edited to say this happens on the article landing page._

**Comment by asmecher** [comment]
I just tested this locally and couldn't reproduce with either `stable-3_3_0` or the `3_3_0-8` tag (OJS and pkp-lib)... The testing data set shows:
```
<dc:subject xml:lang="en-US">Professional Development</dc:subject>
<dc:subject xml:lang="en-US">Social Transformation</dc:subject>
```
Were you able to reproduce this with a 3.3.0-8 installation?

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/3280

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and ported forward to `main` (https://github.com/pkp/ojs/commit/fa5c43fd27f6206981afe164c2d4cd3cc6ced79d).
