### ISSUE TITLE
Add test to check DC metadata tags on article landing page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7608]
**Describe the problem you would like to solve**
The DC metadata tags are not visible to a human when viewing an article landing page. For this reason, bugs can linger for a long time without anyone noticing.

**Describe the solution you'd like**
Add a test to check that DC metadata tags are present and accurate on the article landing page. The tests should check:

- [ ] All tags are present and accurate. See [code](https://github.com/pkp/ojs/blob/main/plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.inc.php).
- [ ] Any tags that show multiple items, like keywords (DC.subject), should have a tag for each item.

**Who is asking for this feature?**
A bug introduced in 3.2 was not caught until after 3.3 was released. See [bug report](https://github.com/pkp/pkp-lib/issues/7607).

---
**PRs**

**Branch `main`**
OJS: pkp/ojs#3586
OMP: pkp/omp#1238

**Comment by defstat** [comment]
@NateWr I am proposing a PR [here](https://github.com/pkp/pkp-lib/issues/7608#issue-1098968927) for that, only for OJS for now, to check if that is the approach you have in mind.

**Notes**
1. The test will fail - I have added an assert that the `content` attribute of a `<meta name="DC.{whatever}" .../>` tag can't be empty. Is this a valid assumption? The `mwandenga` submission (which I am using for this test), adds a `<meta name="DC.Rights" content=""/>` corresponding to `[dublinCorePagesLicenseUrl](https://github.com/pkp/ojs/blob/main/plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.php#L141)` though.
2. To assert the value of the dates added to the `DC.Date.modified`, `DC.Date.issued`, `DC.Date.created`, before running the assertions I unpublish and publish again the Issue that the `mwandenga` submission is published into. Then I am using `today` date to assert those attributes.
3. There is also the `DC.Date.dateSubmitted` value which I can't safely assert (I could check `today` for that also though)

**Comment by NateWr** [comment]
Thanks @defstat. @bozana can you take over the code review on this?

**Comment by bozana** [comment]
@NateWr, I am wondering how thoroughly we should test it -- for example, the current submissions that we use in the tests do not have all 'cases'/metadata, e.g. the following is missing: sponsor, coverage, title with prefix and subtitle, DOI, type, multiple languages. If we would really like to test it all, we would need to create an extra submission, that contains all that. But do you think it is needed (for now)?

**Comment by bozana** [comment]
@defstat, could you also add a check in the DublinCoreMetaPlugin if `getLicenseURL` exists, so that no empty element is created?

**Comment by NateWr** [comment]
> If we would really like to test it all, we would need to create an extra submission, that contains all that. But do you think it is needed (for now)?

It's up to you whether you think we have the time now. But in general I think it's good to try to be comprehensive with these tests, and to test negative expectations too. For example, test that a DC field is missing when disabled or empty; adding metadat, then disabling that metadata, and making sure it doesn't still appear; etc. It doesn't have to be now, but eventually you'll want to set up conditions for testing those scenarios wherever metadata is distributed (Crossref, DataCite, OAI, etc).

**Comment by bozana** [comment]
Thanks @NateWr! For comprehensive testing I will then need more time, also to think about it :-)
Hmmm... but for now...
@defstat, if it would not mean much work for you and it would be OK for you to do it, I would love to have an extra submission, at least with a title with prefix and subtitle and with multilingual metadata, that we would use for this test. If you think it would be much work, than we can leave it for later. What do you think?

**Comment by defstat** [comment]
@bozana I made several changes to the test - (and the plugin). I think OJS is ready for another review round

**Comment by defstat** [comment]
@bozana I have resolved the OJS's review comments and added the PR for OMP as well. OPS does not have the `generic/DublinCoreMetaPlugin` implemented.

**Comment by bozana** [comment]
I realized that we do display the empty DC elements, e.g. if abstract for a language is empty, it will be displayed as an empty DC element, e.g.:
`<meta name="DC.Description" xml:lang="fr" content=""/>`
@asmecher, do you know if the empty DC elements can exist so, or shall we fix it?

**Comment by defstat** [comment]
Just a note here: the test asserts that all meta tags with content, should have their content not empty. In my opinion, if the content is empty it does not add any additional information/metadata, so there is no obvious reason of declaring it, but I am not sure if there is a DC rule that states that....

**Comment by asmecher** [comment]
@bozana, I don't think empty elements are a "bug" speaking strictly, but it would probably be nicer to downstream consumers if we didn't include them when empty.

**Comment by bozana** [comment]
Yes, thanks @asmecher and @defstat! I just wanted to double check if we should change the tests or open a new issue :-)
Here is the new issue: https://github.com/pkp/pkp-lib/issues/8406 :-)

**Comment by bozana** [comment]
Ah, I see there are a few things that should be fixed/improved in the DublinCoreMetaPlugin :-\
Thus, for now the tests are good so. Later, when we address this issue https://github.com/pkp/pkp-lib/issues/8406, we can adapt the tests (e.g. to consider chapters and files pages in OMP, versioning, etc)

**Comment by bozana** [comment]
Thanks a lot @defstat!
Everything merged, thus closing...
