### ISSUE TITLE
Review Laravel/Symfony mail integration before 3.4's release

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7612]
Laravel 9 is migrating to Symfony mail. In https://github.com/pkp/pkp-lib/issues/7581, we have adopted this integration. However, Laravel 9 is not yet released.

Before 3.4 is released, we should review our use of this, identify any changes that were made before Laravel 9's release, and ensure we're handling these appropriately.

**Comment by asmecher** [comment]
Implemented in https://github.com/pkp/pkp-lib/issues/7815.
