### ISSUE TITLE
Keyword auto complete not working while submitting a preprint/book/submission

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7613]
**Describe the bug**
The keywords auto-complete at the 3rd submission step of OPS (perhaps others) isn't working.

**To Reproduce**
1. Ensure the installation have some available keywords
2. Register a new submission
3. At the 3rd step (Enter Metadata), type some letters and wait for the auto complete
4. Nothing happens, no request is made and a div "No search results." appear at the bottom of the page

**What application are you using?**
 OPS 3.3.0

**PRs**
**stable-3_3_0**
https://github.com/pkp/pkp-lib/pull/7625
https://github.com/pkp/ojs/pull/3276
https://github.com/pkp/omp/pull/1054
https://github.com/pkp/ops/pull/222

**main**
https://github.com/pkp/pkp-lib/pull/7626
https://github.com/pkp/ojs/pull/3277
https://github.com/pkp/omp/pull/1053
https://github.com/pkp/ops/pull/220

**Additional information**
![image](https://user-images.githubusercontent.com/361921/149127190-d44ae2a7-c74d-42fa-9242-2e1c08ce7762.png)

**Comment by jonasraoni** [comment]
@asmecher Could you please take a look at the [comment I've left in the OMP's PR](https://github.com/pkp/omp/pull/1053#pullrequestreview-853697392)?

p.s.: I was going to replace the `tag-it` component (looks like it's the only place using it) by our autosuggest, but then I decided to leave it for the next refactoring (replace the current wizard by Vue components).

**Comment by asmecher** [comment]
@jonasraoni, are you waiting for something from me on this?

**Comment by jonasraoni** [comment]
@asmecher I've modified the OMP's VocabHandler handler for  to retrieve ONIX countries:
https://github.com/pkp/omp/pull/1053/commits/241f612a415fa7bef5c63e74e018884d496ce288

If that's fine for you, then I can merge everything.

**Comment by asmecher** [comment]
Thanks, @jonasraoni, please go ahead!
