### ISSUE TITLE
Add support for RSS feeds to OPS

### ISSUE THREAD

**Issue by devinberg** [pkp/pkp-lib#7623]
**Describe the problem you would like to solve**
Ability to produce as RSS feed for a preprint server. Ideally, feeds could be created for "Disciplines", "Keywords", etc. as well.

**Describe the solution you'd like**
Migrate the existing [Web Feeds](https://github.com/pkp/ojs/tree/main/plugins/generic/webFeed) to OPS.

**Who is asking for this feature?**
Server admin. Server users.

**Comment by jonasraoni** [comment]
PRs below, I'll probably add some simple tests later.
- https://github.com/pkp/ops/pull/350
- https://github.com/pkp/ops/pull/351

**Comment by jonasraoni** [comment]
Hi @bozana! I've heard you're going to review this issue :)
This is basically a copy of OJS's web feed plugin with minor updates, I didn't spend much time trying to improve it (besides updating some syntaxes). As there's few code, the only thing I'd change would be to separate the rss/rss2/atom into "modules", and it's always worth to add some basic tests.

Feel free to review. Once it's tested/approved, I'll give you a green flag to merge.

**Comment by bozana** [comment]
Hi @jonasraoni, I went through the PR for the main branch and left a few comments. When you finish it all, I can take another look and also into PR for the stable branch... Thanks!

**Comment by jonasraoni** [comment]
Updated PRs:
`main`
- https://github.com/pkp/ops/pull/351
- https://github.com/pkp/pkp-lib/pull/8276

`stable-3_3_0`
- https://github.com/pkp/ops/pull/350
- https://github.com/pkp/pkp-lib/pull/8277

**Comment by bozana** [comment]
Everything merged, thus closing...
