### ISSUE TITLE
Replace strftime() as it's deprecate in PHP 8.1 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7624]
**Describe the problem you would like to solve**
`strftime` function is deprecated in PHP 8.1, see: https://www.php.net/manual/en/function.strftime.php

**Describe the solution you'd like**
It's suggested for locale-dependent formatting to use `IntlDateFormatter::format()`: https://github.com/php/php-src/commit/4b3615a33ff376281ddd1e228237b435a9738521

**Additional information**
`strftime` uses its own formatting pattern that isn't directly convertible to `DateTime`'s.

**Comment by NateWr** [comment]
I've assigned this to 3.4 so we can get ahead of it. I think because it's such a key configuration item, it might be too big of a change for 3.3.0, but I'm not sure how this will effect 3.3 as a LTS version. @asmecher thoughts on PHP 8.1 and LTS?

**Comment by asmecher** [comment]
It's deprecated with 8.1, not removed. The removal is set for PHP 9.0, which as far as I can tell doesn't have a release date. I recommend we don't schedule a back-port of the adaptation away from `strftime` for `stable-3_3_0` until we know it'll be needed per our LTS commitments; the gap between major PHP releases can be very significant.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/7767
- https://github.com/pkp/ojs/pull/3328
- https://github.com/pkp/quickSubmit/pull/57

**Comment by NateWr** [comment]
@asmecher FYI the test failure was just a mistake in the date format.

PR:
https://github.com/pkp/ojs/pull/3339

**Comment by NateWr** [comment]
I've merged those PRs, which should fix the stats test failures. But OMP/OPS are still failing on a decision. See https://github.com/pkp/pkp-lib/issues/7768.

**Comment by asmecher** [comment]
Back-porting to `stable-3_3_0` using a BC shim library as part of https://github.com/pkp/pkp-lib/issues/8193.
