### ISSUE TITLE
Add CSV monograph report to OMP

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#7635]
**Describe the problem you would like to solve**
Press Managers would like to be able to generate reports from the front end similar to what would be provided by the 'Articles Report' in OJS

**Describe the solution you'd like**
Columns to include
- Monograph Title
- Authors
- Publication Date
- Series Name
- ISBN/ISSN
- URL
- DOI
- Categories

**Who is asking for this feature?**
Press Managers

**Comment by NateWr** [comment]
> from the front end

Just to clarify, do you mean by going to Statistics > Reports in the editorial UI?

**Comment by pmangahis** [comment]
Yes, overall the frontend statistics available on OMP are fairly limited.

**Comment by jonasraoni** [comment]
**PRs**
`main`
- https://github.com/pkp/pkp-lib/pull/8256
- https://github.com/pkp/omp/pull/1204

`stable-3_3_0`
- https://github.com/pkp/omp/pull/1202
- https://github.com/pkp/pkp-lib/pull/8254

**Comment by jonasraoni** [comment]
Merged these PRs: https://github.com/pkp/pkp-lib/issues/7635#issuecomment-1246780793
