### ISSUE TITLE
Can't export XML or deposit via CrossRef Export Plugin in OPS

### ISSUE THREAD

**Issue by JhonathanLepidus** [pkp/pkp-lib#7637]
**Describe the bug**
When in OPS, it's not possible to deposit a preprint or export it as XML.

**To Reproduce**
1. Go to  Tools > CrossRef XML Export Plugin 
2. Click on "Preprints"
3. Select any preprint and click on "Download XML"

**What application are you using?**
OPS 3.3.0-8

**Additional information**
The error occurs because of [calling the function toArray](https://github.com/pkp/crossref-ops/blob/48b80c5c97a717cd75a7dc12f079b506bbeb6cb1/filter/PreprintCrossrefXmlFilter.inc.php#L68) on the returning of `$pubObject->getData('publications')` which already returns an array.

**Comment by NateWr** [comment]
The code you are looking at is for the `main` branch. This was split out as part of working going into the next release (3.4.0), and the `->toArray()` method is necessary there. 

The Crossref plugin for OPS 3.3.0-x is still located in the OPS repository here:

https://github.com/pkp/ops/blob/stable-3_3_0/plugins/importexport/crossref/filter/PreprintCrossrefXmlFilter.inc.php#L66

It doesn't look like the `->toArray()` method exists there. Can you check your plugin to make sure you're using the version in the `stable-3_3_0` branch of OPS?

**Comment by diegoabadan** [comment]
Oops, mistake our @NateWr !

We didn't realize that the code difference could be due to the OPS version. I believe this PR can be closed.

Abstacts are hugely important and are missing from current OPS, so virtually everyone who uses it has to apply this fix manually.
