### ISSUE TITLE
Add support for the native import/export plugin to OPS 3.3.0-x

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7639]
**Describe the problem you would like to solve**
The current release of OPS doesn't support the XML tooling for importing/exporting data.

**Describe the solution you'd like**
Merge some updates from the /main branch to the `stable-3_3_0` branch to make this functionality available.

**Who is asking for this feature?**
System administrators looking forward to migrate data from other systems.

**PRs**
https://github.com/pkp/ops/pull/223
https://github.com/pkp/pkp-lib/pull/7640

**Comment by jonasraoni** [comment]
Hi @asmecher!

I've created draft [PRs](https://github.com/pkp/pkp-lib/issues/7639#issue-1109232484), later I'll recheck if the basic features (import/export through the CLI and web interface) are still working fine after rebasing.

I've been using these updates to import data locally, and everything seems to be working fine... Most of the changes are additions. The modified parts are inside classes related to the native import/export plugin.

**Comment by asmecher** [comment]
@defstat, could you review these?

@jonasraoni, I'm assuming you went back to the commits where this was first added to `main` and cherry-picked them to `stable-3_3_0`? Or did you bring in the files from `main` and back-port them to compatibility with `stable-3_3_0` again? Just to know what to look for.

**Comment by jonasraoni** [comment]
If I remember well:
https://github.com/pkp/pkp-lib/pull/7640: Cherry picked the first commit + adjusts.
https://github.com/pkp/ops/pull/223: Grabbed the needed files from `/main` + adjusts.

**Comment by asmecher** [comment]
@jonasraoni, that's a lot more code being added to `stable-3_3_0` `lib/pkp` than I expected naively; is there really no impact on the OJS and OMP stable branch?

**Comment by jonasraoni** [comment]
@asmecher I just checked and I fully agree, I think these PRs were a kind of draft.
I'll check if it's possible to decrease the amount of changes.

Anyway, let me know if you're ok to get this amount of code merged in 3.3.0... Then, given that most of changes are additions, I can just test the updates against OJS/OMP.

**Comment by asmecher** [comment]
Unless the potential impact can be brought down on OJS/OMP 3.3.0-x, I'd suggest just leaving these changes to the 3.4.0 release. If someone has a firm requirement for this support in 3.3.0-x, please speak up!

**Comment by asmecher** [comment]
Let's leave this as a thing to be added to an install for anyone who needs it -- but unless there's a compelling reason to merge disruptive changes to `stable-3_3_0` (especially for `pkp-lib`) I'd rather not merge. Thanks all!

**Comment by jonasraoni** [comment]
Yeah! That's what I've told to Michael. It's still useful for those who really need to import data into OPS 3.3 :)

Also, I can confirm all the code here can be applied temporarily, just to get the imported data in place, then it might be fully reverted to the base branch (`stable-3_3_0`) without issues.
