### ISSUE TITLE
duplicate missing keys in translator plugin 

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#764]
When using the "check" function in the translator plug-in, sometimes the missing locale key fields are listed several times. This leads to overriding of the entered translations, when saving the web form.
The problem is in the function TranslatorAction::testLocale: In this function every plug-in is went thought. Some generic plug-ins contain other plug-ins (e.g. block, report), that use the same locale file. Thus, the same locale file will be considered several times, for each of these plug-ins.
The pull request for a solution is coming...

**Comment by asmecher** [comment]
Merged for OJS 2.4.7 -- thanks, @bozana. How do you feel about forward-porting to OMP or OJS master? The code is probably in the https://github.com/pkp/translator rather than the app repo.

**Comment by bozana** [comment]
Sure... :-)

**Comment by asmecher** [comment]
(@bozana, just a reminder that this needs forward-porting -- thanks!)

**Comment by asmecher** [comment]
Closing. Thanks, @bozana!
