### ISSUE TITLE
Pre-flight check fails in OPS due to context table name

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7646]
**Describe the bug**
In the `main` branch (3.4 pre-release), a pre-flight check runs during upgrade. It uses `ServerDAO::$tableName` which is `servers`. However, at the time that the pre-flight check is run, the table is still named `journals`. This causes a fatal error.

**To Reproduce**
1. Install OPS 3.3.0-8
2. Run the upgrade script to `main` (3.4 pre-release)

**What application are you using?**
OPS 3.3.0-8 / 3.4 pre-release

**Additional information**
The pre-flight checks are here: https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.inc.php#L30-L31

They shouldn't use `$contextDao->tableName` or `$contextDao->primaryKeyColumn` because they are run before the table is migrated here: https://github.com/pkp/ops/blob/main/classes/migration/upgrade/v3_4_0/I6759_RenameVariables.inc.php

**PRs**
- https://github.com/pkp/pkp-lib/pull/7679
- https://github.com/pkp/ops/pull/230
- https://github.com/pkp/omp/pull/1063
- https://github.com/pkp/ojs/pull/3293

**Comment by bozana** [comment]
What would be the right solution here: to use the rename script before preflight check or to use old table and column names in the preflight check? -- just for me to know how to implement the usage stats preflight check... :-)

**Comment by bozana** [comment]
Also the other upgrade scripts should be checked, if they depend on the new names -- e.g. this one also depends on new names and is executed before the renaming: https://github.com/pkp/ops/blob/main/dbscripts/xml/upgrade.xml#L35

**Comment by NateWr** [comment]
All migration scripts should hard-code the name of the table instead of using properties of the DAO, since these can change and the migration scripts should never change.

**Comment by bozana** [comment]
Yes, this is what I've done. At the time when preflight check is done, should 'jounals', 'journal_id' be used (instead of 'servers', 'server_id')?

**Comment by NateWr** [comment]
I think so, this migration file shows the names before/after: https://github.com/pkp/ops/blob/main/classes/migration/upgrade/v3_4_0/I6759_RenameVariables.inc.php#L57

**Comment by bozana** [comment]
Maybe one more thing (additionally to that another script also depends on the new names :point_up:): those `${variableName}`, like e.g. here https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.inc.php#L33,  should be `{$variablename}`

**Comment by NateWr** [comment]
Yeah can you fix those too?

**Comment by jonasraoni** [comment]
@bozana Our code formatter is using this format =]

If you attempt to format this line:

```php
echo "$x", "${x}", "{$x}";
```

This will be the output:

```php
echo "${x}", "${x}", "{$x}";
```

**Comment by NateWr** [comment]
Oh, right! I thought it was just as JS syntax. I'm struggling to find reference to that format in the PHP docs. I wanted to check version compatibility. Can you find the docs for `"${x}"`? Everything I'm finding is `"{$x}"`.

**Comment by jonasraoni** [comment]
I found an example here: https://www.php.net/manual/en/language.types.string.php#language.types.string.parsing.simple =]

**Comment by NateWr** [comment]
Perfect, thanks! I can't see a PHP version, but if it's under "simple syntax" it's probably been around a long time. :)

**Comment by jonasraoni** [comment]
@asmecher I was going to write a small fix for this, but then I started facing new issues and decided to make the whole migration static (I just left this part dynamic: https://github.com/pkp/pkp-lib/pull/7679/files#diff-f4951b8d90b205bf60a1111a761b62eb75f598c0c536738da01d027561a33f1cR273).

I've added the PRs to the issue description, and left comments on the ones for `pkp-lib` and `ops`.
