### ISSUE TITLE
Add support for limiting allowed hosts

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7649]
**Description of problem**

OJS/OMP/OPS currently uses the `HTTP_HOST`, `SERVER_NAME`, and `HTTP_X_FORWARDED_HOST` headers to detect the current hostname for formulating absolute URLs.

Per https://portswigger.net/web-security/host-header, these headers may be user-controlled and thus not trustworthy. This could be used to e.g. send password reset emails with poisoned links that direct the user to a 3rd-party site, where the reset hash can be captured. (We are not currently aware of another possible abuse via this mechanism.)

**Solution**

The changes described here add support for a list of allowed host names to be provided in the config.inc.php configuration file. User-supplied values are checked against this list and only one of the listed values will be allowed.

**Affected versions**

This issue affects *all releases* of OJS, OMP, and OPS versions 3.3.0-8 and older.

**How to resolve the issue**
1. Update the code to support the new `allowed_hosts` setting. This can be done by any of the following...
   1. Upgrade OJS, OMP, or OPS to version 3.3.0-9 or newer, *or*
   2. If using git, update to the latest `stable-3_3_0` or `stable-3_2_1` branches, *or*
   3. Apply the appropriate patch for your installation:
     - 3.3.0-9 and newer: Not affected.
     - 3.3.0-1 through 3.3.0-8: [OJS](https://github.com/pkp/pkp-lib/files/8157778/ojs-3.3.0-8.diff.txt) [OMP](https://github.com/pkp/pkp-lib/files/8157780/omp-3.3.0-8.diff.txt) [OPS](https://github.com/pkp/pkp-lib/files/8157781/ops-3.3.0-8.diff.txt)
     - 3.2.0 or 3.2.1: [OJS](https://github.com/pkp/pkp-lib/files/8157784/ojs-3.2.1-4.diff.txt) [OMP](https://github.com/pkp/pkp-lib/files/8157785/omp-3.2.1-4.diff.txt) [OPS](https://github.com/pkp/pkp-lib/files/8157786/ops-3.2.1-4.diff.txt)
2. Add an `allowed_hosts` setting to the `general` section of your `config.inc.php` configuration file. Here is the description/example from `config.TEMPLATE.inc.php`:
  ```
; Restrict the list of allowed hosts to prevent HOST header injection.
; See docs/README.md for more details. The list should be JSON-formatted.
; An empty string indicates that all hosts should be trusted (not recommended!)
; Example:
; allowed_hosts = '["myjournal.tld", "anotherjournal.tld", "mylibrary.tld"]'
allowed_hosts = ''
```
3. You can test whether or not the configuration is working by intentionally misconfiguring `allowed_hosts`. Attempting to load a page from the software should result in a `400 Bad Request` error page.

**Commits/pull requests**

(This is for tracking development work on the issue; you likely don't need to know this.)

PRs/commits:
- `main`:
  - https://github.com/pkp/pkp-lib/pull/7656
  - https://github.com/pkp/ojs/pull/3291
  - omp: https://github.com/pkp/omp/commit/570394176dd1d2b9dbdfcbd78d3a037d4bbdf14e
  - ops: https://github.com/pkp/ops/commit/586c281316db817f086ebc4f04d65b5491e3a7c5
- `stable-3_3_0`:
  - pkp-lib: https://github.com/pkp/pkp-lib/pull/7650
  - ojs: https://github.com/pkp/ojs/pull/3289
  - omp: https://github.com/pkp/omp/commit/006ebf92b1c23b983aed2fdd8d8151b050588690
  - ops: https://github.com/pkp/ops/commit/f75f58a7b1324637a97feb85f613f7e2df806452
- `stable-3_2_1`: 
  - pkp-lib: https://github.com/pkp/pkp-lib/commit/9abc0f70f8d151f153fe36270341938216f3e5c2
  - ojs: https://github.com/pkp/ojs/commit/1dfad486bcd14e7338db497bbb8dd67b0fad1667
  - omp: https://github.com/pkp/omp/commit/29c45954c385ee6ad8944edf187280ddbfeebcf5
  - ops: https://github.com/pkp/ops/commit/a2e7bb8d345af595620ae1aa590267a4a048b351

**Comment by asmecher** [comment]
@bozana, would you mind reviewing this before I port to the other apps and older branches? Thanks!

**Comment by barmintor** [comment]
Just want to add that this will also mitigate XSS vulnerabilities, thank you for moving quickly on it!

**Comment by jnugent** [comment]
Hi everyone,

Now that we've gone through and patched all of our own installations I wanted to share the patches we used, based off of @asmecher's work above.  For some of those there was a discrepancy in older versions of OJS3 where you'd get a fatal error about not being able to pass by reference.   The patch for 3.2 also removes the bits that attempt to patch the readme file that isn't in 3.1.

The original patch for 3.3 works perfectly.

OJS OMP 3.2.1 and 3.2.0: [ojs-3.2.1-4.diff.txt](https://github.com/pkp/pkp-lib/files/8343349/ojs-3.2.1-4.diff.txt)
Older OMP/OJS3: [older.diff.txt](https://github.com/pkp/pkp-lib/files/8343351/older.diff.txt)
OJS2: [ojs2-allowedHosts.diff.txt](https://github.com/pkp/pkp-lib/files/8343350/ojs2-allowedHosts.diff.txt)
