### ISSUE TITLE
inconsistent language names in registry/locales.xml

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#765]

**Comment by bozana** [comment]
The language names are sometimes in the given language and sometimes in English. An user asked if there could be "Русский" instead of "Russian". If so, I can make a pull request with the change...

**Comment by mtub** [comment]
@bozana We've planned to have the names in the respective language and replace the English names accordingly. I've changed a few of them when new new translations came in. Have to make sure that we use the same name in locale files and in the registry. Can go through all of them and patch accordingly. Do you mind if I take over?

**Comment by bozana** [comment]
@mtub, of course not :-) please go ahead... :-)

**Comment by mtub** [comment]
Will deal with other applications later on.

**Comment by asmecher** [comment]
Merged all 4 PRs, thanks!
