### ISSUE TITLE
admin page does not refresh when removing a journal from OJS multi-journal installation

### ISSUE THREAD

**Issue by heike-r** [pkp/pkp-lib#7654]
When I try to remove a journal in a multi-journal installation in the dashboard at the administration / hosted journals site, I can click on the 'remove' button, a window pops up to ask if journal should really be removed, I click yes but then nothing happens. The window is still there and no confirmation message pops up. However, if I refresh the browser page the journal is actually gone, so the removal itself worked. Just the site did not refresh.
 
PHP error log says
 `Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/ojs.domainname.de/lib/pkp/classes/notification/managerDelegate/PKPEditingProductionStatusNotificationManager.inc.php:78\nStack trace:\n#0 /var/www/ojs.domainname.de/lib/pkp/classes/notification/PKPNotificationManager.inc.php(338): PKPEditingProductionStatusNotificationManager->updateNotification()\n#1 /var/www/ojs.domainname.de/lib/pkp/classes/services/PKPSubmissionFileService.inc.php(562): PKPNotificationManager->updateNotification()\n#2 /var/www/ojs.domainname.de/lib/pkp/classes/submission/PKPSubmissionDAO.inc.php(129): PKP\\Services\\PKPSubmissionFileService->delete()\n#3 /var/www/ojs.domainname.de/classes/submission/SubmissionDAO.inc.php(51): PKPSubmissionDAO->deleteById()\n#4 /var/www/ojs.domainname.de/lib/pkp/classes/submission/PKPSubmissionDAO.inc.php(239): SubmissionDAO->deleteById()\n#5 /var/www/ojs.domainname.de/classes/services/ContextService.inc.php(164): PKPSubmissionDAO->deleteByContextId()\n#6 /var/w...', referer: https://ojs.domainname.de/index.php/index/admin/contexts`

This is in OJS 3.3.0.8. It is a'legacy' installation that started as 2.2.3.0 and has gone through 11 updates over the past 12 years. Might be our installation, that is at fault, not the current OJS code. Can someone check?

**Comment by asmecher** [comment]
@heike-r, that is a bug, in fact -- there was a bit of code that assumes that you are working with notifications while within a particular journal's portion of the OJS website, but the code that deletes a journal is in the administrator's area outside any particular journal.

If the journal is gone when you refresh the page, then at least most of it was deleted. However, it might've left some bits and pieces behind. We're gradually adopting database practices that will make this impossible (and the upgrade scripts that introduce it will clean up in the process); see https://github.com/pkp/pkp-lib/issues/6093 for details.

PRs:
- https://github.com/pkp/pkp-lib/pull/7655
- https://github.com/pkp/ojs/pull/3290

**Comment by asmecher** [comment]
@jonasraoni, could you review the above PRs? Thanks!

**Comment by jonasraoni** [comment]
@asmecher I just tested here, using the [datasets](https://github.com/pkp/datasets/). The fix makes sense and it works.

**Comment by asmecher** [comment]
Thanks, @jonasraoni! Merged to `stable-3_3_0`, forward-ported to `main`.
