### ISSUE TITLE
Configuration file format

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7659]
**Describe the problem you would like to solve**
Is there any plan to switch the configuration file to something else?
If not, perhaps we could use the [TOML](https://en.wikipedia.org/wiki/TOML) format, which looks very similar to what we have, and forward the maintenance of the parser to a package.

**Comment by asmecher** [comment]
Until we separate part of the app outside the web root (see https://github.com/pkp/pkp-lib/issues/1832), the configuration file will live within range of a request, thus will need to have a `.php` and `<?php exit();` at the head to prevent accidental exposure of the configuration to the web. Once we have a better place for it to live, I'd be open to changing its format to something more standard.

**Comment by jonasraoni** [comment]
We'll probably be able to migrate this idea to other formats, e.g. 
```json
{"<?php exit; ?>": "Don't remove"}
```
).

I just saw this `TOML` format and thought it could be used to decrease the code base... But as the parser is already small, not a big deal...

**Comment by henriqueramos** [comment]
Just to mentioned, exposed `TOML` had the same troubles as exposed `.env` files.

Here's an [old issue](https://github.com/pkp/pkp-lib/issues/7068) about using `.env` on PKP.
