### ISSUE TITLE
Ensure the build fails when there's an error in the migration tests

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7661]
**Describe the bug**
At this moment, the build is passing even when there's a failure in the upgrade test, we need to ensure such tests fail the build properly.

Current cases:
https://github.com/pkp/pkp-lib/issues/7646
https://github.com/pkp/pkp-lib/issues/7167#issuecomment-1024928275
https://github.com/pkp/pkp-lib/issues/7660

**Comment by asmecher** [comment]
Whoops, it looks like the upgrade script never had bash-friendly exit codes (particularly on upgrade failure). I've corrected this and will check into the other cases listed.

**Comment by asmecher** [comment]
This is now reporting errors properly -- closing, will review the other flagged issues.

**Comment by jonasraoni** [comment]
I can check this one: https://github.com/pkp/pkp-lib/issues/7167 =]

**Comment by jonasraoni** [comment]
FYI I fixed one more. This one was just emitting a warning: https://app.travis-ci.com/github/pkp/ojs/jobs/557983881#L4222

**Comment by jonasraoni** [comment]
Now we just need to fix OPS (https://github.com/pkp/pkp-lib/issues/7646), I can take a look on it later if nobody does it before me 😁
