### ISSUE TITLE
The DataCite Export plugin misrepresents page numbers of journal articles

### ISSUE THREAD

**Issue by felixhelix** [pkp/pkp-lib#7665]
**Describe the bug**
The DataCite Export plugin misrepresents page numbers od journal articles.
The page numbers are tagged with the "size" property.
The datacite metadate schema defines the "size" property as follows:

    Size 0-n Size (e.g. bytes, pages, inches, etc.)
    or duration (extent), e.g. hours,
    minutes, days, etc., of a resource.

and gives the following examples:

    Free text.

    Examples: "15 pages",
    "6 MB", “45 minutes”

https://schema.datacite.org/meta/kernel-4.3/doc/DataCite-MetadataKernel_v4.3.pdf

However, the current plugin generates xml like the following:

```
<sizes>
    <size>27-39 Pages</size>
 </sizes>

```
That is, instead of the page count, the page numbers are given.

A similar problem has been describes in https://forum.pkp.sfu.ca/t/update-to-ojs-3-1-1-4/51140/9

**What application are you using?**
 OJS version 3.3.0.8

**Possible Solution**

Datacite published a new metadata scheme, which includes new tags for page numbers:

>Addition of a new relatedItem property, with subproperties to contain specific details for
containing publication information previously encoded in a description field with
descriptionType=”SeriesInformation” (for example, to define the journal name,
volume, and page number for an article resource). Subproperties:
○ relationType
…
○ firstPage
○ lastPage
...

https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf

So, a solution could be to include this new property in DataCite Export Plugin, and either adjust the "sizes" property to correctly give the number of pages, or omit the size property.

Your's
Felix

<hr>

PR:
- https://github.com/pkp/ojs/pull/3934

**Comment by t-mayer** [comment]
Can confirm this behavior. The page numbers (instead of the page count) are generated inside a size property in the XML.
I am using OJS version 3.3.0.3

**Comment by felixhelix** [comment]
Thinking about this issue, It seems to me that the "pages" input field should be changed first: 

As of now, the field is named "pages", which is ambiguous and can be read as either the number of pages (i.e. 35 pages) or the numbering of the pages (i.e. pages 12-34). 
Also there is no input validation: One can also enter 2,3,6. 
Give this, the current input needs to be parsed at the export stage.

However, unstructured "pages" data already exist, which in case of a new input field would need to be transformed.

A middle way could be to at least validate the new input, so to only allow for either a single number, or two numbers seperated by a hyphen.

What do you think?

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR above?

**Comment by asmecher** [comment]
Thanks, all, I've merged https://github.com/pkp/ojs/pull/3934.
