### ISSUE TITLE
Ensure database schemas are fully synchronized after upgrading

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7670]
**Describe the bug**
At the [issue #7167](https://github.com/pkp/pkp-lib/issues/7167) I concluded the migration from the old database framework (< 3.3.0) has changed the way some database artifacts are created (at least on PostgreSQL).
Even though it's not critical, it's better to get it fixed to avoid unexpected issues.

**Solution**
- Grab different database versions (3.1.0, 3.2.0, 3.3.0, the more the better)
- Run the upgrade scripts until /main (3.4)
- Extract a schema-only script from them and compare the outputs for both MySQL and PostgreSQL
- Write a migration script in /main (3.4.0) to synchronize the found differences (e.g. modify constraints, types, default values, nullability, ...).

**What application are you using?**
/stable-3_2_1
/stable-3_3_0

**Additional information**
![image](https://user-images.githubusercontent.com/361921/152169055-67f49701-ca1e-42ae-9cc6-9c362b2e8747.png)

**Comment by asmecher** [comment]
@jonasraoni, starting with OJS/OMP/OPS 3.3.0 the schema creation tools are now built on Laravel migrations, whereas on 3.2.1 and prior they were done with ADODB XMLSchema. This introduces a bunch of semantic changes, e.g. in the way default values are specified, along with a few minor column type changes. When I committed the changes I did what you proposed -- comparing the "before" and "after" schema dumps. So I think it's already OK.

Looking at your example above, if I inspect the PostgreSQL table describe command's output for the `user_settings` table in `stable-3_3_0`, I get:
```
Indexes:
    "user_settings_pkey" UNIQUE CONSTRAINT, btree (user_id, locale, setting_name, assoc_type, assoc_id)
    "user_settings_locale_setting_name_index" btree (setting_name, locale)
    "user_settings_user_id" btree (user_id)
```
With `stable-3_2_1`, I get:
```
Indexes:
    "user_settings_pkey" UNIQUE, btree (user_id, locale, setting_name, assoc_type, assoc_id)
    "user_settings_locale_setting_name_index" btree (setting_name, locale)
    "user_settings_user_id" btree (user_id)
```
I think you're pointing out the difference in `user_settings_pkey`, which is listed as an index on the left and a constraint on the right. The difference is just in the mechanics; from [the PostgreSQL docs](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS):
> Adding a unique constraint will automatically create a unique B-tree index on the column or group of columns listed in the constraint.

Are you seeing other problems/mismatches?

**Comment by jonasraoni** [comment]
@asmecher I just saw this one, then I created an issue to inspect whether we've got extra divergencies.

Structurally everything's ok about this difference! But they are treated differently by the `Blueprint`, which is the why we have this try/catch here: https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/I7167_RemoveDuplicatedUserSettingsAndDeprecatedFields.inc.php#L96-L107

**Comment by jonasraoni** [comment]
Ah, the other mismatch that I found in the schema was related to those `reviewing` tables in OPS.

**Comment by asmecher** [comment]
^ Ah, interesting. I'll drop a link to this conversation into that code in case it's confusing later. Upgrade testing should catch cases like this, since they cover both ADODB and Laravel migration-based cases. I'll close this issue for now, but if there are other cases, please file them.
