### ISSUE TITLE
Section editors OJS 3.2.1.1

### ISSUE THREAD

**Issue by Mariaros** [pkp/pkp-lib#7671]
Topic: Section editors access

When a section editor is assigned, we can limit their access. We have decided to do so in one of our journals. This limitation means that the section editors can only give a recomandation for the MS, not make a descicion. However, because of this limitation, the section editor can not suggest revisions for the author, which means that any descisions must be made by the main editor. Is it possible to change or edit the access so the section editor can suggest revisions for the author, but can not decide to accept or decline?

And: Once the section editor will make her/his recommandation, the two options: 1: send an email for the editors with recommandation and 2: do not send email to the author. However you can only choose one, and in most cases you wish to choose both. Is it possible to create a default "Do not send email to author"?

Asked by journal editor
Thank you

**Comment by asmecher** [comment]
@Mariaros, this is more of a point for discussion than a bug or fully-specified feature request; would you mind starting out in the support forum (https://forum.pkp.sfu.ca)? If it can be turned into a full specification for a feature, then it'll be suitable for filing here in Github. Thanks!
