### ISSUE TITLE
Remove locale requirement in upgrade XML when installing new email templates

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7673]
**Describe the problem you would like to solve**
When a new email template must be installed during an upgrade, the upgrade script expects a list of locale keys to install. This is applied inconsistently and requires an upgrade maintainer to know more than they might. Examples:

```xml
<code function="installEmailTemplate" key="REVIEW_REINSTATE" locales="en_US" />
<code function="installEmailTemplate" key="STATISTICS_REPORT_NOTIFICATION" locales="ar_IQ,ca_ES,cs_CZ,da_DK,de_DE,en_US,es_ES,fi_FI,fr_CA,hi_IN,hu_HU,id_ID,it_IT,ku_IQ,pt_BR,pt_PT,ru_RU,sl_SI,sv_SE,tr_TR,vi_VN,zh_CN" />
```

**Describe the solution you'd like**
Refactor the `installEmailTemplate` code so that it installs the required locales based on the site's active locales.

**Who is asking for this feature?**
@asmecher:

> I think that function is asking too much of us as upgrade maintainers. I'd rather it was smartened up enough to not require exhaustive listing of locales.

**Additional information**
This work can be undertaken after #6328 is merged.

**Comment by touhidurabir** [comment]
@asmecher please review the PRs 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7673 Removal of locale requirement for email templates installation](https://github.com/pkp/pkp-lib/pull/8085)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7673 Submodule Update ##touhidurabir/i7673_main##](https://github.com/pkp/ojs/pull/3455)

if all ok , I will make the PR for OMP and OPS.

**Comment by NateWr** [comment]
Not a code review but just something to check. Does it work in the following case?

1. Install site with en_US.
2. Create journal with en_US.
3. Install fr_CA to site.

Do the email templates get installed in the `fr_CA` locale?

**Comment by touhidurabir** [comment]
@NateWr yes it will as `fr_CA` is now installed into the site . And it does as I have tested . this PR does not impact on the behaviour of locale management through the dashboard and that behaviour remains as it is now . 

Through this PR the `locales` for the email templates became optional but it still can be defined . if defined , it will work based on that but still run a check to filter out any invalid locales if passes which does not supported by site , say for example , `hi_IN`(Not yet supported into the system) . if none provided , it will be set according to installed locales . this change also applied for the command line tool `tools/installEmailTemplate.php`.

**Comment by touhidurabir** [comment]
@asmecher please review the PRs . I have rebased it to resolve the conflicts and also forward port the changes to `OMP` and `OPS`

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7673 Removal of locale requirement for email templates installation](https://github.com/pkp/pkp-lib/pull/8085)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7673 Submodule Update ##touhidurabir/i7673_main##](https://github.com/pkp/ojs/pull/3455)
[omp](https://github.com/pkp/omp) --> [pkp/pkp-lib#7673 Submodule Update ##touhidurabir/i7673_main##](https://github.com/pkp/omp/pull/1182)
[ops](https://github.com/pkp/ops) --> [pkp/pkp-lib#7673 Submodule Update ##touhidurabir/i7673_main##](https://github.com/pkp/ops/pull/333)

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I've merged the `pkp-lib` PR and closed the app PRs (submodule updates only).
