### ISSUE TITLE
Enable webservice support for PUT

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#768]
We support GET and POST; I need PUT, so that's the next one to be supported.

https://github.com/pkp/pkp-lib/blob/master/classes/webservice/WebService.inc.php#L86

**Comment by asmecher** [comment]
@ctgraham, are you still working on this? I don't see a PR from that branch.

**Comment by ctgraham** [comment]
Hmmm.., I wonder why the [PR](https://github.com/pkp/pkp-lib/pull/769) wasn't automatically linked here based on the title?

Maybe for the best, because I'm going to open another issue presently and add it into that PR.

**Comment by asmecher** [comment]
Merged and cherry-picked into master. Thanks!
