### ISSUE TITLE
DOI Management page or API endpoints should not be accessible when DOIs disabled

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7683]
**Describe the problem you would like to solve**
The new DOI Management page includes a context setting to enable/disable DOIs. When DOIs are disabled, I can still access the DOI Management page by going directly to the URL. While there, I see new submissions. I can select one, assign a DOI, and the message says "success", but it doesn't actually assign a DOI.

**Describe the solution you'd like**
Block access to the DOI Management page and DOI API endpoints when DOIs are disabled.

**Who is asking for this feature?**
Feedback on #7014.

**Additional information**
cc @ewhanson

**Comment by ewhanson** [comment]
Completed with #7522.
