### ISSUE TITLE
Improve use of Unregistered filter on DOI Management Page

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7684]
**Describe the problem you would like to solve**
When I filter by Deposit Status "Unregistered" on the DOI Management page, I see entries with Unpublished, Submitted, and Error statuses. This is confusing because it looks like a distinct status from the others.

**Describe the solution you'd like**
Make "Unregistered" only show submissions that are published and without submitted or error statues.

**Who is asking for this feature?**
Feedback on #7014.

**Additional information**
cc @ewhanson. See also #7682.

**Comment by ewhanson** [comment]
Resolved in #7682
