### ISSUE TITLE
Add Authorization header support to API interactions

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7685]
The API's authorization key middleware currently expects an API key specified in a GET parameter.

However, it's more secure and more standard to use an `Authorization:` header. (We already support this in `ArticleHandler` for requests that make use of the API key.)

Add support to the API to rely on `Authorization` headers for auth key transmission, and potentially deprecate the `apiToken` request parameter.

**Comment by NateWr** [comment]
The following PRs implement the Authorization header using the [Bearer authentication type](https://stackoverflow.com/questions/33265812/best-http-authorization-header-type-for-jwt) for JWTs. They do not remove support for the query parameter yet, but I agree we should discuss if/how we deprecate this.

These PRs haven't been manually tested yet.

https://github.com/pkp/pkp-lib/pull/7729
https://github.com/pkp/ojs/pull/3310

**Comment by asmecher** [comment]
@NateWr, thanks, I've tested this (works well), committed and forward-ported to `main`. I've added a note that I can grep about the apiToken parameter being deprecated with 3.4.0, but I think the most important thing is to update the API documentation to suggest that starting with 3.4.0 we recommend using the Authorization header.

Just FYI, here's a `curl` command to test it:
```
curl -H "Authorization: Bearer API_KEY_HERE" "http://.../index.php/publicknowledge/api/v1/users"
```
