### ISSUE TITLE
Evaluators requisition emails, password changes and etc aren't sent when user's language is set to portuguese

### ISSUE THREAD

**Issue by leonardorodriguesds** [pkp/pkp-lib#7686]
**Describe the bug**
evaluators requisition emails, password changes and etc aren't sent when user's language is set to portuguese

**To reproduce**
1 - Change the language to portuguese
2 - Ask for a password change

**What application are you using?**
OJS 3.3.0.8

**Additional information**
The system also doesn't send news emails. However, it does send the emails to any user with language set to english.

**Comment by asmecher** [comment]
@leonardorodriguesds, I'm pretty certain that these emails are being sent by OJS, but they are being filtered / spam trapped. OJS doesn't decide to send/not send emails based on what locale is being used. I would suggest looking into your DMARC configuration to ensure that emails are being delivered as expected.
