### ISSUE TITLE
Include Date Published for Articles in Statistics Reports (Views, Articles, Custom)

### ISSUE THREAD

**Issue by emmauhl** [pkp/pkp-lib#7691]
**Describe the problem you would like to solve**
Editors for journals using continuous publishing models would like to track article statistics using the date the article was published, which is not included in current statistic reports. They may want to track views or other article statistics by grouping articles by the month/week they were published rather than being confined to grouping them by issue vol/num or the date the issue was published (an issue published in Jan 2022 using this model may contain articles from several months after Jan 2022, for example).

**Describe the solution you'd like**
Please include the date the article was published as a metric within relevant generated reports (Views, Articles, Custom Report Generator).

**Who is asking for this feature?**
This has been requested by a PKP|PS client journal editor. This will help journals comply with Plan S. See [comment](https://github.com/pkp/pkp-lib/issues/7691#issuecomment-1144291993).

**Comment by NateWr** [comment]
It looks like the date published is already available in the Views report but is missing from the Articles and Custom Report Generator.

**Comment by kshuttle** [comment]
The need for a "Date Published" field in the Articles report is also related to the Plan S requirement for journals to publish their average time between submission and publication. If "Date published" was included in the article report it would be possible to use a simple formula in excel to calculate Date Published minus Date Submitted to see number of days from submission to publication. The number of days could then be averaged to get the stat required by Plan S.

+1 for this issue from a PKP | PS client interested in helping their journals comply with Plan S. At this point requests from PKP | PS clients for Plan S specifications are infrequent, so if this feature can be accommodated in 3.4, it is not recommended that it also needs to be back ported to 3.3.

**Comment by bozana** [comment]
PRs:
pkp-lib: https://github.com/pkp/pkp-lib/pull/8237
ojs: https://github.com/pkp/ojs/pull/3536

**Comment by bozana** [comment]
@NateWr, may I ask you to take a look at the PR?

**Comment by NateWr** [comment]
@bozana looks good. Do we need this for OPS or OMP too?

**Comment by bozana** [comment]
Thanks @NateWr! I've merged. Nothing needed for OMP and OPS -- no such plugin there...
