### ISSUE TITLE
Investigate replacing Slim with Laravel-based routing toolset

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7698]
Currently the API routers use the Slim microframework.

As we move towards more complete adoption of the Laravel toolset, it makes sense to remove this dependency in favour of something in the Laravel ecosystem (either Lumen or the full-fledged Laravel routing toolset).

(The page and component routing toolset does not use Slim, and shouldn't be touched for the moment.)

**PRs**

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9176
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3980
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1470
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/578

### How to convert a PKP `Handler` class into a Laravel `Controller` class
While converting a handler class to controller class, about 90%-95% code remain same . Also the name of each method can be remain same but the method signature need to be updated . First note that the current handler class are used directly via the `APIRouter` but to use laravel routing system , we need to use either closure based or controller based approach . But we still need to have the `APIHandler` as `APIRouter` expect that . To facilitate it, we can have a single API Routing Handler that can works as a bridge between these. The conversion process can be proceed as follow 

1. Create new `Controller` class say `UserController` and must extends the `PKP\core\PKPBaseController` . 

2. `PKPBaseController::getHandlerPath` `abstract` method return the handler path that is same as `APIHandler::_handlerPath` property.

3. `PKPBaseController::getRouteGroupMiddleware` `abstract` method return the list of middleware that should be applied to every defined routes . This can be considered as the laravel compatible replacement for `APIHandler::authorize` method . But it can be used to apply any kind of middleware than just to apply specific authorisation.

Consider following implementation example from Converted [UserController](https://github.com/pkp/pkp-lib/pull/9176/files#diff-1c6d20282f76fab128a0ef96ceb7f1a36bd90b0e16ae47f35edabf631df39148R40-R53)
```php
/**
 * @copydoc \PKP\core\PKPBaseController::getRouteGroupMiddleware()
 */
public function getRouteGroupMiddleware(): array
{
    return [
        "has.user",
        "has.context",
        self::roleAuthorizer([
            Role::ROLE_ID_SITE_ADMIN, 
            Role::ROLE_ID_MANAGER, 
            Role::ROLE_ID_SUB_EDITOR
        ]),
    ];
}
```

NOTE that it is also possible to attach middleware to each route as such 
```php
Route::put('/post/{id}', function (string $id) {
    // ...
})->middleware('role:editor');

// or

Route::put('/post/{id}', function (string $id) {
    // ...
})->middleware([SomeMiddleware::class, ...]);
```

4. `PKPBaseController::getGroupRoutes` `abstract` method contains the routes list as follow as example 
```php
public function getGroupRoutes(): void
    {       
        Route::get('ROUTE_PATH', $this->CONTROLLER_METHOD(...))
            ->name('ROUTE_NAME');
    }
```
See implementation example from [UserController](https://github.com/pkp/pkp-lib/pull/9176/files#diff-1c6d20282f76fab128a0ef96ceb7f1a36bd90b0e16ae47f35edabf631df39148R55-R69)

5.  `PKPBaseController::getPathPattern` method can be used as the replacement of `APIHandler::_pathPattern` property to over ride the handler route path pattern . 

6. `PKPBaseController::isSiteWide` method can be used as the replacement of `APIHandler::_apiForAdmin` property to over ride if route will be available as global or context level api .

7. To register the generated controller as the new route handler,  just need to register it the app level api handler index file as follow 
```php
return new \PKP\handler\APIHandler(new \PATH\TO\CONtROLLER());
```
8. In the controller class, each method must take param as the `Illuminate\Http\Request` instance . And for the return, it can be an instance of `\Illuminate\Http\Response` or `\Illuminate\Contracts\Routing\ResponseFactory` . for example 
```php
public function getReport(Request $request): StreamedResponse|JsonResponse
```
Also for `json` return response , the following similar replacement can be used over the slim api response implementations 
```php
return response()->json([
    'error' => __('api.404.resourceNotFound')
], Response::HTTP_NOT_FOUND);
```

9. Finally the `PKP\core\PKPRoutingProvider` is the coar routing provider where the global middleware are registered that must need to run before every api route and possible to add more by adding to `static` property `$globalMiddleware` . 

10. The core `lib/pkp` policy authorizers at the path `classes/security/authorization` are glued through middleware [PKP\middleware\PolicyAuthorizer](https://github.com/pkp/pkp-lib/pull/9176/files#diff-228b49c32682961ae1c661345016fa6ba5d11212dbcd35774a55f725d6a60104) which runs the almost same implementation(only modification is type hints) as in the `PKPHandler::authorize` for existing policy authorization process . This is done through the combination of porting all the same functionality into the [PKP\core\PKPBaseController](https://github.com/pkp/pkp-lib/pull/9176/files#diff-3f4a369cb3637eae79466600a8fabb027e5fab9314b8b6532e0b2ab19146538eR182-R374) and apply a bit of reflection to run these before the actual route controller action run . 

11.

**Comment by NateWr** [comment]
One of the biggest potential benefits here is the possibility to use the router to generate URLs. Our current approach to constructing a URL requires that a lot of our code has a `Request`, and this doesn't work great in a CLI command.

Lumen lets you [generate URLs to named routes](https://lumen.laravel.com/docs/8.x/routing#named-routes) and Symfony offers [a similar feature](https://symfony.com/doc/current/routing.html#generating-urls-in-services). It doesn't appear to be a feature of the `FastRoute` library that Lumen uses. 

As far as I can tell, the biggest benefit is the ability to define and then pass named arguments in the route string. For example, a route like this:

```
/{contextPath:\s+}/example/{submissionId:\d+}/revisions/{roundId:\d+}
```

Can construct the appropriate URL with a call like this:

```
$router->url($context, [
    'submissionId' => $submissionId,
    'roundId' => $roundId,
]);
```

**Comment by touhidurabir** [comment]
@asmecher Draft PRs to review
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9176
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3980

**Comment by henriqueramos** [comment]
@touhidurabir @asmecher Found this some time ago. Could help on understanding how to implement the `illuminate/routing` package itself.

https://github.com/mattstauffer/Torch/blob/master/components/routing/index.php

**Comment by touhidurabir** [comment]
@asmecher check the updated PRs at https://github.com/pkp/pkp-lib/issues/7698#issue-1132905079 modified based on initial review .

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I've added a couple more comments; let's talk about this, but in brief, it's looking very good, thanks!

**Comment by touhidurabir** [comment]
@asmecher see the handler to controller class upgrade process described at https://github.com/pkp/pkp-lib/issues/7698#issue-1132905079 .

**Comment by asmecher** [comment]
@defstat, could you have a look at the description and PRs in the head comment? This is a pattern we'd like to roll out broadly to replace Slim with Laravel for routing API requests.

**Comment by asmecher** [comment]
(@jonasraoni, you might have some good feedback too!)

**Comment by touhidurabir** [comment]
@asmecher see the `Point NO 10` at `How to convert a PKP Handler class into a Laravel Controller class` at https://github.com/pkp/pkp-lib/issues/7698#issue-1132905079 about how the existing authorizers and policies are glued to laravel route . The core implementation code sections are also linked in that comment . Please review that part as I think this is the last complicated and challenging part for this issue .

**Comment by asmecher** [comment]
@touhidurabir, I checked out your branches for `ojs` and `pkp-lib` but was unable to save any of the journal settings (this would be the `PKPContextController`). I get `401` responses to the save requests. Is this a known problem?

**Comment by touhidurabir** [comment]
> @touhidurabir, I checked out your branches for ojs and pkp-lib but was unable to save any of the journal settings (this would be the PKPContextController). I get 401 responses to the save requests. Is this a known problem?

@asmecher we did not have any user resolver logic when api calls are made from within the app without any api keys, I missed this as I am testing from some api client apps with api key . I have fixed it, tested and seems working . should be good to try again now .

**Comment by touhidurabir** [comment]
@asmecher done for `pkp-lib` and `ojs` for now only and I have made the PR as non draft mode to run tests . Once I make the `OJS` tests green, I will move to `OMP` and `OPS` .

**Comment by touhidurabir** [comment]
@asmecher Please review the changes . All changes are done and ported to `OJS`, `OMP` and `OPS` . 

`OMP` tests are all green . 
`OJS` test is only failing for one build on one specific test `Y_NativeXmlImportExportIssue.cy.js`  which does not seems to be related to this issue but I am looking into it . 
`OPS` tests are all failing for all build on `DOI.cy.js` for specific changes `Check Assignment for multi-version submissions` which I am looking into .

**Comment by touhidurabir** [comment]
@asmecher All tests are green . Please review.

**Comment by asmecher** [comment]
@touhidurabir, congratulations! I've merged all of this.
