### ISSUE TITLE
Consider adding "save and continue" to setup forms

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#770]
...to permit stepping through them one at a time.

**Comment by NateWr** [comment]
Is this during the settings wizard? Which settings pages are these? I can't seem to find them based on the URL that Kevin posted in the ux review doc.

**Comment by asmecher** [comment]
The wizard does have a Save & Continue; this is after that's all said and done, when you go through the normal settings area through the dashboard. This would step through the tabs.

**Comment by NateWr** [comment]
I worry that this could be confusing with very little gain. In almost every piece of software I use, saving a settings page returns the same settings page with updated values. They're structured as tabs, not as a step-by-step wizard. And I'm not convinced there's much of a logical sequence to our settings pages either. When I save new Author Guidelines, do I always want to edit the Series?

Clicking save and being presented with a completely different page could be confusing. And I'm not sure -- outside of the initial setup wizard -- it will be frequently useful.

**Comment by asmecher** [comment]
Kevin and I agree, @NateWr.
