### ISSUE TITLE
Refactor relationship between Mailables and Email Templates

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7706]
**Describe the problem you would like to solve**
We introduced [Mailables](https://laravel.com/docs/9.x/mail), which now represent when an email happens, such as a user registration, review assignment, etc. We need to connect `Mailables` to `EmailTemplate`s in OJS/OMP/OPS.

**Describe the solution you'd like**
Each `Mailable` should be able to be associated with one or more `EmailTemplates`. When the manager configures email templates, they should interact with `Mailable`s by assigning email templates, editing email templates or removing email templates. This means that some of the data that was stored with an `EmailTemplate` should now be attached to a `Mailable`.

**Who is asking for this feature?**
This is a necessary part of the email refactor for 3.4

**Additional information**
Much of the data in the `emailTemplates.xml` file should be moved to the `Mailable` classes. For example, consider the following email template XML record:

```xml
<email 
	key="EDITOR_DECISION_ACCEPT" 
	can_edit="1" 
	can_disable="0" 
	from_role_id="16" 
	to_role_id="65536" 
	stage_id="3" 
	subject="emails.editorDecisionAccept.subject" 
	description="emails.editorDecisionAccept.description" 
	body="emails.editorDecisionAccept.body"
/>
```

This corresponds to a class like this:

```php
namespace PKP\mail\mailables;

class DecisionAcceptNotifyAuthor extends Mailable
{
    protected static ?string $name = 'mailable.decision.accept.notifyAuthor.name';
    protected static ?string $description = 'emails.editorDecisionAccept.description';
    protected static ?string $defaultSubject = 'emails.editorDecisionAccept.subject';
    protected static ?string $defaultBody = 'emails.editorDecisionAccept.body';
    protected static ?string $emailTemplateKey = 'EDITOR_DECISION_ACCEPT';
    protected static bool $supportsTemplates = true;
    protected static array $groupIds = [self::GROUP_REVIEW];
    protected static int[] $stageIds = [WORKFLOW_STAGE_ID_EXTERNAL_REVIEW];
    protected static int[] $fromRoleIds = [ROLE_ID_MANAGER];
    protected static int[] $toRoleIds = [ROLE_ID_AUTHOR];
    protected static bool $canDisabled = false;

    ...
}
```

The `can_edit` flag should be removed.

When `Mailable::$supportsTemplates` is true, it should be possible to associate more than one `EmailTemplate` with the mailable. This is the case for emails where the sender can load alternative templates before sending the email.

In the end, this should result in a `GET /mailables` API endpoint that supports the filtering options currently available on `GET /emailTemplates`. Those filtering options can be removed from `GET /emailTemplates`. No other endpoints should be needed for `/mailables`, however, the `/emailTemplates` endpoints will need to be extended:

- Add filter to `GET /emailTemplates` so that email templates can be fetched by their assigned `Mailable`.
- Allow mailable associations to be saved with calls to `POST /emailTemplates` and `PUT /emailTemplates`.

**Comment by Vitaliy-1** [comment]
Thinking about it, what about completely removing `emailTemplates.xml` and adding default data also to editable Mailables? E.g., for mailable associated with reviewer assignment:
```php
class MailReviewerAssigned extends Mailable
{

  public const EMAIL_TEMPLATES = [
        'REVIEW_REQUEST' => [
            'subject' => 'emails.reviewRequest.subject',
            'body' => 'emails.reviewRequest.body',
        ],
        'REVIEW_REQUEST_SUBSEQUENT' => [
            'subject' => 'emails.reviewRequestSubsequent.subject',
            'body' => 'emails.reviewRequestSubsequent.body',
        ],
    ];
}
```
It doesn't look like other default data like `fromRoleIds` is different in templates bundled to one Mailable, so just specifying it like a simple property should do. Or, if the association with templates should be preserved, hardcode them as an example above.

**Comment by asmecher** [comment]
(Just dropping in to say: very supportive of removing the `emailTemplates.xml` files. These became especially silly when their localization was moved into Weblate.)

**Comment by NateWr** [comment]
I'm ok with removing `emailTemplates.xml`, but I want to avoid coupling `Mailables` to `EmailTemplates` too closely. Right now, it's entirely possible for a `Mailable` to have no relationship to an `EmailTemplate`. It's also possible for an `EmailTemplate` to exist with no relationship to a `Mailable`. The more we mix concerns the less flexible we make both objects.

If we go this route, you might want to think about how an `EmailTemplate` would be discovered and installed when it has no relationship to a `Mailable`.

On the specific implementation: I think using a `const` is going to cause problems when we get to distributing code across the apps. Since a `const` can't be changed, we'll run into cases where we want a `Mailable` to extend a base class but have different email template relationships.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/7891
OJS: https://github.com/pkp/ojs/pull/3386

**Comment by asmecher** [comment]
Belated congratulations on this, @Vitaliy-1!
