### ISSUE TITLE
Reviewer's competing interests should be visible for journal editors before review files are uploaded

### ISSUE THREAD

**Issue by illipsum** [pkp/pkp-lib#7711]
If a reviewer acknowledges possible competing interests when asked for a review those are visible for the journal editors only AFTER the review process is finished by the reviewer and review files are uploaded. Journal editors should be informed about competing interests beforehand so that they could assign a different reviewer if they decide to do so.

**Comment by NateWr** [comment]
@illipsum we prefer to receive feature requests in our [feature request forum](https://forum.pkp.sfu.ca/c/questions/feature-requests/8), where our community can get involved to discuss or support the request. Can you please post your request there?
