### ISSUE TITLE
Build package fails with npm 8

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7719]
**Describe the bug**
When trying to build the JavaScript package for `stable-3_3_0` on npm 8, it ends in an error:

```
sh: 1: vue-cli-service: not found
```

**To Reproduce**
1. Try to build `stable-3_3_0` with npm 8 installed.

**What application are you using?**
`stable-3_3_0`

**Additional information**
See [forum report](https://forum.pkp.sfu.ca/t/problems-installing-from-git-stable-3-3-0/72046) and [proposed PR](https://github.com/pkp/ojs/pull/3307).

**Comment by leocsilva** [comment]
https://github.com/pkp/omp/pull/1069
https://github.com/pkp/ops/pull/237
https://github.com/pkp/ui-library/pull/181

**Comment by NateWr** [comment]
@leocsilva can you double-check your OJS pull request? The tests are [failing on the build step](https://app.travis-ci.com/github/pkp/ojs/jobs/560551726#L1266) so something seems to be off. I restarted the tests once to see if it was a one-off, but they failed again. The OMP, OPS and UI Library tests are all passing, so I'm not sure what would be the issue.

**Comment by leocsilva** [comment]
@NateWr, I can't believe my pull request could have caused this error. Could you run the test again without the changes from my pull request?

**Comment by NateWr** [comment]
I was surprised too. That's why I re-ran the tests to be sure it wasn't a hiccup. You can see other recent builds passing our test suite here (look for tests against `stable-3_3_0`): https://app.travis-ci.com/github/pkp/ojs/builds 

It's unclear to me why this would effect OJS but not the other PRs. I can only spot two possible problems: a [peer dependency issue](https://app.travis-ci.com/github/pkp/ojs/jobs/560551726#L1255) and a [linting error](https://app.travis-ci.com/github/pkp/ojs/jobs/560551726#L1271-L1275). With the latter, all I can think of is that maybe vue cli 4.5.15 is stricter than 4.5.9 in some way that's catching us out? Or the version of node in our travis tests is causing an issue...

I've gone ahead and restarted the tests again, just in case it was a one-off that day.

**Comment by NateWr** [comment]
Looks like the tests failed again. Are you able to run `vue-cli-service lint js/load.js lib/pkp/js/load.js lib/pkp/js/classes/VueRegistry.js` locally? 

There is some further information in our linting test: https://app.travis-ci.com/github/pkp/ojs/jobs/560551725#L1469-L1488

**Comment by leocsilva** [comment]
```bash
leocsilva@localhost:~/cti/stable-3_3_0> npm run lint

> OJS3@3.3.0 lint
> vue-cli-service lint js/load.js lib/pkp/js/load.js lib/pkp/js/classes/VueRegistry.js

 DONE  No lint errors found!
```

**Comment by NateWr** [comment]
@asmecher can you pick this up? This is a fairly minor dependency update to `stable-3_3_0`, but it's leading to a test failure in OJS. No other apps are effected, and I can't reproduce the error locally. I wonder if it's related to the version of node/npm on the travis server? :shrug:

**Comment by asmecher** [comment]
Hi all -- I've merged all 4 PRs, after investigating the OJS issue. It looks like Travis sometimes defaults to bionic, sometimes to xenial, and this was causing the failure with OJS when the others worked. I've added an explicit `dist: bionic` to all apps on `stable-3_3_0` (we already have this on `main` for similar reasons) and the tests should pass now. :crossed_fingers:

**Comment by NateWr** [comment]
Thanks @asmecher and @leocsilva! Forward-ported all four PRs to `main`.
