### ISSUE TITLE
Respond to nonexistent monographs with a 404

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#772]
May facilitate http://forum.pkp.sfu.ca/t/how-to-remove-a-journal-from-google-scholar/4218/4

**Comment by asmecher** [comment]
@beghelli, could you give this a careful review? Here's the rationale:

Previously, AuthorizationDecisionManager, PolicySet, and AuthorizationPolicy were all independent classes. They duplicated some functions and code. One problem is that while AuthorizationPolicies could supply callback advice, PolicySets could not.

Rather than duplicate the relevant code in PolicySet, I decided to make a subclass relationship:

- AuthorizationDecisionManager
 - PolicySet
   - AuthorizationPolicy

... and remove all the duplicated methods.

**Comment by beghelli** [comment]
@asmecher Sorry the delay, looking into it now. 

My first worry is that we are breaking the conceptual idea here. Policy set objects are not authorization policies, they are objects that have authorization policies. Also, the authorization decision manager is not a policy set.

The callback advice should be implemented by authorization policies only right? I mean, those are the ones that have effect method that decides between deny and accept. So it should be up to them also to implement also the callback. Do you have an use case where you need the policy set to define the advice callback? If many authorization policies need to share the same callback, why not implement a base authorization policy class that implements that callback and use that for the other policies?

Just initial thoughts, I am waiting for your feedback.

**Comment by asmecher** [comment]
Here's the policy change that led me down this rabbit-hole:
https://github.com/pkp/pkp-lib/pull/773/files#diff-a44e423067de7f99b59c90f2fe2bccebR26
Without the ability to add callback advice to policy sets, it wasn't clear to me where a good place to add this behavior was.

**Comment by beghelli** [comment]
the SubmissionRequiredPolicy.inc.php is already an AuthorizationPolicy right? Why not leave it there? You wanted to move this behavior to anywhere else?

**Comment by beghelli** [comment]
@asmecher is this still relevant?

**Comment by asmecher** [comment]
@beghelli, I haven't had time to look at it for a while. Do you feel like taking it over? Feel free to discard my approach if you don't think it makes sense; on the plus side I did feel like it removed a lot of duplicated concepts.

**Comment by asmecher** [comment]
Solved much more simply.
