### ISSUE TITLE
Update php-cs-fixer to v3

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7722]
**Describe the problem you would like to solve**
When running php-cs-fixer, the following notice is shown:

> You are running PHP CS Fixer v2, which is not maintained anymore. Please update to v3.
> You may find an UPGRADE guide at https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.3.0/UPGRADE-v3.md .
> If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!

v2 may not support some of the newer language features that we are adopting for PHP 8/8.1.

**Describe the solution you'd like**
Upgrade the php-cs-fixer to v3 while minimizing disruptive changes to the codebase in case of minor syntax changes.

**Comment by jonasraoni** [comment]
There's an issue here: https://github.com/pkp/pkp-lib/issues/7313 =]

**Comment by NateWr** [comment]
lol, I even worked on it and forgot! https://github.com/pkp/pkp-lib/issues/7313
