### ISSUE TITLE
Check Submissions Files ojs3

### ISSUE THREAD

**Issue by JohnKlark** [pkp/pkp-lib#7723]
Hi,I uploaded the plugin created by @jedi-tor:

https://github.com/firatakin/checkSubmissionFiles

but it keeps giving me the error below
![img01](https://user-images.githubusercontent.com/100204705/155127983-132b8476-8ffb-4bab-b016-96dd8cc576de.jpg)

Should I update any information within the PHP file?
We require authors to upload two files as mandatory for the submission.

*We are using OJS 3.3.0.8

_Originally posted by @JohnKlark in https://github.com/pkp/pkp-lib/issues/3100#issuecomment-1047723533_

**Comment by asmecher** [comment]
https://github.com/pkp/pkp-lib/issues/3100#issuecomment-1047725450
