### ISSUE TITLE
Can't cancel DOI assignment

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7724]
**Describe the bug**
In the new DOI management panel, when I use the Bulk Actions to Assign DOIs, it opens a small dialogue modal to confirm. If I try to click cancel in this modal, nothing happens.

**To Reproduce**
1. Enable DOIs in Settings > Distribution > DOIs for issues and submissions.
2. Have at least one published issue without a DOI assigned.
3. Go to DOIs > Issues.
4. Select the checkbox beside the issue.
5. Click Bulk Actions > Assign DOIs
6. See the confirmation dialog and click Cancel
4. See that nothing happens.

**What application are you using?**
`main` 3.4 pre-release

**Additional information**
@ewhanson this may be a bug related to my rebase for #7265. If you can't reproduce it quickly, leave it until that is merged and we can revisit this issue.

**Comment by ewhanson** [comment]
@NateWr, I wasn't able to reproduce it on OJS, OMP, or OPS, so checking in after #7265 sounds good.

**Comment by NateWr** [comment]
I was unable to reproduce this.
