### ISSUE TITLE
Code in abstact

### ISSUE THREAD

**Issue by Mariaros** [pkp/pkp-lib#7728]
In OJS 3.1 we have the possibility to code the text in abstracts. We find this very useful in order to ajust the headings to theme. However, this is not available in OJS 3.2.1.1. Is it somehow possible to code in abstract in this version? 
And will it be possible in OJS 3.3?

**Comment by NateWr** [comment]
We have no plans to support this. The use of extra HTML code in abstracts may cause problems with downstream consumers through OAI, Crossref exports, etc. However, if you still want to make use of this, there is a plugin that allows you to add the code editing button to several TinyMCE fields, including the abstract.

The plugin is Text Editor Extras and you can install and configure it from Settings > Website > Plugins > Plugin Gallery.
