### ISSUE TITLE
Native XML import creates submissions that cannot be edited

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7730]
**Describe the bug**
There's a locale field on the publications table and also one that is deprecated on the submissions table.  When importing Native XML, only the publications table gets the locale set because the submissions locale field is deprecated.  This however  makes it impossible to edit the metadata of an imported submission, even if all locales required by submissions are filled in (green icons):

![Screenshot at 2022-02-24 14-10-55](https://user-images.githubusercontent.com/218719/155584784-3604934b-b58c-4164-9649-36b078962b50.png)

Looking at the post request when saving the form, we get back a "400 Bad Request" response:

![Screenshot at 2022-02-24 14-11-15](https://user-images.githubusercontent.com/218719/155584866-40eafd3e-a79d-4080-b4d0-9c74ee6d8ad9.png)

And the returned JSON looks like it's complaining about a missing abstract, but the locale isn't set:

![Screenshot at 2022-02-24 14-11-34](https://user-images.githubusercontent.com/218719/155584851-17e0f98d-674c-463f-964a-f06c3fff36d5.png)

Manually updating the locale field in the submissions table allows the metadata form to save correctly.

**To Reproduce**
1. Perform native import XML
2. Verify in the database the the submissions locale field is null 
3. Attempt to edit and save the metadata, it should fail.
4. Manually set the locale field in the submissions table to something e.g. en_US, and attempt the edit again.  It should work.

**What application are you using?**
3.3.0.8

**Additional information**
I can provide an XML sample for this.  This may not be a bug in the Native import?

**Comment by jonasraoni** [comment]
Hi @jnugent! I'll close this one, because there's already an issue here: https://github.com/pkp/pkp-lib/issues/7636
