### ISSUE TITLE
Manuscript theme - User menu floating over journal title in Arabic Language interface

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#7733]
**Describe the bug**
There is an issue with the User menu location when the journal editor enables Arabic or R-to-L languages. If you are note using a Journal logo, the menu will be floating over the Journal title.
It seems that this element is not switching to the left side of the screen how it should.
 
**To Reproduce**
1. Enable the Arabic language to the journal
2. Remove the journal logo
3. On the public reader interface, switch to the Arabic language
4. See error on top bar

**What application are you using?**
 OJS  version 3.3.0-8

**Additional information**
Demo Journal using Default Theme:
![image](https://user-images.githubusercontent.com/4992902/156085301-8aed25f7-7288-486d-bc35-c466e83f6394.png)

Demo Journal using Manuscript Theme (Default child theme):
![image](https://user-images.githubusercontent.com/4992902/156085390-6b3c6399-9a65-475a-b7f6-4dd91eeb0d54.png)

I've highlighted the menu floating over the Title.

**Comment by israelcefrin** [comment]
I've filled a PR to patch it, could you please review it @NateWr ?
https://github.com/NateWr/defaultManuscript/pull/38

**Comment by NateWr** [comment]
@israelcefrin if this effects the Manuscript theme then it also effects the default theme in OJS/OMP/OPS. All of the layout in Manuscript is inherited from the Default theme. Can you open a PR to fix this in the Default theme? There is a `rtl.less` file in the Default theme to handle these cases.
