### ISSUE TITLE
Request for revision modal missing/undefined

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7735]
**Describe the bug**
When clicking "Request Revisions" in the "Review" tab of the submission workflow, the expected modal does not open and the browser console presents the following error: `TypeError: can't access property "hiddenFields", e.components.selectRevisionDecision is undefined`. The state components are not correctly being passed to the template and Vue component.

**To Reproduce**
1. Go to a submission in the review stage.
2. Click on "Request Revision"
3. Nothing will visibly happen on the page.
4. See error in browser console.

**What application are you using?**
 OJS `main` branch

**Additional information**
@asmecher, this is the Editorial Decisions bug I mentioned earlier (Mon, Feb. 28). I found the culprit and it's quick fix. The variable names should be `$state` instead of `$stage` here: https://github.com/pkp/pkp-lib/blob/ab54ebc627a7377f1d10da38535d7ef8473c3bd2/pages/workflow/PKPWorkflowHandler.inc.php#L413-L414

~~Would you prefer if I created a discrete bug fix PR for this or would it be okay if I rolled it into my DOI PR that will just need rebase?~~ Thanks!

**Comment by ewhanson** [comment]
Hey @asmecher, I went ahead and made a bug fix PR for this. Could you have a look? Thanks!

PRs:

- `pkp-lib`: #7738
- `ojs`: pkp/ojs#3316
- `omp`: pkp/omp#1076
- `ops`: pkp/ops#244

**Comment by asmecher** [comment]
Ha! That's the kind of typo you can squint at for a long time before you see it. I've merged it all, thanks!
