### ISSUE TITLE
DOI migration fails when `chunkById` operations execute more than once

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7737]
**Describe the bug**
Laravel's `chunkById` method needs to have the table as well as the column specified in operations in `I7014_DoiMigration.inc.php`. 
**To Reproduce**
1. Upgrade an application to 3.4.
2. See error:

> 2022-03-02 11:04:32 [downgrade for "PKP\migration\upgrade\v3_4_0\I7167_RemoveDuplicatedUserSettingsAndDep recatedFields" unsupported: Downgrade unsupported due to removed data] ERROR: Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'publication_id' in where clause is ambiguous (SQL: select s.context_id, p.publication_id, p.doi_id, pss.setting_name, pss.setting_value from submissions as s left join publications as p on p.subm ission_id = s.submission_id left join publication_settings as pss on pss.publication_id = p .publication_id where pss.setting_name = pub-id::doi and publication_id > 2433 order by publication_id asc limit 1000)

**What application are you using?**
OJS/OMP/OPS `main` branch

**Additional information**
See pkp/ojs#3314.

**Comment by ewhanson** [comment]
Hi @asmecher, here's @Falk358's PR along with the change ported over to all other tables with DOIs. Assuming everything with the testing looks good, they should be good to go. Thanks!

PRs:

- `ojs` from @Falk358: pkp/ojs#3314
- `ojs`: pkp/ojs#3315
- `ops`: pkp/ops#243
- `omp`: pkp/omp#1075

**Comment by asmecher** [comment]
Thanks, @ewhanson, all merged!
