### ISSUE TITLE
Plugin Gallery empty on OJS 3.3.0-10

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#7752]
**Describe the bug**
After upgrade to OJS 3.3.0-10 Plugin Gallery is empty.
I also tried it on a fresh OJS 3.3.0-10 install and it always comes out empty without any plugins

**To Reproduce**
Upgrade or install OJS 3.3.0-10 and go on Plugin Gallery

**What application are you using?**
 OJS version 3.3.0-10

**Comment by asmecher** [comment]
Whoops, I forgot to add the compatibility statements to the gallery! Fixed, thanks.

**Comment by slaotie** [comment]
@asmecher Plugin Gallery always loading

**Comment by slaotie** [comment]
@asmecher Thank you. That problem has been solved
