### ISSUE TITLE
Confirm review broken in the main branch

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7759]
**Describe the bug**
When confirming a review, the application throws a fatal error.

**To Reproduce**
1. Go to a submission in the review stage
2. Add a reviewer.
3. Click the arrow beside the reviewer to open options
4. Click Review details
5. Select a recommendation
6. Click confirm
7. See that the form does not save and the error is in the log

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
In `SubmissionEventLogEntry`, the constants are defined as global. But the parent class, `PKPSubmissionEventLogEntry`, defines iits constants as class constants. To fix this, we should either move the constants into the class (and produce the globals as needed) or import the class.

This is the error:

```
PHP Fatal error:  Uncaught Error: Undefined constant "SUBMISSION_LOG_REVIEW_RECOMMENDATION_BY_PROXY" in /home/nate/Projects/pkp/ojs/controllers/grid/users/reviewer/ReviewerGridHandler.inc.php:40
Stack trace:
#0 [internal function]: ReviewerGridHandler->reviewRead(Array, Object(APP\core\Request))
#1 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#2 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(288): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#3 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/Dispatcher.inc.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#4 /home/nate/Projects/pkp/ojs/lib/pkp/classes/core/PKPApplication.inc.php(375): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#5 /home/nate/Projects/pkp/ojs/index.php(70): PKP\core\PKPApplication->execute()
#6 {main}
  thrown in /home/nate/Projects/pkp/ojs/controllers/grid/users/reviewer/ReviewerGridHandler.inc.php on line 40
```

**Comment by NateWr** [comment]
@Vitaliy-1 I assigned this to you because I think once your PR is merged this will be fixed. Just needs to be tested and closed if it's all good.

**Comment by asmecher** [comment]
@Vitaliy-1, do you know if this one was resolved?

**Comment by Vitaliy-1** [comment]
Yes, was fixed
