### ISSUE TITLE
Wrong charset conversion in citationStyleLanguage plugin

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#7765]
**Describe the bug**

In a full functional OJS stable-3.2.1 (but also in last 3.3.0-10):

With:
- Tables and fields in utf8mb4_general_ci.
- Header html declares "utf8".
- Source code php: text/x-php; charset=us-ascii
- PHP 7.3.22
- All plugins up to date.

Only on CitationStyleLanguage plugin I found special chars are removed (accents, non ascii letters).

Log shows the following notice:
```
PHP Notice:  iconv(): Wrong charset, conversion from `UTF-8' to `ISO-8859-1//IGNORE' is not allowed in /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/symfony/polyfill-mbstring/Mbstring.php on line 345
```

**To Reproduce**
1. Run a ojs 3.3.0-10 "offical" docker container. 
2. Add a journal, author and an article... all with a few special chars (ie: accents)
3. Enable citationStyleLanguage plugin.
4. Go to the published article
5. See error

**What application are you using?**
- OJS 3.2.1-4
- OJS stable-3.2.1
- OJS 3.3.0-10

**Additional information**

Mbstring is installed:
```
$ php -m  | grep mbstring
mbstring
```
![imagen](https://user-images.githubusercontent.com/2779168/158406226-20cccbe3-1762-4655-822d-a593bfef7258.png)

@jonasraoni checked it and looks like polyfill is always being called:
https://github.com/seboettg/citeproc-php/blob/c1df840d897b938431130445927d48a4b6cf464b/src/Util/StringHelper.php#L141-L143

**Comment by asmecher** [comment]
@jonasraoni, would you be able to look into this? (It sounds like you already started!)

**Comment by jonasraoni** [comment]
Ok!

**Comment by marcbria** [comment]
@jonasraoni please, let me know if you need help with the testing... or whatever.

**Comment by jonasraoni** [comment]
Hi @marcbria,

I just could simulate it using your Docker image, in my environment, which is also under Docker, it worked fine.

So it looks like a problem in the image, I've created an [issue against the docker-ojs repository](https://github.com/pkp/docker-ojs/issues/214), with the source of the problem and a possible solution.

So, I'll close this issue for now :)

**Comment by jonasraoni** [comment]
There's also a similar issue here (missing letters + same error message): https://github.com/seboettg/citeproc-php/issues/102
