### ISSUE TITLE
Improve UX of the Steps wizard component

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7768]
**Describe the problem you would like to solve**
The Steps component is designed to support a step-by-step wizard UI. Currently it is designed as a `tabpanel` that allows the user to jump forwards and backwards. This leads to problems such as:

- Confusing visual markers for currently active, completed, and focused steps.
- Can't restrict user's progress through the wizard, which makes it harder to design useful wizards.

**Describe the solution you'd like**
Turn the Steps component into an `<ol>` and prevent the user from jumping forwards. Only "activate" a step once previous steps are completed.

**Who is asking for this feature?**
UX improvements from #7265.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ui-library/pull/185
https://github.com/pkp/pkp-lib/pull/7769

Tests:
https://github.com/pkp/ojs/pull/3329
https://github.com/pkp/omp/pull/1081

**Comment by NateWr** [comment]
This broke the tests because it removes the `id` attribute used in some tests: https://github.com/pkp/ui-library/commit/dba48255fbe46beac34de160870ae953fb75d9b1#diff-d50adb5d1e5707a838d03f0253f438c8e4397a7608284c380e9aecbbef3ce86dL5

See conversation here: https://github.com/pkp/ojs/pull/3331

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/7778

Tests:
https://github.com/pkp/ojs/pull/3333
https://github.com/pkp/omp/pull/1086

**Comment by asmecher** [comment]
@NateWr, the above PR for pkp-lib also needed a couple of selector tweaks:

https://github.com/pkp/pkp-lib/commit/61d62dcfc427a5e609237e3f49a4de756573db9e

I've cherry-picked your changes in and committed submodule updates for the apps.

**Comment by asmecher** [comment]
^ This didn't quite get it there -- OJS content tests pass, but OMP and OPS do not, and there is a statistics test fail in OJS (and presumably the others). I'll check out the statistics test fail in the morning.

**Comment by NateWr** [comment]
@asmecher I was able to fix the stats test failure, but I can't reproduce the OMP/OPS test failure when recording a decision. See https://app.travis-ci.com/github/pkp/omp/jobs/564143472#L2142.

Based on the test log, it seems like the `<h1>` element is not on the page at all. This would indicate a fatal error of some kind that stops execution (rather than a JS error that stops Vue.js from showing the text in the `<h1>`). However, there is nothing in the `error.log` and the screenshots are cut off in the log, so I was unable to recover them.

There is a fatal error in OPS's logs, but I believe this is unrelated. Filed at https://github.com/pkp/pkp-lib/issues/7783.

Are you able to reproduce the test failure locally?
