### ISSUE TITLE
BackendDOIHandler missing argument to publication schema map

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7771]
**Describe the bug**
Error when trying to assign a DOI in `main`:

```
Slim Application Error:
Type: ArgumentCountError
Message: Too few arguments to function PKP\publication\Repository::getSchemaMap(), 2 passed in /home/nate/Projects/pkp/ojs/lib/pkp/api/v1/_dois/PKPBackendDoiHandler.inc.php on line 97 and exactly 3 expected
File: /home/nate/Projects/pkp/ojs/lib/pkp/classes/publication/Repository.inc.php
Line: 115
Trace: #0 /home/nate/Projects/pkp/ojs/lib/pkp/api/v1/_dois/PKPBackendDoiHandler.inc.php(97): PKP\publication\Repository->getSchemaMap(Object(APP\submission\Submission), Array)
#1 [internal function]: PKPBackendDoiHandler->editPublication(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
```

**To Reproduce**
1. Try to assign a DOI
4. See error in server logs

**What application are you using?**
 `main`

**Additional information**
There's a new argument required for the publication schema map. See:

https://github.com/pkp/pkp-lib/blob/94ac521b0815d27f667c902fff675735c4f3afab/api/v1/submissions/PKPSubmissionHandler.inc.php#L639-L644

@ewhanson can you also check for other calls to `Repo::publication()->getSchemaMap()`? May have forgotten to update one or two when I made the change.

**Comment by ewhanson** [comment]
Hey @NateWr, here are the PRs for this fix. Could you have a look? Thanks.

PRs:

- #7775
- pkp/ojs#3332
- pkp/omp#1085
- pkp/ops#250

**Comment by NateWr** [comment]
Thanks @ewhanson. I've merged in the pkp-lib PR and closed the others. The test failures were not related to this fix, but a problem I introduced last week. See https://github.com/pkp/ojs/pull/3331#issuecomment-1073733794.
