### ISSUE TITLE
Configuration parameters get truncated if they are too long

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7776]
**Describe the bug**
If a parameter in config.inc.php exceeds 1024 characters, it will get truncated because the ConfigParser class only reads that many bytes. This has consequences for issue #7649 when an installation contains many journals with custom domains.  In that case, the configuration parameter will get truncated and the call to json_decode in the security policy will return null.

**To Reproduce**
Increase the length of the e.g. allowed_hosts parameter to a very long string and eventually you will see this in the log:

```
PHP Warning:  array_map(): Expected parameter 2 to be an array, null given in lib/pkp/classes/security/authorization/AllowedHostsPolicy.inc.php on line 52 
```

**What application are you using?**
OJS 3.3.0.10

**Comment by asmecher** [comment]
There was an arbitrary 1024-byte limit on a single config line; I've removed this. Committed to `main` and `stable-3_3_0`.
