### ISSUE TITLE
Incorrect dates in publications stats intervals

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7777]
**Describe the bug**
Instead of sequential days of the month, like February 1, February 2, etc., in PKP stats days of the month are repeated: February 1, February 1..., March 1, March 1, etc. 

**To Reproduce**
1. Go to Article Stats
2. Set abstract views/daily
3. See date intervals

**What application are you using?**
 OJS main branch

**Additional information**
![date_intervals](https://user-images.githubusercontent.com/20665587/159132634-f143386b-0173-4ea2-9666-6172713eaec2.png)
This is likely caused by a recent commit related to the date and time formating: https://github.com/pkp/pkp-lib/commit/18390f9ac91e1acbccfc8999f820b63c15b6947b

**Comment by asmecher** [comment]
@Vitaliy-1, I've confirmed locally that this is fixed by https://github.com/pkp/pkp-lib/commit/c3345625740e6110b348d3065d038e7d4e61676e, but please re-open if it still gives you trouble.
