### ISSUE TITLE
OJS 3.3.0-10: All administrative links are broken

### ISSUE THREAD

**Issue by Helyfoxer** [pkp/pkp-lib#7779]
**Describe the bug**

After upgrading to 3.3.0-10 we having bug with broken link to administrative page.
_UPDATE: on clean setup 3.3.0-10 situation is the same._

**To Reproduce**

In updated to (or installed new) 3.3.0-10 in user profile drop-down menu the system generates a link like `https://SITE_NAME/:///SITE_NAME/admin/index` , but admin page opens (manually) by `https://SITE_NAME/index/admin` ( _restful_urls = On_ ) and opening administrative page got errors in contained links and form's urls.

**Additional information**

I've checked that `lib/pkp/classes/services/PKPNavigationMenuService.inc.php` in this version already looks like https://github.com/asmecher/pkp-lib/commit/e9f5360ffe6638ff77e7c76db9496094eaf7759a

Only https://github.com/asmecher/pkp-lib/commit/bdbfc6ba5da486d3c3949782637a6513ab8d6367 patch was applied to change `lib/pkp` dir content.

Temporalily I added to `lib/pkp/classes/services/PKPNavigationMenuService.inc.php`
```
$navigationMenuItem->setUrl('/index/admin');
```
after
```
case NMI_TYPE_ADMINISTRATION:
	$navigationMenuItem->setUrl($dispatcher->url(
	$request,
	ROUTE_PAGE,
	'index',
	'admin',
	'index',
	null
	));
```
while I trying to analyse reasons.

And it did not help to fix the link to the admin page in the last link of the Dasboard left menu - there link is shaped by different way.

But as I wrote above, the administration page is useless.

Because all links and urls on it are also with errors.

At the same time, other links on the site are formed correctly.

**Comment by asmecher** [comment]
@Helyfoxer, what version were you upgrading from?

**Comment by Helyfoxer** [comment]
I tried to update from 3.2.1.1, going by both ways: 3.3.0.-10 at once, and sequentially installing all intermediate versions.
But, as I already wrote, this problem also exists when installing a new 3.3.0-10 separately.

**Comment by asmecher** [comment]
What errors are you seeing at the URLs that are not working?

Are you using `mod_rewrite`?

**Comment by Helyfoxer** [comment]
I'm seeing 
**404 Not Found**

_Are you using mod_rewrite?_

Yes, I'm using it. 
But without `mod_rewrite` and with `restful_urls = Off` problem still remains.
In that case link to admin page looks like 
`https://SITE_NAME/index.php/journal/:///SITE_NAME/admin`

**Comment by asmecher** [comment]
@Helyfoxer, did you carry across your `base_url` configuration directives from your 3.2.1.1 installation? The `base_url[index]` setting is probably relevant here, as it determines URLs for the administration pages.

**Comment by Helyfoxer** [comment]
`base_url` and `base_url[index]` are the same and equal "SUBDOMAIN.DOMAIN" (without http:// or https://).

**Comment by asmecher** [comment]
@Helyfoxer, I'm not sure I'll be able to help with `mod_rewrite` rules, but can you include...
- your rewrite configuration, and
- all your `base_url[...]` directives from `config.inc.php`?

**Comment by Helyfoxer** [comment]
I leave only `base_url` and it helps.
