### ISSUE TITLE
Role settings page broken in OPS on PHP 8.1

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7783]
**Describe the bug**
When accessing Settings > Users & Roles > Roles, there is a fatal error and the roles list does not load. This only occurs in PHP 8.1

**To Reproduce**
1. Go to Settings > Users & Roles > Roles.
2. See that the roles list does not load.
4. See error in server log.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
This bug occurs in PHP 8.1 because an assertion fails when it tries to get the name of the submission stage. Because `Application::getApplicationStages()` does not include the submission stage, it fails.

This will effect 3.3.0 LTS when it supports PHP 8.1.

The error is:

```
PHP Fatal error:  Uncaught AssertionError: assert(isset($stageMapping[$stageId])) in lib/pkp/classes/workflow/WorkflowStageDAO.inc.php:79
Stack trace:
#0 lib/pkp/classes/workflow/WorkflowStageDAO.inc.php(79): assert(false, 'assert(isset($s...')
#1 lib/pkp/classes/security/UserGroupDAO.inc.php(1107): PKP\workflow\WorkflowStageDAO::getTranslationKeyFromId(1)
#2 lib/pkp/controllers/grid/settings/roles/UserGroupGridCellProvider.inc.php(40): PKP\security\UserGroupDAO->getAssignedStagesByUserGroupId(1, 2)
#3 lib/pkp/classes/controllers/grid/GridCellProvider.inc.php(57): UserGroupGridCellProvider->getTemplateVarsFromRowColumn(Object(UserGroupGridRow), Object(PKP\controllers\grid\GridColumn))
#4 lib/pkp/classes/controllers/grid/GridHandler.inc.php(1253): PKP\controllers\grid\GridCellProvider->render(Object(APP\core\Request), Object(UserGroupGridRow), Object(PKP\controllers\grid\GridColumn))
#5 lib/pkp/classes/controllers/grid/GridHandler.inc.php(1154): PKP\controllers\grid\GridHandler->_renderCellInternally(Object(APP\core\Request), Object(UserGroupGridRow), Object(PKP\controllers\grid\GridColumn))
#6 lib/pkp/classes/controllers/grid/GridHandler.inc.php(1129): PKP\controllers\grid\GridHandler->renderRowInternally(Object(APP\core\Request), Object(UserGroupGridRow))
#7 lib/pkp/classes/controllers/grid/GridHandler.inc.php(1179): PKP\controllers\grid\GridHandler->renderRowsInternally(Object(APP\core\Request), Array)
#8 lib/pkp/classes/controllers/grid/GridHandler.inc.php(1054): PKP\controllers\grid\GridHandler->renderGridBodyPartsInternally(Object(APP\core\Request))
#9 lib/pkp/classes/controllers/grid/GridHandler.inc.php(725): PKP\controllers\grid\GridHandler->doSpecificFetchGridActions(Array, Object(APP\core\Request), Object(APP\template\TemplateManager))
#10 [internal function]: PKP\controllers\grid\GridHandler->fetchGrid(Array, Object(APP\core\Request))
#11 lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#12 lib/pkp/classes/core/PKPComponentRouter.inc.php(288): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#13 lib/pkp/classes/core/Dispatcher.inc.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#14 lib/pkp/classes/core/PKPApplication.inc.php(375): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#15 index.php(70): PKP\core\PKPApplication->execute()
#16 {main}
  thrown in lib/pkp/classes/workflow/WorkflowStageDAO.inc.php on line 79
```

**Comment by asmecher** [comment]
https://github.com/pkp/pkp-lib/commit/26e9075279c6d59cf3713777f133331be3065e33 isn't the cleanest fix but I think it's the lesser evil. We can't 100% remove WORKFLOW_STAGE_SUBMISSION because `pkp-lib` depends on it in various ways, e.g. in listing author user groups for role selection. But OPS jumps submissions right to WORKFLOW_STAGE_PRODUCTION so authors can upload galleys, which also makes sense. So while WORKFLOW_STAGE_SUBMISSION shouldn't be user visible, it can continue to have a place in the back end.

**Comment by NateWr** [comment]
@asmecher it looks like this maybe didn't get back ported to `stable-3_3_0`. I just ran into it today. I've reopened it and assigned it to 3.3.0-14, but please close it if I'm mistaken.

**Comment by asmecher** [comment]
Thanks, I've back-ported this to `stable-3_3_0`. It's still just a warning for me, even on PHP8.1(.13), but this at least makes the warning go away.
