### ISSUE TITLE
OJS 3.2.1.1 - OJS 3.3.0-10⚠️ Serious security issue

### ISSUE THREAD

**Issue by Helyfoxer** [pkp/pkp-lib#7786]
**Describe the bug**

**⚠️ Serious security issue: User can upload and execute malicious code.**

**To Reproduce**

1. Go to Submissions
2. Click on **New Submission**
3. Enter the required primary article data and click **Save and Continue**.
4. Select article component
5. Upload some *.phtml, *.shtml file or file with extension from mixed register of chars of those extension (evil.pHtMl etc).
6. If the ill-wisher knows how OJS forms links and filenames, then running the script will not be difficult 

**What application are you using?**

Issue applied to OJS 3.2.1.1 - OJS 3.3.0-10 (it seems to me)

**Additional information**

While I was troubleshooting the upgrade to 3.3.0-10 today my journal site on 3.2.1.1 got hacked.
Some bastard was able to change my .htaccess file, create files and folders in /uploads/journal, and in /, and replace the main page of the site. 
Because he could steal the parameters from the configuration file, I subsequently changed all the passwords indicated there. 

⚠️ I think I found a vulnerability...
After checking the code 3.3.0-10, I believe it remained in it too.

I make changes in function `parseFileExtension` in `/lib/pkp/classes/file/FileManager.inc.php`

Current (stock):
```
        /**
         * Parse the file extension from a filename/path.
         * @param $fileName string
         * @return string
         */
        function parseFileExtension($fileName) {
                $fileParts = explode('.', $fileName);
                if (is_array($fileParts) && count($fileParts) > 1) {
                        $fileExtension = $fileParts[count($fileParts) - 1];
                }

                // FIXME Check for evil
                if (!isset($fileExtension) || stristr($fileExtension, 'php') || strlen($fileExtension) > 6 || !preg_match('/^\w+$/', $fileExtension)) {
                        $fileExtension = 'txt';
                }

                // consider .tar.gz extension
                if (strtolower(substr($fileName, -7)) == '.tar.gz') {
                        $fileExtension = substr($fileName, -6);
                }

                return $fileExtension;
        }
```

Modified:
```
        /**
         * Parse the file extension from a filename/path.
         * @param $fileName string
         * @return string
         */
        function parseFileExtension($fileName) {
                $fileParts = explode('.', $fileName);
                if (is_array($fileParts)) {
                        $fileExtension = $fileParts[count($fileParts) - 1];
                }

                // FIXME Check for evil
                if (!isset($fileExtension) || !in_array(strtolower($fileExtension), array('tex','rtf','doc','docx','pdf','zip','gz','xls','odf','eps','jpg','png','jpg','jpeg','gif','tiff','ai','rar')) || strlen($fileExtension) > 6 || !preg_match('/^\w+$/', $fileExtension)) {
                        $fileExtension = 'txt';
                }

                // consider .tar.gz extension
                if (strtolower(substr($fileName, -7)) == '.tar.gz') {
                        $fileExtension = substr($fileName, -6);
                }

                return $fileExtension;
        }
```

It works. Now *.phtml goes to *.txt too.

I understand that, perhaps, I could solve the issue at the level of web server settings, and not by editing the code.

But so I determined a list of exactly relatively safe file types to upload to the server.

My decision is clumsy and does not claim to be elegant, but I had to act quickly.

I will wait for the official patch for this problem.

Dear friends, be careful! 

P.S.
Forgive me if something awkwardly stated, but I'm still on my nerves from an unexpected situation.
I consider myself lucky that this happened just when I was on the server and was able to notice it fairly quickly.

**Comment by asmecher** [comment]
@Helyfoxer, this is an unsafe deployment rather than a bug; see the installation form:

![image](https://user-images.githubusercontent.com/200411/159723569-076574d7-1174-4fbf-8981-65880375b9ea.png)
(Relevant part: "This directory should not be directly web-accessible.")

Also in `docs/README.md`:
> ## Recommended Configuration
>
> [...]
> * Install OJS so that the files directory is NOT a subdirectory of
>        the OJS installation and cannot be accessed directly via the web
>        server. Restrict file permissions as much as possible. Automated
>        backups of this directory should be roughly synchronized with
>        database backups.

In the future, if you're disclosing a potential security issue, please follow responsible disclosure best practices by contacting the team privately before filing a public issue. This gives us time to respond to the issue before it's made public to potential malicious users.

**Comment by dunglehome** [comment]
Hello @asmecher 

If I want to further secure the files_dir directory by removing the x bit on Linux system directory permission (to disallow executable action) would there be any downfall happening to the application such as stopping legit users from uploading their documents? Or in anyway it will stop the application from functioning normally?

We have got an attempt file such as "/data/production/journals/81/articles/30342/submission/attack-30342-193-79508-1-2-20160813.phtml-Feb-21-2017.txt " - this dir is not web accessible directly.

I appreciate any advice.

Dung.

**Comment by asmecher** [comment]
@dunglehome, your question is best asked/answered on the support forum (I see you've posted it [here](https://forum.pkp.sfu.ca/t/block-certain-file-types-from-being-uploaded-in-ojs/26087/3)).
