### ISSUE TITLE
User::getContactSignature() may return array and break email template variable replacement

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7787]
**Describe the bug**
`User::getContactSignature()` accepts optional `$locale` as an argument. The idea behind the method's body is returning a localized user signature or if not, combining fullname, affiliation and phone number from user settings to create one. see: https://github.com/pkp/pkp-lib/blob/d5a8934eea2f3454f31e81aee1eade5cdb699697/classes/user/User.inc.php#L420-L431 

But if the locale isn't specified, it returns an array [locale => signature], which bypasses the signature construction and breaks `signature` variable replacement. 

**To Reproduce**
Steps to reproduce the behavior, e.g., in review reminder form
1. Make a submission, pass it to the review stage and assign a reviewer
2. Click on Send Reminder to open email editing modal
3. Click on Send Reminder to send email
4. See error.
```
PHP Fatal error:  Uncaught TypeError: str_replace(): Argument #2 ($replace) must be of type string when argument #1 ($search) is a string in /home/doc/OJS/development/ojs/lib/pkp/classes/mail/MailTemplate.inc.php:264
Stack trace:
#0 /home/doc/OJS/development/ojs/lib/pkp/classes/mail/MailTemplate.inc.php(264): str_replace()
#1 /home/doc/OJS/development/ojs/lib/pkp/classes/mail/MailTemplate.inc.php(243): PKP\mail\MailTemplate->replaceParams()
#2 /home/doc/OJS/development/ojs/lib/pkp/classes/mail/SubmissionMailTemplate.inc.php(83): PKP\mail\MailTemplate->send()
#3 /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/users/reviewer/form/ReviewReminderForm.inc.php(182): PKP\mail\SubmissionMailTemplate->send()
#4 /home/doc/OJS/development/ojs/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.inc.php(847): ReviewReminderForm->execute()
#5 [internal function]: PKP\controllers\grid\users\reviewer\PKPReviewerGridHandler->sendReminder()
#6 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#7 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(288): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#8 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(163): PKP\core\PKPComponentRouter->route()
#9 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(375): PKP\core\Dispatcher->dispatch()
#10 /home/doc/OJS/development/ojs/index.php(70): PKP\core\PKPApplication->execute()
#11 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/classes/mail/MailTemplate.inc.php on line 264
```

**What application are you using?**
 OJS main branch

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/7788
tests: https://github.com/pkp/ojs/pull/3345

**Comment by Vitaliy-1** [comment]
@NateWr, you made changes in this method recently, do I get its logic correctly? 
(Failed tests aren't related to this PR)

**Comment by NateWr** [comment]
> But if the locale isn't specified, it returns an array [locale => signature], which bypasses the signature construction and breaks signature variable replacement.

I'm not sure I understand exactly. What would be the value of `$a` and `$b` in the following code?

```php
$a = $user->getContactSignature(null);
$b = $user->getSignature(null);
```

It seems to me like `$b` should be `null`, but I think you're suggesting it is something else?

**Comment by Vitaliy-1** [comment]
Yes, an array

**Comment by Vitaliy-1** [comment]
e.g.:
```php
[
  'en_US' => ''
]
```

**Comment by NateWr** [comment]
What's the value of that user's records in the database? Looking at the code, it seems like that would only get returned if the user object was like this:

```php
User {
  $_data = [
    ...
    signature => [
        en_US => ''
    ]
  ]
}
```

But I think empty strings are not supposed to be saved to the database... The DAO is supposed to remove the `signature` row if it is an empty string...

**Comment by Vitaliy-1** [comment]
```sql
INSERT INTO `user_settings` (`user_id`, `locale`, `setting_name`, `setting_value`) VALUES ('1', 'en_US', 'signature', '')
```

**Comment by NateWr** [comment]
Yes, the data can be manually inserted into the database that way. But the `UserDAO` is not meant to add such rows, I think, once the entity schema is in place. Something like `$user->getData('anything');` shouldn't return an empty text string because the row in the database _shouldn't_ exist. (Just trying to figure out the root cause here.)

**Comment by Vitaliy-1** [comment]
I don't see anything in new DAO classes that should convert empty string values to NULL in setting tables. I think the logic of such behavior should be implemented in `EntityDAO::fromRow()`

**Comment by NateWr** [comment]
I think it is meant to be part of the `PKPSchemaService::sanitize()` method, but maybe things changed a bit with how `null` values were handled. The easiest thing to do is to test to see if you can save an empty string value to a user profile. If it happens, then yeah we should try to account for it.

**Comment by Vitaliy-1** [comment]
I see that some Collectors already rely on this new pattern, I mean saving setting as an empty string. E.g., considering Issue Collector and searching by a phrase: https://github.com/pkp/ojs/blob/4a2f3423e4ada68a919087d8c6cf7f13db3802a5/classes/issue/Collector.inc.php#L375

Searching in the settings table is performed by taking into account that the setting value for title and name exists and it's an empty string. Let's say the phrase is an empty string, it produces a subquery, like:
```sql
(select `iss_t`.`issue_id` from `issue_settings` as `iss_t` where `iss_t`.`setting_name` = 'title' and lower(iss_t.setting_value) LIKE CONCAT('%', LOWER(''), '%'))
```
which produces false results if that setting `title` doesn't exist. And this looks like a widely used pattern.

**Comment by Vitaliy-1** [comment]
The full query:
```sql
select `i`.* from `issues` as `i` left join `custom_issue_orders` as `o` on `o`.`issue_id` = `i`.`issue_id` where `i`.`journal_id` in (1) and `i`.`issue_id` in (select `iss_t`.`issue_id` from `issue_settings` as `iss_t` where `iss_t`.`setting_name` = 'title' and lower(iss_t.setting_value) LIKE CONCAT('%', LOWER(''), '%')) or `i`.`issue_id` in (select `iss_d`.`issue_id` from `issue_settings` as `iss_d` where `iss_d`.`setting_name` = 'name' and lower(iss_d.setting_value) LIKE CONCAT('%', LOWER(''), '%'))
```
The API request that is failing on a test instance: `http://localhost:8000/index.php/publicknowledge/api/v1/issues?searchPhrase=&count=30&offset=0&_=1649520111528`. It's DOIs page -> Issues tab

**Comment by NateWr** [comment]
@asmecher I've lost track of what's happening in this issue, and changes in the PR touch the deepest, darkest parts of the entity system (`PKPSchemaService::coerce()` at https://github.com/pkp/pkp-lib/pull/7788/files#diff-00ac1d93cf0f9b86c713ab3c9f385335674efd25588b62c6ce83340fa09054dcR286). Can you take over on this one?

(It may be easier to just implement #7479 but I don't know if that will solve all the problems.)

**Comment by asmecher** [comment]
@Vitaliy-1, was this issue mitigated by https://github.com/pkp/pkp-lib/issues/7479?

**Comment by Vitaliy-1** [comment]
Yes, looks like it has been solved
