### ISSUE TITLE
Update supported Crossref Schema across pkp-lib

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#7796]
Currently, OJS supports version 4.3.6 of the Crossref schema. Crossref is currently on version 5.3.1. The schema hasn't broken backwards so there's no immediate need to panic or anything, but you can see notes on each supported schema here: https://www.crossref.org/documentation/schema-library/schema-versions/ 

Here's a summary of major highlights for the versions we don't support in OJS:
 
- 5.3.1 added ROR support. 
- 4.8.1 changes include support for ISBN that begin with 979, changes to the regex for the email_address field, relaxed regex for given_name to allow numbers, and schema refactoring (useful for OMP, I'd assume)
- 4.4.2 adds support for pending publication, distributed usage logging (DUL), multiple dissertation authors, abstracts for all content types, support for JATS 1.2 abstracts, and adds acceptance_date element to journal article, book, book chapter, and conference papers
- 4.4.1 adds support for [peer reviews](https://www.crossref.org/documentation/content-registration/content-type-markup-guide/peer-reviews/)
- 4.4.0 adds support for [posted content (includes preprints)](https://www.crossref.org/documentation/content-registration/content-type-markup-guide/posted-content-includes-preprints/) (useful for OPS, I'd assume)
- 4.3.7 adds support for linked clinical trials, journal deposits without [ISSNs](https://www.crossref.org/documentation/content-registration/descriptive-metadata/issns-isbns/) (this comes up with OJS journals a fair bit... currently you need to have an ISSN in order for your crossref deposit to be valid)

**Describe the solution you'd like**
I know we're in the middle of a 3.4 release push with a major DOI refactor and, as I said, these won't break backwards so there is no huge rush, but it would be nice if we could address this after the launch. 

**Who is asking for this feature?**
Well, as Crossref liaison, I guess I am. But I think the functionality afforded OPS, OMP, and OJS in this space speaks to some friction I've seen in publishing services. It would be nice if we could tie in ROR work here also. 

**Additional information**
I'm happy to help out here as much as I'm capable.

**Comment by alexxxmendonca** [comment]
+1 for ROR support
+1 for OPS (recently with Lepidus' help we managed to include abstract in the Crossref posted content schema, which wasn't possible until then)

**Comment by othwunrai** [comment]
Hi. I'm little confused. If OJS supports version 4.3.6 of the Crossref schema and only crossref 5.3.1 has ROR support, doesn't it make ROR Plugin useless?

**Comment by bozana** [comment]
PRs:
pkp-lib: https://github.com/pkp/pkp-lib/pull/8233
crossref-ojs: https://github.com/pkp/crossref-ojs/pull/15
ojs: https://github.com/pkp/ojs/pull/3533
crossref-ops:
ops:

**Comment by bozana** [comment]
@NateWr, could you take a look at the PRs above? In the meantime I will prepare the PRs for OPS...

**Comment by bozana** [comment]
@NateWr, I corrected the PRs according to your comments. Would you maybe like to take another look? 
Thanks a lot!

**Comment by NateWr** [comment]
Looks good @bozana!
