### ISSUE TITLE
Recipient names incorrect in reviewer notification emails for editorial decisions

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7798]
**Describe the bug**
When recording an editorial decision in the review stage, it is possible to send an email to reviewers to notify them of the decision. Each reviewer is sent a separate email, so that the reviewer's identities are not disclosed to each other. 

However, the `{$recipientName}` email variable still shows all of the reviewer's names. When an email template is loaded, the names are added to the body of the email.

Instead, the `{$recipientName}` variable should be left "raw", so that the email body that is sent to the server still contains the variable string `{$recipientName}`. This variable can then be substituted on the server for each email, so that each reviewer receives an email with only their name.

**To Reproduce**
1. Make sure that your Request Revisions email template contains the `{$recipientName}` variable. (Go to Settings > Workflow > Emails > find the email > make sure the variable is there or add it.)
2. Go to a submission in the review stage.
3. Make sure there are two reviews that have been _completed_ and _confirmed_ by an editor.
4. Begin the process to record an editorial decision (eg - Request Revisions)
5. Go to the "Notify Reviewers" step.
6. See that both reviewer names appear in the email.

**What application are you using?**
`main` branch (3.4 pre-release)

**Comment by NateWr** [comment]
One idea would be to add a `prop` to the `Composer` component for emails where each recipient will be emailed separately. This will be a common case, and could be confusing for users, since the To field looks like all will be emailed one message. Maybe have a notice by the To field that says something like:

> Each recipient will be sent a separate email.

**Comment by Vitaliy-1** [comment]
That's sounds familiar, think something related was in Laravel documentation. Maybe it's the case where each Mailable should be initialized individually.

**Comment by Vitaliy-1** [comment]
Maybe this is the case: https://laravel.com/docs/8.x/mail#looping-over-recipients?

**Comment by NateWr** [comment]
Ahh, that's nice to know about `Mailer::to(...)->send(...)`! This issue is more about what happens with the body of the message, though, and it is mostly about how this is handled in the browser.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ui-library/pull/230
https://github.com/pkp/pkp-lib/pull/8434

Tests:
https://github.com/pkp/ojs/pull/3622

These changes add a flag, `separateEmails`, to the `Composer` component. When enabled, the template variable `{$recipientName}` will no longer be rendered with the recipients names. It will stay as `{$recipientName}` in the message subject and body, and this gets replaced when the email is sent with the correct recipient. 

I also added a note to the Notify Reviewers step in editorial decisions to explain this. Ideally, the explanation would be closer to the message body. But I felt it was good enough for now.

![notify-reviewers](https://user-images.githubusercontent.com/2306629/202184206-a38a54c3-ff25-43dd-99d4-ca79a4b46df3.png)

@jonasraoni do you have time to do a code review?

**Comment by NateWr** [comment]
Thanks for the review @jonasraoni! I've gone ahead and merged to `main`. But there was one outstanding question from the review. I can address that after merge needed.
