### ISSUE TITLE
Some email variables do not have a description

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7806]
**Describe the bug**
In the new email template variable UI (#7743), it's possible to see a description of each variable. However, some variables do not have a description.

I noticed this with the `DecisionNotifyReviewers` mailable.

**To Reproduce**
1. Go to a submission in the review stage
2. Make sure there is at least one reviewer who has completed a review.
3. Request revisions
4. Go to the Notify Reviewers step
5. When editing the email, open the Insert Content UI  (see #7743).
6. See that some variables do not have a description

**What application are you using?**
`main` (3.4 pre-release)

**Comment by NateWr** [comment]
@asmecher can you take a quick look at these PRs, just to make sure I'm not messing anything up with the new translation stuff?

I have:

- Made minor copyediting changes to `en_US` locale keys and marked them `#, fuzzy` in other languages.
- Moved a couple locale strings that said "journal" out of pkp-lib and into each app. I removed them in other languages.
- Fixed a totally wrong email template body in OPS and deleted it from other languages since the translation would be wrong.

PRs:
https://github.com/pkp/pkp-lib/pull/8617
https://github.com/pkp/ojs/pull/3751
https://github.com/pkp/ops/pull/461
https://github.com/pkp/omp/pull/1326

**Comment by asmecher** [comment]
@NateWr, while we're still treating `main` as the "definitive" source of translations, and `en_US` as the authoritative source of what keys should exist and in what order, there's no need to make batch changes to other languages beyond our old practice of removing keys in case of a major change in translation or marking them fuzzy in the case of a minor change. The summit toolset will take care of e.g. adding blank translations for other languages, and Weblate should know to treat empty translations as untranslated.

**Comment by NateWr** [comment]
Thanks! All merged to `main`.
