### ISSUE TITLE
[Portico] Add support for using a certificate authentication through SFTP

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7807]
**Describe the problem you would like to solve**
The plugin currently supports exporting submissions using a SFTP connection, but the integration is lacking support for a certificate based authentication.

**Describe the solution you'd like**
Add a field to upload the certificate and an optional key phrase.
Perhaps it would be better to not display the passwords/certificate in plaintext.

**Who is asking for this feature?**
Hosting

**PRs**
- https://github.com/pkp/portico/pull/10
- https://github.com/pkp/portico/pull/11
- https://github.com/pkp/portico/pull/12

**Comment by jonasraoni** [comment]
@asmecher This is based on the #6955, I've just added an extra commit. I tested in an environment using OJS 3.1.2 and locally (3.3.0) and it worked fine.

**Comment by asmecher** [comment]
@jonasraoni, OK, I'm just concerned that it's fixing problems that might not exist -- suggesting it was maybe necessary for a previous version of the plugin but not this one?

**Comment by jonasraoni** [comment]
> suggesting it was maybe necessary for a previous version of the plugin but not this one?
@asmecher I've left [a comment](https://github.com/pkp/pkp-lib/issues/6955#issuecomment-1086656217) on the other issue.

**Comment by jonasraoni** [comment]
@asmecher I'll need this one too!

Summary: 
These PRs just have a single commit to add the certificate authentication. The others are from https://github.com/pkp/pkp-lib/issues/6955.

**Comment by asmecher** [comment]
All merged, thanks!

**Comment by jonasraoni** [comment]
Nope, just these ones. Thanks 🎉
