### ISSUE TITLE
Review and update Composer dependencies before 3.4 testing

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7815]
The Composer lockfile currently specifices a PHP7.x platform requirement; the Laravel email work will result in a bump to 9.x before release. After the major merges are in place, review the platform baseline and update the Composer libraries to current. (This will probably also result in a removal of the 3rd party upsert support in favour of the built-in modern Laravel equivalent.)

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/3366
- https://github.com/pkp/pkp-lib/pull/7842

There were some cascading dependency updates required because of the Laravel 9 bump. I replaced `brainmaestro/composer-git-hooks` (which does not yet support Symfony 6) with `captainhook/captainhook` (which does). I was able to remove `staudenmeir/laravel-upsert` in favour of the built-in Laravel 9 equivalent.

**Comment by asmecher** [comment]
@Vitaliy-1, could you please have a look at these? If the idea is OK, I'll port them to OMP and OPS. (The app-level changes are minimal.)

**Comment by Vitaliy-1** [comment]
I'm surprised about the amount of modifications needed to upgrade from Laravel 7 to 9, how insignificant it is. And that's 2 major releases.  

From what I can find, `Illuminate\Queue\WorkerOptions` constructor now accepts more parameters, like the maximum number of seconds a worker may live or the maximum number of jobs to run. Also, the first parameter is now the name of the worker, so will break things. We initialize it here: https://github.com/pkp/pkp-lib/blob/376e8ff3e3800795f87796a166bf432279aeeae1/classes/core/PKPQueueProvider.inc.php#L48.

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1; I saw evidence of the queues executing all the same, but I've added the default worker name (`'default'`) to the function. I was also surprised by how little was required! In any case, let's talk about it on Monday.

**Comment by NateWr** [comment]
In this PR, `psy/psysh` is still at 0.11.1 in the `composer.lock` file. This needs to be updated to `0.11.2` to fix a recent bug that prevents it from being used.
