### ISSUE TITLE
Journal Page Footer

### ISSUE THREAD

**Issue by anewmn** [pkp/pkp-lib#782]
Text or HTML entered into the the 'Journal Page Footer' textbox does not appear on the journal's fronted page while using OJS 3.0b.

**Comment by NateWr** [comment]
Thanks for filing this. We're still discussing how we want to handle the footer in OJS 3.0. I'll chuck this issue into the 3.0 milestone, but hopefully we'll at least have a direction in mind before too long.

**Comment by NateWr** [comment]
This is working in latest master.
