### ISSUE TITLE
Add LICENCE file to https://github.com/pkp/ojs

### ISSUE THREAD

**Issue by hauschke** [pkp/pkp-lib#7829]
**Describe the problem you would like to solve**
There is no LICENCE file in  the https://github.com/pkp/ojs repository. This means, the licence information does not show up in the 'ABOUT' section in Github.

**Describe the solution you'd like**
In this repository it's compliant to the Github standard. This approach can be replicated.

**Who is asking for this feature?**
Users and contributors of OJS.

**Additional information**
![grafik](https://user-images.githubusercontent.com/1275231/161691225-4e91fc7a-af17-42c0-a6cb-9f5d30b2f33d.png)
![grafik](https://user-images.githubusercontent.com/1275231/161691540-25b7f171-2f1a-4be1-9148-e226aed744b5.png)

**Comment by asmecher** [comment]
Thanks, @hauschke! In the OJS, OMP, and OPS repositories the license is currently in `docs/COPYING` (though it looks like Github doesn't look there). I agree that we should update/standardize this but currently the code headers in all the code refer to `docs/COPYING` and we should probably clean that up in the process. It's already filed for attention at https://github.com/pkp/pkp-lib/issues/7818 so I'll close this issue in favour of that one.
