### ISSUE TITLE
Review use of events and hooks for consistency

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7831]
**Describe the problem you would like to solve**
A new event service provider was implemented to support job queues and email sending. Some pilot events were set up, such as `SubmissionDeleted`. However, events are not consistently used across the application, and sometimes overlap with hooks.

**Describe the solution you'd like**
Review use of events and hooks, decide on a consistent approach for when an event or hook should be used, and apply that where appropriate in the system.

In my view, hooks should be used whenever a plugin may wish to intervene before an action is taken. Examples: when an object is validated or _about to be_ added, edited or deleted; when getting a list of valid decisions; "lifecycle" hooks, like when a handler is loaded, before a template is rendered, etc.

Events should be used when an action has already been taken, and for any asynchronous actions. Examples: after an object is added or edited or deleted; after a submission or issue is published; after a job is run.

**Who is asking for this feature?**
Plugin developers will benefit if we are consistent and don't have to change events/hooks too much between releases.

**Comment by NateWr** [comment]
See also https://github.com/pkp/pkp-lib/discussions/8010

**Comment by NateWr** [comment]
Currently, our event listeners are named after the events they listen to. Some examples:

```
DecisionAddedListener
MetadataChangedListener
SubmissionDeletedListener
```

Listeners should be renamed to indicate _what they do_ instead of _the event they listen to_. Some examples:

```
DecisionAddedListener --> AssignDOIs
MetadataChangedListener --> UpdateSubmissionSearchIndex
SubmissionDeletedListener --> DeleteSubmissionSearchIndex
```

One event can have several listeners. Naming listeners this way will reduce the temptation to put code for different actions in one listener. Here are some examples of names for listeners subscribed to the `DecisionAdded` event.

```
AssignDois
LogDecision
UpdateEditorialNotifications
```

This should be added to the contributor's guide.

**Comment by NateWr** [comment]
@asmecher here is a first pass at renaming some of the events and observers. Can you take a quick look over the naming conventions here and let me know what you'd like to change? I can then roll it out to the rest of the apps. Or hand it off to you if you had something else in mind.

(I've got other questions about the search reindexing over at #8435).

PR:
https://github.com/pkp/pkp-lib/pull/8436

Tests:
https://github.com/pkp/ojs/pull/3623

**Comment by NateWr** [comment]
Thanks @asmecher. @bozana I've renamed the `Usage` event to `UsageEvent` and made a base class for it. Can you take a quick look at the changes to the usage event in the PRs above and let me know if I've missed anything?

**Comment by bozana** [comment]
Hi @NateWr, everything OK.
One more change is needed here: https://github.com/asmecher/lensGalley/blob/main/LensGalleyPlugin.inc.php. But, if you want, I can do it, when this is merged.
Else, maybe only one question: do we want to have events base class in the same folder observers/events/? -- this is a problem with listeners, because then two are found... so maybe to think about another place for events and listeners base classes/traits, so that the solution for both is the same... ?

**Comment by NateWr** [comment]
Thanks @bozana. I've added a PR for LensGalley. 

> do we want to have events base classes in the same folder observers/events/? -- This is a problem with listeners, because then two are found...

I _think_ this will be ok because the base class is an `abstract` class. It shouldn't be possible to instantiate or dispatch this event class.

**Comment by NateWr** [comment]
I've merged the PRs in now. OMP had one failed test, but I rebased the tests twice and each time it was a different test that failed. Travis isn't letting me restart the one test, so I'll assume it's ok.
