### ISSUE TITLE
moveLocaleKeysToLib needs line break before entries appended to pkp-lib .po files

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7834]
**Describe the bug**
When using the `moveLocaleKeysToLib` script, locale keys and strings are appended to the end of the target po file, but a line break is not added before the last entry. This causes the locale key to not be properly recognized. E.g.:

```
msgid "test.key"
msgstr "Test string"
msgid "appended.key"
msgstr "Appended text"
```

It should appear as:

```
msgid "test.key"
msgstr "Test string"

msgid "appended.key"
msgstr "Appended text"
```

**To Reproduce**
1. Run `moveLocaleKeysToLib.php`
2. View po file in pkp-lib that's had a new key appended to it.
3. See error

**What application are you using?**
 OJS `main` branch

**Additional information**
N/A

**Comment by ewhanson** [comment]
Hey @asmecher, I came across this while moving locale keys around. Could you have a look? Thanks!

PR:

- #7835

**Comment by asmecher** [comment]
Checks out for me -- thanks, @ewhanson!
