### ISSUE TITLE
Author who is also an editor can see reviewers' names in the discussion

### ISSUE THREAD

**Issue by kshuttle** [pkp/pkp-lib#7836]
**Describe the bug**
When the author of a submission also has a "journal editor" role in the journal, the reviewers' names are revealed when the author starts a Review Discussion, even if they:
- Are not assigned as a participant on the submission as any other role besides "author"
- Are the only author on the submission
- Select "Submit as author" during the submission process, when given the choice to submit as an author or editor.

The author does see the simplified (author) view for the article they authored. Reviewer identities are not visible to the author until they start a review discussion, at which point they can see the reviewers' names as possible recipients.

When they first enter the submission from the Submissions dashboard, it doesn’t ask whether they are entering the editorial dashboard as an editor. As far as I can tell they are only seeing what an author should see for this submission, except for when they start a discussion and see the reviewers as possible recipients.

**To Reproduce**
1. Login to the journal as a journal editor who also has an "author" role, and make a new submission as an author.
2. With a different journal editor account, push the submission through to peer review, assign reviewers, and have the reviewers submit their reviews.
3. Login again as the author and visit the Review tab. Open a Review Discussion and notice the reviewers' names are visible as possible recipients on the discussion thread.

![image](https://user-images.githubusercontent.com/59741486/162067070-3eab3d41-e782-401f-9b90-add7f7e173e6.png)

**What application are you using?**
OJS 3.3.x

**Additional information**
This issue was reported by a PKP | PS client and is related to issue #3130 which was addressed in version 3.1.

**Comment by NateWr** [comment]
I was able to reproduce this in `stable-3_3_0`. As a general rule, we discourage editors from acting as authors in their own journals, for reasons like this as well ethical considerations more broadly. But we do technically support it.

**Comment by NateWr** [comment]
While reviewing some unrelated code changes, I think I identified the source of the problem. The logic here is will show reviewer names to editors even if they are assigned in another role:

https://github.com/pkp/pkp-lib/blob/stable-3_3_0/controllers/grid/queries/form/QueryForm.inc.php#L241-L247

The logic should be:

```
if (
    has_assignedRoles_manager_or_subeditor 
    OR 
    (has_no_assignedRoles AND is_admin_or_manager)
)
```

**Comment by touhidurabir** [comment]
@asmecher PRs to review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8460
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3639 [TEST ONLY]

**Comment by asmecher** [comment]
@touhidurabir, sorry for the wait -- I've added one comment: https://github.com/pkp/pkp-lib/pull/8460/files#r1042811892

**Comment by touhidurabir** [comment]
@NateWr updated based on your [last comment](https://github.com/pkp/pkp-lib/pull/8460#discussion_r1072074449). Please check the PRs now

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8460
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3639 [TEST ONLY]

**Comment by NateWr** [comment]
@touhidurabir these changes look good. Once you make a PR for `main` I'll merge them both. :+1:

**Comment by touhidurabir** [comment]
@NateWr Updated PRs

### Stable
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8460
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3639 [TEST ONLY]

### Main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8553
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3714 [TEST ONLY]

**Comment by asmecher** [comment]
The test failure is probably my fault -- I just sent up an updated pkp-lib submodule commit to `main` that should correct it.

**Comment by touhidurabir** [comment]
@NateWr all tests have passed, should be good to merge .

**Comment by NateWr** [comment]
All merged to `main` and `stable-3_3_0`. Thanks! :tada:
