### ISSUE TITLE
Reviewer cannot access Step 3 Download and Review (OJS 3.3) 

### ISSUE THREAD

**Issue by OJSomm** [pkp/pkp-lib#7845]
**Describe the bug**
Reviewer cannot access step 3 and conduct the review 

**To Reproduce**
1. Reviewer receives invitation by email and link to access to submission;
2. Enters at 1. Request... - accepts to review;
3. Step 2. Guidelines - Ok
4. Step 3 Download and review - **empty**

**What application are you using?**
OJS 3.3.0.7. 

**Additional information**

![image](https://user-images.githubusercontent.com/79702399/162486299-51c2d719-1295-4d2d-86a5-08b1e9bc4e32.png)

**Comment by asmecher** [comment]
@OJSomm, could you check your PHP error log for details?

**Comment by OJSomm** [comment]
Olá @asmecher, attached is .txt with logs for 8-april, when I did this test. I hope it will help to find the problem
[OJS.log.txt](https://github.com/pkp/pkp-lib/files/8473203/OJS.log.txt)
Thank you!

**Comment by OJSomm** [comment]
@asmecher OK, I will tell my colleagues :-)
Thank you!

**Comment by NateWr** [comment]
Closing this due to the lack of follow-up. Please consider posting in our [support forum](https://forum.pkp.sfu.ca/c/questions/5) for further assistance.
