### ISSUE TITLE
moveLocaleKeysToLib matches more than one key at a time

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7848]
**Describe the bug**
`moveLocaleKeysToLib.php` uses a substring check (`substr($line, 0, strlen($fullMsgidMatch)) === $fullMsgidMatch`) to determine if the provided key matches the key in the current iteration. This will match and move other locale keys if they contain the provided key, e.g. `doi.manager.settings.doiSuffix`. will also match and move `doi.manager.settings.doiSuffixPattern`.

**To Reproduce**
1. Run the moveLocaleKeysToLib tool on a locale key that will match more than one key, e.g. `php lib/pkp/tools/moveLocaleKeystoLib.php doi.manager.settings.doiSuffix manager.po manager.po`
2. See more than one locale key move from the app to pkp-lib.

**What application are you using?**
pkp-lib main branch

**Additional information**
N/A

**Comment by ewhanson** [comment]
Hey @asmecher, hopefully this is my last locale key tool-related question! Is the matching multiple keys behaviour intended? I ran into this and got around it by replacing the `substr()` comparison with this:
```PHP
preg_match("/^${fullMsgidMatch}$/", $line) === 1
```
If this is a bug, I can submit a PR with my fix. Thanks!

**Comment by asmecher** [comment]
@ewhanson, I see the bug you're pointing out, but dropping `{$fullMsgidMatch}` into a regular expression can have unwanted consequences (e.g. a `.` in a key name will match any character, not just `.`); plus the closing quote is not included in `$fullMsgidMatch`, so it'll fail as currently coded.

I haven't tested it, but you should be able to just test the complete line:
```diff
diff --git a/tools/moveLocaleKeysToLib.php b/tools/moveLocaleKeysToLib.php
index 2bf59fd52..97ac5a88e 100644
--- a/tools/moveLocaleKeysToLib.php
+++ b/tools/moveLocaleKeysToLib.php
@@ -106,11 +106,10 @@ class MoveLocaleKeysToLib extends \PKP\cliTool\CommandLineTool
             $changedSourceLines = [];
             $newTargetLines = [];
             $isMovingLine = false;
-            $fullMsgidMatch = 'msgid "' . $this->msgidMatch;
 
             $lines = explode("\n", file_get_contents($localeSourceFile));
             foreach ($lines as $i => $line) {
-                if (substr($line, 0, strlen($fullMsgidMatch)) === $fullMsgidMatch) {
+                if ($line === "msgid \"$this->msgidMatch\"") {
                     $isMovingLine = true;
                 } elseif (trim($line) === '#, fuzzy' || substr($line, 0, 5) === 'msgid') {
                     $isMovingLine = false;
```

**Comment by ewhanson** [comment]
Makes sense! I'll test it out to make sure it works as expected.

**Comment by ewhanson** [comment]
Hey @asmecher, I've tested your suggestion and it works as expected. I've created a PR for it as well. Thanks!

PR:

- #7849

**Comment by NateWr** [comment]
Thanks @ewhanson! I think that's how I intended it to work. I had temporarily modified it to do partial matches when I was moving email templates around, and must have left it that. :see_no_evil: 

I've merged that int.
