### ISSUE TITLE
Add select statements to all Collector::getQueryBuilder() methods

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7854]
**Describe the problem you would like to solve**
The `Collector::getQueryBuilder()` method is used to return a `QueryBuilder` with the appropriate join/where statements. Some `Collectors` add a default `select()` statement in the returned query, while others don't.

**Describe the solution you'd like**
All `Collector::getQueryBuilder()` methods should add a `select()` statement that is needed to retrieve full objects. (See discussion below.)

**Who is asking for this feature?**
See the following [discussion](https://github.com/pkp/pkp-lib/pull/7821#discussion_r844555274).

@asmecher:

> I think the `select` should be left to the `Collector` to add right where the query is first created. That way downstream code can work with the select list, including using `addSelect` to add columns; if `select` is called later it clobbers the whole select list. (I've done this in `classes/user/Collector.inc.php` if you want an example.)

@NateWr:

> In my view, the `getQueryBuilder()` method should not apply any `select()` statements, because it shouldn't presume to know what kind of information the caller wants to retrieve. You're right that the caller can override the `select()` with their own, but each calling method (`getIds()`, `getCount()`, and `getMany()`) will want to retrieve different things. 
> 
> If the `Collector::getQueryBuilder()` should default to selecting something, I think it should default to something more performant, like getting the IDs. Defaulting to the full row will encourage plugins to do things like this:
> 
> ```php
> $count = $collector
>     ->getQueryBuilder()
>     ->where(/* custom condition */)
>     ->get()
>     ->count();
> ```
> 
> Under-the-hood, that will instantiate `stdClass` objects for all row data just to perform a count on the `Collection`. By keeping the `select()` statement out of it, we can force plugins to choose their select statement, and therefore to think about the performance impacts of that choice.
> 
> I'm not wedded to this idea. It basically comes down to whether or not the `Collector` should bake in a default and, if so, what that default should be. But I do think that right now we're getting full objects too much, and this is costing us in performance. Maybe we'll solve this with caching in the future. But I think it's likely that we'll implement more DAO methods that fetch _more than_ ids/counts but _less than_ full entity objects. And in that sense, it might be good discipline for us to not have a default that presumes the query wants to retrieve everything.

**Comment by asmecher** [comment]
@NateWr, thinking about this further:

I don't think the select lists are going to have much of an impact on performance either way. Performance issues are going to come from within the DBMS (large join lists, insufficient indexes, etc) or through the sheer volume of queries.

If we want to tease apart our SELECT behavior, e.g. to only select certain columns, it makes sense to also consider the join lists. If we remove the default columns from the SELECT, then we would also need to implement the default list somewhere alongside the `DAO::fromRow` function, which defines expectations for what columns will be selected, and which is the most common consumer of Collector results.

I'm pretty sure this is not where we want to jump into optimization. Our main, major focus should be to cut down on the number of queries through simple waste reduction (as opposed to e.g. complicated caching additions), and through identifying which of the queries are the worst offenders both for volume and performance. As long as our query count is in the thousands, this stuff really won't rate (and even then I suspect it won't).

**Comment by NateWr** [comment]
Ok, makes sense to me. So our decision is to add the full select statements to the `Collector::getQueryBuilder()` method, right? I've updated the issue description above to reflect this.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/8197
- https://github.com/pkp/ojs/pull/3505 (tests only)

**Comment by asmecher** [comment]
Merged!
