### ISSUE TITLE
It is possible to publish an article with no authors

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7856]
**Describe the bug**
During the submission process, the wizard will prevent the submission of the metadata step (step 3) if you delete all of the authors in the contributors grid.  However, once the submission is submitted, a submission in the workflow can have all of its authors removed, and publishing is still possible.

This in itself may not be a bug, but it prevents any articles like this from being exported using the Native XML plugin since the schema requires an authors element with at least one author in it.

Can the contributors grid handler prevent the removal of the last contributor?

**To Reproduce**
1.  Create a new submission, you'll need to include an author.
2.  Once submitted and in the workflow, advance it to the CE stage, and remove all of the authors.
3. Publish the submission.
4. Attempt to export the submission with the Native XML plugin.  It will fail validation.

**What application are you using?**
OJS 3.3.0.10

**Comment by asmecher** [comment]
@jnugent, per this issue:

https://github.com/pkp/pkp-lib/issues/5955

...we do intend to support authorless submissions, so I think the best instant solution would be to relax the Native XML schema to allow submissions without authors.

**Comment by jnugent** [comment]
Hi @asmecher I think in our specific case we're going to ask the client to go back and add authors since they intend to use the native XML generated here as a source of import into another installation and the import there will also require authors.
