### ISSUE TITLE
Add API endpoint to get a submission's editorial decisions

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7863]
**Describe the problem you would like to solve**
The API endpoint supports writing editorial decisions but not getting them. A third-party tool can not use the API to determine what decisions have been recorded.

**Describe the solution you'd like**
Add an API endpoint, `GET /submissions/<id>/decisions`, to get all the decisions recorded on a submission.

**Who is asking for this feature?**
A question from the systems team. But it should be very easy to add this. The decision's repository already has the methods to do this.

**Comment by touhidurabir** [comment]
@NateWr please review the PRs

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8298
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3557

**Comment by NateWr** [comment]
Thanks @touhidurabir! I've merge that to `main` now. I added a text label and description to the API response in this commit: https://github.com/pkp/pkp-lib/commit/1631b8eeaeca356028e5a432c6405ea86da77245
