### ISSUE TITLE
Full title in page title and DC.Title

### ISSUE THREAD

**Issue by diegoabadan** [pkp/pkp-lib#7864]
OJS does not display subtitle in HTML page title (<title> tag) and dublin core metadata.

Example:
view-source:https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php/testdrive-journal/article/view/723

**To Reproduce**
1) Access an article with the title and subtitle metadata populated. E.g.: https://www.rbmfc.org.br/rbmfc/article/view/3052
2) Check the HTML <TITLE> tag and the <meta name="DC.Title"...> in the source code
3) Compare with <meta name="citation_title" to check the expected value.

**What application are you using?**
 OJS, OMP or OPS version 3.3.0-8 to 3.3.0-10

**Additional information**

This issue has occurred elsewhere, see: https://github.com/pkp/pkp-lib/issues/4021 and related issues.

**Comment by diegoabadan** [comment]
Depreciate `$article->getTitle()` for something like `$article->getMainTitle()` help us and avoid other cases?
Maybe it makes the best decision easier by using getFullTitle or just the main title...

**Comment by iudizm** [comment]
Just sent Pull Requests to OJS and OMP.

@asmecher, in OMP we also noticed that the GoogleScholar plugin is also [setting](https://github.com/pkp/omp/blob/7f0f70db5a594cacf271599d2fb2f1ccf8101b0f/plugins/generic/googleScholar/GoogleScholarPlugin.inc.php#L62) the `citation_title` metadata without the subtitle, should we fix this too?

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/3398/files
- https://github.com/pkp/omp/pull/1117/files

**Comment by asmecher** [comment]
@bozana, would you mind reviewing these?

**Comment by bozana** [comment]
Hi @asmecher. That looks good, but: 
- It seems we mix `article` (i.e. current publication) and `publication` (i.e. actual publication) -- in some places (e.g. templates/frontend/pages/article.tpl) we use `article` in DC plugin we use `publication`. Thus those might differ... But, this is maybe a task for another time, to check and think and decide... ?
- What about chapter in OMP DC -- it seems they could have subtitles too and only getTitle() is used... ?
- What about templates/frontend/pages/preprint.tpl -- it uses getLocalizedTitle() instead of getLocalizedFullTitle() ?
Thanks a lot!

**Comment by iudizm** [comment]
> What about templates/frontend/pages/preprint.tpl -- it uses getLocalizedTitle() instead of getLocalizedFullTitle() ?

@bozana, we just sent a PR over to OPS fixing this:
* https://github.com/pkp/ops/pull/280

**Comment by bozana** [comment]
Thanks @iudizm! I thought @asmecher made the PRs, that's why I wrote to him... :-DDD Sorry!
Let me then just check the GoogleScholar too...

**Comment by bozana** [comment]
@iudizm, would it be possible for you to fix the GoogleScholar too?
Similar to the publications, the chapters in OMP should also be able to use getLocalizedFullTitle($preferedLocale) and getFullTitles(). But this would mean that we would need to implement those function. Of course you do not need to do this here, in this issue, just if you would like to.

**Comment by bozana** [comment]
@asmecher, I cannot remember any more: Why do we use `$publication->getLocalizedFullTitle($monograph->getLocale()))` in DC in OMP and `$publication->getLocalizedFullTitle())` (i.e. once with and once without preferred (submission) locale)? Shall maybe everything be just `$publication->getLocalizedFullTitle())`?

**Comment by asmecher** [comment]
In general we should never depend on the current session's locale in providing metadata -- it should always be in the submission's main locale, ideally including other languages as part of the metadata when it's supported.

**Comment by iudizm** [comment]
> @iudizm, would it be possible for you to fix the GoogleScholar too?

Done that in the above commit. 

> Similar to the publications, the chapters in OMP should also be able to use getLocalizedFullTitle($preferedLocale) and getFullTitles(). But this would mean that we would need to implement those function. Of course you do not need to do this here, in this issue, just if you would like to.

I'm happy to do so 😊. As soon as its done, I will commit it to the PR

**Comment by iudizm** [comment]
@bozana, I believe its all done 😊

PRs:
* https://github.com/pkp/ops/pull/280
* https://github.com/pkp/ojs/pull/3398
* https://github.com/pkp/omp/pull/1117

**Comment by bozana** [comment]
:tada:  @iudizm, thanks a lot! Great contribution! Especially thanks for the test! :heart_eyes:
I merged it all, will then port it to the main branch and then close this issue...

**Comment by iudizm** [comment]
😁😁 Nice! We are happy to help!

**Comment by nils-stefan-weiher** [comment]
Hi everyone,

I get an exception in a fresh OMP install with "stable-3_3_0" branch ( currently checked out commit 42cea48273a09dc60cd4b0794384de4bcfa19351) which I could trace back to this change.

```
[Tue Jun 14 13:15:40 2022] 127.0.0.1:33028 [500]: GET /index.php/test/catalog/view/1/1/3 - Uncaught Error: Call to undefined method Submission::getFullTitles() in /home/nw/dev/projects/omp-3-3/plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.inc.php:221
Stack trace:
#0 /home/nw/dev/projects/omp-3-3/lib/pkp/classes/plugins/HookRegistry.inc.php(107): DublinCoreMetaPlugin->monographFileView()
#1 /home/nw/dev/projects/omp-3-3/pages/catalog/CatalogBookHandler.inc.php(307): HookRegistry::call()
#2 /home/nw/dev/projects/omp-3-3/pages/catalog/CatalogBookHandler.inc.php(216): CatalogBookHandler->download()
#3 /home/nw/dev/projects/omp-3-3/lib/pkp/classes/core/PKPRouter.inc.php(395): CatalogBookHandler->view()
#4 /home/nw/dev/projects/omp-3-3/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()
#5 /home/nw/dev/projects/omp-3-3/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()
#6 /home/nw/dev/projects/omp-3-3/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch()
#7 /home/nw/dev/projects/omp-3-3/index.php(64): PKPApplication-> in /home/nw/dev/projects/omp-3-3/plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.inc.php on line 221
```

Can someone reproduce this exception?

Best regards,

Nils

**Comment by bozana** [comment]
Hi @nils-stefan-weiher, oh, I have apparently overseen this... yes, it seems it should be `getFullTitle(null)` instead of `getFullTitles()`. I will double check and provide a fix here.
If you have opportunity to change that and test, it would be great...

**Comment by bozana** [comment]
@nils-stefan-weiher, the fix has just been merged, could you please test/see if now everything is OK?

**Comment by nils-stefan-weiher** [comment]
Thanks @bozana for the quick work.
For me the catalog view is working again with the current stable-3_3_0 branch.

**Comment by bozana** [comment]
This work is in the stable branch but needs porting to the main branch for 3.4, so I will change the milestone

**Comment by bozana** [comment]
PRs for the main branch:
ojs: https://github.com/pkp/ojs/pull/3513

**Comment by bozana** [comment]
@asmecher, could you please take a look at this PR for the main branch? -- The differences to the stable branch are: I am now using the submission locale for author names and for DC.Title (instead of UI locale). 
Also, I added the _lang_ attribute to the DC.Title. Does this make sense?
What do you think about using `lang` attribute for authors i.e. DC.Contributor.PersonalName, to list the author's names in all languages?
Thanks a lot!

**Comment by bozana** [comment]
I removed this comment -- I was wrong -- Just forget it... Sorry!

> @asmecher, could you please take a look at this PR for the main branch? -- The differences to the stable branch are: I am now using the submission locale for author names and for DC.Title (instead of UI locale).
> Also, I added the lang attribute to the DC.Title. Does this make sense?
> What do you think about using lang attribute for authors i.e. DC.Contributor.PersonalName, to list the author's names in all languages?
> Thanks a lot!
