### ISSUE TITLE
Recommend Similar Articles plugin uses the wrong article identifier

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#7866]
**Describe the bug**
In the Recommend Similar Articles plugin we attempt to pull the keywords for the current article by ID, but as of OJS 3.2 we are fetching a Publication ID and passing to the search as an Article/Submission ID.
```
        $articleId = $displayedArticle->getId();
        $articleSearch = new ArticleSearch();
        $searchTerms = $articleSearch->getSimilarityTerms($articleId);
```
https://github.com/pkp/ojs/blob/4bddb6959aa77ec2f45354a917041ae961b4ad07/plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.inc.php#L75-L77

**To Reproduce**
1. Enable Recommend Similar Articles plugin
2. Go to a published article which has a publication id which corresponds with another published article id
2. Scroll down to Similar Articles in the Article Footer.
4. The link "start an advanced similarity search" will contain the keywords not for this article, but for the publication with the id which matches this article's id

**What application are you using?**
 OJS version 3.2

**Additional information**
Is the correct solution to get the actual article/submission id from `$displayedArticle`, or to rework `$articleSearch->getSimilarityTerms()` to expect a publication id?

**Comment by jonasraoni** [comment]
Looks like this has been fixed already, I've just checked and the `$displayedArticle = $smarty->getTemplateVars('article');` is a Submission.

**Comment by ctgraham** [comment]
@jonasraoni , what version/s of OJS did you confirm this against?

**Comment by jonasraoni** [comment]
@ctgraham I've just checked against OJS 3.3: [A](https://github.com/pkp/ojs/blob/stable-3_3_0/pages/article/ArticleHandler.inc.php#L94) > [B](https://github.com/pkp/ojs/blob/stable-3_3_0/pages/article/ArticleHandler.inc.php#L118) > [C](https://github.com/pkp/ojs/blob/stable-3_3_0/pages/article/ArticleHandler.inc.php#L196)

As we're not actively supporting OJS < 3.3, I didn't check the branch you've reported (3.2).

**Comment by ctgraham** [comment]
Thanks.  I'll assume 3.3.0-14.  Wanted to make sure you weren't just looking at 3.4.
