### ISSUE TITLE
Unexpected closing of modal windows when selecting text with the mouse

### ISSUE THREAD

**Issue by edhelll** [pkp/pkp-lib#7868]
If I select text by mouse anywhere in modal window and release mouse button outside of window, then modal window closes.

In fact, this problem concerns not only text selection. If we click mouse button inside window, but release outside - window close handler fired.

**What application are you using?**
OJS 3.3.0.3

**Comment by edhelll** [comment]
Now I totally disable closing modal windows by clicking outside of windows: in ModalHandler.js comment modalClose() call after line "// Close click events directly on modal (background screen)". Otherwise, more problems than benefits.

**Comment by jonasraoni** [comment]
Hi @edhelll,

I'm closing this one in favor of: https://github.com/pkp/pkp-lib/issues/6653
