### ISSUE TITLE
Modal closes unexpectedly when trying to save a multilingual form

### ISSUE THREAD

**Issue by edhelll** [pkp/pkp-lib#7869]
**Describe the bug**
If multilingual field is focused in modal window (e.g. edit file in submission) and press "Save" button, then modal window tries to close instead of saving. Its happens when textfield collapsed to only one main language, modal window is resized and "Save" button moves up.

**To Reproduce**
1. Open any submission
2. Click "Edit" on any file
3. Click on textfield "Name the file" (it must be multilingual)
4. Enter any changes in textfield
5. Click "Save button" at the bottom
6. Result: popup window shown "The data on ths form has changed. Do you wish to continue without saving?"

**What application are you using?**
OJS 3.3.0.3

**Comment by edhelll** [comment]
Now I totally disable closing modal windows by clicking outside of windows: in ModalHandler.js comment modalClose() call after line "// Close click events directly on modal (background screen)". Otherwise, more problems than benefits.

**Comment by jonasraoni** [comment]
Hi @edhelll!

I believe this issue has been addressed in newer releases of 3.3.0, given that multilingual fields are floating and do not resize the modal interface anymore (see image below), so I'll close this one. You might take a look at the current release here: https://pkp.sfu.ca/ojs/ojs_demo/

![image](https://user-images.githubusercontent.com/361921/163829317-c1b3efb3-ea9f-4ba7-87fd-69f6766a52ff.png)

**Comment by edhelll** [comment]
Indeed, I could not reproduce the problem on the demo site with latest version. Though the size of modal windows changes a little.
