### ISSUE TITLE
National characters should not be removed from the names of downloaded files

### ISSUE THREAD

**Issue by edhelll** [pkp/pkp-lib#7870]
**Describe the bug**
Files uploaded by authors can often consist mainly of national characters, so when downloading such files, they are saved as ----.docx, ---.--.docx, etc. Sometimes even saved as simply "docx" (probably when the file consists of one word).

**What application are you using?**
OJS 3.3.0.3

**Additional information**
I fix it in file lib/pkp/classes/services/PKPFileService.inc.php, method formatFilename, line:
$newFilename = \Stringy\Stringy::create($filename)->toLowerCase()->dasherize()->regexReplace('[^a-z0-9\-\_.]', '');
replaced by:
$newFilename = \Stringy\Stringy::create($filename)->toLowerCase()->dasherize()->toAscii()->regexReplace('[^a-z0-9\-\_.]', '');

**Comment by jonasraoni** [comment]
Hi @edhelll!

Thanks for the report. Looks like this code doesn't exist anymore, I guess your issue has been addressed by this line: https://github.com/pkp/pkp-lib/blob/main/classes/services/PKPFileService.inc.php#L165 which is related to this issue: https://github.com/pkp/pkp-lib/issues/7794.

I'll close the issue for now, let me know if you think I misunderstood something.

**Comment by edhelll** [comment]
Really, in the latest version the files are downloaded with their original names.

**Comment by jonasraoni** [comment]
Great! That's a good signal that things are evolving :)
