### ISSUE TITLE
Registration process throwing unhandled exception for new user registration.

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#7880]
**Describe the bug**
The registration process is throwing internal unhandled exception for a new user registration . The newly registered user do get stored in the DB but success/confirmation page return back as error which make it looks like the registration process failed . 

**To Reproduce**
After a successful installation and set up for journal . 
1. Try to register a new user for a specific journal
2. The redirect page is showing something like `unable to handle the request` which point to an internal `500` error .

The expected behaviour is a success/confirmation page on successful registration done or a information for next step if the user validation is set in the `config` file by setting by
```
; If enabled, email addresses must be validated before login is possible.
require_validation = On
```

**What application are you using?**
 OJS version main

**Additional information**
This issue only arise in the `main` branch and works properly in the branch `stable-3_3_0` as tested .

**Comment by touhidurabir** [comment]
this is the reason exception is originating , https://github.com/pkp/pkp-lib/blob/main/pages/user/RegistrationHandler.inc.php#L72

in the RegistrationHandler  file , `$user`  is return as `null` because of following lines

```php
$userId = $regForm->execute();

$user = Repo::user()->get($userId);
```

Here we are passing the $userId  to retrieve the user instance but in the PKP\user\Repository  class as defined

```php
/** @copydoc DAO::get() */
public function get(int $id, $allowDisabled = false): ?User
{
    return $this->dao->get($id, $allowDisabled);
}
```

```php
/**
 * @copydoc EntityDAO::get()
 *
 * @param bool $allowDisabled If true, allow fetching a disabled user.
 */
public function get(int $id, $allowDisabled = false): ?User
{
    $user = parent::get($id);
    if (!$allowDisabled && $user->getDisabled()) {
        return null;
    }
    return $user;
}
```

the fix to very small , just need to call the user repo as
```php
$user = Repo::user()->get($userId, true);
```

so that it does return the user instance even for `disabled` user

**Comment by touhidurabir** [comment]
@asmecher I have made 2 pull request for `main` branch of `pkp-lib` and `ojs` . once the test passes and you review the code , I will make pull request for `ops` and `omp` . As mentioned in the issue , then only require fix for the `main` branch only . 

PR list 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7880 Registration process throwing unhandled exception for new user registration](https://github.com/pkp/pkp-lib/pull/7884)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7880 Submodule Update ##touhidurabir/i7880_fix_main##](https://github.com/pkp/ojs/pull/3381)

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I've merged the PRs above and directly committed submodule updates for OMP and OPS `main`; no need to open PRs there.
