### ISSUE TITLE
User verification process failing with internal exception 

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#7881]
**Describe the bug**
When set to `validate user` in the `config` , the validation/verification process not working properly after registration . 

**To Reproduce**
After a successful installation of OSJ and setting up journal
1. Make sure in the config file `require_validation` is set to `On`.
2. Go to inbox to retrieve the validation email and copy validation link 
3. Visit the validation link 
4. It supposed to provide/show a success/confirmation page that confirm validation/verification done successfully but instead show something like `can not handle the request` which point to a `500 internal error`. 

**What application are you using?**
 OJS version `3.3.0` and `main`

**Additional information**
Associated with this , for the `main` branch, the generated and passed `validation link` in the email is broken . The link generated as `BASE_URL/index.php/index/user/activateUser//2pfsx9` instead of `BASE_URL/index.php/index/user/activateUser/USER_USERNAME/2pfsx9` , that is in the url , user's `username` segment is missing which breaks the validation process for the main branch installation .

**Comment by touhidurabir** [comment]
@asmecher can you review once the test passes . 

### `stable-3_3_0` branch PRs
1. [pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7881 User verification process failing with internal exception](https://github.com/pkp/pkp-lib/pull/7887)
2. [ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7881 Submodule Update ##touhidurabir/i7881_fix_stable_3_3_0##](https://github.com/pkp/ojs/pull/3383)

### `main` branch PRs
1. [pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7881 User verification process failing with internal exception](https://github.com/pkp/pkp-lib/pull/7888)
2. [ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7881 Submodule Update ##touhidurabir/i7881_fix_main##](https://github.com/pkp/ojs/pull/3384)

There is significant changes between the PR of `main` and `stable-3_3_0` as per 

### `stable-3_3_0` branch issues : 
1. internal exception due to calling `AccessKeyManager` class's non static method `generateKeyHash` statically . 

### `main` branch issues :
1. internal exception due to calling `AccessKeyManager` class's non static method `generateKeyHash` statically . 
2. not passing the option to pull disables users from `DAO`  class `getByUsername` to `get` method which cause to return `null`
3. Broken verification links due to use of `$event->recipient->getData('username')` in the `PKP\observers\listeners\ValidateRegisteredEmail` class .

**Comment by asmecher** [comment]
Excellent, @touhidurabir! These were clear and clean enough that I was content to merge as is and take care of the OPS and OMP submodule updates directly. Thanks!
