### ISSUE TITLE
Portico plugin release v1_1_2-2 points to wrong commit

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#7882]
**Describe the bug**
The Portico plugin's release package of [v1_1_2-2](https://github.com/pkp/portico/releases/tag/v1_1_2-2) points to the wrong commit in the repository.  Specifically, note that the [version.xml file at b6d2ab](https://github.com/pkp/portico/blob/b6d2ab8ba69bc8e5ba829439c8177d6cdabc9ea1/version.xml) references "release" 1.0.0.3.

**To Reproduce**
1. Install OJS 3.3 via git (`stable-3_3_0` branch)
2. `git submodule add https://github.com/pkp/portico.git plugins/importexport/portico`
3. `cd plugins/importexport/portico`
4. `git checkout v1_1_2-2`
5. `grep release version.xml`

This means a probable error such as:
```
$ sudo -u apache php tools/upgrade.php upgrade
2022-04-20 13:40:33 [pre-install]
2022-04-20 13:40:33 [load: upgrade.xml]
2022-04-20 13:40:33 [version: 3.3.0.10]
2022-04-20 13:40:33 [code: Installer Installer::checkPhpVersion]
2022-04-20 13:40:33 [code: Installer Installer::installDefaultNavigationMenus]
WARNING: The NavigationMenu (ContextId: 1, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
WARNING: The NavigationMenu (ContextId: 1, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
WARNING: The NavigationMenu (ContextId: 0, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
2022-04-20 13:40:33 [code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
2022-04-20 13:40:33 [code: Installer Installer::addPluginVersions]
<h1>You are trying to downgrade the product &quot;portico&quot; from version [1.1.1.3] to version [1.0.0.3]. Downgrades are not supported.</h1>ojs2: You are trying to downgrade the product "portico" from version [1.1.1.3] to version [1.0.0.3]. Downgrades are not supported.
```

**What application are you using?**
 OJS version 3.3.0

**Additional information**
The tgz file has the correct release in version.xml.  It was probably packaged from:
https://github.com/pkp/portico/commit/a082a9d7e789ca413596565bf5a93fc0108b8af8
or
https://github.com/pkp/portico/commit/93fd11101b5141cba8aeda4e5ce31521266901ce

**Comment by asmecher** [comment]
@ctgraham, I'm tempted to leave this as a WONTFIX and let the next release bury it rather than rewriting history; would that cause problems for you? I'm not aware of anyone (else) using git to host plugins in a production environment.

**Comment by ctgraham** [comment]
With the advent of composer and npm dependencies we've moved away from git-based production deployments, so this only breaks development for us.  We query the plugin gallery to automatically deploy all compatible plugins as git submodules for development.  Right now that just fails as described above, which is annoying, but manageable.

**Comment by asmecher** [comment]
OK, thanks! I think we'll probably be releasing a new version not too long from now, so I'm content to let that bury this issue. But thanks for letting me know, I'll watch our workflow.
