### ISSUE TITLE
Contributor bio and country not included in API JSON

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7892]
**Describe the bug**
Despite having a biography and a country chosen for a contributor, this information is not present in the returned JSON when calling the submissions/xxxx/publications/xxx end point in the API:

![bios](https://user-images.githubusercontent.com/218719/165311151-c9b48dee-5669-4461-bf8f-f51000b4036c.png)

**To Reproduce**
1. Create and publish a submission with contributors that have bio and country info
2.  Load the API end point for that publication

**What application are you using?**
OJS 3.3.0.9

**Comment by NateWr** [comment]
This is working as intended. These properties are not given the `apiSummary` flag to appear in summaries. They won't be available until 3.4, which introduces dedicated API endpoints for contributors.
