### ISSUE TITLE
fatal error when thanking a reviewer

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7895]
**Describe the bug**
There's a syntax error in the Thank Reviewer form:

https://github.com/pkp/pkp-lib/blob/stable-3_3_0/controllers/grid/users/reviewer/form/ThankReviewerForm.inc.php#L117

That _ should be a closing bracket.  Currently a problem in stable 3.3, and seems to have gone in the commit 7 days ago

https://github.com/pkp/pkp-lib/commit/4f4dcc839c33249f4d11d46ef5dc0e41df0e043d

**Comment by asmecher** [comment]
Fixed -- thanks, @jnugent. This kind of typo will be caught by pre-commit hooks starting with 3.4.0.
