### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedAcronym()

### ISSUE THREAD

**Issue by yogajiwanjaya** [pkp/pkp-lib#7897]
Installed OJS 3.3.0.8

if i click notification, just loading menu, cant open all notification

this error log

[01-May-2022 20:18:44 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedAcronym() on null in /home/...../cache/t_compile/7bdb22b1beb9ad34cdbc123fe840c756abbed6db^642608917fb21577c3f7235b556979f3e7c86b25_0.app.controllersgridtaskstask..php:32
Stack trace:
0 /home/...../lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_626ec03bb8f440_34884567(Object(Smarty_Internal_Template))
1 /home/...../lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
2 /home/...../lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
3 /home/....../lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false,  in /home/...../cache/t_compile/7bdb22b1beb9ad34cdbc123fe840c756abbed6db^642608917fb21577c3f7235b556979f3e7c86b25_0.app.controllersgridtaskstask..php on line 32

- -- - -- - - - - - -- - - - - - - - - - - - - - - - 
in Chrome, inspect element --> console

this error
GET https://........ac.id/index.php/index/$$$call$$$/grid/notifications/task-notifications-grid/fetch-grid?_=1651436319281 500

how fix it

**Comment by Vitaliy-1** [comment]
Hi @yogajiwanjaya,

There isn't enough information to reproduce this bug. I'm going close this issue for now. I would encourage you to post in our support forum. You will find more help there than we are able to provide here: https://forum.pkp.sfu.ca/
