### ISSUE TITLE
One file disappearing when trying to upload multiple files

### ISSUE THREAD

**Issue by nennad** [pkp/pkp-lib#790]
Hi there, I'm just testing the OJS 3.0b and during submission I have run into an issue with plupload.
When I try to drag & drop multiple files one file always disappear from the list immediately after drop. 
I've tried in Google Chrome(Version 45.0.2454.101 (64-bit)) and Safari(Version 9.0 (11601.1.56)).

**Comment by asmecher** [comment]
Hi @nennad -- The plupload tool is intended to be configured for single file upload only. If you'd like to upload multiple files, you'll need to go through the file upload wizard once for each file. We're aware that this could be improved and have been looking at examples like Wordpress for batch uploads, but haven't made it a priority yet.
