### ISSUE TITLE
Exclude duplicated IDs from deleted records in OAI interface

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7901]
**Describe the bug**
Some installations appear to report deleted records with the same IDs as published records in the OAI interface. Details at https://gitlab.erudit.org/coalitionpublica/support/-/issues/98.

I suspect the cause is versioning -- perhaps a version is published, then another is published; the second is deleted, causing a deleted record to rightfully be created, but causing the OAI interface to report both a published and a deleted record with the same ID.

**What application are you using?**
OJS 3.2.x and 3.3.x

**Comment by asmecher** [comment]
It looks like https://github.com/pkp/pkp-lib/issues/6625#issuecomment-768752850 came back to bite me:
>> Do we need a migration to handle any bad tombstones between 3.2 and 3.3? I suspect if items are being published/unpublished, there may be some stray tombstones in there where they shouldn't be. But I doubt the problem is widespread.
>
> I don't think so... OAI data consumers should be resilient about deletion data, and as long as actual data gets properly delivered, I think trying to clean this up without doing a pretty thorough review first would just compound the problem.

I think the best solution will be to make the OAI query resilient against tombstones for records that aren't deleted; it will be patchable (rather than requiring a database-editing migration) and won't require a deep dive on old data conditions.

**Comment by asmecher** [comment]
Here is a SQL query to identify suspect records:
```sql
SELECT dot.* FROM data_object_tombstones dot
   JOIN submissions s ON (dot.data_object_id = s.submission_id)
   JOIN journals j ON (j.journal_id = s.context_id)
   JOIN publications p ON (s.current_publication_id = p.publication_id)
   JOIN publication_settings psissue ON (psissue.publication_id = p.publication_id AND psissue.setting_name='issueId' AND psissue.locale='')
   JOIN issues i ON (CAST(i.issue_id AS CHAR(20)) = psissue.setting_value)
WHERE i.published = 1 AND j.enabled = 1 AND p.status = 3;
```

**Comment by stuartayeates** [comment]
We appear to have encountered this bug in our production environment. See https://ojs.victoria.ac.nz/aha/oai?verb=ListRecords&metadataPrefix=oai_dc record oai:ojs.pkp.sfu.ca:article/6750 appears twice, once deleted. 

[I'm aware that we should not be using 'oai:ojs.pkp.sfu.ca' in our identifiers, we're planning on fixing this with our next minor upgrade.]

Running the SQL query above, gives:

```
 SELECT dot.* FROM data_object_tombstones dot    JOIN submissions s ON (dot.data_object_id = s.submission_id)    JOIN journals j ON (j.journal_id = s.conte   JOIN publications p ON (s.current_publication_id = p.publication_id)    JOIN publication_settings psissue ON (psissue.publication_id = p.publication_id AND psissue.setting_name='issueId' AND psissue.locale='')    JOIN issues i ON (CAST(i.issue_id AS CHAR(20)) = psissue.setting_value) WHERE i.published = 1 AND j.enabled = 1 AND p.status = 3;
+--------------+----------------+---------------------+----------+----------+---------------------------------+
| tombstone_id | data_object_id | date_deleted        | set_spec | set_name | oai_identifier                  |
+--------------+----------------+---------------------+----------+----------+---------------------------------+
|          598 |           6751 | 2021-03-16 22:42:24 | aha:ART  | Articles | oai:ojs.pkp.sfu.ca:article/6751 |
|          594 |           6753 | 2021-03-16 22:42:23 | aha:ART  | Articles | oai:ojs.pkp.sfu.ca:article/6753 |
|          592 |           6754 | 2021-03-16 22:42:22 | aha:ART  | Articles | oai:ojs.pkp.sfu.ca:article/6754 |
|          600 |           6750 | 2021-03-16 22:42:24 | aha:ART  | Articles | oai:ojs.pkp.sfu.ca:article/6750 |
+--------------+----------------+---------------------+----------+----------+---------------------------------+
4 rows in set (0.05 sec)
```

We have a (relatively) full DEV setup, so if someone would care to progress the 'SQL query to identify suspect records' to an actual fix, we would be happy to test.

**Comment by asmecher** [comment]
Building on [my comment above](https://github.com/pkp/pkp-lib/issues/7901#issuecomment-1117674138), here are some queries to use:

1. Identify problem submissions (which have both tombstone entries and published articles):
   ```sql
   SELECT dot.tombstone_id, s.submission_id FROM data_object_tombstones dot
      JOIN submissions s ON (dot.data_object_id = s.submission_id)
      JOIN journals j ON (j.journal_id = s.context_id)
      JOIN publications p ON (s.current_publication_id = p.publication_id)
      JOIN publication_settings psissue ON (psissue.publication_id = p.publication_id AND psissue.setting_name='issueId' AND psissue.locale='')
      JOIN issues i ON (CAST(i.issue_id AS CHAR(20)) = psissue.setting_value)
   WHERE i.published = 1 AND j.enabled = 1 AND p.status = 3;
   ```
2. If the records above seem to match the problematic OAI records (by submission ID), then you can remove them using one of the following:
   - MySQL/MariaDB:
      ```sql
      DELETE dot
        FROM data_object_tombstones dot
        JOIN submissions s ON (dot.data_object_id = s.submission_id)
        JOIN journals j ON (j.journal_id = s.context_id)
        JOIN publications p ON (s.current_publication_id = p.publication_id)
        JOIN publication_settings psissue ON (psissue.publication_id = p.publication_id AND psissue.setting_name='issueId' AND psissue.locale='')
        JOIN issues i ON (CAST(i.issue_id AS CHAR(20)) = psissue.setting_value)
      WHERE i.published = 1 AND j.enabled = 1 AND p.status = 3;
      ```
   - PostgreSQL:
      ```sql
      DELETE FROM data_object_tombstones dot
        USING submissions s, journals j, publications p, publication_settings psissue, issues i
        WHERE dot.data_object_id = s.submission_id
          AND j.journal_id = s.context_id
          AND s.current_publication_id = p.publication_id
          AND psissue.publication_id = p.publication_id
          AND psissue.setting_name='issueId' AND psissue.locale='' AND (CAST(i.issue_id AS CHAR(20)) = psissue.setting_value)
          AND i.published = 1 AND j.enabled = 1 AND p.status = 3;
      ```

@stuartayeates, if you can confirm that these identify and resolve the issue for you, I can get them committed! There are no code changes required -- just the database query to clean out erroneous data. Please take a database backup before running queries manually.

**Comment by stuartayeates** [comment]
I loaded the SQL into DEV and run the code (see below). If I understand correctly, this is what success is meant to look like?

I also checked every item in the issue of the journal (all of the items with issues were in a single issue of a single journal) and the HTML page, associated PDF and DOI link all worked, with no obviously-related issues in the httpd logs or in the display of content. 

I'm more than happy to make any other checks that seem relevant, but I couldn't think of any. @asmecher let me know if there's anything else you would like me to check.

```
mysql> SELECT dot.tombstone_id, s.submission_id FROM data_object_tombstones dot
    ->    JOIN submissions s ON (dot.data_object_id = s.submission_id)
    ->    JOIN journals j ON (j.journal_id = s.context_id)
    ->    JOIN publications p ON (s.current_publication_id = p.publication_id)
    ->    JOIN publication_settings psissue ON (psissue.publication_id = p.publication_id AND psissue.setting_name='issueId' AND psissue.locale='')
    ->    JOIN issues i ON (CAST(i.issue_id AS CHAR(20)) = psissue.setting_value)
    -> WHERE i.published = 1 AND j.enabled = 1 AND p.status = 3;
+--------------+---------------+
| tombstone_id | submission_id |
+--------------+---------------+
|          598 |          6751 |
|          594 |          6753 |
|          592 |          6754 |
|          600 |          6750 |
+--------------+---------------+
4 rows in set (0.07 sec)

mysql> DELETE dot
    ->   FROM data_object_tombstones dot
    ->   JOIN submissions s ON (dot.data_object_id = s.submission_id)
    ->   JOIN journals j ON (j.journal_id = s.context_id)
    ->   JOIN publications p ON (s.current_publication_id = p.publication_id)
    ->   JOIN publication_settings psissue ON (psissue.publication_id = p.publication_id AND psissue.setting_name='issueId' AND psissue.locale='')
    ->   JOIN issues i ON (CAST(i.issue_id AS CHAR(20)) = psissue.setting_value)
    -> WHERE i.published = 1 AND j.enabled = 1 AND p.status = 3;
Query OK, 4 rows affected (0.04 sec)

mysql> SELECT dot.tombstone_id, s.submission_id FROM data_object_tombstones dot                                                                                                ->    JOIN submissions s ON (dot.data_object_id = s.submission_id)
    ->    JOIN journals j ON (j.journal_id = s.context_id)
    ->    JOIN publications p ON (s.current_publication_id = p.publication_id)
    ->    JOIN publication_settings psissue ON (psissue.publication_id = p.publication_id AND psissue.setting_name='issueId' AND psissue.locale='')
    ->    JOIN issues i ON (CAST(i.issue_id AS CHAR(20)) = psissue.setting_value)
    -> WHERE i.published = 1 AND j.enabled = 1 AND p.status = 3;
Empty set (0.02 sec)
```

**Comment by asmecher** [comment]
@stuartayeates, yes, thanks, that does look like a reasonable outcome (4 duplicate entries found, 4 records deleted, afterwards no more duplicates listed by the query). Are you seeing the duplicates disappear in the OAI interface as well?

**Comment by stuartayeates** [comment]
@asmecher I confirm that there are no more duplicates left in the OAI interface.

**Comment by asmecher** [comment]
For users of OJS 3.3.0 encountering this issue, you can either:
- Execute the `DELETE` database statement in [this comment](https://github.com/pkp/pkp-lib/issues/7901#issuecomment-1203144523) to clean out existing bad data, **or**
- Upgrade to OJS 3.4.0 (once released) to resolve the issue.

**Comment by asmecher** [comment]
(Thanks, @stuartayeates!)
