### ISSUE TITLE
Can not accept a submission if associated review has any review form attached to it.

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#7909]
**Describe the bug**
At `Accept Submission`, if the associated review has any review form attached to it , it throws internal exception with 500 error code.

**To Reproduce**
1. Create a Submission.
2. Assign a reviewer and make sure it has a `Review Form` associated with it.
3. Complete the review process.
4. Try to `Accept Submission` and that will present a 500 error page . 

**What application are you using?**
 OJS installation of `main` branch .

**Comment by touhidurabir** [comment]
### Exception Tracing 

Exception originated from `PKP\mail\traits\ReviewerComments` as defined 

```php
if ($reviewFormElements->wasEmpty()) {
     return '';
}
```

Which delegate the call to `PKP\reviewForm\ReviewFormElementDAO` in the method `getByReviewFormId` as defined 

```php
...
return new DAOResultFactory($result, $this, '_fromRow');
```

which delegate to `PKP\db\DAOResultFactory` at method `getCount` where as no $sql is passed , so this line get executed as

```php
if ($this->sql === null) {
    throw new \Exception('DAOResultFactory instances cannot be counted unless supplied in constructor (DAO ' . get_class($this->dao) . ')!');
}
```

**Comment by touhidurabir** [comment]
@asmecher PRs. once reviewed, I will see if I need to forward the changes to `OPS` and `OMP`.

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7909 Can not accept a submission if associated review has any review form attached to it](https://github.com/pkp/pkp-lib/pull/7913)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7909 Submodule Update ##touhidurabir/i7909_fix_main##](https://github.com/pkp/ojs/pull/3394)

**Comment by asmecher** [comment]
Thanks, @touhidurabir! See this comment: https://github.com/pkp/pkp-lib/pull/7913#discussion_r868192045

**Comment by touhidurabir** [comment]
@asmecher changes are pushed . please review now .

**Comment by asmecher** [comment]
Merged -- thanks, @touhidurabir!
