### ISSUE TITLE
Replace HTMLPurifier with a maintained dependency

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7916]
[HTMLPurifier](http://htmlpurifier.org) is not maintained anymore. Find another replacement toolset for "safe" HTML filtering.

It does not support HTML5: https://forum.pkp.sfu.ca/t/tinymce-stripping-anchor-tags-within-or-around-divs/72749/12

We currently use HTMLPurifier in the `PKPString::stripUnsafeHtml` function (lib/pkp/classes/core/PKPString.inc.php). This takes a configuration of allowed elements/attributes from `config.inc.php`.

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9257
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4025 [TEST ONLY]
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1581 [TEST ONLY]
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/696 [TEST ONLY]
[jatsTemplate](https://github.com/pkp/jatsTemplate) --> https://github.com/pkp/jatsTemplate/pull/30
[oaiJats](https://github.com/pkp/oaiJats) --> https://github.com/pkp/oaiJats/pull/36

**Update**
Based on following reasons we have decided to revert back the [Symfony HTML Sanitizer](https://github.com/symfony/html-sanitizer) and keep using the [HTMLPurifier](https://github.com/ezyang/htmlpurifier)
- Bug in the [Symfony html sanitizer ](https://github.com/symfony/html-sanitizer)
  - [Html Sanitizer] Sanitization remove single < (less than) char which is not part of any tag(https://github.com/symfony/symfony/issues/57597)
  - Bug actually in the <https://github.com/Masterminds/html5-php> parser
  - [Parser remove the single < (less than) character from given html string](https://github.com/Masterminds/html5-php/issues/250)
- Also the use of [strip_tags](https://github.com/pkp/pkp-lib/blob/main/classes/core/PKPHtmlSanitizer.php#L78) will cause problem 
  - use of strip_tags omits anything after <=
  - we can overcome it by not using strip_tags and that better
  - Not using the strip_tags will removed any non standard tags and it's inner content, list of [w3c standard tags/elements/attributes](https://github.com/symfony/html-sanitizer/blob/7.1/Reference/W3CReference.php) list based on [w3c sanitization standard](https://wicg.github.io/sanitizer-api/) .

**Reverting Back HTMLPurifier**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10197
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4365 [TEST ONLY]
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1634 [TEST ONLY]
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/729 [TEST ONLY]
[jatsTemplate](https://github.com/pkp/jatsTemplate) --> https://github.com/pkp/jatsTemplate/pull/46
[oaiJats](https://github.com/pkp/oaiJats) --> https://github.com/pkp/oaiJats/pull/46

**Comment by touhidurabir** [comment]
There are few alternative packages/libraries to choose from as [HTMLPurifier](http://htmlpurifier.org/) is still the most common and widely used one even if it's not maintained properly and there has been no major upgrade of it . Most the of popular ones are also kind of based on that one which make those more like a wrapper over it . Few available options are (based on initial R&D)

1. [xemlock/htmlpurifier-html5](https://github.com/xemlock/htmlpurifier-html5) . This one also mentioned in the `pkp forum` at https://forum.pkp.sfu.ca/t/tinymce-stripping-anchor-tags-within-or-around-divs/72749/12 . As this allow compatibility of `HTML5`, it's still a wrapper over the not maintained [HTMLPurifier](http://htmlpurifier.org/) . However one big advantage of this one is that this does not require much modification of current implementation also any modification or option addition to the config options . 

2. [tgalopin/html-sanitizer](https://github.com/tgalopin/html-sanitizer) . This one seems relatively new comparing to [HTMLPurifier](http://htmlpurifier.org/) (first release at 2018) and seems to be maintained regularly . It has much better options and compatibility for `HTML5` also have better implementation. This one also available as `Symfony Bundle` so it may have high chance to be maintained properly . The only downside of this one is to make it work with our current config option implementation which may need more parsing before using with this package or we may need to add more config option in the `config` file . Need more research . 

3. [symfony/html-sanitizer](https://github.com/symfony/html-sanitizer) . This one maintained by `Symfony Team` and only released with `Symfony 6` . This one has a very fluent API to work with and high chance of maintained properly by `Symfony Team`. But even the initial released version is locked to `PHP 8.1+` so it will need to be used with a custom forked version to make it work for the `3.4` release target which aims to work with `PHP 8.0+` . And even with that , there may be additional workload the maintain the forked version up to date with future release . 

@asmecher @NateWr few stuff we need to figure out first 
1. what is the backward compatibility requirement for this enhancement/modification ? 
2. up to which PHP version ? 
3. How much of config option modification/addition we may allow ? Or should we try to keep the config option exact as same for this enhancement ? 

personally I would like to go with option 2 or 3 if we target for a long term supported package but if we just need to make it HTML5 compatible , option 1 may work for now . However , as option 1 is based on old [HTMLPurifier](http://htmlpurifier.org/) , it may not be maintained properly and security issue may arise . Need more research .

**Comment by asmecher** [comment]
Thanks, @touhidurabir! To summarize our convo today:
- `[xemlock/htmlpurifier-html5](https://github.com/xemlock/htmlpurifier-html5)` is a fork and I wouldn't normally recommend that approach but if we have a long-term solution that requires a stopgap (e.g. because of too high a PHP baseline) it's worth considering. (I don't see a formal statement anywhere that HTMLPurifier is not being maintained, but the release schedule sure doesn't look good.)
- `[tgalopin/html-sanitizer](https://github.com/tgalopin/html-sanitizer)` looks good but is a personal repo (does not seem institutionally supported). Not my first choice, though it has promising uptake.
- `[symfony/html-sanitizer](https://github.com/symfony/html-sanitizer)` -- we both agreed that something adopted/maintained by a big project like Symfony seemed like the best approach. However, as you noted, the PHP8.1 requirement is currently steep.

## Decisions

- We don't have a lot of calls for HTMLPurifier to be replaced -- it seems safe/mature enough to continue using, and it's still getting PHP compatibility fixes merged into Github. We can cautiously continue to use it for the time being.
- @touhidurabir will take a quick look to see if we can determine the maintenance roadmap for `[symfony/html-sanitizer](https://github.com/symfony/html-sanitizer)`. We could probably bump our PHP requirements for 3.6 (or possibly even 3.5) to PHP8.1 -- but if `[symfony/html-sanitizer](https://github.com/symfony/html-sanitizer)` is already on to a newer, more aggressive requirement by then, it may force our community into a difficult position.
- If `[symfony/html-sanitizer](https://github.com/symfony/html-sanitizer)`'s maintenance roadmap is compatible enough with ours, I'd recommend we consider adopting it later (3.5 or 3.6). This would mean waiting to implement it until that branch exists.

**Comment by touhidurabir** [comment]
@asmecher if this is not a higher priority right now , we can get back to this one later when we caught up with PHP 8.1+ . Another option is to use a forked version of [symfony/html-sanitizer](https://github.com/symfony/html-sanitizer) that we make compatible with PHP 8.0+ but even so this package by the `Symfony Team` is still in `BETA` state and that why it's still not included in their available component list at https://symfony.com/components . And maintaining a custom forked version may turn into a way more work that it should be.

Now there is no such info about how the future version will integrate newer version of PHP . So we are not sure if this package will have an aggressive PHP version upgrade policy but we can always use a lower release version. For example, if we look at https://symfony.com/releases/6.0 which support 8.0+ but the https://symfony.com/releases/6.1 will require 8.1+ which seems pretty aggressive . Some more general details can be found at https://symfony.com/doc/current/contributing/community/releases.html .

Also current `LST` version of Symfony is [5.4](https://symfony.com/releases/5.4) which will be supported for bug fix till 2024 and security fix till 2025 so there is a high chance we may not get a new LTS before 2024. So basically it's almost impossible to determine if we can have this [symfony/html-sanitizer](https://github.com/symfony/html-sanitizer) package for latest version with PHP version compatible for our next release so we may have to use a lower release version then.

**Comment by touhidurabir** [comment]
@asmecher Updated the implementation based on review comment but wait to rebase till pkp/pkp-lib#9110 merged as test will fail now anyway .

**Comment by touhidurabir** [comment]
@asmecher rebased and if all tests passes , it should be good to merge .

**Comment by asmecher** [comment]
Merged -- I'll update the submodule hashes manually. Thanks, @touhidurabir!

**Comment by asmecher** [comment]
@touhidurabir, one more thing needing a look here: We have a few additional use cases of `HTMLPurifier`, such as the OAIJats plugin, which uses it to filter out anything that's not a `<p>` element.

This commit swaps out HTMLPurifier for Symfony's HTML sanitizer: https://github.com/pkp/oaiJats/commit/3a5cdb227467d4effdc101e38052c0a86d850290

However, the two differ in behaviour. HTMLPurifier would look through the content for any allowed nodes, and return their values; Symfony's HTML sanitizer appears to drop anything appearing in a forbidden element. So consider the following input:
```html
<html><body><p>This is a paragraph.</p></body></html>
```
HTMLPurifier, given `p` as an allowed element, would purify this to:
```html
<p>This is a paragraph.</p>
```
However, Symfony's HTML sanitizer will return an empty string, because `html` and `head` are not in the allowed list.

Could you take a look at the OAIJats implementation (https://github.com/pkp/oaiJats) and try to fix it? (You'll also need to install the JATS Template plugin. It has a similar invocation of HTMLPurifier but I'm working on related aspects, so you can ignore that one for now.)

**Comment by touhidurabir** [comment]
> Symfony's HTML sanitizer will return an empty string, because html and head are not in the allowed list.

@asmecher that is why we are forced to user the `strip_tags` method before running the sanitization process .  I will take a look on this .

**Comment by touhidurabir** [comment]
@asmecher Please check the patched PR to support the plugin/general usage case, check the section `Patched PRs with Updates` at https://github.com/pkp/pkp-lib/issues/7916#issue-1229836527

**Comment by touhidurabir** [comment]
@asmecher Please see the plugins update at https://github.com/pkp/pkp-lib/issues/7916#issue-1229836527

**Comment by touhidurabir** [comment]
@asmecher can you please merge PRs at https://github.com/pkp/pkp-lib/issues/7916#issue-1229836527 . I do no have write access to plugins [oaiJats](https://github.com/pkp/oaiJats) and [jatsTemplate](https://github.com/pkp/jatsTemplate) .

**Comment by touhidurabir** [comment]
With the latest implementation, all previous issue should be resolved . Closing this now but will reopen if any issue arise again .

**Comment by touhidurabir** [comment]
@asmecher I think we need to return back the [HTML Purifier](https://github.com/ezyang/htmlpurifier) as I have found an issue with [symfony html sanitizer](https://github.com/symfony/html-sanitizer) . Please take a look at the issue [[Html Sanitizer] Sanitization remove single < (less than) char which is not part of any tag](https://github.com/symfony/symfony/issues/57597) .  

[symfony html sanitizer](https://github.com/symfony/html-sanitizer) is production grade package that ships as part of symfony bundler but I think this one does not suit all our cases . Or may be it need a bit more time to mature and we jump the gun here .

**Comment by asmecher** [comment]
Re-opening for consideration -- we may need to revert to HTMLPurifier if Symfony sanitizer doesn't better meet our needs by wrap-up time for 3.5.

**Comment by touhidurabir** [comment]
@asmecher please check the reversion PRs at https://github.com/pkp/pkp-lib/issues/7916#issue-1229836527 , see the section `Reverting Back HTMLPurifier` .

**Comment by asmecher** [comment]
Thanks, @touhidurabir! All is merged, and I took care of the submodule updates manually.
