### ISSUE TITLE
Cannot delete DOIs from UI

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7919]
**Describe the bug**
It is not possible to delete/remove a DOI from the DOI management page. See [discussion on #4056](https://github.com/pkp/pkp-lib/issues/4056#issuecomment-1101558443) for details.

**To Reproduce**
1. Go to DOIs
2. Select a publication and expand it.
3. Select edit DOI, delete the text, and attempt to save.

**What application are you using?**
 `main` branch

**Additional information**
N/A

**Comment by ewhanson** [comment]
Hey @NateWr, this adds a small change to allow deleting DOIs by submitting empty strings in the form field. Could you have a look? Thanks!

PRs:

- `ui-library`: pkp/ui-library#202
- `ojs`: pkp/ojs#3405
- `omp`: pkp/omp#1122
- `ops`: pkp/ops#281

**Comment by NateWr** [comment]
Thanks @ewhanson. Merged the UI Library PR and closed the others.
