### ISSUE TITLE
Generalize buildpkg.sh

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#7921]
**Describe the problem you would like to solve**
System administrators would like to use buildpkg.sh against their own forks of OJS.  Specifically, buildpkg.sh lies about its calling syntax, hardcodes the pkp repo, and is overly reliant on enumerating known composer dependencies and git submodules.  

Consider a fork of OJS which includes multiple plugins as submodules.  This script should be able to clone these submodules, run composer, remove the .git folders, etc.

**Describe the solution you'd like**
* [Allow the `$GITREP` variable to be defined outside of the script](https://github.com/pkp/ojs/blob/75c8a7312061053abc9cd6bd6a36dd6a3a8a226c/tools/buildpkg.sh#L16)
* [Clarify that `<tag>-<branch>` is a single required argument](https://github.com/pkp/ojs/blob/75c8a7312061053abc9cd6bd6a36dd6a3a8a226c/tools/buildpkg.sh#L19)
* [Allow for `$PREFIX` to be defined outside of the script.](https://github.com/pkp/ojs/blob/75c8a7312061053abc9cd6bd6a36dd6a3a8a226c/tools/buildpkg.sh#L25)
* [Remove `.git` directories via a find instead of enumeration](https://github.com/pkp/ojs/blob/75c8a7312061053abc9cd6bd6a36dd6a3a8a226c/tools/buildpkg.sh#L42)

**Who is asking for this feature?**
System administrators.

**Additional information**
Consider also the interest of the Docker build with this generalization.  E.g. https://github.com/pkp/pkp-lib/issues/6866

**Comment by ctgraham** [comment]
Is `buildpkg.sh` even currently used?  It still uses the obsolete `git://` protocol.
```
$ git clone git://github.com/pkp/ojs.git
Cloning into 'ojs'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

**Comment by ctgraham** [comment]
PRs:
* stable 3.3: https://github.com/pkp/ojs/pull/3399
* main: https://github.com/pkp/ojs/pull/3400

**Comment by asmecher** [comment]
(comment: https://github.com/pkp/ojs/pull/3400#issuecomment-1124274451)

**Comment by asmecher** [comment]
> Is buildpkg.sh even currently used? It still uses the obsolete git:// protocol.

Yes, it's used -- we just haven't released since unauthenticated `git://` was decommissioned a couple months ago.

**Comment by ctgraham** [comment]
@asmecher , the existing PRs are ready for your eyes again.

**Comment by ctgraham** [comment]
Finally back to you, @asmecher .

PRs:

- OJS 3.3: https://github.com/pkp/ojs/pull/3399
- OJS main: https://github.com/pkp/ojs/pull/3400
- OPS 3.3: https://github.com/pkp/ops/pull/309
- OJS main: https://github.com/pkp/ops/pull/310
- OMP 3.3: https://github.com/pkp/omp/pull/1158
- OMP main: https://github.com/pkp/omp/pull/1159

**Comment by asmecher** [comment]
All merged -- thanks, @ctgraham!
