### ISSUE TITLE
Update ORCID integration with contributor details

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#7922]
**Describe the problem you would like to solve**
The orcidProfile plugin integrates with the author form by modifying the orcid field, and adding checkboxes to send authorization requests. This will no longer work with the new forms in OJS/OPS 3.4.

**Describe the solution you'd like**
- The field "Orcid ID" in publication->contributors should be read-only when the orcidProfile plugin is activated.
- A mechanism to send emails to request authors enter and authenticate their orcids should be included where editors and submitting authors enter the contributor details.

**Who is asking for this feature?**
This preserves a plugin's feature since OJS 3.1, so it should be maintained.

**Additional information**
- Until OJS 3.3., this functionality was achieved through the registerFilter function in the TemplateManager, which no longer works in the main branch. 
- @NateWr suggested adding a slot to the contributor panel as a temporary measure to integrate email functionality for the orcidProfile plugin. We plan to bring orcid support into core, but not in time for 3.4.

**Comment by bozana** [comment]
@withanage, what is the status of this issue? Would you be able to do it?

**Comment by withanage** [comment]
@bozana  I am on it as a sub-task of the update to 3.4. Currently it is disabled for editing, but without modifying it with a Vuejs component, the "override" button is there, allowing the button to still be edited.  

Therefore, it does not yet exactly implement according to  the specification in the ticket description. 

![Screenshot from 2023-02-12 16-20-42](https://user-images.githubusercontent.com/1921992/218320055-86fb4f7c-d37e-4b3e-937f-a080d8dc07c9.png)

I will check tomorrow with Nate , if he has an idea there. Otherwise, I think will not be able to finish  this ticket before 15th.

**Comment by withanage** [comment]
@bozana 


> The field "Orcid ID" in publication->contributors should be read-only when the orcidProfile plugin is activated.

I have updated the orcid consortium parters about the current implementation  and this can be  marked as done.

> A mechanism to send emails to request authors enter and authenticate their orcids should be included where editors and submitting authors enter the contributor details.

This I think would not get before 3.4 release.

**Comment by asmecher** [comment]
@withanage, is this issue ready to be deferred from 3.4.0?

**Comment by withanage** [comment]
@asmecher yes, we need a form component that specifically shows contributors correctly, like in 3.3, I would postpone it until we implement this feature in forms.
As I understood correctly from @NateWr's Mattermost discussion. 
- The HTML form content cannot does not have the value.
- We can activate another form component if the value matches a truthful value, but not check if another component doesn't have the truthful value.

So I would defer it and not close it, because ORCID will not be satisfied until we show the ORCID symbol there as in the following image for co-authors.

![Screenshot from 2023-02-28 21-31-18](https://user-images.githubusercontent.com/1921992/221971961-fa66ea43-dd4b-4524-b9e2-ab2ab75fc1d8.png)

**Comment by asmecher** [comment]
OK, I've moved it to 3.4.0-x.
