### ISSUE TITLE
Can not view catalog page.

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#7923]
**Describe the bug**
When try to view the `Catalog` page from the admin, it showing a 500 internal error page . 

**To Reproduce**
1. Login as Manager/Admin.
2. Create a new Press.
3. Now try to view the Catalog page for that generated press.

**What application are you using?**
OMP 3.3.0.10 

**Additional information**
This exception is occurring for `OMP` installation on `PHP 8.0+` and for the `stable-3_3_0` branch. Not happening for the `main` branch . The cause of exception is similar to code such as
```php
$a ? $b : $c ? $d : $e 
```
which need to be modified as 
```php
$a ? $b : ($c ? $d : $e)
```
The code is modified as per need for `PHP 8.0+` for the `main` branch.

**Comment by asmecher** [comment]
Merged, thanks! Could you forward-port this to `main` as needed?

**Comment by touhidurabir** [comment]
@asmecher issue not present in `main` branch. so it's good to be closed . I am closing it .
