### ISSUE TITLE
conference papers (grey literature)

### ISSUE THREAD

**Issue by felixhelix** [pkp/pkp-lib#7924]
**Describe the problem you would like to solve**
Our partners asked if OJS can also be used for managing conferences call-for-papers, reviews and later publication of the presentations. The first two points can well be addressed using OJS. The last point, publication, is, however, problematic: If not in the form of "proceedings" the papers cannot be seen as "articles", and do not belong to any journal. They are a type of "grey literature".

OJS allows to add new "components". This could be a way to designate conference papers. These components have to be of the type "Document", "Artwork", or "Supplementary Content". "Document" is the most appropriate. However, "Document", as I understand it, refers to a journal article. As such, i.e. when the DOI is registered, they are not registered as conference papers, but as journal articles.

**Describe the solution you'd like**
I.m.o. what would help would be a new document type, which could then get the appropriate meta data and be registered (by Crossref or datacite) in the correct way.  That would make OJS capable to fully represent the workflow for conference submissions and publications.

**Who is asking for this feature?**
Scientific community.

**Comment by asmecher** [comment]
@felixhelix, this is probably needing more general/strategic discussion, and I'd like to pull in some other community members who might be interested. As such it's best discussed over on the support forum (https://forum.pkp.sfu.ca) rather than here; would you mind starting a topic over there? Feel free to link to this (closed) issue.

**Comment by felixhelix** [comment]
https://forum.pkp.sfu.ca/t/feature-request-conference-papers-grey-literature/73298?u=felixhelix
