### ISSUE TITLE
Two UserGroups with the same name for same context

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#7925]
**Describe the problem you would like to solve**
A user can add two (or more) UserGroups with the same Name, possibly causing confusion.

**Describe the solution you'd like**
The creation of a new UserGroup could be prevented if the context already contains a UserGroup with the same name to any locale.

**Additional information**
Already existing userGroups with the same name should be considered. (Merge the users to one of them? what if other attributes of the userGroup, such as role, is different? Maybe we could leave both userGroups and change the name for the "second" to "name_1" (if the original name was "name" for example)

**Comment by asmecher** [comment]
I'm guessing this arose from https://github.com/pkp/pkp-lib/pull/7928/files#diff-1b0cab100d69c17e5cfaf89755b89d19732fa8b92896e31520a93e0f5fe6a863R152, where we look up a user group by name.

IMO a better solution will be at some point to add symbolic name support for user groups, or some other kind of machine-readable vocabulary -- this will be necessary for https://github.com/pkp/pkp-lib/issues/857.

If still we need a general solution for duplicate names and titles, I'd rather approach it holistically, but in my opinion it would be more effort than it's worth.

I'm closing this for now, but we can always come back to it.
