### ISSUE TITLE
Native Import/Export: Better error message for missing UserGroup

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#7927]
**Describe the problem you would like to solve**
When importing a submission, the UserGroup of the Authors should be defined. The userGroup is defined by name, and if a usergroup with the same name does not exist in the destination installation, the import process fails.  

**Describe the solution you'd like**
Currently the error that the process produces is `msgstr "Unknown user group {$param}"`. It could be change to something more informative

**Who is asking for this feature?**
Users that use the Native Import/Export plugin

**Additional information**
Suggested message `msgstr "The import file includes an author '{$authorName}', with the user group '{$userGroupName}'. There is no user group defined in the destination installation with a user group with this name."`

**Comment by defstat** [comment]
@asmecher 

**PR**
[pkp-lib]: #7928

**Comment by asmecher** [comment]
Merged, thanks!
