### ISSUE TITLE
Needs DOI filter considers non-existent galley when running query

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7929]
**Describe the bug**
The Needs DOI filter should check if a submission is in the copyediting or production stage and if the item has any unassigned DOIs. With the current behaviour, if DOIs are enabled for both publications and galleys, but no galley has been assigned to a publication, the Needs DOI filter will always consider this publication as needing a DOI even if one is assigned to the publication.

**To Reproduce**
1. Go to DOIs management page.
2. Ensure DOIs are enabled for both publications and galleys.
3. Assign a DOI to a publication that does not have a galley created for it.
4. Filter by Needs DOI
5. See the submission still present despite having a DOI assigned to the only currently valid publication object.

**What application are you using?**
OJS `main`, but will apply to OMP and OPS

**Additional information**
N/A

**Comment by ewhanson** [comment]
Hey @asmecher, could you have a look at these PRs? Thanks!

PRs:

- `ojs`: pkp/ojs#3416
- `omp`: pkp/omp#1132
- `ops`: pkp/ops#289

**Comment by asmecher** [comment]
All merged, thanks @ewhanson. This is so much cleaner to work with, having DOIs stored in their own table, compared to stashing them as a setting!
