### ISSUE TITLE
Remove LinksHandler.inc.php

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#793]
The footer link categories currently link the category title in addition to the links. The category title just links through to a page which lists the links.

I've gotten rid of this (the category is just text, not a link), so I think we can get rid of the following files:

```
lib/pkp/pages/links/LinksHandler.inc.php
lib/pkp/templates/links/link.tpl
```

I wasn't sure if I could just delete them without causing problems, or if this is a bad idea. But I didn't want to let it slip by and then 3 years later someone is wondering why these files are still around.

So I thought I'd raise an issue. Any thoughts? I can remove the files if you approve, and will be packaged with some commits for the OMP 1.2 UI update.

**Comment by asmecher** [comment]
Nuke away!
