### ISSUE TITLE
Ensure umask is respected in file creation

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7930]
**Describe the bug**
From https://forum.pkp.sfu.ca/t/ojs-v3-3-0-10-some-submitted-files-in-files-dir-journals-are-world-writable/72969:
> Our nightly system check discovered world-writable files in $files_dir/journals, namely:
>
>    4/articles/337
>    4/articles/339
>    4/articles/336
>    4/articles/342
>    4/articles/338

> I checked the umask setting in config.inc.php, but it is “0022”.

**What application are you using?**
 OJS, OMP or OPS version 3.3.0-x (reproduced on 3.3.0-10)

**Comment by asmecher** [comment]
@bozana, could you review this?

**Comment by bozana** [comment]
@asmecher, just one comment/question, else all good... :+1:

**Comment by asmecher** [comment]
Thanks -- merged!
