### ISSUE TITLE
Update DOI suffix generator based on ISO standard best practices

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7933]
**Describe the problem you would like to solve**
Ensure new DOI suffix generation is following all of the established best practices according to the DOI ISO standard.

**Describe the solution you'd like**
Update DOI generator to factor these recommendations into account.

**Additional information**
N/A

**Comment by ewhanson** [comment]
Hey @NateWr, could you have a quick look at this? It's a pretty small change to remove the hyphen in the DOI suffix generator to bring it inline with the ISO standards recommendations for suffixes. Thanks!

PRs:
- `pkp-lib`: #8382
- `ojs`: pkp/ojs#3592
- `omp`: pkp/omp#1233
- `ops`: pkp/ops#380

**Comment by NateWr** [comment]
Thanks @ewhanson. I've merged that change in.

cc @bozana just FYI on the new default DOI patterns. @ewhanson got a hold of the ISO standards which recommend against using hyphens. He's gone from `abcd-efgh` to `abcdefgh`.
