### ISSUE TITLE
Stop using deprecated fgetss() function

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7935]
The HTML indexer currently uses the deprecated fgetss() function. See e.g.:
https://forum.pkp.sfu.ca/t/php-fatal-error-uncaught-error-call-to-undefined-function-fgetss/73277

Replace this function with a non-deprecated alternative.

**Comment by asmecher** [comment]
OJS 3.3.0-x (with x<11) users can resolve this by applying [this change](https://github.com/pkp/pkp-lib/commit/698085ed0f4b503448293b32ecd97cd491d6f2d6) in the `lib/pkp` subdirectory.

**Comment by asmecher** [comment]
@jnugent, tagging you because I think you were running into 4096-character UTF8 issues. This should resolve them in the bargain. I don't know if that ever got filed or put into a PR?

**Comment by jnugent** [comment]
@asmecher are you thinking of this? https://github.com/pkp/pkp-lib/issues/7776

**Comment by asmecher** [comment]
No, thinking on it further I'm pretty sure it was PDF file extraction, which also has a 4096-character block size (https://github.com/pkp/pkp-lib/blob/59bea3dbb2ac0577bac36bb79c4e3676d9d9d531/classes/search/SearchFileParser.inc.php#L103).

**Comment by jnugent** [comment]
Ah, the problem we were having was that the PKPString preg_match calls were expecting a UTF8 string, and what was coming out of the calls to the pdftotext commands was not, so the split was occurring on an empty string and no keywords were extracted.  I think there was a PR for that, but I don't have the link handy.
