### ISSUE TITLE
Deleting dependent file cause submission activity log view to break .

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#7937]
**Describe the bug**
If a submission at any stage (currently only in `Submissions --> Workflow --> Production` stage) has the dependent file feature and removing/deleting any parent file at any time cause the `Activity Log` view to break/not load.

**To Reproduce**
1. Login as an Author and create a new Submission.
2. Login as Editor/Journal Manager and complete the Workflow stages such as `Review`, `Copy Editing` and reach to the `Production` stage .
3. Add/Upload files for submission in the `Production` stage and make sure have the upload files have dependent file association . To achieve that for example, from `Upload file` modal, select `Article` from the dropdown menu and add a `html` file . Proceed next and add dependent file . 
4. Now delete the parent file . Say the main file was `Test.html` and dependent file was `Image.png` . form the files list in the `Production` stage , delete the `Test.html` file .
5. Try to view the `Activity Log` and notice that it's not loading the activity entries . 

**What application are you using?**
 OJS `main` branch.

**Additional information**
Error Trace : 
```
Uncaught TypeError: PKP\submissionFile\Repository::getWorkflowStageId(): Argument #1 ($submissionFile) must be of type PKP\submissionFile\SubmissionFile, null given, called in /INSTALLATION_PATH/lib/pkp/classes/submissionFile/Repository.inc.php
```

because of defined in `PKP\submissionFile\Repository::getWorkflowStageId()` as 
```php
    /**
     * Get the workflow stage for a submission file
     */
    public function getWorkflowStageId(SubmissionFile $submissionFile): ?int
    {
        .....

        if (
            $fileStage === SubmissionFile::SUBMISSION_FILE_DEPENDENT
        ) {
            $parentFile = $this->get($submissionFile->getData('assocId'));

            return $this->getWorkflowStageId($parentFile);
        }
    } 
```

**Comment by touhidurabir** [comment]
@asmecher please review

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7937 Deleting dependent file cause submission activity log view to break](https://github.com/pkp/pkp-lib/pull/7938)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7937 Submodule Update ##touhidurabir/i7937_fix_main##](https://github.com/pkp/ojs/pull/3406)

also should I forward port these to `OPS` and `OMP` ?

**Comment by asmecher** [comment]
Thanks, @touhidurabir, I've merged those two. I don't mind if the OMP and OPS submodule updates fall a little behind; this is a trivial fix.
