### ISSUE TITLE
XML Writer could support Comments

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#794]
XML comments could be useful sometimes, say for example if you were working on EZID and needed [a good way to reuse Crossref's code and structure](https://github.com/chasehd/EzidDOI/commit/6088bd0fae8fd86fa9a82d01401c2df3fd320a9b#commitcomment-13598683) with minimum disruption.

**Comment by ctgraham** [comment]
PR is https://github.com/pkp/pkp-lib/pull/795

**Comment by ctgraham** [comment]
@asmecher, the inheritance here is corrected.  Since the new functionality won't really be called from anything in core, perhaps it could be moved up to 2.4.7?

**Comment by asmecher** [comment]
Moved up to 2.4.7 and merged. I'll also cherry-pick to master, though I hope the custom XML stuff won't last long there. Thanks, @ctgraham.
