### ISSUE TITLE
Use or remove scheduled_tasks flag in config.inc.php

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#7940]
**Describe the bug**
File config.inc.php has a [`scheduled_tasks` setting](https://github.com/pkp/ojs/blob/216f47a3dd03b26e3635ca3bfff0f65f825630e1/config.TEMPLATE.inc.php#L48-L51) in the `general` section with the description:
> Set this to On if you have set up the scheduled tasks script to execute periodically

This is used three times in the current codebase, where it disables reminder options if not "On":
https://github.com/pkp/ojs/blob/216f47a3dd03b26e3635ca3bfff0f65f825630e1/classes/subscription/form/SubscriptionPolicyForm.inc.php#L106
and
https://github.com/pkp/pkp-lib/blob/e87baf6bc525cbc6f2e02277b64656f811bc498c/classes/components/forms/context/PKPReviewSetupForm.inc.php#L86-L92
and
https://github.com/pkp/ojs/blob/216f47a3dd03b26e3635ca3bfff0f65f825630e1/pages/payments/PaymentsHandler.inc.php#L139-L141

This isn't accurate because Acron could be running tasks and Acron is not dependent on the `scheduled_tasks` setting.

Either Acron should be dependent on the `scheduled_tasks` setting, or this setting should be removed from config.inc.php in favor of some other test/indication of whether scheduled tasks are actually enabled.  This may be in scope to be addressed in https://github.com/pkp/pkp-lib/issues/4622 .

**To Reproduce**
1. Enable the Acron plugin
2. Set `scheduled_tasks` in config.inc.php to "Off"
3. Attempt to change reminder options for Subscription Policies, Reviews, or Payments.
4a. Changes are disallowed.
4b. Acron runs attempt DOI registrations and Usage Statistics loads and send Review Reminders, among other things.

**What application are you using?**
 OJS version 3.4 (main / https://github.com/pkp/ojs/commit/216f47a3dd03b26e3635ca3bfff0f65f825630e1)

**Additional information**

**Comment by jonasraoni** [comment]
I ended up here after watching the code at https://github.com/pkp/pln, which has a similar check =]

I consider the work on #4622 supersedes the `scheduled tasks` and the Acron plugin, therefore I think this setting can be removed, as it ended up being replaced by `disable_jobs_run_at_shutdown`.

**Comment by jonasraoni** [comment]
Before removing this setting, we should probably add an alert (email or reminder at the administrative interface):

"There are pending scheduled tasks to run, and they haven't been executed for N days. Ensure you've configured your system to run tasks properly at https://docs.pkp.sfu.ca/admin-guide/en/configure#scheduled-tasks"

**Comment by jonasraoni** [comment]
Closing. The implementation will be done at #9678.
