### ISSUE TITLE
CORS Redirect is not allowed for a preflight request

### ISSUE THREAD

**Issue by sourcedump** [pkp/pkp-lib#7941]
**Describe the bug**
I'm using OJS3.3 installation with multiple journals, each with a different domain name. We can describe the actual configuration as follow:

- Index page with the url ‘https://ojs.journals.com/’
- journal umber 1 with url ‘https://www.myjournal1.com/’
- journal umber 2 with url ‘https://www.myjournal2.com/’
- etc …

config.inc.php configuration:
```
    base_url = “https://ojs.journals.com/”
    base_url[index] = “https://ojs.journals.com/”
    base_url[myjournal1] = “https://www.myjournal1.com/”
    base_url[myjournal2] = “https://www.myjournal2.com/”
    etc ...
    restful_urls = On
```
When I try to make public the myjournal1 from the ‘Hosted Journals’ page:

- https://ojs.journals.com/admin/contexts

I have the following CORS error:
```
Access to XMLHttpRequest at 'https://www.myjournal1.com/api/v1/contexts/1' from origin 'https://ojs.journals.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```
because, despite being on domain ‘http://ojs.journals.com/’ the request is made to domain ‘http://www.myjournal1.com/’.

My question is: shouldn’t this operation be performed on ‘https://ojs.journals.com/api/v1/contexts/1’
instead of link ‘https://www.myjournal1.com/api/v1/contexts/1’?

Thanks.

**To Reproduce**
1. Configure a multi-domain OJS 3.3 installation
2. Login as administrator and enter the backend
3. Click on 'Administration' on the left menu
4. Click on 'Hosted Journals'
5. Click on 'Edit' on a journal
6. Flag the 'Enable this journal to appear publicly on the site' checkbox
7. Click the 'Save' button

**What application are you using?**
OJS 3.3.0.8 (October 12, 2021 - 09:11 AM)

**Comment by NateWr** [comment]
Hi @sourcedump. I would encourage you to post in our [support forum](https://forum.pkp.sfu.ca/c/questions/5). You will find more help there than we are able to provide here.

**Comment by sourcedump** [comment]
Hello @NateWr ,
ok, no problem, but it could be possible that it is a bug of some sort, because it is the OJS3 code that generates the link to a different domain.

**Comment by NateWr** [comment]
If a bug is confirmed we can bring it over. But many instances run a multi-domain journal without problems. So the most likely cause of the problem is a configuration error. The support forum is the best place for that.
