### ISSUE TITLE
Typo in getUsersWithNoRole query

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7943]
**Describe the bug**
The `getUsersWithNoRole()` query is missing a space in its construction and results in `...IS NULLORDER...` instead of `...IS NULL ORDER...`

**To Reproduce**
1. Invoke the `getUsersWithNoRole()` method in `UserDAO`.
2. See SQL error

**What application are you using?**
 pkp-lib stable-3_3_0 branch

**Additional information**
N/A

**Comment by ewhanson** [comment]
Hey @asmecher, could you have a look at this? There wasn't a space at the end of the concatenated string, so the following query elements were added directly against the end of the concatenated string (e.g. `NULLORDER` instead of `NULL ORDER`). I don't think this query is used anywhere in the code, but it came up in a systems team tool. Also, for what it's worth, this was failing silently in MySQL but throwing an error in MariaDB. Thanks!

PR:

- #7944

**Comment by asmecher** [comment]
Merged, thanks!
