### ISSUE TITLE
Can not add new item under checklist

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#7949]
**Describe the bug**
When try to add a new item under the `Settings --> Workflow --> Submission --> Checklist`, it throws `Internal 500 exception` and cause not able to add any new item under the checklist items . 

**To Reproduce**
1. Login as Admin/Manager.
2. Go to `Settings --> Workflow `.
3. Under `Submission --> Checklist`, try to add a new item.
4. See that it's not presenting a proper modal to add new item which points to an internal exception.

**What application are you using?**
 `OJS`, `OMP` and `OPS` on `main` branch .

**Additional information**
This is related to `main` branch on `PHP 8.0+` as due to newly imposed restrictions such as https://wiki.php.net/rfc/lsp_errors by PHP 8 .

**Comment by touhidurabir** [comment]
@asmecher please review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7949 Can not add new item under checklist](https://github.com/pkp/pkp-lib/pull/7950)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7949 Submodule Update ##touhidurabir/i7949_fix_main## ](https://github.com/pkp/ojs/pull/3410)

**Comment by asmecher** [comment]
Merged the pkp-lib change; no need for OPS and OMP PRs. Thanks!
