### ISSUE TITLE
Can not add options for optional type fields in the review form

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#7954]
**Describe the bug**
For a `Review Form`, when attempting to add an form item that has options associated with it such `Checkbox`, `Radio Button` or `Dropdown`, it  failed and no item under the `Response Options` section . 

**To Reproduce**
1. Login as `Admin\Editor\Journal Manager`.
2. Go to `Settings --> Workflow --> Review --> Review Form`.
3. Create a new Review Form.
4. Now edit the newly created form and go to `Form Items --> Create New Item`
5. From the `Choose Item type` dropdown option, select option `Checkboxes`, `Radio Buttons` or `Drop-down box`.
6. Now Try adding an option item by clicking on the `Add Item` under `Response Options`.
7. See that no new field is getting added under `Response Options` which indicates an `Internal Exception`.

**What application are you using?**
 OJS `main` branch .

**Additional information**
Exception trace 
```
PHP Fatal error:  Uncaught Error: Call to undefined method Locale::getPrimaryLocale() in /INSTALLATION_PATH/cache/t_compile/e01beab3fddc96572d9ca0f786cbed05161fec87^13079afb8321a2a0363ebe7d6bab5378471300e1_0.app.controllersgridgridCellCo.php:34
```
this is due to calling `Locale::getPrimaryLocale()` method in the `controllers/grid/gridCellContents.tpl` without the full namespace path .

**Comment by touhidurabir** [comment]
@asmecher please review the RRs at 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7954 Can add options for optional type fields in the review form](https://github.com/pkp/pkp-lib/pull/7955)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7954 Submodule Update ##touhidurabir/i7954_fix_main##](https://github.com/pkp/ojs/pull/3411)

As this is a very trivial fix, I am not sure if I need to forward it to `OPS` and `OMP` but confirm me .

**Comment by asmecher** [comment]
Merged, thanks! I don't mind if we skip submodule updates for OMP and OPS.
