### ISSUE TITLE
Issue publishing feature is not working properly

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#7957]
**Describe the bug**
When publishing a new issue, it's not behaving properly . Issue is getting published but if mail notification is set , it's not sending any mail notifications. Also at the same time issue is not getting moved form `Future Issues` to `Back Issues` and the confirmation model is not getting away which make it looks like the issue publishing has failed . 

**To Reproduce**
1. Login as Admin\Editor\Journal Manager.
2. Create a new issue under `Future Issue`.
3. Now try to publish the issue and see that no mail notifications and confirmation modal is hanging around.

**What application are you using?**
 OJS `main` branch.

**Additional information**
Exception Trace
```
Uncaught Error: Class "APP\controllers\grid\issues\DAORegistry" not found in /INSTALLATION_PATH/classes/controllers/grid/issues/IssueGridHandler.inc.php:606
```

**Comment by touhidurabir** [comment]
@asmecher please review 

[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7957 Issue publishing feature is not working properly](https://github.com/pkp/ojs/pull/3412)

**Comment by asmecher** [comment]
Merged, thanks!
