### ISSUE TITLE
DOIExportDom fails to return cached objects

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#798]
In response to [bugzilla 8494](http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8494), I think [our fix](https://github.com/pkp/ojs/commit/e5cc74d01e058b9f388544ee2d3ee576ad9478f0) breaks caching for DOIExportDom.

I think we want to retain the return of `$cache->get()`, but would like another set of eyes. (perhaps @bozana as the contributor?)
https://github.com/pkp/ojs/commit/e5cc74d01e058b9f388544ee2d3ee576ad9478f0#diff-d0e4e0b567c399b9d428b5d685c074d3L319

**Comment by bozana** [comment]
@ctgraham, I will take a look... :-)

**Comment by bozana** [comment]
@ctgraham, I took a look and yes, you are right :-)

**Comment by bozana** [comment]
Hmm... I've just tried to test it and in my case the cache seems to be never used i.e. it always goes into the if statement...

**Comment by ctgraham** [comment]
In the default install it may never get called twice.  I was testing a change to the EZID plugin where I called retrievePublicationObjects twice:
https://github.com/ulsdevteam/EzidDOI/blob/remove-unneeded-code/classes/EzidExportDom.inc.php#L52
https://github.com/ulsdevteam/EzidDOI/blob/remove-unneeded-code/classes/EzidExportDom.inc.php#L81
The second call triggers the cache.

**Comment by bozana** [comment]
Aaaaaaaaaaa... :-))) Thanks @ctgraham !!! :-)))

**Comment by asmecher** [comment]
I've merged in https://github.com/pkp/ojs/issues/630 -- is that all that needs doing here?

**Comment by ctgraham** [comment]
It is unless you want to evaluate master for the original concern from [8494](http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8494).  I think master will cache correctly, but may suffer from the original unset array variable.

**Comment by asmecher** [comment]
Thanks, @ctgraham. @bozana, would you mind taking a peek at master for that?

**Comment by bozana** [comment]
@asmecher I made a pull request for master branch fixing only this issue. The code in master however seems to be older -- it seems that lots of changes were not included there i.e. it needs more thoroughly attention ...

**Comment by asmecher** [comment]
You're right, @bozana -- I think it would be better to grab the current `ojs-dev-2_4` plugins and replace the code currently in `master` with them, then rewrite them for the `master` branch coding style/standards.
