### ISSUE TITLE
Show REVIEW_REQUEST_SUBSEQUENT email only if reviewer is assigned a second time

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7989]
**Describe the problem you would like to solve**
During reviewer assignment, an editor has an opportunity to compose an email from the `REVIEW_REQUEST` or `REVIEW_REQUEST_SUBSEQUENT` email templates. After refactoring, they are associated with `ReviewRequest`  and `ReviewRequestSubsequent` mailables. 

The current logic is that the `REVIEW_REQUEST` template is shown during first review round and the latter in subsequent rounds. This doesn't correspond to the templates' content after refactoring, which implies that `*_SUBSEQUENT` should be used if the reviewer was already assigned before to this submission.

**Describe the solution you'd like**
Change the current logic to show the `*_SUBSEQUENT` only when the reviewer was already assigned to the submission in previous rounds and completed the assignment. See: https://github.com/pkp/pkp-lib/blob/760200580ce986a1ed9c916899022d8dd9b803ff/controllers/grid/users/reviewer/form/ReviewerForm.inc.php#L482.

**Who is asking for this feature?**
Me

**Additional information**
It could be tricky because during ReviewerForm initialization reviewer is unknown and is determined on the basis of the user selection after initialization.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8316
tests: https://github.com/pkp/ojs/pull/3566

**Comment by NateWr** [comment]
Excellent! No comments. Merged to `main`. :tada:
