### ISSUE TITLE
Warning when accessing the properties of a schema's field

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7995]
**Describe the bug**
Some parts of the code are attempting to access the properties of a schema field, but when it doesn't have any, it generates some warnings:
```
PHP Warning:  Undefined property: stdClass::$properties in /home/travis/build/pkp/ops/lib/pkp/classes/services/PKPSchemaService.inc.php on line 380
```

The object comes from a `json_decode()` over the JSON schema, and some object fields in the schema (`"type": "object"`) are (intentionally) missing a definition of the properties.

**To Reproduce**
Run the Travis tests against the `main` branch.

**PRs**
- https://github.com/pkp/pkp-lib/pull/8000
- https://github.com/pkp/ops/pull/296

**What application are you using?**
Main `branch` of OJS, OMP and OPS.

**Comment by jonasraoni** [comment]
@asmecher another small PR to review:
- https://github.com/pkp/pkp-lib/pull/8000

**Comment by asmecher** [comment]
I haven't seen these warnings in a while. @jonasraoni and @NateWr, have either of you?

**Comment by NateWr** [comment]
Each warning message indicates an error in the entity's schema file (eg - `submission.json`). So we should leave the error in and fix the schema files as they arise. 

I'd suggest closing this issue and filing a separate issue when we encounter a missing property in a schema file.

**Comment by jonasraoni** [comment]
For this issue, if it's not tough, I think it might be worth to create a schema to validate our schemas, just to ensure it's well defined and [catch minor things](https://github.com/pkp/pkp-lib/commit/a7b13f07edf6439d457e6216d6b50cdddbdb8d1d) while building, or in the worst case, to throw an exception where I've added the null coalescing.

**Comment by asmecher** [comment]
Not a bad idea, but the current warning should twig the developer that something's wrong too. I'll close this for now and we can file and re-open on a specific case.
