### ISSUE TITLE
[OMP] Proof files grid fails to load when files are selected from previous stages

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#800]
I was able to reproduce this issue with the fresh test database. Rather than explain the steps I thought it would be easiest just to show how to reproduce this:

![omp-proof-files-issue](https://cloud.githubusercontent.com/assets/2306629/10342412/db035d6e-6d10-11e5-8fa5-86f878b7f42f.gif)

1. The book that's being used to reproduce this has been published. It's the Bricks to Brains one.

2. The grid fails to load because of a JavaScript syntax error. This happens because the More Information link action, which appears in the grid row for the file, is missing a title (see under actionRequestOptions.

```

		$(function() {
		$('#component-proofFiles-1-row-99-moreInformation-button-56153a5b21e92').pkpHandler(
			'$.pkp.controllers.linkAction.LinkActionHandler',
				
{
		staticId: "component-proofFiles-1-row-99-moreInformation-button",
		actionRequest: "$.pkp.classes.linkAction.ModalRequest",
	actionRequestOptions: {
					"title": ,
					"titleIcon": "modal_information",
					"canClose": "1",
					"width": "710",
					"closeButtonText": "Close Panel",
					"modalHandler": "$.pkp.controllers.modal.AjaxModalHandler",
					"url": "http:\/\/192.168.0.8\/omp\/index.php\/publicknowledge\/$$$call$$$\/information-center\/file-information-center\/view-information-center?fileId=99&revision=1&submissionId=15&stageId=5",
			}
}			);
	});
```

This problem does not occur for files that are uploaded directly in this grid.

**Comment by asmecher** [comment]
Nate, this appears to be caused by database encoding problems:
http://stackoverflow.com/questions/19361282/why-would-json-encode-returns-an-empty-string
I used the same dump you have and my charsets are OK; can you try re-creating your DB, making sure to specify the character set:

    CREATE DATABASE my_db DEFAULT CHARACTER SET utf8;

...and loading the dump again? Also, ensure that you config.inc.php contains...

    client_charset = utf-8
    connection_charset = utf8
    database_charset = utf8
    charset_normalization = Off

**Comment by NateWr** [comment]
I can no longer reproduce this.
