### ISSUE TITLE
Prevent cached CSS from being used by forcing the loading of updated CSS in a journal theme after styles have changed in a theme by adding the theme's release and date into the compiled stylesheet url

### ISSUE THREAD

**Issue by eirikhanssen** [pkp/pkp-lib#8018]
@asmecher @NateWr 
This is a bug report/feature request.

**Software: OJS: 3.3.0-11**
This issue is a little related to the issue as reported in:  #6795, but concerns changes made in a journal theme's styles.

The case here is that I have separate themes for each journal on our OJS-platforml. When I make changes in the CSS/LESS of the journal's theme, then it is not reflected immediately because the old CSS is cached by the browser which does not know that the CSS is updated. I have to tell the browser to force reload by hitting SHIFT+Reload.

I am not expecting any of our thousands of users to do this obviously. So there is a need to force the browsers to update the CSS when I have made changes in a journal's theme.

This can be done by changing the stylesheet URL each time a theme has been changed by including a theme's release and date in the stylesheet url.

The theme's CSS is now included in the `<head>` section webpage in the following markup:
`<link rel="stylesheet" href="https://journals.oslomet.no/index.php/journalpath/$$$call$$$/page/page/css?name=stylesheet" type="text/css">`

I would like to suggest adding the theme's release and date in the url. When updating the theme, if I change either of the theme's release  and/or date in the file **plugins/themes/themename/version.xml**, after clearing the template cache on the platform, all visiting browsers will fetch the updated CSS file since they will see that the CSS-url has been changed.

Suggestion for improvement, adding **release** and **date** from a theme's **version.xml** to the CSS-link:
`<link rel="stylesheet" href="https://journals.oslomet.no/index.php/journalpath/$$$call$$$/page/page/css?name=stylesheet&release=3.3.0.11&date=2022-06-11" type="text/css">`

I also suggest making this a little more robust by removing any unexpected characters that might be present in the release or date tags in the theme's version.xml before inserting the text into the CSS-link (characters that are not digits,hyphen or period).

Sample **plugins/themes/themename/version.xml**:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE version SYSTEM "../../../lib/pkp/dtd/pluginVersion.dtd">

<!--
  * plugins/themes/formakademisk/version.xml
  *
  * Copyright (c) 2014-2020 Simon Fraser University
  * Copyright (c) 2003-2020 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Plugin version information.
  -->
<version>
        <application>themename</application>
        <type>plugins.themes</type>
        <release>3.3.0.11</release>
        <date>2022-06-21</date>
        <lazy-load>1</lazy-load>
        <class>ThemeNameThemePlugin</class>
</version>
```

Best regards,
Eirik Hanssen
OsloMet University Library

**Comment by NateWr** [comment]
Thanks @eirikhanssen. Can you please update your post to use the feature request template? This helps us manage our long issue list:

```
**Describe the problem you would like to solve**
Example: Our editors need a way to [...]

**Describe the solution you'd like**
Tell us how you would like this solution to be solved.

**Who is asking for this feature?**
Tell us what kind of users are requesting this feature. Example: Journal Editors, Journal Administrators, Technical Support, Authors, Reviewers, etc.

**Additional information**
Add any other information or screenshots about the feature request here.
```

Finally, we already use the application version in asset URLs. For example:

```
http://localhost:8000/lib/pkp/styles/fontawesome/fontawesome.css?v=3.3.0.0
```

We would probably be most likely to use the same approach for themes, rather than adopting a different syntax.
