### ISSUE TITLE
Context name can not be localized correctly in a job

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8025]
**Describe the bug**
When handling a job, the request locale is not usually appropriate for messages used in the job. We must change the current locale while processing the job. However, this does not work because the locale may already be set in a `DataObject` like the context.

A call to `$context->getLocalizedName()` will return the context name in the request's locale, not the current locale.

**To Reproduce**
You can use the following code anywhere in the application where the context has been loaded to reproduce this bug (adjust the locales as needed);

```php
echo $context->getLocalizedName();
Locale::setLocale('fr_CA');
echo $context->getLocalizedName();
die;
```

In an example with `en_US` as primary locale and `fr_CA` as secondary locale, I would expect to see:

```
Journal of Public KnowledgeJournal de la connaissance du public
```

Instead, I see:

```
Journal of Public KnowledgeJournal of Public Knowledge
```

**What application are you using?**
`main` branch, 3.4 pre-release

**Additional information**
When calling `getLocalizedData()` on a `DataObject`, it calls `DataObject::_getLocalePrecedence()` to determine the correct locale to use. However, this function is static, so once it is called on a data object it will never be updated. Maybe this can be moved to the Locale facade and cleared when `Locale::setLocale()` is called?

Also, the `$preferredLocale` argument in `DataObject::getLocalizedData()` is not used.

This is causing a bug in the context name in a reminder email at https://github.com/pkp/pkp-lib/issues/6126.

**PRs**

#### Stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9211
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3997 [TEST ONLY]

### main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9259
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4027 [TEST ONLY]

**Comment by asmecher** [comment]
> Maybe this can be moved to the `Locale` facade and cleared when `Locale::setLocale()` is called?

I agree!

> Also, the `$preferredLocale` argument in `DataObject::getLocalizedData()` is not used.

True, and it can be cleaned up -- but watch out, it is used in some subclass implementations that override the `getLocalizedData`, e.g. `Chapter` in OMP and PKPPublication in pkp-lib.

@touhidurabir, if it helps clarify some of the code in the `PKPRouter` class that's currently quite messy: We used to support potentially several "levels" of context, rather than just Press/Journal/Server as OMP/OJS/OPS currently require. However, all of our current applications only require one level of context. There is still some complexity left over from the previous support, and it can be removed. See for example: `PKPRouter::getContext`

**Comment by touhidurabir** [comment]
> When calling `getLocalizedData()` on a `DataObject`, it calls `DataObject::_getLocalePrecedence()` to determine the correct locale to use. However, this function is static, so once it is called on a data object it will never be updated. Maybe this can be moved to the Locale facade and cleared when `Locale::setLocale()` is called?

Above idea from Nate seems like a easier solution to implement and maintain . 

@asmecher PRs to review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9207
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3995 [TEST ONLY]

**Comment by asmecher** [comment]
Merged the `stable-3_4_0` and `main` PRs! Thanks, @touhidurabir and @bozana.

**Comment by asmecher** [comment]
Merged the two PRs for OMP; those should fix the test problem!
