### ISSUE TITLE
Pages locale error import xml

### ISSUE THREAD

**Issue by Virpac** [pkp/pkp-lib#8033]
Hello, how can I specify the locale attribute on the pages element? OJS version 3.3.0.8

example:
<.pages locale=en_US>1-3<./pages>
<.pages locale=ru_RU>1-4<./pages>

Element ‘{http://pkp.sfu.ca/}pages’, attribute ‘locale’: The attribute ‘locale’ is not allowed.

**Comment by jonasraoni** [comment]
Hi @Virpac,

That's not possible, only one `<pages>` tag is allowed and it doesn't have attributes, you can see the definition here: https://github.com/pkp/ojs/blob/e8b8c0292b133d564a9ddd9f41905ea5d124e90c/plugins/importexport/native/native.xsd#L50

If you're thinking the software is missing a feature, the forum is the best place for suggesting things: https://forum.pkp.sfu.ca/c/questions/feature-requests/8.
