### ISSUE TITLE
initData hooks not fired in SeriesForm and CategoryForm

### ISSUE THREAD

**Issue by t-mayer** [pkp/pkp-lib#8035]
**Describe the problem you would like to solve**
Currently, a new field can be added to SeriesForm.inc.php by overwriting the template. The DB-saved values however are not initialized upon opening the form due to missing parent::initdata(). This is also missing in CategoryForm.inc.php I am not sure how else to initialize the values that are saved in the DB so it would be convenient to be able to use the initdata-hook....
Currently using OMP 3.3.0.7

***Describe the solution you'd like***
Add  
```
return parent::initdata()  
```
to the function initData() in SeriesForm.inc.php and CategoryForm.inc.php

**Comment by NateWr** [comment]
Confirmed. Thanks for the report @t-mayer. The following PRs restore the parent method calls to themes forms.

PRs:
https://github.com/pkp/pkp-lib/pull/8036
https://github.com/pkp/omp/pull/1147

In the meantime, you might be able to use the hooks in the `fetch()` method of these forms to accomplish what you need.

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and ported to the `main` branch.
