### ISSUE TITLE
Crossref translations contain untranslated English and unused keys

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#804]
The Crossref importexport plugin's pl_PL, vi_VN, and zh_TW are untranslated.  The ar_IQ locale contains an unused common.xml file.  Locales ca_ES, eu_ES, fa_IR, hr_HR, id_ID, it_IT, ja_JP, no_NO, ro_RO, sr_SR, sv_SE, and uk_UA are outdated and contain unused keys.

**Comment by mtub** [comment]
Checked and merged. Sorry for the delay.
