### ISSUE TITLE
Update unit tests

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8040]
**Describe the bug**
A [broken locale test](https://github.com/pkp/pkp-lib/blob/0fbea2d886892d79f2b8427d85669145cc1ac8e6/tests/classes/i18n/LocaleTest.php#L63) was blocking the issue https://github.com/pkp/pkp-lib/issues/7871 from being merged. The test has been skipped temporarily, and this issue was created mainly to handle it.

As part of this issue, a small review will be undertaken at the unit tests:
- [x] Drop outdated "mock environments", it can be done through a less tortuous way
- [x] Address mocked objects that are leaking into other tests from:
  - [x] Registry
  - [x] DAORegistry
  - [x] Laravel's `app()`
- [x] Add code coverage summary to the end of test
- [x] Attempt to fix other skipped tests
- [x] Add namespaces

**PRs**
- https://github.com/pkp/pkp-lib/pull/8057
- https://github.com/pkp/ojs/pull/3445
- https://github.com/pkp/ops/pull/307
- https://github.com/pkp/omp/pull/1155
- https://github.com/pkp/crossref-ojs/pull/13
- https://github.com/pkp/crossref-ops/pull/13

**What application are you using?**
*/main

**Comment by jonasraoni** [comment]
@asmecher PRs
- https://github.com/pkp/ojs/pull/3445
- https://github.com/pkp/pkp-lib/pull/8057

**Comment by asmecher** [comment]
So this is one of the few places where I will welcome scope creep :) The PHPUnit tests badly need review/modernization/cleanup and this looks like a very good start. I've added a couple of comments; please go ahead and port to OMP and OPS!

**Comment by jonasraoni** [comment]
Reminder to check why the `PKPComponentRouterTest::testRoute()` is failing locally.

**Comment by jonasraoni** [comment]
@asmecher forgot to warn that I've already ported the updates to OPS/OMP.

**Comment by jonasraoni** [comment]
I'll wait for your answer here: https://github.com/pkp/ops/pull/307#pullrequestreview-1060447872, then I can update/merge 😁
