### ISSUE TITLE
Error when adding a Note in the "Activity Log & Notes"

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8041]
**Describe the bug**
When trying to add a note in the submission's "Activity Log & Notes" the note is added but the process fails. An error 500 is generated

```
PHP Fatal error:  Uncaught Error: Non-static method PKPNotificationOperationManager::createTrivialNotification() cannot be called statically in ojs-3-dev-3.3.0\lib\pkp\controllers\informationCenter\SubmissionInformationCenterHandler.inc.php:106
```

**To Reproduce**
1. Go to Dashboard -> Submissions
2. Click on any submission
3. Click on "Activity Log" button
4. Click on the "Notes" tab
5. Try to add a Note
6. See error

**What application are you using?**
 OJS 3.3.0 (stable branch) (main branch also)

**Additional information**
There are places in code where the `createTrivialNotification` function is called as a static function (like `PKPNotificationOperationManager::createTrivialNotification()`) and not like `$notificationMgr->createTrivialNotification`. Those code lines should be fixed.

**PHP version**
PHP 8.0

**Comment by NateWr** [comment]
Thanks @defstat. It looks good, but I notice there is a conflict with the PR to OJS's `main` branch, so the tests aren't running. Can you get the tests passing there? Then I'm happy to merge.

**Comment by NateWr** [comment]
Thanks @defstat! Merged to `stable-3_3_0` and `main`.
