### ISSUE TITLE
Send email to Reviewer fails

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8042]
**Describe the bug**
At the submission workflow, at review round, under a reviewer actions, when trying to perform the "Email Reviewer" actions, the action fails with HTTP error 500.

```
PHP Fatal error:  Declaration of EmailReviewerForm::execute($submission) must be compatible with Form::execute(...$functionArgs) in ojs-3-dev-3.3.0\lib\pkp\controllers\grid\users\reviewer\form\EmailReviewerForm.inc.php on line 72
```

**To Reproduce**
1. Go to Dashboard -> Submissions
2. Click on any submission
3. In Reviewers grid, open actions for a Reviewer
4. Click on the "Email Reviewer" action
5. See error

**What application are you using?**
 OJS 3.3.0 (stable branch)

**PHP version**
PHP 8.0

**Comment by NateWr** [comment]
Thanks @defstat. Can you test this fix?

PR:
https://github.com/pkp/pkp-lib/pull/8045

Tests:
https://github.com/pkp/ojs/pull/3439
