### ISSUE TITLE
Allow queued jobs to be processed by workers

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8044]
**Describe the problem you would like to solve**
The new jobs queue works by processing jobs during the shutdown function. This prevents a job from hanging a request by a user. However, in high-volume scenarios it will be hard to manage server resources if high-intensity jobs are processed on the same thread as regular requests.

An example would be when publishing an issue: this usually kicks off a bunch of search indexing processes that will be jobs from 3.4. Taking these off the main thread could prevent resource spikes that lead to slow load times for users.

**Describe the solution you'd like**
Laravel's jobs system includes tools to process jobs through [workers on the server](https://laravel.com/docs/9.x/queues#running-the-queue-worker). We should investigate how this works and make sure that our jobs queue is compatible with their tools. Then we should document how sys admins can run and monitor these workers.

**Who is asking for this feature?**
This could be valuable for our largest hosts, such as PS and Ubiquity. 

**Additional information**
cc @fradeve we'd love your assistance with testing this when you have the time.

**Comment by touhidurabir** [comment]
Do we want to have the options to run multiple workers or force it just one single worker ? Also should we provide a cool down time after a specific numbers of job executed, for example like each 100 jobs , a 5/10 seconds cool down time and that configuration can go into the `config` file ?

**Comment by asmecher** [comment]
For the moment, let's keep it relatively simple. I think just a single worker is enough to handle the load on queues for the foreseeable future. I have no preference for cool-down defaults etc; I'll defer to your experience, knowing that the demands on the queuing system are currently light but are likely to grow!

**Comment by NateWr** [comment]
Can you say a little bit more about why we have these options? It was my understanding that the Laravel system doesn't care how many workers you have running against it and that we shouldn't need to worry about things like cooldowns.

If we can get away with leaving these things to Laravel and not having any options, configuration or controlling code ourselves, we should try to do that.

**Comment by touhidurabir** [comment]
The cool down time is a good configuration when multiple workers are running, but for a single worker, it's does not have that much impact as each worker process jobs one by one . 

Considering an environment that has multiple workers running and also have priority based queues set with dedicated workers , it can have massive impact when both the normal queues and priority queues swarmed with jobs. By providing cool down with different worker options settings `Illuminate\Queue\WorkerOptions` for each of worker, we can reduce the chance to queue crashing down. So when a worker processing a long running jobs that is memory intensive while other workers also running more jobs, we may just run out of memory . By providing a cool down time for dedicated worker, we can reduce that chance . 

But if we are going with only one single worker, we can ignore that for now . In that case, if we decide to set options/methods like `backOff` or just set `app('queue.worker')->shouldQuit  = 1` in job classes that are memory intensive so that worker restart after finish such jobs.

**Comment by NateWr** [comment]
Ok that sounds good. My main concern is to add as little code on top of Laravel as possible. :+1:

**Comment by touhidurabir** [comment]
The PRs
 
[pkp#8133](https://github.com/pkp/pkp-lib/pull/8133) 
[ojs#3476](https://github.com/pkp/ojs/pull/3476)

for the issue pkp/pkp-lib#7105 now have the functionality to handle jobs via worker daemon . 

After this get merged with main, to run a worker daemon, run command 
```bash
php lib/pkp/tools/jobs.php work
```
use the flag `--help` with the `work` command to view all available options that can be passed as it's support most of laravel `queue:work` command options . 

### To set up the worker daemon monitor via `Supervisor`

install it in linux(for example ubuntu)  system as 

```bash
sudo apt-get install supervisor
```

set up a `conf` file(for example `ojs-queue-monitor.conf`) with following content

```
[program:ojs-queue-monitor]
process_name=%(program_name)s
command=/PHP_PATH/php /OJS_INSTALLATION_PATH/lib/pkp/tools/jobs.php work
directory=/OJS_INSTALLATION_PATH
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/OJS_INSTALLATION_PATH/supervisor-database.log
```

usually path of `conf` files are at `/etc/supervisor/conf.d`. Make sure to update few setting like `command`, `directory`, `program` `stdout_logfile` etc as per need . 

Restart the supervisor `sudo service supervisor restart` and go into the supervisor control shell via `sudo supervisorctl`. A `reload` command may need to reload the `.conf` file . 

Installation in `MAC` is bit different as it use `.ini` file extension but the file configuration remains same .  To install in `MAC`

```bash
brew install supervisor
```

install path usually `/usr/local/etc/` but need to create directory `supervisor.d` and create `.ini` file (for example `ojs-queue-monitor.ini`) in there . 

Rest of the process is same as Linux system .

**Comment by NateWr** [comment]
Thanks for the docs, @touhidurabir. I've added them to an issue in our docs repository: https://github.com/pkp/pkp-docs/issues/756#issuecomment-1225506171

**Comment by touhidurabir** [comment]
@NateWr I am closing this as it's implemented in the https://github.com/pkp/pkp-lib/issues/7105
