### ISSUE TITLE
Can't upload review files when in submission workflow

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8048]
**Describe the bug**
When trying to call the review file upload form from the Review submission workflow stage, an error 500 occurs

```
 PHP Fatal error:  Declaration of ManageReviewFilesForm::execute($stageSubmissionFiles, $fileStage = null) must be compatible with ManageSubmissionFilesForm::execute($stageSubmissionFiles = null, $fileStage = null, ...$functionArgs) in ojs-3-dev-3.3.0\lib\pkp\controllers\grid\files\review\form\ManageReviewFilesForm.inc.php on line 87
```

**To Reproduce**
1. Go to Dashboard -> Submissions
2. Click on any submission
3. Click Review workflow stage
4. At 'Review Files' grid, click 'Upload/Select Files' button
5. See error

**What application are you using?**
 OJS 3.3.0 (stable branch)

**PHP version**
PHP 8.0

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**

**Branch stable_3.3.0**
OJS: pkp/ojs#3442
PKP-LIB: #8049

**Comment by NateWr** [comment]
Merged to `stable-3_3_0`. It was already fixed in `main`.
