### ISSUE TITLE
Remove overspecified content management tools

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#805]
...primarily the social media and other link lists for the footer. There's a lot of code and very little flexibility in how content can be presented.

**Comment by asmecher** [comment]
Pulls:
pkp-lib: https://github.com/pkp/pkp-lib/pull/851
omp: https://github.com/pkp/omp/pull/153

@NateWr, this removes all the footer category/footer link/social media stuff entirely and just leaves the footer field on the Appearance setup form.

I suspect the user impact of this removal (>3k LOC!) will be nearly zero, because these were confusing and probably avoided. However, they were an attempt to add monograph-specific content management, so we'll have to consider how to manage that more ideally.

I've removed everything relevant that I could find from CSS/less, but it could use a look -- also how the footer field formats. Mind taking a look before I merge?

**Comment by NateWr** [comment]
I'm in favor of this change. However, it will impact Smithsonian and doesn't offer a way to add multiple columns, which is a very common footer design pattern.

What do you think about re-purposing the Right Sidebar for the footer? Is that something we could get into this PR? We could even leave it identified as right sidebar under the hood, but just label it Footer Sidebar in the admin area. Ideally they'd be called "primary" and "secondary" sidebar or something, since another theme might place them elsewhere.

This would give us the best of both worlds: the ability to add block content into the footer without the over-deterministic approach, a simple way to add arbitrary content in (via the content block plugin), and just enough structure to use a multi-column approach when appropriate in a theme.

**Comment by asmecher** [comment]
Re-using plugins for this is an option, but it seems cumbersome to me to get users to create blocks and then arrange them in the sidebar. I'd rather we worked a little with TinyMCE directly. There are a few options...

- http://bloggingspree.com/how-to-make-columns/ (likely outdated, but an equivalent should exist for newer TinyMCE)
- Create some styles and enable the style drop-down in TinyMCE

Either of those would permit the editor to stay in the TinyMCE editor, which I think is what they'd expect.

**Comment by NateWr** [comment]
The TinyMCE route is probably best. Are you still hoping to get this change in place for 1.2?

**Comment by asmecher** [comment]
Hoping, yes, but replacing suboptimal bits of OMP is a lower priority than missing functionality and high-priority bugs. Call it second-tier.

**Comment by NateWr** [comment]
When viewing frontend pages without a context, eg `/index/login/`, the footer area is missing. Whenever we work out what we're doing with the footer, we should probably have a better fallback if no content is specified.

**Comment by asmecher** [comment]
@NateWr, I don't see the same behavior you do (missing footer). Maybe you're hitting a Smarty error or something?

**Comment by NateWr** [comment]
This is what the `/index.php/index/login` looks like to me currently in OMP. Aside from the missing footer, the logo is all messed up too.

![selection_038](https://cloud.githubusercontent.com/assets/2306629/12324425/609a666a-baba-11e5-8b26-43bb07af3fb8.png)

I'll take a look at some point. But I think it's not a Smarty error. If you look at the [footer.tpl](https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/footer.tpl#L54-L75), the footer is just not shown if no footer categories exist.

If we are getting rid of the footer categories for 1.2, then I'd like to hold off until that's in place and then just fix this once.

**Comment by beghelli** [comment]
I also don't see any problem, neither with footer or the logos. Can you make sure you clean up your complied cache folder (cache/t_compile)?

**Comment by NateWr** [comment]
Yeah I've cleared the cache. Are you sure you're looking at the index login page (ie - no Press selected)?

**Comment by beghelli** [comment]
yes, index.php/index/login

**Comment by NateWr** [comment]
Can you post a screenshot? Looking at the code, the main footer panel on the right should not appear without a context, as footer categories can only be specified per-press.

**Comment by beghelli** [comment]
![omp-index](https://cloud.githubusercontent.com/assets/593977/12326413/d08e9a0c-bab7-11e5-809c-52a9821172ff.jpeg)

**Comment by NateWr** [comment]
Ah ok, so just a bit of miscommunication. The missing footer bit is the large white panel below the main content, to the right of the logo. Ideally we'll have something in there, even if it's just a large white space.

I'm guessing the logo issue might be related to the fact that I have uploaded an image in admin settings. Working on debugging a few things from the top logged in bar merge so I'll see if I can figure that out.

**Comment by NateWr** [comment]
Ok I fixed the issue with Array appearing where the logo/title should be. That leaves just the footer stuff again.

**Comment by asmecher** [comment]
Merged/cherry-picked. This removes the footer links and social media code; the footer can be managed through TinyMCE.

@NateWr, I copy/pasted the existing OpenSI footer into the footer field to check that div/ul/li combos are properly supported, and they are, complete with class names for styling. All that would be needed for SI to retain their existing lists in the footer would be to copy them into the footer field and add a few styles to a custom CSS to support the "1of3" class names that were previously included in OMP by default (per IIRC the OOCSS library, dead and buried, good riddance).

**Comment by NateWr** [comment]
Nice to have this stuff gone. I've touched up the styles a bit, removing some cruft, making it look a bit better with no footer, and fixing the `pageFooter` var in OJS. PRs:

https://github.com/pkp/pkp-lib/pull/1113
https://github.com/pkp/ojs/pull/737
https://github.com/pkp/omp/pull/211

**Comment by asmecher** [comment]
Merged, thanks!
