### ISSUE TITLE
Unexpected issues might happen when a plugin is installed in the wrong folder

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8058]
**Describe the bug**
When a user installs a plugin in the wrong folder, unexpected issues might happen, they are difficult to debug when you have no access to the installation (e.g. here the plugin works partially: https://forum.pkp.sfu.ca/t/error-en-el-proceso-de-deposito-de-pkp-preservation-network/67005).
Given that we're adding namespaces to the plugins, perhaps such problems will become easier to notice.

**Suggestions**
- Update instructions of our plugins, to ensure we're mentioning all the steps to properly install a plugin (perhaps a link inside the documentation hub)
- Warn the administrator if a plugin is placed in the wrong place (take care to avoid spamming notifications)
  - We probably can use the `version.xml` for that (`...<application>pln</application> <type>plugins.generic</type>...`)
- Warn the administrator at the `installPluginVersionTool` as well
- Offer an auto-fix (attempt to move the plugin to the right folder, while taking care with security issues: adding "../../bad-folder", overwriting existing files, etc.)

**To Reproduce**
- Install the PKP PN plugin manually in the incorrect folder
- Try to access the status link at the plugin settings
- See the first interface opening, while a sub-request fails with 404

**What application are you using?**
OJS 3.3.0

**Comment by asmecher** [comment]
@jonasraoni, I'm tempted to mark this a wontfix -- users should be installing plugins through the Plugin Gallery, and if they aren't, they'll be missing other important checks like compatibility assertions. (Users forcing incompatible plugins into their installations are much more common than plugins being installed in the wrong category.)

**Comment by jonasraoni** [comment]
I was thinking mostly about the plugins out of the plugin gallery, even though they are not our responsibility. Just to make the life of users less painful 😁

**Comment by asmecher** [comment]
Namespaces will surface this error immediately, since the plugin category is part of the namespace. I think that'll protect users from the partially-working situation in the original entry.
