### ISSUE TITLE
User locales set to NULL on user registration

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8060]
**Describe the bug**
On the first installation of the software, the initial/first user had the `locales` column in the `users` table set to `NULL`. This is same for any user registration through the publicly accessible registration process. Only for the users added through the admin section, they have the `locales` first set to `EMPTY ARRAY` that is `[]` . 

**To Reproduce**
1. Install the software from the scratch see that the first/initial user have `NULL` for `locales` column in the `users` table in DB.
2. which public registration enabled, register as a new user and see that user have `NULL` for `locales` column in the `users` table in DB.

**What application are you using?**
 OJS, OMP or OPS current `main` branch.

**Additional information**
This cause issues such as pkp/pkp-lib#8023 or may have more hidden bugs to discover .

**Comment by touhidurabir** [comment]
My suggestion is to have all users have the `locales` field set to `EMPTY ARRAY` that is `[]` . Or best would be to set to `site locale` if there is only one `locale` currently enabled . if there are multiple , they can update it form their profile but in case of just single locale install, this option does not show on profile update . 

So the proposed solution takes the following approaches
1. if site has has only one locale installed, set the user `locales` to that . for example , if the site has only `en_US` locale set/enabled, set the `locales` column in `users`  table such as `["en_US"]` . 
2. if the sites has multiple locale set up , set the `locales` column in `users`  table such as `[]` . they can always update form the profile section . 

@asmecher your thoughts on this ?

**Comment by touhidurabir** [comment]
> About the `[]` vs `null`, I'm personally against using `JSON` for fixed data types, so here I'd vote for normalizing the field using another table. If I had to choose between these two options, I'd go with `null`, just because it feels more natural for me to type `locales IS NULL` instead of `locales = '[]'`.

@jonasraoni I agree with you that having a json value as default is not a good idea but in that case we need to come to a consistent implementation . right now for 2 mentioned cases in the issue, we have `NULL` as default value set to `locales` columns. But when any user added from by the admin , we have `[]` for those cases as default value set to `locales`. This make it bit difficult to determine the locales value for an user object as we are getting `NULL` or `EMPTY ARRAY` . I have proposed a change here at https://github.com/pkp/pkp-lib/issues/8023#issuecomment-1172139809 but not sure if that will be accepted as there may be unforeseen effect with that (well there are other messy way to patch it up) . point is we need a consistent default value so that based on that, we can have the `locales` of `user` object to have a consistent data type which also respect the `user json schema` .

**Comment by jonasraoni** [comment]
Yeah, whatever we choose to go with, it should be consistent. I've already left my vote, to store this data in another table.

I'll leave a comment in the other issue just to share my opinion 😁

**Comment by NateWr** [comment]
Just to add the use cases for the field. I think we have a few suggested, but none used yet:

1.  #6221 
2. Send automated emails to users in the best language for them.
3. When drafting an email, help the user choose a language that's best for the recipient. Language selection was implemented in #3525, but we don't yet use the recipient's working languages to help choose the best language.

The main problem is that although we have a field, we don't ask for this information during the normal registration or user creation process. There's a proposal to capture this data during registration here: https://github.com/pkp/pkp-lib/issues/7702

**Comment by asmecher** [comment]
I recommend we leave this as-is until we have a working use of the field.

**Comment by touhidurabir** [comment]
@asmecher got it . And it probably make sense not to set automatically default something for user locales . In that case a simple fix would be to set the `users` table `locales` value set to default `[]` rather than `NULL` as it is right now . and have an update migration to update those users locales column to `[]` if set to `NULL` . that way we can prevent issues such as pkp/pkp-lib#8023 until we provide a way for user to set /select their locale on registration time . Right now , when an user added to system by admin trough the admin dashboard , it set the user locales to `[]` so that way we have at least a consistent data type set there by default. However if my [proposed solution](https://github.com/pkp/pkp-lib/issues/8023#issuecomment-1172139809) got accepted , then we don't need this fix but I think that solution has higher impact than this one .

**Comment by touhidurabir** [comment]
@asmecher please review the PRs 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#8060 User locales column default updated to empty array](https://github.com/pkp/pkp-lib/pull/8088)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#8060 Submodule Update ##touhidurabir/i8060_main##](https://github.com/pkp/ojs/pull/3457)

I will port the PR for the OPS and OMP main branch once get the confirmation if all ok .

**Comment by asmecher** [comment]
Thanks, @touhidurabir -- I've made a suggest here >> https://github.com/pkp/pkp-lib/pull/8088#issuecomment-1179434852

**Comment by touhidurabir** [comment]
@asmecher updated as per suggestion . please review again . then if all ok, I will forward port to OPS and OMP .

**Comment by touhidurabir** [comment]
@asmecher please review the following PRs

[ops](https://github.com/pkp/ops) --> [pkp/pkp-lib#8060 Submodule Update ##touhidurabir/i8060_main##](https://github.com/pkp/ops/pull/308)
[omp](https://github.com/pkp/omp) --> [pkp/pkp-lib#8060 Submodule Update ##touhidurabir/i8060_main##](https://github.com/pkp/omp/pull/1154)

**Comment by asmecher** [comment]
Thanks, @touhidurabir! Merged all, though there was a single test failure on OMP that I'll watch (99.5% sure it'll be fine).
