### ISSUE TITLE
Clear non-used resources uploaded by users

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8062]
**Describe the problem you would like to solve**
If a user uploads a file to a discussion, then aborts creating the discussion, the uploaded resource will remain orphaned in the submission folder.

**Describe the solution you'd like**
- Keep upload files (e.g. images uploaded through TinyMCE, discussion files, etc.) in a staging folder (this should have an interaction with the database), and move to the final destination only after the underlying process is completed
- The staging files should stay behind a code proxy (only the uploading user can view his files)
- Ensure rich text content is "processed" whenever it's updated, so images which were removed from it, can also be wiped off from the disk (watch out for security issues, such as taking care to not remove linked images uploaded by other users). It's needed to think about a good way to detect removed uploads (before vs after, save the used files in a generic database structure, etc.)
- Create garbage collector to delete the entries which are still present in the staging folder after a long time has passed. Perhaps some interaction with the session can be done, e.g. if the session ID which created this file doesn't exist anymore = green signal

If possible, a generic solution sounds interesting here, as the problem is shared by other upload forms.

**Who is asking for this feature?**
Developer

**Comment by NateWr** [comment]
I think that this will be resolved by https://github.com/pkp/pkp-lib/issues/7501. The new email composer uses the temporary files API to attach files to messages, so an aborted discussion would only leave a temporary file (which is automatically cleaned up).

This doesn't address the TinyMCE problem, but I think that's a separate (and bigger) issue to tackle once we settle on an approach to the discussion about public files at https://github.com/pkp/pkp-lib/discussions/8028.
