### ISSUE TITLE
Plugin with "verb=settings" gives "Failed Ajax request or invalid JSON returned"

### ISSUE THREAD

**Issue by marlara** [pkp/pkp-lib#8064]
**Describe the bug**
Installing plugings that calls for an API with "verb=settings" gives no possibilities to configure it, see also: https://forum.pkp.sfu.ca/t/error-when-configuring-texteditor-extras-3-3-0-11/73666

**To Reproduce**
1. Install a plugin like Text-editor-extras
2. Click on "Configure"
3. See error

**What application are you using?**
 OJS 3.3.0.11

**Additional information**
PHP version: 8.1 (but it appears also with PHP 8.0).
Multi-site installation with custom domains. 
The JSON is actually completely empty, that's why there is the invalid JSON returned, but every call without the "verb=settings" works fine.
EDIT: I installed the plugin directly from the Plugin Gallery

**Comment by marlara** [comment]
Unfortunately I am quite sure there is nothing relevant. This error has
been here for days and I checked everyday actually, but nothing appears.
The problem I think is with the call to the json? It is completely blank. I
tried to understand if there were some permission problems, but it doesn't
seem the case

Il gio 7 lug 2022, 16:57 Alec Smecher ***@***.***> ha scritto:

**Comment by asmecher** [comment]
@marlara, can you check your browser's web development tools to see what response the server is giving when it attempts to make the request to the `verb=settings` page? e.g. whether it's responding with a `200 OK` or `500 Internal Server Error`?

**Comment by marlara** [comment]
It's a 500 Internal server error

**Comment by asmecher** [comment]
Hi @marlara -- that should definitely correspond to a more specific message somewhere in your server logs. If not your PHP error log, then perhaps your Apache (or equivalent) log; these are sometimes kept separately.

**Comment by marlara** [comment]
Yes, in fact I cannot explain the missing logs. I checked the apache logs
and there is nothing. The php logs seems to be in the same apache log
file... I cannot figure out. I will check more, but I really checked
everywhere

Il ven 8 lug 2022, 16:52 Alec Smecher ***@***.***> ha scritto:

**Comment by marlara** [comment]
@asmecher I just only get these errors, which I don't really understand where they are coming from

```
[Mon Jul 11 04:08:12.485537 2022] [php:error] [pid 2424083] [client 209.97.135.24:47452] script '/var/www/ojs/info.php' not found or unable to stat
[Mon Jul 11 04:08:12.526975 2022] [negotiation:error] [pid 2423704] [client 209.97.135.24:47480] AH00687: Negotiation: discovered file(s) matching request: /var/www/ojs/config (None could be negotiated).
[Mon Jul 11 04:08:12.735517 2022] [negotiation:error] [pid 2424089] [client 209.97.135.24:47590] AH00687: Negotiation: discovered file(s) matching request: /var/www/ojs/config (None could be negotiated).
[Mon Jul 11 04:08:15.703483 2022] [negotiation:error] [pid 2423706] [client 209.97.135.24:48976] AH00687: Negotiation: discovered file(s) matching request: /var/www/ojs/config (None could be negotiated).
[Mon Jul 11 04:08:18.766080 2022] [php:error] [pid 2424083] [client 209.97.135.24:50602] script '/var/www/ojs/phpinfo.php' not found or unable to stat
[Mon Jul 11 04:08:18.853609 2022] [php:error] [pid 2423706] [client 209.97.135.24:50646] script '/var/www/ojs/info.php' not found or unable to stat
```

**Comment by marlara** [comment]
This is all the request in the Console log

```
XHRGEThttps://aldrovandiana.it/$$$call$$$/grid/settings/plugins/settings-plugin-grid/manage?verb=settings&plugin=customheaderplugin&category=generic&_=1657525500350
[HTTP/1.0 500 Internal Server Error 149ms]

	
GET
	https://aldrovandiana.it/$$$call$$$/grid/settings/plugins/settings-plugin-grid/manage?verb=settings&plugin=customheaderplugin&category=generic&_=1657525500350
Stato
500
Internal Server Error
VersioneHTTP/1.0
Trasferito426 B (dim. 0 B)
Referrer Policystrict-origin-when-cross-origin
Priorità richiestaHighest

    	
    Access-Control-Allow-Origin
    	*
    Connection
    	close
    Content-Length
    	0
    Content-Type
    	text/html; charset=UTF-8
    Date
    	Mon, 11 Jul 2022 07:45:23 GMT
    Server
    	Apache/2.4.54 (Ubuntu)
    Set-Cookie
    	OJSSID=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
    Set-Cookie
    	OJSSID=9c523md8je8nr7mmfdvvrh476t; expires=Wed, 10-Aug-2022 07:45:23 GMT; Max-Age=2592000; path=/; domain=aldrovandiana.it
    	
    Accept
    	application/json, text/javascript, */*; q=0.01
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
    Connection
    	keep-alive
    Cookie
    	OJSSID=9c523md8je8nr7mmfdvvrh476t
    DNT
    	1
    Host
    	aldrovandiana.it
    Referer
    	https://aldrovandiana.it/management/settings/website
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    User-Agent
    	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
    X-Requested-With
    	XMLHttpRequest
```

**Comment by marlara** [comment]
So, I finally managed to get the PHP errors logging in. This is for the TextEditor extra:

` [php:error] [pid 2434173] [client 37.103.18.12:40344] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www/ojs/cache/t_compile/e7015e6e1a3406762d960366518b3414e450feaf^aad0d99d45f1c49794dd5f48888b070605c1db6e_0.plugins-1-plugins-generic-textEditorExtras-generic-textEditorExtras.settings.tpl.php:60\nStack trace:\n#0 /var/www/ojs/cache/t_compile/e7015e6e1a3406762d960366518b3414e450feaf^aad0d99d45f1c49794dd5f48888b070605c1db6e_0.plugins-1-plugins-generic-textEditorExtras-generic-textEditorExtras.settings.tpl.php(60): in_array()\n#1 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_62c6a3b167a514_51631951()\n#2 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()\n#3 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()\n#4 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()\n#5 /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute()\n#6 /var/www/ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php(1072): Smarty_Internal_TemplateBase->fetch()\n#7 /var/www/ojs/lib/pkp/classes/form/Form.inc.php(197): PKPTemplateManager->fetch()\n#8 /var/www/ojs/plugins/generic/textEditorExtras/TextEditorExtrasSettingsForm.inc.php(57): Form->fetch()\n#9 /var/www/ojs/plugins/generic/textEditorExtras/TextEditorExtrasPlugin.inc.php(123): TextEditorExtrasSettingsForm->fetch()\n#10 /var/www/ojs/lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.inc.php(236): TextEditorExtrasPlugin->manage()\n#11 /var/www/ojs/lib/pkp/classes/core/PKPRouter.inc.php(395): PluginGridHandler->manage()\n#12 /var/www/ojs/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()\n#13 /var/www/ojs/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route()\n#14 /var/www/ojs/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch()\n#15 /var/www/ojs/index.php(68): PKPApplication->execute()\n#16 {main}\n  thrown in /var/www/ojs/cache/t_compile/e7015e6e1a3406762d960366518b3414e450feaf^aad0d99d45f1c49794dd5f48888b070605c1db6e_0.plugins-1-plugins-generic-textEditorExtras-generic-textEditorExtras.settings.tpl.php on line 60, referer: https://aldrovandiana.it/management/settings/website
`

For the Custom Header I will open another ticket

**Comment by asmecher** [comment]
Thanks, @marlara, that helps! Applying this change will correct that error message: https://github.com/pkp/textEditorExtras/commit/528fea31178c5ca2d1bbaef5b74d455cea421a17

**Comment by asmecher** [comment]
@marlara, hmm, it's fixed over here; is there either a Javascript (browser console log) error, or a warning in the PHP error log? Could you take a look at the JSON response for the request to the settings page?

**Comment by marlara** [comment]
Thank you very much ascmecher, actually the JSON has status "true", but it's empty:
![Schermata da 2022-07-13 11-34-21](https://user-images.githubusercontent.com/12834687/178702061-63c94627-b3e9-4df7-89b7-c6788a7e554a.png)
