### ISSUE TITLE
Queued DOIs do not update status to submitted

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#8065]
**Describe the bug**
When depositing DOIs, the status does not update to the intermediate "Submitted" status while it is enqueued.

**To Reproduce**
1. Go to DOI management page.
2. Select a submission.
3. Deposit DOI.
4. See "Unregistered" status go straight to "Error" or "Registered"

**What application are you using?**
 OJS `main` branch

**Additional information**
N/A

**Comment by ewhanson** [comment]
Hey @asmecher, could you have a look at this? It fixes a small bug introduced in #8020. Thanks!

PRs:

- `pkp-lib`: #8066
- `ojs`: pkp/ojs#3448
- `omp`: pkp/omp#1150
- `ops`: pkp/ops#304

**Comment by asmecher** [comment]
Merged, thanks!
