### ISSUE TITLE
Can't upload Copyedited files when in submission's Copyediting workflow

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8068]
**Describe the bug**
When the user is in submission's Copyediting workflow stage, and tries to upload Copyedited Files from the corresponding grid, an error 500 is produced 

```
PHP Fatal error:  Declaration of ManageCopyeditFilesForm::execute($stageSubmissionFiles, $fileStage = null) must be compatible with ManageSubmissionFilesForm::execute($stageSubmissionFiles = null, $fileStage = null, ...$functionArgs) in ojs-3-dev-3.3.0\lib\pkp\controllers\grid\files\copyedit\form\ManageCopyeditFilesForm.inc.php on line 33
```

**To Reproduce**
1. Go to Dashboard -> Submissions
2. Click on any submission
3. Click Copyediting workflow stage
4. At 'Copyedited' grid, click 'Upload/Select Files' button
5. See error

**What application are you using?**
OJS 3.3.0 (stable branch)

**PHP version**
PHP 8.0

**Comment by defstat** [comment]
@asmecher @NateWr

**PRs**

**Branch stable_3.3.0**
OJS: pkp/ojs#3450 (Tests Only)
PKP-LIB: #8071

**Comment by asmecher** [comment]
Merged, thanks!
