### ISSUE TITLE
Can't select discussion files to attach when in submission's Copyediting workflow

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8069]
**Describe the bug**
When the user is in submission's Copyediting workflow stage, and tries to select a file to attach in a Copyediting Discussion, an error 500 is produced 

```
PHP Fatal error:  Declaration of ManageQueryNoteFilesForm::execute($stageSubmissionFiles, $fileStage = null) must be compatible with ManageSubmissionFilesForm::execute($stageSubmissionFiles = null, $fileStage = null, ...$functionArgs) in ojs-3-dev-3.3.0\lib\pkp\controllers\grid\files\query\form\ManageQueryNoteFilesForm.inc.php on line 60
```

**To Reproduce**
1. Go to Dashboard -> Submissions
2. Click on any submission
3. Click Copyediting workflow stage
4. At 'Copyediting Discussions' grid, click 'Add discussion' button
5. At 'Attached Files' grid, click 'Select Files' button
6. See error

**What application are you using?**
OJS 3.3.0 (stable branch)

**PHP version**
PHP 8.0

**Comment by defstat** [comment]
@asmecher @NateWr

**PRs**

**Branch stable_3.3.0**
OJS: pkp/ojs#3451 (Tests Only)
PKP-LIB: #8072

**Comment by asmecher** [comment]
Merged, thanks! These could have all been covered in the same issue (anything that extends `ManageSubmissionFilesForm`).
