### ISSUE TITLE
[OJS] add iParadigms functionality to CrossRef plugin

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#807]
See attached diff. Adds iParadigm XML required for plagiarism checking using the iThenticate service. 
[iParadigms.diff.txt](https://github.com/pkp/pkp-lib/files/10802/iParadigms.diff.txt)

**Comment by asmecher** [comment]
Added.

**Comment by akgunib** [comment]
If I add this plugin to OJS, then am I available to faciliate to use iThenticate service for free, or what?

**Comment by asmecher** [comment]
@akgunib, our [support forum](http://forum.pkp.sfu.ca/) is a better place to ask general questions. We use this issue tracker for bugs/active development.
