### ISSUE TITLE
Error when opening Activity Log

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8073]
**Describe the bug**
When I am trying to open the Activity Log, on the Submission's Workflow, I am getting the following error 500

```
 PHP Fatal error:  Uncaught Error: Call to a member function getAssocType() on null in ojs-3-dev-main\lib\pkp\classes\submissionFile\Repository.inc.php:725
```

**To Reproduce**
1. Go to Dashboard -> Submissions
2. Click on any submission (could have to have Discussions attached)
3. Click on "Activity Log"

**What application are you using?**
 OJS (main branch)

**PHP Version**
PHP 8.0

---
**Current PRs**

**Branch `main`**
[OJS]: pkp/ojs#3481
[OMP]: pkp/omp#1179
[OPS]: pkp/ops#330
[pkp-lib]: #8142

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**

**Branch main**
[OJS]: pkp/ojs#3452 (Tests Only)
[pkp-lib]: #8075

**Comment by Vitaliy-1** [comment]
This is related to: https://github.com/pkp/pkp-lib/issues/7563

**Comment by defstat** [comment]
@asmecher 

**PRs**

**Branch `main`**
[OJS]: pkp/ojs#3452
[OMP]: pkp/omp#1160
[OPS]: pkp/ops#312
[pkp-lib]: #8075

**Comment by defstat** [comment]
@asmecher

**New PRs**

**Branch `main`**
[OJS]: pkp/ojs#3481
[pkp-lib]: #8142

**Comment by asmecher** [comment]
Thanks, @defstat! I added a couple of comments.

**Comment by defstat** [comment]
@asmecher last review comments about the use of `->foreignId()` resolved, and tests are passing.

**Comment by asmecher** [comment]
All merged -- thanks, @defstat!
