### ISSUE TITLE
Error when trying to delete a Note from the Activity Log

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8074]
**Describe the bug**
When trying to delete a Note from the Activity Log form in a submission's workflow the following error occurs:

```
 PHP Fatal error:  Uncaught Error: Class "NotificationManager" not found in ojs-3-dev-main\lib\pkp\controllers\informationCenter\InformationCenterHandler.inc.php:130
```

**To Reproduce**
1. Go to Dashboard -> Submissions
2. Click on any submission (could have to have Discussions attached)
3. Click on "Activity Log"
4. Click on "Notes" tab
5. Try to "Delete" a "Note"
6. See error

**What application are you using?**
 OJS (main branch)

**PHP Version**
PHP 8.0

**Comment by defstat** [comment]
@asmecher @NateWr 

**PRs**

**Branch `main`**
[OJS]: pkp/ojs#3453 (Tests Only)
[pkp-lib]: #8077

I could not reproduce the same issue on `stable_3.3.0`

**Comment by asmecher** [comment]
Merged, thanks!
