### ISSUE TITLE
Submission object missing in PKPSubmissionSubmitStep1Form, so execute-hook cannot save values

### ISSUE THREAD

**Issue by t-mayer** [pkp/pkp-lib#8076]
**Describe the bug**
Hi @NateWr ,
I used the hook submissionsubmitstep1form::execute to save the values from a custom field I created.
However, the Submission Object is missing in PKPSubmissionSubmitStep1Form.inc.php so I have no chance to save the values for the current publication. Is there a workaround to get the current publication?

**What application are you using?**
OMP 3.3.0-7

**Possible solution (?)**
Maybe move the parent hook
```
parent::execute(...$functionArgs);
```
further down in PKPSubmissionSubmitStep1Form.inc.php in the function execute(...$functionArgs) so the submission object is present when calling the hook, thus, allowing to get the current publication.

**Comment by NateWr** [comment]
The submission is attached to the form object, which is the first hook argument:

```php
function example($hookName, $args) {
    $form = $args[0];
    $publication = $form->submission->getCurrentPublication();

    // ...
}
```

**Comment by NateWr** [comment]
Apologies, I see what you mean. The submission is only attached after the form is executed the first time.

You probably want to use the `Submission::add` hook instead, which will fire every time a new submission is created. Or the `Publication::add` hook, which will fire every time a publication is created.

**Comment by t-mayer** [comment]
Thank you for the quick answer!!
