### ISSUE TITLE
[OJS 3.2.1.4] Error in Scheduled Tasks an not show metrics

### ISSUE THREAD

**Issue by diegomejia071** [pkp/pkp-lib#8080]
Hi,

I have had an error for almost a month since the Usage Stats are not shown and remain in the stage phase.

![image](https://user-images.githubusercontent.com/21009904/177414210-b58ebb49-22f6-4570-8372-090026794493.png)

I have the Acron plugin enabled and also when I try to run php tools/runScheduledTasks.php plugins/generic/usageStats/scheduledTasks.xml, after a while, it shows me the following error:

`PHP Fatal error: Uncaught Error: Call to a member function getData() on null in /lib/pkp/classes/submission/Representation.inc.php:134 Stack trace: #0 /lib/pkp/classes/statistics/PKPMetricsDAO.inc.php(378): Representation->getContextId() #1 /classes/statistics/MetricsDAO.inc.php(47): PKPMetricsDAO->foreignKeyLookup(515, 246408) #2 /lib/pkp/classes/statistics/PKPMetricsDAO.inc.php(284): MetricsDAO->foreignKeyLookup(515, 246408) #3 /plugins/generic/usageStats/UsageStatsLoader.inc.php(823): PKPMetricsDAO->insertRecord(Array) #4 /plugins/generic/usageStats/UsageStatsLoader.inc.php(228): UsageStatsLoader->_loadData('usage_events_20...') #5 /lib/pkp/classes/task/FileLoader.inc.php(167): UsageStatsLoader->processFile('/datos/usageSta...') #6 /lib/pkp/classes/submission/Representation.inc.php on line 134`

**Comment by asmecher** [comment]
Hi @diegomejia071 -- I see this is a [cross-post](https://forum.pkp.sfu.ca/t/ojs-3-2-1-4-error-en-tareas-programadas-no-muestra-metricas/73894); I'll close this issue and leave the support forum thread open. It's best to just post in one place.

**Comment by diegomejia071** [comment]
What happens is that I need to solve this inconvenience of the metrics, and nowhere do they answer me.

**Comment by asmecher** [comment]
@diegomejia071, I've responded to your original post on the subject (https://forum.pkp.sfu.ca/t/ojs-3-2-1-4-error-in-scheduled-tasks-an-not-show-metrics/73504).

**Comment by diegomejia071** [comment]
Thanks @asmecher.
