### ISSUE TITLE
Consider new templates for automatic notification emails and remove redundant

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8091]
**Describe the problem you would like to solve**
As part of [this issue](https://github.com/pkp/pkp-lib/issues/7286), I'm decoupling emails from notifications. Currently, these automatic emails with a generic `NOTIFICATION` template are sent alongside notifications and might require reconsidering:
-  Request payment from authors, see https://github.com/pkp/ojs/blob/74d9e9eb6eefb752e76e70d7a3da62ed0fd052cd/classes/decision/types/traits/RequestPayment.inc.php#L77
- New version of publication, see https://github.com/pkp/pkp-lib/blob/1f64bda06d6b0ec675b02a2285b867b5413d9ffe/api/v1/submissions/PKPSubmissionHandler.inc.php#L747
- During ReviewerReviewStep3Form execution to notify users (ROLE_ID_MANAGER, ROLE_ID_SUB_EDITOR) associated with the stage assignment, see https://github.com/pkp/pkp-lib/blob/1f64bda06d6b0ec675b02a2285b867b5413d9ffe/classes/submission/reviewer/form/PKPReviewerReviewStep3Form.inc.php#L168
- During EditReviewForm execution to notify the reviewer about new details, see https://github.com/pkp/pkp-lib/blob/1f64bda06d6b0ec675b02a2285b867b5413d9ffe/controllers/grid/users/reviewer/form/EditReviewForm.inc.php#L162 

**Describe the solution you'd like**
For now, I'm leaving only those emails, which have unsubscribe setting in the user profile form. But it looks more approriate not to send a generic email but rather email with a meaningful template. 

**Who is asking for this feature?**
Me

**Comment by NateWr** [comment]
@Vitaliy-1 am I right in thinking that each of the notifications you mention sent an email in 3.3 but will not send an email in 3.4. Is that the breaking change that we're considering?

**Comment by Vitaliy-1** [comment]
Only payment request notification for authors doesn't have an unsubscribe option and I'm considering removing it. I'm leaving others but expecting to change the message itself.

**Comment by Vitaliy-1** [comment]
PR OJS: https://github.com/pkp/ojs/pull/3740

**Comment by Vitaliy-1** [comment]
@NateWr, I think request payment is the last notification email in the system that required refactoring. It doesn't have unsubscribe option. Can you take a look at the PR?
