### ISSUE TITLE
Refactor entity collector to use more intuitive syntax

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8092]
**Describe the problem you would like to solve**
Currently, the entity `Repository` is the interface to get a collection of objects. It uses the `Collector` to select objects and passes that to the `getMany(Collector $c)`, `getIds(Collector $c)`, and `getCount(Collector $c)` methods.

However, this leads to an uncomfortable syntax which requires calling the `Repo` facade twice:

```php
Repo::category()->getMany(
    Repo::category()
        ->getCollector()
        ->filterByPublicationIds([$id])
);
```

**Describe the solution you'd like**
Refactor our entity `Repository` and `Collector` classes so that the `getMany()`, `getIds()` and `getCount()` methods are part of the `Collector` class. This will allow a simplified syntax:

```php
Repo::category()
    ->getCollector()
    ->filterByPublicationIds([$id])
    ->getMany();
```

**Who is asking for this feature?**
A brief proposal was raised in our Mattermost and the response was positive. If we get this out for 3.4, the changes will not cause much disruption for plugins and third-party devs. 

- [x] classes/issues/Repository.inc.php (OJS only)
- [x] lib/pkp/classes/announcement/Repository.inc.php
- [x] lib/pkp/classes/author/Repository.php
- [x] lib/pkp/classes/category/Repository.php
- [x] lib/pkp/classes/decision/Repository.php
- [x] lib/pkp/classes/doi/Repository.php
- [x] lib/pkp/classes/emailTemplate/Repository.php
- [x] lib/pkp/classes/galley/Repository.php
- [x] lib/pkp/classes/institution/Repository.php
- (n/a) lib/pkp/classes/mail/Repository.php
- [x] lib/pkp/classes/publication/Repository.php
- [ ] lib/pkp/classes/submission/Repository.php
- [x] lib/pkp/classes/submissionFile/Repository.php
- [x] lib/pkp/classes/user/Repository.php

PRs:
- https://github.com/pkp/orcidProfile/pull/219
- https://github.com/pkp/omp/pull/1181
- https://github.com/pkp/ojs/pull/3502
- https://github.com/pkp/ops/pull/332
- https://github.com/pkp/pkp-lib/pull/8188
- https://github.com/pkp/browse/pull/11
- https://github.com/asmecher/lensGalley/pull/61

**Comment by NateWr** [comment]
Wow, thanks! I was dreading this work. :laughing:

**Comment by asmecher** [comment]
It was ... pretty annoying, but definitely worthwhile.
