### ISSUE TITLE
UserGroup Entity: Change UserGroupDAO to Repository Pattern

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8093]
UserGroup Entity follows the deprecated DAO class (`UserGroupDAO`) to perform the code actions necessary for UserGroups. 

This issue will cover the appropriate changes for the UserGroups (and possibly related Entities like `UserGroupAssignments`) to follow the active Repository pattern instead.  

---
**Current PRs**

**Branch `main`**
[OJS]: pkp/ojs#3486
[OMP]: pkp/omp#1171
[OPS]: pkp/ops#325
[pkp-lib]: #8154 

**Plugins**
citationStyleLanguage: pkp/citationStyleLanguage#98
quickSubmitPlugin: pkp/quickSubmit#59

---
For documentation purposes I am adding the file bellow, pairing the removed `UserGroupDAO` functions to the new Repository pattern respective ones.

[UserGroupDAO-2-UserGroupRepo.txt](https://github.com/pkp/pkp-lib/files/9693359/UserGroupDAO-2-UserGroupRepo.txt)

**Comment by defstat** [comment]
@asmecher I have resolved the PRs review comments. Waiting for the tests to run on [OJS](https://app.travis-ci.com/github/pkp/ojs/builds/254835640).

**Comment by asmecher** [comment]
All merged to `main` -- thanks, @defstat, this is great! This just needs some documentation at the head of the issue so that @NateWr can schedule it for inclusion in the release notebook for 3.4; I'll leave this issue open until that's in place.

**Comment by asmecher** [comment]
@defstat, it also looks like there's still a call to `UserGroupDAO` in https://github.com/pkp/citationStyleLanguage/blob/main/pages/CitationStyleLanguageHandler.inc.php#L138; could you refactor this?

**Comment by ajnyga** [comment]
Quicksubmit is affected by this and broken at the moment

**Comment by defstat** [comment]
> Quicksubmit is affected by this and broken at the moment

@ajnyga could you please provide the reproduction steps and possible php errors?

**Comment by asmecher** [comment]
@defstat, I see in `QuickSubmitForm::initData`...
```php
$userGroupAssignmentDao = DAORegistry::getDAO('UserGroupAssignmentDAO');
$userGroupDao = DAORegistry::getDAO('UserGroupDAO');
```
These DAOs no longer exist, which will cause fatal errors when the quickSubmit form is initialized.

**Comment by defstat** [comment]
@asmecher @NateWr 

I have added a file in the [top ](https://github.com/pkp/pkp-lib/issues/8093#issue-1300577038) comment, for documentation reasons, pairing the removed UserGroupDAO functions to the new Repository pattern respective ones.

**Comment by defstat** [comment]
@ajnyga I have added a PR for QuickSubmitPlugin [here](https://github.com/pkp/pkp-lib/issues/8093#issue-1300577038). Could you please check if that resolves your issue?

**Comment by asmecher** [comment]
It looks like `<migration class="PKP\migration\upgrade\v3_4_0\I8093_UpdateUserGroupRelationTablesFK"/>` got left out of the upgrade script for OMP and OPS; I'll correct that on #6093.

**Comment by asmecher** [comment]
@defstat, I think everything here has now been merged; is this issue ready for closing from your side?

**Comment by defstat** [comment]
@asmecher I think so.

**Comment by asmecher** [comment]
Excellent! Closing, thanks. This was an important one for establishing some forward-looking patterns!
