### ISSUE TITLE
Journal Settings: `metaCitations` defined twice

### ISSUE THREAD

**Issue by jprk** [pkp/pkp-lib#810]
I have tracked down a strange bug in my OJS 2.4.5 install, which demonstrated itself as the following entry in our web server error log:

    [Sun Oct 11 09:02:31 2015] [error] [client 213.151.87.2] ojs2 has produced an error
    Message: WARNING: Cannot use a scalar value as an array
    In file: /var/www/ojs/classes/journal/JournalSettingsDAO.inc.php
    At line: 83
    [...]

Indeed, there was an attempt to set a journal setting entry `$journalSettings['metaCitations']['en_US']` in the moment when `$journalSettings['metaCitations']` has been already set to scalar value `true`. The cause of this is a duplicate entry for `metaCitations` in `journal_settings` table: The older value has no locale set and its data type is `bool`, the newer value has `en_US` locale and its data type is `string`.

My guess is that the newer value appeared during journal setup, while the older one is a pre-defined entry copied from somewhere. But having no backups of the database right after it has been created it is hard to tell ... 

After deleting the locale-less `metaCitations` entry the error does not occur anymore. 

Jan

**Comment by ctgraham** [comment]
I have see this in multiple installs recently.  I have not identified a cause.

Looking at 2.4.6, however, I had assumed that the boolean locale-less entry is the correct one.

**Comment by asmecher** [comment]
That's bug 8899: http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8899

**Comment by jprk** [comment]
Thanks for information. The Bugzilla entry contains also a description of fix for existing OJS installs, thank you for that as well.
