### ISSUE TITLE
How to remove incomplete submissions in OJS 3.3.0.10?

### ISSUE THREAD

**Issue by koormath** [pkp/pkp-lib#8100]
I couldn't find an option to remove incomplete submissions in OJS 3.3.0.10?. It was available in OJS 3.2.1.4. Could you please let me know, is there any way to delete the incomplete submissions?

**Comment by asmecher** [comment]
@koormath, can you post your question on our support forum at https://forum.pkp.sfu.ca? That's the best place for questions like this.

**Comment by koormath** [comment]
> @koormath, can you post your question on our support forum at https://forum.pkp.sfu.ca? That's the best place for questions like this.

Thank You! I will do it.

**Comment by koormath** [comment]
@asmecher Thank you. I will do it
