### ISSUE TITLE
Update PayPal plugin dependency guzzle adapter

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8105]
**Describe the bug**
I'm receiving a fatal error when trying to make payment with the plugin:
```
PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/vendor/php-http/guzzle6-adapter/src/Client.php(75): GuzzleHttp\choose_handler()
#1 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/vendor/php-http/guzzle6-adapter/src/Client.php(36): Http\Adapter\Guzzle6\Client::buildClient()
#2 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/vendor/php-http/discovery/src/ClassDiscovery.php(219): Http\Adapter\Guzzle6\Client->__construct()
#3 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/vendor/php-http/discovery/src/HttpClientDiscovery.php(30): Http\Discovery\ClassDiscovery::instantiateClass()
#4 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/vendor/omnipay/common/src/Common/Http/Client.php(34): Http\Discovery\HttpClientDiscovery::find()
#5 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/vendor/omnipay/common/src/Common/AbstractGateway.php(332): Omnipay\Common\Http\Client->__construct()
#6 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/vendor/omnipay/common/src/Common/AbstractGateway.php(69): Omnipay\Common\AbstractGateway->getDefaultHttpClient()
#7 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/vendor/omnipay/common/src/Common/GatewayFactory.php(88): Omnipay\Common\AbstractGateway->__construct()
#8 [internal function]: Omnipay\Common\GatewayFactory->create()
#9 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/vendor/omnipay/common/src/Omnipay.php(116): call_user_func_array()
#10 /home/doc/OJS/development/ojs/plugins/paymethod/paypal/PaypalPaymentForm.inc.php(50): Omnipay\Omnipay::__callStatic()
#11 /home/doc/OJS/development/ojs/pages/user/UserHandler.inc.php(338): PaypalPaymentForm->display()
#12 [internal function]: UserHandler->completePurchaseSubscription()
#13 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPRouter.inc.php(465): call_user_func()
#14 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#15 /home/doc/OJS/development/ojs/lib/pkp/classes/core/Dispatcher.inc.php(163): PKP\core\PKPPageRouter->route()
#16 /home/doc/OJS/development/ojs/lib/pkp/classes/core/PKPApplication.inc.php(376): PKP\core\Dispatcher->dispatch()
#17 /home/doc/OJS/development/ojs/index.php(70): PKP\core\PKPApplication->execute()
#18 {main}
  thrown in /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/guzzlehttp/guzzle/src/functions.php on line 61
```

**To Reproduce**
1. Configure subscriptions and set payment type to paypal plugin
2. Go to my subscriptions page  
3. Click purchase subscription and follow purchase steps
4. Instead of redirecting to PayPal see the error message

**What application are you using?**
 OJS main branch

**Additional information**
The error occurs because of conflicting guzzle version in shared lib (7+) vs plugin's (6+), where it's required by `php-http/guzzle6-adapter`, see: https://github.com/pkp/ojs/blob/main/plugins/paymethod/paypal/composer.json#L5. As per the error message, `functions` in Guzzle in the shared library, points to the `Utils` class in the plugin's Guzzle package, where method `chooseHandler()` doesn't exist. Updating to `php-http/guzzle7-adapter` solves the issue but thinking about this further, there is a more global problem with conflicting dependencies if a plugin requires and downloads one that already exists.

**Comment by jonasraoni** [comment]
I was discussing this with @asmecher these days, so I just created a discussion here: https://github.com/pkp/pkp-lib/discussions/8106

I'll try to think about something 🤔

**Comment by asmecher** [comment]
@jonasraoni, I think this came up a few weeks ago in the context of a pull request that added something to the Paypal `composer.json` -- do you recall what PR that was? I can't find it now.

**Comment by jonasraoni** [comment]
@asmecher Guzzle has been introduced here: https://github.com/pkp/ojs/commit/2677348a9078041434ac0b204ef163811ead9b8f, looks like an optional HTTP client configuration after upgrading to omnipay v3.

And on pkp/lib, Guzzle moved to v7 here: https://github.com/pkp/pkp-lib/commit/f9a128e525a619f5e1375de59aaa8ea5b6029367#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R22

Looks like both are ok, so we just need to fix the conflicts, I've added some notes to the [discussion](https://github.com/pkp/pkp-lib/discussions/8106).

**Comment by asmecher** [comment]
In the interests of working around this specific error message, I've added explicit dependencies on the paypal plugin composer JSON to match the same version as we require in the pkp-lib composer JSON:
- https://github.com/pkp/ojs/blob/main/plugins/paymethod/paypal/composer.json#L5
- https://github.com/pkp/omp/blob/main/plugins/paymethod/paypal/composer.json#L5

The bigger issue should be solved in the discussion, but the immediate Paypal issue is resolved in `main`.
