### ISSUE TITLE
NativeImportExport plugin references OMP

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#8107]
**Describe the bug**
There's a reference to `$press` instead of `$journal` in the OJS version of the NativeImportExportPlugin.

**To Reproduce**
See https://github.com/pkp/ojs/blob/f8bd3f9bbe01e32e13625e7473c6af1a5e3cb1a7/plugins/importexport/native/NativeImportExportPlugin.inc.php#L385-L386

**What application are you using?**
 OJS `stable-3_3_0`

**Additional information**
N/A

**Comment by ewhanson** [comment]
@asmecher, I just ran into this on `stable-3_3_0`. Could you have a quick look at the PR? Thanks.

PR:

- pkp/ojs#3464

**Comment by asmecher** [comment]
Good spotting! Merged, thanks.
