### ISSUE TITLE
Thanking reviewer is throwing internal exception.

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8111]
**Describe the bug**
When thanking a reviewer, it throws internal exception and the `Thank Reviewer` modal is not closing at done . 

**To Reproduce**
1. Create a submission and push it to `External Review` stage.
2. Invite a reviewer, complete the review process and submit it.
3. Login as `Editor` and confirm the submitted review by reviewer.
4. Try to thank the reviewer and see that the modal is not going away even though the mail went through . 

**What application are you using?**
 OJS OMP in the `main` branch.

**Additional information**
Error Log
```
PHP Fatal error:  Uncaught Error: Class "SubmissionEmailLogEntry" not found in /INSTALLED_PATH/lib/pkp/controllers/grid/users/reviewer/form/ThankReviewerForm.inc.php:123
```
In addition, the mentioned class `ThankReviewerForm` has several `class use statement` missing .

**Comment by touhidurabir** [comment]
@asmecher please review the PRs. As this is a trivial fix, I have made PR for all . 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#8111 added missing use class statements](https://github.com/pkp/pkp-lib/pull/8112)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#8111 Submodule Update ##touhidurabir/i8111_main##](https://github.com/pkp/ojs/pull/3468)
[omp](https://github.com/pkp/omp) --> [pkp/pkp-lib#8111 Submodule Update ##touhidurabir/i8111_main##](https://github.com/pkp/omp/pull/1162)
[ops](https://github.com/pkp/ops) --> [pkp/pkp-lib#8111 Submodule Update ##touhidurabir/i8111_main##](https://github.com/pkp/ops/pull/315)

**Comment by NateWr** [comment]
Thanks @touhidurabir. It looks like one test failed for each app. Probably just a fluke but I've restarted them to be sure. Can you let me know when they've passed?

**Comment by touhidurabir** [comment]
@NateWr , the `OJS` tests have passed for `stage 2`. But for `OPS` and `OMP`  it has failed for one of each instances . 

For `OPS`, it shows error as 
```
Cypress failed to start.
This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
Command failed: /home/travis/.cache/Cypress/4.12.1/Cypress/Cypress --no-sandbox --smoke-test --ping=958
----------
Platform: linux (Ubuntu - 18.04)
Cypress Version: 4.12.1
The command "./lib/pkp/tools/travis/run-tests.sh" exited with 1.
```

for `OMP` it's shows as 

```
Create a submission:
     AssertionError: Timed out retrying: Expected to find element: `input[id^="title-en_US-"`, but never found it.
      at Context.eval (http://localhost/__cypress/tests?p=cypress/support/index.js:847:6)
```

Both of these are non related to this PR so I am not sure what I can do to make it all pass.

**Comment by NateWr** [comment]
Travis has had a bunch of hiccups lately. I've restarted those again and I expect they'll pass. Let me know when you see they've finished.

**Comment by asmecher** [comment]
Thanks, all, I've gone ahead and merged these. There does seem to be a Cypress dependency issue lately on specific configurations only; if it doesn't resolve this week I'll contact Travis about it.
