### ISSUE TITLE
Refactor email sending code in plugins and convert to Mailables

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8117]
The following plugins still rely on old email sending:
- Users XML Plugin
- Manual Payment Plugin
- Orcid Profile Plugin, see: https://github.com/pkp/orcidProfile/issues/210

Replace with Mailables and make configurable through the UI

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8215
OJS: https://github.com/pkp/ojs/pull/3518

**Comment by NateWr** [comment]
Looks good. Just a few small comments.

**Comment by Vitaliy-1** [comment]
@NateWr, I've updated PRs. It appears that `QueuedPaymentEmailVariable` already exists, no need to add those variables individually to the Mailable.

**Comment by NateWr** [comment]
Thanks @Vitaliy-1, I've merged those PRs to `main`. Nothing required for OMP/OPS, right?

**Comment by Vitaliy-1** [comment]
Yes. It's for shared library and OJS only
