### ISSUE TITLE
Remove duplicated locale keys

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8119]
**Describe the bug**
Some locale files have duplicated keys, which might raise unexpected issues when editing them through Weblate.

**What application are you using?**
/main
/stable-3_3_0

**PRs**
`main`
- https://github.com/pkp/pkp-lib/pull/8120
- https://github.com/pkp/ojs/pull/3472
- https://github.com/pkp/ops/pull/316
- OMP: no duplicates

`stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8121
- https://github.com/pkp/ojs/pull/3473
- OMP/OPS: no duplicates

**Comment by asmecher** [comment]
All merged, thanks!
