### ISSUE TITLE
OPS Browse Section gives 500 error, namespace does not match folder

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#8126]
**Describe the bug**
SectionsHandler.php defines `namespace APP\pages\sections;`
https://github.com/pkp/ops/blob/main/pages/preprints/SectionsHandler.php#L17

This causes 500 error:
`PHP Fatal error:  Uncaught TypeError: get_class_methods(): Argument #1 ($object_or_class) must be an object or a valid class name, string given in /home/vagrant/htdocs/ops-master/lib/pkp/classes/core/PKPPageRouter.php:282`

**To Reproduce**
1. Go to browse by section in OPS
2. See error

**What application are you using?**
 OPS main branch

**Comment by NateWr** [comment]
Thanks @ajnyga. The following PR should fix it:

https://github.com/pkp/ops/pull/319

**Comment by NateWr** [comment]
Merged to `main`.
