### ISSUE TITLE
Docblocks still use .inc.php in @file statements

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8128]
The docblock at the top of PHP files still refers to the `.inc.php` files after they were renamed to `.php`. Example:

```
/**
 * @file classes/notification/PKPNotificationManager.inc.php
 *
```

These should be updated to refer to the correct file names.

@asmecher I suspect you can handle this easily with a clever command-line script, so assigning to you.

**Comment by asmecher** [comment]
Indeed!
```
find . -name \*.php -exec sed -i -e "s/^\( \* @file.*\).inc\.php/\1.php/" "{}" ";"
```
I ran this for some of the files I renamed but not all. I'll try to catch the rest.
