### ISSUE TITLE
404 Not Found on Statistics in 3.0b1

### ISSUE THREAD

**Issue by selwyntcy** [pkp/pkp-lib#813]
The Statistics page seems broken, with error 404 when accessing `index.php/quest/manager/statistics` with a logged in user (mine with Journal Manager role).

**Comment by selwyntcy** [comment]
The correct request path seems to be `index.php/quest/management/tools/statistics`.

**Comment by asmecher** [comment]
Assigning to @beghelli -- but @selwyntcy, note that this is beta-level code so you'll run into this kind of thing.

**Comment by beghelli** [comment]
Fixed.
