### ISSUE TITLE
Default email signature can't be created

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8130]
**Describe the bug**
Context's `emailSignature` property has a default value, see: https://github.com/pkp/pkp-lib/blob/1e395122fe482a89177864dcf24a6bb0599278f1/schemas/context.json#L262. It's composed of other variables: `contextUrl`, `contextName`, `mailingAddress`, `contactName` and `contactEmail`. During new context creation, some of them aren't yet available. This leads to the appearance of default variables in the email signature:
```
<br/><hr /><br/><p><a href="http://localhost:8000/index.php/tj">Third journal</a></p><p>{$mailingAddress}</p><p>{$contactName}, <a href="mailto: {$contactEmail}">{$contactEmail}</a></p>
``` 

**To Reproduce**
1. Create a new journal
2. Go to workflow settings -> emails of the newly created journal
3. See the value of the signature

**What application are you using?**
 OJS main branch

**Additional information**
![emailSignature](https://user-images.githubusercontent.com/20665587/182366991-784659b3-2f13-4966-b829-11495848bdf9.png)

**Comment by Vitaliy-1** [comment]
Can be changed to something like:
```
<br>
<hr>
A message sent from <a href="{$contextUrl}">{$contextName}</a>.
```

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/8574

Tests only:
https://github.com/pkp/ojs/pull/3728

**Comment by NateWr** [comment]
Merged to `main`.
