### ISSUE TITLE
CC and BCC not working in Mailable

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8131]
**Describe the bug**
Adding CC or BCC recipients to a mailable with `$mailable->cc(...)` and `$mailable->bcc(...)` doesn't work. Although the recipients appear in the `Mailable` class, the email that is sent doesn't include headers with these recipients.

**To Reproduce**
1. Login as editor.
1. Go to any submission in the submission stage
2. Click on Send for Review
3. In the first step, when composing an email to the author, click CC/BCC and add amails to the CC and BCC.
4. Complete the steps to record the editorial decision.
5. See in the logs or mail server that the email is sent without a CC or BCC.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
I discovered this while working on the submission wizard, where we need to cc and bcc the submission acknowledgement email. Here is an example of a `Mailable` class showing the cc recipients:

```
PKP\mail\mailables\SubmissionAcknowledgement {#795
     +locale: null,
     +from: [
       [
         "name" => "Ramiro Vaca",
         "address" => "rvaca@mailinator.com",
       ],
     ],
     +to: [
       [
         "name" => "Carlo Corino",
         "address" => "ccorino@mailinator.com",
       ],
     ],
     +cc: [
       [
         "name" => "Ramiro Vaca",
         "address" => "rvaca@mailinator.com",
       ],
       [
         "name" => null,
         "address" => "bcc1@example.com",
       ],
       [
         "name" => null,
         "address" => "bcc2@example.com",
       ],
     ],
     +bcc: [],
     +replyTo: [],
     +subject: "Thank you for your submission to {$journalName}",
     +markdown: null,
     +view: "<p>Dear {$recipientName},</p><p>Thank you for your submission to {$journalName}. We have received your submission, {$submissionTitle}, and a member of our editorial team will see it soon. You will be sent an email when an initial decision is made, and we may contact you for further information.</p><p>You can view your submission and track its progress through the editorial process at the following location:</p><p>Submission URL: {$authorSubmissionUrl}</p><p>If you have been logged out, you can login again with the username {$recipientUsername}</p><p>If you have any questions, please contact me from your <a href="{$authorSubmissionUrl}">submission dashboard</a>.</p><p>Thank you for considering this journal as a venue for your work.</p>{$signature}",
     +textView: null,
     +viewData: [],
     +attachments: [],
     +rawAttachments: [],
     +diskAttachments: [],
     +callbacks: [],
     +theme: null,
     +mailer: null,
   }
```

And here is the email that resulted:

```
From: Ramiro Vaca <rvaca@mailinator.com>
To: Carlo Corino <ccorino@mailinator.com>
Subject: Thank you for your submission to Journal of Public Knowledge
MIME-Version: 1.0
Date: Wed, 03 Aug 2022 14:14:40 +0000
Message-ID: <3717eb31246732951abceb864384ac07@mailinator.com>
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<p>Dear Carlo Corino,</p><p>Thank you for your submission to Journal of Pub=
lic Knowledge. We have received your submission, Lorem ipsum example, and a=
 member of our editorial team will see it soon. You will be sent an email w=
hen an initial decision is made, and we may contact you for further informa=
tion.</p><p>You can view your submission and track its progress through the=
 editorial process at the following location:</p><p>Submission URL: http://=
localhost:8000/publicknowledge/authorDashboard/submission/25</p><p>If you h=
ave been logged out, you can login again with the username ccorino</p><p>If=
 you have any questions, please contact me from your <a href=3D"http://loca=
lhost:8000/publicknowledge/authorDashboard/submission/25">submission dashbo=
ard</a>.</p><p>Thank you for considering this journal as a venue for your w=
ork.</p>{$signature}
```

@Vitaliy-1 do you have any ideas what might be causing this? Is there any chance that my logging setup just isn't picking these fields up, but it's otherwise working?

**Comment by Vitaliy-1** [comment]
`PKP\mail\traits\Recipient::recipients()` may overwrite cc and bcc on the line:
```
$this->setAddress($to);
```

**Comment by NateWr** [comment]
No that's not it. I did a test with a mailable without the `Recipient` trait, using the `->to()` directly, and still had the same problem.

**Comment by Vitaliy-1** [comment]
According to my tests on the branch with the completed refactoring of emails, `cc` is reflected in the mail log as it should. As for `bcc`, I suspect Laravel simply doesn't include it in the log. I traced that if using Sendmail, it receives that data.

**Comment by Vitaliy-1** [comment]
I'll do the final test once this issue is closed: https://github.com/pkp/pkp-lib/issues/7286; I believe it should resolve the problem

**Comment by NateWr** [comment]
Yep, I can see the `cc` now. :+1:
