### ISSUE TITLE
OAI tests failing in the main branch

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8139]
**Describe the bug**
The OAI tests are failing in the `main` branch. See [example test failure](https://app.travis-ci.com/github/pkp/ojs/jobs/579031136). No error log is provided but I was able to track this down to a couple problems:

1. The test dataset still seems to produce a scheduled task for Medra, even though I can't find any references to it in `main` branch.
2. There seem to be problems with the DC metadata format.

**To Reproduce**
1. Download the `main` OJS database from https://github.com/pkp/datasets and use it in a local install.
3. Go to: `/index/oai?verb=ListRecords&metadataPrefix=oai_dc`
5. See 500 error and find errors in error log

**What application are you using?**
OJS `main` branch

**Additional information**
The database from the dataset includes a scheduled task for Medra which caused the following error:

```
[08-Aug-2022 10:34:05 UTC] PHP Warning:  require_once(/home/nate/Projects/pkp/ojs-main/plugins/importexport/medra/MedraInfoSender.inc.php): Failed to open stream: No such file or directory in /home/nate/Projects/pkp/ojs-main/lib/pkp/includes/functions.php on line 37
[08-Aug-2022 10:34:05 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/nate/Projects/pkp/ojs-main/plugins/importexport/medra/MedraInfoSender.inc.php' (include_path='.:/usr/share/php') in /home/nate/Projects/pkp/ojs-main/lib/pkp/includes/functions.php:37
Stack trace:
#0 /home/nate/Projects/pkp/ojs-main/plugins/generic/acron/AcronPlugin.php(249): import('plugins.importe...')
#1 /home/nate/Projects/pkp/ojs-main/plugins/generic/acron/AcronPlugin.php(181): APP\plugins\generic\acron\AcronPlugin->_shutdownFunction('/home/nate/Proj...')
#2 [internal function]: APP\plugins\generic\acron\AcronPlugin->APP\plugins\generic\acron\{closure}()
#3 {main}
  thrown in /home/nate/Projects/pkp/ojs-main/lib/pkp/includes/functions.php on line 37
```

I was able to fix this by deleting the row from the scheduled tasks table:

```
delete from scheduled_tasks where class_name LIKE '%MedraInfoSender%';
```

However, I wasn't able to find out where that row came from. There's nothing in the code base that references it, but the test dataset seems to include it.

Once that was fixed, I was getting the following error:

```
[08-Aug-2022 10:37:39 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getProperties() on null in /home/nate/Projects/pkp/ojs-main/lib/pkp/plugins/oaiMetadataFormats/dc/PKPOAIMetadataFormat_DC.php:42
Stack trace:
#0 /home/nate/Projects/pkp/ojs-main/plugins/oaiMetadataFormats/dc/OAIMetadataFormat_DC.inc.php(33): PKP\plugins\oaiMetadataFormats\dc\PKPOAIMetadataFormat_DC->toXml(Object(APP\submission\Submission), NULL)
#1 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/oai/OAI.php(836): APP\plugins\oaiMetadataFormats\dc\OAIMetadataFormat_DC->toXml(Object(PKP\oai\OAIRecord))
#2 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/oai/OAI.php(564): PKP\oai\OAI->formatMetadata('oai_dc', Object(PKP\oai\OAIRecord))
#3 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/oai/OAI.php(93): PKP\oai\OAI->ListRecords()
#4 /home/nate/Projects/pkp/ojs-main/pages/oai/OAIHandler.php(46): PKP\oai\OAI->execute()
#5 [internal function]: APP\pages\oai\OAIHandler->index(Array, Object(APP\core\Request))
#6 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#7 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/core/PKPPageRouter.php(307): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#8 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#9 /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#10 /home/nate/Projects/pkp/ojs-main/index.php(70): PKP\core\PKPApplication->execute()
#11 {main}
  thrown in /home/nate/Projects/pkp/ojs-main/lib/pkp/plugins/oaiMetadataFormats/dc/PKPOAIMetadataFormat_DC.php on line 42
```

I found that the files in `plugins/oaiMetadataFormats/dc` still include `inc.php`. However, even after cleaning this up, it didn't seem to fix the problem. I dug around a bit more and landed on `DataObject::getSupportedExtractionAdapters()`, which seems to interact with the `filters` table. At that point I was out of my depth and gave up.

**Comment by NateWr** [comment]
I have temporarily skipped the OAI tests so that we can continue to run the other tests and merge until this is fixed. To un-skip, revert this commit:

https://github.com/pkp/pkp-lib/commit/07c3c093a7f518c6b4f455ed54b296bc382b489f

**Comment by jonasraoni** [comment]
I could fix yesterday, so I'll push the PRs soon, basically the plugin isn't being loaded.

**Comment by jonasraoni** [comment]
Here goes the PRs, the OPS one passed through the tests, I just rebased to grab the last updates... The others I'm not sure, let's see if there are more stones on the way 😁

PRs
- https://github.com/pkp/pkp-lib/pull/8140
- https://github.com/pkp/ops/pull/322
- https://github.com/pkp/omp/pull/1168
- https://github.com/pkp/ojs/pull/3482

**Comment by asmecher** [comment]
@jonasraoni, it looks like you've taken this on -- can you let me know when it's ready for review?

**Comment by jonasraoni** [comment]
Ok! At this moment I'm just using the `omp` branch to debug a flaky cypress test, looks like it's ok, I'll restart the build a couple of times to confirm

**Comment by asmecher** [comment]
OK. It looks like there's quite a bit of code rewriting in the PRs -- besides the missing [class alias](https://github.com/pkp/ops/pull/322/files#diff-8ff0043158f5efe36590f2effb57cdc3bd69ed71ac1a67e75b31cb58b70a342eR23), what was required to fix the initial issue @NateWr reported?

**Comment by jonasraoni** [comment]
Together with the `class_alias()`, this piece of code is needed at `pkp-lib` to also look for files without the `.inc`: https://github.com/pkp/pkp-lib/pull/8140/files#diff-ae633b551c0c70e7b0520a15de4747ea83d8bf0a1bb14f0930df73d1d4733a39R259
Other alternatives would be to include an `index.php` or rename the class.

**Comment by jonasraoni** [comment]
@asmecher I've reset the OMP build around 5x and didn't flag random failures, so perhaps the flaky test is fixed 😅
So feel free to review now.

Another method that I fixed (just redirected to the standard "plugin loader") was this one: https://github.com/pkp/pkp-lib/pull/8140/files#diff-ae633b551c0c70e7b0520a15de4747ea83d8bf0a1bb14f0930df73d1d4733a39R145

**Comment by asmecher** [comment]
@jonasraoni, there are a ton of changes here that aren't related to the OAI test failure. It's hard to review and would be easy to let an unrelated (breaking) change slip in accidentally. Could you break this up into separate PRs/issues?

**Comment by jonasraoni** [comment]
Ok!

**Comment by asmecher** [comment]
The original problem should be fixed incidentally by https://github.com/pkp/ojs/commit/1e89821c7f3162bf09a4f779b6317061b233a56a, which renames `Dc11MetadataPlugin` to `Dc11Plugin` in accordance with the [expectations of the plugin loader](https://github.com/pkp/pkp-lib/blob/648521f27b96ecd71f4670caacf3426603827043/classes/plugins/PluginRegistry.php#L297) for cases without an `index.php` wrapper. I'll revert your work-arounds and confirm, @NateWr.

**Comment by jonasraoni** [comment]
I'm closing as it has been fixed. I've moved everything that I considered relevant to other issues.
