### ISSUE TITLE
Problem update OJS 2.4.5 to version 3.2.1.4

### ISSUE THREAD

**Issue by elton557** [pkp/pkp-lib#8144]
I'm having trouble updating my ojs which is on version 2.4.5 and I want to go to 3.2.1-4, I get the error below:

`
ERROR: Reviewer files with ID 17396 from review assignment 5569 could not be found in the database table submission_files
ERROR: Reviewer files with ID 23841 from review assignment 7261 could not be found in the database table submission_files
ERROR: Reviewer files with ID 25150 from review assignment 7451 could not be found in the database table submission_files
ERROR: Reviewer files with ID 25679 from review assignment 7478 could not be found in the database table submission_files
ERROR: Reviewer files with ID 28775 from review assignment 7878 could not be found in the database table submission_files
ERROR: Reviewer files with ID 29753 from review assignment 8100 could not be found in the database table submission_files
ERROR: Reviewer files with ID 32806 from review assignment 8748 could not be found in the database table submission_files
[code: Installer Installer::fixAuthorGroup]
[data: dbscripts/xml/upgrade/3.0.0_reviewer_files.xml]
ERROR: Upgrade failed: DB: Column 'review_round_id' cannot be null`

**Comment by NateWr** [comment]
Hi @elton557, we're no longer handling general support enquiries here on GitHub. Please use our [community support forum](https://forum.pkp.sfu.ca/c/questions/5) to ask for help with upgrades from OJS 2.
