### ISSUE TITLE
Class "PKP\plugins\generic\usageEvent\Config" not found

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8146]
**Describe the bug**
When trying to access a Journal, `Class "PKP\plugins\generic\usageEvent\Config" not found` error is produced

```
PHP Fatal error:  Uncaught Error: Class "PKP\plugins\generic\usageEvent\Config" not found in ojs-3-dev-main\lib\pkp\plugins\generic\usageEvent\PKPUsageEventPlugin.php:250
```

**To Reproduce**
1. In an installation with more than one Journals, try to click on the name of one of them
2. See error

**What application are you using?**
 OJS main branch

**Additional information**
PHP 8.0

**Comment by defstat** [comment]
@asmecher @NateWr 

**PR**

**Branch `main`**
[pkp-lib]: #8147

**Comment by asmecher** [comment]
Merged, thanks!
