### ISSUE TITLE
OMP missing REVIEW_REQUEST_SUBSEQUENT email template

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8150]
**Describe the bug**
The `REVIEW_REQUEST_SUBSEQUENT` email template is included in OJS and used in `ReviewerForm`. However, it is not in OMP's list of default email templates to be installed.

https://github.com/pkp/omp/blob/main/registry/emailTemplates.xml

@Vitaliy-1 not sure if you've already fixed this but maybe you can roll it into your other PR.

**What application are you using?**
`main` branch (3.4 pre-release)

**Comment by Vitaliy-1** [comment]
PRs
OMP: https://github.com/pkp/omp/pull/1219
pkp-lib: https://github.com/pkp/pkp-lib/pull/8345 (this includes the commit, which resolves https://github.com/pkp/pkp-lib/issues/7324)
