### ISSUE TITLE
Allow Mailables to use custom email templates through API 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8155]
Mailable API was implemented as per https://github.com/pkp/pkp-lib/issues/7706 but Mailables are still using only default email template, e.g., consider `ReviewRemind`: 
```php
class ReviewRemind extends Mailable
{
    ...
    protected static ?string $emailTemplateKey = 'REVIEW_REMIND';
    protected static bool $supportsTemplates = true;
    ...
}
```
to retrieve the template to be shown  during `ReviewRemindForm` initialization, `ReviewRemind::getEmailTemplateKey` is used, which just returns the default template, see: https://github.com/pkp/pkp-lib/blob/34ef99e26cb2d6c7fead29deeaef4fa2f458e35a/classes/mail/Mailable.php#L133
However, `ReviewRemind` supports custom templates, which implies that another template associated with Mailable in `mailable_templates` table should be returned, e.g.
```php
Repo::emailTemplate()->getMany(
    Repo::emailTemplate()->getCollector()
        ->filterByMailables(ReviewRemind::getId())
        ->filterByContext(...)
);
```

**Comment by NateWr** [comment]
The `ReviewRemind` mailable doesn't yet support multiple templates. I'm going to close this for now but I plan to sort this out when we refactor the email template management UI.
