### ISSUE TITLE
Replace abandoned Stringy package

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8158]
**Describe the bug**
The https://github.com/danielstjules/Stringy, as well as the other repos from this author, have been unmaintained (no commits nor comments over pending PRs/issues) since 2017.

For now we've got warnings related to PHP 8.1, but later nobody knows. So I think it makes sense to replace it, the best fork seems to be the https://github.com/voku/Stringy.

**What application are you using?**
/main

**PRs**
- https://github.com/pkp/pkp-lib/pull/8159
- https://github.com/pkp/ojs/pull/3488 [TESTS ONLY]

**Comment by jonasraoni** [comment]
@asmecher As it passed through the tests, feel free to check the PR.
This package is 100% compatible with the original (according to the maintainer). The other option would be probably the https://github.com/statamic/Stringy (looks like they've just fixed the PHP 8.1 warnings).

**Comment by asmecher** [comment]
Merged, thanks!
