### ISSUE TITLE
[OJS] Pdf links not displayed in search results depending on locale

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#816]
Hi,

We have encountered a problem with our dual-locale journals, they don't display pdf links of one language in the search results.

Examples:
1. Journal 1 (Journal's primary locale: Swedish) don't display links to English pdfs when Swedish is the selected UI language.
2. Journal 2 (Journal's primary locale: English) don't display links to Swedish pdfs when English is the selected UI language.

This is different from the display of links in the issue view, where everything is correct (language within parentheses for pdf files that are not in the selected UI language).

(OJS 2.4.6)

Best regards,
Martin Persson, Lund University Library

**Comment by asmecher** [comment]
Thanks for reporting, @martinpub; I've scheduled this for attention in OJS 2.4.8.

**Comment by martinpub** [comment]
Thanks @asmecher!

**Comment by asmecher** [comment]
@martinpub, sorry for the delay -- this turned out to be a very small fix. Please try out the attached commit and confirm whether it's working. Meanwhile my local tests seem to be OK so I'm closing the issue; the fix will be included in OJS 2.4.8 (to be released soon).

**Comment by martinpub** [comment]
Thanks for the fix @asmecher, it's working.
