### ISSUE TITLE
Drop forgotten locale file in OMP

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8162]
**Describe the bug**
The addThis plugin was removed in 2017, but one file remained.

**PRs**
- https://github.com/pkp/omp/pull/1173

**What application are you using?**
OMP /main

**Comment by jonasraoni** [comment]
@asmecher Trivial fix.

**Comment by asmecher** [comment]
Have you checked the status of that locale file against https://github.com/pkp/omp/blob/cb13f35b506e8159da9db699f41fe153447ea77d/plugins/generic/addThis/locale/sl_SI/locale.po?

**Comment by jonasraoni** [comment]
The file at https://github.com/pkp/addThis/blob/main/locale/sl_SI/locale.po, has a similar content, and it was updated in Weblate, while this one wasn't, so I think it's ok.

**Comment by asmecher** [comment]
OK, thanks! Merged.
