### ISSUE TITLE
Missing the localization files for the DC11 metadata plugin

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8164]
**Describe the bug**
The `en_US` and the `sl_SI` folders are misplaced for the `dc11` filter in OMP (see https://github.com/pkp/omp/tree/main/plugins/metadata/dc11).
While in other repositories, some filters are ok and others don't even have the localization folder.

**PRs**
- https://github.com/pkp/ojs/pull/3493
- https://github.com/pkp/omp/pull/1175
- https://github.com/pkp/ops/pull/328

**What application are you using?**
/main

**Comment by jonasraoni** [comment]
@asmecher Minor fixes

**Comment by asmecher** [comment]
Merged all 3 PRs, thanks.
