### ISSUE TITLE
Travis is currently swallowing pieces of the log

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8165]
**Describe the bug**
See the latest OMP build output: https://app.travis-ci.com/github/pkp/omp/jobs/579596625

Sometimes it works though 😅

**PRs**
- https://github.com/pkp/ojs/pull/3490
- https://github.com/pkp/omp/pull/1174
- https://github.com/pkp/ops/pull/326

**What application are you using?**
/main

**Comment by jonasraoni** [comment]
@asmecher Here I just wanted to go with a workaround, by placing the `error.log` output before the `uuencode`, but it ended up fixing the other issue ¯\_(ツ)_/¯

**Comment by asmecher** [comment]
No objections here -- the Travis logs are capricious and subject to quirks, but if this works for now...
