### ISSUE TITLE
The dc oai metadata format plugin for OJS has duplicated localization

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8166]
**Describe the bug**
The locale files located here: https://github.com/pkp/ojs/tree/main/plugins/oaiMetadataFormats/dc/locale, are not needed, as [they are already covered by the `pkp-lib`](https://github.com/pkp/pkp-lib/tree/main/plugins/oaiMetadataFormats/dc/locale).

**PRs**
- https://github.com/pkp/ojs/pull/3491

**What application are you using?**
OJS /main

**Comment by jonasraoni** [comment]
@asmecher Trivial fix.

**Comment by asmecher** [comment]
Merged!
