### ISSUE TITLE
Unable to export a monograph with the NativeImportExport Plugin at OMP

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8169]
**Describe the bug**

When trying to export a published monograph (I've used one from the build/tests: `Bomb Canada and Other Unkind Remarks in the American Media`) I get the errors below (I've applied some minor fixes to `/main`, before reaching the validation message):

```
Errors occured:
Generic Items
- Line 0 Column 0: Element '{http://pkp.sfu.ca}submission_file', attribute 'stage': [facet 'enumeration'] The value '' is not an element of the set {'public', 'submission', 'note', 'review_file', 'review_attachment', 'final', 'fair_copy', 'editor', 'copyedit', 'proof', 'production_ready', 'attachment', 'query', 'review_revision', 'dependent'}.
- Line 0 Column 0: Element '{http://pkp.sfu.ca}submission_file', attribute 'stage': [facet 'enumeration'] The value '' is not an element of the set {'public', 'submission', 'note', 'review_file', 'review_attachment', 'final', 'fair_copy', 'editor', 'copyedit', 'proof', 'production_ready', 'attachment', 'query', 'review_revision', 'dependent'}.

Validation errors:
- Element '{http://pkp.sfu.ca}submission_file', attribute 'stage': [facet 'enumeration'] The value '' is not an element of the set {'public', 'submission', 'note', 'review_file', 'review_attachment', 'final', 'fair_copy', 'editor', 'copyedit', 'proof', 'production_ready', 'attachment', 'query', 'review_revision', 'dependent'}.
- Element '{http://pkp.sfu.ca}submission_file', attribute 'stage': [facet 'enumeration'] The value '' is not an element of the set {'public', 'submission', 'note', 'review_file', 'review_attachment', 'final', 'fair_copy', 'editor', 'copyedit', 'proof', 'production_ready', 'attachment', 'query', 'review_revision', 'dependent'}.
```

**To Reproduce**
1. Setup the installation with a fresh database from the dataset repository, together with its associated files
2. Access the link `/index.php/publicknowledge/management/importexport/plugin/NativeImportExportPlugin#export-tab`
3. Select the article `Bomb Canada and Other Unkind Remarks in the American Media` and try to export.

**What application are you using?**
OMP /main

**Comment by asmecher** [comment]
@defstat, could you have a look at this one?

**Comment by defstat** [comment]
@jonasraoni I think that this is directly related to [#8137](https://github.com/pkp/pkp-lib/issues/8137#issue-1331031565). I have proposed a fix for that [here](https://github.com/pkp/pkp-lib/pull/8212). Could you please check if the change proposed resolves this issue as well (It does on my dev installation)

**Comment by jonasraoni** [comment]
@defstat I just checked and I could export, I just got this warning:
`The submission file 21 was skipped because it is attached to a record that will not be imported, such as a review assignment or discussion.`

**Comment by jonasraoni** [comment]
Closed in favor of https://github.com/pkp/pkp-lib/issues/8137.
