### ISSUE TITLE
[OJS] lib/password_compat includes .git file in release tarball

### ISSUE THREAD

**Issue by bricas** [pkp/pkp-lib#817]
Not a big deal, but, after downloading the OJS 2.4.7 tarball, I noticed the lib/password_compat directory has a .git file, which is messy for us since we track our OJS install in git.

**Comment by ctgraham** [comment]
If using git for OJS tracking, consider `git clone`ing the repo directly, rather than downloading the tarballs.

**Comment by asmecher** [comment]
Thanks for reporting, @bricas -- I've added the .git directory from the password_compat library to the package builder's exclusion list.
