### ISSUE TITLE
Upgrade sokil/php-isocodes to fix warnings

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8170]
**Describe the bug**
In order to avoid warnings at PHP 8.1 and also update the ISO database, it will be needed to move into `sokil/php-isocodes` 4.0, the breaking change from 3.0 is that the library was divided into sub-packages.

**PRs**
- https://github.com/pkp/pkp-lib/pull/8171
- https://github.com/pkp/ojs/pull/3494 [TESTS ONLY]

**What application are you using?**
/main

**Comment by jonasraoni** [comment]
@asmecher Upgrading the main package to 4.x and adding the new one was enough to make things work.

**Comment by asmecher** [comment]
OK, thanks -- merged the pkp-lib PR and closed the (outdated) submodule update.
