### ISSUE TITLE
Article Cover pages are not preserved during the upgrade from OJS2

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#8174]
**Describe the bug**
When upgrading from OJS 2.4 to OJS 3.2.1, the upgrade transformation for the new article cover page data format (`migrateSubmissionCoverImages`) is not applied and needs to be run later in the upgrade process.

This was first reported with an upgrade from OJS 2.4 to OJS 3.2.1, but the upgrade function in question is applicable from OJS 2.4 through OJS 3.1 so may be applicable to other upgrades. While this does not directly affect OJS 3.3, it may impact upgrade paths from OJS 2.4 moving to OJS 3.3.

The `migrateSubmissionCoverImages` function need to be run after `3.0.0_submission_settings.xml` because this is where the relevant setting names are renamed to the expected `coverImage` and `coverImageAltText`. It also needs to continue to run before the `localizeIssueCoverImages` and `localizeArticleCoverImages` functions.

**To Reproduce**
1. Run an upgrade from OJS 2.4 to OJS 3.2.1 that has articles with cover pages.
2. See cover images not showing up.
3. See data not transformed correctly into coverImage associate array

**What application are you using?**
 OJS 3.2.1

**Additional information**
N/A

**Comment by ewhanson** [comment]
Hey @asmecher, could you take a look at this? We've primarily run into this issue with upgrades from OJS 2 with a stopover at OJS 3.2.1, but it can affect upgrades to OJS 3.3.0 as well. The fix doesn't change the upgrade code, just reorders when the `migrateSubmissionCoverImages` is run. Thanks!

PRs:

- `stable-3_2_1`: pkp/ojs#3861
- `stable-3_3_0`: pkp/ojs#3862

**Comment by asmecher** [comment]
Hi @ewhanson! Those changes look simple enough, and I can't think of any side-effects off the top of my head. So I haven't reviewed the sequence of events that leads to this being necessary, but I'm OK to merge it when you're ready (or go ahead and do it yourself). :+1:

**Comment by ewhanson** [comment]
Thanks. Merged!
