### ISSUE TITLE
OJS 3.3.0-10 I can't enable usage statistics plugin

### ISSUE THREAD

**Issue by gurumelo** [pkp/pkp-lib#8178]
https://forum.pkp.sfu.ca/t/enable-usage-statistics-plugin-on-ojs-3-3-0-10/73426

**Comment by asmecher** [comment]
I'll close this issue; the forum is the best place to get support.

**Comment by asmecher** [comment]
If you feel your post has been forgotten, feel free to post a follow-up on the same forum thread.
