### ISSUE TITLE
Native export fails when missing copyright holders

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#818]
When show_errors is on and an article does not have copyright holders, the native export fails when trying to iterate the null return.

$article->getCopyrightHolder(null) is not guaranteed to return an array() at:
https://github.com/pkp/ojs/blob/98753f9f1b4dd3f730d400ab44746e55d70e966b/plugins/importexport/native/NativeExportDom.inc.php#L298

**Comment by asmecher** [comment]
Merged and cherry-picked to ojs-stable-2_4_7. Thanks, @ctgraham!
