### ISSUE TITLE
OJS TimeZone error

### ISSUE THREAD

**Issue by Azizulibrahim** [pkp/pkp-lib#8181]
I had problem as below:-

[proxy_fcgi:error] [pid 366698] [client 219.92.19.117:63112] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /var/www/***/lib/pkp/classes/xml/PKPXMLParser.inc.php:212\nStack trace:\n#0 /var/www/***/lib/pkp/classes/xml/PKPXMLParser.inc.php(162): PKPXMLParser->createParser()\n#1 /var/www/***/lib/pkp/classes/xml/PKPXMLParser.inc.php(204): PKPXMLParser->parseTextStruct()\n#2 /var/www/***/lib/pkp/classes/db/XMLDAO.inc.php(52): PKPXMLParser->parseStruct()\n#3 /var/www/***/lib/pkp/classes/i18n/TimeZoneDAO.inc.php(58): XMLDAO->parseStruct()\n#4 /var/www/***/lib/pkp/classes/cache/GenericCache.inc.php(63): TimeZoneDAO->_timeZoneCacheMiss()\n#5 /var/www/***/lib/pkp/classes/cache/FileCache.inc.php(115): GenericCache->get()\n#6 /var/www/***/lib/pkp/classes/i18n/TimeZoneDAO.inc.php(77): FileCache->getContents()\n#7 /var/www/***/lib/pkp/classes/i18n/PKPLocale.inc.php(885): TimeZoneDAO->getTimeZones()\n#8 /var/www/gaexc...'

already check XML was installed and enable.
already changed time zone..also same error came out. 
PHP version 7.4
OJS Version 3.1

Please help

**Comment by asmecher** [comment]
The forum is the best place to get help; I see you're already posting there (https://forum.pkp.sfu.ca/t/fatal-error-uncaught-error-call-to-undefined-function-xml-parser-create/51953).
