### ISSUE TITLE
OMP | upgrade to 3.3.0.11 | DublinCore plugin is acting up

### ISSUE THREAD

**Issue by gemusehandler** [pkp/pkp-lib#8182]
**Describe the bug**

I have just updated my OMP 3.3.0.7 to 3.3.0.11. As a result the book galleys refuse to load. Clicking on the download link result in a white page. The chapters by the way are doing fine. Makes no difference if I switch from PhP 7.4.21 to 8.0.8.

My PHP error log says:

```
#0 /Users/gemusehandler/Sites/omp-3.3.0-11/lib/pkp/classes/plugins/HookRegistry.inc.php(107): DublinCoreMetaPlugin->monographFileView('CatalogBookHand...', Array)
#1 /Users/gemusehandler/Sites/omp-3.3.0-11/pages/catalog/CatalogBookHandler.inc.php(307): HookRegistry::call('CatalogBookHand...', Array)
#2 /Users/gemusehandler/Sites/omp-3.3.0-11/pages/catalog/CatalogBookHandler.inc.php(216): CatalogBookHandler->download(Array, Object(Request), true)
#3 /Users/gemusehandler/Sites/omp-3.3.0-11/lib/pkp/classes/core/PKPRouter.inc.php(395): CatalogBookHandler->view(Array, Object(Request))
#4 /Users/gemusehandler/Sites/omp-3.3.0-11/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#5 /Users/gemusehandler/Sites/omp-3.3.0-11/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route(Object(Request))
# in /Users/gemusehandler/Sites/omp-3.3.0-11/plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.inc.php on line 221
```

Because there are some references to the DublinCoreMetaPlugin, the first step I undertook was switching that plugin off. And with that the books are downloadable again.

**Comment by asmecher** [comment]
@gemusehandler, you've included the stack trace, but the actual PHP error message should appear just above the first line (`#0`).

**Comment by gemusehandler** [comment]
Sorry for that. Here you go:

`[17-Aug-2022 18:05:33 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Call to undefined method Submission::getFullTitles() in /Users/gemusehandler/Sites/omp-3.3.0-11/plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.inc.php:221
`

**Comment by asmecher** [comment]
See: https://github.com/pkp/pkp-lib/issues/7864#issuecomment-1155051764

**Comment by gemusehandler** [comment]
Correct,
getFullTitles() >> getFullTitle(null)
DublinCoreMetaPlugin.inc.php:221
resolves this issue.
Thanks

**Comment by asmecher** [comment]
Thanks for the confirmation; that'll be fixed in the -12 build.

**Comment by dagosalas** [comment]
@asmecher 
The same error just happened to me yesterday when upgrading to v3.3.0.11, so I would recommend that PKP notify them not to upgrade to this version and wait for .12

**Comment by asmecher** [comment]
I'll put together the -12 builds for OJS, OMP, and OPS in the near future; that should resolve the issue.
