### ISSUE TITLE
Submission Acknowledgement email fails if context email contact isn't set

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8183]
**Describe the bug**
After the last step of the submission process is finished,  SubmissionAcknowledgement and SubmissionAcknowledgementNotAuthor are sent to authors with `from` field being populated by context contact details. If the latter isn't set, it leads to a fatal error:
```
PHP Fatal error:  Uncaught Symfony\Component\Mime\Exception\LogicException: An email must have a "From" or a "Sender" header
```
in `PKP\submission\form\PKPSubmissionSubmitStep4Form`

**To Reproduce**
1. Remove journal contact email if set.
2. Make a new submission following the guidelines
3. Submit it
4. See the error 

**What application are you using?**
 OJS, OMP and OPS main branch

**Additional information**
Context contact details should be made mandatory during the new context creation process or disable this email if it's not filled.

**Comment by NateWr** [comment]
@Vitaliy-1 I like the idea of making a context contact mandatory. How do you think we should handle upgrades? Should we add a pre-flight check that requires every context to have contact details before they can upgrade?

**Comment by Vitaliy-1** [comment]
Yes, a pre-flight check sounds like a good solution

**Comment by touhidurabir** [comment]
@asmecher PRs to review 
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8324
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3570

**Comment by NateWr** [comment]
@touhidurabir, can I ask @Vitaliy-1 to review this instead of @asmecher? Vitaliy has the best understanding of the problem at the moment.

**Comment by touhidurabir** [comment]
@NateWr sure, no problem .

**Comment by Vitaliy-1** [comment]
Yes, this should resolve the current problem with emails. Thanks @touhidurabir!
I left a couple of comments regarding query generating part in the pre-flight checks but, honestly, I'm not an expert

**Comment by touhidurabir** [comment]
@Vitaliy-1 can you check again. I have update the requested changes .  PRs

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8324
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3570

if all ok, I will forward it to `OMP` and `OPS` .

**Comment by touhidurabir** [comment]
@Vitaliy-1 all PRs. If tests pass for all , it should be good to merge.

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8324
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3570
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1225
[ops](https://github.com/touhidurabir/ops) --> https://github.com/pkp/ops/pull/373

**Comment by Vitaliy-1** [comment]
Thanks, merged!
