### ISSUE TITLE
incomplete_count calculation does not account for cancelled review assignment

### ISSUE THREAD

**Issue by p6steve** [pkp/pkp-lib#8189]
**Describe the bug**
As [posted](https://forum.pkp.sfu.ca/t/unassign-does-not-clear-active-badge-in-add-reviewer-dialog/73665) on the PKP Community Forum

In the Add Reviewer search list, dialog, the “active” badge shows “1 active” even when this reviewer has been unassigned by clicking the Unassign button on the review panel.

The Review Requests Cancelled (1) field reflects the Unassignment

There is also a NaN value in the Days Since Last Assigned Field

**To Reproduce**
1. In a Submission in Review phase,
1. Assigned a Reviewer
1. Unassigned this Reviewer
0. Opened the Add Reviewer dialog and view pulldown detail next to Select Reviewer button
What I tried to resolve the issue:
0. Clear data cache

**What application are you using?**
OJS 3.3.0.6

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
<img width="844" alt="image" src="https://user-images.githubusercontent.com/40125330/185605085-9e9e69ca-c410-4d58-81ff-638bd1813453.png">
[OJS incomplete_count Error Report.xlsx](https://github.com/pkp/pkp-lib/files/9381623/OJS.incomplete_count.Error.Report.xlsx)

**Comment by asmecher** [comment]
For OJS 3.3.0-x, the appropriate patch (applied in lib/pkp) is https://github.com/pkp/pkp-lib/commit/e010f2cee357a936462825553ec7c3498fd3757b. Thanks, @p6steve!
