### ISSUE TITLE
piwik plugin doesn't play well with others

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#819]
See: http://forum.pkp.sfu.ca/t/google-analytics-in-ojs-2-4-6-0/4617

Piwik plugin overwrites the output in insertFooter() rather than appending to it.
https://github.com/pkp/ojs/blob/fddc0a90d6ca922117f2384e12ab1d2046d7c4a1/plugins/generic/piwik/PiwikPlugin.inc.php#L172

**Comment by asmecher** [comment]
Merged and cherry-picked to ojs-stable-2_4_7. Thanks again, @ctgraham!
