### ISSUE TITLE
DOAJ export plugin 

### ISSUE THREAD

**Issue by OJSomm** [pkp/pkp-lib#8192]
**error message**
Deposit was not successful! The DOAJ API returned an error: 'Client error: `POST https://doaj.org/api/v2/articles?api_key=31e6cc196ec9481ebedc8e3b9e42233a` resulted in a `403 Forbidden` response: {"status": "forbidden", "error": "It is not possible to create an article for this journal. Have you included in the upl (truncated...) '.

**To Reproduce**
1. DOAJ registered and accepted
2. settings - ID and API Key - OK
3. Entered Api key on DOAJ Export plugin
4. Do not want to export automatically!
5.  Mark one and register
6. ERROR message - forbidden

**What application are you using?**
OJS 3.3.0.7.

**Additional information**
At Help DOAJ 
«If you are trying to upload a file that was automatically generated by the OJS DOAJ plugin, then you should first contact OJS for help.»

Thank you!

**Comment by asmecher** [comment]
@OJSomm, could you post this question in the support forum (https://forum.pkp.sfu.ca)? That's the best place to get support. If it turns out to be a bug requiring code changes, then it'll come here for work by the dev team.

**Comment by OJSomm** [comment]
Thank you!, @asmecher, I have just post the question in the support forum.
