### ISSUE TITLE
Back-port PHP8.1 compatibility to stable-3_3_0

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8193]
Currently `stable-3_3_0` is not PHP8.1 compatible. Anecdotally on the support forum, encounters with this incompatibility are getting more frequent; it's likely necessary to back-port 8.1 compatibility to `stable-3_3_0` within the LTS lifetime of this release.

PHP 8.1 compatibility with `main` was added in https://github.com/pkp/pkp-lib/issues/7690. This would make a good basis for back-porting.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/3578
- https://github.com/pkp/pkp-lib/pull/8342

**Comment by asmecher** [comment]
@bozana, could you have a look over the PRs in [this comment](https://github.com/pkp/pkp-lib/issues/8193#issuecomment-1281622784)? The goal here was to have a low-risk, low-impact way to add PHP8.1 support (without e.g. compromising PHP7.4 support), so I erred in favour of suppressing deprecation warnings rather than updating dependencies wholesale. The dependencies have already been updated in `main`, which is a more forward-looking approach.

**Comment by bozana** [comment]
@asmecher, that looks all OK to me :-)

**Comment by asmecher** [comment]
All merged!
