### ISSUE TITLE
I can't send email to users but the email for password reset works ok

### ISSUE THREAD

**Issue by pachadotdev** [pkp/pkp-lib#8194]
**Describe the bug**
I can't send email to users but the email for password reset works ok
![image](https://user-images.githubusercontent.com/10091065/185987572-9fbca9a5-75e3-4441-85a3-ba915f6eb107.png)

**To Reproduce**
1. Go to Users & Roles > Users
2. Click on "Email" for any user
3. Try to send an email

But if I reset my own password, I get the email.

**What application are you using?**
 OJS 3.1.2

**Additional information**
`config.inc.php` is correctly configured, I tested by adding the same settings to Thunderbird

**Comment by asmecher** [comment]
@pachadotdev, we're directing support requests to the support forum (https://forum.pkp.sfu.ca); that's the best place to ask a question like this. But just a heads-up that we're not supporting OJS 3.1.x any longer; you'll likely be asked to upgrade first. You might find helpful posts from other users on the forum with older versions of OJS, though.
