### ISSUE TITLE
Add more information about DOI format settings

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8198]
**Describe the problem you would like to solve**
When selecting the DOI format settings, it's not clear what will happen when Default and None are selected.

**Describe the solution you'd like**
It could be useful for a user to provide context information for the Plugin settings options (Default/None). How will the DOI construction be if a user selects any of those?
I.e.
What would happen if a user selected Default?
What would happen if a user selected None?

**Who is asking for this feature?**
This is part of the Crossref feedback for #6062.

**Additional information**
![doi-format](https://user-images.githubusercontent.com/2306629/186372983-4a559a21-d359-46ca-b5cc-717056516525.png)

**Comment by ewhanson** [comment]
Hey @bozana, would you be able to have a look at this? It updates the DOI format settings text to be more descriptive. Thanks!

PRs:

- `pkp-lib`: #8619
- `ojs`: pkp/ojs#3752
- `omp`: pkp/omp#1328
- `ops`: pkp/ops#463

**Comment by bozana** [comment]
@ewhanson, all well, just a minor comment :-) Feel free to merge... Thanks a lot!
