### ISSUE TITLE
Add Crossref submission ID to the DOI management panel

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8199]
**Describe the problem you would like to solve**
It can be difficult to troubleshoot Crossref submission problems with Crossref members because it is not easy to relate the submission in OJS that to the submission in Crossref.

**Describe the solution you'd like**
When a DOI has been submitted to Crossref, include the Crossref submission ID in the DOI management panel. This is different from the submission ID in OJS. If possible, it should link to the submission in the Crossref admin panel:

https://doi.crossref.org/servlet/submissionAdmin?sf=detail&submissionID=1521565335

**Who is asking for this feature?**
This is part of the feedback from Crossref on #6062.

**Additional information**
![crossref-deposited](https://user-images.githubusercontent.com/2306629/186376712-ec081244-9b53-40e5-b72a-81eb06ac9ebf.png)

Perhaps the deposited message could be changed to:

> The metadata for this item has been [submitted to Crossref](https://doi.crossref.org/servlet/submissionAdmin?sf=detail&submissionID=1521565335).

**Comment by ewhanson** [comment]
Hi @bozana, I still need to confirm the `submission_id` field exists in the XML returned from Crossref, but could you have a look at this? Thanks!

PR:

- pkp/crossref-ojs#18

**Comment by ewhanson** [comment]
Merged in for OJS. Will confirm with Crossref on OPS if the URL is the same.

**Comment by ewhanson** [comment]
Hi @bozana, could you have a quick look at pkp/crossref-ops#23. It's the OPS version of pkp/crossref-ojs#18 and should be more-or-less the same. Thanks!

**Comment by bozana** [comment]
Hi @ewhanson, all fine, it can be merged :-)

**Comment by ewhanson** [comment]
Merged!
