### ISSUE TITLE
Mailables may use wrong context when sent in jobs

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8204]
**Describe the bug**
When a `Mailable` is sent as part of a job, the job may be run during a request with a different context or no context at all (eg - CLI). When this happens, a couple of errors can appear:

1. Any email template variables that rely on the request context may use the wrong context, such as URLs.
2. It may use the envelope sender from the wrong context.

**To Reproduce**
1. Set `allow_envelope_sender` to `On` in the config.
3. Set `force_default_envelope_sender` to `Off` in the config. 
4. Go to Settings > Workflow > Emails in one context and set the envelope sender to `a@example.com`.
4. Go to Settings > Workflow > Emails in the second context and set the envelope sender to `b@example.com`.
1. Create a job that sends a mailable with a URL variable (for example, the submission email variable) in context a.
2. Process the job with a request to the second context.
8. See that the email includes a wrong URL in the submission URL variable and the wrong `FROM` header in the email.

Also, from step 6, process the job from the CLI so there is no context and see the resultant errors.

**What application are you using?**
`main` branch (3.4 pre-release)

**Comment by Vitaliy-1** [comment]
PR to pkp-lib: https://github.com/pkp/pkp-lib/pull/8209
Tests: https://github.com/pkp/ojs/pull/3514

**Comment by Vitaliy-1** [comment]
@NateWr, can you take a look?

**Comment by NateWr** [comment]
@Vitaliy-1 I think this solves the problem with the envelope sender but not the email variables. For example, the URLs generated by `SubmissionEmailVariable` still rely on the request context:

https://github.com/pkp/pkp-lib/blob/d0cd5cc32f94906c5bcac0a59e7ea2b6a03889d9/classes/mail/variables/SubmissionEmailVariable.php#L99-L130

**Comment by Vitaliy-1** [comment]
Thanks, I've updated the PRs to rely on the submission's context rather than on the request in email template variables.

**Comment by Vitaliy-1** [comment]
@NateWr, I've moved DAO calls from Mailables/Variables. Can you check if I haven't forgotten anything from what we discussed?  (This is only for OJS and shared library)

**Comment by Vitaliy-1** [comment]
merged
