### ISSUE TITLE
It is not safe to rely on the system's timezone settings

### ISSUE THREAD

**Issue by samueloph** [pkp/pkp-lib#821]
I'm just reporting the error that I received while using https://github.com/lepidus/fullJournalTransfer

ojs2 has produced an error
 Message: WARNING: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
  In file: /srv/http/ojs/lib/pkp/classes/core/Core.inc.php
  At line: 95
  Stacktrace: 
  Server info:
   OS: Linux
   PHP Version: 5.6.14
   Apache Version: N/A
   DB Driver: mysql
   DB server version: 10.0.21-MariaDB-log

Is this usefull?

**Comment by asmecher** [comment]
Hi @samueloph -- there's nothing in OJS to specifically set time zones; your best option is to use a .htaccess PHP configuration directive or edit your system's php.ini configuration file to set the default time zone there.

**Comment by samueloph** [comment]
Hi @asmecher, I'm using a vanilla installation of PHP, it looks like the timezone is not set by default, shouldn't OJS check for it and use "date_default_timezone_set()" if not set, as told by the message?

I found this "PHP 5.3 now requires that you either have a timezone set in your php.ini file or that you pass the desired timezone via the date_default_timezone_set() function before calling the date() function."
https://chrisjean.com/php-5-3-and-system-timezone-settings/

**Comment by asmecher** [comment]
Hi @samueloph -- we could add a config.inc.php setting where you could define a timezone, but that would be an exact duplication of the php.ini setting, so we've opted not to do it for now. It would make sense if there were some other logic affecting the time zone setting, such as a user-specific time zone option, but we haven't had sufficient call for that yet.

**Comment by samueloph** [comment]
@asmecher I didn't make the tests myself, but it looks there are cases where not checking for this causes performance losses (http://php.net/manual/pt_BR/function.date-default-timezone-set.php).

I was thinking in a different approach, something like checking if the timezone is set (ini_get), if not, set it as "UTC" in Core.inc.php (ini_set), as this would be the chosen one anyway, as seen in "We selected the timezone 'UTC' for now".

But I'm not as experienced in PHP as you guys, Am I going in the right direction?

**Comment by asmecher** [comment]
IMO the best behavior would be to throw a warning -- which is exactly what PHP is already doing. The performance differences noted on the PHP site comments won't be noticeable; dates are rarely fetched in OJS. But if you'd like to propose something in a pull request, I'd be happy to take a look.
