### ISSUE TITLE
Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry for key ‘plugin_settings_pkey

### ISSUE THREAD

**Issue by my5660** [pkp/pkp-lib#8213]
**Describe the bug**
When trying to upgrade from OJS 3.2.1-4 to 3.3.0-111 I get the errors Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry ‘index-6-blockTitle’ for key ‘plugin_settings_pkey

**To Reproduce**
1. upgrade from Full Package
2. run nohup php tools/upgrade.php upgrade > upgrade.log &
3. seem like plugin_settings reproduce duplicate value

**What application are you using?**
 OJS 3.3.0-11 TLS

**Additional information**
2022-08-25 22:44:51 [pre-install]
2022-08-25 22:44:51 [load: upgrade.xml]
2022-08-25 22:44:51 [version: 3.3.0.11]
2022-08-25 22:44:51 [code: Installer Installer::checkPhpVersion]
2022-08-25 22:44:51 [code: Installer Installer::installDefaultNavigationMenus]
WARNING: The NavigationMenu (ContextId: 2, Title: User Navigation Menu, Area: user) will be skipped because the specified area has already a NavigationMenu attached.
WARNING: The NavigationMenu (ContextId: 2, Title: Primary Navigation Menu, Area: primary) will be skipped because the specified area has already a NavigationMenu attached.
[....]
2022-08-25 22:44:51 [migration: PKPv3_3_0UpgradeMigration]
Removing orphaned submission_files entry ID 1444 with submission_id 687
Removing orphaned submission_files entry ID 1381 with submission_id 724
Removing orphaned submission_files entry ID 1382 with submission_id 724
Removing orphaned submission_files entry ID 1437 with submission_id 724
A submission file was expected but not found at journals/1/articles/5/submission/5-1-2-1-2-20191105.pdf.
A submission file was expected but not found at journals/1/articles/6/submission/6-1-4-1-2-20191105.pdf.
A submission file was expected but not found at journals/1/articles/7/submission/7-1-6-1-2-20191105.pdf.
[....]
Removing orphaned review_files entry with review_id ID 33 and submission_file_id 1306
Removing orphaned review_files entry with review_id ID 56 and submission_file_id 1591
[....]
ERROR: Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'index-6-blockTitle' for key 'plugin_settings_pkey' (SQL: insert into `plugin_settings` (`context_id`, `plugin_name`, `setting_name`, `setting_type`, `setting_value`) values (1, menusidebar, blockTitle, object, a:1:{s:5:"en_US";s:11:"menusidebar";}), (1, flagcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"flagcounter";}), (1, barcode, blockTitle, object, a:1:{s:5:"en_US";s:7:"barcode";}), (1, visitor, blockTitle, object, a:1:{s:5:"en_US";s:7:"visitor";}), (1, citednessinscopus, blockTitle, object, a:1:{s:5:"en_US";s:17:"citednessinscopus";}), (1, journaltemplate, blockTitle, object, a:1:{s:5:"en_US";s:15:"journaltemplate";}), (1, partnership, blockTitle, object, a:1:{s:5:"en_US";s:11:"partnership";}), (1, sinta_acredited, blockTitle, object, a:1:{s:5:"en_US";s:15:"sinta_acredited";}), (1, statindeks, blockTitle, object, a:1:{s:5:"en_US";s:10:"statindeks";}), (2, sidebarmenu, blockTitle, object, a:1:{s:5:"en_US";s:11:"sidebarmenu";}), (2, collapsepanel, blockTitle, object, a:1:{s:5:"en_US";s:13:"collapsepanel";}), (2, indexing, blockTitle, object, a:1:{s:5:"en_US";s:8:"indexing";}), (2, references, blockTitle, object, a:1:{s:5:"en_US";s:10:"references";}), (2, template, blockTitle, object, a:1:{s:5:"en_US";s:8:"template";}), (2, sertifikat, blockTitle, object, a:1:{s:5:"en_US";s:10:"sertifikat";}), (2, visitor, blockTitle, object, a:1:{s:5:"en_US";s:7:"visitor";}), (3, template, blockTitle, object, a:1:{s:5:"en_US";s:8:"template";}), (3, indexed, blockTitle, object, a:1:{s:5:"en_US";s:7:"indexed";}), (3, plagiarism, blockTitle, object, a:1:{s:5:"en_US";s:10:"plagiarism";}), (3, mendeley, blockTitle, object, a:1:{s:5:"en_US";s:8:"mendeley";}), (3, visitorcounter, blockTitle, object, a:1:{s:5:"en_US";s:14:"visitorcounter";}), (3, menu, blockTitle, object, a:1:{s:5:"en_US";s:4:"menu";}), (3, akreditasi, blockTitle, object, a:1:{s:5:"en_US";s:10:"akreditasi";}), (3, authorguidelines, blockTitle, object, a:1:{s:5:"en_US";s:16:"authorguidelines";}), (4, indexed, blockTitle, object, a:1:{s:5:"en_US";s:7:"indexed";}), (4, plagiarism, blockTitle, object, a:1:{s:5:"en_US";s:10:"plagiarism";}), (4, statcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"statcounter";}), (4, menu, blockTitle, object, a:1:{s:5:"en_US";s:4:"menu";}), (4, visitorflag, blockTitle, object, a:1:{s:5:"en_US";s:11:"visitorflag";}), (4, references, blockTitle, object, a:1:{s:5:"en_US";s:10:"references";}), (4, newsidebar, blockTitle, object, a:1:{s:5:"en_US";s:10:"newsidebar";}), (5, menu, blockTitle, object, a:1:{s:5:"en_US";s:4:"menu";}), (5, index, blockTitle, object, a:1:{s:5:"en_US";s:5:"index";}), (5, tools, blockTitle, object, a:1:{s:5:"en_US";s:5:"tools";}), (5, pict-akreditasi, blockTitle, object, a:1:{s:5:"en_US";s:15:"pict-akreditasi";}), (5, blank-1, blockTitle, object, a:1:{s:5:"en_US";s:7:"blank-1";}), (5, template, blockTitle, object, a:1:{s:5:"en_US";s:8:"template";}), (5, referensi, blockTitle, object, a:1:{s:5:"en_US";s:9:"referensi";}), (6, menu, blockTitle, object, a:1:{s:5:"en_US";s:4:"menu";}), (6, index, blockTitle, object, a:1:{s:5:"en_US";s:5:"index";}), (6, tools, blockTitle, object, a:1:{s:5:"en_US";s:5:"tools";}), (6, template, blockTitle, object, a:1:{s:5:"en_US";s:8:"template";}), (6, statcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"statcounter";}), (6, index, blockTitle, object, a:1:{s:5:"en_US";s:5:"index";}), (7, menu, blockTitle, object, a:1:{s:5:"en_US";s:4:"menu";}), (7, index, blockTitle, object, a:1:{s:5:"en_US";s:5:"index";}), (7, tools, blockTitle, object, a:1:{s:5:"en_US";s:5:"tools";}), (7, statcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"statcounter";}), (8, aboutjournal, blockTitle, object, a:1:{s:5:"en_US";s:12:"aboutjournal";}), (8, user, blockTitle, object, a:1:{s:5:"en_US";s:4:"user";}), (8, index, blockTitle, object, a:1:{s:5:"en_US";s:5:"index";}), (8, visitor, blockTitle, object, a:1:{s:5:"en_US";s:7:"visitor";}), (8, citation, blockTitle, object, a:1:{s:5:"en_US";s:8:"citation";}), (9, sidebar, blockTitle, object, a:1:{s:5:"en_US";s:7:"sidebar";}), (9, newsidebar, blockTitle, object, a:1:{s:5:"en_US";s:10:"newsidebar";}), (10, plagiarism, blockTitle, object, a:1:{s:5:"en_US";s:10:"plagiarism";}), (10, articletemplate, blockTitle, object, a:1:{s:5:"en_US";s:15:"articletemplate";}), (10, menu, blockTitle, object, a:1:{s:5:"en_US";s:4:"menu";}), (10, statcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"statcounter";}), (10, refrence, blockTitle, object, a:1:{s:5:"en_US";s:8:"refrence";}), (10, issn, blockTitle, object, a:1:{s:5:"en_US";s:4:"issn";}), (10, gambar, blockTitle, object, a:1:{s:5:"en_US";s:6:"gambar";}), (11, aboutthejournal, blockTitle, object, a:1:{s:5:"en_US";s:15:"aboutthejournal";}), (11, issn, blockTitle, object, a:1:{s:5:"en_US";s:4:"issn";}), (11, index, blockTitle, object, a:1:{s:5:"en_US";s:5:"index";}), (11, statcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"statcounter";}), (11, flagcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"flagcounter";}), (12, menu, blockTitle, object, a:1:{s:5:"en_US";s:4:"menu";}), (12, flagcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"flagcounter";}), (12, tools, blockTitle, object, a:1:{s:5:"en_US";s:5:"tools";}), (12, statcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"statcounter";}), (12, issn, blockTitle, object, a:1:{s:5:"en_US";s:4:"issn";}), (12, index, blockTitle, object, a:1:{s:5:"en_US";s:5:"index";}), (13, menu, blockTitle, object, a:1:{s:5:"en_US";s:4:"menu";}), (13, upload, blockTitle, object, a:1:{s:5:"en_US";s:6:"upload";}), (13, plagirism, blockTitle, object, a:1:{s:5:"en_US";s:9:"plagirism";}), (13, template, blockTitle, object, a:1:{s:5:"en_US";s:8:"template";}), (13, reference, blockTitle, object, a:1:{s:5:"en_US";s:9:"reference";}), (13, statcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"statcounter";}), (13, bg, blockTitle, object, a:1:{s:5:"en_US";s:2:"bg";}), (13, e-issn, blockTitle, object, a:1:{s:5:"en_US";s:6:"e-issn";}), (13, indeks, blockTitle, object, a:1:{s:5:"en_US";s:6:"indeks";}), (13, indeks2, blockTitle, object, a:1:{s:5:"en_US";s:7:"indeks2";}), (14, menu_utama, blockTitle, object, a:1:{s:5:"en_US";s:10:"menu_utama";}), (14, template, blockTitle, object, a:1:{s:5:"en_US";s:8:"template";}), (14, plagiarism-detection, blockTitle, object, a:1:{s:5:"en_US";s:20:"plagiarism-detection";}), (14, reference_management, blockTitle, object, a:1:{s:5:"en_US";s:20:"reference_management";}), (14, visitor-counter, blockTitle, object, a:1:{s:5:"en_US";s:15:"visitor-counter";}), (14, call-editor, blockTitle, object, a:1:{s:5:"en_US";s:11:"call-editor";}), (15, menu, blockTitle, object, a:1:{s:5:"en_US";s:4:"menu";}), (15, menu_1, blockTitle, object, a:1:{s:5:"en_US";s:6:"menu_1";}), (16, sidemenu, blockTitle, object, a:1:{s:5:"en_US";s:8:"sidemenu";}), (16, counter, blockTitle, object, a:1:{s:5:"en_US";s:7:"counter";}), (16, plagiarism, blockTitle, object, a:1:{s:5:"en_US";s:10:"plagiarism";}), (16, rference, blockTitle, object, a:1:{s:5:"en_US";s:8:"rference";}), (16, uploadartikel, blockTitle, object, a:1:{s:5:"en_US";s:13:"uploadartikel";}), (17, sidebar, blockTitle, object, a:1:{s:5:"en_US";s:7:"sidebar";}), (17, statcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"statcounter";}), (18, statcounter, blockTitle, object, a:1:{s:5:"en_US";s:11:"statcounter";}), (18, schoolar, blockTitle, object, a:1:{s:5:"en_US";s:8:"schoolar";}), (18, mainmenu, blockTitle, object, a:1:{s:5:"en_US";s:8:"mainmenu";}), (18, template, blockTitle, object, a:1:{s:5:"en_US";s:8:"template";}), (18, etichal, blockTitle, object, a:1:{s:5:"en_US";s:7:"etichal";}), (18, copyright, blockTitle, object, a:1:{s:5:"en_US";s:9:"copyright";}), (18, eissn, blockTitle, object, a:1:{s:5:"en_US";s:5:"eissn";}), (19, visitors, blockTitle, object, a:1:{s:5:"en_US";s:8:"visitors";}), (19, template, blockTitle, object, a:1:{s:5:"en_US";s:8:"template";}), (19, scholar, blockTitle, object, a:1:{s:5:"en_US";s:7:"scholar";}), (19, analitic, blockTitle, object, a:1:{s:5:"en_US";s:8:"analitic";}), (19, sidebar, blockTitle, object, a:1:{s:5:"en_US";s:7:"sidebar";}))

Anyone could help me?

**Comment by asmecher** [comment]
@my5660, I see you've already posted this question on the support forum (https://forum.pkp.sfu.ca/t/upgrade-failed-db-sqlstate-23000-integrity-constraint-violation-1062-duplicate-entry-index-6-blocktitle-for-key-plugin-settings-pkey/74504) -- that's the best place to get help. I'll close this issue.
