### ISSUE TITLE
¿Bug? usageStats

### ISSUE THREAD

**Issue by gurumelo** [pkp/pkp-lib#8216]
**Describe the bug**
Enable/disable UsageStats when you have a journal with id=2

**To Reproduce**
1. OJS 3.3.X fresh install
2. Create a journal id=1
3. Disable plugin usagestats (if it's enabled)
4. Create a new journal id=2
5. Delete journal id=1 ( Important :1234: )
6. Go to Settings → Website → Plugins
7. You can't enable usageStats

**Comment by touhidurabir** [comment]
@gurumelo with the latest version of `OJS 3.3.0-13` the `Usage Statistics` plugin should be by default enabled and can not be disabled as that is supposed to be the right behaviour . can you try to upgrade to the latest version of `3.3.X` that is to `3.3.0-13` to see if this get resolved or not as with my current installation of `3.3.0-13` I could not produce this issue .

**Comment by bozana** [comment]
Ah, I think I know where the problem could be:
The usageStats plugin is an site-wide plugin and can be enabled/disabled only by the admin. If the installation has only one journal the admin (site-wide) settings are in the same place as for journal managers, under journal's  Website > Plugins. If the installation has more than one journal, the admin (site-wide) settings are under Administration > Site Settings > Plugins.
@touhidurabir, could you please maybe check if that all works correctly when you do the steps listed above?

**Comment by bozana** [comment]
@touhidurabir, I've just seen all this with the latest stable_3_3_0 branch and you are right -- now the Usage Stats Plugin cannot be disabled and this problem seems not to occur any more.
Thus, I think we can close the issue...
@gurumelo, if you still encounter the issue after upgrading to the latest stable release, please re-open the issue...

**Comment by touhidurabir** [comment]
> now the Usage Stats Plugin cannot be disabled and this problem seems not to occur any more.

@bozana thanks for confirming it . that is what I am experiencing when I am testing it and thats why I can not reproduce it on the latest stable `3.3.0-13` . 

@gurumelo as I have suggested before and also @bozana in last comment , please upgrade to the latest stable version to see if this get resolved. I am closing this now but re-open it if the issue still persist .
