### ISSUE TITLE
Wrong URL when exporting and registering DOIs via command line

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#822]
$url = $router->url($request, null,... i.e. $request->url(null, ... leads to 'index' instad of the actual journal path in the URL, when export and registration is executed via command line.
S. also http://forum.pkp.sfu.ca/t/doi-registration-not-working-via-command-line/4585

**Comment by bozana** [comment]
I forgot one more change for the CrossRef, thus the last reference is the right one...

**Comment by asmecher** [comment]
Merged and cherry-picked to ojs-dev-2_4, thanks!
