### ISSUE TITLE
Update API Key related cypress test

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8223]
**Describe the bug**
API Key related cypress tests need update to handle the api key deletion process before creating one so that it does not conflict already existing API Key . 

**To Reproduce**
1. Login as author/manager
2. Go to `Edit Profile --> API KEY` . 
3. If no `API KEY` already available, create one .
4. Run the specific cypress `API.spec.js` and see that it failing at `creates API Key`.

**What application are you using?**
 OJS, OMP or OPS `main` branch

**Additional information**
This is probably the reason travis builds are failing with following error 
```
API tests
       Configures an author's API key:
     AssertionError: Timed out retrying: Expected to find element: `form[id="apiProfileForm"] button:contains("Create API Key")`, but never found it.
      at Context.eval (http://localhost/__cypress/tests?p=cypress/tests/integration/API.spec.js:27:8)
```

**Comment by touhidurabir** [comment]
PRs 
[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#8223 API test update](https://github.com/pkp/pkp-lib/pull/8224)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#8223 API test update](https://github.com/pkp/ojs/pull/3521)

@asmecher if the tests passes, I will forward port it to `OMP` and `OPS`. Hope this fix the build failing in the `main` branch .

**Comment by touhidurabir** [comment]
@asmecher As the `OJS`. travis build test has passed , I have forward port the changes for `OPS` and `OMP`. all PRs

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8224
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3521
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1192
[ops](https://github.com/touhidurabir/ops) --> https://github.com/pkp/ops/pull/342

**Comment by asmecher** [comment]
All merged; thanks, @touhidurabir!
