### ISSUE TITLE
Custom email templates not present in Notify form after upgrade

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#8230]
**Describe the bug**
After upgrading from OJS 3.1.2 to OJS 3.3.0.11, completely custom email templates that used to be present in the stage participant notify form are no longer available in the email template dropdown menu. 

**To Reproduce**
1. Go to Settings > Workflow > Emails > Email Templates and create a new custom email template.
3. Go to a submission and click Notify next to a participant
4. See in the list of template options for the message the custom template is not there.
5. Edit the base PKPStageParticipantNotifyForm class and remove or comment out the isCustom parameter in the `fetch` method.
6. Reload the Notify form.  Your custom template will be there.

**What application are you using?**
 OJS 3.3.0.11 upgraded from 3.3.0-11. The bug does not appear in new 3.3.0-11 installs.

**Additional Information**
I've investigated this and discovered that `controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php` performs two calls to the email template service. The first call is for any custom templates, the second is for templates appropriate to the workflow stage in question.  These two fetches are merged together. 

The first fetch passes in an isCustom flag to the email template service:

https://github.com/pkp/pkp-lib/blob/stable-3_3_0/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php#L77

Which is used by `classes/services/queryBuilders/PKPEmailTemplateQueryBuilder.inc.php` to add an extra constraint on the query:

https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/services/queryBuilders/PKPEmailTemplateQueryBuilder.inc.php#L315

However, because the `can_disable` column in `email_templates_default` cannot be null, this constraint results in the query returning no records.  Commenting out the isCustom flag that is being passed into the email template service results in all of the custom email templates being correctly returned and available in the Notify form. 

With `isCustom` passed in:

![Screenshot at 2022-09-01 09-19-11](https://user-images.githubusercontent.com/218719/187913428-8ba2f8a7-9eb9-44c5-9982-c2a8f9c3cb47.png)

With `isCustom` removed:

![Screenshot at 2022-09-01 09-18-36](https://user-images.githubusercontent.com/218719/187913497-676c9c65-8e06-4ec1-a7f3-7938e0b2c2d4.png)

Seen in 3.3.0.11.  Also confirming that removing the isCustom parameter solves the problem as far as our client is concerned.

**Comment by NateWr** [comment]
@jnugent I tried to reproduce this in 3.3.0-11 but couldn't. I tried on the test drive install as well and my custom template appeared in the notify form. (I updated the reproduction steps above with my exact steps, maybe I did something wrong?)

I'm guessing this only effects upgrades from 3.1.2? Maybe the custom email template has to be created in 3.1.2? Do you have a sample database you could give me with this problem?

**Comment by jnugent** [comment]
Hi @NateWr  I can provide you with a database, no problem.  I'll reach out via MM.

**Comment by asmecher** [comment]
@jnugent, can you send me a copy of the DB? I can take a look, thanks.

**Comment by asmecher** [comment]
This turned out to be a data issue in the 3.1.2 database (possibly predating even that). Custom email templates should not have corresponding entries in the `email_templates_default` database table (this is how they are distinguished from built-in templates). However, they did exist in this database. Deleting them results in the templates appearing as expected in the "notify" drop-down.

I suspect the templates were created using the Translator plugin, or with some kind of manual intervention.
