### ISSUE TITLE
Consider valid spacial characters in DOI suffix

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8231]
For stable-3_3_0 this was fixed with this issue: https://github.com/pkp/pkp-lib/issues/7595, but it needs to be considered in the new DOI code too.

**Describe the bug**
Starting in OJS 3.3, all special characters present in a journal acronym are stripped from the DOI suffix - as per https://github.com/pkp/pkp-lib/issues/5505

This includes the characters that are recognized as [valid by Crossref](https://www.crossref.org/documentation/member-setup/constructing-your-dois/#afewrules), in particular: "hyphen, period, underscore, semicolon, parentheses, forward slash".

**To Reproduce**
1. Add a journal acronym with a hyphen or another permitted character to the masthead
2. Generate a DOI for an article
3. See DOI generated with no permitted character

**What application are you using?**
 OJS 3.3

**Additional information**
-

**Comment by ewhanson** [comment]
Hey @bozana, could you have a look at this? It adds in the DOI suffix character validation for the DOI via the DOI repository as implemented in #5505. It also adds a hook so individual registration agency plugins can override the regex for valid characters as needed. Thanks!

PRs:

- `pkp-lib`: #8381 
- `ojs`: pkp/ojs#3591
- `omp`: pkp/omp#1232
- `ops`: pkp/ops#379

**Comment by bozana** [comment]
Hi @ewhanson, yes, that all looks good. Would you like to rebase and merge once the tests pass (I think OMP tests are sometimes not accurate)?

**Comment by ewhanson** [comment]
Hi @bozana, thanks for the review. Yes, I'll take a look at the tests and do that once the tests are passing.
