### ISSUE TITLE
Custom locale plugin - Error in function's signature 

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#8232]
**Describe the bug**
On a clean OJS 3.3.0-11 custom locale plugin fails when you try to edit the files. Error is:

```
PHP Fatal error:  Declaration of LocaleFileForm::fetch($request) must be compatible with 
Form::fetch($request, $template = null, $display = false) in 
/var/www/html/plugins/generic/customLocale/controllers/grid/form/LocaleFileForm.inc.php on line 40
```

**To Reproduce**
1. go to the galley and install&enable "Custom Locale" plugin.
2. go to the plugin tab (Settings > Website > Locales"
3. try to edit any of the existing files.
4. See the error in frontend: "Failed Ajax request or invalid JSON returned" (with 500 error)
5. See the error in backend yelling about line 40 call.

**What application are you using?**
 OJS 3.3.0-11

**Solution**

Looks like is an error in the function call so following the error indications is enough to make it work:
Replacing line 40 at /var/www/html/plugins/generic/customLocale/controllers/grid/form/LocaleFileForm.inc.php

FROM: `fetch($request)`
TO: `fetch($request, $template = null, $display = false)`

**Fixes the issue.**

PD: I would contrib with a PR but I couldn't find customLocale code in ojs or [pkp-lib repo](https://github.com/pkp/ojs/tree/main/plugins/generic).

**Comment by jonasraoni** [comment]
Hi @marcbria!

I've just checked the plugin and found this commit on its `stable-3_3_0` branch: https://github.com/pkp/customLocale/commit/5f9ae4de53d9f350cd8567b4b24f30b1425a34d7, which seems to address the issue you had.

**Comment by jonasraoni** [comment]
So, looks like we just need to release a new version of the plugin, as the [tag `v1_1_0-1` doesn't have the fix](https://github.com/pkp/customLocale/blob/v1_1_0-1/controllers/grid/form/LocaleFileForm.inc.php). :)

**Comment by marcbria** [comment]
No hurry at all.

Thanks Jonas!

**Comment by jonasraoni** [comment]
A couple of releases have been pushed, so closing this one 😁
