### ISSUE TITLE
Show Role Title in Contributor List works in issue table of contents but not on article metadata page (OJS 3.3.0.11)

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/pkp-lib#8245]
**Describe the bug**
If I check "show role title in contributor list" in the Role Options for a given Role (`Users & Roles > Roles`), those role titles appear in the contributor list in the issue table of contents ([example](https://lobo.journals.yorku.ca/index.php/default/issue/view/9)) but not in the contributor list for the article's metadata ([example](https://lobo.journals.yorku.ca/index.php/default/article/view/23)). The role titles should probably appear on the article metadata page as well.

**To Reproduce**
1. Go to `Users & Roles > Roles`
2. Click 'Edit' for the Author or Translator roles
3. Scroll down to 'Role Options'
4. Click the box for 'Show role title in contributor list'
5. Click 'OK'
6. Compare the contributor lists in a published issue's table of contents with the contributor list in a published article (see examples linked above)

**What application are you using?**
 OJS 3.3.0.11

**Additional information**
Sorry, I feel like this is nitpicky but it would be really useful for certain types of journals.

**Comment by asmecher** [comment]
@tmrozewski-york, I think this is a duplicate of https://github.com/pkp/pkp-lib/issues/5739.

**Comment by tmrozewski-york** [comment]
@asmecher yeah, it looks like that item covers this issue (and others besides). Sorry I didn't catch that when searching for a duplicate before logging this.

**Comment by asmecher** [comment]
Not a problem, the issue list is daunting and often hard to search!
