### ISSUE TITLE
Add font-display: swap to use system fonts until font files are loaded

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8246]
**Describe the problem you would like to solve**
Until the font files are loaded in the browser, the text will remain invisible. This can be especially problematic when the request takes a long time to return.

**Describe the solution you'd like**
Add `font-display: swap` to all places where we load fonts (`@font-face`) so that text is shown in the system font until the custom fonts are loaded.

**Who is asking for this feature?**
@lucasDevLepidus https://github.com/pkp/pkp-lib/pull/8244

**Additional information**
This should be implemented for all font loading files, including those in the default theme and PKP's custom themes. In the default theme, fonts are loaded in `plugins/themes/default/styles/fonts/*.less`. The other themes to be updated are `classic`, `healthSciences`, `immersion` and `pragma`.

**Comment by NateWr** [comment]
Initial PR from @lucasDevLepidus is here: https://github.com/pkp/pkp-lib/pull/8244

**Comment by NateWr** [comment]
PRs:
- [OJS](https://github.com/pkp/ojs/pull/3551)
- [OPS](https://github.com/pkp/ops/pull/358)
- [OMP](https://github.com/pkp/omp/pull/1209)

**Comment by NateWr** [comment]
Thanks @lucasDevLepidus. I have merged those PRs to `stable-3_3_0` and cherry-picked the commits to the `main` branches.

**Comment by lucasDevLepidus** [comment]
Alright @NateWr

I'm happy to contribute.
