### ISSUE TITLE
One-click Reviewer Access provides full access to reviewer account

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#8247]
**Describe the bug**
When enabling the feature "One-click Reviewer Access" a link containing a special access key is send to the reviewer to easily access the submission he/she is invited to review.

The description of the feature states: "Reviewers can be sent a secure link in the email invitation, which will allow them to access the review without logging in. Access to other pages requires them to log in."

However, when using the provided URL the reviewer gains full access to his/her account and is able to edit the profile or create new submissions.

Either the description is incorrect or the feature is not implemented as intended.

**To Reproduce**
1. Enable the "One-click Reviewer Access" feature
2. Create a review round inviting a reviewer
3. Use the link provided in the invitation mail to access the review
4. Use "⟵ Back to Submissions" on the top left corner to gain full access to the reviewer account

**What application are you using?**
Tested on OJS 3.3.0-11
A customer recognized this behaviour on OJS 3.1.2-4

**Comment by NateWr** [comment]
I believe the description is incorrect. @asmecher do you know if this has always been the case? Or did this behavior change at some point?

**Comment by asmecher** [comment]
Yes, in OJS 2.x the reviewer access key was limited to just the review process. It was implemented here:
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/pages/reviewer/ReviewerHandler.inc.php#L102
All user object fetches in the review process derived from this code.

In OJS 3.x it's no longer the case; the access key grants complete access to the reviewer's account.

**Comment by NateWr** [comment]
I've updated the description.

![one-click](https://user-images.githubusercontent.com/2306629/190117009-94312086-17ec-4adc-82f0-241aa9d99317.png)

@asmecher sorry, this is another one where I'm not quite sure what to do about the translations. This fix will go into `stable-3_3_0`, and I've marked the appropriate locale keys `#, fuzzy`. But will translators know to update this?

PRs:
https://github.com/pkp/ojs/pull/3543
https://github.com/pkp/omp/pull/1203

**Comment by NateWr** [comment]
Ok, I've merge this to `stable-3_3_0` and cherry-picked it to `main` and the translations can get sorted out later. Thanks for reporting, @ronste!
