### ISSUE TITLE
Unable to remove journals on OJS 3.3.0 after importing with native xml plugin

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#8253]
**Describe the bug**
On a clean OJS 3.3.0-11, I create a new journal and then I full enable 2 langs (UI, Forms & Submission).
I follow the full workflow and I publish a new issue with 1 article associated to ART section.
Then I export this issue with the native import&export plugins.

In same OJS I create a second journal with 2 langs full enabled and I use the native import&export plugins to import the content of the first journal. 

When I try to remove the second journal I, if get got error:

```
PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedAbbrev() on null in /var/www/html/classes/article/ArticleTombstoneManager.inc.php:31
```

**What application are you using?**
 OJS 3.3.0-11

**Comment by marcbria** [comment]
Tried to remove (without success)...
- Filling all section lang names and abbr.
- Changing default primary lang.

Full error stack trace is:

```
#0 /var/www/html/classes/article/ArticleTombstoneManager.inc.php(58): ArticleTombstoneManager->insertArticleTombstone(Object(Submission), Object(Journal))
#1 /var/www/html/classes/services/ContextService.inc.php(134): ArticleTombstoneManager->insertTombstonesByContext(Object(Journal))
#2 /var/www/html/lib/pkp/classes/plugins/HookRegistry.inc.php(107): APP\Services\ContextService->beforeDeleteContext('Context::delete...', Array)
#3 /var/www/html/lib/pkp/classes/services/PKPContextService.inc.php(503): HookRegistry::call('Context::delete...', Array)
#4 /var/www/html/lib/pkp/controllers/grid/admin/context/ContextGridHandler.inc.php(265): PKP\Services\PKPContextService->delete(Object(Journal))
#5 /var/www/html/lib/pkp/classes/core/PKPRouter.inc.php(395): ContextGridHandler->deleteContext(Array, Object(Request))
#6 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#7 /var/www/html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route(Object(Request))
#8 /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))
#9 /var/www/html/index.php(68): PKPApplication->execute()
#10 {main}
  thrown in /var/www/html/classes/article/ArticleTombstoneManager.inc.php on line 31
```

**Comment by asmecher** [comment]
Oh, NVM, I see it's in the first part of the entry.

**Comment by marcbria** [comment]
When I removed all articles (unpublish > assign editor > refuse the article > delete), I could remove the journal.

BTW, my report was partial. A fellow just explained me that one of the articles I exported, was initially published with quicksubmit.
So the issue is somewhere between multilang + quicksubmit + native xml import/export. :-(

Alec, I know you all have your hands full so what about closing it till I could report in a more detailed way?

**Comment by asmecher** [comment]
I believe this will be resolved with https://github.com/pkp/pkp-lib/issues/6093 in OJS 3.4; since journal deletion is a very very uncommon task, I don't mind leaving it unresolved in LTS.

**Comment by marcbria** [comment]
I suspect won't be as uncommon in big installations that have testing journals that like to clean up from time to time.

My guess is this is caused by quicksubmit + i18n + native xml import/export combination, that miss exporting data that is essential and breaks DB integrity... 

But let's close it till we find time to discover how to reproduce the issue.

Thanks for your time Alec.
