### ISSUE TITLE
Add more context and documentation to Crossref setup/credentials 

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#8258]
**Describe the problem you'd like to solve**
The Crossref plugin settings page is a frequent source of misunderstandings or user error. Additionally, there are _two different ways, potentially_ that user credentials might need to be entered depending on the Crossref membership. In short, Crossref have been transitioning from a system where members all share one login to a system in which multiple members can login to represent a membership. The instructions on the plugin page should be as clear as possible. 

**Describe the solution you'd like**
Crossref has specific documentation for OJS-using members. My recommendation is we just put as much of this as makes sense in our settings page. 

https://www.crossref.org/documentation/content-registration/ojs-plugin/ 

This is pretty comprehensive. I don't think we necessarily need to list the other plugins, though. But maybe it wouldn't hurt to let people know they have other things they can enable? Maybe a collapseable list of the other plugins. 

**Who is asking for this feature?**
This is part of the Crossref feedback for #6062.

**Comment by NateWr** [comment]
@AhemNason we're going to need a more detailed proposal before we're ready to begin work. I'm going to close this for now, but if you can draft the language for the settings form fields and description, the actual implementation won't be very difficult and I can re-open this.

**Comment by AhemNason** [comment]
**Describe the Solution You'd Like**

<img width="1041" alt="OJS-DOIs-Crossref-settings" src="https://user-images.githubusercontent.com/504276/191330012-0423a6b5-889e-483e-a949-beed80ae1ecc.png">

**Field 1**: _Depositor Name_
Change the text from `Depositor name` to the following: 
`Depositor name: Name of the organization registering the DOIs (note: this field is not authenticated with Crossref).`

**Field 2**: _Depositor Email_
Change the text from `Depositor email` to the following:
`Depositor email: email address of the individual responsible for registering content with Crossref (note: this field is not authenticated with Crossref).`

**Field 3**: _Copy_
Current copy text: 

> If you would like to use this plugin to register Digital Object Identifiers (DOIs) directly with [CrossRef](http://www.crossref.org/) you will need a username and password (available from CrossRef) in order to do so. If you do not have your own username and password you can still export into the CrossRef XML format, but you cannot register your DOIs with CrossRef from within OJS.

Proposed Replacement... 

> If you woud like to use this plugin to register Digital Object Idnetifiers (DOIs) directly with If you plan to set up the plugin to register content with [Crossref](http://www.crossref.org/) you’ll need to add your [Crossref account credentials](https://www.crossref.org/documentation/member-setup/account-credentials/) into the username and password fields below. 
>
> Depending on your Crossref membership, there are two potential ways to populate your username and password: 
> 
> - If you are using organization-wide, shared [role credentials](https://www.crossref.org/documentation/member-setup/account-credentials/#00376), you can simply add in your shared username and password.
> - If you are using personal [user credentials](https://www.crossref.org/documentation/member-setup/account-credentials/#00368) that are unique to you, you’ll need to add your email address and your role into the username field, and your personal password into the password field. Here’s an example of what this will look like:
>
> Username: [email@address.com](mailto:email@address.com)/role
> Password: your Password
> 
> - If you do not know or have access to your Crossref credentials, you can contact [Crossref support](https://support.crossref.org/) for assistance. Without credentials, you may still export metadata into the CrossRef XML format, but you cannot register your DOIs with Crossref from OJS.

**Field 4**: Username
Change the text from `Username` to the following: 
`Username: the Crossref username that will be passed to us to authenticate your submission(s) (please see role versus user credentials above).`

**Field 5**: Password
Change the text from `Username` to the following: 
`Password: the password associated with your Crossref credentials (Note: saved as plain text, i.e. not encrypted).`

**Comment by NateWr** [comment]
Ok thanks. Field 1 and 2 are still unclear to me. Can you say more about how this information is used? Saying it is "not authenticated" only tells me how it is not used. Is this metadata that's part of the deposit? Should the organization be a journal or a publisher or something else?

I'll re-open this and leave it for Erik to review on his return.

**Comment by ewhanson** [comment]
Will be updated as part of #7513.
