### ISSUE TITLE
Email variables not being parsed and replaced in mail preview

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8262]
**Describe the bug**
The email template variable not getting properly parsed and replaced in the mail preview. But in the original sent mail, they are ok . 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any submission and follow through the external review process.
2. Try to invite a new reviewer or try to resend the invitation .
3. See in the `mail preview` right before sending the mail the `{$PLACEHOLDER_VARIABLE}` not getting replaced in the preview .
![CleanShot 2022-09-16 at 12 33 48](https://user-images.githubusercontent.com/2587979/190573226-664d09e2-6b89-4a22-90ac-65a52b736fef.png)

**What application are you using?**
 OJS `main` branch . But this probably also present in the `OMP` and `OPS` `main` branch also . 

**Additional information**
According to @NateWr, this is probably related to this section of code at https://github.com/pkp/pkp-lib/blob/main/controllers/grid/users/reviewer/form/ReviewerNotifyActionForm.php#L74-L87

**Comment by Vitaliy-1** [comment]
Hmm, I'm trying to reproduce it. Is it a new template/functionality that isn't yet on the main branch? The referenced code isn't related (it's for unassign reviewer or reinstate reviewer) and I'm unable to find the template on the screenshot. According to the text, it should appear when the reviewer declines the initial request and the editor is trying to assign a second time, right?

**Comment by touhidurabir** [comment]
@Vitaliy-1 yes, it's a new mailable for the issue pkp/pkp-lib#4789 which still not merged with main yet .

**Comment by Vitaliy-1** [comment]
I'm unable to reproduce it with reviewer-related forms. As for the particular form on the screenshot, I'm making a reminder to take a look after this issue is solved: https://github.com/pkp/pkp-lib/issues/8311

**Comment by touhidurabir** [comment]
@Vitaliy-1 the issue https://github.com/pkp/pkp-lib/issues/8311 has been resolved .

**Comment by Vitaliy-1** [comment]
The variables are replaced as expected on my local instance. I see that already made changes to that part of the code around a month ago, which likely solved the problem. @touhidurabir, feel free to reopen the issue if you are still able to reproduce it.
