### ISSUE TITLE
Wrong translation for username in ./lib/pkp/locale/de_DE/manager.po

### ISSUE THREAD

**Issue by me-kell** [pkp/pkp-lib#8266]
The OJS download files for versions from `3.3.3.0.8` until `3.3.3.0.11` (as offered in https://pkp.sfu.ca/ojs/ojs_download/) 
have a file `./lib/pkp/locale/de_DE/manager.po` that differs from the sources (https://github.com/pkp/pkp-lib/blob/6f673bd0d17c165435063b4acb2397986bfdc98f/locale/de_DE/manager.po#L2026) and with a wrong message variable:

Line #2158 is `msgstr "Sie sind derzeit als {$Benutzername} angemeldet"` in the download files but must be `msgstr "Sie sind derzeit als {$username} angemeldet"`.

**Comment by asmecher** [comment]
This correction will be included in 3.3.0-12, due out shortly. It has already been corrected in `main` (for 3.4.0) via Weblate.
