### ISSUE TITLE
[OMP] Saved modals "eat" an element when reloaded

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#827]
I think this only happens on OMP but haven't checked OJS in a while. When you load a modal with an ajax form, then save that form, and the modal reloads, it will "eat" its containing element. So:

```
<div class="modal">
  <div class="title">Modal Title</div>
  <div class="content">
    <form></form>
  </div>
</div>
```

When saved and the form refreshes, we'll have this structure:

```
<div class="modal">
  <div class="title">Modal Title</div>
  <form></form>
</div>
```

I think I remember something like this happening in OJS, I just want to get it down so it doesn't get forgotten before 1.2 goes out.

**Comment by asmecher** [comment]
OTOH there might be a convention where there's normally a wrapper element in the form template that gets consumed and then re-created when the form is reloaded. Possibly that's missing in some cases.

**Comment by NateWr** [comment]
You were right. It was just the catalog modal that was walking up the dom one level when refreshing. [PR#148](https://github.com/pkp/omp/pull/148)
