### ISSUE TITLE
ReviewFormResponseDAO::insertObject creates an E_NOTICE and stacktrace

### ISSUE THREAD

**Issue by prechelt** [pkp/pkp-lib#8274]
Every call to `insertObject()` makes a call to `update()` that uses a _method call_ for the `&type` parameter, which produces a PHP notice.  
`insertObject()` should be structured like `updateObject()` where a helper variable is used instead.

PRs #8269 and #8270 repair this problem.

**Comment by asmecher** [comment]
Thanks, @prechelt, I've merged both!
