### ISSUE TITLE
Integrity constraint violation during migration of navigation_menu_item_assignment_id

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8279]
**Describe the bug**
Receiving an error during the test upgrade of an OJS instance:
```
ERROR: Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`cypress-master`.`#sql-54a_41`, CONSTRAINT `assignment_settings_navigation_menu_item_assignment_id` FOREIGN KEY (`navigation_menu_item_assignment_id`) REFERENCES `navigation_menu_item_assignme) (SQL: alter table `navigation_menu_item_assignment_settings` add constraint `assignment_settings_navigation_menu_item_assignment_id` foreign key (`navigation_menu_item_assignment_id`) references `navigation_menu_item_assignments` (`navigation_menu_item_assignment_id`) on delete cascade)
```

**To Reproduce**
1. Install OJS stable branch
2. Go to Website settings -> setup -> navigation
3. Add a new custom item
4. Edit primary navigation menu to add the new menu item to the end of the already assigned items
5. See a new entry in a `navigation_menu_item_assignment_settings` table
```
SELECT * FROM `navigation_menu_item_assignment_settings`

navigation_menu_item_assignment_id	locale	setting_name	setting_value	setting_type	
0	en_US	title	CUSTOM	string	
0	fr_CA	title	CUSTOM	string	

```
6. Run an upgrade 

**What application are you using?**
OJS upgrade to the current main

**Additional information**
![menu_assignments](https://user-images.githubusercontent.com/20665587/191327108-517f9836-5290-4129-85eb-533bccd04a2e.png)

**Comment by Vitaliy-1** [comment]
The error can be also reproduced on the clean OJS main branch (without an upgrade) just by saving edit primary navigation menu form

**Comment by diepz** [comment]
@Vitaliy-1, try the following way click `Administration` -> `Clear Data Caches` and `Clear Template Cache`
I hope this could help you.

**Comment by Vitaliy-1** [comment]
I can reproduce this also on a fresh install. Here's a PR that resolves the problem for me: https://github.com/pkp/pkp-lib/pull/8282
What I found is that in my case [PDO::lastInsertId()](https://github.com/pkp/pkp-lib/blob/6f82e69dad1c8d264bfa97eba5cc59c3fba745fa/classes/db/DAO.php#L199) returns `'0'` if executed not after INSERT statement, like in  `NavigationMenuItemAssignmentDAO::insertObject`. 

Also, `DAO::_getInsertId()` accepts no arguments but I see several places, where arguments are passed. e.g.: https://github.com/pkp/pkp-lib/blob/6f82e69dad1c8d264bfa97eba5cc59c3fba745fa/classes/navigationMenu/NavigationMenuItemAssignmentDAO.php#L304. Is the idea to pass it to the `PDO::lastInsertId()` as an argument for a sequence name?

**Comment by asmecher** [comment]
Ah, are you using PostgreSQL? Yes, the ID fetch needs to be executed right after the `INSERT` for PostgreSQL (and it's a good idea in general). Does this resolve it?
```diff
diff --git a/classes/navigationMenu/NavigationMenuItemAssignmentDAO.php b/classes/navigationMenu/NavigationMenuItemAssignmentDAO.php
index 3b7685ecc5..6b3038e81d 100644
--- a/classes/navigationMenu/NavigationMenuItemAssignmentDAO.php
+++ b/classes/navigationMenu/NavigationMenuItemAssignmentDAO.php
@@ -208,6 +208,7 @@ class NavigationMenuItemAssignmentDAO extends \PKP\db\DAO
                 (int) $assignment->getSequence(),
             ]
         );
+        $assignment->setId($this->getInsertId());
 
         // Add default title (of the navigationMenuItem)
         $navigationMenuItemDao = DAORegistry::getDAO('NavigationMenuItemDAO'); /** @var NavigationMenuItemDAO $navigationMenuItemDao */
@@ -215,7 +216,6 @@ class NavigationMenuItemAssignmentDAO extends \PKP\db\DAO
 
         $assignment->setTitle($navigationMenuItem->getTitle(null), null);
 
-        $assignment->setId($this->getInsertId());
         $this->updateLocaleFields($assignment);
 
         $this->unCacheRelatedNavigationMenus($assignment->getId());
```

As for parameters to `getInsertId`, watch out for `_getInsertId` (which is protected and does take parameters) and `getInsertId` (which is public and doesn't).

**Comment by Vitaliy-1** [comment]
Yes, as I referenced in the PR, this resolves the problem. But I was using MySQL to test this issue.
```
mysql  Ver 8.0.30-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
```

> As for parameters to getInsertId, watch out for _getInsertId (which is protected and does take parameters) and getInsertId (which is public and doesn't).

Those arguments aren't used anywhere. The method's signature doesn't accept anything: https://github.com/pkp/pkp-lib/blob/79ebd6d9d4f00da7e0973df4270f0b7ed839c4b2/classes/db/DAO.php#L197. Is the idea to pass `$name` parameter to `PDO::lastInsertId()`?

**Comment by asmecher** [comment]
> Those arguments aren't used anywhere

Ah, you're right. Looking into this, it's a combination of 1) moving from ADODB to Laravel (PDO), and 2) PostgreSQL coming more in line with other DBMSs.

Back when we were using ADODB, PostgreSQL required the name of the table and column in order to determine the sequence used to generate the inserted ID. (See the [footnote on ADODB _insertid](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:insert_id&s[]=insertid).)

Around PHP 7.0, ADODB's implementation of this feature [changed to no longer require](https://github.com/php/php-src/pull/2014) the table/column name. And we moved to Laravel (based on PDO), which also does not require this to be specified.

So we can remove table/column naming. Not a huge priority to go do it, but anyway, it's not used and that's OK.

**Comment by asmecher** [comment]
I've cleaned up the `getInsertId` functions; I see https://github.com/pkp/pkp-lib/pull/8282 has been merged or cherry-picked. I've also back-ported it to `stable-3_3_0`, which doesn't appear to be affected, but no harm done. Closing this issue, thanks!
