### ISSUE TITLE
Announcements placed on homepage may include announcements from other contexts

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8288]
**Describe the bug**
The ~web feed~ (fixed by https://github.com/pkp/pkp-lib/issues/8770) and announcement feed plugins don't strictly enforce a record sorting (notice the behavior of the announcement feed is right at the `stable-3_3_0` branch).

Besides fixing the order, it seems the announcement feed is leaking data across contexts (see: https://forum.pkp.sfu.ca/t/ojs-3-4-0-1-announcement-page-showing-annoucnements-of-all-the-journals/79904).

**Announcement feed**
The behavior at the `stable-3_3_0` branch makes sense, where it's sorted by `date_posted`.
At the `main` branch the expired announcements should probably be hidden, and the announcement collector should probably have the sorting by `date_posted` enabled by default.

~**Web feed**
On the https://github.com/pkp/pkp-lib/issues/7623 (which is a version of the latter plugin for OPS), the last modified date was used to sort the items, perhaps it can be used as a model.~

**Extra**
Check the feasibility of creating a generic feed plugin and share it with the applications (done for the webFeed)

**What application are you using?**
OJS `main` and `stable-3_3_0`

**Comment by asmecher** [comment]
@jonasraoni, I've fixed the data leak aspect of this entry; can you re-file anything remaining in a new issue?

Users of OJS/OMP/OPS 3.4.0-0 or 3.4.0-1 who are encountering this problem can fix it by applying [this patch](https://github.com/pkp/pkp-lib/commit/b1f89ea4d2669c40ca4c3ca1d319721798e08c68.diff) in the `lib/pkp` subdirectory.

**Comment by nils-stefan-weiher** [comment]
I also fixed the sorting by `date_posted` in our local installation.

I can open a pull request for `stable_3_4_0` branch.

**Comment by asmecher** [comment]
@nils-stefan-weiher, excellent, thanks! A PR would be welcome [over here](https://github.com/pkp/pkp-lib/issues/9226#issuecomment-1677658445).
