### ISSUE TITLE
Inclusion of Data Availability Statement as submission metadata

### ISSUE THREAD

**Issue by iudizm** [pkp/pkp-lib#8290]
**Describe the problem you would like to solve**
In issue #6278, @jalperin proposed the inclusion of a "Data Availability Statement" field to enable metadata for datasets to be published alongside articles.

As discussions in that issue expanded to Data Citations and indexing services, we created this child-issue to focus on the inclusion of the Data Availability Statement field.

**Describe the solution you'd like**
Make possible to enable the Data Availability Statement as submission metadata, so it can be requested/required to authors in the submission and revision processes.

It should be visible in the publication public page and also for reviewers.

It would be great to have it in OJS, OPS and OMP.

**Who is asking for this feature?**
As stated by Juan, "it has been a standard feature in virtually all journal submissions systems (in PLOS since 2014)". As the number of datasets published continues to grow, this also becomes a increasing demand from the community.

**Additional information**
There is more context to this in the parent issue: #6278

**Comment by iudizm** [comment]
Are there any acceptance tests that should be implemented for this new submission metadata? if so, how could it be done?

**Comment by asmecher** [comment]
@iudizm, for tests, there are two options:
1. Alter one of the existing submission tests (something in `cypress/tests/data/60-content/`) so that it provides a data availability statement and e.g. checks the reviewer process to ensure that it's present, or
2. Create a new test in e.g. `lib/pkp/cypress/tests/integration/` (if it can be kept application-agnostic) or `cypress/tests/integration/` (if not) that enters a data availability statement in an existing submission in the dataset, and checks an existing review assignment to ensure that it's visible.

I think option 2 will probably be better. You can get a fully built dataset to work with from https://github.com/pkp/datasets -- this is what the Travis CI tests generate for their own testing purposes, before running the integration tests.

**Comment by asmecher** [comment]
@iudizm, if I read it correctly, the attached PRs...
- Add a new field to setup allowing the journal manager to enable / disable / require the Data Availability Statement
- Add a new field for the Data Availability Statement to the submission process, when enabled
- Expose the contents of that field to reviewers when they access the submission metadata in Peer Review

@jalperin, does that match your expectations?

**Comment by jalperin** [comment]
* What about displaying on the abstract page? 
* does exposing to reviewers respect anonymity?

**Comment by iudizm** [comment]
About the presentation of the Data Availability Statement in the landing page of the article/preprint/monograph:

Is the [`main_entry`](https://github.com/lepidus/ojs/blob/ac2dd866b2a8bdf13ef6bb01af8965a1fd471122/templates/frontend/objects/article_details.tpl#L101) the most appropriate place for exposing the statement? 

We have placed it there, because It feels like in some cases, this Statement may be too long to display it in the details in the side bar. 

Also, would like a feedback about placing it directly below the Abstract.

<details><summary>Displaying in 'main' below Abstract</summary>

![main_entry](https://user-images.githubusercontent.com/43123002/192382901-cb786af0-38e1-4ad4-b219-b8fff9db677a.png)

</details>
<details><summary>Displaying in details side bar</summary>
 
![details-entry](https://user-images.githubusercontent.com/43123002/192385908-d31182aa-79a1-41d2-acc1-112a4d1cc7ea.png)

</details>

**Comment by diegoabadan** [comment]
> does exposing to reviewers respect anonymity?

I think you mentioned an important point, @jalperin! Today, this metadata is simply being exposed.

How do you think this flow should be? Should the editor manually choose whether to make this metadata available when it is not an open review?

> What about displaying on the abstract page?

Yes, it is present just below the abstract of the article/preprint/monograph today.

In the comment above, Iudi asks if it looks better this way, or in the side section when viewed in the default theme, as exemplified in the images.

**Comment by jalperin** [comment]
if authors are supposed to remain anonymous, then the metadata should not
be shared with reviews.

I like the sidebar display better than below the abstract.

**Comment by iudizm** [comment]
> I like the sidebar display better than below the abstract.

Ok, moved it to the sidebar display in the PRs to the landing pages.

> if authors are supposed to remain anonymous, then the metadata should not
be shared with reviews.

Right, [just changed it](https://github.com/pkp/pkp-lib/pull/8291/commits/429561b6954bcf7b351eccdfb3474c470b19c09f), now we only expose the Data Availability Statement to the reviewer when the review method **is not** double anonymous (same way used to list the authors)

**Comment by bozana** [comment]
OK, thanks @NateWr! I will take a closer look. And maybe we need to coordinate/check with JII...

**Comment by asmecher** [comment]
My apologies for the delay in responding; I've just gone through for a second review. https://github.com/pkp/pkp-lib/pull/8291#pullrequestreview-1163532478

**Comment by asmecher** [comment]
@NateWr, this will affect the submission wizard for 3.4 as it adds a new field to the submission forms (similar to the other optional metadata fields that can be enabled/disabled in setup). Would you prefer this to be merged after the submission wizard work, or before?

**Comment by asmecher** [comment]
@iudizm, the latest OJS test appears to fail; have you looked this over? https://app.travis-ci.com/github/pkp/ojs/builds/257457389

**Comment by iudizm** [comment]
I believe it is because the failing test expects the submission to already have the Data Availability Statement, which inserted by the [application-agnostic tests from pkp-lib](https://github.com/pkp/pkp-lib/pull/8291/files#diff-bb23160115233ba107b181077d37776cd48b6b08bca81dc34a86f0a99c54cacd), but the [pkp-lib version being used](https://app.travis-ci.com/github/pkp/ojs/jobs/587621143#L460) on the build does not have those tests integrated yet.

**Comment by asmecher** [comment]
@iudizm, I see; it is possible to instruct Travis which `pkp-lib` branch to check out: https://docs.pkp.sfu.ca/dev/testing/en/continuous-integration#prepare-pull-requests-for-testing

However, we have some outstanding work that will overlap with this PR (https://github.com/pkp/pkp-lib/pull/8349). I'd propose that we...
1. Get https://github.com/pkp/pkp-lib/pull/8349 merged first (this may take a few weeks yet).
2. Adapt this PR to suit the testing changes introduced by 8349.
3. Re-run the tests and merge these PRs after that.

**Comment by NateWr** [comment]
@iudizm I'm going to pick this up. Is there a PR for this? If so, can you comment with a link to the PR as well as an explanation of what it does?

**Comment by iudizm** [comment]
OK @NateWr!  Yes, there are PRs to pkp-lib and the applications:

1. The PR to pkp-lib: https://github.com/pkp/pkp-lib/pull/8291
    These changes are intended to:
    * add a metadata settings field for the Data Availability Statement, so it can be required/requested in submission
    * add a submission metadata form field for the Data Availability Statement
    * add the Data Availability Statement metadata to the workflow
    * make the Data Availability Statement available to reviewers in submission details (only when author is disclosed in the review)
    * implement the cypress integrations tests

3. The PRs to the applications:
   * OJS: https://github.com/pkp/ojs/pull/3553
   * OPS: https://github.com/pkp/ops/pull/359 
   * OMP: https://github.com/pkp/omp/pull/1210
   
   These PRs are meant to display the data availability statement in the landing page of the article/preprint/monograph, in the `entry_details` section of the page

**Comment by NateWr** [comment]
Thanks @iudizm! I've rebased your PRs and pulled the commits into my own PR just to make it easier for me to manage. I made a couple of minor changes:

- The data availability statement is now a rich text editor so that people can include links.
- I restructured the tests slightly to keep the code centralized in pkp-lib.

@asmecher I used the cypress config file to conditionally run tests related to reviews in OJS/OMP but not OPS. You can see the [examples](https://github.com/pkp/pkp-lib/pull/8570/files#diff-1f08e976feaf02883b22c77bdf27247e1f8c5eb60f05985d7ab49b9cb1bf7802R27-R47). Just FYI in case you want to avoid this approach.

PRs:
https://github.com/pkp/pkp-lib/pull/8570
https://github.com/pkp/ojs/pull/3724
https://github.com/pkp/omp/pull/1309
https://github.com/pkp/ops/pull/445

**Comment by jalperin** [comment]
Great to see this make it in! Thanks everyone.

**Comment by asmecher** [comment]
> I used the cypress config file to conditionally run tests...

No objections here, thanks; let's watch to see if these start to get too tangled.

**Comment by NateWr** [comment]
All merged to `main`. This will go out with 3.4. Thanks @iudizm!
