### ISSUE TITLE
Enable reprocessing of the older usage stats log files (< 3.4 release) 

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8293]
The current tool for log file reprocessing allows only monthly reprocessing and reprocessing of the log files > 3.4 release, s. https://github.com/pkp/pkp-lib/blob/main/tools/reprocessUsageStatsMonth.php and https://github.com/pkp/pkp-lib/blob/main/classes/task/PKPUsageStatsLoader.php#L330-L333.
Allow also the reprocessing of the older usage stats log files.

PRs

- https://github.com/pkp/pkp-lib/pull/8504
- https://github.com/pkp/ojs/pull/3672 (only submodule update)
- https://github.com/pkp/omp/pull/1285 (only submodule update)
- https://github.com/pkp/ops/pull/421 (only submodule update)

**Comment by bozana** [comment]
@NateWr, could you please take a look at the PRs above?
The workflow for older log files would be like this:

1. The old log files need to be converted into the new format, s. https://github.com/pkp/pkp-lib/issues/6849.
2. All the log files for a month that would like to be reprocessed need to be copied into the folder `usageStats/stage/`. (I require this manual copy of the files on purpose -- for admin to be aware of all of them, but also because theoretically it could be a mix of our internal and Apache log files -- but I could also try to implement it so that the log files are copied by the CLI tool?).
3. The CLI tool `reprocessUsageStatsMonth.php` with the` month (YYYYMM)` as argument needs to be called.

When these old log files are reprocesses also the COUNTER R5 tables/stats will be filled -- everything the same as the reprocessing of the new log files (> 3.4 release). However this will not influence the `dateStart` for the SUSHI reports -- this is still the installation date of the version 3.4 or the first next one. Eventually once we can allow the admin/manager to move that `startDate` manually, for it to be earlier if some earlier month were reprocessed without gaps.
Or maybe I should not fill the COUNTER R5 tables when those old log files are reprocessed? :thinking: 

Thanks a lot!

**Comment by NateWr** [comment]
I've had a look at the code, but I don't understand it. Having read the comment at the top of this issue, I expected this code to support old usage stats logs. Which part of the PR does that?
