### ISSUE TITLE
OJS: Publicating an issue throws an error from fulltext search indexing

### ISSUE THREAD

**Issue by felixhelix** [pkp/pkp-lib#8294]
**Describe the bug**
Publicating a recent issue of one of our journals leads to a halt in the publication with some articles unpublished and the following error in the php log file:

`PHP Fatal error: Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9D\x90\xB9\xF0\x9D...' for column ojs.submission_search_keyword_list.keyword_text at row 1 in /var/www/html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115\nStack trace:\n#0 /var/www/html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(115): PDOStatement->execute(NULL)\n#1 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(489): Doctrine\DBAL\Driver\PDOStatement->execute()\n#2 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('INSERT INTO sub...', Array)\n#3 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback('INSERT INTO sub...', Array, Object(Closure))\n#4 /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illum in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 671, referer: https://www.xxx.de/index.php/xxx/manageIssues
`

**To Reproduce**
1. Go to issues
2. Click on publish
3. Publication process continues to run indefinitely
4. See error in php error.log file

**What application are you using?**
 OJS version 3.3.0.8

**Additional information**

I think that this could be due to special characters in one of the PDF files that are not part of the utf8 specification but need utf8mb4 (see https://stackoverflow.com/questions/20411440/incorrect-string-value-xf0-x9f-x8e-xb6-xf0-x9f-mysql#20429481). While i.e.  character_set_client and character_set_connection are utf8mb4 in our database, character_set_database is utf8. 

I don't know if this is due to a local setting or defined by PKP? If the first is the case, can I simply change the encoding?

Your's

Felix

**Comment by asmecher** [comment]
@felixhelix, yes, it does appear that you've encountered a character that requires a 4-byte encoding -- the error log quotes `𝐹` (https://www.compart.com/en/unicode/U+1D439) and part of another character (cut off in the log). As far as I'm aware, the UTF8MB4 requirement only affects the MySQL/MariaDB part of the installation, and PHP and OJS don't need to care about it and can handle 4-byte characters without further ado.

You have two options:
1. Configure/transcode your MySQL to use and support UTF8MB4. See e.g. [this StackOverflow thread](https://stackoverflow.com/questions/20411440/incorrect-string-value-xf0-x9f-x8e-xb6-xf0-x9f-mysql#20429481).
2. Configure your text extraction tools to filter characters like these. See `config.inc.php` for the text extraction tool configuration. I believe the defaults include some filtering.

This is more of an administration/configuration question, so the PKP support forum (for the extraction tools part) and/or StackOverflow (for that plus MySQL configuration) are probably better venues. If it does turn out that our code can better support UTF8MB4, then a Github issue is appropriate. But that's not clear to me yet.
