### ISSUE TITLE
"Copyright (c)" should not be translated as "all right reserved" (tous droit réservé)

### ISSUE THREAD

**Issue by ml4rrieu** [pkp/pkp-lib#8297]
There is a translation error here : 
https://github.com/pkp/pkp-lib/blob/54219af871eeda90dc76efdb4029fa4a725b6551/locale/fr_FR/submission.po#L1476

the [english version is (en_US)](https://github.com/pkp/pkp-lib/blob/54219af871eeda90dc76efdb4029fa4a725b6551/locale/en_US/submission.po#L1930) `Copyright (c) {$copyrightYear} {$copyrightHolder}`

I suggest the french translation : 

`msgstr "Droit d'auteur (c) {$copyrightYear} {$copyrightHolder}`

explanation :  just because you have a (c) doesn't mean _all_ rights are reserved. I can publish with a CC BY licence with a (c) to myself, and that does not mean that _all_ the rights are reserved.

**Comment by asmecher** [comment]
@ml4rrieu, can you adjust the translation in our Weblate installation? https://translate.pkp.sfu.ca
(I'd also accept a pull request if you're comfortable working with git, but we prefer translation work to happen via Weblate.)

If you think there's a discussion needed between French translators, then I'd suggest the support forum (https://forum.pkp.sfu.ca). But the change you suggest makes sense to me.
