### ISSUE TITLE
Use helper method in galley grids

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8299]
The galley grids should use the helper method, `$this->getGalley()`.

**Comment by NateWr** [comment]
PRs for `stable-3_3_0`:
https://github.com/pkp/pkp-lib/pull/8300
https://github.com/pkp/ojs/pull/3558/files
https://github.com/pkp/ops/pull/360

PRs for `main`:
https://github.com/pkp/pkp-lib/pull/8301
https://github.com/pkp/ojs/pull/3559
https://github.com/pkp/ops/pull/361

**Comment by asmecher** [comment]
Thanks, @NateWr, looks good -- please go ahead and merge. I'll try to get 3.3.0-13 released tomorrow if this is ready to be included.

**Comment by NateWr** [comment]
All merged to `stable-3_3_0` and `main`.
