### ISSUE TITLE
Author dashboard needs styling

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#830]
- Submission Library and View Metadata link actions
- Submission progress bar (to match workflow dashboard)

**Comment by asmecher** [comment]
@NateWr, this is the Author's view of a submission in progress. It's basically a subset of the information available to the editorial insiders.

**Comment by NateWr** [comment]
@asmecher I've updated the markup to adopt the same pattern as the main workflow, but I've noticed another bug. The Internal Review tab isn't loading in the Author Dashboard.

It looks like [the requested template file](https://github.com/pkp/pkp-lib/blob/master/controllers/tab/authorDashboard/AuthorDashboardTabHandler.inc.php#L103) doesn't exist. I tried debugging this but only got more confused about the setup.

There is `/omp/templates/authorDashboard/stages/internalReview.tpl`. It might be the tab template, but I tried moving it into position and that just led to errors.

I tried to see what the main workflow does, and it looks like it [loads the same template for internal and external review](https://github.com/pkp/pkp-lib/blob/master/controllers/tab/workflow/PKPWorkflowTabHandler.inc.php#L72-L73).

At this point, I thought if I went any further I was likely to break things I didn't understand. If you point me in the right direction I'll tackle it, or I can submit a PR for just this Issue and spin out a new Issue to fix this second  bug.

**Comment by asmecher** [comment]
@NateWr, thanks for the heads-up -- I've put a bit of time into this and gotten it going again. Check out my branches:
https://github.com/asmecher/pkp-lib/tree/i830-pre-fix
https://github.com/asmecher/omp/tree/i830-pre-fix

If those look OK, let me know and I'll merge them into master. Or you can base your work on those, and then send a PR to include that and some styling -- up to you.

**Comment by NateWr** [comment]
[PR](https://github.com/pkp/pkp-lib/pull/970).

**Comment by asmecher** [comment]
Merged, thanks!
