### ISSUE TITLE
OMP Multi presses installation | Books from other press can be accesed changing the ID in the URL

### ISSUE THREAD

**Issue by saponidas** [pkp/pkp-lib#8303]
Hi, sorry if the issue is already created, I could not find it (maybe related with #6949 ?)

When creating more than 1 press, the books can be loaded in other press just changing the "book id" in the url
I mean the book 3 of the press 1, can be accesed in the press 2:
https:/mydomain.ocm/PRESS1/catalog/book/3
https:/mydomain.ocm/PRESS2/catalog/book/3

Seems that a check for the context is missing. The same enviroment using  OJS shows a 404 page. 

--------------

OMP 3.3.0.12 (but have found the same behavior in some existing installations using >= 3.3.0.5)
Multipress Installation
Ubuntu 22.04
Apache 2.4
PHP 7.4
Mysql 8.0

--------------

Thanks in advance,

**Comment by asmecher** [comment]
@saponidas, thanks for reporting; you can correct this by patching your 3.3.0 installation with https://github.com/pkp/omp/commit/abbaeec2c29c18a9484dc3786c6777fb9e670de5. This will be released in OMP 3.3.0-14.
