### ISSUE TITLE
Enhance the queue failed jobs functionality. 

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8306]
**Describe the enhancement**
We have a frontend UI implemented to view queue pending/waiting to execute queue jobs in pkp/pkp-lib#7171 also queue job execution/handling enhancement in pkp/pkp-lib#7105 . But have no UI or CLI functionality to view or manage failed jobs and associated error for those failed job. It can be a good enhancement to have following functionalities for better managing of failed jobs 

- UI for failed jobs with redispatch, remove and exception trace visualisation.
- CLI enhancement for listing failed jobs with ability to redispatch and clear out failed jobs. 
- Schedule task to clear out much older failed jobs such as older than 180 days . 

**Who is asking for this one?**
No one right now.  But this will give both the devs and site admins each access to failed jobs with better visualisation. 

**Possible UI Update(screenshots)**
<img width="991" alt="CleanShot 2023-01-11 at 14 54 38@2x" src="https://user-images.githubusercontent.com/2587979/211762460-e60403de-05cc-4bb2-a088-bb8eb068ba82.png">
<img width="1005" alt="CleanShot 2023-01-11 at 14 52 01@2x" src="https://user-images.githubusercontent.com/2587979/211762507-19953341-a3dc-4569-9a31-0d63c467357e.png">
![omp-main test_index php_index%2Fadmin%2FfailedJobDetails_73](https://user-images.githubusercontent.com/2587979/211762598-3d6731c2-4f17-4b45-a7a6-63be267300e7.png)

**Previous Idea**
Clear out much older failed jobs from the `failed_jobs` table. Suggestion is to run a schedule task once a week and clear out any failed jobs older that 2 weeks from the table to keep it cleaner . This can also include some enhancement to existing job cli tool for better failed jobs handling.

### PRs
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3763
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1298
[ops](https://github.com/touhidurabir/ops) --> https://github.com/pkp/ops/pull/472
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8534
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/248

**Comment by NateWr** [comment]
I like it but I suggest a much longer window before removing failed jobs. Maybe 6 months? I think that in some cases failed jobs will be one way that people audit when things have gone wrong, and they may not recognize a problem for a while. This may be especially true with metadata deposits (eg - Crossref) where someone might not realize that their work has failed to be deposited for a long time.

**Comment by touhidurabir** [comment]
> suggest a much longer window before removing failed jobs. Maybe 6 months?

How about we set it as a config option in number of days ? and if thats turned off or disabled , the schedule task will not run. better control than hard coded values .

**Comment by NateWr** [comment]
Yes, that sounds good.

**Comment by touhidurabir** [comment]
@asmecher Please take a look at this.

**Comment by asmecher** [comment]
Looks very promising so far, @touhidurabir! I like the simplification you've proposed as well. I've left a few comments.

**Comment by touhidurabir** [comment]
@NateWr please take a look at this one .

**Comment by NateWr** [comment]
@touhidurabir can you give me some quick steps for testing this (ie - how to trigger job failures and where to view the new UI?)

**Comment by touhidurabir** [comment]
@NateWr you can access the job failure section from the `Administration` section logged in as a site admin . in the `Jobs` section , there is a new link `View Failed Jobs` . 

To dispatch test jobs (one bound to fail and one bound to succeed), run command 
```bash
php lib/pkp/tools/jobs.php test
```

To execute test jobs , run command 
```bash
php lib/pkp/tools/jobs.php run --test
```
this will push 1 failed job in the failed list. you can dispatch and execute test jobs many as times as you like to populate more failed jobs in failed list.

to view failed jobs from CLI, run command
```bash
php lib/pkp/tools/jobs.php list --failed
```

each of the above command take few parameters/flags to do bit more, best to check the details via command 
```bash
php lib/pkp/tools/jobs.php usage
```

**Comment by NateWr** [comment]
Thanks @touhidurabir. I'm running into some problems compiling the JS on your branch. I don't really understand why, but I found that these were resolved when I rebased. Can you do a rebase against the latest `main` and push up your changes? I'll then try again to test.

**Comment by touhidurabir** [comment]
@NateWr PR updated and also rebased. Please take a look .

**Comment by NateWr** [comment]
Looks good @touhidurabir. I left a few comments on the PRs. In addition, I'd recommend the following changes to the UI:

1. Instead of loading job details in a separate page, try moving them into a modal. That way they don't require a whole page load to access. You can see an example of a [simple modal](https://docs.pkp.sfu.ca/dev/ui-library/dev/#/component/Modal) in the UI library.
2. Once you move the job details into a modal, move the other actions in there too. That way each row only has a "View Details" button.
3. In the table to view the details, use a custom column to show the code inside of a `<pre>` tag. You can use [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#parameters) to format the exception a little bit nicer.
4. Finally, if you have time, consider adding a button to requeue all of the failed jobs. That will probably be the most frequent task needed.

**Comment by touhidurabir** [comment]
@NateWr it should be good to merge once all test pass. However no test is running but just queued and waiting .

**Comment by NateWr** [comment]
I'll let Alec merge this as he has done the review on the backend code. :+1:

**Comment by asmecher** [comment]
All merged -- thanks, @touhidurabir and @NateWr!

**Comment by touhidurabir** [comment]
Builds are failing for `PostgreSQL` because of `zero-length delimited identifier` . 

Patch PRs
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8644
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1341 [Submodule Update Only]
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/476 [Submodule Update Only]
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3771 [Submodule Update Only]

**Comment by touhidurabir** [comment]
All test is passing now .
