### ISSUE TITLE
Add help text to describe the DOI status filters

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8309]
**Describe the problem you would like to solve**
The new DOI management UI includes filters to view DOIs by their status, such as Unpublished, Unregistered, and Registered. However, it is not immediately clear what each of these statuses mean. 

**Describe the solution you'd like**
Add a button near the filters that will open a modal with a short description of each status. In the mockup below, a small question mark circle button appears to the right of the filters heading.

![filters-help](https://user-images.githubusercontent.com/2306629/193877553-cbd5fd0d-a3ea-4627-80d7-79abb3a61433.png)

**Who is asking for this feature?**
This is part of the feedback from Crossref on the new DOI UI

**Additional information**
cc @ewhanson

**Comment by ewhanson** [comment]
Hey @bozana, could you have a look at this? It's pretty straightforward and only added in the help text. Thanks!

PRs:

- `pkp-lib`: #8565 
- `ui-library`: pkp/ui-library#250 
- `ojs`: pkp/ojs#3735 
- `omp`: pkp/omp#1315 
- `ops`: pkp/ops#452

**Comment by bozana** [comment]
All fine, it can be merged :-)

**Comment by ewhanson** [comment]
Thanks. Merged!
