### ISSUE TITLE
Password reset fails with addition of expiration token

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#831]
Validation::generatePasswordResetHash() now adds an expiration token for OJS.
https://github.com/pkp/ojs/blob/ojs-dev-2_4/classes/security/Validation.inc.php#L307-L341

We have a lovely method which validates a password reset hash and expiration.
https://github.com/pkp/ojs/blob/ojs-dev-2_4/classes/security/Validation.inc.php#L349-L359

We never use it.

Instead, we compare a newly generated reset hash against the former hash, expiry and all.
https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/pages/login/PKPLoginHandler.inc.php#L240-L241

C.f.: http://forum.pkp.sfu.ca/t/ojs-2-4-7-reset-password-link-expired/4768

**Comment by asmecher** [comment]
Thanks for reporting, @ctgraham. Are you working on this, or shall I?

**Comment by ctgraham** [comment]
Testing a change to PKPLoginHandler::resetPassword() now.

**Comment by asmecher** [comment]
Thanks, @ctgraham. I'll looking into writing a test up to prevent regressions like this once a fix is in place.

**Comment by asmecher** [comment]
For instructions on how to apply the patch to an OJS 2.4.7 installation, see here:
https://github.com/pkp/pkp-lib/pull/833#issuecomment-150335585
