### ISSUE TITLE
Discourage DOI assignment for items other than submissions

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8310]
**Describe the problem you would like to solve**
When enabling DOIs, journal managers are asked to select which objects to enable DOIs for, such as articles, issues and galleys. It's uncommon to use DOIs for anything other than articles, but many journal managers may select all options without understanding what it means ("I don't see why not").

In some cases, like Crossref, article galleys that represent the primary file should _not_ be assigned their own DOI. This leads to journals registering multiple DOIs for the same "object" (the article).

**Describe the solution you'd like**
Change the settings form so that enabling DOIs for other objects is less prominent and accompanied with text that explains clearly that this may not be desired.

**Who is asking for this feature?**
Crossref suggested this after reviewing the new DOI UI.

**Additional information**
For some journals and DOI registration agencies, it is important to be able to assign DOIs to issues and article galleys. So this setting can not be removed entirely.

The existing settings form:

![enable-doi-settings](https://user-images.githubusercontent.com/2306629/193880592-36e69d28-3e0c-4e7e-bd4e-a40360fa185b.png)

A suggested settings form that enables articles by default when DOIs are enabled, and only asks the journal manager if they want to add extra DOIs. It also moves the field to the bottom of the form so it appears less important.

![enable-other-dois](https://user-images.githubusercontent.com/2306629/193880767-d96764de-135c-4b60-8128-abd889e49c15.png)

cc @ewhanson

**Comment by ewhanson** [comment]
Hey @bozana, this should be the last one ahead of RC1. Could you have a look? Thanks!

PRs:

- #8643 
- pkp/ui-library#259
- pkp/crossref-ojs#27
- pkp/ojs#3770
- pkp/omp#1340
- pkp/crossref-ops#24
- pkp/ops#475

**Comment by bozana** [comment]
Hi @ewhanson, I have not tested it and would have only one question. If your are also not sure about the answer now, you can merge and we can think about it later :-) Thus, it can be merged... :+1: :-)

**Comment by ewhanson** [comment]
Thanks @bozana! Merged!
