### ISSUE TITLE
Fatal error when trying to load ResendRequestReviewerForm

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8311]
**Describe the bug**
Unable to load the form to resend the review request to a reviewer, who previously declined it.

Associated fatal error:
```
PHP Fatal error:  Class PKP\controllers\grid\users\reviewer\form\ResendRequestReviewerForm contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PKP\controllers\grid\users\reviewer\form\ReviewerNotifyActionForm::getMailable) in /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/users/reviewer/form/ResendRequestReviewerForm.php on line 30
```

**To Reproduce**
1. Make a submission and pass it to the review stage
2. Assign Reviewer
3. Login as a reviewer and decline the review
4. Login as an editor and reassign this reviewer - `Resend Review Request` button in the reviewer grid

**What application are you using?**
 OJS main branch

**Additional information**
This is a new feature implemented in: https://github.com/pkp/pkp-lib/issues/4789

**Comment by Vitaliy-1** [comment]
@touhidurabir, I've assigned you as you worked on this feature before

**Comment by touhidurabir** [comment]
@Vitaliy-1 fixed. PRs
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8312
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3565

**Comment by touhidurabir** [comment]
@asmecher as `OJS` test has passed , it's good to merged .

**Comment by asmecher** [comment]
Merged, thanks!
