### ISSUE TITLE
ThemePlugin: Unable to retrieve array options

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8317]
**Describe the bug**
When adding an array option to the `ThemePlugin`:

```php
ThemePlugin::addOption(
  'field', 'FieldOptions', [
    'options' => [['value' => 'value1', 'label' => 'label1'], ['value' => 'value2', 'label' => 'label2']],
    'default' => []
  ]
);
```

It's stored properly to the database, as a `JSON` value, but it fails to be retrieved [due to the `unserialize()`](https://github.com/pkp/pkp-lib/blob/2597e2dc6ed7be93b6d6e461d2c675d313baf896/classes/plugins/ThemePlugin.php#L605).

Fix reference: https://github.com/pkp/pkp-lib/blob/2597e2dc6ed7be93b6d6e461d2c675d313baf896/classes/db/DAO.php#L334-L341

**PRs**
`stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8320
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3567

`main`
- https://github.com/pkp/pkp-lib/pull/8321
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3568

**What application are you using?**
main and stable-3_3_0

**Comment by jonasraoni** [comment]
@asmecher Just a small fix for an issue that I found while creating a custom theme.

**Comment by jonasraoni** [comment]
@asmecher Just a small fix for an issue that I found while creating a custom theme.

**PRs**
`stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8320
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3567

`main`
- https://github.com/pkp/pkp-lib/pull/8321
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3568

**Comment by asmecher** [comment]
All merged -- thanks, @jonasraoni.
