### ISSUE TITLE
Server error after install

### ISSUE THREAD

**Issue by xeroticikot** [pkp/pkp-lib#8319]
I’ve installed the system on ubuntu 20.04 with aapanel apache. But the domain returning the following error - This page isn’t working

The server log error -

```
AH01071: Got error ＇PHP message: PHP Fatal error: Uncaught Error: Call to undefined function putenv() in /www/wwwroot/ojs/lib/pkp/classes/i18n/PKPLocale.inc.php:292
Stack trace:
#0 /www/wwwroot/ojs/lib/pkp/classes/core/Dispatcher.inc.php(116): PKPLocale::initialize()
#1 /www/wwwroot/ojs/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher-＞dispatch()
#2 /www/wwwroot/ojs/index.php(68): PKPApplication-＞execute()
#3 {main}\n thrown in /www/wwwroot/ojs/lib/pkp/classes/i18n/PKPLocale.inc.php on line 292＇
```

**Comment by jonasraoni** [comment]
Hi @xeroticikot!

Please, try to solve your problem using [our forum](https://forum.pkp.sfu.ca/c/questions/5). I just can say this is a core PHP function, which should be working fine, perhaps it was disabled by your host provider.

**Comment by sagaraoneone** [comment]
I Have same Problem. Pls I need Helps

**Comment by jonasraoni** [comment]
Hi @sagaraoneone, this type of problem isn't going to be solved here (it's not even related to our code), please use the forum: https://forum.pkp.sfu.ca/c/questions/5
