### ISSUE TITLE
Typo in subsequent review request email template body

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8325]
**Describe the bug**
The subsequent review request email template message has a stray `{$contextName}` variable that should be removed:

```
"I'm writing to ask if you would conduct a second round of peer review for this submission. {$contextName}.</p>"
```

We should look at existing translations and remove the variable where it is clearly out of place. For example, in the Czech translation:

```
"předložené práce. {$contextName}.</p><p> Pokud jste schopni tento příspěvek "
```

Wherever we are not confident of fixing this in a translation, we should mark `msgid "emails.reviewRequestSubsequent.body"` with the `#, fuzzy` designation so it will be re-translated

**What application are you using?**
`main` banch, 3.4 pre-release

**Comment by NateWr** [comment]
@Vitaliy-1 can you take a look at this?

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8352 (remove duplicate localization)
OJS: https://github.com/pkp/ojs/pull/3580
