### ISSUE TITLE
CSV for stats API timeline functions

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8328]
Implement the CSV export for the stats API timeline functions, to be able to replace the Custom Report Generator, that provides monthly and daily stats

**Comment by bozana** [comment]
PRs:
pkp-lib: https://github.com/pkp/pkp-lib/pull/8359
ui-library: https://github.com/pkp/ui-library/pull/223
ojs: https://github.com/pkp/ojs/pull/3583

**Comment by bozana** [comment]
Hi @NateWr, me again :-) Could you take a look at the PRs above? If OK, I will do the same for stats issues page (once it is merged) and provide submodule updates for OMP and OPS.

**Comment by NateWr** [comment]
Looks good! No comments. Happy for you to merge when ready.
