### ISSUE TITLE
Review missing indexes

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8329]
**Describe the bug**
After the migration from the old database framework, looks like some indexes were left behind, for example the [submissions schema](https://github.com/pkp/pkp-lib/blob/7d21b0173906f3336fd975b19ad04e4e547c0870/classes/migration/install/SubmissionsMigration.php#L30-L50) has no index over the `context_id` field, but it's declared in the old framework: https://github.com/pkp/pkp-lib/blob/7d21b0173906f3336fd975b19ad04e4e547c0870/xml/schema/submissions.xml#L53-L55

This problem might be reduced under MySQL, as it [creates indexes automatically for fields involved in foreign keys](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html#:~:text=MySQL%20requires%20indexes,as%20described%20previously).

Considering that our application is made of lots of reads and fewer writes, it might be a good time to review the index usage against a heavy installation:
- [x] Ensure all fields involved in foreign key constraints have an index. It's a general good rule of thumb, and as the indexes will be created by MySQL anyway, it's better to keep the PostgreSQL structurally synchronized. (Done in pkp/pkp-lib#6093)
- [ ] Check the slow query log of a large installation to look for low hanging fruits.
- [ ] Add indexes to columns used often in `order by` clauses (when they are followed by a `limit` clause), might be interesting.
- [ ] Review used filters at query builders, there might be some filters that are used often and have a large cardinality.

To address the missing indexes in OJS 3.3 a migration in 3.4 will be needed.

**What application are you using?**
OJS /main

**Comment by asmecher** [comment]
Fixing this issue in part over at https://github.com/pkp/pkp-lib/issues/6093#issuecomment-1276868480.

**Comment by asmecher** [comment]
@jonasraoni, a number of these need some scoping...

> Add indexes to columns used often in `order by` clauses (when they are followed by a `limit` clause), might be interesting.

> Review used filters at query builders, there might be some filters that are used often and have a large cardinality.

> Check the slow query log of a large installation to look for low hanging fruits.

These aren't bad ideas in general, but doing a complete review would be a big/vague task. Do you have specific proposals for these?

If we're brainstorming ideas, maybe this should be converted to a Discussion, or brought to the Optimization / Testing groups in Mattermost.

**Comment by jonasraoni** [comment]
I don't have anything specific in mind, so it's better to move it to the optimization document (which could be transformed into a discussion) if it's not already there... And further work will probably fit better into the https://github.com/pkp/pkp-lib/issues/7304 :)

**Comment by asmecher** [comment]
OK! Closing in favour of those.
