### ISSUE TITLE
3.4 plugin updates

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8338]
- [x] QuickSubmit
- [ ] mEDRA (s. https://github.com/pkp/pkp-lib/issues/8597)
- [x] paperbuzz
- [x] Matomo/Piwik
- [x] Backup
- [x] JATSTemplate
- [x] OAI JATS
- [ ] themes
  - [x] submission checklist
  - [x] usage stats display option
- [x] CSV in OMP ?
- [x] reviewReport ?
- [x] URN ? (Bozana)
- [x] CrossrefReferenceLinking (Bozana)
- [ ] ReturningAuthorScreening (see https://github.com/pkp/pkp-lib/issues/8810)
- [ ] customLocale https://github.com/pkp/customLocale/issues/23
- [ ] pln https://github.com/pkp/pln/issues/57

**Comment by NateWr** [comment]
@Vitaliy-1 when you updated the themes, did you also update the submission checklist? It's now a text field instead of an array.

**Comment by Vitaliy-1** [comment]
I believe you have updated the submission checklist for all of the themes, I'm seeing your commits there

**Comment by asmecher** [comment]
@bozana, can you look at QuickSubmit? It needs updating for https://github.com/pkp/pkp-lib/issues/7128.

**Comment by bozana** [comment]
> @bozana, can you look at QuickSubmit? It needs updating for #7128.

Done, s. https://github.com/pkp/quickSubmit/pull/69

**Comment by asmecher** [comment]
@touhidurabir, did you have a chance to test the OMP CSV import plugin?

**Comment by bozana** [comment]
All from this list are either adapted or another issue exists, thus closing...
