### ISSUE TITLE
SHA-1 is being deprecated

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#834]
The OMP installation process says, under security “SHA1 is recommended.” SHA-1 is being deprecated; browsers, for instance, are dropping support for SHA-1 signed certificates by 2017, some of them possibly sooner. SHA-2 or SHA-3 support should be added as soon as feasible.

**Comment by asmecher** [comment]
@crism, we recently shifted our password hashing to current standards and this is about to be merged into OMP and OJS3: https://github.com/pkp/pkp-lib/issues/781
