### ISSUE TITLE
Author country is not validated in the REST API

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8344]
**Describe the bug**
It's possible to create an author without a valid country when creating or editing an author through the REST API endpoint:

```
/submissions/1/publications/1/contributors
```

**To Reproduce**
1. Use the REST API to create or edit an author with an invalid country code, like `1234NoCountry`.
2. Inspect the database to see that this country is in the database.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
A couple of changes:

1. Add a `validation` attribute to the `country` property in the `author.json` schema. The validation should probably just be a regex that enforces a 2-capital-letter format.
2. Add a rule to `PKP\author\Repository::validate()` that checks this against the valid countries.

Also, adding `"apiSummary": true` to the `country` property in the schema will make it appear in the REST API, which will probably make it easier to debug.

**Comment by touhidurabir** [comment]
@NateWr PRs to review 
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8361
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3584

**Comment by touhidurabir** [comment]
@NateWr required changes are done and ready to merge .

**Comment by NateWr** [comment]
Thanks @touhidurabir! All merged. :+1:
