### ISSUE TITLE
Add more tests for the new submission wizard

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8346]
**Describe the issue**
Due to time constraints, there are several features of the new submission wizard that are not tested as part of the integration tests. The following are tests that would be good to add before 3.4's final release.

**High-value Tests**
- [x] I can change the language and section of the submission after I have started the submission. (From the "submitting to X in X language" area.)
- [x] I can submit in a language other than the current UI. All forms show fields in this language and I'm able to complete my submission without entering details in any other language.
- [x] When more than one submission language is enabled in Settings > Website > Languages, I can enter title, abstract and keyword information in multiple languages. This appears correctly in the review step.
- [x] Keywords, subjects and references appear in the form according to the settings in Settings > Workflow > Metadata. When required, I am unable to submit without entering them.
- [x] I am unable to complete my submission if I have forgotten to select a file type after uploading a file in the first step.
- [x] I am unable to complete my submission if i have forgotten to enter a title. 
- [x] I am unable to complete my submission if I am submitting to a section that requires abstracts and I have not entered an abstract. I am allowed to complete my submission if the section does not require abstracts.
- [ ] I am unable to complete my submission if I enter an abstract that is longer than the section allows.
- [x] When a copyright notice is configured in the context, it appears in the review step of the submission wizard and I am unable to submit without checking its checkbox.
- [x] When I enter comments to the editor, a discussion with these comments is created once the submission is submitted.
- [x] As an author, I am unable to submit to a section when it is marked inactive or when it is configured so that only editors can submit to it.
- [ ] When I am logged in as a user with editor and author roles, I am able to choose which role to create a submission as when starting a submission. When I choose to submit as an editor, no author record is created automatically in the submission.
- [ ] When a journal has only one section and language, I am not asked to select these when starting a submission. The text "submitting to X in X language" does not appear at the top of the wizard. Forms do not have any multilingual input. And I am still able to complete my submission.
- [ ] When I make a submission, editorial assignments configured for sections and categories are applied correctly.

**Other tests**
- [ ] The back buttons work on every step.
- [ ] On the review step, I can click the Edit button by any review panel to go to that step.
- [ ] Categories appear correctly in the submission wizard. When I select a category, it appears in the review step.
- [ ] I can go to any previous step by clicking the step name in the list of steps at the top.
- [ ] All metadata settings are tested (see test above about keywords, subjects, and references).
- [ ] If no privacy statement has been entered, this doesn't appear on the form to start a submission.
- [ ] I can start a submission even if I don't have the author role (eg - as reviewer, copyeditor, etc.) After I have created a submission, I have the author role.
- [ ] If there is no author role, or the author role does not allow self-registration, I can not start a submission when I am logged in as a reviewer or copyeditor.

**Additional Comments**
I'm assigning this to 3.4 in the hope that we can get some of these tests implemented before the final release. But I suspect we'll bump most of them.

**Comment by NateWr** [comment]
The following PRs add several of the high-value tests listed above, but not all of them.

PRs:
https://github.com/pkp/pkp-lib/pull/8876
https://github.com/pkp/ojs/pull/3866

**Comment by NateWr** [comment]
@asmecher I've run out of ideas for how to fix the tests. It works for me locally. I've tracked the problem down to the call to switch languages. I've tried a few different ways to change languages, but none of them seem to be working in the Travis tests (they all work for me locally).

The error is here: https://app.travis-ci.com/github/pkp/ojs/jobs/600315309#L3477

I am testing that the copyright notice appears correctly when I switch languages in the submission wizard. I wrote a command to change languages, but it's not working: 

https://github.com/NateWr/pkp-lib/blob/d8a059d6823f70beeffc5f3bff1e06f678a71b41/cypress/support/commands.js#L870-L876

I made a previous attempt to write this in a more generic way, but that failed too: 

https://github.com/NateWr/pkp-lib/blob/a3936b9987be5769b0a5eb36c4c1ae6da632a5d7/cypress/support/commands.js#L870-L887

Using `cy.screenshot()`, I was able to verify that the language is never switched on Travis (again, both methods work fine locally). The other test failures are happening because this test fails (the test resets the copyright notice when it is done, and the other tests expects it to be empty).

Any idea why this might not be working? All I can think of is if there is something about the travis build that doesn't do sessions or referer headers correctly?

**Comment by asmecher** [comment]
@NateWr, looking at the screenshot from https://app.travis-ci.com/github/pkp/ojs/jobs/600315309, it looks like the French language option isn't being found at all in the user navigation menu. The error `get .app__userNav a:contains('Français')` is failing to find the element, so the language switcher isn't submitting the request to change the language.
![image](https://user-images.githubusercontent.com/200411/233675168-78ff52ef-6ba6-457d-9e55-e06724e305cd.png)

**Comment by NateWr** [comment]
Thanks @asmecher, that helped! I was able to find a test that disables the UI language. I went ahead and re-enabled it in that test to "reset" the data: https://github.com/pkp/pkp-lib/pull/8876/files#diff-33549da02ff3ea0d4410934cdb3f9f063321bf8849a132890471bb4902bab43fR31-R36

Oddly, our test data at pkp/datasets doesn't seem to include this setting. I thought the test data was saved after all the tests finished. But is the test data maybe saved before some of the integration tests are finished?

**Comment by asmecher** [comment]
👍👍 The datasets are saved after the data build tests, but before the integration tests.

**Comment by NateWr** [comment]
In that case, it might be good to encourage integration tests to "reset" any conditions that have been modified as part of the tests. If side effects can be isolated then it's easier to debug a single test without having to run the full suite.
