### ISSUE TITLE
Missing email template variables in emails related to a new submission

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8348]
**Describe the bug**
Several email template variables are missing in some of the emails that are sent when a new submission is made. These are usually related to the signature in one form or another.

This issue can not be addressed until #7191 is complete and merged to `main`.

**To Reproduce**
1. Configure the journal so that editors will be automatically assigned to a submission (eg - from the section settings).
2. Login as an author and create a submission in that section to ensure an editor is assigned. Enter at least one co-author other than the author you are logged in as.
3. Complete the submission.
4. View the email logs to see missing email variables emails that were sent.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
The missing variables seem to be related to the signature. In some cases, a `{$signature}` variable is not replaced:

```
To: Daniel Barnes <dbarnes@mailinator.com>
Subject: You have been assigned as an editor on a submission to Journal of
 Public Knowledge
MIME-Version: 1.0
Date: Wed, 19 Oct 2022 08:53:17 +0000
Message-ID: <3b70b93603df41a6c7ddd3e9dfe976c9@mailinator.com>
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<p>Dear Daniel Barnes,</p><p>The following submission has been assigned to =
you to see through the editorial process.</p><p><a href=3D"http://localhost=
:8000/publicknowledge/workflow/access/6">Investigating the Shared Backgroun=
d Required for Argument: A Critique of Fogelin's Thesis on Deep Disagreemen=
t</a><br />Dana Phillips</p><p><b>Abstract</b></p>Robert Fogelin claims tha=
t interlocutors must share a framework of background beliefs and commitment=
s in order to fruitfully pursue argument. I refute Fogelin=E2=80=99s claim =
by investigating more thoroughly the shared background required for product=
ive argument. I find that this background consists not in any common belief=
s regarding the topic at hand, but rather in certain shared pro-cedural com=
mitments and competencies. I suggest that Fogelin and his supporters mistak=
enly view shared beliefs as part of the required background for productive =
argument because these procedural com-mitments become more difficult to uph=
old when people=E2=80=99s beliefs diverge widely regarding the topic at han=
d.<p>If you find the submission to be relevant for Journal of Public Knowle=
dge, please forward the submission to the review stage by selecting "Send t=
o Review" and then assign reviewers by clicking "Add Reviewer".</p><p>If th=
e submission is not appropriate for this journal, please decline the submis=
sion.</p><p>Thank you in advance.</p><p>Kind regards,</p>{$signature}  
```

In other places, it seems that the journal signature is being inserted. But because this has variables within it, those variables are not getting rendered:

```
To: Mark Irvine <mirvine@mailinator.com>
Subject: Submission confirmation
MIME-Version: 1.0
Date: Wed, 19 Oct 2022 08:51:46 +0000
Message-ID: <92ceff67e51d66fc96fc5cf59131403d@mailinator.com>
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<p>Dear Mark Irvine,</p><p>You have been named as a co-author on a submissi=
on to Journal of Public Knowledge. The submitter, Craig Montgomerie, provid=
ed the following details:</p><p>Computer Skill Requirements for New and Exi=
sting Teachers: Implications for Policy and Practice<br></p><p>If any of th=
ese details are incorrect, or you do not wish to be named on this submissio=
n, please contact me.</p><p>Thank you for considering this journal as a ven=
ue for your work.</p><p>Kind regards,</p><br><br><p><a href=3D"http://local=
host:8000/publicknowledge">Journal of Public Knowledge</a></p><p>{$mailingA=
ddress}</p><p>{$contactName}, <a href=3D"mailto:%20%7B$contactEmail%7D">{$c=
ontactEmail}</a></p>  
```

**Comment by NateWr** [comment]
The following PRs address two problems:

- Variables used inside the context signature weren't rendered.
- Use `{$contextSignature}` or `{$siteSignature}` instead of `{$signature}` in several templates.

@Vitaliy-1 can you do a code review on this? 

@asmecher this involved changes to email variables in locale keys for other languages (see [example](https://github.com/pkp/ojs/pull/3713/files#diff-27357fdbb5d6593e433ba6712fc3f465361dcd57fdd2df2c936dbf4e94cd4e2c)). Is this ok to merge in or will it cause problems with the translation toolset?

PRs:
- https://github.com/pkp/pkp-lib/pull/8552
- https://github.com/pkp/ojs/pull/3713
- (OMP coming)
- (OPS coming)

**Comment by NateWr** [comment]
In case I need to do this again, this is the tool I wrote to replace the variables in specific msgid's in all locale files.

[replaceVariableInLocaleKey.php.txt](https://github.com/pkp/pkp-lib/files/10458088/replaceVariableInLocaleKey.php.txt)

And these were the replacements I ran:

```
php lib/pkp/tools/replaceVariableInLocaleKey.php emails.submissionAck.body signature contextSignature
php lib/pkp/tools/replaceVariableInLocaleKey.php emails.userValidateContext.body signature contextSignature
php lib/pkp/tools/replaceVariableInLocaleKey.php emails.userValidateContext.body signature contextSignature
php lib/pkp/tools/replaceVariableInLocaleKey.php emails.userValidateSite.body signature siteSignature
php lib/pkp/tools/replaceVariableInLocaleKey.php emails.reviewResponseOverdueAuto.body signature contextSignature
php lib/pkp/tools/replaceVariableInLocaleKey.php emails.reviewRemindAuto.body signature contextSignature
```

**Comment by asmecher** [comment]
> This involved changes to email variables in locale keys for other languages (see [example](https://github.com/pkp/ojs/pull/3713/files#diff-27357fdbb5d6593e433ba6712fc3f465361dcd57fdd2df2c936dbf4e94cd4e2c)). Is this ok to merge in or will it cause problems with the translation toolset?

@NateWr, that's fine to merge. The two affected email templates don't appear in OJS/OMP/OPS `stable-3_3_0`, so no need to worry about conflicting translations. But if they did, you could resolve it by adding them to the list in the [summit toolset configuration](https://github.com/asmecher/summit-tools/blob/767564c0d901de98e4685080f61cf203dde8416b/summit-config-shared#L53).

**Comment by Vitaliy-1** [comment]
> In other places, it seems that the journal signature is being inserted. But because this has variables within it, those variables are not getting rendered

Could it be possible that those variables just aren't set? I think it's just a default value that is being created with for a signature during journal creation. E.g., I'm getting this set as a `journalSignature` after creation of a new context:
```
<br/><hr /><br/><p><a href="http://localhost:8000/index.php/sj">Second Journal</a></p><p>{$mailingAddress}</p><p>{$contactName}, <a href="mailto: {$contactEmail}">{$contactEmail}</a></p>
```
If it was because of a problem with replacing variables within another one, `journalUrl` also wasn't replaced. This is related: https://github.com/pkp/pkp-lib/issues/8130

**Comment by Vitaliy-1** [comment]
Contact name and contact email are also mandatory during new context creation after recent change. Maybe it's a timing problem and they are added to a context after the default variable value is set?

**Comment by Vitaliy-1** [comment]
Ahh, it looks like it's a matter of priority, when a variable depends on other variables it should be compiled first. If it's the only case, I'd just passed it first first but I'm ok with this approach too - the only thing is that we should ensure it's always compiled last after all other values are available.

**Comment by NateWr** [comment]
Merged or cherry-picked to `main`. Thanks @Vitaliy-1!

Regarding the context signature variables -- I think I prefer leaving them as variables when a new context is created. That way they'll always use the latest contact name and email.
