### ISSUE TITLE
fresh OJS installation gets redirected to same place no matter the url

### ISSUE THREAD

**Issue by luandro** [pkp/pkp-lib#835]
I've tried many times installing [OJS 2.4.7-1](https://pkp.sfu.ca/ojs/ojs_download/) on my server, but something seems not to be working. You can check what happens live [here](http://104.236.19.211), not matter where I click it ends up on the same page.

I've gone thru all the [installation](http://pkp.sfu.ca/ojs/README) process, giving permission to all the files, and doing the manual setup "php tools/install.php", since the in browser doesn't show anything.

My stack
- Nginx 1.8.0
- PHP 5.5.30
- MariaDB 10.0.21

Any clues to what could be the problem?

**Comment by luandro** [comment]
Got it to work on normal LAMP stack. Seems it's not compatible with Nginx or MariaDB. My guess would be Nginx.

**Comment by asmecher** [comment]
@luandro, the problem is likely because of Nginx, PHP, and the `path_info` server variable. See e.g. https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/ for an example configuration that should include `path_info`.

**Comment by luandro** [comment]
I finally got `path_info` server variable to work by changing my default `fastcgi_params` to:

```
fastcgi_intercept_errors on;
# this will allow Nginx to intercept 4xx/5xx error codes
# Nginx will only intercept if there are error page rules defined
# -- This is better placed in the http {} block as a default
# -- so that in the case of wordpress, you can turn it off specifically
# -- in that virtual host's server block
 
location ~ \.php {
	fastcgi_split_path_info ^(.+\.php)(/.+)$;
	# A handy function that became available in 0.7.31 that breaks down 
	# The path information based on the provided regex expression
	# This is handy for requests such as file.php/some/paths/here/ 
 
	fastcgi_param  PATH_INFO          $fastcgi_path_info;
	fastcgi_param  PATH_TRANSLATED    $document_root$fastcgi_path_info;
 
        fastcgi_param  QUERY_STRING       $query_string;
        fastcgi_param  REQUEST_METHOD     $request_method;
        fastcgi_param  CONTENT_TYPE       $content_type;
        fastcgi_param  CONTENT_LENGTH     $content_length;
 
        fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param  REQUEST_URI        $request_uri;
        fastcgi_param  DOCUMENT_URI       $document_uri;
        fastcgi_param  DOCUMENT_ROOT      $document_root;
        fastcgi_param  SERVER_PROTOCOL    $server_protocol;
 
        fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
        fastcgi_param  SERVER_SOFTWARE    nginx;
 
        fastcgi_param  REMOTE_ADDR        $remote_addr;
        fastcgi_param  REMOTE_PORT        $remote_port;
        fastcgi_param  SERVER_ADDR        $server_addr;
        fastcgi_param  SERVER_PORT        $server_port;
        fastcgi_param  SERVER_NAME        $server_name;
 
	fastcgi_pass   127.0.0.1:9000;
	fastcgi_index  index.php;
}
```
[source](http://kbeezie.com/php-self-path-nginx/)

You can check it's working: `curl http://104.236.19.211/test.php/foo/bar.php\?v\=1`. But if you try the [index](http://104.236.19.211), where ojs installation dashboard should show up, I still get redirected around.

**Comment by asmecher** [comment]
@luandro, that test URL is only working because of the `.php` suffix in the `bar.php` part; if that's not included you'll see that your server isn't properly sending the request via the `test.php` script.

**Comment by luandro** [comment]
So what am I missing? Are there any other files I should be modifying besides `fastcgi_params`?

**Comment by asmecher** [comment]
@luandro, I don't have any experience with Nginx configuration -- but one option would be to turn on the `disable_path_info` option in `config.inc.php`. This will result in uglier URLs but won't require `path_info` to work.

**Comment by luandro** [comment]
I don't have any experience with Nginx config either. Changing `disable_path_info` to `On` works, but could there be any issues in the future because of that?

Really appreciate the support.

**Comment by asmecher** [comment]
If you can live with the URLs that this mode uses, then you should be fine. I'd suggest trying stackoverflow for help with the nginx setup; they're usually very quick.
