### ISSUE TITLE
Store a copy of the agreed copyright notice in a submission's activity log

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8351]
**Describe the problem you would like to solve**
When making a new submission, authors are asked to agree to the copyright notice of the journal, preprint server or press. However, this information is not stored so it is not possible to know later what terms the author agreed to.

**Describe the solution you'd like**
When a new submission is made, store a copy of the agreed copyright notice as an entry in the submission's activity log. 

Ideally, this will be visible from the activity log. But even if it is not possible to make it visible for 3.4, a copy should be stored so that it can be accessed from the database when required. And we can make it visible in future versions. The important thing is to start storing the data as soon as possible so the historical record is kept.

**Who is asking for this feature?**
This overlaps with the request in https://github.com/pkp/pkp-lib/issues/7062, but with a few small differences. The copyright notice may not be appropriate for some use cases described in that issue, which probably wants a new setting, like a "terms and conditions" field the user must accept.

**Additional Comments**
The copyright notice should not appear in the submission wizard when submitting as an editor, and in these cases no entry should be added to the activity log, since the author was not involved in agreeing to the terms.

**Comment by NateWr** [comment]
The following PRs save the copyright notice into the submission log when the submission is submitted through the new wizard (or posted to the API's `/submit` endpoint with the appropriate props). The log shows who agreed to the copyright notice:

![log-copyright-agreed](https://user-images.githubusercontent.com/2306629/217601500-ff2d8992-fc70-4f53-8ff9-4512cf313054.png)

The text of the copyright notice is saved to the database, but not available in the UI. There's no pattern in place now to show this information, so exposing it would require a bigger rewrite of the activity log.

In the meantime, if you need to access the copyright notice for a submission that has this log entry, it can be retrieved with the following SQL query:

```sql
select * 
from event_log_settings 
left join event_log on (event_log.log_id = event_log_settings.log_id) 
where event_log.assoc_type = 1048585 
and event_log.assoc_id = <submission_id>
and setting_name='copyrightNotice';
```

PRs:
https://github.com/pkp/pkp-lib/pull/8615
https://github.com/pkp/ui-library/pull/254

Tests only:
https://github.com/pkp/ojs/pull/3749

@jonasraoni do you have time to code review this?

**Comment by NateWr** [comment]
Thanks @jonasraoni! Merged to `main`.

**Comment by felixhelix** [comment]
@NateWr Shouldn't this be already in 3.5?: I looked at the existing submissions activity log for some submissions from the PKP OJS test data set, submitted a paper myself and found neither an entry on the "activities log & notes" nor via a database query?
