### ISSUE TITLE
New OMP 1.2 Frontend

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#836]
This is just a ticket to help track various tasks related to polishing off the new frontend for 1.2. It will make it easier for me to peg PRs to a specific issue.

- [x] Ensure header looks good without logo. [PR](https://github.com/pkp/omp/pull/147)
- [x] Style catalog entries and sections for full catalog, category, series, new releases and search results. [PR](https://github.com/pkp/omp/pull/149)
- [x] Style about and announcement pages. [PR](https://github.com/pkp/omp/pull/151)
- [x] Individual book page [PR](https://github.com/pkp/omp/pull/152)
- [x] Footer (rough style of what's already there in [PR](https://github.com/pkp/omp/pull/150))
- [x] Get the info pages (for reader, for libraries, etc) styled up. [PR](https://github.com/pkp/pkp-lib/pull/860)
- [x] Get the tinymce content block working and looking good in the sidebar. [PR](https://github.com/pkp/omp/pull/155), [PR](https://github.com/pkp/customBlockManager/pull/6)
- [x] Figure out a good homepage (features prominent) [PR](https://github.com/pkp/omp/pull/161) and [PR](https://github.com/pkp/pkp-lib/pull/894)
- [x] Remove features from category and series pages [PR](https://github.com/pkp/omp/pull/159)
- [x] Search results page [PR](https://github.com/pkp/omp/pull/155)
- [x] Login page [PR](https://github.com/pkp/omp/pull/155)
- [x] Tasks popover [PR](https://github.com/pkp/omp/pull/155)
- [x] Primary nav menu dropdowns can go off-page if they're right on the edge of the viewport. [PR](https://github.com/pkp/omp/pull/162) and [PR](https://github.com/pkp/pkp-lib/pull/900)
- [x] Primary nav menu dropdowns not accessible on some touch devices (Android) [PR](https://github.com/pkp/omp/pull/162)
- [x] Ensure options in Settings > Website > Appearance align with what's actually implemented on the frontend. [PR](https://github.com/pkp/pkp-lib/pull/922), [PR](https://github.com/pkp/omp/pull/167) and [PR](https://github.com/pkp/ojs/pull/676).
- [x] When no logo is selected, OMP tries to load an `ojs_logo.png` [PR](https://github.com/pkp/pkp-lib/pull/916), [PR](https://github.com/pkp/ojs/pull/674) and [PR](https://github.com/pkp/omp/pull/165)
- [x] Update all [OMP-compatible bloock plugins](https://github.com/pkp/customBlockManager/pull/6#issuecomment-154204306) to new layout structure. [PR](https://github.com/pkp/omp/pull/158)
- [x] Ensure AddThis plugin can add social share buttons to book page. See [this comment](https://github.com/pkp/pkp-lib/issues/836#issuecomment-155130660) [PR](https://github.com/pkp/omp/pull/157)
- [x] Set up a durable HTML scheme for outputting content via hooks on the book page (both right panel and in the main content panel) See [PR](https://github.com/pkp/omp/pull/157) for a bit of discussion.

**Comment by NateWr** [comment]
From Alec regarding the AddThis plugin:

> I spent some time fixing the AddThis plugin in OMP master. You can now set it up in the back-end (under "Generic Plugins" in the plugin management interface).
>
> It used to drop into the front end using a hook called "Templates::Catalog::Book::BookInfo::Sharing" but that's gone with the new front end. Feel free to introduce a new hook and change it in plugins/generic/addThis/AddThisPlugin.inc.php to suit. I think this is the method we decided on and it seems OK to me for the moment.

**Comment by asmecher** [comment]
That was a big one! Congrats.
