### ISSUE TITLE
OMP Catalog List does not show

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8362]
**Describe the bug**
At dashboard, if the user selects "Catalog" the "All Monographs" CatalogListPanel is not getting displayed 

**To Reproduce**
1. Go to Dashboard
2. Click on Catalog (underneath "Submissions")

**What application are you using?**
 OMP version 3.4.0

**Additional information**
The `CatalogListPanel` does not load because the `items` property receives `Object` instead of `Array`

---
**PRs**

**Branch `main`**
OMP: pkp/omp#1231

**Comment by NateWr** [comment]
@bozana could you review this?

**Comment by defstat** [comment]
@bozana I added [this](https://github.com/pkp/omp/pull/1231) PR with the one-liner syntax.
