### ISSUE TITLE
Submission search index not updating after deleting a submission

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8363]
**Describe the bug**
While deleting a new submission, the queue jobs `RemoveSubmissionFromSearchIndexJob` and `RemoveSubmissionFileFromSearchIndexJob` both are throwing exception while trying to update the submission search index . As a result, the submission search index associated table not getting updated properly which indicate broken search index data. 

**To Reproduce**
1. Create a new submission.
2. make sure that new submission related job has run . (either have a worker thread open or run cron or reload pages several time)
3. open the error log and see that there is few error such as `invalid.job.payload` at `Jobs/Submissions/RemoveSubmissionFromSearchIndexJob.php` file which indicate that job has failed .

**What application are you using?**
 OJS `main` branch .

**Additional information**
The error is occurring because of this check at https://github.com/pkp/pkp-lib/blob/main/Jobs/Submissions/RemoveSubmissionFromSearchIndexJob.php#L50-L54 . Here a submission is being tried to pull from DB but it's already deleted which is defined at https://github.com/pkp/ojs/blob/main/classes/submission/DAO.php#L31-L33. Here an event is fired but queue jobs does not get to run immediately . And by the time jobs get to run , that submission information already deleted form DB which cause the jobs to throw custom exception as not found in DB .

**Comment by touhidurabir** [comment]
@asmecher PRs to review

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8364
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3585

**Comment by asmecher** [comment]
Looks good, thanks, @touhidurabir! Before I merge these, can you also port to OMP and OPS?

**Comment by touhidurabir** [comment]
@asmecher All PRs

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8364
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3585
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/376
[omp](https://github.com/touhidurabir/omp) --> https://github.com/pkp/omp/pull/1227

**Comment by asmecher** [comment]
All merged/cherry-picked -- thanks, @touhidurabir!
