### ISSUE TITLE
Remove disable_path_info URL generation mode

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8365]
The `disable_path_info` setting in `config.inc.php` has been marked as deprecated since 3.2.0. It was originally introduced to work around servers that did not properly support `PATH_INFO` URLs, but those seem to have dwindled over the past ~10 years. The `disable_path_info` setting is known to misbehave with API-based requests, but we haven't had much complaint about it, suggesting the mode is not widely used (or that users who require it are using very old versions).

With this mode deprecated for several years, it's time to remove it and simplify all the related code.

**Comment by asmecher** [comment]
Once this is done, a logical next step would be to look into URL generation more broadly -- do better request-independent tools need solidifying? Can we delegate it to a Laravel-based toolset?

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/9761
- https://github.com/pkp/ojs/pull/4199

**Comment by asmecher** [comment]
@bozana, could you review the PR [linked above](https://github.com/pkp/pkp-lib/issues/8365#issuecomment-1960098852)? The `disable_path_info` feature has been deprecated since 3.2.0, partially broken since at least 3.3.0, and removed entirely since 3.4.0; I think we're safe to remove the last bits and pieces for 3.5.0, but I'm not sure if you intended to keep especially long backwards compatibility in the log file parsing stuff?

**Comment by asmecher** [comment]
Also, some of the log files couldn't be parsed in the upgrade tests -- but they don't appear to have path info disabled. Could you help me spot the problem there?

**Comment by jonasraoni** [comment]
@asmecher / @bozana, the upgrade is failing due to the lines below, so I've created a dumb PR (https://github.com/pkp/pkp-lib/pull/9836), but I just read the comments and I see the issue might goes deeper than that. Are we going to recover the old code (regarding `disable_path_info`) just to make it works? I think it's good to leave a couple of "@todo" to remember about removing everything later.

https://github.com/pkp/pkp-lib/blob/69e7baad781699d6bbdbf65124c3a0c35db2c0fe/classes/cliTool/traits/ConvertLogFile.php#L323-L325

**Comment by bozana** [comment]
Hi @jonasraoni, we will not recover the old code i.e. I only recovered it for log file conversion, for the users to be able to convert their old log files, also if they were suing disable_path_info. Thus, I think it should stay there as it is. Else, there are no other leftovers.
The upgrade script defines the isPathInfoDisabled() like this: https://github.com/pkp/pkp-lib/blob/stable-3_4_0/classes/migration/upgrade/v3_4_0/I8508_ConvertCurrentLogFile.php#L118.
Is this correct for the installation you are trying to upgrade? I.e. maybe there is the problem with the upgrade?

**Comment by bozana** [comment]
Oh, I see, wrongly Core::getPage() is used instead of $this->getPage()...

**Comment by bozana** [comment]
additional fix:
stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/9842
- https://github.com/pkp/ojs/pull/4226 (only submodule update)
- https://github.com/pkp/omp/pull/1538 (only submodule update)
- https://github.com/pkp/ops/pull/651 (only submodule update)

**Comment by bozana** [comment]
Can this issue now be closed?

**Comment by asmecher** [comment]
Yes! :tada:
