### ISSUE TITLE
[OMP] Hide inactive series in browse block plugin #1224

### ISSUE THREAD

**Issue by franz-dev** [pkp/pkp-lib#8366]
Browse Block plugin: When an inactive series is set from backend, you shouldn't view in 'browse' public frontend.

1. Enable Browse Block plugin
2. Set some series as inactive
3. Go to your site's home page

OMP version 3.3.0-13

[OMP Pull request #1224](https://github.com/pkp/omp/pull/1224)

Thanks.

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by asmecher** [comment]
Also ported to https://github.com/asmecher/browse.
