### ISSUE TITLE
Custom Locale on Site level

### ISSUE THREAD

**Issue by eddoff** [pkp/pkp-lib#8371]
**Describe the bug**
The Custom Locale Plugin does not work on site level

**To Reproduce**
1. Download the Custom Locale Plugin from the journal's plugin page. version 1.1.0.2
1. Enable the Custom Locale Plugin on site level i.e. at https://site.com/index.php/index/admin/settings#plugins
Then the administration settings and the site home website is not reachable for me. Hence the plugin cannot be disabled from the web interface.
2. I tried to disable the plugin on site level with this command in the database:
UPDATE plugin_settings SET setting_value='0' where context_id=0 AND plugin_name="customlocaleplugin";
Now the websites are loading but the plugins tab at site settings is not loading.
![image](https://user-images.githubusercontent.com/41610473/198009090-a47874df-71e4-4fa4-9253-c711bea84708.png)

3. Tried also to do 
DELETE from plugin_settings where context_id=0 AND plugin_name="customlocaleplugin";
but still the plugins list at https://site.com/index.php/index/admin/settings#plugins does not load

4. When removing the /plugins/generic/customLocale folder the website is now loading again. 
5. But when installing the plugin it again does not work to load the site plugin settings.
6. In another instance of OJS on the same server the plugin is installed and the site plugin settings are loaded. Is there another database record need to be changed?

**What application are you using?**
 OJS 3.3.0-13

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by jonasraoni** [comment]
Hi @eddoff!

This is a known issue, see: https://github.com/pkp/customLocale/issues/11.
If you have the technical skills, would you mind checking if [this PR works for you](https://github.com/pkp/customLocale/pull/14)?

Meanwhile I'll close this issue as duplicate, if you have some feedback about the PR, please, leave a message on the other issue.

p.s. As I've been touching this plugin recently, I might take a look on it.
