### ISSUE TITLE
PHP 8 requirement introduced by accident?

### ISSUE THREAD

**Issue by dersmon** [pkp/pkp-lib#8375]
WIth https://github.com/pkp/ojs/commit/ee93247a3f2dc083f5f220ac8f08b926df973426 PHP 7 throws  `PHP Fatal error:  Uncaught Error: Call to undefined function PHP81_BC\\strftime()`. Was that intended?

 OJS 3.3.0.13

**Comment by jonasraoni** [comment]
Hi @dersmon!

Did you update the composer packages? The `PHP81_BC\strftime` refers to this package: https://packagist.org/packages/php81_bc/strftime, which was added here: https://github.com/pkp/pkp-lib/pull/8342/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R28

**Comment by jonasraoni** [comment]
Great, better safe than sorry :)
