### ISSUE TITLE
Remove reply to link from DISCUSSION_NOTIFICATION email template body

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8379]
**Describe the bug**
As the work on the [email footer](https://github.com/pkp/pkp-lib/issues/8127) is finished, this kind of information (like a reply to or unsubscribe link) should be added to it instead rather than to the email template body. In the Discussion... mailables this leads to duplication:
```
...
<p>Reply to this message at 
<a href="http://localhost:8000/index.php/publicknowledge/workflow/access/1">
Journal of Public Knowledge</a>.
<hr>
Reply to this comment on <a href="http://localhost:8000/index.php/publicknowledge/workflow/access/1">
#1 Karbasizaed</a>
 ...
```

**To Reproduce**
1. Set the default email transport to `log` in config 
1. Go to the Submission workflow, e.g., copyediting stage
2. Click on 'Add discussion'
3. Compose a message and send it
4. See the email debugging information in the error log

**What application are you using?**
 OJS main branch

**Comment by Vitaliy-1** [comment]
PR to pkp-lib: https://github.com/pkp/pkp-lib/pull/8380

**Comment by NateWr** [comment]
Thanks @Vitaliy-1, did this email template exist in `stable-3_3_0`? If so we might need a migration, but I'm not sure.

**Comment by Vitaliy-1** [comment]
No, was added only to main
