### ISSUE TITLE
The stable branch isn't synchronizing the submodules

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8386]
**Describe the bug**
When opening a PR against the `stable` branch, only the `pkp-lib` submodule is synchronized, using the special commit message pattern (`##user/branchname##`).

**What application are you using?**
`stable-3_3_0`

**PRs**
- https://github.com/pkp/ojs/pull/3597
- https://github.com/pkp/omp/pull/1236
- https://github.com/pkp/ops/pull/383

**Comment by jonasraoni** [comment]
@asmecher I think it's not needed to port this down to branches < `stable-3_3_0`, right?

The PRs are here (just a copy of the current script):
- https://github.com/pkp/ojs/pull/3597
- https://github.com/pkp/omp/pull/1236
- https://github.com/pkp/ops/pull/383

**Comment by asmecher** [comment]
Merged, thanks; no, I don't recommend back-porting this further.
