### ISSUE TITLE
Email client safelink cause user password reset feature broken.

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8392]
**Describe the bug**
This issue ported from forum and details at https://forum.pkp.sfu.ca/t/e-mail-client-safelink-feature-expires-password-reset-confirmation-emails-sorry-the-link-you-clicked-on-has-expired-or-is-not-valid-please-try-resetting-your-password-again/75112/3

**To Reproduce**
1. Request for a password reset
2. Open the mail in MS Outlook and click on the given reset link
3. See that it shows message as `Sorry, the link you clicked on has expired or is not valid. Please try resetting your password again.`
4. Check mailbox again and see that a new password already mailed which cause by `safelink` feature to execute the code of `LoginHandler::resetPassword` before user redirected to the give link properly . 

**What application are you using?**
 OJS, OMP or OPS version `3.3.0-13` and `main`

**Additional information**
one possible solution already mentioned at https://forum.pkp.sfu.ca/t/e-mail-client-safelink-feature-expires-password-reset-confirmation-emails-sorry-the-link-you-clicked-on-has-expired-or-is-not-valid-please-try-resetting-your-password-again/75112/2?u=touhidur

#### Update
decided to implement the feature request from https://github.com/pkp/pkp-lib/issues/2135 to address this issue . It will change the entire password reset process so that outlook's safelink feature will not have any impact on process while it verify an included link in the mail .

**Comment by asmecher** [comment]
If someone is able to confirm whether or not the Safelink tool results in a `HEAD` request to OJS (as opposed to e.g. `GET`), it'll help us know how to fix this!

**Comment by touhidurabir** [comment]
> someone is able to confirm whether or not the Safelink tool results in a HEAD request to OJS (as opposed to e.g. GET)

@asmecher I am thinking that what we can do it is to check for any request in the `LoginHandler::resetPassword` that is not a `GET` and redirect back to site/context home page . I think that way we can resolve this one .

**Comment by touhidurabir** [comment]
@asmecher PRs to review . 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8400
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3602

if this PRs got accepted , I will forward port it for the `stable 3.3.0`

**Comment by asmecher** [comment]
Thanks, @touhidurabir, I've added a comment on the PR:

https://github.com/pkp/pkp-lib/pull/8400/files#r1013310927

Before we merge this, I'd like to identify someone with Outlook and verify that safelink actually *does* use a `HEAD` request.

**Comment by asmecher** [comment]
Unfortunately it looks like safelink does not use HEAD requests.

The solution will be to change the password reset process so that the user is presented with a button that triggers a form POST to perform the actual action.

**Comment by touhidurabir** [comment]
> Unfortunately it looks like safelink does not use HEAD requests.

is this confirmed ? 

> The solution will be to change the password reset process so that the user is presented with a button that triggers a form POST to perform the actual action.

If that is the path we need to take, the I think we need to first take user to page from the given link in mail which prompt to confirm the password reset via a button and then make a post request form there . Then after the successful reset, redirect to page what shows message such as 

***Password reset completed successfully. Please check your mail for new updated password*** . 

@asmecher what do you think about above workflow ? But to me that seems bit verbose so any suggestion to shorten it .

**Comment by asmecher** [comment]
@touhidurabir, yes, something like that might be necessary. But please have a look over https://github.com/pkp/pkp-lib/issues/2135 -- this has been on the wish list for a while and might be good to implement at the same time as you resolve the safelink issue.

**Comment by touhidurabir** [comment]
> But please have a look over https://github.com/pkp/pkp-lib/issues/2135

@asmecher that one way to get around of it and I also think such workflow is better for password reset . But I think we decided not to implement it as we plan to move to laravel's auth process in future version if I am not mistaken. However it may be a good opportunity to update our password reset process .

**Comment by touhidurabir** [comment]
After a discussion with @asmecher, we have decided to implement the feature request from https://github.com/pkp/pkp-lib/issues/2135 to address this issue . It will change the entire password reset process so that outlook's safelink feature will not have any impact on process while it verify an included link in the mail .

**Comment by asmecher** [comment]
Fixed by #2135!
