### ISSUE TITLE
Translations do not respect the loading order of locale files

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8394]
**Describe the bug**
When using the `AppLocale::registerLocaleFile()` with the argument `$addToTop = true`, it's expected the given locale file will have preference over the others when looking for a translation. But the code isn't satisfying this expectation.

The problem is located here:
https://github.com/pkp/pkp-lib/blob/5de2f5e6f7d6102f4ade90e8b3bb9db6af26a0df/classes/i18n/PKPLocale.inc.php#L265

The `registerLocaleFile()` adds the locale to the top, while the loop, which attempts to find a translation, is starting from the end.

**What application are you using?**
`stable-3_3_0` (probably others)

**Additional information**
Given that it has been broken for 11 years, perhaps it makes sense to change the parameter to `$addToBottom`?

**PRs for `stable-3_3_0`**
- https://github.com/pkp/pkp-lib/pull/8454
- **TESTS ONLY** https://github.com/pkp/ojs/pull/3637

**Comment by asmecher** [comment]
What is `$addToTop` being used for? (What are the motivating examples?) If it's been broken for 10 years, we might just consider removing it.

**Comment by jonasraoni** [comment]
@asmecher A use case for this would be the `customLocale` plugin, to ensure the customizations have preference.

Given that `false`, actually means `true` for this argument, then it's being used properly here:
https://github.com/pkp/customLocale/blob/d2d717d93903fd3b7059cdfa25e103651391b912/CustomLocalePlugin.inc.php#L40

But any locale file loaded after that (other plugins?!) will steal the preference from the `customLocale` 😁

I don't think this method is used often in the wild, so it's probably ok to either remove or fix it... If we fix, then we just need to consider the `customLocale` code (e.g. releasing a plugin update that breaks on OJS X, but works on Y).

**Comment by asmecher** [comment]
We can handle precedence of registration for plugins using the plugin sequence (`$plugin->getSeq()`); this was used for block plugins but at a glance that use case might've been implemented some other way with the settings rewrite. I'm in favour of removing `$addToTop`.

**Comment by jonasraoni** [comment]
Agreed! Here's the small PR for `stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8454
- **TESTS ONLY** https://github.com/pkp/ojs/pull/3637

**Comment by asmecher** [comment]
That looks fine to me, @jonasraoni; please merge and forward-port to `main`.

**Comment by jonasraoni** [comment]
I see I've erased this code at `main`, so there's nothing to port :)
