### ISSUE TITLE
Improve DublinCoreMetaPlugin

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8406]
There are a few things that should be considered in the DublinCoreMetaPlugin:
- get rid of the deprecated submission methods, use publication instead
- chapters (OMP) -- e.g. DOIs, URL
- the URL for book files is wrong
- see if we can get rid of wait in the test
- empty content 
E.g. if abstract only exists in one locale and for the other it is empty, the following DC element will be displayed:
`<meta name="DC.Description" xml:lang="fr" content=""/>`
Adapt the DublinCoreMetaPlugin so that it does not consider/display empty content.
I am not sure where the empty content in the DB comes from, because when using the UI forms they are not saved if empty.

**Comment by bozana** [comment]
@asmecher, should the DC meta elements be displayed on the galley i.e. file view page in OJS, as this is the case in OMP? 
Or should the OMP be change so that the DC elements are only displayed on the book/chapter view page (as this is the case for GoogleScholarPlugin)?
Currently, in OMP, the only difference between the DC elements on the submission and representation/file view page are the elements DC.Identifier and DC.Identifier.URI. 
If we would like to keep the DC elements on both pages (submission and representation), then eventually also DC.Format , DC.Identifier.DOI, DC.Language and DC.Type could be changed to only display values of that particular representation?
Something else? :thinking:

**Comment by bozana** [comment]
This Issue changes/improves the following:
OJS and OMP:
- replaces deprecated submission methods
- fixes DC.Contributor.Sponsor: instead of not existing article->getData('sponsor') the publication->getData('submissionAgencies') is used
- does not display empty elements
- adds subjects (additionally to the existing keywords) -- to be the same as in OMP and GoogleScholar
- changes the way the keywords and subjects are get: instead of using the SubmissionKeywordDAO and SubmissionSubjectDAO the publication->getData() is used
- some small changes in code, like e.g. instead of using `$i` to differentiate template headers use $`locale` if already there, or use `$i` from already existing `foreach` loops.
additionally in OMP:
- considers the chapter pages
- considers submission file DOIs/URNs on submission file page 

The way the subjects and keywords are get is also changed in GoogleScholar plugin

**Comment by bozana** [comment]
PRs:
- https://github.com/pkp/googleScholar/pull/12
- https://github.com/pkp/ojs/pull/3746
- https://github.com/pkp/omp/pull/1322

**Comment by bozana** [comment]
Hi @asmecher, 
For the representation i.e. submission file view pages I left everything as it was. This I can approach later, if needed.
Else s. https://github.com/pkp/pkp-lib/issues/8406#issuecomment-1419244982 for the changes I have made now.
Could you please review the PRs above?

**Comment by bozana** [comment]
Hi @asmecher, thanks a lot for the review! I considered everything (s. the last commits). 
Additionally:
In OMP I also considered chapter for datePublished and pages, and I changed the way we assure the DC meta elements are displayed only for the current version when viewing a file (see the comment there). 
In OJS now I get the section from the TemplateManger.
OK so?

**Comment by asmecher** [comment]
Yes, I can't think of any problem with those approaches. Please go ahead, thanks!
