### ISSUE TITLE
Restructure the implementation of queue jobs related files/classes to match current class file structure

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8409]
**Describe the Problem**
The current implementation of queue/job system distributed into multiple folders and namespace which does not match the internal structure of other functionality across the app. This cause quite a bit confusion and hard to track class files used for what purpose . At the same time this makes it harder to track down the execution flow and integration of new functionality in the queue/job system .

**Current Structure**
1. A job cli tool resides in the shared lib `lib/pkp` at the path `tools/jobs.php`
2. A core service provider for queue managements in the shared lib `lib/pkp` at the path `classes/core/PKPQueueProvider.php`
3. Job classes located in the shared lib `lib/pkp` at the `Jobs` . The same conversion followed for other apps(e.g `OJS`, `OMP` and `OPS`).
4. Models, repositories, interfaces and custom queue manager classes located in the shared lib `lib/pkp` at the path `Domains/Jobs`
5. The base model, repo, few more interfaces etc contains within the shared lib `lib/pkp` at the path `Support`. 

The major confusion comes from the distributed codes between the `Domains/Jobs` and `Support` located in the shared lib `lib/pkp` . 

**Proposed Structure**
1. The job classes with remain as same as it is as it's better to have those into it's own separate path/namespace .
2. The merge of `Domains/Jobs` and `Support` and move those to the namespace `PKP` that is to the `classes` folder of shared lib `lib/pkp` 
    - Have a new folder named `job` where most of the core repository, interfaces, models will be put . 
    - Have a new folder named `queue` that will contains the custom queue manager classes such as `WorkerConfiguration.php`, `JobRunner.php` etc . 
3. The base job and test job classes need to be moved to core job namespace . 
4. Keep the CLI tool and core Service Provider as it is . 

### PRs
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8410
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3612
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1287
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/422

**Comment by asmecher** [comment]
@touhidurabir, it looks like the OJS tests are failing; can you take a look and ping me when it's ready for a review?

**Comment by touhidurabir** [comment]
@asmecher I am bit confused why the Travis tests are failing at the end . I can see that all the cypress tests and units test are getting done . But at the end of log file, this is showing

```
OK, but incomplete, skipped, or risky tests!
Tests: 224, Assertions: 845, Skipped: 2.
cat: lib/pkp/tests/results/coverage.txt: No such file or directory
The command "./lib/pkp/tools/travis/run-tests.sh" exited with 1.
```

Any suggestion ?

**Comment by asmecher** [comment]
The coverage tests are described in `lib/pkp/tests/phpunit.xml`:
```xml
    <coverage>
        <include>
            <directory suffix=".inc.php">./../classes</directory>
            <directory suffix=".inc.php">./../api</directory>
            <directory suffix=".inc.php">./../controllers</directory>
            <directory suffix=".php">./../Domains</directory>
            <directory suffix=".inc.php">./../pages</directory>
            <directory suffix=".php">./../Support</directory>
        </include>
        <report>
            <text outputFile="results/coverage.txt" showUncoveredFiles="false" showOnlySummary="true"/>
        </report>
    </coverage>
```
It's strange that PHPUnit isn't triggering an error, but I wonder whether it's failing to generate the report because you've moved `Domains` and `Support` elsewhere and the other code has been renamed to `.php` instead of `.inc.php`. Maybe try changing the `.inc.php` entries to `.php`, and correcting/removing the `Domains` and `Support` paths as necessary.

**Comment by touhidurabir** [comment]
@asmecher Thanks for the tip . it worked nicely and all tests are passing . Please review the PRs if all ok , I will forward port it  to `OMP` and `OPS` .

**Comment by asmecher** [comment]
Sorry, this will be a bit of a pain, but could you standardize paths to lowerCamelCase to match the rest of the system? `Jobs` should be `jobs`, for example.

**Comment by touhidurabir** [comment]
@asmecher please take a look at this now . Tests are finally passing .

**Comment by asmecher** [comment]
Thanks, @touhidurabir, this looks good! Can you...
1. Rebase the existing OJS and pkp-lib PRs
2. Port this to OPS and OMP main?

Then, once the tests all pass, I can merge!

**Comment by touhidurabir** [comment]
@asmecher PRs are rebased and ported to `OPS` and `OMP` . Please check now . If the tests for `OMP` and `OPS` passed, it's good to merge .

**Comment by asmecher** [comment]
All merged -- thanks, @touhidurabir!
