### ISSUE TITLE
Spell checker doesn't work at administrative pages

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8411]
**Describe the bug**
The browser spell checker is disabled for all input components at the administrative pages.

This is caused by TinyMCE which deliberately inserts a `spellcheck="false"` at the `body` tag if it's not setup to use a custom/browser spell checker. Setting up TinyMCE to use the browser spell checker fixes the issue.

**To Reproduce**
1. Access any administrative interface that has text inputs
2. Type something wrong
3. Check if the browser spell checker highlighted something

**What application are you using?**
*/stable-3_3_0
*/main

**PRs**
**`stable-3_3_0`**
- https://github.com/pkp/pkp-lib/pull/8412
- https://github.com/pkp/ui-library/pull/228
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3613

**`main`**
- https://github.com/pkp/pkp-lib/pull/8413
- https://github.com/pkp/ui-library/pull/229
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3614

**Comment by jonasraoni** [comment]
Hi @NateWr! I think this one is better for you to take a look.

**Comment by jnugent** [comment]
+1 for this - we've tested it on a hosted installation and the fix works nicely.

**Comment by NateWr** [comment]
Thanks for hunting this down, @jonasraoni. All merged to `stable-3_3_0` and `main`. :tada:

**Comment by jnugent** [comment]
Hi everyone, a hosted client has let us know that this is still an issue on modal windows that contain TinyMCE forms, like the modal for editing a user's data.  An example would be an affiliation field.  Is there a way to get the patch here extended to cover that extra use case?

**Comment by jonasraoni** [comment]
Thanks @jnugent! I thought I had patched it everywhere, I'll take a look :)

**Comment by jonasraoni** [comment]
I just saw this attribute has some `browser-defined` magic. Firefox for example doesn't enable the spell checker by default for simple inputs, only textareas. So, in order to have a homogeneous behavior we would have to force it, by adding a `spellcheck="true"` to a top-element...

I can't see problems here, so I don't have anything against 👌

The only negative note is that the spell checker might be done online (https://www.otto-js.com/news/article/chrome-and-edge-enhanced-spellcheck-features-expose-pii-even-your-passwords) 😁
But at this point, I think all users are already fully compromised, unless they disable the extended spell checker on their browsers.
