### ISSUE TITLE
Improve the configuration for the OAI endpoint

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8414]
**Describe the bug**
At this moment it's possible to limit the number of records which are retrieved for the `ListRecords` verb through the configuration file (`[oai].oai_max_records`), but it's not possible to limit the `ListIdentifiers` (defaults to 500) nor the `ListSets` (defaults to 50).

It might be worth to skim the code, to check if there's something affecting the performance (see the forum post below).

**What application are you using?**
*/main
*/stable-3_3_0

**Additional information**
Here's a forum post where the user is having performance issues:
https://forum.pkp.sfu.ca/t/ojs3-3-0-13-and-oai-validator-oaipmh-com-listidentifiers-request-time-too-much-time/75372

**Comment by asmecher** [comment]
@jonasraoni, before jumping into adding another configuration option, I'd suggest verifying with the user that some of the usual database issues don't apply -- for example, mixed InnoDB and MyISAM tables. The performance of `ListIdentifiers` verb has never been a (reported) performance problem before, including on some very large repositories.

**Comment by jonasraoni** [comment]
Thanks for the information, I've just assumed the performance would be a bit similar to the `ListRecords` (very similar tables and thus engines), but perhaps the user isn't even using MySQL, I've just asked for more information :)
