### ISSUE TITLE
Multiple emails use the same email template

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8420]
**Describe the bug**
The changes in #5716 mean that every `Mailable` that can be configured from Settings > Workflow > Emails > Manage Emails must have a unique email template. However, several mailables use the `NOTIFICATION` email template. These mailables should be refactored so that each one uses a unique email template.

**To Reproduce**
1. Go to Settings > Workflow > Emails > Manage Emails.
2. Click on "Edit" for one of these emails: Publication Version Notification, Edit Review Notification, Reviewer Commented Notify Editors.
3. Try to edit the template to be different for each email.
4. See that changes effect all emails.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
I think it's probably enough, for now, to create an entry for each in `emailTemplates.xml` and use the same subject/body locale keys. We'll also need a migration to install these new templates. Hopefully we can get rid of the `NOTIFICATION` template completely.

**Comment by NateWr** [comment]
There is a `Notification` trait for the mailables that can be removed, maybe. If so, it uses these locale keys which we can maybe remove:

- emailTemplate.variable.notificationContents
- emailTemplate.variable.notificationUrl
- emailTemplate.variable.unsubscribeLink

**Comment by Vitaliy-1** [comment]
`NOTIFICATION` template was replaced by the template for each notification type and removed as a part of https://github.com/pkp/pkp-lib/issues/7874
