### ISSUE TITLE
LOCKSS email templates are not associated with a mailable

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8421]
**Describe the bug**
In OJS, there are two email templates defined in `emailTemplates.xml` that do not have any mailables associated with them. These are `LOCKSS_EXISTING_ARCHIVE` and `LOCKSS_NEW_ARCHIVE`.

Someone needs to investigate whether these email templates are used or not. If so, they should be converted to use the mailables system. If not, they should be removed from `emailTemplates.xml`.

**What application are you using?**
`main` branch (3.4 pre-release)

**Comment by NateWr** [comment]
@asmecher do you know where I should look to find out if these email templates are used (LOCKSS)?

**Comment by asmecher** [comment]
@NateWr, there have been a lot of twists and turns in the related code, but in OJS 2.x there was a setup form that looked like this (from OJS in an Hour):
![image](https://user-images.githubusercontent.com/200411/213815979-b5132965-754b-4b61-bb0c-91c3a165db4d.png)

The links `(i) libraries participating in LOCKSS` and `(ii) libraries not yet participating in LOCKSS` went to email compose forms with the `LOCKSS_EXISTING_ARCHIVE` and `LOCKSS_NEW_ARCHIVE` templates, respectively. (There was no special code for the sending of these; they used the old email handler, which could optionally receive a `template` parameter for managers/admins.)

The code went out with 3.0.x including URLs to these compose forms, but the associated locale keys no longer made use of them so they were never presented. Starting with 3.1.0 that part was removed too.

I think these templates can be removed entirely.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/8563
https://github.com/pkp/ojs/pull/3721

@asmecher these PRs remove several locale keys from pkp-lib and ojs (main), so it might be best to wait to do the locale summit stuff. Should be merged within 24 hours unless I've done something dumb to the tests. :)

**Comment by asmecher** [comment]
Thanks for the heads-up, @NateWr -- I won't commit the locale file rearrangement until after next Monday's dev call.

**Comment by NateWr** [comment]
Merged to `main`.
