### ISSUE TITLE
Unable to define which mailables are used by each application

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8424]
**Describe the problem**
`Mailer::scanMailables()` will search the `/mail/mailables` directory at the application and `lib/pkp` layers and return any `Mailable` classes that it finds. However, for convenience, we will often keep mailable classes or parent classes in the `lib/pkp` directory, even though they are not used for every application.

The most common use case is mailables related to OJS and OMP stages which are not supported in OPS. Some examples of this are `DiscussionSubmission`, `DiscussionReview`, `DiscussionCopyediting`, as well as all of the mailables related to editorial decisions in the submission, review and copyediting stages. These are a lot of files and it wouldn't be good to have to maintain duplicates of them, even just empty class containers, in OJS and OMP to keep them out of `lib/pkp`.

**Describe the solution you would like to see**
I don't care too much what the solution looks like, but I think the simplest solution is to have a central registry of mailables supported by the application. This could just be a repository method that returns the supported class names. Maybe it just integrates with `PKP\mail\Repository::getMany(...)`?

Other solutions I can think of, like giving each mailable a function which it can override to say whether it is enabled, seem like they will lead to more code boilerplate and spread out the logic into dozens of classes.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
@Vitaliy-1 I'll assign this one to you to think about since you understand the loading sequence best.

**Comment by Vitaliy-1** [comment]
Also relevant for `PKP\mail\Repository::get(...)`

**Comment by Vitaliy-1** [comment]
pkp-lib: https://github.com/pkp/pkp-lib/pull/8464
OJS: https://github.com/pkp/ojs/pull/3645
OMP: https://github.com/pkp/omp/pull/1264
OPS: https://github.com/pkp/ops/pull/403

**Comment by Vitaliy-1** [comment]
Tests for OMP are still running but I think it's ready to go. @NateWr, can you take a look at these PRs?
