### ISSUE TITLE
Description of {$skippedSubmissions} email variable unclear

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8425]
**Describe the bug**
Once #5716 is merged, the new email management UI will be in place. In this UI, editors can manage all of the email templates with email template variables like {$submissionUrl}. In the "Statistics Report Notification" email, there is a variable, `{$skippedSubmissions}` with the description, "The number of skipped submissions".

It's not clear what this means for an editor who is editing this template.

**To Reproduce**
1. Wait for #5716 to be merged to `main`.
2. Go to Settings > Workflow > Emails > Manage Emails > Add and Edit Templates.
3. Find the Statistics Report Notification email and click Edit.
4. Click the Insert Content button above the email body editing field.
5. Find the `{$skippedSubmissions}` variable and see the description.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
@jonasraoni I think this email variable is maybe the "Other Submissions" in the editorial stats. Is that right? If so, can you provide a description of what this includes that an editor might understand?

**Comment by jonasraoni** [comment]
I'm working on a related task, I'll take a look and perhaps update the constant there :)

**Comment by jonasraoni** [comment]
The "Other Submissions" refers to submissions which are ignored by the statistics, this is the extended description for it:

> This includes submissions that are not counted in other totals, such as those that are still in progress and those that appear to have been imported.

After the #7709, the count for both the "imported" and "in progress" submissions are also displayed, which helps to make things clearer:

![image](https://user-images.githubusercontent.com/361921/204157551-ce84e018-ff3e-42bc-94c9-699bd365003b.png)

**Comment by NateWr** [comment]
Completed in https://github.com/pkp/pkp-lib/commit/65ec1df5a880429bc4bc77e3cd7dfdb0ea7b3d9c.
