### ISSUE TITLE
Implement statistics dimensions settings

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#843]
The default statistic plugin in OJS aggregates stats by city. Most of the users so far don't need that. We also want to implement another dimension (institution), and this also is not a requirement for most of the users. 

It would be good to have a place in the plugin settings page to control which extra dimension one would want to use for their site.

**Comment by ctgraham** [comment]
+1

**Comment by asmecher** [comment]
@ctgraham, I merged this after reading but not testing. If you need this and manage to give it a quick spin, I'd appreciate the feedback. Thanks, @beghelli!

**Comment by beghelli** [comment]
Just to keep track the need to port to master

**Comment by beghelli** [comment]
Maybe that's not a good idea, will use another issue number.

**Comment by ctgraham** [comment]
@beghelli , for existing installs, won't this change disable the city and region collection for users who don't explicitly turn it on after upgrading?  Is this intended?

**Comment by beghelli** [comment]
@ctgraham 
Actually I didn't thought about that. I add the settings to keep everything as it was before the upgrade, and then users can disable those dimensions after that. Thanks
