### ISSUE TITLE
[OJS] Enabling ordering mode with no journals

### ISSUE THREAD

**Issue by nmpx** [pkp/pkp-lib#844]
Fresh install of OJS 3.0b. I clicked the 'order' button to see it. 

The result brings up a 'done' button and another link to 'cancel ordering', except that clicking either does nothing. And you can't click either 'order' or 'create a journal'. Essentially... you're trapped on this page.

Refreshing does 'unfreeze' it but.... Here's a screenshot.
 
![ojs-bug](https://cloud.githubusercontent.com/assets/5183702/10793474/7040c248-7d67-11e5-95d4-89cb80e3e576.png)

**Comment by asmecher** [comment]
Thanks for reporting, @nmpx. @beghelli, I think this is probably a boundary condition in the ordering stuff for when the list is empty; probably a JS error.

**Comment by NateWr** [comment]
I'd recommend just hiding the order button if the grid is empty, if that's an easy thing to do. Happy to take a look at it.

**Comment by beghelli** [comment]
@NateWr , if you did nothing related to this, I can fix it. Just let me know.

**Comment by NateWr** [comment]
@beghelli Go for it! I won't be looking at stuff again until Monday and this probably won't be near the top of my list. Thanks!

**Comment by beghelli** [comment]
This bug was happening because of feature class error, in PHP land, fixed. Also discovered that the ordering was not working due to the removal of the 'element' class in the grid rows, fixed. And finally implemented what Nate suggested.

**Comment by asmecher** [comment]
@beghelli, is this ready to be closed?

**Comment by beghelli** [comment]
yes, closing it now.
