### ISSUE TITLE
OMP: Press cannot be disabled

### ISSUE THREAD

**Issue by felixhelix** [pkp/pkp-lib#8449]
Applies to OMP Version 3.3.0.10

Once enabled, presses cannot be disabled again. The error message in the log is 

`Slim Application Error:\nType: Error\nMessage: Call to undefined method Publication::getIsAvailable()\nFile: /var/www/html/classes/publicationFormat/PublicationFormatTombstoneManager.inc.php\nLine: 89\nTrace: #0 /var/www/html/classes/services/ContextService.inc.php(64): ...`

Looking at the specified location in PublicationFormatTombstoneManager.inc.php I found that there happens to be a misnomer: In line 89 it reads:

`
if ($publication->getIsAvailable()) {
`

While it probably should be
`
if ($publicationFormat->getIsAvailable()) {
`

Changing this removes the error and allows presses to be disabled.

**Comment by asmecher** [comment]
Thanks for catching this, @felixhelix -- can you add a pull request with that change?

**Comment by felixhelix** [comment]
Dear @asmecher 
I just saw that the issue has already been solved in the current file ([PublicationFormatTombstoneManager.php](https://github.com/felixhelix/omp/blob/74347ab0f9233ea4cf2b05b6cbea0c1ecef8efb0/classes/publicationFormat/PublicationFormatTombstoneManager.php) line 174) 
: )
So this can be closed.

**Comment by asmecher** [comment]
Good spotting -- thanks!
