### ISSUE TITLE
Allow inheritance of DOI export -> Crossref export -> EZID export

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#845]
Right now, DOIExportPlugin duplicates the logic of checking for DOIs as a check for exportability.  This should be a call to the existing `canBeExported()` method.  See, for example:
https://github.com/pkp/ojs/blob/ojs-2_4_7-0/plugins/importexport/datacite/classes/DOIExportPlugin.inc.php#L1041

Calling `$this->canBeExported()` when listing articles for export allows inheriting classes, such as CrossRefExportPlugin or EZIDExportPlugin, to reuse the existing method, while retaining more limiting (for Crossref) or expanded (for EZID) criteria for what can be exported.

**Comment by ctgraham** [comment]
I think this can be scheduled against 2.4.8 and closed.

**Comment by asmecher** [comment]
Thanks, @ctgraham!
