### ISSUE TITLE
[OJS 3.3.0.13] Reviewer cannot download file

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#8455]
I'm getting the following error on one submission, not sure what happened, the file can be download just fine by the editors.

```
PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedName() on null in /lib/pkp/controllers/api/file/FileApiHandler.inc.php:109
Stack trace:
#0 /lib/pkp/classes/core/PKPRouter.inc.php(395): FileApiHandler->downloadFile(Array, Object(Request))
#1 /lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#2 /lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route(Object(Request))
#3 /lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))
#4 /index.php(68): PKPApplication->execute()
#5 {main}
  thrown in /lib/pkp/controllers/api/file/FileApiHandler.inc.php on line 109, referer: https://periodicos.fclar.unesp.br/alfa/reviewer/submission/15025
```

I've also found this forum post with the same error but no answers https://forum.pkp.sfu.ca/t/reviewer-unable-to-download-file-ojs-3-3-0-11/73735

**Comment by luizbgomide** [comment]
I've checked and the database for this particular file and in `submission_files` those columns are `null`:

- viewable
- assoc_id
- genre_id
- direct_sales_price
- sales_type
- assoc_type

**Comment by asmecher** [comment]
@luizbgomide, it'll be the `genre_id` that's causing the problem. Try applying https://github.com/pkp/pkp-lib/commit/fd848fdfc212ac4c98952ae1d01c9ef6897f5ed6 in `lib/pkp` and see if that fixes the issue.

**Comment by luizbgomide** [comment]
@asmecher thanks for the quick reply. I applied the fix and it worked.

What would cause the `genre_id` to be `NULL`? I just checked my database and among 52615 submission_files I have just 48 files like that.

**Comment by asmecher** [comment]
@luizbgomide, those will be reviewer files -- for reviewers that e.g. annotated original submissions and uploaded that as their review. It sounds like most of your reviewers are using the text boxes instead.

**Comment by luizbgomide** [comment]
But this particular file that triggered the error was an original submission, it was supposed to be an Article Text, but I'm not sure hwo it got a null genre.

**Comment by asmecher** [comment]
I'm not sure... Perhaps it was attached to a genre that was deleted from the journal config at some point?
