### ISSUE TITLE
upgrade.php fails while upgrading from OJS version 3.3.0-13 to dev version of 3.4

### ISSUE THREAD

**Issue by Falk358** [pkp/pkp-lib#8458]
**Describe the bug**
Our system is currently on OJS 3.3.0-13. When trying to migrate a test copy of our production system's database to version 3.4 with the following commit id: 45903d1e09006281a7a637720dc7880e27475408, by running *upgrade.php* we get the following error:
```
Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dev0`.`#sql-alter-2dccaa-10`, CONSTRAINT 
`notification_subscription_settings_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE) in /home/dev0/jstatsoft-ojs3/html/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctr
ine/DBAL/Driver/PDOStatement.php:117 
``` 
We did not get this error before upgrading our production OJS 3.3.0-13, (we were on 3.3.0-7 before this)

To summarize: 
3.3.0-7 -> 3.4 upgrade works fine without any errors
3.3.0-13 -> 3.4 throws the error above

**To Reproduce**
1. delete content of html `sudo rm -rf html`
2. run  `git clone https://github.com/pkp/ojs.git html`
`(cd html && git submodule update --init --recursive && \
cp config.TEMPLATE.inc.php config.inc.php && \
composer --working-dir=lib/pkp install && \
composer --working-dir=plugins/paymethod/paypal install && \
composer --working-dir=plugins/generic/citationStyleLanguage install && \
npm install && npm run build)`
3. run a script which copies the database of the live system (database version OJS 3.3.0-13) onto our test system
4. `(cd html && php tools/upgrade.php upgrade)`
5. See error

**What application are you using?**
 OJS, OMP or OPS version 3.3.0-13
upgrading to : OJS 3.4 development branch on commit 45903d1e09006281a7a637720dc7880e27475408

**Comment by asmecher** [comment]
@Falk358, we can't provide support on pre-release code -- but I suspect you have bad data in the `notification_subscription_settings` table in your 3.3.x installation that's causing an error during upgrade.

**Comment by Falk358** [comment]
Thats understandable, thanks for the hint anyway!
