### ISSUE TITLE
DOAJ plugin missing ORCID iD in JSON request to DOAJ API

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#8462]
**Describe the bug**
While the DOAJ export plugin includes the ORCID iD of an author in the exported XML, it does not so in the JSON that is sent to the DOAJ API.

See https://forum.pkp.sfu.ca/t/bugs-in-doaj-export-plugin-orcid-id-missing-in-json-registration-of-duplicates-possible/75673

**To Reproduce**
See https://forum.pkp.sfu.ca/t/bugs-in-doaj-export-plugin-orcid-id-missing-in-json-registration-of-duplicates-possible/75673

**What application are you using?**
OJS 3.3.0-13

PR: 
- https://github.com/pkp/ojs/pull/3894
- https://github.com/pkp/ojs/pull/3899

**Comment by bozana** [comment]
Hi @asmecher, could you take a look at the small change here?

**Comment by bozana** [comment]
@asmecher, it would be nice if these changes could also go into 3.4, but...
