### ISSUE TITLE
Citation Style Language plugin fails to extact first letter of name if name begins with a unicode character

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#8468]
**Describe the bug**
A client reported that the CSL plugin, which normally generates a series of initials for given names, fails to do so if an author's name begins with a character like Å.  In that case, it falls back to including the full name (and then initials of middle and other names).

I tracked this down to the StringHelper.php class that comes with the Seboettg vendor library that ships with the plugin.  There is a method in there called `initializeBySpaceOrHyphen` that takes a name, extracts initials, and then returns the string.  However, the problem is that the string being passed in here in this author case is not Å, it's \xc3\x85 and there is a test in this method to see if this is a latin string.  It's not a latin string, but the method thinks it is, so the method then calls ctype_upper which is a Latin only method, and that fails.  The default return in the case of failure is the entire name. 

Inverting the test for the Latin check fixes this problem and the correct single letter is returned.   This database is entirely utf8, and I've also tested this problem on a new server with the utf8mb4 collations and it persists there too.  I can probably submit a composer patch to fix this in the library but I'd appreciate a bit of extra testing if possible.

**To Reproduce**
1. Create a submission that has author names beginning with UTF characters.
2. Examine the CSL plugin and confirm that the author name is not being "initialed". 

**What application are you using?**
OJS 3.3.0.13

**Comment by asmecher** [comment]
@jnugent, wouldn't this be more appropriate submitted to the citeproc-php repository? The developer has been quite responsive in the past. See e.g. this potentially-related issue: https://github.com/seboettg/citeproc-php/issues/46

**Comment by jnugent** [comment]
@asmecher I can definitely do that.  I'd still like a confirmation that the problem exists in another installation, though.  I've confirmed it on another one of our installations on a different server, but many of our servers are configured in a similar way.

**Comment by asmecher** [comment]
I'd suggest trying to replicate the issue with citeproc-php outside of OJS using the citeproc-php example script, similar to what's described here:
https://forum.pkp.sfu.ca/t/citation-style-language-punctuation-issue-ojs-3-1-2-4/60314/10

**Comment by jnugent** [comment]
@asmecher thanks for that link. I've cloned the example test and have confirmed that if an author name begins with a UTF-8 character, the name is not initialized.

**Comment by asmecher** [comment]
:+1: Great, that simplifies things! Please drop the issue into the citeproc-php repo, and add a link back to this for tracking purposes. The dev over there has been very good with rapid responses, especially if there's clear reproduce code. If it results in a quick fix that's easily back-portable e.g. to `stable-3_3_0`, I'll re-open this issue to track the commits required for updating our version requirements for the resulting citeproc-php release.

**Comment by jnugent** [comment]
https://github.com/seboettg/citeproc-php/issues/146

**Comment by ronste** [comment]
Hi @jnugent ,

just to let you know, one of our journals reported the same bug:

[https://www.cgt-journal.org/index.php/cgt/article/view/11](https://www.cgt-journal.org/index.php/cgt/article/view/11)
