### ISSUE TITLE
File download is not being logged anymore

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#847]
The problem was introduced by the usage of the request object when logging events in the usage stats plugin. The problem is that for file downloads, the hook download finished is called after a clean registry action.

**Comment by beghelli** [comment]
Needs porting to OMP and OJS master after the privacy work is there

**Comment by bozana** [comment]
@beghelli, I ported it to OMP stable, s. https://github.com/pkp/omp/pull/137. I believe it can be cherry-picked to OMP master then :-)
