### ISSUE TITLE
OMP Google Scholar Plugin causes 500 error with Language metadata

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#8473]
**Describe the bug**
Enabling `Language` metadata field in OMP and filling in data will cause 500 error on the monograph landing page if Google Scholar plugin is enabled.

`PHP Fatal error:  Uncaught TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given in plugins/generic/googleScholar/GoogleScholarPlugin.inc.php:90`

The error is caused here because `$languages` is a multidimensional array: https://github.com/pkp/omp/blob/main/plugins/generic/googleScholar/GoogleScholarPlugin.php#L104-L109

We could fix this, but the OJS/OPS Google Scholar plugin does not use this data for displaying the `citation_language`. Instead, the publication locale is used: https://github.com/pkp/googleScholar/blob/main/GoogleScholarPlugin.inc.php#L114-L116

**So I suggest that we do the same for OMP and use the Publication locale to fill in the data for citation_language.**

**To Reproduce**
1. Enable Language metadata field and add data to that field for some submission and publish the submission
2. Enable google scholar plugin
3. see the submission landing page

**What application are you using?**
OMP 3.3.0 but applies to OMP main branch as well

**Comment by asmecher** [comment]
@bozana, since the proposed change affects the distribution metadata, assigning to you for a look!

**Comment by bozana** [comment]
PRs:
omp main: https://github.com/pkp/omp/pull/1270
omp stable-3_3_0: https://github.com/pkp/omp/pull/1271

**Comment by bozana** [comment]
Here just the minimal changes (fix). There are other things that could be improved in this plugin, s. https://github.com/pkp/pkp-lib/issues/8478.

**Comment by bozana** [comment]
@ajnyga, for some reason I was not even able to add those metadata, s. https://github.com/pkp/pkp-lib/issues/8479.
Which OMP version exactly do you use?

**Comment by ajnyga** [comment]
yes I have that same change in our own 3.3.0 test site and it solved the problem

**Comment by asmecher** [comment]
^ That's great -- if it's been successful in deployment, that's good enough for me. Please go ahead, @bozana!

**Comment by ajnyga** [comment]
It is still a upgrade test site though
