### ISSUE TITLE
Improve the content of REVIEW_COMPLETE and REVIEW_EDITED templates 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8474]
Both templates were added as a part of email refactoring to substitute the generic NOTIFICATION template.

REVIEW_COMPLETE is sent to the assigned editors when the reviewer completes the review and should include reviewer's recommendation:

> {$senderName} completed their review of {$submissionTitle} (#{$submissionId}). Their recommendation was: Accept Submission.

> See all reviews for this submission.

as well as reviewer comments and attached uploaded files. Original discussion: https://github.com/pkp/pkp-lib/pull/8452/files#r1037208057

REVIEW_EDITED is sent to the reviewer when the details of their review assignment have been changed. It should include the new review due dates along with a link to the review assignment that the reviewer follows to complete the assignment. `$submissionUrl` will probably be an editorial URL that the reviewer can't access.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/8646
https://github.com/pkp/ojs/pull/3773
https://github.com/pkp/omp/pull/1343

**Comment by NateWr** [comment]
All merged to `main`.
