### ISSUE TITLE
AuthorDashboard does not show reviewRoundInfo

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#8475]
**Describe the bug**
When an author looks at the review stage, they can only see the discussions panel.

The round status, editorial decision emails, revisions file upload panel etc. are missing.

Related error:
`PHP Fatal error:  Uncaught Error: Class "PKP\controllers\tab\authorDashboard\AuthorDashboardHandler" not found in /lib/pkp/controllers/tab/authorDashboard/AuthorDashboardReviewRoundTabHandler.php:33`

**To Reproduce**
1. Send a new submission to the review stage
2. Record a new Request Revisions decision on the review stage
3. Log in as the author and go to the submission and the review stage
4. Only the Discussions panel is visible

**What application are you using?**
OJS main branch, probably affecting also OMP. PHP 8.1

**Comment by ajnyga** [comment]
pkp-lib: https://github.com/pkp/pkp-lib/pull/8476

**Comment by ajnyga** [comment]
Ok, added the data. Basically it is any decision done in the review stage. Because of the error the whole reviewRoundInfo.tpl contents are not loaded. Also note that this is with PHP 8.1, not sure if that affects things.

**Comment by NateWr** [comment]
Thanks @ajnyga! I cherry-picked in your commit rather than rebase.
