### ISSUE TITLE
Fatal error when cancelling review round

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8477]
**Describe the bug**
When an editorial decision to cancel a review round is taken, a fatal error is thrown and a popup appears saying there was an unexpected error.

**To Reproduce**
1. Find a submission in the Submission stage and send it to the Review stage.
2. Before adding any reviewers, click the Cancel Review Round button.
3. Complete the steps to cancel the review round.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
This occurs because the database table `edit_decisions.review_round_id` has a foreign key set up to delete on cascade. When the `ReviewRound` is deleted, this decision is deleted too. So between adding the decision and getting it in the handler, it has disappeared. The second line of code below (from `PKPSubmissionHandler`) returns `null`:

```php
$decisionId = Repo::decision()->add($decision);
$decision = Repo::decision()->get($decisionId);
```

@asmecher do you have any opinions on this? My first reaction was that editorial decisions shouldn't be deleted, even if the relevant review round is deleted, so that the editorial history is preserved. However, there is an entry in the activity log which (I think) will remain. That gives us the history. But removing editorial decisions might complicate efforts to get, for example, reliable statistics about editorial decisions. 

I could go either way, here. But it seems to me like setting `edit_decisions.review_round_id` to `null` when a review round is deleted might give us the benefits of preserving editorial decisions. Is it possible to do something like "null on cascade" with a foreign key?

The error message:

```
[08-Dec-2022 12:27:58 UTC] Slim Application Error:
Type: TypeError
Message: PKP\decision\maps\Schema::map(): Argument #1 ($item) must be of type APP\decision\Decision, null given, called in lib/pkp/api/v1/submissions/PKPSubmissionHandler.php on line 1558
File: lib/pkp/classes/decision/maps/Schema.php
Line: 32
Trace: #0 lib/pkp/api/v1/submissions/PKPSubmissionHandler.php(1558): PKP\decision\maps\Schema->map(NULL)
#1 [internal function]: PKP\API\v1\submissions\PKPSubmissionHandler->addDecision(Object(Slim\Http\Request), Object(PKP\core\APIResponse), Array)
```

**Comment by NateWr** [comment]
@asmecher looking for input from you on this one. In particular this question:

> it seems to me like setting edit_decisions.review_round_id to null when a review round is deleted might give us the benefits of preserving editorial decisions. Is it possible to do something like "null on cascade" with a foreign key?

**Comment by asmecher** [comment]
@NateWr Sorry, this slipped off my desk.

To answer your specific question, yes, it's possible to have foreign key columns get updated to `null` when the entity they refer to is deleted. See e.g.:

https://github.com/pkp/pkp-lib/blob/0a7644c9803733bd3957a9c1bb125c4110e798b1/classes/migration/upgrade/v3_4_0/I6093_AddForeignKeys.php#L50

I'd like to be cautious about relaxing data integrity requirements in the data model; it invites bugs when developers forget to consider the `null` in cases where data rarely looks that way. I think we decided that the review round can only be deleted before any real activity takes place, right (the [point of no return discussion](https://github.com/pkp/pkp-lib/issues/2890#issuecomment-1141282791)? The "I accidentally started a new round" use case that gets repeated over and over in https://github.com/pkp/pkp-lib/issues/2890 and https://github.com/pkp/pkp-lib/issues/3585. Once reviewer activity has started, even on a potentially accidentally created round, I say it's part of the scholarly record.

If we're only concerned about the case where we're reverting an accidental decision, why not just delete the whole enchilada including "send to review" decision and let the log tell the tale?

**Comment by NateWr** [comment]
Thanks @asmecher, makes sense.

PR:
- https://github.com/pkp/pkp-lib/pull/8558

Tests only:
- https://github.com/pkp/ojs/pull/3718

**Comment by NateWr** [comment]
Merged to `main`.
