### ISSUE TITLE
ReportPlugin::report() parameter $request is missing in UsageStatsReportPlugin::report()

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#848]
Followup to: https://github.com/pkp/pkp-lib/issues/253 and http://forum.pkp.sfu.ca/t/apache-error-log-ojs-usage-statistics-report/4883

https://github.com/pkp/ojs/blob/f4cf6ed7bb782c0c0a9f0afaa4e6fc1ecfccdd77/pages/manager/StatisticsHandler.inc.php#L160
and
https://github.com/pkp/ojs/blob/0fe3c1996662ef00d03939ea9b2a41a3d6a95471/plugins/reports/timedView/TimedViewReportPlugin.inc.php#L89
Set the precedent for:
https://github.com/pkp/ojs/blob/0fe3c1996662ef00d03939ea9b2a41a3d6a95471/classes/plugins/ReportPlugin.inc.php#L200

So now, UsageStatsReportPlugin::report() is "missing" the $request parameter.
https://github.com/pkp/ojs/blob/f4cf6ed7bb782c0c0a9f0afaa4e6fc1ecfccdd77/plugins/generic/usageStats/UsageStatsReportPlugin.inc.php#L56

I wonder if my earlier fix shouldn't have removed the pass of $request and reworked `TimeViewReportPlugin::display()` to just call `$request = Application::getRequest();` instead?

**Comment by asmecher** [comment]
@beghelli, could you take a look at this one? Thanks!
