### ISSUE TITLE
The content-type of the Response Headers for the .svg images in lib/pkp/templates/images is wrong (403)

### ISSUE THREAD

**Issue by kosson** [pkp/pkp-lib#8483]
**Describe the bug**
I have installed version 3.3.0.13 as an upgrade from 3.3.0.7 (database upgrade). The problem is that on the front page the svg icons associated with https://www.rrbsi.ro/lib/pkp/templates/images/atom.svg, https://www.rrbsi.ro/lib/pkp/templates/images/rss20_logo.svg, and https://www.rrbsi.ro/lib/pkp/templates/images/rss10_logo.svg issue a 403 on loading due to the fact the headers have and incorrect content-type of text/html.

**To Reproduce**
Open the front page and look at the Current issue section. It would be faster here https://www.rrbsi.ro/index.php/rrbsi

**What application are you using?**
OJS 3.3.0.13

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
![Screenshot from 2022-12-11 08-29-33](https://user-images.githubusercontent.com/3862735/206889769-dc70bddf-ede5-48f8-844a-e8603feb4fba.png)

**Comment by Vitaliy-1** [comment]
Hi @kosson,

403 error code means that access to the resource is forbidden and it doesn't look like OJS issue, likely the problem with permissions. Feel free to use [forum](https://forum.pkp.sfu.ca/latest) for such questions, if it's unclear it's an OJS bug or not. I'll reopen the issue if confirmed.

**Comment by kosson** [comment]
Thank you, I will investigate further. If I put a png image and access it it renders correctly. It must be something related to the mime types.
