### ISSUE TITLE
Fix SQL delete for mariaDB

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8484]
A few SQL DELETE statements that have the same source and target table, introduced with usage stats improvements, are wrong for the mariaDB. S. https://github.com/pkp/pkp-lib/commit/86acb0706615cf3217756418176987e8a599c4ac#r90169797
To be fixed in:
- classes/statistics/PKPTemporaryItemRequestsDAO.php
- classes/statistics/PKPTemporaryTotalsDAO.php
- classes/statistics/PKPTemporaryItemInvestigationsDAO.php

PRs:

- https://github.com/pkp/pkp-lib/pull/8491
- https://github.com/pkp/ojs/pull/3679 (only submodule update)
- https://github.com/pkp/omp/pull/1280
- https://github.com/pkp/omp/pull/1289 (second, only submodule update)
- https://github.com/pkp/ops/pull/424 (only submodule update)

**Comment by bozana** [comment]
@asmecher, may I ask you to take a look at the PRs above?

**Comment by asmecher** [comment]
Thanks, @bozana! Merged the pkp-lib and OMP PRs; I'll take care of the submodule requests separately for OJS and OPS.

**Comment by bozana** [comment]
hmmm... it seems this was not merged :-O
