### ISSUE TITLE
Some strings not translated in DOI Management UI

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8485]
**Describe the bug**
There are a few places where text is hard coded in the new DOI management UI. These include the `displayType` (Issue, Article, Monograph, Preprint), and the button to Edit and Save Changes.

**To Reproduce**
These are easy to see with a language in a different character set, like Arabic. Steps to reproduce the behavior:
1. Install Arabic (Iraqi) from the admin site settings.
2. Enable Arabic in the journal for UI and Form.
3. Enable DOIs and make sure DOIs are enabled for submissions.
4. Click "DOIs" to go to the DOI management screen.
5. See errors

**What application are you using?**
`main` (OJS 3.4 pre-release)

**Additional information**
@ewhanson I'm going to assign this to you because I think you understand best how to pass in locale keys for these UI components. But if you'd like us to assign it to someone else no worries.

**Comment by ewhanson** [comment]
Hey @bozana, I've gone through and added the missing locale keys. Could you have a look? Thanks!

PRs:

- `pkp-lib`: #8532
- `ui-library`: pkp/ui-library#247
- `ojs`: pkp/ojs#3695
- `omp`: pkp/omp#1297
- `ops`: pkp/ops#432

**Comment by bozana** [comment]
Hi @ewhanson, all fine, just two questions (to double check)?
