### ISSUE TITLE
Use more permanent URL in mailing list signup after install

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8503]
**What is the problem?**
The success screen after installation now includes a prompt to sign up to our mailing list for developer updates:

> If you wish to receive news and updates, please register at https://lists.publicknowledgeproject.org/lists/. If you have questions or comments, please visit the support forum.

This is great. However, `https://lists.publicknowledgeproject.org/lists/` will become a broken URL if we ever change our list management software.

**What is the solution you would like?**
Use a URL we can more easily control and redirect, like we do with our roadmap (`https://pkp.sfu.ca/roadmap`). I suggest `https://pkp.sfu.ca/dev-updates-signup`. We can add a 301 redirect to ensure it points to the most relevant page at any time.

**What application are you using?**
`main` branch (3.4 pre-release)

**Comment by asmecher** [comment]
I've requested that Hosting make the alias as proposed above, and gone ahead with the change in the locale files.

**Comment by NateWr** [comment]
I checked the redirect and it was `https://pkp.sfu.ca/developer-newsletter`, so I've updated the URLs. I also took the chance to update the install/upgrade language a little bit. I left language as-is in other locales but marked them `#, fuzzy`.

**Comment by asmecher** [comment]
@NateWr It looks like you missed the URL change in OMP, so I corrected those. Thanks for catching the missing newsletter text in OPS!
