### ISSUE TITLE
Convert current usage stats log file into new format at upgrade

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8508]
Convert the current usage stats log file into the new format at the upgrade, so when the logging for that day continues that the file can be fully processed (all usage considered).

PRs:

- https://github.com/pkp/pkp-lib/pull/8509
- https://github.com/pkp/ojs/pull/3674
- https://github.com/pkp/omp/pull/1300
- https://github.com/pkp/ops/pull/434

**Comment by bozana** [comment]
@asmecher, one more for you to review :-) But, this assumes the code from here: https://github.com/pkp/pkp-lib/issues/6849. Thus, first that other issue, then this one :-)
Thanks a lot!

**Comment by asmecher** [comment]
Thanks, @bozana, and sorry for the wait! Just one comment.
