### ISSUE TITLE
Once added, issue title can't be deleted

### ISSUE THREAD

**Issue by alexdryden** [pkp/pkp-lib#8510]
**Describe the bug**
If editors mistakenly add a title to an issue, it can't be totally removed. When you try to delete the issue title, upon saving a form validation message appears saying "Title is required for the issue"
**To Reproduce**
1. Create an issue and add a title to it 
2. Save the issue
3. Edit the issue and attempt to delete the issue title
4. See error "Title is required for the issue"

**What application are you using?**
 OJS version 3.3.0.13

**Additional information**
<img width="1465" alt="Screenshot 2022-12-16 at 10 18 46 AM" src="https://user-images.githubusercontent.com/47127862/208131084-4ba230b7-9788-4247-b45e-4ba7521c8bc0.png">

**Comment by NateWr** [comment]
This is a really confusing UI. You have to uncheck the Title checkbox, then you will be able to save it without a title. (Basically, those checkboxes set the "required" data.) Yes, it's _really_ confusing.
