### ISSUE TITLE
Controlled vocabularies are being URL decoded at input time

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8511]
**Describe the bug**
When inserting a controlled vocabulary item, the data is being URL decoded, which ends up changing the user input.

**To Reproduce**
1. Access a submission
2. Add a keyword with a text which is sensible for the `urldecode()` function, for example `+test`
3. Check the saved data and see the plus is gone.

**What application are you using?**
*/stable-3_3_0
*/main

**PRs**
`stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8513
- **[TESTS ONLY] https://github.com/pkp/ojs/pull/3678**

`main`
- https://github.com/pkp/pkp-lib/pull/8515
- **[TESTS ONLY] https://github.com/pkp/ojs/pull/3681**

**Comment by jonasraoni** [comment]
@asmecher Just to confirm, the [`urldecode()`](https://github.com/pkp/pkp-lib/pull/8513/files#diff-d8273023a31ab548908248f7e072f5832b858fef2ae3c1bcd12117f5970b98d1R113) is just a fragment from the past, right? Or is there any special reason for it to be here?

**PRs**
`stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8513
- **[TESTS ONLY] https://github.com/pkp/ojs/pull/3678**

`main`
- https://github.com/pkp/pkp-lib/pull/8515
- **[TESTS ONLY] https://github.com/pkp/ojs/pull/3681**

**Comment by asmecher** [comment]
I believe it's due to the old UI tool we used to use for tags double-escaping things. I'm OK to remove it if it tests out to work well.

**Comment by jonasraoni** [comment]
It worked fine on my environment and the tests passed, so I've merged the PRs.
