### ISSUE TITLE
Update npm packages

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8518]
The npm packages in `package.json` and `package-lock.json` should be updated before 3.4 is released. These will need to be updated in `ui-library` and identical changes need to be applied to `ojs`, `omp` and `ops`.

**Comment by NateWr** [comment]
The updates were mostly smooth. When applying these changes, a simple `npm install && npm run build` should get you the new dependencies. If you run into any problems, please delete your `node_modules` and try to install and build again.

The ESLint rules are catching a lot of new things. If you're working on the UI Library and get a linting warning/error, you can try to solve it automatically by running `npm run lint`. You'll need to run this in the repository with the file. So if it's a problem in `lib/ui-library`, you'll need to run `npm run lint` from that directory. If that doesn't work, chuck that error message into Google and you'll find something quick enough.

There are two changes to note:

1. We are no longer using TinyMCE in `inline` mode. We used the `inline` mode as a workaround to a problem in previous versions, which made duplicate requests for stylesheets for every instance of TinyMCE on the page. That no longer seems to be the case, and the `inline` mode was causing new(ish) problems. So I've adapted the `FieldRichTextarea` to load in normal mode. This solves persistent problems we've had with the editor toolbar thinking it had no space to render into. So win-win, hopefully. @touhidurabir I believe you're working on rich text titles right now, so this may effect that.
2. As a result of the ESLint change, there's a lot of "noise" in these PRs. It's mostly just formatting changes. The main changes in this PR are in `package.json`, `package-lock.json` (automatically generated), and `vue.config.js` -- as well as the changes to `FieldRichTextarea` described above.

@asmecher do you want to take a look at this or happy for me to merge once the tests pass?

PRs:
https://github.com/pkp/ui-library/pull/245
https://github.com/pkp/pkp-lib/pull/8519
https://github.com/pkp/ojs/pull/3688
https://github.com/pkp/omp/pull/1293
https://github.com/pkp/ops/pull/427

**Comment by asmecher** [comment]
@NateWr, thanks, it's a relief to be a little closer to up-to-date. I'm content for you to merge once tests are passing.

**Comment by NateWr** [comment]
@asmecher I'm going to have to admit defeat for now. I keep running into odd problems with the tests.

The main one was with TinyMCE. The `editor.setContent()` isn't causing some event to fire, so it wouldn't trigger the autosave in the submission wizard. I worked around this by [typing directly into the field](https://github.com/pkp/pkp-lib/pull/8519/files#diff-1b1a73ba561eab6738c8b62510feed5b10edcd25c56626ac79017752b806439d).

That worked, but I keep getting caught on odd things that don't really make sense as things introduced by this PR. The last one was that submitting authors are allowed to edit metadata after submission (their stage assignment allows it). This seems to be a functional change, but I don't understand why.

Anyway, I've rebased and pushed up what I've done. If the tests pass, please merge. If not, feel free to have a go or I'll take a look when I'm back.

**Comment by NateWr** [comment]
All merged to `main`! :tada:
