### ISSUE TITLE
Update cypress to add run all tests feature in the UI testing

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8523]
**Describe the bug**
With the merge of PRs for pkp/pkp-lib#8239, the cypress version updated to `10.11.0` in which the option `Run All` in the cypress UI has been removed. Tests are running properly in the CLI mode. However it can be useful for devs to see each tests executed in the UI to debug which has become painful as there is no option to run all tests, only way to run each tests one by one by clicking on those . By upgrading cypress to `11.2.0` or higher, the `Run All` option will become available again . 

**To Reproduce**
1. For any app(`OJS`, `OPS` or `OMP`), open the cypress UI by command such as `node_modules/cypress/bin/cypress open`
2. Select `E2E`, then browser env and start `E2E` tests .
3. This will bring a browser window to list all tests/specs .
4. See there is no option to run all tests . Only way to click each tests one by one to initiate.

**What application are you using?**
 OJS, OMP or OPS version `3.4(pre-release)`

**Proposal for Solution**
There are 2 options to handle it 
1. Create a `AllTestsRun.cy.js` file and import tests in that file in proper sequence. example at https://www.youtube.com/watch?v=3rgTQ4QZ0zc&ab_channel=glebbahmutov . Drawback to this approach is that devs have to maintain the `AllTestsRun.cy.js` and need to update it every time if a new test spec added.
2. Update cypress to `11.2.0` or higher as the option to run all tests has been brought back by cypress team in that version . example at https://www.youtube.com/watch?v=3rgTQ4QZ0zc&ab_channel=glebbahmutov. One drawback it has is that the option `Run All`  only appeared at the folder level and tests are divided into 2 groups, one in each app level at `cypress/tests` and one in `pkp-lib` library at `cypress/tests`. As a result devs still have to run each to those 2 groups individually. 

More details at https://glebbahmutov.com/blog/run-all-specs-cypress-v10 . 

`Solution:2` can be considered as better approach as it will not force devs to maintain a different file where tests needed to list in proper sequence which is described in `Solution:1` considering the drawbacks for each solution . 

#### Apps
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/428
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3708
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1307

#### Plugins
[staticPages](https://github.com/pkp/staticPages) --> https://github.com/pkp/staticPages/pull/70
[quickSubmit](https://github.com/pkp/quickSubmit) --> https://github.com/pkp/quickSubmit/pull/65
[customLocale](https://github.com/pkp/customLocale) --> https://github.com/pkp/customLocale/pull/21
[customHeader](https://github.com/pkp/customHeader) --> https://github.com/pkp/customHeader/pull/26
[orcidProfile](https://github.com/pkp/orcidProfile) --> https://github.com/pkp/orcidProfile/pull/228
[customBlockManager](https://github.com/pkp/customBlockManager) --> https://github.com/pkp/customBlockManager/pull/74
[defaultManuscript](https://github.com/NateWr/defaultManuscript) --> https://github.com/NateWr/defaultManuscript/pull/40

**Comment by asmecher** [comment]
Looks like a good solution, @touhidurabir, but is it necessary to rename the test specs?

**Comment by touhidurabir** [comment]
> is it necessary to rename the test specs

@asmecher it's more like rearranging those files in a folder . It's necessary because cypress UI is not respecting the file naming sequence and putting folders at top . As a result then clicking on `Run all Specs/Tests` , it's first starting to run the specs in `60-content` first but, basically the following become test order (`OPS` as the example)
```
60-content
10-Installation.cy.js
20-CreateContext.cy.js
40-CreateUsers.cy.js
50-SubmissionGroups.cy.js
```
but we need it in the following order
```
10-Installation.cy.js
20-CreateContext.cy.js
40-CreateUsers.cy.js
50-SubmissionGroups.cy.js
60-content
```

So putting the following file 
```
10-Installation.cy.js
20-CreateContext.cy.js
40-CreateUsers.cy.js
50-SubmissionGroups.cy.js
```
folder in a `10-ApplicationSetup`, it become 
```
10-ApplicationSetup
60-content
```
and continue to run in proper order.

**Comment by touhidurabir** [comment]
@asmecher rebased and all tests have passed for all 3 apps .

**Comment by touhidurabir** [comment]
@asmecher plugin builds are failing for following plugins 

[staticPages](https://github.com/pkp/staticPages) --> https://github.com/pkp/staticPages/pull/70
[customHeader](https://github.com/pkp/customHeader) --> https://github.com/pkp/customHeader/pull/26
[customBlockManager](https://github.com/pkp/customBlockManager) --> https://github.com/pkp/customBlockManager/pull/74

But the test failure reason caused by actual test spec and mostly because of following error 
```
CypressError: Timed out retrying after 10050ms: `cy.click()` failed because this element:
`<button class="pkp_button  submitFormButton" type="submit" name="submitFormButton" id="submitFormButton-63d0ef1dbc044">Save</button>`
is being covered by another element:
`<iframe id="blockContent-fr_CA-63d0ef1db22d1_ifr" frameborder="0" allowtransparency="true" title="Rich Text Area" class="tox-edit-area__iframe"></iframe>`
```

I can restart those build as `Restart Job` option not available in travis build page . Any suggestion to restart those build again ?

**Comment by asmecher** [comment]
@touhidurabir, I've restarted the tests and checked your status -- you should have restart capabilities yourself now too.

**Comment by asmecher** [comment]
All merged -- thanks!
