### ISSUE TITLE
Cypress tests login failing for Nginx or PHP built in web server

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8524]
**Describe the bug**
With the merge of PRs for https://github.com/pkp/pkp-lib/issues/8239, the cypress version updated to `10.11.0`, user login is failing at tests run time when app is running via Nginx or PHP built in web server. 

**To Reproduce**
1. Make sure any app (`OJS`, `OPS` or `OMP`) running through Nginx or PHP built in web server(`php -S`). 
2. Set the proper env and clean the DB. 
3. Start tests from CLI or UI . 
4. See that after the first test(`10-Installation.cy.js `) complete, it halted at `20-CreateContext.cy.js`. 

![Data suite tests -- Creates a context (failed)](https://user-images.githubusercontent.com/2587979/209653500-b4fb75f4-63df-44d1-9246-dc5f71a10968.png)

Above screenshot points that a login attempt initiated and completed but then it was not redirected to intended url as cypress internal cookie issue . Further investigation points that a successful login is happening at https://github.com/touhidurabir/pkp-lib/blob/main/cypress/support/commands.js#L106-L113 but then cypress is setting a new cookie with different session id for which no `user_id` is associated with in `users` table in DB. As s result, it's failed to redirect to or so it seems. 

**What application are you using?**
 OJS, OMP or OPS version `3.4(pre-release)`

**Additional information**
@jonasraoni has confirmed this behaviour when running apps via PHP built in serve(`php -S`) and confirmed that using `Apache` it's ok . . @touhidurabir confirming this same behaviour running apps via `Nginx` . 

**Proposed Solution/Workaround**
it is tested that login via `login form` rather than `AJAX POST` request does not reset the generated cookie after a successful login . So having a `loginViaForm` command with the following implementation 
```JS
Cypress.Commands.add('loginViaForm', (username, password, context) => {
	context = context || 'index';
	password = password || (username + username);
	
	cy.visit('index.php/' + context + '/login');

	cy.get('input[name=username]').clear().type(username);
	cy.get('input[name=password]').clear().type(password);

	cy.get('button').contains('Login').click();
});
```
and controlling by a `env` variable named `loginViaForm` which will be set to `false` by default in the `cypress.config.js`. Then setting it `true` by command `export CYPRESS_loginViaForm=true` from terminal before running tests and having modified `cy.login()` as such 
```JS
Cypress.Commands.add('login', (username, password, context) => {
	if (Cypress.env('loginViaForm')) {
		cy.loginViaForm(username, password, context);
		return;
	}
	
	context = context || 'index';
	password = password || (username + username);
	cy.visit('index.php/' + context + '/login/signIn', {
		method: 'POST',
		body: {username: username, password: password}
	});
});
```
will allow tests to run properly both form CLI and UI . The above change does not break travis test also . 

**Who will be benefited by above changes**
Devs who are using `Nginx` or `PHP built in web server(php -S)` for their local testing . 

### PRs
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8525
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/429

**Comment by asmecher** [comment]
@jonasraoni and @touhidurabir, I've tried running the tests with the PHP builtin server and couldn't get this behaviour to replicate... I don't think it's as simple as an Apache vs. others issue.

**Comment by jonasraoni** [comment]
Yep, there's something strange going on, otherwise the tests would probably fail on Travis as well.
I think I'll try to debug it tomorrow, at least to ensure it's an issue involving only Cypress + local setup 😂

**Comment by jonasraoni** [comment]
This is the minimal reproduction case:

`a.php`
```php
session_start();
$_SESSION['ID'] = session_id();

setcookie(session_name()); // Removes the cookie
setcookie(session_name(), session_id()); // Recreates the cookie
header('location: b.php');
```

`b.php`
```php
session_start();
print_r($_SESSION); // Should be empty
```

I left a note for Cypress here: https://github.com/cypress-io/cypress/issues/19800#issuecomment-1374876892

I'll check our code base, and perhaps come up with an alternative fix.

**Comment by jonasraoni** [comment]
I've just created a PR for the https://github.com/pkp/pkp-lib/issues/6340, which also addressed this one.

**Comment by jonasraoni** [comment]
@touhidurabir, I've merged the #8544, you may check if it's enough to solve your issue with Cypress at `main`.

I think we're not going to backport it to `stable-3_3_0`, so it's needed to discuss with @asmecher if we're going to adopt the `loginViaForm` or wait Cypress to check the issue (I think my comment there will probably be ignored, so I just created a new issue https://github.com/cypress-io/cypress/issues/25495).

**Comment by touhidurabir** [comment]
@jonasraoni thanks a lot . I will check and confirm it .

**Comment by asmecher** [comment]
This interaction with Cypress only appears since the upgrade to the new version, right? I don't anticipate back-porting that to `stable-3_3_0`.

**Comment by touhidurabir** [comment]
> This interaction with Cypress only appears since the upgrade to the new version, right?

I haven't faced this issue with stable yet so I guess it's only a main branch related issue after the upgrade of cypress .

**Comment by touhidurabir** [comment]
@jonasraoni it's resolved. Big thanks for fixing it .

**Comment by touhidurabir** [comment]
Fixed by https://github.com/pkp/pkp-lib/issues/8544
