### ISSUE TITLE
Malware injected through file submission form

### ISSUE THREAD

**Issue by ekristino** [pkp/pkp-lib#8528]
Attackers can inject malware (.phtml, .php, s.html, etc) through user using "creepy" email address. They submit non-.docx files through files submission.

**Comment by jonasraoni** [comment]
Hi @ekristino,

This is something that varies from server to server (your server might be configured to process `.xyz` extension as a `.php` file or `.aspx` as `C#` code, etc.), so the recommended approach is to shield the user uploads, see more information here: https://docs.pkp.sfu.ca/admin-guide/en/securing-your-system

Also, there's a small protection here:
https://github.com/pkp/pkp-lib/blob/8733e5aad94aa9cca1d76a105b0b8df7546c005a/classes/file/FileManager.php#L701-L704

Which will cover some extensions (`.php`, `.htaccess`, ...), such files will end up being saved in the disk with the suffix `.txt`.
