### ISSUE TITLE
Several mailable and templates are missing from the registry

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8529]
**Describe the bug**
As part of the work on the [new submission wizard](https://github.com/pkp/pkp-lib/issues/7191) several new mailables were introduced but they are missing from the registry in mailable Repo, and correspondent templates - from `emailTempate.xml`

in OPS, it's `SubmissionAcknowledgementCanPost` and `PostedNewVersionAcknowledgement` (and default templates)

**To Reproduce**
It breaks OPS tests

**What application are you using?**
OPS main branch

**Comment by NateWr** [comment]
Added templates for those two mailables, fixed a couple names/descriptions, and removed the `EditorialReminder` mailable from OPS.

PR:
https://github.com/pkp/ops/pull/442

**Comment by NateWr** [comment]
Merged to `main`.
