### ISSUE TITLE
Configuring an Alternate Header is insane.

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#853]
In OJS Journal Setup 5.3, the instructions for the Alternate Header state, "Alternately, instead of title and logo, an HTML version of the header can be inserted into the text box below. Leave textbox blank if not required."
https://github.com/pkp/ojs/blob/ojs-stable-2_4_7/locale/en_US/manager.xml#L205
This strongly suggests to me that I could override the title and logo options with arbitrary HTML for the header.  That is useful, and pretty standard in other hosted platforms.

Really, what happens is:
- Wrap everything in an H1
- Display the Logo if present
- If there isn't a Title, display the Alternate Header

https://github.com/pkp/pkp-lib/blob/724f1a8593c405f5f4ef22a6854d4cba27a79c32/templates/common/header.tpl#L128-L143

Eh?!??!

Option 1:
Realign the Alternate Header to function sanely.  This will probably break a bunch of existing installs.
Option 2:
Edit the instructions so the user can understand the implications of the interaction of these settings.

**Comment by asmecher** [comment]
@ctgraham, I agree that the current implementation is at least a little rickety. However, I'm hesitant to change it for existing users, since it's been that way for a long time. We're overhauling this substantially for OJS 3.0.

**Comment by ctgraham** [comment]
For 2.x, to make the UI match the existing function, we could move the text box up to the "5.3 -> Journal title" section, and change the instruction to something like, "If you want to use arbitrary HTML inside the Journal Title, the content of the H1 can be inserted into the text box below".

Of course, that presumes that the existing "5.3 -> Journal title -> Title text" option doesn't accept HTML.  Actually it does.

**Comment by asmecher** [comment]
On second thought, and looking at the template -- yep, you're absolutely right, dropping this into the `<h1>` is insane. Let's make it less insane.
