### ISSUE TITLE
References are not saved correctly

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8530]
**Describe the bug**
When the references are added/edited for a publication they are only saved in publication_settings and not in the citations DB table.

PRs
- https://github.com/pkp/pkp-lib/pull/8531
- https://github.com/pkp/ojs/pull/3693 (only submodule update)
- https://github.com/pkp/omp/pull/1299 (only submodule update)
- https://github.com/pkp/ops/pull/433 (only submodule update)

**Comment by bozana** [comment]
Hi @asmecher, could you take a look at this one too?

**Comment by asmecher** [comment]
Please go ahead, @bozana; that looks fine.
