### ISSUE TITLE
Filter by series in OMP statistics does not display correct statistics

### ISSUE THREAD

**Issue by rcgillis** [pkp/pkp-lib#8536]
**Describe the bug**
When attempting to use a filter by series in the OMP statistics, applying a filter does not correctly display the statistics (e.g. they don't change at all)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Statistics'
2. Click on 'Monographs'
3. Select a series from 'Filters'
4. Note how the statistics do not change based on the filter for a given series being selected 

**What application are you using?**
User reported in OMP 3.3.0-8 but tested on test drive instance (OMP 3.3.0=13)

**Additional information**
Please see:  https://forum.pkp.sfu.ca/t/filter-in-omp-statistics-monograph-does-not-work-properly/76138

**Comment by bozana** [comment]
PR:
https://github.com/pkp/omp/pull/1305
