### ISSUE TITLE
OJS 3.3 Native Import for articles not working

### ISSUE THREAD

**Issue by drycko** [pkp/pkp-lib#8539]
**Describe the bug**
I am trying to do a Native Import of articles from OJS 3.2.1.1 to 3.3.0-13 but is giving me an error even if I it is a single submission.
Since github will not allow me to attach the XML file I will share the XML import file as a word docx below;

**To Reproduce**
1. Go to Tools > Native XML Plugin > Import (tab)'
2. Click on 'Upload a file' or drag and drop a submission XML format file
3. Click 'Import' button
![image](https://user-images.githubusercontent.com/59409711/212111514-831ebd92-52b2-4e47-810b-647144225874.png)

**What application are you using?**
 OJS version 3.3.0-13

**Additional information**
Since github will not allow me to attach the XML file I will share the XML import file as a word docx below
[xml submission.docx](https://github.com/pkp/pkp-lib/files/10403189/xml.submission.docx)

**Comment by jonasraoni** [comment]
Hi @drycko!

Please look for support/answers in the forum (https://forum.pkp.sfu.ca/), we're just accepting triaged issues in GitHub, so I'll close this one.

FYI the first issue in this post has the answer for your problem: https://forum.pkp.sfu.ca/t/request-for-comments-deprecate-the-native-import-export-plugin/73329

Best,
Jonas
