### ISSUE TITLE
Bug in UPLOAD_MAX_FILESIZE calculation in stable-3_3_0

### ISSUE THREAD

**Issue by dersmon** [pkp/pkp-lib#8541]
The calculation here is the wrong way around: https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/core/PKPApplication.inc.php#L861:L870

This will cause a fallback to 2mb if you set your php.ini value to a (realistic) GB value.

**Comment by jonasraoni** [comment]
Yeah, looks like the handling for 'K' and 'G' should be inversed.
Also, perhaps it makes sense to replace the `floor()` by `ceil()`, but I'd have to check how this function is being used to be sure :)

**Comment by asmecher** [comment]
I think this was incorrectly adapted from https://www.php.net/manual/en/function.ini-get.php#example-576. I don't think just swapping `K` and `G` handling will fix it -- note the lack of `break` in the `case` statement.

**Comment by jonasraoni** [comment]
PRs

**`stable-3_3_0`**
- https://github.com/pkp/pkp-lib/pull/8547
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3706

**`main`**
- https://github.com/pkp/pkp-lib/pull/8548
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3707

**Comment by asmecher** [comment]
All merged -- thanks, @jonasraoni!
