### ISSUE TITLE
Review the configuration template file 

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8543]
**Describe the bug**
The configuration across the applications shares most of the settings, but some of them seems to be missing a synchronization, e.g.:

The config of OMP has:
`scheduled_tasks_report_error_only = On`

The config of OJS has:
`show_upgrade_warning = On`
`citation_checking_max_processes = 3`
`sitewide_privacy_statement = Off`
:

It's needed to compare the settings across OJS/OMP/OPS for `main` and `stable-3_3_0`, and ensure the differences make sense.

Some settings seems to be not used:
`[general].citation_checking_max_processes`
`[files].filename_revision_match`
`[curl].cainfo`

**What application are you using?**
*/main
*/stable-3_3_0

**Comment by kaitlinnewson** [comment]
PRs ready for review for the 3.3 branches @asmecher:

- OJS: https://github.com/pkp/ojs/pull/4418
- OMP: https://github.com/pkp/omp/pull/1687
- OPS: https://github.com/pkp/ops/pull/760

Will work on PRs to 3.4/main when approved.

**Comment by kaitlinnewson** [comment]
PRs for 3.3 branches ready for review @asmecher:

- OJS: https://github.com/pkp/ojs/pull/4418
- OMP: https://github.com/pkp/omp/pull/1687
- OPS: https://github.com/pkp/ops/pull/760

Will work on forward-porting to 3.4/main once approved.

**Comment by touhidurabir** [comment]
Hi @kaitlinnewson as you are working on this issue , please consider updating the description of `validation_timeout` under `email` section . Basically `validation_timeout` description set as `Maximum number of days before an unvalidated account expires and is deleted` but in real , it just define time in number of days the validity of validation link in email . The current description of `email --> validation_timeout` is conflicting and confused with `general --> user_validation_period` . More details at https://github.com/pkp/pkp-lib/issues/10351 .

**Comment by kaitlinnewson** [comment]
@asmecher the PRs above have been updated and are ready for review.

**Comment by kaitlinnewson** [comment]
Hi @asmecher, would you have time to give this a look? I'd like to work on this for 3.4/main as well if everything looks good here.

**Comment by asmecher** [comment]
All 3 `stable-3_3_0` PRs merged, thanks! Please go ahead with the other branches.

**Comment by kaitlinnewson** [comment]
@asmecher other branch PRs are now done (listed above) and ready for review.
