### ISSUE TITLE
Unable to login when there's many session cookies

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8544]
**Describe the bug**
Given that N+1 cookies with the same name, but different domain/path might co-exist, the application might end up getting fixed to an invalid cookie, and then block the user from logging into the application (if the session gets fixed to the cookie which isn't logged), until the user clears the cookies manually or the bad cookie gets expired.

There's also a kind of "session fixation":
If the given session ID refers to an existing session, but from another user, the session will then be deleted from the database (invalidating the other user's session) and recreated with the same ID. This way, once the original owner refreshes his interface, he will steal the session back and vice-versa.

Notes:
- The code below only drops domainless cookies
https://github.com/pkp/pkp-lib/blob/ef79d952408a9c91fa0b38cfbdb407df69429704/classes/session/SessionManager.php#L247

- The parent domain cookie (see reproduction case below) could be re-used, but the following line doesn't work (it's not possible to set session constants when a session is active):
https://github.com/pkp/pkp-lib/blob/ef79d952408a9c91fa0b38cfbdb407df69429704/classes/session/SessionManager.php#L78

- Other session cookies, which don't fit the rules above, could be present and also break expectations.

- Laravel has session capabilities, but it probably won't handle such exceptions (after skimming the documentation, it looks like a facade/decorator around the session stuff). Anyway, it will probably work out of the box with the `SessionManager`, it supports drivers extending the `SessionHandlerInterface` (this PR fulfills this requirement).

**To Reproduce**
1. Accessed `journal.xyz`
   > Got a cookie with the domain `.journal.xyz`.
2. Accessed `www.journal.xyz`
   > The previous cookie is visible at the subdomain, and no extra cookie was created.
3. Tried to login and got redirected back to the login form
   > A new cookie with the domain `.www.journal.xyz` was created, the previous cookie wasn't removed nor reused.

**What application are you using?**
*/main
*/stable-3_3_0

**PRs**
- https://github.com/pkp/pkp-lib/pull/8545
- https://github.com/pkp/ojs/pull/3701
- https://github.com/pkp/ops/pull/441
- https://github.com/pkp/omp/pull/1306

**Comment by jonasraoni** [comment]
@asmecher These PRs were built over the ones I created for https://github.com/pkp/pkp-lib/issues/6340, if those are ok, feel free to review them:
- https://github.com/pkp/pkp-lib/pull/8545
- https://github.com/pkp/ojs/pull/3701

**Comment by asmecher** [comment]
Looks good, @jonasraoni -- and thanks for keeping the commit history so clean, it made reviewing a lot easier! Just one comment on the OJS repo (https://github.com/pkp/ojs/pull/3701/files#r1071594209); then can you port this to OMP and OPS `main` for release in 3.4.0?

**Comment by jonasraoni** [comment]
Merged PRs at the issue description to `main`.

**Comment by asmecher** [comment]
@jonasraoni, after this is merged I get:
```
[23-Jan-2023 21:36:08 UTC] PHP Fatal error:  Uncaught TypeError: ini_set(): Argument #2 ($value) must be of type string|int|float|bool|null in .../lib/pkp/classes/session/SessionManager.php:295
Stack trace:
#0 .../lib/pkp/classes/session/SessionManager.php(295): ini_set()
#1 .../lib/pkp/classes/session/SessionManager.php(49): PKP\session\SessionManager->start()
#2 .../lib/pkp/classes/session/SessionManager.php(73): PKP\session\SessionManager->__construct()
#3 .../lib/pkp/classes/security/Validation.php(400): PKP\session\SessionManager::getManager()
#4 .../lib/pkp/classes/core/PKPPageRouter.php(88): PKP\security\Validation::isLoggedIn()
#5 .../lib/pkp/classes/core/Dispatcher.php(137): PKP\core\PKPPageRouter->isCacheable()
#6 .../lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch()
#7 .../index.php(21): PKP\core\PKPApplication->execute()
#8 {main}
  thrown in .../lib/pkp/classes/session/SessionManager.php on line 295
```
The issue is that `$requestDomain` is a `Stringy` object, so it needs e.g. an explicit string cast before it can be passed into `ini_set`.

**Comment by jonasraoni** [comment]
I thought we were going to update `stable-3_3_0`, then I replaced the `str_ends_with` and created this issue 🎉

If you think it's worth, I can create another issue to add some tests to the session or cover at the PR below.

- https://github.com/pkp/pkp-lib/pull/8561
- https://github.com/pkp/ojs/pull/3720

**Comment by asmecher** [comment]
Merged, thanks. This is a common enough case that I don't think a specific test is necessary; the team will catch it.

**Comment by asmecher** [comment]
@jonasraoni, I ran into another error...
```
PHP Fatal error:  Uncaught TypeError: PKP\session\SessionManager::PKP\session\{closure}(): Return value must be of type PKP\session\Session, null returned in .../lib/pkp/classes/session/SessionManager.php:277
```
I suppose the first-checked session wasn't valid.

I committed https://github.com/pkp/pkp-lib/commit/b5b763b1289c3eeb14525894fce91efcaa43f527 to fix it.

**Comment by jonasraoni** [comment]
Yep, that's why I left a `@var ?Session` here: https://github.com/pkp/pkp-lib/commit/b5b763b1289c3eeb14525894fce91efcaa43f527#diff-0ebb932271ea926588ac1e61c2d18d7920922cd3baf8d83c9345132472d8a78cR274, but I forgot to update the function return :)

**Comment by asmecher** [comment]
@jonasraoni, also a warning cropping up when the sessions are garbage-collected:
```
PHP Deprecated:  Return type of PKP\session\SessionManager::gc(int $lifetime): bool should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../lib/pkp/classes/session/SessionManager.php on line 160
```

**Comment by jonasraoni** [comment]
Thanks, this one didn't show up on my PHP 8.0 😁

**Comment by jonasraoni** [comment]
I've merged the PR to address the deprecated warning:
- https://github.com/pkp/pkp-lib/pull/8595
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3737
