### ISSUE TITLE
OPS 3.3.0: Crossref Deposit plugin interrupting the Publication::publish hook flow

### ISSUE THREAD

**Issue by thiagolepidus** [pkp/pkp-lib#8559]
**Describe the problem**
The method of Crossref Deposit plugin that uses the Publication::publish hook is [returning true](https://github.com/pkp/ops/blob/stable-3_3_0/plugins/generic/crossrefDeposit/CrossrefDepositPlugin.inc.php#L83), preventing others plugins to be called.
We had an issue with the [Dataverse plugin](https://github.com/lepidus/dataversePlugin), which also listened for the Publication::publish hook. We solved by changing [the hook priority order](https://github.com/lepidus/dataversePlugin/commit/b6e321828b1dfaaa4b36e739db5e3807eeeb2a66), but other plugins might be affected by the current behaviour of Crossref Deposit plugin.

**Describe the solution you would like**
Crossref Deposit plugin should not interrupt other plugins from being called.

**What application are you using?**
OPS stable-3_3_0

**Comment by bozana** [comment]
PR:
https://github.com/pkp/ops/pull/444
