### ISSUE TITLE
Can't Display and Downloaded as Blank PDF File

### ISSUE THREAD

**Issue by alwathan** [pkp/pkp-lib#8560]
**Can't Display and Downloaded as Blank PDF File**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

Pdf Viewer not display pdf file, and blank if i downloaded the file.

PDF.js v2.6.347 (build: 3be9c65f)
Messege: Invalid PDF structure.

![View of PEMIKIRAN MODERNIS MUHAMMAD IQBAL DAN FAZLUR RAHMAN DALAM PENDIDIKAN ISLAM](https://user-images.githubusercontent.com/16916624/214253951-94fa7324-54f8-4eef-9479-261c7a9fa42b.png)

But if deprecation_warnings is set to ON pdf viewer displayed correctly

![View of PEMIKIRAN MODERNIS MUHAMMAD IQBAL DAN FAZLUR RAHMAN DALAM PENDIDIKAN ISLAM (2)](https://user-images.githubusercontent.com/16916624/214257440-eed56af8-a1cd-4da6-a1dc-12dab71a8cd2.png)

link - [https://jurnal.inkadha.ac.id/index.php/kariman/article/view/240/172](url)

please anybody can help?

**What application are you using?**
 OJS version 3.3.0.10

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by jonasraoni** [comment]
Hi @alwathan!

Please use the forum (https://forum.pkp.sfu.ca/) before posting questions here, we're just handling triaged questions.

Anyway, I advise you to disable the `deprecation_warnings` and take a look at the output of your page (you'll see a bunch of hidden links in the top which breaks everything).
