### ISSUE TITLE
Improve submission wizard after usability tests

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8562]
**Describe the problem you would like to solve**
@Devika008 ran usability testing sessions on the new submission wizard (#7191) with editors and authors. The following feedback had broad consensus:

- Change the order of the steps in the wizard so that submission details are first. The preferred order is: 1) Details, 2) Upload Files, 3) Contributors, 4) For the Editors.
- Move the keywords field into the Details step, because it is a fundamental part of the submission itself.
- In the screen to start a new submission, move Language above Title, so that authors feel they are entering the title in the language they selected.
- Clarify the error message when a contributor is missing the given name in a language (see below).

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional Information**
When a contributor is missing the given name in the required language, the message says:

> One or more of the contributors are missing details in {$language}.

This should be updated to say that the given name must be completed in that language for all contributors.

![Screenshot from 2023-01-26 10-55-47](https://user-images.githubusercontent.com/2306629/214819040-f0fc269e-2687-4c9b-900f-deda2b3ca837.png)

**Comment by asmecher** [comment]
We originally moved uploads before metadata (details) in order to prepare for automatic metadata extraction, which would pre-fill those fields with data detected from the upload. That hasn't happened yet, but it might; personally I'd rather we kept the order this way rather than flip-flopping. Thoughts?

**Comment by NateWr** [comment]
@Devika008 and I discussed this, but 8/8 participants wanted the order changed. I think that if/when we do automatic metadata extraction, we can reorder the submission wizard. With the new structure, it'd be easy for a plugin to swap the order of steps or even to change the order depending on whether metadata extraction is enabled.

**Comment by asmecher** [comment]
If a plugin can easily reorder the steps, I'm on board!

**Comment by NateWr** [comment]
The following PRs implement the changes described above. @Devika008 here's a short video showing the changes.

[submission-wizard.webm](https://user-images.githubusercontent.com/2306629/214880292-4df4a45b-290c-45c8-b773-d08531d578cb.webm)

@jonasraoni do you have time to do a code review? This is mostly just moving things around, but I slightly restructured the `TitleAbstract` form to use a new `Details` form step in the wizard, so that I could keep most of the code in pkp-lib.

PRs:
https://github.com/pkp/ui-library/pull/251
https://github.com/pkp/pkp-lib/pull/8575
https://github.com/pkp/ojs/pull/3729
https://github.com/pkp/ops/pull/449
https://github.com/pkp/omp/pull/1312

**Comment by Devika008** [comment]
> The following PRs implement the changes described above. @Devika008 here's a short video showing the changes.
> 
>  submission-wizard.webm 
> @jonasraoni do you have time to do a code review? This is mostly just moving things around, but I slightly restructured the `TitleAbstract` form to use a new `Details` form step in the wizard, so that I could keep most of the code in pkp-lib.
> 
> PRs: [pkp/ui-library#251](https://github.com/pkp/ui-library/pull/251) #8575 [pkp/ojs#3729](https://github.com/pkp/ojs/pull/3729) [pkp/ops#449](https://github.com/pkp/ops/pull/449) [pkp/omp#1312](https://github.com/pkp/omp/pull/1312)

I would suggest three things over here:

1. In the "for the editors" category, let go the subject field as it feels very similar to the keywords form field and might confuse the users even more
2. In the "for the editors" category, please include more context as to what categories stand for as it was getting really confusing to the users. Maybe the description can be "Select only the categories that are appropriate for your submission. Categories help us differentiate submissions by purpose or type"
3. In the review screen, please let go of form fields in the multilingual space in which information has not been entered. It seemed to confused users. I will work of a design for it and share it with you by Monday 😄

**Comment by jonasraoni** [comment]
@NateWr are you going to update something after @Devika008's comments? If not, then I'll take a look =]

**Comment by NateWr** [comment]
@jonasraoni go ahead with the review, thanks.

@Devika008:

1. The subject field is optional and most journals have it turned off. I just turned it on for testing.
2. Every journal uses categories in a different way so we can't really say what they are for. Most journals don't use them at all, so they won't appear. When they are used, they are probably make more sense to the author, who will be familiar with the names of the categories.
3. Personally, I lean towards showing people that fields were not filled out. This is how things like big online government forms from gov.uk work (eg - tax / visa forms). And I think there's some value in showing people what they _haven't_ completed, otherwise they may not even know those fields were an option. But I'll wait to see your suggestion. :)

**Comment by NateWr** [comment]
All merged to `main`. Thanks for the review @jonasraoni and for the usability tests @Devika008. If you want to propose a change to the review of multilingual fields, we can file that as a separate issue.

**Comment by Devika008** [comment]
> All merged to `main`. Thanks for the review @jonasraoni and for the usability tests @Devika008. If you want to propose a change to the review of multilingual fields, we can file that as a separate issue.

Yes was gonna suggest that only
