### ISSUE TITLE
Pubmed plugin exports articles out of order compared to issue order

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#8564]
**Describe the bug**
The generated XML that the PubMed plugin generates when exporting an issue does not sort the articles according to how they appear in an issue's table of contents.  This used to happen in older versions of OJS but is no longer the case.   This is probably due to the plugin using the submission service's `getMany` method since the old way of doing this with the PublishedArticleDAO is no longer possible.  Restoring the order of content is important to some of our largest medical journal clients.

**To Reproduce**
1. Export an issue using the PubMed plugin
2. Examine the <ArticleTitle> elements and compare them to the issue's table of contents.

**What application are you using?**
OJS 3.3.0.13

**Comment by mgscano** [comment]
Just to add a note here, since I'm the client impacted, also I hope I'm not the only one.
This one's really a painful thing to work around, since when a journal is under periodic publishing it becomes necessary to have PubMed IDs in the correct page order.
Reordering the XML code manually is definitely prone to error, and becomes an unnecessary long task.

**Comment by kaitlinnewson** [comment]
PRs ready for review:

- 3_3_0: https://github.com/pkp/ojs/pull/4388
- 3_4_0: https://github.com/pkp/ojs/pull/4389
- main: https://github.com/pkp/ojs/pull/4390

@bozana could you review these?

**Comment by bozana** [comment]
Hi @kaitlinnewson, the plugin does not consider the section ordering, and the publication sequence is currently only per section. Thus, I think some more work is needed -- similar to how the articles are displayed on the issue TOC page.
Depending on how the issue https://github.com/pkp/pkp-lib/issues/8998 is going to be fixed, this plugin will maybe need to be adapted as well, but lets fix it now as if that other issue would not exists :-)

**Comment by kaitlinnewson** [comment]
Hi @bozana, I've updated the PRs above, can you take another look?

**Comment by bozana** [comment]
Hi @kaitlinnewson, I left a few comments for the PR for the main branch, but they can be applied to other PRs/branches as well. Thanks!

**Comment by kaitlinnewson** [comment]
Hi @bozana, I've updated the PRs above, ready for another check!

**Comment by bozana** [comment]
Hi @kaitlinnewson, one more comment in the PR for stable-3_3_0, but relevant for all :-)
Thanks!

**Comment by kaitlinnewson** [comment]
Hi @bozana, PRs updated and hopefully ready to merge now!

**Comment by bozana** [comment]
All merged, thus closing
