### ISSUE TITLE
Duplicate entry '......' for for key 'sessions_pkey'

### ISSUE THREAD

**Issue by marcoblancas** [pkp/pkp-lib#8576]
**Describe the bug**
3 days ago we upgraded to 3.3.0.13 using the stable-3_3_0 branch 
https://github.com/pkp/ojs/tree/38ac0ef46ed026993aafb2af48a4a320454e1407

and our logs has started to register those errors:
```
Jan 26 02:13:57 patty php: PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'islkj86p2oa520jhf02vjk069m' for key 'sessions_pkey' in /var/web1/ojs33/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
Jan 26 02:13:57 patty php: #0 /var/web1/ojs33/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(119): PDOStatement->execute(NULL)
Jan 26 02:57:31 patty php: PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'mvhegbg2lep5qb4ckil2cvn5a8' for key 'sessions_pkey' in /var/web1/ojs33/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
Jan 26 02:57:31 patty php: #0 /var/web1/ojs33/lib/pkp/lib/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(119): PDOStatement->execute(NULL)
```
Those errors were not present with our previous 3.3.0.10 version. 

**To Reproduce**
I don't know how to reproduce. Everything seems to be working OK and I'm not sure how much FATAL is this error.

**What application are you using?**
 OJS version 3.3.0.13

**Comment by asmecher** [comment]
@marcoblancas, I'd suggest starting by looking through some of the existing forum threads on the subject:

https://forum.pkp.sfu.ca/search?q=Duplicate%20entry%20for%20key%20sessions%20order%3Alatest

If none of those are helpful, post with your details on the support forum. If it can be confirmed as a bug we can reopen this issue.

**Comment by marcoblancas** [comment]
Thank you @asmecher . I have post this https://forum.pkp.sfu.ca/t/duplicate-entry-for-for-key-sessions-pkey-aflter-upgrade-to-3-3-0-13/76553
