### ISSUE TITLE
When a new issue is published, notification emails are sent before the issue is actually public.

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#8583]
**Describe the bug**
When publishing a new issue the notification emails are sent first and then the issue is published, so if the list of users is large the email will arrive first and if a user tries to review the new content they will not see it available.

**To Reproduce**
1. Prepare an issue for publication
2. Be sure to enable the plugin “Email Issue Table of Contents”
3. Publish the number with the "Send notification email to all registered users" option enabled.
4. While the emails are being sent, check the website in another browser, you will see that it is not updated yet.
5. You can also wait until arrive the email notification with the Table of Contents (if you are using the plugin in step 2) and click on an article link, the link will appear broken.

**What application are you using?**
 OJS 3.2.1.4 with the plugin Email Issue Table of Contents v1.0.2.2 

**Additional information**
I check the server when emails are being sent, after 300 emails sent and several minutes, the site content was still not updated. And finally the confirmation window did not close (but that is not a problem).

**Comment by asmecher** [comment]
@carzamora, this is a characteristic of the Email Issue Table of Contents plugin, which isn't written and maintained by PKP; I'd suggest contacting the author of that plugin.
