### ISSUE TITLE
Session confusion in OJS 3 when user with author role accidentally click "Review" button

### ISSUE THREAD

**Issue by febrifahmi** [pkp/pkp-lib#8588]
**Describe the bug**

There is cookie session confusion in OJS 3 when a user with an author role accidentally clicked the review button. Users with a role as an author should not be able to see the review button since he/she doesn't have a reviewer role. After clicking the review button, a user with an author role gets some alerts and seems to lost his/her original role in the cookie context which make it impossible to continue browsing the OJS without deleting cookies and re-login. 

**To Reproduce**
1. Login with an author role
2. Check my submission page
3. Click on review button (besides "View" button)
4. You will get error alert

**What application are you using?**
 OJS version 3

**Comment by asmecher** [comment]
@febrifahmi, could you start by posting this on our support forum at https://forum.pkp.sfu.ca? Please include the exact version of OJS you're using, and a screenshot of the error alert that you see. If it is confirmed there to be a bug, then we can re-open this issue.
