### ISSUE TITLE
Adapt mEDRA plugin for 3.4, migrade mEDRA data

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#8597]
**Describe the bug**
Data from the MEDRA plugin still needs to be migrated from the 3.3 to 3.4 DOI formatting. It will need to follow a similar migration path as the Crossref and Datacite plugins for OJS and the Crossref plugin for OPS.

**Additional information**
see `\APP\migration\upgrade\v3_4_0\I7014_DoiMigration` for implementation details.

<hr>

PR: 
- https://github.com/pkp/medra/pull/16

**Comment by bozana** [comment]
@ewhanson, I will return this issue to 3.4 -- all issues that we would like to address/include till/in 3.4 (and not only RC1) should go there...

**Comment by bozana** [comment]
This will be done withing the plugin migration, so I will rename this issue to consider general update of the medra plugin for 3.4.
