### ISSUE TITLE
Merge locale folders to locale code folders

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8598]
For example there are `es_ES` and `es_MX` folders in the installation. Consider a solution/process that would merge them to an `es` locale code folder. 

Changes need to be made to 
1. the filesystem regarding the translation `.po` files, and their respective folders.
2. the DB, regarding the data that directly correspond and manage the installation's locale
3. the base code, where ever certain affected locales are hard coded 

-----------------------------------
**PRs**

**FOR MERGE**
~~OJS: https://github.com/pkp/ojs/pull/3774 (Alec: Additions made here https://github.com/pkp/ojs/pull/3775)~~
~~OMP: https://github.com/pkp/omp/pull/1344~~
~~OPS: https://github.com/pkp/ops/pull/478~~
~~PKP-LIB: https://github.com/pkp/pkp-lib/pull/8649 (Alec: Additions made here https://github.com/pkp/pkp-lib/pull/8650)~~
~~UI-LIBRARY: https://github.com/pkp/ui-library/pull/261~~
~~staticPages: https://github.com/pkp/staticPages/pull/74~~

**ADDITIONAL PRs**
OJS: https://github.com/pkp/ojs/pull/3779 **TESTS ONLY**
~~pkp-lib: https://github.com/pkp/pkp-lib/pull/8654 (merged)~~
pkp-lib: https://github.com/pkp/pkp-lib/pull/8658

**PLUGINS**
plagiarism :  https://github.com/pkp/plagiarism/pull/41
paperbuzz  :  https://github.com/pkp/paperbuzz/pull/27
pln:  https://github.com/pkp/pln/pull/62
pdfJsViewer:  https://github.com/pkp/pdfJsViewer/pull/65
crossref   :  https://github.com/pkp/crossref-ojs/pull/28
oaijats:  https://github.com/pkp/oaiJats/pull/34
makesubmission :  https://github.com/pkp/makeSubmission/pull/35
medra  :  https://github.com/pkp/medra/pull/8
lensGalley :  https://github.com/asmecher/lensGalley/pull/63
jatsTemplate   :  https://github.com/pkp/jatsTemplate/pull/23
JATSParser :  https://github.com/Vitaliy-1/JATSParserPlugin/pull/82
immersion  :  https://github.com/pkp/immersion/pull/84
hypothesis :  https://github.com/asmecher/hypothesis/pull/21
googleScholar  :  https://github.com/pkp/googleScholar/pull/13
googleAnalytics:  https://github.com/pkp/googleAnalytics/pull/56
defaultTranslation :  https://github.com/pkp/defaultTranslation/pull/12
customLocale   :  https://github.com/pkp/customLocale/pull/22
customHeader   :  https://github.com/pkp/customHeader/pull/27
customBlockManager :  https://github.com/pkp/customBlockManager/pull/75
classic:  https://github.com/pkp/classic/pull/112
citationStyleLanguage  :  https://github.com/pkp/citationStyleLanguage/pull/104
coins  :  https://github.com/pkp/coins/pull/9
browse :  https://github.com/pkp/browse/pull/12
backup :  https://github.com/asmecher/backup/pull/7
browseBySection:  https://github.com/pkp/browseBySection/pull/34
pragma :  https://github.com/pkp/pragma/pull/91
quickSubmit:  https://github.com/pkp/quickSubmit/pull/68
returningAuthorScreening   :  https://github.com/pkp/returningAuthorScreening/pull/2
reviewReport   :  https://github.com/pkp/reviewReport/pull/46
swordServer:  https://github.com/pkp/swordServer/pull/3
subscriptionSSO:  https://github.com/asmecher/subscriptionSSO/pull/12
texture:  https://github.com/pkp/texture/pull/116
tinymce:  https://github.com/pkp/tinymce/pull/88
usageStats :  https://github.com/pkp/usageStats/pull/55
addThis:  https://github.com/pkp/addThis/pull/27
controlPublicFiles :  https://github.com/pkp/controlPublicFiles/pull/9
piwik  :  https://github.com/pkp/piwik/pull/15
textEditorExtras   :  https://github.com/pkp/textEditorExtras/pull/18
sword  :  https://github.com/pkp/sword/pull/33
registrationNotification   :  https://github.com/pkp/registrationNotification/pull/10
orcidProfile   :  https://github.com/pkp/orcidProfile/pull/238
crossref-ops: https://github.com/pkp/crossref-ops/pull/25

Script Actions
[outputProcessOJS.txt](https://github.com/pkp/pkp-lib/files/10741604/outputProcessOJS.txt)
[outputProcessOMPOPS.txt](https://github.com/pkp/pkp-lib/files/10741607/outputProcessOMPOPS.txt)

**Comment by defstat** [comment]
@asmecher here are the draft PRs containing the merged locale files for review

OJS: https://github.com/pkp/ojs/pull/3754
pkp-lib: https://github.com/pkp/pkp-lib/pull/8621

**plugins**
staticPages: https://github.com/pkp/staticPages/pull/71

I found some issues in the DB migration and still working on that.

**Comment by asmecher** [comment]
Thanks, @defstat! This needs a few things...
- Please check on the DOS line endings noted [here](https://github.com/pkp/staticPages/pull/71) (but presumably affecting all repos)
- Please port the code changes to OMP and OPS and open PRs for those (don't worry about committing a sample conversion just yet -- reviewing the results of the merge on OJS, pkp-lib and staticPages repos are enough for now);
- I've added a few comments to https://github.com/pkp/pkp-lib/pull/8621/commits/2b6427ce259e9e7688eff55f0de5214394a4c618 and https://github.com/pkp/pkp-lib/pull/8621/commits/70bb4af778cf84b0c7c0438f72575e074e210b12 that could use a look

**Comment by asmecher** [comment]
Still needs fixing:
- [ ] Other plugins in Weblate (besides static pages)
- [ ] Various parts of the system that call `substr($locale, 0, 2)` -- not always accurate, e.g. for Kurdish, which is now `ckb`

**Comment by defstat** [comment]
> 



> Still needs fixing:
> 
> * [ ]  Other plugins in Weblate (besides static pages)
> * [ ]  Various parts of the system that call `substr($locale, 0, 2)` -- not always accurate, e.g. for Kurdish, which is now `ckb`

@asmecher I have added PRs for all plugins

I also changed the `substr($localeValue, 0, 2)` in the Migration to: 

```
$localeParts = explode('_', $localeValue);
$localeCode = $localeParts[0];
```

Do you mean something else regarding that?

One thing remaining: to add the plugin's db tables to the migration.

**Comment by asmecher** [comment]
@defstat, don't forget https://translate.pkp.sfu.ca/projects/plugins/ops-crossref-importexport-plugin/ / https://github.com/pkp/crossref-ops/!

**Comment by defstat** [comment]
> @defstat, don't forget https://translate.pkp.sfu.ca/projects/plugins/ops-crossref-importexport-plugin/ / https://github.com/pkp/crossref-ops/!

Thanks for the reminder - just added it

**Comment by asmecher** [comment]
I think this one is finally completed!!!

**Comment by kelynch** [comment]
We're currently on Open Journal Systems 3.3.0.8 and using the `es_ES` convention; do we need to upgrade OJS before we accept these new commits?

**Comment by asmecher** [comment]
@kelynch, yes, these changes are for release in 3.4.0 and it would be a complicated process to port them back to 3.3.0. Is there a particular change you need in 3.3.0-8?

**Comment by bess** [comment]
@asmecher I think we understand the issue and have a plan to move forward, thank you!

**Comment by asmecher** [comment]
@bess, OK, thanks! Let me know if I can provide any further context for these changes.
