### ISSUE TITLE
Request payment step is missing when skipping external review if APC is enabled

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8605]
**Describe the bug**
When [authors fees](https://docs.pkp.sfu.ca/learning-ojs/en/subscriptions#author-fees) are enabled there should be an option to request payment when submission is accepted, either with or without the review.

When article is accepted after the review, request payment option is shown to the editor
![requestPayment](https://user-images.githubusercontent.com/20665587/216684095-2ebbfae4-452b-4cd0-9ada-8997254352bc.png)
But this doesn't happen when article is accepted after skipping the review
![acceptAndSkip](https://user-images.githubusercontent.com/20665587/216684167-a90ae793-6f9c-4a6c-a175-07602ac274dc.png)

**To Reproduce**
1. Enable APC, as per [docs](https://docs.pkp.sfu.ca/learning-ojs/en/subscriptions#author-fees) 
2. Submit an article
3. Make a decision to accept and skip review
4. See the absence of the request payment option

**What application are you using?**
 OJS main branch

**Additional information**
Looking at the backend part, `RequestPayment` trait is used in both, `Accept` and `SkipExternalReview` but the latter lacks `getStep()` [method](https://github.com/pkp/ojs/blob/main/classes/decision/types/Accept.php#L62) to initialise the payment form

**Comment by Vitaliy-1** [comment]
PR OJS: https://github.com/pkp/ojs/pull/3744

**Comment by Vitaliy-1** [comment]
@NateWr, it looks like an easy fix but can you take a look just in case, I'm not yet familiar with this part of code.

**Comment by NateWr** [comment]
Merged to `main`, thanks @Vitaliy-1!
