### ISSUE TITLE
No licenseUrl elements found for issues when using Native XML export

### ISSUE THREAD

**Issue by mschomm** [pkp/pkp-lib#8607]
**Describe the bug**
After a command line XML export, no elements `<licenseUrl>` did show up in the generated output. The root cause was identified as a combination of a case-sensitive comparison/lookup in the source code and mismatching DB values for the column `publication_settings.setting_name`. More details under ‘Additional information’

**What application are you using?**
OJS version: 3.3.0.13 (after multiple updates since 2016)
PHP version: 7.4.33
OS: Windows Server 2016 Datacenter

**Additional information**
In `SchemaDAO->_fromRow()` the following line checks rows fetched from a '…_settings' database table against a JSON schema for an entity and only processes rows for which there is a matching property found in the schema. This comparison/lookup appears to be case-sensitive:
`if (!empty($schema->properties->{$settingRow['setting_name']})) {`
 
In our database rows from `publication_settings.setting_name` show the value 'licenseURL'. In the corresponding JSON schema file this property is given as 'licenseUrl' (last two characters not capitalised).
 
For our instance we executed the following SQL update statement to adapt the column values to the expectation of the current OJS source code:
`UPDATE publication_settings set setting_name = "licenseUrl" WHERE binary setting_name = 'licenseURL'; `
 
After that change `<licenseUrl>` elements were included in the export files.
 
This data omission was detected in the process of migrating our currently internally hosted OJS instance to an external hoster. Our production instance (running since 2016) is still on version 2.4.8.5, exports and problem analysis were done on a cloned VM with OJS upgraded to version 3.3.0.13.
 
In our original 2.4.8.5 instance the 'offending data' is found in the table `article_settings`, which indicates a schema update during the upgrade process to 3.2 or 3.3. Since the problem seems to originate from DB values for `setting_name` having strings differently capitalised in older versions of OJS, it might be a good idea to add a column value normalisation to this upgrade process. 
 
Also, since the source code in question is not specific to entities of class `PKPPublication` or the `publication_settings` DB table, similar data omission problems might occur for other 'non-primary table columns' and other 'settings' tables as well.
 
Another interesting point here is that our OJS instance does indeed show license information for articles/publications on the generated web pages. This hints at a different code path or different parameters used for obtaining data from the DB for HTML generation - which might be another problem to look at.

**Comment by NateWr** [comment]
I had a recollection of the renaming and tracked it down to this commit: https://github.com/pkp/ojs/commit/9e14bbb9a44df2e0709a73d01c27c13b9342ab70

It looks like that commit went into the 3.3.0 release but is part of a 3.2 upgrade script, so there was probably an upgrade gap.

**Comment by asmecher** [comment]
I'm going to chalk this up to an old upgrade issue; your work-around (the SQL query) should resolve it, @mschomm.
