### ISSUE TITLE
Ensure email templates of plugins have their names properly set 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8611]
**Describe the bug**
Unable to install email templates for the following plugins
- Orcid Profile
- Manual Fee Payment
- Paypal Fee Payment

All of them are missing the `name` attribute in the correspondent `emailTemplate.xml` file (already solved)

The second issue is with the name attribute migration, names need to be installed and for upgrades as well.

The related third issue is that email templates in plugins are installed in all available locales, rather than only in those that are installed (already solved)

**To Reproduce**
1. Install OJS or run upgrade from a command line `php tools/upgrade.php upgrade` 
2. See that templates are not installed in the `email_templates_default_data` table

**What application are you using?**
 OJS main branch

**Comment by Vitaliy-1** [comment]
As the `name` is a new email template attribute, it also requires migration

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8620
OJS: https://github.com/pkp/ojs/pull/3753

**Comment by Vitaliy-1** [comment]
@NateWr, can you take a look at these PRs? I also found another problem and tried to fix it - email templates of plugins are installed in all available locales, rather than only those installed on the site

**Comment by NateWr** [comment]
I'm not sure I really understand how migrations and plugin installs work. For example, `ManualPaymentPlugin::getInstallMigration()` will run `ManualPaymentEmailDataMigration`. But when is `getInstallMigration()` run?

Is it run when OJS/OMP/OPS is initially installed? Or when the plugin is installed? I'm not sure about the sequence. Do you know?

**Comment by asmecher** [comment]
> I'm not sure I really understand how migrations and plugin installs work...

There are some hook registrations in the base plugin `register()` plugin:
https://github.com/pkp/pkp-lib/blob/8ec256c0293c7c8c4d6b64a0108fb955d31c8fbc/classes/plugins/Plugin.php#L108..L133

These handle database table creation and email template installation (in that order).

These are triggered both during OJS/OMP/OPS installation (this is how the built-in plugins like static pages create their tables) and [when the plugins are separately installed](https://github.com/pkp/pkp-lib/blob/8ec256c0293c7c8c4d6b64a0108fb955d31c8fbc/classes/plugins/PluginHelper.php#L140) (this is how plugin gallery plugins like PKP|PN create their tables).

**Comment by NateWr** [comment]
Hmm, what does this mean for plugins included in the release package? Are their install hooks triggered during an upgrade? If not, then this migration won't work for existing installs.

@Vitaliy-1 have you tried running an upgrade from 3.3 with this migration in place to see if it is run?

**Comment by Vitaliy-1** [comment]
I'm running migration from a plugin using `Plugin::getInstallMigration()`. What I don't understand is how to determine the OJS version for which migration is attributed. @asmecher, I can't find any examples, should I include this logic to a plugin when running a migration or is there another way?

**Comment by NateWr** [comment]
@asmecher there are three things here, but I need your review on two of them:

1. First, the `Installer::$installedLocales` is configured to match all system locales (`Locale::getLocales()`). However, this value, `Installer::$installedLocales`, is used to install email templates. @Vitaliy-1 is proposing to use site installed locales here: https://github.com/pkp/pkp-lib/pull/8620/files. Is this ok or will it have side effects during the install process? (I'm not sure how `Installer::$installedLocales` is used.)

2. The other problem is described in @Vitaliy-1's comment above. In short: a plugin migration doesn't specify what version to run the migration against, so it will be run with every upgrade (even 3.4, 3.5, 3.6, etc). What's the best way to handle this?

This issue won't block testing in RC1 (except for a couple emails in the payment plugins), so I think we can solve it after RC1. But I'm not sure how to suggest Vitaliy proceed. Thanks!

**Comment by asmecher** [comment]
1. Yes, `Installer::$installedLocales` is meant to be used for this, IIRC.
2. This is currently an unsolved problem, unfortunately. The only place we've had to tackle it so far is the PLN plugin. It's very imperfect but works. See: https://github.com/pkp/pln/blob/0bfa3fbeb85c5f67b423ae107278316d37a194fd/PLNPluginSchemaMigration.inc.php#L25

**Comment by NateWr** [comment]
@asmecher do you know if the plugin migration is run before the core migration? If so, then @Vitaliy-1 could check the `versions` table to see what version is being upgraded from, and the code to see what version is being upgraded to.

Alternatively, as a short-term solution, @Vitaliy-1 could just convert this into a core migration in the `upgrade.xml` file. That way it is pegged to a specific version. Then we wouldn't need to solve this problem with a workaround right away...

**Comment by asmecher** [comment]
If there's time and the change is relatively small, I'd support making a test with the `versions` table check. I would eventually like to build out some infrastructure to support this, so trying it less formally with one plugin would be a good test case -- and we're about to do a lot of testing.

**Comment by Vitaliy-1** [comment]
I've filled a separate issue for a problem with installing the templates in all translated locales: https://github.com/pkp/pkp-lib/issues/8667

**Comment by Vitaliy-1** [comment]
PR OJS only: https://github.com/pkp/ojs/pull/3753

**Comment by Vitaliy-1** [comment]
@NateWr, can you take a look? Solving here only the issue with `name` attribute (add and migrate)

**Comment by NateWr** [comment]
Looks good @Vitaliy-1. Was there a migration needed for the Paypal plugin too? Or just this one?

**Comment by Vitaliy-1** [comment]
Only this one. It appears that Paypal plugin didn't send email and I've removed the email template

**Comment by NateWr** [comment]
Ok I'm happy for you to merge this when ready. :+1:

**Comment by Vitaliy-1** [comment]
Should also be shipped to OMP

**Comment by Vitaliy-1** [comment]
PRs
OJS: https://github.com/pkp/ojs/pull/3795
OMP: https://github.com/pkp/omp/pull/1352
