### ISSUE TITLE
Implement better logging for web service requests

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#862]
Alec has already provided a code sample to log web service requests to a log file when things fail.  Make this general, as a config.inc.php option for system admin debugging.

**Comment by asmecher** [comment]
Pulls were:
https://github.com/pkp/ojs/pull/661
https://github.com/pkp/pkp-lib/pull/864

**Comment by asmecher** [comment]
Committed to ojs-dev-2_4; needs forward-porting to OMP and OJS master.

**Comment by jnugent** [comment]
Forward ported to OMP and OJS master

**Comment by asmecher** [comment]
@jnugent, this didn't get added to the release notes as a new config option; could you add it? Also to config.TEMPLATE.inc.php.

**Comment by jnugent** [comment]
@asmecher I will add it to the release notes, but this is definitely already in config.TEMPLATE.inc.php with documentation.

**Comment by jnugent** [comment]
Add to RELEASE notes in ojs-dev-2_4.

**Comment by asmecher** [comment]
Right you are. Thanks, @jnugent.
