### ISSUE TITLE
Make the Native XML more resilient about missing files

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8627]
**Describe the bug**
In case a submission has a missing file, the Native XML plugin fails to export it, I'd like to be able to export it even though some parts of it might be broken.

As a user of a disk recovery software, I'd rather have a partial recovery than nothing, warnings/error messages are enough to let me know that something didn't go as expected, especially when the most important piece of data is still available.

Source:
https://forum.pkp.sfu.ca/t/status-pendente-plugin-pkp-pn/76262/22

**To Reproduce**
1. Erase physically a file of a submission
2. Attempt to export it through the Native XML plugin

**What application are you using?**
*

**PRs**
- `stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8653
- https://github.com/pkp/ojs/pull/3778
- **[TESTS ONLY]** https://github.com/pkp/omp/pull/1348
- OPS doesn't have support for the native plugin at the stable branch
- `main`
- https://github.com/pkp/pkp-lib/pull/8655
- https://github.com/pkp/ojs/pull/3780
- **[TESTS ONLY]** https://github.com/pkp/ops/pull/481
- **[TESTS ONLY]** https://github.com/pkp/omp/pull/1347

**Comment by NateWr** [comment]
@jonasraoni if you are not planning to work on this immediately can you convert it to a discussion?

**Comment by jonasraoni** [comment]
I'm waiting for something out of my control, so I can work on it :)

@asmecher do you have anything against skipping the missing files? I've seen it happening before with other users from the forum (e.g. submissions missing files from the folders review/fairCopy).

As long as the final files are present, I think it's better than nothing.

**Comment by asmecher** [comment]
I have no objection to skipping missing files when building an export.

**Comment by jonasraoni** [comment]
@asmecher/@defstat here are the PRs:

- `stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8653
- https://github.com/pkp/ojs/pull/3778
- `main`
- https://github.com/pkp/pkp-lib/pull/8655
- https://github.com/pkp/ojs/pull/3780

**Comment by jonasraoni** [comment]
Merged linked PRs.
