### ISSUE TITLE
Error when upgrading a large installation to OJS 3.3.0 under PostgreSQL

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8631]
**Describe the bug**
The following error happens when attempting to pass many parameters to a query:

`ERROR: Upgrade failed: DB: SQLSTATE[HY000]: General error: 7 number of parameters must be between 0 and 65535 (SQL: select “locale”, “submission_id” from “publications” where “publication_id” in ([…]))`

The exactly place that raised this error is this line:
https://github.com/pkp/pkp-lib/blob/13a717e0cbcc06262f8084d5ab6b11cb49009545/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.php#L150

**To Reproduce**
1. Attempt to pass more than 65535 (unsigned short) parameters to a query.

**What application are you using?**
*/stable-3_3_0

**Additional information**
https://forum.pkp.sfu.ca/t/ojs-problems-updating-from-3-2-1-1-to-3-3-0-10-lts-postgresql/73018

**PRs**
- **`stable_3_3_0`**
- https://github.com/pkp/pkp-lib/pull/8641
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3768
- **`main`**
- https://github.com/pkp/pkp-lib/pull/8642
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3769

**Comment by asmecher** [comment]
@jonasraoni, it looks like the query could easily be adapted to using...
```
->whereIn('publication_id', function($query) {
   ...
})
```
...instead of...
```
->whereIn('publication_id', $currentPublicationIds)
```
I'd welcome a PR for this, or may try to get to it after 3.4 is released.

**Comment by jonasraoni** [comment]
@asmecher, here are the PRs:

- **`stable_3_3_0`**
- https://github.com/pkp/pkp-lib/pull/8641
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3768
- **`main`**
- https://github.com/pkp/pkp-lib/pull/8642
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3769

**Comment by asmecher** [comment]
Thanks, @jonasraoni -- have you tested that with the original upgrade where you encountered the issue?

**Comment by jonasraoni** [comment]
This happened with a user from the forum (he solved by himself with a "chunk by 65535"), I'll check if he's able to test :)

**Comment by jonasraoni** [comment]
@asmecher The user confirmed it worked (https://forum.pkp.sfu.ca/t/ojs-problems-updating-from-3-2-1-1-to-3-3-0-10-lts-postgresql/73018/16?u=jonasraoni)

**Comment by asmecher** [comment]
:+1: Perfect, thanks, @jonasraoni!
