### ISSUE TITLE
Recommend Similar Articles plugin not showing all articles with a same keyword

### ISSUE THREAD

**Issue by MlaplanteD** [pkp/pkp-lib#8633]
**Describe the bug**
Only articles with the exact same keywords are showed in the section Similar Articles if the article has more than 2 keywords. For exemple, an article with 2 keywords (ex: open access + journals) will show in the section Similar Articles only the articles with the keyword “open access + journals”, not the articles containing only the keyword “open access”.

I would expect the system to use the OR operator to find all articles with similar keywords, not just article with the exact two or three keywords. 

**To Reproduce**
1. Enable Recommend Similar Articles plugin
2. Publish two articles : one with only one keyword (eg : open access), the other with 2 keywords, one is the same than the first article (eg : open access; journals)
3. Go to the article with 2 keywords
4. Scroll down to Similar Articles in the Article Footer.
5. No similar article is showed

**What application are you using?**
OJS 3.3.0.13

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by jonasraoni** [comment]
This one will be covered by #8710
