### ISSUE TITLE
unknown messages appears in discussion OJS 3.3

### ISSUE THREAD

**Issue by memes1987** [pkp/pkp-lib#8637]
In OJS 3.3 unknown messages appears in discussion, messages are empty and users didn't sent them.

![bug](https://user-images.githubusercontent.com/123550076/219035184-2224b568-e992-4b53-a877-bd09b9972f79.jpg)

**Comment by asmecher** [comment]
@memes1987, could you try our support forum for questions like this? First try searching for an existing issue, then if you don't find one, create a new topic there. https://forum.pkp.sfu.ca
