### ISSUE TITLE
OJS: Eternally loading 

### ISSUE THREAD

**Issue by nmpx** [pkp/pkp-lib#866]
Not sure if this problem is replicated in other areas, but I was in Journal Settings -> policies.

Filled in some of the fields and hit 'save'. Got the notification that it was saved, but the 'I'm processing' image didn't stop after 5 minutes.

Attached is a screenshot.

edit: I checked a few other places and the loading image never goes away.

![bug02](https://cloud.githubusercontent.com/assets/5183702/10947196/b5e2f4d2-82f4-11e5-90a3-a3b2482320ea.png)

**Comment by asmecher** [comment]
@nmpx, there's probably a PHP error message in the log. Is this an install you're testing on one of our servers?

**Comment by nmpx** [comment]
@asmecher no, not on one of your servers. i'm on a virtual machine. where are your servers?

**Comment by asmecher** [comment]
Can you check in your PHP error log (probably somewhere in `/var/log/` on the VM) for errors?

**Comment by nmpx** [comment]
My log didn't register any errors. I actually decided to destroy the machine and do a very fresh install (debian 8/apache/php/mysql). I'm still getting the eternally loading image.

**Comment by asmecher** [comment]
The other possibility is that you're hitting a Javascript error -- the formatting of the "Save" button suggests to me that this is the case. If you don't have it, can you install a developer tool like Firebug and check the console there to see if there are any listed Javascript errors, either before hitting "Save" or upon hitting it?

**Comment by nmpx** [comment]
Here's what I'm getting from Chrome's console:

```
jquery.js:9627 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
tinymce.js:154 'webkitMovementX' is deprecated. Please use 'movementX' instead.
tinymce.js:154 'webkitMovementY' is deprecated. Please use 'movementY' instead.journal:176 GET http://localhost:8080/plugins/generic/lucene/js/LuceneAutocompleteHandler.js 
jquery.js:9627 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```

**Comment by asmecher** [comment]
Hmm, nothing unusual there. What version of the software are you using? (3.0 beta, or master checkout? If a master checkout, is it up to date both in the ojs and pkp-lib repositories?)

I've just checked a recent checkout of the master branch and couldn't duplicate the problem.

**Comment by nmpx** [comment]
Ah. I'm using 3.0 beta. Should I be testing master checkout to ensure that any bugs I find are still relevant? I can do that.

**Comment by asmecher** [comment]
Hi @nmpx -- yes, it would be better to check out the master branch from git (both ojs and pkp-lib); we've done quite a bit of work since the beta release. Let me know if you get stuck on anything. Two current gotchas:

    cd lib/pkp
    composer update

(You might need to install Composer first)

...and if you keep your current DB from OJS 3.0b, you'll need to run (in MySQL)...

    ALTER TABLE users CHANGE COLUMN password password VARCHAR(255);

**Comment by nmpx** [comment]
Okay. cool. I'm close this issue then.

**Comment by asmecher** [comment]
Thanks!

**Comment by mimolore** [comment]
Hi Alec, I have a similar problem in my OJS installation 2.4.7.1 on centos server. this is the mesage on chrome console, when I try load a image to a journal or i want to access like admin or manager: "**Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/**." . The server administrator says that is a .js problem in tyni mce. please help me and thanks.

**Comment by asmecher** [comment]
@mimolore, I think that's a different issue; could you post this in our support forum at http://forum.pkp.sfu.ca/?

**Comment by aplatanado** [comment]
Hi. I have similar issue that could be related.

The URL `/index.php/<journal here>/notification/` never shows any notification and the loading image never goes away.

Javascript report an error:

Uncaught ReferenceError: $ is not defined(anonymous function)

and the code is this:

~~~.javascript
<script>
	// Initialise JS handler.
	$(function() { <--------- Error here
		$('#normalNotificationsGridContainer').pkpHandler(
			'$.pkp.controllers.UrlInDivHandler',
			{
				sourceUrl: "http:\/\/imedicalsociety.org\/ojs\/index.php\/iam\/$$$call$$$\/grid\/notifications\/normal-notifications-grid\/fetch-grid"
			}
		);
	});
</script>
~~~

**Comment by asmecher** [comment]
@aplatanado, this issue is somewhat different and has already been closed. Could you start by posting this in the forum at http://forum.pkp.sfu.ca/? Make sure to check your PHP error log and post your OJS version number.

**Comment by aplatanado** [comment]
Yes, I can. I'm sorry. I don't see the issue has been closed. I though it could be related.
