### ISSUE TITLE
Submission file with validation error leads to fatal error

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8665]
**Describe the bug**
When uploading a submission file, if the file has a validation error it will cause a fatal application error. This happens when the system tries to delete the file on disk.

**To Reproduce**
1. Use the REST API to upload a file to `POST submissions/{id}/files`. Include a `createdAt` in the post body to trigger a validation error. See: https://docs.pkp.sfu.ca/dev/api/ojs/3.3#tag/Submissions-Files/paths/~1submissions~1{submissionId}~1files/pos
2. See error.

**What application are you using?**
 `main` branch (3.4 pre-release)

**Additional information**
Error:

```
Slim Application Error:
Type: Exception
Message: Unable to delete file 50 at journals/1/articles/21/63f33b929210d.png.
File: /home/vagrant/htdocs/ojs-master/lib/pkp/classes/services/PKPFileService.php
```

This exception is thrown here:

https://github.com/pkp/pkp-lib/blob/84c5a17c958948a4d5b29bdbd935c89ff835d17a/classes/services/PKPFileService.php#L124-L126

And this is caused because v3+ of Flysystem expects the `delete()` method to be in a `try`/`catch` block:

https://flysystem.thephpleague.com/docs/usage/filesystem-api/#deleting

The following does not return `true` or `false` as expected in the conditional:

```php
$this->fs->delete($path)
```

**Comment by asmecher** [comment]
I wasn't able to replicate the problem in my local testing, but the description looks clear enough and the fix was quick and easy.
