### ISSUE TITLE
[OJS 3.3] Shariff plugin translations not available on weblate

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#8672]
**Describe the bug**
The Shariff plugin for Social media sharing has no french translations, however, it is nowhere to be found in the Weblate website.

**To Reproduce**
I have tried searching weblate using parmeters used by the Shariff plugin on the following projects: 
1. Common Plugins
2. Open Journal Systems 
3. PKP Web Application Library 

Parameter used for searching: 

- plugins.generic.shariff.settings.service.shared_content.note (note describing the plugin ; in english: "This plugin only shares the page URL with the selected service provider. The type of content presented to the public depends on the selected service provider and is usually extracted from the HTML headers metadata. Please verify what metadata you share in your HTML header.")
- plugins.generic.shariff.displayName (name of the section added in Parameters > Website > Appearence ; "Shariff Plugin" in english).

**Comment by asmecher** [comment]
@pilasou, we can add 3rd-party plugins to Weblate by request -- best to contact me directly, rather than filing a issue. In order for Shariff to be added, a few things will be necessary; I've proposed them [here](https://github.com/ojsde/shariff/pull/31).
