### ISSUE TITLE
Remove unsupported email config settings 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8673]
Settings not supported by Symfony Mailer:

- `smtp_authtype`. Symfony doesn't support this configuration and tries authentication in the following order: CRAM-MD5, LOGIN, PLAIN, XOAUTH2. It's the same order that was with PHPMailer
- OAuth 2.0 protocol related settings. This is used to connect to Google APIs. Although it still possible to connect through Symfony Mailer to Gmail through the API using only username and password, the implications of this are not known. Nevertheless, there is another option with app-specific password. Unfortunately, both options won't work with Microsoft products starting from 2023, see: https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online 
- `smtp_suppress_cert_check`

**Comment by Vitaliy-1** [comment]
PR: https://github.com/pkp/ojs/pull/3793

**Comment by Vitaliy-1** [comment]
@asmecher, there are still two email settings present that aren't used and I don't know where they origin from: `time_between_emails` and `max_recipients`. I can't find them in the code in 3.3 either. Are they still needed/require implementation somewhere or just can be removed?

**Comment by asmecher** [comment]
Those can be removed; they've been unused since at least 3.1.2. They used to be part of the mass email sending process, but that's long obsolete.

**Comment by Vitaliy-1** [comment]
Leaving `smtp_suppress_cert_check` to implement as Symfony supports it
