### ISSUE TITLE
Selected issue filter not visible in DOI management UI 

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8676]
**Describe the bug**
When filtering DOIs by issue, the selected issue filter is not visible. It looks like no issue filter is applied.

**To Reproduce**
1. Make sure DOIs are enabled at Settings > Workflow > DOIs.
2. Click on DOIs in the left-hand navigation menu.
3. Under filters, type the first part of an issue identifier (in the test data, this would be `Vol. 1`).
4. When the issue appears, click to selected.
5. See that the list updates with the filter applied, but there is no indication of the selected issue.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
Probably, the `autosuggestProps` passed down to this filter need to include the `value` that is derived from `activeFilters`. In other words, when the `activeFilters` change to include an issue filter, the `value` prop passed to the autosuggest needs to be updated to include this.

I also noticed a bit of commented out code that should be fixed or removed.

https://github.com/pkp/ui-library/blob/ab6086b6d29b6d1d249c0d0c31b028d6f3a585f6/src/components/ListPanel/doi/DoiListPanel.vue#L481-L501

**Comment by NateWr** [comment]
This also effects the autosuggest filters in the main submissions list.

**Comment by NateWr** [comment]
@ewhanson do you have time to code review this? The problem was introduced when I rewrote the autosuggest field a little while ago. Now the field changes both the `value` prop and the `selected` prop when a suggestion is selected. But the filter was only expecting the `value` prop to change. This PR introduces `currentValue` and `currentSelected` data to the autosuggest filter so that it can manage the state of the currently selected values and pass that back down into the autosuggest field properly.

PR:
https://github.com/pkp/ui-library/pull/264

Tests:
https://github.com/pkp/ojs/pull/3797

**Comment by ewhanson** [comment]
Hey @NateWr, looks good to me! Did some manual testing as well and all is working as expected. No more Vue-related errors in the console either.

**Comment by NateWr** [comment]
Thanks @ewhanson, all merged!
