### ISSUE TITLE
Chapter landing pages preview not possible

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8679]
**Describe the bug**
When a book that is not published yet and contains a chapter that should have its own landing page is previewed and one goes to that chapter landing page 404 error happens.
It is because of this line, where it is required for the publication to be published: https://github.com/pkp/omp/blob/main/pages/catalog/CatalogBookHandler.php#L506.

**To Reproduce**
1. Go to an unpublished submission that contains chapters
2. Edit the chapter, select the option "Show this chapter on its own page and link to that page from the book's table of contents." and save the form.
3. Click on 'Preview'
4. Click on the chapter title
5. See error

**What application are you using?**
OMP 3.4.0.0

----
PR:
https://github.com/pkp/omp/pull/1350

**Comment by bozana** [comment]
@asmecher, could you take a look at this PR?

**Comment by asmecher** [comment]
@bozana, please go ahead, thanks!

**Comment by asmecher** [comment]
I went ahead and merged it.
