### ISSUE TITLE
smtp_suppress_cert_check not being honored

### ISSUE THREAD

**Issue by gianfj** [pkp/pkp-lib#8687]
**Describe the bug**
smtp_suppress_cert_check not being honored and sending email is failing because the SSL certificate is being checked

**To Reproduce**
1. edit config.inc.php
2. set
[email]
default = smtp
smtp_suppress_cert_check = On
(the test server has no authentication and it's ainternal server so it does not have a valid SSL certificate
3. Send a test email
4. From apache logs
[Wed Feb 22 15:34:19.866187 2023] [php:notice] [pid 23] [client XXX.XXX.XXX.XXX:39480] Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed, referer: REDACTED

**What application are you using?**
OJS/OPS 2.4 (main branch) - 3_4_0rc1 tag

**Comment by asmecher** [comment]
Thanks, @gianfj! This is happening because the mailing back-end was switched replaced (Symfony Mailer instead of PHPMailer) and this setting appears no longer to be used.

@Vitaliy-1, assigning to you for a look; it might be worth checking other settings in the `email` section to ensure they're hooked up.

**Comment by Vitaliy-1** [comment]
It appears to be supported by Symfony Mailer, see: https://symfony.com/doc/current/mailer.html#tls-peer-verification

**Comment by gianfj** [comment]
In a quick replication, setting verify-peer to false fixes the issue.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8745
OJS: https://github.com/pkp/ojs/pull/3813
OMP: https://github.com/pkp/omp/pull/1356
OPS: https://github.com/pkp/ops/pull/486
