### ISSUE TITLE
OMP default install is broken

### ISSUE THREAD

**Issue by gianfj** [pkp/pkp-lib#8690]
**The default instructions for OMP installs causes error 500**

**To Reproduce**
1. install OMP: git pull + composer commands + npm commands
2. Try to open the default page (installation)

Apache will show:
[Thu Feb 23 14:42:10.967450 2023] [php:warn] [pid 17] [client XXX.XXX.XXX.XXX:60246] PHP Warning:  require_once(/var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.php on line 18
[Thu Feb 23 14:42:10.968121 2023] [php:error] [pid 17] [client XXX.XXX.XXX.XXX:60246] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.php:18\nStack trace:\n#0 /var/www/html/lib/pkp/lib/vendor/composer/ClassLoader.php(571): include()\n#1 /var/www/html/lib/pkp/lib/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('/var/www/html/l...')\n#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('APP\\\\plugins\\\\gen...')\n#3 /var/www/html/lib/pkp/classes/plugins/PluginRegistry.php(190): class_exists('\\\\APP\\\\plugins\\\\ge...')\n#4 /var/www/html/lib/pkp/classes/plugins/PluginRegistry.php(240): PKP\\plugins\\PluginRegistry::_instantiatePlugin('generic', 'citationStyleLa...')\n#5 /var/www/html/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\\plugins\\PluginRegistry::_loadFromDisk('generic')\n#6 /var/www/html/lib/pkp/classes/core/Dispatcher.php(153): PKP\\plugins\\PluginRegistry::loadCategory('generic', true)\n#7 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))\n#8 /var/www/html/index.php(21): PKP\\core\\PKPApplication->execute()\n#9 {main}\n  thrown in /var/www/html/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.php on line 18

3. As the issue appears to be in the citationStyleLanguage plugin, tried: ```composer --working-dir=plugins/generic/citationStyleLanguage install```
4. It fails with:
```
$ composer --working-dir=plugins/generic/citationStyleLanguage install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 4 installs, 0 updates, 0 removals
  - Syncing citation-style-language/locales (1.0.0) into cache
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=Composer+on+f393fcf55442+2023-02-23+1447 to retrieve a token.
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+f393fcf55442+2023-02-23+1447
Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer.
Tokens will be stored in plain text in "/home/www-data/.composer/auth.json" for future use by Composer.
For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth
Token (hidden):
In QuestionHelper.php line 431:

  [Error]
  Call to undefined function Symfony\Component\Console\Helper\shell_exec()


Exception trace:
  at phar:///usr/local/bin/composer/vendor/symfony/console/Helper/QuestionHelper.php:431
 Symfony\Component\Console\Helper\QuestionHelper->getHiddenResponse() at phar:///usr/local/bin/composer/vendor/symfony/console/Helper/QuestionHelper.php:120
 Symfony\Component\Console\Helper\QuestionHelper->doAsk() at phar:///usr/local/bin/composer/vendor/symfony/console/Helper/QuestionHelper.php:67
 Symfony\Component\Console\Helper\QuestionHelper->ask() at phar:///usr/local/bin/composer/src/Composer/IO/ConsoleIO.php:314
 Composer\IO\ConsoleIO->askAndHideAnswer() at phar:///usr/local/bin/composer/src/Composer/Util/GitHub.php:104
 Composer\Util\GitHub->authorizeOAuthInteractively() at phar:///usr/local/bin/composer/src/Composer/Util/Git.php:124
 Composer\Util\Git->runCommand() at phar:///usr/local/bin/composer/src/Composer/Util/Git.php:310
 Composer\Util\Git->syncMirror() at phar:///usr/local/bin/composer/src/Composer/Util/Git.php:328
 Composer\Util\Git->fetchRefOrSyncMirror() at phar:///usr/local/bin/composer/src/Composer/Downloader/GitDownloader.php:73
 Composer\Downloader\GitDownloader->doDownload() at phar:///usr/local/bin/composer/src/Composer/Downloader/VcsDownloader.php:73
 Composer\Downloader\VcsDownloader->download() at phar:///usr/local/bin/composer/src/Composer/Downloader/DownloadManager.php:228
 Composer\Downloader\DownloadManager->Composer\Downloader\{closure}() at phar:///usr/local/bin/composer/src/Composer/Downloader/DownloadManager.php:240
 Composer\Downloader\DownloadManager->download() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:105
 Composer\Installer\LibraryInstaller->download() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:353
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:282
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:759
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:281
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:137
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1015
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:334
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:130
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:88
 require() at /usr/local/bin/composer:29
 ```

**What application are you using?**
OMP (main branch), latest commit 1b4835f3e034e60a57f31467cdd9c34fa5a68979

**Additional information**
The same issue does not happens on OJS even using the same plugin

**Comment by asmecher** [comment]
@gianfj, when you're using a git checkout, you'll need to install the Composer dependencies manually. The citationStylePlugin has additional dependencies, so:
```
cd /path/to/ojs/plugins/generic/citationStylePlugin
composer install
```

**Comment by gianfj** [comment]
Hi @asmecher 

I did it, please see '4.'

**Comment by gianfj** [comment]
Hi @asmecher 

No worries. git is installed:
```
$ git --version
git version 2.20.1
```

**Comment by asmecher** [comment]
@gianfj, could you investigate this further on that machine, or else use the tarball with the dependencies already included? This is something to do with git/composer on that machine, not something wrong with OMP.

**Comment by asmecher** [comment]
Oh! I see the issue right here:
```
Call to undefined function Symfony\Component\Console\Helper\shell_exec()
```
Composer uses `shell_exec` to invoke the Git binary when it needs to; it appears that `shell_exec` is disabled in your PHP configuration, so Composer can't use it. You'll have to enable `shell_exec`, at least temporarily.

**Comment by gianfj** [comment]
Hi @asmecher 

Thank you for pointing me out to the right direction, enabling shell_exec did the trick. It seems only citationStyleLanguage on OMP is calling git using shell_exec, OJS and OPS are working fine.
