### ISSUE TITLE
When searching for a user, the results might be not visible in the interface

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8696]
**Describe the bug**
After moving to the next page of results, the "page" gets sticky, then if you attempt to search for something else, the interface will attempt to keep at the same page.

As part of the fix, it's better to search if this is being used elsewhere.

**To Reproduce**
1. Access the user list at `Settings` > `User & Roles`
2. Go to the second page of results (or any other)
3. Try to search for an existing user (something with few matches)
4. See the error

**What application are you using?**
 OJS/stable-3_3_0

**Additional information**
![image](https://user-images.githubusercontent.com/361921/221510418-17cbd5c0-2121-4ab7-b62c-22425b78cc6f.png)

![image](https://user-images.githubusercontent.com/361921/221509671-833c7eec-ec39-4165-ae64-79a9846a58c3.png)

---------------------------------------------------------------
**PRs**

**Branch `main`**
PKP-LIB: #8842
OJS: pkp/ojs#3850 ***TESTS ONLY***

**Comment by amandastevens** [comment]
In my testing, I found that I got no results when I searched for a user, either by username or by role. I'm not sure if this is the same bug. 

You can see in the list of users that there is a user called "copyeditor."
![List of users](https://user-images.githubusercontent.com/35044512/224457962-a5cf29e5-b323-4105-ac32-195894634df9.png)

But when I search for "copyeditor" I get no results. I tried also searching for "copy," "Copy," and other usernames and still got no results. I also tried leaving the Search box blank and selecting a role, and still I got no results.
![User search - no results](https://user-images.githubusercontent.com/35044512/224457970-c801047e-3f31-438f-b748-8773b36ebad3.png)

**Comment by jonasraoni** [comment]
Hi @amandastevens, by watching at the page number of your screenshot, I see it's the same problem.

**Comment by defstat** [comment]
@asmecher @jonasraoni there is the mix of the PagingFeature and the "Search" filter in other places also. 

Also I could not find another place in the code where I could put the change of the request.
So I decided to leave the code there, I just added a check to apply the conditional code only if the grid has the `PagingFeature` attached.

**Comment by asmecher** [comment]
Merged, thanks!
