### ISSUE TITLE
User search at stage participant assignment performing as case sensitive search for PostgreSQL

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8697]
**Describe the bug**
Installation running on PostgreSQL DB, the user search for a submission to assign participant to a stage causing empty result to return because of case sensitive search. 

**To Reproduce**
See details at https://forum.pkp.sfu.ca/t/remove-case-sensitive-search-when-assigning-participants/77033

**What application are you using?**
 OJS 3.3.0-14

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8698
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3798 [TEST ONLY]

**Comment by touhidurabir** [comment]
@asmecher Please review the PRs at https://github.com/pkp/pkp-lib/issues/8697#issue-1600903209 if test all passes .

**Comment by touhidurabir** [comment]
@asmecher I think it's good to merge now .

**Comment by asmecher** [comment]
Merged, thanks, @touhidurabir! I think we already confirmed that this doesn't need forward-porting to `main`, right?

**Comment by touhidurabir** [comment]
> I think we already confirmed that this doesn't need forward-porting to `main`, right?

@asmecher  Yes . I have tested it in main and it works fine there so no forward porting needed . I am closing it as completed .
