### ISSUE TITLE
Slowness at the "user & roles" page

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8700]
**Describe the bug**
A journal with around 20K users is taking around 60s to retrieve a response for the `User & Roles` interface.

The origin is MySQL trashing the disk with temporary tables (our `max_heap_table_size` is defined with 128MB, which is a reasonably high value) for the query, which can't be perfectly optimized.

**What application are you using?**
OJS/stable-3_3_0

**Additional information**
![image](https://user-images.githubusercontent.com/361921/221585883-8c49f1f7-5456-417d-9ad9-f85033be92fe.png)

**PRs**
- **`stable-3_3_0`**
- https://github.com/pkp/pkp-lib/pull/8702
- https://github.com/pkp/ojs/pull/3799
- https://github.com/pkp/omp/pull/1386
- https://github.com/pkp/ops/pull/510
- **`stable-3_4_0`**
- https://github.com/pkp/pkp-lib/pull/9994
- https://github.com/pkp/ojs/pull/4286
- https://github.com/pkp/omp/pull/1572
- https://github.com/pkp/ops/pull/686
- **`main`**
- https://github.com/pkp/pkp-lib/pull/9997
- https://github.com/pkp/ojs/pull/3870
- https://github.com/pkp/omp/pull/1387
- https://github.com/pkp/ops/pull/511

**Comment by asmecher** [comment]
@jonasraoni, are you going to work on this yourself? If so, great; if not, this isn't enough to be able to reproduce and correct the issue.

**Comment by jonasraoni** [comment]
Okay, I've assigned myself.

I did a generic fix on the `DAO.inc.php` which brought the time to 8s, and another specific one which decreased it to 2s.

I'll create a PR and check if the Laravel framework does a similar optimization out-of-the-box.

**Comment by jonasraoni** [comment]
@asmecher Here are the PRs
- https://github.com/pkp/pkp-lib/pull/8702
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3799

**Comment by jonasraoni** [comment]
@asmecher You might take a look again at the PRs, I've replaced my query optimizer by manual interventions and added a macro to address Laravel.

**Comment by asmecher** [comment]
@jonasraoni Thanks, this looks like a good solution for `stable-3_3_0`, if you can prove it out a little by applying it to hosts who have identified a performance problem. If they're happy after some use, I'm OK to commit it to `stable-3_3_0`. For `main` / `stable-3_4_0` (when that branch is created), I'd rather use an approach that's a bit more querybuilder-centric, as I think we discussed on one of the PRs.

**Comment by jonasraoni** [comment]
> If you can prove it out a little by applying it to hosts who have identified a performance problem. If they're happy after some use.

Great, I'll do it! How much time are you planning to run the test? I'd say that 1 month should be enough, but if you're ok with less, no problems.

> For `main` / `stable-3_4_0` (when that branch is created), I'd rather use an approach that's a bit more querybuilder-centric

For the main, I prototyped this (I'll just move the function to another place, perhaps a `DatabaseExtensionsServiceProvider`):
https://github.com/pkp/pkp-lib/pull/8702/files#diff-1f9b4a313ad0dfc341b0ed9d6d38cdf0588e4c533f9a3d346198648fe172bff0R228-R238

Perhaps this extension exists somewhere, I can try to find a package 🤔

**Comment by asmecher** [comment]
@jonasraoni, I'm still against the introduction of `safeCount` per [this comment](https://github.com/pkp/pkp-lib/issues/8700#issuecomment-1496135701) -- the performance problem can be resolved by using the query builder to drop the `orderBy` condition before counting. A safer counting function is something that should be introduced at the Laravel querybuilder level or below, not maintained as part of this project.

**Comment by jonasraoni** [comment]
@asmecher, it's not even about the performance, the main issues/justifications for this function are:
- Considering that we allow users to intercept/modify queries AND that we also have query builder extensions...
If a base query introduces a `GROUP BY`/`UNION`, the `count()` call will keep working, but its result will be **wrong**, until someone flags it. The proper fix requires going with the fix covered by the `safeCount()`.
- Due to the previous problem, it's not possible to add the performance improvement blindly everywhere. It's needed to inspect every query... Then apply the fix (enclose with a sub-query) or ignore the improvement. But this is error-prone, we don't have control over user-defined code, and we, developers, will fail to check if upstream changes break code down below the road (there will be no `Exception`).
- Miscounting isn't the only issue within the Laravel `count()`, this query generates an `Exception`: `DB::table('submissions')->select('submission_id AS x')->groupBy('x')->count()`

This function gives me confidence that I'm counting properly the rows. I could add it everywhere without even watching the underlying code.

Again, I'm not proud of having to do the dirty job that should be done by the database (avoid computing not-needed things) and lastly by Laravel, but it is what it is... **IF** the fix was very complex or didn't bring measurable gains, I'd be ok to discard it.

This is the last time I'll try to convince you, so feel free to give me a straight yes or no 😁

**Comment by asmecher** [comment]
Sorry, but no, I don't support adding `safeCount`. We're wedded to Laravel, usually for better and rarely for worse; they've [considered and rejected](https://github.com/laravel/framework/issues/22883#issuecomment-438521002) changes to the `count()` function to resolve this same issue there. I'd like to respect that choice, even if I don't 100% agree with it, rather than going the opposite direction and maintaining the code in application space to do that. (We have a long history of going the opposite route with ADODB and it got expensive and confusing.) Resolving the performance issue originally filed here just requires a `reorder()` call (or, as noted below, `getCountForPagination()`) and the rest (unless I've missed it) is hypothetical.

It does appear that there is a Laravel-level function that does what you want -- [`getCountForPagination`](https://laravel.com/api/10.x/Illuminate/Database/Query/Builder.html#method_getCountForPagination). If that serves the purpose, it would keep us "Laravel-standard" while avoiding the performance problem. Would that work?

**Comment by jonasraoni** [comment]
@asmecher The `getCountForPagination()` fits my expectations, and it's a natural replacement to my workaround. I've updated the PRs, if you'd like to double check, it's ready. If everything was ok last time, I can proceed with the merge, the only extra addition was replacing `offset(0)->limit(0)->getCount()` by `getCount()` (I didn't do it on `stable-3_3_0` though).

ps: Only Travis was able to build my PRs for `main`, I might take a look at the GitHub actions later (it might not be understanding the long branch)

**Comment by jonasraoni** [comment]
Ok, I'll check the effort of porting the SQL generation into the QueryBuilder 👌

**Comment by jonasraoni** [comment]
Closing this one, I fixed a couple of unrelated bugs and converted the affected queries to the Laravel Query.
