### ISSUE TITLE
Crossref username character limit too low

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#8705]
**Describe the bug**
Crossref usernames now include both an email and a role, which frequently extend beyond the 50 character limit for the username. With this users are unable to successfully save their credentials or use the plugin to deposit metadata.

**To Reproduce**
1. Go to 'Crossref Export Plugin' settings page under tools.
2. Enter a username longer than 50 characters.
4. See error.

**What application are you using?**
 OJS 3.3, but also applicable to OPS 3.3 and OJS/OPS 3.4.

**Additional information**
N/A

**Comment by bozana** [comment]
@ewhanson, I saw you working on this :-) And I have just checked the changes you have made once again, and they look good to me. 
Thus, if this should go into 3.4 could you provide the PRs and merge, maybe together with the submodule update...
