### ISSUE TITLE
Use salt from config file to encrypt IP addresses in usage stats

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8709]
**Describe the problem you would like to solve**
In order to encrypt the IP addresses in the usage stats logs, the application creates a `salt` file in `<files_dir>/usageStats`. As a result, we now have three different salts and secret keys in the system:

| Name | Location |
| --- | --- |
| `salt` | In `config.inc.php` |
| `api_key_secret` | In `config.inc.php` |
| `salt` | in `<files_dir/usageStats` |

**Describe the solution you would like to see**
I think the usage stats should re-use the salt from the config file. I would be prefer that we have just one salt used for all three cases. But that may require more discussion.

**What application are you using?**
`main` branch (3.4 pre-release)

**Comment by bozana** [comment]
The usage stats salt 'needs' to be created anew daily, so that it is 'not possible' to recalculate the IP address...

**Comment by NateWr** [comment]
Ah, I see! That makes sense. Sorry for the noise. :+1:
