### ISSUE TITLE
Performance issues at the plugin "Recommend By Similarity"

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8710]
**Describe the bug**
This plugin is causing an excessive delay on the article response, even when the server isn't under heavy load.

As an example, a single article takes < 2s to be loaded, but once the plugin is enabled, it goes up to 10s (when the server a bit loaded, the number went up to 60s)

**What application are you using?**
OJS/stable-3_3_0

**Comment by jonasraoni** [comment]
As part of this assignment, I might end up solving related issues at the plugin (https://github.com/pkp/pkp-lib/issues/7866, https://github.com/pkp/pkp-lib/issues/8633)

**Comment by jonasraoni** [comment]
@asmecher here's an initial PR for this one, if you agree, then I'll create extra PRs wherever is needed:
- https://github.com/pkp/ojs/pull/3804

**Comment by jonasraoni** [comment]
@asmecher I've created these extra PRs for `main`:
- https://github.com/pkp/pkp-lib/pull/8912
- https://github.com/pkp/ojs/pull/3874

**Comment by asmecher** [comment]
@jonasraoni, we're too close to the 3.4.0 release for substantive changes; can you separate the changes that resolve the hard errors (e.g. https://github.com/pkp/pkp-lib/issues/8947) from the code rearrangement?

**Comment by jonasraoni** [comment]
Yeah, I'll create a small one and leave the bigger changes for post 3.4 release 👌

**Comment by jonasraoni** [comment]
It was a small fix, so I've already commited to `main` and updated the "close resolution" on the other issue. I'll add the PRs here to my post-3.4 list.

**Comment by asmecher** [comment]
@Vitaliy-1, could you review the remaining PRs on this issue? There will be some impact on the submissions list changes due to the submission collector changes, so keep those in mind.

**Comment by Vitaliy-1** [comment]
Looks good to merge! I left a comment regarding improving the search ranking results but it's optional.
