### ISSUE TITLE
DAOResultFactory::getCount() may get called N times

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8714]
**Describe the bug**
Given the `DAOResultFactory` instance may be holding a complex query, it makes sense to cache the result of its `getCount()` method, which is called by other methods of the class.

As an example, some templates have a call to `wasEmpty()`, followed by a paging, which later on calls the `getPageCount()` (both methods make use of the `getCount()`).

**What application are you using?**
OJS/stable-3_3_0

**PRs**
- `stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8720
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3806
- `main`
- https://github.com/pkp/pkp-lib/pull/8721
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3807

**Comment by jonasraoni** [comment]
@asmecher here are some small PRs
- `stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/8720
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3806
- `main`
- https://github.com/pkp/pkp-lib/pull/8721
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3807

**Comment by asmecher** [comment]
Merged, thanks!
