### ISSUE TITLE
Unable to update email via profile

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#8715]
**Describe the bug**
During OJS 3.4 testing, found that a user is unable to change email address via their Profile. 

**To Reproduce**
1. Go to Profile
2. Click on Edit Profile followed by Contact
![image](https://user-images.githubusercontent.com/50342731/222574618-5bb52996-9782-4d88-aeb3-8624572d5652.png)
3. Change email address - tried mailiator, hotmail, gmail
![image](https://user-images.githubusercontent.com/50342731/222574691-925b9e26-d19a-44d1-b020-58f93a4db5ba.png)
4. Encounter the following error message "The selected email address is already in use by another user.*"

**What application are you using?**
Open Journal Systems 3.4.0.0

**Additional information**
List of current enrolled users:
![image](https://user-images.githubusercontent.com/50342731/222574943-6fbe752a-7b04-489e-87c2-0c2c51f2af10.png)

No issue with Journal Manager updating the email address via Users & Roles

**Comment by touhidurabir** [comment]
@asmecher PRs to review

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8740
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3810 [TEST ONLY]

**Comment by asmecher** [comment]
Merged, thanks, @touhidurabir!
