### ISSUE TITLE
Keywords and Supporting Agencies required but not appearing as required on the submission form

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#8716]
During 3.4 testing, I tested enabling metadata fields and making them required on the submission form. The Keywords field and Supporting Agencies fields were enabled and set as required, but they did not appear as required on the submission form.  All of the other fields appeared as required when configured to be so.

When I try to complete the submission, I'm told that the fields are required, but the fields are not marked as required on the form in the earlier steps.

1. In Workflow Settings > Metadata, configure Keywords and Support Agencies to be required
2. Make a new submission
3. See that they're not required

![FireShot Capture 278 - Workflow Settings - Demo Journal - ojs testing publicknowledgeproject org](https://user-images.githubusercontent.com/35044512/222586781-8b4d4eef-6672-43c1-8ed0-4e3e8a75a766.png)

![Screenshot 2023-03-02 at 17-06-27 Make a Submission Details Demo Journal](https://user-images.githubusercontent.com/35044512/222587127-06f2da2b-211e-45a5-ba72-e107512de67d.png)

**Comment by touhidurabir** [comment]
@NateWr PRs to review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8741
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3811 [TEST ONLY]

**Comment by NateWr** [comment]
Thanks @touhidurabir! Merged to `main`.
