### ISSUE TITLE
Unable to install plugins on 3.4.0

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#8723]
**Describe the bug**
It's not possible to install plugins through the file upload nor the plugin gallery.

The reason is that the `PharData` class is picky with the file extension (it might work on other SO/PHP combinations, it does work on my machine).

**What application are you using?**
OJS 3.4
PHP 8.0.18 (Dockerized Debian 10)

**PRs**
- https://github.com/pkp/pkp-lib/pull/8746
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3814

**Comment by jonasraoni** [comment]
If nobody take this issue, I can try to take a look, I was trying to help and couldn't simulate in my machine :)

**Comment by jonasraoni** [comment]
@asmecher PRs
- https://github.com/pkp/pkp-lib/pull/8746
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3814

**Comment by asmecher** [comment]
@pmangahis or @jonasraoni, can you describe the problem in more detail? Is this a problem introduced with 3.4.0, or is it sometimes also an issue with 3.3.0-x?

**Comment by jonasraoni** [comment]
It's on 3.4, the PharData fails to open an extensionless file... After adding the extension, everything works.
OJS 3.3 uses the system's tar to extract the plugin archive.

**Comment by jonasraoni** [comment]
Merged.

**Comment by asmecher** [comment]
@jonasraoni, this was a non-trivial amount of set of changes and I had it on my desk for investigation and review before merging. Sorry that's taking a while, but please wait for confirmation from the reviewer before merging!

**Comment by jonasraoni** [comment]
Oh sorry, I thought you just had those comments :)

**Comment by jonasraoni** [comment]
Let me know if you spot something else, then I can open an extra PR. For this PR I just wanted to use the `Flysystem` stuff, but it will probably need another separated PR (the current implementation is limited to accessing the `files_dir`, so some comments from that discussion that I had opened might be useful).
