### ISSUE TITLE
Cypress often hangs on failure, leading to Travis timeout

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8726]
Cypress often appears to hang after a failure, leading Travis to axe testing after 10 minutes of inactivity without the ability to inspect log files for information about the failure.

**Comment by asmecher** [comment]
This removes the "stop on first failure" work-around that we were using to avoid running tests after an early failure.

**Comment by jonasraoni** [comment]
@asmecher I've added PRs to cover `stable-3_3_0` and updated the `main` to output only the first/oldest screenshot (Travis interrupts the job once the output becomes too large):

- **`stable-3_3_0`**
- https://github.com/pkp/pkp-lib/pull/8877
- https://github.com/pkp/ojs/pull/3867
- https://github.com/pkp/omp/pull/1384
- https://github.com/pkp/ops/pull/508
- **`main`**
- https://github.com/pkp/ojs/pull/3868
- https://github.com/pkp/omp/pull/1385
- https://github.com/pkp/ops/pull/509

**Comment by asmecher** [comment]
All merged, thanks!
