### ISSUE TITLE
Multilingual rich text doesn't minimize after losing focus through tab

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8727]
**Describe the bug**
After navigating out of a multilingual rich text field, the focus goes to the next field, but the rich text is kept opened.

Also, when the rich text field receives focus, it's not brought into the viewport, which would be handy for me.

**To Reproduce**
1. Go to the last field of the set and press tab

**What application are you using?**
OMP 3.4

**Additional information**
![image](https://user-images.githubusercontent.com/361921/222888012-7ccefe8f-12e8-4b9e-8cb8-9cdef639e6b8.png)

**Comment by NateWr** [comment]
This is a long-standing UX issue that we don't plan to fix for the old forms. That will be fixed when the related UI uses the new forms.
