### ISSUE TITLE
Some labels at the UI are referring to simple elements instead of the field

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8729]
**Describe the bug**
When clicking on a field label, I expected the focus to go to the field.

**To Reproduce**
1. Access the Press > Categories
2. Click on the Name field: The focus doesn't work
3. Click on the Path field: The focus work

**What application are you using?**
OMP 3.4

**Additional information**
![image](https://user-images.githubusercontent.com/361921/222890573-8a166969-f032-4c41-ae29-f65d39194fdb.png)

**Comment by NateWr** [comment]
We don't plan to fix UX issues with the old forms.
