### ISSUE TITLE
The version.xml descriptor has invalid XML in OJS 2.4.7

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#873]
[See here](https://github.com/pkp/ojs/blob/ojs-stable-2_4_7/dbscripts/xml/version.xml)

**Comment by jalperin** [comment]
to be more precise: the `</patch>` has been removed from every line, apparently by commit [fe82b9ae8ef88](https://github.com/pkp/ojs/commit/fe82b9ae8ef884120a328af6231047f54b3bad3e)

**Comment by asmecher** [comment]
Hmm, that's a fubar in the automated build script's regular expression. I wonder why the automatic XML linting never caught this? Looking now.

**Comment by asmecher** [comment]
This was a problem with the validation testing script -- errors were being displayed but the  build wasn't failing. https://github.com/pkp/ojs/commit/9e22463d3687eaad0e8fd2ceecd3238cde305693#diff-354f30a63fb0907d4ad57269548329e3L42
