### ISSUE TITLE
Acron plugin missing localization

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8732]
**Describe the bug**
The acron is missing its localization text.

It's needed to synchronize the submodule to incorporate the latest updates to the localization.

**To Reproduce**
1. Go to Website > Plugins
2. Search for acron

**What application are you using?**
*/3.4

**Additional information**
![image](https://user-images.githubusercontent.com/361921/222946189-86390b74-b219-4ef3-a4f1-749c43710dde.png)

**PRs**
- https://github.com/pkp/ojs/pull/3815
- https://github.com/pkp/omp/pull/1357
- https://github.com/pkp/ops/pull/487

**Comment by asmecher** [comment]
@jonasraoni, is your check-out up to date? I renamed the locale files on Friday to suit the new convention.

**Comment by jonasraoni** [comment]
It was just missing the submodule update at OJS/OMP/OPS.
