### ISSUE TITLE
Warnings at the FileCache class

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8733]
**Describe the bug**
In order to have a clean log, the FileCache should probably be fixed while it's not replaced, just to decrease the noise at the log.

```php
PHP Warning:  chmod(): No such file or directory in /var/www/html/lib/pkp/classes/cache/FileCache.php on line 107
PHP Warning:  include(/var/www/html/cache/fc-pluginSettings-1-dataciteplugin.php): Failed to open stream: No such file or directory in /var/www/html/lib/pkp/classes/cache/FileCache.php on line 50
```

**PRs**
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3820
- https://github.com/pkp/pkp-lib/pull/8761

**Comment by jonasraoni** [comment]
@asmecher PRs
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3820
- https://github.com/pkp/pkp-lib/pull/8761

ps: I've noticed there's an issue with `null` at the cache, but as this code is going to be dropped, I didn't attempt to fix.

**Comment by asmecher** [comment]
Merged, thanks!
