### ISSUE TITLE
[OMP] Edit Chapter not showing content in tab Identifiers

### ISSUE THREAD

**Issue by franz-dev** [pkp/pkp-lib#8758]
**Describe the bug**
Once enabled and configured DOI plugin for chapters, when opening a publication to edit chapters the Identifiers tab isn't loaded properly.

**To Reproduce**
1. Enable and configure DOI plugin for chapters and monographs
2. Go to Submissions
3. Pick an active submission with chapters (View)
4. Go to main tab "Publication"
5. Go to "Chapters"
6. Click the chapter you want
7. Go to "Identifiers" tab
8. See error
![edit_chapter_identifiers](https://user-images.githubusercontent.com/72202910/223428684-0c03827d-4c22-41ac-a83e-b2380bb1e4fc.jpg)

**What application are you using?**
OMP 3.3.0.13

**Additional information**
- See screenshot
- I'm running php > 8.x with apache
- from error log i got this error : 
`Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www/omp/controllers/tab/pubIds/form/PublicIdentifiersForm.inc.php:37 ... `

**Comment by asmecher** [comment]
Merged https://github.com/pkp/omp/pull/1360, thanks! I'll also cherry-pick it back to `stable-3_3_0` for the next 3.3.0-x release.
