### ISSUE TITLE
[CitationStyleLanguage] Warning when changing the citation style

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8759]
**Describe the bug**
When changing the citation style a warning is generated:

```php
PHP Warning:  Undefined array key "issueId" in /var/www/html/plugins/generic/citationStyleLanguage/pages/CitationStyleLanguageHandler.php on line 162
```

**To Reproduce**
1. Enable the plugin
2. Access a submission
3. Change the citation style

**What application are you using?**
OJS 3.4.0rc1

**Comment by jonasraoni** [comment]
@asmecher PR
- https://github.com/pkp/citationStyleLanguage/pull/107

**Comment by asmecher** [comment]
Merged, thanks!
