### ISSUE TITLE
[CitationStyleLanguage] Fatal error when using the ACS style

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8760]
**Describe the bug**
When trying to view the citation using the ACS style, the request fails.

```php
PHP Fatal error:  Uncaught Error: Call to a member function render() on null in /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/CiteProc.php:137
Stack trace:
#0 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/CiteProc.php(183): Seboettg\CiteProc\CiteProc->bibliography(Object(Seboettg\CiteProc\Data\DataList))
#1 /var/www/html/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.php(601): Seboettg\CiteProc\CiteProc->render(Object(Seboettg\CiteProc\Data\DataList), 'bibliography')
#2 /var/www/html/plugins/generic/citationStyleLanguage/pages/CitationStyleLanguageHandler.php(80): APP\plugins\generic\citationStyleLanguage\CitationStyleLanguagePlugin->getCitation(Object(APP\core\Request), Object(APP\submission\Submission), 'acs-nano', Object(APP\issue\Issue), Object(APP\publication\Publication), NULL)
#3 [internal function]: APP\plugins\generic\citationStyleLanguage\pages\CitationStyleLanguageHandler->get(Array, Object(APP\core\Request))
#4 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#5 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(308): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#6 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#7 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#8 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#9 {main}
  thrown in /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/CiteProc.php on line 137
```

**To Reproduce**
1. Enable the plugin
2. Access a submission
3. Choose the `ACS` style at the `More Citation Formats`

**What application are you using?**
OJS 3.4.0rc1

**Comment by jonasraoni** [comment]
The https://github.com/citation-style-language/journals/blob/master/acs/_template.csl doesn't have the `<bibliography>` node.
Looks like the ["schema" supports the missing bibliography](https://github.com/citation-style-language/schema/blob/v1.0.1/csl.rnc#L68), then I guess it's an issue at the `seboettg/citeproc-php`.

I didn't create extra issues, I'll wait for confirmation.

**Comment by jonasraoni** [comment]
As a fast fix, I think we can disable this style for now 😁

I saw the https://github.com/citation-style-language/journals/ has a bunch of extra formats, is it worth to download/link them?!

**Comment by jonasraoni** [comment]
It works on OJS 3.3, because the `acs-nano.csl` is different (probably outdated), and includes the `bibliography` node.

**Comment by Vitaliy-1** [comment]
The `acs-nano` looks like a dependent style, metadata points that https://github.com/citation-style-language/styles/blob/master/american-chemical-society.csl is an independent parent style. As the latter is a generic one  we should stick to it.

**Comment by jonasraoni** [comment]
Thanks for the information @Vitaliy-1 🙃

@asmecher PR
- https://github.com/pkp/citationStyleLanguage/pull/108
