### ISSUE TITLE
[UI] Make participants grid more visible

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#877]
I'd recommend chucking it underneath the buttons on the right in the workflow, and leaving it up rather than having it as a fly-out. It may also make sense to not use the Category Grid, in order to save a bit of space, if we think there will only be 3-4 people assigned at any given stage.

This will also address a few issues with the participants grid mentioned in #604.

**Comment by asmecher** [comment]
How about if we keep it as a category grid, but don't present the category rows without entries?

**Comment by NateWr** [comment]
Sure. Is that possible with via CSS or does it involve touching the grid template files?

**Comment by asmecher** [comment]
It's something I'd do in PHP-land. I'll take care of it if you like -- it shouldn't collide with the rest of this issue.

**Comment by asmecher** [comment]
(Changed participants grid to exclude user groups that aren't active for the submission.)

**Comment by NateWr** [comment]
:+1:

**Comment by NateWr** [comment]
I'm going to chuck this under OMP 1.2 because, at the very least, we need to solve the focus bug. If you click Add Participant and the modal pops up, when closing the focus remains on the participants list which leaves the main content panel mostly out of view.

**Comment by asmecher** [comment]
Quirk with the current layout: when the workflow page is short, the participants grid gets crunched.
![scrunked](https://cloud.githubusercontent.com/assets/200411/12522545/304326e4-c106-11e5-9b18-47e70c7aab3b.png)

**Comment by NateWr** [comment]
Yeah this will be resolved when I get it chucked into a right-hand panel rather than using all the fancy positioning and slide-in stuff.

**Comment by NateWr** [comment]
Once the OMP PR tests pass I'll issue one for OJS.

https://github.com/pkp/omp/pull/201
https://github.com/pkp/omp/pull/202

Here's what it looks like now:

![participants-grid](https://cloud.githubusercontent.com/assets/2306629/12591691/f48c2caa-c460-11e5-8f36-3ecbfba1e42f.png)

**Comment by asmecher** [comment]
Looks good, Nate. Tweaked a few things (JS linting, etc) and superseded your pulls with...

https://github.com/pkp/pkp-lib/pull/1094
https://github.com/pkp/omp/pull/203
https://github.com/pkp/ojs/pull/724

Tests are ticking along so far (jinx) so will merge.

**Comment by asmecher** [comment]
All OK. Closing!

**Comment by asmecher** [comment]
@NateWr, one minor glitch: the dashboard now shows a bullet beside the "New Submission" button.

**Comment by NateWr** [comment]
Good catch! https://github.com/pkp/pkp-lib/pull/1103
