### ISSUE TITLE
Unify webFeed plugin code

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8770]
**Describe the bug**
Given the code of the webFeed plugin is almost the same for OMP/OPS/OJS, it makes sense to unify it.

It's probably ok to follow the lead of the `acron` plugin, and just move the code at `main` to a new repository.

The only difference is that the OJS one has the option below (displays only items available at the latest issue), I think it makes sense to remove it:
![image](https://user-images.githubusercontent.com/361921/224282140-3959ecfe-0229-4c41-9aa6-070004795e64.png)

**What application are you using?**
OJS 3.4

**PRs**
- https://github.com/pkp/webFeed/pull/1
- https://github.com/pkp/ojs/pull/3834
- https://github.com/pkp/omp/pull/1368
- https://github.com/pkp/ops/pull/493

**Comment by jonasraoni** [comment]
@asmecher
- I decided to leave the OJS only options (related to issues).
- There's a test at OJS/OMP/OPS and I didn't move it here, I can create another issue for that.

PRs
- https://github.com/pkp/webFeed/pull/1
- https://github.com/pkp/ojs/pull/3834
- https://github.com/pkp/omp/pull/1368
- https://github.com/pkp/ops/pull/493

**Comment by asmecher** [comment]
I'm not sure if you have time for this, and it's not crucial for 3.4.0, but best practice would be to move the tests in with the plugin as well.

**Comment by jonasraoni** [comment]
Is Travis configured to look for `.travis.yml` at every repository? If yes, I can try to copy a sample (it would be probably good to add one test for each application).

**Comment by asmecher** [comment]
Looks like you've already figured this out! https://app.travis-ci.com/github/pkp/webFeed/builds/261537623

**Comment by jonasraoni** [comment]
@asmecher Okay, the PRs are updated. I tried to use the datasets/tools to load some data into the applications, but curiously the `OPS/main` doesn't have a public folder 🤔

**Comment by asmecher** [comment]
@jonasraoni, I think the issue is that OPS was missing an `index.html` in the `public` directory -- I've added one for consistency with the other apps.

**Comment by asmecher** [comment]
Are the PRs in https://github.com/pkp/pkp-lib/issues/8770#issuecomment-1469588614 ready for another look?

**Comment by jonasraoni** [comment]
Yeah, I'm not planning to change anything besides the Travis script.

**Comment by asmecher** [comment]
OK, thanks; it looks good at a glance, so I'd say go ahead and merge when you're ready.

**Comment by jonasraoni** [comment]
@asmecher I don't have write permissions on this repository :)

**Comment by jonasraoni** [comment]
Linked PRs were merged.
