### ISSUE TITLE
[OJS] Review report is missing user name

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8777]
**Describe the bug**
The review report is missing the user name

```php
PHP Warning:  Undefined property: stdClass::$user_given in /var/www/html/plugins/reports/reviewReport/ReviewReportPlugin.inc.php on line 219
PHP Warning:  Undefined property: stdClass::$user_family in /var/www/html/plugins/reports/reviewReport/ReviewReportPlugin.inc.php on line 219
```

**To Reproduce**
1. Access the Reports
2. Click on the Reviews Report

**What application are you using?**
OJS 3.4.0rc1

**PRs**
- https://github.com/pkp/reviewReport/pull/47

**Comment by jonasraoni** [comment]
@asmecher PR
- https://github.com/pkp/reviewReport/pull/47

**Comment by asmecher** [comment]
Merged, thanks!
