### ISSUE TITLE
Submission incomplete filter using old matching criteria 

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#8779]
**Describe the bug**
The `incomplete` submission filter is retrieving any incomplete results. In the database, the submission status now uses strings to denote `submission_progress` e.g. "start" or "details." The `isIncomplete` filter is checking if the value of `submission_progress` is greater than zero:

https://github.com/pkp/pkp-lib/blob/f57afe846ec66cae416e14203ed3c1a37e6765b3/classes/submission/Collector.php#L321-L323

**To Reproduce**
1. Go to submissions page.
2. Filter submissions by incomplete.
3. See no results even when incomplete submissions are present.

**What application are you using?**
 OJS 3.4 RC 1

**Additional information**
N/A

**Comment by asmecher** [comment]
Fixed, thanks!
