### ISSUE TITLE
Link to email templates not visible when text string is untranslated

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#8781]
I don't know if this is exactly a bug, but I could see it presenting some big problems so I'll file it as a bug and you can recategorize it if you like. For 3.4 testing, I was doing the task "For less used languages - check that email templates appear translated." I changed the interface language to French, German, etc. and went to Workflow Settings > Emails to check the templates. However, I couldn't open the list of templates because the link to "Add and edit templates" is part of a string of text instead of a button, and when the text has not been translated, no link appears.  It just appears as an untranslated text string. 

![Workflow Settings - Email Templates - in French](https://user-images.githubusercontent.com/35044512/224457022-82650f38-a4bd-4fc9-9302-0183da797545.png)

I hope that folks will be using a fully translated site and always be able to access the link, but if not it could be very confusing that there is no link to view the email templates in Workflow Settings. We might get a lot of questions about what happened to the email templates and restoring the link by updating the translation would not be an easy process.

Could the link to the email templates be turned into a button, so it appears even when untranslated?

**Comment by NateWr** [comment]
I don't know any way around this, really. @asmecher any thoughts? The problem is that the link is in the translated string, like:

```
msgstr "This is some <a href="{$url}">text</a>."
```

**Comment by asmecher** [comment]
In practice the default locale plugin will help, but fundamentally it's hard to plan around the software working when a translation is incomplete. Sometimes it'll be more critical than others. I think we need to focus on the translation being completed.
