### ISSUE TITLE
Fatal error when creating institutional subscription with PHP 8.1.16

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8794]
**Describe the bug**
When trying to create an institutional subscription, a fatal error occurs because the `each()` function has been removed in PHP 8.0.0.

**To Reproduce**
1. Go to Settings > Distribution > Payments.
2. Enable payments and save the form.
3. Go to Payments > Subscription Types and create an institutional subscription type.
4. Go to Payments > Subscription Policies and enter a name/email address for the subscription contact.
5. Go to Payments > Institutional Subscriptions and click "Create New Subscription".
6. Try to create a subscription and click "Save"
7. See error

**What application are you using?**
`stable-3_3_0` (3.3.0-14)

**Additional information**
The error message:

```
PHP Fatal error:  Uncaught Error: Call to undefined function each() in classes/subscription/InstitutionalSubscriptionDAO.inc.php:623
Stack trace:
#0 classes/subscription/InstitutionalSubscriptionDAO.inc.php(252): InstitutionalSubscriptionDAO->_insertSubscriptionIPRanges('2', Array)
#1 controllers/grid/subscriptions/InstitutionalSubscriptionForm.inc.php(147): InstitutionalSubscriptionDAO->insertObject(Object(InstitutionalSubscription))
#2 controllers/grid/subscriptions/InstitutionalSubscriptionsGridHandler.inc.php(168): InstitutionalSubscriptionForm->execute()
#3 lib/pkp/classes/core/PKPRouter.inc.php(395): InstitutionalSubscriptionsGridHandler->updateSubscription(Array, Object(Request))
#4 lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)
#5 lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route(Object(Request))
#6 lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))
#7 index.php(68): PKPApplication->execute()
#8 {main}
  thrown in classes/subscription/InstitutionalSubscriptionDAO.inc.php on line 623
```

This code is 14 years old! :open_mouth:

**Comment by asmecher** [comment]
> This code is 14 years old!

If you want to make someone feel old, I think it was @mfelczak who originally wrote this :)

**Comment by mfelczak** [comment]
Back in the day, we just created the schema, classes, workflow, and UI. Today that'd make you a "full stack developer" but we just did it! :older-man-with-cane-and-raised-fist:
