### ISSUE TITLE
[OMP] Deleting a series deletes related publications

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8795]
**Describe the bug**
If you remove a series that have a submission assigned, the submission will lose its publication and disappear from the list of submissions.

⚠ It's definitely needed to check if other applications are affected, and probably review our foreign keys (we can add restrict rules or if to go cascade all the way down, then software locks must be placed at strategic points).

**To Reproduce**
1. Create a series
2. Assign a submission to it
3. Remove the series

**What application are you using?**
OMP 3.4.0rc1

**Comment by touhidurabir** [comment]
I believe the right behaviour for this is not to allow a series to get deleted if it has any submission associated with it like what we have for OJS(association of submission with section) . 

<img width="1591" alt="CleanShot 2023-03-14 at 17 41 26@2x" src="https://user-images.githubusercontent.com/2587979/224990845-8a13edf8-fe44-4fd4-adca-e6df4615f351.png">

**Comment by jonasraoni** [comment]
Yep, this is the behavior that I saw in another similar form, so I think it's ok to follow the pattern.

Something better would be to offer a new field, to allow the user select a "redirection" (e.g. move all submissions to section X before deleting this one).

**Comment by touhidurabir** [comment]
@asmecher PR to review

[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1367

**Comment by asmecher** [comment]
@touhidurabir, looks good, but can you also change the `ON DELETE CASCADE` condition on the foreign key to a set null? (See `classes/migration/install/OMPMigration.php` and `classes/migration/upgrade/v3_4_0/I6093_AddForeignKeys.php` where they set up the `publications_series_id` foreign key constraint.)

**Comment by touhidurabir** [comment]
@asmecher I have rebased the PR, should be good to merge .

**Comment by asmecher** [comment]
Merged, thanks!
