### ISSUE TITLE
[OMP] Long text breaking the viewport

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8796]
**Describe the bug**
Long texts without breaks are escaping from the viewport.
Also, it's not possible to know which format is being displayed until you select something else. Given the `More citation formats` makes it clear that other formats are available, maybe we just need to display the used format somewhere.

**To Reproduce**
The underlying image can be simulated by enabling the citation style plugin.

1. Enable the citation style plugin
2. Access a submission
3. Select any style that generates a URL (e.g. APA)

**What application are you using?**
OMP 3.4.0rc1

**Additional information**
![image](https://user-images.githubusercontent.com/361921/224687483-51a465f1-bf39-400d-ba62-6458a1212261.png)

**Comment by asmecher** [comment]
This is not a 3.4.0 regression, so moving past the 3.4.0 release.

**Comment by NateWr** [comment]
Please add the citation style you are using to the reproduction steps. Not all styles include the URL.

**Comment by jonasraoni** [comment]
I didn't select anything on the screenshot (I've just added an extra note to this issue about it), but basically all formats are displaying an URL for me, except the ACM and the ACS (not working on the test installation) :)

**Comment by NateWr** [comment]
Thanks for the report! Merged to `main`.
