### ISSUE TITLE
Category form doesn't store the cover image

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8798]
**Describe the bug**
After uploading a cover image to a category, it's data isn't stored at the database (only at the disk), from a user perspective it's like nothing changed.

⚠ As it's working on OJS 3.3.0, perhaps the database has been modified, which means, some migration might have to be done.

**To Reproduce**
1. Create/edit a category at the Context (Press/Journal/Server) > Categories
2. Upload a cover image

**What application are you using?**
OJS 3.4.0rc1

**PRs**
- https://github.com/pkp/pkp-lib/pull/8836
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3844

**Comment by jonasraoni** [comment]
@asmecher PRs
- https://github.com/pkp/pkp-lib/pull/8836
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3844

**Comment by asmecher** [comment]
Merged, thanks!
