### ISSUE TITLE
[OMP] Unable to export ONIX metadata

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8799]
**Describe the bug**
When trying to export a submission through the ONIX Monograph Export Plugin an error happens:

> The process failed. Check below for errors/warnings.
> Errors occured:
> Generic Items
> Cannot instantiate class. Class "MonographONIX30XmlFilter" is not declared in "plugins.importexport.onix30.filter.MonographONIX30XmlFilter".

**To Reproduce**
1. Go to Tools > ONIX 3.0 Monograph Export Plugin
2. Export any submission

**What application are you using?**
OMP 3.4.0rc1

**Comment by touhidurabir** [comment]
@jonasraoni can you still produce this issue . I am unable to re produce it.

**Comment by jonasraoni** [comment]
Yep, I can confirm it happens locally. I'm closing this issue, which will be solved as part of https://github.com/pkp/pkp-lib/issues/8800.
