### ISSUE TITLE
[OJS] New submission process does not show details page first when abstract is required. 

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8806]
**Describe the bug**
When creating a new submission, after filling up the start page details, it directly jumps to `Upload Files` instead of `Details` page even when `keywords` or `abstract` set as `required` . 

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure that submission keyword or abstract is set as required information to complete a submission. 
2. Now login as author .
3. Start a new submission, fill up the initial details and submit
4. See that the first page show is the `Upload Files` even when keywords/abstract is set as required.
5. At the final stage author will be prompt to fill the missing details and need to go back to `Details` page .

**What application are you using?**
 OJS 3.4.0 RC1

**Additional information**
The intended behaviour should be to show the `Details` view first if any of keywords/abstract is set as required .

**Comment by NateWr** [comment]
I was unable to produce this using a `main` dataset or using a `stable-3_3_0` dataset and upgrading to `main`. @touhidurabir, I think you probably have an outdated database. The `submissions.submission_progress` column should have a default of `start`. Here is what my database looks like (postgres):

```
                                                     Table "public.submissions"
         Column         |              Type              | Collation | Nullable |                      Default                       
------------------------+--------------------------------+-----------+----------+----------------------------------------------------
 submission_id          | bigint                         |           | not null | nextval('submissions_submission_id_seq'::regclass)
 context_id             | bigint                         |           | not null | 
 current_publication_id | bigint                         |           |          | 
 date_last_activity     | timestamp(0) without time zone |           |          | 
 date_submitted         | timestamp(0) without time zone |           |          | 
 last_modified          | timestamp(0) without time zone |           |          | 
 stage_id               | bigint                         |           | not null | '1'::bigint
 locale                 | character varying(14)          |           |          | 
 status                 | smallint                       |           | not null | '1'::smallint
 work_type              | smallint                       |           |          | '0'::smallint
 submission_progress    | character varying(50)          |           | not null | 'start'::character varying
```

The default is changed in the `I7191_SubmissionProgressType` migration. Can you double-check your database?

**Comment by touhidurabir** [comment]
> I think you probably have an outdated database.

@NateWr  you are right, the default for column `submission_progress` was set to `files` . sorry for the confusion .
