### ISSUE TITLE
Plugin installation doesn't cleanup temporary data properly

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8807]
**Describe the bug**
After attempting to install/upgrade a plugin, it always leave some cruft behind:
![image](https://user-images.githubusercontent.com/361921/224993527-13a8712d-e309-405c-91d3-ac88e4574f14.png)

**To Reproduce**
1. Install a plugin
2. Watch out the folder where it was extracted (at main `/temp`, at 3.3.0 "it depends")
3. See the temporary folders

**What application are you using?**
*

**PRs**
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3833
- https://github.com/pkp/pkp-lib/pull/8808

**Comment by jonasraoni** [comment]
@asmecher I just remembered of another issue at the plugin installation that I've seen in the wild, so I created this extra issue...
PRs
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3833
- https://github.com/pkp/pkp-lib/pull/8808

**Comment by asmecher** [comment]
Merged the pkp-lib PR; I'll take care of the app submodules separately.
