### ISSUE TITLE
[OJS] Incorrect notification signature

### ISSUE THREAD

**Issue by switowski** [pkp/pkp-lib#881]
Hi,

I just encountered the same error as described here:
https://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=8493
When a new article is created, the notification email is send but the signature is weird, because it contains:
contactName of the journal (so not the name of the author !)
signature of the author

So the e-mail that is send is a bit confusing. I tried to pinpoint where does this error come from and so far I have figured out that:
- the signature is set in `function MailTemplate` in `MailTemplate.inc.php` file - the signature is taken from the current user (from the request)
- the user name is set in `function assignParams` further in the same file and it's taken from `journal->getSetting('contactName')`, so it's not taken from the request.
I'm currently still on version 2.4.6.0 of OJS but I have compared this file with ojs-stable-2.4.7 branch and those functions are the same.
Does anyone have the same problem ? Any ideas how to fix it (or is it intended ?) ?

Best regards,
Sebastian

**Comment by asmecher** [comment]
Hi @switowski -- can you confirm...

- The signature at the end of the email
- The reply-to name and address
- The "from" name and address
- Which template you're seeing the text of ("You have a new notification from..." or "Thank you for submitting the manuscript, ...")

Feel free to anonymize these if you need; I just need to know which are appropriate and which are causing confusion.

**Comment by switowski** [comment]
Hi @asmecher,

sure, this is the whole email:
```
From: AAAAA <A@xxx>
Subject: [CC] New notification from NAME-OF-OJS-SYSTEM
Date: 16 juillet 2015 12:18:51 UTC+2
To: AAAAA <A@xxx>
Reply-To: BBBB <B@xxx>

The following message is being delivered on behalf of NAME-OF-JOURNAL.
________________________________________________________________________
You have a new notification from NAME-OF-OJS-SYSTEM:

A new article, "ARTICLE-NAME", has been submitted.

Link:
https://OJS-URL/index.php/JOURNAL-URL/author/submission/49

AAAAAAAAAA
SIGNATURE OF BBBBBBB
________________________________________________________________________
NAME-OF-JOURNAL
https://OJS-URL/index.php/JOURNAL-URL
```
Here, the AAAAA is the contactName of the journal and BBBBB is the person submitting the article.
I hope that helps.

**Comment by asmecher** [comment]
@switowski, can you try the patch attached to https://github.com/pkp/pkp-lib/pull/887 (applied in the lib/pkp subdirectory) and see if that corrects the problem?

**Comment by switowski** [comment]
@asmecher , yes that fixed the problem (no signature is better than a confusing one :)
Thank you very much for help !

**Comment by asmecher** [comment]
Thanks for confirming!
