### ISSUE TITLE
URN plugin setting form: failed ajax, invalid json

### ISSUE THREAD

**Issue by kirchnerf** [pkp/pkp-lib#8811]
**Describe the bug**
When trying to open the settings of the URN plugin in the websites' plugin manager, the following error message appears: "Failed Ajax request or invalid JSON returned".

The following entry appears in the Apache error log: "PHP Warning:  Declaration of URNSettingsForm::fetch($request) should be compatible with Form::fetch($request, $template = NULL, $display = false) in /srv/www/htdocs/ojs/plugins/pubIds/urn/classes/form/URNSettingsForm.inc.php on line 106"

**To Reproduce**
1. Go to Journal -> Website -> Plugins -> URN
2. Click on 'Settings'
3. See error

**What application are you using?**
 OJS version 3.3.0-14, PHP 7.4.33

**Comment by asmecher** [comment]
@kirchnerf, this can be fixed by applying this change: https://github.com/pkp/ojs/commit/975c55e05572f6e37aee487be31b3e8e2ba9415e
