### ISSUE TITLE
Citation Style Language plugin settings can't be accessed or modified

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#8817]
**Describe the bug**
After the CSL plugin is enabled, the plugin settings cannot be accessed or changed.

**To Reproduce**
1) Enable the CSL plugin via the Installed Plugins page
2) Click on the Settings link from the plugin pulldown

**What application are you using?**
OPS 3.4 RC1

**Additional information**
Error message: "Failed Ajax request or invalid JSON returned."

**Comment by jonasraoni** [comment]
Yep! So far there were 3 issues: https://github.com/pkp/pkp-lib/issues/8757 (about the plugin settings), https://github.com/pkp/pkp-lib/issues/8760, https://github.com/pkp/pkp-lib/issues/8759

I guess @asmecher will do a global submodule update later, there's a bunch of them that needs to be synchronized.
