### ISSUE TITLE
Submission review (step 5) error message displayed in unselected user UI locale

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#8818]
**Describe the bug**
1) When multiple locales are enabled, the error message in step 5 of the submission workflow is not displayed in the user's selected locale.
2) There is also an untranslated key: ##submission.copyright.description##

**To Reproduce**
1) Complete the submission process until step 5, but do not upload a submission file in step 2

**What application are you using?**
 OPS 3.4 RC1

**Additional information**
Screenshots below.

![Screen Shot 2023-03-15 at 7 01 09 PM](https://user-images.githubusercontent.com/200793/225462790-6cbf1e45-5b60-48db-8ef4-ec9bff7bc683.png)
![Screen Shot 2023-03-15 at 7 02 37 PM](https://user-images.githubusercontent.com/200793/225462812-66e790f8-8fdb-440b-9c1d-0ccf85609089.png)

**Comment by NateWr** [comment]
@mfelczak can you add the following to the reproduction steps:

1. What do you expect to see and how does this differ from what you actually see? (referring to specific text or elements in the screenshots) 
2. Any steps you took to set the locale the user is viewing the page in.
3. I don't see `##submission.copyright.description##` anywhere. Where does this occur?
4. What  has been set for the "Review and Submit" description under Settings > Workflow > Submission > Author Guidance in all languages.
5. What is the submission's primary language?

**Comment by mfelczak** [comment]
Hi @NateWr, please find some additional info below:

1) Expect the error message in the left hand column to be in English rather than Arabic.
2) No additional steps.
3) It was in the last section at the bottom of the step 5 page.
4) Screenshot below.
5) English.

![Screen Shot 2023-03-16 at 8 43 08 AM](https://user-images.githubusercontent.com/200793/225620623-e460ae5d-3a83-4301-8230-8333a2bc9272.png)

**Comment by NateWr** [comment]
It looks to me like the defaults have been installed for some languages but either not installed for english or they were removed. So it is falling back to Arabic as the first language it finds. I don't think this is reproducible with the `main` branch and the `main` dataset, so I think we need reproduction steps that get us to this state. For example, is there a database from which this install was upgraded that I could test an upgrade against? If it is a fresh 3.4 install, can you find reproduction steps that take us from installation of `main` to seeing this problem?

**Comment by NateWr** [comment]
Ok, I'll close this for now but if we find reproduction steps we can re-open it and have a look.
