### ISSUE TITLE
Category with a child subcategory missing link toggle in Categories grid

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#8819]
**Describe the bug**
After adding a child category, it should be possible to Edit or Remove the parent category, but the link options for these actions are missing from the category grid.

**To Reproduce**
1) Add a parent category
2) Add a child category

**What application are you using?**
OPS 3.4 RC 1

**Additional information**
In the screenshot below, Category A and Category B are parent categories. Category 1 is a child category under Category A.

![Screen Shot 2023-03-15 at 7 16 27 PM](https://user-images.githubusercontent.com/200793/225464828-2d1af682-b119-436e-bef1-9751d2235ec9.png)

**Comment by NateWr** [comment]
This is working as intended in the code.
