### ISSUE TITLE
[OMP] Not possible to edit nor delete a sales right and related forms

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8828]
**Describe the bug**
When trying to edit a sales right an alert with the message "Failed Ajax request or invalid JSON returned." pops out.
When trying to delete, nothing happens.

**To Reproduce**
1. Go to the publication tab of a submission
2. Access the publication formats
3. Expand one item and click on the edit
4. Go to the metadata tab of the popup
5. At the "Sales Rights" try to edit/delete one item

**What application are you using?**
- OMP 3.4.0rc1
- OMP 3.3.0

**PRs**
- **`main`**
- https://github.com/pkp/omp/pull/1374
- https://github.com/pkp/ojs/pull/3848
- **`stable-3_3_0`**
- https://github.com/pkp/omp/pull/1377
- https://github.com/pkp/ojs/pull/3851

**Comment by asmecher** [comment]
Looks good, thanks -- please go ahead. Yes, the return values from update / delete DAO functions have long been an inconsistency; it would be good to pin down a clear pattern for the EntityDAO and Eloquent-based replacements to those patterns.

While we're so late in the release process for 3.4.0, please don't add unnecessary extra clean-up; it's hard to keep up on code reviews, and it's entirely possible I'll let a regression sneak through!

**Comment by asmecher** [comment]
No objections; please go ahead.

**Comment by jonasraoni** [comment]
Merged linked PRs.
