### ISSUE TITLE
[OMP] Sales rights fields too squeezed

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8829]
**Describe the bug**
While accessing the sales right form, it's noticeable the fields to select the countries are a bit squeezed:
![image](https://user-images.githubusercontent.com/361921/226360425-62b02ce6-de47-42c3-8b54-6211f66dff52.png)

**To Reproduce**
1. Go to the publication tab of a submission
2. Access the publication formats
3. Expand one item and click on the edit
4. Go to the metadata tab of the popup
5. At the "Sales Rights" try to add/edit one item

**What application are you using?**
OMP 3.4.0rc1

**PRs**
- https://github.com/pkp/pkp-lib/pull/8833

**Comment by jonasraoni** [comment]
@asmecher PR
- https://github.com/pkp/pkp-lib/pull/8833

**Comment by asmecher** [comment]
Merged, thanks!
