### ISSUE TITLE
Fatal error when attempting to access Crossref/Datacite at Tools

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8838]
**Describe the bug**
When attempting to view the page `DataCite Export/Registration Plugin` or the `Crossref XML Export Plugin` at the Tools > Import/Export a fatal error happens.

```php
[22-Mar-2023 11:52:57 UTC] PHP Fatal error:  Uncaught Exception: DOI settings no longer managed via plugin settings form. in plugins/generic/datacite/DataciteExportPlugin.php:115
Stack trace:
#0 classes/plugins/PubObjectsExportPlugin.php(881): APP\plugins\generic\datacite\DataciteExportPlugin->getSettingsFormClassName()
#1 classes/plugins/PubObjectsExportPlugin.php(156): APP\plugins\PubObjectsExportPlugin->_instantiateSettingsForm(Object(APP\journal\Journal))
#2 classes/plugins/DOIPubIdExportPlugin.php(39): APP\plugins\PubObjectsExportPlugin->display(Array, Object(APP\core\Request))
#3 lib/pkp/pages/management/PKPToolsHandler.php(102): APP\plugins\DOIPubIdExportPlugin->display(Array, Object(APP\core\Request))
#4 [internal function]: PKP\pages\management\PKPToolsHandler->importexport(Array, Object(APP\core\Request))
#5 lib/pkp/classes/core/PKPRouter.php(333): call_user_func(Array, Array, Object(APP\core\Request))
#6 lib/pkp/classes/core/PKPPageRouter.php(280): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#7 lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#8 lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#9 index.php(21): PKP\core\PKPApplication->execute()
#10 {main}
  thrown in plugins/generic/datacite/DataciteExportPlugin.php on line 115
```

**To Reproduce**
1. Enable one of the plugins
2. Access the Tools > Import/Export
3. Access the plugin link

**What application are you using?**
OJS 3.4.0rc1

PRs:
- https://github.com/pkp/crossref-ojs/pull/34 (another crossref plugin fix)
- https://github.com/pkp/ojs/pull/3881
- https://github.com/pkp/ops/pull/517

**Comment by jonasraoni** [comment]
Both plugins are throwing an exception with a message like `DOI settings no longer managed via plugin settings form.`

If I allow the processing to continue, a message stating `Crossref XML Export Plugin
DOI management has moved. Please see the DOI management and DOI settings pages.` is displayed.

**Comment by bozana** [comment]
Hi @ewhanson, the PRs moved here :-) Could you please take a look at the PRs?

**Comment by ewhanson** [comment]
Hey @bozana, I've had a look, and it all looks good!
