### ISSUE TITLE
Permit X in ONIX-formatted ISSNs

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#884]
See http://forum.pkp.sfu.ca/t/bug-in-doi-medra-plugin/5070

**Comment by ctgraham** [comment]
We have a validator for this, no?
https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/classes/validation/ValidatorISSN.inc.php

**Comment by asmecher** [comment]
Yes, but this data model needs ONIX-formatted ISSNs, which have the hyphens stripped. This regexp is intended for formatting, not validation.

**Comment by ctgraham** [comment]
Ah, I guess I could read before commenting.

**Comment by asmecher** [comment]
No, then I'd have to start doing that.
