### ISSUE TITLE
Discussions: mail attached files alongside the content 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8854]
As part of the email refactoring for 3.3, instead of a generic notification about the new/updated discussion, participants receive an email containing the note's title and content. See https://github.com/pkp/pkp-lib/issues/6222 for more details.

Each message/note may contain an attached file - the new one or selected from a workflow. This file isn't mailed together with the content.

![dicussions](https://user-images.githubusercontent.com/20665587/228321482-b47354e0-a7af-4065-afb4-fa702e5e61b8.png)

Initially, discussions weren't designed to be mailed to participants. E.g., queries and attachments are managed by different grid handlers, the UI doesn't show available email template variables, the message itself can be edited.

Consider adding this feature separately or as a part of the discussions refactoring.

**Comment by Vitaliy-1** [comment]
@jonasraoni, do you have time to look at these small PRs to the stable and main branches?

**Comment by asmecher** [comment]
I jumped in on these to get them into `stable-3_4_0`. Merged both `pkp-lib` PRs, will handle the submodule updates separately. Thanks, @Vitaliy-1!

**Comment by asmecher** [comment]
@Vitaliy-1, this works for uploaded attachments, but not attachments that are chosen using the "Select Files" button. I've merged the existing PRs to `stable-3_4_0` and `main` already, so new PRs to fix this would be much appreciated!

**Comment by Vitaliy-1** [comment]
This should work. @asmecher, can you take a look?

**Comment by asmecher** [comment]
Merged, thanks!
