### ISSUE TITLE
[OJS] Updating the file of an issue galley ends up deleting it

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8856]
**Describe the bug**
When updating the file of an existing galley issue, the issue galley is removed.
The problem happens during the removal of the current file, due to the FK present at `issue_galleys.file_id`. Once the file is removed, the linked issue galley is lost as well.

- Solution 1:
  - Set the new `issue_galleys.file_id` before deleting the `issue_files` record.
  - Change the `ON DELETE` rule to `RESTRICT` to avoid accidents

- Solution 2:
  - Drop the `NOT NULL` from `issue_galleys.file_id`
  - Change the `ON DELETE` rule to `SET NULL`

**Notes**
- ⚠ Before the final release of 3.4.0 it's worth to review the cascading rules, at least the cases where a parent record references a child (e.g. `submission.current_publication_id`).
-  Given the solution #<wbr>2 might lead us to unexpected orphan data, I'm all for applying the solution #<wbr>1 to similar cases.
- `RESTRICT` everywhere is the safest option, but deleting every little bit manually isn't that great (bloated code), and at this point, not even feasible (massive work + error prone).

**To Reproduce**
1. Access an issue
2. Create an issue galley
3. Edit the recently created issue galley
4. Upload a new image

**What application are you using?**
OJS 3.4.0rc1

**Comment by asmecher** [comment]
Fixed; I grepped around for similar file upload cases but couldn't find any.
