### ISSUE TITLE
OPS: Submission final submit fails with unspecified error

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#8857]
**Describe the bug**
When trying to perform the final submission for an OPS new submission, the interface informs me of an error, which is not shown on the interface.

![image](https://user-images.githubusercontent.com/560456/228525644-c0c9269b-e3f4-4cca-ae88-3d8c027f03a5.png)

**To Reproduce**
1. Go to Dashboard > Submissions > New Submission
2. At "Files" step, add a file with type other than 'Preprint Text' type
3. Pass through the steps and finally try to submit the data. 
4. See the image above with the generic error, but no relevant error on any other form component

**What application are you using?**
OPS main branch

**Additional information**
Checking the `Validate` function of the Submission API, the error which does not seem to be available in the front end is `You must upload at least one Preprint Text file.`

**Comment by NateWr** [comment]
Merged to `main`.
