### ISSUE TITLE
Bootstrap3 theme needs locale directories to be updated to 2-letter syntax

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8862]
**Describe the bug**
The [bootstrap3 theme](https://github.com/pkp/bootstrap3) still uses the [old locale codes](https://github.com/pkp/bootstrap3/tree/main/locale) (`en_US`). This needs to be updated for 3.4.

@defstat I'll assign this to you because I believe you have a script you can run to fix it. If not, let me know and I'll reassign.

**What application are you using?**
`main` branch (3.4 pre-release)
-----------------
**PRs**
bootstrap3: pkp/bootstrap3#197

**Comment by defstat** [comment]
@NateWr do you want to check the PR found [here](https://github.com/pkp/pkp-lib/issues/8862#issue-1647208553)?

**Comment by NateWr** [comment]
Thanks @defstat!
