### ISSUE TITLE
Cosider affiliation element in DataCite XML export

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8865]
Consider creator's affiliation in the DataCite XML export.

**Additional information**
See https://support.datacite.org/docs/connecting-to-organizations and the schema: https://schema.datacite.org/meta/kernel-4.4/metadata.xsd.
Example:
```
<creator>
  <creatorName nameType="Personal">Garcia, Sofia</creatorName>
  <givenName>Sofia</givenName>
  <familyName>Garcia</familyName>
  <nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">0000-0001-5727-2427</nameIdentifier>
  <affiliation affiliationIdentifier="https://ror.org/03efmqc40" affiliationIdentifierScheme="ROR" SchemeURI="https://ror.org">Arizona State University</affiliation>
</creator>
```

**Comment by simonevecchi** [comment]
Did anybody proceed with this suggestion ?

**Comment by asmecher** [comment]
Fixed by https://github.com/pkp/ojs/pull/3932, thanks!

**Comment by bozana** [comment]
Yes, I forgot that -- because it is a plugin... I will add it in this issue: https://github.com/pkp/pkp-lib/issues/9068
