### ISSUE TITLE
Installing a plugin using commandline tool  exits   if email migration is included

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#8868]
**Describe the bug**

Cannot install the email templates of plugins using the 
`php  lib/pkp/tools/installPluginVersion.php `

**To Reproduce**

-  Download the orcidProfile Plugin to `$OJS/plugins/generic` e.g.  ` git clone https://github.com/pkp/orcidProfile`
- Execute inside  `$OJS`   folder the following command  `php  lib/pkp/tools/installPluginVersion.php plugins/generic/orcidProfile/version.xml`
- Result : `PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/html/ojs-main/lib/pkp/classes/plugins/Plugin.php on line 592`

**What application are you using?**
 OJS 3.4

**Additional information**

-  In Command-Line , the installer may not have any information about the Context including [locales](https://github.com/pkp/pkp-lib/blob/main/classes/plugins/Plugin.php#L592)

**Comment by asmecher** [comment]
@withanage, the `installPluginVersions.php` tool isn't intended to install email templates; that can only be done by uploading the plugin .tar.gz into the UI, or using the Plugin Gallery, or installing the system with the plugin present.
