### ISSUE TITLE
Add ability to login via Email

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8871]
**Describe the enhancement**
Current OJS/OMP/OPS system only allow login via username . As the username is not changeable and a lot of time set via JM/System admin, it's sometime become lot difficult for user to remember it . Allowing the login via user email can be considered a good solution as in the system of OJS/OMP/OPS, as both the username and email of a user is unique .

**What application are you using?**
 OJS, OMP or OPS version 3.4.0 

**Who is asking for it**
It's a feature that has been requested quite a few times in the PKP forum . 

**Additional information**
This will provide alternative solution for a regularly requested feature to allow the update of username . One challenge with username is that it's used as the salt for the password hashing and need some consideration to implement it . As updating email is allowed, it can provide an alternative approach for it . 

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9012 [TRANSLATION UPDATE ONLY] (merged)

#### main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8950 (merged)
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3886 [TEST ONLY]

#### stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9416
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4066 [TEST ONLY]

**Comment by jonasraoni** [comment]
There's a related discussion here: https://github.com/pkp/pkp-lib/discussions/7965

**Comment by asmecher** [comment]
Thanks, @touhidurabir -- I can't merge this for 3.4.0-0 as most of the translators have already completed their work and this would be a breaking change for them. Here's what I suggest:
- Let's leave the PRs for the feature addition for merge later, *but*...
- Please create and merge a PR that adds the new locale key to the English translation, so that translators will be prompted to add it for other translations in the meantime.

**Comment by ajnyga** [comment]
This is a very important new feature, thank you!

But do we actually need the username at all after this?

**Comment by asmecher** [comment]
Thanks! I've merged the translation PR and the rest can wait until a later 3.4.0-x.

**Comment by mfelczak** [comment]
Including a note here for review about user feedback for failed login attempts to ensure that the login form cannot be abused to confirm/deny users or their email addresses by unauthenticated site visitors. This is similar to https://github.com/pkp/pkp-lib/issues/9301

**Comment by asmecher** [comment]
@touhidurabir, I double-checked, and the translation change is in place for `stable-3_4_0` already. I did add [one comment](https://github.com/pkp/pkp-lib/pull/8950#discussion_r1349415101) to the PR, but otherwise I think this is ready to merge to `stable-3_4_0` and `main`.

**Comment by asmecher** [comment]
@touhidurabir, https://github.com/pkp/pkp-lib/pull/8950 looks good -- please go ahead with a back-port to `stable-3_4_0`.

**Comment by touhidurabir** [comment]
@asmecher PR for stable-3.4.0 is ready , check it at https://github.com/pkp/pkp-lib/issues/8871#issue-1651674902

**Comment by asmecher** [comment]
Merged -- thanks, @touhidurabir!

**Comment by ajnyga** [comment]
Great addition, this will most likely reduce a lot of "I can not log in" support tickets!
