### ISSUE TITLE
Fatal error in editing submission metadata on missing section

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#889]
Steps to reproduce:
* In OJS 2.4.7, navigate to a submission without a valid section assignment.
* Select "Summary"
* Select "Edit Metadata"
Expected result:
The form to edit the metadata
Actual result:
The form to edit the metadata, up until the fatal error when [checking the unset $section for abstract requirements](https://github.com/pkp/ojs/blob/973d391c76a073bc700b4cdc036da1ee8cbdfc3e/templates/submission/metadata/metadataEdit.tpl#L229).

Solution: warn user on missing section on the Summary page; check for unset object before using in form.

**Comment by asmecher** [comment]
This same problem will crop up in many other cases -- missing sections are a data error and we haven't checked for it. See https://github.com/pkp/pkp-lib/issues/255 for discussion. On the other hand, this change isn't major and will be helpful. @ctgraham, I don't see an open PR -- could you flag it here when it's ready?

**Comment by asmecher** [comment]
Sorry, I found it:
https://github.com/pkp/ojs/pull/669

**Comment by asmecher** [comment]
Thanks, @ctgraham!
