### ISSUE TITLE
UsageStats settings form enhancements

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#890]
Enhancements for the UsageStats plugin Settings form in OJS 2.4.7:
- [x] The Regex parsing for Access Logs should allow named parameters.  Currently, the order of parameters in the access log must be identical for all users.
- [x] The Data Privacy option should not depend on a config.inc.php entry.  The filename should be able to be provided directly in the interface.
- [x] The Data Privacy option, when enabled, should disable the city and region boxes in Optional Statistic Information.
- [x] The Optional Statistic Information should avoid throwing errors when no option is selected.
- [x] Form validation should be added, e.g. dependency of the Data Privacy option on the salt file, dependency of the optional "city" category on the "region" category.

**Comment by asmecher** [comment]
(Temporarily scheduling for 2.4.8 so it doesn't get lost.)

**Comment by bozana** [comment]
@asmecher, could you please explain why the salt file path should be in the config.inc.php ?

**Comment by asmecher** [comment]
Sorry, @bozana, I'm not following -- got a link to a commit or something?

**Comment by bozana** [comment]
@asmecher Hihihihi :-) I don't know exactly why did we put the salt file path in the config.inc.php and not in the plugin settings form, so I thought you could surely explain it better -- it concerns the second point from this issue... :-)

**Comment by ctgraham** [comment]
One potential reason for having an entry in config.inc.php would be if there is a distinction between a System Administrator who has access to the OS and file-level configuration, and a Site Administrator, who has access to the web configuration.

I'm having a hard time seeing that as a benefit here.

In general, I personally think most entries in config.inc.php belong in the UI instead.

**Comment by ctgraham** [comment]
@asmecher , so your concern is separating the configuration of items that would be changed in a OS or hardware change from items that would be OS independent?

I didn't like the concept of having a plugin setting that then needed to be manually entered in the config.inc.php, even if it is a filesystem location.  I think generally moving any settings into a UI improves the end-user experience.

@bozana, what is your preference here?

**Comment by bozana** [comment]
Unfortunately, I don't have any preference here :-( Originally I thought it would be easier to deal with the plug-in options only at one place i.e. only within the plug-in settings, but adding those two extra lines in the config.inc.php is not a problem. If there is no strong advantage of using the config.inc.php for this, I would say we could include it into the plug-in settings.

**Comment by beghelli** [comment]
I think that, since there is no way to use this plugin setting without touching the server itself, the option inside the config.inc.php file only helps to prevent users to change this and to expect some result without creating the proper location to the file.

**Comment by ctgraham** [comment]
@beghelli , are you saying that keeping the setting in config.inc.php forces a server-level interaction and better guarantees a proper change?  Or are you saying that moving the setting to the plugin better ensures a proper change because we can provide immediate feedback?

I think the second is true: we can validate the user's input in the plugin and provide immediate feedback if the file location is usable.

I'm not clear which direction you are recommending.

**Comment by beghelli** [comment]
sorry if I made myself unclear. I said that keeping the setting into the configuration file is an easy way to enforce that only system administrators will try to use that setting. Since they are going to need to create the file in the server, they can easily edit the configuration file.

**Comment by ctgraham** [comment]
Why force the sysadmin to manually create the file?  One of my proposed changes is to [automatically create the file if needed](https://github.com/ulsdevteam/ojs/commit/e809b7f554bc92ae7e10d951555a99555e0ac197#diff-8fa6ae6b02bb4af0936e0e2e94c6afdcR233).  This could even have a restrictive `umask` statement to ensure readability only to the web user, which might enhance the data privacy.

**Comment by beghelli** [comment]
My concern is just to avoid journal managers being able to change this, but I think that's a site plugin already, so journal managers can't manage it.

**Comment by ctgraham** [comment]
Correct.  This is a site level plugin.

**Comment by beghelli** [comment]
Thanks Clinton! Lots of improvements, as usual.
