### ISSUE TITLE
Unable to type in Title meta box for new installation of OMP3.4RC2

### ISSUE THREAD

**Issue by aabahishti** [pkp/pkp-lib#8900]
**Describe the bug**
After fresh installation of OMP3.4RC2, I tried to make a submission as an author but the Title field is not writable (nor clickable). I tried enabling all metadata from the workflow setting (also by disabling all metadata) but the Title field is not clickable and hence cant type in it.

**To Reproduce**
1. Create a press & series after a fresh installation of OMP 3.4 RC2.
2. Enable all required metadata under workflow settings (I also tried by disabling all metadata).
3. Initiate a New Submission (either from the admin account or from a separate author account)
4. The title box is not clickable and hence can't write the title.

**What application are you using?**
 OMP version 3.4 RC2

**Additional information**
![Untitled](https://user-images.githubusercontent.com/130147414/230594678-7e269605-35e8-4fff-97eb-6623249521e7.png)

I didn't find any logged error, screenshot is attached herewith.

**Comment by aabahishti** [comment]
Dear @NateWr 
On the other hand, while upgrading from OMP3.2.1.1 to OMP3.4.0RC2. I am getting the following error-
A database error has occurred: SQLSTATE[HY000]: General error: 1005 Can't create table `host_beta`.`submission_file_revisions` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `submission_file_revisions` add constraint `submission_file_revisions_submission_file_id_foreign` foreign key (`submission_file_id`) references `submission_files` (`submission_file_id`))

Thanks

**Comment by NateWr** [comment]
@aabahishti please report the database error in a separate issue.

**Comment by NateWr** [comment]
Thanks @aabahishti. There are a few similar reports. I'm going to close this one, but I'll continue investigating the problem at https://github.com/pkp/pkp-lib/issues/8901.
