### ISSUE TITLE
OMP3.4.0RC2 upgrade (from OMP3.2.1.1) error Foreign key constraint is incorrectly formed

### ISSUE THREAD

**Issue by aabahishti** [pkp/pkp-lib#8903]
Dear @NateWr 
While upgrading from OMP3.2.1.1 to OMP3.4.0RC2. I am getting the following error-
A database error has occurred: SQLSTATE[HY000]: General error: 1005 Can't create table `host_beta`.`submission_file_revisions` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `submission_file_revisions` add constraint `submission_file_revisions_submission_file_id_foreign` foreign key (`submission_file_id`) references `submission_files` (`submission_file_id`))

**What application are you using?**
 Trying to upgrade from OMP3.2.1.1 to OMP3.4.0RC2

**Additional information**
I also tried upgrading to OMP3_3_0-14 from OMP3.2.1.1 and got the same error as above.

**Comment by aabahishti** [comment]
Thank you @asmecher 
I applied above patch and upgraded from a fresh backup but the issue is still the same.
![Untitled](https://user-images.githubusercontent.com/130147414/231360505-fb7a5f42-7c2b-4b3f-a1cf-348a5e66d70f.png)

**Comment by asmecher** [comment]
Hi @aabahishti! Hmm, would it be possible to send me (privately!) a copy of your database?

**Comment by aabahishti** [comment]
Thank you @asmecher 
I am not sure how to send sql file privately here. I tried to send it through the PKP forum but was unable to upload it. Can you please let me know how can I send it (if through email, can I send it to your institutional email id in your GitHub profile or any other email id?)
![Untitled](https://user-images.githubusercontent.com/130147414/231655328-96a875a7-38ab-4f22-8d4e-7a3d50817c32.png)

**Comment by asmecher** [comment]
Thanks, @aabahishti!

The error is actually occurring during the OMP 3.2.1 to 3.3.0 process, not the 3.3.0 to 3.4.0 process. It's happening because your existing MySQL/MariaDB database tables use the MyISAM storage engine, but the default storage engine for new tables is InnoDB. It's not possible to mix storage engines in this way.

I would suggest converting your database to InnoDB before running the upgrade process.
