### ISSUE TITLE
Event discovery not working under Windows

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8905]
**Describe the bug**
The event discovery is failing on Windows due to path issues, therefore everything that depends on it doesn't work (e.g. jobs).

**To Reproduce**
1. Run `php .\lib\pkp\tools\events.php list`

**What application are you using?**
OJS 3.4.0rc2

**PRs**
- https://github.com/pkp/pkp-lib/pull/8907
- https://github.com/pkp/ojs/pull/3872

**Comment by asmecher** [comment]
@Vitaliy-1, could you review these?

**Comment by Vitaliy-1** [comment]
Thanks @jonasraoni for finding this!

I left a couple of comments. 
Looks good! I wish we could delegate the event discovery back to Laravel but the namespaces are defined differently in our case.

**Comment by jonasraoni** [comment]
Yeah, I'll take a look at the default Laravel implementation before merging, perhaps it's ok to use it now (if there aren't other dependencies) and just override this small piece.

**Comment by jonasraoni** [comment]
Merged.
