### ISSUE TITLE
Non-published submissions are being indexed

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8906]
**Describe the bug**
After unpublishing a submission, its search content will be removed, then re-indexed.

In my opinion even declined submissions should be indexed, for the sake of being searchable, but that would be subject for a new discussion/issue.

**To Reproduce**
1. Publish a submission
2. Unpublish the submission
3. Check the search tables (e.g. `SELECT * FROM submission_search_objects WHERE submission_id = SUBMISSION_ID`)

**What application are you using?**
OJS 3.4.0rc2

**PRs**
- https://github.com/pkp/pkp-lib/pull/8908
- https://github.com/pkp/ojs/pull/3873

**Comment by jonasraoni** [comment]
Hi @asmecher, I forgot to tag you here and on another issue 😅

PRs
- https://github.com/pkp/pkp-lib/pull/8908
- https://github.com/pkp/ojs/pull/3873

**Comment by asmecher** [comment]
Merged, thanks!
