### ISSUE TITLE
Journal Manager who is not Site Admin cannot change journal theme

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8909]
**Describe the bug**
Journal Managers who are not Site Administrators can't change the journal theme settings. They receive the message:

![image](https://user-images.githubusercontent.com/200411/231272992-844e5226-b00f-4c04-8daa-72a9a2e19d75.png)

**To Reproduce**
1. Log in as a Journal Manager who is not an Admin (e.g. `dbarnes` in the test dataset)
2. Go to Settings > Website > Appearance > Theme
3. Save the form

**What application are you using?**
OJS 3.3.0rc2

**Additional information**

This is caused by https://github.com/pkp/pkp-lib/pull/8610/files#diff-7c8f8752b8c8302fab60d70e7b5a0baea1944c323e9dbbb9468c391d9bb28f52R448.

**Comment by ewhanson** [comment]
Hey @asmecher, could you have a look at this? It was a quick, one line fix in `pkp-lib`. Thanks!

PRs:

- #8931
- pkp/ojs#3878
- pkp/omp#1393
- pkp/ops#516

**Comment by asmecher** [comment]
@ewhanson, a few lines up there's a hard requirement for `$requestContext` to be set; can you reconcile those two? https://github.com/pkp/pkp-lib/pull/8931/files#diff-7c8f8752b8c8302fab60d70e7b5a0baea1944c323e9dbbb9468c391d9bb28f52L439

**Comment by bozana** [comment]
@ewhanson, the 3.4 should come very soon, I think you solved this, so maybe to ping Alec to see it again, so that it can go into 3.4...

**Comment by asmecher** [comment]
Looks good to me; please go ahead!

**Comment by ewhanson** [comment]
Merged, thanks!
