### ISSUE TITLE
Normalize the database

### ISSUE THREAD

**Issue by Devika008** [pkp/pkp-lib#8914]
### Discussed in https://github.com/pkp/pkp-lib/discussions/7975

<div type='discussions-op-text'>

<sup>Originally posted by **jonasraoni** September 22, 2021</sup>
**Describe the problem you would like to solve**
Normalize the database in order to have better expectations (e.g. ensure a record is always identifiable by a single ID), improve the performance, decrease the amount of rows and also improve the data integrity.

**Describe the solution you'd like**
1. Add an `ID` field to all tables and discard composite primary keys.  https://github.com/pkp/pkp-lib/issues/3573

2. Move non-localized fields from the `*_settings` tables to their origin table (e.g. `user_settings` > `user`), I think we have few cases, I just remember of seeing an `issueId` somewhere.

3. Move dynamic localized fields from the `*_settings` tables to a better typed table
- The moved field will be strongly typed instead of just a string, which will speed up queries against it
- Simplify the queries (instead of having a join for each field or an extra query returning all the settings, a single join will make all the localized fields available)
- Allow for customized indexes in specific fields
- Easier to upgrade (renaming a field vs updating the `setting_name` for N rows)
- Less prone for leaving orphan data behind
- The `*_setting` table might be left (reserved for plugins) or removed  altogether (plugins will deal with their data directly).

4. Remove duplicated fields from dependent entities (e.g. remove the `review_round_files.stage_id` given that `stage_id` exists in its parent entity `review_rounds.stage_id`)

5. Replace the columns assoc_type/assoc_id by "real" columns with integrity checks.

**Who is asking for this feature?**
Developer

---

**Draft for the conversion process for the item 3**

Taking the `user_settings` as an example, where each user have at least two rows in the `user_settings` (one for the `givenName` and another for the `familyName`).

- Create a table `user_locale` (id int, **user_id int**, **locale varchar**, given_name varchar, family_name varchar, ...)`, with all the localized fields (unique key index on the bolded fields), this way we'll have 1 record for each locale + user.
- Update the queries to consider the new structure
- Create migration scripts

**Extra**
If we're going to keep the `*_settings` for something else, perhaps we can use the JSON aggregate functions to return the data instead of having it loaded in a loop.</div>

**Comment by asmecher** [comment]
Closing to avoid splitting the conversation between the issue and the discussion. Further work is welcome at the discussion link (https://github.com/pkp/pkp-lib/discussions/7975)!
