### ISSUE TITLE
Install Form displays old locales naming

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8917]
**Describe the bug**
Additional locales in Install Form  are displayed together with country code (alongside with the new naming pattern), e.g.: `Ukrainian (uk)`, `Ukrainian (Ukraine) (uk_UA)`
![install_form](https://user-images.githubusercontent.com/20665587/231876632-6cb774b5-a94b-46f9-8334-43ed3aaad113.png)

**To Reproduce**
1. Reproduced with the OJS dataset (main)
2. In the config set installed to off
3. See Additional locales, Primary locale and languages options

**What application are you using?**
 OJS 3.4

**Additional information**
Caching issue?

**Comment by asmecher** [comment]
@Vitaliy-1, do you have any repos (plugins) that still contain the old xx_YY locale codes? Even if a single plugin has one of these, it'll cause the duplicates.

**Comment by Vitaliy-1** [comment]
This folder likely redundant: https://github.com/pkp/pkp-lib/tree/main/locale/fi_FI

**Comment by asmecher** [comment]
Removed, thanks!
