### ISSUE TITLE
Cleanup Laravel cache

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8922]
**Describe the bug**
The Laravel cache is currently being stored at the folder `cache/opcache`, and it needs to be cleared, at least on these two key places:

- The installer has a [method to clear the cache](https://github.com/pkp/pkp-lib/blob/bfe1f50983092385531ed01cfc8a928ce76651c2/classes/install/Installer.php#L714), the Laravel cache must be cleared at this point to avoid complex issues (if possible, it would be great to investigate if this method is running before everything else).

- The administrative panel has a "Delete Data Caches" which also doesn't handle the Laravel cache.

- It's also needed to prune stale/expired cache from times to times (job).

**To Reproduce**
1. Access the Administration
2. Click on Delete Data Caches
3. Check if there are old files at the `cache/opcache` folder

**What application are you using?**
OJS 3.4.0rc2

**Comment by asmecher** [comment]
Thanks, @touhidurabir and @jonasraoni -- and agreed, the rest should be dealt with later as part of https://github.com/pkp/pkp-lib/issues/7111.

**Comment by jonasraoni** [comment]
Ok, I've updated the description and I'll drop a note on the other issue.
