### ISSUE TITLE
OMP3.4RC3 Submission Wizard Improvement Suggestion

### ISSUE THREAD

**Issue by aabahishti** [pkp/pkp-lib#8924]
**Describe the bug**
The first step of submission is for Details where the author can add chapters. Under the chapter detail form, the option for adding contributors and files is available but no contributor (except the submitting author) or file is available to select here. Also, no option to add these at this step is available.  
![1](https://user-images.githubusercontent.com/130147414/232397811-822d8d27-5e8c-4f5b-b9a3-94a1a7552286.png)
**Note:** above screenshot has been taken when making submissions through the editor account, if we use the author account then only submitting author is available under the add contributor option.

The files and contributors appear only after adding at the next steps (steps 2 & 3) and hence the selection option of these at step 1 looks confusing. 

I believe that either the First step for detail moved to be the Third step (after the contributor's step) or add a new feature so that the author can have options to add contributors and files directly from the chapter detail popup.

**To Reproduce**
1. Initiate New Submission
2. Add title and accept submission terms then click on "Begin Submission".
3. Scroll down to locate chapters grid and click on Add chapter
4. Scroll Down to see the "Add Contributors" and Files options which are empty. Only submitting authors can be included here, if need to add other contributors then move on to step 3 and return back again to select them.

**What application are you using?**
OMP3.4.0RC3

**Comment by asmecher** [comment]
@aabahishti, I think you're running into some kind of an error. Can you check your PHP error log and your browser console to see if either contains a message that might explain the blank contents?

**Comment by asmecher** [comment]
Closing for lack of feedback; @aabahishti, please feel free to add more details.
