### ISSUE TITLE
Cancelling revision upload removes the original file

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8933]
**Describe the bug**
From the forum: https://forum.pkp.sfu.ca/t/bug-when-canceling-file-revision-in-omp/77900
Related to file upload wizard in general. When uploading a new submission file revision, there is an option to cancel the upload. If the file is already uploaded, pressing `Cancel` button deletes also original file
![fileUploadWizard](https://user-images.githubusercontent.com/20665587/233077491-5770f872-64c1-4028-a256-6cfcb5b42311.png)

**To Reproduce**
1. Make s submission, upload a submission file
2. On the submission stage, under `Submission Files` click on `Upload File`
3. Select that this file is a revision of an existing submission file
4. Click on `Upload File` and select file from the system to upload
5. After upland press `Cancel` button
6. See that the original file is removed

**What application are you using?**
 OJS, OMP and OPS 3.4/stable 3.3.0

**Additional information**
When revision is uploaded it replaces the previous submission file: https://github.com/pkp/pkp-lib/blob/9c6f915b617069b1ee36b0038f3394655121f02c/controllers/wizard/fileUpload/form/SubmissionFilesUploadForm.php#L194. Create a new submission file instead?

Pressing `Cancel` triggers `deleteFile` operation on the correspondent submission file, which also removes both entries in `files` table, original and a new (revised) one

**Comment by Vitaliy-1** [comment]
The logic behind file revisions handling in the file upload wizard work as per documentation: 1) when a new revision is uploaded, new entry is added in the `files` table and the previous submission file is updated in the `submission_files` table; 2) During submissionFile removal all orphaned files not references in the `submission_files` are also removed, they are considered to be revisions, see: https://github.com/pkp/pkp-lib/blob/9c6f915b617069b1ee36b0038f3394655121f02c/classes/submissionFile/Repository.php#L492

The solution (considering the stage of the dev cycle) could be passing additional parameter to `PKPManageFileApiHandler::deleteFile()` from the old JS handler where the [post request](https://github.com/pkp/pkp-lib/blob/9c6f915b617069b1ee36b0038f3394655121f02c/js/controllers/wizard/fileUpload/FileUploadWizardHandler.js#L246) is made to cancel file upload, with the data from the original submissionFile so it could be restored

**Comment by Vitaliy-1** [comment]
@NateWr, can you take a look? According to my tests on cancelling file upload, this PR does the trick. Cancelling the wizard  updates the submission file, so it points to the original entry in the `files` table and the uploaded file is removed. 

Do I need additional steps to validate the data regarding original file when passing it to the new endpoint in `PKPManageFileApiHandler`?

**Comment by Vitaliy-1** [comment]
Watch out for: https://github.com/pkp/pkp-lib/issues/8389 as it also touches event log, either PR should be modified depending on what is merged first

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8941
OJS: https://github.com/pkp/ojs/pull/3883/files

**Comment by Vitaliy-1** [comment]
@NateWr, do you have time for a second round of review?
After the last time I've included here refactoring of the event log

**Comment by Vitaliy-1** [comment]
Reminder: 1) test migration for OMP before merging, 2) make a PR for OPS (hopefully, it doesn't contain any app-specific event log manipulations)

**Comment by Vitaliy-1** [comment]
Merged

**Comment by asmecher** [comment]
@Vitaliy-1, heads-up that the `is_translated` column is nullable on install in the `event_log` table but not nullable on upgrade. This was causing upgrade failures with PostgreSQL (see e.g. https://app.travis-ci.com/github/pkp/ops/builds/263527519). I'm not sure the column is actually supposed to be nullable but at least this gets the tests back to working (hopefully).

**Comment by Vitaliy-1** [comment]
Thanks! Forgot to revert changes on that line. Ideally, `isTranslated` column shouldn't be nullable or should be removed but I don't have enough information on how it was use before 3.0 release, so decided to leave it for now.
