### ISSUE TITLE
editorialContactName being set to author in stage notify form

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#8936]
**Describe the bug**
A hosted client reported that when using a custom template sent to an author by a  copyeditor, the author's name is being inserted in the editorialContactName variable used in the email template.  I took a look at `PKPStageParticipantNotifyForm` in 3.3 and it seems that the `$fromUser` variable is never used in the `sendMessage` method, and maybe the User the form is being sent to is used in place of the editor?  

The user sending the message is added here, from the `Request` object:

https://github.com/pkp/pkp-lib/blob/stable-3_3_0/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php#L152

But the `$user` being used for the editorialContactName variable is the user the form is being sent to:

https://github.com/pkp/pkp-lib/blob/stable-3_3_0/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php#L175

This is also the variable being used a bit further down in the $authorName variable.

I think that maybe because this form is used in a generic way and the form can send to a variety of users in different roles perhaps this variable needs to be specifically set by pulling the assigned editor on the stage and then using that instead?  

**What application are you using?**
OJS 3.3.0.12

**Comment by asmecher** [comment]
@jnugent, is it possible that the user is misunderstanding the purpose of the `{$editorialContactName}`? It's actually supposed to be the user *to whom* the message is being sent, not its sender. Have a look at the templates referring to `{$editorialContactName}` in https://github.com/pkp/ojs/blob/stable-3_3_0/locale/en_US/emails.po and you'll see what I mean.

**Comment by asmecher** [comment]
OK, thanks!
