### ISSUE TITLE
Web-based upgrade reports error message ("This script can only be executed from the command-line")

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8938]
**Describe the bug**
The upgrade script breaks when executed through the web browser: 
```
This script can only be executed from the command-line
```
This is caused by `classes/migration/upgrade/v3_4_0/I8508_ConvertCurrentLogFile.php`, which makes use of `PKP\cliTool\ConvertLogFile`, which is not intended for web-based invocation.

**To Reproduce**
1. Load an old database (e.g. `stable-3_3_0`)
2. Prepare the system for an upgrade
3. Set `Installed` to `Off` in `config.inc.php
4. Browse to the website
5. Click the link: 
   ![image](https://user-images.githubusercontent.com/200411/233744654-5b71ad5c-dfd2-452b-93b9-81133f04fc65.png)
6. Click the upgrade button.

**What application are you using?**
OJS 3.4.0RC3

PRs:
- https://github.com/pkp/pkp-lib/pull/8944
- https://github.com/pkp/ojs/pull/3885 (only submodule update)
- https://github.com/pkp/omp/pull/1397 (only submodule update)
- https://github.com/pkp/ops/pull/518 (only submodule update)

**Comment by asmecher** [comment]
@bozana, could you have a look at this one?

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR above? Thanks a lot!

**Comment by asmecher** [comment]
Looks good, @bozana, please go ahead!
