### ISSUE TITLE
Missing workflow diagram in OJS 3.3 or newer versions

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#8939]
**Describe the bug**
Till OJS 3.2 "/about/aboutThisPublishingSystem" drives to a page with a short explanation about OJS and a classic diagram (keep intact since OJS 2.x or probably 1.x).

In 3.3+ this diagram was removed.

A visual representation of the workflow is important for newcomers, but also to get a clear image about what the tool is doing.

I'm quite sure it was done because the diagram was obsolete and a graphic representations are difficult to translate and track with git tooling, but till we find a better way, I suggest create a SVG (that are standard and could be diff with git).

**What application are you using?**
 OJS, OMP or OPS version 3.3.0

**Additional information**
Old diagram example in context:
https://revistes.uab.cat/brumal/about/aboutThisPublishingSystem

And a couple of attempts that could be used as a starting point:
- OJS 2: https://publicacions.uab.cat/sites/default/files/documents/workflowojs-generic.png
- OJS 3: https://i.imgur.com/t9xkZzJ.jpg
- OMP 3: https://i.imgur.com/uZqudNn.png

All diagrams were published under free licenses, including the SVG sources.

**Comment by asmecher** [comment]
@marcbria, the removal was intentional; see https://github.com/pkp/pkp-lib/issues/5984. Feel free to follow up there if you think it was a mistake.

**Comment by marcbria** [comment]
Great... I missed the conversation. :-(
It's hard to keep an eye in the forum an other here.

It's ok to keep this thread to talk here about how to mantain and translate this image or is there a different issue talking about this?
