### ISSUE TITLE
Fix getPublishedSubmissions, getPublishedIssues and getArticleGalleys in DOIPubIdExportPlugin and PubObjectsExportPlugin

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8956]
The functions getPublishedSubmissions and getArticleGalleys in DOIPubIdExportPlugin and PubObjectsExportPlugin do not consider context when getting the objects, which is above all important when the functions are called from CLI.
The function getPublishedSubmissions in DOIPubIdExportPlugin does not consider if the DOI exist for a submission.
Also, the collectors' filter function could be used now.

PRs:
- https://github.com/pkp/ojs/pull/3890
- https://github.com/pkp/ops/pull/519

**Comment by bozana** [comment]
@ewhanson, could you please take a look at the PRs above?

**Comment by ewhanson** [comment]
Hey @bozana, I've taken a look and it looks good! I just had a few naming/style comments. Other than that, it looks ready to go. Was there nothing in OMP that needed to be updated in the same way?

**Comment by bozana** [comment]
Hi @ewhanson, I considered the comments, and rebased. Once the tests pass I will merge... Thanks a lot!
