### ISSUE TITLE
Load generic plugins for all contexts in the CLI tool construct

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8960]
Here https://github.com/pkp/pkp-lib/blob/main/classes/cliTool/CommandLineTool.php#L70 the generic plugins are loaded but without a context. However, the generic plugins register for Hooks only if they are enabled for a context. 
Load generic plugins here for all contexts, so they can register for Hooks and work fully/properly in any CLI too.

PRs:
- https://github.com/pkp/pkp-lib/pull/8961
- https://github.com/pkp/ojs/pull/3891 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you please take a look?

**Comment by asmecher** [comment]
Hmm, I was sure I gave the go-ahead for this already, but I don't see it now! Anyway, yes, please proceed.
