### ISSUE TITLE
Possibility for importexport plugins not to support CLI 

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8962]
Implement a possibility for importexport plugins not to have to support CLI (import/export).
The current case are DOIPubIdExportPlugins.

PRs:
- https://github.com/pkp/pkp-lib/pull/8963
- https://github.com/pkp/crossref-ojs/pull/36
- https://github.com/pkp/ojs/pull/3892
- https://github.com/pkp/crossref-ops/pull/29
- https://github.com/pkp/ops/pull/520

**Comment by bozana** [comment]
@asmecher, could you take a look at this one too?

**Comment by asmecher** [comment]
@bozana, just so I understand -- the 3.3.0-x CrossRef support did have CLI support, but the 3.4.0 one does not. Was the 3.3.0-x CLI support working? Do we know whether anyone was using it?

**Comment by bozana** [comment]
@asmecher, yes that is true -- 3.3.0-x CrossRef plugin did have CLI support and is was working. I do not know if anyone was using it :-(
Theoretically the CLI export and registration would work in 3.4 too, in the same way they work in 3.3, but differently then UI registration works now -- e.g. registration would be directly and not using the jobs. We would need to refactor the code at some point -- we still use lots of the old code in the background -- and latest then the CLI support would not work or needed to be re-implemented... So I thought to remove it now... :thinking:

**Comment by asmecher** [comment]
OK, let's go ahead and try this, and schedule the re-addition based on user feedback. Not my preferred process but given we're very close to releasing 3.4.0-0 it's OK!

**Comment by bozana** [comment]
Maybe to also double check with @mfelczak and @AhemNason: do you know of any user that registers Crossref DOIs using the CLI import/export tool?

**Comment by bozana** [comment]
hmmm... I think the CLI tool was above all useful for the case when an user imports a lot of articles with DOIs that would then need to be registered. CLI tool would help for the timeout not to happen. In the new implementation and for the same use case: There is a possibility to say that the DOIs should be registered automatically. Also there are bulk actions. The deposits will be divided into jobs, so that the timeout should not happen any more.
Thus, I think I will proceed and remove the CLI functionality now, and if a need for it appears (again) we can re-implement it...
