### ISSUE TITLE
OJS 3.4 Upgrade: Submission checklist pre-flight check failed on valid json array

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#8966]
**Describe the bug**
During an OJS 3.3 to OJS 3.4 test upgrade the upgrade process fails with the error message:

```
[A pre-flight check failed. The software was successfully upgraded to 3.3.9.9 but could not be upgraded further (to 3.4.0.0). Check and correct the error, then try again.]
ERROR: Upgrade failed: DB: A row with setting_name="submissionChecklist" found in table journal_settings without the expected setting_value. Expected an array encoded in JSON but found:

{"0":{"order":44,"content":"Der Beitrag passt in den Scope von <em>FQS<\/em>."},"3":{"order":46,"content":"Bitte nutzen Sie unser Template und stellen Sie sicher, dass die inhaltlichen, formalen, stilistischen und bibliografischen Anforderungen der Hinweise zur <a href=\"https:\/\/www.qualitative-research.net\/index.php\/fqs\/submission\/guidelines\" target=\"_blank\" >Manuskriptgestaltung<\/a> umgesetzt wurden."},"1":{"order":34,"content":"Der zur Einreichung vorgesehene Beitrag wurde noch nicht veröffentlicht und ist auch nicht zur Veröffentlichung an einem anderen Ort vorgesehen. Andernfalls nehmen Sie bitte <em>vor Einreichung<\/em> Kontakt zur <a href=\"mailto:fqs@qualitative-research.net\">Redaktion<\/a> aufnehmen. "},"10":{"order":35,"content":"Für Beiträge, die aus Qualifikationsarbeiten (z.B. Dissertation) entstanden sind, akzeptieren wir in aller Regel nur eine Einzelautor*innenschaft. Betreuer*innen können nach erfolgreicher Begutachtung in einer Danksagung gewürdigt werden."},"11":{"order":36,"content":"\"Selbstplagiate\" bitte prinzipiell vermeiden, indem Teile aus bereits veröffentlichten Texten korrekt zitiert werden."},"2":{"order":37,"content":"Rechte bzw. Lizenzen für alle im Beitrag verwandten Materialien, Abbildungen usw. liegen bei den Autor*innen bzw. müssen vor Publikation eingeholt und im Text entsprechend ausgewiesen werden."},"4":{"order":38,"content":"<em>Gender Bias<\/em> bitte prinzipiell vermeiden, siehe die APA-Empfehlungen zu <a href=\"https:\/\/apastyle.apa.org\/style-grammar-guidelines\/bias-free-language\" target=\"_blank\" rel=\"noopener\">Bias-Free Language<\/a>."},"5":{"order":39,"content":"In <em>FQS<\/em> bereits verfügbare Veröffentlichungen wurden systematisch berücksichtigt."},"7":{"order":40,"content":"Anthropomorphismen bitte prinzipiell vermeiden: Nicht Beiträge oder Studien arbeiten, fragen, forschen, beschreiben usw., sondern die Forschenden bzw. Autor*innen (APA 6, Abschnitt 3.09 \"Precision and Clarity\", S.69)."},"9":{"order":41,"content":"Bitte die Vergangenheitsform verwenden, wenn die Arbeit anderer Autor*innen besprochen wird (APA 6, 3.18 \"Verbs\", S.78)."},"8":{"order":42,"content":"Texte von Nicht-Muttersprachler*innen müssen vor Einreichung sorgfältig muttersprachlich geprüft worden sein."},"12":{"order":47,"content":"Im Falle multipler Autor*innenschaft bitte vollständige Metatdaten für jede einzelne Person bei Einreichung eingeben."}}
```

despite the fact that the json string is correctly fromated.

**To Reproduce**
1. Perform a 3.3 to 3.4 Upgrade with a custom submission checklist.

**What application are you using?**
 OJS 3.4

**Additional information**

The error originates in PreflightCheckMigration line 686. 

$checklist = json_decode($value);

returns the checklist as type stdClass

![grafik](https://user-images.githubusercontent.com/54445456/236809500-ca04e132-5704-4e3b-9b31-53e6dca38d71.png)

which does not validate as array in:

if (is_null($checklist) || !is_array($checklist)) {...}

I temporariliy "fixed" this by changing line 686 to:

$checklist = json_decode($value, true);

which obviously renders !is_array($checklist) useless ...

**Comment by touhidurabir** [comment]
PRs to review 
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8969
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3893 [TEST ONLY]

**Comment by simonevecchi** [comment]
hi i have the same error
A database error has occurred: Exception: A row with setting_name=“submissionChecklist” found in table journal_settings without the expected setting_value. Expected an array encoded in JSON but found: All submissions must meet the following requirements.

Do I have to make this change to solve it definitively?

" which does not validate as array in:
if (is_null($checklist) || !is_array($checklist)) {...}
I temporarily "fixed" this by changing line 686 to:
$checklist = json_decode($value, true);
which obviously renders !is_array($checklist) useless ..."

or are there other solution?

**Comment by asmecher** [comment]
@simonevecchi, this is a closed Github issue; please continue the conversation on [your forum thread](https://forum.pkp.sfu.ca/t/error-upgarding-to-ojs-version-3-4-0-0/79225/2). It's best if you don't cross-post.
