### ISSUE TITLE
[OMP] Adding representatives does not update the view for newly added data

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#8968]
**Describe the bug**
When adding the a representative for a submission , it does not update the grid view to list the newly added representative . But a hard refresh of page does show that it has stored properly and show in the list . This is confusing as initially seems that information is not added or stored .

**To Reproduce**
1. Go the `Marketing` tab of a submission and select `Representatives` option from left side
2. Select `Add Representative` and fill up the required information.
3. Save the form.
4. See that it does not show in the list of `Agents` or `Suppliers`
5. Do a hard refresh of page and see that now it's showing.

**What application are you using?**
OMP 3.4.0 rc2

**Additional information**
The following exception is thrown 
```
[08-May-2023 13:12:13 UTC] PHP Fatal error:  Uncaught AssertionError: assert($categoryElementId !== false) in /Users/abir/Sites/code/omp-main/lib/pkp/classes/controllers/grid/CategoryGridHandler.php:144
Stack trace:
#0 /Users/abir/Sites/code/omp-main/lib/pkp/classes/controllers/grid/CategoryGridHandler.php(144): assert(false, 'assert($categor...')
#1 /Users/abir/Sites/code/omp-main/lib/pkp/classes/controllers/grid/CategoryGridHandler.php(311): PKP\controllers\grid\CategoryGridHandler->getGridCategoryDataElements(Object(APP\core\Request), '1')
#2 /Users/abir/Sites/code/omp-main/lib/pkp/classes/controllers/grid/GridHandler.php(804): PKP\controllers\grid\CategoryGridHandler->getRowsSequence(Object(APP\core\Request))
#3 [internal function]: PKP\controllers\grid\GridHandler->fetchRow(Array, Object(APP\core\Request))
#4 /Users/abir/Sites/code/omp-main/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#5 /Users/abir/Sites/code/omp-main/lib/pkp/classes/core/PKPComponentRouter.php(292): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#6 /Users/abir/Sites/code/omp-main/lib/pkp/classes/core/Dispatcher.php(166): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#7 /Users/abir/Sites/code/omp-main/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#8 /Users/abir/Sites/code/omp-main/index.php(21): PKP\core\PKPApplication->execute()
#9 /Users/abir/.composer/vendor/laravel/valet/server.php(235): require('/Users/abir/Sit...')
#10 {main}
  thrown in /Users/abir/Sites/code/omp-main/lib/pkp/classes/controllers/grid/CategoryGridHandler.php on line 144
```

PRs:
Solution A:
- https://github.com/pkp/omp/pull/1411

Solution B:
- https://github.com/pkp/pkp-lib/pull/9036
- https://github.com/pkp/omp/pull/1413 (only submodule update)

**Comment by bozana** [comment]
hmmm... somehow I could not 'easily' figure out where is the problem... I will look further but maybe somebody else have an idea immediately?

**Comment by bozana** [comment]
@touhidurabir, the PR above should fix the issue. Could you take a look?

**Comment by touhidurabir** [comment]
@bozana above PR fix it . However tests are failing though it looks like it does not related to this PR .

**Comment by bozana** [comment]
Thanks @touhidurabir. I have just restarted the tests, and once they pass I will merge, if no objections...

**Comment by bozana** [comment]
@asmecher, could you please take a look at the changes under Solution B above? I think this is the actual fix, and the Solution A is only a way around. -- The representatives grid categories have categoryId 0 and 1, and categoryId 0 is skipped in those if statements (`if ($categoryId)`). Also CategoryGridHandler::getRowsSequence was wrong: getGridCategoryDataElements expects categoryElement as second parameter, and not categoryId.

**Comment by asmecher** [comment]
Thanks, I've merged Solution B. I know we have some long-standing issues with 0 IDs, but the whole grid toolset should be considered deprecated and I'd prefer not to make massive changes to it. The category grid stuff is not very widely used, though, so I'm OK with this fix. Thanks, both!
