### ISSUE TITLE
ThesisFeedPlugin is missing request type check

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#897]
See: http://forum.pkp.sfu.ca/t/custom-reports-generator-interface-not-loading/5113/2
Similar to: https://github.com/pkp/ojs/pull/606 for https://github.com/pkp/pkp-lib/issues/336

**Comment by asmecher** [comment]
Thanks, @ctgraham; merged and cherry-picked to `ojs-stable-2_4_7`.
