### ISSUE TITLE
[OJS 3.4 rc3] remarks on submission form

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#8972]
Hello,

These issues are from my post in the forum (https://forum.pkp.sfu.ca/t/test-of-ojs-v3-4-rc3/78354)

- I setup only 3 Components for an Article (in management/settings/workflow#submission/components) but when I submit a new submission, all default types are proposed ?
    In the best, if there is only 2 or 3 Components Types, it should be selective directly without a popup.

- I find that ergonomics for the multilingual form is not easy to use. Maybe some modifications could be made on submission metadata form especially in multi language support. the form is by default in submission language (French here): label of input are “Title” etc. and then when you click on the other language (English for my case), label is English for all input. I think that if we have multilingual support for submissions, label could be, even for default language, “Title ($name of language)” (true for all input)

- In same form, in languages other than submission language, input like Title are required (red star), but if you don’t fill it, there is no error.
Maybe we could remove red stars

- Always in submission form, with french as submission language and english for UI, in the contributor list, the English name of the author (I imagine if he registered in English) is shown. If you add a contributor, it’s the french version of the name of the new contributor that is shown. But at the end of the submission, when validating all inputs, there is an error as primary author has not fill french version (submission language) of his name, so author has to edit his contributor role to add french name. I think, in the contributors form for the current author, name should be “Fill french version of name” or something like that.

Thank you

**Comment by asmecher** [comment]
@forgive38, I've fixed the issue with removed components still being available for selection; the rest of the issues are language-related and we have it on our list to audit and fix this as a medium/high priority. The issues you've raised have already been noted as part of that, so I'll close this issue as fixed, thanks!
