### ISSUE TITLE
[OJS 3.4 rc3] email variable not replaced when assigning an editor

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#8973]
Hello,

As a Journal Manager, when I assign an editor and select template mail “Assign Editor”, which contains {$recipientName}, the sent email has the tag {$recipientName} replaced but not in the created discussion.

Thank you

**Comment by asmecher** [comment]
@Vitaliy-1, would you mind taking a look at this one?

**Comment by Vitaliy-1** [comment]
Thanks, @forgive38 

It looks like the information about the recipient (i.e. editor) is not available at the time of form initialization.
My initial thought was to retrieve this data based a [user chose](https://github.com/pkp/pkp-lib/blob/fb8cb9aef73f20b0393a0ec0e8db5c9ef56cf9a6/js/controllers/grid/users/stageParticipant/form/AddParticipantFormHandler.js#L38) and replace the variable in TinyMCE content.  But it looks like that it was handled with placeholders before and the fix should be addressed there, suspect this call is failing: https://github.com/pkp/pkp-lib/blob/fb8cb9aef73f20b0393a0ec0e8db5c9ef56cf9a6/controllers/grid/users/stageParticipant/StageParticipantGridHandler.php#L570

**Comment by Vitaliy-1** [comment]
PRs
ui-library: https://github.com/pkp/ui-library/pull/274
pkp-lib: https://github.com/pkp/pkp-lib/pull/9019
OJS: https://github.com/pkp/ojs/pull/3917

**Comment by Vitaliy-1** [comment]
While working on it I found other missing template variables and removed a template, which wasn't supported in 3.3 - it's likely from OJS 2+ with a functionality that doesn't exist

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1, I've reviewed and tested; the feature now works as expected, and I appreciate the additional clean-up! Please go ahead.
