### ISSUE TITLE
[OJS 3.4 rc3] error 404 with unsubscribe link in an email

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#8977]
Hello

In a local install, when I follow the unsubscribe link in a discussion email, “http://localhost:8000/index.php/publicknowledge/notification/unsubscribe?validate=&id=263” I get an error 404 .

Thanks

**Comment by asmecher** [comment]
@Vitaliy-1, could you have a look at this one? Possibly related to:
- https://github.com/pkp/pkp-lib/issues/7874
- https://github.com/pkp/pkp-lib/issues/5048

**Comment by asmecher** [comment]
I've been able to figure out the cause of this: the `api_key_secret` in `config.inc.php` was not set, causing the JWT authorization token to be generated empty.
