### ISSUE TITLE
[OJS-3.4rc3] Crossref XML Export Plugin not working in Tools, On click HTTP ERROR 500 appeared. 

### ISSUE THREAD

**Issue by shantanu198713** [pkp/pkp-lib#8978]
**OJS-3.4rc3
PHP-8.1.13**

Crossref XML Export Plugin not working in Tools. On clicking HTTP ERROR 500 appeared.

![crossref error](https://github.com/pkp/pkp-lib/assets/108086810/064359db-89fb-484b-a12e-a11a1c011aef)
![500 error](https://github.com/pkp/pkp-lib/assets/108086810/d19ab3b9-e3e3-4d9b-8d6e-9c7fffcc41bc)

**Error log**
`[10-May-2023 07:14:38 UTC] Exception: Plugin referral expected to inherit from ReferralPlugin, actual type NULL in F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php:202
Stack trace:
#0 F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php(218): PKP\plugins\PluginRegistry::_instantiatePlugin('generic', 'referral', 'ReferralPlugin')
#1 F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php(111): PKP\plugins\PluginRegistry::_loadFromDatabase('generic', NULL)
#2 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#3 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 F:\wamp64\www\ojs34rc3\index.php(21): PKP\core\PKPApplication->execute()
#5 {main}

[10-May-2023 07:14:38 UTC] Exception: Plugin coins expected to inherit from CoinsPlugin, actual type NULL in F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php:202
Stack trace:
#0 F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php(218): PKP\plugins\PluginRegistry::_instantiatePlugin('generic', 'coins', 'CoinsPlugin')
#1 F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php(111): PKP\plugins\PluginRegistry::_loadFromDatabase('generic', NULL)
#2 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#3 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 F:\wamp64\www\ojs34rc3\index.php(21): PKP\core\PKPApplication->execute()
#5 {main}

[10-May-2023 07:14:38 UTC] Exception: Plugin crossrefReferenceLinking expected to inherit from CrossrefReferenceLinkingPlugin, actual type NULL in F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php:202
Stack trace:
#0 F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php(218): PKP\plugins\PluginRegistry::_instantiatePlugin('generic', 'crossrefReferen...', 'CrossrefReferen...')
#1 F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php(111): PKP\plugins\PluginRegistry::_loadFromDatabase('generic', NULL)
#2 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#3 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 F:\wamp64\www\ojs34rc3\index.php(21): PKP\core\PKPApplication->execute()
#5 {main}

[10-May-2023 07:14:38 UTC] Exception: Plugin citations expected to inherit from CitationsPlugin, actual type NULL in F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php:202
Stack trace:
#0 F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php(218): PKP\plugins\PluginRegistry::_instantiatePlugin('generic', 'citations', 'CitationsPlugin')
#1 F:\wamp64\www\ojs34rc3\lib\pkp\classes\plugins\PluginRegistry.php(111): PKP\plugins\PluginRegistry::_loadFromDatabase('generic', NULL)
#2 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#3 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 F:\wamp64\www\ojs34rc3\index.php(21): PKP\core\PKPApplication->execute()
#5 {main}

[10-May-2023 07:14:38 UTC] PHP Fatal error:  Uncaught Exception: DOI settings no longer managed via plugin settings form. in F:\wamp64\www\ojs34rc3\plugins\generic\crossref\CrossrefExportPlugin.php:178
Stack trace:
#0 F:\wamp64\www\ojs34rc3\classes\plugins\PubObjectsExportPlugin.php(879): APP\plugins\generic\crossref\CrossrefExportPlugin->getSettingsFormClassName()
#1 F:\wamp64\www\ojs34rc3\classes\plugins\PubObjectsExportPlugin.php(154): APP\plugins\PubObjectsExportPlugin->_instantiateSettingsForm(Object(APP\journal\Journal))
#2 F:\wamp64\www\ojs34rc3\classes\plugins\DOIPubIdExportPlugin.php(39): APP\plugins\PubObjectsExportPlugin->display(Array, Object(APP\core\Request))
#3 F:\wamp64\www\ojs34rc3\lib\pkp\pages\management\PKPToolsHandler.php(102): APP\plugins\DOIPubIdExportPlugin->display(Array, Object(APP\core\Request))
#4 [internal function]: PKP\pages\management\PKPToolsHandler->importexport(Array, Object(APP\core\Request))
#5 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPRouter.php(333): call_user_func(Array, Array, Object(APP\core\Request))
#6 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPPageRouter.php(278): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#7 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\Dispatcher.php(165): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#8 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#9 F:\wamp64\www\ojs34rc3\index.php(21): PKP\core\PKPApplication->execute()
#10 {main}
  thrown in F:\wamp64\www\ojs34rc3\plugins\generic\crossref\CrossrefExportPlugin.php on line 178`

**Comment by jonasraoni** [comment]
Closing as duplicate of https://github.com/pkp/pkp-lib/issues/8838.

Once you update your installation with the latest release, it should be ok.

**Comment by orcalator** [comment]
Hi,

I had this plugin ver. 1.0.2.1 running on OJS 3.2.1-4 but it stopped working. Since i'm not able to do OJS upgrade to 3.3/3.4 right now is there any chance to make it work on 3.2 ver. ? Thx.

Regards.

**Comment by jonasraoni** [comment]
@orcalator We're not providing bug fixes for applications older than 3.3.0, even security issues are not covered, unless it's something exceptional (e.g. a problem blocking users from upgrading to newer versions).

Anyway, what's the error that you've got? If it's working on OJS 3.3, perhaps you can do a `diff` and try to fix by yourself. The code from 3.2 isn't very different from 3.3...

If the problem also happens on 3.3, then we can fix and you can try to copy the resolution 😁

**Comment by orcalator** [comment]
Hello @jonasraoni,

Thank you for reaching out. I'm getting this when i try to deposit article:

PHP Fatal error:  Uncaught Error: Call to undefined method PublicationDAO::getIdsBySetting() in /ojs-3.2.1-4/plugins/generic/crossrefReferenceLinking/CrossrefReferenceLinkingPlugin.inc.php:206\nStack trace:\n#0 /ojs-3.2.1-4/lib/pkp/classes/plugins/HookRegistry.inc.php(107): CrossrefReferenceLinkingPlugin->addCrossrefCitationsElements()

```
#1 /ojs-3.2.1-4/lib/pkp/classes/filter/Filter.inc.php(451): HookRegistry::call()
#2 /ojs-3.2.1-4/classes/plugins/PubObjectsExportPlugin.inc.php(366): Filter->execute()
#3 /ojs-3.2.1-4/plugins/importexport/crossref/CrossRefExportPlugin.inc.php(215): PubObjectsExportPlugin->exportXML()
#4 /ojs-3.2.1-4/classes/plugins/PubObjectsExportPlugin.inc.php(171): CrossRefExportPlugin->executeExportAction()
#5 /ojs-3.2.1-4/classes/plugins/DOIPubIdExportPlugin.inc.php(29): PubObjectsExportPlugin->display()
#6 /ojs-3.2.1-4/lib/pkp/pages/management/PKPToolsHandler in /ojs-3.2.1-4/plugins/generic/crossrefReferenceLinking/CrossrefReferenceLinkingPlugin.inc.php on line 206, referer: https://xxx.xxx.xx/ojs/index.php/xxx/management/importexport/plugin/CrossRefExportPlugin
```

Maybe i can do some fast fix if it is not too complicated? Thx.

Reagrds.

**Comment by bozana** [comment]
Hi @orcalator, unfortunately there is no support for the plugin CrossrefReferenceLinking for 3.2.x releases, thus you cannot use it with that release.
