### ISSUE TITLE
(OJS 3.4 rc3] UI : invite reviewers

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#8979]
Hello

- In the list of reviewers (when selecting a new reviewer), I think that the email address of the reviewer could be listed under the reviewer name, as it could help to detect old (and disabled) email addresses.

-  add reviewer modal is not the new select email form with the possibility of select language of the template. I think it is maybe the main place that this new form should be, because, often in our case, editor want to select the language in function of the reviewer.

- As a reviewer, I think I’d really prefer the new upload file form as in the submission form : just simply drag & drop file without open a modal with 3 steps ; upload file, change name and Finish step!

For our journals, it’s very difficult to find (good) reviewers, so make easier the reviewers job and the communication between editors and reviewers ( like add the ability to select email template language) should be very appreciate.

Thanks

**Comment by asmecher** [comment]
@forgive38, this is more of a feature request than a bug; could you add it here? https://forum.pkp.sfu.ca/c/feature-requests/8

**Comment by forgive38** [comment]
just to remember : already an issue for having the email address in reviewer list
pkp/pkp-lib#6580
