### ISSUE TITLE
[OJS]Strange behavior if journal url = rt

### ISSUE THREAD

**Issue by samueloph** [pkp/pkp-lib#898]
I just found out that if I create a new journal with its abbrev. "rt", giving urls like localhost/rt/manager, this journal won't work properly, I think this is happening because OJS already have a "rt" folder.

Maybe it could prevent users from making "rt" journals or identifying such cases to differentiate between the journal and the system folder.

**Comment by asmecher** [comment]
@samueloph, are you using mod_rewrite? If so, the problem is likely in those rules.

**Comment by samueloph** [comment]
oh god I forgot. Yeah i'm using it, so this isn't a OJS problem, I'm closing this.

Thanks and sorry.

**Comment by asmecher** [comment]
No worries!
