### ISSUE TITLE
[OJS 3.4 rc3] when taking a decision, all reviewers should be informed

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#8984]
Hello

a really good thing is the ability to inform reviewers when taking a decision, but only reviewer of the last round are shown, I think reviewers of all rounds who have responded should be shown.

Thanks

**Comment by asmecher** [comment]
@forgive38, this is more of a feature request than a bug report; we're handling those on the [support forum](https://forum.pkp.sfu.ca/c/feature-requests/8). Could you see if anything there speaks to this request, and if not, post a new one?

(See also: https://github.com/pkp/pkp-lib/issues/4284)
