### ISSUE TITLE
[OJS 3.4 rc3] submission status when you cancel copyediting 

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#8985]
One minor thing, when you “Cancel copyediting” after accept submission, the status go back in Review step but the status of the submission is still “submission accepted”.
Maybe status should be the status of the last round of review ?
 (in the activity log : “##{$editorName} has sent this submission back from the copyediting stage.##” )

Thank you

**Comment by touhidurabir** [comment]
@Vitaliy-1 PRs to review

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9013
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3913

@Vitaliy-1 we still need to finalise few key behaviour .First of all , should we allow the status to show as `Return back to review.` or what is the current status of that round before moved to Copy Editing stage . for example , if no reviewer was assigned to round before moved to copy editing and then return back to review, it can show `Waiting for reviewers to be assigned.` which actually points the current status of the round . 

Also if we want to add a new status for which we need a new local key, may be we should wait for `3.4.0-1` to get this merged as for `3.4.0` translations are done .

**Comment by Vitaliy-1** [comment]
> First of all , should we allow the status to show as Return back to review. or what is the current status of that round before moved to Copy Editing stage

Ideally, I believe we should show the status which was before the submission was moved to the next stage. Let's show `Returned back to review` if it can't be determined otherwise for now.  

> for example , if no reviewer was assigned to round before moved to copy editing and then return back to review, it can show Waiting for reviewers to be assigned

Yeah, as it's based on review assignments, it's possible.

> Also if we want to add a new status for which we need a new local key, may be we should wait for 3.4.0-1 to get this merged as for 3.4.0 translations are done

I think it's ok to introduce a new locale key here, it's better than leaving an incorrect status. 

Thanks, @touhidurabir for looking into this!

**Comment by Vitaliy-1** [comment]
Thanks, merged!
