### ISSUE TITLE
Google Analytics setting references "boolean instead of "bool"

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#899]
Typeo on:
https://github.com/pkp/ojs/blob/0a28c81dc409065d4495e28ce3b903d81db7d60c/plugins/generic/googleAnalytics/GoogleAnalyticsSettingsForm.inc.php#L110

Reported in:
http://forum.pkp.sfu.ca/t/google-analytics-plugin-db-error-ojs-2-4-7-1/5181

**Comment by asmecher** [comment]
Thanks -- merged and ported to `ojs-stable-2_4_7`. Doesn't apply to `master` (the plugin there needs re-syncing with current `ojs-dev-2_4` first).
