### ISSUE TITLE
Slim application error 

### ISSUE THREAD

**Issue by sayid-DB** [pkp/pkp-lib#8991]
I'm having issues making a submission on the ojs page.. Everytime I try to submit a paper I’m always seeing this slim application error. Have tried so many tricks and solutions online however, the problem still persist. kindly assist me in solving this issue..

**Comment by jonasraoni** [comment]
Hi @sayid-DB,

The issues in GitHub are reserved for well-defined technical problems. Please, post your problem in the forum: https://forum.pkp.sfu.ca/c/questions/5, our technical staff is also supporting users there. And when you post there, ensure you're sharing the OJS/PHP version and the error log.
