### ISSUE TITLE
Button to view/preview a submission leads to a 404 page for submissions imported through the Native XML plugin

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8992]
**Describe the bug**
After importing a submission, the view/preview button isn't linking to the right URL, after clicking on it, a 404 is displayed.

**To Reproduce**
1. Import a submission using the Native XML plugin
2. Access it through the dashboard
2. Click on view/preview

**What application are you using?**
OJS 3.4/main

**Additional information**
![image](https://github.com/pkp/pkp-lib/assets/361921/6511d13c-9411-43f7-bf25-0a148cdabade)

**Comment by bozana** [comment]
Crazy... I cannot reproduce this neither... :thinking:

**Comment by jonasraoni** [comment]
I can reproduce the issue with the `Preview` (if you try to view a non-published submission) on my local environment, but the `View` I just can reproduce in a test installation that we setup (perhaps there's "corrupted" data), I'll try to grab more information later :)

**Comment by bozana** [comment]
I cannot even reproduce the issue with `Preview` -- it works for me :-O

**Comment by jonasraoni** [comment]
I just checked this one and it's related to the Native XML plugin. I imported a submission and it ended up with an empty string in the `publications.url_path` field.

**Comment by jonasraoni** [comment]
This one got broken in 3.4. OJS 3.3 has such check in place `if ($currentPublication->getData('urlPath'))`, which will cover null/empty string, but fail with `0` 😅

As a `urlPath` with empty string might exist in older versions, it's required to fix the `Submission::getBestId()` (a `strlen()` check sounds fair).

**Comment by jonasraoni** [comment]
I found some places to fix, maybe it's worth to add a migration to set this field with null when it's empty (there's issues.url_path, publication.url_path, ...), as it's not possible to guarantee that no more cases exist...
I didn't see something in Laravel to setup database constraints (e.g. `is null or length(field) > 0`), so it's better to fix on the code side.

Also, the `url_path` has a standard/simple index on it, I **think** it was supposed to be an unique index... And if yes, then it should be a composed index (mixed with the context_id, but there isn't a context_id nearby in those tables 😅)

**Comment by jonasraoni** [comment]
Hmm, there's a URL validation to check if it's duplicated, but if I use `0`, it fails, i'll fix it as well.

**Comment by jonasraoni** [comment]
Well, I'll leave the validation, but it's a weak enforcement... I'll add a reminder in this discussion https://github.com/pkp/pkp-lib/discussions/8016
