### ISSUE TITLE
Fatal error creating new submission version after upgrade

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9005]
**Describe the bug**
After upgrading an installation from 3.3.0, creating a new submission version results in a fatal error:

```
Slim Application Error:
Type: Error
Message: Call to a member function getLocalizedData() on null
File: .../lib/pkp/api/v1/submissions/PKPSubmissionHandler.php
Line: 1026
```

This appears to be caused by a missing `VERSION_CREATED` email. This is created for new installations, but not on upgrades.

**Comment by asmecher** [comment]
@Vitaliy-1, I've gone ahead and committed these directly to `main`:

- https://github.com/pkp/ojs/commit/5dce702684afaeb19c647eb12e93b5f8e84a85fa
- https://github.com/pkp/omp/commit/39c8c463bd3460dfc666f680617212552bf86871
- https://github.com/pkp/ops/commit/daf3ff692987fc4a825373a6218030194a862fe4

...but can you have a quick double-check and make sure I haven't missed something?

**Comment by Vitaliy-1** [comment]
Thanks, it should be enough
