### ISSUE TITLE
Updating status in an unpublished version won't update the status on the posted preprint page

### ISSUE THREAD

**Issue by carolinatanigushi** [pkp/pkp-lib#9008]
**Describe the bug**
If you update the status in an unpublished version on OPS, it gets "stuck" on whatever status was set previously and doesn't update on the posted version. Any other status updates aren't registered on the posted version either.

**To Reproduce**
1. Go to a preprint with both a posted and an unposted version.
2. Update the preprint status on the unposted version.
3. Go to the posted preprint page.

**What application are you using?**
OPS version 3.3.0.14

EDIT: just adding a detail, when I say "status" I mean preprint relations.

**Comment by asmecher** [comment]
@carolinatanigushi, can you spell out specifically what you do when you update the preprint status?

**Comment by carolinatanigushi** [comment]
@asmecher, I changed the status as usual, selected the Relations button, selected the "preprint has been published..." option, added the DOI link and saved. However, I did it by mistake on the unpublished version of the preprint.

Once I realized this, I looked at the posted preprint on the public interface and noted the status hadn't changed so I tried updating the status on the posted version to no success.

Tried updating it again, unposting and re-posting the preprint to no success.

I was able to replicate the error on our testing site with another submission so it wasn't anything with that specific submission.

**Comment by asmecher** [comment]
@carolinatanigushi, sorry, I think I'm stuck visualizing the wrong thing when you say "changed the status". Can you post a screenshot of that specific part?

**Comment by carolinatanigushi** [comment]
Apologies, @asmecher. It's on the relations button:

![image](https://github.com/pkp/pkp-lib/assets/12699183/f75ba43f-884c-40b2-8914-7b4b02f73437)

**Comment by asmecher** [comment]
Thanks, @carolinatanigushi. If I get what you're describing correctly, I think it might be intentional -- the status is attached to the publication, and the published form represents the current publication. So if there's an unpublished publication with a different status than the currently published publication, the public-facing record won't show the unpublished data. Does that make sense?

**Comment by carolinatanigushi** [comment]
@asmecher I think the main issue here is that it also "breaks" the relations on the posted version and it gets stuck on whatever it previously was. The relations aren't isolated on each version of the preprint, if this makes sense.

**Comment by bozana** [comment]
Hmmm... With the latest code from the branch stable-3_3_0 I cannot reproduce it -- I can normally change the relation of any publication/version, posted and unposted...
I will try to test it exactly on the 3.3.0-14 release...

**Comment by bozana** [comment]
I have also tested it on the PKP OPS testdrive https://demo.publicknowledgeproject.org/ops/testdrive/index.php/publicknowledge/index and cannot reproduce it there neither...

**Comment by bozana** [comment]
Hmmm... I've just installed exactly 3.3.0-14 version and I still cannot reproduce it :-O
Could you tell me what error do you then see?

**Comment by bozana** [comment]
Hi @carolinatanigushi, sorry, I really do not understand what is happening. Could you please take a look at that preprint:  https://demo.publicknowledgeproject.org/ops/testdrive/index.php/publicknowledge/preprint/view/19. I could change the relation for the unpublished version and the relation for the first version is still there and displayed.

**Comment by carolinatanigushi** [comment]
Hi @bozana thank you for taking the time to look into this! We did notice this issue a couple of months ago, though we tried again and it updated just fine. Current theory is that it could've been some interference with a plugin that end up getting solves with plugin updates. Closing this now.

**Comment by bozana** [comment]
Hi @alexxxmendonca, on that web page I can select different preprint versions and I see different statuses for different versions. It seems the version 2 is published?
(I just cannot reproduce the problem described here...)

**Comment by alexxxmendonca** [comment]
Hi @bozana
You ara absolutely right. I think I made a confusion. I apologize! 

I'll pay extra attention next time so as to write a comment only when I'm positive about this problem (hopefully it won't happen again).
