### ISSUE TITLE
[OJS-3.4rc3] Clicking on my side added menu `HTTP ERROR 500` appeared.

### ISSUE THREAD

**Issue by shantanu198713** [pkp/pkp-lib#9015]
**OJS-3.4rc3
PHP-8.1.13
Error after upgrade (OJS3.3.0-14 to OJS3.4rc3)**

If I am clicking on the default menu item then it is working fine, but if I am clicking on my side added menu then `HTTP ERROR 500` appeared.

**Note:** Red circle menu was added from our side.

![error5](https://github.com/pkp/pkp-lib/assets/108086810/e303d677-b9b4-47a8-9db9-4da28ad805e6)
![500 error](https://github.com/pkp/pkp-lib/assets/108086810/13aca062-2392-4541-a931-1a1a94513840)

**Error log:**
`PHP Fatal error:  Uncaught TypeError: get_class_methods(): Argument #1 ($object_or_class) must be an object or a valid class name, string given in F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPPageRouter.php:253
Stack trace:
#0 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPPageRouter.php(253): get_class_methods('NavigationMenuI...')
#1 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\Dispatcher.php(165): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#2 F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#3 F:\wamp64\www\ojs34rc3\index.php(21): PKP\core\PKPApplication->execute()
#4 {main}
  thrown in F:\wamp64\www\ojs34rc3\lib\pkp\classes\core\PKPPageRouter.php on line 253`

**Comment by asmecher** [comment]
@shantanu198713, thanks for reporting! I've fixed this with the attached commit.
