### ISSUE TITLE
OJS 3.0b: Weird text in Plugin Gallery Dropdown Menu

### ISSUE THREAD

**Issue by nmpx** [pkp/pkp-lib#902]
(Yes, I am now using the github master, so all my issues should be current, I hope.)

In the Plugin Gallery Dropdown Menu, I'm seeing this text:

     ##plugins.categories.viewableFiles##

    ##plugins.categories.ImplicitAuth##

See screenshot below

![bug05](https://cloud.githubusercontent.com/assets/5183702/11248411/0b786bac-8def-11e5-9a9f-9d475df29184.png)

**Comment by asmecher** [comment]
@nmpx, can you check whether the following line exists in `locale/en_US/locale.xml`?

    <message key="plugins.categories.viewableFiles">Article Galley Plugins</message>

**Comment by nmpx** [comment]
Yes, that line is there.

**Comment by asmecher** [comment]
Hmm, maybe there are some outdated cache files? Try deleting `cache/*.php` from your install and see if that changes it.

**Comment by nmpx** [comment]
I just cleared the cache and it remains.

**Comment by asmecher** [comment]
Hi @nmpx,

Hmm, strange -- I haven't been able to duplicate that behavior here. Could you send me a database dump, and the URL (everything after the "index.php" part) that you're seeing this on?

**Comment by nmpx** [comment]
Sure. Here's the URL part: /test3/management/settings/website

and the database dump:

[xnmp_data-dump.txt](https://github.com/pkp/pkp-lib/files/44139/xnmp_data-dump.txt)

**Comment by asmecher** [comment]
Hmm, I still can't replicate this behavior. Just in case of a git problem, try...

    cd lib/pkp
    git checkout master
    git pull
    cd ../..
    git checkout master
    git pull

Then flush your cache:

    rm -f cache/*.php

Then try loading the page again.

**Comment by nmpx** [comment]
Did above and, yup, still there.

Um. I guess if you can't replicate it I'll close this for now since it might just be me.

Alternatively, I have this in a vagrant box and could export the machine and send that to you, if you think it'll help.

**Comment by asmecher** [comment]
@nmpx, yes, a Vagrant image would be helpful, thanks! I'll leave this open until we've figured that angle out.

**Comment by nmpx** [comment]
Ok! Here it is:

http//f.nmp.pw/nmpx-ojs3b-testing.box

Let me know if you have problems downloading it.

**Comment by asmecher** [comment]
Hi @nmpx -- I finally tracked this down. I was looking in the wrong place.
I've fixed it now: https://github.com/pkp/pkp-lib/commit/8245a43661805acac139c9ad804e00a10c7cd024

Thanks for your persistence!
