### ISSUE TITLE
OJS 3.0b3: Announcements not showing on front page and clicking 'Read More' results in 404 error

### ISSUE THREAD

**Issue by mxbees** [pkp/pkp-lib#903]
When turning on announcements, you get the header on the front page, however none of the announcements show up on the page. Not clear if it ought to be showing announcements, but it's peculiar. See screenshot.

Also, one the Announcements page, when you click a 'Read More' link, it results in a 404 error.

![bug06](https://cloud.githubusercontent.com/assets/5183702/11248786/164016c8-8df1-11e5-8ff9-b49efb053bed.png)

**Comment by asmecher** [comment]
@NateWr, I think you were working on this recently.

**Comment by NateWr** [comment]
@asmecher OJS is out-of-sync with a few of the recent frontend changes. Should get cleaned up once we polish off the OMP frontend.

**Comment by nmpx** [comment]
I grabbed the php errors for this, in case it is useful.
````
[Thu Nov 19 13:58:37.833045 2015] [:error] [pid 2545] [client 10.0.2.2:44516] PHP Warning:  Smarty error: unable to read resource: &quot;announcements/announcements.tpl&quot; in /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php on line 1094, referer: http://localhost:8080/index.php/test3/dashboard
[Thu Nov 19 13:58:47.505363 2015] [:error] [pid 2632] [client 10.0.2.2:44525] PHP Warning:  Smarty error: unable to read resource: &quot;announcements/announcements.tpl&quot; in /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php on line 1094, referer: http://localhost:8080/index.php/test3/dashboard
````

**Comment by asmecher** [comment]
This should already be resolved!
