### ISSUE TITLE
Pre-flight checks are conflicting with migration

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9034]
**Describe the bug**
The pre-flight migration has a check to protect against duplicated data after merging the locales. But this behavior is currently conflicting with a migration that's supposed to clear a known source of duplicated data (see: https://github.com/pkp/pkp-lib/issues/7167).

I see two ways to fix:
- <strong>A. Safest/easiest:</strong> Apply the fix from the other issue before the pre-flight check happens.</li>
- <strong>B. Proper fix:</strong> The pre-flight check should cover the exception (which will be fixed by the `I7167_RemoveDuplicatedUserSettingsAndDeprecatedFields`), and the `MergeLocalesMigration` should be executed after the fix is applied.

Given the pre-flight migration is already doing updates, I don't see a strong reason to go with B.

**To Reproduce**
1. Ensure your database has the issue covered by the referenced side-issue.
2. Try to upgrade to 3.4.0

**What application are you using?**
OJS 3.4.0rc3

**Additional information**
Source: https://github.com/pkp/pkp-lib/issues/8929

**Comment by asmecher** [comment]
All merged, thanks!
