### ISSUE TITLE
Exception at OJS migration while inserting a new journal setting

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9037]
**Describe the bug**
The migration `I7014_DoiMigration` is attempting to insert the setting `automaticDoiDeposit` twice, which fails with a integrity constraint violation.

The fix might be done with slightly updates to the code to insert only once or by replacing the `insert` with an `upsert`.

**What application are you using?**
OJS 3.4.0rc3

**Additional information**
Source: https://github.com/pkp/pkp-lib/issues/8929

**Comment by asmecher** [comment]
Merged, thanks!
