### ISSUE TITLE
Entities using the "schema" pattern don't need the setting_type field

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9040]
**Describe the bug**
The field setting_type can be dropped from entities using the new schema toolset. No cleanup is needed, just a migration to drop the field is enough.

It's better to leave this migration on the end, as at least one migration makes use of these fields.

**What application are you using?**
OJS 3.4.0rc3

**Comment by asmecher** [comment]
Thanks, @jonasraoni -- all merged!
