### ISSUE TITLE
Add fallback to retrieve the submissions.locale field from the publications.locale

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9041]
**Describe the bug**
The current pre-flight migration is interrupting the process when a `submissions.locale` is empty.
Due to an old bug, the `submissions.locale` could be empty, while the `publications.locale` was filled, so it makes sense to first check if we can retrieve a value from the publications.

**What application are you using?**
OJS 3.4.0rc3

**Comment by asmecher** [comment]
Merged, thanks!
