### ISSUE TITLE
Invalid foreign key relationship at the migration I6093_AddForeignKeys for OJS

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9042]
**Describe the bug**
The migration is connecting the `publications.primary_contact_id` to the field `users.user_id` instead of `authors.author_id`, even though the migration might work, it will lead to failures later on.

**What application are you using?**
OJS 3.4.0rc3

**Comment by asmecher** [comment]
One comment that needs attention: https://github.com/pkp/ojs/pull/3937/files#r1213773246

**Comment by asmecher** [comment]
This corrected the foreign key declaration but left the old `user_id`-based cleanup code in place. Fixed: https://github.com/pkp/ops/commit/6fa87146a98fb15ec4dc3d24541682557882a892 https://github.com/pkp/omp/commit/c433cdadd0f491495554a7f600c3c76d9ad94559 https://github.com/pkp/ojs/commit/fc77b03eefc4a94ad62b70368e36bf546162ddb2

**Comment by jonasraoni** [comment]
Nice catch, the automated code replaced this piece by `$this->cleanOptionalReference('publications', 'primary_contact_id', 'authors', 'author_id')`, anyway, I probably wouldn't see it :)
