### ISSUE TITLE
Consider galleys for DataCite export and deposit only if they are enabled in DOI settings

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9044]
DataCite plugin considers galleys for export and deposit no matter if the DOIs are assigned to them, i.e. if they are selected in the DOI settings.
Also, if DOIs are enabled for galleys, only galleys with an assigned DOI should be considered for the export and deposit.
Consider also that a galley can be a remote galley i.e. that there is no galley file.

PRs:
- https://github.com/pkp/ojs/pull/3926

**Comment by bozana** [comment]
@ewhanson, could you maybe take a look at the PR above?

**Comment by ewhanson** [comment]
Hey @bozana, everything looked good at first glance. 👍  

I was having a bit of trouble testing it locally, specifically with the `tar` step, specifically [DataciteExportPlugin.php, line #365](https://github.com/pkp/ojs/blob/dfe067744e7850a85c105e030ba5de89ad974739/plugins/generic/datacite/DataciteExportPlugin.php#L365): `$tarCommand .= ' --owner 0 --group 0 --';`. It's failing to create the tar.gz file, and when I run the exact command directly in the command line, I get the following output: `tar: Option --owner is not supported`. I'm guessing this is probably a tar on Mac issue, but thought I'd let you know. 

I'll try and take another look at it tomorrow.

**Comment by bozana** [comment]
Thanks a lot @ewhanson! I will then leave that tar option as it is for now -- because nobody has complained yet... :-)

**Comment by ewhanson** [comment]
Great! And yes, it should only ever be a problem if it is running on a mac. The options aren't supported by the default tar implementation on Mac, so one would need to install GNU Tar via homebrew. I did this, updated the line in the config file, and tested again. Everything worked as expected.
