### ISSUE TITLE
Inability to Properly Add and Display New Fields in PKPMetadataForm

### ISSUE THREAD

**Issue by henriquejsfj** [pkp/pkp-lib#9045]
**Describe the bug**
In PKP's lib application, the Submission Metadata Fields from the PKPMetadataForm are currently hard-coded across multiple files, thereby preventing a seamless addition of new fields. When a new field is added in FORM_METADATA, the added field doesn't render correctly.

When trying to visualize this new field in Submission Step 3, after invoking the 'Form::config::before' Hook, no custom fields are displayed. This is possibly because the hook is not getting called. It appears that this issue originates from the file lib/pkp/templates/submission/submissionMetadataFormFields.tpl. Here, we have an abundance of `if else` statements which are used to add the default metadata when enabled, fetched from lib/pkp/classes/submission/form/PKPSubmissionSubmitStep3Form.inc.php. However, this file only retrieves the default metadataFields, leaving me at a loss as to how to resolve this issue.

A similar issue arises on the `workflow/index/1234/4#publication/metadata` endpoint. The new field only gets added to this page if at least one default metadata field is enabled. If not, no fields are displayed and the 'Form::config::before' Hook isn't invoked. This seems to be caused by the file lib/pkp/pages/workflow/PKPWorkflowHandler.inc.php, which contains the following code:
```php
$metadataFields = ['coverage', 'disciplines', 'keywords', 'languages', 'rights', 'source', 'subjects', 'agencies', 'type'];
$metadataEnabled = false;
foreach ($metadataFields as $metadataField) {
	if ($submissionContext->getData($metadataField)) {
		$metadataEnabled = true;
		break;
	}
}
if ($metadataEnabled || in_array('publication', (array) $submissionContext->getData('enablePublisherId'))) {
```

That last one is an easy fix, I have done it and will submit a PR soon.

**To Reproduce**
1. Develop a plugin akin to the tutorial [examples-custom-field](https://docs.pkp.sfu.ca/dev/plugin-guide/3.3/en/examples-custom-field) and bind it to FORM_METADATA.
2. Implement the necessary schema changes.
3. Enable at least one metadata to observe it working on `workflow/index/1234/4#publication/metadata` endpoint.
4. Disable all default metadata to see no fields at `workflow/index/1234/4#publication/metadata` (endpoint like)
5. Create a new submission, but note that no new fields are added.

**What application are you using?**
 OJS version stable-3.3.0

<hr>

PRs:

 stable-3_3_0:
- https://github.com/pkp/pkp-lib/pull/9053
- https://github.com/pkp/ojs/pull/3945 (only submodule update)
- https://github.com/pkp/omp/pull/1422 (only submodule update)
- https://github.com/pkp/ops/pull/541 (only submodule update)

main:
- https://github.com/pkp/pkp-lib/pull/9078
- https://github.com/pkp/ojs/pull/3947 (only submodule update)
- https://github.com/pkp/omp/pull/1424 (only submodule update)
- https://github.com/pkp/ops/pull/542 (only submodule update)

stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/9117
- https://github.com/pkp/ojs/pull/3955 (only submodule update)
- https://github.com/pkp/omp/pull/1426 (only submodule update)
- https://github.com/pkp/ops/pull/544 (only submodule update)

**Comment by henriquejsfj** [comment]
@asmecher I guess the plugin is properly registered. I was able to debug see my callbacks being called and the new fields added to the workflow page. One of the problems is that the submission forms treat the metadata fields as a fixed array `['coverage', 'disciplines', 'keywords', 'languages', 'rights', 'source', 'subjects', 'agencies', 'type'];`. Other problem is on metadata tab from the workflow where only display my field if there is at least one metadata enabled.

**Comment by asmecher** [comment]
Thanks, @henriquejsfj! @bozana, could you review the attached PR?

**Comment by henriquejsfj** [comment]
I found out that the Author Dashboard has the same issue, I fixed it on the last commit.

**Comment by bozana** [comment]
Hi @henriquejsfj, could you maybe post the link to your plugin here?
If you would like to add a form field to the submission form in step 3, you would probably need to use that form's hooks ('submissionsubmitstep3form::...').
Using the FORM_METADATA would add the fields in the submission production stage > metadata form.
You could also maybe take a look at the orcidProfile plugin (https://github.com/withanage/orcidProfile/blob/stable-3_3_0/OrcidProfilePlugin.inc.php), ror plugin (https://github.com/withanage/ror/blob/master/RORPlugin.php), vgWort plugin (https://github.com/ojsde/vgWort/blob/ojs-stable-3_1_2/VGWortPlugin.inc.php) -- as an example how they extend such a form. Unfortunately, I cannot find an appropriate form for exactly that submissionsubmitstep3form as an example...
If you post you plugin link here, maybe I can help... Although that would maybe be more appropriate for the forum than here, but because you have already opened the issue... lets continue here now...

**Comment by henriquejsfj** [comment]
@bozana Thanks for the reply. I understand what you are saying, I was using those form hooks ('submissionsubmitstep3form::...') to get things working. 

However, I find this approach to be a bit of a workaround rather than a robust solution. Essentially, I'm not setting the metadata as I ideally would, but rather adding a field on the page to capture the data, and subsequently retrieve it later. This approach creates additional challenges when extending it to the Workflow and AuthorDashboard pages. In these cases, I'd need to add the fields again, which could lead to duplicated code and challenges in managing templates for the fields.

PKP already provides the Field functionality for adding to a Form. This theoretically should enable me to add the field in one place and have it correctly rendered (e.g., select-box, date-picker, text, etc.), and also store the data when needed.

> Using the FORM_METADATA would add the fields in the submission production stage > metadata form.

Perhaps I misunderstood something, but the current approach seems inconsistent with PKP's architecture. Rather than restricting the FORM_METADATA use to the submission production stage, wouldn't it be more flexible and coherent to use it in the `submissionsubmitstep3form`? This could potentially replace the need to retrieve an array from `Application::getMetadataFields()` and maintain a separate template for each field.

From what I understand, adding a Field to other Forms maintains consistency across the board. Is there a particular reason this wouldn't be feasible for `submissionsubmitstep3form`?

Thanks for suggesting the orcidProfile plugin (https://github.com/withanage/orcidProfile/blob/stable-3_3_0/OrcidProfilePlugin.inc.php) - I've been referring to this as a guide throughout the process.

Apologies for any confusion caused earlier, and I hope my explanation is clearer now. If the approach I've outlined above is not feasible for some reason, perhaps we could focus this issue on addressing the problems I've already fixed, particularly those related to displaying the metadata field on the Workflow and Author Dashboard pages.

Thanks again for your time and support!

**Comment by bozana** [comment]
Hi @henriquejsfj, we improve and refactor the code gradually -- we are not able to always consider everything related at once. I think this is also such a case -- earlier there was only the possibility to use those `form::...` hooks, but then we gradually re-implemented some forms using other structures/concepts, thus we currently have both in the system. Slowly we will go through the other parts of the system... And the forms are just one aspect of it, we have many others to consider too... :-)
I took a look at your PR and suggested just a small further change. Else, all well. It would be great if you could do that as well, else, I can do it. I can then merge and port it to the main branch...
Thanks a lot!

**Comment by bozana** [comment]
Hi @henriquejsfj, when porting the changes to the main branch, I saw that the form refactoring for submitting a submission is done -- now there is a new submission wizard and a new form that extends PKPMetadataForm that can be then used in the same way as PKPMetadataForm by a plugin i.e. no submissionstep4form::... hooks any more :-) Well, then there are a few new things to consider, but... :-)
