### ISSUE TITLE
Use of nonexistent variables on the PreflightCheckMigration

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9047]
**Describe the bug**
The variables `$localeCode` and `$defaultLocale` do not exist when this line gets executed:

https://github.com/pkp/pkp-lib/blob/181f09dabe1ef3458744277eaabd31914ba3b064/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php#L74

**What application are you using?**
OJS 3.4.0rc3

-------------------
PR

**Branch `main`**
PKP-LIB: #9059

**Comment by asmecher** [comment]
@defstat, could you resolve this? It was introduced with https://github.com/pkp/pkp-lib/commit/35012e8a185db6f1b85148a64ffcb0a6a526692e#diff-f85a73b74ff2f18598c46a3870bd2f3baba3691ed41083b7674166199ff17614.

**Comment by defstat** [comment]
@asmecher @jonasraoni I have added a PR [here](https://github.com/pkp/pkp-lib/issues/9047#issue-1735593837).

**Comment by asmecher** [comment]
Thanks, all!
