### ISSUE TITLE
OJS 3.0b: Deleting Journal Error

### ISSUE THREAD

**Issue by nmpx** [pkp/pkp-lib#905]
When deleting journals, once you hit 'ok', nothing happens. However, after you refresh the page, you see that the journal's associated data has been deleted, but not the journal itself. Renamed to 'untitled'.

See screencast: https://youtu.be/l9trNfoYgEY

From the error log: 

````
[Wed Nov 18 20:07:03.914910 2015] [:error] [pid 538] [client 10.0.2.2:35938] ojs2: Unrecognized DAO RTDAO!, referer: http://localhost:8080/index.php/index/admin/contexts

[Wed Nov 18 20:07:26.004452 2015] [:error] [pid 1390] [client 10.0.2.2:35947] ojs2: Unrecognized DAO RTDAO!, referer: http://localhost:8080/index.php/test1/admin/contexts?openWizard=1
```

**Comment by asmecher** [comment]
Thanks, @nmpx -- I've committed a change that should fix this.

**Comment by nmpx** [comment]
The change works and delete journals functions as expected.

**Comment by asmecher** [comment]
Great, thanks!
