### ISSUE TITLE
OJS 3.3 to 3.4 Upgrade fails with "Table 'failed_jobs' already exists"

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#9055]
**Describe the bug**
When running an upgrade from OJS 3.3.0-14 to 3.4rc2 (main branch as of 1.6.2023) the upgrade scripts fails with: 

```
2023-06-01 16:23:38 [migration: PKP\migration\upgrade\v3_4_0\FailedJobsMigration]
2023-06-01 16:23:38 [revert migration: APP\migration\upgrade\v3_4_0\MergeLocalesMigration]
2023-06-01 16:23:38 [downgrade for "APP\migration\upgrade\v3_4_0\MergeLocalesMigration" unsupported: Downgrade not supported]
ERROR: Upgrade failed: DB: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'failed_jobs' already exists (SQL: create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8 collate 'utf8_general_ci')
```

Well, obviously dropping the table before running the script again would be a solution. However, I think this should be handled by the upgrade script either as pre-flight check or by dropping the table. As it is now the script fails during migration.

**To Reproduce**
1. Do a 3.3 to 3.4 upgrade (probably with some failed pre-flight checks)

**What application are you using?**
OJS version 3.3 + 3.4rc2

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by asmecher** [comment]
(@ronste and I spoke about this briefly during the Testing Committee call -- he'll confirm some details with me. Self-assigning.)

**Comment by asmecher** [comment]
It looks like this was caused by an attempt to resume the upgrade after a failure that happened sometime after the preflight check completed; @ronste, if you're able to identify the cause of that first failure, please file a new issue! We're hoping that the preflight checks prevent as many of the failure modes as possible, but there will still be some.
