### ISSUE TITLE
OMP MonographSearchIndex missing hooks

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#9057]
The monograph search index class in OMP is missing the corresponding hooks from OJS. These are needed in order to hook into and replace the default indexing via plugin.

**Comment by ewhanson** [comment]
Hey @asmecher, could you have a look at these PRs? They add in missing search index class hooks for OMP. Thanks!

PRs:

- `stable-3_3_0`: pkp/omp#1418
- `main`: pkp/omp#1419

**Comment by asmecher** [comment]
Merged, thanks! There are improved conventions available for new hooks in `main` using `Hook::run` -- but this is not 100% backwards compatible, and you're also adding this to `stable-3_3_0` and staying consistent with OJS, so sticking with `Hook::call` is preferred.
