### ISSUE TITLE
[OMP] CSVImportExportPlugin is broken

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9065]
**Describe the bug**
The plugin is using some methods that don't exist anymore, initial fixes can be cherry-picked from here:
https://github.com/pkp/omp/pull/1412/files#diff-3a899a87f4935084a15647bb119256f752cc7623f451304ffcfeda1459b5fa70

As part of this task, it makes sense to add a test for it (a sample `.csv` file that could be placed in the plugin folder).

**What application are you using?**
OJS 3.4rc3

**Comment by asmecher** [comment]
Thanks, @jonasraoni -- if it's just a matter of cherry-picking existing fixes, please go ahead (and more tests are always welcome).
