### ISSUE TITLE
[OJS] CLI for the PubMedExportPlugin plugin is broken

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9066]
**Describe the bug**
The plugin is using some methods/arguments that don't exist anymore, initial fixes can be cherry-picked from here:
https://github.com/pkp/ojs/pull/3925/files#diff-65ae64191f7f56af72345ef343494e8eb0fe9a8d984517b932e41729ec545cdd

As part of this task, it makes sense to add tests for it.

**What application are you using?**
OJS 3.4rc3

**Comment by asmecher** [comment]
Thanks, @jonasraoni -- if it's just a matter of cherry-picking existing fixes, please go ahead (and more tests are always welcome).
