### ISSUE TITLE
Consider ROR in DataCite affiliation element

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9068]
PRs:
- https://github.com/pkp/ojs/pull/3941 (stable-3_3_0)
- https://github.com/pkp/ojs/pull/3942

**Comment by simonevecchi** [comment]
A thousand thanks. one thing is not clear to me using little git

https://github.com/bozana/ojs/blob/e006e33f537da0b8cae28475be56042cf528350f/plugins/generic/datacite/filter/DataciteXmlFilter.php

here I have the file modified with the ror for the new version of the plugin.

i'm using ojs pkp 3.3.14 and i don't have this file in this path but i have it here
 plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php

I used the new file taken from this link

https://github.com/bozana/ojs/blob/f2fe29fd5618a6a4c240eea69f8fea04b938e11c/plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php

but it didn't add me the ror in the xml.

where am i wrong?
