### ISSUE TITLE
Fix the pre-flight migration cleanup

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9069]
**Introduction**
Besides doing helpful checks, the pre-flight migration is also clearing orphaned data from the database ahead of the introduction of foreign keys.

**Problem**
If not done properly, the cleanup might still leave orphaned data behind, which will break the upgrade later on, at the `I6093_AddForeignKeys` migration. So far a couple of problems were identified from issues reported by community members and staff, this issue will cover:
- A couple of fields which are going to receive foreign key constraints are not being cleaned up.
- The way we delete data matter: if we delete a parent, we should also delete its children and cyclic relationships might pose an extra treat.
- Some fields are missing a foreign key constraint (they will be fixed separately after the 3.4 release, as part of the https://github.com/pkp/pkp-lib/issues/8333).

**Solution**
The proposed solution revolves around using the foreign key metadata from a clean 3.4 database, which will have all the expected foreign keys in place.

Below there are some samples of MySQL queries (tied to OMP) to extract the required information, they consider the user got 3.3 and 3.4 databases from the [datasets repository](https://github.com/pkp/datasets).

<details>
<summary>Detect missing foreign keys</summary>
<code>SELECT
	x.TABLE_NAME,
	x.COLUMN_NAME
FROM
	INFORMATION_SCHEMA.COLUMNS x
WHERE
	x.EXTRA <> 'auto_increment'
	AND RIGHT(x.COLUMN_NAME, 3) = '_id'
	AND (
		x.COLUMN_NAME NOT IN (
			'assoc_id',
			'from_role_id',
			'to_role_id',
			'stage_id',
			'load_id',
			'role_id'
		)
		AND NOT (
			x.table_name = 'sessions'
			AND x.COLUMN_NAME = 'session_id'
		)
		AND NOT (
			x.table_name = 'users'
			AND x.COLUMN_NAME = 'auth_id'
		)
		AND NOT (
			x.table_name = 'mailable_templates'
			AND x.COLUMN_NAME = 'mailable_id'
		)
	)
	AND x.TABLE_SCHEMA = 'omp'
	AND NOT EXISTS(
		SELECT
			0
		FROM
			INFORMATION_SCHEMA.KEY_COLUMN_USAGE u
		WHERE
			u.TABLE_SCHEMA = x.TABLE_SCHEMA
			AND u.TABLE_NAME = x.TABLE_NAME
			AND u.COLUMN_NAME = x.COLUMN_NAME
			AND u.REFERENCED_TABLE_SCHEMA = u.table_schema
	)
ORDER BY
	table_name,
	column_name;</code>
</details>

<details>
<summary>Automated cleanup code</summary>
<code>SELECT
	CONCAT(
		IF (
			EXISTS(
				SELECT
					0
				FROM
					INFORMATION_SCHEMA.COLUMNS c
				WHERE
					c.TABLE_SCHEMA = 'ops33'
					AND u.TABLE_NAME = c.TABLE_NAME
			)
			AND EXISTS(
				SELECT
					0
				FROM
					INFORMATION_SCHEMA.COLUMNS c
				WHERE
					c.TABLE_SCHEMA = 'ojs33'
					AND u.TABLE_NAME = c.TABLE_NAME
			),
			'',
			'// Application specific entity\n'
		),
		'$this->addTableProcessor(',
		QUOTE(c.TABLE_NAME),
		', function (): int {\n$affectedRows = 0;\n\t// Depends directly on ~',
		COALESCE(
			(
				SELECT
					COUNT(0)
				FROM
					INFORMATION_SCHEMA.KEY_COLUMN_USAGE u
				WHERE
					u.TABLE_SCHEMA = c.TABLE_SCHEMA
					AND u.TABLE_NAME = c.TABLE_NAME
					AND u.REFERENCED_TABLE_SCHEMA IS NOT NULL
			),
			'0'
		),
		' entities: ',
		COALESCE(
			(
				SELECT
					GROUP_CONCAT(
						CONCAT(
							u.COLUMN_NAME,
							'->',
							u.REFERENCED_TABLE_NAME,
							'.',
							u.REFERENCED_COLUMN_NAME,
							IF(
								EXISTS(
									SELECT
										0
									FROM
										INFORMATION_SCHEMA.COLUMNS c
									WHERE
										c.TABLE_SCHEMA = 'omp33'
										AND u.REFERENCED_TABLE_NAME = c.TABLE_NAME
										AND u.REFERENCED_COLUMN_NAME = c.COLUMN_NAME
								),
								'',
								'(not found in previous version)'
							)
						) SEPARATOR ' '
					)
				FROM
					INFORMATION_SCHEMA.KEY_COLUMN_USAGE u
				WHERE
					u.TABLE_SCHEMA = c.TABLE_SCHEMA
					AND u.TABLE_NAME = c.TABLE_NAME
					AND u.REFERENCED_TABLE_SCHEMA IS NOT NULL
			),
			''
		),
		'\n\t// Dependent entities: ~',
		(
			SELECT
				COUNT(0)
			FROM
				INFORMATION_SCHEMA.KEY_COLUMN_USAGE u
			WHERE
				u.REFERENCED_TABLE_SCHEMA = c.TABLE_SCHEMA
				AND u.REFERENCED_TABLE_NAME = c.TABLE_NAME
		),
		'\n',
		GROUP_CONCAT(
			CONCAT(
				IF(
					EXISTS(
						SELECT
							0
						FROM
							INFORMATION_SCHEMA.COLUMNS c
						WHERE
							c.TABLE_SCHEMA = 'omp33'
							AND u.TABLE_NAME = c.TABLE_NAME
							AND u.COLUMN_NAME = c.COLUMN_NAME
					),
					IF (
						EXISTS(
							SELECT
								0
							FROM
								INFORMATION_SCHEMA.COLUMNS c
							WHERE
								c.TABLE_SCHEMA = 'ops33'
								AND u.TABLE_NAME = c.TABLE_NAME
								AND u.COLUMN_NAME = c.COLUMN_NAME
						)
						AND EXISTS(
							SELECT
								0
							FROM
								INFORMATION_SCHEMA.COLUMNS c
							WHERE
								c.TABLE_SCHEMA = 'ojs33'
								AND u.TABLE_NAME = c.TABLE_NAME
								AND u.COLUMN_NAME = c.COLUMN_NAME
						)
						AND EXISTS(
							SELECT
								0
							FROM
								INFORMATION_SCHEMA.COLUMNS c
							WHERE
								c.TABLE_SCHEMA = 'ops33'
								AND u.REFERENCED_TABLE_NAME = c.TABLE_NAME
								AND u.REFERENCED_COLUMN_NAME = c.COLUMN_NAME
						)
						AND EXISTS(
							SELECT
								0
							FROM
								INFORMATION_SCHEMA.COLUMNS c
							WHERE
								c.TABLE_SCHEMA = 'ojs33'
								AND u.REFERENCED_TABLE_NAME = c.TABLE_NAME
								AND u.REFERENCED_COLUMN_NAME = c.COLUMN_NAME
						),
						'',
						'\t// Custom field (not found in at least one of the softwares)\n'
					),
					'\t// Deprecated/moved field (not found on previous software version)\n//'
				),
				'\t$affectedRows += ',
				IF (
					c.IS_NULLABLE = 'YES',
					'$this->deleteOptionalReference(',
					'$this->deleteRequiredReference('
				),
				IF(
					u.TABLE_NAME IN (
						'journal_settings',
						'server_settings',
						'press_settings'
					),
					'$this->getContextSettingsTable()',
					IF(
						u.TABLE_NAME IN ('journals', 'servers', 'presses'),
						'$this->getContextTable()',
						QUOTE(u.TABLE_NAME)
					)
				),
				', ',
				IF(
					u.COLUMN_NAME IN ('journal_id', 'server_id', 'press_id'),
					'$this->getContextKeyField()',
					QUOTE(u.COLUMN_NAME)
				),
				', ',
				IF(
					u.REFERENCED_TABLE_NAME IN (
						'journal_settings',
						'server_settings',
						'press_settings'
					),
					'$this->getContextSettingsTable()',
					IF(
						u.REFERENCED_TABLE_NAME IN ('journals', 'servers', 'presses'),
						'$this->getContextTable()',
						QUOTE(u.REFERENCED_TABLE_NAME)
					)
				),
				', ',
				IF(
					u.REFERENCED_COLUMN_NAME IN ('journal_id', 'server_id', 'press_id'),
					'$this->getContextKeyField()',
					QUOTE(u.REFERENCED_COLUMN_NAME)
				),
				');'
			)
			ORDER BY
				c.IS_NULLABLE SEPARATOR '\n'
		),
		'\nreturn $affectedRows;\n});\n'
	) AS code
FROM
	INFORMATION_SCHEMA.KEY_COLUMN_USAGE u
	INNER JOIN INFORMATION_SCHEMA.COLUMNS c ON u.TABLE_SCHEMA = c.TABLE_SCHEMA
	AND u.TABLE_NAME = c.TABLE_NAME
	AND u.COLUMN_NAME = c.COLUMN_NAME
WHERE
	u.REFERENCED_TABLE_SCHEMA = 'omp'
GROUP BY
	u.TABLE_NAME
ORDER BY
	(
		SELECT
			COUNT(0)
		FROM
			INFORMATION_SCHEMA.KEY_COLUMN_USAGE u
		WHERE
			u.REFERENCED_TABLE_SCHEMA = c.TABLE_SCHEMA
			AND u.REFERENCED_TABLE_NAME = c.TABLE_NAME
	) DESC,
	u.TABLE_NAME,
	u.COLUMN_NAME;</code>
</details>

<details>
<summary>Foreign key dependencies</summary>
<code>SELECT
	CONCAT(
		IF(
			u.REFERENCED_TABLE_NAME IN (
				'journal_settings',
				'server_settings',
				'press_settings'
			),
			'$this->getContextSettingsTable()',
			IF(
				u.REFERENCED_TABLE_NAME IN ('journals', 'servers', 'presses'),
				'$this->getContextTable()',
				QUOTE(u.REFERENCED_TABLE_NAME)
			)
		),
		' => [',
		GROUP_CONCAT(
			IF(
				u.TABLE_NAME IN (
					'journal_settings',
					'server_settings',
					'press_settings'
				),
				'$this->getContextSettingsTable()',
				IF(
					u.TABLE_NAME IN ('journals', 'servers', 'presses'),
					'$this->getContextTable()',
					QUOTE(u.TABLE_NAME)
				)
			)
			ORDER BY
				(
					SELECT
						COUNT(0)
					FROM
						INFORMATION_SCHEMA.KEY_COLUMN_USAGE u2
					WHERE
						u2.REFERENCED_TABLE_SCHEMA = u.TABLE_SCHEMA
						AND u2.REFERENCED_TABLE_NAME = u.TABLE_NAME
				) DESC SEPARATOR ', '
		),
		'],'
	) AS relation
FROM
	INFORMATION_SCHEMA.KEY_COLUMN_USAGE u
	INNER JOIN INFORMATION_SCHEMA.COLUMNS c ON u.TABLE_SCHEMA = c.TABLE_SCHEMA
	AND u.TABLE_NAME = c.TABLE_NAME
	AND u.COLUMN_NAME = c.COLUMN_NAME
WHERE
	u.REFERENCED_TABLE_SCHEMA = 'omp'
	AND EXISTS (
		SELECT
			0
		FROM
			INFORMATION_SCHEMA.COLUMNS c
		WHERE
			c.TABLE_SCHEMA = 'omp33'
			AND u.TABLE_NAME = c.TABLE_NAME
	)
	AND EXISTS (
		SELECT
			0
		FROM
			INFORMATION_SCHEMA.COLUMNS c
		WHERE
			c.TABLE_SCHEMA = 'omp33'
			AND u.REFERENCED_TABLE_NAME = c.TABLE_NAME
	)
GROUP BY
	u.REFERENCED_TABLE_NAME
ORDER BY
	(
		SELECT
			COUNT(0)
		FROM
			INFORMATION_SCHEMA.KEY_COLUMN_USAGE u2
		WHERE
			u2.REFERENCED_TABLE_SCHEMA = c.TABLE_SCHEMA
			AND u2.REFERENCED_TABLE_NAME = u.REFERENCED_TABLE_NAME
	) DESC;</code>
</details>

**What application are you using?**
OJS 3.4rc3

**Additional information**
Source issue: https://github.com/pkp/pkp-lib/issues/8929

**Comment by asmecher** [comment]
@jonasraoni, is there a motivating example? i.e. a dataset from the hosting team that breaks in a particular way?

**Comment by jonasraoni** [comment]
The motivation is random orphaned data that remains in the database after the cleanup (I haven't seen those anymore with this approach). I can grab a failing database, but that's not the point. I just see that upgrading without some things here will require good luck 🤔

Probably 80% of the code in these PRs was automated, directly from the expected FKs, with some retryability, and a reasonably good sorting for the operations.
