### ISSUE TITLE
Make easier to create custom Vue component in plugin

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9089]
Its already possible to create custom vue component and than add it via smarty hooks to existing UI.

But are few small improvements to make that experience easier
- [ ]  Expose more basic components from ui-library to be global and therefore easily available to the custom component
- [ ] Add example to the docs to see how it can be done
Currently if plugin create custom Vue.component, its limited to the use of global components from ui-library.

**Comment by jardakotesovec** [comment]
PR is now ready for review.

**Comment by asmecher** [comment]
No objections here, @jardakotesovec; can you open a PR against one of the applications with the specially-formulated submodule update commit message, so that the Travis tests integration can run over this change?

**Comment by asmecher** [comment]
Thanks, @jardakotesovec, the Travis test didn't quite complete one run but it's nothing you broke. Are you ready for https://github.com/pkp/pkp-lib/pull/9125 to be merged and cherry-picked forward to `main`?

**Comment by jardakotesovec** [comment]
@asmecher merged&cherry picked in pkp-lib. Should I always also update the the submodules across ojs/omp/ops?

**Comment by asmecher** [comment]
...and thanks for implementing this! I'll close the issue, unless there's something left to do here.
