### ISSUE TITLE
OJS 3.0b2: Required fields without asterisks

### ISSUE THREAD

**Issue by nmpx** [pkp/pkp-lib#909]
In the Journal Setting, under the contact tab, it shows that only two fields are required as denoted by the \* adjacent to the label.

However, both the name and email for the technical contact are actually required, but do not have an adjacent \* to mark this. Basically, its confusing.

![bug10](https://cloud.githubusercontent.com/assets/5183702/11276179/f610e7c4-8eae-11e5-938b-6c1035653f9e.png)

**Comment by asmecher** [comment]
Fixed, thanks!
