### ISSUE TITLE
ROLE_ID_ASSISTANT const has wrong value  

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9091]
**Describe the bug**
Role::ROLE_ID_ASSISTANT constant has wrong value 4096 and should have 4097, see: https://github.com/pkp/pkp-lib/blob/c00090f50254491da3b97b429f7303b2ebfedb7b/classes/security/Role.php#L29
This created a collision with another constant.

**What application are you using?**
 OJS, OMP or OPS main branch, 3.4.0 stable

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib main: https://github.com/pkp/pkp-lib/pull/9092
pkp-lib stable-3_4_0: https://github.com/pkp/pkp-lib/pull/9093

**Comment by asmecher** [comment]
This issue is fixed in OJS, OMP, and OPS 3.4.0-1. Users of 3.4.0-0 can also fix it by applying [this patch](https://patch-diff.githubusercontent.com/raw/pkp/pkp-lib/pull/9092.diff) in `lib/pkp`.
