### ISSUE TITLE
OMP 3.4.0-0 Backend Page for managing catalog not loading

### ISSUE THREAD

**Issue by nils-stefan-weiher** [pkp/pkp-lib#9094]
**Describe the bug**
The page in the editorial backend usually reached by the menu entry "Catalog" is generating a fatal error for our test installation.
The url ends with the path "manageCatalog".
Sorry for the late report, the bug was probably present for while now. But I was busy with another project.

**To Reproduce**
1. Go to 'Editiorial backend' either through login from the frontend page or via a direct url
2. Click on 'Catalog'
4. See a white screen

**What application are you using?**
OMP 3.4.0-0

**Additional information**
Log output from the exception:
```
[15-Jun-2023 10:20:46 Europe/Amsterdam] PHP Fatal error:  Uncaught InvalidArgumentException: Order direction must be "asc" or "desc". in /web/omp-3-4/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2285
Stack trace:
#0 /web/omp-3-4/lib/pkp/classes/submission/Collector.php(286): Illuminate\Database\Query\Builder->orderBy()
#1 /web/omp-3-4/classes/submission/Collector.php(130): PKP\submission\Collector->getQueryBuilder()
#2 /web/omp-3-4/lib/pkp/classes/submission/DAO.php(93): APP\submission\Collector->getQueryBuilder()
#3 /web/omp-3-4/lib/pkp/classes/submission/Collector.php(79): PKP\submission\DAO->getCount()
#4 /web/omp-3-4/pages/manageCatalog/ManageCatalogHandler.php(124): PKP\submission\Collector->getCount()
#5 [internal function]: APP\pages\manageCatalog\ManageCatalogHandler->index()
#6 /web/omp-3-4/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#7 /web/omp-3-4/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#8 /web/omp-3-4/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#9 /web/omp-3-4/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch()
#10 /web/omp-3-4/index.php(21): PKP\core\PKPApplication->execute()
#11 {main}
  thrown in /web/omp-3-4/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 2285
```

We are using a copy from our production database first migrated from OMP 3.1.2 to 3.3.0 and then once the 3.4 release candidate 3 was released from 3.3.0 to 3.4.0rc3 and then the code was updated to 3.4.0-0.

Do you need more details?

**Comment by nils-stefan-weiher** [comment]
My first assumption: It could be corrupted press settings. I will check that.

**Comment by asmecher** [comment]
You can fix the issue by...
- Applying https://github.com/pkp/omp/pull/1425 to your OMP 3.4.0-0 installation, **and**
- One of the following...
   - Running the upgrade from 3.3.0 to to 3.4.0 again (after restoring from backup), **or** 
   - Navigating to Settings > Website > Appearance, selecting one of the sort ordering options, and saving the form: 
![image](https://github.com/pkp/pkp-lib/assets/200411/ee37448b-ce39-4f59-9a42-1d9a7a7b9a7d)

The issue only affects OMP 3.4.0-0, and will be fixed in 3.4.0-1 and later.

**Comment by asmecher** [comment]
@nils-stefan-weiher, I've tested this locally and run through Travis tests, but your confirmation that this resolved the issue would be wonderful! Thanks for reporting.

**Comment by nils-stefan-weiher** [comment]
Thanks for the quick response, will test the fix with our installation.

**Comment by nils-stefan-weiher** [comment]
Mange catalog page is working again for all presses.
Thanks @asmecher for your fast and effective fix!

**Comment by asmecher** [comment]
Thanks to you for the clear report and confirmation, @nils-stefan-weiher!
