### ISSUE TITLE
OJS Update 3.3.0.14 to 3.4.0.0 stable

### ISSUE THREAD

**Issue by Mathewwss** [pkp/pkp-lib#9097]
**Describe the bug**

During the update, an attempt is made to insert data into the journal_settings table, with journal_id = 0.

journal_id always starts at 1 and increases with each new journal.

**What application are you using?**
OJS 3.3.0.14 to OJS 3.4.0.0 Stable.

**Additional information**
![image](https://github.com/pkp/pkp-lib/assets/50458770/860a6fdd-446d-42f5-8d09-cdfeeafd2c5a)

Solution?

**Comment by asmecher** [comment]
@Mathewwss, can you check the results of the following query in your OJS 3.3.0-14 database?
```sql
SELECT * FROM plugin_settings WHERE plugin_name = 'doipubidplugin' AND context_id = 0;
```

**Comment by Mathewwss** [comment]
![image](https://github.com/pkp/pkp-lib/assets/50458770/b1c4d757-9fcc-45d5-894d-992a49f2f44f)

**Comment by Mathewwss** [comment]
Run:

`DELETE FROM plugin_settings WHERE context_id = '0';`

Update successfully, just a few alerts about theme plugins.

Is there any problem removing these lines?

**Comment by asmecher** [comment]
Thanks, @Mathewwss. This is caused by bad data in your 3.3.0-x database. You can fix it with either of the following...
- Execute this database query before running the upgrade script:
   ```SQL
   DELETE FROM plugin_settings WHERE plugin_name = 'doipubidplugin' AND context_id = 0;
   ```
   **...or...**
- Apply [this patch](https://github.com/pkp/pkp-lib/commit/ec2903621d0259fa576a2c2e1d692d5cbb2ef8e2.diff) in `lib/pkp` before running the upgrade script.

**Comment by acspublisher** [comment]
After running below script issue is still presist
SELECT * FROM plugin_settings WHERE plugin_name = 'doipubidplugin' AND context_id = 0;

**------------------------------------------**

A database error has occurred: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'dois' already exists (SQL: create table `dois` (`doi_id` bigint not null auto_increment primary key, `context_id` bigint not null, `doi` varchar(255) not null, `status` smallint not null default '1') default character set utf8 collate 'utf8_general_ci')

**Comment by asmecher** [comment]
Hi @acspublisher -- I've already responded to [your forum post](https://forum.pkp.sfu.ca/t/request-pkp-team-to-check-all-thing-before-lauching-upgradation-not-check/79260/6) on the same matter. It's best to just post a question to one place to avoid duplicating support effort.
