### ISSUE TITLE
Review Reports not generate

### ISSUE THREAD

**Issue by Mathewwss** [pkp/pkp-lib#9102]
**Describe the bug**
Error when trying to generate review reports. Open empty tab.

Review reports -> ERROR
Counter reports -> OK
Articles reports -> OK

**What application are you using?**
 OJS 3.4.0.0 stable

**Additional information**
![image](https://github.com/pkp/pkp-lib/assets/50458770/eac4e878-9a8f-4c5e-87a4-5ddbfea6abae)

**Comment by asmecher** [comment]
@Mathewwss, thanks for reporting; you can fix this by applying https://github.com/pkp/reviewReport/commit/729253c7d27d9c40418baf4c016174d70c7b48e8.diff in `plugins/reports/reviewReport`. (The fix will be included in OJS 3.4.0-1, which will be released shortly.)
