### ISSUE TITLE
OJS 3.0b2: Multi-language journal creation glitch

### ISSUE THREAD

**Issue by mxbees** [pkp/pkp-lib#911]
When creating a new journal, if you have more than one language enabled, you see each field in both English and French (in this particular case) for the title. Once you fill this in, when you click on the journal description you get this screen:
![bug11_01](https://cloud.githubusercontent.com/assets/5183702/11280454/1b6ae01e-8ec4-11e5-8918-9ed833a72a87.png)
The problem, is that after you've entered the description in both languages, the next step appears to be clicking 'save'. But then this:
![bug11_02](https://cloud.githubusercontent.com/assets/5183702/11280484/348d66d4-8ec4-11e5-8879-84559bb66958.png)
It took me a while to notice, but when you see the two language textfields, the 'path' field just.... disappears.

**Comment by asmecher** [comment]
The way we do multilingual inputs is this: normally the field is presented in the main language, but when you enter that field, several languages may be presented for entering. @nmpx, try clicking outside the field before trying to save the form. Clicking outside the fields collapses the set back down to just the main language.

@NateWr, perhaps we could use a UI clue to make this clearer.

**Comment by nmpx** [comment]
I did eventually discover this. I doubt that I'd be the only person hitting 'save' once all the visible fields are filled in, so some sort of contextual clue would be helpful.

**Comment by NateWr** [comment]
Yeah the localisation popovers are a handy technique, but they will result in these kinds of confusing moments. I don't have any great ideas for solving multilingual input at this time and I think the downsides of the current method are small enough that it doesn't really justify a major re-engineering of the technique for now.

Perhaps one thing we could try is simply disabling the save button as long as a multilingual popover is open? It wouldn't solve the confusion like for @nmpx, but most people probably would figure it out eventually...

**Comment by nmpx** [comment]
I can see the reasoning behind this, since it is a rather small UI issue. Disabling the save button unless all required fields might work. Although, I can see that being as confusing for people as the other.

As it stands, the error will pop up after you hit save and the UI will inform you that you missed a field.

If there isn't a quick/easy way to address this, then leaving as it is might be the best idea.

**Comment by asmecher** [comment]
Moving to OMP 1.2.1 for consideration/UI/UX testing.

**Comment by t4x0n** [comment]
Hi, I read this post and I am thinking about this "issue", all my journals are in English and Spanish and in many cases is not a problem, but in Keywords yes it is! Maybe the popovers are not good enough for some actions like delete a keyword by click on the red X (See: https://github.com/pkp/pkp-lib/issues/3003)

I want to propose another way for implementation: Bootstrap Collapse.

I think, the first or main language is static, and only if others language is activated could appear below the textarea another language name and by click on it "uncollapse" this textarea like an accordion.

I am not a good coder as to make this changes, but if anybody likes, maybe could make some proofs.

**Comment by NateWr** [comment]
Hi @t4x0n. A manually triggered toggle could be a good solution to this approach. In the next month or so, I'm going to be mocking up some ideas for refactoring our form system. I'll definitely keep that approach in mind.

**Comment by NateWr** [comment]
Deferring because this requires a broader rethink on translations in forms if we're going to address it.

**Comment by carlaribeiro1234** [comment]
Me surprendi com Duratron! Vejam que incrpivel esse estimulante sexual[http://www.jacsondamasceno.com.br/duratron-estimulante-sexual/](http://www.jacsondamasceno.com.br/duratron-estimulante-sexual/)

**Comment by asmecher** [comment]
This has been fixed with the setup forms rewrite!
