### ISSUE TITLE
Doi migration script failing to return doi_id

### ISSUE THREAD

**Issue by MrRob100** [pkp/pkp-lib#9123]
**Describe the bug**
When DoiMigration is run it fails because of this error
`ERROR: Upgrade failed: DB: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "id" does not exist
LINE 1: ... "dois" ("context_id", "doi") values ($1, $2) returning "id"
                                                                   ^ (SQL: insert into "dois" ("context_id", "doi") values (1, 10.5334/test.1234) returning "id")`

**To Reproduce**
run the upgrade via the cli `$ php tools/upgrade.php upgrade`

**What application are you using?**
 OJS 3.3.0.14 upgrading to OJS 3.4.0.1

**Additional information**
PR for the fix here: https://github.com/pkp/pkp-lib/pull/9122

**Comment by asmecher** [comment]
Thanks, @MrRob100 -- I added a similar fix to another call to `insertGetId` (https://github.com/pkp/ojs/commit/188a600169aee1c6a56284f8d0d2e00909abe5c7). I could be wrong, but based on [this Laravel documentation](https://laravel.com/docs/10.x/queries#auto-incrementing-ids), the issue should only affect PostgreSQL users:
![image](https://github.com/pkp/pkp-lib/assets/200411/1260e6af-a3c7-43b7-af7a-155b2c9ce47b)

**Comment by MrRob100** [comment]
> pkp/ojs@188a600

Thanks for that extra insight @asmecher
