### ISSUE TITLE
Multilingual Metadata in Crossref

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#9126]
**Describe the bug**
*PKP Sprint Copenhagen.* Metadata exported to Crossref is currently mono-lingual (primary locale).  Journals are collecting multilingual metadata for articles.  Crossref can index this either as supplementary metadata (when there is multilingual metadata for a monolingual article), or as independent DOIs (for articles which have been translated).  This facilitates discovery in the user’s language.

**To Reproduce**
1. Add translations of the title and abstract to a submission
2. Publish the submission
3. Export the Crossref XML for the submission
4. Only the primary locale will be represented

**What application are you using?**
 OJS 3.3, 3.4

**Additional information**
Shayn Smulyan from Crossref writes:

the format you used would be fine for submitting multiple abstracts in multiple languages.  
 
```
<jats:abstract xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1" xml:lang="en">
<jats:p>Abstract in English</jats:p>
</jats:abstract>
<jats:abstract xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1" xml:lang="es">
<jats:p>Abstract in Spanish</jats:p>
</jats:abstract>
<jats:abstract xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1" xml:lang="cs">
<jats:p>Abstract in Czech</jats:p>
</jats:abstract>
 ```

But, as far as the titles go, there are two options. 
 
If the article you're registering is a translation of another article, you should use the <original_language_title> tag.  In context that looks like this:
 
```
<journal_article language="en">
<titles>
<title>New Article</title>
<original_language_title language="es">Nuevo Artículo</original_langauge_title>
</titles>
.....
```
 
In this case, as well, we'd strongly recommend adding an [isTranslationOf intra-work relationship](https://www.crossref.org/documentation/schema-library/markup-guide-metadata-segments/relationships/#00042) to connecting to the DOI of the original. 
 
If the article is not a translation, but you simply want the metadata expressed in multiple languages, you should not use `<original_language_title>` but instead add multiple `<titles>` sections, one for each language.  The language attribute within the `<journal_article>` tag should reflect the language of the full text content.  
 
So that would look like like this
 
```
<journal_article language="en">
<titles>
<title>New Article</title>
</titles>
<titles>
<title>Nuevo Artículo</title>
<titles>
```

---

Sprint contributors to this work include:
* Clinton Graham, University of Pittsburgh
* Radek Gomola, Masaryk University Press Czech Republic
* Susan Collins, Crossref
* Emma Uhl, Public Knowledge Project
* Ramana Fragola, National Library of Sweden
* Jyrki Heinonen, Federation of Finnish Learned Societies
* Esmee Klumpenaar, University of Groningen

<hr>

PRs:
OJS
- https://github.com/pkp/crossref-ojs/pull/38
- https://github.com/pkp/crossref-ojs/pull/39 (stable-3_4_0)
- https://github.com/pkp/ojs/pull/3960 (only submodule update stable-3_4_0)
- https://github.com/pkp/ojs/pull/3964 (stable-3_3_0)

OPS
- https://github.com/pkp/crossref-ops/pull/32
- https://github.com/pkp/crossref-ops/pull/31 (stable-3_4_0)
- https://github.com/pkp/ops/pull/545 (only submodule update stable-3_4_0)

**Comment by asmecher** [comment]
@bozana, could you have a look at this when you're available? Thanks!

**Comment by bozana** [comment]
Just to double check: I would port this change to stable-3_4_0 but also to crossref-ops repository. Are there any objections or doubts, @ctgraham and @ajnyga?

**Comment by ctgraham** [comment]
I don't see a reason this wouldn't be appropriate to OPS as well. In the Sprint there was also interest in possible backporting to 3.3. Should I write something up?

**Comment by bozana** [comment]
@ctgraham, great! Any contribution is very welcome! :pray:

**Comment by fgnievinski** [comment]
this is huge, many thanks for making it happen! it has the potential to unleash a ton of multilingual metadata that were never really exposed before (because of either #7272 or #699).

about multilingual metadata of monolingual content, last time I've checked with CrossRef, they've recommended "adding it [the language attribute] to both the journal-level and journal-article-level metadata", e.g.:
```
<journal_article language="en">
<titles language="en">
<title>New Article</title>
</titles>
<titles language="es">
<title>Nuevo Artículo</title>
<titles>
```
https://community.crossref.org/t/multi-language-support/3054/12

could you confirm if the language attribute is always set, even in the case of a single language?
https://github.com/pkp/crossref-ojs/issues/21

maybe it's also a good time to reconsider the implications of #7569, to avoid problems downstream during deposit and indexing. as an editor/admin, I'd appreciate the option to follow CrossRef's recommended practices more strictly (i.e., adopting a language-agnostic journal title), without imposing the choice.

here are a couple of other related issues:
* #5000
* #7335
* #5303

**Comment by ctgraham** [comment]
Hi, @fgnievinski .  In pkp/crossref-ojs#38, the `journal_article` `language` attribute is always set to the primary submission language, even in the case of a single language.
https://github.com/pkp/crossref-ojs/pull/38/files#diff-6ac12250187bc0d79809f02163656bd00203f38c8dc684057b883317800cc5c8R111

Note that Crossref does not (as of schema 5.3.1) support the `language` attribute on the `titles` tag.
https://data.crossref.org/reports/help/schema_doc/5.3.1/index.html

**Comment by bozana** [comment]
Regarding OPS: 
Crossref schemas (4.4.0 (used in stable-3_3_0) and 5.3.1 (used in stable-3_4_0 )) only allow one `titles` element for `posted_content`. 
In OPS stable-3_3_0 no `abstract` element is used.
Thus, only `abstract` element in stable-3_4_0 (and main) can be adapted to the changes here.
