### ISSUE TITLE
PHP mt_rand function should not be used for secrets

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9138]
**Describe the bug**
Per [the documentation of the `mt_rand` function](https://www.php.net/manual/en/function.mt-rand.php):
> This function does not generate cryptographically secure values, and must not be used for cryptographic purposes, or purposes that require returned values to be unguessable. 
> If cryptographically secure randomness is required, the [Random\Randomizer](https://www.php.net/manual/en/class.random-randomizer.php) may be used with the [Random\Engine\Secure](https://www.php.net/manual/en/class.random-engine-secure.php) engine. For simple use cases, the [random_int()](https://www.php.net/manual/en/function.random-int.php) and [random_bytes()](https://www.php.net/manual/en/function.random-bytes.php) functions provide a convenient and secure API that is backed by the operating system’s CSPRNG.

**Comment by asmecher** [comment]
For `stable-3_3_0` older than 3.3.0-16, this is resolved with the application of https://github.com/pkp/pkp-lib/commit/e5e7e543887fe77708aa31e07b18fe85f9b5a3b5 in `lib/pkp`.
For `stable-3_4_0` older than 3.4.0-2, this is resolved with the application of https://github.com/pkp/pkp-lib/commit/a79a6bba3aa22933c75558516306598a79b46b1d in `lib/pkp`.

**Comment by asmecher** [comment]
@jnugent, this shouldn't be included in 3.3.0-15, but I've added a fix to `stable-3_3_0` -- can you confirm?

**Comment by jnugent** [comment]
@asmecher  that's perfect on our side.  And yes, sorry, just in stable-3_3_0, not 3.3.0.15 (we deploy whatever stable is, and I just happened to catch this one)
