### ISSUE TITLE
OJS 3.0b1: OAI interface doesn't work

### ISSUE THREAD

**Issue by felixgruender** [pkp/pkp-lib#914]
In OJS3 beta, the OAI interface is broken. As far as I've seen, the reason for this is that the functions "getFileType()" and "getFilePath()" are called on an ArticleGalley object.
In OJS 2.x, that's no problem as the functions of parent classes are called (PKPFile::getFileType() and ArticleFile::getFilePath()). 
But in OJS 3, the inheritance schema is different (ArticleGalley extends Representation) - and thus non-existing functions are called.

**Comment by asmecher** [comment]
@felixgruender, you're right. We changed the mapping between files and galleys to support multiple files per galley, but haven't updated the OAI classes to suit that yet. A similar change is already in place for the OMP OAI interface, so we'll probably work with that.

**Comment by asmecher** [comment]
This is now working.
