### ISSUE TITLE
Google Analytics plugin seems no longer operational

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#9141]
The Google Analytics plugin (based on Measurement ID) seems no longer sufficient.

I've experienced the issue and I've found similar reports in the forum, e.g.:

https://forum.pkp.sfu.ca/t/ojs-3-3-google-analytics/68938/3
https://forum.pkp.sfu.ca/t/google-analytics-4-in-ojs3-3-x/66810/12

A workaround is to use Tracker ID in an HTML code snippet (redacted with ****...):
`<meta name="google-site-verification" content="********************" />`

It can be included in either the Custom Header plugin or in the following OJS setting:
`/management/settings/distribution#indexing`

The following JavaScript code snippet is also recommended for inclusion (redacted with ****...):
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-G506LBTMH2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '**************');
</script>
```

**Comment by bozana** [comment]
@fgnievinski, which OJS version are you using?
The support for GA v4 should be there since 3.3.0-12...

**Comment by fgnievinski** [comment]
current version installed is 3.3.0.13.
but the relevant version was 3.3.0.11
back when I've experienced the problem,
(I've been meaning to file this since January).

if the implementation has changed between now and then, 
it might be safe to assume it's been fixed, and we can close this issue.

(I'd rather not undo my special settings to double check.)

**Comment by asmecher** [comment]
It was added here: https://github.com/pkp/googleAnalytics/pull/55
