### ISSUE TITLE
One-click review request access keys not being generated/sent

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9142]
**Describe the bug**
In OJS/OMP 3.4.0-0 and 3.4.0-1, when one-click reviewer access URLs are enabled, they are not being sent as part of the review request email.

**To Reproduce**
1. Enable one-click reviewer access:
   1. Go to Settings > Workflow
   2. Go to Review
   3. Click the "One-click Reviewer Access" checkbox
   4. Save the settings.
2. Assign a reviewer to a submission
   1. In a submission's Review stage, assign a reviewer to a submission.
   2. Open the resulting email that was sent to the reviewer. Note that the submission URL does not include an `accessKey` variable indicating support for an access key.

This is a regression from OJS/OMP 3.3.0-x, which supported access keys on reviewer assignment.

**What application are you using?**
 OJS or OMP version 3.4.0-0 or 3.4.0-1

**Additional information**
One-click URLs appear to be implemented using a `OneClickReviewerAccess` trait; this is not currently used in the `ReviewRequest` mailable.

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib main: https://github.com/pkp/pkp-lib/pull/9177
tests: https://github.com/pkp/ojs/pull/3981

**Comment by asmecher** [comment]
Please go ahead and merge when ready -- thanks, @Vitaliy-1! The test failures are what Jarda mentioned in the dev call today, not related to the proposed changes.
