### ISSUE TITLE
An issue's TOC can be wrongfully pulled from another issue if the url path partially matches

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#9144]
**Describe the bug**
Had a client today mention that two issues, with different tables of contents on the reader front end, were showing the same table of contents in the issue management area.   One of these had an issueId of 57 and one had an issueId of 111.

It turned out that issueId 57 was using an url path in the issue data area of "111-207". This was causing the TocGridHandler to erroneously set the authorized context object of type ASSOC_TYPE_ISSUE to the same issue in both of these cases.  So, if you loaded the TOC for issueId 57, you received the TOC for issueId 111, because issueId 57 had an url path that matched.

This does not occur on the reader front end, which is a bit weird because it also uses the ASSOC_TYPE_ISSUE context object.  It must be fetching it in a different way in the issue management area.

This is more than a cosmetic bug because it means that if you update one issue's metadata you affect the other.

**To Reproduce**
1.  Create two issues with different tables of contents
2. publish both issues
3. Edit one issue and set the url path to begin with the issue id of the other issue.
4. load the tables of contents for both issues, they will be the same.

**What application are you using?**
OJS 3.3.0.15

**Comment by asmecher** [comment]
This was a subtle one. It appears to have already been fixed in 3.4.0, likely because a [`string` typehint](https://github.com/pkp/ojs/blob/8fa5a39fedcdc1ab7bd149c3e4b7492301cc0eca/classes/issue/Repository.php#L261) already coerced the data into a string.

PR: https://github.com/pkp/ojs/pull/3966

@jnugent, I'd love confirmation that this fixes the issue before I commit it.

**Comment by jnugent** [comment]
@asmecher confirming fixed!

**Comment by asmecher** [comment]
Merged, thanks!
