### ISSUE TITLE
Recommend decision email form doesn't respect to, cc and bcc fields

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9148]
**Describe the bug**
When an editor is making one of the recommend decisions, the email form allows to send a form to editors as well as specify cc/bcc recipients
![recommend](https://github.com/pkp/pkp-lib/assets/20665587/e1ec6475-37fb-454d-9cfd-9c3b931645a1)
There a several problems that arise with the current implementation:
1. The email is sent to each editor separately, despite `to` field indicates that email will be sent to all deciding editors. 
2. The mailable itself and email template variables are configured to include all editors as recipients, e.g., `recipientName`, `recipientUsername`, see: https://github.com/pkp/pkp-lib/blob/e8ebfba18f5fb809cc5c43329c3442d6ca3d44e1/classes/decision/types/traits/IsRecommendation.php#L104. 
3. cc and bcc fields are not included into the final email as it's sent as a query/discussion email: https://github.com/pkp/pkp-lib/blob/e8ebfba18f5fb809cc5c43329c3442d6ca3d44e1/classes/decision/types/traits/IsRecommendation.php#L131

**To Reproduce**
1. In the OJS email config set `default` to `log`
2. Make a submission and pass it to the review stage
3. Assign editors, one of which having a recommend only flag, log in as this editor
4. Press `Recommend Accept` button.
5. Add cc recipient to email and press `Record Decision`
6. In the log see that each recipient receives separate email, `cc` field is empty.

**What application are you using?**
 OJS, OMP, OPS version 3.4.0 stable and main

**Additional information**
The email to recipients is sent via `QeuryDAO::addQuery()` method. We can either use the same mechanism as sending emails to notify authors or reviewers about the decision or modify `addQuery` method implementation.

**Comment by Vitaliy-1** [comment]
PRs main
pkp-lib: https://github.com/pkp/pkp-lib/pull/9241
tests: https://github.com/pkp/ojs/pull/4015

stable-3_4_0
pkp-lib: https://github.com/pkp/pkp-lib/pull/9242

This should address all issues related to the recommend decision email

- Send to all editors at once rather than separate emails for each editor
- Support for cc and bcc fields
- Support for attachments

**Comment by asmecher** [comment]
Looks great, @Vitaliy-1, I thought this might have to be deferred to 3.4.0-3! I've skimmed the code and it looks good; if you're happy with your testing, I can sneak it into 3.4.0-2.

**Comment by asmecher** [comment]
If you'll forgive me for rushing this -- I've merged the PRs, and will give them a test. I'll test manually. Thanks for the quick work!

**Comment by asmecher** [comment]
@Vitaliy-1, I ran into a couple of problems testing this:
- The CC and BCC addresses don't seem to receive the email messages (I'm testing with local SMTP using Mailhog)
- It doesn't seem to be possible to add multiple addresses in the CC or BCC field (not sure if this is intentional or if I'm missing the right way?)

**Comment by Vitaliy-1** [comment]
> The CC and BCC addresses don't seem to receive the email messages (I'm testing with local SMTP using Mailhog)

That's strange, SMTP works fine in my case. I have a remote email server I can test with and I'm receiving emails.  

> It doesn't seem to be possible to add multiple addresses in the CC or BCC field (not sure if this is intentional or if I'm missing the right way?)

It looks like a global problem, rather than specific to the recommend decision. new email UI doesn't support multiple cc/bcc addresses.

**Comment by Vitaliy-1** [comment]
Regarding multiple cc/bcc, see: https://github.com/pkp/pkp-lib/issues/9246

**Comment by asmecher** [comment]
@Vitaliy-1, you're right, thanks -- the BCC/CC fields are working correctly. It looks like Mailhog lists them in the message source to the recipient, but does not deliver them as separate messages. Closing!
