### ISSUE TITLE
Error on User Import :Uncaught BadMethodCallException: PKP\mail\mailables\UserCreated doesn't support from(), use sender() instead in lib/pkp/classes/mail/traits/Sender.php:45

### ISSUE THREAD

**Issue by loadbrain** [pkp/pkp-lib#9150]
I try to import users from OJS 3.3.0.14 to 3.4.0.1
I get the error:
`PHP Fatal error:  Uncaught BadMethodCallException: PKP\mail\mailables\UserCreated doesn't support from(), use sender() instead in /web/ojs3/lib/pkp/classes/mail/traits/Sender.php:45
Stack trace:
#0 /web/ojs3/lib/pkp/plugins/importexport/users/filter/UserXmlPKPUserFilter.php(278): PKP\mail\mailables\UserCreated->from()
#1 /web/ojs3/lib/pkp/plugins/importexport/users/filter/UserXmlPKPUserFilter.php(348): PKP\plugins\importexport\users\filter\UserXmlPKPUserFilter->parseUser()
#2 /web/ojs3/lib/pkp/plugins/importexport/users/filter/UserXmlPKPUserFilter.php(331): PKP\plugins\importexport\users\filter\UserXmlPKPUserFilter->handleChildElement()
#3 /web/ojs3/lib/pkp/plugins/importexport/native/filter/NativeImportFilter.php(51): PKP\plugins\importexport\users\filter\UserXmlPKPUserFilter->handleElement()
#4 /web/ojs3/lib/pkp/classes/filter/Filter.php(498): PKP\plugins\importexport\native\filter\NativeImportFilter->process()
#5 /web/ojs3/lib/pkp/plugins/importexport/users/PKPUserImportExportPlugin.php(276): PKP\filter\Filter->execute()
#6 /web/ojs3/plugins/importexport/users/UserImportExportPlugin.php(74): PKP\plugins\importexport\users\PKPUserImportExportPlugin->importUsers()
#7 /web/ojs3/tools/importExport.php(78): APP\plugins\importexport\users\UserImportExportPlugin->executeCLI()
#8 /web/ojs3/tools/importExport.php(83): importExport->execute()
#9 {main}
  thrown in /web/ojs3/lib/pkp/classes/mail/traits/Sender.php on line 45
`
But I can repeat the import and every time mor users get imported...

What could I do?

Do be more precise, I can recall the import as many times as I want and every time a few more users get imported.
Sometimes only one, but sometimes also more...

**Comment by asmecher** [comment]
@Vitaliy-1, could you have a look at this one?

**Comment by Vitaliy-1** [comment]
PRs
main:
pkp-lib: https://github.com/pkp/pkp-lib/pull/9192
tests: https://github.com/pkp/ojs/pull/3989

stable 3.4.0:
pkp-lib: https://github.com/pkp/pkp-lib/pull/9193

`UserCreated` mailable was designed to be sent from the User (this generates certain sender-related email template variables) but Users XML import plugin sends this email with journal contact email and name set in the `from` field. In this PR I set the sender to be a User associated with the Request. Another approach could be to create a separate Mailable with new template.

**Comment by Vitaliy-1** [comment]
@bozana, could you take a look at this PR?

**Comment by asmecher** [comment]
Looks good to me, @Vitaliy-1 -- please go ahead. We should be cautious about using information (such as the current user) derived from the request in import/export operations, as those operations could be kicked off from the command line -- but this plugin in particular can only be invoked from the UI, so it's OK.
