### ISSUE TITLE
Locale migration does not take into account plugin_settings table

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#9152]
**Describe the bug**
Because the Locale migration does not take into account `plugin_settings` table, localized content from `customBlockManager` plugin is not getting migrated.

**What application are you using?**
 OJS `main` branch

**Additional information**
It seems that the localized content is in `setting_name`: [`blockContent`, `blockTitle`]

---------------------------

**PRs**

**Branch `main`**
PKP-LIB: #9156
OJS: pkp/ojs#3968 (***TESTS ONLY***)

**Comment by defstat** [comment]
@asmecher I have added the proposed PR fix in the [top](https://github.com/pkp/pkp-lib/issues/9152#issue-1803138776) comment.

**Comment by asmecher** [comment]
Just one comment needing attention, thanks! https://github.com/pkp/pkp-lib/pull/9156#issuecomment-1634711333

**Comment by defstat** [comment]
@asmecher I have pushed the change to PR
