### ISSUE TITLE
Section editor is automatically assigned after article submission

### ISSUE THREAD

**Issue by shantanu198713** [pkp/pkp-lib#9159]
**OJS-3.3.0-14
PHP-7.4**

I have configured one more journal on our ejournal portal but the Section editor is automatically assigned after the article submission.

No error was generated.

![Screenshot 2023-07-14 164539](https://github.com/pkp/pkp-lib/assets/108086810/84e7cfb4-3a48-4f0f-9b1e-e08cdcb62db7)

**Comment by asmecher** [comment]
@shantanu198713, can you start this discussion on the PKP Support Forum (https://forum.pkp.sfu.ca)? That's the best way to begin; if it turns out to be a bug, we can migrate it back here.
