### ISSUE TITLE
Call to getLocale() on NULL in NativeXmlPKPAuthorFilter.inc.php

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#9160]
**Describe the bug**
When importing issues via native XML import in OJS 3.3.0-15 the uninitialized variable $submission is referenced:

https://github.com/pkp/pkp-lib/blob/5cad3a1534781d682b242b528158b957702948f1/plugins/importexport/native/filter/NativeXmlPKPAuthorFilter.inc.php#L127

Most likely `$submission->getLocale()` in line 127 needs to be replace by `$publication->getData('locale')`. At least that fixed the issue in my case.

Only applies to OJS 3.3 (code is change anyway in 3.4).

**What application are you using?**
 OJS, OMP or OPS version 3.3.0
 
 --------
 
**PR**

**Branch `stable-3_3_0`**
PKP-LIB: #9173

**Comment by asmecher** [comment]
@defstat, could you have a look at this one?

**Comment by defstat** [comment]
@ronste That `$submission` variable seems to be left by mistake. Removed it and changed it with the same code you suggested. Thanks.

@asmecher PR ready in the top comment

**Comment by asmecher** [comment]
Merged, thanks!
