### ISSUE TITLE
Password reset process does not provide username to user

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9169]
Starting with OJS 3.3.0-14, the password reset process was simplified:

https://github.com/pkp/pkp-lib/issues/2135

However, the new password reset email does not include the username in the text (or available variables). This causes confusion when users know their password but are using the wrong username.

Re-add the username to the available list of variables, and consider adding it to the default text.

**Comment by asmecher** [comment]
Changes:
- For 3.3.0-x users, a new variable `{$recipientUsername}` can be added to the `PASSWORD_RESET_CONFIRM` email template. (This is already available in 3.4.0.)
- At the conclusion of the password reset process, clicking "Login" will pre-fill the login form with the appropriate username.

Users of OJS 3.3.0-x older than 3.3.0-16 can apply this patch:
```diff
diff --git a/pages/login/LoginHandler.inc.php b/pages/login/LoginHandler.inc.php
index ef61d9d82c..761caca888 100644
--- a/pages/login/LoginHandler.inc.php
+++ b/pages/login/LoginHandler.inc.php
@@ -51,7 +51,7 @@ class LoginHandler extends Handler {
 		$templateMgr = TemplateManager::getManager($request);
 		$templateMgr->assign(array(
 			'loginMessage' => $request->getUserVar('loginMessage'),
-			'username' => $session->getSessionVar('username'),
+			'username' => $request->getUserVar('username') ?? $session->getSessionVar('username'),
 			'remember' => $request->getUserVar('remember'),
 			'source' => $request->getUserVar('source'),
 			'showRemember' => Config::getVar('general', 'session_lifetime') > 0,
@@ -202,6 +202,7 @@ class LoginHandler extends Handler {
 		$mail->assignParams([
 			'url' => $request->url(null, 'login', 'resetPassword', $user->getUsername(), array('confirm' => $hash)),
 			'siteTitle' => htmlspecialchars($site->getLocalizedTitle()),
+			'recipientUsername' => $user->getUsername(),
 		]);
 		$mail->addRecipient($user->getEmail(), $user->getFullName());
 		$mail->send();
@@ -209,7 +210,7 @@ class LoginHandler extends Handler {
 		$templateMgr->assign([
 			'pageTitle' => 'user.login.resetPassword',
 			'message' => 'user.login.lostPassword.confirmationSent',
-			'backLink' => $request->url(null, $request->getRequestedPage()),
+			'backLink' => $request->url(null, $request->getRequestedPage(), null, null, ['username' => $user->getUsername()]),
 			'backLinkLabel' => 'user.login',
 		]);
 		$templateMgr->display('frontend/pages/message.tpl');
@@ -303,7 +304,7 @@ class LoginHandler extends Handler {
 				$templateMgr->assign([
 					'pageTitle' => 'user.login.resetPassword',
 					'message' => 'user.login.resetPassword.passwordUpdated',
-					'backLink' => $request->url(null, $request->getRequestedPage()),
+					'backLink' => $request->url(null, $request->getRequestedPage(), null, null, ['username' => $user->getUsername()]),
 					'backLinkLabel' => 'user.login',
 				]);
```

**Comment by asmecher** [comment]
Users wishing to add the username to existing email templates can do that with queries like the following, one for each language:

English:
```
UPDATE email_templates_default_data SET body=replace(body, '{$url}<br />', '{$url}<br />Username: {$recipientUsername}<br />') WHERE email_key='PASSWORD_RESET_CONFIRM' AND locale = 'en_US';
```
Spanish:
```
UPDATE email_templates_default_data SET body=replace(body, '{$url}<br />', '{$url}<br />Nombre usario: {$recipientUsername}<br />') WHERE email_key='PASSWORD_RESET_CONFIRM' AND locale = 'es_ES';
```
Portuguese (Brazilian):
```
UPDATE email_templates_default_data SET body=replace(body, '{$url}<br />', '{$url}<br />Usuário: {$recipientUsername}<br />') WHERE email_key='PASSWORD_RESET_CONFIRM' AND locale = 'pt_BR';
```
Each query should result in a message like the following:
```
Rows matched: 1  Changed: 1  Warnings: 0
```
(Do not run a query for one language multiple times! You'll end up duplicating the username in the template that way.)

**Comment by radjr2** [comment]
Does this mean that systems running 3.3.0.14 can use the variable {$recipientUsername} in the email without any changes to any other code? My testing shows that it does NOT return the username. The note above with the patch suggests that patch is only to automatically bring up the username on the login screen. 

Please clarify as we have published many issues with the {$Username} in the body and it has not work for a long time and we look silly. Thanks!

**Comment by asmecher** [comment]
@radjr2, could you ask questions in the support forum (https://forum.pkp.sfu.ca), linking to issues like this where necessary? That's the best place to get support.

**Comment by radjr2** [comment]
Sorry, when I do that I don't hear from anyone. Then I found a note stating that all support should go through github.


Richard A. DeVito, Jr

Publisher

Weston Medical Publishing, LLC

470 Boston Post Road, Suite 301

Weston, MA 02493

www.wmpllc.org<http://www.wmpllc.org> - ***@***.***

781-899-2702 Ext. 107

339-222-4364 Cell


________________________________

**Comment by radjr2** [comment]
I will look for it. I think it was on Alperns' survey request today.


Richard A. DeVito, Jr

Publisher

Weston Medical Publishing, LLC

470 Boston Post Road, Suite 301

Weston, MA 02493

www.wmpllc.org<http://www.wmpllc.org> - ***@***.***

781-899-2702 Ext. 107

339-222-4364 Cell


________________________________

**Comment by radjr2** [comment]
https://forum.pkp.sfu.ca/t/username-does-not-populate-in-emails/95619


Richard A. DeVito, Jr

Publisher

Weston Medical Publishing, LLC

470 Boston Post Road, Suite 301

Weston, MA 02493

www.wmpllc.org<http://www.wmpllc.org> - ***@***.***

781-899-2702 Ext. 107

339-222-4364 Cell


________________________________
