### ISSUE TITLE
Undefined array key "user" in pkp/classes/proxy/ProxyParser.php on line 57

### ISSUE THREAD

**Issue by Commifreak** [pkp/pkp-lib#9171]
**Describe the bug**
Defining a proxy within OJS 3.4 like

```
[proxy]

; The HTTP proxy configuration to use
http_proxy = "http://1.2.3.4:8000"
https_proxy = "http://1.2.3.4:8000"
```

produces:

```
Array
(
    [scheme] => http
    [host] => 1.2.3.4
    [port] => 8000
)
```
for the `parse_url` function within ProxyParser. Regardless if user:pass is set, OJS tries to access array-key `user` and `pass` whcih not exist. OJS/PKP warns:

```
PHP Warning:  Undefined array key "user" in /var/www/test.ojs/lib/pkp/classes/proxy/ProxyParser.php on line 57
```

**To Reproduce**
Configure proxy like said, executy anything

**What application are you using?**
OJS 3.4.0

**Additional information**
PHP 8.2

**Comment by jonasraoni** [comment]
Thanks for the detailed report and reproduction :)
