### ISSUE TITLE
[OJS]NativeImportExportPlugin accepts malformed xml

### ISSUE THREAD

**Issue by samueloph** [pkp/pkp-lib#918]
The NativeImportExportPlugin currently accepts articles without abstract, and abstract is a required field in the submission templates (and the edit ones).

This causes some stranges situations where articles's titles are showed as a text (without link to the abstract/pdf) and blocks the edition of the article until somebody set ups an abstract.

Is this the right behaviour?

**Comment by asmecher** [comment]
It's possible for abstracts to be optional, if the section is flagged as "abstracts not required". So strictly speaking, the XML isn't invalid; it depends on the system's section configuration.

**Comment by samueloph** [comment]
Oh, sorry, my boss asked me about this "issue" and I'm not familair enough with OJS on the user side to know this. Gonna double my attention next time.
Thanks.

**Comment by asmecher** [comment]
Not to worry -- there are a ton of options and it's easy to overlook one.
