### ISSUE TITLE
Add controlling configuration to queue jobs

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#9195]
**Describe the bug**
We have queue jobs that can managed and executed via JobRunner or Cron or Worker Thread . But it works with default jobs configurations such as tries, backoff with no maxException etc . It will be a good enhancement to have this added to the `PKP\jobs\BaseJob` class. 

**Who will be benefited from it**
This will help users to handle case such as https://forum.pkp.sfu.ca/t/ojs-3-4-0-1-pkp-jobs-doi-depositsubmission-has-been-attempted-too-many-times-or-run-too-long/80154/3 . In fact `job has been attempted too many times or run too long` is a very common occurrence for which can be handled via worker command options but have no default configs when running via JobRunner. 

**What configs should be added**
1. tries = 3
2. backoff = 5 seconds
3. maxExceptions = 3
4. timeout = 60 seconds with increased to 180 for long running jobs .
5. failOnTimeout = true
6. retry_after = 240 seconds 

**What application are you using?**
 OJS, OMP or OPS version `3.4.0` and `main`

**PRs**

#### Stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9213
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3998 [TEST ONLY]

Need to forward port to `main`

**Comment by touhidurabir** [comment]
@asmecher can you please review the PR at https://github.com/pkp/pkp-lib/issues/9195#issue-1826346096

**Comment by asmecher** [comment]
@touhidurabir, no objections here, but are the two PRs syced?

**Comment by touhidurabir** [comment]
@asmecher I suggest to discard the `main` branch PR and forward port the `stable-3.4.0` branch PR . I am closing the `main` branch PR as that has some outdated changes .

**Comment by asmecher** [comment]
Thanks, @touhidurabir -- merged to `stable-3_4_0` for `pkp-lib`, and cherry-picked that forward to `main`. I'll handle the submodule updates separately.

**Comment by touhidurabir** [comment]
@asmecher Patch PR

### stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9263
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4029 [TEST ONLY]

**Comment by asmecher** [comment]
@touhidurabir, because [this new issue](https://forum.pkp.sfu.ca/t/ojs-3-4-0-2-php-fatal-error-usage-statistics-stopped-procesing-records/80762) isn't strictly speaking the same issue that this entry resolved, I've filed the new issue [here](https://github.com/pkp/pkp-lib/issues/9264) for resolution in 3.4.0-3.
