### ISSUE TITLE
ojs 3.3.0 - commit pkp/pkp-lib#9132 breaks postgres query

### ISSUE THREAD

**Issue by bdcaf** [pkp/pkp-lib#9199]
**Describe the bug**
Rebuilt my docker container with OJS branch stable-3_3_0 (Alpine Linux, php 8.2, postgres database). Noticed that Dashboard/Editorial activity gives 500. 
Longish Errorlog has the line
```
#20 {main} Next Illuminate\Database\QueryException: SQLSTATE[22007]: Invalid datetime format: 7 ERROR: invalid input syntax for type date: "pi.date_published" (SQL: select count(*) as aggregate from "submissions" as "s" left join "publications" as "pi" on "pi"."publication_id" = (select "pi2"."publication_id" from "publications" as "pi2" where "pi2"."submission_id" = "s"."submission_id" and "pi2"."status" = 3 order by "pi2"."date_published" asc limit 1) where "s"."context_id" in (16) and CAST(s.date_submitted AS DATE) > pi.date_published) in /var/www/html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671 Stack trace: 
```
Which is odd as the query executes perfectly fine when  submitted directly on the database. 

**To Reproduce**
1. Login as admin
2. Dashboard 
3. Select "Editorial Activity"
4. White page 

**What application are you using?**
 OJS version 3.3.15

**Additional information**
The commit https://github.com/pkp/pkp-lib/commit/96883fad1a05f57615e59a360fdf927d4d2c1735 looked suspicious. And I can confirm the issue disappears if I build with:
```
RUN cd /build/lib/pkp && git revert 96883fad1a05f57615e59a360fdf927d4d2c1735 --no-edit  && composer install --ignore-platform-reqs --no-interaction --no-progress
```

**Comment by asmecher** [comment]
Thanks for reporting, @bdcaf. @bozana, can you have a look at this one please?

**Comment by bdcaf** [comment]
Just tried it - first test looks promising (In an empty journal with just a single submission the  editorial statistics page loads fine).
I'll start deploying it and let you know if anything comes up.

**Comment by bozana** [comment]
I will then close this issue now, if something else comes up please feel free to reopen this or create a new issue.
Thanks a lot!
