### ISSUE TITLE
OMP 3.4.0 Sitemap does not respect chapter landing page setting

### ISSUE THREAD

**Issue by nils-stefan-weiher** [pkp/pkp-lib#9210]
**Describe the bug**
OMP Sitemap creation does not respect the new chapter setting "Show this chapter on its own page and link to that page from the book's table of contents." (internally called `isPageEnabled`).

Found this bug while testing the sitemap during a migration test with a production database with many books with chapters.

**To Reproduce**
1. Go to a sitemap of a current OMP 3.4.0 installation path '<press>/sitemap'
2. See chapter URLs output for chapter which do not have their own page, the created URLs show a page with 404 Error

**What application are you using?**
OMP 3.4.0 (Branch `stable-3_4_0`, commit `1e3eef60a2419f0d9ca0e4e6d40f6e6c328f5899`)

**Additional information**
The following lines in the SitemapHandler create the chapter URLs in the sitemap:
https://github.com/pkp/omp/blame/stable-3_4_0/pages/sitemap/SitemapHandler.php#L53-L55
A statement is missing that only adds the URL if `\APP\monograph\Chapter::isPageEnabled()` is true.

I will add a pull request soon.

**Comment by jonasraoni** [comment]
Hi @nils-stefan-weiher!
I see this is a 3.4 feature, both the problem description and the fix looks right for me, so I've approved the PR. If you have free time to create the one for `main`, great 😁
If not, we can cherry-pick it once it's merged.

**Comment by jonasraoni** [comment]
Closing!
I went ahead, merged the PR and [cherry-picked it](https://github.com/pkp/omp/commit/88ea6518a72de4343a7997716e1ea7c38db4d8c3) on the main branch.
