### ISSUE TITLE
 504 Gateway Timeout when accessing settings -> context page

### ISSUE THREAD

**Issue by lucas-carrijo** [pkp/pkp-lib#9212]
Hi, can anybody help me?

I´m using OJS 3.2.1.1

With this configuration
![OJS OS](https://github.com/pkp/pkp-lib/assets/58045516/a2ada311-bf62-4fb1-bf34-03bc7cfcd142)

When I try to enter the settings -> context tab I get a timeout error, I already checked the server logs, I didn't find any evidence of what could be the problem, does anyone know what it could be?

this is my url https://"my-domain"/index.php/revistadedefesadaconcorrencia/management/settings/context

![image](https://github.com/pkp/pkp-lib/assets/58045516/9f7eef9d-a3ae-4179-89c3-b26a8c51883b)

thank you very much if anyone can help!

**Comment by touhidurabir** [comment]
@lucas-carrijo please submit your problem/issue at https://forum.pkp.sfu.ca/ as that is the best place to get help and possible solution .
