### ISSUE TITLE
Uncaught Error: Object of class Version could not be converted to string LocaleFile.inc.php

### ISSUE THREAD

**Issue by rafaelmr2** [pkp/pkp-lib#9225]
**Describe the bug**
I upgraded to version 3.3.0-15. When I access site I get a notice from PHP:

```
[Thu Aug 10 10:37:01.777381 2023] [php7:notice] [pid 10959] [client 10.199.209.2:54734] PHP Notice:  Undefined index: gl_ES in /var/www/html/ojs/lib/pkp/classes/site/Site.inc.php on line 39
```

But when I access admin page I get a Fatal Error with blank screen:

```
[Thu Aug 10 10:38:49.199606 2023] [php7:error] [pid 18052] [client 10.199.209.2:42486] PHP Fatal error:  Uncaught Error: Object of class Version could not be converted to string in /var/www/html/ojs/lib/pkp/classes/i18n/LocaleFile.inc.php:102\nStack trace:\n#0 /var/www/html/ojs/lib/pkp/classes/i18n/LocaleFile.inc.php(102): str_replace()\n#1 /var/www/html/ojs/lib/pkp/classes/i18n/PKPLocale.inc.php(266): LocaleFile->translate()\n#2 /var/www/html/ojs/lib/pkp/classes/i18n/PKPLocale.inc.php(914): PKPLocale::translate()\n#3 /var/www/html/ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php(1353): __()\n#4 /var/www/html/ojs/cache/t_compile/0a89bb8d88c18a023186c7de6d80e4868e9d29fa^e7315c2d256da370b88dfcb90db35dd31eedaa4e_0.app.adminindex.tpl.php(31): PKPTemplateManager->smartyTranslate()\n#5 /var/www/html/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_64d4e1903f29b7_43915681()\n#6 /var/www/html/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()\n#7 /var/www/html/ojs/lib/pkp/lib/ve in /var/www/html/ojs/lib/pkp/classes/i18n/LocaleFile.inc.php on line 102, referer: https://xyz.br/
```

There is no 'gl_ES' in locale, I think this could be the source of error. I tried to put the 2.4.8 folder in locale but didn't work. I tried to clean the folder /var/www/html/ojs/cache/t_compile but didn't work too.

**To Reproduce**
1. Go to https://xyz.br/index.php/index/admin/index
2. See error

**What application are you using?**
 OJS version 3.3.0-15

Thanks.

**Comment by jonasraoni** [comment]
Hi @rafaelmr2

> Undefined index: gl_ES

The language `gl_ES` doesn't exist at the file https://github.com/pkp/ojs/blob/stable-3_3_0/registry/locales.xml, you'll have to either drop it (in case you recognize it's wrong) from the database or add it to the `locales.xml`.

> When I access admin page I get a Fatal Error

I couldn't simulate this error, and after watching the code it doesn't make sense to happen.
No changes have been made to these files lately, and they are used often, which means someone should have seen this error before, and we didn't receive such report.

Therefore, I'll close this issue, unless you can provide us a way to simulate it.
