### ISSUE TITLE
Announcement feed plugin incorrect sorting

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9226]
**Describe the bug**
At the `stable-3_3_0` branch, the announcement feed plugin enforces a record sorting by `date_posted`, the behavior wasn't ported to `stable-3_4_0` during the refactoring.

**Solution**
- The collector should have the sorting by `date_posted` enabled by default.
- The expired announcements should probably be hidden.
- Given the plugin is generic, it might make sense to turn it into a submodule and share it with the other applications.

**What application are you using?**
OJS 3.4.0

**Additional information**
Issue created to track the remaining work from https://github.com/pkp/pkp-lib/issues/8288

<hr>
PRs:

stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/9459
- https://github.com/pkp/ojs/pull/4082

**Comment by asmecher** [comment]
@nils-stefan-weiher, you offered a PR for `stable-3_4_0` for this issue [over here](https://github.com/pkp/pkp-lib/issues/8288#issuecomment-1670750852) -- it would be very welcome, thanks! We're hoping to wrap up 3.4.0-2 late this week and would love to include it if you have time.

**Comment by nils-stefan-weiher** [comment]
@asmecher Sorry, I was on holiday the last three weeks.
I have the code already, I can wrap-up a PR this week, if its still neede.

**Comment by asmecher** [comment]
@nils-stefan-weiher, actually I think this will be fixed by https://github.com/pkp/pkp-lib/pull/9255 when it's merged; don't worry about it!

**Comment by bozana** [comment]
@jonasraoni, could you please take a look at the PRs above?
I see that Nate will solve the problem of sorting the announcements by date_posted by default, but the PRs here also fix the isActive filter and consider that filter in the AnnouncementFeed plugin.
I have not managed to display the feeds, so I could not tested the feed plugin. Can you tell me how to display the announcement feeds?

**Comment by bozana** [comment]
Oh, for some reason I did not seen the Announcement Feed Plugin in that sidebar list earlier (and I did take a look there), but now I do se it :-D
Thanks @jonasraoni!

**Comment by jonasraoni** [comment]
Ok! I've already reviewed. It's better to merge these small fixes than waiting for the other issue to be solved, it might always take longer than expected 😁
