### ISSUE TITLE
[OJS-3.4.0-1] Incorrect (encrypted) password sent to the user after the user was added by Admin/Journal Manager

### ISSUE THREAD

**Issue by shantanu198713** [pkp/pkp-lib#9227]
OJS-3.4.0-1
PHP-8.1

Incorrect (encrypted) password sent to the user after the user was added by Admin/Journal Manager.
**I think the registration portal URL can be included in the mail.**

![Screenshot 2023-08-14 101858](https://github.com/pkp/pkp-lib/assets/108086810/89e998d3-8b5b-4412-a8f6-934dd8767447)

**Comment by touhidurabir** [comment]
@Vitaliy-1 PRs to review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9230
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4006 [TEST ONLY]

we probably need to port the changes to `main` branch and user export import plugin also .

**Comment by touhidurabir** [comment]
@Vitaliy-1 can you check again ? Updated the PR based in review .

**Comment by Vitaliy-1** [comment]
PR pkp-lib main: https://github.com/pkp/pkp-lib/pull/9233

**Comment by Vitaliy-1** [comment]
Thanks, merged!
