### ISSUE TITLE
Improve support for CC and BCC fields in the new decision email step UI 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9246]
**Describe the bug**
New decisions UI implements a form to edit and send the email as one of the steps. E.g., when making a recommendation decision whether to accept a submission. The form supports CC and BCC fields. The problem is that it's not intuitive to fill the fields with multiple email address. It accepts only email addresses separate by a comma, spaces are not allowed. E.g., 
```
vitaliy@test.test, vitaliy2@test.test
```
would trigger a vue form error. 
Also, keyboard `Enter` key is often used in our UI (e.g., in keywords input) and email clients, like Gmail, to separate the values of those fields. 

**To Reproduce**
1. Make a submission
3. Pass submission to the review stage and assign an editor
4. Under the editor grid click on the `edit` button and check `This participant is only allowed to recommend an editorial decision and will require an authorised editor to record editorial decisions.`
5. Log in as assigned editor
6. Go to the submission and click `Recommend Accept`
7. When composing and email as one of the steps, click on Add CC/BCC
8. In the CC or BCC fields specify multiple email addresses separate by a comma and a space. 
9. See the error message in the UI 

**What application are you using?**
 OJS 3.4.0

**Additional information**

![email](https://github.com/pkp/pkp-lib/assets/20665587/2be4d557-b98d-4b44-9178-6a00ce9b6d1f)

**Comment by Vitaliy-1** [comment]
PRs main
ui-library: https://github.com/pkp/ui-library/pull/281
tests: https://github.com/pkp/ojs/pull/4020

stable-3_4_0
ui-library: https://github.com/pkp/ui-library/pull/282

This only addresses the problem with spaces

**Comment by Vitaliy-1** [comment]
@asmecher, I think this fix can be shipped with the next stable release and the rest (UI improvement) could be planned for 3.5

**Comment by asmecher** [comment]
All merged -- thanks, @Vitaliy-1!
