### ISSUE TITLE
Add filter to search by journal to site-level searching in OJS

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#9256]
**Describe the problem you would like to solve**
When searching for published articles across all journals in a multi-journal install of OJS, it is not possible to restrict the search to one journal. Also, the search results do not show which journal each article is from.

**Describe the solution you'd like**
Add a filter to the advanced search page to filter search results by journal. This filter should only be visible when accessed from the site-wide search page.

Also, add the journal name to each search result when searching from this page.

**Who is asking for this feature?**
This is part of sponsored development work for a PKP|PS client, UNIANDES, who will use this feature in their custom theme.

**Comment by NateWr** [comment]
The following PR implements this:

https://github.com/pkp/ojs/pull/4024

@asmecher would you be able to review? Here's a screenshot.
![Screenshot 2023-08-24 at 16-04-06 Search](https://github.com/pkp/pkp-lib/assets/2306629/7a43b8af-ac77-494e-915f-ea472013dc77)

**Comment by asmecher** [comment]
With apologies for the wait -- I've added a couple of comments on that PR.

**Comment by NateWr** [comment]
@asmecher I made the changes and the tests are passing for `stable-3_4_0`. I've cherry-picked the relevant commits over to a PR for `main`. Both of these can be merged when you're ready:

https://github.com/pkp/ojs/pull/4024 (stable-3_4_0)
https://github.com/pkp/ojs/pull/4093 (main)

**Comment by asmecher** [comment]
@NateWr, thanks, I've merged both the PRs in [the comment above](https://github.com/pkp/pkp-lib/issues/9256#issuecomment-1790953664). Can this issue be closed?
