### ISSUE TITLE
Coins plugin expects an issue and generates fatal error when previewing submissions

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#9265]
**Describe the bug**
There  are several places in the Coins plugin where an issue object is expected.  This isn't the case when an article is being previewed before it is assigned to an issue, and fatal errors result.

**To Reproduce**
1.  Create an article and send to copyediting
2. Do not assign an issue to the article
3. Enable the Coins plugin
4. Preview the article - a fatal error is generated.

**What application are you using?**
OJS 3.3.0.15

**Comment by asmecher** [comment]
@jnugent, can you try one of the attached commits?
- `stable-3_4_0`: https://github.com/pkp/coins/commit/e679ae0dea8c78118f7ec401a48c6c244dc929b4.diff
- `stable-3_3_0`: https://github.com/pkp/coins/commit/dbfebe4e6fd21d113f74f1952094004181483bd6.diff

**Comment by jnugent** [comment]
@asmecher  the stable-3_3_0 patch fixes the problem nicely, thanks!

**Comment by asmecher** [comment]
Thanks, I've released new packages to the plugin gallery for COinS for 3.3.0-x and 3.4.0-x with the fix included.
