### ISSUE TITLE
OJS 3.4.0.1 / 3.4.0.3 error tools/install.php

### ISSUE THREAD

**Issue by Mathewwss** [pkp/pkp-lib#9266]
Errors - tools/install.php (OJS 3.4.0.1 and 3.4.0.3)

Error 1

![29 August 2023_02 38 31](https://github.com/pkp/pkp-lib/assets/50458770/802394d9-4ae9-4035-8ae5-5a0fb823cc98)

The installer gives the SQLSTATE [2002] error, referring to the database connection.

After modifying the config.inc.php, correctly configuring the
database variables, the error changes.

Error 2

![29 August 2023_02 40 02](https://github.com/pkp/pkp-lib/assets/50458770/e6ae1ffb-ca83-4c54-9143-63c21cd57a28)

The installer tries to find a table and fails.

In OJS 3.3.0.14 it is not necessary to modify anything, when running the
tools/install.php the installation starts correctly.

I did not understand the reason for looking for the table, since I am running
a fresh install, so the database is empty.

Should the tables be created at installation ??

Solution?

**Comment by asmecher** [comment]
@Mathewwss, I can check whether the command-line installer is working. It's not often used. In the meantime, I'd suggest using the web-based installation tool.

**Comment by Mathewwss** [comment]
Ok, thanks.

PS: 

If you modify config.inc.php, configuring a non-empty database, the installation starts.

Before the end, an error occurs, precisely an error saying that the database It is not empty.

**Comment by asmecher** [comment]
@Mathewwss, applying https://github.com/pkp/pkp-lib/commit/abfd511eda63283dde31daab6a2fca7308953741.diff in the `lib/pkp` subdirectory should resolve the issue. Thanks for reporting!
