### ISSUE TITLE
OJS 3.0b2: Slight textual error in the Native XML Plugin

### ISSUE THREAD

**Issue by nmpx** [pkp/pkp-lib#927]
The text reads:

> Please select an XML file to upload and press "Start Upload". When the upload has completed, press "OK" to import the document into OMP.

I'm guessing the OMP should be OJS.

Honestly, just logging this so it isn't forgotten when this is put into production.

![bug12](https://cloud.githubusercontent.com/assets/5183702/11407544/7a1d45b8-9381-11e5-829c-3490f9160f3c.png)

**Comment by asmecher** [comment]
Fixed, thanks!
