### ISSUE TITLE
[OHS] error

### ISSUE THREAD

**Issue by infotegra** [pkp/pkp-lib#928]
Hello
I have installed the latest OHS version 2.3.2, but I always presents this error in the log / s:

 harvester2 has produced an error\n  Message: WARNING: Invalid argument supplied for foreach()\n  In file: /var/www/html/ohs/lib/pkp/classes/i18n/PKPLocale.inc.php\n  At line: 138

I have also blank page with Reading Tools (rtadmin) and not recorded in the log

I am installing the ohs on centos 7 there will be a problem?

**Comment by asmecher** [comment]
Hi @infotegra -- someone will respond to your query on the forum:
http://forum.pkp.sfu.ca/t/error-ohs-2-3-2-pkplocale-inc-php-line-138/5400

Please only use one means to contact us; otherwise it clutters our systems.
