### ISSUE TITLE
Inability to properly modify the Submission Forms 

### ISSUE THREAD

**Issue by henriquejsfj** [pkp/pkp-lib#9281]
**Describe the bug**

The tutorial [Add Custom Fields](https://docs.pkp.sfu.ca/dev/plugin-guide/en/examples-custom-field) says to do this way to add a field:
```php
if (!defined('FORM_MASTHEAD') || $form->id !== FORM_MASTHEAD) {
    return;
}
```
This pattern does not work with the Submissions Forms (in `classes/components/forms/submission/`) since they don't define any constant. 

Thus, to fit the pattern I would expect in [ForTheEditors.php](https://github.com/pkp/pkp-lib/blob/main/classes/components/forms/submission/ForTheEditors.php) something like:
```php
define('FORM_EDITORS', 'forTheEditors');

class ForTheEditors extends PKPMetadataForm
{
    public $id = FORM_EDITORS;
```

However, this pattern seems against the new [Namespaces and Constants](https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.4-release-notebook#namespaces-and-constants) convention. Following the new convention we would have:
```php
class ForTheEditors extends PKPMetadataForm
{
    public const ID = 'forTheEditors';
```

And the plugin code:
```php
if ($form::id !== ForTheEditors::ID) {
    return;
}
```

**What application are you using?**
 OJS version 3.4

**Additional Information**
I may do the changes with the solution you prefer, but I don't know how this would impact the hole system.
Besides, this is related with my previous [Issue #9045](https://github.com/pkp/pkp-lib/issues/9045).

**Comment by bozana** [comment]
Hi @henriquejsfj, just to be sure: is it not possible to modify the submission forms at all, or do you just say that the submission form is not fully conform to some of our goals? 
If the first is the case, what exactly is the problem? (except that there is no constant to check on, but one could check `if ($form->id !== 'forTheEditors') { return; }`, or?)
If second is the case: I believe @asmecher can best decide on that -- at the moment all form classes have the `public $id` attribute (which is equal to an old type constant), and if this needs to be changed, it is probably best to change it everywhere.

**Comment by henriquejsfj** [comment]
@bozana @asmecher ping

**Comment by bozana** [comment]
@henriquejsfj, sorry for the delay... we had a developer sprint and are first now back...
I will take a look/test...

**Comment by bozana** [comment]
@henriquejsfj, I found one thing: if you would like to display a new field on the step "For the Editors" the form field would need to have `'groupId' => 'default'`.  
Also, maybe the plugin [funding](https://github.com/ajnyga/funding/blob/master/FundingPlugin.inc.php) is a good example how one could add things there.
Does this help?
