### ISSUE TITLE
[OJS 3.4.0-3] Upgrade error, DOI related

### ISSUE THREAD

**Issue by ohilbig01** [pkp/pkp-lib#9282]
I got an error when upgrading from OJS 3.3.0-11 to OJS 3.4.0-3:

```
ERROR: Upgrade failed: DB: SQLSTATE[23000]: 
Integrity constraint violation: 1062 Duplicate entry '1--registrationAgency' for key 'doi_settings.doi_settings_unique' 
(SQL: insert into `doi_settings` (`doi_id`, `setting_name`, `setting_value`) values (1, registrationAgency, DataciteExportPlugin))
```

After switching from Datacite to Crossref my OJS 3.3 has in the submission_settings table entries with the setting_name "datacite::status" and also with the setting_name "crossref::status", both with the same submission_id and both with the value "registered". 
Such duplicate entries also exist for the setting_name "registeredDoi". 
Obviously the upgrader tries to fill the table doi_settings with values a second time, which goes wrong.

Also, I discovered a typo in ./classes/migration/upgrade/v3_4_0/I7014_DoiMigration.php on line 386: 

`{ if ($item['datacite::status'] === 'regisetered') {
`

I helped myself, as a workaround, by deleting the datacite entries in the submission_settings. So I could upgrade the OJS.

<hr>

PRs:
- ttps://github.com/pkp/ojs/pull/4033 (stable-3_4_0)

**Comment by asmecher** [comment]
@ewhanson, could you take a look at this one? Thanks!

**Comment by ewhanson** [comment]
Hi @ohilbig01, thanks for sharing the details.

Just to confirm my understanding of the issue, in OJS 3.3, you had previously had both the Datacite and Crossref plugins configured, leading to registration agency settings for each to be saved in the 3.3 database?

Thanks!

**Comment by ewhanson** [comment]
This fix will need to be addressed in the following place before merge:

- [ ] OJS `stable-3-4_0`
- [ ] OJS `main`
- [ ] OMP `stable-3-4_0`
- [ ] OMP `main`
- [ ] OPS `stable-3-4_0`
- [ ] OPS `main`

**Comment by ohilbig01** [comment]
Hi @ewhanson ,

thanks for your help.
We activated Crossref and deactivated Datacite. I don't think they were active at the same time. We also asked Crossref's support service to transfer the DOIs from Catacite to Crossref.

**Comment by ewhanson** [comment]
Hey @bozana, I have a draft of this work ready for OJS. Would you be able to give it a look? If this looks good, I'll apply the changes to OMP and OPS as well.

Thanks!

PRs:

- pkp/ojs#4033
- pkp/pkp-lib#9427

**Comment by bozana** [comment]
@ewhanson, this all looks good to me. I think we even do not need to consider OMP and OPS because there hasn't been DataCite and mEDRA plugin for them yet. Thus it all could go only into OJS :thinking:

**Comment by ewhanson** [comment]
@bozana, the current PRs for `stable-3_4_0` should be ready for merge. I still need to port the changes to `main`, but if this is holding up `3.4.0-4`, it could be merged before `main` is finished.
