### ISSUE TITLE
Typo in translation

### ISSUE THREAD

**Issue by claivaz** [pkp/pkp-lib#9285]
https://github.com/pkp/pkp-lib/blob/6bd4bdbc1beb9ab002caa4d9792d6034bd59624c/locale/fr_FR/submission.po#L428C1-L428C36

Must be:
msgstr "Biographies de l'auteur"

instead of:
msgstr "Bibliographies de l'auteur"

**Comment by asmecher** [comment]
@claivaz, the community manages translations of the software using Weblate (https://translate.pkp.sfu.ca/) -- you can update the translation there for the next 3.4.0-x release of OJS/OMP/OPS. See https://docs.pkp.sfu.ca/translating-guide/en/translate-software#update-an-existing-translation for details. Thanks for spotting this!
