### ISSUE TITLE
Error on reset password feature

### ISSUE THREAD

**Issue by diazsasak** [pkp/pkp-lib#9289]
**Describe the bug**
Hi all, i got error when filling email field and press "Reset Password" on forgot password feature. any help? thank you

**What application are you using?**
 OJS version 3.4.0-3

**Additional information**

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/u3572082/public_html/mysite.or.id/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1081 Stack trace: #0 /home/u3572082/public_html/mysite.or.id/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1081): count() #1 /home/u3572082/public_html/mysite.or.id/lib/pkp/classes/emailTemplate/DAO.php(173): Illuminate\Database\Query\Builder->whereIn() #2 /home/u3572082/public_html/mysite.or.id/lib/pkp/classes/emailTemplate/DAO.php(124): PKP\emailTemplate\DAO->fromRow() #3 [internal function]: PKP\emailTemplate\DAO->PKP\emailTemplate\{closure}() #4 /home/u3572082/public_html/mysite.or.id/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php(686): Generator->valid() #5 /home/u3572082/public_html/mysite.or.id/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(319): Illuminate\Support\LazyCollection->isEmpty() #6 /home/u3572082/public_html/mysite.or.id/lib/pkp/classes/emailTemplate/DAO.php(138): Illuminate\Support\LazyCollection->isNotEmpty() #7 /home/u3572082/public_html/mysite.or.id/lib/pkp/classes/emailTemplate/Repository.php(56): PKP\emailTemplate\DAO->getByKey() #8 /home/u3572082/public_html/mysite.or.id/lib/pkp/pages/login/LoginHandler.php(252): PKP\emailTemplate\Repository->getByKey() #9 [internal function]: PKP\pages\login\LoginHandler->requestResetPassword() #10 /home/u3572082/public_html/mysite.or.id/lib/pkp/classes/core/PKPRouter.php(334): call_user_func() #11 /home/u3572082/public_html/mysite.or.id/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest() #12 /home/u3572082/public_html/mysite.or.id/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route() #13 /home/u3572082/public_html/mysite.or.id/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch() #14 /home/u3572082/public_html/mysite.or.id/index.php(21): PKP\core\PKPApplication->execute() #15 {main} thrown in /home/u3572082/public_html/mysite.or.id/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 1081

<img width="855" alt="image" src="https://github.com/pkp/pkp-lib/assets/7880137/81dbbd8b-68ec-4ac5-b7cc-3abfb4f3e379">

**Comment by asmecher** [comment]
@diazsasak, I'd suggest starting on our support forum (https://forum.pkp.sfu.ca) for questions like this.

It looks to me like your "supported locales" list is not correct. You should be able to fix this by reviewing both your languages configuration in the individual journal, and the languages configuration in Site Administration. It might be that re-saving the settings there will resolve the problem.

If not, check the following settings in your database:

```sql
SELECT supported_locales FROM site;
SELECT journal_id, setting_value FROM journal_settings WHERE setting_name='supportedLocales';
```

**Comment by asmecher** [comment]
Closing.
