### ISSUE TITLE
1061 Duplicate key name 'static_page_settings_static_page_id'

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#9290]
**Describe the bug**
When trying to install OJS I get a `1061 Duplicate key name 'static_page_settings_static_page_id'` error. 

**What application are you using?**
 OJS `main` branch

**Additional information**
It seem that in main branch the line https://github.com/pkp/staticPages/blob/main/StaticPagesSchemaMigration.php#L42 is duplicated at line https://github.com/pkp/staticPages/blob/main/StaticPagesSchemaMigration.php#L48, causing this issue. 

---
**PR**

StaticPages: pkp/staticPages#78

**Comment by asmecher** [comment]
@defstat, is this still active, or did it get solved along the way?

**Comment by defstat** [comment]
@asmecher find [here](https://github.com/pkp/pkp-lib/issues/9290#issue-1888789172) a proposed PR for this. 

I removed the duplicate index declaration and I renamed the index from `static_page_settings_static_page_id` to `static_page_settings_static_page_id_index` to distinguish it from the foreign key that is also named `static_page_settings_static_page_id`.

**Comment by asmecher** [comment]
@defstat, I haven't seen this error myself, and I've installed OJS frequently since this was reported... Is there a particular combination of circumstances that causes this to crop up? (I'm worried that the proposed solution might leave two indexes on the same column.)

**Comment by defstat** [comment]
> @defstat, I haven't seen this error myself, and I've installed OJS frequently since this was reported... Is there a particular combination of circumstances that causes this to crop up? (I'm worried that the proposed solution might leave two indexes on the same column.)

@asmecher You are right, on my current setting (php 8.1, mysql  8.0.23, postgres 14.5) it seems that I can't reproduce this problem somehow. 

I am wondering why we need the second declaration of `$table->index(['static_page_id'], 'static_page_settings_static_page_id');` here. 

In any case we could close the issue and the PR and if it comes up again I can reopen it with a better description of how to reproduce it.

**Comment by defstat** [comment]
@asmecher I have investigated that a little deeper. 

The way the code is now, the `StaticPagesSchemaMigration` Migration is not completely executed. You can see that if you check the end result of the Migration - The `static_page_settings_pkey` index from the `$table->unique(['static_page_id', 'locale', 'setting_name'], 'static_page_settings_pkey');` is not getting created.

This is because the second `$table->index(['static_page_id'], 'static_page_settings_static_page_id');` statement does produce an exception which is handled [here](https://github.com/pkp/pkp-lib/blob/main/classes/plugins/Plugin.php#L725), but does not seem to be displayed to the user. The full exception message is the `"SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'static_page_settings_static_page_id' (Connection: mysql, SQL: alter table `static_page_settings` add index `static_page_settings_static_page_id`(`static_page_id`))"`

The code in the PR, by removing the second `$table->index(['static_page_id'], 'static_page_settings_static_page_id');` fixes the issue. The renaming part of the first `$table->index(['static_page_id'], 'static_page_settings_static_page_id'); ==> $table->index(['static_page_id'], 'static_page_settings_static_page_id_index');` is not necessary for this fix.

**Comment by asmecher** [comment]
@defstat, I'd suggest dealing with this in two pieces...
1. The specific corrections to the static pages schema migration, which should be fixed here, and
2. File the error suppression/missing error handling as a separate issue.

**Comment by defstat** [comment]
> @defstat, I'd suggest dealing with this in two pieces...
> 
> 1. The specific corrections to the static pages schema migration, which should be fixed here, and
> 2. File the error suppression/missing error handling as a separate issue.

@asmecher I resolved the review comments and created a new issue for the exceptions suppression

**Comment by asmecher** [comment]
Merged, thanks! On balance I think I won't back-port this to `stable-3_4_0`, in order to reduce potential discrepancies between database structures for the upgrade to 3.5. I think the old schema, though imperfect, won't cause problems for 3.4.0 (and prior) users.
