### ISSUE TITLE
Missing locale key site.upgradeAvailable.admin in OMP

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#9294]
**Describe the bug**
The locale key, `site.upgradeAvailable.admin`, is not present in OMP. This leads to a missing message in the site administration area.

**To Reproduce**
I'm not sure of the reproduction steps, but I the message is shown when `VersionCheck::checkIfNewVersionExists()` returns `true`.

1. Login as admin
2. Go to Administration area

**What application are you using?**
OMP `main` branch running a `stable-3_4_0` database.

**Additional information**
![upgrade-available](https://github.com/pkp/pkp-lib/assets/2306629/8b3f5b8d-8127-4a4c-b4d1-7986474cbf04)

**Comment by kaitlinnewson** [comment]
This looks like a case of just needing to move the locale key to pkp-lib from OJS, but it's not easy to reproduce because `show_upgrade_warning` is not typically set in the OMP config file/template (see also https://github.com/pkp/pkp-lib/issues/8543).

**Comment by kaitlinnewson** [comment]
PRs ready for review @asmecher:

3.4:
- pkp-lib 3_4_0: https://github.com/pkp/pkp-lib/pull/10307
- OJS 3_4_0: https://github.com/pkp/ojs/pull/4399
- OMP 3_4_0 (submodule update only): https://github.com/pkp/omp/pull/1672

main:
- pkp-lib main: https://github.com/pkp/pkp-lib/pull/10308
- OJS main: https://github.com/pkp/ojs/pull/4400
- OMP main (submodule update only): https://github.com/pkp/omp/pull/1673

**Comment by asmecher** [comment]
@kaitlinnewson, unfortunately the locale key makes explicit reference to OJS, and would need to be generalized in order to be moved to the `pkp-lib` shared library.

**Comment by kaitlinnewson** [comment]
@asmecher I've updated the list of PRs above, ready for another review. Since we are not actively translating the 3.3 branch, I've copied over the full text from OJS and updated the strings to OMP where possible.

For 3.4/main, I made a small change to the english text so we aren't using "here" links to follow better accessibility practices.

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson, looks good! Were those stable-3_3_0 translations adapted manually from OJS translations, or machine translated, or something else? Generally speaking, it's good to mark them [fuzzy](https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html) so anyone working with translation tools can give them a review.

**Comment by asmecher** [comment]
:arrow_up: Sorry, I see you specified that these were adapted manually. Should be good to go!
