### ISSUE TITLE
Implement sandbox mode

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9296]
**Describe the bug**
When taking an installation from a production environment into a testing environment, certain activities should be prevented -- sending emails, depositing issues/articles, etc.

So far we have maintained lists of individual features to disable, but it would be better to have a single configuration setting (e.g. in `config.inc.php`) to refer to.

(To be considered: what about making LessCSS cache less obtrusive for developers? The LessCSS compilation takes too long to disable entirely, but perhaps sandbox mode could consider setting no-cache directives and letting e.g. inotifywait be used on the developer side to automatically delete cache files when a .less file changes.)

Things to disable:
- Emails
- CrossRef deposits
- DataCite deposits
- ORCiD
- PayPal

**PRs**
#### Stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9616
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4143
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/631
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1516
[crossref-ojs](https://github.com/pkp/crossref-ojs) --> https://github.com/pkp/crossref-ojs/pull/43
[crossref-ops](https://github.com/pkp/crossref-ops) --> https://github.com/pkp/crossref-ops/pull/35
[orcidProfile](https://github.com/pkp/orcidProfile) --> https://github.com/pkp/orcidProfile/pull/310

#### main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9699
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4175
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/632
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1517
[orcidProfile](https://github.com/pkp/orcidProfile) --> https://github.com/pkp/orcidProfile/pull/311
[crossref-ojs](https://github.com/pkp/crossref-ojs) --> https://github.com/pkp/crossref-ojs/pull/44
[crossref-ops](https://github.com/pkp/crossref-ops) --> https://github.com/pkp/crossref-ops/pull/36

#### Stable-3.4.0
[acron](https://github.com/pkp/acron) --> https://github.com/pkp/acron/pull/9
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9747
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4197 [TEST ONLY]

#### PKP Doc
[pkp-docs](https://github.com/pkp/pkp-docs) --> https://github.com/pkp/pkp-docs/pull/1178

**Comment by asmecher** [comment]
(related but different: https://github.com/pkp/pkp-lib/discussions/8132)

**Comment by touhidurabir** [comment]
@asmecher please review the PRs at https://github.com/pkp/pkp-lib/issues/9296#issue-1892311185 . Still need to forward port to `crossref-ops` and `main` and will do once we confirm the changes .

**Comment by asmecher** [comment]
Thanks, @touhidurabir! Rather than a bunch of individual sandbox settings for each feature, what I think we're looking for is a single `sandbox` setting, e.g. in `config.inc.php`:

```
[general]

; Turn sandbox mode to On in order to prevent the software from interacting with outside systems.
; Use this for development or testing purposes.
sandbox = Off
```

When turned `On`, this will disable everything all at once -- emails, CrossRef, etc. -- with just a single setting.

That way admins who are testing can change just a single setting in order to work confidently with test installs, and it still leaves individual integrations with their own sandbox feature support (e.g. PayPal's test mode).

**Comment by touhidurabir** [comment]
@asmecher updated PR as per the suggestion . Please review it again at https://github.com/pkp/pkp-lib/issues/9296#issue-1892311185 and if all ok, I will forward port to `OPS/OMP` and `main/stable-3.4.0` branches .

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I've made a couple of comments that need to be implemented wherever you use the sandbox feature:
- An error_log should be added to note the skipped action, and
- The only action that should be skipped is the specific interaction with the external service; the checks here happen too early and too generally.

**Comment by touhidurabir** [comment]
@asmecher I have update the PR as per suggestion . Please take a look again .

**Comment by asmecher** [comment]
Thanks, I've reviewed each of the PRs.

**Comment by asmecher** [comment]
Thanks, @touhidurabir, I've just made one or two minor comments. This also needs porting to OMP and OPS -- and then forward to `main`.

**Comment by asmecher** [comment]
Thanks, @touhidurabir! All merged except https://github.com/pkp/orcidProfile/pull/311, where I've asked @ewhanson for his preference.

**Comment by asmecher** [comment]
All resolved, thanks!

**Comment by touhidurabir** [comment]
@asmecher Based on the observation of the current [sandboxing](https://docs.pkp.sfu.ca/admin-guide/en/deploy-sandbox) doc, the following enhancement possible : 
1. [current implementation](https://github.com/pkp/pkp-lib/pull/9616/files#diff-3490bdf027af7363a9ecbe27192dd5b8d7695efc583fa64ee24f05af8ee3b298R120-R126) of `email` sandbox does not sent any email, even to the log drive . we can make it default to `log` driver when sandbox mode is set
2. it is possible to easily disable the schedule task with minimum code level change when sandbox mode is set
3. we can disable the job execution process (`job runner`, `cron` and via `run` command) with very little code change . If an installation has `worker` already running, then it's not possible to disable instantly by setting the sandbox mode(that need intervention from installation server level) but possible to restrict the initiation of new `worker` after the sandbox mode set . 
4. The `Acron` plugin's task execution can be disabled with very little code update for sandbox mode . 

All the above enhancement will removed all the extra steps necessary in current sandbox doc and admins can set it up with a single config change . 

BTW, the current behaviour of `sandbox` mode(functionality that it disable) is described at https://github.com/pkp/pkp-lib/issues/9296#issue-1892311185 . 

However, disabling all of these with a single sandbox setting my not be desirable for all situations as mentioned at https://github.com/pkp/pkp-lib/issues/9296#issuecomment-1724973175 . for example , some job or task need to run even in sandbox mode for desired outcome and only need to disable few of the functionality like email, payment, crossref, etc . For that purpose may be we should think about another `config` settings like `sandbox_functionalities` or a totally separate sandbox config option where each functionality can be individually set to sandbox mode .

**Comment by touhidurabir** [comment]
@asmecher please review the PRs at https://github.com/pkp/pkp-lib/issues/9296#issue-1892311185 which now consider the septs at https://docs.pkp.sfu.ca/admin-guide/en/deploy-sandbox

**Comment by asmecher** [comment]
The `stable-3_4_0` PRs have been merged and forward-ported to `main`; it's just the docs changes that need addressing before this can be closed.

**Comment by touhidurabir** [comment]
@asmecher I have merged your PR for doc change .

**Comment by asmecher** [comment]
Merged the last PR, thanks!
