### ISSUE TITLE
Not possible to edit a publication from a CLI tool

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9298]
**Describe the bug**
Trying to update/edit a publication from within a CLI tool (i.e. e.g. via CLI -- also executing a migration from CLI) there is an error:
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ojs_stable2`.`event_log`, CONSTRAINT `event_log_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE) in .../lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:545`

The reason:
In this line: https://github.com/pkp/pkp-lib/blob/stable-3_4_0/classes/publication/Repository.php#L405
the part `Validation::loggedInAs()`
is returning 0 (=false) and not null, and userId = 0 does not exist.
Thus, that part should actually be `Validation::loggedInAs() != 0 ?  Validation::loggedInAs() : $userId`

PRs:
stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/9299
- https://github.com/pkp/ojs/pull/4039 (only submodule update)
- https://github.com/pkp/omp/pull/1459 (only submodule update)
- https://github.com/pkp/ops/pull/568  (only submodule update)

main:
- https://github.com/pkp/pkp-lib/pull/9311
- https://github.com/pkp/ojs/pull/4041 (only submodule update)
- https://github.com/pkp/omp/pull/1460 (only submodule update)
- https://github.com/pkp/ops/pull/570 (only submodule update)

**Comment by bozana** [comment]
@Vitaliy-1, could you take a look at the PR?

**Comment by Vitaliy-1** [comment]
Thanks @bozana, I recall that `Validation::loggedInAs()` should return null or int. It's possible that I've made a mistake in the method's body. Would it work if just change this line https://github.com/pkp/pkp-lib/blob/6bd4bdbc1beb9ab002caa4d9792d6034bd59624c/classes/security/Validation.php#L413 to `return null`?

**Comment by bozana** [comment]
Hi @Vitaliy-1, yes, that solves the problem :-)
I wasn't sure if it was for some reason an intention to have `return false`... 
:+1: 
OK so?

**Comment by Vitaliy-1** [comment]
Thanks! Yes, looks good. I don't see where the code relies on this method to return specifically `false`.
