### ISSUE TITLE
Remove user email address confirmation from password reset message

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#9301]
**Describe the bug**
The current password reset message confirms the existence of a user account with the provided email address:
"A confirmation has been sent to your email address. Please follow the instructions in the email to reset your password."

If a site visitor is fishing for valid emails and no user exists with the provided email address, the following is displayed:
"No user exists with the specified email address."

The above approach provides information about registered users and their email addresses to unauthenticated site visitors. This doesn't meet [OWASP best practices](https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html#forgot-password-service) and likely violates GDPR.

User feedback should be updated to a generic message for both valid and invalid email addresses, e.g. "If a user exists with this email address a password reset email has been sent to that email address."

**To Reproduce**
1. Go to 'Forgot my password'
2. Enter known user account email address.
3. Enter invalid email address.

**What application are you using?**
 All versions of OJS, OMP and OPS.

**PRs**
#### Stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9317
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4046 [TEST ONLY]

#### Main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9519
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4103 [TEST ONLY]

#### Stable-3.3.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9520
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4104

**Comment by asmecher** [comment]
(@touhidurabir, this might make a good small task to work in with the larger stuff you're working on)

**Comment by touhidurabir** [comment]
@asmecher ok, I will take a look at this .

**Comment by touhidurabir** [comment]
@asmecher can you review the PR at https://github.com/pkp/pkp-lib/issues/9301#issue-1894620042 . just a very minor change and once finalise, I can forward port to `main` and back port to `stable-3.3.0` .

**Comment by asmecher** [comment]
@touhidurabir, there's a merge conflict there; can you rebase the PR to resolve?

**Comment by touhidurabir** [comment]
@asmecher rebased the PR and resolve the conflict .

**Comment by asmecher** [comment]
Thanks, @touhidurabir, and sorry for the wait!

Just to confirm that I know what's needed --

1. https://github.com/pkp/pkp-lib/pull/9317 needs to be merged, and
2. forward-ported to `main`

Is that correct?

**Comment by touhidurabir** [comment]
@asmecher this need to be back ported to `3.3.0` and forward port to `main` . But before that we need to finalise the changes that mentioned at https://github.com/pkp/pkp-lib/pull/9317#discussion_r1338229364 .

**Comment by touhidurabir** [comment]
@asmecher All PRs are done, see at https://github.com/pkp/pkp-lib/issues/9301#issue-1894620042

**Comment by asmecher** [comment]
All merged -- thanks, @touhidurabir!
