### ISSUE TITLE
Internal PHP locale fails to be defined under Windows and others

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9302]
**Describe the bug**
The [locale format used by Windows](https://learn.microsoft.com/en-us/cpp/c-runtime-library/language-strings?view=msvc-170) uses a `-` instead of `_`, therefore the call to `setlocale()` should consider the OS or retry with another combination (sounds like the best choice).

Besides this, when the OS doesn't have the expected locale, it fails silently and keeps the last locale that worked. Which is bad for long-lived processes (e.g. PHP-FPM).

**What application are you using?**
OJS 3.3

**Comment by asmecher** [comment]
@defstat, have you experienced this, or is it maybe something that gets configured/mapped with WSL?

**Comment by jonasraoni** [comment]
I've tested on my machine, I can create a small PR later :)

**Comment by defstat** [comment]
@asmecher I have not experienced that. @jonasraoni can you point out when you are experiencing it?

**Comment by jonasraoni** [comment]
If you change the PHP's internal locale to an invalid value, some functions that depend on it, will not work properly (under WSL should work, as it uses a Linux distribution).

```php
setlocale(LC_ALL, 'fr_FR');
echo strftime('%B'); //September
setlocale(LC_ALL, 'fr-FR');
echo strftime('%B'); //septembre
```

**Comment by defstat** [comment]
That should have affected ojs also, if it was running under windows (not WSL), right?

**Comment by jonasraoni** [comment]
@asmecher Regarding `*nix`... For the `setlocale()` to work properly, it's expected from the server to have the needed locales at `locale -a` (we currently have this issue on our servers). So in the long run, I think we should avoid depending on the `setlocale()` 🤔

On another hand, such functions work fine: https://www.php.net/manual/en/class.intldateformatter.php.

**Comment by defstat** [comment]
@jonasraoni I have never experienced issues with locales on my windows installations (I am exclusively working on windows for ojs for some years now).. 

But something might have changed on the php version that you are working on, or I may have missed something on the certain process that you are experiencing this...

**Comment by jonasraoni** [comment]
Here I've used an updated Windows 11 + PHP 8.2.
I've just ran `php -a`, then pasted [the code above](https://github.com/pkp/pkp-lib/issues/9302#issuecomment-1721526514), and got `September`, then `septembre`.

**Comment by defstat** [comment]
Do you have an ojs example to demonstrate the problem so I can test it on the software?

**Comment by jonasraoni** [comment]
It's possible to simulate this way: https://github.com/pkp/pkp-lib/issues/9303

Customize the date format to display the month/week name, then change the language.

**Comment by jonasraoni** [comment]
I'll probably get this merged tomorrow, there's nothing special IMHO.

**Comment by asmecher** [comment]
@jonasraoni, I'm seeing a lot of warnings of the form:
```php
Failed to set locale "en.utf8", ensure that all locales enabled in the application are available in your operational system
```
My system is a pretty vanilla Ubuntu system. I also see the warnings in the Travis error log. We might need to revisit how we're mapping our translation locales into `setlocale`.

**Comment by jonasraoni** [comment]
@asmecher Yes! I've seen those warnings :)

Looks like our code isn't very reliant on the `setlocale()`. The environment variables are used by internally the C functions, so it's a bit difficult to understand exactly which PHP functions are affected. It's possible to have an idea by watching such links https://en.cppreference.com/w/c/locale/setlocale.

I can say the `setlocale()` has never worked at the PS servers, we just have the `en_US`, `POSIX` and `C`. So far, I haven't seen issues, besides the date ones that I've flagged recently.

**Comment by jonasraoni** [comment]
So, in general I think we can't rely on this function. It can be used for improvements though (e.g. sorting a list of strings properly according to the locale).

I see these two ways:
- Drop the `setlocale()`/`putenv()` and depend uniquely on the `C` locale, and any problem that arises will have to be solved by code/external libraries, but in a more predictable way.
- Look for compatible matches at `ResourceBundle::getLocales('')`, and append them to the list, which isn't perfect (e.g. en_US vs en_UK), but will do it.

**Comment by asmecher** [comment]
@jonasraoni, if setlocale has been frequently failing e.g. on PKP|PS servers, then these changes to `stable-3_3_0` and `stable-3_4_0` are going to flood our error logs (and probably everyone else's). Maybe it would be better to remove the `error_log` function and just let the call fail, if it doesn't cause problems.

**Comment by jonasraoni** [comment]
@asmecher
`stable-3_3_0`: It's possible to fix at the server, by installing the missing locales, so it's ok to keep the `error_log()`. But I'll create a PR to drop it.
`stable-3_4_0`: We've got to take a decision, because the `en.utf8` just works in Windows.

I'll add my preferences to the PR (i.e. the effects of not setting up a proper locale are so minimal that nobody has noticed), then we can keep discussing :)

**Comment by jonasraoni** [comment]
- `stable-3_4_0`
- https://github.com/pkp/pkp-lib/pull/9700
- `stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/9701

**Comment by asmecher** [comment]
Thanks, @jonasraoni. I'm OK with the change for `stable-3_3_0`, but am not sure about the effect of the change to `setlocale` in the `stable-3_4_0` branch. I've added a comment on that PR. You'll also need to make a similar PR for `main` too, right?

**Comment by asmecher** [comment]
I've reverted the changes to `stable-3_3_0`, and merged https://github.com/pkp/pkp-lib/pull/9700 to `stable-3_4_0` and cherry-picked it forward to `main`. Thanks, @jonasraoni, and next time, please make sure these sorts of changes go through a code review, especially if they're changing something fundamental in `stable-3_3_0` and `stable-3_4_0`.
