### ISSUE TITLE
OJS 3.3 Fatal Error on PHP 8

### ISSUE THREAD

**Issue by kswro** [pkp/pkp-lib#9307]
**Describe the bug**
A fatal error occurs if, in OJS 3.3.0 (tested on build 15), the **Web Cache setting is active** under **PHP 8** (8.0, 8.1, 8.2). This doesn't happen if I use PHP 7.4.

**To Reproduce**
1. PHP 8
2. web_cache is On (config.inc.php)
3. Visit site

**What application are you using?**
OJS 3.3.0-15

**Log**
```
PHP Fatal error:  Uncaught ArgumentCountError: mktime() expects at least 1 argument, 0 given in /home/.../public_html/lib/pkp/classes/core/Dispatcher.inc.php:226

Stack trace:
#0 /home/.../public_html/lib/pkp/classes/core/Dispatcher.inc.php(226): mktime()
#1 /home/.../public_html/lib/pkp/classes/core/Dispatcher.inc.php(122): Dispatcher->_displayCached()
#2 /home/.../public_html/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch()
#3 /home/.../public_html/index.php(68): PKPApplication->execute()
#4 {main}
  thrown in /home/.../public_html/lib/pkp/classes/core/Dispatcher.inc.php on line 226
```

**Comment by asmecher** [comment]
Hi @kswro! The short answer is that the `web_cache` is known to be broken and should not be used. We have some discussion/early work on a better caching toolkit on https://github.com/pkp/pkp-lib/issues/7111; I'll leave this issue open in the meantime in case anyone cares to work on it. (But I don't recommend it.)

**Comment by jonasraoni** [comment]
Fixed by https://github.com/pkp/pkp-lib/commit/11cc5806d1db7ca30401da826cea1509b7a3e19b
