### ISSUE TITLE
OJS 3.4 Editorial Activity: "Accept and Skip Review" does not mark article as "Accepted"

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#9310]
**Describe the bug**
When accepting a submission without review the submission is not counted as "Accepted" in the editorial activity statistics. It is only counted as "Accepted" in case the review process was initiated.

**To Reproduce**
1. Go to "Editorial activity" and see the number of "Submissions Accepted"
2. Create a new submission
3. Go to the editorial workflow and click "Accept and Skip Review"
4. Go to "Editorial activity" and see that the number of "Submissions Accepted" didn't increase (as is the behaviour in OJS 3.3)

**What application are you using?**
 OJS 3.4.0.3

<hr>

PRs:
stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/9318
- https://github.com/pkp/ojs/pull/4047 (only submodule update)
- https://github.com/pkp/omp/pull/1462 (only submodule update)
- https://github.com/pkp/ops/pull/573 (only submodule update)

main:
- https://github.com/pkp/pkp-lib/pull/9378
- https://github.com/pkp/ojs/pull/4055 (only submodule update)
- https://github.com/pkp/omp/pull/1468 (only submodule update)
- https://github.com/pkp/ops/pull/576 (only submodule update)

**Comment by bozana** [comment]
@jonasraoni, do you maybe remember if this needs to be so, and why have we decided to be so, or if "Accept and Skip Review" should be counted as well?

**Comment by jonasraoni** [comment]
@bozana I've initially written a SQL query to retrieve the statistics (performance purposes), then Nate decided to break the code into an object-oriented approach. I'm not sure when this was introduced, but it's clearly a bug and it will probably need to be addressed at 3.3 as well.

**Comment by ronste** [comment]
> It seems 3.3 is OK, correct @ronste? I see the code is different -- those decision constants have changed in 3.4....

Yes, seems to be a 3.4 bug only.

**Comment by bozana** [comment]
@jonasraoni, could you take a look at the PR above?
