### ISSUE TITLE
[UI] Make grid row dropdown caret styles generalisable and accessible

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#932]
The dropdown caret for grid rows with actions has a couple of problems that need to be sorted.

- It's too small on some screens. Some people don't see it as a dropdown caret.
- It needs an actual element (rather than :psuedo element) in order to be focusable and therefore accessible to keyboard users.
- Right now we have to position it and the other content in the grid awkwardly using over-prescribed CSS. The markup should allow us to align it and its sibling content in a generalisable manner.

The actions are defined [here](https://github.com/pkp/pkp-lib/blob/omp-stable-1_1_1/templates/controllers/grid/gridRow.tpl#L30).

**Comment by asmecher** [comment]
@NateWr, I've cherry-picked the commits (both pkp-lib and omp) and fixed some of the wait conditions that were causing the tests to fail.

@willinsky, I think the points at the start of this entry address some of the things you'd identified in your postings?
