### ISSUE TITLE
[OJS 3.4] Document CGIPassAuth setting for API Authorization

### ISSUE THREAD

**Issue by kswro** [pkp/pkp-lib#9320]
**Describe the bug**
I am unable to authenticate to the REST API via the Authorization Header as in the page https://docs.pkp.sfu.ca/dev/api/ojs/3.4#tag/Authentication (403 Forbidden).

```
> GET /journal/api/v1/issues?count=4 HTTP/1.1
> Host: ojs.dvl.to
> User-Agent: insomnia/2023.2.0
> Cookie: OJSSID=1669db1b3b95485e42542709da720e2f
> Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ImNkMGQ1M2QxMmM3ZDY1YTA0YmE4Yzk1YjdlZGM3MWNiOTcwY2MxNzUi.XzQKQmNOdUdjvtSKa30yjQaEh6Cj9AmSYIGLJwyUMYk
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 403 Forbidden
< Date: Mon, 25 Sep 2023 06:13:43 GMT
< Server: Apache/2.4.54 (Unix) OpenSSL/3.0.7
< X-Powered-By: PHP/8.2.1
< Via: 1.1 (null) (apache/2.4.54)
< Transfer-Encoding: chunked
< Content-Type: application/json
```

But, if authentication uses the apiToken parameter query, the connection to the REST API can be established (200 OK).

```
> GET /journal/api/v1/issues?count=4&apiToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ImNkMGQ1M2QxMmM3ZDY1YTA0YmE4Yzk1YjdlZGM3MWNiOTcwY2MxNzUi.XzQKQmNOdUdjvtSKa30yjQaEh6Cj9AmSYIGLJwyUMYk HTTP/1.1
> Host: ojs.dvl.to
> User-Agent: insomnia/2023.2.0
> Cookie: OJSSID=1669db1b3b95485e42542709da720e2f
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200 OK
< Date: Mon, 25 Sep 2023 06:19:03 GMT
< Server: Apache/2.4.54 (Unix) OpenSSL/3.0.7
< X-Powered-By: PHP/8.2.1
< Access-Control-Allow-Origin: *
< Via: 1.1 (null) (apache/2.4.54)
< Content-Length: 25
< Content-Type: application/json
```

**To Reproduce**
1. Fresh Install
2. Set api_secret_key (config.inc.php)
3. Add API Token from user profile
4. Add the API Token in an Authorization header with every request made to the API

**What application are you using?**
OJS 3.4.0-3

**Additional information**
Tested on production server and new (fresh) local installation.

**Comment by touhidurabir** [comment]
Unable to produce the issue in the latest stable 3.4.0-3 for local testing . Both the Authorization header and apiToken query param works fine . 

@kswro I see that you are using insomnia api client app for testing and same for me . see the screenshot below 
<img width="1376" alt="CleanShot 2023-09-25 at 16 59 54@2x" src="https://github.com/pkp/pkp-lib/assets/2587979/ff700a6d-0bcc-47e5-98b7-1d0cc9cf6d71">

do you see any error in the error log file ?

**Comment by kswro** [comment]
Hello @touhidurabir 

Thank you for your reply. I didn't find any error logs on PHP and Apache.

However, I have found a solution to this problem. From [this page](https://stackoverflow.com/questions/17018586/apache-2-4-php-fpm-and-authorization-headers) I learned that various Apache modules will strip the Authorization header, usually for "security reasons".

So, based on the same source, I added the line below to the .htaccess file in my OJS public folder and now I can connect to the REST API via authorization header:
`CGIPassAuth on`

Apart from the above lines, I also tried using other alternatives as below which also solved the problem.
```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

FYI, I used Apache >2.4.54, PHP 8.2 (FPM) in this test.

Based on what I experienced ([and many others](https://stackoverflow.com/questions/26475885/authorization-header-missing-in-php-post-request)), do you think the above problems and solutions can be added to the [documentation](https://docs.pkp.sfu.ca/dev/api/ojs/3.4#tag/Authentication)?

**Comment by touhidurabir** [comment]
@kswro I will discuss with other dev team members to see if it is possible to add few details regarding this in the doc .

**Comment by orcalator** [comment]
You should really add this note because i also experienced same problem. If i didn't find this post i'd be spending a lot of time investigating what's going on. GG @kswro.

**Comment by kaitlinnewson** [comment]
PRs for review:

- OJS 3.4: https://github.com/pkp/ojs/pull/4481
- OJS main: https://github.com/pkp/ojs/pull/4482

@ewhanson are you the best person to review/merge this change to the API docs? I can also make the PR to the docs hub once approved.

**Comment by ewhanson** [comment]
@asmecher and @kaitlinnewson, I've reviewed and merged the changed, thanks!

**Comment by asmecher** [comment]
Thanks, @ewhanson and @kaitlinnewson!
