### ISSUE TITLE
Web caching occasionally generates a fatal error on PHP8

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#9334]
**Describe the bug**
This is probably a low priority issue because not many people use the web_cache feature in OJS or OMP, but occasionally the `_displayCached` method in `classes/core/Dispatcher.inc.php` will log a fatal error with:

`[Wed Sep 27 14:57:41.224758 2023] [proxy_fcgi:error] [pid 712321:tid 140703581591104] [client 84.211.110.164:54828] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0 in lib/pkp/classes/core/Dispatcher.inc.php:219`

if the file it is trying to fetch `filesize` from does not exist for some reason.  Possibly if the cache was recently cleared?  It only appears sporadically.  Suggest changing that bit of code to use a variant of `file_get_contents` or similar.

**To Reproduce**
1. enable web_cache
2. probably load the site a lot and clear the cache occasionally?  It is hard to reproduce.

**What application are you using?**
 OMP 3.3.0.14

**Comment by asmecher** [comment]
@jnugent, I'm going to close this in favour of https://github.com/pkp/pkp-lib/issues/9307 -- that's a slightly different error message, but stems from the same underlying cause, which is that `web_cache` is not currently maintained.
