### ISSUE TITLE
Poor SQL performance for ReviewFormDAO::getActiveByAssocId()

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#935]
When testing access to editing a Journal Section in OJS 2.4, I'm finding slow performance on the query in `ReviewFormDAO::getActiveByAssocId()`.

In a sample with 37 review_forms records and 12,133 review_assignments records, on MySQL 5.1, the [as-is query with two LEFT JOINS](https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/classes/reviewForm/ReviewFormDAO.inc.php#L279-L292) runs for 1:18.93.

A modified query with a single LEFT JOIN and an OR condition runs in 0:00.05.
```
SELECT rf.*
   FROM review_forms rf
    LEFT JOIN review_assignments rac ON (
     rac.review_form_id = rf.review_form_id AND
     (rac.date_confirmed IS NOT NULL OR (rac.date_confirmed IS NULL AND rac.date_notified IS NOT NULL))
    )
   WHERE rf.assoc_type = ? AND assoc_id = ? AND rf.is_active = 1
   GROUP BY rf.assoc_type, rf.assoc_id, rf.review_form_id, rf.seq, rf.is_active
   ORDER BY rf.seq
```

A modified query with a subquery runs in 0:00.0006.
```
SELECT rf.*
   FROM review_forms rf
   WHERE rf.assoc_type = ? AND assoc_id = ? AND rf.is_active = 1 AND rf.review_form_id IN
    (SELECT rac.review_form_id FROM review_assignments rac WHERE
     rac.review_form_id = rf.review_form_id AND
     (rac.date_confirmed IS NOT NULL OR (rac.date_confirmed IS NULL AND rac.date_notified IS NOT NULL))
    )
   ORDER BY rf.seq
```

Can someone with Postgres validate these alternate syntaxes and runtimes?

**Comment by asmecher** [comment]
@ctgraham, reviewing the SQL and this change looks good to me.

Both formulations work in PostgreSQL (testing for syntax, not for correct results).

Personally I try to avoid subqueries but I suspect that's a historical aversion and no longer relevant.

**Comment by ctgraham** [comment]
One potential problem with subqueries is that MySQL and Postgres differ on whether `NOT IN (NULL)` is true or false/undefined.  That oddity is still relevant, to my knowledge.

Since I see multiple other instances of double `LEFT JOIN`s in this file, some of which depend on a negative match, I suggest `EXISTS` / `NOT EXISTS` to the rescue.  Hopefully this is as efficient in Postgres as it is in Mysql.

**Comment by ctgraham** [comment]
Hmmmm... I'm pretty sure the original lines in question are completely spurious.  `SELECT a.* FROM a LEFT OUTER b LEFT OUTER c WHERE a.* GROUP BY a.*` is effectively a very slow `SELECT a.* FROM a WHERE a.*`

**Comment by asmecher** [comment]
Huh. Yep, you're right -- and that explains why the query was so poorly-performed.

**Comment by ctgraham** [comment]
Resolved.
