### ISSUE TITLE
Update country codes

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#936]
These need updating. See: forum.pkp.sfu.ca/t/fixed-bug-in-contry-code-for-serbia/5334/5

**Comment by asmecher** [comment]
@mtub, could you look at this pull request?
https://github.com/pkp/pkp-lib/pull/937

**Comment by mtub** [comment]
@asmecher, these are lots of changes - what's the source of the translated versions? Just curious, but when we refer to the ISO list it might be a could idea to have more or less authoritative lists in other languages as well (the ISO list is only available in English and French). My suggestion: the respective lists on Wikipedia, e.g. https://ca.wikipedia.org/wiki/ISO_3166-1

**Comment by mtub** [comment]
I think we should agree on one way of sorting these files - the languages are sorted by code, the countries are sorted, well, mostly by (translated) name. I am tempted to reorder the countries.xml files (because it makes comparing them easier), but people might prefer a list alphabetically sorted by translated name of that country.

**Comment by asmecher** [comment]
@mtub, I had a hard time finding a machine-actionable resource that was available in most languages, and ended up using the source of the Debian iso-codes package:
https://packages.debian.org/sid/iso-codes
I recommend that we don't do any local maintenance of these files at all -- simply refresh them from upstream sometimes. If we need sorting, it should be added to the conversion script (`tools/poToCountries.php` in the OJS repo).

**Comment by mtub** [comment]
Agreed, @asmecher. May I suggest that we include a reference to the source (Debian) and a warning? Maybe something like "Please don't edit or translate. This file is automatically generated using the ISO 3166 files of Debian's iso-codes package (https://packages.debian.org/sid/all/iso-codes)."

**Comment by asmecher** [comment]
Also, a snippet to convert the English-language version of the XML file from the iso-codes package:

    $f = simplexml_load_file('/path/to/iso_3166.xml');
    foreach ($f->children() as $c) {
            if ($c->attributes()->date_withdrawn) continue;
            echo "\t<country name=\"" . $c->attributes()->name . '" code="' . $c->attributes()->alpha_2_code . "\"/>\n";
    }

**Comment by asmecher** [comment]
@mtub, I've updated the PR, adding "do-not-edit" warnings among other things. Mind taking another look? If it's OK, I'll then move the poToCountries.php tool to the shared library so that everything will be shared between OJS and OMP, and then back-port to OJS stable for the 2.4.8 release.

**Comment by mtub** [comment]
This looks good and ready to merge as far as I can tell, @asmecher. Will be a relieve to have that list automatically compiled for all locales.

**Comment by asmecher** [comment]
Done! Thanks, @mtub.
