### ISSUE TITLE
Translation performance improvement

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9364]
## Problem
Using xdebug I noticed that lots of time was spent on calculating following key, which literally was calculated for every translation call `__.(...))`.
```
$key = __METHOD__ . static::MAX_CACHE_LIFETIME . array_reduce(array_keys($this->paths), fn (string $hash, string $path): string => sha1($hash . $path . filemtime($path)), '');
```

## Solution
Did small refactor to make key calculation faster and happen only if needed. (PR will be attached shortly)

## Potential improvement in future
There is still one performance opportunity. That new LocaleBundle gets created multiple times during the request (in my local setup 3 times). And reason is that `__.()` is called before all locale paths from plugins are registered. Example is `init` function of default theme:
```
    public function init()
    {
        // Register theme options
        $this->addOption('typography', 'FieldOptions', [
            'type' => 'radio',
            'label' => __('plugins.themes.default.option.typography.label'),

```
Every time new path is registered the LocaleBundle gets removed and needs to be loaded from cache again.

To solve this problem I think it would require to basically decouple locale path registering from plugin registration process. So at first all locale paths would register before running actual plugin registration.

Given that `addLocaleData` is called on different places depending on plugin category - it would be likely breaking change for plugins.

**Comment by jardakotesovec** [comment]
pkp-lib PR: https://github.com/pkp/pkp-lib/pull/9365

And performance different (unit is % of overall time):
article landing page:  
  before: 8.42%
  after: 2.22%
submissing listing:
  before: 11.74%
  after: 3.96%

Submission After
<img width="1868" alt="perf_submission_listing_after" src="https://github.com/pkp/pkp-lib/assets/1590681/2c523def-4b62-4023-92a7-d68928eb927a">
Submission Before
<img width="1858" alt="perf_submission_listing_before" src="https://github.com/pkp/pkp-lib/assets/1590681/53a980c2-e213-466d-ab22-aea4788cfcd5">
Article After
<img width="1871" alt="perf_article_after" src="https://github.com/pkp/pkp-lib/assets/1590681/69ca27e3-9e12-469f-a21a-c04e942d09e6">
Article Before
<img width="1716" alt="perf_article_before" src="https://github.com/pkp/pkp-lib/assets/1590681/e8067139-1516-4aa2-9ce4-6608a52c90be">

**Comment by jonasraoni** [comment]
@jardakotesovec regarding the "Potential improvement in future": Our plugins are loaded on-demand, and user-land code, might also decide to load an extra set of plugins. Therefore, you cannot predict what's going to be loaded for a given request.

Another optimization that I've intentionally skipped, was to append only the new translations/paths to the `LocaleBundle` (the priority/order and other caches should be considered). It would work, but it's not worth 😁

**Comment by jonasraoni** [comment]
> Hi @jonasraoni, can you give me example, why its not predictable?

We're not loading all plugins at every request, they are loaded dynamically. See:
https://github.com/pkp/ojs/blob/6c5d40f2b8e8da6b1e9bb1fd7302089ce23f125a/classes/payment/ojs/OJSPaymentManager.php#L211

Therefore, it's not possible to know which files we should load in advance. A plugin might load another plugin or [add its own custom translations](https://github.com/pkp/customLocale) on demand.

There are other alternatives:
- Load the translations for all enabled plugins: Not backwards compatible (even though I believe unexpected problems/collisions are unlikely to happen) + will force every request to hold the maximum number of translations in memory (not possible to measure the impact).
- Heuristic methods: if the `login.php` always uses XYZ, we can start with this set of translations (same problems as above, but less memory intensive).

Also, a user with a production environment + the [OPcache](https://www.php.net/manual/en/book.opcache.php) properly configured, should see extra performance improvements.

**Comment by jonasraoni** [comment]
This has been merged to `main` and cherry-picked in `stable-3_4_0`, so I'm closing :)
