### ISSUE TITLE
Make translation seamless in Vue.js as its in smarty templates

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9371]
To follow up the discussion from https://github.com/pkp/pkp-lib/discussions/9254 with some code.

## Current problem
Every translation that needs to be done in Vue.js is currently either passed via props (with varying naming conventions) or add to the 'common' list in PKPTemplateManager.php.

Using just simple `__.('')` syntax on php&smarty side is very convenient and I would like to bring similar experience to Vue.js, which can't directly get the translation from PHP.

## Suggested solution
- Simple vite plugin, which extracts all locale keys used in the components(by detecting `t('')` syntax). As result after npm run build, we have new file `locale/uiLocaleKeysBackend.json`, which is simple array of all used keys
- On php side new endpoint /index.php/index/api/v1/_i18n/ui.js, which returns javascript which populates `pkp.localeKeys`.
- Mechanism to use translations from pkp.localeKeys is already in place. 
- There is couple of translations used in tpl files (but using Vue.js translation), but its just few of them, so currently add them statically to the vite.config, as these files are not processed by the npm build process.

## Implementation
I will share the PR shortly. I was aiming to align it with our Locale implementation as much as possible to piggy back on existing mechanism of registering locale paths and following same caching strategy.

## Performance considerations
- `/index.php/publicknowledge/api/v1/_i18n/ui.js?hash=0fe7795c6dae047214f42254675b80c61c35255c` this script is referenced from frontend (in PKPTemplateManager). Using hash which represents current cache key ensures that browser will re-fetch this script only if translation changes.
- Calculating the cache key is done same way as for detecting .po files. Its using last modified timestamp to ensure that it will read new file if that timestamp is changed. This is surprisingly efficient and it won't introduce any noticeable performance degradation. (Translation performance is now 3 times faster with simple improvement - https://github.com/pkp/pkp-lib/issues/9364).

## Future improvements
- I would like to ship that simple vite plugin as npm module as it can be easily used in plugins if they decide to leverage Vue.js, so they can have same experience. That will be handled in separate issue.

Any suggestions & feedback is welcomed.

**Comment by jonasraoni** [comment]
Extracting the keys from Vue templates is the proper way to setup defaults automatically. I'm just not sure it's good to touch the `locale` folder.
The hash is invalidated based on enough information (locale, files, modification date), so it looks safe to me.

I'm just missing the possibility of loading extra locale keys dynamically (including from another language), but that might be addressed as a second part of the discussion.

**Comment by jardakotesovec** [comment]
@jonasraoni Thanks Jonas, lots of good feedback.

One thing still to figure out (and guidance is welcomed) is really where to place this functionality. More details here - https://github.com/pkp/pkp-lib/pull/9372#discussion_r1345424612

**Comment by jardakotesovec** [comment]
> Extracting the keys from Vue templates is the proper way to setup defaults automatically. I'm just not sure it's good to touch the `locale` folder. The hash is invalidated based on enough information (locale, files, modification date), so it looks safe to me.

Moving that to registry folder, that suggestion came from @asmecher 
> 
> I'm just missing the possibility of loading extra locale keys dynamically (including from another language), but that might be addressed as a second part of the discussion.

Yes, its currently limited to fetch translations for one language, which is align with what you can do in php/smarty just by using `__`. So I believe we don't need more than that. I assume there is some mechanism for multilingual forms to fetch translations for multiple languages, but have not really look into it.  What I am really just trying to solve here is that we don't have hard coded list of translation keys to be passed to frontend. Not introducing new functionality as I am not aware thats needed.

> 
> I've left my comments on the PRs.

**Comment by jardakotesovec** [comment]
Sigh, not good git day for me today. Accidentally commited these changes to main, its now reverted..

**Comment by jardakotesovec** [comment]
@jonasraoni @asmecher 
I did some refactor to improve separation and also get the last cache key from LocaleBundle to ensure the hash in url gets updated also when any po file get changed.

- Logic is now in dedicated class UITranslator (naming is always hard, if you have better idea let me know)
- Locale.php is only responsible on creating UITranslator and sharing all data it needs to operate(locale paths, LocaleBundle cache key, locale)
- Added optimistic caching (1year for ui.js file)
- json files are placed in registry folder


I think its good change as Locale.php is already doing a lot and now its explicitly clear what exact information this new functionality needs to operate.

I think its getting in good shape to be merge, but would really appreciate one more review round if you can spot something! Thank you!

**Comment by NateWr** [comment]
@jardakotesovec very cool! Love to see this happening. One comment on performance. In my experience, OJS installations "in the wild" often suffer from significant latency issues. This is usually due to poor hosting environments, where even a lightweight API request often takes 1s to complete. That's one of the reasons that I preferred server hydration wherever possible. If it's not too heavy, you might consider delivering the translations in the initial page request, through an inline `<script>` tag. This was done for some initial translations in `PKPTemplateManager::setupBackendPage()`.

**Comment by jardakotesovec** [comment]
Hi @NateWr, thank you for checking it out. I am expecting that this list of keys will significantly grow as we migrate props locale keys, I wanted to make sure its cacheable resource. Thats why I made it as separate endpoint&file, even though injecting via PKPTemplateManager would be easier to implement.  As result this should get fetched once as other static js files.  Which also prevent from retrieving this whole list from cache every time. If you think I missed something in this logic, please let me know.

**Comment by jardakotesovec** [comment]
Merged in main now.

What it means:
- just use t('locale.key') in vue.js components
- npm run build step will detect it was used and saves list to registry/uiLocaleKeysBackend.json
- backend will fetch translations from the API endpoint  **_18n/ui.js**
- t('locale.key') will apply that translation
- no need to use `setLocaleKeys` anymore

Will create separate issue for creating npm package for that vite plugin, which extracts the key, so it can be also leveraged in plugins.
