### ISSUE TITLE
Push author biographical statement to JATS

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9374]
JATS Template data delivered via OAI does not currently include the author's biographical statements. See CP Metadata Recommendations for details.

(Worth reviewing: DataCite; CrossRef; etc)

**Comment by AhemNason** [comment]
I'm happy to review where these might go in any place you'd like to put them. I doubt, for example, that Datacite includes it. We'd say what?: 

- Crossref
- Datacite
- JATS
- OpenAIRE? 

Anything else?

**Comment by ewhanson** [comment]
@asmecher, could you have a look at my approach for this? If it looks okay, I'll do the same for `stable-3_4_0` and `main`. Thanks!

PR:
- pkp/jatstemplate#36

**Comment by asmecher** [comment]
Looks good, @ewhanson! You'll have to change your tack a little in the `main` branch for HTML purification; there we use Symfony instead of HTMLSanitizer. have a look at the OAIJats plugin, which has recent adaptations to accommodate this.

**Comment by fabiobatalha** [comment]
@asmecher 

This is how we deal with bio notes in our stack.

``` xml
      <contrib-group content-type="author">
        <contrib contrib-type="person" id="au1">
          <name>
            <surname>Féron</surname>
            <given-names>François-Xavier</given-names>
          </name>
          <bio xml:lang="fr">
            <p>Titulaire d’un master en acoustique musicale...</p>
          </bio>
        </contrib>
      </contrib-group>
  ```

**Comment by asmecher** [comment]
@ewhanson Ah, one change to request for `stable-3_3_0` (and `stable-3_4_0` and `main` when you get a chance to port those) -- rather than localizing the biography per the current UI locale (which is what `getLocalizedBiography` will give you), it's best to get *all* biographical statements and use `xml:lang` to indicate what language is being provided.

**Comment by ewhanson** [comment]
Hey @asmecher, could you take a look. I've updated `stable-3_3_0` as discussed and ported the changes to `stable-3_4_0` and `main`. Thanks!

PRs:
- `stable-3_3_0`: pkp/jatsTemplate#38
- `stable-3_4_0`: pkp/jatsTemplate#39
- `main`: pkp/jatsTemplate#40

**Comment by asmecher** [comment]
All merged -- thanks, @ewhanson!
