### ISSUE TITLE
Add preferred name to JATS XML

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9375]
The current JATS XML does not include the preferred public name, which is available in OJS. Add it. Suggested JATS element: [string-name](https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/string-name.html)

**Comment by AhemNason** [comment]
https://jats.nlm.nih.gov/archiving/tag-library/1.2/chapter/tag-names.html 

you're looking for <name-alternative>  

Our use cases are largely covered by these two points but I think there's validity across and a good expectation that our own "preferred name" field would operate similarly. 

```
- An alternate name for indexing (For example, a publisher may choose to record several name variants for an individual, such as a nickname, author-pseudonym, maiden name, religious name, or tribal name. The attribute [@specific-use](https://jats.nlm.nih.gov/archiving/tag-library/1.2/attribute/specific-use.html) could be used to record the rationale for the name variant, such as “primary”, “index”, or “table-of-contents”. Alternatively, or in addition, the attribute [@content-type](https://jats.nlm.nih.gov/archiving/tag-library/1.2/attribute/content-type.html) could be used to record the type of name variant, such as “nickname”, “maiden-name”, or “pseudonym”, etc.);

- A version of the name in a different arrangement (For example, since the order of the [<surname>](https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/surname.html) and [<given-names>](https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/given-names.html) is fixed in JATS, a publisher might also wish to record a byline-style version of the name in given-surname order and could use a [<string-name>](https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/string-name.html) with @content-type="byline" to accompany the name inside a [<name-alternatives>](https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/name-alternatives.html) element.); or
```

**Comment by AhemNason** [comment]
I'll add that alt-name is also used in Crossref metadata: 

https://data.crossref.org/reports/help/schema_doc/5.3.1/crossref5_3_1_xsd.html#person_name

**Comment by asmecher** [comment]
@AhemNason, the `<name-alternatives>` element can be used to group alternative names, but doesn't itself describe them -- I think the recommendation would be something like...
```xml
<contrib>
  ...
  <name-alternatives>
    <string-name specific-use="display">José del Pozo García</string-name>
    <name specific-use="primary" name-style="western">
      <surname>del Pozo García</surname>
      <given-names>José</given-names>
    </name>
  </name-alternatives>
  ...
</contrib>
```

...in place of our current XML, which looks like...

```xml
<contrib>
  ...
  <name specific-use="primary" name-style="western">
    <surname>del Pozo García</surname>
    <given-names>José</given-names>
  </name>
  ...
</contrib>
```

The `@specific-use` attribute does not have a formal vocabulary, but I think `display` and `primary` capture OJS's use cases.

However, any downstream code that currently expects `<name>` to appear directly in `<contrib>` will have to be adapted to expect `<name-alternatives>` instead.

Does that sound workable?

**Comment by ewhanson** [comment]
Hey @asmecher, I've created PRs for `stable-3_3_0`, `stable-3_4_0`, and `main` that add the preferred name according to the mockup above. Could you have a look. Thanks!

PRs:

- `stable-3_3_0`: pkp/jatstemplate#33
- `stable-3_4_0`: pkp/jatstemplate#34
- `main`: pkp/jatstemplate#35

**Comment by ewhanson** [comment]
For future reference:

This update does include a potentially breaking change for downstream consumers. `<name>` will now always be wrapped within a `<name-alternatives>` tag and contain the `specific-use='primary'` attribute. When a preferred name is present, it will also be contained within the `<name-alternatives>` tag inside of a `<string-name specific-use='display'>` tag.

New format:
```xml
<contrib>
  ...
  <name-alternatives>
    <string-name specific-use="display">José del Pozo García</string-name>
    <name specific-use="primary" name-style="western">
      <surname>del Pozo García</surname>
      <given-names>José</given-names>
    </name>
  </name-alternatives>
  ...
</contrib>
```

Previous format:
```xml
<contrib>
  ...
  <name specific-use="primary" name-style="western">
    <surname>del Pozo García</surname>
    <given-names>José</given-names>
  </name>
  ...
</contrib>
```

**Comment by asmecher** [comment]
All merged, thanks!
