### ISSUE TITLE
Limit reviewers' statistics to a journal in multi-journals OJS instance

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#9381]
As an editor of a journal hosted in a multi-journals OJS instance, I want to be able to limit the review statistics to my journal only. 

By default, when inviting reviewers, OJS provide statistics (number of invitations, already invited or not, etc.) that are global for all journals hosted. 

Improvement:  

- Add a site setting to setup wheter the statistics should be shared, defaulting to yes, to avoid breaking changes.
  
  ![image](https://github.com/pkp/pkp-lib/assets/31410053/ce4c017e-6edc-4468-afdd-e75bda44eaef)

- ~~Add a high-level configuration in the config.inc.php (reviewers_stats_local_only ; On/Off) which offer the ability to limit statistics to each of the journals or for the complete journal platform.
https://github.com/pkp/pkp-lib/assets/19291880/945d6f54-210d-42e0-99b4-784c3de46e63~~

This feature was already documented on PKP Forum (by me :°) https://forum.pkp.sfu.ca/t/ojs-3-reviewer-invite-window-statistics-configuration/75490

**Comment by kristinmhoffmann** [comment]
As a host for a multi-journal OJS instance, I would appreciate having this option. Some of our journals have reviewers in common, but editors assume that they are seeing statistics that pertain to their journal only, and are confused to learn that that's not the case.
