### ISSUE TITLE
Display users’ roles in OJS user list 

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#9382]
As an editor, I want to see the roles given to users in my OJS journal user list. 

Improvements:  

- Add a column in user list to displayed roles given to each user. 

![image](https://github.com/pkp/pkp-lib/assets/19291880/4ab2467b-3f6f-4280-b4c0-a45a70cefb37)

**Comment by jonasraoni** [comment]
@asmecher as a user, I think this is useful and I've already reviewed the linked PR, anything against?

**Comment by asmecher** [comment]
Merged and cherry-picked!

**Comment by pilasou** [comment]
Hi @jonasraoni, sorry I am late in sending you our big thanks for reviewing and suggesting improvment to our code! This is our first contribution making its way to OJS code! We have a few more coming soon!

**Comment by jonasraoni** [comment]
@pilasou great, help is always welcome 🤗
