### ISSUE TITLE
installPluginVerion.php script fails for some importexport plugins in OJS 3.4

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#9384]
**Describe the bug**
When trying to run the installPluginVersion script for some ImportExport-Plugins in OJS 3.4 the script fails with:

    PHP Fatal error:  Uncaught Error: Call to a member function getInstallMigration() on null in /var/www/html/ojs/lib/pkp/tools/installPluginVersion.php:92 

This error can be tracked down to a combination of changes introduced with OJS 3.4 which result in importexport plugins derived from PubObjectsExportPlugin not being loaded.

In PluginRegistry.php an additional condition checking for the success of plugin registration has been introduced.

OJS 3.4:

https://github.com/pkp/pkp-lib/blob/e89570424b2b0a0d7f3a5a77ac9b649b29c30af6/classes/plugins/PluginRegistry.php#L76

OJS 3.3:

https://github.com/pkp/pkp-lib/blob/9f9208779eab9786d54ab62d31b6ef620742c9e5/classes/plugins/PluginRegistry.inc.php#L72

In addition, the class PubObjectsExportPlugin in OJS 3.4 checks if the application is under maintanance:

https://github.com/pkp/ojs/blob/f92717fcdb2e993c338abf3f5af49a6e4c22e955/classes/plugins/PubObjectsExportPlugin.php#L93

which will cause the register function to always return false when called from installPluginVersion and the plugin not being loaded.

I tried to run the script for our DNB Export plugin in the first place. But it also fails if you run it for the DOAJ Export plugin since both are derived from PubObjectsExportPlugin. Other importexport plugins are loaded.

I can implement a temporary workaround for my plugin but this should be handled in PubObjectsExportPlugin. I also would appreciate if we could handle this quickly because journals here in Germany and the German Natioanl Library are waiting for the plugin upgrade. They will not move to OJS 3.4 without the DNB Export plugin.

**To Reproduce**
1. I guess you know what to do ...

**What application are you using?**
 OJS 3.4

<hr>

PRs:
stable-3_4_0:
- https://github.com/pkp/ojs/pull/4072
- https://github.com/pkp/ops/pull/586

main:
- https://github.com/pkp/ojs/pull/4073
- https://github.com/pkp/ops/pull/587

**Comment by jonasraoni** [comment]
I believe I was the last person to touch the `PluginRegistry.php`. I'll be watching this issue, if nobody gets assigned to it, I'll take a look ASAP.

**Comment by bozana** [comment]
I think it was wrong that PubObjectsExportPlugin has returned false when Application::isUnderMaintenance.
@ronste, could you maybe try if this patch (above) works?

**Comment by ronste** [comment]
> I think it was wrong that PubObjectsExportPlugin has returned false when Application::isUnderMaintenance. @ronste, could you maybe try if this patch (above) works?

Yes, that does the job. Thanks!
