### ISSUE TITLE
FieldRichText formatting options not visible after migration to Vite/Vue3

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#9390]
**Describe the bug**
The `FieldRichText` field includes a button dropdown to show formatting options, like bold and italic. After the migration to Vite/Vue3, the button no longer appears.

**To Reproduce**
1. Launch the ui library.
2. Go to Form > FieldRichText
4. Click on the input field.
7. See that the formatting button doesn't appear

**What application are you using?**
 `main` branch (pre-3.5)

**Additional information**
How it used to work:

[field-rich-text.webm](https://github.com/pkp/pkp-lib/assets/2306629/eceae468-e4e5-4fd2-a7c9-28e74847eefe)

How it works in main:

[field-rich-text-broken.webm](https://github.com/pkp/pkp-lib/assets/2306629/d39bee2d-22ee-409a-8bf3-9f3836f08cc6)

**Comment by touhidurabir** [comment]
@jardakotesovec can you please take a look at this one . Probably would be a good idea to tackle this as a part of https://github.com/pkp/pkp-lib/issues/9366 as we may need some modification to make it compatible with TinyMCE 6.0 .

**Comment by jardakotesovec** [comment]
@NateWr Thank you for the report. Addressed on ui-library main (https://github.com/pkp/ui-library/pull/291). Should be ok now.
