### ISSUE TITLE
DOAJ plugin does not store deposit status in OJS 3.4

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#9391]
**Describe the bug**
When using "Register" or "Mark registered" in the DOAJ plugin the deposit status is not stored, i.e. after reload the article is still "Not Deposited".

**To Reproduce**
1. Go to "Tools -> DOAJ Export Plugin -> Articles"
2. Select an article
3. Click "Register" or "Mark registered"
4. See "Status"

**What application are you using?**
 OJS 3.4.0-3

**Additional information**

The field "doaj::status:" with value "registered" is correctly stored in the submission object but sanitized out in

https://github.com/pkp/pkp-lib/blob/4aad70b0cf437b174b2c9922ef50b886aeab7a98/classes/core/EntityDAO.php#L190

because it was not added to the submission schema.

<hr>

PRs:
stable-3_4_0:
- https://github.com/pkp/ojs/pull/4068 
- https://github.com/pkp/ops/pull/583

main:
- https://github.com/pkp/ojs/pull/4069
- https://github.com/pkp/ops/pull/584

**Comment by bozana** [comment]
@ronste, would you maybe be able to test the changes provided in the PR above?

**Comment by ronste** [comment]
> @ronste, would you maybe be able to test the changes provided in the PR above?

I can confirm it works.
