### ISSUE TITLE
Enable strict RFC compliant redirects for Guzzle

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9397]
**Describe the bug**
Recently ORCID redirected the API URL to another URL which led to users not being able to use the plugin, s.https://github.com/pkp/orcidProfile/issues/281.
Thus add the option `'allow_redirects' => ['strict' => true]` so that redirects will work.

<hr>

PRs:
stable-3_3_0:
- https://github.com/pkp/pkp-lib/pull/9398
- https://github.com/pkp/ojs/pull/4062 (only submodule update)

stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/9399
- https://github.com/pkp/ojs/pull/4063 (only submodule update)

main:
- https://github.com/pkp/pkp-lib/pull/9423
- https://github.com/pkp/ojs/pull/4067 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you please take a look at the PR?

**Comment by asmecher** [comment]
@bozana, that looks good, please go ahead -- but it also needs forward-porting to `main`, right?

**Comment by bozana** [comment]
forwarded to main, merged all, thus closing...
