### ISSUE TITLE
Sample issue

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#940]
(Demonstration issue, please ignore)

I spotted this:

- [x] xyz is broken
- [ ] abc is broken
- [ ] also tuv

**Comment by asmecher** [comment]
I think xyz is supposed to work that way.

**Comment by jalperin** [comment]
no way! xyz is supposed to work this way, not that way!

**Comment by asmecher** [comment]
^ @willinsky, this is roughly what you predicted.

**Comment by willinsky** [comment]
hoping to do better
John

On Dec 1, 2015, at 9:52 PM, Alec Smecher <notifications@github.com<mailto:notifications@github.com>> wrote:


^ @willinsky<https://github.com/willinsky>, this is roughly what you predicted.
