### ISSUE TITLE
Inline CSS styles ignored in htmlGalley context

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#9401]
**Describe the bug**
When using the `htmlGalley` context to add styles to a HTML galley, the `inline` argument is ignored. 

When a theme plugin calls `$this->addStyle($name, $styles, ['inline' => true'])`, the styles are added inline, in a `<style>` tag, instead of a `<link>` tag. However, the `inline` argument is ignored in the `htmlGalley` context.

Example code in a theme's `init()`:

```php
$styles = 'body { color: red; }';
$this->addStyle($name, $styles, ['inline' => true', 'contexts' => ['htmlGalley']);
```

Expected result in the HTML galley's `<head>`:

```html
<style type="text/css">body { color: red; }</style>
```

Actual result:

```html
<link rel="stylesheet" href="body { color: red; }" " type="text/css">
```

**To Reproduce**
1. Create a submission with a HTML galley.
2. Add the following code to the default theme's `init()` method: `$this->addStyle($name, 'body { color: red; }', ['inline' => true', 'contexts' => ['htmlGalley']);`
4. Check the `<head>` of the HTML galley. **NOTE:** this should effect the `<head>` of the HTML galley itself, which is loaded in an `<iframe>`. It will not appear in the `<head>` of the OJS page which wraps the `<iframe>`.

**What application are you using?**
3.4.x

<hr>

PRs:
- https://github.com/pkp/pkp-lib/pull/9402 (stable-3_4_0)
- https://github.com/pkp/pkp-lib/pull/9424 (main)

**Comment by NateWr** [comment]
@bozana can you take a look? Hopefully an easy merge and cherry-pick.

PR:
https://github.com/pkp/pkp-lib/pull/9402

Tests:
https://github.com/pkp/ojs/pull/4065

**Comment by bozana** [comment]
Thanks @NateWr, and sorry for the wait. Merged and I will cherry-pick it to main...
