### ISSUE TITLE
OMP: Trying to add contributors: Uncaught Error: Class "APP\\controllers\\grid\\users\\author\\form\\AuthorForm" not found

### ISSUE THREAD

**Issue by loadbrain** [pkp/pkp-lib#9403]
I want to add contributors in OMP 3.4 from a plugin
Code calls the `editAuthor($args, $request)` function from 
 \lib\pkp\controllers\grid\users\author\AuthorGridHandler.php, 
In line 352 
`$authorForm = new AuthorForm($this->getPublication(), $author);`
is called which throws an error

`Class "APP\controllers\grid\users\author\form\AuthorForm"`

If I change the code to call
`$authorForm = new \PKP\controllers\grid\users\author\form\PKPAuthorForm($this->getPublication(), $author);`
it works.

But this can't be the solution...
What can I do, any ideas?

**Comment by touhidurabir** [comment]
@loadbrain this is expected as in the `OMP` has no `AuthorForm`, need to use the one from `pkp-lib` .

**Comment by loadbrain** [comment]
Sorry, maybe I do not quite understand, but I have to change 
\lib\pkp\controllers\grid\users\author\AuthorGridHandler.php
which is a core file from lib/pkp.

So after an update it would be overwritten.

There must be a better solution!

**Comment by touhidurabir** [comment]
Ah , got it , it seems the proper namespace is not included at the top . Also it seems that `AuthorGridHandler` and the `PKPAuthorForm/AuthorForm` has been deprecated in `3.4` (see at the top with doc block as `@deprecated 3.4`). And thats probably why it has not updated with proper namespace.

May be ask in the [forum](https://forum.pkp.sfu.ca/) and see anyone know what is the alternative now as this one has been deprecated .

**Comment by loadbrain** [comment]
Exactly.
I will try the forum, thanks.
