### ISSUE TITLE
Announcement title not properly escaped on delete

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9408]
**Describe the bug**
Announcement titles containing HTML special characters are not properly escaped in the delete confirmation modal.

**Comment by asmecher** [comment]
Draft PRs:
- [stable-3_3_0](https://github.com/pkp/pkp-lib/issues/9408)
- TODO: `stable-3_4_0`
- TODO: `main`

**Comment by jardakotesovec** [comment]
Added some comments to the PR.

Also found same problem when deleting contributor..

<img width="1143" alt="Screenshot 2023-10-16 at 12 10 48" src="https://github.com/pkp/pkp-lib/assets/1590681/1ecc0d37-b3b8-4ffb-9341-2837892b8342">

And Highlights seems to have same implementation as Announcements (was not able to test it as main is broken for me now)

I also attempted to review all uses of browser side param replacement. And did not find anything that would look like it needs html for params. I think that mostly should be `title` right? Using any of other richtext fields as param is highly unlikely and did not see anything suggesting that.  Therefore I would be inclined just to escape all params.  If you think its risky for 3.3/3.4.

Than the other cases are ContributorsListPanel.vue
```
				message: this.replaceLocaleParams(this.i18nConfirmDelete, {
					name: contributor.fullName,
				}),
```

And HighlightsListPanel.vue
```
                message: this.replaceLocaleParams(this.i18nConfirmDelete, {
                    title: this.localize(highlight.title),
                }),
```

Even though I agree this should be correctly handled by frontend, bit surprised that we don't attempt to filter these out during validation step, when data are submitted.

**Comment by jardakotesovec** [comment]
Created frontend specific issue for me to circle back to it later on - https://github.com/pkp/pkp-lib/issues/9421 .

@asmecher  Not sure if you would want to also review validation on server side to not let such content in first place?

**Comment by asmecher** [comment]
Deferring; this is a privileged action anyway, so the risk is low.

**Comment by asmecher** [comment]
@jardakotesovec, I've revisited my PR [above](https://github.com/pkp/pkp-lib/issues/9408#issuecomment-1760505137) after your comments -- thanks. I think you're looking for cases in `stable-3_4_0`, when I only grepped through `stable-3_3_0` -- for example, both highlights and contributor deletion don't appear until 3.4.0. This is easy enough to grep for -- there aren't that many use cases for `replaceLocaleParams`. Do you mind if I go ahead with this expedient fix for `stable-3_3_0` and `stable-3_4_0`?

**Comment by jardakotesovec** [comment]
@asmecher I found strong candidate for replacing v-html, intend to test that tomorrow. If thats successful and we would be able to do the sanitisation on vue.js level (using the allowed_html whitelist). Would that be good enough to cover this case in your opinion? It still would be possible to sneak in things like image via announcements to the dialog. Which is not ideal, but not security issue.

I still would like to explore whether there are better patterns to minimise even use of any 'v-html-restricted', but this could be good catch all approach across all versions, with minimal risk of regressing something.

**Comment by asmecher** [comment]
Sounds good; I'll leave this open against 3.3.0-17 and let you come back to it.

**Comment by jardakotesovec** [comment]
Testing locally seems promising..  now running tests on travis -https://github.com/pkp/pkp-lib/issues/9421

**Comment by asmecher** [comment]
@jardakotesovec, just to confirm, this is resolved in `stable-3_3_0` and `stable-3_4_0` by https://github.com/pkp/pkp-lib/issues/9421, correct?

**Comment by jardakotesovec** [comment]
@asmecher Yes, from security point of view. It still can show some 'safe' html in that dialog. This is one of the cases when it would be useful to 'label' translation to allow html or not.
