### ISSUE TITLE
Fatal error when uploading .mht file

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9415]
**Describe the bug**
When trying to upload a `.mht` file (therefore, other uncommon extensions might raise the same problem), the following exception is raised:

```php
PHP Fatal error:  Uncaught League\Flysystem\UnableToRetrieveMetadata: Unable to retrieve the mime_type for file at location: journals/11/articles/711/652a43f657b82.mht.  in /var/www/html/lib/pkp/lib/vendor/league/flysystem/src/UnableToRetrieveMetadata.php:49
Stack trace:
    #0 /var/www/html/lib/pkp/lib/vendor/league/flysystem/src/UnableToRetrieveMetadata.php(44): League\Flysystem\UnableToRetrieveMetadata::create('journals/11/art...', 'mime_type', '', NULL)
#1 /var/www/html/lib/pkp/lib/vendor/league/flysystem-local/LocalFilesystemAdapter.php(397): League\Flysystem\UnableToRetrieveMetadata::mimeType('journals/11/art...', '')
#2 /var/www/html/lib/pkp/lib/vendor/league/flysystem/src/Filesystem.php(150): League\Flysystem\Local\LocalFilesystemAdapter->mimeType('journals/11/art...')
#3 /var/www/html/lib/pkp/classes/services/PKPFileService.php(95): League\Flysystem\Filesystem->mimeType('journals/11/art...')
#4 /var/www/html/lib/pkp/controllers/wizard/fileUpload/form/SubmissionFilesUploadForm.php(192): PKP\services\PKPFileService->add('/tmp/phpXGWt8z', 'journals/11/art...')
#5 /var/www/html/lib/pkp/controllers/wizard/fileUpload/FileUploadWizardHandler.php(427): PKP\controllers\wizard\fileUpload\form\SubmissionFilesUploadForm->execute()
#6 [internal function]: PKP\controllers\wizard\fileUpload\FileUploadWizardHandler->uploadFile(Array, Object(APP\core\Request))
#7 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#8 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#9 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#10 /var/www/html/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#11 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#12 {main}
  thrown in /var/www/html/lib/pkp/lib/vendor/league/flysystem/src/UnableToRetrieveMetadata.php on line 49
```

**To Reproduce**
1. Upload a submission file with the `.mht` extension.

**What application are you using?**
OJS 3.4

**Comment by asmecher** [comment]
@jonasraoni, would the solution not be to add .mht to https://github.com/thephpleague/mime-type-detection rather than fixing it here?

**Comment by jonasraoni** [comment]
I've checked the underlying library, and it has around 1200 extension <=> mime-type mappings, so anything that doesn't exist there might raise this issue.

I didn't inspect our usage of mime-types (I guess it's being used just to display different icons on the frontend), but given that:
- Our software doesn't limit uploads to specific file types
- Mapping using extensions is already an error-prone approach (I mean that the library's output isn't really important/should be used with a grain of salt)

I think this should be fixed on our side. Check if the library provides a way to give us the default mime-type or add a try/catch providing to do it (`finfo_file() ?: 'application/octet-stream'`).

**Comment by asmecher** [comment]
I'd be open to reviewing an approach like you describe -- but I also think there's benefit in adding `.mht` to that database.

**Comment by jonasraoni** [comment]
@asmecher
- https://github.com/pkp/pkp-lib/pull/9439

**Comment by asmecher** [comment]
Merged https://github.com/pkp/pkp-lib/pull/9439, thanks -- can you forward-port to `main` as well?

**Comment by jonasraoni** [comment]
Cherry-picked to `main` by this commit: https://github.com/pkp/pkp-lib/commit/ffe412d83eebc881244930a9e571631554bb8560
