### ISSUE TITLE
UI Design Suggestions: Submission and Review

### ISSUE THREAD

**Issue by willinsky** [pkp/pkp-lib#942]
- [ ] I think we should standardize page titles (as I suggested Editorial Dashboard above) and Editorial Workflow for this page, placed above the submission title (even as I regret adding a line to a page). We already have this working well with other pages we have such Press Settings, which has the precision and press-specific nature I’m looking for.
- [ ] The right-hand buttons. Some colored and no colored, especially on the first tab, may suggest only the colored are active. ~~Maybe use a pale blue similar to the hyperlink font to limit the pallet for the less critical buttons of this sort.~~ https://github.com/pkp/pkp-lib/commit/aeb259f456e98928bf73c7b21ef195b64abf7c79
- [ ] I My inclination on the order of the buttons is logic-of-decision and frequency-based as follows (the order of buttons in Internal Review is great):
  Send to Internal Review
  Send to External Review
  Accept Submission 
  Expedite Submission
      Decline Submission

![screen shot 2015-12-01 at 11 01 15 pm](https://cloud.githubusercontent.com/assets/10342108/11524407/75d86a84-987f-11e5-9851-e9d33fb1feca.png)
- [ ] “Start Typing” could be “Start typing reviewer’s name (autocomplete)...
- [x] These links -- Advanced Search, Create New Reviewer, Enroll Existing Reviewer -- would better be Search reviewer database   Add new reviewer   Enroll user as reviewer . These choices should appear directly below “Reviewer” box and not directly above “Choose a pre…”
- [ ] Could “Choose a predefined message..,” appear in the pull-down itself? Given that a message already appears in the form by default, perhaps what should appear in the pulldown in this module and all modules with this option, is simply “Prepared email texts” and the pull down should appear directly below the “Email to be sent…” to indicate that the selected prepared text will appear in the form for further editing.
- [x] Work needed on the default email texts (paragraphs are not handled right, with additional spacing.) 
- [x] “Do not send Reviewer email” could better worded as “Do not send email to reviewer.”
- [x] The two titles “Restrict Available FIles” and “Available Review FIles” would be better reduced to “Files To Be Reviewed”  https://github.com/pkp/pkp-lib/commit/370bd98206fd96c693dcb7120af77c20b92297fd
- [ ] “Selected Reviewer” does not have title bolding. 
- [ ] It would be great to have some standardized visual grouping for this popups that set the messaging section apart from the file selection section.

![screen shot 2015-12-01 at 11 05 13 pm](https://cloud.githubusercontent.com/assets/10342108/11524480/04b0aff0-9880-11e5-8cd4-6c5b81102ab7.png)
- [ ] “Record Editorial Decision” doesn’t correspond to the pop-up’s Send to External Review. We need a different way of indicating multiple actions in these pop-ups, perhaps along these lines, with text and common button. 
- [x] Notify authors, record decision, and send selected file(s) to External Review.  [Complete]
- [ ] I think we only use a contact author, so that “author” can be singular right through
  Again on the theme of too much going on in the popup, I’d suggest two sections in this one organized like this:
  Notify Author
      Notification email
      Reviewer’s attachments
  Send to Copyedit 
      Files

![screen shot 2015-12-01 at 11 06 33 pm](https://cloud.githubusercontent.com/assets/10342108/11524512/352eba32-9880-11e5-8ae0-30fdb012127b.png)
- [ ] Discussion gray box isn’t behaving properly in Internal and External Review.

![screen shot 2015-12-01 at 11 07 34 pm](https://cloud.githubusercontent.com/assets/10342108/11524542/59b0753a-9880-11e5-885b-bea3f3eca0bb.png)

**Comment by NateWr** [comment]
- "Editorial Workflow": it's not clear to me what problem this is supposed to solve. We're in the context of a submission, not just an editorial workflow. Marketing materials, galley production all takes place here.  I'm not in favor of changing this (which would actually break consistency with the design on other pages) unless user tests suggest there is some confusion happening here that needs to be fixed.
- Button colors and order: We talked at pkp2015 about the miscommunication around the Accept Submission button. I believe I renamed that and it's confusing. It's already come up in a user test as well. Clarity around "Accept" vs "Expedite" is not immediately clear. Accept should be a regular button color (not blue). I disagree that the other buttons "look disabled" but user tests should surface that if it really is a problem. I think we need to get the language right. Agree with your button order.
- Add Reviewer: problems with selecting a reviewer and choosing a predefined message have already surfaced pretty strongly in the initial user tests. I suspect it will get a rework. I agree with the wording changes you suggest. In general I feel the wording throughout the system is out-dated given all the changes that have occurred and need a pretty systematic review. But these issues will give us a start.
- Full-width discussions box on review stage: there's confusion happening here. The discussions panel is not tied to a particular review round, whereas the other grids are. We need a better way to communicate this but don't really have anything in the layout architecture to do that.

**Comment by willinsky** [comment]
The "Editorial Workflow" describes the activity the page is concerned with, and does, I think, apply to all 4 tabs, while the title of the submission is not the title of the page in that sense, and in the way that other titles of the pages operate, and which we can consistently present graphically.

**Comment by NateWr** [comment]
I disagree.

Page titles are not there merely to describe the page content. They are primarily there to track position within the system. On all pages in the admin panel, page titles correspond to items in the navigation menu. "Press Settings" is a clue to finding your way back to the page via the navigation menu.

There is no link to "Editorial Workflow" nor would it be possible for us to create one, because there is no such page. This page represents a submission, is unique to a submission, and can only be accessed again by searching for that submission from the dashboard. 

Page content typically describes itself and if it doesn't do this sufficiently it should be designed to do so, because people will generally skip past the page titles. They'll only look at page titles if a) they are uncertain what the page is for (in which case the page content needs to be redesigned) or b) they need to store a reference to their position within the system (ie - "what page am I on so I can get back here or tell my copyeditor where to go?"). In both cases the submission title is the more relevant and helpful piece of information.

**Comment by NateWr** [comment]
If my assertions are wrong on this account, this will be clear in user testing and we'll have reasonable data on which to solve the problem.

**Comment by asmecher** [comment]
Moved "Advanced Search, Create New Reviewer, Enroll Existing Reviewer" links up. The renaming of the "Advanced Search" is handled in https://github.com/pkp/pkp-lib/issues/983

**Comment by asmecher** [comment]
“Do not send Reviewer email” could better worded as “Do not send email to reviewer.” -- implemented.

**Comment by asmecher** [comment]
Fixed doubled line breaks in email templates.

**Comment by NateWr** [comment]
I swapped out the dark blue for the pale blue in the primary button style. https://github.com/pkp/pkp-lib/commit/aeb259f456e98928bf73c7b21ef195b64abf7c79

**Comment by asmecher** [comment]
@willinsky, regarding:

> I think we only use a contact author, so that “author” can be singular right through Again on the theme of too much going on in the popup...

We already have support for multiple authors to be active in the workflow with OJS 3, and if there are remaining restrictions on only a single author participating, we need to remove those. So I'd suggest we stick with "Authors" rather than assuming there will be a single contact author.
