### ISSUE TITLE
Uncaught Error: Class “AjaxModal” not found

### ISSUE THREAD

**Issue by janevsky** [pkp/pkp-lib#9422]
**Describe the bug** & **To Reproduce(Steps to reproduce the behavior)**

When an author is logged in and visiting dashboard>submissions>Archives and then View on a already published submission entering the workflow, he can see four tabs plus publication, but when trying to access the copyediting tab he can see the copyediting discussions but the rest of the page is loading and never loads. There is an error in the php error log:

`[14-Oct-2023 16:50:04 Europe] PHP Fatal error:  Uncaught Error: Class "AjaxModal" not found in /home/XXX/domains/XXX/public_html/plugins/generic/texture/TexturePlugin.inc.php:258
Stack trace:
#0 /home/XXX/domains/XXX/public_html/plugins/generic/texture/TexturePlugin.inc.php(140): TexturePlugin->_createGalleyAction()
#1 /home/XXX/domains/XXX/public_html/lib/pkp/classes/plugins/HookRegistry.inc.php(107): TexturePlugin->templateFetchCallback()
#2 /home/XXX/domains/XXX/public_html/lib/pkp/classes/template/PKPTemplateManager.inc.php(1070): HookRegistry::call()
#3 /home/XXX/domains/XXX/public_html/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1022): PKPTemplateManager->fetch()
#4 /home/XXX/domains/XXX/public_html/lib/pkp/classes/controllers/grid/GridHandler.inc.php(988): GridHandler->renderRowInternally()
#5 /home/XXX/domains/XXX/public_html/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1033): GridHandler->renderRowsInternally()
#6 /home/XXX/domains/XXX/public_html/lib/pkp/classes/controllers/grid/GridHandler.inc.php(923): GridHandler->renderGridBodyPartsInternally()
#7 /home/XXX/domains/XXX/public_html/lib/pkp/classes/controllers/grid/GridHandler.inc.php(643): GridHandler->doSpecificFetchGridActions()
#8 /home/XXX/domains/XXX/public_html/lib/pkp/classes/core/PKPRouter.inc.php(395): GridHandler->fetchGrid()
#9 /home/XXX/domains/XXX/public_html/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()
#10 /home/XXX/domains/XXX/public_html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route()
#11 /home/XXX/domains/XXX/public_html/lib/pkp/classes/core/PKPApplication.inc.php(363): Dispatcher->dispatch()
#12 /home/XXX/domains/XXX/public_html/index.php(68): PKPApplication->execute()
#13 {main}
  thrown in /home/XXX/domains/XXX/public_html/plugins/generic/texture/TexturePlugin.inc.php on line 258`

Apache log:

`[14/Oct/2023:16:50:04 +0200] "GET /jhrs/$$$call$$$/tab/author-dashboard/author-dashboard-tab/fetch-tab?submissionId=89&stageId=4&_=1697294991519 HTTP/1.1" 200 436 "https://domainXXX/XXX/authorDashboard/submission/89" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
[14/Oct/2023:16:50:04 +0200] "GET /jhrs/$$$call$$$/grid/queries/queries-grid/fetch-grid?submissionId=89&stageId=4&_=1697294991520 HTTP/1.1" 200 1437 "https://domainXXX/XXX/authorDashboard/submission/89" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
[14/Oct/2023:16:50:04 +0200] "GET /jhrs/$$$call$$$/grid/files/copyedit/copyedit-files-grid/fetch-grid?submissionId=89&stageId=4&_=1697294991521 HTTP/1.1" 500 0 "https://domainXXX/XXX/authorDashboard/submission/89" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"`

The rest of the tabs works without problems.
Forgot to mention that i've tried this on multiple versions, 3.4.0, 3.3.0-14 and 3.3.0-11, got the same results.

**What application are you using?**
OJS 3.3.0-14

**Additional information**

Chrome devtools>networking
![image](https://github.com/pkp/pkp-lib/assets/63719545/62491d60-bee5-455a-8ef7-60ca30e57856)

Already posted on the forum:
[[Uncaught Error: Class “AjaxModal” not found](https://forum.pkp.sfu.ca/t/uncaught-error-class-ajaxmodal-not-found/82140)](https://forum.pkp.sfu.ca/t/uncaught-error-class-ajaxmodal-not-found/82140)

**Comment by asmecher** [comment]
@janevsky, try [this change](https://github.com/pkp/texture/commit/fd13462c7e68edb5daae3a7c51695aaa6aa8c266) to resolve the issue.

**Comment by janevsky** [comment]
> @janevsky, try [this change](https://github.com/pkp/texture/commit/fd13462c7e68edb5daae3a7c51695aaa6aa8c266) to resolve the issue.

This fixed the problem with the AjaxModal, thank you @asmecher!

**Comment by asmecher** [comment]
Great, thanks for confirming!
