### ISSUE TITLE
UI Design Suggestions: Editorial Stage

### ISSUE THREAD

**Issue by willinsky** [pkp/pkp-lib#943]
- [ ] Having the links for the linked Catalog Entry, etc. appear in a different place depending on how many authors, and as if it followed from the authors, leads to ask whether that set of links can always be right-justified on the line with the authors, and if not then I’d be tempted to set aside my desire to reduce lines by suggesting it be right justified on its own line, below the authors, and with a blank line before the tab titles start.
- [x] “Editorial” could be “Copyedit” as that is the task of the page, and submission, review, etc. are all editorial concerns. ["Copyediting", actually; see below. - AS]
- [ ] It seems hard to get to the Help On and Help Off, and I see that Off is not yet working,
- [ ] When Discussions is not used, it creates this second line with Last Reply, which either remains or disappears when DIscussion is used.
- [x] Replies would seem to naturally follow Last Reply, like this From  Last Reply  Replies   , although that may not be as easy re the spacing, given Replies is pretty predictable (less than 10) and Last isn’t.
- [x] Discussions could be 
  Submission Chat
  Review Chat
  Copyedit Chat
  Production Chat
  This naming will help in off-line references to where something was discussed, as in “it came up in Copyedit Chat.”

![screen shot 2015-12-01 at 11 11 22 pm](https://cloud.githubusercontent.com/assets/10342108/11524604/dd7b4142-9880-11e5-8ac0-397ac3d56921.png)

**Comment by asmecher** [comment]
I've moved "Replies" after "Last Reply" per your suggestion.

**Comment by asmecher** [comment]
Renaming of "Discussions" is covered in https://github.com/pkp/pkp-lib/issues/960

**Comment by asmecher** [comment]
@stranack, do you recall what our decision was re: renaming the "Editorial" stage to "Copyediting"?

**Comment by asmecher** [comment]
@willinsky, regarding the placement of the Catalog Entry; Submission History; etc. tools, these appear inline with the author list only if screen real-estate permits. If not, they get bumped onto a subsequent line. It's not dependent on how many authors there are, just screen real-estate. Are you suggesting these should always appear on their own line?

**Comment by willinsky** [comment]
I'm wondering about the slight distraction of having these linked terms (Catalog Entry; Submission History; etc)  in a different place on every page depending on how many authors and how long their names are. I am wondering about creating a space for them as a right-justified set of four terms -- to set them off from the five tab terms (as they are the same size as the tab terms, if underlined). The authors names could run into them and then the names take up a second line, which makes sense if there are a lot, whereas the four terms hold their place. If this is not possible, then placing the our items on their own line is worth considering although I'm reluctant to push down the real center of attention by taking up another line.

**Comment by stranack** [comment]
We decided to rename the stage to "Copyediting".

On 2015-12-18 3:59 PM, Alec Smecher wrote:
> @stranack <https://github.com/stranack>, do you recall what our decision
> was re: renaming the "Editorial" stage to "Copyediting"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pkp/pkp-lib/issues/943#issuecomment-165923444>.
>

-- 
--
Kevin Stranack, MLIS, MAEd
Learning and Development Consultant
Email: kevin@stranack.ca
Twitter: @stranack
Skype: kstranack
Web: http://stranack.ca

**Comment by asmecher** [comment]
"Editorial" stage renamed to "Copyediting".
