### ISSUE TITLE
Allow plugins to add/modify API endpoints of existing entity

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#9434]
**Describe the problem**
With the merge of https://github.com/pkp/pkp-lib/issues/7698 in the `main branch(Future 3.5.0 LTS)` , slim routing toolset set has been removed as one of the core dependency and the API implementation moved to laravel routing toolset completely . This has made the previously applied hook `APIHandler::endpoints` to tap into and modify/add/update obsolete and removed . 

**Describe the proposal**
Possible enhancement is to bring back the hook similar kind of hook `APIHandler::endpoints` to allow dynamic insertion of API routes on run time using laravel router which oversees the each routing process . This will be helpful for plugins to inject routes to any existing routes collection . 

**What application are you using?**
OJS, OMP or OPS version `main`

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9451
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4081 [TEST ONLY]
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1625 [TEST ONLY]
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/724 [TEST ONLY]

An example plugin to demonstrate the usage of plugin level api implementation at https://github.com/touhidurabir/apiExample

**Additional Information**
Feature request : https://forum.pkp.sfu.ca/t/create-custom-api-handler-ver-3-5/89101/4

**Comment by touhidurabir** [comment]
@asmecher can you please preview the PR at https://github.com/pkp/pkp-lib/issues/9434#issue-1953801910

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I added a review: https://github.com/pkp/pkp-lib/pull/9451#pullrequestreview-1723622313

**Comment by touhidurabir** [comment]
@asmecher can you take a look at the PRs at https://github.com/pkp/pkp-lib/issues/9434#issue-1953801910

**Comment by asmecher** [comment]
@touhidurabir, it's promising, but it feels like the `APIRouter` is trying to be two things at once. I wonder if maybe it's worth coming up with a `PluginAPIRouter` class that lives parallel to `APIRouter`? That would keep `APIRouter` from having to accommodate two distinctly different URL patterns.

**Comment by touhidurabir** [comment]
@asmecher All tests have passed so should be good to merge .

**Comment by asmecher** [comment]
Merged for `main`, thanks, @touhidurabir! But do you think this is worth back-porting to `stable-3_4_0` too?

**Comment by touhidurabir** [comment]
> But do you think this is worth back-porting to stable-3_4_0 too?

@asmecher we don't need to back port it to `stable3-4-0` as it use the Slim for api routing purpose . And `stable-3.4.0` has it's own hook to allow plugin to add api routes .

**Comment by touhidurabir** [comment]
Closing this as this does not need back porting .
