### ISSUE TITLE
Missing locale key on UI library

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9435]
**Describe the bug**
The file `components/ListPanel/submissionFiles/SelectSubmissionFileListItem.vue` is using the locale key `common.uploaded`, which isn't defined in the application.

After skimming the code, I think it should be using `common.uploadedBy` with an extra argument (`this.uploadedBy`).

**What application are you using?**
OJS 3.4

**Comment by jardakotesovec** [comment]
@jonasraoni Hi Jonas, good catch! I think thats correct fix. Do you know in what scenario you would not get the createdAt date? Maybe we did not track createdAt in past?

**Comment by jonasraoni** [comment]
When used to display submission files, the `createdAt` will be always available (the `uploadedBy` may be empty though).
Besides the decision page, this component is also used by [other components](https://github.com/pkp/ui-library/tree/main/src/components/FileAttacher), which are not feeding these properties, I guess that might be the reason.
