### ISSUE TITLE
[OMP] The series field is optional, but it's not possible to revert the selection

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9443]
**Describe the bug**
Once you select a value for the series field on the submission wizard, it's not possible to undo it, we need to have a "None" option for it.

**What application are you using?**
OMP 3.4

**Additional information**
![image](https://github.com/pkp/pkp-lib/assets/361921/d1df5191-e70f-4fae-a691-9baee69d8522)

**Comment by bozana** [comment]
@kaitlinnewson, all good, I have merged it :-)
Then only to forward it to main...
Thanks a lot!

**Comment by kaitlinnewson** [comment]
Forward-ported to main and merged, closing!
