### ISSUE TITLE
[OJS] issueform::execute hook without $issue attached to $form

### ISSUE THREAD

**Issue by henriquejsfj** [pkp/pkp-lib#9449]
**Describe the bug**
There are 2 problems in `IssueForm` `execute` method:
- `parent::execute` calling the Hook in the beginning of the function without any $issue created/attached.
- In the end, when creating new Issue, the Hook is called with `$issue` as argument without attaching the created $issue to the `IssueForm` instance.

<hr>
PRs:

- https://github.com/pkp/ojs/pull/4080 (main)
- https://github.com/pkp/ojs/pull/4092 (stable-3_4_0)

**Comment by henriquejsfj** [comment]
Sorry, I made a PR but since it is in the OJS it is not linked. I don't know how to link between different repo.
See: https://github.com/pkp/ojs/pull/4080

**Comment by bozana** [comment]
Hi @henriquejsfj, thanks a lot!
Yes, that is correct, we crate issues in pkp-lib and put the PR link in the issue...
I have taken a look at your changes and left a comment...
