### ISSUE TITLE
Usage Stats plugin has wrong link to privacy statement

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#9458]
**Describe the bug**
The usage stats plugin can have a side bar block enabled if the privacy stuff is enabled.  This block points to a page that is supposed to contain a link to the journal's privacy page.  The link instead points to the journals about/submissions page.

https://github.com/pkp/usageStats/blob/main/UsageStatsHandler.inc.php#L46

That should instead be 

`$privacyStatementUrl = $router->url($request, null, 'about', 'privacy');`

**What application are you using?**
OJS 3.3.0.15

<hr>

PR:
- https://github.com/pkp/usageStats/pull/56
- https://github.com/pkp/ojs/pull/4083 (usageStats submodule update)

**Comment by bozana** [comment]
@jnugent, would you maybe like to test the patch above?
@jonasraoni, could you please take a look for code review?

**Comment by bozana** [comment]
The link actually calls the plugin's privacyInformation.tpl, but because the router->url() has changed the link was leading directly to the about/submissions page...
