### ISSUE TITLE
Consider start and end date for user roles

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9462]
In order to have information needed for masthead, and considering the Journal Integrity Initiative (JII), we would need to have start and end date for user roles, i.e. we need to add start and end date column to the DB table user_user_groups.

PRs
- https://github.com/pkp/pkp-lib/pull/9529
- https://github.com/pkp/ojs/pull/4105 
- https://github.com/pkp/omp/pull/1497
- https://github.com/pkp/ops/pull/612

**Comment by bozana** [comment]
For the upgrade script that fills the start dates for user roles I go as following:
The min(date_assigned) from DB tables review_assignments and stage_assignments is used as start date. For all other user_user_groups (that are not in those two tables) I take the date of the first publication of that journal. However, there could be journals (that have some user_user_groups) that have not published anything yet, and because we do not have journal installation date (that we could eventually use) those start dates will be NULL. 
Thus I will leave date_start also as nullable for now, and will see if this can be addressed somehow differently later, via the UI.
@asmecher, OK i.e. what do you think?

**Comment by asmecher** [comment]
@bozana, is there any downside to leaving `date_start` null for *all* data that predates this feature? In the past using heuristics to determine values hasn't always been accurate, and the start/end dates should behave predictably when either date is left blank.

**Comment by bozana** [comment]
I am not sure. The start is (maybe) needed for Masthead. But lets discuss it in the JII group...

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR above?
I would need to add the migration script to the upgrade.xml -- I forgot to do that now -- but this I can do next time when I change something... :-)

**Comment by bozana** [comment]
The new columns are minimally considered in the rest of the code, so that everything works as till now. That means, for example:
- If the user is assigned to a submission and then this user's role is ended, the user will see the submission in their queue (but will not be able to view/access it), and the submission will be treated as assigned.
- The ended roles are currently not visible in the UI in the user form.
- Disabling an user does not end their roles -- as it worked till now -- nothing was changed in the user_user_groups table. It maybe also makes sense, because the user can be re-enabled again.
- Removing an user means ending all their roles -- as till now.
- Merging an user means removing all their roles, and assigning the new user to the old user's active roles, with the start date of the merging action.
- Everywhere in the code only active user roles are considered -- it matches the situation till now, where only active roles were in the DB table user_user_groups. At a few places the possibility to consider ended or all user roles is introduced minimally, the rest should be done when we develop further functions around this new functionality.

The further development that would be needed, but maybe in a separate issue, would be:
- extend native import/export
- display all, also ended roles on the user edit form
