### ISSUE TITLE
Sanitize cover image filename in native import

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9464]
When an issue cover image is imported using the native import/export plugin, the filename it is given in the XML is trusted. It should be checked to ensure it's an image file.

**Comment by mfelczak** [comment]
Hi @asmecher, does this also extend to the article cover image?

**Comment by asmecher** [comment]
@mfelczak, yes, it affects OMP and OJS article cover images, and OJS issue cover images as well. The fixes above cover all those cases.

**Comment by asmecher** [comment]
Related CVE: https://karmainsecurity.com/KIS-2023-14 (thanks to Egidio Romano for the report!)
