### ISSUE TITLE
License terms not displayed on article page in certain themes

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#9467]
**Describe the bug**
The contents of the License Terms text field (added in Distribution > License) are supposed to be displayed on the article landing page. Depending on the theme, they are:
- DISPLAYED in: Default, Manuscript, Bootstrap, Material, Gopher
- NOT DISPLAYED in: Pragma, Immersion, Health Science, Classic

**To Reproduce**
1. Add text to the License Terms field under Distribution > License
2. Publish and article
3. Toggle between the themes to see the text displayed or not, as per the themes above

**What application are you using?**
 OJS 3.3.0.8 and 3.3.0.14

![image](https://github.com/pkp/pkp-lib/assets/45104797/5fd05a40-3e28-4d81-84e5-826f22ba6ab0)
![image](https://github.com/pkp/pkp-lib/assets/45104797/3b0724a2-cad3-4236-8c9a-7295809e59a7)

**Comment by kaitlinnewson** [comment]
Hi @librariam, I've filed issues for this in the repositories for the themes so they can be worked on in the next round of updates:

- https://github.com/pkp/pragma/issues/102
- https://github.com/pkp/immersion/issues/100
- https://github.com/pkp/healthSciences/issues/256
- https://github.com/pkp/classic/issues/120

I'm going to close this one in favour of the individual issues in the themes. Thanks for the detailed report!
