### ISSUE TITLE
Use of proxy settings is not consistent

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#947]
In OJS 2.x, config.inc.php defines proxy settings for remote URL calls.
https://github.com/pkp/ojs/blob/ojs-dev-2_4/config.TEMPLATE.inc.php#L469-L482

These settings are used in the FileWrapper classes [HTTPFileWrapper](https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/classes/file/wrappers/HTTPFileWrapper.inc.php) and [HTTPSFileWrapper](https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/classes/file/wrappers/HTTPSFileWrapper.inc.php), but other places call curl directly to fetch remote resources.

For example, the [CrossRef plugin](https://github.com/pkp/ojs/blob/ojs-dev-2_4/plugins/importexport/crossref/CrossRefExportPlugin.inc.php) does so for GET and POST requests.

See: http://forum.pkp.sfu.ca/t/problem-with-crossref-automatic-registration/5440

Possible solutions include enhancing and then consistently using the HTTPFileWrapper and HTTPSFileWrapper classes, or directly referencing the config's proxy settings in curl requests.

**Comment by knjigor** [comment]
I have changed code in CrossRef plugin (/plugins/importexport/crossref/CrossRefExportPlugin.inc.php)
Added lines that define proxy and port at top (around line 260):
```
function registerDoi(&$request, &$journal, &$objects, $filename) {
		$curlCh = curl_init ();
		curl_setopt($curlCh, CURLOPT_PROXY, 'proxy.uns.ac.rs');
		curl_setopt($curlCh, CURLOPT_PROXYPORT, 8080);
		curl_setopt($curlCh, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($curlCh, CURLOPT_POST, true);
		curl_setopt($curlCh, CURLOPT_HEADER, 1);
		curl_setopt($curlCh, CURLOPT_BINARYTRANSFER, true);
```

This is my work around for now, I think that it should be implemented in different way using config file.

**Comment by asmecher** [comment]
@knjigor, can you try the patch linked above? That will tell OJS to use the proxy configuration in the `[proxy]` section of `config.inc.php`. I haven't tested it, so would love to get your confirmation.

**Comment by knjigor** [comment]
I have applied provided patch and crossref plugin is working as expected.

Is there a way to implement a patch for citation plugins that also doesn't use proxy settings [forum.pkp.sfu.ca](http://forum.pkp.sfu.ca/t/problem-with-processing-references-with-citation-markup-assistant/5417)?

**Comment by asmecher** [comment]
@knjigor, I attached some similar fixes to other uses of cURL; does that address your question re: citation plugins?

**Comment by knjigor** [comment]
I have patched all suggested files but processing citations with Citation Markup Assistant is still not working.

Also, I can't find folder 'webservice' in classes actually in OJS 2.4.7.1. last folder in classes is 'user'

**Comment by asmecher** [comment]
See my response to your comment on that commit; I think it'll resolve this.

**Comment by knjigor** [comment]
I have applied all provided patches and services are using proxy now, only one that still doesn't work is Crossref DOI lookup, I still get error:

```The CrossRef's web service call has returned an error when called with the following URL: http://www.crossref.org/openurl/?pid=crossref@ff.uns.ac.rs&noredirect=true&format=unixref&url_ver=Z39.88-2004&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.aufirst=M M&rft.aulast=Kennedy&rft.jtitle=Educational Researcher&rft.atitle=Attribution error and the quest for teacher quality&rft.date=2010&rft.volume=39&rft.issue=8&rft.spage=591&rft.epage=598. It may be that the web service is temporarily unavailable. You'll still be able to work with the remaining services and save your results. You can also try again later. If the error persists then please ask the journal manager to deactivate this service and open a bug report.```

**Comment by asmecher** [comment]
@knjigor, I missed a case; try this patch (in lib/pkp) in addition:
https://github.com/pkp/pkp-lib/commit/e8b34155c9ce37ac21e67681d8a0c479a38f1b59

**Comment by knjigor** [comment]
I have applied patch and citation markup assistant is working as expected.

**Comment by asmecher** [comment]
@knjigor, I'll have to look into that a little -- but can you post it as a question on our support forum?
