### ISSUE TITLE
Data loss at review rounds after migrating from OJS 2.x to +3.3

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9476]
**Describe the bug**
During the OJS 2.x to OJS 3.2.x migration, the table `review_round_files` is filled with review files, see:
https://github.com/pkp/ojs/blob/08e6c0cbd4842beeafaa1cac7f31bb0237e3faf1/dbscripts/xml/upgrade/3.0.0_update.xml#L192-L193

This process might leave the table with series of the same `file_id`s with different `revision`s, which is ok!

Then, when passing through the OJS 3.3.x data migration, the `review_round_files` entity data is consolidated based on the field `file_id`, which leads to data loss, see all duplicated `file_id`s will be discarded and only a possibly random one (lack of `order by`) will be kept:
https://github.com/pkp/pkp-lib/blob/8555405111e143ce46f40abd004701ecff1aa542/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php#L448-L457

The final result is that submissions with several review rounds, might end up with a couple of review rounds without the expected files or with the incorrect revisions of them.

This bug only affects installations that were previously upgraded from OJS 2.x. From OJS 3.0 onwards, new review rounds do not seem to share the `file_id`.

**What application are you using?**
OJS 3.3

**Comment by asmecher** [comment]
Scheduling to 3.4.0-5, but I'm not opposed to committing to the next 3.3.0-x if it's a simple cherry-pick with low risk.

**Comment by jonasraoni** [comment]
@asmecher This is the PR for 3.3.0 https://github.com/pkp/pkp-lib/pull/9488, are you comfortable with it? :)
I'll try to test this patch, together with others, on a couple of OJS 2 > OJS 3 migrations.

**Comment by nwoodward** [comment]
If I understand the bug description correctly does it mean that if we upgraded from 2.x to 3.2.x and then from 3.2.x to 3.3.x there is possible data loss with the review rounds and their files?

**Comment by jonasraoni** [comment]
The description isn't very clear, but that's it.

The review files will not be erased from the disk, but their relationship with the review rounds will.
I'll come back from vacation next week and inspect if it's possible to recover the broken relationships (for those who already upgraded and don't have an old database backup available).

**Comment by nwoodward** [comment]
Gotcha. Thanks for the information. I'm pretty sure the files are still around with the journal, but the database will be really hard to track down, so a solution like what you mentioned would be helpful. Or even for starters just a way to identify if one of our journals is affected by the problem.

**Comment by jonasraoni** [comment]
@nwoodward I've just checked and it's not possible to reassign the files to the review rounds automatically (unless some conditions are met, like number of review rounds = number of found review files).

I just could retrieve the review files of a submission using the query below, which is helpful to proceed with a manual fix:
```sql
SELECT * FROM files WHERE path like 'journals/JOURNAL_ID/articles/SUBMISSION_ID/submission/review/SUBMISSION_ID-%';
```

**Comment by nwoodward** [comment]
Thank you for looking into it. If a user identifies an instance of the problem we'll try to resolve it by hand.

**Comment by jonasraoni** [comment]
This query might be useful to find the cases (i.e. I'm using OJS 3.3), submissions that have at least 2 review rounds, and at least one round without review files:

```sql
SELECT rr.submission_id, rr.round
FROM review_rounds rr
WHERE NOT EXISTS (
	SELECT 0
	FROM review_round_files rrf
    WHERE rrf.submission_id = rr.submission_id
    AND rrf.review_round_id = rr.review_round_id
)
AND (
	SELECT COUNT(0)
    FROM review_rounds rr2
    WHERE rr2.submission_id = rr.submission_id
) > 1;
```
