### ISSUE TITLE
[ OMP ] DOI Chapter url syntax

### ISSUE THREAD

**Issue by franz-dev** [pkp/pkp-lib#9480]
**Describe the bug**
Generated DOI urls are broken because they refer to a wrong path.
es. https://doi.org/123456/mypress.11.c10 will refer to https://myomp.com/index.php/mypress/catalog/book/11/c10

Seems to be that c{chapterid} isn't recognized.

**To Reproduce**
1. Use default DOI suffix `%p.%m.c%c` for chapters
2. Enable DOI for chapters
3. Enable landing page for chapters

**What application are you using?**
OMP 3.4.0-3

**Additional information**
Fix the url by typing `chapter` instead of `c{chapterid}` works fine 

https://myomp.com/index.php/mypress/catalog/book/11/chapter/10

**Comment by bozana** [comment]
@franz-dev, what registration agency do you use i.e. how do you register your DOIs?
I think in OMP we currently only have DOI assignments and no registration agency support, where it is defined to what URL a DOI refers/resolves.
Thus, it seems you are using a plugin or you are creating an XML to register the DOI metadata with the wrong URL.

**Comment by franz-dev** [comment]
Hi @bozana, we'd generated DOIs in previous release (3.3.0-13) with DataCite from @withanage.

**Comment by bozana** [comment]
I am not sure if the plugin has been adapted for 3.4 -- @withanage can tell best -- I think Heidelberg University is working on it right now...
Else, maybe to move this issue to that repository: https://github.com/withanage/datacite.
