### ISSUE TITLE
Search navigation menu item not displayed at site level

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#9483]
**Describe the bug**
Site-wide searching is available in 3.4, but if a site-wide navigation menu includes the search item, it is not displayed. This is because of a flag that hides it at the site-level. Presumably this was in place before site-wide searching was supported.

**To Reproduce**
1. Create an install with at least two public journals.
2. Go to Administration > Site Settings > Site Setup > Navigation
3. Create a navigation menu with the search menu item and assign it to the primary navigation menu slot.
4. See that it doesn't appear.

**What application are you using?**
OJS 3.4.x

**Comment by NateWr** [comment]
@asmecher this is necessary for the UNIANDES client theme. Hopefully a simple review,  merge, and cherry-pick?

PR:
https://github.com/pkp/pkp-lib/pull/9484

Tests only:
https://github.com/pkp/ojs/pull/4094

**Comment by asmecher** [comment]
Done thanks!
