### ISSUE TITLE
Is it possible to get authors to select only one category when submitting?

### ISSUE THREAD

**Issue by kjmcomms** [pkp/pkp-lib#9490]
At step 4 of a new submission (For the editors) I have switched on and created categories, however, I want to limit the choice to only one category, i.e. have a radio button list rather than checkboxes.

Is this possible?

**Comment by asmecher** [comment]
@kjmcomms, could you post questions like this to the [support forum](https://forum.pkp.sfu.ca) rather than opening issues? That's the best place to get help. Thanks!

**Comment by kjmcomms** [comment]
Okay, thank you.
