### ISSUE TITLE
Opción de Modulos en OJS no funciona

### ISSUE THREAD

**Issue by ohelit** [pkp/pkp-lib#9491]
Cordial saludo a toda la comunidad

Necesito de su valiosa colaboración, en el momento cuento con la version 3.1.2.0 del OJS y estoy teniendo el siguiente problema 

![image](https://github.com/pkp/pkp-lib/assets/75231364/6c1431c6-6404-4c24-a158-b7c39e7582c3)

En donde la parte de MODULOS de OJS no carga, ya verifiqué el error.log y no se evidencia ningun resultado

Quedo atento a sus respuestas, mil gracias

**Comment by asmecher** [comment]
@ohelit, could you post in our support forum (https://forum.pkp.sfu.ca) rather than filing an issue? That's the best place to get help. I would recommend also checking your PHP error log for details.
