### ISSUE TITLE
CrossRef XML Export Plugin creating URLs with IP address instead of domain name

### ISSUE THREAD

**Issue by ramanfr** [pkp/pkp-lib#9492]
**Describe the bug**
We use the CrossRef XML Export Plugin to deposit DOIs to Crossref. After we have deposited a DOI and the article is showing the status "Active", if we go to the article's landing page and click on the DOI link, instead of bringing up the URL with the domain name (the article landing page), it brings up a URL with the IP address. So instead of https://domainname/journal/article/view/submissionid, it brings up https://IPaddress/journal/article/view/submissionid, and a "Your connection is not private" page. 

**To Reproduce**
1. Publish an article
2. Deposit the DOI to Crossref
3. Article status shows "Active"
4. Go to article landing page
5. Click on DOI link
6. Get "Your connection is not private" page

**What application are you using?**
 OJS  3.3.0.13

**Additional information**
![notprivate](https://github.com/pkp/pkp-lib/assets/149602851/62a432c5-1b2a-4207-ac11-48f21f07a13c)

**Comment by ramanfr** [comment]
Hi @bozana I see the URL with the domain name...I think. 
Do you mean here? 
<doi_data>
<doi>10.26676/jevtm.v4i2.137</doi>
<resource>https://publicera.kb.se/jevtm/article/view/16918</resource>

**Comment by bozana** [comment]
Yes... Thus I think the problem is somewhere else... The URL deposited with Crossref seems to be OK...

**Comment by bozana** [comment]
Can it be that your domain has changed? That IP address shows me this domain ojs-prod.kb.se and that seems not to work...

**Comment by ramanfr** [comment]
@bozana 
If you use curl to view the doi link you can see that the data has been exported with the host's IP address instead of FQDN

curl https://doi.org/link...
<html><head><title>Handle Redirect</title></head>
<body><a href="[https://IP:443/jevtm/article/view/16918](https://ip/jevtm/article/view/16918)">[https://IP:443/jevtm/article/view/16918](https://ip/jevtm/article/view/16918)</a></body></html>

We need it to export everything under the same name as the service name/FQDN, publicera.kb.se
or we need a settings option to enable the user of suitable FQDN.

In this case, the exposed IP can't be used.

**Comment by bozana** [comment]
@ramanfr, I just do not know why the plugin would use the IP address -- the export and deposit/registration use one and the same function, thus XML looks the same for both (export and deposit/registration), and the URL is taken from the `base_url` setting in the file `config.inc.php`. And it looks (from your comment above) that your XML does contain the correct URL.
Could it be that use used IP address earlier in your config.inc.php?

Else, I do not know where else in the chain (from export/registration till DOI's URL resolve) this could happen and how :-(

Could you maybe try two things:
- Export XML for one article, and double check that the URLs there (in the XML document) are correct. Then upload it manually in the Crossref portal. After some time double check if clicking on that article's DOI link leads to a correct page.
- Chose another article (with the same problem), export the XML, and double check that the URLs there are correct. Then register that article from within OJS again. After some time double check if clicking on that article's DOI link leads to a correct page.

Lets first try these two things, then we can see further... -- I do not know if it is possible to see the XML that the Crossref got from you, when you registered those article DOIs? Or maybe to ask Crossref, if they would know how the XML looks like and if it contained IP addresses?

**Comment by ramanfr** [comment]
@bozana Thanks so much for your help troubleshooting this issue! 

I tried both things you suggested, and in both cases, after about a day, the DOI links led to the correct page. 

I don't know if this is any help, but this is something strange I noticed: if I export the XML for an article that has the problem, the URL in the exported XML is correct; however, when I check the metadata that is sent to Crossref for the same article (by adding the doi number to the end of https://doi.crossref.org/search/doi?pid=support@crossref.org&format=unixsd&doi=), I see that the IP number is in the URL. Does that shed any light on what is going on?

**Comment by bozana** [comment]
Hi @ramanfr, I do not know why those IPs are there...  The reason I can think of is that you maybe at some point had the IP address in your config.inc.php, but... 
But now, when I use that Crossref URL to check the DOI 10.26676/jevtm.v4i2.137 from above, I see the correct URLs.
Thus, maybe you can re-register all your problematic DOIs again?

**Comment by ramanfr** [comment]
Hi @bozana We haven't ever had the IP in the config.inc.php, so it really is a mystery. I could potentially reregister the DOIs, but I would have a hard time tracking them all down (we have a multi-journal installation with 23 journals). And even if I were able to fix all the problematic ones, this issue keeps cropping back up, so it won't be sustainable over the long term. Not sure where to go from here...if you have any other suggestions, I'll be happy to try them!

**Comment by bozana** [comment]
Hi @ramanfr, what do you think with "this issue keeps cropping back up"?

**Comment by ramanfr** [comment]
Hi @bozana What I mean is that we've had this problem before, then it seemed to be fixed for a while, then it started happening again. I don't know if that gives any hint or indication of what might be the root cause. Do you think load balancer settings could be implicated?
