### ISSUE TITLE
Unable to deposit dois for crossref. seemed to be related to XML

### ISSUE THREAD

**Issue by johnnyzhz** [pkp/pkp-lib#9502]
**Describe the bug**
When we tried to deposit dois to Crossref, we receive the following error:

```
Error: cvc-pattern-valid: Value '10.xxx/' is not facet-valid with respect to pattern '10\.[0-9]{4,9}/.{1,200}' for type '#AnonType_doi'.
Error: cvc-type.3.1.3: The value '10.xxx/' of element 'doi' is not valid.

<?xml version="1.0" encoding="UTF-8"?>
<doi_batch_diagnostic status="completed" sp="ds3.crossref.org">
   <submission_id>1596662090</submission_id>
   <batch_id>_1699647180</batch_id>
   <record_diagnostic status="Failure">
      <doi />
      <msg>Error: cvc-pattern-valid: Value '10.xxx/' is not facet-valid with respect to pattern '10\.[0-9]{4,9}/.{1,200}' for type '#AnonType_doi'.
Error: cvc-type.3.1.3: The value '10.xxx/' of element 'doi' is not valid.
</msg>
   </record_diagnostic>
   <batch_data>
      <record_count>1</record_count>
      <success_count>0</success_count>
      <warning_count>0</warning_count>
      <failure_count>1</failure_count>
   </batch_data>
</doi_batch_diagnostic>
```
On our server, it logged the error ` Filter output validation failed, expected "schema(https://www.crossref.org/schemas/crossref5.3.1.xsd)", but found "object", referer: https://xxx/dois`

It seemed that the XML was not generated correctly. However, I don't know how to display the content of the xml.

**To Reproduce**
1. Go to 'DOIs'
2. Select an article
3. Click on 'Deposit DOI(s)'

**What application are you using?**
 OJS 3.4.0.3

**Additional information**
Recently upgraded to 3.4.0.3.

Thanks a lot for your help!

**Comment by asmecher** [comment]
@johnnyzhz, can you raise this in the support forum (https://forum.pkp.sfu.ca) rather than filing an issue here? If it turns out to be a bug in the software, we'll return to this.

**Comment by johnnyzhz** [comment]
Will do. Thanks!
