### ISSUE TITLE
[A11Y] Add information about required fields with asterisks in forms

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#9503]
## Issue Description
Some input and text fields in Login and Register User forms use an asterisk (*) to indicate that the control is required. However, it is important that the asterisk meaning is defined at the start of the form. Some users may have some issues to understand why the asterisk is on such fields and it will state clearly the purpose of the element on the interface.

## How to reproduce / Current behavior
1. Access a journal
2. Click on "Login" or "Register"
3. See the fields with asterisk
4. There is no message or instructions regarding it.

## What application are you using?
 OJS version 3.3.0 / 3.4.0

## Stack used 
- Device: Laptop
- OS: MacOS
- Browser: Firefox / Chrome / Edge

## Testing method
- Method: Manual - Keyboard

## Action
Adding instruction like:  `<p> Required fields are marked with an asterisk (*).</p>` would be enough to remediate it and increase the accessibility of the form.

W3C provides examples of indicating required form controls that can be checked here:
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H90#H90-examples

### Current view:
![Image](https://github.com/pkp/pkp-lib/assets/4992902/823d6b30-1ce3-44c6-a6a6-115170abb93d)

### Remediation mockup:
![Image](https://github.com/pkp/pkp-lib/assets/4992902/b8b7fd2f-b193-4780-b40e-c1102918411a)

**Comment by israelcefrin** [comment]
Hi @asmecher 
Could you please review this PR https://github.com/pkp/pkp-lib/pull/9507

**Comment by asmecher** [comment]
@israelcefrin, I've merged that -- but it'll need forward-porting to `stable-3_4_0` and `main`. (It's up to your judgement whether you want to code this all the way back to `stable-3_3_0` for that reason!)

**Comment by israelcefrin** [comment]
> @israelcefrin, I've merged that -- but it'll need forward-porting to `stable-3_4_0` and `main`. (It's up to your judgement whether you want to code this all the way back to `stable-3_3_0` for that reason!)

Hi @asmecher , given 3.3 is still LTS and many PKP-PS clients are using I think I will keep porting between these versiosn. Also, Default Theme on OJS3.3 is the very first to focus on Accessibility. 
Do we have any formal process to port it to 3.4 and main, .e.g.: open a new issue? Or is it just creating new PR against these 2 branches?

**Comment by israelcefrin** [comment]
Hi @asmecher ,

Here is the porting to OJS 3.4
https://github.com/pkp/pkp-lib/pull/9510

**Comment by asmecher** [comment]
All merged, thanks!
