### ISSUE TITLE
Backport ArticleSearch getTitle() bug fix to OJS 3.3.0 stable

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#9524]
**Describe the bug**
When limiting the site search to a specific journal, the following bug occurs:

[21-Nov-2023 16:53:55 Europe/Zurich] PHP Fatal error:  Uncaught Error: Call to undefined method Journal::getTitle() in /usr/local/hope/www/ojs/classes/search/ArticleSearch.inc.php:192

**What application are you using?**
 OJS version 3.3.0-15, Lucene plugin

**Solution**
Please backport the fix in line 207 of main https://github.com/pkp/ojs/blob/65b914a613f3bfceb152e699e9dd6dbfde2eebcf/classes/search/ArticleSearch.php#L207C56-L207C56

to line 192 in OJS 3.3.0 stable

**Comment by asmecher** [comment]
Fixed -- unfortunately this just missed the 3.3.0-16 release, but it'll be included in 3.3.0-17! Thanks for reporting, @mpbraendle.
