### ISSUE TITLE
Visual testing with storybook and chromatic

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9527]
I would like to introduce visual testing to our workflow to increase our test coverage for UI. This would be in addition to our end to end tests with focus on component testing.

### Steps to take
- Migrate our ui-library to use storybook
- Setup storybook with service for visual testing - chromatic.com, which is using storybook to run component tests
- Having automatic CI integration using github actions which would run tests for any PR against ui-library

### Benefits we would get from that
- Storybook has additional capabilities like mocking network communication, which would help us testing also more complex components that communicate with API endpoints
- Storybook supports user interaction testing using [testing-library](https://storybook.js.org/docs/react/writing-tests/interaction-testing) to do component functional testing
- When used with testing service from chromatic - storybook becomes two purpose solution - documentation and testing tool
- We will be able to test our components using different contexts (right to left language, maybe additional language, in future we might want to also test smaller screen sizes)

**Comment by d-ivashchuk** [comment]
hey @jardakotesovec accidentally stumbled on your repo while searching for something on GitHub :D if you would want to add visual tests that would be totally free to use for your(as OSS project). I would love if you gave lost-pixel.com a try! it's an open source alternative to Chromatic and has first class citizen support for storybook visual regression testing!

**Comment by jardakotesovec** [comment]
@asmecher @jonasraoni @eirikhanssen 
Migration is complete, the previous docs tool is now removed, so this is ready to be closed.

Only thing that would be nice to get reviewed is the new documentation related to the technical roadmap change.

I temporarily duplicated the files to be reviewed so we can take advantage of the github review process where its simple to comment anywhere.

https://github.com/pkp/ui-library/pull/328

You can see the docs live here - https://main--6555d3db80418bb1681b8b17.chromatic.com/

Any feedback on clarity, wording, missing topics, language (fixing grammer, typos) is appreciated.

**Comment by asmecher** [comment]
Thanks, @jardakotesovec! It looks very good. I've proposed some grammar changes -- there are lots of them, all trivial, so I just sent a [PR to your fork](https://github.com/jardakotesovec/ui-library/pull/1).

**Comment by jardakotesovec** [comment]
@asmecher Thanks a lot, merged.

**Comment by jardakotesovec** [comment]
Language improvements from @asmecher are now merged to main. Thank you. Time to finally close this one.

**Comment by asmecher** [comment]
Thanks, @jardakotesovec!
