### ISSUE TITLE
Add ability to save metadata without completing submission

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#953]
Step 3 of the author's submission process ends with the "Finish" button, which completes the submission. Users might want to enter the cataloging metadata and save it without formally completing the submission, allowing them to return later when they're ready.

**Comment by bozana** [comment]
@asmecher, this issue seem to be solved: now there ist the step `4. Confirmation` with the button `Finish Submission` and the user does not have to click on it -- he/she can go back to one of the previous steps, if needed... Correct so?

**Comment by asmecher** [comment]
Yes, I think so!
