### ISSUE TITLE
No stylesheet loaded on frontend when not in press context and logged out

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#954]
This seems to only effect multi-press contexts. If you go straight to index.php, there will be no press context and it will prompt you to login. No stylesheet is getting loaded. Once logged in, it directs to a press and the stylesheet loads.

**Comment by asmecher** [comment]
Nate, that should've been fixed by this:
https://github.com/pkp/omp/commit/a816ad768347dfab0fe07dc29b59168efa804266
...but for existing installs, you'll need to...

    insert into site_settings (locale, setting_name, setting_value, setting_type) values ('', 'themePluginPath', 'default', 'string');

**Comment by NateWr** [comment]
:+1:
