### ISSUE TITLE
[OJS] internal server error 500 on ListRecords/Identifiers/Identify

### ISSUE THREAD

**Issue by arielsartorio** [pkp/pkp-lib#9544]
Hi, i have problems in my site https://ojs.emerj.com.br/index.php/revistadaemerj/oai when i try to list the next

ListRecords
Identify
ListIdentifiers
return to me a error 500, i don't know what happens, because ListSets & ListMetadataFormats it's ok

php -v PHP 7.3.33
ojs-3.3.0-16

And the php error log:
[Tue Nov 28 17:27:43.921950 2023] [autoindex:error] [pid 25148:tid 47108111214336] [remote 45.166.79.41:49873] AH01276: Cannot serve directory /home/emerjco/ojs.emerj.com.br/public/journals/3/: No matching DirectoryIndex (index.php,index.html,index.php7,index.php5,index.perl,index.pl,index.plx,index.ppl,index.cgi,index.jsp,index.jp,index.phtml,index.shtml,index.xhtml,index.htm,index.js) found, and server-generated directory index forbidden by Options directive, referer: https://ojs.emerj.com.br/index.php/direitoemmovimento/$$$call$$$/page/page/css?name=stylesheet

**Comment by asmecher** [comment]
@arielsartorio, can you post your question to our support forum (http://forum.pkp.sfu.ca) rather than filing an issue? That's the best place to get help.
