### ISSUE TITLE
"xmlEscapeEntities: char out of range" error when exporting issues through the Native XML plugin

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9546]
**Describe the bug**
When exporting through the native XML, the message `xmlEscapeEntities : char out of range` might be displayed, and it fails the export.

**Solution**
Passing the encoding to the `DOMDocument` is enough to address the issue.

**What application are you using?**
OJS 3.3

**PRs**
- **`stable-3_3_0`**
- https://github.com/pkp/pkp-lib/pull/9547
- https://github.com/pkp/ojs/pull/4114
- https://github.com/pkp/omp/pull/1491
- https://github.com/pkp/ops/pull/606
- **`stable-3_4_0`**
- https://github.com/pkp/crossref-ojs/pull/41
- https://github.com/pkp/crossref-ops/pull/33
- https://github.com/pkp/pkp-lib/pull/9571
- https://github.com/pkp/ojs/pull/4122
- https://github.com/pkp/ops/pull/607
- https://github.com/pkp/omp/pull/1492
- `main`
- https://github.com/pkp/COUNTER/pull/5
- https://github.com/pkp/crossref-ojs/pull/42
- https://github.com/pkp/crossref-ops/pull/34
- https://github.com/pkp/pkp-lib/pull/9572
- https://github.com/pkp/ojs/pull/4123
- https://github.com/pkp/ops/pull/608
- https://github.com/pkp/omp/pull/1493

**Comment by asmecher** [comment]
@jonasraoni, no objections here; could you forward-port this to `stable-3_4_0` and `main`, and also to OMP and OPS?

**Comment by jonasraoni** [comment]
Yep, I'll update everywhere and merge.
