### ISSUE TITLE
[UI] Improvement to grids with scroll-for-more-results

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#955]
Several of the grids no longer reveal more on scroll, likely due to style adjustments I made a while ago. We need to check each grid and ensure it actually works as intended.

Also, the feature is nice, but not initially intuitive. Usually endless scrolling occurs when the component is the primary or sole content on the page, and happens naturally during browser scroll. I think we should consider adding a "more" button next to the "5 of 10 items" text to make this clearer.

While we're at it: "1 of 10 Items" should be "1 of 10 items" (lowercase)

**Comment by asmecher** [comment]
@beghelli wrote the infinite scrolling; he might be able to help with debugging.

**Comment by beghelli** [comment]
@NateWr @asmecher will take a quick look, it should be something simple related to the markup

**Comment by beghelli** [comment]
Discovered what it is. There used to be an height value to trigger grid scrollbar, now it seems that it is gone. If you manually change the height to something smaller than the grid actual height, the scrolling works again. I will take a look to what @NateWr changed and will try to adapt.

**Comment by NateWr** [comment]
Yes, not all grids are necessarily the same height now (the Active grid, for instance). That's why I suggested that we need to scan all grids.

I think a "Load more items" or "View more items" button would kill two birds with one stone: it would be a fallback so we don't have to worry so much about grid height and would also improve awareness and keyboard accessibility.

**Comment by beghelli** [comment]
I've made a comment where the change was introduced and the scrolling stopped working. I explained why I did it that way, will wait for your opinion @NateWr. Thanks.

**Comment by NateWr** [comment]
@beghelli I'm ok if you want to restore the `max-height` setting and set grid height programmatically in JavaScript.

I'm a little nervous about relying on the height calculation. For instance, if people resize the browser and this changes the height of rows, it can cause problems. We can recalculate with the `.onresize` event (be sure to throttle though!) and do other things to fix the problem, it's just a lot more manual work. But it's probably our best simple solution at the moment.

I'd still recommend we consider a More Items link of some kind, or perhaps we need better visual indication of how to get more items.

I'm not sure if this is an OMP 1.2 issue or something we kick down the road. Perhaps once the functionality is fixed we can ask Kevin to incorporate it into his user tests to see if people are getting it.

**Comment by beghelli** [comment]
Done, I a gree with the more items link. Adding that now.

**Comment by beghelli** [comment]
@NateWr , please, take a look, see if that's what you were thinking...

**Comment by NateWr** [comment]
@beghelli Thanks! I'm getting a permissions error when I try to load more items in the Dashboard > Active grid:

`The current role does not have access to this operation.`

Can you reproduce the problem?

Also, I was having some issues with the loading row triggering the scroll event over and over again. I thought it would be better to take the loading element out of the row list:

![load-more](https://cloud.githubusercontent.com/assets/2306629/11808656/920d60e8-a319-11e5-85ad-ce7d7160c4da.gif)

Would you be willing to check [my work](https://github.com/NateWr/pkp-lib/commit/b96497c3984cb92a70865a7e2a8a0ca6e8747d19). I'm sure I've unintentionally broken something.

I'm not sure if it's related to my changes but I get this in my apache error log when I load the active grid:

```
[Tue Dec 15 10:38:10.182174 2015] [:error] [pid 18467] [client 192.168.0.8:40084] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/omp/lib/pkp/classes/controllers/grid/GridCellProvider.inc.php on line 50, referer: http://192.168.0.8/omp/index.php/publicknowledge/dashboard
```

**Comment by beghelli** [comment]
@NateWr I've tested your work here an everything works fine. I have no problems with authorization, can you send me your database dump? BTW, great improvement. :)

**Comment by beghelli** [comment]
@NateWr the grid row error is probably related to the press name. That will be fixed when we remove that column. The authorization is also related to getting submissions from another context that you don't have access to, I think. I will remove that column and will make this list context specific and check if this solves both problems. Thanks for your dump. :)

**Comment by NateWr** [comment]
:+1:

**Comment by asmecher** [comment]
(I'm leaving this up to the two of you, BTW -- if you want my intervention you'll have to ask for it :)

**Comment by asmecher** [comment]
^ The above commits remove a bunch of support for the multi-context dashboard.

**Comment by beghelli** [comment]
Tested again with the more recent changes, and the scrolling and the submission lists are working. @asmecher Are you going to remove the leftover from OJS also?

**Comment by asmecher** [comment]
The changes were pretty much all in pkp-lib, @beghelli -- do you see something I missed?

**Comment by beghelli** [comment]
No, but you needed to stop using PKPContext naming in OMP land also, here: https://github.com/pkp/omp/commit/8fca1d741e3948c82a5ae63870ca0e3a7e58303d I thought it would be necessary to do something like that in OJS...

**Comment by asmecher** [comment]
Already done: https://github.com/pkp/ojs/commit/1110e154cd7f5232c1b792518cba0c119670436c

**Comment by asmecher** [comment]
@NateWr and @beghelli, are you satisfied with what's been done on this issue?

**Comment by NateWr** [comment]
@asmecher Looks great. Thanks Bruno. I just issued my PR with the style adjustments.

@beghelli Is there an easy way to give a grid a larger default height? Particularly on the pages where there's just one grid (Active/Archived submissions) I think it makes sense to show 20-30 rows before needing to load more.

**Comment by beghelli** [comment]
@NateWr Yes, you can define in the grid php class how many rows you want it to show at once. Just implement the getItemsNumber() method.

**Comment by NateWr** [comment]
Thanks @beghelli. I've upped the count on Active and Archived grids to 20. https://github.com/pkp/pkp-lib/pull/997

I'm a bit worried about the double-scroll bar with tall grids, though. What can happen is that the user ends up trying to scroll down but scrolls the outer window (and can't access the hidden items) or tries to scroll the grid area but a chunk of the grid is out of the viewport.

Take a look and let me know what you think. Would it be possible on very large grids to support "scroll-for-more" but disable scrolling? So only the "Load more" button is used?

In general, the scrolling is better. But for the few grids we have like this where they're the only element on the page, it might be better just to show a whole bunch of rows with the load more button.

What do you think?

**Comment by beghelli** [comment]
yes, that seems a little bit confusing. I like the idea of removing the scroll for some grids. Maybe I can try to trigger the load more items event using the page scroll for grids that are likely to be the only thing at the page. What do you think?

**Comment by NateWr** [comment]
Yeah if you think you can pull it off. I presume you'll just check the scroll position against the bottom of the grid and, if it's scrolled into view, fire it off? Sounds like a good idea.

**Comment by beghelli** [comment]
Done @NateWr 

Now the active grid is responding to the page scroll down. I will let this open until you take a look and see if that's ok.

**Comment by NateWr** [comment]
Great! I probably won't look until after Christmas though.

**Comment by beghelli** [comment]
No problem, have fun! :)

**Comment by NateWr** [comment]
Finally took a look at this. Looks good to me! Can you do the same with the Archive grid?

**Comment by beghelli** [comment]
No :)

**Comment by beghelli** [comment]
I think this is ready, @NateWr can we close it?

**Comment by NateWr** [comment]
Lovely!
