### ISSUE TITLE
## signs in title tag

### ISSUE THREAD

**Issue by loadbrain** [pkp/pkp-lib#9551]
title tag has ## around words

In a plugin I set the title with

```
        $templateMgr->assign([
            'pageTitle' => __('plugins.generic.browseByAuthor.authors'),
        ]);
```

Works fine as far as the title tag from ‘plugins.generic.browseByAuthor.authors’ is now surrounded by “##”

This is what it looks like:

`<title>##Autoren## | OMP</title>`

What happens here?

Using OMP 3.4.0-3*

**Comment by asmecher** [comment]
@loadbrain, could you post your question on the support forum (https://forum.pkp.sfu.ca) rather than filing an issue? Thanks!
