### ISSUE TITLE
Add masthead option to user roles

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9552]
Implement the possibility for JM to define if a role should be considered and displayed on/in the masthead. This should be a further option in the add/edit role form.

PRs:
- https://github.com/pkp/pkp-lib/pull/9603
- https://github.com/pkp/ojs/pull/4138
- https://github.com/pkp/omp/pull/1499
- https://github.com/pkp/ops/pull/614

**Comment by bozana** [comment]
@asmecher, could you please review the PRs above? 
Thanks a lot!

**Comment by asmecher** [comment]
@bozana, looks good -- the plan is to allow individual registrations for a user group to override the user group's "default", right?

**Comment by bozana** [comment]
Hi @asmecher, yes, I understand that the JII users will not have the possibility to change it on the invitation page, but the others will have that possibility, i.e. for the other there will be a possibility to define it on the user level, if a user will be considered for the masthead). Is this what you mean?

**Comment by asmecher** [comment]
I am at risk of forgetting our thought process on this :) but I think it will not be uncommon for journals to want e.g. some editors listed on the masthead, others not. No matter how much everyone swears before we code it that this won't happen. :)

So the default role configuration for Editors should be `masthead=true`, as you've currently coded it :+1:

...but...

When an invitation is sent, the user who creates it (typically the journal manager) should also have a checkbox for the masthead status (only showing for user groups with `masthead=true`) allowing them override it and hide certain enrolments. The user receiving the invitation maybe will be informed of it, but won't be able to change it.

**Comment by bozana** [comment]
Yes, this is so. There will be a select box with "Appears on the Masthead" and "Does not appear in the Masthead", that JM can choose from for each users and role the user is invited in.
Hmmm... Maybe there should then also be the masthead select box on the user edit form, so that JM can change it later? (e.g. if users change their mind)... :thinking: 
But, for JII plugin users there will not be this possibility, as far as I understand.

**Comment by bozana** [comment]
Ah, yes, correct. This is also on my list, the change of the user edit form according to the second image here: https://github.com/pkp/pkp-lib/issues/9271#issuecomment-1700822600. So yes, there will then also be the select box on the user edit form... :-)
I will then merge this and proceed with the UIs next... :-)

**Comment by bozana** [comment]
So actually, we would also need a masthead column in the user_user_groups table? :thinking:

**Comment by asmecher** [comment]
> So actually, we would also need a masthead column in the user_user_groups table? 🤔

Yes, I think so!
