### ISSUE TITLE
Error Upgrade Ojs 2.4.8.5 > 3.2.1.4

### ISSUE THREAD

**Issue by devmainme** [pkp/pkp-lib#9569]
Good afternoon friends!

a doubt when running the update command I come across this error > PHP Fatal error: Uncaught Exception: DB Error: ERROR: invalid input syntax for integer: “” Query: INSERT INTO submission_galley_settings (galley_id, setting_name, setting_value, setting_type) VALUES ( ?, ?, ?, ?) in /opt/data/html/lib/pkp/classes/db/DAO.inc.php:703

Does anyone know how to treat it?

**Comment by asmecher** [comment]
Cross-posted:

https://forum.pkp.sfu.ca/t/error-upgrade-ojs-2-4-8-5-3-2-1-4/83890

@devmainme, it's best to pick just one place to post a question, and the support forum is the best place. I'll close this and continue the conversation over there.
