### ISSUE TITLE
Add support for author's competing interests statement

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9574]
**Describe the bug**
An author Competing Interest statement used to be an option in OJS 2.x, but was removed with OJS 3.0 (not sure if on purpose).

It has been requested as a feature again e.g. in the Support Forum:

https://forum.pkp.sfu.ca/t/competing-interests-authors/38181

It's also a requirement for the Journal Integrity Initiative, which displays information on author CI disclosures.

**Comment by bozana** [comment]
Maybe also of interest here: https://gitlab.com/ubiquitypress/ojs-plugin-competing-interests

**Comment by asmecher** [comment]
Thanks, @bozana; see related: https://forum.pkp.sfu.ca/t/competing-interests-plugin-for-ojs3/59592/19

**Comment by asmecher** [comment]
PRs for `stable-3_3_0`:
- https://github.com/pkp/pkp-lib/pull/9576
- https://github.com/pkp/ojs/pull/4124 (only for testing and removal of locale keys moved to `lib/pkp`)

Notes:
- See the forum thread linked [above](https://github.com/pkp/pkp-lib/issues/9574#issuecomment-1856677456) for a discussion of whether CI statements live with the submission or with the author record. When we move to invitation-based author participation as part of the GDPR work on 3.5, it'll become even more important for co-authors to enter or confirm data like this by invitation. I opted to keep the CI statement at the author level.
- I kept the journal setting name ([`requireAuthorCompetingInterests`](https://github.com/pkp/ojs/blob/857b5bbcd68f74c28b4659a97a8bc4313f5f2091/classes/manager/form/setup/JournalSetupStep3Form.inc.php#L38)) and author setting name ([`competingInterests`](https://github.com/pkp/ojs/blob/857b5bbcd68f74c28b4659a97a8bc4313f5f2091/classes/article/Author.inc.php#L53)) the same as their OJS2 equivalents. This should mean that OJS2 users who have carried the data forward to OJS3 should see this feature resume functioning as before.
- This adds identical support to OMP and OPS as well.
- A couple of additional locale keys are introduced, but are only relevant when the CI feature is enabled in Setup; this means existing 3.3.0-x installs won't be negatively affected by missing translations.
- Notably, the CI Statements are **not** displayed anywhere other than the author settings form. (@Devika008, this should go on the list of things that need consideration for changes to the default theme.)

In the Publication Facts Label, rather than a stand-alone CI page as per the test data, I opted to make it a pop-over:
![image](https://github.com/pkp/pkp-lib/assets/200411/024c5c6c-835a-43eb-b1dd-aa7bdd4ddfc4)

## Next Steps
- [ ] If 3.3.0-x implementation is OK, forward-port to `stable-3_4_0` and `main`

**Comment by asmecher** [comment]
@bozana, could you have a look at the approach described above and the PRs? Thanks! Also could use a look from you, @Devika008.

**Comment by willinsky** [comment]
Great approach, Alec. I can see this pop-over being used for the competing interests, data availability (with hyperlink), and funders PFL elements. The only question I have is that this information is typically included in the PDF at the end of the study, because the PDF circulates independently of the journal. Presumably, anyone preparing the PDF could include this data and there wouldn't be problem with including it when it comes to converting XML or HTML to PDF.

**Comment by asmecher** [comment]
@willinsky, yes, it would be up to whoever prepares the PDF to include the information, and the Publication Facts Label (plugin) wouldn't be involved in presenting it in that case.

**Comment by bozana** [comment]
Hi @asmecher, I have taken a look and it looks good to me.
I think Crossref and DataCite do not have a field for author's competing interests. Crossref has competing_interest_statement for peer_review, which I think we do not push yet...

**Comment by asmecher** [comment]
All merged to `stable-3_3_0`, `stable-3_4_0`, and `main`; the availability of this data on the front end (beyond the PFL plugin) will wait for the default template review. This will ship with 3.3.0-17 and 3.4.0-5.
