### ISSUE TITLE
Browse plugin produces fatal error on journal homepage

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#9579]
**Describe the bug**
If 1+ categories have been created and you enable the Browse plugin a fatal error is produced and the journal homepage is not accessible.

**To Reproduce**
1. As JM, create a new Category
2. As JM, enable the Browse plugin
3. Access the journal homepage

**What application are you using?**
OJS 3.4.0-3

**Comment by asmecher** [comment]
@mfelczak, can you post the error from the log?

**Comment by jnugent** [comment]
@asmecher  this is the error:

`
PHP Fatal error:  Uncaught Error: Call to a member function getIsInactive() on null in cache/t_compile/0e409079d545b1713553b5bf9154a29e849820bf_0.plugins-11-plugins-blocks-browse-blocks-browse.block.tpl.php:44
`

**Comment by asmecher** [comment]
@jnugent and @mfelczak, https://github.com/pkp/browse/commit/2ead2792fe2ef41c26234f5a74567a1ca3f6f22f (applied in `plugins/blocks/browse`) should fix it.

**Comment by nibou230** [comment]
Hi @asmecher, the object `Category` still doesn't have any method `getIsInactive`. There is still a missing piece, but maybe I'm missing something?

**Comment by asmecher** [comment]
:cry: That's a second error in the same line of code! Thanks, @nibou230, I've removed the check entirely; it's related to sections, not categories.
