### ISSUE TITLE
[UI] Display of identifiers on frontend needs to be looked at

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#958]
The section which displays pub IDs displays even though it's got nothing to display.

![pubids-empty](https://cloud.githubusercontent.com/assets/2306629/11400127/65c0c250-9383-11e5-9c9a-547c6cccabc3.png)

I may need a bit of a briefing on identifiers to figure out how the data is structured and we want it to display.

**Comment by asmecher** [comment]
@NateWr, remind us to talk about this on Monday.

**Comment by NateWr** [comment]
The main blocker for me is that I don't really understand how the data is loaded into the template file and, therefore, how I'm meant to access and retrieve it. I copied over the pub formats data in the templates but doubt their accuracy:

https://github.com/pkp/omp/blob/master/templates/frontend/objects/monograph_full.tpl#L262-L355

This is the main issue in #958. So these are some of the questions I need answering before I can do anything:

1. Is there any test data with identifiers? Or how can I get identifiers going to test them? The DOI plugin is enabled and seems to be configured but I can't find anything.

2. What can have identifiers? Books, chapters, pub formats, files? The template only goes looking in pub formats but from our discussion that seems wrong.

3. The template looks for identifier codes and pub id types. What's the difference?

**Comment by bozana** [comment]
Hi @NateWr,

I can speak for DOI i.e. pub id plugins, the other part I don't know: The code addressing pub ids is https://github.com/pkp/omp/blob/master/templates/frontend/objects/monograph_full.tpl#L324-L339
I.e. the template gets the types of the enabled pub id plugins (at the moment only DOI, but there could be others as well, e.g. URN) and then it looks if the publication format has a pub id and in that case the pub id will be displayed (like this: DOI:  http://dx.doi.org/10.12345/doiSuffix, e.g. s. this article page: https://www.querelles-net.de/index.php/qn/article/view/1173).
Before template, in the catalog book handler the enabled pub id plugins are went through and the pub ids stored for all appropriate publication formats: https://github.com/pkp/omp/blob/master/pages/catalog/CatalogBookHandler.inc.php#L85-L100.
If you edit a publication format there should be a pub id preview, but I don't see it -- so maybe it's currently different in OMP -- I'll double check.

**Comment by NateWr** [comment]
Thanks @bozana. I was able to find the ONIX settings and set an ISBN-13 value. So to summarise:

1. ONIX available but DOI doesn't appear to be shown in OMP yet.

2. Only pub formats in OMP 1.2.

3. ONIX = identifier coders. DOI and other plugins = pub id types.

The existing display is not too bad actually:

![pub-format-identifiers](https://cloud.githubusercontent.com/assets/2306629/12751573/d161990e-c9b5-11e5-80c8-f9272fa65737.png)

I wonder how common it will be for different pub formats to have different identifiers. Either way, if that's where the data is we'll probably want to display the identifiers alongside the pub format download details.

**Comment by bozana** [comment]
Yes :-)
I believe ISBN and DOI are pretty common and both could exist, s. for example the Complete Book drop-down here http://langsci-press.org/catalog/book/18 or the data under the book cover here http://heiup.uni-heidelberg.de/catalog/book/43. For the others I don't know :-\

**Comment by asmecher** [comment]
This is the ONIX weirdness we were speaking about on Monday. Eventually we'll need to be able to attach identifiers to files, publication formats, submissions, and series -- and maybe more entities too. Limiting the set to less than that is guaranteed to make someone unhappy. But we're not planning to port Bozana's identifier work to OMP until after 1.2, so for now, the current identifier assignment (ONIX data for ISBNs etc, and DOI plugin for DOIs) is what we have to work with.

**Comment by NateWr** [comment]
Thanks @bozana, armed with that info I've made a couple of adjustments to downloads and pub format information. From the commit message:

> This commit adjusts the display of file downloads and publication
format details depending on the number or formats and files. If
a format has only one file, it will display a large download
link with the format named in the link. If a format has multiple
files, it will present an itemized download presentation.
>
> If there is only one publication format, it will list details
such as pub ids, pub dates, etc without naming the format. If
there are multiple publication formats, it will list these under
a heading with the name of the format.

Multiple files but only one pub format:

![pub-details-one-format](https://cloud.githubusercontent.com/assets/2306629/12784161/637ee914-ca7d-11e5-872e-f9a71099a62e.png)

Multiple pub formats but only one file each:

![pub-details-one-file](https://cloud.githubusercontent.com/assets/2306629/12784165/7001e3b2-ca7d-11e5-93f2-d5ac4fdf044b.png)

I still haven't done anything with files associated with chapters, but if we want this for OMP 1.2 then we should create a new issue I think. I'd need to set up test data and dive into how the relationships are identified in the data.

**Comment by NateWr** [comment]
PR here: https://github.com/pkp/omp/pull/209
