### ISSUE TITLE
Migration from 3.4.0.4 to 3.5.0.0

### ISSUE THREAD

**Issue by efcjunior** [pkp/pkp-lib#9580]
I cloned from the **main branch** and tried to do the upgrade.

![image](https://github.com/pkp/pkp-lib/assets/2645720/cc7985ea-a4be-4681-b01f-13dd43109070)

When I ran php tools/upgrade.php upgrade I got only this log without any detail about it:

![image](https://github.com/pkp/pkp-lib/assets/2645720/2bb2f69b-779b-485d-bad2-5ce7a710ac60)

**Systems Tools Versions**

- MYSQL 8.0
- PHP 8.2
- Ubuntu 22

These commands also were executed:

![image](https://github.com/pkp/pkp-lib/assets/2645720/40ee52a9-6128-4626-aead-98f0c68e647d)

**Comment by asmecher** [comment]
@efcjunior, the `main` branch is unreleased code under heavy development, and should not be expected to be stable. You probably want the `stable-3_3_0` or `stable-3_4_0` branch.
