### ISSUE TITLE
False "save" confirmation leads to keyword loss

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#9592]
**Describe the bug**
Keywords entered in the metadata have to be followed by hitting "enter" in order to be recorded. However it's possible to add them without hitting "enter" in the end. There is no error message. Clicking "save" gives a false positive confirmation that the keywords are saved. Navigating away or refreshing the page shows that the keywords are lost.

This is quite common in journals where a comma separated string of keywords is pasted in its entirety from a manuscript document, and the system shows no indication that anything should be done differently.

**To Reproduce**
1. Go to Publication > Metadata > Keywords
2. Enter any number of keywords without hitting "enter"
3. Click "Save" at the bottom of the page - observe the "Saved" checkmark
4. Navigate away or refresh the page
5. Observe the keywords not being there

False save (without hitting "enter" after each keyword) :
![image](https://github.com/pkp/pkp-lib/assets/45104797/2b7e7661-8a0e-4d38-ac98-5360ece7b45c)

Proper save (hitting "enter" after each keyword):
![image](https://github.com/pkp/pkp-lib/assets/45104797/a94c60b3-a059-4d40-a537-94b61ef8b6c6)

**What application are you using?**
 OJS 3.3.0.14

**Comment by asmecher** [comment]
@jardakotesovec, if you're looking for a UI front-end tweak side quest...

**Comment by jardakotesovec** [comment]
@librariam Oki, the behaviour which we have in 3.5 is that if users does not hit enter/tab it will erase the input, so its obvious nothing will be persisted. Will try to bring same behaviour to 3.3 as I understand as its easy pitfall. 

And its feasible to also break it down to individual keywords if you copy&paste *keyword1, keyword2, keyword3* and hit enter. Currently it creates one keyword `keyword1, keyword2, keyword3`, which is not great.

But wondering whether its safe to assume that we want to split it every time we see comma as separator. I can't think of why comma would be part of the keyword, but its hard to be sure when serving the whole world. :-) Any thoughts whether we want to stick with original behavior when you have to enter them individual or do 'comma separating' magic?

**Comment by librariam** [comment]
Thanks for taking a look @jardakotesovec. Bringing 3.5 behaviour into 3.3 will be an improvement for sure.

I agree that it's hard to predict all use cases for commas in keywords - and whether a comma would be the only possible separator.

An alternative approach I've seen is a separate field for each keyword. It doesn't stop people from copy-pasting a string of keywords into one field, but it is more visually intuitive that that's what it's meant for. It does make for a more cluttered submission form display.

**Comment by jardakotesovec** [comment]
Alright, so will just clear the input when clicking outside of input (blur).

Tagging @Devika008 so she can collect feedback for future iterations of keyword input.


@ewhanson Can you please review? Hate to solve things with setTimeout, but this seems only reasonable way in current setup. In 3.5 its build on different library and this workaround is not necessary anymore.

3.4: https://github.com/pkp/ui-library/pull/314
3.3: https://github.com/pkp/ui-library/pull/315

**Comment by ewhanson** [comment]
Hey @jardakotesovec, the code looks good to me. 👍 

But I wonder about applying this to the `<vue-autosuggest>` component across the board. It solves the keyword issue, but can potentially lead to some confusing interactions in other places the autosuggest field is used. The one instance I looked at specifically is in 3.4, in the DOI management page, where you can filter by issue. Now, as expected, if you click outside before you've selected an issue, it will remove the input. I'm not sure if this is an okay trade off for the keyword issue, but wanted to point it out.

**Comment by jardakotesovec** [comment]
@ewhanson Ok.. lets think about this more. Because in any case thats how it behaves in 3.5 across the autocomplete use cases, so if thats undesirable its good to identify it.

How I look at it is - that text in autocomplete input does not do anything (its not used for filtering, its not saved), unless you hit enter and select something. Therefore removing it after you click somewhere else is imo good indication that nothing is selected there. And having just text there does not do anything.

And in DOI interface I think it works the same - until you select issue with enter - it does not actually filter it by issue, right? So if you type something in..  and click outside it gets removed to indicate nothing is really selected..

**Comment by ewhanson** [comment]
Thanks @jardakotesovec. That makes sense and sounds good to me. 👍

**Comment by jardakotesovec** [comment]
Closing this one as this particular problem was addressed by cleaning up the input if its not properly entered with enter. And we still have to figure out better way to input keywords -  #9754
