### ISSUE TITLE
illegal string offset ojs 3.2.1.4

### ISSUE THREAD

**Issue by devmainme** [pkp/pkp-lib#9601]
After updating js 2.4.8.5 to 3.2.1.4 we noticed many errors including: some pdfs of some magazines do not appear even though they are in the database and files_dir folders and also this illegal string offset error, can anyone help me?

ojs > 3.2.1.4
php > 7.4
apache > 2.4.5.8
postgre > 9

log php apache: 

[Tue Jan 09 02:28:55.491461 2024] [php7:notice] [pid 3136619] [client 10.200.10.                                                                                        11:36836] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:55.494986 2024] [php7:warn] [pid 3136619] [client 10.200.10.11                                                                                        :36836] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:55.496880 2024] [php7:notice] [pid 3136619] [client 10.200.10.                                                                                        11:36836] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:55.496998 2024] [php7:notice] [pid 3136619] [client 10.200.10.                                                                                        11:36836] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:55.497165 2024] [php7:notice] [pid 3136619] [client 10.200.10.                                                                                        11:36836] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:55.497528 2024] [php7:notice] [pid 3136619] [client 10.200.10.                                                                                        11:36836] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:55.500054 2024] [php7:warn] [pid 3136619] [client 10.200.10.11                                                                                        :36836] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:55.537801 2024] [php7:notice] [pid 3136619] [client 10.200.10.                                                                                        11:36836] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:55.556136 2024] [php7:notice] [pid 3136619] [client 10.200.10.                                                                                        11:36836] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:55.574200 2024] [php7:notice] [pid 3136619] [client 10.200.10.                                                                                        11:36836] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:55.574316 2024] [php7:notice] [pid 3136619] [client 10.200.10.                                                                                        11:36836] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.019282 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Illegal string offset 'es_ES' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.019327 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Illegal string offset 'en_US' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.019472 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.026417 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.030724 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Illegal string offset 'es_ES' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.030752 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Illegal string offset 'en_US' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.030895 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.033024 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.033124 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.033281 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.033447 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.033568 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.033619 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.033802 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.033939 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.034098 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.034250 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.034360 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.034521 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.035299 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.038430 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Illegal string offset 'es_ES' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.038458 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Illegal string offset 'en_US' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.038602 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.088038 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.133540 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.133990 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Cannot modify header information - headers already sent by                                                                                         (output started at /opt/data/html/lib/pkp/classes/template/PKPTemplateManager.i                                                                                        nc.php:973) in /opt/data/html/lib/pkp/classes/template/PKPTemplateManager.inc.ph                                                                                        p on line 917
[Tue Jan 09 02:28:56.134012 2024] [php7:warn] [pid 3136620] [client 10.200.10.11                                                                                        :36846] PHP Warning:  Cannot modify header information - headers already sent by                                                                                         (output started at /opt/data/html/lib/pkp/classes/template/PKPTemplateManager.i                                                                                        nc.php:973) in /opt/data/html/lib/pkp/classes/template/PKPTemplateManager.inc.ph                                                                                        p on line 918
[Tue Jan 09 02:28:56.156192 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.156302 2024] [php7:notice] [pid 3136620] [client 10.200.10.                                                                                        11:36846] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.472450 2024] [php7:warn] [pid 3136621] [client 10.200.10.11                                                                                        :36856] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.481370 2024] [php7:notice] [pid 3136621] [client 10.200.10.                                                                                        11:36856] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.485191 2024] [php7:warn] [pid 3136621] [client 10.200.10.11                                                                                        :36856] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.487181 2024] [php7:notice] [pid 3136621] [client 10.200.10.                                                                                        11:36856] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.487299 2024] [php7:notice] [pid 3136621] [client 10.200.10.                                                                                        11:36856] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.488180 2024] [php7:notice] [pid 3136621] [client 10.200.10.                                                                                        11:36856] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.489196 2024] [php7:notice] [pid 3136621] [client 10.200.10.                                                                                        11:36856] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.490271 2024] [php7:notice] [pid 3136621] [client 10.200.10.                                                                                        11:36856] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973
[Tue Jan 09 02:28:56.494441 2024] [php7:warn] [pid 3136621] [client 10.200.10.11                                                                                        :36856] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/cl                                                                                        asses/core/DataObject.inc.php on line 135
[Tue Jan 09 02:28:56.536210 2024] [php7:notice] [pid 3136621] [client 10.200.10.                                                                                        11:36856] PHP Notice:  Deprecated call without request object. in /opt/data/html                                                                                        /lib/pkp/classes/template/PKPTemplateManager.inc.php on line 973

**Comment by devmainme** [comment]
ojs also reports unserialize errors even though the database has utf8, correct collation, anyway I don't know what to do...

**Comment by asmecher** [comment]
@devmainme, could you post your question on the PKP community forum (https://forum.pkp.sfu.ca) rather than opening an issue here? That's the best place to get help.

**Comment by devmainme** [comment]
cool @asmecher link post forum: https://forum.pkp.sfu.ca/t/ojs-3-2-1-4-error-after-upgrade/85039
