### ISSUE TITLE
Error when changing the section during submission

### ISSUE THREAD

**Issue by henriquejsfj** [pkp/pkp-lib#9604]
**Describe the bug**
I got error when trying to change the section during the submission progress.

Going deeper, the cause of the error was a PUT request to submission without payload that led to Slim Application Error on server when trying to edit with `null` as `$params`.

**What application are you using?**
 OJS version 3.4.0.1

**Comment by asmecher** [comment]
@henriquejsfj, can you include the error message/stack trace?

**Comment by henriquejsfj** [comment]
@asmecher you was very fast haha

The stack trace (until # 4):

Slim Application Error:\nType: TypeError\nMessage: PKP\\API\\v1\\submissions\\PKPSubmissionHandler::getWriteDisabledErrors(): Argument # 2 ($params) must be of type array, null given, called in /var/www/html/lib/pkp/api/v1/submissions/PKPSubmissionHandler.php on line 587\nFile: /var/www/html/lib/pkp/api/v1/submissions/PKPSubmissionHandler.php\nLine: 1642\nTrace: #0 /var/www/html/lib/pkp/api/v1/submissions/PKPSubmissionHandler.php(587): PKP\\API\\v1\\submissions\\PKPSubmissionHandler->getWriteDisabledErrors('submission', NULL)\n#1 [internal function]: PKP\\API\\v1\\submissions\\PKPSubmissionHandler->edit(Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Array)\n#2 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Array)\n#3 /var/www/html/lib/pkp/lib/vendor/slim/slim/Slim/Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(PKP\\core\\APIResponse), Array)\

**Comment by asmecher** [comment]
Merged, thanks! This may be necessary to forward-port to `main`, but that code has been swapped over to Laravel rather than Slim, so I suspect it'll behave differently.
