### ISSUE TITLE
Plugin UsageStats: Fatal error for zero bytes salt file on PHP 8.0

### ISSUE THREAD

**Issue by kirchnerf** [pkp/pkp-lib#9613]
**Describe the bug**
If the salt file has 0 bytes, a PHP fatal error occurs when reading the file with fread in UsageStatsPlugin.inc.php line 694.

**What application are you using?**
 OJS version 3.3.0.16

**Additional information**
PHP 8.0.30

`PHP Fatal error:  Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0 in /ojs/plugins/generic/usageStats/UsageStatsPlugin.inc.php:694\nStack trace:\n#0 /ojs/plugins/generic/usageStats/UsageStatsPlugin.inc.php(694): fread()\n#1 /ojs/plugins/generic/usageStats/UsageStatsPlugin.inc.php(403): UsageStatsPlugin->_writeUsageEventInLogFile()\n#2 /ojs/lib/pkp/classes/plugins/HookRegistry.inc.php(107): UsageStatsPlugin->logUsageEvent()\n#3 /ojs/lib/pkp/plugins/generic/usageEvent/PKPUsageEventPlugin.inc.php(125): HookRegistry::call()\n#4 /ojs/lib/pkp/classes/plugins/HookRegistry.inc.php(107): PKPUsageEventPlugin->getUsageEvent()\n#5 /ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php(1186): HookRegistry::call()\n#6 /ojs/pages/index/IndexHandler.inc.php(67): PKPTemplateManager->display()\n#7 /ojs/lib/pkp/classes/core/PKPRouter.inc.php(397): IndexHandler->index()\n#8 /ojs/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()\n#9 /ojs/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()\n#10 /ojs/lib/pkp/classes/core/PKPApplication.inc.php(360): Dispatcher->dispatch()\n#11 /ojs/index.php(68): PKPApplication->execute()\n#12 {main}\n  thrown in /ojs/plugins/generic/usageStats/UsageStatsPlugin.inc.php on line 694, referer: https://www.example.de/`

**Comment by jonasraoni** [comment]
@bozana I don't have write access to the usageStats, so merge this one me:
- https://github.com/pkp/usageStats/pull/57
