### ISSUE TITLE
Adding a new not null column in PostgreSQL leads to an error if the table contains entries

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9617]
**Describe the bug**
s.https://forum.pkp.sfu.ca/t/institutional-subscriptions-break-upgrade-to-ojs-3-4-0-4-from-3-3-0-16/85125
Here we add a new not null column institution_id: https://github.com/pkp/ojs/blob/main/classes/migration/upgrade/v3_4_0/I6895_Institutions.php#L33, that leads to a "Not null violation" error. Thus, consider a default value there.

PRs:
stable-3_4_0: https://github.com/pkp/ojs/pull/4144
main: https://github.com/pkp/ojs/pull/4151

**Comment by bozana** [comment]
@asmecher, could you please see the PR above? Thanks a lot!

**Comment by asmecher** [comment]
@bozana, that looks good to me. Please go ahead!
