### ISSUE TITLE
Plugin DataCite-Export: Registration of article DOIs fails

### ISSUE THREAD

**Issue by kirchnerf** [pkp/pkp-lib#9623]
**Describe the bug**
When executing the DOI registration via a cronjob (not the Acron plugin), the process fails with the following error message: 

`PHP Fatal error:  Uncaught Error: Call to a member function url() on null in /ojs/plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php:723
Stack trace:
#0 /ojs/plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php(221): DataciteXmlFilter->createRelatedItemsNode()
#1 /ojs/lib/pkp/classes/filter/Filter.inc.php(449): DataciteXmlFilter->process()
#2 /ojs/classes/plugins/PubObjectsExportPlugin.inc.php(391): Filter->execute()
#3 /ojs/plugins/importexport/datacite/DataciteInfoSender.inc.php(135): PubObjectsExportPlugin->exportXML()
#4 /ojs/plugins/importexport/datacite/DataciteInfoSender.inc.php(73): DataciteInfoSender->_registerObjects()
#5 /ojs/lib/pkp/classes/scheduledTask/ScheduledTask.inc.php(146): DataciteInfoSender->executeActions()
#6 /ojs/lib/pkp/classes/cliTool/ScheduledTaskTool.inc.php(111): ScheduledTask->execute()
#7 /ojs/lib/pkp/classes/cliTool/ScheduledTaskTool.inc.php(95): ScheduledTaskTool->executeTask()
#8 /ojs/lib/pkp/classes/cliTool/ScheduledTaskTool.inc.php(67): ScheduledTaskTool->parseTasks()
#9 /ojs/tools/runScheduledTasks.php(34): ScheduledTaskTool->execute()
#10 {main}
  thrown in /ojs/plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php on line 723`

The problem is that the dispatcher of the request object is NULL. There is already a fix for OJS 3.4 with commit [8062831](https://github.com/pkp/pkp-lib/commit/8062831a1ea80c2574d415c25e6138d2cca83a88) which solves the problem in PKPRequest.php. The problem only occurs if the journal or article does not have an ISSN.

**What application are you using?**
 OJS version 3.3.0.16

**Additional information**
PHP 8.0.30

PRs:
stable-3_3_0: https://github.com/pkp/ojs/pull/4150

**Comment by bozana** [comment]
Hi @kirchnerf, would it be possible for you to test this fix: https://github.com/pkp/ojs/pull/4150 ?

**Comment by kirchnerf** [comment]
Hi @bozana, I'll give it a try on our test system later today.

**Comment by kirchnerf** [comment]
Works like a charm, thank you!
