### ISSUE TITLE
[OMP] Smarty prevents adding contributor

### ISSUE THREAD

**Issue by FSaldanha** [pkp/pkp-lib#9630]
**Describe the bug**
When trying to add a contributor to an open submission, there is a error with the message "Failed Ajax request or invalid JSON returned". There seems to be some issue with Smarty. Please see below what I found in the log:

```
[21-Jan-2024 09:26:45 America/Fortaleza] PHP Fatal error:  Uncaught Error: Call to a member function getData() on null in /home3/<user>/public_html/publicacoes/cache/t_compile/502a3c7e2e32fa61fb30b380b67fb26018d497e4^06932f1259fee8e7c6747e1a2b9752b223abefd1_0.app.controllersgridusersautho.php:25
Stack trace:
#0 /home3/<user>/public_html/publicacoes/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_65833cda6985a9_02757935(Object(Smarty_Internal_Template))
#1 /home3/<user>/public_html/publicacoes/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /home3/<user>/public_html/publicacoes/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /home3/<user>/public_html/publicacoes/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render in /home3/abpedu29/public_html/publicacoes/cache/t_compile/502a3c7e2e32fa61fb30b380b67fb26018d497e4^06932f1259fee8e7c6747e1a2b9752b223abefd1_0.app.controllersgridusersautho.php on line 25
```

**To Reproduce**
Open a submission, go to Catalog tab, try to add a contributor and see the error.

**What application are you using?**
OMP version 3.1.2.4

**Additional information**
![screenshot](https://github.com/pkp/pkp-lib/assets/628565/fce05fca-1fbd-4a68-a7f4-b268e9840ea2)

**Comment by asmecher** [comment]
@FSaldanha, could you post on the support forum (https://forum.pkp.sfu.ca) rather than filing an issue here? That's the best place to get help. But a heads-up -- you're likely to get a "we don't support OJS 3.1.2 any more" response; I'd strongly recommend upgrading to OJS 3.3 or 3.4 when you get the chance.
