### ISSUE TITLE
Manuscript reverts to Review stage after late review submission in Production phase

### ISSUE THREAD

**Issue by carzamora** [pkp/pkp-lib#9631]
**Describe the bug**
Reviewers who have not completed the review process can still perform their review even when the manuscript is in the Production stage. Furthermore, when they submit their review, the manuscript reverts to the previous stage, under the Review tab.

**To Reproduce**

1. Request a review, for example from three reviewers.
2. Two reviewers approve the manuscript and request changes; you continue the process with their two reviews.
3. However, you left the third reviewer active, assuming they would no longer participate in the process.
4. Months later, when the manuscript is already in production, the third reviewer can still submit their review.
5. If the third reviewer submits their review, the process returns to the Review tab.

**What application are you using?**
 OJS 3.2.1.4 (but if this was not reported before, I asume it is still a bug)

**Comment by Vitaliy-1** [comment]
Hi @carzamora,

I'm unable to reproduce it in later versions - 3.3 and 3.4. OJS 3.2.1 was released 3 years ago and is no longer supported. I suggest upgrading. Feel free to reopen this issue with reproduction steps if it nevertheless appears in 3.3 or 3.4.
