### ISSUE TITLE
Opening category in OPS/OMP causes 500

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9632]
**Describe the bug**
On reader side, if I click on category page won't load and PHP crashes with following error:

```
[Thu Jan 18 11:41:08 2024] [::1]:60076 [500]: GET /index.php/publicknowledge/preprints/category/biology - Uncaught TypeError: PKP\category\Category::getLocalizedDescription(): Return value must be of type string, null returned in /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/classes/category/Category.php:112
Stack trace:
#0 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/cache/t_compile/487b610351ebf9d7c64f1869ee8d77745c23a9cb^5d0ca16a7c78afd59d26eb1b852e00f92f50a8d9_0.app.frontendpagescatalogCategory.tpl.php(48): PKP\category\Category->getLocalizedDescription()
#1 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_65a8fe6233ea99_67429392(Object(Smarty_Internal_Template))
#2 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1)
#5 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, '487b610351ebf9d...', NULL, 1)
#6 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/classes/template/PKPTemplateManager.php(1326): Smarty_Internal_TemplateBase->display('frontend/pages/...', NULL, '487b610351ebf9d...', NULL)
#7 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/pages/catalog/PKPCatalogHandler.php(113): PKP\template\PKPTemplateManager->display('frontend/pages/...')
#8 [internal function]: PKP\pages\catalog\PKPCatalogHandler->category(Array, Object(APP\core\Request))
#9 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#10 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#11 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#12 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#13 /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/index.php(21): PKP\core\PKPApplication->execute()
#14 {main}
  thrown in /Users/jarda/git/pkp/pkp-3_4_0/ops-3_4_0/lib/pkp/classes/category/Category.php on line 112
```

**To Reproduce**
1. Go to OPS Main landing page
2. Click on any category below Search field
3. It returns 500 error

**What application are you using?**
OMP or OPS version 3.4.0-4

**Comment by jardakotesovec** [comment]
There is report on forum as well - https://forum.pkp.sfu.ca/t/omp-3-4-0-4-categories-not-working/84895/3

**Comment by jardakotesovec** [comment]
Crash comes from Category.php, when `getLocalizedDescription(): string` is called, because its supposed to return string (not null).

And the [changes](https://github.com/pkp/pkp-lib/pull/9259/files#diff-2118a3e58f59d92657598067643b23437cc111d5b846389245005efeeb90d1ddR66) in 3.4.0-4 - changed little bit how `getLocalizedData` works. Because now its using `empty` function even on individual values, it decides there is nothing to return when in database are only empty string and it falls back to `null`. Previously it would fallback to first value, which is empty string, because there was empty string in database (`{"en":"","fr_CA":""}`). 

Its possible to easily fix it by changing the type to:
```
    public function getLocalizedDescription(): ?string
```
But wanted to first check with you, whether we have some conventions for empty string vs null. I would expect that for API we normalise it to empty string, even if its null. But internally not sure.

@asmecher @touhidurabir

**Comment by asmecher** [comment]
Yep, I'm satisfied to relax `string` to `?string` in this case, thanks!

**Comment by asmecher** [comment]
Just a quick follow-up after some further conversation with @jardakotesovec -- it looks like we have two cases elsewhere in the codebase:

- `getLocalized...` returns a `string` (no `null` allowed): This is done in cases where the field is required
- `getLocalized...` returns a `?string`: This is done in cases where the field is optional

So longer-term decisions around the strict use of `null`s aside, we have an existing convention that works, and grepping the codebase didn't turn up any other cases where we have a mismatch like this one.

**Comment by jardakotesovec** [comment]
@asmecher ok, in that case very simple PRs:

3.4: https://github.com/pkp/pkp-lib/pull/9644
main: https://github.com/pkp/pkp-lib/pull/9645

**Comment by asmecher** [comment]
Forgive me all the discussion over literally a 1 byte change :) Thanks, @jardakotesovec!
