### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by hasanatkhawaja01** [pkp/pkp-lib#9633]
I installed OJS 3.4.0.4 on Cpanel and attached it to my domain. but after complete installation everything is working but when i or any user upload file for submission or any thing it show error i.e "Slim Application Error". Kindly guide step by step how to resolve it so it will be easier for me. i am trying this from yesterday but still not resolved.

![Screenshot 2024-01-22 165854](https://github.com/pkp/pkp-lib/assets/157375256/9b19541d-71ac-401a-ac94-2bd62c9eee43)

**Comment by asmecher** [comment]
@hasanatkhawaja01, can you post your question on our support forum (https://forum.pkp.sfu.ca)? That's the best place to get help. Include the contents of your PHP error log.
