### ISSUE TITLE
Migrations can be re-executed at OJS 3.4

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9637]
**Describe the bug**
The `upgrade.xml` has an entry (see: https://github.com/pkp/ojs/blob/d5a1be7d5e20ca95da229ca3824dab10d588b6c7/dbscripts/xml/upgrade.xml#L215-L218), that might re-execute the migrations whenever the user upgrades to a newer minor version.

At this moment the latest release is 3.4.0.4, and the migrations above look like extra fixes for the 3.4. Therefore, the `maxversion` should be probably 3.4.0.3.

On the `main` branch, there's a different issue, looks like some migrations won't be executed if the user is migrating from a version released earlier than `3.4`.

**To Reproduce**
1. User upgrades to 3.4.0.4
2. The migrations will be executed
3. User upgrades to 3.4.0.5 (next release), the current `maxversion` will still fit, and the migrations will probably be re-executed (hopefully without errors, then it's not a bad issue YET).

Extra care should be taken when introducing minor migrations, which is something that we didn't do much before.

**What application are you using?**
OJS 3.4

**Additional information**
Source https://github.com/pkp/ojs/pull/4147#pullrequestreview-1833204835

**Comment by jonasraoni** [comment]
According to @bozana these are the versions where each migration was introduced:
- I9136_MigrateUniqueSiteId: 3.4.0.1
- I9231_FixMetricsIndexes: 3.4.0.2
- I9627_AddUsageStatsTemporaryTablesIndexes: 3.4.0.5/3.4.1

**Comment by jonasraoni** [comment]
@asmecher, please check if it makes sense, then I'll spread the updates:
- https://github.com/pkp/ojs/pull/4158
- https://github.com/pkp/ojs/pull/4159

**Comment by asmecher** [comment]
Looks good to me; please go ahead.
