### ISSUE TITLE
Resolve template injection with context name

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9650]
**Describe the bug**
The context name (e.g. journal name in OJS or site name) is susceptible to Vue template injection (e.g. `{{ 4*5 }}` will present as `20` rather than as a literal string.

After some review, the impact of this issue is fortunately low -- the affected fields are for privileged users, who already (intentionally) have tools to e.g. enter arbitrary Javascript in certain fields. Injectability requires:
- The content must be inserted into back-end template markup (e.g. using Smarty)
- The content must not be added to the DOM dynamically, i.e. it must be present in the initial page generation.

We were not able to identify other cases meeting these requirements.

**What application are you using?**
 OJS, OMP or OPS version 3.4.0

Reported by Daniel Barros.

**Comment by asmecher** [comment]
PRs:
- `stable-3_3_0`: https://github.com/pkp/pkp-lib/pull/9653
- `stable-3_4_0`: https://github.com/pkp/pkp-lib/pull/9654
- `main`: https://github.com/pkp/pkp-lib/pull/9655

**Comment by asmecher** [comment]
@jardakotesovec, could you review the PRs? I've tested them here. Thanks!

**Comment by jardakotesovec** [comment]
3.4.0
ojs (only tests): https://github.com/pkp/ojs/pull/4180
pkp-lib: https://github.com/pkp/pkp-lib/pull/9711

**Comment by asmecher** [comment]
Sorry for the headache, @jardakotesovec, but could you reformat the `stable-3_3_0` changes with tabs instead of spaces? (At some point this will go away!)

**Comment by jardakotesovec** [comment]
@asmecher should be better now..

**Comment by asmecher** [comment]
Thanks! There was an accidental submodule update, but I removed it. I'll file a new issue for `main` so we don't forget to deal with 3.5.0 and forward.

**Comment by jardakotesovec** [comment]
Ops, not sure how that happened. Sorry about that.
