### ISSUE TITLE
[UI] [Submission] Indicate role is required when adding contributor

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#966]
During submission you can add a contributor. When doing so, the role is required, but it's not indicated in the form.

**Comment by NateWr** [comment]
When the form reloads with the error, there are duplicate "* Denotes Required Field" elements in the modal.

**Comment by asmecher** [comment]
The duplicate required field warning can be fixed by moving the message div into the form element, IIRC.

**Comment by asmecher** [comment]
@NateWr, is this ready to be closed?

**Comment by NateWr** [comment]
Yep! [merged PR](https://github.com/pkp/pkp-lib/pull/976)
