### ISSUE TITLE
No user can create a category in ojs 3.3.0 or 3.2.1.4

### ISSUE THREAD

**Issue by devmainme** [pkp/pkp-lib#9662]
**Describe the bug**
I have roles as managing editor and editor in ojs 3.3.0 I use php 7.4, linux, apache I try to create a category and it gives an error like "The current role does not have permission to perform this operation." or error in ajax data

**To Reproduce**

access the magazine that I am the manager of, click on configuration > magazine > categories > create category and get this error

**What application are you using?**
 OJS VERSION 3.3.0

**Additional information**
LOGS APACHE:

[Fri Jan 26 23:35:46.939590 2024] [php7:notice] [pid 3150902] [client 10.200.10.10:44372] Database query\nSELECT * FROM journals WHERE path = ?\n["lib"]
[Fri Jan 26 23:35:46.940447 2024] [php7:notice] [pid 3150902] [client 10.200.10.10:44372] Database query\nSELECT\t* FROM navigation_menu_items WHERE path = ? and context_id = ? and type= ?\n["pkp\\/lib\\/vendor\\/tinymce\\/tinymce\\/skins\\/lightgray\\/skin.min.css.map",0,"NMI_TYPE_CUSTOM"]
[Fri Jan 26 23:35:46.940606 2024] [php7:notice] [pid 3150902] [client 10.200.10.10:44372] ojs2: 404 Not Found
[Fri Jan 26 23:35:46.942091 2024] [php7:notice] [pid 3150902] [client 10.200.10.10:44372] Database query\nUPDATE sessions\n\t\t\t\tSET\n\t\t\t\t\tuser_id = ?,\n\t\t\t\t\tip_address = ?,\n\t\t\t\t\tuser_agent = ?,\n\t\t\t\t\tcreated = ?,\n\t\t\t\t\tlast_used = ?,\n\t\t\t\t\tremember = ?,\n\t\t\t\t\tdata = ?,\n\t\t\t\t\tdomain = ?\n\t\t\t\tWHERE session_id = ?\n[705916,"10.200.10.10","Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/121.0.0.0 Safari\\/537.36",1706322935,1706322946,1,"userId|i:705916;username|s:6:\\"karlag\\";csrf|a:2:{s:9:\\"timestamp\\";i:1706322941;s:5:\\"token\\";s:32:\\"e15d4fe0d26a20e7f73c5f8b8d09e55e\\";}","ojs.homologa.ufpr.br","s0on5eerq1vob7533e50dpad8v"]
[Fri Jan 26 23:35:48.546382 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT * FROM sessions WHERE session_id = ?\n["s0on5eerq1vob7533e50dpad8v"], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.547709 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT * FROM users WHERE user_id = ?\n[705916], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.548782 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT * FROM user_settings WHERE user_id = ?\n[705916], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.550721 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nDELETE FROM sessions WHERE session_id = ?\n["s0on5eerq1vob7533e50dpad8v"], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.552151 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nINSERT INTO sessions\n\t\t\t\t(session_id, ip_address, user_agent, created, last_used, remember, data, domain)\n\t\t\t\tVALUES\n\t\t\t\t(?, ?, ?, ?, ?, ?, ?, ?)\n["s0on5eerq1vob7533e50dpad8v","10.200.10.10","Mozilla\\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/16.0 Safari\\/605.1.15",1706322948,1706322948,0,"","ojs.homologa.ufpr.br"], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.553088 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT * FROM journals WHERE path = ?\n["acaomidiatica"], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.555483 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT * FROM journal_settings WHERE journal_id = ?\n[62], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.555673 2024] [php7:warn] [pid 3150903] [client 10.200.10.10:41658] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/classes/core/DataObject.inc.php on line 133, referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.556512 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT * FROM site\n[], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.557168 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT * FROM site_settings\n[], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.558106 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSET TIME ZONE INTERVAL '+0:00' HOUR TO MINUTE\n[], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.562914 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT v.*\n\t\t\tFROM versions v LEFT JOIN plugin_settings ps ON\n\t\t\t\tlower(v.product_class_name) = ps.plugin_name\n\t\t\t\tAND ps.setting_name = 'enabled' AND (context_id = ? OR v.sitewide = 1)\n\t\t\tWHERE v.current = 1 AND (ps.setting_value = '1' OR v.lazy_load <> 1)\n[62], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.566604 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT setting_name, setting_value, setting_type FROM plugin_settings WHERE plugin_name = ? AND context_id = ?\n["defaultthemeplugin",62], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.570371 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT * FROM journals WHERE path = ?\n["acaomidiatica"], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.571529 2024] [php7:notice] [pid 3150903] [client 10.200.10.10:41658] Database query\nSELECT * FROM journal_settings WHERE journal_id = ?\n[62], referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context
[Fri Jan 26 23:35:48.571713 2024] [php7:warn] [pid 3150903] [client 10.200.10.10:41658] PHP Warning:  Illegal string offset 'pt_BR' in /opt/data/html/lib/pkp/classes/core/DataObject.inc.php on line 133, referer: https://ojs.homologa.ufpr.br/acaomidiatica/management/settings/context

**Comment by asmecher** [comment]
Can you post this on our support forum at https://forum.pkp.sfu.ca? That's the best place to get help. I'd recommend disabling `debug` in `config.inc.php`, to reduce the noise from database queries; and include anything that's generated by trying to create a category after that's done. Also include the exact version you're using (the logs appear to be from 3.2.1-4 but you also mention a 3.3.0-x build).
