### ISSUE TITLE
Use jobs chain for usage stats log files processing

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9664]
Use a job for usage stats log file processing, split the job CompileUsageStatsFromTemporaryRecords into several jobs, and chain all usage stats jobs:

Above all the function removeDoubleClicks() and compileUniqueClicks() executed in the job CompileUsageStatsFromTemporaryRecords take some time for a huge installations (e.g. ca. 50sec. for 20000 rows). In order to avoid a timeout, the job CompileUsageStatsFromTemporaryRecords can be separated into several smaller jobs.

Till now the scheduled task UsageStatsLoader has been used to read an usage stats log file and insert the entries into the usage stats temporary tables. Then the job CompileUsageStatsFromTemporaryRecords would compile the stats form the temporary tables. Because the job is executed asynchronously/at some later point, it could happen that the UsageStatsLoader will fill the temporary tables with new data, from the next log file, while the job CompileUsageStatsFromTemporaryRecords still have not compiled the stats from the previous log file. Which leads to a huge amount of data in the temporary tables, which makes the processing difficult and can cause a timeout. (This is above all the case when the user wants to reprocess the old log files -- the old log files need to be reprocessed for the whole month). Thus, the log file processing (parsing and inserting into the temporary tables) can be done from a job as well. Also, all the usage stats jobs needs to be chained i.e. they need to be executed one after another -- so that no job can write into the temporary tables before the other has finished, but also to ensure the correct stats when the job CompileUsageStatsFromTemporaryRecords is separated into several jobs.

The scheduled task UsageStatsLoader would log a message if something would be wrong with a line in the log file, or if the inserting the line into the temporary tables would not work for some reason, however this would not stop the scheduled task from working and processing other log file lines. A similar solution would be needed for jobs -- a way of logging or informing a user that something was wrong with a line.

PRs:
stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/9672
- https://github.com/pkp/ojs/pull/4164
- https://github.com/pkp/omp/pull/1511
- https://github.com/pkp/ops/pull/627

main:
- https://github.com/pkp/pkp-lib/pull/9710
- https://github.com/pkp/ojs/pull/4179
- https://github.com/pkp/omp/pull/1520
- https://github.com/pkp/ops/pull/635

**Comment by jonasraoni** [comment]
@bozana Just something to consider when using jobs https://github.com/pkp/pkp-lib/issues/9591

**Comment by bozana** [comment]
@jonasraoni, thanks a lot!
Can I test it running the jobs from CLI using `php lib/pkp/tools/jobs.php run`? 
I will also double check the code having in mind that new issue, although I maybe do not understand everything... :-\

**Comment by jonasraoni** [comment]
You should be using the `supervisor`, which will keep a PHP process running and listening for new jobs.

Then all classes will be kept loaded in memory, and that's when magics can happen due to the static variables stored in classes and inside functions 😁

**Comment by bozana** [comment]
OK, I will try to test it with supervisor... :-\ :sweat_smile:

**Comment by jonasraoni** [comment]
It should be enough to run the `jobs.php work` and keep it opened in another console window.

**Comment by bozana** [comment]
@jonasraoni, I could not install supervisor yesterday -- I got message that there is no such package for my ubuntu version, although I double checked it shouldbe... So I need to figure out the next steps for it... 
However, could you please review the PRs above?

**Comment by jonasraoni** [comment]
Ah, you don't need the supervisor, it's enough to run:
`php lib/pkp/tools/jobs.php work`

It will stay running forever and waiting for new jobs. Take a look at the last thread on the development channel, I just left an example of the problem that we can have 😁

**Comment by bozana** [comment]
As far as I can see, I think these usage stats jobs should not have such a major problems -- we use some static variables/functions but those seems to me to be fine, and there is no explicit caching... :thinking:

**Comment by jonasraoni** [comment]
I saw your code is using some settings from the `Application::get()->getRequest()->getSite()`, the request stays cached in a static variable of the `PKP\core\Registry`.

If one of these site settings will be changed, your code will keep using the old value.
