### ISSUE TITLE
Indexation for search purposes might fail silently

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9665]
**Describe the bug**
This is a follow-up for an old discussion at the forum (see: https://forum.pkp.sfu.ca/t/ojs-3-1-2-4-problem-with-rebuildsearchindex/57666)

The latest updates at the codebase (see: new RegExp at https://github.com/pkp/pkp-lib/issues/8915 and dechunking at https://github.com/pkp/pkp-lib/issues/8502) are not enough to address the issue. A bunch of bad UTF-8 characters is enough to break the `preg_replace()`.

**To Reproduce**
1. Use a bad text input, such as the [sample.txt](https://github.com/pkp/pkp-lib/files/14085392/sample.txt), which was extracted using the following config setting `index[application/pdf] = "/usr/bin/pdftotext -enc UTF-8 -nopgbrk %s - | /usr/bin/tr '[:cntrl:]' ' '"`.
2. Try to `preg_replace()` it using the UTF-8 modifier.
3. See that the output is an empty string.

**What application are you using?**
OJS 3.3

**Comment by fgnievinski** [comment]
My installation of OJS 3.4.0.8 still doesn't search in the full text of PDF files -- should the index be rebuilt manually or is this fix automatic when upgrading from version 3.3?

**Comment by jonasraoni** [comment]
Hi! This issue should affect just content with bad UTF-8 characters. So, most of the content should be fine.
Do you have the .pdf/.doc/etc parsers enabled on the `config.inc.php`? If yes, you may try to check what they are outputting, that's the content OJS is going to ingest.
