### ISSUE TITLE
Replace task scheduler by Laravel scheduler

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9678]
**Describe the feature**
The task scheduler syntax isn't very friendly and has caused issues in the past.

For a next big release, it's better to discard the code and move to the [Laravel scheduler](https://laravel.com/docs/10.x/scheduling), which supports better configurations and the usage of a CRON syntax.

**Extra reasons**
If a plugin wants to run scheduled tasks, it needs to provide a `scheduledTasks.xml` file, and also attach itself to the `Acron` plugin. After installing such plugin, the administrator of a journal, which is using CRON instead of the Acron plugin, will also need to add a new entry at `CRON` to execute the plugin's `scheduledTasks.xml`.
- This is a bit counter-intuitive, the Acron shouldn't be any simpler than using CRON after both are setup.
- The "registration" should be unified, the executor just needs to have access to the list of tasks and their execution periods.

This is a follow-up of https://github.com/pkp/pkp-lib/issues/8921
Also considering https://github.com/pkp/pkp-lib/issues/7940 

**Plugins to update**
- [x] [pkp/ojs](https://github.com/pkp/ojs) · [classes/plugins/PubObjectsExportPlugin.php](https://github.com/pkp/ojs/blob/d3214bd8fd88cbb72a6b2156f0531cfbf34e4d1f/classes/plugins/PubObjectsExportPlugin.php#L94)
- [ ] [pkp/usageStats](https://github.com/pkp/usageStats) · [UsageStatsPlugin.inc.php](https://github.com/pkp/usageStats/blob/51b955e2089d5ec64eba6ba945d967f926cd1aab/UsageStatsPlugin.inc.php#L127) [NOT REQUIRED AS FUNCTIONALITY MOVED TO CORE IN 3.4.0]
- [x] [pkp/pln](https://github.com/pkp/pln) · [PlnPlugin.php](https://github.com/pkp/pln/blob/226737802d31cff7870ee6b803cdd41288c588e1/PlnPlugin.php#L107)
- [x] [pkp/crossrefReferenceLinking](https://github.com/pkp/crossrefReferenceLinking) · [CrossrefReferenceLinkingPlugin.php](https://github.com/pkp/crossrefReferenceLinking/blob/6dc8724ab5bd415dc61a4c44d5e0e414934a7b2b/CrossrefReferenceLinkingPlugin.php#L69)
- [x] [pkp/ops](https://github.com/pkp/ops) · [classes/plugins/PubObjectsExportPlugin.php](https://github.com/pkp/ops/blob/8783170f656f2c0d274c5eca855dd9b972f849d5/classes/plugins/PubObjectsExportPlugin.php#L93)
- [x] [medra](https://github.com/pkp/medra/tree/28a5fc1f63469005306715323a19b5a373bc8ad7) . [MedraDoiDataMigration.php](https://github.com/pkp/medra/blob/28a5fc1f63469005306715323a19b5a373bc8ad7/MedraDoiDataMigration.php#L312)

**PRs**
- [pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10107
- [ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4332
- [omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1657
- [ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/738
- [acron](https://github.com/pkp/acron) --> https://github.com/pkp/acron/pull/10 [Making acron non-functional]
- [pln](https://github.com/pkp/pln) --> https://github.com/pkp/pln/pull/92
- [crossrefReferenceLinking](https://github.com/pkp/crossrefReferenceLinking) --> https://github.com/pkp/crossrefReferenceLinking/pull/26
- [medra](https://github.com/pkp/medra) --> https://github.com/pkp/medra/pull/29

**Implementation Details**
Changes are as following :-
1. the XML based task scheduler is removed and moved to use the laravel like task scheduling approach, see at https://laravel.com/docs/11.x/scheduling . To register a schedule task that shared by all app , register it in `PKP\scheduledTask\PKPScheduler` and only app specific ones in `APP\scheduler\Scheduler`. 
2. The old schedule tool `tools/runScheduledTasks.php` has been removed and we now have few different command to run schedules as :-
```bash
php lib/pkp/tools/scheduler.php run # Run any pending schedule task 
php lib/pkp/tools/scheduler.php list # List all schedule tasks registered
php lib/pkp/tools/scheduler.php work # Run the schedule tasks as daemon, useful for local dev rather than to set up a crontab
php lib/pkp/tools/scheduler.php test # Allow the run specific schedule task from the list, useful for devs to test during development
```
Better to run `php lib/pkp/tools/scheduler.php usage` to see all available options.
3. The `Acron plugin` has been removed and the functionality to run schedule task on web based request has been moved to core . To enable the web based schedule task running , need to add the following in `config.inc.php` file :-
```
;;;;;;;;;;;;;;;;;;;;;;;;;;
; Schedule Task Settings ;
;;;;;;;;;;;;;;;;;;;;;;;;;;

[schedule]

; Whether or not to turn on the built-in schedule task runner
;
; When enabled, schedule tasks will be processed at the end of each web
; request to the application.
;
; Use of the built-in schedule task runner is highly discouraged for high-volume 
; sites. Use your operational system's task scheduler instead, and configure 
; it to run the task scheduler every minute.
; Sample for the *nix crontab
; * * * * * php lib/pkp/tools/scheduler.php run >> /dev/null 2>&1
;
; See: <link-to-documentation>
task_runner = On

; How often should the built-in schedule task runner run scheduled tasks at the
; end of web request life cycle (value defined in seconds).
; 
; This configuration will only have effect for the build-it task runner, it doesn't apply
; to the system crontab configuration. 
;
; The default value is set to 60 seconds, a value smaller than that might affect the
; application performance negatively.
task_runner_interval = 60

; When enabled, an email with the scheduled task result will be sent only when an error
; has occurred. Otherwise, all tasks will generate a notification.
scheduled_tasks_report_error_only = On
```

4. the previously existed config option `scheduled_tasks_report_error_only` has been moved from `general` section to newly added section `schedule` in `config.inc.php`
5. config option `scheduled_task` from section `general` has been removed in favour of https://github.com/pkp/pkp-lib/issues/7940 . 
6. Plugins now also can not register schedule tasks as `XML` but to use the laravel based scheduler convention . To plugins have own scheduler, it need to implement the `PKP\plugins\interfaces\HasTaskScheduler` and register the task, for example : 
```php
/**
     * @copydoc \PKP\plugins\interfaces\HasTaskScheduler::registerSchedules()
     */
    public function registerSchedules(PKPScheduler $scheduler): void
    {
        $scheduler
            ->addSchedule(new DOAJInfoSender())
            ->everyMinute()
            ->name(DOAJInfoSender::class)
            ->withoutOverlapping();
    }
```

**Comment by jonasraoni** [comment]
Ah, while you're working on it, check if you need to address this comment: https://github.com/pkp/pkp-lib/issues/9979#issuecomment-2189076176

**Comment by touhidurabir** [comment]
@asmecher it's ready for review. Please see the PRs at https://github.com/pkp/pkp-lib/issues/9678#issue-2110219392 .

**Comment by asmecher** [comment]
@jonasraoni, could you have a look at this one?

**Comment by touhidurabir** [comment]
@jonasraoni can you take another look at the PRs ? I have addressed most of your suggestions and if all ok, I will port the changes to OMP and OPS main . Also I have listed few plugins that need modification for this and if I have missed any, please add those to list . All details at https://github.com/pkp/pkp-lib/issues/9678#issue-2110219392

**Comment by touhidurabir** [comment]
@jonasraoni can you check the plugin PRs at https://github.com/pkp/pkp-lib/issues/9678#issue-2110219392 specially for the [pln](https://github.com/pkp/pln) . If all ok, I plan to update the submodules for `OJS`  and `OMP` (already removed the `Acron` submodule for `OPS` and it's working) and should be good to merge .

**Comment by asmecher** [comment]
Thanks, @jonasraoni and @touhidurabir, I've commented on both.

**Comment by touhidurabir** [comment]
@jonasraoni I have merged the `OJS`, `OMP` and `OPS` PRs but do not have the write access to plugins , details at https://github.com/pkp/pkp-lib/issues/9678#issue-2110219392 . Can you please merge the plugins PRs ?

**Comment by jonasraoni** [comment]
Me neither, summoning @asmecher / @bozana to merge the remaining PRs.

ps: As we've got write access to the pkp-lib/apps, I think we should have write-access to the other repos, as they are less risky from a security perspective.

**Comment by asmecher** [comment]
I've merged the 3 remaining PRs, thanks! Is this ready to be closed?

**Comment by touhidurabir** [comment]
> I've merged the 3 remaining PRs, thanks! Is this ready to be closed?

@asmecher it now good to be closed . But there was no need to merge the PR https://github.com/pkp/acron/pull/10 for `acron` as thats obsolete anyway for `main` . That was just basically comment out the Hooks in register so that those does not run. However it's only for main branch so i don't see any problem.
