### ISSUE TITLE
The arguments for the jobs.php are not working

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9686]
**Describe the bug**
When calling `php lib/pkp/tools/jobs.php`, all arguments that have values are ignored and their default values are used instead.

**To Reproduce**
1.  Run `php lib/pkp/tools/jobs.php work --max-jobs=1`
2. See that the value was ignored

**What application are you using?**
OJS 3.4

**Comment by jonasraoni** [comment]
@touhidurabir I think there's nothing special here, but if you'd like to take a look, see the linked PRs.

**Comment by touhidurabir** [comment]
@jonasraoni I added one comment for both PR, please check that . Just you need to make the same change at 2 more places and it should be good to merge .

**Comment by jonasraoni** [comment]
Thanks!
