### ISSUE TITLE
The primary navigation menu doesn't display on the site level

### ISSUE THREAD

**Issue by TheBigGoldenEagle** [pkp/pkp-lib#9695]
**Describe the bug**
On a  multi-journal site, the primary navigation menu displays without issue when a journal is selected but it does not display on site level

**To Reproduce**
1. Make sure you have more than one hosted journal. Go to Administration/Site Setting/Navigation
2. Click on  "Add Menu" give it a title and assign it to the "primary" navigation area
3. Drag any "Unassigned Menu Items" you wish and drop it below the "Assigned Menu Items"
4. Hit "Save" clear cache and go to the main url of your website

**What application are you using?**
 OJS 3.4.0.4

**Additional information**
I have tried almost all available themes but no matter what I do, the primary navigation menu will not display

**Comment by defstat** [comment]
Hi @TheBigGoldenEagle! Thanks for reporting that. Unfortunately I can't reproduce the problem that you are referring to on OJS 3.4.0.4

I have added a new `Primary` Navigation Menu on the Site level, and I can see it on the site level without having to do anything more. Is it possible that you are trying to access your new Site Navigation Menu from within a specific context? What is the URL that you try to access?

![image](https://github.com/pkp/pkp-lib/assets/560456/6e05e3ec-962f-4460-9266-a8d3f6794c32)

**Comment by TheBigGoldenEagle** [comment]
Thank you for your response and trying it out. I fought for it for a week and then gave up and added a static menu to the header.tpl. That's the best approach for me as I want a consistent navigation menu across all the hosted journals. I'm closing this issue, Thank you

**Comment by defstat** [comment]
@TheBigGoldenEagle thanks. The best approach would be to make your installation work though. Did you create a new theme for that, or you overrided the core/header template?

If so you may have issues on upgrading your installation, or unexpected behavior on the ui part. 

If I understand correctly you want all your journals to have the same primary menu. The site navigation menu toolset manages the 'site' level and is not designed to make the a navigation menu be displayed across the installation's journals. 

We could work on making a data workaround for your case, though, and still use the build-in capabilities of navigation menus, without having any problems regarding upgrading your installation.

**Comment by TheBigGoldenEagle** [comment]
Thank you again for getting back to me. yes, I had altered the bootstrap theme and now to demonstrate the issue I have switched to the default theme that I have not modified its source code (except for adding a custom.less for styling). The URL
![PageSource](https://github.com/pkp/pkp-lib/assets/64661875/66f36d2c-7885-431b-88f9-d3b2367a02f7)
 is https://www.gsijournals.com/ and I have attached two screenshots of the primary menu setting that I expect to see on the site level.
![Settings_1](https://github.com/pkp/pkp-lib/assets/64661875/5181f6d6-b22c-488d-ad7d-bb7c5acdd766)
![Settings](https://github.com/pkp/pkp-lib/assets/64661875/798da5c2-366d-4be9-b27f-6f4bb625e1ea)

**Comment by defstat** [comment]
@TheBigGoldenEagle I think I know what the problem is here - you are trying to display some context related Menu Items at the Site level, something that will not work like that. 

If you check the code [here](https://github.com/pkp/ojs/blob/main/classes/services/NavigationMenuService.php#L101) you can see that each `navigatiuonMenuItem` has a `_isDisplayed` property that can be calculated. For specific types like `NMI_TYPE_CURRENT` and `NMI_TYPE_ARCHIVES`, this property will be set to `false` if not in the context of a specific Journal. 

That is the reason why you don't see something there.

**Comment by TheBigGoldenEagle** [comment]
It worked thank you very much!
