### ISSUE TITLE
Add masthead column to user_user_groups table 

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9709]
Implement the possibility for an user to opt-out of being displayed on the masthead.
When inviting a user to a masthead role, JM will have the possibility to choose if the user will appear on the masthead (default) or not.
This (agreed) information needs to be saved in the DB. 

PRs:
- https://github.com/pkp/pkp-lib/pull/9727
- https://github.com/pkp/ojs/pull/4185
- https://github.com/pkp/omp/pull/1527
- https://github.com/pkp/ops/pull/642

**Comment by bozana** [comment]
Hi @asmecher, could you please review the PRs above?
Currently the masthead for user_user_groups is not visible anywhere in the UI, but I would next start with masthead public page, and once I have finished that I will see what is needed to consider it all in the user grid and user form (there is fully new design of it, so either to implement that new design or to see how those masthead changes could be considered in our old design i.e. grid and form).
Thanks a lot!

**Comment by asmecher** [comment]
Sorry for the wait with these, @bozana! Looks good; please go ahead.
