### ISSUE TITLE
Locales not loading for Statistics Tab for the role "section editor"

### ISSUE THREAD

**Issue by basti95** [pkp/pkp-lib#9721]
**Describe the bug**
When accessing the Statistics Tabs in OJS Backend, the user sees "##stats.editorialActivity##" and "##manager.users##" Instead the localized texts. This bug is language independend

**To Reproduce**
1. Login in as a Section Editor
 ![OJS_Bug_2024-02-09](https://github.com/pkp/pkp-lib/assets/12784444/1ad7e3ee-be97-4635-9a96-05e495c57b7c)
2. Click any Link in the Statistics Section of the left navigation bar ("Articles", "Editorial Activity" or "Users")
3. See error 
![OJS_Bug_2024-02-09_2](https://github.com/pkp/pkp-lib/assets/12784444/7b5ff36d-5a32-4700-96ce-63950b436c73)

**What application are you using?**
 OJS 3.3.0.15

**Comment by asmecher** [comment]
@basti95, I can't replicate this on my local machine, but can you try the following patch to see if it resolves the issue?
```diff
diff --git a/classes/template/PKPTemplateManager.inc.php b/classes/template/PKPTemplateManager.inc.php
index af859ebafd..fb9b84925e 100644
--- a/classes/template/PKPTemplateManager.inc.php
+++ b/classes/template/PKPTemplateManager.inc.php
@@ -1012,6 +1012,7 @@ class PKPTemplateManager extends Smarty {
                                        }
 
                                        if (count(array_intersect([ROLE_ID_MANAGER, ROLE_ID_SUB_EDITOR], $userRoles))) {
+                                               AppLocale::requireComponents([LOCALE_COMPONENT_PKP_MANAGER]); // pkp/pkp-lib#9721
                                                $menu['statistics'] = [
                                                        'name' => __('navigation.tools.statistics'),
                                                        'submenu' => [
```

**Comment by basti95** [comment]
That works! Thank you Alec! We have encountered this bug in multiple instances, not sure why this is specific to our systems.

**Comment by asmecher** [comment]
Thanks for confirming! This'll go out in the next 3.3.0-x build.
