### ISSUE TITLE
OMP - Empty category missing locale key

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#9722]
**Describe the bug**
When a category in OMP is empty (has 0 titles associated to it) it shows a missing locale key error instead a translated message.

**To Reproduce**
1. Go to  [OMP 3.3 Demo](https://demo.publicknowledgeproject.org/omp3/testdrive/index.php/td-press/catalog/category/business)
2. Click on 'Business & Economics ' (or any empty category)
3. See error

**What application are you using?**
OMP 3.2 / 3.3 / 3.4

**Additional information**
![image](https://github.com/pkp/pkp-lib/assets/4992902/2654851f-47f5-4dfb-a324-313b341e96fb)

OJS 1.2 still has the original locale key message: 
https://github.com/pkp/omp/blob/omp-stable-1_2_0/locale/en_US/locale.xml#L289C16-L289C39

**Comment by kaitlinnewson** [comment]
Fixed in https://github.com/pkp/omp/pull/986, back-porting PR for review @asmecher:

- OMP 3_3_0: https://github.com/pkp/omp/pull/1654

**Comment by asmecher** [comment]
Merged, thanks!
