### ISSUE TITLE
OJS and images attached to XML

### ISSUE THREAD

**Issue by sergej-papper-itpc-vu-lt** [pkp/pkp-lib#9725]
Have an issue with clean OJS (3.4.0.4) setup (without any additional plugins).  Want to upload a xml file and an image attached to them via Submissions -> Publication -> Galleys
![1](https://github.com/pkp/pkp-lib/assets/148333478/02994a88-0186-405f-8d04-5cd279c92ed2)
 
And there is a row in xml file:
<graphic xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="photo.jpg"/>

However images are not showing in a browser (Microsoft Edge).
![2](https://github.com/pkp/pkp-lib/assets/148333478/a2a48a6a-6e15-4254-a994-d1c32bc142f3)

And finally, when I check the file in Windows Explorer, I found that image name is encoded.
![3](https://github.com/pkp/pkp-lib/assets/148333478/3a88051f-c02a-4381-a5e6-142d1e913e7d)

I think this is the main reason why pictures in a browser are invalid.

Can you help me with that? 

Thanks.

**Comment by asmecher** [comment]
@sergej-papper-itpc-vu-lt, this is more of a support question than a bug report; can you post it on our forum at https://forum.pkp.sfu.ca? That's the best place to start.
