### ISSUE TITLE
The participant assignment form fails to display the correct number of items.

### ISSUE THREAD

**Issue by salmanm2003** [pkp/pkp-lib#9728]
@asmecher When assigning a participant to a submission and selecting the user group, the count displayed below the user list doesn't accurately reflect the number of users. This discrepancy occurs because the query responsible for generating the list fails to eliminate duplicate records.

**Steps to Reproduce:**

-    Choose an existing submission.
-    Navigate to workflow > Submission.
-    Go to Participants on the right side and click the Assign button.
-    Select a user group from the list, then click the Search button.
-    A list of users will appear, with the items count shown incorrectly (e.g., 48 out of 100 items).

**Environment:**

    OJS version 3.3.0.14

**Solution:**

To address this issue, the relevant query in UserStageAssignmentDAO.inc.php
[https://github.com/pkp/pkp-lib/blob/01391492608c84ad9a414fbaaf9f55a2bb834416/classes/user/UserStageAssignmentDAO.inc.php#L109](https://github.com/pkp/pkp-lib/blob/01391492608c84ad9a414fbaaf9f55a2bb834416/classes/user/UserStageAssignmentDAO.inc.php#L109)
 needs modification. Below is the revised query:

`$result = $this->retrieveRange(
    $sql = 'SELECT DISTINCT u.*, COALESCE(usfs_l.setting_value, usfs_pl.setting_value) AS ordered_setting_value
    FROM    users u
        LEFT JOIN user_user_groups uug ON (u.user_id = uug.user_id)
        LEFT JOIN stage_assignments s ON (s.user_id = uug.user_id AND s.user_group_id = uug.user_group_id AND s.submission_id = ?)
        JOIN user_group_stage ugs ON (uug.user_group_id = ugs.user_group_id AND ugs.stage_id = ?)
        LEFT JOIN user_settings usgs_pl ON (usgs_pl.user_id = u.user_id AND usgs_pl.setting_name = ? AND usgs_pl.locale = ?)
        LEFT JOIN user_settings usfs_pl ON (usfs_pl.user_id = u.user_id AND usfs_pl.setting_name = ? AND usfs_pl.locale = ?)
        LEFT JOIN user_settings usgs_l ON (usgs_l.user_id = u.user_id AND usgs_l.setting_name = ? AND usgs_l.locale = ?)
        LEFT JOIN user_settings usfs_l ON (usfs_l.user_id = u.user_id AND usfs_l.setting_name = ? AND usfs_l.locale = ?)
    WHERE   uug.user_group_id = ? AND
        s.user_group_id IS NULL'
        . ($name !== null ? ' AND (usgs_pl.setting_value LIKE ? OR usgs_l.setting_value LIKE ? OR usfs_pl.setting_value LIKE ? OR usfs_l.setting_value LIKE ? OR u.username LIKE ? OR u.email LIKE ?)' : '')
    . ' ORDER BY ordered_setting_value',
        $params,
        $rangeInfo);`

This adjustment ensures that duplicate records are not retrieved, thus resolving the issue of incorrect item counts in the list.

![Screenshot from 2024-02-13 18-38-04](https://github.com/pkp/pkp-lib/assets/11320786/1c02604a-9ca4-44a5-a8fb-613a4a7f82bf)

**Comment by asmecher** [comment]
@salmanm2003, could you open a pull request against the `stable-3_3_0` branch that includes the revised query? That'll be a lot easier to read and review. Thanks for raising this!

**Comment by salmanm2003** [comment]
@asmecher here is the PR https://github.com/pkp/pkp-lib/pull/9730

**Comment by asmecher** [comment]
@salmanm2003, thanks, but I'm having a hard time spotting where the duplicates are coming into it:
 - The `user_user_groups` join is limited by the specified `user_group_id`, and joined on `user_id`; which together make a unique identifier -- so it shouldn't generate more rows;
 - The `stage_assignments` join is used to exclude rows (`s.user_group_id IS NULL`);
 - The `user_group_stage` join is limited by the specified `stage_id` and `user_group_id`;
 - You don't appear to have search text, so the localized data joins shouldn't play into it

Can you take a look at a specific example and see what the duplicate rows look like? It's possible I missed something, or it's possible that your database is a little divergent from stock. Either way, I'm hoping there's a resolution that doesn't involve adding a `SELECT DISTINCT`; these can sweep a lot of issues under the rug until the data size starts causing problems.

**Comment by salmanm2003** [comment]
@asmecher You're correct. It was actually a database issue, not a problem with the code. Thanks for investigating.

**Comment by asmecher** [comment]
@salmanm2003, thanks for following up!
