### ISSUE TITLE
User gains access to article even though payment does not complete. Transactions that are in the queued_payments table are not charged/processed properly at paypal

### ISSUE THREAD

**Issue by radjr2** [pkp/pkp-lib#9735]
**Describe the bug**  Same as https://forum.pkp.sfu.ca/t/queued-payments/86350
The issue is that a user purchases an article or other item and the transaction does NOT complete but the user is given access to the item.

Briefly, we have determined that there are many transactions that are in the queued_payments table that have NOT been charged/processed properly at paypal. In our case the majority are reprint purchases but there may be some subscription purchases.

The paypal module from OJS and/or the base code for OJS seems to have a bug that causes the transaction to fail. Or it is possible that paypal is dropping the charge somehow. OJS grants access to the content but payment was never received. We found out when a customer asked for a receipt but we could not find the charge on paypal.

What makes this sketchy is that it does not fail all the time. If we run tests, it works. But there is something in there that causes the charge to fail about 60% of the time!

**To Reproduce**
1: Set up and configure paypal payments with ClientID and Secret key
2: Process order for articles - log in, no subscription, no ip access, purchase article
3: In every case where the paypal transaction never completes, access is granted to the article. The user ID shows up in the user table. NO payment is recorded. No payment is recorded at paypal end.
4: look in queued_payments and details of payment are in that table. There is NO status of the transaction or resulting error.
5: If you log in with the user's id, you WILL have access to the article.

**What application are you using?**
 OJS, 3.3.0.13

**Additional information**
Have tracked down the following successful and failed transaction requests from paypal. Seems that OJS gives up or sends a partial request.
Successful Transaction:

Request Path:
POST /v1/payments/payment/PAYID-MXF32ZQ56X69216U37604225/execute

Failed Transactions:

POST /v1/payments/payment

**Comment by asmecher** [comment]
Closing in favour of the [forum thread](https://forum.pkp.sfu.ca/t/queued-payments/86350/3) to avoid duplicated effort. We'll re-open this if the conversation makes it as far as code changes.
