### ISSUE TITLE
Allow ordering of masthead roles

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9736]
There should be a possibility for JM to order the roles selected to appear on masthead. This should be available under Website > Appearance > Masthead, and it should look similar to Website > Appearance > Setup > Sidebar, but if possible without the checkbox.

PRs:
- https://github.com/pkp/ui-library/pull/331
- https://github.com/pkp/pkp-lib/pull/9738
- https://github.com/pkp/ojs/pull/4191
- https://github.com/pkp/omp/pull/1537
- https://github.com/pkp/ops/pull/650

**Comment by bozana** [comment]
Hi @asmecher, could you take a look at the PRs above? @jardakotesovec will review the ui-library part, but if you could take a look how the order of the masthead roles is saved (as a context setting) and if it is OK so.

**Comment by asmecher** [comment]
Sorry for the wait! I just added a small comment; it's ready to go otherwise.
