### ISSUE TITLE
php81_bc/strftime patch does not apply in 3.3 build

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#9739]
**Describe the bug**
The application of the php81_bc/strfttime patch in composer fails:
https://github.com/pkp/pkp-lib/blob/01391492608c84ad9a414fbaaf9f55a2bb834416/composer.json#L84-L86
```
  - Applying patches for php81_bc/strftime
    lib/strftime-locale-patch.diff (Apply strftime locale patch)
   Could not apply patch! Skipping. The error was: Cannot apply patch lib/strftime-locale-patch.diff
```

The patchfile format has a unified diff header and no path specification in the diff.
https://github.com/pkp/pkp-lib/blob/01391492608c84ad9a414fbaaf9f55a2bb834416/lib/strftime-locale-patch.diff#L1-L3

**To Reproduce**
1. `git clone https://github.com/pkp/ojs.git .`
2. `git checkout stable-3_3_0`
3. `git submodule update --init --recursive`
4. `composer --working-dir=lib/pkp install`

**What application are you using?**
 OJS 3.3.0

**Additional information**
n/a

**Comment by asmecher** [comment]
Thanks, @ctgraham; separately fixed by @jonasraoni here: https://github.com/pkp/pkp-lib/commit/eea01cc462bfbe5a126311d5a5c888682e326df0
