### ISSUE TITLE
Add missing functionality to gracefully restart queue worker

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#9742]
**Describe the bug**
With the release of `3.4.0`, we have queue jobs that can be executed in several approach such as 
1. Job Runner
2. Cron/Acron
3. Queue Worker

Among the above options, most effective approach would be `Queue Worker` but there is no functionality to gracefully restart the worker once new changes are pushed. As `worker` load the application in memory , restart is required to reflect the new changes . One option is to quit the currently running worker or `supervisor` (if that is installed to monitor worker process) but that can have major side effect . For example, if a long running job being executed via the worker and worker/supervisor restarted in the middle of it, the job will not get to complete and that may have a major side effect . Need a functionality that can gracefully restart the worker . 

**To Reproduce**
1. boot up the worker via `php lib/pkp/tools/jobs.php work` or through `supervisor`
5. deploy the long running job
6. restart the worker/supervisor the middle of that long running job
7. see that desired output/outcome may not achieved. 

**What application are you using?**
 OJS, OMP or OPS version 3.4.0+ and main . 

**Additional Information**
This may not required right now if another proposed solution at https://github.com/pkp/pkp-lib/issues/9591#issuecomment-1924655959 merged which restart worker after completing a single job . 

**PRs**

#### stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9743
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4194 [TEST ONLY]

#### main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9745
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4196 [TEST ONLY]

#### PKP Doc
[pkp-docs](https://github.com/pkp/pkp-docs) --> https://github.com/pkp/pkp-docs/pull/1177

**Comment by touhidurabir** [comment]
@asmecher Please review the PR at https://github.com/pkp/pkp-lib/issues/9742#issue-2141546504 . If we agree to have this merge, I will forward port it to `main` . Also in that case we need to update our doc so I will make a PR for that also .

**Comment by touhidurabir** [comment]
@asmecher please review the PRs at https://github.com/pkp/pkp-lib/issues/9742#issue-2141546504

**Comment by asmecher** [comment]
Thanks, @touhidurabir, all merged!

**Comment by jonasraoni** [comment]
I've created a PR to add extra details to the documentation: https://github.com/pkp/pkp-docs/pull/1182
