### ISSUE TITLE
Crossref Export plugin Error on ojs 3.4.0.4

### ISSUE THREAD

**Issue by edwardsafari** [pkp/pkp-lib#9746]
An XML validation error occurred and the XML could not be exported.

I get the above error when i try to export article dois but works with issue dois.

But for automatic deposits to crossref i get the error "Deposit contains title error(s): Title name value is missing from the title element" 

Am using OJS 3.4.0.4

kindly assist

**Comment by asmecher** [comment]
@edwardsafari, could you post your question (with as much detail as possible) on the support forum (https://forum.pkp.sfu.ca)? That's the best place to get help.
