### ISSUE TITLE
Authors list on reviewers page

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9756]
PRs (`stable-3_4_0`):
- ojs: https://github.com/pkp/ojs/pull/4061
- ui-library: https://github.com/pkp/ui-library/pull/287
- pkp-lib: https://github.com/pkp/pkp-lib/pull/9288

Just the locale keys (`stable-3_4_0`):
- https://github.com/pkp/pkp-lib/pull/9495

**Comment by MrRob100** [comment]
Feature: A feature to display authors on the 'Add Reviewer' modal. A box listing the submission's authors shows 4 rows and is scrollable with the option of expanding the box to show all rows. Potential reviewers that are from the same institution as any of the submission authors, a badge is added to highlight this. The institution matching is done based on text only

**Comment by asmecher** [comment]
@MrRob100, just checking up on our translation coverage for https://github.com/pkp/pkp-lib/pull/9495, we consider the "core" translations to be...

- Spanish
- Portuguese (pt_PT and pt_BR)
- German
- Danish
- Finnish

(This list is somewhat informal and will be a touch different every time I give it. But anyway.)

So far we have coverage for all of these *except* German. I'll check to see if we can get an eye over that work in the short term.

**Comment by asmecher** [comment]
Hi all! At long last we have good coverage with the core languages in `stable-3_4_0`, so I've merged the PRs here. I think all the work on `main` has long since been merged -- so closing this issue. Thanks for your patience!
