### ISSUE TITLE
Additional file validation causes error

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9759]
**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

**To Reproduce**
1. Enable a plugin that triggers the `submissionfilesuploadform::validate` hook and uses `submissionfilesuploadform->addError()`, like https://github.com/ajnyga/allowedUploads
2. Enter the valid file extensions to the plugin settings
3. Go to a submission workflow and try to upload a file that is not permitted in the plugin settings

**What application are you using?**
 OJS 3.4 stable

**Additional information**
![Näyttökuva 2024-2-22 kello 14 46 25](https://github.com/pkp/pkp-lib/assets/16347527/12cf9d3a-3eea-4efb-b105-629e411f7941)

**Comment by jardakotesovec** [comment]
From looking to usual uses of JSONMessage. Second parameter should be error message to be displayed via alert dialog. But given that form validation errors seems to be communicated from fetchNotification, its probably correct just return JSONMessage(false).

pkp-lib PR https://github.com/pkp/pkp-lib/pull/9760

**Comment by jardakotesovec** [comment]
3.4.0
pkp-lib: https://github.com/pkp/pkp-lib/pull/9760
ojs (tests only): https://github.com/pkp/ojs/pull/4201

**Comment by jardakotesovec** [comment]
@jonasraoni Can I ask you for review?

**Comment by jonasraoni** [comment]
Merged and cherry picked in main.
