### ISSUE TITLE
Offline App: Creating the PHP Fatal error

### ISSUE THREAD

**Issue by henriquejsfj** [pkp/pkp-lib#9767]
See: https://github.com/pkp/pkp-lib/issues/7022

Seems that in version 3.4 this error persists. I tried the configuration said by @asmecher without success.

With setting `enable_beacon` and `show_upgrade_warning` to On in `config.inc.php` I got the following error:
```
PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ConnectException: cURL error 7: Failed to connect to pkp.sfu.ca port 443 after 1 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://pkp.sfu.ca/ojs/xml/ojs-version.xml?id=&oai=http%3A%2F%2Flocalhost%3A8081%2Findex%2Foai in /var/www/html/lib/pkp/lib/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210\nStack trace:   [...] 
```
After setting `enable_beacon` and `show_upgrade_warning` to Off in `config.inc.php` I got the following error:
```
PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ConnectException: cURL error 7: Failed to connect to pkp.sfu.ca port 443 after 2 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://pkp.sfu.ca/ojs/xml/ojs-version.xml in /var/www/html/lib/pkp/lib/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210\nStack trace: [...]
```

Note that after changing the configuration the requested URL does not have the OAI stuff anymore. 

I investigated it deeper and saw that in the [AdminHandler](https://github.com/pkp/pkp-lib/blob/8ce4daced2a4ab5e08eb95779df5e92d91951f00/pages/admin/AdminHandler.php#L122C9-L123C66) the function `VersionCheck::checkIfNewVersionExists()` is being called and VersionCheck only uses `enable_beacon` to add the OAI stuff in the URL.

A hotfix would move this function call to be inside the if with `show_upgrade_warning` right below.

Going even deeper, I investigate the stable 3.3 branch and that error would persist the same way after configuring...

**Comment by jonasraoni** [comment]
Cherry-piked into `stable-3_3_0` and `main`.
