### ISSUE TITLE
Submission title/subtitle html text quirk

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#9773]
**Describe the bug**
In pkp/pkp-lib#2564, submission title and subtitle got new enhancement which allow limited number of html tags/elements into this field which is possible to apply via editor toolbar or as text like `Some <b>Bold</b> text` . However this leads to allow adding any kind of html and sometime those don't get parsed well .  This does not pose any `Cross-site scripting (XSS)` issue as that being handled well but causing broken title or subtitle . 

**To Reproduce**
1. Start a new submission or edit a submission that has reached to production stage
2. Add/Edit the title/subtitle field with invalid html e.g. `Some <b>Bold</b> text <img src="error" onerror=alert(1)>`
3. See that title and subtitle bit broken due to invalid html tags/elements

**What application are you using?**
 OJS, OMP or OPS version `3.4.0` and `main`

**PRs**
#### Stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9774
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/335
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4205 [TEST ONLY]

#### Main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10025
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/361
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4303 [TEST ONLY]

**Comment by touhidurabir** [comment]
@asmecher can you take a look at the PRs at https://github.com/pkp/pkp-lib/issues/9773#issue-2171415633 .

**Comment by touhidurabir** [comment]
@asmecher if test pass , please review the PRs at https://github.com/pkp/pkp-lib/issues/9773#issue-2171415633 , need forward porting to main .

**Comment by asmecher** [comment]
Reviewed, thanks, @touhidurabir; see https://github.com/pkp/ui-library/pull/335

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I've merged the 4 PRs (and will update the application submodules manually). Is this ready to be closed?

**Comment by touhidurabir** [comment]
@asmecher yeah,  it's all done . I am closing this now .
