### ISSUE TITLE
[OMP] ONIX extract reports different authorship metadata depending on the user's language

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9784]
**Describe the bug**
The ONIX extract from OMP detects author roles in a way that's dependent on the exporting user's language selection.

It uses the user group abbreviation (typically `AU` for Author, for example) to determine the mapping to ONIX's role codes (e.g. `A01` for author). However, it looks up the abbreviation based on the current locale; if that's not English, the abbreviation is not likely to be `AU`.

It would be better still to use something that's not dependent on localized data or defaults, but that may have to wait for another mechanism (e.g. CRediT) to be integrated.

**To Reproduce**
1. Set up the Masthead settings in order to get ONIX exports working
2. Set up the press with at least two UI languages
3. Switch the UI to English
4. Go to Tools > ONIX 3.0 Monograph Export Plugin and export a single submission
5. Check the generated XML for the contributor role in the XML: `<ContributorRole>A01</ContributorRole>`
6. Switch the UI to another language and re-generate the XML as per step 4
7. Check the generated XML for the contributor role in the XML: `<ContributorRole>Z99</ContributorRole>`

The two extracts should not differ depending on the UI locale.

**What application are you using?**
OMP 3.3.0-x and 3.4.0-x

**Comment by asmecher** [comment]
@kaitlinnewson, rather than keep you waiting -- the change you've proposed doesn't resolve the issue, which is that we're [hard-coding tests against user-entered (localized) data](https://github.com/pkp/omp/pull/1599/files#diff-b5daa02c10a9ffcb877f445f9d43a98df5b20ae6cf5175a1f210e2b5965e08e4L323). The English-language abbreviation for the Author role might be `Au`, but the press might not even have English installed, or may have customized the values using the setup fields.

It's not a perfect solution, but you could try using the user group setting called `nameLocaleKey`, which you'll see stored in the `user_group_settings` table; for authors, for example, it'll be `default.groups.name.author`. These are installed based on `registry/userGroups.xml`, if you're wondering where they come from.

**Comment by kaitlinnewson** [comment]
Thanks @asmecher, ready for a second look now

**Comment by kaitlinnewson** [comment]
[Ready for another review](https://github.com/pkp/omp/pull/1599) @bozana. If everything looks good, I'll work on PRs to 3.4/main.

**Comment by kaitlinnewson** [comment]
@bozana the other branch PRs are listed above and ready for review

**Comment by bozana** [comment]
Hi @kaitlinnewson, this looks good to me, I am just waiting to see if that one MariaDB test will pass...

**Comment by bozana** [comment]
Thanks a lot @kaitlinnewson! 
All merged, thus closing the issue...
