### ISSUE TITLE
System Information displays SMTP password as plain text.

### ISSUE THREAD

**Issue by bdcaf** [pkp/pkp-lib#9789]
**Describe the bug**
System Information displays SMTP password as plain text - in comparison DB password is concealed. IMO this is similar sensitive and should be protected similarly.
This is not a deal breaker as the page is login protected, but does seem not too difficult to add either.

**To Reproduce**
1. Go to '/index/admin/systemInfo'
3. Scroll down to 'email section'
4. See password in plain text

**What application are you using?**
 OJS 3.4.0.5

**PRs**
#### Stable-3.3.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9805
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4217 [TEST ONLY]

#### Stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9801
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4215 [TEST ONLY]

#### Main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9804
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4216 [TEST ONLY]

**Comment by touhidurabir** [comment]
@asmecher can you review the PR at https://github.com/pkp/pkp-lib/issues/9789#issue-2178678595 . need forward porting to main and will do once test passes and confirmed.

**Comment by asmecher** [comment]
Done, thanks: https://github.com/pkp/pkp-lib/pull/9801#pullrequestreview-1944003139

**Comment by touhidurabir** [comment]
`pkp-lib` changes are merged . Need to do the submodule update later manually .
