### ISSUE TITLE
ojs 2.4.7 problem with passwords

### ISSUE THREAD

**Issue by sebastienlhaire** [pkp/pkp-lib#979]
Hi

I have tried to upgrade from ojs 2.4.5 to 2.4.7, b oth using the tar file and a git repository. The Journal I work for has some custom files that have nothing to do with user management.
I have run "php tools/update.php update" but still have problems with loging users to the database:

Here is the structure:

mysql> describe users;
+----------------------+--------------+------+-----+---------+----------------+
| Field                | Type         | Null | Key | Default | Extra          |
+----------------------+--------------+------+-----+---------+----------------+
| user_id              | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| username             | varchar(32)  | NO   | UNI | NULL    |                |
| password             | varchar(40)  | NO   |     | NULL    |                |
| salutation           | varchar(40)  | YES  |     | NULL    |                |
| first_name           | varchar(40)  | NO   |     | NULL    |                |
| middle_name          | varchar(40)  | YES  |     | NULL    |                |
| last_name            | varchar(90)  | NO   |     | NULL    |                |
| gender               | varchar(1)   | YES  |     | NULL    |                |
| initials             | varchar(5)   | YES  |     | NULL    |                |
| email                | varchar(90)  | NO   | UNI | NULL    |                |
| url                  | varchar(255) | YES  |     | NULL    |                |
| phone                | varchar(24)  | YES  |     | NULL    |                |
| fax                  | varchar(24)  | YES  |     | NULL    |                |
| mailing_address      | varchar(255) | YES  |     | NULL    |                |
| country              | varchar(90)  | YES  |     | NULL    |                |
| locales              | varchar(255) | YES  |     | NULL    |                |
| date_last_email      | datetime     | YES  |     | NULL    |                |
| date_registered      | datetime     | NO   |     | NULL    |                |
| date_validated       | datetime     | YES  |     | NULL    |                |
| date_last_login      | datetime     | NO   |     | NULL    |                |
| must_change_password | tinyint(4)   | YES  |     | NULL    |                |
| auth_id              | bigint(20)   | YES  |     | NULL    |                |
| auth_str             | varchar(255) | YES  |     | NULL    |                |
| disabled             | tinyint(4)   | NO   |     | 0       |                |
| disabled_reason      | text         | YES  |     | NULL    |                |
| suffix               | varchar(40)  | YES  |     | NULL    |                |
| billing_address      | varchar(255) | YES  |     | NULL    |                |
| inline_help          | tinyint(4)   | YES  |     | NULL    |                |
+----------------------+--------------+------+-----+---------+----------------+
28 rows in set (0.00 sec)

I have tried to run the "forgot password" procedure but it did not help

any ideas?

**Comment by ctgraham** [comment]
The password field in 2.4.7 is 255 characters in length, not 40.
https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_7/xml/schema/common.xml#L161

This would indicate a problem when you ran `php tools/update.php update`.

Please try the update again, capture any error messages, and post this to the support forum if you continue to have trouble:
http://forum.pkp.sfu.ca/

**Comment by asmecher** [comment]
(Conversation continues here: http://forum.pkp.sfu.ca/t/ojs-broken-database-users-unable-to-connect)
