### ISSUE TITLE
Primary colour can't be set from the theme menu

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9790]
**Describe the bug**
In the Appearance -> Theme menu, when trying to set new theme primary colour, changes aren't being saved.   

**To Reproduce**
1. Go to Appearance -> Theme menu
2. Set new primary colour
3. Click 'Save' button
4. Refresh the page
5. See that new colour hasn't been applied, old value is displayed instead

**What application are you using?**
 OJS main branch

**Additional information**
This causes failure of tests for all the themes

**Comment by jardakotesovec** [comment]
@Vitaliy-1 Oki, good news its just 3.5. Will try to get to that soonish (next week), so its not blocking theme tests, ok?

**Comment by Vitaliy-1** [comment]
It fails tests on Travis for the main.  I haven't created 3.4 branch yet.

**Comment by jardakotesovec** [comment]
@Vitaliy-1 Just merged the fix (https://github.com/pkp/ui-library/pull/336). Feel free to close it once you can verify that the tests are working now.

**Comment by Vitaliy-1** [comment]
I've re-run tests for Health Sciences

**Comment by jardakotesovec** [comment]
@Vitaliy-1 Seems this is resolved, reopen if its not.
