### ISSUE TITLE
[OJS] New submissions "Do not send an email" configuration not functionnal

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#9797]
**Describe the bug**
In OJS 3.4 a new config exists not to send email when a new submission is made: 

![image](https://github.com/pkp/pkp-lib/assets/19291880/9b082ef3-855d-40af-86a8-2fccfe4eb9c0)

However, when activated, OJS continues to send the emails to the authors. 

**To Reproduce**
1. Desable sending emails to authors when a new submission is made (Menu Parameters > Workflow >Emails).
2. As a user with only Author permissions and a valid email address, complete a new submission.
3. An email is sent to the user address.

**What application are you using?**
 OJS 3.4.0.5

**PRs**
#### Stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9800
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4214 [TEST ONLY]

#### Main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9808
[ojs](https://github.com/pkp/ojs) -->  https://github.com/pkp/ojs/pull/4219 [TEST ONLY]

**Comment by pilasou** [comment]
The problem may be due to the "handle" in SendSubmissionAcknowledgement file. It is always active no matter the options that is selected. The options have no impact on this method so it does not work, and emails are always sent. 
See SendSubmissionAcknowledgement lign 59 to 69: https://github.com/pkp/pkp-lib/blob/a95b221969aa35aa25540c23f8874a9226fcc49e/classes/observers/listeners/SendSubmissionAcknowledgement.php#L59

**Comment by touhidurabir** [comment]
@Vitaliy-1 can you check the PR at https://github.com/pkp/pkp-lib/issues/9797#issue-2187228427 . need forward porting to main and will do once confirmed .

**Comment by Vitaliy-1** [comment]
@touhidurabir, looks good in is ready to merge. Thanks!

**Comment by touhidurabir** [comment]
`pkp-lib` changes are merged . Need to do the submodule update later manually .
