### ISSUE TITLE
Fetch submission' title for the reviewer assignments list

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9825]
Reviewer dashboard should include not only data related to the assignments but also submission title. Submission could be added to the review assignments schema the same way as it's done for the review/stage assignments in the submission schema, see https://github.com/pkp/pkp-lib/issues/8885

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/9908
tests: https://github.com/pkp/ojs/pull/4253

**Comment by Vitaliy-1** [comment]
@jonasraoni, can you take a look at this PR, which includes fetching submissions into review assignments list in a performant way?

**Comment by jardakotesovec** [comment]
Hi @Vitaliy-1 ,
just connecting this to the UI. And I realised that when we are showing submission metadata - we have slightly different fallbacking strategy there.

If meta are not available in the 'current UI language', it fallbacks to the publication locale and than it would fallback to the journal primary language. 

To be able to keep consistent with this logic - I would also need to know the publication locale - could we add that one as well?

**Comment by jardakotesovec** [comment]
@Vitaliy-1 Currently getting following payload from `/publicknowledge/api/v1/_submissions/reviewerAssignments?offset=0&count=30&page=1&perPage=30`

```
{
            "_href": "http:\/\/localhost:7001\/index.php\/_\/api\/v1\/_submissions\/reviewAssignments\/6",
            "cancelled": false,
            "comments": null,
            "competingInterests": null,
            "considered": null,
            "dateAcknowledged": null,
            "dateAssigned": "2024-05-23 05:22:12",
            "dateCancelled": null,
            "dateCompleted": null,
            "dateConfirmed": null,
            "dateDue": "2024-06-20 00:00:00",
            "dateNotified": "2024-05-23 05:22:12",
            "dateRated": null,
            "dateReminded": null,
            "dateResponseDue": "2024-06-20 00:00:00",
            "declined": false,
            "id": 6,
            "lastModified": "2024-05-23 05:22:12",
            "publicationTitle": {
                "en": "Genetic transformation of forest trees",
                "fr_CA": ""
            },
            "quality": null,
            "recommendation": null,
            "reminderWasAutomatic": false,
            "requestResent": false,
            "reviewFormId": null,
            "reviewMethod": 2,
            "reviewRoundId": 4,
            "reviewerFullName": "Paul Hudson",
            "reviewerId": 8,
            "round": 1,
            "stageId": 3,
            "step": 1,
            "submissionId": 5
        },
```

Interestingly also statusId is missing - could that be included or are there any concerns including that?

**Comment by Vitaliy-1** [comment]
pkp-lib: https://github.com/pkp/pkp-lib/pull/10024
tests: https://github.com/pkp/ojs/pull/4302

**Comment by Vitaliy-1** [comment]
@jardakotesovec, can you take a look if it's what's needed?

**Comment by jardakotesovec** [comment]
@Vitaliy-1 Yes, sorry for delay that look as what I need, feel free to merge it :-)
