### ISSUE TITLE
Reviewer search roadblock

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#983]
From UI/UX testing:

> Rename “Advanced Search” to “Find Reviewers” or “Reviewer List”

**Comment by asmecher** [comment]
Renamed "Advanced Search" to "Find Reviewer". @NateWr, the major feature of that interface is the search filter form, but that (like all filter forms) is collapsed by default. Any opinion on expanding the filter by default for that one form? It would break consistency, but it would make that interface clearer, I think. We might consider this elsewhere in cases where the filter form should be prominent.

**Comment by NateWr** [comment]
The name change will be a big help. You're right that search should be expanded by default. I'd also like to maybe show the grid by default. I think this is worth a bit more looking at for 1.2 so I'll assign to myself if that's alright.

**Comment by asmecher** [comment]
Sure, thanks!

**Comment by NateWr** [comment]
Doing some work on this. Quick question: what happens if the user enters a review interest that doesn't exist in the database? Will that result in 0 matches? Any way we can restrict one of these tag-it fields to valid entries?

**Comment by asmecher** [comment]
Tag-It doesn't appear to have an option to limit tags only to the existing set, but this could be accomplished pretty quickly by using the beforeTagAdded callback to check for nonexistent tags and cancel their addition, OTOH: https://github.com/aehlke/tag-it/blob/master/README.markdown

**Comment by NateWr** [comment]
Ok I've done a bunch of work on this now and submitted a couple of PRs:

[omp](https://github.com/pkp/omp/pull/196)
[pkp-lib](https://github.com/pkp/pkp-lib/pull/1064)

This involved changing some things which I haven't really touched before so I suspect we'll get some broken tests or comments during code review that need to be addressed. Once the PR is ok'd I'll send a PR over for OJS.

Here's a look at what the process is like now:

![select-reviewer](https://cloud.githubusercontent.com/assets/2306629/12396943/0f39aa60-be02-11e5-9729-b2e2ca98c948.gif)

I've cut everything out of the initial screen to focus on what the user's were most looking for: a searchable list of reviewers. Users can jump from this screen over to other selection methods (creation/enrollment) and jump back to it at any stage.

I think this will go a long way in addressing the issues brought up by the user tests and helping users by giving them what they most expected up-front.

There are a still a few issues that I think probably should be thought about, though we can test them with users before sinking lots more time into the problem:

1. When enrolling a new user, I think we have the same problem whereby the type-to-find-a-user control may confuse users. Ideally, I'd love to see this work like the reviewer select grid, where the user can search users, select one and opt them in as a review, and only then see the rest of the reviewer form with the new user selected.

2. The "back to search" link at the top of the Create/Enroll forms is easily missed. Users may struggle to find it and get frustrated. I'd love to think of a better, more consistent way to handle linked forms/actions like these but it may not be that high of a priority.

3. There may be more code that can be stripped out. I removed what I was sure wasn't relevant, but I didn't do a very systematic review of all the code in these linked forms. My sense is that we could probably create one JS handler that would better coordinate data and flow between them, but I felt that was maybe more investment than it warranted from me at this time.

**Comment by NateWr** [comment]
Another issue that could cause frustration is that the name search only returns full matches with individual columns (first name, last name, username, etc) in the user database. As a result, a search for "Gonzalo" will return "Gonzalo Favio". But a search for "Gonzalo Favio" will not return that user.

This problem also exists in the autocomplete field in the enroll form.

We could split the search string by spaces and search each fragment for matches. But in this case, a search for "Gonzalo Favio" could potentially return "Gonzalo Hernandes", which would seem just as odd.

We could require a match for all string fragments, eg:

```
...
AND (first_name LIKE '%fragment_1%' OR last_name LIKE '%fragment_1'% ... )
AND (first_name LIKE '%fragment_2%' OR last_name LIKE '%fragment_2'% ... )
...
```

But I'm not sure about the performance implications or if there's a better way to do this with SQL.

**Comment by asmecher** [comment]
@NateWr, neither SQL nor ADODB are very helpful in this regard. Searching a concatenation of field could also work, but it's likely to be horribly slow.

**Comment by NateWr** [comment]
I've added an enable/disable toggle to the reviewer search filters after [some discussion](https://github.com/pkp/omp/pull/196#issuecomment-173405863). Here's what that looks like:

![disable-reviewer-filters](https://cloud.githubusercontent.com/assets/2306629/12578477/1135c9c6-c419-11e5-9358-9bc9f3b3be68.gif)

I also fixed the reviewer interests search as that was apparently broken. Could someone take a look at 45473fd just to make sure I haven't done anything wrong in the guts (it required changing the name where the post data is located).

I'll update the PR for OMP to see how the tests do now.

**Comment by NateWr** [comment]
I've stumbled on a couple more issues related to reviewers:

__Missing in "My Assigned"__
Even though I have assigned a user as a reviewer, the review doesn't appear in their "my assigned" queue. Is it possible that this is because the submission is already at the production stage? Can anyone else reproduce this problem?

![reviewer-assigned](https://cloud.githubusercontent.com/assets/2306629/12585315/6d290642-c443-11e5-9cc5-271d793268e9.png)

![reviewer-no-my-assigned](https://cloud.githubusercontent.com/assets/2306629/12585319/74050bd2-c443-11e5-87a4-9bdb6bc2875d.png)

__Missing in user grid__
When I use the option to create a new reviewer when assigning a reviewer, the user gets created and can be found in the reviewer selection grid. But the user can not be located in the standard users grid.

![create-reviewer](https://cloud.githubusercontent.com/assets/2306629/12585364/acb9436c-c443-11e5-9caa-6cade1b83d3c.png)

![create-reviewer-not-found](https://cloud.githubusercontent.com/assets/2306629/12585363/acb7962a-c443-11e5-891b-a464c7c667f7.png)

**Comment by NateWr** [comment]
Oh and to clarify these issues exist in `master` so weren't introduced with the recent changes.

**Comment by asmecher** [comment]
Looks great, Nate -- just a couple of comments. Can you file the problems you encountered as a separate issue? Agreed that this probably doesn't have anything to do with it.

**Comment by asmecher** [comment]
Most recent PRs -- @NateWr, make sure you add links when you open these, otherwise it gets tricky to keep track.

https://github.com/pkp/ojs/pull/723
https://github.com/pkp/omp/pull/200
https://github.com/pkp/pkp-lib/pull/1064

**Comment by NateWr** [comment]
Ok the two issues are filed elsewhere now:

#1091 and #1090

**Comment by asmecher** [comment]
New PRs:

https://github.com/pkp/pkp-lib/pull/1095
https://github.com/pkp/ojs/pull/725
https://github.com/pkp/omp/pull/204

**Comment by asmecher** [comment]
Merged; closing!
