### ISSUE TITLE
Enrolling an existing user as reviewer is broken

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9832]
**Describe the bug**
From: https://forum.pkp.sfu.ca/t/php-fatal-error-when-trying-to-search-user-in-add-reviewer-enroll-an-existing-user-as-reviewer/87148

When inserting name in the search bar for Enroll an Existing User as Reviewer, php fatal error occurred and no result is display. only spinning wheel.

**Steps I took leading up to the issue**
1. Add reviewer
2. Enroll an Existing User as Reviewer
3. Search Name

What application are you using?
OJS 3.4.0.5, PHP 8.2, MariaDB 10.5

```
AH01071: Got error ‘PHP message: PHP Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column ‘u.user_id’ in ‘where clause’ in /home/xxxxxxx/public_html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414\nStack trace:
n#0/home/xxxxxxx/public_html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare(‘select u.* fr…’)
n#1/home/xxxxxxx/public_html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}(‘select u.* fr…’, Array)
n#2/home/xxxxxxx/public_html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback(‘select u.* fr…’, Array, Object(Closure))
n#3/home/xxxxxxx/public_html/ojs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\Database\Connection->run(‘select u.* fr…’…’, referer:
```

This is a regression caused by https://github.com/pkp/pkp-lib/issues/9541.

<ht>

PRs:
stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/9882
- https://github.com/pkp/ojs/pull/4243 (only submodule update)
- https://github.com/pkp/omp/pull/1543 (only submodule update)
- https://github.com/pkp/ops/pull/656 (only submodule update)

main:
- https://github.com/pkp/pkp-lib/pull/9881
- https://github.com/pkp/ojs/pull/4242 (only submodule update)

**Comment by Vitaliy-1** [comment]
The example of the query that's causing the specific for MariaDB issue:
```sql
select u.* from users as u where u.disabled = 0 and exists 
(select * from user_user_groups as uug inner join user_groups as ug on uug.user_group_id = ug.user_group_id left join
(select uug.user_id from user_user_groups as uug inner join user_groups as ug on uug.user_group_id = ug.user_group_id where uug.user_id = u.user_id and ug.context_id in (1) and ug.role_id in (4096)) as agr on uug.user_id = agr.user_id where uug.user_id = u.user_id and ug.context_id in (1) and agr.user_id is null);
```
The problem is in the subsubquery `where` clause that checks column value existence in another column: `where uug.user_id = u.user_id`.

**Comment by Vitaliy-1** [comment]
So, it seems that Maria DB doesn't permit using outer references in the derived tables...

**Comment by Vitaliy-1** [comment]
Likely related mariadb feature request: https://jira.mariadb.org/browse/MDEV-19078

**Comment by bozana** [comment]
Hi @Vitaliy-1, could you please review the PR above?
Thanks a lot!

**Comment by Vitaliy-1** [comment]
@bozana, the code itself looks good. Have you tested that with users having several roles within the journal?

**Comment by bozana** [comment]
Hi @Vitaliy-1 and @jonasraoni, I changed the SQL according to the comments from Jonas. Could you take a look again please?
I have tested it with users having several roles...

**Comment by Vitaliy-1** [comment]
Looks good to me, thanks!

**Comment by bozana** [comment]
@jonasraoni, could you also take a look -- OK now?
