### ISSUE TITLE
you can access to worflow process even if a submission is incomplete

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#9837]
**Describe the bug**
If you enter the id of an incomplete submission directly into the URL: e.g. https://ojs34.testdrive.publicknowledgeproject.org/index.php/testdrive-journal/workflow/index/981/4 (here, 981 is an incomplete submission), you can access the editorial workflow and accept the submission, and so on.

So I think there should be a safety feature to prevent this.
**To Reproduce**
just change the id of the submission in the url

**What application are you using?**
 OJS 3.4 (test drive)

Thank you

**PRs**

#### Stable-3.3.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9869
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4238 [TEST ONLY]

#### Stable-3.4.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10008
[ojs](https://github.com/pkp/ojs) -->  https://github.com/pkp/ojs/pull/4295 [TEST ONLY]

#### Main
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10007
[ojs](https://github.com/pkp/ojs) -->  https://github.com/pkp/ojs/pull/4294 [TEST ONLY]

**Comment by touhidurabir** [comment]
This issue also exists in 3.3.0 + .

**Comment by touhidurabir** [comment]
@Vitaliy-1 can you take a look at the PR at https://github.com/pkp/pkp-lib/issues/9837#issue-2210378703 . If all ok, need to forward port it to 3.4.0 and main .

**Comment by touhidurabir** [comment]
@Vitaliy-1 , ported to main and stable-3.4.0 . Also please see the comment https://github.com/pkp/pkp-lib/pull/9869#issuecomment-2139319509

**Comment by touhidurabir** [comment]
All merged . will let the submodule get updated later .
