### ISSUE TITLE
Add new functions for submission locales conversion into other forms/standards

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9838]
Currently there are functions in LocaleConversion that convert locales from one format into another. This needs to be done also for the new submission and metadata locales that now uses the Weblate language list.
They are for example used in Crossref, DataCite, mEDRA, DOAJ, PubMed, OAI exports.
Search the code for "LocaleConversion::" to see where it is used for submission locales. It could also be that those LocaleConversion functions are not used, for example here https://github.com/pkp/orcidProfile/blob/main/OrcidProfilePlugin.php#L405, so I do not know how should we find all places that needs to be addressed, but... at least to start with LocaleConversion:: and maybe most important plugins...

**Comment by bozana** [comment]
@ajnyga and @jyhein, would it be possible for you to address this issue? It is 'a left-over' form the https://github.com/pkp/pkp-lib/issues/9425 -- I fully forget about this at the end :-) And because you have a better overview how to best convert it, I would love you to do it, if possible. I think you were testing it with the PHP intl functions, no?
Maybe to then either create a new SubmissionLocaleConversion class that will handle this, or to add further function into the existing LocaleConversion...

**Comment by ajnyga** [comment]
Thanks, yes this is in my followup list. I also hope to at the same time map what kind of multilingual data these services accept. You can assign this to me.

**Comment by bozana** [comment]
Hi @ajnyga, I am currently working on this issue https://github.com/pkp/pkp-lib/issues/9707 -- to align the UI locales with Weblate locales. I will then need to consider these conversion functions for UI locales however, so I think this issue is not needed any more.

**Comment by bozana** [comment]
This is done in https://github.com/pkp/pkp-lib/issues/9707. Thus closing...
