### ISSUE TITLE
Sitemap index namespace URL shouldn't contain https

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#9845]
**Describe the bug**
Google Search Console complains that the sitemap index file deposited for a multi-journal site contains a namespace error

**To Reproduce**
https://github.com/pkp/pkp-lib/blob/69e7baad781699d6bbdbf65124c3a0c35db2c0fe/pages/sitemap/PKPSitemapHandler.php#L29 

should contain http://www.sitemaps.org/schemas/sitemap/0.9 as namespace URL and not https://www.sitemaps.org/schemas/sitemap/0.9

See also https://www.sitemaps.org/protocol.html

Namespace URLs usually do not have https.

**What application are you using?**
 OJS 3.3.0-17

**Comment by asmecher** [comment]
Confirmed: https://webmasters.stackexchange.com/questions/108855/is-incorrect-to-have-the-https-version-of-the-sitemaps-org-url-in-the-xmlns-site

**Comment by asmecher** [comment]
Fixed for the next releases!
