### ISSUE TITLE
Unable to create new autor's checklist-items when ALL former items are deleted

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#9849]
**Describe the bug**
If you delete all items from the author's check-list you are not able to create new items again.

**To Reproduce**
1. Go to /management/settings/workflow#submission/submissionChecklist
2. Remove all items and save.
3. Click on "New Item" to create a new one.
4. See a circle spinning for ever. 

**What application are you using?**
 OJS 3.3.0-17 (dockerized)

**Additional information**

Apache reports a 500 error:
```
[30/Mar/2024:23:30:47 +0000] "POST /myjournal/$$$call$$$/grid/settings/submission-checklist/submission-checklist-grid/update-item HTTP/1.1" 500 - "https://foo.org/myjournal/management/settings/workflow" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"
```

PHP reports the following at /var/log/apache2/error.log 

```
[Sat Mar 30 23:32:06.120323 2024] [php:error] [pid 21] [client 93.176.182.4:47474] PHP Fatal error:  Uncaught ValueError: max(): Argument #1 ($value) must contain at least one element in /var/www/html/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php:98\nStack trace:\n#0 /var/www/html/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php(98): max()\n#1 /var/www/html/lib/pkp/controllers/grid/settings/submissionChecklist/SubmissionChecklistGridHandler.inc.php(147): SubmissionChecklistForm->execute()\n#2 /var/www/html/lib/pkp/classes/core/PKPRouter.inc.php(397): SubmissionChecklistGridHandler->updateItem()\n#3 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()\n#4 /var/www/html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route()\n#5 /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php(360): Dispatcher->dispatch()\n#6 /var/www/html/index.php(68): PKPApplication->execute()\n#7 {main}\n  thrown in /var/www/html/lib/pkp/controllers/grid/settings/submissionChecklist/form/SubmissionChecklistForm.inc.php on line 98, referer: https://foo.org/myjournal/management/settings/workflow
```

"Argument 1 ($value) must contain at least one element" part, it's quite explicit so I will try injecting an item into the database to do the job... but deletion of all items should be blocked... or allowed to create new items when the list is clean.

It is curious that we have never encountered this error before, isn't it? :-)

**PRs**
#### Stable-3.3.0
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9856
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4232 [TEST ONLY]

**Comment by asmecher** [comment]
@marcbria, PHP has been getting stricter about operands supplied to built-in functions; I suspect that's why this is showing up as an error.

@touhidurabir, here's a super quick one to look at when you get a sec.

**Comment by marcbria** [comment]
Thanks for the comments Alec.
It also explains why it didn't happen with prior docker images (ojs 3.3.0-15 not using php8.1 yet).

A workaround just in case somebody falls in same hole:

1. Confirm it's same issue and get your journal's ID:

```
SELECT *
FROM `journal_settings`
WHERE `setting_name` LIKE '%checklist%'
```
![image](https://github.com/pkp/pkp-lib/assets/2779168/07508add-5dc7-4812-bce9-d611a248558c)

In my case, I only get null values with journal ID = 1.

2. Add some content to settings_value:

```
UPDATE `journal_settings`
SET `setting_value` = '{\"1\":{\"order\":2,\"content\":\"fixThis\"}}'
WHERE `journal_id` = 1
AND `setting_name` = 'submissionChecklist';
```

After this, you will be able to edit in OJS and create new items.

**Comment by touhidurabir** [comment]
fixed by https://github.com/pkp/pkp-lib/pull/9856
