### ISSUE TITLE
Wrong portuguese (pt_BR) validating message

### ISSUE THREAD

**Issue by henriquejsfj** [pkp/pkp-lib#9853]
## Issue Description
There is a little issue in `submission.wizard.validating`, in pt_BR should be "Verificando sua submissão" instead of "Verificando seu submissão". 

## How to reproduce / Current behavior
This message appears in the last stage when submitting, since it appears for a fraction of seconds nobody noticed it before.

## What application are you using?
 OJS, version 3.4

**Comment by asmecher** [comment]
Thanks, @henriquejsfj, I've merged https://github.com/pkp/pkp-lib/pull/9854 to `main` and `stable-3_4_0`.
In the future, it's quickest/easiest to make translation changes using our Weblate install at: https://translate.pkp.sfu.ca

**Comment by henriquejsfj** [comment]
Nice @asmecher, didn't know about Weblate!
