### ISSUE TITLE
[UI] Make the catalog page work

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#986]
- [ ] Several of the tabs don't load monograph details
- [ ] The feature/new releases designation is broken
- [ ] Probably lots more... 

The catalog page position is getting reworked. See #985.

**Comment by NateWr** [comment]
@asmecher @beghelli 

As part of #985 I've started looking at the catalog page. It's going to take some work to get it going. There are three problems:

1. It's broken. No big deal just going to take some work to get the functionality back in.
2. The category and series selection technique needs to change. Jumping from a select dropdown doesn't work for keyboard users.
3. The featuring technique needs some work. The icon-based system is not clear enough (there's also no indication that we support per-category/series features or global features).

Rather than spend the time refactoring all of this code that's used exclusively in OMP, I wonder if our time would be better spent implementing grids in these sections.

Here's my mockup of what the catalog page could look like if it leaned more heavily on grids. What do you guys think?



We should also get some feedback from UX group (John and Kevin). But I wanted to ask you first since you guys have a clearer sense of how easy it might be to transition the existing code over to grids.

**Comment by beghelli** [comment]
I like the idea of using existing components and getting rid of the ones we just implemented for this part of the system. I like the all monographs tab. But I feel that the categories one is confusing. I expected to see categories listed there, and not submissions. Also, it took me some time to figure it out that the controllers on the right would load the grid with a filter, showing only the submissions assigned to that category.

I would try to implement a category grid for this one, with the categories being the categories :P and the category data being the submissions assigned to that category. I would also use the grid accordion feature, to let users expand or collapse the submissions.

For the series, the same thing. If you want I can draw something @NateWr, just to make it clear.

**Comment by asmecher** [comment]
@beghelli, feel like tackling the implementation of this one? (@NateWr, if I'm poaching something in progress, please let me know!)

**Comment by NateWr** [comment]
Would love it if @beghelli took it off my hands. :) Maybe throw #985 in to kill two birds with one stone?

**Comment by NateWr** [comment]
The only thing I don't like about a category grid is the lack of focus. I guess that usually when people are visiting the page they don't want to see all of the monographs for all of the categories. In a very large library, the grid list could be pretty long, right?

I think you're right about the links on the right being not very clear. I'm not sure precisely what the best way to organise this is. Probably people want a list of categories with add/edit/delete links right? Is submission searching really important on this page?

**Comment by NateWr** [comment]
Ahh yes, we do need submission searching/listing in order to flag as featured or new release...

**Comment by beghelli** [comment]
@NateWr I agree, people should have the possibility to hide monographs they don't want to see. Even better, they should have the option to show the ones they want. That's why I suggested that we used that grid feature, so the monographs would be collapsible. We can define the initial state to collapsed, so they would only see the categories names.

**Comment by NateWr** [comment]
Ok let's give it a shot.

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/pkp-lib/pull/1322
https://github.com/pkp/omp/pull/254

The second half of the OMP pull was especially satisfying to review, @beghelli, with all those removals! Just a few minor comments.

**Comment by NateWr** [comment]
I'm having trouble getting the **New Catalog Entry** modal working. What's the status on this part?

When I click on **New Catalog Entry** in the Catalog modal, there's a dropdown list that says "Select a submission" but there are no submissions available to select. I've moved a submission through to Production stage.

What are the pre-requisites for getting a submission into this list? What's the intended purpose of this modal?

**Comment by beghelli** [comment]
The modal is supposed to be a shortcut to bring submissions into the catalog. If it's listing nothing, then all your submissions are published already. But I will double check that.

**Comment by beghelli** [comment]
Checked both code and UI and it's working as expected. Closing for now.
