### ISSUE TITLE
Public masthead page

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9860]
The masthead page should be under context's about. 
It should list all active masthead services i.e. all masthead roles as well as uses that are active in those masthead roles and that have accepted to be listed on masthead. 
Users are listed with following information: full name, affiliation, start date and orcidIcon (if ORCID authorized).
Reviewer role is treated differently: The reviewers are listed for the previous year. All reviewers that have submitted a review in the previous year will be displayed on the masthead page.

JII plugin should be able to overwrite the masthead users -- generally, a user can opt-out of being displayed on masthead, but this does not guild for JII users -- according to JII all users in the masthead roles needs to be displayed (and cannot opt-out).

PRs:
- https://github.com/pkp/pkp-lib/pull/9861
- https://github.com/pkp/ojs/pull/4234
- https://github.com/pkp/omp/pull/1552
- https://github.com/pkp/ops/pull/665

Upgrade script that adds the Editorial Masthead nav menu item under About nav menu item:
PRs:
- https://github.com/pkp/pkp-lib/pull/9934
- https://github.com/pkp/ojs/pull/4264
- https://github.com/pkp/omp/pull/1562
- https://github.com/pkp/ops/pull/675

**Comment by bozana** [comment]
@asmecher, could you please review the PRs above?

**Comment by bozana** [comment]
@asmecher, could you please also review these PRs:
- https://github.com/pkp/pkp-lib/pull/9934
- https://github.com/pkp/ojs/pull/4264
They provide an upgrade script that should add the new navigation menu item Editorial Masthead to the existing journals...
Thanks a lot!

**Comment by asmecher** [comment]
Thanks, @bozana, please go ahead! In general it's not a good idea to use DAOs in the upgrade scripts, because the DAO may change in the future (e.g. as the schema gets adjusted) but the upgrade scripts should not evolve. But we don't have any plans to change this aspect of the code, so I suppose it's OK.
