### ISSUE TITLE
PKP-LIB: Hook call author validate errors param missing &-reference

### ISSUE THREAD

**Issue by jyhein** [pkp/pkp-lib#9867]
**Describe the bug**
Hook call param `$errors` missing `&`, i.e. should be `&$errors`

File: PKP-LIB: classes/author/Repository.php
Line: 143
Code: `Hook::call('Author::validate', [$errors, $author, $props, $allowedLocales, $primaryLocale]);`
Code should be: `Hook::call('Author::validate', [&$errors, $author, $props, $allowedLocales, $primaryLocale]);`

**Comment by asmecher** [comment]
Thanks, @jyhein -- added the `&` in `main` and `stable-3_4_0`.
