### ISSUE TITLE
[UI] Create top logged-in bar

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#987]
Everyone in user testing has expected to find logout details at the top right. Let's go ahead and implement a top admin bar for our secondary navigation menu.

![context-view-3](https://cloud.githubusercontent.com/assets/2306629/11928455/97c5ab88-a7cb-11e5-9eb5-3261ca6daf8c.png)

How far we'll go for OMP 1.2 is still up in the air, but here's a list of things to consider in vague order of importance:

- [x] Relocate login/logout/logged-in-as/user-profile buttons to the top
- [x] Move the View Site link to the top.
- [x] Move the journal/press context switcher to the top
- [ ] Maybe (?) consider some kind of editorial/admin context or perhaps some kind of breadcrumb trail so that the admin bar can point towards the current location in the system.

[Original discussion](https://github.com/pkp/pkp-lib/issues/941#issuecomment-164431862)

**Comment by NateWr** [comment]
I'm going to go ahead and call this done. If we want to do more with the top bar (and I think there's much we could do) let's deal with it separately.

I'll leave it open until the PRs are successfully tested and merged.

**Comment by beghelli** [comment]
@NateWr There are some problems with the tests, are you able to look at it? If you prefer, I can take a look here, I can run the tests locally, it's easier to fix them. Just let me know.

**Comment by NateWr** [comment]
@beghelli Thanks, I'll be working again some tomorrow so I'll take a look. I'll let you know if I have any trouble.

**Comment by NateWr** [comment]
Merged.

**Comment by asmecher** [comment]
+1, this looks very sharp.
