### ISSUE TITLE
Fatal error at Recommend by similarity plugin

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9872]
**Describe the bug**
The commit https://github.com/pkp/ojs/commit/00f365eaa507f6fa1a4deb164f66c6fe014bf1e6 introduced the regression below:

```php
PHP Fatal error:  Uncaught TypeError: APP\plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin::buildTemplate(): Argument #1 ($templateManager) must be of type APP\template\TemplateManager, Smarty_Internal_Template given, called in plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin.php on line 47 and defined in plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin.php:59
Stack trace:
#0 plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin.php(47): APP\plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin->buildTemplate(Object(Smarty_Internal_Template))
#1 [internal function]: APP\plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin->APP\plugins\generic\recommendBySimilarity\{closure}('Templates::Arti...', Array)
#2 lib\pkp\classes\plugins\Hook.php(139): call_user_func_array(Object(Closure), Array)
#3 lib\pkp\classes\plugins\Hook.php(113): PKP\plugins\Hook::run('Templates::Arti...', Array)
#4 lib\pkp\classes\template\PKPTemplateManager.php(1782): PKP\plugins\Hook::call('Templates::Arti...', Array)
#5 cache\t_compile\42362804174f266c598cdb32c3208fc745b92101^1c372c95cd85572e0fbc9a53d0323a0b229cfc78_0.app.frontendpagesarticle.tpl.php(43): PKP\template\PKPTemplateManager->smartyCallHook(Array, Object(Smarty_Internal_Template))
#6 lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php(123): content_66154f0d1ddd65_21969434(Object(Smarty_Internal_Template))
#7 lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#8 lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#9 lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1)
#10 lib\pkp\lib\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, '42362804174f266...', NULL, 1)
#11 lib\pkp\classes\template\PKPTemplateManager.php(1367): Smarty_Internal_TemplateBase->display('frontend/pages/...', NULL, '42362804174f266...', NULL)
#12 pages\article\ArticleHandler.php(355): PKP\template\PKPTemplateManager->display('frontend/pages/...')
#13 [internal function]: APP\pages\article\ArticleHandler->view(Array, Object(APP\core\Request))
#14 lib\pkp\classes\core\PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#15 lib\pkp\classes\core\PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#16 lib\pkp\classes\core\Dispatcher.php(165): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#17 lib\pkp\classes\core\PKPApplication.php(388): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#18 index.php(21): PKP\core\PKPApplication->execute()
#19 {main}
  thrown in plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin.php on line 59
```

**To Reproduce**
1. Enable the Recommend by similarity plugin
2. Access an article

**What application are you using?**
OJS 3.4

**Comment by jonasraoni** [comment]
Solved by the 
- `stable-3_4_0` https://github.com/pkp/ojs/commit/67a5d80991ba357a28acc13d107875b62accfb8c
- `main` https://github.com/pkp/ojs/commit/ccdc684a9f9ba5e5ef3e0726a92f78c346a6377d

**Comment by saalam** [comment]
Hello @jonasraoni 
After we upgraded our OJS to the latest version which is 3.4.0.8, The error below appears continuously. Could you please help us regarding this issue. Many Thanks.

`PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - int in //public_html/plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.php:83
Stack trace:
#0 //public_html/plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.php(46): APP\plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin->buildTemplate()
#1 [internal function]: APP\plugins\generic\recommendBySimilarity\RecommendBySimilarityPlugin->APP\plugins\generic\recommendBySimilarity\{closure}('Templates::Arti...', Array)
#2 /public_html/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array(Object(Closure), Array)
#3 /public_html/lib/pkp/classes/plugins/Hook.php(113): PKP\plugins\Hook::run('Templates::Arti...', Array)
#4 /public_html/lib/pkp/classes/template/PKPTemplateManager.php(1787): PKP\plugins\Hook::call('Templates::Arti...', Array)
#5/public_html/cache/t_compile/a4fc84a2d9d2a85c011fcc528f09577e88e2fcff^1c372c95cd85572e0fbc9a53d0323a0b229cfc78_0.app.frontendpagesarticle.tpl.php(43): PKP\template\PKPTemplateManager->smartyCallHook(Array, Object(Smarty_Internal_Template))
#6 /public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_67adfef71bfb08_04115926(Object(Smarty_Internal_Template))
#7 /public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#8 /public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#9 /public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1)
#10 /public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, 'a4fc84a2d9d2a85...', NULL, 1)
#11 /public_html/lib/pkp/classes/template/PKPTemplateManager.php(1372): Smarty_Internal_TemplateBase->display('frontend/pages/...', NULL, 'a4fc84a2d9d2a85...', NULL)
#12/public_html/pages/article/ArticleHandler.php(355): PKP\template\PKPTemplateManager->display('frontend/pages/...')
#13 [internal function]: APP\pages\article\ArticleHandler->view(Array, Object(APP\core\Request))
#14 /public_html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#15 /public_html/lib/pkp/classes/core/PKPPageRouter.php(278): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false)
#16 /public_html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route(Object(APP\core\Request))
#17 /public_html/lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#18 /public_html/index.php(21): PKP\core\PKPApplication->execute()
#19 {main}
  thrown in /public_html/plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.php on line 83`

**Comment by asmecher** [comment]
@saalam, that is a different problem; rather than commenting on a closed issue, I'd suggest posting the details on our support forum: https://forum.pkp.sfu.ca

**Comment by saalam** [comment]
@asmecher, Thank you so much. I just opened a new topic on the forum 
https://forum.pkp.sfu.ca/t/recommendbysimilarityplugin-fatal-error/94966
