### ISSUE TITLE
Download reviews

### ISSUE THREAD

**Issue by MrRob100** [pkp/pkp-lib#9873]
The ability to download reviews in PDF format with the options 'Export author-friendly version of the form, displaying only sections marked as visible to the author' or 'Export editor version of the form, displaying all sections of the review form'. These options will be available from the 'Read review' modal

PRs:
https://github.com/pkp/ojs/pull/4512
https://github.com/pkp/pkp-lib/pull/10226
https://github.com/pkp/ui-library/pull/410
https://github.com/pkp/omp/pull/1757

Implementation:

<img width="1022" alt="Screenshot 2024-07-18 at 16 13 50" src="https://github.com/user-attachments/assets/c2ec1421-6880-4837-b86f-f13915cfc9dd">

Examples of a downloaded reviews:

<img width="806" alt="Screenshot 2024-07-18 at 16 34 40" src="https://github.com/user-attachments/assets/3e8c55dc-d4c3-43d3-b363-1ba11bf60610">

<img width="789" alt="Screenshot 2024-07-18 at 16 19 59" src="https://github.com/user-attachments/assets/c4cd1e48-f415-4bb0-b6c1-4aa9f12c0591">

<img width="588" alt="Screenshot 2024-07-19 at 11 21 22" src="https://github.com/user-attachments/assets/4e918e43-c245-4edd-8fde-0dc19084b0e9">

**Comment by MrRob100** [comment]
@Devika008 I would like to revisit this and get your ideas about the design of this please :)

**Comment by LetyBA** [comment]
I find this incredibly helpful, it is in process of development as a plugin?

**Comment by MrRob100** [comment]
@LetyBA No, it's in process of development for OJS 3.5 :)

**Comment by Devika008** [comment]
@MrRob100 on it! Sharing the designs with you in some :D

**Comment by Devika008** [comment]
**My Proposal**

One common concern users frequently voice about OJS is its heavy reliance on clicks and modals, leading to a frustratingly lengthy process just to perform a single action. To address this issue, I've streamlined the interface by significantly reducing the number of modals and clicks required to make decisions. Instead, I've condensed the options into a convenient dropdown menu with Text Only Buttons. This not only enhances user experience but also demonstrates the platform's adaptability, as evidenced by the inclusion of alternative formats beyond just PDF, ensuring future scalability and flexibility.

![image](https://github.com/pkp/pkp-lib/assets/112014397/3a5ba2e3-97a3-4437-801e-3c03da25e11e)

I'm interested in hearing your thoughts on this proposal.

**Comment by MrRob100** [comment]
@Devika008 Thanks, this crossed our minds. Great to have your input. This will make the dev a lot simpler too as we won't have a nested modal @jardakotesovec

**Comment by MrRob100** [comment]
@asmecher About the downloading of reviews in XML format, I want to confirm whether this will be XML in JATS XML format or a more freeform structure. Can you provide a use case for downloading them in XML to give me an idea how to structure this XML for a review.

**Comment by asmecher** [comment]
@MrRob100, that's right, it should be JATS XML. The JATS4R recommendations for peer review provides best practices on this; see: https://jats4r.niso.org/peer-review-materials/
Let me know if you've got any specific questions about this and I'm happy to work through it here!

**Comment by MrRob100** [comment]
> @MrRob100, that's right, it should be JATS XML. The JATS4R recommendations for peer review provides best practices on this; see: https://jats4r.niso.org/peer-review-materials/ Let me know if you've got any specific questions about this and I'm happy to work through it here!

@asmecher Thanks, I have ran into some issues creating a structure for this XML. The minimum requirements for an article (https://jats4r.niso.org/peer-review-materials/#example-2-minimal-requirements-for-an-article) show that a DOI and publication date need to be provided, but articles at this stage of review don't have those data yet. Are we able to structure the data in a different way for the XML download?

**Comment by asmecher** [comment]
@MrRob100, I would suggest getting as close as you can to the JATS4R recommendations, but omitting any data that is not available. These are recommendations, and not subject e.g. to validation errors, but good guidelines for us to shoot for.

**Comment by MrRob100** [comment]
> We use 3.3.15 but maybe could work hehe or maybe if possible the developers could consider a friendly plugin for older versions... Thank you!

@LetyBA Apologies for taking a while but this feature is now in an open source plugin that supports OJS 3.3 and 3.4 https://github.com/ubiquitypress/ojs-plugin-download-reviews

**Comment by ewhanson** [comment]
Hey @MrRob100, aside from a minor style/formatting issue with pkp-lib, it looks good to me! Once that change has been made, could you rebase it against the main branches again as well a squash down each PR to a single commit? Then assuming no merge conflicts, I should be able to merge it. Thanks!

**Comment by ewhanson** [comment]
Thanks, @MrRob100. All merged! 🎉

**Comment by asmecher** [comment]
@MrRob100, it looks like the review ID is [taken from the user request without validation](https://github.com/pkp/pkp-lib/pull/10226/files#diff-d2395d3a8bc46421de23d6b0d02d0f2af245303a22b2a3a481b9501b68803e19R266) -- it isn't checked to make sure it belongs to the submission. Could you add checks to ensure that the review assignment's submission ID matches the submission? That'll prevent e.g. exposing reviews from other journals. (Heads-up @ewhanson)

**Comment by MrRob100** [comment]
> [@MrRob100](https://github.com/MrRob100), it looks like the review ID is [taken from the user request without validation](https://github.com/pkp/pkp-lib/pull/10226/files#diff-d2395d3a8bc46421de23d6b0d02d0f2af245303a22b2a3a481b9501b68803e19R266) -- it isn't checked to make sure it belongs to the submission. Could you add checks to ensure that the review assignment's submission ID matches the submission? That'll prevent e.g. exposing reviews from other journals. (Heads-up [@ewhanson](https://github.com/ewhanson))

@asmecher The method validateReviewExport is run before which runs checks

**Comment by asmecher** [comment]
@MrRob100 Gotcha, thanks, I missed that. Our general practice is to locate the validation code right where the data is fetched from the request, so that it's clear where and how it's checked -- but this does the trick as well, thanks!

**Comment by LetyBA** [comment]
I really appreciate the time an effort you put in this valuable tool. Thank you @MrRob100 @asmecher for everything.

**Comment by ddhung81** [comment]
> > We use 3.3.15 but maybe could work hehe or maybe if possible the developers could consider a friendly plugin for older versions... Thank you!
> 
> [@LetyBA](https://github.com/LetyBA) Apologies for taking a while but this feature is now in an open source plugin that supports OJS 3.3 and 3.4 https://github.com/ubiquitypress/ojs-plugin-download-reviews

**Is this version compatible for OJS 3.2?**
