### ISSUE TITLE
Error when using "View record" button in OJS Crossref DOI page 

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#9874]
**Describe the bug**
When looking at a specific DOI with Registered status in the OJS DOI page, the following "View record" button is available: 
![image](https://github.com/pkp/pkp-lib/assets/19291880/82efc641-9992-4420-a766-c51a0e29d007)

When clicking on it, the following error is displayed even if the DOI in fully registered and functionnal: 

![image](https://github.com/pkp/pkp-lib/assets/19291880/687428d9-5ca6-4a0d-8ab7-40943dafb703)

**To Reproduce**
1. As an editor in OJS, clic on DOIs section in the admin menu on the left.
2. Look for a DOI with Registered status
3. Expend the menu (clic on the down arrow on the left)
4. Clic on the "View record" button
5. An error is displayed.

**What application are you using?**
 OJS 3.4.0.5

**Comment by asmecher** [comment]
@ewhanson or @bozana, would you mind having a look at this?

**Comment by ewhanson** [comment]
Thanks for flagging this, @pilasou!

I looked into it, and there is an error with the way the successful registration message is displayed within OJS, but there is no error with the DOI registration. I'll get it fixed for the next release, but in the mean time, it's a display issue only and shouldn't affect your workflow.

**Comment by ewhanson** [comment]
@pilasou, when you open the "View record" modal, is the rest of the screen aside from the modal black?

**Comment by pilasou** [comment]
@ewhanson yes, all black except the message box: 
![image](https://github.com/pkp/pkp-lib/assets/19291880/9c9741e6-8b48-4620-8d18-9e82ccfb4efa)

**Comment by ewhanson** [comment]
PRs:

- `stable-3_4_0`: pkp/ui-library#345
- `main`: TODO

**Comment by ewhanson** [comment]
Merged! Thanks @pilasou for sharing this.
