### ISSUE TITLE
Unused AuthorForm files

### ISSUE THREAD

**Issue by henriquejsfj** [pkp/pkp-lib#9879]
**Describe the case**
The AuthorForm and its related files are marked as deprecated and unused in OJS 3.4, I'm not sure about OPS or OMS.

So, why don't we delete it? Keeping it made me spend some hours trying to access the Hooks.
(OrcidProfile Plugin keeps adding hooks to `authorform`)

Although keeping it causes no error, removing it causes no harm. (AFAIK)

**Comment by asmecher** [comment]
This is required for QuickSubmit; see https://github.com/pkp/pkp-lib/pull/9880#issuecomment-2050363587. I'm eager to rewrite QuickSubmit just so we can get rid of all of this! However, closing for now.
