### ISSUE TITLE
[UI] Single-file upload component

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#988]
Our upload component is large and geared towards multiple file uploads. But it's only ever used for uploading one file at a time. Using the `plupload` API it should be fairly easy to create an upload component that is more intuitive for single-file uploads.

This will only be a first step towards improvement of the submission process (see #975).

**Comment by NateWr** [comment]
Note for later: it might be nice to remove the "is this a revision" selection option in file upload during submission. It's only relevant later anyway.

**Comment by NateWr** [comment]
PRs
https://github.com/pkp/pkp-lib/pull/1171
https://github.com/pkp/omp/pull/221
https://github.com/pkp/ojs/pull/756

**Comment by asmecher** [comment]
The tests are complaining, both the validation and build phases. Did you want me to take a look at that, @NateWr? See e.g. https://travis-ci.org/pkp/omp/builds/110967289

**Comment by asmecher** [comment]
Everything merged, tests fixed. Thanks, @NateWr!

**Comment by NateWr** [comment]
Thanks for the cleanup @asmecher!
