### ISSUE TITLE
After Random characters in autosuggest field for categories, you'll get directly the XHR response

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#9884]
**Describe the bug**
During th submission process, when you have more than 10 categories, a autosuggest field is used. And if you enter some random characters in and hit Enter, you'll get the result of XHR request.

**To Reproduce**
1. Go to  testdrive 3.4
2. enable categories, add more than 10 categories
3. make a new submission and in For the Editors tab, try it

**What application are you using?**
 OJS 3.4 testdrive

**Comment by jardakotesovec** [comment]
This was interesting to track down. Apparently there is some default browser behaviour specifically on form with one field. So hitting enter in that one field was automatically submitting the form, which was causing to display the endpoint where the form was pointing to.

But additionally if there is form with one input and some button - it will hit the button automatically?!  So additional to the report, what was happening is that if you would enter valid category and than you would type something that does not exist and hit enter - it clicked on the 'remove' button of the previous category..  

What seems to be effective way to prevent it is just discard such enter event on the form level. I did test it with chrome, safari and firefox, so hopefully its good fix.

@jonasraoni Can you please do the code review?

Will check whether same problem is on 3.3 and main branch.

3.4.0 PR
https://github.com/pkp/ui-library/pull/381

**Comment by jardakotesovec** [comment]
3.3 is using legacy form with checkboxes, so not relevant in that particular use case, but it be problem in other vue.js form which would have just one FieldText for example

Therefore adding same improvement for 3.3 https://github.com/pkp/ui-library/pull/383


And same thing for main - its not problem in this particular scenario, because the autocomplete component from headless-ui does not let propagate enter event. But its misbehaving for example with simple FieldText.

After the code review I will also cherry pick it to the main branch.

**Comment by jonasraoni** [comment]
Yeah, this behavior is old. I agree with the fix 😁

The worst was the backspace behaving as a back button 🥲

**Comment by jardakotesovec** [comment]
Merged to 3.3 and 3.4 and cherry-picked to main. Thanks @jonasraoni

**Comment by bozana** [comment]
After this change it is not possible to enter a new line in the field References.

Removing `@keydown.enter.prevent=""` apparently fixes it.

> ... even the original issue why I added this was sneaky behavior when there is just one field in the form... 
> But that hitting enter in textarea will get suppressed if I am ignoring this keydown on form element - I don't see how someone could anticipate such behavior...

**Comment by jardakotesovec** [comment]
main:
ui-library: https://github.com/pkp/ui-library/pull/432
ojs (tests): https://github.com/pkp/ojs/pull/4485

3.4: 
ui-library: https://github.com/pkp/ui-library/pull/433
ojs (tests): https://github.com/pkp/ojs/pull/4486

3.3

**Comment by jardakotesovec** [comment]
Test for main are failing..  let me check whether its all rebased

**Comment by jardakotesovec** [comment]
All tests are passing now.

**Comment by asmecher** [comment]
All merged (except submodules which will be handled separately), thanks!
