### ISSUE TITLE
Ilegal situs di https://journal.uinsi.ac.id/pages/link/?wp=sableng88

### ISSUE THREAD

**Issue by StephenVasquez** [pkp/pkp-lib#9885]
**Describe the bug**
Saya telah menemukan situs Anda mengiklankan kasino online. ini sangat buruk bagi reputasi Anda dan juga ilegal.
https://journal.uinsi.ac.id/pages/link/?wp=sableng88

![image](https://github.com/pkp/pkp-lib/assets/166856188/97b726da-b08e-4c34-a339-3bb704ac5473)

**Comment by asmecher** [comment]
@StephenVasquez, this is not something built into Open Journal Systems -- the individual installation has probably been hacked. I would suggest contacting the journal's technical contact, identified here: https://journal.uinsi.ac.id/index.php/mazahib/about/contact
