### ISSUE TITLE
Invitations: API Support (Update Invitation and Add Invitation) + Change Profile Email Invitation

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#9887]
**Describe the feature**
There is a need to add certain features to the Invitations toolset.

1. API Support

- [ ] Update Invitation Payload
- [ ] Accept Invitation
- [ ] Decline Invitation
- [ ] Dispatch invitation (Access rights should be considered)

2. A new invitation for Change user Profile Email.
- [ ] Ability to request an email change in the user profile page
- [ ] A new mailable that will be send to the requested email, and will contain the "accept invitation url"
- [ ] Message on the user profile page that there is already an email change request. Something like:
<img width="748" alt="image" src="https://github.com/pkp/pkp-lib/assets/560456/5d20ca85-ffb7-4398-8b23-57ce50ace3fa">

- [ ] Disable the ability to request another email change if one is pending. Something like:
<img width="995" alt="image" src="https://github.com/pkp/pkp-lib/assets/560456/582a7213-a972-46cc-a59e-c164835714da">

- [ ] Ability to cancel the change request from within the profile page. Something like:
<img width="995" alt="image" src="https://github.com/pkp/pkp-lib/assets/560456/0a8fc310-2750-4eee-bdd0-177cf6740729">

---
**PRs**

OJS: pkp/ojs#4244
PKP-LIB: #9888

**Comment by asmecher** [comment]
Thanks, @defstat, I've added a review on pkp-lib: https://github.com/pkp/pkp-lib/pull/9888#pullrequestreview-2069025688

**Comment by asmecher** [comment]
Thanks, @defstat, I added a few commits and merged the following PRs based on yours:
- https://github.com/pkp/ojs/pull/4297
- https://github.com/pkp/pkp-lib/pull/10013

I've also ported the app-specific changes to OMP and OPS `main`.
