### ISSUE TITLE
[UI] Improve frontend navigation dropdown menus

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#989]
User tests showed people overwhelmingly fail to click on the top-level item of a dropdown menu (eg - About in the About dropdown). They struggled to find some of the details in the about page too, so let's consider the following:
- [x] Repeat the About link within the submenu
- [x] Consider more descriptive labels in the submenu. "About the Journal/Press"
- [ ] Consider splitting contact into its own page or maybe just add a link to it in the primary menu.

**Comment by NateWr** [comment]
I suspect we won't need to add a specific menu item for Contact but just in case I'll leave this open until we get our second round of UX tests in  January.

**Comment by asmecher** [comment]
Merged what you sent PRs for, @NateWr, and designating the rest for OMP 1.2.1 unless testing suggests we push it up the list.

**Comment by bozana** [comment]
@NateWr, I am not sure if these questions belong to this issue: Is there a possibility to see the site (index) page? How to switch the view from one press/journal to another and to the site page?

**Comment by NateWr** [comment]
@bozana We removed the frontend press/journal switcher because we (I?) felt it wasn't really of much interest for the majority of users on the frontend. I'd expect if a publisher wants a link back to the main site that they'll add it in the footer or have a customized header of some kind.

**Comment by bozana** [comment]
Yes, ok @NateWr :-) Do you maybe know how is the URL for the main site? 'index' is always redirecting me to the press page -- maybe this is a bug?

**Comment by NateWr** [comment]
I think you need to have multiple presses set up under **Administration > Hosted Presses**.

**Comment by bozana** [comment]
I have...

**Comment by NateWr** [comment]
Check the press settings for something like a "default press" maybe? I'm not entirely sure.

**Comment by bozana** [comment]
Ah... OK... When I am logged out then I can see it. When I am logged in then not :-O

**Comment by NateWr** [comment]
To be honest, I'm just not really sure about the overall site index pages and haven't spent much time on them. I think this is more common with OJS than OMP and so may be more neglected in OMP.

Perhaps we need to discuss this further with @asmecher. @bozana can you post a comment in #1231 since that's filed against OMP 1.2?

**Comment by asmecher** [comment]
We decided not to implement a site-wide page for OMP, since presses seem not to brand themselves in groups the same way journals do. So OJS should have a site-wide index page listing all journals, and OMP should not for presses.

**Comment by NateWr** [comment]
Closing. If the remaining item is important it will re-surface in future tests.
