### ISSUE TITLE
OJS 3.4.0.5 Long Delay

### ISSUE THREAD

**Issue by Mathewwss** [pkp/pkp-lib#9891]
After updating from OJS 3.3.0.14 to OJS 3.4.0.5, article pages were very slow to load.
Below is a comparison video between the versions.

https://github.com/pkp/pkp-lib/assets/50458770/ec31455d-35b8-4a6c-b84e-44e135df8d3c

Any idea??

**Comment by asmecher** [comment]
@Mathewwss, the support forum (https://forum.pkp.sfu.ca) is a better place to ask general questions like this. But I suspect the problem is caused by a plugin; try disabling off any plugins that add details to the article page. You'll probably be able to narrow it down to one plugin fairly quickly.

**Comment by Mathewwss** [comment]
https://forum.pkp.sfu.ca/t/ojs-3-4-0-5-long-delay/87738

Thanks.
