### ISSUE TITLE
Upgrade to Laravel version 11.x

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#9892]
**Describe the Proposal**
With the intension to make the release of `3.5.0` a `LTS`, we should aim to have all the dependencies updated as much as possible . The current main(pre release of 3.5.0) now have Laravel 10.x as the dependency which will be get bug fix till `August 6th, 2024` .  Also by the time the 3.5.0 get to release it will be an older version of laravel . Better to upgrade the laravel version to `11.x` .

**Additional Information**
With the release of stable laravel version `11.x` at `March 12th, 2024` which seems like a more of better candidate for next LTS release as it will have a longer support period, more details at https://laravel.com/docs/11.x/releases#support-policy . The most important requirement for it is `PHP 8.2+` which is also seems like a good opportunity to ship the next LTS with more actively supported PHP version  as `PHP 8.1` will be at the end of active support by next release, more details at https://www.php.net/supported-versions.php . 

The upgrade process and details does not seems to contains many high impact changes and most of those seems to be resolvable with less effort, more details at https://laravel.com/docs/11.x/upgrade . 

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10211
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4367
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1669
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/748

**Comment by asmecher** [comment]
@touhidurabir, I checked with the Technical Committee, and they didn't raise any problems with bumping our PHP base to 8.2 for OJS/OMP/OPS 3.5. They're primarily familiar with RHEL (EPEL) and Debian/Ubuntu.

**Comment by touhidurabir** [comment]
@asmecher can you review it at https://github.com/pkp/pkp-lib/issues/9892#issue-2248712326 . Unit tests are still failing as we need to update the github workflow main branch to make it phpunit test command compatible with version 11 .

**Comment by asmecher** [comment]
@touhidurabir, I think you're probably referring to [this change](https://github.com/pkp/pkp-github-actions/issues/60), which got merged last week; did it resolve the problem?

**Comment by asmecher** [comment]
I've added reviews to [ojs](https://github.com/pkp/ojs/pull/4367#pullrequestreview-2208619936) and [pkp-lib](https://github.com/pkp/pkp-lib/pull/10211#pullrequestreview-2208635274), thanks, @touhidurabir!

**Comment by touhidurabir** [comment]
> @touhidurabir, I think you're probably referring to [this change](https://github.com/pkp/pkp-github-actions/issues/60), which got merged last week; did it resolve the problem?

@asmecher that was one part but I missed [another one](https://github.com/pkp/pkp-github-actions/blob/main/.github/actions/run-unit-tests.sh#L107) where set flag `-v` not supported by PHPUnit 11 anymore . I will create a new PR soon for this .

**Comment by touhidurabir** [comment]
@asmecher tests are finally passing . Can you please take a second look , PRs at https://github.com/pkp/pkp-lib/issues/9892#issue-2248712326

**Comment by asmecher** [comment]
Thanks, @touhidurabir, I've added a review to [the pkp-lib PR](https://github.com/pkp/pkp-lib/pull/10211#pullrequestreview-2228783482). There are a couple small things to look at, but once you're satisfied, please port to OMP and OPS and let's get it merged! I appreciate the attention to detail here.

**Comment by touhidurabir** [comment]
@asmecher All tests are passing and resolved all pointed reviews at  https://github.com/pkp/pkp-lib/pull/10211#pullrequestreview-2228783482 . Just one query to review at https://github.com/pkp/omp/pull/1669#discussion_r1713384194 . If all ok, should be good to merge .

**Comment by asmecher** [comment]
All merged -- thanks, @touhidurabir!

**Comment by touhidurabir** [comment]
@asmecher do you think anything more required for this ? may be some plugins ?

**Comment by asmecher** [comment]
Nothing off the top of my head -- but I'll keep an eye out. Closing, thanks!
