### ISSUE TITLE
[OMP] Add support for submission keyword metadata in ONIX extract

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9894]
**Describe the bug**
The ONIX extract doesn't currently include submission keyword metadata. From DOAB:

> Please use DescriptiveDetail/Subject[SubjectSchemeIdentifier=20]/SubjectHeadingText or else DescriptiveDetail/Subject[SubjectSchemeIdentifier=04]/SubjectCode

**Comment by kaitlinnewson** [comment]
@asmecher This is ready for an initial review.

I noticed that currently the subjects are being pulled from all locales and combined together, so I changed that so it's only pulling in subjects from the publication's primary locale.

- OMP 3_3_0: https://github.com/pkp/omp/pull/1605

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson, I merged the PR. But just to confirm: you found documentation about ONIX with guidance about multilingual content, right? Could you link that here?

**Comment by kaitlinnewson** [comment]
[Here's the documentation on multilingual metadata in Onix](https://www.editeur.org/files/ONIX%203/APPNOTE%20Multilingual%20metadata%20in%20ONIX.pdf).

**Comment by kaitlinnewson** [comment]
@asmecher Additional ported PRs are linked above and ready for review.

**Comment by asmecher** [comment]
All merged, thanks! Closing.
