### ISSUE TITLE
Introduce APP KEY feature of Laravel

### ISSUE THREAD

**Issue by touhidurabir** [pkp/pkp-lib#9895]
**Describe the Proposal**
Introduce the Laravel like APP KEY feature/behaviour for next release of OJS/OMP/OPS . This will be a required details need to set which will be required at the app bootstrapping . 

**Additional Information**
With the merge of [Convert session and cookie management to Laravel](https://github.com/pkp/pkp-lib/issues/9566), we have the ability to make the cookie encrypted and that feature added . However we have limited chiper support for the cookie encryption because we do not have full featured app key behaviour implemented . By introducing the app key we can have bring in the full encryption support of laravel.

However this will not only have impact for cookie encryption but for any encryption and auth token generation process and we can leverage the native laravel built in functionality for that purpose . Also this does not impact with any hashing functionality e.g. password hashing . 

**Possible Implementation flow**
1. A config option named `app_key`
2. Command line tool to generate/update app key
3. config option to on/off cookie encryption
4. config option to set cipher settings e.g. aes-128-cbc/aes-256-cbc/aes-128-gcm/aes-256-gcm
5. keeping the app key optional of app bootstrapping process but required for encryption/decryption process . 
6. upgrade migration to set the app key in `app_key` variable present in the `config.inc.php` file, it will not throw error but log error in missing or failed . 

**Impacted systems**
OJS/OMP/OPS main(3.5.0 pre release)

**PRs **
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9918
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4257
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1575
[ops](https://github.com/touhidurabir/ops) --> https://github.com/pkp/ops/pull/690

**Comment by touhidurabir** [comment]
@asmecher can you review the PRs at https://github.com/pkp/pkp-lib/issues/9895#issue-2249932770

**Comment by asmecher** [comment]
Reviewed: https://github.com/pkp/ojs/pull/4257#pullrequestreview-2072664307

Once that's ready, please port to the other apps as well.

**Comment by asmecher** [comment]
Thanks, @touhidurabir! I've added some reviews:
- https://github.com/pkp/pkp-lib/pull/9918#pullrequestreview-2089030304
- https://github.com/pkp/omp/pull/1575#pullrequestreview-2088983021
- https://github.com/pkp/ojs/pull/4257#pullrequestreview-2089062722

**Comment by touhidurabir** [comment]
@asmecher changes are pushed to all apps .

**Comment by asmecher** [comment]
Sorry for the long delay, @touhidurabir, but I've [reviewed this again](https://github.com/pkp/pkp-lib/pull/9918#pullrequestreview-2149141514). It's late on a Friday so it's not as in-depth a review as I would like, but with one correction (noted in the review), it's ready for a merge and will probably get some refinement in `main` before release; please go ahead.

**Comment by touhidurabir** [comment]
completed by merging of PRs at https://github.com/pkp/pkp-lib/issues/9895#issue-2249932770
