### ISSUE TITLE
[UI] Improve TinyMCE fields

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#990]
We can adjust the formatting of text and things in TinyMCE fields. Right now the text is tiny and at odds with the rest of the UI.

I'm filing this against OMP 1.2 in the hopes I can get it in, but it's not absolutely vital.

**Comment by NateWr** [comment]
Some basic style improvements are done in [this PR](https://github.com/pkp/tinymce/pull/5).

This raised two more issues I'd like to get resolved as part of this ticket.

- [ ] The TinyMCE button tooltips often appear misplaced. This especially happens in the modal when adding a reviewer.
- [ ] TinyMCE fields get a fixed height of `140px` added to their `iframe`'s `style` attribute. It'd be great to be able to set these on a case-by-case basis. Some fields, like any of the email input fields, really need a lot more height to them.

**Comment by NateWr** [comment]
@beghelli Do you handle the TinyMCE code at all? I'm trying to track down the code which adds a fixed height of `140px` to the TinyMCE iframe but not having much success. If you've dealt with that, you have any pointers?

**Comment by NateWr** [comment]
Thanks to some help from @beghelli, [this PR](https://github.com/pkp/pkp-lib/pull/1035) makes sure that TinyMCE controls will respond appropriately to the `rows` attribute of its target textarea.

**Comment by asmecher** [comment]
@NateWr, if the rest of this entry is not crucial for OMP 1.2, can you file a new issue for 1.2.1 with the remaining elements and close this one?

**Comment by NateWr** [comment]
@asmecher There's still the misplaced tooltip issue that needs to be solved.

**Comment by asmecher** [comment]
@NateWr -- ah, OK.

**Comment by NateWr** [comment]
By sheer dumb luck I believe I finally stumbled on the cause of the offset tinymce tooltips.

PR: https://github.com/pkp/pkp-lib/pull/1218

**Comment by asmecher** [comment]
https://www.youtube.com/watch?v=p5cOqCjInYI
