### ISSUE TITLE
Database error when loading block plugins

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#992]
I've started getting a database error that kills execution on my own test site. 

![db-error](https://cloud.githubusercontent.com/assets/2306629/11933766/b707b958-a7f5-11e5-878d-d65821d32774.png)

I tracked it down to `PluginRegistry::loadCategory('blocks',true);` in the [PKPTemplateManager.inc.php](https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L227).

Anyone able to replicate?

**Comment by beghelli** [comment]
Yes, I can. Fixing it.

2015-12-21 13:17 GMT-02:00 Nate Wright <notifications@github.com>:

**Comment by beghelli** [comment]
No bug, just need to upgrade your database, due to this change: https://github.com/pkp/omp/commit/afa755bf49e869359122f6a8f98231dee977904d
