### ISSUE TITLE
[OMP] Add license data to ONIX export

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9925]
License information is not currently present in the ONIX export, and DOAB would like for it to be included.

DOAB suggests we use the following ONIX field(s):

> DescriptiveDetail EpubLicense/EpubLicenseExpression/EpubLicenseExpressionLink or DescriptiveDetail/EpubLicense/EpubLicenseName

See ONIX documentation: https://www.editeur.org/files/ONIX%203/APPNOTE%20Describing%20Open%20Access%20monographs%20in%20ONIX%203.0%20and%203.1.pdf

**Comment by kaitlinnewson** [comment]
This will require an update to the ONIX schema version, as the `<EpubLicense>` was introduced in 3.0.2 (we are using 3.0.1).

**Comment by asmecher** [comment]
@kaitlinnewson, I would support bumping to the latest 3.0.x -- that's 3.0.8, I think. Going to 3.1 would mean a bit more consultation, but 3.0.8 should be backwards-compatible with 3.0.1.

**Comment by asmecher** [comment]
Re: ONIX schema version bump: https://github.com/pkp/pkp-lib/issues/10086

**Comment by bozana** [comment]
Hi @kaitlinnewson, I merged the PR for stable-3_3_0. Can you port it to other branches?

**Comment by kaitlinnewson** [comment]
@bozana Ported and added to the list of PRs above.

**Comment by bozana** [comment]
All merged. Thanks a lot @kaitlinnewson!
Closing...
