### ISSUE TITLE
[OMP] Provide download URL in OMP ONIX export

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9926]
The download URL is not currently present in the ONIX export, and DOAB would like for it to be included.

DOAB suggests we use the following ONIX field(s):

> ProductSupply/SupplyDetail/Supplier/Website[WebsiteRole=29]/WebsiteLink or else use PublishingDetail/Publisher/Website[WebsiteRole=29]/WebsiteLink

**Comment by kaitlinnewson** [comment]
Would this be the landing page URL for the monograph (e.g. `/catalog/book/5`), or the link to download the PDF (e.g. `/catalog/download/5/1/21')? In some cases a monograph might have multiple download links, e.g. when the monograph is broken into multiple chapter files for download.

**Comment by asmecher** [comment]
The ONIX export doesn't currently include chapter data, so I would choose the landing page for the full monograph.

**Comment by kaitlinnewson** [comment]
Ready for review @asmecher 

PR to OMP 3_3_0: https://github.com/pkp/omp/pull/1593

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson, just one comment to address and it's ready to port forward: https://github.com/pkp/omp/pull/1593/files#r1642846149

**Comment by kaitlinnewson** [comment]
Ready for a second look @asmecher

**Comment by asmecher** [comment]
Sorry for being pedantic, just one more little tweak then it's ready! https://github.com/pkp/omp/pull/1593/files#r1643322822

**Comment by kaitlinnewson** [comment]
@asmecher Done and ported! PRs listed above.

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson, all merged!
