### ISSUE TITLE
[OMP] Add related ISBN data to ONIX export

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9928]
DOAB would like related ISBN data added to the ONIX export.

They recommend the following schema:

> RelatedMaterial/RelatedProduct/ProductIdentifier[ProductIDType=15]/IDValue or else RelatedProduct/ProductIdentifier[ProductIDType=15]/IDValue

This would be used to link other editions of the same book.

Related documentation:
- [ONIX Application Note: Related products and other product links](https://www.editeur.org/files/ONIX%203/APPNOTE%20Related%20products%20and%20other%20product%20links.pdf)

**Comment by kaitlinnewson** [comment]
Which ISBNs within OMP are considered to be for other editions of the same book? In the Onix export metadata, when there are multiple publication formats with different ISBNs these are all included as separate products with their own ISBN if it's included in the metadata. Is there another location for this type of ISBN?

**Comment by asmecher** [comment]
Hmm, probably a good question for DOAB. I'll get you into the appropriate Mattermost channel to ask them directly.

**Comment by asmecher** [comment]
...but as for where you can enter ISBNs in OMP: there's the publication format form...
![image](https://github.com/pkp/pkp-lib/assets/200411/eb7231ee-c746-48ec-b78c-39707fb5075d)
...and the "Product Identification" grid on the Metadata tab of the same area:
![image](https://github.com/pkp/pkp-lib/assets/200411/81037f62-e009-4fcc-84d1-f8ff877607d7)
When you enter ISBNs in the publication format edit form, they show up in the grid, i.e. they aren't different data sources.

**Comment by kaitlinnewson** [comment]
Thanks Alec - I found the place for ISBNs, but they already seem to be in the Onix export, so I'm trying to understand which ISBNs are appropriate for this "RelatedMaterial" field.

**Comment by kaitlinnewson** [comment]
PR ready for review and will forward-port once approved:

- OMP 3.3: https://github.com/pkp/omp/pull/1756

This PR collects the identifiers for all publication formats being exported, and creates a `<RelatedMaterial>` element which contains the identifiers for all other publication formats that belong to the publication. This may be an ISBN, or any other identifier.

@bozana are you able to review?

**Comment by kaitlinnewson** [comment]
@bozana forward-ported and PRs are listed above.
