### ISSUE TITLE
[UI] Fix the notifications page on the frontend

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#993]
@asmecher I've just discovered this page for the first time. Is it still a thing? Do we need to talk about what goes in and how it's managed?

If so, I'll need to fix it up and make sure it's accessible somehow from the frontend and backend.

It can be accessed at `/notification`.

- [x] LInk to modify notifications is broken
- [x] Markup and styling out-of-date
- [x] Notifications of new announcements should have titles of announcements

**Comment by beghelli** [comment]
Hi @NateWr,

If I am not wrong, the modify notification you're talking about is related to select the ones you want to receive and/or receive emails about or not. This is already moved to the user profile page, under a notification tab.

I think we only want the list of the notifications on this page. The tasks is already showing notifications that have to do with something that the user needs to perform, but notifications like the announcements have no place in the system yet.

We used to have a notifications grid in the dashboard, but I think this should also be a frontend component. Maybe a link that could live next to the tasks? So it would be in the same place for both front and back end...

**Comment by NateWr** [comment]
Ok, here's what it looks like at the moment. 

![notification](https://cloud.githubusercontent.com/assets/2306629/11935869/323eab16-a802-11e5-942b-78697b2dddba.png)

I guess we'll just need to discuss what to do with it and then do it. Just recording it for now so I don't forget.

**Comment by NateWr** [comment]
It's public too. If you log out you get all notifications, like this one:

> The monograph has been approved. Please visit Catalog to manage its catalog details, using the catalog link just above.

Is that intentional?

**Comment by beghelli** [comment]
No, I don't think so.

**Comment by asmecher** [comment]
@beghelli, how's progress on this one?

**Comment by beghelli** [comment]
Still moving operations from NotificationsHandler to the grid, also reusing some of the tasks grid code. I will try to finish this today so we can have some testing before release. I will let you know in a few hours.

**Comment by beghelli** [comment]
https://github.com/pkp/omp/pull/273
https://github.com/pkp/pkp-lib/pull/1362

Though we have to still decide where to link this page. I will show how it looks like on the meeting today and I can quickly implement what we decide there.
