### ISSUE TITLE
Make possible to open Vue.js modal from legacy grid

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9932]
**Describe the issue**
Our goal is to write new interfaces using Vue.js components. One of the cases is new or re-build modals thats being triggered from the Legacy Grid. Example of such use case is in https://github.com/pkp/pkp-lib/issues/9893 .

**Solution**
Proposing solution with new VueModal.php action as alternative to typical AjaxModal.php action, which makes possible to open Vue.js side modal, which is built as separate component from the grid action.

Steps for new modals would be
1) Create separate modal component (see WorkflowLogResponseForModal.vue as example)
2) Its necessary to register that component in ModalManager.vue, so its possible to open it by name
3) use VueModal to add the action:
```
            $this->addAction(
                new LinkAction(
                    'logResponse',
                    new VueModal(
                        'WorkflowLogResponseForModal',
                        $actionArgs // these are passed as props to modal
                    ),
                    'Log Response for'
                )
            );

```

Its often important to communicate events back to grid to trigger reload if the action changes data. This can be achieved with following pattern:

```
<script setup>
import {inject} from 'vue';
import SideModalBody from '@/components/Modal/SideModalBody.vue';
import PkpButton from '@/components/Button/Button.vue';

const props = defineProps({
	submissionId: {type: Number, required: true},
	reviewAssignmentId: {type: Number, required: true},
	legacyOptions: {type: Object, required: true},
});
const closeModal = inject('closeModal');

function submitThings() {
	// pass events to the Grid, to trigger reload if action changed the data
	props.legacyOptions.modalHandler
		.getHtmlElement()
		.trigger('dataChanged', props.reviewAssignmentId);
	closeModal();
}
</script>

```

PR (includes example that we don't want to merge unfinished, but its best to illustrate the functionality for review)
ojs: https://github.com/pkp/ojs/pull/4266
pkp-lib: https://github.com/pkp/pkp-lib/pull/9933
ui-library: https://github.com/pkp/ui-library/pull/347
omp: https://github.com/pkp/omp/pull/1568
ops: https://github.com/pkp/ops/pull/681

**Comment by jardakotesovec** [comment]
Appreciate feedback from anyone.

tagging @asmecher  @jonasraoni  @eirikhanssen @MrRob100

**Comment by jonasraoni** [comment]
I can do a late review after I get back on track (11/05). I'm just curious if you didn't intend to tag @ewhanson instead of Eirik Hanssen 😁

**Comment by MrRob100** [comment]
@jardakotesovec On my setup this it needed `lib/pkp/js/controllers/modal/VueModalHandler.js` to be registered in `minifiedScripts.txt` to work. Otherwise working well :)

**Comment by jardakotesovec** [comment]
@MrRob100 Cool, thanks for testing it out! I added PR for OJS with the updated minifiedScripts.tt

**Comment by jardakotesovec** [comment]
Cleaned up and merged
