### ISSUE TITLE
Rename Editorial Team settings field into Editorial History, and display it on the Editorial History page

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9937]
As part of JII and Editorial Masthead work, it was decided to rename the current context settings field Editorial Team into Editorial History. 
It will not be a navigation menu item any more. 
Now there is Editorial Masthead navigation item, s. https://github.com/pkp/pkp-lib/issues/9860.
On Editorial Masthead page there will be a link to the Editorial History page. It should list all ended editorial masthead services i.e. all masthead roles as well as uses that were active and are not active any more in those masthead roles and that have accepted to be listed on masthead. S. https://github.com/pkp/pkp-lib/issues/9914. At the end of the Editorial History page, the content of the new Editorial History (and old Editorial Team) field should be displayed.

PRs:
- https://github.com/pkp/pkp-lib/pull/9943
- https://github.com/pkp/ojs/pull/4271
- https://github.com/pkp/omp/pull/1565
- https://github.com/pkp/ops/pull/680
- still to remove primaryNavMenu.tpl from theme plugins...

**Comment by bozana** [comment]
@asmecher, could you maybe review these PRs as well?

**Comment by asmecher** [comment]
Hi @bozana! I see the changes to remove/rename editorial team, but I don't see the changes to present editorial history anywhere... Are those coming in a separate changeset, or did I miss them here?

**Comment by bozana** [comment]
Ah, yes, there is a separate issue: https://github.com/pkp/pkp-lib/issues/9914 -- this issue introduced the new Editorial History page and this new Editorial History field should be displayed at the end of that page. So yes, I was waiting for that issue to get merged first in order to just display this field there.
Or maybe I can merge those two issues?

**Comment by bozana** [comment]
I moved all the work from this issue into https://github.com/pkp/pkp-lib/issues/9914, thus closing...
