### ISSUE TITLE
Remove the option of "Cancel Review Assignment" after the Review has been declined

### ISSUE THREAD

**Issue by Devika008** [pkp/pkp-lib#9948]
**Describe the problem you would like to solve**
Currently in the OJS workflow, if a reviewer has declined the the review request, the editor still has an option to cancel the review.

![Image](https://github.com/pkp/pkp-lib/assets/112014397/e6c94c8c-42e5-4c98-b832-c13bc3761c55)

After the reviewer has been cancelled.

![Image](https://github.com/pkp/pkp-lib/assets/112014397/f6e5b514-43bf-4d69-804c-f0ea6929b7e4)

If the cancelled review has been reinstated

![Image](https://github.com/pkp/pkp-lib/assets/112014397/d0eb0a3a-6d0e-4faf-b0e3-8f6f0cbd07b9)

As you can see, the cancel functionality doesn't provide any value to a declined review. It's not tracked in the review history either. I believe it simply adds unnecessary actions to the review process without any benefit.

**Describe the solution you'd like**
To remove the "cancel" function from a declined review and let the case be as declined

Who is asking for this feature?
@Devika008 @jardakotesovec 

**PRs**
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/10422
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4440 [TEST ONLY]
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1702 [TEST ONLY]

**Comment by touhidurabir** [comment]
@Vitaliy-1 can you please check the PRs at https://github.com/pkp/pkp-lib/issues/9948#issue-2286360215

**Comment by touhidurabir** [comment]
fixed by https://github.com/pkp/pkp-lib/pull/10422 .
