### ISSUE TITLE
Add support for laravel pagination pattern in useFetchPaginated

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9950]
**Describe the issue**
On most APIs, which support pagination, we pass offset and count and we get itemsMax and items. 

But we also have (for example jobs api - /index.php/index/api/v1/jobs/all) laravel specific pattern. Which is using page&perPage query params and return `data` and `total`.

From discussion on mattermost it seems that we will have both patterns coexist for some time. But feel free to add more context about how the transition is going to happen. 

**Solution**

Therefore adding newer laravel pattern to be supported also in [useFetchPaginate](https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/composables-usefetchpaginated--docs). Given that these endpoints don't mind receiving some additional query params, I can simply always send both and based on the response fields to detect which pattern is used.

As result it won't make difference to frontend developer, when using useFetchPaginate which convention the API is using.

**Comment by jardakotesovec** [comment]
ui-library PR: https://github.com/pkp/ui-library/pull/348

@eirikhanssen Can I ask you for code review? Thank you!

**Comment by ewhanson** [comment]
Hey @jardakotesovec, I took a look and everything looks good to me! 👍 Just had a few questions in order to better understand some of the changes, but nothing that would require changes. Thanks!

**Comment by jardakotesovec** [comment]
@ewhanson Thank you, merged.
