### ISSUE TITLE
[UI] Style forgotten frontend pages

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#996]
- frontend/pages/userRegisterSite.tpl (multi-context registration landing page)
- frontend/pages/notification.tpl #993 
- frontend/pages/error.tpl
- frontend/pages/message.tpl

**Comment by NateWr** [comment]
Some notes on the `frontend/pages/userRegisterSite.tpl` template from Alec:

> In OJS, try...
- Create at least two journals
- Navigate to the site-wide homepage, where you should see a list of journals.
- Click "Register".

> You should be forced to pick a journal to register with.

> FWIW, on your Profile form, when you're browsing from a particular journal context you should see a "Show Other Journals" link in the Roles area. There you can control your role selection for journals outside the one you're currently browsing from. This currently needs some styling.

**Comment by NateWr** [comment]
@asmecher or @beghelli Do you know under what conditions the following page templates might be displayed?

```
frontend/pages/error.tpl
frontend/pages/message.tpl
```

**Comment by beghelli** [comment]
@NateWr It seems that error.tpl is used by the PKPLoginHandler when there's a problem resetting the user password or an user is trying to login as an user and it has no authorization to do that. It's also used by the RegistrationHandler to show any reason for a failing registration operation.

And the message.tpl is a generic template that's used to show a message to the user. It's mainly used by plugins, but some core handlers like the UserHandler are also using it.

I just did a grep to check where its used, but I didn't see it in action. But if you follow the examples and the handlers I told, you should be able to check that.

**Comment by asmecher** [comment]
frontend/pages/error.tpl:

- If a user tries to self-register, but the journal/press doesn't allow it (`lib/pkp/pages/user/RegistrationHandler.inc.php::validate`)
- If a user tries to login at the end of the registration process but their account has been disabled (`lib/pkp/pages/user/RegistrationHandler.inc.php::validate`)
- If a user tries to sign in as another user, but doesn't have sufficient rights over their account (`lib/pkp/pages/login/PKPLoginHandler.inc.php::signInAsUser`)
- If a user follows the password reset process but the hash couldn't be verified (`lib/pkp/pages/login/PKPLoginHandler.inc.php::resetPassword`)

**Comment by NateWr** [comment]
PRs:

https://github.com/pkp/pkp-lib/pull/1112
https://github.com/pkp/ojs/pull/736
https://github.com/pkp/omp/pull/210

These dont' deal with the notifications page, but that's handled in a separate ticket #993.
