### ISSUE TITLE
VS Code Error due parsing too many files

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9972]
**Describe the bug**
Recently I was getting following error in vs code:

```

To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on.
```

As result some JS features did not work on some files. Per my testing the root cause was that the jsconfig was just excluding top level node_modules. Solution that is working well is to point jsconfig to src folders.

**Solution**
Refine jsconfig.json to make sure vs code is dealing just with the source files

**What application are you using?**
 OJS, OMP or OPS main

**Comment by jardakotesovec** [comment]
OJS PR: https://github.com/pkp/ojs/pull/4279

Will add PRs for OMP and OPS after review.

@ewhanson Could you have a look?

**Comment by ewhanson** [comment]
Just one question in the PR, but otherwise looks good! 👍
