### ISSUE TITLE
Display Galley language in the grid

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#9976]
In OJS and OPS the Galley grid only shows the Galley label. In multilingual journals an article might have full text files in more than one language and finding out what language versions have been added to the grid requires editing the Galley.

The suggestion is to display the Galley language in the grid.

<img width="921" alt="Näyttökuva 2024-5-21 kello 18 32 19" src="https://github.com/pkp/pkp-lib/assets/16347527/92f99c85-f491-4f85-98a6-2094e5bbb84a">

**Comment by ajnyga** [comment]
OJS: https://github.com/pkp/ojs/pull/4283

**Comment by asmecher** [comment]
@bozana, would you mind reviewing the above? Thanks!

**Comment by ajnyga** [comment]
OPS: https://github.com/pkp/ops/pull/687
OJS: https://github.com/pkp/ojs/pull/4283

**Comment by bozana** [comment]
Thanks a lot @ajnyga! I have merged it, so I will close the issue...

**Comment by ajnyga** [comment]
cheers
