### ISSUE TITLE
Make easier to check for success when using useFetch

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9977]
**Describe the issue**
With introduction of Vue.js composition API - we also introduced couple of composables, including [useFetch](https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/composables-usefetch--docs) to handle the API interactivity. 

Scenario where I think it currently falls short is if you make a POST and if thats successfull you want to do some additional action (close modal, open notification,...).  If the POST does not provide meaningful response other than 200 http code - than currently there is no easy way to check it went well other than checking data being null, which I don't think it clear enough - especially considering that POST return empty response.  

**Proposed solution**

Add computed property isSuccess to useFetch, which can be used to check whether the response was successful (http code 200).

**Comment by jardakotesovec** [comment]
@ewhanson Can you I ask you for another small PR check? :-)

ui-library: https://github.com/pkp/ui-library/pull/355

**Comment by ewhanson** [comment]
Just one question in the PR, otherwise looks good! 👍

**Comment by jardakotesovec** [comment]
Merged, closing.
