### ISSUE TITLE
Upgrade OJS 2.4.8-4 to 3.2.1-4:  Error when change datatype of email subject to TEXT

### ISSUE THREAD

**Issue by leho-dev** [pkp/pkp-lib#9978]
**Describe the bug**
I try to upgrade OJS from 2.4.8-4 to 3.2.1-4. In all tables of email in 2.4.8-4, I change the datatype of the subject from varchar(120) to TEXT, name of the tables are `email_log`, `email_templates_data`, `email_templates_default_data`.

![image](https://github.com/pkp/pkp-lib/assets/82250843/ccfa3a2b-5449-443a-916f-eea2f7442ba2)

And when I run `php -d memory_limit=2048M tools/upgrade.php upgrade`, I have an error: 

![image](https://github.com/pkp/pkp-lib/assets/82250843/99aeebe3-2b82-46f9-8c27-8e621fb25722)

I have enabled debug output and the error below:

![image](https://github.com/pkp/pkp-lib/assets/82250843/52e96f4a-cc3b-45a9-a747-37226e1d7e24)

Can I change the datatype of subject email to TEXT in 3.2.1-4?

**To Reproduce**
I follow [this guide](https://docs.pkp.sfu.ca/dev/upgrade-guide/en/#9-run-the-upgrade) and have an error in step 9, I have researched but seems no problem is similar. 

**What application are you using?**
 OJS version 2.4.8-4

**Comment by asmecher** [comment]
@leho-dev, you'll also need to edit `lib/pkp/xml/schema/log.xml` and change the type/length of the `subject` field to a longer type there. This isn't really a bug -- it's the result of an incomplete modification -- so next time it's probably better to post on our support forum with questions like this. That's available at https://forum.pkp.sfu.ca.
